### ISSUE TITLE
User sign in saying can't enter personal email

### ISSUE THREAD

**Issue by SabirHossain** [AzureAD/microsoft-authentication-library-for-js#1003]
#607 
 Current behavior
When the pop up windows come and enter an Microsoft account email it saying I can't use personal account here, but the app from your repository is working fine.

## Expected behavior
It should show the same login pop up as your project.

## Minimal reproduction of the problem with instructions
In AppModule
```
       MsalModule.forRoot({
            clientID: "8_my_id_f",
            authority: "https://login.microsoftonline.com/common/",
            validateAuthority: true,
            redirectUri: "http://localhost:4200/",
            cacheLocation: "localStorage", 
            postLogoutRedirectUri: "http://localhost:4200/",
            navigateToLoginRequestUrl: true, 
            consentScopes: ["user.read", "openid", "profile", "api://a88bb933-319c-41b5-9f04-eff36d985612/access_as_user"],
            unprotectedResources: ["https://www.microsoft.com/en-us/"],
            protectedResourceMap: protectedResourceMap,
            correlationId: '1234',
            piiLoggingEnabled: true
      }),
```
Opening the login popup
```
       if (isIE) {
            this.authService.loginRedirect();
        } else {
            this.authService.loginPopup();
        }
```

Your app redirect to https://login.microsoftonline.com/common/oauth2/authorize
and mine to https://login.microsoftonline.com/common/oauth2/v2.0/authorize

What should I do to get the access token for any user ? in my app I want import outlook contacts because my clients uses outlook and want to import contact and email from outlook?

**Comment by jasonnutter** [comment]
@SabirHossain It's possible your application is only configured to allow users to sign in from your tenant. To confirm, login to the [Azure Portal](https://portal.azure.com), go to "Azure Active Directory", "App registrations", open the app registration for your app, then go to "Authentication", and then scroll to the bottom to "Supported account types". Which option is selected? 

Example:
![azure_portal_directories](https://user-images.githubusercontent.com/443409/65440048-0309de00-dddd-11e9-8f4e-9be20c8a7f45.PNG)

**Comment by SabirHossain** [comment]
> @SabirHossain It's possible your application is only configured to allow users to sign in from your tenant. To confirm, login to the [Azure Portal](https://portal.azure.com), go to "Azure Active Directory", "App registrations", open the app registration for your app, then go to "Authentication", and then scroll to the bottom to "Supported account types". Which option is selected?
> 
> Example:
> ![azure_portal_directories](https://user-images.githubusercontent.com/443409/65440048-0309de00-dddd-11e9-8f4e-9be20c8a7f45.PNG)

This my Authentication setting in Azure Active Directory app registration.
![image](https://user-images.githubusercontent.com/23700852/65443669-5cf7bb80-de50-11e9-8b9f-eb1727ba5443.png)

**Comment by jasonnutter** [comment]
@SabirHossain Can you please share an image of the error message you are seeing?

**Comment by SabirHossain** [comment]
@jasonnutter 
This is the error I get

![ms_login_error](https://user-images.githubusercontent.com/23700852/65620171-2ef6b080-dfe3-11e9-8f3b-e7af48f72cb0.png)

**Comment by jasonnutter** [comment]
@SabirHossain Ah, in order to be able to use personal Microsoft accounts, you must **Accounts in any organizational directory (Any Azure AD directory - Multitenant) and personal Microsoft accounts (e.g. Skype, Xbox)** when registering the application (screenshot below). Unfortunately, I don't believe you can change this option once you have registered the application, so you will need to register a new application with this option selected.

![Annotation 2019-09-30 102359](https://user-images.githubusercontent.com/443409/65901281-bbe79400-e36c-11e9-939a-c45f6c2ff06f.png)

**Comment by SabirHossain** [comment]
@jasonnutter Yes that was the issue, now it's working as expected, Thank you for your response.
