### ISSUE TITLE
PWA, loginpopup ends with about:blank

### ISSUE THREAD

**Issue by abegines** [AzureAD/microsoft-authentication-library-for-js#1006]
## I'm submitting a...

<pre><code>
[x] Bug report  
</code></pre>

## Browser:
PWA in android with Chrome (Add To Home Screen)

## Library version

<pre><code>
Library version: 1.0.0 a 1.1.2
</code></pre>

## Current behavior
When I use my page from the browser, the loginPopup process works fine (show popup, signin, back to app window...)
But when I use my page from icon created with "Add to Home Screen" the popup window shows nothing (about:blank).

## Expected behavior
Same behavior in browser mode or in PWA mode (standalone)

## Minimal reproduction of the problem with instructions

Create this little application, with one manifest indicating `"display": "standalone"` and test in Android phone creating the shortcut with "Add to home screen" from Chrome.

```html
<!DOCTYPE html>
<html>
  <head>
    <title>PWA + LOGIN MICROSOFT TEST</title>
    <meta charset='utf-8' />
    <link rel="manifest" href="/manifiesto.json">
    <script src="https://secure.aadcdn.microsoftonline-p.com/lib/1.1.2/js/msal.js"></script>
    <script type="text/javascript">
    
      let __msalInstance = undefined;
      const __msalConfig = {
        auth: { clientId: "f7d9d4ca-f66c-42b9-9181-XXXXXXXX" }
      };

      const __loginRequest = {
        scopes: ["user.read"] ,
        prompt: 'select_account',
      }
      __msalInstance = new Msal.UserAgentApplication(__msalConfig);

      function login()
      {
        __msalInstance.loginPopup(__loginRequest).then(logged);
      }

      function logged(loginResponse)  {
        console.log('onLoged=', loginResponse)
      }
    </script>

  </head>

  <body>
    <button onclick="login();">LOGIN</button><br>
  </body>
</html> 
```

**Comment by sameerag** [comment]
@abegines MSAL JS does not support PWAs yet. We are currently only supporting full browser environments.

**Comment by abegines** [comment]
The problem is that PWA does not allow communication with the pop-up window after being created.

MSAL creates the pop-pup by pointing to "about: blank" and then tries to replace its location ...

```javascript
popUpWindow = this.openWindow("about:blank", "_blank", 1, this, resolve, reject);
calls...
popupWindow = this.openPopup(urlNavigate, title, Constants_1.Constants.popUpWidth, Constants_1.Constants.popUpHeight);
calls...
var popupWindow = window.open(urlNavigate, title, "width=" + popUpWidth + ", height=" + popUpHeight + ", top=" + top + ", left=" + left);


_this.navigateWindow(urlNavigate, popUpWindow);
calls...
navigateWindow.location.replace(urlNavigate);
```

I have created a minimal application to reproduce the problem outside MSAL: create a simple a popup (window.open) and change location after (location.replace). And it gives the same result: in PWA the location isn't changed.

I have workaround the problem using the loginRedirect method (which have other pitfalls). 

Anyway, the Google authentication API uses pop-ups and it works. I guess they communicate with the pop-up in a different way.

**Comment by himadrinath** [comment]
https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/984#issuecomment-532990004

**Comment by nakawankuma** [comment]
Hi. 
I have same incident.
I have application is Microsoft Office onenote addin.
I addin include onenote page that allow  create loginPopup on chrome. but not ran Edge browser.

I try 
            navigateWindow.location.assign(urlNavigate);
but not ran.

**Comment by nakawankuma** [comment]
I replace this code. but dont check side effect.
https://github.com/AzureAD/microsoft-authentication-library-for-js/commit/66acdd57c926f2c3cf615194779ba50ef10231b1

**Comment by nakawankuma** [comment]
I Changed mistake.

"ClientAuthError: Nonce is not matching, Nonce received: 2917b477-aef0-435f-918e-506643f8844e, nonce expected : f33d9f23-130f-46c9-89d0-fa3376abf8d6. at UserAgentApplication.prototype.saveTokenFromHash (https://localhost:3000/taskpane.js:146702:13) at UserAgentApplication.prototype.processCallBack (https://localhost:3000/taskpane.js:146106:13) at a.open (https://appsforoffice.microsoft.com/lib/1.1/hosted/onenote-web-16.00.js:24:120500) at UserAgentApplication.prototype.openPopup (https://localhost:3000/taskpane.js:145842:13) at UserAgentApplication.prototype.openWindow (https://localhost:3000/taskpane.js:145757:13) at Anonymous function (https://localhost:3000/taskpane.js:145586:17) at invokeCallback (https://localhost:3000/taskpane.js:16986:7) at publish (https://localhost:3000/taskpane.js:16969:7) at flush (https://localhost:3000/taskpane.js:16706:5)"

umm.

**Comment by himadrinath** [comment]
We are still having this issue. It's frustrating. It's unpredictable some time it's works and most of the time it's doesn't work.

**Comment by jasonnutter** [comment]
We've been working on some other things, but we will make sure this gets fixed, as we want PWAs to be a properly supported.

**Comment by himadrinath** [comment]
@jasonnutter :+1:

**Comment by pkanher617** [comment]
@abegines @himadrinath @nakawankuma Is this issue still persisting after upgrading to msal v1.3.0?

**Comment by himadrinath** [comment]
@pkanher617 @jasonnutter looks like the issue is fixed
