### ISSUE TITLE
[Documentation]: obtain an AAD token with MSAL.js to call Azure

### ISSUE THREAD

**Issue by legomushroom** [AzureAD/microsoft-authentication-library-for-js#1008]
Hello,

Currently, our SPA uses MSAL.js for authentication and we are getting AAD v2 tokens with an `aud` claim that our services can accept. Now we have the need to list all the `subscriptions`/`resource groups` a user might have. I'm trying to understand how to change the MSAL.js config to be able to get a token that is capable to do the requests to Azure and, unfortunately, cannot find anything close to that.

#### Question: Are there any examples of how to get an AAD token that can do the requests to list Azure resources? Is it possible with MSAL.js 3rd party app?

Thanks!

**Comment by jasonnutter** [comment]
I think you should check out [azure-sdk-for-js](https://github.com/Azure/azure-sdk-for-js) (which uses `msal`).

**Comment by jmckennon** [comment]
Closing this issue, as it's been some time and I'm assuming the issue has been resolved. Feel free to open a new issue if you have further questions.
