### ISSUE TITLE
Creating new client application (.then) promise / auto login

### ISSUE THREAD

**Issue by DonBeck69** [AzureAD/microsoft-authentication-library-for-js#101]
I find that when creating a new client application, a few seconds passes before the component is ready. Clicking a login button to sign (_clientApplication.loginPopup) in throws this exception
"angular.js:14525 TypeError: Cannot read property 'loginPopup' of undefined", because the component is not yet created. Wait few seconds and it works fine. 

I would like to something like this

            _clientApplication = new Msal.UserAgentApplication(clientId, null, authCallback).then(function () {
                //show log in button
            });

Also I would like to allow "Auto" login?

**Comment by rohitnarula7176** [comment]
@DonBeck69 The constructor does not return a promise so you cannot use the .then on it. Please refer to the samples here on how to use the api's. https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/devApps/VanillaJSTestApp/index_LoginRedirect.html. Auto-login feature cannot be provided as part of the library. You will have to write custom code for it.

**Comment by rohitnarula7176** [comment]
@DonBeck69 Closing this issue for now. Please reopen if you still face any issues.
