### ISSUE TITLE
Release blog post for msal 1.2.0

### ISSUE THREAD

**Issue by sameerag** [AzureAD/microsoft-authentication-library-for-js#1014]
@negoe to track the blogpost content for the upcoming msal js release `1.2.0`

**Comment by DarylThayil** [comment]
@sameerag  is this still in progress ?

**Comment by sameerag** [comment]
I have the content ready. Since the betas are in progress, I haven't been able to close it. Will send it for review next week once we have beta-4 released.

**Comment by sameerag** [comment]
All fixes for cache now are merged into dev. Targeting 1.2.0 release this week.

**Comment by sameerag** [comment]
Placeholder currently is https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL-JS-1.2.0; This will be probably changed a little this week once the team reviews it.

**Comment by sameerag** [comment]
Closing this as the PR is in progress in ADO.
