### ISSUE TITLE
Add detailed error messaging when Service times out during token requests

### ISSUE THREAD

**Issue by sameerag** [AzureAD/microsoft-authentication-library-for-js#1015]
We swallow STS errors today in `msal js` if we do not receive error as a fragment in the redirect response from the service for a token request. 

This issue is for the library to allow for more detailed error description:  by providing the URL `msal js` is navigating to, which would instruct the developer to open the URL in a separate window, facilitating for the next steps to be taken to resolve the same.

**Comment by sameerag** [comment]
#1068 merged to dev now.

**Comment by navzam** [comment]
@sameerag Does this also address #699 where `acquireTokenSilent()` does not detect the `interaction_required` errors when they're sent via query parameters? I'm still seeing that issue. Happy to open a new issue if that's better

**Comment by sameerag** [comment]
Can you please share the repro steps @navzam? We are curious regarding the specific set of errors that may cause this and work on the mitigation.

**Comment by sameerag** [comment]
And yes, please open a new issue.
