### ISSUE TITLE
Change the Signing secret key

### ISSUE THREAD

**Issue by foramkumar-parekh** [AzureAD/microsoft-authentication-library-for-js#1017]
I have a scope in the msal and the authorization token gets generated for that scope. I am using Microsoft easy auth on the other side to validate the token.

1) I wanted to know if I can update the secret signing key for the authorization token?

2) As I am using Microsoft easy auth on the other side to validate the token, is it possible that we can encrypt the token or the values inside the token and still get the token validated and get the necessary information from the token?

If any of these features are not available, can I know if these are in the pipeline and also share the ETA if any?

**Comment by jasonnutter** [comment]
1. Are you asking if you can use a different secret key to sign access tokens? The answer to that would be no, as the signature generated/verified by MSFT proves the authenticity of the token.
2. We do not encrypt tokens, instead using signatures to verify that they haven't been tampered with.

And I would not expect either of these features to be implemented.
