### ISSUE TITLE
Example with ASP .NET Core Web Application angular template

### ISSUE THREAD

**Issue by devna13** [AzureAD/microsoft-authentication-library-for-js#1018]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[x ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

Need an example with ASP .NET Core Web Application angular template:
after successful login, angular app web api request passes the access & idtoken token back to the web api that is protected with [Authorize] attribute and web api can extract username from the claims ( to do some audit logging etc..) and make calls on behalf of user.

**Comment by tommygeek103** [comment]
Here is a simple sample project I did a few days ago - if you have further questions contact me. Don't forget to set your client id
[msal_poc.zip](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/3671161/msal_poc.zip)

**Comment by jasonnutter** [comment]
@devna13 We have a sample for ADAL.js that uses Angular and ASP.net: https://github.com/Azure-Samples/active-directory-angularjs-singlepageapp

That said, we are working on investing more in our samples, including updating ADAL samples to use MSAL. 

The feedback is appreciated, closing as nothing immediately actionable, thanks!

**Comment by devna13** [comment]
Thanks @tommygeek103 !

> Here is a simple sample project I did a few days ago - if you have further questions contact me. Don't forget to set your client id
> [msal_poc.zip](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/3671161/msal_poc.zip)
