### ISSUE TITLE
handleLoginRedirectCallback execute before it should

### ISSUE THREAD

**Issue by alexandrtovmach** [AzureAD/microsoft-authentication-library-for-js#1019]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Browser:
- [x] Chrome version 77
- [x] Firefox version 69

## Library version

<pre><code>
Library version: 1.1.3
</code></pre>

#### If user already loggedin in browser:
`handleRedirectCallback` executing before actual redirect and never execute after end of login (in both cases success / error)
![image](https://user-images.githubusercontent.com/28801003/65767225-eb608b80-e135-11e9-94b0-05d706d92d87.png)

#### If user not loggedin in browser:
`handleRedirectCallback` never execute
![image](https://user-images.githubusercontent.com/28801003/65767279-134fef00-e136-11e9-9654-be0b30bb475f.png)

#### If user already loggedin in browser:
Execute `handleRedirectCallback` after auto redirect login

#### If user not loggedin in browser:
Execute `handleRedirectCallback` after manual redirect login

## Minimal reproduction of the problem with instructions

1. Create React App (SPA)
2. Simple code:
```
  redirectLogin(msalInstance: any, scopes: string[]) {
    msalInstance.handleRedirectCallback(() => {
      console.log('handleRedirectCallback');
    });
    console.log('loginRedirect');
    msalInstance.loginRedirect({ scopes });
  }
```

**Comment by jasonnutter** [comment]
@alexandrtovmach `handleRedirectCallback` should not be registered in the same function that triggers the actual redirect, and should instead get registered on initial page load (because it needs to run when the page first loads after returning from a redirect). In a React application, you can do this by putting that callback inside `componentDidMount`, as demonstrated in our React sample application: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/react-sample-app/src/AuthProvider.js#L123

**Comment by alexandrtovmach** [comment]
@jasonnutter Okay, thank you for a quick response, I'll check it on Monday. Hope it helps)

**Comment by alexandrtovmach** [comment]
@jasonnutter Thank you, it works, but it still has additional page reload that not allow me to continue handling response. In this code "step two" will never show in case of additional page reload after successful redirect:
```
msalInstance.handleRedirectCallback(
	(error: AuthError, authResponse: AuthResponse) => {
		console.log("step one");
		setTimeout(() => console.log("step two"), 1000);
	}
)
```

**Comment by alexandrtovmach** [comment]
UPD: I found `navigateToLoginRequestUrl` property in [this comment](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/react-sample-app/src/AuthProvider.js#L126) my fault

thank you for help
