### ISSUE TITLE
window.load Fired Multiple Times with loginRedirect - Maybe related to acquireTokenSilent?

### ISSUE THREAD

**Issue by spottedmahn** [AzureAD/microsoft-authentication-library-for-js#102]
I forked the [MSAL.js SPA Sample](https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp) and tried using `loginRedirect` instead of `loginPopup`.  The problem I'm having is that sometimes the window.onload event is firing multiple times.  It seems to correspond to the call to `acquireTokenSilent`.

Is there a working sample using `loginRedirect` for a SPA app?

Why is window.onload firing twice sometimes?  Seems to be a timing bug/issue.

[This branch](https://github.com/spottedmahn/active-directory-b2c-javascript-msal-singlepageapp/tree/mine-2) has my minor changes plus some logging code to try to track this down.

### Overview of my Changes ###

```js
function login() {
            clientApplication.loginRedirect(applicationConfig.b2cScopes);
        }
```
```js
var clientApplication = new Msal.UserAgentApplication(applicationConfig.clientID, applicationConfig.authority, (errorDesc, token, error, tokenType) => {
            // Called after loginRedirect or acquireTokenPopup
            console.info('cacheLocation (B): ' + clientApplication.cacheLocation);
            //updateUI();

            this.clientApplication.acquireTokenSilent(applicationConfig.b2cScopes).then(async accessToken => {
                console.debug('Got an access token - 1');

                updateUI();
            });

        }, { cacheLocation: 'localStorage' });

console.info('cacheLocation (A): ' + clientApplication.cacheLocation);

```

```js
window.onload = function () {
            console.info('PAGE LOADED');
        }
```
### Sometimes I get the expected flow ###

![image](https://user-images.githubusercontent.com/14079228/28738537-126a5e7e-73c2-11e7-9277-aebba908aecd.png)

### Sometimes I see 2 page load events fired ###

![image](https://user-images.githubusercontent.com/14079228/28738553-1de0d0f8-73c2-11e7-93d4-a1d3600080d2.png)

**Comment by rohitnarula7176** [comment]
@spottedmahn window.onload event should be fired twice and it is expected behavior. The first time it is fired is during login and second time is fired during acquireTokenSilent. In both method calls, you get redirected to the authorization endpoint and then get redirected back to your app's root page with the idtoken/access_token which causes the page reload. If you set your redirectUri to something other than your app's root page, you can prevent these reloads. Closing this issue.

**Comment by spottedmahn** [comment]
Hi @rohitnarula7176 thanks for the response!

>The first time it is fired is during login and second time is fired during acquireTokenSilent

I must be misunderstanding something then.  I thought `acquireTokenSilent` would make an AJAX call if the user is signed in, no?  If Msal.js has a valid `id_token` why would it need to redirect the user back to B2C?

Won't this redirect design be a problem for SPA apps?  I could loose user data, no?  If the user is signed-in, they are filling out something, their access token expires, redirecting away will lose all of their state.

>If you set your redirectUri to something other than your app's root page, you can prevent these reloads

Why would this change the behavior?  I don't see the connection here.

---

PS, the delayed response does not imply this is low priority to me.  I had to work on other parts of our B2C implementation and now I'm back on the browser working on this part.

**Comment by rohitnarula7176** [comment]
@spottedmahn The redirect for the access_token happens in a hidden iframe which is different than the main page. The app gets reloaded in the iframe scope on redirect but the state of the parent page should be preserved. The state of the main page differs from the iframe and should stay unaffected. I hope this answers your question.

**Comment by spottedmahn** [comment]
Hi @rohitnarula7176 - that makes sense; I should only see one-page load event fired on the main page.  I'll double check my sample app and make I'm not setting the 2nd-page load event from the `IFRAME`.

**Comment by spottedmahn** [comment]
@rohitnarula7176 any chance you can re-open this for now?  thanks!

**Comment by drewf7** [comment]
Just adding here in case anyone else stumbles across this while googling.

For my use case at least (Angular 7). Not only did I have to specify a separate callback page (just a blank component/page), but I _also_ had to set the "navigateToLoginRequestUrl" property to false.

So my msalConfig looked like the below
`
msalConfig: any = {
    auth: {
        clientId: <client_id>
        authority: <authority>
        redirectUri: "https://localhost:4200/callback",
        validateAuthority: false,
        navigateToLoginRequestUrl: false
    },
    cache: {
        cacheLocation: "localStorage",
        storeAuthStateInCookie: true
    },
  };
`
Once I did that loginRedirect behaved as I would have expected it too.
