### ISSUE TITLE
Unhandled Rejection (TypeError): Cannot read property 'accessToken' of undefined

### ISSUE THREAD

**Issue by jerdobi** [AzureAD/microsoft-authentication-library-for-js#1021]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ x] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version
0.1.0
<pre><code>
Library version: X.Y.Z

</code></pre>

## Current behavior

Pressing the Login button and then throws error.

## Expected behavior

Not to throw exception

## Minimal reproduction of the problem with instructions

×
Unhandled Rejection (TypeError): Cannot read property 'accessToken' of undefined
AuthProvider._callee2$
D:/microsoft-authentication-library-for-js-dev/microsoft-authentication-library-for-js-dev/samples/react-sample-app/src/AuthProvider.js:15
  12 | // If you support IE, our recommendation is that you sign-in using Redirect APIs
  13 | const useRedirectFlow = isIE();
  14 | 
> 15 | export default C =>
  16 |     class AuthProvider extends Component {
  17 |         constructor(props) {
  18 |             super(props);
View compiled
▼ 5 stack frames were expanded.
tryCatch
D:/microsoft-authentication-library-for-js-dev/microsoft-authentication-library-for-js-dev/samples/react-sample-app/node_modules/regenerator-runtime/runtime.js:45
Generator.invoke [as _invoke]
D:/microsoft-authentication-library-for-js-dev/microsoft-authentication-library-for-js-dev/samples/react-sample-app/node_modules/regenerator-runtime/runtime.js:264
Generator.prototype.<computed> [as next]
D:/microsoft-authentication-library-for-js-dev/microsoft-authentication-library-for-js-dev/samples/react-sample-app/node_modules/regenerator-runtime/runtime.js:98
asyncGeneratorStep
D:/microsoft-authentication-library-for-js-dev/microsoft-authentication-library-for-js-dev/samples/react-sample-app/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:3
_next
D:/microsoft-authentication-library-for-js-dev/microsoft-authentication-library-for-js-dev/samples/react-sample-app/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:25
▲ 5 stack frames were expanded.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.

**Comment by jasonnutter** [comment]
@jerdobi Ah I see in the `react-sample-app` where this could happen, I'll make sure it gets fixed, thanks!

**Comment by jerdobi** [comment]
Cool!

I’m in studio a and doing a Linux site in react.  I will keep in touch!

Gary
Gawood@microsoft.com
