### ISSUE TITLE
Browser back button new login attempt results in error.

### ISSUE THREAD

**Issue by chr1soscl** [AzureAD/microsoft-authentication-library-for-js#1025]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [X] Chrome version 75.0.3770.90

## Library version

<pre><code>
"@azure/msal-angular": "^0.1.4"

</code></pre>

## Current behavior

I successfully login and I am redirected to my landing page, I click the browser back button and I am taken to the login page again, then I try to login again but I get an error:
<pre><code>
Nonce Mismatch. Expected Nonce: 123,Actual Nonce: 1234 
</code></pre>
In my landing page I have a navbar with some links to other pages, if I do right click to one of those links and open a new tab, I am also prompted to the login page, if I login there, no error is trigger in that new tab.
## Expected behavior

User should be able to use the back button.

**Comment by sameerag** [comment]
@chr1soscl I suspect this is happening because the intermittent cache created by a request is not cleaned on some error cases. We are working on a PR that remedies this and please watch out this space for the PR number and the update. 

Also can you please move to the latest MSAL version 1.1.3 (or upcoming 1.2.0 if you want to wait).

Thanks for raising this issue.

**Comment by chr1soscl** [comment]
> @chr1soscl I suspect this is happening because the intermittent cache created by a request is not cleaned on some error cases. We are working on a PR that remedies this and please watch out this space for the PR number and the update.
> 
> Also can you please move to the latest MSAL version 1.1.3 (or upcoming 1.2.0 if you want to wait).
> 
> Thanks for raising this issue.

this is the last version I am able to install from npm:
<pre><code>
"@azure/msal-angular": "^0.1.4"
</pre></code>

**Comment by sameerag** [comment]
@chr1soscl This is fixed in the `msal` beta: `1.2.0-beta.2`. As you know, the `angular` version of the library is being worked upon currently to be compatible with the latest `msal js` and this should be addressed in the process. cc @jasonnutter for awareness.

**Comment by sameerag** [comment]
@chr1soscl Closing this issue as we have fixed this in the recent versions of `msal js`. Please raise a new issue if you still find this not working.
