### ISSUE TITLE
Add sample for conditional access 

### ISSUE THREAD

**Issue by PraveenVerma17** [AzureAD/microsoft-authentication-library-for-js#1026]
## I'm submitting a...

[ ] Documentation issue or request
</code></pre>

## Library version

<pre><code>
Library version: 1.2.0-beta.0

</code></pre>

## Current behavior
Unable to find the conditional access documentation for MSAL 1.2.0 beta.0

## Expected behavior
Need documentation 

## Minimal reproduction of the problem with instructions
Not Required

**Comment by sameerag** [comment]
@pkanher617 Do we have anything in the pipeline for this?

**Comment by PraveenVerma17** [comment]
@sameerag Any update on conditional access documentation?

**Comment by sameerag** [comment]
@PraveenVerma17 yes, we are planning to close this with the upcoming release, projected early next week. @negoe to track this.
