### ISSUE TITLE
resetCacheItems should only remove msal. prefixed local/session storage items

### ISSUE THREAD

**Issue by DibranMulder** [AzureAD/microsoft-authentication-library-for-js#103]
If you call [logout](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/UserAgentApplication.ts#L408) on a clientApplication the storage with its token and such will be cleared, this is correct. However it doesn't clear only whitelisted or prefixed key's but just every key available, please see:  [resetCacheItems](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/Storage.ts#L105)

The library should keep track of a list of keys or prefix them and only clear the prefixed keys. It looks like "msal" is the prefix but that's not taken into account when the cache is reset.

Therefore any local/session storage items used by our applications are also cleared, this is unwanted behavior.

**Comment by rohitnarula7176** [comment]
@DibranMulder Thank you for pointing out this issue. I have made a fix for it in my branch. Can you please use it to confirm if the issue is resolved for you. Here is the link for my branch 
https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/rohitnarula7176/Issue_103
I will then merge it into dev.

**Comment by DibranMulder** [comment]
There are more changes made to the branch you're pointing to, so I had to adjust my code. Your code changes look fine but my normal authentication flow broke. I'm able to head to the login page and then login, the return url is returned fine but the when I instantiate a clientApplication is does not seem to store the tokens.

URL:
https://localhost:44399/#state=2cf1dee1-3cee-46e3-ac74-520a7446b5cc&client_info=eyJ1aWQiOiI0NTgwN2IyNC04OWM5LTQ0MTQtY.... etc.

```TypeScript
let clientApplication = new Msal.UserAgentApplication(AUTH_B2C_CLIENTID, AUTH_B2C_AUTHORITY, () => { }, {
    cacheLocation: "localStorage",
    redirectUri: window.location.origin,
    postLogoutRedirectUri: window.location.origin,
});

let user = this.clientApplication.getUser();
// user = null
```
![bug](https://user-images.githubusercontent.com/5592416/30201034-9872c36c-9479-11e7-911f-c831ed055c46.png)
Am I doing something wrong?

**Comment by rohitnarula7176** [comment]
@DibranMulder I would need to see your code to find out why the tokens are not stored because the pr changes should not affect your auth flow. Can you please share a code repro for the issue?

**Comment by DibranMulder** [comment]
@rohitnarula7176 Hi I found some time to review your changes and its not good yet. I managed to perform a login, the change with [setTimeout ](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/rohitnarula7176/Issue_103/lib/UserAgentApplication.ts#L222 )broke my existing AngularJS routing fallback. I managed to workaround that. After that the login was processed correctly. Bear in mind that this setTimeout is a breaking change for existing users. The change 
should be part of the release notes.

When I'm logged in I usually retrieve the user from the clientApplication. This however always returns null. Its probably caused by the mixed use of the clientInfo constant.

`const rawClientInfo = this._cacheStorage.getItem(Constants.clientInfo);`
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/rohitnarula7176/Issue_103/lib/UserAgentApplication.ts#L1169

`this._cacheStorage.setItem(Constants.msalClientInfo, clientInfo);`
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/rohitnarula7176/Issue_103/lib/UserAgentApplication.ts#L1386

Please review the [Constants ](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/rohitnarula7176/Issue_103/lib/Constants.ts )file for duplicate constants, one with and one without msal prefix. They are used alternatively. 

Below some screenshots for clarification:
![localstorage](https://user-images.githubusercontent.com/5592416/30367016-5536ffee-986d-11e7-9e3f-452893f7bb9c.PNG)
![localstorage2](https://user-images.githubusercontent.com/5592416/30367020-57492046-986d-11e7-9c69-3f5da5d5cbeb.png)

**Comment by rohitnarula7176** [comment]
@DibranMulder Thank you for pointing out this issue. I have fixed it in mybranch. Can you please check that and confirm. Also can you explain why is the setTimeout method a breaking change for you. I made that code change so that it is backwards compatible.

**Comment by DibranMulder** [comment]
@rohitnarula7176 This is fixed, nice! Thank you

**Comment by arunkumar1811** [comment]
I'm also facing the similar issue. I don't see the token being stored in localstorage with the latest version (0.1.3). Please let me know whether this issue is included in the latest build
