### ISSUE TITLE
Upgrade msal-angular to support the latest versions of Angular

### ISSUE THREAD

**Issue by jasonnutter** [AzureAD/microsoft-authentication-library-for-js#1034]
The current version of `msal-angular` is built with and supports Angular 4/5, neither of which are currently supported by the Angular team. While we have customers who are able to get `msal-angular` working with the newer versions of Angular, we need to upgrade `msal-angular` to provide out-of-the-box support for Angular 6+.

https://angular.io/guide/releases#support-policy-and-schedule

AC:
1. `msal-angular` works out-of-the-box for Angular versions 6, 7, 8, 9.
2. There is a sample available for each supported version of Angular.

**Note**:  Per the link above, Angular 6 will soon leave LTS. While we will plan to support Angular 6 in the short-term, in the long-term it would be preferable to have our framework version support match that of the framework itself, meaning we would no longer support a version of Angular if it isn't supported by the Angular team.

**Comment by stevenruizhang** [comment]
@jasonnutter i have IE11 issue when use below version for this library in Angular8, anyway it can work well in Chrome and Firefox, #1011 , please see detail information i mentioned in #1011.


@azure/msal-angular:0.1.2
               "msal": "0.2.1",

**Comment by jasonnutter** [comment]
This work is complete, and available in the beta version of MSAL Angular.
