### ISSUE TITLE
SameSite warnings from Chrome

### ISSUE THREAD

**Issue by Therapho** [AzureAD/microsoft-authentication-library-for-js#1037]
I'm submitting a question for clarification.
## Library version: v0.2.1

When logging in I receive this warning from Chrome:  _A cookie associated with a cross-site resource at http://live.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`._

## Expected behavior
No warning

## Minimal reproduction of the problem with instructions
Angular 8 app using core MSAL.JS library, not angular wrapper.  
```
 this.agent = new UserAgentApplication(environment.clientId, environment.authority, null, {
      validateAuthority: false,
      cacheLocation: 'localstorage',
      protectedResourceMap: environment.protectedResourceMap
    });
this.agent.loginPopup(environment.contentScopes);

```

**Comment by PraveenVerma17** [comment]
This is happening in version 1.1.3 too

**Comment by sameerag** [comment]
@PraveenVerma17 STS is aware of this issue and working on it. You should not see it in a week and if it persists, please let us know.

**Comment by toddfsnyder** [comment]
Any update on the warnings for SameSite cookies?

**Comment by sameerag** [comment]
The service rolled out the fix last week and may take a week to propagate for 100% users. Is this still seen? @toddfsnyder @Therapho  @PraveenVerma17

**Comment by toddfsnyder** [comment]
Just check and we still see warnings about SameSite cookies used by Azure B2C.

A cookie associated with a cross-site resource at http://b2clogin.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

**Comment by abf7d** [comment]
Is there any movement on this? It seems the next major release of Chrome will block cookies without SameSite=None.

**Comment by toddfsnyder** [comment]
The ASP.Net Team posted an article in mid Oct about required changes to for ASP.Net Server apps:
https://devblogs.microsoft.com/aspnet/upcoming-samesite-cookie-changes-in-asp-net-and-asp-net-core.

Will there be update required for msal.js or will the cookie get automatically set in AzureB2C? It would be good to have an ETA on when to expects any changes.

**Comment by abf7d** [comment]
I’m using Angular and MSAL.js. I haven’t been able to find a fix for those.

**Comment by toddfsnyder** [comment]
> The ASP.Net Team posted an article in mid Oct about required changes to for ASP.Net Server apps:
> https://devblogs.microsoft.com/aspnet/upcoming-samesite-cookie-changes-in-asp-net-and-asp-net-core.
> 
> Will there be update required for msal.js or will the cookie get automatically set in AzureB2C? It would be good to have an ETA on when to expects any changes.

Looks like Microsoft is pushing back the ASP.NET Server fix until Jan (Check out my question on the linked blog post). Can we get some clarification on if the msal.js library will require a fix for connecting to Azure B2C with SameSite cookies and if a change is coming when can we expect it?

**Comment by aappddeevv** [comment]
I'm runnning this issues and the warning says the cookie is blocked. When I try to get an access token, it fails. I think its because some cookies are sent that are not present, when requesting an access token. Perhaps the fix has not hit the AAD I am working from yet. 

Is there a workaround?

**Comment by flieks** [comment]
@aappddeevv you mean the `block_token_requests`. I am on 1.2.0-beta.5 and have that too.
upgraded to beta because on stable i had the sameSite issue

**Comment by aappddeevv** [comment]
I set the flags in chrome to disable all SameSite processing for the time being. The problem went away. I notice that I was getting a "cookie not set" warnings in the console log which I did not realize what they were at first. I guess I am running my browser with all experimental features on so I hit this sooner than my AAD was upgrade to send the SameSite header correctly.

That solved the issues for now.

**Comment by sameerag** [comment]
Can we close this now @aappddeevv and @Therapho ?

**Comment by toddfsnyder** [comment]
@sameerag With Chrome 79 we are now seeing a different behavior. After logging into Azure B2C chrome says it blocks all the B2C cookies. This seems incorrect or at least unexpected behavior. Can you clarify if this is correct or is there a pending change for how B2C writes the cookie?

**Comment by toddfsnyder** [comment]
@sameerag while doing testing with Chrome 80 Beta (with the same site flags enabled). We are encountering a couple different behaviors.  Can we get clarification on the expected behavior? Will Azure B2C be updated to set the cookies to the correct SameSite values?

- We are successfully logging in, but chrome says it blocked the B2C cookies. Happens in both our Angular (uses msal.js) and ASP.NET MVC (uses owin) applications. 

- Occasionally we see this warning with our ASP.NET MVC application when logging in - A cookie associated with a resource set without a `SameSite` attribute was sent with a non-idempotent top-level cross-site request because it was less than 2 minutes old. A future release of Chrome will treat such cookies as if they were set with `SameSite=Lax` and will only allow them to be sent with top-level cross-site requests if the HTTP method is safe.

**Comment by kumarunster** [comment]
we see that warning on B2B AAD integration with MSAL.js with React based SPA. 

> `A cookie associated with a cross-site resource at http://login.microsoftonline.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.`

the SameSite attribute should be set on microsoft side, what is the ETA?

**Comment by gpit2286** [comment]
@sameerag  - This really shouldn't be closed until the Azure Endpoint issues the cookies correctly.  (With the SameSite=None and Secure).  I've had to tell my end users to stop using Safari for the time being because Safari's bypass doesn't actually work and is requiring the cookie to be set correctly with its ITP.

**Comment by amtandon** [comment]
I am seeing this when using AAD authentication (MSAL.js) with React. I also see the same issue with chromium based edge.

_A cookie associated with a cross-site resource at http://login.microsoftonline.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032._

**Comment by relakhani** [comment]
@toddfsnyder : Can you paste the console log error related to B2C and also after you run the sample, in Developer Tools -> Network tab, select the authorize request and check response cookies under the Cookies section. Can you check for the authorize request which response cookies are not having SameSite = None 

We are not able to reproduce the issue. For us the B2C Cookies are having SameSite = None and Secure = true

So can you provide exact steps to reproduce your issue

**Comment by toddfsnyder** [comment]
Here is what we are seeing in the chrome console. Take note: these requests seem to be over HTTP not HTTPS. These warnings come up when we are calling – “clientapplication.acquireTokenSilent”. The token is returned, and we can successfully call the secured external Web API. I checked the chrome network trace and do not seem any specific calls for these requests. I can verify the other B2C authentications calls do appear and make all the response cookies marked secure and SameSite = none. 

A cookie associated with a cross-site resource at http://gs1usadb2cdev.b2clogin.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

A cookie associated with a cross-site resource at http://b2clogin.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

**Comment by gpit2286** [comment]
Console output: 
```
Angular is running in the development mode. Call enableProdMode() to enable the production mode.
Logger.js:68 2 "Wed, 08 Jan 2020 21:34:41 GMT:0.2.2-Info Processing the callback from redirect response" false
Logger.js:68 2 "Wed, 08 Jan 2020 21:34:42 GMT:0.2.2-Info Add msal frame to document:msalRenewFrameuser.read" false
Logger.js:68 2 "Wed, 08 Jan 2020 21:34:42 GMT:0.2.2-Info LoadFrame: msalRenewFrameuser.read" false
client:52 [WDS] Live Reloading enabled.
Logger.js:68 2 "Wed, 08 Jan 2020 21:34:42 GMT:0.2.2-Info Add msal frame to document:msalRenewFrameuser.read" false
dashboard:1 A cookie associated with a cross-site resource at https://login.microsoftonline.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
dashboard:1 A cookie associated with a cross-site resource at http://login.microsoftonline.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
core.js:38781 Angular is running in the development mode. Call enableProdMode() to enable the production mode.
Logger.js:68 2 "Wed, 08 Jan 2020 21:34:44 GMT:0.2.2-Info State status:true; Request type:RENEW_TOKEN" false
2Logger.js:68 0 "Wed, 08 Jan 2020 21:34:44 GMT:0.2.2-Error Error when acquiring token for scopes: user.read AADSTS50058: A silent sign-in request was sent but no user is signed in. The cookies used to represent the user's session were not sent in the request to Azure AD. This can happen if the user is using Internet Explorer or Edge, and the web app sending the silent sign-in request is in different IE security zone than the Azure AD endpoint (login.microsoftonline.com).
Trace ID: a30dc8e5-908b-4702-a7bf-fc6662c94100
Correlation ID: 4a8bae22-eb81-4538-9566-40f34159d6fa
Timestamp: 2020-01-08 21:34:42Z|login_required" false
client:52 [WDS] Live Reloading enabled.
```

OpenID config Request URL: https://login.microsoftonline.com/{Company-ID}/v2.0/.well-known/openid-configuration

Response: 
![image](https://user-images.githubusercontent.com/3317312/72018501-9d6f1f80-321c-11ea-9fdd-66287fd98a26.png)

Auth Call: ``` https://login.microsoftonline.com/{CompanyID}/oauth2/v2.0/authorize?response_type=token&scope=user.read%20openid%20profile&client_id={ClientID}&redirect_uri=http%3A%2F%2Flocalhost%3A4200%2Fdashboard&state=f866fc06-da94-4dd0-a988-e83352d17d5c&nonce=81a417b2-e18e-4f8b-adba-f39c83d31ace&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=0.2.2&client-request-id=6d0fbd3f-549a-4838-b890-1dd8e3cf5985&prompt=none&login_hint=kyle%40{domain}.com&domain_req=b9b471bf-a113-4bd6-82ad-9397bdb0e371&login_req=ac4925d7-e3d2-4d59-9b1b-00d6b3f4ff70&domain_hint=organizations ```

Response URL: http://localhost:4200/dashboard#error=login_required&error_description=AADSTS50058%3a+A+silent+sign-in+request+was+sent+but+no+user+is+signed+in.+The+cookies+used+to+represent+the+user%27s+session+were+not+sent+in+the+request+to+Azure+AD.+This+can+happen+if+the+user+is+using+Internet+Explorer+or+Edge%2c+and+the+web+app+sending+the+silent+sign-in+request+is+in+different+IE+security+zone+than+the+Azure+AD+endpoint+(login.microsoftonline.com).%0d%0aTrace+ID%3a+a0823ea6-4663-4329-a571-c3cf890a4300%0d%0aCorrelation+ID%3a+6d0fbd3f-549a-4838-b890-1dd8e3cf5985%0d%0aTimestamp%3a+2020-01-08+21%3a44%3a37Z&error_uri=https%3a%2f%2flogin.microsoftonline.com%2ferror%3fcode%3d50058&state=f866fc06-da94-4dd0-a988-e83352d17d5c 

Response Cookies: 
![image](https://user-images.githubusercontent.com/3317312/72018952-87ae2a00-321d-11ea-86c4-67d23d20388c.png)

So what it looks like is that Chrome isn't sending the cookies to MS in the auth call... The reason the error is appearing is because the cookies set on the **error message** don't have the correct samesite setting.  

Also, another interesting tidbit is that Firefox doesn't seem to parse sameSite as samesite because of case. 

In the end it looks like a problem with Chrome sending cookies. Can anyone else reproduce this?

**Comment by relakhani** [comment]
Thanks @toddfsnyder for your response. Would you mind sending a fiddler trace to below email id relakhan@microsoft.com

We can verify in the fiddler trace which particular b2c response doesn't have correct cookie value

**Comment by GFoley83** [comment]
@kumarunster Did you find an answer to your question? Since the cookie is being issued by **http://login.microsoftonline.com**, there not much we can do here; unless I'm missing something?

**Comment by kumarunster** [comment]
@GFoley83 we are using this library, offered from MS and we are seeing this issue linked to Chrome. Chrome will release new version early Feb, and it seems for me, because of the warnings, that many companies will be affected, if they are using MS as Identity Provider. So far I was not able to analyze it in details, but it seems for me, for the first look, that all cookies are provided correct with SameSite=None and Secure attributes. Nevertheless we still observe this warning, so something is wrong on MS side.

**Comment by jasonnutter** [comment]
@hpsin Can you provide more context please? Thanks!

**Comment by hpsin** [comment]
Thanks @jasonnutter .

AAD and MSA correctly mark the cookies that need to be cross-domain as samesite=none.  We purposefully do not mark the cookies that are not required cross-domain as "lax" in order to reduce the number of changes we're introducing to the system. 

**It is expected that login.microsoftonline.com produces warnings about samesite in the Chrome console - this is NOT an indication of an error, but a side effect of not marking all our cookies.  This is intentional - SameSite issues in your app are a result of cookies your app is setting, not the server side.**

**Comment by hpsin** [comment]
To expand on what is required here:

SameSite in Chrome requires BOTH clients (your app running MSAL.NET/ADAL.NET/3rd party library) and the STS (login.*.com) to update their cookies.  Pure SPA apps likely do not need any update here - the SameSite change only breaks the form_post part of the OIDC standard for client apps, as well as logout for all  web-apps.  SPA apps (MSAL.js, e.g.) use the implicit flow and response_mode=fragment or query,  and therefore are not impacted by this change (once the STS updates their cookies).

**Comment by hpsin** [comment]
I would recommend downloading Chrome, enabling the flags, and testing your app. That's the only way to be certain and it's something that every app developer should do in the next two weeks.

In particular, use the command line flags to launch chrome so that the 2 minute grace period for POSTs is removed, otherwise your app might pass tests and fail suddenly in a future version of Chrome.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by toddfsnyder** [comment]
> I would recommend downloading Chrome, enabling the flags, and testing your app. That's the only way to be certain and it's something that every app developer should do in the next two weeks. In particular, use the command line flags to launch chrome so that the 2 minute grace period for POSTs is removed, otherwise your app might pass tests and fail suddenly in a future version of Chrome. Get Outlook for Android<https://aka.ms/ghei36>
> […](#)
> ________________________________ From: toddfsnyder <notifications@github.com> Sent: Monday, January 13, 2020 8:26:26 AM To: AzureAD/microsoft-authentication-library-for-js <microsoft-authentication-library-for-js@noreply.github.com> Cc: Hirsch Singhal <hirsin@microsoft.com>; Mention <mention@noreply.github.com> Subject: Re: [AzureAD/microsoft-authentication-library-for-js] SameSite warnings from Chrome (#1037) @hpsin<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhpsin&data=02%7C01%7Chirsin%40microsoft.com%7C872062df36c94c1bb2bc08d79845566f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637145295882372541&sdata=elgX1vzoJhHJT%2FWS3VRf6z9Bn%2FWG8GXO6PrYErPlog0%3D&reserved=0> To expand on what is required here: SameSite in Chrome requires BOTH clients (your app running MSAL.NET/ADAL.NET/3rd party library) and the STS (login.*.com) to update their cookies. Pure SPA apps likely do not need any update here - the SameSite change only breaks the form_post part of the OIDC standard for client apps, as well as logout for all web-apps. SPA apps (MSAL.js, e.g.) use the implicit flow and response_mode=fragment or query, and therefore are not impacted by this change (once the STS updates their cookies). Thanks for the clarification. What about ASP.NET MVC applications using the OWIN Client. We are seeing the SameSite cookie warnings in both our MSAL Angular applications and ASP.NET MVC Applications. Here is what the ASP.NET MVC Applications are showing: The cookie warning is related to making a call to the signin policy SelfAsserted method. Here are the results for the cookies sent back. Take note, there are a few ms- cookie that do not have SameSite set. The one I would think was the most important was the SSO cookie. [image]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F12663723%2F72272706-18f31700-35f7-11ea-94cf-6e0ea5d4470a.png&data=02%7C01%7Chirsin%40microsoft.com%7C872062df36c94c1bb2bc08d79845566f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637145295882372541&sdata=as5AHhhZggTBfrdoshKQKDKu%2F1hLj5i9OmmaRXPgtOA%3D&reserved=0> — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzureAD%2Fmicrosoft-authentication-library-for-js%2Fissues%2F1037%3Femail_source%3Dnotifications%26email_token%3DAAMW2O5OG24VJNHOWNOYT43Q5SI3FA5CNFSM4I6Q75JKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIZLKUA%23issuecomment-573748560&data=02%7C01%7Chirsin%40microsoft.com%7C872062df36c94c1bb2bc08d79845566f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637145295882382497&sdata=DiEGk8S8HRdHV0FrHE22x3S7AlBucQQpG4xIncwz6Hs%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAMW2O2HV3ZRKH2YSYOSFZDQ5SI3FANCNFSM4I6Q75JA&data=02%7C01%7Chirsin%40microsoft.com%7C872062df36c94c1bb2bc08d79845566f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637145295882382497&sdata=spTkj1sYZIM%2FSPIIrnsVl9zYn3jLAVgy3Fg%2BUFHyn8s%3D&reserved=0>.

We have been testing in Chrome 80 Beta for the last several weeks and the login to Azure B2C is working. We are just corned by the warning are still appearing and want to make sure we have not missed something that will break when Chrome 80 is released. 

Do you know the specific command line flags to disable the 2 minute grace period for POSTs?

**Comment by hpsin** [comment]
--enable-features=SameSiteDefaultChecksMethodRigorously

From https://www.chromium.org/updates/same-site

**Comment by relakhani** [comment]
> @hpsin
> 
> > To expand on what is required here:
> > SameSite in Chrome requires BOTH clients (your app running MSAL.NET/ADAL.NET/3rd party library) and the STS (login.*.com) to update their cookies. Pure SPA apps likely do not need any update here - the SameSite change only breaks the form_post part of the OIDC standard for client apps, as well as logout for all web-apps. SPA apps (MSAL.js, e.g.) use the implicit flow and response_mode=fragment or query, and therefore are not impacted by this change (once the STS updates their cookies).
> 
> Thanks for the clarification. What about ASP.NET MVC applications using the OWIN Client. We are seeing the SameSite cookie warnings in both our MSAL Angular applications and ASP.NET MVC Applications.
> 
> Here is what the ASP.NET MVC Applications are showing:
> 
> The cookie warning is related to making a call to the signin policy SelfAsserted method. Here are the results for the cookies sent back. Take note, there are a few ms- cookie that do not have SameSite set. The one I would think was the most important was the SSO cookie.
> 
> ![image](https://user-images.githubusercontent.com/12663723/72272706-18f31700-35f7-11ea-94cf-6e0ea5d4470a.png)

@toddfsnyder : The cookies that you are referring are the request cookies which would have been present from old session. The cookies that you should be concerned about are the response cookies. If you see the response cookies section then both of them have SameSite

**Comment by toddfsnyder** [comment]
> --enable-features=SameSiteDefaultChecksMethodRigorously
> 
> From https://www.chromium.org/updates/same-site

Do you have any more details about this flag and the grace period? Has the chrome team posted anywhere how the grace period will work once Chrome 80 is released in February?

**Comment by hpsin** [comment]
@toddfsnyder : 
From Chrome's description:
>Starting in Canary version 80.0.3975.0, the Lax+POST temporary mitigation can be disabled for testing purposes using the new flag --enable-features=SameSiteDefaultChecksMethodRigorously to allow testing of sites and services in the eventual end state of the feature where the mitigation has been removed. [...]

So, this removes the grace period.  The grace period is present without this flag in Chrome 80.  At some point (within 2 years apparently based on today's announcement) the grace period will be eliminated.

**Comment by toddfsnyder** [comment]
> @toddfsnyder :
> From Chrome's description:
> 
> > Starting in Canary version 80.0.3975.0, the Lax+POST temporary mitigation can be disabled for testing purposes using the new flag --enable-features=SameSiteDefaultChecksMethodRigorously to allow testing of sites and services in the eventual end state of the feature where the mitigation has been removed. [...]
> 
> So, this removes the grace period. The grace period is present without this flag in Chrome 80. At some point (within 2 years apparently based on today's announcement) the grace period will be eliminated.

Do you have a link to this announcement?

**Comment by hpsin** [comment]
It's an inference from their plan to eliminate 3rd party cookies in two years: https://blog.chromium.org/2020/01/building-more-private-web-path-towards.html

**Comment by hpsin** [comment]
#please-close
The resolution to this issue is: AAD and MSA servers have updated (several months ago) to correctly mark the cookies that are needed.  Some cookies are not marked by design, which causes warnings to appear in the Chrome dev console. Any issues in your site that occur when signing into AAD need to be fixed in your app.

**Comment by jasonnutter** [comment]
Thanks @hpsin, closing.

**Comment by toddfsnyder** [comment]
@hpsin 

Plus we noticed that with the stable version of Chrome 80 the --enable-features=SameSiteDefaultChecksMethodRigorously command line no longer seems to turn off the SameSite grace period. Do you know if there is another way to test with the grace period off with the stable version of Chrome 80?

Todd Snyder

**Comment by hpsin** [comment]
Hi @toddfsnyder - what makes you think this? It may be beta only, so you might need to try in version 81.

**Comment by toddfsnyder** [comment]
If you check chrome://version in Chrome 80 Beta vs Chrome 80 Stable it no longer shows the the command line setting even when chrome is being loaded with the SameSiteDefaultChecksMethodRigorously command line. We have a test site that fails in Chrome 80 Beta with the SameSiteDefaultChecksMethodRigorously  and works in Chrome 80 Stable. It not clear if the issue has no longer valid or if the command line was turning the grace period off.

**Comment by hpsin** [comment]
Yes, the command line turns off the grace period.  Sounds like it doesn’t work in the stable release, will roll that into our docs.

**Comment by DanielLitvak** [comment]
> #please-close
> The resolution to this issue is: AAD and MSA servers have updated (several months ago) to correctly mark the cookies that are needed. Some cookies are not marked by design, which causes warnings to appear in the Chrome dev console. Any issues in your site that occur when signing into AAD need to be fixed in your app.

How to fix it in the app? safari and chromium are blocking cross site cookies by default. is the a way to mark the cookie as non cross site?

see my comment on other issue: https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/323#issuecomment-601932294

**Comment by AbhaysinghBhosale** [comment]
Is this issue resolved ?
**Using msal in react application**

I am still getting warning in console.
`A cookie associated with a cross-site resource at http://example.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
`

**Comment by hpsin** [comment]
You have to resolve this in your application by setting the cookies correctly.  Cookies are controlled entirely by the server listed here (example.com) and for security reasons no other party is allowed to touch them.  You'll need to set these cookies correctly in your codebase - the library you're using or framework that is setting the cookies in question should have options to handle this.
