### ISSUE TITLE
after successful login acquireTokenSilent returns id_token instead of access token

### ISSUE THREAD

**Issue by djleonskennedy** [AzureAD/microsoft-authentication-library-for-js#1038]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version 
- [ x] Firefox version XX
- [x ] IE version XX
- [ x] Edge version XX
- [ x] Safari version XX

## Library version

<pre><code>
    "msal": "0.2.2",
    "msal-angular": "0.1.4"

</code></pre>

## Current behavior
After successful login we need to get `access token`
(due to documentation: https://docs.microsoft.com/bs-latn-ba/azure/active-directory/develop/quickstart-v2-javascript#more-information)
however method return `id_token` type

```
{"_token":"bla bla bla","_tokenType":"idToken"}
```
however directlly we can fetch access token with using "token id_token"

e.g https://login.microsoftonline.com/<tenant>/oauth2/v2.0/authorize?client_id=<client_id>&response_type=token+id_token&redirect_url=<our_url>&scope=openid&response_mode=fragment&nonce=678918

## Expected behavior

acquireTokenSilent have to return `accessToken` instead `idToken`

Could you please recommend solution? Might configuration require some extra steps

Thank you

## Minimal reproduction of the problem with instructions

we're using `https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/MSALAngularDemoApp`

with out customer's azure environment

**Comment by djleonskennedy** [comment]
library works fine there was problem with configuratio

**Comment by whobeika** [comment]
@djleonskennedy can you share what was the problem and adjustments to configs you had to make? Thanks
