### ISSUE TITLE
Include TypeScript typings the right way

### ISSUE THREAD

**Issue by DibranMulder** [AzureAD/microsoft-authentication-library-for-js#104]
Please follow the TypeScript [guidelines ](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) for publishing typings with your npm package. This library doesn't comply to either:

1. Bundling with your npm package, or

Your are missing the "types" attribute in package.json

2. Publishing to the @types organization on npm.

This is in my opinion the preferred approach. Every major library has its typings published this way.

**Comment by DibranMulder** [comment]
This issue can be partially solved by merging the following pull request: #79

**Comment by dfederm** [comment]
Now that #79 is merged, this issue can now be closed.
