### ISSUE TITLE
MSAL.AuthenticationParameters prompt property should be typed

### ISSUE THREAD

**Issue by jannikbuschke** [AzureAD/microsoft-authentication-library-for-js#1041]
Currently the 'prompt' parameter has type `string | undefined`.
However it seems that only following values are allowed:

login
select_account
consent
none

https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-prompt-behavior

Do you accept PRs in this repository?

msaljs v1.1.3

**Comment by sameerag** [comment]
@jannikbuschke This is intentional from the library as the support for `prompt` parameter and it's possible values is based on the STS code and not the library. What exactly is the functionality you are looking for by adding a new value to `prompt`?

**Comment by jannikbuschke** [comment]
I want to restrict the prompt values to login, select_account, consent, none so that typescript throws early (in case of spelling error) and to get IDE/intellisense support so that I don't need to always lookup the correct values in the documentation.

I.e. something like

`type Prompt = "login" | "select_account" | "consent" | "none" | undefined`

Currently the type of this property is `string | undefined`, which seems to be wrong. Not all string values are valid...

**Comment by PraveenVerma17** [comment]
@jannikbuschke  its already present 
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/src/utils/Constants.ts

Use PromptState Enum from above file


export const PromptState = {
    LOGIN: "login",
    SELECT_ACCOUNT: "select_account",
    CONSENT: "consent",
    NONE: "none",
};

**Comment by jannikbuschke** [comment]
But why is the prompt property on `AuthenticationParameters` a string and not typed to the concrete string values?
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/src/AuthenticationParameters.ts#L16

**Comment by keystroke** [comment]
@jannikbuschke The values you see there are not the actual complete set of values, In special circumstances, the prompt values can include other strings that are unique in a particular directory, like one federated with ADFS or perhaps other B2C scenarios. Sorry I don't have a great example for you, but I recall running into this previously in some circumstance where the prompt string accepted a different value not included in the normal set of strings documented above. Though, this was a while ago, so not sure if anything changed, or perhaps I am mis-remembering.

**Comment by jannikbuschke** [comment]
Ok, in this case string might be the best type.

**Comment by isaacList** [comment]
how can we allow user to select account and ask for consent together? It seems strange not able to select_account and consent in one shot.

**Comment by sameerag** [comment]
Thanks @keystroke. Yes, eg: we had `prompt=auto` supported before a while in older libraries. The decisive authority here is the service team and they would like to keep this expandable. 

@isaacList I am not sure if UI supports that. @jmprieur Any help here. The question is: "Can we allow user to select account and ask for consent together? It seems strange not able to select_account and consent in one shot."

**Comment by keystroke** [comment]
@isaacList The behavior here is determined 100% by the AAD backend. All MSAL gets to do is construct the URI to send the user, like below two examples which you can click:

1. https://login.microsoftonline.com/common/oauth2/authorize?client_id=a963b646-fa01-4c06-b302-42c6ed1b2774&redirect_uri=https%3a%2f%2flocalhost%3a3000&response_type=code+id_token&scope=openid+profile&nonce=foo&prompt=consent

2. https://login.microsoftonline.com/common/oauth2/authorize?client_id=a963b646-fa01-4c06-b302-42c6ed1b2774&redirect_uri=https%3a%2f%2flocalhost%3a3000&response_type=code+id_token&scope=openid+profile&nonce=foo&prompt=select_account

Above, we have to pick a single value for the prompt parameter. If you try to include more than one value, you get an error: "AADSTS9000411: The request is not properly formatted. The parameter 'prompt' is duplicated."

However, you will find that AAD page will induce a select_account experience (or login experience) during a consent flow on that page if the user has multiple active sessions for different accounts which are valid (e.g. depending on what your authority value is).

You can lookup more details about this API flow in general, there is another query parameter for login_hint which can be used, like this (replace details of username at the end to be your account name):

https://login.microsoftonline.com/common/oauth2/authorize?client_id=a963b646-fa01-4c06-b302-42c6ed1b2774&redirect_uri=https%3a%2f%2flocalhost%3a3000&response_type=code+id_token&scope=openid+profile&nonce=foo&prompt=consent&login_hint=user%whatever.com

Above flow is supported by MSAL, and you can achieve this kind of thing using below code snippet:

````js
for (let account of msal.getAllAccounts()) {
    console.log('starting consent for account: ', account);
    try {
        await msal.acquireTokenPopup({ account, scopes: ['openid'], prompt: 'consent' })
    }
    catch (error) {
        console.log('error during popup consent for account: ', account, error)
    }
}
````

Above, we pass a specific account to use with the consent prompt, and this will cause MSAL to set the login_hint to that target account. Note that this may force the user to re-enter their password in some cases.

**Comment by sameerag** [comment]
This is exactly how it works @keystroke, Thanks for the explanation. Since the thread deviated from the original issue, and we have answers for all the points discussed, I am closing this issue. Please open a new issue for any remaining concerns @isaacList.
