### ISSUE TITLE
Getting Unable to connect error from vuejs + msal+ azure active directory when running a build

### ISSUE THREAD

**Issue by pmatte** [AzureAD/microsoft-authentication-library-for-js#1043]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [x ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 0.2.4
Checked with the latest version of msal i.e. 1.1.3 by updating package.json and running npm install, but no luck
</code></pre>

## Current behavior
Getting Unable to connect error, but only in preview or production build

## Expected behavior
Should be redirected to dashboard page/home page

## Minimal reproduction of the problem with instructions
run npm run preview/npm run build:prod

**Comment by jasonnutter** [comment]
@pmatte Do you have a sample project you share with us? Feel free to create a private repo on Github and invite me to it, thanks!

**Comment by pmatte** [comment]
Hi Jason, here is the snapshot of the code where vuejs is calling azure via msal. 

import * as Msal from 'msal'
import config from '../config'
import router from '../router'
import store from '../store'

export default class AuthService {
  constructor() {
    const redirectUri = config.redirect_url
    this.graphUrl = config.graph_end_point
    this.applicationConfig = {
      clientID: config.auth_client_id,
      authority: config.authority,
      graphScopes: config.graph_scopes
    }
    this.app = new Msal.UserAgentApplication(
      this.applicationConfig.clientID,
      this.applicationConfig.authority,
      () => {
        // callback for login redirect
      },
      {
        redirectUri
      }
    )

    const whiteList = ['/login'] // no redirect whitelist
    const usrInfo = this.app.getUser()

    router.beforeEach(async(to, from, next) => {
      if (usrInfo) {
        store.dispatch('inventory/setLoggedInUserEmail', usrInfo.displayableId)
        store.dispatch('inventory/setLoggedInUserFullName', usrInfo.name)
        if (!this.isUserAuthorized(usrInfo) && to.path !== '/401') {
          next({ path: '/401' })
        } else if (to.path === '/login') {
          // if is logged in, redirect to the home page
          next({ path: '/' })
        } else {
          next()
        }
      } else {
        if (whiteList.indexOf(to.path) !== -1) {
          // in the free login whitelist, go directly
          next()
        } else {
          // other pages that do not have permission to access are redirected to the login page.
          next(`/login?redirect=${to.path}`)
        }
      }
    })
  }

  isUserAuthorized(usr) {
    const usrGroups = usr.idToken.roles

    if (usrGroups === undefined) {
      return false
    } else {
      const env = process.env.NODE_ENV
      const dev_client_id = process.env.VUE_APP_COMPASS_DEV_CLIENT_ID
      const prd_client_id = process.env.VUE_APP_COMPASS_PRD_CLIENT_ID

      return ((env === 'development' && usrGroups.includes(dev_client_id)) || (env === 'production' && usrGroups.includes(prd_client_id)))
    }
  }

  loginRedirect() {
    this.app.loginRedirect(this.applicationConfig.graphScopes)
  }

  logout() {
    this.app._user = null
    this.app.logout()
  }
}

**Comment by jasonnutter** [comment]
@pmatte Can you share a screenshot of the error?

**Comment by jmckennon** [comment]
Closing this issue, as it's been some time and I'm assuming the issue has been resolved. Feel free to open a new issue if you have further questions.
