### ISSUE TITLE
Incorrect type of acquiring token logged

### ISSUE THREAD

**Issue by anton-gorbikov** [AzureAD/microsoft-authentication-library-for-js#1046]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version 77
- [x] Firefox version 69
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>Library version: 1.1.3</code></pre>

## Current behavior
Verbose logging reports about "acquiring token interactive in progress" meanwhile only silent login happened.

## Expected behavior
Correct type of login should be logged.

## Minimal reproduction of the problem with instructions
Try to acquire new token using `acquireTokenSilent`.

The problem is that this code checks whether it's called from `iframe` or not:
```javascript
UserAgentApplication.prototype.processCallBack = function (hash, stateInfo, parentCallback) {
  // Some code here
  if (window.parent !== window) {
    this.logger.verbose("Window is in iframe, acquiring token silently");
  } else {
    this.logger.verbose("acquiring token interactive in progress");
  }
```
The trick is that this code is called from the iframe via `window.opener` object which is parent window:

```javascript
if (isWindowOpenerMsal) {
    self = window.opener.msal;
    isPopup = true;
}
// Some code here
self.processCallBack(hash, stateInfo, tokenResponseCallback);
```

As a result this code is initiated by silent login in `iframe`, but executed in the parent window.
This logging creates a lot of confusion, you expect that something went wrong and instead of silent login interactive login started however it's not the case.

**Comment by jasonnutter** [comment]
@anton-gorbikov Apologies, this issue slipped through the cracks.

In `msal@1.2.0`, msal is not executed in the hidden iframe, so the logging should make sense. 

Closing, please let us know if you have further questions.
