### ISSUE TITLE
MSAL based angular js app lost homepage if Azure AD access is blocked.

### ISSUE THREAD

**Issue by malayidan** [AzureAD/microsoft-authentication-library-for-js#1048]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
MSAL angular js library used in the app loosing the app homepage and shows the error " AADSTS50059: No tenant-identifying information found in either the request or implied by any provided credentials."  if there is an access issue with Azure AD.
</code></pre>

## Browser:
- [x ] Chrome version XX
- [x ] Firefox version XX
- [x ] IE version XX
- [x] Edge version XX
- [x] Safari version XX

## Library version
    "@azure/msal-angularjs": "^0.1.1"

<pre><code>
Library version: 0.1.1

</code></pre>

## Current behavior

When I configure MSAL with the authority "https://login.microsoftonline.com/organizations" from my AngularJS application , I am facing the below issue.
1. My access to O365 tenant is denied due to account lockout/password/tenant server down.
2. When the AngularJS app starts, it tries to bring up popup for sign in but popup never comes up and home page redirected to microsoft page with the below error 

"Sign in
Sorry, but we’re having trouble signing you in.
AADSTS50059: No tenant-identifying information found in either the request or implied by any provided credentials."

3. Now I lost my homepage access and wish to continue with other functionalities in the page.
4. But MSAL for Angular JS does not handle the error and does not stay in the home page with an error message "there is an issue with O365 azure access"
## Expected behavior

The desired behavior would be an option to catch the error related to O365 azure AD access and show an error message in the homepage and continue with the other functionalities.

## Minimal reproduction of the problem with instructions

1. Configure AngularJS app with @azure/msal-angularjs.
2. Assume your O365 access has been denied or O365 tenant down.
3. When the app starts it is trying to perform oauth2 using sign in popup.
4. But sign in popup does not come and showing the redirected error page 

" Microsoft
  Sign in
 Sorry, but we’re having trouble signing you in.
AADSTS50059: No tenant-identifying information found in either the request or implied by any provided credentials."

5. Now I lost the access to my app's homepage and I am not able to use other features by staying back at the homepage.

**Comment by jasonnutter** [comment]
@malayidan Apologies, this issue slipped through the cracks.

In `@azure/msal-angularjs`, there is no workaround to stop this behavior, unfortunately. We have addressed this in `msal@1.2.0`, and we are currently working to uprade `@azure/msal-angular` to use `msal@1.2.0`. So you will need to switch to `@azure/msal-angular`, and you can try out `@azure/msal-angular@1.0.0-alpha.0`, which is the first version of `@azure/msal-angular` with `msal@1.2.0`. 

Please try that and let us know if you have any feedback.
