### ISSUE TITLE
How to enable httpOnly for auth cookies

### ISSUE THREAD

**Issue by simonstewart** [AzureAD/microsoft-authentication-library-for-js#1049]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>
 
## Browser:
- [x] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>Library version: "msal": "^1.0.1"</code></pre>

## Current behavior

Unable to configure the library to use *httpOnly* for the authentication cookies.

## Expected behavior

Should be able to toggle this via the JavaScript library.

## Minimal reproduction of the problem with instructions

Multiple cookies are flagged as not being "http only".

**Comment by jasonnutter** [comment]
@simonstewart Which cookies are flagged for not being httponly?

**Comment by simonstewart** [comment]
The "login.microsoftonline*" cookies.

**Comment by jasonnutter** [comment]
@simonstewart It does look like most of the cookies set for login.microsoftonline.com are httponly, but there are a few that are not. I'm going to assume this is done intentionally, given that is only for a few of them (i.e. the login UI probably needs those for client-side logic). Regardless, this is set by the server, and we have no ability to control cookies set for login.microsoftonline.com, as our library will always be running on a different domain.

Closing, as no further actionable items.
