### ISSUE TITLE
 Compatibility of msalService Service with native android browser

### ISSUE THREAD

**Issue by Giovane-Roberti-Tafine** [AzureAD/microsoft-authentication-library-for-js#1058]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX
-[x] Others(Browser Native Android)

## Library version

<pre><code>
Library version: 0.1.4

</code></pre>

## Current behavior

When opening the application by the native browser of android, it does not appear the components, only when it is instant service MsalService:

private authService: MsalService,

and in other browsers, even in IOS it usually picks up

## Expected behavior

I hope when instantiation has no problem with browser compatibility

## Minimal reproduction of the problem with instructions

My project is a Portival Case, so it releases or accesses a network, when the user tries to access an open network in this portal, then opens the native browser of the operating system, for example on my mobile phone this default is Chrome, but still it opens in this browser, and because of this bug is not possible to take advantage of it.

I can not get any log, because the browser does not release resources for it

**Comment by jasonnutter** [comment]
Closing, as I don't expect us to prioritize fixing compatibility issues with this browser, given how old it is and relatively low usage.
