### ISSUE TITLE
Problems with Microsoft Account with B2C react

### ISSUE THREAD

**Issue by trbngr** [AzureAD/microsoft-authentication-library-for-js#106]
Repo here: https://github.com/trbngr/azure_b2c_react

Using a MS account, the initial login succeeds but, redirects continuously until `acquireTokenSilent` times out. The next time through everything works perfectly.

This only happens with MS accounts.

relavent code here: https://github.com/trbngr/azure_b2c_react/blob/master/src/redux/auth/actions.js#L32

logs here: https://pastebin.com/eMsBwwUd

**Comment by trbngr** [comment]
Just added Google and it happens as well.

**Comment by jmprieur** [comment]
+ @parakhj

**Comment by DibranMulder** [comment]
Is it related to this bug: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/63

**Comment by jmprieur** [comment]
@trbngr : could you please try to see if this version of msal.js (in the dev branch) fixes your issue: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/out/msal.js

**Comment by trbngr** [comment]
That seems to have done it!

Thanks @jmprieur and @DibranMulder

**Comment by jmprieur** [comment]
Thanks for the update, @trbngr 
BTW, we want to release a new version of msal.js soon (with this fix)
cc: @rohitnarula7176
