### ISSUE TITLE
DevOps + SharePoint at the same time

### ISSUE THREAD

**Issue by eirikb** [AzureAD/microsoft-authentication-library-for-js#1063]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Other... Please describe: Question
</code></pre>

## Library version

<pre><code>
Library version: 1.2.0-beta.1
</code></pre>

## Current behavior
Using two scopes at the same time for login:
SharePoint`https://mytentant.sharepoint.com/Sites.Read.All` and DevOps `499b84ac-1321-427f-aa17-267ca6975798/.default`.  
I'm not sure if that's the correct scope for DevOps, but I tried several things from random posts online, and this was the only one that worked.

When I pass these two scopes, like this:
```js
await msal.loginPopup({ scopes: [
  'https://mytenant.sharepoint.com/AllSites.FullControl', 
  '499b84ac-1321-427f-aa17-267ca6975798/.default']
});
```
 at the same time I get the error 
> AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope https://mytenant.sharepoint.com/AllSites.FullControl 499b84ac-1321-427f-aa17-267ca6975798/.default openid profile is not valid. .default scope can't be combined with resource-specific scopes.  

Like this:  
![image](https://user-images.githubusercontent.com/241706/67207317-9b62a500-f413-11e9-8d5f-139694c4a4b9.png)

I can read the text and understand I'm mixing up resource and  `.default`, but I haven't found any documentation for how to do this against DevOps online.

My current working solutions:

1. Do login twice, once for each scope.  
   Bad part: User actually have to click two times on login button.
2. Don't include scopes in login popup.  
   This actually works, but I'm not sure about the implications, what can go wrong - perhaps new users won't get prompt and silent acquire of token will always fail.

## Expected behavior
Not having to log in twice.  
Also, is this the proper way to connect to DevOps?

**Comment by sameerag** [comment]
@eirikb So it is possible to do this without logging in twice. `access token` calls are JIT calls, hence can be made multiple times. Please call `acquireTokenSilent` (if you have a session already i.e., after logging in) twice with these scopes and see if you have two different tokens to access the corresponding resources.

@negoe  to reference more documentation on this.

**Comment by eirikb** [comment]
I already use `acquireTokenSilent` to acquire the tokens, and I do these simultaneously with `Promise.all` - this works fine.  But in order to do this I must first log in, and then I need the two calls - or do as in my second solution to simply omit the scopes in login, but as I said I don't know the implications of this (works for me now, but app is already consented).

**Comment by sameerag** [comment]
Omitting the scopes in login would mean that if you are not pre-consented to the scopes you need access to and need `consent` to one of these scopes, you will be prompted to interact (if you call `acquireTokenSilent` it fails with `consent_required` error) and you need to call `acquireTokenPopup` or `acquireTokenRedirect` to give the consent as you have correctly stated in the issue description.

**Comment by eirikb** [comment]
@sameerag That could be an alternative solution then. A bit awkward flow perhaps.  
Something like this:
1. First time without consent:
    1. User clicks login
    1. Login fails (catch error, start original flow)
    1. User click login again (for SharePoint)
    1. User click login again (for DevOps)
1. Every time after consent:
    1. User clicks login

A couple of notes: I have an iframe in an iframe, which is why I must use `acquireTokenPopup`. Also note; I must get a user interaction (actual mouse click) before each opening of popup in order to not get popup blocked.

**Comment by anomepani** [comment]
@eirikb Are you able to resolve an issue? Did you find any workaround?
I am also having difficulty while I need to get token for multiple services like SharePoint, MS Graph and DevOps with a single app.

No Proper documentation present with adal.js or msal.js

**Comment by anomepani** [comment]
@eirikb I have created a demo for Multi-Tenant, Multi Resource authentication using `adal.js` and `msal.js`

Working Demo Using `adal.js` for Multi Resource Multi Authentication is live at [https://anomepani.github.io](https://anomepani.github.io/Multi-Tenant-Authentication-using-adal-js/index.html)

Working Demo Using `msal.js` for Multi Resource Multi Authentication is live at [https://anomepani.github.io](https://anomepani.github.io/Multi-Tenant-Authentication-using-adal-js/index1.html)

Source Code at:  https://github.com/anomepani/Multi-Tenant-Authentication-using-adal-js

This might be helpful to you at some level.

**Comment by eirikb** [comment]
@anomepani No I haven't found a good solution. I think there might not be any, so the issue can be closed.

But before we close it I would like to know three things:
  * Will it be possible to have several different scopes in login in the future?
  * Are there any other possible flows, such as catching missing consent on `acquireTokenSilent` and then conditionally forcing a new login for each error?
  * Is it possible to use admin consent (or similar) to ensure no user in a whole tenant/organization will ever have to consent?

**Comment by tnorling** [comment]
@eirikb Sorry this went unanswered. You can include several different scopes in your login request. This will allow you to pre-consent to the scopes in question. Then in order to actually get your access tokens for these, you need to call ```acquireTokenSilent``` once for each resource you are trying to access. If ```acquireTokenSilent``` fails with an ```InteractionRequired``` Error you should catch this error and call ```acquireTokenRedirect``` or ```acquireTokenPopup```. Hope this clears things up. Let us know if you still have questions about this.
