### ISSUE TITLE
MSAL throws an error whenever logging in to an Azure B2C enabled application with Facebook credentials

### ISSUE THREAD

**Issue by tvperez76** [AzureAD/microsoft-authentication-library-for-js#1065]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [X] Chrome version 77.0.3865.120 
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 1.2.0-beta.1
</code></pre>

## Current behavior
Whenever I try to log on to my Azure B2C enabled application with Facebook credentials, the following error is thrown and the 
```console
Error while getting a token! SyntaxError: Unexpected token m in JSON at position 0
    at JSON.parse (<anonymous>)
    at AuthCache.js:143
    at Array.reduce (<anonymous>)
    at e.getAllAccessTokens (AuthCache.js:139)
    at t.getCachedToken (UserAgentApplication.js:929)
    at UserAgentApplication.js:464
    at new j (zone-evergreen.js.pre-build-optimizer.js:876)
    at t.acquireTokenSilent (UserAgentApplication.js:433)
    at d.project (authentication.service.ts:130)
    at d._next (switchMap.js.pre-build-optimizer.js:30)
```
![Error as found in Chrome](https://mlpexpress2.blob.core.windows.net/errors/Error.png)
## Expected behavior
To log in without an error.

## Minimal reproduction of the problem with instructions
Log in to [MLP Express](https://mlp-express.com/) with a Facebook account.

**Comment by sameerag** [comment]
@tvperez76 This is a bug we identified yesterday in the beta, especially for concurrent calls. We are working on a fix and I will update the thread as we have the PR in dev. Please watch out for a new beta release soon. Thanks for raising this.

**Comment by sameerag** [comment]
`msal.1.2.0-beta.2` fixes this. We are working on the announcement and detailed release notes to follow soon, but the package is available in npm now for anyone to test try it.
