### ISSUE TITLE
Enable Issues for MicrosoftDocs/azure-docs

### ISSUE THREAD

**Issue by Hongbo-Miao** [AzureAD/microsoft-authentication-library-for-js#107]
I am reading the doc [Call the Microsoft Graph API from a JavaScript Single Page Application (SPA)](https://docs.microsoft.com/en-us/azure/active-directory/develop/guidedsetups/active-directory-javascriptspa)

I try to open an issue, so I go to
https://github.com/MicrosoftDocs/azure-docs

But obviously Issues is disabled. Please enable it, thanks!

![image](https://user-images.githubusercontent.com/3375461/28998868-722673ce-79ea-11e7-880d-a08c48a870d9.png)

**Comment by danieldobalian** [comment]
@Hongbo-Miao I would recommend dropping issues you had on that sample here: 

https://github.com/Azure-Samples/active-directory-javascript-graphapi-v2

Unfortunately, we cannot unlock issues for that repo as it represents all docs across Microsoft.

**Comment by Hongbo-Miao** [comment]
Cool thanks
