### ISSUE TITLE
How to pass tokenRenewalOffsetSeconds to MSAL from MSAL AngularJS wrapper?

### ISSUE THREAD

**Issue by leniel** [AzureAD/microsoft-authentication-library-for-js#1077]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ X ] Other... Please describe:
</code></pre>

## Browser:
- [ X ] Chrome version 78.0.3904.70
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre>Library version: MSAL 1.1.3 and MSAL for AngularJS 0.1.1</pre>

## Current behavior
I'd like to test token renewal\expiration. I opened [this question](https://stackoverflow.com/q/58548911/114029) at SO.

I do see [here](https://stackoverflow.com/q/57494059/114029) that `tokenRenewalOffsetSeconds` is being used to test it. However I don't see any way of passing `tokenRenewalOffsetSeconds` to MSAL when using MSAL Angular JS wrapper. This parameter is not described on MSAL Angular JS doc [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angularjs/README.md).

By the way... in some places like on this table *****[here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#release) it's mentioned MSAL AngularJS `0.1.1`. On the latest file [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/3844c9eedb7f07e6fc927d1039af9a8f54366cad/lib/msal-angularjs/dist/msal-angular.js#L1651) it still mentions `0.0.1`... so it's kinda confusing which version it really is.

***** The link anchor `#release` and others are not working either on this page. 
## Expected behavior
Be able to pass additional (new) parameter(s) from Angular JS wrapper to MSAL latest code.

**Comment by jasonnutter** [comment]
@leniel Unfortunately, this option is not available for `@azure/msal-angularjs`, as it was added in `msal` 1.0, and `@azure/msal-angularjs` uses `0.2.2` of `msal`. This also means it is not currently available in `@azure/msal-angular`, however, it will be soon, as we are working this quarter to upgrade to `@azure/msal-angular` to version 1 of `msal`. We do not have plans to backport this fetaure to `@azure/msal-angularjs`, however. 

Apologies for the confusion with the version in the source code, it looks like the code comment you referenced is out of date.

**Comment by leniel** [comment]
@jasonnutter thanks for the reply... we're using the latest MSAL code `1.1.3` with MSAL Angular JS and it is working as expected so far but we're limited. Can't use these new additions.

The way ahead is then going with `@azure/msal-angular`.

**Comment by leniel** [comment]
@jasonnutter : how can we contribute to the wiki page(s) [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki)?

Can't we submit PR to fix the pages? :)

**Comment by jennyf19** [comment]
@leniel  you should be able to fork the repo and then submit a PR. here's [an example w/the .net repo](https://github.com/AzureAd/microsoft-authentication-library-for-dotnet/wiki/Contributing-overview#fork)

**Comment by leniel** [comment]
@jennyf19... I only saw an option to clone the wiki directly from origin... could not fork it. Can you point me to the real Github repo where it's hosted so that I can fork?

I cloned directly from the origin... and that won't allow me to push.

**Comment by jennyf19** [comment]
@leniel - okay...figured it out. so if you go to the [wiki main page](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki) at the bottom right under the TOC, you'll see the below link to clone the wiki. Then you should be able to make PRs.
![image](https://user-images.githubusercontent.com/19942418/67606739-235bee00-f737-11e9-94fa-4f1ab776b94d.png)

**Comment by leniel** [comment]
@jennyf19 this is the link I sent in my previous comment. There's no way to send a PR here on GitHub. Somehow the Wiki is closed.

If any of you know how to send a PR to the wiki, let me know. I fixed some doc links locally but I can't send a PR.

**Comment by jennyf19** [comment]
@negoe -> Do you know what's up w/the wiki for JS? An outside contributor should be able to clone the wiki locally and do a PR, could you check on the settings for the repo? Thanks

cc: @leniel @jmprieur

**Comment by jasonnutter** [comment]
Unfortunately, I don't believe Github supports pull requests for wikis (even though wikis are themselves Git repos). If you have corrections you would like us to make, please open a separate issue detailing the changes and we'll take a look, thanks!

**Comment by leniel** [comment]
@jasonnutter yeah... looks like [this is true](https://stackoverflow.com/q/10642928/114029) but really not good when it comes to collaboration.

Here [on this post](https://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html) there's a proposed solution.

**Comment by jasonnutter** [comment]
@leniel Thanks for the links. I agree its unfortunate and not conducive to outside contributions. Generally speaking, we are hoping to move more of our documentation to docs.microsoft.com (and off of Github Wikis), which does provide functionality for outside contributors to make contributions.
