### ISSUE TITLE
MSAL python 3 support ?

### ISSUE THREAD

**Issue by bilalAchahbar** [AzureAD/microsoft-authentication-library-for-js#1079]
I installed the current wheel library of msal from the official pypi reposirory.
But the wheel file has a python version of v2.
I try to install this library into my Azure Databricks Cluster where python 3 is configured. This conflicts because the wheel library of msal has python 2 configured. The library installed perfectly when I downgraded the cluster to python 2. But that can't be the solution because all my notebooks are programmed in python 3. I also can't think of any idea why the msal library isn't already in python 3 ?
Any workaround for this one.

**Comment by jasonnutter** [comment]
@bilalAchahbar This the repo for MSAL.js, here is the link for the Python repo: https://github.com/AzureAD/microsoft-authentication-library-for-python
