### ISSUE TITLE
MSAL ignoring MSA access token expiry times

### ISSUE THREAD

**Issue by shane7218** [AzureAD/microsoft-authentication-library-for-js#1081]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- ALL
## Library version

<pre><code>
Library version: 1.1.3

</code></pre>

## Current behavior

When requesting delegated MSA access tokens we are getting the incorrect expiry date set in the MSAL session storage. I believe even for these requests MSAL is only saving the IDToken expiry and is ignoring the Access token expiry which is important for our use case.

## Expected behavior

MSAL should set the expiresIn time for Access token requests to the access token expiry time and not the Id Token expiry time

## Minimal reproduction of the problem with instructions

Request a delegated authentication token using MSA

**Comment by tnorling** [comment]
@shane7218 Sorry for the delayed response. Is this still an issue when upgrading to a newer version? e.g. ```msal@1.3.0-beta.1```?

**Comment by tnorling** [comment]
This should be fixed by updating by `msal@1.3.0`. Let us know if this is not the case.
