### ISSUE TITLE
loginRedirect does not redirect in some flows

### ISSUE THREAD

**Issue by darsney** [AzureAD/microsoft-authentication-library-for-js#1084]
Specifically, in adal => msal SSO flows, loginRedirect fires ATS and does not actually redirect.  In these cases, users may need to use handleRedirectCallback to continue their page load flow, which requires referencing potentially local variables in the handleRedirectCallback closure.  

That is fine, as long as the page doesn't redirect, but if the page does in fact redirect, the redirectCallback function will not execute as intended since the state from when the callback was registered is lost.  

It may be more clear to return a promise from loginRedirect for circumstances where the page does not actually redirect, so users can continue their page load flow without abusing handleRedirectCallback 

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/3844c9eedb7f07e6fc927d1039af9a8f54366cad/lib/msal-core/src/UserAgentApplication.ts#L302

**Comment by jasonnutter** [comment]
@pkanher617 Do plan to change this behavior for v2?

**Comment by pkanher617** [comment]
This behavior will change in v2, ADAL SSO in loginRedirect will still redirect but will not prompt for credentials. Closing for now.
