### ISSUE TITLE
unnecessary `async` key word

### ISSUE THREAD

**Issue by maljuburi** [AzureAD/microsoft-authentication-library-for-js#1085]
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/3844c9eedb7f07e6fc927d1039af9a8f54366cad/samples/react-sample-app/src/AuthProvider.js#L29

`await` isn't being used in this code block, I don't think `async` is necessary here.

**Comment by jasonnutter** [comment]
While it is `true` that `async` is required to use `await`, it also inherently makes the function return a promise. In this case, the function already explicitly returns a promise, so you're right, its technically not needed, but I just added it for consistency with the other functions in the file that return a promise.  

Appreciate the feedback, we're always looking to improve our samples and make them clearer, so I'll keep this in mind as we make further improvements.
