### ISSUE TITLE
Feature Request: offer a new (optional) property on the config passed to UserAgentApplication, "redirectUriForTokenRefresh" which is used only in the case of silent token refresh with iframe.

### ISSUE THREAD

**Issue by sstchur** [AzureAD/microsoft-authentication-library-for-js#1087]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [X] Chrome version latest
- [X] Firefox version latest
- [ ] IE version XX
- [X] Edge version latest
- [X] Safari version latest

## msal 1.2.0-beta2

<pre><code>
Library version: 1.2.0-beta2
</code></pre>

## Current behavior
For SPAs today, the config passed to the constructor of UserAgentApplication has a property called "redirectUri" which, when set will instruct MSAL where to redirect the browser after successful interactive sign in.  This is fine, but this same URL will be used when MSAL creates an iframe for Silent Token refresh, thereby causing an additional hit to our server to serve up our SPA.  Despire the iframe getting destroyed within 50 ms, some requests could still be sent out from the SPA in the iframe, which is suboptimal.

## Expected behavior
If the config passed to UserAgentApplication offered an additional property, called something like "redirectUriForTokenRefresh" (which could default to the same value as redirectUri if not set), it would give consumers the opportunity to provide a *different* redirect Uri in the case of silent token refresh.  This is useful because (assuming the application author has registered the additional reply URL in AAD), he could then provide a URL such as /auth which is nothing more than a cached blank page.  This would be optimal as it would return very fast and not make any additional requests.

**Comment by sstchur** [comment]
@sameerag tagging you in this issue, as we previously discussed

**Comment by sameerag** [comment]
Thanks @sstchur. Will have a PR for this in the coming week, please watch out this space for the status.

**Comment by AndrewCraswell** [comment]
Just want to clarify, I know some time back it was made possible to use Popup authentication mode and set the `redirectUri` to a blank `/auth.html` file to prevent the site from reloading in the iframe. This was working pretty well when I tried it and was super cool. But for Redirect login, I don't think this is possible. Would the PR that is put together remedy this issue for Redirect login, and if so, will there be some documentation put together? It will get a bit unclear how this impacts the Popup login method using the `redirectUri` config, or how the behavior will be different.

The `redirectUri`, `navigateToLoginRequestUrl`, and now some sort of new `redirectUriForTokenRefresh` could get even more complicated.

**Comment by sstchur** [comment]
Would this impact popup at all though?  redirectUriForTokenRefresh would (I expect) only come into play for token refresh (and never for login, be it redirect login or popup login).  So I would think, regardless of whether or not the refresh is happening via popup or iframe, if (and only if) the redirectUriForTokenRefresh is set, the redirect would go to the specified URL (either in an iframe or in a popup).  Either way, it seems like it should work (and with the added benefit that a redirect to a blank page (or whatever the dev chooses) would more efficient than a redirect back to a page that tries to spin up the entire app, make http requests, etc...)

**Comment by sameerag** [comment]
Okay. Let me chime in, @AndrewCraswell, the idea is to enable a user set a "redirectUri" per request and fall back to the default(which can be the redirect page user would want to be redirected to for interactive cases). This translates to `aquireTokenSilent` redirecting to the blank page if needed. This should not impact `popup` or `redirect` flows. 

Please let me know if you have further questions.

**Comment by sameerag** [comment]
#1116 adds this feature.

**Comment by sameerag** [comment]
Closing this as the PR #1116 is now merged and released in `msal@1.2.0-beta.5`
