### ISSUE TITLE
Renewing idToken fails

### ISSUE THREAD

**Issue by LeanderVanEck** [AzureAD/microsoft-authentication-library-for-js#109]
For renewing the idToken i noticed some bugs in msal.js

in function UserAgentApplication.prototype.renewIdToken there is a reference to "adalIdTokenFrame". This should be "msalIdTokenFrame". Otherwise navigation won't even happen.

Also in acquireTokenSiltent the response type is token and not id_token. So the navigation url that is being constructed is not valid.

**Comment by LeanderVanEck** [comment]
@rohitnarula7176 
That's awesome. Works perfectly.

**Comment by rohitnarula7176** [comment]
Closing this issue. Fixed in dev
