### ISSUE TITLE
Typo in readme msalnstance should be msalInstance

### ISSUE THREAD

**Issue by fippli** [AzureAD/microsoft-authentication-library-for-js#1093]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version
Latest
<pre><code>
Library version: X.Y.Z

</code></pre>

## Current behavior

Typo in README `return msalnstance.acquireTokenPopup(tokenRequest)`

## Expected behavior

`msalnstance` should be `msalInstance`

## Minimal reproduction of the problem with instructions

1. Go to [https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/README.md](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/README.md)
2. Search for "msalnstance" and you will find it

**Comment by jasonnutter** [comment]
Fixed, thanks for the heads up!
