### ISSUE TITLE
API permissions not working

### ISSUE THREAD

**Issue by srasool** [AzureAD/microsoft-authentication-library-for-js#1094]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version 76.0.3809.132
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 1.1.3

</code></pre>

## Current behavior

I have created an AAD app with Azure Service Management api permissions and the scope listed on the portals say no admin consent required.

https://management.azure.com/user_impersonation

Admin consent required
No

But when i run my sample app using msal and after successful login my sample app was redirected to a UI popup saying admin approval required, I am not sure which admin it is referring if its azure subscription admin (which I am ) and even tried login again with my credentials but it always redirected to the same UI popup

**Comment by jasonnutter** [comment]
@srasool Is this in the Microsoft 1st party tenant? It sounds like this permission is restricted at the tenant level, and you would need a tenant admin to grant the permission. 

https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent#admin-restricted-permissions

@manoj-rath Are you or someone from your team able to provide any additional insight?

**Comment by srasool** [comment]
@jasonnutter thanks for response. I might be wrong in my understanding for how it should work. Our scenario is basically we want to release an app to third party customers and they should be able to login using their AAD login and call Azure ARM apis (get azure resources list etc.) My understanding is we would create a multi-tenant AAD app in our tenant and use that app (client id basically ) in msal login flow, once user logged in using his creds there will be a new SP created in their tenant to access azure resources.

**Comment by jasonnutter** [comment]
@srasool Have you tried setting this up in a custom tenant (as opposed to the Microsoft 1st-party tenant)?

**Comment by srasool** [comment]
@jasonnutter yes it worked on custom tenant. I reached out the internal teams and learned that i need to make my AAD app as 1P app. Thanks for the info

**Comment by jasonnutter** [comment]
@srasool Thanks for the update, glad you were able to get it working!
