### ISSUE TITLE
Enable `"strictNullChecks": true` everywhere

### ISSUE THREAD

**Issue by freshtonic** [AzureAD/microsoft-authentication-library-for-js#1097]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 1.2.0-beta.3
</code></pre>

## Current behavior

I discovered a bug where `UserAgentApplication.buildIDTokenRequest` was receiving an `undefined` `AuthenticationParameters` object and failing at runtime. On further investigation I could not comprehend how the calling code could compile because in the scope of the calling code the `request` parameter is optional. I then realised `strictNullChecks` was not enabled on the codebase. After enabling `strictNullChecks` the codebase is littered with compiler errors too numerous to be listed here.

## Expected behavior

The code should compile with `strictNullChecks` enabled.

## Minimal reproduction of the problem with instructions

Enable `strictNullChecks` in the base `tsconfig.base.json`, open the project in VSCode and see the red wiggly lines all over the place.

**Comment by jasonnutter** [comment]
@freshtonic Thanks for the issue, didn't realize that was disabled, I'll definitely take a look.

**Comment by ab0nent** [comment]
Is there any update on this bug? Will it be fixed? Thanks.

**Comment by jasonnutter** [comment]
@ab0nent We haven't had a chance to get to this, but we will at some point soon.

**Comment by sameerag** [comment]
We are working on this in the background, since some of the code needs to be rewritten or needs additional checks, we are taking an incremental approach. This will be updated once we have everything in place. FYI for future libraries, we are enabling this from the start.

**Comment by tnorling** [comment]
Closing as this will no longer be picked up for version 1.x. This work will be done in 2.x, the first part of which has been started in #2602
