### ISSUE TITLE
is auto-login possible using id_token to acquire access_token?

### ISSUE THREAD

**Issue by Danieliverant** [AzureAD/microsoft-authentication-library-for-js#1098]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[X ] Other... Please describe: Question - is autologin possible?
</code></pre>

## Browser:
- [ X] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 1.0.1

</code></pre>

## Current behavior

I have an Angular application using MSAL.js for authentication.

I've created a sign-up page (not Microsoft's), that sends the credentials to the server, the server opens a user in Azure AD and responds with an id_token.

is it possible to use this id_token to acquire access_token and by that way authenticate the user automatically?

I've tried to save it under "msal.idtoken" and "msal.nonce.idtoken" in the localStorage (in the same way MSAL.js does) and call "acuireTokenSilent" but with no success.

**Comment by jasonnutter** [comment]
@Danieliverant Apologies for the delay, this issue fell through the cracks.

This is a known short-coming of MSAL Angular, but will be available in the next version of MSAL Angular, which will use MSAL 1.x, which has this capability. I'll post an update when there is a version available to try.

**Comment by jasonnutter** [comment]
We are adding a new top-level API for this use case, `ssoSilent`, which you can track at #1166. 

Closing, let us know if you have further questions.
