### ISSUE TITLE
Angular 7 msal-angular login problem with IE11

### ISSUE THREAD

**Issue by hearstfy** [AzureAD/microsoft-authentication-library-for-js#1099]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [x ] IE version 11
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: latest

</code></pre>

## Current behavior

First issue is  Even tough isPopup is set to false IE opens popup for password after selecting or entering account info.
Second issue is after logout, when i try to login with different account even tough i enter new account or select different account, IE does not ask for password and logs in directly to previous logged out account.

I faced these issues in both adal.js and msal.js wrappers for Angular.
Works fine in Chrome and Firefox

## Expected behavior

Should login to correct account in IE11.

**Comment by jasonnutter** [comment]
@hearstfy Can you please provide the MSAL configuration code your app is using?

**Comment by hearstfy** [comment]
I use Adal.js at the moment. Config is as follows:

{
  clientId: "xxxx",
  tenant: "xxx",
  cacheLocation: "localStorage",
  navigateToLoginRequestUrl: true,
  endpoints: {
    api: "xxx"
  }
}

**Comment by jasonnutter** [comment]
@hearstfy Can you provide the configuration you use when you tried `@azure/msal-angular`?

**Comment by hearstfy** [comment]
Hi @jasonnutter, I used same config;

{
      clientID: "xxx",
      authority: "https://login.microsoftonline.com/xxx",
      popUp: false,
      storeAuthStateInCookie: true
    }

**Comment by jasonnutter** [comment]
@hearstfy would you be able to share a sample application that demonstrates this behavior? Feel free to create a private repo on Github and then invite me to access it, thanks!

**Comment by hearstfy** [comment]
@jasonnutter, invited you to sample repo. I removed clientID and authority info because they have client info.

**Comment by jasonnutter** [comment]
@hearstfy Thanks! I'll let you know when I have taken a look and/or if I have any further questions.

**Comment by jasonnutter** [comment]
I believe this should be fixed in teh new version of MSAL Angular, closing.
