### ISSUE TITLE
B2C custom policies authority url

### ISSUE THREAD

**Issue by foramkumar-parekh** [AzureAD/microsoft-authentication-library-for-js#1101]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[X ] Other... Please describe:
</code></pre>

## Library version

<pre><code>
Library version: @azure/msal-angular@0.1.2

</code></pre>

I have B2C custom policies for authentication and I want to use them in my angular application. So with msal when I tried adding the authority it is saying that the authority is not valid. below are some of the combinations I tried.

- https://mytenant.b2clogin.com/tfp/mytenant.onmicrosoft.com/B2C_1A_signin/
- https://mytenant.b2clogin.com/mytenant.onmicrosoft.com/B2C_1A_signin/
- https://mytenant.b2clogin.com/mytenant.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_signin/
- https://mytenant.b2clogin.com/mytenant.onmicrosoft.com/oauth2/v2.0/authorize?p=B2C_1A_signin&client_id=myclientId&nonce=defaultNonce&redirect_uri=https%3A%2F%2Fjwt.ws&scope=openid&response_type=id_token&prompt=login

Please share the correct authority format to use the B2C custom policies with MSAL

**Comment by jasonnutter** [comment]
@foramkumar-parekh In your configuration, try setting `validateAuthority` to `false`. This should allow you to use b2clogin.com.

**Comment by foramkumar-parekh** [comment]
And which Url format, from the question, will work?

**Comment by jasonnutter** [comment]
I believe `https://mytenant.b2clogin.com/mytenant.onmicrosoft.com/B2C_1A_signin/` is the correct format, @pkanher617 can you please confirm?

**Comment by jmckennon** [comment]
Closing this issue, as it's been some time and I'm assuming the issue has been resolved. Feel free to open a new issue if you have further questions.
