### ISSUE TITLE
Prevent passing config through the constructor

### ISSUE THREAD

**Issue by daniel-seitz** [AzureAD/microsoft-authentication-library-for-js#1103]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Library version

<pre><code>
Library version: all

</code></pre>

## Current behavior
We have got an up-to-date Angular App with a defined service that new's up UserAgentApplication. However this is not desired as it prevents DI and testability. Right now I dont know of a better way so here is what I would like:

## Expected behavior
Have an empty constructor and a public setConfig method.
This would allow for depedency injection where we can overwrite the implementation in our tests.

I feel like there is an alternative solution with the Angular Injector but to make things more complicated, we load some config from the server on runtime and hence likely cannot create a static injector.

## Minimal reproduction of the problem with instructions

not needed

**Comment by jasonnutter** [comment]
@daniel-seitz Can you provide some pseudo-code that would demonstrate what this would look like? Would help me better understand the ask, thanks!

**Comment by daniel-seitz** [comment]
@jasonnutter sure, thanks for asking.

Currently its looking similar to this:

    export class MyAuthService {
        private msal: UserAgentApplication;

        constructor() {}

        configure(config) {
             this.msal = new UserAgentApplication(config.clientId, config.authority, youGetThePoint);
        }
    }

And what I would like is something like this:

    export class MyBetterAuthService {
   
        constructor(private msal: UserAgentApplication) {}

        configure(config) {
             this.msal.setConfig(config.clientId, config.authority, youGetThePoint);
        }
    }

What this allows later is to say something along

    describe(....

        const sut = fancyDI.get(MyBetterAuthService);

        beforeAll(
              .... 
              sut.configure(someTestConfig)
              .... 
        )

        it(..... expect... )

    );

Which now, I dont know how to do because the real UserAgentApplication is being 'new'ed up in my class. Something which might (not sure) be even better is if we could do something like this:

    export class MyNotSureIfThisIsPossibleAuthService {
   
        constructor(private @Inject(someConfigForNow into) msal: UserAgentApplication) {}

        // not needed in this case
        // configure(config) {
        //      this.msal.setConfig(config.clientId, config.authority, youGetThePoint);
        // }
    }

What do you think?

Oh, btw, one reason for not directly injecting the config now is that we load some parts async from the server .. and might not have the full config once the service is created. Only at a later point we would call the configure method and start using the object.

**Comment by jasonnutter** [comment]
@daniel-seitz Thank you for that, very helpful. We have heard this request from other customers, so we'll definitely consider it. I'll follow up when I get a chance to dig into this in more detail.

**Comment by daniel-seitz** [comment]
@jasonnutter you are welcome, thank you for having an open ear.

If you agree on a new method I could create a PR. This would be easy to implement but a breaking change though. The docs would need an update as well.

Oh, I just realize that the code snippet for the tests above should be improved, will do if github allows me.

**Comment by jasonnutter** [comment]
@daniel-seitz Don't worry about on PR for the moment, as were working heavily on Angular to get it updated for MSAL 1 and the new versions of Angular. Because this will result in a new major version, we will consider pulling in other breaking API changes such as this. Once the baseline work is completed, I will be revisiting this and make a decision on whether or not to include it for that major version release.

**Comment by jasonnutter** [comment]
@daniel-seitz This should be doable using factory providers, as shown here: https://github.com/Azure-Samples/active-directory-javascript-singlepageapp-angular/blob/master/src/app/app.component.spec.ts

**Comment by jasonnutter** [comment]
Documentation on how to configure MSAL Angular is available here: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/configuration.md

Closing.
