### ISSUE TITLE
Forgot password with signup-signin policy

### ISSUE THREAD

**Issue by DibranMulder** [AzureAD/microsoft-authentication-library-for-js#111]
When using a combined signup - signin policy in Azure B2C, users have to handle the forgot password scenario themselves. Please take a look at the [documentation](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-reference-policies).

> How do I link a sign-up or sign-in policy with a password reset policy?
When you create a sign-up or sign-in policy (with local accounts), you see a Forgot password? link on the first page of the experience. Clicking this link doesn't automatically trigger a password reset policy.
Instead, the error code AADB2C90118 is returned to your app. Your app needs to handle this error code by invoking a specific password reset policy. For more information, see a sample that demonstrates the approach of linking policies.

It would be nice if the library also took care of this. So it should redirect to the forgot password policy page if this particular error is returned. 

The following url is returned from the signup - signin page:

> https://someurl.com/#error=access_denied&error_description=AADB2C90118: The user has forgotten their password.
> Correlation ID: 6df37966-bc26-4931-8e1a-6be0ec753efc
> Timestamp: 2017-08-16 06:58:01Z

**Comment by mikelunn** [comment]
I'm having the same issue. I'm not sure why the forgot password policy is not being handled the same way the sign up policy is.

**Comment by DibranMulder** [comment]
I created an issue at the demo repo i'm using. It might be helpful to solve this issue.
https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp/issues/9

**Comment by jmprieur** [comment]
Thanks for the feedback, @DibranMulder @mikelunn 
Adding @saraford to keep track of the request, and @danieldobalian so that we update the error handling documentation.
I don't think that we would do that we would add this to msal.js itself. but maybe to a higher level API.
Closing this msal.js issue for now.
