### ISSUE TITLE
iOS build errors in Azure DevOps

### ISSUE THREAD

**Issue by mtanml** [AzureAD/microsoft-authentication-library-for-js#1111]
## I'm submitting a...

<pre><code>
[X ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 4.7.0

</code></pre>

## Current behavior

Error when building for iOS in Azure DevOps:   MTOUCH : error MT2002: Failed to resolve "System.Collections.Generic.Stack`1" reference from "mscorlib, Version=2.0.5.0, Culture=neutral, 

## Expected behavior

Succesful build in Azure DevOps

## Minimal reproduction of the problem with instructions

The issue started to appear when we updated to version 4.5.1, and also occurs in 4.7.   We rolled back to 4.4 and the build was successful.

**Comment by jasonnutter** [comment]
@mtanml I think you meant to file this in the MSAL Objective-C repo? https://github.com/AzureAD/microsoft-authentication-library-for-objc

**Comment by mtanml** [comment]
Argh... sorry... yes
