### ISSUE TITLE
Allow to open the new account form instead of login form

### ISSUE THREAD

**Issue by sarahshul** [AzureAD/microsoft-authentication-library-for-js#112]
There are cases where we know the user is a new user (for example - the user press the: Join us now button).

I would like in this case to show the user the create new account form immediately and not to force him to go to the log in form and then he have to press the create new account.

In some cases, it is important that he wouldn't be able to do the log in - just to registrar.

**Comment by rohitnarula7176** [comment]
@sarahshul This is not something we can handle from the library perspective. Closing this issue.
