### ISSUE TITLE
Whats the plan for this repo to move to angular 8?

### ISSUE THREAD

**Issue by tbudukh** [AzureAD/microsoft-authentication-library-for-js#1121]
Whats the plan for moving the repo from angular 7 to angular 8?

We're moving our project to angular 8 and w need MSAL to be on Angular 8 as well to be able to use it.. Is there a plan for that?

**Comment by jasonnutter** [comment]
@tbudukh We are currently working on upgrading `@azure/msal-angular` to support the newest versions on Angular, including 6/7/8/9, and are committed to having this work completed by the end of the year. We will make an announcement when that work has been completed and released.
