### ISSUE TITLE
loginRedirect or loginPopup works in IE11 debug mode only(after opening the console)

### ISSUE THREAD

**Issue by venki786** [AzureAD/microsoft-authentication-library-for-js#1125]
In IE11, while calling the onsignin, navigation not happening either using the redirect or popup,

Tried with sample react-sample-app also, same behaviour

works only when i open the console(inspect element).

async onSignIn(redirect) {
    if (redirect) {
      return msalApp.loginRedirect(GRAPH_REQUESTS.LOGIN);
    }

    const loginResponse = await msalApp
      .loginPopup(GRAPH_REQUESTS.LOGIN)
      .catch(error => {
        console.log(error)
      });
    console.log({ loginResponse })
  }

**Comment by jasonnutter** [comment]
@venki786 Are there errors in the JavaScript console when this happens?

**Comment by venki786** [comment]
No errors in javascript console, if again i call onsignin it shows errors like below

"Login_In_Progress: Error during login call - login is already in progress"

if i try with loginPopup in IE11, popup shows blank window.

**Comment by venki786** [comment]
Issue resolve, this is due to below code in UserAgentApplication
system: {
        navigateFrameWait: 0,
        logger: {
            error: console.error,
            errorPii: console.error,
            info: console.log,
            infoPii: console.log,
            verbose: console.log,
            verbosePii: console.log,
            warning: console.warn,
            warningPii: console.warn
        }
    }
After removing the above code it works fine. 

Ref: https://www.wikitechy.com/tutorials/javascript/why-does-javascript-only-work-after-opening-developer-tools-in-ie-once

**Comment by jasonnutter** [comment]
@venki786 Ah, makes sense. I'll see if I can make it so the sample doesn't do that by default.
