### ISSUE TITLE
Azure B2C | Changing Policy Dynamically

### ISSUE THREAD

**Issue by raghavankarthik80** [AzureAD/microsoft-authentication-library-for-js#1128]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: X.Y.Z

</code></pre>

## Current behavior

In our application we have two main policy Signin and EditEmail Id. After i Signin to the Application with the Signin Policy i am able to browse through the application but when i click on EditEmail, i want ot change the Authority with the EditEmail Policy. I have the change the authroity and calling the LoginRedirect method. The method  first goes to the Signin Policy to relogin and then goes to the EditEmail Policy.

## Expected behavior

I am expecting it to directly go the EditEmail policy without loginin Again. Its being possible in Asp.net but i am not able to achieve in MSAL-Angular 

In ASP.Net they are able to pass the authenication properties and when they are navigating to B2C screen(Edit Email Policy) its not asking for Authorization again and directly going to Edit Email Page.

**Comment by raghavankarthik80** [comment]
@FrankHu-MSFT  nad @jmckennon  :Can you please help me out in resolving this issue. Is it a still a defect or any solution is avaiable. I have checked another issue quite similar to this :https://github.com/MicrosoftDocs/azure-docs/issues/41013.. Like to know the status

**Comment by FrankHu-MSFT** [comment]
@jennyf19 Can you help on this issue?

**Comment by jennyf19** [comment]
@raghavankarthik80 I'm not familiar w/the JS library, but in .NET, developers can pass in [`Prompt.NoPrompt`](https://github.com/azuread/microsoft-authentication-library-for-dotnet/wiki/AAD-B2C-specifics#special-case-of-editprofile-and-resetpassword-policies) which will not send a [prompt](https://github.com/azuread/microsoft-authentication-library-for-dotnet/wiki/Acquiring-tokens-interactively#withprompt) to the authentication server (b2c), and rather let it decide to show a prompt based on if the current user has an active session. 

This will allow the user, after hitting the sign-up/sign-in policy, to not have to sign in again, but go directly to the edit profile page.

@sameerag @DarylThayil Can you confirm if the JS library has something similar to the .NET library? Which has the option of sending no prompt to B2C (see above links for more details).

cc: @FrankHu-MSFT @jmprieur

**Comment by sameerag** [comment]
I think we do, but we never had samples for this use case. @raghavankarthik80 Let me check this once and reach out in a few days?

**Comment by raghavankarthik80** [comment]
@sameerag @DarylThayil  We are middle of the development phase and client are behind us. Can you please help us out as early as possible.

**Comment by jennyf19** [comment]
@sameerag @DarylThayil Looks like you have [it here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/d10a5b5fb789a319b0058b48e1f1a52d1b2f6824/lib/msal-core/src/utils/Constants.ts#L25)...is this surfaced to the developer? it doesn't need a sample to be working, just if sending this prompt means you send no prompt (nothing for this value in the header) to b2c ests, based on the code, it looks like you send `prompt=none`. 

for us in .NET sending `prompt=none` is not the same as not sending anything for the prompt.

@raghavankarthik80

**Comment by sameerag** [comment]
`prompt=none` is appended by `acquireTokenSilent` calls only for `msal js`. And yes, it isn't same as not sending any prompt. My concern is more about using two policies. As long as it is a single user and we pass the policy as an `authority` in the `request`, this should work.  

@raghavankarthik80 Can you try this with `msal js` and let us know if you face any issues?

**Comment by sameerag** [comment]
My apologies on the delay. We are in middle of a release and I will be able to check this post release - please expect a response by Friday. cc @raghavankarthik80. If you need a more specific scenario debug for this (msal js) or a call since this seems urgent on your part, please email me @ sameera.gajjarapu@microsoft.com

**Comment by raghavankarthik80** [comment]
@sameerag I tried using MSAL.js and below are the activities I have performed.

I have set the useragentapplication object authority to different Policy
While calling the AquireTokenSilent I have passed the Client ID.

When I do this I am getting two main error:

1.	The first error is related to X-Frame-Options: deny error
2.	The second error its says Token does not match: When I try to debug I found that in the UserAgentApplication.ts file we have a line number 784 (method: getCachedToken) where you are validating he existing Authority in the Local Storage and the requested Authority, since these two authority does not match we have an error.
I hope the explanation is clear, if not please let me know
Please help me out in resolving this issue we have a go to Production by this month.

Thanks,
Karthik

**Comment by sameerag** [comment]
@raghavankarthik80 There are couple of things happening here:

- Policies that need interaction like "EditEmail" cannot be called using `acquireTokenSilent()` in `msal js`. `msal js` creates a hidden iframe for a silent calls and `B2C Service` blocks any policy executing an iframe. The guidance here is to make an interactive call. I do understand that a user login should be SSO but currently there is no easy way to do this in `msal js`. cc @ktsakas, we need to design an intermittent solution for use cases like these.

- We currently do not support `multiple policies` in `msal js`. We have an error `createMultipleAuthoritiesInCacheError` for mismatching authorities and for a B2C policy, each policy is an authority. This is a feature ask for `msal js` and will be probably planned in the upcoming quarter.

We are aware of these gaps in B2C use cases for `msal js` and there is an effort planned to address these in the upcoming quarter. Given these, `msal js` may not be the right library for your use today. 

We can still schedule a call tomorrow to discuss this in further detail if there is any intermediate solution that we can plug-in now for you. I can have the B2C dev pitch in here too if he has anything else to add. cc @ktsakas

**Comment by sameerag** [comment]
@raghavankarthik80 As we discussed offline, closing this issue; we will announce the support for multiple policies once we have clarity on the implementation with the B2C dev team. Please watch out for the announcement in the roadmap.
