### ISSUE TITLE
need for logoutPopup() [was logout: Should not redirect the user to our homepage]

### ISSUE THREAD

**Issue by rolandoldengarm** [AzureAD/microsoft-authentication-library-for-js#113]
When logging out, it is redirecting the user to the homepage. I know that you can specify the postlogoutRedirectUrl, but in an SPA like Angular this requires us to save everything in cache.
Ideally this happens in a popup, similar to logging in.

**Comment by jmprieur** [comment]
@rolandoldengarm : when login out we need to clear the cookies both for the application, and for https://msft.sts.microsoft.com. Clearing the cookies for https://msft.sts.microsoft.com can only be done by the STS itself (security isolation), and therefore it needs to redirect to the epostlogoutRedirectUrl afterwards.
This is by design

**Comment by rolandoldengarm** [comment]
@jmprieur but why can't this happen in a popup?

**Comment by jmprieur** [comment]
@rolandoldengarm : if you use the popup mode, I'd expect this to happen in the popup (I believe it does in plain JavaScript). Which Angular wrapper did you use for MSAL?

**Comment by rolandoldengarm** [comment]
@jmprieur login has two modes, loginPopup and loginRedirect. I use loginPopup and that works great.

however, logout only has one function: `logout()`. So what I'd like to see is a `logoutPopup()` method.

I'm not using any wrapper, using MSAL JS straight in an Angular 4 app :)

**Comment by IainAdamsLabs** [comment]
@rohitnarula7176 - Why is this closed? Has this feature been delivered? I can't see it in the library. Using msal 1.3.0

**Comment by jasonnutter** [comment]
@IainAdamsLabs No, `logoutPopup` has not been added. There is an open feature request for it here: #1386
