### ISSUE TITLE
Setting up a Synthetic User for Integration Tests

### ISSUE THREAD

**Issue by claudiordgz** [AzureAD/microsoft-authentication-library-for-js#1130]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[X] Other... Please describe: Tutorial on how to setup a Service Account that uses MSAL without two factor Auth
</code></pre>

## Browser:
- [X] Puppeteer

## Library version

<pre><code>
Library version: 1.1.3

</code></pre>

## Question

Hi, I'm new to Microsoft, and on the Statutory Reporting team building a new Application called SubLedger. I migrated from ADAL to MSAL on my React Frontend, but my backend is a v1.0 API (thank you for the wiki on scopes btw).

I want to set up integration tests as a Frontend User, using a tool called puppeteer, then I want to run it in a Stage in our Release Pipeline in Azure DevOps. 

How would I go around doing that? I've heard about using Service Accounts and putting them on Azure Key Vault, would that work? Even when it asks for MFA?

I'm looking for more information on that, and to a lesser extent, how to upgrade from a V1.0 API to a V2.0 API.

Kind regards,
Claudio

**Comment by sameerag** [comment]
We have MSIDLabs that may help you here. Please DM me since it is for internal use only and I can help you with the links and the team contacts for the same.

**Comment by claudiordgz** [comment]
Is there an `aka.ms` link?

**Comment by sameerag** [comment]
Yes, I responded to your DM today. Apologies for the delay.

**Comment by sameerag** [comment]
Shared the information offline since it is an internal microsoft setup. Closing this issue.
