### ISSUE TITLE
Dynamic configuration of Authority (User Flows)

### ISSUE THREAD

**Issue by cleberdantas** [AzureAD/microsoft-authentication-library-for-js#1135]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[X] Other... Please describe:
</code></pre>

## Question

Is it possible to have different user flows configured in one application? 

Today we can configure the `Authority` property in app.module.

Imagine that different areas of my application have different login pages. 

How can I change the last portion of the authority (which is the user flow at Azure AD B2C) dynamically?

**Comment by sameerag** [comment]
@cleberdantas Yes, you can. The `request` in `msal js`(code [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/src/AuthenticationParameters.ts) accepts `authority` and the user can pass in a different `authority` from that of the configured one during the initialization.

**Comment by sameerag** [comment]
@cleberdantas Closing this issue, Please raise a new one or comment here to haver this re-opened if the above answer is not helping you.
