### ISSUE TITLE
acquireTokenPopup promise doesn't reject on closing the popup without logging in.

### ISSUE THREAD

**Issue by LeanderVanEck** [AzureAD/microsoft-authentication-library-for-js#114]
When the popup is closed manually then the interval is cleared, but the promise doesn't get resolved or rejected.

See `UserAgentApplication.prototype.openWindow`

**Comment by rohitnarula7176** [comment]
@LeanderVanEck Issue is now fixed in dev. Please check and confirm.

**Comment by LeanderVanEck** [comment]
@rohitnarula7176 
Looks alright, thanks!

**Comment by JohnWeisz** [comment]
Thank you for fixing this, we've been getting ready to employ work-arounds to overcome the issue. When is this planned to be shipped to the CDN?

```
<script src="//secure.aadcdn.microsoftonline-p.com/lib/0.1.2/js/msal.min.js"></script>
```
