### ISSUE TITLE
Obtain Application roles in Access Token to pass to AAD secured API

### ISSUE THREAD

**Issue by januszj** [AzureAD/microsoft-authentication-library-for-js#1143]
## I'm submitting a question how to obtain Application roles in Access Token to pass to AAD secured API

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [X] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [X ] Edge version 79.0.309.40
- [ ] Safari version XX

## Library version 

<pre><code>
Library version: 1.1.3
</code></pre>

## Current behavior
Application consists of:
1 .WebApi on Core 3.1 secured by AAD using AzureADDefaults.JwtBearerAuthenticationScheme in Startup, and authorizations through services.AddAuthorization and setting up policies that match ones setup in Azure.
2. VueJs app that is using msal.js

I'm able successfully login in Vue App to AAD.
Call Web API by getting Id Token and then calling acquireTokenSilent and using Access token for that. This works fine for controllers with [Authorize].
But Access Token does not contain roles, so any API that is protected using role (eg [Authorize(Roles = "Manager")]) fails.

When running Web Api as Asp.net app and using AzureADDefaults.AuthenticationScheme roles are working fine, so Azure setup and authorization in WebApi is correct.

In Azure I created roles to be both User and Application (but either separately does not make difference), here is how it is defined in app registration manifest:
`
"appRoles": [
		{
			"allowedMemberTypes": [
				"Application",
				"User"
			], ..., "value": "Manager"},
`

## Expected behavior
Roles present in Access Token, so it can be pass to Web Api for validation.
According documentation: https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens Roles could / should be present in Access Token.

**Comment by jasonnutter** [comment]
I believe this is a known issue, already tracked in #677

**Comment by januszj** [comment]
@jasonnutter what I'm missing in token are roles not wids, roles are specific to application so this should not fall under the same issue

**Comment by jasonnutter** [comment]
@januszj Ah, apologies, my mistake. @hpsin would you know how to get the `roles` claim in the implicit flow?

**Comment by hpsin** [comment]
Same issue as referenced in #677 - long form values are not put into length-restricted tokens since it breaks browsers. We don't have a way around this.

**Comment by jasonnutter** [comment]
Closing, as there is nothing further for the library.
