### ISSUE TITLE
Support for authentication with client credentials

### ISSUE THREAD

**Issue by haonliu** [AzureAD/microsoft-authentication-library-for-js#1145]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
N/A
## Library version
N/A

## Expected behavior

I'm trying to authenticate to a Rest API in Azure Function without any user context. Currently I'm using client Id and Secret to authenticate,  something similar to this: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/34892e8d44d493df9754bc5692caebbccb451be3/lib/msal-core/endToEndTests/keyvault.js#L13

I'm wondering if there is support to authenticate with client credentials in msal, since there is a regression in adal-node.

## Minimal reproduction of the problem with instructions

N/A

**Comment by jasonnutter** [comment]
We do not currently support in this in MSAL. MSAL Node is on our roadmap, but that work has not been committed or scheduled yet.

Thanks for the feedback!
