### ISSUE TITLE
Cannot acquire access token for MSA account  

### ISSUE THREAD

**Issue by muying-cui** [AzureAD/microsoft-authentication-library-for-js#1148]
#607  I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version XX
- [x] Firefox version XX
- [x] IE version XX
- [x] Edge version XX
- [x] Safari version XX

## Library version

<pre><code>
Library version: 1.2.0-beta.4

</code></pre>

## Current behavior

While calling acquireTokenSilent() for MSA, since the user has not signed in, the prompt is present for login. However, using login.microsoft.com/common as authority for MSA does not work, here is the screenshot:

![image](https://user-images.githubusercontent.com/56005923/70479032-5e20a800-1a91-11ea-9800-89b80dbe5bf5.png)

It claims the login username must be a work or school address (AAD). The application A used to acquire token and constructed in UserAgentApplication has AAD and MSA configured as supported in **_first party onboarding portal_**:

![image](https://user-images.githubusercontent.com/56005923/70480191-f28c0a00-1a93-11ea-9b22-6494e741a719.png)

And **_the application B has application A pre-authorized_**, for AAD flow, providing applicationB's applicationID/.default as scope works for acquiring AAD access token, however the same scope for MSA does not work.

## Expected behavior

MSA users should be able to login and acquire access token using login.microsoft.com/common as the authority.

## Minimal reproduction of the problem with instructions

Use login.microsoft.com/common as the authority and use the applicationID/.default as scope (the same scope used to successfully acquire AAD token) and call acquireTokenSilent() with no user signed in. MSA user is prompted to login but error message is present and preventing the MSA user to login.

**Comment by jasonnutter** [comment]
@pkanher617 @sameerag Any thoughts? Chatted with @muying-cui in Teams, and I'm stumped on this issue.

**Comment by sameerag** [comment]
I think MSA is supported only on v2 and `.default` as scope works for only v1. That could be the issue. @hpsin can you add more?

**Comment by hpsin** [comment]
Both are v2 only. Can you confirm that the resource you're accessing also supports MSA? We can't emit tokens for users that the token recipient doesn't support.

**Comment by hpsin** [comment]
Ah, you're not even requesting a token here for a resource. Can you copy and paste that entire URL here?

**Comment by muying-cui** [comment]
The app A that has both AAD and MSA configured has its application ID constructed in UserAgentApplication, and app B is given as the scope with .default.

The login request went to: https://login.microsoftonline.com/**consumers**/oauth2/v2.0/authorize?response_type=id_token&scope=9e4a5442-a5c9-4f6f-b03f-5b9fcaaf24b1%2F.default%20openid%20profile&client_id=c1f66aa2-edcf-4a40-81cb-7710724e8e04&redirect_uri=https%3A%2F%2Fsdx.officeapps-dev.live.com%2Fsdx-msa.html&state=584cd7f2-3f1d-4908-a4aa-1f02a698c2e4&nonce=6f882eb4-b3b5-4846-9174-77653ca402d3&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=1.2.0-beta.4&login_hint=cszerostrike%40hotmail.com&client-request-id=c93f739f-7e30-4775-ad5e-9a2960652760&response_mode=fragment

Error message received: invalid_scope: The provided value for the input parameter 'scope' is not valid. The scope '9e4a5442-a5c9-4f6f-b03f-5b9fcaaf24b1/.default openid profile' does not exist.

**Comment by hpsin** [comment]
Your resource doesn't exist in MSA - the same request (with a different ID) works with user.read.  Did App B mark that MSA was supported in their registration?

**Comment by muying-cui** [comment]
App A has AAD and MSA configured as supported in first party onboarding site, App B only has AAD configured, but App B has App A as pre-authorized with scopes. I have also tried to use the pre-authorized scope in the access token request, but got the error: 

_invalid_request: The request is not valid. The application is a first party application, the user does not have consent, and users are not permitted to consent to first party applications. Rather, the first party application should obtain pre-authorization for the resource server._

**Comment by hpsin** [comment]
App B does not exist in MSA - you can't ask for a scope that MSA doesn't know about.  You must remove the scope from the request and only ask for it after you know if the user is in MSA or AAD.

**Comment by muying-cui** [comment]
In our WebAuth.Implicit component, when our callers make a call to us for access tokens, they already let us know whether the user is MSA or AAD. And when you mentioned App B does not exist in MSA, are you saying if App B also has MSA configured in first party onboarding portal, the request would have worked?

So in order to acquire MSA access token, the client (App A) needs to have MSA configured AND the resource (App B) with App A pre-authed?

**Comment by hpsin** [comment]
That's correct.
