### ISSUE TITLE
Getting "Permission Denied" exception in Edge, when using MSAL.js

### ISSUE THREAD

**Issue by dannygar** [AzureAD/microsoft-authentication-library-for-js#115]
Running the same code in Chrome has no issues and the client SPA app (angular4+msal) successfully authenticates with AD v2. The apps calls MSAL, which presents with a popup window prompting for user credentials. Once, authenticated, the popup window is closed and the app is redirected to the ReplyUrl as expected. However, when launching this app in Edge browser, the app hangs with an empty popup window remaining opened with about:blank address line. Just before it hung, I can see the MSAL is trying to redirect to the app's ReplyURL, but in the popup window rather than in a parent window, and then it hangs with an opened empty popup window.
Debugging the code, I found that MSAL.js library throws an exception when trying to locate the current windows location at the line 1254, when it is trying to execute this line:
if (popupWindow.location.href.indexOf(_this.redirectUri) !== -1) {
...
}
The exception thrown is #-2146828218 and the message: "Permission denied".

![msal1](https://user-images.githubusercontent.com/1878251/29423391-9458062a-8349-11e7-84ef-feb987d90af9.png)
![msal2](https://user-images.githubusercontent.com/1878251/29423392-945cfe50-8349-11e7-9171-72dcc8b500ab.png)

**Comment by danieldobalian** [comment]
@rohitnarula7176 this is the case Vittorio referenced over email if you can take a look.

**Comment by rohitnarula7176** [comment]
@parakhj Jean-Marc pointed me to this https://github.com/Azure-Samples/active-directory-b2c-javascript-angular2.4-spa created by you and I was able to sign in to this app using my google account in Edge. window.open returns a NULL reference object if Enable Protected Mode is checked under Internet Options->Security->Security Level for this zone. Can you check to see if Enable Protected Mode is checked in your browser. We can have a skype session and I can go over this with you.
