### ISSUE TITLE
urlContainsHash removed from public API

### ISSUE THREAD

**Issue by anton-gorbikov** [AzureAD/microsoft-authentication-library-for-js#1151]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version XX
- [x] Firefox version XX
- [ ] IE version XX
- [x] Edge version XX
- [x] Safari version XX

## Library version

<pre><code>
Library version: 1.2.0
</code></pre>

## Current behavior
`urlContainsHash` is missing in the public API

## Expected behavior
1. `urlContainsHash` removal should be mentioned as a breaking change;
1. Informational messages about `isCallback` deprecation should not be logged as public API doesn't contain other options.

## Minimal reproduction of the problem with instructions
In version 1.1.3 calling `isCallback` function resulted in informational message: `isCallback will be deprecated in favor of urlContainsHash in MSAL.js v2.0.`. We've changed the `isCallback` function to `urlContainsHash`. But in version 1.2.0 this function was removed from the UserAgentApplication prototype.

**Comment by sameerag** [comment]
@anton-gorbikov Thanks for bring this to our notice. This was an unintended side-effect of a code consolidation made for url helper functions. Can this wait until the next release or would you need a patch?

**Comment by anton-gorbikov** [comment]
@sameerag Thanks for quick reply and confirming that it's unintended. As for me it can wait. The change in the code was minimal, I just replaced `urlContainsHash` back to `isCallback`.
