### ISSUE TITLE
Add `sideEffects: false` to package.json so webpack 4 can do better treeshaking

### ISSUE THREAD

**Issue by TheLarkInn** [AzureAD/microsoft-authentication-library-for-js#1153]
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report  
- [ ] Performance issue
- [x] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX
- [x] Not relevant XX

## Current behavior

There isn't a sideEffects false field

## Expected behavior

There is a sideEffects false field

For prior work here: 
https://github.com/microsoft/fast-dna/issues/367

Also why you want the sideEffects field in a package with es modules: 
https://stackoverflow.com/questions/49160752/what-does-webpack-4-expect-from-a-package-with-sideeffects-false

**Comment by jasonnutter** [comment]
@TheLarkInn Thanks Sean! We'll take a look at enabling this.
