### ISSUE TITLE
loginInProgress error when invalid user email provided. This does not reset

### ISSUE THREAD

**Issue by rajasekhar2** [AzureAD/microsoft-authentication-library-for-js#1154]
I am using authority as "Consumers" so as to allow only MSA logins. When I give @microsoft.com email , I receive correct error. If I try my website again I receive below error. This remains till I close the browser. Loginredirect keeps on throwing this error till I close my session. Is this not handled properly or am I missing anything here?

errorCode: "login_progress_error"
name: "ClientAuthError"

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 1.1.3

</code></pre>

**Comment by jasonnutter** [comment]
@rajasekhar2 Please try `msal@1.2.0` and let us know if this is still an issue.

**Comment by rajasekhar2** [comment]
thanks @jasonnutter this worked with 1.2.0. However I am facing below issue after including msal. First build runs fine, subsequent builds fail

<--- Last few GCs --->
 
[17208:0000020B4EB70F20]  1184996 ms: Scavenge 3365.3 (4162.0) -> 3364.3 (4162.5) MB, 10.8 / 0.0 ms  (average mu = 0.164, current mu = 0.189) allocation failure
[17208:0000020B4EB70F20]  1185019 ms: Scavenge 3366.8 (4163.0) -> 3366.0 (4163.5) MB, 10.5 / 0.0 ms  (average mu = 0.164, current mu = 0.189) allocation failure
[17208:0000020B4EB70F20]  1185036 ms: Scavenge 3367.7 (4163.5) -> 3366.9 (4164.0) MB, 9.7 / 0.0 ms  (average mu = 0.164, current mu = 0.189) allocation failure
 
 
<--- JS stacktrace --->
 
==== JS stack trace =========================================
 
    0: ExitFrame [pc: 0000016F06950481]
Security context: 0x023dcff9d9d1 <JSObject>
    1: set [0000023DCFF90E29](this=0x022843ae3df1 <Map map = 000000A62F483EC1>,0x00fc22082d79 <DependenciesBlock map = 000001714723CBD1>,4096)
    2: processDependenciesBlocksForChunkGroups [000003C1DC7AD841] [D:\TCS\Projects\AzureCXP\Git\AzureCXP-Eng-UX\src\node_modules\webpack\lib\Compilation.js:~1514] [pc=0000016F07884402](this=0x024f2d6ba8f9 <Tapable m...
 
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
1: 00007FF7B12BD7AA v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4618
2: 00007FF7B126B736 uv_loop_fork+86646
3: 00007FF7B126C1FD uv_loop_fork+89405
4: 00007FF7B169454E v8::internal::FatalProcessOutOfMemory+798
5: 00007FF7B1694487 v8::internal::FatalProcessOutOfMemory+599
6: 00007FF7B1747F64 v8::internal::Heap::RootIsImmortalImmovable+14068
7: 00007FF7B173DD72 v8::internal::Heap::CollectGarbage+7234
8: 00007FF7B173C588 v8::internal::Heap::CollectGarbage+1112
9: 00007FF7B1745EB7 v8::internal::Heap::RootIsImmortalImmovable+5703
10: 00007FF7B1745F36 v8::internal::Heap::RootIsImmortalImmovable+5830
11: 00007FF7B187DC6D v8::internal::Factory::AllocateRawArray+61
12: 00007FF7B187E602 v8::internal::Factory::NewFixedArrayWithFiller+66
13: 00007FF7B18C52DE v8::internal::wasm::AsmType::Void+86510
14: 00007FF7B18C599D v8::internal::wasm::AsmType::Void+88237
15: 00007FF7B194F6B4 v8::internal::StoreBuffer::StoreBufferOverflow+123924
16: 0000016F06950481
error Command failed with exit code 134.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 134.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by jasonnutter** [comment]
@rajasekhar2 I see you opened a separate issue for the webpack question, closing this.
