### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by rajasekhar2** [AzureAD/microsoft-authentication-library-for-js#1157]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 1.2.0

</code></pre>

## Current behavior

After including msal library, yarn started failing. If I don't include msal in my dependencies, everything works fine. First build runs successfully, and then it starts failing. If we stop build and run again, first build runs successfully, subsequent builds which trigger on save of any file change fails.

I tried beta, 1.1.3 and 1.2.0 versions

My code is having Adal library also.

## Minimal reproduction of the problem with instructions

 If I don't include msal in my dependencies, everything works fine. First build runs successfully, and then it starts failing. If we stop build and run again, first build runs successfully, subsequent builds which trigger on save of any file change fails.

**Comment by rajasekhar2** [comment]
I am still struggling with this issue. It will be great if someone can look into this

**Comment by jasonnutter** [comment]
I'm working with @rajasekhar2 via internal channels to debug this, which happens after adding `msal` to his team's application and then running Webpack.

**Comment by jasonnutter** [comment]
Issue resolved by customer, closing.
