### ISSUE TITLE
404 link to documentation

### ISSUE THREAD

**Issue by andersthorsen** [AzureAD/microsoft-authentication-library-for-js#1168]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version XX
- [x] Firefox version XX
- [x] IE version XX
- [x] Edge version XX
- [x] Safari version XX

## Library version

<pre><code>
Library version: X.Y.Z

</code></pre>

## Current behavior

at this page:
https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-v2-libraries

and this page:
https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki

there is a link to https://htmlpreview.github.io/?https://raw.githubusercontent.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/docs/classes/_useragentapplication_.useragentapplication.html
which simply ends up in a 404

Frustration with the highly fragmented nature of msal and Azure AD authentication documentation increase.

## Expected behavior

Link to a real, working and complete documentation

Lower frustration.

## Minimal reproduction of the problem with instructions

Click link

**Comment by jasonnutter** [comment]
@andersthorsen Sorry about that, here is the updated link: https://azuread.github.io/microsoft-authentication-library-for-js/docs/msal/

We updated this in the README in the repo, but missed a few other spots, we'll get that fixed, sorry about that!

**Comment by jasonnutter** [comment]
Wiki link has been updated, docs.microsoft.com link has been committed and will go out with the next deployment of the docs site. Closing.
