### ISSUE TITLE
Mitigate IE/Edge truncation of the #hash for response_type=id_token_token

### ISSUE THREAD

**Issue by sameerag** [AzureAD/microsoft-authentication-library-for-js#1172]
Add a mitigation in the library for this use case. @sameerag  to add a clear desc.

**Comment by fayejaye** [comment]
Hi, I'm getting this same error in MS Edge using react-aad-msal package (v2.3.4).
**Unexpected error in authentication.: Hash does not contain state.**
Was #1172 ever merged in? or a workaround solution available?

**Comment by sameerag** [comment]
The latest version `msal@1.4.1` should fix all the issues tagged above. Closing this.
