### ISSUE TITLE
Reduce initial bundle size of msal.js

### ISSUE THREAD

**Issue by christiango** [AzureAD/microsoft-authentication-library-for-js#1173]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version XX
- [x] Firefox version XX
- [x] IE version XX
- [x] Edge version XX
- [x] Safari version XX

## Library version

<pre><code>
Library version: 1.2.0

</code></pre>

## Current behavior
MSAL is on our critical bundle for our application. We currently use it to authenticate the user and kick off some token requests early on in the boot sequence. Right now MSAL is 80KB (uncompressed)/20KB (gziped), which is about 15% of our initial bundle. 

The library is currently not eligible for tree shaking in webpack due to the lack of a [side effects property on it's package.json](https://webpack.js.org/guides/tree-shaking/). Also, there is a large module UserAgentApplication.ts with a lot of imports. Since tree shaking happens at the module level in webpack, this large module may be pulling in bits to the bundle that go unused by applications. Breaking this module up into smaller modules that can be imported by applications may reduce bundle sizes, assuming that all the code here is not necessary for token fetching and initial auth. 

## Expected behavior
Make the cost of MSAL pay per play (enable tree shaking of bits some apps don't use, if that is common) and reduce the initial bundle size to give app teams the best performance.

## Minimal reproduction of the problem with instructions
Create a webpack config where MSAL token fetch is in the main bundle.

**Comment by jasonnutter** [comment]
@christiango Thanks for the feedback! I definitely agree there's a lot we could here. Some thoughts:

- Tree shaking: Agree about `sideEffects: false`, we already have an issue open to add that. #1153 
- `UserAgentApplication`: We're currently working on the next major version of the library (to support Auth Code flow), which has a lot of refactoring of this module, namely breaking it up into smaller pieces. So you should improvements in that regard when that is available early next year.
- Source maps: Another thing (that may not impact you) is the inline source maps for the CDN builds, which I would like to change to be a separate file, which will help CDN users. 

Let us know if you have any further questions or concerns, thanks!

**Comment by christiango** [comment]
Thanks for the quick reply Jason! Yeah, we're using the npm package in our bundle directly, just to confirm. 

With regards to sideEffects: false, I did an initial experiment with that in a branch and didn't see a big drop in our bundle size, likely due to UserAgentApplication creating a large dependency tree that can't really be shaken out. 

Looking forward to the next major release!

**Comment by jasonnutter** [comment]
@christiango No problem, and thanks for sharing your findings!

**Comment by jasonnutter** [comment]
Closing as no further action at this time (that isn't tracked by other issues).
