### ISSUE TITLE
400: bad request

### ISSUE THREAD

**Issue by ahqardah** [AzureAD/microsoft-authentication-library-for-js#1174]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [X] Chrome version 78
- [X] Firefox version latest
- [X] IE version latest
- [X] Edge version latest
- [X] Safari version 13.04

## Library version

<pre><code>
Library version: 1.2.0

</code></pre>

## Current behavior

After the user logs in, and the token is expired, the refresh token call returns this
"Failed to load resource: the server responded with a status of 400 (Bad Request)" on all browsers, it happened in 1.2.0-beta and again in 1.2.0

## Expected behavior
It's supposed to refresh the token gracefully

## Minimal reproduction of the problem with instructions
We have the following config:
<pre><code>
const msalConfig: Msal.Configuration = {
            auth: {
                clientId: AAD_APP_ID,
                authority: 'https://login.microsoftonline.com/common',
                validateAuthority: false,
                redirectUri: window.location.origin + RouteUtils.routeForSignIn(),
                navigateToLoginRequestUrl: false,
            },
            cache: {
                cacheLocation: 'localStorage',
                storeAuthStateInCookie: true,
            },
        };
        this._msal = new Msal.UserAgentApplication(msalConfig);
</code></pre>

**Comment by sameerag** [comment]
@ahqardah How are you refreshing the token? Refresh token does not happen by default, the user is expected to call `acquireTokenSilent` and as long as the AAD session is active, the `token` will be renewed. 

From your error, it seems to me that the resource is called with an expired token in which case it is expected. The pattern is to:

- acquire a token
- renew it silently before expiry (more notes on token lifetimes [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes#single-sign-on-session-tokens) and renewals [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/FAQs#q3-how-to-renew-tokens-with-msaljs)

**Comment by ahqardah** [comment]
@sameerag obviously, by calling `acquireTokenSilent`, which does the refresh silently if the token is expired. Now a couple of questions:
- if the user is idle for a while, the token expires, will that cause the 400? if yes, this is a bug and needs to be addressed. An expired token should not throw a 400 (bad input), 400 should only be used when the input is malformed or missing something. 

Please suggest a fix/work around when the user is idle and the token expires, a 400 response should not be accepted as a solution, this is a bad state management.

**Comment by jasonnutter** [comment]
@ahqardah Which API are you calling that is returning a 400? A Microsoft Graph API, or your own custom web API?

**Comment by ahqardah** [comment]
@jasonnutter we get this response from MSAL after an acquireTokenRedirect

**Comment by jasonnutter** [comment]
Worked with @ahqardah internally and determined the 400 is likely getting generated by the application server because the cookies that MSAL generates are too long (> 4096 characters). Workaround is to only enable `storeAuthStateInCookie` for IE/Edge, and to have users clear their cookies if they encounter this error. We'll look to see what protections we can add into the library to prevent this from happening (i.e. prevent MSAL from generating a cookie header length than exceeds 4096 characters).

**Comment by jasonnutter** [comment]
Closing, tracking in #1188.
