### ISSUE TITLE
Angular 8 and Asp.Net Core 3.1

### ISSUE THREAD

**Issue by jsmith39** [AzureAD/microsoft-authentication-library-for-js#1175]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[X] Other... Please describe:
</code></pre>

## Browser:
- [X] Chrome version XX
- [X] Firefox version XX
- [X] IE version XX
- [X] Edge version XX
- [X] Safari version XX

## Library version
<pre><code>
Library version: @azure/msal-angular": "^0.1.4
"@angular/core": "8.2.14"
.Net Core 3.1
</code></pre>

## Current behavior
I am able to login with Azure AD correctly from the client side.  However, when I make an API call back to the server (the angular app and Web API site are the same site) it always returns a unauthorized response.  I'm using the MsalGuard and MsalInterceptor.  The guard and interceptor seem to be doing what they should be doing.  The interceptor is passing the token back to the server.
My configurations may be the problem.  I've tried a ton of variations of the configuration.  Here is what it is now.  Angular:
![image](https://user-images.githubusercontent.com/32643873/71267186-01867e00-2318-11ea-9e4a-16a3a0e4c273.png)
.Net Core 3.1
![image](https://user-images.githubusercontent.com/32643873/71267280-372b6700-2318-11ea-81a3-153fe4d0a107.png)
![image](https://user-images.githubusercontent.com/32643873/71267362-5b874380-2318-11ea-8fd1-9e66166ed6c1.png)
I receive this error on the server:
IDX10205: Issuer validation failed. Issuer: 'https://login.microsoftonline.com/XXXX/v2.0
I've tried setting:  config.TokenValidationParameters.ValidateIssuer = false; and that didn't change anything.

Question of the day:  what thing am I doing wrong?  I know the error is on the server, but it seems like the problem is with my configuration of the client.  I don't know.

## Expected behavior
I expect to not receive unauthorized responses from the server (again it is the same Url as the angular app).

What parts of the settings on the server/client should be the same?  I know the clientID and tenetID are used in multiple locations.  I'm not convinced I'm using them in the correct places.  

Any help would be appreciated.

**Comment by jasonnutter** [comment]
@jsmith39 Given that you have scopes for two different resources (Graph and your web API), you will get a separate access token for each resource (as access tokens are issued per-resource). Can you confirm that the right access token is being used in the request to your web api? Might help to see your `protectedResourceMap`.

**Comment by jsmith39** [comment]
Sorry for the delayed response.  Unfortunately, the client has put this project on hold for the next month at least.  I'll close it for now and open a new one if necessary in the future.
