### ISSUE TITLE
[MSAL ANGULAR] Use config function instead of a config object

### ISSUE THREAD

**Issue by guevaraf** [AzureAD/microsoft-authentication-library-for-js#1177]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version XX
- [x] Firefox version XX
- [x] IE version XX
- [x] Edge version XX
- [x] Safari version XX

## Library version

<pre><code>
Library version: 0.1.4

</code></pre>

## Current behavior

[MSAL ANGULAR] For configuring MSAL module you receive an object that is passed over from Msal module to Msal service with static values for configuring the client.

## Expected behavior

Pass a valur or an object in order to obtain dynamically the configuration value at the time the service is injected and used for the first time and not when the module is imported.

This will allow to have scenarios where the configuration is pulled from the server or other async sources or at a latter time than import.

## Sample scenario
config.service.ts
```javascript
import { Injectable } from '@angular/core';
import { HttpClient, HttpBackend } from '@angular/common/http';

// Configuration object to be used when requesting result
let appConfig: any = null;

export function configurator() {
  return appConfig;
}

@Injectable()
export class ConfigService {
  http: HttpClient;
  constructor(httpBackend: HttpBackend) {
    // we create our own HttpClient to avoid carrying over any interceptors added such as authentication
    this.http = new HttpClient(httpBackend);
  }

  loadAppConfig(): Promise<any> {
    const promise = this.http.get('/api/clientsettings')
      .toPromise()
      .then(data => {
        appConfig = data;
        return appConfig;
      });

    return promise;
  }

  getConfig(): RemoteAppSettings {
    return appConfig;
  }
}
```
app.module.ts
```javascript
import { BrowserModule } from '@angular/platform-browser';
import { NgModule, APP_INITIALIZER } from '@angular/core';
import { HttpClientModule, HttpClient, HttpBackend } from '@angular/common/http';
import { MsalModule, MsalConfig } from '@azure/msal-angular';
import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { ConfigService, configurator } from './services/config.service';

const appInitializerFn = (configService: ConfigService) => {
   return configService.loadAppConfig();
};

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    HttpClientModule,
    AppRoutingModule,
    MsalModule.forRoot(configurator),
  ],
  entryComponents: [  ],
  providers: [
    ConfigService,
    {
      provide: APP_INITIALIZER,
      useFactory: appInitializerFn,
      multi: true,
      deps: [ConfigService]
    }
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**Comment by jasonnutter** [comment]
@guevaraf Thanks for the feedback. This has been requested a few times (#963, #1103 , #943), so I'll close this as a duplicate. I'll definitely see that we make this possible in the next version of MSAL Angular.

**Comment by jrdutton** [comment]
Hi @jasonnutter, I've tried many of the solutions suggested. They all work with Angular 8, but none work with Angular 9 + Ivy + AOT = true.

In all cases, I see the following error ... 

bootstrap-fail NullInjectorError: R3InjectorError(AppModule)[MsalService -> InjectionToken MSAL_CONFIG -> InjectionToken MSAL_CONFIG -> InjectionToken MSAL_CONFIG]: 
  NullInjectorError: No provider for InjectionToken MSAL_CONFIG!

I'm wondering if this is something that you have seen and whether you have any suggestions?

Thanks

**Comment by jasonnutter** [comment]
@jrdutton Please see my comments here about Angular 9 + Ivy, specifically links to the new sample: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/855#issuecomment-593674986

**Comment by jrdutton** [comment]
Thanks very much, @jasonnutter, I saw your branch and was very excited. I'd already tried almost identical code to yours within main.ts and app.module.ts, but guess there is something else that I am missing.

**Comment by jasonnutter** [comment]
@jrdutton Are you using `@azure/msal-angular@1.0.0-beta.3`?

**Comment by jasondicker** [comment]
I had the same problem but managed to resolve it with the @azure/msal-angular@1.0.0-beta.3 build. The key was replacing 'adalConfig' with MSAL_CONFIG_ANGULAR in the providers section:

        {
          provide: MSAL_CONFIG,
          useFactory: msAdalAngular6ConfigFactory
        },
        {
          provide: MSAL_CONFIG_ANGULAR,
          useFactory: msAdalAngular6ConfigFactory
        },

**Comment by jrdutton** [comment]
Hi, we did get this working. We used:

"@azure/msal-angular": "^1.0.0-beta.3"
"msal": "^1.2.2-beta.0"

and then this within our main.ts file...

export function getBaseUrl() {
  return document.getElementsByTagName("base")[0].href;
}

fetch(getBaseUrl() + "/api/configuration/authorisation")
  .then(response => response.json())
  .then(json => {
    const configuration = {
      auth: {
        authority: json.authority,
        clientId: json.clientID,
        postLogoutRedirectUri: json.postLogoutRedirectUri,
        redirectUri: json.redirectUri
      },
      cache: {
        cacheLocation: json.cacheLocation
      }
    } as Configuration;
    platformBrowserDynamic([
      { provide: MSAL_CONFIG, useValue: configuration },
      { provide: MSAL_CONFIG_ANGULAR, useValue: {} }
    ])
      .bootstrapModule(AppModule)
      .catch(err => console.error(err));
  });
