### ISSUE TITLE
Prevent MSAL from generating cookies that exceed a set limit

### ISSUE THREAD

**Issue by jasonnutter** [AzureAD/microsoft-authentication-library-for-js#1188]
When `storeAuthStateInCookie` is enabled, MSAL will store information in cookies on the application domain. These cookies are meant only for MSAL, but they could get sent with an AJAX request sent to the server, and if these cookies are too long for the server, then the server will likely return a 400 error (as in #1174). When creating cookies, MSAL should first inspect the current set of cookies, and if the new cookie length will exceed some limit (e.g. 4096), then perform logic to ensure the new cookie will not exceed that limit.

This limit should be configurable by an application, including the option to disable the limit completely.

AC:
1. Cookies created by MSAL do not exceed a known limit set in the library. Any truncation that occurs should only remove values set by MSAL.
2. Default limit is 4096.
3. Limit can be disabled.
4. If possible, find root cause of cookies not getting deleted (as in #1174).

**Comment by rick077** [comment]
Timing on this to be fixed?   It is preventing release of MSAL code for my application to correct Chrome Same Site issue.    None of the work arounds suggested have been successful.

**Comment by jasonnutter** [comment]
@rick077 `msal@1.2.2` included a fix for the root cause of this bug, which was the library not properly deleting temporary cache entries. This should address the problem for most scenarios (if you finding that this is not the case, please open a new issue). 

This enhancement is a further safe-guard, however, is lower priority since the we root cased the original issue.

**Comment by rick077** [comment]
@jasonnutter I was using the msal@1.2.2-beata0 code recieved 431 errors on gets & posts only when running in Azure, not on my desktop.  Just upgraded to msal@1.3.0 and am still getting the 431 with duplicate MSAL auth cookies in the headers

**Comment by vinusorout** [comment]
We are also facing this same issue.
lib versions are:
"@azure/msal-angular": "1.0.0-beta.5",
"msal": "1.3.0",

**Comment by vinusorout** [comment]
Hello @jasonnutter do we have a fix for this!

**Comment by jasonnutter** [comment]
> @jasonnutter. Thank you for the prompt reply. I was using the msal@1.2.2-beata0 code recieved 431 errors on gets & posts only when running in Azure, not on my desktop. Just upgraded to msal@1.3.0 and am still getting the 431 with duplicate MSAL auth cookies in the headers

If you logout from MSAL and then log back in, does the error still happen?

**Comment by rick077** [comment]
@jasonnutter If you logout from MSAL and then log back in, does the error still happen?

The 431 error still happen after logging out then back into MSAL.   Never occur when running on localhost.

**Comment by jasonnutter** [comment]
@rick077 When this happens, how many MSAL cookies are there?

**Comment by rick077** [comment]
@jasonnutter   4 cookies. Below details removed.   My MSAL code is in angular app.module.ts and the errors come immediately on launch in my main.component.ts as I pull database info for the app. 

	localStorage: Storage
	length: 5
	msal.********-****-****-****-************.client.info: "**********************"
	msal.********-****-****-****-************.idtoken: "xxxxxxxxxxxxxx.yyyyyyyyyyyyyyyyyyyyyyyyyy"
	msal.client.info: "**********************"
	msal.idtoken: "xxxxxxxxxxxxxxxxxxxx.yyyyyyyyyyyyyyyyyyyyyyyyyy"
		{"authority":"https://login.microsoftonline.com/39487c85-7397-40a2-80d4-c1694acb64ae/","clientId":"********-****-****-**-************","scopes":"********-****-****-****-************",					"homeAccountIdentifier":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}: "{"accessToken":"er":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}"

**Comment by jasonnutter** [comment]
@rick077 Those look like localStorage values (which are not passed to your server), I'm interested in the cookies specifically.

**Comment by vinusorout** [comment]
Hello @jasonnutter  I also tried this logout as you mentioned here, but this doesn't solve the error.
And yes it store multiple cookie related to msal.

Please check https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1615#issuecomment-626854629
for all the cookie values it stored in browser.

**Comment by rick077** [comment]
@jasonnutter @vinusorout   Where do I see the cookies in the Javascript 431 error?  I am looking at these errors in the Chrome Console.

**Comment by vinusorout** [comment]
@jasonnutter our users are facing this issue in IE only and for our configurations, please see issue description:
https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1615

**Comment by rick077** [comment]
@jasonnutter .....  Interesting does not appear to error in IE though I need to verify as I am not familiar with the console.  Tried IE and was able to get the server to dump the header into the Azure console.    I will try to get the same info running from Chrome.

In the header on the server  I see two cookie: 'ARRAffinity=  and  AppServiceAuthSession=.  

I also see very large strings for:
 authorization: 'Bearer ...
'x-ms-client-principal': 
'x-ms-token-aad-id-token':

**Comment by rick077** [comment]
@jasonnutter  with Chrome browser and using the Azure "Log Stream" in verbose mode I can see the two MSAL cookies and that I am authenticated OK.  Using Chrome All the subsequent calls to the server return 431 errors and the server never logs any of the log msgs in the code.  Appears to be a Chrome browser specific error I am seeing.

**Comment by rick077** [comment]
@jasonnutter   Immediately after the 431 errors I see in the verbose log a html page for "HTTP Error 401.71 - Unauthorized"

**Comment by djleonskennedy** [comment]
Any updates ?

**Comment by sebol** [comment]
Hi!
I have the same problem, I cannot go to production with our application due to this bug.

Regards

**Comment by jasonnutter** [comment]
I will investigate what more can be done in the library to mitigate this issue. Until then, I suggest these mitigations:

1. Increase the max header size limit for your server. 
2. Only enable `storeAuthStateInCookie` for IE/old Edge (it should not be needed for other browsers).

**Comment by AbhaysinghBhosale** [comment]
I can see long cookie with each API call even after updating to version `"msal": "1.3.1"`. Headers too long issue occurs to random users.

**Comment by Dima11235813** [comment]
I'm on version 1.1.3, **what version of MSAL should we be using?** 

**Which one is stable and supported in production?**

I was under the impression that all 1.x versions are backward compatible, is that correct?

Also isn't checking for IE/old edge a brittle solution since user agent strings are subject to change, or am I mistaken about that, not sure if they're static strings?

Is this an [acceptable way to check for browser version](https://social.msdn.microsoft.com/Forums/en-US/edde0150-9478-4ca6-ba0f-9e084b5a4719/how-to-detect-microsoft-edge-chromium-chrome-ie-browser-using-javascript)?

**What is the most stable Ms/Azure recommended way of checking for IE/edge?**

Also, I'm working on a large enterprise solution and they use 99% IE11 and this issue is continually happening in production and causes user's experience to grind to a halt for the rest of the day (due to 400 errors from our NGINX server, serving up our React App). 

Oddly it only happens with some users, and it's not clear why it affects some and not others.

Perhaps it's something about how the enterprise uses SSO. They changed from on-prem to Azure AD SSO recently.

We're using GCP App Engine and that uses NGINX which has a max header size of 8kb by default. 

We're opening a case to increase that max size but I'm not sure if that'll fix it for sure, since the Microsoft Identity Server could just keep setting cookies and exceed the new max that we set.

Is the identity server checking for cookies sent before responding with more set cookie headers? 

Is there a planned date of pushing a fix for this?

I know that's a lot of questions but I'm really looking forward to getting this resolved as it's been an open Ms support issue (with this Enterprise) for a number of months now with no solution.

**Comment by NagaCSC** [comment]
one of our customer also has issue of Htpp 400 with MSAL 1.3.3 Please advice on the fix ETA. Thanks

**Comment by jakehockey10** [comment]
I'm having this issue as well, but I don't see any cookies or anything in local storage or session storage or cache.  My site data is 0.  I'm not sure how to resolve this?

**Comment by horvay** [comment]
Thanks a ton for fixing this! We could really use this fix soon, so the sooner it gets released on the npm beta/preview, the better for us!

**Comment by NagaCSC** [comment]
Thank you Jason for the help

**Comment by jasonnutter** [comment]
Apologies for the delay, `msal@1.3.3` is available on npm, and should create fewer cookies, those cookies should be shorter in length, and should properly delete cookies when necessary.

**Comment by jasonnutter** [comment]
If you have further issues or questions around cookies, please open a new issue, thanks!
