### ISSUE TITLE
Support OAuth 2.0 client credentials flow

### ISSUE THREAD

**Issue by scott-lin** [AzureAD/microsoft-authentication-library-for-js#1189]
## I'm submitting a...
<pre><code>
[ ] Regression
[ ] Bug report
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX
- [x] Not applicable

## Library version
<pre><code>
Library version: 1.2.0
</code></pre>

## Current behavior
Acquiring token for a [confidential client application](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-authentication-flows#client-credentials) is not possible.

## Expected behavior
Similar to how [MSAL.NET supports client credentials](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Client-credential-flows) flow, I expect MSAL.JS to support it.

Is there a workaround for client credentials flow? My team is developing components in Node & TypeScript and I don't consider changing to .NET to be a reasonable suggestion.

**Comment by jasonnutter** [comment]
@scott-lin MSAL.js for Node is on our roadmap for this year, but has not been scheduled yet. We'll post an update when we have more information to share!

**Comment by jasonnutter** [comment]
Closing as no further actionable items at this time.
