### ISSUE TITLE
How to get scopes defined for a user after the user is logged in?

### ISSUE THREAD

**Issue by alvipeo** [AzureAD/microsoft-authentication-library-for-js#1192]
I've been trying to get the answer myself looking at the source but failed.

Basically, the question is here - [https://stackoverflow.com/q/59651353/2896495](https://stackoverflow.com/q/59651353/2896495).

Sorry for posting it here but I'm stuck with all this Azure AD B2C authentication.

**Comment by jasonnutter** [comment]
@alvipeo Can you clarify the problem you are trying to solve with this mapping? Scopes are linked to specific resources (e.g. reading information about the user from Microsoft Graph requires the `user.read` scope), so when your application makes a request to a resource, you should request a token with the scopes needed for that resource, regardless of the user. 

If the question you want to answer is "has this user consented to this scope?", you can find out by requesting a token with that scope, and if the user has not consent, the library will return an `interaction_required` error, at which point you can invoke one of the interactive methods to prompt the user to provide that consent.

**Comment by alvipeo** [comment]
My understanding is if I have extensive API and I need to "slice" permissions for parts of that API, I use scopes. So if Part1 of my api expects "Part1.scope" permissions from a user then the user must have this "Part1.scope" assigned (in Azure AD). Just like with Graph API. Is this correct?

If it is, then when a user is authenticated and the web app gets AuthResponse, the response does have the scopes for that user. So I can use those scopes as defined permissions (and change UI accordingly). Now, when web app user needs to issue a request to the backend (web API) that expects to have "Part1.scope" assigned to this user, web app should request the token with the required scope "Part1.scope". Then the backend should validate this token, correct?

Keeping the list of scopes in a web app is just a way of evaluating his role (by looking at the set of scopes returned with AuthResponse).

**Comment by jasonnutter** [comment]
@alvipeo It sounds like you should be using roles (which are per-user), instead of scopes (which are per-resource). You can find out which roles are assigned to a user with the [checkMemberObjects](https://docs.microsoft.com/en-us/graph/api/user-checkmemberobjects?view=graph-rest-1.0&tabs=http) API in Microsoft Graph.

More info about roles can be found here: https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/directory-assign-admin-roles

**Comment by alvipeo** [comment]
Oh, I got it. So when I define scope for my web API app, and this scope is defined for the client web app this means that the client app has permission to the web API app according to defined scope. Is that right?

**Comment by alvipeo** [comment]
Actually, I'm confused again - [https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-access-tokens#scopes](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-access-tokens#scopes).

> Scopes are used by the web API to implement scope-based access control. For example, users of the web API could have both read and write access, or users of the web API might have only read access. To acquire multiple permissions in the same request, you can add multiple entries in the single scope parameter of the request, separated by spaces.

This is about USERS - users have or have not access. Damn, this is nuts.

**Comment by alvipeo** [comment]
FFS, I found the answer here - [https://stackoverflow.com/a/49848259/2896495](https://stackoverflow.com/a/49848259/2896495)!

Jesus, why then not call them **Application Scopes**?? Not just scopes.
