### ISSUE TITLE
Add Error Codes and a Documentation page for all MSAL JS errors

### ISSUE THREAD

**Issue by sameerag** [AzureAD/microsoft-authentication-library-for-js#1195]
The idea is to add numeric codes to errors generated by the MSAL JS library and redirect the user to a webpage that contains detailed desc of the errors. Searching for "1234"  in the webpage should result in :     

    code: 1234
    category: Configuration Error
    desc: "Configuration has not been set. Please call the UserAgentApplication constructor with a valid Configuration object."

We can leverage this by:
- adding a link to this page in all our error messaging
- in alignment with Server errors lookup: https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-aadsts-error-codes

Thanks @jasonnutter  for the suggestion. We can flesh out this in detail soon.

**Comment by pkanher617** [comment]
#1272 linked issue
