### ISSUE TITLE
Getting error in broadcaster after calling acquireTokenSilent() method

### ISSUE THREAD

**Issue by Ankita22** [AzureAD/microsoft-authentication-library-for-js#1196]
Hi,

I am using MSAL-ANGULAR for AD B2C Implementation with Angular 7.I am able to login but getting error to acquire Access token.Trying to acquire the access token silently as suggested in Docs after getting login success response on broadcaster. PFA for error details

## Code sample

```
  this.broadcastService.subscribe('msal:loginSuccess', (payload) => {
    console.log('[Info] - Login success');.
    // Getting login sucess here and giving call for token
    this.authService.acquireTokenSilent(b2cScopes);
  });

  this.broadcastService.subscribe('msal:acquireTokenSuccess', (payload) => {
    // Should get access token here
    console.log('[Info]- Acquire Token success : ', JSON.stringify(payload));
  });

  this.broadcastService.subscribe('msal:acquireTokenFailure', (payload) => {
    // Getting error details here
    console.error('[Error] - Access token failure ::', JSON.stringify(payload));
  });
```

## Browser:
- [ X] Chrome version XX
- [ X] Firefox version XX

## Library version
 @azure/msal-angular: '^0.1.4'
Angular CLI version : 7.0.4

## Current behavior
After Login success broadcaster response,getting the **ID token** here and calling  acquireTokenSilent() to get access token, but it is giving error for Acquire token failure : 

Error] - Access token failure :: {"_error":"AADB2C90205: This application does not have sufficient permissions against this web resource to perform the operation.\r\nCorrelation ID: bd95d6e4-d62a-4f57-a51f-bfb5297ef21a\r\nTimestamp: 2020-01-10 05:24:05Z\r\n","_errorDesc":"invalid_request","_scopes":""}

## Expected behavior

After Login success broadcaster response, it should give success response for access token [Info]- " Acquire Token success : "  with access token attached to it.

I am passing all the required scopes for the same.Do i need to add anything else ? It would be better if i get some help.

![msal_issue_1](https://user-images.githubusercontent.com/20045943/72129969-177ae200-339e-11ea-8f2d-62e1f22cc515.png)
![msal_issue_2](https://user-images.githubusercontent.com/20045943/72129970-177ae200-339e-11ea-91ca-720660683288.png)

**Comment by Ankita22** [comment]
##Update

I tried to change the authority URL but facing following issue :

**Comment by jasonnutter** [comment]
@Ankita22 I believe this error indicates either your request was invalid or the app is not configured properly. Can you please provide some sample code that demonstrates your usage (e.g. what scopes you are using)? Thanks!

**Comment by Ankita22** [comment]
@jasonnutter Thanks for your reply. I am using following scopes  : 'user_impersonation','offline_access','openid','profile'


Following is the piece of code i am using to try to connect :

## In app.module.ts

  ```
MsalModule.forRoot({
        clientID: environment.b2CDetails.clientID,
        authority: environment.b2CDetails.authority,
        validateAuthority: false,
        redirectUri: environment.b2CDetails.redirectUri,
        cacheLocation : 'localStorage',
        postLogoutRedirectUri: environment.b2CDetails.redirectUri,
        popUp: false,
        consentScopes: environment.b2CDetails.b2cScopes,
        unprotectedResources: ['https://www.microsoft.com/en-us/'],
        logger: loggerCallback,
        correlationId: '1234',
        level: LogLevel.Info,
        piiLoggingEnabled: false
     }
```

## B2C details

```
 b2CDetails: {
    'tenant': '<tenantName>',
    'clientID': '<clientID>',
    'signUpSignInPolicy': '<policyName>',
    'b2cScopes': ['https://<tenantName>.onmicrosoft.com/<applicationName>/user_impersonation','offline_access','openid','profile'],
    'nonce': '123456789',
    'redirectUri': 'http://localhost:4200/login',
    'authority': 'https://<tenantName>.b2clogin.com/<tenantName>.onmicrosoft.com/<policyName>',
}
```

**Comment by Ankita22** [comment]
Thanks a lot for the help @jasonnutter . I updated my Authority URL and couple of setting and i am able to login properly but not able to get access token.

I am getting access token at localhost but once app gets hosted , facing issue to acquire the same. Can you please help with it ?

Please refer the code sample associated with above comments,you can see in 

```
 this.broadcastService.subscribe('msal:acquireTokenFailure', (payload) => {
    // Getting error details here
    console.error('[Error] - Access token failure ::', JSON.stringify(payload));
  });
```
this part of the code i am getting error.

Please refer attached image for error details which i received on **" msal:acquireTokenFailure"** broadcaster provided by MSAL-ANGULAR


![access-token-error](https://user-images.githubusercontent.com/20045943/72257443-b2d7b580-3631-11ea-89cd-41f546aa52c8.png)
![Access-token-issue](https://user-images.githubusercontent.com/20045943/72257444-b2d7b580-3631-11ea-9ab9-73eacc13d03e.png)

**Comment by jasonnutter** [comment]
@Ankita22 Since it works locally but not when deployed, can you verify that you have correctly configured your redirect uris in both your app in the Azure Portal?

**Comment by Ankita22** [comment]
@jasonnutter Yes, I checked the Redirect URIs on  Azure portal. It looks fine. It has both the URLs - Localhost and webapp's  app service url.

**Comment by jasonnutter** [comment]
@Ankita22 And you are using the appropriate redirect uri for the deployed environment? I notice you have `localhost` hardcoded above for the redirect uri, make sure that is updated to use the app service url when not running locally.

If you can share an example network request url that is resulting in a timeout, that would also be helpful, thanks!

**Comment by Ankita22** [comment]
@jasonnutter Yes, i have configured the correct redirect URIs in local and on hosted app as well :)

Surprisingly I just tried to login again and got to know that i am getting access token on hosted app service as well. Thanks for the help :) 
Appreciated!

**Comment by jasonnutter** [comment]
@Ankita22 Glad its working, sounds good!
