### ISSUE TITLE
setup authority for AAD B2C tenant

### ISSUE THREAD

**Issue by ericmok66** [AzureAD/microsoft-authentication-library-for-js#1203]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-angular@0.1.4`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
1. I registered AAD B2C application already
2. I created user flow and well tested already
3. I can get the authorize_token and id_token using PostMan

When I try to follow the \MSALAngularDemoApp, I encountered error [endpoints_resolution_error: Endpoints cannot be resolved]. 

I tried different Uri 
- https://\<mytenant\>.b2clogin.com/\<mytenant\>.onmicrosoft.com/\<policyname\>
- https://login.microsoftonline.com/<tenantid\>/tfp/\<policyname\>

All of above return the same error.

The application work if I use this, `https://login.microsoftonline.com/<mytenant>.onmicrosoft.com/`, but I can't specific the policy I want to execute.

How should I config the MsalModule.forRoot()?

**Comment by ericmok66** [comment]
it work for `https://login.microsoftonline.com/<mytenant>.onmicrosoft.com/`
But I can't specific the policy I want to execute.

**Comment by jasonnutter** [comment]
@ericmok66  `https://<tenant-name>.b2clogin.com/<tenant-name>.onmicrosoft.com/<policy-name>` should work. Can you set `validateAuthority` to `false`?

**Comment by jasonnutter** [comment]
@ericmok66 Closing, let us know if you have further questions.
