### ISSUE TITLE
Scope Calls not working

### ISSUE THREAD

**Issue by johanjudai** [AzureAD/microsoft-authentication-library-for-js#1204]
Hi,
I want to develop an app for doing calls in Teams. When I want to get the login token, the popup says the Calls scopes don't exist. Is it supported yet ?
I tried typing "call", "calls" or "Calls.Initiate.All"

**Comment by jasonnutter** [comment]
@johanjudai You can find more information about the Calls-related scopes here: https://docs.microsoft.com/en-us/graph/permissions-reference#calls-permissions

Please note, these scopes require Application Permissions, which do not work with public client applications such as SPAs, as public client applications work with Delegated Permissions (which means these scopes will not work with the Implicit Flow, which MSAL.js uses). 

You can find more information about Application Permissions [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-configure-app-access-web-apis), and you find can an example of setting up a Confidential Client with MSAL.net [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-instantiate-confidential-client-config-options).

Also, in the future, please use one of the predefined issue templates, as listed [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/new/choose), thanks!

**Comment by sameerag** [comment]
@hamiltonha  We have many questions on scopes from folks using this library. Can we note this somewhere and have a FAQ which we can refer to? Tagging this as `documentation` issue assigned to you and me, so we can track this.

**Comment by sameerag** [comment]
@hamiltonha Since you are tracking this internally and it is now in the queue, closing this git issue.
