### ISSUE TITLE
msal@1.2.1 released

### ISSUE THREAD

**Issue by sameerag** [AzureAD/microsoft-authentication-library-for-js#1212]
`msal@1.2.1` is released.

- Please find the release in npm [here](https://www.npmjs.com/package/msal)
- The release notes can be found [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/releases/tag/v1.2.1)
- The release announcement is added to the wiki [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL-JS-1.2.X#msal-js-121-release).

> Note:

 CDN release can be found [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL-JS-CDN-URL-and-SRI-Hash).

**Comment by djleonskennedy** [comment]
@sameerag Hello
When do you plan update angular wrapper with new version ?

**Comment by jasonnutter** [comment]
@djleonskennedy Very soon, I'm working on preparing the next version now.

In the meantime, you can try the alpha version: `npm install msal@beta @azure/msal-angular@alpha`

More details here: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev-angular-1.0/lib/msal-angular/changelog.md#100-alpha1

Please file a separate issue if you any feedback on that, thanks!

**Comment by niravkanakhara** [comment]
Hi Team,
Currently i have used adal-angular package in one of my production application. For samesite issue I found that there is no update happening in adal-angular package. So I would like to upgrade my application from adal-angular to msal-angular. But I think msal-angular is still in preview stage, 

Is msal-angular in a stage where it can be configured and used in production application?

**Comment by jasonnutter** [comment]
@niravkanakhara Answered this in the other issue you opened, #1215.

**Comment by djleonskennedy** [comment]
@jasonnutter Thank you for answer! Regards

**Comment by sameerag** [comment]
UPDATE: CDN link updated
