### ISSUE TITLE
Any update for samesite cookie issue in latest Google Chrome?

### ISSUE THREAD

**Issue by niravkanakhara** [AzureAD/microsoft-authentication-library-for-js#1214]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Please describe the functionality or improvement you would like to see added.

**Comment by jasonnutter** [comment]
@niravkanakhara Yes, our services have been updated to appropriately mitigate SameSite cookie issues. Please see this issue for more details: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1037#issuecomment-573174503

Closing as a duplicate.

**Comment by niravkanakhara** [comment]
Thanks for update Jason.
Currently i have used adal-angular package in one of my production application. For samesite issue I found that there is no update happening in adal-angular package. So I would like to upgrade my application from adal-angular to msal-angular. But I think msal-angular is still in preview stage, 

Is msal-angular in a stage where it can be configured and used in production application?

**Comment by jasonnutter** [comment]
@niravkanakhara We're working on bringing MSAL Angular to GA, and we'll have more information on that soon.

And yes, it will work with Samesite cookies in Chrome (and similar browsers).
