### ISSUE TITLE
Question about Samesite and GA for MSAL Angular

### ISSUE THREAD

**Issue by niravkanakhara** [AzureAD/microsoft-authentication-library-for-js#1215]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

Hi Team, Currently i have used adal-angular package in one of my production application. For samesite issue I found that there is no update happening in adal-angular package. So I would like to upgrade my application from adal-angular to msal-angular. But I think msal-angular is still in preview stage,   Is msal-angular in a stage where it can be configured and used in production application?

**Comment by niravkanakhara** [comment]
Also will it have a solution for samesite cookie issue in Google Chrome?

**Comment by jasonnutter** [comment]
We're working on bringing MSAL Angular to GA, and we'll have more information on that soon.

And yes, it will work with Samesite cookies in Chrome (and similar browsers).

**Comment by jasonnutter** [comment]
MSAL Angular is nearing GA, closing as no further action at this time.
