### ISSUE TITLE
Problem with renew token in Angular (msal-angular alpha)

### ISSUE THREAD

**Issue by asanchezfe** [AzureAD/microsoft-authentication-library-for-js#1218]
## Library
- [ ] `msal@1.2.1`
- [ ] `@azure/msal-angular@1.0.0-alpha.1`

## Framework
 Angular 8.2.14

## Description
I was having a related issue with msal-angular 0.1.4 so I tried to update to the new alpha version to check if the library worked correctly

The login works correctly, but after 1 hour, when it needs to renew the token, calls AAD and gets a new token which is stored correctly in local Storage but the first Https calls are made with "Bearer null" so they get a 401 http error.

I don't know if the interceptor doesn't wait enough time to have the token before inject it to the call or is a problem with scopes :S

## Configuration
```js
export function MSALConfigFactory(/*config: ConfigService*/) {
  return {
    auth: {
      clientId: 'MY_CLIENT_ID_KEY',
      authority: 'https://login.microsoftonline.com/MY_TENANT',
      validateAuthority: true,
      redirectUri: 'http://localhost:4200',
      postLogoutRedirectUri: 'http://localhost:4200',
      navigateToLoginRequestUrl: true
    },
    cache: {
      cacheLocation: 'localStorage',
      storeAuthStateInCookie: false
    },
    framework: {
      unprotectedResources: [],
      protectedResourceMap: new Map([['//myapimanager.com', ['api://MY_CLIENT_ID_KEY/user_impersonation']]])
    }
  };
}

export function MSALConfigAngularFactory(config: ConfigService) {
  return {
    popUp: false,
    consentScopes: ['api://MY_CLIENT_ID_KEY/user_impersonation'],
    extraQueryParameters: {}
  };
}
```

## Reproduction steps
1. login
2. wait 1 hour
3. navigate through the angular app again

## Expected behavior
Session should renew silently without errors.

## Browsers
Tested on Firefox 🦊  and Chrome

**Comment by AndriiDidkivsky** [comment]
Hi, same issue. We really do need fresh msal-core version. 
When are you going to release new angular-msal ? 
Cause for now the only one solution is  integrating with msal-core on my own.

**Comment by jasonnutter** [comment]
@asanchezfe To clarify, the access token is correctly attached in the Authorization header, but then after an hour, you get `null`? Does this happen every time or is it intermittent?

**Comment by asanchezfe** [comment]
Hi @jasonnutter
I'm not really sure if sometime works, but it seems to happen every time.
Let's see a sample:
- I was using the app until  09:55.
- I left the computer and after a while, at 11:13 I make an action on the app (I didn't close the tab) that makes a REST call so Msal interceptor makes a GET call to
`https://login.microsoftonline.com/MY-CLIENT-ID/v2.0/.well-known/openid-configuration`
It responses as cached at 09:52. 
At 11:13:36, it opens the app in the iframe passing the hash with a new token. At the exact time, makes the REST call to back service with  `Bearer null` that faills.
- Just some second laters, I repeat the operation (11:13:48) makes the call correctly.

Here is the net traffic:
![screen-token2](https://user-images.githubusercontent.com/11560329/73537799-a02ef000-4429-11ea-96f0-2d910790c6c1.PNG)

**Comment by jasonnutter** [comment]
@asanchezfe Thanks for that info. I'll investigate and let you know if I need more info.

**Comment by asanchezfe** [comment]
Any update on this? We still have this issue with beta 4 and msal 1.2.2 ☹️

**Comment by jasonnutter** [comment]
@asanchezfe My theory is that in this scenario, the interceptor is retrieving an ID token instead of an access token, which would explain why `acquireTokenSilent` succeeds but `accessToken` is null. I'm working on potential fix to allow your app to better handle this, will follow up when its ready.

**Comment by asanchezfe** [comment]
@jasonnutter Thank you for your work, currently I'm thinking the scopes configuration has some influence

**Comment by asanchezfe** [comment]
@jasonnutter updating info: I saw that was apparently only happening on some environments.
I think this happens: in environtments when API is on same host, API is not defined under the `protectedResourceMap` map so the MsalService `getScopesForEndpoint` method is returning clientId as only scope and this causes to get an ID token... Don't should it use all `consentScopes ` by default?

**Comment by jasonnutter** [comment]
> @jasonnutter updating info: I saw that was apparently only happening on some environments.
> I think this happens: in environments when API is on same host than Ng front, API is not defined under the `protectedResourceMap` map so the MsalService `getScopesForEndpoint` method is returning clientId as only scope and this causes to get an ID token... Don't should it use all `consentScopes ` by default?

No, because `consentScopes` could include scopes that span multiple resources. Does adding the API to `protectedResourceMap` fix it for you?

**Comment by asanchezfe** [comment]
Hi @jasonnutter, I have ensured now It works correctly, it was the config causing the clientId to be the single scope

**Comment by jasonnutter** [comment]
@asanchezfe Great, thanks for the update!

Closing.
