### ISSUE TITLE
loginredirect get user details in background without redirecting to microsoft login page

### ISSUE THREAD

**Issue by kiranbudati** [AzureAD/microsoft-authentication-library-for-js#1224]
Is there any way to get user details with `loginredirect` without opening new window or login screen.

Need to get details in background

**Comment by sameerag** [comment]
Can you please expand your use case in more detail @kiranbudati? `loginRedirect` is opted to login when a SPA chooses not to have `popUps` to authenticate. Without logging in, there is no user information and hence your question is a little unclear for me.
