### ISSUE TITLE
Silent token requests cancel any active popup requests.

### ISSUE THREAD

**Issue by keystroke** [AzureAD/microsoft-authentication-library-for-js#1226]
## Library
- [x] `msal@1.2.0` or `@azure/msal@1.2.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

None.

## Description

Silent token requests cancel any active popup requests.

## Security
Is this issue security related?

No.

## Regression
Did this behavior work before?

No.

## Configuration
Please provide your MSAL configuration options.

```js
const msal = new Msal.UserAgentApplication({
    auth: {
        clientId: 'a963b646-fa01-4c06-b302-42c6ed1b2774',
        authority: 'https://login.microsoftonline.com/common'
    }
});
```

## Reproduction steps

Below is a sample. Attempt to initiate a silent token request while a popup request is active. The silent token request will implicitly cancel the popup request.

````html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>MSAL Bug</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.min.js" class="pre"></script>
    <script src="https://alcdn.msauth.net/lib/1.2.0/js/msal.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.min.js"></script>
</head>

<body>

    <script>
        'use strict';
        $(document).ready(function (e) {

            const msal = new Msal.UserAgentApplication({
                auth: {
                    clientId: 'a963b646-fa01-4c06-b302-42c6ed1b2774',
                    authority: 'https://login.microsoftonline.com/common'
                }
            });

            msal.handleRedirectCallback(function (error, response) {
                console.log('MSAL redirect callback: ', { error: error, response: response });
            });

            if (msal.isCallback(window.location.hash)) {
                return;
            }

            if (!msal.getAccount()) {
                msal.loginRedirect({
                    scopes: ['openid'],
                    prompt: 'select_account'
                });
                return;
            }

            msal.acquireTokenPopup({ scopes: ['openid'], prompt: 'consent' })
                .then(console.log.bind(console))
                .catch(console.error.bind(console));

            setTimeout(function () {
                msal.acquireTokenSilent({ scopes: ['openid openid'] })
                    .then(console.log.bind(console))
                    .catch(console.error.bind(console));
            }, 3000);
        });
    </script>

</body>

</html>
````

If you run the sample above, it will open a popup, and then if you wait for the silent token request, it will automatically cancel the popup. If you are wondering why I have to use scope 'openid openid', it is an extension of issue #1225, though in this case, it seems that MSAL will collide on the target iframe for silent and popup, so that is perhaps a further disambiguation that needs to be implemented for hidden iframes beyond just scope and authority!

## Expected behavior

MSAL should support concurrent token requests. It may be fine to restrict token popups to one at a time, but MSAL should internally defer execution of concurrent popup requests so only one is active at a time, instead of forcing clients to build extraordinarily complicated wrapper modules for MSAL to do this. It should also ensure silent token requests may continue even when a active popup is present. And of course, it should support these concurrent silent token requests for multiple different authorities (see #1225 for more details).

## Browsers
Is this issue browser-specific? If so, please detail which browsers are impacted (e.g. IE 11, Safari).

Any browser.

**Comment by jasonnutter** [comment]
@keystroke Can you please clarify the use case for this? I understand making this work for different request scopes (e.g. you need tokens from two different resources, e.g. MS Graph and custom Web API), but making a silent and interactive request for the same scopes (as your demo code does) doesn't make sense to me.

**Comment by keystroke** [comment]
@jasonnutter My use case is the scenario you understand, getting tokens for difference scopes ;)

You might be interested to check the behavior yourself though: what happens if an active popup request is ongoing for a particular set of scopes / authority, and other code in the app induces a new silent token request for the same scopes / authority? What might you expect the behavior to be?

In that case, the silent token request gets joined to the active popup request, due to some behavior which I suspect is related to #1225. Both callbacks (for the popup and the silent request) are invoked with the result of the popup request, because they both seem to "point" to the same iframe. But in this case, the popup was created explicitly, and the silent request only completes immediately if the token is in the cache. If the token isn't in the cache, then MSAL just adds the extra callback to the popup request, meaning the silent token request catch handler gets invoked with the "user cancelled the popup" error callback (or whatever the result was).

In the example above for this issue, I could've used the popup request with scope "openid" and the silent request with "User.Read", and the behavior would also be as described in my post (the silent request, when initiated, cancels the active popup, interrupting the user's interaction with it).

I used the duplicate scope "openid openid" to more directly point you folks at a core mechanic of the issue, which is around properly isolating concurrent token requests in their various forms, based on authority, requested scopes, and apparently silent vs popup should also be taken into account because of the semantic differences around the code that induces them.

But what should the behavior be here in general? If two different parts of my app both induce a silent token request with overlapping claims, should those be processed separately, or joined together? I think that popup vs silent should be separated, but duplicate silent requests could perhaps be joined.

I'm trying to do the whole progressive permission thing, where different parts of my app are rendered with a "click here to grant consent" experience when interaction is required on the failure of a silent token request, but actually running that popup request requires draining all the active silent requests, then blocking new ones while the popup is running, and also I have to build a queue to serially process concurrent popup request that may come in. Consider what happens if two different areas of my app need consent, and the user induces both at the same time. Maybe I can be careful to block this by disabling the buttons when one is pressed, etc. But it gets complicated quickly to build a wrapper in front of MSAL client to queue and process all the concurrent token requests that could occur in a way where MSAL doesn't break or hand-back the wrong tokens to the wrong callbacks.

**Comment by jasonnutter** [comment]
@keystroke Thanks for the context, and apologies for the delayed follow up. We'll definitely make sure that requests are not cancelled and that the right tokens are handed back to the right requests.

Having the same-scoped requests de-duped into a single request is unlikely to change, as we need to help prevent clients from unintentionally making too many of the same request in a short period of time, as that can result in throttling errors from eSTS.  

For now, I would recommend creating your own abstracts (which I personally think is a good idea, regardless) to help mitigate the issues you are seeing, in lieu of fixes from the library. We'll keep this open to track work on a fix.

**Comment by keystroke** [comment]
@jasonnutter can you please clarify:

1. If multiple silent token requests (all with the same properties) are initiated within a short duration, they will all resolve to the same target iframe, and thus receive the same result in their callbacks (like how promise branching works). Will this literally be the same promise object, or distinct promise objects that all resolve or reject with the same data? Not sure if the difference matters, just curious.

2. Please confirm that you would never join silent token requests and popup token request, regardless of the overlap in authority / scopes / etc. These operations are semantically distinct and I believe it is completely invalid for a catch handler of a silent token request to receive errors like "user cancelled the popup request" if you were to join these requests together to the same iframe / promise.

3. When you say that I should build my own abstractions in front of MSAL, can I assume that you mean MSAL will internally ensure that while a popup request is active, arbitrary silent token requests can be initiated and complete concurrently to that popup request? Furthermore, what is the behavior to be for multiple popup requests, should apps ensure they sequence popup requests serially?

4. If you intend for clients to wrap MSAL to handle concurrency, then will you provide us interfaces to retrieve all the active token requests that are currently running, covering both silent and popup requests?

**Comment by jasonnutter** [comment]
@keystroke 

1. Yes, they will reuse the same iframe and get the same result. There will be multiple promises that are each given the same result.
2. They are separate promises, so I don't think that is happening. What I do see happening is that if you fire a silent and popup request for the same set of scopes, and if the silent request finishes first, it will close any popups, without indicating to the code monitoring the popup that the closure is the result of a successful response. This results in an error being thrown in the code monitoring the popup, because it assumes that if the popup it was monitoring was closed, that it was because the user closed the popup, and not because a similar silent request succeeded. I believe this is the root cause of your issue, and something we should fix.
3. Yes, MSAL should make sure that you can make silent request(s) while a popup request is ongoing. The library does not allow for multiple interactive request in parallel, so yes, apps would need to sequence popup requests.
4. We don't have any plans for that, but something we can consider.

**Comment by keystroke** [comment]
@jasonnutter You need to try-out all the combinations ;)

In below version of sample, I trace each callback distinctly to make it easier. This should help clarify what I was getting at in the second item of my previous reply. What you noted can be seen in configurations 1 and 4 in below table, whereas I am also concerned about the behavior in configurations 2 and 3. It changes based on which request is initiated first (silent or popup), and whether they have the same scopes or different scopes. I also strongly advise you (or whomever will work on fix for this issue) also check-out issue #1225 as that same error affects the outcomes shown below (it is the reason why the "same" scoped requests are joined together in configurations 2 and 3 and why they don't behave like configurations 1 and 4).

````html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>MSAL Bug</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.min.js" class="pre"></script>
    <script src="https://alcdn.msauth.net/lib/1.2.0/js/msal.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.min.js"></script>
</head>

<body>

    <script>
        'use strict';
        $(document).ready(function (e) {

            const msal = new Msal.UserAgentApplication({
                auth: {
                    clientId: 'a963b646-fa01-4c06-b302-42c6ed1b2774',
                    authority: 'https://login.microsoftonline.com/common'
                }
            });

            msal.handleRedirectCallback(function (error, response) {
                console.log('MSAL redirect callback: ', { error: error, response: response });
            });

            if (msal.isCallback(window.location.hash)) {
                return;
            }

            if (!msal.getAccount()) {
                msal.loginRedirect({
                    scopes: ['openid'],
                    prompt: 'select_account'
                });
                return;
            }

            const popupRequest = { scopes: ['openid'], prompt: 'consent' };
            const popupRequestTime = 2000;

            const silentRequest = { scopes: ['openid'], forceRefresh: true };
            const silentRequestTime = 1000;

            setTimeout(function () {
                console.log("initiating popup token request...");
                msal.acquireTokenPopup(popupRequest)
                    .then(handler("success handler for token popup"))
                    .catch(handler("error handler for token popup"));
            }, popupRequestTime);

            setTimeout(function () {
                console.log("initiating silent token request...");
                msal.acquireTokenSilent(silentRequest)
                    .then(handler("success handler for token silent"))
                    .catch(handler("error handler for token silent"));
            }, silentRequestTime);

            function handler(prompt) {
                return function (input) {
                    console.log(prompt, input.message || input);
                }
            }
        });
    </script>

</body>

</html>
````

Let's make a table of outcomes. When scopes indicate "same" then both requests are made using a single scope value of "openid" and when this value is "different" it indicates that the popup request scope is changed to "User.Read" scope. Order indicates the order in which the requests are initiated; the first token request listed is initiated 1 second before the other. Please note that I am forcing the popup and the silent requests to actually be initiated here, rather than relying on cached tokens or prior consent to take effect.

|scopes|order|interaction|result|notes
|-|-|-|-|-|
|same or different|silent, popup|~|silent succeeds, silent handler invoked with token result, popup error handler invoked with "user cancelled" error|This behavior is not correct and we agree on the desirged behavior; the outcome of the silent request should have no effect on the popup request.|
|same|popup, silent|click accept or cancel button|Both requests are "joined" together; the silent request will not resolve until the popup request resolves. Both success / error handlers are invoked with the same result|This is not correct behavior either. The silent token request should pass/fail independently from the popup request (after-all, it is the error handler of the silent token request that should decide whether to initiate a popup request or not, and in many cases, that may not be the desire, and slows-down or breaks the app).|
|same|popup, silent|close popup window|The silent request is left unresolved and never completes; only the error handler for the popup request is invoked|This seems like a "separate" issue though it will invariably be affected by the resolution of this issue; I might've expected the behavior to match the previous outcome.|
|different|popup, silent|~|silent succeeds, silent handler invoked with token result, popup error handler invoked with "user cancelled" error|Same outcome as first example.|

I would assume at this point that you plan on fixing the issues around how silent and popup requests affect each other. Assuming those fixes would go-in, it would imply that I can make arbitrary and concurrent silent token requests without concern for the other token activity in my app (each silent token request having a distinct outcome, with the exception that duplicate *silent* token requests may be joined together, but that a popup token request and silent token request would never be joined together, regardless of any overlap in scopes / authority, and regardless of the order in which they are initiated). Please confirm if I can expect this behavior (eventually at least; I understand triage is necessary and it may take a while).

What is left undefined, is the behavior around concurrent popup requests, and whether those need to be sequenced by my app, or whether the library will handle that internally (either by: internally sequencing the popup requests itself; supporting concurrent popup requests; or by throwing an exception indicating an active popup request is already underway (as your own client should never implicitly terminate an ongoing request because a new one is initiated).

**Comment by jasonnutter** [comment]
@keystroke Thanks for the thorough breakdown. Yes, we will fix the issues with silent/popup requests interfering with each other, and I agree that each request being its own distinct operation should be the default (especially since it will simplify the request handling code in the library, which I think is overly-complex due to some of the optimizations that were made to "join" requests). We'll discuss this amongst the team and follow up with a plan (as it is possible these two changes will be made incrementally, especially since the later may not be trivial).

The library currently does not allow multiple concurrent interactive requests (e.g. popup or redirect), and will throw an error if a client attempts to do so.

**Comment by keystroke** [comment]
@jasonnutter Thanks! Sorry for any confusion around the scenarios (and for my aggressive details), it definitely gets complicated to discuss. Appreciate your time and confirmation on target behavior!

I did also check behavior as you indicate; concurrent popup requests beyond the first will immediately resolve an error to their catch handler with the message "AcquireToken_In_Progress: Error during login call - login is already in progress." Not sure I would've used "login" verbiage here but that's not an issue; this behavior seems fine and I can orchestrate a popup request queue in the application layer (once the overlap with silent requests is removed).

**Comment by pkanher617** [comment]
We have shipped enhancements for MSAL v1 to include authority in the iframe IDs, and we will implement throttling and request signatures in v2 to help mitigate these issues in the future.

**Comment by senthilkumarnh** [comment]
Is this resolved msal v2?
