### ISSUE TITLE
MSAL Library Config for Anguar 7 to work with tenant.b2clogin.com

### ISSUE THREAD

**Issue by anish-pillai** [AzureAD/microsoft-authentication-library-for-js#1228]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x ] `@azure/msal-angular@0.1.4`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
Angular 7.0.3

## Description
Current version of @azure/msal-angular library used in our Angular 7 application is 0.1.4

In the config, validateAuthority is set true application doesn't bring up the login screen. Rather it gives AADSTS50049 exception in browser developer window. For now, I have set the validateAuthority to false and application lets me log in.

How should the MSAL be configured to support the latest tenant.b2clogin.com sothat the application works with Angular 7?

## Security
Yes

## Regression
This used to work with 
`validateAuthority: true` in MSAL Config and 
authority: 'https://login.microsoftonline.com/tfp/' + tenant + '/B2C_1A_signup_signin'

When the authority was changed to new B2C 'tenant.b2clogin.com', with validateAuthority as true, I see AADSTS50049 exception in browser developer window.

## Configuration
```
MsalModule.forRoot({
      clientID: environment.clientID,
      authority: environment.authority,
      redirectUri: environment.redirectUri,
      validateAuthority: true,
      cacheLocation: 'localStorage',
      postLogoutRedirectUri: environment.postLogoutRedirectUri,
      protectedResourceMap: protectedResourceMap,
      unprotectedResources: ['./assets/i18n/en.json'],
      consentScopes: [environment.clientScope1],
      navigateToLoginRequestUrl: false,
      logger: loggerCallback,
      popUp: false,
      isAngular: true,
    }),

```js
// Provide configuration values here.
We are using custom sign in policy.
```

## Reproduction steps
1.  Run angular 7 application with authority as tenant.b2clogin.com and validateAuthority: true
2. Application doesnt give login screen

## Expected behavior
User should be able to see login screen & upon authentication, user should be able to access the application.

**Comment by jasonnutter** [comment]
@anish-pillai This is a known issue, and setting `validateAuthority` to `true` is our recommended workaround. We have this tracked in #1187, so closing this.
