### ISSUE TITLE
msal@v1.2 - When acquireTokenSilent fails, it never times out, and promise never resolves

### ISSUE THREAD

**Issue by Tim91084** [AzureAD/microsoft-authentication-library-for-js#1230]
## Library
- [x ] `msal@1.2.x`

## Framework
React@latest

## Description
acquireTokenSilent doesn't fail/time out properly when 3rd party cookies are disabled.

## Security
No

## Regression
Yes, works in 1.1.x

## Reproduction steps
You can reproduce this by disabling 3rd party cookies and then trying to acquire a token silently using the library.  You'll see that the library tries to make a request here:  https://login.microsoftonline.com/[tenent]/oauth2/v2.0/undefined

This won't work and should fail immediately, but for some reason the msal library is not handling this properly.  My app depends on this failure/timeout to then issue an acquireTokenPopup.

## Expected behavior
When acquire token silent fails, it should properly resolve/reject the promise

## Browsers
Tested in Chrome

**Comment by Draccoz** [comment]
Encountered this issue as well.

**Comment by Chryogenic** [comment]
This happens to me as well. Does anyone have a workaround?

**Comment by jasonnutter** [comment]
@Tim91084 Apologies for the delay in responding. I have some theories about what is happening, I'll investigate and follow up.

**Comment by Chryogenic** [comment]
Hi @jasonnutter, were you able to look into this issue? Thanks!

**Comment by jasonnutter** [comment]
@Chryogenic Not yet, I'll follow up when I have.

**Comment by mbrevda** [comment]
This seems to be happening for as well since updating to 1.2.1

**Comment by jasonnutter** [comment]
The fix for this is available in `msal@1.2.2-beta.2`, please try that version and confirm that it has been fixed, thanks!

**Comment by jasonnutter** [comment]
And to be clear, the new version above ensures MSAL will at worst timeout. The specific issue of `https://login.microsoftonline.com/[tenent]/oauth2/v2.0/undefined` requests we believe is an issue with the service, not the library, and the service team is investigating this now.
