### ISSUE TITLE
Msal-Browser stale state blocking login?

### ISSUE THREAD

**Issue by garrettm** [AzureAD/microsoft-authentication-library-for-js#1231]
## Library
`@azure/msal-browser@2.0.0-alpha.0`

## Framework
React, but I don't think that matters

## Description
Sign in state gets stuck on `interaction_in_progress`

See https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1000#issuecomment-576896230

## Reproduction steps
(I think these work, but not 100%)
1. Open a sign in pop up
2. Close/refresh the web app
3. Close the sign in pop up
4. Try to open a sign in pop up again from the reloaded app
5. Open fails, says it's blocked by interaction

## Expected behavior
I'd expect that a freshly reloaded app wouldn't have login blocked by prior app state

## Browsers
I tried it in Chrome

**Comment by pkanher617** [comment]
Thanks @garrettm, I am reviewing this and debugging the issue.

**Comment by tnorling** [comment]
Closing as this was fixed in the mentioned PR. Let us know if this is still an issue.

**Comment by randompixel** [comment]
![image](https://user-images.githubusercontent.com/2316601/89685694-c2338e80-d8f4-11ea-99d6-e1ddf7648588.png)
I'm still seeing this using MSAL 2.0.1. I had prior cleared out all session and cookies, but coming back to the app this evening encountered this error. Pressing F5 to completely reload app doesn't fix it.

**Comment by randompixel** [comment]
Although it seems by checking if user is authenticated before getting tokens for API request this fixes this. I guess it is trying to get a token as the SPA builds up and then the loginRedirect is being called which fails.
