### ISSUE TITLE
AcquireTokenRedirect redirect to "wrong" page / policy with Google (B2C)

### ISSUE THREAD

**Issue by Nasicus** [AzureAD/microsoft-authentication-library-for-js#1233]
MSAL Version: `1.2.1` 

So I have the following scenario:
On my site I have different login possibilites: AzureAd (login.microsoft), B2C (E-Mail) and B2C (Gmail).

For the google login I have a button to allow the log in directly, without first redirecting to the policy page and then there selecting the Google Login button again.
For this I create the MSAL client with this config:

```
{
   "auth":{
      "clientId":"whatever-c1c5-41da-8e22-1252b5fed0e4",
      "authority":"https://whatever.b2clogin.com/tfp/whatever.onmicrosoft.com/B2C_1_SignInSignUpPolicy",
      "redirectUri":"http://localhost:3000/login-complete",
      "postLogoutRedirectUri":"http://localhost:3000",
      "navigateToLoginRequestUrl":false,
      "validateAuthority":false
   },
   "cache":{
      "cacheLocation":"localStorage",
      "storeAuthStateInCookie":false
   }
}
```

And then call the `loginRedirect` method with this config:

```
{
   "scopes":[
      "https://whatever.onmicrosoft.com/web/access_as_user"
   ],
   "extraScopesToConsent":[
   ],
   "extraQueryParameters":{
      "domain_hint":"google.com"
   },
   "prompt":"login"
}
```

The relevant bit here is the `domain_hint` I guess, because this redirects directly to the google login page.
Also noteworthy is that the `B2C_1_SignInSignUpPolicy` has no google button anymore, it basically looks like this:
![image](https://user-images.githubusercontent.com/1086065/72873066-23946700-3cef-11ea-913f-0b53a7ea80b4.png)

Now this all works flawlessly.

Also as long as `acquireTokenSilent` still works we're fine.

However in the case `acquireTokenSilent` throws this exception...
```
{"errorCode":"interaction_required","errorMessage":"AADB2C90077: User does not have an existing session and request prompt parameter has a value of 'None'.\r\nCorrelation ID: 9187eec3-4f88-4aaf-b205-3d0ac006bd75\r\nTimestamp: 2020-01-22 07:07:27Z\r\n","name":"InteractionRequiredAuthError"}
```
... things start to go down hill.

When this happens I  do a `acquireTokenRedirect`.
The client is in this case created like this (same as before):
``` 
{
   "auth":{
      "clientId":"whatever-c1c5-41da-8e22-1252b5fed0e4",
      "authority":"https://whatever.b2clogin.com/tfp/whatever.onmicrosoft.com/B2C_1_SignInSignUpPolicy",
      "redirectUri":"http://localhost:3000/login-complete",
      "postLogoutRedirectUri":"http://localhost:3000",
      "navigateToLoginRequestUrl":false,
      "validateAuthority":false
   },
   "cache":{
      "cacheLocation":"localStorage",
      "storeAuthStateInCookie":false
   }
}
```
... and the request config is this:

```
{
   "scopes":[
      "https://whatever.onmicrosoft.com/web/access_as_user"
   ]
}
```
And now instead of redirecting to the google login page, the user is redirected to the actual policy page (screenshot above). As you can see there is no google button there, therefore the user has NO WAY to log in anymore and is stuck forever.

The URL now looks like this:
```
https://whatever.b2clogin.com/whatever.onmicrosoft.com/b2c_1_signinsignuppolicy/oauth2/v2.0/authorize?response_type=token&scope=https%3A%2F%2Fwhatever.onmicrosoft.com%2Fweb%2Faccess_as_user%20openid%20profile&client_id=whatever-c1c5-41da-8e22-1252b5fed0e4&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Flogin-complete&state=whatever-6512-402b-8b1d-1546f2c661ff&nonce=2410fcb1-a498-46d7-9fc1-7dcfbbfc4560&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=1.2.1&login_req=whatever-4d15-4958-81d5-d29b091def63-b2c_1_signinsignuppolicy&domain_req=whatever-a7ab-43e9-bcbd-83bfd11e56b9&domain_hint=organizations&client-request-id=c9193000-da7e-4ee7-a6e7-51a8d0dec72e&response_mode=fragment
```
Notice that the `domain_hint` is set to `organizations`.

Now you might say: "It's ovious! When calling  `acquireTokenRedirect` you have to pass in the `"extraQueryParameters":{"domain_hint":"google.com"}` again"!

I tried that, but that also doesn't work, it redirect to the same page and the URL looks like this:

```
https://whatever.b2clogin.com/whatever.onmicrosoft.com/b2c_1_signinsignuppolicy/oauth2/v2.0/authorize?response_type=token&scope=https%3A%2F%2Fwhatever.onmicrosoft.com%2Fweb%2Faccess_as_user%20openid%20profile&client_id=whatever-c1c5-41da-8e22-1252b5fed0e4&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Flogin-complete&state=whatever-9432-4fc2-8a55-5cfda325e967&nonce=4f936d31-eefe-45dc-8673-c38c075a0d5f&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=1.2.1&login_req=whatever-4d15-4958-81d5-d29b091def63-b2c_1_signinsignuppolicy&domain_req=whatever-a7ab-43e9-bcbd-83bfd11e56b9&domain_hint=organizations&domain_hint=google.com&client-request-id=ba18d43d-0781-402f-8392-48eb3346917d&response_mode=fragment
```
As you can see now there are 2 domains hints: `domain_hint=organizations&domain_hint=google.com`.

If I now try to manually remove the `domain_hint=organizations` the page redirect directly (somewhere?) goes back to my app, but MSAL does nothing and no callback etc. happens.
Somewhere there is an error thrown
`TypeError: Cannot read property 'requestContent' of undefined` (not sure if this is from MSAL).

So bascially my questions are:
- Is this a supported scenario?
- Am I doing something wrong?
- Shouldn't MSAL in `acquireTokenRedirect` already redirect to google themselves?

PS: If I look at my token in the local storage, you can clearly see the `idp` is google:
![image](https://user-images.githubusercontent.com/1086065/72873891-1d06ef00-3cf1-11ea-9096-50b6978c3445.png)

**Comment by tnorling** [comment]
@Nasicus Apologies for the delayed response. We recently released ```msal@1.3.0-beta.1``` which contains a fix for how we handle ```domain_hint```. Could you try to upgrade your msal version and let us know if this fixes your issue?

**Comment by Nasicus** [comment]
Will do thanks (will need some time, since I actually need to wait until the token expires, so I get to the required screen - or is there any easy way to fake this via the local storage?)

**Comment by tnorling** [comment]
Unfortunately invalidating a token is not currently possible. The best way to test the login screen once you've already logged in would be either to log out or to open an incognito window.

**Comment by Nasicus** [comment]
It looks like you misread or misunderstand my issue. Because for the initial login screen, we never had or have a problem. On our login screen there is bascially a Google button an a Email button, if the user clicksthe google button he is redirected directly to the google login (this works). But when a relogin is  required (i.e. acquireTokenRedirct) is called then the user is redirected to the b2c login screen instead of directly to google.

**Comment by tnorling** [comment]
Got it. For testing purposes you can try setting ```prompt:"login"``` in the request object sent to acquireTokenRedirect and either removing the token from the local storage or setting the ```expiresIn``` property to 0.

**Comment by Nasicus** [comment]
I actually just logged in yesterday evening and refresh just now. 

However I didn't get redirected to the google login scren, instead I got to the b2c page:

```
https://<mytenant>.b2clogin.com/condenseappexternaldev.onmicrosoft.com/b2c_1_signinsignuppolicy/oauth2/v2.0/authorize?response_type=token&scope=https%3A%2F%mytenant>.onmicrosoft.com%2Fweb%2Faccess_as_user%20openid%20profile&client_id=a13a12ba-a1a5-41aa-8e22-1252b5fed0e4&redirect_uri=https%3A%2F%2Fmy-app.azurewebsites.net%2Flogin-complete&state=eyJpZCI6IjJiYzQ5NGI5LTA3YTUtNGRkNS05ZmEzLTUxYzhjZDcyMTQ2YyIsInRzIjoxNTg2OTc1MzQ1LCJtZXRob2QiOiJyZWRpcmVjdEludGVyYWN0aW9uIn0%3D&nonce=590f7927-ad7a-468b-bde5-9a5fce79ca60&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=1.3.0&client-request-id=7b62ee75-3769-42af-8a4b-2f92d133174f&response_mode=fragment
```

And in the console I could also see this error:

```
Will try to get the token via acquireTokenRedirect, because an error happened when calling acquireTokenSilent {"errorCode":"interaction_required","errorMessage":"AADB2C90077: User does not have an existing session and request prompt parameter has a value of 'None'.\r\nCorrelation ID: 37ff7e00-ef3e-4026-a39e-9602349a3326\r\nTimestamp: 2020-04-15 18:29:05Z\r\n","name":"InteractionRequiredAuthError"}
```

=> I now did a relogin (we just put the google button back to th b2c login page for now) and will check the same scenario again yesteray evening or so

**Comment by tnorling** [comment]
So what I'm not seeing in the url you pasted above is the ```domain_hint``` parameter, this is why you are getting the b2c page and not the google page. Note that ```domain_hint``` will only be sent to interactive calls (redirect or popup), it is not supported for silent calls. Given that your session expired it is expected that the ```acquireTokenSilent``` call would fail. When you get an ```interaction_required``` error you should add ```domain_hint``` in ```extraQueryParameters``` to your request object and then call ```acquireTokenRedirect```

**Comment by Nasicus** [comment]
Right. I could have sworn we already do that, but we didn't so I changed it and will update you tomorrow or so if it worked.

Thanks in advance!

**Comment by Nasicus** [comment]
Nice! Can confirm this is now fixed. Not even sure if the problem was the version upgrade or just that I didn't pass the domain hint properly?

Thanks!
