### ISSUE TITLE
get data from login page in the app

### ISSUE THREAD

**Issue by daniel-codeoasis** [AzureAD/microsoft-authentication-library-for-js#1242]
## Library
- [ X] `msal@1.2.1` 

## Description

I'm using msal.js in my Angular app (**not** the Angular wrapper).
I'm sending the "ui_locales" query param to the login page so the user can see the page in the same language he had in my app.

but if the user changes this parameter I want to know about it and redirect him to the corresponding language. 

the redirect callback in the "response-handler" doesn't have any query params or data about "ui_locales"...

how can I get this information?

(the problem is that I have only one redirect-uri which is the English site,
so when the user finish the login process I want to redirect him to the same site he had in his "ui_locales" parameter)

**Comment by sameerag** [comment]
@daniel-codeoasis Our `response` is constructed based on the `service  response`.  I do not think `ui-locales` are supported but will reach out once I confirm it.

Other options I can think of for you to tie up a request to a response is to pass a "state" parameter with the request, which is returned unchanged to you.

**Comment by daniel-codeoasis** [comment]
> @daniel-codeoasis Our `response` is constructed based on the `service response`. I do not think `ui-locales` are supported and neither do we send any `extraQueryParameters` passed to us as the response to the user.
> 
> Options I can think of for this use case:
> 
> * Tie up a request to a response is to pass a "state" parameter with the request, which is returned unchanged to you.
> * `redirectUri` can be set per request. I am assuming you are calling `acquireTokenRedirect` whose response is redirected to the`redirectUri` set in the request. Can you try that and let us know if it works for your use case?

Thank you for the response.

The first method you mentioned might work, but I don't want to change the "state" parameter in the login page manually, which may cause unwanted side effects.

setting different redirectURI won't work also, possible scenario:
user starts with the English version -> get the "/en" redirectURI -> changing the ui_locales in the login page to "/es" and now I want him to come back to the "/es" page and not the "/en".
I can change the redirectURI manually using JS on the login page but I'm afraid of side effects.

**Comment by daniel-codeoasis** [comment]
For now, I manage to have this functionality by changing the "redirect_uri" parameter in the url with JS, and adding each redirect_uri I want to support in Azure. 

if there a better way to do it please tell me.

**Comment by pkanher617** [comment]
Hi @daniel-codeoasis, I'm a little confused by your use case. Is this being done for a B2C use case as described [here?](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-reference-language-customization#customize-the-page-ui-by-using-language-customization). If so, then it will be a little more complicated as we only support user query parameters, no path changes. We are working with the B2C team to understand these scenarios, and we hope to have some features out in the next few months to support them.

You can try sending the following as an option to the request parameter:
```javascript
extraQueryParameters: {
     "ui_locales": "<desired language code>"
}
```
but I am unsure if the B2C service will consume this query parameter. 

If this does work, you can also send the value in the state parameter for the request, and it will be available in the accountState parameter of the response.

**Comment by daniel-codeoasis** [comment]
> Hi @daniel-codeoasis, I'm a little confused by your use case. Is this being done for a B2C use case as described [here?](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-reference-language-customization#customize-the-page-ui-by-using-language-customization) If so, then it will be a little more complicated as we only support user query parameters, no path changes. We are working with the B2C team to understand these scenarios, and we hope to have some features out in the next few months to support them.
> 
> You can try sending the following as an option to the request parameter:
> 
> ```js
> extraQueryParameters: {
>      "ui_locales": "<desired language code>"
> }
> ```
> 
> This is how our samples our configured to work. Please let me know if this works for you.
> 
> If this does work, you can also send the value in the state parameter for the request, and it will be available in the accountState parameter of the response.

my scenario is as follows: 
- the user goes to my-site.com/en
- redirect to an English login page.
- in the login page, the user changes the language to Spanish (ui_locales = "es").
- the user performs a login, and by default redirected to my-site.com/en

I want to redirect him to the Spanish site (my-site.com/es).

**Comment by pkanher617** [comment]
As I said above, please try sending 
```
extraQueryParameters: {
     "ui_locales": "<desired language code>"
}
```
and see if this works for the B2C service. If this doesn't work I can do more investigation into how to get this use case working for you.

**Comment by tnorling** [comment]
Closing as the question was answered. Please reopen if you still need assistance.
