### ISSUE TITLE
Is BroadcastService's use of observables set in stone, or can it be improved?

### ISSUE THREAD

**Issue by rellis-of-rhindleton** [AzureAD/microsoft-authentication-library-for-js#1244]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [x] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

BroadcastService exposes a way to subscribe to messages regarding msal activity, but the way it works is not what I would normally expect in an Angular application, or with RxJS in general.

- The service should not expose a function that creates and returns a subscription; it should only expose observable(s) that can be subscribed to if needed. (It already does in the form of getMSALItem, though it is not intuitive.) Creating the subscription within BroadcastService prevents the consumer from chaining their own operators -- including takeUntil, which is a great way to automatically unsubscribe.

- The messages are transitory and should probably be exposed using a hot observable, like Subject. Currently it uses BehaviorSubject, which is more appropriate for state. If you want to expose an observable of the current state of the user data (which I think would be handy!) then that would be a good case for BehaviorSubject.

Normally I would submit a pull request but I saw you have an outstanding PR for updating to a version of Angular that uses RxJS 6. That ought to be done first as it would change the code I'm talking about. If any of this sounds useful then I'm happy to submit something when the time comes.

Example service (just for messages):

```tscript
import { Injectable } from '@angular/core';
import { Subject } from 'rxjs';

export interface BroadcastMessage {
    type: string;
    payload: any;
}

@Injectable()
export class BroadcastService {

    private readonly _messages$ = new Subject<BroadcastMessage>();
    public readonly messages$ = this._messages$.asObservable();

    broadcast(type: string, payload: any) {
        this._messages$.next({type, payload});
    }
}
```

Example for consuming:

```tscript
private readonly _destroying$ = new Subject<void>();

// ...

ngOnInit() {

this.broadcastService.messages$
  .takeUntil(this._destroying$)
  .subscribe(msg => {
	const user = this.authService.getUser();
	this.loggedIn = (user != null);
  });

this.broadcastService.messages$
  .filter(msg => msg.type === 'msal:loginFailure')
  .takeUntil(this._destroying$)
  .subscribe(msg => {
	console.log("login failure " + JSON.stringify(msg.payload));
	this.loggedIn = false;
  });

this.broadcastService.messages$
  .filter(msg => msg.type === 'msal:loginSuccess')
  .takeUntil(this._destroying$)
  .subscribe(msg => {
	console.log("login success " + JSON.stringify(msg.payload));
	this.loggedIn = false;
  });
}

ngOnDestroy() {
  this._destroying$.next(null);
  this._destroying$.complete();
}
```

I realize this would be a breaking change. The earlier the better I suppose.

**Comment by jasonnutter** [comment]
@rellis-of-rhindleton This is great feedback, thanks for the explanation! 

This seems like a sensible change, especially if it makes for a more idiomatic Angular library. I would definitely be open to considering this change, and would love to see a PR to demonstrates a proposed changed. Feel free to create a PR off of `dev-angular-1.0-beta` (which I will be very soon).

Since we are still in pre-release phase for 1.0, we are open to making a breaking change like this now, as opposed to waiting for 2.0. Out of curiosity, is it possible to make this change in a backwards-compatible way (and make the `subscribe` function deprecated)? 

Thanks!

**Comment by rellis-of-rhindleton** [comment]
Idiomatic - that’s the word I was looking for, thank you. 

Backwards compatible just means not getting rid of the existing public members, right? I’ll write something up.

**Comment by jasonnutter** [comment]
@rellis-of-rhindleton Correct. If you are able to make it a non-breaking change, we can add it incrementally to the upcoming Angular release, instead of having to decide now between potentially delaying that release or waiting until v2.

**Comment by rellis-of-rhindleton** [comment]
Hey, so I'm not ignoring this, but I'm behind the curve on the tooling. Never dealt with a lerna project before. Are we supposed to be able to build msal-angular and have the updated code be usable by the sample projects, or am I misreading this? 

If you don't have time to point me in the right direction I understand -- but on the other hand I'll be happy to write up a cheat sheet, if I can get it going.

**Comment by jasonnutter** [comment]
@rellis-of-rhindleton After cloning the repo, run `npm install` in the root. This will first install lerna, then bootstrap all of the libraries and samples, which yes, will make it so that the samples will use the local versions of the library. If it doesn't appear that this is happening, `cd` back to the root folder and run `npx lerna bootstrap`.

**Comment by rellis-of-rhindleton** [comment]
@jasonnutter - Sorry I let this go; I could not get the project to build or any imports to recognize anything, and then life intervened, etc.  I'm still up for it, if anyone cares. But I've made a fresh fork and still having the same problems. I hate to bug you all with dumb questions but I don't want to submit a pull request if I can't get the project to build on my own machine.

It looks like lerna bootstrap works - no errors or warnings. But I'm getting errors in msal.service.ts.

```typescript
import {
    UserAgentApplication,
    Configuration,
    AuthenticationParameters,
    AuthResponse,
    AuthError,
    authResponseCallback,
    errorReceivedCallback,
    tokenReceivedCallback,
    UrlUtils
} from "msal";
```

Says _Cannot find module 'msal' or its corresponding type declarations_.

There must be some step I'm missing. Do I need to build a particular part of this project first?

**Comment by jasonnutter** [comment]
@rellis-of-rhindleton Run `npm run build` in the `msal-core` folder, I believe that should fix that error.

**Comment by rellis-of-rhindleton** [comment]
Thanks - ran it at the top level folder. Had to restart VS Code afterward.

________________________________

**Comment by rellis-of-rhindleton** [comment]
Broadcast message types are arbitrary strings with untyped payloads. Is there any desire to type these? Or is the full set of messages still undetermined?

**Comment by jasonnutter** [comment]
@rellis-of-rhindleton Apologies for the delay in responding, I missed your question. 

> Broadcast message types are arbitrary strings with untyped payloads. Is there any desire to type these? Or is the full set of messages still undetermined?

Yes, we would like to type these. Furthermore, we are considering adding an event API to the core MSAL library (#2056), as a consideration for both Angular and other frameworks such as React. Given that, any substantial changes to the current use of observables in MSAL Angular will be made in MSAL Angular v2. We are still interested in your perspective and feedback as we design and implented these improvements.

**Comment by rellis-of-rhindleton** [comment]
Sounds good. I've subscribed to that issue. Thanks.
