### ISSUE TITLE
How to autoRenew msal.idtoken before expiry

### ISSUE THREAD

**Issue by AbhaysinghBhosale** [AzureAD/microsoft-authentication-library-for-js#1246]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.2.1`

## Description
I have implemented the user login flow using the msal in SPA react application. Normal login flow is working fine(except sometime redirect loop). 

The issue is msal.idtoken is valid for 1 hour and we send this to out back-end API's. So API fails after 1 hour. How i can renew this token automatically 5 min before expiry.
I have set `tokenRenewalOffsetSeconds: 300` expecting it will renew token 5 min before expiry but it is not working as expected.

Following is my implementation

```
let redirectUri = 'https://'+document.domain+'/';
    const logger = new Msal.Logger(this.loggerCallback, {correlationId: '1234',level:Msal.LogLevel.Verbose, piiLoggingEnabled: false});

    const config = {
      auth: {
        clientId: process.env.REACT_APP_ClientID,
        redirectUri: redirectUri,
        postLogoutRedirectUri : redirectUri
      },
      cache: {
        cacheLocation: "localStorage",
        storeAuthStateInCookie: true
      },
      system: {
        logger: logger,
        tokenRenewalOffsetSeconds: 300
      }
    }
    this.loginRequest = {
      scopes: ["user.read"],
    }
    this.app = new Msal.UserAgentApplication(config);
    this.app.handleRedirectCallback((error,response) => {
    });
```

For login method is 
```
  login = () => {
    this.app.loginRedirect(this.loginRequest);
  };
```

**Comment by pkanher617** [comment]
@AbhaysinghBhosale in order to renew id tokens, you need to use acquireTokenSilent with the client-id of your application as the scope.

So before you send the token to your backend application, but after the initial login call, you can retrieve a valid token from MSAL by doing the following:
```javascript
const renewIdTokenRequest = {
     scopes; "<client-id>"
};

this.app.acquireTokenSilent(renewIdTokenRequest).then(response => {
     // send response.idToken to the backend
}).catch(error => {
     // if it is an InteractionRequired error, send the same request in an acquireToken call
     if (error instanceof InteractionRequiredAuthError) {
          this.app.acquireTokenRedirect(renewIdTokenRequest);
     }
});
```
acquireTokenSilent will perform the token renewal if the expiry time is within the tokenRenewalOffsetSeconds.

You can get the error types from the msal package. You can also check the errorCode field of the error object instead of using instanceof, which should be either "interaction_required", "login_required" or "consent_required" for an InteractionRequiredAuthError.

Please let me know if this helps.

**Comment by AbhaysinghBhosale** [comment]
Yes i know about acquireTokenSilent but should i explicitly call this method ?

i had created a function called acquireToken as below

```
acquireToken = () =>{
   this.app.acquireTokenSilent(this.accessTokenRequest).then(accessTokenResponse => {
          const accessToken = accessTokenResponse.accessToken;
   }, error => {
          return this.app.acquireTokenRedirect(this.accessTokenRequest).then(accessTokenResponse => {
              const accessToken = accessTokenResponse.accessToken;
          }, err => {
             console.error(err);
          });
    });
} 
```

after setting `tokenRenewalOffsetSeconds: 300` msal will automatically call this function was expected. OR i have to call this method explicitly 5 min before token expiry. I generate own token using msal.idtoken  once user logged in and renew it every hr if user is active. So msal.idtoken should be renewed before custom token renewed.

**Comment by pkanher617** [comment]
MSAL will not automatically call acquireTokenSilent. MSAL doesn't place any timeouts on the page to renew a token. The library will instead check the token **when it is retrieved**. 

Which means that you should be calling acquireTokenSilent **when you need the token**. If this function is called within the renewal offset (5 min before expiration), or after the expiration, we will renew the token automatically for you. If your session on the server is not valid, we will throw an InteractionRequiredAuthError which will force you to call an interactive API (login/acquireTokenRedirect).

You are correct, msal will update the localStorage msal.idtoken when it retrieves a new token. You can place a timer yourself to retrieve the token from the cache every hour, which will allow you to always have a fresh token.

The function signature you posted above should work for you.

**Comment by AbhaysinghBhosale** [comment]
I had created own logic to check msal expiry by following function 
```
 this.checkingInterval  =  setInterval(function(){
    if(msalToken !== null){
        if(new Date(jwt.decode(msalToken).exp * 1000) < new Date(Date.now() - (5 * 60000))){
          this.authService.acquireIdToken();
        }
      }
    }.bind(this), 60000);
```

and 

 ```
this.app.acquireTokenSilent(this.idTokenRequest).then(response => {
          //const idToken = response.idToken;
        }, error => {
          if (error.name === "InteractionRequiredAuthError") {
            return this.app.acquireTokenRedirect(this.idTokenRequest).then(response => {
              //const idToken = response.idToken;
            }, err => {
              console.error(err);
            });
          }
      });
```

So it call aquireTokenSilent when expiry is greater than current time-5 min. But the issue is that logger shows `Thu, 30 Jan 2020 07:20:34 GMT:1234-1.1.3-Info User login is required` and error in console is 

```
ClientAuthError: User login is required.
    at ClientAuthError.AuthError [as constructor] (http://localhost:3000/static/js/25.chunk.js:28944:24)
    at new ClientAuthError (http://localhost:3000/static/js/25.chunk.js:29075:24)
    at Function.ClientAuthError.createUserLoginRequiredError (http://localhost:3000/static/js/25.chunk.js:29145:12)
    at http://localhost:3000/static/js/25.chunk.js:27074:95
    at new Promise (<anonymous>)
    at UserAgentApplication.acquireTokenSilent (http://localhost:3000/static/js/25.chunk.js:27059:12)
    at UserAgentApplication.descriptor.value [as acquireTokenSilent] (http://localhost:3000/static/js/25.chunk.js:26656:33)
    at AuthService.acquireIdToken (http://localhost:3000/static/js/main.chunk.js:2765:18)
    at DefaultLayout.<anonymous> (http://localhost:3000/static/js/28.chunk.js:2151:28)
```

**Comment by tnorling** [comment]
You should not open and inspect access tokens. In order to make sure you always have a valid token you can call `acquireTokenSilent` at least once per hour. Or if you just want to maintain the session and make sure you can renew a token silently when you need it, call it at least once every 24 hours providing a `sid` or `loginHint`. Closing as there is no further action needed from msal, but let us know if you still have questions.
