### ISSUE TITLE
Differentiating between idToken acquired on sign in vs idToken acquired silently/renewed

### ISSUE THREAD

**Issue by NareshKumarM** [AzureAD/microsoft-authentication-library-for-js#1252]
## Library
- [x] `@azure/msal-angular@0.x.x` - 0.1.4

## Browser
- Chrome - Version 78.0.3904.108

## Description
Hi Team,

I am fairly new to the MSAL-Angular realm and I have this question of differentiating between idToken acquired on sign in vs idToken acquired silently/renewed. Are there any identifiers in the idTokens themselves that can indicate that the token acquired, is either a fresh one or a renewed one. Some internal operations in our app depend on the token types and we wish to know if there are any such indications in the idTokens themselves.

Upon some digging and debugging, when I subscribe to 'msal:loginSuccess' event, the payload shows tokenType:'id_token' which can be confirmed via the HTTP request containing response_type parameter set to id_token when signing in for the first time.
The same payload when token is renewed silently, the payload shows tokenType:'' but the HTTP request contains response_type parameter set to token.

What I was also curious to know about is are there events to subscribe to, similar to 'msal:loginSuccess' which i can use to identify whether the token was issued during sign in or renewed silently

Any info on this can be really helpful

**Comment by sameerag** [comment]
@NareshKumarM AFAIK `idTokens` are JWTs that do not contain the information whether they are invoked for the first time or renewed. When you request for a token, depending on your cache and the specific API call made (interactive vs silent) the library fetches the token either from the cache or from the network. There are use cases that may fetch the idToken from cache and not renew it.

The only way I can think of handling this is:
* Maintain the app state in the browser, which helps you check if you have ever logged in
* `msal js` cache state indicates the presence of idToken and when the library logs out all cache is erased; this information can be used to verify the authentications status by calling getAcccount()

Hope this helps.

**Comment by sameerag** [comment]
@jasonnutter Anything to add for `msal-angular`?

**Comment by jasonnutter** [comment]
In `msal@1` we have added a `fromCache` property to `AuthResponse`, which will indicate whether or not the token was returned from the cache or from the network. I'm not sure if that is exactly what you are looking forward, but it is the closest we have I believe.

This is available in the new version of MSAL Angular. Please follow the instructions here to upgrade: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev-angular-1.0-protectedresources/lib/msal-angular/docs/0.x-1.x-upgrade-guide.md

**Comment by NareshKumarM** [comment]
Hi @sameerag @jasonnutter Thabks for your inputs guys. I did manage to find out another easy way to identify a new token from renewed token 
The objectIdFromSession when exposed via custom policy in B2C, it will come up as false if it's a fresh token and will come up as true if it is a renewed token

**Comment by sameerag** [comment]
Thanks @NareshKumarM. Closing this ticket.
