### ISSUE TITLE
MSAL.JS SSO No Longer Works when Upgrading to 1.2

### ISSUE THREAD

**Issue by toddfsnyder** [AzureAD/microsoft-authentication-library-for-js#1253]
## Library
- `msal@1.2` 

## Framework
Angular 7 (SPA) Using MSAL.js library directly 

## Description
We have different applications configured to work with Azure B2C (Angular 7 and ASP.NET MVC 4.8). Previously when using msal.js 1.0.2 SSO was working when we logged into the ASP.NET MVC application than navigated to the Angular 7 application (see sample code below). After upgrading to 1.2 (or 1.2.1) SSO no longer works and calling UserAgentApplication getAccount() always returned NULL. 

We rolled back to msal 1.0.2 and SSO starts working again as expected - UserAgentApplication getAccount() is now returning a valid account. 

Is there something different that needs to be done for SSO with msal1.2? Note, when we navigate between applications we are loading the second app in another tab.

Sample Code Linking between ASP.NET MVC application and Angular Application.
<a href="https://localhost:6420/" target="_blank">Angular Test App</a>

## Security
Yes, Single Sign On (SSO)

## Regression
Yes, the behavior works in msal 1.0.2

## Configuration
Azure B2C Tenant 

```js

    var msalConfig: Msal.Configuration = {
      auth: {
        clientId: this.config.clientID,
        authority: this.authority,
        validateAuthority: false,
        redirectUri: window.location.origin,
        postLogoutRedirectUri: window.location.origin
      },
      cache: {
        cacheLocation: 'localStorage',
        storeAuthStateInCookie: true
      },
      system: {
        //logger: logger,
        loadFrameTimeout: 20000
      }
```

## Reproduction steps
1. Long into ASP.NET MVC Application
2. User Clicks on link to Angular application that has target="_blank"
3. Angular Application Loads in New Tab
4. Redirect to B2C happens to verify user is logged in
5. Redirect back to Angular Application, but the logged in user is not recognized 

## Expected behavior
SSO works across browser tabs

## Browsers
Is this issue browser-specific? If so, please detail which browsers are impacted (e.g. IE 11, Safari).
Chrome  78+, IE 11, Firefox 72+

**Comment by sameerag** [comment]
@toddfsnyder Any fiddler trace or logs that can help us? Also, did you try our angular branch [msal-angular](https://www.npmjs.com/package/@azure/msal-angular/v/1.0.0-beta.1)?

**Comment by sameerag** [comment]
@toddfsnyder Any update?

**Comment by toddfsnyder** [comment]
No, we are not using the msal-angular library, our application is already in production with no plans to migrate at this time. I will email the fiddler trace.

**Comment by quickstar** [comment]
Same issue here, it seems somehow related to a state check. The callstack might help:

`"AuthError@https://localhost:4200/vendor.js:123346:28
ClientAuthError@https://localhost:4200/vendor.js:123484:28
./node_modules/msal/lib-es6/error/ClientAuthError.js/ClientAuthError.createInvalidStateError@https://localhost:4200/vendor.js:123518:16
./node_modules/msal/lib-es6/UserAgentApplication.js/UserAgentApplication.prototype.saveTokenFromHash@https://localhost:4200/vendor.js:121936:97
./node_modules/msal/lib-es6/UserAgentApplication.js/UserAgentApplication.prototype.processCallBack@https://localhost:4200/vendor.js:121377:29
./node_modules/msal/lib-es6/UserAgentApplication.js/UserAgentApplication.prototype.handleRedirectCallback@https://localhost:4200/vendor.js:120730:18
MsalService/<@https://localhost:4200/main.js:1645:24
./node_modules/rxjs/_esm5/internal/Subscriber.js/SafeSubscriber.prototype.__tryOrUnsub@https://localhost:4200/vendor.js:128242:16
./node_modules/rxjs/_esm5/internal/Subscriber.js/SafeSubscriber.prototype.next@https://localhost:4200/vendor.js:128180:22
./node_modul…"
`

**Comment by tnorling** [comment]
@toddfsnyder @quickstar Is this still an issue in ```msal@1.3.0-beta.1```?

**Comment by tnorling** [comment]
Let us know if this is still an issue. Closing.
