### ISSUE TITLE
TypeError when acquiring token for scopes

### ISSUE THREAD

**Issue by ranjanmicrosoft** [AzureAD/microsoft-authentication-library-for-js#1254]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.2.1`
- [x] `@azure/msal-angular@1.0.0-beta.1`

## Description
Received the following error when trying to get token for graph API.

Error when acquiring token for scopes: user.read TypeError: Cannot read property 'extraQueryParameters' of null

## Regression

I haven't successfully used MSAL yet. 

## Configuration

        MsalModule.forRoot({
            auth: {
                clientId: this.config.clientId,
                authority: 'https://login.microsoftonline.com/' + this.config.tenantId,
                redirectUri: window.location.origin,
                validateAuthority : true,
                postLogoutRedirectUri: window.location.origin,
                navigateToLoginRequestUrl : true
            },
            cache: {
                cacheLocation : 'sessionStorage',
                storeAuthStateInCookie: false
            },
            system: {
                logger: new Logger(
                    // tslint:disable-next-line:no-console
                    (level: LogLevel, error: string) => { console.log('MSAL LOGGING: ' + level + ' ' + error); } , 
                    {
                        level: LogLevel.Verbose,
                        piiLoggingEnabled: false,
                        correlationId: '1234'
                    })
            },
            framework: {
                isAngular: true,
                protectedResourceMap: new Map([['https://graph.microsoft.com/v1.0/me', ['user.read']]])
            }
        }, {
            consentScopes: [ 'user.read', 'user_impersonation' ],
            extraQueryParameters: null,
            popUp: true // todo: configure redirect
        }),

## Expected behavior

Current behavior is as such from verbose logs: 
MSAL LOGGING: 3 Wed, 29 Jan 2020 18:03:54 GMT:1234-1.2.1-Verbose Url: https://graph.microsoft.com/v1.0/me/photo/$value maps to scopes: user.read
MSAL LOGGING: 3 Wed, 29 Jan 2020 18:03:54 GMT:1234-1.2.1-Verbose ADAL's idToken exists. Extracting login information from ADAL's idToken 
MSAL LOGGING: 0 Wed, 29 Jan 2020 18:03:54 GMT:1234-1.2.1-Error Error when acquiring token for scopes: user.read TypeError: Cannot read property 'extraQueryParameters' of null

I'd expect the token to be retrieved properly. I didn't have extraQueryParameters set at all in the config, but tried setting it to various values to see if it fixed the issue without success. also didn't have consent scopes set and have tried setting it to various things.

**Comment by jasonnutter** [comment]
This will be solved by addressing #1411, closing.
