### ISSUE TITLE
Support for SSR in msal.js

### ISSUE THREAD

**Issue by anderseide** [AzureAD/microsoft-authentication-library-for-js#1256]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Based on my own testing, and issue #914 and #608, Server Side Rendering support seems to be missing in msal.js.

SSR is becoming more popular these days, even with JavaScript/TypeScript based applications, so it would be really good if we could do that using msal.js. Currently passport-azure-ad is a possible library to use, but it would be nice to have a single library for all use cases.

According to documentation, MSAL SSR support exists for ASP.NET Core, ASP.NET, Java and Python. Javascript would be a good addition in 2020

**Comment by sameerag** [comment]
@hamiltonha to follow up internally if this feature is in the pipeline.

**Comment by sameerag** [comment]
`According to documentation, MSAL SSR support exists for ASP.NET Core, ASP.NET, Java and Python. Javascript would be a good addition in 2020`

@anderseide `msal-node` is in the pipeline and we are currently in the planning stages. This could potentially add this support for you. Please check our roadmap for the timelines, we will update it when we have a plan in place.

**Comment by sameerag** [comment]
Closing this to track with #1258.
