### ISSUE TITLE
After login access token is expired, MSAL interceptor acquire token for every request

### ISSUE THREAD

**Issue by emadalsous** [AzureAD/microsoft-authentication-library-for-js#1257]
Hello I am using MSAL with Angular. When i first login the website work correctly as expected. After a while, i think after the first token refreshing, MSAL interceptor start to make acquireTokenSilent for every request.

I checked the interceptor and i found that the following method is always returning null after the first acquired token expires and renewed:
const tokenStored = this.auth.getCachedTokenInternal(scopes);

This happens only on IE Edge and IE 11

Is there a workaround for Angular for this issue ?

Best regards,
Emad

**Comment by jasonnutter** [comment]
@emadalsous Can you please clarify which version of the library you are using? And in the future, please follow one of the Github issue templates, thanks!

**Comment by tnorling** [comment]
Closing due to no response. Feel free to reopen if this is still an issue.
