### ISSUE TITLE
Users can't logout in Chrome if they aren't on "/"

### ISSUE THREAD

**Issue by asanchezfe** [AzureAD/microsoft-authentication-library-for-js#1262]
## Library
- [ ] `msal@1.2.2-beta.0`
- [ ] `@azure/msal-angular@1.0.0-beta.2`

## Framework
Angular 8.2.14

## Description
User is on `http://localhost:4200/projects` (our index main page) clicks on logout and he sees the select account to logout MS screen. Ok this is correct.

Users navigates to `http://localhost:4200/project/3/summary` clicks on logout and he is redirected to `http://localhost:4200/#id_token=ey....` and later to  `http://localhost:4200/project/3/summary`  again and it keeps loged in.

In Firefox it works correctly.

## Configuration
```js
export function MSALConfigFactory(/*config: ConfigService*/) {
  return {
    auth: {
      clientId: 'MY_CLIENT_ID_KEY',
      authority: 'https://login.microsoftonline.com/MY_TENANT',
      validateAuthority: true,
      redirectUri: 'http://localhost:4200',
      postLogoutRedirectUri: 'http://localhost:4200',
      navigateToLoginRequestUrl: true
    },
    cache: {
      cacheLocation: 'localStorage',
      storeAuthStateInCookie: false
    },
    framework: {
      unprotectedResources: [],
      protectedResourceMap: new Map([['//myapimanager.com', ['api://MY_CLIENT_ID_KEY/user_impersonation']]])
    }
  };
}

export function MSALConfigAngularFactory(config: ConfigService) {
  return {
    popUp: false,
    consentScopes: ['api://MY_CLIENT_ID_KEY/user_impersonation'],
    extraQueryParameters: {}
  };
}
```

## Logger outputs
Mon, 03 Feb 2020 16:39:34 GMT:1234-1.2.2-Verbose location change event from old url to new url
 Mon, 03 Feb 2020 16:39:34 GMT:1234-1.2.2-Info Navigate to:https://login.microsoftonline.com/_tenant_/oauth2/v2.0/logout?post_logout_redirect_uri=http%3A%2F%2Flocalhost%3A4200
 Mon, 03 Feb 2020 16:39:34 GMT:1234-1.2.2-Info Navigate to:https://login.microsoftonline.com/_tenant_/oauth2/v2.0/authorize?response_type=id_token&scope=user.read%20openid%20profile%20api%3A%2F%2Fcustomscope%2Fuser_impersonation&client_id=ourclientID&redirect_uri=http%3A%2F%2Flocalhost%3A4200&state=HIDDEN&nonce=HIDDEN&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=1.2.2&client-request-id=HIDDEN&response_mode=fragment
Navigated to http://localhost:4200/
 Mon, 03 Feb 2020 16:39:38 GMT:1234-1.2.2-Info Returned from redirect url
 Mon, 03 Feb 2020 16:39:38 GMT:1234-1.2.2-Verbose Url: /mvs/api/staticData maps to scopes: c9e73de6-71bf-4ece-950d-2ae9848ccbcc
Mon, 03 Feb 2020 16:39:38 GMT:1234-1.2.2-Info User login is required
 Mon, 03 Feb 2020 16:39:38 GMT:1234-1.2.2-Info Processing the callback from redirect response
 Mon, 03 Feb 2020 16:39:38 GMT:1234-1.2.2-Info State status:true; Request type:LOGIN
 Mon, 03 Feb 2020 16:39:38 GMT:1234-1.2.2-Info State is right
 Mon, 03 Feb 2020 16:39:38 GMT:1234-1.2.2-Info Fragment has id token

## Expected behavior
User is loged out.

## Browsers
Chrome.

**Comment by DarylThayil** [comment]
Can you confirm the version of the Angular lib you are on?

**Comment by DarylThayil** [comment]
@jasonnutter  can you take a look at this?

**Comment by jasonnutter** [comment]
@asanchezfe I'm confused, can you clarify this?

> clicks on logout and he is redirected to `http://localhost:4200/#id_token=ey....`

If you a user is redirected to a page with a hash such as `#id_token` that would indicate that login was initiated, not logout.

**Comment by asanchezfe** [comment]
@jasonnutter yeah, the logout button executes the MsalService logout() method, however it seems that in Chrome the users re-login.
I'm investigating but seems that the user is redirected to '/' and it is a MsalGuard route guarded so it ask for a login again? The strange thing is that only happens on Chrome. We are using a custom guard that nest inside the MsalGuard, checking also if this affects in some mode. I keep investigating.

**Comment by asanchezfe** [comment]
Sorry, after investigating, I saw that the button of logout had a router link not necessary (is a big app reusing code...)
`<button (click)="logout()" routerLink="/login"">`
This was causing the user be redirected to main page (cause /login doesn't exist) that was MsalGuarded and for any reason it re-logs the user.
