### ISSUE TITLE
Preview Version With B2C?

### ISSUE THREAD

**Issue by Taats** [AzureAD/microsoft-authentication-library-for-js#1264]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [X ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Hey team, i've been trying out the new version as requested by @jasonnutter and so i am upgrading from an other client ('oidc-client', which can login/logout etc) but i can not get this new version to work with our Azure B2C.

The flow that i want to implement is the **Authentication Code Flow for Azure B2C**.

I have registered the callback required for msalService.handleRedirectCallback and i have subscribed to the broadcastService.

I also have registered the library in app.module.ts with the following configuration:

> MsalModule.forRoot({

            auth: {
                clientId: 'XXXXXXX-XXXXXXXX',
                authority: "https://my-site.b2clogin.com/tfp/my-site.onmicrosoft.com/B2C_1_signupsignin1",
                validateAuthority: true,
                redirectUri: "https://localhost:5001/oidc-signin",
                postLogoutRedirectUri: "https://localhost:5001/",
                navigateToLoginRequestUrl: true,
            },
            cache: {
                cacheLocation: "localStorage",
                storeAuthStateInCookie: false, // set to true for IE 11
            },
            framework: {
              unprotectedResources: ["https://www.microsoft.com/en-us/"],
            //  protectedResourceMap: new Map(protectedResourceMap)
            },
        },
        {
            popUp: true, // !isIE
            consentScopes: [
                "openid", "https://my-site/read"
            ],
            extraQueryParameters: {}
        }),

When i then execute the .login()  a pop-up is opened and closed instantly and the error is see in the browser console is: **Uncaught (in promise): ClientAuthError: Error: could not resolve endpoints. Please check network and try again.**
Ofcourse i have a working network but what i dont see is any calls in the network-monitor. 

Any advice please or maybe a working example? (i could only find the implicite flow)

**Comment by jasonnutter** [comment]
@Taats Unfortunately, B2C does not yet support the Auth Code Flow. cc @pkanher617 who can provide more context.

**Comment by DarylThayil** [comment]
@Taats  Auth code flow is in an alpha in our core library and support for it in Angular would probably not be ready till next quarter at the earliest.

**Comment by Taats** [comment]
@DarylThayil Thanks for the heads up, guess ill have to look elsewhere then (for now : )
