### ISSUE TITLE
APPLE ID LOGIN acquireTokenSilent X-Frame-Options DENY ERROR

### ISSUE THREAD

**Issue by Gevornairi** [AzureAD/microsoft-authentication-library-for-js#1266]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- msal Javascript Library: 1.2.1

## Framework
If you are using a framework, please provide the framework and version (e.g. Angular v8, React v16, etc).

## Description
User navigates to Azure AD B2C Authentication page, selects Apple to login then IdToken is coming back but when we call acquireTokenSilent function it throws **Refused to display https://appleid.apple.com/auth/authorize? client_id={clientID}&redirect_uri={redirectUri}&response_type=code&scope=email&response_mode=form_post&nonce={nonce}&state={state} in a frame because it set X-Frame-Options to Deny**

## Security
Is this issue security related? with higher probability yes

## Regression
Did this behavior work before? NO

## Configuration
Please provide your MSAL configuration options.
{
 clientId: 'clientId',
authority: 'authority',
validateAuthority: false
},
cache: {
cacheLocation: 'localStorage',
storeAuthInCookie: true
}

**Comment by jasonnutter** [comment]
@Gevornairi If you have a b2c policy that requires interaction, it is currently expected that you will receive this error from `acquireTokenSilent`. A workaround is to call `acquireTokenPopup` or `acquireTokenRedirect`.

**Comment by Gevornairi** [comment]
Thanks for the comment, 

Multiple things.

1. In the policy I have also another provider(spotify) which works fine, why apple not working fine?
2. Then through MSAL how I can get and IDToken and Access Token together?
3. acquireTokenPopup, acquireTokenRedirect will refresh the page how I can do silently?

**Comment by jasonnutter** [comment]
@Gevornairi 

1. I'm guessing that Spotify is okay with its page being rendered in an iframe, while Apple is not. 
2. Currently we don't allow users to indicate that they need both tokens in a single call, as that is considered an implementation detail of the library. Can you explain why you want both in one call?
3. There is no way to perform these requests silently other than `acquireTokenSilent`. I don't believe `acquireTokenPopup` should refresh the page.
4. There may not be a lot we can do, given the restriction of preventing Apple's website from being rendered in an iframe is done by Apple, not us (this usually done for security purposes to prevent click-jacking).

cc: @sameerag @pkanher617

**Comment by Gevornairi** [comment]
Thanks Jason,

Regards,

**Comment by sameerag** [comment]
Closing this as this is expected behavior for B2C endpoints when interaction is required.
