### ISSUE TITLE
acquireTokenSilent iframe issue with B2C and federation to AAD common endpoint

### ISSUE THREAD

**Issue by alex-mason-by** [AzureAD/microsoft-authentication-library-for-js#1269]
## Library
- [msal@1.2.1 ]

## Framework
React 16

## Description
A previous fix resolved issue [1165](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1165) but remains an issue for B2C federations to the common AAD endpoint
 
## Security
Is this issue security related? No

## Regression
Did this behavior work before? Not clear

## Configuration
Configure common AAD tenant endpoint as well specific AAD tenant federation in B2C

## Reproduction steps
1. Test using specific AAD tenant federation (works fine and previous fix resolved iframe issues on this case)
2. Test using common AAD tenant endpoint with the same tenant as step one and observe below sanitized error when retrieving token for resource after login

Refused to display 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=xxx&redirect_uri=xxx&response_type=code&scope=openid+profile+email&response_mode=form_post&nonce=xxx&state=xxx' in a frame because it set 'X-Frame-Options' to 'deny'.

## Expected behavior
Should work exactly the same

## Browsers
Is this issue browser-specific? No

**Comment by JasSuri** [comment]
This problem is likely different. 
More likely that at the common endpoint you have multiple accounts available to login into. Due to the ambiguity, AAD will offer a form to choose an account, and that will trigger the x frame options deny. Check in a non SSO/silent token flow to see if you are seeing the account selection screen.

The only way I think to solve this is to pass the login hint along with the silent token request.

**Comment by sameerag** [comment]
I agree with @JasSuri (Thank you). @alex-mason-jdas did you happen to test this in interactive flow?

**Comment by alex-mason-jdas** [comment]
It happened after the initial login and when getting an access token. I think that this is the acquireTokenSilent flow of the library.

**Comment by sameerag** [comment]
Can you pass `login_hint` and see if that helps? This could use a better user experience from us but the changes needed should be agreed upon by both the `B2C service` and `msal js`. 

cc @ktsakas any ideas?

**Comment by JasSuri** [comment]
As part of the silent token msal call, you will have the ‘extraQueryParameters’ overload. Use that to pass in ‘login_hint=“email address”’

**Comment by sameerag** [comment]
Can you please use the parameter: `login_hint` which is supported? We suggest that as we ignore hints sent in `extraQueryParameters`.

**Comment by alex-mason-jdas** [comment]
At this point, I have moved away from the common endpoint

**Comment by JasSuri** [comment]
You can still have this issue if there are two accounts logged in at some point to the same tenant. I would recommend adding loginhint for the most robust solution.

**Comment by gabriel-kohen-jdas** [comment]
What would be the way to get the preferred_login to populate such login_hint?

**Comment by alex-mason-jdas** [comment]
It seems like subject id is the right thing that should determine silent token behavior but that wouldn't line up with login_hint. We have the possibility that the same federated identity resolves to different b2c identities.

**Comment by JasSuri** [comment]
Each federated identity will come back with an objectId or Identifier, which is then transformed into a AlternativeSecurityId. That transformation always returns the same output as long as the Identifier is the same. Therefore sending the login hint as well as the domain hint would still satisfy this issue.

**Comment by JasSuri** [comment]
@gabriel-kohen-jdas you can extract the preferred_login from the Azure AD token as part of the OutputClaims within your AAD OIDC Technical Profile and issue that into the AAD B2C token as a claim name of your choice. Then on subsequent silent calls, use the claim value as the login hint in the new request.

**Comment by alex-mason-jdas** [comment]
Totally agree with login_hint + domain_hint but unfortunately I believe that MSAL.js is going to merge a PR that basically ignores domain_hint on silent calls so isn't there still an issue here?

https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/1299

**Comment by JasSuri** [comment]
Not really to be fair, since in a silent token call, we already know which IdP to send the request to due to the cookies present.

**Comment by CodyMorris** [comment]
Can login_hint currently be used when using the AngularJS wrapper?

**Comment by Zucka** [comment]
It seems thet I might be facing the same underlying issue.

Every bit of ducomentation about AAD B2C is saying it does not allow the B2C login site to be loaded in an iframe. How does that impact MSAL when MSAL is trying to get token updates through iframes?

**Comment by JasSuri** [comment]
You cannot do an interactive login within an iframe, but silent tokens can be obtained within an iframe as long as there are no HTTP 200's occurring, only 302 redirects. So that is not the underlying issue.

**Comment by philip-young** [comment]
Hi, I am using the B2C Azure AD Multi-Tenant Custom Policy found [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/identity-provider-azure-ad-multi-tenant-custom?tabs=applications). I have also been experiencing this issue. I provided the login_hint, which now skips the account selection screen, but was still getting an x-frame error. After reviewing the Azure AD login audits, I found that there is a "keep me signed in" interaction coming up after the login_hint is supplied that is causing this issue. After doing some research on how to disable this screen, I found this [previous issue](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/982/commits/1b71462eff480d29e937740436f11824440d2cf3) that was raised which allows you to skip the flow by providing the 'x-client-Ver=' and the current MSAL version to the common endpoint (which works). 

I'm just wondering if this is the issue everyone else is facing and also if this is a valid way of doing this (I can't find any other documentation on how to disable this functionality for the common endpoint).

**Comment by CodyMorris** [comment]
I ended up solving my issue by properly configuring my session provider.

Before, I was using the `SamlSSOProvider` as my connection with the idp was over SAML.  Switching to the `DefaultSSOSessionProvider` caused my session to be properly maintained, which avoided the `X-Frame-Options` error.  Hope this helps someone, was quite a pain to figure out.

**Comment by tnorling** [comment]
Closing as the original question has been answered. Let us know if this is still an issue.
