### ISSUE TITLE
Add .npmignore to avoid publishing unnecessary files to the registry

### ISSUE THREAD

**Issue by unindented** [AzureAD/microsoft-authentication-library-for-js#1270]
## Library
- [x] `msal@1.2.1`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Right now you're publishing a lot of unnecessary stuff (config, tests, etc.) to the npm registry:

<img width="335" alt="Screen Shot 2020-02-06 at 4 09 06 PM" src="https://user-images.githubusercontent.com/69485/73989648-5f3c4d00-48fb-11ea-8617-a86d0d5993dd.png">

You can use [`.npmignore`](https://docs.npmjs.com/using-npm/developers.html#keeping-files-out-of-your-package) to avoid that.

**Comment by jasonnutter** [comment]
Good call, been meaning to do this.

**Comment by jasonnutter** [comment]
This has been added, closing.
