### ISSUE TITLE
msal-node error handling

### ISSUE THREAD

**Issue by sameerag** [AzureAD/microsoft-authentication-library-for-js#1272]
## Upcoming Library
- [x] `@azure/msal-node@1.x`

## Description
Error module for `msal-node`
- Design and code error interfaces/implementation for node
- classify to be flexible to contain all flows
- introduce numeric codes and documentation(a webpage) for the developer to look up
- OAuth compliance (@sameerag to specify the details in this ticket soon)
- Compatible with `msal-browser`

## Priority
Alpha branch by March end (Current Quarter - Q3)

## Acceptance Criteria
- Unit tests
- Dev samples test against popular error types - Server or otherwise
- Documentation on error types in the library (`msal-node`)

**Comment by jasonnutter** [comment]
@sameerag Can this be closed?

**Comment by sameerag** [comment]
Will address the documentation gaps on this and close it. Picking this activity soon.

**Comment by sameerag** [comment]
Node does not need a new error class so far, after careful analysis, closing this issue. @pkanher617 If we decide to pick up error codes, let us do it for all libraries including `msal-common` as a separate effort.
