### ISSUE TITLE
MSAL Angular: Popups in Facebook mobile browser

### ISSUE THREAD

**Issue by engbibi** [AzureAD/microsoft-authentication-library-for-js#1284]
## Library
- [ ] `@azure/msal-angular@1.0.0-beta2

## Framework
Angular V9

## Description
I have a SPA with MSAL B2C authentication. Everything works fine in desktop and mobile browsers: Chrome, Firefox and Safari. However, in Facebook internal browser my app does not seems to receive any event from auth window. The second window opens, user sign in successfully, redirects fine, window closes and nothing. No success, nor failure.

## Configuration
I'm using popup method and localstorage.

**Comment by jasonnutter** [comment]
@engbibi When you say Facebook internal browser, you are referring to the browser that comes up when you click a facebook link from the facebook app? From what I've read we might have trouble supporting popups, given the limitation on the in-app browser. As a workaround, have you tried using the redirect methods instead?

**Comment by engbibi** [comment]
@jasonnutter I did some remote de debugging with Chrome on an Android device. It seems that on Android, Facebook is using webviews to open links and popups are restricted. I believe that on iOS we have a similar situation.
Redirect flow works as expected, so we should implement checks if browser have popups restricted.

**Comment by jasonnutter** [comment]
@engbibi Thanks for the update. For now, I don't think we'll be implementing any checks in the library for this, as we intentionally any business logic like this up to consuming applications. Closing, as no further actions items at this time. Thanks!
