### ISSUE TITLE
createBlockTokenRequestsInHiddenIframeError

### ISSUE THREAD

**Issue by mbrevda** [AzureAD/microsoft-authentication-library-for-js#1285]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.2.1` 

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
- React

## Description
exception `createBlockTokenRequestsInHiddenIframeError` is thrown after `loginPopup`. Possibly related, the iFrame is never removed, causing our app to run twice (and cause issues). It should be noted that if dev tools are closed (i.e. exceptions remain uncaught) the auth succeeds

## Regression
not sure

## Configuration
Please provide your MSAL configuration options.

```js
const loginRequest = {
  scopes: ['user.read'],
  state: /* custom state here */
}
```

## Reproduction steps
1. Login via popup
2. exception is thrown
3. iframe is never removed from page

## Expected behavior
no exception and no lingering iframe

## Browsers
Is this issue browser-specific? If so, please detail which browsers are impacted (e.g. IE 11, Safari).

**Comment by mbrevda** [comment]
I've updated my code to point to a dummy redirectUrl preventing the issue above. The iframe still stays in the dom. Is this the intended behavior?

**Comment by sameerag** [comment]
@mbrevda  `createBlockTokenRequestsInHiddenIframeError` is just an informative message that for folks who are reloading their home page (which could in turn have another `acquireToken*` call in theory that we do not execute those requests in a hidden iframe. The recommendation to redirect to a blank page is to avoid this behavior and to save some cycles consumed by the app reloading.

On a successful response we tear down the iframe we create, but if there is a failure or a timeout, you may see a frame in the dom.

Are you seeing the frame alive after your response is handled by the app?

**Comment by mbrevda** [comment]
Yes. The first time the page loads the iframe seems to persist for the
duration of the session. After a reload, it doesn't stick around. This
doesn't bother me per se (it's hidden after all) I just found it strange.

**Comment by mbrevda** [comment]
update: while the iframe still lingers at times, auth & tokens are now working after https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1222#issuecomment-587717744

**Comment by jasonnutter** [comment]
@mbrevda The iframe not getting removed is not necessarily a problem, are you seeing any other problematic behavior?
