### ISSUE TITLE
SCP is missing in access token claims

### ISSUE THREAD

**Issue by vaibhav915** [AzureAD/microsoft-authentication-library-for-js#1286]
Unable to get SCP="access_as_user" in access token claims. I want an access token of OAuth v2.0 that returns SCP="access_as_user" in the claims.

## Library
- [ ] `@azure/msal-angular`: `^1.0.0-beta.2`
- [ ] `msal`: `^1.2.2-beta.0`

## Description
I am trying to get SCP claim from the access token using msal-angular 1.0.0 beta version in my SPA application. Please refer below steps:

1. Define MsalModule.forRoot({}), with all the information and consentScopes as 'api://xxxxxxx-xxxxxxx-xxxxxxxx-xxxxxxxx/access_as_user'. (exposed in Azure portal for API app) 
2. Call this.authService.loginRedirect() method to get id_token.
3. In the success callback of login redirect, I called below method to get access token this.authService.acquireTokenSilent(accessTokenRequest); 

But 'acquireTokenSilent' doesn't return OAuth 2.0 token rather it return either same id_token or v1.0 access token, which is not useful for me to get SCP in the claims

Thanks

**Comment by sameerag** [comment]
@vaibhav915 Your token depends on the scopes requested/permitted for your app and the authority that grants the token to those scopes. `access_as_user` used to be a default scope provided by the app portal registration experience but the new UI requires one to explicitly add this as a supported scope now.

From what I gather, the request above does not request this scope explicitly and hence you do not see it in the token. Can you please add it in the `scopes` part of the request and verify? I tested this and it works in a sample app for me.

Also we recommend not to open `access_tokens` in your application as a good practice.

**Comment by vaibhav915** [comment]
@sameerag 
Thanks for the quick reply.
Yes, after adding explicitly I have scp in my access token.

> Also we recommend not to open access_tokens in your application as a good practice.

Can you please elaborate this point, I didn't get you.

Thanks
Vaibhav

**Comment by jasonnutter** [comment]
@vaibhav915 Generally speaking, we do not recommend decoding access tokens (especially tokens for resources you do not control, e.g. Microsoft Graph), as they should be treated as opaque strings. If you need to validate an access tokens for your own resource, we recommend to use one of our middleware libraries.

Closing, as the original issue is resolved.

**Comment by jwahr** [comment]
@vaibhav915 Can you explain or show how you resolved this? I am having the same issue.

**Comment by vaibhav915** [comment]
> @vaibhav915 Can you explain or show how you resolved this? I am having the same issue.

As per Microsoft documentation, you need to integrate msal-angular for SPA.
Firstly, user need to authentication in Microsoft AD account using 'loginRedirect', once user gets authentication, you will receive token_id, use this to call 'acquireTokenSuccess' in the same msal object with defined scope, this time you will receive access token in the response callback.

**Comment by jwahr** [comment]
@vaibhav915 I believe that is what I am doing. I am getting a token_id back but when I check the token, it doesn't include scopes or roles. Does it matter what the source of my user? Either Azure Active Directory or Windows Server AD?

**Comment by jasonnutter** [comment]
> @vaibhav915 I believe that is what I am doing. I am getting a token_id back but when I check the token, it doesn't include scopes or roles. Does it matter what the source of my user? Either Azure Active Directory or Windows Server AD?

ID tokens do not have scopes, as scopes are present on access tokens as the `scp` claim. If you need roles, I recommend updating to MSAL.js v2 (as roles are not usually returned in the Implicit Flow), and then enabling the `wids` claim.

- MSAL.js v2: #1000 
- `wids` claim info: https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens#payload-claims
- groupMembershipClaim: https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-app-manifest#groupmembershipclaims-attribute

**Comment by jwahr** [comment]
Hey @jasonnutter 

So now I understand what you are saying I need scopes, I don't need roles because I am using implicit grant flow. I have my accessToken returning when I sign in but when I go to jwt.ms and decode the token, I don't have `scp`. In my `consentScopes` I have `openid, profile and api://{client_id}/access_as_user` being sent.

I don't know what I am missing to get `scp` to show up in my accessToken?

![image](https://user-images.githubusercontent.com/541820/85054567-7ae11b00-b159-11ea-8f0b-c4934cbbd4ed.png)

**Comment by jwahr** [comment]
@jasonnutter this is the sample I am going by https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/angular9-sample-app

**Comment by vaibhav915** [comment]
@jwahr Did you setup the scopes in the Azure App registration and grant permission to your angular app in the same app registration.

**Comment by jwahr** [comment]
@vaibhav915 My Azure API, I exposed the API and created a scope and on the Azure UI/Client I added a permission of that scope from the API `access_as_user`

**Comment by jasonnutter** [comment]
> Hey @jasonnutter
> 
> So now I understand what you are saying I need scopes, I don't need roles because I am using implicit grant flow. I have my accessToken returning when I sign in but when I go to jwt.ms and decode the token, I don't have `scp`. In my `consentScopes` I have `openid, profile and api://{client_id}/access_as_user` being sent.
> 
> I don't know what I am missing to get `scp` to show up in my accessToken?
> 
> ![image](https://user-images.githubusercontent.com/541820/85054567-7ae11b00-b159-11ea-8f0b-c4934cbbd4ed.png)

What's the value of the `tokenType` property of the response where you get that token? `id_token` or `access_token`?

**Comment by jwahr** [comment]
@jasonnutter I was able to get the correct access token after login. On the broadcast call `msal:loginSuccess`, I put in the following code below. I verified the token on jwt.ms and I am seeing the `scp` > `access_as_user` and was able to verify the token on the API.

https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-protected-web-api-verification-scope-app-roles#verify-scopes-in-apis-called-on-behalf-of-users

**CLIENT**
```
      const tokenRequest = {
        scopes: [environment.resources.api.resourceScope]
      };

      this.authService.acquireTokenSilent(tokenRequest);
```

I am now running into an issue with `VerifyUserHasAnyAcceptedScope` not finding the `scp` but after dropping the method into my code and making some modifications, I was able to verify the scope. This is another issue I need to figure out 😄 

**API**
```
private void VerifyUserHasAnyAcceptedScope(params string[] acceptedScopes)
        {
            if (acceptedScopes == null)
            {
                throw new ArgumentNullException(nameof(acceptedScopes));
            }
            var context = HttpContext;
            Claim scopeClaim = context?.User?.FindFirst("scp");
            if (scopeClaim == null || !scopeClaim.Value.Split(' ').Intersect(acceptedScopes).Any())
            {
                context.Response.StatusCode = (int)HttpStatusCode.Unauthorized;
                string message = $"The 'scope' claim does not contain scopes '{string.Join(",", acceptedScopes)}' or was not found";
                throw new HttpRequestException(message);
            }
        }
```
