### ISSUE TITLE
Issues on Mac - Login flickering screen with issue in url 'error=login_required&error_description=Silent+authentication+was+denied.+The+user+must+first+sign+in+and+if...

### ISSUE THREAD

**Issue by AbhaysinghBhosale** [AzureAD/microsoft-authentication-library-for-js#1287]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.1.3`

## Framework
React v16.5

## Description
Once user tries to login to the application screen is flickering for some time. This behavior started recently. In the URL i can see the issue as follows.

https://myexample.com/#/error=login_required&error_description=Silent+authentication+was+denied.+The+user+must+first+sign+in+and+if. 

## Security
Is this issue security related?

## Regression
No

## Configuration
Please provide your MSAL configuration options.
```
const config = {
      auth: {
        clientId: 'ClientID',
        redirectUri: redirectUri,
        postLogoutRedirectUri : redirectUri
      },
      cache: {
        cacheLocation: "localStorage",
        storeAuthStateInCookie: true
      },
      system: {
        logger: logger,
        tokenRenewalOffsetSeconds: 300
      }
    }
    
    this.loginRequest = {
      scopes: ["user.read"],
    }
    this.idTokenRequest = {
      scopes: [ClientID]
    }
```

```
this.app = new Msal.UserAgentApplication(config);

//login 
this.app.loginRedirect(this.loginRequest);
```

## Expected behavior
User should be able to login without redirect and screen flickering

## Browsers
Chrome, Safari.

**Comment by jasonnutter** [comment]
@AbhaysinghBhosale Can you clarify what you mean by "flickering"? Is your app going in a login loop (i.e. redirecting to the login page, back to your app, back to the login screen, etc).

Do you have third-party cookies disabled?

**Comment by AbhaysinghBhosale** [comment]
The issue is once page redirected back from microsoft.login website it land on dashboard, but this occurs multiple times without redirecting to Microsoft domain. Yes app is going in login loop and login  callback get called multiple times. But user just see flickering on screen instead redirecting to microsoft.login . In local storage i can see multiple login request, states,interaction inProgress.

Also app.login getting called twice some times.

**Comment by jasonnutter** [comment]
@AbhaysinghBhosale I see. Can you confirm whether or not third-party cookies are disabled? It is a known issue that disabling third-party cookies (e.g. via Safari ITP) will cause a login loop.

**Comment by AbhaysinghBhosale** [comment]
@jasonnutter no there is not configuration for disabling third party cookies.

**Comment by jasonnutter** [comment]
@AbhaysinghBhosale I'm referring to the third-party cookie options on the browser.

Safari: https://support.apple.com/guide/safari/manage-cookies-and-website-data-sfri11471/mac
Chrome: https://support.google.com/chrome/answer/95647?co=GENIE.Platform%3DDesktop&hl=en

The behavior you describe is the behavior we expect to see when third-party cookies are disabled in the browser. The error you mention would be the expected error when making an `acquireTokenSilent` call in this scenario.

**Comment by AbhaysinghBhosale** [comment]
No, i have not disabled third party cookies, also one of application user received this issue and dont know cookies were disabled or not.

But this issue is reported at the time of login and i call `acquireTokenSilent `method after 1 hr of login. So if its issue with `acquireTokenSilent `they it should occur while renewing token instead the time of login.

**Comment by zsid** [comment]
I have raised a similar bug to `https://github.com/syncweek-react-aad/react-aad/issues/211` which I think it might be a `msal` issue.

My case is when I have Dev and QA env and user credentials that can log into one and not the other. So for example:
1. I log into Dev
2. Navigate to QA env now
3. Stuck in a redirect loop and I have error in the url. I think it is not checking that the first attempt failed and trying to authenticate again.

**Comment by zsid** [comment]
This is the error I get in the url

`
http://localhost:3000/login#error=interaction_required&error_description=AADSTS50105%3a+The+signed+in+user+%27%7bEmailHidden%7d%27+is+not+assigned+to+a+role+for+the+application
`

**Comment by jasonnutter** [comment]
@AbhaysinghBhosale @zsid Can you both provide a Fiddler trace for the behavior you are seeing? Thanks!

**Comment by zsid** [comment]
@jasonnutter  - this is what i get in fiddler

```
HTTP/1.1 302 Found
Cache-Control: no-cache, no-store
Pragma: no-cache
Content-Type: text/html; charset=utf-8
Content-Encoding: gzip
Expires: -1
Location: http://localhost:3000/login#error=interaction_required&error_description=AADSTS50105%3a+The+signed+in+user+%27%7bEmailHidden%7d%27+is+not+assigned+to+a+role+for+the+application+%27client_id%27(Dev).%0d%0aTrace+ID%3a+907851ba-1776-4656-84a5-d1a0ded73200%0d%0aCorrelation+ID%3a+6c248312-887b-4f85-857a-26ff84015351%0d%0aTimestamp%3a+2020-02-27+17%3a26%3a46Z&error_uri=https%3a%2f%2flogin.microsoftonline.com%2ferror%3fcode%3d50105&state=e583211c-3b4a-4dea-a17d-6dafefb10f0e
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
x-ms-request-id: 907851ba-1776-4656-84a5-d1a0ded73200
x-ms-ests-server: 2.1.10104.13 - DUB2 ProdSlices
x-ms-clitelem: 1,50105,0,,
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
Set-Cookie: buid=AQABAAEAAABeAFzDwllzTYGDLh_qYbH8jAIpI4seyTdPNdf9XqzCIutd_bzjPVyYW3o6JJQ-ioKEP9y4vy14BDx9GYOhdE4T-bIBNc8-9HDrVP1WtLCjIEzyAtEb8oyoLZPHp_uzJYcBhUd8WOqawFiiHqC58h3nucxyZlYbdo2BOGZQpgaD1qt6Zzu0NnGkMxk5u4BIHpogAA; expires=Sat, 28-Mar-2020 17:26:46 GMT; path=/; secure; HttpOnly; SameSite=None
Set-Cookie: fpc=AubIJxEQeW1KiXCt5-6XmnHBhmevAQAAAKjw6dUOAAAAE7C--A4AAADE8unVDgAAAA; expires=Sat, 28-Mar-2020 17:26:46 GMT; path=/; secure; HttpOnly; SameSite=None
Referrer-Policy: strict-origin-when-cross-origin
Set-Cookie: x-ms-gateway-slice=prod; path=/; SameSite=None; secure; HttpOnly
Set-Cookie: stsservicecookie=ests; path=/; secure; HttpOnly; SameSite=None
Date: Thu, 27 Feb 2020 17:26:46 GMT
Content-Length: 457
```

**Comment by jasonnutter** [comment]
@zsid That particular error needs to be resolved an admin: https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/application-sign-in-problem-federated-sso-gallery#user-not-assigned-a-role

Have you gone through those steps?

**Comment by jasonnutter** [comment]
@AbhaysinghBhosale I think I'm confused about what is going on. The error you mention (`error=login_required&error_description=Silent+authentication+was+denied.+The+user+must+first+sign+in+and+if.`) is one that would be sent when calling `acquireTokenSilent`, which you say is being done one hour after login?

1. Call `loginRedirect`
2. Wait one hour, call `acquireTokenSilent`
3. Receive the `login_required` error

Is that correct? If not, can you please explain step-by-step what is happening?

And note, that generally speaking, if you receive an error for `login_required` or `interaction_required` when calling `acquireTokenSilent`, you should then call `acquireTokenPopup` or `acquireTokenRedirect`, as the user will be unable to acquire a token until they have performed some interactive steps (e.g. login, provide consent).

**Comment by AbhaysinghBhosale** [comment]
No issue is that error occur on login itself and not on `acquireTokenSilent` as before calling this acquireTokenSilent i check token expiry time and if its near to expiry then only this method gets called.

following is the error case.

1. - Call loginRedirect
2. User redirected back to website(screen flicker here) and user get logged in after 2-3 times flickering.

Now if i capture video and see while screen flicker it keep changing url 2 3 times which causing flickering. while screen flicker this login required error is there in url.

**Does msal automatically call `acquireTokenSilent`?**

**One more issue**
After login msal sending an cookie with each API call. that cookie is too long causing http 431. ref https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1316.

This causing issue on prod and need to fixed as soon as possible.

**Comment by zsid** [comment]
@jasonnutter, this is a valid use case for us. Only few users within our organisation will have access to our application. We would like to show an error page to the rest of the users that they are not authorised to use the application.

How can we do this?

**Comment by jasonnutter** [comment]
@AbhaysinghBhosale 

1. First, you do not need to manually check the expiry time of the token, as `acquireTokenSilent` will handle that for you. So you should just call `acquireTokenSilent` right before you need a token, and let it figure out whether or not you need a new token (which it will acquire for you).
2. No, MSAL does not automatically call `acquireTokenSilent`. The symptoms you describe (and specifically the error message you mention) occur when a user gets logged in (with third-party cookies disabled) and then your app attempts to call `acquireTokenSilent`. MSAL returns the `login_required` error you mention, since those third-party cookies are what AAD needs in order for `acquireTokenSilent` to work properly. If you could share a Fiddler trace and/or the video of the flickering, that would be helpful (email is in my profile).
3. #1316: Yep, that is a known issue that we are planning to fix soon.

**Comment by jasonnutter** [comment]
@zsid If you want to show an error page specifically for that scenario, you can inspect the error response (in `handleRedirectCallback`) and perform the desired business logic based on that response.

**Comment by andrantis** [comment]
@jasonnutter Shouldn't the above case be handle at the Idp level? Instead of the login/select user screen, have a screen saying you don't have access to the app or you haven't been assigned to the app. Is there a way to set that up?

**Comment by jasonnutter** [comment]
@andrantis Many errors are handed back to the application to handle, and I'm not familiar with a way to configure that behavior, unfortunately.

**Comment by tnorling** [comment]
Closing. Let us know if this is still an issue.
