### ISSUE TITLE
loginPopup's promise never resolves when the user closes the popup

### ISSUE THREAD

**Issue by dfederm** [AzureAD/microsoft-authentication-library-for-js#129]
When the user closes the popup I'd expect to get a rejection with some signal stating the user cancelled the login so it can be handled appropriately.

If the user hits the "back" button in the popup, there is a rejection though. So the cancellation is inconsistent based on the user explicitly cancelling in the UI vs closing the popup.

**Comment by rohitnarula7176** [comment]
@dfederm We already had the event for the case when the user hits the back button in the UI where we reject the promise with "access_denied". We recently added the event for the case when the user closes the popup manually and in that case we reject the promise with "user_cancelled". Can you please try the dev branch to see if it resolves your issue. This will be part of our next release.

**Comment by dfederm** [comment]
I'm consuming the lib through npm; so y'all have a prerelease dist tag?

Either way, good to know that it should be fixes and just needs a release. Feel free to close this issue.
