### ISSUE TITLE
Auto login redirect when application starts

### ISSUE THREAD

**Issue by soares-fernando** [AzureAD/microsoft-authentication-library-for-js#1292]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Hello, how is it going? 
I'm working with an Angular application that uses Azure authentication, and I'm wondering if there is way to redirect to the login page before the application "starts", or shows any content. This is something to enhance user experience, since the browser shows the interface of the app before the user has a change to login. I could create a login page to show before the app's real content, or some other work around, but my point is: is there a way to do this only using the msal-angularjs library?

I downloaded this sample: https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev-angular-1.0/samples/angular7-sample-app

And tried something like this:

```javascript
import { Component, OnInit } from '@angular/core';
import { BroadcastService, MsalService } from '@azure/msal-angular';
import { Logger, CryptoUtils } from 'msal';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  title = 'MSAL - Angular 7 Sample App';
  isIframe = false;
  loggedIn = false;

  constructor(private broadcastService: BroadcastService, private authService: MsalService) { }

  ngOnInit() {
    this.isIframe = window !== window.parent && !window.opener;

    this.checkoutAccount();

    this.broadcastService.subscribe('msal:loginSuccess', () => {
      this.checkoutAccount();
    });

    this.authService.handleRedirectCallback((authError, response) => {
      if (authError) {
        console.error('Redirect Error: ', authError.errorMessage);
        return;
      }

      console.log('Redirect Success: ', response.accessToken);
    });

    this.authService.setLogger(new Logger((logLevel, message, piiEnabled) => {
      console.log('MSAL Logging: ', message);
    }, {
      correlationId: CryptoUtils.createNewGuid(),
      piiLoggingEnabled: false
    }));

    if (!this.loggedIn) {
      this.login();
    }

  }

  checkoutAccount() {
    this.loggedIn = !!this.authService.getAccount();
  }

  login() {
    const isIE = window.navigator.userAgent.indexOf('MSIE ') > -1 || window.navigator.userAgent.indexOf('Trident/') > -1;

    // if (isIE) {
    //   this.authService.loginRedirect();
    // } else {
    //   this.authService.loginPopup();
    // }

    this.authService.loginRedirect();
  }

  logout() {
    this.authService.logout();
  }
}
```
However, the app still loads its content before the redirect.

I'm new to this version of Angular, so I'm sorry if there's already a silly solution for this.

Thanks in advance for the support!

**Comment by jasonnutter** [comment]
@soares-fernando To clarify, are you using Angular or AngularJS? The sample you link to is for Angular, not AngularJS.

Since MSAL is a client-side library, your application will have to load client-side initially in some way before redirecting to the login page. As you mention, you could create a page in your app dedicated to making this check, but that is work you would need to do, and is outside the scope of the library. If you want your application to be able to make that determination before loading anything client-side, you should use one of the server-side side MSAL libraries.

**Comment by soares-fernando** [comment]
@jasonnutter I'm so sorry. I'm using Angular, not AngularJS. Force of habit to call it AngularJS. That said, thanks for your answer. I'm definitely look into this two options, building a login page, or use a server-side MSAL library.  Since the project is for a client I'll have to consider it with them. But anyways, thanks.
