### ISSUE TITLE
Property 'intercept' in type 'MsalInterceptor' is not assignable to the same property in base type 'HttpInterceptor'

### ISSUE THREAD

**Issue by nikheelneelay** [AzureAD/microsoft-authentication-library-for-js#1296]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [x] `@azure/msal-angular@0.1.4`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
If you are using a framework, please provide the framework and version (e.g. Angular v8, React v16, etc).
Angular CLI: 8.3.25
Node: 10.15.3
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.25
@angular-devkit/build-angular     0.803.25
@angular-devkit/build-optimizer   0.803.25
@angular-devkit/build-webpack     0.803.25
@angular-devkit/core              8.3.25
@angular-devkit/schematics        8.3.25
@angular/cli                      8.3.25
@ngtools/webpack                  8.3.25
@schematics/angular               8.3.25
@schematics/update                0.803.25
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
## Description
A clear and concise description of the bug. If you receive specific error codes, please include them.
I am using Azure AD authentication for Angualr Project and while trying to build the project i am getting compile error in Msal node module class:

ERROR in node_modules/@azure/msal-angular/dist/msal.interceptor.d.ts:11:5 - error TS2416: Property 'intercept' in type 'MsalInterceptor' is not assignable to the same property in base type 'HttpInterceptor'.

## Security
Is this issue security related?
No
## Regression
Did this behavior work before?
Dont know
## Configuration
Please provide your MSAL configuration options.

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```
 MsalModule.forRoot({
      clientID: '4660391a-773f-4c62-9fe2-007c872b5432',
      authority: 'https://login.microsoftonline.com/3740593b-33d3-4fbb-a91d-50b7f09dcea2',
      consentScopes: ['user.read', 'api://45ca7b06-9203-4e2b-ba9b-d842f706c666/api-access'],
      protectedResourceMap: protectedResourceMap
    }

-----
providers: [TestService, {
    provide: HTTP_INTERCEPTORS,
    useClass: MsalInterceptor,
    multi: true
  }]

## Reproduction steps
1. Create a new Angualr Project using versions mentioned above
2. Add npm install @azure/msal-angular --save package for Azure AD authentication
3. Add Msal configuarations as mentioned above
4. Build the project
5. Error on build

## Expected behavior
Should be able to build and serve the project and use Azure AD autntentication
## Browsers
Is this issue browser-specific? If so, please detail which browsers are impacted (e.g. IE 11, Safari).
No

**Comment by jasonnutter** [comment]
@nikheelneelay For Angular 8, you should use `@azure/msal-angular@1.0.0` instead of `0.1.4`. 

You can see a sample for Angular 8 here: https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev-angular-1.0/samples/angular8-sample-app
Upgrade guide: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev-angular-1.0/lib/msal-angular/docs/0.x-1.x-upgrade-guide.md

**Comment by tnorling** [comment]
Closing as this has been answered. Please reopen if you are still having issues after upgrading.
