### ISSUE TITLE
Manually trigger InteractionRequiredAuthError

### ISSUE THREAD

**Issue by rasedgwick** [AzureAD/microsoft-authentication-library-for-js#1297]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.2.1`

## Description
How can I manually trigger a InteractionRequiredAuthError.

I'm upgrading an Aurelia SPA from v 0.2.2 to 1.2.1 and am interested in testing agent.acquireTokenRedirect() which would be called after receiving this error. 

``` javascript
myMSALObj.acquireTokenSilent(accessTokenRequest).then(function (accessTokenResponse) {
    // call API
}).catch( function (error) {
    // call acquireTokenPopup in case of acquireTokenSilent failure
    // due to consent or interaction required
    if (error.name === "InteractionRequiredAuthError") {
        myMSALObj.acquireTokenRedirect(accessTokenRequest);
    }
});
```

**Comment by jasonnutter** [comment]
@rasedgwick You can trigger an `InteractionRequiredAuthError` by removing consent for the application on the [consent page](https://account.live.com/consent/Manage). You can also trigger it by requesting a new scope for which the user has not provided consent.

**Comment by jasonnutter** [comment]
Closing, please let us know if you have further questions, thanks!
