### ISSUE TITLE
Unable to build as per documentation

### ISSUE THREAD

**Issue by prashantkarkera** [AzureAD/microsoft-authentication-library-for-js#1300]
Hi , 

This is for https://www.npmjs.com/package/@azure/msal-browser
I am following the documentation but unable to build . Please see steps below:

npm install @azure/msal-browser - This works fine

The next commands do not work.
lerna bootstrap.

This always gives an error of the form that either package.json or lerna.json was not found. Could you please check this and let me know what is required here.

**Comment by tnorling** [comment]
Looks like docs have been updated. Closing, but feel free to reopen if you're still having issues
