### ISSUE TITLE
Changing the client id on run time

### ISSUE THREAD

**Issue by satish1597** [AzureAD/microsoft-authentication-library-for-js#1304]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`

## Description
> "I am working on a scenario where I need to change the clientId during run time. So, is there any way possible to do this?"

**Comment by jasonnutter** [comment]
@satish1597 You could try instantiating a new instance of `UserApplication` with a different clientId, have you tried that?

**Comment by satish1597** [comment]
@jasonnutter Defining new MsalService requires 4 arguments and it contains msalConfig and msalAngularConfig. What is the difference between them?

**Comment by jasonnutter** [comment]
@satish1597 `msalConfig` is the same `Configuration` object that is used to initialize `msal`, while `msalAngularConfig` is a set of configuration options that are needed specifically for MSAL Angular.
