### ISSUE TITLE
Local dev env not being localhost

### ISSUE THREAD

**Issue by Glideh** [AzureAD/microsoft-authentication-library-for-js#1307]
## Library
- [x] `msal@1.2.1`

## Description

I'm trying to configure my app on Azure Portal for my dev env which is not using http://localhost as URI.

Let's say my application is locally served on http://my-app.test, Portal will tell me the URI:

> Must start with "HTTPS" or "http://localhost"

How can I register this http://my-app.test local URI ?

I've been able to do so on other OAuth 2 suppliers and I'd rather not have to add a self signed certificate. I'm not using `localhost` because I have several web services running locally through a reverse proxy

**Comment by jasonnutter** [comment]
@Glideh Non-https redirect uris are only possible in certain scenarios. See our docs for more info: https://docs.microsoft.com/en-us/azure/active-directory/develop/reply-url#supported-schemes

**Comment by Glideh** [comment]
Thank you for your quick anwser.
So I understand I don't have the choice in my case.
I'll most likely go for a self signed certificate.
