### ISSUE TITLE
How to port redirectUri page from ADAL.js to MSAL.js?

### ISSUE THREAD

**Issue by gabbsmo** [AzureAD/microsoft-authentication-library-for-js#1313]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [x] `@azure/msal-angularjs@1.x.x`

## Description
When building SPAs with ADAL.js you would implement a separate page for redirectUri that would only load adal.js and not the rest of your (heavy) SPA. This page would contain some minimal boilerplate code for processing the hash and then redirect back to the original application. The process is described in the [adal.js wiki](https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/FAQs#q1-my-app-is-re-loading-every-time-adal-renews-a-token).

Should I implement something similar using MSAL.js? If so, how?

**Comment by gabbsmo** [comment]
So far I have replaced adal.js with msal.js and updated the Microsoft.IdentityModel.* nuget packages since the version I used with adalwas not able to extract a principal from the request.

My app consists of two server side pages. One with a AngularJS SPA that talks to a Azure AD authenticated web api and a page with no dependencies other than msal for handling the redirect with the token.

In my SPA msal is configures like this:
```
var protectedResourceMap = {};
protectedResourceMap[$window.location.origin + '/api/'] = ['https://contoso.onmicrosoft.com/000000-0000-0000-0000-0000000000/.default'];

var authConfig = {
    clientID: '000000-0000-0000-0000-0000000000',
    navigateToLoginRequestUrl: false,
    redirectUri: $window.location.origin + '/FrameRedirect',
    authority: 'https://login.microsoftonline.com/organizations/',
    cacheLocation: 'localStorage',
    loadFrameTimeout: 12000,
    optionalParams: {
        cacheLocation: 'localStorage',
        redirectUri: $window.location.origin + '/FrameRedirect',
        unprotectedResources: ['api/language', '/Scripts/'],
        protectedResourceMap: protectedResourceMap
    }
};

msalAuthenticationServiceProvider.init(authConfig, $httpProvider);
```

And on the /FrameRedirect page:
```
var authConfig = {
    auth: {
        clientId: '000000-0000-0000-0000-0000000000',
        navigateToLoginRequestUrl: true
    },
    cache: {
        cacheLocation: "localStorage",
    }
};

new Msal.UserAgentApplication(authConfig);
```

When I open the app I am redirected to the login page. After login in I am redirected to /FrameRedirect. When creating the UserAgentApplication there I am redirected back to the root. When my app bootstraps and starts sending requests they fail with the error `login in progress, cancelling the request for /api/controller/action/`.

**Comment by jasonnutter** [comment]
@gabbsmo Apologies for the delay in responding. To your original question, yes, in MSAL you can also have a dedicated page for your redirect URI. Since v1.2.0, for popup and silent actions this page can be a blank HTML page (i.e. it doesn't even have to include MSAL on it). Redirect URI for redirect actions (loginRedirect and acquireTokenRedirect) will still need to include MSAL in order to process the response (which is done by calling `handleRedirectCallback`). 

You can find an example of a blank `auth.html` page here: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/VanillaJSTestApp/index_blankPageRedirectUri.html

**Comment by rits-development** [comment]
@gabbsmo I attempted the exact same migration. However, I bumped into a bug in MSAL.js (see #1229) so the redirect flow with a separate authenticated redirect page won't work with the current version of MSAL.js.

**Comment by jasonnutter** [comment]
@rits-development I think we'll be able to address this in #1358, so keep an eye on that issue.

@gabbsmo Is this still an issue for you?

**Comment by gabbsmo** [comment]
@jasonnutter I gave up on migrating to MSAL for now. Waiting for the bugs mentioned earlier to be fixed.

**Comment by jasonnutter** [comment]
@gabbsmo To confirm, #1229 / #1358 ?

**Comment by gabbsmo** [comment]
@jasonnutter yes

**Comment by DarylThayil** [comment]
closing because question has been answered
