### ISSUE TITLE
431 Request Header Fields Too Large due to msal long cookie send in headers

### ISSUE THREAD

**Issue by AbhaysinghBhosale** [AzureAD/microsoft-authentication-library-for-js#1316]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.2.1`

## Framework
React v16.6

## Description
Due to loo long cookie send in request header azure webapp returning 431 error ie request headers field too large. After looking into the issues found that cookie send in the header is too long causing this issue. 

cookie shown in request headers(in chrome network tab) contains a long info about msal as follows.
It contains msal login urls, client-info, nonce, authority and many other thing prefixed with `msal`.

I think cookie sent as header contain duplicate info about msal.....

## Configuration
```
const config = {
      auth: {
        clientId: process.env.REACT_APP_EnterpriseADAppClientID,
        redirectUri: redirectUri,
        postLogoutRedirectUri : redirectUri
      },
      cache: {
        cacheLocation: "localStorage",
        storeAuthStateInCookie: true
      },
      system: {
        logger: logger,
        tokenRenewalOffsetSeconds: 300
      }
    }
```

## Browsers
Chrome

**Comment by AbhaysinghBhosale** [comment]
@jasonnutter is there any workaround for this? will it fixed in any new version of msal ?

**Comment by jasonnutter** [comment]
@AbhaysinghBhosale Not yet, we are planning to have a fix soon.

**Comment by AndreiZe** [comment]
This is serious issue because all requests going to app will be failing with the same 431 error. We fixed this in our case by specifying 
cache: { storeAuthStateInCookie: false } 
in MSAL configuration. We could do it because we do not support IE anymore and rely on localStorage for caching tokens.

**Comment by jasonnutter** [comment]
Closing as duplicate, tracked in #1188

**Comment by AbhaysinghBhosale** [comment]
Even after updating to latest version getting same issue

**Comment by wojtek1150** [comment]
+1
