### ISSUE TITLE
Incorrect redirectUri parameter is displayed at the Azure portal website.

### ISSUE THREAD

**Issue by thelowman** [AzureAD/microsoft-authentication-library-for-js#1318]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Documentation location
- [ ] docs.microsoft.com
- [ ] MSAL.js Github Wiki
- [ ] README file
- [x] Other (please fill in)
- [ ] Documentation does not exist

## Description
The quick start guide at portal.azure.com repeatedly shows the following configuration:
```javascript
var msalConfig = {
    auth: {
        clientId: "xxxxxxxx",
        authority: "https://login.microsoftonline.com/organizations",
        redirectURI: "http://localhost:30662/"
    },
    cache: {
        cacheLocation: "localStorage",
        storeAuthStateInCookie: true
    }
};
```
But I kept getting "The reply URL specified in the request does not match the reply URLs configured for the application" errors with my SPA.  After a lot of time troubleshooting I came across issue  #724 and in one response by @DarylThayil he mentioned setting the "redirectUri" (camel-case) value.  It took a little while to realize I'd copied "redirectURI" from the example.  I've changed it and all is well.

Given the temptation to just copy and paste this handy premade configuration it might save others a great deal of frustration to have that looked at.

**Comment by jasonnutter** [comment]
@thelowman Great catch, we'll make sure that gets fixed, thanks!

**Comment by jasonnutter** [comment]
A fix is in progress for this, we'll update this ticket when it is done.

**Comment by tnorling** [comment]
Looks like this was fixed. Let us know if its still incorrect.
