### ISSUE TITLE
There is a problem with login from Azure Account Applications page

### ISSUE THREAD

**Issue by legrak** [AzureAD/microsoft-authentication-library-for-js#132]
It is not possible to log in using MSAL loginRedirect method if user starts his trip from an Azure Account Applications page.
Please note that Account Applications page is entry point for following 

**Scenario:**
1. Register new Guest user in Azure AD (B2B)
2. Assign user to application in Azure
3. User clicks Get Started button in Invitation email
4. User is logged in/registered as new user on Microsoft page
5. User is redirected to https://account.activedirectory.windowsazure.com/r#/applications page
6. User clicks application to get started his work with it

Actual: Application can not log user in and url hash with token are present in url.

**Technical details:**
1. There is a following code in UserAgentApplication.ts:

```
if (!window.opener) {
	var isCallback = this.isCallback(window.location.hash);
	if (isCallback) {
		var self = this;
		setTimeout(function () { self.handleAuthenticationResponse(window.location.hash); }, 0);
	}
}
```

This code is trying to parse redirect url if detects that it is a calback url.
However, Azure Account Applications page opens new window as controlled (window.opener is not empty) when click on application.

I do understand that !window.opener check is present to support both popup and redirect login flows, but MSAL should find some better way for this.

**Workaround:**
There is a possibility to solve this problem with a little 'hack'. Add this code for application entry point:

```
if (window.location.href.indexOf("logincallback") < 0) {
  window.opener = null;
}
```

Please note that check for 'logincallback' possibly needed to not break some other integrations that uses popup login scenario.
I'm not sure if this is correct and what can it broke but it works in my case.

**Comment by navyasric** [comment]
@legrak Is there any specific error you are seeing in the network trace or console logs when user cannot log in?

**Comment by legrak** [comment]
@navyasric , no, there are no errors. MSAL just skipping to parse redirect URI because of window.opener is not null. using following code I have just endless redirects from login page to my app and then again to login page. Clicking login button with correct user/password redirects me correctly to my app, but token is not extracted from reply url..

```
      if (this.clientApplication.getUser()) {
        return this.clientApplication.acquireTokenSilent(scopes)
          .catch(error => {
            console.error(`Failed to get access token: ${error}`);
            this.clientApplication.loginRedirect(scopes);
          });
      }
      this.clientApplication.loginRedirect(scopes);
```

**Comment by legrak** [comment]
by the way, I'm using version 0.1.1 from CDN:
```
  <script src="https://secure.aadcdn.microsoftonline-p.com/lib/0.1.1/js/msal.min.js"></script>
```

**Comment by rohitnarula7176** [comment]
@legrak Thank you for pointing out this issue. This issue occurs in Edge because of a race condition where the constructor and the popup window both try to process the hash at the same time. I have changed the code logic to fix it. Can you please use my branch and verify if it resolves your issue. https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/rohitnarula7176/Issue_132. I will add this fix as part of our next release.

**Comment by rohitnarula7176** [comment]
@legrak Issue is now fixed in the dev branch.
