### ISSUE TITLE
MSAL Angular B2C Authorization SignalR connection/Hub

### ISSUE THREAD

**Issue by Raysapps** [AzureAD/microsoft-authentication-library-for-js#1322]
## Library
"@azure/msal-angular": "^1.0.0-beta.2"

## Description
My Angular -ASP.NET Core web app hosted on Azure AppService is integrated with Active directory B2C for Web API authorization and I would like to use the same B2C credentials to authorize SignalR connection/hub.Is this possible? If yes, could you please provide the procedure/samples to implement the same.

**Comment by Raysapps** [comment]
I've successfully authorized SignalR from angular by accessing token from the broadcast service as below:
` this.acquireTokenSuccessSubscription = this.broadcastService.subscribe("msal:acquireTokenSuccess", (payload) => {
    
// pass token to _signalR service init method
      _signalR.init(payload["accessToken"]);
    
    }); 
class SignalR 
{     
     init(accessToken:string) {
    this.createConnection(accessToken);
   
  }
private createConnection(accessToken: string) {
    this._hubConnection = new HubConnectionBuilder()
      .withUrl("url",{ accessTokenFactory: () => accessToken })
      .configureLogging(LogLevel.Trace).build();
  }` 

However, I am not sure whether this is the right approach. I would like to know if there is any direct API to fetch the access token instead of initializing from the broadcast service?

**Comment by tnorling** [comment]
@Raysapps Apologies for the delayed response. Is this still an issue? You can use `this.authService.acquireTokenSilent` to acquire tokens directly.

**Comment by Raysapps** [comment]
No worries and thanks for your response. Closing this question as it  is resolved.
