### ISSUE TITLE
Status of AngularJS wrapper, unsupported?

### ISSUE THREAD

**Issue by CodyMorris** [AzureAD/microsoft-authentication-library-for-js#1334]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [X] `@azure/msal-angularjs@1.x.x`

## Description
When investigating msal and msal-angularjs, it appears as if its an actively supported wrapper.  Neither the core readme or the readme for the AngularJS mention that the wrapper is no longer supported.  Unfortunately, after spending some time with this library its become clear after finding a handful of Github issues that the wrapper is actually at end of life.  Is that the case?

If it is, can you please make it much more obvious that there is no actively supported AngularJS wrapper for this library?  While it works in some cases, there are serious challenges which make using it production a struggle to say the least

**Comment by jasonnutter** [comment]
@CodyMorris Yes, the `@azure/msal-angularjs` wrapper is in maintenance mode, and only receiving high-priority security fixes. We are concentrating our efforts on `@azure/msal-angular`.

We'll make sure this made clearer in our documentation. Thanks for the feedback!

**Comment by sameerag** [comment]
cc @hamiltonha
