### ISSUE TITLE
MSAL issue in MS Teams

### ISSUE THREAD

**Issue by Nitin393** [AzureAD/microsoft-authentication-library-for-js#1335]
I have developed an SPFX component where I am authenticating Azure AD using MSAL. I am able to get token and extension is working fine for me. Now, when I add this SharePoint page in MS Teams (Desktop version) tab, I am getting error while acquiring token. I am acquiring token using 'acquireTokenSilent' method of MSAL and passing authentication parameters with loginHint with scopes. SharePoint works fine with this, but as soon as I access the same page with MS Teams (desktop version) I gets below error while accessing token;
**ClientAuthError: Token calls are blocked in hidden iframes**

 Below is error in detail;

_ClientAuthError: Token calls are blocked in hidden iframes
(anonymous) @ project-web-part_cbf0d4453e2cf832810b609670ef60d8.js:15
Promise.catch (async)
(anonymous) @ project-web-part_cbf0d4453e2cf832810b609670ef60d8.js:15
e.getAPIAccessToken @ project-web-part_cbf0d4453e2cf832810b609670ef60d8.js:15
(anonymous) @ project-web-part_cbf0d4453e2cf832810b609670ef60d8.js:15
e.GetWebAPI @ project-web-part_cbf0d4453e2cf832810b609670ef60d8.js:15
t.getProjectSiteUsersCount @ project-web-part_cbf0d4453e2cf832810b609670ef60d8.js:15
t.componentWillMount @ project-web-part_cbf0d4453e2cf832810b609670ef60d8.js:15
sl @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:21
ki @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:21
(anonymous) @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:21
Ua @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:21
Ia @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:21
xo @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:21
bo @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:21
mo @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:21
Wa @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:21
Co @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:21
Po @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:21
Do.render @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:21
(anonymous) @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:21
Eo @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:21
Io @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:21
render @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:21
t.render @ project-web-part_cbf0d4453e2cf832810b609670ef60d8.js:15
t._renderWithAccessibleTitle @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:21
(anonymous) @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:21
Promise.then (async)
(anonymous) @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:21
Promise.then (async)
t._onInViewport @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:21
e._renderWebpartInViewport @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:21
e.release @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:21
(anonymous) @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:21
e._loadOutsideViewPort @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:21
e.loadOutsideViewPort @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:21
e._onViewportWebpartsLoaded @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:21
(anonymous) @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:21
setTimeout (async)
e._onAllWebpartsAdded @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:21
a.Environment.type.a.EnvironmentType.ClassicSharePoint.t.totalWebparts.t.totalWebparts.i.then.r._onAllWebpartsAdded.t.totalWebparts @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:21
Promise.then (async)
e._loadWebPartOld @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:21
e.loadWebPart @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:21
n._loadWebPart @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:2
t.componentDidMount @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:2
Na @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:21
Ma @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:21
(anonymous) @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:21
Ay1f.t.unstable_runWithPriority @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:21
wo @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:21
xo @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:21
bo @ sp-pages-assembly_en-us_dcfe147211950575af0e17d26b0ced7b.js:21_

I am using MSAL 1.2.1 library.

**Comment by icatchx22i** [comment]
Hey, I'm not an expert on the issue by any means but I hit this same issue where my React app was authenticating successfully in browser but failing gloriously as an MSTeams Tab. I believe the solution here is to use the popup workflow instead of the redirect method.  Now im not sure if fully applicable to SPFX components, but here is the example : https://github.com/OfficeDev/microsoft-teams-sample-complete-node/tree/master/src/views/tab-auth (uses adal for some reason..) Hope the many hours I spent on this help you in this case.

**Comment by icatchx22i** [comment]
Unfortunately.. it seems like there's a known bug that means this may not work with MSAL: #1095

**Comment by DarylThayil** [comment]
@Nitin393 
This error message you are seeing is a consequence of calling AcquireTokenSilent on the page that loads inside a hidden iframe.
To mitigate this receiving this error message, either don't call ATS on page load when your app is loaded in a hidden iframe or use a blank page as the redirect uri for silent requests (will improve perf as well) 
The error message is purely informational and will not block your app from acquiring a token. 

@icatchx22i  we have a solution for #1095 in PR #1413  
Expect it in our next release cc @tnorling  for context

**Comment by DarylThayil** [comment]
closing this issue
