### ISSUE TITLE
Unable to change accounts when using OpenID Connect pointing to an AAD tenant

### ISSUE THREAD

**Issue by cleberdantas** [AzureAD/microsoft-authentication-library-for-js#1336]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [x] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Azure AD B2C is configured to use `Local Accounts` and `OpenID Connect`, which points to an Azure Active Directory tenant.

When an user from the AAD logs in via the button configured in B2C, usually he/she is also logged in another "application", lets say Outlook or Office or Sharepoint etc from the original tenant.

The `logOut()` feature on `MSAL` for Angular (not AngularJS) seems to just remove session data for the application that uses B2C, which seems far at first, but here comes the problem.

User gets logged out from the application that uses ADD B2C, so now the user can login into the application with another user, but in my scenario the user wants to login with a different user that exists in the AAD tenant (via the button, configured with `OpenID Connect`)... since the session/cookies data from the original tenant was not removed, when hitting the button to try a different user, the user gets logged in again with the same user automatically. 

The only way to do login with a different user is, lets say, open Office.com do a signout and now try again in the application that uses B2C, because now a login page from the original tenant will appear, allowing the user to choose any user.

Please, any advice? Is there a way to do a "hard logout" coming from the application? Is there any configuration that forces the login page from the AAD to always appear when hitting the `OpenID Connect` button?

**Comment by jmckennon** [comment]
To clarify the use case here:

You have B2C configured with an AAD tenant. You have a user who is logged into multiple applications, we'll say your B2C app and Office. If the user logs out of the B2C app, and then tries to login again on a different user in the same AAD tenant. At this point, they will login to the original user, not the new one. If the second app, Office in this scenario, was never opened, this doesn't happen and the second user can log in properly. Is this all correct?

As a question: what are you setting your `prompt` value to in the configuration? You may be able to use that as an immediate workaround for this as well. [Prompts in msal](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-prompt-behavior).

**Comment by cleberdantas** [comment]
It is partially correct.

The scenario where the Office was never opened before does not change the behavior. 

Lets say I'm opening the application in a new computer (no session/cookies anywhere), so I open my B2C app and go to login, there I can choose to do the authentication `locally` or via a `federated` AAD (a button like facebook, but for an AAD tenant). In this case I will choose the button, since I have never done login in the AAD tenant before the page to enter credentials will be prompted, so I proceed and enter the information, the authentication will succeed and I will get back to my B2C app authenticated, everything just fine here. (at this point I'm already 'logged' into Office as well even though I have never opened the Office website so far, since the session that was created when I did login for the B2C app is kind of shared between applications that uses the same tenant, that is my understanding so far.)

So when I try to logout from my B2C app, the session for the AAD tenant is not destroyed (apparently) and when I try to login with a different user this just goes automatically for the user that "still" is logged in for Office, not allowing me to change user or enter new credentials.

`Users will not see an account selection experience if there is only a single authenticated session with Azure AD.` 

I got the phrase above from the link that will shared at the end, it just like that indeed.

Maybe the use of `prompt` will solve the problem, I'll try it. 

Do you know if it is possible to configure it via the `Angular` wrapper? I did not see this configuration before.

**Comment by jasonnutter** [comment]
@cleberdantas Yes, you can provide the prompt parameter via `extraQueryParameters`: `extraQueryParameters: 'prompt=select_account',`

**Comment by sameerag** [comment]
Hey all, The recommendation is to send prompt as its own parameter and is supported in the request for interactive calls. silent calls include `prompt=none` from the library scrubbing any other `prompt` values set as we want no prompts in that case.

**Comment by jasonnutter** [comment]
@cleberdantas Is this solved?

**Comment by DarylThayil** [comment]
closing since this has not had activity
