### ISSUE TITLE
acquireTokenSilent fails when using clientid as scope

### ISSUE THREAD

**Issue by joeweale** [AzureAD/microsoft-authentication-library-for-js#134]
When using my client id to get a token I get: "Token renewal operation failed due to timeout: null"

clientApplication.acquireTokenSilent(["0000000-0000-0000-0000-000000000"])

works fine on the login methods (popup and redirect) just not on acquireTokenSilent. If i replace the scope with ["User.Read"] it gets the token successfully.

Unfortunately this is causing users to be prompted every hour to login again which isn't a good experience.

Any ideas?

Thanks

Joe

**Comment by rohitnarula7176** [comment]
@joeweale The issue is fixed in dev. Could you please use the dev branch and confirm? We will release a new version this week with this fix and a few others.

**Comment by joeweale** [comment]
thanks. Fixed.
