### ISSUE TITLE
MsalInterceptor not attaching tokens

### ISSUE THREAD

**Issue by abishekreddy** [AzureAD/microsoft-authentication-library-for-js#1341]
## Library
- [x] `@azure/msal-angular@1.0.0-beta.2`

## Framework
Angular 7.2

## Description
The MsalInterceptor is not attaching tokens to API calls. 
I have added the logger callback with console logging and log level set to Verbose to identify where its failing. The log shows that its unable to find the url in the protectedResourceMap array even though it has been passed.

Note: I am passing the protectedResourceMap and unprotectedResources to the MsalAngularConfiguration and not the framework part of MSAL's Configuration.

## Configuration

```
MsalModule.forRoot({
      auth: {
        authority: environment.auth.authority,
        clientId: environment.auth.clientId
      },
      cache: {
        cacheLocation: environment.auth.cacheLocation,
        storeAuthStateInCookie: true,
      },
      system: {
        loadFrameTimeout: environment.auth.loadFrameTimeout
      }
    }, {
      consentScopes: environment.auth.initialConsentScopes,
      protectedResourceMap: environment.auth.autoProtectedResources,
      unprotectedResources: environment.auth.manuallyProtectedResource.prodBotApi
    })
```

**Comment by abishekreddy** [comment]
Seems like the issue is with the getScopesForEndpoint method of MsalService. On line 182, the code doesn't seem to check for an empty array/map. 

`const protectedResourceMap = (this.msalConfig.framework && this.msalConfig.framework.protectedResourceMap) || new Map(this.msalAngularConfig.protectedResourceMap);`

So if framework is not passed as part of msalConfig and msal sets a default, then protectedResourceMap variable would be empty => Scopes will not be found.

**Comment by jasonnutter** [comment]
@abishekreddy Great catch, I'll make sure this gets fixed. Thanks!
