### ISSUE TITLE
Automate new CDN uploads

### ISSUE THREAD

**Issue by jmckennon** [AzureAD/microsoft-authentication-library-for-js#1345]
We've reworked the CDN so that we can directly upload to Azure Storage. We want to automate this process in our pipeline. Extension of #893

**Comment by keystroke** [comment]
Yes please! I'd love to rely on the new release notifications implying that the new version is available at the CDN link. I've seen it delayed weeks and it is annoying.

**Comment by jasonnutter** [comment]
@keystroke Trust me, don't have to tell @jmckennon how annoying this has been :)

**Comment by jasonnutter** [comment]
The first part of this is done (automating the upload process). Rest of the work is captured in internal PBIs, closing.
