### ISSUE TITLE
[1.x] Tokens are being cached with client id scope

### ISSUE THREAD

**Issue by pkanher617** [AzureAD/microsoft-authentication-library-for-js#1357]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.2.2-beta.1` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Description
When completing a redirect auth flow, the tokens in the cache are being cached with the client id as the scope. Ideally this should be cached with openid and profile scopes instead. This is causing false cache mismatches, and forcing acquireTokenSilent to go to the wire to get new tokens. 

## Regression
Worked in 1.1.3

## Configuration
Please provide your MSAL configuration options.

```js
// initialize MSAL
    const msalConfig = {
        auth: {
            clientId: "xxxxx",
            authority: "https://login.microsoftonline.com/common",
            navigateToLoginRequestUrl: true
        },
        cache: {
            cacheLocation: "localStorage",
            storeAuthStateInCookie: false
        }
    };

    const loginRequest = {
        scopes: ["openid", "profile", "User.Read"]
    };

    const tokenRequest = {
        scopes: ["Mail.Read"]
    };

    // resource endpoints
    const graphConfig = {
        graphMeEndpoint: "https://graph.microsoft.com/v1.0/me",
        graphMailEndpoint: "https://graph.microsoft.com/v1.0/me/messages"
    };

    // instantiate MSAL
    const myMSALObj = new Msal.UserAgentApplication(msalConfig);

    // register callback for redirect usecases
    myMSALObj.handleRedirectCallback(authRedirectCallBack);

    // signin and acquire a token silently with POPUP flow. Fall back in case of failure with silent 
    acquisition to popup
    function signIn() {
        myMSALObj.loginRedirect(loginRequest);
    }

    // redirect call back
    function authRedirectCallBack(error, response) {
        if (error) {
            console.log(error);
        } else {
            if (response.tokenType === "id_token") {
                showWelcomeMessage();
                acquireTokenRedirectAndCallMSGraph(graphConfig.graphMeEndpoint, loginRequest);
            } else if (response.tokenType === "access_token") {
                callMSGraph(graphConfig.graphMeEndpoint, response.accessToken, graphAPICallback);
            } else {
                console.log("token type is:" + response.tokenType);
            }
        }
    }

// This function can be removed if you do not need to support IE
   function acquireTokenRedirectAndCallMSGraph(endpoint, request) {
        //Call acquireTokenSilent (iframe) to obtain a token for Microsoft Graph
        myMSALObj.acquireTokenSilent(request).then(function (tokenResponse) {
            callMSGraph(endpoint, tokenResponse.accessToken, graphAPICallback);
        }).catch(function (error) {
            console.log("error is: "+ error);
            console.log("stack:" + error.stack);
            //Call acquireTokenRedirect in case of acquireToken Failure
            if (requiresInteraction(error.errorCode)) {
                myMSALObj.acquireTokenRedirect(request);
            }
        });
    }

if (myMSALObj.getAccount()) {// avoid duplicate code execution on page load in case of iframe and popup window.
            showWelcomeMessage();
            acquireTokenRedirectAndCallMSGraph(graphConfig.graphMeEndpoint, loginRequest);
        }
```

## Reproduction steps
1. Run the sample with the above config
2. Hit "Sign In" and enter creds.
3. Review console and look for token blocked error. Check cache and you should see a token cached with client id scope.

## Expected behavior
Should be caching with openid and profile, not client id. No cache misses.

## Browsers
Tested in Chrome, but most likely an issue in all browsers

**Comment by element8763** [comment]
Sorry about the late reply,I track the debug and found that when use webform to get the accesstoken from the cache,it will fail because the key is wrong.So that can not get token in the C# webform solution.I mean when execute function in a form runat in server.

**Comment by tnorling** [comment]
@element8763 Can you try upgrading to `msal@1.3.0`. This version fixes a token caching bug which may be why you are getting a cache miss. ID tokens are currently being cached with client id in the scope field. Access tokens should be getting properly cached as of 1.3.0
