### ISSUE TITLE
how to get scopes using “@azure/msal-angular”: “^0.1.4”?

### ISSUE THREAD

**Issue by singshiv90** [AzureAD/microsoft-authentication-library-for-js#1360]
Currently, I am facing an issue with scope. As we are passing the scope in the URL but after successful authentication with azure I am able to get the token, but when I decode the token the scopes are not present in the token. Could you please help out here? I have tried so many ways, but unfortunately, I am unable to get scopes in the token.

Plugin Used: "@azure/msal-angular": "^0.1.4"

![my](https://user-images.githubusercontent.com/62064574/76424426-3c0b2e80-63ce-11ea-80e0-c748249c011f.jpg)

![Analytics](https://user-images.githubusercontent.com/62064574/76677234-e9aa5780-65f1-11ea-9daa-c7a72ab91207.png)

**Comment by jasonnutter** [comment]
See this issue for how to get the `scp` claim: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1286

Closing.
