### ISSUE TITLE
Needs a clear installation guide

### ISSUE THREAD

**Issue by razorsyntax** [AzureAD/microsoft-authentication-library-for-js#1364]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x ] `@azure/msal-browser@2.x.x`
- [x] `@azure/msal-angular@0.x.x`
- [ x] `@azure/msal-angular@1.x.x`
- [x ] `@azure/msal-angularjs@1.x.x`

## Documentation location
- [ x] docs.microsoft.com
- [x ] MSAL.js Github Wiki
- [x ] README file
- [ ] Other (please fill in)
- [x] Documentation does not exist

## Description
There doesn't appear to be any documentation that does says something like `npm install <library name>` followed by what to expect. This should be standard across all documentation despite how easy this might seem. We need an extremely simple, clear, step-by-step instructions to install and get running. Most the documentation is around explaining what the library is and how it works.  That's great, but it needs easier steps to get up and running.

**Comment by jasonnutter** [comment]
@razorsyntax We are currently working on the GA of MSAL Angular, which will include improved documentation and quickstart guides, which I believe is what you are asking for. We'll make an announcement when that is ready.

In the mean time, let us know if you have any specific questions, thanks!

**Comment by jasonnutter** [comment]
Updated installation and upgrade instructions are in the README: https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-angular

Closing.
