### ISSUE TITLE
Guard does not set the valid token

### ISSUE THREAD

**Issue by Stefan185** [AzureAD/microsoft-authentication-library-for-js#1365]
## Library
- [ x] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
I am using the Beta 4 with ng9 - latest version.
I have two portals with the same b2c tenent.

I have a simple href link to http://localhost:4200  from one portal to the other one.
If the target is same window it work. 
With the target _blank the target page is call, but the token will not be set. 
The guard redirects correctly to the redirectpage http://localhost:4200/oidc-signin

Targetpage:
http://localhost:4200/oidc-signin#state=c395df86-6746-4ee3-ad8a-791f9147d45d&client_info=ey...&id_token=ey...

Strg-F5 changes nothing.

Everything is fine, when I create a new tab with this url.

What could be the reason?

**Comment by jasonnutter** [comment]
@Stefan185 This is a known issue with the core `msal` library, which we plan to have fixed soon.

**Comment by jasonnutter** [comment]
Closing as duplicate, will be fixed with #1413
