### ISSUE TITLE
@azure/msal-angular and SSO for apps from different domains

### ISSUE THREAD

**Issue by mrivero2020** [AzureAD/microsoft-authentication-library-for-js#1367]
## Library
msal@1.2.2-beta.0
@azure/msal-angular@1.0.0-beta.2

## Description

I am trying to implement SSO from two different (but related) angular 9 apps, hosted on different domains.

The Microsoft documentation states that SSO functionality is provided out of the box if apps are hosted on the same domain. However, if they are not on the same domain, then using acquireTokenSilent with optional sid may be the way to go. The @azure/msal-angular documentation acknowledges the existence of acquireTokenSilent but recommends staying inside the bounds of MsalGuard.

Question: Is there a way to configure MsalGuard to implement SSO for apps running on different domains? If not, can it be done with acquireTokenSilent, mixing this function with MsalGuard?

Thanks

**Comment by mrivero2020** [comment]
Just added the optionalClaims section below to the application manifest and so far it looks like that is all I needed to do to get SSO between applications on different domains. Is this the solution?

"optionalClaims": 
	 {
	     "idToken": [ 
		{ 
      		      "name": "sid", 
      		      "essential": false
        		}
       	     ]
	},

**Comment by jasonnutter** [comment]
@mrivero2020 Yes, I believe `sid` should be the right approach. And for this scenario, I wouldn't worry about staying within the Guard (I'm planning to revise that guidance).
