### ISSUE TITLE
How do I properly update @azure/msal-angular 0.1.4 to latest

### ISSUE THREAD

**Issue by dinukaw007** [AzureAD/microsoft-authentication-library-for-js#1370]
## Library
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@angular/compiler@8.2.13`
- [ ] `typescript@3.4.5`

## Description
After update the library form 0.1.4 it's gives error when build the angular 8 app (Cannot find module 'msal'.) in node_modules. For the information tried to delete node_modules and (npm run) again it didn't work either.

> "How do I properly update @azure/msal-angular 0.1.4 to latest

**Comment by alberthoekstra** [comment]
```
npm install msal@latest --save
npm install @azure/msal-angular@latest --save
```

**Comment by jasonnutter** [comment]
@dinukaw007 You can find complete instructions for upgrading here: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/0.x-1.x-upgrade-guide.md

**Comment by chr1soscl** [comment]
in what package can I find these dependencies?
ERROR in The target entry-point "@azure/msal-angular" has missing dependencies:
 - msal/lib-commonjs/utils/UrlUtils
 - msal/lib-commonjs/utils/WindowUtils
 - msal/lib-commonjs/cache/AuthCache

**Comment by jasonnutter** [comment]
@chr1soscl You need to use the latest version of `msal`, such as `msal@1.2.2`.
