### ISSUE TITLE
[msal-node] coverage works with same tools as `msal-common`

### ISSUE THREAD

**Issue by sameerag** [AzureAD/microsoft-authentication-library-for-js#1372]
## Upcoming Library
- [x] `@azure/msal-node@1.x`

## Description
`msal-node` coverage tools are currently running with `tsdx test --coverage`. Since `msal-common` uses a different set of tools, make sure automation pipeline works when `msal-node` is merged to dev

## Priority
Alpha branch by March end (Current Quarter - Q3)

## Acceptance Criteria
- Coverage works with build automation pipeline

**Comment by pkanher617** [comment]
Coverage is being run, but publishing to Coveralls needs to be done.
