### ISSUE TITLE
MSAL React Sample App Error in IE11

### ISSUE THREAD

**Issue by exequeryphil** [AzureAD/microsoft-authentication-library-for-js#1375]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
The version included in the MSAL React Sample App.

## Framework
The version included in the MSAL React Sample App.

## Description
In IE11, after clicking the "Sign In" button, nothing happens, and the console reports the following:
Possible Unhandled Promise Rejection (id: 0):
TypeError: Invalid calling object
If the page is refreshed, and the "Sign In" button is clicked again, the authentication process begins as expected.
This error does not occur in Edge, Firefox, or Chrome.

## Security
No

## Regression
Unknown

## Configuration
The default configuration of the MSAL React Sample App.

## Reproduction steps
1. Clone the React Sample App repo
2. npm install, npm start, add valid clientId to auth-utils.js
3. Open localhost:3000 in IE11 and attempt to log in.

## Expected behavior
The login process should begin after a user clicks the "Sign In" button

## Browsers
The problem occurs in IE11 only.

**Comment by oskarcronwall** [comment]
I had a similar issue. Looking at the stack trace, it seems it is caused by the logging functionality. Try the sample without the logger defined in auth-utils.js.

**Comment by Ascenticprathap** [comment]
> I had a similar issue. Looking at the stack trace, it seems it is caused by the logging functionality. Try the sample without the logger defined in auth-utils.js.

this works perfectly .Kudos @oskarcronwall  👯‍♂️

**Comment by jasonnutter** [comment]
Thanks for the infor, we'll make sure this gets fixed.
