### ISSUE TITLE
MSAL Angular Raw UserID (Access to own Web API)

### ISSUE THREAD

**Issue by myleskeeffe** [AzureAD/microsoft-authentication-library-for-js#1377]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [X] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
I've got a NodeJS backend webserver with passport.js and passport-azure-ad. I am looking to append all of my web requests with the signed in user's IdToken so they can authenticate with the API. To test this before I implemented it I'm testing around in a component I've called home. Here's the code I have in home.component.ts:

```
import { Component, OnInit } from '@angular/core';
import { GlobalConstants } from '../common/global-constants';
import { BroadcastService, MsalService } from '@azure/msal-angular';



@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit {

  constructor(private broadcastService: BroadcastService, private authService: MsalService) {console.log(this.userData)}

  //
  userData = this.authService.getUser();
  loggedIn;

  ngOnInit() {
    
  }



}

```

However, with this I get everything but the RawUserID - which is what my backend needs to authenticate the user. I've been searching a while and found how to do it with normal js, but I was hoping for a more eloquent way of doing it with Angular. Hopefully I've missed some really obvious option. Thankyou in advance!

**Comment by myleskeeffe** [comment]
Found the answer after ages looking around. RawIDToken is saved in session storage so I was able to retrieve it using `sessionStorage.getItem("msal.idtoken")` and then request my web api using `this.http.get("http://localhost:8080/api/user/prefs/", {headers: {Authorization:"Bearer " + sessionStorage.getItem("msal.idtoken")}})......`

**Comment by jasonnutter** [comment]
@myleskeeffe For custom web APIs, you should use access tokens (with custom scopes) instead of ID tokens, as access tokens represent that the user has provided consent for a given resource (e.g. your custom web api). More context here: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1040#issuecomment-540810355
