### ISSUE TITLE
Locally access_token retrieve perfectly but after build for production and deploy it wont work

### ISSUE THREAD

**Issue by dinukaw007** [AzureAD/microsoft-authentication-library-for-js#1378]
## Library
- [ ] `@azure/msal-angular@1.0.0-beta.4` 
- [ ] `@angular/cli@8.3.24`
- [ ] `@angular/compiler-cli@8.2.14`

## Description
 
When I run the system (Anguler 8 app) locally  access_token retrieve perfectly. But ones I build to --prod and deploy it, It wont work and give id token as access_token so below code snippet  wont work. and Graph API gives InvalidAuthenticationToken [401 Unauthorized]

```
const acquireTokenSuccessSubscription = this.broadcastService.subscribe(
			'msal:acquireTokenSuccess',
			payload => {
				if (payload.tokenType === 'access_token') {
					localStorage.setItem('accessToken', payload.accessToken);
					console.log('..');
				}
			}
		)
```

app.module.ts Msal Configuration
```

export const protectedResourceMap: [string, string[]][] = [
	['https://graph.microsoft.com/v1.0/me', ['User.Read']],
	['https://graph.microsoft.com/v1.0/users', ['User.Read']],
	['api://' + environment.clientId + '/user.read', ['user.read']],
	[
		'https://graph.microsoft.com/',
		[
			'https://graph.microsoft.com/User.Read',
			'https://graph.microsoft.com/User.Read.All',
			'https://graph.microsoft.com/User.ReadBasic.All'
		]
	]
];
	MsalModule.forRoot(
			{
				auth: {
					clientId: environment.clientId,
					authority: 'https://login.microsoftonline.com/common/',
					validateAuthority: true,
					redirectUri: environment.redirectUri,
					postLogoutRedirectUri: environment.redirectUri,
					navigateToLoginRequestUrl: true
				},
				cache: {
					cacheLocation: 'localStorage',
					storeAuthStateInCookie: true // set to true for IE 11
				},
				framework: {
					// unprotectedResources: ['https://www.microsoft.com/en-us/'],
					protectedResourceMap: new Map(protectedResourceMap)
				}
			},
			{
				popUp: !isIE,
				consentScopes: [
					'user.read',
					'User.ReadBasic.All',
					'openid',
					'https://graph.microsoft.com/User.Read',
					'https://graph.microsoft.com/User.Read.All',
					'https://graph.microsoft.com/User.ReadBasic.All'
				],
				extraQueryParameters: {}
			}
		)
```

> "What can be the issue for this ?

**Comment by jasonnutter** [comment]
@dinukaw007 Are you also using the `MsalInterceptor`? The interceptor will automatically attach access tokens (with the relevant scopes) to outgoing http requests, based on the `protectedResourceMap`.

**Comment by alberthoekstra** [comment]
In my app I have multiple actions on the backend that don’t require being authenticated. 
When putting the url of the backend in the protectedResourceMap those actions it also will authenticate of course. 
Therefor I had to create my own interceptor to prevent this. 

For example:
‘’’
- /api/values/post requires Auth
- /api/values/get does not require Auth
‘’’

**Comment by dinukaw007** [comment]
FYI It's working fine when I run  locally (ng serve) when I build --prod and deploy this problem occur. 
However  seems like there is a issue with AOT ones i disable the AOT for build  its work and also there is a another workaround, I add fallowing code lines
```
const acquireTokenFailureSubscription = this.broadcastService.subscribe('msal:acquireTokenFailure', payload => {
             this.adaAuthService.signIn();
});
```

```
const loginFailureSubscription = this.broadcastService.subscribe('msal:loginFailure', payload => {
          this.router.navigateByUrl('auth/login');
});
```
