### ISSUE TITLE
Authenticating MSAL.js auth Tokens using Node.js

### ISSUE THREAD

**Issue by thelements** [AzureAD/microsoft-authentication-library-for-js#1380]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`

## Description
I have used MSAL.js with my React,js Application. This application uses backend api used in node,js apis to drive the application. 
I read the docs, but I am unable to authenticate any user using Node.js
Is there any docs or library available which I am missing?

**Comment by jasonnutter** [comment]
@thelements You can use our `passport-azure-ad` library to validate access tokens server-side in your Node application: https://github.com/AzureAD/passport-azure-ad/

**Comment by jasonnutter** [comment]
Closing, let us know if you have further questions.

**Comment by thelements** [comment]
Let's say I have my custom token in my app. So i can't use as middleware is there a way to do it manually. I can pass as a custom key and validate. I am unable to find any proper method to do so,
I am receiving some msal.idtoken or something.

**Comment by jasonnutter** [comment]
You can find more information about validating access tokens here: https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens#validating-tokens
