### ISSUE TITLE
Hidden iFrame accessibility error

### ISSUE THREAD

**Issue by Sl1MBoy** [AzureAD/microsoft-authentication-library-for-js#1381]
I have noticed that the application is loaded to the hidden iframe while using msal. Unfortunately this causing A11Y voice over features to focus and read out elements inside the iframe. This can be prevented by adding aria-hidden="true" attribute to the iframe. 

I have experienced this with msal 1.2.1 and Safari browser.

**Comment by jasonnutter** [comment]
@Sl1MBoy Thanks for the information, we definitely want to make sure this is fixed.

**Comment by DarylThayil** [comment]
Note: This may be solved in 1.2.2 by removing hidden iframes, but we should add correct aria tags regardless

**Comment by jo-arroyo** [comment]
@Sl1MBoy We believe we have a potential fix for this issue in #1581. However, we are having trouble reproducing the behavior you described. Would it be possible for you to provide a video of demonstrating this behavior? Thanks!
