### ISSUE TITLE
Issue on Edge and IE11: Token renewal operation failed due timeout: Token Renewal Failed

### ISSUE THREAD

**Issue by chaitanyabhalerao1** [AzureAD/microsoft-authentication-library-for-js#1384]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.2.1`

## Framework
NA
## Security
No
## Regression
Yes, Authentication was working with MSAL on Edge/chrome/IE11 but now timeout is happening on Edge and IE11.  Receives below error in Edge and IE11 consistently.

"Token renewal operation failed due timeout: Token Renewal Failed"

## Configuration
We have added below configuration to increase time out. 
 const msalConfig = {
        auth: {
            clientId: '${b2c_clientid}' ,
            authority: '${b2c_authority}',
            validateAuthority: false,
            redirectUri: '${b2c_nacsredirectui}'            
        },
        cache: {
            cacheLocation: "localStorage",
            storeAuthStateInCookie: true
        },
        system: {
        	loadFrameTimeout: 60000
        }
```js

## Reproduction steps
1. Open the site in Edge/IE11  
2. Provide your Microsoft logins
3. Continuous redirect happening on IE11 due to timeout

## Expected behavior
On IE11 and Edge browser user should redirect to site pages after authentication with MSAL library.

## Browsers2
IE11 and Microsoft Edge

[view.txt](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/4343394/view.txt)

**Comment by jasonnutter** [comment]
@chaitanyabhalerao1 There are known issues with Edge/IE11: https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Known-issues-on-IE-and-Edge-Browser

Have you tried the workarounds detailed above?

**Comment by chaitanyabhalerao1** [comment]
Thank you Jason for quick response!

Yes, we have tried all workarounds specified in the link mentioned but no luck ..Issue is intermittently observed on Edge but consistently on IE11.

FYI,

We are using recommended version of MSAL i.e.  1.2.1 along with this we have also added pre-requisite JS script i.e.e bluebird

[cid:image002.png@01D5FCB1.4298F8B0]

As mentioned in the workaround all required flags are set in the MSAL config
[cid:image005.png@01D5FCB1.4298F8B0]


Also tried Adding all required sites in trusted site still did not work.


Regards,
Chaitanya Bhalerao

**Comment by jasonnutter** [comment]
@chaitanyabhalerao1 It looks like you are using `msal@1.1.2`. Have you tried `1.2.1`?

**Comment by jasonnutter** [comment]
Also, what happened that made it stop working? Did you change versions of MSAL? Or did you change your application code? Or something else?

**Comment by chaitanyabhalerao1** [comment]
Hi Jason,

We tried both the versions of MSAL and currently using 1.2.1.

It is working in chrome ( 80+) and Edge but getting into redirect loop on IE11. It never worked on IE11.

Our application was tested and working for all browser( chrome and edge) but due to user demand we had to make this application compatible for IE11 but MSAL is giving timeout exceptions.

As attached in the ticket , we have provided all the config where we are redirecting the user to dashboard after aquiringtoken but due to exception, user gets into redirection loop.

Thanks in advance!

Regards,
Chaitanya

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jasonnutter** [comment]
@chaitanyabhalerao1 The behavior you describe is expected for IE11 if the application domain (e.g. myapplication.com) and the login authority domain (e.g. login.microsoftonline.com) are in different security zones. Our general guidance is to ensure both domains are in the Trusted Zone. I believe this will need to be done by either the end-user, or a network admin. Can you confirm that putting both domains in the same zone does or does not solve this issue?

**Comment by chaitanyabhalerao1** [comment]
Hi Jason,

Thank you for the response,

Yes we have added the both the sites(login.microsoftonline.com & our application site URL) into Trusted site zone still facing the same issue

[cid:image001.png@01D5FDFA.0D2B4AD0]


Regards,
Chaitanya Bhalerao

**Comment by chaitanyabhalerao1** [comment]
![IE11RedirectIssue](https://user-images.githubusercontent.com/25057664/77049038-63c14e80-69ed-11ea-8d05-bd56c20ce5dc.JPG)

**Comment by pkanher617** [comment]
@chaitanyabhalerao1 Your login authority domain is going to be your b2c authority, not `https://login.microsoftonline.com/`, which is the AAD authority. The B2C authority should be the same one you pass into the MSAL config.

**Comment by pkanher617** [comment]
No response for a while, closing for now. Please let us know if you are still facing this issue.
