### ISSUE TITLE
[msal-common] ScopeSet changes to reflect generality

### ISSUE THREAD

**Issue by sameerag** [AzureAD/microsoft-authentication-library-for-js#1390]
- [ ] `@azure/msal-node@1.x`

## Source
- [ ] Internal (MSAL.js team)

## Description
Modify `ScopeSet.ts` to be more generic to msal-common and not msal-browser specific for certain functionlity

## Priority
In line with `msal-node` library

## Acceptance Criteria
Describe the conditions that must met for this work to be considered complete.

1. Unit tests
2. Generality of this class to apply for SPA and Browser 
3. Sample

**Comment by DarylThayil** [comment]
@sameerag  can you fill a more detailed description so we can add to the appropriate board

**Comment by sameerag** [comment]
This is already added to `msal-node` board. I added more description.
