### ISSUE TITLE
Why guard on acquireTokenSilent broadcasts msal:loginSuccess and not just msal:acquireTokenSuccess?

### ISSUE THREAD

**Issue by oleksii-kostin** [AzureAD/microsoft-authentication-library-for-js#1392]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [X] `@azure/msal-angular@0.x.x`
- [X] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
In my application I need to know when user simply reloads page (by typing url into the browser, in my specific case), and when he logins. On [npm page](https://www.npmjs.com/package/@azure/msal-angular#4-subscribe-to-event-callbacks) it states that `msal:loginSuccess` should be broadcasted in case of `loginPopup()/loginRedirect`. But msal-guard.service.ts broadcasts `msal:loginSuccess` after `acquireTokenSilent` function.

In my case, user types url, and angular navigate him to the page. `msal-guard.service.ts` does his check, get token silently, broadcasts `msal:loginSuccess`, and I dont know if user just was redirected from login page, or he simply pasted url.

Why it has such behavior, and is there a way to know when user simply reloads page, and when he comes from login page?

**Comment by jasonnutter** [comment]
@oleksii-kostin When the MSAL Guard calls `acquireTokenSilent`, it is doing so to get an ID token, which is essentially verifying that the user is indeed logged in (as this call would fail if they no longer have an AAD session). I understand why this is confusing, and have considered changing this behavior (or changing the broadcasted event to differentiate it).

You can determine whether or not the user was already logged in by looking at the `fromCache` property of the `AuthResponse` object that is broadcasted. If the value is `true`, that means the user was already logged in.

**Comment by jasonnutter** [comment]
And yeah I also see how it confusing the `acquireTokenSilent` in the guard broadcasts both `acquireTokenSuccess` and `loginSuccess`.

**Comment by cristofercri** [comment]
> @oleksii-kostin When the MSAL Guard calls `acquireTokenSilent`, it is doing so to get an ID token, which is essentially verifying that the user is indeed logged in (as this call would fail if they no longer have an AAD session). I understand why this is confusing, and have considered changing this behavior (or changing the broadcasted event to differentiate it).
> 
> You can determine whether or not the user was already logged in by looking at the `fromCache` property of the `AuthResponse` object that is broadcasted. If the value is `true`, that means the user was already logged in.

I didn't realize the MSAL Guard was calling acquireTokenSilent (which makes perfect sense :)). Thanks for letting us know.
