### ISSUE TITLE
Redirect response object sets idTokenClaims to the idToken property.

### ISSUE THREAD

**Issue by EricForgy** [AzureAD/microsoft-authentication-library-for-js#1396]
## Library
- [x] `msal@1.2.1`

## Framework
React v16

## Description

I create a new MSAL instance and console.log the response in my `handleRedirectCallback` and I can see a property:

```js
response = {
    account: {
        idToken: someIdTokenClaimsObject,  # Duplicate - should be someIdTokenObject not Claims.
        idTokenClaims: someIdTokenClaimsObject
}
```

## Security
Is this issue security related?

I don't think so.

## Regression
Did this behavior work before?

I don't think so.

## Configuration
Please provide your MSAL configuration options.

```js
{
    auth: {
        clientId: "blah",
        authority: "https://blah.b2clogin.com/blah.onmicrosoft.com/B2C_1_signupsignin",
        validateAuthority: false,
        redirectUri: "http://localhost:3000",
        postLogoutRedirectUri: "http://localhost:3000"
    },
    cache: {
        cacheLocation: "sessionStorage",
        storeAuthStateInCookie: false
    }
}
```

## Reproduction steps
1. Create a new MSAL instance
2. Console.log the response in handleRedirectCallback

## Expected behavior

I expect to see:

```js
response = {
    account: {
        idToken: someIdTokenObject,
        idTokenClaims: someIdTokenClaimsObject
}
```

It looks like instead of populating `idToken` with an id token object, it is populating it with a duplicate of the id token claims object.

It is not the end of the world, but noticed this when setting up some mobx-state-tree stores.

## Browsers
Is this issue browser-specific? No.

**Comment by tnorling** [comment]
This is expected behavior as the idToken field is being deprecated. It still exists for the time being for backwards compatibility.
See PR #804

**Comment by EricForgy** [comment]
Cool. Ok. Thank you :)

I'll setup MST to just grad the claims 👍
