### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present - CORS

### ISSUE THREAD

**Issue by LonBoy98** [AzureAD/microsoft-authentication-library-for-js#1398]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
If you are using a framework, please provide the framework and version (e.g. Angular v8, React v16, etc).

## Description
I try to get information from Office 365 Service Communications API (Messages --> https://manage.office.com/api/v1.0/contoso.com/ServiceComms/Messages)
But when i rebuild you documentation i get an CORS error.

I am also wondering because my "response.accessToken" is always emtpy?!
I hope you can help me 

## Security
Is this issue security related?

## Regression
Did this behavior work before?

## Configuration
Please provide your MSAL configuration options.

```js
<!DOCTYPE html>
<script type="text/javascript" src="https://alcdn.msauth.net/lib/1.2.0/js/msal.js" integrity="sha384-LSjD9o5MhT3UejOHZ5BJrlAp3TxNM6z68DPYw3o7Q3ApJviS9kOGP0oQyTaJJd9O" crossorigin="anonymous"></script>
<script type="text/javascript" src="https://alcdn.msauth.net/lib/1.2.0/js/msal.min.js" integrity="sha384-bUAfT3zjpyf+nuTqeGYWk7ZKN6E89ouvkiXth6G45RG55uQERls6TtStVOBM6v4O" crossorigin="anonymous"></script>

<html lang="en">
<script type="text/javascript">
var global;
const msalConfig = {
        auth: {
            clientId: 'XXXXX-XXXX-XXXX-XXXX-XXXXXXXX'
        }
    };

    const msalInstance = new Msal.UserAgentApplication(msalConfig);

    msalInstance.handleRedirectCallback((error, response) => {
        // handle redirect response or error
    });
	
	var loginRequest = {
       scopes: ["user.read", "mail.send"] // optional Array<string>
   };

    msalInstance.loginPopup(loginRequest)
        .then(response => {
            // handle response
        })
        .catch(err => {
            // handle error
        });
	
	    // if the user is already logged in you can acquire a token
    if (msalInstance.getAccount()) {
        var tokenRequest = {
            scopes: ["user.read", "mail.send"]
        };
        msalInstance.acquireTokenSilent(tokenRequest)
            .then(response => {
				
                // get access token from response
                //response.accessToken
				debugger;
					var headers = new Headers();
					var bearer = "Bearer " + response.accessToken;
					headers.append("Authorization", bearer);
					var options = {
						 method: "GET",
						 headers: headers
					};
					var graphEndpoint = "https://manage.office.com/api/v1.0/XXXXXXXX.com/ServiceComms/Messages";

					fetch(graphEndpoint, options)
						.then(resp => {
							 //do something with response
						});
            })
            .catch(err => {
                // could also check if err instance of InteractionRequiredAuthError if you can import the class.
                if (err.name === "InteractionRequiredAuthError") {
                    return msalInstance.acquireTokenPopup(tokenRequest)
                        .then(response => {
                            // get access token from response
                            // response.accessToken
                        })
                        .catch(err => {
                            // handle error
                        });
                }
            });
    } else {
        // user is not logged in, you will need to log them in to acquire a token
    }
	


</script>
</html>
```

## Reproduction steps
1. 
2. 
3. 

## Browsers
Is this issue browser-specific? If so, please detail which browsers are impacted (e.g. IE 11, Safari).

**Comment by jasonnutter** [comment]
@LonBoy98 You are receiving this error when making the fetch request to `https://manage.office.com`, correct? If so, that means that `https://manage.office.com` has configured to disallow cross-origin requests, which means you will not be able to make this request client-side, and instead will need to make this request server-side.

**Comment by LonBoy98** [comment]
> @LonBoy98 You are receiving this error when making the fetch request to `https://manage.office.com`, correct? If so, that means that `https://manage.office.com` has configured to disallow cross-origin requests, which means you will not be able to make this request client-side, and instead will need to make this request server-side.

But how? Am i able to add addresses to the CORS-Policy on azure? Because i want to execute this call via JavaScript from a html page on a PRTG-Server and i dont know how i can do this request server-side.

**Comment by jasonnutter** [comment]
@LonBoy98 Sorry for the delay in responding. I don't believe you can add domains that are allowed to make CORS requests to `manage.office.com`. Your client-side javascript should initiate a fetch request to your server, which then makes a network request to `manage.office.com`. 

Closing, as no further action for the library.
