### ISSUE TITLE
Error adding MsalModule to app.module

### ISSUE THREAD

**Issue by mylle** [AzureAD/microsoft-authentication-library-for-js#1400]
## Library
- [x] `msal@^1.2.1`
- [x] `@azure/msal-angular@^1.0.0-beta.4`

## Framework
Angular 9

## Description
I Just started a new 'ng new' Angular project and want to implement MSAL.
I followed the steps (npm install, and msalModule.forroot()) but then i'm already getting lots of errors:
```
imports: [
    MsalModule.forRoot({
      auth: {
          clientId: "Your client ID"
      }
    }),
```
Am I doing something wrong?

## Reproduction steps
1. ng new
2. npm i @azure/msal-angular
3. add msalModule to imports[]

**Comment by jasonnutter** [comment]
@mylle Can you please include the error messages you are getting?

For Angular 9, `MsalModule.forRoot` may not work with Ivy. Instead, try using a factory, which is demonstrated in the Angular 9 sample: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/angular9-sample-app/src/app/app.module.ts

**Comment by mylle** [comment]
@jasonnutter, this is the error i'm getting:
![image](https://user-images.githubusercontent.com/18067020/77292872-6e2b6300-6ce1-11ea-8a98-bd4221ea024a.png)

The factory way works, thanks for that! 
Can I find any documentation about this? (I'm still finding my way in Angular)

**Comment by jasonnutter** [comment]
@mylle You can read more about FactoryProviders here: https://angular.io/api/core/FactoryProvider

We'll have this noted in our documentation as well.
