### ISSUE TITLE
angular-msal 1.0.0 with angular 8 , msal-loginSuccess broadcast event fires twice

### ISSUE THREAD

**Issue by llakhani** [AzureAD/microsoft-authentication-library-for-js#1405]
Hi,
I'm using angular msal 1.0.0 , I'm getting this broadcast service msal:loginSuccess. 
I have functionality like on successful login i want to call my web API (so Should I do on loginSuccess or redirecthandlecallback) ?
I'm getting msal:loginSuccess event twice. What can be issue?
I have lazy loading for routing and for every path I need to check for login or not, so i added msalGuard in app routing . Is it ok?

**Comment by jasonnutter** [comment]
Closing as duplicate of #1404
