### ISSUE TITLE
AuthError object is empty when loginRedirect() fails

### ISSUE THREAD

**Issue by BenjaminBorlet** [AzureAD/microsoft-authentication-library-for-js#1406]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.2.2.beta.3`
- [x] `@azure/msal-angular : 1.0.0-beta.4`

## Framework
Angular 9

## Description
The login workflow work fine using popUp workflow, but does not trigger loging and AuthError object if I use redirect workflow (i.e. loginRedirect())
## Security
No

## Configuration
Please provide your MSAL configuration options.

```js
function MSALConfigFactory(): Configuration {
  return {
    auth: {
      clientId: 'xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx',
      authority: 'https://login.microsoftonline.com/xxx.xxx.xxx',
      validateAuthority: true,
      redirectUri: 'http://localhost:4200/',
      postLogoutRedirectUri: 'http://localhost:4200/login',
      navigateToLoginRequestUrl: true
    },
    cache: {
      cacheLocation: 'localStorage',
      storeAuthStateInCookie: false // set to true for IE 11
    }
  };
}

function MSALAngularConfigFactory(): MsalAngularConfiguration {
  return {
    popUp: false,
    unprotectedResources: ['https://www.microsoft.com/en-us/'],
    extraQueryParameters: {}
  };
}
```

## Reproduction steps
1. Clone this repo
2. change popUp option to false
3. use       this.authService.loginRedirect(); instead of popUp in app.component.ts

## Expected behavior
All the log should appear in the same way with popUp or with redirect workflow
## Browsers
I only tested it on chrome last version

**Comment by jasonnutter** [comment]
@BenjaminBorlet Are you referring to the broadcast events?

**Comment by BenjaminBorlet** [comment]
`
this.authenticationService.handleRedirectCallback((authError, response) => {
      if (authError) {
        console.error('Redirect Error: ', authError.errorMessage);
        //authError is emtpy with redirect workflow
        return;
      }

      if (!response.account) {
        console.error(
          this.authenticationService
            .getCacheStorage()
            .getItem('msal.error.description')
//But here i get the correct value in the cache storage
        );
      }
    });
`

**Comment by tnorling** [comment]
@BenjaminBorlet Fixes for ```handleRedirectCallback``` were included in ```msal@1.3.0-beta.1``` and ```@azure/msal-angular: 1.0.0-beta.5``` Can you try upgrading your msal version and let us know if this issue is resolved?

**Comment by tnorling** [comment]
`msal@1.3.0` has been released and should fix this issue. Let us know if you're still having issues.

**Comment by BenjaminBorlet** [comment]
Hi ! I had time to test it today, unfortunately the authError is still empty when using the redirect workflow (customer requirement).

I tried a login with wrong credentials on `msal@1.3.0-beta.1` with `@azure/msal-angular: 1.0.0-beta.5`

**Comment by tnorling** [comment]
@BenjaminBorlet I believe I found the root cause of this. I'll put up a PR shortly to address.

**Comment by BenjaminBorlet** [comment]
@tnorling should i check on my side with your changes before you merge the PR ?

**Comment by tnorling** [comment]
@BenjaminBorlet Yes please do! That would be much appreciated

**Comment by BenjaminBorlet** [comment]
I got an authError with everything I need, but now the response object is undefined :') I could work for me but now you know !
