### ISSUE TITLE
MSAL for Angular: support for multi-tenant login with non-default tenant

### ISSUE THREAD

**Issue by antonGritsenko** [AzureAD/microsoft-authentication-library-for-js#1408]
## Library
- [x] `@azure/msal-angular@1.0.0-beta.2`

## Description
We try to implement standard multi-tenant authentication, which works pretty well. Now we going to next step: choose the target tenant. Each user can have more than one tenant attached to they account, one default tenant and unlimited number of other. When you using the multi-tenant authentication, you must use **/common** endpoint, so the default tenant will be used. With C# MSAL SDK we can authenticate against /common, then load list of tenants (show this list to user) and then silently login to required tenant (actually just get a new token for this tenant).

Is this possible with MSAL for Angular? The authority is defined on the module level, so I don't see a way how to handle such cases.

**Comment by jasonnutter** [comment]
@antonGritsenko Can you link me to the documentation showing how to get this list of tenants? I'm not familiar with how that's done in C#. Thanks!

**Comment by antonGritsenko** [comment]
@jasonnutter  There is nothing special, just calling to the management API (this is for Angular for sure :) )
```

export const AzureManagementUrl = "https://management.azure.com";
...
getTenants(){
    return this.http.get(AzureManagementUrl + '/tenants?api-version=2017-08-01');
  }
```

**Comment by jasonnutter** [comment]
@antonGritsenko Ah, yes, you should be able to request an access token that can be used with Azure Resource Management. Search for "Azure Service Management" under "Add a Permission" in the "API Permissions" for your app. Then you can add that scope to your `consentScopes` and `protectedResourceMap`.

**Comment by antonGritsenko** [comment]
ok, so we have to use UserAgentApplication directly. Then no make sense to use @azure/msal-angular at all, right? :)

**Comment by jasonnutter** [comment]
@antonGritsenko This may be possible directly with Angular but I haven't had a chance to figure out the best approach. I can follow up when I get a chance to do so.

**Comment by jasonnutter** [comment]
This should now be possible in MSAL Angular v2, which allows you to update the instance of MSAL dynamically (e.g. with a new authority). Please try that out and let us know if you have any feedback.
