### ISSUE TITLE
MSAL doesn't work in conjunction with oidc client .js

### ISSUE THREAD

**Issue by poctob** [AzureAD/microsoft-authentication-library-for-js#1412]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.2.1` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.0.0-beta.4"`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
Angular 9

## Description
When mixing oidc-client.js and msal, msal intercepts callbacks from oidc-client and redirects to the homepage. 

Happening here:
```
function UserAgentApplication(configuration) {
...
if (urlContainsHash && !WindowUtils.isInIframe() && !WindowUtils.isInPopup()) {
            this.handleAuthenticationResponse(urlHash);
        }
}
```
Since oidc response contains token hash, this function intercepts it every time. 
Typical use case would be to secure some routes using one auth provider with oidc-client.js and some routes using azure ad with msal.

## Security
No

## Regression
Yes

## Configuration
Please provide your MSAL configuration options.

N/A

## Reproduction steps
1. Add MsalModule to the application.
2. Add oidc-client.
3. Authenticate with a server using oidc-client.
4. Observe redirect to the homepage and failure to complete authentication.

## Expected behavior
msal does not intercept all routes containing token hash.

## Browsers
Not browser specific

**Comment by DarylThayil** [comment]
Unfortunately supporting running alongside other authentication libraries is not supported by this library. Closing this issue.
