### ISSUE TITLE
Window.Opener Check Stops Authentication Process

### ISSUE THREAD

**Issue by mindingdata** [AzureAD/microsoft-authentication-library-for-js#1417]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
I'm not really sure if this is a bug request or feature request, but I logged it under a bug request anwyay. 

In short, I've been having issues whereby I'm using a Headless CMS that has a button to open a website. It uses window.open to open a new tab to view content (my site). The source code of which is here : https://github.com/Squidex/squidex/blob/master/frontend/app/features/content/shared/preview-button.component.ts#L77

What I noticed was that if I wasn't logged in, that it would try and authenticate me but simply bomb out at some point because it was stuck in a state of "LoginInProgress" (I could see this in LocalStorage) and wouldn't go further. If I opened a new window to the same link, everything would go fine. 

I checked what kicked off the handling of the hash when being redirected back to the site (I'm using Redirect auth not popup), and saw a particular interesting line : https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/src/UserAgentApplication.ts#L240

```
if (urlContainsHash && !WindowUtils.isInIframe() && !WindowUtils.isInPopup()) {
	this.handleAuthenticationResponse(urlHash);
}
```

Notably the isInPopup line. I went and checked the WindowUtils code and found : https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/src/utils/WindowUtils.ts#L29

```
static isInPopup(): boolean {
	return !!(window.opener && window.opener !== window);
}
```

So basically if the window.opener is set, and the window.opener is not the same as the current window, we are in a "popup". 

I figured this must be about a specific way of opening a window but when I check the documentation https://developer.mozilla.org/en-US/docs/Web/API/Window/opener

>using window.open(), or by a link with target attribute set

So if I'm reading that right, target="_blank" would also cause issues? 

Unless there is a very strict security reason for this to be in place, I think it should be removed as anyone linking to the site even using target="_blank" will have their auth stalled out and not able to continue. 

If I'm wrong in my thinking and there is a way to bypass this check (Even from the CMS' side), I'm happy to log a ticket there to change it too. 

## Reproduction steps
1. Create any site protected by MSAL using Redirect Auth. 
2. Use window.open or target="_blank" to link the site. 
3. Click on link/use window.open to open site when *not* already authenticated, and auth will stall out. 

## Expected behavior
Auth should continue regardless of the opener.

**Comment by jasonnutter** [comment]
This is a known issue, and there is an open PR that will address it: #1413 

Closing as a duplicate.

**Comment by mindingdata** [comment]
Sorry to comment/reopen this @jasonnutter , but probably better here than on that PR. Is there a workaround until then? Any way to monkey patch the isPopup method or similar? Any way to call process ourselves?

**Comment by jasonnutter** [comment]
@mindingdata I believe setting `window.opener = null` will fix.
