### ISSUE TITLE
Replacing the version 0.1.2 with 0.1.1 does not work in sample application

### ISSUE THREAD

**Issue by ArunMudiraj** [AzureAD/microsoft-authentication-library-for-js#142]
I am trying to use the latest version on msal.js updated from 0.1.1 
to    <script src="https://secure.aadcdn.microsoftonline-p.com/lib/0.1.2/js/msal.min.js"></script> 
In sample application.

Now I do not get the popup for signin.. can you please let me know if api has changed.

Sample used
https://github.com/Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi-v2 

Thanks,
Arun

**Comment by btitular** [comment]
I'm getting the same behavior - no login popup when using the link:
<script src="https://secure.aadcdn.microsoftonline-p.com/lib/0.1.2/js/msal.min.js"></script>

**Comment by btitular** [comment]
Figured out the problem. The the loginPopup method is expecting a scopes parameter. Once I provided a valid parameter value, the loginPopup window appeared as expected.

**Comment by rohitnarula7176** [comment]
@btitular @ArunMudiraj Thank you pointing out this issue. Please pass an array to loginPopup as loginPopup([clientId]) or loginPopup([scopes]) to resolve this issue. I have fixed this issue in the dev branch. We will add clientId as default scope for loginPopup for the next release.
