### ISSUE TITLE
Interface for UserAgentApplication

### ISSUE THREAD

**Issue by whung1** [AzureAD/microsoft-authentication-library-for-js#1427]
## Library
- [x] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Would like to see an interface for UserAgentApplication, since my team is writing a React Context that is shared that will have msal user agent app injected. We had experience with some contract breaking in the past, and would prefer our TS to error appropriately if the contract is not fulfilled.

UserAgentApplication is a TS file already, but it's simply a class. 
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/src/UserAgentApplication.ts

**Comment by jasonnutter** [comment]
@whung1 This is reasonable request, and something we can definitely consider.

**Comment by jasonnutter** [comment]
This was implemented in MSAL.js v2, closing.
