### ISSUE TITLE
Working with Safari

### ISSUE THREAD

**Issue by MathieuDWeill** [AzureAD/microsoft-authentication-library-for-js#1430]
When will msal 2.0 be released? and will it work successfully with safari?

**Comment by jmckennon** [comment]
@MathieuDWeill we released the [msal 2.0 beta](https://www.npmjs.com/package/@azure/msal-browser) on both npm and CDN yesterday. I will let @pkanher617 comment on it's use with Safari/ITP, as I'm unsure of what we've landed on.

**Comment by jmckennon** [comment]
I was able to talk to @pkanher617 about this, and it will solve ITP in most scenarios for 2.0 release, and we will have more details and documentation regarding the edge cases soon.

**Comment by jmckennon** [comment]
@pkanher617 reminder for docs for ITP as well

**Comment by NerdyB713** [comment]
@jmckennon Do you know when msal/angular 2.0 will be released? Looking for the ITP solution.

**Comment by tnorling** [comment]
@NerdyB713 Msal 2.0 is currently in beta. Angular updates to 2.0 currently do not have an ETA. You can track this ticket for updates on MSAL 2.0 #1000
