### ISSUE TITLE
Align on one of Webpack / Rollup in the library

### ISSUE THREAD

**Issue by DarylThayil** [AzureAD/microsoft-authentication-library-for-js#1432]
Please follow the issue template below.

## Source
- [x] Internal (MSAL.js team)
- [ ] Customer request

## Description
We currently have both rollup and webpack in our libs, along with whatever the node library is currently using with tsdx. 

## Priority
Medium ?

## Acceptance Criteria
Describe the conditions that must met for this work to be considered complete.

1.  One bundling manager 
2.  Choice takes bundle size, project popularity / maintenance, and feature support into account (esmodules?)

**Comment by DarylThayil** [comment]
@jasonnutter   @pkanher617  cc

**Comment by jasonnutter** [comment]
Given the different libraries have different considerations for bundling, I'm not sure this will be realistic. Closing for now.
