### ISSUE TITLE
Doesn't create token for APIs which has same path key in URL as present in app-routing.module.ts

### ISSUE THREAD

**Issue by vinusorout** [AzureAD/microsoft-authentication-library-for-js#1438]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework
Angular 9

## Description
I have multiple APIs which are listening on different ports like 3000, 3001, 3002 on localhost.
Also i have provided the azure id in protected resources like:

```javascript
export const protectedResourceMap:[string, string[]][]= [
    ['http://localhost:3000', [ 'xxxxxxxx/.default' ]],
    ['http://localhost:3001', [ 'xxxxxxxx/.default' ]],
    ['http://localhost:3002', [ 'xxxxxxxx/.default' ]]
];
```
*NOTE: 'xxxxxxxx/.default' is same for all APIs

But msal creates token for only one call which occurs first and for other it says 
Tue, 31 Mar 2020 10:55:23 GMT:c3e6d717-0999-4561-b902-edff36ae88cc-1.2.2-Verbose Url: http://localhost:3002/xyg/abc/1 maps to scopes: null

Tue, 31 Mar 2020 10:55:23 GMT:c3e6d717-0999-4561-b902-edff36ae88cc-1.2.2-Verbose Url: http://localhost:3001/tru/fyg/1 maps to scopes: null

## Msal configurations

```javscript
cost configuration = {
        auth: {
            clientId: 'xxxxxxxx',
            authority: https://login.microsoftonline.com/company_authprity_id,
            redirectUri: 'http://localhost:4200/'
        },
        cache: {
            cacheLocation: 'localStorage',
        }
}



const msalAngularConfiguration = {
               unprotectedResources: [],
               protectedResourceMap:  [
    ['http://localhost:3000/', [ 'xxxxxxxx/.default' ]],
    ['http://localhost:3001/', [ 'xxxxxxxx/.default' ]],
    ['http://localhost:3002/', [ 'xxxxxxxx/.default' ]]
]
}
```

## Expected behavior
Each localhost should have their own mapping of scope, and msal should create token for all the API calls.

**Comment by vinusorout** [comment]
Following is the root cause:

You guys add all the path variables which are set in app-routing.module.ts, to unprotectedResources,

```javascript
this.router.events.subscribe(event => {
            for (var i = 0; i < router.config.length; i++) {
                if (!router.config[i].canActivate) {
                    if (this.msalAngularConfig.unprotectedResources) {
                        if (!this.isUnprotectedResource(router.config[i].path) && !this.isEmpty(router.config[i].path)) {
                            this.msalAngularConfig.unprotectedResources.push(router.config[i].path);
                        }
                    }
                }
            }
        });
```

Now, if someone has same path key in their APIs url, then your module thinks that it is an unprotected resource and doesnt create token for that API url.

In my case in app-routing.module.ts I have path specified as "xyg" and "tru", and also these same paths are part of my API urls:
http://localhost:3002/xyg/abc/1
http://localhost:3001/tru/fyg/1 

Pl let me know if there is any way to avoid this!

**Comment by jasonnutter** [comment]
@vinusorout What happens if you don't provide `unprotectedResources`?

**Comment by vinusorout** [comment]
> @vinusorout What happens if you don't provide `unprotectedResources`?

Yes, this would work. 
But once I need to make an API unprotected then again this will be a issue.

**Comment by lordtct** [comment]
I have an issue with `unprotectedResources` matching fragments of `protectedResourceMap` URL fragments. In my case a route entry "500" matched a URL entry "https://localhost:5000".

Would suggest changing the following (msal.service.ts:76) from:
`return unprotectedResources.some(resource => url.indexOf(resource) > -1);`

to:
`return unprotectedResources.some(resource => url.startsWith(resource) > -1);`

**Comment by jnssn** [comment]
> I have an issue with `unprotectedResources` matching fragments of `protectedResourceMap` URL fragments. In my case a route entry "500" matched a URL entry "https://localhost:5000".

I'm having a similar issue where an endpoint ("https://localhost:5001/api/confirm") and an Angular route ("confirm") are causing the MsalInterceptor to send the request without a token.

> Would suggest changing the following (msal.service.ts:76) from:
> `return unprotectedResources.some(resource => url.indexOf(resource) > -1);`
> 
> to:
> `return unprotectedResources.some(resource => url.startsWith(resource));`

This seems like the correct solution. Currently, all angular routes are added to the unprotectedResources array. Having a route called "graph" in your Angular app breaks the example  protectedResourceMap (["https://graph.microsoft.com", ["user.read"]])

> Verbose Url: https://graph.microsoft.com/1.0/me maps to scopes: null

**Comment by jakehockey10** [comment]
I didn't know if this warrants another ticket as it looks like there are 1 or two that are similar to this.  But my routes in angular don't match the API urls whatsoever.  It is actually an issue for me, because I'm lazily loading feature modules.  What is really weird about my issue is that api urls seem to be being added to the unprotectedResources array only sometimes.  For example, if Angular, from within a lazily loaded feature module make a request to, for example, /api/roles/APP:ADMIN/users, the auth token is added to this request.  But if the same method makes a request to /api/roles/app:admin/users, the auth token is NOT added to the request.  The order in which I make this requests does not matter.  It seems that case sensitivity is somehow involved here.

Disclaimer, we are also trying to get away from allowing roles that are the same except for case, but that is still besides the point.  I think this is a bug.

**Comment by jakehockey10** [comment]
nulling out the unprotectedREsources in my config seems to have fixed the issue as well.  But if I needed something in that array, I'm not sure how to overcome this issue.
