### ISSUE TITLE
GetUser must be called prior to AcquireTokentSilent

### ISSUE THREAD

**Issue by davidmorissette** [AzureAD/microsoft-authentication-library-for-js#144]
Hi,

I am using MSAL 0.1.2 in order to get a token from B2C using _loginRedirect_. That works fine.

On subsequent calls, when I try to get the token from cache using _acquireTokenSilent_ I get this error: user_login_error:User login is required.

I looked into your code and noticed that whether the global _user variable must already be assigned (by calling _getUser_) or a user object should be passed as a parameter when calling the function in order for it to succeed.

According to the documentation:
@param {User} user - The user for which the scopes are requested. The default user is the logged in user.

My suggestion:

The logged in user should be figured out internally by the _acquireTokenSilent_ function and calling _getUser_ prior to calling that function should not be required. The current design is not intuitive and does not respect the single responsibility principle.

Thank you!

**Comment by joanjane** [comment]
Same here since 0.1.2. It took me some time to figure out what was happening because I have referenced msal expecting semantic versioning (^0.1.1). 

I'm frozing the version right now to ensure no unexpected breaking changes.

In my case, after user logs in successfully, `acquireTokenSilent` **fails** with the same error and redirects to login page on B2C. If you go back to your authenticated page, it doesn't prompts you to login because it already has the token stored.

I hope it can be fixed soon.

Thanks!

**Comment by rohitnarula7176** [comment]
@davidmorissette The user property(this._user) gets set when we receive an idtoken response as a result to calling loginRedirect. Any call to acquireTokenSilent after you call login should have the logged in user property set already without a need to call getUser(). Can you please provide a code repro for this issue so I can look into this further?

**Comment by davidmorissette** [comment]
@rohitnarula7176 Yes the user property (this._user) stays set **as long as the application does not perform any subsequent redirects**. In that case, the values (tokens, etc.) are still available from the storage but this._user is null again and calling getUser() is required in order to assign this._user.

I didn't try but I think every places in your code doing this:
const userObject = user ? user : this._user;

Should be replaced with this:
const userObject = user ? user : this.getUser();

Do you still need a code repro?

Thank you!

**Comment by davidmorissette** [comment]
@joanjane You need to call getUser() right before you call acquireTokentSilent() if you want your code to work until the team here finds a better solution. This is how I fixed my code.

**Comment by rohitnarula7176** [comment]
@davidmorissette @joanjane Thank you for pointing out this issue. Can you please use the dev branch and see if it resolves your issue.

**Comment by davidmorissette** [comment]
In my case YES I confirm it resolves the issue. Thank you!

**Comment by joanjane** [comment]
@davidmorissette @rohitnarula7176 Thanks for your response, it solved my issue too.
