### ISSUE TITLE
Is there any way to renew `sid` silently?

### ISSUE THREAD

**Issue by winperec** [AzureAD/microsoft-authentication-library-for-js#1445]
## Library
- [x] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
We use silent sign-in and 'sid' parameter instead of `login_hint`. 
Reason: some of our clients have ADFS and mixed authentication and with `login_hint` we get 

*`AADSTS50058: A silent sign-in request was sent but none of the currently signed in user(s) match the requested login hint when inviting external users using alias`*

All works fine with `sid` but when the session expires we need to renew access tokens and `sid` as well. to renew `sid` we run normal login redirect and update `id_token`, which is not best from UX point of view. 
**Is there any way to renew `sid` silently?** 
I know there are methods allow renewing tokens(`id_token`) silently but they require `login_hint` or `sid` in our case `login_hint` doesn't work, `sid` is staled

I see #1166 may be it is related...

**Comment by jmckennon** [comment]
If the user's session with AAD has expired, then the user has to sign in interactively and it is not possible to do this silently.

**Comment by winperec** [comment]
ok this is something I expect :) and what is the lifetime of `sid` I assume it should be longer then access_token lifetime.

**Comment by tnorling** [comment]
@winperec This [doc](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes) suggests AAD sessions are valid for 24 hours and get renewed each time the session token is used within its validity period.

Closing this issue but feel free to reopen if you have follow up questions.
