### ISSUE TITLE
Msal-Angular@1.0.0.beta.4 for Custom B2C policies. LoginRedirect() does nothing but refresh. 

### ISSUE THREAD

**Issue by charles-chen-wtw** [AzureAD/microsoft-authentication-library-for-js#1446]
# Library 
msal-angular@1.0.0.beta.4
@angular @ 8.2.14

# Problem
My Angular Single Page App try to let the user login to our b2c tenant using a custom policy. 
When the authority is set to :
`https://login.microsoftonline.com/common/` --> loginRedirect() somtimes needs to click multiple times to get the redirect. 

When the authority is set to :
`http://{tenant}.b2clogin.com/{tenant}.onmicrosoft.com/{policy_name}`
`http://{tenant}.b2clogin.com/tfp/{tenant}.onmicrosoft.com/{policy_name}`

Neither of these will redirect to login page. 

When I debug, it did go through:

`acquireTokenInteractive()`
`acquireTokenHelper()`
`resolveEndpointsAsync()`

Then no luck from there. 

Please advice and help. Thank you very much.

**Comment by tnorling** [comment]
@charles-chen-wtw Can you share more information about your ```auth``` configuration? Are you setting ```validateAuthority: false``` when using your b2c authority?

**Comment by tnorling** [comment]
Closing. Let us know if this is still an issue.
