### ISSUE TITLE
MsalGuard constructs incorrect redirectStartPage when HashLocationStrategy is used

### ISSUE THREAD

**Issue by Ivan-L** [AzureAD/microsoft-authentication-library-for-js#1447]
## Library
- [X] `@azure/msal-angular@1.0.0-beta.4`

## Framework
Angular v7.

## Description
PR #1343 introduced the `redirectStartPage` field in `AuthenticationParameters` and the `MsalGuard` started using it in order to preserve the Angular route being hit when redirecting. This was great!

Unfortunately this does not work when an Angular app such as ours uses `HashLocationStrategy` by setting the `useHash` field to `true` in the root router module. For completeness, this is our router module configuration:
```ts
RouterModule.forRoot(
  routes,
  {
    enableTracing: false,
    paramsInheritanceStrategy: 'always',
    useHash: true
  }
)
```

When the `MsalGuard` constructs the `routePath` on [this line](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/06e879cf0b4eb07c6d4408934dceadf08352f296/lib/msal-angular/src/msal-guard.service.ts#L41), the hash is not included.
For example, when the route is meant to be the following:
```
http://localhost:4200/#/path/to/secure/route
```
What actually gets constructed is:
```
http://localhost:4200/path/to/secure/route
```
This is because `window.location.origin` is `http://localhost:4200` and `state.url` is `/path/to/secure/route`. The `/#` in between the two is missing.

I am trying to find out what the best way is to safely construct the full URL to the current route irrespective of whether `PathLocationStrategy` or `HashLocationStrategy` is used in an Angular app. I thought I would post this issue in the meantime in case you already know the answer @jasonnutter.

## Configuration
This issue is not dependent on the MSAL configuration but is instead dependent on setting `useHash` to `true` on the root Angular routing module as above.

## Expected behavior
When using `HashLocationStrategy`, deep-linking to a route protected by the `MsalGuard` should cause the correct `redirectStartPage` to be constructed, with the hash in the URL.

**Comment by Ivan-L** [comment]
So it seems I keep on running into hurdles with the `HashLocationStrategy` usage in our Angular app. I'll start with the good news first, but there is bad news at the end.

###  The good news
I did find a good fix for the current issue (pending your scrutiny, of course). Here are the details.
Instead of concatenating `window.location.origin` with `state.url` to get the `redirectStartPage`, `window.location.origin` can be concatenated with `this.location.prepareExternalUrl(state.url)` instead where `this.location` refers to the `Location` class in `@angular/common` which was already being injected in the `MsalGuard` constructor. Here are the docs for [prepareExternalUrl](https://angular.io/api/common/Location#prepareExternalUrl).

When using `HashLocationStrategy`, the `prepareExternalUrl(state.url)` call returns:
```
#/path/to/secure/route
```
When using `PathLocationStrategy`, the same call returns:
```
/path/to/secure/route
```
Because in the one case there is no leading `/` and in the other case there is, I wrote the following helper function which could be moved into `UrlUtils`:
```ts
private combineUrl(baseUrl: string, relativePath: string): string {
  return relativePath
    ? baseUrl.replace(/\/+$/, '') + '/' + relativePath.replace(/^\/+/, '')
    : baseUrl;
}
```
So [the line](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/06e879cf0b4eb07c6d4408934dceadf08352f296/lib/msal-angular/src/msal-guard.service.ts#L41) referred to in the initial issue description would change to:
```ts
const routePath = this.combineUrl(window.location.origin, this.location.prepareExternalUrl(state.url));
``` 
I believe this fix will also solve the case where the `base-href` of the app is not just `/`.

### The bad news
Whilst the above did fix my issue, I ran into another blocker right away. Here is what happens when accessing a deep link into the Angular app in incognito mode:

1. The `http://localhost:4200/#/path/to/secure/route` URL is hit.
2. `MsalGuard` picks up that there is no logged on user, sets the correct `redirectStartPage` and the browser gets redirected to `login.microsoft.com`
3. After entering the correct credentials, a redirect back to `http://localhost:4200/#id_token=&client_info=&state=&session_state=` happens (values omitted) because the `redirectUri` in `MsalConfig` is `http://localhost:4200/`
4. `UserAgentApplication` retrieves the correct (with the above fix) `loginRequestUrl` from storage [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/857ff1f68b4ad9a65703b5b69ed7971fe05dd9e1/lib/msal-core/src/UserAgentApplication.ts#L1061)
5. A redirect happes to `${loginRequestUrl}${hash}` [on this line](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/857ff1f68b4ad9a65703b5b69ed7971fe05dd9e1/lib/msal-core/src/UserAgentApplication.ts#L1070) - dang!
6. The resultant URL ends up having two hashes:
```
http://localhost:4200/#/path/to/secure/route#id_token=&client_info=&state=&session_state=
```
7. `UserAgentApplication` can not parse the correct hash after the redirect and the app goes into limbo

I am not sure how this would be solved and whether an app having hash parameters on `redirectStartPage` which are not MSAL parameters, has been considered. Would this latter issue be more difficult to solve?

**Comment by jasonnutter** [comment]
@Ivan-L I was able to come up with a solution for both problems, see #1452.

**Comment by Ivan-L** [comment]
@jasonnutter Thank you for putting up the PR so quickly!

I tested the app against the branch of #1452 and both issues above are resolved, thanks!

I am just hitting one last issue though, a `Token renewal operation failed due to timeout` error and it is difficult to debug, plus I'm not sure whether it's related to PR #1452 at all or not.

Here is the strange thing and it is very consistent: if I have F12 developer tools open in Chrome everything works fine testing against that branch and the new logic in `UserAgentApplication` is hit where a forced `processCallBack` call [is made](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/2360b47622917af58f308ee8e2323787c5e4cae7/lib/msal-core/src/UserAgentApplication.ts#L1073) before the final redirect to the `loginRequestUrl ` happens. If the F12 developer tools are not open, I get the above error. It looks like the first API call the app makes after the final redirect above, which triggers the  `MsalInterceptor` logic to obtain an access token silently, causes this, but only if F12 developer tools are closed. I checked and do not have any automatic watch expressions being evaluated in the developer tools.

I certainly do not want to hold #1452 up or prevent this current issue #1447 from being closed and if you feel that the app should be starting up again correctly after the final redirect without any side effects from the forced `processCallBack` call just prior to that, then I will diagnose this error separately and open a different issue if needed.

Thanks again!

**Comment by jasonnutter** [comment]
@Ivan-L Which version of `msal` are you using?

**Comment by Ivan-L** [comment]
@jasonnutter "msal": "1.3.0-beta.0"

**Comment by jasonnutter** [comment]
@Ivan-L Gotya. Seems like that is a different issue, so if you could open up a new Github issue, that'd be great (I might also search existing issues, possible there is an open issue). Thanks!

**Comment by Ivan-L** [comment]
@jasonnutter Will do. Thanks for the fixes to the two issues and looking forward to being able to use #1452 in a beta.
