### ISSUE TITLE
Pressing browser back again asking msal login in react

### ISSUE THREAD

**Issue by ranshine** [AzureAD/microsoft-authentication-library-for-js#1448]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.2.1`

I am using this library for azure authentication login in react. After successful login, using react router i am navigating to home page. But in home page if i press browser back button it is again asking azure login. How to stop showing azure page on pressing back or it should do auto login.
Do i need to do any configuration on azure side to do auto login when i press back.

I am doing after successful login
this.props.history.replace("/home")

if i press back it is showing
https://login.microsoftonline.com/xxxxxxxxxxxxxx/oauth2/v2.0/authorize?response_type=token

**Comment by tnorling** [comment]
Thanks @JamesBream for answering this. @ranshine We hope this answers your question.
