### ISSUE TITLE
IE redirects to /null after acquireTokenAsync

### ISSUE THREAD

**Issue by joanjane** [AzureAD/microsoft-authentication-library-for-js#145]
I've been trying to add stable support on IE in a remote environment (azure website) in my app and I've found a bug that redirect to `/null` after authenticating via Azure B2C. I've saw an error _user_login_error:User login is required_ on `acquireTokenAsync ` method.

After reading [this page](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Using-msal.js-with-Internet-Explorer), I've disabled _Protected Mode_ and work pretty well, but I can't ask users to do that.

I'm using v0.1.1 since v0.1.2 has this issue: #144 

Is there a workaround/fix for this issue?

Thanks!

**Comment by rohitnarula7176** [comment]
@joanjane Can you please use the dev branch to see if it resolves your issue.

**Comment by joanjane** [comment]
Hi! I've tested dev branch and made a few changes related to #144. Now /null redirection is gone, the most cases, I have redirects back to B2C after log in on IE.

My flow tries to authenticate directly on my app without using any login button like some examples I've seen, but maybe is having some issues maybe because of a [setTimeout](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/c5aef89abff79539529818c5a2a60eec1b6b9759/lib/UserAgentApplication.ts#L253) on the constructor of msal.

I'm calling acquireTokenSilent at startup, but it seems is not working without wrapping it in a setTimeout.

I have an [example](https://gist.github.com/joanjane/61cbed87ba19ad01c923078704f66f8f) that shows this behavior.

Do you prefer a new issue to talk about this?

Thank you!
