### ISSUE TITLE
AADB2C90273: An invalid response was received : 'Error: interaction_required,Error Description: AADSTS16000: Either multiple user identities are available for the current request or selected account is not supported for the scenario.

### ISSUE THREAD

**Issue by GaddamRajuReddy** [AzureAD/microsoft-authentication-library-for-js#1450]
hi am using "@azure/msal-angular": "^0.1.4", getting below error message while getting token with acquireTokenSilent method. 

AADB2C90273: An invalid response was received : 'Error: interaction_required,Error Description: AADSTS16000: Either multiple user identities are available for the current request or selected account is not supported for the scenario.

**Comment by tnorling** [comment]
Can you confirm if there are multiple accounts currently signed in or if you are providing a login_hint? This error occurs when the library cannot determine which user to acquire the token for. When you get this error please call either ```acquireTokenPopup()``` or ```acquireTokenRedirect()```

**Comment by tnorling** [comment]
Closing as this has been answered. Please reopen if you have follow up questions.
