### ISSUE TITLE
loginRedirect is not working

### ISSUE THREAD

**Issue by roneesh** [AzureAD/microsoft-authentication-library-for-js#1453]
## Library
- [x] `msal@1.2.2`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework
React 16.12

## Description
I am implementing a login redirect auth flow with a specific policy and the loginRedirect method is not working. When I use it in my code, I get an error in console that endpoints could not be resolved. I have double checked my endpoints and I believe they are correct. I have verified that my policy's user flow is working when I click "Run User Flow" in the Azure portal.

NOTE: This specific policy was working when I was using a 0.x.x version of msal. However I am trying to upgrade to the latest version and I am now getting this issue.

## Security
No

## Regression
I believe it worked in the 0.x.x libraries, but I tried it in a few versions and it is not working for me.

## Configuration
this is the config I'm trying to use for my local development environment

```js
      auth: {
        clientId: [redacted],
        redirectUri: 'http://localhost:3000', // this address is configured in Azure Portal as well.
        postLogoutRedirectUri: 'https://[tenant].b2clogin.com/',
        authority:
          'https://[tenant].b2clogin.com/tfp/[tenant.onmicrosoft.com/b2c_1_signin_v2',
      },
      cacheOptions: {
        cacheLocation: 'sessionStorage',
      },

policy being used: B2C_1_signin_v2 | Sign in v2
```

## Reproduction steps
1. Create a new user age in msal with the configuration given above, I am doing it inside an es6 class called "Auth" in a method called "initialize". I an saving the instance to an es6 class property.

```js
  public static initialize() {
    if (this.instance) {
      console.warn(this.MESSAGES.DUPLICATE_INSTANCE);
      return;
    }
    this.instance = new msal.UserAgentApplication(environment.msalConfig);
    this.instance.handleRedirectCallback(Auth.handleRedirectCallback);
  }
// ... further down the class file...
private static handleRedirectCallback(error, response) {
    if (error) {
      console.log('response: ', response);
      console.log('errorMessage: ', error);
      return;
    }
    console.log('response: ', response);
  }
```

2. Call a static class method on the class to login:
```js
  public static login() {
    if (!this.instance) {
      console.warn(this.MESSAGES.NO_INSTANCE);
      return;
    }

    this.instance
      .loginRedirect(environment.msalLoginRequest) // which is { scopes: [scope redacted] }
      .then((response) => {
        console.log('r: ', response);
      })
      .catch((err) => {
        console.log('e: ', err);
      });
  }
```

3. See the error in console that is logged by my handleRedirect method set up in step #1

```js
Error: could not resolve endpoints. Please check network and try again.

And it also returns a response object that is empty:
{
  uniqueId: ""
  tenantId: ""
  tokenType: ""
  idToken: null
  accessToken: ""
  scopes: null
  expiresOn: null
  account: null
  accountState: undefined
}
```

## Expected behavior
I expected to be navigated to the login page that my authority sets up. 

## Browsers
It does not appear to be browser specific.

**Comment by josh-manton** [comment]
I'm also have a similar problem with the code in branch msal-common-known-authorities. I need the new b2c functionality that has not yet been merged into msal v2. 

Pull request here:
https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/1416/files

I believe both libraries share "@azure/msal-common" "1.0.0-beta.0.

@roneesh  check the request that the browser is making in dev tools. Does it look similar to this:

https://login.microsoftonline.com/common/discovery/instance?api-version=1.0&authorization_endpoint=https://TENANT.b2clogin.com/tfp/TENANT.onmicrosoft.com/B2C_1_default-signin

And are you receiving:
{"error":"invalid_instance","error_description":"AADSTS50049: Unknown or invalid instance......

I had the redirect login working in the previous version (msal v1)  and it required that "validateAuthority:false" be set. I'm doing some digging, but I don't think that flag is being respected and it is trying to validate when it should not be, or, some format or parameter has changed.

@tnorling - Am I correct they use the same msal-common? have you put tests in place for this yet?
@sameerag -  I see some of your tests don't include 'tfp'. Thoughts on the issue?

If my issue is different i'll open another ticket with more details.

**Comment by tnorling** [comment]
@roneesh When using B2C in msal v1 you must set ```validateAuthority: false``` in your auth config. This should solve the issue you are experiencing.

@josh-manton msal v1 uses msal-core. That specific branch, as you pointed out, is to enable B2C functionality in MSAL v2 which uses msal-common. It has not been thoroughly tested yet. As you noticed, ```validateAuthority``` has been removed in v2 and all authorities going forward will be validated. If you would like to play around with that branch you must set ```knownAuthorities: ["tenant.b2clogin.com"]``` in your authConfig in order to use B2C. This sets the "trusted authorities" that your requests will be validated against. 'tfp' is no longer a reliable indicator that an authority is B2C and thus this check has been removed in favor of the ```knownAuthorities``` logic.

**Comment by roneesh** [comment]
this issue is working on my end-- I just had to add the ```validateAuthority: false ``` value to my initial config. Thanks to the product team for being so responsive.
