### ISSUE TITLE
On Premise ADFS

### ISSUE THREAD

**Issue by krytical** [AzureAD/microsoft-authentication-library-for-js#1457]
## Library
msal@1.2.2

## Description
Just wondering if there is any update for MSAL and on-premise ADFS? We have a React application that would need ADFS access token for API calls and we got that working using the react-adal library, however, we're switching to MSAL as ADAL is not supported anymore.

We cannot use Azure AD for this project, only our on-premise ADFS. Is there a way to accomplish this with MSAL.js?

Thanks!

**Comment by tnorling** [comment]
We do not officially support on-premise ADFS in msal.js but if you want to try it out with the existing library and let us know specifically what issues you are facing we can look into it.

**Comment by krytical** [comment]
Thanks for the reply!

I guess if MSAL doesn't support on-premise ADFS, I should be going back to ADAL. Getting the access token and passing that to an API call worked using ADAL.

From the attempts I've been making using MSAL, I think I was mainly having issues with the authority and what scopes I should be passing but since MSAL doesn't support on-premise ADFS that would be the issue.

My config is setup something like this:
```
let msalConfig = {
    auth: {
        clientId: 'XXXX',
        authority: 'https://adfs.mydomain.ca/adfs',
        validateAuthority: true,
        navigateToLoginRequestUrl: false
    },
    cache: {
        cacheLocation: "localstorage",
        storeAuthStateInCookie: true
    }
}
```
I am not sure what scopes to pass in for on-premise ADFS so I am just passing in "openid" as the scope which I think is probably incorrect.

In my component, I am attempting to sign in using msal.loginPoup and it tries to hit https://login.microsoftonline.com/common/discovery/instance?api-version=1.0&authorization_endpoint=https://adfs.mydomain.ca/adfs/oauth2/v2.0/authorize which returns the error: could not resolve endpoints. Please check network and try again.

I followed this to setup the React components: https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/react-sample-app

**Comment by tnorling** [comment]
You can review this [document](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-adfs-support) for more information. Currently, msal.js _should_ support scenario 1, where the ADFS instance is federated with AAD. In this case you would pass "https://login.microsoftonline.com/common" to the ```authority``` parameter and it would authenticate the same way an AAD authority would. Scenario 2, where msal communicates directly with the ADFS instance, may be a future enhancement to msal.js but we do not currently have specific plans or timelines to implement this and it would only support ADFS 2019 and beyond.

**Comment by krytical** [comment]
Scenario 2 is closer to what I'm trying to attempt right now. I will most likely go back to ADAL as it supports communicating directly with our on-premise ADFS. My React app is purely just a front end application that makes API calls to a separate .NET 4.5.2 web API project so I cannot use MSAL.NET.

We are currently using ADFS 2019 so hopefully, MSAL.js will support direct communication with on-premise ADFS in the future when support for ADAL ends.

Do you know when ADAL will be deprecated?

Thanks!

**Comment by tnorling** [comment]
@krytical I am not aware that a date has been set for ADAL deprecation yet but ADAL is no longer being actively developed outside of security related fixes. We hope to support this in MSAL before ADAL is deprecated. 

Closing as this has been answered but you can follow issue #99 for updates. Thanks!
