### ISSUE TITLE
Using claims-mapping with MSAL

### ISSUE THREAD

**Issue by double0scotty** [AzureAD/microsoft-authentication-library-for-js#1458]
I've setup an App Registration and applied a custom policy to it as outlined here:
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-claims-mapping

I can't find a way though to pass through and use the validation key. According to the documents the openid-configuration requires an appId parameter to be added to get the correct key for validation: 

e.g. https://login.microsoftonline.com/{tennant}/v2.0/.well-known/openid-configuration?appId={appId}

Is there anyway of getting the msal.js library to do this or is this not supported at the moment?

**Comment by tnorling** [comment]
This is not currently supported, but there is a feature in consideration that will allow fetching the openid-configuration to be configurable. Currently the AAD claims mapping is in public preview, after it is released we will look into supporting this in msal.js
