### ISSUE TITLE
Does it support saml protocol?

### ISSUE THREAD

**Issue by jorgebibarra** [AzureAD/microsoft-authentication-library-for-js#1462]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Please provide your question here, including as much relevant details as possible.

Examples: 
> "How do I use MSAL with Vue.js"
> "How do I SSO between tabs?"
> "How do I use MSAL to protect my custom Web API?"
> "How can my app support multiple AAD tenants?"
> "When will my scenario be supported?"
> "When will this framework be supported"

**Comment by tnorling** [comment]
No msal.js does not support saml, it implements the OAuth2.0 spec
