### ISSUE TITLE
404 for samples directory

### ISSUE THREAD

**Issue by StefanSchoof** [AzureAD/microsoft-authentication-library-for-js#1463]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Documentation location
- [ ] docs.microsoft.com
- [ ] MSAL.js Github Wiki
- [ ] README file
- [x] Other (please fill in)
- [ ] Documentation does not exist

## Description
The link to  Samples at https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/README.md and https://www.npmjs.com/package/@azure/msal-angular result into a 404

**Comment by jasonnutter** [comment]
@StefanSchoof Thanks, I'll make sure that gets fixed.

**Comment by tnorling** [comment]
Looks like this was fixed. Let us know if you're still getting a 404
