### ISSUE TITLE
loginRedirect() works only the second time

### ISSUE THREAD

**Issue by returnvoid95** [AzureAD/microsoft-authentication-library-for-js#1467]
## Library
- [x] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
I'm trying to log in using the loginRedirect () function, but after entering my credentials on the Microsoft page, I get back to my page and the getAccount() function returns null. 
If you repeat the procedure again, then authorization is normal.

This situation is manifested in IE11, bacause in other browser i use loginPopUp() function. How i can fix that?

## Code
Initialization
```javascript
MsalModule.forRoot({
      auth: {
        clientId: '<client-id>',
      },
      cache: {
        cacheLocation : "localStorage",
        storeAuthStateInCookie: isIE, // set to true for IE 11
      }
    }, {
      popUp: !isIE
    }),
```

Usage
```javascript
signInIE() {
    this.msalService.handleRedirectCallback((authError, response) => {
      if (authError) {
        console.error('Redirect Error: ', authError.errorMessage);
        return;
      }

      console.log('Redirect Success: ', response);
    });
    this.msalService.loginRedirect(OAuthSettings)
  }
```

**Comment by jasonnutter** [comment]
@returnvoid95 First, `handleRedirectCallback` needs to be set outside of the function that is invoking `loginRedirect` (see [this sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/angular9-sample-app/src/app/app.component.ts#L26) for an example).

Second, which version of `msal` are you using? `msal@1.3.0-beta.0` has some fixes for `handleRedirectCallback`, would be interested to see if it fixes this issue.

**Comment by returnvoid95** [comment]
I don’t know which item mattered, but I updated the library and put the `handleRedirectCallback` into the constructor and now authorization works the first time! Thanks!
