### ISSUE TITLE
How to solve a AADB2C90055 error on acquireTokenSilent with msal-angular (AAD B2C)

### ISSUE THREAD

**Issue by jesuspsalas2** [AzureAD/microsoft-authentication-library-for-js#1470]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library

- [X ] `@azure/msal-angular@0.1.4x`

## Description
Call to acquireTokenSilent is failing always with error AADB2C90055, it is mandatory to have a custom scope in the B2C configuration? It is possible to renew the token without having this?

AADB2C90055: The scope 'openid profile' provided in request must specify a resource, such as 'https://example.com/calendar.read'

**Comment by tnorling** [comment]
Yes for B2C you need to pass custom scopes, which you need to create in the app portal beforehand.

**Comment by tnorling** [comment]
Closing. Feel free to reopen if you have follow up questions.
