### ISSUE TITLE
Angular 9 - AcquireTokenSilent keeps redirecting within custom interceptor

### ISSUE THREAD

**Issue by zlaja1983** [AzureAD/microsoft-authentication-library-for-js#1476]
We are working with Angular 9 SPA and have integrated MSAL library "@azure/msal-angular": "1.0.0-beta.4"). We are using Azure B2C user flows to authenticate the users. Initially, the users logs in by invoking loginRedirect with 
`{           authority: environment.B2C_SIGNIN_URL,
            state: redirectUrl ? redirectUrl : '/home',
            redirectUri: environment.B2C_REDIRECT_URL
}`
So far we've encountered the issue with the out of the box MsalInterceptor in which it was not attaching access tokens on the request. So we had to roll out our own custom interceptor which ended up working except that when the token expires, default of 60 mins, the AcquireTokenSilent promise does not resolve but it in turn gets redirected and eventually hits our `handleRedirectCallback`. From that point on, the access tokens within the custom interceptor are not getting attached on further requests. I'd really appreciate if someone could provide me with a workaround so that I can silently request refresh tokens.

**Comment by NechiK** [comment]
@zlaja1983 Did you added your api endpoint to scopes?

**Comment by zlaja1983** [comment]
That was it @NechiK. I just tested it at the correct scopes were missing.
