### ISSUE TITLE
loginRedirect fails when multiple resources are specified for consent

### ISSUE THREAD

**Issue by deasems** [AzureAD/microsoft-authentication-library-for-js#1487]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@^2.0.0-beta.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework
React 16.12, though the issue occurs prior to loading any React libs or code.

## Description
I specify multiple resources in a `loginRedirect` call and the user is redirected back to the app after successful auth. I then see a 400 network error from a POST request to `https://login.microsoftonline.com/common/oauth2/v2.0/token`. The logged error is:
```
Auth Failed ServerError: 28000 - [2020-04-09 22:47:24Z]: AADSTS28000: Provided value for the input parameter scope is not valid because it contains more than one resource. Scope openid profile email https://graph.microsoft.com/user.readbasic.all https://microsoft.onmicrosoft.com/aria.api/user_impersonation offline_access is not valid.
Trace ID: 01c174e2-664f-42e9-a0f3-8121f8aa0000
Correlation ID: e4b33f3a-d5c4-442a-bd0f-743b84656134
Timestamp: 2020-04-09 22:47:24Z - Correlation ID: e4b33f3a-d5c4-442a-bd0f-743b84656134 - Trace ID: 01c174e2-664f-42e9-a0f3-8121f8aa0000
```

Based on [this](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/request-response-object.md#scopes) I'd expect to be able to specify up to 3 distinct resources in the login scopes array.

If I workaround this initial error by not specifying scopes in the login request, I then get this error when I silently acquire tokens: `ClientAuthError: No tokens were found for the given scopes, and no authorization code was passed to acquireToken. You must retrieve an authorization code before making a call to acquireToken(). Scopes: https://microsoft.onmicrosoft.com/aria.api/user_impersonation offline_access`. Please consider this scenario because in first party apps consent is not required (handled separately by preauthorization) so we should be able to silently get access tokens without pre-consenting.

## Security
Is this issue security related?
Unknown

## Regression
Did this behavior work before?
I've only tried v2 releases because I depend on auth code support. This issue has been present in both the alpha and beta releases.

## Configuration
Please provide your MSAL configuration options.

```js
{
  auth: {
    clientId: '1f901506-f9a7-48fc-9a97-88e08a7f7c4b',
    navigateToLoginRequestUrl: false,
  },
  cache: {
    cacheLocation: 'localStorage',
  },
}
```

## Reproduction steps
1. Here's a self contained code snippet that should repro the issue, you'll need to substitute in your own ID/scopes:
```ts
import * as msal from '@azure/msal-browser';

const msalInstance = new msal.PublicClientApplication({
  auth: {
    clientId: '1f901506-f9a7-48fc-9a97-88e08a7f7c4b',
    navigateToLoginRequestUrl: false,
  },
  cache: {
    cacheLocation: 'localStorage',
  },
});

// Better type inference on `handleRedirectCallback` argument would be appreciated here
msalInstance.handleRedirectCallback((error: any, response: any) => {
  if (error) {
    // Error gets caught here - "TypeError: Failed to fetch"
    console.error('Auth Failed', error, response);
    return;
  }
  init().catch(console.log);
});

// A better way to know if we're in the middle of completing the auth flow for a user would be appreciated here
if (
  !msalInstance.getAccount() &&
  !window.localStorage.getItem('msal.1f901506-f9a7-48fc-9a97-88e08a7f7c4b.request.state')
) {
  signIn();
}

if (msalInstance.getAccount()) {
  init().catch(console.log);
}

function signIn(): void {
  msalInstance.loginRedirect({
    scopes: [
      'openid',
      'profile',
      'email',
      'https://graph.microsoft.com/User.ReadBasic.All',
      'https://microsoft.onmicrosoft.com/aria.api/user_impersonation',
    ],
  });
}

async function init(): Promise<any> {
  const ariaResponse = await msalInstance.acquireTokenSilent({
    scopes: ['https://microsoft.onmicrosoft.com/aria.api/user_impersonation'],
  });
  const graphResponse = await msalInstance.acquireTokenSilent({
    scopes: ['https://graph.microsoft.com/User.ReadBasic.All'],
  });
  renderApp({
    tokens: {
      aria: ariaResponse.accessToken,
      graph: graphResponse.accessToken,
    },
    account: ariaResponse.account,
  });
}

function renderApp(config: any): void {
  console.log('Success!', config);
}
```

## Expected behavior
The login flow should resolve successfully and I should be able to silently acquire tokens.

I'm wondering, why is MSAL even making a request for access tokens at this point? I'm not calling any of the acquireToken methods yet.

## Browsers
Is this issue browser-specific? If so, please detail which browsers are impacted (e.g. IE 11, Safari).
I've only tried on Chrome

**Comment by pkanher617** [comment]
@deasems Sorry for the delay on this. I am working on improving the story for multiple resources and should be able to address this shortly.
