### ISSUE TITLE
[msal-node][msal-common] Enable sub error codes support

### ISSUE THREAD

**Issue by sameerag** [AzureAD/microsoft-authentication-library-for-js#1491]
## Upcoming Library
- [ ] `@azure/msal-node@1.x`

## Type
- [ ] Feature

## Source
- [ ] Internal (MSAL.js team)

## Description
Enable sub error codes support in `msal-node`, Port #1348 

## Acceptance Criteria

1. Unit tests and 100% coverage 
2. Compatibility with `msal-browser`

**Comment by pkanher617** [comment]
#1533
