### ISSUE TITLE
Can I use this library if I need a refresh token, or do I have to write everything from scratch

### ISSUE THREAD

**Issue by rjpruitt16** [AzureAD/microsoft-authentication-library-for-js#1493]
Can I use this library if I need a refresh token, or do I have to write everything from scratch

I am trying to build an email automation tool for microsoft outlook, and it seems your api only give access token. Maybe, you can add a link for those people in need of refresh token if you cannot use this library for microsoft.

**Comment by tnorling** [comment]
@rjpruitt16 [Msal v2.0](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-browser) is currently in beta and will provide you with a refresh token. Please feel free to try it out and let us know what you think! Msal v1.x does not support refresh tokens as it implements the Implicit Grant Flow.

**Comment by rjpruitt16** [comment]
@tnorling thank you for the timely response
