### ISSUE TITLE
MSAL Angular 8 SSO

### ISSUE THREAD

**Issue by diljithpc** [AzureAD/microsoft-authentication-library-for-js#1494]
Hello Everyone,

I have been trying to add SSO for my Angular 8 app using MSAL library and Azure AD.
To an extend it is successful but my SSO page is coming in a popup window. Is it possible to load the SSO page without a popup window?

## Library
@azure/msal-angular
1.0.0-beta.4

Second to that, I'm having a web api as well in the same application. 
How do I use MSAL to protect my custom Web API?

Thanks in advance.

**Comment by tnorling** [comment]
@diljithpc You can use the ```loginRedirect()``` and ```acquireTokenRedirect()``` methods instead of the popup methods. You will need to register your web api in the Azure portal and then provide the relevant scopes to your MSAL instance. The samples directory in this repo has a few examples of how to use custom scopes.

**Comment by diljithpc** [comment]
@tnorling Thanks for providing a solution. I tried to change it accordingly. But even loginRedirect() is showing in popup window. I have cleared cache as  well.

**Comment by tnorling** [comment]
@diljithpc Can you try setting ```msalAngularConfig.popUp``` to ```false```? Can you also share your config, relevant code snippets and any logs that might help us narrow down why this is happening? Have you tried to do any debugging on your own? ```loginRedirect()``` should not be opening a popup

**Comment by tnorling** [comment]
Let us know if this is still an issue.
