### ISSUE TITLE
acquireTokenSilent is always failing for the guest user.

### ISSUE THREAD

**Issue by Visinghr** [AzureAD/microsoft-authentication-library-for-js#1495]
Please follow the issue template below. 

## Library
- [x] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Upcoming Library
- [ ] `@azure/msal-node@1.x`

## Type
- [ ] Bug
- [ ] Feature
- [ ] Enhancement
- [ ] Tooling
- [ ] Documentation
- [x] Samples
- [ ] Other (please describe)

## Source
- [x] Internal (MSAL.js team)
- [x] Customer request

## Description
   return msalApp.acquireTokenSilent() is always failing when it has been called after the authentication for guest user. 

http://localhost:3000/#error=login_required&error_description=AADSTS50058%3a+A+silent+sign-in+request+was+sent+but+none+of+the+currently+signed+in+user(s)+match+the+requested+login+hint.%0d%0aTrace+ID%3a+9506d8a5-6d61-4296-aab0-a76461803c00%0d%0aCorrelation+ID%3a+9ae75790-cf1e-43f8-9370-8ca4a04ec9de%0d%0aTimestamp%3a+2020-04-13+10%3a39%3a39Z&error_uri=https%3a%2f%2flogin.microsoftonline.com%2ferror%3fcode%3d50058&state=d11bc052-3cd3-47ad-ad05-3829b8ad3f2e

**Comment by Visinghr** [comment]
I was able to replicate this issue on the React Sample in dev branch.  
https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/react-sample-app

**Comment by tnorling** [comment]
@Visinghr When acquiring tokens for guest users you will need to pass ```sid``` to your ```acquireTokenSilent``` call. This is an optional claim that will need to be enabled in your app registration. You can find more information [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims#v10-and-v20-optional-claims-set)

**Comment by tnorling** [comment]
Closing as this has been answered. Feel free to reopen if you have follow up questions.
