### ISSUE TITLE
How do I automatically sign in on page load using `@azure/msal-browser@2.0.0`?

### ISSUE THREAD

**Issue by unindented** [AzureAD/microsoft-authentication-library-for-js#1497]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.0.0-beta.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

I'm modifying the `VanillaJSTestApp2.0` sample to sign in on page load, without user interaction. This is the diff: https://github.com/AzureAD/microsoft-authentication-library-for-js/compare/dev...unindented:dev

The problem is that, with functions like `getLoginInProgress` no longer available, I'm not able to tell whether I need to call `loginRedirect` on page load, so I end up in a loop:
- Page loads, `getAccount` returns `null`, so we call `signIn('loginRedirect')`.
- That redirects to the login flow, and send the user back to our page.
- Page loads, `getAccount` still returns `null`, and we have no way of checking that the login is in progress, so we call `signIn('loginRedirect')`.
- That redirects  to the login flow, etc.

**Comment by pkanher617** [comment]
@unindented Could you explain your model a bit more? Are you attempting to (A) use an access token to acquire a resource on page load, or (B) are you trying to see if the user has an id token available?

If it is (A), then you can use the acquireTokenSilent method to fetch a token from the cache on page load, and if it fails you can use loginRedirect() with the same scope to trigger a login.

If it is (B), you can use the getAccount() method to see if an account object is available, and if no account object is returned (i.e. getAccount() = null) then you trigger a login. 

As I say in the docs, when the page comes back to the redirect URI with the authorization code, it does take a little bit of time to perform the token exchange. You can use handleRedirectCallback to trigger any functionality after the token exchange is done.

**Comment by unindented** [comment]
I'm attempting to trigger sign in as soon as the user loads the page, without the user having to click a button.

I'm doing what you say in (B), but the problem is that, when the login flow redirects back to my page, `getAccount()` is  still `null`, cause `authRedirectCallBack` hasn't fired yet, so I call  `loginRedirect` again, and I get stuck in a loop. 

If you check the code in my fork of your sample app, and/or run it, you may understand my issue, cause it's difficult for me to explain in words any better.

**Comment by deasems** [comment]
I have the same requirement. 

Currently I'm looking at msal's storage to see if `state` exists as an indicator that we're in the middle of the login process but that's obviously not a preferred approach.

```ts
if (
  !msalInstance.getAccount() &&
  !window.localStorage.getItem('msal.1f901506-f9a7-48fc-9a97-88e08a7f7c4b.request.state')
) {
  msal.loginRedirect(...);
}
```
