### ISSUE TITLE
Issue with routing to Tenant Login View.

### ISSUE THREAD

**Issue by harishreddypothula1993** [AzureAD/microsoft-authentication-library-for-js#1498]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ X] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
How do I setup my application to navigate to Tenant login page instead of Microsoft login?
When I hit login on my application it takes me to Microsoft login page where after typing in my email and hit next it routes me to my Organization login, I want this to redirect to organization login page as soon as I hit login.
Do I need to add my tenantId to config or do I need to make any specific changes?
Examples: 
> "How do I use MSAL with Vue.js"
> "How do I SSO between tabs?"
> "How do I use MSAL to protect my custom Web API?"
> "How can my app support multiple AAD tenants?"
> "When will my scenario be supported?"
> "When will this framework be supported"

**Comment by tnorling** [comment]
@harishreddypothula1993 You can add ```authority: "https://login.microsoftonline.com/<tenant>"``` to your auth config when you initialize msal. More information on the different authorities and initializing msal can be found [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-initializing-client-applications)

**Comment by tnorling** [comment]
You can also pass ```domain_hint: "yourdomain.com"``` to ```extraQueryParameters``` in your login request

**Comment by tnorling** [comment]
Closing as this has been answered. Feel free to reopen if you have follow up questions.
