### ISSUE TITLE
Get Access Token for a multi-tenant App using MSAL.js

### ISSUE THREAD

**Issue by mohsinonxrm** [AzureAD/microsoft-authentication-library-for-js#1504]
## Library
- [X] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Scenario:
I have an Azure Function/API in tenant Azure AD "AB". The Azure Function is enabled for Authentication using System Managed Identity. Another App Registration is used to allow access to this Azure Function through API Permissions. I've enabled ID Tokens and Access Tokens on this. I've also enabled multi-tenant access, as this will be consumed by other Azure AD tenants.

Now, in another Azure AD tenant "CD", I have Dynamics 365 Customer Engagement online. I'm trying to get ID Token and Access Token to call the Azure Function in "AB" tenant and running into issues.

Under Azure AD tenant "CD", I can see the App Registration under Enterprise applications but when I try to 
`myMSALObj.acquireTokenSilent(tokenRequest)`

It gives me the below error:
"AADSTS500011: The resource principal named https://someazurefunction.azurewebsites.net was not found in the tenant named 092B0FF4-A19D-482C-A8F4-7AD4D66C83D8 (FAKE). This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
Trace ID: d7f01e48-8ca2-423d-a89b-6fcdba4e3400 (Actual)
Correlation ID: 3a1170a0-1a55-46e0-ad44-08e19cae4718 (Actual)
Timestamp: 2020-04-15 18:35:26Z"

`
const msalConfig = {
            auth: {
                clientId: "6D2B8538-3F7D-4970-A3D6-8309591B2E07", //FAKE for this issue
                authority: "https://login.microsoftonline.com/common",
                redirectUri: "https://crm018156.crm.dynamics.com",
            },
            cache: {
                cacheLocation: "sessionStorage", // This configures where your cache will be stored
                storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
            }
        };

const loginRequest = {
            scopes: ["user.read"]
        };

const tokenRequest = {
            scopes: ["https://someazurefunction.azurewebsites.net/user_impersonation"] //FAKE for this issue
        };
`

Can someone please point out me in the right direction.

I also tried to implement client credential flow in JS but that didn't work and results in CORS exception from Azure AD/login.microsoftonline.com, so now trying implicit flow

**Comment by tnorling** [comment]
@mohsinonxrm This looks like an app registration issue. Can you confirm that A. The scopes you are trying to access from tenant AB are registered in your app registration on CD? And B. That your user exists on both tenants and has permission to access to the resources you are trying to access? 

If you can provide more information about how these are configured in the azure portal it could help us figure out what's going on here. You may also find some of the information [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/accounts-overview) helpful.

**Comment by tnorling** [comment]
Closing. But let us know if you still need help, we'd be more than happy to reopen if needed.

**Comment by mohsinonxrm** [comment]
@tnorling , thanks for the comment above. I'm evaluating couple of options and will report back here what I ended up doing.
