### ISSUE TITLE
I cannot pass ClientId as a scope to Azure B2C

### ISSUE THREAD

**Issue by gavinbarron** [AzureAD/microsoft-authentication-library-for-js#1506]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.2.2` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
React 16, but that's not at play in this instance

## Description
I am unable to use the clientId as a scope when using AzureB2C and MSAL.
Calling `loginRedirect(loginRequest)` results in 
`Uncaught ClientConfigurationError: Client ID can only be provided as a single scope. Given value: my-client-id,openid,profile`

I am not in control of the B2C instance being used for Authentication. I have been using this B2C instance and clientID using HelloJS for some time, and requesting the scopes that I'm attempting to use here successfully.

## Security
Is this issue security related?
No.

## Regression
Did this behavior work before?
using HelloJs, yes, attempting to port to MSAL is not going well...

## Configuration
Please provide your MSAL configuration options.

```js
export const msalConfig: Configuration = {
    auth: {
        clientId: Resources.ApplicationId,
        authority: `https://${Resources.AadTenantName}.b2clogin.com/${Resources.AadTenantName}.onmicrosoft.com/${Resources.Aadb2cPolicy}`,
        redirectUri: `${window.location.origin}${Resources.RedirectUriRelativePath}`,
        validateAuthority: false
    },
    cache: {
        cacheLocation: 'localStorage', 
        storeAuthStateInCookie: false 
    }
};
loginRequest = {
    scopes: [Resources.ClientId, 'openid', 'profile']
};
```

## Reproduction steps
1. Use the above configuration.
2. `const msalApp: UserAgentApplication = new UserAgentApplication(msalConfig);`
2.  `msalApp.loginRedirect(loginRequest);`

Using just the clientId results in the scopes passed to the authorize endpoint being scopes=openid%20profile

If I do not have the client ID listed as a scope the B2C page fails with: AADB2C90047:+The+resource+'https://partner-domain.com/b2cview/signinup'+contains+script+errors+preventing+it+from+being+loaded

I attempted to be cute and set a scope of 'openid profile my-client-id' and but MSAL is being too smart and turning this into a scope parameter on the authorize GET of openid%20profile%2018236251-fd4e-4755-a5f9-b6d5e4ebc5fa%20openid%20profile.

## Expected behavior
I am allowed to pass the clientId along with additional scopes to the Azure B2C page

## Browsers
Not browser specific

**Comment by tnorling** [comment]
```client_id``` is not actually a "real" scope in the same sense that the others are. Sending ```client_id``` as a scope tells the service that you are requesting an ```id_token```. The purpose of the ```loginRedirect``` and ```loginPopup``` methods, by design, is to get you an ```id_token``` so in this case it would be redundant to send ```client_id``` in the request. The scopes that you send to these methods are the scopes that you want the user to consent to in order to successfully login and msal will add ```openid``` and ```profile``` automatically to the request if they are not included in this request. 

If you need to renew your ```id_token``` you can send ```client_id``` as the **only** scope to ```acquireTokenSilent()``` and msal will silently fetch you a new ```id_token```. If you, however, need an access token please send the scopes you need an access token for to ```acquireTokenRedirect()``` or ```acquireTokenPopup()``` first, and from then on you can call ```acquireTokenSilent()``` to retrieve the access token from the cache if it's there and still valid, or make a silent network call to get a new one.

**Comment by gavinbarron** [comment]
Thanks for the reply @tnorling.

I've subsequently discovered that the hellojs implementation was making a single combined request for an access_token and id_token via response_type=token%20id_token, and additionally setting an extra parameter required by the B2C customizations our partner has made.

Since doing a little refactoring on my end I'm able to get the Id token, which is all I need as based on the Identity of the User our application does some authorization outside of the IDP and issues it's own access_token with application specific scopes
