### ISSUE TITLE
SPA using Angular 8 and .Net core Web API

### ISSUE THREAD

**Issue by diljithpc** [AzureAD/microsoft-authentication-library-for-js#1508]
Hello everyone,

I have an application build using Angular 8 in the front end and .Net Core for Web API. The versions of both are mentioned below. I have created using the default template available for Angular and WebAPI project  in Visual studio 2019. Hence my Angular and .Net core part resides in the same project of a single solution. 

I'm trying to bring SSO using Azure AD. For that I have registered my application in Azure platform and configured MSAL in the Angular part. Now the application is getting authenticated correctly.

Is there any way to authenticate my API as well because now my API is not protected. Can I use MSAL.net for this.

 Library versions used:
-@azure/msal-angular 1.0.0-beta.4
.Net Core 3.1

Thanks in advance.

Diljith P C.

**Comment by derisen** [comment]
@diljithpc indeed you can. Please refer to the article [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-configure-app-expose-web-apis) and check out this sample [here](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi/tree/derisen).
