### ISSUE TITLE
guest users are getting error: aadsts50020 User account 'xyz@company.com' from identity provider 'mail' does not exist in tenant Microsoft. Library msal v1.1.3

### ISSUE THREAD

**Issue by skyovi** [AzureAD/microsoft-authentication-library-for-js#1513]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.1.3` or `@azure/msal@x.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
No Framework. 

## Description
Some of the guest users of the app, are getting error: aadsts50020 User account 'xyz@company.com' from identity provider 'mail' does not exist in tenant Microsoft. 
AAD Audit Log:

**Sign-in error code** 50058 

Failure reason: The application tried to perform a silent sign in and the user could not be silently signed in. The application needs to start an interactive flow giving users an option to sign in. Contact app owner.

## Security
Is this issue security related?
Yes

## Regression
Did this behavior work before?
Yes it was working without any issue till last week.

## Configuration
Please provide your MSAL configuration options.
 auth: {
                        clientId: '<<client id>>',
                        authority: "https://login.microsoftonline.com/microsoft.onmicrosoft.com"
                    },
                    cache: {
                        cacheLocation: "sessionStorage",
                        storeAuthStateInCookie: true
                    }
  requestObj: {
                    scopes: [serverUrl + "//user_impersonation"]
                }

It is Implicit Flow
signInAudience  is set to AzureADMultipleOrgs 

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
1.  Guest user logs into our Dynamics 365 CRM app and open an entity records
2. Clicks a button which will open a HTML page in a pop up
3. the html page tries to acquire user token (OAuth) by calling **acquireTokenSilent** 
4.  Instead of acquiring token from cache, it is forcing user to login again (acquireTokenPopup is called if acquireTokenSilent is failed). once user logged in successfully, it is redirecting user to error page (aadsts50020 )

## Expected behavior
It should acquire token from cache (SSO) as user is already logged into D365 app. the impacted users never faced this issue before and they have been facing this issue week. 

we have also observed that , this is happening for only few guest users and that too who  have two email ids (alias and easy id) in their company. they are logging into D365 using their easy id(secondary) , but the html page is not allowing them to use secondary email ids. 

we don't want use **prompt (login or select_user)** property as the use experience will be bad and user need to login every time the html page is opened. 

## Browsers
Is this issue browser-specific? If so, please detail which browsers are impacted (e.g. IE 11, Safari).
No

**Comment by tnorling** [comment]
@skyovi Can you specify, is this occurring to users that previously worked? There is a known issue with the service related to the length of the username for guest accounts. Can you also try sending ```sid``` instead of ```login_hint``` to your ```acquireTokenSilent``` and see if that resolves your issue?

**Comment by skyovi** [comment]
@tnorling  Yes this is occurring to user that previously worked.  I will try with sid parameter

Also, If it is known issue with length of username for guest account. How it was working earlier? and It is working perfectly now for users whose username length more than the impacted users.

**Comment by skyovi** [comment]
@tnorling  how can I get sid value?

**Comment by tnorling** [comment]
@skyovi Following up. Was your issue solved by passing ```sid```? The library should not be passing both ```login_hint``` and ```sid``` could you try updating to the newest version and let me know if you are still getting this behavior?

**Comment by skyovi** [comment]
@tnorling  yes issue got resolved. Thanks for your help

library is passing both `login_hint `and `sid` if I don't pass `prompt='none'` to request object

**Comment by tnorling** [comment]
@skyovi ```sid``` should only be sent to silent calls so it makes sense that it would work with ```prompt='none'```. That said, there should not be a scenario in which both ```login_hint``` and ```sid``` are sent. In fact, there is explicit logic in the code to prioritize ```sid``` over ```login_hint```. Can you try the newest version of the library (currently 1.3.0-beta.1) and open a new ticket, with steps to reproduce, if you are still seeing both being added to the url? I'm going to close this ticket as the original question has been solved.

**Comment by skyovi** [comment]
@tnorling  thanks for you support. I will test with newest version of library and will share the feedback
