### ISSUE TITLE
Could Not Resolve Endpoints & LoginPopup

### ISSUE THREAD

**Issue by FlyRocketDrones** [AzureAD/microsoft-authentication-library-for-js#1518]
Hi,

I updated auth-utils.js lines 63 and 64 with my clientid and authority but I am still getting this error:
`Error: Error: could not resolve endpoints. Please check network and try again.`

I do have a working application, so when I login on that app then come back to this, then it displays my user info but if I sign out and click sign in within this app it gives that same error.

Also, how can I make it so when I click login, it takes me to the custom login page I set for my b2c without loading the popup, and then once I login, it comes back from that as logged in?

**Comment by tnorling** [comment]
@FlyRocketDrones Please use the issue template when opening issues. It helps us address your issue more quickly.

Can you confirm which version of msal you are using? Can you also verify that you set ```validateAuthority: false``` in your auth config? When using B2C in msal versions prior to 1.3.0 you must set this. As for your 2nd question, you have 2 options when it comes to signing in; you can either use a popup or fully redirect your application to the login page and be redirected back to your application at successful sign-in. I would encourage you to read the docs and the samples in this repo to learn how to set this up.
