### ISSUE TITLE
prompt=select_account not working for personal Microsoft accounts

### ISSUE THREAD

**Issue by lborghsvanin** [AzureAD/microsoft-authentication-library-for-js#1521]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.2.2`
- [x] `@azure/msal-angular@1.0.0-beta.5`

## Framework
Angular v9 and another plain html, css & javascript project without framework.

## Description
We have set the prompt option to "select_account". This works fine for corporate Microsoft accounts but personal Microsoft accounts are unable to select their account and are automatically logged in. Once you login with a personal Microsoft account, you are stuck.

## Security
No

## Regression
Yes

## Configuration
```js
Global config:
{
    auth: {
      redirectUri: window.location.origin + '/login',
      clientId: configuration['microsoft.application.client.id'],
      authority: 'https://login.microsoftonline.com/common/',
      validateAuthority: true
    },
    cache: {
      cacheLocation: 'localStorage',
      storeAuthStateInCookie: true
}

Login function: 
this.msalService
      .loginPopup({
        prompt: 'select_account'
      })
      .then(microsoftRes => {
        // Do something
      });
```

## Reproduction steps
1. Login with personal Microsoft account
2. Try to switch account
3. Login again and no prompt is shown. The popup automatically closes and logs in the previous account

## Expected behavior
When any account tries to login with the prompt option to "select_account", a prompt to select the account should be shown anytime.

## Browsers
All browsers

**Comment by tnorling** [comment]
@lborghsvanin Could you provide fiddler traces and a CorrelationId to help our service team troubleshoot your issue? Email is in my profile.

**Comment by lborghsvanin** [comment]
@tnorling How do I exactly get the correlationId? I can set it by providing it in the options to the loginPopup, but then it would be the same for all request I think.

**Comment by tnorling** [comment]
@lborghsvanin You can use the built in function in msal to generate a correlationId in the request object like so: ```correlationId: Msal.CryptoUtils.createNewGuid()```

**Comment by lborghsvanin** [comment]
@tnorling Additional information has been sent to you.

**Comment by sameerag** [comment]
Yes, and one thing to remember here is that the `correlationId` is a per request based construct, hence please make sure you have it set to a unique per API call: eg loginPopup(.., id1) -> acquireTokenSilent(..,id2) etc.

**Comment by tnorling** [comment]
@lborghsvanin Can you clarify are you logging out between requests? Msal does not currently support multiple signed in users on one application. If you want to switch accounts you should first logout and then do a new sign in on the 2nd account. We realize this isn't ideal and we're looking at ways to enable this functionality, but unfortunately dont have an ETA right now. 

It's curious that you say it does work for corporate accounts because it shouldn't. That may be something for us to follow up on if that is indeed the case.

**Comment by lborghsvanin** [comment]
@tnorling Ok, that's something I will try, but I am not sure this is something that fits our application flow. It does work for corporate accounts as described in my original post. 

Another possibility I see is to switch from prompt=select_account to prompt=login, but I also seem to be running into an issue there. I cannot switch account, is this because of the same reason that we need to logout first? See images and description below.

User is asked to provide his password, but when you click on "Sign in with a different Microsoft account", you are redirected to a page where you still need to provide your password but can no longer switch users (screenshot2). The user then is completely stuck.
![msal1](https://user-images.githubusercontent.com/52910615/80343001-6cffcf80-8865-11ea-9add-97bf433f8f42.png)

![msal2](https://user-images.githubusercontent.com/52910615/80343007-71c48380-8865-11ea-8619-e671a91d8cf4.png)

Thanks!

**Comment by tnorling** [comment]
@lborghsvanin What is happening here is that msal sees there is already a logged in user and provides a ```login_hint``` indicating who is logged in. This is used to pre-fill email information if you are not logged in, or to reference your active session if you are. For MSA accounts what is happening is that your request is providing both the ```login_hint``` and ```prompt=select_account``` and the authority thinks you are already logged in and silently gives you a new token. If it is working for corporate accounts that potentially means that the authority isn't respecting the ```login_hint```. 

One way to get around this is to clear your cache so msal doesn't know about any previously logged in users. You could try calling the ```clearCache()``` method on your msal object. The downside of this is that your identity provider still thinks you are logged in, which could potentially be a vulnerability. Our recommendation would be to logout first before switching accounts. One thing that remains true with either approach is that you can only ever have 1 user known to msal, meaning each time you switch accounts you will need to acquire new tokens.

**Comment by tnorling** [comment]
@lborghsvanin This may actually be a bug, apologies for dismissing it. While multiple accounts are not supported, switching accounts should be. For interactive calls we should allow the `prompt` parameter to override a `login_hint`. Waiting to hear back from the service teams about whether corporate and MSA accounts behave differently when both are provided and then will determine if changes are needed for msal. Since another similar issue was recently opened please track that one for updates #1557

**Comment by rfcdejong** [comment]
@tnorling while testing our own app I ran into this issue, on Edge.. it doesn't show the prompt and takes an account which was used before in the browser session. I expect always to see a selection screen to select an known account or add a new account credentials.

I'm using Angular 9 with "msal": "^1.3.2",
  login() {
    const isIE = window.navigator.userAgent.indexOf('MSIE ') > -1 || window.navigator.userAgent.indexOf('Trident/') > -1 || window.navigator.userAgent.indexOf('Edge') > -1;
//    const apiScope = 'api://' + environment.apiApplicationId + '/access_as_user';
    const loginRequest = {
      scopes: [
        "user.read",
        "openid",
        "profile",
        "email"
      ],
      prompt: 'select_account'
    };

    if (isIE) {
      this.authService.loginRedirect();      
    } else {

**Comment by rfcdejong** [comment]
@tnorling nevermind... now that I posted the code I see the mistake... if (isIE) is missing the loginRequest as parameters :)
Might be copy paste from samples or documentation, it all works better on Chrome!

It should ofcourse be:
```

if (isIE) {
      this.authService.loginRedirect(loginRequest );      
    } else {
```
