### ISSUE TITLE
Is it me or some commits were losts i.e. (PR 147 for issue 145)?

### ISSUE THREAD

**Issue by mathlesp** [AzureAD/microsoft-authentication-library-for-js#153]
I was looking at issue #145 and a saw that a fix was made to "setting user object from cache before acquireToken". This was merged in PR #147 in dev branch. However, the code appear to be lost since commit aea14104312b7e6a569f67b1ee762f22a579c2cc. 

Am I looking in the wrong place?

**Comment by rohitnarula7176** [comment]
@mathlesp Thank you for pointing out this issue. The changes for setting the user object from cache before every acquireToken call are now added to dev.
