### ISSUE TITLE
Change language for login page in B2C

### ISSUE THREAD

**Issue by dusanjovanov** [AzureAD/microsoft-authentication-library-for-js#1530]
## Library
- [x] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
When I redirect the user to the login page, I want to somehow append &lang=langCode to dynamically change the language. The problem is I don't control the generation of the login URL. 
Is that possible ?

**Comment by tnorling** [comment]
@dusanjovanov You can add additional query parameters to the login url by passing them to ```extraQueryParameters``` in your request object. For the example you provided it would look something like this: ```extraQueryParameters: {lang: langCode}```
