### ISSUE TITLE
[@azure/msal-angular] contains deep imports

### ISSUE THREAD

**Issue by snebjorn** [AzureAD/microsoft-authentication-library-for-js#1532]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.0.0-beta.5`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework
Angular 9.1.2

## Description
When running `ng serve` I see this warning

> Warning: Entry point '@azure/msal-angular' contains deep imports into 
>     'redacted/node_modules/msal/lib-commonjs/utils/UrlUtils', 
>     'redacted/node_modules/msal/lib-commonjs/utils/WindowUtils', 
>     'redacted/node_modules/msal/lib-commonjs/cache/AuthCache', 
>     'redacted/node_modules/msal/lib-commonjs/UserAgentApplication'. 
>     
> This is probably not a problem, but may cause the compilation of entry points to be out of order.

That should probably be looked at.

## Reproduction steps
1. `npm i @azure/msal-angular@1.0.0-beta.5`
2. `ng serve`
3. Observe warning

**Comment by jasonnutter** [comment]
This was fixed in #1499 and will be available in teh next release of MSAL Angular. Closing.
