### ISSUE TITLE
Broken links on the npm package page.

### ISSUE THREAD

**Issue by crystalbyte** [AzureAD/microsoft-authentication-library-for-js#1536]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Documentation location
- [ ] docs.microsoft.com
- [ ] MSAL.js Github Wiki
- [ ] README file
- [x] Other (please fill in)
- [ ] Documentation does not exist

## Description
Many links on the [npm package](https://www.npmjs.com/package/@azure/msal-angular) page run into 404 errors, see this image.

![image](https://user-images.githubusercontent.com/548964/80077016-38ca9d00-854d-11ea-8a35-df6b61e05d80.png)

**Comment by jasonnutter** [comment]
@crystalbyte Thanks for the heads up, unfortunately looks like Github relative links aren't handled properly on npm.com. I'll have a PR to fix shortly.
