### ISSUE TITLE
Can we use Angular Wrapper of MSAL for production ?

### ISSUE THREAD

**Issue by hammerstrike** [AzureAD/microsoft-authentication-library-for-js#1540]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [x] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Using Angular wrapper "@azure/msal-angular": "^0.1.4" and using Angular 8.x in app
for project which will be going in production.
Roadmap shows Angular wrapper 1.x is still in beta version.
How suitable current version is for production and can we go with it ?

**Thanx for this awesome library**

**Comment by tnorling** [comment]
@hammerstrike We generally do not recommend using beta versions for production applications. However, Angular 1.0 will be coming out of beta and will be GA very soon. We will post an announcement when that happens so keep your eyes open for that.
