### ISSUE TITLE
Can not get accesstoken using webform

### ISSUE THREAD

**Issue by element8763** [AzureAD/microsoft-authentication-library-for-js#1541]
## Library
- [ ] `msal@1.2.2` 

## Description
If I use acquireTokenSilent in a webform,can not get cache token.The cache item key storaged in a clientid instead of a scope！

## Regression
Can be used in a html page

## Configuration
Please provide your MSAL configuration options.

```js
// Provide configuration values here.
function seeProfile() {
    if (myMSALObj.getAccount()) {
        alert();
        myMSALObj.acquireTokenSilent(loginRequest).then(
            response => {
                //alert(response);
                callMSGraph(graphConfig.graphMailEndpoint, response.accessToken, updateUI);
                // success response
            }).catch(function (error) {
                alert(error);
                console.log(error);
            });
}
}
```

## Browsers
Chrome &Edge

**Comment by tnorling** [comment]
@element8763 Are you getting any errors? Steps to reproduce would be helpful in debugging this for you.

**Comment by tnorling** [comment]
@element8763 Please track issue #1357 for updates on this. Thanks!
