### ISSUE TITLE
Remove accounts from the token cache

### ISSUE THREAD

**Issue by DarkLite1** [AzureAD/microsoft-authentication-library-for-js#1545]
## Library
- [x] `msal@1.2.2 from `npm install msal`

## Description
I was wondering if there is a way to clear the session/cache of `msal` completely? 

In my app the `logon` and `logout` functions flawlessly thanks to `msal`. However, sometimes when we are within the company network we get a credential popup from Google Chrome where we have to enter our domain credentials (`bob@contoso.com`) before the logon is confirmed. It's a different sing-in dialogue than the one from Microsoft. 

When a user enters the wrong password the `SPA` cannot be reached as authentication fails. When then trying to sing-in again we end straight into the `cannot find page`. To mitigate this issue I have to restart `node.js` with the `Vue.js` app and restart the browser. I haven't found a better way of handling this. So I'm wondering, would it be possible to complete clear the cache of `msal` so it can start all over again with a clean sheet?

This seems [possible for Java](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-java-get-remove-accounts-token-cache) but I didn't find it for javaScript.

Thank you for your help.

![image](https://user-images.githubusercontent.com/10828570/80273765-66425280-86d5-11ea-8fe5-979f75bda690.png)

**Comment by tnorling** [comment]
@DarkLite1 You should be able to call the ```clearCache()``` method on your msal object. Let me know if you have additional questions about this.
