### ISSUE TITLE
How do I prevent token replay for access tokens acquired using @azure/msal-browser@2.0.0-beta.0?

### ISSUE THREAD

**Issue by dylan-hart** [AzureAD/microsoft-authentication-library-for-js#1546]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
How do I prevent replay of access tokens acquired using the @azure/msal-browser@2.0.0-beta.0 library?

I'm familiar with checking the `nonce` claim against a cache of previously seen values. That claim is provided when using @azure/msal@1.2.2-beta.1, but doesn't appear to be provided when using @azure/msal-browser@2.0.0-beta.0.

Thanks for your help!

**Comment by tnorling** [comment]
@dylan-hart Can you explain a little more about your use case? The library should do these types of things for you in the background. The ```nonce``` claim is generated by the library before each request, sent back by the identity provider and then the library validates that it matches what was sent. Is this not sufficient for your use case?

**Comment by dylan-hart** [comment]
Hi,

I'm probably misunderstanding how to use the library somehow, or perhaps some aspect of using tokens.

I've got a web app that's registered in my AAD. The web app uses .loginPopup() to acquire an ID token. Once it's successfully acquired an ID token, it then calls .acquireTokenSilent() with some scopes to acquire an access token and passes that access token on to a backend application that is running on a remote server. The backend application uses the access token to decide whether to allow a websocket connection.

In my backend application, I use the jws and jsonwebtoken NPM packages to decode and verify the access token. Where I'm stuck is that I expected to see a nonce field in the access token so that my backend application could cache its value and prevent replays. The ID tokens my web app acquires have a nonce field when decoded, but the access tokens do not. My assumption at the moment is that this is by design, but I'm not sure what I've misunderstood.

Thanks again!

**Comment by tnorling** [comment]
@dylan-hart Gotcha. We don't recommend using msal-browser for applications which have a backend. It is intended to be used only for Single Page Applications. If you are using the access tokens on your backend you should obtain the access tokens on your backend. You can, however, acquire the Authorization Code with msal-browser and pass this to your backend to use to acquire the access token. There are many different flavors of msal available to help you with this. What language is your backend written in? I'll try to point you in the right direction.

With that disclaimer out of the way: If you must proceed with msal-browser, the ```nonce``` claim can be found in the header of the access token. More information about Access tokens [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens)

**Comment by dylan-hart** [comment]
Ah. Thanks @tnorling ! I actually didn't realize SPAs had no backend. I thought 'single page application' just meant there's no full reloading of the browser window. Whoops.

Thanks for your offer! My backend is a Node.js app.

Lastly, just for reference, here's all the fields of an access token as decoded by https://jwt.ms:
```
{
  "typ": "JWT",
  "alg": "RS256",
  "x5t": "CtTuhMJmD5M7DLdzD2v2x3QKSRY",
  "kid": "CtTuhMJmD5M7DLdzD2v2x3QKSRY"
}.{
  "aud": "...",
  "iss": "...",
  "iat": 1588022586,
  "nbf": 1588022586,
  "exp": 1588026486,
  "acr": "...",
  "aio": "...",
  "amr": [
    ...
  ],
  "appid": "...",
  "appidacr": "...",
  "email": "...",
  "family_name": "...",
  "given_name": "...",
  "idp": "...",
  "ipaddr": "...",
  "name": "...",
  "oid": "...",
  "scp": "...",
  "sub": "...",
  "tid": "...",
  "unique_name": "...",
  "uti": "...",
  "ver": "..."
}.[Signature]
```

**Comment by tnorling** [comment]
@dylan-hart No worries, you're not wrong, that is what it means. However, the idea is that your frontend is doing most of the work and really just making API calls to get what it needs to display its content. Authentication in the browser is inherently less secure than authentication on a backend so for that reason, if you have a backend component, we recommend you do your authentication there. Additionally an access token should only be sent to and read by the resource its for. Adding a middle man increases your surface area for attack.

Unfortunately, msal for Node.js is one of the ones we're still working on. The team is hard at work trying to get this out so please keep your eyes open and expect to see an announcement about that soon!

I realize that doesn't help you today so I'll see what I can find out about ```nonce``` and get back to you. I do see it included in the header for my access tokens so there may be some configuration that's missing.

**Comment by dylan-hart** [comment]
Oh got it. Thanks very much for your help! This particular project isn't in production yet, fortunately. Eagerly awaiting the Node.js preview, and any more information you're able to provide about the nonce field in the access tokens.

**Comment by tnorling** [comment]
@dylan-hart I hate to be the bearer of bad news, but here's the deal with access tokens. We cannot guarantee the format of the token, what is inside or that it is a JWT at all. We also can't promise that fields in an access token today will be there tomorrow. They really aren't intended to be opened and inspected by anything other than the resource for which it is intended. So unfortunately, I dont have a good answer for you regarding `nonce`. You may be able to get creative and find a different way to validate that you are receiving a new token, but the official answer is that you gotta wait for msal-node and implement authentication on your backend. Sorry for the inconvenience and we appreciate your patience while we get msal-node spun up. We're very excited to get it into your hands and hear your feedback!
