### ISSUE TITLE
How can my backend discover the issuer URL for access tokens acquired using @azure/msal-browser@2.0.0-beta.0?

### ISSUE THREAD

**Issue by dylan-hart** [AzureAD/microsoft-authentication-library-for-js#1547]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
How can I set up a process to discover the issuer URL for access tokens that are acquired using the @azure/msal-browser@2.0.0-beta.0 library?

I'm familiar with using a `.well-known/openid-configuration` endpoint to discover this value while using @azure/msal@1.2.2-beta.1, but the issuer URL of access tokens acquired using @azure/msal-browser@2.0.0-beta.0 have a value that doesn't seem to appear in my tenant's `.well-known/openid-configuration` metadata document. (It's a `https://sts.windows.net/...` value, but my metadata document only contains `https://login.microsoftonline.com/...` values). Is it OK to hard-code the `https://sts.windows.net/` value I find in tokens acquired using msal-browser? Am I using the wrong discovery endpoint?

Thanks!

**Comment by tnorling** [comment]
@dylan-hart The issuer listed in the metadata endpoint is the default issuer. The issuer included in your token is the actual issuer of the token and can vary depending on which cloud is issuing the token. Are you trying to verify whether the token issued came from a trusted source? If so, msal has mechanisms in place to do this, you should not need to do this validation yourself.

**Comment by jasonnutter** [comment]
@dylan-hart Here is some additional context around the issuer field: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/560#issuecomment-620133340

**Comment by dylan-hart** [comment]
Ah! Thanks very much both. This clears it up pretty well for me, I think.

@tnorling That's basically what I was attempting I suppose, just probably even more niavely than expected lol. I'm assuming I can't use msal in my backend application, which is a Node.js app running on a remote server, so I'm using the jws and jsonwebtoken NPM packages to decode and verify access tokens sent to it by browser clients. Because my jwks_uri endpoint returns an issuer field and the jsonwebtoken NPM package accepts an issuer value when verifying tokens, it seemed like a natural fit to use it in the verification process. This 'works' for @azure/msal@1.2.2-beta.1, but your response and the issue that @jasonnutter linked seems to make it clear that the values just happen to align in some scenarios.

I guess I can either ignore the issuer field in my backend while I wait for the Node.js library preview, or maybe take a look at msal's mechanisms for doing this?

Thanks again!

**Comment by tnorling** [comment]
@dylan-hart I suppose you could check if the issuer field contains your tenant id. May be better than nothing in the interim until we get msal-node pushed out? Closing this but let us know if you have additional questions.
