### ISSUE TITLE
during login call - login is already in progress

### ISSUE THREAD

**Issue by PrashanthReddy7** [AzureAD/microsoft-authentication-library-for-js#1549]
## Library
-1.1.3
-https://alcdn.msauth.net/lib/1.1.3/js/msal.min.js

## Description
Facing "login in is already in progress" issue.
I have cleared the cache &  cookies, but still the same issue

Error Messgae:
Message received in processMessage: {"type":"dialogMessageReceived","message":"{\"status\":\"failure\",\"result\":{\"errorCode\":\"login_progress_error\",\"errorMessage\":\"Login_In_Progress: Error during login call - login is already in progress.\",\"name\":\"ClientAuthError\"}}"}

## Regression
Yes, same code worked before, facing issue now only.

## Configuration
const msalConfig = {
  auth: {
    clientId: "XXXXX", //This is your client ID
    authority: "https://login.microsoftonline.com/common",
    redirectUri: "https://localhost:3000/fallbackauthdialog.html",
    navigateToLoginRequestUrl: false
  },
  cache: {
    cacheLocation: "localStorage", // Needed to avoid "User login is required" error.
    storeAuthStateInCookie: true // Recommended to avoid certain IE/Edge issues.
  }
};

## Expected behavior
It Should logins and gets the valid access token

## Browsers
IE11, Microsoft Edge, Chrome, Outlook client add in.

**Comment by tnorling** [comment]
@PrashanthReddy7 Can you update to the latest version of msal and let us know if this is still an issue? ```msal@1.3.0-beta.1``` is currently available. Thanks!

**Comment by PrashanthReddy7** [comment]
@tnorling Thank you for your reply, its working now with msal@1.3.0-beta.1 and I have following queries.
1. Can you please share the CDN url for the same (msal@1.3.0-beta.1), I couldnt find it in Git.
2. Since its in beta, may I know,  by when it will be available for PROD.
3. And I am facing following issue sometimes, while login pop up openes ,its throwing as
"Failed to load resource: the server responded with a status of 431 (Request Header Fields Too Large)"

**Comment by PrashanthReddy7** [comment]
@tnorling , Thank you for your help

**Comment by muecahit** [comment]
I get the same error. When I navigate from our sharepoint to our webapp(uses msal) by clicking on a link, the same error occours. Upgrading to version 1.3.0 did not fix it.

**Comment by muecahit** [comment]
For me upgrading to 1.3.0 did not fix the problem. On sharepoint we have a link to our webapp(uses msal). When we click the link, the error occours. But when you visit the URL by hand it works.

**Comment by muecahit** [comment]
@tnorling For me upgrading to 1.3.0 did not fix the problem. On sharepoint we have a link to our webapp(uses msal). When we click the link, the error occours. But when you visit the URL by hand it works.
