### ISSUE TITLE
"Forgot Password" click results in msal:acquireTokenSuccess Event

### ISSUE THREAD

**Issue by Hampfter** [AzureAD/microsoft-authentication-library-for-js#1554]
## Library
- `"@azure/msal-angular": "^1.0.0-beta.5"`
- `"msal": "^1.3.0"`
 

## Framework
 `"@angular/core": "8.2.3",`

## Description
When I start a Login UserFlow and the User clicks on `Forgot your password?`, I should get a redirect to my Page with an AuthError like this:
```
ServerError: AADB2C90118: The user has forgotten their password.
Correlation ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```

The Redirect happens, but if i subscribe to the msal:loginFailure or msal:acquireTokenFailure events in the broadcastService, they are never triggered. Instread I get a msal:acquireTokenSuccess Event.
I guess the error has to be in the handleRedirectCallback method of the MsalService

## Regression
I'm not sure why this is happening. It worked with beta4 when I implemented it. Now it isn't even working with beta4.

## Configuration
```
MsalModule.forRoot(
{
	auth: {
		clientId: "**hidden**",
		authority: "**hidden**",
		validateAuthority: false,
		redirectUri: "**hidden**",
		postLogoutRedirectUri: "**hidden**"
	},
	cache: {
		cacheLocation: "localStorage",
		storeAuthStateInCookie: isIE // set to true for IE 11
	}
},
{
	unprotectedResources: [**hidden**],
	popUp: !isIE,
	consentScopes: [
	]
});

```

## Expected behavior
Getting the right event.

**Comment by tnorling** [comment]
@Hampfter Msal just passes back what the service returns. If the service doesn't throw an error, neither will msal. Are you getting a token in the response? What happens when it triggers your acquireTokenSuccess event? Also, want to confirm, this is a b2c scenario?

**Comment by jasonnutter** [comment]
@Hampfter Can you try reproducing this bug with [our Angular B2C sample](https://github.com/Azure-Samples/active-directory-b2c-javascript-angular-spa)? And then share the link to the fork here? Thanks!

**Comment by Hampfter** [comment]
You only need to change the login method in the app.component.ts and use loginredirect.
```
  login() {
    if (isIE) {
      this.authService.loginRedirect(loginRequest);
    } else {
      this.authService.loginRedirect(loginRequest);
    }
  }
```

If you now click Login -> "Forgot your Password?", you will get an acquireTokenSuccess Event. My local storage says different. It has entries like: 
```
AADB2C90118: The user has forgotten their password.
Correlation ID: bfeac638-375e-4719-ab2a-c35201daa383
Timestamp: 2020-04-29 05:54:29Z
```
So my Implementation did react on a loginFailure Event in which payload i had this errormessage, so i could redirect to my PasswordReset UserFlow. In the acquireTokenSucces Event I'm not getting a token. This is the payload:
`{"uniqueId":"","tenantId":"","tokenType":"","idToken":null,"idTokenClaims":null,"accessToken":"","scopes":null,"expiresOn":null,"account":null,"accountState":"f279adc8-dc67-4217-8701-b0f5a2008163","fromCache":false}`


@tnorling I#m not getting a Token back. And yes, it is a b2c scenario

**Comment by tnorling** [comment]
This is related to #1406. Will put up a PR to address.
