### ISSUE TITLE
msal.js log in account that is not current user that launched the browser

### ISSUE THREAD

**Issue by SaratMuppala** [AzureAD/microsoft-authentication-library-for-js#1557]
Hi,

I am trying to implement switch account feature for my SPA website. I am able to login an account that matches the current user that launched the browser. But if i prompt for account selection and provide a different account email id to login then it still using the current user that launched the browser to login and retrieves the id token. I have a service account that i would like to use but am not able to get token for the service user account from my actual windows account browser instance. Both of these accounts are in same tenant (company tenant) and i can log them in if i launch the browser (Run as User feature) with the corresponding windows Account. Is it possible to implement switch account using msal.js 1.2.2 version? if yes, can i get a sample on how to implement the feature?

The below is my msal config

var msalConfig = {
                auth: {
                    clientId: config.appServiceConfig.clientId,
                    authority: config.appServiceConfig.authority,
                    redirectURI: config.appServiceConfig.redirectURI,
                    navigateToLoginRequestUrl: false
                },
                cache: {
                    cacheLocation: "sessionStorage",
                    storeAuthStateInCookie: true
                }
            };
var requestObj = {
                    scopes: ["User.ReadBasic.All"],
                    prompt: "select_account",
                    loginHint: "serviceaccount@xxx.com",
                    authority: config.appServiceConfig.authority
                };

Appreciate any help!!!

Thanks Sarat.

**Comment by tnorling** [comment]
@SaratMuppala This issue has been confirmed to be a bug with the MSA service. We will update you here when it has been fixed. Thanks for bringing this to our attention.

**Comment by tnorling** [comment]
Update: This has been fixed but will take some time to fully roll out. If you are still experiencing this issue at the end of the month please let me know and I will reopen.
