### ISSUE TITLE
error in MSAL.html file? request and respons mixup?

### ISSUE THREAD

**Issue by proplanlava** [AzureAD/microsoft-authentication-library-for-js#1558]
## Library
https://alcdn.msauth.net/lib/1.2.1/js/msal.js 

## Framework
plain JS

## Description
Error in line 70.
I think line 69 in samples/UnifiedCacheTestApp/MSAL.html is wrong.
    myMSALObj.acquireTokenSilent(request).then(function (request) {
should be:
   myMSALObj.acquireTokenSilent(request).then(function (tokenResponse) {

## Security
no

## Regression
na

## Configuration
var msalConfig = {     auth: {         clientId: "....",         authority: "https://login.microsoftonline.com/organizations",         redirectUri: "https://localhost:44327/",         validateAuthority: true
    },    cache: {         cacheLocation: "localStorage",         storeAuthStateInCookie: true    }};

## Expected behavior
no error in acquireTokenPopupAndCallMSGraph

## Browsers
na

**Comment by tnorling** [comment]
@proplanlava Thanks for pointing this out! I'll make sure to get this fixed.
