### ISSUE TITLE
@azure-msal-browser@2 documentation missing

### ISSUE THREAD

**Issue by ktikku** [AzureAD/microsoft-authentication-library-for-js#1559]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Documentation location
- [ ] docs.microsoft.com
- [ ] MSAL.js Github Wiki
- [ ] README file
- [X ] Other (please fill in) https://www.npmjs.com/package/@azure/msal-browser
- [ ] Documentation does not exist 

## Description
A clear and concise description of the documentation issue.
I want to migrate from `msal` to `@azure/msal-browser` `v2.0.0-beta.0`, I was going through [@azure/msal-browser](https://www.npmjs.com/package/@azure/msal-browser) but the links given for migration and consumption of modules are not working. 
eg: 

1. 
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/HEAD/docs/v1-migration.md

2. 
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/HEAD/docs/initialization.md

**Comment by tnorling** [comment]
@ktikku Thanks for pointing this out. We'll make sure to get this updated on npm. You should be able to find the docs you are looking for in the repo for msal-browser. 
1. https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/v1-migration.md
2. https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/initialization.md

**Comment by ktikku** [comment]
thanks for the quick response! 👍

**Comment by tnorling** [comment]
Doc links on npm have been updated.
