### ISSUE TITLE
Migrating from old version of msal to msal-browser

### ISSUE THREAD

**Issue by SebastianPellitero** [AzureAD/microsoft-authentication-library-for-js#1561]
## Library
- [ ] `msal@0.2.3`  
- [ ] `@azure/msal-browser@2.0.0-beta.0` 

## Description
Hi there. 

Im working on a React/redux Application, and Im using the msal functions to allow a user to log in. Im having an issue with users with multiple accounts and users trying to log in on Safari and I saw that migrating to a new version of the library fixs the issue.
Link to the issue: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1205

So, Im trying to update my dependencies, and im having this new issue now:
"ClientAuthError: State mismatch error. Please check your network. Continued requests may cause cache overflow."

I couldnt find documentation related to how to use this library with React so im using the plain Javascript docs that I found. 

Could you please redirect me to some documentation or example that I can follow in order to migrate to the new version?  or do you know what could be causing this error that im having?

Thanks in advance!

**Comment by tnorling** [comment]
@SebastianPellitero Migration guide can be found here: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/v1-migration.md

You can dig around the repo for docs on a number of topics or ask here for further clarification. Without additional information about your use case it's hard to say what could be causing the state mismatch error. If you can't figure it out with the docs please open a bug report using the template and include steps to reproduce. Forking the repo and reproducing the error using one of the provided samples will be the quickest way for us to investigate. Thanks for trying out the beta!
