### ISSUE TITLE
Refused to display in iframe

### ISSUE THREAD

**Issue by exuviae** [AzureAD/microsoft-authentication-library-for-js#1563]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x ] `@azure/msal-angular@1.0.0-beta.5`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
If you are using a framework, please provide the framework and version (e.g. Angular v8, React v16, etc).

Angular 8

## Description
We have users that use multiple microsoft account, for example they have an office 365 account and an azure B2C account that is a social login to Azure AD.  When both accounts are logged in with the same browser window and go to our app, the account selection screen is shown as expected.  However the console shows the following error:

Refused to display 'https://login.microsoftonline.com/09d69ad0-9c02-4895-a443-160317c2cb02/oauth2/v2.0/authorize?client_id=REMOVED&redirect_uri=REMOVED&response_type=code&scope=openid+profile+email&response_mode=form_post&nonce=93r7tHZXGBjfiMi6QV%2bdnw%3d%3d&state=StateProperties%3deyJTSUQiOiJ4LW1zLWNwaW0tcmM6ZmRjNjk4MGQtZDZkMy00YjhjLThhNTMtNjA4ODNiZWU5N2Y5IiwiVElEIjoiNzkzMmRlMDAtMDE2MC00ZDI0LTkwZmMtY2ZiM2QwMDAwZjM0IiwiVE9JRCI6IjE1OWY4MDFmLTI4YTgtNDY4ZC04NjMyLWU3M2NiZjM1OTE4YyJ9' in a frame because it set 'X-Frame-Options' to 'deny'.

We have tried using a domain hint, but it is never sent.  We have tried conditionally initializing the angular app with a different redirect url, but none of those have worked. 

## Security
Is this issue security related?

Yes and No.  It is security related in the sense our users can't login, but no there are no apparent risk associated with the error. 

## Regression
Did this behavior work before?
No

## Configuration
Please provide your MSAL configuration options.
{
    auth: {
      clientId: environment.clientID,
      authority: environment.authority,
      validateAuthority: true,
      redirectUri: environment.baseUrl,
      postLogoutRedirectUri: environment.baseUrl,
      navigateToLoginRequestUrl: true,
    },
    cache: {
      cacheLocation: 'sessionStorage', // 'localStorage',
      storeAuthStateInCookie: isIE, // set to true for IE 11
    },
    system: {
      loadFrameTimeout: 90000
    }

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
The only policy we have in use is a custom policy, the name is B2C_1A_MFA_IP_TimeoutCCMSI which only implements sign in, it does include the azure ad social identity provider and everything works with a single user logged in.

## Reproduction steps
1. go to azure portal, sign in as anyone
2. in a new tab go to azure portal or office 365 and sign in as a different user 
3. go to an app that has a default sigin only policy or a custom policy with azure ad as a social provider.
4. go to an app using @azure/msal-angular and you will get the issue

## Expected behavior
A clear and concise description of what you expected to happen.

After the user selects the account they wish to login into, the application should work identical to the app when only a single account is signed in to an azure service.  

## Browsers
Is this issue browser-specific? If so, please detail which browsers are impacted (e.g. IE 11, Safari).
ALL

**Comment by tnorling** [comment]
@exuviae This is a known issue. You can track #1437 and #1161 for updates and workarounds. Closing as duplicate
