### ISSUE TITLE
@azure/msal-browser vs @azure/msal for Angular SPA

### ISSUE THREAD

**Issue by thrixton** [AzureAD/microsoft-authentication-library-for-js#1568]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Is @azure/msal-browser the recommended library for SPA apps?
Does it replace @azure/msal in that case?
Should it be used in conjunction with @azure/msal-angular?

**Comment by jasonnutter** [comment]
> Is @azure/msal-browser the recommended library for SPA apps?

MSAL Browser is currently in private preview, but once it is generally available, yes, it will be the recommended library to use.

> Does it replace @azure/msal in that case?

Yes, as it switches from the Implicit Flow (used by msal v1) to the Auth Code Flow w/ PKCE.

> Should it be used in conjunction with @azure/msal-angular?

We will upgrade @azure/msal-angular to work with @azure/msal-browser, however, that will not happen at least until msal-browser is GA (and that work is not yet scheduled).

**Comment by CerosDev** [comment]
@jasonnutter any ETA on when we will be able to test msal-browser with AD B2C?

**Comment by jasonnutter** [comment]
@CerosDev Not sure of the ETA on that, @pkanher617 @hamiltonha should be able to provide more context.

**Comment by hamiltonha** [comment]
@CerosDev  B2C support is now supported, you can test by manually editing your manifest as described in the msal-browser README

**Comment by pkanher617** [comment]
Closing as the conversation is no longer pertaining to the issue.

**Comment by kemins** [comment]
So where we are right now???
@azure/msal-angular that has been recently released(not beta anymore) is not compatible with Safari(renew token fails), forcing users to turn off the security feature(cross-site tracking) seems like a ridiculous and controversial option.

There is no even raw ETA for 'MSAL Browser' support.
IMHO authentication flow is essential for any enterprise, there must be a stable library with cross-browser support without compromise and workarounds.

Microsoft is not a charity and that's a question of integration with Microsoft platform itself, have no idea why it's not a priority why there is no beta/alpha yet, no even dates.

**Comment by jasonnutter** [comment]
> So where we are right now???
> @azure/msal-angular that has been recently released(not beta anymore) is not compatible with Safari(renew token fails), forcing users to turn off the security feature(cross-site tracking) seems like a ridiculous and controversial option.
>
> 
> There is no even raw ETA for 'MSAL Browser' support.
> IMHO authentication flow is essential for any enterprise, there must be a stable library with cross-browser support without compromise and workarounds.
> 
> Microsoft is not a charity and that's a question of integration with Microsoft platform itself, have no idea why it's not a priority why there is no beta/alpha yet, no even dates.

We decided to upgrade MSAL Angular to use MSAL.js v1 (as opposed to v2, aka MSAL Browser) because MSAL.js v2 is still in development (currently in public preview), and we did not want to wait until MSAL.js v2 was stable before GAing MSAL Angular, as we know there customers waiting for MSAL Angular to work with MSAL.js v1. 

I understand the frustration with Safari and ITP, and agree it is suboptimal to ask users to disable privacy settings or to often seeing popups in your application when new tokens are needed. Once MSAL.js v2 is GA and stable, we will look at upgrading MSAL Angular to use it. As noted, we haven't scheduled this work yet, but we will post an update when we know (this is dependent both on MSAL.js v2 and other priorities of our team).

**Comment by liben-y** [comment]
The recent changes on the app registrations page in Azure: Integration Assistant (preview), sets out recommendations and evaluates the app registration for SPA application types.

The Develop tab has recommendations to "Avoid programming directly against protocols... instead, use open source library such as MSAL".

On the summary tab, one of the recommendations is "Do not enable access tokens for the implicit grant flow" (image below). There is no disclaimer that the MSAL library doesn't support Auth Code Flow and to ignore this recommendation for Angular.

Whilst the recommendations are definitely welcome, there is a serious issue for Angular that leads to a roadblock.

![image](https://user-images.githubusercontent.com/16204903/83624362-6c580880-a58a-11ea-9fe7-05dfcefeddc9.png)

**Comment by jasonnutter** [comment]
@liben-y I agree that is confusing, thanks for the feedback. cc: @hamiltonha

**Comment by Vince5555** [comment]
Does this fix the looping in IE11 between the app and MSAL?
