### ISSUE TITLE
Logout doesn't redirect back when using AD tenant in the authority url.

### ISSUE THREAD

**Issue by Riff451** [AzureAD/microsoft-authentication-library-for-js#1569]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.0.0-beta.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Hi all, this is about an issue I already explained [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/127#issuecomment-621088587) and as requested I'm opening a new issue.
I'm using a B2C tenant even if I'm trying the standard Azure AD identity feature (personal MS and organizational accounts). 
I've tried a couple of different combinations with authorities and accounts.

Following are authorities that all work with both accounts, personal and organizational:

`authority: "https://login.microsoftonline.com/consumers"` 
`authority: "https://login.microsoftonline.com/organizations"`
`authority: "https://login.microsoftonline.com/common"`

But if I try to use my tenantId or name (`authority: "https://login.microsoftonline.com/<tenant_name_or_id>"`) with my organizational account the logout url doesn't get triggered.

## Regression
I haven't tried a previous version.

## Configuration
```js
MsalConfig: {
        auth: {
            clientId: "",
            authority: "https://login.microsoftonline.com/<my_tenenat_id_or_name>",
            redirectUri: "https://localhost:30444",
            postLogoutRedirectUri: "https://localhost:30444/logout"
        },
        cache: {
            cacheLocation: "sessionStorage",
            storeAuthStateInCookie: false,
        }
}
```

This the relevant sections of the manifest of my app registered in the tenant:

```json
"logoutUrl": "https://localhost:30444/logout"
[...]
"replyUrlsWithType": [
		{
			"url": "https://localhost:30444",
			"type": "Spa"
		},
		{
			"url": "https://localhost:30444/logout",
			"type": "Web"
		}
]
```

## Reproduction steps
1. call msal.logout();

## Expected behavior
The page should redirect back to my logout url, but it gets stuck here:

![image](https://user-images.githubusercontent.com/1071189/80578903-129b7600-8a01-11ea-8e77-05d53b3c5ca8.png)

## Browsers
Tried with Chrome 81.0.4044.129 (Official Build) (64-bit) and Firefox 75.0 (64-bit).

Thanks!

**Comment by Riff451** [comment]
I opened this, by mistake, as a bug. Sorry, it's probably more an investigation. Not sure if I can remove the label.

**Comment by SebastianPellitero** [comment]
I still have the same issue.

**Comment by Riff451** [comment]
> I still have the same issue.

Hi, I have not retried recently. Did you try with the latest version, 2.0.0-beta.2? When I tried it was 2.0.0-beta.0 Thanks.

**Comment by jasonnutter** [comment]
Closing, as this is an issue with AAD.
