### ISSUE TITLE
Login screen "Loader" disappears before custom policy is executed

### ISSUE THREAD

**Issue by cubogdan** [AzureAD/microsoft-authentication-library-for-js#1570]
## Library
- [X] `msal@1.3.0`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework
React v16 (not related)

## Description
After you login inside the popup, the loader starts while the calls are made, but stops before all the calls are finished. ![Here's a GIF showing the issue.](https://user-images.githubusercontent.com/19728050/80704500-58356d00-8aed-11ea-8fc6-e312536cc2f3.gif)

## Regression
The previous version we used was 1.2.1 and the bug was still present

## Configuration
Please provide your MSAL configuration options.

We're using 3 custom policies:
[B2C_1A_signup_signin](https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack/blob/master/LocalAccounts/SignUpOrSignin.xml)
[B2C_1A_TrustFrameworkBase](https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack/blob/master/LocalAccounts/TrustFrameworkBase.xml)
[B2C_1A_TrustFrameworkExtensions](https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack/blob/master/LocalAccounts/TrustFrameworkExtensions.xml)

## Reproduction steps
See the attached GIF

## Expected behavior
The Loader should be visible until all the login flow is complete and the pop closes/user redirected

I'm not sure I provided all the info that's needed for this, so if there's anything else I can provide, please ping me. 

If this isn't the right place to report this, any suggestion to where should it be reported would help.

**Comment by tnorling** [comment]
@cubogdan Apologies for the delayed response. This is an issue with the B2C service. Please file a support ticket with the B2C team by following the instructions here: https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options

They can help you out further, they may ask for a public repro link or additional data. You can also link this Github issue in the support request.
