### ISSUE TITLE
Add SendX5c support

### ISSUE THREAD

**Issue by zivazvex** [AzureAD/microsoft-authentication-library-for-js#1571]
We are currently working with SNI - Subject Name and Issuer Authentication.

While the .NET library has this feature:
AuthenticationResult result = await authApp.AcquireTokenForClient(defaultScopes)
                    .WithSendX5C(_useSubjectAndIssuerAuth)
                    .ExecuteAsync()
                    .ConfigureAwait(false);

The JS does not support it yet.

We would like to have this feature on this library as well.

**Comment by jasonnutter** [comment]
@zivazvex This feature is for Confidential Clients, correct? If so, we would support it in MSAL Node (which will support Confidential Clients), but not our client-side libraries, which only support public clients.

cc: @sameerag @sangonzal
