### ISSUE TITLE
MSAL appends an # after login redirection

### ISSUE THREAD

**Issue by onlyann** [AzureAD/microsoft-authentication-library-for-js#1579]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [X] `msal@1.3.0` 

## Description

Since MSAL 1.3.0 , once a user authenticates and is redirected back to the web application, a # is appended to the URL.
The login flow is working as expected. It is just appendin a #. This only happens when the user doesn't already have a valid token. 

## Security
Is this issue security related?
No

## Regression
Did this behavior work before?
Yes in msal 1.2.2

## Configuration
Please provide your MSAL configuration options.
```
{
      auth: {
        clientId: config.clientId,
        postLogoutRedirectUri: window.location.origin,
        redirectUri: window.location.origin
      },
      cache: {
        cacheLocation: "localStorage",
        storeAuthStateInCookie: true
      }
```

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
Login using `loginRedirect` flow.

## Expected behavior
I don't expect a `#` to be present if it was not part of `redirectUri` .

## Browsers
I haven't tried all browsers but could reproduce on both Chrome and Firefox.

**Comment by tnorling** [comment]
@onlyann This is a side-effect of removing an unnecessary redirect in previous versions. The token is returned in the hash of the url, so when msal gets the response it extracts the token, saves it, and clears the hash by setting `window.location.hash=""` which, unfortunately, does leave a `#` in the url. Previously we set `window.location.href=loginRequestUrl` which would do an additional refresh of the page but would rid the url of the `#`. If the leftover hash is undesired you can have your `handleRedirectCallback` set the `window.location.href` to your desired page and have the same functionality as before.

**Comment by onlyann** [comment]
That makes sense. Thank you. I’ll close the issue then.
