### ISSUE TITLE
is loginPopUp the only way? 

### ISSUE THREAD

**Issue by jrmcdona** [AzureAD/microsoft-authentication-library-for-js#158]
Hello,  I am using the v2 endpoint for Oauth.  

Figured I would use the MSAL to make things easier.  

I am looking to avoid the popup and just have the flow where you go to the login screen then redirect back to the app.

I am only seeing loginPopup examples.  

Thanks

**Comment by jmprieur** [comment]
@jrmcdona there is also a redirect sample: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/devApps/VanillaJSTestApp/index_LoginRedirect.html

**Comment by jrmcdona** [comment]
That works thanks
