### ISSUE TITLE
Redirect after login is not working as expected

### ISSUE THREAD

**Issue by ktikku** [AzureAD/microsoft-authentication-library-for-js#1580]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.0.0-beta.0` 
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework

`React v16.3.1`

## Description

I am calling `loginRedirect()` method, I get redirected to the redirect uri `https://localhost:3000` provided while configuring the client and then again to the page from where `loginRedirect()` was called  from - `https://localhost:3000/login`.
And I get these messages.
`[Fri, 01 May 2020 13:30:15 GMT] :  : 1.0.0-beta.0 : Info - State was detected - nonce should be available.
index.es.js:3673 [Fri, 01 May 2020 13:30:15 GMT] :  : 1.0.0-beta.0 : Info - No tokens found, creating new item.
`

## Security
Is this issue security related?

## Regression
Did this behavior work before?

## Configuration

```js
const userAgentApplicationConfig = {
    auth: {
        clientId: <CLIENT_ID>,
        redirectUri: 'https://localhost:3000',
        authority: 'https://login.microsoftonline.com/<TENANT_ID>'
    }
}

// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps

1. call `loginRedirect()` method
2. the app gets redirected back to `https:localhost:3000` and then to the page when `loginRedirect()` was called from - `https://localhost:3000/login`

## Expected behavior

The app gets redirected back to the redirect URI provided while configuring the client. 
`https:localhost:3000`

## Browsers
Is this issue browser-specific? If so, please detail which browsers are impacted (e.g. IE 11, Safari).

**Comment by tnorling** [comment]
@ktikku Please set `navigateToRequestUrl: false` in your `auth` config if you do not want to return to the page that initiated the request. This is set to `true` by default.

**Comment by ktikku** [comment]
`navigateToRequestUrl:false ` didn't work for me.
I went inside the msal object and found `navigateToLoginRequestUrl: true` as a default value.
Changing it to `navigateToLoginRequestUrl: false` did the trick for me.
Thanks for the help!
Also, apologies for labelling the question as a bug.

**Comment by tnorling** [comment]
@ktikku Apologies for giving you the wrong parameter name! That's my bad. Glad you got it working though, thanks for confirming. Let us know if you have any other questions.
