### ISSUE TITLE
What's the reason of the change in UrlUtils.replaceTenantPath() in fix #1299

### ISSUE THREAD

**Issue by reseul** [AzureAD/microsoft-authentication-library-for-js#1583]
## Library
- [X] `msal@1.3.0`

## Description
I noticed change #1299 updated UrlUtils.replaceTenantPath() as well, and I wonder whether it was intended:

`        -if (tenantId && (pathArray.length !== 0 && (pathArray[0] === Constants.common || pathArray[0] === SSOTypes.ORGANIZATIONS))) {
        +if (tenantId && (pathArray.length !== 0 && pathArray[0] === Constants.common)) {
`
The code is used when caching an incoming token, by tweaking the authority.
So in msal 1.2.2:
- tokens acquired using common or organizations authority are cached with a tenant'ed authority in the key
- tokens acquired using consumers authority are cached as is

Whereas in msal 1.3.0:
- tokens acquired using common authority are cached with a tenant'ed authority in the key
- tokens acquired using organizations or consumers authority are cached as is.

None of these behaviors is particularly consistent, but external code may have subtle dependency on how the things work internally.

So I'd like to understand whether the change is due to the unfortunate use of SSOTypes.ORGANIZATIONS in the old code (even though this has nothing to do with SSO), or there's some other thing/development I'm missing.

Thanks

Cc @jasonnutter

**Comment by jasonnutter** [comment]
cc: @sameerag 

> but external code may have subtle dependency on how the things work internally.

Can you elaborate on this? Where you relying on the cache keys in local storage?

**Comment by reseul** [comment]
Not that bad, but we do need access to the plain (JWT) id token, since it is sent to a backend for a policy reason/purpose (old architecture, a given).
I think getAccount() returns the parsed value, even though I see there's some attempt to eventually have them both (the binary and the parsed) in the same object.

We do call GetCachedToken. It's not that kosher (it's not marked as public), but for the sake of the argument let's say we call acquireTokenSilent (scope: client_id, dont_go_to_network: true):

- we initialize msal.js with <base>/organizations authority
- we call loginRedirect
- the received id_token is cached as an access token, with a <base>/tenantid key (in 1.2.2), or the 
<base>/organnizations (1.3.0)
- we want to extract the plain token, so we're trying to be as less ambiguous as possible, so we pass "authority" in the AuthenticationParameters. This is the point where we rely on how the library works: we pass <base>/tenantid in 1.2.2 (we extract the tenantid from the parsed id_token), we would have to change for 1.3.0.
Various scenarios can led to multiple id tokens stored for various authorities, hence we need the authority filter.

**Comment by pkanher617** [comment]
@reseul The `acquireTokenSilent` API should allow you to to make this lookup without having to use the private API, the id token comes back as a parameter in the return value of `acquireTokenSilent()`. The "going to network" portion only happens if the id_token is expired, and it will attempt to get you a valid token. `getCachedToken` by itself will only remove it from the cache if it is expired. You can also set forceRefresh=true if you want to guarantee a token renewal. 

@sameerag can provide more context for the change to `replaceTenantPath()`.

**Comment by reseul** [comment]
@pkanher617 thanks, and yes, I understand the merits of calling a public API. There's a lot to discuss here about our scenarios, etc., but the problem is somewhat orthogonal.
We can easily end up (in our case) with several cached id_tokens as access tokens, one obtained with an "organizations" authority (we wanted home tenant), and some with particular tenant'ed authorities.
Trying to acquire the "right" cached token if we want the "home tenant" one changes for us with the new msal.js version. In 1.2.2 we use the tenant'ed authority as filter (since the authority of the cached token is tweaked), whereas in 1.3.0 we'd have to special case it.

We already had to special case "consumers", that has never been replaced with the specific guid by msal.js.
So we have ways, either way. 
It's just that I wanted to understand whether the change was on purpose, whether there's other similar changes planed, etc., so we can adapt accordingly.

**Comment by sameerag** [comment]
`replaceTenantPath` is not really a needed change for `domain_hint` changes; since we removed all occurrences  of `Organizations` in our code, I thought deleting it makes sense. If there is valid reason we need that i.e. when the users pass `/Organizations` as authority, we can consider adding this again.

**Comment by reseul** [comment]
Yes, we do pass "organizations"-like authorities in some scenarios. 
And thanks for confirming the change was a side effect of the unfortunate use of SSOTypes.ORGANIZATIONS, when in that context "organizations" has nothing to do with the domain_hint parameter.

The main problem is the change of behavior, and having to adapt to it when dot versions are released.
This may not be documented as such, but the way the keys for tokens are computed transpires through the API, from a semantic point of view.

In other words, the behavior of MSAL.JS is to apply some logic (in replaceTenantPath) that changes the authority in the cache key compared to what user provided in this.config.authority.
Retrieving the cached token by passing an authority filter requires the dev be aware of that logic.
If the logic changes, the filter has to change.

In 1.2.2 I can pass an authority based on id_token.tid, simple.
In 1.3.0 I would have to first try id.token_id, or if it fails, base/consumers. Variations exist, and I may not get all the details crisply, but the point still stands.

**Comment by reseul** [comment]
@sameerag Should I convert/create a bug for this? The change breaks our current code, the workaround on our side would be messy, and we seem to all have agreed the change had nothing to do with hints, but with authorities.

**Comment by jasonnutter** [comment]
@reseul No, we'll use this issue for tracking. We'll discuss this as a team and I'll follow up here.
