### ISSUE TITLE
Token not available after redirect

### ISSUE THREAD

**Issue by ktikku** [AzureAD/microsoft-authentication-library-for-js#1585]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@ 2.0.0-beta.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
I'm using React framework.
When I login using `loginRedirect()` method, I get redirected back to the redirect uri I had provided - `https:localhost:3000`. 
 After the redirect (back into my page) when `componentDidMount()` is called, `msalInstance.getAccount()` returns `null` as token hasn't been created yet. 
After this the redirect callback is triggered.
`componentDidMount()` gets called before Trigger of redirect callback and token creation. 
Hence I have to reload the page after the redirection so that `msalInstance.getAccount()` present inside `componentDidMount()` works.
How can I handle this or is it a bug?

I was using `msal v1.3.0` and I didn't use to get this issue.

![image](https://user-images.githubusercontent.com/50620678/80873084-b9b73080-8cd3-11ea-8d07-3cf851f03f59.png)

**Comment by tnorling** [comment]
@ktikku This behavior should be fixed by #1490 and will be included in the next release. @pkanher617 can share more info about when this might be available on npm

**Comment by ktikku** [comment]
Thanks for the update @tnorling

**Comment by pkanher617** [comment]
@ktikku Could you please try the [new version of msal-browser](https://www.npmjs.com/package/@azure/msal-browser) and see if you are still getting this issue?

**Comment by ktikku** [comment]
@pkanher617 The issue got fixed, thanks!

**Comment by ktikku** [comment]
Hi,
I'm getting the Bearer token.
But I'm using `acquireTokenSilent` method to query to check whether the user is able to fetch the id and access_token silently. 
I have written a check to determine whether the user is logged in based on the above check.

The moment I get redirected back to my app, acquireTokenSilent` call fails. On refresh, I'm able to silently fetch the id token silently.

This wasn't the case with msal v1.3.0

**Comment by ktikku** [comment]
I am getting the same error despite using `handleRedirectPromise` because of the delay.

**Comment by ktikku** [comment]
I figured out how to work with `handleRedirectPromise`.
Thanks!

**Comment by khloe19** [comment]
hi @ktikku how do you resolved the issue using `handleRedirectPromise`. I'm having issues after I login and it didn't go back to my `handleRedirectPromise `but instead go straight to my `componentDidMount`.
