### ISSUE TITLE
msal-browser sample not working 

### ISSUE THREAD

**Issue by taysco** [AzureAD/microsoft-authentication-library-for-js#1587]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x ] `@azure/msal-browser@2.0.0-beta0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
If you are using a framework, please provide the framework and version (e.g. Angular v8, React v16, etc).
React v16

## Description
The sample doesn't appear to work with the packages in npm. When are you planning to synchronize these?

The public package contains handleCallbackResponse whereas the sample now contains handleCallbackPromise, as well as a bunch of error handling and interactionrequired stuff.

Can you advise on how to proceed? I am desperately trying to get our app running in the Teams iframe now that the redirect is fixed. The sample code is all over the place though and I am not sure which one to use.

yarn deps:
info Direct dependencies
├─ @azure/msal-browser@2.0.0-beta.0
└─ msal@1.3.0
info All dependencies
├─ @azure/msal-browser@2.0.0-beta.0
├─ @azure/msal-common@1.0.0-beta.0
└─ msal@1.3.0
Done in 26.23s.
 

## Security
No

## Regression
Probably

## Configuration
N/A

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
1. yarn add @azure/msal-browser
2. try to incorporate latest sample VanillaJSTestApp2.0
3. missing deps

## Expected behavior
The sample actually works.

## Browsers
No

**Comment by pkanher617** [comment]
@taysco the samples in the repository are dev samples, and are meant to work with the local version of the library. We have a sample [here](https://github.com/Azure-Samples/ms-identity-javascript-v2) which is intended to be current with the npm package.

**Comment by taysco** [comment]
Thanks. When are you planning the push the new versions? There's a lot of new functionality in the newer releases that really need to be publicly available. I don't really want to set up a npm feed just for this :) This feature should really be prioritized imo.

**Comment by pkanher617** [comment]
@taysco Sorry for the delay, we are preparing for a full release and I haven't been able to do a new beta version just yet. I will try to get a new version out shortly.

**Comment by pkanher617** [comment]
@taysco I have pushed a new release of msal-browser and msal-common to npm today. I am working on updating the quickstart sample.

**Comment by taysco** [comment]
Awesome, thank you very much. Great work btw.
