### ISSUE TITLE
Compilation failed with msal-browser package using TypeScript

### ISSUE THREAD

**Issue by chunliu** [AzureAD/microsoft-authentication-library-for-js#1590]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.
@azure/msal-browser@2.0.0-beta.0

## Framework
If you are using a framework, please provide the framework and version (e.g. Angular v8, React v16, etc).
React

## Description
I installed the @azure/msal-browser@2.0.0-beta.0 package in a TypeScript project. When compile the project with tsc, it failed with the following error: 

```
node_modules/@azure/msal-browser/dist/app/PublicClientApplication.d.ts:3:30 - error TS2307: Cannot find module '../types/AuthCallback'.

3 import { AuthCallback } from "../types/AuthCallback";
```

types/AuthCallback could not be found in node_modules. 

## Security
Is this issue security related?
No

## Regression
Did this behavior work before?
Not sure

## Configuration
Please provide your MSAL configuration options.

## Reproduction steps
1. `npm install @azure/msal-browser`.
2. Initialize PublicClientApplication object.
3. Compile the code.

## Expected behavior
Include types/AuthCallback in the npm package. 

## Browsers
Is this issue browser-specific? If so, please detail which browsers are impacted (e.g. IE 11, Safari).
No

**Comment by tnorling** [comment]
@chunliu A fix for this was merged into `dev` in #1517 and will be included in the next release. Thanks for your patience while we work out the kinks in this new library!
