### ISSUE TITLE
Invalid token Account connected to windows edge

### ISSUE THREAD

**Issue by dennisblokland** [AzureAD/microsoft-authentication-library-for-js#1591]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [x] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework
Angular v9

## Description
I send the token returned by acquireTokenSuccess to "https://graph.microsoft.com/v1.0/me" this work fine. But when using edge and choosing an count that is "Connected to windows" the returned token is invalid.

## Configuration
```js
      [ MsalModule.forRoot({
         clientID: msal.clientid,
         redirectUri: msal.redirecturi,
         consentScopes: ['openid profile'],
         navigateToLoginRequestUrl: true,
         authority: "https://login.microsoftonline.com/common/",
         validateAuthority: true,
     })],
```

## Browsers
i used edge 44 it also applies to other versions

**Comment by jasonnutter** [comment]
@dennisblokland Can you provide more details about why the token is invalid?

**Comment by dennisblokland** [comment]
i think i copied it wrong when validating it. sorry for any inconvenience
