### ISSUE TITLE
postLogoutRedirectUri redirects user to Microsoft office website even when I have not mentioned it anywhere

### ISSUE THREAD

**Issue by sandesai** [AzureAD/microsoft-authentication-library-for-js#1594]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [x] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.x.x`
- [x] `@azure/msal-angularjs@1.x.x`

## Description
Please provide your question here, including as much relevant details as possible.

Examples: 
> "How do I use MSAL with Vue.js"
> "How do I SSO between tabs?"
> "How do I use MSAL to protect my custom Web API?"
> "How can my app support multiple AAD tenants?"
> "When will my scenario be supported?"
> "When will this framework be supported"

**Comment by sandesai** [comment]
After logging out, I am redirected to office.com with the following URL. It somehow overrides the configuration that I have given.
https://login.microsoftonline.com/common/oauth2/authorize?client_id=<clientid>&redirect_uri=https%3A%2F%2Fwww.office.com%2Flanding&response_type=code%20id_token&scope=openid%20profile&response_mode=form_post&nonce=637242053377147792.ZmE1OTMwZGQtZmMxOS00ZjAzLWI0OTEtMGZkY2FjY2U2Nzk2ZmRjYjhjMzktYjNkNy00ZGRjLWIwMzMtYTIwMzFhZWVjYjk3&ui_locales=en-US&mkt=en-US&client-request-id=<client-request-id>&state=MNJqtJpawyVxi-aka2dq0M2BYENLWDA0U5kaV7epKWrssA1fUa_-W_NLTIrfaGD5EhPOx3ijSEnK8S6TqK1nbeif57uXbUC4mpka7FudDc66W17zW36D-OY_elMsNFmk3JZLABdamTea9e1PJNaKRRQdzbpQ9qTnuLZ99ddmL2mpfDai4Nefuoyv01ii56U5Xcth-jC4PXNzrGvZu3ifiJS4eNHykb0voPIhUkHABjYl_8aQ5oUynn5syAaldW4oNBsm9KYM085FWABDn4fNxw&x-client-SKU=ID_NETSTANDARD2_0&x-client-ver=6.3.0.0

this is my configuration
 auth: {
                clientId: environment.clientId,
                authority: environment.authority,
                redirectUri: environment.redirectUri,
                postLogoutRedirectUri : "http://localhost:4200/logout",
                navigateToLoginRequestUrl: true,
              },

and during my app registration, I have given 
![image](https://user-images.githubusercontent.com/49960606/80988648-c76ad400-8e01-11ea-9555-aabca95b92fe.png)

**Comment by pkanher617** [comment]
@sandesai I'm a bit confused, could you explain what you are expecting to occur when you logout vs what is actually happening? When you say you are "redirected to office.com with the following url", I'm not sure what you mean.

I see that the redirect URL in the url is the office page, which won't work given your registration. I also see `response_type=code`, which leads me to believe that you are using the @azure/msal-browser package (which is not what you have indicated in the template).

A Fiddler trace or some sort of network log may also help.

**Comment by sandesai** [comment]
> @sandesai I'm a bit confused, could you explain what you are expecting to occur when you logout vs what is actually happening? When you say you are "redirected to office.com with the following url", I'm not sure what you mean.
> 
> I see that the redirect URL in the url is the office page, which won't work given your registration. I also see `response_type=code`, which leads me to believe that you are using the @azure/msal-browser package (which is not what you have indicated in the template).
> 
> A Fiddler trace or some sort of network log may also help.

Hi Prithvi,

Thank you for the response.

I have not explicitly installed @azure/msal-browser package. It might have been added as part of @azure/msal-angular package if I am not wrong.

Coming back to your question,I would like my application to go back to http://localhost:4200 after logout as I have mentioned in postLogoutRedirectUri in **msal** configuration instead of redirecting me to log in to Microsoft office. 

Step 1 : User clicks on log out
Here logout URL is my intended URL i.e; http://localhost:4200/
![image](https://user-images.githubusercontent.com/49960606/81021699-be95f480-8e39-11ea-9861-4b449ff3c5d4.png)

Step 2 : Once user select the account, this page is displayed
![image](https://user-images.githubusercontent.com/49960606/81021749-e5542b00-8e39-11ea-87b4-de082108bb50.png)

Step 3 : Next page is this where the redirect URL is suddenly changed to office.com
![image](https://user-images.githubusercontent.com/49960606/81021811-07e64400-8e3a-11ea-8e90-5a803e868b89.png)

It should redirect me to localhost:4200 as mentioned in postLogoutRedirectUri is what I am expecting.

Regards,

**Comment by pkanher617** [comment]
@sandesai if you are using the @azure/msal-angular package, it is using the msal package, not the @azure/msal-browser package. Which is why I'm a bit confused why you are getting response_type=code in Step 3, as @azure/msal-angular only supports the implicit flow (where response_type=token or response_type=id_token). Are you using another service, like MSAL.NET, on the server side? I suspect what is happening is that the logout is working correctly, and upon returning to localhost:4200 another piece of code is kicking off an authentication request. I can't be sure without knowing more about the application scenario and the actual usage of the @azure/msal-angular package.

**Comment by sandesai** [comment]
@pkanher617 
I am using @azure/msal-angular package to integrate Azure Active Directory in my frontend Angular application. I have a node server running in the background. 

I have registered both of my applications in the azure portal. The app successfully logs in and everything else works properly apart from the logout scenario.

The package: [(https://www.npmjs.com/package/@azure/msal-angular)]

The sample application that I have followed: [https://github.com/Azure-Samples/active-directory-javascript-singlepageapp-angular]

I have attached a fiddler screenshot which captures the logout scenario
![image](https://user-images.githubusercontent.com/49960606/81103731-76311200-8edf-11ea-9822-b59509038c74.png)

Thank you,

**Comment by pkanher617** [comment]
@sandesai Could you send me the Fiddler trace in an email? My email is available on my profile.

I don't believe msal javascript is making the additional call with the office.com redirect uri, but I would like to take a more detailed look at the Fiddler trace to make sure.

**Comment by sandesai** [comment]
@pkanher617 

Unfortunately, I cannot share any more details than I already did due to my client's privacy concerns. 

Regards,

**Comment by pkanher617** [comment]
Understood, unfortunately I can't really help unless I know where the call in Step 3 is originating from. Neither the [@azure/msal-angular](https://www.npmjs.com/package/@azure/msal-angular) package nor the [msal](https://www.npmjs.com/package/msal) package craft URLs with response type=code.

If you can reproduce the issue in one of the dev samples in this repo, we may be able to identify the cause faster.

**Comment by pkanher617** [comment]
> https://login.microsoftonline.com/common/oauth2/authorize?client_id=&redirect_uri=https%3A%2F%2Fwww.office.com%2Flanding&response_type=code%20id_token&scope=openid%20profile&response_mode=form_post&nonce=637242053377147792.ZmE1OTMwZGQtZmMxOS00ZjAzLWI0OTEtMGZkY2FjY2U2Nzk2ZmRjYjhjMzktYjNkNy00ZGRjLWIwMzMtYTIwMzFhZWVjYjk3&ui_locales=en-US&mkt=en-US&client-request-id=&state=MNJqtJpawyVxi-aka2dq0M2BYENLWDA0U5kaV7epKWrssA1fUa_-W_NLTIrfaGD5EhPOx3ijSEnK8S6TqK1nbeif57uXbUC4mpka7FudDc66W17zW36D-OY_elMsNFmk3JZLABdamTea9e1PJNaKRRQdzbpQ9qTnuLZ99ddmL2mpfDai4Nefuoyv01ii56U5Xcth-jC4PXNzrGvZu3ifiJS4eNHykb0voPIhUkHABjYl_8aQ5oUynn5syAaldW4oNBsm9KYM085FWABDn4fNxw&x-client-SKU=ID_NETSTANDARD2_0&x-client-ver=6.3.0.0

@sandesai Looking at the url given above, the x-client-SKU parameter shows this request coming from the MSAL.NET library. I suggest looking at their github repo here for more context: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet
