### ISSUE TITLE
AADB2C90117: The scope 'user.read' provided in the request is not supported.

### ISSUE THREAD

**Issue by beezital** [AzureAD/microsoft-authentication-library-for-js#1597]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
When trying the sample for Angular 9 attempting to get the user profile (scope user.read) ends up with the error "AADB2C90117: The scope 'user.read' provided in the request is not supported." in the browser.
I am using a user flow for my tenant (authority = "https://<instance>/tfp/<tenant>/<policyName>/")
Why do I get this error?

**Comment by pkanher617** [comment]
@beezital I'm assuming you are using a B2C authority.

`user.read` is a Microsoft Graph scope. I think there may be some extra configuration required to set up Microsoft Graph for B2C, please make sure you follow the [instructions here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/microsoft-graph-get-started?tabs=applications).

**Comment by beezital** [comment]
@pkanher617 yes I am using B2C authority (sorry, my post got stripped. I meant authority = `https://_TENANT_.b2clogin.com/tfp/_TENANT_.onmicrosoft.com/b2c_1_signupsignin/` ).
Thanks for the link. I've followed the [Grant API Access](https://docs.microsoft.com/en-us/azure/active-directory-b2c/microsoft-graph-get-started?tabs=app-reg-preview#grant-api-access) instructions, but I could not get the Angular 9 sample to work (I'm new to this openid/oauth subjet).

![image](https://user-images.githubusercontent.com/63583702/81106578-26217200-8f16-11ea-82e3-ec9953fbdc4d.png)

I also found this post that worries me...
https://stackoverflow.com/a/60481839/2742007
Do you have further hints?

**Comment by pkanher617** [comment]
@beezital I am talking to some B2C service team members to better understand how to implement MS Graph in B2C tenants. Will update when I have more information.

**Comment by beezital** [comment]
Some news on my side after setting up and experimented with my own API.
For the MS Graph request,
if I change the protected resource from

`'https://graph.microsoft.com/v1.0/me', ['user.read']`
to
`'https://graph.microsoft.com/v1.0/me', ['https://graph.windows.net/User.Read']`

I no longer get the AADB2C90117 error, but a 401 (Unauthorized):

`HttpErrorResponse: {"headers":{"normalizedNames":{},"lazyUpdate":null},"status":401,"statusText":"Unauthorized","url":"https://graph.microsoft.com/v1.0/me","ok":false,"name":"HttpErrorResponse","message":"Http failure response for https://graph.microsoft.com/v1.0/me: 401 Unauthorized","error":{"error":{"code":"InvalidAuthenticationToken","message":"Access token validation failure."}}}`

**Comment by pkanher617** [comment]
@beezital The doc you followed was correct. The only change you should make is to add you b2c authority uri to your scope (instead of the graph resource uri).
```javascript
'https://graph.microsoft.com/v1.0/me', ["https://authorityuri/user.read"]
```
