### ISSUE TITLE
Any chance of publishing an updated @azure/msal-browser to NPM?

### ISSUE THREAD

**Issue by HarryGifford** [AzureAD/microsoft-authentication-library-for-js#1598]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
There have been a bunch of useful bug fixes and updates checked into the dev branch. Please could you publish an updated `@azure/msal-browser` to NPM? In particular, for me, #1543 and #1517 would be really useful.

**Comment by pkanher617** [comment]
@HarryGifford Running some final tests now to publish a new version. Will close and update this issue when it is available.

**Comment by pkanher617** [comment]
@HarryGifford I found a bug with multiple resources around the refresh token, as well as needed to update docs for the new release, so I was a bit delayed. I finished the work, just waiting on reviews from the team and then I will be able to publish. PR here: https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/1603

**Comment by pkanher617** [comment]
@HarryGifford @azure/msal-browser v2.0.0-beta.1 and @azure/msal-common v1.0.0-beta.1 are available on npm.

**Comment by chunliu** [comment]
@pkanher617 index.d.ts is missing from @azure/msal-browser v2.0.0-beta.1. Build failed with the following error: 
```
error TS7016: Could not find a declaration file for module '@azure/msal-browser'. '/home/chunliu/github/gotodo/frontend/node_modules/@azure/msal-browser/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/azure__msal-browser` if it exists or add a new declaration (.d.ts) file containing `declare module '@azure/msal-browser';`

2 import * as msal from "@azure/msal-browser";
                        ~~~~~~~~~~~~~~~~~~~~~
```
