### ISSUE TITLE
Error message contains EUII (login_hint) which compromises Microsoft Privacy Policy

### ISSUE THREAD

**Issue by muying-cui** [AzureAD/microsoft-authentication-library-for-js#1599]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.2.1`

## Description
We have noticed that in one particular error message, the login_hint is present and that compromises the privacy policy, please take a look into it and see what fix can be done in MSAL.js for that.

Error msg: "URL navigated to is https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=id_token token&scope=394866fc-eedb-4f01-8536-3ff84b16be2a%2F.default%20openid%20profile&client_id=b23dd4db-9142-4734-867f-3577f640ad0c&redirect_uri=https%3A%2F%2Fword-edit.officeapps.live.com%2Fwe%2FWacOAuth.html&state=f382f9de-8979-4d06-9ed8-70b12e2c783d&nonce=b303cd2b-a76d-4484-9e6d-68ee4d2fbe4e&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=1.2.1&**login_hint=<REDACTED>**&client-request-id=53f30bd6-7f70-48e8-9c1c-00c01f459fe9&prompt=none&response_mode=fragment, Token renewal operation failed due to timeout."

## Security
**This issue is Privacy related, should have high priority.**

## Reproduction steps
1. This error message is tied to timeout.

## Expected behavior
In the error message, login_hint or any other value contains user identifier should be removed.

**Comment by muying-cui** [comment]
@jasonnutter Probably you are already taking care of the extra check here, but I want to confirm that as part of this bug fix, we are also looking at other possible places where a login_hint or any other EUII can be in an unexpected presence. Thank you!

**Comment by jasonnutter** [comment]
@muying-cui Yes, a couple other messages have been adjusted.
