### ISSUE TITLE
invalid_grant of 9002313 returned when sign in AAD with personal Outlook account

### ISSUE THREAD

**Issue by kafka-yu** [AzureAD/microsoft-authentication-library-for-js#1611]
Hi There,

recently, we found in our Teams app when we sign in via AAD with personal Outlook account, it will show error as below:
```json
 {
    "error": "invalid_grant",
    "error_description": "AADSTS9002313: Invalid request. Request is malformed or invalid.\r\nTrace ID: 3099dbcf-726a-4cda-aaae-6e4012332c00\r\nCorrelation ID: b46949b3-a406-48d4-8cb5-179eba1d7487\r\nTimestamp: 2020-05-06 09:52:09Z",
    "error_codes": [
        9002313
    ],
    "timestamp": "2020-05-06 09:52:09Z",
    "trace_id": "3099dbcf-726a-4cda-aaae-6e4012332c00",
    "correlation_id": "b46949b3-a406-48d4-8cb5-179eba1d7487",
    "error_uri": "https://login.microsoftonline.com/error?code=9002313"
}
```
It works fine for the normal O365 accounts.
Do you know the reason?
We have scopes of the request:

```jsson
[
 'profile',
 'openid',
 'User.Read',
 'User.Read.All',
 'Calendars.ReadWrite',
]
```
One of the scope needs the admin consent.

**Comment by pkanher617** [comment]
@kafka-yu Could you please use the templates when creating an issue? It will allow us to identify your issue faster.

**Comment by kafka-yu** [comment]
@pkanher617 thanks, I created new one here:
https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1614
