### ISSUE TITLE
Safari Login Issues

### ISSUE THREAD

**Issue by lnadudva** [AzureAD/microsoft-authentication-library-for-js#1612]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.3.0` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
Angular 8

## Description
After a successful login using redirectToLogin() (or calling acquireTokenRedirect()) the app redirects to the given redirectUri and throws two errors:

- Refused to display 'https://...' in a frame because it set 'X-Frame-Options' to 'DENY'.
- 'https://...' Failed to load resource: the server responded with a status of 400 (Bad Request)

The redirectUri page is not protected by any guard. After navigating away from here to a page which is protected by a guard which calls acquireTokenSilent() the following error is thrown:

- Auth Error (token_renewal_error): URL navigated to is 'https:/...', Token renewal operation failed due to timeout.

This issue only appears on Safari 13.1 and only when the "Prevent cross-site tracking" setting under the Privacy tab is checked. On Chrome ver 81.0.4044.138 everything works as intended.

To fix this I've tried the methods listed [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1437#issuecomment-611263997), acquireTokenRedirect() gave me an infinite loop and acquireTokenPopup() can't really be used because Safari blocks popups by default, and it didn't work too.

## Security
Is this issue security related?
Shouldn't be.

## Regression
It appeared with msal 1.2.2 too.

## Configuration
Please provide your MSAL configuration options.

```js
 {
      clientId: '1234',
      authority: 'https://..',
      redirectUri: `http://localhost:4200/home/redirect`,
      validateAuthority: false,
      navigateToLoginRequestUrl: false,
      postLogoutRedirectUri: `http://localhost:4200/home/landing`,
    },
    cache: {
      cacheLocation: 'sessionStorage',
    }
}
```

## Expected behavior
After a succesful login the application should be able to have a token and safely navigate away from the redirect page.

## Browsers
Safari 13.1

**Comment by pkanher617** [comment]
@lnadudva Are you using a B2C or AAD authority? Could you also post a small snippet of how you are calling acquireTokenRedirect?

There are known issues caused by Safari's tracking prevention (see [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-known-issues-safari-browser)) which will cause acquireTokenSilent() to fail token renewal regardless of whether or not you have an active session. We can probably look into why the acquireTokenRedirect is looping however.

**Comment by pkanher617** [comment]
@lnadudva Could you try reproducing this with [a sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples) in our repo?

**Comment by lnadudva** [comment]
@pkanher617 Thank you for your help! We are using B2C.
I forgot to mention that this issue happens when using Google login
Here are the code segments which handle the login flow and the guarding of the routes:

```js
import { Injectable } from '@angular/core';
import { environment } from '@environments/environment';
import { AuthError, AuthResponse, UserAgentApplication } from 'msal';
import { TemporaryCacheKeys } from 'msal/lib-commonjs/utils/Constants';

@Injectable({
  providedIn: 'root',
})
export class AuthService extends UserAgentApplication {
  constructor() {
    super(environment.authConfig);
    this.handleRedirectCallback((error: AuthError, response: AuthResponse) => {
      const url = this.cacheStorage.getItem(TemporaryCacheKeys.LOGIN_REQUEST);
      // We should change this to a nicer solution, unfortunately it is not clear how to do that
      // in the current version of msal (1.2.1).
      // https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1288
      window.location.href = url;
    });
  }

  public getLoginRequestKey(): string {
    return this.cacheStorage.getItem(TemporaryCacheKeys.LOGIN_REQUEST);
  }

  public getToken(): Promise<AuthResponse> {
    return this.acquireTokenSilent({ scopes: environment.authScopes });
  }

  public redirectToLogin(redirectUri: string): void {
    this.cacheStorage.setItem(TemporaryCacheKeys.LOGIN_REQUEST, redirectUri);
    this.loginRedirect({ scopes: environment.authScopes });
  }

  public redirectToGetToken(redirectUri: string): void {
    this.cacheStorage.setItem(TemporaryCacheKeys.LOGIN_REQUEST, redirectUri);
    this.acquireTokenRedirect({ scopes: [environment.authConfig.auth.clientId] });
  }
}
```

```js
import { Injectable } from '@angular/core';
import { CanActivate, ActivatedRouteSnapshot, RouterStateSnapshot, UrlTree, CanLoad, Route, UrlSegment } from '@angular/router';
import { Observable } from 'rxjs';
import { AuthService } from '../services';
import { InteractionRequiredAuthError, AuthError } from 'msal';
import { ClientAuthErrorMessage } from 'msal/lib-commonjs/error/ClientAuthError';

@Injectable({
  providedIn: 'root',
})
export class AuthGuard implements CanActivate, CanLoad {
  constructor(private authService: AuthService) {}
  public canActivate(
    next: ActivatedRouteSnapshot,
    state: RouterStateSnapshot
  ): Observable<boolean | UrlTree> | Promise<boolean | UrlTree> | boolean | UrlTree {
    return this.checkLoggedIn(state.url);
  }

  public canLoad(route: Route, segments: Array<UrlSegment>): boolean | Promise<boolean> | Observable<boolean> {
    const uri = segments.reduce((path, currentSegment) => {
      return `${path}/${currentSegment.path}`;
    }, '');

    return this.checkLoggedIn(uri);
  }

  private checkLoggedIn(uri: string): Promise<boolean> {
    return new Promise((resolve, reject) => {
      this.authService.getToken().then(
        () => {
          resolve(true);
        },
        (error: AuthError) => {
          if (error.errorCode === ClientAuthErrorMessage.userLoginRequiredError.code) {
            this.authService.redirectToLogin(uri);
          } else if (error instanceof InteractionRequiredAuthError) {
            this.authService.redirectToGetToken(uri);
          }
          console.error(`Auth Error (${error.errorCode}): ${error.errorMessage}`);
          resolve(false);
        }
      );
    });
  }
}
```
The error is thrown in the guard's `checkLoggedIn()` method, and if I catch it and try to call `acquireTokenRedirect()` or `loginRedirect()` the browser starts refreshing and I get and infinite loop. The environment variables contain the same configuration values mentioned in the issue above and the authScope.

I was not able the reproduce the issue with your Angular 8 sample while using our credentials and using Google login so i decided to add @azure/msal-angular 1.0.0 to our app but the same errors were thrown with Google login in Safari.

Sidenote: The AuthService is injected in the AppComponent (root) so the AuthService constructor is invoked as soon as the app starts. This is necessary for the redirections to happen.

**Comment by adrichema** [comment]
We also have this problem when using the SharePoint App and browsing to our SharePoint Home Site with some SPFX webparts on it that make use of MSGraphClient.

**Comment by jasonnutter** [comment]
@lnadudva A couple of things:

First, it is expected that the library will not work completely if third-party cookies are disabled, as the implicit flow relies on third-party cookies.

Second, in `checkLoggedIn`, when interaction is required, you should be calling `acquireTokenRedirect` with the same scopes that were used for `acquireTokenSilent`. It appears you are using `environment.authScopes` (which I presume are access token scopes), but using `clientId` when calling `acquireTokenRedirect` (which will fetch an ID token, instead of an access token).

```js
  public redirectToLogin(redirectUri: string): void {
    this.cacheStorage.setItem(TemporaryCacheKeys.LOGIN_REQUEST, redirectUri);
    this.loginRedirect({ extraScopesToConsent: environment.authScopes });
  }

  public redirectToGetToken(redirectUri: string): void {
    this.cacheStorage.setItem(TemporaryCacheKeys.LOGIN_REQUEST, redirectUri);
    this.acquireTokenRedirect({ scopes: environment.authScopes });
  }
```

**Comment by pkanher617** [comment]
Closing for now, please let us know if you are still seeing this issue.
