### ISSUE TITLE
Token renewal operation failed due to timeout IE 11

### ISSUE THREAD

**Issue by vinusorout** [AzureAD/microsoft-authentication-library-for-js#1615]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [x] `@azure/msal-angular@1.0.0-beta.5`
- [x] `msal@1.3.0`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework
Angular 9

## Description
On windows 10, IE11 browser facing  'Token renewal operation failed due to timeout '

"Error: Uncaught (in promise): ClientAuthError: URL navigated to is https://login.microsoftonline.com/xxxxxxxxxxxx/oauth2/v2.0/authorize?response_type=id_token&scope=openid%20profile&client_id=a20846ed-4780-4d93-9fe4-7f0f32077713&redirect_uri=https%3A%2F%2Fcrbs.abc.com%2Ffa&state=eyJpZCI6Ijc0N2FhMWM2LWE0ZGYtNDhmMS05ZDYzLTA4MmZlYTViNjQ4ZCIsInRzIjoxNTg4ODY2Mzc5LCJtZXRob2QiOiJzaWxlbnRJbnRlcmFjdGlvbiJ9&nonce=3ff587f8-cc08-471b-b7b4-c028f958958b&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=1.3.0&login_hint=devvws%40abc.com&client-request-id=f000d64a-160d-4cc1-b413-b1c16683504a&prompt=none&response_mode=fragment, Token renewal operation failed due to timeout.
ClientAuthError: URL navigated to is https://login.microsoftonline.com/xxxxx/oauth2/v2.0/authorize?response_type=id_token&scope=openid%20profile&client_id=a20846ed-4780-4d93-9fe4-7f0f32077713&redirect_uri=https%3A%2F%2Fcrbs.abc.com%2Ffa&state=eyJpZCI6Ijc0N2FhMWM2LWE0ZGYtNDhmMS05ZDYzLTA4MmZlYTViNjQ4ZCIsIn"

## Configuration
export const protectedResourceMap: [string, string[]][] = [
  ['https://crbs.abc.com/security', ['xxxxxxxxxxxxx/.default']]
];

const isIE = window.navigator.userAgent.indexOf("MSIE ") > -1 || window.navigator.userAgent.indexOf("Trident/") > -1;

function MSALConfigFactory(): Configuration {
  return {
    auth: {
      clientId: 'xxxxxxxxxxxxx',
      authority: "https://login.microsoftonline.com/xxxxxxxxxxx",
      redirectUri: "https://crbs.abc.com/fa",
    },
    cache: {
      cacheLocation: "localStorage",
      storeAuthStateInCookie: isIE, // set to true for IE 11
    },
  };
}

function MSALAngularConfigFactory(): MsalAngularConfiguration {
  return {
    protectedResourceMap,
  };
}

`

## Expected behavior
It should work in IE11

## Browsers
IE11

**Comment by jasonnutter** [comment]
@vinusorout The logs for this request show the server took 4.3 seconds to response, so it is not surprising the library timed out, as the default timeout (which you can adjust via system.loadFrameTimeout) is set to 6000ms (6 seconds). Two mitigations:

1. Set a higher timeout (e.g. 10000 for 10 seconds)
2. If a request times out, retry the request (please only retry once or twice, the server will throw an error if you retry too many times).

**Comment by vinusorout** [comment]
> @vinusorout The logs for this request show the server took 4.3 seconds to respond, so it is not surprising the library timed out, as the default timeout (which you can adjust via system.loadFrameTimeout) is set to 6000ms (6 seconds). Two mitigations:
> 
> 1. Set a higher timeout (e.g. 10000 for 10 seconds)
> 2. If a request times out, retry the request (please only retry once or twice, the server will throw an error if you retry too many times).

Thanks @jasonnutter I will check this.
Which server you are talking about? can we check these errors by our own!

**Comment by jasonnutter** [comment]
> Which server you are talking about? can we check these errors by our own!

This is the server that loads in the hidden iframe, and unfortunately, you are not able to check these errors on your own.

**Comment by vinusorout** [comment]
Hello @jasonnutter after increasing the load frame time, now we are getting 431 Request header too large.

To resolve this we set storeAuthStateInCookie to false, but after that we are getting Timeout error please see logs in logs.txt file.

This issue is intermittent, as one user is able to run the application but one is not!

Please guide. 

[logs.txt](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/4597019/logs.txt)

**Comment by jasonnutter** [comment]
@vinusorout Does this error happen if you logout and log back in? And when the error happens, how many cookie values are MSAL cookies (i.e. are there dozens of MSAL cookies, or only 1)?

**Comment by vinusorout** [comment]
Hello @jasonnutter  there are many cookie values related to MSAL cookies.

Thankfully I have one of such example saved in my notepad:

   Cookie: AzureAppProxyAnalyticCookie_fbf140f0-89ed-4765-9e02-70431ce7c3f3_1.3=3|vTLfJB1eUV27VEsijJU7M/wTjc/AvHe+XY1Ld3Jb0fU7h+4TRblAO8f9jXjn918wOx9ZASVjjwP2vhlSq7jHdOvs3eC4VPgLLdaVTrHsRMxu9y2A+iiOt4HQobUAzvpicr3ESu24eSLj87b+2GaJXA==; msal.cd2e0505-3490-4e2c-8c1b-2fbd6ad7e048.idtoken=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IkN0VHVoTUptRDVNN0RMZHpEMnYyeDNRS1NSWSJ9.eyJhdWQiOiJjZDJlMDUwNS0zNDkwLTRlMmMtOGMxYi0yZmJkNmFkN2UwNDgiLCJpc3MiOiJodHRwczovL2xvZ2luLm1pY3Jvc29mdG9ubGluZS5jb20vZjVjYjMyZDgtZTlmMC00NGM1LTg5MmQtMjlhNWJkMzcxZDZlL3YyLjAiLCJpYXQiOjE1ODkxODQ1OTksIm5iZiI6MTU4OTE4NDU5OSwiZXhwIjoxNTg5MTg4NDk5LCJhaW8iOiJBVFFBeS84UEFBQUFEYXVaYWdwUG1RRVU2YklhT1c5a3VubzBCRTA5b29kRG02dmkvZ1lGMW1SaTR2aVZPdC9YY0EvYkwvTXY3TzkyIiwibmFtZSI6IlNvcm91dCwgVi4gKFZpbmF5KSIsIm5vbmNlIjoiZDEwZjAzZGYtNDQxNC00NTFhLTljODAtODFiODMyNGFmZGUyIiwib2lkIjoiOGRhNTU0YWEtMTBhNi00N2VjLTgzZmMtN2RlMjA5ZTA0ODc2IiwicHJlZmVycmVkX3VzZXJuYW1lIjoiZGV2dndzQHR0eC5jb20iLCJzdWIiOiJUX3VZOVREWm43MGxJUWFHS1pkbG1qeG5lWTV0NE80bDJXS0l1Sm82QTlNIiwidGlkIjoiZjVjYjMyZDgtZTlmMC00NGM1LTg5MmQtMjlhNWJkMzcxZDZlIiwidXRpIjoiV2NmYjVuSVhpVW1HY0xoZTdmOThBQSIsInZlciI6IjIuMCJ9.bwZOyoOcxtWTDPqD8rIj3OsJXiVOcZSV6wOjY6DmPVgkAsD4pwjbUKZOzIZos7hvbt2-reHyt7R1HARxOBTg24FhaW0gO2zNdqPFEtVNRId6reoHBosfX8hAtdzIBvTFn7txVwICM8NS1-_xMyVlCTn8MDdzc2Ury1brRl1X8W1efVncx1P_WyAFxZA-TcKCHlq1lN--LvveGoiEIAdbR4fQnF7Ee6nMga8l9gFXhOorevN8n7nBAqTrBwQhBk4l1ujIrBoAn_0PeZgrvHcj6lNdpdCrzZ4xH5eLsu-tXU3HYz2xnYaMMbrMR7klm7DVrPr-Ar3wqbG3Y4ei-PrzAQ; msal.idtoken=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IkN0VHVoTUptRDVNN0RMZHpEMnYyeDNRS1NSWSJ9.eyJhdWQiOiJjZDJlMDUwNS0zNDkwLTRlMmMtOGMxYi0yZmJkNmFkN2UwNDgiLCJpc3MiOiJodHRwczovL2xvZ2luLm1pY3Jvc29mdG9ubGluZS5jb20vZjVjYjMyZDgtZTlmMC00NGM1LTg5MmQtMjlhNWJkMzcxZDZlL3YyLjAiLCJpYXQiOjE1ODkxODQ1OTksIm5iZiI6MTU4OTE4NDU5OSwiZXhwIjoxNTg5MTg4NDk5LCJhaW8iOiJBVFFBeS84UEFBQUFEYXVaYWdwUG1RRVU2YklhT1c5a3VubzBCRTA5b29kRG02dmkvZ1lGMW1SaTR2aVZPdC9YY0EvYkwvTXY3TzkyIiwibmFtZSI6IlNvcm91dCwgVi4gKFZpbmF5KSIsIm5vbmNlIjoiZDEwZjAzZGYtNDQxNC00NTFhLTljODAtODFiODMyNGFmZGUyIiwib2lkIjoiOGRhNTU0YWEtMTBhNi00N2VjLTgzZmMtN2RlMjA5ZTA0ODc2IiwicHJlZmVycmVkX3VzZXJuYW1lIjoiZGV2dndzQHR0eC5jb20iLCJzdWIiOiJUX3VZOVREWm43MGxJUWFHS1pkbG1qeG5lWTV0NE80bDJXS0l1Sm82QTlNIiwidGlkIjoiZjVjYjMyZDgtZTlmMC00NGM1LTg5MmQtMjlhNWJkMzcxZDZlIiwidXRpIjoiV2NmYjVuSVhpVW1HY0xoZTdmOThBQSIsInZlciI6IjIuMCJ9.bwZOyoOcxtWTDPqD8rIj3OsJXiVOcZSV6wOjY6DmPVgkAsD4pwjbUKZOzIZos7hvbt2-reHyt7R1HARxOBTg24FhaW0gO2zNdqPFEtVNRId6reoHBosfX8hAtdzIBvTFn7txVwICM8NS1-_xMyVlCTn8MDdzc2Ury1brRl1X8W1efVncx1P_WyAFxZA-TcKCHlq1lN--LvveGoiEIAdbR4fQnF7Ee6nMga8l9gFXhOorevN8n7nBAqTrBwQhBk4l1ujIrBoAn_0PeZgrvHcj6lNdpdCrzZ4xH5eLsu-tXU3HYz2xnYaMMbrMR7klm7DVrPr-Ar3wqbG3Y4ei-PrzAQ; msal.cd2e0505-3490-4e2c-8c1b-2fbd6ad7e048.client.info=eyJ1aWQiOiI4ZGE1NTRhYS0xMGE2LTQ3ZWMtODNmYy03ZGUyMDllMDQ4NzYiLCJ1dGlkIjoiZjVjYjMyZDgtZTlmMC00NGM1LTg5MmQtMjlhNWJkMzcxZDZlIn0; msal.client.info=eyJ1aWQiOiI4ZGE1NTRhYS0xMGE2LTQ3ZWMtODNmYy03ZGUyMDllMDQ4NzYiLCJ1dGlkIjoiZjVjYjMyZDgtZTlmMC00NGM1LTg5MmQtMjlhNWJkMzcxZDZlIn0; msal.cd2e0505-3490-4e2c-8c1b-2fbd6ad7e048.authority|eyJpZCI6IjU4ZWUyZWIxLTFkZmItNGY1Zi05NDVlLTI2MDg4NTMyNWJlNyIsInRzIjoxNTg5MTg0ODY2LCJtZXRob2QiOiJzaWxlbnRJbnRlcmFjdGlvbiJ9=https://login.microsoftonline.com/f5cb32d8-e9f0-44c5-892d-29a5bd371d6e/; msal.authority|eyJpZCI6IjU4ZWUyZWIxLTFkZmItNGY1Zi05NDVlLTI2MDg4NTMyNWJlNyIsInRzIjoxNTg5MTg0ODY2LCJtZXRob2QiOiJzaWxlbnRJbnRlcmFjdGlvbiJ9=https://login.microsoftonline.com/f5cb32d8-e9f0-44c5-892d-29a5bd371d6e/; msal.cd2e0505-3490-4e2c-8c1b-2fbd6ad7e048.nonce.idtoken|eyJpZCI6IjU4ZWUyZWIxLTFkZmItNGY1Zi05NDVlLTI2MDg4NTMyNWJlNyIsInRzIjoxNTg5MTg0ODY2LCJtZXRob2QiOiJzaWxlbnRJbnRlcmFjdGlvbiJ9=665160c5-613e-4dd0-80c6-628f1a80b005; msal.nonce.idtoken|eyJpZCI6IjU4ZWUyZWIxLTFkZmItNGY1Zi05NDVlLTI2MDg4NTMyNWJlNyIsInRzIjoxNTg5MTg0ODY2LCJtZXRob2QiOiJzaWxlbnRJbnRlcmFjdGlvbiJ9=665160c5-613e-4dd0-80c6-628f1a80b005; msal.cd2e0505-3490-4e2c-8c1b-2fbd6ad7e048.authority|eyJpZCI6IjI2NTU5ODlmLWVlODUtNGE1NC1hNWYzLTM5MDVlMDIzODg3NyIsInRzIjoxNTg5MTg0OTA0LCJtZXRob2QiOiJzaWxlbnRJbnRlcmFjdGlvbiJ9=https://login.microsoftonline.com/f5cb32d8-e9f0-44c5-892d-29a5bd371d6e/; msal.authority|eyJpZCI6IjI2NTU5ODlmLWVlODUtNGE1NC1hNWYzLTM5MDVlMDIzODg3NyIsInRzIjoxNTg5MTg0OTA0LCJtZXRob2QiOiJzaWxlbnRJbnRlcmFjdGlvbiJ9=https://login.microsoftonline.com/f5cb32d8-e9f0-44c5-892d-29a5bd371d6e/; msal.cd2e0505-3490-4e2c-8c1b-2fbd6ad7e048.nonce.idtoken|eyJpZCI6IjI2NTU5ODlmLWVlODUtNGE1NC1hNWYzLTM5MDVlMDIzODg3NyIsInRzIjoxNTg5MTg0OTA0LCJtZXRob2QiOiJzaWxlbnRJbnRlcmFjdGlvbiJ9=402d1a49-ba49-406e-a42b-7dba22e41901; msal.nonce.idtoken|eyJpZCI6IjI2NTU5ODlmLWVlODUtNGE1NC1hNWYzLTM5MDVlMDIzODg3NyIsInRzIjoxNTg5MTg0OTA0LCJtZXRob2QiOiJzaWxlbnRJbnRlcmFjdGlvbiJ9=402d1a49-ba49-406e-a42b-7dba22e41901; msal.cd2e0505-3490-4e2c-8c1b-2fbd6ad7e048.login.request|eyJpZCI6IjIzODIxNmQxLWUzMzMtNGJlMC1hM2UyLTczNzZmMzUxNDk0MyIsInRzIjoxNTg5MTg0OTk2LCJtZXRob2QiOiJyZWRpcmVjdEludGVyYWN0aW9uIn0==https://crbt.ttx.com/fa/notauthorised; msal.login.request|eyJpZCI6IjIzODIxNmQxLWUzMzMtNGJlMC1hM2UyLTczNzZmMzUxNDk0MyIsInRzIjoxNTg5MTg0OTk2LCJtZXRob2QiOiJyZWRpcmVjdEludGVyYWN0aW9uIn0==https://crbt.ttx.com/fa/notauthorised; msal.cd2e0505-3490-4e2c-8c1b-2fbd6ad7e048.state.login|eyJpZCI6IjIzODIxNmQxLWUzMzMtNGJlMC1hM2UyLTczNzZmMzUxNDk0MyIsInRzIjoxNTg5MTg0OTk2LCJtZXRob2QiOiJyZWRpcmVjdEludGVyYWN0aW9uIn0==eyJpZCI6IjIzODIxNmQxLWUzMzMtNGJlMC1hM2UyLTczNzZmMzUxNDk0MyIsInRzIjoxNTg5MTg0OTk2LCJtZXRob2QiOiJyZWRpcmVjdEludGVyYWN0aW9uIn0=; msal.state.login|eyJpZCI6IjIzODIxNmQxLWUzMzMtNGJlMC1hM2UyLTczNzZmMzUxNDk0MyIsInRzIjoxNTg5MTg0OTk2LCJtZXRob2QiOiJyZWRpcmVjdEludGVyYWN0aW9uIn0==eyJpZCI6IjIzODIxNmQxLWUzMzMtNGJlMC1hM2UyLTczNzZmMzUxNDk0MyIsInRzIjoxNTg5MTg0OTk2LCJtZXRob2QiOiJyZWRpcmVjdEludGVyYWN0aW9uIn0=; msal.cd2e0505-3490-4e2c-8c1b-2fbd6ad7e048.authority|eyJpZCI6IjIzODIxNmQxLWUzMzMtNGJlMC1hM2UyLTczNzZmMzUxNDk0MyIsInRzIjoxNTg5MTg0OTk2LCJtZXRob2QiOiJyZWRpcmVjdEludGVyYWN0aW9uIn0==https://login.microsoftonline.com/f5cb32d8-e9f0-44c5-892d-29a5bd371d6e/; msal.authority|eyJpZCI6IjIzODIxNmQxLWUzMzMtNGJlMC1hM2UyLTczNzZmMzUxNDk0MyIsInRzIjoxNTg5MTg0OTk2LCJtZXRob2QiOiJyZWRpcmVjdEludGVyYWN0aW9uIn0==https://login.microsoftonline.com/f5cb32d8-e9f0-44c5-892d-29a5bd371d6e/; msal.cd2e0505-3490-4e2c-8c1b-2fbd6ad7e048.nonce.idtoken|eyJpZCI6IjIzODIxNmQxLWUzMzMtNGJlMC1hM2UyLTczNzZmMzUxNDk0MyIsInRzIjoxNTg5MTg0OTk2LCJtZXRob2QiOiJyZWRpcmVjdEludGVyYWN0aW9uIn0==d9f1cf72-d5cb-4738-a19c-a034739720fe; msal.nonce.idtoken|eyJpZCI6IjIzODIxNmQxLWUzMzMtNGJlMC1hM2UyLTczNzZmMzUxNDk0MyIsInRzIjoxNTg5MTg0OTk2LCJtZXRob2QiOiJyZWRpcmVjdEludGVyYWN0aW9uIn0==d9f1cf72-d5cb-4738-a19c-a034739720fe; msal.cd2e0505-3490-4e2c-8c1b-2fbd6ad7e048.login.request|eyJpZCI6IjczODEzOTAwLTdlMzMtNGZjZi05OTRhLWJjMTI5YWMwNDUzMCIsInRzIjoxNTg5MTg1MDAxLCJtZXRob2QiOiJyZWRpcmVjdEludGVyYWN0aW9uIn0==https://crbt.ttx.com/fa/#; msal.login.request|eyJpZCI6IjczODEzOTAwLTdlMzMtNGZjZi05OTRhLWJjMTI5YWMwNDUzMCIsInRzIjoxNTg5MTg1MDAxLCJtZXRob2QiOiJyZWRpcmVjdEludGVyYWN0aW9uIn0==https://crbt.ttx.com/fa/#; msal.cd2e0505-3490-4e2c-8c1b-2fbd6ad7e048.state.login|eyJpZCI6IjczODEzOTAwLTdlMzMtNGZjZi05OTRhLWJjMTI5YWMwNDUzMCIsInRzIjoxNTg5MTg1MDAxLCJtZXRob2QiOiJyZWRpcmVjdEludGVyYWN0aW9uIn0==eyJpZCI6IjczODEzOTAwLTdlMzMtNGZjZi05OTRhLWJjMTI5YWMwNDUzMCIsInRzIjoxNTg5MTg1MDAxLCJtZXRob2QiOiJyZWRpcmVjdEludGVyYWN0aW9uIn0=; msal.state.login|eyJpZCI6IjczODEzOTAwLTdlMzMtNGZjZi05OTRhLWJjMTI5YWMwNDUzMCIsInRzIjoxNTg5MTg1MDAxLCJtZXRob2QiOiJyZWRpcmVjdEludGVyYWN0aW9uIn0==eyJpZCI6IjczODEzOTAwLTdlMzMtNGZjZi05OTRhLWJjMTI5YWMwNDUzMCIsInRzIjoxNTg5MTg1MDAxLCJtZXRob2QiOiJyZWRpcmVjdEludGVyYWN0aW9uIn0=; msal.cd2e0505-3490-4e2c-8c1b-2fbd6ad7e048.authority|eyJpZCI6IjczODEzOTAwLTdlMzMtNGZjZi05OTRhLWJjMTI5YWMwNDUzMCIsInRzIjoxNTg5MTg1MDAxLCJtZXRob2QiOiJyZWRpcmVjdEludGVyYWN0aW9uIn0==https://login.microsoftonline.com/f5cb32d8-e9f0-44c5-892d-29a5bd371d6e/; msal.authority|eyJpZCI6IjczODEzOTAwLTdlMzMtNGZjZi05OTRhLWJjMTI5YWMwNDUzMCIsInRzIjoxNTg5MTg1MDAxLCJtZXRob2QiOiJyZWRpcmVjdEludGVyYWN0aW9uIn0==https://login.microsoftonline.com/f5cb32d8-e9f0-44c5-892d-29a5bd371d6e/; msal.cd2e0505-3490-4e2c-8c1b-2fbd6ad7e048.nonce.idtoken|eyJpZCI6IjczODEzOTAwLTdlMzMtNGZjZi05OTRhLWJjMTI5YWMwNDUzMCIsInRzIjoxNTg5MTg1MDAxLCJtZXRob2QiOiJyZWRpcmVjdEludGVyYWN0aW9uIn0==5ebb4dae-15a6-4848-87b3-58f30272a5f5; msal.nonce.idtoken|eyJpZCI6IjczODEzOTAwLTdlMzMtNGZjZi05OTRhLWJjMTI5YWMwNDUzMCIsInRzIjoxNTg5MTg1MDAxLCJtZXRob2QiOiJyZWRpcmVjdEludGVyYWN0aW9uIn0==5ebb4dae-15a6-4848-87b3-58f30272a5f5; rxVisitor=15891846449077SUHVSFFGSEBB6FL29S19QSPCHMJK6GI; dtPC=1$384705344_772h6p1$384906051_404h1p1$384998900_438h2vCEAIAINLFMSJMKMMXLANPGEKJTFCAUDV; rxvt=1589186801009|1589184644910; dtSa=false%7Cxhr%7C2%7Cg2.0.0%7Cg2.0.0%7C1589185000797%7C384998900_438%7Chttps%3A%2F%2Fcrbt.ttx.com%2Ffa%2F%7CCRB%20FA%7C1589184998900%7C%7C; dtLatC=662; dtCookie=v_4_srv_1_sn_318110AE18C95CA4FB8A9203AB478E2E_perc_100000_ol_0_mul_1_app-3Afb4ff0c9d3e50dca_1

**Comment by vinusorout** [comment]
@jasonnutter  I also faced an issue where URL after authentication is too long and due to which I got 400 (request header too large or uri too large error) error from nginx server.

Does msal.js creates longer redirect uri than adal.js?

Follwoing is the url it created:
https://abc.abc.com/fa/#id_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IkN0VHVoTUptRDVNN0RMZHpEMnYyeDNRS1NSWSJ9.eyJhdWQiOiJjZDJlMDUwNS0zNDkwLTRlMmMtOGMxYi0yZmJkNmFkN2UwNDgiLCJpc3MiOiJodHRwczovL2xvZ2luLm1pY3Jvc29mdG9ubGluZS5jb20vZjVjYjMyZDgtZTlmMC00NGM1LTg5MmQtMjlhNWJkMzcxZDZlL3YyLjAiLCJpYXQiOjE1ODkyMDI1ODksIm5iZiI6MTU4OTIwMjU4OSwiZXhwIjoxNTg5MjA2NDg5LCJhaW8iOiJBVVFBdS84UEFBQUFBNHY4TFN6OGl3UjJuSjdBT3kzRnRwZ3RGNDkrR3dlRE54dTdibVo1d0VaaVY4bmlpb0JydC9LTWdyWlZqMVU4VXZEdjhCWGhTUnVRQXgxaXdjdkMrdz09IiwibmFtZSI6IkdhaGxhd2F0LCBWLiAgKFZpa2FzKSIsIm5vbmNlIjoiZDYxYWExYmYtN2E4Zi00MmU1LWE0ODQtNDQ1YmVlNDM2YWQ2Iiwib2lkIjoiNDA3ZWQ3MzctMTlmOC00NWZkLWIwZmUtNDI0NGM5NTI4Zjc0IiwicHJlZmVycmVkX3VzZXJuYW1lIjoiZGV2djFnQHR0eC5jb20iLCJzdWIiOiJrTjNSTGx3RmNOMlFFWk8xVHNyRFhTZWZ4S0dDamlyMEpTdGNXWWFrN0hnIiwidGlkIjoiZjVjYjMyZDgtZTlmMC00NGM1LTg5MmQtMjlhNWJkMzcxZDZlIiwidXRpIjoiU0xaOGtHX3NBMGlDbkczZjA4dDhBQSIsInZlciI6IjIuMCJ9.DkXvHwNwoHpV0JTjS8NmLxZ7R_QA3gcj5-L62rCEk5_RsQJ4RLB4yOtNb8rkIcTpQDU19s4aOrD8gd_5YIbO-iSuksE9ODnA3Rnr8TNo851q5adLFyVW3CLcFWu9liVqd0_ImM7MIUqVXSPEcGtWb-aIQ6xnQp-XlnfeCLvN_GD5o9i4ibPmvJoohC0v1rnpz8W7h-9QPedrtGCAkZB4d92q1iTuZONHtAqz06eZ_z18CeFKhZNaT1lU8hn24QaSEBtIaLdWH3NM1zRujUxg87LIxd2oKMDK5ypJoQRPKy6FWNUO_aUq9uFvbOP0YKG16wckbAPv7LFkNKjYxyaURw&client_info=eyJ1aWQiOiI0MDdlZDczNy0xOWY4LTQ1ZmQtYjBmZS00MjQ0Yzk1MjhmNzQiLCJ1dGlkIjoiZjVjYjMyZDgtZTlmMC00NGM1LTg5MmQtMjlhNWJkMzcxZDZlIn0&state=eyJpZCI6ImQzODk1MDIwLWFkZTEtNGU4OC05N2IxLTlhOTViYzNiYTI4MiIsInRzIjoxNTg5MjAyODQwLCJtZXRob2QiOiJyZWRpcmVjdEludGVyYWN0aW9uIn0%3d&session_state=56b9d9ac-097f-4975-9354-7f1c56f6ec50

**Comment by jasonnutter** [comment]
@vinusorout Yes, it does. I would suggest increasing those limits to see if it mitigates those errors.

**Comment by vinusorout** [comment]
Thanks @jasonnutter 
Will increase the same, can you suggest a max number here for URI!

Also what should we do for cookie issue?

**Comment by jmckennon** [comment]
The original issue is fixed here, the cookie issue will be fixed by #1188 which is in progress. Please open a new issue if you see further issues. Thanks!
