### ISSUE TITLE
Apparent race condition after fetching token via redirect

### ISSUE THREAD

**Issue by Basaingeal** [AzureAD/microsoft-authentication-library-for-js#1616]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.0.0-beta.1`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework
Vue v2

## Description
I have an SPA client registed in Azure AD. I also have a custom API that it calls registered in Azure AD. Before every call to my API, I call a function that calls `acquireTokenSilent({ scopes: apiScopes })` and falls back to `acquireTokenRedirect()`.

I'm also hitting this endpoint on page load, so I'm acquiring tokens on page load.

I would expect the flow to work like this.
1. Load page. User is unauthenticated. Log them in.
2. Acquire token. Since the API is a custom registered API, the login process didn't return tokens for it. `acquireTokenSilent()` fails, and `acquireTokenRedirect()` triggers
3. On redirect back to my app, access token for my API has been set, and the next call to `acquireTokenSilent()` succeeds.

Instead, sometimes, the final call to `acquireTokenSilent()` will sometimes still throw a "no_tokens" error. I look in application storage, and I don't see tokens stored for my API. This error looks no different from the error I would expect to see when I need to do the redirect, so my flow doesn't know what to do besides trying `acquireTokenRedirect()` again. This causes a redirect loop that continues 2 - 6 times before it finally works.

Putting a ~2 second delay before the `acquireTokenSilent()` call avoids this issue, so it feels like there's something I should waiting for before calling, but I don't know what that would be.

## Regression
Not to my knowledge

## Configuration

```js
{
    auth: {
      clientId: `${clientId}`,
      authority:
        `https://login.microsoftonline.com/${tenantId}`,
      redirectUri: `${window.location.origin}/login`,
    },
    cache: {
      cacheLocation: "localStorage".
    },
    system: {
      loggerOptions: {
        loggerCallback: (level, message, containsPii) => {
          if (containsPii) {
            return;
          }
          switch (level) {
            case 0:
              window.console.error(message);
              return;
            case 1:
              window.console.info(message);
              return;
            case 2:
              window.console.debug(message);
              return;
            case 3:
              window.console.warn(message);
              return;
          }
        },
        piiLoggingEnabled: false,
      },
      windowHashTimeout: 60000,
    },
  };
```

## Reproduction steps
1. 
2. 
3. 

## Expected behavior
That after `acquireTokenRedirect()` has been completed, that the tokens would be stored in browser storage and immediately accessible for a `acquireTokenSilent()` call
## Browsers
Not sure if browser specific, but seeing in Edge 81

**Comment by tnorling** [comment]
@Basaingeal Are you waiting for `handleRedirectPromise` to resolve before calling `acquireTokenSilent`? Given that setting a delay seems to fix your problem I suspect the response from the redirect request is not finished processing before you call `acquireTokenSilent`. You should also be able to retrieve the token from the redirect response, an immediate silent call should not be needed in order to retrieve the token.

This [sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/VanillaJSTestApp2.0/app/onPageLoad) may be of interest to you.

**Comment by Basaingeal** [comment]
Interesting. That works. I hadn't thought to use that as a promise to await outside of initial configuration. That sample that you linked is what I was going off of, although I had to tweak some things to fit into an authenticated router setup.

So basically doing the call how the sample said but with that extra initial await works:
```js
async function getTokenRedirect(request) {
    await myMSALObj.handleRedirectPromise();
    return await myMSALObj.acquireTokenSilent(request).catch(async (error) => {
        console.log("silent token acquisition fails.");
        if (error instanceof AuthenticationRequiredError) {
            if (AuthenticationRequiredError.isInteractionRequiredError(error.errorCode, error.errorDesc)) {
                // fallback to interaction when silent call fails
                console.log("acquiring token using redirect");
                myMSALObj.acquireTokenRedirect(request);
            }
        } else {
            console.error(error);
        }
    });
}
```

I'm not sure if this could be clearer somehow. Most of the examples are still based on the old `handleRedirectCallback` flow, and the examples given of the new flow basically just recreate `handleRedirectCallback` with `myMSALObj.handleRedirectPromise().then((tokenResponse) => { ... })`

I think in the sample, the getToken methods are all only called after we're past the resolution of the `handleRedirectPromise` promise. But because it's not obvious just based off of the sample, it seems easy to fall into the trap that I did. When you're using a framework and a lot of things are wired to happen on load, putting everything on hold to only complete when a promise is resolved can be tricky. 

Having that promise always exposed via the `handleRedirectPromise` solves this, but it's not clear through any samples I would say.

**Comment by tnorling** [comment]
@Basaingeal I agree. Our redirect flows are not as well documented as they could be and we definitely have plans to improve that. The redirect promise is a new concept we introduced in the newest beta of msal-browser in an effort to align redirect flows with popup flows and reduce confusion. Your feedback is much appreciated and we'll make sure to call this out more clearly in the docs and samples!
