### ISSUE TITLE
openid configuration sends on each request

### ISSUE THREAD

**Issue by djleonskennedy** [AzureAD/microsoft-authentication-library-for-js#1619]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x ] `msal@1.3.0`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x ] `@azure/msal-angular@1.0.0`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
I've set app with msal angular and i got request for open-configuration on each request

https://login.microsoftonline.com/<CLIENT_ID>/v2.0/.well-known/openid-configuration

`function MSALAngularConfigFactory(config: ConfigService): MsalAngularConfiguration {
  const props = config.appProps;
  const msal = config.appProps.msal;
  const applicationIdUri = props.wellKnown.tenant.applicationIdUri;
  const envDependentScope = `${applicationIdUri}/AdminAccess`;

  const protectedResourceMap = msal.protectedResourceMap.map((row): [string, string[]] => {
    const [resource, scopes] = row;
    return [resource, [...scopes, envDependentScope]];
  });
  return {
    popUp: !isIE,
    consentScopes: msal.scopes.concat(envDependentScope),
    unprotectedResources: ['env-config'],
    protectedResourceMap,
    extraQueryParameters: {}
  };
}`

**Comment by AndriiDidkivsky** [comment]
Facing same issue with MSAL great than v1.1.3

**Comment by djleonskennedy** [comment]
Duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1240

If someone will face issue, remove unnecessary  scopes from protected resource map 

Here :  https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dacad07ff71f35d658cfa509142bdf5b8c07d28b/lib/msal-angular/src/msal-angular.configuration.ts#L14

Regards
