### ISSUE TITLE
What is the correct string to use to identify a specific user in a local database?

### ISSUE THREAD

**Issue by DarkLite1** [AzureAD/microsoft-authentication-library-for-js#1620]
## Library
- [x ] `msal@1.3.0` from `npm install msal`

## Documentation location
- [x] MSAL.js Github Wiki
- [x] README file
- [x] Documentation does not exist

## Description
It's hard to find which identifier to use when a user authenticated to Azure AD. The returned object from `msal.getAccount()` contains multiple fields that can be used but it's unclear which one. 

A similar question has been asked [here](https://stackoverflow.com/questions/58645442/msal-useridentifier-versus-idtoken-oid) and shows 2 possible options:

- [accountIdentifier](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/src/Account.ts): combination of idToken.uid and idToken.utid
- [idTokenClaims.oid](https://stackoverflow.com/questions/58645442/msal-useridentifier-versus-idtoken-oid)

In the [README ](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/README.md) it syas:

> When the login methods are called and the authentication of the user is completed by the Azure AD service, an id token is returned which is used to identify the user with some basic information.

But the [class account](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/src/Account.ts) says the `idToken` will be deprecated soon:
```javascript
export class Account {
    accountIdentifier: string;
    homeAccountIdentifier: string;
    userName: string;
    name: string;
    idToken: StringDict; // will be deprecated soon
    idTokenClaims: StringDict;
    sid: string;
    environment: string;
```

My single goal is to be store settings for the app in the database and find them back the next time the user signs-in. Thank you for clarifying which ID to use for this purpose.

**Comment by derisen** [comment]
I believe `oid` is what you need. From the [documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens#payload-claims):

> The immutable identifier for an object in the Microsoft identity system, in this case, a user account. This ID uniquely identifies the user across applications - two different applications signing in the same user will receive the same value in the oid claim. The Microsoft Graph will return this ID as the id property for a given user account. Because the oid allows multiple apps to correlate users, the profile scope is required to receive this claim. Note that if a single user exists in multiple tenants, the user will contain a different object ID in each tenant - they're considered different accounts, even though the user logs into each account with the same credentials. The oid claim is a GUID and cannot be reused.

**Comment by DarkLite1** [comment]
Thanks for the feedback @derisen . So the correct one to use is `idTokenClaims oid`

It might be beneficial to add this to the examples as a comment. So it's clear for developers which one they need to use. Given that there's no need to store a token in the app, because `acquireTokenSilent` calls will do that for us, the only remaining question can be on how to identify the user with a unique string. So therefore a small comment in the examples might be a good idea.

**Comment by derisen** [comment]
@DarkLite1 sounds good. I'm actually working on FAQ and will sure to add this.
