### ISSUE TITLE
Caching problems with acquireTokenSilent()

### ISSUE THREAD

**Issue by heikkilamarko** [AzureAD/microsoft-authentication-library-for-js#1623]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.0.0-beta.1`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

Vanilla JavaScript

## Description

It seem that after upgrading from `msal-browser@2.0.0-beta.0` to `msal-browser@2.0.0-beta.1`, caching is not working properly anymore.

Every time I call `await msalApp.acquireTokenSilent(request)`, both the metadata and token requests are made against Azure AD endpoints. This was NOT happening with `beta.0`.

## Security

No

## Regression

This was NOT happening with `msal-browser@2.0.0-beta.0`.

## Configuration

```js
{
  msal: {
    auth: {
      clientId: "<client_id>",
      authority: "https://login.microsoftonline.com/<tenant_id>/",
      redirectUri: location.origin,
      postLogoutRedirectUri: location.origin,
    },
    cache: {
      cacheLocation: "localStorage",
      storeAuthStateInCookie: false,
    }
  }
}
```

## Reproduction steps

See the Description section.

## Expected behavior

Calling `await msalApp.acquireTokenSilent(request)` shouldn't go to Azure AD endpoints every time.

## Browsers

Can be reproduced, at least, in Chrome and Firefox.

**Comment by pkanher617** [comment]
@heikkilamarko Thank you for posting this issue. I was able to reproduce it, I will try to push a fix and a new release today.
