### ISSUE TITLE
B2C - Localization strings

### ISSUE THREAD

**Issue by dusanjovanov** [AzureAD/microsoft-authentication-library-for-js#1625]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
We have B2C customization with unified.html. This what the sign in page in Lithuanian looks like: 

![image](https://user-images.githubusercontent.com/20474783/81542982-c42d9600-9375-11ea-81b1-72d01a44aaa1.png)

What are the ids of LocalizationStrings for email and password ? 

This is a part of my TrustFrameworkExtensions.xml :

![image](https://user-images.githubusercontent.com/20474783/81545182-cba26e80-9378-11ea-98d3-6f92147e64f3.png)

**Comment by tnorling** [comment]
@dusanjovanov Can you check the documentation [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/user-flow-language-customization) on language customization for B2C and let us know if this addresses your use case?

**Comment by tnorling** [comment]
Let us know if the docs linked above did not address your use case and you still need assistance. Thanks!

**Comment by dusanjovanov** [comment]
The link that you gave me is for user flows, we're using custom policies. The problem is specifically in this part `<LocalizedResources Id="api.signuporsignin.lt">`. Email and password labels are not translated correctly. But, I can't find the LocalizedString attributes (ElementType, ElementId, StringId) for those labels.

**Comment by tnorling** [comment]
This would be a question for the B2C service as this is not something MSAL owns. Please file a support ticket with the B2C team by following the instructions here: https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options
