### ISSUE TITLE
Example in README.md points to not-existing file in cdn

### ISSUE THREAD

**Issue by RobertoPrevato** [AzureAD/microsoft-authentication-library-for-js#163]
Hello,
The file:
```
https://secure.aadcdn.microsoftonline-p.com/lib/1.0.0/js/msal.min.js
```

Referenced in the documentation of README.md does not exist.

**Comment by dan-harris** [comment]
I think we have to wait for v1.0.0 to be properly released (https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/162) as the current link in the master branch readme is: https://secure.aadcdn.microsoftonline-p.com/lib/0.1.2/js/msal.min.js

I agree though, would really like to see either v1.0.0 or v0.1.3 released to npm/cdn as soon as possible.

**Comment by rohitnarula7176** [comment]
@dan-harris @RobertoPrevato Version 0.1.3 is now released on npm and cdn.

**Comment by RobertoPrevato** [comment]
Thanks for answering so fast! 👍
