### ISSUE TITLE
Wrong location of index.d.ts in @azure/msal-browser v2.0.0-beta.1

### ISSUE THREAD

**Issue by chunliu** [AzureAD/microsoft-authentication-library-for-js#1635]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.
@azure/msal-browser v2.0.0-beta.1

## Framework
React v16

## Description
The location of `index.d.ts` should be in `node_modules/@azure/msal-browser/dist/`. However, its actual location in the package is `node_modules/@azure/msal-browser/dist/src`. It leads to the following compilation error when using TypeScript. 

```
error TS7016: Could not find a declaration file for module '@azure/msal-browser'. '<project path>/node_modules/@azure/msal-browser/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/azure__msal-browser` if it exists or add a new declaration (.d.ts) file containing `declare module '@azure/msal-browser';`

2 import * as msal from "@azure/msal-browser";
                        ~~~~~~~~~~~~~~~~~~~~~
``` 

## Security
Is this issue security related?
No

## Regression
Did this behavior work before?
Yes

## Reproduction steps
1. `npm install @azure/msal-browser`
2. Compile the sample with TypeScript.
3. 

## Expected behavior
Put index.d.ts in the correct location. 

## Browsers
Is this issue browser-specific? If so, please detail which browsers are impacted (e.g. IE 11, Safari).
No.

**Comment by pkanher617** [comment]
@chunliu Could you try upgrading to beta.2 and see if you are still seeing this issue?

**Comment by pkanher617** [comment]
Confirmed to work for TS projects.

**Comment by chunliu** [comment]
there is no issue with beta.2. thx.
