### ISSUE TITLE
manually trigger token renewal ? 

### ISSUE THREAD

**Issue by hdrodel** [AzureAD/microsoft-authentication-library-for-js#1636]
## Library
-[]AdalJS v1.0.18

## Description
Is there a way to manually trigger token renewal?

Im currently trying to tackle the pagerefresh problem when the token is renewed. is it possible to trigger a renewal without having to wait until the token expires?

**Comment by pkanher617** [comment]
@hdrodel Could you please clarify what package you are using? Our adal library is here: https://www.npmjs.com/package/adal-angular. It only goes up to v 1.0.17.

Please open issues for ADAL here: https://github.com/AzureAD/azure-activedirectory-library-for-js/issues
