### ISSUE TITLE
Provide nonce for request

### ISSUE THREAD

**Issue by IainAdamsLabs** [AzureAD/microsoft-authentication-library-for-js#1638]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [X] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
I am working with a 3rd party authentication system that allows for federated identities. The way it works is that you obtain an ID Token from a provider and then send it to them, they check that the token is from a provider configured for the account and if so, they re-issue you a token for their system.

The issue that I am facing is that they assume that the nonce used when requesting the original token was a SHA-256 encoded version of a raw string. They then ask you to send the raw string to them which they can obviously then use to check that the nonce in the token is correct.

Because MSAL has it's own algorithm for creating the nonce it means that I can't use the 3rd party system. Instead, it would be better if you could provide a nonce in the AuthenticationParameters.

```
msalClient.acquireTokenSilent({
    scopes: [ ... ],
     loginHint: "",
     nonce: <nonce to use in the authorize request>
})
```

Of course, it could be defaulted to using the current implementation if a nonce is not provided.

Also in msal-browser - when using PKCE, I don't believe nonce is still required as the code_verifier can be used for the same function.

Thanks
Iain

**Comment by pkanher617** [comment]
@IainAdamsLabs This seems like a reasonable request, we will take some time to review it.

**Comment by tnorling** [comment]
Closing as this is possible in `msal-browser` and new features are no longer going into `msal@1.x`
