### ISSUE TITLE
TypeScript Error: "Declaration or statement expected." in msal-browser/dist/src/index.d.ts

### ISSUE THREAD

**Issue by ninio** [AzureAD/microsoft-authentication-library-for-js#1640]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.0.0-beta.2
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework
react@16.12.0 with typescript@3.7.5

## Description
When including the @azure/msal-browser in the project, the following error appears:
``` ts
TypeScript error in D:/project_name/node_modules/@azure/msal-browser/dist/src/index.d.ts(5,1):
Declaration or statement expected.  TS1128

    3 | export { BrowserAuthError, BrowserAuthErrorMessage } from "./error/BrowserAuthError";
    4 | export { BrowserConfigurationAuthError, BrowserConfigurationAuthErrorMessage } from "./error/BrowserConfigurationAuthError";
  > 5 | export type { AuthCallback } from "./types/AuthCallback";
      | ^
    6 | export { AuthenticationParameters, TokenExchangeParameters, AuthResponse, TokenResponse, InteractionRequiredAuthError, AuthError, AuthErrorMessage, INetworkModule, Logger, LogLevel } from "@azure/msal-common";
```

## Security
No.

## Regression
Don't know.

## Configuration
Please provide your MSAL configuration options.

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Expected behavior

When `export type { AuthCallback } from './types/AuthCallback'` is changed to `export { AuthCallback } from './types/AuthCallback'` it is compiling successfully. 

Could be related to my tsconfig
``` json
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react"
  },
  "include": [
    "src"
  ]
}

```

## Browsers
Is this issue browser-specific? If so, please detail which browsers are impacted (e.g. IE 11, Safari).''
No.

**Comment by pkanher617** [comment]
@ninio Could you try upgrading to Typescript 3.8? This version introduced [type-only imports and exports](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-exports) which is why you may be seeing the above error.

**Comment by ninio** [comment]
The update fixes this.

Thanks!

**Comment by jrmcdona** [comment]
Solved me issue,  you may want to add this to the documentation on getting started. I am upgrading a project that was using older version of TypeScript and was hitting this error.
