### ISSUE TITLE
Feature Request: API for retrieving the redirect url for MSAL.AcquireTokenRedirect

### ISSUE THREAD

**Issue by lahuey** [AzureAD/microsoft-authentication-library-for-js#1644]
Scenario:
1. Silent Authentication fails with Multi Factor Authentication Required
2. SPA prompts the end user to provide credentials (rather than redirecting immediately)

This scenario is difficult to support, as we cannot regenerate the original token request (via AcquireTokenRedirect) when the user clicks the hyperlink. If we had an API to build the redirect url from a request, we could pass it to our UX element.

**Comment by jasonnutter** [comment]
See #1691 for proposed solution.
