### ISSUE TITLE
How to renew the tokens when using multiple scopes?

### ISSUE THREAD

**Issue by DarkLite1** [AzureAD/microsoft-authentication-library-for-js#1649]
##  Library
- [x] `msal@1.3.o` from `npm install msal`

## Description

To only ask the user for consent once we included all scopes in the `loginRedirect` and `loginPopup` methods. We assume this ok to do.

While updating the code we also try to convert it to TypeScript but get the error below. The strange thing is that this is the same code as in [the exmaple](https://github.com/Azure-Samples/active-directory-javascript-graphapi-v2/blob/quickstart/JavaScriptSPA/authRedirect.js) with the same signature `acquireTokenSilent(request, endpoint)`. It seems like `endpoint` is not accepted here?

Given the fact that we updated the scope to include all scopes, would it be an issue for msal to renew the token silently? The message below speaks about only passing the clientId as scope, this makes me concerned that [we're](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/752) doing it wrong.

> (method) UserAgentApplication.acquireTokenSilent(userRequest: AuthenticationParameters): Promise<AuthResponse>
> Use this function to obtain a token before every call to the API / resource provider
> MSAL return's a cached token when available Or it send's a request to the STS to obtain a new token using a hidden iframe.
> @param
> @link — AuthenticationParameters}
> To renew idToken, please pass **clientId as the only scope** in the Authentication Parameters
> @returns — - a promise that is fulfilled when this function has completed, or rejected if an error was raised. Returns the {@link AuthResponse} object
> 

![image](https://user-images.githubusercontent.com/10828570/81803499-10184080-9518-11ea-9481-504223add592.png)

**authRedirect.ts**
```typescript
import { msal } from 'src/services/auth/authIndex'

export const consentScopes: {scopes: string[]} = {
  scopes: [
    config.resources.gatewayApi.resourceScope,
    ...config.scopes.loginRequest
  ]
}
export const getAccount = () => msal.getAccount()
export const loginRedirect = () => { msal.loginRedirect(consentScopes) }
export const logout = () => { msal.logout() }
export const getTokenRedirect = (request, endpoint) => {
  return msal
    .acquireTokenSilent(request, endpoint)
    .catch(() => msal.acquireTokenRedirect(request)) // page reload
}
```

**app-config.json:**

```json
{
  "scopes": {
    "loginRequest": ["openid", "profile", "user.read"]
  },
  "resources": {
    "gatewayApi": {
      "resourceUri": "https://localhost:44351/api",
      "resourceScope": "api://0e01a2d8-64bb-4c3b-a75d-939aa5d8d361/access_as_user"
    }
  }
}
```
My [GitHub](https://github.com/DarkLite1/hip) for more details

**Comment by pkanher617** [comment]
> To only ask the user for consent once we included all scopes in the loginRedirect and loginPopup methods. We assume this ok to do.

This assumption is correct - by doing this, you will be able to consent to multiple scopes from multiple resources on login.

> While updating the code we also try to convert it to TypeScript but get the error below. The strange thing is that this is the same code as in the exmaple with the same signature acquireTokenSilent(request, endpoint). It seems like endpoint is not accepted here?

Correct - endpoint is not an accepted parameter for `acquireTokenSilent`. The accepted parameters are available in the AuthenticationParameters.ts class [here](https://azuread.github.io/microsoft-authentication-library-for-js/ref/msal-core/modules/_authenticationparameters_.html).

> Given the fact that we updated the scope to include all scopes, would it be an issue for msal to renew the token silently? The message below speaks about only passing the clientId as scope, this makes me concerned that we're doing it wrong.

Unfortunately no - while on interactive calls, sending multiple scopes is ok, each token is scoped to a single resource, and we differentiate these tokens based on the scopes (since scopes are usually of the format `'resource:scope'` with the exception of MS Graph scopes). We cache them separately, and they must be sent separately to the appropriate resource. So when making an acquireTokenSilent call, you can only send the scopes of the access token that you want to use.

So for your scenario, in your login call you can send the following scopes:
`openid profile user.read api://0e01a2d8-64bb-4c3b-a75d-939aa5d8d361/access_as_user`

But when you are using a graph scope, you can only send the graph and openid scopes:
`openid profile user.read`

And when you want to use the gatewayApi token, send the following scope:
`api://0e01a2d8-64bb-4c3b-a75d-939aa5d8d361/access_as_user`

Hope this clears things up a bit.

**Comment by DarkLite1** [comment]
Thank you @pkanher617 , this really cleared things up a bit for me. 

> Correct - endpoint is not an accepted parameter for acquireTokenSilent. 

In this case, could it be that line 53 in the [example code](https://github.com/Azure-Samples/active-directory-javascript-graphapi-v2/blob/quickstart/JavaScriptSPA/authRedirect.js) should be update from ` return myMSALObj.acquireTokenSilent(request, endpoint)` to ` return myMSALObj.acquireTokenSilent(request)`?

I think I'll stick to the plan to send all scope consent requests to the user upon login, all at once. As this seems to be ok.. Suppose that later on the token get expired and `acquireTokenSilent` retrieves a new fresh token when calling `MS Graph` for example with its proper scopes. Is that token then also valid for calls to my own external API? Or will `cquireTokenSilent` also do a refresh when calling the API just after the token is refreshed for the `MS Graph` call?

Just to be 100% certain, these will be the correct Uri's with the correct scopes right?
```json
  "resources": {
    "gatewayApi": {
      "resourceUri": "https://localhost:44351/api",
      "resourceScope": "api://0e01a2d8-64bb-4c3b-a75d-939aa5d8d361/access_as_user"
    },
    "msGraphProfile": {
      "resourceUri": "https://graph.microsoft.com/v1.0/me",
      "resourceScope": ["openid", "profile", "user.read"]
    },
    "msGraphMail": {
      "resourceUri": "https://graph.microsoft.com/v1.0/me/messages",
      "resourceScope": ["Mail.Read"]
    }
  }
```

**Comment by pkanher617** [comment]
> In this case, could it be that line 53 in the example code should be update from return myMSALObj.acquireTokenSilent(request, endpoint) to return myMSALObj.acquireTokenSilent(request)?

Thanks for catching this, I have opened a PR for this in that repo: https://github.com/Azure-Samples/active-directory-javascript-graphapi-v2/pull/37.

Access tokens are tied to a specific resource, so you can't get a token that is valid for both `MS Graph` and your external API. What you should do is before making a call to an endpoint, call `acquireTokenSilent` (calling it ATS from now on) with the scopes you need for that endpoint. So if you are calling your external API, call ATS with your external resource scope. If you are calling graph, user the user.read or mail.read scopes. ATS will:
1. retrieve the corresponding token from the cache
2. check if it is expired
3. renew the token if your session is still active, or throw an error to tell you to call an interactive API if the session is not active
4. Return the valid token in the response, or throw an error if there wasn't enough information or a login is required.

This way ATS will always get you a valid access token.

As far as I can tell, your URIs look correct.

**Comment by DarkLite1** [comment]
Awesome! That cleared it up for me. Closing this one. Thanks for the amazing feedback, very much appreciated :)
