### ISSUE TITLE
404 error while installing @msal-angular in angular 9 app

### ISSUE THREAD

**Issue by MrinmoyM** [AzureAD/microsoft-authentication-library-for-js#1651]
npm install msal @angular/msal-angular --save
giving error - 
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@angular%2fmsal-angular - Not found
npm ERR! 404
npm ERR! 404  '@angular/msal-angular@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:

**Comment by jasonnutter** [comment]
@MrinmoyM The correct name is `@azure/msal-angular`, instead of `@angular/msal-angular`. Can you please try that?

**Comment by MrinmoyM** [comment]
My bad! Thanks.
