### ISSUE TITLE
Create Documentation for Scopes and Multiple Resource Scenarios

### ISSUE THREAD

**Issue by pkanher617** [AzureAD/microsoft-authentication-library-for-js#1653]
Please follow the issue template below. 

## Library
- All

## Type
- [ ] Bug
- [ ] Feature
- [ ] Enhancement
- [ ] Tooling
- [x] Documentation
- [ ] Samples
- [ ] Other (please describe)

## Source
- [x] Internal (MSAL.js team)
- [ ] Customer request

## Description
Add docs for scopes and multiple resources, this isn't well documented enough and needs to be more clear in terms of usage for our library. Follow up from #1361.

## Priority
Medium

**Comment by tnorling** [comment]
Also see sample for [multiple resources](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/VanillaJSTestApp2.0/app/multiple_resources)

**Comment by tnorling** [comment]
Merged in #2002
