### ISSUE TITLE
loginPopup is opening a new windows on mobile

### ISSUE THREAD

**Issue by zlaja1983** [AzureAD/microsoft-authentication-library-for-js#1654]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.3.1`
- [ ] `@azure/msal-angular@1.0.0`

## Description
I am seeing an odd behavior on mobile when using msalService.loginPopup(data)
        const data: AuthenticationParameters = {
            authority: `${B2CPolicyFlows.B2C_BASE_URL}/${B2CPolicyFlows.B2C_SIGNIN_FLOW}`,
            state: redirectUrl ? redirectUrl : '/home',
            scopes: this.scopes
        };

the popup works fine while on desktop but as soon as i use mobile device, iphone, and try to login, the loginPopup ends up opening a new browser window which is not the behavior I want

**Comment by jasonnutter** [comment]
@zlaja1983 Mobile browsers open popups as new windows, unfortunately (and I don't believe there is anything we can do to change that).
