### ISSUE TITLE
Better workaround for silent token refresh failure in Safari

### ISSUE THREAD

**Issue by niwsa** [AzureAD/microsoft-authentication-library-for-js#1656]
## Library
- [x] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Current [work around](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Known-issue-on-Safari#work-around
) for silent token renewal failure in safari requires user intervention i.e to completely disable the third party cookie blocking in Safari Preferences.However it appears a better alternative exists in the form of Storage Access API.

From  [MDN doc](https://developer.mozilla.org/en-US/docs/Web/API/Storage_Access_API)
>In addition, sandboxed <iframe>s cannot be granted storage access by default for security reasons. The API therefore also adds the allow-storage-access-by-user-activation sandbox token. The embedding website needs to add this to allow storage access requests to be successful, along with allow-scripts and allow-same-origin to allow it to call the API, and execute in an origin that can have cookies

From [webkit blog](https://webkit.org/blog/10218/full-third-party-cookie-blocking-and-more/)
> To keep supporting cross-site integration, we shipped the Storage Access API two years ago to provide the means for authenticated embeds to get cookie access with mandatory user control.

Is this something we can look into as a possible alternative ?

**Comment by pkanher617** [comment]
@niwsa Thanks for posting this. We have looked at the Storage API and we are currently exploring options that will require changes to both the auth client library and server. 

The current workaround we are using is to introduce the authorization code flow for browsers, which limits the usage of iframes. We have introduced this in the @azure/msal-browser package which is currently in beta. We recommend using this package to get token exchange working in Safari browsers.

**Comment by niwsa** [comment]
@pkanher617 Thanks for the reply.However I understand that @azure/msal-browser is not available for B2C tenants which is really my use case.For now thinking of using https://github.com/AzureAD/passport-azure-ad with server side rendering.

**Comment by pkanher617** [comment]
@niwsa We are hoping to have support for B2C tenants by the end of this month, keep an eye out for new releases!

**Comment by HockeyJustin** [comment]
@pkanher617 - re your comment on 14th May - are B2C tenants now supported please?
