### ISSUE TITLE
MSAL.js is not working in IE11. I am getting 'signIn’ is undefined script error. I tried to run latest vanilatest as well and getting same error in vanila test as well.

### ISSUE THREAD

**Issue by lax-github** [AzureAD/microsoft-authentication-library-for-js#1658]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
If you are using a framework, please provide the framework and version (e.g. Angular v8, React v16, etc).

## Description
A clear and concise description of the bug. If you receive specific error codes, please include them.

## Security
Is this issue security related?

## Regression
Did this behavior work before?

## Configuration
Please provide your MSAL configuration options.

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
1. 
2. 
3. 

## Browsers
Is this issue browser-specific? If so, please detail which browsers are impacted (e.g. IE 11, Safari).

**Comment by lax-github** [comment]
using msal.js 1.1.3 package.

**Comment by jasonnutter** [comment]
@lax-github This is with one of the samples, correct?

**Comment by pkanher617** [comment]
Need to add IE 11 samples

**Comment by derisen** [comment]
@lax-github samples use ES6 conventions and will not work on IE11 without some additional steps. Please see [this answer](https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp/issues/61#issuecomment-630953375) for further guidance.

**Comment by jasonnutter** [comment]
Closing due to in activity. I'll add an item to our backlog for IE11 specific samples.
