### ISSUE TITLE
MSAL 1.3.1, broke authentication with Azure AD B2C

### ISSUE THREAD

**Issue by widget31too** [AzureAD/microsoft-authentication-library-for-js#1659]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.3.1` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
If you are using a framework, please provide the framework and version (e.g. Angular v8, React v16, etc).
Angular 8

## Description
A clear and concise description of the bug. If you receive specific error codes, please include them.
Authentication had been working with Azure AD B2C using msal 1.2.1. I tried upgrading to msal 1.3.1 (which should resolve another issue we were having), but authentication fails with "could not resolve endpoints" error.

I realized that the issue was the openid-configuration request URL had changed.
For msal 1.2.1 it was https://<authority>/tfp/<tenant>/<policy>/v2.0/.well-known/openid-configuration
For msal 1.3.1 it was https://<authority>/tfp/<tenant>/<policy>/**oauth2/v2.0/authorize/**/v2.0/.well-known/openid-configuration

Being morbidly curious, I got the msal library code and dug in, and found a change in AuthorityFactory, detectAuthorityFromUrl.
msal 1.2.1 used pathSegments[0] == "tfp" to detect B2C
msal 1.3.1 uses Object.keys(B2CTrustedHostList).length != 0 to detect B2C

Since B2CTrustedHostList wasn't being set, it was defaulting to standard AAD authority. Further digging, B2CTrustedHostList is only set if validateAuthority is true and knownAuthorities has values; other documentation indicates that validateAuthority must be false for B2C.

## Security
Is this issue security related?
No

## Regression
Did this behavior work before?
Yes, in msal 1.2.1.
## Configuration
Please provide your MSAL configuration options.

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```
Not entirely sure what you need - AAD B2C policy is B2C_1_SignIn
msal UserAgentApplication configuration included
      auth: {
        clientId: `<our client ID>`,
        authority: `<full authorize URL>`,
        validateAuthority: false,
        redirectUri: ...,
        postLogoutRedirectUri: ...,,
        navigateToLoginRequestUrl: false,
      }

## Reproduction steps
Requires working authentication via msal 1.2.1 to AAD B2C, then upgrade to use msal 1.3.1.

## Expected behavior
I can still authenticate...

## Browsers
Is this issue browser-specific? If so, please detail which browsers are impacted (e.g. IE 11, Safari).
Not browser-specific

**Comment by tnorling** [comment]
@widget31too Can you confirm whether `/oauth2/v2.0/authorize/` is part of the authority you are sending in your config? The authority url should only be in the format `https://example.b2clogin.com/example_tenant/policy` and can optionally also include`/tfp/`. The authorize endpoint info should be left off as msal will discover this with the openid-configuration call you see above.

**Comment by widget31too** [comment]
That indeed was the case. Unsure why that was working before (unless the B2C authority was stripping off he suffix).

Removed the /oauth2/v2.0/authorize suffix from the authority URL and authentication works.
