### ISSUE TITLE
Wrong protectedResourceMap Usage in README

### ISSUE THREAD

**Issue by eeskildsen** [AzureAD/microsoft-authentication-library-for-js#1660]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Documentation location
- [ ] docs.microsoft.com
- [ ] MSAL.js Github Wiki
- [x] README file
- [ ] Other (please fill in)
- [ ] Documentation does not exist

## Description
I think the sample `protectedResourceMap` usage is wrong. It shows a `[string, string[]][]` being passed to `config.framework.protectedResourceMap`. But that property requires `Map<string, string>`.

The property that does accept a `[string, string[]][]` is `angularConfig.protectedResourceMap`. So I think the readme should demonstrate setting that property instead of `config.framework.protectedResourceMap`.

Current readme sample code:

```
export const protectedResourceMap:[string, string[]][]= [
    ['https://buildtodoservice.azurewebsites.net/api/todolist', [ 'api://a88bb933-319c-41b5-9f04-eff36d985612/access_as_user' ]],
    ['https://graph.microsoft.com/v1.0/me', ['user.read']]
];

@NgModule({
    imports: [
        MsalModule.forRoot({
            auth: {
                clientId: 'Your client ID',
            },
            framework: {
                protectedResourceMap: protectedResourceMap // <---- The type is wrong, and if you use the required type instead (Map<string, string>), it breaks in production build (https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/407). I think this property should be avoided....
            }
        })
    ]
})
```

Proposed change:

```
export const protectedResourceMap:[string, string[]][]= [
    ['https://buildtodoservice.azurewebsites.net/api/todolist', [ 'api://a88bb933-319c-41b5-9f04-eff36d985612/access_as_user' ]],
    ['https://graph.microsoft.com/v1.0/me', ['user.read']]
];
 
@NgModule({
    imports: [
        MsalModule.forRoot({
            auth: {
                clientId: 'Your client ID',
            }
        }, {
            protectedResourceMap: protectedResourceMap
        })
    ]
})
```

**Comment by jasonnutter** [comment]
Good catch, we'll make sure this fixed, thanks!
