### ISSUE TITLE
When is MSAL.JS 2.0 (auth code flow) getting released?

### ISSUE THREAD

**Issue by jrmcdona** [AzureAD/microsoft-authentication-library-for-js#1669]
I am interested in the switching to auth code flow instead of implicit flow so that I can get the wids claim.

When would this be getting released?

**Comment by jrmcdona** [comment]
I will test the Beta/Preview version for auth code flow.

**Comment by hamiltonha** [comment]
@jrmcdona this is currently in beta/public preview, with public documentation going live later today on docs.microsoft. Please let me know if you have any feedback or questions testing the beta using the instructions in the msal-browser package or using the documentation (I will post links here this afternoon once published)

**Comment by kylephp** [comment]
@hamiltonha I am interested in beta preview too. Is the documentation for this published?

**Comment by jrmcdona** [comment]
@kylephp it is on their GIT site and here is a link to it.  https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-browser.   Which is linked from their main site GIT site https://github.com/AzureAD/microsoft-authentication-library-for-js

**Comment by hamiltonha** [comment]
@kylephp @jrmcdona Yep we are now in public preview! To get started here are some links: [quickstart](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-javascript-auth-code) [tutorial](https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-javascript-auth-code) [Registration guide](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-app-registration) [ITP solution](https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-third-party-cookies-spas)

**Comment by pkanher617** [comment]
#1000 is tracking this, closing.

**Comment by willzhan** [comment]
When will the CDN version be available for direct reference?

**Comment by jrmcdona** [comment]
@willzhan it is at the bottom of this page https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-javascript-auth-code#more-information

**Comment by kyro38** [comment]
When do you plan to publish it on npm ?

**Comment by jrmcdona** [comment]
@kyro38 it has been on NPM for a long time.

**Comment by jrmcdona** [comment]
npm install @azure/msal-browser
