### ISSUE TITLE
Library for

### ISSUE THREAD

**Issue by jrmcdona** [AzureAD/microsoft-authentication-library-for-js#167]
Hello,

Do you all happen to have a library and example for **The MSA v1 OAuth 2.0** protocol for 1st party site?  Look to implement that flow with redirecting to the login page (not popup).

`The MSA v1 OAuth 2.0 protocol: When clients implement MSA v1 OAuth, they communicate directly with the MSA login system at https://login.live.com. The MSA v1 OAuth protocol supports only MSA users - it does not support Azure AD users whatsoever. If your goal is for your clients to get tokens from the MSA v1 OAuth protocol, this is the correct choice for you.`

Thanks

**Comment by rohitnarula7176** [comment]
@jrmcdona I am not aware of any such library. Please post your question on StackOverflow to get a response to your query.
