### ISSUE TITLE
InteractionRequiredAuthError: AADSTS50058: A silent sign-in request was sent but no user is signed in

### ISSUE THREAD

**Issue by Anshu8405** [AzureAD/microsoft-authentication-library-for-js#1672]
When the user logs in, MSAL saves the id_token in the browser cache. This token expires in 1 hr. Since I am using localStorage, this cache persists when you re-open the browser. So, if I re-opening the browser within 1 hr of logging in, everything will work fine, as I noticed, since the cached token is valid. But if I re-open the browser after 1 hr, the cached token is expired and MSAL tries to renew the token but it fails since the AAD authentication cookie is expired or not present and I get the AADSTS50058 error. 

And also this error blocks the navigation in Angular application.
Can you anyone help me to solve this?

`"@azure/msal-angular": "^1.0.0-beta.4",
 "msal": "^1.2.2",`

**Comment by jasonnutter** [comment]
@Anshu8405 Please upgrade to `@azure/msal-angular@1.0.0`, which has a fix for the the MSAL Guard preventing navigation when an error like this is encountered.

Also, in the future, please use one of the pre-defined issue templates, as it helps us more effectively answer your issue, thanks!
