### ISSUE TITLE
unable to add id_token_hint while logging out

### ISSUE THREAD

**Issue by CoderMb** [AzureAD/microsoft-authentication-library-for-js#1673]
-  "@azure/msal-angular": "^1.0.0"
-   Angular 8.2.14

Azure B2c gives us the provision to mandate id_token_hint to logout but in angular msal ther are no options to specify this. On logout() we get an error that id_token_hint is missing. 

I was not able to find anything on adding extraQueryParameters also to logout?

![image](https://user-images.githubusercontent.com/19566265/82212653-8231c080-9930-11ea-994c-ed7d23d4406d.png)

**Comment by tnorling** [comment]
@CoderMb This is currently not supported but is under consideration. There is already an open issue for this so I'm closing as duplicate but you can track #996 for updates. Thanks!
