### ISSUE TITLE
handleRedirectCallback returning null for authErr?

### ISSUE THREAD

**Issue by thoo1** [AzureAD/microsoft-authentication-library-for-js#1674]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [X] `@azure/msal@1.3.0`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
If you are using a framework, please provide the framework and version (e.g. Angular v8, React v16, etc).

React 16

## Description
type of this.userAgentApp.handleRedirectCallback is: 
handleRedirectCallback(authCallback: authResponseCallback): void;
where authResponseCallback is:
export declare type authResponseCallback = (authErr: AuthError, response?: AuthResponse) => void;

I have passed in a callback that fits this signature however, on first time load of the site when user logs in, authErr is null and the site crashes because of a TypeError

![image](https://user-images.githubusercontent.com/55852795/82244149-a15f2c80-98f5-11ea-85ec-2d711457f3f7.png)

^errorCode is a property of AuthError type. Let me know if you need code example

## Security
Is this issue security related?

No
## Regression
Did this behavior work before?

Not sure
## Configuration
Please provide your MSAL configuration options.

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.

{
      auth: {
        clientId: this.clientId,
        authority: this.authority,
        redirectUri: this.loginRedirectUri,
        postLogoutRedirectUri: this.postLogoutRedirectUri
      },
      cache: {
        cacheLocation: "localStorage",
        storeAuthStateInCookie: true
      },
      system: {
        logger: new Logger(MsalAuthContext.msalLoggerCallback, { level: LogLevel.Verbose, piiLoggingEnabled: false }),
        navigateFrameWait: 0
      }
    }
```

## Reproduction steps
Not 100% reproducible..

## Expected behavior

I expect the callback to not be passed a null for authErr in the callback authResponseCallback = (authErr: AuthError, response?: AuthResponse) => void;

## Browsers
Is this issue browser-specific? If so, please detail which browsers are impacted (e.g. IE 11, Safari).

**Comment by thoo1** [comment]
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/0dbbda42160addfdfb926f0245b702f52009365a/lib/msal-core/src/UserAgentApplication.ts#L297 this might be root cause..

**Comment by tnorling** [comment]
@thoo1 Please check if `error` is truthy before referencing `error.errorCode`. Error is returned as null if no error occurred. You can take a look at some of our samples for guidance on how to implement the `handleRedirectCallback`

**Comment by thoo1** [comment]
@tnorling makes sense, however the type of the callback seems to say that it'll be called with a non-null authErr `export declare type authResponseCallback = (authErr: AuthError, response?: AuthResponse) => void;`

**Comment by tnorling** [comment]
@thoo1 Gotcha, I understand the confusion. The reason it is set up like this is to ensure that the error object is always returned to the first parameter and the response in the 2nd. If both were optional you would have to inspect the response to determine if its an error or success case. I understand this may not be the most intuitive but I hope that explanation makes sense.

**Comment by tnorling** [comment]
This will also be more clearly defined in the code when we turn on `strictNullChecks` which we are currently working on

**Comment by thoo1** [comment]
got it, for now I will add the null check, thanks

**Comment by kibum-kim-1** [comment]
authErrorHandler missed the null check, so it's throwing the same error.

![image](https://user-images.githubusercontent.com/49103630/84388052-8d87ad00-abb9-11ea-956e-85bc0a6e9f18.png)

[https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/0dbbda42160addfdfb926f0245b702f52009365a/lib/msal-core/src/UserAgentApplication.ts#L313](url)

**Comment by tnorling** [comment]
@kibummy This seems to suggest you are not passing a callback function to `handleRedirectCallback` please take a look at our samples for guidance on how to implement the redirect flow and open a new issue if you are still having issues. Thanks!

**Comment by kibummy** [comment]
@tnorling Thanks for the fast response! I've read that `handleRedirectCallback` has become an optional parameter since 1.3.0. Do I still need to provide a stub function to the callback?

I am using 
"@azure/msal-angular": "1.0.0"
"msal": "1.3.2"

![image](https://user-images.githubusercontent.com/49103630/84440739-20e3d100-ac00-11ea-88fc-fd1de9dbf1ed.png)

**Comment by tnorling** [comment]
@kibummy That is correct. It is optional, but if you do choose to implement it you must pass functions to it. The error you provided in your previous comment seems to suggest you called `handleRedirectCallback` and passed something other than a function to it.

**Comment by kibummy** [comment]
That's the thing. I didn't choose to implement it. I'm not even touching MsalService. I'm using MsalGuard through Angular CanActivate which calls loginInteractively and such. The call stacks are shown in the error that I posted earlier.

I wish I could provide some code snippets but I can't without AAD.

**Comment by tnorling** [comment]
@kibummy Can you open a new ticket and include steps to repro? Thanks!

**Comment by vajnorcan** [comment]
I experience this issue when I include the **popup: false** in the config for MsalModule. If I include the **popup:true** popup is being shown and handles everything ok. But as soon as it's false, it gives the same as the author of this post has posted before.
