### ISSUE TITLE
sample msal-node-device-code cannot read property setKnownAuthorities

### ISSUE THREAD

**Issue by ctaggart** [AzureAD/microsoft-authentication-library-for-js#1677]
Please follow the issue template below. 

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Upcoming Library
- [x] `@azure/msal-node@1.x`

## Type
- [ ] Bug
- [ ] Feature
- [ ] Enhancement
- [ ] Tooling
- [ ] Documentation
- [x] Samples
- [ ] Other (please describe)

## Source
- [ ] Internal (MSAL.js team)
- [x] Customer request

## Description
I tried out a couple of the msal-node examples with the latest (commit fc973cf951a30e813c9385df2c06aa3d294c7be0) and both failed, unable to read property msalCommon.B2cAuthority.setKnownAuthorities.

I built and ran all the tests successfully in msal-node. In the sample directory, I linked to the dependencies with:
```
npm link @azure/msal-common
npm link @azure/msal-node
```
You can see that:
```
Camerons-MacBook-Pro:msal-node-device-code cameron$ ls -al node_modules/@azure/
total 0
drwxr-xr-x  4 cameron  staff  128 May 18 18:00 .
drwxr-xr-x  3 cameron  staff   96 May 18 17:59 ..
lrwxr-xr-x  1 cameron  staff   69 May 18 18:00 msal-common -> ../../../../../../../../usr/local/lib/node_modules/@azure/msal-common
lrwxr-xr-x  1 cameron  staff   67 May 18 17:59 msal-node -> ../../../../../../../../usr/local/lib/node_modules/@azure/msal-node
```

But when I `npm start` or just `node index.js`:
```
Camerons-MacBook-Pro:msal-node-device-code cameron$ node index.js
/Users/cameron/github/microsoft-authentication-library-for-js/lib/msal-node/dist/msal-node.cjs.development.js:715
    msalCommon.B2cAuthority.setKnownAuthorities(this.config.auth.knownAuthorities);
                            ^

TypeError: Cannot read property 'setKnownAuthorities' of undefined
    at PublicClientApplication.ClientApplication (/Users/cameron/github/microsoft-authentication-library-for-js/lib/msal-node/dist/msal-node.cjs.development.js:715:29)
    at new PublicClientApplication (/Users/cameron/github/microsoft-authentication-library-for-js/lib/msal-node/dist/msal-node.cjs.development.js:894:31)
    at Object.<anonymous> (/Users/cameron/github/microsoft-authentication-library-for-js/samples/msal-node-device-code/index.js:15:13)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11
```

## Acceptance Criteria
The msal-node-device-code sample works. I really that it is super new, but also super cool!

**Comment by sangonzal** [comment]
@ctaggart Are you linking against the local version of msal-common? Can you try running in:   
- "lerna bootstrap"
- "npm run build" in msal-common
- "npm run build" in msal-node

You can then try running any of the Node samples.

**Comment by ctaggart** [comment]
Thank you @sangonzal! Yes, I'm trying to run a local version. I pulled latest, followed your instructions, and `npm start` in `samples/msal-node-device-code` worked.
