### ISSUE TITLE
MSAL 2, override redirectUrl

### ISSUE THREAD

**Issue by jrmcdona** [AzureAD/microsoft-authentication-library-for-js#1679]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
@azure/msal-browser

I am not seeing any example on how you might override the redirectUrl for a loginRequest.  They loginRedirect take an AuthenticationParameters object which doesn't have redirectUrl property.  So If I want to initiate login in my Angular SPA from a specific page, how would I redirect back to that page versus the default page set up in the initial configuration.

**Comment by pkanher617** [comment]
@jrmcdona I recognize this is a gap. We are working on updating our request APIs, and will make sure to include redirect URI moving forward. Should be included in a future release.

**Comment by jrmcdona** [comment]
@pkanher617 When would this gap be fixed?  In the coming weeks?

**Comment by pkanher617** [comment]
Should be fixed in the next release of the beta. I will update here when it is available.

**Comment by DarkLite1** [comment]
It would be great to have this feature. Please don't close.

**Comment by jrmcdona** [comment]
@tnorling  ETA?    Since this is somewhat of a big gap we need an ETA so we can do something else instead.

**Comment by tnorling** [comment]
@jrmcdona `msal-browser@2.0.0-beta.3` has been released. Let us know if you are still experiencing issues after upgrading.
