### ISSUE TITLE
How do I wait for the login to finish before proceeding to render my app?

### ISSUE THREAD

**Issue by sarahkang58** [AzureAD/microsoft-authentication-library-for-js#1684]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [X] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
I have an app built with React components, and on startup (when the user doesn't have an auth token yet) I first call loginPopup().  I do see the popup briefly come up, but then it quickly goes away (so I don't actually see the login screen).  Then, there's an error with accessing the API because it seems like the login didn't completely finish before trying to access the API, so the user is technically not authenticated yet (which then results in an error screen when the user first opens the app).  However, I do see the auth token in the developer tools, so refreshing the page then makes the app work again.

I found a workaround where I use setInterval() to wait for the login to finish and for the auth token to generate before trying to access the API.  This way, the user just sees a Loading screen for a bit longer than usual when he first accesses the app instead of seeing an Error screen and then having to refresh the page.

However, I'm wondering if there's a better way to wait for the login to finish?  Shouldn't there be a way to await the call and provide some sort of callback function when the login is done?

**Comment by pkanher617** [comment]
@sarahkang58 Could you please post a snippet of your code? loginPopup returns a Promise, so you should be able to wait on that returned Promise. You can learn more about Promises [here](https://javascript.info/promise-basics). You shouldn't need setInterval() for `loginPopup()`. 

> I do see the popup briefly come up, but then it quickly goes away (so I don't actually see the login screen). Then, there's an error with accessing the API because it seems like the login didn't completely finish before trying to access the API, so the user is technically not authenticated yet (which then results in an error screen when the user first opens the app). However, I do see the auth token in the developer tools, so refreshing the page then makes the app work again

This behavior usually happens because the server detects a signed-in account and silently authenticates a user. When you are attempting `loginPopup()`, do you already have an active session in the browser you are using? Could you check if this is an issue in an incognito or private browser? Since the tokens are being sent back to the application, it seems like the auth is completing successfully.

**Comment by sarahkang58** [comment]
@pkanher617 Hi, thank you for your response!  I'm working with the team to change how we're using loginPopup so that we can use the callback functionality, so that should fix the issue!

A related question though, what do you think is the best way to determine if the login is successful or not?  I noticed that the response is of type AuthResponse with multiple properties, but which property can tell me whether or not the login was successful?

**Comment by tnorling** [comment]
@sarahkang58 You can call `msal.getAccount()` to verify you were successfully logged in. Take a look at our [sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/VanillaJSTestApp/app/default/auth.js) to see how to implement this.

**Comment by sarahkang58** [comment]
@tnorling ok thank you!  i'll look into it!
