### ISSUE TITLE
Access_token is always null

### ISSUE THREAD

**Issue by Codeluck** [AzureAD/microsoft-authentication-library-for-js#1688]
## Library
- [ x] `msal@1.1.3`

## Framework
React v16

## Description
I have an Azure B2C App configured as a multi-tenant app and a flow with OpenId IDP pointing to that app.
IDP Scope parameter is `openid email profile https://mytenant.onmicrosoft.com/test/User.ReadOnly`

## Security
Is this issue security related? NO

## Regression
Did this behavior work before? NO

## Configuration
Please provide your MSAL configuration options.

```{
	"auth": {
		"clientId": "=GUID=",
		"authority": "https://mytenant.b2clogin.com/tfp/mytenant.onmicrosoft.com/B2C_1_SignIn",
		"validateAuthority": false
	},
	"cache": {
		"cacheLocation": "localStorage",
		"storeAuthStateInCookie": false
	},
	"system": {
		"logger": {
			"level": 3,
			"correlationId": "1234",
			"piiLoggingEnabled": false
		}
	}
}
```

Azure B2C policies - default sign in flow, created from the portal

## Reproduction steps
1. Every time I call `acquireTokenSilent()` it causes redirect to MS sign in url
2. By turning verbose logging on I've noticed that: `accessToken` is always `null`, while `id_token` is here
3. Token is not stored in `localStorage` cache: I always got `Token is not in cache for scope` in browser's console when I am trying to call `acquireTokenSilent()` again.

In Azure B2С app both `Access Token` and `Id Token` check boxes are checked.
Btw, in claims of `id_token` it always returns `idp_access_token` with a valid access token in it.

## Expected behavior
I should be able to receive access token and it should be cached properly.

## Browsers
I don't think it's related to browser. Mine is Chrome 81

**Comment by jasonnutter** [comment]
@Codeluck The `openid email profile https://mytenant.onmicrosoft.com/test/User.ReadOnly` scopes are scopes for multiple resources (MS graph and your custom resource). When you have scopes that span multiple resources, you must call `acquireTokenSilent` once for each set of scopes per resource. This because access tokens can only be used for one resource, and they are cached accordingly.

```js
const graphAccessToken = await msalInstance.acquireTokenSilent({
  scopes: [ "openid", "email", "profile" ]
});

const resourceAccessToken = await msalInstance.acquireTokenSilent({
  scopes: [ "https://mytenant.onmicrosoft.com/test/User.ReadOnly" ]
});
```

**Comment by Codeluck** [comment]
@jasonnutter - thank you for the explanation. Now I use the following flow:

1. Call `msal.loginRedirect({
  scopes: [ "openid", "email", "profile" ]
})`
2. Call `msal.acquireTokenSilent({
  scopes: [ "https://mytenant.onmicrosoft.com/test/User.ReadOnly" ]
})`

The first call successfully returns an `id_token` while the 2nd one fails.
After 2nd call I got an error: 
`InteractionRequiredAuthError: AADB2C90077: User does not have an existing session and request prompt parameter has a value of 'None'.`

Any suggestion on that? Thank you in advance!

**Comment by Codeluck** [comment]
UPD: after googling and searching issues I found the root of this problem. Looks like I had 'Block third-party cookies' setting turned on in my Chrome's instance. It's immediately started working once I turn it off.
Question: is there a way to avoid using 3rd party cookies? I don't think we can guarantee that these cookies are allowed for any client.

P.S. I used Chrome 83, Windows 10

**Comment by jasonnutter** [comment]
> UPD: after googling and searching issues I found the root of this problem. Looks like I had 'Block third-party cookies' setting turned on in my Chrome's instance. It's immediately started working once I turn it off.
> Question: is there a way to avoid using 3rd party cookies? I don't think we can guarantee that these cookies are allowed for any client.
> 
> P.S. I used Chrome 83, Windows 10

Unfortunately, MSAL.js v1 implements the Implicit Flow, which relies on 3rd-party cookies. As a workaround, you should invoke acquireTokenPopup or acquireTokenRedirect when you encounter this error (which you should do anyways). 

We are currently working on MSAL.js v2, which will switch to the Auth Code Flow, which will mitigate third-party cookies issues in most scenarios. This is currently in public preview, see #1000.

**Comment by Codeluck** [comment]
@jasonnutter thank you for the update. 
Q: do you think we could use MSAL.js v2 already for the current configuration? Is it stable enough?

**Comment by jasonnutter** [comment]
> Q: do you think we could use MSAL.js v2 already for the current configuration? Is it stable enough?

MSAL.js v2 is in public preview (beta). It is not intended for production usage, yet.

> I believe it doesn't support Azure AD B2C yet. Could you confirm, please?

B2C is supported: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1000#issuecomment-634217520

> Q2: What other options do we have? I only see a manually-controlled token with very long expiration time (24 hours for instance).

Not sure what you mean, options other than MSALjs?

**Comment by Codeluck** [comment]
@jasonnutter thank you  for the answer!

> Not sure what you mean, options other than MSAL.js?

I mean do we have any other option while MSAL.js v2 is not in production? How would you suggest to workaround this problem? I think MS is recommending to use MSAL.js for SPA but looks like it has stopped working after that '3rd party cookies' problem :(

**Comment by jasonnutter** [comment]
> @jasonnutter thank you for the answer!
> 
> > Not sure what you mean, options other than MSAL.js?
> 
> I mean do we have any other option until MSAL.js v2 is in production? How would you suggest to workaround this problem? I think MS is recommending to use MSAL.js for SPA but looks like it has stopped working after that '3rd party cookies' problem :(

The available mitigations are:
- Invoke acquireTokenPopup or acquireTokenRedirect when you receive errors calling acquireTokenSilent (which you should do anyway).
- Users can disable third-party cookie blocking.
- Use a server-side library (e.g. MSAL.net) which does not rely on third-party cookies.

**Comment by Codeluck** [comment]
@jasonnutter thanks a lot for the answer!
Q: Does MSAL.js v2 have the same 3rd party cookies issue at the moment? If not then I am gonna try to temporary use it.

**Comment by jasonnutter** [comment]
> Could you provide any examples on how to use MSAL.net in together with FE web app?

https://docs.microsoft.com/en-us/azure/active-directory/develop/sample-v2-code#web-applications

> Q: Does MSAL.js v2 have the same 3rd party cookies issue at the moment? If not then I am gonna try to temporary use it.

No, MSAL.js v2 does not rely on third-party cookies in most scenarios.

> Q2: Sorry if I am too annoying :) But how other people solve this 3rd party cookies problem?

Auth Code Flow w/ PKCE (which MSAL.js v2 implements) is the solution for the third-party problem, as it uses POST requests to obtain tokens, instead of iframes.

**Comment by Codeluck** [comment]
@jasonnutter Thank you for such a good support! Looks like we are going to wait until Msal.js v2 releases or at least when you fix an issue with wrong B2C discovery url in V2.
I think this thread can be closed.
