### ISSUE TITLE
WindowUtils.monitorWindowForHash does not return hash

### ISSUE THREAD

**Issue by streamcode9** [AzureAD/microsoft-authentication-library-for-js#1689]
## Library
- [x] `msal@1.3.1`

## Description
What could prevent MSAL from getting the token?
The code below works for some users but fails for others. I have debugged the MSAL library and found out that when the library renews the token it calls `loadIframeTimeout` and inside `WindowUtils.monitorWindowForHash`. As a result, its function returns a valid hash for some users and an empty string for another. Could you advise me on how can I find out the issue cause?
As I understand the logic of `loadIframeTimeout` is to create an iframe, open URL, and wait for a hash part. So I guess it could be an issue with opening URL in the iframe or getting the hash from the URL inside the iframe. Does it make sense?

## Minimal reproducible example
```js
const tokenRequest = { scopes: [ /* scopes go here */] };
var userAgentApplication = new UserAgentApplication({
    auth: {
      authority, clientId,
      navigateToLoginRequestUrl: false,
      postLogoutRedirectUri: baseUri,
      redirectUri: baseUri,
      validateAuthority: true
    },
    system: { loadFrameTimeout: 10000 },
    cache: { cacheLocation: 'localStorage', storeAuthStateInCookie: true }
  });
userAgentApplication.acquireTokenSilent(tokenRequest);
```

**Comment by jasonnutter** [comment]
@streamcode9 This could happen for a few different reasons:

1. The iframe never gets redirected back to the redirect uri (on your domain) set for the application/request. 
2. The redirect uri loaded in the hidden iframe removes the hash from the url in the iframe before the library has a chance to parse it.
3. The iframe gets redirected back to the redirect uri on your domain, but the response is not formatted properly and the library is unable to parse it.

Can you figure out which of these is happening?

**Comment by streamcode9** [comment]
@jasonnutter thank you for your help!

It looks like the first point - "The iframe never gets redirected back to the redirect uri". It seems some users have a middleware between `login.microsoft.com` and the redirect uri that should be taken into account.
