### ISSUE TITLE
allow-top-navigation re authorization (MSAL disables it by default)

### ISSUE THREAD

**Issue by reijam** [AzureAD/microsoft-authentication-library-for-js#1690]
## Library
- [x ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Documentation location
- [ ] docs.microsoft.com
- [ ] MSAL.js Github Wiki
- [ ] README file
- [ ] Other (please fill in)
- [x ] Documentation does not exist

## Description

Not sure if this is a documentation issue or an actual limitation. 

I have a requirement to allow the user to access an href location other than just the base href of say localhost:3000.  I want the user to be able to go to localhost:3000/table or   localhost:3000/charts

Presently when I try this i get an error 
`authorize:82 Unsafe JavaScript attempt to initiate navigation for frame with origin 'http://localhost:3000' from frame with URL 'https://login.microsoftonline.com/ `  
... etc ...
 `The frame attempting navigation of the top-level window is sandboxed, but the flag of 'allow-top-navigation' or 'allow-top-navigation-by-user-activation' is not set. `

The normal way this happens is with the **allow-top-navigation**  header parameter... but his is disabled by msal.js  (and I cannot find in the code where it is removed)

If there is a way to do this any help would be appreciated ( and should be included in the docs somewhere)

Thanks

**Comment by jasonnutter** [comment]
@reijam This error is happening because login.microsoftonline.com is try to navigate the top frame of your application (from inside the hidden iframe) to show an error message. Try opening the login.microsoftonline.com url in its own tab, and I would expect to see an error message.

**Comment by jasonnutter** [comment]
Closing, let us know if you further questions.
