### ISSUE TITLE
Resource Owner Password Credential Grant in browser

### ISSUE THREAD

**Issue by cclauson** [AzureAD/microsoft-authentication-library-for-js#1692]
Is it possible to do an [ROPC grant](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth-ropc) in the browser using MSAL?  I'm fully aware of all of the OAuth caveats surrounding this grant, but it would actually be extremely useful in my situation for the purposes of automated testing.

Thanks

**Comment by jasonnutter** [comment]
@cclauson No, we do not support ROPC in MSAL.js (and there are currently no plans to support it).
