### ISSUE TITLE
Migrating from MSAL 1.x to MSAL 2.x

### ISSUE THREAD

**Issue by DarkLite1** [AzureAD/microsoft-authentication-library-for-js#1696]
## Library
- [x] `@azure/msal-browser@2.x.x`

## Documentation location
- [x] MSAL.js Github

## Description
In the [migration guide](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/v1-migration.md) from MSAL 1 to MSAL 2 the following code is written:

```js
async function signIn() {
    myMSALObj.loginRedirect(loginRequest);
}
```

Given that there is no `await` statement before `myMSALObj.loginRedirect(loginRequest);` makes me think that it doesn't return a promise and should be written like this:

```js
function signIn() {
    myMSALObj.loginRedirect(loginRequest);
}
```

I'm new to javaScript but I thought this needed some attention in case I'm correct.

**Comment by jasonnutter** [comment]
@DarkLite1 Correct, technically `async` is not needed for this function. cc: @pkanher617
