### ISSUE TITLE
Type TokenRenewParameters not exported

### ISSUE THREAD

**Issue by jrmcdona** [AzureAD/microsoft-authentication-library-for-js#1706]
## Library
- [ ] `@azure/msal-browser@2.x.x`

## Description
I am trying to use TokenRenewParameters type to use with  :
`acquireTokenSilent(silentRequest: TokenRenewParameters): Promise<TokenResponse>;`

However, that type is not exported and available for me to use; so I am passing in an "any" type.

Not sure if this is by design or something missed here.

**Comment by sameerag** [comment]
This probably will change with the refactor in progress. cc @pkanher617 for details soon.

**Comment by tnorling** [comment]
@jrmcdona `msal-browser@2.0.0-beta.3` has been released and the type has been changed to `SilentFlowRequest` which is now exported. Let us know if you're still experiencing issues.
