### ISSUE TITLE
Newest version doesn't support navigateToLoginRequestUrl anymore

### ISSUE THREAD

**Issue by tobiasbrenner** [AzureAD/microsoft-authentication-library-for-js#171]
Unfortunately the newest version doesn't have a flag where you can prevent the lib from redirecting to an url after a successful token refresh. Therefor an angular SPA will load two times. Please reintroduce this flag as a part of the options object in the UserAgentApplication constructor.

Best regards,
Tobias Brenner

**Comment by rohitnarula7176** [comment]
@tobiasbrenner The latest version has this property which allows you to do your custom navigation.
