### ISSUE TITLE
getAccount return type for idTokenClaims.oid

### ISSUE THREAD

**Issue by DarkLite1** [AzureAD/microsoft-authentication-library-for-js#1710]
## Library
- [x] `@azure/msal-browser@2.0.0-beta2`

## Description
We receive the following TypeScript error:

> TS2322: Type 'string | undefined' is not assignable to type 'string'.

This comes from expecting the `idTokenClaims.oid` to be a string:

```js
const accountID = ref('')

export const setAccountID = () => {
  const account = auth.getAccount()

  if (account) {
    accountID.value = account.idTokenClaims.oid
  } else {
    accountID.value = ''
  }
}
```

Should the property `oid` not [always be populated](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1620) with a string when `getAccount()` is successful as it identifies the logged on user?

Our current workaround is this:
```js
  const account = auth.getAccount()

  if (account) {
    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
    accountID.value = account.idTokenClaims.oid!
  } 
```
## Regression
- [x] Did this behavior work before? I think it did in version 1.3.0

## More details
In [Account.ts](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/src/Account.ts) you see the following lines:

```js
import { StringDict } from "./MsalTypes";
idTokenClaims: StringDict;
```
When verifying [MsalTypes](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/src/MsalTypes.ts) we see this:

```js
export type StringDict = {[key: string]: string};
```

The issue with this setup is that the property `oid` on the object `idTokenClaims` can be `undefined` when it's not added. I think this is why TS fails to see that there is always an `oid` property when `getAccount()` succeeds.

If I got this wrong please correct me. As I see it now there are 3 options:
- Either TS should be smart enough to see that the property `oid` is always there when `getAccount()` succeeds, this is not the case, so there should be a bug report at TS for this issue.
- TS is correct but the type definition in the msal library is incorrect and should be corrected. So that the property `oid` is hard coded on the `idTokenClaims` property.
- I got it totally wrong, which happens :D 

Continuation of [issue 4](https://github.com/Azure-Samples/ms-identity-javascript-v2/issues/4)

**Comment by tnorling** [comment]
@DarkLite1 The `oid` claim is not 100% guaranteed to be returned from the service and msal just passes through what the service returns, thus we need to mark it as optional in our code. In most cases it will be present but there are some edge cases where it may not be. If it is not returned for your use case you should be able to enable it in the app portal. But in terms of the problem this poses, I would suggest using the `accountIdentifier` property on the `Account` object as this may be more reliable. This property is type `string` and returns the `oid` in most cases or falls back to `sub` if `oid` is not present.

**Comment by DarkLite1** [comment]
In my case I'm trying to identify a user with a unique string. A user is someone who logged into to our Azure AD. I've asked this questions [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1620) and the answer was to use the `oid` property.

In my use case, with all tests I've done already, I always get an `oid` back. When you say it's not 100% guaranteed to be returned, is that because of a configuration within Azure? Or a different config of msal? I mean, if you get it once will you get it always?

As a side note, when a user logs in from mobile, desktop, or whatever and he authenticates to Aszure AD will the `accountIdentifier` always be the same for him? If so, this could be used too. 

It's a bit unclear to me. Thank you for suggesting the best approach. I just want a unique user ID so the apps settings for that user are set when he logs back in.

**Comment by tnorling** [comment]
> I mean, if you get it once will you get it always?

Yes. This depends on the token claims configured on your id_token. The `oid` claim is returned by default but there are some edge cases msal needs to handle where it may not be returned and this is the reason the type is possibly undefined. This should not be something you need to worry about.

> As a side note, when a user logs in from mobile, desktop, or whatever and he authenticates to Aszure AD will the `accountIdentifier` always be the same for him? If so, this could be used too.

Yes. `accountIdentifier` **is** `oid` unless it does not exist in which case it falls back to `sub`. I suggested this because, unlike `oid`, it must be type string.

**Comment by DarkLite1** [comment]
Awesome! Switched my code to using the `accountIdentifier` instead of `oid`:

```js
  const account = auth.getAccount()

  if (account) {
    accountID.value = account.accountIdentifier
  } 
```
