### ISSUE TITLE
Authorization missing in request headers for specific words in URL 

### ISSUE THREAD

**Issue by mylle** [AzureAD/microsoft-authentication-library-for-js#1712]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x ] `@azure/msal-angular@1.0.0-beta-4`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
Angular

## Description
I have a weird problem. I created a few new endpoints in my API, but when I have a specific word 'multipress' in the request API the request is send without authorization bearer token.
When I change the word 'multipress' to 'mp' in the API endpoint URL, the request works (and bearer is in the request header.

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration
With AD, and API also.
```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Browsers/Environment
- [x ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by Hyperionza** [comment]
Ditto, except mine refuses to attach a bearer to a GET  request with endpoint `https://localhost:44323/api/security/profilemenu`
If I change it to 'menu' instead of 'profilemenu' it works. Also in parallel with this request is another GET request to the same '/api/security' controller but targeting endpoint 'navigationmenu' which works fine. To make sure I wasn't imagining it, I switched the endpoint url back and forth and it consistently only failed at 'profilemenu'

using Angular 9 with  MSAL 1.3.1 and MSAL-Angular 1.0.0, browser: chrome

Happy to provide more details if required

**Comment by pbranforn** [comment]
Are there any news on this topic? Sounds scary to me and we are hitting this, too!

**Comment by jasonnutter** [comment]
Apologies for the delay, as I've been busy with some other work items. We're aware of this issue and will be addressing it soon. Thanks!

**Comment by vitaliidasaev** [comment]
I've made own implementation of MsalInterceptor to overcome issues with protectedResourceMap.  
This is my custom code block:

    // #region own workaround in order not to put every api endpoint url to settings
    if (!scopes && req.url.startsWith(this.settingsService.apiUrl)) {
      scopes = [this.auth.getCurrentConfiguration().auth.clientId];
    }
    // #endregion
    
    // If there are no scopes set for this request, do nothing.
    if (!scopes) {
      return next.handle(req);
    }
    
PS: Vote for wildcard in protectedResourceMap https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1776

**Comment by mylle** [comment]
This problem is still existing. Don't close this ticket.

**Comment by mylle** [comment]
This problem is still existing. Don't close this ticket.

**Comment by Hyperionza** [comment]
This problem is still existing. Don't close this ticket.

**Comment by mylle** [comment]
When can I download a new version of @azure/msal-angular to fix this problem?

**Comment by jo-arroyo** [comment]
@mylle A new version was published last night. Please try `@azure/msal-angular@1.1.1` and let us know if you have any feedback.
