### ISSUE TITLE
Logger: Unable to get valid login request url from cache, redirecting to home page

### ISSUE THREAD

**Issue by thoo1** [AzureAD/microsoft-authentication-library-for-js#1713]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [X] `@azure/msal@1.3.0`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
In the logger for UserAgentApplication, it sometimes logs: `Unable to get valid login request url from cache, redirecting to home page`

Why does this happen and is there any action I can take to mitigate these errors?
Thanks!

**Comment by jasonnutter** [comment]
@thoo1 What APIs are you calling when this occurs? `acquireTokenRedirect` or `loginRedirect`? (or both). 

Your configuration and usage of those APIs would also be helpful, thanks!

**Comment by thoo1** [comment]
I believe `loginRedirect`. When looking at logs for users that get this, an exception also gets thrown with `errorCode: login_progress_error`

**Comment by thoo1** [comment]
btw if you'd like to see our code, feel free to contact me on teams, my alias is thoo
