### ISSUE TITLE
Authentication without popup or redirect

### ISSUE THREAD

**Issue by eagerestwolf** [AzureAD/microsoft-authentication-library-for-js#1719]
## Library
- [x] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
So, I am developing an internal application that does not need access to B2C resources. I don't need the user to grant any permissions for anything relating to their Office 365 subscription and everything I need will be handled in code by an SPA using (much to my dismay because Microsoft refuses to admit Vue exists) React using connection strings and an ORM. Users need to have access to relevant information to them, but the relationships are far too intricate to establish via traditional OAuth claims. Furthermore, many of my users won't have access to Office 365 and if I present/redirect them with/to a Microsoft login page, well that's just begging a user to go to the Azure portal and see what they can find, which is a ***MASSIVE*** security flaw. Is there any way I can simply collect the credentials, **in my own login form**, and pass them to a Microsoft API to do the authentication (***NOT AUTHORIZATION***)? If not, then I think I'm just going to cancel my Office 365 subscription and move over to G Suite because Google **does** support this flow, as does Amazon; so I'm perplexed why Microsoft refuses to do so.

**Comment by jasonnutter** [comment]
@eagerestwolf This is supported via [ROPC](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth-ropc). Note, this flow is not supported in the MSAL.js library, but can be used directly as noted in the documentation.
