### ISSUE TITLE
RedirectUri and CacheStorage

### ISSUE THREAD

**Issue by spottedmahn** [AzureAD/microsoft-authentication-library-for-js#172]
If I specify a `redirectUri` via the constructor, shouldn't it be setting that value in the `cacheStorage` too?

```javascript
new UserAgentApplication(
	environment.auth.webAppId,
	this.authority,
	this.authCallBack,
	{
             redirectUri: window.location.origin
	});
```

One example of a conflict:

```javascript
if (window.parent === window && !isPopup) {
    window.location.href = self._cacheStorage.getItem(Constants.loginRequest);
}
```

[Source code](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/54439c2b75eabb4885207d7f9fa2c63c3ca7ae6c/src/UserAgentApplication.ts#L1347)

**Comment by MarkHawcroft** [comment]
The redirect Uri you configure is the one B2C will redirect to. 

The following
` window.location.href = self._cacheStorage.getItem(Constants.loginRequest);`
seems to always want to take you back to the page you were on when the loginredirect was initiated.

**Comment by spottedmahn** [comment]
>... I'm in a similar situation with an Angular SPA...

Hey @MarkHawcroft - any chance you can put that comment on #102?

**Comment by rohitnarula7176** [comment]
Duplicate of #243
