### ISSUE TITLE
How to prevent acquireTokenSilent from calls to SSO

### ISSUE THREAD

**Issue by streamcode9** [AzureAD/microsoft-authentication-library-for-js#1721]
## Library
- [x] `msal@1.3.1`

## Description
I've noticed that after I call `acquireTokenSilent`, there are a few calls (not sure who does this call MSAL itself or https://login.microsoftonline.com/ page inside the MSAL's iframe) to `https://autologon.microsoftazuread-sso.com/`. Probably the reason is https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/e65a909267a727d78894eba3f54e48591dea8918/lib/msal-core/src/UserAgentApplication.ts#L691 condition returns `true`.

Could you advise me whether I can disable the calls to SSO?

## Minimal reproducible example
```js
const tokenRequest = { scopes: [ /* scopes go here */] };
var userAgentApplication = new UserAgentApplication({
    auth: {
      authority, clientId,
      navigateToLoginRequestUrl: false,
      postLogoutRedirectUri: baseUri,
      redirectUri: baseUri,
      validateAuthority: true
    },
    system: { loadFrameTimeout: 10000 },
    cache: { cacheLocation: 'localStorage', storeAuthStateInCookie: true }
  });
userAgentApplication.acquireTokenSilent(tokenRequest);
```

## Other information
- my application is the Office Add-in

**Comment by jasonnutter** [comment]
> not sure who does this call MSAL itself or https://login.microsoftonline.com/ page inside the MSAL's iframe

@streamcode9 I don't believe this is initiated by MSAL. In the dev tools, you can tell which script invoked the call in the "Initiator" column of the network tab.

**Comment by streamcode9** [comment]
@jasonnutter agree. It seems like something is going on inside the iframe and not connected with MSAL directly. But if I do like this:
```js
const serverAuthenticationRequest = {
  scopes,
  authority,
};
const account = userAgentApplication.getAccount();
let cachedToken = null;
try {
  cachedToken = userAgentApplication.getCachedToken(serverAuthenticationRequest, account);
} catch (err) { }
return cachedToken !== null
  ? userAgentApplication.acquireTokenSilent(tokenRequest)
  : userAgentApplication.loginPopup(tokenRequest);
```
I am able to avoid unnecessary calls to https://autologon.microsoftazuread-sso.com/ and as a result, avoid timeout exceptions.

Does this code make sense?

**Comment by jasonnutter** [comment]
> @jasonnutter agree. It seems like something is going on inside the iframe and not connected with MSAL directly. But if I do like this:
> 
> ```js
> const serverAuthenticationRequest = {
>   scopes,
>   authority,
> };
> const account = userAgentApplication.getAccount();
> let cachedToken = null;
> try {
>   cachedToken = userAgentApplication.getCachedToken(serverAuthenticationRequest, account);
> } catch (err) { }
> return cachedToken !== null
>   ? userAgentApplication.acquireTokenSilent(tokenRequest)
>   : userAgentApplication.loginPopup(tokenRequest);
> ```
> 
> I am able to avoid unnecessary calls to https://autologon.microsoftazuread-sso.com/ and as a result, avoid timeout exceptions.
> 
> Does this code make sense?

Interesting, are you observing timeouts when https://autologon.microsoftazuread-sso.com/ is invoked?

This endpoint is invoked as part of SSO on Windows machines, and is outside of MSAL's control.

As far as your code, I would not recommend calling `getCachedToken`, as it is technically an implementation detail and may be removed or not accessible in the future. If you are experiencing timeouts, you can increase the timeout duration via `system.loadFrameTimeout` (which defaults to `6000` milliseconds).

**Comment by streamcode9** [comment]
> Interesting, are you observing timeouts when https://autologon.microsoftazuread-sso.com/ is invoked?
> This endpoint is invoked as part of SSO on Windows machines, and is outside of MSAL's control.

@jasonnutter  yes, and I guess it is because of my application is Outlook Add-In. So basically it can be run inside the Outlook desktop client or via the browser in OWA. And calls to https://autologon.microsoftazuread-sso.com/ happened only when users run it from the Outlook desktop client.

> you can increase the timeout duration via system.loadFrameTimeout (which defaults to 6000 milliseconds).

I've tried to increase timeout but it still fails with 401, so I think I need to avoid these calls at all if there is no cached token. Is there a recommended way of doing it instead of `getCachedToken`?

**Comment by streamcode9** [comment]
> In the dev tools, you can tell which script invoked the call in the "Initiator" column of the network tab.

I see that initiator is an image, what does not make any sense, but I see the actual errors in the `console` tab:
![image](https://user-images.githubusercontent.com/1745268/83645697-10ee4080-a5b3-11ea-829c-bdce0aa03ea6.png)

**Comment by jasonnutter** [comment]
@streamcode9 Gotya, thanks for that information. Is that screenshot from the dev tools inside the Outlook desktop client? Or from the browser?

**Comment by jasonnutter** [comment]
> I've tried to increase timeout but it still fails with 401, so I think I need to avoid these calls at all if there is no cached token. Is there a recommended way of doing it instead of getCachedToken?

`acquireTokenSilent` is the API you should use to get a token without interaction. I think the fix here will be determining why the auto logon calls fail, as opposed to bypassing them (which may not be possible in your scenario).

**Comment by streamcode9** [comment]
@jasonnutter it is screenshot from https://www.microsoft.com/en-us/p/microsoft-edge-devtools-preview/9mzbfrmz0mnj?activetab=pivot:overviewtab when I debug outlook desktop client.

> I think the fix here will be determining why the auto logon calls fail, as opposed to bypassing them (which may not be possible in your scenario).

So the issue is on my side right? Could you advise me how I should debug it to find the problem? I see the two actors there:
1 - login.microsoft.com page inside MSAL iframe 
2 - autologon page

I can try pull code from login.microsoft.com and unuglify it, but I can’t debug or add console.log.

I doubt I can check something on autologon side.

I have also tried fiddler and wireshark but all the data are encrypted so it had zero output.

**Comment by jasonnutter** [comment]
> @jasonnutter it is screenshot from https://www.microsoft.com/en-us/p/microsoft-edge-devtools-preview/9mzbfrmz0mnj?activetab=pivot:overviewtab when I debug outlook desktop client.
> 
> > I think the fix here will be determining why the auto logon calls fail, as opposed to bypassing them (which may not be possible in your scenario).
> 
> So the issue is on my side right? Could you advise me how I should debug it to find the problem? I see the two actors there:
> 1 - login.microsoft.com page inside MSAL iframe
> 2 - autologon page
> 
> I can try pull code from login.microsoft.com and unuglify it, but I can’t debug or add console.log.
> 
> I doubt I can check something on autologon side.
> 
> I have also tried fiddler and wireshark but all the data are encrypted so it had zero output.

A couple things:

First, it looks like this can be controlled via [group policy](https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-sso), so you in theory you could disable it for your users.

Seconds, the work to get it working in the library will be done on our side, as the library should work as intended when seemless SSO is enabled.

**Comment by streamcode9** [comment]
@jasonnutter thank you for you help and fast reponse! Should I close the issue as we know all the answers now?

**Comment by jasonnutter** [comment]
@streamcode9 No problem. You can leave it open for now, as we'll investigate why timeouts are happening when this SSO flow is involved.
