### ISSUE TITLE
audience/resource for token acquisition

### ISSUE THREAD

**Issue by et1975** [AzureAD/microsoft-authentication-library-for-js#1722]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Trying to figure how to acquire a token for [AppConfiguration API]( https://github.com/Azure/AppConfiguration/blob/master/docs/REST/authentication/aad.md) and coming up short.

The API documentation is talking about requesting a `resource` and even though `AuthenticationParameters` has a field for it I get the error: 
> AADSTS901002: The 'resource' request parameter is not supported.

I tried using `scopes` for it, but it's not clear to me how to correctly setup `*.azconfig.io` as a scope - AppConfiguration is not listed as an API I can request permissions for.

**Comment by ranjanmicrosoft** [comment]
scope will be something like https://{myconfig}.azconfig.io/.default

in your resource map you'll do [ 'https://{myconfig}.azconfig.io/', [ 'https://{myconfig}.azconfig.io/.default' ]],

**Comment by et1975** [comment]
@ranjanmicrosoft  that's what I thought, but then my other problem:
```
ServerError: invalid_client: AADSTS650057: Invalid resource. The client has requested access to a resource which is not listed in the requested permissions in the client's application registration. Client app ID: 7e327720-2c2b-4516-a52b-d255e3834907(avs-capman-dev). Resource value from request: https://*.azconfig.io. Resource app ID: 35ffadb3-7fc1-497e-b61b-381d28e744cc. List of valid resources from app registration: 00000003-0000-0000-c000-000000000000.
```

How do I add the `*.azconfig.io` URI to my app definition? It has to be registered somewhere because the manifest takes a GUID, not the URI:
```
	"requiredResourceAccess": [
		{
			"resourceAppId": "00000003-0000-0000-c000-000000000000",
			"resourceAccess": [
				{
					"id": "e1fe6dd8-ba31-4d61-89e7-88639da4683d",
					"type": "Scope"
				}
			]
		}
	],
	"samlMetad
```

**Comment by jmckennon** [comment]
Closing this as it looks like it's being handled in https://github.com/Azure/AppConfiguration/issues/338.
