### ISSUE TITLE
Is it possible to have additional query parameters when calling openid-configuration endpoint?

### ISSUE THREAD

**Issue by LukaszFliegel** [AzureAD/microsoft-authentication-library-for-js#1727]
## Library
- [x] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
I'm trying to use msal with external AAD B2C. Policies they support have to be passed as a query parameter for authorization or v2.0/.well-known/openid-configuration endpoints. 
I have looked at https://docs.microsoft.com/en-us/samples/azure-samples/active-directory-b2c-javascript-msal-singlepageapp/active-directory-b2c-javascript-msal-singlepageapp/ where B2C with policies is being show. However, policies there are being sent as a part of the url, like that:
`https://fabrikamb2c.b2clogin.com/fabrikamb2c.onmicrosoft.com/b2c_1_susi/v2.0/.well-known/openid-configuration` where b2c_1_susi is the policy name

Which is fine, but as I wrote my B2C provider expects me to send it like that:
`https://<b2caddress>/<my_tenant>/v2.0/.well-known/openid-configuration?p=b2c_1_susi`
where policy b2c_1_susi is send as a query param.

I tried to follow the library code, and openId-configuration endpoint is being created like that:
```
protected get defaultOpenIdConfigurationEndpoint(): string {
        return '${this.canonicalAuthority}v2.0/.well-known/openid-configuration';
    }
```
There is no option to add this query param now or are they added somewhere else? The `AuthenticationParameters` class `have extraQueryParameters?: StringDict` but they seem to not be added to openid-configuration endpoint.

What am I missing?

**Comment by tnorling** [comment]
@LukaszFliegel We do not currently support customization of the `openid-configuration` call nor do we officially support IDPs outside of AAD and Azure B2C. Are you using some other B2C service, outside of Azure? A potential alternative solution; we will be releasing `msal@1.3.2` soon which will allow you to provide your endpoint metadata to skip the `openid-configuration` call, potentially solving this issue for you. See #1578. We can let you know when this is available.

**Comment by LukaszFliegel** [comment]
@tnorling thank you for the confirmation, it is what I thought.

The B2C IDP I'm calling is also a Azure B2C as far as I know, however somehow wrapped. I do not know implementation details, they are 3rd party for me. I see they implemented B2C policies in a way I described.
I will be looking for a release of `msal@1.3.2` thank you.

**Comment by tnorling** [comment]
@LukaszFliegel Could you share the documentation that states you need to provide the policy in the query param? This is not something I have seen before and I'd like to follow up with the B2C service team to find out if this should be a supported scenario.

**Comment by LukaszFliegel** [comment]
@tnorling the IDP I'm working with is a my client's internal project. I can't share anything regarding it. It is also a 3rd party for me so I have just some examples how to use this IDP. 

I wasn't aware, this is a unique scenario, some quick googling allowed me to think this is common since the policy sent as a "p" query param occur in few other code samples I saw.
Sorry I can't be more helpful.
