### ISSUE TITLE
processHash removed from msal-guard.service.ts and cannot find where is it now

### ISSUE THREAD

**Issue by neo-feng** [AzureAD/microsoft-authentication-library-for-js#1728]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.x.x` or `@azure/msal@1.0.0`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.3.1`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
processHash method was removed from file msal-guard.service.ts in this commit https://github.com/AzureAD/microsoft-authentication-library-for-js/commit/f634c5acd814d1d45aac6dbb77ac933ec1035120, but hash processing is required, could you please tell me which file the corresponding code was moved to? 

## why I asked this?
I encountered an issue which it try to route to #access_token when redirect back, this happens occasionally, and setting initialNavigation to disabled can fix it.

## findings
please read [root cause analysis](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1728#issuecomment-639207891) of my root cause analysis

**Comment by jasonnutter** [comment]
@neo-feng The processing of the response hash is now done [in the core library](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/b793ac74d413d0d27e9e9b1134c9702e90cff20f/lib/msal-core/src/UserAgentApplication.ts#L1069). You should not need to call this manually, as the library will invoke it for you. 

It sounds like you are using hash routing with your angular project?

**Comment by neo-feng** [comment]
@jasonnutter yes, we use hash routing, thanks for your reply. 

I did noticed method processCallback() in UserAgentApplication.ts, and traced its invoking chain, it is invoked in 2 methods, 
1. UserAgentApplication constructor
        -- handleRedirectAuthenticationResponse
        -- processCallBack

2. UserAgentApplication acquireTokenSilent 
        -- renewToken 
        -- loadIframeTimeout() 
        --WindowUtils.ts -- monitorWindowForHash 
        -- handleAuthenticationResponse 
        -- processCallBack 

none of them is linked with a envent listener as proessHash did, please let me know if I missed anything. 

I want to know how hash is processed when redirected back from iframe-acquireTokenSilent flow and that's the timing my access_token route errror was rasied.

**Comment by jasonnutter** [comment]
@neo-feng When you invoke acquireTokenSIlent, it will be called when the library detects a response in the iframe, as you noted. In Angular, this will emit `msal:acquireTokenSuccess` events.

At this point, I'm not sure I understand the problem you are having. Can you please clarify?

**Comment by jasonnutter** [comment]
Note, if your application modifies the hash, it may prevent MSAL from parsing the response, which will prevent the hash from being processed and returned.

**Comment by neo-feng** [comment]
@jasonnutter after the library detecting a response in the iframe I expect to see the code to remove hash from url (http://localhost:4200/#access_token=xxx ) like "window.location.hash = ", but I didn't, that's what I'm struggling to find. In the method processCallBack() you suggested above I can not find it, either.

Two console error logs printed in my issue,
 - Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'access_token'
 -  ClientAuthError: URL navigated to is https://login.microsoftonline.com/xxx/oauth2/xxx, Token renewal operation failed due to timeout.

I understand the second error which could be simply timeout due to slow network, but with these 2 errors shown together I'm wondering if it's the route error cause the timeout or the timeout cause the route error.  Especially by setting initialNavigation to 'disabled' can fix it, I believe there is something worth digging there. I kind feel it's a multi-thread issue, need to find the hash removing code to get more clue.

**Comment by jasonnutter** [comment]
@neo-feng Did you try adding a route for `access_token`? And yes, setting `initialNavigation` to `false` when your application is loaded inside an iframe may also help.

**Comment by neo-feng** [comment]
@jasonnutter No, we didn't adding any route to access_token. I believe I find the cause.
2 threads are running after creating iframe and waiting for redirecting back, 
 - 1. in main frame it keeps detecting iframe and close it when detecting its redirecting back, or timeout
 - 2. inside iframe, redirecting back will trigger route process to access_token

If 1nd thread acts faster, thing will be OK since iframe is killed before it tries to route.
But if 2nd thread is faster, my error reproduced, since access_token doesn't exist, the router will route to default or last successful route address where hash is removed and this will casue 1nd time out because it'll never detect hash.

And this explains why disable initialNavigation can fix the issue

**Comment by jasonnutter** [comment]
> @jasonnutter No, we didn't add any route to access_token. I believe I find the cause.
> 2 threads are running after creating iframe and waiting for redirecting back,
> 
> * 1- in main frame it keeps detecting iframe and close it when detecting its redirecting back(if hash exists in url), or timeout
> * 2- inside iframe, redirecting back will trigger route process to /access_token
> 
> If 1nd thread acts faster, thing will be OK since iframe is killed before it tries to route.
> But if 2nd thread is faster, my error reproduced, since access_token doesn't exist, route error reported and the router will change route to default or last successful address where hash is removed and this will casue 1nd time out because it'll never detect hash.
> 
> And this explains why disable initialNavigation can fix the issue

That makes sense, as if the page loaded in the hidden iframe manipulates the hash response in the iframe before the library has a chance to parse it, a timeout error can occur.

**Comment by neo-feng** [comment]
@jasonnutter Thanks, clear now. Do you have any clue why nobody else reported this problem? According to analysis above, it should be a common issue to everyone.

**Comment by jasonnutter** [comment]
> @jasonnutter Thanks, clear now. Do you have any clue why nobody else reported this problem? According to analysis above, it should be a common issue to everyone.

I have seen other customers with issues that are similar to this. 

Closing, as no further action in the library.
