### ISSUE TITLE
loginRedirect leads to a wrong discovery Url

### ISSUE THREAD

**Issue by Codeluck** [AzureAD/microsoft-authentication-library-for-js#1730]
## Library
- `@azure/msal-browser@2.0.0-beta2`

## Framework
React v16.8.6

## Description
After calling `msalObject.loginRedirect({ scopes: ['openid', 'email'] })` MSAL is sending a request to

`https://login.microsoftonline.com/common/discovery/instance?api-version=1.0&authorization_endpoint=https://mytenant.b2clogin.com/mytenant.onmicrosoft.com/b2c_1_signupin/oauth2/v2.0/authorize` 

which returns a 400 error.

I think this is a wrong url that's why server returns the error.

## MSAL Configuration

```js
const msalConfig: Configuration = {
    auth: {
      clientId: "xxx-xxx-xxx-xxx",
      authority: "https://mytenant.b2clogin.com/mytenant.onmicrosoft.com/B2C_1_SignUpIn",
      redirectUri: "http://localhost:3000"
    },
    cache: {
      cacheLocation: "localStorage",
      storeAuthStateInCookie: false
    },
    system: {
        tokenRenewalOffsetSeconds: 0,
        loadFrameTimeout: 9000
    }
  };
```

## Expected behavior
User should be redirected to an appropriate B2C flow page or signed in automatically

## Browsers/Environment
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by tnorling** [comment]
@Codeluck To use B2C you must set `knownAuthorities: ["mytenant.b2clogin.com"]` in your auth config. Let us know if you continue to have issues after this has been added

**Comment by Codeluck** [comment]
@tnorling I've added the authority you mentioned and it doesn't help.

When calling `loginRedirect()` it's still trying to access this url with HTTP code 400 result:

`https://login.microsoftonline.com/common/discovery/instance?api-version=1.0&authorization_endpoint=https://mytenant.b2clogin.com/mytenant.onmicrosoft.com/b2c_1_signupin/oauth2/v2.0/authorize`

**Comment by tnorling** [comment]
@Codeluck This is a bug with the current beta of msal-browser. A fix has already been merged to the dev branch but has not yet been released. Please track #1683 for updates.
