### ISSUE TITLE
VanillaJSTestApp2.0 sample, code question for getTokenRedirect 

### ISSUE THREAD

**Issue by jrmcdona** [AzureAD/microsoft-authentication-library-for-js#1731]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `@azure/msal-browser@2.x.x`

## Description
In the sample, in this file linked below.  Why on line 45 would you showWelcomeMessage after successful signIn then immediately do a getTokenRedirect request.  Seems out of place to me.

```
 if (myMSALObj.getAccount()) {
            console.log('id_token acquired at: ' + new Date().toString());
            showWelcomeMessage(myMSALObj.getAccount());
            **getTokenRedirect(loginRequest);**
```

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/VanillaJSTestApp2.0/app/ssoSilent/auth.js

**Comment by jmckennon** [comment]
Our naming convention could certainly be better here. `getTokenRedirect` is just a helper function that calls `acquireTokenSilent`, and then finally falls back to `acquireTokenRedirect`. The idea with this whole function is that we check for an active account, and if we have one, we show the welcome page. If not, we try `ssoSilent`. If we don't have the creds for `ssoSilent`, we still want to show the welcome page, but call `getTokenRedirect` (as a simple helper) to fall back to `acquireTokenSilent` and then the final fallback to `acquireTokenRedirect`.

Hopefully this answers your question, if not, I am happy to discuss further.

We're actively working on some of the problems with our samples, and they've came a long way in the past few months--though we still have plenty of work to do. We appreciate the feedback!

**Comment by jmckennon** [comment]
Closing this as I'm assuming this problem is resolved due to the inactivity.
