### ISSUE TITLE
How to get access token version 2 for Graph API

### ISSUE THREAD

**Issue by patatas** [AzureAD/microsoft-authentication-library-for-js#1733]
## Library
- [ ] `@azure/msal-angularjs@0.1.1

## Description
After authenticating the user in https://login.microsoftonline.com/{tenantID}/oauth2/v2.0/authorize?, our application is using 'msalAuthenticationService.acquireTokenSilent' to acquire access token that we will use to call MS Graph APIs. We're expecting to get access token ver. 2 however, per checking in token payload it has "ver": "1.0 value.

Is there are a way to configure MSAL to get access token v2 from Microsoft Identity Platform?

**Comment by jasonnutter** [comment]
@patatas `@azure/msal-angularjs` uses the v1 endpoints. If you want to use the v2 endpoints (and get v2 tokens), you need to upgrade to `@azure/msal-angular`.

**Comment by patatas** [comment]
@jasonnutter  Thank you for that information. Although I'm still wondering why @azure/msal-angularjs uses the v1 token endpoints and at the same time it uses the Microsoft identity platform endpoint for OAuth 2.0 authorize request.

**Comment by patatas** [comment]
@jasonnutter  How can we call MS Graph API if msal-angularjs uses the (Azure Active Directory) v1 endpoints?

Based from this documentation [MSAL AngularJS](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-angularjs), application can use this library to get an access to MS Graph API.
![image](https://user-images.githubusercontent.com/16602605/83709420-19955400-a651-11ea-9765-bbe120542d1a.png)

And from this document, [AuthN and AuthZ basics for Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth/auth-concepts) , we need to acquire token from (**Microsoft Identity Platform**) v2 endpoints when calling MS Graph. 

![image](https://user-images.githubusercontent.com/16602605/83709921-223a5a00-a652-11ea-8205-d9c73817863f.png)

**Comment by jasonnutter** [comment]
@patatas Sorry, I misread your original question. MSAL uses the v2 endpoint, which is capable of return v2 and v1 tokens. You can control which version is return  by editing the manifest and setting `accessTokenAcceptedVersion`: https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-app-manifest#manifest-reference

**Comment by patatas** [comment]
Great! that's exactly what I'm looking for. Thanks @jasonnutter
