### ISSUE TITLE
Getting an infrequent msal.error "Invalid_state" when authenticating, not sure why?

### ISSUE THREAD

**Issue by mcdonnell-john** [AzureAD/microsoft-authentication-library-for-js#1734]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [X] `@azure/msal-angular@0.x.x`
- [X] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

At present we have an front end application written with Angular 8, and we are using the Azure B2C Identity Experience Framework with a custom sign-in/sign-up policy when logging in.  

The issue we have is that in some cases, and often more frequently when in a private browser window in Firefox and Chrome, we get an error once the user attempts to login, and we see the following in our browsers local storage:

```
msal.error: Invalid_state
msal.error.description: Invalid_state.state: {GUID}
``` 

From inspecting our trace B2C logs, we can see no issue with the user's authentication via B2C, as these logs seem to show the same for a login that works and one that doesn't, so we suspect the issue is in the msal-angular/msal library (or at least how we use it)

Previously we had been using @azure/msal-angular@0.1.14, in an effort to see if this was causing the issue we have  used a branch to test the upgrade to @azure/msal-angular@1.0.0, but it didn't help resolve the issue.

In our angular app we have a LoginComponent:
```
@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {

  constructor(protected router: Router,
    protected authService: MsalService,
    protected broadcastService: BroadcastService,
    protected authorisationService : AuthorisationService,
    protected http: HttpClient) {

    broadcastService.subscribe("msal:loginSuccess", (payload) => {
      if (localStorage.getItem('redirect')) {
        this.router.navigate(['/login']);
        localStorage.clear();
      } 
      else{
        if(this.authorisationService.currentUser != null && this.http != null){
          this.isLoading = true;
           // removed logic which just retrieves the user's role and permissions
             this.router.navigate(['/dashboard']);
        }
      }
    });
  ngOnInit() {
  }
}
```
From what we can see the event 'msal:loginSuccess' is not being fired, and as a result the user is redirected back from the B2C login page to our login page again, and never is re-directed to the dashboard.

My question is around how can we diagnose this issue further, to get more information about the Invalidate_state we see in local storage?

**Comment by jmckennon** [comment]
Can you provide some information about the custom policy that you're using with B2C?

**Comment by mcdonnell-john** [comment]
Hi @jmckennon 

Yes, I can try too, bare in mind the developer who created all this on our project has since left, so if I miss something that you need to know please do not hesitate to ask :)

At a basic level, we are only using a customised SignUpSignIn flow, where we allow users to sign in via a username/password or via SSO from a Federated AAD.  The numbers of users we have at present mostly use the username/password flow so that's where we have seen this issue, although it might also have occurred via SSO, I just can't say for certain right now.

Our RelayingParty is defined as:
`<RelyingParty>
    <DefaultUserJourney ReferenceId="SignUpSignIn-RenamedForGitHub" />
    <UserJourneyBehaviors>
      <JourneyInsights TelemetryEngine="ApplicationInsights" InstrumentationKey="XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX" DeveloperMode="true" ClientEnabled="false" ServerEnabled="true" TelemetryVersion="1.0.0" />
      <ScriptExecution>Allow</ScriptExecution>
    </UserJourneyBehaviors>
    <TechnicalProfile Id="PolicyProfile">
      <DisplayName>PolicyProfile</DisplayName>
      <Protocol Name="OpenIdConnect" />
      <OutputClaims>
        <OutputClaim ClaimTypeReferenceId="displayName" />
        <OutputClaim ClaimTypeReferenceId="givenName" />
        <OutputClaim ClaimTypeReferenceId="surname" />
        <OutputClaim ClaimTypeReferenceId="email" />
        <OutputClaim ClaimTypeReferenceId="otherMails" />
        <OutputClaim ClaimTypeReferenceId="signInName" />
        <OutputClaim ClaimTypeReferenceId="newUser" />
        <OutputClaim ClaimTypeReferenceId="objectId" PartnerClaimType="sub" />
        <OutputClaim ClaimTypeReferenceId="identityProvider" />
        <OutputClaim ClaimTypeReferenceId="tenantId" AlwaysUseDefaultValue="true" DefaultValue="{Policy:TenantObjectId}" />
        <OutputClaim ClaimTypeReferenceId="userRoleId" />
        <OutputClaim ClaimTypeReferenceId="userRoleDescription" />
        <OutputClaim ClaimTypeReferenceId="userId" />
        <OutputClaim ClaimTypeReferenceId="activeStatusIndicator" />
      </OutputClaims>
      <SubjectNamingInfo ClaimType="sub" />
    </TechnicalProfile>
  </RelyingParty>`

And our UserJourney is defined as:
`<UserJourney Id="SignUpSignIn-RenamedForGitHub">
      <OrchestrationSteps>
        <OrchestrationStep Order="1" Type="CombinedSignInAndSignUp" ContentDefinitionReferenceId="api.signuporsignin">
          <ClaimsProviderSelections>
            <ClaimsProviderSelection TargetClaimsExchangeId="AdacapExchange" />
            <ClaimsProviderSelection ValidationClaimsExchangeId="LocalAccountSigninEmailExchange" />
          </ClaimsProviderSelections>
          <ClaimsExchanges>
            <ClaimsExchange Id="LocalAccountSigninEmailExchange" TechnicalProfileReferenceId="SelfAsserted-LocalAccountSignin-Email" />
          </ClaimsExchanges>
        </OrchestrationStep>
        
        <OrchestrationStep Order="2" Type="ClaimsExchange">
          <Preconditions>
            <Precondition Type="ClaimsExist" ExecuteActionsIf="true">
              <Value>objectId</Value>
              <Action>SkipThisOrchestrationStep</Action>
            </Precondition>
          </Preconditions>
          <ClaimsExchanges>
            <ClaimsExchange Id="AdacapExchange" TechnicalProfileReferenceId="AdacapProfile" />
            <ClaimsExchange Id="SignUpWithLogonEmailExchange" TechnicalProfileReferenceId="LocalAccountSignUpWithLogonEmail" />
          </ClaimsExchanges>
        </OrchestrationStep>
        
        <OrchestrationStep Order="3" Type="ClaimsExchange">
          <Preconditions>
            <Precondition Type="ClaimEquals" ExecuteActionsIf="true">
              <Value>authenticationSource</Value>
              <Value>localAccountAuthentication</Value>
              <Action>SkipThisOrchestrationStep</Action>
            </Precondition>
          </Preconditions>
          <ClaimsExchanges>
            <ClaimsExchange Id="AADUserReadUsingAlternativeSecurityId" TechnicalProfileReferenceId="AAD-UserReadUsingAlternativeSecurityId-NoError" />
          </ClaimsExchanges>
        </OrchestrationStep>
        
        <OrchestrationStep Order="4" Type="ClaimsExchange">
          <Preconditions>
            <Precondition Type="ClaimsExist" ExecuteActionsIf="true">
              <Value>objectId</Value>
              <Action>SkipThisOrchestrationStep</Action>
            </Precondition>
          </Preconditions>
          <ClaimsExchanges>
            <ClaimsExchange Id="SelfAsserted-Social" TechnicalProfileReferenceId="SelfAsserted-Social" />
          </ClaimsExchanges>
        </OrchestrationStep>
        <OrchestrationStep Order="5" Type="ClaimsExchange">
          <Preconditions>
            <Precondition Type="ClaimsExist" ExecuteActionsIf="true">
              <Value>objectId</Value>
              <Action>SkipThisOrchestrationStep</Action>
            </Precondition>
          </Preconditions>
          <ClaimsExchanges>
            <ClaimsExchange Id="AAD-UserReadUsingLocalAccountEmail-NoError" TechnicalProfileReferenceId="AAD-UserReadUsingLocalAccountEmail-NoError" />
          </ClaimsExchanges>
        </OrchestrationStep>
        <OrchestrationStep Order="6" Type="ClaimsExchange">
          <Preconditions>
            <Precondition Type="ClaimsExist" ExecuteActionsIf="true">
              <Value>objectId</Value>
              <Action>SkipThisOrchestrationStep</Action>
            </Precondition>
            <Precondition Type="ClaimsExist" ExecuteActionsIf="false">
              <Value>tempObjectId</Value>
              <Action>SkipThisOrchestrationStep</Action>
            </Precondition>
          </Preconditions>
          <ClaimsExchanges>
            <ClaimsExchange Id="SelfAsserted-UniqueUserMessage" TechnicalProfileReferenceId="SelfAsserted-UniqueUserMessage" />
          </ClaimsExchanges>
        </OrchestrationStep>
        <OrchestrationStep Order="7" Type="ClaimsExchange">
          <Preconditions>
            <Precondition Type="ClaimEquals" ExecuteActionsIf="true">
              <Value>authenticationSource</Value>
              <Value>socialIdpAuthentication</Value>
              <Action>SkipThisOrchestrationStep</Action>
            </Precondition>
          </Preconditions>
          <ClaimsExchanges>
            <ClaimsExchange Id="AADUserReadWithObjectId" TechnicalProfileReferenceId="AAD-UserReadUsingObjectId" />
          </ClaimsExchanges>
        </OrchestrationStep>
        <OrchestrationStep Order="8" Type="ClaimsExchange">
          <Preconditions>
            <Precondition Type="ClaimEquals" ExecuteActionsIf="false">
              <Value>authenticationSource</Value>
              <Value>localAccountAuthentication</Value>
              <Action>SkipThisOrchestrationStep</Action>
            </Precondition>
          </Preconditions>
          <ClaimsExchanges>
            <ClaimsExchange Id="GetLoyaltyData" TechnicalProfileReferenceId="AzureFunctions-WebHook2" />
          </ClaimsExchanges>
        </OrchestrationStep>
        <OrchestrationStep Order="9" Type="ClaimsExchange">
          <Preconditions>
            <Precondition Type="ClaimEquals" ExecuteActionsIf="true">
              <Value>authenticationSource</Value>
              <Value>localAccountAuthentication</Value>
              <Action>SkipThisOrchestrationStep</Action>
            </Precondition>
          </Preconditions>
          <ClaimsExchanges>
            <ClaimsExchange Id="GetLoyaltyData2" TechnicalProfileReferenceId="AzureFunctions-WebHook3" />
          </ClaimsExchanges>
        </OrchestrationStep>
        <OrchestrationStep Order="10" Type="SendClaims" CpimIssuerTechnicalProfileReferenceId="JwtIssuer" />
      </OrchestrationSteps>
      <ClientDefinition ReferenceId="DefaultWeb" />
    </UserJourney>`

AzureFunctions-WebHook2 and 3 are defined as:
`
<ClaimsProvider>
      <DisplayName>REST APIs</DisplayName>
      <TechnicalProfiles>
        <TechnicalProfile Id="AzureFunctions-WebHook2">
          <DisplayName>Azure Function Web Hook</DisplayName>
          <Protocol Name="Proprietary" Handler="Web.TPEngine.Providers.RestfulProvider, Web.TPEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />
          <Metadata>
            <Item Key="ServiceUrl">https://XXXXXXXXXXXXX.azurewebsites.net/api/GetUserRoleByEmail</Item>
            <Item Key="SendClaimsIn">Body</Item>
            <Item Key="AuthenticationType">ClientCertificate</Item>
            <Item Key="AllowInsecureAuthInProduction">true</Item>
          </Metadata>
          <CryptographicKeys>
            <Key Id="ClientCertificate" StorageReferenceId="B2C_1A_B2cRestClientCertificate" />
          </CryptographicKeys>
          <InputClaims>
            <InputClaim ClaimTypeReferenceId="signInNames.emailAddress" PartnerClaimType="email" />
          </InputClaims>
          <OutputClaims>
            <OutputClaim ClaimTypeReferenceId="userRoleId" PartnerClaimType="userRoleId" />
            <OutputClaim ClaimTypeReferenceId="userRoleDescription" PartnerClaimType="userRoleDescription" />
            <OutputClaim ClaimTypeReferenceId="userId" PartnerClaimType="userId" />
            <OutputClaim ClaimTypeReferenceId="activeStatusIndicator" PartnerClaimType="activeStatusIndicator" />
          </OutputClaims>
          <OutputClaimsTransformations>
            <OutputClaimsTransformation ReferenceId="CreateEmailFromSignInNames" />
          </OutputClaimsTransformations>
          <UseTechnicalProfileForSessionManagement ReferenceId="SM-Noop" />
        </TechnicalProfile>
      </TechnicalProfiles>
    </ClaimsProvider>
    <ClaimsProvider>
      <DisplayName>REST APIs</DisplayName>
      <TechnicalProfiles>
        <TechnicalProfile Id="AzureFunctions-WebHook3">
          <DisplayName>Azure Function Web Hook</DisplayName>
          <Protocol Name="Proprietary" Handler="Web.TPEngine.Providers.RestfulProvider, Web.TPEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />
          <Metadata>
            <Item Key="ServiceUrl">https://XXXXXXXXXXXXX.azurewebsites.net/api/GetUserRoleByEmail</Item>
            <Item Key="SendClaimsIn">Body</Item>
            <Item Key="AuthenticationType">ClientCertificate</Item>
            <Item Key="AllowInsecureAuthInProduction">true</Item>
          </Metadata>
          <CryptographicKeys>
            <Key Id="ClientCertificate" StorageReferenceId="B2C_1A_B2cRestClientCertificate" />
          </CryptographicKeys>
          <InputClaimsTransformations>
            <InputClaimsTransformation ReferenceId="CreateEmailFromOtherMails" />
          </InputClaimsTransformations>
          <InputClaims>
            <InputClaim ClaimTypeReferenceId="email" />
          </InputClaims>
          <OutputClaims>
            <OutputClaim ClaimTypeReferenceId="email" />
            <OutputClaim ClaimTypeReferenceId="userRoleId" PartnerClaimType="userRoleId" />
            <OutputClaim ClaimTypeReferenceId="userRoleDescription" PartnerClaimType="userRoleDescription" />
            <OutputClaim ClaimTypeReferenceId="userId" PartnerClaimType="userId" />
            <OutputClaim ClaimTypeReferenceId="activeStatusIndicator" PartnerClaimType="activeStatusIndicator" />
          </OutputClaims>
          
          <UseTechnicalProfileForSessionManagement ReferenceId="SM-Noop" />
        </TechnicalProfile>
      </TechnicalProfiles>
    </ClaimsProvider>`

There 2 are needed as they support retrieving the permissions we store in our database, by the users email address.  The email address is referenced differently based on if the user logs in via SSO, or username/password.

We also have ClaimProviders for Azure AD, etc..

**Comment by mcdonnell-john** [comment]
Hi apologies, 

Our MSAL config in the UI looks like:

```
{
    "clientID": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
    "authority": "https://login.microsoftonline.com/tfp/XXXXXXXXX.onmicrosoft.com/B2C_1A_signup_signin_XXX",
    "redirectUri": "https://localhost:44323/login",
    "validateAuthority": false,
    "cacheLocation": "localStorage",
    "postLogoutRedirectUri": "https://localhost:44323/login",
    "navigateToLoginRequestUrl": false,
    "popUp": true,
    "consentScopes": [
        "user_impersonation",
        "https://XXXXXXXXX.onmicrosoft.com/api/user_impersonation"
    ],
    "protectedResourceMap": [
        [
            "https://localhost:44380",
            [
                "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
            ]
        ]
    ],
    "unprotectedResources": [
        "/assets/"
    ],
    "loadFrameTimeout": 900000,
    "renewTokenBeforeExpires": 420000
}
```

**Comment by jmckennon** [comment]
Can you also confirm that you're on the latest version of msal, `msal@1.3.2`? There were some fixes to state changes in the past few versions.

**Comment by mcdonnell-john** [comment]
Hi @jmckennon we're still using 1.3.0 which is the altest version listed [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/releases).

We can switch to 1.3.2 and review if that's still working.  I'll get back to you to see if that worked

**Comment by mcdonnell-john** [comment]
Hi @jmckennon  we upgraded in a development branch to 1.3.2 and got the same behavior.

**Comment by jmckennon** [comment]
Okay, can you provide all of the msal logs in the browser that you're seeing in these cases, along with any other logs you may have?

**Comment by jmckennon** [comment]
Closing this as we're assuming it's no longer an issue due to inactivity. Please open another issue if you have further questions. Thanks!

**Comment by mcdonnell-john** [comment]
Hi @jmckennon Apologies I've been on holidays, I'll be back next week and will open another ticket
