### ISSUE TITLE
The access token has been obtained from wrong audience or resource 'https://batch.core.windows.net'. It should exactly match (including forward slash) with one of the allowed audiences 'https://batch.core.windows.net/'

### ISSUE THREAD

**Issue by gwh-cpnet** [AzureAD/microsoft-authentication-library-for-js#1735]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.3.1`

## Description

By `msal.acquireToken({ scopes: ['https://batch.core.windows.net/user_impersonation'] })`, I successfully got an access token with Payload including 

```json
    "aud": "https://management.azure.com"
```

But when I use this access token in the header for [Azure Batch API](https://docs.microsoft.com/en-us/rest/api/batchservice/#batch-account), a response with status 401 would return with payload:

```
{
  "odata.metadata":"https://cpproto1batch.eastus.batch.azure.com/$metadata#Microsoft.Azure.Batch.Protocol.Entities.Container.errors/@Element","code":"AuthenticationFailed","message":{
    "lang":"en-US","value":"Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly.\nRequestId:a2e5f376-b529-43d0-a0ab-f9bf55716c70\nTime:2020-06-03T18:21:40.2674126Z"
  },"values":[
    {
      "key":"AuthenticationErrorDetail","value":"The access token has been obtained from wrong audience or resource 'https://batch.core.windows.net'. It should exactly match (including forward slash) with one of the allowed audiences 'https://batch.core.windows.net/'"
    }
  ]
}
```

## Expected behavior

I have use the same approach: acquireToken({ scopes: ['https://management.azure.com/user_impersonation'] }), the access token it returened includes payload of 
```json
"aud": "https://management.azure.com",
```
no forward slash also, but it works fine when access API like `https://management.azure.com/subscriptions`. 

I believe Azure Batch API should behave the same. This issue could be more of an API backend issue. And it has be there for quite a while. Is there any work around msal can do? like define audience when acquire access token?

## Browsers/Environment
- [ ] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by gwh-cpnet** [comment]
I tried the `client credentials flow` too, without msal. The access token it return got no slash in `aud` too. And again it failed to call api like `https://{account-name}.{region-id}.batch.azure.com/pools`. 

Here could to be a wrong place to report this BUG. but where is the right place?

**Comment by jmckennon** [comment]
I double checked this and yeah, `msal` isn't affecting anything on that audience string, it looks like a bug from the API itself. A workaround would be to potentially code in the extra slash at the end of the audience string until this is fixed.

You can try to report the issue on both the [report an issue page](https://www.microsoft.com/en-us/msrc/faqs-report-an-issue) and the [batch feedback page](url). We'll pass this along internally as well. Thanks for the information!

**Comment by gwh-cpnet** [comment]
Thanks @jmckennon , I know it is more of an Azure batch API bug than an MSAL issue. 

I have already issued a support ticket. After 6 days, they supply a workaround to change the scope from `https://batch.core.windows.net/user_impersonation` to `https://batch.core.windows.net//.default` (yes. there are double slashes). 

This approach works for now. For someone who ran into the same problem, I hope this issue would supply some help. 

As a developer myself, I always prefer opening issues on github rather than mailing back and forth for days explaining I am not a idiot. Just wish all you official contributors could have confirmed the BUG sooner.
