### ISSUE TITLE
Add fromCache flag to MSAL.js

### ISSUE THREAD

**Issue by jasonnutter** [AzureAD/microsoft-authentication-library-for-js#1740]
Please follow the issue template below. 

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Upcoming Library
- [ ] `@azure/msal-node@1.x`

## Source
- [x] Internal (MSAL.js team)
- [ ] Customer request

## Description

In v1, the `AuthResponse` type includes `fromCache`, which indicates whether or not the response came from the cache or from the network.

## Priority

Medium

## Acceptance Criteria

1. Responses in v2 include the `fromCache` flag.

**Comment by pkanher617** [comment]
Added in #1770
