### ISSUE TITLE
URL navigated to is [B2Clogin_authorization_endpoint_URL], Token renewal operation failed due to timeout

### ISSUE THREAD

**Issue by alvipeo** [AzureAD/microsoft-authentication-library-for-js#1747]
**@azure/msal-angular@1.0.0, any browser, ONLY IN PRODUCTION (it works for https://localhost!)**

I have a dev set up for my angular 9 project and it works like a charm!

But then I deploy it to production and I get the following error:

>Refused to display '[https://mydonmain.com/app_start_route/#state=...&client_info=...&access_token=**[access_token]**&token_type=Bearer&expires_in=3600&scope=...' in a frame because it set 'X-Frame-Options' to 'deny'.

Log shows that:

>URL navigated to is [the_link_above], **Token renewal operation failed due to timeout.**
>errorCode: "token_renewal_error"

That same set up works in development with `https://localhost:4200` local URL. The only changes are ClientID and scope.

Also, I tried to use the standard interceptor `MsalInterceptor` but it does not work for some reason as it doesn't get an access token. So I use my own:
```
@Injectable()
export class AuthInterceptor implements HttpInterceptor {
  constructor(private msalSvc: MsalAuthService) {}

  intercept(
    req: HttpRequest<any>,
    next: HttpHandler
  ): Observable<HttpEvent<any>> {
    if (this.msalSvc) {
      return this.msalSvc.getGuestAccessToken().pipe(
        map((token) => {
          if (token) {
            const tokenValue = "Bearer " + token.accessToken;
            // console.log(`tokenValue: ${token.accessToken}`);
            return req.clone({ setHeaders: { Authorization: tokenValue } });
          }
          return req;
        }),
        mergeMap((request) => next.handle(request))
      );
    } else {
      throw Error("Auth Service is undefined: NO auth header!");
    }
  }
}
```

What's interesting - if I grab the access token from that Url and use it in Postman against my production app, IT WORKS! So this only happens on the msal library it seems.

Can you please help with this?

**Comment by tnorling** [comment]
@alvipeo What happens when you open the url from the error in a new window? The X-Frame Options Deny error happens when the page that is being loaded in the hidden iframe expects some sort of interaction, such as selecting an account or a "keep me signed in" box. Opening the page should give you more insight into why this is failing. Please also note that some B2C policies do not support silent token renewal. See [here](https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp/issues/49) for more info on that.

As for not getting an access token, can you share how you attempted to get the access token using the standard Interceptor? That will help us identify what the issue is.

In the future please do not delete the provided issue template, filling this out helps us identify and address your issue quicker. Thanks!

**Comment by alvipeo** [comment]
@tnorling when I open the url I see my app page.
Obviously, when I work locally there's no X-Frame-Options header at all (angular dev server).
Flow - SuSi v2.

here's my auth service:
```
@Injectable({ providedIn: "root" })
export class MsalAuthService {
  constructor(
    private broadcastService: BroadcastService,
    private authService: MsalService,
    private store: Store
  ) {
    // event listeners for authentication status
    this.broadcastService.subscribe("msal:loginSuccess", (success) => {
      // We need to reject id tokens that were not issued with the default sign-in policy.
      // "acr" claim in the token tells us what policy is used (NOTE: for new policies (v2.0), use "tfp" instead of "acr")
      // To learn more about b2c tokens, visit https://docs.microsoft.com/en-us/azure/active-directory-b2c/tokens-overview
      if (success.idToken.claims.tfp !== b2cPolicies.names.signUpSignIn) {
        window.alert(
          "Password has been reset successfully. \nPlease sign-in with your new password"
        );
        return this.authService.logout();
      }

      console.log(
        "login succeeded. id token acquired at: " + new Date().toString()
      );
      console.log(success);

      this.updateAuthStatus();
    });

    this.broadcastService.subscribe("msal:loginFailure", (error) => {
      console.log("login failed");
      console.log(error);

      // Check for forgot password error
      // Learn more about AAD error codes at https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-aadsts-error-codes
      if (error.errorMessage.indexOf("AADB2C90118") > -1) {
        // if (isIE) {
        //   this.authService.loginRedirect(b2cPolicies.authorities.resetPassword);
        // } else {
        //   this.authService.loginPopup(b2cPolicies.authorities.resetPassword);
        // }
        this.authService.loginRedirect(b2cPolicies.authorities.resetPassword);
      }
    });

    // redirect callback for redirect flow (IE)
    this.authService.handleRedirectCallback((authError, response) => {
      if (authError) {
        console.error("Redirect Error: ", authError.errorMessage);
        return;
      }

      console.log("Redirect Success: ", response);
    });

    if (!environment.production) {
      this.authService.setLogger(
        new Logger(
          (logLevel, message, piiEnabled) => {
            console.log("MSAL Logging: ", message);
          },
          {
            correlationId: CryptoUtils.createNewGuid(),
            piiLoggingEnabled: false,
          }
        )
      );
    }
  }

  login(isIE: boolean) {
    this.authService.loginRedirect();
    // check if login is not in progress
    // if (isIE) {
    //   this.authService.loginRedirect();
    // } else {
    //   this.authService.loginPopup();
    // }
  }

  logout() {
    this.store.dispatch(AuthActions.userIsLoggedOut());
    this.authService.logout();
  }

  tryLoginSilently() {
    this.updateAuthStatus();
  }

  getGuestAccessToken(): Observable<AuthResponse | null> {
    return this.getToken({
      scopes: apiConfig.b2cScopes,
    });
  }

  private getToken(
    tokenReq: AuthenticationParameters
  ): Observable<AuthResponse | null> {
    return from(
      this.authService.acquireTokenSilent({
        scopes: this.authService.getScopesForEndpoint(apiConfig.webApi),
      })
    ).pipe(
      tap((resp) => console.log("AuthResponse", resp)),
      catchError((err) => {
        if (err.name === "InteractionRequiredAuthError") {
          console.warn(`Couldn't acquire token silently`, err);
          this.authService.acquireTokenRedirect(tokenReq);
          return of(null);
        }
        return throwError(err);
      })
    );
  }

  private updateAuthStatus() {
    const acc = this.authService.getAccount();
    const accInfo = acc ? new IlgAccountInfo(acc) : undefined;
    this.store.dispatch(AuthActions.setAuthStatus({ accInfo }));
  }
}
```
I'm going to set X-Frame-Options to SAMEORIGIN got the app route and see if this helps... no other ideas for now.

**Comment by tnorling** [comment]
@alvipeo We generally recommend you set the `redirectUri` in `acquireTokenSilent` to a blank html page so that you aren't rendering your whole application again in the hidden iframe. This can especially cause issues if the hash containing the token gets cleared from the iframe before your top frame can extract it. Can you try that and see if that changes anything?

**Comment by alvipeo** [comment]
The issue is fixed setting X-Frame-Options to SAMEORIGIN ! Thanks, closing the issue for now.
