### ISSUE TITLE
Skip authentication and use debug token

### ISSUE THREAD

**Issue by tank104** [AzureAD/microsoft-authentication-library-for-js#1749]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [X] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
When running locally is there an easy way to skip authentication and use a debug token (likely not valid, but has the valid Claims ).
Ideally in config for debug would be to pass in the token and that gets pass through all the API calls same as MSAL library does now.

**Comment by jmckennon** [comment]
@tank104 are you basically looking to mock the API calls and return a dummy token? This is how many of our unit tests are ran, though the samples themselves are designed to be E2E and use the actual APIs.

**Comment by tank104** [comment]
Not entirely - I want to return a token that has valid claims (but expiration, and other values would be self generated), and have it attached as bearer token when I send requests to the microservices.

**Comment by sangonzal** [comment]
@tank104 If I'm understanding correctly, it sounds like you are trying to mock MSAL (Instead of getting a token from Azure AD, you'd like create your own token with your own claims)? 

You can't modify Azure AD tokens, as they are signed. You could always create and sign your own tokens, but then the microservices you describe would have to update their token validation logic (as the tokens are signed by you, not by Azure AD).

**Comment by tank104** [comment]
@sangonzal thats exactly right.  On all the microservices (azure functions) when we run in debug mode we just skip checking that they are signed by Azure AD - so they can be self signed)

**Comment by sangonzal** [comment]
@tank104 Makes sense. MSAL does not provide this functionality. A quick online search will return multiple third party libraries and tutorials on how to create JWTs that you can use for testing.

**Comment by tank104** [comment]
I can create the tokens fine.  What i want to do is be able to somehow get MSAL to use the token I create, and not do any auth.  So that it automatically adds the token to requets, etc.

**Comment by sangonzal** [comment]
@tank104 MSAL acquires tokens for you, but doesn't "use them". It won't automatically append them to any requests, that's up to you. It sounds like in your testing scenario, you would not use MSAL at all. (Instead of using MSAL to acquire a token, you just create your own)

**Comment by tank104** [comment]
Perhaps I have misunderstood then, but my understanding is that MSAL use http interceptors (?) to append the token onto requests that require it - I believe through the protectedResourceMap urls?

Are you saying that MSAL doesn't append token to any requests ever?  If so then I need to figure how I am doing it, because I am sure I don't add them on myself. (as that would be an easy solution)

**Comment by sangonzal** [comment]
Looks like question has been answered, closing issue. Feel free to open up in case anything else comes up.

**Comment by tank104** [comment]
I finally got round to implementing this, and just wanted to leave a guide for others:
I used A

so in app.module.ts I have this code:
```
  providers: [
    AngularStartupService,
    {
      provide: APP_INITIALIZER,
      useFactory: (ds: AngularStartupService) => () => {
        return ds.load();
      },
      deps: [AngularStartupService],
      multi: true,
    },
...
```
And my startup service looks like this:
```
import { Injectable } from "@angular/core";

@Injectable({
  providedIn: "root",
})
export class AngularStartupService {
  constructor() {}

  load() {
    //run at angular stratup
    localStorage.setItem("msal.9c...32f.client.info",".XXX");
    localStorage.setItem("msal.9c....32f.idtoken", "XXX");
    localStorage.setItem('{"authority":.....}', 'XXXX');
  }
}


```

**Comment by marinvirdol** [comment]
Hi @jmckennon! I was looking into the source code to see how to mock the API calls and return a dummy token. Unfortunately, I couldn't find it. Could you please point me to a piece of code that will help me? Thank you.
