### ISSUE TITLE
LogIn Popup doesn't close itself in an Iframe

### ISSUE THREAD

**Issue by pwombwa** [AzureAD/microsoft-authentication-library-for-js#175]
Am building an outlook addin which uses an Iframe to display it's contents. 

When authenticating to Microsoft Graph using MSAL, the user is able to enter their credentials but the login page doesn't close after but instead redirects the user the user to the redirect URL.

![image](https://user-images.githubusercontent.com/7061532/32442232-98965d8e-c2f2-11e7-9001-c75f7ccfd690.png)

**Code :** 
`let msalApp = new Msal.UserAgentApplication('app-id', null,null, { cacheLocation: 'localStorage', redirectUri: 'https://localhost:44330/home' });`

**Expectation:** 
After the user has authenticated themselves, the login popup should close and return the access token or fail.

**Comment by Alagaesia93** [comment]
Hello! 

I know this is a very old issue, but I have the same problem. I followed this guide https://docs.microsoft.com/it-it/azure/active-directory/develop/tutorial-v2-javascript-spa and everything works perfectly. 

When I bring the code to my application the popup does not close, after authentication. Is there anything I am missing?
