### ISSUE TITLE
Unexpected to Token during compile

### ISSUE THREAD

**Issue by demersjd** [AzureAD/microsoft-authentication-library-for-js#1750]
I am getting an unexpected toekn in the AuthProvider for REACT, I have added the files to my current app, to authenticate using MSAL

                               return redirect
                         ? msalApp.acquireTokenRedirect({
                             ...request,
                            ^

**Comment by jmckennon** [comment]
@demersjd To debug this, we'll need some more information. Can you give us the entire snippet of code, including the config you're passing into MSAL?

**Comment by jmckennon** [comment]
Closing this is we're assuming there's no longer a problem. Please open a new issue if you see further problems.
