### ISSUE TITLE
acquireTokenRedirect from nested application redirects user to parent application

### ISSUE THREAD

**Issue by jhaskett** [AzureAD/microsoft-authentication-library-for-js#1755]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.3.1`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Working on implementing MSAL.js 1.3.1 using redirects. Our local development setup has our website as a nested application in IIS ie: https://localhost/OurWeb. The loginRedirect call works fine and I can get my id token. When I then go to get my access token using the acquireTokenRedirect method, the redirect takes me back to https://localhost. 
I've moved from trying to implement this in my application to using and recreating it on the active-directory-javascript-graphapi-v2-quickstart sample application with the same result. In the getTokenRedirect method I commented out all but the line "return myMSALObj.acquireTokenRedirect(request)" for testing in Google Chrome although in FireFox it never gets the token silently

## Error Message
none

## MSAL Configuration
const msalConfig = {
  auth: {
    clientId: "xxxxxxxxxxxxxxxxxxxx",
    authority: "https://login.microsoftonline.com/xxxxxxxxxxxxxxxxxxxxxxxxxxxx/",
    redirectUri: "https://localhost/TestWeb/index.html",
  },
  cache: {
    cacheLocation: "localStorage", 
    storeAuthStateInCookie: false, 
}
};  

## Expected behavior
The acquireTokenRedirect redirects back to the redirectUri

## Browsers/Environment
- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by tnorling** [comment]
@jhaskett You can set `navigateToLoginRequestUrl:false` in your auth config. This is defaulted to `true` and will redirect you back to the `redirectUri` and then additionally redirect you back to the page that you were on when you initiated the request. Setting this to `false` will only redirect you to your `redirectUri`

**Comment by jhaskett** [comment]
@tnorling The biggest issue I see with that is the page we are initiating the login process from is a dynamically generated page (https://mysite/static/[dynamic id]/[another id]) and need that redirect back to the calling page.

**Comment by tnorling** [comment]
@jhaskett I think I misunderstood your original question. This is indeed a bug with `acquireTokenRedirect`. Thanks for pointing this out, we'll make sure it gets fixed.
