### ISSUE TITLE
Uncaught ReferenceError: Msal is not defined & bootbox

### ISSUE THREAD

**Issue by MtarantoOa** [AzureAD/microsoft-authentication-library-for-js#176]
Hello, 
Im trying to configure the msal service and library into my angular application. I run the npm install command for the msal library 

`npm install --save msal` and Install bootbox `npm i bootbox --save-dev`

Now I define on my msal.service.ts like this:
```

Import { Injectable } from '@angular/core';
declare var bootbox: any;
declare var Msal:any;
@Injectable()
export class MsalService {
    
    access_token: string;

    tenantConfig = {
        tenant: "fabrikamb2c.onmicrosoft.com",
        clientID: '90c0fe63-bcf2-44d5-8fb7-b8bbc0b29dc6',
        signUpSignInPolicy: "b2c_1_susi",
        b2cScopes: ["https://fabrikamb2c.onmicrosoft.com/demoapi/demo.read"]
    };
    
    // Configure the authority for Azure AD B2C

    authority = "https://login.microsoftonline.com/tfp/" + this.tenantConfig.tenant + "/" + this.tenantConfig.signUpSignInPolicy;

    /*
     * B2C SignIn SignUp Policy Configuration
     */
    clientApplication = new Msal.UserAgentApplication(
        this.tenantConfig.clientID, this.authority, 
        function (errorDesc: any, token: any, error: any, tokenType: any) {
            // Called after loginRedirect or acquireTokenPopup
        }
    );
```

My problem is that the Msal and bootbox get undefinded.
Im missing an import?
I take this as an example: [https://github.com/Azure-Samples/active-directory-b2c-javascript-angular2.4-spa](https://github.com/Azure-Samples/active-directory-b2c-javascript-angular2.4-spa) I noticed that under node_modules folder they have an out folder. But wen I install the library I dont get that 'out' folder.
So what I did just for testing is remove all the content that the msal folder have and put the out put folder from the example.
Then I add this:
`var Msal = require('../../node_modules/msal/out/msal')` and I got my Msal var declared and running. (after that discover the bootbox was also not defied).

What Im missing? Im doing wrong installation from npm?

Thanks for your help!

**Comment by rohitnarula7176** [comment]
@MtarantoOa Please use this sample for your reference. https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/devApps/ModuleSample/src/components/index.tsx . Please use npm install msal --save-dev and then you can import msal as follows:
```
import {UserAgentApplication} from "msal";
```
Please let me know if you still face issues.

**Comment by MtarantoOa** [comment]
@rohitnarula7176  Thanks for your help! worked as a charm!
