### ISSUE TITLE
Changes in acquireTokenRedirect cause ClientAuthError: User login is required. For silent calls, request must contain either sid or login_hint

### ISSUE THREAD

**Issue by MayankKT** [AzureAD/microsoft-authentication-library-for-js#1763]
Library

- [ ] `msal@^1.3.1` 

## Error
 When running the application to call the API, not getting the access token from acquireTokenSilent() hence in catch block calling the acquireTokenRedirect which is giving this error

## ClientAuthError: 
login is required. For silent calls, request must contain either sid or login_hint

## MSAL Configuration
`
```
let userAgentApplication = new UserAgentApplication({
    auth: {
        clientId: YOUR CLIET ID,
        redirectUri: REDIRECT URI default window.location.href,
        postLogoutRedirectUri: window.location.origin
    }
    cache: {
         cacheLocation: "localStorage"
        , storeAuthStateInCookie: true
    }
})
   authCallback(error:any, response:any):void {
    console.log('redirect hit ', response);
    //handle redirect response
  }
 
userAgentApplication.handleRedirectCallback(this.authCallback);

 let authenticationParameters = null ;
         authenticationParameters = {
         scopes: ['Your Scope'];
        , loginHint: this.userName // if not found then not added the loginHint
     }
 
 userAgentApplication.acquireTokenSilent(authenticationParameters).then(token => {
              // call the API 
            }).catch(err => {
                    console.log("Error occured while acquring token");
                    console.error("Error occured while acquring token=> " + err);
                    userAgentApplication.acquireTokenRedirect(authenticationParameters);
           });
```

Alternate when I use acquireTokenPopup() it open the blank popup window.

## Expected behavior

If user is not logged in then it should call the authCallback() which is passed to handleRedirectCallback() method
Or
when uses acquireTokenPopup() it should open the appropriate  login screen and after successful login I should get the access token in the success of the acquireTokenPopup promise.

If I use 
## Browsers/Environment
- [ ] Chrome
- [ ] IE

**Comment by MayankKT** [comment]
![issues1](https://user-images.githubusercontent.com/28943234/84022303-a74fa700-a9a3-11ea-8978-c484a2bb2202.png)

**Comment by tnorling** [comment]
@MayankKT There is a known issue with `acquireTokenRedirect` which would cause the callback to not be called. This will be fixed with the PR I linked to this issue. However, what I don't see in the code snippet you shared above is a login call. Before calling an `acquireToken` function you must call `loginRedirect` or `loginPopup`. This may solve the error you're getting

**Comment by MayankKT** [comment]
I am getting the error when calling the acquireTokenSilent() method getting following error : 

ClientAuthError: Cache error for scope [Scope]: The cache contains multiple tokens satisfying the requirements. Call AcquireToken again providing more requirements like authority.

**Comment by tnorling** [comment]
Tokens are cached with `authority`, `scopes`, `clientId` and an accountId. If you are trying to use multiple clientIds or authorities you need to provide that in the request to disambiguate between your cache entries. If this does not sound like your use case, you should take a look at local or session storage and see what's going on.
