### ISSUE TITLE
using a 3rd party IDP as a Azure Federated Provider

### ISSUE THREAD

**Issue by graphicsxp** [AzureAD/microsoft-authentication-library-for-js#1764]
I am currently using msal.js in my Angular application to authenticate users in Azure AD.

This is all working fine but my client wants to use a third-party identity provider for the authentication part while keeping Azure AD as an authorization provider.

My assumption is that I need to somehow configure federation in Azure AD. This should have no impact whatsoever in my web application and webapi and I should keep using msal.Js the same way.

Is this correct ? I have a reference to https://login.microsoftonline.com/tenantId in the msal factory. Would that need to be changed to use the federated idp url ?

**Comment by jmckennon** [comment]
`msal` only directly supports use with AAD, ADFS, and AAD B2C. If you want to use a 3rd party IDP instead of `msal`, only certain IDPs will be supported per these three methods. There is more info about that [here](https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-fed-compatibility), along with old compatibility lists. That compatibility will be up to the particular 3rd party IDP, so you will likely have to ask their developers for guidance.

**Comment by graphicsxp** [comment]
If you want to use a 3rd party IDP instead of msal
>This statement is confusing for me. MSAL is not an IDP, it is a library that can connect to an idp, right ?
In any case, if I manage to federate authentication in azure ad to use my third party IDP, will I need to make any changes to the way MSAL is used at the moment in my angular app?

**Comment by graphicsxp** [comment]
@jmckennon What I mean is that Azure should redirect to my client's IDP (built in-house). User signs-in as usual with her credentials. Upon successful login, the IDP redirects to Azure with an ID Token and Azure should then forward it to the web app, along with an Access Token if required.

I had asked this question on stackoverflow here: https://stackoverflow.com/questions/61990770/using-third-party-identity-provider-with-azure-ad-and-msal-js/61993117

And I just wanted to make sure that, as the answer mentions it, there should be no changed on the msal side of things. 
I'm more on frontend  and I have not enough experience with azure to give you more details on how the federation will work yet. Just trying to make sure there's no impact on what I have already put in place on the frontend.

**Comment by jmckennon** [comment]
No, there should be no needed changes with `msal`, as long as everything is configured properly. `msal` only makes requests to AAD on an app's behalf.

**Comment by jmckennon** [comment]
Closing this as there's no further action for us. If you have further questions please open another issue. Thanks!
