### ISSUE TITLE
Reading roles/groups from token

### ISSUE THREAD

**Issue by graphicsxp** [AzureAD/microsoft-authentication-library-for-js#1766]
## Library
- [ ] `@azure/msal-angular@1.x.x`

## Description
How to read roles or groups from token returned by msal ? 
I'm doing the following : `this.msalService.getAccount().idTokenClaims["roles"]; `  but in returns a string as the defined type by StringDict. However at runtime when I debug the application it is not a string, it is an array of strings (the roles), which is exactly what I need. 
But typescript won't compile if I try to cast it since StringDict returns a string. What is the correct way to get roles then ?

**Comment by derisen** [comment]
@graphicsxp could you take a look at the [sample here](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-dotnetcore-webapi-roles-groups/tree/derisen/chapter1). There, we demonstrate how to implement a `RoleGuard` service.

**Comment by graphicsxp** [comment]
Yes indeed. I still find it confusing. The sample uses the .include function of string to check if the role is part of the route data. However it only works because String and Array share an `include` method in their signature.
For example, what if we want to allow multiple roles to access a routes. Or just one role but assuming in the tokenClaims there are many roles. The include method wouldn't work there and we'd need to use  `find` or `filter`, which don't exist on the String type.
any insights ?

**Comment by graphicsxp** [comment]
ok, I will use one of these workarounds for the time being until the type definition is fixed.

Thank you !

**Comment by benc-uk** [comment]
Any update? Still seeing idTokenClaims as a StringDict with string values, making accessing the _array_ of roles quite tricky

**Comment by jasonnutter** [comment]
@benc-uk We haven't a chance to address this, but you can try the workaround above to get an array for those values.
