### ISSUE TITLE
Iframe issue when logging-in using twitter account or choosing from multiple google accounts

### ISSUE THREAD

**Issue by sushi4u** [AzureAD/microsoft-authentication-library-for-js#177]
I tried the VanillaJSTestApp-b2c. When I am login using twitter, there is an error: 

> Refused to display 'https://api.twitter.com/oauth/authenticate?oauth_token=....' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self' https://tweetdeck.twitter.com https://tdapi-staging.smf1.twitter.com https://tdapi-staging.atla.twitter.com https://tweetdeck.localhost.twitter.com". 

Also, when I have multiple google accounts logged-in and choose one of them for the app, it throws the following error: 

> Refused to display 'https://accounts.google.com/o/oauth2/auth?.....' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

In both the cases, id token is generated. While acquiring access_token (acquireTokenSilent()), these errors are thrown and the login popup is shown again. When I enter the same credentials this time, I get the access_token. This happens every time I am using twitter to login or choosing a google account from the list of logged-in google accounts.
When there is a single google account logged-in in my browser or when I enter google credential on the google login page, I get access_token with one login itself and no error is thrown.
Also, login using facebook gives access_token with single login itself.

**Comment by kanzelm3** [comment]
I am having the same issue.

**Comment by kanzelm3** [comment]
Looks like we aren't the only ones having this problem: https://stackoverflow.com/questions/47163384/msal-js-iframe-issue-with-twitter-and-while-choosing-from-multiple-google-accoun

**Comment by kanzelm3** [comment]
@rohitnarula7176 would you be able to give any insight to why this might be happening? I can take a stab at fixing it, but it would be helpful if you could at least point me in the right direction.

**Comment by sushi4u** [comment]
Hi @kanzelm3 
Sorry for the late reply. Here is what I did to overcome this issue, not sure if I should call it a solution.

Basically I made few changes in the msal.js file. Instead of fetching just the `id_token` first and then fetching the `access_token` using `acquireTokenRedirect`, I used `id_token_token` to fetch both on login itself in `loginRedirect` function. Also, you would need to change the function `processCallBack` so that it can send the new object containing id_token and access_token. There is one more change I did in function `saveTokenFromHash`.

Let me know if you need detailed explanation about the changes.

P.S. I made all these changes in msal.js v0.1.3 dated 2017-10-30 and it is working well for me, no problem in twitter or gmail multiple logins.

**Comment by kanzelm3** [comment]
It would be great if you could post a more detailed explanation, for me and any others that may be having the problem. I would also like to know what's causing it so that I could create a PR so that it's fixed for a future release.

**Comment by ChrisHaag** [comment]
Has this issue been fixed already?

I am having the same or a similar issue with the latest msal.js version available on npm which is 0.1.5.
I attached a sample app (angular 1.6) where you can reproduce the error as described in the readme.

Steps to reproduce (as described in the readme):
1. Open developer tools to see console output.
2. Login via facebook.
3. Acquire a token for both APIs in parallel.
4. There should instantly be an error like: _Load denied by X-Frame-Options: ..._

[AngularApp.zip](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/2008282/AngularApp.zip)

**Comment by vladkosarev** [comment]
Same issue with twitter here.

Refused to display [redacted] in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'

**Comment by Tovli** [comment]
Hi
I'm also having this issue with Google.
the acquireTokenSilent is generating this:
Refused to display 'https://accounts.google.com/o/oauth2/auth?client_id=xxxxx' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

**Comment by andy008** [comment]
I have the same issue @Tovli - did you solve?

**Comment by Tovli** [comment]
moved to auth0 :-(
