### ISSUE TITLE
Update from 1.3.1 => 1.3.2 throws TypeError: this.logger.isPiiLoggingEnabled is not a function

### ISSUE THREAD

**Issue by gvlot** [AzureAD/microsoft-authentication-library-for-js#1772]
Hello , 

In our application we use the Authentication integration as described in the sample project : "react-sample-app". Unfortunatley after updating of the package from version 1.3.1 -> 1.3.2 we are not able to Authenticate any more. 

Error : TypeError: this.logger.isPiiLoggingEnabled is not a function
Trigger Function : this._msalApp.loginPopup(GRAPH_REQUESTS.LOGIN)

Function where the error is being thrown : 
TelemetryManager.ts: 
createAndStartApiEvent(correlationId: string, apiEventIdentifier: API_EVENT_IDENTIFIER): ApiEvent {
        const apiEvent = new ApiEvent(correlationId, this.logger.isPiiLoggingEnabled(), apiEventIdentifier);
        this.startEvent(apiEvent);
        return apiEvent;
    }

P.s. just to throw it out : switching back to version 1.3.1 (   "msal": "1.3.1") will solve the issue. 

Please help/advise :-) 

Thanks in advance ,

**Comment by jasonnutter** [comment]
@gvlot The react-sample-app previously showed an incorrect implementation of `system.logger` (which was my fault, sorry about that). It has been updated to show proper usage (by instantiating the `Logger` class). Please update your usage  accordingly: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/react-sample-app/src/auth-utils.js#L76-L81

**Comment by gvlot** [comment]
Great, Thank you Jason .. it is working again !!
