### ISSUE TITLE
ClientAuthError: Token calls are blocked in hidden iframes

### ISSUE THREAD

**Issue by SreekamaleshAnnapragada** [AzureAD/microsoft-authentication-library-for-js#1774]
## Library
- [ ] `"@azure/msal-angular": "^1.0.0",`
- [ ] `"msal":^1.3.1`
Angular - 7.3.1

## Current behavior
Hi, We are seeing this issue 'vendor.js:81041 ERROR Error: Uncaught (in promise): ClientAuthError: Token calls are blocked in hidden iframes' and 'Token renewal operation failed due to timeout.' when we load our client application for the first time. The application is successfully loading when the developer tools window is opened. Currently we do not have any login screen. MSAL directly redirects the application to login screen and after successful login it is redirected back to the client url and loads the application from there. 

My Configuration: 
```
{
        auth: {
          clientId: '',
          authority: '',
          validateAuthority: true,
          redirectUri: '',
          navigateToLoginRequestUrl: true,
        },
        cache: {
          cacheLocation: 'localStorage',
          storeAuthStateInCookie: true,
        },
      },
      {
        consentScopes: ['user.read', 'openid', 'profile', environment.scopeApi],
        unprotectedResources: [],
        protectedResourceMap: [
          [environment.apiBaseUrl, [environment.scopeApi]],
          ['https://graph.microsoft.com/v1.0/me', ['user.read']],
        ],
      }
}
providers: [{ provide: HTTP_INTERCEPTORS, useClass: MsalInterceptor, multi: true }]
```
we have enabled msalguard for each routing url. 

##Expected Behavior
This application should be loaded successfully without any issues. 

Please let me know if I need to provide any further information. Thanks

**Comment by jmckennon** [comment]
@jasonnutter left a great response on #1194 which also addresses problems with hidden iframes. One of his proposed fixes will likely solve the issue. Let us know if you're still experiencing problems afterwards.

**Comment by jmckennon** [comment]
Closing this as we're assuming the issue has been resolved. Please open another ticket if you have further questions. Thanks!
