### ISSUE TITLE
wildcard for protectedResourceMap ?

### ISSUE THREAD

**Issue by gItSpLasHeR** [AzureAD/microsoft-authentication-library-for-js#1776]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
msal interceptor will attach the token to the requests which url & scope listed in "protectedResourceMap" as below format
`      protectedResourceMap: [
        ['https://graph.microsoft.com/v1.0/me', ['user.read']]
      ]`
since in my situation i got some urls with same scope.
so is it possible to use a wild card url in protectedResourceMap? 
which similar like this
`      protectedResourceMap: [
        ['https://*.microsoft.com/*', ['user.read']]
      ]`

or

`      protectedResourceMap: [
        ['*', ['user.read']]
      ]`

**Comment by jasonnutter** [comment]
@gItSpLasHeR This is reasonable ask, we'll track it and follow up when we have a chance to address, thanks!

**Comment by vitaliidasaev** [comment]
For those who looks about msal-angular MsalHttpInterceptor.  
I've made own implementation of MsalInterceptor to overcome issues with protectedResourceMap.  
This is my custom code block:

    // #region own workaround in order not to put every api endpoint url to settings
    if (!scopes && req.url.startsWith(this.settingsService.apiUrl)) {
      scopes = [this.auth.getCurrentConfiguration().auth.clientId];
    }
    // #endregion
    
    // If there are no scopes set for this request, do nothing.
    if (!scopes) {
      return next.handle(req);
    }
