### ISSUE TITLE
React sample not working 100% with b2clogin Authority

### ISSUE THREAD

**Issue by lorenzobrito** [AzureAD/microsoft-authentication-library-for-js#1778]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x ] "msal": "1.3.0",
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `"msal": "1.3.0",`.

## Framework
Reactjs, the code base is https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/react-sample-app
## Description
Working with b2clogin trows  The scope 'openid profile' provided in request must specify a resource, such as 'https://example.com/calendar.read'.

If i put in the scope, custom scope like https://cuartooscuro.onmicrosoft.com/3a23363c-33b8-429a-ae26-5776e30164c8/profile or https://graph.microsoft.com/openid. 
the aplication get cycle, after login page took me to the page but after one second it take me to login again and so on. But if just leave in the scopes 
"openid" and "profile",  just gave me the error The scope 'openid profile' provided in request must specify a resource, such as 'https://example.com/calendar.read'

## Error Message
 The scope 'openid profile' provided in request must specify a resource, such as 'https://example.com/calendar.read'.
## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

export const GRAPH_SCOPES = {
    OPENID: "openid",
    PROFILE: "profile",
    USER_READ: "User.Read",
    MAIL_READ: "Mail.Read"
};
export const msalApp = new UserAgentApplication({
    auth: {
        clientId: "valid client id",
        authority: "https://cuartooscuro.b2clogin.com/cuartooscuro.onmicrosoft.com/B2C_1_cuartooscuro",
        redirectUri: "http://localhost:3000/auth.html",
        validateAuthority: false,
        postLogoutRedirectUri: "http://localhost:3000",
        navigateToLoginRequestUrl: false
        
    },
    cache: {
        cacheLocation: "sessionStorage",
        storeAuthStateInCookie: isIE()
    },
    system: {
        navigateFrameWait: 500,
        logger: new Logger((logLevel, message) => {
            console.log(message);
        }, {
            level: LogLevel.Verbose,
            piiLoggingEnabled: true
        }),
        telemetry: {
            applicationName: "react-sample-app",
            applicationVersion: "1.0.0",
            telemetryEmitter: (events) => {
                console.log('Telemetry Events:', events);
            }
        }
    }
});
```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Browsers/Environment
- [ x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by tnorling** [comment]
@lorenzobrito This error occurs when you request an `access_token` for `openid` and `profile` in B2C because these are MS Graph Scopes and are not valid for B2C. If you need access to MS Graph you will need to do some additional steps on your app registration. You can follow the instructions [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/microsoft-graph-get-started?tabs=app-reg-ga). If you're just looking to renew an `id_token` try passing your `clientId` to your request instead.

**Comment by tnorling** [comment]
Closing as the original question has been answered. Let us know if you're still having issues.
