### ISSUE TITLE
How to acquire the access_token with the new scopes

### ISSUE THREAD

**Issue by streamcode9** [AzureAD/microsoft-authentication-library-for-js#1780]
## Library
- [x] `msal@1.3.1`

## Description
My application asks users to provide access for the next scopes - `"SCOPE1", "SCOPE2", "SCOPE3"`. Users will be asked to provide the [permissions ](https://docs.microsoft.com/en-us/azure/active-directory/develop/media/application-consent-experience/consent_prompt.png) once and other login requests will skip this step.
```js
const loginRequest = { scopes: ["SCOPE1", "SCOPE2",  "SCOPE3"] };
const token = msalInstance.loginPopup(loginRequest)
```

If I remove some scope from the list, users will NOT be asked to provide the permissions again and this [dialog](https://docs.microsoft.com/en-us/azure/active-directory/develop/media/application-consent-experience/consent_prompt.png) will be skipped.

I can force the showing of the permissions [dialog](https://docs.microsoft.com/en-us/azure/active-directory/develop/media/application-consent-experience/consent_prompt.png) like this and I will see the new list of the permissions:

```js
const loginRequest = {
  scopes: ["SCOPE1", "SCOPE2"],
  prompt: 'consent'
};
const token = msalInstance.loginPopup(loginRequest)
```

But in both cases the returned token contains the old list of scopes. And in the `Network` tab in Chrome Dev Tools I see the request to `https://login.microsoftonline.com/guid/oauth2/v2.o/athorize?response_type=token&scope=SCOPE1+SCOPE2` redirects to `https://mydomain/#access_token=SomeParameterss&scope=SCOPE1+SCOPE2+SCOPE3`

Is it possible to fix somehow or it is cached on server side (https://login.microsoftonline.com/)?

**Comment by tnorling** [comment]
@streamcode9 When acquiring tokens you will receive all scopes the user has ever consented to for that resource, not just the ones specifically requested. If one of the scopes requested has not yet been consented to the user will be prompted to consent. The only way to stop receiving a particular scope that had previously been consented, is for each user to revoke consent or remove the scope from the app registration, which would remove it for all users.

**Comment by streamcode9** [comment]
@tnorling thank you for the quick response! 

I've already removed the scope from the app registration but it seems like it has no effect.

Ho to revoke consent for each user? Is it possible to call some method of MSAL library?

**Comment by tnorling** [comment]
@streamcode9 This is not possible from MSAL. Each user will need to go [here](https://myapplications.microsoft.com/), find your app and revoke permissions. Let me know if this works. Alternatively, I haven't tried it myself but, it may be possible to revoke consent tenant-wide if you remove the entire resource from your app registration, save, and then add it back with just the scopes you want moving forward. Let me know if either of these work!

**Comment by tnorling** [comment]
Closing as the original question has been answered.

**Comment by streamcode9** [comment]
@tnorling sorry for the late response. "remove the scope from the app registration" this smees to work for me. Thanks again for your help!
