### ISSUE TITLE
How to logout without redirecting to microsoft logout page?

### ISSUE THREAD

**Issue by smnth90** [AzureAD/microsoft-authentication-library-for-js#1782]
## Library
- "@azure/msal-angular": "^1.0.0",

## Description
We are working on integrating the Microsoft Teams application with our application. I am using msal-angular library for authentication. I am able to get access token using this library. We have issue with logout feature/method.

msal-angular library has a logout method. When I am using this, this is redirecting to the "https://login.microsoftonline.com/{tenantId}/oauth2/v2.0/logout?post_logout_redirect_uri=http%3A%2F%2Flocalhost%3A3000%2F" by leaving our page. We have a requirement it should not leave the current page and logout process should happen in background or in hidden iframe html. Please help if any of you know any solution for our issue?

**Comment by jmckennon** [comment]
We don't currently support any sort of silent logouts, though we will consider this for the future as it's been asked a few times.

**Comment by smnth90** [comment]
Thank you @jmckennon. Is there any alternative to use until this feature gets added?

How much time it might takes to get this feature with this library?
