### ISSUE TITLE
getScopesForEndpoint always returnes null in msalinterceptor

### ISSUE THREAD

**Issue by negberts** [AzureAD/microsoft-authentication-library-for-js#1784]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [X] `msal@1.3.2` 
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [X] `@azure/msal-angular@1.0.0`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
Angular/ .NET framework

## Description
We have configured our protectedresourcemap like this:

```
const protectedResourceMap: [string, string[]][] = [
            ['http://localhost', [`http://ilionx.onmicrosoft.com/PimLocalServiceFabricApi/user_impersonation`]], // example
            ['https://graph.microsoft.com/v1.0/me', ['user.read']] // ms graph api - uses short scope names with no uri prefix
        ];

const msalAngularConfig: MsalAngularConfiguration =
        {
            popUp: !isIE,
            consentScopes: [
                'user.read',
                'openid',
                'profile',
            ],
            unprotectedResources: [],
            protectedResourceMap: protectedResourceMap,
            extraQueryParameters: {}
        };
```

But when we request an url like http://localhost/userprofile the scopes are null

I would have expected the scope http://ilionx.onmicrosoft.com/PimLocalServiceFabricApi/user_impersonation to be found.

What am I missing?

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Expected behavior
The correct scope should be returned because http://localhost is a subset of http://localhost/userprofile

## Browsers/Environment
- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by vitaliidasaev** [comment]
Agree, even wildcards will be great to have:
https://api.website.com/*

**Comment by jmckennon** [comment]
@negberts I've been unable to reproduce this in our samples/tests, everything seems to be working fine both inside and outside the interceptor. Can you provide some code examples/screenshots of the issues you're facing?

@vitaliidasaev this has been asked previously, and while it's not currently a feature, we will keep that feature-ask on our radar.

**Comment by negberts** [comment]
@jmckennon for some strange reason, it's working now… So I will close it...
