### ISSUE TITLE
[Angular] MSAL keeps the user logged in after closing the tab and loading page again in the new tab

### ISSUE THREAD

**Issue by anth-git** [AzureAD/microsoft-authentication-library-for-js#1785]
I recently upgraded msal-angular library from v0.1.4 to v1.0.0 but I'm encountering some strange issue in such scenario:

1. A user opens a Browser and signs into the application.
2. The user closes the Tab.
3. The user opens a new Tab and enters the URL address and loads the page.
4. **The Application is loaded and the user is signed in automatically without being redirected to the login page**.
5. Only after closing the entire Browser it works as expected - the user needs to sign in again.

In the previous version in 4th step the user was redirected to the login page and he had to sign in again by typing username and password.

I don't understand why is it happening since I'm using cacheLocation: sessionStorage:
```
cache: {
        cacheLocation: 'sessionStorage',
        storeAuthStateInCookie: false
      }
```

And this is login() method code:
```
  login(): Observable<LoggedOnUser> {
    const cfg = environment.loginConfig;
    return from(this.msalService.acquireTokenSilent({ scopes: cfg.angular.consentScopes, authority: cfg.msal.auth.authority })).pipe(
      switchMap(() => this.fetchLoggedOnUser()),
      catchError(err => {
        this.msalService.loginRedirect();
        return of(undefined);
      })
    );
  }
```

and package.json
```
"@azure/msal-angular": "1.0.0",
"msal": "^1.3.2",
```

How can I force it to always redirect to the login page if the Tab was closed?

**Comment by Adelaiten** [comment]
Having similar issue, user is logged out once browser is closed. Closing tab doesn't make user to log out.

**Comment by anth-git** [comment]
I've replicated the same behavior in angular9-sample-app, with these modifications:

```
// app.module.ts
function MSALConfigFactory(): Configuration {
  return {
    auth: {
      clientId: 'xxx',
      authority: "xxx",
      validateAuthority: true,
      redirectUri: "http://localhost:4200",
      postLogoutRedirectUri: "http://localhost:4200",
      navigateToLoginRequestUrl: true,
    },
    cache: {
      cacheLocation: "sessionStorage",
      storeAuthStateInCookie: false,
    },
  };
}

function MSALAngularConfigFactory(): MsalAngularConfiguration {
  return {
    popUp: false,
    consentScopes: ['xxx'],
    protectedResourceMap,
    extraQueryParameters: {}
  };
}

// app.component.ts
login() {
   this.authService.loginRedirect();
}
```

Could someone confirm whether it's an expected behavior or a bug, and how to get around this?

**Comment by jmckennon** [comment]
When you go to the page for the second time, can you see check to see if the tokens are still in the cache? Using the sample app with the changes you provided, this was not the case for me. There was neither an automatic login, nor information in the cache. Once I press the login button, it will automatically log me in without asking for credentials, as credentials stay active in AAD for 24 hours unless explicitly logged out. This is completely separate from the idea of local/session storage.

You can also try using `prompt=select_account` on the request to force logins.

**Comment by anth-git** [comment]
Sorry, perhaps my description was not clear enough. Using the example app, the behavior is as you described, that is a user is not automatically logged in when he visits the site for the second time, but there is no login/password screen once he presses the Login button. So lets call it semi-automatic login, but it's still not the desired behavior from my point of view.

But, indeed, passing `prompt=select_account` to `loginRedirect()` and `acquireTokenSilent()` methods did the trick!
