### ISSUE TITLE
AuthError.errorMessage - can it contain PII data?

### ISSUE THREAD

**Issue by thoo1** [AzureAD/microsoft-authentication-library-for-js#1792]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [X] `@azure/msal@1.3.0`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
There is an option in Logger class to exclude piiLogging. This is what we currently do.
In addition, we'd like to log as much info as possible from the thrown exceptions that are caught in `this.userAgentApp.handleRedirectCallback`.
However I'm not sure if AuthError can contain PII data, and is safe to log
Does AuthError.errorMessage contain PII data? Thanks

**Comment by jmckennon** [comment]
It is safe to log with `AuthError`, it won't ever contain PII.
