### ISSUE TITLE
How to avoid "Permission Required" confirmation for end user while access an application

### ISSUE THREAD

**Issue by vinusorout** [AzureAD/microsoft-authentication-library-for-js#1798]
When we login into any application, some time Microsoft redirect users to a "Permission Required" page, where user need to "Accept" this.
<img width="214" alt="PermissionRequired" src="https://user-images.githubusercontent.com/27411868/85006135-5f850880-b177-11ea-97bc-919d7d27d49f.PNG">

Is there any way to avoid this for end-users?

**Comment by jmckennon** [comment]
Unfortunately no, users generally will only have to accept permissions once per app unless there are major updates to the permissions that the app asks for.

**Comment by vinusorout** [comment]
> Unfortunately no, users generally will only have to accept permissions once per app unless there are major updates to the permissions that the app asks for.

Can we avoid this using "Admin Consent"?

https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/grant-admin-consent#:~:text=Sign%20in%20to%20the%20Azure,then%20click%20Grant%20admin%20consent.

**Comment by jmckennon** [comment]
@vinusorout Sorry, yes--I have confirmed this will work. I was actually unaware of this feature. The steps on that page outline the steps for enabling admin consent. Let us know if you have further questions about it.
