### ISSUE TITLE
When sign-out with MSAL.js, one is required to "choose which account to use", which is confusing

### ISSUE THREAD

**Issue by jmprieur** [AzureAD/microsoft-authentication-library-for-js#18]
**Repro steps**

1. Clone https://github.com/jmprieur/angular-msgraph-rest-sample-with-msaljs.git
2. Run the application (just follow the README.md of that repo. You don't need to register the application, though.
3. execute http://localhost:8080 in your favorite browser
4. Sign-in 
5. Sign-out

**Actual**
the pages announces "which account do you want to use?", which is not clear. It even appears if you have signed-in with only one identity.
I guess, that you are requested to choose the account to sign-out (?). This is confusing. I thought initially that it was trying to sign-in.
![image](https://cloud.githubusercontent.com/assets/13203188/25243598/dce254f8-25fd-11e7-9c44-b3644fdca164.png)

**Expected**
- If the browser/msal knows the identity I signed-in with, this should be preselected? 
- Or do we want to propose a separate experience where we can remove other identities? 
I'd like to discuss the experience, actually.

**Comment by jmprieur** [comment]
Update on this. This is because we want an app to sign-out a user without his acknowledgement (as this is signing-him off this identity for all pages in the browser). The UX needs work, though, and this work is planned.

**Comment by jmprieur** [comment]
Closing as duplicate.

**Comment by daniel-seitz** [comment]
@jmprieur can you add a link? I dont find another issue/solution for this.

**Comment by jelohipolitocruz** [comment]
@jmprieur Hi is this fix? Do you mind adding the duplicate link of the fix?

**Comment by jmprieur** [comment]
+ @negoe @DarylThayil @sameerag

**Comment by anton-kochev** [comment]
Hi, guys!
I faced the same issue when I need to choose an account while logout process. Do you have any workaround to skip this step? 
Thanks in advance

**Comment by nikbabchenko** [comment]
Hey Guys! Any update/clarifications on this?

**Comment by thibaultvdb-incerta** [comment]
Having the same issue, would be lovely to have a status for it :D
@jmprieur

**Comment by jmprieur** [comment]
@hpsin do you have an update?

**Comment by hpsin** [comment]
Nothing at this time.  We're investigating options for a new feature here that is secure and respects privacy.
