### ISSUE TITLE
authority parameter

### ISSUE THREAD

**Issue by MtarantoOa** [AzureAD/microsoft-authentication-library-for-js#180]
Hi, 
Sorry to bother you again. Im continue working with the JS library. And I was able to configure the code. Now the problem that I have is with the authority parameter (I think is that.)
What is happening is that I have some replay URL configured in azure. And when the loginPopup get called on that window I get redirected to one of those URL'S:

![pasted_image_at_2017_11_07_02_50_pm](https://user-images.githubusercontent.com/31453863/32551315-e0ec01e2-c46e-11e7-83ff-86ea9f4c7cfb.jpg)

 `https://localhost:60372/#error=redirect_uri_mismatch&error_description=AADB2C90006%3a+The+redirect+URI+%27http%3a%2f%2flocalhost%3a60372%2fdist%2f%27+provided+in+the+request+is+not+registered+for+the+client+id+%2722470c04-07e4-4ef0-a06d-0ccd9b31b557%27.%0d%0aCorrelation+ID%3a+e9887d06-985d-440b-953c-3c3e7e8e78eb%0d%0aTimestamp%3a+2017-11-08+13%3a19%3a13Z%0d%0a&state=4bd62682-4ae5-4357-bbdb-dfbbd877cb36`

I know that that error is becuse Im using local host and that is wrong. But I put a sever url and 

![capture](https://user-images.githubusercontent.com/31453863/32551300-d1fbd446-c46e-11e7-97e4-5d76e7bec5e9.PNG)

When I create a new instance of the UserAgentApplication and pass the authority as null. It works but send me to a login that does not have the providers and the URL is like this:

![image](https://user-images.githubusercontent.com/31453863/32551498-82043d06-c46f-11e7-96ab-4c32daa50e1f.png)

I see that in the url there is no /ftp/<tenant> so Im not sure if it is something that I did not configure properly on the library or in Azure.

When I browse the azure site I get this login:

![capture](https://user-images.githubusercontent.com/31453863/32551772-61083d7c-c470-11e7-8006-c64f6d69aa44.PNG)

```
`  tenantConfig = {
        tenant: "<myTenant>.onmicrosoft.com",
        clientID: '22470c04-07e4-4ef0-a06d-0ccd9b31b557',
        signUpSignInPolicy: "B2C_1_SiUpIn2",
        authority: "https://login.microsoftonline.com/tfp/<myTenant>.onmicrosoft.com/B2C_1_SiUpIn2",
        b2cScopes: ["https://<myTenant>.onmicrosoft.com/api/read.data"]
    };
    
    // Configure the authority for Azure AD B2C

    authority = "https://login.microsoftonline.com/tfp/" + this.tenantConfig.tenant + "/" + this.tenantConfig.signUpSignInPolicy;
    
    /*
     * B2C SignIn SignUp Policy Configuration
     */
    clientApplication = new UserAgentApplication(
        this.tenantConfig.clientID, null, 
        function (errorDesc: any, token: any, error: any, tokenType: any) {
            // Called after loginRedirect or acquireTokenPopup
        }
    );

    public login(): void {
        console.log(this.authority);
       var _this = this;
        this.clientApplication.loginPopup(this.tenantConfig.b2cScopes).then(function (idToken: any) {
            _this.clientApplication.acquireTokenSilent(_this.tenantConfig.b2cScopes).then(
                function (accessToken: any) {
                    _this.access_token = accessToken;
                }, function (error: any) {
                    _this.clientApplication.acquireTokenPopup(_this.tenantConfig.b2cScopes).then(
                        function (accessToken: any) {
                            _this.access_token = accessToken;
                        }, function (error: any) {
                            bootbox.alert("Error acquiring the popup:\n" + error);
                        });
                })
        }, function (error: any) {
            bootbox.alert("Error during login:\n" + error);
        });
    }`
```

Any help will be appreciated.

Thanks in advance.

Mauricio

**Comment by lovemaths** [comment]
@MtarantoOa The redirectURI you registered in Azure is 'https://localhost:60372', but in your app you are using 'http://localhost:60372/dist/'. Register 'http://localhost:60372/dist/' in Azure should solve the problem.

**Comment by rohitnarula7176** [comment]
@MtarantoOa Closing this issue. Please follow the solution mentioned above and reopen if it is still not resolved for you.
