### ISSUE TITLE
Delegated Access to graph.microsoft.com using Azure B2C with Multitenant AAD policy?

### ISSUE THREAD

**Issue by gavinbarron** [AzureAD/microsoft-authentication-library-for-js#1800]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x ] `msal@1.2.2` 
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Is it possible to allow users who have authenticated with a work or school account using Azure B2C as the identity provider for OAuth Implicit to consent for graph.microsoft.com scopes?

Scenario:

Azure B2C with a custom Multi tenant AAD policy in place.
The host AAD app registration is a very simple app and only asks for User.Read permission and redirects back to the B2C /oauth2/authresp URI
App registration in B2C lists the following delegated scopes:
https://graph.microsoft.com/Calendars.ReadWrite
https://graph.microsoft.com/offline_access
https://graph.microsoft.com/openid

During login only the open_id and profile scopes are requested and the application can get a id_token.

Trying to use .acquireTokenPopup results in AADB2C90205: This application does not have sufficient permissions against this web resource to perform the operation.

Is what I'm trying to do a supported scenario? Or do I need to have a side car app registration for the calendar integration I want to offer the users who have used organizational and MSA accounts?

**Comment by jmckennon** [comment]
This is a supported scenario, though there are a few extra steps involved. There's a whole slew of information outlined in [the Microsoft docs](https://docs.microsoft.com/en-us/azure/active-directory-b2c/microsoft-graph-get-started?tabs=app-reg-ga). You will need to configure a few permissions, along with also providing the resource on requests.

Please let us know if you have further questions.

**Comment by gavinbarron** [comment]
All of the examples in the linked docs, which I had previously read, are specifically about administrative scenarios where there is Admin consent flows or App only permission flows. 

I am specifically wanting to gain a token for delegated permissions which do not require admin consent using an implicit flow. Given this is for an open multitenant scenario and I don't want to have to go through the processes of admin consent. Are there any worked examples that I can refer to for this scenario?

**Comment by jmckennon** [comment]
Correct me if I'm wrong, but my understanding is that you want to completely avoid making that initial configuration altogether? Or is it that you want to avoid interactive consent per request?

**Comment by gavinbarron** [comment]
I'm fine with user interactive consent. I'd expect that this would happen once per user to gain the `https://graph.microsoft.com/Calendars.ReadWrite` scope as is normal outside of B2C scenarios  
What I can't have is a need to gain admin consent from the admin of the "home tenant" for the user at any stage

**Comment by jmckennon** [comment]
> What I can't have is a need to gain admin consent from the admin of the "home tenant" for the user **at any stage**

There's not a way to do this without granting admin/app consent at least once in the configuration in the portal. This can be done for all users of an app via [tenant-wide admin consent](https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/grant-admin-consent). So instead of the user facing this problem, it just becomes a part of creating an app registration, effectively.

**Comment by gavinbarron** [comment]
If I'm understanding you correctly, If I have users from N different AAD tenant signing in and attempting to use this functionality then I need to have an admin consent for each of those N tenants.

That seems like a massive gap from where I'm sitting.

In a regular multi tenant AAD application it's possible to get this scope with only end user consent. Is this a gap that is even on the roadmap to close?

**Comment by jmckennon** [comment]
Unfortunately, yes, that is the case. We understand the frustration of managing many tenants in that way. 

You can send feature requests and feedback for AAD directly on the [AAD feedback page](https://feedback.azure.com/forums/169401-azure-active-directory). I will bubble this up internally as well.

**Comment by gavinbarron** [comment]
Thanks for your help. Closing this as the question is answered

**Comment by gavinbarron** [comment]
Post script, it's worth noting that to deliver the user experience I need here I'll be having a web app with two instances of UserApplication, one for a B2C application that manages authentication for the site and one for an AAD Multitenant application to allow users to consent to the graph scope to allow us to deliver the user experience we want without putting roadblocks in the way
