### ISSUE TITLE
Are specific events tracked in MsalService, BroadcastService or UserAgentApplication?

### ISSUE THREAD

**Issue by spiricb** [AzureAD/microsoft-authentication-library-for-js#1806]
## Library
- [ ] `msal@1.3.0` and `@azure/msal@1.0.0`

Are there any internal events that can be tracked, listened to or otherwise used to see what the user is doing?
For example, if a user creates an account in b2c and they're redirected and logged into an angular app for the first time can this be tracked apart from a regular loginSuccess event?
I know this was possible with b2c and older version of msal but i don't see any mention of this in any sort of documentation or issue posts with msal 1.3.0 and angular-msal v1.

**Comment by jmckennon** [comment]
> Are there any internal events that can be tracked, listened to or otherwise used to see what the user is doing?

No, there isn't currently an event api for the core `msal` library (though as you stated `msal-angular` will emit events for `login` and `acquireToken`).

> For example, if a user creates an account in b2c and they're redirected and logged into an angular app for the first time can this be tracked apart from a regular loginSuccess event?

No, there is not a separate event for the first time when a user logs in. Can you clarify how you were doing this in previous versions?

**Comment by jmckennon** [comment]
Closing as I'm assuming this is no longer a problem due to inactivity. If you have further questions please open a new issue. Thanks!
