### ISSUE TITLE
Redirect of HTTPS really necessary?

### ISSUE THREAD

**Issue by negberts** [AzureAD/microsoft-authentication-library-for-js#1807]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [X] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [X] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
We are trying to move from ADAL to MSAL. But where ADAL accepted for http as redirect for our development environment, MSAL seems not. A https redirect is required, even tough it is an existing Azure AD application. Do we really have to buy certificates to get MSAL to work? Or is there some possibility to keep using the current application redirect urls?

Examples: 
> "How do I use MSAL with Vue.js"
> "How do I SSO between tabs?"
> "How do I use MSAL to protect my custom Web API?"
> "How can my app support multiple AAD tenants?"
> "When will my scenario be supported?"
> "When will this framework be supported"

**Comment by jmckennon** [comment]
Yes, `msal js` requires redirectUri to begin with https, except for `http://localhost` case. This is mandated by app registrations in the portal for security. We're sorry for the inconvenience.
