### ISSUE TITLE
Enhancement: Provide ability to focus the open login popup window

### ISSUE THREAD

**Issue by RobARichardson** [AzureAD/microsoft-authentication-library-for-js#181]
**Background**: 
When anonymous users access our application, they're presented with a landing page and a "Sign-In" button. When the user clicks said button, the app calls `UserAgentApplication.loginPopup` to begin the sign-in process.

**Issue**: 
On a few occasions, we've had complaints from users who have clicked this button, opened the popup window, but before signing in, they've shifted their attention to something else on their desktop and the popup window for authentication loses focus and/or gets lost among other windows.  When they return to the application to finish signing in, they attempt to click the "Sign-In" button on the landing page again which results in nothing happening since the popup window is already open (but potentially hidden) on their desktop.

**Enhancement:**
It would be great if calls to `UserAgentApplication.loginPopup` could refocus the popup window if one was already open, OR provide a built-in function to do this via `UserAgentApplication` programatically.  As a workaround for now, I was able to use `UserAgentApplication._openedWindows` to find the popup window and call `focus `on it, but my concern is that this could easily break as MSAL-JS changes in the future.

**Comment by rohitnarula7176** [comment]
@RobARichardson I don't think there is a way to achieve this without adding dom focus or click events which we cannot add to the library. If we call .focus() in the timer while the window is open, it still hides the popup window if you navigated away from it. The only way to do it programatically is going back to the main window and call UserAgentApplication._openedWindows[index].focus().

**Comment by RobARichardson** [comment]
@rohitnarula7176  I might be misunderstanding your response, but it sounds like you interpreted my original request as a suggestion that the library automatically detect when the user leaves the focus of the popup window and bring it back into focus. If so, I would agree; not something the library should do.

Instead, what I'm proposing is when repeated calls are made to UserAgentApplication.loginPopup, could the library automatically call .focus on an existing open popup window when UserAgentApplication._loginInProgress is true?  Something like the following:

```
loginPopup(scopes: Array<string>, extraQueryParameters?: string): Promise<string> {

    return new Promise<string>((resolve, reject) => {
      if (this._loginInProgress) {

        // Bring Open Popup Window Back Into Focus
         let openPopupWindow = this._openedWindows.find(window => !window.closed);
         if(openPopupWindow){
             openPopupWindow.focus();
          }

        reject(ErrorCodes.loginProgressError + ":" + ErrorDescription.loginProgressError);
        return;
      }
      ........
```
Either that, or provide a supported function as part of UserAgentApplication that any client application can call (like myself) to focus an open popup window should one exist and should this._loginInProgress be true.
