### ISSUE TITLE
Azure B2C Support for Microsoft Authentication Library for JavaScript v2.x (Preview)

### ISSUE THREAD

**Issue by toddfsnyder** [AzureAD/microsoft-authentication-library-for-js#1812]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

# Current Application State
Here are a few details about our current implementation. We have an Angular 9 application using msal 1.2 that authenticates with an Azure B2C Tenant. Once the user is authorized in B2C, we acquire a silent token to call secured WebAPIs that use custom Azure B2C scopes.

# Question
We are looking to better understand the road map for Microsoft Authentication Library for JavaScript v2.x (Preview) and if its currently supports Azure B2C, Specifically for SPAs that call back-end secured Web APIs using Azure B2C Scopes. 

Can we use the v2 (Preview) in this scenario? What is the timeline for v2 to be released?

**Comment by jmckennon** [comment]
This is not supported today, but it will be supported in the near future via #1811. We are planning to fully release 2.0 (currently in beta) in the next few weeks.

**Comment by toddfsnyder** [comment]
@jmckennon Thanks for the update and clarification on disabling CORS

**Comment by jmckennon** [comment]
Closing this as there's no further action for us here, and the bug will be tracked in #1795.
