### ISSUE TITLE
MSAL does not redirect user to login page after PW reset

### ISSUE THREAD

**Issue by FlyRocketDrones** [AzureAD/microsoft-authentication-library-for-js#1814]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
exact version is  "msal": "^1.3.2",
- [x] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
React

## Error Message
User does not get redirected after reseting their Passwords.

## Security
- [No ] Is this issue security related?

## Regression
- [No ] Did this behavior work before? 
Version:

## Reproduction steps
```js
 this.msalConfig = {
      auth: {
        clientId: process.env.REACT_APP_AZURE_APP_ID, //B2C Client ID
		...
        redirectUri: appLink,
		...
      },
      cache: {
        cacheLocation: "localStorage",
        storeAuthStateInCookie: false,
      },
    };

this.msalConfigPR = {
      auth: {
        clientId: process.env.REACT_APP_AZURE_APP_ID, //B2C Client ID
		...
        redirectUri: appLink,
		...
      },
      cache: {
        cacheLocation: "localStorage",
        storeAuthStateInCookie: false,
      },
    };
```

## Expected behavior
After user resets password, user gets redirected to homepage provided within the redirectUri

## Browsers/Environment
- [x] Chrome
- [x] Firefox
- [x] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jmckennon** [comment]
I was unable to reproduce this. Are you not seeing any redirect at all? Is it going to a different page than the one specified in the `redirectUri`?

**Comment by FlyRocketDrones** [comment]
So user enters password then it goes to the redirectUri, which is expected but it's still using the msalConfigPR therefore user sees a field to enter their email for password reset. It gets stuck in password reset flow once it enters there.

**Comment by jmckennon** [comment]
Are you using the B2C sample as a basis for implementing the forgot-your-password flow? This can be seen here: https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp/blob/master/JavaScriptSPA/authRedirect.js#L17

**Comment by jmckennon** [comment]
Closing as I'm assuming this is no longer a problem due to inactivity. If you have further questions please open a new issue. Thanks!
