### ISSUE TITLE
AADSTS16000

### ISSUE THREAD

**Issue by ranjanmicrosoft** [AzureAD/microsoft-authentication-library-for-js#1816]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.3.1` or `@azure/msal@1.x.x`
- [x] `@azure/msal-angular@1.0.0`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Description
Please see this link for additional info and solution. The same issue exists in MSAL and ADAL library.  
https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/580

The issue is specifically with MSA passthrough accounts with more than one account signed in. The token does not return enough information so it is ambiguous and the user can not log in. Using the data from the 'email' field to replace the 'upn' field when it is not present works as a solution in ADAL as suggested in the link, and I assume the same fix would work for MSAL. 

## Error Message
AADSTS16000

**Comment by jmckennon** [comment]
You can try using the `login_hint` flag and using the `preferred_username` as the value. More on that is outlined in the [Microsoft docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-implicit-grant-flow):
> Can be used to pre-fill the username/email address field of the sign in page for the user, if you know their username ahead of time. Often apps will use this parameter during re-authentication, having already extracted the username from a previous sign-in using the preferred_username claim.

**Comment by jmckennon** [comment]
Closing as I'm assuming this is no longer a problem due to inactivity. If you have further questions please open a new issue. Thanks!

**Comment by ranjanmicrosoft** [comment]
I'm not setting the login_hint myself, I'm using this authentication library which fails in this scenario. 
The code here lists checking how this behaves when the idtoken has no upn as a todo, which is the bug I think: 

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/266c6e98c861b5cfb124647c04d377ebf8412087/lib/msal-core/src/ServerRequestParameters.ts
