### ISSUE TITLE
React Native sample

### ISSUE THREAD

**Issue by aRajeshKumar** [AzureAD/microsoft-authentication-library-for-js#1817]
How do I use msal.js with React-Native ?

**Comment by jmckennon** [comment]
We currently do not support React-Native, though there are other native libraries for [Android](https://github.com/AzureAD/microsoft-authentication-library-for-android) and [Objective C](https://github.com/AzureAD/microsoft-authentication-library-for-objc).

React and React-Native is something we'll be looking at in the future, though we don't currently have a timeline on when that will be.

**Comment by aRajeshKumar** [comment]
Thanks @jmckennon ! Looking forward for it...

**Comment by jmckennon** [comment]
Closing as there's no further action for us. Thanks!
