### ISSUE TITLE
Token Cache Scope URL Encoding Problem

### ISSUE THREAD

**Issue by SebastianLindner** [AzureAD/microsoft-authentication-library-for-js#182]
I'm using Azure B2C for authentication. The scope I'm using looks like this:

scopes = ['https://mydirectory.onmicrosoft.com/myapp/read']
clientApplication = new UserAgentApplication(....)

To log in I'm using clientApplication.loginRedirect(scopes).

Now if I'm subsequently calling 

this.clientApplication.acquireTokenSilent(scopes);

and the token did not time out, yet, the token from the token chache should be returned.

However, every time new request is sent to Azure B2C to refresh the token, which is very inefficient.

I took a look at the code to retrieve the token from the cache and this is what I found.

UserAgentApplication.getCachedToken() {

	...

	//authority was passed in the API, filter by authority and scope
	for (var i = 0; i < tokenCacheItems.length; i++) {
		var cacheItem = tokenCacheItems[i];
		var cachedScopes = cacheItem.key.scopes.split(" ");

		if (Utils_1.Utils.containsScope(cachedScopes, scopes) && cacheItem.key.authority === authenticationRequest.authority) {
			filteredItems.push(cacheItem);
		}
	}
	
	...
	
	
}

Utils_1.Utils.containsScope(cachedScopes, scopes)

This comparison compares if the submitted scope can be found within the cache. In my example:

scopes = ['https://mydirectory.onmicrosoft.com/myapp/read']
cachedScopes = ['https%3a%2f%2fmydirectory.onmicrosoft.com%2fmyapp%2fread'] 

So the scopes in the cache seem to be url encoded and the current scope value is not.
Therefore the comparison can never find such a cached value.

All scopes that do not contain characters affected by url encoding seem to work fine.

Can someone confirm this? I'm currently on version 0.1.2

**Comment by rohitnarula7176** [comment]
@SebastianLindner The library decoded the token and saves it in the cache so you should not face this problem. Can you use the dev branch and confirm if it resolves your issue?

**Comment by zamzowd** [comment]
@rohitnarula7176 I'd like to corroborate what @SebastianLindner reported - the `Utils.deserialize(hash)` that you reference does not url decode the scope parameter value.  To use Sebastian's example, what gets saved to the cache has key.scopes value "https%3a%2f%2fmydirectory.onmicrosoft.com%2fmyapp%2fread" which does not match the requested scopes "https://mydirectory.onmicrosoft.com/myapp/read".

I am using msal.js 0.1.3.

**Comment by zamzowd** [comment]
What I described above isn't reproduced when I change the redirectUri to a different, simple page (the "Iframe+form+hash communication hack" trying to resolve acquireTokenSilent).  My login page is in an Angular application.
