### ISSUE TITLE
ADFS Authority Validation

### ISSUE THREAD

**Issue by sangonzal** [AzureAD/microsoft-authentication-library-for-js#1822]
## Library
- [x] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [x] `@azure/msal-node@1.x`

## Source
- [x] Internal (MSAL.js team)

## Description
Please read ADFS authority validation [spec](https://microsoft.sharepoint.com/:w:/r/teams/aad/devex/_layouts/15/Doc.aspx?sourcedoc=%7BF0EB0F6F-2B78-42A2-B44F-01DA1D6015E2%7D&file=ADFS%20Authority%20Validation%20-%20Original%20Spec.docx&action=default&mobileredirect=true&wdLOR=c22AE0924-0124-3D40-8BD4-435F36B291C7&cid=55F6763D-6E90-4588-A0AD-AF062981A3E4) and asses if MSALs implements this. 

Please see equivalent MSAL.NET [issue ](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1885)for a few more details.

**Comment by sameerag** [comment]
Closing this as "At this point no validation is expected from all MSALs" as per the ADFS team. If this feature if revamped in future, will track it with a new Issue.
