### ISSUE TITLE
Discrepancy between example in README and TypeScript definitions

### ISSUE THREAD

**Issue by pschaeflein** [AzureAD/microsoft-authentication-library-for-js#183]
In the example code in the README.md file passes `null` for the `authority` parameter. In the TypeScript definition (lib-commonjs/UserAgentApplication.d.ts), the parameter is declared as a string.

For projects in which strictNullChecks is set to true, this causes a build error.

**Comment by rohitnarula7176** [comment]
@pschaeflein Fixed in dev.
