### ISSUE TITLE
msal:loginSucces not broadcast unless handleRedirectCallback() is called

### ISSUE THREAD

**Issue by ChrisFulstow** [AzureAD/microsoft-authentication-library-for-js#1837]
## Library
- `@azure/msal-angular@1.0.0`
- `msal@1.3.2`

## Framework
- `Angular 9.1.11`

## Description
The `BroadcastService` doesn't trigger an `msal:loginSuccess` event after successful login via `loginRedirect()` unless `this.msal.handleRedirectCallback()` has been registered.

## Error Message
N/A

## Security
- Not security related

## Regression
- Unknown

## MSAL Configuration

```js
function MSALConfigFactory(): Configuration {
  return {
    auth: {
      clientId: environment.msal.clientId,
      authority: 'https://login.microsoftonline.com/common/',
      validateAuthority: true,
      redirectUri: environment.msal.redirectUri,
      postLogoutRedirectUri: environment.msal.postLogoutRedirectUri,
      navigateToLoginRequestUrl: true,
    },
    cache: {
      cacheLocation: 'localStorage',
      storeAuthStateInCookie: false,
    }
  };
}

function MSALAngularConfigFactory(): MsalAngularConfiguration {
  return {
    popUp: false,
    consentScopes: environment.msal.consentScopes,
    protectedResourceMap: environment.msal.protectedResourceMap as [string, string[]][]
  };
}
```

## Reproduction steps
Here I'd expect the BroadcastService to push a `msal:loginSuccess` event after a successful login completes.
```js
ngOnInit() {
  this.broadcast.subscribe('msal:loginSuccess', () => {
    console.log('msal:loginSuccess');
  });
}

login(): void {
  this.msal.loginRedirect();
}
```

However, the event isn't pushed unless I also register `handleRedirectCallback()`, then it works fine.
```js
ngOnInit() {
  this.msal.handleRedirectCallback(() => {});
  this.broadcast.subscribe('msal:loginSuccess', () => {
    console.log('msal:loginSuccess');
  });
}
```

## Expected behavior
This is ok, but the [1.0.0 changelog](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/693e7bc442784a69b926fa765bdf8bd26e534e36/lib/msal-angular/changelog.md#100) is perhaps misleading

> Applications using Redirect methods can optionally implement the handleRedirectCallback method

so ideally the `handleRedirectCallback()` step wouldn't be necessary to enable `msal:loginSuccess` for `loginRedirect()`, or the docs could highlight the prerequisite.

## Browsers/Environment
- Chrome

**Comment by jmckennon** [comment]
Thanks for the heads up here, I was able to reproduce this. Moving over to be fixed. For now, just implementing a simple `handleRedirectCallback` or using `loginPopup` can serve as a workaround, as you mentioned.

**Comment by rajithakolan** [comment]
"ClientAuthError: Invalid state" unable to get catch this error in 'handleRedirectCallback' in angular 9 . Please assist me, our project must support password reset feature also.
