### ISSUE TITLE
ReadMe and B2C tenant docs misaligned?

### ISSUE THREAD

**Issue by stephenstroud** [AzureAD/microsoft-authentication-library-for-js#1842]
Inside the Azure B2C Tenant it advises using the authorisation code flow, however, the docs say it's not yet supported. Which is correct? 

Github read me
![image](https://user-images.githubusercontent.com/7649287/85922574-61884f00-b87c-11ea-890e-0f02a424a7de.png)

Azure B2C tenant
![image](https://user-images.githubusercontent.com/7649287/85922584-782ea600-b87c-11ea-845a-77142fbe6fdf.png)

**Comment by tnorling** [comment]
@stephenstroud Thanks for pointing this out, we'll make sure the docs get updated. B2C is supported in msal-browser as of version 2.0.0-beta.3, however with one caveat. You'll need to disable CORS in your browser until #1795 gets resolved. Let me know if you have any issues getting this working

**Comment by technical-boy** [comment]
Closing. This will be taken care of as soon as B2C is fully supported.
