### ISSUE TITLE
Is it possible to use ADFS Federation Services authority url in place of login.microsoftonline.com

### ISSUE THREAD

**Issue by vinusorout** [AzureAD/microsoft-authentication-library-for-js#1848]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Earlier when we were using the adal.js library our applications used to redirect to our company ADFS authority(fs.mycompany.com) for login.

Now after MSAL.js upgrade, our applications started to redirect to login.microsoftonline.com because we specified 
"AZURE_AUTHORITY_ENDPOINT": "https://login.microsoftonline.com/tenant id" in our configurations.

Is it still possible to use Federation Service Authority in the Angular msal-angular library?

**Comment by tnorling** [comment]
@vinusorout ADFS support is coming, currently scheduled for the `msal@1.4.0` release, though we don't have a specific date yet. You can track issue #99 and PR #1668 for updates on when this feature will be available.
