### ISSUE TITLE
MsalInterceptor should handle InteractionRequiredAuthError

### ISSUE THREAD

**Issue by rpd10** [AzureAD/microsoft-authentication-library-for-js#1850]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
The default MsalInterceptor will attempt to acquire a token using `acquireTokenSilent`.  If the user has not yet consented for the given scope(s), the request will fail with `InteractionRequiredAuthError`.  As currently implemented, each Service would need to handle that error and use some boilerplate code to prompt for consent and re-fire the request.  I propose that the default interceptor could handle that error as a cross-cutting concern.

One concern is the limitation in IE11 around using popups.  If the interceptor were to use `acquireTokenRedirect`, that would kick the user out of the application and they could lose state.  Are there suggestions for how do deal with that?

I would be willing to contribute a PR for this, if it's something that you want to include in the project.

**Comment by jasonnutter** [comment]
@rpd10 This is something we want to address. Marking as a duplicate, as there is already an open issue: #1647

**Comment by jasonnutter** [comment]
> One concern is the limitation in IE11 around using popups. If the interceptor were to use acquireTokenRedirect, that would kick the user out of the application and they could lose state. Are there suggestions for how do deal with that?

Yes, using `acquireTokenRedirect` in this scenario would result in a loss of state. If your application needs to use a redirect operation, it will be your responsibility to leave a hint to yourself about how to resume when the redirect operation is complete. This could be done in the redirect request itself by providing a value for the `state` property that your application is able to parse and interpret to properly resume when the user completes interaction.

**Comment by jasonnutter** [comment]
This is now available in the MSAL Angular v2 alpha: https://github.com/AzureAD/microsoft-authentication-library-for-js/releases/tag/msal-angular-v2.0.0-alpha.0

Closing
