### ISSUE TITLE
recommended practice for distinguishing loginRequest from acquireToken on the basis of response object in MSAL 2.x

### ISSUE THREAD

**Issue by derisen** [AzureAD/microsoft-authentication-library-for-js#1853]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

Version: msal@2.0.0-beta.2
Sample: [ms-identity-javascript-v2 ](https://github.com/Azure-Samples/ms-identity-javascript-v2)

## Description
With msal@1.x it is possible to distinguish these by the `tokenType` property (among others). This no longer seems to be the case, as the response object returned from both request types are the essentially the same, including the `tokenType` ("Bearer").  What is the recommended practice for users to distinguish these in msal@2.x?

**Comment by pkanher617** [comment]
@derisen All responses in msal@2.x will contain an access token, and an id_token if `openid` and `profile` are sent. `tokenType` in v1 was used to distinguish between id_tokens and access_token responses, which is something one can still do by reviewing the values of the tokens returned. 

I'm not sure I see the reason to include tokenType, at least until support for Proof-of-possession has been added. It will always be "Bearer".
