### ISSUE TITLE
Expanding required scopes using acquireTokenRedirect causes null_or_empty_id_token error

### ISSUE THREAD

**Issue by daniel-chambers** [AzureAD/microsoft-authentication-library-for-js#1858]
## Library
- [x] `@azure/msal-browser@2.0.0-beta3`

## Framework
React

## Description
If I log in with one set of scopes using `loginRedirect` and then later use `acquireTokenSilent` (and then fall back to `acquireTokenRedirect`) with an expanded set of scopes, `handleRedirectPromise` fails when returning to the page with the new access token.

## Error Message
```
ClientAuthError: "null_or_empty_id_token: The idToken is null or empty. Please review the trace to determine the root cause. Raw ID Token Value: undefined"
    AuthError index.es.js:109
    ClientAuthError index.es.js:368
    createIdTokenNullOrEmptyError index.es.js:399
    IdToken index.es.js:2871
    generateAuthenticationResult index.es.js:3260
    acquireToken index.es.js:3393
    step index.es.js:74
    verb index.es.js:55
    fulfilled index.es.js:45
index.js:1
    e index.js:1
    tsx index.tsx:28
```

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
const msalConfig = {
  auth: {
    clientId: '<my client id>',
    redirectUri: window.location.origin + "/admin",
    authority: 'https://login.microsoftonline.com/<my tenant id>'
  }
}
```

## Reproduction steps
This the code that I put into a new create-react-app project just to spike out using this library. You could likely do it in a standard HTML page too.
```js
import React from 'react';
import ReactDOM from 'react-dom';
import './index.scss';
import App from './App';
import * as Msal from "@azure/msal-browser"

const msalConfig = {
  auth: {
    clientId: '<my client id>',
    redirectUri: window.location.origin + "/admin",
    authority: 'https://login.microsoftonline.com/<my tenant id>'
  }
}

const publicClientApplication = new Msal.PublicClientApplication(msalConfig);

publicClientApplication.handleRedirectPromise().then(tokenResponse =>{
  console.log("Token response")
  console.log(tokenResponse);
  if (tokenResponse === null && publicClientApplication.getAllAccounts() === null) {
    publicClientApplication.loginRedirect({
      scopes: [],
      redirectUri: msalConfig.auth.redirectUri,
    })
  }
}).catch(error => {
  console.log("handle redirect promise error")
  console.error(error);
});

console.log("All accounts:");
const accounts = publicClientApplication.getAllAccounts()
console.log(accounts);

function acquireToken() {
  const accounts = publicClientApplication.getAllAccounts()
  let request = { scopes: ["User.Read"], account: accounts[0], redirectUri: msalConfig.auth.redirectUri }
  publicClientApplication.acquireTokenSilent(request).then(tokenResponse => {
    console.log("Access token:")
    console.log(tokenResponse)
  }).catch(error => {
    if (error instanceof Msal.InteractionRequiredAuthError) {
      console.error("InteractionRequiredAuthError")
      return publicClientApplication.acquireTokenRedirect({ ...request })
    }
    console.log("Silent token error")
    console.error(error)
  })
}

ReactDOM.render(
  <React.StrictMode>
    <button onClick={() => acquireToken()}>Acquire Token</button>
    <App />
  </React.StrictMode>,
  document.getElementById('root')
);
```

The code attempts to log in immediately on page load, if it detects there is no user logged in. Note that it logs in with `scopes: []`. You will get bounced to Azure AD to consent to the default OpenID scopes.

You can then click the `Acquire Token` button which runs the `acquireToken` function. This tries to acquire a token with `scopes: ["User.Read"]` which is expanded from the original login request. You will be bounced back to Azure AD to consent to the new `User.Read` scope. Upon returning, you will experience the reported error from above.

Note that once you have consented to the expanded scopes, you cannot reproduce this issue until you revoke your consent by deleting the Azure AD App from your https://account.activedirectory.windowsazure.com/r#/applications page.

## Expected behavior
No error; `handleRedirectPromise` should be able to accept an access token without an id token.

## Browsers/Environment
- [x] Chrome
- [x] Firefox

**Comment by tnorling** [comment]
@daniel-chambers This should be fixed in `2.0.0-beta.4` please let us know if you are still having issues
