### ISSUE TITLE
How to deny to renew token id by acquireTokenSilent() and force it to redirect login

### ISSUE THREAD

**Issue by NhatDuy1407** [AzureAD/microsoft-authentication-library-for-js#1859]
## Library
- [ ] `@azure/msal-angular@1.0`

## Description
In my web app, I authenticate user login via azure b2c. I use `msal angular` with scope `openid` and add `MsalGuard`, `MsalInterceptor` to acquire token silently, then my token is expired, msal will renew token id. 
In my web api, I implement an api using Microsolft Graph .Net Client to deny renew token id silently, force it to redirect login.
I researched about `invalidateallrefreshtokens` function using Microsolft Graph .Net Client but not work.
Anyone can tell me how to deny renew token id silently, force it to redirect login? 

Thanks a lot.

**Comment by jmckennon** [comment]
`@azure/msal-angular` and `@azure/msal-core` implement the implicit flow, outlined by the OAuth spec, which does not use refresh tokens--this is probably why something like `invalidateAllRefreshTokens` does not work with our library.

You can try using `prompt: "login"` in your msal config to always force logins instead of silent ones.

**Comment by NhatDuy1407** [comment]
Thank you @jmckennon

**Comment by NhatDuy1407** [comment]
One more thing @jmckennon what happens if I use scope `offline_access` for msal config as following [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/implicit-flow-single-page-application)?

**Comment by jmckennon** [comment]
`offline_access` shouldn't have an effect at all when using `msal-angular`, as again, it uses the implicit flow which does not deal with refresh tokens.

**Comment by jmckennon** [comment]
Closing this as we're assuming the problem is solved due to inactivity. Please open a new issue if you gave further questions. Thanks!
