### ISSUE TITLE
How can I prevent login_hint to be added to URL when loginRedirect() is called?

### ISSUE THREAD

**Issue by lidermanrony** [AzureAD/microsoft-authentication-library-for-js#1865]
## Library
- [x] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
When my users want to switch to another account, I want to redirect them to the general AAD login page where they can enter their email and password.

The problem is that when i call `loginRedirect()`, msal.js always appends a login_hint that has the currently logged-in account.

This logic happens in `ServerRequestParameters.addHintParameters`.

Is there a way to make msal js _not_ provide the login hint?

A possible workaround is to use select_account instead of login in prompt, but I'm already using Me control for account switching from within my app (without needing to redirect), so I'm interested in redirecting to user/password entry rather than a "pick an account" UX.

**Comment by jmckennon** [comment]
You can try calling `logout()` before calling `loginRedirect()`, maybe with some logic to detect if there is a user currently logged in.

**Comment by lidermanrony** [comment]
Thanks, Is there any other option? logging out is kind of a last resort since it affects other browser tabs / applications

**Comment by lidermanrony** [comment]
Also I'm trying to implement the workaround (select_account), but the issue i'm encountering is that I'm not able to login with a personal account (only work or school).

here's the url i'm being redirected to:

`https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=id_token&scope=https%3A%2F%2Fhelp.kusto.windows.net%2F.default%20openid%20profile&client_id=f9818e52-50bd-463e-8932-a1650bd3fad2&redirect_uri=https%3A%2F%2Fdataexplorer.azure.com%2F&state=eyJpZCI6IjM1NTI0MjJhLTcwZTUtNDQ3Ni04Yjk2LWJhOWU1YWY0ODc2YSIsInRzIjoxNTkzNTg4MzE1LCJtZXRob2QiOiJyZWRpcmVjdEludGVyYWN0aW9uIn0%3D&nonce=e178522d-d6ec-4d49-9397-b21b9e7b6763&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=1.3.1&login_hint=user%40ronylkusto.onmicrosoft.com&prompt=select_account&client-request-id=917f6c48-df7b-4d19-882c-c013bfa6b75c&response_mode=fragment`

What should I change in MSAL configuration to allow for personal accounts? I was under the impression that common endpoint is for both personal and organizational accounts.

**Comment by lidermanrony** [comment]
OK i think i can use onRedirectNavigate to remove the login hint and redirece myself.
Is that a good solution?

**Comment by jmckennon** [comment]
Sorry for the delay over the long weekend. Yes--`onRedirectNavigate` allows you to control the redirect yourself, so your solution should definitely be possible. More info on that in #1691
