### ISSUE TITLE
Angular 9 sample error

### ISSUE THREAD

**Issue by sam-wheat** [AzureAD/microsoft-authentication-library-for-js#1867]
I am am able to log in however the consent dialog is not shown.  When I click the profile button I get:

> InteractionRequiredAuthError: Silent authentication was denied. The user must first sign in and if needed grant the client application access to the scope 'user.read openid profile'

All the required scopes are granted.
Can you guys please point me in the right direction?

Thanks.

**Comment by jasonnutter** [comment]
@sam-wheat Are you using the pre-configured client ID in the sample? Can you try [creating a new app registration](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-app-registration#redirect-uri-msaljs-10-with-implicit-flow) in your own tenant, and then try again?

**Comment by jasonnutter** [comment]
Also, in the future, please use one of the [pre-configured issue templates](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/new/choose), thanks!

**Comment by leaderanalytics** [comment]
Hey Jason thanks for the app registration document.  I am using my own client.  I tried using both auth flow and implicit flow:

Implicit flow disabled:

> ERROR Error: Uncaught (in promise): ServerError: The provided value for the input parameter 'response_type' is not valid. Expected values are the following: 'code', 'token', 'none'. 'id_token' is disabled for this app.
ServerError: The provided value for the input parameter 'response_type' is not valid. Expected values are the following: 'code', 'token', 'none'. 'id_token' is disabled for this app.

Implicit flow enabled:
> Error: Uncaught (in promise): InteractionRequiredAuthError: Silent authentication was denied. The user must first sign in and if needed grant the client application access to the scope 'user.read openid profile'.
InteractionRequiredAuthError: Silent authentication was denied. The user must first sign in and if needed grant the client application access to the scope 'user.read openid profile'.


Sorry about the template.  I just clicked the new issue button, Github didnt show the template list.

**Comment by jasonnutter** [comment]
Which version of MSAL.js are you using? v1 only supports the Implicit Flow, v2 supports the Auth Code Flow.

**Comment by sam-wheat** [comment]
I am using the sample as-is, only thing I changed is the clientID.  I found the versioning for the repo a little confusing: branch is for MSAL2 but the samples are for v1.  I was throwing darts looking for anything that might work.

**Comment by jasonnutter** [comment]
Ah sorry, misread your last comment.

Which browser are you using? And are third-party cookies enabled or disabled?

**Comment by leaderanalytics** [comment]
Using Chrome, third party cookies are enabled.  Same error when third party cookies are disabled.

**Comment by rfcdejong** [comment]
I have the same issue, in our client app getting an access token works fine, but then acquire token silent (msal guard code) it says interaction is required, even just after login. It used to work. So I downloaded the sample code which also results into the same error as topic owner, the content dialog is not shown anymore even with own client id. Something has changed on the microsoft identity provider endpoint, as it doesn't look like it is a msal issue.

**Comment by sam-wheat** [comment]
I am sorry to see this closed without an explanation of what was wrong, if anything.  These are the kinds of issues that cost us days.
