### ISSUE TITLE
How to prevent the popup after logout. Is there a silent logout available?

### ISSUE THREAD

**Issue by vajnorcan** [AzureAD/microsoft-authentication-library-for-js#1874]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
This is my config:
``` json
auth: {
          clientId: '<client>',
          authority: 'https://login.microsoftonline.com/<authority>',
          validateAuthority: true,
          redirectUri: environment.msalRedirectUri,
          // postLogoutRedirectUri: environment.msalRedirectUri,
          navigateToLoginRequestUrl: false
        },
        cache: {
          cacheLocation: 'localStorage',
          storeAuthStateInCookie: isIE, // set to true for IE 11
        },
```

After I invoke the **msalService.logout()** method, the popup shows with my application reloaded within it, while my original window display the page with the account to choose to sign out from (that one works as expected), but the popup is there with my whole other instance of the app loaded.

Not sure what to do to get this done right. I'd prefer to do this completely silently (even though I understand a reason for the account-to-sign-out choice) and handle the redirect myself.

Thank you

Examples: 
> "How do I use MSAL with Vue.js"
> "How do I SSO between tabs?"
> "How do I use MSAL to protect my custom Web API?"
> "How can my app support multiple AAD tenants?"
> "When will my scenario be supported?"
> "When will this framework be supported"

**Comment by jmckennon** [comment]
To clarify: are you specifically showing a popup for the logout/select account feature in your app? This functions as a redirect, which is why you're likely seeing this functionality.

Can you also provide the version of `angular` that you're using? Some things aren't quite working in angular10 yet.

**Comment by vajnorcan** [comment]
> To clarify: are you specifically showing a popup for the logout feature in your app?

I'm not aware of setting this anywhere hence the question. I've checked the config params and tried to change a few but none of it fixed the issue. If you could describe in more details on what you meant that might help me better to understand the behavior of the logout().

Version of Angular is 8,x. Ty.

**Comment by vajnorcan** [comment]
@jmckennon still unable to get this done properly. Any resources to (re)direct me (pun intended) to ? cheers

**Comment by jmckennon** [comment]
Sorry for the delay over the long weekend.

What I meant is if you had a Logout button in your app that was explicitly opening a popup, though that sounds like it's not the case.

Can you provide the related `msal` code so we can see your usage? I believe it would be a bug if logout was a popup by default.

The usage in our sample could also be useful if you haven't seen it: [the html](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/97e8cecc6cbe2a1209a52fc46b5767581bc138e1/samples/msal-angular-samples/angular8-sample-app/src/app/app.component.html#L9) and [the msal code](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/97e8cecc6cbe2a1209a52fc46b5767581bc138e1/samples/msal-angular-samples/angular9-sample-app/src/app/app.component.ts#L57).

**Comment by tnorling** [comment]
@vajnorcan Is it possible that your app is automatically triggering a login when it notices no-one is signed in? When you call the logout API, msal will clear your tokens from local/session storage then redirect to the page asking which account you would like to log out of. What this kind of sounds like is that your app is clearing storage, then noticing no-one is signed in, triggering `loginPopup` and then your top frame app has already navigated to the logout screen so is not able to close the popup, leaving you with another instance of your app in the popup. Does this sound like something that could be happening in your case? 

msal will not open a popup except when calling a popup function (`loginPopup` or `acquireTokenPopup` so I would try to debug and see what is opening that popup.

**Comment by vajnorcan** [comment]
Hi all, thanks for the suggestions. 
@jmckennon Just to clarify, I'm using the MsalSerivice to logout, and this popup has been introduced by MSAL as I haven't seen it before. 

@tnorling There is no automatic login mechanism as I'm moving out of the Msal guarded route to landing page /sites.

Below is my config and the screenshot. Please notice that on the screenshot, the /redirect page gets loaded in the popup, whereas the 'choose your account to logout' is in the parent window. Once I chose my account, it goes to /sites as expected. (the MG you see in the popup is the different OAuth2.0 login user so don't get confused)

`MsalModule.forRoot( {
        auth: {
          clientId: '<ClientId>',
          authority: 'https://login.microsoftonline.com/<authority>',
          validateAuthority: true,
          redirectUri: environment.msalRedirectUri,
          postLogoutRedirectUri: environment.msalRedirectUri,
          navigateToLoginRequestUrl: true,
        },
        cache: {
          cacheLocation: 'localStorage',
          storeAuthStateInCookie: isIE, // set to true for IE 11
        },
      },
      {
        popUp: true,
        // popUp: !isIE,
        consentScopes: [
          'user.read',
          'openid',
          'profile'
        ],
        unprotectedResources: ['https://www.microsoft.com/en-us/'],
        protectedResourceMap,
        extraQueryParameters: {}
      })`

![image](https://user-images.githubusercontent.com/5698035/86667139-ae1a1a00-c034-11ea-94bb-1b6fc1c3352c.png)

**Comment by vajnorcan** [comment]
Thanks all. I had a test piece of code from time when I was experimenting with the msal-guard.canActivate which was buried in the account component responsible for logging the user out. It works as expected.

My apologies.
