### ISSUE TITLE
How to obtain accessToken after loginSuccess event?

### ISSUE THREAD

**Issue by vajnorcan** [AzureAD/microsoft-authentication-library-for-js#1876]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
I can see that acquireTokenSuccess event in the broadcast service is carrying the **accessToken** property, but I don't know how to obtain one right after the **loginSuccess** event which is carrying only idToken. I don't intend to use the msal interceptors but I will need the access token for my api.

Thank you

Examples: 
> "How do I use MSAL with Vue.js"
> "How do I SSO between tabs?"
> "How do I use MSAL to protect my custom Web API?"
> "How can my app support multiple AAD tenants?"
> "When will my scenario be supported?"
> "When will this framework be supported"

**Comment by jasonnutter** [comment]
@vajnorcan You can use the `acquireTokenSilent` API to acquire an access token after logging in.

**Comment by vajnorcan** [comment]
thanks
