### ISSUE TITLE
[msal-node] Add a request type to make redirectURI mandatory for getAuthCodeUrl in ClientApplication.ts

### ISSUE THREAD

**Issue by pkanher617** [AzureAD/microsoft-authentication-library-for-js#1881]
Please follow the issue template below. 

## Upcoming Library
- [x] `@azure/msal-node@1.x`

## Source
- [x] Internal (MSAL.js team)
- [ ] Customer request

## Description
The current request object for the `getAuthCodeUrl()` function in msal-node ClientApplication.ts has an optional redirect URI that does not enforce the requirement in `msal-common`, which currently throws a runtime error if redirect_uri is not provided. We should move this to a typescript error by creating a new request object in node that enforces this as a required parameter.

## Priority

Low to Medium

## Acceptance Criteria

redirect URI is mandatory for the `msal-node` `getAuthCodeUrl()` function.

**Comment by jasonnutter** [comment]
@sameerag @pkanher617 Is this still an issue?
