### ISSUE TITLE
handleAuthenticationResponse fails when page was opened from different domain

### ISSUE THREAD

**Issue by jzet** [AzureAD/microsoft-authentication-library-for-js#189]
when using the library for authentication in a page, handleAuthenticationReponse fails when the page was opened from another domain.
This is the case because at line 1293, 

`    if (window.opener && window.opener.msal) {`

will cause an exception:
_Uncaught DOMException: Blocked a frame with origin "https://MYDOMAIN.com" from accessing a cross-origin frame._
and therefore stop execution.
This can easily be fixed by changing the order of the if conditions and checking for window.parent first:

```
    if (window.parent && window.parent.msal) {
        self = window.parent.msal;
    }
    else if (window.opener && window.opener.msal) {
      self = window.opener.msal;
      isPopup = true;
    }
```

**Comment by rohitnarula7176** [comment]
@jzet We cannot switch the order of the if conditions as window.parent is always true and we need to differentiate the case when this function is called from inside the popUp window. Can you provide a code repro of this issue.

**Comment by jzet** [comment]
it makes sense that window.parent is always true, in that case it might be necessary to check if window.opener has the same origin as the current window / catch the cross origin exception.
To reproduce the issue, simple embed the library in a page on domain A and try to retrieve a token not in a popup but via redirect. 
Access this page not directly but from another domain B via a link that either uses window.open or sets the target attribute (see https://developer.mozilla.org/en-US/docs/Web/API/Window/opener when window.opener is set)
If needed I can try to find the time and create a little page examplifying the issue.

**Comment by RonaldV** [comment]
I've got the same problem.

What about the next piece of code until you find a more elegant solution (I've already tested it.):

`
        function hasWindowOpenerMsal() {
            try {
                return window.opener && window.opener.msal;
            } catch (err) {
                // err = SecurityError: Blocked a frame with origin "[url]" from accessing a cross-origin frame.
                return false;
            }
        }

        if (hasWindowOpenerMsal()) {
            self = window.opener.msal;
            isPopup = true;
        }
        else if (window.parent && window.parent.msal) {
            self = window.parent.msal;
        }
        
        var requestInfo = self.getRequestInfo(hash);
        var token = null, tokenReceivedCallback = null, tokenType, saveToken = true;
        
        if (window.parent !== window && window.parent.callBackMappedToRenewStates[requestInfo.stateResponse]) {
            tokenReceivedCallback = window.parent.callBackMappedToRenewStates[requestInfo.stateResponse];
        }
        else if (hasWindowOpenerMsal() && window.opener.callBackMappedToRenewStates[requestInfo.stateResponse]) {
            tokenReceivedCallback = window.opener.callBackMappedToRenewStates[requestInfo.stateResponse];
        }
        else {
            tokenReceivedCallback = null;
            self._cacheStorage.setItem(Constants_1.Constants.urlHash, hash);
            saveToken = false;
        }
`

**Comment by ggirard07** [comment]
I think I am hitting the same issue, but it is really strange as I currently have the issue in an instance of chrome, but not in Firefox neither on another instance of chrome launched with another user profile...

**Comment by kanafghan** [comment]
I'm getting this issue after I have deployed my app, not while developing, e.g. on `http://localhost:4200`.

What is the status on this issue?

**Comment by rohitnarula7176** [comment]
@jzet @RonaldV @ggirard07 @kanafghan Thanks a lot for pointing out this issue @RonaldV for providing a workaround. I have fixed the issue in the dev branch. Can you all please use the dev branch and let me know if it resolves your issue.

**Comment by DmitryGonchar** [comment]
@rohitnarula7176 When will new patch version with this fix be published?

**Comment by mrman888** [comment]
It works for me. When can we expect a release?

**Comment by RonaldV** [comment]
It seems to be working, but I'm unable to test it on IE11. This is probably not related to this issue. I'm unable to see the errors in the developer console because it crashes on IE. So I've no idea what is happening. I'll create another issue for it.

**Comment by cheresier** [comment]
Just noticed a strange behavior. When I launch the application by typing in the URL directly into the browser's address bar, everything seems fine. However, this error (DOMException: Blocked a frame with origin "https://......" from accessing a cross-origin frame) seems to still be happening when the application is launched from http://myapps.microsoft.com (a portal where you can see all the web apps that you logged in to via Azure AD). Does anyone else see this behavior?

**Comment by DmitryGonchar** [comment]
@rohitnarula7176 We still see this error, although it is hard to reproduce, as it happens mainly in Edge and not on each occasion.

But looking at the code (`UserApplication.ts`), although you wrapped the first usage in try/catch, following ones do not have such check. According to our logs this line is the source of the error

```
else if (window.opener && window.opener.msal && window.opener.callBackMappedToRenewStates[requestInfo.stateResponse])
```


Proposal is to change to sth like
```
   /**
     * If object is not null - it also means that he have access to window.opener, it will not throw "Blocked a frame" error
     */
    private getWindowOpenerMsal() {
      try {
        return window.opener && window.opener.msal;
      }
      catch (err) {
        // err = SecurityError: Blocked a frame with origin "[url]" from accessing a cross-origin frame.
        return null;
      }
    }
```

and then replace all `window.opener.msal` or `window.opener && window.opener.msal` with its result

```
   ...
 private handleAuthenticationResponse(hash: string): void {
    ...
    var isPopup: boolean = false;
    var windowOpenerMsal = getWindowOpenerMsal(),
          isWindowOpenerMsal = windowOpenerMsal && windowOpenerMsal !== window.msal; // or should be named "isPopup" ?

    if (isWindowOpenerMsal) {
        self = windowOpenerMsal;
        isPopup = true;
    }
    ...
    else if (windowOpenerMsal && window.opener.callBackMappedToRenewStates[requestInfo.stateResponse]) {
        tokenReceivedCallback = window.opener.callBackMappedToRenewStates[requestInfo.stateResponse];
    }
    ...
  }
        
```

Names/code can be improved, but looks like it should fix this issue

**Comment by RonaldV** [comment]
This should already be handled by my code snippets above. I think they missed that part.
It is indeed difficult to reproduce. When testing this I didn't get the issue anymore. But we're not using the new version yet.

**Comment by dougmolineux** [comment]
@cheresier I am also experiencing this exact problem with version `"msal": "^0.1.5",`. Were you able to resolve your issue? I am also trying to come from myapps.microsoft.com but I get this error every time. Going directly to the URL works fine. I wonder if I should open a separate issue. Sorry for commenting on one that has been fixed already!

**Comment by cheresier** [comment]
@dougmolineux , nope, never heard from anyone with a resolution. The issue is still happening. Would love to see it resolved, so if you think opening a separate issue is the way to go, I'm all for it.

**Comment by dougmolineux** [comment]
@cheresier Thanks for the response! I opened one here: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/300
