### ISSUE TITLE
'ClientAuthError: Invalid state' when returning from a password reset policy in angular 9

### ISSUE THREAD

**Issue by rajithakolan** [AzureAD/microsoft-authentication-library-for-js#1890]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Browsers/Environment
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jo-arroyo** [comment]
Hi @rajithakolan, please take a look at the B2C sample below that shows you how to implement the password reset policy: [B2C Sample](https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp/blob/master/JavaScriptSPA/authRedirect.js)

If you have any further questions, please fill out the form above so we have the information needed to address your issue. Thanks!
