### ISSUE TITLE
Change password Functionality Angular 8

### ISSUE THREAD

**Issue by jacksonhart** [AzureAD/microsoft-authentication-library-for-js#1891]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [X ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Documentation location
- [ ] docs.microsoft.com
- [ ] MSAL.js Github Wiki
- [ ] README file
- [ ] Other (please fill in)
- [X ] Documentation does not exist

## Versions
msal 1.3.2 and msal angular 1.0

## Description
I'm sure i'm missing this but cannot find example of implementing a Change Password button in an Angular (8) app.

We had it working in msal-angular 0.1.4 using a custom msal-interceptor but now I get the 'Unexpected error in authentication: Hash does not contain state' error that I see a few people reporting when the password is changed or the request is cancelled causing a return to the app.

I can see the AADB2C90091 error in the browser URL.
The error appears to occur before I can reach any code in my app i.e. constructor of app.component.

I though instead of trying to debug the error (as other threads havent helped me) I would see how such a feature should be implemented in the first place.

**Comment by jo-arroyo** [comment]
Hi @jacksonhart, please take a look at the B2C sample below that shows you how to implement the password reset policy: [B2C Sample](https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp/blob/master/JavaScriptSPA/authRedirect.js)
Please feel free to reach out if you have any further questions. Thanks!

**Comment by derisen** [comment]
@jacksonhart alternatively, here's an [angular b2c sample](https://github.com/Azure-Samples/active-directory-b2c-javascript-angular-spa/blob/master/src/app/app.component.ts) that has the same functionality.

**Comment by jacksonhart** [comment]
thanks @derisen and @jo-arroyo.

I am looking at your example Derison as it is angular.

Unfortunately none of the events are triggered when I get the error.
I.e. msal:loginFailure, msal:loginSuccess or handleRedirectCallback().

In fact my app is not reached at all as it appears to break before the app.component constructor is executed.

We are using redirect login.
I have a 'change password' btn that just routes to the appropriate URL.

This is what is in the URL upon attempting to return to the app (when cancelling - different error after successfully changing pw obviously):
http://localhost:4200/#error=access_denied&error_description=AADB2C90091%3a+The+user+has+cancelled+entering+self-asserted+information.%0d%0aCorrelation+IDXXXTimestamp%XXX.

Along with the 'Unexpected error in authentication.: Hash does not contain state' error in the console.

So not sure what  I can change in my app considering it isnt being executed.

Let me know if theres any other details I can provide.

Our config:
```
MsalModule.forRoot({
      auth: {
        clientId: environment.clientID,
        authority: environment.authority,
        validateAuthority: false,
        redirectUri: 'http://localhost:4200/',
        postLogoutRedirectUri: environment.redirectUri,
        navigateToLoginRequestUrl: true,
      },
      cache: {
        cacheLocation: 'localStorage',
        storeAuthStateInCookie: true
      },
    },
    {
      popUp: false,
      consentScopes: environment.consentScopes,
      // unprotectedResources: ['https://www.microsoft.com/en-us/'],
      protectedResourceMap,
      extraQueryParameters: {}
    })
```

**Comment by derisen** [comment]
@jackshonhart can you clarify the issue a bit more please? Are you saying: 

1. The user authenticates to the app normally (using the redirect flow)
1. The app exposes a "reset password" button to call appropriate URL (can you please share the URL?)
3. When user cancels the password reset attempt, they get the error: 

`http://localhost:4200/#error=access_denied&error_description=AADB2C90091%3a+The+user+has+cancelled+entering+self-asserted+information.%0d%0aCorrelation+IDXXXTimestamp%XXX.` (why is this unexpected?)

You said: 

> Unfortunately none of the events are triggered when I get the error.
> I.e. msal:loginFailure, msal:loginSuccess or handleRedirectCallback().

What exactly the error you mention here. If you are calling the password reset manually, it is expected that the logic in the broadcasts (or `handleRedirectCallback()`) is not triggering.

Now the way this sample handles the password reset flow is as follows:

1. The sample has two user flows, **sign-up/sign-in** and **password reset**. These user flows rely on different **authority strings**
1. On login screen (as part of **sign-up/sign-in** user flow), when user clicks on password reset, B2C throws the `AADB2C90118 `error, and MSAL treats it as a failed login attempt, which then triggers the **authority switch logic**.
1. The app switches to **password reset** user flow and the associated authority string. It then attempts to login again, which takes the user to the password reset screen. Once this is done, the user will back to the app, but the app will carry out an automatic sign-out (this is because you cannot use the id_token you've obtained from password reset authority). 
1. The user sign-ins again with their new password using the standard sign-in/sign-up user flow.

**Comment by jacksonhart** [comment]
Thanks for the reply @derisen .

Yes those steps are correct.

The URL is https://XX.b2clogin.com/XX.onmicrosoft.com/oauth2/v2.0/authorize?p=B2C_1_SSPR&client_id='XX'&nonce=defaultNonce&redirect_uri=httpsXX.azurewebsites.net&scope=openid&response_type=id_token&prompt=login'

The error in the URL on return is not unexpected. In msal-angular 0.X we just ignored that error.

Now in 1.0 there is the additional  'Unexpected error in authentication.: Hash does not contain state' error in the console which appears to break everything. Not even deleting all cookies and everything in local storage and refreshing the page will help. 
The tab must be closed or interestingly, going 'back' in the browser also works.

If we were to change to this authority switch logic instead of manually going to a URL - looks like this involves setting up this pw-reset 'authority' in azure? Do you have any details on that? I will have to speak to someone else on my team as I dont currently have access to the B2C config in Azure.

Thanks,
Jackson.

**Comment by derisen** [comment]
Hmm, I wonder how would you even initiate password reset without setting up the flow first. The URL you shared has the policy string `B2C_1_SSPR` -what is this policy? At any rate, here's the [tutorial to set up user flows](https://docs.microsoft.com/en-us/azure/active-directory-b2c/tutorial-create-user-flows). Password reset is one of the defaults, so its quite easy to set it up.

**Comment by jacksonhart** [comment]
Hi @derisen,

ok so that must be our pw-reset policy.
I changed it so the authority is switched and then loginRedirect is called instead of manually routing to the URl but exactly the same thing happens.

That is, it takes you to the reset page, but if you cancel or complete it breaks when you return.

(passwordAuthority: 'https://XX.b2clogin.com/XX.onmicrosoft.com/B2C_1_SSPR')

```
this.msalService.handleRedirectCallback((authError, response) => {
    if (authError.toString().indexOf('AADB2C90118') > -1) {
          this.msalService.authority = environment.passwordAuthority;
          this.msalService.loginRedirect();
    }
}
```

It seems others have had the issue i.e. [this thread](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/701) which doesnt offer much hope currently.

**Comment by jacksonhart** [comment]
Thanks @derisen,

switching authorities and then logging in again instead of redirecting manually works.

The above was our pw reset flow.

I just have a question about handling the type 'access_token' in the callback.
In what situation does that occur? Its not something we are currently handling.
I.e. can I leave that block empty for now.

Cheers.

**Comment by derisen** [comment]
@jacksonhart glad you solved your issue : ) Can you remind me which callback is this? If you're talking about [this](https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp/blob/aff0ad7ce528561f7dfe211edfd8ec9842bbe44d/JavaScriptSPA/authRedirect.js#L39), then that's not something you have to worry in Msal-Angular. It's simply to check whether the token returned is an id_token or access_token.

**Comment by jacksonhart** [comment]
Great thanks @derisen.
