### ISSUE TITLE
Unable to sign in multiple users.  loginRedirect adds login_hint to redirect and tries to sign in existing user.

### ISSUE THREAD

**Issue by jrmcdona** [AzureAD/microsoft-authentication-library-for-js#1893]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
"@azure/msal-browser": "^2.0.0-beta.2"

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
Angular

## Description
It does not seem that there is a loginRedirect or login function that does not add the login_hint to the return URL.

The Microsoft ME Control within UHF needs to be able to sign in multiple users.   You could try to log the user out first but that defeats the purposed of having multiple accounts logged in and switching between them  Which is also part of ME Control and UHF.

Am I missing something or does this not exist?

![image](https://user-images.githubusercontent.com/4327773/86541289-47c8b680-bed1-11ea-9b53-2469e28ebc93.png)

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## Expected behavior
I would expect to be able to sign in multiple users and have the APIs available to do so.

## Browsers/Environment
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jrmcdona** [comment]
Calling logout before loginrRedriect didn't work it seems.  So that doesn't look like an option anyhow.

**Comment by jo-arroyo** [comment]
Hi @jrmcdona, please try using 2.0.0-beta.3. Beta.2 does not have support for multiple account scenarios. Please reach out if you still have issues with beta.3. Thank you.

**Comment by jrmcdona** [comment]
@jo-arroyo I had to roll back from .3 as it had some core issues.   I have this in produciton since I had to move to auth code flow for a certain scenario that was required for my First Party Microsoft app.

https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1844

**Comment by jrmcdona** [comment]
I will reopen this if I get back into testing this scenario.
