### ISSUE TITLE
Missing 'Auth-start' broadcast message to detect when the authentication has commenced

### ISSUE THREAD

**Issue by vajnorcan** [AzureAD/microsoft-authentication-library-for-js#1894]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
How can I detect when the **MsalGuard** starts the authentication so I can display the profile component in 'pending' state ?

My application doesn't require logging in the user at the landing page, but it does at some routes. Once the user hits the route guarded by the **Msal-Guard**, I'd like to display the pending state of the profile component as the authentication might take few secs. 

What is the recommended approach?

Thank you

**Comment by jo-arroyo** [comment]
@vajnorcan Unfortunately, the library does not emit any events at the start of the authentication process. We'll take this into consideration for future versions of the library. (The library will emit events when the authentication process is complete).

We don't have a recommended approach for your use case, but you can look at the Angular router events [here](https://angular.io/api/router/Event) which may be helpful.

**Comment by jasonnutter** [comment]
This is now possible in MSAL Angular v2: https://github.com/AzureAD/microsoft-authentication-library-for-js/releases/tag/msal-angular-v2.0.0-alpha.0

Closing.
