### ISSUE TITLE
Would it be possible to use relative paths for the redirectUri?

### ISSUE THREAD

**Issue by DarkLite1** [AzureAD/microsoft-authentication-library-for-js#1896]
## Library
- [x] `@azure/msal-browser@2.0.0-beta-3`

## Description

Using a relative path for the `redirectUri` fails:

```typescript
export const login = async () => {
  if (isLoginPopup) {
    return auth.loginPopup({ redirectUri: '/', scopes: allScopes })
  }
    return auth.loginRedirect({ redirectUri: '/', scopes: allScopes })
}
```
![image](https://user-images.githubusercontent.com/10828570/86599115-7bbddd80-bf9e-11ea-86b3-3e7641aede95.png)

Would it be possible to support relative paths to be used in the redirectUri? Things like `/`, `/about`, `/settings`, .... instead of a FQDN  like`http://localhost:8080/`. It would be great if the library was able to stitch these two together behind the scenes.

**Comment by jo-arroyo** [comment]
@DarkLite1 Thanks for the suggestion. We agree that this would be a nice enhancement. We'll track this and post an update here when it gets added to the library.
