### ISSUE TITLE
How to use forceRefresh: true in msal-angular config

### ISSUE THREAD

**Issue by hammerstrike** [AzureAD/microsoft-authentication-library-for-js#1913]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
How do I use `forceRefresh: true` in msal-angular config?

Skip cache option is available in msal. [Ref](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-core#forcerefresh-to-skip-cache)

config pass inside `MsalModule.forRoot({})` not accepting `forceRefresh` for me.
What is the best way to skipCache and use forceRefresh in config?
Thnx,

**Comment by jo-arroyo** [comment]
@hammerstrike Currently, `forceRefresh` can be used with direct calls to `acquireTokenSilent` in Angular. Unfortunately there is no way to pass `forceRefresh` from the configuration to the guard or interceptor. This is an enhancement we would like to make, so we will track this issue and update it when it has been added to the Angular library.

**Comment by jasonnutter** [comment]
This is now possible in MSAL Angular v2: https://github.com/AzureAD/microsoft-authentication-library-for-js/releases/tag/msal-angular-v2.0.0-alpha.0

Closing.
