### ISSUE TITLE
Scopes are being changed to lowercase

### ISSUE THREAD

**Issue by dapathy** [AzureAD/microsoft-authentication-library-for-js#1922]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.3.2` or `@azure/msal@1.3.2`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Description
#1600 seems to have introduced a change that is changing all scopes to lowercase.  This is causing issues with some backends that have case-sensitive audience validation.

## Error Message
Receiving a 401 from call to API due to invalid audience.

## Security
- [ ] Is this issue security related?

## Regression
- [x] Did this behavior work before? 
Version: 1.2.2

## MSAL Configuration

```js
this.msalContext = new UserAgentApplication({
	auth: {
		clientId: config.clientId,
		authority: `https://login.microsoftonline.com/${tenant}`,
		redirectUri: config.redirectUri || defaultRedirect,
		postLogoutRedirectUri: config.postLogoutRedirectUri || defaultRedirect,
		validateAuthority: true,
		navigateToLoginRequestUrl: true
	},
	cache: {
		cacheLocation: "sessionStorage",
		storeAuthStateInCookie: this.isEdge() || this.isInternetExplorer()
	},
	framework: {
		protectedResourceMap: new Map(),
		unprotectedResources: []
	}
});
```

## Reproduction steps
```js
const requestParameters: AuthenticationParameters = {
	scopes: ["https://UpperCase.domain.com/.default]
};
```

## Expected behavior
Scopes should be unmodified (other than trimming)

## Browsers/Environment
- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari
- [x] IE
- [ ] Other (Please add browser name here)

**Comment by jo-arroyo** [comment]
@dapathy Thanks for the information. This is something we're going to look at and follow up on.
