### ISSUE TITLE
Silent login fails when id/access token preferred_username for guest users is in the form of username_gmail.com#EXT#@tenant.onmicrosoft.com

### ISSUE THREAD

**Issue by Tim91084** [AzureAD/microsoft-authentication-library-for-js#1925]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

This appears to affect 1.x versions of msal

## Framework
Framework independent

## Description
Occasionally, the id/access token returned from a guest user login contains a `preferred_username` in the form of `username_gmail.com#EXT#@tenant.onmicrosoft.com`.  Most of the time this is not an issue - especially if you only need a token for a single scope.  Occasionally though, like in my scenario, I need to get a token for one of my API's, and then subsequently try to retrieve a token for a graph API call.  When using msal's `acquireTokenSilent` the second time, the library appears to get confused.  It recognizes that the user is logged in, but that they don't have an access token in the cache for the new scope being requested.  As a result, the library tries to facilitate a silent login by passing a `loginHint` using the `preferred_username` from the id/access token it has in the cache.  Since that's not a valid username, the silent login fails.

## Security
- [ ] Is this issue security related?

## Regression
- [x] Did this behavior work before? 
Prior to about a week ago, we never received a token with a `preferred_username` in the form of: `username_gmail.com#EXT#@tenant.onmicrosoft.com`

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Browsers/Environment
- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by mattrichard** [comment]
We recently started having this issue as well. In addition to what is described above, when this occurs, attempting to provide the `sid` from the id token results in the following error: "Application requested a user session which does not exist". The only way we're able to get around this right now is to supply the loginHint with the expected value (not the `preferred_username`) and do a full redirect.

**Comment by shb98** [comment]
+1

**Comment by Tim91084** [comment]
Looks like this may be related?

https://github.com/SharePoint/sp-dev-docs/issues/3722

**Comment by jo-arroyo** [comment]
@Tim91084 There are known issues with login hint and guest users. Please try enabling the sid claim and passing that in your requests? Here are the instructions to enable sid: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims

@mattrichard Does this error happen every time, or is it intermittent?

**Comment by Tim91084** [comment]
@jo-arroyo, I am not passing the `loginHint`, the msal library is doing it.  I am happy to add `sid` as an optional claim, but this still seems like a legitimate bug against the library unless this limitation is specified somewhere in the docs. 

Also it seems @mattrichard has already tried that and did not have success.

**Comment by mattrichard** [comment]
@Tim91084 I'd recommend still adding the sid claim, especially when dealing with guest users. My issue might end up being a different issue.

@jo-arroyo I'll try to get back to you once I have more info, or will open a separate issue. I'm starting to think my issue is unrelated.

**Comment by jasonnutter** [comment]
We have heard about intermittent errors with `sid` (which is why we asked @mattrichard to clarify), but it should work otherwise.

**Comment by rhummelmose** [comment]
I am seeing this with MSAL 2, trying to get an access token using acquireTokenSilent with a guest account, regardless of its preffered username, returns me an access token without any scopes.
