### ISSUE TITLE
Some requests failing while others succeed due to CORS error

### ISSUE THREAD

**Issue by a-train** [AzureAD/microsoft-authentication-library-for-js#1926]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.3.2` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.0.0`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Please provide your question here, including as much relevant details as possible.

I'm using MSAL Angular to acquire an access token and attach it to http calls that go to my API with the MsalInterceptor. 

I am seeing a very strange behavior in some of my requests that is driving me mad.

Very consistently, some of my requests to the same endpoint always succeed and some always fail. The only difference between them is a slightly different parameter in the query string. The requests are each started in the same way from my code, but one will always (consistently) fail. 

I see this CORs error for the one that failed:

`Access to XMLHttpRequest at 'https://login.windows.net/707e8816-9153-4841-b8eb-17b974748957/oauth2/authorize?response_type=id_token&redirect_uri=https%3A%2F%2Ffacilitydirectoryapi-dev.azurewebsites.net%2F.auth%2Flogin%2Faad%2Fcallback&client_id=9851368d-c8ef-450e-a3fa-6f5bf662b23f&scope=openid+profile+email&response_mode=form_post&nonce=18b6f4b29c624d9a87e9a40f335589f3_20200710165933&state=redir%3D%252Fgraphql%253Fquery%253D%25257Bemployee(facilitycode%253A%252520%2525220500%252522)%25257B%252520company%252520companyCode%252520dept%252520deptDesc%252520div%252520divDesc%252520%252520eeid%252520eeType%252520email%252520employeeNumber%252520facility%252520facilityCode%252520%252520firstName%252520hireDate%252520job%252520jobCode%252520jobLong%252520lastName%252520preferedName%252520remoteEmployee%252520spvNameFirst%252520spvNameLast%252520spvNameMiddle%252520spvEeid%252520spvEmpNo%252520status%252520termDate%25257D%25257D' (redirected from 'https://facilitydirectoryapi-dev.azurewebsites.net/graphql?query={employee(facilitycode:%20%220500%22){%20company%20companyCode%20dept%20deptDesc%20div%20divDesc%20%20eeid%20eeType%20email%20employeeNumber%20facility%20facilityCode%20%20firstName%20hireDate%20job%20jobCode%20jobLong%20lastName%20preferedName%20remoteEmployee%20spvNameFirst%20spvNameLast%20spvNameMiddle%20spvEeid%20spvEmpNo%20status%20termDate}}') from origin 'https://localhost:44356' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

![image](https://user-images.githubusercontent.com/5514536/87177246-f178c080-c2a0-11ea-8309-ea433fd1ec34.png)  

Only difference is a parameter, yet one will always fail and one will always work regardless of the order they're called.

Any idea why the CORS error is occurring on one but not the other?

Some insight would be greatly appreciated!

**Comment by jo-arroyo** [comment]
@a-train Take a look at [this comment](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1834#issuecomment-650171361) on another thread that had a similar CORS error. This may help with figuring out what might be adding or changing headers on your requests.

**Comment by a-train** [comment]
@jo-arroyo, thanks for getting back to me. This definitely got me thinking.

It turns out there was a bad configuration in the app's routing, which was interfering with API calls that contained certain codes (like 404 and 500).
