### ISSUE TITLE
MSAL NodeJS authentication error for WebApp and SPA

### ISSUE THREAD

**Issue by lucafaggianelli** [AzureAD/microsoft-authentication-library-for-js#1927]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`
- [x] `@azure/msal-node@1.0.0-alpha.0`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework

NodeJS - KoaJS

## Description

I integrated msal-node with a NodeJS server following this example:
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-node-samples/auth-code/index.js

BTW, the app is NodeJS REST API server + ReactJS SPA served by the same server and I need to auth users with Azure AD only for calling my REST API, no need to call MS Graph API or similar, so should I use MSAL.js or there's a better solution?

## Error Message

 If I register my app in Azure AD as **Web app**, I have an error of missing `client_secret`, otherwise if I register it as **SPA** I get *AADSTS9002325: Proof Key for Code Exchange is required for cross-origin authorization code redemption.*

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Browsers/Environment
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jo-arroyo** [comment]
@lucafaggianelli Thanks for bringing this to our attention. We are working on updating our node samples and will follow up.

**Comment by riazXrazor** [comment]
any progress yet i am getting this error

`{"errorCode":"invalid_client","errorMessage":"7000218 - [2020-07-24 06:15:57Z]: AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.\r\nTrace ID: 268d0f07-42a4-4318-b1b9-e5d1933a1900\r\nCorrelation ID: 107611aa-3a1f-421d-869d-b8c3175226bb\r\nTimestamp: 2020-07-24 06:15:57Z - Correlation ID: 107611aa-3a1f-421d-869d-b8c3175226bb - Trace ID: 268d0f07-42a4-4318-b1b9-e5d1933a1900","name":"ServerError"}`

**Comment by riazXrazor** [comment]
![image](https://user-images.githubusercontent.com/13194363/88365479-cc597700-cda3-11ea-96ea-4829fa178534.png)
in the lib found that its in TODO
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/src/server/RequestParameterBuilder.ts

**Comment by lucafaggianelli** [comment]
Ah I gave up and now I'm using passport azure ad

**Comment by riazXrazor** [comment]
I manually post request the data it worked.

**Comment by dvguo** [comment]
@riazXrazor Hi how did you solve the issue? I'm having the exact error after singing in and about to get the access token.

**Comment by riazXrazor** [comment]
i just manually did a post request with the appropriate data 
```  
const tokenRequest = {
    client_id: client_id,
    scope: 'https://graph.microsoft.com/.default',
    client_secret: client_secret,
    grant_type: 'client_credentials',
  };

  var options = {
    method: 'POST',
    url: 'https://login.microsoftonline.com/common/oauth2/v2.0/token',
    headers: {'content-type': 'application/x-www-form-urlencoded'},
    form: tokenRequest
  };

  request(options, function (error, response, body) {
    console.log(body)
  });


```
