### ISSUE TITLE
.loginPop() window position within browser window is cut off in Chrome and Edge.

### ISSUE THREAD

**Issue by cwalker-reveille** [AzureAD/microsoft-authentication-library-for-js#1928]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X ] `@azure/msal-browser@2.0.0-beta.4`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
vanilla JS

## Description
When calling .loginPopup on Chrome and Edge and the browser window is near the top of the screen, the popup window will have the top of it's frame outside the boundry of the screen (cut off and cannot see the title bar to move/resize). Using Firefox, the whole popup window will appear inside the boundry of browser window and displays correctly.

## Error Message
None
## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```
{
            auth: {
                clientId: 'xxxxxxxxxxxxxxxxx',
                redirectUri: 'http://localhost/'

            },
            cache: {
                cacheLocation: 'sessionStorage',
                storeAuthStateInCookie: false
            }
 }    
```

## Reproduction steps

1. Open the browser. Move the top of the browser to be near the top of your screen. 
2. Trigger an event to cause the .loginpopup() method to be called.
3. Note the position of the popup window. Edge and Chrome will show this window above the browser window and, depending on how close to the top to set the browser, the titlebar will not appear. Doing the same step on Firefox, the popup window will appear within the bounds of the browser window. 

## Expected behavior
The entire popup window should be visible initially.

## Browsers/Environment
- [ X] Chrome-> 83 and 86(canary)
- [ X] Firefox=> 78
- [ X] Edge -> 83 and 86 (edge canary)
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jo-arroyo** [comment]
@cwalker-reveille Can you please provide screenshots of this behavior?

**Comment by cwalker-reveille** [comment]
@jo-arroyo . Here is the screen show showing the the behavior when invoking the .loginPopup(). 
![image](https://user-images.githubusercontent.com/46533015/87349809-ed5cd500-c524-11ea-8610-34c487feba2f.png)
