### ISSUE TITLE
Log Errors to the Console Too

### ISSUE THREAD

**Issue by spottedmahn** [AzureAD/microsoft-authentication-library-for-js#193]
Why does [the code in](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dec1064eb1d38be29dff2f205e4e6413b0625ae6/src/UserAgentApplication.ts#L1343) `handleAuthenticationResponse()` only log errors to the `logger`?  Shouldn't it log to the console too?

```js
try {
    if (tokenReceivedCallback) {
    tokenReceivedCallback(errorDesc, token, error, tokenType);
    }

} catch (err) {
    self._logger.error("Error occurred in token received callback function: " + err);
}
```

I had a bug in my handler code and I got no indication that there was a problem.

If it shouldn't log to the console then shouldn't a `logger` be required or at least strongly encouraged?

**Comment by rohitnarula7176** [comment]
@spottedmahn Thank you for your feedback. We want to limit the number of required parameters in the constructor for better code readability and hence logger is not a required field. Logging errors on the console can lead to a lot of unnecessarily traffic for cases where people are writing automated login code and their callback function has an error. Hence as a library we do not log anything on the console. To catch this edge case, the developer will have to enable logging by passing a logger to the constructor function.

**Comment by spottedmahn** [comment]
Hi @rohitnarula7176 - I see, that makes sense.

I think it would be good to put a [NOTE] on the readme page that:
>errors will get swallowed... please use the logger to see error/issues

What do you think?

---

And, in the future, can you leave some time before closing the issue?  I understand proper hygiene and keeping the issues list current but what if the reporter has feedback 😄
