### ISSUE TITLE
Unable to use acquireTokenSilent() method for Live Accounts via Azure B2C

### ISSUE THREAD

**Issue by DibyodyutiMondal** [AzureAD/microsoft-authentication-library-for-js#1934]
## Library
- [x] `msal@1.3.2` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Description

This is essentially the same as #267

And so, it breaks functionality for MSA accounts using Azure AD B2C

In my chrome console, I get
```
Refused to display 'https://login.live.com.....' in a frame because it set 'X-Frame-Options' to 'deny'
```
... and then...
```
ClientAuthError: Token renewal operation failed due to timeout
```
Note: There is no problems for Azure AD Accounts (login.microsoftonline.com), only for Microsoft Social Accounts (login.live.com)

**Comment by jo-arroyo** [comment]
@DibyodyutiMondal Unfortunately, this is a known issue with MSA accounts in B2C. We have already flagged this with B2C, but if you would like to track it directly, please file a support ticket with the B2C team by following the instructions here: https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options

They can help you out further, they may ask for a public repro link or additional data. You can also link this Github issue in the support request.

**Comment by DibyodyutiMondal** [comment]
Unable file a support request because I'm not on a paid plan. Additionally, I can only type in 140 characters.

**Comment by DibyodyutiMondal** [comment]
Will the new preview of msal (2.x.x) have these shortcomings? It doesn't work for B2C at all last I checked, though.

**Comment by jo-arroyo** [comment]
@DibyodyutiMondal MSAL 2.0 is intended to support B2C, but we are currently working on some bug fixes. We are tracking this internally and will post an update here when it is available.

**Comment by DibyodyutiMondal** [comment]
Initial testing seems to suggest that signing in to live.com works but it's facing the same CORS issue as #1795 
Will need to test further to confirm that

**Comment by tnorling** [comment]
Msal 2.x now supports B2C and should not have this issue in most scenarios. Closing, please open a new ticket if this is not resolved after upgrading.
