### ISSUE TITLE
Unable to get sid in idtoken

### ISSUE THREAD

**Issue by DataHippo93** [AzureAD/microsoft-authentication-library-for-js#1935]
## Library
- [ ] `msal@1.3.1`
- [ ] `react-aad-msa@2.3.5`
## Documentation location
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims
https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-sso
_"Session ID is an optional claim that can be configured in the ID tokens. "_ 
## Description

I am trying to pass my idtoken to another domain and then use acquireTokenSilent with the sid so the user does not have to login and I can recreate the context in that other domain. 

I cannot for the life of me get the sid to be present in my id token. I am using Azure B2C with wechat as identity provider and a built-in flow. This means updating the optionClaims on the app level does not work because the built-in policy takes precedence. I have also tried creating a custom policy but I cannot get the sid as an output claim (documentation seems to tease that this is possible but cannot get it to work.) 

Can we update the documentation to explain this? Or better yet make it a configurable claim in the built-in flows.

**Comment by jo-arroyo** [comment]
@DataHippo93 Can you please indicate which version of MSAL you are using, and also link to the documentation you are referring to?

**Comment by tnorling** [comment]
@DataHippo93 Unfortunately `sid` is not available in `B2C` scenarios. The docs you linked are for `AAD` use cases, apologies for the confusion. Can you try passing `login_hint` with the user's username instead?
