### ISSUE TITLE
Access tokens in the cache are not used because all requests have openid and profile scopes

### ISSUE THREAD

**Issue by mderriey** [AzureAD/microsoft-authentication-library-for-js#1936]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.0.0-beta.4`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework

No framework.

## Description

1. Application code calls `loginRedirect` with a scope `<client-id>/user.access`
1. User logs in to AAD
1. AAD redirects to the app with an authorisation code
1. The authorisation code is exchanged for an id token, an access token, and a refresh token, which are stored in cache (1st network call to the token endpoint)
1. Application code calls `acquireTokenSilent` with the same scope that was provided in `loginRedirect`
1. Access token from cache is not used, and instead the stored refresh token is used to get a new access token (2nd network call to the token endpoint)

I believe I found what that is the case.

When calling `acquireTokenSilent`, the request passed as a parameter sees its scopes "augmented" with the `openid` and `profile` scopes through the [`initialiseBaseRequest`](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/0f352a074dff709304d87e3543c89472a1bcf875/lib/msal-browser/src/app/PublicClientApplication.ts#L367-L370) method, which itself calls [`setDefaultScopes`](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/0f352a074dff709304d87e3543c89472a1bcf875/lib/msal-browser/src/app/PublicClientApplication.ts#L604).

The `SilentFlowClient` then tries to get a matching access token from the cache using the "augmented" list of scopes, which results in a cache miss, see [`readAccessTokenFromCache`](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/0f352a074dff709304d87e3543c89472a1bcf875/lib/msal-common/src/client/SilentFlowClient.ts#L109-L116).

As a result, the logic falls back to using the `RefreshTokenClient` to get a new access token, see [`acquireToken`](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/0f352a074dff709304d87e3543c89472a1bcf875/lib/msal-common/src/client/SilentFlowClient.ts#L61-L75).

## Error Message

None

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
{
  auth: {
    clientId: '<aad-client-id>',
    authority: 'https://login.microsoftonline.com/<aad-tenant-id>',
  },
  cache: {
    cacheLocation: 'localStorage'
  }
}
```

## Reproduction steps

N/A

## Expected behavior

Access tokens stored in the cache that match the requested scope(s) and that haven't expired should be used.

## Browsers/Environment
- [ ] Chrome
- [ ] Firefox
- [X] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jo-arroyo** [comment]
@mderriey Thanks for bringing this to our attention. We will look into this and follow up if we need more information.
