### ISSUE TITLE
MFA Support

### ISSUE THREAD

**Issue by nasrnassar** [AzureAD/microsoft-authentication-library-for-js#1937]
Hi,

I created an angular application with AAD authentication implemented based on the angular 9 sample, my application has a .net core API back-end that is also protected by AAD Authentication. Our organization has MFA enabled for all the users and if I try to open the application in incognito I get the following error 

`core.js:5828 ERROR Error: Uncaught (in promise): InteractionRequiredAuthError: AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access 'API Client Id'.
Trace ID: a1efbaca-fc0b-4ea9-8932-3571517f3700
Correlation ID: 44cb331f-a226-4a6d-ac71-f4159d490732
Timestamp: 2020-07-12 12:20:06Z
InteractionRequiredAuthError: AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access 'API Client Id'.
Trace ID: a1efbaca-fc0b-4ea9-8932-3571517f3700
Correlation ID: 44cb331f-a226-4a6d-ac71-f4159d490732
Timestamp: 2020-07-12 12:20:06Z
    at InteractionRequiredAuthError.AuthError [as constructor] (AuthError.js:22)
    at InteractionRequiredAuthError.ServerError [as constructor] (ServerError.js:22)
    at new InteractionRequiredAuthError (InteractionRequiredAuthError.js:24)
    at MsalService.push../node_modules/msal/lib-es6/UserAgentApplication.js.UserAgentApplication.saveTokenFromHash (UserAgentApplication.js:1385)
    at MsalService.push../node_modules/msal/lib-es6/UserAgentApplication.js.UserAgentApplication.processCallBack (UserAgentApplication.js:941)
    at MsalService.push../node_modules/msal/lib-es6/UserAgentApplication.js.UserAgentApplication.handleAuthenticationResponse (UserAgentApplication.js:993)
    at MsalService.<anonymous> (UserAgentApplication.js:737)
    at step (tslib.es6.js:99)
    at Object.next (tslib.es6.js:80)
    at fulfilled (tslib.es6.js:70)
    at resolvePromise (zone-evergreen.js:793)
    at resolvePromise (zone-evergreen.js:752)
    at zone-evergreen.js:854
    at ZoneDelegate.invokeTask (zone-evergreen.js:400)
    at Object.onInvokeTask (core.js:40744)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Zone.runTask (zone-evergreen.js:168)
    at drainMicroTaskQueue (zone-evergreen.js:570)
    at invokeTask (zone-evergreen.js:485)
    at ZoneTask.invoke (zone-evergreen.js:470)`

from what I understood msal will call acquireTokenSilent but that's not triggering MFA and I don't get the approval to my Authenticator.

Any help is appreciated.
Thank you in advance

**Comment by derisen** [comment]
@nasrnassar the pattern to handle these errors is to fallback to one of the interactive methods to acquire the token (which in this case should trigger MFA prompt). Take a look at the [documentation here](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-handling-exceptions?tabs=javascript#javascript-1).

**Comment by jo-arroyo** [comment]
@nasrnassar Hope the documentation helps. Please use our issue template in the future if you have further issues so we can attempt to reproduce the errors. Thank you.

**Comment by nasrnassar** [comment]
@jo-arroyo Apologies, I missed the template when adding my issue.
After going through the documentation link provided above and multiple failures, I filled the proper template below, hope this information sheds some light.

## Library
- [x] `msal@1.3.0`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.0.0`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework
Angular 9
.Net core 3.1.2
## Description
The application keeps going into 'msal:acquireTokenFailure' whenever I'm redirecting to the guarded Component.

## Error Message
`ERROR Error: Uncaught (in promise): InteractionRequiredAuthError: AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '2d5c1a48-588c-475a-9f33-65cf44627f3b'.
Trace ID: d558e24b-10c2-4864-ae28-8f36e1e28e00
Correlation ID: 393290df-4f36-436c-bbb6-a74f3d5bb8ef
Timestamp: 2020-07-14 07:39:53Z
InteractionRequiredAuthError: AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '2d5c1a48-588c-475a-9f33-65cf44627f3b'.
Trace ID: d558e24b-10c2-4864-ae28-8f36e1e28e00
Correlation ID: 393290df-4f36-436c-bbb6-a74f3d5bb8ef
Timestamp: 2020-07-14 07:39:53Z
    at InteractionRequiredAuthError.AuthError [as constructor] (AuthError.js:22)
    at InteractionRequiredAuthError.ServerError [as constructor] (ServerError.js:22)
    at new InteractionRequiredAuthError (InteractionRequiredAuthError.js:24)
    at MsalService.push../node_modules/msal/lib-es6/UserAgentApplication.js.UserAgentApplication.saveTokenFromHash (UserAgentApplication.js:1385)
    at MsalService.push../node_modules/msal/lib-es6/UserAgentApplication.js.UserAgentApplication.processCallBack (UserAgentApplication.js:941)
    at MsalService.push../node_modules/msal/lib-es6/UserAgentApplication.js.UserAgentApplication.handleAuthenticationResponse (UserAgentApplication.js:993)
    at MsalService.<anonymous> (UserAgentApplication.js:737)
    at step (tslib.es6.js:99)
    at Object.next (tslib.es6.js:80)
    at fulfilled (tslib.es6.js:70)
    at resolvePromise (zone-evergreen.js:793)
    at resolvePromise (zone-evergreen.js:752)
    at zone-evergreen.js:854
    at ZoneDelegate.invokeTask (zone-evergreen.js:400)
    at Object.onInvokeTask (core.js:40744)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Zone.runTask (zone-evergreen.js:168)
    at drainMicroTaskQueue (zone-evergreen.js:570)
    at invokeTask (zone-evergreen.js:485)
    at ZoneTask.invoke (zone-evergreen.js:470)`
## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
...
const baseHref = document.getElementsByTagName('base')[0].href;

export const protectedResourceMap: [string, string[]][] = [
    [
        baseHref,
        [environment.azureConfig.apiClientUrl]
    ],
    [environment.endpoints.GRAPH_ENDPOINT, ['user.read']]
];
const isIE = window.navigator.userAgent.indexOf('MSIE ') > -1 || window.navigator.userAgent.indexOf('Trident/') > -1;

function MSALConfigFactory(): Configuration {
    return {
        auth: {
            clientId: environment.azureConfig.uiClientId,
            authority: environment.azureConfig.instance + environment.azureConfig.tenantId,
            validateAuthority: true,
            redirectUri: baseHref,
            postLogoutRedirectUri: baseHref,
            navigateToLoginRequestUrl: true,
        },
        cache: {
            // cacheLocation: 'localStorage',
            storeAuthStateInCookie: isIE, // set to true for IE 11
        },
    };
}

function MSALAngularConfigFactory(): MsalAngularConfiguration {
    return {
        popUp: !isIE,
        consentScopes: [
            'user.read',
            'openid',
            'profile',
            environment.azureConfig.apiClientUrl
        ],
        unprotectedResources: ['https://www.microsoft.com/en-us/'],
        protectedResourceMap,
        extraQueryParameters: {}
    };
}
const appRoutes: Routes = [
    {
        path: 'apps',
        loadChildren: () => import('./main/apps/apps.module').then(m => m.AppsModule),
        canActivate: [
            MsalGuard
        ]
    },
    {
        path: 'pages',
        loadChildren: () => import('./main/pages/authentication/authentication.module').then(m => m.AuthenticationModule)
    },
    {
        path: '**',
        redirectTo: 'pages'
    }
];

@NgModule({
    declarations: [
        ...
    ],
    imports: [
      ...
RouterModule.forRoot(appRoutes, { useHash: true }),
        MsalModule,
...
    ],
    providers: [
        {
            provide: HTTP_INTERCEPTORS,
            useClass: MsalInterceptor,
            multi: true
        },
        {
            provide: MSAL_CONFIG,
            useFactory: MSALConfigFactory
        },
        {
            provide: MSAL_CONFIG_ANGULAR,
            useFactory: MSALAngularConfigFactory
        },
        MsalService
    ],
    bootstrap: [
        AppComponent
    ]
})

Login.component:
ngOnInit(): void {
        this.isIframe = window !== window.parent && !window.opener;

        this.checkoutAccount();

        this.broadcastService.subscribe('msal:loginSuccess', () => {
            this.checkoutAccount();
        });

        this.authService.handleRedirectCallback((authError, response) => {
            if (authError) {
                console.error('Redirect Error: ', authError.errorMessage);
                return;
            }

            console.log('Redirect Success: ', response);
        });

        this.broadcastService.subscribe('msal:acquireTokenFailure', payload => {
           if (!this.authService.getLoginInProgress()) {
                const accessTokenRequest = {
                    scopes: [environment.azureConfig.uiClientId],
                    authority: environment.azureConfig.instance + environment.azureConfig.tenantId,
                    forceRefresh: true
                };

                this.authService.acquireTokenPopup(accessTokenRequest).then((response) => {
                    console.log('success');
                    // redirect to my guarded component
                });
            }
        });

        this.authService.setLogger(new Logger((logLevel, message, piiEnabled) => {
            console.log('MSAL Logging: ', message);
        }, {
                correlationId: CryptoUtils.createNewGuid(),
                piiLoggingEnabled: false
            }));
    }

 checkoutAccount(): void {
        this.loggedIn = !!this.authService.getAccount();
    }

// called on button click
    login(): void {
        const isIE = window.navigator.userAgent.indexOf('MSIE ') > -1 || window.navigator.userAgent.indexOf('Trident/') > -1;

        if (isIE) {
            this.authService.loginRedirect();
        } else {
            this.authService.loginPopup().then((result) => {
                // redirect to my guarded component
            });
        }
    }

For the .NET core side, I set up the Authentication using JwtBearer with the below code

var tenantId = Configuration.GetValue<string>("AzureAd:TenantId");
            var apiAppId = Configuration.GetValue<string>("AzureAd:ClientId");
            var clientAppId = Configuration.GetValue<string>("AzureAd:UIClientId");

            services.AddAuthentication(sharedoptions =>
            {
                sharedoptions.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
            })
            .AddJwtBearer(options =>
            {
                options.Authority = $"https://login.microsoftonline.com/{tenantId}";

                options.TokenValidationParameters = new Microsoft.IdentityModel.Tokens.TokenValidationParameters
                {
                    ValidAudiences = new List<string>
                    {
                        apiAppId,
                        clientAppId
                    },
                    ValidIssuers = new List<string>
                    {
                        $"https://login.microsoftonline.com/{tenantId}/v2.0",
                        $"https://sts.windows.net/{tenantId}/",
                        $"https://sts.windows.net/{tenantId}/v2.0"
                    }
                };

                options.Events = new JwtBearerEvents
                {
                    OnAuthenticationFailed = ctx =>
                    {
                        if (!ctx.Response.HasStarted)
                        {
                            ctx.Response.StatusCode = StatusCodes.Status401Unauthorized;
                            message += "From OnAuthenticationFailed:\n";
                            message += FlattenException(ctx.Exception);
                        }
                        return Task.CompletedTask;
                    },

                    OnChallenge = ctx =>
                    {
                        if (!ctx.Response.HasStarted)
                        {
                            message += "From OnChallenge:\n";
                            ctx.Response.StatusCode = StatusCodes.Status401Unauthorized;
                            ctx.Response.ContentType = "text/plain";
                        }
                        return ctx.Response.WriteAsync(message);

                    },

                    OnMessageReceived = ctx =>
                    {
                        if (!ctx.Response.HasStarted)
                        {
                            message = "From OnMessageReceived:\n";
                            ctx.Request.Headers.TryGetValue("Authorization", out var BearerToken);
                            if (BearerToken.Count == 0)
                                BearerToken = "no Bearer token sent\n";
                            message += "Authorization Header sent: " + BearerToken + "\n";
                        }
                        return Task.CompletedTask;
                    },

                    OnTokenValidated = ctx =>
                    {
                        Debug.WriteLine("token: " + ctx.SecurityToken.ToString());
                        return Task.CompletedTask;
                    }
                };
            });
```

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.

- Create .NET core web application with Angular template
- Add the msal required libraries to the angular application
- Register both API and UI applications on Azure
- Start from a fresh browser where cookies and cache is emptied

```


## Expected behavior
I expect the app to trigger MFA so I can get the approval notification on MS Authenticator app
## Browsers/Environment
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jo-arroyo** [comment]
@nasrnassar The logs seem to indicate that a popup window is opened. Did you observe that? Can you also provide the logs that happen before the error?

**Comment by nasrnassar** [comment]
@jo-arroyo indeed a popup opens but closes immediately, and if i debug the code goes into the success function of "acquireTokenPopup" but when it tries redirecting to the guarded component that calls my .NET core api it throws the error.

**Comment by derisen** [comment]
@nasrnassar just in case, are you observing this in other browsers as well? The blinking popup window issue sometimes happen on Chrome -try checking your javascript settings.

**Comment by jo-arroyo** [comment]
@nasrnassar Is this only happening in Chrome Incognito? Does this happen in a normal Chrome window as well?

**Comment by nasrnassar** [comment]
@jo-arroyo if I'm already logged in to my microsoft account it doesn't happen.
@derisen it's not JavaScript setting but might be browser related. We're investigating if something is blocking the request from completely going through. Will update you on Sunday as soon as I find out.

**Comment by nasrnassar** [comment]
closing this issue, it was our network preventing the request from going properly. Sorry for any inconvenience and Thank you for your support
