### ISSUE TITLE
MSAL.js with B2C - verifying signout behaviour

### ISSUE THREAD

**Issue by philip-young** [AzureAD/microsoft-authentication-library-for-js#1941]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.3.0`

## Framework
React 16.8.3
## Description
I am using Msal.Js with a React app that utilizes Azure B2C with custom policies. I noticed that when you click logout in the app (which calls the msal logout() function) the log out seems to be successful. However, on subsequent visits to the app, you are taken to the B2C login page and when you click 'Work Account' (which I have using the [Azure Ad Multitenant provider](https://docs.microsoft.com/en-us/azure/active-directory-b2c/identity-provider-azure-ad-multi-tenant-custom?tabs=app-reg-ga) though a custom policy), it just puts you straight through. So it seems logout does not actually log the user out. Is this the desired behaviour? Is there any way to configure this? 

My second question is on the B2C signout in Fiddler I can see a call made to the https://login.microsoftonline.com/common/common/oauth2/v2.0/logout endpoint which returns a 200 and then redirects back to my app. Is this actually doing anything? According to the B2C Documentation [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/session-overview#sign-out), an attempt is made to sign out the user from their federated identity provider. I believe this is what is happening, or trying to happen. However, it doesn't seem to be working. When I redirect the user to the common logout endpoint myself, then it works (except I cannot get the post_logout_redirect_uri to work so it just stays on the common page, is this still a known issue?). When they visit the B2C Login Page again, they are prompted for their credentials.

I have also tested it with Gmail and it does the same. It seems that the logout function does not log the user out of their Gmail session, however on subsequent visits to the app when they click Gmail it takes them right in. However I do not see an attempt to sign them out of their identity provider. I am primarily concerned with the Azure Ad login though.

## Security
- [ ] Is this issue security related? No.

## Regression
- [ ] Did this behavior work before? I don't believe so.
Version:

## MSAL Configuration

```js
Configuration = {
    auth: {
      authority: `https://mytenant.b2clogin.com/mytenant.onmicrosoft.com/b2c_1a_susi`,
      clientId: `GuidHere`,
      redirectUri: 'https://myapp.com/acc/authenticate',
      validateAuthority: false,
      postLogoutRedirectUri: (!!window ? window.location.origin : '') + '/signout'
    },
    cache: {
      cacheLocation: "localStorage",
      storeAuthStateInCookie: false
    }
  };
```

## Reproduction steps
1. Sign in to app with B2C Login using msal.LoginRedirect() and if is an Azure Ad Account, using ssoSilent() and sid claim.
2. Sign out of app, using msal logout()
3. Sign into app again, go to B2C Login Page
4. Click on Provider and am still logged in and taken right through to the App.

## Expected behavior
User is actually logged out when the Microsoft common logout endpoint is hit.

## Browsers/Environment
- [ ] Chrome Yes
- [ ] Firefox Yes
- [ ] Edge
- [ ] Safari Yes
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jo-arroyo** [comment]
@philip-young In regards to your first question, this is indeed the expected behavior. Calling logout removes the B2C session cookie, and the user is logged out of the B2C tenant, but the user is not logged out from their social IDP, so that they are not signed out of other websites which may also be logged in. B2C does not currently support federated logout.
From the [B2C documentation](https://docs.microsoft.com/en-us/azure/active-directory-b2c/session-overview#sign-out) linked above:

> The sign-out clears the user's single sign-on state with Azure AD B2C, but it might not sign the user out of their social identity provider session. If the user selects the same identity provider during a subsequent sign-in, they might reauthenticate without entering their credentials. If a user wants to sign out of the application, it doesn't necessarily mean they want to sign out of their Facebook account.

Your second question is in regards to a known issue that is being tracked internally. If you would like to track it directly, please file a support ticket with the B2C team by following the instructions here: https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options

**Comment by philip-young** [comment]
Thank you for the response @jo-arroyo and for confirming that. I was wondering about the behaviour of this. 

I have submitted a ticket to B2C as you recommended regarding the second issue. I still have yet to hear back. I missed the part where you said I should link this GitHub issue, should I leave it open for now and reference it when they get back to me?

**Comment by tnorling** [comment]
Closing as there is no further action from the msal team at this time
