### ISSUE TITLE
redirectUri not available on SilentFlowRequest 

### ISSUE THREAD

**Issue by dapathy** [AzureAD/microsoft-authentication-library-for-js#1951]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@v2.0.0-beta.4
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Description
The docs for SilentFlowRequest mention a redirectUri property, but it's not available on the type.  Will this be added in the future?
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/c6db556ceef9012bc1852dcf27e9d46fae4c2046/lib/msal-common/src/request/SilentFlowRequest.ts#L16

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:
(similar functionality did exist in msal 1.2.x)

## Expected behavior
The redirectUri property should be available on the type and be used appropriately.

## Browsers/Environment
- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari
- [x] IE
- [ ] Other (Please add browser name here)

**Comment by jo-arroyo** [comment]
@dapathy Thanks for pointing that out. It was something we were considering for silent flow, but have since decided against it. If you need a redirectUri in case of a refresh token error, please use the redirectUri parameter in configurations.

**Comment by dapathy** [comment]
@jo-arroyo In the msal 1.x library, we could specify the redirectUri so that the iframe could point to an empty page.  Is that no longer necessary?  Thank you

**Comment by pkanher617** [comment]
@dapathy Apologies I think this was an oversight. I will add the ability to specify this for iframe request. 

To be clear, acquireTokenSilent in 2.x will only open an iframe if the refresh token is expired.

ssoSilent also opens an iframe, and accepts a redirect URI

**Comment by dapathy** [comment]
Thank you
