### ISSUE TITLE
B2C token validation by msal libraby

### ISSUE THREAD

**Issue by rajesh-naik-by** [AzureAD/microsoft-authentication-library-for-js#1952]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.x.x` or `@azure/msal@1.x.x`

## Description
I have a generic question about token validation from msal library for js, does msal library takes care of validating below attributes from the token? or is it a responsibility of consumer to validate the token?

- Signature
- exp
- nbf
- iss
- aud

**Comment by jo-arroyo** [comment]
@rajesh-naik-by MSAL does not perform any token validation itself. It is the responsibility of resources to validate all tokens that they receive.
