### ISSUE TITLE
Please decide over and communicate a new GA date for msal-browser 2.0

### ISSUE THREAD

**Issue by mindcrash** [AzureAD/microsoft-authentication-library-for-js#1953]
## Library
- `@azure/msal-browser@2.x.x`

## Description
Since the original release window has been missed please update README.md with a new expected GA date.

We really would like to have this as input for our technology roadmap as it seems this version is a much better fit for SPAs/browser based apps than the current one.

**Comment by DarylThayil** [comment]
Thanks for reaching out.  We expect to cut 2.0 this week.  We were waiting on a server fix to get deloyed.  
@pkanher617  cc   Updating read me now

**Comment by DarylThayil** [comment]
Updated readme with date of 7/20 
Thanks for the feedback!
