### ISSUE TITLE
Logout without logoutRequest does not clear cache

### ISSUE THREAD

**Issue by philtweir** [AzureAD/microsoft-authentication-library-for-js#1956]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.0.0-beta4`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

Also visible in current dev branch.

## Description

Spotted when migrating from MSAL 1.x, where logout does not require a passed account: `PublicClientApplication.logout()` is not properly clearing the cache unless an account is actually passed within the optional `logoutRequest` parameter.

From looking at [AuthorizationCodeClient.ts:111](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/3c11674f5e741eedc9f2e6ea74d31068119da803/lib/msal-common/src/client/AuthorizationCodeClient.ts#L111), it seems that the `AuthorizationCodeClient.clear` call is skipping removing account cache entries, as they do not begin with `Constants.CACHE_PREFIX` (`CredentialEntity.generateCredentialCacheKey` does not add it). From looking at #1802 and the comment on [AuthorizationCodeClient.ts:110](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/3c11674f5e741eedc9f2e6ea74d31068119da803/lib/msal-common/src/client/AuthorizationCodeClient.ts#L110), this does not seem to be intended.

## Error Message

None; on returning to the page, after logout redirect, the `PublicClientApplication.getAllAccounts()` still has entries, breaking the logout flow.

## Reproduction steps

1. Log in to an AD instance
2. Call `PublicClientApplication.logout()` with no argument
3. User is redirected to logout endpoint
4. On returning to the page, the user still has an account in `PublicClientApplication.getAllAccounts()` - i.e. appears to the app to be logged in

## Expected behavior

`PublicClientApplication.getAllAccounts()` has no entries.

## Browsers/Environment

Tested on Firefox, but not browser specific.

**Comment by philtweir** [comment]
Temporary confirmed workaround for a single login: `client.logout(client.getAllAccounts()[0])` (plus necessary checks)

**Comment by pkanher617** [comment]
@philtweir The logic in #1919 should fix this issue.

**Comment by philtweir** [comment]
Many thanks

**Comment by pkanher617** [comment]
#1919 merged
