### ISSUE TITLE
AADSTS16000 

### ISSUE THREAD

**Issue by ranjanmicrosoft** [AzureAD/microsoft-authentication-library-for-js#1958]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.3.1` or `@azure/msal@1.x.x`
- [x] `@azure/msal-angular@1.0.0`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Description
Please see this link for additional info and solution. The same issue exists in MSAL and ADAL library.  
https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/580

The issue is specifically with MSA passthrough accounts with more than one account signed in. The token does not return enough information so it is ambiguous and the user can not log in. Using the data from the 'email' field to replace the 'upn' field when it is not present works as a solution in ADAL as suggested in the link, and I assume the same fix would work for MSAL. 

## Error Message
AADSTS16000

I just recreated this issue, since it was closed without fixing: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1816

I believe this is an existing bug in the library, the code here lists checking how this behaves when the idtoken has no upn as a todo, which I don't think works right now

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/266c6e98c861b5cfb124647c04d377ebf8412087/lib/msal-core/src/ServerRequestParameters.ts

**Comment by jo-arroyo** [comment]
@ranjanmicrosoft You could try passing in a session id (sid) as part of the request. This is an optional claim that will help you bypass account selection, as detailed on the docs [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-sso#automatically-select-account-on-azure-ad).

**Comment by ranjanmicrosoft** [comment]
i'm using the msal-angular library, not making these requests on my own. would i need to reimplement the MsalInterceptor to make that change?

**Comment by jo-arroyo** [comment]
@ranjanmicrosoft Unfortunately, it is a known issue that you are unable to pass additional options to the `acquireTokenSilent` call made inside the MSAL Interceptor. This is something we are planning to address soon. For now, you can reimplement the MSAL Interceptor to be able to pass additional parameters to the `acquireTokenSilent` call.

**Comment by jasonnutter** [comment]
Passing additional parameters to the interceptor is now possible in MSAL Angular v2 alpha: https://github.com/AzureAD/microsoft-authentication-library-for-js/releases/tag/msal-angular-v2.0.0-alpha.0

Closing.
