### ISSUE TITLE
Not able to login from multiple accounts after moving to 1.x.x

### ISSUE THREAD

**Issue by madhugore1** [AzureAD/microsoft-authentication-library-for-js#1965]
##  Library
- `@azure/msal-1.3.3-beta.0`
- `@azure/msal-angular-1.0.0`

## Framework
- Angular 9

## Description
- We recently upgraded the msal library version from 0.x.x to 1.x.x. Previously, the single sign on used to ask for the account selection through which user could select multiple accounts to log in to the application. After upgrading the msal library version to 1.x.x, **we observe that the loginPopup() method on passing only the { scopes: ['user.read'] }, the default account is getting selected and the user is not able to sign in from multiple accounts.**

Is there any configuration option we're missing that needs to be added? Please suggest a fix for this behaviour.

**Comment by jo-arroyo** [comment]
@madhugore1 You can pass `prompt=select_account` when you call `loginPopup` to prompt the user to select which account they would like to use. 

```javascript
this.authService.loginPopup({
  scopes: ["User.Read"],
  prompt: "select_account"
})
```

**Comment by tnorling** [comment]
Closing as the question was answered. Let us know if the above did not solve your issue
