### ISSUE TITLE
azure-msal-angular.js - unprotectedResources Array Issue

### ISSUE THREAD

**Issue by svpoon** [AzureAD/microsoft-authentication-library-for-js#1966]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Description
Inside azure-msal-angular.js, the following code is not quite correct:
```
        _this.router.events.subscribe(function (event) {
            for (var i = 0; i < router.config.length; i++) {
                if (!router.config[i].canActivate) {
                    if (_this.msalAngularConfig.unprotectedResources) {
                        if (!_this.isEmpty(router.config[i].path) && !_this.isUnprotectedResource(router.config[i].path)) {
                            _this.msalAngularConfig.unprotectedResources.push(router.config[i].path);
                        }
                    }
                }
            }
        });
```

Should the condition  !_this.isUnprotectedResource be  _this.isUnprotectedResource instead?

In my scenario, it is adding all the paths from my routes as UnproectedResources.

Please check if it is correct or I am not setting up the configuration improperly.

## Security
- [ ] Is this issue security related? No

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration
```
        MsalModule.forRoot({
            auth: {
                clientId: '....',
                authority: '....',
                redirectUri: '....'
            },
        },
            {
                popUp: !isIE,
                consentScopes: [
                    'api://........', "openid", "profile"
                ],
                unprotectedResources: ["https://www.microsoft.com/en-us/"],
                protectedResourceMap: [
                    ['http://localhost:5000/', ['api://......']]
                ],
                extraQueryParameters: {}
            })
```

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Browsers/Environment
- [x] Chrome
- [x] Firefox
- [x] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jo-arroyo** [comment]
@svpoon This is a known issue, and will be fixed soon. Thank you.
