### ISSUE TITLE
Difference between company account and MSA account

### ISSUE THREAD

**Issue by pieterdv** [AzureAD/microsoft-authentication-library-for-js#197]
Hi,

I'm creating an test application with MSAL to see how we can implement it in our products. I stumbeled upon something I can't explain, so I hope someone can explain it to me.

I can configured the application like this

![image](https://user-images.githubusercontent.com/1443286/33502564-e58f07f6-d6e0-11e7-8f1c-89c46eb74288.png)

I use msal.js to get an authorization token

![image](https://user-images.githubusercontent.com/1443286/33502638-2c8d18fa-d6e1-11e7-919d-c9a5c833f236.png)

I get redirected to login page as expected, if I try to login with my company account, I don't get to the consent screen and get back following error description:

AADSTS65005: The application 'auth-test' asked for scope 'openid' that doesn't exist on the resource. Contact the app vendor.

If I login with my MSA account, I get to the consent screen and back to my application with an authorization token as expected

So for the same app there's a difference between company account and MSA account? What do I have to do so that I can get with my company account to the consent screen and back to the application with an authorization token?

Kind regards

**Comment by nehaagrawal** [comment]
@pieterdv Is this still an issue? Is your company account registered with AAD? Are you using the same authority for both MSA and company account?

**Comment by navyasric** [comment]
@pieterdv Closing this issue as we need more info to investigate. Please reopen if the issue still exists for you.
