### ISSUE TITLE
msal-angular 1.0.0: update msal from 1.3.0 to 1.3.3 invalid_token error

### ISSUE THREAD

**Issue by Mr230268** [AzureAD/microsoft-authentication-library-for-js#1975]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `@azure/msal@1.3.3`
- [ ] `@azure/msal-browser@2.x.x`
- [X] `@azure/msal-angular@1.0.0`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework
Angular 8
## Description
After Update MSAL from 1.3.0 to 1.3.3 I get from the API-Server an 401 Unauthorized. If I install 1.3.0 of MASL everything is fine.

## Error Message
Bearer error="invalid_token", error_description="The audience 'xxxxxxxxxxxxxxxxxxxxxxxx' is invalid"

## Security
- [ ] Is this issue security related?

## Regression
- [x] Did this behavior work before? 
Yes
Version:msal 1.3.0 

## MSAL Configuration
auth: {
        clientId: '45t45g4g-1ab3-4374-b63e-8139e1d42350',
        authority: 'https://login.microsoftonline.com/dddddddd',
        validateAuthority: true,
        navigateToLoginRequestUrl: false,
      },
      cache: {
        cacheLocation: 'localStorage',
        storeAuthStateInCookie: false 
      },
    },
      {
        popUp: false,
        consentScopes: [
          'user.read',
          'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
        ],
        unprotectedResources: ['https://www.microsoft.com/en-us/'],
        protectedResourceMap,
        extraQueryParameters: {}
      })

## Reproduction steps
Just update

## Browsers/Environment
- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [X] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jo-arroyo** [comment]
@Mr230268 This is a known issue that has been addressed in the PR linked above, and will be fixed in the next release.
