### ISSUE TITLE
Broken links on microsoft-authentication-library-for-js/tree/dev/lib/msal-browser#samples

### ISSUE THREAD

**Issue by damoodamoo** [AzureAD/microsoft-authentication-library-for-js#1976]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Documentation location
- [ ] docs.microsoft.com
- [ ] MSAL.js Github Wiki
- [ X ] README file
- [ ] Other (please fill in)
- [ ] Documentation does not exist

## Description
Links to the samples in the https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-browser#samples all lead to 404 pages in GH.

**Comment by jo-arroyo** [comment]
@damoodamoo Thanks for bringing this to our attention. We will update the sample links.
