### ISSUE TITLE
[msal-node] Remove default scopes from refresh and silent flows

### ISSUE THREAD

**Issue by pkanher617** [AzureAD/microsoft-authentication-library-for-js#1979]
Please follow the issue template below. 

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Upcoming Library
- [x] `@azure/msal-node@1.x`

## Source
- [ ] Internal (MSAL.js team)
- [ ] Customer request

## Description
We have removed adding default scopes from `acquireTokenSilent` in the `msal-browser` package to ensure that we don't have any cache misses. `msal-node` should follow the same model to ensure that we don't go to the wire when we don't need to.

## Priority
Medium

## Acceptance Criteria
`msal-node` handles the scenario where non-graph resource scopes are sent together and cause a cache miss because of default scopes.

**Comment by pkanher617** [comment]
Refer to #1962 for `msal-browser` changes.

**Comment by tnorling** [comment]
Closing per #2267 all network calls should request default scopes
