### ISSUE TITLE
getAccountByUsername not matching

### ISSUE THREAD

**Issue by IainAdamsLabs** [AzureAD/microsoft-authentication-library-for-js#1980]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.0.0-beta.4`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

N/A

## Description

When trying to retrieve an account by username the account is not being returned. This is because it has been stored with a capitalised first letter 'Iain@xxx.com' and I am trying with 'iain@xxx.com'. 

<img width="674" alt="Screenshot 2020-07-16 at 20 13 52" src="https://user-images.githubusercontent.com/55837547/87712729-0671ba00-c7a1-11ea-92a4-1a421658e6ae.png">

I assume this is because in the response from MS the username is capitalised. However, they are the same account.

## Expected behavior

This is the same user. It must be because I login with iain@xxx.com

Request to change:

```
getAccountByUsername(userName: string): AccountInfo {
        const allAccounts = this.getAllAccounts();
        return allAccounts.filter(accountObj => accountObj.username === userName)[0];
}
```
to
```
getAccountByUsername(userName: string): AccountInfo {
        const allAccounts = this.getAllAccounts();
        return allAccounts.filter(accountObj => accountObj.username?.toLowerCase() === userName?.toLowerCase())[0];
}
```

## Browsers/Environment
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by tnorling** [comment]
@IainAdamsLabs Thanks for reporting this! PR is linked to fix this and will make it into the next release.
