### ISSUE TITLE
getAllAccounts() treats any local storage entry with json as an 'account'

### ISSUE THREAD

**Issue by daniel-chambers** [AzureAD/microsoft-authentication-library-for-js#1984]
## Library
- [x] `@azure/msal-browser@2.0.0-beta4`

## Framework
React

## Description
If the browser local storage contains any non-MSAL entries that have a JSON-shaped value, regardless of content, they are treated as "accounts", which effectively come through with all their properties as `undefined`.

## Error Message
Passing one of these accounts into any other API causes null reference exceptions because the account object is malformed.

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
const msalConfig = {
  auth: {
    clientId: '<my client id>',
    redirectUri: window.location.origin,
    authority: 'https://login.microsoftonline.com/<my tenant id>'
  }
}
```

## Reproduction steps
Clear your local storage, then create an entry with any key name (a guid will do, but I discovered this because our redux state is stored in local storage with key name `redux-state`), and make the value any json (`{}` will do).

```js
import * as Msal from "@azure/msal-browser"

const msalConfig = {
  auth: {
    clientId: '<my client id>',
    redirectUri: window.location.origin,
    authority: 'https://login.microsoftonline.com/<my tenant id>'
  }
}

const publicClientApplication = new Msal.PublicClientApplication(msalConfig);

console.log("All accounts:");
const accounts = publicClientApplication.getAllAccounts();
console.log(accounts);
```

You'll see the accounts listed on the console, and you'll see a corrupt one in there.

For example, with a local storage like this:
![image](https://user-images.githubusercontent.com/1214352/87745703-01a91680-c832-11ea-9ff7-64333a973721.png)

You'll get a console output like this:
![image](https://user-images.githubusercontent.com/1214352/87745737-11c0f600-c832-11ea-8c8a-da57624c8e74.png)

## Expected behavior
MSAL should only look at its own local storage keys and not get confused by other keys that may be in local storage and treat them like accounts.

## Browsers/Environment
- [x] Chrome
- [x] Firefox

**Comment by jo-arroyo** [comment]
@daniel-chambers This is a known issue that has been addressed in the PR linked above, and will be fixed in the next release.
