### ISSUE TITLE
Getting Error for using loginRedirect with handleRedirectCallBack

### ISSUE THREAD

**Issue by amng9560** [AzureAD/microsoft-authentication-library-for-js#1989]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Hello,

I am trying to use "@azure/msal-browser": "^2.0.0-beta.4" for a React.js project in order to use auth code flow instead of implicit flow. 
I followed the documentation to get the redirect method (I don't want to use the popup) https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-javascript-auth-code#:~:text=After%20a%20successful%20sign%2Din,application%20and%20processed%20by%20msal to the best of my abilities (pretty much copying and pasting). 
I'm having a hard time incorporating it in React.js, when I got to the point where I think it might be functioning I get an error saying **"Unhandled Rejection (TypeError): myMSALObj.handleRedirectCallback is not a function"**.

How do I incorporate @azure/msal-browser to use the loginRedirect?

**Comment by pkanher617** [comment]
@amng9560 `handleRedirectCallback` was deprecated in favor of using promises through the `handleRedirectPromise` function. The tutorial needs to be updated to reflect this. 

Please see our [usage](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-browser#usage) docs here which will give you more info on how to [initialize the application for redirect scenarios](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/initialization.md#redirect-apis).

**Comment by amng9560** [comment]
Thank you so much for your reply. That makes sense. I used the resources that you gave me and it works.
