### ISSUE TITLE
Should login screen be always popup ?  

### ISSUE THREAD

**Issue by prabhakarreddy1234** [AzureAD/microsoft-authentication-library-for-js#199]
Is it possible to redirect to a webapp with login screen than a popup ?  I am trying to use my own login pages using B2C UI customization. I don't want to show popup with login controls. Is this possible with MSAL js ?

**Comment by jmprieur** [comment]
It is possible @prabhakarreddy1234 : Instead of using loginPopup, you want to use loginRedirect: See https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/devApps/VanillaJSTestApp/index_LoginRedirect.html
