### ISSUE TITLE
msal-browser crashes before starting with an error `ReferenceError: window is not defined`

### ISSUE THREAD

**Issue by ken5scal** [AzureAD/microsoft-authentication-library-for-js#1994]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.0.0-beta.4`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
- none

## Description
- Importing `msal-browser` fails when  `BrowserUtils.ts:67` is called.

## Error Message

```
[nodemon] starting `ts-node -r dotenv/config --transpile-only ./index.ts`

/Users/Kengo/workspace/azure-ad-oidc-signin/node_modules/@azure/msal-browser/src/utils/BrowserUtils.ts:67
        if (window.fetch) {
        ^
ReferenceError: window is not defined
    at Function.BrowserUtils.getBrowserNetworkClient (/Users/Kengo/workspace/azure-ad-oidc-signin/node_modules/@azure/msal-browser/src/utils/BrowserUtils.ts:67:9)
    at Object.<anonymous> (/Users/Kengo/workspace/azure-ad-oidc-signin/node_modules/@azure/msal-browser/src/config/Configuration.ts:93:33)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/Users/Kengo/workspace/azure-ad-oidc-signin/AuthModule.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
```

## Security
- [ ] Is this issue security related?

No

## Regression
- [ ] Did this behavior work before? 

It worked in sample  `TypescriptTestApp2.0`.

## MSAL Configuration

```js
auth: {
            clientId: clientId,
            authority: `https://login.microsoftonline.com/${tenantId}` // single tenant authority
        },
        cache: {
            cacheLocation: "sessionStorage",
            storeAuthStateInCookie: false,
        },
        system: {
            loggerOptions: {
                loggerCallback: (level, message, containsPii) => {
                    if (containsPii) {	
                        return;	
                    }	
                    switch (level) {	
                        case LogLevel.Error:	
                            console.error(message);	
                            return;	
                        case LogLevel.Info:	
                            console.info(message);	
                            return;	
                        case LogLevel.Verbose:	
                            console.debug(message);	
                            return;	
                        case LogLevel.Warning:	
                            console.warn(message);	
                            return;	
                    }
                }
            }
        }
```

## Reproduction steps
1. copy and paste entire AuthModule.ts from [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-browser-samples/TypescriptTestApp2.0)
2. call it from  `index.ts ` 

```ts
import Express from 'express';
import { AuthModule } from "./AuthModule";

const port = 3000
const host = 'localhost'
const clientId = 'xxxxxx-xxxxx'
const tenantId = 'xxxxx-xxxxx'

const app = Express()
const path = require('path');
app.get('/', (req, res) => {
    new AuthModule(clientId, tenantId)
    res.sendFile(path.join(__dirname + '/index.html'));
    // res.send(data)
})
```

## Expected behavior
run without an error

## Browsers/Environment
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

It doesn't run

**Comment by pkanher617** [comment]
@ken5scal Could you describe what app model you are attempting to employ? If you are using a single page application, then `@azure/msal-browser` needs to be added to whatever application you are running in the browser, not in the Express server.

If you are creating a server-side application, you should look at `@azure/msal-node` [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-node) ([link to package](https://www.npmjs.com/package/@azure/msal-node)), which is currently still in alpha.

Your application above is attempting to instantiate `@azure/msal-browser`, which can only be run in a browser environment, in an Express server, which is not supported.

**Comment by reidbarber** [comment]
#570
#558

**Comment by ken5scal** [comment]
@pkanher617 supposed to be running in SPA environment. Probably that may be the reason. I will try it out

**Comment by reidbarber** [comment]
As mentioned above, it looks like you’re trying to run that on a Node server. Here are some issues where people ran into the same problem for reference:

#570
#608
#558

If you are trying to use msal on a server, try the alpha version of the package mentioned above or this 1.x version: https://github.com/AzureAD/azure-activedirectory-library-for-nodejs

Otherwise, add msal-browser to the client part of your application.

**Comment by ken5scal** [comment]
IC, after changing the app to SPA, it worked fine. Thanks!
