### ISSUE TITLE
loginPopup fails in mobile safari

### ISSUE THREAD

**Issue by michaelmesser** [AzureAD/microsoft-authentication-library-for-js#2001]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.0.0-beta.4`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Description
In mobile safari `loginPopup` fails. I belief this is because `window.open` is called from async. Maybe [this](https://stackoverflow.com/questions/20696041/window-openurl-blank-not-working-on-imac-safari) could fix it?

## Error Message

popup_window_error: Error opening the popup window. This can happen if you are using IE or if popups are blocked in the browser. Details:
BrowserAuthError: empty_window_error: window.open returned null or undefined window object

## Security
- [ ] Is this issue security related? No

## Regression
- [ ] Did this behavior work before? Did not try with a previous version
Version:

## MSAL Configuration

```js
const myMSALObj = new msal.PublicClientApplication({
  auth: {
    clientId: "{}",
    authority:
      "https://login.microsoftonline.com/{}",
    redirectUri: "https://{}",
  },
  cache: {
    cacheLocation: "localStorage",
    storeAuthStateInCookie: false,
  },
});

const request = {
  scopes: ["openid", "profile", "User.Read"],
};
```

## Reproduction steps
```js
const { idToken } = await myMSALObj.loginPopup(request);
```

## Browsers/Environment
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [x] Other (Mobile Safari)

**Comment by michaelmesser** [comment]
So on mobile safari this fails:
```js
setTimeout(() => {
          window.windowRef = window.open();
          window.windowRef.location = "https://google.com";
}, 1000);
```
but this works:
```js
window.windowRef = window.open();
setTimeout(() => {
          window.windowRef.location = "https://google.com";
}, 1000);
```

Both snippets are run in an onclick handler. So this issue can be fixed.

**Comment by michaelmesser** [comment]
```javascript
const windowHack = () => {
  const old_open = window.open;
  const myWindow = window.open();
  window.open = (url, windowName, windowFeatures) => {
    myWindow.location = url;
    window.open = old_open;
    return myWindow;
  };
};
```
For anyone who is looking for an immediate solution, if I call `windowHack` before `.loginPopup` it works fine.

**Comment by jo-arroyo** [comment]
@michaelmesser Thanks for bringing this to our attention. We will look into it and follow up.

Another mitigation for this error is to call `loginRedirect` when you receive this error from `loginPopup`.

**Comment by jo-arroyo** [comment]
@michaelmesser Can you verify what version of iOS you are running, and whether popups are allowed or disallowed for Safari? This can be found in Settings > Safari.

**Comment by michaelmesser** [comment]
@jo-arroyo iOS 13.5.1 and with Block Pop-up on

**Comment by jo-arroyo** [comment]
@michaelmesser We were only able to reproduce the above error when popups were blocked for Safari. Turning off Block Popups allowed `loginPopup` to work as expected. 

However, we are investigating how we can allow `loginPopup` while still having Block Pop-ups turned on for Safari, and are taking your workaround into account.

**Comment by oscarcosta** [comment]
I'm experiencing the same behaviour on the latest Firefox.
