### ISSUE TITLE
React JS new app, wait for 2.x for auth code(PKCE) and B2C?

### ISSUE THREAD

**Issue by ivan7707** [AzureAD/microsoft-authentication-library-for-js#2003]
## Library
- [ ] `@azure/msal-browser@2.x.x`

## Description
Hello, I am starting a new application using react and will ultimately be using B2C and AD.  I currently have 1.x working using the react aad repo. 

If I am looking ultimately to use auth code with PKCE, can you give me some idea of whether I should be using the beta, start with implicit flow using 1.x (i.e. use react aad) or wait for 2.0 of MSAL to be ready? Any suggestions or timelines?

Thank you,

Ivan

**Comment by jo-arroyo** [comment]
@ivan7707 MSAL.js 2.0 was actually released yesterday! Please see [this blog post](https://developer.microsoft.com/en-us/identity/blogs/msal-js-2-0-supports-authorization-code-flow-is-now-generally-available/) for our announcement, which also has links to the quickstart and tutorial. 

However, we are still working on a CORS bug on the B2C endpoint. This is a priority for us, and we hope to have a fix available soon.

**Comment by ivan7707** [comment]
Amazing!  Thanks.  Just to be sure, you are thinking about #1795 is the issues with CORS in 2.0 with B2C?

**Comment by jo-arroyo** [comment]
@ivan7707 Yes, that's the right issue and it is being tracked and will be updated there.
