### ISSUE TITLE
Use access token in rest api calls

### ISSUE THREAD

**Issue by chigivigi** [AzureAD/microsoft-authentication-library-for-js#201]
I am working on a single page application.

Currently my application calls a custom function on page initialization that will run login and acquire access token function from the msal library. I can't use the acquireTokenPopup function because it is something that was agreed on , the acquireTokenSilent never returns successfully so I am forced to use acquireTokenRedirect. The problem is that the callback function that is called after acquireTokenRedirect is called to late and I can't use it for verification that the user is logged or getting token for the rest api header. i Am forced to use to get the verification from session storage. 

Is there another way to get the token after a successful login ?

**Comment by rohitnarula7176** [comment]
@chigivigi Since we receive every response as a redirect (302) which causes an entire reload of the app, the library is written in a certain manner. You can use the below code snippet to achieve what you have mentioned above.
```
  var applicationConfig = {
            clientID: '',
            graphEndpoint: "",
            graphScopes: []
        };
 var userAgentApplication = new Msal.UserAgentApplication(applicationConfig.clientID, null, authCallback, { cacheLocation: 'localStorage', logger: logger });
        function authCallback(errorDesc, token, error, tokenType) {
            if (token) {
                userAgentApplication.acquireTokenSilent(applicationConfig.graphScopes).then(function (accessToken) {
                    console.log(token);
                }, function (error) {
                    console.log(error);
                    userAgentApplication.acquireTokenPopup(applicationConfig.graphScopes).then(function (accessToken) {
                         console.log(token);
                    }, function (error) {
                        console.log(error);
                    });
                });
            }
            else if (errorDesc || error) {
                console.log(error + ':' + errorDesc);
            }
        }

        if (userAgentApplication && userAgentApplication.getUser() && window.parent!==window) {
            console.log(userAgentApplication.getUser());
        }
        else {
            if (userAgentApplication && window.parent === window && 
            !userAgentApplication.isCallback(window.location.hash)) {
                userAgentApplication.loginRedirect(applicationConfig.graphScopes);
            }
        }
```
The reason to check for userAgentApplication object in every if call is because the constructor function is currently asynchronous. the condition window.parent !== window

**Comment by hkusulja** [comment]
Is this possible to resolve without popup? with 302 redirect with token back to SPA angular application?

**Comment by chigivigi** [comment]
I can't use popup in my app so the acquireTokenPopup is not a solution for me, can the acquireTokenSilent be used differnty that it can return the token in success response ?

**Comment by hkusulja** [comment]
We have issues also with acquireTokenSilent , this method never returns success...
