### ISSUE TITLE
msal node missing dist folder and types entry

### ISSUE THREAD

**Issue by baywet** [AzureAD/microsoft-authentication-library-for-js#2011]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`
- [x] `@azure/msal-node@1.0.0-alpha.1`

## Framework
NodeJS + Express: you can see the code here https://github.com/microsoftgraph/nodejs-webhooks-rest-sample/tree/feature/msalnode

## Description
The package is missing the dist folder which makes it empty and unusable.
The package is missing the types entry as well as the types themselves.

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration
N/A

## Reproduction steps
[the reference on unpkg](https://unpkg.com/@azure/msal-node@1.0.0-alpha.1) gives you a 404 because the dist folder is missing.

## Expected behavior
Dist folder to be included.
Types to be configured and included for the package.

## Browsers/Environment
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by sangonzal** [comment]
@baywet Thanks for notifying us, you are right, this was a bug with the release process. The team has published v1.0.0-alpha.2, which should now work for you.

**Comment by sangonzal** [comment]
@baywet closing this issue as it's been resolved, but feel free to reopen in case of any other questions/issues.

**Comment by baywet** [comment]
thanks for the reactivity, this is better indeed. Closing

**Comment by baywet** [comment]
@sangonzal FYI only people with contrib permissions and above can reopen an issue on any given repo.
![image](https://user-images.githubusercontent.com/7905502/88095779-a5146700-cb63-11ea-89f7-7699d9a802f8.png)

**Comment by sangonzal** [comment]
@baywet Oh interesting, didn't know that was the case. I will see if we can update this setting on the repository.

**Comment by baywet** [comment]
Yeah I don't think a lot of people know that. Having joined Microsoft fairly recently it is super frustrating from the outside when people close your things and tell you to reopen of you need, but you can't.
