### ISSUE TITLE
Unable to login to angular 9 application using msal v1.3.3 in chrome incognito mode

### ISSUE THREAD

**Issue by rv90** [AzureAD/microsoft-authentication-library-for-js#2016]
Hi,

We are using msal library v1.3.3 in an angular 9 application and we are unable to login to the application in chrome incognito mode. We are using azure b2c authentication. Below is the configuration.

  auth: {
    clientId: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
    authority: 'https://login.microsoftonline.com/tfp/tenant/policyname',
    validateAuthority: true,
    redirectUri: 'http://localhost:4200/',
    postLogoutRedirectUri: 'http://localhost:4200/',
    navigateToLoginRequestUrl: true
  },
  cache: {
    cacheLocation: 'localStorage' as 'localStorage',
    storeAuthStateInCookie: isIE
  },
  system: {
    logger: new Logger(loggerCallback, {
        correlationId: '1234',
        level: LogLevel.Verbose,
        piiLoggingEnabled: true
    })
  }

We are seeing the below error.

GET: https://login.microsoftonline.com/common//discovery/instance?api-version=1.1&authorization_endpoint=https://login.microsoftonline.com/tfp/tenant/policyname/oauth2/v2.0/authorize  is a bad request

Redirect Error:  Error: could not resolve endpoints. Please check network and try again.

The same application works fine on other browsers.

The application works well in chrome incognito mode when I turn off the feature 'Block third-party cookies'.

Could someone point to a solution programmatically as we cannot ask our clients to unblock third-party cookies.

Thanks.

**Comment by corrspt** [comment]
Latest Chrome (83) blocks third party cookies by default, I think the only solution Microsoft suggests is to switch to MSAL 2.0 which implements a new authentication mechanism.

I feel your pain as well

**Comment by vlafranca** [comment]
@corrspt  How to switch to MSAL 2.0 ?

**Comment by jo-arroyo** [comment]
@rv90 Unfortunately, it is expected that the library may not work correctly when third-party cookies are disabled. MSAL.js v2.0 mitigates those issues by switching to the auth code flow. MSAL-Angular has not yet been updated to work with MSAL 2.0, so in the meantime you can switch to using MSAL 2.0 directly if you no longer want to use MSAL.js v1.3.3.

@vlafranca Here are the steps to migrate to 2.0 from 1.x: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/v1-migration.md

**Comment by vlafranca** [comment]
@jo-arroyo thx for infos, unfortunately we are using B2C tenants, and 2.0 does not support B2C yet according documentation. 
I ended up with executing `acquireTokenPopup` in case `acquireTokenSilent` fails. It's quiet a good solution as the popup has the same behavior as the iframe.

**Comment by Lexcess** [comment]
This issue is also being tracked here #2042

**Comment by jasonnutter** [comment]
Closing as a duplicate.
