### ISSUE TITLE
Does this lib support federation-based SSO from Office365 Access Panel(My Apps) 

### ISSUE THREAD

**Issue by hwangzhiming** [AzureAD/microsoft-authentication-library-for-js#202]
We created a SPA with this msal.js that supports oauth2, now we want to ask is it possible  to support federation-based SSO just by a single SPA?

**Comment by navyasric** [comment]
@hwangzhiming Is this still an issue for you? Can you clarify which Identity provider you are trying to federate sso with?
MSAL.js supports these Identity providers: Azure AD , Azure AD B2C and Microsoft accounts.

**Comment by navyasric** [comment]
Closing this issue because the OP has not responded.
