### ISSUE TITLE
Msal logout() method requires user interaction before clearing session

### ISSUE THREAD

**Issue by ken5scal** [AzureAD/microsoft-authentication-library-for-js#2024]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.0.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
@azure/msal-browser@2.0.0

## Description
According to [this page](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md) and code descriptions, MSAL is supposed to remove entire session and caches automatically by calling  `msalObj.logout();`.

But, msal object always asks to choose which account to be logged out.

![image](https://user-images.githubusercontent.com/9734362/88362418-6a0a7180-cdb7-11ea-911f-65e50dfdfd86.png)

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
const msalConfig: Configuration = {
  auth: {
    clientId: clientId,
    authority: `https://login.microsoftonline.com/${tenantId}`
  },
  cache: {
    storeAuthStateInCookie: true
  },
  system: {
            loggerOptions: {
                loggerCallback: (level, message, containsPii) => {
                    if (containsPii) {	
                        return;	
                    }
                    switch (level) {	
                        case LogLevel.Error:	
                          console.error(message);	
                            return;	
                        case LogLevel.Info:	
                            console.info(message);	
                            return;	
                        case LogLevel.Verbose:	
                            console.debug(message);	
                            return;	
                        case LogLevel.Warning:	
                            console.warn(message);	
                            return;	
                    }
                }
            }
        }
}
```

## Reproduction steps
call msalObj.logout()

## Expected behavior
logout and clear cache without any user interaction

## Browsers/Environment
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jo-arroyo** [comment]
@ken5scal Thanks for bringing this to our attention. We will look into it and follow up.

**Comment by shamprasadrh** [comment]
The behaviour is same in 1.3.X as well

**Comment by jo-arroyo** [comment]
@ken5scal @shamprasadrh Unfortunately, there is not a way in the library to bypass the account selection screen on logout. This is an improvement we would like to make, however, we do not have an ETA on when that would be available.

**Comment by jo-arroyo** [comment]
Closing as no further action for the library at this time.
