### ISSUE TITLE
Azure B2C - MSAL.js Session Behavior with Multiple Tabs

### ISSUE THREAD

**Issue by mkrrishk** [AzureAD/microsoft-authentication-library-for-js#2025]
## Library
- [x] `msal@1.3.2`

## Framework
MSAL.js - 1.3.2
Azure B2C Custom Policies
Vue.js - 2.6.10

## Description
We're using MSAL.js 1.3.2 for interacting with Azure AD B2C for a Vuejs SPA. MSAL.js config is set to use session storage for storing its cache. As per the documentation (https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-sso#sso-between-browser-tabs) session is not allowed to be shared between different tabs when using session storage. But, when a new tab is opened existing session is being used to sign in the user automatically. We've used 'prompt = login' parameter to suppress this behavior. While this helps us to ensure that the user has to sign in manually when a new tab is opened, we're now noticing an issue with token renewal.

Here's the scenario -

Login with Account 1 in the Tab 1.

Open a new tab (Tab 2) and Login with Account 2.

Now, in Tab 1 make a token renewal request using acquireTokenSilent() with client id as the scope - this is returning a new token with Account 2's Object ID as the Subject. (which means it is renewing the token for Account 2 instead of Account 1)

How do we suppress/control this behavior?

## MSAL Configuration

```js
msalConfig = {
  auth: {
   clientId: xxxx,
   authority: xxxx,
   redirectUri: xxxx,
   postLogoutRedirectUri: xxxx,
   validateAuthority: false,
   navigateToLoginRequestUrl: false,
  },
  cache: {
   cacheLocation: 'sessionStorage',
   storeAuthStateInCookie: false,
  },
};
```

## Reproduction steps
Reproduction steps are mentioned in the Description. Also, these are the session configuration settings in our B2C custom Policy
```xml
<SingleSignOn Scope="Tenant" KeepAliveInDays="1" />
<SessionExpiryType>Absolute</SessionExpiryType>
<SessionExpiryInSeconds>86400</SessionExpiryInSeconds>
```

## Expected behavior
Existing session/cookies should not be re-used in a new Tab.

## Browsers/Environment
- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jo-arroyo** [comment]
@mkrrishk Unfortunately, this is a known issue with B2C service, where `login_hint` isn't being forwarded to the B2C IDP. Please file a support ticket with the B2C team by following the instructions here: https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options

They can help you out further, they may ask for a public repro link or additional data. You can also link this Github issue in the support request.

**Comment by s2ramana** [comment]
Is there any update on this? We are also running into this issue and we are using B2C.

**Comment by jo-arroyo** [comment]
@s2ramana The B2C service has been working on this, and has some updates for custom policies, although some issues appear to remain. For help with your custom policy, please file a support ticket with the B2C team by following the instructions here: https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options
