### ISSUE TITLE
How to fetch token from cache(sessionStorage)

### ISSUE THREAD

**Issue by ktikku** [AzureAD/microsoft-authentication-library-for-js#2026]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.0.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
How can I fetch token stored in cache using `acquireTokenSilent` method?
In my case, the client is making call to the token  endpoint each time to fetch the token.

My Client configuration :

`
const config = {
      auth: {
        clientId: 'my client id',
        redirectUri: 'https://localhost:3000/auth/callback',
        authority: 'https://login.microsoftonline.com/my-tenant-id',
        navigateToLoginRequestUrl: false,
      },
      cache: {
        cacheLocation: 'sessionStorage',
        storeAuthStateInCookie: 'false',
      },
    };
`

my silent request object:
`
 var currentAccount = this.getAccountByUsername('tikku_karan@myorg.com');
      var silentRequest = {
        scopes: ['openid', 'profile', 'offline_access', 'user.read', 'email'],
        account: currentAccount,
        forceRefresh: false
    };
      const response = await this.acquireTokenSilent(silentRequest);
`

**Comment by jo-arroyo** [comment]
@ktikku What scopes are you consenting to in your initial login request? If you are silently requesting scopes that are not in the cache, it will result in a cache miss.

**Comment by ktikku** [comment]
I'm consenting the following scopes: `scopes: ['openid', 'profile', 'offline_access', 'user.read', 'email']` while login.
After login whenever I try `acquireTokenSilent`, it results in a cache miss and it fetches the token from the token endpoint.

**Comment by ktikku** [comment]
okay, it's working as expected now.
Thank you!

**Comment by ktikku** [comment]
> okay, it's working as expected now.
> Thank you!

@jo-arroyo 
Whenever I provide `offline_access` as a required scope, it results in cache miss, and fetches token from the token end point.

**Comment by jo-arroyo** [comment]
@ktikku Can you tell us what happens when you don't provide `offline_access`?

**Comment by ktikku** [comment]
@jo-arroyo When I don't provide `offline_access` while logging in, calling `acquireTokenSilent` returns the access token from the cache, sessionStorage in my case.

**Comment by jo-arroyo** [comment]
@ktikku Thanks for responding. The behavior you are seeing is expected behavior. We are recommending that you do not provide `offline_access` as a scope anymore both in the initial login request and `acquireTokenSilent`. It is no longer a supported scope as it is meant for long-lived refresh tokens which are not supported in single-page applications. Removing `offline_access` will have `acquireTokenSilent` working as expected.

**Comment by ktikku** [comment]
Thanks @jo-arroyo for the clarification.
