### ISSUE TITLE
msal-browser should have an option not to store access token/refresh token

### ISSUE THREAD

**Issue by ken5scal** [AzureAD/microsoft-authentication-library-for-js#2027]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.0.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
If the purpose of msal-browser is only for OIDC Federated login, then access token and refresh token doesn't really have a use.
In such cases, those tokens are desirable not to be stored in any browser cache, because they are inherently vulnerable to attacks such as XSS. Maybe supporting  `response_type=id_token` or utility that enables us to delete certain caches help.

**Comment by jo-arroyo** [comment]
@ken5scal msal-browser is meant to support authentication code flow for single-page applications. If you are looking for federated login and you don't need the access token, msal-core uses the implicit flow and supports that. However, customized storage for msal-browser is something that we are looking into.

**Comment by ken5scal** [comment]
@jo-arroyo thanks for your response. I understood.
