### ISSUE TITLE
Authorization Request always come with scopes = [openid profile] even though specifying scopes = [] in the code

### ISSUE THREAD

**Issue by ken5scal** [AzureAD/microsoft-authentication-library-for-js#2031]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.0.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework
@azure/msal-browser@2.0.0

## Description
Request objects without scopes defined construct authorization requests having `scope=[opened profile]` parameter.

```
https://login.microsoftonline.com/{masked-tenant-id}/oauth2/v2.0/authorize?client_id={masked-client-id}&scope=openid%20profile&redirect_uri=http%3A%2F%2Flocalhost%3A30662%2F&client-request-id={masked-client-request-id}&response_mode=fragment&response_type=code&x-client-SKU=msal.js.browser&x-client-VER=2.0.0&x-client-OS=&x-client-CPU=&client_info=1&code_challenge={some-pkce-code-challenge}
```

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
const MSAL_CONFIG: Configuration = {
    auth: {
        clientId: clientId,
        authority: `https://login.microsoftonline.com/${tenantId}`
    },
    cache: {
        cacheLocation: "sessionStorage", // This configures where your cache will be stored
        storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
    },
    system: {
        loggerOptions: {
            loggerCallback: (level, message, containsPii) => {
                if (containsPii) {	
                    return;	
                }	
                switch (level) {	
                    case LogLevel.Error:	
                        console.error(message);	
                        return;	
                    case LogLevel.Info:	
                        console.info(message);	
                        return;	
                    case LogLevel.Verbose:	
                        console.debug(message);	
                        return;	
                    case LogLevel.Warning:	
                        console.warn(message);	
                        return;	
                }
            }
        }
    }
};
```

## Reproduction steps
1. `git clone https://github.com/AzureAD/microsoft-authentication-library-for-js.git`
2. modify line of codes specify scope to `scopes: []` in `samples/msal-browser-samples/TypescriptTestApp2.0`
3. run `samples/msal-browser-samples/TypescriptTestApp2.0` with  `yarn start`

## Expected behavior
either...
1. constructs authorization request with specified scopes
2. improve documents that explicitly define mandated scopes value.

## Browsers/Environment
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jo-arroyo** [comment]
@ken5scal Adding openid and profile to scopes is expected behavior, and we are currently working on adding documentation that explains this.

**Comment by jasonnutter** [comment]
Closing, see here: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md#im-seeing-scopes-openid-profile-email-offline_access-and-userread-in-my-tokens-even-though-i-havent-requested-them-what-are-they
