### ISSUE TITLE
MSAL-Angular JS logout not working as expected

### ISSUE THREAD

**Issue by harinivedala** [AzureAD/microsoft-authentication-library-for-js#2034]
We recently had to update our forms based authentication to use MSAL-AngularJS to authenticate against Azure AD in a production application for various reasons. We also have a requirement to enable 15 minute user inactivity session timeout. I used the ng-idle plugin to go about it. It is working as expected, except that the auto logout functionality is displaying a window that displays the signed in users for the user to select. I was expecting that if I used msalAuthenticationService.logout() method, it would take care of logging out the user completely without presenting any window to the user. This is very important for our application.  If the user does not select anything, the user remains logged in which is not acceptable in our situation.

We greatly appreciate your help!!

**Comment by jo-arroyo** [comment]
Closing as is duplicate.
