### ISSUE TITLE
Msal-AngularJS logout is not working as expected

### ISSUE THREAD

**Issue by harinivedala** [AzureAD/microsoft-authentication-library-for-js#2035]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [x] `@azure/msal-angular@0.2.2`
- [ ] `@azure/msal-angular@1.x.x`
- [x] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
Angular JS 1.7

## Description
We recently had to update our forms based authentication to use MSAL-AngularJS to authenticate against Azure AD in a production application for various reasons. We also have a requirement to enable 15 minute user inactivity session timeout. I used the ng-idle plugin to go about it. It is working as expected, except that the auto logout functionality is displaying a window that displays the signed in users for the user to select. I was expecting that if I used msalAuthenticationService.logout() method, it would take care of logging out the user completely without presenting any window to the user. This is very important for our application. If the user does not select anything, the user remains logged in which is not acceptable in our situation.

We greatly appreciate your help!!

## Error Message
No error but the user is presented with a dialog to select the user to logout. In our case, it is just one user. I thought that the behavior would be to logout the user completely with no user interaction.

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:
```
## MSAL Configuration
$locationProvider.html5Mode(false).hashPrefix('');
        msalAuthenticationServiceProvider.init({
            clientID: applicationConfig.clientID,
            authority: 'https://login.microsoftonline.com/ourtenantId',
            tokenReceivedCallback: function (errorDesc, token, error, tokenType) {
                if (token) {
                    //console.log("token received: in callback " + token)
                } else if (error) {
                    console.log("error received: in callback " + error)
                }
            },
            optionalParams: {
                cacheLocation: 'localStorage',
                // logger: logger,
                validateAuthority: true,
                redirectUri: window.location.origin,
                postLogoutRedirectUri: serviceBase + '/app/auth/logout.html',
                navigateToLoginRequestUrl: false,
                unprotectedResources: [],
                protectedResourceMap: protectedResourceMap,
                storeAuthStateInCookie: false
            },
            routeProtectionConfig: {
                popUp: false,
                consentScopes: applicationConfig.consentScopes,
                
            }
        }, $httpProvider);

// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
msalAuthenticationService.authority = "https://login.microsoftonline.com/ourtenantid";
msalAuthenticationService.logout();

```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Expected behavior
No user interaction when logging out.

## Browsers/Environment
- [*] Chrome
- [ ] Firefox
- [*] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jasonnutter** [comment]
@harinivedala Unfortunately, there is currently not a way to automatically bypass the account selection screen during logout. This is being considered for AAD, however, we do not have an ETA on when it will be available in the library. Also, please note that MSAL AngularJS is in maintenance, and will not receive any new features. We highly recommend upgrading to the latest version of MSAL.js to get the latest features.

Closing, as no further action.
