### ISSUE TITLE
The TypeScript sample app doesn't start due to lack of exported function

### ISSUE THREAD

**Issue by stephlocke** [AzureAD/microsoft-authentication-library-for-js#2040]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.0.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework
Vanilla install of npm & node 12 lts on wsl

## Description
Trying to run the TypeScript sample results in an error 
## Error Message
```
> typescript-test-app-2.0@1.0.0 build /home/steph/microsoft-authentication-library-for-js/samples/msal-browser-samples/TypescriptTestApp2.0
> tsc && npm run build:babel && npm run build:webpack && npm run clean:build

src/AuthModule.ts:1:60 - error TS2305: Module '"../node_modules/@azure/msal-browser/dist/src"' has no exported member 'SilentFlowRequest'.

1 import { PublicClientApplication, AuthorizationUrlRequest, SilentFlowRequest, AuthenticationResult, Configuration, LogLevel, AccountInfo, InteractionRequiredAuthError, EndSessionRequest, RedirectRequest, PopupRequest } from "@azure/msal-browser";
```

## MSAL Configuration
No config - just basic launching

## Reproduction steps
```bash
git clone https://github.com/AzureAD/microsoft-authentication-library-for-js
cd microsoft-authentication-library-for-js
typescript-test-app-2.0@1.0.0 build
```

## Expected behavior
Should build and run

## Browsers/Environment
N/A

**Comment by jo-arroyo** [comment]
@stephlocke Thanks for bringing this to our attention. We are working on correcting this and will follow up.
