### ISSUE TITLE
How do you get the ID Token ?

### ISSUE THREAD

**Issue by madwomanx** [AzureAD/microsoft-authentication-library-for-js#2041]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

I know you can get access tokens with `aquireTokenSilent` , but how do you get the ID token? I can get it after login with `handleRedirectPromise`, but when the user is logged in, this promise resolves `null`?

**Comment by jo-arroyo** [comment]
@madwomanx An idToken can be obtained with `acquireTokenSilent` by passing in `openid` and `profile` as scopes. This will cause `acquireTokenSilent` to respond with both the graph access token as well as an idToken, as any call that has `openid` and `profile` as scopes will receive an idToken for the user. Please see our docs on this topic [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/request-response-object.md#scopes).
