### ISSUE TITLE
"@azure/msal-angular" has missing dependencies msal

### ISSUE THREAD

**Issue by HadyAllam** [AzureAD/microsoft-authentication-library-for-js#2043]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [X ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.
@azure/msal: "^1.3.1"
@azure/msal-angular: ^1.0.0
## Framework
Angular CLI: 9.1.11
Node: 12.16.2
OS: win32 x64
Angular: 9.1.12

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.11
@angular-devkit/build-angular     0.901.11
@angular-devkit/build-optimizer   0.901.11
@angular-devkit/build-webpack     0.901.11
@angular-devkit/core              9.1.11
@angular-devkit/schematics        9.1.11
@angular/cdk                      9.2.4
@angular/cli                      9.1.11
@angular/material                 9.2.4
@ngtools/webpack                  9.1.11
@schematics/angular               9.1.11
@schematics/update                0.901.11
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

## Description
After importing MsalModule and set the default configurations. try to build the app using ng serve or ng build --prod it will fail 
## Error Message

ERROR in The target entry-point "@azure/msal-angular" has missing dependencies:
 - msal

## Security
- [ ] Is this issue security related?

## Regression
- [X ] Did this behavior work before? 
Version:

## MSAL Configuration
MsalModule.forRoot({
      auth: {
        clientId: 'clientId',
        authority: 'tenant',
        redirectUri: 'redirectUri',
      },
      cache: {
        cacheLocation: 'localStorage',
        storeAuthStateInCookie: isIE, // set to true for IE 11
      },
    },
    {
      popUp: !isIE,
      consentScopes: [
        'user.read',
        'openid',
        'profile'
      ],
      unprotectedResources: [],
      protectedResourceMap: [
        ['https://graph.microsoft.com/v1.0/me', ['user.read']]
      ],
      extraQueryParameters: {}
    })
```js

```

## Reproduction steps
```js
After importing MsalModule and set the default configurations. try to build the app using ng serve or ng build --prod it will fail
```

## Browsers/Environment
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jo-arroyo** [comment]
@HadyAllam This is expected behavior as MSAL.js is a peer dependency of `@azure/msal-angular`, which means your application needs to install `msal` directly. When you install `@azure/msal-angular`, you should install msal at the same time. https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-angular#installation
