### ISSUE TITLE
protecteResourceMap replacement in msal-browser 

### ISSUE THREAD

**Issue by AndriiDidkivsky** [AzureAD/microsoft-authentication-library-for-js#2047]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
I'm working on migration angular project from msal-core to msal-browser. 
Does msal-browser suggest something instead of protectedResourceMap because i can't find something similar in the documetation. 
Should I work on some code to cover this logic ?

**Comment by jo-arroyo** [comment]
@AndriiDidkivsky msal-browser does not have an API for `protectedResourceMap`, so you will need to implement this logic yourself until we are able to upgrade msal-angular to use MSAL.js 2.0.
