### ISSUE TITLE
CORS-related error when returning back from B2C sign in policy page

### ISSUE THREAD

**Issue by Codeluck** [AzureAD/microsoft-authentication-library-for-js#2051]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.0.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
I've got CORS-related error when getting back from Azure AD B2C sign in policy page. I think the system is trying to retrieve token but CORS is blocking it for some reason. Do you know any reasons for that? Thanks!

## Error Message
`(Access to fetch at 'https://mytenant.b2clogin.com/mytenant.onmicrosoft.com/b2c_1_signupin/oauth2/v2.0/token' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.)`

## Security
- [x] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```
const msalConfig: Configuration = {
    auth: {
      clientId: 'xxx-xxxx-xxxx-xxx',
      authority: "https://mytenant.b2clogin.com/tfp/mytenant.onmicrosoft.com/b2c_1_signupin",
      redirectUri: 'http://localhost:3000', 
      knownAuthorities: ["mytenant.b2clogin.com"]
    },
    cache: {
      cacheLocation: 'localStorage', 
      storeAuthStateInCookie: false
    },
    system: {
        tokenRenewalOffsetSeconds: 0,
        loadFrameTimeout: 9000,
        loggerOptions: {
          loggerCallback: msalLoggerCallback,
          logLevel: LogLevel.Verbose
        }
    }
  };
```
// Provide configuration values here.

// For Azure B2C issues, please include your policies.
```
Standard sign in policy using Azure AD B2C account
```

## Expected behavior
Token should be retrieved.

## Browsers/Environment
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jo-arroyo** [comment]
@Codeluck Unfortunately, this is a known issue. We are currently prioritizing and working on a fix. Please refer to [our wiki page](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL-browser-B2C-CORS-issue) for timelines and to issue #1795 for further details and updates.
