### ISSUE TITLE
ReferenceError: window is not defined break SSR

### ISSUE THREAD

**Issue by mbrevda** [AzureAD/microsoft-authentication-library-for-js#2052]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
n/a
## Description
When trying to SSR the code, `window` not being defined causes the SSR to fail

## Error Message
```
ReferenceError: window is not defined
    at Function.BrowserUtils.getBrowserNetworkClient (PATH_TO_PROJECT/node_modules/@azure/msal-browser/src/utils/BrowserUtils.ts:67:9)
```
## Security
- [ ] Is this issue security related?

## Regression
- [x] Did this behavior work before? 
Version:
1.3
## MSAL Configuration

n/a

## Reproduction steps
import MSAL and try SSR'ing

## Expected behavior
the code should be more sensitive to `window` not being defined

## Browsers/Environment
node. Yes, I know this a browser-based package, trying to SSR for the browser! Perhaps delaying the call that checks for `window` (or probably `fetch`) until runtime would help.

Thanks!

**Comment by jo-arroyo** [comment]
@mbrevda This is a known issue that we intend to fix. We will follow up when we have done so.

**Comment by mbrevda** [comment]
I hate to ask, but can you give a unit of measure for an ETA (days/weeks/months)?

**Comment by jo-arroyo** [comment]
@mbrevda Unfortunately, we are not able to give a more specific timeline yet, but we would like to have this fixed soon.

**Comment by jasonnutter** [comment]
@mbrevda There is now a PR open to fix this scenario, and will be included in an upcoming release of MSAL.js v2. This issue will be updated when that PR has been accepted and merged.

**Comment by mbrevda** [comment]
I saw, thanks for pointing it out! Looking forward to the release
