### ISSUE TITLE
Fix function signatures for getAllAccounts and getAccountByUsername

### ISSUE THREAD

**Issue by jasonnutter** [AzureAD/microsoft-authentication-library-for-js#2053]
Please follow the issue template below. 

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Upcoming Library
- [ ] `@azure/msal-node@1.x`

## Source
- [x] Internal (MSAL.js team)
- [ ] Customer request

## Description

Today, the signatures for `PublicClientApplication.getAllAccounts` and `PublicClientApplication.getAccountByUsername` do not indicate that these methods can return `null`.

## Priority

Medium

## Acceptance Criteria

1. `PublicClientApplication.getAllAccounts` and `PublicClientApplication.getAccountByUsername` return types are updated to indicate they can return `null`.

**Comment by aappddeevv** [comment]
Wow! I just hit this 1 hour ago but you already had this issue created. Thanks!
