### ISSUE TITLE
MSAL.js 2.0 Support for Azure B2C

### ISSUE THREAD

**Issue by toddfsnyder** [AzureAD/microsoft-authentication-library-for-js#2057]
## Library
- [X] `@azure/msal-browser@2.x.x`

## Description
Looking for clarification and timeline for when MSAL.js 2.0 will support Azure B2C. We were under the impression this was going to be supported in the MSAL.js 2.0 release. The documentation says otherwise: Important: MSAL.js 2.0 with Authorization Code Flow is not yet available for B2C tenants (coming soon).

**Comment by jo-arroyo** [comment]
@toddfsnyder We are currently prioritizing and working on a fix. Please refer to [our wiki page](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL-browser-B2C-CORS-issue) for the estimated timeline and to issue #1795 for further details and updates.
