### ISSUE TITLE
Obtain Access Token on Login

### ISSUE THREAD

**Issue by spottedmahn** [AzureAD/microsoft-authentication-library-for-js#206]
Please allow for obtaining an access token on login.  Currently, one can only obtain the `id_token` during login.

`response_type=id_token token`

**Comment by rohitnarula7176** [comment]
@spottedmahn This particular case has been discussed within our team. The sole purpose of login is to recieve an id_token which is meant for proving to a Client that the user has authenticated, and who they are as a result. The response type 'id_token token' would receive both an id_token and an access_token which would work for the case when you have a single resource but it limits the case when there are multiple resources for which you intend to acquire an access_token and as you can only request one access_token per request. The other reason for not including this response_type is that it would lead to a lot of data on the wire as now you will receive two tokens which might cause problems across old browsers. Can you explain why you need to pass this responseType.

**Comment by spottedmahn** [comment]
Hi Rohit - as it stands now, we're facing timeout issues obtaining access tokens (because the iframe is loading our Angular app and we have a lot of stuff on startup).  By obtaining an access token on login, we would be able to work-around our time-out issues.

Even w/o the time-out issue, it would just be more efficient.  Why make 2 calls when you can make one? 😄 

Also, we only have one resource at this point in time so it would work for us.

**Comment by rohitnarula7176** [comment]
@spottedmahn The case where we receive both an id_token and an access_token would  break in older browsers because of exceeding the URL length limit and this would break a lot of our customers. So our team has decided to not support this responseType at login. The ability to alter the loadFrameTimeout would take care of the timeout issues for you. Closing this issue for now.

**Comment by spottedmahn** [comment]
Hi @rohitnarula7176 - thanks for the update.

1. Shouldn't it be the consumer of the library that makes the decision, not the library 😄 ?
1. If [`acquireTokenSilent`](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/208#issuecomment-359569114) will allow both values to be sent then that will brake older browsers.  So if breaking the browser is the reason not to do this then that is violated with `acquireTokenSilent` 😄.  Why let one part of the library to do it and not another part?  Seems like an inconsistency, maybe I'm missing something though.

**Comment by spottedmahn** [comment]
Hi @rohitnarula7176 - can you please re-open this?  I suspect you [missed this reply](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/206#issuecomment-359572166).

Thanks again for all your help.

**Comment by spottedmahn** [comment]
Hi @rohitnarula7176 - any updates?

**Comment by spottedmahn** [comment]
Hi @rohitnarula7176 - any updates?

**Comment by spottedmahn** [comment]
Any thoughts 💭?

**Comment by navyasric** [comment]
@spottedmahn Thanks for your thoughts on this scenario. We do not plan to support this scenario in our current roadmap. Due to reasons above this will need investigation and we will consider in our future backlog. Closing issue for now.

**Comment by spottedmahn** [comment]
Hi @navyasric - did you read [this comment](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/206#issuecomment-359572166)?  The library already does this in parts of it!
