### ISSUE TITLE
MSAL(@1.3.3)'s  acquireToken not  sets UPN to X-MS-client-principal-name.

### ISSUE THREAD

**Issue by master-maintenance1-peer-connect** [AzureAD/microsoft-authentication-library-for-js#2069]
When I upgraded to MSAL@1.3.3, my program didn't work well.
I also confirmed that the avoidance action is to version down to msal@1.3.2.
I seem to have encountered some incompatible change.
As before, MSALl@2 and MSAL@1.3.3 and later versions provide a configuration method that allows  to set "UPN" for "X-MS--client-principal-name".

## Library
- [v ] `msal@1.3.3`

## Framework
 * -- Client SPA
     * TypeScript@3.8.3,
     *  react@16.13.1,
  * -- Azure Functions
     *  "@azure/functions": "^1.2.2",
``` 
   Project Sdk="Microsoft.NET.Sdk"
     TargetFramework>netstandard2.0</TargetFramework
    ItemGroup
       PackageReference Include="Microsoft.Azure.WebJobs.Extensions.CosmosDB" Version="3.0.7" 
      PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="1.8.5"
      PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.11" 
      PackageReference Include="Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator" Version="1.0.2"
```

## Description
I have created a function app for the http trigger that authenticates with Azure AD UserPrincipalName in the Azuer function environment.
When the function kicks the URL from the browser, the UserPrincipalName arrives and it authenticates correctly.
However, if you acquire a token from MSAL.js, you will get a short name instead of UserPrincipalName, resulting in http 401 error unautolize.

![x-MS-CLIENT-PRINCIPAL-NAME-not-UPN1](https://user-images.githubusercontent.com/64691446/88884476-a33c5900-d271-11ea-9c52-84002c0b1e72.png)

## Error Message
       * HTTP Status Code: 401 Unauthorized
　　* MSAL samplle apps Error message: Unable to acquire access token for get ResourceKeys.

## Security
- [v ] Is this issue security related?
   Setting'x-MS-CLIENT-PRINCIPAL-NAME' to a shorter name than UserPrincipalName facilitates impersonation.

## Regression
- [v ] Did this behavior work before? 
Version: msal@1.3.2 
     * msal@1.2
     * https://alcdn.msauth.net/lib/1.2.1/js/msal.js

## MSAL Configuration

```js
// Provide configuration values here.
```js
// Provide relevant code snippets here.
export const GRAPH_SCOPES = {
    OPENID: "openid",
    PROFILE: "profile",
    USER_READ: "User.Read",
    MAIL_READ: "Mail.Read",
    RESOURCEKEYS: [
        "api://d1789387-f340-464a-ace5-1df84244b661/User.Read",    // "http://supportersystem-demo1-makedataactivity2.kazumatakedapeerconnectcojp.onmicrosoft.com/User.Read"
        "api://d1789387-f340-464a-ace5-1df84244b661/user_impersonation"  // "http://supportersystem-demo1-makedataactivity2.kazumatakedapeerconnectcojp.onmicrosoft.com/user_impersonation"
    ]
};

export const GRAPH_ENDPOINTS = {
    ME: "https://graph.microsoft.com/v1.0/me",
    MAIL: "https://graph.microsoft.com/v1.0/me/messages",
    RESOURCEKEYS:
        "https://supportersystem-demo1-makedataactivity2.azurewebsites.net/api/WebApps_getResourceKeys1?tenantName=%E3%83%94%E3%82%A2%E3%82%B3%E3%83%8D%E3%82%AF%E3%83%88%E3%81%AE%E5%BE%8C%E6%8F%B4%E4%BC%9A&code=?????????????????????????????????????????"
};

export const GRAPH_REQUESTS = {
    LOGIN: {
        scopes: [
            GRAPH_SCOPES.OPENID,
            GRAPH_SCOPES.PROFILE,
            GRAPH_SCOPES.USER_READ,
            ...GRAPH_SCOPES.RESOURCEKEYS
        ]
    },
    EMAIL: {
        scopes: [
            GRAPH_SCOPES.MAIL_READ
        ]
    },
    RESOURCEKEYS: {
        scopes: [...GRAPH_SCOPES.RESOURCEKEYS]
    }
};

export const msalApp = new UserAgentApplication({
    // export const msalApp = new msal.PublicClientApplication({
    auth: {
        clientId:
            "d1789387-f340-464a-ace5-1df84244b661",
        authority:
            "https://login.microsoftonline.com/common",
        redirectUri:
            window.location.protocol + "//" + window.location.hostname + ":" + window.location.port + "/" + "auth.html" // :
        // "https://supportersystem-demo1-makedataactivity2.azurewebsites.net/.auth/login/aad/callback"
        //  このcallbackを指定すると、下記URLが開いたままとなった。 auth.htmlでも認証状態は保持できた。
        //  https://supportersystem-demo1-makedataactivity2.azurewebsites.net/.auth/login/done
        // )
        ,
        validateAuthority: true,
        postLogoutRedirectUri: this_first_URL1, // document.URL,
        navigateToLoginRequestUrl: true
    },
    cache: {
        cacheLocation: "sessionStorage",
        storeAuthStateInCookie: isIE()
    },
    system: {
        navigateFrameWait: 500,
        logger: new Logger((logLevel: any, message: string) => {
            console.log(message);
        }),
        telemetry: {
            applicationName: "supportrt Association demo app",
            applicationVersion: "1.0.0",
            telemetryEmitter: (events: object) => {
                console.log('Telemetry Events:', events);
            }
        }
    }
});

```

## Azure functions/Microsoft_AAD_RegisteredApps manifest

![UPN-setting5](https://user-images.githubusercontent.com/64691446/88939233-3badfa00-d2c1-11ea-99e8-3c4e5fbd296f.png)

## Reproduction steps
After signing on using MSAL.js, the URL of the http trigger function of Azure function was fetched using the token obtained from msalApp.acquireTokenSilent.

    When you look at the request header that arrived at the http trigger function of that Azure function, the name is set instead of the UPN.

## Expected behavior
    When the URL of the http trigger function of the Azure function is kicked from the browser, UPN is set in the request header that reaches the Azure function. I expect that similar values will be set via MSAL.js.

![x-MS-CLIENT-PRINCIPAL-NAME-is-UPN2](https://user-images.githubusercontent.com/64691446/88884522-c36c1800-d271-11ea-87d4-f0d33ec63865.png)

## Browsers/Environment
- [v ] Chrome
- [ v] Edge

**Comment by jasonnutter** [comment]
@master-maintenance1-peer-connect Can you please clarify if this behavior happens using 1.2 today?

**Comment by master-maintenance1-peer-connect** [comment]
@jasonnutter 
MSAL@1.2.2  worked well.
MSAL@1.3.2  worked well.
MSAL@1.3.3 Do NOT worked well.

**Comment by rfink** [comment]
Having this issue as well

**Comment by technical-boy** [comment]
Hi, @master-maintenance1-peer-connect. Could you please clarify the 'x-MS-CLIENT-PRINCIPAL-NAME' header is being set?

**Comment by master-maintenance1-peer-connect** [comment]
@rfink Thank you for checking the reproducibility.

＠technical-boy　Here's the request header when it works.
I can't set anything directly to 'x-MS-CLIENT-PRINCIPAL-NAME' header.
The 'x-MS-CLIENT-PRINCIPAL-NAME' header is set to the INVALID value that is not in UPN (USER PRINCIPAL-NAME) by something that MSAL.js@1.3.3 passed to Azure Function.

```
  req:
   Request {
     method: 'GET',
     url:
      'http://supportersystem-demo1-makedataactivity2.azurewebsites.net/api/WebApps_getResourceKeys1?tenantName=%E3%83%94%E3%82%A2%E3%82%B3%E3%83%8D%E3%82%AF%E3%83%88%E3%81%AE%E5%BE%8C%E6%8F%B4%E4%BC%9A&code=5KTWXP4BvexMSq2bpAcGahWGXWs3GGIjLbadL1euTuGDCCbeXTLBCw==',
     originalUrl:
      'http://supportersystem-demo1-makedataactivity2.azurewebsites.net/api/WebApps_getResourceKeys1?tenantName=%E3%83%94%E3%82%A2%E3%82%B3%E3%83%8D%E3%82%AF%E3%83%88%E3%81%AE%E5%BE%8C%E6%8F%B4%E4%BC%9A&code=5KTWXP4BvexMSq2bpAcGahWGXWs3GGIjLbadL1euTuGDCCbeXTLBCw==',
     headers:
      { connection: 'Keep-Alive',
        accept: '*/*',
        'accept-encoding': 'gzip, deflate, br',
        'accept-language': 'ja, en-US; q=0.9, en; q=0.8',
        authorization:
         'Bearer eyJxxxxxxxxxxx',
        host: 'supportersystem-demo1-makedataactivity2.azurewebsites.net',
        'max-forwards': '10',
        referer:
         'https://supportersassociation-demo1-web-svc-d2.azurewebsites.net/demo1/index.html',
        'user-agent':
         'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36',

        'x-original-url':
         '/api/WebApps_getResourceKeys1?tenantName=%E3%83%94%E3%82%A2%E3%82%B3%E3%83%8D%E3%82%AF%E3%83%88%E3%81%AE%E5%BE%8C%E6%8F%B4%E4%BC%9A&code=5KTWXP4BvexMSq2bpAcGahWGXWs3GGIjLbadL1euTuGDCCbeXTLBCw==',
        'x-forwarded-for': '58.0.32.7:64082',
        'x-arr-ssl':
         '2048|256|C=US, S=Washington, L=Redmond, O=Microsoft Corporation, OU=Microsoft IT, CN=Microsoft IT TLS CA 5|CN=*.azurewebsites.net',
        'x-forwarded-proto': 'https',
        'x-appservice-proto': 'https',
        'x-forwarded-tlsversion': '1.2',
        'x-ms-client-principal-name':
         'master-maintenance2@kazumatakedapeerconnectcojp.onmicrosoft.com',
        'x-ms-client-principal-id': 'f2cddec7-8438-487f-873f-8296ef73f96a',
        'x-ms-client-principal-idp': 'aad',
        'x-ms-client-principal':         'xxxxx',
        'request-id': '|8dc61940-444c4fe33cf6b260.1.' },

```

**Comment by master-maintenance1-peer-connect** [comment]
Please tell me,
What should be tracked back in MSAL authentication flow to determine the cause of this Issue?

Now I saw the difference in cookie values using Azure functions ".auth/me" endpoint.

* cookie  When it dosn't Work:
  Cookie.user_name(== 'x-MS-CLIENT-PRINCIPAL-NAME') Equal to Cookie.user_claims.name(Short Name).
![cookie-ng_userId1](https://user-images.githubusercontent.com/64691446/90648242-3e728e00-e274-11ea-8d03-0040620fe87c.png)

* cookie  When it  Work well:
  Cookie.user_name(== 'x-MS-CLIENT-PRINCIPAL-NAME') Equal to Cookie.user_claims.preferred_username(Long Name).
![cookie-ok_userId2](https://user-images.githubusercontent.com/64691446/90648344-5e09b680-e274-11ea-9f03-59c5bebe4d55.png)

**  Perhaps the whims of user_id (='x-MS-CLIENT-PRINCIPAL-NAME') are related to Azure functions token configuration.
![token-config3](https://user-images.githubusercontent.com/64691446/90648625-b93ba900-e274-11ea-9c52-726bbca57285.png)

** Or maybe openID_configlation(isser) is involved.
![openid_conf4](https://user-images.githubusercontent.com/64691446/90648791-f011bf00-e274-11ea-80eb-b52a1d0f970c.png)
