### ISSUE TITLE
Token Renewal Timeout Failure In IE 11 For Social Provider

### ISSUE THREAD

**Issue by mikelunn** [AzureAD/microsoft-authentication-library-for-js#207]
Using msal 1.3 i'm receiving a timeout error after authenticating to the google provider and then calling acquireTokenSilent. This doesn't occur in other browsers. Also, acquireTokenSilent works when authenticating to the local azure b2c provider. I have loaded bluebird.js as documented in the docs. The complete error thrown is "Token renewal operation failed due to timeout: null"

**Comment by rohitnarula7176** [comment]
@mikelunn Can you please elaborate on the exact repro steps for the above scenarion or provide us with a code repro. Can you confirm if your facing this issue with previous versions of msal?

**Comment by mikelunn** [comment]
@rohitnarula7176 Social login ended up not being a requirement for the project i'm working on. If I get time to experiment with social login, and I run into this issue again I will reopen
