### ISSUE TITLE
state expected : null: MSAL breaks when user clicks back button without logging in

### ISSUE THREAD

**Issue by jaslloyd** [AzureAD/microsoft-authentication-library-for-js#2071]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [X] `msal@1.x.x` or `@azure/msal@1.x.x` (1.3.3)
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework

None

## Description

Having inProgress in the caches breaks  Msal.UserAgentApplication

## Error Message
```
Uncaught (in promise) ClientAuthError: Invalid state. http://localhost:3000/home, state expected : null.
    at ClientAuthError.AuthError [as constructor] (http://localhost:3000/Users/jason/src/error/AuthError.ts:25:1)
    at new ClientAuthError (http://localhost:3000/Users/jason/src/error/ClientAuthError.ts:107:1)
    at Function.ClientAuthError.createInvalidStateError (http://localhost:3000/Users/jason/src/error/ClientAuthError.ts:151:1)
    at Function.RequestUtils.parseLibraryState (http://localhost:3000/Users/jason/src/utils/RequestUtils.ts:189:1)
    at AuthCache.resetTempCacheItems (http://localhost:3000/Users/jason/src/cache/AuthCache.ts:135:1)
    at Function.WindowUtils.checkIfBackButtonIsPressed (http://localhost:3000/Users/jason/src/utils/WindowUtils.ts:331:1)
    at new UserAgentApplication (http://localhost:3000/Users/jason/Documents/src/UserAgentApplication.ts:243:1)
```

## Security
- [ ] Is this issue security related? - No

## Regression
- [ ] Did this behavior work before? 
Version: We are migrating from adal-angular and it worked fine there

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
const msalConfig: Msal.Configuration = {
  auth: {
    authority: 'https://login.microsoftonline.com/<our_tenant>',
    clientId: CLIENT_ID,
    navigateToLoginRequestUrl: false,
    redirectUri: window.location.origin + '/auth_redirect',
  },
  cache: {
    cacheLocation: 'localStorage',
  },
};

// My stack tracks breaks on this line...
const msalInstance = new Msal.UserAgentApplication(msalConfig);

msalInstance.handleRedirectCallback((err, resp) => {
  console.warn(err, resp);
  if (resp.accountState) {
    // Redirect user back to URl where they were.
    window.location.href = resp.accountState;
  }
});


function renewAuthToken() {
  msalInstance.loginRedirect({
    state: window.location.href,
    scopes: [`${CLIENT_ID}/.default`],
  });
}

export async function getToken() {
  const userAccount = msalInstance.getAccount();
  console.log(userAccount);
  if (userAccount) {
    try {
      // Get cached token or refresh if required
      const token = await msalInstance.acquireTokenSilent({
        scopes: [
          `${CLIENT_ID}/.default`,
        ],
        account: userAccount,
      });
      console.log(token);
      return Promise.resolve(token.accessToken);
    } catch (err) {
      // If we cannot do it silently we have to do a redirect
      if (err.name === 'InteractionRequiredAuthError') {
        renewAuthToken();
      }
    }
  } else {
    if (!msalInstance.getLoginInProgress()) {
      renewAuthToken();
    }
  }
}
```

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

1. User loads our site, MSAL sees user is not logged in so redirects to microsoft
2. User for whatever reason doesn't understand why they go redirected and go back to the application in same tab or same browser session or even click the back button
3. MSAL breaks with Invalid state error above

## Expected behavior

It should realize the user is coming back, delete the localStorage / cookies inProcess state and start the auth process again so avoid crashing. You can do a very awful hack to clear the localStorage and reload the window e.g:
```js
let msalInstance;
try {
  msalInstance = new Msal.UserAgentApplication(msalConfig);
} catch (e) {
  
  localStorage.clear();
  window.location.reload();
}
```

It seem like the library has. code to handle back button presses e.g WindowUtils.checkIfBackButtonIsPressed but it is not working.
## Browsers/Environment
- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by tnorling** [comment]
@jaslloyd Thanks for bringing this to our attention. Looks like this is indeed a bug when providing a custom `state` in the request. We'll work on a fix but for now, in your scenario shown above, a workaround may be to not implement your own redirection logic and let the library do so. 

Instead of passing in the current page to the `state` parameter you can set `navigateToLoginRequestUrl: true` in `msalConfig.auth` and the library should handle redirecting you back to the calling page after reaching the configured `redirectUri`. We will update here when we have a fix available.

**Comment by gavinbarron** [comment]
Adding a second data point on this issue. Reproduction on Edge 86.0.587.0 (Official build) dev (64-bit)

Updated from 1.2.2 to 1.3.2 yesterday and noticed this immediately in development.

For us the workaround you suggest is infeasible for as we're only using MSAL to capture and manage id_token acquisition, we issue our own access token from the server after validating the id_token and some backend systems, using `navigateToLoginRequestUrl: true` will stop our authorization flow from executing.

I've found that the state validation is also now failing when using it to roundtrip the final url to re-direct the user to when there are certain characters in the query string.
`state: "http://localhost:9000/home"` works as expected.  

However: `state: "http://localhost:9000/sessions?t=%257B%2522from%2522%253A%25222020-07-19T08%253A30%253A00-07%253A00%2522%252C%2522to%2522%253A%25222020-07-23T18%253A00%253A00-07%253A00%2522%257D&g=%255B%2522available-rsvp-only%2522%255D"` results in:

ClientAuthError: Invalid state. eyJpZCI6Ijc5ODdlMTJmLTk2M2YtNDBkMC1hM2QxLTRiOGVjZTNlMmM1NyIsInRzIjoxNTk2MjE4NDA2LCJtZXRob2QiOiJyZWRpcmVjdEludGVyYWN0aW9uIn0=|http://localhost:9000/sessions?t=%7B%22from%22%3A%222020-07-19T08%3A30%3A00-07%3A00%22%2C%22to%22%3A%222020-07-23T18%3A00%3A00-07%3A00%22%7D&g=%5B%22available-rsvp-only%22%5D, state expected : null

**Comment by tnorling** [comment]
@gavinbarron To clarify this is happening when the back button is clicked? The part where you say passing `http://localhost:9000/home` works as expected throws me off because after looking at the code, I don't expect any user provided state to work when pressing the back button. 

If this is for a different scenario please open a separate issue so we can debug what's going on there.

**Comment by gavinbarron** [comment]
Ahh I missed the back button bit, splitting this to a separate issue.

**Comment by jaslloyd** [comment]
This issue doesn’t only happen when you click the back button, it is also when you open a new tab on the same website msal is already in a bad state and crashes again when it tries to load the library

**Comment by tnorling** [comment]
@jaslloyd Understood. The block of code you pointed out, `checkIfBackButtonIsPressed`, runs both when pressing the back button and when opening a new tab, so the PR I linked should fix both scenarios. The name of the function is maybe a little too specific to one scenario, as the real purpose is to ensure msal is in a clean state on load. 

If you're able to pull down the branch and build msal locally, let me know if this fixes your problem. Otherwise, you can expect the fix in an upcoming release soon.

**Comment by jaslloyd** [comment]
@tnorling thanks a lot, I will try to test it at this some point this week, PR looks good to me :) if that matters at all!

**Comment by gavinbarron** [comment]
> @gavinbarron To clarify this is happening when the back button is clicked? The part where you say passing `http://localhost:9000/home` works as expected throws me off because after looking at the code, I don't expect any user provided state to work when pressing the back button.
> 
> If this is for a different scenario please open a separate issue so we can debug what's going on there.

Appologies, opening a new issue for some states being invalid.
