### ISSUE TITLE
In Chrome incognito, when using silent login, the app goes in a continuous login loop

### ISSUE THREAD

**Issue by gladiatorAsh** [AzureAD/microsoft-authentication-library-for-js#2076]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [X] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.
msal@1.2.2

## Description
This app is React based and uses msal for auth, When in incognito mode, the login process recurs in a loop. I suspect it's because the auth cookies are not set with Same site property and hence found missing in the auth calls. Note that the same works fine in Edge Incognito and regular windows of all browsers tested. 

Tested with Chrome Version 84.0.4147.105 (Official Build) (64-bit)

## Error Message
Continuously shows Login popup in silent authentication

## Security
- [ ] Is this issue security related?

## Regression
- [X] Did this behavior work before? 

Version:
## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```
Silent login in latest version of Chrome in incognito mode in any app

## Browsers/Environment
- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by tnorling** [comment]
@gladiatorAsh Chrome Incognito recently updated to block third-party cookies. The silent flow in Msal.js version 1.x relies on third party cookies to work and thus is expected not to work in browsers where this is blocked. You need to either call an interactive method, enable third-party cookies or update to Msal-browser v2.0 which implements the auth code flow and does not rely on third-party cookies in most scenarios. You can read more about this specific problem [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-third-party-cookies-spas)
