### ISSUE TITLE
How do I pass query parameters in the URL when users are redirected to B2C?

### ISSUE THREAD

**Issue by renjithgr** [AzureAD/microsoft-authentication-library-for-js#2077]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x
- [x] `@azure/msal-angular@1.x.x`
-  [ ] `@azure/msal-angularjs@1.x.x`

## Description
I am trying to pass extra query parameters to the B2C page where the user will be redirected to enter their user name and password. To do that I used the ```extraQueryParameters``` key in the Angular configuration object as follows,

```javascript
{
      popUp: !isIE,
      consentScopes: [
        'openid', ...
      ],
      unprotectedResources: [],
      protectedResourceMap: [
        ['...', ['...']]
      ],
      extraQueryParameters: {
        parameterName: 'parameterValue'
      }
    }
```

But when the user is redirected I don't see the query parameter is added to the URL. Am I using the ```extraQueryParameters``` wrong?

**Comment by technical-boy** [comment]
Hi @renjithgr , the `extraQueryParameters` that are set in the configuration are used in the MSAL Guard. Can you please clarify if you're using the MSAL Guard or if you're calling one of the MSAL APIs (loginRedirect or loginPopup) directly?

**Comment by renjithgr** [comment]
Hi @technical-boy, thank you for your response. Our app is calling ```loginRedirect```. 
- Is there a way to pass extra parameters to the URL while using the ```loginRedirect```? Or is using MSAL Guard the only way to do it?

**Comment by technical-boy** [comment]
@renjithgr if you are calling `loginRedirect` manually when `msal:loginFailure` or `msal:acquireTokenFailure` events are broadcast, you will need to manually set the `extraQueryParameters` on those calls to `loginRedirect`:

```js
 this.broadcastService.subscribe('msal:loginFailure', () => {
      this.authService.loginRedirect({
        extraQueryParameters: {}
       });
    });
```

**Comment by renjithgr** [comment]
@technical-boy I couldn't find any examples where MSAL library is used without calling one of the MSAL APIs directly. Even in the samples provided in the repo `loginRedirect` or `loginPopup` is called. Do you know where I can find more information on how to use MSAL library without calling the APIs directly?

**Comment by technical-boy** [comment]
@renjithgr the two mechanisms provided by MSAL Angular that will automatically call MSAL are the MSAL Guard and the MSAL interceptor, which will call `loginPopup`/`loginRedirect` and `acquireTokenSilent` respectively.  Could you clarify what you mean by using MSAL without using MSAL?

**Comment by renjithgr** [comment]
@technical-boy I meant a sample where only MSAL guard and MSAL interceptors are used but not the MSAL API directly (like calling `loginRedirect` or `loginPopup`). For example, in the sample app provided in this repo, the `loginRedirect` is called manually. Why is it required if MSAL Guard and Interceptor are all we need to detect and redirect user to the login page? 

 https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/92e7f3d7db0aa6ac81d3847b0b0b7a236bc90557/samples/msal-angular-samples/MSALAngularDemoApp/src/app/app.component.ts#L37

**Comment by adesca** [comment]
We (@harukogaki)  looked into the issue with a coworker (extra query params set in configuration aren't used as part of loginRedirect call) and here are our findings:
Initial steps:
We add config with extra query parameter
Make a call to loginRedirect()

expected behavior:
redirect with the query parameter set in the config

actual behavior:
redirect without query parameter passed in the config

We looked at the code and observed that login redirect in UserAgentApplication.ts does not use the existing config to set the authenticationParameters, if extraQueryParameter is unprovided. Instead validateRequest (in RequestUtils) sets the  extraQueryParams to an empty stringDict if nothing is passed.

**Comment by jasonnutter** [comment]
> @technical-boy I meant a sample where only MSAL guard and MSAL interceptors are used but not the MSAL API directly (like calling `loginRedirect` or `loginPopup`). For example, in the sample app provided in this repo, the `loginRedirect` is called manually. Why is it required if MSAL Guard and Interceptor are all we need to detect and redirect user to the login page?
> 
> https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/92e7f3d7db0aa6ac81d3847b0b0b7a236bc90557/samples/msal-angular-samples/MSALAngularDemoApp/src/app/app.component.ts#L37

That is shown in the sample to support showing a login button, as the home page is not protected by the MSAL Guard. If you wanted to avoid using MSAL directly, you can add the guard to the home page and remove the login button. Note, you will still need a button to perform logout, as we don't currently provide a mechanism in MSAL Angular to invoke logout automatically.
