### ISSUE TITLE
Allow Controlling the prompt parameter

### ISSUE THREAD

**Issue by spottedmahn** [AzureAD/microsoft-authentication-library-for-js#208]
Please allow the **prompt parameter** to be controlled by the caller.  As of now, it is hard-coded to `select_account`.  This forces the user to sign-in everytime.

If the session cookie is still valid, the user shouldn't have to login again.

```js
const urlNavigate = authenticationRequest.createNavigateUrl(scopes) + "&prompt=select_account" + "&response_mode=fragment";
```

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/43b035152d43787903bccb5f5b06ec061e39192c/src/UserAgentApplication.ts#L352

**Comment by rohitnarula7176** [comment]
@spottedmahn We have hard coded the prompt value as this value is recommended. For instance, if you are using popup and you don't set the prompt=select_account, you will see a flash where the popup will open and close immediately if you have a valid session cookie after you click login and it is not an ideal experience for the end user. The other reason for hard coding this value and having a generic design is that if we allow this prompt parameter to be configurable for the developer, he might end up changing this prompt value from 'none' to 'select_account' in acquireTokenSilent and it will lead to an error condition because in silent authentication,  you only receive responses via redirects, and never with a login page which allows you to select an account. Please let me know if I have answered your question.

**Comment by spottedmahn** [comment]
Hi @rohitnarula7176 - thanks for the quick reply!

I don't understand how we're supposed to take advantage of the [B2C cookie then](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-token-session-sso#session-behavior).  If the user sign-ins, closes the browser, opens our app again they shouldn't have to sign-in again.  That is supposed to be a feature of B2C I believe.

**Comment by danieldobalian** [comment]
Hi @spottedmahn, I think there may be a little bit of confusion of your question.  From what I can tell (please correct me if I'm misunderstanding), your intention is to get an Access token without any interaction.  To do this, you can use the [`acquireTokenSilent`](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/src/UserAgentApplication.ts#L1045) function before any interactive `acquireToken`. This method will make a best effort attempt to get a token silently, but will fail before performing an interactive request.  

[Here's a snippet](https://github.com/Azure-Samples/active-directory-javascript-graphapi-v2/blob/VisualStudio/JavaScriptSPA/app.js#L60) that implements the pattern described above.

**Comment by spottedmahn** [comment]
Hi @danieldobalian - nope, that's not what I'm asking 😄 

When you go to b2c and sign-in, it creates a cookie.  That cookie defaults to being valid for [24hrs, rolling](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-token-session-sso#session-behavior).  If I visit the login page again within 24hrs I shouldn't have to sign-in again.  That's the point of the cookie 😄 

Using the cookie can be overridden though w/ the `prompt` parameter.  For example, when using the Azure portal to test your policies, it adds `&prompt=login` therefore telling it to ignore the cookie.  Apparently `&prompt=select_account` does the same thing.

**Comment by danieldobalian** [comment]
When you use `acquireTokenSilent()`, it will take advantage of the cookie B2C sets, and silently sign in the user (assuming a valid cookie exists).  [renewToken](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/src/UserAgentApplication.ts#L1108) is the code that does this and doesn't allow a prompt behavior that would prevent it from using the cookie (uses `prompt=none`). 

 At that point, calling an subsequent `acquireTokenPopup` (with `prompt=select_account`) can assume there was not a valid cookie that could be used and proceed with the interactive request using the prompt behaviors that bypass the cookie. 

Can you expand on the case in which one of the interactive requests `acquireTokenRedirect`, `acquireTokenPopup`, or `login` should use the cookie set by B2C?  The intended pattern of MSAL is to preempt any interactive function with a call to `acquireTokenSilent` which would succeed in the case of the cookie's existence.

**Comment by spottedmahn** [comment]
Ah, I see, thanks for setting me straight!

We're using `loginRedirect` and `acquireTokenSilent` at this point.  The challenge we're having is w/ `loginRedirect`.  On app-start, we see the user is not signed in so we call `loginRedirect`.

Based on what you're saying, maybe we can call `acquireTokenSilent()` if the user is not signed in.  I wonder if that will populate the `user` though?  i.e. `msal.getUser()`

**Comment by VSDekar** [comment]
For me `acquireTokenSilent()` does not work. I get the error described in this new issue https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/214

Other related issues:
https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/191
https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/61

@spottedmahn Did the `acquireTokenSilent()` work for you?

**Comment by spottedmahn** [comment]
I haven't tried.  Let me lower to token expiration times and try it.  Will try to get to it today.  @VSDekar

**Comment by DavidHenri008** [comment]
@spottedmahn Any news about this?

**Comment by rohitnarula7176** [comment]
@spottedmahn @DavidHenri008 You can achieve this behavior by just calling acquireTokenSilent and passing a user Object as parameter. If you are using local Storage and the tokens persist in the cache after you close and reopen the browser, you can call getUser() to get the user and make the acquireTokenSilent call by passing that user as parameter. if you are using session Storage, and the tokens are cleared when you close and reopen the browser, you can still call acquireTokenSilent by passing an empty user object. In this case meal will send responseType = "id_token token" to request both an id_token to establish user context as well as an access_token. Please put break point at the following line of code to confirm whether the acquireTokenSilent request is sent out or not.
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dfbf950c193ae2f7e3925c921e53702d9b609669/src/UserAgentApplication.ts#L1064

**Comment by DavidHenri008** [comment]
@rohitnarula7176 The MSAL mechanism seems to to be OK but the AD B2C returns me an error, one hour after I signed-in, saying the session is not valid. I always call the acquireTokenSilent() and the silent iFrame access the B2C login page but it receives the error. I really don't know if it is related with the `prompt` parameter. The link below describes the error in more details.

Related MSAL issues:
[#214](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/214)
[#191](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/191)

Related StackOverflow issues:
[Error aadb2c90077](https://stackoverflow.com/questions/48267456/cannot-renew-access-token-from-b2c-error-aadb2c90077)
[Decode cookie](https://stackoverflow.com/questions/48328607/how-to-decode-azure-b2c-cookie)

**Comment by spottedmahn** [comment]
Hi @rohitnarula7176 - that worked!

I set `cacheLocation: 'localStorage'` and then `acquireTokenSilent()` got a token w/o having to sign-in.

### Flow

1. Opened our app
1. Redirected to B2C b/c our app/MSAL saw I wasn't signed-in
1. Signed-in and returned to our app
1. Closed tab and opened our app back up in a new tab
1. Our app/MSAL saw the user as signed-in
1. `acquireTokenSilent()` obtained a token 🔥

**Comment by rohitnarula7176** [comment]
@spottedmahn Thank you for testing this scenario.

**Comment by RonaldV** [comment]
@rohitnarula7176 I still need to be able to change the prompt parameter. Or in this case a way to not send it would also be ok.
I'm using msal.js with Azure AD B2C. When invoking the password change policy I don't want the user to need to log in again. Which means "prompt" should not be set to "select_account".

An extra param (excludePrompt) for loginRedirect would sufficient or maybe a different function.
What do you think?

**Comment by spottedmahn** [comment]
In regards to @RonaldV [post](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/208#issuecomment-376895254).

Reference: SO Post: [Azure AD B2C password change custom policy, user needs to sign in every time](https://stackoverflow.com/questions/48750636/azure-ad-b2c-password-change-custom-policy-user-needs-to-sign-in-every-time)

Reference: [Password **change** policy](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-reference-password-change-custom) (not reset policy)

**Comment by danielzach** [comment]
What about prompt=consent? How to display a consent dialog so that user can accept all the permissions for the app? Without it I'm getting an error when calling Graph API. As a temperatury workaroud I used 'Grant permissions' button im the Azure Portal.
