### ISSUE TITLE
Angular JS 1.7 app with new versions of MSAL Angular

### ISSUE THREAD

**Issue by harinivedala** [AzureAD/microsoft-authentication-library-for-js#2080]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [x] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [x] `@azure/msal-angularjs@1.x.x`

## Description
We have an Angular JS 1.7 production application. I used msal-angularjs wrapper to authenticate against Azure AD. It is working but I have an issue with logout functionality. Based on the response I got from earlier bug report, the feature I want will not be added to msal-angularjs. So, my question is, **can I use the newer versions of msal in our current angular js 1.7 application** with no issues? If so, what version of Msal-Angular should I use? I have not tried it, as I assumed that I will only be able to work with msal-angularjs.

Please advise if there is a better approach to this. We have a rewrite to our Angular JS 1.7 app coming up, possibly in the last quarter of this year or early next year. But, we need to provide authentication mechanism against Azure AD for several reasons up until then. Originally the app had forms based authentication for several years.

**Comment by technical-boy** [comment]
Hey @harinivedala . Unfortunately, `msal-angular` does not support AngularJS applications. If you'd like to use the new versions of MSAL with an AngularJS application, you can use MSAL JS v1 (`msal`) or v2 (`@azure/msal-browser`).

> We have a rewrite to our Angular JS 1.7 app coming up, possibly in the last quarter of this year or early next year. 

Are you updating your AngularJS application to the newer versions of Angular? If so, you would be able to use the `msal-angular` wrapper libraries, which is what we would recommend for Angular applications.

**Comment by harinivedala** [comment]
Thanks @technical-boy.
