### ISSUE TITLE
SSO without login_hint

### ISSUE THREAD

**Issue by mbrevda** [AzureAD/microsoft-authentication-library-for-js#2083]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
When multiple web properties (think production site, development branches with their own url, other sites in the same tenant) use the same credentials, sharing the SSO `login_hint` becomes challenging due to cross-origin restrictions. There are workarounds, like embedding an iframe and using postMessage to store/retrieve the `login_hint` from a common site, however, this is a bit cumbersome.

Would it be feasible to design an SSO mechanism that didn't require a `login_hint` or where the login_hint was hosted by Microsoft and could be retrieved in response to more permanent data (e.g. tenant id)?

**Comment by technical-boy** [comment]
Hi @mbrevda ! Thanks for the feedback. We understand the difficulty and complexity of SSO across web applications. While we are working on improvements to the SSO experience for certain scenarios, at this time we don't have any plans for an SSO mechanism that does not require a hint such as `login_hint`.

**Comment by mbrevda** [comment]
My issue is less with the `login_hint` and more with the challenges of sharing it cross-domain. 

To clarify the use case: currently, there are multiple apps each at a different domain configured to the same tenant/organization. A non-silent login must be initiated when the user loads a given app. For the assorted apps to have true SSO, a `login_hint` needs to be shared between them. 

This is currently only possible if either a backend server is used and the hint is stored in a cookie or via other browser-based storage options and the domain is cross by sending messages to a hidden iframe. 

If Microsoft would host the cookie/iframe which could keep track of the hint on a per tenant basis as part of the AAD service, we could easily append the hint for a silent login without having to host additional infrastructure.

**Comment by technical-boy** [comment]
@mbrevda 

> Microsoft would host the cookie/iframe which could keep track of the hint on a per tenant basis as part of the AAD service, we could easily append the hint for a silent login without having to host additional infrastructure.

Unfortunately, iframe/cookie based solutions will not work because of privacy features such as Safari ITP, which block third party cookies. 

We appreciate your feedback and we'll take it into consideration as we look to improve the SSO experience for browser applications. For now, please take a look at our [Seamless SSO docs](https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-sso-quick-start) and [Windows 10 Accounts Chrome Extension](https://chrome.google.com/webstore/detail/windows-10-accounts/), which can improve the SSO experience for your users.

**Comment by jasonnutter** [comment]
Closing, as no further action at this time.
