### ISSUE TITLE
Incorrect idTokenClaims Type

### ISSUE THREAD

**Issue by deasems** [AzureAD/microsoft-authentication-library-for-js#2084]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.0.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
N/A

## Description
ID token claims include a mix of strings/numbers but the type used (StringDict) only allows string values

## Error Message
> Type 'number' is not assignable to type 'string'.ts(2322) 
MsalTypes.d.ts(5, 5): The expected type comes from this index signature. */

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
```ts
import { AuthenticationResult } from '@azure/msal-browser';

const idTokenClaims: AuthenticationResult['idTokenClaims'] = {
  exp: 1596411774067 // error
  // ...
}
```

## Expected behavior
Allow numbers and strings to be used for id token claims

## Browsers/Environment
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by technical-boy** [comment]
Hi @deasems , this is a known-issue that we're planning to fix. We'll follow up once we've done so.

**Comment by deasems** [comment]
@technical-boy I've updated to 2.0.2 which appears to have this change. Unfortunately changing the `idTokenClaims` type to `object` prevents accessing any of its properties (TS version 3.9.7 here), I get the error `Property 'preferred_username' does not exist on type 'object'`. 
IMO the idTokenClaims type would explicitly type the common claims and include an index signature to represent any other optional claims.

**Comment by technical-boy** [comment]
Hi @deasems . We decided to use the generic `object` type on the exported IdTokenClaims object to avoid making any guarantees about the claims an IdToken can contain and how those might change in the future. 

The workaround we recommend is that you create your own type and cast the IdTokenClaims object in your application code like so:


```js
type IdTokenClaims = {
  preferred_username: string
}

const preferred_username = (result.idTokenClaims as IdTokenClaims).preferred_username;
```
