### ISSUE TITLE
Promise returned from "ssoSilent" never resolves or rejects

### ISSUE THREAD

**Issue by nbfr** [AzureAD/microsoft-authentication-library-for-js#2089]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.0.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
Angular 7

## Description
The promise returned by ssoSilent never resolves or rejects.

## Error Message
-

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
const msalConfig = {
        auth: {
            CLIENT_ID,
            authority: 'https://login.microsoftonline.com/' + TENANT_ID,
            redirectUri: window.location.origin
        },
        cache: {
            cacheLocation: 'localStorage',
            storeAuthStateInCookie: false
        },
        system: {
            loadFrameTimeout: 3 * 60_000
        }
    };
```

## Reproduction steps
```js
const msalInstance = msal.PublicClientApplication(config);
msalInstance .ssoSilent({
                            scopes: ['openid', 'profile', 'user.read'],
                            loginHint: 'foo@microsoft.com',
                            redirectUri: window.location.origin
}).then(response => console.log(response)).catch(error => console.error(error));
```

## Expected behavior
The promise returned by ssoSilent should either resolve or reject.

## Browsers/Environment
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by pkanher617** [comment]
@nbfr  Thanks for opening this, I've added a PR that should fix this and be available in the 2.0.1 release, which should be out shortly.
