### ISSUE TITLE
Is there any plan to upgrade msal-angular@1.x.x to 

### ISSUE THREAD

**Issue by bsocket** [AzureAD/microsoft-authentication-library-for-js#2090]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ X] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Upgrade this library to Microsoft Authentication Library for JavaScript v2.x. Want to use PKCE code flow  for adding security for SPAs

**Comment by technical-boy** [comment]
Hi, @bsocket . Yes, we're planning to upgrade `msal-angular` to use MSAL JS v2. We'd like to do that soon, however, that work hasn't been scheduled yet. We'll update our [Roadmap](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#roadmap) when it is scheduled.

**Comment by Lexcess** [comment]
Also being tracked here: #2042

**Comment by jasonnutter** [comment]
Closing as a duplicate.
