### ISSUE TITLE
MSAL.js - Implicit Authentication - Issue with reply url parameters

### ISSUE THREAD

**Issue by sid1260** [AzureAD/microsoft-authentication-library-for-js#2100]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.3.3`
- [ ] `@azure/msal-browser@2.0.1`

## Description
I am using MSAL.js for a javascript based single page application. We have configure Azure Ad for implicit authentication. The redirection url also has been configured to a page.

However we have a requirement where we get a daily email report. This email has links to the application page but with query parameters that allows to filter the report for that day.

Now if we access the app via the landing page, we are able to login fine. But with the query params it gives the exception "The reply URL specified in the request does not match the reply URLs..".

I am using the endpoint V2 on Azure AD , hence not able to put * in the reply url. I guess this is an existing problem. But is there some way to overcome the issue of logging in & redirection with parameters?

**Comment by technical-boy** [comment]
Hi, @sid1260. Could you please provide your MSAL configuration object (the configuration for PublicClientApplication). Also, are you using `loginPopup` or `loginRedirect`?

In your scenario, when the current page changes dynamically, you should set a redirctURI in your configuration that matches the one in the Azure Portal (the one without query parameters). If you're using `loginRedirect` you can set `navigateToLoginRequestUrl` to true in order to have the user redirected back to the version of the page with query parameters.

Thanks!

**Comment by sid1260** [comment]
Thanks @technical-boy 


Code is below
`const msalConfig = {
  auth: {
    clientId: "bcb2a88a-9efb-414d-89cb-d194acb28a96",
    authority: "https://login.microsoftonline.com/GUID",
    redirectUri: "URL",
  },
  cache: {
    cacheLocation: "sessionStorage",
    storeAuthStateInCookie: false,
  }
};

const myMSALObj = new Msal.UserAgentApplication(msalConfig);

myMSALObj.loginPopup(loginRequest)
  .then(loginResponse => {
    if (myMSALObj.getAccount()) {
      serverLogin(myMSALObj.getAccount().userName);
      window.location.reload()
    }
  }).catch(error => {
    console.log(error);
  });`

We are using loginPopup. My RedirectURI is the one matching the one on Azure. But with the popup option how does it redirect back to the original page with params? Can we set navigateToLoginRequestUrl  = true in this case , does the framework take care of the redirection?

**Comment by technical-boy** [comment]
@sid1260 if you're using `loginPopup`, your application will need to manually redirect the user once the `loginPopup` promise has resolved.
