### ISSUE TITLE
While building in prod mode in ES6 targeted project is not working as @azure/msal-angular library is targeting es5

### ISSUE THREAD

**Issue by sameerrswt** [AzureAD/microsoft-authentication-library-for-js#2108]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.0.0`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework
I have tested on angular 6, onward

## Description
My application is targeting ES6.

As I can see that @azure/msal-angular library is targeting ES5.

So when i am building my application in prod mode with build-optimizer=true and optimization=true. It works fine when I am set either of these properties to false.

it is not working and giving error.
"Must call super constructor in derived class before accessing 'this' or returning from derived constructor."

## Error Message
![image](https://user-images.githubusercontent.com/17155131/89617522-f896ec80-d8a7-11ea-9de7-0094087fa483.png)

"Must call super constructor in derived class before accessing 'this' or returning from derived constructor."

I am able to replicate this issue on sample application provided in below repo by changing its target to ES6.

path for sample app:
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-angular-samples/angular6-sample-app/tsconfig.json

just change target to es6 and build in prod mode. application will stop working.

## MSAL Configuration
No change. As provided in sample.

## Reproduction steps
I am able to replicate this issue on sample application provided in below repo by changing its target to ES6 in tsconfig file.

path for sample app:
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-angular-samples/angular6-sample-app/tsconfig.json

just change target to es6 and build in prod mode. application will stop working.

tsconfig.json
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "esnext",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "**es6**",
    "typeRoots": [
      "node_modules/@types"
    ],
    "paths": {
      "jszip": [
        "node_modules/jszip/dist/jszip.min.js"
      ]
    },
    "lib": [
      "es2017",
      "dom"
    ]
  }
}

## Expected behavior
It should work with ES6 in prod mode with build-optimizer=true and optimization=true in angular.json.

## Browsers/Environment
- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari
- [x] IE
- [x] Other (Please add browser name here)

**Comment by pkanher617** [comment]
@sameerrswt Please use the issue template.

**Comment by sameerrswt** [comment]
Updated issue descriptions as per bug template.

**Comment by technical-boy** [comment]
@sameerrswt thanks for raising the issue. We'll look into it and follow up if we need more information.

**Comment by sameerrswt** [comment]
> @sameerrswt thanks for raising the issue. We'll look into it and follow up if we need more information.

Hi.. Any update on the same?
