### ISSUE TITLE
change accessTokenAcceptedVersion to 2 and iss still be https://sts.windows.net/{id}/

### ISSUE THREAD

**Issue by qinmaye** [AzureAD/microsoft-authentication-library-for-js#2109]
I install keycloak-proxy on AKS and then I meet some questions.

{"error": "oidc: JWT claims invalid: invalid claim value: 'iss'. expected=https://login.microsoftonline.com/{id}/v2.0, found=https://sts.windows.net/{id}/."}

I have already change accessTokenAcceptedVersion to 2

![image](https://user-images.githubusercontent.com/33417731/89515504-c5058500-d809-11ea-8386-23acc3d98abf.png)

but when I get my jwt, it still unchanged

![image](https://user-images.githubusercontent.com/33417731/89515559-e0709000-d809-11ea-9c8f-18ec6a32e900.png)

how can I solve this problem, thanks a lot.

**Comment by pkanher617** [comment]
@qinmaye Please fill out the issue template, we cannot answer your question effectively if we don't have the information there.
