### ISSUE TITLE
Provide Public Access to msal.error and desc

### ISSUE THREAD

**Issue by spottedmahn** [AzureAD/microsoft-authentication-library-for-js#211]
Please provide access to `msal.error` and `msal.error.description` from `_cacheStorage`.

Reason being, our Angular app checks if the user is not logged in and sends them to the login page via a `loginRedirect()` if not.  The problem is when returning from an `AADB2C90118`, password reset request, I need to reach into `_cacheStorage` to determine if this is the case.

```typescript
getMsalErrorDesc(): string{
        //this is hack as we're reaching into private variables.
	let clientApplication2 = this.clientApplication as any;
	let storage = clientApplication2._cacheStorage;
	let errorDesc: string = storage.getItem('msal.error.description');
	return errorDesc;
}
```
Related to [Password Reset Issue](https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp/issues/9)

**Comment by rohitnarula7176** [comment]
@spottedmahn we cannot add public API surface on the library which does not exist on other MSAL platforms. You should be able to get these errors in the callback function you pass in the configurable. The call back function takes errorDesc, token and error as parameters.

**Comment by spottedmahn** [comment]
Hi @rohitnarula7176 - relying upon the callback function isn't working for us.  Let me try to better explain why.  Maybe I am misunderstanding something and you can point me in the right direction 😄 

## Login Only

- On app start, check if the user is logged in?
   1. If yes, do nothing
   1. If no, send to B2C login page

## Login and Password Reset

That was working fine, but now when we bring in password reset it no longer works

- On app start, check if the user is logged in?
     1. If yes, do nothing
     1. If no
           1. Is the user returning from a password request?
                 1. If no, send to B2C login page
                 1. If yes, send to B2C password reset page

---

If the user is not logged in and is not returning from B2C, the **auth callback will not fire**.  Therefore, I can't wait for it to fire to determine where to send the user.

W/O being able to access `msal.error` I can not determine if the user is returning from a password reset request or not.

**Comment by spottedmahn** [comment]
hey @rohitnarula7176 - any updates on handling this use case?  thanks!

**Comment by spottedmahn** [comment]
Hey @rohitnarula7176 - any updates on handling this use case? thanks!

**Comment by spottedmahn** [comment]
Hey @rohitnarula7176 - any updates on handling this use case? thanks!

**Comment by spottedmahn** [comment]
Hey @rohitnarula7176 - any updates on handling this use case? thanks!

**Comment by pkanher617** [comment]
@spottedmahn Apologies for the long delay on this issue. I have read some of the history of this issue, and I have a couple of questions:

1. Are you still seeing an issue with the auth callback not firing when returning from a failed non-B2C login? This is not something we have seen in our test environments.
2. Are you unable to access localStorage or sessionStorage from your application? After MSAL has populated the cache, it should be available to fetch using the msal.error and msal.error.description keys.

**Comment by spottedmahn** [comment]
Hi @pkanher617  👋

>Are you still seeing an issue with the auth callback not firing when returning from a failed non-B2C login? This is not something we have seen in our test environments.

Not a failed login but a "reset password request".

**Comment by spottedmahn** [comment]
>Are you unable to access localStorage or sessionStorage from your application? 

I can it's hacky though.  I'm messing w/ the internals.  I'm crossing the boundary from public to private, not a fan of that.  Make sense?

**Comment by sameerag** [comment]
@spottedmahn I have asked the B2C Service team to take a look at this issue and test this locally. We will try addressing this soon after our 1.0.0 release goes out.

**Comment by sameerag** [comment]
@spottedmahn Is this still seen with the latest MSAL JS? I am planning to sort through B2C issues with the server team and would like to know if this issue needs to be debugged?

**Comment by spottedmahn** [comment]
Hi @sameerag - yes, still an issue for this use case.  I'm not actively working on this project anymore so I'm not a personally vested in it.

To me, it's all about the [use case stated above](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/211#issuecomment-359438043).  Whether that is exposing the error and some other means I'm game.

**Comment by sameerag** [comment]
@spottedmahn The later MSAL versions 1.0.x do expose error in the response. If that mitigates this issue, then it is great. My confusion was more about if this is a B2C specific issue or just the error interface.

We have enhanced our [error handling](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL.js-1.0.0-api-release#error-handling-in-msaljs) and it should cover your use case.

Please let me know if I am missing anything else.

**Comment by spottedmahn** [comment]
>The later MSAL versions 1.0.x do expose error in the response

Oh, nice 😊.  Closing the issue! 👍

>We have enhanced our error handling and it should cover your use case.

Great, I'll take a look!
