### ISSUE TITLE
acquireTokenPopup fails if used concurrently with acquireTokenSilent

### ISSUE THREAD

**Issue by dsaunders45459** [AzureAD/microsoft-authentication-library-for-js#2116]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.
msal@1.3.2
https://alcdn.msauth.net/lib/1.3.2/js/msal.min.js

## Framework
None, basic JavaScript application

## Description
When MSAL tries to acquire a token via acquireTokenSilent and acquireTokenPopup concurrently, if acquireTokenSilent returns a response it automatically closes the popup before user has a chance to interact with it. This results in acquireTokenPopup failing. In our usage the acquireTokenPopup is used when user has not yet consented to scopes, but acquireTokenSilent is trying to acquire a token for different scopes that user has already consented to.

## Error Message
ClientAuthError: User cancelled the flow.

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
It worked with ADAL
Version:

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
// Repros with a basic configuration
var application = new Msal.UserAgentApplication({
    auth: {
        clientId: "<APP_ID>",
        redirectUri: "https://localhost"
    }
});
```

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
// Get token that requires consent. Fails with ClientAuthError: User cancelled the flow.
application.acquireTokenPopup({
    scopes: ["https://onenote.com/Notes.Read"]
}).then((result) => {
    console.log(result)
}).catch((ex) => {
    console.error(ex);
});

// Gets the token silently successfully.
application.acquireTokenSilent({
    scopes: ["https://graph.microsoft.com/user.read"]
}).then((result) => {
    console.log(result)
}).catch((ex) => {
    console.error(ex);
});
```
## Code causing issue
```
   private handleAuthenticationResponse(hash: string): void {
        this.logger.verbose("HandleAuthenticationResponse has been called");

        // retrieve the hash
        const locationHash = hash || window.location.hash;

        // if (window.parent !== window), by using self, window.parent becomes equal to window in getResponseState method specifically
        const stateInfo = this.getResponseState(locationHash);
        this.logger.verbose("Obtained state from response");

        const tokenResponseCallback = window.callbackMappedToRenewStates[stateInfo.state];
        this.processCallBack(locationHash, stateInfo, tokenResponseCallback);

        // If current window is opener, close all windows
        WindowUtils.closePopups();
    }
```
 **WindowUtils.closePopups()** is closing all popups opened by MSAL when any response is received from a different request.

## Expected behavior
I would expect that I can acquire both tokens as they are for different resources, I need two separate tokens. The getTokenSilent call succeeding should not impact the result of my interactive flow I need for another feature. We expect MSAL to allow concurrent token requests.

## Browsers/Environment
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by technical-boy** [comment]
Hi @dsaunders45459 ! Thanks for raising the issue, we'll look into it and follow up when we have more information!

**Comment by ebonato** [comment]
We are also getting this error, but using msal-browser@2.x.x. 
Just using basic sample code provided by Wiki Pages we are getting this ClientAuthError: User cancelled the flow in 40% of runned tests.
Using Firefox, this could reach 90%.
```
/**
         * See here for more info on account retrieval: 
         * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/docs/Accounts.md
         */
        request.account = myMSALObj.getAccountByUsername(o365username);
        return myMSALObj.acquireTokenSilent(request).catch(error => {
            // fallback to interaction when silent call fails
            console.warn("Silent token acquisition fails. acquiring token using Popup");
            return myMSALObj.acquireTokenPopup(request).then(tokenResponse => {
                console.log(tokenResponse);

                return tokenResponse;
            }).catch(error => {
                toastr.warning("Não conectado ao Office 365");
                toastr.warning(error.errorMessage);
                console.error(error);
            });

            //if (error instanceof msal.InteractionRequiredAuthError) {
            //} else {
            //    console.warn(error);
            //}
        });
```

**Comment by hectormmg** [comment]
Hey @dsaunders45459 I published a draft PR that should fix your issue, but I haven't been able to reproduce your original use-case. Could you please help me out by pulling the branch in #2355 , build `msal-core` locally and see if your issue is fixed? I'd really appreciate if you could confirm that for me so we can have validation that the problem is fixed! Thanks!

**Comment by hectormmg** [comment]
@ebonato could you provide more information around your issue? It seems like this is a separate issue because it is happening in 2.0, so maybe open a separate issue to track it? Thanks!

**Comment by dsaunders45459** [comment]
@hectormmg sorry for the delay, I was able to test that your branch fixes the issue I was having.

**Comment by hectormmg** [comment]
@dsaunders45459 no problem, thanks for the confirmation, I'll try to get this into the upcoming 1.4.2 release!
