### ISSUE TITLE
ServerError auth.js

### ISSUE THREAD

**Issue by titodevera** [AzureAD/microsoft-authentication-library-for-js#2117]
## Library
- [x] `msal@1.2.1` or `@azure/msal@1.2.1`

## Description
We are experimenting an issue when trying to auth in the Microsoft Graph API throught the Javascript SDK.
Our web application worked as expected for few months, until some days ago...
We are trying to consume the `https://graph.microsoft.com/beta/me/outlook/tasks?$top=100&$filter=status ne 'completed'` endpoint.
The login popup fires, but after introducing the email, the browser console throughts the error below.

## Error Message
ServerError: The request is not valid for the application's 'userAudience' configuration.

![89411598-f9a01080-d725-11ea-90f2-664a7d73f7e5](https://user-images.githubusercontent.com/11556124/89613462-94adfd00-d882-11ea-8fd0-601ad0babcec.png)

## MSAL Configuration

```js
// <msalConfig>
const msalConfig = {
  auth: {
    clientId: "XXXXXXX",
    redirectUri: "https://allowedurl.com"
  },
  cache: {
    cacheLocation: "localStorage",
    storeAuthStateInCookie: true,
    forceRefresh: false
  }
};

const loginRequest = {
  scopes: [
    "tasks.read"
  ]
}
// </msalConfig>
```

## Reproduction steps
```js
// <signIn>
async function todoSignIn( skipPopup = false ) {
  // Login
  try {

    let getAccount = msalClient.getAccount();

    if ( getAccount ) {

      todoUpdatePage( getAccount );

    } else {

      if ( ! skipPopup ) {
        await msalClient.loginPopup( loginRequest );
      }
      todoUpdatePage( msalClient.getAccount() );

    }

  } catch (error) {
    console.log(error);
  }

}
// </signIn>
```

## Expected behavior
Authenticate to the Graph API and list the user "Microsoft To Do" tasks.

## Browsers/Environment
Tested on:
- [x] Firefox
- [x] Chrome

--------------------

Related to [ServerError auth.js #310](https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/310)

--------------------

Thank you so much!

**Comment by technical-boy** [comment]
Hi @titodevera ! 

Is your application designed to work with only public Microsoft accounts (outlook.com/hotmail.com) or do you want to allow users with work accounts (i.e. @microsoft.com)?

**Comment by titodevera** [comment]
The application is designed to work with public Microsoft accounts, anyone with a Microsoft account should be able to login and reach his own To Do tasks.

¿Can you help us with this issue?

Thank you so much!

**Comment by titodevera** [comment]
Set the value "AzureADandPersonalMicrosoftAccount" for the property "signInAudience" in the manifest solves the issues.

![audience](https://user-images.githubusercontent.com/11556124/89775666-9ab50f80-db08-11ea-95c2-abddcbdbf848.png)
