### ISSUE TITLE
How can I put together a static URL that explicitly redirects to B2C?

### ISSUE THREAD

**Issue by lnadudva** [AzureAD/microsoft-authentication-library-for-js#2122]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x ] `msal@1.3.0` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
I know that this is a weird use-case, but let me explain the reason for it first.

Tech stack: Angular 8 & msal 1.3.0

The problem: Our client wants us to provide a static URL which they can put up on their site on their domain, and after the user clicks on it they get explicitly redirected to the B2C login screen.
We already implemented a solution which is basically a new route (/auth-redirect) on our Angular frontend which loads msal and starts the login process but it just takes too long to do (like 3-4 seconds on average). Is there any way that we can put together an URL which explicitly redirects to the B2C login screen?
The URL that msal puts together for us looks something like this:

```
https://EXAMPLE.b2clogin.com/EXAMPLE.onmicrosoft.com/b2c_1a_signup_signin_EXAMPLE/oauth2/v2.0/authorize?response_type=id_token&scope=openid%20profile&client_id=1a487b73-5d9f-486c-af69-f50300c74b5e&redirect_uri=https%3A%2F%2FEXAMPLE.azurewebsites.net%2Fhome%2Fredirect&nonce=e8730f85-ec6f-4100-b228-f54aa9af8e57&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=1.3.0&response_mode=fragment&domain_hint=EXAMPLE
```

But if we just copy this URL and try to make it generic, we get the following error:
`AuthError: Unexpected error in authentication.: Hash does not contain state.`
May there be a solution which provides a generic state?

Thank you for your help, msal team!

Examples: 
> "How do I use MSAL with Vue.js"
> "How do I SSO between tabs?"
> "How do I use MSAL to protect my custom Web API?"
> "How can my app support multiple AAD tenants?"
> "When will my scenario be supported?"
> "When will this framework be supported"

**Comment by technical-boy** [comment]
Hi @lnadudva ! `loginRedirect` has a callback called `onRedirectNavigate` that you can implement to get the URL that MSAL would navigate the user to. Your application can use this to generate the URL that would take the user to the B2C login page. 

```js
msalInstance.loginRedirect({
  onRedirectNavigate: (url) => {
    // The value of 'url' is the URL that MSAL would redirect the user to.
    // To prevent MSAL from performing the redirect itself, you must return 'false' from this function
    return false; 
  };
});
```

MSAL does not support a static URL as the service requires dynamic values that are set per request.

**Comment by lnadudva** [comment]
@technical-boy thank you for your quick response!

**Comment by technical-boy** [comment]
@lnadudva you are very welcome! Let me know if this works for you so we can close the issue!

**Comment by technical-boy** [comment]
Closing, please let us know if you have any further questions.
