### ISSUE TITLE
msal-angular does not cache access tokens

### ISSUE THREAD

**Issue by dbpieter** [AzureAD/microsoft-authentication-library-for-js#2124]
- [x] `msal@1.3.4`
- [ ] `@azure/msal-browser@2.x.x`
- [x] `@azure/msal-angular@1.0.0`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

We see msal(-angular) making an acquireTokenSilent request upon each subsequent api call.
While this issues seems very similar to #1936. The fix in #1962 does not seem to fix this for us. At least if this fix is included in msal@1.3.4, which I think it is.

## Logs
![image](https://user-images.githubusercontent.com/1613011/89800391-0316e780-db2f-11ea-86a0-c4bc2a9ae977.png)

What's weird here is that initially 'api://clientid/openid' is logged but later when the token is renewed we see 
'api://clientid/openid|undefined'. I don't know if that '|undefined' is just part of a wonky logging statement but it seems a bit odd.

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:
We started at 1.3.3, same behaviour in 1.3.4

## MSAL Configuration

```ts
export function MsalConfigFactory(appSettings: AppSettings): Configuration {
   const msalConfig: any = {
      auth: {
         clientId: appSettings.getMsalConfigByKey('clientId'),
         authority: appSettings.getMsalConfigByKey('authority'),
         validateAuthority: true,
         redirectUri: appSettings.getMsalConfigByKey('redirectUri')
      },
      cache: {
         cacheLocation: appSettings.getMsalConfigByKey('cacheLocation'),
      },
      system : {}
   };

   if (appSettings.getMsalConfigByKey('enableDevLogger')) {
      msalConfig.system.logger = new Logger((logLevel, message, piiEnabled) => { console.log(message); }, {
         correlationId: '1234',
         level: LogLevel.Verbose,
         piiLoggingEnabled: true,
      });
   }

   return (msalConfig as Configuration);
}

export function MsalAngularConfigFactory(appSettings: AppSettings): MsalAngularConfiguration {
   const msalAngularConfig = {
      popUp: !isInternetExplorer11,
      protectedResourceMap: [],
      extraQueryParameters: {}
   };

   // add endpoints
   for (const endpoint of appSettings.getMsalConfigByKey('endpoints')) {
      msalAngularConfig.protectedResourceMap.push([endpoint, [`api://${appSettings.getMsalConfigByKey('clientId')}/openid`]]);
   }

   return (msalAngularConfig as MsalAngularConfiguration);
}```

## Expected behavior

Cached access token is used.

## Browsers/Environment
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by dbpieter** [comment]
We have been able to work around this issue in two ways. Still the behaviour with the initial config seems a bit buggy.

- Workaround 1: Not specifying the endpoint in protectedResourceMap. This only works if the angular app is on the same domain as the resource I believe.
- Workaround 2: Using an arbitrary custom scope: api://clientid/do_stuff instead of /openapi

**Comment by technical-boy** [comment]
Hi, @dbpieter . Could you please clarify if your intention is to protect your API resources with ID Tokens as opposed to access tokens?

**Comment by dbpieter** [comment]
@technical-boy No that's not the intention. The API requires access tokens.  We don't require any meaningfull custom scope for our api since we have our own system to manage claims and authorization hence /openid, but I guess that's not a good choice, at least for our usecase. We have since create a custom scope for our api and the caching issue is no more.

**Comment by technical-boy** [comment]
@dbpieter thanks for the update, please let us know if you have any other questions!
