### ISSUE TITLE
Web storage cache

### ISSUE THREAD

**Issue by hraz-msft** [AzureAD/microsoft-authentication-library-for-js#2126]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Storing tokens in localStorage or sessionStorage is not really secured, because it is accessible from JS (XSS).

I don't think that sessionStorage is better than localStorage for apps that are fully protected by authentication, since the experience of re-login every time the user close the browser / tab is very bad and annoying.

What is the best approach for that? Is there any way to prevent MSAL.js from caching the JWT token in the web storage?

**Comment by technical-boy** [comment]
Hi @hraz-msft . Thanks for the question. We are aware of the trade-offs that come with client-side authentication and storing tokens in browser storage. MSAL JS leverages mechanisms such as the `state` and `nonce` to mitigate possible security concerns, such as token replay. You can read more on our thoughts about client-side authentication in [this blog post](https://developer.microsoft.com/en-us/identity/blogs/our-thoughts-on-implicit-grant-with-microsoft-identity/).

Having said this, there is work in progress to allow applications to provide their own storage for token caching. As of this moment, we have a draft PR (#2060) that addresses this. This would allow your application to store tokens in something other than `localStorage` or `sessionStorage`.

**Comment by technical-boy** [comment]
Closing, please let us know if you have further questions.
