### ISSUE TITLE
allow "logout" of a specific application but not end the entire AAD session, which logs you out of all apps

### ISSUE THREAD

**Issue by aappddeevv** [AzureAD/microsoft-authentication-library-for-js#2127]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
If one is using outlook on the web as well as an app that is leverage AAD, if you logout the app, you are also logging out of the outlook application. The feature request is for a way to just "logout" (perhaps clear the app specific storage) the app without logging out of the entire AAD session.

I have a few apps that are based on a registered app in AAD in the same tenant as the outlook web app (e.g. O365). Logging out of one app seems to log you out of all apps, which to me at least, was unexpected. I had expected to only be logged out of the account/app that was specified in the `logout` call.

**Comment by technical-boy** [comment]
Hi @aappddeevv . Thanks for the feedback, we'll take this under consideration. As you mention, if you'd like this functionality now, you can manually clear or delete values from local storage.

**Comment by aappddeevv** [comment]
Of course, however, I do not want to tell my users to go clear local storage. I would need to duplicate the key naming logic to clear those entries programattically.

**Comment by jasonnutter** [comment]
This will be addressed in #2669, which will add the `onRedirectNavigate` callback to the logout API.
