### ISSUE TITLE
How to handle redirects URLs with many dynamic sub domains

### ISSUE THREAD

**Issue by jaslloyd** [AzureAD/microsoft-authentication-library-for-js#2130]
Hi everybody,
Was wondering if you could provide some advice.

We generate "live" previews for our feature branches every time one of our team pushes a feature branch. This is completely live environments connected to our dev BE.

The URL have somewhat of a format: http://<app_name>.<generated_unique_id>.ourcompanydomain.dev.com

Each branch gets its own FQDN in the above format that is unique to the branch. Now comes the questions, how can we handle redirect uris with MSAL?, previously on a very old instance of app registration we were using wildcards for the subdomain so http://*.ourcompanydomain.dev.com this is generally not a good idea but it worked for our use case at the time.

This is not really supported anymore and we want to move to a better way of doing it but we are struggling with how to handle this with MSAL and adding every possible combination of redirect_uris to our app registration is impossible. Here are a few things we thought about:

## Idea 
Have all login requests for these features go through a "central" point, maybe on the same domain (maybe not) e.g http://<app_name>.ourcompanydomain.dev.com, so the idea would be:
1. User loads branch URL  http://<app_name>.<generated_unique_id>.ourcompanydomain.dev.com if user is not authenticated redirect them to microsoft with a redirect_uri of the central point e.g http://<app_name>.ourcompanydomain.dev.com, also add some state to tell what the orignal request url is
2. User logs in, MS redirects them back to http://<app_name>.ourcompanydomain.dev.com it sees this is not meant for this domain (checks state) so it "forwards" the request to the correct feature branch.

This doesn't seem to work because msal records the domain the requested the URL, if it's not the same on the way back it won't let you use it. This seems like a valid check for security

The other options we are evaluating are:
- Completely disable auth on features - Although this would be the last resort for us
- Generating some very long-lived token or "test" token that we can use for features that would be valid token issues by microsoft so our BE could still verify the request

Any other ideas? or has somebody ever asked a question like this.

Thanks for reading this!

Jason

**Comment by technical-boy** [comment]
Hi @jaslloyd . One approach would be to use the [Microsoft Graph API ](https://docs.microsoft.com/en-us/powershell/module/azuread/set-azureadapplication?view=azureadps-2.0)or [Azure Powershell](https://docs.microsoft.com/en-us/powershell/module/azuread/set-azureadapplication?view=azureadps-2.0) to programmatically update your app registration to add and remove the dynamic redirect URLs when deploying staging branches. Could you try that and let us know if it works for you?

**Comment by JonDReese** [comment]
I asked a very similar question here #2139 

This documentation seems to talk about our problem @jaslloyd  and a solution, but I'm not sure how to implement it with MSAL.

**Comment by jaslloyd** [comment]
@technical-boy This worked out mostly great, I ended up using the az cli, the support wasn't the best in term of updating SPA urls but otherwise it worked. For anybody reading this later details can be found [here](https://github.com/Azure/azure-cli/issues/12946#issuecomment-679273199)

I also have looked in @JonDReese approach, i think we have another issue (#2139) about that so I will close this
