### ISSUE TITLE
MSAL Loading Frame has time out after 30 seconds. 

### ISSUE THREAD

**Issue by Vivek-M-651** [AzureAD/microsoft-authentication-library-for-js#2143]
# Library
msal@1.3.2

## Framework
React Application

## Description
When we try to login using msal library in my react application, acquireTokenSilent is throwing following errors.

_[MSAL] Thu, 13 Aug 2020 10:45:44 GMT:1.3.4-Error monitorIframeForHash unable to find hash in url, timing out

 [MSAL] Wed, 12 Aug 2020 11:17:51 GMT:1.3.2-Verbose Loading frame has timed out after: 30 seconds for scope/authority_

Even on Retrying also we are getting same error continously. 

We are calling acquiretokensilent with graph API scopes  User.Read. Also we tried to call with PowerBi Scopes in both cases it is happening.

Please help to figure out the solution

## Error Message
Error monitorIframeForHash unable to find hash in url, timing out

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration
Graph API Scopes - https://graph.microsoft.com/User.Read
Power Bi Scopes -  "https://analysis.windows.net/powerbi/api/Report.Read.All",
    "https://analysis.windows.net/powerbi/api/Dataset.Read.All"
```

## Expected behavior
It should acquiretokensilent without retrying. Due to this retrying the login process is taking too much time.

## Browsers/Environment
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE

**Comment by technical-boy** [comment]
Hi @Vivek-M-651 . Could you please provide the complete MSAL logs for the request? If you are requesting scopes for multiple resources (Microsoft Graph and PowerBI), you need to make separate calls to acquireTokenSilent for each set of scopes.

```js
// First call for MSGraph
const msGraphRequest = await msalInstance.acquireTokenSilent({
  scopes: ["https://graph.microsoft.com/User.Read"]
});

// A second call for PowerBI scopes
const powerBiRequest = await msalInstance.acquireTokenSilent({
  scopes: [ "https://analysis.windows.net/powerbi/api/Report.Read.All", "https://analysis.windows.net/powerbi/api/Dataset.Read.All"]
});
```

**Comment by Vivek-M-651** [comment]
We are making a separate calls for Power Bi and Microsoft Graph just as mentioned by you. When we try to make the calls for acquiretokensilent we are getting this issue.

Please find the logs. (marked the error)

AuthProvider.jsx:31 [MSAL] Wed, 12 Aug 2020 11:17:20 GMT:1.3.2-Info State status:true; Request type:LOGIN
AuthProvider.jsx:31 [MSAL] Wed, 12 Aug 2020 11:17:20 GMT:1.3.2-Info State is right
AuthProvider.jsx:31 [MSAL] Wed, 12 Aug 2020 11:17:20 GMT:1.3.2-Info Fragment has id token
AuthProvider.jsx:135 [Custom] powerBiAccessToken: Getting powerBiAccessToken
AuthProvider.jsx:108 [Custom] : Getting Silent Result
AuthProvider.jsx:31 [MSAL] Wed, 12 Aug 2020 11:17:20 GMT:1.3.2-Verbose AcquireTokenSilent has been called
AuthProvider.jsx:31 [MSAL] Wed, 12 Aug 2020 11:17:20 GMT:1.3.2-Verbose Telemetry Event started: 085eb334-8647-4702-8b9e-685eaccfca78_9a858514-b5a0-4c4b-b33d-79dd2f83e8fe-msal.api_event
AuthProvider.jsx:31 [MSAL] Wed, 12 Aug 2020 11:17:20 GMT:1.3.2-Verbose Account set from MSAL Cache
AuthProvider.jsx:31 [MSAL] Wed, 12 Aug 2020 11:17:20 GMT:1.3.2-Verbose Response type: token
AuthProvider.jsx:31 [MSAL] Wed, 12 Aug 2020 11:17:20 GMT:1.3.2-Verbose Finished building server authentication request
AuthProvider.jsx:31 [MSAL] Wed, 12 Aug 2020 11:17:20 GMT:1.3.2-Verbose Query parameters populated from existing SSO or account
AuthProvider.jsx:31 [MSAL] Wed, 12 Aug 2020 11:17:20 GMT:1.3.2-Verbose Token is not in cache for scope: https://analysis.windows.net/powerbi/api/report.read.all https://analysis.windows.net/powerbi/api/dataset.read.all
AuthProvider.jsx:31 [MSAL] Wed, 12 Aug 2020 11:17:20 GMT:1.3.2-Verbose No cached metadata for authority
AuthProvider.jsx:31 [MSAL] Wed, 12 Aug 2020 11:17:20 GMT:1.3.2-Verbose Telemetry Event started: 085eb334-8647-4702-8b9e-685eaccfca78_e29e0339-feed-480b-89af-dafc504afdce-msal.http_event
AuthProvider.jsx:31 [MSAL] Wed, 12 Aug 2020 11:17:20 GMT:1.3.2-Verbose Telemetry Event stopped: 085eb334-8647-4702-8b9e-685eaccfca78_e29e0339-feed-480b-89af-dafc504afdce-msal.http_event
AuthProvider.jsx:31 [MSAL] Wed, 12 Aug 2020 11:17:20 GMT:1.3.2-Verbose Authority has been updated with endpoint discovery response
AuthProvider.jsx:31 [MSAL] Wed, 12 Aug 2020 11:17:20 GMT:1.3.2-Verbose Renewing accesstoken
AuthProvider.jsx:31 [MSAL] Wed, 12 Aug 2020 11:17:20 GMT:1.3.2-Verbose renewToken is called for scope and authority: https://analysis.windows.net/powerbi/api/report.read.all https://analysis.windows.net/powerbi/api/dataset.read.all|undefined
**AuthProvider.jsx:31 [MSAL] Wed, 12 Aug 2020 11:17:20 GMT:1.3.2-Verbose monitorWindowForHash polling started
AuthProvider.jsx:31 [MSAL] Wed, 12 Aug 2020 11:17:51 GMT:1.3.2-Error monitorWindowForHash unable to find hash in url, timing out
AuthProvider.jsx:31 [MSAL] Wed, 12 Aug 2020 11:17:51 GMT:1.3.2-Verbose Loading frame has timed out after: 30 seconds for scope/authority https://analysis.windows.net/powerbi/api/report.read.all https://analysis.windows.net/powerbi/api/dataset.read.all|undefined:eyJpZCI6IjVmMTdkMGI4LWRhY2QtNDBhYS04NzAxLTA5NWZhNzhlMzUxNiIsInRzIjoxNTk3MjMxMDQwLCJtZXRob2QiOiJzaWxlbnRJbnRlcmFjdGlvbiJ9**
AuthProvider.jsx:31 [MSAL] Wed, 12 Aug 2020 11:17:51 GMT:1.3.2-Verbose Telemetry Event stopped: 085eb334-8647-4702-8b9e-685eaccfca78_9a858514-b5a0-4c4b-b33d-79dd2f83e8fe-msal.api_event
AuthProvider.jsx:31 [MSAL] Wed, 12 Aug 2020 11:17:51 GMT:1.3.2-Verbose Flushing telemetry events: 085eb334-8647-4702-8b9e-685eaccfca78
AuthProvider.jsx:175 [MSAL] token_renewal_error: Token renewal operation failed due to timeout. Re-trying...


On Retrying the same thing will happen again. Sometimes it is happening for Power Bi and Sometimes for Graph API. Both time we are getting this same error **Error monitorWindowForHash unable to find hash in url, timing out**


Please help us on this.

**Comment by technical-boy** [comment]
@Vivek-M-651 have you tried debugging MSAL and determining what is happening in the hidden iframe that is causing MSAL to timeout?
