### ISSUE TITLE
How to disable post-logout redirect

### ISSUE THREAD

**Issue by deasems** [AzureAD/microsoft-authentication-library-for-js#2145]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.0.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
The default logout behavior redirects users back to the current location.href. This doesn't work for my app because if a user is not authenticated we auto redirect users to login creating a confusing UX on logout. Instead, I would like to not redirect the user at all after the logout is successful. How can I disable the default redirect behavior? I've tried setting the msal config `postLogoutRedirectUri: ''` without success. 
I believe our current auth solution achieves this behavior by simply not providing the redirect param.

**Comment by technical-boy** [comment]
Hi @deasems. Thanks for bringing this to our attention! It does look like there's no way to disable this behavior at the moment, so it may be a bug. We'll follow up if we need more information.

**Comment by deasems** [comment]
commenting for activity

**Comment by sameerag** [comment]
@deasems Does the app settings in portal configure a `Logout URL`?  Can you let us know what happens if you leave that field blank?

**Comment by deasems** [comment]
HI @sameerag, our app does not have a logout url configured -- the behavior in the original issue is with a blank logout url. 
Note - we're configuring our app via the first party identity portal, not the azure portal.
