### ISSUE TITLE
AccountInfo doesn't return name of account

### ISSUE THREAD

**Issue by thoo1** [AzureAD/microsoft-authentication-library-for-js#2147]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.0.1`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

The AccountInfo interface doesn't expose a name property 
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/7cd420254b57b3a988446dc5774659a81a2bbd2a/lib/msal-common/src/cache/entities/AccountEntity.ts#L95
It looks like this object already has the name of the account, it is just not exposed

Is there reason for this? Could this be exposed? It is useful for us to render the name of the currently logged in user 
Thanks!

**Comment by technical-boy** [comment]
Hi @thoo1! This is a known issue we plan to address it soon. Thanks!

**Comment by jaslloyd** [comment]
@technical-boy Is there an easy way we can guess the key msal stores it in so we can pull the username ourselves? I have a "hack" that i needed to do to pull the username @thoo1 but I need to loop through entire localStorage.

```ts
   Object.keys(localStorage).forEach(function (key) {
      if (localStorage[key] && (localStorage[key] as string).includes('"name"')) {
        const parsedUsername = JSON.parse(localStorage[key])!.name;
      }
    });
```

**Comment by jeverduzco** [comment]
I was thinking about migrating my applications to 2.x.x but because of this I can't do it, it completely breaks my UI where I show the name.
