### ISSUE TITLE
Architecture help

### ISSUE THREAD

**Issue by freeman-g** [AzureAD/microsoft-authentication-library-for-js#215]
Hello,

I have a Vue.js SPA with a .NetCore 2.0 backend and I'm hoping to achieve the following architecture, but I haven't found an example with the same architecture:

1) Front End uses MSAL to retrieve an ID Token JWT containing the user's AD Group Claims
2) Front End sends Bearer requests with the ID Token JWT to the backend API
3) Backend validates the ID Token and parses the claims
4) Backend policies are configured based on claims which are used for group level authorization on different API endpoints.

Is this architecture possible? If not, what is the correct architecture I should be using?

Thank you

**Comment by rohitnarula7176** [comment]
@freeman-g I don't see a problem with the above architecture. We have a sample that shows how to integrate authentication with msal using a Vue app but not the one that uses a backend API but implementing a backend API on top of it should be straightforward. Please see below:
https://github.com/sunilbandla/vue-msal-sample

**Comment by freeman-g** [comment]
@rohitnarula7176 - Thank you, I had not seen the vue example yet, which is helpful.

After researching this much further, I don't think my architecture above will work because I cannot get the MSAL retrieved ID token to contain AD groups. Apparently this is a limitation with the URL fragment based flow that MSAL uses. Unless you know of a way to do this?

Unfortunately, this means I need a much more complicated architecture. So this is what I'm working on now:

1. Front End uses MSAL to retrieve an ID Token and an Access Token
2. Front End sends a POST to the backend with the ID Token (As Bearer) and Access Token (As Body) to a special JWT endpoint I have developed. This endpoint is secured and requires an AAD ID token.
3. Backend uses the Access token to fetch the user's groups from the Graph API
4. Backend parses this data and generates another new JWT containing the groups. This is an application specific JWT. Backend responds to the front end with this new JWT.
5. Front end uses this new JWT for all requests moving forward as it contains groups and all information needed for role based policy authorization and authentication
