### ISSUE TITLE
[Angular] Cannot find name TaskData || Cannot find name Task

### ISSUE THREAD

**Issue by Asphiii** [AzureAD/microsoft-authentication-library-for-js#2150]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [x ] `@azure/msal-angular@1.3.4`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
Angular 10.0.8 with:
    "@angular/animations": "~10.0.8",
    "@angular/common": "~10.0.8",
    "@angular/compiler": "~10.0.8",
    "@angular/core": "~10.0.8",
    "@angular/forms": "~10.0.8",
    "@angular/platform-browser": "~10.0.8",
    "@angular/platform-browser-dynamic": "~10.0.8",
    "@angular/router": "~10.0.8",
    "@azure/msal-angular": "^1.0.0",
    "jwt-decode": "^2.2.0",
    "msal": "^1.3.4",
    "ngx-cookie-service": "^3.1.3",
    "ngx-toastr": "^13.0.0",
    "rxjs": "~6.6.2",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"

## Description
Can't run project - errors in Zone.js. If you look at the files it seem, that he can't reach these interfaces / classes - they're in zone.ts. It only happens when i'm trying to use MSAL

## Error Message
` ERROR in node_modules/zone.js/lib/common/utils.d.ts:42:101 - error TS2304: Cannot find name 'TaskData'.

    42 export declare function scheduleMacroTaskWithCurrentZone(source: string, callback: Function, data?: TaskData, customSchedule?: (task: Task) => void, customCancel?: (task: Task) => void): MacroTask;
                                                                                                           ~~~~~~~~
    node_modules/zone.js/lib/common/utils.d.ts:42:135 - error TS2304: Cannot find name 'Task'.

    42 export declare function scheduleMacroTaskWithCurrentZone(source: string, callback: Function, data?: TaskData, customSchedule?: (task: Task) => void, customCancel?: (task: Task) => void): MacroTask;
                                                                                                                                             ~~~~
    node_modules/zone.js/lib/common/utils.d.ts:42:172 - error TS2304: Cannot find name 'Task'.

    42 export declare function scheduleMacroTaskWithCurrentZone(source: string, callback: Function, data?: TaskData, customSchedule?: (task: Task) => void, customCancel?: (task: Task) => void): MacroTask;
                                                                                                                                                                                  ~~~~
    node_modules/zone.js/lib/common/utils.d.ts:42:188 - error TS2304: Cannot find name 'MacroTask'.
    42 export declare function scheduleMacroTaskWithCurrentZone(source: string, callback: Function, data?: TaskData, customSchedule?: (task: Task) => void, customCancel?: (task: Task) => void): MacroTask;
                                                                                                                                                                                                  ~~~~~~~~~
    node_modules/zone.js/lib/common/utils.d.ts:57:40 - error TS2304: Cannot find name 'TaskData'.
    57 export interface MacroTaskMeta extends TaskData {
                                              ~~~~~~~~
    node_modules/zone.js/lib/common/utils.d.ts:64:40 - error TS2304: Cannot find name 'TaskData'.
    64 export interface MicroTaskMeta extends TaskData {`

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 

## Reproduction steps
npm start / ng serve and you'll receive an error

## Expected behavior
Compile properly

**Comment by technical-boy** [comment]
Hi @Asphiii ! Are you able to reproduce this with one of our [Angular samples](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-samples)?

**Comment by Asphiii** [comment]
Hi, my bad - it's not MSAL that makes an error; I can't explain why it disappeared while deleting MSAL. 
I'm closing it
