### ISSUE TITLE
Timeout with acquireTokenSilent in Microsoft Edge Chromium 

### ISSUE THREAD

**Issue by toddfsnyder** [AzureAD/microsoft-authentication-library-for-js#2156]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] msal@1.2.2

## Framework
Angular 9 Working directly with the msal.js 1.2.2 library

## Description
Getting a timeout error when trying to get acquireTokenSilent in  Microsoft Edge Chromium Version 84.0.522.59 when calling Azure B2C Tenant. 

## Error Message
URL navigated to is https://{B2CTenant}.b2clogin.com/{B2CTenant}.onmicrosoft.com/b2c_1a_gs1us_ac_signin_v1/oauth2/v2.0/authorize?response_type=token&scope=https%3A%2F%{B2CTenant}.onmicrosoft.com%2Fusermgmtapilocal%2Fcompany.read%20https%3A%2F%{B2CTenant}.onmicrosoft.com%2Fusermgmtapilocal%2Fdemo.read%20openid%20profile&client_id={clientID}&redirect_uri=https%3A%2F%2Flocalhost%3A6420&state=8a6bcf44-8023-4fca-b72d-312052d88bad&nonce=a655090e-5100-437f-af05-9e7c3baf7200&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=1.2.2&login_req=0f9619f0-b980-4708-82e8-e6c964c869b0-b2c_1a_gs1us_ac_signin_v1&domain_req=a136b191-4415-4ed5-bf91-d7c94247cfcd&domain_hint=organizations&CompanyId=99999999&client-request-id=c0463f93-c938-43c5-848c-96a3708da3fc&prompt=none&response_mode=fragment, Token renewal operation failed due to timeout.

## Security
- [X ] Is this issue security related? Yes, trying to acquire token for calling Web API

## Regression
- [X ] Did this behavior work before? Yes, this worked in msal 1.0.2. version. msal 1.2.2 successfully works with Chrome.

## Reproduction steps
After redirecting back from the Azure B2C Login screen. Trying to acquire token to call Azure B2C Secured (Scoped) ASP.NET Web API. 

## Expected behavior
Calling acquireTokenSilent  works successfully in Edge Chromium.

## Browsers/Environment
- [X] Edge

**Comment by technical-boy** [comment]
Hey, @toddfsnyder! Timeouts can happen for many reasons. Are there any other errors in the browser console? Also, are you using hash routing in Angular? Is this issue consistently reproducible, or is it intermittent? And finally, does this only happen with Edge Chromium, or is it reproducible in other browsers as well? Thanks!

**Comment by toddfsnyder** [comment]
Chrome and Firefox both work fine. We are only seeing this issue in Edge Chromium. Below are the other warnings/errors we are getting. The issue happens every time, sometimes if we refresh the browser the application will load. 

**SameSite Cookie Warnings:**
A cookie associated with a cross-site resource at http://b2clogin.com/ was set without the `SameSite` attribute. A future release of Microsoft Edge will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

search:1 A cookie associated with a cross-site resource at http://{B2CTenant}.b2clogin.com/ was set without the `SameSite` attribute. A future release of Microsoft Edge will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

**Other Error**
authentication.service.ts:429 acquireTokenSilent: error: ClientAuthError: Token calls are blocked in hidden iframes


A cookie associated with a cross-site resource at http://b2clogin.com/ was set without the `SameSite` attribute. A future release of Microsoft Edge will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
search:1 A cookie associated with a cross-site resource at http://{B2CTenant}.b2clogin.com/ was set without the `SameSite` attribute. A future release of Microsoft Edge will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

authentication.service.ts:429 acquireTokenSilent: error: ClientAuthError: Token calls are blocked in hidden iframes

**Comment by technical-boy** [comment]
Hi @toddfsnyder.

>ClientAuthError: Token calls are blocked in hidden iframes

This error happens when the page that you use for the redirect_uri for `acquireTokenSilent` itself calls `acquireTokenSilent` on page load.

I noticed you are using your homepage as your redirect_uri, which means your homepage will load in the hidden iframe, which may be causing the timeouts. For `acquireTokenSilent` calls, you can use a blank html page as your redirect_uri, which will remove the `ClientAuthError` and may fix the timeouts. 

Could you please try that and let us know if it works for you?
