### ISSUE TITLE
Can handleRedirectPromise be documented better with Examples? Otherwise can lead to race conditions

### ISSUE THREAD

**Issue by jaslloyd** [AzureAD/microsoft-authentication-library-for-js#2160]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Documentation location
- [ ] docs.microsoft.com
- [ ] MSAL.js Github Wiki
- [ ] README file
- [ ] Other (please fill in)
- [X] Documentation does not exist

## Description

Hey guys, first of all, I do like to thank you for all the work you guys are doing on the libraries and I understand auth is a hard battle especially when you have so many libraries. Now to my point, I was upgrading from ADAL-angular to msal yesterday for basically a 3 framework TS/JS application but for these purposes, adal/msal was used in a utility file in vanilla JS i.e framework agnostic 

All was going mostly well until I ran into handleRedirectPromise and how its behavior of changed/been upgraded from previous angular models(handleWindowCallback)....our old code mostly had the format of:

- When library is imported this code ran, this would cause a redirect (we are using redirects not popups)
```js
  const authContext = new AuthenticationContext(context);

  authContext.handleWindowCallback();
  authContext.getCachedUser();
  ... other function...
```

- We exported 3 functions, the important one was getToken() which looked something like this:
```js
  function getToken() {
    const token = authContext.getCachedToken(CLIENT_ID);
    if (!token && !authContext.loginInProgress()) {
      return renewAuthToken(); // (uses loginRedirect)
    } else {
      return Promise.resolve(token);
    }
  }
```

We didn't have much protection around when this loads because angular-adal was able to handle it quite well, the important part that almost never caused a race condition was authContext.loginInProgress() e.g if we were already trying to auth then don't try to renew again...this is not the most robust logic but it worked for 2 years without any issues.

When we switched to msal I keep most of the same structure but I could no longer check `authContext.loginInProgress()` since msal-browser no longer had this function...after hitting my head against a wall for a while and reading the documentation more I finally found out what we had to do which was basically only call renewAuthToken (which will use loginRedirect) inside handleRedirectPromise (if resp was null and no user account was found) again we want to do this on onload. (Our getToken function used acquireTokenSilent if user was already logged in)

Before I gave to this realization, I keep running into race conditions because getToken would be called before handleRedirectPromise was fulfilled which led to this cat and mouse game. Finally coming to my point:

We can provide a better example that shows users how to make sure handleRedirectPromise is resolved before they call any other functions, I know in the docs it says you need to await this but doesn't show any examples. I think this is going to very confusing for beginners especially if they are doing it onPageLoad. I do realize that is mostly an application problem and how it is set up but it wouldn't surprise me many people have this setup.

Thanks
Jason

**Comment by tnorling** [comment]
@jaslloyd Have you seen our [onPageLoad sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-browser-samples/VanillaJSTestApp2.0/app/onPageLoad/auth.js)? The redirect flow is definitely confusing and we're always looking for ways to improve it and our documentation. We appreciate the feedback and will try to make this more clear in the docs!

**Comment by jaslloyd** [comment]
@tnorling Thanks for the reply, yeah I took a look at it and it is very similar to how we are actually doing it. I think the problem comes from even in that example what stops you using async function signIn before handleRedirectPromise? Imagine it is not a user action, lets say they load the page and it automatically called signIn...if they manage to call signin before handleRedirectPromise they will get an error because sigin "beat" handleRedirectPromise. 

I know you guys make it clear you need to await handleRedirectPromise but in that example its not really doing that right?

**Comment by tnorling** [comment]
That sample is intended to demonstrate signing in on page load without user interaction. There's nothing stopping a developer from moving the `signIn` call out of `handleRedirectPromise` but they do so at risk of breaking the flow we're trying to demonstrate with that sample. To clarify, are you asking for an example that shows `await handleRedirectPromise()` instead of `handleRedirectPromise().then(handleResponse)`?

**Comment by jaslloyd** [comment]
>There's nothing stopping a developer from moving the signIn call out of handleRedirectPromise but they do so at risk of breaking the flow we're trying to demonstrate with that sample.  
-
eah, 100% right and this was mostly my point that it leaves a lot to go wrong or can leave the developer scratching their head trying to figure out the race condition.

Maybe there could be an example of it showing `handleRedirectPromise` being called first then allowing the use of other commands or maybe add a bit more detailed description. I know this is a rather difficult problem to describe :)

**Comment by tnorling** [comment]
We can certainly add some comments to the sample with a warning and expand the docs with a disclaimer but I'm not sure I understand what exactly the ask is here beyond that. We have a sample demonstrating the flow and docs explaining `handleRedirectPromise` must be called when using redirect flows. If someone ignores our recommendations to make this work they shouldn't be surprised when it doesn't work. If it would be easier for you to submit a PR with what you're envisioning those changes look like, we are always open and more than happy to take a look!
