### ISSUE TITLE
MsalService has a constructor which is not compatible with Dependency Injection. It should probably not be @Injectable()

### ISSUE THREAD

**Issue by Jc25cool** [AzureAD/microsoft-authentication-library-for-js#2164]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `@azure/msal-angular@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.3.1`.

## Framework
Angular version 8

## Description
Trying to build the application on angular 8 version with ivy enabled

## Error Message
Application fails with the following runtime error in the console.
"MsalService has a constructor which is not compatible with Dependency Injection. It should probably not be @Injectable()"

## Security
- [ ] Is this issue security related? -- No

## Regression
- [ ] Did this behavior work before? 
The library was working when ivy was disabled.

## Browsers/Environment
- [x] Chrome
- [ ] Firefox
- [x] Edge
- [x] Safari
- [x] IE
- [ ] Other (Please add browser name here)

**Comment by jasonnutter** [comment]
@Jc25cool Does this error happen with Angular 9?
