### ISSUE TITLE
User type should be exported

### ISSUE THREAD

**Issue by davidmorissette** [AzureAD/microsoft-authentication-library-for-js#217]
Considering the fact that `UserAgentApplication` can return an object of `User` type, that type should therefore be exported.

I should be able to do this in my code:

```
import { User } from 'msal';

class MyClass {
    const user: User;
}
```

Please edit the index.ts file accordingly.

**Comment by rohitnarula7176** [comment]
Thank you for your feedback. You are correct. The issue is fixed in dev. You should now be able to import the user object.
