### ISSUE TITLE
Is there any plan for msal-angular 2.0?

### ISSUE THREAD

**Issue by Georgeoak** [AzureAD/microsoft-authentication-library-for-js#2172]
## Library
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@1.x.x`

## Description
Is there any plan for msal-angular 2.0 since MSAL.js 2.0 is released?
Thank you.

**Comment by jasonnutter** [comment]
Yes, we will soon be upgrading MSAL Angular to support MSAL.js v2. We will update our roadmap when we know more.

In the mean time, we will be adding a sample showing how to use MSAL.js v2 in Angular directly, #2167.

**Comment by Georgeoak** [comment]
Thank you for letting me know.
