### ISSUE TITLE
MSAL.js, B2C, and ADFS Provider: acquireTokenSilent failing

### ISSUE THREAD

**Issue by philip-young** [AzureAD/microsoft-authentication-library-for-js#2173]
## Library
- `msal@1.3.0`

## Framework
React 16.8.3

## Description
Using MSAL.js with B2C and ADFS Provider via Custom Policy - AcquireTokenSilent failing the first time then the user has to login again and it works.

I am using a React SPA app with the B2C ADFS provider the one given [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/identity-provider-adfs2016-custom?tabs=app-reg-ga) in the B2C documentation and am having difficulty when acquireTokenSilent is called after the user logs in: MSAL is reporting a timeout and I am getting an X-Frame Deny error with the iFrame. Previously I ran into this issue when using an Azure AD Provider, but solved it by using a login_hint, or in my case, the sid. Does the same kind of logic apply with ADFS? I tried to use a login_hint but the problem still persists. The user is directed back to login again after acquireTokenSilent fails and then is able to login in successfully. 

From what I have read in some Microsoft ADFS documentation [here](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/customize-http-security-headers-ad-fs) 

> Note that non-interactive logins can be performed via iFrame due to prior session level security that has been established.

It seems that this non-interactive action via iframe should be possible. Just wondering if there is anything I am missing. Thanks.

## Error Message
Timeout when calling acquireTokenSilent - getting X-Frame Deny error in iFrame in console of browser.
## Security
- Is this issue security related?
No
## Regression
- [ ] Did this behavior work before? 
No.

## MSAL Configuration

```js
Configuration = {
    auth: {
      authority: `https://mytenant.b2clogin.com/mytenant.onmicrosoft.com/b2c_1a_susi`,
      clientId: `GuidHere`,
      redirectUri: 'https://myapp.com/acc/authenticate',
      validateAuthority: false,
      postLogoutRedirectUri: (!!window ? window.location.origin : '') + '/signout'
    },
    cache: {
      cacheLocation: "localStorage",
      storeAuthStateInCookie: false
    }
  };
```

## Reproduction steps
1. Sign in to app with B2C Login using msal.LoginRedirect()
2. Msal goes on to get an access token via acquireTokenSilent
3. App works with token

## Expected behavior
When a user logs in initially via loginRedirect with the B2C ADFS provider, the subsequent call to acquireTokenSilent works.
## Browsers/Environment
- [x] Chrome (I'm not sure browsers apply here)
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by technical-boy** [comment]
Hi, @philip-young! Could you try opening the URL mentioned in the X-Frame Options Deny error in a new window and let us know what happens? Also, check out our [FAQ](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/docs/errors.md#refused-to-display--in-a-frame-because-it-set-x-frame-options-to-deny) on te X-Frame Options Deny error, hopefully it'll help.

**Comment by philip-young** [comment]
Hello again @technical-boy . I managed to get it all working with acquireTokenSilent. Basically what I needed to do like I said is to ensure there was no interaction required on the B2C UserJourney / Custom Policy side when the hidden iFrame makes its request. Once I got that working, it now works like a dream with the established session 🙂 closing this issue.
