### ISSUE TITLE
SSO with loginhint in angular 10

### ISSUE THREAD

**Issue by rajithakolan** [AzureAD/microsoft-authentication-library-for-js#2177]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [x] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Documentation location
- [ ] docs.microsoft.com
- [ ] MSAL.js Github Wiki
- [ ] README file
- [ ] Other (please fill in)
- [x] Documentation does not exist

## Description

Need a sample for using sso getting worked in multiple user flows in a single tenant.

**Comment by jasonnutter** [comment]
> Need a sample for using sso getting worked in multiple user flows in a single tenant.

Can you please provide more details about your scenario? What do you mean by "multiple user flows?" Can you provide some examples?

**Comment by rajithakolan** [comment]
@jasonnutter  Our project is having multiple applications using single azure AD B2C tenant but each application has its own userflow has diplayed in below image. If a user log into application using 'B2C_1_A_th_travelhub' useflow, then want to have sso login into angular application using 'B2C_1_bonvoyage' userflow. Need a sample angular project on using sso login using loginhint.

![image](https://user-images.githubusercontent.com/57349756/91150986-b3adeb00-e6da-11ea-85d8-629ddc5ea29d.png)

**Comment by rajithakolan** [comment]
@jasonnutter  Any update on the above?

**Comment by rajithakolan** [comment]
I  cannot find any documentation for this. Any inputs pls?
