### ISSUE TITLE
Multiple msal-browser instances

### ISSUE THREAD

**Issue by ingwarr23** [AzureAD/microsoft-authentication-library-for-js#2178]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Hi!
I have a noob question for which I was not able to find a clear answer. Maybe you can help me.

This is the scenario:
1. The user logs into our app, which is instantiated using the https://login.microsoftonline.com/common/ authority;
2. The user acquires an access token, with which he requests a list of all tenants. The first tenant in this list is the one in which he is currently logged in; the other tenants are the Azure Active Directories in which the user was added as a guest.
3. In order to log the user in another tenant (in an AAD in which he is a guest tenant) we create another msal instance with the authority:  https://login.microsoftonline.com/{guestTenantId}/. This instance will be used for all token requests, until the user changes the tenant again. If the user changes the tenant again, we create another instance of msal. (There is only one instance "active at a time", in the sense that we use the same variable to store all msal references).

I have read that there might be problems when there are multiple instances of msal-browser.
When the user wants to change the tenant, I think I could login him using a request with authority https://login.microsoftonline.com/{guestTenantId}/ without creating a new instance of msal. 

I have also read that:
"_Url of the authority which the application acquires tokens from. Defaults to
https://login.microsoftonline.com/common. If using the same authority for all request, authority should set
on client application object and not request, to avoid resolving authority endpoints multiple times._" (https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/request-response-object.md)

What is the correct and recommended way to approach this situation?

Thank you!

**Comment by technical-boy** [comment]
Hi, @ingwarr23 we recommend setting the authority in the request object with a single instance of MSAL, as it should be easier to manage.

**Comment by ingwarr23** [comment]
Thank you, @technical-boy !
