### ISSUE TITLE
AcquireTokenSilent does not return success

### ISSUE THREAD

**Issue by chigivigi** [AzureAD/microsoft-authentication-library-for-js#218]
I am working in single page application and am calling  userAgentApplication.acquireTokenSilent method  but it never returns a successful response.  AcquireTokenRedirect writes the token in my session and AcquireTokenPupup returns a successful response. Is ther a way to allow acquireTokenSilent  to return a successful response ?

**Comment by rohitnarula7176** [comment]
@chigivigi The acquireTokenSilent should return a token or error and save it in the browser storage. Can you please provide the fiddler trace for the issue. Also, if you can enable logging and attach them to the issue, that would be great. You can find instructions in the readme or the devApps folder on how to enable logging.
