### ISSUE TITLE
Logout function breaks with JSON error

### ISSUE THREAD

**Issue by jaslloyd** [AzureAD/microsoft-authentication-library-for-js#2181]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.0.2`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework

Vanilla JS

## Description

`calling logout` errors on `BrowserStorage.ts:157 Uncaught (in promise) SyntaxError: Unexpected token a in JSON at position 1`

## Error Message

```
Uncaught (in promise) SyntaxError: Unexpected token a in JSON at position 1
    at JSON.parse (<anonymous>)
    at BrowserStorage.getItem (BrowserStorage.ts:157)
    at index.es.js:2295
    at Array.forEach (<anonymous>)
    at BrowserStorage.CacheManager.removeAccountContext (index.es.js:2290)
    at BrowserStorage.CacheManager.removeAccount (index.es.js:2280)
    at AuthorizationCodeClient.getLogoutUri (index.es.js:3535)
    at PublicClientApplication.<anonymous> (PublicClientApplication.ts:491)
    at step (0.chunk.js:198)
    at Object.next (0.chunk.js:129)
    at fulfilled (0.chunk.js:81)
```

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? - I don't know, I was manually clearing local storage every time so it had nothing to clear.
Version:

## MSAL Configuration

```js
 // rest of file here....using loginRedirect
 function logout(): void {
    // localStorage.clear();
    const [user] = msalInstance.getAllAccounts();
    console.log(user);
    msalInstance.logout({
      account: user,
    });
```

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Expected behavior

Clears user localStorage of account that is signed in.

## Browsers/Environment
- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by AndriiBoiko1** [comment]
Have the same issue

**Comment by tnorling** [comment]
@jaslloyd @AndriiBoiko1 Closing as duplicate. Please track #2161 for this issue. Also please verify you don't have any non-msal cache values in local/session storage with a cache key that contains the words "idToken", "accessToken" or "refreshToken". PR #2115 will make MSAL's cache lookups more robust to avoid issues such as these
