### ISSUE TITLE
Implicit Flow activation

### ISSUE THREAD

**Issue by johannes-z** [AzureAD/microsoft-authentication-library-for-js#219]
I'm trying to use this library to get an access token, but I see no way of activating implicit flow in my app I registered in the application registration portal. Nor did I find an option where I can put the redirectURI in.

> you will also need to add the Web platform, check the "Implicit Flow" checkbox, and add the redirectURI to your application.

I could not find any more information about this - can you please elaborate?

**Comment by rohitnarula7176** [comment]
@johannes-z https://docs.microsoft.com/en-us/azure/active-directory/develop/guidedsetups/active-directory-javascriptspa Please use this doc for getting started. Please let me know if you still have questions.
