### ISSUE TITLE
CORS error: No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by thoo1** [AzureAD/microsoft-authentication-library-for-js#2193]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.0.2`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
React
## Description
When using msal-browser and attempting to sign in using a @gmail.com account, I encountered an error for the POST https://login.microsoftonline.com/organizations/oauth2/v2.0/token api call
Access to fetch at 'https://login.microsoftonline.com/organizations/oauth2/v2.0/token' from origin has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
I checked and the reply uri is configured to be of type: "SPA"

This only happens for @gmail.com or other non MSA accounts, it works fine for @microsoft.com accounts

Here is the x-ms-request-id for the failed call
x-ms-request-id: 7a62ba9c-0e88-40ce-aec3-a7b217f2e700

Also not sure why it is saying No 'Access-Control-Allow-Origin' header is present on the requested resource. because the OPTIONS request does return a header "Access-Control-Allow-Origin": * (wildcard)
## Error Message
Access to fetch at 'https://login.microsoftonline.com/organizations/oauth2/v2.0/token' from origin has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
    const publicClientApp = new PublicClientApplication({
      auth: {
        clientId: this.clientId,
        authority: this.authority,
        redirectUri: this.loginRedirectUri,
        postLogoutRedirectUri: this.postLogoutRedirectUri
      },
      cache: {
        cacheLocation: "localStorage",
        storeAuthStateInCookie: isIEOrOldEdge // https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1188#issuecomment-634281307
      },
      system: {
        loadFrameTimeout: 30000,
        tokenRenewalOffsetSeconds: 60,
        loggerOptions: {
          loggerCallback: MsalAuthContext.msalLoggerCallback,
          piiLoggingEnabled: false,
          logLevel: LogLevel.Verbose
        }
      }
    });
    const handleRedirectPromise = publicClientApp
      .handleRedirectPromise()
      .then(response => {
        this.account = response ? response.account : this.getAccount();
        if (!this.account) {
          CoreLogger.trackEvent(TelemetryEventName.Core_MSALAuthContext_login);
          this.publicClientApp.loginRedirect({
            scopes: this.scopes,
            authority: this.authority
          });
        }
      })
      .catch(error => {
        if (error) {
          this.trackError(error);
        }
      });
```

## Reproduction steps
Try to log into our site with a @gmail.com account
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Expected behavior
No CORS error

## Browsers/Environment (tested so far)
- [X] Chrome
- [ ] Firefox
- [X] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by stephenstroud** [comment]
Could be related to this [link](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL-browser-B2C-CORS-issue)

**Comment by technical-boy** [comment]
Hi @thoo1. Could you please share a fiddler trace with me over e-mail or Teams?

**Comment by thoo1** [comment]
@technical-boy sure, ill send over teams

**Comment by technical-boy** [comment]
Closing since the problem appears to have been resolved after consulting with @thoo1 .
