### ISSUE TITLE
can't change clientid at run time

### ISSUE THREAD

**Issue by sahusankar7** [AzureAD/microsoft-authentication-library-for-js#2194]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.3.0` or `@azure/msal@1.0.0`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.3.0`.

## Framework
angular
## Error Message
I can't change clientid at run time
is this possible for change clientid at run time?
## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Browsers/Environment
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by technical-boy** [comment]
Hi @sahusankar7 . We recommend creating a new instance of UserAgentApplication for a second clientId. Let us know if this solves your question!
