### ISSUE TITLE
Incorrect access token for API scope when using a personal Microsoft account

### ISSUE THREAD

**Issue by jviney** [AzureAD/microsoft-authentication-library-for-js#2195]
## Library
- [x] `@azure/msal-browser@2.1.0`
- [x] `@azure/msal-common@1.2.0`

## Framework

AngularJS 1.6.1

## Description

Setup:

* Frontend SPA (AngularJS) and a backend. Both access Graph APIs on behalf of the user.
* 1 Azure app.
* API scope under "Expose an API" in Azure (eg: api://1ae23a84-215a-4bd5-ae99-d54f1b7b211a/access_as_user).

In the browser, login with:

```js
msal.acquireTokenPopup({
  prompt: 'select_account',
  redirectUri: "https://local.com/redirect_microsoft.html",
  scopes: ["profile", "email", "openid", "offline_access", "user.read", "files.readwrite.all"],

  // Get consent for this scope, but it won't be included in the access token
  extraScopesToConsent: ["api://1ae23a84-215a-4bd5-ae99-d54f1b7b211a/access_as_user"]
})
```

This works correctly so far for personal and business Microsoft accounts.

Next, try to get an access token for the API scope. The returned token will be passed to our API, which uses the OBO flow to exchange it for its own access and refresh token. We store the refresh token for future use.

```js
msal.acquireTokenSilent({
  scopes: ["api://1ae23a84-215a-4bd5-ae99-d54f1b7b211a/access_as_user"],
  account: account // from the result of acquireTokenPopup()
})
```

In `@azure/msal-browser` 2.0.2 this step would fail for personal Microsoft accounts with the error `ClientAuthError: null_or_empty_id_token: The idToken is null or empty`. It succeeds in 2.1.0 even though the id token is not present. It works for non-personal Microsoft accounts in both versions, and includes an id token. I don't know why personal accounts do not get an id token here.

The access token is then passed to our API to perform the OBO flow. It works for non-personal Microsoft accounts, but fails for personal accounts with the error:

```
{
    "error": "invalid_request",
    "error_description": "AADSTS90023: Cross-origin token redemption is permitted only for the 'Single-Page Application' client-type.\r\nTrace ID: 32db7dc0-ab90-4a03-94bc-69522f919100\r\nCorrelation ID: 3b10fa8d-0527-4cad-a459-206f4086a731\r\nTimestamp: 2020-08-26 07:27:14Z",
    "error_codes": [
        90023
    ],
    "timestamp": "2020-08-26 07:27:14Z",
    "trace_id": "32db7dc0-ab90-4a03-94bc-69522f919100",
    "correlation_id": "3b10fa8d-0527-4cad-a459-206f4086a731"
}
```

## Regression

Did not work in 2.0.2.

## MSAL Configuration

```js
new PublicClientApplication({
  auth: {
    clientId: "<<client id here>>",
  },
  cache: {
    cacheLocation: "sessionStorage",
    storeAuthStateInCookie: false,
  }
})
```

## Expected behavior

* `acquireTokenSilent` should return an access token that is valid when used in the OBO flow for personal Microsoft accounts.

I'm not sure if this is actually a bug in MSAL. It may be a problem somewhere else with personal Microsoft accounts, or perhaps we aren't using the OAuth APIs correctly.

## Browsers/Environment
- [x] Chrome

Issue occurs with multiple personal Microsoft accounts.

Issue does not occur in testing with non-personal accounts across several different tenants.

**Comment by froatsnook** [comment]
I've been running into this lately, but can confirm that there's no more error message with 2.1.0. When I looked through the code I saw it wasn't actually using the account param when calling `acquireTokenSilent`, but rather using `this.getAccount()`. Not sure if this is still the case.

**Comment by technical-boy** [comment]
@jviney thanks for raising the issue. We believe this is an issue with the AAD service and we've raised this issue with that team. We'll let you know when we have further information.

**Comment by jviney** [comment]
Any update?

**Comment by jmckennon** [comment]
@jviney this is being tracked internally and worked on by another AAD team. I will leave this open as a work-in-progress for updates.

**Comment by jviney** [comment]
Any update?

**Comment by jviney** [comment]
I've retested this with `@azure/msal-browser` 2.10. The situation certainly seems to have improved - the issue is now that when using a personal account the backend OBO request doesn't provide a refresh token, where non-personal accounts do.

Example OBO response for personal account:

```
{"token_type": "Bearer", "scope": "https://graph.microsoft.com/.default https://graph.microsoft.com/User.Read https://graph.microsoft.com/Files.ReadWrite.All", "expires_in": 3557, "ext_expires_in": 3557, "access_token": "REMOVED"}
```

Example OBO response for non-personal account:

```
{"token_type": "Bearer", "scope": "email openid profile https://graph.microsoft.com/Files.ReadWrite.All https://graph.microsoft.com/User.Read https://graph.microsoft.com/.default", "expires_in": 3589, "ext_expires_in": 3589, "access_token": "REMOVED", "refresh_token": "REMOVED"}
```

The scopes are also different for the two scenarios. The personal account is missing the OpenID scopes `email openid profile`.

**Comment by jviney** [comment]
Ah - so it works if you explicitly add the `offline_access` scope to the OBO request for personal accounts. So the scope becomes: `https://graph.microsoft.com/.default offline_access`. Great!

The Azure app I'm using includes `openid profile email offline_access` in the default scopes - but perhaps they aren't being picked up correctly for personal accounts?

**Comment by hpsin** [comment]
Can you record the POST to /token being made by your server, and see what the `scope` parameter looks like? It should be `openid profile offline_access https:://graph.microsoft.com/.default` or similar, even before you use manually append `offline_access`

**Comment by jviney** [comment]
The scope sent to `/token` for non-personal accounts is `https:://graph.microsoft.com/.default`. The returned scopes are `email openid profile https://graph.microsoft.com/Files.ReadWrite.All https://graph.microsoft.com/User.Read https://graph.microsoft.com/.default`

**Comment by hpsin** [comment]
Thanks! This is a combination SDK bug and server side bug.  AAD considers "offline_access" to be part of MS Graph, so it gives you an RT since it's part of tokens for Graph.  MSA handles this differently and requires offline_access in the request, per OIDC spec. I'll file this bug internally. 

The SDKs should also be adding this in automatically if they expect there to be a refresh token provided.

**Comment by jviney** [comment]
Thanks - so is providing the OpenID scopes in the OBO request a sufficient workaround?

**Comment by hpsin** [comment]
Yup, for the issue you ran into.  Per OIDC if you want a refresh token you need to request it, so certainly that's the more standards-based way of making this work.

**Comment by jasonnutter** [comment]
> Thanks! This is a combination SDK bug and server side bug. AAD considers "offline_access" to be part of MS Graph, so it gives you an RT since it's part of tokens for Graph. MSA handles this differently and requires offline_access in the request, per OIDC spec. I'll file this bug internally.
> 
> The SDKs should also be adding this in automatically if they expect there to be a refresh token provided.

Thanks @hpsin, we'll take a look at fixing this.
