### ISSUE TITLE
Error getting access token when the page loads for the very first time after logging into the app using MSAL

### ISSUE THREAD

**Issue by SujitGodavarti** [AzureAD/microsoft-authentication-library-for-js#220]
I am using MSAL in my angular app for authentication purpose. I am able to successfully login into the app. After logging in, when I am trying to load the page with the API call for the very first time, I get an error 'User login is required' and there is no 'user' in the 'this.clientapplication' which I am logging in console as shown in the image below. 

![img1](https://user-images.githubusercontent.com/20764924/35130325-55da39be-fd14-11e7-984d-8caa2ddf5001.png)

But when I refresh the page that has the API call, I am able to get the token without error and the 'user' which was missing in the first case, is there after the refresh as shown in the image below.

![img2](https://user-images.githubusercontent.com/20764924/35130335-665027cc-fd14-11e7-9e06-1f6b3ea99374.png)

I am unable to figure out what I am missing when the page loads for the very first time. Please help me solve this issue.

**Comment by rohitnarula7176** [comment]
@SujitGodavarti the above error is thrown when you try to acquire an access_token prior to calling login first and having a signed in user. can you please attach a code repro for this issue along with instructions on how to run it.

**Comment by SujitGodavarti** [comment]
@rohitnarula7176  Hi. It would be a little difficult for me to attach a code repro. I debugged the code and kind of figured out the issue but I don't know why it is happening. I will mention it clearly and if you could not exactly figure out, then I will attach a code repro here. 

Part of the code in my authentication service is shown below. 

`constructor() {
        this.clientApplication =
            new Msal.UserAgentApplication(
                configSettings.clientID,
                this.authority,
                this.authCallback,
                {
                    redirectUri: window.location.origin
                }
            );
    }

    public login(): void {
        this.clientApplication.loginRedirect(configSettings.b2cScopes);
    }

    private authCallback(errorDesc: any, token: any, error: any, tokenType: any) {
        if (error) {
            console.error(`${error} ${errorDesc}`);
        }
    }`

As you can see above, 'login()' function is called when my app loads and I am redirected to login page.
After I enter login credentials, I am redirected to home page of the app but the 'authCallback' function is not getting called for the very first time and I don't have 'msal.idtoken' in sessionstorage as shown in below image.

![img1](https://user-images.githubusercontent.com/20764924/35255310-8471547a-0042-11e8-9300-a942542ccf04.png)

But when I refresh the page by clicking 'F5', the 'authCallback' function is called and there is 'msal.idtoken' in sessionstorage as shown below image.

![img2](https://user-images.githubusercontent.com/20764924/35255426-0fcf9054-0043-11e8-9d71-e0fd40505d99.png)

I don't know why is 'authCallback' not being called for the very first time. Please help me out.

**Comment by SujitGodavarti** [comment]
@rohitnarula7176 Hi. I opened a new issue relating to this one which is 'https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/232' and attached a code repo with instructions on how to run it in the 'README.md' file. So I will close this one.
