### ISSUE TITLE
Implicit flow silent authentication iFrame - Third party cookies blocked

### ISSUE THREAD

**Issue by kunalkankariya** [AzureAD/microsoft-authentication-library-for-js#2200]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ **]** `msal@1.3.4` or `@azure/msal@1.x.x`

## Description

I need some clarification with scenarios where third party cookies are blocked in implicit flow.

When the hidden iframe is loaded with the source as the authorization server's endpoint, login.microsoftonline.com, in our case, why isn't it able to access cookies that were set by the same domain earlier when third party cookies are blocked?

The iframe is trying to read cookies that were set by the same domain right?

Third party cookies block only incoming cookies from a different domain or does it also prevent iframe from accessing any cookies (irrespective of the domain, same or not)?

Also, when the attempt to silently authenticate fail the browser opens the login popup and uses a cookie to indicate the session is alive. Which cookie is that specifically ( ESTSAUTHPERSISTENT,ESTSAUTH)?  Is it a combination?

Thank you so much in advance :)

**Comment by technical-boy** [comment]
Hi @kunalkankariya .

>When the hidden iframe is loaded with the source as the authorization server's endpoint, login.microsoftonline.com, in our case, why isn't it able to access cookies that were set by the same domain earlier when third party cookies are blocked?
>
>The iframe is trying to read cookies that were set by the same domain right?

Cookies can be read and set either in a first-party context, i.e. where the domain is loaded in the top frame or a pop up, or in a third-party context, i.e. inside of an iframe inside a different domain. Privacy protection features such as Safari ITP prevent those cookies from being shared (i.e. cookies set for a given domain in a first-party context are not available when that domain is used in a third-party context).

You may find our [docs on handling Safari ITP](https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-third-party-cookies-spas), the [MDN docs on HTTP Cookies](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#Tracking_and_privacy), and the [Webkit blog on Privacy](https://webkit.org/blog/category/privacy/) helpful.

>Which cookie is that specifically ( ESTSAUTHPERSISTENT,ESTSAUTH)? Is it a combination?

We use a few different cookies to track login state (such as the ones you list here).

**Comment by kunalkankariya** [comment]
Thanks @technical-boy 

> cookies set for a given domain in a first-party context are not available when that domain is used in a third-party context
 
The domain open inside the iframe (third party context) can set cookies right? Can these cookies be accessible by the same domain in first party context? (vice-versa of the point above)

**Comment by technical-boy** [comment]
@kunalkankariya no, cookie storage is segmented. This means third-party cookie access is blocked for both scenarios.

**Comment by kunalkankariya** [comment]
@technical-boy Thank you!
