### ISSUE TITLE
Angular MSAL dependencies conflict on Angular 10

### ISSUE THREAD

**Issue by SimonWilliams-STL** [AzureAD/microsoft-authentication-library-for-js#2208]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [X] `msal@1.x.x` or `@azure/msal@1.4.0`
- [X] `@azure/msal-angular@1.1.1`

## Description
Updating to Angular 10 makes the project dependent on tslib^2.0.0. Since @azure/msal-angular is dependent on tslib^1.10.0 this generates an NPM dependency warning:
```
npm WARN @azure/msal-angular@1.1.1 requires a peer of tslib@^1.10.0 but none is installed. You must install peer dependencies yourself.
```
In my project, this does appear to be an inconsequential warning, but it would be good to get rid of the warning.

**Comment by technical-boy** [comment]
@SimonWilliams-STL thanks for the information, we'll address this in a future version of msal-angular. We'll let you know if we need more information!

**Comment by jasonnutter** [comment]
MSAL Angular v2 is now available in alpha, and this should no longer be an issue. We will not be fixing this in MSAL Angular v1.

https://github.com/AzureAD/microsoft-authentication-library-for-js/releases/tag/msal-angular-v2.0.0-alpha.0
