### ISSUE TITLE
Issues with MSAL.js using IE11 in corporate environments (Enable Protected Mode)

### ISSUE THREAD

**Issue by chesterhartin** [AzureAD/microsoft-authentication-library-for-js#221]
Hello! I am having an issue with this sample (https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp) in a corporate environment and can be simulated at home via checking the Enable Protected mode box (which I am unable to do at work due to domain policies (currently showing home setup)

![1](https://user-images.githubusercontent.com/1890420/35185707-234d238e-fdce-11e7-8026-3317939a6b60.PNG)

Running the bat file works great, I'm able to see the page:

![2](https://user-images.githubusercontent.com/1890420/35185708-23682e18-fdce-11e7-8dfe-adb1e0c8f1f2.PNG)

I get a nice friendly popup. I signup or login as normal:

![3](https://user-images.githubusercontent.com/1890420/35185709-2385029a-fdce-11e7-81fa-e993371c1bb0.PNG)

And then I get the parent form, now shown in the popup. 

![4](https://user-images.githubusercontent.com/1890420/35185710-23a33396-fdce-11e7-8a92-94374d373605.PNG)

Watching my console, it appears that things went well until it hit: 

GET / 304 1.550 ms - -
GET /null 200 2.382 ms - 4724

![5](https://user-images.githubusercontent.com/1890420/35185711-23be5da6-fdce-11e7-9476-1c5591427db7.PNG)

Noting the outdated msal.js version in the sample, I updated it to the latest and greatest, but no luck.

Which is all well and good if you are allowed to, but alas -- corporate policies. I tried this as a redirect as well, but no luck.

Further digging I came across this, which mentions that if you turn off this setting - voila, it works:

https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/16 

But as stated above, that only works **if you have the ability to do so**. 

Alternatively, I came across this: https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Using-msal.js-with-Internet-Explorer which has the whimsical "This just works in production" . Just tried it on azure, with every production environment setting I could think of, and no dice.  

The only "hack" I could find was to run IE 11 as administrator (if you have the permission). Any suggestions?

**Comment by rohitnarula7176** [comment]
@chesterhartin We are tracking this issue with the Edge browser team and unfortunately we do not have any other workaround as of now.

**Comment by allinagaraju** [comment]
I have the same issue and when we logged in always in the sessionStorage getting State as Invalid State.

**Comment by nehaagrawal** [comment]
@allinagaraju @chesterhartin  This is fixed and released in MSAL 0.2.2. Please check release notes for more details.
