### ISSUE TITLE
How do I authenticate using msal-browser@2.x.x

### ISSUE THREAD

**Issue by devdeer-emeissner** [AzureAD/microsoft-authentication-library-for-js#2210]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Hi MSAL Team, I am currently implementing authentication in my react app using MSAL 2.x.x with loginRedirect and handling the result in the handleRedirectPromise function, but for some reason, the handleRedirectPromise callback always receives null as the tokenResponse, even though I successfully authenticated myself. 

Another issue I have noticed is that getAllAccounts never returns null, like it is shown in the migration guide, but instead returns an empty array if there are no authenticated accounts.

 I've been following this [Migration Guide](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/v1-migration.md) because I have used MSAL 1.x in the past with no problems. 

Any help is greatly appreciated

[Here is my code](https://gist.github.com/devdeer-emeissner/e6245da6a537df634ed5a9e6d18a0205)

**Comment by technical-boy** [comment]
Hi, @devdeer-emeissner !

>Hi MSAL Team, I am currently implementing authentication in my react app using MSAL 2.x.x with loginRedirect and handling the result in the handleRedirectPromise function, but for some reason, the handleRedirectPromise callback always receives null as the tokenResponse, even though I successfully authenticated myself.

handleRedirectPromise will only return a token response when your application is returning from a redirect operation. If it returns null, that means that your app is not loading as a result of a redirect operation or handleRedirectPromise has already been called once in the page.

Could you confirm that this happens after returning from a redirect operation and that handleRedirectPromise isn't being called more than once?

>Another issue I have noticed is that getAllAccounts never returns null, like it is shown in the migration guide, but instead returns an empty array if there are no authenticated accounts.

Thanks for bringing this up, we're updating the migration guide as well as our FAQ.
