### ISSUE TITLE
How to control authorize endpoint oauth2/authorize vs oauth2/v2.0/authorize

### ISSUE THREAD

**Issue by gumowy-kaczak** [AzureAD/microsoft-authentication-library-for-js#2211]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
How to control authorize endpoint oauth2/authorize vs oauth2/v2.0/authorize?

It seems I have weird behavior for my clients authenticating in the angular. In most while logging in it utilizes `oauth2/authorize?response_type=code+id_token` with skipping `redirectUri` and overriding it to the  `.../.auth/login/aad/callback`.

I got report from colleagues and had it on my machine (cannot reproduce now) that they were routed to:  `oauth2/v2.0/authorize?response_type=id_token` with proper `redirectUri`.

Any idea where to look?

**Comment by technical-boy** [comment]
@gumowy-kaczak could you provide your MSAL configuration? Also, could you please confirm which MSAL libraries your using (specifically, are you using any server-side library such as MSAL .NET in addition to MSAL JS?)

**Comment by gumowy-kaczak** [comment]
Hello, sorry for missing those info, thought there was some simple switch:
Environment:
Angular client app with app registration connecting to web api with separate app registration.
Libraries:
    "msal": "^1.3.4",
    "@azure/msal-angular": ^1.0.0

I just realized that with `oauth2/v2.0/authorize` has improper `redirect_uri` url pointing to my configuration `postLogoutRedirectUri`.

````
https://login.microsoftonline.com/{CUT}/oauth2/v2.0/authorize?response_type=id_token
&scope={CUT}%2Fuser_impersonation%20openid%20profile
&client_id={CUT}
&redirect_uri={CUT}%2Flogin
&state={CUT}
&client_info=1
&x-client-SKU=MSAL.JS
&x-client-Ver=1.3.4
&client-request-id={CUT}
&response_mode=fragment&sso_reload=true
````


Msal/angular config:
````
  "msalConfiguration": {
    "auth": {
      "clientId": "{CLIENT ID AS GUID}",
      "authority": "https://login.microsoftonline.com/{AUTHORITY}",
      "validateAuthority": true,
      "navigateToLoginRequestUrl": true
	  "redirectUri": "https://{CLIENT_URL}"
	  "postLogoutRedirectUri": "https://{CLIENT_URL}/login"
    },
    "cache": {
      "cacheLocation": "localStorage"
    }
  },
  "msalAngularConfiguration": {
    "popUp": false,
    "consentScopes": [
      "https://{API_REGISTRATION}/user_impersonation"
    ],
    "unprotectedResources": ["./"]
	"protectedResourceMap": new Map([
      ["https://{API_URL}", "https://{API_REGISTRATION}/user_impersonation"],
    ])
  }
````
I have verified those config on site, running in command: `msal.msalAngularConfig` and `msal.msalConfig`.

App registration:
![image](https://user-images.githubusercontent.com/15362706/91751442-0dc01c00-ebc5-11ea-90a5-4b3e06b2bc12.png)
![image](https://user-images.githubusercontent.com/15362706/91754303-7ad5b080-ebc9-11ea-9a5b-f5adce1b3304.png)



To make it even more weird, we have two environments configured. The old one is returning to me constantly `/oauth2/authorize` endpoint and the new one is returning `oauth2/v2.0/authorize`.

Configuration of both is mirrored with different urls/guids.

I remember that Azure did some switch on November/December with app registrations.. 

So my question is.. is there a way to make it all behave that same? During cleanup process I tried to remove unused values and this caused disruption as sometimes we have v2.0 andpoint and sometimes not (and both require different redirect uris being registered).

**Comment by gumowy-kaczak** [comment]
Ach one more thing I just found.. when I perform logout it redirects me to `oauth2/v2.0/logout` and then when I try to login again it uses also `oauth2/v2.0/authorize`. 
When I enter with new browser window it then redirects again to.. `oauth2/authorize`..

**Comment by jmckennon** [comment]
@gumowy-kaczak Can you record a fiddler trace and email it to me at the email on my profile?

If you could also provide details on the "weird behavior" you're seeing and the differences between using the various endpoints, that would help as well.

**Comment by rangeranger** [comment]
@gumowy-kaczak : 

**How to control authorize endpoint oauth2/authorize vs oauth2/v2.0/authorize?**

1. If your app is registered with the legacy registration portal then it uses the V1 endpoint. If it is created with the new portal then it uses the V2 endpoint.

2. If your app is created with the legacy portal and if you want to use the V2 endpoint then you have to set the value of _**accessTokenAcceptedVersion**_ to 2. [Here ](https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-app-manifest#accesstokenacceptedversion-attribute)is the MS docs reference for the same.

[Here ](https://stackoverflow.com/a/45991564/7795138)is the Stackoverflow answer to your question.
