### ISSUE TITLE
forceRefresh for acquireTokenSilent throws no_tokens_found

### ISSUE THREAD

**Issue by AndriiBoiko1** [AzureAD/microsoft-authentication-library-for-js#2212]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [+] `@azure/msal-browser@2.0.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
"react": "^16.9.0",

## Description
When using acquireTokenSilent with forceRefresh: true -> getting an error "no_tokens_found"
When using acquireTokenSilent with forceRefresh: false -> token is retrieved from cache as expected BUT after token is expired (in an hour) it is not getting refreshed and again error "no_tokens_found" is thrown and you become logged out

## Error Message
no_tokens_found: No tokens were found for the given scopes, and no authorization code was passed to acquireToken. You must retrieve an authorization code before making a call to acquireToken().

## Security
- [ ] Is this issue security related?

## Regression
- [+] Did this behavior work before? 
Version: "msal": "^1.1.3",

## MSAL Configuration

```const msalInstanse = new PublicClientApplication({
    auth: {
      clientId,
      authority : 'https://{tenant}.b2clogin.com/tfp/tenant}.onmicrosoft.com/B2C_1_signupsignin'
      redirectUri,
      postLogoutRedirectUri,
      navigateToLoginRequestUrl: true,
      knownAuthorities: ['{tenant}.b2clogin.com'],
    },
    system: {
      loggerOptions: {
        loggerCallback: (level: LogLevel, message: string, containsPii: boolean): void => {
          if (containsPii) {
            return;
          }
          switch (level) {
            case LogLevel.Error:
              console.error(message);
              return;
            case LogLevel.Info:
              console.info(message);
              return;
            case LogLevel.Verbose:
              console.debug(message);
              return;
            case LogLevel.Warning:
              console.warn(message);
              return;
            default:
              console.debug(message);
          }
        },
        piiLoggingEnabled: true,
      },
      loadFrameTimeout: 25000,
      networkClient: new MsalFetchClient(), // custom network client(calls proxy instead of token endpoint directly) to fix B2C CORS issues
    },
    cache: {
      cacheLocation: 'localStorage',
      storeAuthStateInCookie: true,
    },
  });
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
```js
1. Sign In
  const signIn = () => {
      const requestParams = {
        scopes: ['https://{tenant}.onmicrosoft.com/{app_name}/read'],
        prompt: 'select_account',
      };

      msalInstanse.loginRedirect(requestParams);
  };
```
2. Verify info is in local storage
![image](https://user-images.githubusercontent.com/57752495/91710911-ae92e500-eb8d-11ea-93fb-265e80b1b043.png)
BUT
no "refresh_token" in response from token endpoint
https://tenant.b2clogin.com/tenant.onmicrosoft.com/b2c_1_signupsignin/oauth2/v2.0/token
![image](https://user-images.githubusercontent.com/57752495/91733583-60dca380-ebb2-11ea-9458-b26af3d431e6.png)

3. Make silent call
```
  const getInfoSilently = async () => {
    // eslint-disable-next-line no-shadow
    let authResponse;
    let interactionRequired;

    const account = getAccount(); // returns info from storage

    try {
      authResponse = await msalInstanse.acquireTokenSilent({
        scopes: ['https://{tenant}.onmicrosoft.com/{app_name}/read'],
        forceRefresh: true,
        account,
      });
    } catch (err) {

      // catch and show 'no_tokens_found'
      console.error(`${err.errorCode}>>>${err.errorMessage}`);

      interactionRequired = requiresInteraction(err);
    }

    return [authResponse, interactionRequired];
  };
```
4. See error in console
![image](https://user-images.githubusercontent.com/57752495/91711098-fe71ac00-eb8d-11ea-9351-b12dc96a693b.png)

5. acquireTokenSilent has thrown an error

## Expected behavior
1) forceRefresh: true -> return new token on each acquireTokenSilent call
2) no "no_tokens_found" error after token expired (1 hour) but successful token renewal should take place

## Browsers/Environment
- [+] Chrome
- [] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by tnorling** [comment]
@AndriiBoiko1 It looks like you are using B2C. Currently in order to get a refresh token in B2C scenarios you need to include the `offline_access` scope in the request. However, we strongly advise against doing this for production environments as including this scope will return a long lived refresh token. Please track issue #1999 for this issue as it is currently being worked on by the service and is expected to be completed soon. For now I'm going to close this as duplicate.

**Comment by AndriiBoiko1** [comment]
@tnorling Thanks for a quick reply, really appreciate that! I've tried to do what you suggested:

Added 'offline_access' to Sign in / acuireTokenSilent  scopes:
```
  const signIn = () => {
      const requestParams = {
        scopes: ['https://{tenant}.onmicrosoft.com/{app_name}/read',  'offline_access' ],
        prompt: 'select_account',
      };
      msalInstanse.loginRedirect(requestParams);
  };

``` 
```
  const getInfoSilently = async () => {
    // eslint-disable-next-line no-shadow
    let authResponse;
    let interactionRequired;

    const account = getAccount(); // returns info from storage

    try {
      authResponse = await msalInstanse.acquireTokenSilent({
        scopes: ['https://{tenant}.onmicrosoft.com/{app_name}/read', 'offline_access'],
        account,
      });
    } catch (err) {

      // catch and show 'no_tokens_found'
      console.error(`${err.errorCode}>>>${err.errorMessage}`);

      interactionRequired = requiresInteraction(err);
    }

    return [authResponse, interactionRequired];
  };
```

'no_tokens_found' error has gone, refresh token is in response BUT "null_or_empty_id_token" error appeared on silent call
localstorage:
![image](https://user-images.githubusercontent.com/57752495/91828652-165a3600-ec49-11ea-9469-063734928315.png)

token endpoint response:
![image](https://user-images.githubusercontent.com/57752495/91828901-6933ed80-ec49-11ea-9402-8dab635654a9.png)


error: 
![image](https://user-images.githubusercontent.com/57752495/91829571-50780780-ec4a-11ea-9ec5-06f910eea4bd.png)

**Comment by AndriiBoiko1** [comment]
also tried this:
```
  const getInfoSilently = async () => {
    // eslint-disable-next-line no-shadow
    let authResponse;
    let interactionRequired;

    const account = getAccount(); // returns info from storage

    try {
      authResponse = await msalInstanse.acquireTokenSilent({
        scopes: ['https://{tenant}.onmicrosoft.com/{app_name}/read'],      // NO 'offline_access'
        forceRefresh: true;                                                                           // BUT with this set to true
        account,
      });
    } catch (err) {

      // catch and show 'no_tokens_found'
      console.error(`${err.errorCode}>>>${err.errorMessage}`);

      interactionRequired = requiresInteraction(err);
    }

    return [authResponse, interactionRequired];
  };
```

The same effect: 'null_or_empty_id_token'

**Comment by tnorling** [comment]
@AndriiBoiko1 Can you update to version 2.1.0 and let me know if that fixes it? This was a known issue with the initial release of msal-browser which should have been fixed in a subsequent release.

**Comment by tnorling** [comment]
@AndriiBoiko1 Currently `acquireTokenSilent` does not automatically request scopes `openid` and `profile` which are required in order to get back an `idToken`. We plan to address this in an upcoming release but for now you can add these scopes to the request when you need an `idToken`. Unfortunately this may result in a cache miss if the server does not respond with those scopes so if performance is of concern you should only request `openid` and `profile` when you know your token is expired and needs to be refreshed. Apologies for the inconvenience!

**Comment by AndriiBoiko1** [comment]
@tnorling  Many many thanks to you! good luck with releases
