### ISSUE TITLE
BrowserAuthError: monitor_window_timeout: Token acquisition in popup failed due to timeout

### ISSUE THREAD

**Issue by kunalkankariya** [AzureAD/microsoft-authentication-library-for-js#2213]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@2.1.0` or `@azure/msal@2.1.0`

## Framework

Using MSAL-Browser with SharePoint SPFx webpart that simply pulls data from graph API (No other logic implemented)

## Description
Remove all cookies / cache of the browser.

Login to SharePoint for the first time directly to the page where the webpart is present  -> asks you to sign-in -> SPFx webpart starts loading -> Try to acquire token using acquireTokenSilent, which fails as the 'account - msalInstance.getAllAccounts()' is null -> Try to sign-in using ssoSilent

The error message keeps changing on refresh - It is either BrowserAuthError: monitor_window_timeout: Token acquisition in popup failed due to timeout

 at BrowserAuthError.AuthError [as constructor] (https://localhost:4321/dist/testwebpartmsal-web-part.js:1067:24)
    at new BrowserAuthError (https://localhost:4321/dist/testwebpartmsal-web-part.js:5798:28)
    at Function.u8tD.BrowserAuthError.createMonitorWindowTimeoutError (https://localhost:4321/dist/testwebpartmsal-web-part.js:5876:16)
    at https://localhost:4321/dist/testwebpartmsal-web-part.js:7541:45

OR

InteractionRequiredAuthError: login_required: AADSTS50058: A silent sign-in request was sent but no user is signed in

Now, the fiddler trace reveals that the response is always a redirect with query string as error: login_required, In case of both these errors.

While I know how to handle the error and initiate an interactive session. Why is the error different each time on refresh? This makes it hard to handle try, catch based on specific error.

## MSAL Configuration

const msalConfig: msal.Configuration = {
  auth: {
    clientId: "xxx",
    authority:
      "xxx",
    redirectUri:
      "xxx,
  },
  system: {
    loggerOptions: {
      loggerCallback: (level, message, containsPii) => {
        if (containsPii) {
          return;
        }
        switch (level) {
          case msal.LogLevel.Error:
            console.error(message);
            return;
          case msal.LogLevel.Info:
            console.info(message);
            return;
          case msal.LogLevel.Verbose:
            console.debug(message);
            return;
          case msal.LogLevel.Warning:
            console.warn(message);
            return;
        }
      },
    },
  },
};

## Browsers/Environment
- [ *] Chrome

**Comment by kunalkankariya** [comment]
**UPDATE** :  I have resolved this by changing the iframeHashTimeout config value to 10s now, from the default value of 6s. This is after I looked at the implementation of monitorIframeForHash.

**Comment by technical-boy** [comment]
Thanks for the update, closing since it's resolved.
