### ISSUE TITLE
msal-angular fails to login user on safari browser in Mac, Iphone and Ipad

### ISSUE THREAD

**Issue by FrancisMascarenhas** [AzureAD/microsoft-authentication-library-for-js#2214]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] msal@1.3.4` or `@azure/msal@1.1.1`

## Description
msal loginRedirect is returning loginSuccess but not returning token and getting an Authentication error. This happens safari browser in Mac, Iphone and Ipad. Desktop version works fine.
msal loginPopup working fine in all browser.

## Expected behavior
msal loginRedirect should works

## Browsers/Environment
- [ ] Safari

**Comment by technical-boy** [comment]
@FrancisMascarenhas could you please provide your MSAL configuration, a code snippet where you show your usage of MSAL and any logs from the MSAL Logger? Thanks!

**Comment by FrancisMascarenhas** [comment]
Hi, Request admin to please delete this issue. No longer valid
