### ISSUE TITLE
unprotectedResources ignored

### ISSUE THREAD

**Issue by rellis-of-rhindleton** [AzureAD/microsoft-authentication-library-for-js#2217]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `@azure/msal-angular@1.1.1`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework

Angular

## Description

I found this in the README after a couple of hours' worth of troubleshooting:

```
As of @azure/msal-angular@1.1.0, protectedResourceMap supports wildcard patterns that are supported by minimatch, and unprotectedResources is deprecated and ignored.
```

This is a breaking change. Using the default behavior of npm -- which sets up packages using the `^1.0.0` syntax -- installing the project fresh after this change ends up with the new behavior, while existing installs still have the old behavior (until they force npm to update their packages).

## Regression
- [x ] Did this behavior work before? 
Version: 1.0.0

## Expected behavior

A warning or error in the console while still honoring unprotectedResources until 2.x.

**Comment by rellis-of-rhindleton** [comment]
After looking into this further -- it doesn't look like there is a supported way to make one of my API's endpoints unprotected, while keeping others protected.

For example, if our service is running in an orchestrated container environment, we will have a health check endpoint that is NOT protected (because the back-end services that call it will never have a token). But all other endpoints do need to be protected. Under the new approach, how would we accomplish this?  Is there some syntax for minimatch that supports it? 

```
const resourceMap: [string, string[]][] = [
  [`${apiBaseUrl}/health`, null],
  [`${apiBaseUrl}`, ['scope1', 'scope2']],
];
```

The above code seems to work -- for now -- but browsing the source code for msal-core suggests that it shouldn't, and may not someday.

**Comment by jasonnutter** [comment]
@rellis-of-rhindleton The `null` pattern should work for v1. Can you also try using the negate syntax?

For example:

```js
const resourceMap: [string, string[]][] = [
  [`!${apiBaseUrl}/health`, ['scope1', 'scope2']],
];
```

We decided to ignore `unprotectedResources` because it was causing a number of other bugs, and we are planning to remove it in v2. This was not a scenario we had tested for (all requests for the same root path needing tokens except for one, just using the base url), unfortunately, so apologies about that. 

We'll keep your scenario in mind as we rework the interceptor for v2.

**Comment by rellis-of-rhindleton** [comment]
Understood. I suspect it’s not a super-rare use pattern though.

The way the interceptor is written, negation doesn’t work. You’re correct that we have other APIs to add to the list. Minimatch would need to support regular expressions for negation to work out, I think.

If using null will work for the foreseeable future then we can get by with that. It looks like some of the other libraries throw an error for that though, so I wanted to confirm it’s ok to do so.

**Comment by jasonnutter** [comment]
> If using null will work for the foreseeable future then we can get by with that. It looks like some of the other libraries throw an error for that though, so I wanted to confirm it’s ok to do so.

Yes, we'll make sure `null` is supported as a way to denote something explicitly as unprotected.

**Comment by rellis-of-rhindleton** [comment]
Good enough, thanks.
