### ISSUE TITLE
How to simplify the authentication flow given several unique app instances

### ISSUE THREAD

**Issue by mindcrash** [AzureAD/microsoft-authentication-library-for-js#2224]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
My team is building a multitenant application which uses a unique url per tenant/instance (as of now instance.applicationname.tld). We use AAD and MSAL to provide authentication and authorization for our application.

We currently are using a redirect URI per tenant to get the flow going but this likely will lead to a few hundred redirect URIs registered in AAD in the near future. We would prefer to bring this down to just one (basically how your own Azure Devops handles its authentication flow / redirection)

Is this scenario supported by MSAL v2? If so how?

**Comment by jmckennon** [comment]
To clarify your use case: you have one single multi-tenanted app. It uses a unique url per instance (possibly 100s of different urls). These URLs are inevitably included in each redirectUri, so you also need 100s of different redirectUris registered in the portal/AAD. Is this correct?

**Comment by mindcrash** [comment]
Hi Jake,

Yes, this is exactly the use case. I am currently working on a (rather crude) prototype which does something like the following:

1. Some necessary bits (e.g. current page, some form of correlation key) are encoded and put into the state parameter 
2. The authorization request is made against the AAD OAuth 2 v2 authorize endpoint
3. User signs in through either Microsoft Account or AAD signin flow
4. When successful the flow redirects back to the configured redirectURI with code and state attached
5. Code is exchanged for bearer token and additional information and cached serverside using info in state  
6. Redirect back to the caller using info in state
7. Bearer token and additional information are retrieved from the serverside cache, invalidated and made available to the SPA
8. Signin finalizes and the user is signed in

**Comment by mindcrash** [comment]
Since we actually need to support this on a pretty short term I am currently hacking on a forked dev branch to integrate some things which could work for us.

I will submit a PR when ready.

**Comment by pkanher617** [comment]
@mindcrash thanks for reaching out. MSAL.js can currently only support redirect URIs that are on the same domain as the application that is requesting the tokens. This is because we rely on local/sessionStorage to check state and nonce, as well as some other features that rely on the same-domain policy.

> My team is building a multitenant application which uses a unique url per tenant/instance (as of now instance.applicationname.tld). We use AAD and MSAL to provide authentication and authorization for our application.

You will, at the very least, have to register either a separate application or a separate redirect URI for each unique URL. Either that, or you will have to handle auth on the server-side, rather than in the browser.
