### ISSUE TITLE
The Login requested responseMode parameter is not respected (Redirect and Popup)

### ISSUE THREAD

**Issue by GabrielFerrarini** [AzureAD/microsoft-authentication-library-for-js#2228]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.1.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework
Next Js + React

## Description
Changing the response mode parameter to start a login flow doesn't have any effect on the popup or redirect urls that follow when either `loginPopup` or `loginRedirect` functions are called.

## Error Message
No error message

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
{
  "clientId":"app id",
  "redirectUri":"http://localhost:5555/auth",
  "authority":"https://tenant.b2clogin.com/tenant.onmicrosoft.com/B2C_1_SignIn",
  "knownAuthorities":["tenant.b2clogin.com"]
}
```

## Reproduction steps
Just execute the sign in flow

```js
const signIn = {
  responseMode:"query",
  scopes:["openid","profile","email"]
};

myMSALObj?.loginRedirect(signIn);

```

The issue can be seen in this sample as well: https://github.com/Azure-Samples/ms-identity-javascript-v2 - Just add the responseMode param in the loginRequest object in `app/authConfig.js`

## Expected behavior
URL Redirect should be in the format`https://tenant.b2clogin.com/tenant.onmicrosoft.com/b2c_1_signin/oauth2/v2.0/authorize?client_id=[client id]&scope=openid%20profile%20email&redirect_uri=http%3A%2F%2Flocalhost%3A5555%2Fauth&client-request-id=[request id]&response_mode=**query**&response_type=code&x-client-SKU=msal.js.browser&x-client-VER=2.1.0&x-client-OS=&x-client-CPU=&client_info=1&code_challenge=[code challenge]&code_challenge_method=S256&nonce=[nonce info]&state=[state info]

## Actual behavior
URL Redirect is in the format:
https://tenant.b2clogin.com/tenant.onmicrosoft.com/b2c_1_signin/oauth2/v2.0/authorize?client_id=[client id]&scope=openid%20profile%20email&redirect_uri=http%3A%2F%2Flocalhost%3A5555%2Fauth&client-request-id=[request id]&response_mode=**fragment**&response_type=code&x-client-SKU=msal.js.browser&x-client-VER=2.1.0&x-client-OS=&x-client-CPU=&client_info=1&code_challenge=[code challenge]&code_challenge_method=S256&nonce=[nonce info]&state=[state info]

## Browsers/Environment
- [X] Chrome
- [X] Firefox
- [X] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jmckennon** [comment]
>Changing the response mode parameter to start a login flow doesn't have any effect on the popup or redirect urls that follow when either loginPopup or loginRedirect functions are called.

This is currently by design as the library is built to specifically use the fragment response mode, which is done as a security consideration as the fragment of the URL is not sent to the server and modifying/clearing the fragment does not result in a new page load.

What's the use case that you're looking to use this feature for? We have considerations to implement something like this in the future to support scenarios such as using a client-side library and server-side library together (e.g., msal-node and msal-browser used together in the same app).

**Comment by GabrielFerrarini** [comment]
@jmckennon I don't have a specific use case. I thought it was supported because I didn't find any mention in the docs about it (I didn't reall ALL of the docs though). But I did found some comments in code stating otherwise: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/src/request/RedirectRequest.ts#L17

**Comment by jmckennon** [comment]
Yeah, we should change that comment in the `msal-common` library and clarify in our docs for `msal-browser` that it can only use the fragment response type. Those fields are made for the `msal-node` library (and potentially others in the future). Will mark this as an enhancement.
