### ISSUE TITLE
Token issues

### ISSUE THREAD

**Issue by zippy1981** [AzureAD/microsoft-authentication-library-for-js#223]
I have a pure client side SPA app (angular 4 with typescript) that is calling .NET service. Both are hosted on azure and both have separate client Ids.

My login logic looks like this:

```
    const loginResult: Promise<boolean> = this.userAgentApplication
      .acquireTokenSilent(scopes, null, user)
      .then((idToken: any): boolean => {
        console.debug('Got token from storage');
        return this.processToken(idToken);
      },
      (): Promise<boolean> => {
        console.log('Redirecting you to the login page.');
        this
          .userAgentApplication
          .loginRedirect(this.azureAdAuthConfig.scopes);
        return Promise.resolve(null);
      }
    );
```

The first problem is, immediately after logging in via the login page I end up in a state where `this.userAgentApplication.getUser()` returns a user but `acquireTokenSilent()` fails.

The second question is I am not sure how to create a token that the service can consume. If this was a .net mvc app, I know how I can use the net library to get a token for that service. 

If I just include the client id of the service app as an additional scope in `acquiateTokenSilent()` that does not work. I get this error in my session:

```
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidAudienceException: IDX10214: Audience validation failed. Audiences: '9c9d792e-d197-4c2d-b530-b44d0abe612c'. Did not match: validationParameters.ValidAudience: '8cd8391f-883f-4d09-9df2-b201cce0c7cf' or validationParameters.ValidAudiences: 'null'.
   at Microsoft.IdentityModel.Tokens.Validators.ValidateAudience(IEnumerable`1 audiences, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateAudience(IEnumerable`1 audiences, JwtSecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwt, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.<HandleAuthenticateAsync>d__6.MoveNext()
```

**Comment by rohitnarula7176** [comment]
@zippy1981 The above error is thrown during validation of id_token. It seems like the aud (app ID)  field contained in the id_token does not match. This error is not thrown in your .net service and not in msal js. Can you please enable logging in msal and attach the logs along with fiddler trace for this issue.

**Comment by zippy1981** [comment]
I'd prefer to share said logs via a private channel if possible.

Yes  understand why when I pass the token with the aud matching my SPAs client ID to the .net service, it returns the audience validation error.

My question is, once I resolve the first issue, how would I generate a token with msal.js with an audience of the second applicationid? If this was a .NET mvc app talking to a .net service I know how to do that inside of `OnAuthorizationCodeReceived` with `authContext.AcquireTokenAsync` or `AcquireTokenByAuthorizationCodeAsync`

**Comment by zippy1981** [comment]
@rohitnarula7176 I am closing this issues as I have opened an MSFT support case and getting resolution through that.  Thank you for your time.

**Comment by rohitnarula7176** [comment]
@zippy1981 Thanks for the update. I will close this issue then.
