### ISSUE TITLE
ClientAuthError: Login_In_Progress: Error during login call - login is already in progress.

### ISSUE THREAD

**Issue by rangeranger** [AzureAD/microsoft-authentication-library-for-js#2234]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.4.0` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.1.1`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework
Angular 10
## Description
I'm getting the below error when a user is trying to log in for the first time. The login is always successful. But, the error is logging in the browser console.

## Error Message
ClientAuthError: Login_In_Progress: Error during login call - login is already in progress.

## MSAL Configuration
```js
export const environment = {
  production: true,
  apiUrl: 'https://qwerty.azurewebsites.net/',
  graphUrl: 'https://graph.microsoft.com/v1.0/'
};

const protectedResource: Map<string, Array<string>> = new Map<string, Array<string>>();

protectedResource.set(environment.apiUrl + 'api/NoAuth', null);
protectedResource.set(environment.apiUrl, ['qwertyAppID/user_impersonation']);
protectedResource.set('https://graph.microsoft.com/v1.0/',
  ['Directory.Read.All', 'email', 'People.Read', 'People.Read.All', 'profile', 'User.Read', 'User.Read.All', 'User.ReadBasic.All']);

export const msalConfig: Configuration = {
  auth: {
    clientId: 'XXXXXX-YYY-ZZZZZZ',
    authority: 'https://login.microsoftonline.com/myTenantID',
  },
  cache: {
    cacheLocation: 'localStorage'
  },
  framework: {
    isAngular: true,
  }
};

export const angularOptions: MsalAngularConfiguration = {
  protectedResourceMap: protectedResource
};
```
**app.module.ts**
```js
@NgModule({
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    HttpClientModule,
    AppRoutingModule,
    MsalModule.forRoot(msalConfig, angularOptions),
    ServiceWorkerModule.register('ngsw-worker.js', { enabled: environment.production })
  ],
  schemas: [NO_ERRORS_SCHEMA],
  declarations: [
    AppComponent,
    MsalComponent
  ],
  providers: [
    Globals,
    AuthGuard,
    {
      provide: HTTP_INTERCEPTORS,
      useClass: MsalInterceptor,
      multi: true
    }
  ],
  entryComponents: [
    AppComponent,
    MsalComponent
  ]
  // bootstrap: [AppComponent]
})
export class AppModule {
  constructor() {
    console.log('APP Module Constructor!');
  }

  ngDoBootstrap(ref: ApplicationRef) {
    if (window !== window.parent && !window.opener) {
      console.log('Bootstrap: MSAL');
      ref.bootstrap(MsalComponent);
    }
    else {
      // this.router.resetConfig(RouterModule);
      console.log('Bootstrap: App');
      ref.bootstrap(AppComponent);
    }
  }
}
```
**app.routing.ts**
```js
const routes: Routes = [
  {
    path: '',
    redirectTo: '/abc/def',
    pathMatch: 'full',
    canActivate: [MsalGuard]
  },
  {
    path: '',
    component: SomeComponent,
    canActivate: [MsalGuard],
    canActivateChild: [AuthGuard],
    children: [
      {
        path: 'abc',
        loadChildren: () => import('../app/views/abc/abc.module').then(m => m.abcModule)
      }
    ]
  },
  {
    path: 'noAuth',
    loadChildren: () => import('../app/views/no-auth/no-auth.module').then(n => n.NoAuthModule)
  }
];

@NgModule({
  imports: [RouterModule.forRoot(
    routes,
    {
      useHash: false,
      initialNavigation: isInIframe() ? true : undefined
    },
  )],
  exports: [RouterModule]
})
export class AppRoutingModule { }

export function isInIframe() {
  return window !== window.parent && !window.opener;
}
```
## Browsers/Environment
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by rangeranger** [comment]
I get _**ClientAuthError: Login_In_Progress: Error during login call - login is already in progress.**_ in local. In production, it is always throwing an error **_ClientAuthError: Token renewal operation failed due to timeout_**. I use sessionStorage and I don't why it gives Token renewal operation failed error when the user is logging in for the first time.

**Comment by anth-git** [comment]
1. initialNavigation should be `disabled` when in an iframe. So if you need it for some reason, it should be `initialNavigation: isInIframe() ? 'disabled' : true` and if you don't need it, it can be just `initialNavigation: 'disabled'`
2. If still doesn't work, you can try do downgrade to previous version `"msal": "1.3.4"`. I encountered some problems with `1.4.0`
3. It probably has nothing to do with msal issues, but your routing looks weird (why do you need two routes to empty path?)

**Comment by rangeranger** [comment]
@anth-git : Thanks for your quick response. I changed to `initialNavigation: isInIframe() ? 'disabled' : 'enabled'` I still get the error **ClientAuthError: Login_In_Progress: Error during login call - login is already in progress in my Local.** . Also, sometimes it gives an error **The selector "app-root" did not match any elements**. It is because of using MsalComponent. In production and in local, user is able to login successfully. I just want to make sure I'm not doing anything wrong.

**Comment by Rahul-P** [comment]
the issue still persists. Token received back from B2C is correct. Angular App just drops the ball and reports the error: 
1.4.0-Error Error during login:
Login_In_Progress: Error during login call - login is already in progress.

**Comment by jmckennon** [comment]
@rangeranger @Rahul-P Can you try setting `redirectUri` to a page that does not require auth, like a blank html page?

**Comment by rangeranger** [comment]
@jmckennon : What to do if the app doesn't have a page that doesn't require auth?

**Comment by igorvvv** [comment]
I have the same issue. 
Tried msal 1.3.4 as well as setting redirectUri to a page without auth. Nothing helps.

**Comment by Rahul-P** [comment]
@jmckennon gave up for now mate. The combination that worked for me is: azure/msal-angular@1.1.0 and msal@1.3.3-beta.0

Had to do a fair bit of configuration, especially to subdue client auth error but for now the world seems at peace again. 

watching the issue closely as soon as a formidable fix is in i will upgrade to the latest and the greatest.

cheers.

**Comment by igorvvv** [comment]
The problem, as I see it, is that when 'navigateToLoginRequestUrl' is set to true, msal stores in a cache only url path, say '/workflow', but when it processes hash, it compares path to full url. 
There is no match, and another 
window.location.assign(`${finalRedirectUrl}${hash}`);  
is made.
This redirect hits MsalGuard in Angular and yes, two login requests collide. 
Screenshots attached to illustrate. I can provide .har file and logs is required. 
![msal-issue-guard](https://user-images.githubusercontent.com/15187095/94013412-23a8b180-fdfe-11ea-9d60-ab3a20da007a.png)
![msal-issue-compare-currentUrl-loginUrl](https://user-images.githubusercontent.com/15187095/94013418-286d6580-fdfe-11ea-83ed-796e1d9749d5.png)

**Comment by rangeranger** [comment]
Nowadays most of the apps are SPA, it's so tough to explain to the business that **Microsoft MSAL library** **sucks** and we don't have other options to achieve SSO. So many issues with every version. Sometimes I get thoughts like to create a change.org petition to Satya Nadella to hire better and more developers in the MSAL team and fix all the open issues.

It won't work in Safari. Can't ask users to use only Chrome. It's so painful to deal with the MSAL library and it's issues.

**Comment by rangeranger** [comment]
Here is my petition [link](http://chng.it/MF6DC7XBTQ). If anyone agrees with me then please sign it

**Comment by Rahul-P** [comment]
@rangeranger i absolutely do agree :)

**Comment by jasonnutter** [comment]
@rangeranger By participating in this repository you agree to adhere to the Microsoft Open Source Code of Conduct: https://opensource.microsoft.com/codeofconduct/

Failure to adhere may result in permanent banishment from this repository.

**Comment by jasonnutter** [comment]
> The problem, as I see it, is that when 'navigateToLoginRequestUrl' is set to true, msal stores in a cache only url path, say '/workflow', but when it processes hash, it compares path to full url.
> There is no match, and another
> window.location.assign(`${finalRedirectUrl}${hash}`);
> is made.
> This redirect hits MsalGuard in Angular and yes, two login requests collide.
> Screenshots attached to illustrate. I can provide .har file and logs is required.
> ![msal-issue-guard](https://user-images.githubusercontent.com/15187095/94013412-23a8b180-fdfe-11ea-9d60-ab3a20da007a.png)
> ![msal-issue-compare-currentUrl-loginUrl](https://user-images.githubusercontent.com/15187095/94013418-286d6580-fdfe-11ea-83ed-796e1d9749d5.png)
> 
> With 'navigateToLoginRequestUrl=false' login is successful, though it's not really a solution.

This specific issue should be fixed in the latest version of MSAL Angular, which will contruct an absolute url instead of a relative url. Please upgrade to `@azure/msal-angular@1.1.1` and let me know if this is still an issue.

**Comment by jasonnutter** [comment]
> @jmckennon : What to do if the app doesn't have a page that doesn't require auth?

@rangeranger As long as you are not using redirects for interactions (which it doesn't look like you are), you can set the `auth.redirectUri` configuration value to the url for a blank html page. You can do this by creating an html file (e.g. `auth.html`) and putting it in the `assets` folder of your app, then registering the full url for that page in the Azure portal as a redirect URI and setting it in the configuration in your code. Please try this and let me know if you still get the error.

**Comment by rajeshvinayagam** [comment]
Am still having the issue with the latest version of @azure/msal-angular@1.1.1. Can you help with the request.
