### ISSUE TITLE
MSAL v2 App Registration with CLI

### ISSUE THREAD

**Issue by h3rmanj** [AzureAD/microsoft-authentication-library-for-js#2236]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
For msal.js v2 to work properly, the reply urls in Azure has to be specified under "Single Page Application". This is available during creation of an App Registration in the UI. Is the same possible with the Azure CLI? One would think the command would be along the lines of `az ad app create --display-name my-app --reply-urls http://localhost:3000` with an additional `--spa` option etc, but the CLI today doesn't seem to differentiate between reply-urls from web or spa. How would one do it with the current version? And are there plans to make it easier in the future?

**Comment by derisen** [comment]
@h3rmanj this option is not available at the moment unfortunately, but it is in the backlog (feel free to raise a user voice [here](https://feedback.azure.com/forums/169401-azure-active-directory)). You could alternatively use MS Graph to [create an application](https://docs.microsoft.com/en-us/graph/api/application-post-applications?view=graph-rest-1.0&tabs=http), which gives you more options and flexibility.

**Comment by h3rmanj** [comment]
Not optimal, but got it working by calling MS Graph from the CLI.  
`az rest -u https://graph.microsoft.com/v1.0/applications -m post -b '{\"displayName\":\"MyApp\",\"spa\":{\"redirectUris\":[\"http://localhost:3000\"]}}'`

Did some research, and `az ad` currently uses the Azure Graph, which does not support SPA. They have plans to move over to MS Graph, when that gets implemented I'm guessing support for spa will too, so I won't bother with user voice.
