### ISSUE TITLE
couldn't get token from acquiretokenpopup,opens the popup ,still have an 404 issue,after entered  the credentials in popup

### ISSUE THREAD

**Issue by ssunkara79** [AzureAD/microsoft-authentication-library-for-js#2237]
Please follow the issue template below. 

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Upcoming Library
- [ ] `@azure/msal-node@1.x`

## Source
- [ ] Internal (MSAL.js team)
- [ ] Customer request

**Comment by jmckennon** [comment]
@ssunkara79 We'll need more information to help you with the problem, can you please fill out the provided issue template with your config, versions, and msal usage?

**Comment by ssunkara79** [comment]
using this "@azure/msal-angular": "^0.1.1" to authenticate B2C Account,we are using MSAL Guard for routes.

Below is the authentication code
import { Injectable, Inject } from '@angular/core';
import { HttpClient } from '@angular/common/http'
import { User } from '../../account/account.user';
import { Observable } from 'rxjs/Observable';
import * as Msal from 'msal';

import { EnvService } from '../../env.service';
@Injectable()
export class AuthenticationService {
 

  private projectURL = null;
  private headers = new Headers({ 'Content-Type': 'application/json' });
  private clientApplication: Msal.UserAgentApplication;
 
  private authority = ""; //environment.instance + environment.tenant + "/" + environment.signUpSignInPolicy;

  constructor(private http: HttpClient, @Inject('BASE_URL') private baseUrl: string, private _env: EnvService) {
    this.projectURL = this.baseUrl + "api/Token";
    
    this.authority = _env.instance + _env.tenant + "/" + _env.signUpSignInPolicy;
   
    this.clientApplication = new Msal.UserAgentApplication(_env.clientID, this.authority, function (errorDesc, token, error, tokenType) {

      if (token) {
        localStorage.setItem('token', token);
      }
    },
      {
        validateAuthority: false,
        cacheLocation: 'localStorage',
        redirectUri: this.getFullUrl(window.location.href),
      });
  }
  private getFullUrl(url: string): string {
    // this create a absolute url from a relative one.
    const pat = /^https?:\/\//i;
    return pat.test(url) ? url : this.origin() + url;
  }

  private origin() {
    return (window.location.origin) ? window.location.origin :
      window.location.protocol + '//' + window.location.hostname + (window.location.port ? ':' + window.location.port : '');
  }

  private authCallback(errorDesc: any, token: any, error: any, tokenType: any) {
    if (token) {
      localStorage.setItem('token', token);

    }
    else {

      console.log(error + ":" + errorDesc);
      
    }

  }
  loginAzure() {
    this.clientApplication.loginRedirect(this._env.b2cScopes);
  }
  login(username: string, password: string): Observable<User> {


    var json = JSON.stringify({ Username: username, Password: password });
    return this.http.post(this.projectURL, { Username: username, Password: password })
      .map((response) => <User>response)




  }

  getUserfromDB(): Observable<User> {

    return this.http.get(this.baseUrl + "api/user/getUserbyAzureID")
      .map((response) => <User>response)
  }
  public getLoggedInUser() {
    var azureusre = JSON.parse(localStorage.getItem('Azureuser'));
    if (azureusre == null) {
      localStorage.setItem('Azureuser', JSON.stringify(this.clientApplication.getUser()));
      azureusre = JSON.parse(localStorage.getItem('Azureuser'));
    }
    return azureusre;
  }


  public getAuthenticationToken() {
    
    return this.clientApplication.acquireTokenSilent(this._env.b2cScopes)
      .then(token => {
        console.log("Got silent access token: ", token);
        localStorage.setItem('token', token);
        
        return token;
      }).catch(error => {
        console.log("Could not silently retrieve token from storage.", error);
        return this.clientApplication.acquireTokenPopup(this._env.b2cScopes)
          .then(token => {
            console.log("Got popup access token: ", token);
            localStorage.setItem('token', token);
            return token;
          }).catch(error => {
            console.log("Could not retrieve token from popup.", error);
            //this.clientApplication.acquireTokenRedirect(this.tenantConfig.b2cScopes);
            return Promise.resolve("");
          });
      });
  }
  logout() {
    // console.log(this.getAuthenticationToken())
    localStorage.clear();
    // console.log("user", this.clientApplication.getUser())
    this.clientApplication.logout();
    //this.router.navigate([''])
  }



  public getToken() {
    return localStorage.getItem('token');
  }

  public getUser() {
    return localStorage.getItem('user');
  }



  public isAuthenticated(): boolean {
    // get the token
    var token = localStorage.getItem("Azureuser")

 
    if (token != null)
      return true;
    else
      return false;
  }



}

**Comment by ssunkara79** [comment]
Getting the below 2 errors
This application does not have sufficient permissions against this web resource to perform the operation. Could not silently retrieve token from storage. 
AADB2C90077: User does not have an existing session and request prompt parameter has a value of 'None'.

**Comment by jmckennon** [comment]
>Getting the below 2 errors
This application does not have sufficient permissions against this web resource to perform the operation. Could not silently retrieve token from storage.
AADB2C90077: User does not have an existing session and request prompt parameter has a value of 'None'.

Can you clarify: are you getting both of these errors from calling `acquireTokenSilent` or from calling `acquireTokenPopup`?

**Comment by ssunkara79** [comment]
from acquireTokenPopup

**Comment by jmckennon** [comment]
@ssunkara79 can you provide the full set of errors/logs that you're seeing? If you're receiving the error "Could not silently retrieve token from storage", it would be very unlikely that it came from `acquireTokenPopup`, as that function does not make a silent call. Can you also provide the browsers and their versions that you're seeing this functionality in?

**Comment by ssunkara79** [comment]
I am checking on Google chrome,Version 85.0.4183.102

First it opens the popup,after I enter the credentials closes the popup and getting this error
Could not silently retrieve token from storage. AADB2C90077: User does not have an existing session and request prompt parameter has a value of 'None'.
Correlation ID: 934f2d15-3f1c-4412-aff3-e72580ae8359
Timestamp: 2020-09-18 12:56:56Z
|interaction_required

and popup opens again,after entering the credentials,this time it will shows the two errors in console

Could not retrieve token from popup. AADB2C90205: This application does not have sufficient permissions against this web resource to perform the operation.
Correlation ID: f66fa77f-c12e-4966-af5b-4c226f6a813c
Timestamp: 2020-09-18 13:02:59Z
|invalid_request
VM10 main.9425218ffd8f6519ba1a.js:1 Could not silently retrieve token from storage. AADB2C90205: This application does not have sufficient permissions against this web resource to perform the operation.
Correlation ID: f66fa77f-c12e-4966-af5b-4c226f6a813c
Timestamp: 2020-09-18 13:02:59Z
|invalid_request[
![error1](https://user-images.githubusercontent.com/70937077/93601354-b4d2ef00-f9de-11ea-8927-6851e3ca7c35.png)
![error2](https://user-images.githubusercontent.com/70937077/93601556-ffed0200-f9de-11ea-9619-f1b465fa03e2.png)

](url)

**Comment by jmckennon** [comment]
This looks like an issue/question for B2C, can you [file an issue with the B2C support team](https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options)? Feel free to link this issue to it.
