### ISSUE TITLE
SSO between apps

### ISSUE THREAD

**Issue by BristolJim** [AzureAD/microsoft-authentication-library-for-js#2240]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.1.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

I'm running the following sample app:

https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-browser-samples/VanillaJSTestApp2.0/app/ssoSilent

I'm having trouble with SSO between apps. What I'm trying to achieve is a silent login to the sample app when I'm already logged in via Dynamics 365. The Azure app registration for the sample is in the same directory as Dynamics 365.

I am met with:

`Silent Error: InteractionRequiredAuthError: interaction_required: Seamless single sign on failed for the user. This can happen if the user is unable to access on premises AD or intranet zone is not configured correctly`

I can then log in via loginRedirect or loginPopup, but I don't want the end user to have to do this. The eventual goal is an SPA that can be iframed into Dynamics 365, hence not wanting to ask the user to log in (again).

Any help will be greatly appreciated.

**Comment by jmckennon** [comment]
I am assuming that you're using the sample out-of-the-box. You will need to change the authority in `authConfig.js` to match the authority with whatever app you're trying to get SSO with. If this is just logging in with a school or work account to Dynamics 365, you will probably want to use the default common authority of `https://login.microsoftonline.com/common/`. The sample app will not work with its currently written authority, as it is setup to work with our internal test accounts.

**Comment by BristolJim** [comment]
Thanks for the quick reply. 

I have configured authConfig.js with the relevant authority `https://login.microsoftonline.com/<our tenant id>`
I think the configuration is good as I can login by calling `signIn("loginRedirect")`. In fact, with interaction, it all works ok.

I think the issue I have is that *the first time* a user visits the SPA, `myMSALObj.getAllAccounts()` in ` handleResponse()` returns an empty array (where I'm hoping to use `myMSALObj.getAllAccounts()[0].username` as the `loginHint` for `myMSALObj.ssoSilent` (rather than using the hard-coded `loginHint` in `authConfig.js`).

If this is the case, then the question is how do I get the username of the user currently logged in to Dynamics 365 to use as the login hint?

Thanks again.

**Comment by jmckennon** [comment]
> I think the issue I have is that the first time a user visits the SPA, myMSALObj.getAllAccounts() in handleResponse() returns an empty array (where I'm hoping to use myMSALObj.getAllAccounts()[0].username as the loginHint for myMSALObj.ssoSilent (rather than using the hard-coded loginHint in authConfig.js).
>
> If this is the case, then the question is how do I get the username of the user currently logged in to Dynamics 365 to use as the login hint?

This is for you as the app developer to figure out. The `msal` library does not have the ability to know if a user is already logged into another app without being explicitly told so. One method to accomplish this is to pass the `loginHint` in a query parameter and have the second application parse the `loginHint` from the query parameter and pass it to `msal` (this technique could also be used to solve the iframe scenario). If that's not possible or desired, your application can invoke `loginRedirect` or `loginPopup` which should complete very quickly if the user has an active AAD session.

**Comment by BristolJim** [comment]
Hi @jmckennon,

> This is for you as the app developer to figure out.

Yes, understood, and I have a mechanism for doing that now. Unfortunately, having been round the loop many times now, I'm back with the initial issue with `ssoSilent` failing, but only under some circumstances. I'll detail the steps to explain...

* Clear all cookies & storage in the browser (Chromium)
* Log on to Dynamics 365
* Visit my SPA
* `ssoSilent` works (given that I supply the login hint)

That's all good, and exactly what I want to happen.

Now, in a different browser (Chrome), where I have not cleared the cookies & storage:

* Log on to Dynamics 365
* Visit my SPA
* `ssoSilent` fails saying **Seamless single sign on failed for the user. This can happen if the user is unable to access on premises AD or intranet zone is not configured correctly**

In this scenario, calling `loginRedirect` after `ssoSilent` does work, but not when the SPA is in an iframe as if fails with **redirect_in_iframe: Code flow is not supported inside an iframe. Please ensure you are using MSAL.js in a top frame of the window if using the redirect APIs, or use the popup APIs.**

Given that the `ssoSilent` flow works for me in a browser with all cookies and storage cleared, it seems I have the code, app registration, auth config etc. all good. I'm therefore thinking that in the browser where `ssoSilent` fails, there is some cookie or local storage thing going on that's causing it to fail.

I don't really want to clear cookies and storage in that browser as the same issue might re-surface when I have this stuff out in the wild. I'd rather work out why the `ssoSilent` call is failing and work out a way around it.

**Comment by jmckennon** [comment]
@BristolJim Can you try disabling SSO and see if you still see the same errors? This page gives some information about SSO [here](https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-sso-quick-start).
