### ISSUE TITLE
Doesn't compile with Typescript

### ISSUE THREAD

**Issue by sikemullivan** [AzureAD/microsoft-authentication-library-for-js#2243]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x ] `@azure/msal-browser@2.1.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework
React with Typescript

## Description
I created a React application with Typescript. Created an authentication service that uses msal-browser. The service fails to compile.

## Error Message
```
/node_modules/@azure/msal-common/dist/src/authority/Authority.d.ts
TypeScript error in /node_modules/@azure/msal-common/dist/src/authority/Authority.d.ts(66,17):
Property 'aadInstanceDiscoveryEndpointUrl' implicitly has type 'any', because its get accessor lacks a return type annotation.  TS7033

    64 |      */
    65 |     private discoverEndpoints;
  > 66 |     private get aadInstanceDiscoveryEndpointUrl();
       |                 ^
    67 |     private validateAndSetPreferredNetwork;
    68 |     /**
    69 |      * Perform endpoint discovery to discover the /authorize, /token and logout endpoints.
```

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 

Version:

## MSAL Configuration & Reproduction steps
```js
import { PublicClientApplication, Configuration, RedirectRequest } from "@azure/msal-browser";

export class AuthenticationService {
    private _msal: PublicClientApplication;

    constructor(
    ) {
        const msalConfig: Configuration = {
            auth: {
                clientId: "myappguid",
                authority: "https://login.microsoftonline.com/mytenantguid/",
                redirectUri: `${window.location.origin}/auth-callback`
            },
            cache: {
                cacheLocation: "localStorage", // This configures where your cache will be stored
                storeAuthStateInCookie: false // Set this to "true" if you are having issues on IE11 or Edge
            },
        };

        this._msal = new PublicClientApplication(msalConfig);
    }

    signIn(): Promise<void> {
         const req : RedirectRequest = {
             scopes : ["openid", "profile", "offline_access"]
         };
         return this._msal.loginRedirect(req);
        
    }

}

```

## Expected behavior
It should compile. 

## Browsers/Environment
- [x ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by pkanher617** [comment]
@sikemullivan What version of typescript are you using in your project?

This may be an issue where `"noImplicitAny"` is running incorrectly on Typescript versions <3.7. Here are some similar and related issues:

- https://github.com/vercel/next.js/issues/9996
- https://github.com/microsoft/TypeScript/issues/33894
- https://github.com/aws/aws-cdk/issues/5497

 If this isn't a typescript version issue happy to take a look at how to fix this.

**Comment by sikemullivan** [comment]
The dev dependency is typescript 3.6.4. I'm using the latest Visual Studio .NET Core 3.1 React + Redux template. 

I tried turn setting noImplicitAny with both true and false. That didn't help at all. I modified /node_modules/@azure/msal-common/dist/src/authority/Authority.d.ts manually to get it compiling. 

```
private get aadInstanceDiscoveryEndpointUrl() : string;
```

**Comment by pkanher617** [comment]
@sikemullivan Ideally the TS shouldn't erroring on private getters, this is the bug that I am referencing above. 

> I tried setting noImplicitAny with both true and false.

Strange, I figured setting this to false would have fixed it. Upgrading to Typescript 3.7+ should fix the issue until we can get a new release out. Thanks for bringing this to our attention!

**Comment by sikemullivan** [comment]
@pkanher617 I switched to using oidc-client instead of MSAL. I'll try going back to MSAL sometime in the future. Should I leave this issue open?
