### ISSUE TITLE
MSAL ISSUE in IE11

### ISSUE THREAD

**Issue by allinagaraju** [AzureAD/microsoft-authentication-library-for-js#225]
Hi Team,

I am using MSAL using Type Script and Angular CLI.

We notice that in few IE 11 and EDGE browsers returning NULL in the URL.

Below is the observation on Debugging.
Invalid State in the MSAL Session Storage is MSAL.Error key.

Note:
We used BLUEBIRD as well,
Checked in Protection Mode.
We are not using POPUP for Login IN.

Need your help in resolving the issue.

Please let me know for any additional information needed.

**Comment by rohitnarula7176** [comment]
@allinagaraju Closing this issue as it was resolved during our skype conversation. This is a known issue with Edge/IE browsers where local/sessionStorage values are dropped when you navigate/redirect across zones. The current workaround is to add https://login.microsoftonline.com along with your app's url to the trusted sites list.

**Comment by Chandu12x** [comment]
Hi Team,

Myself facing similar issue.Few times getting below errors in IE and Edge .Works fine  in Chrome.

msal.error: "Invalid_state"
msal.error.description:"Invalid_state. state: 63e08f7b-512f-47c5-826d-737da5c9604e"

Our portal is used by multiple clients and we can't ask each and every client to add https://login.microsoftonline.com  to trusted sites list.

We are using below  files for MSAL Implementation.

<script src="https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.js" class="pre"></script>
 <script src="https://secure.aadcdn.microsoftonline-p.com/lib/0.1.3/js/msal.js"></script>

Could you please help us in resolving this issue.

Please let me know for any additional information needed.
