### ISSUE TITLE
How to do audience authorization?

### ISSUE THREAD

**Issue by ruowan** [AzureAD/microsoft-authentication-library-for-js#2257]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
 "@azure/msal-node": "^1.0.0-alpha.5"
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
I am using MEO(Microsoft Email Orchestrator) to send auto notification emails, but I meet some issues about authorization.  I want to pass audience when acquire token, so that I could gain permission to access MEO. Does MSAL support audience? And MSAL is different from dotnet SDK. 

For internal reference: [MEO aad-token](https://dev.azure.com/azurecom/AEO/_wiki/wikis/AEO.wiki/1829/AAD-Token)

My sample code:
``` 
    const tenant = "xxxx";
    const authority = "https://login.microsoftonline.com";
    this.config = {
      auth: {
        clientId: "xxxx",
        clientSecret: "xxxx",
        authority: `${authority}/${tenant}`
      }
    };
    const pca = new msal.ConfidentialClientApplication(this.config);
    const resp = await pca.acquireTokenByClientCredential({
      scopes: ["https://graph.microsoft.com/.default"]
    });
```

dotnet sample code:

```
  string clientId = "YOUR CLIENT ID HERE";
            string clientSecret = "YOUR SECRET HERE";
            string audience = "https://emailorchestrator.onmicrosoft.com/<talent-id>";
            string tenant ="tanant";
            string authority = "https://login.microsoftonline.com";

            var authenticationContext = new AuthenticationContext($"{authority}/{tenant}");

            var credential = new ClientCredential(clientId, clientSecret);
            var result = await authenticationContext.AcquireTokenAsync(audience, credential);

            if (result == null)
            {
                return "Failed to obtain the AD token";
            }

            return result.AccessToken;
```

Examples: 
> "How do I use MSAL with Vue.js"
> "How do I SSO between tabs?"
> "How do I use MSAL to protect my custom Web API?"
> "How can my app support multiple AAD tenants?"
> "When will my scenario be supported?"
> "When will this framework be supported"

**Comment by jmckennon** [comment]
> Does MSAL support audience?

`Audience` is a legacy field. The concept is baked into some of the other fields for msal and AAD. You can read about that on the [Microsoft docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-client-application-configuration).

>And MSAL is different from dotnet SDK.

I'm not exactly sure what you mean here, but there are separate libraries for both JavaScript and .NET with regards to `msal`. There are also separate Azure SDKs for each as well. If your backend is all .NET, you may want to look into using [msal for .NET](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet), along with their samples and quickstarts.

If you do intend to stay with the JavaScript library, please provide the errors you're seeing along with which versions of the library you're using and we can help debug.

**Comment by ruowan** [comment]
I use `@azure/msal-node": "^1.0.0-alpha.5`.   What I want to do is to pass audience field during AAD auth. And I expect the access jwt token aud is my audience not `https://graph.microsoft.com`.  I do not quite understand about `The instance and audience can be concatenated and provided as the authority URL.` from the doc. Could you give me some examples?
 
My audience is `https://emailorchestrator.onmicrosoft.com/11c28534-b7e2-xxxxx-xxxx-54777bea593e`. My APP tenant is  `72f988bf-xxxx-xxxx-91ab-2d7cd011db47`. So what the final authority URL is like this:`https://login.microsoftonline.com/<my-tenant-id>/<my-audience-url>`. But its format is wrong and auth failed.

Error:

```
ClientAuthError: endpoints_resolution_error: Error: could not resolve endpoints. Please check the network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter.
    at ClientAuthError.AuthError [as constructor] (/home/ruowan/work/openapi-kebab/node_modules/@azure/msal-common/dist/index.js:113:24)
    at new ClientAuthError (/home/ruowan/work/openapi-kebab/node_modules/@azure/msal-common/dist/index.js:402:28)
    at Function.ClientAuthError.createEndpointDiscoveryIncompleteError (/home/ruowan/work/openapi-kebab/node_modules/@azure/msal-common/dist/index.js:439:16)
    at /home/ruowan/work/openapi-kebab/node_modules/@azure/msal-node/dist/msal-node.cjs.development.js:1648:42
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async MSALClient.acquireToken (/home/ruowan/work/openapi-kebab/lib/bots/common/meo.js:39:22)
    at async main (/home/ruowan/work/openapi-kebab/lib/bots/common/meo.js:65:19) {
  errorCode: 'endpoints_resolution_error',
  errorMessage: 'Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter.'
}
```

**Comment by jmckennon** [comment]
You need to expose an API and create a custom scope in the portal to get an access token for that audience. There are instructions for this on the [Microsofts docs page](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-configure-app-expose-web-apis).
