### ISSUE TITLE
Refresh token lifetime with auth code using ConfidentialClientApplication

### ISSUE THREAD

**Issue by Toktik** [AzureAD/microsoft-authentication-library-for-js#2259]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`
- [x] `@azure/msal-node@1.x.x`

## Description
I'm using @azure/msal-node, have the below flow and I'm not sure whether the refresh token expiration is limited or until-revoked?

Here is the breakdown of steps I do (summarized):
```
const config = {
  auth: {
    clientId: process.env.MICROSOFT_TEAMS_APP_ID,
    authority: 'https://login.microsoftonline.com/common',
    clientSecret: process.env.MICROSOFT_TEAMS_APP_SECRET
  },
  system: {
    loggerOptions: {
      loggerCallback(loglevel, message, containsPii) {
        console.log(message);
      },
      piiLoggingEnabled: false,
      logLevel: msal.LogLevel.Verbose,
    }
  }
};
const msalClient = new msal.ConfidentialClientApplication(config);
this.msalClient.getAuthCodeUrl(authCodeUrlParameters).then((response) => {
  res.redirect(response);
}).catch((error) => console.log(JSON.stringify(error)));

// After redirect back I do:
const result = await this.msalClient.acquireTokenByCode({
   code: req.query.code,
   scopes: ['user.read', 'offline_access'],
   redirectUri: redirectUri
});

// Then I can do, but I'm really interested what would be the expiration for the underlying refresh token?
const tokenRequest = {
    scopes: ['user.read', 'offline_access'],
    redirectUri: redirectUri,
    account: result.account
};

this.msalClient.acquireTokenSilent(tokenRequest).then((response) => {
  console.log("\nResponse: \n:", response);
  res.sendStatus(200);
}).catch((error) => {
  console.log(error);
  res.status(500).send(error);
});
```

What confuses me is that I'm using ConfidentialClientApplication class, but as I understand from the docs, this lies into "Authorization Code Grant with PKCE" category. Is client secret used from my configs? Is this public or confidential client? What is the expiration of refresh token? If it's not until-revoked, what flow I can use in Node.JS to achieve that?

**Comment by sangonzal** [comment]
@Toktik This is confidential client authorization code flow. The client secret you set in your config is used. If you remove the client secret, the flow will not work. The lifetime of the [tokens is configurable](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes), and I believe by default confidential client refresh tokens are valid until revoked. 

When you say "but as I understand from the docs, this lies into "Authorization Code Grant with PKCE" category", can you point to the docs that are confusing you?

**Comment by Toktik** [comment]
@sangonzal Thanks for your help!

I can't point to specific part of the documentation, but that was a little bit confusing. I think mentioning that Confidential Client is using the client secret and a word about refresh tokens will make things more clear.
