### ISSUE TITLE
Silent Login not working correctly

### ISSUE THREAD

**Issue by johannes-z** [AzureAD/microsoft-authentication-library-for-js#226]
I've tried adding the `login_hint` and `domain_hint` parameters to the call of the `loginPopup` function, but I still get a popup, limited to one single user, namely the one specified in `login_hint`.

This is how I pass the paramters:

```js
clientApplication.loginPopup(
  APPLICATION_CONFIG.graphScopes,
  'login_hint=username@domain.com&domain_hint=domain.com'
)
```

References: #148

**Comment by rohitnarula7176** [comment]
@johannes-z In the issue you are referring to, the word 'silent' is used incorrectly to enable the feature where the user does not have to select an account of the user already signed in which happens because Msal adds prompt=select_account to the login request. When you call loginPopup, you will see a UI every time as the name suggests. To achieve silent login in the case where you already have a valid session with AAD, you can call acquireTokenSilent by passing an empty user object and login_hint as extraQueryParameters. Please let me know if you have more questions.

**Comment by johannes-z** [comment]
@rohitnarula7176 Ok that makes sense, thanks.

I tried what you were suggesting, but how do I get an empty user object? Simply passing `{}` does not work. Do I have to read through the MSAL source to know which properties the object needs?

This is what I'm doing now:

```js
    clientApplication.acquireTokenSilent(
      APPLICATION_CONFIG.graphScopes,
      'https://login.microsoftonline.com/common',
      {},
      'login_hint=username@domain.com'
    ).then(console.log)
```

**Comment by rohitnarula7176** [comment]
@johannes-z I apologize for the misunderstanding. The silent login feature in Msal is still work in progress and will be available as part of our next release which will be in a couple of weeks. Once completed, you should just be able to pass just the login_hint of the user and silently log in.

**Comment by johannes-z** [comment]
@rohitnarula7176 Hi, thanks a lot for the clearification, that helped me a lot! I was wondering about something though. You spoke of `id_token` and `token`, and that Msal does not support this (yet).

I was wondering what that means: Is it implemented but still experimental, or is it a planned feature that's not yet in? Either way, is there an ETA for this feature?

**Comment by rohitnarula7176** [comment]
@johannes-z This is a planned feature which is not yet in the code. In the current state of the code , we do not have the condition in the acquireToken function where if the user has established a session with AAD outside of MsalJs and passes a login_hint of that user as parameter to the acquireToken api, we do not check for the user object and directly make the authorization request by sending responseType = id_token token.

**Comment by johannes-z** [comment]
Good to know - will monitor this repo then. Thanks!
