### ISSUE TITLE
Lots of old msal entries in local storage

### ISSUE THREAD

**Issue by bankszorsqt** [AzureAD/microsoft-authentication-library-for-js#2261]
## Library
- [x ] `msal@1.4.0` 
- [x ] `@azure/msal-angular@1.1.1`

## Description
I'm seeing lots of "msal.acquireTokenUser" in storage. I suspect there is only supposed to be one?
There were two issues open on this already, #327 and #527.

## MSAL Configuration

```js

export const config = {
  auth: {
    clientId: 'clientIdGUID',
    authority: 'https://login.microsoftonline.com/authorityGUID',
    validateAuthority: true,
    redirectUri: 'http://localhost:3000',
    postLogoutRedirectUri: 'http://localhost:3000',
    navigateToLoginRequestUrl: true
  },
  cache: {
    cacheLocation: 'localStorage'
  },
  scopes: {
    loginRequest: ['openid', 'profile']
  },
  resources: {
    microsoftGraphApi: {
      resourceUri: 'https://graph.microsoft.com/v1.0/me',
      resourceScope: 'user.read'
    },
    resourceApi: {
      resourceUri: 'https://localhost:44301/api',
      resourceScope: 'api://resourceGUID/access_as_user'
    }
  }
}
```

## Angular usage
```js
 ngOnInit(): void {
    this.checkoutAccount()
    this.subs.add(
      this.broadcastService.subscribe('msal:loginSuccess', () => {
        this.checkoutAccount()
      })
    )

    this.subs.add(
      this.broadcastService.subscribe('msal:acquireTokenFailure', () => {
        this.authService.loginRedirect()
      })
    )

    this.authService.handleRedirectCallback((authError, response) => {
      if (authError) {
        this.authService.loginRedirect()
        return
      }
    })
    this.authService.setLogger(
      new Logger(
        (logLevel, message, piiEnabled) => {
        },
        {
          correlationId: CryptoUtils.createNewGuid(),
          piiLoggingEnabled: false
        }
      )
    )
    if (!this.loggedIn) {
      this.authService.loginRedirect()
    }
  }

  checkoutAccount(): void {
    this.loggedIn = !!this.authService.getAccount()
  }
```

## Result
![image](https://user-images.githubusercontent.com/15078887/92941102-3b705500-f450-11ea-9e62-1b9b83acd46a.png)

## Reproduction steps
Check issue #327 

## Expected behavior
The msal library should be cleaning up the local storage and only keeping around what it needs.

## Browsers/Environment
- [x ] Chrome

**Comment by jmckennon** [comment]
@bankszorsqt Can you provide your configurations and `msal` usage? Also, is it possible for you to test with version `1.3.4` rather than `1.4.0`? We've seen a few problem with `1.4.0` and this could be tangentially related.

**Comment by bankszorsqt** [comment]
Hi @jmckennon I have updated the issue as you requested. I hope it gives more context now. (*note that I have changed some values of config for security reasons, GUID parts.)

**Comment by jmckennon** [comment]
@bankszorsqt Have you been able to consistently reproduce this problem? If so, what are the steps? We haven't seen anything like this with our sample apps.

**Comment by bankszorsqt** [comment]
@jmckennon Well, it happens over time, local storage gets bigger each time the user gets logged in. (around 50 rows are added each time). Also, might be worth mentioning, we are sending a bearer token with each API request.

**Comment by jmckennon** [comment]
Since I'm unable to reproduce this, have you done any debugging or network tracing to determine why there may be so many entries or why they aren't getting deleted? You can send a fiddler trace to the email on my profile if you see anything suspicious.
