### ISSUE TITLE
ssoSilent in Chrome results in BrowserAuthError: monitor_window_timeout: Token acquisition in popup failed due to timeout.

### ISSUE THREAD

**Issue by georgejdli** [AzureAD/microsoft-authentication-library-for-js#2263]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x ] `@azure/msal-browser@2.1.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework
react- 16.13.x

## Description

Based on the other issues I think this is an iframe timeout issue instead of a popup timeout. I tried increasing the iframeHashTimeout to 10 seconds with no luck.

So weird issue for me is that this works as expected when I run my react application locally on my laptop.
I get this error when I have the application hosted in an Azure VM but not consistently. Once in a while it behaves as expected.

This works as expected on Firefox 68 ESR for both local and remote server deployments.

Not sure if this is a related issue or not but in the code snippet above I try to work around this error by falling back to interactive login (loginPopup). However I run into an (intermittent) issue where the login popup doesn't go to the microsoft login url but instead goes to my website url (showing my application login page in the popup window).

## Error Message
BrowserAuthError: monitor_window_timeout: Token acquisition in popup failed due to timeout.

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
{
  auth: {
    clientId,
    authority,
    redirectUri: window.location.origin,
    postLogoutRedirectUri: window.location.origin
  },
  cache: {
    cacheLocation: "sessionStorage", 
    storeAuthStateInCookie: false, 
  }
}
```

## Reproduction steps
1) Navigate to react application hosted on Azure VM in my Chrome
2) react app checks if user is logged in with acquireTokenSilent
3) Interactive login required -> redirect user to application login page with a button to trigger logInSilent() function defined below.
4) Click login button. Wait 10 seconds (iframeHashtimeout). Get monitor_window_timeout error.

```js
export const logInSilent = async (): Promise<string> => {
  //  to refresh id_token only pass the clientID in scopes
  const silentRequest: msal.AuthorizationUrlRequest = {
    scopes: [authConfig.appGeneralScope],
    loginHint: "username",
    redirectUri: authConfig.getUrlOrigin()
  }

  //TODO need a reliable way to get the "correct" account object
  if (msalInstance.getAllAccounts() && msalInstance.getAllAccounts().length > 0) {
    silentRequest.loginHint = msalInstance.getAllAccounts()[0].username;
  }

  try {
    const loginResponse = await msalInstance.ssoSilent(silentRequest);
    // console.log('SILENT id_token acquired at: ' + new Date().toString());
    // console.log('SILENT access_token', loginResponse.accessToken)
    // console.log(loginResponse);
    return loginResponse.accessToken;
  } catch (err) {
    if (err instanceof msal.InteractionRequiredAuthError) {
      console.log("Silent Login failed - interactive requred")
      return await logIn();
    } else if (err instanceof msal.AuthError) {
      console.log("Some other auth error - fallback to interactive login anyway", err)
      return await logIn();
    }
    else {
      console.error("auth.loginSilent()", err);
      throw new Error(`Login failed: ${err.message}`);
    }
  }
}

export const logIn = async () => {

  try {
    const loginResponse = await msalInstance.loginPopup(authConfig.loginRequest);

    return loginResponse.accessToken;
  } catch (err) {
    // some error - not logged in
    console.error("auth.logIn()", err);
    //return "";
    throw new Error(`logIn failed: ${err.message}`);
  }

}
```

## Expected behavior
ssoSilent either logs the user in silently or returns the appropriate "InteractionRequiredAuthError" error instead.

## Browsers/Environment
- [X ] Chrome 85
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jmckennon** [comment]
Can you try setting your `redirectUri` for `ssoSilent` to a blank html page (with no content)? We have seen timeouts when applications use their homepage as the `redirectUri` for silent operations. An example of this can be shown in our react sample app, with our blank html page [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-core-samples/react-sample-app/public/auth.html) and the configuration using this blank page [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/7bb37ec8fd31f5d9263d5eb4aa882101c48a9924/samples/msal-core-samples/react-sample-app/src/auth-utils.js#L65). This is technically for version 1, but the same technique can be used for silent operations in version 2 of `msal`.

**Comment by georgejdli** [comment]
Using a blank html page for the redirectUri seems to resolve the iframe timeout issue (at least for now).

I am still seeing an intermittent issue with the loginPop itself either failing to navigate to the interactive login page with microsoft or after interactive login failing to redirect to my application home page but I guess that's an unrelated issue.
