### ISSUE TITLE
After clearCache is called you cannot acquire any token

### ISSUE THREAD

**Issue by julio177** [AzureAD/microsoft-authentication-library-for-js#2266]
## Library
- [x] `msal@1.3.3` or `@azure/msal@1.3.3`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework
None, basic JavaScript application

## Description
When receiving an error on an acquireToken, the catch block will trigger a call to application.clearCache(), causing any subsequent calls to get a "null_or_empty_id_token".
clearCache removes the id token from localStorage, but it is still set for the in-memory copy of Msal.UserAgentApplication.
MSAL sees that idToken is set in-memory, so it never requests a new idToken and will fail on receiving the access token if it can't lookup the id token in localStorage

## Error Message
null_or_empty_id_token

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
// Repros with a basic configuration
var application = new Msal.UserAgentApplication({
    auth: {
        clientId: "<APP_ID>",
        redirectUri: "https://localhost"
    }
});
```

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.

// Get token that requires consent. Fails with error code: consent_required.
application.loginPopup().then((result) => {
    console.log(result)
    return application.acquireTokenSilent({
        scopes: ["user.read"],
    });
}).then((result) => {
    console.log(result)
}).catch((ex) => {
    application.clearCache();
    console.error(ex);
});

//Try call again, subsequent calls will fail with error code: null_or_empty_id_token
```

## Expected behavior
Allow subsequent calls even if the first one failed.

## Browsers/Environment
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jmckennon** [comment]
@julio177 What's the reason that you want to call `clearCache`? That method is not intended to be used for situations other than logout. Additionally, your app should not have to invoke it directly.

**Comment by julio177** [comment]
I'm sorry, clearCache call was supposed to be in the catch section of the call.
So calling the method on anything other than logout i.e. error calls is not an expected behaviour right?

**Comment by jmckennon** [comment]
`clearCache` is designed for logout, and we don't recommend calling it directly.

**Comment by jmckennon** [comment]
Closing this as we're assuming the original question has been answered, please open a new issue if you have further questions. Thanks!
