### ISSUE TITLE
Getting both id_token and (access) token from acquiteTokenSilent()

### ISSUE THREAD

**Issue by zippy1981** [AzureAD/microsoft-authentication-library-for-js#227]
The function acquireTokenSilent takes an Optionally null user paramater that is by default populated by the classes user. 

```
acquireTokenSilent(scopes: Array<string>, authority?: string, user?: User, extraQueryParameters?: string): Promise<string> {
    return new Promise<string>((resolve, reject) => {
. . .
        const userObject = user ? user : this.getUser();
        if (!userObject) {
          reject(ErrorCodes.userLoginError + ":" + ErrorDescription.userLoginError);
          return;
        }
. . .
```

It seems there are three code paths:

1. Does the user parameter match the classes user object. If so 
 1. If one of the scopes requested is the client id, then retrieve an id token 
 2. Otherwise retrieve an access token (token)
2. Otherwise retrieve both an id token and access token

```
        let authenticationRequest: AuthenticationRequestParameters;
        let newAuthority = authority ? AuthorityFactory.CreateInstance(authority, this.validateAuthority) : this.authorityInstance;
        if (Utils.compareObjects(userObject, this._user)) {
          if (scopes.indexOf(this.clientId) > -1) {
            authenticationRequest = new AuthenticationRequestParameters(newAuthority, this.clientId, scopes, ResponseTypes.id_token, this._redirectUri);
          }
          else {
            authenticationRequest = new AuthenticationRequestParameters(newAuthority, this.clientId, scopes, ResponseTypes.token, this._redirectUri);
          }
        } else {
          authenticationRequest = new AuthenticationRequestParameters(newAuthority, this.clientId, scopes, ResponseTypes.id_token_token, this._redirectUri);
        }
```

What is the use case for third path? Is that only when you login as one user and wish to impersonate another user? Wold I everwant to knowingly put bad data there to take the third path in one shot?

**Comment by rohitnarula7176** [comment]
@zippy1981 One reason is what you have mentioned that is to login as one user and wish to get an access_token for another. Consider the case when you are using session storage where storage gets cleared when you close and reopen the browser. In that case your session cookie established between the browser and AAD might still be valid. Msal tries to populate the this._user from id_token saved in the cache but since the storage is cleared, we cannot retrieve user information from the cache. To achieve silent login in this scenario, you can call acquireTokenSilent by passing a non-null user object and if you have a single signed-in user in the browser, Msal will be able to sign you in without explicitly calling login first. One thing to note is that if you have more than one signed-in user, this request will fail unless you pass the login_hint of that user through extraQueryParameter in the acquireTokenSilent method. Please let me know if you have more questions.

-

**Comment by zippy1981** [comment]
@rohitnarula7176 In that scenario, the promise will always return the access token not the id token? Correct?

**Comment by rohitnarula7176** [comment]
@zippy1981 Yes you are right. In that scenario, AAD will return both an id_token and an access_token. Msal will use the id_token to create user context and resolve the promise with an access_token. Please see below for reference:
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/d32c5aa6e576bae924a3a319a38c810576e7f09d/src/UserAgentApplication.ts#L1333

**Comment by DavidHenri008** [comment]
@zippy1981 @rohitnarula7176 I am confuse, is this functionality supported or not? You said

>  There is another scenario for silent login which is not yet supported by Msal. 
and then 
> Yes you are right. In that scenario, AAD will return both an id_token and an access_token. Msal will use the id_token to create user context and resolve the promise with an access_token

**Comment by rohitnarula7176** [comment]
@DavidHenri008 The functionality to handle the response when you send responseType = 'id_token token' is not yet supported by Msal.

**Comment by wictorwilen** [comment]
@rohitnarula7176  - any ETA on support?

**Comment by ChristianOlsson** [comment]
@rohitnarula7176 is there any news on support for responseType = 'id_token token'?

**Comment by sameerag** [comment]
@ChristianOlsson Are you suggesting you need both "id_token" and "access_token" in the response?

**Comment by Zireael** [comment]
> @ChristianOlsson Are you suggesting you need both "id_token" and "access_token" in the response?

Yes, I too would like to get both tokens

**Comment by sameerag** [comment]
@Zireael @ChristianOlsson  We have a new MSAL JS release that supports this. It is still in preview but would you want to try the release and let us know how it works? It is breaking changes wrt the API surface and documented [msal 1.0.0-preview.x](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL.js-1.0.0-preview-api-release). 

npm install msal@preview should give you the latest release. Please let us know for any support needed.
