### ISSUE TITLE
Support for latest MSAL in @azure/msal-angularjs

### ISSUE THREAD

**Issue by skhilliard** [AzureAD/microsoft-authentication-library-for-js#2270]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [x] `@azure/msal-angularjs@1.x.x`

## Description
Currently, only the preview version of @azure/msal-angularjs is available and is dependent on an old version of MSAL (0.2.1).  We need to migrate our existing Angular JS application from ADAL to MSAL (1.x.x).  I have seen here [https://www.npmjs.com/package/msal](url) that you are planning to deprecate @azure/msal-angularjs.  I hope that this will not be the case!  Will there be an update for @azure/msal-angularjs that supports MSAL 1.x.x versions?  I saw that for the msal-angular library, you were changing MSAL to be a peer dependency, which seems ideal.  Is this planned also for the msal-angularjs library?

Thanks

**Comment by jasonnutter** [comment]
> Will there be an update for @azure/msal-angularjs that supports MSAL 1.x.x versions?

Unfortunately, no, we will not be updating `@azure/msal-angularjs` to support the new versions of MSAL.js. You will either need to use MSAL.js directly, or upgrade from AngularJS to Angular to use MSAL Angular.
