### ISSUE TITLE
MSAL JS and ADFS

### ISSUE THREAD

**Issue by LastTribunal** [AzureAD/microsoft-authentication-library-for-js#2272]
## Library
- [ ] `@azure/msal@1.4.0`
ref: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/99

## Description
MSAL seems to be a product of highly diverse SJW team of non-binary NPCs..  MS has now condemned their previously disastrous ADAL JS and is nudging everyone to migrate to their glorious MSAL.  However, there is still no support for ADFS + MSAL.JS despite of any confirmations that have recently been made,  ADAL JS still works with ADFS, but its problematic and requires hackery.  

The fact that MSAL JS (1.4.0) still doesn't work with ADFS is pathetic and MS has no legitimate excuse to make.

This limitation has tremendously detrimental effects on any effort to design onprem/hybrid  SPA/OAUTH applications.

**Comment by tnorling** [comment]
@LastTribunal Support for ADFS 2019 was added in `msal@1.4.0`. Please see our [ADFS specific sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-core-samples/VanillaJSTestApp/app/adfs) for help getting set up. Please also note that your ADFS server must have service pack [KB 4490481](https://support.microsoft.com/en-us/help/4490481/windows-10-update-kb4490481) applied. If there are specific issues you are having please fill out a bug template with steps to reproduce and we would be more than happy to look into it. Thanks!

**Comment by LastTribunal** [comment]
If that's the case, I will take back everything I said :)... Ill test and get back

**Comment by jasonnutter** [comment]
Closing.

@LastTribunal As I believe I have warned you before, by participating in this repository, you agree to follow Microsoft's Code of Conduct: https://opensource.microsoft.com/codeofconduct/

Further violations may result permanent banishment.
