### ISSUE TITLE
AADSTS50105: Page not rendering on server Environment

### ISSUE THREAD

**Issue by raj-here** [AzureAD/microsoft-authentication-library-for-js#2274]
Hi, 
In local, This is page being rendered if The signed in user 'xzz@abc.microsoft.com' is not assigned to a role for the application. 

It is working fine.

![image](https://user-images.githubusercontent.com/37954436/86225842-6ca6ec00-bba8-11ea-8cb0-654610750175.png)

But when I'm trying to produce the same thing on server, It is not being rendered.

Earlier, It was fall under infinite loop. I've follow the Issue AzureAD/azure-activedirectory-library-for-js#463 . and got the solution for Endless redirect on access_denied error AADSTS50105 AzureAD/azure-activedirectory-library-for-js#463 .

Below line solved my problem for infinite loop. 
`navigateToLoginRequestUrl: false`

But How can I get the above same page on server env. 
In Server Environment It's being redirect to my Login URL while on server it rendered the above page.
I'm using  this library https://www.npmjs.com/package/react-aad-msal.

Any idea how to stop this endless loop as well as show the AADSTS50105: Page on server Environment.

**Comment by jasonnutter** [comment]
@raj-here Apologies for the delay. MSAL.js is currently not supported in server environments, and only works client-side. For MSAL.js v2 we will address this, see #2073. Closing.
