### ISSUE TITLE
MSAL JS + ADFS, id_token not returning custom attributes

### ISSUE THREAD

**Issue by LastTribunal** [AzureAD/microsoft-authentication-library-for-js#2277]
## Library
- [ ] `@azure/msal@1.4.0`
## Description
In ADAL JS, the ADFS did not return custom attributes, unless **response_mode="form_post"** was sent in the request.
I am having the same problem here

I understand this is a limitation not of MSAL, but of ADFS.  
Is there a way to get the full id_token from ADFS via MSAL.JS?

ref:
https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/custom-id-tokens-in-ad-fs
https://medium.com/the-new-control-plane/the-mystery-of-the-missing-adfs-jwt-claims-7658d9cdeaac

**Comment by jmckennon** [comment]
@LastTribunal You are exactly correct, ADFS will not return certain fields like custom attributes because the token size will grow and it is difficult to predict if it will fit in query string--so ADFS prohibits it.

We're looking into whether or not this will be supported in `msal` version 2 which uses the authorization code flow.

**Comment by LastTribunal** [comment]
ADFS DOES return custom attributes, but only with "form_post", as I described.  
ADFS needs to allow it.  the fact that the seize may grow, should not be a deemed as prohibitor of the feature.  If anything, an upper limit should be set to prevent over-sized responses

**Comment by jmckennon** [comment]
@LastTribunal I've been trying to open a proper internal channel to communicate some of this feedback (and to find what work is needed on our end to enable this feature with the auth code flow) to ADFS, but in the meantime, feedback can be communicated externally [here](https://windowsserver.uservoice.com/forums/295047-general-feedback).
