### ISSUE TITLE
Requesting an AppId as a scope, error message indicates truncation of GUID occuring

### ISSUE THREAD

**Issue by zippy1981** [AzureAD/microsoft-authentication-library-for-js#228]
I have two applications registered in a Tenant. One is all client side javascript, the other is a .NET rest API.

The API has an app id of `https://TENANT_NAME.onmicrosoft.com/SOME_GUID`. I'm of the understanding that I need this appid as one of the scopes when I request a token.

I am requesting a token with that like so:

```
const scopes = [
    'openid',         // Needed to connect via OpenId
    'email',          // Not redundant by profile
    'profile',        // Supposedly everything here https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-tokens
    'offline_access'  // Necessary for refresh tokens. Not sure if we are actually utilizing these.
    https://devvalidusb2c.onmicrosoft.com/SOME_GUID
];

. . .
this.userAgentApplication
      .acquireTokenSilent(scopes.concat(clientId) /* so we get id_token not access token */, null, user)
```

Accordingto the chrome debugger this generates the url with the following scope param:

> &scope=email%20offline_access%20https%3A%2F%2FTENANT_NAME.onmicrosoft.com%2FSOME_GUID%20openid%20profile

However, the following error message indicates that somewhere along the line MSFT is stripping off the app id

```
MSAL: Tue, 23 Jan 2018 00:17:52 GMT:12345-0.1.3-Info Error :invalid_resource; Error description:AADSTS50001: The application named https://TENANT_NAME.onmicrosoft.com was not found in the tenant named TENANT_ID.  This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant.  You might have sent your authentication request to the wrong tenant.
Trace ID: XXXXXX
Correlation ID: YYYYYY
Timestamp: 2018-01-23 00:16:43Z
```

Am I doing something wrong, or is an incorrect error message being generated?

**Comment by nehaagrawal** [comment]
As per the error message: AADSTS50001, it appears to be an issue with client app permissions for accessing your Web API.Please double check if you have assigned the right permissions to the client application for accessing the Web application Interface
