### ISSUE TITLE
Silent token refresh event

### ISSUE THREAD

**Issue by whittssg** [AzureAD/microsoft-authentication-library-for-js#2282]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `@azure/msal-angularjs@1.1.1`
MSAL 1.3.4 (downgraded from 1.4 due to too many issues)

## Description

Is there an event in the angular version that i can subscribe to when the silent token refresh starts?

From the documentation i can see these:

```
this.broadcastService.subscribe('msal:loginSuccess', () => {
           console.log("Login Successor ");
    });

    this.broadcastService.subscribe("msal:loginFailure",
      () => {
        console.log("Login Failed or expired");
      });

    this.broadcastService.subscribe("msal:acquireTokenSuccess", payload => {
      console.log("Silent token success");
    });

    this.broadcastService.subscribe("msal:acquireTokenFailure", payload => {
      console.log("Silent token fail");
    });
```

But they all seem to be when it fails or succeeds. Due to the fact that after the token expires it can take several seconds to renew (on a route change for example) I would like to show some kind feedback to the user.. 'Please wait while we log you back in" sort of thing. 

I guess i could always start a loading animation on route change and kill it once i get the silent token refresh success message but i believe there should really be  a start message from the libaray. 

While i am here.. why is that first call so long? I already made a fake html page for the redirect url to try and speed it up (before that It seemed to be loading my entire app which took a long time) but i still find it quite long for a silent refresh (4 seconds or so)?

Thanks,

**Comment by jmckennon** [comment]
> Is there an event in the angular version that i can subscribe to when the silent token refresh starts?

No, there is not currently an event to support this. We are currently looking into improving the events for `msal-angular` and we'll definitely take this feedback into account.

> While i am here.. why is that first call so long?

Token acquisition performance is impacted by a number of factors. Does it always seem to take 4+ seconds, or is that duration intermittent?

**Comment by whittssg** [comment]
> No, there is not currently an event to support this. We are currently looking into improving the events for `msal-angular` and we'll definitely take this feedback into account.

OK thank you, I will look out for any updates in the future.

> Token acquisition performance is impacted by a number of factors. Does it always seem to take 4+ seconds, or is that duration intermittent?

It seems to be around 4 seconds ish like you said on the first call, subsequent calls are instant. This is why I was looking for an event to show some kind of feedback once the process starts (if for instance it takes longer than 1 second)..

**Comment by jmckennon** [comment]
> It seems to be around 4 seconds ish like you said on the first call, subsequent calls are instant. This is why I was looking for an event to show some kind of feedback once the process starts (if for instance it takes longer than 1 second)..

Can you provide your msal config? I'd be interested in seeing what page you're using for your redirectUri, as the process can cause some reloads on that page.

Additionally, the first call to AAD to establish a session will inherently take a bit longer than subsequent ones, but 4 seconds is more than what we would expect.

**Comment by whittssg** [comment]
> > It seems to be around 4 seconds ish like you said on the first call, subsequent calls are instant. This is why I was looking for an event to show some kind of feedback once the process starts (if for instance it takes longer than 1 second)..
> 
> Can you provide your msal config? I'd be interested in seeing what page you're using for your redirectUri, as the process can cause some reloads on that page.
> 
> Additionally, the first call to AAD to establish a session will inherently take a bit longer than subsequent ones, but 4 seconds is more than what we would expect.

Sure:

```
auth: {
      clientId: 'xxxxxxxxxxxxxxxxxxxxxxx',
      authority: 'https://login.microsoftonline.com/xxxxxxxxxxxxxxxxxxxxxxxxxx',
      validateAuthority: true,
      redirectUri: "https://localhost:44300", //here i tried putting in auth.html which is a blank html file but it didnt speed things up
      postLogoutRedirectUri: "https://localhost:44300/",
      navigateToLoginRequestUrl: true,
    },
    cache: {
      cacheLocation: "localStorage",
      storeAuthStateInCookie: isIE,
    },
    system: {
      logger: new Logger(loggerCallback, {
        correlationId: '1234',
        level: LogLevel.Verbose,
        piiLoggingEnabled: true,
      })
        }  
  };
```

Thanks,

**Comment by jmckennon** [comment]
Have you done any debugging or network tracing in your app to determine where the bottleneck for those 4 seconds is? You can email me a fiddler trace at the email on my profile and we can check to see if it's AAD that's taking a long time in your case.

**Comment by jasonnutter** [comment]
This is now possible in MSAL Angular v2: https://github.com/AzureAD/microsoft-authentication-library-for-js/releases/tag/msal-angular-v2.0.0-alpha.0

Closing.
