### ISSUE TITLE
Does acquireTokenSilent require prior loginPopup/loginRedirect to get account in @azure/msal-browser@2.1.0

### ISSUE THREAD

**Issue by antonfil** [AzureAD/microsoft-authentication-library-for-js#2283]
## Library
- [x] `@azure/msal-browser@2.1.0`

## Description
acquireTokenSilent method takes SilentRequest parameter with mandatory field 'account'. How can I get this account? Do I need to firstly loginPopup/loginRedirect to get account? What if I already logged in - how to check it and get account without loginPopup/loginRedirect?

**Comment by jmckennon** [comment]
Yes, this is correct, you will need to call one of the login methods before using `acquireTokenSilent` successfully. This can be seen in [our msal-browser sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-browser-samples/VanillaJSTestApp2.0/app/default/auth.js), along with our recommended usage for the library as well. We also have an example of how to use some of the [getAccount APIs](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/39e83918eedb9246d9a4bb16d6fb2db9b4892700/samples/msal-browser-samples/VanillaJSTestApp2.0/app/default/graph.js#L23).

Please let us know if you have more questions!

**Comment by antonfil** [comment]
@jmckennon thanks for the answer.

If PublicClientApplication.getAllAccounts() returns some account/accounts then does it guarantee that user is logged in? If I want to check authentication on startup do I need to force loginRedirect/loginPopup or I can firstly check that getAllAccounts() already has something? What is the best practice?

`let config = {...}
const authProvider = new AuthProvider(config)
const app = new App()

authProvider.authenticate(() => {
    app.run()
})

class App {
    run() {
        ...
        authProvider.acquireTokenSilent(...)
        ...
    }
}

class AuthProvider extends PublicClientApplication {
    authenticate(callback: () => void): void {
        let currentAccounts = this.getAllAccounts()
        if (currentAccounts && currentAccounts.length) {
            // if we have current account then we are logged in
            // and have account to pass into acquireTokenSilent,
            // so we can run application immediately
            callback()
        } else {
            // otherwise we handle login
            this.handleRedirectPromise().then(res => {
                if (res === null) {
                    // if no redirect login is in progress then we force login
                    let redirectRequest = {...}
                    this.loginRedirect(redirectRequest)
                } else {
                    // if redirect login is successfull then we run application
                    callback()
                }
            })
        }
    }
}`

**Comment by jmckennon** [comment]
Yes, if `getAllAccounts` doesn't return an account object, then you can assume that you need to call a login function, and if it does return an account, you can use it to call `acquireTokenSilent`. The structure of your code seems like its on the right path with the account-checking logic. 

Additionally, unless you call `logout` or the cache gets cleared, we won't remove an existing account out of local storage.
