### ISSUE TITLE
MsalGuard forces renew token on each page request

### ISSUE THREAD

**Issue by elliott90** [AzureAD/microsoft-authentication-library-for-js#2284]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ 1] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
I am using angular 9, using a dotnet web api protected using azure B2C.

I have a welcome page which does not use the msalguard but all other routes use the guard.
I have noticed once logged in and navigating from page to page the app is trying to renew the id token? Is this correct?
I assumed the msal library would be able to figure out that I'm logged in and have a valid token?

Each page navigation is taking 2-3 seconds to load because it seems to renew the token. This is being logged to the console:

MSAL Logging:  -Info RenewIdToken has been called
app.component.ts:80 MSAL Logging:  -Info ProcessCallBack has been called. Processing callback from redirect response
app.component.ts:80 MSAL Logging: -Info State status: true; Request type: LOGIN
app.component.ts:80 MSAL Logging:  -Info State is right
app.component.ts:80 MSAL Logging:  -Info Fragment has idToken

Is this correct behaviour?

**Comment by jmckennon** [comment]
This should be fixed by #2206. Thanks for the information!

**Comment by jmckennon** [comment]
@vishmay-AF We think that #2206 should have fixed this problem as well, as it also solves cache-lookup problems that result in token renewals. Can you test `msal@1.4.1` to see if your issues are still persistent? 

If you still have problems, please open a new issue with your config, versions, and usage so we can assist further.

**Comment by vishmay-AF** [comment]
@jmckennon
Just now, my issues was solved by setting up azure configuration,
I'm not sure which one did the trick, so I'm listing all...

I gave some permission, (attached)
created client secret,
Exposed API with scope for impersonate user.
I'ven't checked with 1.4.1,
1.4.0 is working for me.
permissions .txt

**Comment by JasonTheProgrammer** [comment]
@vishmay-AF if you happen to figure out what change helped get the desired behaviour in 1.4.0, let me know. For now, I can't update to 1.4.1 because of #2402.

**Comment by vishmay-AF** [comment]
I also had to update to 1.4.1 since it was not working while uploaded to server.
