### ISSUE TITLE
SPA iframe support for loginRedirect flow

### ISSUE THREAD

**Issue by idri** [AzureAD/microsoft-authentication-library-for-js#2285]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.1.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
When performing loginRedirect flow from an iframe that is used in an Angular SPA I get this error:
`Unhandled rejection BrowserAuthError: redirect_in_iframe: Code flow is not supported inside an iframe. Please ensure you are using MSAL.js in a top frame of the window if using the redirect APIs, or use the popup APIs. (window.parent !== window) => true    at BrowserAuthError.AuthError [as constructor] (https://alcdn.msftauth.net/browser/2.1.0/js/msal-browser.js:201:28)    at new BrowserAuthError (https://alcdn.msftauth.net/browser/2.1.0/js/msal-browser.js:4932:32)    at Function.BrowserAuthError.createRedirectInIframeError (https://alcdn.msftauth.net/browser/2.1.0/js/msal-browser.js:5017:20)    at RedirectHandler.initiateAuthRequest (https://alcdn.msftauth.net/browser/2.1.0/js/msal-browser.js:6400:44)    at PublicClientApplication.<anonymous> (https://alcdn.msftauth.net/browser/2.1.0/js/msal-browser.js:7027:48)    at step (https://alcdn.msftauth.net/browser/2.1.0/js/msal-browser.js:80:27)    at Object.next (https://alcdn.msftauth.net/browser/2.1.0/js/msal-browser.js:61:57)    at fulfilled (https://alcdn.msftauth.net/browser/2.1.0/js/msal-browser.js:51:62)    at r (https://cdn.jsdelivr.net/npm/bluebird@3.7.2/js/browser/bluebird.min.js:31:10952)    at i._settlePromiseFromHandler (https://cdn.jsdelivr.net/npm/bluebird@3.7.2/js/browser/bluebird.min.js:30:15746)    at i._settlePromise (https://cdn.jsdelivr.net/npm/bluebird@3.7.2/js/browser/bluebird.min.js:30:16549)    at i._settlePromiseCtx (https://cdn.jsdelivr.net/npm/bluebird@3.7.2/js/browser/bluebird.min.js:30:17057)    at c (https://cdn.jsdelivr.net/npm/bluebird@3.7.2/js/browser/bluebird.min.js:29:1583)    at a (https://cdn.jsdelivr.net/npm/bluebird@3.7.2/js/browser/bluebird.min.js:29:1469)    at r._drainQueues (https://cdn.jsdelivr.net/npm/bluebird@3.7.2/js/browser/bluebird.min.js:29:2484)    at drainQueues (https://cdn.jsdelivr.net/npm/bluebird@3.7.2/js/browser/bluebird.min.js:29:1211)`

I am executing the loginRedirect call using pure javascript from the child iframe, while in the parent window I am handling a postMessage from the child iframe when the login redirect-uri is called in the iframe, and then I acquire a token silently from the SPA parent window. This used to work in MSAL v1.3.x, but not in Safari due to ITP issue. This is why I switched to MSAL v2.0.

I assume the loginRedirect call is now intentionally blocked when done from an iframe with MSAL v2.0, due to this Safari ITP like issue (with "prevent cross-site tracking" enabled flag).
Can you please confirm?

The only documentation I could find about this is: https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-third-party-cookies-spas 
I would suggest to be more explicit in MSAL v2.x documentation about iframe support. 
It is not clear if the text from link above applies just for MSAL v1.x or MSAL v2.x or both.

Thank you.

**Comment by jmckennon** [comment]
Redirect actions are blocked in iframes because the login UX can't be rendered in an iframe. We are working on improving support for iframed applications in `msal` 2.x. 

Can you provide details about how you accomplished this in `msal@1.3.x`?

**Comment by jmckennon** [comment]
Closing this as we're assuming the original problem has been solved due to inactivity, please open a new issue if you have further questions. Thanks!
