### ISSUE TITLE
Retrieve Authorization Code using MSAL Browser

### ISSUE THREAD

**Issue by Luismvm** [AzureAD/microsoft-authentication-library-for-js#2286]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Is it possible to just retrieve the authorization code using the MSAL browser library?

From what I was able to gather from multiple code samples, the library uses the authorization code flow, to retrieve access tokens but it doesn't seem to provide anyway of just retrieving an authorization code so the access tokens can be retrieved on the server side. 

The only way seems to be to call the endpoints directly as per Microsoft docs, [https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow).

**Comment by jmckennon** [comment]
We currently do not expose the authorization code in `msal-browser`. Auth codes returned to the browser are not redeemable server-side. In our `msal-node` library we do expose the authorization code, so you may want to see if that can fit your use case. 

We have considerations to include the ability to use both `msal-browser` and `msal-node` in the same app together, and your use case sounds like it may make use of that. Unfortunately it's not supported today.

**Comment by jmckennon** [comment]
Closing this as we're assuming the original question has been answered, please open a new issue if you have further questions. Thanks!
