### ISSUE TITLE
openid-configuration is called in every acquireTokenSilent call (B2C)

### ISSUE THREAD

**Issue by Codeluck** [AzureAD/microsoft-authentication-library-for-js#2291]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

@azure/msal-browser@2.1.0

## Framework
React

## Description

`/.well-known/openid-configuration` endpoint is called every time I call `acquireTokenSilent`

At first I call `loginRedirect` with scopes
```
const loginRequest: RedirectRequest = {
    scopes: [],    
    extraScopesToConsent: [ 'offline_access' ]
};
```

and then `acquireTokenSilent` with the same scopes. The problem is that I see a request to `/.well-known/openid-configuration` of my B2C policy every time which is totally wrong to me. Looks like it's not cached for some reason...

## MSAL Configuration

```
const msalConfig: Configuration = {
    auth: {
        clientId: AZURE_AUTH_APP_CLIENT_ID,
        redirectUri: redirectUri, 
        postLogoutRedirectUri: logoutUri,
        knownAuthorities: [ AZURE_B2C_TENANT_NAME, 'login.microsoftonline.com' ]
    },
    cache: {
        cacheLocation: 'localStorage', 
        storeAuthStateInCookie: false,
    },
    system: {
        tokenRenewalOffsetSeconds: 0,
        loadFrameTimeout: 9000,
        loggerOptions: {
            logLevel: LogLevel.Error,
            loggerCallback: msalLoggerCallback
        }
    }
  };
```

## Expected behavior

`openid-configuration` should only be called once

## Browsers/Environment
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by tnorling** [comment]
@Codeluck What I'm not seeing here is where you're specifying your authority. Try providing your B2C authority on `msalConfig.auth.authority`

If you are passing an authority to your request object which is different from the value of `msalConfig.auth.authority` (defaults to login.microsoftonline.com/common) it will make a new call to the `openid-config` endpoint each time by design. I recognize that may have a performance impact if you have several authorities you are trying to use for different calls so we may consider enhancing this in the future.

**Comment by Codeluck** [comment]
@tnorling thank you for the answer. Yes, I use 2 authorities which are different custom B2C policies. I conditionally determine the policy right at the moment of sign in. Therefore I have to bypass `msalConfig.auth.authority` (it's not set as you see) and pass it as a request parameter when calling `loginRedirect` or `acquireTokenSilent`. Will it cause `openid-config` to be re-called on each request?

**Comment by tnorling** [comment]
@Codeluck Yes. Is there a reason you can't do your conditional logic before initializing msal? Do you need to switch back and forth between the authorities in the same browser context?

**Comment by Codeluck** [comment]
@tnorling I've finally implemented a conditional initialization of my msalObject so that the "main" current authority is always set as `msalConfig.auth.authority`. Now it works like a charm! I don't see any extra requests to my B2C's policy `well-known/openid-configuration` endpoint anymore. Thank you very much for your suggestion! It would be great if you can describe such a behavior in the documentation. It was not so obvious to me :) I think we can close this thread.

**Comment by tnorling** [comment]
@Codeluck Thanks for the update, glad that worked out! I'll leave this open for now and mark it as an enhancement as I do think there's room for improvement here.

**Comment by rugglcon** [comment]
@tnorling We are setting our authority on app initialization (we also have two authorities), but are still seeing this behavior on `msal@1.3.1`. Do you have any other suggestions for what we could do?

**Comment by tnorling** [comment]
@rugglcon Version 1.x behaves a little bit differently. Are you perhaps also passing the authority to your request object? If you are only setting it on app initialization and not as part of the request, it should only be called once. But every request that has an authority provided on it will make the openid-config call.

**Comment by rugglcon** [comment]
@tnorling No, we are not. But we updated to 1.4.0 to test if that has the same behavior, and it didn't send multiple requests to openid-configuration endpoint. Not sure why, we didn't change any code all we did was update the version. Oh well, thanks for the reply!
