### ISSUE TITLE
MSAL: ClientAuthError: Token renewal operation failed due to timeout.

### ISSUE THREAD

**Issue by mohsinmuzawar01** [AzureAD/microsoft-authentication-library-for-js#2292]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-angular@1.1.1`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
Angular 8

## Description
![image](https://user-images.githubusercontent.com/71313954/93222232-59112780-f78c-11ea-90fb-c561b88fab8a.png)

## Error Message
ClientAuthError: Token renewal operation failed due to timeout.
## Security
- [ ] Is this issue security related?
no
## Regression
- [ ] Did this behavior work before? 
no

## MSAL Configuration
```javascript
auth: {
      clientId: <clientid>
      authority: <authority>
      validateAuthority: true,
      redirectUri: environment.azureAdRedirectUri,
      navigateToLoginRequestUrl: true
    },
    cache: {
      cacheLocation: 'localStorage',
      storeAuthStateInCookie: isIE, // set to true for IE 11
    },
    framework: {
      isAngular: true
    },
{
    popUp: false,
    consentScopes: [
      'user.read',
      'profile',
      'openid',
      'files.readwrite',
      'email',
      'offline_access',
      '<custom scope>'
    ],
    unprotectedResources: ['https://www.microsoft.com/en-us/'],
    protectedResourceMap: [
  ['https://graph.microsoft.com/v1.0/me', ['user.read']], // ,
  [environment.apiUri, ['<Custom Scope>']]
]
    extraQueryParameters: {}
  }
```
```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
Error occurs intermittently after access the browser after it was being idle for some time.

```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Browsers/Environment
- [x ] Chrome
- [ x] Firefox
- [ x] Edge
- [ ] Safari
- [ x] IE
- [ ] Other (Please add browser name here)

**Comment by jmckennon** [comment]
@mohsinmuzawar01 Can you also post your `msal` code and usage? We will need to see a bit more to debug/assist further. Timeouts can occur for a number of reasons.

**Comment by mohsinmuzawar01** [comment]
AuthService.ts

import { Observable, of } from 'rxjs';
import { Injectable } from '@angular/core';
import { MsalService } from '@azure/msal-angular';
import { Account, AuthenticationParameters, AuthResponse, Logger, LogLevel } from 'msal';

@Injectable({
  providedIn: 'root'
})
export class AuthService {
  authParams: AuthenticationParameters = {
    scopes: ['user.read', 'files.readwrite', 'email', 'offline_access', 'profile', 'openid', '<Custom Scope>']
  };
  constructor(private msal: MsalService) { }

  getUser(): Observable<Account>{
    const user = this.msal.getAccount();
    return of(user);
  }


  // Silently request an access token
  async getNewAccessToken(): Promise<AuthResponse | void> {
    const result = await this.msal.acquireTokenSilent(this.authParams)
      .catch((reason) => {
        // this.alertsService.add('Get token failed', JSON.stringify(reason, null, 2));
        console.error(reason);
      });

    // Temporary to display token in an error box
    // if (result) this.alertsService.add('Token acquired', result);
    return result;
  }

  async getAccessTokenTwo(): Promise<AuthResponse | void> {
    const result = await this.msal.acquireTokenSilent(this.authParams)
    .catch((reason) => {
      // call acquireTokenPopup in case of acquireTokenSilent failure
      // due to consent or interaction required
      console.log(reason, 'getAccessTokenTwo');
    });

    // Temporary to display token in an error box
    return result;
  }

  forceRedirectToLogin() {
    this.msal.loginRedirect(this.authParams);
  }

  forceLoginPopup(){
    return this.msal.acquireTokenPopup(this.authParams);
  }

  handleRedirect(){
    this.msal.handleRedirectCallback((authError, response) => {
      if (authError) {
        console.error('Redirect Error: ', authError.errorMessage);
        return;
      }

      console.log('Redirect Success: ', response);
    });
  }

  logger(){
    this.msal.setLogger(new Logger((logLevel, message, piiEnabled) => {
      console.log(message, logLevel, piiEnabled , ' this is from logger');
    }, {
      level: LogLevel.Warning,
      piiLoggingEnabled: true
    }));
  }
  doLogout() {
    sessionStorage.clear();
    localStorage.clear();
    this.msal.logout();
  }
}

app.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { ActivatedRoute, Router, NavigationStart, NavigationEnd } from '@angular/router';
import { SEOService } from './services/seo.service';
import { takeUntil, startWith, delay } from 'rxjs/operators';
import { Subject, Subscription } from 'rxjs';
import { AuthService } from './services/auth.service';
import { CustomLoggerService } from './core/customLogger/customLogger.service';
import { BroadcastService } from '@azure/msal-angular';
import { Account } from 'msal';
import { SharedService } from './services/shared.service';
import { CheckForUpdateService } from './misc/updates/check-for-update.service';
import { LogUpdateService } from './misc/updates/log-update.service';
import { PromptUpdateService } from './misc/updates/prompt-update-service.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.less']
})

export class AppComponent implements OnInit, OnDestroy {
  isErr = false;
  private ngUnsubscribe: Subject<any> = new Subject();
  private ngRouterUnsubscribe: Subject<any> = new Subject();
  isLoggedIn = false;
  loadingRouteConfig: boolean;
  showMenuItems = true;
  isIframe: boolean;
  user: Account;
  constructor(
    private router: Router,
    private activatedRoute: ActivatedRoute,
    private seoService: SEOService,
    private authService: AuthService,
    private sharedService: SharedService,
    private logger: CustomLoggerService,
    private broadcastService: BroadcastService,
    // service worker "services"
    private checkForUpdates: CheckForUpdateService,
    private logUpdates: LogUpdateService,
    private promptUpdate: PromptUpdateService
  ) { }
  // msal subscribers
  private tokenFailSubscription: Subscription;
  private tokenSuccessSubscription: Subscription;
  private loginFailSubscription: Subscription;
  private loginSuccessSubscription: Subscription;

  ngOnInit()
  {
    this.authService.logger();
    this.isIframe = window !== window.parent && !window.opener;
    this.router.events
    .pipe(
      startWith(null),
      delay(0),
      takeUntil(this.ngUnsubscribe)
      )
    .subscribe(event => {
        if (event instanceof NavigationStart) {
          this.loadingRouteConfig = true;
        }else if (event instanceof NavigationEnd) {
          this.loadingRouteConfig = false;
          this.showMenuItems = true;
          if (event.url.indexOf('approve-request') > - 1){
            this.showMenuItems = false;
          }else {
            this.showMenuItems = true;
          }
        }
    });
    this.authService.handleRedirect();
    this.getUser();
    this.seoService.setPageMetaData(this.router, this.activatedRoute);
    this.sharedService.isApplicationError.pipe(takeUntil(this.ngUnsubscribe)).subscribe((val: boolean) => {
      this.isErr = val;
    });

    this.tokenFailSubscription = this.broadcastService
    .subscribe('msal:acquireTokenFailure', (reason) => {
      // catch token fails
      // console.log('msal:acquireTokenFailure', reason);

      const err = JSON.stringify(reason, null, 2);
      const res = JSON.parse(err);
      if (res.errorCode.toLowerCase() === 'consent_required'
      || res.errorCode.toLowerCase() === 'interaction_required'
      || res.errorCode.toLowerCase() === 'login_required') {
        this.authService.forceRedirectToLogin();
      }
      else {
        // fetch the token
        console.log('msal:acquireTokenFailure', err, reason);
        // this.authService.getAccessTokenTwo();
        if (res.errorCode.toLowerCase() === 'token_renewal_error'){
          this.authService.forceLoginPopup().then((ress) => {
            this.isLoggedIn = true;
            console.log(ress, 'successfully fetch');
          }).catch((err1) => {
            console.log('forceLoginPopup', err1);
            this.isLoggedIn = false;
            this.authService.forceRedirectToLogin();
          });
        }
      }
    });

    this.tokenSuccessSubscription = this.broadcastService
    .subscribe('msal:acquireTokenSuccess', (payload) => {
      // catch token fails
      this.isLoggedIn = true;
      console.log('token acquired successfully');
    });

    // catch login fails
    this.loginFailSubscription = this.broadcastService
    .subscribe('msal:loginFailure', (payload) => {
      this.isLoggedIn = false;
      this.authService.forceRedirectToLogin();
    });

    this.loginSuccessSubscription = this.broadcastService
    .subscribe('msal:loginSuccess', (payload) => {
      this.isLoggedIn = true;
    });
  }

  getUser() {
    this.authService.getUser()
    .pipe(takeUntil(this.ngUnsubscribe))
    .subscribe(
    result => {
      if (result){
        this.user = result as Account;
      }
    },
    error => {
      this.logger.error(this.constructor.name, error);
    });
  }

  ngOnDestroy(){
    this.broadcastService.getMSALSubject().next(1);
    if (this.tokenFailSubscription) {
      this.tokenFailSubscription.unsubscribe();
    }

    if (this.tokenSuccessSubscription)
    {
      this.tokenSuccessSubscription.unsubscribe();
    }

    if (this.loginFailSubscription) {
      this.loginFailSubscription.unsubscribe();
    }
    if (this.loginSuccessSubscription)
    {
      this.loginSuccessSubscription.unsubscribe();
    }
    this.ngUnsubscribe.next();
    this.ngUnsubscribe.complete();

    this.ngRouterUnsubscribe.next();
    this.ngRouterUnsubscribe.complete();
  }
}

**Comment by mohsinmuzawar01** [comment]
@jmckennon I started printing logs using the logger i started getting the below error just before it throws the token timeout exception.

**Error monitorIframeForHash unable to find hash in url, timing out**

**Comment by jmckennon** [comment]
@mohsinmuzawar01 Can you try setting `initialNavigation` to false when you're inside an iframe and let us know if that fixes the error? This has helped other users in the [past with timeout errors](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1260#issuecomment-586766234).
