### ISSUE TITLE
Firefox private browsing Invalid state Expected null

### ISSUE THREAD

**Issue by Vizzr** [AzureAD/microsoft-authentication-library-for-js#2294]
_Originally posted by @jasonnutter in https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1035#issuecomment-621997612_

The issue still occurs in Firefox Private browsing when the app is deployed (localhost works).

Packages:
msal: 1.4.0
@azure/msal-angular: 1.1.1

Configuration:
```
    auth: {
      clientId: environment.azureSettings.applicationId,
      authority: environment.azureSettings.authority + environment.azureSettings.signInPolicyId,
      validateAuthority: false,
      redirectUri: environment.azureSettings.signInRedirectUri,
      postLogoutRedirectUri: environment.azureSettings.logoutRedirectUri,
      navigateToLoginRequestUrl: false,
    },
    cache: {
      cacheLocation: "localStorage",
      storeAuthStateInCookie: isIE,
    },
```

**Comment by jmckennon** [comment]
This may be caused by localStorage being cleared by Firefox while in private mode, can you try setting `storeAuthStateInCookie: true` in Firefox to see if that fixes your issue?

**Comment by Vizzr** [comment]
> This may be caused by localStorage being cleared by Firefox while in private mode, can you try setting `storeAuthStateInCookie: true` in Firefox to see if that fixes your issue?

Thanks for your reply.
This indeed fixed the issue in Firefox.

I copied the isIE part from the Angular 9 Sample App. It might be useful to mention such an error somewhere.
