### ISSUE TITLE
'PublicClientApplication.acquireTokenSilent' throws 'state_mismatch' exception when refresh token is expired in @azure/msal-browser@2.1.0

### ISSUE THREAD

**Issue by antonfil** [AzureAD/microsoft-authentication-library-for-js#2305]
## Library
- [x] `@azure/msal-browser@2.1.0`

## Description
'PublicClientApplication.acquireTokenSilent' throws 'state_mismatch' exception when refresh token is expired.
How to handle this exception?

![image](https://user-images.githubusercontent.com/5970483/93403744-15541600-f891-11ea-92a9-fcc654441e09.png)

**Comment by jmckennon** [comment]
This is intended. When your refresh token is expired and there is not an established session in AAD, you get an error, both from the server (invalid_grant) and in our client library. You should have a fallback to a login function on your acquireTokenSilent calls for cases like this one. This is shown in our [samples for msal-browser](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/2c75dcfdc3af95ce942433d950ceb95de085c3da/samples/msal-browser-samples/VanillaJSTestApp2.0/app/default/auth.js#L62). You can also read about some of the [functionality of these calls in our docs](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/acquire-token.md).

**Comment by jmckennon** [comment]
Additionally, #2290 addresses an issue with multiple concurrent requests. If you are making multiple `acquireTokenSilent` calls, that PR may fix the issue as well.

**Comment by antonfil** [comment]
@jmckennon
As I see this 'state_mismatch' exception is not instance of 'InteractionRequiredAuthError'. Is it supposed to be so?
Do we need to handle it like below?
```typescript
try {
            let response = await acquireTokenSilent(...)
            return response.accessToken
        } catch (e) {
            if (
                e instanceof InteractionRequiredAuthError ||
                (e instanceof AuthError && e.errorCode === 'state_mismatch')
            ) {
                await acquireTokenRedirect(...)
            }

            throw e
        }
```

**Comment by jmckennon** [comment]
@antonfil yes, if you wanted to catch both of those errors and fallback to `acquireTokenRedirect`, that would work. Many errors can be solved by calling an interactive method, and some users will choose to do that in various scenarios.
