### ISSUE TITLE
Login timeouts / login not possible anymore for Australian AAD's (tenants)

### ISSUE THREAD

**Issue by Nasicus** [AzureAD/microsoft-authentication-library-for-js#2307]
- [x] `msal@1.4.0`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

MSAL

## Description

We noticed already quite a time ago that our Australian customers have a very slow performance when performing a log in or when refreshing tokens.

Starting a few days ago they couldn't even login at all anymore.
Sometimes they received something like `Token renewal operation failed due to timeout` (when already being logged in) and when they tried to log in freshly (private window, new browser, whatever) and came back from the microsoft login page to the app  some requests to `login.microsoft.com` were cancelled (seen in the network tab of the dev tools) and therefore it obviously also didn't work!

In my absolute desperation (since this is on production!) this morning I increased the `loadFrameTimeout` to a very high value (was not set before i.e. we used the default) and now the seem to be able to log in again (for the time being).

However obviously either we are doing something wrong (don't know what though) or there is a problem with Australian AADs... 
Either way there should be done something about this, since the user experience is very bad!

What would also be interesting if there are any other Australian users / devs around here, how the performance is for them and if they also have issues.

Also something to note is that our app registration is (obviously) a multi tenant app which was originally created in a our AAD which is hosted in West-Europe.

Here's our current MSAL config:

```
    const authConfig: Configuration = {
      auth: {
        clientId: this.authConfiguration.clientId,
        authority:  this.authority,
        redirectUri: `${this.appUrl}/login-complete`,
        postLogoutRedirectUri: postLogoutRedirectUri || this.appUrl,
        navigateToLoginRequestUrl: false,
        validateAuthority: true
      },
      cache: {
        cacheLocation: 'localStorage',
        storeAuthStateInCookie: env.browserName === 'ie'
      },
      system: {
        logger: this.getLogger(),
        loadFrameTimeout: 30 * 6000 // <-- this is the value I drastically increased now, we didn't set a value at all for this
      }
    };
```

**Comment by jmckennon** [comment]
Can you take a look at the network traces (both when on success and error/timeout) to try to see where the bottleneck is? You can send a fiddler trace to the email on my profile as well.

You can also set your `redirectUri` to a blank html page to prevent any reloading shenanigans. This speeds up the process for many users.

We've also had some reports of AAD slowing down, so I will make sure that the feedback is heard if that is the case. You can also leave feedback for the AAD service [here](https://feedback.azure.com/forums/169401-azure-active-directory).

**Comment by Nasicus** [comment]
Thanks for the response.

I don't want to bother another customer atm, but I already asked our infrastructure guys to give me an australian VM. As soon as I have it, I will create an australian demo tenant and can try to reproduce it.

I already strongly suspected that it's not MSAL-libraries fault, my hope was (is) that someone would give me a miracle setting like "you obviously have to set `enableGeoReplication: true` in your `manifest` file of your app ;) Or that one of you guys would forward this to the right guys from azure, since I find it quite hard to get to the right person there. That said we also plan on opening a ticket in azure for that.

**Comment by Nasicus** [comment]
Small update.

I now have an Australian VM (Central Australia).

I basically set up our "dev setup" there. This means all data is stored in a local (docker) database, therefore there are no API calls to anywhere else and of course the web app is also hosted locally.

I also removed my `loadFrameTimeout` setting again, so it's back to default.

I did a very basis test with 2 different AADs on this machine.

An Australian AAD:

I could login, however it was very slow and for `acquireTokenSilent` I often get timeouts:
![image](https://user-images.githubusercontent.com/1086065/94782777-00689e00-03cc-11eb-98f4-9b86bbaf3068.png)

The one who is cancelled / causes the timeout:
![image](https://user-images.githubusercontent.com/1086065/94783025-63f2cb80-03cc-11eb-9788-d1bebe8d78dc.png)
![image](https://user-images.githubusercontent.com/1086065/94782976-52112880-03cc-11eb-8610-ce1a94ec692a.png)


An West-Europe AAD (now remember: I'm testing this from an Australian VM!):
Works!
![image](https://user-images.githubusercontent.com/1086065/94783286-c350db80-03cc-11eb-91f0-853af9fa2b8a.png)

So it's definitely related to the azure app registration (which is  - as written above- also living in a west-europe tenant).

**Comment by Nasicus** [comment]
@jmckennon fyi I just had a call with a Microsoft Support Engineer (via an Azure Ticket) and sent him the HAR and fiddler files. He said he will keep yo updated.

**Comment by jmckennon** [comment]
@Nasicus I would still recommend trying to set your `redirectUri` to a blank or almost blank html page (if you haven't tried that already) to try and speed up the auth process--that could also potentially help mitigate the problem. I will be in contact with the support engineer to provide assistance where I can.

**Comment by Nasicus** [comment]
@jmckennon our login-complete page is already quite minimal (and not the same page is the main app) I can not really reduce it any further.

**Comment by jmckennon** [comment]
@Nasicus Okay, for now, hopefully you can use `loadFrameTimeout` to mitigate the problem. I will be escalating this to the server team and have accessed the support engineer to do the same as I believe this is out of scope for the `msal` library and could be a problem with the service. It also just may be that the latency between West EU and Australia makes that big of a difference in load times. You can try creating another tenant/app reg in Australia and pointing your Australian customers to that version to reduce latency if that is the case.

I'll leave this open to report any information I find.
