### ISSUE TITLE
How does Angular use MSAL to add an authorization code stream with PKCE?

### ISSUE THREAD

**Issue by fengzhihenxs** [AzureAD/microsoft-authentication-library-for-js#2308]
hi，Does the latest version of Microsoft Authentication Library for Angular (msal-angular: 1.1.1) support pkce?
 
If Angular is not supported to implement pkce, how to implement it?

**Comment by mathieu2em** [comment]
I have the same question. Thank you.

**Comment by jasonnutter** [comment]
MSAL Angular does not yet support PKCE. We will be updating it to support MSAL.js v2, and will post more details about this soon.

For now, you can use MSAL.js v2 directly. We have a sample that demonstrates how to do this: https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular10-browser-sample
