### ISSUE TITLE
Build error after upgrading to Angular 10 and opting out of Ivy

### ISSUE THREAD

**Issue by felixvanleeuwen** [AzureAD/microsoft-authentication-library-for-js#2309]
## Library
- `msal@1.4.0`
- `@azure/msal-angular@1.1.1`
- `@angular/core@10.1.1`

Disabled Ivy: `"angularCompilerOptions": { "enableIvy": false }`
## Framework
Angular 10

## Description
After upgrading to angular 10 MSAL gives us a build error.
We were using older versions of MSAL before the upgrade and figured updating to the latest versions would fix something.
This was not the case though and looking at the NPM page implies that angular 10 is not supported:
![image](https://user-images.githubusercontent.com/64589372/93433370-fff9de80-f8c6-11ea-81f7-603ea9fff8da.png)
However, there's also a line about following the angular support schedule:
![image](https://user-images.githubusercontent.com/64589372/93433455-1bfd8000-f8c7-11ea-8042-8641381bc3ca.png)
To me, this implies that angular 10 is supported, since 10 is currently active.
![image](https://user-images.githubusercontent.com/64589372/93433522-2e77b980-f8c7-11ea-9332-c282d196d95c.png)

With a build error like it leads me to conclude that angular 10 is not supported by the msal-angular package.
Is this conclusion correct?

## Error Message
`msal.module.d.ts:5:86 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s)`
Importing ModuleWithProviders from angular core: `import { ModuleWithProviders } from "@angular/core";`

**Comment by Vizzr** [comment]
I don't know why it doesn't work for you, but I can tell you that it works for me.
Running the same package versions as you specified.

**Comment by felixvanleeuwen** [comment]
@Vizzr are you sure you are using the `@angular/core` version that I listed?
Can you check the package.json file to see if you're not just installing a version from your cache or something?

https://angular.io/guide/deprecations#modulewithproviders-type-without-a-generic
Angular documentation is pretty clear on having to use a generic type when extending `ModuleWithProviders`.

**Comment by felixvanleeuwen** [comment]
Even the source [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/src/msal.module.ts#L21) shows no use of a generic type.

**Comment by Vizzr** [comment]
> @Vizzr are you sure you are using the `@angular/core` version that I listed?
> Can you check the package.json file to see if you're not just installing a version from your cache or something?
> 
> https://angular.io/guide/deprecations#removed-apis-1
> Angular documentation is pretty clear on having to use a generic type when extending `ModuleWithProviders`.

"dependencies": {
    "@angular-mdc/web": "^6.0.0-canary.9",
    "@angular/animations": "^10.1.1",
    "@angular/cdk": "^10.2.0",
    "@angular/common": "^10.1.1",
    "@angular/compiler": "^10.1.1",
    "@angular/core": "^10.1.1",
    "@angular/forms": "^10.1.1",
    "@angular/material": "^10.2.0",
    "@angular/material-moment-adapter": "^10.2.0",
    "@angular/platform-browser": "^10.1.1",
    "@angular/platform-browser-dynamic": "^10.1.1",
    "@angular/router": "^10.1.1",

And you can try it for yourself by upgrading the Sample Angular 9 Application to Angular 10.

**Comment by felixvanleeuwen** [comment]
Tried the sample, it works.
Then tried the sample again without Ivy:
`"angularCompilerOptions": {
    "enableIvy": false
  }`
This breaks the compile of the source code of the sample itself.
When inspecting the `msal.module.d.ts` the error I reported is also here.

I will update the bug description to better reflect what is going on.

**Comment by xmesaj2** [comment]
Go to
``node_modules\@azure\msal-angular\src\msal.module.d.ts``
search
``ModuleWithProviders;``
and replace with
``ModuleWithProviders<any>;``
as a temp workaround for Angular 10

**Comment by felixvanleeuwen** [comment]
That's fine for a local build but setting that up for our build pipelines is a little funky.

**Comment by xmesaj2** [comment]
Perhaps can still do it little hacky over an extra step after npm install and before ng build that invokes script that does eg. find and replace of that line
in the `angular.json` dir
```javascript
const fs = require('fs');
const path = require('path');

function searchReplaceFile(regexpFind, replace, fileName) {
    var file = fs.createReadStream(fileName, 'utf8');
    var newcontent = '';

    file.on('data', function (chunk) {
        newcontent += chunk.toString().replace(regexpFind, replace);
    });

    file.on('end', function () {
        fs.writeFile(fileName, newcontent, function(err) {
            if (err) {
                return console.log(err);
            } else {
                console.log('Updated');
            }
        });
    });
};
var msalnpm = path.join('node_modules', '@azure', 'msal-angular', 'src', 'msal.module.d.ts');
searchReplaceFile(/ModuleWithProviders;/g, 'ModuleWithProviders<any>;', msalnpm);
```

**Comment by felixvanleeuwen** [comment]
@jasonnutter As assignee to this issue, any word?

**Comment by felixvanleeuwen** [comment]
@jasonnutter

**Comment by jasonnutter** [comment]
Apologies for the delay on this. #2577 will pass the needed generic. Please note, while this should make it possible to use MSAL Angular v1 with Angular 10 as described in this issue, MSAL Angular v2 will be the recommended supported version for Angular 10 applications.

**Comment by felixvanleeuwen** [comment]
Is there an ETA for when this version will be released to NuGet?

**Comment by jasonnutter** [comment]
`@azure/msal-angular@1.1.2` is now available on npm.
