### ISSUE TITLE
Updating causes a switch from v2 token to invalid v1 token

### ISSUE THREAD

**Issue by snebjorn** [AzureAD/microsoft-authentication-library-for-js#2310]
## Library
- [x] `msal@1.4.0`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.1.1`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Updating from 
```
@azure/msal-angular     1.0.0  →    1.1.1   
msal                    1.3.4  →    1.4.0
```
Causes a switch in the token sent to self (localhost).
Before it was a v2 token.
Now it's a v1 token, and on top of that the signature is invalid.

None of the changelogs indicated this switch. Or the invalid token.

## Error Message
Response headers:
```
server: Kestrel
status: 401
www-authenticate: Bearer error="invalid_token", error_description="The signature is invalid"
```

## Security
- [ ] Is this issue security related?

## Regression
- [x] Did this behavior work before? 
Version:

```
@azure/msal-angular     1.0.0
msal                    1.3.4 
```

## MSAL Configuration

```ts
const msalConfig: Configuration = {
  auth: {
    authority:
      "https://login.microsoftonline.com/hidden/",
    clientId: "hidden",
    navigateToLoginRequestUrl: true,
    postLogoutRedirectUri: "http://localhost:4200/logged-out",
  },
  cache: {
    cacheLocation: "localStorage",
  },
};
const msalAngularConfig: MsalAngularConfiguration = {
  consentScopes: ["User.Read", "User.Read.All", "openid", "profile"],
  popUp: true,
  protectedResourceMap: [
    ["https://graph.microsoft.com", ["profile", "User.Read", "User.Read.All"]],
  ],
};
```

## Reproduction steps
In my ASP.NET Core backend I have
```cs
services.AddAuthentication(AzureADDefaults.JwtBearerAuthenticationScheme)
    .AddAzureADBearer(options => Configuration.Bind("AzureAd", options));

services.Configure<JwtBearerOptions>(AzureADDefaults.JwtBearerAuthenticationScheme, options =>
{
    // This is a Microsoft identity platform web API.
    options.Authority += "/v2.0";
});
```
In angular I use the `MsalInterceptor`

```
providers: [
    {
      multi: true,
      provide: HTTP_INTERCEPTORS,
      useClass: MsalInterceptor,
    },
    MsalService,
]
```

## Browsers/Environment
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jmckennon** [comment]
Have you looked at any network/fiddler traces of the behavior you're seeing? You can send them to the email on my profile for us to take a look. If you can provide two traces, one of the successful call and one with the erroneous one, we may be able to see what the problem is.

**Comment by snebjorn** [comment]
@jmckennon you've got mail :)

While I was gathering the data I observed some strange behavior! (in the new version)
It makes two requests to `/oauth2/v2.0/authorize?response_type=id_token` right after each other. This didn't happen before the update.
Another weird thing I observed was that sometimes it would attach the correct v2 token.

**Comment by jmckennon** [comment]
Wanted to update here--I couldn't get any great reasoning from the logs, so I'm going to escalate this internally to the server team. My guess is something may just need to be changed in the configuration of the portal/app reg. Will report back with information when I have it, sorry for the delay.

**Comment by jmckennon** [comment]
A thought I also just had would be to recreate your app registration and test the updated version against that app reg to see if it fixes the problem.

**Comment by jmckennon** [comment]
@snebjorn Are you requesting tokens from Microsoft Graph and then validating them in your backend? If so, you should not be using Microsoft Graph tokens to authorize your API--you should instead create a custom scope for your resource and request tokens for it.

**Comment by snebjorn** [comment]
@jmckennon we're requesting tokens from the MS Graph and using it in the frontend to call MS Graph directly (from the frontend). But we also use the token to identify the user when they make calls to the backend. Adding a custom scope to the token doesn't add any value, that I can see, as we're only interested in the object id (AzureAD guid) of the token. We validate the token on the backend so it cannot be tampered with.

**Comment by jmckennon** [comment]
Tokens that are issued for Microsoft Graph should only be sent and inspected by Microsoft Graph, you shouldn't be validating or using them to identify the user on your backend.

**Comment by snebjorn** [comment]
thanks for bringing that to my attention. I'll have to investigate this

**Comment by DK8ALREC** [comment]
@jmckennon what do you mean when you say "issued for Microsoft Graph"? And why not use the token in your own backend if using Azure AD for single sign-on?

Microsoft [documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-overview) on MSAL says:
"Microsoft Authentication Library (MSAL) enables developers to acquire tokens from the Microsoft identity platform endpoint in order to access secured web APIs. These web APIs can be the Microsoft Graph, other Microsoft APIs, third-party web APIs, or your own web API."
