### ISSUE TITLE
State error b2c 

### ISSUE THREAD

**Issue by rnkpareek** [AzureAD/microsoft-authentication-library-for-js#2312]
Hello,
I request you people to create a clear documentation and the samples code itself have issues.
I have faced a lot of issues while doing refresh tokens and iam facing state routes Error now..

**Comment by jmckennon** [comment]
Hi @rnkpareek, we've been actively working on documentation and samples, and we definitely agree with your feedback that documentation could be improved.

If you can fill out the issue template and provide your `msal` versions, config, and usage, we can help with debugging or fixing any problems you may be seeing.

**Comment by jmckennon** [comment]
Closing this as I'm assuming the original question has been answered, if you have further questions please open a new issue. Thanks!
