### ISSUE TITLE
invalid_grant is being handled by calling ssoSilent which relies on ITP

### ISSUE THREAD

**Issue by thoo1** [AzureAD/microsoft-authentication-library-for-js#2313]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.0.2`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
When a refresh token is expired and we try to acquireTokenSilent, it will throw a invalid_grant error which is currently being handled by calling ssoSilent https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/2c75dcfdc3af95ce942433d950ceb95de085c3da/lib/msal-browser/src/app/ClientApplication.ts#L402

However, documentation for ssoSilent says that it relies on using an iframe to get a new refresh token. This relies on the browser allowing 3rd party cookies
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/2c75dcfdc3af95ce942433d950ceb95de085c3da/lib/msal-browser/src/app/ClientApplication.ts#L319

What happens if the user is using safari? This will fail right? What error will it fail with and is there a way to get a new refresh token for browsers that don't support 3rd party cookies like safari? This is one of the main reasons we want to switch to msal-browser is the support for safari's ITP.

I think this might be related to #2219? Not sure

**Comment by jmckennon** [comment]
This is by design. We attempt to get a new RT/auth code in an iframe, and if that fails the error will be thrown to the app where you should be invoking an interactive call. So yes, this is expected to fail in Safari with ITP--nonetheless, even in other browsers, you should have that fallback logic in place.

**Comment by thoo1** [comment]
@jmckennon thanks for the quick response

Nice that makes sense! I'm wondering what error it will throw? We already handle `InteractionRequiredAuthError` and call `acquireTokenRedirect`.

**Comment by thoo1** [comment]
@jmckennon and a follow up, does this mean to make an interactive call (acquireTokenRedirect) if the iframe times out as well? Because you mentioned "nonetheless, even in other browsers, you should have that fallback logic in place."

**Comment by jmckennon** [comment]
> I'm wondering what error it will throw?

Yes, it will throw `InteractionRequiredAuthError`.

> does this mean to make an interactive call (acquireTokenRedirect) if the iframe times out as well?

It depends on what's causing the timeouts, but calling an interactive method can be a good fallback for timeouts.

**Comment by thoo1** [comment]
@jmckennon for `monitor_timeout_error`s, they are`BrowserAuthError`s instead of `InteractionRequiredAuthError`s, just want to make sure if this is expected?

If so, I'll update our code to call interactive methods as a fallback for these `monitor_timeout_error`s as well (as right now we only do so for `InteractionRequiredAuthError`s

**Comment by jmckennon** [comment]
You are correct--I was mistaken, I just double checked and it it most definitely a `BrowserAuthError`. The actual error code is `monitor_window_timeout`, if we are talking about the same error. Can be seen [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/5783a8157633b4e6aa0dac330b4d4265bdbaa4f3/lib/msal-browser/src/error/BrowserAuthError.ts#L52).
