### ISSUE TITLE
loadFrameTimeout not doing what it is documented to in msal-browser?

### ISSUE THREAD

**Issue by thoo1** [AzureAD/microsoft-authentication-library-for-js#2314]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.0.2`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
React
## Description
Noticed this while I was reading what `loadFrameTimeout` does, in the documentation:
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/90e0231e749e11c200290322abdcc32b67cddfb3/lib/msal-browser/src/config/Configuration.ts#L55

But in the code https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/2c75dcfdc3af95ce942433d950ceb95de085c3da/lib/msal-browser/src/interaction_handler/SilentHandler.ts#L105, I see it is being used in a setTimeout. How I'm understanding this is that this value delays the load of the iframe. Is this expected?
## Error Message
No error, just wondering if the config is doing what it says it does in the documentation 
## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Browsers/Environment
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jmckennon** [comment]
The value here does not delay the load of the frame, it is the maximum amount of time to wait for a frame to load. It is a timeout based on the iframe loading.

**Comment by thoo1** [comment]
@jmckennon doesn't `setTimeout` only run the function once the timer expires? so in this case, it waits `this.loadFrameTimeout` milliseconds before running the function, and the function starts the iframe loading. Maybe I'm misunderstanding something here..

**Comment by jmckennon** [comment]
@thoo1 I think I misunderstood your original question, and upon taking a second look, you're correct that there's a disconnect here and is actually a bug. We're going to move this over to be fixed, thanks for the heads up!

**Comment by jasonnutter** [comment]
@thoo1 PR has been opened to restore `loadFrameTimeout` to how it worked in v1 and add `navigateFrameWait` from v1. Feedback appreciated.
