### ISSUE TITLE
Build Error occurs when tsconfig 'strict: true'

### ISSUE THREAD

**Issue by Takas0522** [AzureAD/microsoft-authentication-library-for-js#2316]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.2.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework

None

## Description

I tried to use '@azure/msal-browser' in TypeScript.

At that time, if strict of TypeScript tsconfig.json is specified as true, an error will occur and the build will fail.

The phenomenon can be reproduced with the sample of `microsoft-authentication-library-for-js/samples/msal-browser-samples/TypescriptTestApp2.0`.

## Error Message

> node_modules/@azure/msal-common/dist/src/cache/CacheManager.d.ts:78:5 - error TS2416: Property 'getCredential' in type 'CacheManager' is not assignable to the same property in base type 'ICacheManager'.
  Type '(key: string) => CredentialEntity | null' is not assignable to type '(key: string) => CredentialEntity'.
    Type 'CredentialEntity | null' is not assignable to type 'CredentialEntity'.
      Type 'null' is not assignable to type 'CredentialEntity'.

## Security
- [ ] Is this issue security related?

## Regression
- [x] Did this behavior work before? 
Version: 2.1.0

## MSAL Configuration

I think that it occurs regardless because it is at build time.

## Reproduction steps

* tsconfig.json
``` json
{
    "compilerOptions": {
        "target": "ES2017",
        "module": "CommonJS",
        "noImplicitAny": true,
        "moduleResolution": "node",
        "rootDir": "./src",
        "outDir": "./build-tsc",
        "strict": true
    }
}
```
Same settings as `samples/msal-browser-samples/TypescriptTestApp2.0`, except `strict:true`.

* src/index.ts
``` js
import { PublicClientApplication } from '@azure/msal-browser';
const client = new PublicClientApplication({ auth: { clientId: '' } });
```

1. run `tsc`

## Expected behavior

Build is not fails.

## Browsers/Environment
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by Takas0522** [comment]
Sorry.
Did this behavior work before?
❌Version: 2.1.0
⭕Version: 2.0.0

**Comment by jmckennon** [comment]
I was able to reproduce this with our sample, thanks for the heads up. Mitigation for now is to use `"strict": false`. Thanks!

**Comment by DarkLite1** [comment]
Same TS error here after upgrading from `"@azure/msal-browser": "2.1.0"` to "@azure/msal-browser": "2.2.0":

![image](https://user-images.githubusercontent.com/10828570/93762138-4c1e8900-fc0f-11ea-9c15-7325077b6069.png)

Downgrading for now.
