### ISSUE TITLE
CORS issue when exchanging authorization code for token

### ISSUE THREAD

**Issue by DASPRiD** [AzureAD/microsoft-authentication-library-for-js#2317]
## Library
- [X] `@azure/msal-browser@2.2.0`

## Framework

React / SPA

## Description

When the login redirects back to the SPA, MSAL tries to exchange the authorization code for a token. The OPTIONS response of the `token` endpoint does in fact include the required CORS headers, but the following POST response does not. This leads to the following error message:

## Error Message

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://login.microsoftonline.com/XXX/oauth2/v2.0/token. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```ts
{
    auth: {
        authority: `https://login.microsoftonline.com/${process.env.REACT_APP_AAD_TENANT_ID}`,
        clientId: process.env.REACT_APP_AAD_CLIENT_ID,
        redirectUri: absoluteUrl('/').toString(),
    },
    cache: {
        cacheLocation: 'localStorage',
        storeAuthStateInCookie: false,
    },
}
```

## Reproduction steps
```ts
const tokenResponse = await msalClient.handleRedirectPromise();

if (!tokenResponse) {
   msalClient.loginRedirect({scopes});
}
```

## Expected behavior

Token exchange should work without CORS issues.

## Browsers/Environment
- [X] Chrome
- [X] Firefox
- [X] Edge
- [X] Safari
- [X] IE
- [X] Other (Please add browser name here)

**Comment by tnorling** [comment]
@DASPRiD Can you confirm that your redirectUri is registered in the Azure Portal as type "spa" and you do not have that same redirectUri also registered as type "Web"?

**Comment by pdl5p** [comment]
I've just seen this issue too. In my case my Azure AD App registration had the SPA redirect url set to http://localhost:3001, but also had a web redirect of http://localhost:3000. 

Once I removed the redirect url for the web, it started working. Seems like having different port numbers for the different app types is not a valid configuration.

**Comment by DASPRiD** [comment]
We figured it out yesterday: Even though the URLs were set up correctly only in the SPA section, there were entries for other clients in the web section (different URLs), and the implicit flags were checked for them. In summary, you cannot mix implicit and authorization code applications (which seems like a bug).

We've created a secondary app registration now, where we migrate everything in our dev environment to to authorization code now.

**Comment by tnorling** [comment]
@DASPRiD Great to hear you solved it! We are aware of issues with different type redirectUris configured on the same app registration and we recommend you keep separate app registrations for each of your apps. We will follow up with the portal team to understand whether and how this will be addressed, for now I'm going to close this as there's no further action needed on the library.

**Comment by DASPRiD** [comment]
@tnorling The problem with that approach is that multiple app registrations cannot expose the same application API, which is a blocker.

**Comment by tnorling** [comment]
@DASPRiD I would suggest you open a [support ticket](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request#:~:text=%20To%20start%20a%20support%20request%20from%20anywhere,your%20problem.%20We%27ll%20suggest%20some%20possible...%20More%20) since this is a problem with the portal/service and not with the library.
