### ISSUE TITLE
token refresh redirected to 'The reply URL specified in the request does not match

### ISSUE THREAD

**Issue by bilalmalik777** [AzureAD/microsoft-authentication-library-for-js#2321]
We are using adal-angular for authentication from the azure ad. After some time it redirects to the page which is attached below

![MicrosoftTeams-image](https://user-images.githubusercontent.com/23011613/93736509-1c03c580-fbd0-11ea-85f1-d91ffd52aaf4.png)
We have no idea why is it happening either it is caused by token expiration or re-login. It is occurring over both local and production environment. Even we have registered return url in application in ad
Please help us to solve this issue

**Comment by jmckennon** [comment]
You receive this error when the `redirectUri` used in your app on the request is not the same as one registered in AAD. Can you please confirm that these are always the same in your erroneous calls?

**Comment by bilalmalik777** [comment]
the issue  has been resolved 
thanks, @jmckennon  for your assistance
