### ISSUE TITLE
How do users log in that does not exist in the tenant's "default directory"?

### ISSUE THREAD

**Issue by fengzhihenxs** [AzureAD/microsoft-authentication-library-for-js#2322]
Hello, I want to know how to log in if the logged-in user is not in the tenant's "default directory"? For example, I want to log in with a Skype or Microsoft account, but they are not in the "default directory" of the application tenant. How to implement or set up the application?

For example, the official demo: https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular10-browser-sample.   How do all users who have registered to log in?

**Comment by jmckennon** [comment]
@fengzhihenxs Can you fill out the issue template with your config, versions, and usage? We will need more information to help with questions and debugging.

> Hello, I want to know how to log in if the logged-in user is not in the tenant's "default directory"? For example, I want to log in with a Skype or Microsoft account, but they are not in the "default directory" of the application tenant. How to implement or set up the application?

To clarify: is the problem that you can't login with any Microsoft account at all? You may need to just make your set your app to be multi-tenanted to enable this functionality.

**Comment by fengzhihenxs** [comment]
@jmckennon   
## Library 
- [ ] `@azure/msal-browser@2.2.0` 

## Description
I want to log in with a Skype or Azure account, but they are not in the tenant's "default directory". How to implement or set up the application?
In the official demo, the logged-in user may not be in the default directory of azureserver in the demo. For example, my azure account is not there, but I can log in and get the token. I don’t understand how to implement or set the application.

Examples: 
https : //github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular10-browser-sample

**Comment by jmckennon** [comment]
I may still not be 100% clear on the issue, but I think [this documentation about multi-tenanted apps](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-convert-app-to-be-multi-tenant) will lead you in the right direction. To have any users (Skype/Azure/Microsoft) be allowed to login to your app, it must be multi-tenanted.
