### ISSUE TITLE
Forgot Password and Login Issue

### ISSUE THREAD

**Issue by rajeshvinayagam** [AzureAD/microsoft-authentication-library-for-js#2325]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Please provide your question here, including as much relevant details as possible.

Examples: 
> "How do I use MSAL with Vue.js"
> "How do I SSO between tabs?"
> "How do I use MSAL to protect my custom Web API?"
> "How can my app support multiple AAD tenants?"
> "When will my scenario be supported?"
> "When will this framework be supported"

**Comment by rajeshvinayagam** [comment]
##msal@1.3.3
Getting the below errors

1.  When i select forgot password link

 Redirect Error:  Login_In_Progress: Error during login call - login is already in progress.
{errorCode: 'login_progress_error', errorMessage: 'Login_In_Progress: Error during login call - login is already in progress.', name: 'ClientAuthError', stack: 'ClientAuthError: Login_In_Progress: Error dur…r (http://localhost:4200/vendor.js:279579:12)', message: 'Login_In_Progress: Error during login call - login is already in progress.'}


2. When I select SignIn with Third party cookies not set it gives the below error.

ERROR InteractionRequiredAuthError: AADB2C90077: User does not have an existing session and request prompt parameter has a value of 'None'.

**Comment by jmckennon** [comment]
@rajeshvinayagam Can you try to upgrade to `msal@1.4.0`? This may fix the issues you're seeing.

**Comment by rajeshvinayagam** [comment]
I tied updating the library still it produces the same error
