### ISSUE TITLE
storeAuthStateInCookie false is not being honor by msal api

### ISSUE THREAD

**Issue by franktr** [AzureAD/microsoft-authentication-library-for-js#2328]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x ] `@azure/msal-browser@2.1.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Description
Calling msal-browser ssoSilent /w storeAuthStateInCookie = false results in read of cookie instead of bypassing cookie a specified in the passed in configuration.

DOMException: Failed to read the 'cookie' property from 'Document': The document is sandboxed and lacks the 'allow-same-origin' flag.

## Error Message
DOMException: Failed to read the 'cookie' property from 'Document': The document is sandboxed and lacks the 'allow-same-origin' flag.

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

 const msalConfig = {
        auth: {
            clientId: "1234bb3f-12cc-42c3-ad06-5b608dc1234",
            authority: "https://login.microsoftonline.com/12345-9004-4d9b-991a-XXXXX", //
            prompt: "none"
        },
        cache: {
            cacheLocation: "sessionStorage", // This configures where your cache will be stored
            storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
        },

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Expected behavior
Not read cookie and make call directly

## Browsers/Environment
- [X ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jasonnutter** [comment]
@franktr Thanks! Confirmed that MSAL attempts to read from `document.cooke` before checking if `storeAuthStateInCookie` is set: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/1c1a65f9ccdf7f31b53e10f0a1fe5397afd4d788/lib/msal-browser/src/cache/BrowserStorage.ts#L180-L181

**Comment by sameerag** [comment]
#2415
