### ISSUE TITLE
Strictest Possible Content Security Policy?

### ISSUE THREAD

**Issue by talismax** [AzureAD/microsoft-authentication-library-for-js#233]
Has anyone done the brain damage on how to craft the strictest possible content security policy for an app using this lib?

Here's the config I was using for my app:
"ContentSecurityPolicyConfiguration": {
      "DefaultSrc": [
        "'self'"
      ],
      "ScriptSrc": [
        "'self'",
      ],
      "StyleSrc": [
        "'self'",
        "'unsafe-inline'",
      ],
      "FontSrc": [
        "'self'",
        "data:"
      ],
      "ConnectSrc": [
        "'self'",
        "https://login.microsoftonline.com/",
        "https://graph.microsoft.com/"
      ],
      "FrameSrc": [
        "'self'",
        "https://login.microsoftonline.com/"
      ],
      "BaseUri": [
        "'none'"
      ],
      "BlockAllMixedContent": "true",
      "UpgradeInsecureRequests": "true",
      "ReportUri": ""
    },

However, I kept getting script-src violations (unsafe inline) in the "#access_token=" callback. My app worked in spite of this violation being blocked so maybe there's a setting to turn this off?

 I'm also curious if the urls above are guaranteed not to change?

**Comment by talismax** [comment]
Is no one else implementing CSP in their app? Is this a dumb question?

**Comment by rohitnarula7176** [comment]
@talismax Closing this as this is out of scope for the library.
