### ISSUE TITLE
Upgrading to msal-angular@1.1.1 from 0.1.4 - Help handling redirect URL with an invitation flow.

### ISSUE THREAD

**Issue by mcdonnell-john** [AzureAD/microsoft-authentication-library-for-js#2330]
# Library
- [X] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [X] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Up until recently we were using @azure/msal-angular@0.1.4, since we upgraded to 1.1.1 we've introduce an issue where by the invitation flow we had doesn't work any more.

The flow we have is:
![image](https://user-images.githubusercontent.com/2251059/93865798-b7736400-fcbe-11ea-9e73-fec35db0a294.png)

But since upgrading to 1.1.1/ msal@1.4.0 the invitation flow no longer works, presumably because we had to implement a handleRedirectCallback:
```
    this.authService.handleRedirectCallback((authError, response) => { 
      if (authError && this.appConfig.config.authentication.enableLogging) {
        console.error('Redirect Error: ', authError.errorMessage);
        return;
      }
    });
```
Without this a user wasn't able to login normally because they kept getting redirected back to the login screen and not into our application.

My question is how can we implement the handleRedirectCallback to handle this?  

Our msal configuration has some of the following properties:
```
{
    "clientID": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
    "authority": "https://login.microsoftonline.com/tfp/XXX.onmicrosoft.com/B2C_1A_signup_signin_adacap-r2sys",
    "redirectUri": "https://XXX/login",
    "validateAuthority": false,
    "cacheLocation": "localStorage",
    "postLogoutRedirectUri": "https://XXX/login",
    "navigateToLoginRequestUrl": false,
    "popUp": true,
    "consentScopes": [
        "user_impersonation",
        "https://XXX.onmicrosoft.com/api/user_impersonation"
    ],
    "protectedResourceMap": [
        [
            "https://localhost:44380",
            [
                "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
            ]
        ]
    ],
    "loadFrameTimeout": 900000,
    "renewTokenBeforeExpires": 1800000,
    "enableLogging": false,
    "enablePiiLogging": false
}
```
And our current login.component.ts has the following(I've stripped down alot of it as its not part of this):
```
@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit, OnDestroy {

  public isLoading = false;

  constructor(protected router: Router,
    protected authService: MsalService,
    protected broadcastService: BroadcastService,
    protected authorisationService: AuthorisationService,
    protected http: HttpClient,
    protected axEntityTypesService: AxEntityTypesService,
    protected usersService: UsersService,
    protected legalTextService: LegalTextService,
    protected ccService: NgcCookieConsentService,
    private appConfig: AppConfigService) {
    
    this.authService.handleRedirectCallback((authError, response) => { 
      if (authError && this.appConfig.config.authentication.enableLogging) {
        console.error('Redirect Error: ', authError.errorMessage);
        return;
      }
    });
    
    this.broadcastService.subscribe('msal:loginSuccess', () => {
      this.handleLoginSuccessEvent();
    });

    broadcastService.subscribe("msal:loginFailure", (payload) => {
      if (this.b2cForgotPassword()) {
        localStorage.setItem('redirect', 'login');
        this.router.navigate(['forgot-password']);
      }
      else if (this.authorisationService.currentUser && !this.authorisationService.currentUser.isActive())
        this.router.navigate(['unauthorised']);
    });
  }

  login() {
    this.authService.loginRedirect();
  }

  handleLoginSuccessEvent() {
    if (localStorage.getItem('redirect')) {
      this.router.navigate(['/login']);
      localStorage.clear();
    }
    else {
      if (this.authorisationService.currentUser != null && this.http != null) {
        this.isLoading = true;
        
        // do some things with the current user setting them up correctly before:
        
        this.isLoading = false;
        this.router.navigate(['/dashboard']);
      }
    }
  }
}

```

**Comment by mcdonnell-john** [comment]
Additionally the msal logging when we do press confirm on the confirmation screen and are redirected back to the login screen, it doesn't show much to me but it might help in investigating:
```
Tue, 22 Sep 2020 10:40:33 GMT:a44345ac-0a15-4fba-8dfd-241a2dfa2d59-1.4.0-Verbose GetResponseState has been called
Tue, 22 Sep 2020 10:40:33 GMT:a44345ac-0a15-4fba-8dfd-241a2dfa2d59-1.4.0-Verbose GetResponseState has been called
Tue, 22 Sep 2020 10:40:33 GMT:a44345ac-0a15-4fba-8dfd-241a2dfa2d59-1.4.0-Verbose GetResponseState has been called
Tue, 22 Sep 2020 10:40:33 GMT:a44345ac-0a15-4fba-8dfd-241a2dfa2d59-1.4.0-Verbose GetResponseState has been called
```

**Comment by jmckennon** [comment]
When the user is redirected from B2C to the app, is there information included in the URL about the user?

**Comment by mcdonnell-john** [comment]
Hi @jmckennon 

Yes, when the user is redirected from B2C to our app, they have an id_token:
```
GET https://XXX/login#id_token=XXXXXXXXXXXX
```
If I decode that token, it has my users details.

I also added some logging to the handleRedirectCallback:
```
this.authService.handleRedirectCallback((authError, response) => { 
      if (authError) {
        console.log("B2C - Auth Error" + JSON.stringify(authError));
      }
      if (response) {
        console.log("B2C - Redirect Response" + JSON.stringify(response));
      }
      // previous error handling logic in initial post... 
    });
```

But neither were logged to the console, so maybe my assumption about needing to do something in this method is incorrect since its not called?  Or should it be?

**Comment by jmckennon** [comment]
I believe what's happening here is that you click the email and are immediately redirected to B2C, so when B2C redirects to the app, `msal` doesn't actually have the correct context and cache contents, so it doesn't process the hash.

The solution is to email the user a link to the application which attaches the query parameters needed (`id_token_hint`) and have that initiate the request to B2C so that `msal` can properly populate cache values.

I will leave this ticket open to help us track getting documentation on this problem, as it's not very well explained or easy to figure out.

**Comment by mcdonnell-john** [comment]
Hi @jmckennon,

So we do this already.  When we generate the email link to the user, we generate a `id_token_hint` query parameter, which is made up of 3 claims, firstName lastName and email, which are referenced in our B2C Custom Policy.

Just gonna paste some key extracts from this policy file here:

```
<TrustFrameworkPolicy xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.microsoft.com/online/cpim/schemas/2013/06" PolicySchemaVersion="0.3.0.0" TenantId="XXX.onmicrosoft.com" PolicyId="B2C_1A_signup_invitation-r2sys" PublicPolicyUri="http://XXX.onmicrosoft.com/B2C_1A_signup_invitation-r2sys" TenantObjectId="XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX">
  <BasePolicy>
    <TenantId>XXX.onmicrosoft.com</TenantId>
    <PolicyId>B2C_1A_TrustFrameworkExtensions-r2sys</PolicyId>
  </BasePolicy>
  <BuildingBlocks>
    // Building Blocks
  </BuildingBlocks>
  <ClaimsProviders>
    // LocalAccountSignUpWithReadOnlyEmail - (Technical Profile)
    // SelfAsserted-Unsolicited - (Technical Profile)
    <ClaimsProvider>
      <DisplayName>My ID Token Hint ClaimsProvider</DisplayName>
      <TechnicalProfiles>
        <TechnicalProfile Id="IdTokenHint_ExtractClaims">
          <DisplayName> My ID Token Hint TechnicalProfile</DisplayName>
          <Protocol Name="None" />
          <Metadata>
            <Item Key="METADATA">https://XXX/.well-known/openid-configuration</Item>
          </Metadata>
          <OutputClaims>
            <OutputClaim ClaimTypeReferenceId="email" />
            <OutputClaim ClaimTypeReferenceId="firstName" />
            <OutputClaim ClaimTypeReferenceId="lastName" />
          </OutputClaims>
        </TechnicalProfile>
      </TechnicalProfiles>
    </ClaimsProvider>
  </ClaimsProviders>
  <UserJourneys>
    <UserJourney Id="SignUpInvitation">
      <OrchestrationSteps>
        <OrchestrationStep Order="1" Type="GetClaims" CpimIssuerTechnicalProfileReferenceId="IdTokenHint_ExtractClaims" />
        <OrchestrationStep Order="2" Type="ClaimsExchange">
          <Preconditions>
            <Precondition Type="ClaimsExist" ExecuteActionsIf="true">
              <Value>email</Value>
              <Action>SkipThisOrchestrationStep</Action>
            </Precondition>
          </Preconditions>
          <ClaimsExchanges>
            <ClaimsExchange Id="SelfAsserted-Unsolicited" TechnicalProfileReferenceId="SelfAsserted-Unsolicited" />
          </ClaimsExchanges>
        </OrchestrationStep>
        <OrchestrationStep Order="3" Type="ClaimsExchange">
          <ClaimsExchanges>
            <ClaimsExchange Id="LocalAccountSignUpWithReadOnlyEmail" TechnicalProfileReferenceId="LocalAccountSignUpWithReadOnlyEmail" />
          </ClaimsExchanges>
        </OrchestrationStep>
        <OrchestrationStep Order="4" Type="ClaimsExchange">
          <ClaimsExchanges>
            <ClaimsExchange Id="GetLoyaltyData" TechnicalProfileReferenceId="AzureFunctions-WebHook" />
          </ClaimsExchanges>
        </OrchestrationStep>
        <OrchestrationStep Order="5" Type="SendClaims" CpimIssuerTechnicalProfileReferenceId="JwtIssuer" />
      </OrchestrationSteps>
      <ClientDefinition ReferenceId="DefaultWeb" />
    </UserJourney>
  </UserJourneys>
  <RelyingParty>
    <DefaultUserJourney ReferenceId="SignUpInvitation" />
    <UserJourneyBehaviors>
      <ScriptExecution>Allow</ScriptExecution>
    </UserJourneyBehaviors>
    // PolicyProfile - (Technical Profile)
  </RelyingParty>
</TrustFrameworkPolicy>
```

So as I understand it, we should be doing everything you asked for.  This was working when we were on a much older version (0.1.4), but not in the later versions.

**Comment by tnorling** [comment]
@mcdonnell-john It's not clear from the policy what the flow is. It should be something like this: 

User clicks link in email -> your app calls `loginRedirect` or `loginPopup` with the `id_token_hint` passed into `extraQueryParameters` ->B2C service -> your app calls `handleRedirectCallback` to process response.

It looks like in the flow diagram you shared originally, that 2nd step is missing, can you confirm?

**Comment by mcdonnell-john** [comment]
Hi @tnorling,

No, I think the image I have is what we do now, but what you have above is slightly different.

Basically the link we generate as part of the email is in the following format:

`https://{tenant}.b2clogin.com/{tenant}.onmicrosoft.com/B2C_1A_signup_invitation-r2sys/oauth2/v2.0/authorize?client_id={clientId}&nonce={nonce}&redirect_uri=https://XXX/login&scope=openid&response_type=id_token&id_token_hint={generatedToken}`

This appears to be bypassing msal initially and is probably what @jmckennon might have been alluding too, correct?

If so potentially what we need to do is generate the link to point to something like:
`https://XXX/login?invitationToken={generatedToken}`
And in our login component in Angular if we have a invitationToken query param call `loginRedirect ` and pass the invitationToken value in the `extraQueryParameters` as a param with a key `id_token_hint`, Possibly?
And I believe, we'll need to update the `authority` to point to the correct B2C Policy in this situtation as well `https://login.microsoftonline.com/tfp/XXXX.onmicrosoft.com/B2C_1A_signup_signin_adacap-r2sys`

I'll be in the office early tomorrow so will be able to test this out if this makes sense to you.

**Comment by tnorling** [comment]
> This appears to be bypassing msal initially and is probably what @jmckennon might have been alluding too, correct?

Correct. msal.js will not process responses for requests that it did not create.

> pass the invitationToken value in the extraQueryParameters as a param with a key id_token_hint, Possibly?
> And I believe, we'll need to update the authority to point to the correct B2C Policy in this situtation as well https://login.microsoftonline.com/tfp/XXXX.onmicrosoft.com/B2C_1A_signup_signin_adacap-r2sys

Correct. Your call should look something like this: 
```js
const request = {
    authority: "your_invite_authority",
    extraQueryParameters: { 'id_token_hint': 'your_invite_token' }
}
msal.loginRedirect(request)
```

**Comment by mcdonnell-john** [comment]
Cool thanks, I'll test it out tomorrow

**Comment by mcdonnell-john** [comment]
Hi @tnorling apologies for the delay, we had some infrastructure issues :(

This works, we managed so update the email link a user gets to redirect to our application which then redirects the user to B2C using the msal `loginRedirect` method.
