### ISSUE TITLE
Need to call aquireTokenSilent after ssoSilent necessary?

### ISSUE THREAD

**Issue by daniel-seitz** [AzureAD/microsoft-authentication-library-for-js#2331]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
I have found different examples but no documentation about it:

Here https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/d1b306f8acf438d62033b045520e30f81f5bcd55/samples/msal-browser-samples/VanillaJSTestApp2.0/app/ssoSilent/auth.js
you call **acquireTokenSilent** after ssoSilent. It states that this is just necessary in order to support IE.

    ...
    myMSALObj.ssoSilent(silentRequest).then(() => {
            const currentAccounts = myMSALObj.getAllAccounts();
            accountId = currentAccounts[0].homeAccountId;
            showWelcomeMessage(currentAccounts[0]);

            // call aquireTokenSilent
            getTokenRedirect(loginRequest, currentAccounts[0]);  
        }).catch(error => {
    ....

And here https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-browser-samples/TypescriptTestApp2.0/src/AuthModule.ts you don't use it. 

    this.myMSALObj.ssoSilent(this.silentLoginRequest).then(() => {
            this.account = this.getAccount();
            UIManager.showWelcomeMessage(this.account);
    }).catch(error => {

- Since the recently published version works for IE11, is **calling aquireTokenSilent after ssoSilent** necessary anyway, or.. under which circumstances should we do this? 

ssoSilent already returns Promise < AuthenticationResult > , doesn't _aquireTokenSilent_ do the same thing anyway?

Thank you,
Daniel

**Comment by jmckennon** [comment]
Technically, you can pass the same scopes to `ssoSilent` that you would pass so `acquireTokenSilent`, however we recommend that you invoke them separately, especially if you have an application where you need to request access tokens for multiple resources.

**Comment by daniel-seitz** [comment]
@jmckennon thank you for the answer, however it's not clear to me, yet.

Perhaps I need to explain better, basically the code is as follows:

    this.authApp = new PublicClientApplication(msalConfig);

    this.authApp
            .handleRedirectPromise()
            .then((result: AuthenticationResult) => {
                if(!result) { // (right now I'm only interested in this path here)
                    const accounts = this.authApp.getAllAccounts();

                    if (accounts.length !== 1) {
                        return;
                    }

                    const ssoRequest = {
                        scopes: [],
                        loginHint: accounts[0].username,
                    } as AuthorizationUrlRequest;

                    const ssoResult = await this.authApp.ssoSilent(ssoRequest);

                    // ?? do we need this here ??
                    // const silentTokenRequest = { scopes: ssoResult.scopes, account: ssoResult.account } as SilentRequest;
                    // const silentTokenResult = await this.authApp.acquireTokenSilent(silentTokenRequest);

                    // set our app's authState with either ssoResult or silentTokenResult ??
                }
            })
    ;

If I understand you correctly:
- we don't need to call aquireTokenSilent **here** _since we are only interested here in the authenticated state._ 

- Later, i.e. when we try to call the API however, we should call aquireTokenSilent **with the corresponding scopes** to get the correct access token for the intended purpose.

Is this correct?

**Comment by jmckennon** [comment]
> If I understand you correctly:
>
>we don't need to call aquireTokenSilent here since we are only interested here in the authenticated state.
>
>Later, i.e. when we try to call the API however, we should call aquireTokenSilent with the corresponding scopes to get the correct access token for the intended purpose.
>
>Is this correct?

Exactly, that is our recommended usage.

**Comment by daniel-seitz** [comment]
Perfect, thank you.
