### ISSUE TITLE
Is the msal.idtoken safe to use for authentication

### ISSUE THREAD

**Issue by AnkHansen** [AzureAD/microsoft-authentication-library-for-js#2333]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Hi 

I am in the process of enabling our existing web site (Angular SPA with .Net Core API (and apps)) to make use of Azure AD through MSAL for authenticating our users. 

Our solution already has built in user-management, which I expect some portion of our customers will continue using. It is a single-tenant solution. So each customer has their own installation/domain. At some customers only the API is installed, along with a windows client - instead of the Angular SPA. So each customer will also have to register our solution as an App in their Azure AD.

In our solution we manage 2.000+ userrights, that are mapped to the users through User Groups. Obviously I cannot map these in Azure as API permissions. 

So my solution so far, is to use that MsalGuard on a landing page in my Angular SPA. 
This gives me the msal.idtoken, once the user has authenticated with MS. 

I have then made changes in the .Net Core API, and using Microsoft.AspNetCore.Authentication.AzureAD.UI so I can verify/authenticate the AzureAD tokens serverside. 

From my Angular site, I then call the API to give me an accessToken, which is similar to the accesstoken we use if customers just use username/password login on our site. It holds claims to identify the user, and from which we can deduct the authorization rights this user possesses. The API endpoint for getting the Access Token requires authorization - and the ID Token is sent as Authorization Bearer header. 

The first question is: 
I am currently using the IDToken received from MSAL to validate the users identity in the API. I do this using the "oid" claim. 
Would that be considered a correct approach? Or do I need to get an access token from MSAL? (I find that step not necessary.)
Asked on stackoverflow a week ago - and did not get fully enlightened. 
https://stackoverflow.com/questions/63879052/create-my-own-accesstokens-with-ms-identity-platform

Secondly. 
In the case we are now, I will make it possible for customers to enable Azure AD login on an already existing userbase. 
But the existing users are obviously not mapped with Object Identifier (oid-claim) yet. And I can't see the administrators locating the object id and set it manually to connect our user-object with the Azure-account. 
So, if I can't find a user with the oid of the idtoken, I am currently using the "preferred_email" claim from the id-token, and look up users in our system with the same mail registered - and then I connect the two and persist oid on our user object. 
Are there better approaches here? 
For new users, after AzureAD is enabled, I expect them to receive a welcome mail with a dedicated link to map the user with the Azure AD account they logon with. So we don't need the email step there. 

I hope you are able to answer the above - to make me more certain that I am doing the right or wrong things. :-) 

Best Regards
/Anders

**Comment by jmckennon** [comment]
I will first say that the usage you're trying to describe here is generally not fully supported by us, but it should theoretically work. It seems to me like you're on the right track and things are correct for your use case.

> I am currently using the IDToken received from MSAL to validate the users identity in the API. I do this using the "oid" claim.
Would that be considered a correct approach? Or do I need to get an access token from MSAL? (I find that step not necessary.)

This is fine as long as you are using the id token explicitly for user validation rather than resource acquisition (where you would want an access token).

> So, if I can't find a user with the oid of the idtoken, I am currently using the "preferred_email" claim from the id-token, and look up users in our system with the same mail registered - and then I connect the two and persist oid on our user object.
Are there better approaches here?

This also looks correct and is a perfectly valid usage.

You probably have already seen this, but I will plug the [quickstart showing how to expose a custom web API in an app](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-configure-app-expose-web-apis). It may be useful to leverage AAD more where you can--though you may also just want to stick to what you have.

**Comment by AnkHansen** [comment]
Thanks for the quick reply. 
I will continue on the path I am on. 

It would be great to not have the step where our product generates the access token, because we could then just claim standard OAuth2 compliant. 

But I can't figure out how to inject the extra information we need in our token (userid, roleid, and unitid) into the Azure token. 

It comes down to a chicken or egg dilemma. I can't trust that someone "IS" the userid, and is allowed to take on the roleid, or use the unitid - without valid authentication.
So I need the ID token for that - and Azure can't tell me the mapping to user, role and unit. 
So no matter how, I need the extra roundtrip to our API to get the userid, roleid, and unitid claims. 
So for external developers coding against our API - it can't be just an OAuth2 implementation because I need to add information to the token after it is generated. 

And then a  follow up on the scopes - this might be a good idea. 

Will it make sense to make a scope called API.Access? 

The purpose for this, as I see it, is that if some of the customer organization want to lock down API access even more, then by creating this scope, and saying only admins can grant it - then the individual users can not accept on their own - but need higher level access. 

Our customers vary a lot in security policies, but the main objective of using Azure AD and MSAL is to get single-sign-on and MFA. And the ability for the customer organization to e.g. close a user - and know their access is revoked. 

I think I still need to use my own access tokens later in the process, but could quite easily change the flow to
1. Require token from Azure (not sure if I can get Id + Access token for "API.Access" in one go - or need to calls) 
2. With the Azure Access Token, I call my API, and issue our site-generated Access Token
3. Use our site-generated Access Token until it expires. 
4. Then I need a refreshed AccessToken from Azure, and go to step 2. 

The benefit of this approach will be
- There is an explicit scope in Azure AD on the Application registration
- This grant can be revoked - and then the user can no longer use our product. 
  - The ID token cannot be revoked unless a User is closed. 
  - Is it possible for domain admin to revoke access to scopes for other users in the domain? 

I think I might experiment a bit with that. 

Once again - thanks for the quick and clear reply.

**Comment by jmckennon** [comment]
> Will it make sense to make a scope called API.Access?

The purpose for this, as I see it, is that if some of the customer organization want to lock down API access even more, then by creating this scope, and saying only admins can grant it - then the individual users can not accept on their own - but need higher level access.

Yes, this is the exact use case for a custom scope. AAD wants users to be able to get tokens for an arbitrary setup using scopes.

> Require token from Azure (not sure if I can get Id + Access token for "API.Access" in one go - or need to calls)
With the Azure Access Token, I call my API, and issue our site-generated Access Token
Use our site-generated Access Token until it expires.
Then I need a refreshed AccessToken from Azure, and go to step 2.

This also seems correct to me for your use case. It's unfortunate that you'll have to basically do auth twice--once against AAD and once against your app--but if my understanding is correct, that may just be the nature of the situation here.

**Comment by AnkHansen** [comment]
Thanks again.

And yes - I think i'm stuck with the two authorizations. 

I need the token I use for data-requests to include the additional claims. But who knows - I might find a better way before I'm done.
