### ISSUE TITLE
loginRedirect on msal-browser from CDN causes a CORS error and no token provided.

### ISSUE THREAD

**Issue by tylerjwatson** [AzureAD/microsoft-authentication-library-for-js#2338]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.
msal@2.1.0

## Framework

Simple HTML page.

## Description

Following instructions on https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-browser I cannot get msal-browser to log in even in the simplest of use cases.  

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

The entire project has been elided to one file for the purposes of reproduction:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>

  <script src="https://alcdn.msauth.net/browser/2.1.0/js/msal-browser.js"
    integrity="sha384-M9bRB06LdiYadS+F9rPQnntFCYR3UJvtb2Vr4Tmhw9WBwWUfxH8VDRAFKNn3VTc/"
    crossorigin="anonymous">
  </script>

  <script>
    var ua = new msal.PublicClientApplication({
      auth: {
        clientId: '<app id>',
      }
    });

    (async function() {
      const token = await ua.handleRedirectPromise();
      console.log(token);
    })();

    function login(ev) {
      ua.loginRedirect({});
    }
  </script>

</head>
<body>
  <button onclick="login()">do the stuff</button>
</body>
</html>
```

## Reproduction steps
```js
1) copy the index.html file into a directory
2) put a client ID in it
3) start a live server on a localhost URL and port set in the app's redirect URIs
4) press "do the stuff" to initiate a loginRedirect
5) log in with an account in that tenant
5) observe CORS error in console and no login condition upon redirect back to client
```

## Expected behavior

It works in some capacity.

## Browsers/Environment
- [X] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jasonnutter** [comment]
@tylerjwatson Is the redirect URI of type "spa"? This is required for MSAL.js v2 to work cross-origin.

**Comment by tylerjwatson** [comment]
Thanks for the reply @jasonnutter, that was it.  I had no idea the `Spa` redirect URI type existed.

For future visitors:

MSAL 2.x PKCE flow requires a Redirect URI entry of type `Spa`.  `Web` Redirect URIs are not supported.  You need to edit your application entry's manifest and change the `Web` type to `Spa` to enable PKCE flow.

1) As of the time of writing, use the *Add a Platform* button on the Application Registration page in Azure AD
<img width="729" alt="image" src="https://user-images.githubusercontent.com/5001408/94211106-e2a2c100-ff13-11ea-909b-2da70bf92849.png">

2) Pick Single-page application
<img width="587" alt="image" src="https://user-images.githubusercontent.com/5001408/94211141-f9491800-ff13-11ea-907d-7fe9816aa2a6.png">

3) Add SPA Redirect URIs in the Application Registration page
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/5001408/94211018-b129f580-ff13-11ea-9c8d-264a4b976ca1.png">
