### ISSUE TITLE
B2C support for MSAL.js 2.0 with Authorization Code Flow

### ISSUE THREAD

**Issue by s2ramana** [AzureAD/microsoft-authentication-library-for-js#2340]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
The Readme states that B2C support for MSAL.js 2.0 with Authorization Code Flow is not yet available. Is this still the case? If so, when will it be available? 

We are currently using MSAL.js 1.x with implicit flow for our web apps and we are waiting for support for Authorization Code Flow with PKCE to increase our security.

**Comment by jmckennon** [comment]
This is correct, we are still not ready to use B2C in production apps with `msal-browser@2.x.x`. We are actively working on this support and trying to get it out ASAP. Sorry for the delay!

**Comment by s2ramana** [comment]
Thanks for the update! Is there a time-line for this? This will help us to plan our migration from msal 1.x to 2.x.

**Comment by jmckennon** [comment]
We don't have a timeline, but it is currently our #1 priority. We will make an announcement and change the docs when the feature is ready.

**Comment by jmckennon** [comment]
Going to close this as I'm assuming the question is here is answered and we are tracking this internally--please open a new issue if you have further questions. Thanks!
