### ISSUE TITLE
Keep me signed in prompt not appearing

### ISSUE THREAD

**Issue by sudhirmadaan** [AzureAD/microsoft-authentication-library-for-js#2346]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `@azure/msal-browser@2.1.0`

## Framework
React/Typescript using this sample - https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-browser-samples/TypescriptTestApp2.0 

## Description
Keep me signed in prompt doesn't appear during initial login. This is causing sign-in prompt (with error code 50058) being presented to users on subsequent visits.

## Error Message
Error code 50058

## Expected behavior
Keep me signed in window should appear on initial login.

## Browsers/Environment
- Chrome
- Safari

**Comment by jmckennon** [comment]
This feature isn't controlled by the `msal` library, you can find docs for it [here](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/keep-me-signed-in).

**Comment by sudhirmadaan** [comment]
Thanks! Would look into it
