### ISSUE TITLE
Optional Redirect URI in documentation

### ISSUE THREAD

**Issue by ForellenDompteur** [AzureAD/microsoft-authentication-library-for-js#2347]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Documentation location
- [ ] docs.microsoft.com
- [ ] MSAL.js Github Wiki
- [X] README file
- [ ] Other (please fill in)
- [ ] Documentation does not exist

## Description
Hi, on [page](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/initialization.md) it is stated that the redirectURI is optional. By not providing it in the configuration, the authorization code is directly send back to the application.
However, when I remove the redirect uri in the azure project and leave out the field in the client, I get the error message "No reply address is registered for the application."
Is the authorization code flow with pkce even possible without providing a redirect uri? All I want is the authorization code directly back to the client after the user successfully logs in.
Thank you

**Comment by jmckennon** [comment]
You don't have to provide a `redirectUri` in the msal configuration (it defaults to the current page), but it still always needs to be registered in the portal `msal` to function properly.

**Comment by ForellenDompteur** [comment]
@jmckennon thank you. The problem with this approach is that I get an error message after a successful login, saying that the provided redirect uri is not equal to the one provided in the azure project.

**Comment by jmckennon** [comment]
The `redirectUri` in your app will always need to match one of the `redirectUri` listed in the portal whether it's provided in the app or not. It's optional to provide it in the app configuration only because it defaults to the current window. If that window (for example, http://localhost:30662) is not listed in the portal as a valid `redirectUri`, you will get an error like this one.
