### ISSUE TITLE
Set token expiration time

### ISSUE THREAD

**Issue by fengzhihenxs** [AzureAD/microsoft-authentication-library-for-js#2350]
## Library 
- [x] `@azure/msal-browser@2.1.0` 

## Description
 

Examples: 
 How long does the default token expire?
How to set the token expiration time?

**Comment by jmckennon** [comment]
The default expiration for a refresh token is 24 hours and 1 hour for refresh tokens and access tokens, respectively. We have more information on [configurable token expiry times](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes#configurable-token-lifetime-properties) in our documentation.
