### ISSUE TITLE
Login into @msal/angular angular application using id_token generated by custom policy

### ISSUE THREAD

**Issue by rajithakolan** [AzureAD/microsoft-authentication-library-for-js#2351]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.3.2` or `@azure/msal@1.1.1`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Browsers/Environment
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by rajithakolan** [comment]
Is there is any option to login the user into angular application using a existing token.  

http://localhost:4200/#id_token=eyJ0eXAiOiJKV1...

**Comment by jmckennon** [comment]
@rajithakolan Please fill out the issue template with your configs, versions, and `msal` usage.

Where are you getting your `id_token` from?

**Comment by rajithakolan** [comment]
Using Identity Experience Framework custom policy 'B2C_1A_SignUpSignInSaml' policy we are generating a token and redirecting the user to angular application.
![image](https://user-images.githubusercontent.com/57349756/94585144-352a0780-029d-11eb-9c75-cea5cdb192b7.png)

So at angular end, how to create msal instance for that token and how to login the user automatically. 

Basically we are using the above flow to achive the SSO in Azure AD B2C between multiple applications(clients).

**Comment by jmckennon** [comment]
> So at angular end, how to create msal instance for that token and how to login the user automatically.
>
>Basically we are using the above flow to achive the SSO in Azure AD B2C between multiple applications(clients).

Instead of passing an `id_token` to `msal` (`msal` does not support bootstrapping an `id_token` requested by another app), can you pass the user's email and use it in the `loginHint` field to call `ssoSilent`? This would achieve the SSO you're looking for.
