### ISSUE TITLE
Logging configuration not working

### ISSUE THREAD

**Issue by vinceve** [AzureAD/microsoft-authentication-library-for-js#2352]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.2.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Logging is not triggered with configuration.

## Error Message
Logging is not triggered with configuration object PublicClientApplication

## Security
- [ ] Is this issue security related? no

## Regression
- [ ] Did this behavior work before? yes (msal version, it just worked)
Version:

## MSAL Configuration

```js
const AZURE_CONFIG: Configuration = {
  auth: {
    authority,
    clientId: AZURE_ID,
  },
  cache: {
    cacheLocation: 'localStorage',
  },
  system: {
    loggerOptions: {
      loggerCallback: () => {
        console.log('triggered');
      },
      piiLoggingEnabled: false,
      logLevel: LogLevel.Verbose,
    },
  },
};

const azureProvider = new PublicClientApplication(AZURE_CONFIG);
```

## Expected behavior
Log all stuff happening in Verbose mode. In the case of the configuration above, it should log 'triggered'.

## Browsers/Environment
- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari
- [x] IE
- [x] Other (Please add browser name here)

**Comment by jmckennon** [comment]
I was not able to reproduce the logger not working, at least not with our [sample implementation](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/da2fda9c751b9d121ae16ea8a80e295162668cea/samples/msal-browser-samples/VanillaJSTestApp2.0/app/default/authConfig.js#L13). `msal-browser` doesn't actually have that much logging in general, so it may just not be hitting a path with logging. Can you try to confirm this with a bit more testing and/or using our example? 

Is the expectation that you would expect a lot of logging even on a regular base case? I want to try to understand the problem/thoughts so we can take that feedback into account.

**Comment by vinceve** [comment]
@jmckennon thank you for your answer. I am upgrading from the "regular" msal library to the new msal-browser package. When I turned on logging in the "regular" MSAL library I could see a lot of extra information. For example: Do I hit the cache for refreshing my token. (Which in fact is my root problem now :-) ).

**Comment by vinceve** [comment]
Yes indeed. I see my browser hitting the token endpoint each time. So my guess is that the token is not cached. (I have a polling mechanism so I am hitting the endpoint on each poll)

**Comment by jmckennon** [comment]
Can you provide your `msal` usage? We would not expect to always bypass the cache and go to the network.

**Comment by vinceve** [comment]
Hi Jake,

Sorry it took a while to respond:

configuration:
```
// @flow
import { PublicClientApplication, Configuration } from '@azure/msal-browser';

export const AZURE_ID = process.env.REACT_APP_AZURE_AD_APP_ID || '';
export const AZURE_TENANT = process.env.REACT_APP_AZURE_AD_TENANT_ID || '';
export const AZURE_REDIRECT_URI = 'http://localhost:3000';

const authority = `https://login.microsoftonline.com/${AZURE_TENANT}`;

const AZURE_CONFIG: Configuration = {
  auth: {
    authority,
    clientId: AZURE_ID,
  },
  cache: {
    cacheLocation: 'localStorage',
  },
};

export const INTERACTIVE_CALL_LOGIN = {
  scopes: [],
  redirectUri: AZURE_REDIRECT_URI,
};

export const azureProvider = new PublicClientApplication(AZURE_CONFIG);
```

When I successfully have authenticated I configure following Axios interceptor:
```
const account = azureProvider.getAllAccounts()[0];

// Register a callback to check if the token is still valid and refresh it with the refresh token silently.
      appApi.interceptors.request.use(async (config) => {
        try {
          const response = await azureProvider.acquireTokenByRefreshToken({ account, ...INTERACTIVE_CALL_LOGIN });
          appApi.defaults.headers.Authorization = `Bearer ${response.idToken}`;
          localStorage.setItem('my.id_token', response.idToken);
        } catch (e) {
          // login is required to proceed, we cannot refresh silently anymore.
          // Tokens are all expired.
          localStorage.clear();
          window.location.href = '/';
        }

        return config;
      });
```

**Comment by tnorling** [comment]
@vinceve Looks like you're calling `acquireTokenByRefreshToken`. This function always makes a network call and is intended to only be used internally by msal. You should not call this directly as it is subject to change or be removed at any time. You should use `acquireTokenSilent` instead which will first do a cache lookup, then attempt to refresh if the token is expired or can't be found in cache.
