### ISSUE TITLE
Using refresh tokens in @azure/msal-browser

### ISSUE THREAD

**Issue by amng9560** [AzureAD/microsoft-authentication-library-for-js#2353]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.1.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Hello,
I was wondering how this library handles the refresh token in Javascript/Reast js. Does the library handle it behind the scenes and is this apparent in the sample code or is there a separate function that should be created to use the refresh token? I have read outside of the docs that the `ssoSilent` and the `aquireSilentRedirect` functions are supposed to be used to use the refresh token. 

I've been looking through the samples and noticed the `forceRefresh` property. I was wondering if this helps to get new tokens for accessing APIs.

I'm still very new to authentication and just wanted to get some concepts down. If I could get some direction on this, that would be great. Thank you so much and this library has been a huge help in my development. Wonderful job!

Examples: 
> "How do I use MSAL with Vue.js"
> "How do I SSO between tabs?"
> "How do I use MSAL to protect my custom Web API?"
> "How can my app support multiple AAD tenants?"
> "When will my scenario be supported?"
> "When will this framework be supported"

**Comment by fengzhihenxs** [comment]
I also have this requirement. I am using angular9. I am thinking that if the token expires, should I call the method to refresh the token?

**Comment by jmckennon** [comment]
@amng9560 You can read about properties of refresh tokens in the library and how they're handled [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/token-lifetimes.md#token-renewal). The `forceRefresh` flag bypasses a cache lookup for any tokens and goes directly to the network. You can use this to force a token refresh, but it will happen as needed if it's unused.

@fengzhihenxs There are no refresh tokens in the current iteration of our `msal-angular` library, as it is based on version 1 of `msal` and uses the implicit flow. We are currently working on supporting version 2 (auth code flow + ability to use refresh tokens) for `msal-angular`.

**Comment by amng9560** [comment]
@jmckennon Thank you for explaining the `forceRefresh` flag, giving me the documentation, and your fast response. I have read the documentation and I'm still a little confused as to how to use the refresh token.

I have the code that uses the `aquireTokenSilent` method but it still doesn't work, and I must refresh the page a couple of times before it gets a token. 

`async getTokenRedirect(request, account) {
    let requestAccount = account;
    if (account == null) {
      const accounts = await super.getAllAccounts();
      if (accounts && accounts.length === 1) {
        requestAccount = super.getAccountByUsername(username)
      }
    }
    request = {...request, account: requestAccount};

    return super.acquireTokenSilent(request).catch((error) => {
      if (error instanceof msal.InteractionRequiredAuthError) {
        console.warn("silent token acquisition fails. acquiring token using redirect");
        if (this.loginType === LoginType.LoginRedirect) {
          return super.acquireTokenRedirect(request);
        } 
        else {
          return super.acquireTokenPopup(request);
        }
      }
      throw error;
    });
  }`

**Comment by jmckennon** [comment]
@amng9560 Can you provide any errors/logs you're seeing and also your `msal` config?

**Comment by amng9560** [comment]
@jmckennon Unfortunately I don't have any logs. The only one that I usually get is the console.warn message that I wrote in the `getTokenRedirect` function that I showed you above. I have to refresh the page multiple times and sometimes it would work, otherwise I'd need to clear my localStorage and cookies to get a new token. 

Sorry for asking so many questions and not being able to provide more information.

```
export const config = {
  auth: {
    authority: `${process.env.REACT_APP_MICROSOFT_LOGIN}/${process.env.REACT_APP_TENANT_ID}`,
    clientId: process.env.REACT_APP_CLIENT_ID,
    navigateToLoginRequestUrl: false,
    redirectUri: process.env.REACT_APP_REDIRECT_URI,
  },
  cache: {
    cacheLocation: process.env.REACT_APP_CACHE_LOCATION,
    storeAuthStateInCookie: false,
  },
};
```

**Comment by amng9560** [comment]
@jmckennon I finally got the errors and looked at them. This is the error I get in the network tab `{"error":"invalid_grant","error_description":"AADSTS700081: The refresh token has expired due to maximum lifetime. The token was issued on 2020-10-05T12:48:43.5425484+00:00 and the maximum allowed lifetime for this application is 1.00:00:00."}`

Then in the console I got the errors: 
![refresh_error](https://user-images.githubusercontent.com/54042143/95255452-9e020a00-07de-11eb-9e4e-b3de50caf010.png)

Currently, I'm using the forceRefresh tag and I still get these errors. So, I'm a bit confused about how to use the refresh tokens and get a new access token without refreshing multiple times or clearing my local storage.

**Comment by amng9560** [comment]
Hi, I'm still lost as to what to do about the refresh token because I am using the aquireTokenSilent method. I'm using react so to make the auth work, I'm using higher-order components and the auth component wraps the app component. I still can't figure out how to use the refresh token correctly. Can I please get a little more direction on how to use the refresh token? I get those errors and I have to refresh at least 6-8 times to potentially get a new refresh token. Is this a problem with the state? How can I fix this problem?
