### ISSUE TITLE
CommonJS or AMD dependencies warning in Angular 10

### ISSUE THREAD

**Issue by uberchris2** [AzureAD/microsoft-authentication-library-for-js#2354]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.x.x` or `@azure/msal@1.4.0`
- [x] `@azure/msal-angular@1.1.1`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework

Angular 10

## Description

Angular 10 provides a build warning. This seems to stem from the [use of minimatch](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/2029).

This is non-consequential, but would be nice to clean up.

## Error Message

> WARNING in C:\...\node_modules\@azure\msal-angular\__ivy_ngcc__\fesm2015\azure-msal-angular.js depends on 'minimatch'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

>WARNING in C:\...\node_modules\minimatch\minimatch.js depends on 'path'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

>WARNING in C:\...\node_modules\minimatch\minimatch.js depends on 'brace-expansion'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

## Security
- [ ] Is this issue security related?

## Regression
- [x] Did this behavior work before? 
Version:
msal.angular 1.0.0
## MSAL Configuration

```js
// not relevant
```

## Reproduction steps
```js
// not relevant
```

## Browsers/Environment
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by willyt150** [comment]
any news on this? we're just working on updating our npm packages and running into this same issue

**Comment by jasonnutter** [comment]
We'll be addressing this in MSAL Angular v2 (preview version coming soon!).

**Comment by jasonnutter** [comment]
Minimatch has been replaced in the latest alpha of MSAL Angular v2. Closing.
