### ISSUE TITLE
error: "invalid_instance"

### ISSUE THREAD

**Issue by zmsoft** [AzureAD/microsoft-authentication-library-for-js#2357]
## Library
"@azure/msal-angular": "^1.1.1"

## Description
I clone the example project and then replace the configuration file in app-config.json with my own.
After compiling successfully, run the project. When I click the login button, the console prompts error: error: "invalid_instance".

## Error Message
{"error":"invalid_instance","error_description":"AADSTS50049: Unknown or invalid instance.\r\nTrace ID: 7798ecd4-fabc-4eda-b5a4-693d0cd96a01\r\nCorrelation ID: 0250a443-5fe4-4741-beb0-4bce9754b2b6\r\nTimestamp: 2020-09-30 03:50:55Z","error_codes":[50049],"timestamp":"2020-09-30 03:50:55Z","trace_id":"7798ecd4-fabc-4eda-b5a4-693d0cd96a01","correlation_id":"0250a443-5fe4-4741-beb0-4bce9754b2b6","error_uri":"https://login.microsoftonline.com/error?code=50049"}

## Regression
NO

## MSAL Configuration
```javascript
{
"auth": {
"clientId": "92f23179-1bc8-41b0-a4af-d935b25c2e2b",
"authority": "https://smarthomedev.b2clogin.cn/smarthomedev.partner.onmschina.cn/B2C_1_signupsignin1/",
"validateAuthority": true,
"redirectUri": "http://localhost:4200",
"postLogoutRedirectUri": "http://localhost:4200",
"navigateToLoginRequestUrl": true
},
"cache": {
"cacheLocation": "localStorage"
},
"scopes": {
"loginRequest": ["openid", "profile", "https://smarthomedev.partner.onmschina.cn/smarthome/user_impersonation"]
},
"resources": {
"todoListApi": {
"resourceUri": "http://localhost:15838/api",
"resourceScope": "https://smarthomedev.partner.onmschina.cn/smarthome/user_impersonation"
}
}
}
```
## Reproduction steps
Same as the sample code

## Browsers/Environment
Chrome

**Comment by jmckennon** [comment]
Can you try either setting `validateAuthority: false` or to keep that field as true and to provide your URI in `knownAuthorities`?
