### ISSUE TITLE
Loading flag after redirect to App side and before handleRedirectPromise()

### ISSUE THREAD

**Issue by Tzvetelin88** [AzureAD/microsoft-authentication-library-for-js#2358]
#2300  Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.x.x`

## Description
Hello is there a flag which is set on MSAL after redirect back to Application side and before handleRedirectPromise() ?
Because handleRedirectPromise() need few seconds to get the response users can still see Login page on App side and after handleRedirectPromise() response it is login the user.

I checked a lot of examples with React and MSAL (also Vanilla JS) and all of the have this issue :) 

So basically the steps:
1. User clicks Login on App side.
2. User is redirected to MS page for Pass/MFA
3. User is redirected to App side.
4. User is seeing Login page again
5. After few seconds needed for handleRedirectPromise() to get response.
6. User is seeing Welcome page.

It is very difficult to control that on App side, because we are doing Redirecting and everything on App side like Store, Redux, Local Storage will be lost. So, I was thinking is there mechanism to control that, for example parameter in MSAL which is set after redirection from MS to App side?

Thanks!

**Comment by jmckennon** [comment]
>User is redirected to App side.
>User is seeing Login page again

This is controlled by the `redirectUri`. We generally recommend setting this to a blank html page, or a page with no auth/low functionality, but you can redirect to whichever page you'd like (so the user doesn't have to see the login screen again).

We don't currently expose a flag that shows if the redirect has been completed or not. What's your use case where this would be useful?

**Comment by Tzvetelin88** [comment]
Well redirect to blank page on App side before we get response is some kind of workaround. 

> What's your use case where this would be useful?

handleRedirectPromise() is initiated after the redirect on App side, but it takes few seconds to get response from it.
So, everything inside handleRedirectPromise() will took affect after that time, so we can't use that one to control App side Loading etc.

Also you can't do anything on App side to handle this, because you have been redirected from MS page to App side, so everything in Store, Redux, Saga, Local Storage will be lost, so again setting state or store won't help.

To be able to handle this time frame of few seconds (after you have been redirected from MS page to App side and Before handleRedirectPromise() response) and show Loading message or spinning button, it will be a good idea to have some flag, that we have been redirected and currently awaiting handleRedirectPromise().

This flag could have information like redirectedFromMS: true, or some method which is bind to handleRedirectPromise() which we can initiated before handleRedirectPromise().

**Comment by Tzvetelin88** [comment]
Actually Local Storage is preserved after refresh, and I used Persist Reducer to set Flag in the store. 
When user clicks SignIn, flag is set to true and then redirects to MS page. 

On return back, as we have flag true I show loading and after  handleRedirectPromise return a promise I redirect the user to Welcome page.
