### ISSUE TITLE
Error AADB2C90055 on acquireTokenSilent and fails to renew token

### ISSUE THREAD

**Issue by imranmomin** [AzureAD/microsoft-authentication-library-for-js#236]
I'm getting a below error on `acquireTokenSilent` method

```
id_token AADB2C90055: The scope 'openid profile' provided in request must specify a resource, such as 'https://example.com/calendar.read'.
Correlation ID: 37515e59-c83e-4468-a88b-6df01e7ecc8f
Timestamp: 2018-01-29 19:30:49Z
invalid_request
```
Code snippet 
```typescript
acquireToken(): Promise<string | void> {
	return this.context.acquireTokenSilent(this.scopes, null, this.principal)
		.then((token: string) => {
			return token;
		},
		(error: string) => {
			console.error(error);  // get timeout error:null
			this.context.acquireTokenRedirect(this.scopes);
		});
}
```
I call this method before all the API calls, so I can assure that the token is valid. But when the token expires `acquireTokenSilent`, Azure AD returns back with **AADB2C90055**

On errror call  acquireTokenRedirect and returns back with error 

> Tue, 30 Jan 2018 17:53:16 GMT:0.1.3-Info State status:true; Request type:renewToken
> Tue, 30 Jan 2018 17:53:16 GMT:0.1.3-Info Error :invalid_request; Error description:AADB2C90055: The scope 'openid profile' provided in request must specify a resource, such as 'https://example.com/calendar.read'.
> Correlation ID: 7eb608c6-1433-48e2-95ed-9dc0c7d437dd
> Timestamp: 2018-01-30 17:52:56Z

Note: I'm using **Azure AD B2C** and the scopes is set to `openid`

**Comment by rohitnarula7176** [comment]
@imranmomin Please refer to the B2C sample under the devApps folder on instructions on how to create a B2C app using Msal.

**Comment by imranmomin** [comment]
@rohitnarula7176  - if you are referring to this sample https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/devApps/VanillaJSTestApp-b2c

It also fails on the sample. I only changed the config. If you want to try at your end, I can create a gist

**Comment by rohitnarula7176** [comment]
@imranmomin 'openid profile' scope doesn't correspond to any resource, So AAD rejects your request. You have to add the scope for your resource in scopes, for example, 'https://example.com/calendar.read'.

**Comment by imranmomin** [comment]
@rohitnarula7176  - Thank you. I had to go create a custom scope, which I was not knowing. After which all worked perfectly.
