### ISSUE TITLE
Token issue in tenant with MFA and Windows integrated authentication(only username and password)

### ISSUE THREAD

**Issue by MaheshakaMudli** [AzureAD/microsoft-authentication-library-for-js#2362]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.4.0`

## Framework
Html and Javascript

## Description
We are using MSAL for generating token to get graph data. On our tenant we have enabled MFA authentication for all the users. Recently we have activated one policy in which if the user signs from the trusted domain, it would ask for the MFA authentication code also there is password-less settings enabled on our tenant. 
Using MSAL when we login only using **username and password in trusted systems**, the authentication process completes but the graph token is not generated and we get below error. 
But when the user completes the login with **password less option with MFA code** the authentication completes successfully and the token is generated. This issue occurs only in **Teams Desktop Client**
Is there any way we can handle the same by code to handle the authentication process when user selects the username and password option while login.

## Error Message
<img width="308" alt="InteractionError" src="https://user-images.githubusercontent.com/23700986/94796170-08d8cd00-03fc-11eb-9fd9-6703ed16055a.png">

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Browsers/Environment
Teams Desktop Client

**Comment by jmckennon** [comment]
We will need more information to assist with debugging, could you please fill out the provided issue template with your msal usage, verisons, and configuration?
