### ISSUE TITLE
Wrong Issuer in the Token Response causing Invalid JWT.

### ISSUE THREAD

**Issue by Tzvetelin88** [AzureAD/microsoft-authentication-library-for-js#2363]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [X] `@azure/msal-browser@2.2.0`

## Framework
React 16.12.0

## Description
Migrated from MSAL 1.x to MSAL 2.x.
Authenticating against API Mamangent in Azure failed with Invalid JWT token.

Token versions:
https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens
v1 using https://sts.windows.net/  
v2 using https://login.microsoftonline.com

## Error Message
Invalid JWT Token.
Wrong Issuer: 
Why I get from the token old issuer   https://sts.windows.net/ and not   https://login.microsoftonline.com/ which is used by MSAL?

## MSAL Configuration

```js
export const msalConfig = {
    auth: {
        clientId: "<id>",
        authority: "https://login.microsoftonline.com/<id>",
        redirectUri: 'http://localhost:3000/',
    },
    cache: {
        cacheLocation: "sessionStorage", // This configures where your cache will be stored
        storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
    },
};

export const apiConfig = {
    // Enter the API scopes as declared in the app registration 'Expose an Api' blade in the form of 'api://{client_id}/.default'
    resourceScope: "api://<Application (client) ID>/<Scope name>",
}
```

## Reproduction steps
```js
I'm using standart code example from MSAL 2.x

export const msalApp = new PublicClientApplication(msalConfig);
let username = '';

....

export const signIn = async () => {
    return msalApp.loginRedirect(loginRequest);
}

.....
```

After handleRedirectPromise() the Token response is:

{
...
  "iss": "https://sts.windows.net/<id>/",
  "ver": "1.0"
....
}

## Expected behavior
To get right Token and get valid JWT token.

## Browsers/Environment
- [X] Chrome

**Comment by jmckennon** [comment]
Is your app originally created in the legacy app registration? You may need to recreate your app in the new app registration or set your `accessTokenAcceptedVersion` to 2 in the legacy app reg. This can be seen [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-app-manifest#accesstokenacceptedversion-attribute).

**Comment by Tzvetelin88** [comment]
Sorry for the late response. Yes,  I've created a new App Registration, but after I have looked into manifest, I saw accessTokenAcceptedVersion was null, which by default goes to v.1 Tokens and not v.2 Tokens. After I've set it to 2 it worked. Thanks so much
