### ISSUE TITLE
Msal-angular 2.0

### ISSUE THREAD

**Issue by andmagom** [AzureAD/microsoft-authentication-library-for-js#2365]
## Library
- [x] `@azure/msal-angular@1.x.x`

## Description
Hello AzureAD Team !

We use msal-angular 1.x in a lot of projects, we want to use authorization code flow but it is only enabled in msal 2.0. We are wondering if you will include in your backlog a new version of msal-angular in order to use this flow.

We know there is an example for use msal-browser in Angular 10, However we want to explore an easy way to move to msal 2.0 into our projects.

Thanks,
Have a nice day

**Comment by jasonnutter** [comment]
@andmagom Yes, we will update our roadmap soon to reflect our plan for MSAL Angular v2. We expect to have preview versions available relatively soon.

**Comment by andmagom** [comment]
**Awesome** @jasonnutter !!

 We are going to be waiting for the update !

Thanks
