### ISSUE TITLE
Always asks for MFA

### ISSUE THREAD

**Issue by Tzvetelin88** [AzureAD/microsoft-authentication-library-for-js#2366]
## Library
- [X] `@azure/msal-browser@2.2.0`

## Framework
React 16.12.0

## Description
Login to Application using:
```
return msalApp.loginRedirect(loginRequest);
```
always asking for MFA, no matter if I'm accessing from Internal or External network.

## Error Message
No

## Security
- [ ] Is this issue security related?

## Regression
- [X] Did this behavior work before? 
Version: MSAL 1.x this wasn't a issue. It was asking only when accessing from external network.

## MSAL Configuration

```js
export const msalConfig = {
    auth: {
        clientId: "<id>",
        authority: "https://login.microsoftonline.com/<id>",
        // redirectUri: 'http://localhost:3000/',
    },
    cache: {
        cacheLocation: "sessionStorage", // This configures where your cache will be stored
        storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
    }
};

const GRAPH_SCOPES = {
    OPENID: "openid",
    PROFILE: "profile",
    USER_READ: "User.Read",
    APP: "api://<id>/<name>",
};

export const GRAPH_REQUESTS = {
    LOGIN: {
        scopes: [
            GRAPH_SCOPES.APP,
            GRAPH_SCOPES.USER_READ,
            GRAPH_SCOPES.OPENID,
            GRAPH_SCOPES.PROFILE
        ]
    },
    GROUP: {
        scopes: [GRAPH_SCOPES.USER_READ]
    }
};

// Coordinates and required scopes for your web api
export const apiConfig = {
    resourceScope: GRAPH_SCOPES.APP
}

export const loginRequest = {
    scopes: GRAPH_REQUESTS.GROUP.scopes,
    // forceRefresh: false // Set this to "true" to skip a cached token and go to the server to get a new token
};

// Add here scopes for access token to be used at the API endpoints.
export const tokenRequest = {
    scopes: GRAPH_REQUESTS.LOGIN.scopes,
    // scopes: [apiConfig.resourceScope]
}
```

## Reproduction steps
```js
export const signIn = async () => {

    return msalApp.loginRedirect(loginRequest);
}
```

## Browsers/Environment
- [X] Chrome
- [X] Edge

Some times on Edge it is not asking for MFA.

**Comment by jmckennon** [comment]
This is most likely an app registration problem. MFA can be required conditionally based on whichever settings are added in the portal--your new app reg most likely has it set to always require MFA. Instructions for adding/changing MFA policies can be seen on the [Microsoft docs](https://docs.microsoft.com/en-us/azure/active-directory/authentication/tutorial-enable-azure-mfa).

**Comment by Tzvetelin88** [comment]
Hey thanks so much for the hint.

Indeed it was an issue with App Registration and more specific with MFA policy which was applied to the App Registration.

For future issues of this kind here are some screenshots:

Tracking what policies were applied on the time of the authentication:
![image](https://user-images.githubusercontent.com/9692941/94936325-c1733f00-04d6-11eb-9815-193ca373aac6.png)

and current MFA policy:
![image](https://user-images.githubusercontent.com/9692941/94936430-e5cf1b80-04d6-11eb-8520-de56cc0fbda8.png)
