### ISSUE TITLE
AADSTS90130 acquireTokenSilent

### ISSUE THREAD

**Issue by johannes-z** [AzureAD/microsoft-authentication-library-for-js#237]
I've tried registering an app through the azure portal (https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/RegisteredApps), and get the following error message when using `acquireTokenSilent`:

```
AADSTS90130: Application '<application_id>' (Test) is not supported over the /common or /consumers endpoints. Please use the /organizations or tenant-specific endpoint.
Trace ID: <Trace ID>
Correlation ID: <Correlation ID>
Timestamp: 2018-01-30 11:31:01Z: invalid_request
```

**Comment by rohitnarula7176** [comment]
@johannes-z Is the tenant/app B2C? B2C doesn't support /common endpoint, you must provide your tenant name or tenant id. For example, you should use 'https://login.microsoftonline.com/tfp/<your_tenant_id_or_tenant_name>/<your_policy_name>' as the 'authority' in your msal.js constructor. Tenant name is something like 'fabrikamb2c.onmicrosoft.com', tenant id is something like 'xxx....xx', policy name is something like 'b2c_1_xxx'.
