### ISSUE TITLE
Receiving error - Seamless single sign on failed for the user

### ISSUE THREAD

**Issue by calvinnelms** [AzureAD/microsoft-authentication-library-for-js#2372]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.1.1`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework
Angular 10.0.2

## Description
When a user logs into the angular application from Safari via either a mac, iPad, or iPhone, they receive an error listed below.
The app loads correctly on Chromium Edge and Chrome when loaded on that same mac.  This seems to be related to the Safari web browser.

## Error Message
Seamless single sign on failed for the user. This can happen if the user is unable to access on premises AD or intranet zone is not configured correctly.
In Safari Developer Tools, I receive a 401 (Unauthorized) to https://autologon.microsoftazuread-sso.com/winauth/sso...

## Security
- [x] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version: Unsure, this is my first attempt at msal and have only tested in Angular 10.0.2

## MSAL Configuration
auth: {
      clientId: environment.msalConfig.clientId,
      authority: "https://login.microsoftonline.com/" + environment.msalConfig.tenant + "/",
      validateAuthority: true,
      redirectUri: environment.msalConfig.redirectUri,// "http://localhost:4200/",
      postLogoutRedirectUri: environment.msalConfig.postLogoutRedirectUri, // "http://localhost:4200/",
      navigateToLoginRequestUrl: true,
    },
    cache: {
      cacheLocation: "localStorage",
      storeAuthStateInCookie: false, // set to true for IE 11
    },

## Reproduction steps
Load angular app on Safari browser in iOS, iPadOS, or MacOS

## Expected behavior
App should authenticate correctly

## Browsers/Environment
- [x] Chrome
- [ ] Firefox
- [x] Edge
- [x] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jmckennon** [comment]
@calvinnelms Does this error still occur with ITP disabled?

**Comment by calvinnelms** [comment]
@jmckennon Yes actually, if I uncheck "Prevent cross-site tracking" on both mac os and ios/ipados safari, the site works.

Are there any work arounds if I leave this setting enabled?  Or is this one of the downsides of the msal library?

**Comment by ryan-ost** [comment]
I am also experiencing this issue on iOS and MacOS in safari, but not chrome. The workaround works for me as well.

**Comment by sameerag** [comment]
@calvinnelms @ryan-ost Is calling `acquireTokenPopup` or `acquireTokenRedirect` working in this case?

**Comment by ryan-ost** [comment]
It looks like we were not calling acquireTokenRedirect after acquireTokenSilent failed. After adding this, I am able to log in in safari.

**Comment by calvinnelms** [comment]
@ryan-ost Can you post a code sample of the "call acquireTokenRedirect after acquireTokenSilent failed" fix?

**Comment by ryan-ost** [comment]
Sure, it's similar to the implementation in the sample app here on line 72: https://github.com/Azure-Samples/active-directory-javascript-graphapi-v2/blob/quickstart/JavaScriptSPA/authRedirect.js

```
export const acquireTokenSilent = () => {
  const authority = getItem(lastUsedAuthority)
  if (!msalApp) {
    msalApp = initUserAgent(authority)
    clearItem(lastUsedAuthority)
  }
  const request = { scopes: B2C_SCOPES }
  return msalApp.acquireTokenSilent(request).then((response) => {
    return response
  })
    .catch(() => {
      return msalApp.acquireTokenRedirect(request)
    })
}
```

I am sure there is a better way to do this, but I am hoping to upgrade to MSAL 2.0 once this is resolved: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2381

**Comment by calvinnelms** [comment]
Thanks @ryan-ost , I'll give this a try!

**Comment by calvinnelms** [comment]
@ryan-ost it worked, thanks for the code snippet and reference!

Calling acquireTokenRedirect on a failed acquiredTokenSilent works with the "Prevent Cross-Site Tracking" enabled on the iPad.
