### ISSUE TITLE
[msal-browser] rogue console.log() in BrowserCrypto.ts

### ISSUE THREAD

**Issue by derisen** [AzureAD/microsoft-authentication-library-for-js#2373]
## Library
- [x] `@azure/msal-browser@2.3.0`

## Framework
N/A

## Description
A `console.log()` statement seems to be forgotten in the latest release.

This appears in: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/80962a0f7fc9064c2fbe98387b10cb2e9a2c86e6/lib/msal-browser/src/crypto/BrowserCrypto.ts#L140

## Error Message
N/A

## Security
- [ ] Is this issue security related?

## Regression
- [x ] Did this behavior work before? 
Version: 2.1.0

## MSAL Configuration
N/A

## Reproduction steps
N/A

## Expected behavior

Crypto method not logged to console.

## Browsers/Environment
- [x ] Chrome
- [x ] Firefox
- [x ] Edge
- [x ] Safari
- [x ] IE
- [ ] Other (Please add browser name here)

**Comment by jasonnutter** [comment]
FYI @pkanher617 

(I need to add this to the lint rules.)
