### ISSUE TITLE
Token renewal errors on page reload

### ISSUE THREAD

**Issue by LadaM** [AzureAD/microsoft-authentication-library-for-js#2378]
While running the react application which is using Azure AD authentication locally the following 3 msal errors are happening every time application reloads:
1. [ERROR] ClientAuthError: Token renewal operation failed due to timeout.
2. [ERROR] ClientAuthError: Token renewal operation failed due to timeout.
3. [ERROR] ClientAuthError: Login_In_Progress: Error during login call - login is already in progress.
The errors happen every time the application reloads in the same order. There is a significant rendering delay (about 2s).
### Environment
``` 
"react": "16.12.0",
"react-aad-msal": "^2.3.5",
"msal": "^1.3.3",
```
AuthenticationProvider settings:
```
  cache: {
    cacheLocation: "sessionStorage",
    storeAuthStateInCookie: false
  },
...
const options = {
  loginType: LoginType.Popup,
  tokenRefreshUri: window.location.origin +'/auth.html'
}
```
Using AuthenticationProvider:
```
...  
<AzureAD provider={authProvider} forceLogin={true}>
          {({login, logout, authenticationState, error, accountInfo}: IAzureADFunctionProps) => {
            // sessionStorage.clear();
            switch (authenticationState) {
              case AuthenticationState.Authenticated:
                return (
                  <p>
                    <span>Welcome, {accountInfo.account.name}!</span>
                    <button onClick={logout}>Logout</button>
                  </p>
                );
              case AuthenticationState.Unauthenticated:
                return (
                  <div>
                    {error && <p><span>An error occurred during authentication, please try again!</span></p>}
                    <p>
                      <span>Hey stranger, you look new!</span>
                      <button onClick={login}>Login</button>
                    </p>
                  </div>
                );
              case AuthenticationState.InProgress:
                return (<p>Authenticating...</p>);
            }
          }
          }
        </AzureAD>
```
### Error logs from msal
react_devtools_backend.js:2273 [ERROR] ClientAuthError: Token renewal operation failed due to timeout.
overrideMethod @ react_devtools_backend.js:2273
ERROR @ Logger.js:69
_callee4$ @ MsalAuthProvider.js:434
tryCatch @ runtime.js:45
invoke @ runtime.js:271
prototype.<computed> @ runtime.js:97
asyncGeneratorStep @ MsalAuthProvider.js:26
_next @ MsalAuthProvider.js:28
(anonymous) @ MsalAuthProvider.js:28
(anonymous) @ MsalAuthProvider.js:28
(anonymous) @ MsalAuthProvider.js:451
_callee3$ @ MsalAuthProvider.js:278
tryCatch @ runtime.js:45
invoke @ runtime.js:271
prototype.<computed> @ runtime.js:97
asyncGeneratorStep @ MsalAuthProvider.js:26
_throw @ MsalAuthProvider.js:28
Promise.then (async)
asyncGeneratorStep @ MsalAuthProvider.js:26
_next @ MsalAuthProvider.js:28
(anonymous) @ MsalAuthProvider.js:28
(anonymous) @ MsalAuthProvider.js:28
(anonymous) @ MsalAuthProvider.js:293
_callee6$ @ MsalAuthProvider.js:509
tryCatch @ runtime.js:45
invoke @ runtime.js:271
prototype.<computed> @ runtime.js:97
asyncGeneratorStep @ MsalAuthProvider.js:26
_next @ MsalAuthProvider.js:28
(anonymous) @ MsalAuthProvider.js:28
(anonymous) @ MsalAuthProvider.js:28
_callee5$ @ MsalAuthProvider.js:471
tryCatch @ runtime.js:45
invoke @ runtime.js:271
prototype.<computed> @ runtime.js:97
asyncGeneratorStep @ MsalAuthProvider.js:26
_next @ MsalAuthProvider.js:28
(anonymous) @ MsalAuthProvider.js:28
(anonymous) @ MsalAuthProvider.js:28
MsalAuthProvider @ MsalAuthProvider.js:626
./app/authentication/AuthenticationProvider.ts @ AuthenticationProvider.ts:62
__webpack_require__ @ bootstrap:79
./main.tsx @ main.tsx:1
__webpack_require__ @ bootstrap:79
3 @ main.js:11313
__webpack_require__ @ bootstrap:79
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js:1
react_devtools_backend.js:2273 [ERROR] ClientAuthError: Token renewal operation failed due to timeout.
overrideMethod @ react_devtools_backend.js:2273
ERROR @ Logger.js:69
_callee6$ @ MsalAuthProvider.js:522
tryCatch @ runtime.js:45
invoke @ runtime.js:271
prototype.<computed> @ runtime.js:97
asyncGeneratorStep @ MsalAuthProvider.js:26
_throw @ MsalAuthProvider.js:28
Promise.then (async)
asyncGeneratorStep @ MsalAuthProvider.js:26
_next @ MsalAuthProvider.js:28
(anonymous) @ MsalAuthProvider.js:28
(anonymous) @ MsalAuthProvider.js:28
_callee5$ @ MsalAuthProvider.js:471
tryCatch @ runtime.js:45
invoke @ runtime.js:271
prototype.<computed> @ runtime.js:97
asyncGeneratorStep @ MsalAuthProvider.js:26
_next @ MsalAuthProvider.js:28
(anonymous) @ MsalAuthProvider.js:28
(anonymous) @ MsalAuthProvider.js:28
MsalAuthProvider @ MsalAuthProvider.js:626
./app/authentication/AuthenticationProvider.ts @ AuthenticationProvider.ts:62
__webpack_require__ @ bootstrap:79
./main.tsx @ main.tsx:1
__webpack_require__ @ bootstrap:79
3 @ main.js:11313
__webpack_require__ @ bootstrap:79
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js:1
react_devtools_backend.js:2273 [ERROR] ClientAuthError: Login_In_Progress: Error during login call - login is already in progress.
### Workaround
When session storage is cleared `sessionStorage.clear()` the errors aren't occurring as well as when the new window is opened.

**Comment by jmckennon** [comment]
We have some documentation on common issues that can result in timeouts in [our docs](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/docs/errors.md#token-renewal-operation-failed-due-to-timeout).

Can you try upgrading to `msal@1.4.1` to see if your issue persists? This may not work as I'm unsure if `react-aad-msal` will support our new version (we don't own that library), and you may want to [put in an issue with them](https://github.com/syncweek-react-aad/react-aad), as it may be entirely on the wrapper library.

**Comment by LadaM** [comment]
Thanks for the reply. You're right it's most probably a problem with the wrapper lib. 

I've tried to update to msal@1.4.0 and it caused endless reload cycles, so it's easy to assume that the react-aad lib isn't working well with the newer version. What worked for me is to use the msal directly. I'll post the issue on their board and close this one.
