### ISSUE TITLE
Remove the `debug` package from `msal-common`'s `dependencies`

### ISSUE THREAD

**Issue by HarryGifford** [AzureAD/microsoft-authentication-library-for-js#2380]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-common@1.5.0`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

Please remove `debug` (and `@types/debug`) from the `package.json` of `@azure/msal-common` or move it to `devDependencies`. It does not appear to be used in the package and having it as a dependency means other teams must track the package for vulnerabilities etc. If it's in `devDependencies` then this isn't an issue.

## Priority

Low. In general, extra dependencies aren't a major problem, but in this case it's extraneous, so we might as well remove it.

**Comment by DarylThayil** [comment]
@HarryGifford the debug package is added specifically to support debugging messages in the wild, not just in dev
@jasonnutter  cc
