### ISSUE TITLE
It is not clear what 'storeAuthStateInCookie' does given that my access token is still in local storage

### ISSUE THREAD

**Issue by CraigComeOnThisNameCantBeTaken** [AzureAD/microsoft-authentication-library-for-js#2382]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Documentation location
- [ ] docs.microsoft.com
- [ ] MSAL.js Github Wiki
- [ ] README file
- [ ] Other (please fill in)
- [x] Documentation does not exist

## Description
I am trying to understand what the setting storeAuthStateInCookie actually does but I can't find documentation on the subject other than 'If set, MSAL store's the auth request state required for validation of the auth flows in the browser cookies. By default this flag is set to false.', however, it is not clear to me what that means. I assume this is not a security feature, but a workaround to an IE problem. However, if that is the case it would be helpful to briefly explain what the 'auth request state' is given my id token is still in local or session storage as I am blindly following docs on it (making it boilerplate IMO).

**Comment by DarylThayil** [comment]
StoreAuthStateInCookie stores a specific set of authentication artifacts in the cookie.  Specifically `state` and `nonce`, and I believe this was to get around some interesting issues on ie11.  

The storage you choose, either local or session is where all other artifacts like token are stored

**Comment by sameerag** [comment]
@CraigComeOnThisNameCantBeTaken The documentation for IE11 is available [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Known-issues-on-IE-and-Edge-Browser) and can be navigated from our [FAQs](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/docs/FAQ.md#what-browsers-are-supported-by-msaljs) page. If the explanation there isn't clear, please let us know, we will try to add more detail.
