### ISSUE TITLE
acquireTokenSilent failing in only IE11 (embedded iframe scenario)

### ISSUE THREAD

**Issue by pmcgannon22** [AzureAD/microsoft-authentication-library-for-js#2383]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.4.1`

## Description

acquireTokenSilent issues in IE11, whereas it is working properly in all other browsers (Chrome, FF, Edge Chromium), using the exact same code path. The implementation involves an embedded, hidden iframe across a large number of domains that proxies calls inside of the frame and sends their responses to the parents. The expectation is that the parent will be an authenticated page. 

Previously, we have this pattern already working with ADAL.js and we are currently upgrading to use MSAL and are running into this issue that is blocking our upgrade. 

The main error in the logs is:

`Tue, 06 Oct 2020 20:59:57 GMT:1.4.0-Error Please call ResolveEndpointsAsync first`

You can see in the network trace that `https://login.microsoftonline.com/common//discovery/instance?api-version=1.1&authorization_endpoint=https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize` is being called properly, but there is _not_ an ensuing call to `https://login.microsoftonline.com/organizations/v2.0/.well-known/openid-configuration`, which I see happening in successful cases in other browsers.

## Error Message

**IE11 Error Logs**

```
Tue, 06 Oct 2020 20:59:57 GMT:1.4.0-Verbose AcquireTokenSilent has been called
Tue, 06 Oct 2020 20:59:57 GMT:1.4.0-Verbose Telemetry Event started: a2659e58-8da7-4921-a900-5cc0cc751f88_3e7295bd-01dc-41ba-b822-a484fa790b7e-msal.api_event
Tue, 06 Oct 2020 20:59:57 GMT:1.4.0-Verbose Account set from MSAL Cache
Tue, 06 Oct 2020 20:59:57 GMT:1.4.0-Verbose Response type: id_token token
Tue, 06 Oct 2020 20:59:57 GMT:1.4.0-Verbose Finished building server authentication request
Tue, 06 Oct 2020 20:59:57 GMT:1.4.0-Verbose Query parameters populated from existing SSO or account
Tue, 06 Oct 2020 20:59:57 GMT:1.4.0-Verbose GetCachedToken has been called
Tue, 06 Oct 2020 20:59:57 GMT:1.4.0-Verbose No tokens found
Tue, 06 Oct 2020 20:59:57 GMT:1.4.0-Verbose Getting all cached access tokens
Tue, 06 Oct 2020 20:59:57 GMT:1.4.0-Verbose No matching tokens found when filtered by clientId and account
Tue, 06 Oct 2020 20:59:57 GMT:1.4.0-Verbose No token found in cache lookup
Tue, 06 Oct 2020 20:59:57 GMT:1.4.0-Verbose No cached metadata for authority
Tue, 06 Oct 2020 20:59:57 GMT:1.4.0-Verbose Telemetry Event started: a2659e58-8da7-4921-a900-5cc0cc751f88_a8991d89-b8b1-4c14-a423-2838156807ad-msal.http_event
Tue, 06 Oct 2020 20:59:57 GMT:1.4.0-Verbose Authority has been updated with endpoint discovery response
Tue, 06 Oct 2020 20:59:57 GMT:1.4.0-Verbose Renewing access token
Tue, 06 Oct 2020 20:59:57 GMT:1.4.0-Verbose RenewToken has been called
Tue, 06 Oct 2020 20:59:57 GMT:1.4.0-Error Please call ResolveEndpointsAsync first
```

Logs for successful call in Edge Chromium 

```
Tue, 06 Oct 2020 20:47:16 GMT:1.4.0-Verbose AcquireTokenSilent has been called
Tue, 06 Oct 2020 20:47:16 GMT:1.4.0-Verbose Telemetry Event started: 99278209-e2d7-4cb8-abce-4bfd17383bf0_33ba05f6-4bb3-48c7-897a-789e9c623e8b-msal.api_event
Tue, 06 Oct 2020 20:47:16 GMT:1.4.0-Verbose Account set from MSAL Cache
Tue, 06 Oct 2020 20:47:16 GMT:1.4.0-Verbose Response type: id_token token
Tue, 06 Oct 2020 20:47:16 GMT:1.4.0-Verbose Finished building server authentication request
Tue, 06 Oct 2020 20:47:16 GMT:1.4.0-Verbose Query parameters populated from existing SSO or account
Tue, 06 Oct 2020 20:47:16 GMT:1.4.0-Verbose GetCachedToken has been called
Tue, 06 Oct 2020 20:47:16 GMT:1.4.0-Verbose No tokens found
Tue, 06 Oct 2020 20:47:16 GMT:1.4.0-Verbose Getting all cached access tokens
Tue, 06 Oct 2020 20:47:16 GMT:1.4.0-Verbose No matching tokens found when filtered by clientId and account
Tue, 06 Oct 2020 20:47:16 GMT:1.4.0-Verbose No token found in cache lookup
```

Version:

## MSAL Configuration

```typescript
        const msalConfig: MSALConfig = {
            auth: {
                clientId: "xxxxxxxx",
                authority: "https://login.microsoftonline.com/organizations"
            },
            cache: {
                cacheLocation: "sessionStorage",
                storeAuthStateInCookie: isIE
            },
            upn: config.upn
        };

        this.userAgentApplication = new UserAgentApplication(msalConfig);

        const scopes: Array<string> = [`${resource}/.default`];
        const authenticationParameters: AuthenticationParameters = {
            scopes,
            loginHint: this.upn
        };

    public acquireToken(resource: string, callback: TokenRequestCallback): void {
        this.userAgentApplication.acquireTokenSilent(authenticationParameters).then((authResponse: AuthResponse) => {
            callback(null, authResponse.accessToken);
        }).catch((error) => {
            if (error.errorMessage.indexOf("interaction_required") !== -1) {
                // This is where we have to explore the reasons, and if it is problem only in the Iframe.
                // In such situations it may be appropriate to have user help and then used loginPopup to get user login.
                // or send message to parent page about this.
            }
            callback(error.errorMessage, null);
        });
    }
```

## Browsers/Environment
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [x] IE
- [ ] Other (Please add browser name here)

**Comment by sameerag** [comment]
@pmcgannon22 Are you able to make a call to the openid-configuration [endpoint](https://login.microsoftonline.com/organizations/v2.0/.well-known/openid-configuration) independent of `msal js` in IE11?  

Also FYI: some of the IE11 issues we have seen in the past are documented [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/docs/FAQ.md#what-browsers-are-supported-by-msaljs) in case that helps.

**Comment by pmcgannon22** [comment]
@sameerag, yes, I am. I just tried sending an XHR from the console and everything seemed to work fine. I was going through that page, but wasn't able to pinpoint something that applied to my scenario. 

Some additional information. Here is what sessionStorage looks like in IE after the attempt to auth with MSAL:

```
{
   [functions]: ,
   __proto__: { },
   constructor: { },
   length: 20,
   msal.<clientId-xxxxxx>.acquireTokenAccount|NO_ACCOUNT|<resourceId-xxxxxx>: "null",
   msal.<clientId-xxxxxx>.acquireTokenAccount|NO_ACCOUNT|<resourceId-xxxxxx>: "null",
   msal.<clientId-xxxxxx>.acquireTokenAccount|NO_ACCOUNT|<resourceId-xxxxxx>: "null",
   msal.<clientId-xxxxxx>.acquireTokenAccount|NO_ACCOUNT|<resourceId-xxxxxx>: "null",
   msal.<clientId-xxxxxx>.acquireTokenAccount|NO_ACCOUNT|<resourceId-xxxxxx>: "null",
   msal.<clientId-xxxxxx>.authority|<resourceId-xxxxx>: "https://login.microsoftonline.com/organizations/",
   msal.<clientId-xxxxxx>.authority|<resourceId-xxxxx>: "https://login.microsoftonline.com/organizations/",
   msal.<clientId-xxxxxx>.authority|<resourceId-xxxxx>: "https://login.microsoftonline.com/organizations/",
   msal.<clientId-xxxxxx>.authority|<resourceId-xxxxx>: "https://login.microsoftonline.com/organizations/",
   msal.<clientId-xxxxxx>.authority|<resourceId-xxxxx>: "https://login.microsoftonline.com/organizations/",
   msal.<clientId-xxxxxx>.nonce.idtoken|<resourceId-xxxxx>: "<requestId?-xxxxx-not totally sure>",
   msal.<clientId-xxxxxx>.nonce.idtoken|<resourceId-xxxxx>: "<requestId?-xxxxx-not totally sure>",
   msal.<clientId-xxxxxx>.nonce.idtoken|<resourceId-xxxxx>: "<requestId?-xxxxx-not totally sure>",
   msal.<clientId-xxxxxx>.nonce.idtoken|<resourceId-xxxxx>: "<requestId?-xxxxx-not totally sure>",
   msal.<clientId-xxxxxx>.nonce.idtoken|<resourceId-xxxxx>: "<requestId?-xxxxx-not totally sure>",
   msal.acquireTokenAccount|NO_ACCOUNT|<resourceId-xxxx> "null",
   msal.acquireTokenAccount|NO_ACCOUNT|<resourceId-xxxx> "null",
   msal.acquireTokenAccount|NO_ACCOUNT|<resourceId-xxxx> "null",
   msal.acquireTokenAccount|NO_ACCOUNT|<resourceId-xxxx> "null",
   msal.acquireTokenAccount|NO_ACCOUNT|<resourceId-xxxx> "null",
   remainingSpace: 5242752
}
```

Additionally, I am also internal Microsoft if you want/have time reach out for more context, that would be extremely helpful and potentially we can circle back with a general solution. 

Appreciate the reply!

**Comment by sameerag** [comment]
@pmcgannon22 Couple more follow up questions:

* Have you followed all the considerations highlighted in our IE sample [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-core-samples/VanillaJSTestApp/app/ie11-sample) - Including providing a `promise polyfill`?
* Are you able to run your application successfully outside of an iframe in IE11?

**Comment by pmcgannon22** [comment]
@sameerag 

- Confirmed that Promise polyfill is in place before any MSAL code is run. Also, confirmed there is no trusted sites issue and the `storeAuthStateInCookie` set to true in IE contexts. 
- I just went directly to the embedded iframe to test and it is behaving in essentially the exact manner given the MSAL log output. 

Thanks for the help.

**Comment by pmcgannon22** [comment]
Updating here. This ended up being an issue with my Promise polyfill being too old and/or not having the proper full implementation. I was using a custom polyfill that was defined in a downstream dependency that I assumed would be fine, but it was causing really confusing behavior with some of the transpiled asynchronous code.

After changing my polyfill to [es6-promise](https://www.npmjs.com/package/es6-promise) things seemed to behave much more normally in IE.
