### ISSUE TITLE
Best practice to store and secure tokens/sensitive data in Cookies

### ISSUE THREAD

**Issue by Tzvetelin88** [AzureAD/microsoft-authentication-library-for-js#2384]
## Library
- [X] `@azure/msal-browser@2.3.0`

## Description
Using MSAL 2.x with React 16.12.0.
Is it possible to store sensitive data like Tokens only in Cookies and not in Local/Session storage?

I know about Msal Config:
```
cache: {
        cacheLocation: "sessionStorage", // This configures where your cache will be stored
        storeAuthStateInCookie: true, // Set this to "true" if you are having issues on IE11 or Edge
},
```
, but reading more it seems MSAL will always store data in Local/Session storage and if checked storeAuthStateInCookie to true will store in Cookie too. 

What is the right way to Secure SPA with Cookies and MSAL 2.x? 

Examples: 
I've found very nice demo here: https://courses.reactsecurity.io/courses/react-security-fundamentals, but it is using express as API and they do not use MSAL as authentication library.

**Comment by jasonnutter** [comment]
> Is it possible to store sensitive data like Tokens only in Cookies and not in Local/Session storage?

No, it is not possible with MSAL.js. Cookies come with their own set of negative tradeoffs, namely length concerns.

`storeAuthStateInCookie` will enable MSAL to store certain pieces of information in a cookie, as a mitigation for scenarios where localStorage/sessionStorage gets cleared (IE, Firefox InPrivate) during redirection.

**Comment by Tzvetelin88** [comment]
> We are planning to enable custom storage for MSAL.js, which will allow applications to store tokens in cookie

When it is expected, sounds good.
So, storeAuthStateInCookie  is not yet available?

**Comment by jasonnutter** [comment]
@Tzvetelin88 `storeAuthStateInCookie` is already available in the library. As noted, it only enables storing of certain values in cookies. 

See https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/2060 for progress on custom storage.

(I will also reiterate that we do not believe that it is inherently insecure to store tokens in local storage. )

**Comment by Tzvetelin88** [comment]
I agree, but the only concern with local storage is security. JavaScript code easily access local storage: it has no data protection whatsoever. This is the big one for security reasons.  It is perfect when you need to store some publicly available information that is not at all sensitive, doesn't need to be used in a high-performance app, isn't larger than 5MB, and consists of purely string data. 
Yes, best way is to thing what data to be stored were. For me, best is to store sensitive data like IdTokens, accessTokens in Cookies, mark them as HttpOnly and if they exist in Local/Session storage on time of authenticate delete them.
I will check storeAuthStateInCookie and check which is the best option for me in this case. Thanks!

**Comment by jasonnutter** [comment]
@Tzvetelin88 HttpOnly cookies will not work for MSAL.js, as MSAL.js needs to be able to read/write cookies from JavaScript. 

Closing.
