### ISSUE TITLE
How to get user role of the logged in user

### ISSUE THREAD

**Issue by manoharnikkam** [AzureAD/microsoft-authentication-library-for-js#2385]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.3.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
What is the right way to get the logged in user role setup in Azure AD app registration in [angular10-browser-sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular10-browser-sample) app using @azure/msal-browser.

1. Added a user role to app manifest during app registration in Azure
2. added a user to the role
3. launched angular-10-browser-sample app. 
4. I see from the access token that role is identified

<img width="1099" alt="Screen Shot 2020-10-07 at 4 30 33 PM" src="https://user-images.githubusercontent.com/8573069/95391614-f7d90180-08bc-11eb-99f8-ffe9e2f8a23a.png">
<img width="700" alt="Screen Shot 2020-10-07 at 4 45 11 PM" src="https://user-images.githubusercontent.com/8573069/95391623-fa3b5b80-08bc-11eb-8f14-54beff921c12.png">

**Comment by sameerag** [comment]
@manoharnikkam your question isn't clear to me. Are you asking if the above steps are the correct way to get the `user roles` in your tokens?

**Comment by manoharnikkam** [comment]
@sameerag Sorry, I was not clear.  I got the token with application roles coming back after authentication. The area I needed help was on how to get these roles into the [Angular 10](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular10-browser-sample) application so that I can use them trim security in UI based on the role. 
Appreciate any help.

Thanks
Manohar

**Comment by brunnosantos** [comment]
Subscribe to MSALBroadcastService.msalSubject$ and filter any events LOGIN_SUCCESS || ACQUIRE_TOKEN_SUCCESS... for my use case I just needed to do it once, but the operators depend on your needs

`if (authService.getAllAccounts().length > 0) {
        broadcastService.msalSubject$
            .pipe(
                filter(msg => msg.type === MsalBroadcastEvent.LOGIN_SUCCESS || msg.type === MsalBroadcastEvent.ACQUIRE_TOKEN_SUCCESS),
                first()
            )
            .subscribe((response) => {
                // do whatever you want with response.payload, including **response.payload.roles** array, or account info 
                // (response.payload.account)
            });
  }`

> @sameerag Sorry, I was not clear. I got the token with application roles coming back after authentication. The area I needed help is on how to get these roles into the [Angular 10](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular10-browser-sample) application so that I can use them trim security in UI based on the role.
> Appreciate any help.
> 
> Thanks
> Manohar

**Comment by manoharnikkam** [comment]
Thank you @brunnosantos for the tip. I ended up caching the roles and Login_success or Acquire_Token_Success in msal.service.ts. Having it this way I don't know to subscribe every single time

**Comment by manoharnikkam** [comment]
Thank you @brunnosantos for the tip. I ended up caching the roles and Login_success or Acquire_Token_Success in msal.service.ts. Having it this way I don't know to subscribe every single time

**Comment by manoharnikkam** [comment]
If there is a better alternative, please share
