### ISSUE TITLE
Renewing Token

### ISSUE THREAD

**Issue by bstair** [AzureAD/microsoft-authentication-library-for-js#2386]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

Claims aren't updating when renewing the token.

Using msal-browser 2.2 with a custom user flow that sets some claims in the token.
The application has a workflow to update some of those fields via graph and renew the token immediately to see the updated claims in the token.

We had it working in msal 1.2 by calling acquireTokenSilent, but with 2.2 calling acquireTokenSilent with forceRefresh: true doesn't seem to be updating any of the claims. I can see the network call to fetch the token and I can see that a new token comes back with an updated expiration, but for some reason it doesn't come back with updated claims in the token. If I log out and log back in the claims are correctly in the token.

Am I missing something for properly renewing a token with updated claims?

**Comment by sameerag** [comment]
I am not entirely sure if this is a service issue or the library. Can you please share us the steps to reproduce or email me [here](sameera.gajjarapu@microsoft.com) if the custom claims and token details are specific to your application, for me to be able to check your use case with the eSTS team?

**Comment by bstair** [comment]
I've tried to include all relevant information, please let me know if there's something else needed for clarification.


Our B2C Policy makes a REST call to a service to populate some custom claims in the token.

1. Log into application (I get a valid access token with claims)
2. Land on an Account Information Page
3. Update some fields that are usually shown on the token.
4. Hit save
    a) a service call is made to update a claim via graph
    b) then the response triggers a call to acquireTokenSilent with forceRefresh: true

Expectation: The token contains the updated claims
Reality: The token gets an updated expiration time but still has the original claims

Here is my renewToken request

```
get renewTokenRequest(): Msal.SilentRequest {
        const params: Msal.SilentRequest = {
            account: this.msalApp.getAccountByHomeId(this.accountId),
            scopes: this.config.scopes.map(s => s.value),
            forceRefresh: true
        };
        params.scopes.push('offline_access');

        return params;
}
```

And here is how I call acquireTokenSilent

`this.msalApp.acquireTokenSilent(this.renewTokenRequest)`

Request Headers:
```
POST /{tenant}.onmicrosoft.com/{policy}/oauth2/v2.0/token HTTP/1.1
Host: {tenant}.b2clogin.com
Connection: keep-alive
Content-Length: 1724
x-ms-lib-capability: retry-after, h429
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
x-client-sku: msal.js.browser
content-type: application/x-www-form-urlencoded;charset=utf-8
x-client-cpu: 
x-client-current-telemetry: 2|61,0|
x-client-last-telemetry: 2|0|||0
x-client-os: 
x-client-ver: 2.3.0
Accept: */*
Origin: {origin}
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: {referer}
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
```

Request Body:
```
client_id: {clientId}
scope: {scope} offline_access openid profile
grant_type: refresh_token
client_info: 1
client-request-id: {clientRequestId}
refresh_token: {token}
```

Response: 

`{"access_token":"{token}","scope":"{scope}"}`

**Comment by bstair** [comment]
any updates on this?

**Comment by MedGhassen** [comment]
Any updates on this ?

**Comment by tnorling** [comment]
@bstair @MedGhassen If you call `acquireTokenRedirect`, `acquireTokenPopup` or `ssoSilent` instead of `acquireTokenSilent` do you get the updated claims? Service level questions such as this are better asked to the Service teams but I'm going to guess that claims are refreshed when calling the `/authorize` endpoint. One major difference between `msal@1.x` and `msal-browser@2.x` is that `acquireTokenSilent` does not call the `/authorize` endpoint but instead calls the `/token` endpoint with your refresh token, usually this will only return the same token you had before but with an updated expiration.
