### ISSUE TITLE
Is it possible to authenticate websites with a broker like the MS-Authenticator-App on android?

### ISSUE THREAD

**Issue by meinto** [AzureAD/microsoft-authentication-library-for-js#2395]
## Library
- [x] `@azure/msal-browser@2.x.x`

## Description

I have multiple android apps and websites (spa's) and want to provide SSO across all of them. I successfully implemented SSO across the native apps using the msal-sdk and the MS-Authenticator app in shared-mode. But when i setup the [masl.js sample app](https://github.com/Azure-Samples/ms-identity-javascript-v2), it always asks me for credentials although i'm logged in, in one of my native apps.

**Comment by sameerag** [comment]
`msal js` doesn't support native brokers and we do not have SSO with the native applications in android yet. From my understanding, in FLW, embedded web view works with brokers and hence the default browsers will not have the cookies for `msal js` to login silently.

Linking @rpdome from the android team to note this use case for the FLW design.

**Comment by sameerag** [comment]
@meinto Please contact the [Android team](https://github.com/AzureAD/microsoft-authentication-library-for-android) for any more questions. Closing this.
