### ISSUE TITLE
msal-browser and B2B: redirect to the Azure sign in page in a specified language

### ISSUE THREAD

**Issue by jasonjohnlee** [AzureAD/microsoft-authentication-library-for-js#2397]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
When we use the `PublicClientApplication.loginRedirect` function, is it possible to specify the language to display on the Azure login page?  I looked at the `RedirectRequest` interface and I don't believe there's an option for that.  Other posts I've seen are in reference to the B2C flow but we're using B2B.

I know the Azure webpages use the language of the browser which is typically fine.  However, our web app allows the user to select a language so it would be great to somehow keep Azure and our web app's language in sync in the event that the browser language is not in the user's preferred language.

**Comment by sameerag** [comment]
@hpsin We tried passing `extraQueryParameters` with `ui-locales`:`<desired language code>?` and still see the issue.

```javascript
extraQueryParameters: {
     "ui_locales": "<desired language code>"
}
```

 Is there any other global setting needed here for the user to have dynamic language support for the above use case?

**Comment by hpsin** [comment]
ui_locales is not supported by AAD.  I've opened a tracking item for it internally.

**Comment by hpsin** [comment]
#please-close the ask is not supported today.
