### ISSUE TITLE
Modify or add the parameter value of "scope"

### ISSUE THREAD

**Issue by fengzhihenxs** [AzureAD/microsoft-authentication-library-for-js#2398]
## Library 
- [x] `@azure/msal-browser@2.2.0` 

## Description
 Hello, how can I modify or add the parameter value of "scope" in the request using this library?

**Comment by sameerag** [comment]
Can you please read the documentation [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/request-response-object.md#scopes)? 

Hope it helps!
