### ISSUE TITLE
Token is not getting refreshed

### ISSUE THREAD

**Issue by bilalmalik777** [AzureAD/microsoft-authentication-library-for-js#2400]
Hello, We are using adal-angular for authentication, in the react js application, from the azure ad. After some time it shows the error and the token is getting refreshed. The error is given below. also shared the network trace(ttreacttest.azurewebsites.net.txt), code, and console error image. We are using OAuth and generating a token for API resources. After reloading the page error, the application starts to behave normally. Please help me to solve this issue

`We are getting this error "WWW-Authenticate: Bearer error="invalid_token", error_description="The token expired at '10/02/2020 16:50:51'""`
[ttreacttest.azurewebsites.net.txt](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/5353139/ttreacttest.azurewebsites.net.txt)

**This is the configuration part**
```
 "apiUrl": "https://localhost:44379/api",
    "hubConnectionUrl": "https://localhost:44379/hub/",
    "adalConfig": {
      "clientId": "********************",
      "endpoints": {
        "api": "************************"
      },
      "tenant": "****************************",
      "cacheLocation": "localStorage",
      "redirectUri": "http://localhost:3000"
    }
```
**this one is for authentication after loading the configuration**
```
import AuthenticationContext from "adal-angular";
import { getEnvDetail } from "../../utils/env";
 
const envDetail = getEnvDetail();
const AdalConfig = envDetail.adalConfig;
 
// We use this to enable logging in the adal library. When you're building for production, you should know that it's best to disable the logging.
window.Logging.log = function(message) {
  console.log(message); // this enables logging to the console
};
window.Logging.level = 2; // 0 = only error, 1 = up to warnings, 2 = up to info, 3 = up to verbose
 
// Initialize the authentication
export default new AuthenticationContext(AdalConfig);
```
**Here we are fetching and attaching the token with api call**
```
import axios from 'axios';
 
import AuthContext from '../services/auth';
import { getEnvDetail } from '../utils/env';
 
const envDetail = getEnvDetail();
const AdalConfig = envDetail.adalConfig;
const instance = axios.create();
 
// Add a request interceptor
instance.interceptors.request.use(
  config => {
    // Check and acquire a token before the request is sent
    return new Promise((resolve, reject) => {
      AuthContext.acquireToken(
        AdalConfig.endpoints.api,
        (message, token, msg) => {
          if (!!token) {
            config.headers.Authorization = `Bearer ${token}`;
            resolve(config);
          } else {
            // Do something with error of acquiring the token
            reject(config);
          }
        }
      );
    });
  },
  function(error) {
    // Do something with error of the request
    return Promise.reject(error);
  }
);
```
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/23011613/95555398-3c6db580-0a01-11eb-83bb-dfae39c92562.png)

**Comment by sameerag** [comment]
@bilalmalik777 Can you clarify if you are seeing the `token expired` error even after refreshing the token? Please note that every token has a limited lifetime and the application should refresh the token before expiry to keep it active. This usually can be done by calling `acquireToken` which silently refreshes the token.

I suspect that the page refresh is doing this for you and hence the error is not seen in that case. 

Also we recommend to upgrade to [`msal-js`](https://github.com/AzureAD/microsoft-authentication-library-for-js) for your authentication, since `adal-js` is in maintenance and all new features and supportability is focused on `msal-js`
