### ISSUE TITLE
Does MSAL v2 support redirect interactions in iframe scenarios?

### ISSUE THREAD

**Issue by deasems** [AzureAD/microsoft-authentication-library-for-js#2401]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
I'm working on an application that will be embedded within an iframe in a partner application. I understood that redirect flows are not supported in iframe scenarios and so we've been developing a solution with cross-frame communication using `ssoSilent` using a username sent from the parent application. 

By chance, I triggered a `redirect_in_iframe` error and saw the message:
> Code flow is not supported inside an iframe. Please ensure you are using MSAL.js in a top frame of the window if using the redirect APIs, or use the popup APIs. (window.parent !== window) => true

This leads me to believe MSAL has some extra level of support for scenarios where both the parent and child frame are running MSAL v2, is that correct? are there any docs on this? any specific implementation requirements for the parent app? can the child app just use the redirect methods as if they're not in an iframe and have it work as expected?

**Comment by sameerag** [comment]
@deasems At this time, the `redirect` APIs in `msal-browser` are not supported in iframed applications (`popup` and `silent` APIs are supported). This is a restriction from the Service where the login UX does not support rendering in an iframe. We are working on providing support for embedded application scenarios like this, however that work is currently in progress and hence there is no documentation available at this time.

We will share more in our roadmap soon.

**Comment by deasems** [comment]
Thanks @sameerag, I'll keep an eye out for roadmap updates.
