### ISSUE TITLE
Acquire silent token refresh strategy does not return an access token

### ISSUE THREAD

**Issue by judedaryl** [AzureAD/microsoft-authentication-library-for-js#2408]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.3.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
React

## Description
When targeting multiple resources, acquireSilentToken does not return an access token for a resource that was not part of the ``acquireTokenRedirect`` scope.

Scopes:

``A.0`` - Resource A
``B.0`` - Resource B

This request redirects to idp and returns an id_token
```
acquireTokenRedirect({
   scopes: ['openid','profile']
});
```

This request calls the token endpoint using refresh strategy and **does not** return an access token
```
acquireTokenSilent({
   scopes: ['A.0']
})
```

This request calls the token endpoint using refresh strategy and **does not** return an access token
```
acquireTokenSilent({
   scopes: ['B.0']
})
```

While tracing the network calls, both of the acquireTokenSilent request are appending the scopes ``['openid', 'profile']`` to the refresh endpoint, causing it to not fail and in effect does not proceed to request for an access token using the other strategies (``authorization code``, ``iframe``)

![Screenshot_26](https://user-images.githubusercontent.com/13645031/95666049-a19fe300-0b88-11eb-9f21-3452cb2a4ae6.png)

![Screenshot_27](https://user-images.githubusercontent.com/13645031/95666091-27bc2980-0b89-11eb-83dd-83358a7d76f6.png)

## Error Message

N/A

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Expected behavior

``acquireTokenSilent`` should not append the scopes ``openid`` and ``profile`` to the refresh token request so that it fails and proceed to the other strategies.

This however works fine in the [compiled](https://alcdn.msauth.net/browser/2.1.0/js/msal-browser.min.js) version ``2.1.0`` and the [npm package](https://www.npmjs.com/package/@azure/msal-browser/v/2.1.0) version ``2.1.0``

## Browsers/Environment
- [ ] Chrome
- [ ] Firefox
- [x] Edge - Chromium
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by judedaryl** [comment]
This issue was addressed here https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/1962/files, but i think it regressed for version 2.3.0

**Comment by tnorling** [comment]
@judedaryl This is a known issue with B2C and is being tracked in #2315. Please see that thread for the suggested workaround until a fix is rolled out. Closing as duplicate.
