### ISSUE TITLE
Authentication failure, invalid audience with Confidential Client (Microsoft Graph, Node.js)

### ISSUE THREAD

**Issue by aimkey** [AzureAD/microsoft-authentication-library-for-js#2409]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

I'm trying to read and write users and send some email on my Node.js backend (permissions: User.ReadWrite.All, Mail.Send). I'm getting ```Error: Access token validation failure. Invalid audience``` when trying to use auth tokens to make requests. Does anyone know what I'm doing wrong?

Some overview:

* I'm using authority: ```'https://login.microsoftonline.com/' + <my_tenant_id>``` in the clientConfig object
* Since there doesn't appear to be a provided AuthenticationProvider for Confidential Clients, I'm rolling my own implementation (storing the serialized json in Redis, acquiring a new token if the most recent token is near expiration)
* (Point of confusion) I'm using the rather nebulous ```api://<application_id_uri>/.default``` as my scope passed to the ```confidentialClientApplication.acquireTokenByClientCredential``` call instead of ```['Mail.Send', 'User.ReadWrite.All']```. Is this correct?
* A sample token object looks like this: 

```
    '-login.windows.net-accesstoken-<client_id>-https://graph.microsoft.com/.default': {
      home_account_id: '',
      environment: 'login.windows.net',
      credential_type: 'AccessToken',
      client_id: '<client_id>',
      secret: '<secret>',
      realm: '<realm>',
      target: 'https://graph.microsoft.com/.default',
      cached_at: '1602459904',
      expires_on: '1602463503',
      extended_expires_on: '1602467102',
      token_type: 'Bearer'
    }
```

* When I decode the secret from the above token on ```https://jwt.ms```, the ```aud``` field value is ```"https://graph.microsoft.com"```
* (Point of confusion) I DON'T have any Scopes or Authorized Client Applications defined on the ```Expose an API``` page on the Azure Portal. Do I need to expose Mail.Send and User.ReadWrite.All and authorize my client app? I have already configured these permissions and granted admin consent on the ```API Permissions``` tab...

Anyone know what I'm doing wrong? Any help would be GREATLY appreciated!

With all respect, I must say that this is quite the rat's nest of terminology and leaky abstractions. Tenants? Authorities? Scopes? Audiences? No ```ConfidentialClientAuthenticationProvider``` implementation for Node? A lot to wrap your head around. Almost on par with rolling my own OAuth implementation. I just want to list my users and send an email...it would be great if an admin API key could be provided with the token refresh implementation hidden under the hood in the future, a la Firebase Admin SDK.

**Comment by sameerag** [comment]
@aimkey 

You mentioned  `msal@1.x.x or @azure/msal@1.x.x` in your question. Are you using `msal@1.x.x  or msal-node`?`msal@1.x.x` does not support confidential client and supports only implicit_flow in browser apps. 
If you are looking for a backend authentication support, please use `msal-node` which is currently in private preview [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-node)

* There is `ConfidentialClient` support provided in `msal-node`: [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-node-samples/standalone-samples/auth-code/index.js) for `auth-code` and [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-node-samples/standalone-samples/auth-code/index.js) for `ClientCredentials` flow.
* What is the API mentioned in: `api://<application_id_uri>/.default`, is it the webAPI you want permissions for? `Scopes` of the format ['Mail.Send', 'User.ReadWrite.All'] are assumed to be for `MSGraph`. More details on scopes, consent and permission can be found [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent)
* The tutorial provided above also specifies `portal` settings, please let us know if your question still remains.

**Comment by aimkey** [comment]
I got things working my changing my scope to ```'https://graph.microsoft.com/.default'```
