### ISSUE TITLE
Authentication of personal Microsoft Account not working

### ISSUE THREAD

**Issue by sherwincool** [AzureAD/microsoft-authentication-library-for-js#241]
When we use this Adal js before, we can successfully login using personal microsoft account and azure ad account. But...

Im not sure whats going on in microsoft online but when Im trying to authenticate using a personal microsoft account, its always getting this error: 

AADSTS50020: We are unable to issue tokens from this api version for a Microsoft account. Please contact the application vendor as they need to use version 2.0 of the protocol to support this.

here is the login URL:

https://login.microsoftonline.com/common/oauth2/authorize?response_type=id_token&client_id=f69fde41-bc12-4a24-9833-10bef9704107&redirect_uri=http%3A%2F%2Flocalhost%3A1508%2F&state=2a5e88e6-8bd8-42eb-ba45-6b672d84ba26&client-request-id=ed065975-54e8-4018-a15d-b12826929bfd&x-client-SKU=Js&x-client-Ver=1.0.13&nonce=17108978-fdd6-4232-a21e-4d70e2b26024

I also registered that client ID in https://apps.dev.microsoft.com/#/appList which supports both V1 and V2.

**Comment by rohitnarula7176** [comment]
@sherwincool MSAL.js works with the AzureAD V2 endpoint, whereas ADAL.js works with the AzureAD V1 endpoint. The V1 endpoint supports work accounts, but not personal accounts. The V2.0 endpoint is the unification of Microsoft personal accounts and work accounts into a single authentication system. if you need to authenticate using your personal Microsoft account , you should use MSALJs whch goes through the v2 endpoint.

**Comment by sherwincool** [comment]
Thank you @rohitnarula7176  for this reply and really appreciate it. :) but just what I said we can successfully authenticated both before (Feb 2017) then suddenly this happen. Is there any changes in authentication?

**Comment by rohitnarula7176** [comment]
@sherwincool This is just a coincidence. Personal account is not officially supported by v1 endpoint, There is no guarantee it will work.
