### ISSUE TITLE
When could MSAL React package released?

### ISSUE THREAD

**Issue by RichardSunMS** [AzureAD/microsoft-authentication-library-for-js#2412]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `@azure/msal-react@???`

Is there any release plan ready for msal React version? 

Thanks.
Richard.

**Comment by ankursehdev** [comment]
looking forward to this too!

**Comment by tnorling** [comment]
@RichardSunMS We currently expect to have an alpha of msal-react available sometime next month. Any changes to timelines and additional feature work will be tracked in our [roadmap](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/roadmap.md). We look forward to sharing more and getting your feedback soon!
