### ISSUE TITLE
Cannot read property 'split' of undefined` Error upon starting app

### ISSUE THREAD

**Issue by jonasgroendahl** [AzureAD/microsoft-authentication-library-for-js#2413]
## Library
- [ ] `@azure/msal-browser@2.3.0`

## Framework
Next.js

## Description
When using the HTML export feature in nextjs to build my app, I get an error once the app starts. It works fine locally in development, but as I soon as I export the app and run the static files, it throws an error. I believe maybe the error has something to do with msal-browser changing the browser history behind the scenes? (https://github.com/vercel/next.js/issues/9698)

## Error Message

<img width="736" alt="Screen Shot 2020-10-13 at 11 02 39 AM" src="https://user-images.githubusercontent.com/23399953/95840028-f76cba80-0d43-11eb-86e1-b75d67e0269e.png">
<img width="893" alt="Screen Shot 2020-10-13 at 11 02 26 AM" src="https://user-images.githubusercontent.com/23399953/95840032-f89de780-0d43-11eb-9f9c-f20a1a39bdb4.png">

## Security
- [Maybe] Is this issue security related?

## MSAL Configuration
Not important since it works just fine in development.

## Reproduction steps
I wrapped my app in a context provider and in there i define the following useEffect hook:
```js
  import { checkIfLoggedIn, msalObj, signIn } from './auth';

  const handleResponse = (response) => {
    console.log('handleResponse', response);
    // check cookies
    const signedIn = checkIfLoggedIn();

    if (signedIn) {
      setIsLoggedIn(true);
    } else if (response) {
      // if we redirected from the login page
      setIsLoggedIn(true);
    } else if (!signedIn) {
      // if no cookies set and we are not getting redirected, we assume the user is not authenticated yet
      signIn();
    }
  };


  useEffect(() => {
    console.log('AuthContext loaded');
    // on app load, add the redirect promise handler, this one is executed each time the app is loaded and the msal object created.
    msalObj.handleRedirectPromise().then(handleResponse);
  }, []);
```

## Browsers/Environment
- [x ] Chrome
- [x ] Safari

**Comment by sameerag** [comment]
@tnorling Can you please address this issue? This may fall under the `React` bucket of issues.

**Comment by tnorling** [comment]
@jonasgroendahl Can you clarify if `msal-browser` is throwing this error or something else? If you could provide a reproduction or do some debugging on your own to determine what's going on here that would be helpful. We have tested `msal-browser` with next.js and have not experienced this.

**Comment by jonasgroendahl** [comment]
if I remove the useEffect hook, the app works no problem. it only happens for **HTML exported nextjs** apps.

**Comment by jonasgroendahl** [comment]
Seems to be a problem with another dept. Apologies
