### ISSUE TITLE
Seeings CORS error when POST /token returns 401. There are no CORS headers in response

### ISSUE THREAD

**Issue by thoo1** [AzureAD/microsoft-authentication-library-for-js#2416]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.2.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
React

## Description
Getting unexpected CORS error
sample x-ms-request-id: 1fc40f56-aa0b-4c05-9a96-45fd61420400
I also have an HAR file that can show this. Please message me for it

## Error Message
CORS error in browser's console

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
    const browser = Bowser.getParser(window.navigator.userAgent);
    const isIEOrOldEdge =
      browser.satisfies({ edge: "<79" }) || browser.getBrowserName().toLowerCase() === "internet explorer";
    const publicClientApp = new PublicClientApplication({
      auth: {
        clientId: this.clientId,
        authority: this.authority,
        redirectUri: this.loginRedirectUri,
        postLogoutRedirectUri: this.postLogoutRedirectUri
      },
      cache: {
        cacheLocation: "localStorage",
        storeAuthStateInCookie: isIEOrOldEdge // https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1188#issuecomment-634281307
      },
      system: {
        tokenRenewalOffsetSeconds: 60,
        iframeHashTimeout: 30000, // iframe is used to refresh the refresh_token as it has a 24h lifetime
        loggerOptions: {
          loggerCallback: MsalAuthContext.msalLoggerCallback,
          piiLoggingEnabled: false,
          logLevel: LogLevel.Verbose
        }
      }
    });
    const handleRedirectPromise = publicClientApp
      .handleRedirectPromise()
      .then(response => {
        this.account = response ? response.account : this.getAccount();
        if (!this.account) {
          CoreLogger.trackEvent(TelemetryEventName.Core_MSALAuthContext_login);
          this.publicClientApp.loginRedirect({
            scopes: this.scopes,
            authority: this.authority,
            extraQueryParameters: this.safeRolloutQueryParams
          });
        }
      })
      .catch(error => {
        if (error) {
          this.trackError(error);
        }
      });
```

## Reproduction steps
1. Have a refresh token that is expired
2. MSAL will try to call POST /token and receives a 400 - that the refresh token has expired
3. MSAL will try to call POST /token again and receives a 401 - but with no CORS headers in the response headers, resulting in CORS issue

## Expected behavior
- no CORS issues

## Browsers/Environment
- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jasonnutter** [comment]
@thoo1 Can you please confirm that the redirect URI used for the request is of type "spa"? This is required for CORS with MSAL v2.

**Comment by thoo1** [comment]
@jasonnutter yes, I can confirm that, however its a bit complicated because i'm using safe rollout (our app is a first-party app) and so the config change that switches the reply url from "web" to "spa" is inside a safe rollout which is enabled by passing some queryParameters

I did this for `acquireTokenRedirect` and `loginRedirect` as those functions have options for `extraQueryParameters`, I notice that `acquireTokenSilent` does not have an option to attach `extraQueryParameters`.

So in this case, would the POST /token endpoint also check that the reply url has to be type "spa"? If so, it looks like this is probably the reason, since there is no option to pass my safe-rollout query param on `acquireTokenSilent`

**Comment by jasonnutter** [comment]
@thoo1 Ah, sounds like we need to add `extraQueryParameters` to the acquireTokenSilent API?

**Comment by jasonnutter** [comment]
Although looking at the logs for the request above, the error is happening when MSAL.js is attempting to trade the authorization code. If this error happens in that scenario, it means the redirect URI used to acquire the authorization code was not of type spa.

**Comment by thoo1** [comment]
In that case then yea, it looks like the acquireTokenSilent api needs this `extraQueryParameters` to support safe rollout

I tried this manually by copying the request in browser and adding query param and it still fails with same error (no cors headers returned and response is 401) (x-ms-request-id: 935b4122-6d56-4cba-9501-950b35ba0a00)

Btw in fiddler, I'm able to see that the body is: {
  "error": "invalid_client",
  "error_description": "AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.\r\nTrace ID: 935b4122-6d56-4cba-9501-950b35ba0a00\r\nCorrelation ID: 83f1aba5-4048-4d21-bf69-8c0d1f06f10c\r\nTimestamp: 2020-10-13 23:14:18Z",
  "error_codes": [
    7000218
  ],
  "timestamp": "2020-10-13 23:14:18Z",
  "trace_id": "935b4122-6d56-4cba-9501-950b35ba0a00",
  "correlation_id": "83f1aba5-4048-4d21-bf69-8c0d1f06f10c",
  "error_uri": "https://login.microsoftonline.com/error?code=7000218",
  "claims": "{\"access_token\":{\"capolids\":{\"essential\":true,\"values\":[\"c4cc8861-4e14-42f9-b2e5-9f04efa54474\",\"0a262422-d374-4d34-8542-4de125591b51\"]}}}"
}

**Comment by jasonnutter** [comment]
As a workaround for now, when you get this error can you invoke `ssoSilent` (passing the same scopes and the users's email as the loginHint)? It accepts extraQueryParameters.

**Comment by thoo1** [comment]
Sure, I can try that, however could we confirm if adding the safe_rollout query param to the request will fix the issue? Because in the above comment, I tried and the request was still failing

Is there a reason why 401s on this endpoint does not return CORS headers? This makes the js unable to read the response at all and do anything according to the response body's error codes

**Comment by thoo1** [comment]
Thanks for the quick action on this @jasonnutter! Looking forward to the next release

**Comment by thoo1** [comment]
@sameerag, could you provide any ETA for the 2.3.2 release?

**Comment by jasonnutter** [comment]
@thoo1 One note, the fix for this was purely for types. This means if you provide `extraQueryParameters` to `acquireTokenSilent` at runtime, they should get passed (you will need to ignore the Typescript warnings).

**Comment by thoo1** [comment]
@jasonnutter thanks jason! I'll try that
