### ISSUE TITLE
msal-node multiple resources

### ISSUE THREAD

**Issue by NuSkooler** [AzureAD/microsoft-authentication-library-for-js#2418]
## Library
`@azure/msal-node`

## Description
I'm using `msal-node` with the device code flow. I would like to acquire consent and tokens for multiple resources but can't seem to figure out how to do it with this library. Please advise.

**Comment by sameerag** [comment]
@NuSkooler Can you please share your template code? 

Here are the general guidelines on acquiring tokens for multiple resources:

* Please pass scopes(resource specific) in separate requests, typically one resource per `acquireToken` call
* Make sure the concerned consent is given to the user accessing the resources, either through interaction, or pre-consent in the portal

Please let me know if this doesn't work for your use case. Also please share the config and the request code, any logs and fiddler trace for the same.

**Comment by NuSkooler** [comment]
@sameerag Thanks for your response. Here are some more details and some code:

I'm attempting to use `node-msal` to:
- Use the Device Code flow prompting the user to grant permission for multiple resource/scopes (requires user interaction of course)
- Acquire a token for each of the resource/scope pairs (this portion should be silent as they have already consented)

There isn't a ton of information I can find in this, but I see mentions of using the `acquireTokenSilent` to request the additional resource/scope tokens.

Example code:
```
const msal = require('@azure/msal-node');

const POCClientID = "XXXXXXXX-f6e7-XXXX-XXXX-dbdd083e7e5a"; // redacted

const msalConfig = {
    auth : {
        clientId: POCClientID,
        authority: "https://login.microsoftonline.com/XXXXXXXX-20bf-XXXX-XXXX-e3323b05adfa", // redacted
        // from what I understand the Angular wrappers allow up-front additional resource/scopes here
    }
}

const pca = new msal.PublicClientApplication(msalConfig);

const deviceCodeRequest = {
    deviceCodeCallback: (response) => (console.log(response.message)),
    scopes: ["offline_access", "https://storage.azure.com/user_impersonation" ],
};

pca.acquireTokenByDeviceCode(deviceCodeRequest).then((response) => {
    console.log(JSON.stringify(response, null, 2));

    console.log(pca.getTokenCache().getAllAccounts());

    setTimeout(() => {
        const newTokenScopeRequest = {
            scopes : [ "offline_access", "https://management.azure.com/user_impersonation" ],
            account : response.account,
        };
        pca.acquireTokenSilent(newTokenScopeRequest).then((response) => {
            console.log(JSON.stringify(response, null, 2));
        });
    }, 5000);

}).catch((error) => {
    console.log(JSON.stringify(error));
});
```

Given the above, the call to `acquireTokenSilent` fails.

Should I be using `acquireToken` again? Using pure REST calls (e.g. with cURL or httpie) I utilize the refresh_token to acquire tokens with additional scopes.

**Comment by sameerag** [comment]
Can you please share the error? In theory, the above code should have worked if all scopes are pre-authorized. May be looking at the specific error code will give us a better clue on why this is failing for you.

**Comment by NuSkooler** [comment]
@sameerag I've been pulled to another project for a bit, but I'll try to get you information ASAP

**Comment by NuSkooler** [comment]
@sameerag I changed two things with the application posted above due to requirements and it is working for me now. I'm not sure if they are related:
* `authority: "https://login.microsoftonline.com/common",`
* Now using `.default` scope, e.g. `scopes: ["https://storage.azure.com/.default" ],`

**Comment by sameerag** [comment]
Great @NuSkooler. As I mentioned above, access tokens are resource specific and scope format is agreed with the service in advance. Please let us know if you notice any further issues.
