### ISSUE TITLE
MSAL throws clientAuthError

### ISSUE THREAD

**Issue by NishanthRE** [AzureAD/microsoft-authentication-library-for-js#2419]
At firsttime login with the msal is working fine. when i try to open the same application in another tab it throws an error as **clientAuthError:  The idToken is null or empty. Please review the trace to determine the root cause. Raw ID Token Value: null**
![Screenshot (482)](https://user-images.githubusercontent.com/43135722/95965120-345dad80-0e27-11eb-96d4-eb9c4905b2fa.png)

using the latest version of msal and @azure/msal-angular. please have a look into it and help me to get out from this issue.

code sampe:
```
return from(
      this.msalSvc.acquireTokenSilent({ scopes })
        .then((response: AuthResponse) => {
          defaultHeaders['Authorization'] = accessToken;
          return request.clone({
            setHeaders: defaultHeaders
          });
        })
    )
      .pipe(
        mergeMap(nextReq => next.handle(nextReq).pipe(
          map((event: HttpEvent<any>) => {
            if (event instanceof HttpResponse) {
            }
            return event;
          }),
          catchError((error: HttpErrorResponse) => {
            return throwError(error);
          })
        )),
        tap(
          event => { },
          err => {
            if (err instanceof HttpErrorResponse && err.status === 401) {
              this.msalSvc.clearCacheForScope(accessToken);
            }
            return err;
          }
        )
      );
```
Thanks in advance

**Comment by sameerag** [comment]
@NishanthRE Can you please share your configuration? If you are using `sessionStorage` you will not be able to share authentication across tabs.

**Comment by NishanthRE** [comment]
Sameera,
          Thanks for the response. I have fixed it by myself.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
