### ISSUE TITLE
MSAL and Full trust Oauth for First party app

### ISSUE THREAD

**Issue by jrmcdona** [AzureAD/microsoft-authentication-library-for-js#242]
We have an Angular front end connecting to a Web Api project using a bearer token and the Full trust Oauth flavor.

Will MSAL work well for our front end?

Thanks

**Comment by navyasric** [comment]
@jrmcdona What is the full trust Oauth flavor you are referring to? MSAL.js uses the Implicit grant of Oauth. Regarding the web api, is it your application's own backend API or a third party API?

**Comment by navyasric** [comment]
Closing this issue for now. Please re-open if necessary.
