### ISSUE TITLE
handleRedirectPromise is returning a null token response

### ISSUE THREAD

**Issue by abf7d** [AzureAD/microsoft-authentication-library-for-js#2420]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.3.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Description
I am developing an Angular 10 app that utilizes Azure B2C for policy and user management. I set up my app registration in Azure Active Directory as a singlepage app without the implicit option checked. I am using msal.js 2.3.0 @azure/msal-browser to log into B2C and retrieve id and access tokens using code flow. I set up my configuration, created the msal object, defined the redirect promise, then later call loginRedirect with the appropriate user scopes. The page redirects properly.

However, after I sign in the tokenResponse comes back as null. I have tried altering the authority and scopes, but it always comes back as null. How do I get the handleRedirectPromise to return a valid token response?

## Error Message
No error message shows, the token response comes back as null.

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
private msalConfig: Msal.Configuration = {
        auth: {
            clientId: environment.clientID,
            authority: `https://<mytenant>.b2clogin.com/tfp/<mytenant>.onmicrosoft.com/B2C_1_DefaultSignInSignUp`,
            redirectUri: 'https://localhost:4200', 
            knownAuthorities: ['<mytenant>.b2clogin.com'],
            navigateToLoginRequestUrl: true
        },
        cache: {
            cacheLocation: 'sessionStorage',
            storeAuthStateInCookie: true, 
        },
        system: {
            loggerOptions: {
                loggerCallback: (level: Msal.LogLevel, message: string, containsPii: boolean): void => {
                    if (containsPii) {
                        return;
                    }
                    switch (level) {
                        case Msal.LogLevel.Error:
                            console.error(message);
                            return;
                        case Msal.LogLevel.Info:
                            console.info(message);
                            return;
                        case Msal.LogLevel.Verbose:
                            console.debug(message);
                            return;
                        case Msal.LogLevel.Warning:
                            console.warn(message);
                            return;
                    }
                },
                piiLoggingEnabled: false,
            },
        },
    };
```

## Reproduction steps
Here is how I set up the redirect promise. Below is the login function with the scope I use.
```js
    private msalInstance: Msal.PublicClientApplication;

    constructor(private accountDataService: AccountDataService, private authStore: AuthStoreService) {

        this.msalInstance = new Msal.PublicClientApplication(this.msalConfig);
        
        this.msalInstance
            .handleRedirectPromise()
            .then((tokenResponse: Msal.AuthenticationResult) => {
                let accountObj = null;
                if (tokenResponse !== null) {
                    accountObj = tokenResponse.account;
                    const id_token = tokenResponse.idToken;
                    const access_token = tokenResponse.accessToken;
                    console.log('id_token', id_token);
                    console.log('access_token', access_token);
                }
            })
            .catch(error => {
                authStore.loginError$.next(true);
                console.error(error);
            });
    }

    private loginRequest: Msal.RedirectRequest = {
        scopes: ['openid'],
    };

    public login() {
        this.msalInstance.loginRedirect(this.loginRequest);
    }
```

## Expected behavior
The tokenResponse in the handleRedirectPromise should contain the token

## Browsers/Environment
- [x] Chrome
- [ ] Firefox
- [x] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by sameerag** [comment]
@abf7d Can you please read the documentation on `handleRedirectPromise` [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md#i-dont-understand-the-redirect-flow-how-does-the-handleredirectpromise-function-work) and let us know if you are still seeing this issue?

cc @tnorling to track this if a follow up is needed.

**Comment by abf7d** [comment]
> Please ensure handleRedirectPromise has resolved before invoking any other MSAL method. If your app was not loaded as a result of a redirect operation handleRedirectPromise will immediately return null.

I removed all other calls using my msalInstance object.  I'm still getting null for my response. I switched navigateToLoginRequestUrl to false as the redirectUri is the same as the login request url.  This is just a random question... looking at Azure Active Directory, I see the registration for my client id that I'm using is listed under "Owned Applications". Does that impact anything?

**Comment by tnorling** [comment]
@abf7d Could you implement the [msal logger](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/configuration.md#using-the-config-object) and paste the log messages here?

**Comment by abf7d** [comment]
I think I have implemented the msal logger (see MSAL Configuration above, loggerCallback). I get no messages in my console. 

I looked under the application tab in the debugger and have found a number of entries:
msal.<other text>nonce.id_token<other text>
msal.<other text>request.params
msal.<other text>request.origin
msal.<other text>request.state<other text>
msal.<other text>authority<other text>

**Comment by tnorling** [comment]
@abf7d Could you capture your network traffic when trying to login and email it to me? Email is on my profile. There are a couple reasons `handleRedirectPromise` might return null and the immediate obvious answers would have logged to the console. I'll make a note to add some more logging throughout `handleRedirectPromise`

In the meantime, while I look at the network traces it may be helpful if you can debug and determine where `null` is being returned.

**Comment by abf7d** [comment]
I found the problem. I had my base url redirecting to my /home route. So whenever you open the base route the app is redirected. From this route, the request is made. I needed to add the redirect uri for the /home route to my AAD app registration, commented out the redirectUri in my b2c configuration and set navigateToLoginRequestUrl to true. I debugged the handleRedirectPromise code and when it redirected, the hash in the redirect url was not cleared out. I put a breakpoint in in the handleRedirectPromise and the id_token is coming back.

**Comment by abf7d** [comment]
One last issue.  The access_token is not coming back. In msal.js 1.3 and implicit flow I needed to call acquireTokenSilent to retrieve the access token. Do I need to call acquireTokenSilent here? I saw something that mentioned calling Microsoft Graph for an access token. Do I need to do that? I'm also interested in how to get the refresh token. In one of the sampes, it doesn't look like they are explicitly retrieving the access token after getting the id_token. Any direction you can give would be appreciated.

**Comment by tnorling** [comment]
Resolved offline
