### ISSUE TITLE
navigateToLoginRequestUrl: true - For Dyanmic pages

### ISSUE THREAD

**Issue by jrmcdona** [AzureAD/microsoft-authentication-library-for-js#2421]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `@azure/msal-browser@2.x.x`

## Description
I have dynamic pages, like a blog for example.  If the user tries to access a blog and they are not signed in, we are redirecting them to sign in.    Therefore, I want to use navigateToLoginRequestUrl: true.   However, I am getting errors that my redirect URL is not valid.

I have a first party app in the First party portal.   Can we configure wildcard redirect URLs in the FPP?  I do not think we can and if not how should I handle this scenario.

Thanks

**Comment by tnorling** [comment]
@jrmcdona You should set your `redirectUri` in MSAL to something that is registered in the portal and implement `handleRedirectPromise` on that page as well. After signing in AAD will redirect you to your `redirectUri` and from there `handleRedirectPromise` will redirect you a 2nd time to the original page that made the request (this is the part that `navigateToLoginRequestUrl: true` enables)

**Comment by sameerag** [comment]
@jrmcdona You can also find the relevant documentation [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md#i-dont-understand-the-redirect-flow-how-does-the-handleredirectpromise-function-work)

**Comment by jrmcdona** [comment]
@tnorling so it needs to be on a page different from our primary  handleRedirectPromise?

I don't think this is going to work I have an Angular app.  My handleRedirectPromise is in the app.component.ts right now so it will load everytime the Angular app loads, there for it is going to load twice if I add handleRedirectPromise  in yet another Angular route.

When I set navigateToLoginRequestUrl = true in my current App is seems to get caught in a login loop.

**Comment by tnorling** [comment]
@jrmcdona Yes. It's fine if it loads twice (this is actually intentional) because the internal logic will ensure that it only processes the redirect response on the route that the response is intended for. It determines this based on the `navigateToLoginRequestUrl` flag. If this is set to true `handleRedirectPromise` will redirect to the original route that initiated the request. If it's set to false or you're already on the original route it will just process the response.

> When I set navigateToLoginRequestUrl = true in my current App is seems to get caught in a login loop.

Can you do some debugging to determine what's causing your loop? Is your app calling login again before completing the redirect to your other route?

**Comment by jrmcdona** [comment]
@tnorling  I think I see the issue here.    We are using auth guards on our Angular routes.   The Auth guard is getting called before the user has been authenticated during the redirect process and therefore triggers another loginRedirect request and starts a loop.  

It then errors out saying there is already an interaction in progress.  

I am having some difficulty thinking of a way to get around this so far.  Besides moving Auth guards altogether and coming up with some at the page level that check for auth but that isn't ideal.

**Comment by jrmcdona** [comment]
@tnorling  is there a way I can capture the URL  where MSAL is going to redirect to?  Because if so then maybe I can get the URL and do something on my own with it.   Not sure what but trying to come up with some ideas.

**Comment by jrmcdona** [comment]
Actually,  maybe MSAL.JS should not perform a redirect until the callback has completed.
