### ISSUE TITLE
Logout is not working properly

### ISSUE THREAD

**Issue by Shyam268** [AzureAD/microsoft-authentication-library-for-js#2422]
Packages Used:
   "msal": "^1.3.4",
    "@azure/msal-angular": "^1.0.0",
issue:
User cannot logout it struct at logout session page:
![image](https://user-images.githubusercontent.com/30112490/95956763-63baed00-0e1c-11eb-968b-8ec610106243.png)

Code to reproduce:
appsetting.json

```
{
  "appsettings":{
     "authentication":{
      "authority": "https://login.microsoftonline.com/tenentId",
      "clientId":"1112222-2232-235456-21311",
      "cacheLocation": "localStorage"
      },
      "Service1":{
         "url" : "https://localhost:5001",
         "scope"  : ["https://{mytenent}.onmicrosoft.com/1231-321313-13233311/CRUD"]
      },
      "redirectUri":"http://localhost:4200/",
      "postLogoutRedirectUri": "http://localhost:4200/",
  }
}
```
msalConfig.ts
```

export function MSALConfigFactory(config: AppConfigService): Configuration {
  const appSettings = config.getConfig(config.APP_SETTINGS);
  const authentication = appSettings.authentication;
  const auth = {
      auth: {
          clientId: authentication.clientId,
          authority: authentication.authority,
          redirectUri: appSettings.redirectUri,
          postLogoutRedirectUri: appSettings.postLogoutRedirectUri,
          navigateToLoginRequestUrl: true,
          validateAuthority: true,
      },
      cache: {
         cacheLocation: 'localStorage'
      }
  };
  return (auth as Configuration);
}
```
logoutComponet.ts
  logout() {
    this.authService.logout();
  }

app registration settings:

![image](https://user-images.githubusercontent.com/30112490/95956884-91a03180-0e1c-11eb-8116-f5567a69dda4.png)

i am able to call web api but logout not working properly

**Comment by sameerag** [comment]
@Shyam268 Can you share your logs and any fiddler trace you can collect? Would like to especially see what is happening once you call `logOut` in `msal-browser`. 

@hpsin Is there any known issue on the server end where post logout URI redirect is not triggered? I remember MSA accounts has this issue but unsure if it is fixed.

**Comment by hpsin** [comment]
![image](https://user-images.githubusercontent.com/1666363/96048927-2a8a7900-0e2c-11eb-9740-c867f7bb8774.png)

We won't send you to the logout redirect URI if the logout redirect URI is not registered. That's a dangerous open redirector avenue.

**Comment by sameerag** [comment]
Thanks @hpsin. 

@Shyam268 Can you please configure your logout redirect uri for your app and let us know if it works as expected?

**Comment by Shyam268** [comment]
I have mentions "postLogoutRedirectUri": "http://localhost:4200/" i think this should work right?. even @sameerag I tried logout redirect uri still it is not working.

**Comment by hpsin** [comment]
Your app registration has to also have it filled in. See the picture I posted above - your app does not have a logout redirect uri registered, so when your code attempts to use it, we reject it since no logout redirect uri matches.

**Comment by Shyam268** [comment]
logout redirect uri is also not help full.

**Comment by Shyam268** [comment]
I have tried this example https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi
I have registered app in b2c tenent and  replaced client id, tenent id(example: https://login.microsoftonline.com/{12-41561-546541-465641}) in json file 
then i can reproduce this issue. i.e logout is not working properly, page struck "it is good idea to close all browsers"

**Comment by hpsin** [comment]
If this is for B2C then alternate rules may apply.  @sameerag  do you know who a good B2C contact would be?

**Comment by sameerag** [comment]
@nickgmicrosoft Can you please help with this?

**Comment by Shyam268** [comment]
no console error. i am able to login when call msal.logout() , the user is not logout properly the page stuck at "It is good idea to close all browers window"

please have a look into the fiddler 

[Not_Working_sample.zip](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/5398996/Not_Working_sample.zip)

this trace contains both traces one is working with azure Ad and other case not working with Azure Ad B2C

**Comment by Naakhta** [comment]
This is happening even in the simplest version of the sample - https://github.com/Azure-Samples/active-directory-javascript-singlepageapp-angular. 

For us the scenario is something like this.
Case1: Registered with B2C tenant.

**External AAD user - MSA -   Doesn't redirects to application home page after logout.**
Local AAD user - naakhtab2c@nadimb2ctenant.onmicrosoft.com - Gets redirected to application home page.

Case 2: Registered with normal AAD tenant.

Works with both external AAD(MSA) and AAD user.
==

**Comment by nickgmicrosoft** [comment]
So this seems to apply only to MSA as an IDP? For this scenario, there are **two** registered applications:
1) One for MSA (as described [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/identity-provider-microsoft-account)); used for IDP federation
2) One for the application that's signing in/signing out users using Azure AD B2C

Can you upload or share a picture of your manifest file for both? Would help clarify if this is an app registration issue rather than an MSAL issue.

**Comment by Shyam268** [comment]
@nickgmicrosoft This is critical issue now for us  and blocking production deployment

**Comment by nickgmicrosoft** [comment]
@Shyam268 , can you help me clarify your scenario:
- What type of users are logging into this application? Are they using Azure AD B2C user flows/custom policies at all or just only using login.microsoftonline.com?

**Comment by Shyam268** [comment]
This happens only with MSA accounts and i did not use any user flows or any policies.

**Comment by jasonnutter** [comment]
@Shyam268 Can you please confirm the following settings:

- Logout uri is https
- Logout uri is registered as a reply uri in the portal (even if you don't use it as a reply uri)
- Logout uri is registered as the post logout url (unfortunately, the portal doesn't allow non-https logout uris)
- Logout uri is set as `auth.postLogoutRedirectUri` in msal (and you call `logout`).

**Comment by Shyam268** [comment]
All the settings are configured properly. but
still having the same issue

app registraion: 

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/30112490/98202176-7a55ef00-1f57-11eb-8a1a-c12dfe95b576.png)


config.json 

```
{
    "appsettings": {
        "authentication": {
            "clientId": "123-456-4564-54561-5845",      
            "authority": "https://login.microsoftonline.com/123-654561-4866-68511-4546"
            "cacheLocation": "localStorage"
        },
     
        "redirectUri": "https://myapp.azurewebsites.net/",
        "postLogoutRedirectUri": "https://myapp.azurewebsites.net/",
    }
}
```

msal-confiration.ts

```
export function MSALConfigFactory(config: AppConfigService): Configuration {
  const appSettings = config.getConfig(config.APP_SETTINGS);
  const authentication = appSettings.authentication;
  const auth = {
      auth: {
          clientId: authentication.clientId,
          authority: authentication.authority,
          redirectUri: appSettings.redirectUri,
          postLogoutRedirectUri: appSettings.postLogoutRedirectUri,
          navigateToLoginRequestUrl: false,
          validateAuthority: false,
      },
      cache: {
          cacheLocation: authentication.cacheLocation
      }
  };
```

**Comment by Shyam268** [comment]
@nickgmicrosoft  Any updates on this ticket.

**Comment by jasonnutter** [comment]
Closing, as the last remaining issue is related to the B2C service, and not MSAL.js. Please file a support ticket with the B2C team by following the instructions here: https://docs.microsoft.com/azure/active-directory-b2c/support-options

They can help you out further, they may ask for a public repro link or additional data. You can also link this Github issue in the support request.
