### ISSUE TITLE
How do i configure msal angular service which is wrapper service of deferent services 

### ISSUE THREAD

**Issue by Shyam268** [AzureAD/microsoft-authentication-library-for-js#2423]
Used packages versions:
"@azure/msal-angular": "^1.0.0",
"msal": "^1.3.4",

json example:

```
     "Service1": {
          "url": "https://service-xyz-abc.azurewebsites.net",
          "scope": [
              "https://{mytenent}.onmicrosoft.com/1111111-111-1111-1111-1111111111/CRUD"
          ]
      },
      "Service2": {
          "url": "https://service-xyz-abc.azurewebsites.net",
          "scope": [
             "https://{{mytenent}}.onmicrosoft.com/222222-2222-222-22222-222222/CRUD"
          ]
      }
	  
	  "Service3": {
          "url": "https://service-xyz-abc.azurewebsites.net",
          "scope": [
             "https://{{mytenent}}.onmicrosoft.com/33333333-333333-3333-33333-33333/CRUD"
          ]
      }
	  
```
	  
msal-coniguration.ts
```
export function MSALAngularConfigFactory(config: AppConfigService): MsalAngularConfiguration {
   const appSettings = config.getConfig(config.APP_SETTINGS);
   const service1 = Service1;
   const service2 = Service2;
   const service3 = Service3;
   const protectedResourceMap: [string, string[]][] = [
    [service1.url, service1.scope],
    [service2.url, service2.scope],
    [service3.url, service3.scope],
   ];
   const auth = {
      popUp: false,
      protectedResourceMap: protectedResourceMap,
  };
  return (auth as MsalAngularConfiguration);
}	 
``` 
we have deferent service for deferent models instead of exposing all services  we are using wrapper service for these services.
the wrapper service(https://service-xyz-abc.azurewebsites.net) which will redirect to intended endpoints based on the route.	  

when we used respective service urls and their scope ids it worked as expected but as we replaced the service url with wrapper url, we are able able to access service3 and for 
service1 and service2 tokens are generated for service3 which is why service1 and service2 are failing

**Comment by jasonnutter** [comment]
@Shyam268 Different ways to dynamically configure MSAL Angular are documented here: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/configuration.md

Is this what you are looking?

**Comment by Shyam268** [comment]
i think my case is different. we are using one wrapper service instead of exposing all services. the wrapper service which will redirect to intended endpoints based on the route.
