### ISSUE TITLE
Is there any way to only change password instead of forgot password?

### ISSUE THREAD

**Issue by Shyam268** [AzureAD/microsoft-authentication-library-for-js#2424]
Is there any way to only change password instead of forgot password?

used packages versions:
"@azure/msal-angular": "^1.0.0",
"msal": "^1.3.4",

I have integrated msal and signup, sign and forgot policies are working fine.
but i have to give support to user to change password after login.

simillar issue https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp/issues/76

**Comment by derisen** [comment]
[Duplicate issue](https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp/issues/76). Closing.
