### ISSUE TITLE
Confusion around loginPopup

### ISSUE THREAD

**Issue by nfpiche** [AzureAD/microsoft-authentication-library-for-js#2434]
## Library
- [x] `msal@1.4.1`

## Description
I am on page `myapp.com/sub-route` with potentially infinite sub-routes (in a SPA) and authenticate via `UserAgetApplication.loginPopup`.  We have an authorized `redirectUri` that is set to `myapp.com/specfic-route`.  I am unsure what is supposed to happen when the `loginpopup` hits that authorized redirectUri.  Currently it just hits that page, the popup stays open forever and I am never authenticated on the original page.  Is there something that I need to do when `myapp.com/specific-route` is hit? I tried this [issue](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/174) but it did not have an effect.

I'm not sure if I am supposed to do something like [this](https://docs.microsoft.com/en-us/azure/active-directory/develop/reply-url#use-a-state-parameter) but I would not think so as I am using the popup specifically to not use redirects.

**Comment by sameerag** [comment]
@nfpiche The most common case we have seen where a `popup` can potentially stay open is if the `redirectUri` set in the `popup request` has a different domain than the webpage that initiated the `popup`. Can you please verify this?

Please provide your MSAL `configuration` and the `request` for us to further help you.

**Comment by nfpiche** [comment]
Thanks for the quick response @sameerag 

Here is what our code looks like, this request is being initiated from `https://local.app.com:33221/some/other/route`.  Could the addition of the port have an effect?

```javascript
const MSAL_CONFIG = {
  auth: {
    clientId: config.MSAL_CLIENT_ID,
    navigateToLoginRequestUrl: false,
    redirectUri: 'https://local.app.com/specific-route'
  },
  cache: {
    cacheLocation: "localStorage",
  },
};

const msal = new UserAgentApplication(MSAL_CONFIG);
const AUTH_OPTIONS = { scopes: ["calendars.read", "calendars.readwrite"] };

 try {
    await msal.loginPopup(AUTH_OPTIONS);
  } catch (e) {
    return err(OutlookError.from(e));
  }
```

**Comment by sameerag** [comment]
I think so: Same origin policy  RFC6454 [here](https://tools.ietf.org/html/rfc6454#section-3.2) specifies that if a different `port` is used, it is not considered as `Same origin`.

**Comment by jasonnutter** [comment]
@sameerag Correct, addresses with different ports are considered different origins.

**Comment by nfpiche** [comment]
That definitely seems like the culprit, let us do some reconfiguration on our and I'll report back, thanks for the assistance.

**Comment by nfpiche** [comment]
Definitely it, thanks again, always hate an issue that only crops up in dev mode 😅
