### ISSUE TITLE
MSAL Angular with ASP.NET core Auth Guides (updated to match current Azure)

### ISSUE THREAD

**Issue by whittssg** [AzureAD/microsoft-authentication-library-for-js#2437]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Are there any tutorials that explain how to get this working with asp.net core? Say angular frontent using msal and asp.net core backend with AddAzureADBearer. I tried all of the ones i could find on google and couldnt get any of them to work. 

MSAL on the front end works fine but i get bearer errors on the back end, invalid authority, invalid issuer and even after disabling those checks i just get a 401 with no error. I think ive gone through 4 or 5 tutorials on how to setup the backend API and front end in Azure and they are all completely different. Please tell me you have a standard one hidden somewhere that matches what azure currently displays ?

Thanks,

**Comment by derisen** [comment]
@whittssg would [this sample](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi) help with your case?

**Comment by whittssg** [comment]
> @whittssg would [this sample](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi) help with your case?

Yeh that helped. Thanks alot.
