### ISSUE TITLE
Access token not resolved, although acquired

### ISSUE THREAD

**Issue by johannes-z** [AzureAD/microsoft-authentication-library-for-js#244]
I've tried multiple ways of getting this to work, and now the library won't even fetch the access_token anymore, although it's retrieved.

I'm using local storage, and after `loginPopup` there is a `msal.urlHash` key with the `#access_token=...` as value. 

This is the code I use, which is basically exactly the same as the example of the `README.md`. The `token` of the `loginPopup` is acquired, and then nothing happens, but popups popping up once or twice before closing again. Am I doing something wrong here?

```js
  return new Promise(resolve => {
    clientApplication.loginPopup(APPLICATION_CONFIG.graphScopes).then(function (token) {
      console.log('token', token)

      var base64Url = token.split('.')[1]
      var base64 = base64Url.replace('-', '+').replace('_', '/')
      var decodedToken = JSON.parse(window.atob(base64))

      console.log(decodedToken)

        // Login Success
      clientApplication.acquireTokenSilent(APPLICATION_CONFIG.graphScopes).then(function (accessToken) {
        console.log('1', accessToken)
        localStorage.token = accessToken
        resolve(accessToken)
            // AcquireToken Success
      }, function (error) {
            // AcquireToken Failure, send an interactive request.
        clientApplication.acquireTokenPopup(APPLICATION_CONFIG.graphScopes).then(function (accessToken) {
          // updateUI()
          console.log('2', accessToken)
          localStorage.token = accessToken
          resolve(accessToken)
        }, function (error) {
          console.log(error)
        })
      })
    }, function (error) {
      console.log(error)
    })
  })
```

Also, the expiration date of the token seems to be 1 hour. Does that mean, that I'd get another popup every other hour of inactivity? Why can't I just get a token silently without user interaction (once the app is authorized). This makes consuming MS Graph APIs very cumbersome in my opinion...

**Comment by rohitnarula7176** [comment]
@johannes-z The library should be able to fetch the token as others are also using the same version to call the graph API's with no issues. Can you attach a copy of your full code where you login and then call the graph me endpoint for instance. Also the access_tokens are valid for an hour in implicit flow and just before it expires, you need to send another silent request to renew it. After authorization, the acquireTokenSilent will only work if you have consented for the scope at least once by calling acquireTokenPopup or acquireTokenRedirect.

**Comment by rohitnarula7176** [comment]
@johannes-z Closing this issue. Please reopen once you have a code repro for this issue.
