### ISSUE TITLE
Azure Dogfood accounts(***@live.com) not found in login.windows-ppe.net

### ISSUE THREAD

**Issue by RichardSunMS** [AzureAD/microsoft-authentication-library-for-js#2441]
## Library
- [ ] `@azure/msal-angular@1.4.1`

## Framework
MSAL in Angular

## Description
We are having a app which is still using ADAL which integrating Azure AD and calling apis(Microsoft Graph & Azure Resource Manager), and I am evaluating moving to MSAL. 

I tried to use the sample code for building a test app following: https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-angular.
I used our 1st party app PPE environment to test, and it works well for @microsoft.com df accounts, and I can get the graph/me and ARM tenants back, but I failed to login with some Azure DF accounts (which created for Azure DF and can login: https://df.onecloud.azure-test.net/), the accounts look like ***@live.com.

During the login, it goes to: https://login.live-int.com/, which not same as Azure DF portal: https://login.live.com/ when I input my ***@live.com account name.

Please help.

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Browsers/Environment
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by sameerag** [comment]
@hpsin Can you help here?

**Comment by hpsin** [comment]
There's an extant bug here I believe, where we run ifexists against PROD and move to PPE.  Note you have to use /organizations to use MSA with ARM - please use that here, and it should move you to PROD MSA correctly. 
Please mark this as internal, as these don't work for public users.

**Comment by sameerag** [comment]
@hpsin Are we tracking this in ADO?

**Comment by hpsin** [comment]
We need a repro URL.  @richardsunMS please share the login URL that appears in the browser bar during login (login.windows-ppe.net/...?client_id=....)

**Comment by tnorling** [comment]
@RichardSunMS Is this still an issue? If so can you provide the login url to @hpsin?
