### ISSUE TITLE
Issues in making silent MSAL calls to fetch access token.

### ISSUE THREAD

**Issue by Naakhta** [AzureAD/microsoft-authentication-library-for-js#2442]
MSALJS 1.4.0

We are using SAML based authentication in our front end web page and then in the same page we are using MSALJS to fetch the access token silently using the existing session which has been established by SAML.

myMSALObj = new Msal.UserAgentApplication(msalConfig),

 requestObj = {scopes: ["user.read"] };

 function base64url(source) {

 encodedSource = CryptoJS.enc.Base64.stringify(source);

 encodedSource = encodedSource.replace(/=+$/, '');

 encodedSource = encodedSource.replace(/\+/g, '-');

 encodedSource = encodedSource.replace(/\//g, '_');

 return encodedSource;

 }

 ( function loadChatbot() {

 let urlParam = "";

 myMSALObj.acquireTokenSilent(requestObj).then(function (tokenResponse) {

 console.log("RAW AUZRE RESPONSE");

 console.log(tokenResponse);

It was working well with MSAL.JS 1.0.0 however moved to 1.4.0 when we started getting the token renewal issues in the older version. 

**Issues in 1.4.0:**

MSAL is asking for interactive login even though the first layer of SAML authentication is working well hence we expect that MSAL will read the current SAML session and do the silent token call.

**Troubleshooting performed:**

When we have hard coded the login_hint in our code it works well with Chrome and Edge however fails with the same token renewal error with IE – Screenshots attached.

**requestObj = {scopes: ["user.read"],login_hint:emailID };**
IE – version 11.1457

**Observation**
When we use the interactive method of acquiring the token then it doesn't give any prefilled account to choose from. We receive a screen where it expects us to input the username and password manually.
Shouldn't it be prefilled? Application has already established a session in the first SAML auth.

Full code and error is attached.

**Questions:

Why the SSO is not working if we don't use the login_hint explicitly? 
Why the IE still failing even we pass the login_hint?**

![error](https://user-images.githubusercontent.com/53153647/96221032-71e94480-0fa7-11eb-9725-08a3a1990e50.jpg)
[Erimatch UAT 22 Sept.txt](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/5389685/Erimatch.UAT.22.Sept.txt)

**Comment by sameerag** [comment]
@Naakhta 
> Why the SSO is not working if we don't use the login_hint explicitly?

* SSO is never designed to work without `login_hint` prefilled. The idea of SSO is that the user established his session already and MSAL is designed to identity the session by passing `sid` or `login_hint` to the service.

> Why the IE still failing even we pass the login_hint?**

* IE issue could be because of trusted zones, can you please check these [docs](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Known-issues-on-IE-and-Edge-Browser) and let us know if the workarounds helped you.

> When we use the interactive method of acquiring the token then it doesn't give any prefilled account to choose from. We receive a screen where it expects us to input the username and password manually.
Shouldn't it be prefilled? Application has already established a session in the first SAML auth.

Is this seen only for IE?

**Comment by AyushMahendru** [comment]
Hi 
The workarounds mentioned in https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Known-issues-on-IE-and-Edge-Browser have been tried out. 

cache:{
               cacheLocation: "localStorage",
               storeAuthStateInCookie:is_ie
              }

Also, https://login.microsoftonline.com is in trusted sites. 

Would the issue with PopUp Blockers be applicable here ?

**Comment by cybersuv** [comment]
The interactive authentication for already acquired SAML token is not an option here @Naakhta . We are expecting as per doc that, MSAL will work with underlying token and login_hint provided. Why even that is not working with IE 11 ? @sameerag any idea further ?

**Comment by cybersuv** [comment]
@sameerag , can we have a working session to show you the problem further and get better suggestion ?

**Comment by DarylThayil** [comment]
@AyushMahendru just small nit in the example you provided, are you setting storeAuthStateInCookie to true boolean?

**Comment by DarylThayil** [comment]
Also curious the error you are getting back

**Comment by DarylThayil** [comment]
Curious if this is a regression in 1.4.x can you try v1.3.x and see if the same issue persists?

**Comment by AyushMahendru** [comment]
> @AyushMahendru just small nit in the example you provided, are you setting storeAuthStateInCookie to true boolean?

yes if the Browser is internet explorer

**Comment by AyushMahendru** [comment]
![Error](https://user-images.githubusercontent.com/71528211/96734522-ef072600-13ba-11eb-8c19-6eead9cbe1d0.jpg)
