### ISSUE TITLE
Facing Issue with cache clear (ctrl+shift+del) unable to retrieve idtoken and user detail for the first time 

### ISSUE THREAD

**Issue by Igadde** [AzureAD/microsoft-authentication-library-for-js#2443]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.
Facing Issue with cache clear (ctrl+shift+del) unable to retrieve idtoken and user detail for the first time 

1. Redirect to login page after cache clr 
2. Enter user details (correct) and click on submit idtoken not getting from msal service.
3. _oauthservice not returning user object and idtoken and its returning to the login page again .
4. if i try again with same credentials able to login. 

can you please check this once 

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.0.1`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
Angular 7
## Description
There was a general error in Client-side.
Error: Uncaught (in promise): TypeError: Cannot read property 'idToken' of null
TypeError: Cannot read property 'idToken' of null
    at e.getIDToken (https://kiddecloud-dev.azurewebsites.net/main.9c002ea969467c3555dd.js:1:1215165)
    at e.checkUserExists (https://kiddecloud-dev.azurewebsites.net/main.9c002ea969467c3555dd.js:1:1217385)
    at e.canActivate (https://kiddecloud-dev.azurewebsites.net/main.9c002ea969467c3555dd.js:1:3056149)
    at https://kiddecloud-dev.azurewebsites.net/main.9c002ea969467c3555dd.js:1:1763298
    at e._subscribe (https://kiddecloud-dev.azurewebsites.net/main.9c002ea969467c3555dd.js:1:2424384)
    at e._trySubscribe (https://kiddecloud-dev.azurewebsites.net/main.9c002ea969467c3555dd.js:1:210869)
    at e.subscribe (https://kiddecloud-dev.azurewebsites.net/main.9c002ea969467c3555dd.js:1:210655)
    at e.call (https://kiddecloud-dev.azurewebsites.net/main.9c002ea969467c3555dd.js:1:2779578)
    at e.subscribe (https://kiddecloud-dev.azurewebsites.net/main.9c002ea969467c3555dd.js:1:210527)
    at https://kiddecloud-dev.azurewebsites.net/main.9c002ea969467c3555dd.js:1:779721
Navigated to https://ccskidde.b2clogin.com/ccskidde.onmicrosoft.com/b2c_1a_signup_signin/oauth2/v2.0/authorize?response_type=id_token&scope=https%3A%2F%2Fccskidde.onmicrosoft.com%2Fkiddeapi%2Fuser_impersonation%20openid%20profile&client_id=10cec170-c41f-452b-a73d-23f1ea0d2e4b&redirect_uri=https%3A%2F%2Fkiddecloud-dev.azurewebsites.net&state=b7f59433-ab67-4046-9439-8c16fa439b0e&nonce=4b5a12fe-cf16-4263-946a-7b0b13ef7856&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=0.2.2&client-request-id=dadaa29a-b2aa-4e88-95c5-c968aab0975e&prompt=select_account&response_mode=fragment
## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
1. Redirect to login page after cache clr
2. Enter user details (correct) and click on submit idtoken not getting from msal service.
3. _oauthservice not returning user object and idtoken and its returning to the login page again .
4. if i try again with same credentials able to login.
```

## Expected behavior
it should login first time 
## Browsers/Environment
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by sameerag** [comment]
@Igadde Can you please share the `msal` logs for your use case? Also please share the `configuration` and `request` code snippets for us to check why you are seeing this?
