### ISSUE TITLE
Samples links are broken

### ISSUE THREAD

**Issue by MarkZuber** [AzureAD/microsoft-authentication-library-for-js#2444]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Documentation location
- [ ] MSAL.js Github Wiki

## Description

https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-node#samples

This page has some links below it to samples.  Those links are broken.  They should end up here (as an example): https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples

I believe they're set to blob/dev/samples instead of tree/dev/samples.

**Comment by sameerag** [comment]
@MarkZuber Thanks for bringing to to our notice. #2448 is raised to close this. More docs on samples are coming soon.
