### ISSUE TITLE
Azure Active Directory External Identities - Self-Serve Sign-Up and Roles

### ISSUE THREAD

**Issue by gidich** [AzureAD/microsoft-authentication-library-for-js#2445]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ X] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

I am working to set up AAD External Identities with Self-Serve Sign-Up and Roles, I have created an App Registration, and edited the Manifest to include roles.

When setting up the MSAL authority option I see two choices (the B2B option doesn't seem appropriate) 

- Common Authority: `https://login.microsoftonline.com/common`

- Tenant Authority: `https://login.microsoftonline.com/${tenantId}`

### Observed Behavior
The impact of the choice between the two is distinct:

- **Common Authority**:
  - Self Serve Sign Up: 
    - Facebook Users: Can sign up
    - Email: (New user with no AD account): Can Sign up
  - AAD Portal: 
    - Users do **not** show up
    - **Cannot** assign roles to users
  - MSAL Auth Token:
    - Auth Token:  Roles **not** present in AAD Auth Token

- **Tenant Authority**:
  - Self Serve Sign Up:
    - Facebook Users: Can sign up
    - Email: **Only** users with AAD Accounts can sign-up 
      - (New user with no AD account get an error asking to contact their admin)
  - AAD Portal: 
    - Users **do** show up 
    - **Can** assign roles to users
  - MSAL Auth Token:
    - Auth Token: Assigned roles present in AAD Auth Token

### Expectation:

The [AAD marketing page](https://azure.microsoft.com/en-us/services/active-directory/external-identities/) notes: 

> "Provide seamless and highly secure digital experiences for partners, customers, citizens, patients, or any other user outside your organization with the level of customization and control your business requires. Bring user directories together into one portal to manage access across organizational boundaries." 

Ideally the **tenant authority** would allow for new user sign-up for external identities **without** AAD Accounts (like the common authority) while also exposing those users in the directory and allowing for role assignment and roles to be exposed in AAD Auth Token - This would allow for Social Accounts / External AD Accounts / New Users (without AD) all to take advantage of self-serve sign-up from a single entry point.

Is there any way to configure MSAL + AAD/Azure together for this behavior to work as expected?
 
### Reference:
- All steps to configure the application and the application are open source:
  - [Application Setup and Configuration Documentation](https://ecfmg.gitbook.io/azure-serverless-quickstart/)
     - [AAD Configuration Details](https://ecfmg.gitbook.io/azure-serverless-quickstart/application-design/adding-authentication/aad-application)
  - [Source Code](https://github.com/simnova/sharethrift)

**Comment by sameerag** [comment]
@hpsin Can you take a look at this?

**Comment by jkdouglas** [comment]
@gidich - Could you provide a bit more clarity on what you mean when you say "allow users to sign up for external identities without AAD accounts"? What is the end state for that user and what type of identity are they using to sign up? Today, we support AAD accounts, Google, and Facebook. We are working to add more supported identity types to self-service sign up. Would love to hear your feedback on this.

The experience you describe for the tenanted endpoint is the expected behavior, where a user can sign up and actually gain a guest account in the directory and then use those accounts for things like role and group assignment.

**Comment by gidich** [comment]
With the Tenant Authority when a user attempts to create an account and chooses the "email" option, it's not apparent that in selecting "email" really means "Sign up using an email associated with an AAD account from this tentant or some other tenant".

![image](https://user-images.githubusercontent.com/1847881/96799341-eb7e9980-13d0-11eb-9659-05f43ecc52aa.png)


With the Tenant Authority if the user uses an email which is not associated with a tenant, they receive a rather cryptic error message stating to "contact their administrator", which to an end user would be very confusing.


![image](https://user-images.githubusercontent.com/1847881/96800366-2bdf1700-13d3-11eb-92ff-0ad073e759b7.png)


The same screen using the common authority allows a user to create a (a Microsoft Live) account on the fly and then sign in.

**Comment by gidich** [comment]
With the Common Authority, user can create a new account (as depicted below):

![image](https://user-images.githubusercontent.com/1847881/96802029-f805f080-13d6-11eb-90a5-f9f472b03cbd.png)

**Comment by gidich** [comment]
@jkdouglas  - The ideal end state would be to allow the tenant authority to permit a visitor without an AAD account to follow the same signup flow as the common authority ( that is - asking to create a password and continue to gain access to the application). In this way Facebook/Google/AAD/_and newly minted Microsoft accounts_ could all have access to the application through self-serve sign-up, and be administered in AAD giving admins ability to add these users to app roles which would be exposed through the access token permitting tiered access within the application.

The [Woodgrove Grocers demo](https://woodgroveb2cdemo.azurewebsites.net/) illustrates an experience I'd like to avoid which has 3 distinct logins:

![image](https://user-images.githubusercontent.com/1847881/97523544-f8732e00-1978-11eb-8de4-dcbcbefe018a.png)

Compare the Woodgrove Grocers Demo with [another example login](https://auth0.com/signup?&signUpData=%7B%22category%22%3A%22button%22%7D&email=undefined) which doesn't require 3 separate logins yet still supports creating an account on the fly as well as Microsoft login. This experience is a bit more what end users would expect, that is to have a single login experience regardless of how they're looking to interact with the service (e.g. customer/partner/etc).

![image](https://user-images.githubusercontent.com/1847881/97523780-7fc0a180-1979-11eb-92c4-9a00981d3a33.png)

**Comment by jkdouglas** [comment]
Thanks @gidich - this makes sense and I understand you are looking a better sign up experience with more options for users to sign up with. We have a few things on our roadmap that will help address some of your points, so stay tuned!

**Comment by gidich** [comment]
@jkdouglas  - I'd be willing to go under NDA to explore this further in beta w/you.

**Comment by gidich** [comment]
@jkdouglas is there any preview features I can test out?

**Comment by tnorling** [comment]
Closing as the discussion is no longer relevant to MSAL.js, please open a support ticket with AAD if you have further service related questions. Thanks!
