### ISSUE TITLE
Validate access token in backend

### ISSUE THREAD

**Issue by jeremyc11** [AzureAD/microsoft-authentication-library-for-js#2446]
## Library
- [ ] `@azure/msal-angular@1.x.x`

## Description
I 'm using MSAL angular to authenticate users using Microsoft login. After the authentication, I'm sending the access token to all requests to a API to execute actions in the backend. For security reasons, I need to assert in the backend the access token is a valid access token created by Microsoft. My question is how to validate the access token in the backend?

I'm using python 3.6 in my backend.

**Comment by derisen** [comment]
You should check the [documentation](https://docs.microsoft.com/azure/active-directory/develop/access-tokens#validating-tokens) on validating access tokens. There's also a web api code sample doing validation [here](https://github.com/Azure-Samples/ms-identity-python-webapi-azurefunctions/blob/f88a9466bb0ec0ce20c6742a21bc47a16e13652e/Function/secureFlaskApp/__init__.py#L71)
