### ISSUE TITLE
URL refreshes multiple times when using MSAL and calling the API. 

### ISSUE THREAD

**Issue by MayankKT** [AzureAD/microsoft-authentication-library-for-js#2450]
## Library
- "msal": "^1.4.1"

## Browsers/Environment
- [ ] Chrome
- [ ] Edge
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/28943234/96440750-07920780-1226-11eb-8eac-dabaf2c66c90.png)

**Comment by jasonnutter** [comment]
@MayankKT In SharePoint, you should not use MSAL directly. Please see this document for more information: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient
