### ISSUE TITLE
The "Need admin approval" login response won't throw error? [bug?]

### ISSUE THREAD

**Issue by kafka-yu** [AzureAD/microsoft-authentication-library-for-js#2454]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.4.1`  
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

I'm building a front-end app by using the masl 1.4.1.

1. Open the login popup, (note the scopes need to get admin consent to use)
2. Log in an account without admin permission to grant.
3. It shows "Need admin approval", which is correct.
4. Then click "Return to the application without granting consent"
5. Now the popup just closed, and I cannot get any response or errors in my code? I can not even know the `loginPopup` return or not, cause it doesn't throw an error or return response.

Does anyone know how to resolve this? Please at least give it a response (error or something is ok)

code snippets:
```js
try {
      this._updateLoginStatus(true);
      const authResponse = await this._msal
        .loginPopup({
          scopes: ['User.Read.All'],
        })
        .catch(() => {
           console.log('error?') 
        })
        .finally(() => {
          console.log('finshed?');
        });
```
The detailed logs:

![image](https://user-images.githubusercontent.com/3942409/96529631-4375ad00-12b8-11eb-867e-34684e5c178b.png)

It stops at "CLosing popup window", no errors return/reject back to the caller.

Thanks!

**Comment by kafka-yu** [comment]
I've fallbacked to 1.3.4 which works as expected.... what changed in v1.4.1 team?

**Comment by tnorling** [comment]
@kafka-yu Apologies for missing this. Is this still an issue? Have you tried version `msal@1.4.3`?

From the logs you shared it looks like there's some sort of state mismatch error which is causing the response/error to be routed through the `handleRedirectCallback`. It's not immediately clear why this is happening. Since you mentioned this arose when upgrading from 1.3.4 to 1.4.1 could you confirm whether or not this is a problem in `msal@1.4.0`? Is this happening in all browsers?

It would be helpful if you could reproduce this using one of our samples, without more information about how you've configured msal it's difficult to say what the problem might be.

**Comment by nfpiche** [comment]
We're seeing the same thing, where it throws as expected in 1.3.4 but 1.4.x does not.

Here is the gist of our code, we execute the `syncOutlook` function from a React SPA, the basic flow is
* Try to get token from localStorage
* If no token, do loginPopup (this is where it hangs)
* After logging in, try to get token again

Happy to try and do a full reproduction later on if this isn't helpful!

```javascript
const MSAL_CONFIG = {
  auth: {
    clientId: GLOBAL.msalClientId
  },
  cache: {
    cacheLocation: "localStorage" as const,
  },
};
const AUTH_OPTIONS = { scopes: ["calendars.read", "calendars.readwrite"] };

async function getToken(): Promise<string> {
  try {
    const token = await msal.acquireTokenSilent(AUTH_OPTIONS);
    return token.accessToken;
  } catch (err) {
    await msal.loginPopup(AUTH_OPTIONS); // We never make it past this line
    const token = await msal.acquireTokenSilent(AUTH_OPTIONS);
    return token.accessToken;
  }
}
```

**Comment by tnorling** [comment]
@nfpiche I have not been able to reproduce this behavior although from the logs shared above it looks like a state mismatch problem where the state coming back from the server response does not match what msal cached in local storage before making the request. It would be helpful if you could debug [this function](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/src/UserAgentApplication.ts#L1283) and figure out why there's a mismatch, in particular take a look at localstorage at the time this is run and see if the state cache values are present.
