### ISSUE TITLE
'AADSTS9002327' Can't retrieve token from an SPA

### ISSUE THREAD

**Issue by ursedaniel** [AzureAD/microsoft-authentication-library-for-js#2458]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

"@azure/msal-browser": "^2.3.1",

## Description
I'm trying to successfully authenticate using msal-browser package but after I enter the email and password needed in the microsoft popup i get an error when calling POST https://login.microsoftonline.com/{code}/oauth2/v2.0/token. 
The full error is: "AADSTS9002327: Tokens issued for the 'Single-Page Application' client-type may only be redeemed via cross-origin requests.

I will attach some screenshots that will showcase the settings I'm currently use.

Thanks!

![Screenshot 2020-10-20 at 16 54 46](https://user-images.githubusercontent.com/17604236/96596844-d1bc5400-12f5-11eb-9b03-8e6125894b3a.png)
<img width="990" alt="Screenshot 2020-10-20 at 17 10 44" src="https://user-images.githubusercontent.com/17604236/96602831-1a770b80-12fc-11eb-8947-ab9c76cb00c4.png">

<img width="806" alt="Screenshot 2020-10-20 at 16 59 39" src="https://user-images.githubusercontent.com/17604236/96596858-d54fdb00-12f5-11eb-9fee-190e3d219cf0.png">
<img width="568" alt="Screenshot 2020-10-20 at 17 10 33" src="https://user-images.githubusercontent.com/17604236/96602859-21058300-12fc-11eb-97f5-2148fed2389a.png">

**Comment by jasonnutter** [comment]
@ursedaniel MSAL Browser does not support any other response mode other than fragment, and as noted in the error, authorization codes acquired with MSAL Browser can only be redeem in the browser (MSAL Browser handles this for you automatically). This is a security feature to help protect the authorization code. If you do not pass `responseMode`, MSAL Browser will acquire the auth code and perform the trade for the IDT/AT/RT automatically.

**Comment by ursedaniel** [comment]
<img width="403" alt="Screenshot 2020-10-20 at 18 44 29" src="https://user-images.githubusercontent.com/17604236/96610583-75acfc00-1304-11eb-9536-07a378815e86.png">

@jasonnutter  thank you for your response. Even with responseMode: Fragment or without the parameter at all I still receive this error...

**Comment by jasonnutter** [comment]
@ursedaniel How are you invoking the `init` function? Is this being done server-side or client side?

**Comment by ursedaniel** [comment]
I tried it via 2 methods, one to load the config from the module level within a factory function, and the 2nd one is this one with the images (the init method is called from within an effect from ngrx state).
Both of the methods throw the same error.

I'll attach the screenshots with the other method, but same output.

<img width="579" alt="Screenshot 2020-10-21 at 10 18 40" src="https://user-images.githubusercontent.com/17604236/96686126-ccf3b080-1386-11eb-906c-41397a2c791a.png">
<img width="609" alt="Screenshot 2020-10-21 at 10 33 39" src="https://user-images.githubusercontent.com/17604236/96687725-f6154080-1388-11eb-9ae8-d5f5413302e6.png">
<img width="675" alt="Screenshot 2020-10-21 at 10 33 50" src="https://user-images.githubusercontent.com/17604236/96687737-f9103100-1388-11eb-9702-29e2e64ed4d3.png">


Also I've been looking over this example: https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular10-browser-sample. But I still get the same error even though I use the same files from msal folder and the same config injection.

**Comment by jasonnutter** [comment]
@ursedaniel Can you please share a Fiddler trace with me showing this behavior? Email is in my profile, thanks!

**Comment by sameerag** [comment]
@ursedaniel After some digging, we figured this error is thrown by the `server` in some cases where the expected headers are missing. We are trying for a repro to check why this may happen. Can you please track this issue with #2482?
