### ISSUE TITLE
Base64 Encoding not handlling special characters

### ISSUE THREAD

**Issue by eranotutamoh** [AzureAD/microsoft-authentication-library-for-js#246]
src/Utils  base64DecodeStringUrlSafe method
Polish Characters in given/family name fields of token are wrong when decoded. Actually works fine once I grabbed this from MDN to replace the window.atob / this.decode() method

//  https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding#The_Unicode_Problem

`base64DecodeStringUrlSafe = function (base64IdToken) {
    base64IdToken = base64IdToken.replace(/-/g, '+').replace(/_/g, '/');
    return decodeURIComponent(atob(base64IdToken).split('').map(function(c) {
      return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2);
    }).join(''));
  };`

**Comment by rohitnarula7176** [comment]
@eranotutamoh Can you provide an example for this issue with some test case.

**Comment by nehaagrawal** [comment]
@eranotutamoh  - This is a known issue with window.atob() that it can't support unicode charcaters. There are different ways to solve this issue as per the MDN article( https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding#The_Unicode_Problem) and below stackoverflow link.
https://stackoverflow.com/questions/30106476/using-javascripts-atob-to-decode-base64-doesnt-properly-decode-utf-8-strings
We need to discuss the fix in our team. I will report this as a bug for now.

**Comment by idrislab** [comment]
@nehaagrawal any update on this issue?

**Comment by navyasric** [comment]
Similar to #264
