### ISSUE TITLE
MSAL-Browser: Causing unrelated Jest / React unit tests to fail.

### ISSUE THREAD

**Issue by v-vrusse** [AzureAD/microsoft-authentication-library-for-js#2464]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
I currently switched our React / Typescript app from ADAL to MSAL v2.  Functionally, everything seems to be working correctly when it comes to logging the users in and calling protected APIs.  However, the unit tests for our package of common controls has started failing.  Oddly, only 1 of 128 tests fail; however, it is a different random component / test each time that fails with the following error message:
```
FAIL  packages/common/src/components/Table/Table.test.tsx
  ● Render Table › Should render Table component

    TypeError: Cannot read property 'cookie' of null

      at BrowserStorage.getItemCookie (packages/common/node_modules/@azure/msal-browser/src/app/PublicClientApplication.ts:262:63)
      at BrowserStorage.getItem (packages/common/node_modules/@azure/msal-browser/dist/index.js:6917:33)
      at BrowserStorage.cleanRequest (packages/common/node_modules/@azure/msal-browser/dist/index.js:7179:28)
      at PublicClientApplication.<anonymous> (packages/common/node_modules/@azure/msal-browser/dist/index.js:8756:33)
      at extendStatics (packages/common/node_modules/@azure/msal-browser/dist/index.js:182:17)
      at Object.next (packages/common/node_modules/@azure/msal-common/dist/index.es.js:23:12)
      at fulfilled (packages/common/node_modules/@azure/msal-browser/dist/index.js:65:24)
```
These components and tests don't have any msal interactions in them, so I'm at a bit of a loss as to why msal would be throwing this error.

In addition, I've already worked around this error in the one component that indirectly interacts with msal:
```
 FAIL  packages/common/src/components/WithServiceContext/WithServiceContext.test.tsx (16.088 s)
  ● WithServiceContext: › Render › Renders error message when error from config occurs

    BrowserAuthError: pkce_not_created: The PKCE code challenge and verifier could not be generated. Detail:TypeError: Cannot read property 'digest' of undefined

      at BrowserAuthError.AuthError [as constructor] (packages/common/node_modules/@azure/msal-common/dist/index.es.js:109:24)
      at new BrowserAuthError (packages/common/node_modules/@azure/msal-browser/src/error/BrowserAuthError.ts:91:9)
      at Function.BrowserAuthError.createPkceNotGeneratedError (packages/common/node_modules/@azure/msal-browser/src/error/BrowserAuthError.ts:109:16)
      at PkceGenerator.<anonymous> (packages/common/node_modules/@azure/msal-browser/src/crypto/PkceGenerator.ts:66:36)
      at step (packages/common/node_modules/@azure/msal-browser/dist/index.js:182:17)
      at Object.throw (packages/common/node_modules/@azure/msal-browser/dist/index.js:113:14)
      at rejected (packages/common/node_modules/@azure/msal-browser/dist/index.js:73:32)
```
by added the following to our test startup config:
``` js
Object.defineProperty(global.self, 'crypto', {
    value: {
        // Needed for azure-maps-control
        getRandomValues: arr => crypto.randomBytes(arr.length),
        // Needed for @azure/msal-browser
        subtle: {
            digest: jest.fn(),
        }
    }
});
```

Can you please provide guidance on what jest test environment setup and/or mocks we should have in place to be able to run unit tests without running into these seemingly unrelated errors in what must be the msal startup code.  It would also be extremely helpful if your repo included a React sample that included unit tests.

Please reach out to me (v-vrusse) on Teams if it would be easier to work directly with me.

**Comment by sameerag** [comment]
@tnorling Can  you please take a look at these `React` unit test case failure?

**Comment by tnorling** [comment]
@v-vrusse It looks like `document` is null in your test environment. You can either assign a global `document` or mock out the part of msal that is attempting to access it. From the stack trace it looks like `BrowserStorage.cleanRequest` is what's calling this. This function is called in each of the `acquireToken` and `login` APIs as well as `handleRedirectPromise`.

If you have additional questions about testing msal and how we do mocking you can find our unit tests [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-browser/test)

**Comment by v-vrusse** [comment]
> @v-vrusse It looks like `document` is null in your test environment. You can either assign a global `document` or mock out the part of msal that is attempting to access it. From the stack trace it looks like `BrowserStorage.cleanRequest` is what's calling this. This function is called in each of the `acquireToken` and `login` APIs as well as `handleRedirectPromise`.

@tnorling That's what I originally thought, so I used [this SO answer](https://stackoverflow.com/a/16194633/183195) to mock out `document.cookie` to no avail.  It's also my understanding that JSDOM implements document already which is used by Jest / React Testing Library to test that our components are rendering as expected.  It's also worth noting that I'm never calling `acquireToken`, `login`, nor `handleRedirectPromise` in the tests as I've already mocked out our authClient for use in the tests.

> 
> If you have additional questions about testing msal and how we do mocking you can find our unit tests [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-browser/test)

Yes, I already found your unit tests there; however, looking at [mochaSetup.js](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/test/mochaSetup.js) provided very little information beyond seeing that you are also using JSDOM and using a crypo library to add the `window.crypto` support instead of mocking it.  Meanwhile the tests themselves are pretty low level; hence why I was hoping you'd have a React sample with unit tests from the app level perspective.

My question still feels unanswered so can you please provide some more guidance?

**Comment by tnorling** [comment]
> It's also worth noting that I'm never calling acquireToken, login, nor handleRedirectPromise in the tests as I've already mocked out our authClient for use in the tests.

@v-vrusse Can you debug this? These APIs are the only entry points to getting the stack trace you shared above so if your tests aren't calling them directly maybe something else in your app is?

**Comment by v-vrusse** [comment]
Our app is wrapped by a React Context that has the authClient and httpClient in it.  This component ensures that the user is logged in before api calls are made via the httpClient which uses the authClient.  In unit tests, I initialize the authClient with a mocked version rather than the one that uses the msal apis:
```typescript
export const mockAuthClient: IAuthClient = {
    login: jest.fn(),
    logOut: jest.fn(),
    getUser: jest.fn(
        () => new Promise<IUser>((resolve) => resolve(mockUserInfo))
    ),
    getUserId: jest.fn(
        () => new Promise<string>((resolve) => resolve('userid'))
    ),
    isLoggedIn: jest.fn(),
    acquireToken: jest.fn(),
    authContext: jest.fn(),
};
```

The other components in the package I'm attempting to run tests for don't interact with msal nor the above React Context.  They simply exist in a package that has a dependency on `@azure/msal-browser`.

Sample generic component and tests:
```typescript
export const LoadingBase = (props: ILoadingProps): React.ReactElement => {
    const classNames = getClassNames(props.styles, { theme: props.theme ?? (getTheme() as ITHubTheme) });

    const intl = useIntl();

    return (
        <div className={classNames.root}>
            <Spinner
                ariaLabel={props.ariaLabel}
                label={props.label ?? intl.formatMessage({ id: MessageKey.loadingText })}
                labelPosition={props.labelPosition ?? 'bottom'}
                ariaLive={props.ariaLive ?? 'assertive'}
                data-testid="spinner"
            />
        </div>
    );
};

describe('Loading', () => {
    const props: ILoadingProps = {
        ariaLabel: 'Loading content',
    };

    it('should render loading', () => {
        const { container, getByTestId } = render(
            <TestIntlProviderContext>
                <Loading {...props} />
            </TestIntlProviderContext>
        );
        expect(container).not.toBe(undefined);
        expect(getByTestId('spinner')).not.toBe(undefined);
    });
});
```

As such, I'm not sure how I can debug further beyond the stack trace I included in my original post =/

**Comment by v-vrusse** [comment]
I finally tracked down the one test that somehow was still managing to grab the real context implementation rather than the mocked one.  Not sure how that test was one of the ones always passing while the tests that didn't use the context at all were the ones failing randomly =/

Closing since the test suite passes now; although, it would still be worthwhile if a React example with unit tests were added for the next person.
