### ISSUE TITLE
Authorization Code after redirect accessible in browser history

### ISSUE THREAD

**Issue by forellendev** [AzureAD/microsoft-authentication-library-for-js#2466]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
According to [best current practice](https://www.ietf.org/archive/id/draft-ietf-oauth-security-topics-16.html#name-credential-leakage-via-brow) by the ietf, authorization code leakage can happen if the code is accessible in the browser history. This is the case with msal-browser@2.x.x.. One of the two countermeasures is to utilize Authorization code replay prevention as described in [RFC6819]. My question is if this is used in the msal-browser@2.x.x library, or are there other measures taken against this problem?

**Comment by sameerag** [comment]
@forellendev The `authorization code` is protected by PKCE in order to prevent `replay`
