### ISSUE TITLE
MSAL Browser: Return specific error when invalid authority is provided

### ISSUE THREAD

**Issue by thoo1** [AzureAD/microsoft-authentication-library-for-js#2467]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.2.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
React
## Description
When logging a user into an invalid tenant (tenant id is wrong or does not exist), the login fails and an exception gets thrown to the console. This is an edge case where in our app, we allow user to specify the tenant id in the url. In the off chance they type in an invalid tenant id, this error gets thrown and our application hangs
## Error Message
Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined
    at e.replaceTenant (index.2089bb4e.js:2)
    at e.get [as authorizationEndpoint] (index.2089bb4e.js:2)
    at t.<anonymous> (index.2089bb4e.js:2)
    at index.2089bb4e.js:2
    at Object.next (index.2089bb4e.js:2)
    at index.2089bb4e.js:2
    at new Promise (<anonymous>)
    at N (index.2089bb4e.js:2)
    at t.getAuthCodeUrl (index.2089bb4e.js:2)
    at t.<anonymous> (index.2089bb4e.js:2)
## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Not sure
Version:

## MSAL Configuration
const publicClientApp = new PublicClientApplication({
      auth: {
        clientId: this.clientId,
        authority: this.authority,
        redirectUri: this.loginRedirectUri,
        postLogoutRedirectUri: this.postLogoutRedirectUri
      },
      cache: {
        cacheLocation: "localStorage",
        storeAuthStateInCookie: isIEOrOldEdge // https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1188#issuecomment-634281307
      },
      system: {
        tokenRenewalOffsetSeconds: 60,
        iframeHashTimeout: 30000, // iframe is used to refresh the refresh_token as it has a 24h lifetime
        loggerOptions: {
          loggerCallback: MsalAuthContext.msalLoggerCallback,
          piiLoggingEnabled: false,
          logLevel: LogLevel.Verbose
        }
      }
    });
    const handleRedirectPromise = publicClientApp
      .handleRedirectPromise()
      .then(response => {
        this.account = response ? response.account : this.getAccount();
        if (!this.account) {
          CoreLogger.trackEvent(TelemetryEventName.Core_MSALAuthContext_login);
          this.publicClientApp.loginRedirect({
            scopes: this.scopes,
            authority: this.authority,
            extraQueryParameters: this.safeRolloutQueryParams
          });
        }
      })
      .catch(error => {
        if (error) {
          this.trackError(error);
        }
      });

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Expected behavior
It should fail gracefully, throw an expected error so our application code can handle it
## Browsers/Environment
- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jasonnutter** [comment]
@thoo1 Seems like a reasonable improvement, thanks for the information.
