### ISSUE TITLE
MSAL Invalid_State error in IE11/Edge 

### ISSUE THREAD

**Issue by Chandu12x** [AzureAD/microsoft-authentication-library-for-js#247]
Hi Team,

We have a Consumer portal where MSAL authentication is implemented.

Currently we are getting  below errors in IE and Edge .It works fine in Chrome.

msal.error: "Invalid_state"
msal.error.description:"Invalid_state. state: 63e08f7b-512f-47c5-826d-737da5c9604e"

Our portal is used by multiple clients and we can't ask each and every client to add https://login.microsoftonline.com to trusted sites list.

We are using below files for MSAL Implementation.

<script src="https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.js" class="pre"></script> <script src="https://secure.aadcdn.microsoftonline-p.com/lib/0.1.3/js/msal.js"></script>

Could you please help us in resolving this issue.

Please let me know for any additional information needed.

**Comment by navyasric** [comment]
@Chandu12x This is an existing issue with the Edge and IE browsers. We have documented this in our ADAL library but this applies here as well. Currently, we only have the work arounds listed here: https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/Known-issues-on-Edge#issues

**Comment by nehaagrawal** [comment]
@Chandu12x  This is fixed and released in MSAL 0.2.2. Please check release notes for more details.
