### ISSUE TITLE
Consent error when acquire token for delegated api

### ISSUE THREAD

**Issue by cloudsere** [AzureAD/microsoft-authentication-library-for-js#2472]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.4.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
React

## Description
After signing in the user, I try to call `acquireTokenSilent` on scope of my delegated api, but I recevied a `invalid_grant: AADSTS65001: The user or administrator has not consented to use the application with ID`
And After I send an interact request to user, it says I have to login in as admin to consent.

## Error Message
`invalid_grant: AADSTS65001: The user or administrator has not consented to use the application with ID`
## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

I didn't try it with other versions, but I do request access token of the same scope, using the same clientId in ASP.NET using Microsoft.Identity.Web and it works.

## MSAL Configuration

```js
export const msalConfig: BrowserAuthOptions = {
  clientId: "{myid}",
  authority:
    "https://login.microsoftonline.com/{tenant}/",
};
```

## Reproduction steps

```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Browsers/Environment
- [x] Chrome
- [ ] Firefox
- [x] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by sameerag** [comment]
Is your application registered as a "SPA type" in the portal?
