### ISSUE TITLE
loginPop in Chrome navigate to application login page instead of Azure AD login

### ISSUE THREAD

**Issue by georgejdli** [AzureAD/microsoft-authentication-library-for-js#2475]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x ] `@azure/msal-browser@2.4.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework
react- 16.13.x

## Description
There is an intermittent issue in Chrome with `loginPopup()` where the popup doesn't navigate the user to the Azure AD login but instead navigates to the application login page. See attached picture.
![msal-login-popup](https://user-images.githubusercontent.com/9357792/96900084-51adff80-1457-11eb-9e9b-1bfbe831e909.png)

This works fine when I run the react application locally on my laptop.
I get this error when I have the application hosted in an Azure AppService but not consistently.

This works as expected on Firefox 78.1.0esr for both local and remote server deployments.

## Error Message
None
## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
{
  auth: {
    clientId,
    authority,
    redirectUri: window.location.origin,
    postLogoutRedirectUri: window.location.origin
  },
  cache: {
    cacheLocation: "sessionStorage", 
    storeAuthStateInCookie: false, 
  }
}

```

## Reproduction steps
1. Navigate to react application hosted on Azure AppService in my Chrome browser
2. react app checks if user is logged in with acquireTokenSilent
3. Interactive login required -> redirect user to application login page with a button to trigger logInSilent() function defined below.
4. `logInsilent()` fails (no user session scenario). `loginInteractive()` is triggered which calls `msalInstance.loginPopup()`
5. Popup is triggered but navigates to the application login screen instead of Azure AD

```js
export const loginSilent = async (): Promise<string> => {
    // to refresh id_token only pass the clientID in scopes
    const silentRequest: msal.AuthorizationUrlRequest = {
        scopes: [authConfig.appGeneralScope],
        loginHint: getCurrentUserAccount()?.username,
        // use an empty html page for redirect to avoid timeouts
        // https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2263
        redirectUri: authConfig.getUrlOrigin() + '/auth.html',
    };

    try {
        const authResult = await msalInstance.ssoSilent(silentRequest);

        currentAuthResult = authResult;

        return authResult.accessToken;
    } catch (err) {
        if (err instanceof msal.InteractionRequiredAuthError) {
            console.error('Silent login failed - interactive required', err);

            return await loginInteractive();
        } else if (err instanceof msal.AuthError) {
            console.error(
                'Some other auth error - fallback to interactive login anyway',
                err
            );

            return await loginInteractive();
        } else {
            console.error('auth.loginSilent()', err);

            throw new Error(`Login failed: ${err.message}`);
        }
    }
};

const loginInteractive = async () => {
    try {
        const authResult = await msalInstance.loginPopup(
            authConfig.loginRequest
        );

        currentAuthResult = authResult;

        return authResult.accessToken;
    } catch (err) {
        console.error('auth.loginInteractive()', err);

        throw new Error(`Login failed: ${err.message}`);
    }
};
```

## Expected behavior
`loginPopup` opens a pop up that navigates the user to the Azure AD interactive login page

## Browsers/Environment
- [X ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by sameerag** [comment]
@georgejdli Can you please share any  logs you have and a fiddler trace? Is it possible that the popUp is supposed to be a consent screen only in this scenario? 

Also, do you see any tokens at all returned or are you stuck with the popup?

**Comment by georgejdli** [comment]
Sorry I don't have any useful logs to share and can't run fiddler behind our corporate proxy.
The popUp is for interactive login (username and password) No tokens are returned and I'm stuck with the popup.

I retested in Chrome with private browsing.
![msal-login-private](https://user-images.githubusercontent.com/9357792/96942653-5a282980-149b-11eb-8078-69c717cd5cda.png)
So I get the above login popup. I enter my email and get redirected to my organization's authentication page. I login there and I'm expecting to get an authToken back. Except I get stuck with the login page rendered in the popup that you see in the original post.

**Comment by sameerag** [comment]
@georgejdli Can you generate a .har file from the chrome dev tools? Also may be emailing us the uncensored urls will help us understand what is happening with the `redirect`. Can you please reach out to us [here](sameera.gajjarapu@microsoft.com)?

**Comment by georgejdli** [comment]
@sameerag I just sent you an email from my work email address with the HAR files

**Comment by sameerag** [comment]
Thanks @georgejdli. Will check the data and reach out.

**Comment by ingwarr23** [comment]
Hi! We have the same issue. Did you find any solution for it? Thank you!

**Comment by georgejdli** [comment]
@ingwarr23 I'm still waiting to hear back from @sameerag

**Comment by sameerag** [comment]
Apologies for the delay. I will be inspecting the logs tomorrow and will reach out if I need further data. Thanks for the patience.

**Comment by jasonnutter** [comment]
@georgejdli Can you please try setting the redirectUri for popup (and silent) requests to be a blank page (e.g. a blank html page)? I suspect this issue is happening because the page used for the redirectUri (your app's home page) is mangling the URL in the popup (i.e. removing/changing the url fragment), which is preventing MSAL from parsing it and closing the popup.

**Comment by georgejdli** [comment]
@jasonnutter  thanks I'm no longer working on the project that has this problem but I'll forward your suggestion to the team

Closing the issue for now
