### ISSUE TITLE
Token Renewal - Offset Time (tokenRenewalOffsetSeconds)

### ISSUE THREAD

**Issue by muperi** [AzureAD/microsoft-authentication-library-for-js#2479]
Do we have the ability to configure an offset time by which the library should fetch new tokens and not return the ones from the cache?

Also, in our current implementation we have implemented a polling mechanism where we call acquireTokenSilent every 10 minutes to get a token. However I am not sure what would happen if the token (returned from the cache) has an expiration time between two 10 minute intervals. Will be left with an expired token for a short period of time? If so, can we avoid it by specifying an offset time as a configuration. Please advise.

**Comment by sameerag** [comment]
Closing this as a dup to [this issue](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2479)
