### ISSUE TITLE
TypeError: history.replaceState is not a function - in office.js

### ISSUE THREAD

**Issue by ralphtheninja** [AzureAD/microsoft-authentication-library-for-js#2488]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.4.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework

`webpack`, `react`

## Description

The redirect promise crashes due to `history.replaceState` is not a function.

## Error Message

![history](https://user-images.githubusercontent.com/308049/97095722-5ba44e00-1663-11eb-8e9a-7f68105d3c9c.PNG)

## Security
- [ ] Is this issue security related?

## Regression
- [x] Did this behavior work before? 
Version: 2.3.1

## MSAL Configuration

No special configuration. Only using `clientId` and `cacheLocation: 'localStorage'`

## Reproduction steps

Just initialize an `msal` instance and use `msal.handleRedirectPromise()`.

## Expected behavior

`msal.handleRedirectPromise()` doesn't crash.

## Browsers/Environment
- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jasonnutter** [comment]
@ralphtheninja Can you please provide more information about the browser environment your app is running in? `history.replaceState` should be available in [all modern browsers](https://developer.mozilla.org/en-US/docs/Web/API/History/replaceState#Browser_compatibility). Is it possible your app is overwriting the `history` object?

**Comment by ralphtheninja** [comment]
> Also, bychance are you using [Office.js](https://github.com/OfficeDev/office-js/issues/429)?

Yes, I'm using `office.js`.

**Comment by jasonnutter** [comment]
> > Also, bychance are you using [Office.js](https://github.com/OfficeDev/office-js/issues/429)?
> 
> Yes, I'm using `office.js`. And because of this it's not really feasible for me to try out one of the samples. All I did was to update from `2.3.1` to `2.4.0` and the error happened. I didn't notice at first since I'm only doing the redirect if not already logged in. Just noticed it now when I cleared `localStorage`.

Okay, thanks for the confirmation. We'll investigate this and follow up when we have a resolution.

**Comment by ralphtheninja** [comment]
Thanks! I'd be happy to try out a test branch if you need an extra verification or similar.

**Comment by jasonnutter** [comment]
> Thanks! I'd be happy to try out a test branch if you need an extra verification or similar.

PR with fix linked above.

**Comment by ralphtheninja** [comment]
> PR with fix linked above.

Awesome. Thank you for swift response!
