### ISSUE TITLE
@azure/msal-react: usable or time frame for release?

### ISSUE THREAD

**Issue by cheslijones** [AzureAD/microsoft-authentication-library-for-js#2490]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Please provide your question here, including as much relevant details as possible.

I see a number of branches referencing `@azure/msal-react`. I'm mostly curious what the state of it is: is it usable or a time frame for it being released?

I ask because this tutorial doesn't seem to be up-to-date:

https://docs.microsoft.com/en-us/graph/tutorials/react

The examples in this repo primarily deal with VanillaJS. 

This repo says it will be deprecated when `@azure/msal-react` is released so I'm reluctant to use it for that reason and given it is also based on `msal@v1.x.x`:

https://github.com/syncweek-react-aad/react-aad#readme

At any rate, having a hard time getting this working in my CRA app with the examples provided, so thought I'd ask about the availability of it.

**Comment by jasonnutter** [comment]
@cheslijones We have an updated roadmap available [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/roadmap.md). We're working to have a preview version available by November.

**Comment by cheslijones** [comment]
@jasonnutter Got it, thanks.
