### ISSUE TITLE
ClientAuthError: Login_In_Progress: Error during login call

### ISSUE THREAD

**Issue by thodwris** [AzureAD/microsoft-authentication-library-for-js#2493]
## Library
- [x] `msal@1.x.x` or `@azure/msal@1.3.2` (tried with 1.4.2 as well)
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework
React

## Error Message
`ClientAuthError: Login_In_Progress: Error during login call`

## MSAL Configuration
Default

## Reproduction steps
When I click outlook login button then the login popup opens but when I go back and click the button again I got the error mentioned above. And if I proceed with the user login nothing happens despite the popup closes itself. 

## Expected behavior
It shouldn't throw an error or even by throwing an error it shouldn't interrupt the normal login flow of the user.

## Browsers/Environment
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by sameerag** [comment]
@thodwris This error is thrown intentionally when we open multiple pop-ups. Can you please give us more context on your scenario?
