### ISSUE TITLE
Allow timeout configurability with Device code 

### ISSUE THREAD

**Issue by jonathandturner** [AzureAD/microsoft-authentication-library-for-js#2494]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
 - msal-node

## Description
Something that we'd like to be able to do is set a timeout for the device code credential so that once the timeout has been reached, we return control and can give an error to the user. It seems that some MSAL languages, like Python (https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/identity/azure-identity/azure/identity/_credentials/device_code.py#L85-L88), are able to use these timeouts, and it'd be great to be able to set them from node also.

**Comment by sameerag** [comment]
Thanks @jonathandturner for raising this. I think this is possible. Will update this space once the specifics are clear. Tracking this PR with node project.
