### ISSUE TITLE
SSO(log in, log out) on different domains

### ISSUE THREAD

**Issue by AndriiBoiko1** [AzureAD/microsoft-authentication-library-for-js#2499]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
I ran into issue when moving from MSAL 1.3.1  to  2.x. I have 2 SPA apps  (using B2C tenant) on a different domains and when using 1.3.1 SSO works as expected (login into 1st app logs me into the 2nd and vice versa, the same thing with logout) BUT the biggest problem is that 1.3.1 ver of lib doesn't work in Safari because of Intelligent Tracking Prevention so that's why I'm moving to 2.x.

For ver 1.3.1 I used ```acquireTokenSilent()``` with  ```LoginHint: ' '``` to acquire token and it perfectly did all the SSO work
```
msalInstanse.acquireTokenSilent({
        scopes: [scopes],
        forceRefresh: true,
        loginHint: ' ',
})
```

For ver 2.x this func has been changed to accept different object (with Account prop required)
and that broke all the SSO for me as this is applicable only when sites are on the same domain
```
msalInstanse.acquireTokenSilent({
        scopes: [scopes],
        account,
      });
```

I can see ```ssoSilent()``` func in docs but it feels it still has "Intelligent Tracking Prevention" limitation and for some reasons it works SLOW in Chrome for me (following event takes ~30 secs: "1.6.3 : Info - Emitting event: msal:ssoSilentStart")

The result I'm trying to reach out is: open 1st site log in, open 2nd site and be already logged in (or open 2 sites on a home page, login on one of them, reload the second one and be already logged in) the same thing with log out.

## Question
How do I do SSO between domains or if it's possible at all with MSAL 2.x?

**Comment by sameerag** [comment]
@AndriiBoiko1 To SSO to an existing session using `msal 2.x` we recommend `ssoSilent` API. As noted in the docs, it still uses `iframes` hence it is susceptible to ITP and hence we recommend `loginPopup` or `loginRedirect` as a fall back.

> How do I do SSO between domains or if it's possible at all with MSAL 2.x?
As long as you are trying to access the same service session, you should be able to SSO. 

> I can see ssoSilent() func in docs but it feels it still has "Intelligent Tracking Prevention" limitation and for some reasons it works SLOW in Chrome for me (following event takes ~30 secs: "1.6.3 : Info - Emitting event: msal:ssoSilentStart")

Have you tried other browsers? And have you any clue why it is taking that long? ~30secs is too long and hence any debug information will be helpful.

**Comment by AndriiBoiko1** [comment]
@sameerag Thanks for the reply.

Regarding ~30secs:

I'm using func like this to sso (it is executed on every page load)
```
  const getAuthInfoSilently = async () => {
      authResponse = await msalInstanse.ssoSilent({
        scopes: [scopes],
        loginHint: ' ',
      });

     return authResponse;
  }
```
And I get this log in console with no errors or additional logs (you can see a huge gap between 1st and 2nd event)
![image](https://user-images.githubusercontent.com/57752495/97416087-aac1db80-190e-11eb-9219-a31c4ca67546.png)



Regarding "recommend loginPopup or loginRedirect as a fall back."

Can you provide me with an example of using ssoSilent for Safari with loginPopup or loginRedirect? 

As I said previously I have 2 sites on a diff domains so will it actually do the job (handle sso) when I'm on a home page of site ```abc.com```(not logged in), then open the site ```def.com``` in another tab log in there, go back to ```abc.com``` reload the page and then I should be logged in.

**Comment by AndriiBoiko1** [comment]
@sameerag any thoughts?

**Comment by bajzat** [comment]
@AndriiBoiko1 May I ask what was the configuration issue regarding the 30 seconds? I'm facing the same issue right now.

**Comment by AndriiBoiko1** [comment]
@bajzat had a LoadFrameTimeout set to 25 secs, just removed it
![image](https://user-images.githubusercontent.com/57752495/97978578-6afb6800-1dd6-11eb-9cf9-6dc5891eb4b2.png)

**Comment by bajzat** [comment]
Thanks, @AndriiBoiko1 , it made a trick. The question may be to @sameerag , why the loadFrameTimeout affects the SSO performance.

**Comment by jasonnutter** [comment]
@bajzat I believe this is a known bug, see #2314. Unfortunately we haven't had a chance to address it, I'll make sure it gets fixed soon.
