### ISSUE TITLE
Account caching issue

### ISSUE THREAD

**Issue by naishx** [AzureAD/microsoft-authentication-library-for-js#2500]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.4.1`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
After a successful login the user account is stored in the local cache. But the next time the app runs the account array is empty.
I looked in the source code and found that AccountEntity.isAccountEntity will check the properties. My account has no localAccountId so it will always return null. 

![tempsnip](https://user-images.githubusercontent.com/13622683/97322972-9a5b2380-1870-11eb-83de-7b6e5265b9ff.png)

## Question
How can i add this field?

**Comment by sameerag** [comment]
@naishx `localAccountId` should be added in the `msal` code. Can you please share the library version you are seeing this issue?

Note: General recommendation is to follow the template, so we have all the necessary data to proceed with an issue.

**Comment by naishx** [comment]
Edited with template and library version.

**Comment by sameerag** [comment]
@naishx Can you elaborate why your account doesn't have `localAccountId`? Specifically can you confirm your `IdToken` does not contain `oid` or `sub` claims?

**Comment by TimoWilhelm** [comment]
@sameerag  I'm facing the same issue with @azure/msal-browser 2.4.1 and azure/msal-common 1.6.3. I'm using Azure AD B2C and my `IdToken` does **not** contain an `oid` claim but it does have the `sub` claim.
![image](https://user-images.githubusercontent.com/22396907/97607225-02e10680-1a11-11eb-92e3-e5dfbf3958ec.png)

**Comment by sameerag** [comment]
@TimoWilhelm We noticed a bug on our end where we are not adding `sub` and this is being fixed with #2516.

**Comment by jasonnutter** [comment]
Closing, as this bug has been fixed and released.
