### ISSUE TITLE
How to acquire access token when there is no scope

### ISSUE THREAD

**Issue by graphicsxp** [AzureAD/microsoft-authentication-library-for-js#2503]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.3.1
- [x] `@azure/msal-angular@1.1.1`

## Description

In my angular application, I receive id token and access tokens for some APIs that are called by the application.

Whenever a http request is made to one of the API, I have an interceptor to retrieve the access token from cache and add it to bearer in authentication header.

This is the relevant code:

```
 getAccessToken(url: string): Observable<AuthResponse> {
    if (url.startsWith(environment.backendUrl)) {
      return this._getAccessToken([environment.scopes.authorApi.fullaccess]);
    } else if (url.startsWith(environment.microsoftGraphUrl)) {
      return this._getAccessToken([environment.scopes.microsoftGraphApi.profile]);
    } else if (url.startsWith(environment.fileUrl)) {
      return this._getAccessToken([environment.scopes.fileApi.fileDownload, environment.scopes.fileApi.fileUpload]);
    }
  }

  private _getAccessToken(scopes): Observable<AuthResponse> {
    return from(this.msalService.acquireTokenSilent({ scopes }).catch(reason => {
      if (reason.errorCode === 'consent_required' || reason.errorCode === 'interaction_required') {
        return this.msalService.acquireTokenPopup({ scopes });
      }
      if (reason.errorCode === 'login_required') {
        // id token could not be found - redirect
        this.msalService.loginRedirect();
      }
    }));
  }
```

The problem is that now I have to call an API for which there is no particular scope. So how do I retrieve the access token from cache ?  What do I pass to acquireTokenSilent parameter ?

**Comment by jasonnutter** [comment]
@graphicsxp Is it possible this API is expecting an ID token? You will need to clarify with the maintainers of said API.

**Comment by graphicsxp** [comment]
@jasonnutter I am the mantainer of the API. Basically it is just a asp.net core API that expects the ID token in the header of the request.
But as I said the problem is not really the API itself, it is just the fact that there are no scopes on this API and I don't know how to fetch the token from cache given the code above.

**Comment by jasonnutter** [comment]
@graphicsxp I believe if you configure your application to accept an audience claim that matches your client id, it could accept ID tokens acquired by msal (which you get from the `openid profile` scopes). That said, we do not recommend protecting backend APIs with ID tokens, and instead you should register a custom scope in the Azure portal and use MSAL to acquire an access token for that scope. See: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1797#issuecomment-646004202

**Comment by graphicsxp** [comment]
Sorry, I meant Access token. In Azure my Angular application is already configured to acquire an access token. Only i did not create any scope for this API. Because my understanding is that scope are for giving client access to specific parts of an API. But my cient app should be able to access everying.
So you are saying that in my case, there should be at least one scope for this to work ?

**Comment by jasonnutter** [comment]
@graphicsxp Yes, you should still create a scope.

**Comment by graphicsxp** [comment]
thanks for confirming 👍
