### ISSUE TITLE
Overzealous Cache Manager does not return some valid account tokens

### ISSUE THREAD

**Issue by harveyramer** [AzureAD/microsoft-authentication-library-for-js#2504]
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/532fbcfeb542452ce3ac434fc1704a39d9218e14/lib/msal-browser/src/cache/BrowserStorage.ts#L133

The msal-common cache manager contains this `isAccountEntity` function:

```
AccountEntity.isAccountEntity = function (entity) {
        if (!entity) {
            return false;
        }
        return (entity.hasOwnProperty("homeAccountId") &&
            entity.hasOwnProperty("environment") &&
            entity.hasOwnProperty("realm") &&
            entity.hasOwnProperty("localAccountId") &&
            entity.hasOwnProperty("username") &&
            entity.hasOwnProperty("authorityType"));
    };
```

However, not every valid session is guaranteed a  localAccountId property. In fact, in the little documentation I found about localAccountId, it seems to be included only for backwards compatibility and should not factor into a test of an account entity.

My sessions cannot be reconstituted by looking up the account unless localAccountId is removed from this function.

**Comment by jasonnutter** [comment]
@harveyramer Does this seem like the same issue described in #2500?

**Comment by harveyramer** [comment]
Yes. It's a duplicate. I didn't see it already logged.

**Comment by jasonnutter** [comment]
Closing as duplicate.
