### ISSUE TITLE
Bug - msal-browser@2.3.0 throws an exception when logging out

### ISSUE THREAD

**Issue by plamber** [AzureAD/microsoft-authentication-library-for-js#2506]
## Library
- [x] `@azure/msal-browser@2.3.0`

## Framework
React 1.6

## Description
MSAL browser fails on a Chrome on Windows 10 machine when trying to logout. Use the logout method of the object with and without logoutRequest operation.
Seems that the windowStorage object where you are retrieving the cached items to delete might not only contain JSON objects when looking up for idtokens (see screenshots below). This lets your method fail and the logout is not performed.

## Error Message
Unhandled promise rejection SyntaxError: Unexpected token e in JSON at position 0
    at JSON.parse (<anonymous>)
    at BrowserStorage.getItem (index.es.js:7153)
    at index.es.js:2830
    at Array.forEach (<anonymous>)
    at BrowserStorage.CacheManager.removeAccountContext (index.es.js:2825)
    at BrowserStorage.CacheManager.removeAccount (index.es.js:2815)
    at AuthorizationCodeClient.getLogoutUri (index.es.js:4614)
    at PublicClientApplication.<anonymous> (index.es.js:8857)
    at step (index.es.js:74)
    at Object.next (index.es.js:55)
    at fulfilled (index.es.js:45)
    at es.promise.js:114

## MSAL Configuration

```js
Standard configuration for SPA. We are also using the JS library for graph to perform Graph HTTP calls.
```

## Reproduction steps
```js
const logoutRequest = {
      account: this._account as any
};
this._app.logout(logoutRequest);

```
![image](https://user-images.githubusercontent.com/18241305/97384972-14bb9000-18d1-11eb-82c0-764afc21d0c4.png)
![image](https://user-images.githubusercontent.com/18241305/97385330-cc50a200-18d1-11eb-91b1-0458218ceb35.png)

## Expected behavior
In case you are not able to parse the object in the storage, graceful handle it and keep it where it is without clearing it out. The rest of the logout operation should run without issues.

## Browsers/Environment
- [x] Chrome (latest version on Windows 10 latest version)
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by sameerag** [comment]
@plamber The latest browser version should resolve this issue. Can you please test this with `msal-browser@2.4.x` and let us know if this is still an issue?

**Comment by plamber** [comment]
Hi @sameerag,
thank you for the feedback. I upgraded to 2.4.1 and I can't reproduce the issue.

I will come back to you if I notice something coming up.

Thank you,
Patrick
