### ISSUE TITLE
Expose OID aka localAccountId in AccountInfo

### ISSUE THREAD

**Issue by kostrse** [AzureAD/microsoft-authentication-library-for-js#2507]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

In the MSAL v2 library, `AccountInfo` exposes `homeAccountId` which is user's OID in the home tenant, but doesn't expose the user's real identifiers like OID or SUB (aka `localAccountId` aka `uniqueId`).

Could you please expose it via public interface?

Even better would be to return specifically OID and/or SUB if they present, rather than abstracted out value `localAccountId`.

The problem is that, at least in our particular scenario, our app communicates with Graph API, and with other APIs, and in every case the OID is the actual unique identifier of the user, regardless of whether it's a normal user or a guest user from another tenant.

Or at least what is the way to retrieve the cached id-token for a given `AccountInfo` to obtain the OID without re-triggering the login process since you already have it in cache (`BrowserStorage`).

I understand that I could get it from `AuthenticationResult` after a successful login and store it on my own, but it's just basically re-implementation of own cache manager which msal already has (`BrowserStorage`).

**Comment by sameerag** [comment]
@kostrse Thanks for raising this. I think this can be done, will soon raise a PR for the same.

**Comment by CerosDev** [comment]
My solution is to perform a `acquireTokenSilent` to retrieve the Id Token. From my understanding, this should get the one from the cache if it's still valid. 

But doing so requires you to convert your function to async/await.

It would be great if the `getAllAccounts` could return the cached Id Token too. I believe this was the case in msal-core (msal 1.x)

**Comment by kostrse** [comment]
I tried `acquireTokenSilent` as a workaround but it isn't perfect solution.

id-token doesn't have concept of expiration but `acquireTokenSilent` is meant for access tokens, so it triggers refresh of access token if it has expired even though I do not need access token itself.

I also have to provide some scopes, `acquireTokenSilent` cannot request access token without any scopes, even though I do not need them.

Access to collection of received id claims would be great and flexible enough since different application may request different claims (profile, sid, etc.).

**Comment by TimoWilhelm** [comment]
@sameerag Would it be possible for the `ClientApplication` to also have another method `getAccountByLocalAccountId(homeAccountId: string): AccountInfo|null` similar to  https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/15facdac21e62daccde549b48c6d54aa4f2cfc19/lib/msal-browser/src/app/ClientApplication.ts#L597-L610

**Comment by kostrse** [comment]
Same person can be logged in to several tenants as a guest user.
In each tenant the person will have a different user object (different 'oid`) but `homeAccountId` will be the same.

The accounts collection may have several entries with same `homeAccountId` making `getAccountByHomeId` not reliable.

**Comment by sameerag** [comment]
Let me summarize and comment on the asks in this thread:

> Expose `idTokenClaims` in  `AccountInfo` instead of sending them only in the `Response`.

Possible. Let me get back on this.

> Provide APIs `getAccountByHomeId()` and `getAccountByLocalId()`

I think the tenant profiles feature we are starting soon should encompass this. I have already marked this as a feature and will track it with the said work item.

**Comment by TimoWilhelm** [comment]
`getAccountByHomeId` is already implement, as is `getAccountByUsername`. They are just convenience methods so you don't have to do `getAllAccounts` and then filter yourself. 

Since we now also have localId, I think it would be a good idea to add `getAccountByLocalId` as well.

**Comment by kostrse** [comment]
At least you guys could ship the `localAccountId` now and decide about `getAccountByLocalId` later since at least it will be possible to query proper account from `getAllAccounts` manually.
