### ISSUE TITLE
allowPublicClient in App Registration for Auth Code Flow

### ISSUE THREAD

**Issue by CerosDev** [AzureAD/microsoft-authentication-library-for-js#2508]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Documentation location
- [x] docs.microsoft.com
- [x] MSAL.js Github Wiki
- [ ] README file
- [ ] Other (please fill in)
- [ ] Documentation does not exist

## Description

I am now using msal-browser 2.4.

My app registration has two redirect uris of type Spa, one for my server and one http://localhost.
My app registration has the allowPublicClient to null (or false in the UI)

Running locally (localhost), everything is OK.
Running from the server, I get the AADB2C90058 error (The provided application is not configured to allow public clients )

I found out, from a [blog concerning another lib](https://www.taithienbo.com/obtain-access-token-via-authorization-code-grant-with-pkce-in-angular-using-oidc-client-js-and-microsoft-identity-platform/), that I need to have allowPublicClient set to true.
I did not see any mention of this neither in this repo or on [Microsoft's website](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-app-registration).

Am I doing something wrong?

**Comment by sameerag** [comment]
@CerosDev If `allowPublicClient` is null, then it is assumed that your client is `Confidential`. `msal-browser` supports only `PublicClientApplications` with `PKCE`. Thanks for bringing this to our attention, we will add this to our docs.

**Comment by sameerag** [comment]
@hamiltonha Is this something we can add to Microsoft docs?

**Comment by CerosDev** [comment]
@sameerag @hamiltonha  I'd like to also point out that according to [this doc](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-app-registration#redirect-uri-msaljs-20-with-auth-code-flow):

> Do NOT select either checkbox under Implicit grant.

Which totally brake the [id_hint_token invitation flow ](https://github.com/azure-ad-b2c/samples/tree/master/policies/invite) with this error:

> AADB2C90057 The provided application is not configured to allow the OAuth Implicit flow.

**Comment by tnorling** [comment]
@nickgmicrosoft Can you update the docs/app registration experience to call out the nuances with the invite flow?

**Comment by nickgmicrosoft** [comment]
Hi all, there's currently a limitation for Azure AD B2C in which the service relies purely on the access token checkbox to enable both ID token and access token implicit requests. For Azure AD B2C, you have to check that checkbox, regardless of whether you'll use ID token/implicit flow or not.

We're exploring options to update the documentation and portal experience updates to reflect this while this is the case.

**Comment by sameerag** [comment]
Closing this as there is no immediate work for msal team. @nickgmicrosoft please track this in the B2C portal activities as needed.
