### ISSUE TITLE
Deploy Beta's to NPM

### ISSUE THREAD

**Issue by spottedmahn** [AzureAD/microsoft-authentication-library-for-js#251]
Can you **please** deploy beta releases to NPM?  Without this, I don't know how I can test the new functionality in our Angular app.  Thoughts?

**Comment by spottedmahn** [comment]
Hello - any thoughts/updates on this?  We really need to get our hands on the next version of MSAL.js.  Thanks!

**Comment by rohitnarula7176** [comment]
@spottedmahn We are busy working on the security review of the libraries. We will release the new version next week.

**Comment by spottedmahn** [comment]
Hi @rohitnarula7176 - that's great.

What about my [original post](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/251#issue-297093721)?  Can you please deploy beta's to NPM?

**Comment by rohitnarula7176** [comment]
@spottedmahn The beta version is now deployed on npm. You can install it using npm install msal@beta. Please refer to the changelog.md for the breaking change. Can you please test the version and provide feedback.

**Comment by spottedmahn** [comment]
I tried the beta, no issues ⭐️ !

- [X] [Try `loadFrameTimeout` for getting an access token: 209](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/209)
- [X] [Try `navigateToLoginRequestUrl`: 238](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/238#issuecomment-365453972)

Thanks for publishing the beta!
