### ISSUE TITLE
MSAL.js loginPopup() method returns a cached login instead of account entered

### ISSUE THREAD

**Issue by emilepretorius** [AzureAD/microsoft-authentication-library-for-js#2522]
## Library
- [x] `msal@1.3.4` 
- [x] `msal@1.4.3`

## Framework
React 

## Description
The loginPopup() method returns a cached login regardless of the account manually entered. 

## Error Message
N/a

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version: Unknown

## MSAL Configuration
const msalConfig = {
    auth: {
        clientId: config.auth.clientId,
        audience: config.auth.tenantId,
        redirectUri: config.spaUrl,
        authority: "https://login.microsoftonline.com/organizations",
        //authority: `https://login.microsoftonline.com/${config.auth.tenantId}/` //Same result as "organisations"
    },
    cache: {
      cacheLocation: "sessionStorage",
      storeAuthStateInCookie: false, 
    }
};

## Reproduction steps
Trigger MSAL.loginPopup()
List of recent logins displays (1)
Select "Use other account" 
Enter any other account name, enter
Dialogue states "Taking you to your organisation's sign in page"
Dialogue box closes and MSAL.loginPopup() returns first cached account displayed in (1)

Clearing browser cache does not solve the problem
Incognito mode does not solve the problem

A machine restart is all that appears to work. 

## Expected behavior
The user should be able to sign in with the specified account / account typed in.

## Browsers/Environment
- [x] Chrome
- [ ] Firefox
- [x] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by pkanher617** [comment]
@emilepretorius Do you see the new account object in your sessionStorage?

**Comment by sameerag** [comment]
@emilepretorius Are you trying to login in one account first and then attempt to login with another? Can you clarify the reproduction steps?

**Comment by emilepretorius** [comment]
> @emilepretorius Do you see the new account object in your sessionStorage?

I did not check at the time, I'll have to get back to you on that.

**Comment by emilepretorius** [comment]
> @emilepretorius Are you trying to login in one account first and then attempt to login with another? Can you clarify the reproduction steps?

Trigger MSAL.loginPopup() = Open the app which does the sign in. 

Not trying multiple logins. Trying to log in with an account not displayed in the list of recent / cached logins.

**Comment by jasonnutter** [comment]
@emilepretorius MSAL v1 does not support multiple accounts. This means the behavior you describe can happen if your application does not first call the MSAL logout function. MSAL Browser v2 (@azure/msal-browser) does support multiple accounts. Please try upgrading and let us know if you still experience this issue, thanks!
