### ISSUE TITLE
getAllAccounts() returns an empty array

### ISSUE THREAD

**Issue by soufian044** [AzureAD/microsoft-authentication-library-for-js#2524]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x ] `@azure/msal-browser@2.4.1` and UP
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
VueJs 
## Description
getAllAccounts() returns an empty array when using version 2.4.1 and up, the token request return the user nothing to note, about it. i attached a Gif hopping it describe the issue better
![msal](https://user-images.githubusercontent.com/10144036/97706765-7d179680-1ab6-11eb-803c-7ba5c3371fd5.gif)

## Error Message
No error merssage
## Security
- [ ] Is this issue security related?

## Regression
- [X ] Did this behavior work before? 
Version: 2.4.0
## MSAL Configuration

```js
auth: {
        clientId: XX,
        authority: XXX,
        knownAuthorities: XXX,
        redirectUri: "http://localhost:8081/auth/callback",
        postLogoutRedirectUri: 'http://localhost:8081',
        validateAuthority: false
    }
```

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Expected behavior
should return an array of logged in users, same that happens on version 2.4.0
## Browsers/Environment
- [x ] Chrome
- [x ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by sameerag** [comment]
@soufian044 Yes, this is a bug . We are working on a patch and will update here once we have something available.

**Comment by soufian044** [comment]
@sameerag I can confirm you that the bug is present on the latest "msal-browser": "2.5.1", including the the "2.5.0" and "2.4.1" , the array is always null.

**Comment by soufian044** [comment]
the issue seems to be comfing from these check 
![image](https://user-images.githubusercontent.com/10144036/97818978-0640f000-1ca6-11eb-86bf-f63d29b50191.png)

and related to this PR from you #2516

**Comment by sameerag** [comment]
Yes. #2516 should fix this. Linking the PR.

**Comment by pkanher617** [comment]
@soufian044 Does this issue still occur in 2.5.2?

**Comment by sai-nagarjuna-t** [comment]
issue still present in 2.5.2 and 2.4.1

**Comment by alandecastros** [comment]
Hope this gets fixed asap

**Comment by pkanher617** [comment]
Taking a look at this today, thanks for your patience.

**Comment by sameerag** [comment]
#2516 should be merged soon. The wait is on unit tests and we have them ready now.

**Comment by alandecastros** [comment]
Still not working on 2.6.0

**Comment by MariMax** [comment]
@sameerag could you please reopen this issue, getAllAccounts on CacheManager always returns an empty array for ADFS
it uses getAccount on child class
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/src/cache/CacheManager.ts#L243
and in case of BrowserCacheManager it cannot reconstruct AccountEntity, validation fails here
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/src/cache/BrowserCacheManager.ts#L150
it doesn't have localAccountId, because here
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/src/cache/entities/AccountEntity.ts#L177
when we construct genericAccountEntity we are not setting localAccountId

I can suggest a PR, please let me know if it would help

**Comment by sameerag** [comment]
@MariMax Sorry this is a miss form our end. We calculate `homeAccountId` for ADFS as `oid` or `sub` but missed adding `localAccountId` as a property. This was there in the draft, looks like when we finally merged this was missing. Putting out a PR soon.

**Comment by sameerag** [comment]
One question @MariMax. What is the `name` claim in your ADFS token? There are various versions of ADFS tokens in play, I want to make sure we support that as a part of `AccountInfo`.

**Comment by MariMax** [comment]
we actually don't have `name` in our claims
```
appid: string;
apptype: string;
aud: string;
auth_time: number;
authmethod: string;
certsubject: string;
email: string;
exp: number;
given_name: string;
iat: number;
iss: string;
nbf: number
nonce: string;
pwd_exp: string;
scp: string;
sid: string;
sub: string;
unique_name: string;
upn: string;
ver: string;
```

Thank you for quick PR!
