### ISSUE TITLE
"ClientAuthError: Token renewal operation failed due to timeout" for authProvider.getAccessToken()

### ISSUE THREAD

**Issue by cheslijones** [AzureAD/microsoft-authentication-library-for-js#2526]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [X] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.
`msal@1.4.3`

## Framework

ReactJS using [`react-aad`](https://github.com/syncweek-react-aad/react-aad)

## Description

`authProvider.getIdToken()` is working as expected. `authProvider.GetAccessToken()` is not and is producing `ClientAuthError: Token renewal operation failed due to timeout.` errors. Keeps looping through this before ultimately timing out.

## Error Message

![image](https://user-images.githubusercontent.com/59094233/97749063-a5e65e80-1aab-11eb-92c7-00162610fc83.png)

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```
// ../utils/authProvider.js
import { MsalAuthProvider, LoginType } from 'react-aad-msal';
// import { Logger, LogLevel } from "msal";

// The auth provider should be a singleton. Best practice is to only have it ever instantiated once.
// Avoid creating an instance inside the component it will be recreated on each render.
// If two providers are created on the same page it will cause authentication errors.
export const authProvider = new MsalAuthProvider(
  {
    auth: {
      authority:
        'https://login.microsoftonline.com/tenant_id/',
      clientId: '<client_id>',
      postLogoutRedirectUri: 'https://' + window.location.origin + '/admin/',
      redirectUri: 'https://' + window.location.host + '/admin/',
      validateAuthority: true,
    },
    cache: {
      cacheLocation: 'sessionStorage',
      storeAuthStateInCookie: true,
    },
  },
  {
    scopes: ['openid', "profile", "user.read"],
  },
  {
    loginType: LoginType.Redirect,
    // When a token is refreshed it will be done by loading a page in an iframe.
    // Rather than reloading the same page, we can point to an empty html file which will prevent
    // site resources from being loaded twice.
    tokenRefreshUri: window.location.origin + "/auth.html"
  }
);
```

## Reproduction steps
```
// App.js
import React from 'react';
import { BrowserRouter as Router, Route, Switch } from 'react-router-dom';
import { AzureAD, AuthenticationState } from 'react-aad-msal';

// Component Imports
import Authentication from './authentication';
import Dashboard from './dashboard';
import Navbar from './navbar';

// Utilities Imports
import { authProvider } from '../utils/authProvider';

const App = () => {
  return (
    <AzureAD provider={authProvider} forceLogin={true}>
      {({ logout, authenticationState }) => {
        switch (authenticationState) {
          case AuthenticationState.Authenticated:
            return (
              <Router basename={process.env.PUBLIC_URL}>
                <Navbar logout={logout} />
                <Switch>
                  <Route path='/dashboard/' component={Dashboard} />
                  <Route path='/' component={Authentication} />
                </Switch>
              </Router>
            );
          default:
            return <div>Authenticating...</div>;
        }
      }}
    </AzureAD>
  );
};

export default App;
```

```
// ./authentication/Authentication.js
import React, { useState, useEffect } from 'react';
import { authProvider } from '../../utils/authProvider';

const Authentication = () => {
  const [idToken, setIdToken] = useState('');
  const [accessToken, setAccessToken] = useState('');

  useEffect(() => {
    if (!idToken) {
      getIdToken();
    }

    if (!accessToken) {
      getAccessToken();
    }
  }, [idToken, accessToken]);

  let getIdToken = async () => {
    let token = await authProvider.getIdToken();
    setIdToken(token);
  };

  let getAccessToken = async () => {
    let token = await authProvider.getAccessToken();
    setAccessToken(token);
  };

  if (idToken.idToken) {
    return <div>Have idToken</div>;
  } else {
    return <div>Fetching token...</div>;
  }
};

export default Authentication;
```
## Expected behavior

That it should retrieve the accessToken for validation.

## Browsers/Environment
- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jasonnutter** [comment]
![image](https://user-images.githubusercontent.com/59094233/97749063-a5e65e80-1aab-11eb-92c7-00162610fc83.png)

In the above image, can you try opening the `login.microsoftonline.com` url in the "The current window does not have permission to navigate the target from to..." error message in its own tab? What happens when you do that?

**Comment by jasonnutter** [comment]
One thing to note is that your redirect uri must either be `http://localhost:<port>` or an https url. I am guessing you will see an error message regarding your redirect uri, which must be registered in teh Azure Portal and needs to be https or localhost.

**Comment by cheslijones** [comment]
![image](https://user-images.githubusercontent.com/59094233/97750418-fa8ad900-1aad-11eb-9900-716d1364d21c.png)

Ok looks, like I might not have the app configured properly on my end, so I'll read up on that to see where I need to enable this in Azure.

As for the redirect, I do have my local dev environment `https://192.168.64.7/admin/` in the Azure App Registration redirect. I do get the "Unsafe" error because I'm not using a certificate locally, but seems to work.
