### ISSUE TITLE
Teams app custom tab: BrowserAuthError: redirect_in_iframe: Code flow is not supported inside an iframe

### ISSUE THREAD

**Issue by goldylucks** [AzureAD/microsoft-authentication-library-for-js#2531]
## Library
- [x] `@azure/msal-browser@2.3.1`

## Framework
React

## Description
We have a ms teams app with a chatbot tab and a custom tab.
In the custom tab, calling `msalInstance.loginRedirect({ scopes: [] });` throws the error below.
In the chatbot tab, opening an iframe with the exact same screen as the custom tab, and calling the same command  `msalInstance.loginRedirect({ scopes: [] });` works just fine.

## Error Message
```
BrowserAuthError: redirect_in_iframe: Code flow is not supported inside an iframe. Please ensure you are using MSAL.js in a top frame of the window if using the redirect APIs, or use the popup APIs. (window.parent !== window) => true
```

## Security
- [ ] Is this issue security related?
No

## Regression
- [ ] Did this behavior work before? 
No

## MSAL Configuration
```js
{
	auth: {
		clientId: process.env.REACT_APP_MICROSOFT_CLIENT_ID,
		redirectUri: window.location.origin,
	},
};
```

## Reproduction steps
Make a custom tab inside a ms teams app with the following code:
```js
import * as msal from '@azure/msal-browser';
const msalConfig = {
	auth: {
		clientId: process.env.REACT_APP_MICROSOFT_CLIENT_ID,
		redirectUri: window.location.origin,
	},
};

const msalInstance = new msal.PublicClientApplication(msalConfig);

msalInstance
	.handleRedirectPromise()
	.then(response => {
		if (!response) {
			return;
		}
		store.dispatch(
			socialLoginRequest({
				token: response.accessToken,
				backend: 'azuread-oauth2',
			})
		);
	})

msalInstance.loginRedirect({ scopes: [] }); // simulating trigger with a button
```

## Expected behavior
It should trigger ms auth process with redirect and respond with an access token.

## Browsers/Environment
- [x] Chrome
- [ ] Firefox # haven't tested
- [ ] Edge # haven't tested
- [ ] Safari # haven't tested
- [ ] IE # haven't tested
- [x] MS Teams app

**Comment by idan666** [comment]
Doesn't work for me either

**Comment by goldylucks** [comment]
If I change the strategy from redirect to popup:
```
const response = await msalInstance.loginPopup({ scopes: [] });
```

 I get this error:

`Unable to send AtomFrameHostMsg_Message_Sync`

**Comment by jasonnutter** [comment]
@goldylucks Are you using the [Teams JS SDK](https://www.npmjs.com/package/@microsoft/teams-js) (as demoed [here](https://github.com/nmetulev/teams-msal))?

**Comment by goldylucks** [comment]
I'm using `@azure/msal-browser`

**Comment by janandreschweiger** [comment]
Any updates on this? I have the same issue.

**Comment by kenny-reyes** [comment]
For me also, appears this when logout user:

`Code flow is not supported inside an iframe. Please ensure you are using MSAL.js in a top frame of the window if using the redirect APIs, or use the popup APIs`

It appears before redirection, so technically doesn't affect to my flow but leave this awful error in the console.

**Comment by jasonnutter** [comment]
@kenny-reyes Currently this is expected. We will be making improvements to logout in #2546 and #2563.

**Comment by brugh** [comment]
Happens to me at logon too. Is there a workaround yet?

**Comment by jasonnutter** [comment]
Update: We will have a proper sample for this scenario, but if you are getting this error, it is because you are trying to call `loginRedirect` inside the Teams tab directly, which is not the proper way to invoke auth in Teams. 

You need to use the [Teams JS SDK](https://docs.microsoft.com/en-us/javascript/api/overview/msteams-client?view=msteams-client-js-latest):

1. Invoke [`microsoftTeams.authentication.authenticate`](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/authentication?view=msteams-client-js-latest#authenticate_AuthenticateParameters_), setting the `url` to a page on your app (e.g. `/auth-start`), 
2. The `/auth-start` page should invoke `loginRedirect` on page load, setting the `redirectUri` to a page (e.g. `/auth-end`) that will call `handleRedirectPromise` to handle the response.
3. The result of `handleRedirectPromise` should be passed to `microsoftTeams.authentication.notifySuccess` or `microsoftTeams.authentication.notifyFailure`, depending on if there is an error. 
4. This result will be passed back to your code from step 1, at which point you can use the result.

Example:

```js
// auth.js
const msal = new PublicClientApplication({
    auth: {
        clientId: "your-client-id",
        authority: `https://login.microsoftonline.com/common`, // may need to replace with tenanted endpoint
        redirectUri: `${window.location.origin}/auth-end`,
        navigateToLoginRequestUrl: false
    }
})

// tab.js (when auth is needed)
microsoftTeams.authentication.authenticate({
    url: window.location.origin + "/auth-start",
    width: 600,
    height: 535,
    successCallback: (accessToken) => {
        // This will be called when microsoftTeams.authentication.notifySuccess is called from the popup
    },
    failureCallback: (error) => {
        // This will be called when microsoftTeams.authentication.notifyFailure is called from the popup
    }
});

// auth-start.js (on page load)
msal.loginRedirect()

// auth-end.js (on page load)
msal.handleRedirectPromise()
    .then(result => {
        microsoftTeams.authentication.notifySuccess(result);
    })
    .catch((error) => {
        microsoftTeams.authentication.notifyFailure(error);
    })
```

**Comment by jasonnutter** [comment]
And if you want to use the Teams OBO token to get SSO, you will need to trade it server-side, as demonstrated here: https://github.com/OfficeDev/microsoft-teams-app-quickstarts/blob/master/js/clients/tabs/tab-personal-sso/src/components/Tab.js#L68

We'll have a sample that shows both approaches.
