### ISSUE TITLE
acquireTokenSilent doesn't work for AD FS workflow

### ISSUE THREAD

**Issue by MariMax** [AzureAD/microsoft-authentication-library-for-js#2532]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.5.1`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

User successfully acquired accessToken and refresh token, but there is no client_info in the response
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/fef918b8cdbff3dc82aea3ca41118a0130ac1d40/lib/msal-common/src/response/ResponseHandler.ts#L115
so homeAccountId will stay empty on the other hand we set homeAccountId on the account here
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/fef918b8cdbff3dc82aea3ca41118a0130ac1d40/lib/msal-common/src/cache/entities/AccountEntity.ts#L183

later when I'm trying to refresh token it's not possible to get refreshToken from the storage, as there is no homeAccountId associated with it

So proposal is to do the same as we do for account, set it from `idTokenObj.claims.sub` for AD FS workflow.

Thoughts? I'll create PR...

**Comment by MariMax** [comment]
should be resolved with #2516

**Comment by sameerag** [comment]
Merged #2516
