### ISSUE TITLE
acquireTokenSilent null_or_empty_id_token error when open new window/browser for the logged in user

### ISSUE THREAD

**Issue by paranthamanwp** [AzureAD/microsoft-authentication-library-for-js#2535]
acquireTokenSilent  **null_or_empty_id_token** error when open new window/browser for the logged in user

Cache: sessionstorge

Library Version
![error](https://user-images.githubusercontent.com/13029220/97957929-49af7180-1e00-11eb-8fea-a0ce3a5994dd.png)
![error2](https://user-images.githubusercontent.com/13029220/97958159-c5a9b980-1e00-11eb-9f41-5a80e6501c70.png)

"@azure/msal-angular": "^1.1.1",
"msal": "^1.4.3",

**Comment by jasonnutter** [comment]
@paranthamanwp Please provide more information, including your MSAL Angular configuration and any relevant code samples. Also, in the future, please use the issue template, thanks!

**Comment by paranthamanwp** [comment]
app.module.ts

function MSALConfigFactory(): Configuration {
    return {
        auth: {
            clientId: environment.clienId,
            authority: environment.msLoginUrl + environment.tenantId,
            validateAuthority: true,
            redirectUri: environment.redirectUrl,
            postLogoutRedirectUri: environment.postLogoutRedirectUrl,
            navigateToLoginRequestUrl: true,
        },
        cache: {
            cacheLocation: 'sessionStorage',
            storeAuthStateInCookie: false, // set to true for IE 11
        },
    };

function MSALAngularConfigFactory(): MsalAngularConfiguration {
    return {
        popUp: false,
        consentScopes: environment.scopeUri,
        protectedResourceMap: [
            [apiURL.ApiURL1, environment.scopeUri],
 [apiURL.ApiURL2, environment.scopeUri],
        ],
        extraQueryParameters: {}
    };
}



app.component.ts

ngOnInit(): void {

         this.authService.handleRedirectCallback((authError, response) => {
            if (authError) {
                console.error('Redirect Error: ', authError.errorMessage);
                return;
            }
        });

        
            this.broadcastService.subscribe('msal:acquireTokenFailure', (error) => {
                this.authService.loginRedirect({ scopes: environment.scopeUri });
            });
		**//reach else second time onwards and api calling from home screen failed acquiretoken firsttime**
          if (!this.authService.getAccount()) {
            this.authService.loginRedirect({ scopes: environment.scopeUri });
          } else {
            this.router.navigateByUrl('/home');
          }
    }

**Comment by jasonnutter** [comment]
Can you please clarify the steps for reproducing this error? Are you opening the application in multiple tabs at the same time?

**Comment by paranthamanwp** [comment]
**Steps:**
1) Trigger app.component.ts inti
//go to **if** condition and redirect to the login page of Microsoft 
if (!this.authService.getAccount()) {
        **this.authService.loginRedirect({ scopes: environment.scopeUri });**
      } else {
        this.router.navigateByUrl('/home');
      } 
2) Microsoft login page
3) Redirected to redirect url of the application which configured which is just a base path/home
4) Call our own API which is configured in the home component init mehtod
5) Acquiretokensilent getting called from msal through httpintreceptor 
6) **AccessToken** successfully generated and api return data
**Error Steps below** 
7) Open a new window/new tab in chrome
8) Trigger app.component.ts and this time go to **else** condition since getAccount return data from coockie
if (!this.authService.getAccount()) {
        this.authService.loginRedirect({ scopes: environment.scopeUri });
      } else {
        **this.router.navigateByUrl('/home');**
      } 
9) Call our own API which is configured in the home component init method
10) Acquiretokensilent getting called from msal through httpintreceptor 
11) msal:acquireTokenFailure with the reason 'null_or_empty_id_token'
**Note:** seems its trying to find the idtoken from cockie but no key available for that
