### ISSUE TITLE
ssoSilent inside an iframe when 3rd party cookies are disabled by the browser

### ISSUE THREAD

**Issue by Dolevco** [AzureAD/microsoft-authentication-library-for-js#2537]
Hi, 
we are using msal browser (2.3) in our react web application, that is hosted inside an iframe within Dynamics.
since redirect flow is not allowed inside an iframe, we are using ssoSilent, considering the user must login using AAD to Dynamics.

It works great in some versions of Chrome, but we are facing problems in some others which rollout the prevention of using 3rd party cookies, which is used by the ssoSilent.

do you know how is it possible for us to acquire token inside an iframe in such scenario?

**Comment by jasonnutter** [comment]
@Dolevco In this scenario, no, you will not be able to silently SSO if third-party cookies are disabled. Given your app is inside an iframe, when ssoSilent fails you can call loginPopup.

**Comment by jasonnutter** [comment]
Also, in the future please use one of the issue templates, thanks!

**Comment by Dolevco** [comment]
Thank you Json. implemented the popup fallback.
Is there any plan to support the ssoSilent from an iframe, considering most of the browser going to block 3rd party cookies?

**Comment by jasonnutter** [comment]
@Dolevco We are investigating ways to improve the silent sso experience that bypasses the use of iframes, and we'll share details on that once they are finalized and available to customers.

**Comment by jasonnutter** [comment]
Closing, as no further action at this time.
