### ISSUE TITLE
If the session cookie is expired, the token cache doesnt get cleared 

### ISSUE THREAD

**Issue by sai-nagarjuna-t** [AzureAD/microsoft-authentication-library-for-js#2538]
## Library
- [ ] `@azure/msal-browser@2.1.0`

## Description
When the session cookie is expired or manually cleared, user is not getting logged out because the access token and refresh token in the sessionStorage are not getting cleared.

 Because of this even tough the session cookie (say 15 mins lifetime) is expired the user will still stay logged in until the refresh token is expired. (24 hours !!!!)
 
## Security
This is a serious security issue

## Expected behavior
The session cookies should be monitored and when they are expired or cleared the token cache should be cleared and user should be signed out.

**Comment by jasonnutter** [comment]
Can you please clarify which session cookies you are referring to? Are you referring to the session cookies on `login.microsoftonline.com` for your AAD session?

**Comment by sai-nagarjuna-t** [comment]
hi @jasonnutter I am referring to the Azure ad b2c cookies. x-ms-cpim-sso:{Id} and x-ms-cpim-csrf of b2clogin.com, login.microsoftonline.com, branded domain.


Here are some links for reference.
Cookie definitions https://docs.microsoft.com/en-us/azure/active-directory-b2c/cookie-definitions
Session lifetime configuration https://docs.microsoft.com/en-us/azure/active-directory-b2c/session-behavior

So even though I specify a 900 sec lifetime for the session like below, user is stays logged in as long the token are expired in the session cache
```
<UserJourneyBehaviors>
   <SingleSignOn Scope="Application" />
   <SessionExpiryType>Absolute</SessionExpiryType>
   <SessionExpiryInSeconds>900</SessionExpiryInSeconds>
</UserJourneyBehaviors>
```

**Comment by jasonnutter** [comment]
@sai-nagarjuna-t Thank you for clarifying. This is by design, as due to the [Same-origin policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy), there is no way for MSAL.js to know if a user's session has ended if user's session is ended outside the context of the MSAL `logout` function.

**Comment by baSSiLL** [comment]
@jasonnutter I want to get a sliding session expiration window of 1 hour since last user "activity" (request to a protected backend). I hoped that AD session timeout will help me with that invalidating a refresh token. So I could prompt a user to sign in when `acquireTokenSilent` fails. Seeing your comment I see it won't work this way.
Looks like I need to implement a custom solution for tracking session timeout. E.g. store the time of the last request to the backend and make an explicit logout if the next request is made more than 1 hour since the previous one.
Do I get it right?

**Comment by sai-nagarjuna-t** [comment]
@jasonnutter thanks for the reply,.
But i would suggest MSAL team to refer 'oidc-client-js' library which monitors session expiry. 

https://github.com/IdentityModel/oidc-client-js/blob/dev/src/SessionMonitor.js

Given that refresh tokens are valid for a min of 24 hours, MSAL is enforcing a huge limitation on the users to not able get auto logged out until the refresh tokens are expired as the session cookie expiry is unmanaged by MSAL.

**Comment by jasonnutter** [comment]
> @jasonnutter thanks for the reply,.
> But i would suggest MSAL team to refer 'oidc-client-js' library which monitors session expiry.
> 
> https://github.com/IdentityModel/oidc-client-js/blob/dev/src/SessionMonitor.js
> 
> Given that refresh tokens are valid for a min of 24 hours, MSAL is enforcing a huge limitation on the users to not able get auto logged out until the refresh tokens are expired as the session cookie expiry is unmanaged by MSAL.

We do not include (and we highly discourage applications from implementing) session monitoring (e.g. polling in an iframe) due to the increased overhead it puts on the AAD service, in addition to your application. Furthermore, refresh tokens (and access tokens) are not invalidated and only become unusable once they have expired (even after logout, where they are cleared from browser storage). Their short-lived expiration (1 hour for access tokens, max 24 hours for refresh tokens) is designed to help mitigate concerns such as this where the user's session has expired.

**Comment by jasonnutter** [comment]
> @jasonnutter I want to get a sliding session expiration window of 1 hour since last user "activity" (request to a protected backend). I hoped that AD session timeout would help me with that invalidating a refresh token. So I could prompt a user to sign in when `acquireTokenSilent` fails. After your comment I see it won't work this way.
> Looks like I need to implement a custom solution for tracking session timeout. E.g. store the time of the last request to the backend and make an explicit logout if the next request is made more than 1 hour since the previous one.
> Do I get it right?

In theory, that could work, yes.

**Comment by jasonnutter** [comment]
> @sai-nagarjuna-t ....there is no way for MSAL.js to know if a user's session has ended if user's session is ended outside the context of the MSAL `logout` function.

@sai-nagarjuna-t Correction about this statement. Your application can be informed when other applications end the current session by configuring the "Logout URL" on your app registration in the portal. When another application in the user's browser performs a logout, the "Logout URL" registered in the portal for your app will be loaded. When this url is loaded, you can have your application invoke the MSAL logout function (or you can manually clear cache). We will have documentation with more details and example soon.

**Comment by sai-nagarjuna-t** [comment]
> > @sai-nagarjuna-t ....there is no way for MSAL.js to know if a user's session has ended if user's session is ended outside the context of the MSAL `logout` function.
> 
> @sai-nagarjuna-t Correction about this statement. Your application can be informed when other applications end the current session by configuring the "Logout URL" on your app registration in the portal. When another application in the user's browser performs a logout, the "Logout URL" registered in the portal for your app will be loaded. When this url is loaded, you can have your application invoke the MSAL logout function (or you can manually clear cache). We will have documentation with more details and example soon.
> 
> ![image](https://user-images.githubusercontent.com/443409/98189624-2bae4380-1eca-11eb-8836-6cf3c0c24879.png)

Thanks @jasonnutter 
So if I understand correctly, if the user is logged in multiple tabs in a browser then by configuring the logout URL, if the user manually logs out of the application in a particular tab then we can log him out from the other tabs as well ? 

Please correct me if I am wrong.

**Comment by jasonnutter** [comment]
@sai-nagarjuna-t Correct. If your user has two tabs open, appA.com and appB.com, both logged into the same account, when the user logs out from appA.com, the logout URL for appB.com will be loaded inside an iframe. This is signal to appB.com to logout the user from appB.com.

**Comment by sai-nagarjuna-t** [comment]
Thanks @jasonnutter . 
Apologies for one last question, 
I have configured the logoutURL and opened two tabs with appA.com and logged out of one of the tabs, am I expected to logout from the other tab ?

**Comment by jasonnutter** [comment]
@sai-nagarjuna-t This will not work if you are using sessionStorage, as sessionStorage is not shared between tabs. localStorage will be though.
