### ISSUE TITLE
Failed to initialize: SyntaxError when migrating from from MSAL v1 to MSAL v2

### ISSUE THREAD

**Issue by kostrse** [AzureAD/microsoft-authentication-library-for-js#2539]
## Library
- [x] `msal@1.4.1`
- [x] `@azure/msal-browser@2.4.1`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

When migrating existing website from MSAL v1 to MSAL v2, users who already have cached data in local storage see error message suggesting that local cache cannot be parsed.

## Error Message

```
SyntaxError: Unexpected token c in JSON at position 0
    at JSON.parse (<anonymous>)
    at t.getIdTokenCredential (index.es.js:7213)
    at t.e.getSpecificCredential (index.es.js:3008)
    at index.es.js:2697
    at Array.forEach (<anonymous>)
    at t.e.getCredentialsFilteredByInternal (index.es.js:2690)
    at t.e.getCredentialsFilteredBy (index.es.js:2671)
    at t.e.saveAccessToken (index.es.js:2603)
    at t.e.saveCacheRecord (index.es.js:2588)
    at e.<anonymous> (index.es.js:4405)
```

## MSAL Configuration

```ts
    const msalConfig: Configuration = {
      auth: {
        clientId: '<CLIENT_ID>',
        authority: 'https://login.microsoftonline.com/organizations',
        redirectUri: window.location.origin + '/callback',
      },
      cache: {
        cacheLocation: 'localStorage',
      },
    };

    const msal = new PublicClientApplication(msalConfig);

    // In case if we just successfully logged in, then initialize from the authentication result
    const loginResult = await msal.handleRedirectPromise();
    if (loginResult) {
      return loginResult.account;
    }

    // Try to find an already logged in user, if any present in the browser
    let accounts = msal.getAllAccounts(); // THROWS HERE
```

## Expected behavior

If MSAL v2 library is unable to reuse the local data left by MSAL v1, then it should ignore it without crashing.

## Browsers/Environment
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jasonnutter** [comment]
Please try `@azure/msal-browser@2.5.2` and let us know if this is still an issue, thanks!

**Comment by kostrse** [comment]
Updated to `@azure/msal-browser@^2.7.0` and `@azure/msal-common@^1.7.2`

See another error for previously signed in user:
```
ClientAuthError: no_tokens_found: No tokens were found for the given scopes, and no authorization code was passed to acquireToken. You must retrieve an authorization code before making a call to acquireToken().
    at Function.t.createNoTokensFoundError
    at new Promise (<anonymous>)
    at t.acquireTokenWithCachedRefreshToken
```

**Comment by tnorling** [comment]
@kostrse This error is thrown when you call `acquireTokenSilent` before calling an interactive method such as one of the login methods or `acquireTokenPopup` or `acquireTokenRedirect` due to the fact that a refreshToken has not been obtained yet. Your app should catch this error and call an interactive method. If you are using `loginRedirect` or `acquireTokenRedirect` you should also make sure that `handleRedirectPromise` has resolved before calling `acquireTokenSilent`

**Comment by tnorling** [comment]
Closing as the question was answered and the issue has not seen any activity since.
