### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by spottedmahn** [AzureAD/microsoft-authentication-library-for-js#254]
Where can I find the release notes for each version?  More specifically, where can I find the release notes for version 0.1.4?  Thanks!

**Comment by rohitnarula7176** [comment]
@spottedmahn There should be a changeLog.md file in the repo https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/rn/catchHandler/changelog.md.

**Comment by spottedmahn** [comment]
FYI, the [`loadFrameTimeout`](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/209) is missing from the change log.

**Comment by navyasric** [comment]
@spottedmahn You can also see release notes here: https://github.com/AzureAD/microsoft-authentication-library-for-js/releases
