### ISSUE TITLE
window.crypto.subtle is undefined on iOS 10 Safari

### ISSUE THREAD

**Issue by ArktinenSieni** [AzureAD/microsoft-authentication-library-for-js#2543]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.1.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- React

## Description

While attempting to log in using `PublicClientApplication` `loginRedirect`, it fails on iOS 10 devices. iOS 11 and beyond seem to work.

The error message complains about `window.crypto.subtle` being undefined. `window` and `crypto` are both existing, but in iOS 10 device, `subtle` is undefined. I wonder if it is the same as `window.crypto.webkitSubtle`, which can be found from the context.

I tested this with BrowserStack with a iOS 10 device, using Safari since it was the only one including dev-tools.

I assume that the issue lies here:
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/fc150c85612660d20f14e823ca32495a75b0b312/lib/msal-browser/src/crypto/BrowserCrypto.ts#L139

## Error Message

```
{
    "line": 927,
    "column": 24,
    "sourceURL": "http://bs-local.com:5000/static/js/1.chunk.js",
    "errorCode": "pkce_not_created",
    "errorMessage": "The PKCE code challenge and verifier could not be generated. Detail:TypeError: undefined is not an object (evaluating 'window.crypto.subtle.digest')",
    "name": "BrowserAuthError"
}
```

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before?

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.

const MSAL_CONFIG: Configuration = {
  auth: {
    clientId: "my-client-id",
    authority: b2cPolicies.authorities.signUpSignIn.authority,
    knownAuthorities: [
      b2cPolicies.authorities.signUpSignIn.authority,
      b2cPolicies.authorities.forgotPassword.authority,
    ],
    redirectUri: appRoot,
    postLogoutRedirectUri: appRoot,
  },
  cache: {
    cacheLocation: "sessionStorage", // This configures where your cache will be stored
    storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
  },
  system: {
    loggerOptions: {
      loggerCallback: (level, message, containsPii) => {
        if (containsPii) {
          return;
        }
        switch (level) {
          case LogLevel.Error:
            console.error(message);
            return;
          case LogLevel.Info:
            console.info(message);
            return;
          case LogLevel.Verbose:
            console.debug(message);
            return;
          case LogLevel.Warning:
            console.warn(message);
            return;
        }
      },
    },
  },
};
```

## Reproduction steps
```js
// This should result in error using device with iOS 10.
const msalInstance = new PublicClientApplication(MSAL_CONFIG);

msalInstance.loginRedirect(loginRequest).catch(e => {
        console.log("*************");
        console.log(JSON.stringify(e, null, 4));
        console.log("*************");
      });
```

## Browsers/Environment
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [x] Safari 
- [ ] IE
- [x] Other (Safari on iOS 10)

**Comment by jasonnutter** [comment]
Unfortunately, iOS 10.2 and below does not support the standard `SubtleCrypto`, instead supporting [Safari's non-standard `webkitSubtle`](https://webkit.org/blog/7790/update-on-web-cryptography/). Given that the standard `SubtleCrypto` APIs should be supported [in 10.3 and above](https://caniuse.com/mdn-api_subtlecrypto), and the relatively low usage of iOS 10, I think it is unlikely we will prioritize supporting older browsers like iOS Safari that do not support the standard APIs.

You are welcome to open a PR adding support for these APIs for us to consider. You can also look at polyfills such as [MSR Crypto](https://github.com/microsoft/MSR-JavaScript-Crypto).
