### ISSUE TITLE
MSAL-Browser: Can't logout user. Logout function is not working properly.

### ISSUE THREAD

**Issue by pedoe** [AzureAD/microsoft-authentication-library-for-js#2547]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.5.1`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Can't logout user by using logout function. The user will be re-authenticated automatically and there is no chance to change the user account or select different user account. I have to clear the browsing data - "Cookies and other site data" then i can change the user account.

I used the [MSAL 2.0 typescript sample code](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-browser-samples/TypescriptTestApp2.0)

## MSAL Configuration
```js
// configuration from MSAL 2.0 typescript sample code
const MSAL_CONFIG: Configuration = {
    auth: {
        clientId: "client-id"
    },
    cache: {
        cacheLocation: "sessionStorage", // This configures where your cache will be stored
        storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
    },
    system: {
        loggerOptions: {
            loggerCallback: (level, message, containsPii) => {
                if (containsPii) {	
                    return;	
                }	
                switch (level) {	
                    case LogLevel.Error:	
                        console.error(message);	
                        return;	
                    case LogLevel.Info:	
                        console.info(message);	
                        return;	
                    case LogLevel.Verbose:	
                        console.debug(message);	
                        return;	
                    case LogLevel.Warning:	
                        console.warn(message);	
                        return;	
                }
            }
        }
    }
};
```
## Reproduction steps
1. User will see the signIn button at first time.
![image](https://user-images.githubusercontent.com/14311331/98200459-8784c680-1ee2-11eb-900c-0e26a5316320.png)
2. Click signIn button will need user to provide login info at first time.(use redirect login)
![image](https://user-images.githubusercontent.com/14311331/98200102-b6e70380-1ee1-11eb-95dc-72526b5dd814.png)
3. Login success
![image](https://user-images.githubusercontent.com/14311331/98200572-bbf88280-1ee2-11eb-9bcf-f04bb2dbc5ee.png)
4. Click logout button, user will be redirected to website again and see the signIn button
![image](https://user-images.githubusercontent.com/14311331/98200697-04b03b80-1ee3-11eb-9d87-089930da22ed.png)
5. Click signIn button, user will **login immediately** without provide any login info, and user can't select different account. It supposed to redirect user to the page like step2, and ask user to provide the credential info.
![image](https://user-images.githubusercontent.com/14311331/98200828-46d97d00-1ee3-11eb-99c2-268731431cf7.png)
6. Have to clear the browsing data - cookie and  other site data then i can see the login page like step2
![image](https://user-images.githubusercontent.com/14311331/98201568-cfa4e880-1ee4-11eb-848e-bdd6d0c0e169.png)

## Expected behavior
The user should be logout and need to provide login information when the use visit the website again.

## Browsers/Environment
- [x] Chrome
- [ ] Firefox
- [x] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jasonnutter** [comment]
@pedoe You can prompt the user to login by passing `prompt: "login"` when invoking the login APIs:

```js
msalInstance.loginPopup({
  prompt: "login" // "select_account" will force account selection
})
```

**Comment by pedoe** [comment]
@jasonnutter But we should not force account selection or user login every time if user didn't logout from our portal right? Users should login immediately if they didn't click logout before. Use prompt: "login" will ask user to provide login info every time. Is there any way to clear all the user data when invoking logout API? Thanks!

**Comment by tnorling** [comment]
@pedoe After clicking the logout button you should be redirected to the AAD signout page where you are given the option to select an account to sign out of. It's not clear from your description above if you went through this account selection process. Can you confirm?

**Comment by lemenhir** [comment]
I have the same problem of not being able to logout but I am using @azure/msal-angular@1.1.2
Also, it seems that the problem presents itself only for some users and not for others...

**Comment by tnorling** [comment]
> And after asking for logout I am not redirected to the aad signout page where you are given the option to select an account to sign out of.

@lemenhir This is why logout isn't working properly for you. Selecting the account on the aad signout page is how the service knows to clear the user's session data. Are you using AAD or B2C?

**Comment by lemenhir** [comment]
> @lemenhir This is why logout isn't working properly for you. Selecting the account on the aad signout page is how the service knows to clear the user's session data. Are you using AAD or B2C?

I am using B2C

**Comment by tnorling** [comment]
@lemenhir This is expected behavior when using B2C, you can read more about this [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/working-with-b2c.md#b2c-and-sign-out-experience) and in our [FAQ](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md#i-logged-out-of-my-application-why-am-i-not-asked-for-credentials-when-i-try-to-log-back-in)

**Comment by iZagi** [comment]
I am using AAD and still have the same issue. The logout request gets canceled when called by the msal logout function and i get redirected to localhost:44326/# , oddly when i copy the same url that is canceled and call it manualy by pasting it in the url bar, it works as expected.

https://login.microsoftonline.com/{authorityString}/oauth2/v2.0/logout?post_logout_redirect_uri=https%3A%2F%2Flocalhost%3A44326%2Fhome%2Fdashboard%2Fns&client-request-id=0366dc43-57e4-4ba6-8377-cd6f8d53ba3c

Let me know if need to add some additional information. I've used the angular10 sample as guideline. 
    "@azure/msal-browser": "^2.7.0",
    "@angular/core": "~8.2.14",
    "msal": "^1.4.4",

**Comment by tnorling** [comment]
@iZagi Is there any error in the console or on the network request that might provide a clue as to why it gets cancelled? Are you perhaps trying to initiate logout from an iframe?

Also are you using msal@1.4.4 or msal-browser@2.7.0? You mentioned both...

**Comment by iZagi** [comment]
@tnorling we've migrated from msal 1.4.4 to msal-browser 2.7.0, i did recheck, we are using only msal-browser now, during a bit of research i've noticed we didnt use hashlocation strategy, after setting it to true, the logout started to work as intented. Is there a way to avoid using "useHash:true" in the router or its mandatory for the framework to work?

**Comment by tnorling** [comment]
@iZagi "useHash:true" is not required for msal-angular to work. Can you clarify what is not working or not happening? Is it not redirecting to the logout url? Can you also try setting the `post_logout_redirect_uri` to your homepage?
