### ISSUE TITLE
Unsafe JavaScript attempt to initiate navigation for frame with origin 'https://xxx.xxx.net.au...

### ISSUE THREAD

**Issue by paranthamanwp** [AzureAD/microsoft-authentication-library-for-js#2548]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-angular@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
"msal": "^1.4.1",
"@azure/msal-angular": "^1.1.1",

## Description
The user automatically navigate to logout with below error message 

## Error Message
Unsafe JavaScript attempt to initiate navigation for frame with origin 'https://xxx.xxx.net.au' from frame with URL 'https://login.microsoftonline.com/xxxx/oauth2/v2.0/authorize?response_type=token&scope=api%3A%2F%2FXXXXX%2Fuser_impersonation%20openid%20profile&client_id=XXXXX&redirect_uri=https%3A%2F%2Fxxx.xxx.x.cmltd.net.au&state=eyJpZCI6Ijc4NjU4M2E4LWZlN2QtNDI4OS04Mzk3LTk0NzdjNWRlMWZmNyIsInRzIjoxNjA0NTYxMDI0LCJtZXRob2QiOiJzaWxlbnRJbnRlcmFjdGlvbiJ9&nonce=014cffb4-dc46-4424-8d0a-93720a192002&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=1.4.0&login_hint=xxx&client-request-id=xx&prompt=none&response_mode=fragment'.

## Security
- [ ] Is this issue security related? No

## Regression
- [ ] Did this behavior work before? No
Version:

## MSAL Configuration
app.module.ts

function MSALConfigFactory(): Configuration {
return {
auth: {
clientId: environment.clienId,
authority: environment.msLoginUrl + environment.tenantId,
validateAuthority: true,
redirectUri: environment.redirectUrl,
postLogoutRedirectUri: environment.postLogoutRedirectUrl,
navigateToLoginRequestUrl: true,
},
cache: {
cacheLocation: 'sessionStorage',
storeAuthStateInCookie: false, // set to true for IE 11
},
};

function MSALAngularConfigFactory(): MsalAngularConfiguration {
return {
popUp: false,
consentScopes: environment.scopeUri,
protectedResourceMap: [
[apiURL.ApiURL1, environment.scopeUri],
[apiURL.ApiURL2, environment.scopeUri],
],
extraQueryParameters: {}
};
}

app.component.ts

ngOnInit(): void {

     this.authService.handleRedirectCallback((authError, response) => {
        if (authError) {
            console.error('Redirect Error: ', authError.errorMessage);
            return;
        }
    });

    
        **this.broadcastService.subscribe('msal:acquireTokenFailure', (error) => {
            this.authService.loginRedirect({ scopes: environment.scopeUri });
        });**
	**//reach else second time onwards and api calling from home screen failed acquiretoken firsttime**
      if (!this.authService.getAccount()) {
        this.authService.loginRedirect({ scopes: environment.scopeUri });
      } else {
        this.router.navigateByUrl('/home');
      }
}

**Note:** I am suspecting that the error occurred on the above highlighted loginredirect but its required

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
issue occurred when open the base url in new window or tab in chrome

```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Expected behavior
should not navigate to logout page

## Browsers/Environment

- [ ] Chrome

**Comment by jasonnutter** [comment]
@paranthamanwp Can you please the `client-request-id` from the url? This will help me lookup logs for your request. Also, what happens when you load the `login.microsoftonline.com` url in its own tab?

**Comment by paranthamanwp** [comment]
client id : 593de8b7-8747-4b3b-a0c2-57aa7c8c2b46

**Comment by jasonnutter** [comment]
@paranthamanwp That error ("client request loop") is thrown when your application is making too many requests for tokens in a short period of time. I would recommend upgrading to the latest version of `msal@1.4.3`, as it should help reduce the occurrence of that error.

**Comment by paranthamanwp** [comment]
Hi @jasonnutter, I have updated the version "msal": "^1.4.3", but still same error occurred and I suspect this is happening because of the acquiretokenfailure and recalling the loginredirect as I mentioned in the open **bug  #2535** (https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2535) which I raised previous this.  Could you please help?

**Comment by paranthamanwp** [comment]
Can u please help

**Comment by paranthamanwp** [comment]
Hi Team, Any update on this?

**Comment by jasonnutter** [comment]
@paranthamanwp Apologies for the delay in responding. Can you please provide the `client-request-id` from the URL in teh screenshot above (or from a similar error)?

**Comment by derkoe** [comment]
I have the same issues - `client-request-id=85b85525-a1b6-4541-b10f-efac70a14414`

**Comment by paranthamanwp** [comment]
client-request-id=2def2b18-e04e-41a7-ac8b-afa98d2bd5b4

https://login.microsoftonline.com/82551a12-bbc8-4fed-8b7f-2b758284b5ea/oauth2/v2.0/authorize?response_type=id_token&scope=api%3A%2F%2F593de8b7-8747-4b3b-a0c2-57aa7c8c2b46%2Fuser_impersonation%20openid%20profile&client_id=593de8b7-8747-4b3b-a0c2-57aa7c8c2b46&redirect_uri=****.net.au&state=eyJpZCI6IjQ1ZTM0NGJkLTQwYTUtNDg0Ny05OWNkLWJhNmJiMjBhNjcyOCIsInRzIjoxNjA2OTA2ODQxLCJtZXRob2QiOiJyZWRpcmVjdEludGVyYWN0aW9uIn0%3D&nonce=b2da83cb-f0c8-4122-acd1-84c051579bc8&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=1.4.4&client-request-id=2def2b18-e04e-41a7-ac8b-afa98d2bd5b4&response_mode=fragment

**Comment by paranthamanwp** [comment]
any updates?

**Comment by jasonnutter** [comment]
@paranthamanwp Apologies again for the delay. I've been unable to determine why this is happening, but I would interested to know if these issues still happen if you upgrade to MSAL v2 and MSAL Angular v2: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/1.x-2.x-upgrade-guide.md

**Comment by paranthamanwp** [comment]
np, still the issue happen when open the page in multiple tab same time.
