### ISSUE TITLE
handleRedirectPromise response null for Firefox in private mode

### ISSUE THREAD

**Issue by didair** [AzureAD/microsoft-authentication-library-for-js#2549]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.5.2`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
After a sign in using loginRedirect handleRedirectPromise fails using Firefox in private window. I get back the #code in the url and the promise resolves with response null and doesnt throw an exception.

Only replicated in Firefox private. Works in Safari & Chrome (with and without private).

## Security
- [ ] Is this issue security related?

## Regression
- [x] Did this behavior work before? 
Version: 2.3.1

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
	auth: {
		clientId: '',
		authority: 'https://login.microsoftonline.com/common/',
		postLogoutRedirectUri: window.location.origin + '/',
		redirectUri: window.location.origin + '/',
		navigateToLoginRequestUrl: false,
	},
	cache: {
		cacheLocation: "localStorage",
		storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
	},
```

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Expected behavior
loginResponse should contain user session or handleRedirectPromise should throw an error.

## Browsers/Environment
- [ ] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jasonnutter** [comment]
@didair This is happening because Firefox is clearing localStorage when you navigate to the login page, and as a result, when you get redirected back to your app, MSAL.js does not think there is a pending redirect request in progress. To mitigate this, enable `cache.storeAuthStateInCookie` in Firefox.

**Comment by didair** [comment]
@jasonnutter Yes that resolved our issues. Thanks!
