### ISSUE TITLE
we cannot add a separate public api getClaim() on user object, why not?

### ISSUE THREAD

**Issue by spottedmahn** [AzureAD/microsoft-authentication-library-for-js#255]
As stated [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/169#issuecomment-356477876)

>unfortunately we cannot add a separate public api getClaim() on user object as then we will have to enable that same api on all other MSAL libraries

I understand your desire to have the same public API across all MSAL libraries but I don't understand why other libraries wouldn't want this? What am I missing?

**Comment by spottedmahn** [comment]
Any thoughts 💭?

**Comment by rohitnarula7176** [comment]
@spottedmahn We discussed this with the team and the decision was to just expose the id_token object on the user object and not adding a separate getClaim method. 

The decision was made by taking in account that the actual code to query claims on the id_token object should be very minimal and hence eliminating the need for a separate api.

**Comment by spottedmahn** [comment]
>was to just expose the id_token

That makes sense, provides unlimited flexibility.

>not adding a separate getClaim method.

Then all of us will be writing the same helper method in our respective code bases 😜

---
Anyways, for the reply!

**Comment by Tovli** [comment]
This is just a one liner:
JSON.parse(atob(this.jwt.split('.')[1]))
and it is actually giving you incentive to create a facade over the msaljs lib. so you can have an API that is better for your needs and abstract the use of this external lib.

Everyone is happy :)
