### ISSUE TITLE
Unable to login on IOS 14.1 issue caused by .acquireTokenSilent(), stuck in a refresh loop

### ISSUE THREAD

**Issue by michaelchunD** [AzureAD/microsoft-authentication-library-for-js#2552]
## Library
- [x] `msal@1.4.3` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework
"msal": "^1.4.3",
"react": "^16.12.0",

## Description

This issue is only occurring on IOS 14.1 regardless of the device model i.e. iphone 11, 7+, etc.
We are unable to reproduce the issue on desktop browsers and Andriod browsers. This issue did not occur on IOS 12.4.

Once a user successfully logs on a b2c login page, the user is redirected back to our website, and when we're trying to fetch user data an error occurs and refreshed the page.
The error occurs when we trigger the .acquireTokenSilent() function, from the verbose logs we can see that Request RENEW_TOKEN is returning an error.

I have added full logging to see where the issue occurs and to see how it compares with the desktop logs.
I have uploaded screenshots for desktop and ios to this ticket.

Is this issue occurring to any other developers using this library? Could this issue be caused by a software update from Apple's side?

## Error Message
The image on the right shows Desktop logs, the image on the left shows IOS Chrome logs.
![Difference 2](https://user-images.githubusercontent.com/53840105/98302065-ac7f5380-2020-11eb-8cc4-e7e7dbb7b710.png)

State status: true; Request type: RENEW_TOKEN
Server returned an error

InteractionRequiredAuthError: AADB2C90077: User does not have an existing session and request prompt parameter has a value of 'None'.

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version: The issue also occurs on msal 1.4.0

## MSAL Configuration

```js
const init = (auth, toggleLoading) => {
    authentication = auth;
    console.log('B2C init');
    console.log(window.location.href);
    //MSAL configuration
    myMSALObj = new Msal.UserAgentApplication({
        auth: {
            clientId: authentication.clientId,
            authority: authentication.signUpSignInUrl,
            validateAuthority: authentication.validateAuthority,
            postLogoutRedirectUri: authentication.postLogoutRedirectUri,
            navigateToLoginRequestUrl: false,
        },
        cache: {
            cacheLocation: authentication.cacheLocation,
            storeAuthStateInCookie: authentication.storeAuthStateInCookie,
        },
        system: {
            navigateFrameWait: 0,
            logger: new Msal.Logger(
                loggerCallback,
                {
                    level: Msal.LogLevel.Verbose,
                    piiLoggingEnabled: false,
                }
            )
        },
    });
...
}
...
```

## Reproduction steps

Issue occurs when triggering the {msalObject}.acquireTokenSilent() function on IOS 14.1 (Both physical device and simulator).

Our login flow:
1. As an IOS 14.0 user, open Google Chrome application.
2. Go to the home page.
3. Click on login button in the header, takes user to b2c login page.
4. User completes login form and submits.
5. The page is stuck in a loop where the page is constantly refreshing.

```js
const isLoggedIn = async () => {
    console.log("isLoggedIn: check is Logged In");
    if (myMSALObj && myMSALObj.getAccount()) {
        const accessTokenRequest = {
            scopes: authentication.tokenRequestScopes,
        }
        try {
            if (!isEditMode() && myMSALObj) {
                console.log("isLoggedIn: !isEditMode() && myMSALObj true");
                const accessTokenResponse = await myMSALObj.acquireTokenSilent(accessTokenRequest); //Issue occurs when triggering this function
                console.log("isLoggedIn: acquireTokenSilent(accessTokenRequest)");
                console.log(JSON.stringify(accessTokenResponse));
                return accessTokenResponse.accessToken;
            }
            console.log("isLoggedIn: !isEditMode() && myMSALObj false");
        } catch (e) {
            if (e) {
                console.log("isLoggedIn: error");
                console.log(e);
                clearLocalCache();
                myMSALObj.clearCache();
            } else {
                console.log("Generic error");
                console.log(e);
            }
        }
    }
    return false;
}
```

## Expected behavior

User is redirected to our website once the user has completed the login form.

## Browsers/Environment
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [x] Other (Chrome on IOS 14.1)

**Comment by jasonnutter** [comment]
@michaelchunD This is a known issue for browsers such as mobile Safari that have privacy features such as Intelligent Tracking Protection enabled. In MSAL.js v1, your application should invoke one of the interactice methods (acquireTokenPopup or acquireTokenRedirect) when `acquireTokenSilent` throws an `InteractionRequiredAuthError` to complete token acqusition.

Alternatively, you can upgrade to `@azure/msal-browser`, which does not use hidden iframes for silent token acquisition and thus is not susceptible to aforementioned privacy features in most scenarios.

- https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/v1-migration.md
- https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/working-with-b2c.md

**Comment by tnorling** [comment]
Closing as the question was answered.
