### ISSUE TITLE
LocalAccountId should be always expected in AccountInfo and shouldn't have nullable type

### ISSUE THREAD

**Issue by kostrse** [AzureAD/microsoft-authentication-library-for-js#2553]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@dev`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

Recent PR #2516 added `localAccountId` to `AccountInfo` and it was added as an nullable field (`string?`):
```ts
export type AccountInfo = {
    homeAccountId: string;
    environment: string;
    tenantId: string;
    username: string;
    name?: string;
    localAccountId?: string;
};
```

If `oid` claim is present in ID token, then `localAccountId` is set to `oid`, otherwise it set to a value of `sub` claim.

From the code [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/6624336aafe2bc95a90bfe751667a26f2dde64d6/lib/msal-common/src/cache/entities/AccountEntity.ts#L155-L157):

```ts
const localAccountId = !StringUtils.isEmpty(idToken.claims.oid)
    ? idToken.claims.oid
    : idToken.claims.sub;
```

`oid` is optional claim which is present in ID token only if `profile` scope was requested, but `sub` is a required claim according to Open ID Connect specification:
https://openid.net/specs/openid-connect-core-1_0.html#IDToken

It means that `localAccountId` is always have a value, same as every user always have a unique ID.

Please make the `localAccountid` as a required field in `AccountInfo`, so it would make code that consumes `AccountInfo` cleaner.

**Comment by sameerag** [comment]
Will do. Please expect a PR soon.

**Comment by sameerag** [comment]
#2559 addresses this!
