### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by CerosDev** [AzureAD/microsoft-authentication-library-for-js#2555]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.4.0` and after
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Description

In msal-browser 4.0.0, `BrowserStorage` was implementing abstract class `CacheManager` from msal-common 1.6.2

Starting from msal-browser 4.0.1, `BrowserStorage` is implementing a new interface `IWindowStorage`.
Meanwhile, `CacheManager` from msal-common 1.6.3 gained new abstract functions.

So far, everything fits together. But now with msal-browser 4.5.2, I'm having issue #2524. 
So now I'm trying to downgrade back to 4.0.0 but I get many compile errors saying that `BrowserStorage` does not implement xyz from abstract class `CacheManager`

Turns out that the `msal-common` dependency in `msal-browser`'s package.json is using a caret (^1.6.2) so npm is just always downloading the latest which is 1.6.3, which now has additional abstract function in `CacheManager`.

So I'm currently stuck. I can't downgrade, and I can't use latest msal-browser because of the issue.

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Browsers/Environment
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jasonnutter** [comment]
@CerosDev Apologies for the inconvenience, we will look to have #2516 released soon.

**Comment by CerosDev** [comment]
@jasonnutter We can close this. I just wanted to let you know these side-effects
