### ISSUE TITLE
Error on Chrome extension startup

### ISSUE THREAD

**Issue by directcuteo** [AzureAD/microsoft-authentication-library-for-js#2557]
Hi. I am using the MsalAngular library in a chrome extension and in a web application.
Everything is working fine in the web app, but not in the extension app.

I am receiving an error on startup of the extension, without even trying to aquire a token, or login, or check anything (I basically use Msal just in the AppModule to import the required modules/configs/interceptors).

Here is the error just after the app has started:
![image](https://user-images.githubusercontent.com/37619567/98398129-220f1200-2069-11eb-946c-eff488c5d0c5.png)

The error seems to be inside MsalService. I mention that the error doesn't show if I start the extension app as a web application (using ng serve and going to localhost:4200) and I also mention that there is not a single request made (not even for a font) so I don't know why is it complaining about.

I ask for guidance, thank you very much.

**Comment by jasonnutter** [comment]
@directcuteo Can you please provide logs from the MSAL logger?

**Comment by directcuteo** [comment]
![image](https://user-images.githubusercontent.com/37619567/98635167-25d2bb00-232d-11eb-9686-4653d07c682e.png)

I have enabled the logs like on the npm Msal page, this is what I get in the console.

**Comment by jasonnutter** [comment]
Apologies for the delay. That log message indicates that MSAL is trying to acquire a token using clientId as the scope. This likely means that your app is using the MSAL Interceptor, and making an http request to an API in your app (e.g. `http://localhost:4200/api/`). By default, the MSAL Interceptor will attempt to acquire an access token for those requests. You can mitigate this logic by determining the path for these requests, and then setting `null` as the scopes in the `protectedResourceMap`, as detailed in #2515. You can also try upgrading to MSAL Angular v2, where we have removed this logic in the MSAL Interceptor.
