### ISSUE TITLE
B2C - error trying to redirect to different login pages 

### ISSUE THREAD

**Issue by ranros** [AzureAD/microsoft-authentication-library-for-js#2561]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.4.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
I have a scenario which I don't know if possible with B2C. 

I want to redirect the user to a login page which I get dynamically from the server based on user's input in 'organization' field (authority and client Id are different for each organization and the requirement is not to give the client all the available authorities in advance).

Every login, I create a new instance with clientId and authority I get from the server, but it looks like the authority is cached. If I login and logout, and then login to a different organization I get an error:

> endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter.

The code to get the instance:
```js
export const getInstance = (clientId, authority) => {
  return new msal.PublicClientApplication({
    auth: {
      clientId: clientId,
      authority: authority,
      knownAuthorities: [authority],
      navigateToLoginRequestUrl: true,
      redirectUri: getRedirectUri(),
      validateAuthority: false
    },
    cache: {
      cacheLocation: "localStorage", 
      storeAuthStateInCookie: false 
    },
    system: {
      windowHashTimeout: 60000,
      iframeHashTimeout: 6000,
      loadFrameTimeout: 6000
    }
  });
};
```

Please help me to understand if this is a bug, or if there should be other way to achieve the requirement in B2C
Thanks!
Ran

**Comment by jasonnutter** [comment]
@ranros Can you please provide your code showing how you invoke the login APIs (i.e. loginPopup, loginRedirect, etc)?

**Comment by ranros** [comment]
@jasonnutter 
- Before login I store in local storage the company, clientId, authority (according to the dynamic configuration)
- Then:
`const msalInstance = getInstance(clientId, authority);
  await msalInstance.loginRedirect({
    scopes: ["openid"],
  });`

- First time it works great. 

Issue occurs if for example I cancel the login, or log out, and page is redirected to the app. On init I call _getInstance_ with one authority. Then I try to login again with a different authority. I call msal.PublicClientApplication with the new authority but it seems it caches the old one.

**Comment by ranros** [comment]
Hi any news?

**Comment by tnorling** [comment]
@ranros Apologies for the delay on this. I was able to reproduce this and confirm this is a bug. Will try to have a fix available soon.
