### ISSUE TITLE
Which property on AuthenticationResult is the user ID?

### ISSUE THREAD

**Issue by sam-wheat** [AzureAD/microsoft-authentication-library-for-js#2562]
var z = await this.myMSALObj.loginPopup(this.loginRequest);

Of the properties on object `z`, which is the one that has a value that corresponds with the id of the user as defined in active directory?

![Capture](https://user-images.githubusercontent.com/16885210/98445187-16543780-20cb-11eb-8032-42353c33a859.PNG)

The reason I ask is because I have three users in my AD with the same user name:

9e32d9eb-fe41-4ff3-a351-28d47c5f099e
7aee9e27-4767-4479-a9f3-a1816e3a2b24
33c2780f-b5c6-41d5-bd03-98668c36b0d8

I logged in as one of them.  Here is the result.  How can I tell which user I logged in as?

![Capture](https://user-images.githubusercontent.com/16885210/98445490-e0b04e00-20cc-11eb-9492-bf0da91e1d14.PNG)

**Comment by sam-wheat** [comment]
Discovered the github bug that bypasses the template.  If you click "create issue" before logging in you bypass the issue template.  Raised a new issue using the template.

**Comment by jasonnutter** [comment]
@sam-wheat Interesting, good to know.
