### ISSUE TITLE
Which property on AuthenticationResult is the user ID?

### ISSUE THREAD

**Issue by sam-wheat** [AzureAD/microsoft-authentication-library-for-js#2564]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Please provide your question here, including as much relevant details as possible.

    var z = await this.myMSALObj.loginPopup(this.loginRequest);

Of the properties on object `z`, which is the one that has a value that corresponds with the id of the user as defined in active directory?

![Capture](https://user-images.githubusercontent.com/16885210/98445187-16543780-20cb-11eb-8032-42353c33a859.PNG)

The reason I ask is because I have three users in my AD with the same user name:

9e32d9eb-fe41-4ff3-a351-28d47c5f099e
7aee9e27-4767-4479-a9f3-a1816e3a2b24
33c2780f-b5c6-41d5-bd03-98668c36b0d8

I logged in as one of them.  Here is the result.  How can I tell which user I logged in as?

![Capture](https://user-images.githubusercontent.com/16885210/98445490-e0b04e00-20cc-11eb-9492-bf0da91e1d14.PNG)

**Comment by sam-wheat** [comment]
Related to `uniqueId`, [this document](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.authenticationresult?view=azure-dotnet) states: "Gets the Unique Id of the account. It can be null. When the IdToken is not null, this is its ID, that is its ObjectId claim, or if that claim is null, the Subject claim."  

However the uniqueId's I see don't match object ID of any users on my AD.

**Comment by sam-wheat** [comment]
Apparently the config found [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-browser-samples/TypescriptTestApp2.0/src/AuthModule.ts) is actually valid:

const MSAL_CONFIG: Configuration = {
    auth: {
        clientId: "2eb9245f-612b-46cc-994a-f5e35ef37da0"
    },

[Per this](https://azuread.github.io/microsoft-authentication-library-for-js/ref/msal-browser/modules/_src_config_configuration_.html):

> authority - You can configure a specific authority, defaults to " " or "https://login.microsoftonline.com/common"


This is what confused me.  If a random authority is defaulted, what is the purpose of the clientID?  

If a client ID is provided isn't a more suitable default provider the AD where the client is registered?

**Comment by jasonnutter** [comment]
@sam-wheat If you want to get the "Object ID" (from the portal as shown in your screenshot) for the current user, your application should make a request to [MS Graph profile endpoint](https://docs.microsoft.com/en-US/graph/api/user-get?view=graph-rest-1.0&tabs=http), which will return an `id` property matching the "Object ID" from the portal.

Note, this will require obtaining an access token with the `user.read` scope. You can see the data returned from this endpoint in [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer?request=me&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com).

**Comment by sam-wheat** [comment]
Thank you Jason.  The problem I ran into is that I logged in as myself (using my email address) and the object that was returned does not exist on my AD.  The reason - I later found out - is that I did not provide an authority.  So the default authority was used.  No idea how/why it authenticated me.  
This is the origin of my question about client ID (which I did provide).  If a client ID is provided, doesn't it make sense to use the AD that the client belongs to instead of microsoftonline?

**Comment by jasonnutter** [comment]
@sam-wheat Correct, by default MSAL.js will use the common authority if none is provided, which supports both MSA and AAD accounts. If you want to ensure your users sign into your tenant, you can use the "tenanted authority": `https://login.microsoftonline.com/<tenantId>`, e.g. `https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad`. 

We use `/common` as the default because it is needed for multi-tenant applications.
