### ISSUE TITLE
Conditional Access check should be processed during initialization instead of throwing error during token acquire process.

### ISSUE THREAD

**Issue by pwang2** [AzureAD/microsoft-authentication-library-for-js#2565]
## Library
`@azure/msal-browser@2.6.0`

## Description
When conditional access like MFA applied, the login grant check is not handled during handleRedirectPromise but till acquireToken and throw following error..  This would generate a flood of same message for all tokenAcquire method.. 

## Error Message
AADSTS50078: Presented multi-factor authentication has expired due to policies configured by your administrator,

**Comment by jasonnutter** [comment]
@pwang2 Can you please email me a Fiddler trace demonstrating the existing behavior you observe? My email is in my profile, thanks!

**Comment by pwang2** [comment]
It seems a quite difficult thing to reproduce the scenario here.  I start to doubt if out IT admin do change the policy which invalidate the token acquire flow but not the handleRedirectionPromise flow. 

Is there any easy way to simulate the accessToken and renewToken expiry?

**Comment by jasonnutter** [comment]
> Is there any easy way to simulate the accessToken and renewToken expiry?

You can simulate an expired token by manually deleting the access token from local/session storage.

**Comment by pkanher617** [comment]
@pwang2 You can either delete the access token or change the expiresOn value in the cache to 0.

**Comment by pwang2** [comment]
Thank @jasonnutter and @pkanher617.  The expirary trick works. 

I think I have found more information regarding the renewToken [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#refresh-the-access-token) and as described,  application code supposed t handle all kinds of token request error.   

For SAP, the refresh (renew) token is good for 24 hrs.   So I think it could be the case that, our IT admin's MFA policy set a shorter period for every MFA authentication(less than 24hrs). I found another discussion in this Microsoft Community thread here(https://www.microsoftpartnercommunity.com/t5/Multi-Factor-Authentication-MFA/MFA-with-refresh-tokens-seems-to-have-expired-and-is-no-longer/m-p/15738), here is the answer from an MSFT employee.

>@crodriguez :
>Can you please check to turn the setting of "Remember MFA for x Days" off?
>https://docs.microsoft.com/en-us/azure/active-directory/authentication/howto-mfa-mfasettings#how-the-feature-works
>"When a refresh token is validated, Azure AD checks that the last two-step verification occurred within the specified number of days."
>(or test the opposite by setting it to one day lifetime and check if again your tokens are invalid after this timeframe -. then you can be sure it is this setting).
>This feature can actually force that interactive MFA in requested again after the specified days and thus your current tokens will be invalid. It would be great if you could update the thread on the result

I do not fully understand the employee's answer here but assume there is a rabbit hole somewhere here as the `errorCode` is not even mentioned in the documents and as devs, we have no control over how IT setup the AAD policy.   As a workaround, I forced page to reload when seeing AADSTS50078 in `errorMessage`.

Free free to close this issue or leave it on if we could have people contribute further.

**Comment by jasonnutter** [comment]
@pwang2 Thanks for the update, glad you figured it out!

**Comment by pwang2** [comment]
Hi, @jasonnutter, finally, I was managed to understand the case better as well as get more details about this.

In our case, MFA policy requires every 12hrs need to reauthorize using MFA. After the maximum lifespan of MFA policy ends, while the refreshToken is still valid (24hours for AuthorizationCode flow), MSAL will NOT redirect to the authorization endpoint when we initialize the MSAL app as below.

```
  const msalApp = new PublicClientApplication(msalConfig)
  await msalApp.handleRedirectPromise()
```

It makes sense for application code to handle error AADSTS50078.  But the situation is kinda tricky.  It looks like we have to call the `msalApp.logout()`first which is a very unfriendly flow(too many pages to jump between).  Can you suggest if any better workaround?

**Comment by pkanher617** [comment]
@pwang2 To be clear - is the error above happening when you call acquireTokenSilent? Or when you come back from the redirect?

> It makes sense for application code to handle error AADSTS50078. But the situation is kinda tricky. It looks like we have to call the msalApp.logout()first which is a very unfriendly flow(too many pages to jump between).

You shouldn't have to call `msalApp.logout()`, you can also resolve this by calling acquireTokenRedirect/acquireTokenPopup and present the MFA screen to the user again.

**Comment by pwang2** [comment]
Yes, that is during acquireTokensilent.   

I haven't tried to use redirect it pop-up.. I usually feel using popup or redirect not very favorable as we are fanning out a lot of xhr request in the page..  And we all know promise does not elegantly exit as we expected.   I have seen those popup blast for a few times.  In this case, the popup definitely need intervention.  Not sure if it will result to many forms to fill.. 

I would put some code to test and let you know. Thank you a lot for your
