### ISSUE TITLE
msal.js log in account that is not current user that launched the browser

### ISSUE THREAD

**Issue by kthimmai** [AzureAD/microsoft-authentication-library-for-js#2566]
Hi,

We are facing the similar issue as documented here https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1557

As per the above logged in issue it is mentioned that the issue will be fixed in MSA service. Could you please let us know if the issue has been in msal library and which version of this library has a fix.

## Library

azure/msal-angular@1.0.0
msal@1.3.0

## Framework
Angular 9
MSAL

## Description
Once the user is logged into the application with one Azure account and not able to login to different account with
in same browser session. (in out application we have Logout button which calls msalService.logout() to logout the current
user and then redirects to Microsoft azure login page. In login page, I select a different account to login but the app lands
with previous user logged in data and also acquireTokenSilent method getting old user access token only.

## Error Message
No errror

## Security
- [ No] Is this issue security related? 

## Regression
- [No ] Did this behavior work before? 
Version:

## MSAL Configuration
MsalModule.forRoot({
     auth: {
       clientId: environment.azClient,
       authority: environment.azAuthority,
       redirectUri: environment.clienturl
    },
    cache: {
      cacheLocation: 'localStorage',
      storeAuthStateInCookie: isIE, // set to true for IE 11
    },
  },
  {
    popUp: !isIE,
    consentScopes: [
      'user.read',
      'openid',
      'profile',
    ],
    unprotectedResources: [],
    protectedResourceMap: [
      [environment.azGraphEndpoint, ['user.read']]
    ],
    extraQueryParameters: {}
  })
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Expected behavior
Application should allow to login with different user account in same browser session.

## Browsers/Environment
- [Yes ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jasonnutter** [comment]
@kthimmai Can you please provide a Fiddler trace demonstrating the behavior you describe? My email is in my profile, thanks!

**Comment by kthimmai** [comment]
@jasonnutter I have shared to your email the Fiddler trace and below are the steps what I am doing in my app

1. Login to my angular webapp where it opens a page to login
2. Click on login button
3. It takes to Azure login page and I select one user to login
4. Azure authenticates and redirects back to my app home page
5. on my home page I see the user data logged in. I click on logout button
6. on click of logout button the app calls msalservice.logout() method and it redirects the page to azure logout page
7. In azure logout page I select the logged in User to logout and then it redirects me back to my app
8. In my app I click on Login button again which takes me to Azure login page
9. IN Azure login page I select a different user to login and it redirects me back to my application Home page
10. But in my App Home Page I still see the old user info instead of new user information. These user information in my app is read from access token retrieved from azure using acquireTokenSilent method call. also getAccount() of msal library or graph api call  returns the first logged in user details only instead of second select user details.

Thanks
Kamala

**Comment by kthimmai** [comment]
@jasonnutter - Hi Jason, did you get chance to check on this issue?
