### ISSUE TITLE
Detecting when the redirect auth flow is complete

### ISSUE THREAD

**Issue by MarkHerhold** [AzureAD/microsoft-authentication-library-for-js#257]
How do we know when the auth flow has been completed after a redirect? In my experience, initializing MSAL after the redirect back to my app doesn't always immediately make `msalApp.getUser()` available. Do we have to listen to the `authCallback`? If so, how do we uniquely identify a successful login?

**Comment by rohitnarula7176** [comment]
@MarkHerhold The best way is to listen to authCallback. The callback will be called after the redirect with token/error.

**Comment by MarkHerhold** [comment]
But are we guaranteed that this will be called either every time MSAL is instantiated or every time we call `acquireTokenSilent()`?

Also, how do we uniquely identify that the callback was called due to a successful login and not some other successful event?

**Comment by rohitnarula7176** [comment]
@MarkHerhold The call back will be called every time you receive an id_token/access_token in the url fragment and you can identify its type by using tokenType parameter in the authCallback.
