### ISSUE TITLE
AADB2C99059: The supplied request must present a code_challenge

### ISSUE THREAD

**Issue by sam-wheat** [AzureAD/microsoft-authentication-library-for-js#2571]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

My app is a SPA.  I use MSAL loginPopup() to show the login dialog.  When the user clicks "Forgot password" I handle the error and attempt to redirect.  When I do I get this error:

> AADB2C99059: The supplied request must present a code_challenge

[This issue](https://github.com/MicrosoftDocs/azure-docs/issues/64073) suggests:

>  In general, we recommend you use an auth library like MSAL to do the code generation/etc. for you. 

Sorry for being such a noob but even though I am using MSAL I don't understand how to get the code challenge.  Also, is there I a way I can handle this in the popup?  Handling an exception and redirecting the user just does not seem right. Am I doing this right?  I don't see any documentation that recommends anything different.

See also [this issue](https://github.com/AzureAD/microsoft-identity-web/issues/751)

And [this one ](https://github.com/AzureAD/microsoft-identity-web/issues/729) - With respect to this issue I did copy the the URL that was generated in the B2C portal as was suggested by jennyf19.

	async login(signInType: string): Promise<AuthenticationResult>  {
        var response: AuthenticationResult = new AuthenticationResultClass();

        if (signInType === "loginPopup") {
            try {
                response = await this.myMSALObj.loginPopup(this.loginRequest);
                this.account = response.account;
            }
            catch (ex) {

                if ((ex as Error).message.indexOf("AADB2C90118") > -1) {
                    this.resetPassword();
                }
                else
                    throw ex;
            }
        }
        return response;
    }
	
	
	
	resetPassword(): void {
        // still writing this
        const url = "https://client.b2clogin.com/client.onmicrosoft.com/oauth2/v2.0/authorize?p=B2C_1_password_reset&client_id=12345&nonce=defaultNonce&redirect_uri=https%3A%2F%2Flocalhost%3A5031&scope=openid&response_type=code&prompt=login";
        window.location.href = url;   // Dont want to do this.  Prefer to use dialog
    }

**Comment by tnorling** [comment]
@sam-wheat Instead of handling the redirect yourself you should call `loginPopup` again with the password reset policy. You can find an example [here](https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp/blob/master/JavaScriptSPA/authPopup.js)

**Comment by sam-wheat** [comment]
@tnorling  Thanks much!
