### ISSUE TITLE
Add ADFS tests in UT and E2E

### ISSUE THREAD

**Issue by sameerag** [AzureAD/microsoft-authentication-library-for-js#2574]
Please follow the issue template below. 

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Upcoming Library
- [x] `@azure/msal-node@1.x`

## Source
- [x] Internal (MSAL.js team)
- [ ] Customer request

## Description
Add ADFS tests with correct mocks for msal-common

## Priority
medium

## Acceptance Criteria
ADFS unit tests match all claims

**Comment by sameerag** [comment]
@samuelkubai @hectormmg Can you please confirm we are testing this in E2E and if not, can you guys please add these test cases?

**Comment by hectormmg** [comment]
@sameerag I've been adding ADFS test cases for silent flow in the end to end test suite in #2684. They're on par with the AAD cases, will be adding more as soon as we fix the puppeteer issues.

**Comment by sameerag** [comment]
Thanks @hectormmg. Closing this issue in that case.
