### ISSUE TITLE
[msal-node] Add docs for B2C

### ISSUE THREAD

**Issue by sameerag** [AzureAD/microsoft-authentication-library-for-js#2576]
## Library
- [x] `@azure/msal-node@1.x.x`

## Documentation location
- [x] docs.microsoft.com
- [x] MSAL.js Github Wiki
- [x] README file
- [ ] Other (please fill in)
- [ ] Documentation does not exist

## Description
Add docs for B2C (Samples included)

**Comment by sameerag** [comment]
@derisen Anything else pending for node? If not, can we please close this?

**Comment by derisen** [comment]
@sameerag we should be good to go after merging [this PR](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/2636).

**Comment by sameerag** [comment]
Thanks @derisen. Linked the PR, this should auto close with the merge now.
