### ISSUE TITLE
acquireTokenSilent not working as expected 

### ISSUE THREAD

**Issue by mitul11191** [AzureAD/microsoft-authentication-library-for-js#2579]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
Below version we are using in Angular\

MSAL : "0.2.4",
angular/cli : "~6.0.8",

from Azure side we have set token expiration 15 minutes

After login I have set some logic to call acquireTokenSilent Method  before 2 minute once it call open popup and getting error on session storage like : interaction_required

 **code:**

`
  setTimer() {
    this.interval = setInterval(() => {
      const token = sessionStorage.getItem("msal.idtoken");
      if (token) {
        const base64Url = token.split(".")[1];
        const base64 = base64Url.replace(/-/g, "+").replace(/_/g, "/");
        const jsonPayload = decodeURIComponent(
          atob(base64)
            .split("")
            .map(function (c) {
              return "%" + ("00" + c.charCodeAt(0).toString(16)).slice(-2);
            })
            .join("")
        );
        const sessionPayload = JSON.parse(jsonPayload);
        const date = new Date(0);
        const sessionTimeOut = date.setUTCSeconds(sessionPayload.exp - 14 * 60);
        const currentTime = new Date();
        if (currentTime.valueOf() > sessionTimeOut.valueOf()) {
          this.stopInterval();
          //this.getToken();
        }
      }
    }, 1000);
  }

  getAccessToken() {
    return this.app.acquireTokenSilent(https://abcd.onmicrosoft.com/xxxx-xxx-xxxx-xxx-xxxxxxx/user.read).then(accessToken => {
        this.saveAccessTokenToCache(accessToken);
        return accessToken;
    },
    error => {
        return this.app.acquireTokenRedirect(https://abcd.onmicrosoft.com/xxxx-xxx-xxxx-xxx-xxxxxxx/user.read).then(accessToken => {
            this.saveAccessTokenToCache(accessToken);
            return accessToken;
        },
            err => {
                console.error(error);
            });
    });
  }

  stopInterval() {
    clearInterval(this.interval);
  }

  saveAccessTokenToCache(accessToken: string): void {
    sessionStorage.setItem("msal.idtoken", accessToken);
    this.setTimer();
  }`


## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Expected behavior

once user login successful in application if user is actively working then need to refresh token silently

## Browsers/Environment
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by pkanher617** [comment]
@mitul11191 msal@v0.2.4 is a pre-release version, and may not have the full support you need for you scenario. Can you upgrade to the latest msal version and see if you are still having issues?

**Comment by mitul11191** [comment]
Hi @pkanher617,

I have installed the latest (v1.4.3) @azure/msal-angular and have angular 9.1.3

**Config:** Token life setup 15 minutes from Azure side and below is a configuration 

```
function MSALConfigFactory(): Configuration {
  return {
    auth: {
      clientId: 'xxxx-xxxx-xxxx-xxxx-xxxx',
      authority:
        'https://login.microsoftonline.com/tfp/abcd.onmicrosoft.com/xxxx_policy',
      validateAuthority: false,
      redirectUri: 'https://localhost:4200',
      postLogoutRedirectUri: 'https://localhost:4200/logout',
      navigateToLoginRequestUrl: true,
    },
    cache: {
      cacheLocation: 'sessionStorage',
      storeAuthStateInCookie: false,
    },
    system: {
      tokenRenewalOffsetSeconds: 300,
      logger: new Logger(loggerCallback, {
        correlationId: '1234',
        level: LogLevel.Verbose,
        piiLoggingEnabled: true,
      }),
    },
  };
}

function MSALAngularConfigFactory(): MsalAngularConfiguration {
  return {
    popUp: true,
    consentScopes: [
      'user.read',
      'openid',
      'profile',
      'https://xxxx.onmicrosoft.com/xxxx-xxxx-xxxx-xxxx-xxxx/user.read',
    ],
    unprotectedResources: ['https://www.microsoft.com/en-us/'],
    protectedResourceMap,
    extraQueryParameters: {},
  };
}

@NgModule({
  declarations: [ ],
  imports: [
    MsalModule,
  ],
  providers: [   
    {
      provide: HTTP_INTERCEPTORS,
      useClass: AuthenticationHttpInterceptor,
      multi: true,
    },
    {
      provide: MSAL_CONFIG,
      useFactory: MSALConfigFactory,
    },
    {
      provide: MSAL_CONFIG_ANGULAR,
      useFactory: MSALAngularConfigFactory,
    },
    MsalService,
  ],
  bootstrap: [AppComponent],
  exports: [RouterModule],
}) 
```

--------------------------------MSAL Service    ------------------------

calling below function every minute to renew the token.


```
getToken() {
    const requestObj = {
      scopes: [
        'https://xxxxxxxx.onmicrosoft.com/xxxxx-xxx-xxx-xxx-xxxxx/user.read',
      ],
    };
    this.authService
      .acquireTokenSilent(requestObj)
      .then((tokenResponse) => {
        this.saveAccessTokenToCache(tokenResponse.accessToken);
      })
      .catch((error) => {
          this.authService
            .acquireTokenPopup(requestObj)
            .then((tokenResponse) => {
              this.saveAccessTokenToCache(tokenResponse.accessToken);
            })
            .catch((error) => {
              // Acquire token interactive failure
              console.log(error);
            });
        console.log(error);
      });
  }
saveAccessTokenToCache(accessToken: string): void {
    sessionStorage.setItem('msal.idtoken', accessToken);
    this.setTimer();
  }
```

**Summary:** after login success gets token from session Storage of 'msal.idtoken' and passing this token to API header. 
after refresh method getting accessToken and set it in 'msal.idtoken'.

**Issue:** calling acquireTokenSilent method every minute to renew token for testing it is working for the first minute after that it is not renewing token and it's calling before 5 minute of expiration and getting exception like intraction_required and open popup.

**expectation:** default token lifetime is 1 hour if a user is working more than hours so need to renew token before expiration.

**Comment by tnorling** [comment]
@mitul11191 Silent token acquisition is not guaranteed to succeed and you should have fallback logic to call `acquireTokenPopup` when it fails with errors such as `interaction_required`. Additionally, we do not recommend calling `acquireTokenSilent` on an interval or caching the tokens yourself as it will automatically try to renew the token before expiration and cache it. If you are using the msal-angular interceptor, all of this should be done when calling an API and there should be no need for you to call `acquireTokenSilent` yourself.

Please take a look at our [Angular 9 sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-samples/angular9-sample-app) if you need an example of how this is done.

**Comment by mitul11191** [comment]
Hi @tnorling, I'm using a custom interceptor so in this case do I need to call any method to get Token for every API?

**Comment by tnorling** [comment]
@mitul11191 Yes, if you are using a custom interceptor you will need to call `acquireTokenSilent`, however, you do not need to do your own caching or expiration checks as that is built into `acquireTokenSilent`

**Comment by c-mpatel** [comment]
Hi @tnorling , @pkanher617 ,

MSAL Library Version:
 msal-angular : "1.1.2",
 msal : "^1.4.4",
 
 This version i'm using 
 i'm using acquireTokenSilent in interceptor 
 
 **Issue:** in chrome incognito mode if  'Block third-party cookies' are enabled then getting below issue.
 
 is there any way to solve this issue?
 
 InteractionRequiredAuthError: AADB2C90077: User does not have an existing session and request prompt parameter has a value of 'None'.

**Comment by tnorling** [comment]
@c-mpatel Please see this [wiki article](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Known-issue-on-Safari) regarding 3rd party cookies. Currently the best way to handle this is to upgrade to `msal-browser@2.8` and `msal-angular@2.0.0-alpha.1` which does not require 3rd party cookies in most scenarios. If you do not wish to upgrade the solutions are to either enable 3rd party cookies or call an interactive method (`acquireTokenRedirect` or `acquireTokenPopup`) instead of `acquireTokenSilent`

**Comment by c-mpatel** [comment]
Hi @tnorling ,

May I know when is the plan for release stable Msal-angular v2,
To check refresh token I'm using tokenRenewalOffsetSeconds and given 3540 which means every minute refresh token method will call from Msal angular.

in crome while 'Block third-party cookies' enable that time I'm getting the error on below method and calling acquireTokenRedirect but it not working

**issue:**  it's infinite redirection loop

**other scenario:**  if I'm using acquireTokenRedirect() instead of `this.authService.acquireTokenRedirect(requestObj)` in the below code then once login URL blinking and page reloading and it is redirecting to the home screen.

Please give me the perfect solution to handle acquireTokenFailure if the 'Block third-party cookies' is enabled in any browser.
 
const requestObj = {
      scopes: [`https://xxxxx.onmicrosoft.com/xxxx-xxxx-xxx-xxxxxx/user.read`],
    };
`this.broadcastService.subscribe('msal:acquireTokenFailure', (payload) => {
      if (payload.errorMessage.includes('AADB2C90077')) {
        this.authService.acquireTokenRedirect(requestObj);
      }
    });`

**Comment by tnorling** [comment]
@c-mpatel We expect `msal-angular v2` to go into public preview/beta sometime this month. We do not have a GA date we can share yet but it should not be too long after we go into beta. The solutions for this issue, as stated previously, are to upgrade to v2, enable 3rd party cookies, or call an interactive method instead of `acquireTokenSilent`. Looping can be caused by several different things and I would ask that you open a new issue with steps to reproduce so that we can keep the discussion here focused on the original issue. Thanks!

**Comment by c-mpatel** [comment]
Hi @tnorling I have opened a new issue please check this #2822
