### ISSUE TITLE
Create Guidance about the Access Token and the IFRAME

### ISSUE THREAD

**Issue by spottedmahn** [AzureAD/microsoft-authentication-library-for-js#258]
Following up on #209...

>Shouldn't there be some guidance/warning for this library that iframe's are used to obtain access tokens so be careful as your entire SPA app will load again (wasting a bunch of resources like RAM) so keep your startup code very light

**Comment by rohitnarula7176** [comment]
@spottedmahn Thank you for pointing out. We will add guidance around the usage of iframe in the next release.
