### ISSUE TITLE
Authority string is being incorrectly appended to

### ISSUE THREAD

**Issue by pconnell99** [AzureAD/microsoft-authentication-library-for-js#259]
When I am trying to set an authority string the call to the server is corrupted.

Example:-
```
this.applicationConfig = {
      clientID: '<clientid>',
      authority:'https://login.microsoftonline.com/<mytenant>.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1_GPlus',
      graphScopes: ['user.read']
    };
```
The authority is readable in a browser and returns a policy.  However, when I run the application so:-

```
this.app = new Msal.UserAgentApplication(
      this.applicationConfig.clientID,
      this.applicationConfig.authority,
      () => {
        // callback for login redirect
      },
      {
        redirectUri
      }
    );
```
The popup closes and the browser reports a 400 (Bad Request) for the URL `https://login.microsoftonline.com/<mytenant>.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=b2c_1_gplus/v2.0/.well-known/openid-configuration`

Am I setting the authority incorrectly or is the library appending the string?

**Comment by nehaagrawal** [comment]
I think your authority url is incorrect. It shouldn't have openid-configuration in the path.

**Comment by rohitnarula7176** [comment]
@pconnell99 Please refer to the samples in the repo on how to create the authority string. Closing this for now. Please reopen if you still face any issues.
