### ISSUE TITLE
How to use  the "MSAL Angular 2.X sample" with AD B2C?

### ISSUE THREAD

**Issue by hhubik** [AzureAD/microsoft-authentication-library-for-js#2597]
## Library
- [x] `@azure/msal-angular^2.0.0-alpha.0`
- [x] `@azure/msal-browser@2.7.0`

## Description
I just downloaded this [sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/angular-v2-minor-fixes/samples/msal-angular-v2-samples/angular10-sample-app).

It runs fine "as is".  However, I am having trouble getting the sample to work with my own AD B2C tenant.

The login/logout functionality works fine, but when I try to get to the `profile` page, I get the following error:
`ERROR ServerError: invalid_request: AADB2C90117: The scope 'user.read' provided in the request is not supported.`

I see the following in the console:
```
app.module.ts:39 MSAL logging:  [Fri, 13 Nov 2020 21:05:02 GMT] :  : 1.7.2 : Info - Emitting event: msal:acquireTokenFailure
app.module.ts:39 MSAL logging:  [Fri, 13 Nov 2020 21:05:02 GMT] :  : 1.7.2 : Info - Emitting event: msal:acquireTokenStart
app.module.ts:39 MSAL logging:  [Fri, 13 Nov 2020 21:05:03 GMT] :  : 1.7.2 : Info - Emitting event: msal:acquireTokenFailure
core.js:4197 ERROR ServerError: invalid_request: AADB2C90117: The scope 'user.read' provided in the request is not supported.
Correlation ID: 4c9aeeef-7fe5-4f5c-a12b-abf69b5bb2af
Timestamp: 2020-11-13 21:05:03Z

    at ServerError.AuthError [as constructor] (http://localhost:4200/vendor.js:92152:24)
    at new ServerError (http://localhost:4200/vendor.js:95255:28)
    at ResponseHandler.push.u8tD.ResponseHandler.validateServerAuthorizationCodeResponse (http://localhost:4200/vendor.js:96427:19)
    at AuthorizationCodeClient.push.u8tD.AuthorizationCodeClient.handleFragmentResponse (http://localhost:4200/vendor.js:96715:25)
    at PopupHandler.<anonymous> (http://localhost:4200/vendor.js:100448:52)
    at step (http://localhost:4200/vendor.js:92016:23)
    at Object.next (http://localhost:4200/vendor.js:91997:53)
    at http://localhost:4200/vendor.js:91990:71
    at new ZoneAwarePromise (http://localhost:4200/polyfills.js:10142:33)
    at __awaiter (http://localhost:4200/vendor.js:91986:12)
```
Any suggestions on how to fix this?

**Comment by jasonnutter** [comment]
@hhubik `user.read` is a MS Graph scope, and will not work with B2C. You will need to create a custom scope in your app registration, and then use it against your own API. You can see this done in our MSAL Angular v1 B2C sample: https://github.com/Azure-Samples/active-directory-b2c-javascript-angular-spa

We'll be sure to add an MSAL Angular v2 B2C sample. cc: @jo-arroyo @derisen

**Comment by hhubik** [comment]
@jasonnutter thanks for the suggestion.  If I use my own API, what is the best way to get the user's name (or display name)?  Do I need to call MS graph from my API?  I use Azure Functions for my APIs.  Does what you said above about the custom scope apply to Azure functions as well?

**Comment by hhubik** [comment]
Upon  a closer look, it looks like I can get the basic info (including the oid and the name) of the authenticated user from MSAL using the getAccounts() method.  I would still appreciate a sample that shows how to protect an API implemented as an Azure Function.
