### ISSUE TITLE
[@azure/msal-browser] Null accountInfo in acquireTokenSilent response

### ISSUE THREAD

**Issue by muying-cui** [AzureAD/microsoft-authentication-library-for-js#2598]
## Library
- [x] `@azure/msal-browser@2.7.0`

## Description
In the authResponse returned from acquireTokenSilent API, the accountInfo is null, however, the getAllAccounts() API returns expected account information.

## Expected behavior
accountInfo should have expected account information

## Browsers/Environment
- [x] Chrome

**Comment by sameerag** [comment]
@muying-cui Can you please share the logs, Configuration and the request details for your case?
