### ISSUE TITLE
MSAL B2C Session Expiration and Automatic Logout Problems

### ISSUE THREAD

**Issue by elizabethconnolly** [AzureAD/microsoft-authentication-library-for-js#2601]
We have recently upgraded our Azure SPA to use msal-browser 2.x  as part of migrating to use the new b2clogin endpoint specified in:

https://docs.microsoft.com/en-us/azure/active-directory-b2c/b2clogin

The MSAL version specified is:

    "@azure/msal-browser": "^2.3.0",

We are using built-in B2C user flows - no custom user flows. For testing, the B2C User flow (SignInOnly variant) specifies a Session behavior of 15 minutes and Absolute Timeout (see below). The token is set to a 30-minute timeout. However, the session does NOT appear to time out at 15 minutes. Requests for logged in users are still honored, and the user is not automatically logged out. Requests start to fail after the token expires (and the session still does not expire when this happens).

![SessionBehavior](https://user-images.githubusercontent.com/43051224/99258383-7a22e280-27e6-11eb-93e6-a175398a56b9.PNG).

Note that this "SignInOnly" user flow had to be updated to "recommended" type because our existing "standard" type did not honor the b2clogin-using endpoint that is now required (we determined this via a support ticket opened with Microsoft).

The login code is successfully creating an Msal PublicClientApplication using the correct clientId, authority, redirect URi, and postLogout Uri arguments. The cache type is localStorage. Login, logout, and all other authentication behave properly.

In our previous version (a several-year-old Msal version) the session would end when the SessionTimeout time was reached and the user would be automatically logged out (I assume through a combination of MSAL and B2C behaviors.) We didn't need any code in our SPA to do this logout.

Please tell me if there is some additional configuration required to enforce the Session Timeout, or if this appears to be a bug, when it will be addressed, as the deadline for this b2clogin endpoint requirement is fast approaching. Thanks.

**Comment by elizabethconnolly** [comment]
Other environment information: react, typesecript

**Comment by sameerag** [comment]
@elizabethconnolly This could be a B2C Service issue than MSAL. Can you please file a support ticket with the B2C team by following the instructions here: https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options

They can help you out further, they may ask for a public repro link or additional data. You can also link this Github issue in the support request.

**Comment by elizabethconnolly** [comment]
Thanks for the response. In fact, we already had a ticket open and they told us to file an issue here. Please advise.

**Comment by pkanher617** [comment]
@elizabethconnolly Could you please fill out the [bug template](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/new?assignees=&labels=bug&template=bug_report.md&title=) with the required information? You have provided most of the information we need, but the template will help us organize the information better.

As @sameerag said above, I believe this is something the B2C team should have been able to answer for you. Session lifetime =/= token lifetime here, so while your session may have been deactivated the token has not yet expired. You can set the token lifetime separately in your user flow (see [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/configure-tokens#configure-jwt-token-lifetime)).

If your session is still active even after the token has expired, that is an issue the service has to help you with - our library only queries the service to see if the session is active. You can try changing your SSO config for the user flow to Application level only as well, as it may be that there are other apps in the tenant that the user has signed into, keeping their session active.

**Comment by elizabethconnolly** [comment]
Thank you @pkanher617. I am filling out the bug template now. Are you saying that if we make token lifetime = session lifetime this should work? We had them set at different times for testing because our understanding was that the session would end at its own lifetime expiration, even if the token hasn't expired. If that's the case we will test it with equal times. Surprised the B2C team did not ask us to do that. Anyway, I'll fill out the template to make sure all the information is in the correct format. Thanks.

**Comment by HarmanDhunna** [comment]
Hi @elizabethconnolly, would you have the id of the bug you filled out? I would like to look at the details of this issue. 
If you have not already, could you share a network trace with us in the bug?

**Comment by elizabethconnolly** [comment]
ID is #2601. Couldn't find a place to put that in the template.

**Comment by elizabethconnolly** [comment]
Now I can't access the template - not sure it saved. Do you have access to it @HarmanDhunna ? Thanks

**Comment by HarmanDhunna** [comment]
2601 links me back to this issue. I was looking for the ID of the support ticket that you filled. I can ask my contact in the support team to look up the ticket for me, I don't have access to support tickets. 

Did you receive an email when you filled the report? You might be able to update the ticket from there.

**Comment by elizabethconnolly** [comment]
Ah, thanks.

This is the support ticket ID for the B2C issue we opened. I will add this to the 2601 issue too.

2011050040006485


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by tnorling** [comment]
Determined in offline discussions that the refresh token (24hr lifetime) is renewing the session when calling acquireTokenSilent. Options are:
1. Use a custom policy to set refresh token lifetime to at or below session lifetime
2. Track user activity app side and call `logout()` after the desired amount of inactivity

Closing as the question has been answered. Discussion over implementation is ongoing offline.
