### ISSUE TITLE
Wrong type for getAllAccounts, should be nullable

### ISSUE THREAD

**Issue by Calamari** [AzureAD/microsoft-authentication-library-for-js#2604]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.7.0`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

In all examples calling `getAllAccounts()` there is a check for null done, see [here](https://github.com/Azure-Samples/ms-identity-javascript-v2/blob/master/app/authPopup.js#L14). But the type defined is not defined as nullable (as can be seen in `IPublicClientApplication` interface).

## Expected behavior

It would be helpful to know, through typing as well, that the result can be null, or if that is not the case, to adapt the examples to match the current behaviour.

**Comment by tnorling** [comment]
@Calamari Thanks for pointing this out, looks like the sample needs to be updated. `getAllAccounts` will return an empty array if no accounts are found.

@derisen Could you please update the samples to check for `currentAccounts.length === 0` instead of `null`?

**Comment by tnorling** [comment]
Closing as the samples have been updated
