### ISSUE TITLE
RENEW_TOKEN called on every MSAL Interceptor call

### ISSUE THREAD

**Issue by ThomasPe** [AzureAD/microsoft-authentication-library-for-js#2605]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.4.4` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.1.2`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework
Angular 10

## Description
I've set up MSAL with the provided Interceptor to talk to my backend. This works fine for a while, but after sending a lot of requests I start getting errors from MSAL and the calls don't reach the backend anymore.

After enableing logging I noticed, that on every API call there's a RENEW_TOKEN log which leads me to believe that I might simply hit an AD quota due to the Token being refreshed on every API call.

## Error Message

![image](https://user-images.githubusercontent.com/4225039/99389926-1678e200-28d8-11eb-9754-d3a6d3730ea8.png)

```
Unsafe JavaScript attempt to initiate navigation for frame with origin 'http://localhost:4200' from frame with URL 'https://login.microsoftonline.com/.../oauth2/v2.0/authorize?response_type=token&scope=...+user.read+openid+profile&client_id=...,,
The frame attempting navigation of the top-level window is sandboxed, but the flag of 'allow-top-navigation' or 'allow-top-navigation-by-user-activation' is not set.
```

```
authorize:84 Uncaught DOMException: Failed to set the 'href' property on 'Location': The current window does not have permission to navigate the target frame to 'https://login.microsoftonline.com/6b7ca376-8cb7-4198-bbce-ec381c51fabf/oauth2/v2.0/authorize?...
```

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

### app.module.ts
```js
  providers: [
    {
      provide: MSAL_CONFIG,
      useFactory: MSALConfigFactory
    },
    {
      provide: MSAL_CONFIG_ANGULAR,
      useFactory: MSALAngularConfigFactory
    },
    MsalService,
    {
      provide: HTTP_INTERCEPTORS,
      useClass: MsalInterceptor,
      multi: true
    }
```

### msal.factory.ts
```js
import { MsalAngularConfiguration } from '@azure/msal-angular';
import { Configuration } from 'msal';
import { environment } from 'src/environments/environment';

export const protectedResourceMap: [string, string[]][] = [
  [environment.api.baseUrl, environment.api.scopes],
  ['https://graph.microsoft.com/v1.0/me', ['user.read']]
];

export function MSALConfigFactory(): Configuration {
  return {
    auth: {
      clientId: {clientID},
      authority: 'https://login.microsoftonline.com/{tenantid}',
      redirectUri: window.origin,
      postLogoutRedirectUri: window.origin,
      navigateToLoginRequestUrl: true,
    },
    cache: {
      cacheLocation: 'localStorage'
    }
  };
}

export function MSALAngularConfigFactory(): MsalAngularConfiguration {
  return {
    popUp: false,
    protectedResourceMap,
    consentScopes: environment.api.scopes
  };
}
```

### app.component.ts
```js
  isIframe = false;
  loggedIn: boolean;
  private subscription: Subscription;

  constructor(private authService: MsalService,
              private broadcastService: BroadcastService) {
    //  This is to avoid reload during acquireTokenSilent() because of hidden iframe
    this.isIframe = window !== window.parent && !window.opener;
    if (this.authService.getAccount()) {
      this.loggedIn = true;
    }
    else {
      this.loggedIn = false;
    }

    this.authService.handleRedirectCallback((authError, response) => {
      if (authError) {
        console.error('Redirect Error: ', authError.errorMessage);
        return;
      }
      console.log('Redirect Success: ', response);
    });
  }
  ngOnInit(): void {

    this.broadcastService.subscribe('msal:loginFailure', (payload) => {
      console.log('login failure ' + JSON.stringify(payload));
      this.loggedIn = false;

    });

    this.broadcastService.subscribe('msal:loginSuccess', (payload) => {
      console.log('login success ' + JSON.stringify(payload));
      this.loggedIn = true;
    });

    this.broadcastService.subscribe('msal:interactionRequiredAuthError', (payload) => {
      console.log('interactionRequiredAuthError', JSON.stringify(payload));
    });

    this.authService.setLogger(new Logger((logLevel, message, piiEnabled) => {
      console.log('MSAL Logging: ', message);
    }, {
      correlationId: CryptoUtils.createNewGuid(),
      piiLoggingEnabled: false
    }));
  }

  ngOnDestroy(): void {
    this.broadcastService.getMSALSubject().next(1);
    if (this.subscription) {
      this.subscription.unsubscribe();
    }
  }

}
```

## Expected behavior
I guess the RENEW_TOKEN should only be called whenever the token is close to expiring or already expired. The new token i receive seem to be valid for one hour.

## Browsers/Environment
- [x] Chrome
- [ ] Firefox
- [x] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by tnorling** [comment]
@ThomasPe Could you try opening the `login.microsoftonline.com` url in the error message in a new tab? This error is usually thrown when the Authority is trying to display an error in the top frame from the hidden iframe used by `acquireTokenSilent`. It's quite likely based on your description that you are being throttled but it would be good to confirm.

Can you also take a look at localstorage and confirm that there is an access token cached with all the scopes you are requesting? We should understand why a cache miss is happening as that is unexpected.

**Comment by ThomasPe** [comment]
Turns out the issue was that I included the 'user.read' scope that was meant for the Graph API in the Protected Resources Map for the API which it doesn't know about. Any chance that these kind of issues could result in more meaningful error messages or is this something that you don't get back from Azure AD yourself?

**Comment by tnorling** [comment]
@ThomasPe Unfortunately we have no way of getting the errors AAD displays on the sign-in page, msal can only bubble up the errors that are returned in the url hash when AAD redirects back to the app. 

Did making this change resolve the cache miss?

**Comment by ThomasPe** [comment]
Yes, I'm not seeing token refreshes in every call anymore.
