### ISSUE TITLE
acquireTokenSilent does not return the token field

### ISSUE THREAD

**Issue by jakubgrzywaczewski** [AzureAD/microsoft-authentication-library-for-js#2606]
## Library
- [x] `msal@1.4.4`

## Framework
React 16.11.3 

## Description

So far I have used msal.js version 1.3.2 for authorization via b2c. After upgrading to version 1.4.4, I noticed a problem with the response returned by the **acquireTokenSilent** method - the **accessToken** field is missing. The token itself appears in the **idToken**.**rawIdToken** field.

## Regression
- [x] Did this behavior work before? 
Version: 1.3.2

## MSAL Configuration

```js
const msalConfig = {
  auth: {
    clientId: Settings.default.msalClientId,
    authority: Settings.default.msalAuthority,
    redirectUri: `${document.location.origin}/signin/b2c`,
    validateAuthority: false,
  },
  cache: {
    cacheLocation,
    storeAuthStateInCookie: false,
  },
};

const msalAuthenticationParameters = {
  scopes: [Settings.default.msalClientId],
};

const msalInstance= new UserAgentApplication(msalConfig);

const msalAuthenticationParameters = {
  scopes: [Settings.default.msalClientId],
};

```

## Reproduction steps
```js
export function fetchWithMsal(
  url: string,
  request: RequestInit,
): Promise<Response> {
  let resultRequest = request;

  const result = msalInstance
    .acquireTokenSilent(msalAuthenticationParameters)
    .then((response) => {
      if (!response.accessToken) {
        return undefined;
      }
      resultRequest = generateRequestProperties({
        accessToken: response.idToken.rawIdToken,
        request,
      });

      return fetch(url, resultRequest);
    })
    .catch((e) => {
      msalInstance.acquireTokenRedirect(msalAuthenticationParameters);
    });

  return result as Promise<Response>;
}
```

## Expected behavior
Return accessToken field with token.

**Comment by pkanher617** [comment]
@jakubgrzywaczewski If you are sending `msalClientId` as the scope, you are requesting the scopes for openid and profile, which are idToken scopes. Please check the network trace to make sure, but this should only give you an id_token from the STS. 

Previously, the library returned this token as an access token as well. We have since changed that behavior to be in-line with what the server is sending back.

If you are seeing an access token in the network trace and it is not being returned, we can investigate this further.

**Comment by jakubgrzywaczewski** [comment]
@pkanher617 Got it, thank you for your explanation. I recieve `idToken`. If I understand correctly, it is impossible to restore `access_token` field in response, and the only field with token is `idToken` (for `openid` and `profile` scope), right? 

I am trying to understand how to restore the accessToken field in response by modifying the scope, but I cannot tell. I looked at the documentation https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/docs/scopes.md and https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/docs/response-types.md and it's still unclear for me.

**Comment by hectormmg** [comment]
Hi @jakubgrzywaczewski , 

> I wonder if it's possible to restore the accessToken field in response by modifying the scope, but I cannot tell. I looked at the documentation https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/docs/scopes.md and https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/docs/response-types.md and it's still unclear for me.

Yes, you can turn your request into an access token request by manually adding "openid" and or "profile" to your scopes. This would be the very last example case in the scopes doc you refer to. When Client ID is the only scope, MSAL replaces it with openid and profile and turns it into an ID Token request. However, if you add any other scopes (including openid or profile), the Client ID will be treated as an access token scope (which I believe is what you want) and be sent to the server. In the B2C case, you should get an access token back, along with an ID token.

**Comment by jakubgrzywaczewski** [comment]
Hi, @hectormmg 

Thank you for your response. Unfortunately, after adding a new parameter to this configuration as you proposed, I catch an error:

```
InteractionRequiredAuthError: AADB2C90077: User does not have an existing session and request prompt parameter has a value of 'None'.
Correlation ID: 695efe57-5850-4523-87e6-6871b77cfb28
Timestamp: 2020-11-19 13:51:03Z

    at InteractionRequiredAuthError.AuthError [as constructor] (https://localhost:8080/static/js/6.chunk.js:69732:24)
    at InteractionRequiredAuthError.ServerError [as constructor] (https://localhost:8080/static/js/6.chunk.js:70306:24)
    at new InteractionRequiredAuthError (https://localhost:8080/static/js/6.chunk.js:70237:24)
    at UserAgentApplication.saveTokenFromHash (https://localhost:8080/static/js/6.chunk.js:67776:17)
    at UserAgentApplication.processCallBack (https://localhost:8080/static/js/6.chunk.js:67148:23)
    at UserAgentApplication.handleAuthenticationResponse (https://localhost:8080/static/js/6.chunk.js:67209:10)
    at UserAgentApplication.<anonymous> (https://localhost:8080/static/js/6.chunk.js:66867:20)
    at step (https://localhost:8080/static/js/6.chunk.js:113544:17)
    at Object.next (https://localhost:8080/static/js/6.chunk.js:113475:14)
    at fulfilled (https://localhost:8080/static/js/6.chunk.js:113428:24)
```

I'm a little bit confused. Without additional parameter I'm able to recive response (without access token field) and with `openid` parameter I get an error.

**Comment by hectormmg** [comment]
@jakubgrzywaczewski  thanks, I'll look into it!

**Comment by hectormmg** [comment]
@jakubgrzywaczewski 

> I wonder if it's possible to restore the accessToken field in response by modifying the scope, but I cannot tell. I looked at the documentation https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/docs/scopes.md and https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/docs/response-types.md and it's still unclear for me.

Do you mean you want the value that is currently in idToken to also be in accessToken? Or are you trying to acquire an access token as well?

In the past, for client Id as the only scope, MSAL would get an ID token and put it into the "accessToken" and "idToken" fields (both with the same value). Now MSAL gets the same ID Token but puts it under idToken and leaves "accessToken" empty.

**Comment by jakubgrzywaczewski** [comment]
@hectormmg 

> Do you mean you want the value that is currently in idToken to also be in accessToken? Or are you trying to acquire an access token as well?

Well, yes, but I don't know if this approach is correct.
 
> In the past, for client Id as the only scope, MSAL would get an ID token and put it into the "accessToken" and "idToken" fields (both with the same value). Now MSAL gets the same ID Token but puts it under idToken and leaves "accessToken" empty.

So if I understand it correctly this change is permanent and I should switch to idToken. If so, we can close this issue.
