### ISSUE TITLE
Typescript Compilation Error 

### ISSUE THREAD

**Issue by PKCheap** [AzureAD/microsoft-authentication-library-for-js#2607]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `@azure/msal-browser@2.7.0`
- [x] `@azure/msal-react@1.0.0`

## Framework
React

## Description
Importing anything from @azure/msal-react into a tsx file triggers a compilation error.

## Error Message
TypeScript error in .../node_modules/@azure/msal-react/dist/index.d.ts(1,1):
Declaration or statement expected.  TS1128

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration
not applicable.

## Reproduction steps
Any .TSX file:
import * as msalReact from "@azure/msal-react";

## Expected behavior
The application should compile without error.

## Browsers/Environment
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by tnorling** [comment]
@PKCheap I was not able to reproduce this, can you do some debugging to determine if this is a problem with the package or with your development environment? We will have a typescript sample up soon.

**Comment by PKCheap** [comment]
Hi @tnorling,
I ended up switching back to react-aad-msal for my project - waiting with anticipation to see how msal-react turns out! Since this issue seemingling was only affecting me, I'll close the issue.
