### ISSUE TITLE
the code does not work in IE 11

### ISSUE THREAD

**Issue by binhnguyen1984** [AzureAD/microsoft-authentication-library-for-js#2609]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `@azure/msal-browser@2.7.0`
## Description
Nothing happens when choosing either pop-up or redirect sign in.
## Error Message
No error message

## Expected behavior
A window should pop up and ask for the user's credentials
## Browsers/Environment
- [ ] IE

**Comment by tnorling** [comment]
@binhnguyen1984 Using our library with IE11 has some additional considerations, such as providing a promise polyfill. Have you tried our [IE11 sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-browser-samples/VanillaJSTestApp2.0/app/ie11-sample)?

**Comment by binhnguyen1984** [comment]
The sample for IE 11 is not available. There is a link but it leads to nowhere.

**Comment by sameerag** [comment]
@binhnguyen1984 The link provided by @tnorling above is the IE11 sample. Can you check that?

**Comment by binhnguyen1984** [comment]
@sameerag @tnorling My mistake. I tried a different link (https://www.npmjs.com/package/@azure/msal-browser#samples). I will try the one you mention and let you know the result. Thanks.

**Comment by binhnguyen1984** [comment]
@tnorling I got an error "no such file or directory, stat 'C:\microsoft-authentication-library-for-js-dev\samples\msal-browser-samples\VanillaJSTestApp2.0\index.html'".
I run the command:  npm start -- -s ie11-sample
from the VanillaJSTestApp2.0 folder as instructed.

**Comment by tnorling** [comment]
@binhnguyen1984 hmmm interesting, I just tried it myself and did not get that error. Are you getting this error when trying to serve the sample or when you navigate your browser to `localhost:30662`? Are there any other messages in the console?

**Comment by binhnguyen1984** [comment]
@tnorling I got this error when clicking on the Sign In button. There is no other error. Below is the messages in the Console.
Listening on port 30662...
GET / 304 5.269 ms - -
GET /lib/msal-browser.js 404 5.818 ms - 318
Error: ENOENT: no such file or directory, stat 'C:\microsoft-authentication-library-for-js-dev\samples\msal-browser-samples\VanillaJSTestApp2.0\index.html'
GET /authConfig.js 200 7.343 ms - 1167
GET /ui.js 304 5.472 ms - -
GET /auth.js 304 2.084 ms - -
GET /graph.js 304 1.698 ms - -

**Comment by tnorling** [comment]
@binhnguyen1984 Did you build the `msal-browser` package? You can run `npm run build:package` in the `VanillaJSTestApp2.0` folder then try starting the server again.

Alternatively you can open up `VanillaJSTestApp2.0/app/ie11-sample/index.html` and replace the local msal-browser import on line 10 with the cdn import 

`<script type="text/javascript" src="https://alcdn.msauth.net/browser/2.7.0/js/msal-browser.min.js"></script>`

**Comment by binhnguyen1984** [comment]
@tnorling I replace the script link and the error disappears. But nothing happens when clicking on Sign in. 
Listening on port 30662...
GET / 200 9.015 ms - 3117
GET /authConfig.js 304 2.205 ms - -
GET /ui.js 304 1.439 ms - -
GET /auth.js 304 1.213 ms - -
GET /graph.js 304 1.664 ms - -
GET / 200 4.815 ms - 3117
GET /ui.js 304 2.367 ms - -
GET /auth.js 304 2.688 ms - -
GET /graph.js 304 2.910 ms - -
GET /authConfig.js 200 6.319 ms - 1167

**Comment by tnorling** [comment]
@binhnguyen1984 Sorry about that, looks like 2.7.0 is not on CDN yet try:

**Comment by binhnguyen1984** [comment]
@tnorling It is working this time. Thank you very much. I will see if I can make it work for my project.

**Comment by binhnguyen1984** [comment]
@tnorling I could not call my API as
