### ISSUE TITLE
Subsequent calls to acquireTokenPopup break the first invocation and prevent authentication

### ISSUE THREAD

**Issue by jviney** [AzureAD/microsoft-authentication-library-for-js#2614]
## Library
- [x] `@azure/msal-common@1.7.2`
- [x] `@azure/msal-browser@2.7.0`

## Framework

AngularJS.

## Description

The first call to `acquireTokenPopup` works correctly. If there is a subsequent call to `acquireTokenPopup` before the first one has completed, it causes the first popup to go blank, and raises a `BrowserAuthError.interaction_in_progress` error.

## MSAL Configuration

```js
new PublicClientApplication({
  auth: {
      clientId: "client-id",
    },
    cache: {
      cacheLocation: "localStorage",
      storeAuthStateInCookie: false,
    }
})
```

## Reproduction steps
```js
application.acquireTokenPopup()

setTimeout(() => {
  application.acquireTokenPopup()
}, 500)
```

## Expected behavior

Subsequent calls to `acquireTokenPopup` should raise the `BrowserAuthError.interaction_in_progress` without interrupting the first auth flow.

## Browsers/Environment
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jdolearydl** [comment]
I observed the similar behavior; however, for me it was the second, most recent popup that goes blank.

**Comment by jasonnutter** [comment]
PR to fix issues related to blank popup windows is linked above. This will allow separate tabs to open their own popups, and prevent the first popup from breaking when a second one is opened.
