### ISSUE TITLE
Guidance for persisting JWT?

### ISSUE THREAD

**Issue by sam-wheat** [AzureAD/microsoft-authentication-library-for-js#2616]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

What is the the Microsoft guidance and tooling for (not?) persisting the JWT on the client?

My app is React, using MSAL 2, Auth provided by Auzure AD B2C.

Thank you.

**Comment by jasonnutter** [comment]
@sam-wheat MSAL.js will handle caching of JWTs in the browser, either in local storage, session storage, or in memory. Your application should not need to implement any token caching logic of its own, and can instead rely on MSAL to handle it. 

Do you have specific concerns or considerations?

**Comment by sam-wheat** [comment]
> Do you have specific concerns or considerations?
No I was reading scary articles that warned of security risks.  But that is a long story.
I think MSAL will handle it just fine.

Thank you.
