### ISSUE TITLE
msal-angular unable to find cached access token

### ISSUE THREAD

**Issue by JeffFisher-sitekit** [AzureAD/microsoft-authentication-library-for-js#2618]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.4.4`
- [ ] `@azure/msal-angular@1.1.2`

## Framework
Angular 8

## Description
MSAL does not locate a valid access token in the cache, causing it to try, and fail, to invoke a silent refresh.

I have debugged this issue and found why this is happening:

To get a hit on the token cache, the account needs a matching homeAccountIdentifier. In my case, the homeAccountIdentifier is not being set.

In the code below, from ClientInfo.js, msal attempts to obtain a uid and utid from the clientInfo. My observation is that it fails to obtain the uid. This subsequently causes homeAccountIdentifier to be undefined, hence the cache miss.

When attempting to get the uid, ClientInfo.stripPolicyFromUid is called, to remove the B2C policy. I guess the idea is that this would leave the user id. However, the clientInfo looks like this:

`{uid: "-b2c_1a_hpsignin{VALID-CUSTOM-POLICY-NAME-HERE}", utid: "valid-guid-here"}`

After stripping the policy name a blank uid remains. This results in account.homeAccountIdentitifer to be undefined, resulting in the cache miss.

In debug, I can set accounbt.homeAccountIdentifier to the expected value (taken from local storage), and the access token is retrieved from cache as expected.

It is unclear to me whether this is a bug in msal, or whether there is something in our B2C configuration that results in the omission of the user id from the Client Info hashed fragment. Whatever, the outcome is that msal is not working as expected.

`    function ClientInfo(rawClientInfo, authority) {
        if (!rawClientInfo || StringUtils.isEmpty(rawClientInfo)) {
            this.uid = "";
            this.utid = "";
            return;
        }
        try {
            var decodedClientInfo = CryptoUtils.base64Decode(rawClientInfo);
            var clientInfo = JSON.parse(decodedClientInfo);
            if (clientInfo) {
                if (clientInfo.hasOwnProperty("uid")) {
                    this.uid = authority ? ClientInfo.stripPolicyFromUid(clientInfo.uid, authority) : clientInfo.uid;
                }
                if (clientInfo.hasOwnProperty("utid")) {
                    this.utid = clientInfo.utid;
                }
            }
        }
        catch (e) {
            throw ClientAuthError.createClientInfoDecodingError(e);
        }`
## Error Message
Refused to display 'https://login.microsoftonline.com/[guid]/oauth2/authorize?client_id=[remainder omitted]' in a frame because it set 'X-Frame-Options' to 'deny'.
app.component.ts:56 MSAL Logging:  Wed, 18 Nov 2020 17:47:14 GMT:1b584bd7-829c-44e3-b23e-655948817e4d-1.4.4-Error monitorIframeForHash unable to find hash in url, timing out
main.ts:51 Wed, 18 Nov 2020 17:47:14 GMT:1234-1.4.4-Verbose Telemetry Event stopped: 8bbd560b-4597-422c-a7b6-b202310f8d93_53999ab9-1f4f-4cc0-aef5-766d6eaa502e-msal.api_event
main.ts:51 Wed, 18 Nov 2020 17:47:14 GMT:1234-1.4.4-Verbose Flushing telemetry events: 8bbd560b-4597-422c-a7b6-b202310f8d93
app.component.ts:56 MSAL Logging:  Wed, 18 Nov 2020 17:47:14 GMT:1b584bd7-829c-44e3-b23e-655948817e4d-1.4.4-Error Error when acquiring token for scopes: [valid scope] ClientAuthError: Token renewal operation failed due to timeout.
## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before?  Unknown
Version:

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
msal-angular b2c login with custom signin policy.
```

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
code is simple and standard, calling msal-angular login and using the msal interceptor to apply access-token to api calls.

`    const isIE = window.navigator.userAgent.indexOf('MSIE ') > -1 || window.navigator.userAgent.indexOf('Trident/') > -1;

    if (isIE) {
      this.authService.loginRedirect();
    } else {
      this.authService.loginPopup();
    }`

```

## Expected behavior
interceptor applies access token to api calls.

## Browsers/Environment
- [X] Chrome
- [X] Firefox
- [X] Edge
- [X] Safari
- [X] IE
- [X] Other (Please add browser name here)

**Comment by tnorling** [comment]
@JeffFisher-sitekit This looks like a problem with the custom policy configuration. We're still waiting to hear back from the B2C service team to find out what you need to change to get the correct `uid` but in the meantime you can also open a [B2C Support Ticket](https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options), they may be able to answer you quicker through that channel.

**Comment by ulken** [comment]
Not using Angular, but potentially suffering from the same issue. 

We're currently using a legacy user flow/policy for sign in. For debugging purposes (with access tokens failing to refresh), we created a new user flow for sign in/sign up (_not_ legacy) with token lifetime set to minimum. However, when we switch to use the new policy, we experience a cache miss every time the access token is acquired silently. It results in a huge performance hit.

Not sure if we have configured something wrong (tried to mimic the old user flow as much as possible) or if this is a bug in MSAL/B2C? Any pointers how we would go about debugging this further? Kind of stuck right now. Thanks 🙏.

**Comment by JeffFisher-sitekit** [comment]
I spent some time debugging this in Angular. My conclusion is that it's not a bug in MSAL. However, the MSAL implementation depends on 3 things coming back from B2C:

1. the 'uid' claim, as a unique identifier for the user in this context,
2. the 'tid' claim - the tenant id,
3. the scope.  I think this normally comes back in the json response that contains the access token.

MSAL caches the token using both a 'homeAccountIdentifier' and the scope to identify the correct access token for the given user in the context of the given scope. The 'homeAccountIdentifier' appears to be set to a string value ${uid.tid}.

We use custom policies in B2C. It seems that our policies are not returning a uid claim, and do not include the scope in the access token response. This prevented MSAL from finding the token, causing issues.

Because we only use one custom SCOPE, the code below can be used as a workaround. it rewrites the cached value, using a key that includes our SCOPE, and sets the account.homeAccountIdentifier to the incomplete value that MSAL used. This code is in our user service, and gets fired when MSAL broadcasts 'msal:loginSuccess'. I hope it helps.

Jeff.

`    this.account = this.authService.getAccount();

    if (this.account && !this.account.homeAccountIdentifier) {
      let keys = new Array<string>();

      let storage: Storage = window[this.authService.getCurrentConfiguration().cache.cacheLocation];
      let oldStorageKey = '';
      let newStorageKey = '';
      let keyFound = false;

      let k = Object.keys(window[this.authService.getCurrentConfiguration().cache.cacheLocation]).reduce((tokens, key) => {
        if (key.startsWith('{')) {
          let o = JSON.parse(key);
          tokens = {
            authority: o.authority as string,
            clientId: o.clientId as string,
            homeAccountIdentifier: o.homeAccountIdentifier as string,
            scopes: [CONFIGURED SCOPES VALUE HERE]
          };

          oldStorageKey = key;
          keyFound = true;
        }
        return tokens;
      }, { authority: '', clientId: '', homeAccountIdentifier: '', scopes: '' });

      if (keyFound) {
        // our B2C Policies don't return the scope.
        // MSAL checks a) that the cache key contains a 'scope' property, and b) that the scope matches the requested scope.
        if (!oldStorageKey.match('scopes')) {
          newStorageKey = JSON.stringify(k);
          storage.setItem(newStorageKey, storage.getItem(oldStorageKey));
          storage.removeItem(oldStorageKey);
          console.log("Authorised User Service set scopes to ", k.scopes);
        }

        // our B2C policies are missing something that allows the homeAccountIdentifier to be properly determined
        // this is *possibly* a 'uid' claim that would come from the federated directory. 
        // homeAccountIdentifier  still has a value in the cache, and look like this: 'uid.tid',
        // where uid is the (missing) user id, and tid is the value of the tid claim.
        // We are missing uid, so the stored value looks like '.tid', where tid is the tenantId.
        // we can set the value of account.homeAccountIdentifier to the value that has been used for the cache.
        this.account.homeAccountIdentifier = k.homeAccountIdentifier;
        console.log("Authorised User Service set homeAccountIdentifier to ", this.account.homeAccountIdentifier);
      }
    }
`

**Comment by tnorling** [comment]
@ulken Your issue may or may not be the same as what's being discussed in this thread, its hard to say without more info. Can you please open a new issue and share the version of msal you're using, a reproduction and any other pertinent information? Thanks

@JeffFisher-sitekit Thanks for following up, we're still waiting to hear back from the service about any guidance they may have in this case, you can also open a ticket with the service directly. If there's something you think the library could do to better handle this scenario feel free to open a PR and we'd be happy to take a look!

**Comment by ulken** [comment]
@tnorling Sure thing. I'll do some digging around what @JeffFisher-sitekit mentions and open a separate ticket.

**Comment by JeffFisher-sitekit** [comment]
Update - we see this issue with msal 1.4.4, and there is no issue when using msal 1.3.1. In both cases running angular-msal 1.1.2.

It's possibly a bug with msal 1.4.4.
