### ISSUE TITLE
KMSI on ADFS with @azure/msal-browser@2.x.x

### ISSUE THREAD

**Issue by MariMax** [AzureAD/microsoft-authentication-library-for-js#2622]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `@azure/msal-browser@2.x.x`

## Description
our case:
after the first successful login using @azure/msal-browser@2.x.x user has one hour to use accessToken, then user has to renew it with refresh token which is good for 8 hours, I guess ADFS setting responsible for that SsoLifetime.

The question is, is there a way to use KMSI with ADFS and @azure/msal-browser@2.x.x to make refreshToken live longer?
or what's is the best way to make it live up to PersistentSsoLifetimeMins ADFS setting?

Thank you!

**Comment by tnorling** [comment]
@MariMax Msal does not control token lifetimes, it only requests a token from the server and caches whatever the server returns. Setting the refresh token lifetime would need to be done on your ADFS server and those types of questions are, regrettably, out of scope for this team. You may get a better answer going through whomever administers your ADFS server or through your support channels.

As a side note, if you do figure out how to configure it, we don't recommend setting your refresh token lifetime to larger than 24 hours.

**Comment by MariMax** [comment]
Thank you!
