### ISSUE TITLE
How to get custom attributes from claims?

### ISSUE THREAD

**Issue by sam-wheat** [AzureAD/microsoft-authentication-library-for-js#2627]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x ] `@azure/msal-browser@2.6.0`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
[This document](https://docs.microsoft.com/en-us/azure/active-directory-b2c/user-flow-custom-attributes) describes steps to select user attributes to appear in claims token:

> You should now see ShoeSize in the list of attributes collected during the sign-up journey, and see it in the token sent back to your application.

After following above steps custom attributes do not appear in the token sent back to my application.  What am I doing wrong?

[See also this stackoverflow ticket](https://stackoverflow.com/questions/45982423/add-claims-into-token-azure-b2c) 

![Capture](https://user-images.githubusercontent.com/16885210/99835290-42cf7100-2b19-11eb-8781-6f0364daed7e.PNG)
![Capture1](https://user-images.githubusercontent.com/16885210/99835592-ad80ac80-2b19-11eb-8676-288212f0e0aa.PNG)

**Comment by tnorling** [comment]
@sam-wheat This looks like a question for the B2C service, can you open a [support ticket](https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options) with them?
