### ISSUE TITLE
Modified copy of msal-angular code inside samples/msal-angular-v2-samples/angular10-browser-sample?

### ISSUE THREAD

**Issue by restfulhead** [AzureAD/microsoft-authentication-library-for-js#2630]
## Library
- [x] `@azure/msal-browser@2.x.x`
- [x] `@azure/msal-angular@2.x.x`

## Documentation location
- [x] Documentation does not exist

## Description
The Angular 10 example does not use the code from `@azure/msal-angular@2.x.x`. Instead it has copied and modified the code, see https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular10-browser-sample/src/app/msal.

Why is that? Does it mean we can't use the official `@azure/msal-angular@2.x.x` library, but instead have to copy the code from the example? What happens with bug fixes? Will they be committed to both, @azure/msal-angular@2.x.x` and the example project?

**Comment by jasonnutter** [comment]
@restfulhead The `angular10-browser-sample` was created before `@azure/msal-angular@2` was available to demonstrate how an app could use MSAL Browser directly. Going forward, applications should use `@azure/msal-angular@2` and the new samples. We'll make sure to update the `angular10-browser-sample` to make it clear to look at the other samples, apologies for the confusion. cc: @jo-arroyo

**Comment by restfulhead** [comment]
Great, thank you for the clarification. That makes sense. I must have overlooked the sample in `@azure/msal-angular@2`.
