### ISSUE TITLE
Vanilla JS Browser project doesn't install with npm 

### ISSUE THREAD

**Issue by diberry** [AzureAD/microsoft-authentication-library-for-js#2633]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library

https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-browser-samples/VanillaJSTestApp2.0

## Description

On Windows 10, using both VSCode bash and Windows cmd, using both package-lock.json and without, with npm and with yarn,  the package.json fails for `npm install`. 

## Error Message

Error message from Windows CMD -

C:\repos\js-e2e\js-e2e-sso\microsoft-authentication-library-for-js\samples\msal-browser-samples\VanillaJSTestApp2.0>npm install
(node:24756) ExperimentalWarning: The fs.promises API is experimental
npm ERR! code EPERM
npm ERR! syscall symlink
npm ERR! path ..\..\..
npm ERR! dest C:\repos\js-e2e\js-e2e-sso\microsoft-authentication-library-for-js\samples\msal-browser-samples\VanillaJSTestApp2.0\node_modules\e2eTestUtils
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, symlink '..\..\..' -> 'C:\repos\js-e2e\js-e2e-sso\microsoft-authentication-library-for-js\samples\msal-browser-samples\VanillaJSTestApp2.0\node_modules\e2eTestUtils'
npm ERR!  { [Error: EPERM: operation not permitted, symlink '..\..\..' -> 'C:\repos\js-e2e\js-e2e-sso\microsoft-authentication-library-for-js\samples\msal-browser-samples\VanillaJSTestApp2.0\node_modules\e2eTestUtils']
npm ERR!   stack:
npm ERR!    'Error: EPERM: operation not permitted, symlink \'..\\..\\..\' -> \'C:\\repos\\js-e2e\\js-e2e-sso\\microsoft-authentication-library-for-js\\samples\\msal-browser-samples\\VanillaJSTestApp2.0\\node_modules\\e2eTestUtils\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '..\\..\\..',
npm ERR!   dest:
npm ERR!    'C:\\repos\\js-e2e\\js-e2e-sso\\microsoft-authentication-library-for-js\\samples\\msal-browser-samples\\VanillaJSTestApp2.0\\node_modules\\e2eTestUtils' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\diberry\AppData\Local\npm-cache\_logs\2020-11-22T13_49_42_461Z-debug.log

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Expected behavior

I expect this same to install regardless of operating system, shell, or package manager.

## Browsers/Environment
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jasonnutter** [comment]
@diberry Can you try running this command with an elevated (admin) command prompt? Also, you can try locally removing the `package-lock.json` file and deleting [this line](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-browser-samples/VanillaJSTestApp2.0/package.json#L17).
