### ISSUE TITLE
ClientAuthError: Token renewal operation failed due to timeout.

### ISSUE THREAD

**Issue by DEEPTI-18** [AzureAD/microsoft-authentication-library-for-js#2634]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
Cdn url  is included in our application for this functionality - https://alcdn.msauth.net/lib/1.3.2/js/msal.js

## Description
When we are trying to do enroll/Signup in one of the scenario in our application, we are getting jwt token correctly. And then we need to call api so for that we are calling below function to get the access token but somehow getting unsual errors in console due to which it failed to renew the token and redirected back to b2c-url.

 function getTokenRedirect(request) {
        return myMSALObj.acquireTokenSilent(request)
            .then((response) => {
                if (response.accessToken) {
                    accessToken = response.accessToken;
                    // logMessage("Request made to Web API:");

                    console.log("accessToken = " + accessToken);
                    if (accessToken) {
                        try {
                            apiCall(myMSALObj, response);
                        } catch (err) {
                            console.log(err);
                        }
                    }
                }
            }).catch(error => {
                console.log("Silent token acquisition fails. Acquiring token using redirect");
                console.log(error);
                // fallback to interaction when silent call fails
                return myMSALObj.acquireTokenRedirect(request);
            });
    }

We are getting below error is console.
**Error1** - Refused to display 'https://tenant.com/policy-name/oauth2/v2.0/authorize?response_type=token&scope=https%3A%2F%2Ftenant.com%2Fapi%2Fdemo.read%20openid%20profile&client_id=xyz&redirect_uri=https%3A%2F%2Fxyz.com%2Fprogress.html&state=xyz&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=xyz&client-request-id=xyz&prompt=none&response_mode=fragment' in a frame because it set 'X-Frame-Options' to 'deny'.

**Error2** - Silent token acquisition fails. Acquiring token using redirect

**Error3**- ClientAuthError: Token renewal operation failed due to timeout.
    at ClientAuthError.AuthError [as constructor] (https://alcdn.msauth.net/lib/1.3.2/js/msal.js:1529:28)
    at new ClientAuthError (https://alcdn.msauth.net/lib/1.3.2/js/msal.js:1414:28)
    at Function.ClientAuthError.createTokenRenewalTimeoutError (https://alcdn.msauth.net/lib/1.3.2/js/msal.js:1440:16)
    at https://alcdn.msauth.net/lib/1.3.2/js/msal.js:4676:62

Can someone please suggest what is going wrong here ?

**Comment by jasonnutter** [comment]
@DEEPTI-18 Please see this document for details and mitigations for this error: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/docs/errors.md#refused-to-display--in-a-frame-because-it-set-x-frame-options-to-deny
