### ISSUE TITLE
BrowserAuthError.interaction_in_progress error persists despite page reloads

### ISSUE THREAD

**Issue by jviney** [AzureAD/microsoft-authentication-library-for-js#2639]
## Library
- [x] `@azure/msal-common@1.7.1`
- [x] `@azure/msal-browser@2.6.1`

## Framework

AngularJS

## Description

User is unable to authenticate. Auth popup opens, but it is blank. Console shows the error: `BrowserAuthError.interaction_in_progress`. Problem persists even after restarting Chrome.

## MSAL Configuration

```js
new PublicClientApplication({
  auth: {
      clientId: "client-id",
    },
    cache: {
      cacheLocation: "localStorage",
      storeAuthStateInCookie: false,
    }
})
```

## Reproduction steps

It looks like a temporary key is used to store the interaction state: 

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/f5da0089bcc3baac759395ac74bbd05dd16fc002/lib/msal-browser/src/interaction_handler/PopupHandler.ts#L38

But if this value is not cleared for any reason, the user is unable to authenticate again. This happened to a couple of our users - but I'm unsure how they got into this state.

## Expected behavior

* The stored interaction state should always be reset when finishing an interaction.
* Reloading the page should reset the interaction state, so that new auths can be performed.

## Browsers/Environment
- [x] Chrome

**Comment by tnorling** [comment]
@jviney We discovered a regression that prevented some temporary cache items from being cleared in certain situations. #2696 addresses this and may also solve this issue. But without knowing the circumstances in which your users reached this bad state I can't say for sure. In any event keep your eyes out for version 2.8.0 in the coming days.

**Comment by jviney** [comment]
> @jviney We discovered a regression that prevented some temporary cache items from being cleared in certain situations. #2696 addresses this and may also solve this issue. But without knowing the circumstances in which your users reached this bad state I can't say for sure. In any event keep your eyes out for version 2.8.0 in the coming days.

Thanks @tnorling. We'll upgrade when 2.8.0 comes out and see if the issue gets reported again.

**Comment by tnorling** [comment]
@jviney Version 2.8.0 has been released. Please give it a shot and let us know whether or not that resolves this issue and, if not, any additional information that might help us determine what's happening here. Thanks!

**Comment by jviney** [comment]
Great - thanks @tnorling. I'll reopen this issue if it still occurs.
