### ISSUE TITLE
Problem when multibyte is included in JWTToken

### ISSUE THREAD

**Issue by ghost** [AzureAD/microsoft-authentication-library-for-js#264]
For example, garbled characters will occur, such as when multibyte is included in the user name.

It is probably caused by calling atob.
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/355dc1fb78651bece7806476879f9955f2cc61e0/src/Utils.ts#L67

**Comment by nehaagrawal** [comment]
HI @HiroyukiSako This is a known issue with window.atob() that it can't support unicode charcaters. There are different ways to solve this issue as per the MDN article( https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding#The_Unicode_Problem) and below stackoverflow link.
https://stackoverflow.com/questions/30106476/using-javascripts-atob-to-decode-base64-doesnt-properly-decode-utf-8-strings
We need to discuss the fix in our team. I will report this as a bug for now.

**Comment by juunas11** [comment]
We also hit this, some of our users have scandinavian characters in their names, like Ö and Ä.
Those get garbled when the Id token is decoded. @nehaagrawal is this on your roadmap?
If you are not going to fix this soon, would you accept a PR if I make one? :D

**Comment by navyasric** [comment]
@juunas11 Are you still open to submit a PR for this? We welcome contribution through PRs.

**Comment by juunas11** [comment]
I'll try to look at it once I have some time. It's been pretty hectic lately so I can't promise a schedule ;)

**Comment by Davilink** [comment]
Ok, i use the code found in decode-jwt on the jwt.ms and find the solution, but i just don't know how do a PR, if someone could help me or do it for me, here the solution:

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/355dc1fb78651bece7806476879f9955f2cc61e0/src/Utils.ts#L95

need to be change for 
```js
return decodeURIComponent(atob(base64IdToken).replace(/(.)/g, function (m, p) {
        var code = p.charCodeAt(0).toString(16).toUpperCase();
        if (code.length < 2) {
          code = '0' + code;
        }
        return '%' + code;
      })); // jshint ignore:line
```
Before the fix:
![image](https://user-images.githubusercontent.com/1498932/52021262-68156a00-24c2-11e9-8438-c7ece002c371.png)

After the fix:
![image](https://user-images.githubusercontent.com/1498932/52021281-7b283a00-24c2-11e9-84f9-caa23288a815.png)

**Comment by sameerag** [comment]
Tracking this with #596

**Comment by sameerag** [comment]
@juunas11 I am trying to integrate this solution in our preview and will update the build details in the tagged #596. Please test and let us know if this works once we release the fix.

**Comment by sameerag** [comment]
#712 fixes this issue. As mentioned above, this will be in the next patch release from msal js, @juunas11 @ghost @jeverduzco @Davilink please feel free to pick the PR or the dev branch (which has the PR now) to test this until the patch is released.
