### ISSUE TITLE
react-msal login not asking to save device for 60 days on MS login screen to skip entering OTP each login

### ISSUE THREAD

**Issue by praveen4949** [AzureAD/microsoft-authentication-library-for-js#2642]
We have react-app that is using msal Authentiction for Login, it is working fine from months, but suddenly it has stopped asking users to save device for 60 days. While login on MS login page no check box is coming for user from 2 days.
But When we logs in office.com of Azure.portal it asks to save device while entering OTP. (Don't ask for 60 days)

We've asked Infra team, and they confirmed that there is no change in MFA settings on Azure portal.

**Comment by jasonnutter** [comment]
@praveen4949 Please file a support request, as this is not an issue with the MSAL.js library: https://docs.microsoft.com/azure/active-directory/develop/developer-support-help-options#open-a-support-request

**Comment by praveen4949** [comment]
Yes, this is not an issue, it is tagged as question, it is happening with only my react application, so there may be any setting or parameter I am missing

**Comment by tnorling** [comment]
@praveen4949 MSAL does not control the sign-in experience. This is likely a configuration either on your app registration or conditional access policies, the support link @jasonnutter shared above can better assist you with this.

**Comment by tnorling** [comment]
Closing as there's no further action from MSAL.js. Please open a new issue if you have other issues with the lib.
