### ISSUE TITLE
acquireTokenByClientCredential s not returning anything when using client_secret

### ISSUE THREAD

**Issue by swapnil-coder-js** [AzureAD/microsoft-authentication-library-for-js#2643]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [x] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Security
- [x] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Browsers/Environment
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by swapnil-coder-js** [comment]
NON WORKING
--------
message =>  [Tue, 24 Nov 2020 07:34:05 GMT] :  : 1.7.2 : Info - acquireTokenByClientCredential called
loglevel =>  2
containsPii =>  false
message =>  [Tue, 24 Nov 2020 07:34:05 GMT] :  : 1.7.2 : Verbose - initializeRequestScopes called
loglevel =>  3
containsPii =>  false
message =>  [Tue, 24 Nov 2020 07:34:05 GMT] :  : 1.7.2 : Verbose - buildOauthClientConfiguration called
loglevel =>  3
containsPii =>  false
message =>  [Tue, 24 Nov 2020 07:34:05 GMT] :  : 1.7.2 : Verbose - createAuthority called
loglevel =>  3
containsPii =>  false
message =>  [Tue, 24 Nov 2020 07:34:05 GMT] :  : 1.7.2 : Verbose - No authority passed in request, defaulting to authority set on application object
loglevel =>  3
containsPii =>  false
message =>  [Tue, 24 Nov 2020 07:34:05 GMT] :  : 1.7.2 : Verbose - Auth client config generated
loglevel =>  3
containsPii =>  false
message =>  [Tue, 24 Nov 2020 07:34:05 GMT] :  : 1.7.2 : Verbose - Retrieving all cache keys
loglevel =>  3
containsPii =>  false
message =>  [Tue, 24 Nov 2020 07:34:05 GMT] :  : 1.7.2 : Verbose - Getting cache key-value store
loglevel =>  3
containsPii =>  false
message =>  [Tue, 24 Nov 2020 07:34:05 GMT] :  : 1.7.2 : Verbose - Item key: server-telemetry-**TENANTID**
loglevel =>  3
containsPii =>  true
message =>  [Tue, 24 Nov 2020 07:34:05 GMT] :  : 1.7.2 : Verbose - Getting cache key-value store
loglevel =>  3
containsPii =>  false
message =>  [Tue, 24 Nov 2020 07:34:05 GMT] :  : 1.7.2 : Verbose - Item key: throttling.{"clientId":"**CLIENTID**","scopes":["**AUTHORITYURL/.default**"]}
loglevel =>  3
containsPii =>  true
message =>  [Tue, 24 Nov 2020 07:34:05 GMT] :  : 1.7.2 : Verbose - Getting cache key-value store
loglevel =>  3
containsPii =>  false
message =>  [Tue, 24 Nov 2020 07:34:06 GMT] :  : 1.7.2 : Verbose - Item key: server-telemetry-**TENANTID**
loglevel =>  3
containsPii =>  true
message =>  [Tue, 24 Nov 2020 07:34:06 GMT] :  : 1.7.2 : Verbose - Getting cache key-value store
loglevel =>  3
containsPii =>  false
message =>  [Tue, 24 Nov 2020 07:34:06 GMT] :  : 1.7.2 : Verbose - Item key: server-telemetry-**TENANTID**
loglevel =>  3
containsPii =>  true
message =>  [Tue, 24 Nov 2020 07:34:06 GMT] :  : 1.7.2 : Verbose - Getting cache key-value store
loglevel =>  3
containsPii =>  false
{
  uniqueId: '',
  tenantId: '',
  scopes: [],
  account: null,
  idToken: '',
  idTokenClaims: null,
  accessToken: '',
  fromCache: false,
  expiresOn: null,
  extExpiresOn: null,
  familyId: null,
  tokenType: '',
  state: ''
} token



------------


WORKING
----


message =>  [Tue, 24 Nov 2020 08:05:48 GMT] :  : 1.7.2 : Info - acquireTokenByClientCredential called
loglevel =>  2
containsPii =>  false
message =>  [Tue, 24 Nov 2020 08:05:48 GMT] :  : 1.7.2 : Verbose - initializeRequestScopes called
loglevel =>  3
containsPii =>  false
message =>  [Tue, 24 Nov 2020 08:05:48 GMT] :  : 1.7.2 : Verbose - buildOauthClientConfiguration called
loglevel =>  3
containsPii =>  false
message =>  [Tue, 24 Nov 2020 08:05:48 GMT] :  : 1.7.2 : Verbose - createAuthority called
loglevel =>  3
containsPii =>  false
message =>  [Tue, 24 Nov 2020 08:05:48 GMT] :  : 1.7.2 : Verbose - No authority passed in request, defaulting to authority set on application object
loglevel =>  3
containsPii =>  false
message =>  [Tue, 24 Nov 2020 08:05:48 GMT] :  : 1.7.2 : Verbose - Auth client config generated
loglevel =>  3
containsPii =>  false
message =>  [Tue, 24 Nov 2020 08:05:48 GMT] :  : 1.7.2 : Verbose - Retrieving all cache keys
loglevel =>  3
containsPii =>  false
message =>  [Tue, 24 Nov 2020 08:05:48 GMT] :  : 1.7.2 : Verbose - Getting cache key-value store
loglevel =>  3
containsPii =>  false
message =>  [Tue, 24 Nov 2020 08:05:48 GMT] :  : 1.7.2 : Verbose - Item key: **KEY WITH TENANT CLIENTID AUTHORITY URL**
loglevel =>  3
containsPii =>  true
message =>  [Tue, 24 Nov 2020 08:05:48 GMT] :  : 1.7.2 : Verbose - Getting cache key-value store
loglevel =>  3
containsPii =>  false
{
  uniqueId: '',
  tenantId: '',
  scopes: [ '**AUTHORITY**/.default' ],
  account: null,
  idToken: '',
  idTokenClaims: null,
  accessToken: '**TOKEN RETURNED**',
  fromCache: true,
  expiresOn: 2020-11-24T08:33:28.000Z,
  extExpiresOn: 2020-11-24T09:33:27.000Z,
  familyId: null,
  tokenType: 'Bearer',
  state: ''
} token

**Comment by jasonnutter** [comment]
@swapnil-coder-js Can you please provide your configuration and relevant code usage? Also, can you please confirm that your application is not registered as a public client?
