### ISSUE TITLE
Redirect Url not being localhost in development

### ISSUE THREAD

**Issue by janusch** [AzureAD/microsoft-authentication-library-for-js#2644]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [X ] `@azure/msal-browser@2.x.x`

## Description
How to use msal-browser.js in development on a VM?
The redirectUrl being set to `localhost` does not work for developing on a VM and accessing the dev server from my local machine. How can I change the config to support this setup, where I am not able to redirect to localhost? The VM does not have HTTPS.

Thank you in advance for regarding my question!

**Comment by jasonnutter** [comment]
@janusch MSAL Browser requires https for non-localhost addresses, so you will need to setup a local https cert. This is because of the restrictions in the Azure Portal, and the crypto APIs used by MSAL.js (which are not available in non-localhost http locations).

**Comment by janusch** [comment]
@jasonnutter Thank you for the swift response. 
I am afraid I will have to figure out how to set up a dev server with a self signed certificate. 
I [saw](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/configuration.md#configuration-options-1) that the default option for `redirectUril` is window.location.href that does not work with http either?
How do you work around this issue? Are the only two options to disable auth for development or to have the dev server run with https?

Thank you again for the help!

**Comment by jasonnutter** [comment]
@janusch Correct, the default redirect uri the library will send to the server is the current page, however, that page must be registered in your app registration, and non-localhost http urls cannot be registered. So yes, those are likely your only two options.

**Comment by tnorling** [comment]
Closing as the original question has been answered. Please open a new issue if you have further questions. Thanks!

**Comment by janusch** [comment]
@jasonnutter Thank you for the reply. It helped me to find a suitable solution for the issue.
Keep up the great work!

**Comment by nomanshahsyed** [comment]
@janusch how did you solve your problem?
