### ISSUE TITLE
acquireTokenSilent() returns an access token signed by the wrong key

### ISSUE THREAD

**Issue by godefroi** [AzureAD/microsoft-authentication-library-for-js#2645]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.7.0`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework
Vanilla JS

## Description
I have an SPA that uses MSAL to authenticate against Azure AD B2C. I call `loginRedirect()` and everything works as expected. Once the redirect comes back, I save the account information in `handleRedirectPromise()` and then use `acquireTokenSilent()` to get an access token to use to call my backend API. This access token, however, is signed by a key that is not one of the keys listed in the JWK key document. I suspect, from research, that maybe I have been given an access token that is supposed to be used to call the MS Graph API, but I do not intend to call that API; I need an access token that can be used to call my backend API. I assume that something is simply misconfigured somewhere, but I've followed every bit of documentation that I can find (most of it is out of date, references MSAL 1.x), and nothing works.

## Error Message
The backend API, when attempting to validate the access token, reports that the signature key cannot be found.

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
const msalConfig = {
	auth: {
		clientId: '96582630-b045-4a92-b798-c1b7448335ad', // (not my real client id)
		authority: 'https://mytenant.b2clogin.com/tfp/mytenant.onmicrosoft.com/B2C_1_signupsignin1',
		knownAuthorities: ['https://mytenant.b2clogin.com/tfp/mytenant.onmicrosoft.com/B2C_1_signupsignin1'],
		redirectUri: 'http://localhost:3000'
	}
};
```

## Reproduction steps
```js
// login is done as follows:
const loginRequest: msal.RedirectRequest = {
	scopes: ["openid", "profile", "offline_access"],
	extraScopesToConsent: ["https://mytenant.onmicrosoft.com/backend-api/normal-things"]
};

msalInstance.loginRedirect(loginRequest);


// access token is obtained as follows:
let request: msal.SilentRequest = {
	scopes: ["openid", "https://mytenant.onmicrosoft.com/backend-api/normal-things"],
	account: accountInfo // (or null?)
};

msalInstance.acquireTokenSilent(request).then(tokenResponse => {
	accessToken = tokenResponse.accessToken;
}).catch(error => {
	if (error instanceof msal.InteractionRequiredAuthError) {
		// fallback to interaction when silent call fails
		return msalInstance.acquireTokenRedirect(request);
	} else {
		console.log(error);
	}
});
```

## Expected behavior
I would expect that the access token I receive from `acquireTokenSilent()` would be usable by my backend API; instead, it is not.

## Browsers/Environment
- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jasonnutter** [comment]
We believe this is an issue with the B2C service. Please file a support ticket with the B2C team by following the instructions here: https://docs.microsoft.com/azure/active-directory-b2c/support-options

They can help you out further, they may ask for a public repro link or additional data. You can also link this Github issue in the support request.

**Comment by godefroi** [comment]
So, I'm not sure that I'm willing to pay $29/month for the privilege of reporting what you believe is a bug in Azure AD B2C. Is there any other way to contact them?

**Comment by sameerag** [comment]
@nickgmicrosoft Can someone in your team address this?

**Comment by nickgmicrosoft** [comment]
Hi @godefroi , can you paste a copy of (anonymized) access token? Could help debug.

**Comment by godefroi** [comment]
@nickgmicrosoft according to jwt.ms:

```
{
  "typ": "JWT",
  "alg": "RS256",
  "kid": "X5eXk4xyojNFum1kl2Ytv8dlNP4-c57dO6QGTVBwaNk"   <-- this is NOT one of the "kid" values from my JWK document
}.{
  "iss": "https://mytenant.b2clogin.com/[my tenant id (GUID)]/v2.0/",
  "exp": 1606263527,
  "nbf": 1606259927,
  "aud": "[the GUID of my 1st application registration in AD B2C]",
  "oid": "[my user's object ID in AD B2C]",
  "sub": "[my user's object ID in AD B2C]",
  "emails": [
    "[the email address I logged in with]"
  ],
  "tfp": "B2C_1_signupsignin1",
  "nonce": "282df8df-3c1a-4289-b242-f00cfd07e35d",
  "scp": "normal-things",
  "azp": "[the GUID of my 2nd application registration in AD B2C]",
  "ver": "1.0",
  "iat": 1606259927
}.[Signature]
```

**Comment by godefroi** [comment]
Looks like we got it taken care of over at https://docs.microsoft.com/en-us/answers/questions/174150/acquiretokensilent-returns-an-access-token-signed.html
