### ISSUE TITLE
msal-react with AAD B2C Guidance

### ISSUE THREAD

**Issue by MarekLani** [AzureAD/microsoft-authentication-library-for-js#2651]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ x] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Please I would like to use msal-react with AAD B2C. Can you provide brief guidance how to achieve that and create proper configuration including setting the scopes. This is my config, but it does not work. I am getting 400 with error message: Clients must send a client_secret when redeeming a confidential grant

```
const tenant = "mytenant.onmicrosoft.com";

const signInPolicy = "B2C_1_signupsignin1";
const applicationID = "123...";
const reactRedirectUri = "http://localhost:1234";
const tenantSubdomain = tenant.split(".")[0];
const signInAuthority = `${instance}${tenant}/${signInPolicy}`;
const authorityDomain = "mytenant.b2clogin.com"

export const msalConfig = {
  auth: {
      clientId: applicationID,
      authority: signInAuthority,
      knownAuthorities: [
        authorityDomain
      ],
      redirectUri:reactRedirectUri,
      navigateToLoginRequestUrl: true,
      clientCapabilities: [
        "cp1"
      ]
  }
};
```

**Comment by MarekLani** [comment]
@tnorling thanks you for quick reaction and help. Indeed when I created Public Client it worked. It was setup as Web type of app before. Once I have whole authentication piece working including calling API with access token I receive I will create quick sample in my github repo. And will let you know when ready, you can consider then, whether it is something to include in samples or link. Thanks again.

**Comment by tnorling** [comment]
Great thanks for the update!
