### ISSUE TITLE
Username property is empty in the getallAccounts response

### ISSUE THREAD

**Issue by Sharatmenon** [AzureAD/microsoft-authentication-library-for-js#2654]
## Library
- [ ] `@azure/msal-browser@6.0.0`

## Description
We are using getallAccounts call to get the account for acquireTokenSilent flow. The account object has a username field which is always empty. Can you suggest what can be done to retrieve the username? 

FYI. I am using a custom policy for signin /signup. 

**getallAccounts Response:** 

environment: "test.b2clogin.com"
homeAccountId: "xxxxx_signuporsignin.xxx"
localAccountId: "xxxxx"
name: "unknown"
tenantId: "xxxxx"
username: ""

**Comment by tnorling** [comment]
@Sharatmenon You will need to enable the `emails` claim on your B2C tenant. Please see our [FAQ](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md#why-is-getaccountbyusername-returning-null-even-though-im-signed-in) for more on this. If you need more assistance please open a support ticket with the [B2C Service](https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options) as they can better assist you with your policy configuration.

**Comment by Sharatmenon** [comment]
Hi @tnorling, Thanks for your response.
I did add the below statement to my custom policy which started showing the sign in email address in the Idtokenclaims. I don't want the email address to show up in the idtokenclaims as it is PII, we are using a user id to identify the logged in user. It should show the username only in the account object which is retrieved from getallaccounts call once the user is logged in. Any guidance would be appreciated.

**Added the below to my custom policy**
<OutputClaim ClaimTypeReferenceId="signInNames.emailAddress" PartnerClaimType="email" />

**Comment by tnorling** [comment]
@Sharatmenon The `username` field on the `AccountInfo` object returned from `getAllAccounts` is populated from the claims on the idToken, if the information is not available on the claims it will not be available on the `AccountInfo`. That said, you should not need a `username` to get a cached token or when exchanging a refresh token for a new access token, were you having any specific issues?

**Comment by Sharatmenon** [comment]
@tnorling Yes , I need to make the msal.acquireTokenSilent call but don't have a login hint. When I use the below request I get an error saying there isn't sufficient info for the silent call to succeed. In another article, I read that this call either needs login hint or else the sid (session id). I am using custom policies and am not sure how to get the session id for this call. 

**Sample request:**

export const loginRequest = {
  scopes: [
    "https://xyz.onmicrosoft.com/api/data.write"],
    account: account,
    redirectUri: msalConfig.redirectUri
  
}

**Comment by tnorling** [comment]
@Sharatmenon Right, that error will happen when the refresh token expires (24 hours). Until that happens you should not need the `login_hint` to silently acquire a token (acquiring from cache or by exchanging a valid RT should not require it). 

When the refresh token expires you have 2 options:
1. Call an interactive method (acquireTokenRedirect or acquireTokenPopup)
2. Provide a `login_hint`, which in your case means you need to enable the `emails` claim or find another way to obtain and manage the current user's email so that you can pass it to the API

**Comment by Sharatmenon** [comment]
@tnorling Thanks for your inputs. One other option was to use a session id for acquireTokenSilent call. I couldn't find any references on how to pull a sid for a user. Do you know how we could get an sid using custom policy ?

**Comment by tnorling** [comment]
@Sharatmenon sid is not supported in B2C scenarios, the 2 options I listed above are your only options currently.

**Comment by Sharatmenon** [comment]
@tnorling - I just read a doc where it said the refresh tokens for a SPA with PKCE can be a max of 24 hrs not more than that, is that true?

**Comment by tnorling** [comment]
@Sharatmenon That's correct.

**Comment by Sharatmenon** [comment]
Thanks for your help @tnorling

**Comment by Sharatmenon** [comment]
Hi @tnorling 

I have a few more quesion
