### ISSUE TITLE
acquireTokenSilent Not Updating The Token

### ISSUE THREAD

**Issue by BarishSarac** [AzureAD/microsoft-authentication-library-for-js#2659]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library: 
- [x] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
"msal": "^1.4.4",
## Description
Initially user logs in and system is able to generate a session in the localStorage. But even though I run acquireTokenSilent and get token at each API call, token in the localStorage never gets updated and acquireTokenSilent never gets a newer token. For testing purposes I changed value of "Access & ID token lifetimes (minutes)" and "Web app session lifetime (minutes)" in b2c to 15 so session is only 15 minutes long. I am trying to ensure acquireTokenSilent is able to extend the session but it never extends it.

## Error Message
Since session length is 15 minutes, after 15 minutes, user gets force logged out, no session extending happening at the moment.

## Security
- [yes] Is this issue security related?

## Regression
- [no] Did this behavior work before? 
Version:

## MSAL Configuration
```js
export const msalApp = new UserAgentApplication({
  auth: {
    clientId: "" //B2C Client ID
    authority: "" 
    validateAuthority: false,
    storeAuthStateInCookie: true,
    redirectUri: "",
    postLogoutRedirectUri: "",
    navigateToLoginRequestUrl: false,
    loadFrameTimeout: 1,
  },
  cache: {
    cacheLocation: "localStorage",
    storeAuthStateInCookie: false,
  },
  system: {
    navigateFrameWait: 1,
    // logger: new Logger(
    //   (logLevel, message) => {
    //     console.log(message);
    //   },
    //   {
    //     level: LogLevel.Verbose,
    //     piiLoggingEnabled: true,
    //   }
    // ),
  },
});
```

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Expected behavior
acquireTokenSilent to extend the session when session length goes below certain threshold. 

## Browsers/Environment
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

I have below function run each time I do an API call, so I can check if user has less than 12 minutes left in their session, then try to extend it.
```js
acquireTokenPossibly = async () => {
      if (this.state.account) {
        let SessionTimeLeft = Math.round(
          (this.state.account.idToken.exp - Math.round(Date.now() / 1000)) / 60
        );
        if (SessionTimeLeft <= 12) {
          const token = await this.acquireToken();
          const account = msalApp.getAccount();
          console.log(account);
          console.log(token);
          // this.setState({ token, account });
          return token;
        } else {
          return this.state.token;
        }
      }
    };
```

And I have acquireToken function like this
```js
acquireToken = async () => {
      let apiScopes = [
        "https://" +
          process.env.REACT_APP_AZURE_SERVICE +
          ".onmicrosoft.com/" +
          process.env.REACT_APP_AZURE_API_SCOPES +
          "/user_impersonation",
      ];

      let token = await msalApp
        .acquireTokenSilent({ scopes: apiScopes.slice() })
        .catch((err) => console.log(err));
      return token.accessToken;
    };
```

this is the initial state
   ```js
 constructor(props) {
      super(props);
      this.state = {
        account: null,
        error: null,
        email: null,
        token: null,
      };
    }
```
Note: if there is any other code I need to provide to clarify my setup, I can please let me know.

**Comment by jasonnutter** [comment]
@FlyRocketDrones By default, access tokens have an expiration of 1 hour. This expiration is separate from the session expiration. If you want to force MSAL to get a new token, set `forceRefresh` to `true` when calling `acquireTokenSilent`.

**Comment by FlyRocketDrones** [comment]
@jasonnutter Thank you! I will test it out with `forceRefresh:true`  that to confirm.

**Comment by FlyRocketDrones** [comment]
@jasonnutter so I have `.acquireTokenSilent({ forceRefresh: true, scopes})` and still I am not able to extend the session each time I do

```
let token = await msalApp
        .acquireTokenSilent({ forceRefresh: true, scopes })
        .catch((err) => console.log(err));
      return token.accessToken;
```

**Comment by tnorling** [comment]
@FlyRocketDrones Looks like you are checking idToken expiration and then trying to acquire an access token? Can you try including `openid` in your scope list? That should result in a request for both a new idToken and accessToken. Additionally, you should not have to check expiration yourself as msal does that as part of `acquireTokenSilent`

**Comment by BarishSarac** [comment]
@tnorling How would I be able to include openid in my scope list? I removed the expiry check now and testing. `.acquireTokenSilent({ forceRefresh: true, scopes: apiScopes.slice() })` still is not extending user's session, it goes down from 60 to 0 then goes to login screen...

This is how I acquire token now
     ```
 let token = await msalApp
        .acquireTokenSilent({ forceRefresh: true, scopes: apiScopes.slice() })
        .catch((err) => this.logout());

      return token.accessToken;
```

**Comment by tnorling** [comment]
@BarishSarac 
> How would I be able to include openid in my scope list?

`.acquireTokenSilent({ forceRefresh: true, scopes: [...apiScopes, "openid"] })`

**Comment by BarishSarac** [comment]
No change, still goes thru initial 60 mins then expires... it does not extend..

**Comment by tnorling** [comment]
@BarishSarac Can you send me a network trace? Email is on my profile.

**Comment by BarishSarac** [comment]
@tnorling just did, thank you

**Comment by HarmanDhunna** [comment]
@BarishSarac Hello, could you check what is the lifetime of id/access token? 
![image](https://user-images.githubusercontent.com/63318798/102563465-31cd3d80-408e-11eb-9803-68fa32d6ff7c.png)

**Comment by BarishSarac** [comment]
Hello @HarmanDhunna, it's 60. I made it 20 earlier to test if it behaves differently it did not. session length started from 20 in that case instead of 60 but didnt extend either.

**Comment by HarmanDhunna** [comment]
What is the difference between the issue time and expiration time of the idToken when you set it to 20minutes?

**Comment by BarishSarac** [comment]
@HarmanDhunna do you mean Web app session lifetime (minutes) in terms of expiration time?

**Comment by tnorling** [comment]
@BarishSarac We took a look at the network logs you sent us and the expiration on both idToken and accessToken are updating. Can you clarify what exactly you are experiencing?

**Comment by BarishSarac** [comment]
> @BarishSarac We took a look at the network logs you sent us and the expiration on both idToken and accessToken are updating. Can you clarify what exactly you are experiencing?

@tnorling so in the file I declare Auth, I save the account into the state like this
```
const account = msalApp.getAccount();
const token = await this.acquireToken();
const email = account.idToken.emails[0].toLowerCase();
const userName = account.idToken.name;
this.setState({ account, token, email, userName });
```
Then I provide it from this HOC using `accountExp={this.state.account.idToken.exp}` then I have a file that checks if user's current session is active or not every 1 minute and if not logs the user out. 

```
    let Check = setInterval(function () {
      let SessionTimeLeft = Math.round(
        (props.ExpirationTime - Math.round(Date.now() / 1000)) / 60
      );
      if (SessionTimeLeft < 1) {
        console.log("yes expired");
        props.LogUserOut();
      } else {
        console.log("not expired left: " + SessionTimeLeft);
      }
    }, 1000 * 1 * 1); // every minute
```

Since you proved that session is getting extended, I assume I need to find a way to check that and update it in the Auth I have so I can keep the state of that updated along the whole time.

     ```
 this.state = {
        account: null,
        error: null,
        email: null,
        token: null,
      };
```

**Comment by BarishSarac** [comment]
I used this to send expiration reference, still it sends initially 60, never changes and goes down from there even if I  do API call
`accountExp={msalApp.getAccount().idToken.exp}`

**Comment by tnorling** [comment]
@BarishSarac Can you confirm that you still have `forceRefresh: true`, included `openid` in your scope list, and you are calling acquireTokenSilent before attempting to retrieve an updated `exp` from `getAccount`? Can you do some debugging to determine what's happening in your scenario or provide a link to a sample we can use to try and reproduce?

**Comment by BarishSarac** [comment]
@tnorling forceRefresh: true is still there and openid is in scope list still. So the main question is how can I get a hold of user's current session expiration time? is it `msalApp.getAccount().idToken.exp` ? and if I continously console.log this, I should see it at 60 each time I do acquireToken, correct?

**Comment by tnorling** [comment]
@BarishSarac 

>  if I continously console.log this, I should see it at 60 each time I do acquireToken, correct?

Correct. As long as `acquireToken` is going to the network and retrieving a new idToken, the next call to `getAccount` should reflect a new expiration. You can also try getting the idToken directly from the response of `acquireTokenSilent` and see if that makes a difference.

**Comment by BarishSarac** [comment]
I confirmed now it updates. I had to create a function within Auth file and share that to child component to be used to update/check the session length.

Thank you everyone!
