### ISSUE TITLE
ADFS 2019 support in msal-browser

### ISSUE THREAD

**Issue by thibaultvdb-incerta** [AzureAD/microsoft-authentication-library-for-js#2660]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
I saw in the PR (https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/1791) that ADFS on-premise is supported in version 1.4.0. Is this also added to the msal-browser version (v2)?
If so, is there any documentation or example for it? We're in need of ADFS 2019.

**Comment by tnorling** [comment]
@thibaultvdb-incerta ADFS 2019 should be supported in msal-browser, however, it will require some configuration on your ADFS server. We unfortunately do not have a sample for this yet, but plan to add one in the future.

In short you will need to do the following things:
- Ensure your ADFS server supports OAuth
- Enable CORS on the server
- Set Refresh Token lifetime to a maximum of 24 hours
- Msal Configuration: Provide your authority in the `knownAuthorities` parameter
- Msal Configuration: Set `ProtocolMode` to `OIDC`

Some docs you may find useful: 
- [Enabling CORS on ADFS Server](https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/customize-http-security-headers-ad-fs#cross-origin-resource-sharing-cors-headers)
- [Pre-requisites for using msal-browser with ADFS](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/docs/ADFS.md)
- [Msal Config Options](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/initialization.md#optional-configure-authority)

Let us know if you have any more specific questions.
