### ISSUE TITLE
Why there is a msal:popUpHashChanged event raised from MSAL?

### ISSUE THREAD

**Issue by chenxinyanc** [AzureAD/microsoft-authentication-library-for-js#2661]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Recently I saw the usage of `msal:popUpHashChanged` event in our repo when trying to retrieve access token via pop-up window in an Angular application. A (simplified) sample of such usage looks like this
```ts
getTokenPopup(authParams: AuthenticationParameters): Promise<string> {
    return new Promise((resolve, reject) => {
        /* _msal: UserAgentApplication */
        this._msal.acquireTokenPopup(authParams).catch(/* error handling */);
        window.addEventListener('msal:popUpHashChanged', (event: CustomEvent) => {
          resolve(event.detail);
        });
    });
}
```

It seems that this event is designed specifically for Angular application. But after [some simple web searching](https://www.bing.com/search?q=%22popUpHashChanged%22), I think this event is not part of ADAL / MSAL public API
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/81d6145cba4f55a5615b610255edabdd12dcab9b/lib/msal-core/src/UserAgentApplication.ts#L609-L612

Additonally, this event is introduced since AzureAD/azure-activedirectory-library-for-js#390 (`adal:popUpHashChanged`), but I'm not sure why this event gets introduced.

My questions are:
* why does this event exist? Does it guarantee to return a valid access token?
* (most importantly) is there any potential pitfall if I write the function above more straightforwardly (in Angular)?
```ts
getTokenPopup(authParams: AuthenticationParameters): Promise<string> {
    const response = await this._msal.acquireTokenPopup(authParams);
    return response.accessToken;
}
```

**Comment by jasonnutter** [comment]
@chenxinyanc The `msal:popUpHashChanged` event will include the raw hash value from the popup, which will then need to be manually decoded. This event is deprecated, and has been removed in MSAL Angular v2, so it is not recommended to build logic based on it. We recommend invoking `acquireTokenPopup` directly, or using the MSAL Interceptor.

**Comment by chenxinyanc** [comment]
Thanks for the information @jasonnutter!
