### ISSUE TITLE
missing slash in aud of token

### ISSUE THREAD

**Issue by VanyLaw** [AzureAD/microsoft-authentication-library-for-js#2665]
I use msal 1.4.4 to get arm token. but the token can not pass the authentication in kudu `/zipdeploy` api, because of the value in aud miss a slash.

I call `msal.acquireTokenPopup` or `msal.acquireTokenSilent` to get the token. the scope I use is `https://management.core.windows.net/user_impersonation`

FYI. I decode the token got by msal.
![image](https://user-images.githubusercontent.com/21174180/100407314-0fee2580-30a3-11eb-9e38-3f8dd9e2ee1c.png)

## Library
- [x] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Browsers/Environment
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jasonnutter** [comment]
@VanyLaw This is likely an issue with Project Kudu, not MSAL.js (which is not responsible for the claims values in tokens). I would recommend reporting this issue to them: https://github.com/projectkudu/kudu/wiki#getting-help
