### ISSUE TITLE
React / JS / Angular MSAL unit tests example request

### ISSUE THREAD

**Issue by ArranM** [AzureAD/microsoft-authentication-library-for-js#2668]
It would be handy to see jest unit tests for the msal 2 library. as port of the examples.

logonRedirect
loginPopup

AuthenticatedTemplate
isLoggedIn  

 Thanks

**Comment by jasonnutter** [comment]
@ArranM You can see tests for MSAL React [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-react/test). We are also planning to add E2E tests for MSAL React before GA. cc: @tnorling 

Please look at the existing unit tests and let us know if you have further questions, thanks!

**Comment by ArranM** [comment]
@jasonnutter thanks, that has helped me so much, I now have only 1 test left, is user clicks logout in AuthenticatedTemplate

spying on instance.logout() seem to generate an end point issue (for me) if I setup handleRedirectSpy initially and then action logout. 

but really, thanks it really helped me understand it much better.

**Comment by tnorling** [comment]
@ArranM You should mock out the logout function to prevent it from trying to do a full frame redirect to the AAD service. If you need to simulate a logout you can clear the account cache instead and then emit the logout event to ensure msal-react updates context. Take a look at [these tests](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/test/components/MsalAuthenticationTemplate.spec.tsx) for examples on mocking out the msal-browser APIs

**Comment by tnorling** [comment]
Closing as the question was answered. Please open a new issue if you have follow up questions. Thanks!
