### ISSUE TITLE
SPA "Any Active Directory multitenant and personal Microsoft accounts" msal throwing  InteractionRequiredAuthError

### ISSUE THREAD

**Issue by sasimsit** [AzureAD/microsoft-authentication-library-for-js#2672]
SPA Application deployed using "**Any Active Directory multitenant and personal Microsoft accounts**" msal throwing  InteractionRequiredAuthError 

## Library
 [ x] msal@1.4.0

## Description
SPA application should work In "Any Active Directory Multitenant and personal Microsoft accounts "  mode.  we have configured in azure deployment steps. 

## Error Message
On launching application, Microsoft showing account  selection  **"Connected to Windows"** section, then selecting account. we got  acquireTokenFailure InteractionRequiredAuthError:  and redirected to again and again login screen.
![image](https://user-images.githubusercontent.com/34427782/100704122-f44c8d00-33ca-11eb-853e-2ce04e21dc82.png)
![image](https://user-images.githubusercontent.com/34427782/100704276-3c6baf80-33cb-11eb-814a-1af9003f5411.png)

But this issue not occurred if  not "Connected to Windows" scenario's , (user entering into the "signed in" or "newly login-in" mode We could procced the application and the msal IdToken available in localstorage )

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration
**Configuration :**
```javascript
{
    "auth": { 
        "clientId": "xxxxxxxxxxxxxxxxxxxxxxxx",
        "authority": "https://login.microsoftonline.com/common",
        "validateAuthority": true,
        "redirectUri": "http://localhost:4200/loginSuccess",
        "postLogoutRedirectUri": "http://localhost:4200/",
        "navigateToLoginRequestUrl": false
    },
    "cache": {
        "cacheLocation": "localStorage",         
    }
    "scopes": {
        "loginRequest": [
            "openid",
            "profile"
        ]
    },
    "graphApi": {
            "resourceUri": "https://graph.microsoft.com/v1.0/me/memberOf",
            "resourceScope": "user.read"
     }    
}
```

## Reproduction steps
```javascript
  this.http.get(GRAPH_ENDPOINT)
      .subscribe({
        next: (profile: any) => {
          this.profile = profile;   
        },
        error: (err: AuthError) => {
          if (InteractionRequiredAuthError.isInteractionRequiredError(err.errorCode)) {           
            this.authService.acquireTokenRedirect({
              scopes: this.authService.getScopesForEndpoint(GRAPH_ENDPOINT),
              authority: config.auth.authority,
              redirectUri: config.auth.redirectUri,
              onRedirectNavigate: (url: string) => {
                console.log(url);
              }
            }); 
          }
        },
        complete: () => this.goToApplicationLaunch()
      }); 
```

## Expected behavior
Application should allow to select personal account and get proper msal token and procced further activities in application. 

## Browsers/Environment
- [x] Chrome
- [ ] Firefox
- [x] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by tnorling** [comment]
@sasimsit Could you try upgrading to version 1.4.4 and let us know if this is still an issue? That version addresses some issues getting id_tokens from cache. If updating does not solve this, please send me a network trace showing this behavior so that I can investigate. My email is on my profile. Thanks!
