### ISSUE TITLE
handleRedirectPromise called but there is no interaction in progress, returning null after successful login 

### ISSUE THREAD

**Issue by luisamckenna1** [AzureAD/microsoft-authentication-library-for-js#2675]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [X] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
    "@azure/msal-angular": "2.0.0-alpha.0",
    "@azure/msal-browser": "2.7.0",

## Description
After successful login, handleRedirectObservable and HandleRedirectPromise return null even when logs show user has successfully logged in. Additionally, sessionstorage show successful login but these methods continue to return null. 

## Error Message
[Tue, 01 Dec 2020 15:31:12 GMT] :  : 1.7.2 : Info - handleRedirectPromise called but there is no interaction in progress, returning null.

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration
export function MSALInstanceFactory(): IPublicClientApplication {
  let config = {
    "auth": {
      "clientId": "...",
      "authority": "...", 
      "navigateToLoginRequestUrl": true,
      "postLogoutRedirectUri": ""
    },
    "cache": {
        "storeAuthStateInCookie": true
    },
    "system": {
      ....
      },
  },
  }
  return new PublicClientApplication(config);
}

export function MSALInterceptorConfigFactory() {
  const protectedResourceMap = new Map<string, Array<string>>();
  protectedResourceMap.set("https://localhost:...", ["api://.../access_as_user"]);

  let config = {
    "popUp": false,
    "consentScopes": [
        ["openid", "profile"],
        "api://.../access_as_user"
    ],
    "interactionType": InteractionType.Redirect,
    "protectedResourceMap": protectedResourceMap
  }
  return config;
}

export function MSALGuardConfigFactory() {
  return { interactionType: InteractionType.Redirect };
}

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```
N/A -> failure occurs in simple scenario with login with no B2C policies set up

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```
In my scenario, I have one login screen with a login button
Login Component
-> Login button interaction-> msalService.loginRedirect(..);
Home Component
-> handleRedirectObservable/handleRedirectPromise(..); *** does not resolve appropriately***

## Expected behavior
The goal is to capture the user logged with tokens after successful handleRedirectObservable callback.
It is expected to return AuthenticationResult with the user info and tokens.

## Browsers/Environment
- [ X] Chrome
- [ ] Firefox
- [ X] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jasonnutter** [comment]
@luisamckenna1 What page are you using for your redirect URI? And is this page protected by the MSAL Guard?

**Comment by luisamckenna1** [comment]
After successful login it redirects to https://localhost../#/reports. The redirect occurs correctly from a UI flow. This is protected with MSAL GUARD. 

const routes: Routes = [
    { path: 'reports', component: HomeComponent, canActivate:[MsalGuard]},
    { path : '', component: SignInComponent},
    //{ path: 'logout', component: SignoutComponent},
    { path: 'reports/:id', component: ReportViewerComponent, canActivate:[MsalGuard]},
    { path: 'code', redirectTo: 'reports'}
];

**Comment by jasonnutter** [comment]
@luisamckenna1 The MSAL Guard will also [invoke handleRedirectObservable](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/msal-angular-v2/lib/msal-angular/src/msal.guard.ts#L71). Given that `handleRedirectPromise` will only return a non-null value the first time it is called, if your app sets the redirect URI to a page that is protected by the MSAL Guard, if you call `handleRedirectObservable` or `handleRedirectPromise` elsewhere in your app, they may receive a null response, as you observe. We recommend setting the redirect URI for your app to page that is not protected by the MSAL Guard, to mitigate behavior like this.

**Comment by luisamckenna1** [comment]
What about the scenario below:
**1st login scenario** 
- User logins through login page -> redirects to https://localhost../#/reports

**2nd Scenario**
- User directly accesses https://localhost/#/reports and attempts to authenticate themselves
- This would redirect the user to the current page which in this case is https://localhost/#/reports
**In this scenario we need to have MSALGuard on /#/reports so the user can directly access /#/reports and it be protected**

How do I successfully capture a userlogin/tokens without the use of hanldRedirectObservable and handleRedirectPromise? Previously I used handleRedirectCallback (msal.js 1...) to capture the user after login.

**Comment by tnorling** [comment]
@luisamckenna1 In order to get the logged in accounts you can call `msalService.instance.getAllAccounts()`, in order to get tokens you can listen to the [broadcastService](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/05b27e4673c9af6d8756503538b4f550ede40a1d/samples/msal-angular-v2-samples/angular11-sample-app/src/app/app.component.ts#L29) or call `msalService.instance.acquireTokenSilent({scopes: ["api://.../access_as_user"], account: AccountInfo})`
