### ISSUE TITLE
Prepopulate Cache Storage from E2E-Tests

### ISSUE THREAD

**Issue by nniikkoollaaii** [AzureAD/microsoft-authentication-library-for-js#2676]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
I'm developing an app, which I'm testing via the e2e test tool Cypress.

Now I'm starting to use msal-browser in my application like in your sample [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular10-browser-sample)

I could try to implement in my cypress tests to insert a test user and password on https://login.microsoftonline.com/ .

But first it's not recommended to test third-party-sites in your e2e-tests because changes breaking your tests aren't under my control
and second it would not be possible to do so with cypress because cypress loads the websites in an iframe which isn't allowed by login.microsoftonline.com

This problem is heavily discussed in this [issue](https://github.com/cypress-io/cypress/issues/1342) at the cypress project.

Solutions here are

1) load your app in something like puppeteer (where you can load login.microsoftonline.com), navigate through the thrid-party-app login.microsoftonline.com and copy the session storage to my cypress browser instance

2) load required token via cypress with an alternative oauth2 flow like client_crendentials and prepolulate the token cache with this token. So when cypress opens the app, msal-browser would return an account / token for the correct service call. [Here](https://xebia.com/blog/how-to-use-azure-ad-single-sign-on-with-cypress/) is an example for the library react-adal.

In my opinion solution 2 seems better because I do not want to test third-party-sites.

Solution 2 is not applicable for msal-browser because msal-browser is saving a lot more information in the cache storage than only an access (and id) token.

Could you provide some guidance if and how we could prepopulate the cache storage?

I could check before calling msal-browser if there is an custom key-value-pair in the session storage and use this access token in my interceptor and do the same in my route guard but this solutions seems not optimal to me

**Comment by tnorling** [comment]
@nniikkoollaaii One option would be to use [msal-node](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-node) to obtain your tokens and then write them to local/session storage in your browser. `msal-node` and `msal-browser` both use `msal-common` to do things like caching so the keys and values will be the same across. An example cache file outputted by msal-node can be found [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-node-samples/standalone-samples/silent-flow/data/example.cache.json)

As this question has come up a few times, I'm also going to look into how we can make this easier in the future, I'll leave this issue open until then.

**Comment by tnorling** [comment]
@nniikkoollaaii I've linked a PR which demonstrates how this could be done with `msal-node`, Jest and Puppeteer. Let me know if you have any questions.

**Comment by nniikkoollaaii** [comment]
Looks good.
Thank you very much!
