### ISSUE TITLE
Token missing in request

### ISSUE THREAD

**Issue by HelplessFlo** [AzureAD/microsoft-authentication-library-for-js#2679]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [x] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
I am developing an Application with Angular in the frontend and Spring Boot Resource Server in the backend. The frontend should authenticate against the Azure AD and get the token to call my backend. The project is deployed in two docker containers on Azure Container Instances. Now my problem is, that everything works fine when I test locally. If I deploy it to Azure I get an 401 Unauthorized on the first call of my backend. What I can see is, that there is an Authentication-Header in the request if I run the application locally but it is missing if it is deployed to Azure Container Instances. Can someone explain this behavior and has  solution for this?

My app.module.ts is configured like this:
```javascript
export function MSALInstanceFactory(): IPublicClientApplication {
  return new PublicClientApplication({
    auth: {
      clientId: '*****',
      redirectUri: environment.msalConfig.loginRedirectUri,
      authority: 'https://login.microsoftonline.com/****',
      navigateToLoginRequestUrl: true
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE // set to true for IE 11
    }
  });
}

export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
  const protectedResourceMap = new Map<string, Array<string>>();
  protectedResourceMap.set('https://graph.microsoft.com/v1.0/me', ['user.read']);
  protectedResourceMap.set('https://graph.microsoft.com/v1.0/users', ['user.read']);
  protectedResourceMap.set(environment.msalConfig.apiUrl, ['api://*******/app']);

  return {
    interactionType: InteractionType.Redirect,
    protectedResourceMap
  };
}

export function MSALGuardConfigFactory(): MsalGuardConfiguration {
  return { interactionType: InteractionType.Redirect };
}
```

My routing:
```javascript
const routes: Routes = [
  { path: 'dashboard', component: DashboardWrapperComponent, children: [{path: '', component: DashboardComponent}], canActivate: [MsalGuard], canActivateChild: [AuthGuardUserService]},
  { path: 'admin', component: DashboardWrapperComponent, children: [{path: '', component: AdminComponent}], canActivate: [MsalGuard], canActivateChild: [AuthGuardAdminService] },
  { path: 'logout', component: LogoutPageComponent, pathMatch: 'full'},
  { path: '**', redirectTo: 'dashboard'}
];
```

The call looks like this:
```javascript
return this.http.get(this.baseUrl + "/user").pipe(
            map((profile: UserDTO) => {return profile;})
        );
```

**Comment by tnorling** [comment]
@HelplessFlo Could you debug the Interceptor and compare the url that is passed to the interceptor with the url you provided in the `protectedResourceMap` as it is possible that the interceptor is receiving a relative url even though you have provided an absolute url or vice versa.

**Comment by sandrooco** [comment]
You probably should add a wildcard to your api requests. I'm guessing thatyour `msalConfig.apiUrl` is only a base url without the `/user` endpoint.

Possible solution: `protectedResourceMap.set(environment.msalConfig.apiUrl + '**', ...);` 

We use it like this: `'https://somebackendurl.ch/api/**',`

**Comment by HelplessFlo** [comment]
> @HelplessFlo Could you debug the Interceptor and compare the url that is passed to the interceptor with the url you provided in the `protectedResourceMap` as it is possible that the interceptor is receiving a relative url even though you have provided an absolute url or vice versa.

@tnorling Thank you very much, I added only "/api" to my protectedResourceMap and it works as intended.


> You probably should add a wildcard to your api (base) url. I'm guessing that your `msalConfig.apiUrl` is only a base url without the `/user` endpoint.
> 
> Possible solution: `protectedResourceMap.set(environment.msalConfig.apiUrl + '**', ...);`
> 
> We use it like this: `'https://somebackendurl.ch/api/**',`

@sandrooco Thank you for your answer too, even if this was not the problem.
