### ISSUE TITLE
No return access token from either loginRedirect or acquireTokenSilent

### ISSUE THREAD

**Issue by JTInfinite** [AzureAD/microsoft-authentication-library-for-js#2681]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.7.0`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

I'm using Vue if that is what is meant by framework

## Description

I am unable to obtain an access token post successful login. I have tried multiple different scopes and understand that if there is no resource scope requested then it stands to reason that no access token should be returned. 

I have read over the issue #2315 thread a couple of times, which has been helpful but ultimately didn't offer a solution for me, aside from hinting at the possibility that there is an issue/bug with b2c itself - which is of course disappointing

Version:

vue2.6.12

## MSAL Configuration

```
const msalConfig = {
  auth: {
    clientId: "xxxxxx", 
    authority: "https://xxxxx.b2clogin.com/xxxxx.onmicrosoft.com/B2C_1_signupsignin", 
    knownAuthorities: ["xxxx.b2clogin.com"], 
    redirectUri: "http://localhost:8080/user/login"
  },
  cache: {
    cacheLocation: "sessionStorage",
    storeAuthStateInCookie: false,
  },
};
```

## Reproduction steps
```
// Some Vue scaffolding omitted - most of this is called in the beforeMount event hook...

let request = {
     scopes: ["https://xxxxx.b2clogin.com/xxxxx.onmicrosoft.com/user.read"],
      } // I've tried a number of different versions of this including a simple "user.read". I have granted my app api permissions to the microsoft graph api 


this.$msal.loginRedirect(request) // This returns no access token although I am expecting it to with the scope I have requested

this.$msal.handleRedirectPromise().then(this.handleResponse).catch(err => {
            // Login failed
            console.log(err)
            //this.$router.push('/error')
        })


// this.handleResponse: - again, this fails to return an access code.
let request = {
                scopes: ["https://xxxxx.b2clogin.com/xxxx.onmicrosoft.com/user.read"], // Same scope as requested originally
                account: this.$msal.getAccountByLocalId(resp.account.localAccountId)
            }

            let res = await this.$msal.acquireTokenSilent(request).catch(error => {
                console.warn("silent token acquisition fails. acquiring token using redirect");
                console.log(error)
                if (/*error instanceof this.$msal.InteractionRequiredAuthError ||*/ error.errorMessage.includes("AADB2C90077") || error.errorMessage.includes("AADB2C90117")) {
                    // fallback to interaction when silent call fails
                    return
                    //return this.$msal.acquireTokenRedirect(request);
                } else {
                    console.warn(error);
                }
            })
            if (res.accessToken) {
                return res.accessToken
            } else {
                console.log("no access")
                //return await this.$msal.ssoSilent(request)
            }

```

## Expected behavior

As I am requesting a resource scope, I am expecting an access_token...

## Browsers/Environment
- [ ] Chrome
- [ ] Firefox
- [X] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by tnorling** [comment]
@JTInfinite Are you trying to obtain an access token for MS Graph or is `user.read` a custom scope you configured on your B2C tenant? You cannot obtain tokens for MS Graph using delegated permissions when using a B2C tenant, this is documented [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/working-with-b2c.md).

Can you try creating a custom scope on your app registration and see if that gets you an access token back?

**Comment by JTInfinite** [comment]
@tnorling yes, I am trying to obtain a token for MS Graph. I've reread the documentation you sent and I think its becoming more clear...

I created a custom scope on my app registration and included it as the scope in the loginRedirect and the subsequent acquireTokenSilent and nothing changes...no token:

![tempsnip](https://user-images.githubusercontent.com/16175334/100941536-b0a07300-34f1-11eb-9123-06d8e5a3d711.png)

Forgive the redacting - I'm not entirely sure what is sensitive

Thanks for your assistance thus far!

**Comment by JTInfinite** [comment]
Hi @tnorling - I've managed to get an access token for a customer scope working. I had to create a webAPI app registration which exposed an endpoint and scope etc..etc..

I'm abit confused now between the scopes and permission section on the webapi app. What does my custom scope relate to? How do I expose microsoft graph through my webapi app to my client app?

Thanks!

**Comment by JTInfinite** [comment]
I am at the stage where I've written an API and am using the b2c registered app secret to get the MS Graph token.

What I don't understand is where the user login and subsequent tokens come into this? How can I make it so an access token from my logged in user is used to access my api, which in turn accesses ms graph?

**Comment by tnorling** [comment]
@JTInfinite Can you clarify what data you're interested in getting from MS Graph and what Identity providers you are using for B2C?

**Comment by JTInfinite** [comment]
@tnorling Thanks for getting back to me.

I've managed to get an access token from my SPA. I've managed to get an azure function to request an access token to use to retrieve a list of users in my B2C directory. 

I'm now working through the docs to understand how to protect the azure function API with B2C.

I've run through this two part documentation:
https://docs.microsoft.com/en-us/azure/active-directory-b2c/tutorial-single-page-app-webapi?tabs=app-reg-ga

...but it uses express and my translation into Azure function doesn't return anything...never used passport.js before.

I'm now on this doc:
https://docs.microsoft.com/en-us/azure/api-management/howto-protect-backend-frontend-azure-ad-b2c

which seems to be taking me down a APIM route.

I wonder if you can point me in the right direction: SPA -> Login -> Protected Azure Function API -> Get data (from multiple sources)?

The documentation for B2C is almost cryptic.

**Comment by JTInfinite** [comment]
I managed to protect an azure function using the B2C access token. 

Still not 100% sure as the webapi registered app in B2C uses the implicit grant flow.

Anyway, at least I have a working system now.

**Comment by derisen** [comment]
@JTInfinite instead of translation you can perhaps use the [azure-function-express](https://www.npmjs.com/package/azure-function-express) library? There is a [sample here](https://github.com/Azure-Samples/ms-identity-nodejs-webapi-azurefunctions) featuring that.

**Comment by JTInfinite** [comment]
@derisen thanks - that looks really cool. Wish i'd found it 2 days ago!

**Comment by derisen** [comment]
Sorry about that, missed this thread : )
