### ISSUE TITLE
Api permissions in SPA app registration

### ISSUE THREAD

**Issue by mulej2** [AzureAD/microsoft-authentication-library-for-js#2685]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Please provide your question here, including as much relevant details as possible.

Examples: 
> "How do I use MSAL with Vue.js"
> "How do I SSO between tabs?"
> "How do I use MSAL to protect my custom Web API?"
> "How can my app support multiple AAD tenants?"
> "When will my scenario be supported?"
> "When will this framework be supported"

I have a React.js application which authenticates user's using msal-browser (auth code flow with PKCE), and I also have a Web API (node.js rest api) which verifies user's token and then returns secure data to the frontend application. This Web API also access to graph api using its own access token (retrieved by using client secret).

Should I register both apps separately to AD? SPA and Web API.

Or is it OK to register only one app for both? I mean, should I just define SPA redirect uris for SPA and give "Delegated" type api permissions. And also create a client secret for web api and add "Application" type api permissions?

**Comment by tnorling** [comment]
@mulej2 Either approach should work. If you try it out and have any issues feel free to let us know
