### ISSUE TITLE
Root Err: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by thoo1** [AzureAD/microsoft-authentication-library-for-js#2690]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.6.1`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Description
Seeing some users get the error below where it says the Root Err: SyntaxError: JSON.parse

## Error Message
State was not the expected format. Please check the logs to determine whether the request was sent using ProtocolUtils.setRequestState(). Invalid State: b81eecce-5da7-4803-90f3-fe0b23113180, Root Err: ClientAuthError: invalid_state: State was not the expected format. Please check the logs to determine whether the request was sent using ProtocolUtils.setRequestState(). Invalid State: b81eecce-5da7-4803-90f3-fe0b23113180, Root Err: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
    const browser = Bowser.getParser(window.navigator.userAgent);
    const isIEOrOldEdge =
      browser.satisfies({ edge: "<79" }) || browser.getBrowserName().toLowerCase() === "internet explorer";
    const publicClientApp = new PublicClientApplication({
      auth: {
        clientId: this.clientId,
        authority: this.authority,
        redirectUri: this.loginRedirectUri,
        postLogoutRedirectUri: this.postLogoutRedirectUri
      },
      cache: {
        cacheLocation: "localStorage",
        storeAuthStateInCookie: isIEOrOldEdge // https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1188#issuecomment-634281307
      },
      system: {
        tokenRenewalOffsetSeconds: 60,
        iframeHashTimeout: 30000, // iframe is used to refresh the refresh_token as it has a 24h lifetime
        loggerOptions: {
          loggerCallback: MsalAuthContext.msalLoggerCallback,
          piiLoggingEnabled: false,
          logLevel: LogLevel.Verbose
        }
      }
    });
    const handleRedirectPromise = publicClientApp
      .handleRedirectPromise()
      .then(response => {
        this.account = response ? response.account : this.getAccount();
        if (!this.account) {
          CoreLogger.trackEvent(TelemetryEventName.Core_MSALAuthContext_login);
          return this.publicClientApp.loginRedirect({
            scopes: this.scopes,
            authority: this.authority,
            extraQueryParameters: this.safeRolloutQueryParams,
            redirectStartPage: returnUrl
          });
        } else {
          this.setTenantId(this.account.tenantId);
        }
        return undefined;
      })
      .catch(error => {
        if (error instanceof AuthError) {
          this.trackError(error);
        }
        this.loginToTenantRedirect(MsalAuthContext.defaultTenantId);
      });
    return { publicClientApp, handleRedirectPromise };
```

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Expected behavior
No JSON.parse error

## Browsers/Environment
- [X] Chrome
- [X] Firefox
- [X] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by tnorling** [comment]
@thoo1 Can you provide some minimal steps to reproduce or any additional information that might help us determine a root cause? 

Typically this error would be thrown in scenarios where the initial request did not originate from msal. Or even potentially a version mismatch between the msal-browser instance that initiated the request vs the one that is processing the response. The state string in the error message above does not match the format of what msal sets for state so I'd be interested to find out where that's coming from.

**Comment by thoo1** [comment]
@tnorling oh that could be it.. let me check more in depth but in our app, we are currently trying to move to msal-browser, region by region, so there could be chance that the old auth implementation is contributing to this error

I'll look more in depth and update

**Comment by thoo1** [comment]
yep, looks to be the case, we had enabled msal-browser through a flight while some users were using the old auth implementation, causing the states to mismatch

Closing, thanks for your help!
