### ISSUE TITLE
Multiple tokens(claims) from different resources

### ISSUE THREAD

**Issue by iulianmarius** [AzureAD/microsoft-authentication-library-for-js#2697]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [x] `@azure/msal-angular@2.0.0-alpha.0`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
Angular 11
## Description
Hello i migrate from Angular Msal 1.x to 2.x because i need to use the code flow. with angular-msal 1.x was possible to get tokens from multiple sources but now i get an error : interaction_in_progress: Interaction is currently in progress.

If i request only scopes from one resource (graph for example) everything is working as expected.

## Error Message
ERROR Error: Uncaught (in promise): BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.
BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.
## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```here is my configuration 
export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
  const protectedResourceMap = new Map<string, Array<string>>();
  protectedResourceMap.set("https://graph.microsoft.com/beta/users/", [
    "user.read",
    "user.read.all",
  ]);
  protectedResourceMap.set("https://graph.microsoft.com/v1.0/users/", [
    "user.read",
    "user.read.all",
  ]);
  protectedResourceMap.set("https://graph.microsoft.com/v1.0/groups/", [
    "group.read.all",
  ]);
  protectedResourceMap.set("https://graph.microsoft.com/beta/groups/", [
    "group.read.all",
  ]);
  protectedResourceMap.set(variables.kvsFunctionsHostname, [
    `${environment.kvsAzureAppIdURI}/Access.Api`,
  ]);
  
   protectedResourceMap.set("https://app.powerbi.com/reportEmbed",[
    "https://analysis.windows.net/powerbi/api/Dashboard.Read.All",
    "https://analysis.windows.net/powerbi/api/Report.Read.All",
    "https://analysis.windows.net/powerbi/api/Dataset.Read.All"
  ]) ;
 return {
    interactionType: InteractionType.Redirect,
    protectedResourceMap,
  };

export function MSALInstanceFactory(): IPublicClientApplication {
  return new PublicClientApplication({
    auth: {
      authority:environment.authority,
      clientId: environment.appId,
      redirectUri: OAuthSettings.redirectUri,
      postLogoutRedirectUri: OAuthSettings.postLogoutRedirectUri,
      navigateToLoginRequestUrl:true
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE, // set to true for IE 11
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Info,
        piiLoggingEnabled: false,
      },
    },
  });
}

## Reproduction steps
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Browsers/Environment
- [x ] Chrome
- [ ] Firefox
- [x ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jasonnutter** [comment]
@iulianmarius I'm guessing that this is happening because your app is making multiple concurrent http requests, each of which are potentially resulting in an error when the interceptor invokes `acquireTokenSilent`. Can you please debug the interceptor and figure out the errors being thrown by `acquireTokenSilent` in the interceptor?

**Comment by jasonnutter** [comment]
If you have logs from the MSAL Logger, that may also be helpful.

**Comment by iulianmarius** [comment]
I found more info:
this errors i get while the login window is shown- so before actually logging in. after login i get only one token:
![image](https://user-images.githubusercontent.com/5133575/101224708-b8961980-368f-11eb-9aac-3786a3c235ec.png)

but if i  refresh the page i get all 3 tokens and everything is working as expected.
![image](https://user-images.githubusercontent.com/5133575/101224782-fabf5b00-368f-11eb-89f2-2f8058458107.png)

**Comment by jasonnutter** [comment]
@iulianmarius Can you try passing all of the scopes from your protectedResourceMap to MSAL.js when you invoke login?

```js
this.msalService.loginPopup({
  scopes: [
    "user.read",
    "user.read.all",
    "group.read.all",
    `${environment.kvsAzureAppIdURI}/Access.Api`,
    "https://analysis.windows.net/powerbi/api/Dashboard.Read.All",
    "https://analysis.windows.net/powerbi/api/Report.Read.All",
    "https://analysis.windows.net/powerbi/api/Dataset.Read.All"
  ]
});
```

**Comment by hypertrends** [comment]
Hello,
Is it fair to assume that if we have multiple APIs with each having their scopes, then the MSAL library will allow us to pass the scopes we need and get the ID and Access tokens correctly? Previously, it appears that this was either an MSAL or an Azure AAD B2C limitation.

We have multiple Microservices, e.g. Tenants API with scopes (tenants.admin, tenants.read) and Affiliates API with scopes (affiliates.admin, affiliates.read) and we have a React Client Application which will require all these scopes. If we utilize the code below, will it return an Access token correctly? The reason we're asking is that this was documented as a known limitation previously and we can't seem to find an update on this.

`this.msalService.loginPopup({
  scopes: [
    "tenants.admin",
    "affiliates.admin"
  ]
});`

**Comment by tnorling** [comment]
@hypertrends You cannot obtain an access token for scopes that span more than 1 resource. [Read more about scopes and resources here.](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/resources-and-scopes.md)

In your case, assuming the Tenants API and Affiliates API are 2 distinct resources you will need to make 2 separate access token requests. You can do the first with `loginPopup` and the 2nd with `acquireTokenPopup` or `acquireTokenSilent`. If you request scopes from more than 1 resource in your login call you will be allowed to consent to each scope, but you will only receive an access token for one of them.

**Comment by hypertrends** [comment]
@tnorling - thank you for the detailed response here. It is a little surprising that it will not work across different resources. Does this mean that we have to keep these access tokens for various APIs in local storage and then also pick the correct access token before making the API call to the correct API? 

We have used Identity Server 4.0 previously with multiple resources and this has never been a problem. Is this something that is being worked on and can this be changed?

The reason I mention this is that we have approximately 15+ micro-services at the present moment and will only grow in size as our application grows. This can post a serious obstacle to our plans on using Azure AAD B2C for our needs.

Would love to hear more about any potential plans on changing this down the line? I'm curious if using an API Gateway model helps here where we register all scopes under the API Gateway as a resource? It's not an ideal solution for us, but we might have to implement this in the worst-case scenario.

**Comment by tnorling** [comment]
@hypertrends 

> Does this mean that we have to keep these access tokens for various APIs in local storage and then also pick the correct access token before making the API call to the correct API?

When using msal.js you do not need to handle storage of tokens yourself as this is done by the library. All you need to do is call `acquireTokenSilent` with the scopes you need a token for before calling your API and msal will return to you the correct token either from local/session storage or by making a new request to the network, if the token is expired or cannot be found in the cache.

> We have used Identity Server 4.0 previously with multiple resources and this has never been a problem. Is this something that is being worked on and can this be changed?

There are no plans to change this behavior, as far as I know. Azure AD issues access tokens for a single audience by design. 

> I'm curious if using an API Gateway model helps here where we register all scopes under the API Gateway as a resource? It's not an ideal solution for us, but we might have to implement this in the worst-case scenario.

You could do this but the recommended way to handle this scenario is to call `acquireTokenSilent` every time before calling your API. Msal will handle all the cache lookup logic for you under the hood, all you need to provide is the scopes you need an access token for. This is the recommendation regardless of whether you keep all the API scopes separate or under the same resource.

**Comment by hypertrends** [comment]
@tnorling - thank you again for the response. Good to know that MSAL.js will take care of the access token management. This simplifies things greatly. I will evaluate this as a strategy moving forward and implement this. If we need anything else at our end, we will definitely reach out.

Thank you again for all the help and have a great one!
