### ISSUE TITLE
AADSTS900144: The request body must contain the following parameter: 'client_id'.

### ISSUE THREAD

**Issue by bladmorenoacn** [AzureAD/microsoft-authentication-library-for-js#2699]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.4.4` 
- [ ] `@azure/msal-angular@1.1.2`

## Framework
Angular 11

## Description

When the library tries to get the access token in test environment we get this error with Angular 11, we started to experience this in incognito mode, for some reason when the Access token is being requested the client_id paramenter is lost in the process

## Error Message

AADSTS900144: The request body must contain the following parameter: 'client_id'.

## Security
- [ ] Is this issue security related?

## Regression
- [ ] Did this behavior work before? 
Version:
We were working with MSAL "@azure/msal-angular": "^0.1.4", but stopped working for not apparent reason, We saw a similar issue that supposed to be solved with the upgrade to "@azure/msal-angular": "^1.X" so we upgraded and we got a different issue now, that is the one the we are reporting here
## MSAL Configuration
Cannot provide actual values for authority ID and ClientID but they are valid We have been working with this ids for beyond a year.

```js
 "msal": {
    "auth":{
      "authority": "https://login.microsoftonline.com/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
      "clientID": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX",
      "redirectUri": "https://XXXXX.acn.com"
    },
    "protectedResourceMap": [
      [
        "https://XXXXXX.XXXXX.acn.om",
        [
          "user.read",
          "openid",
          "profile"
        ]
      ]
    ]
  },
```

## Reproduction steps
authorization Module code:
```js
export function AuthConfigFactory(config: AppConfigService): Configuration {
  const isIE = config.isIE();
  const cfg = Object.assign({}, config.config.msal, {
    cache: {
      cacheLocation:isIE?'localStorage':'sessionStorage'
    }
  });
  return cfg;
}

export function MSALAngularConfigFactory(
  config: AppConfigService
): MsalAngularConfiguration {

  const cfg = Object.assign({
    protectedResourceMap: new Map(Object.entries(config.config.msal.protectedResourceMap))
  });

  return cfg || {};
}

```

## Expected behavior
SSO Logging with no issues

## Browsers/Environment
- [X ] Chrome
- [ ] Firefox
- [ X] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jasonnutter** [comment]
@bladmorenoacn In your code above, you have `clientID`, as opposed to `clientId`. Please update your configuration and let us know if this is still an issue.

**Comment by bladmorenoacn** [comment]
I did made the change now I am getting a CORS Error, the Access Token is not being injected as a header in the protectedResources url, is working on dev env, but not on test or stage

Access to XMLHttpRequest at 'https://XXXXXX..XXXXX.acn.com/api/v1/XXXXXXX?XXXXXXX=false' from origin 'https://XXXXXX.XXXXX.acn.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by bladmorenoacn** [comment]
On Stage environment now I am getting 

ERROR TypeError: Cannot read property 'indexOf' of undefined
    at MsalService.push../node_modules/msal/lib-commonjs/UserAgentApplication.js.UserAgentApplication.saveTokenFromHash (VM16 main-es2015.4846726f9b0b64775122.js:147203)
    at MsalService.push../node_modules/@azure/msal-angular/dist/msal.service.js.MsalService.processHash (VM16 main-es2015.4846726f9b0b64775122.js:140081)
    at new MsalService (VM16 main-es2015.4846726f9b0b64775122.js:140007)
    at _createClass (VM16 main-es2015.4846726f9b0b64775122.js:67894)
    at _createProviderInstance (VM16 main-es2015.4846726f9b0b64775122.js:67855)
    at resolveNgModuleDep (VM16 main-es2015.4846726f9b0b64775122.js:67802)
    at NgModuleRef_.get (VM16 main-es2015.4846726f9b0b64775122.js:68888)
    at injectInjectorOnly (VM16 main-es2015.4846726f9b0b64775122.js:41820)
    at Module.ɵɵinject (VM16 main-es2015.4846726f9b0b64775122.js:41830)
    at RebarAuthService_Factory (VM16 main-es2015.4846726f9b0b64775122.js:195235)

**Comment by tnorling** [comment]
@bladmorenoacn Can you confirm which versions of `msal` and `msal-angular` are generating that stack trace? We would not expect `msal-angular@1.1.2` to generate what was shown above.

The CORS error is thrown by your API, please verify that your API server is setup to handle CORS requests.

**Comment by bladmorenoacn** [comment]
versions are 
"@azure/msal-angular": "^1.1.2", 
"msal": "1.4.4"

**Comment by bladmorenoacn** [comment]
I updated the configuration and now I am getting this error, and the token is not being injected in to the request headers:

ERROR Error: Uncaught (in promise): ClientAuthError: Login_In_Progress: Error during login call - login is already in progress.
ClientAuthError: Login_In_Progress: Error during login call - login is already in progress.
    at ClientAuthError.AuthError [as constructor] (VM16 main-es2015.7a6230a39e66b10e29e4.js:77644)
    at new ClientAuthError (VM16 main-es2015.7a6230a39e66b10e29e4.js:22981)
    at Function.push.7ZR7.ClientAuthError.createLoginInProgressError (VM16 main-es2015.7a6230a39e66b10e29e4.js:23018)
    at MsalService.push.ZES5.UserAgentApplication.acquireTokenInteractive (VM16 main-es2015.7a6230a39e66b10e29e4.js:82438)
    at MsalService.push.ZES5.UserAgentApplication.loginRedirect (VM16 main-es2015.7a6230a39e66b10e29e4.js:82351)
    at MsalGuard.<anonymous> (VM16 main-es2015.7a6230a39e66b10e29e4.js:28982)
    at Generator.next (<anonymous>)
    at VM16 main-es2015.7a6230a39e66b10e29e4.js:137391
    at new ZoneAwarePromise (VM14 polyfills-es2015.754a1f4a2e3a09879603.js:17485)
    at __awaiter (VM16 main-es2015.7a6230a39e66b10e29e4.js:137387)
    at resolvePromise (VM14 polyfills-es2015.754a1f4a2e3a09879603.js:17323)
    at resolvePromise (VM14 polyfills-es2015.754a1f4a2e3a09879603.js:17275)
    at VM14 polyfills-es2015.754a1f4a2e3a09879603.js:17385
    at ZoneDelegate.invokeTask (VM14 polyfills-es2015.754a1f4a2e3a09879603.js:16924)
    at Object.onInvokeTask (VM16 main-es2015.7a6230a39e66b10e29e4.js:121871)
    at ZoneDelegate.invokeTask (VM14 polyfills-es2015.754a1f4a2e3a09879603.js:16923)
    at Zone.runTask (VM14 polyfills-es2015.754a1f4a2e3a09879603.js:16692)
    at drainMicroTaskQueue (VM14 polyfills-es2015.754a1f4a2e3a09879603.js:17094)

**Comment by tnorling** [comment]
@bladmorenoacn Can you explain the steps to getting that stack trace? Login in progress errors happen when an interactive request (popup or redirect) is initiated while another one is already in progress.

**Comment by bladmorenoacn** [comment]
This is the enviroment,
Angular 11,
Libraries:
"@azure/msal-angular": "^1.1.2",
"msal": "1.4.4"

I already described the configuration above,
"msal": {
    "auth":{
      "authority": "https://login.microsoftonline.com/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
      "clientID": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX",
      "redirectUri": "https://XXXXX.acn.com"
    },
    "protectedResourceMap": [
      [
        "https://XXXXXX.XXXXX.acn.om",
        [
          "user.read",
          "openid",
          "profile"
        ]
      ]
    ]
  },

and the module configuration as well:
export function AuthConfigFactory(config: AppConfigService): Configuration {
  const isIE = config.isIE();
  const cfg = Object.assign({}, config.config.msal, {
    cache: {
      cacheLocation:isIE?'localStorage':'sessionStorage'
    }
  });
  return cfg;
}

export function MSALAngularConfigFactory(
  config: AppConfigService
): MsalAngularConfiguration {

  const cfg = Object.assign({
    protectedResourceMap: new Map(Object.entries(config.config.msal.protectedResourceMap))
  });

  return cfg || {};
}

I have this code in the Auth Service component:
 ngOnInit() {

        this.sucessSub = this.broadcastService.subscribe("msal:acquireTokenSuccess", payload => {
            sessionStorage.setItem('msal.access_token', payload._token);
        });
        this.failureSub = this.broadcastService.subscribe("msal:acquireTokenFailure", payload => {
            this.notificationService.showError('Authentication Server is taking longer than expected to Response, Retring...');
            this.adquireTokeSilentRetry();
        });
        this.isIframe = window !== window.parent && !window.opener;
    
        this.broadcastService.subscribe('msal:loginSuccess', () => {
          console.log('login Success');
        });

        this.broadcastService.subscribe('msal:loginFailure', () => {
            console.error('login Failed');
            this.auth.loginRedirect();
            
          });
    
        this.auth.handleRedirectCallback((authError, response) => {
          if (authError) {
            console.error('Redirect Error: ', authError.errorMessage);
            sessionStorage.clear();
            return;
          }
          
          if (this.IsUserAuthenticated()) {
              console.log('User is Authenticated');
          }
          console.log('Redirect Success: ', response);
        });
    
        this.auth.setLogger(new Logger((logLevel, message, piiEnabled) => {
          console.log('MSAL Logging: ', message);
        }, {
          correlationId: CryptoUtils.createNewGuid(),
          piiLoggingEnabled: false
        }));
      }

   public adquireTokeSilentRetry() {
        const accessTokenRequest = {
            scopes: ['user.read', 'openid', 'profile']
        }

        this.auth.acquireTokenSilent(accessTokenRequest).then(tokenResponse => {
            console.log('msal:acquireTokenSilent',tokenResponse);
            return 
        }
        ).catch((error) => {
            console.error('catch msal:acquireTokenSilent ' + JSON.stringify(error));
            if (error.errorMessage.indexOf("interaction_required") !== -1) {
                //this.auth.acquireTokenRedirect(accessTokenRequest);
            }
        }).finally(() => { console.log('finally msal:acquireTokenSilent ') });

    }

--

in the app.component I have this code:

ngOnInit() {
        if (this.rebarAuth.authenticationEnabled()) {
            if (!this.rebarAuth.IsUserAuthenticated()) {
                this.isVisible = false;
                this.notificationService.showError('You must loging');
            } else {
                this.isVisible = true;
                this.rebarAuth.adquireTokeSilentRetry();
            }
        } else {
            this.isVisible = true;
        }

    }
---
Once I was getting the error above 
ERROR Error: Uncaught (in promise): ClientAuthError: Login_In_Progress: Error during login call - login is already in progress.

I commented the line
 this.rebarAuth.adquireTokeSilentRetry();

and after that I am not getting the access token being injected in the headers.

If I leave the adquireTokeSilentRetry() method in place I get the duplicated authentication error plus no access token being injected.


 I encounter is that the MSAL does not find the scopes, I was debugging the code in the browser and what I found is that for some reason instead to consider the protectedResourceMap as configure, it goes and try to read the configuration as framework.protectedResourceMap, then when it tries to get the keys in an array, the scopes are not being able to be retrieve, and in consecuence the access token is not being injected

**Comment by tnorling** [comment]
@bladmorenoacn You shouldn't have to call `acquireTokenSilent` manually, the interceptor should handle that. Also can you debug the interceptor to determine if the url in the `protectedResourceMap` matches the url that is provided to the interceptor? It is possible you may need to configure your `protectedResourceMap` with relative urls a demonstrated [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2515#issuecomment-727108424). You can also take a look at our [angular samples](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-samples/angular9-sample-app) to help you get set up.

**Comment by bladmorenoacn** [comment]
I am calling adquireTokenSilent only when the authentication fails, I can try to use the relative paths, We have been using these urls for about a year, We upgrade the library and they were working well until a couple of weeks ago,

Is this mandatory parameter?
 consentScopes: [
      "user.read",
      "openid",
      "profile",
      "api://a88bb933-319c-41b5-9f04-eff36d985612/access_as_user"
    ],

**Comment by bladmorenoacn** [comment]
I found a fix for the none generation of the token, now I am getting this different error,

ERROR InteractionRequiredAuthError: AADSTS50058: A silent sign-in request was sent but no user is signed in. The cookies used to represent the user's session were not sent in the request to Azure AD. This can happen if the user is using Internet Explorer or Edge, and the web app sending the silent sign-in request is in different IE security zone than the Azure AD endpoint (login.microsoftonline.com).
Trace ID: 269d0ce3-383b-415d-9000-aa834858ca00
Correlation ID: 469f483a-d9f0-415a-9865-acb240e26dbc
Timestamp: 2020-12-15 04:06:19Z
    at InteractionRequiredAuthError.AuthError [as constructor] (https://uhuman.accenture.com/main-es2015.e088897c0e6213547c86.js:77804:28)
    at InteractionRequiredAuthError.ServerError [as constructor] (https://uhuman.accenture.com/main-es2015.e088897c0e6213547c86.js:66289:28)
    at new InteractionRequiredAuthError (https://uhuman.accenture.com/main-es2015.e088897c0e6213547c86.js:8974:28)
    at MsalService.push.ZES5.UserAgentApplication.saveTokenFromHash (https://uhuman.accenture.com/main-es2015.e088897c0e6213547c86.js:83868:25)
    at MsalService.push.ZES5.UserAgentApplication.processCallBack (https://uhuman.accenture.com/main-es2015.e088897c0e6213547c86.js:83306:29)
    at MsalService.push.ZES5.UserAgentApplication.handleAuthenticationResponse (https://uhuman.accenture.com/main-es2015.e088897c0e6213547c86.js:83365:14)
    at MsalService.<anonymous> (https://uhuman.accenture.com/main-es2015.e088897c0e6213547c86.js:83082:34)
    at step (https://uhuman.accenture.com/main-es2015.e088897c0e6213547c86.js:71018:23)
    at Object.next (https://uhuman.accenture.com/main-es2015.e088897c0e6213547c86.js:70999:53)
    at fulfilled (https://uhuman.accenture.com/main-es2015.e088897c0e6213547c86.js:70989:58)

**Comment by bladmorenoacn** [comment]
I found the solution enabling third party cookies in incognito mode

**Comment by tnorling** [comment]
@bladmorenoacn Great, thanks for following up. `msal-angular@2.0.0`, is currently in [alpha](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-angular) and should handle third party cookie problems better than version 1. Can this issue be closed?

**Comment by bladmorenoacn** [comment]
Yes please, so your ultimate recommendation would be to upgrade to msal-angular@2.0.0, right?

thank you so much

**Comment by tnorling** [comment]
@bladmorenoacn Yes, version 2 solves several problems we are unable to solve in version 1, including problems with 3rd party cookies.
