### ISSUE TITLE
TypeError: Cannot read property 'getUser' of undefined | 0.1.4

### ISSUE THREAD

**Issue by spottedmahn** [AzureAD/microsoft-authentication-library-for-js#270]
We're seeing the following error w/ 0.1.4 from the MSAL Logger:

>Thu, 15 Mar 2018 16:06:41 GMT:12345-0.1.4-Error Error occurred in token received callback function: TypeError: Cannot read property 'getUser' of undefined

### Full Log
>webpack-internal:///../../../../../src/app/shared/telemetry.service.ts:89 msal.js: Thu, 15 Mar 2018 16:06:21 GMT:12345-0.1.4-Info Returned from redirect url
webpack-internal:///../../../../../src/app/shared/telemetry.service.ts:89 msal.js: Thu, 15 Mar 2018 16:06:25 GMT:12345-0.1.4-Info State status:true; Request type:LOGIN
webpack-internal:///../../../../../src/app/shared/telemetry.service.ts:89 msal.js: Thu, 15 Mar 2018 16:06:41 GMT:12345-0.1.4-Info State is right
webpack-internal:///../../../../../src/app/shared/telemetry.service.ts:89 msal.js: Thu, 15 Mar 2018 16:06:41 GMT:12345-0.1.4-Info Fragment has id token
webpack-internal:///../../../../../src/app/shared/telemetry.service.ts:70 msal.js: Thu, 15 Mar 2018 16:06:41 GMT:12345-0.1.4-Error Error occurred in token received callback function: TypeError: Cannot read property 'getUser' of undefined
TelemetryService.logException @ webpack-internal:///../../../../../src/app/shared/telemetry.service.ts:70
TelemetryService.logError @ webpack-internal:///../../../../../src/app/shared/telemetry.service.ts:121
AuthenticationService.error @ webpack-internal:///../../../../../src/app/shared/authentication.service.ts:239
AuthenticationService.msalLoggerCallback @ webpack-internal:///../../../../../src/app/shared/authentication.service.ts:259
AuthenticationService.logger.msal_1.Logger.level @ webpack-internal:///../../../../../src/app/shared/authentication.service.ts:26
Logger.executeCallback @ webpack-internal:///../../../../msal/lib-commonjs/Logger.js:68
Logger.logMessage @ webpack-internal:///../../../../msal/lib-commonjs/Logger.js:61
Logger.error @ webpack-internal:///../../../../msal/lib-commonjs/Logger.js:75
UserAgentApplication.handleAuthenticationResponse @ webpack-internal:///../../../../msal/lib-commonjs/UserAgentApplication.js:1130
UserAgentApplication @ webpack-internal:///../../../../msal/lib-commonjs/UserAgentApplication.js:114
AuthenticationService @ webpack-internal:///../../../../../src/app/shared/authentication.service.ts:57
_createClass @ webpack-internal:///../../../core/esm5/core.js:11114
_createProviderInstance$1 @ webpack-internal:///../../../core/esm5/core.js:11086
resolveNgModuleDep @ webpack-internal:///../../../core/esm5/core.js:11071
NgModuleRef_.get @ webpack-internal:///../../../core/esm5/core.js:12307
AuthenticationInterceptor.intercept @ webpack-internal:///../../../../../src/app/shared/authentication.interceptor.ts:28
HttpInterceptorHandler.handle @ webpack-internal:///../../../common/esm5/http.js:1835
(anonymous) @ webpack-internal:///../../../common/esm5/http.js:1505
MergeMapSubscriber._tryNext @ webpack-internal:///../../../../rxjs/_esm5/operators/mergeMap.js:133
MergeMapSubscriber._next @ webpack-internal:///../../../../rxjs/_esm5/operators/mergeMap.js:123
Subscriber.next @ webpack-internal:///../../../../rxjs/_esm5/Subscriber.js:97
ScalarObservable._subscribe @ webpack-internal:///../../../../rxjs/_esm5/observable/ScalarObservable.js:53
Observable._trySubscribe @ webpack-internal:///../../../../rxjs/_esm5/Observable.js:178
Observable.subscribe @ webpack-internal:///../../../../rxjs/_esm5/Observable.js:166
MergeMapOperator.call @ webpack-internal:///../../../../rxjs/_esm5/operators/mergeMap.js:97
Observable.subscribe @ webpack-internal:///../../../../rxjs/_esm5/Observable.js:163
FilterOperator.call @ webpack-internal:///../../../../rxjs/_esm5/operators/filter.js:63
Observable.subscribe @ webpack-internal:///../../../../rxjs/_esm5/Observable.js:163
MapOperator.call @ webpack-internal:///../../../../rxjs/_esm5/operators/map.js:60
Observable.subscribe @ webpack-internal:///../../../../rxjs/_esm5/Observable.js:163
MapOperator.call @ webpack-internal:///../../../../rxjs/_esm5/operators/map.js:60
Observable.subscribe @ webpack-internal:///../../../../rxjs/_esm5/Observable.js:163
CatchOperator.call @ webpack-internal:///../../../../rxjs/_esm5/operators/catchError.js:83
Observable.subscribe @ webpack-internal:///../../../../rxjs/_esm5/Observable.js:163
(anonymous) @ webpack-internal:///../../../../rxjs/_esm5/Observable.js:292
ZoneAwarePromise @ webpack-internal:///../../../../zone.js/dist/zone.js:776
Observable.toPromise @ webpack-internal:///../../../../rxjs/_esm5/Observable.js:290
ApiService.request @ webpack-internal:///../../../../../src/app/shared/api.service.ts:44
(anonymous) @ webpack-internal:///../../../../../src/app/shared/api.service.ts:33
CartService.loadCartItems @ webpack-internal:///../../../../../src/app/elections/benefits/cart.service.ts:30
CartService @ webpack-internal:///../../../../../src/app/elections/benefits/cart.service.ts:26
_createClass @ webpack-internal:///../../../core/esm5/core.js:11116
_createProviderInstance$1 @ webpack-internal:///../../../core/esm5/core.js:11086
resolveNgModuleDep @ webpack-internal:///../../../core/esm5/core.js:11071
NgModuleRef_.get @ webpack-internal:///../../../core/esm5/core.js:12307
resolveDep @ webpack-internal:///../../../core/esm5/core.js:12805
createClass @ webpack-internal:///../../../core/esm5/core.js:12675
createDirectiveInstance @ webpack-internal:///../../../core/esm5/core.js:12512
createViewNodes @ webpack-internal:///../../../core/esm5/core.js:13973
callViewAction @ webpack-internal:///../../../core/esm5/core.js:14407
execComponentViewsAction @ webpack-internal:///../../../core/esm5/core.js:14316
createViewNodes @ webpack-internal:///../../../core/esm5/core.js:14001
createRootView @ webpack-internal:///../../../core/esm5/core.js:13862
callWithDebugContext @ webpack-internal:///../../../core/esm5/core.js:15287
debugCreateRootView @ webpack-internal:///../../../core/esm5/core.js:14570
ComponentFactory_.create @ webpack-internal:///../../../core/esm5/core.js:11457
ComponentFactoryBoundToModule.create @ webpack-internal:///../../../core/esm5/core.js:4228
ApplicationRef.bootstrap @ webpack-internal:///../../../core/esm5/core.js:6052
(anonymous) @ webpack-internal:///../../../core/esm5/core.js:5779
PlatformRef._moduleDoBootstrap @ webpack-internal:///../../../core/esm5/core.js:5779
(anonymous) @ webpack-internal:///../../../core/esm5/core.js:5700
ZoneDelegate.invoke @ webpack-internal:///../../../../zone.js/dist/zone.js:365
onInvoke @ webpack-internal:///../../../core/esm5/core.js:4950
ZoneDelegate.invoke @ webpack-internal:///../../../../zone.js/dist/zone.js:364
Zone.run @ webpack-internal:///../../../../zone.js/dist/zone.js:125
(anonymous) @ webpack-internal:///../../../../zone.js/dist/zone.js:760
ZoneDelegate.invokeTask @ webpack-internal:///../../../../zone.js/dist/zone.js:398
onInvokeTask @ webpack-internal:///../../../core/esm5/core.js:4941
ZoneDelegate.invokeTask @ webpack-internal:///../../../../zone.js/dist/zone.js:397
Zone.runTask @ webpack-internal:///../../../../zone.js/dist/zone.js:165
drainMicroTaskQueue @ webpack-internal:///../../../../zone.js/dist/zone.js:593
ZoneTask.invoke @ webpack-internal:///../../../../zone.js/dist/zone.js:464

**Comment by rohitnarula7176** [comment]
@spottedmahn The log indicates that the error occurred in token received callback function. I am guessing you are trying to access the instance of userAgentApplication with the constructor variable instead of the "this" keyword. Can you share your callback code ?

**Comment by spottedmahn** [comment]
Hi @rohitnarula7176 - oh, my bad.  It's our code.  I'll dig in.  Thanks!
