### ISSUE TITLE
Cannot get access token in React app accessing protected .NET Core API with Azure B2C

### ISSUE THREAD

**Issue by andrewabril** [AzureAD/microsoft-authentication-library-for-js#2702]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [x] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
I'm having issues getting an access token from my React app, trying to access my own .NET Core 3.1 web API. I'm able to login fine and can access the user data, but when I try to get an access token, I get the below error continuously. Would appreciate any help or push in the right direction. Thank you!

> Uncaught (in promise) BrowserAuthError: silent_sso_error: Silent SSO could not be completed - insufficient information was provided. Please provide either a loginHint or sid.

Here's what I have:

 1. Set up React app registration (SPA w/ redirect to localhost:3000 using auth code flow)
 2. Set up .NET Core web api app registration (Web w/ redirect to localhost:44347)
 3. Created two scopes for the web api (read and write)
 4. Gave api permission to the spa to the web api scopes

.NET Core 3.1 Web API setup (ref: https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-protected-web-api-app-configuration):

 1. Startup ConfigureServices

```services.AddMicrosoftIdentityWebApiAuthentication(Configuration, "AzureAdB2C");```

 2. appsettings.json
```
    "AzureAdB2C": {
       "Instance": "https://{example}.b2clogin.com",
       "ClientId": "{web api Client ID}",
       "TenantId": "xxxxxxxxxxxx",
       "Audience": "https://{example}.onmicrosoft.com/api"
    }
```

React set up using "@azure/msal-browser": "^2.7.0" and "@azure/msal-react": "^1.0.0-alpha.0" (ref: https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-react):

 1. index.tsx
```
const configuration: Configuration = {
  auth: {
      clientId: '{SPA Client ID}',
      authority: 'https://{example}.b2clogin.com/{example}.onmicrosoft.com/B2C_1_SignUpIn',
      knownAuthorities: ['{example}.b2clogin.com'],
  },
  cache: {
      cacheLocation: 'localStorage', // This configures where your cache will be stored
      storeAuthStateInCookie: false // Set this to "true" to save cache in cookies
  }
};

```
```const pca = new PublicClientApplication(configuration);```
```
<MsalProvider instance={pca}>
   <App />
</MsalProvider>
```

 2. App.tsx
```
  useEffect(() => {
    if (error) {
        login(InteractionType.Popup);
    }
  }, [error, login]);
```
 3. Accessing the token code
```
const { instance, accounts, inProgress } = useMsal();

useEffect(() => {
        if (inProgress === 'none' && accounts.length > 0) {
            const request = {
                account: accounts[0],
                scopes: ["https://{example}.onmicrosoft.com/api/scope.read"]
            };
            // Retrieve an access token
            instance.acquireTokenSilent(request)
                .then(response => {
                    console.log('response', response);
                    if (response.accessToken) {
                        console.log('accessToken', response.accessToken);
                        return response.accessToken;
                    }
                    return null;
                })
                .catch(error => console.log('token error', error));
        }
    }, [inProgress, accounts, instance]);
```

**Comment by tnorling** [comment]
@andrewabril Can you try including the scopes in your login request? There's a known issue with B2C discussed [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2315) where B2C only issues refresh tokens that can be exchanged for the scopes used to obtain the RT. In this case it results both in a failed cache lookup for the access token (since this is the first time you're requesting it) and then a failed refresh (since the RT doesn't work for these scopes).

If you're using the `useMsalAuthentication` hook you can pass it a request that will be used on the login call.

**Comment by andrewabril** [comment]
Thank you! I was able to get the access token that way. Still trying to piece it together but at least I know I'm getting a token.

What would best practices be in terms of getting and using the token? I used the useMal() example (https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/hooks.md) with useEffect() to get the token, and it's getting called hundreds of times and continuously.

**Comment by aditya-m-shah** [comment]
I am facing the same the issue - calling acquireTokenSilent fails to resolve. It seems to dismounting the component causing an infinite loop

**Comment by tnorling** [comment]
@andrewabril This should be addressed in the newest version. Can you try to update to `@azure/msal-react@1.0.0-alpha.1` and let me know if that fixes it?

**Comment by andrewabril** [comment]
It looks like that did fix it - great.

One more thing if you don't mind so I can get this working end to end. I'm getting a CORS error that I didn't have before. I've tried adding specific origins (https://{sample}.onmicrosoft.com,https://{dample}.b2clogin.com,https://login.microsoftonline.com) to my allowed origins config and also allowing all origins with no effect. I've also tried adding Access-Control-Allow-Origin header as "*" in my Options method.

Is there something specific that needs to be done to get CORS to work witb B2C?

```
Access to XMLHttpRequest at 'http://localhost:5000/api/FixFlipAnalysis' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

Thanks again for all your help.

**Comment by tnorling** [comment]
@andrewabril Looks like this is happening when your app is calling your API which means this does not have to do with B2C. You may need to configure your API to respond to the OPTIONS request with the Access-Control-Allow-Origin header set and possibly others.

You can read more about CORS [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)

**Comment by andrewabril** [comment]
I don't think the error is entirely accurate. I set up CORS before adding any authentication/authorization into the api and haven't had any issues. I have it allowed to certain sites (localhost and a sentry endpoint), but it breaks after I add auth with b2c.

I will look into it a bit more, but because it only occurs when I add the auth piece to the api, I'm leaning toward it being related to auth/b2c.

**Comment by tnorling** [comment]
@andrewabril You should be able to see which network request is failing the OPTIONS request in your network tab. If it's failing on any of the b2c endpoints take a look at your app registration and double check your redirectUri is configured as type SPA. If it's failing on your own API then it's most likely related to any new headers you are adding to your request.

**Comment by andrewabril** [comment]
The CORS issue I was facing was due to incorrect Configuration middleware order. I was calling app.UseCors() after routing and authentication/authorization. Calling that beforehand resolved the CORS issue. 

I also used this reference to make sure my ConfigurationServices was correct, https://github.com/AzureAD/microsoft-identity-web/wiki/web-apis.

ConfigurationServices auth set up using Microsoft.Identity.Web
```services.AddMicrosoftIdentityWebApiAuthentication(Configuration, "AzureAdB2C");```

appsetting.json
```
"AzureAdB2C": {
    "Instance": "https://{tenant name}.b2clogin.com",
    "ClientId": "xyz123",
    "TenantId": "abc123",
    "Domain": "{tenant name}.onmicrosoft.com",
    "SignUpSignInPolicyId": "b2c_1_signupin",
    "ResetPasswordPolicyId": "b2c_1_passwordreset"
  }
```

Thanks for all your help!
