### ISSUE TITLE
Error launching app  ElectronTestApp (msal-node-samples)

### ISSUE THREAD

**Issue by Ladvace** [AzureAD/microsoft-authentication-library-for-js#2714]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `@azure/msal-node@1.0.0-beta.2`

## Framework
react with electron

## Description
I'm using  https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/standalone-samples/ElectronTestApp, it works fine until i try to login (actually I can login) but I get the following error
https://imgur.com/a/9n1SUg0

**Comment by hectormmg** [comment]
Hi @Ladvace, can you provide any more information so we can try to replicate this? Please share your logs as well as your MSAL config.

**Comment by Ladvace** [comment]
Actually I solved, I setted the wrong protocol
