### ISSUE TITLE
MSAL useAccount and acquireTokenSilent will trigger infinite loop if used in React effect

### ISSUE THREAD

**Issue by jgbrands** [AzureAD/microsoft-authentication-library-for-js#2719]
>> Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.7.0`
- [ ] `@azure/msal-node@1.x.x`
- [x] `@azure/msal-react@1.0.0-alpha.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

**Important**: Please fill in your exact version number above, e.g. `msal@1.1.3`.

## Framework
React

## Description
I am building a React application with an ASP.NET Core API backend, so far this is going quite well. To protect my API, I am using Azure AD B2C and thus I am using MSAL to implement login/logout/etc behaviour in my client.

My application makes use of ASP.NET Core SignalR and for that, I need to provide an access token to authenticate the user, so that they may access authorized methods on the server. The problem is that I cannot acquire an access token in a sane manner because `acquireTokenSilent` touches the account state.

When you do this, the client will lock up and eventually crash the browser as it'll get stuck in an endless loop. However, if you remove the dependency on account, then the effect will only occur on the first load of the component and the account will be set to `null`, which makes it impossible to get an access token.

Unless I am missing something really obvious here, this makes MSAL practically unusable in effects.

## Reproduction steps
```ts
        const {instance, accounts, inProgress} = useMsal();
        const account = useAccount(accounts[0] || {});

        React.useEffect(() => {
            if (account) {
                instance.acquireTokenSilent({...loginRequest, account})
                    .then({
                        // do something with the access token here
                    })
                    .finally(() => setDone(true));
            }
        }, [account]);
```
## Expected behavior

`acquireTokenSilent` should not touch MSAL `accounts` state.

**Comment by tnorling** [comment]
@jgbrands Can you please update to `msal-react@1.0.0-alpha.1` and see if that solves your issue? That version contains a fix for this particular issue.

**Comment by jgbrands** [comment]
Thank you, that works. My apologies for not trying to update first, I wish NPM was better at informing you of updates.
