### ISSUE TITLE
Microsoft account is experiencing technical problems. Please try again later.

### ISSUE THREAD

**Issue by ak99372** [AzureAD/microsoft-authentication-library-for-js#272]
I tried both VanillaJSTestApp and ModuleSample examples but after I type in the account in the popup and press [Sign-In] I get:

> We're unable to complete your request
> Microsoft account is experiencing technical problems. Please try again later.

The popup url becomes:

`https://login.live.com/err.srf?lc=1033#error=invalid_request&error_description=The+provided+value+for+the+input+parameter+'redirect_uri'+is+not+valid.+The+expected+value+is+'https://login.live.com/oauth20_desktop.srf'+or+a+URL+which+matches+the+redirect+URI+registered+for+this+client+application.&state=262d52d8-3843-42bd-9336-3ec3c6d8ca37`

Meaning that the [redirect_uri] was not provided which looking at the code is true.

(Note: trying to put in https://login.live.com/oauth20_desktop.srf as [redirectUri] goes through the login process but at the end popup goes blank and hangs, [authCallback] never gets called)

**Comment by Adrianotiger** [comment]
I have this same response when I try to pack a PWA in an APPX and download the app from the store.

I don't use a popup but a redirect. Works as PWA on each browser and as PWA on Android but when I start it as App in Windows 10 I get this message after I insert my email address.

Can't say what is the url, as the App doesn't show it and I am not able to return to the webpage once I get this error.

**Comment by navyasric** [comment]
@ak99372  Are you still facing this issue? The redirectURI should be the same one registered in your app as a the redirect URI. It is usually your apps URL.

**Comment by navyasric** [comment]
@Adrianotiger MSAL.js is designed to be used in browser based SPA apps and does not support the native capabilities required for platforms such as Android.

**Comment by nehaagrawal** [comment]
@ak99372 is this still an issue? It looks like the redirect uri you are using is not registered for your client application. Please register the redirect uri on  app registration portal at https://apps.dev.microsoft.com/ and try again.
