### ISSUE TITLE
B2C Refresh tokens lifetime custom policy 

### ISSUE THREAD

**Issue by Sharatmenon** [AzureAD/microsoft-authentication-library-for-js#2722]
## Library
- [ ] `@azure/msal-browser@2.6.0`

## Description
As per documentation, the max life for a refresh token with a spa using PKCE is 24hrs. 

**Two questions :** 

1. Can I reduce that refresh token lifetime secs to 10 hrs  using the below ?

  **Config in my relying party file** 
     
`   <Metadata>
          <Item Key="token_lifetime_secs">3600</Item>
          <Item Key="id_token_lifetime_secs">3600</Item>
          <Item Key="refresh_token_lifetime_secs">1209600</Item>
          <Item Key="rolling_refresh_token_lifetime_secs">7776000</Item>
          <Item Key="IssuanceClaimPattern">AuthorityAndTenantGuid</Item>
          <Item Key="AuthenticationContextReferenceClaimPattern">None</Item>
        </Metadata>`

2. We want provide the user with an option to extend their session when the refresh token is about to expire. I am thinking of putting in a timer maintained in the app which will help us alert the user and once they confirm we will send the domain hint in a silent request to renew the refresh token. 
Does this sound doable ?

**Comment by tnorling** [comment]
@Sharatmenon We can't help you with custom policy config questions as that is a service level question. You can, however, open a support ticket [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options) and they should be able to help you get set up.

For the 2nd question, `acquireTokenSilent` will automatically call `ssoSilent` under the hood when the RT is expired. You should not need to track or manage the user's session yourself.

**Comment by Sharatmenon** [comment]
Hi @tnorling  - For the 2nd question, I understand that it will automatically call SSoSilent. But in our use case we don't have access to retrieve a email/login hint once the refresh token expires as that is used to get access tokens for api calls. We don't have email/login hint as part of the id token as it is PII.

So we were planning to make a call just before the refresh token window expires, does this seem doable ?

**Comment by tnorling** [comment]
@Sharatmenon msal-browser does not expose the refresh token for you to use. What I would suggest in this case is to simply wait for `acquireTokenSilent` to fail and then call one of the interactive methods to renew your tokens. Without a login_hint your user may be asked to select their account again and/or enter credentials.
