### ISSUE TITLE
Is user expected to be SSOed even after logout (Connected to Windows Account)

### ISSUE THREAD

**Issue by rhnsharma999** [AzureAD/microsoft-authentication-library-for-js#2725]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library
- [x] `@azure/msal-browser@2.x.x`
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
I am not sure if this is related to MSAL specifically.

So if I have a `Connected to Windows` account 
![image](https://user-images.githubusercontent.com/12526148/101669354-cd035900-3a77-11eb-81b3-9fc1d1b0b66b.png)

Do I expect to get SSOed every time I login (even after logging out)? This is under the assumption that the default auth flow tries SSO first, and has access to the user's upn information. 

I have seen this behavior with our implementation. We don't have any issues with logout (AAD accounts), and I can see the single sign out being triggered on outlook.office.com confirming the same. 

Do we need to explicitly disable SSO if a user logs out?

**Comment by tnorling** [comment]
@rhnsharma999 Yes, this is expected behavior when using [Browser SSO](https://docs.microsoft.com/en-us/azure/active-directory/devices/concept-primary-refresh-token#browser-sso-using-prt).

@hpsin Can you provide more context?

**Comment by hpsin** [comment]
That's correct - the user stays signed in the OS, but not "active" when they sign out, so they'll have to click on their tile again to sign in with that account in the future.  We can pull in the team that owns this if there are further questions.

**Comment by rhnsharma999** [comment]
Just to clarify, you mean that if a user logs out, and if then we attempt a `ssoSilent` call, we should get `InteractionRequiredAuthError` because the user needs to click his tile? Is this understanding correct?

(We are not seeing the above mentioned behavior)

**Comment by RavennMSFT** [comment]
@rhnsharma999 in this example above, are you closing the browser or opening a new tab in that same session

**Comment by rhnsharma999** [comment]
We have the `postLogoutRedirectUri` set to the landing page of our app, where the user can trigger the auth flow again. 
So it would be the same tab.

Though I see similar behavior even when I close the browser (different session).

**Comment by RavennMSFT** [comment]
Silent SSO after closing the browser is expected. If you are in the same session and you decided to explicitly sign out, the browser wont do silent logon, it will ask for credentials.

**Comment by rhnsharma999** [comment]
with MSAL we see that `ssoSilent` succeeds, even in the same session after logout
There is no issue with logout (specifically for AAD)
