### ISSUE TITLE
Hash does not contain state error in Office addins

### ISSUE THREAD

**Issue by streamcode9** [AzureAD/microsoft-authentication-library-for-js#2726]
## Library
- [x] `msal@1.4.4`

## Description

Hi!

I am getting `AuthError: Unexpected error in authentication.: Hash does not contain state.` error after requesting access token with `acquireTokenRedirect`. I've checked FAQ `If state is not included in the request, verify the request was built by msal`, but I am not sure how to verify it as my code is pretty simple.

```js
const isCallback = window.location.hash.length !== 0;
let userAgentApplication = new UserAgentApplication({
  auth: {
    authority, clientId, navigateToLoginRequestUrl: false, postLogoutRedirectUri: x, redirectUri: x, validateAuthority: true,
  },
  system: { loadFrameTimeout: 10000, },
  cache: { cacheLocation: 'localStorage', storeAuthStateInCookie: true, },
});
userAgentApplication.handleRedirectCallback(authRedirectCallBack);
if (!isCallback) userAgentApplication.loginRedirect(tokenRequest);

const authRedirectCallBack = callback => (error, response) => {
  if (error) { } else {
    if (response.tokenType === 'id_token' && userAgentApplication.getAccount() && !userAgentApplication.isCallback(window.location.hash)) {
      userAgentApplication.acquireTokenRedirect(tokenRequest);
    } else if (response.tokenType === 'access_token') { }
    else { }
  }
}
```

## Source

- [x] Customer request

**Comment by tnorling** [comment]
@streamcode9 Can you take a look at the network tab in the dev tools for your browser and find the /authorize request? Take a look and see if `state` is included in the query string

**Comment by streamcode9** [comment]
Hi @tnorling! Thank you for your help! I have found the issue but do not know how to interpret it.

I have enabled logs in msal. After `loginRedeirect` is fired and return the **id token**, `acquireTokenHelper` function is navigating to `https://login.microsoftonline.com/<guid>/oauth2/v2.0/authorize` with the next params
```
?response_type=id_token token
&scope=<scopes>
&client_id=<guid>
&redirect_uri=<my url>
&state=<some state>
&nonce=<guid>
&client_info=1
&x-client-SKU=MSAL.JS
&x-client-Ver=1.4.4
&login_hint=<my email>
&client-request-id=<guid>
&response_mode=fragment
```

And then flows are different depends on where my page is hosted:

a) my page (hosted by desktop outlook add-in) is called (by login.microsoftonline.com I guess) I see next parameters in hash:
```
#access_token=
&token_type=Bearer
&expires_in=3599
&scope=<scopes>
&id_token=<some token>
```

b) my page (hosted by web outlook add-in) is called (by login.microsoftonline.com I guess) I see next parameters in hash:
```
#access_token=
&token_type=Bearer
&expires_in=3599
&scope=<scopes>
&id_token=<some token>
&client_info
&state
&session_state
```

Do you have an idea at what stage `&client_info&state&session_state` parameters could be missed? I can't track network activity of outlook desktop (fiddler blocks outlook request and make it stop and wireshark shows encrypted traffic that is useless).

**Comment by tnorling** [comment]
@streamcode9 This sounds like the same problem as #2733. Can you try upgrading to `msal-browser@2.8.0`?

**Comment by streamcode9** [comment]
@tnorling yep. Looks like the same problem. Thanks for pointing!

I've upgraded to `msal-browser@2.8.0` and now it does not work in web outlook (did not check outlook desktop). I get `X-Frame-Option DENY error` when running `loginRedirect` method. Not sure whether other your [comment](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1161#issuecomment-657676371) relates to my case as I do not use B2C. Do you think I can do anything to fix it or outlook add-in has too many restrictions and limitations to be used together with msal lib?

**Comment by jasonnutter** [comment]
@streamcode9 I have put up a PR to the Office Addins sample repo demonstrating how to use MSAL.js v2: https://github.com/jasonnutter/PnP-OfficeAddins/tree/upgrade-msal/Samples/auth/Office-Add-in-Microsoft-Graph-React

Please take a look at this sample and let us know if you still run into issues. Be sure you are running `loginRedirect` inside the dialog window created by [displayDialogAsync](https://github.com/jasonnutter/PnP-OfficeAddins/blob/ba9887a4e4142b87a08ccc6c15e8faaf5c47da95/Samples/auth/Office-Add-in-Microsoft-Graph-React/utilities/office-apis-helpers.ts#L43) function.

**Comment by oleksandr-slys** [comment]
@jasonnutter I was not able to make it work with `displayDialogAsync`. I am getting `undefined object does not have replace function` error when call `loginRedirect`. Debugging outlook add-in on desktop is a bit painful as it is still Edge based on Chakra and not Chromium.  `displayDialogAsync` make things even more complicated. DevTools crashes randomly and often I do not see error line number.

I also can't use `loginRedirect` or `displayDialogAsync` in OWA because I am getting iframe related errors.

But I was able to get `idToken` and `accessToken` using different approaches in OWA and Desktop.
* `loginPopup -> acquireTokenPopup` in OWA
* `loginRedirect -> acquireTokenRedirect` in Desktop (I do redirect to the same page and use localStorage to store state of redirects)

Thank you once again @jasonnutter and @tnorling!

**Comment by jasonnutter** [comment]
@oleksandr-slys Was that with your code or with the sample I linked to? And which version of MSAL.js are you using?

**Comment by oleksandr-slys** [comment]
@jasonnutter I have struggled to all requirements in `Prerequisites`. To make it simple I took your code in `login.html` and `login.js` and opened it via `displayDialogAsync`.

I am using ` azure/msal-browser 2.8.0`.

**Comment by jasonnutter** [comment]
@oleksandr-slys Is the iframe-related errors you are getting the `redirect_in_iframe` error? If so, are you setting the [`displayInIframe`](https://docs.microsoft.com/en-us/javascript/api/office/office.dialogoptions?view=excel-js-preview#displayInIframe) flag for `displayDialogAsync` to true? Also note, in MSAL Browser 2.8.0 you can set `system.allowRedirectInIframe` to `true` to mitigate the `redirect_in_iframe` error.

**Comment by oleksandr-slys** [comment]
@jasonnutter 
>  Is the iframe-related errors you are getting a redirect_in_iframe error? 

Yes, this error is throws when I use redirect flow in OWA. Setting `allowRedirectInIframe` to `true` has fixed the issue. Thanks!

> If so, are you setting the displayInIframe flag for displayDialogAsync to true?

Yes. But the `displayDialogAsync ` still does not work and throws some exceptions when `login.html` send message to parent window.

I think redirect flow with the same windows is the most robust solution for me so far.

**Comment by oleksandr-slys** [comment]
@jasonnutter should I do more testing with `displayDialogAsync` and create another *question* card if I face with the issues?

**Comment by jasonnutter** [comment]
> Yes. But the displayDialogAsync still does not work and throws some exceptions when login.html send message to parent window.

Which errors are thrown? And do they happen if `displayInIframe` is set to `false`?

**Comment by oleksandr-slys** [comment]
@jasonnutter `Office.context.ui.messageParent` sends messages not only back to the add-in but also to `login.microsoft` and other domains. And they throw `cross-origin` or similar error. So I think it is expected and do not prevent add-in work. Fake alarm.
