### ISSUE TITLE
CORS Issue

### ISSUE THREAD

**Issue by grtn316** [AzureAD/microsoft-authentication-library-for-js#273]
In IE11 I am getting the following error when attempting authentication:

SEC7118: XMLHttpRequest for https://login.microsoftonline.com/tfp/xyz.onmicrosoft.com/b2c_1_siupin/v2.0/.well-known/openid-configuration required Cross Origin Resource Sharing (CORS).
File: www.xzy.com

Is there a trick to fix this?

**Comment by spottedmahn** [comment]
But it works in other browsers?  Have you [customized the UI](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-reference-ui-customization)?

**Comment by rohitnarula7176** [comment]
@grtn316 Closing this issue due to lack of information. Please reopen if you still face any issue. @spottedmahn Thank you for your help in understanding the issue.
