### ISSUE TITLE
loginPopup opens offscreen in Chrome and Edge on second display

### ISSUE THREAD

**Issue by dangrussell** [AzureAD/microsoft-authentication-library-for-js#2730]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.1.1`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [x] Angular
- [ ] React
- [ ] Other

## Description
When browser is on a second display, loginPopup opens mostly offscreen or entirely offscreen in Chrome and Edge. Does not happen in Firefox.

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps

```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Identity Provider

- [ ] Azure AD
- [x] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [x] Chrome
- [ ] Firefox
- [x] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by tnorling** [comment]
@dangrussell We'll look at reproducing this but in the meantime it would be helpful if you could provide a screenshot or video showing this behavior.

**Comment by dangrussell** [comment]
I can't find a good way to screen record across two screens, so here's some series of screenshots.

Each series is the same:

1. Browser on primary screen (right)
2, Browser on primary screen (right) after triggering popup
3. Browser on secondary screen (left)
3. Browser on secondary screen (left) after triggering popup

### Chrome
![Screenshot (7)](https://user-images.githubusercontent.com/4387475/101827963-f3200c00-3afe-11eb-82b6-342ea5ebeb85.png)
![Screenshot (8)](https://user-images.githubusercontent.com/4387475/101827971-f6b39300-3afe-11eb-878b-1005a992ed80.png)
![Screenshot (9)](https://user-images.githubusercontent.com/4387475/101828150-2b274f00-3aff-11eb-8f79-4de50addacbc.png)
![Screenshot (10)](https://user-images.githubusercontent.com/4387475/101828160-2e223f80-3aff-11eb-9629-f1d431bf9f92.png)

### Edge
![Screenshot (11)](https://user-images.githubusercontent.com/4387475/101828188-35494d80-3aff-11eb-9ea9-4ebae0812920.png)
![Screenshot (12)](https://user-images.githubusercontent.com/4387475/101828193-38443e00-3aff-11eb-9c2e-4a31050841d3.png)
![Screenshot (13)](https://user-images.githubusercontent.com/4387475/101828203-3aa69800-3aff-11eb-838c-f04e075c3ff7.png)
![Screenshot (14)](https://user-images.githubusercontent.com/4387475/101828213-3da18880-3aff-11eb-852a-d8ecf97b4d6e.png)

### Firefox (no issue)
![Screenshot (15)](https://user-images.githubusercontent.com/4387475/101828286-54e07600-3aff-11eb-8654-2e70d8a9986c.png)
![Screenshot (16)](https://user-images.githubusercontent.com/4387475/101828307-5b6eed80-3aff-11eb-9458-6c0b9ba1b2e4.png)
![Screenshot (17)](https://user-images.githubusercontent.com/4387475/101828313-5e69de00-3aff-11eb-8ebd-21d24c8ec9b3.png)
![Screenshot (18)](https://user-images.githubusercontent.com/4387475/101828322-6164ce80-3aff-11eb-8c94-2408bc7d8430.png)

**Comment by tnorling** [comment]
@dangrussell I was not able to reproduce this in either Edge or Chrome. Is your app running in an iframe? We've heard about some odd behaviors with popups when being opened from iframes.

In any event, this is likely not something we will fix in version 1 unless this also occurs in version 2 and the fix can be easily ported over. Have you tried upgrading to `msal-angular@2.0.0`?

**Comment by dangrussell** [comment]
`msal-angular@2.0.0` is still in alpha, right?

**Comment by tnorling** [comment]
@dangrussell Yes, we expect to go to beta in January and then GA shortly thereafter.
