### ISSUE TITLE
Refused to display in a frame because it set 'X-Frame-Options' to 'deny'

### ISSUE THREAD

**Issue by navinna** [AzureAD/microsoft-authentication-library-for-js#2731]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [x] Angular
- [ ] React
- [ ] Other

## Description
We have integrated Azure AD B2C with Angular application using MSAL, now we are running into an issue, whenever token expiring and trying to renew, we are facing this issue Refused to display in a frame because it set 'X-Frame-Options' to 'deny' in chrome browser
## Error Message

Refused to display in a frame because it set 'X-Frame-Options' to 'deny'

## MSAL Configuration

```js
const msalConfig: Configuration = {
  auth: {
    clientId: `XXX-Client-ID-XXX`,
    authority: `XXX-Authority-XXX`,
    validateAuthority: false,
    redirectUri: `http://localhost:4200`,
  },
  cache: {
    cacheLocation: 'localStorage', // This configures where your cache will be stored
    storeAuthStateInCookie: isIE,
  },
  system: {
    loadFrameTimeout: 30000
  }
};
@NgModule({
imports: [
MsalModule.forRoot(msalConfig, {
      popUp: isIE,
      consentScopes: [
        'openid',
      ],
      unprotectedResources: [],
      protectedResourceMap: [
        [environment.API, environment.SCOPES]
      ],
      extraQueryParameters: {}
    }),
],
providers: [
    MsalService,
    {
      provide: HTTP_INTERCEPTORS,
      useClass: MsalInterceptor,
      multi: true
    }
]
})


// There is no separate login redirect page, all the routes are protected with MsalGuard

```

## Reproduction steps

In our application azure configuration, accessToken lifetime is set to 60 minutes, once accessToken expires when we are trying to request an authorized API endpoint, the browser screen becomes blank and in the console, we could see the **Refused to display in a frame because it set 'X-Frame-Options' to 'deny'**.

## Expected behavior

Token renewed and application behaves normally

## Identity Provider

- [ ] Azure AD
- [x] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [x] Chrome
- [ ] Firefox
- [x] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [x] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by tnorling** [comment]
@navinna Please see the docs on this error [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/docs/errors.md#refused-to-display--in-a-frame-because-it-set-x-frame-options-to-deny)

**Comment by navinna** [comment]
@tnorling 

In order to give a smooth user experience, we couldn't display the popup to renew the token, also we don't want to redirect the user to get the token, is there any other option to achieve this?

**Comment by tnorling** [comment]
@navinna What did you determine was the cause of this error in your scenario? Was it multiple accounts signed in?

**Comment by navinna** [comment]
@tnorling 

No, there is only one account signed in, I couldn't confirm the cause of this issue in my application.

After reading the doc you mentioned above, I came to know this is the expected behavior. Here my concern is I cannot use the `acquireTokenPopup()`, can we restrict the redirection when using `acquireTokenRedirect` to get the new token?

**Comment by tnorling** [comment]
@navinna What happens when you open the link from the error in a new tab? This is expected behavior in **some**, but not all, scenarios.

**Comment by navinna** [comment]
@tnorling I don't understand, may I know what is your recommendation, here is my problem

 - accessToken lifetime is set to 60 minutes, once accessToken expires, when we are trying to request an authorized API endpoint, we could see X-Frames-Options to deny.
 - after a min or two I could see in the console, token renewal operation failed due to timeout .

in this scenario I am not using acquireTokenSilent() to renew the token.

**Comment by tnorling** [comment]
> in this scenario I am not using acquireTokenSilent() to renew the token.

@navinna how are you getting the access token?

Please open the link from the X-Frame options deny error in a new tab and observe what is happening. If it shows an error or is expecting any sort of interaction that is why this error is being thrown.

You can also try upgrading to [msal-angular v2](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-angular) where we do not expect this error to occur as frequently

**Comment by navinna** [comment]
@tnorling 

We cannot use v2 since it's under development and not ready for production.

I opened the error in the new tab and I could see the same error in the console, but I would like to know is there any solution or workaround for this issue.

**Comment by tnorling** [comment]
@navinna X-Frame-Options Deny means that the service does not allow the page to be rendered in an iframe. There are many reasons why this would not be allowed and the solution depends on your particular scenario. When you open the error url in a new tab you should see the page that was trying to be rendered in the hidden iframe. Can you clarify do you see a login page or your app when you open the url?
