### ISSUE TITLE
Is Edge WebView limiting redirect URL to 4095 characters?

### ISSUE THREAD

**Issue by nachoargentina** [AzureAD/microsoft-authentication-library-for-js#2733]
## Library

- [x] `msal@1.4.4` or `@azure/msal@1.4.4`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
   
We have implemented an Outlook Add-In and currently have an authentication issue that ONLY happens in Outlook Desktop application.

We are using an auth flow as described in your docs, very straight forward.

As you access the app, we call `acquireTokenSilent`. If that fails, we show the user a page asking them to click on a link to give the Add-In permissions.

When they click, we call `Office.context.ui.displayDialogAsync` with the URL of a separate page we have setup to handle authorization.

This page is also very straight-forward.

1. It registers an auth callback through `userAgentApp.handleRedirectCallback(authCallback);`, 
2. Then it runs `userAgentApp.acquireTokenSilent(request)` to check whether you are already authorized (in this case, since it's your first time going into the page, it will fail)
3. Once it fails, it will call `acquireTokenRedirect(request)` (is the same request object we use for the `acquireTokenSilent` call)
4. After calling `acquireTokenRedirect(request)` it will prompt you to give all permissions MS is asking. Once you accept, it redirects back to the original page.

**The expected behaviour** is that, after being redirected, the `acquireTokenSilent` will run succesful this time and the dialog will be closed.

**This works totally fine in Web Outlook and Outlook on the Web (Office 365 web version).**

However, when you try to run this on the Outlook Desktop app, the dialog never gets to close after being redirected. Upon inspection using Edge DevTools Preview, we can see the following error.

`SCRIPT5022: SCRIPT5022: Invalid state. eyJpZCI6IjllYTY1MWNiLWFmNWYtNDI1Ny05Njk4LTI2MjczNjgxZGM4OSIsInRzIjoxNjA3Nj, state expected : null.`

When inspecting the URL params, the state param is set as `state=eyJpZCI6IjllYTY1MWNiLWFmNWYtNDI1Ny05Njk4LTI2MjczNjgxZGM4OSIsInRzIjoxNjA3Nj`

This is wrong as it's an incomplete param.
If I go to the local storage, I can see in the `msal.redirect_request` property that the value should be `eyJpZCI6IjllYTY1MWNiLWFmNWYtNDI1Ny05Njk4LTI2MjczNjgxZGM4OSIsInRzIjoxNjA3NjIwMjE4LCJtZXRob2QiOiJyZWRpcmVjdEludGVyYWN0aW9uIn0=`

So, why is the state value not complete in the URL?

Checking the character count on the whole URL, **it seems that is being limited to 4095 characters**. Everything beyond that is not being recognized by the Outlook Desktop App internal browser.

For reference, this is the full redirect URL as MS Authentication page redirects (Some parts are masked with XXXX just in case):

`https://law.cosmolex.com/outlook/login-msal.html#access_token=eyJ0eXAiOiJKV1QiLCJub25jZSI6IlE2UllRRWR3TVFVSTdxbE5ueDAXXXXXXXXXXXXXXXXXXFNweThrVll5aTQiLCJhbGciOiJSUzI1NiIsIng1dCI6ImtnMkxZczJUMENUaklmajRydDZKSXluZW4zOCIsImtpZCI6ImtnMkxZczJUMENUaklmajRydDZKSXluZW4zOCJ9.eyJhdWQiOXXXXXXXXXXXXXXXXXXwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9lNmUzMDhiOC1hNTM4LXXXXXXXXXXXXXXXXXXwOGJhNTNjNmUvIiwiaWF0IjoxNjA3NjIwMTEyLCJuYmYiOjE2MDc2MjAxMTIsImV4cCI6MTYwNzYyNDAxMiwiYWNjdCI6MCwiYWNyIjoiMSIsImFjcnMiOlsidXJuOnVzZXI6cmVnaXN0ZXJzZWN1cml0eWluZm8iLCJ1cm46bWljcm9zb2Z0OnJlcTEiLCJ1cm46bWljcm9zbXXXXXXXXXXXXXXXXXX6bWljcm9zb2Z0OnJlcTMiLCJjMSIsImMyIiwiYzMiLCJjNCIsImM1IiwiYzYiLCJjNyIsImM4IiwiYzkiLCJjMTAiLCJjMTEiLCJjMTIiLCJjMTMiLCJjMTQiLCJjMTUiLCJjMTYiLCJjMTciLCJjMTgiLCJjMTkiLCJjMjAiLCJjMjEiLCJjMjIiLCJjMjMiLCJjMjQiLCJjMjUiXSwiYWlvIjoiRTJSZ1lKQ1ozTEhtUkU5d21tRkkyS3IrQXVXWnB1d1AreXY2aSs1c2MxMHdlV240b2EwQSIsImFtciI6WyJwd2QiLCJyc2EiXSwiYXBwX2Rpc3BsYXluYW1lIjoiQ29zbW9MZXggT3V0bG9vayBBZGQtaW4iLCJhcHBpZCI6IjZmMzYxMWUzLTMwNzEtNDQ5Ni1iYjMyLWUzMWIwM2QzNTVjOCIsImFwcGlkYWNyIjoiMCIsImRldmljZWlkIjoiYWIxOTdmZDktMDIzZi00Yjc4LTgzZDQtNDgyYTU1NGMzZTVjIiwiZmFtaWx5X25hbWUiOiJUZXN0IiwiZ2l2ZW5fbmFtZSI6IkNvc21vTGV4IiwiaWR0eXAiOiJ1c2VyIiwiaXBhZGRyIjoiMTkwLjEwNi45OCXXXXXXXXXXXXXXXXXXQ29zbW9MZXggVGVzdCIsIm9pZCI6IjYwMDUyYTM3LThkYzQtNGQ2ZS05ZGVlLTFlZWVlMjcxOGU5NyIsInBsYXRmIjoiMyIsInB1aWQiOiIxMDAzMjAwMEYyMkFDMDM1IiwicmgiOiIwLkFSc0F1QWpqNWppbFprLVhtbl9RaTZVOGJ1TVJObTl4TUpaRXV6TGpHd1BUVmNnYkFDSS4iLCJzY3AiOiJNYWlsLlJlYWRXcml0ZSBNYWlsLlNlbmQgb3BlbmlkIHByb2ZpbGUgVXNlci5SZWFkIGVtYWlsIiwic2lnbmluX3N0YXRlIjpbImttc2kiXSwic3ViIjoic3Y3UDN2c0hqanJveTFFRmFjdW1aY2lQTWE4YzZYY2hNMS1EMmxUejBTNCIsInRlbmFudF9yZWdpb25fc2NvcGUiOiJOQSIsInRpZCI6ImU2ZTMwOGI4LWE1MzgtNGY2Ni05NzlhLTdmZDA4YmE1M2M2ZSIsInVuaXF1ZV9uYW1lIjoiaWduYWNpb0Bjb3Ntb2xleC5vbm1pY3Jvc29mdC5jb20iLCJ1cG4iOiJpZ25hY2lvQGNvc21vbGV4Lm9ubWljcm9zb2Z0LmNvbSIsInV0aSI6Im5abnNmdlV4RVVpVUhHbEVFMDJLQUEiLCJ2ZXIiOiIxLjAiLCJ4bXNfc3QiOnsic3ViIjoiQlpuR2VqZ3UzRE1yNUMzcWVuckZBMVhnZFhjSHhOdmp6U00wSVMyR2dsNCJ9LCJ4bXNfdGNkdCI6MTQ3NjkwMjkxMX0.uaOQ7xWQo_5PmE_5rTlL95oqKBweCf_AxNxRIhWoH3Emyf1vQh-MEFGnYsLQt3rWC2A07dcpYyLphmVTwt2Q9YNdhWbC5mqozxjG1XnfwrTiyYaTh1TmwmS-5xAPzfxZboZKQpP3xp6e_P1i8y44D53Sfzv8r68YMBhtyMkOAsKZoo1g6_PVvmk8zM1I-jqLBZkqSFzSOy5zXGXIwyEo2I8KhoJsB6YwfFq8brArNe-M7aexS2hL5hvpnt7Z9iAe_4PrZWgTqqSmGpyNYUrsvYpisj8G8UYXY9zB_92GrCjC9lahESGo0XJL4AsOKtC821z9LPR1arTxJfjwftgxxw&token_type=Bearer&expires_in=3599&scope=Mail.ReadWrite+Mail.Send+openid+profile+User.Read+email&id_token=eyJ0eXAiOiJKV1QXXXXXXXXXXXXXXXXXXiIsImtpZCI6ImtnMkxZczJUMENUaklmajRydDZKSXluZW4zOCJ9.eyJhdWQiOiI2ZjM2MTFlMy0zMDcxLTQ0OTYtYmIzMi1lMzFiMDNkMzU1YzgiLCJpc3MiOiJodHRwczovL2xvZ2luLm1pY3JXXXXXXXXXXXXXXXXXX20vZTZlMzA4YjgtYTUzOC00ZjY2LTk3OWEtN2ZkMDhiYTUzYzZlL3YyLjAiLCJpYXQiOjE2MDc2MjAxMTIsIm5iZiI6MTYwNzYyMDExMiwiZXhwIjoxNjA3NjI0MDEyLCJhaW8iOiJBVVFBdS84UkFBQUFieWNhcURUc2VBWlRQWmV3WUlHNyt4ektpOVJqc3QxZWdvd1IvbjZoa21ybHgzdjR3QlRrZEtjdFpFd28xbmlBbTNxR3VtL294cyt6U3RxQ3pSRGs1dz09IiwiYXRfaGFzaCI6IkZwemxjRDRTZGlIT3BvWnNBemd3REEiLCJuYW1lIjoiQ29zbW9MZXggVGVzdCIsIm5vbmNlIjoiY2M2Njc5NjEtZmJmNS00MTg1LTkzYTUtZjQ4MTA5ZGVlNmI2Iiwib2lkIjoiNjAwNTJhMzctOGRjNC00ZDZlLTlkZWUtMWVlZWUyNzE4ZTk3IiwicHJlZmVycmVkX3VzZXJuYW1lIjoiaWduYWNpb0Bjb3Ntb2xleC5vbm1pY3Jvc29mdC5jb20iLCJyaCI6IjAuQVJzQXVBamo1amlsWmstWG1uX1FpNlU4YnVNUk5tOXhNSlpFdXpMakd3UFRWY2diQUNJLiIsInN1YiI6IkJabkdlamd1M0RNcjVDM3FlbnJGQTFYZ2RYY0h4TnZqelNNMElTMkdnbDQiLCJ0aWQiOiJlNmUzMDhiOC1hNTM4LTRmNjYtOTc5YS03ZmQwOGJhNTNjNmUiLCJ1dGkiOiXXXXXXXXXXXXXXXXXXR2xFRTAyS0FBIiwidmVyIjoiMi4wIn0.QxYKbCtsbF43CzTZhJHyjjXok8An4Rvn7N5DeyhPC5g-4arv28kQkg5sBxOIRLhePMp663E6A8gUAqSMUhkUcs8hetly8NWAFL8TjZAyx86QYsr4FahYsCnaSToKas_8KoKnI9SJRRPdzSIVT0KOpboJ4kFG1ADLJAwDwUm-1JuzHaCTgboQUmFDfiekEme9nrajzvj40Yc0JRsJlGRxfWMVdPMqjJsStnF8urFYcub4pO-XkqBAe4BGjXegkRpkBQaOJA8WyLDNlNBQykzF2fkyPPHtsNGAx55plWYi-IhCCTdL7OAd8FLhGDXGbREwikfF3gw82IMF4XRHLmXV0g&client_info=eyJ1aWQiOiI2MDA1MmEzNy04ZGM0LTRkNmUtOWRlZS0xZWVlZTI3MThlOTciLCJ1dGlkIjoiZTZlMzA4YjgtYTUzOC00ZjY2LTk3OWEtN2ZkMDhiYTUzYzZlIn0&state=eyJpZCI6IjllYTY1MWNiLWFmNWYtNDI1Ny05Njk4LTI2MjczNjgxZGM4OSIsInRzIjoxNjA3Nj`

**In both web versions, the URL is longer than 4095 chars and there is no problem whatsoever**. We've tested it in Safari, Chrome, Edge(chromium) and Firefox, so I'm wondering why are this long URLs a problem in the Outlook Desktop (which I understand uses Edge WebView) and how we can avoid this issue.

Any help will be greatly appreciated since this is blocking our Add-In approval.

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by tnorling** [comment]
@nachoargentina This is a known issue with `msal@1.x` when requesting both an access token and id token in the same request in the old Edge browser and IE11. Can you try upgrading to `msal-browser@2.8.0`? We do not expect this to be an issue with the new library.

[Migration Docs](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/v1-migration.md)

**Comment by nachoargentina** [comment]
Thank you **SO MUCH** for your answer. This has solved the problem that has been driving us crazy. I have migrated following your docs and the flow works now on Outlook Desktop App.

I do however still have an issue in Outlook Desktop for which we are getting our approval rejected.

In the web applications, both web Outlook and Outlook on the Web, everything works fine.

For Outlook Desktop however, once you authorize the app, it all works ok, but every time you close and open the add-in again, is asking you for authorization.

Basically, upon opening the add-in, we are calling `ssoSilent` to check if a user has already given permission. On this call we pass the same scopes always and a loginHint, which is the user Email Address.
This call to `ssoSilent` works just fine on all web versions. If the user has already given his authorization in the past, the call is successful and we proceed.

In Outlook for Desktop however, this call NEVER succeeds. It always comes back with an error that reads:

`InteractionnRequiredAuthError: interaction_required: Trace ID: <> Correlation ID: <> Timestamp: <>`

How come this work on web and not on desktop? can you help us figure out if we are missing something?

As a reference, here's our Config for MSAL:

```
const config: msal.Configuration = {
            auth: {
                clientId: `${process.env.REACT_APP_MS_GRAPH_CLIENT_ID}`,
                authority: 'https://login.microsoftonline.com/common',
                redirectUri: `${process.env.REACT_APP_BASE_URL}/login-msal.html`,
                navigateToLoginRequestUrl: false,
            },
            cache: {
                cacheLocation: 'localStorage', // needed to avoid "login required" error
                storeAuthStateInCookie: true, // recommended to avoid certain IE/Edge issues
            },
            system: {
                loggerOptions: {
                    loggerCallback: (level: LogLevel, message: string, containsPii: boolean): void => {
                        if (containsPii) {
                            return;
                        }
                        switch (level) {
                            case LogLevel.Error:
                                console.error(message);
                                return;
                            case LogLevel.Info:
                                console.info(message);
                                return;
                            case LogLevel.Verbose:
                                console.debug(message);
                                return;
                            case LogLevel.Warning:
                                console.warn(message);
                                return;
                        }
                    },
                    piiLoggingEnabled: false,
                },
                loadFrameTimeout: 10000
            }
        };
```

**Comment by nachoargentina** [comment]
@tnorling nevermind, I was able to get it to work by calling `acquireTokenSilent` instead of `ssoSilent`.

Anyway, now a new problem came up. Using MSAL 2.X, the `ImplicitMSALAuthenticationProvider` stop working. It complains that the PublicClientApplication doesn't have a `getAccount` method, which was present in the old `UserAgentApplication` from MSAL 1.X

Any workarounds from this? or am I stuck with creating my own custom authenticator?

Any help is greatly appreciated, thanks!

**Comment by nachoargentina** [comment]
@tnorling nevermind, I found this doc where is stated that the implicit flow is not supported!
https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-javascript-auth-code

**Comment by tnorling** [comment]
@nachoargentina Correct, Msal.js version 2 implements the Auth Code Flow instead of the Implicit Flow. Additionally `getAccount` was deprecated as version 2 now supports multiple accounts. You can call `getAllAccounts` or one of the account APIs listed in [this doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/accounts.md) instead.

**Comment by nachoargentina** [comment]
All seem to be good now, hopefuly we'll get our Add-In approved this time. Thanks for your support 🙏
