### ISSUE TITLE
Always received invalid_request: AADSTS65002: Consent between first party application '0bfc4568-a4ba-4c58-bd3e-5d3e76bd7fff' and first party resource '00000003-0000-0000-c000-000000000000' must be configured via preauthorization.

### ISSUE THREAD

**Issue by pritambaldota** [AzureAD/microsoft-authentication-library-for-js#2738]
Hi Team, 

I am workign on to upgrade from MSAL v1 to v2 and after logging when i am trying to acquire token silently, it always throws consent error. I have verified as our app id is being added to graph app as preauthorizied and with msal v1 it works fine. I am passing client id as scope to the slient request call.

**Comment by tnorling** [comment]
@pritambaldota MSAL.js v2 does not translate clientId to `openid` and `profile` as it did in v1. Can you try sending `scopes: ["openid", "profile"]` instead?

Also in the future please use one of the provided [issue templates](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/new/choose) when opening a new issue. Thanks!

**Comment by pritambaldota** [comment]
@tnorling  I tried sending these scopes which creates token but for wrong audience - i.e. **https://management.core.windows.net/** where as we are expecting our client id should be as audience as it is validated on server.

**Comment by tnorling** [comment]
@pritambaldota Could you raise this issue with the server team as this is not an issue with MSAL.js?

**Comment by tnorling** [comment]
Resolved offline. In msal.js < v1.4 when passing `clientId` as scope, msal will translate to `openid` and `profile` and request an id_token which is returned as both `idToken` and `accessToken`. In v2 `clientId` is no longer translated so to achieve the same behavior you had in v1, you must pass `openid` and `profile` as scopes and use the returned `idToken`
