### ISSUE TITLE
Intermittently receiving "endpoint_resolution_error" when using MSAL Browser with Azure B2C Authentication

### ISSUE THREAD

**Issue by devanshgoenka97** [AzureAD/microsoft-authentication-library-for-js#2739]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework
- [ ] Angular
- [x] React
- [ ] Other

## Description
We are currently using MSAL 2.x with Auth Code flow with an Azure B2C Custom Policy. Ever since last month, we are intermittently seeing an error whenever there is a cache miss in the server telemetry of the browser sessions. This happens across multiple IdPs and multiple browsers, and there has been no pattern that we have ascertained which causes this issue.

## Error Message
The session storage's server telemetry key defines the error as "endpoint_resolution_error". No message is present.

## MSAL Configuration

```js
const MsalObj = new PublicClientApplication({
  auth: {
    clientId: client_id,
    authority: authority ,
    knownAuthorities: [tenant],
    redirectUri: redirectURI,
    navigateToLoginRequestUrl: false,
    postLogoutRedirectUri: postLogoutRedirectUri,
  },
  cache: {
    cacheLocation: "sessionStorage",
    storeAuthStateInCookie: false,
  },
});

const loginRequest = {
  scopes: ["offline_access", "API scope"],
};
```
B2C Tenant : gtasourcingtest.b2clogin.com
B2C Custom Policy : B2C_1A_signup_signin_linkedin

## Identity Provider

- [ ] Azure AD
- [ ] Azure B2C Basic Policy
- [x] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [x] Chrome
- [x] Firefox
- [x] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Source

- [x] Internal (Microsoft)
- [ ] Customer request

**Comment by tnorling** [comment]
@devanshgoenka97 This can happen if the `openid-configuration` network call fails for your b2c tenant. It would be helpful if you could provide fiddler traces showing the network activity when this occurs. Is your app experiencing any failures due to this or are you just seeing the error in the cache?

**Comment by devanshgoenka97** [comment]
@tnorling Currently, the app is listening to a particular key in the session storage. Unfortunately, that key is being changed in the handleRedirectPromise() method, and due to this error, that method is not invoked, which results in a failure in the app. 

I will try to capture the network trace, but as mentioned, it is an intermittent issue so it might take a while.

**Comment by tnorling** [comment]
@devanshgoenka97 Can you clarify what cache key your app is listening to, what `handleRedirectPromise` is changing and what method is not being invoked?

**Comment by devanshgoenka97** [comment]
@tnorling, sorry for the lack of details earlier. We are setting a custom cache key to the session before the auth redirect (its called `authRedirectInProgress`) and in the `handleRedirectPromise` we are setting it to `false`. This is done to ensure our application (which automatically redirects to a `/login' route) does not make another call to `loginRedirect()` while the already redirected response is being parsed.

**Comment by tnorling** [comment]
Gotcha. Can you set the flag to `false` in the catch for both `handleRedirectPromise` and `loginRedirect` ? Once you're able to capture a network trace we can take a look to see why this error is happening.
