### ISSUE TITLE
When is msal-angular 2.0 scheduled for live release?

### ISSUE THREAD

**Issue by SaviChinnadurai** [AzureAD/microsoft-authentication-library-for-js#2753]
We are eagerly waiting for msal angular 2.0 live release to implement auth code flow in our SPA application.

Will be very helpful to know the release date for stable version.

**Comment by jasonnutter** [comment]
@SaviChinnadurai We are currently planning to have the public preview available next month, and general availability sometime not too long after that. We'll update our roadmap.

**Comment by SaviChinnadurai** [comment]
Great, Thanks jason.
