### ISSUE TITLE
PostLogoutUri redirection For MSA accounts doesn't work

### ISSUE THREAD

**Issue by sharmar999** [AzureAD/microsoft-authentication-library-for-js#2754]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [ ] Angular
- [ ] React
- [x] Other

## Description
We have an auth flow using MSAL supporting both MSA and AAD accounts. 
Our login, logout flows work correctly for AAD accounts
However for MSA accounts, the redirection to the postLogoutRedirectUri doesn't happen after logout. 

logout seems to be happening correctly as we see that the session has ended when logging in again. 

- We use the same postLogoutRedirect Uri for both type of accounts.
- I have tried replacing it with the redirect URI which is registered, same result. 
- I don't see any errors in the console. 

## MSAL Configuration
```js
{
    auth: {
      clientId: clientId, // from config
      authority: 'https://login.microsoftonline.com/common' ,
      redirectUri: <our-app>/auth/callback,  // is a valid registered callback URL.
      navigateToLoginRequestUrl : false
    },
    cache: {
      cacheLocation: 'localStorage',
      storeAuthStateInCookie: true,
    },
    system: {
      loggerOptions: {
        loggerCallback: (level, message, containsPii) => {
          if (containsPii) {
            return
          }
          switch (level) {
            case LogLevel.Error:
              console.error(message)
              return
            case LogLevel.Info:
              console.info(message)
              return
            case LogLevel.Verbose:
              console.debug(message)
              return
            case LogLevel.Warning:
              console.warn(message)
              return
          }
        },
      },
      windowHashTimeout: 30000,
      iframeHashTimeout: 30000,
    },
  }
```

## How we call it.
The instance of our class, lets say `AuthModule` holds an account object. 
During logout, we first clear the local storage and then call the logout function passing the postLogoutUri there. 

```js
localStorage && localStorage.clear()
const endSessionRequest: EndSessionRequest = {
      account: this.account,
      postLogoutRedirectUri
 }
this.myMSALObj.logout(endSessionRequest).catch(err => {})
```

## Additional Info
1. On logout we do see a redirection to following URL first 
```https://login.microsoftonline.com/common/oauth2/v2.0/logout?post_logout_redirect_uri=<our_app>&client-request-id=<client request id here>```
2. We get an account picker to select an account to sign out of. 
![image](https://user-images.githubusercontent.com/75980338/102101084-37d5db00-3e50-11eb-8a1d-94153bb9a04a.png)

3. Finally landing here and staying here.
![image](https://user-images.githubusercontent.com/75980338/102100540-8c2c8b00-3e4f-11eb-8bb1-c6d27429608a.png)

I am not sure what additional info I can provide which can be helpful. Let me know if anything else is needed.

## Reproduction steps

Login with an MSA account.
Logout.
Redirection doesn't happen.

## Browsers/Environment

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Source

- [x] Internal (Microsoft)
- [ ] Customer request

**Comment by tnorling** [comment]
@sharmar999 There's 3 things you need in order to have logout redirect back to your app:
1. Pass a `postLogoutRedirectUri` to `logout`
2. Register this url as a `redirectUri` on the app registration
3. Register this url as the Logout url on the app registration

Can you verify that all 3 of these things have been done in your case?

**Comment by sharmar999** [comment]
Apologies @tnorling 
Did not realize `3.` was a hard requirement as our legacy setup worked without it

Also is there a way we can skip the confirmation screen on logout. I mean the screen which says `Which account do you want to sign out of?`

**Comment by tnorling** [comment]
@sharmar999 With the newest version of msal-browser you can skip this, however, doing so means the user is not signed out from the server. If you don't go through this account selection screen and attempt to log back in, the server will automatically log you in without asking for credentials as your session remains active.

**Comment by sharmar999** [comment]
Got it
So I guess there is no way of *skipping it and also closing the session*.

Thank you for the help
