### ISSUE TITLE
How do I get Bearer (Access) Token in v2 format using MsalInterceptor?

### ISSUE THREAD

**Issue by conkman** [AzureAD/microsoft-authentication-library-for-js#2757]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x ] `@azure/msal-angular@1.1.1`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
How do I get Bearer (Access) Token in v2 format using MsalInterceptor?  My Azure AD App registration has the manifest updated to accept v2 tokens.

## Source

- [ ] Internal (Microsoft)
- [x] Customer request

**Comment by tnorling** [comment]
@conkman Can you confirm that you've set the `accessTokenAcceptedVersion` in your app manifest to 2? Please see [this doc](https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens#v10-and-v20) for more information. You can see our angular samples [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-samples) which show how to use the interceptor. 

Additionally, can you clarify what scopes you are using? Are you trying to access MS Graph or a custom scope?

**Comment by conkman** [comment]
@tnorling thanks for taking the time for me.  I have confirmed that our `accessTokenAcceptedVersion` in the manifest for our App Registration is set to 2.

Let me add a little more color to our current setup.  Currently we have one App Registration that is protecting our Dotnet Core Web Api backend and our angular front end client side application.  We are trying to get a Bearer token to call our backend API from the front end.

We currently do not have any scopes setup for the App Registration.  Is this required for us to be able to obtain an Access Token for our angular client side application.

**Comment by tnorling** [comment]
@conkman Yes, scopes are required to obtain an access token as that is what defines what the access token is for. You can read more about scopes in the [OAuth 2.0 spec](https://oauth.net/2/scope/#:~:text=Scope%20is%20a%20mechanism%20in%20OAuth%202.0%20to,application%20will%20be%20limited%20to%20the%20scopes%20granted.)

**Comment by digitalcraftco** [comment]
@conkman I'm battling through this too at the moment. I was able to get the **idToken** for the payload in app.component after login success. [https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/4d79b8ebacd7e4d9acf80fd69d602346dee6bf3c/samples/msal-angular-v2-samples/angular11-b2c-sample/src/app/app.component.ts#L44](url)
```
let payload: IdTokenClaims = <AuthenticationResult>result.payload;  
console.log('Token', payload.idToken);
```
Also was able to get accessTokens from the result of the handleRedirect method after login. In the home.component.
[https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/4d79b8ebacd7e4d9acf80fd69d602346dee6bf3c/samples/msal-angular-v2-samples/angular11-b2c-sample/src/app/home/home.component.ts#L14](url)
```
this.authService.handleRedirectObservable().subscribe({
      next: (result) => console.log(result),
      error: (error) => console.log(error)
    });
```
Which I can then use for custom interceptors etc. Other methods I have seen are to call acquireTokenSilent() with a SilentRequest object for different scopes and URI's. Still not sure of the best way or if this is even right.

**Comment by tnorling** [comment]
Closed due to inactivity. Please open a new issue if you have further questions. Thanks!
