### ISSUE TITLE
How to single sign out multiple angular apps.

### ISSUE THREAD

**Issue by ismail1971** [AzureAD/microsoft-authentication-library-for-js#2760]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

I am working on a portal app which has links to many sub apps. All the apps are using the same clientId for login. Using the following logout  
```js
logout() {
    this.authService.logout();
  }
```
Is not logout all apps.

Here is the config look like:

App 1 :
```js
function MSALConfigFactory(): Configuration {
  return {
    auth: {
       clientId: '469c-4ae9-8806-4687d35bc31e-23323',
    authority: 'https://login.microsoftonline.com/common',
    redirectUri: 'https://localhost:1023/',
    postLogoutRedirectUri: 'https://localhost:1023/'
    },
    cache: {
      cacheLocation: environment.cache.cacheLocation as CacheLocation,
      storeAuthStateInCookie: isIE, // set to true for IE 11
    },
  };
}
```

App 2:
```js
function MSALConfigFactory(): Configuration {
  return {
    auth: {
       clientId: '469c-4ae9-8806-4687d35bc31e-23323',
    authority: 'https://login.microsoftonline.com/common',
    redirectUri: 'https://localhost:1024/',
    postLogoutRedirectUri: 'https://localhost:1024/',
   
    },
    cache: {
      cacheLocation: environment.cache.cacheLocation as CacheLocation,
      storeAuthStateInCookie: isIE, // set to true for IE 11
    },
  };
}
```

same client for both apps clientId: '469c-4ae9-8806-4687d35bc31e-23323',

I want the user to be logout from both apps if he/she logout form either app 1 or app 2. 

Is it possible?

## Source

- [ ] Internal (Microsoft)
- [X] Customer request

**Comment by tnorling** [comment]
@ismail1971 You will need to use 2 different app registrations with 2 different clientIds and in each registration register a Logout Url that points to a logout page on each of your apps. This page should automatically call the msal logout api on page load.
