### ISSUE TITLE
Trying to look for errorCode for type AuthError but EventMessage is using EventError

### ISSUE THREAD

**Issue by shinkhouse** [AzureAD/microsoft-authentication-library-for-js#2761]
## Library

- [ ] `msal@^1.3.2` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.8.0`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [x] `@azure/msal-angular@^2.0.0-alpha.1`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [x] Angular
- [ ] React
- [ ] Other

## Description
When trying to see if i'm getting certain type of error, I'm getting this issue:
Property 'errorCode' does not exist on type 'EventError'.
  Property 'errorCode' does not exist on type 'Error'.
## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps

```js
// Provide relevant code snippets here.
this.msalBroadcastService.msalSubject$
            .pipe(
                tap((msg: EventMessage) => msg),
                takeUntil(this._destroying$)
            )
            .subscribe((result: EventMessage) => {
                if (result.eventType === EventType.LOGIN_SUCCESS) {
                    ...
                } else if (result.eventType === EventType.ACQUIRE_TOKEN_SUCCESS) {
                    ...
                } else if (result.eventType === EventType.LOGIN_FAILURE) {
                    if (result.error.errorCode === 'user_cancelled' || (result.error.errorCode === 'consent_required' && this.router.url === '/login')) {
                        ...
                    }
                } else if (result.eventType === EventType.ACQUIRE_TOKEN_FAILURE) {
                    ...
                }
                if (environment.name !== 'prod') {
                    ...
                }
            });
```

// For Azure B2C issues, please include your policies.

## Expected behavior
In nested if statement for login failure, it should also look at AuthError. I believe this is defined in EventError already but for some reason is not finding it. 
## Identity Provider

- [X] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by tnorling** [comment]
@shinkhouse Can you cast `result.error` to `AuthError` or check that `result.error` is an instance of `AuthError`? EventError is defined as `AuthError | Error | null` so you'll need to validate that `result.error` is of the correct type before accessing specific properties on it.


You could do something like this:

```js
else if (result.eventType === EventType.LOGIN_FAILURE) {
    if (result.error instanceof AuthError && (result.error.errorCode === 'user_cancelled' || (result.error.errorCode === 'consent_required' && this.router.url === '/login'))) {
        ...
    }
```

**Comment by shinkhouse** [comment]
@tnorling Yes, that was a great idea. That did the trick. Thank you for your assistance.
