### ISSUE TITLE
Angular 10 browser sample doesn't build

### ISSUE THREAD

**Issue by Josh-Kewley-BC** [AzureAD/microsoft-authentication-library-for-js#2763]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.8.0`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework
- [X] Angular (CLI 10.0.6)
- [ ] React
- [ ] Other

## Description
The most recent bits which use `msal-browser 2.8.0` do not build for the `angular-10-browser-example`.

## Error Message

```
ERROR in src/app/msal/msal.service.ts:33:53 - error TS2345: Argument of type 'Partial<AuthorizationUrlRequest>' is not assignable to parameter of type 'PopupRequest'.
  Type 'Partial<AuthorizationUrlRequest>' is not assignable to type '{ scopes: string[]; }'.
    Property 'scopes' is optional in type 'Partial<AuthorizationUrlRequest>' but required in type '{ scopes: string[]; }'.

33         return from(this.instance.acquireTokenPopup(request));
                                                       ~~~~~~~
src/app/msal/msal.service.ts:51:46 - error TS2345: Argument of type 'Partial<AuthorizationUrlRequest>' is not assignable to parameter of type 'PopupRequest'.
  Type 'Partial<AuthorizationUrlRequest>' is not assignable to type '{ scopes: string[]; }'.

51         return from(this.instance.loginPopup(request));
                                                ~~~~~~~
```

## MSAL Configuration

```js
N/A
```

## Reproduction steps

```js
git clone repo
open \angular10-browser-example directory in vs code
npm install
ng build 
```

## Expected behavior
build completes

## Identity Provider

- [X] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [ ] Chrome
- [ ] Firefox
- [X] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [X] Did this behavior work before?
Version: I last tried with 2.4.1

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by jasonnutter** [comment]
@Josh-Kewley-BC Thanks, I can reproduce this. You can change the type for the `request` parameter from `AuthorizationUrlRequest` to `PopupRequest` and it should work. cc @jo-arroyo
