### ISSUE TITLE
Can we use KeychainPersistence for windows and linux in msal-node-extension?

### ISSUE THREAD

**Issue by ci010** [AzureAD/microsoft-authentication-library-for-js#2766]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`
- [x] `@azure/msal-node-extension@alpha`

## Description

Can we use KeychainPersistence for windows and linux for msal-node-extension?
From keytar README:

> A native Node module to get, add, replace, and delete passwords in system's keychain. On macOS the passwords are managed by the Keychain, on Linux they are managed by the Secret Service API/libsecret, and on Windows they are managed by Credential Vault.

it's also supporting windows and linux, whereas our documents and comments in code all somehow imply the `KeychainPersistence` is for macOS. What's our concern here?

**Comment by sameerag** [comment]
Extensions help with persistent encrypted storage of the credentials on each platform (mac, windows and linux)

* KeyChainPersistence on mac implies supporting the specific encryption storage model for MacOS - referenced [here](https://support.apple.com/guide/keychain-access/what-is-keychain-access-kyca1083/mac). 
* Similar encryption implementations are available with Windows (Data protection APIs known as DPAPIs referenced [here](https://docs.microsoft.com/en-us/dotnet/standard/security/how-to-use-data-protection))
* Linux has varied implementations and hence we support some of the versions which support libsecret referenced [here](https://wiki.gnome.org/Projects/Libsecret)

The idea is to provide cross platform support for cache persistence in a pre-agreed format with other MSALs (.net/java/python) to be able to store and retrieve tokens securely.

Hope this clarifies.
