### ISSUE TITLE
loginRedirect method opens Microsoft login page and fails

### ISSUE THREAD

**Issue by oleksandr-slys** [AzureAD/microsoft-authentication-library-for-js#2768]
## Library
- [x] `@azure/msal-browser@2.8.0`

## Description

When I start login process with `loginRedirect` method it tries to open Microsoft web page and fails.

![image](https://user-images.githubusercontent.com/53045642/102354281-a4fd8380-3faa-11eb-9a32-4840e03b8029.png)

Do you have any ideas about issue reason or maybe point me to the direction where to find?

I also know that our authentication in AzureAD is federated through our ADFS to the on-prem user identities. And Outlook desktop uses WAM, the new and supposedly modern, Web Account Manager for Modern authentication.

My application is the outlook add-in. The error reproducible in desktop outlook only and works fine in web one (OWA).

I have tried different approaches:
* use custom popup as mentioned https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2039#issuecomment-744070070
* use loginPopup
* use loginRedirect in the same window
* use loginRedirect in the separate dialog (`window.Office.context.ui.displayDialogAsync` method)
* disable WAM

There is a latest sample of code that fails. 

```js
// main window code
window.Office.context.ui.displayDialogAsync(`${baseUri}login.html`, { height: 30, width: 20 })

// login window code
let msalInstance;

const initMsalInstance = () => {
  msalInstance = new window.msal.PublicClientApplication({
    auth: {
      authority,
      clientId,
      navigateToLoginRequestUrl: false,
      postLogoutRedirectUri: `${baseUri}login.html`,
      redirectUri: `${baseUri}login.html`,
      validateAuthority: true,
    },
    system: {
      allowRedirectInIframe: true,
      loadFrameTimeout: 10000,
    },
    cache: {
      cacheLocation: 'localStorage',
      storeAuthStateInCookie: true,
    },
  });

  msalInstance.handleRedirectPromise()
    .then(response => {
        const responseStr = JSON.stringify(response);
        console.log('response', responseStr);
        if (response === null) msalInstance.loginRedirect()
        else window.Office.context.ui.messageParent(responseStr);
    }).catch(error => { });
};

window.Office.initialize = () => {
    window.Office.onReady(() => {
        console.log('onReady');
        initMsalInstance();
    });
};
``` 

I am not sure whether it is related, but I also see next logs in Edge dev console:
![image](https://user-images.githubusercontent.com/53045642/102359523-31ab4000-3fb1-11eb-9180-a91fb94b8533.png)

## Source

- [x] Customer request

**Comment by jasonnutter** [comment]
@oleksandr-slys Can you please record a Fiddler trace for this error and email it to me? The server logs indicate a malformed request, but I'm unable to see exact details. Thanks!

**Comment by oleksandr-slys** [comment]
@jasonnutter could you please advise me how to do it properly? Each time I enable Fiddler Outlook stops to work.

**Comment by oleksandr-slys** [comment]
@jasonnutter I did more investigation. It happens that problem exists only for the users with Windows Virtual Desktop, but it works fine with a regular PC. But again it works fine in WVD with OWA.

**Comment by jasonnutter** [comment]
@oleksandr-slys Interesting, thanks. I'll try to find out more and follow up.
