### ISSUE TITLE
Feature Request: Ability to consume and store a token

### ISSUE THREAD

**Issue by CAJohns** [AzureAD/microsoft-authentication-library-for-js#277]
As a user it would be great to be able to store an authorised token. The main objective would be for MSAL to have a function that can accept a token and then use that for further authorisation.
 
Consider an application that authorises a user through another means that returns an ID Token. This application then links to another separate application in a different window. The second application passes the token from the first and allows a seamless auth flow for the user.

**Comment by rohitnarula7176** [comment]
@CAJohns As per the current design, we expect the signed in user context is established through the same app. Silent SSO is not currently supported in the v2 endpoint which is what Msal goes against to authenticate the user.

**Comment by navyasric** [comment]
@CAJohns  Please try the latest version of MSAL.js for achieving your scenario. You can take a look at this [Wiki page](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Sso) on getting SSO between different apps with MSAL.js

**Comment by nehaagrawal** [comment]
@CAJohns  As @navyasric  mentioned, this is already fixed as part of the SSO feature that we released in latest version. Please check the documentation. I am closing this issue for now. Please reopen if issue still exists.
