### ISSUE TITLE
unprotectedResources workaround

### ISSUE THREAD

**Issue by jayricx** [AzureAD/microsoft-authentication-library-for-js#2774]
## Library

- [ ] `msal@1.4.4` or `@azure/msal@1.4.4`
- [ ] `@azure/msal-angular@1.1.2`

## Framework

- [ ] Angular 9
- [ ] MSAL 1.4.4
- [ ] msal-angular 1.1.2

## Description
I have a specific API method that I don't want msal to protect.  In the previous version of msal-angular 0.1.4, I just add the URL in the unprotectedResources. But now in version 1.1.2, it no longer works.  
The documentation says that 
- As of @azure/msal-angular@1.1.0, protectedResourceMap supports wildcard patterns that are supported by minimatch, and unprotectedResources is deprecated and ignored.

I did some reading about this and I found this link https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2217.  I tried the suggestion by adding the URL in the protectedResourceMap and setting it null and also the negate syntax.  But it never works on me.  It works if the url is on a different domain  than my website.  like if my website base url is "https://localhost:44360" and I have an api https://localhost:44360/oapi/test/getserverdate.  It didn't work if the url starts with https://localhost:44360.  It works if it is from a different domain like https://www.otherwebsite.com/oapi/getserverdate.

Here is my code:

```js
MsalModule.forRoot({
      auth: {
        clientId: config.auth.clientId,
        authority: config.auth.authority,
        validateAuthority: true,
        redirectUri: rootUrl,
        postLogoutRedirectUri: rootUrl,
        navigateToLoginRequestUrl: true,
      },
      cache: {
        cacheLocation: <CacheLocation>config.cache.cacheLocation,
        storeAuthStateInCookie: isIE, // set to true for IE 11
      },
    },
      {
        popUp: !isIE,
        consentScopes: config.consentScopes,
        protectedResourceMap: [          
          ['https://localhost:44360/oapi/test/getserverdate', null],
          ['https://localhost:44360/api/*', [ "api://xxxxx-xxxx-xxxx-xxxx-xxxxxxxx/user.read" ]],
          ['https://graph.microsoft.com/', [ "User.Read", "User.ReadBasic.All" ]]
        ],
        extraQueryParameters: {}
      }),
```

## Error Message
ClientAuthError: User login is required. For silent calls, request must contain either sid or login_hint
    at ClientAuthError.AuthError [as constructor] (https://localhost:44360/vendor.js:148481:28)
    at new ClientAuthError (https://localhost:44360/vendor.js:148614:28)
    at Function.push../node_modules/msal/lib-es6/error/ClientAuthError.js.ClientAuthError.createUserLoginRequiredError (https://localhost:44360/vendor.js:148663:16)
    at MsalService.<anonymous> (https://localhost:44360/vendor.js:145833:130)
    at step (https://localhost:44360/vendor.js:170944:23)
    at Object.next (https://localhost:44360/vendor.js:170925:53)
    at https://localhost:44360/vendor.js:170918:71
    at new ZoneAwarePromise (https://localhost:44360/polyfills.js:15319:33)
    at Module.__awaiter (https://localhost:44360/vendor.js:170914:12)
    at https://localhost:44360/vendor.js:145811:111

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps

```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Identity Provider

- [ ] Azure AD

## Browsers/Environment

- [ ] Chrome
- [ ] Firefox
- [ ] Edge

## Regression

- [ ] Did this behavior work before?
Version: msal-angular 0.1.4

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by tnorling** [comment]
@jayricx Does this work if you use relative uris? i.e. `/oapi/test/getserverdate` instead of `https://localhost:44360/oapi/test/getserverdate`

**Comment by jayricx** [comment]
> @jayricx Does this work if you use relative uris? i.e. `/oapi/test/getserverdate` instead of `https://localhost:44360/oapi/test/getserverdate`

Hi, thanks for your reply. I tried it and unfortunately it is still showing the same error.  It is validating everything within the https://localhost:44360.

**Comment by tnorling** [comment]
@jayricx Can you debug the Interceptor and determine what url is passed to the Interceptor?

**Comment by jayricx** [comment]
Hi @tnorling, Thanks for your reply. I figured how to debug the interceptor. The URL being passed into the interceptor is incorrect, it was an issue in my code :).  There was a line in my code that replaces the URL.
