### ISSUE TITLE
TypeScript example: return type of Promise ` getTokenPopup` not correct

### ISSUE THREAD

**Issue by DarkLite1** [AzureAD/microsoft-authentication-library-for-js#2775]
## Library
- [x] `@azure/msal-browser@2.8.0`

## Framework
- [x] Vue

## Description
In the [TypeScript example](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-browser-samples/TypescriptTestApp2.0/src/AuthModule.ts) we see this method:
```typescript
    private async getTokenPopup(silentRequest: SilentRequest, interactiveRequest: PopupRequest): Promise<string> {
        try {
            const response: AuthenticationResult = await this.myMSALObj.acquireTokenSilent(silentRequest);
            return response.accessToken;
        } catch (e) {
            console.log("silent token acquisition fails.");
            if (e instanceof InteractionRequiredAuthError) {
                console.log("acquiring token using redirect");
                return this.myMSALObj.acquireTokenPopup(interactiveRequest).then((resp) => {
                    return resp.accessToken;
                }).catch((err) => {
                    console.error(err);
                    return null;
                });
            } else {
                console.error(e);
            }
        }
    }
```

The return value of the Promise is of type `string`. However, in case of errors `null | undefined` is returned which are not matching the type.. Same is true for the method `getTokenRedirect`.

## Error Message
> TS2322: Type 'string | null' is not assignable to type 'string'.
  Type 'null' is not assignable to type 'string'.

**Comment by tnorling** [comment]
Closing as duplicate #2779
