### ISSUE TITLE
TypeScript example: Missing initializers

### ISSUE THREAD

**Issue by DarkLite1** [AzureAD/microsoft-authentication-library-for-js#2777]
## Library
- [x] `@azure/msal-browser@2.8.0`

## Framework
- [x] Vue

## Description
In the [TypeScript example](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-browser-samples/TypescriptTestApp2.0/src/AuthModule.ts) we see this class:
```typescript
export class AuthModule {
  private myMSALObj: PublicClientApplication // https://azuread.github.io/microsoft-authentication-library-for-js/ref/msal-browser/classes/_src_app_publicclientapplication_.publicclientapplication.html
  private account: AccountInfo // https://azuread.github.io/microsoft-authentication-library-for-js/ref/msal-common/modules/_src_account_accountinfo_.html
  private loginRedirectRequest: RedirectRequest // https://azuread.github.io/microsoft-authentication-library-for-js/ref/msal-browser/modules/_src_request_redirectrequest_.html
  private loginRequest: PopupRequest // https://azuread.github.io/microsoft-authentication-library-for-js/ref/msal-browser/modules/_src_request_popuprequest_.html
  private profileRedirectRequest: RedirectRequest
  private profileRequest: PopupRequest
  private mailRedirectRequest: RedirectRequest
  private mailRequest: PopupRequest
  private silentProfileRequest: SilentRequest // https://azuread.github.io/microsoft-authentication-library-for-js/ref/msal-browser/modules/_src_request_silentrequest_.html
  private silentMailRequest: SilentRequest
  private silentLoginRequest: SsoSilentRequest

  constructor() {
    this.myMSALObj = new PublicClientApplication(MSAL_CONFIG)
    this.account = null
    this.setRequestObjects()
  }
```
Because the constructor is not setting initial values, the errors below are returned.

## Error Message
> TS2564: Property 'loginRedirectRequest' has no initializer and is not definitely assigned in the constructor.
TS2564: Property 'loginRequest' has no initializer and is not definitely assigned in the constructor.
TS2564: Property 'profileRedirectRequest' has no initializer and is not definitely assigned in the constructor.
TS2564: Property 'profileRequest' has no initializer and is not definitely assigned in the constructor.
TS2564: Property 'mailRedirectRequest' has no initializer and is not definitely assigned in the constructor.
TS2564: Property 'mailRequest' has no initializer and is not definitely assigned in the constructor.
TS2564: Property 'silentProfileRequest' has no initializer and is not definitely assigned in the constructor.
TS2564: Property 'silentMailRequest' has no initializer and is not definitely assigned in the constructor.
TS2564: Property 'silentLoginRequest' has no initializer and is not definitely assigned in the constructor.

**Comment by tnorling** [comment]
Closing as duplicate #2779
