### ISSUE TITLE
TypeScript example: Type 'null' is not assignable to type 'AuthenticationResult'

### ISSUE THREAD

**Issue by DarkLite1** [AzureAD/microsoft-authentication-library-for-js#2778]
## Library
- [x] `@azure/msal-browser@2.8.0`

## Framework
- [x] Vue

## Description
In the [TypeScript example](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-browser-samples/TypescriptTestApp2.0/src/AuthModule.ts) we see this method:
```typescript
  loadAuthModule(): void {
    this.myMSALObj
      .handleRedirectPromise()
      .then((resp: AuthenticationResult) => {
        this.handleResponse(resp)
      })
      .catch(console.error)
  }
```
On success of `handleRedirectPromise()` the response object is said to be of type `AuthenticationResult`. But when we check the definition of `handleRedirectPromise()` within `node_modules\@azure\msal-browser\dist\src\app\ClientApplication.d.ts` the return type is different:

```ts
handleRedirectPromise(hash?: string): Promise<AuthenticationResult | null>;
```

## Error Message
> TS2322: Type 'AccountInfo | null' is not assignable to type 'AccountInfo'.
  Type 'null' is not assignable to type 'AccountInfo'.

**Comment by tnorling** [comment]
Closing as duplicate #2779
