### ISSUE TITLE
TypeScript example: Promises must be handled appropriately

### ISSUE THREAD

**Issue by DarkLite1** [AzureAD/microsoft-authentication-library-for-js#2779]
## Library
- [x] `@azure/msal-browser@2.8.0`

## Framework
- [x] Vue

## Description
In the [TypeScript example](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-browser-samples/TypescriptTestApp2.0/src/AuthModule.ts) we see the following methods:
```typescript
  login(signInType: string): void {
    if (signInType === 'loginPopup') {
      this.myMSALObj
        .loginPopup(this.loginRequest)
        .then((resp: AuthenticationResult) => {
          this.handleResponse(resp)
        })
        .catch(console.error)
    } else if (signInType === 'loginRedirect') {
      this.myMSALObj.loginRedirect(this.loginRedirectRequest)
    }
  }

  logout(): void {
    const logOutRequest: EndSessionRequest = {
      account: this.account,
    }
    this.myMSALObj.logout(logOutRequest)
  }
```
The issue is the methods `loginRedirect` and `logout` both return a Promise that isn't handled correctly. To solve this one need to change the function to either use `async/await` or prefix the Promise call with with `void`.

## Error Message
> @typescript-eslint/no-floating-promises: Promises must be handled appropriately or explicitly marked as ignored with the `void` operator.

**Comment by tnorling** [comment]
@DarkLite1 I'm going to consolidate all of your issues into this one as they represent one work item which has been on our backlog and we intend to pick up soon. The reason this seems inconsistent is because we do not use the `strict` typescript compiler option **yet**. We intend to turn this on soon and you can rest assured the sample will be updated when that happens. I will leave this open until then.

**Comment by DarkLite1** [comment]
Thank you for not closing this one. A proper strict TypeScript example would be nice.

**Comment by tnorling** [comment]
@DarkLite1 The TypeScript sample has been updated with the `strict` compiler option in the linked PR. Hope that helps!

**Comment by DarkLite1** [comment]
Thank you Thomas, I appreciate the help. Closing this one.
