### ISSUE TITLE
Are v2 endpoint post logout redirects currently not working?

### ISSUE THREAD

**Issue by 12trey** [AzureAD/microsoft-authentication-library-for-js#2780]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [x] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
I was attempting to test our app with the @azure/msal-angular@2.0.0-alpha and noticed post logout redirects were not working.  I see the post logout URI encoded in the querystring but it never attempts to redirect.

As a simple test, I removed the v2.0 path in the logoutUri in the ClientApplication.prototype.logout() function.  

`logoutUri = logoutUri.replace('/v2.0', '');`
`return [2 /*return*/, BrowserUtils.navigateWindow(logoutUri, this.config.system.redirectNavigationTimeout, this.logger)];`

This seems to work though I'm not sure what this could be affecting.  Local or session storage are cleared properly and I'm correctly logged out of my application.

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by tnorling** [comment]
@12trey There's 3 things you need in order to have logout redirect back to your app:

- Pass a postLogoutRedirectUri to logout
- Register this url as a redirectUri on the app registration
- Register this url as the Logout url on the app registration

Can you verify that all 3 of these things have been done in your case?

**Comment by 12trey** [comment]
@tnorling - Thanks. All those items have been verified. I think if I were missing any of those, logging out with the v1 endpoint hack would fail as well.

**Comment by tnorling** [comment]
@12trey Can you send me a fiddler trace of both behaviors? My email is on my profile.

**Comment by 12trey** [comment]
Sorry.  I know this is closed and I didn't get back with fiddler dump.  I just wanted to let anyone know who may come across this that I found the problem to be with the "main" account which is a Microsoft Account.  If I log in with an AAD account created in my tenant, it redirects just fine after logout.
