### ISSUE TITLE
How to handle forgot password in @azure/msal-react

### ISSUE THREAD

**Issue by ilbrando** [AzureAD/microsoft-authentication-library-for-js#2781]
## Library

- [x] `@azure/msal-browser@2.7.0`
- [x] `@azure/msal-react@1.0.0-alpha`

## Description

I'm having trouble figuring out how to handle when the user has forgotten his or hers password. I can see, that the user is redirected back to my app, and I suppose that is so I can start the reset password flow I want to use.

But how do I do that? I can't find a suitable method on the result of the `useMsal` hook.

**Comment by tnorling** [comment]
@ilbrando It depends a little bit on how you're calling login. I haven't quite finished the b2c sample yet but you can take a look at an example of how this is handled for redirect cases on the branch I've been working on [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/a7f1995767101d0a93ed212b373d46ea7131bd3c/samples/msal-react-samples/b2c/src/App.jsx#L34).

The gist of it is that you need to catch the error that is thrown when someone clicks "forgot password" and then call login again with the reset policy. If you can share a code snippet of how you're calling login I can give more specific guidance for your scenario.

**Comment by ilbrando** [comment]
I use the hook `useMsal`. The methods on the `instance` object are defined like this:
```TypeScript
export interface IPublicClientApplication {
    acquireTokenPopup(request: PopupRequest): Promise<AuthenticationResult>;
    acquireTokenRedirect(request: RedirectRequest): Promise<void>;
    acquireTokenSilent(silentRequest: SilentRequest): Promise<AuthenticationResult>;
    addEventCallback(callback: Function): string | null;
    removeEventCallback(callbackId: string): void;
    getAccountByHomeId(homeAccountId: string): AccountInfo | null;
    getAccountByLocalId(localId: string): AccountInfo | null;
    getAccountByUsername(userName: string): AccountInfo | null;
    getAllAccounts(): AccountInfo[];
    handleRedirectPromise(hash?: string): Promise<AuthenticationResult | null>;
    loginPopup(request?: PopupRequest): Promise<AuthenticationResult>;
    loginRedirect(request?: RedirectRequest): Promise<void>;
    logout(logoutRequest?: EndSessionRequest): Promise<void>;
    ssoSilent(request: SsoSilentRequest): Promise<AuthenticationResult>;
    getLogger(): Logger;
    setLogger(logger: Logger): void;
}
```
I use the `loginRedirect` for login. It takes a `RedirectRequest` which extends `AuthorizationUrlRequest`:
```TypeScript
export declare type AuthorizationUrlRequest = BaseAuthRequest & {
    authenticationScheme?: AuthenticationScheme;
    redirectUri?: string;
    extraScopesToConsent?: Array<string>;
    responseMode?: ResponseMode;
    codeChallenge?: string;
    codeChallengeMethod?: string;
    state?: string;
    prompt?: string;
    account?: AccountInfo;
    loginHint?: string;
    domainHint?: string;
    sid?: string;
    extraQueryParameters?: StringDict;
    nonce?: string;
};
```
None of these indicates a flow.

The only place I specify my flow is when I instantiate the `PublicClientApplication`, but I only do that one time in the app lifetime. It takes a `Configuration` object where I set the `auth.authority` property to my login flow. There is also an `knownAuthorities` property, but I don't know how to use it.

**Comment by tnorling** [comment]
@ilbrando Since you're using redirect you'll want to register an event callback that listens for a login failure with a specific error code and then calls loginRedirect again with your forgot password policy like so: 

```js
instance.loginRedirect({
    authority: "https://something.b2clogin.com/something.onmicrosoftonline.com/forgotPasswordPolicy"
});
```

The link to the sample I shared above should be what you need.

> There is also an knownAuthorities property, but I don't know how to use it.

`knownAuthorities` should be an array that contains the domains for the authorities your app will use i.e. `knownAuthorities: ["something.b2clogin.com"]` and is required when using b2c with msal.

**Comment by ilbrando** [comment]
@tnorling I looked at your example, and I can see that you set the `authority` property on the `RedirectRequest`. Maybe the problem is with the TypeScript definitions? I will try and cast to `any` and set `authority`. It's a bit late in my timezone so I will try it tomorrow. Thank you for your fast response.

**Comment by tnorling** [comment]
Some of the properties of `RedirectRequest` are not shown in the snippet you shared above because `AuthorizationUrlRequest` also extends `BaseAuthRequest`. Complete type docs can be found here: https://azuread.github.io/microsoft-authentication-library-for-js/ref/msal-browser/modules/_src_request_redirectrequest_.html#redirectrequest

**Comment by ilbrando** [comment]
@tnorling Ohh sorry, I just noticed that I didn't see that `AuthorizationUrlRequest` extends `BaseAuthRequest` which has the `authority` property. I'm so sorry.

**Comment by ilbrando** [comment]
@tnorling I got it to work, but I get an exception in the console. Do you know how to get rid of this? I have set an event handler with `addEventCallback`, but some part of MSAL must also be listening for the event and is throwing the exception.
```
index.es.js:210 Uncaught (in promise) ServerError: access_denied: AADB2C90118: The user has forgotten their password.
Correlation ID: efa45107-f006-440e-8990-e81c60839f4e
Timestamp: 2020-12-17 22:41:10Z
    at ServerError.AuthError [as constructor] (http://localhost:3000/static/js/0.chunk.js:479:20)
    at new ServerError (http://localhost:3000/static/js/0.chunk.js:4212:24)
    at ResponseHandler.validateServerAuthorizationCodeResponse (http://localhost:3000/static/js/0.chunk.js:5609:13)
    at AuthorizationCodeClient.handleFragmentResponse (http://localhost:3000/static/js/0.chunk.js:5993:21)
    at RedirectHandler.<anonymous> (http://localhost:3000/static/js/0.chunk.js:10671:40)
    at step (http://localhost:3000/static/js/0.chunk.js:204:17)
    at Object.next (http://localhost:3000/static/js/0.chunk.js:135:14)
    at http://localhost:3000/static/js/0.chunk.js:107:67
    at new Promise (<anonymous>)
    at __awaiter (http://localhost:3000/static/js/0.chunk.js:84:10)
    at RedirectHandler.handleCodeResponse (http://localhost:3000/static/js/0.chunk.js:10656:12)
    at PublicClientApplication.<anonymous> (http://localhost:3000/static/js/0.chunk.js:11477:34)
    at step (http://localhost:3000/static/js/0.chunk.js:204:17)
    at Object.next (http://localhost:3000/static/js/0.chunk.js:135:14)
    at fulfilled (http://localhost:3000/static/js/0.chunk.js:87:24)
AuthError @ index.es.js:210
ServerError @ index.es.js:3313
ResponseHandler.validateServerAuthorizationCodeResponse @ index.es.js:4485
AuthorizationCodeClient.handleFragmentResponse @ index.es.js:4773
(anonymous) @ index.es.js:8456
step @ index.es.js:74
(anonymous) @ index.es.js:55
(anonymous) @ index.es.js:48
__awaiter @ index.es.js:44
RedirectHandler.handleCodeResponse @ index.es.js:8442
(anonymous) @ index.es.js:9092
step @ index.es.js:74
(anonymous) @ index.es.js:55
fulfilled @ index.es.js:45
```

By the way is there a safe way to read the error code (AADB2C90118)? As far as I can see it is only part of the `errorMessage` string.

**Comment by tnorling** [comment]
@ilbrando hmmm...what version of `msal-react` are you running? I would not expect the error to be thrown in the console, just to verify I ran the sample myself and did not get the error when clicking forgot password.

As for the error, that's an error thrown by the server and msal just passes it along as is. We can look into better ways of handling it in the future but for now that's the recommended way.

**Comment by ilbrando** [comment]
`msal-react` is 1.0.0-alpha.0 and `msal-browser` is 2.7.0.
I have now upgraded to 1.0.0-alpha.1 and 2.8.0 and that solved the problem :-)
