### ISSUE TITLE
acquireTokenSilent always throws interaction_required error (AADB2C90077) when forcing refresh

### ISSUE THREAD

**Issue by bdj61383** [AzureAD/microsoft-authentication-library-for-js#2783]
## Library
- [x] `msal@1.3.1`

## Framework
-[x] None

## Description
Use case is as follows: Currently we store user roles as a claim in the accessToken JWT returned from B2C. Upon certain API actions in our application, we know that a user's roles have changed and that they need to fetch a new JWT that accurately reflects their new, updated roles. We are attempting to use the acquireTokenSilent method with the `forceRefresh` config value set to force the silent fetching of a new JWT.  However, all calls to aquireTokenSilent result in an `interaction_required` (AADB2C90077) error. We are handling this with an acquireTokenRedirect call in the case of such an error, but that of course results in a redirect, which we wish to avoid so as not to interrupt the user's flow.  It's worth noting that we always get this error response, even if making the aquireTokenSilent call within seconds or minutes of logging in via acquireTokenRedirect, so it is not an issue of a user's session expiring. Is this expected behavior?

This is a vanilla JS application.

## Error Message
```
InteractionRequiredAuthError: AADB2C90077: User does not have an existing session and request prompt parameter has a value of 'None'.
Correlation ID: d6e23c30-6261-449f-aca8-c0952949c9fe
Timestamp: 2020-12-17 21:08:34Z
```

## MSAL Configuration

```
	var msalConfig = {
		auth: {
			clientId: applicationConfig.clientID,
			authority: applicationConfig.authority,
			validateAuthority: false,
			redirectUri: applicationConfig.redirectUri,
			navigateToLoginRequestUrl: false
		},
		cache: {
			cacheLocation: 'localStorage',
			storeAuthStateInCookie: false
		},
		system: {
			loadFrameTimeout: 2500
		}
	};
```

## Reproduction steps
- Log a user in with the `loginRedirect` flow.
- Call the `acquireTokenSilent` method with the appropriate scopes and with `forceRefresh: true`.
- The error referenced in the Error Message section above is returned.

## Expected behavior
After a user has logged in successfully, it should be possible to silently update their accessToken via acquireTokenSilent without redirecting or refreshing the page. From the docs, it looks like the handling of the 302 redirect from B2C is supposed to happen in a hidden iframe. 

## Identity Provider

- [ ] Azure AD
- [X] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [X] Chrome
- [X] Brave
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [X] Customer request

**Comment by tnorling** [comment]
@bdj61383 This is unexpected. Please first try upgrading to the latest version (currently 1.4.4). Are you passing a `loginHint` to `acquireTokenSilent` and are 3rd party cookies enabled in your browser? A code snippet showing how you are calling `acquireTokenSilent` would be helpful here.

**Comment by bdj61383** [comment]
My apologies, I didn't realize my browser was set to disable 3rd party cookies.  Enabling them corrected the issue. In the case where a user has disabled 3rd party cookies, I suppose we'll need to live with the redirect back to the homepage. 
Thank you for your assistance and prompt reply.

**Comment by tnorling** [comment]
@bdj61383 Great, thanks for the update. The other option is to upgrade to `msal-browser@2.x` which does not suffer from the same 3rd party cookie limitations as version 1.

**Comment by bdj61383** [comment]
Thanks for letting me know about `msal-browser@2.x`, @tnorling. I was under the impression that it was just using msal core's `acquireTokenSilent` method under the hood and so would suffer from the same limitations.
