### ISSUE TITLE
Get auth code using msal-browser

### ISSUE THREAD

**Issue by Ramprakash333** [AzureAD/microsoft-authentication-library-for-js#2786]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x]  `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Currently, there is no provision for providing **response type as code** for getting auth code in **msal-browser**. In my SPA the front end would fetch the code and send it to backend and the backend will request for a token using it. So I have to modify the login pop-up function to get the code when the response type is set to code. Currently, **msal-node has the support for getting auth code by URL but the problem is I could not get the popup functionality** from msal-node. Please let me know if there is already a feature request or there is a way to pass response type in msal-browser.
## Source

- [ ] Internal (Microsoft)
- [x] Customer request

**Comment by tnorling** [comment]
@Ramprakash333 Unfortunately this functionality is not available today but we will consider this as a future enhancement to `msal-browser`. In the meantime, you can use `msal-node` to generate the auth code url and open a popup yourself. You'll have to manage the popup and close it at the appropriate time.

**Comment by Ramprakash333** [comment]
ok, Thank you. Closing this thread as the issue is addressed.
