### ISSUE TITLE
Renew IdToken silently

### ISSUE THREAD

**Issue by gayathri-rajamanickam4** [AzureAD/microsoft-authentication-library-for-js#279]
Hi,

In my application, we are planning to use Id token instead of access token to call custom web api. As I see that id token has expiry time, is there anyway that I can renew id token before it is expired without going to login page?

Thanks,
Gayathri

**Comment by rohitnarula7176** [comment]
@gayathri-rajamanickam4 You can renew id_token by calling acquireTokenSilent passing client id as the single scope in the scopes array. 
```
acquireTokenSilent(['client_id'])
```
