### ISSUE TITLE
InteractionType is not defined

### ISSUE THREAD

**Issue by wk0** [AzureAD/microsoft-authentication-library-for-js#2793]
## Library
"@azure/msal-browser": "^2.8.0",
"@azure/msal-react": "^1.0.0-alpha.1",

## Documentation location
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-react-samples/nextjs-sample/pages/_app.js  

## Description
Bug:
* ReferenceError: InteractionType is not defined

Fix: 
* import { InteractionType } from "@azure/msal-browser";

**Comment by tnorling** [comment]
@wk0 Thanks for bring this to our attention. I've linked a PR which will address this.
