### ISSUE TITLE
Hooks topic does not show how to logout

### ISSUE THREAD

**Issue by IanMercer** [AzureAD/microsoft-authentication-library-for-js#2794]
The hooks documentation explains how to call login but does not explain logout.

Documentation is here: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/hooks.md#usemsal-hook

Suggest adding something about logout using the sample code found elsewhere:

    const { instance, accounts } = useMsal();

    {accounts.map((account) => (
                <div key={account.homeAccountId}>
                    <span>{account.username}</span>
                    <button onClick={() => instance.logout({ account })} style={{ marginLeft: 20 }}>Logout</button>
                </div>
            ))}

**Comment by tnorling** [comment]
@IanMercer Logout docs can be found [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md) As the docs you linked are mostly intended to show how you can get the `PublicClientApplication` instance using the hook I'm reluctant to start adding usage of specific APIs hanging off that instance. However, links to the API docs for the various `PublicClientApplication` methods may be in order here. Thanks for pointing out this gap, I'll see what I can do to make this information easier to find.

**Comment by IanMercer** [comment]
Thanks, this is indeed a discovery issue. The page _appears_ to be a comprehensive list of what you can do with these hooks but apparently isn't. Whatever the "intent" behind it was is irrelevant to your users as it's not discernable. Adding `logout` will be appreciated by future visitors.
