### ISSUE TITLE
@azure/msal-browser redirect not working correctly.

### ISSUE THREAD

**Issue by CalamityLorenzo** [AzureAD/microsoft-authentication-library-for-js#2796]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x ] `@azure/msal-browser@2.8.0`

## Framework
- [ ] Angular
- [ x ] React 17.0.1
- [ ] Other

## Description
This was done using **msal-react-samples/typescript-sample**.
When using `loginRedirect()` the app is logged in, and returned to the redirect uri, wuth an error
`ClientAuthError: state_not_found: State not found:  Cached State`

I updated the `App()` hook to capture the error:
```export default function App() {
    const msalInstance = new PublicClientApplication(msalConfig);
    msalInstance.handleRedirectPromise()
        .then(a=>{
            console.log(a);
        })
        .catch(b=>{
            console.log('erro');
            console.log(b);
        })
    return (
        <MsalProvider instance={msalInstance}>
            <PageLayout>
                <MainContent />
            </PageLayout>
        </MsalProvider>
    );
}
```

At the login (https://login.microsoftonline.com/organizations || https://login.microsoftonline.com/common) prompt a state variable is in the request, and if I terminate the server and let the response return to the client web, the code and state are in the query string.

Nothing is present in the cookies/localState/sessionState.

## Error Message
(console log output from **msal.handleRedirectPromise**)
ClientAuthError: state_not_found: State not found:  Cached State
    AuthError index.es.js:503
    ClientAuthError index.es.js:685
    node_modules 0.chunk.js:1095
    node_modules 0.chunk.js:5683
    node_modules 0.chunk.js:6087
    node_modules 0.chunk.js:11004
    step index.es.js:74
    verb index.es.js:55
    __awaiter index.es.js:48
    __awaiter index.es.js:44
    node_modules 0.chunk.js:10989
    node_modules 0.chunk.js:11766
    step index.es.js:74
    verb index.es.js:55
    fulfilled index.es.js:45

## MSAL Configuration

```js
export const msalConfig: Configuration = {
    auth: {
        clientId: "GUID",
        authority: 'https://login.microsoftonline.com/organizations/'
    }
};.
```

## Reproduction steps

updates to the sample package.json for the released version of the msal-packages
```js
  "dependencies": {
    "@azure/msal-browser": "^2.8.0",
    "@azure/msal-react": "^1.0.0-alpha.1",
    "@types/node": "^12.19.4",
    "@types/react": "^16.9.56",
    "@types/react-dom": "^16.9.9",
    "bootstrap": "^4.5.3",
    "react": "^17.0.1",
    "react-bootstrap": "^1.4.0",
    "react-dom": "^17.0.1",
    "react-scripts": "3.4.3",
    "typescript": "^4.0.5"
  },
```

## Expected behavior
Redirect login to complete and store a token 

## Identity Provider

- [x ] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [x ] Chrome
- [x ] Firefox
- [x ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by lah8789** [comment]
I am experiencing this same behavior.

**Comment by tnorling** [comment]
@CalamityLorenzo 

> Nothing is present in the cookies/localState/sessionState.

This is why. Can you determine what is clearing sessionStorage?

**Comment by CalamityLorenzo** [comment]
AFAIK nothing is.
Like I said this based on the tutorial, so nothing is being changed, and I'm not changing the session/local state directly.
The following appears occasionally in the session but it doesn't seem consistent
Key
`server-telemetry-b68e0007-afab-4b1a-a391-066c2a18b835`
Value
`{"failedRequests":[865,"dde05bb7-b6ae-4c80-9732-954d3e750c3e"],"errors":["state_not_found"],"cacheHits":0}`

**Comment by tnorling** [comment]
@CalamityLorenzo Can you remove `handleRedirectPromise` and see if that resolves the issue? `msal-react` calls this under the hood and it should not be called manually.

**Comment by CalamityLorenzo** [comment]
Yep, that solves it.
Does that mean the `handleRedirectPromise` is entirely off limits if I am using `msal-react`?

For this report I've used the sample to demonstrate my issue succintly, however in my own project I'm not using `msal-react`, and the same error occurs. (again not writing to the session/local state.)

If i remove the `handleRedirectPromise`  function  from my own project then the response is not processed, and the parameters are left in the query portion of the address.

**Comment by tnorling** [comment]
@CalamityLorenzo 
> Does that mean the `handleRedirectPromise` is entirely off limits if I am using `msal-react`?

Yes, calling it directly should be considered off-limits, however, there are other ways to obtain the response, most notably using the event listener. (This is something I intend to add to the docs before we GA and I'm sorry you had to find out the hard way)

> For this report I've used the sample to demonstrate my issue succintly, however in my own project I'm not using `msal-react`, and the same error occurs. (again not writing to the session/local state.)

If you're not using `msal-react` you will need to call `handleRedirectPromise` but make sure you're only calling it once per page load (or at the very least ensure you don't have multiple unresolved invocations running concurrently). In the example you shared you were creating a race condition between `msal-react` and your own implementation of `handleRedirectPromise` to handle the redirect response. We've worked to minimize the potential for race conditions in `handleRedirectPromise` but it looks like we may need to revisit that effort.

**Comment by CalamityLorenzo** [comment]
Noting your advice around a race-condition, and keeping it early in the pipe line, I moved `PublicClientApplication` and `handRedirectPromise` to fire earlier.

So my app, is a basic `create-react-app`, with the usual start 

```
ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById('root')
);
```

The App function (when it errored), was like the following:
```

function App() {
  const msalInstance = new PublicClientApplication(msalConfig);
  // const currentAccount = new CurrentAccountManager();
  msalInstance.handleRedirectPromise()
    .then((s) => {
      console.log(s);
      if (s !== null && s.account != null)
//        currentAccount.setCurrentAccount(s.account.username, s.account.homeAccountId, s.account.tenantId);
      console.log('success');
    })
    .catch((a: any) => {
      console.log('err');
      console.log(a);
    })

  return (
    <div className="App">
      <BrowserRouter>
        <main>
          <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/Login">Login</a></li>
            <li><a href="/Consent">Consent</a></li>
          </ul>
        </main>
        <Route path="/Login" ><LoginPage msalLogin={msalInstance}></LoginPage></Route>
        <Route path="/Consent" component={ConsentPage} />
        <Route exact={true} path="/" render={() => <h1>Home</h1>} ></Route>
      </BrowserRouter>
    </div>
  );
}

```

Now I've moved the msal calls out of the `App` functions context:

```
const msalInstance = new PublicClientApplication(msalConfig);
// const currentAccount = new CurrentAccountManager();
msalInstance.handleRedirectPromise()
  .then((s) => {
    console.log(s);
    if (s !== null && s.account != null)
      //        currentAccount.setCurrentAccount(s.account.username, s.account.homeAccountId, s.account.tenantId);
      console.log('success');
  })
  .catch((a: any) => {
    console.log('err');
    console.log(a);
  });

function App() {
  return (
    <div className="App">
      <BrowserRouter>
        <main>
          <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/Login">Login</a></li>
            <li><a href="/Consent">Consent</a></li>
          </ul>
        </main>
        <Route path="/Login" ><LoginPage msalLogin={msalInstance}></LoginPage></Route>
        <Route path="/Consent" component={ConsentPage} />
        <Route exact={true} path="/" render={() => <h1>Home</h1>} ></Route>
      </BrowserRouter>
    </div>
  );
}
```
Am I effectively making the msal instance a piece of global state?

**Comment by tnorling** [comment]
@CalamityLorenzo If you want to initialize msal in your component, you can. You just need to put the `handleRedirectPromise` call in a `useEffect` hook. This is one way you could do this:

```js
function App() {
  const msalInstance = new PublicClientApplication(msalConfig);
  // const currentAccount = new CurrentAccountManager();

  useEffect(() => {
      msalInstance.handleRedirectPromise()
        .then((s) => {
          console.log(s);
          if (s !== null && s.account != null)
            //        currentAccount.setCurrentAccount(s.account.username, s.account.homeAccountId, s.account.tenantId);
            console.log('success');
        })
        .catch((a: any) => {
          console.log('err');
          console.log(a);
        });
  }, []);

  return (
    <div className="App">
      <BrowserRouter>
        <main>
          <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/Login">Login</a></li>
            <li><a href="/Consent">Consent</a></li>
          </ul>
        </main>
        <Route path="/Login" ><LoginPage msalLogin={msalInstance}></LoginPage></Route>
        <Route path="/Consent" component={ConsentPage} />
        <Route exact={true} path="/" render={() => <h1>Home</h1>} ></Route>
      </BrowserRouter>
    </div>
  );
}
```
