### ISSUE TITLE
Unable to find hash in url, timing out / Unable to complete authoriation as there is no interactive call in progress. This can be due to closing the app while the authorization was in process.

### ISSUE THREAD

**Issue by nomanshahsyed** [AzureAD/microsoft-authentication-library-for-js#2798]
## Library

- [X] `@azure/msal-angular@1.1.2`
```
Ionic:

   Ionic CLI                     : 6.12.3 (C:\Users\USER\AppData\Roaming\npm\node_modules\@ionic\cli)
   Ionic Framework               : @ionic/angular 5.5.2
   @angular-devkit/build-angular : 0.1002.1
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : 6.0.0, android 8.1.0, browser
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 6 other plugins)

Utility:

   cordova-res                          : not installed
   native-run (update available: 1.3.0) : 0.2.7

System:

   NodeJS : v10.15.2 (C:\Program Files\nodejs\node.exe)
   npm    : 4.6.1
   OS     : Windows 10
```

## Framework

- [X] Angular 10
- [ ] React
- [ ] Other

## Description
I have setup the APP in azure like below. 

![image](https://user-images.githubusercontent.com/26595409/102780764-3308ae00-439f-11eb-89e8-1adda0520041.png)

When I use localhost as the redirect URI. It works fine on browser. It will of course not work on the phone. The redirect URI with localhost has theid token and everything. When I put the redirect URI from the android section, the login page redirects to my app correctly. Immediately i get the error number 4 from below list as an alert on the phone. The other first 3 errors i see on the console. 

It doesnt matter if i put the `useHash: true or false` I get the error 1 all the time.

It also cant fire the `handleRedirectCallback` when i use `loginredirect`. 

## Error Message

1. Error monitorPopupForHash unable to find hash in url, timing out
2. MSALError {_error: "token_renewal_error", _errorDesc: "Token renewal operation failed due to timeout.", _scopes: ""}
3. {"errorCode":"token_renewal_error","errorMessage":"Token renewal operation failed due to timeout.","name":"ClientAuthError"}
4. Alert on Android ( Unable to complete authoriation as there is no interactive call in progress. This can be due to closing the app while the authorization was in process.)

## MSAL Configuration

  

```
MsalModule.forRoot(
      {
        auth: {
          clientId: "xxxx",
          authority: "https://login.microsoftonline.com/common/",
          validateAuthority: true,
          redirectUri: "msauth://com.XXX",
          postLogoutRedirectUri: "msauth://XXX",
          navigateToLoginRequestUrl: true,
        },
        cache: {
          cacheLocation: "localStorage",
        },
      },
      {
        consentScopes: ["user.read", "openid", "profile"],
        protectedResourceMap: protectedResourceMap,
        extraQueryParameters: {},
      }
    ),

```

## Reproduction steps

```js

  ngOnInit(): void {

    this.authService.handleRedirectCallback((authError, response) => {
      if (authError) {
        console.log("Redirect Error: ", authError.errorMessage);
        return;
      }
      console.log("Redirect Success: ", response.accessToken);
    });
    this.broadcastService.subscribe("msal:loginFailure", (payload) => {
      console.log("login failure " + JSON.stringify(payload));
      this.loggedIn = false;
    });

    this.broadcastService.subscribe("msal:loginSuccess", (payload) => {
      console.log("login success " + JSON.stringify(payload));
      this.loggedIn = true;
    });

    this.authService.setLogger(
      new Logger(
        (logLevel, message, piiEnabled) => {
          console.log("MSAL Logging: ", message);
        },
        {
          correlationId: CryptoUtils.createNewGuid(),
          piiLoggingEnabled: false,
        }
      )
    );
  }

  login() {
    this.authService.loginPopup();
  }

  logout() {
    this.authService.logout();
  }
// For Azure B2C issues, please include your policies.
```

## Identity Provider

- [X] Azure AD

## Browsers/Environment

- [X] Chrome

## Source
- [X] Customer request

**Comment by tnorling** [comment]
@nomanshahsyed You cannot use an android `redirectUri` with `msal-angular`. Since you can't use localhost you'll need to serve your app over https and register that redirectUri as type web

**Comment by nomanshahsyed** [comment]
Hi, can't we make it work? The return URL has the token and the navigation to and from the login page works and it redirects correctly to the app.

**Comment by tnorling** [comment]
@nomanshahsyed What happens when you use redirect instead of popup?

**Comment by nomanshahsyed** [comment]
Same behavior. Nothing changes.

**Comment by tnorling** [comment]
Specifically what happens? What errors occur? Can you debug to figure out why there is no hash in the url?

**Comment by nomanshahsyed** [comment]
There is a Hash in the URL. I saw the hash. Then tried to enable/disable the useHash with routes. Nothing changed. 

The errors were same as I posted above. I followed the logcat too and there were same errors. I'm finished for today but tomorrow morning I'll try to run it again and tell you what i see there. 

If only the handle redirect function fires, it will tell more info.

**Comment by nomanshahsyed** [comment]
I implemented the login with google and that works fine. The google plus and firebaseX plugins also don't have the Microsoft login functions though they have Twitter, Apple etc login.

**Comment by tnorling** [comment]
If you're seeing the same errors then it's not running redirect...those errors are specific to the popup scenario. If the url returns with a hash but the error says it can't find a hash then you need to determine what is clearing the hash. One thing you can try (for the popup scenario only) is to make the `redirectUri` a blank page that does not implement msal. If the page used as the `redirectUri` is either removing the hash or initiating a redirect of its own, the calling page will be unable to retrieve the hash and you'll get an error like the one you've shared above.

**Comment by nomanshahsyed** [comment]
Ok so for loginPopup the app crashes now whenever this function is called.

For loginredirect i put the localhost as a redirecturi and the returned url has the # along with the code and client info.

When the URI is for the android app from azure page, the app opens up correctly with the following error Alert on Android 
( Unable to complete authoriation as there is no interactive call in progress. This can be due to closing the app while the authorization was in process.)

**Comment by tnorling** [comment]
> When the URI is for the android app from azure page, the app opens up correctly with the following error Alert on Android
( Unable to complete authoriation as there is no interactive call in progress. This can be due to closing the app while the authorization was in process.)

@nomanshahsyed Can you determine what is throwing that error? I don't think that's one of ours. Do you see any msal errors in the console?
