### ISSUE TITLE
Best pratice to refresh token in react

### ISSUE THREAD

**Issue by francesco-clementi-92** [AzureAD/microsoft-authentication-library-for-js#2799]
## Library
-  `@azure/msal-react@1.0.0-alpha.1`

## Description
As written in the documentation  "It is recommended that you call acquireTokenSilent in your app before making an API call to get the valid token".

So the best practice is to refresh the token at every api call or should I check the expiration every time?

Moreover, in my react project I have my apis centralized as functions, but I can't use the msal-react hooks to get the PCA Instace and the accounts outside of a component. 

What is the best way to avoid replication of code trying to refresh the token at every api call?

Getting the PCA and the accounts in every component that need to call an api, passing them to the api function and refreshing the token seems a bit excessive.

**Comment by tnorling** [comment]
@missklorina 

> So the best practice is to refresh the token at every api call or should I check the expiration every time?

Yes, you should call `acquireTokenSilent` before every API call. `acquireTokenSilent` will examine expiration, you do not need to build logic around this. When you call `acquireTokenSilent` it will first attempt to retrieve the access token from the cache, if it is expired or within the offset (5 minutes by default) or cannot be found it will then attempt to exchange the refresh token for a new access token. It will make a network call, at most, once per hour.

> What is the best way to avoid replication of code trying to refresh the token at every api call?

Our [samples](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/default/src) show how to call an API. We retrieve the token in our component and just pass the access token to the API function, but it's ultimately up to you and what makes sense for your application.

**Comment by shyam2794** [comment]
@tnorling I am using axios interceptor to attach the authorization header in each request . now if i have the acquireTokenSilent logic in the interceptor i see the network call being made to acquire the new token for each request . 

![image](https://user-images.githubusercontent.com/30238125/103699910-aa5a5680-4fc9-11eb-8bdb-f4c5cea38987.png)

This is my interceptor
```
axios.interceptors.request.use(
  async (config) => {
    config.headers['x-api-challenge'] =
      localStorage.getItem('challenge') || 'no-key-found';
    // refreshAccessToken method is the one which makes acquireTokenSilent call .
    const token = await refreshAccessToken();
    if (token) {
      config.headers['Authorization'] = `Bearer ${token}`;
    }
    return config;
  },
  (error) => Promise.reject(error)
);
```

```
export const refreshAccessToken = async () => {
  const account = getAccountInfo();
  try {
    const token = await msalInstance.acquireTokenSilent({
      scopes: loginRequest.scopes,
      account,
    });
    return token.accessToken;
  } catch (error) {
    if (error instanceof InteractionRequiredAuthError) {
      return msalInstance
        .acquireTokenPopup(loginRequest)
        .then((resp) => {
          return resp.accessToken;
        })
        .catch((err) => {
          return null;
        });
    } else {
      console.error(error);
    }
  }
};
```
 Am i missing something here ? . not sure why we have 3 API calls .

**Comment by tnorling** [comment]
@shyam2794 Those are not token requests, though I would not expect those to be made either. Could you please open a new issue with a minimal reproduction so we can better understand your specific scenario? Thanks!

**Comment by shyam2794** [comment]
@tnorling i also see this in the browser dev tools . 
![image](https://user-images.githubusercontent.com/30238125/103708028-be0bba00-4fd5-11eb-827b-c4c7eb1d429a.png)

**Comment by tnorling** [comment]
@shyam2794 Please verify that you are not re-initializing msal at any point as these network calls will be made on the first token request after initialization. When using React, you'll need to be careful to not call the `PublicClientApplication` constructor on re-renders as that will cause everything in `msal-react` to re-render in addition to these network calls.

**Comment by shyam2794** [comment]
@tnorling looks like i was getting this calls on the page reload . Subsequent API calls within the App did not make any call to retrieve the token 👍  . Also if we make a call to `acquireTokenSilent`  will the new access and refresh tokens will be updated in the cache ( local or session storage ) automatically ? or do we need to manually update it in local or session storage ?

**Comment by tnorling** [comment]
@shyam2794 Yes, the library handles all caching under the hood, you do not need to handle this yourself.
