### ISSUE TITLE
Page Redirecting to login repeatedly

### ISSUE THREAD

**Issue by anirudhholla** [AzureAD/microsoft-authentication-library-for-js#280]
I have used MSAL for authentication, once I authenticate using my microsoft account, login page is popping up repeatedly in loop. However it works fine on Chrome. 

I have enbled local storage, added my app URL on Trusted Sites.

**Comment by rohitnarula7176** [comment]
@anirudhholla We have a known issue with  IE/Edge browser. Currently, we do not have any other workaround that we can provide.
