### ISSUE TITLE
Unable to get Access token from the first party AAD using MSAL

### ISSUE THREAD

**Issue by KrisshDev** [AzureAD/microsoft-authentication-library-for-js#2811]
Hi Team,

We are using first party AAD and its a single page application using MSAL with implicit grant, so access token will be from the authentication server after successful authentication and its stored in local storage of browser, during MSAL angular we tried to pass consent scopes ,so from the token got from from authentication server is ID token and unable to generate access token  i.e. with required scopes in claims,we are using We are using MSAL 1.3.0,MSAL-angular 1.0.0,

Please let us know if you need any other information,

Thanks

**Comment by tnorling** [comment]
@KrisshDev Please fill out one of the [provided issue templates](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/new/choose). It helps us organize the information and address your issue quicker.

Can you please try upgrading to the latest versions of both msal (1.4.4) and msal-angular (1.1.2) and if you experience the same issue please let us know what you expect to happen as well as what is currently happening including relevant code snippets. Thanks!
