### ISSUE TITLE
[msal-node] SNI authentication

### ISSUE THREAD

**Issue by hotovee** [AzureAD/microsoft-authentication-library-for-js#2812]
## Library

- [ ] `@azure/msal-node@1.x.x`

## Description
As part of ECR drill, one of our certs was marked as Blocked for NodeJS auto-rotation support. That support is now available since the latest node version of @azure/msal-node (1.0.0-beta.1) supports SNI.

I followed the documentation https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/sni.md and defined msalConfig according to the following template:

const msalConfig = {

    auth: {

        clientId: "enter_client_id_here",

        clientCertificate: {

            thumbprint: "enter_thumbprint_here",

            privateKey: "enter_privatekey_here",

            x5c: "enter_x5c_here"

        },

    }

}

I tried to play around with it, but I got errors and it didn’t worked out of the box.

(I get an error: Failed getting token. message: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: Discovery incomplete.)
so, before I dive deeper into your code I thought maybe you could help.

I created a "ConfidentialClientApplication" using the msalConfig and clientCredentialRequest,
and used acquireTokenByClientCredential

I’ve tried to look for an example at other repositories at msazue, msdata, Microsoft but couldn’t find any.

BTW - I'm moving from adal-node library.
## Error Message

 Failed getting token. message: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: Discovery incomplete

**Comment by jo-arroyo** [comment]
@jmckennon Could you take a look at this?

**Comment by jmckennon** [comment]
@hotovee can you provide the rest of your msal configuration and code usage?
