### ISSUE TITLE
SPA begins authorization code flow - Backend receives the authorization code and performs exchange

### ISSUE THREAD

**Issue by mirusky** [AzureAD/microsoft-authentication-library-for-js#2816]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [X] `@azure/msal-react@1.0.0-alpha.1`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

Scenario:

A Golang back-end serving a React front-end. The front-end starts an `Authorization Code Flow` and configure the `redirect_uri` for the back-end **/callback** where actions will be taken to create the tokens using the azure golang sdk (e.g: [ ...TokenFromAuthorizationCode](https://github.com/Azure/go-autorest/tree/master/autorest/adal#authorization-code-authenticate)). Tokens will be managed by back-end, not showing or getting access to tokens in front-end.

Problem:

It's not possible to set `responseMode`.

As said in [this](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2228#issuecomment-687281538) comment 
> [...]the library is built to specifically use the fragment response mode...

As the response is a fragment url, it not allow to send the **code** (and others query params) to the back-end **/callback** (aka `redirect_uri` ) since post-fragment information (`#code=...&response_mode=...&...`) aren't sent.

As the same in [this](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2228) issue I want to be able to set `ReponseMode` properly

## Source

- [ ] Internal (Microsoft)
- [X] Customer request

**Comment by tnorling** [comment]
@mirusky Currently `msal-browser`, and by extension `msal-react`, are intended for use in SPAs with no back end component. While this feature/scenario is something we have considered and may pick up at some point, it is not yet on the roadmap. For now our recommendation for apps that have a backend component is to handle auth on the backend. In your scenario this may mean using an Auth Library for Go to generate the url you can pass up to your frontend to handle the redirect. One example of such a library is the pre-release [Msal-Go](https://github.com/AzureAD/microsoft-authentication-library-for-go)

**Comment by mirusky** [comment]
Interesting to know you are tracking this scenario, I really want to start the flow in front-end because of internal requirements... But for a while I belive we can start the flow on back-end. But we don't intent to stay in that way, since we want to create a microfront-end with all oauth stuff

Could we maintain this issue open and wait for new updates?

**Comment by jasonnutter** [comment]
Closing, as we have no plans to address this.
