### ISSUE TITLE
Error due to clientInfo object not set in redirect login flow

### ISSUE THREAD

**Issue by saurabhsablaka** [AzureAD/microsoft-authentication-library-for-js#2821]
- [x] `msal@1.2.1` 

I am using msal js for Implicit grant auth with redirect flow. Recently I tried to upgrade to latest version 1.4.4 but with this version I came across this issue "Cannot read property 'encodeClientInfo' of undefined". I checked the flow and it seems the token authority needs to return "CLIENT_INFO" as well with id hash. Unfortunately the token service I am using can not be changed to return this additional info.
Below is the log from my browser console -
![image](https://user-images.githubusercontent.com/76955683/103546599-405a8800-4ec9-11eb-9db8-fc22c28ed045.png)

The error is encountered at this point since the clientInfo object is not initialized.
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/45ef0d5103e5d714e77e26c1834955fc2c734f05/lib/msal-core/src/UserAgentApplication.ts#L1913

In the earlier version i.e 1.2.1 it worked fine for me since the clientInfo was getting initialized with empty string at this line unlike the way it is now .
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/45ef0d5103e5d714e77e26c1834955fc2c734f05/lib/msal-core/src/UserAgentApplication.ts#L1800

Is there a way to as of now to call the method ClientInfo.createClientInfoFromIdToken(idTokenObj, authority) even for my use case. I see right now it is very specific to ADFS authority type here - https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/45ef0d5103e5d714e77e26c1834955fc2c734f05/lib/msal-core/src/UserAgentApplication.ts#L1889

**Comment by jo-arroyo** [comment]
@saurabhsablaka We have the issue fixed in MSAL 2.x, and the service used can be specified, as per the doc [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/configuration.md#auth-config-options). Unfortunately, this is a bug in MSAL 1.x. We would recommend you upgrading to 2.x and setting `protocolMode` to `OIDC`. 

Additionally, can you please specify which service you are using?

**Comment by saurabhsablaka** [comment]
Thanks @jo-arroyo 
I am using msal js in a single page application having IdentityServer4 working as the authority service. Identity Server4 then connects to the internal IDP.
Can you please also help me understand this as well - I was under impression that for Implicit grant flow is available with 1.x only
In my SPA I want to use the basic js based implementation only with IdentiyServer4 as authority service.

**Comment by jo-arroyo** [comment]
@saurabhsablaka You are right, the implicit flow is only used in MSAL.js 1.x. MSAL.js 2.x changes to the authorization code with PKCE (which should supported by Identity Server 4).
