### ISSUE TITLE
Refresh Token is not working on chrome browser when Block third-party cookies is enabled

### ISSUE THREAD

**Issue by c-mpatel** [AzureAD/microsoft-authentication-library-for-js#2822]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [x] Angular
- [ ] React
- [ ] Other

## Description

1> app.module.ts
```
import {
  MsalModule,
  MSAL_CONFIG,
  MSAL_CONFIG_ANGULAR,
  MsalService,
  MsalAngularConfiguration,
  MsalInterceptor,
} from '@azure/msal-angular';
import { environment } from 'src/environments/environment';
import { Configuration } from 'msal/lib-commonjs/Configuration';

function MSALConfigFactory(): Configuration {
  return {
    auth: {
      clientId: xxxx-xxxxx-xxxx-xxxxx,
      authority: `https://test.b2clogin.com/tfp/test.onmicrosoft.com/test-loginPolicy`,
      validateAuthority: false,
      redirectUri: 'http://localhost:4200/',
      postLogoutRedirectUri: `http://localhost:4200/logout`,
      navigateToLoginRequestUrl: false,
    },
    cache: {
      cacheLocation: 'sessionStorage',
      storeAuthStateInCookie: false, // set to true for IE 11
    },
    system: {
      loadFrameTimeout: 90000,
      tokenRenewalOffsetSeconds: 3540,
    },
  };
}

function MSALAngularConfigFactory(): MsalAngularConfiguration {
  return {
    popUp: true,
    consentScopes: [
      'user.read',
      'openid',
      'profile',
      `https://test.onmicrosoft.com/clientId/user.read`,
    ],
    unprotectedResources: [],
    extraQueryParameters: {},
  };
}

@NgModule({
  declarations: [ ],
  imports: [
    MsalModule
  ],
  providers: [
    {
      provide: HTTP_INTERCEPTORS,
      useClass: MsalInterceptor,
      multi: true,
    },
    {
      provide: HTTP_INTERCEPTORS,
      useClass: AuthenticationHttpInterceptor,
      multi: true,
    },
    {
      provide: MSAL_CONFIG,
      useFactory: MSALConfigFactory,
    },
    {
      provide: MSAL_CONFIG_ANGULAR,
      useFactory: MSALAngularConfigFactory,
    },
    MsalService
  ],

  bootstrap: [AppComponent],
  exports: [RouterModule],
})
export class AppModule {}

```

2> app-routing Module

```
const routes: Routes = [ {
    path: 'home',
    loadChildren: () =>
      import('./modules/about/about.module').then((mod) => mod.AboutModule),
    canActivate: [MsalGuard, AuthGuard],
  }]
```

3> app.component.ts

```
const requestObj = {
scopes: [https://xxxxx.onmicrosoft.com/xxxx-xxxx-xxx-xxxxxx/user.read],
};

this.broadcastService.subscribe(
      'msal:acquireTokenFailure',
      (payload) => {
        if (payload.errorMessage.includes('AADB2C90077')) {
          this.authService.acquireTokenRedirect(requestObj);
        }
      }
    );
```

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
 - open application to chrome incognito model with ' Block third-party cookies ' True
 - after two minutes of login if the user navigates one page to another page then acquireTokenSilent method calling from Angular Msal and getting an error on 'Msal:acquireTokenFailure' method in app.component.ts file and calling acquireTokenRedirect.
 - but the issue is its infinite redirection loop.
 
 please give an example of how we can call interactive method if acquireToken gets Failure.
 
```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Expected behavior
- interactive method should work properly if there is a **Block third-party cookies** is enabled otherwise acquireTokenSilent should work
- before token expiration of five-minute token should renew.

## Identity Provider

- [ ] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by jo-arroyo** [comment]
@c-mpatel It looks like your `tokenRenewalOffsetSeconds` is set to 3540, while the default is 300 seconds, and this could be causing the infinite loop. Please try setting this to 300 and let us know if you continue to have problems. We do not recommend setting `tokenRenewalOffsetSeconds` that high, as it can cause timer issues and throttle the server.

**Comment by c-mpatel** [comment]
Hi @jo-arroyo 
In the default `tokenRenewalOffsetSeconds `  method refresh token event will call 55 minutes after login.
for testing purposes, I have set 3540 so the refresh token event will call every minute.

if browser 3rd party cookies enable, in this case, `tokenRenewalOffsetSeconds :3540` working fine it's renewing token every minute.


The issue is when 3rd party cookies are Block.

**Comment by jo-arroyo** [comment]
@c-mpatel With the default `tokenRenewalOffsetSeconds` and 3rd party cookies blocked, do you still experience the redirect loop?

**Comment by c-mpatel** [comment]
@jo-arroyo  I have changes this.authService.acquireTokenPopup(requestObj) when aquireToken api got failure insted of this.authService.acquireTokenRedirect(requestObj) 
 
 **issue:** popup fade in fade out for few second and in console getting below error: 
 AADB2C90077: User does not have an existing session and requests prompt parameter has a value of 'None'.

**Comment by jo-arroyo** [comment]
@c-mpatel When the popup fade in and fades out, are tokens being acquired successfully? If 3rd party cookies are disabled, the error AADB2C90077 is expected, and acquiring tokens via popup should succeed.

**Comment by c-mpatel** [comment]
@jo-arroyo  after popup fade in and fades out and the token is not renewing in session storage. and getting below error.

**error:** ClientAuthError: Login_In_Progress: Error during login call - login is already in progress.

**Comment by jo-arroyo** [comment]
@c-mpatel Can you please provide logs from the msal logger?
