### ISSUE TITLE
interaction_in_progress results in a blank popup

### ISSUE THREAD

**Issue by jdolearydl** [AzureAD/microsoft-authentication-library-for-js#2824]
## Library
- [x] `@azure/msal-browser@2.8.0`

## Description
The `interaction_in_progress` error could be handled more gracefully.  Currently it results in the new popup to be blank with no user-visible explanation as to what went wrong.

Could this be improved so that the most recent popup takes precedence?

## MSAL Configuration

```js
{
    auth: {
      REDACTED
    },
    cache: {
        cacheLocation: "localStorage",
        storeAuthStateInCookie: isIE,
    }
}
```

## Reproduction steps
![interaction_in_progress](https://user-images.githubusercontent.com/43141484/103573950-18552f80-4e9d-11eb-82e6-eb2a2bfe6800.gif)

1. Call `MSAL.loginPopup()` on one tab
2. Before interacting with the popup, switch tabs
3. Call `MSAL.loginPopup()` again on the new tab
4. Notice how the new popup is blank due to the `interaction_in_progress` error

## Expected behavior
I would expect the most recent popup to take precedence, or at least show an error rather than "about:blank"

## Identity Provider

- [x] Azure AD

## Browsers/Environment

- [ ] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [x] Customer request

**Comment by jasonnutter** [comment]
@jdolearydl I believe this is a duplicate of #2614, is that correct?

**Comment by jdolearydl** [comment]
@jasonnutter well in my case it's the second, most recent popup that goes blank, not the first.

**Comment by jdolearydl** [comment]
Closing as a duplicate, will comment on the original with additional info.

**Comment by jasonnutter** [comment]
Sounds good, thanks! We'll look to address this issue soon.
