### ISSUE TITLE
How do I use 'b2clogin' instead of 'login.microsoftonline' when using msal-angularjs?

### ISSUE THREAD

**Issue by SamVanGeijn** [AzureAD/microsoft-authentication-library-for-js#2826]
## Library

- [x] `@azure/msal@1.0.1` Also tried 1.4.4 and 1.2.2
- [x] `@azure/msal-angularjs@1.1.1`

## Description

We currently use the msal-angularjs plugin in our AngularJS application to log a user in via the sign in user flow. Due to the deprecation of login.microsoftonline.com (https://docs.microsoft.com/en-gb/azure/active-directory-b2c/b2clogin) I'm looking into changing the references to this domain to b2clogin, since we use the name of a policy in our URLs.

Currently we use the following URL as the authority when initialising 'msalAuthenticationServiceProvider':
https://login.microsoftonline.com/tfp/< tenant >.onmicrosoft.com/B2C_1_signin

Which works with @azure/msal version 1.0.1 (I've tried 1.2.2 and 1.4.4 as well) and msal-angularjs version 1.1.1. Following the migration guide I changed the authority to the following URL:
https://< tenant >.b2clogin.com/< tenant >.onmicrosoft.com/B2C_1_hs_signin

With the updated URL and the other settings remaining the same (see below) the application runs into an error when calling the 'loginRedirect' method. `msalAuthenticationService.loginRedirect();` 

Looking at the network tab of my browser the plugin eventually calls the following URL:
https://login.microsoftonline.com/common/discovery/instance?api-version=1.0&authorization_endpoint=https://< tenant >.b2clogin.com/< tenant >.onmicrosoft.com/b2c_1_hs_signin/oauth2/v2.0/authorize

Which then returns the following 400 Bad Request message:

````
{
error: "invalid_instance",
error_description: "AADSTS50049: Unknown or invalid instance. Trace ID: < ID > Correlation ID: > Timestamp: 2021-01-05 15:10:29Z",
error_codes: [
50049
],
timestamp: "2021-01-05 15:10:29Z",
trace_id: "< ID >",
correlation_id: "< ID >",
error_uri: "https://login.microsoftonline.com/error?code=50049"
}
````

From looking at the code of the plugin the call to 'https://login.microsoftonline.com/common/discovery/' seems to be hardcoded.

Is it possible to migrate to 'b2clogin' when using the msal-angularjs plugin? If so, which steps should I take? Thanks in advance!

For reference, the full code of initialising the 'msalAuthenticationServiceProvider' is as follows with 'b2clogin' in the authority:

````
msalAuthenticationServiceProvider.init({
            tenant: < name of tenant >,
            clientID: < client ID >,
            signUpSignInPolicy: 'B2C_1_signin',
            unprotectedResources: ["/login"],
            validateAuthority: false,
            b2cScopes: ["https://huuskesshop.onmicrosoft.com/scopes/read", "https://huuskesshop.onmicrosoft.com/scopes/write"],
            authority: false,
            routeProtectionConfig: {
                popUp: false,
                requireLogin: false,
                consentScopes: ["https://huuskesshop.onmicrosoft.com/scopes/read", "https://huuskesshop.onmicrosoft.com/scopes/write"]
            },
            optionalParams: {
                cacheLocation: 'localStorage',
                unprotectedResources: [],
                protectedResourceMap: [],
                logger: logger,
                storeAuthStateInCookie: true
            }
        }, $httpProvider);
````

## Source

- [x] Customer request

**Comment by jo-arroyo** [comment]
@SamVanGeijn Could you please clarify the versions you are using? Is it msal-angular 1.1.1 or msal-angularjs 0.1.1?

The `b2clogin` domain is supported with msal-angular 1.x and 2.x, we encourage you to take a look at our samples for 1.x [here](https://github.com/Azure-Samples/active-directory-b2c-javascript-angular-spa) and 2.x [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular11-b2c-sample), and consider upgrading to use msal-angular instead.

**Comment by SamVanGeijn** [comment]
Hi @jo-arroyo,

We have an AngularJS application and therefore use msal-angularjs 0.1.1. The provided samples are for later versions of Angular. Is it possible to use 'b2clogin' with msal-angularjs? If not, are there any other options besides upgrading our AngularJS application to Angular?

Thanks!

**Comment by jo-arroyo** [comment]
@SamVanGeijn Unfortunately, the `b2clogin` domain is not supported in msal-angularjs 0.1.1, and since msal-angularjs is no longer being actively maintained, we suggest upgrading to msal-angular so you can take advantage of the latest MSAL library. If you are unable to upgrade, you may consider forking msal-angularjs and making the needed changes.
