### ISSUE TITLE
Installing msal-node-extensions package fails npm gyp build step

### ISSUE THREAD

**Issue by eanders-MS** [AzureAD/microsoft-authentication-library-for-js#2827]
## Library

- [x] `@azure/msal-node-extensions@1.0.0-alpha.4`

## Framework

- [x] Node

## Description
Installing @azure/msal-node-extensions fails npm gyp build step.

## Error Message
```
$> npm install --save @azure/msal-node-extensions

> keytar@6.0.1 install C:\code\ms\pxt-backend\node_modules\@azure\msal-node-extensions\node_modules\keytar
> prebuild-install || node-gyp rebuild


> @azure/msal-node-extensions@1.0.0-alpha.4 install C:\code\ms\pxt-backend\node_modules\@azure\msal-node-extensions
> node-gyp rebuild


C:\code\ms\pxt-backend\node_modules\@azure\msal-node-extensions>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
internal/modules/cjs/loader.js:331
      throw err;
      ^

Error: Cannot find module 'C:\code\ms\pxt-backend\node_modules\nan\include_dirs.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:323:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:681:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:944:27)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:120:20)
    at Object.runInThisContext (vm.js:311:38)
    at Object.<anonymous> ([eval]-wrapper:10:26) {
  code: 'MODULE_NOT_FOUND',
  path: 'C:\\code\\ms\\pxt-backend\\node_modules\\nan\\package.json',
  requestPath: 'nan'
}
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
```

## Reproduction steps

1. Add `@azure/msal-node-extensions` to a Node project: `npm install --save @azure/msal-node-extensions`.
2. Notice the above error message.

## Expected behavior

Install would succeed.

## Environment

- [x] Windows 10
- [x] Node

## Source

- [x] Internal (Microsoft)

**Comment by eanders-MS** [comment]
Node v12.16.3

**Comment by hectormmg** [comment]
@eanders-MS we'll take a look at this, thanks for raising the issue!

**Comment by sameerag** [comment]
@samuelkubai can you please prioritize this?

**Comment by smhnkmr** [comment]
I too have the same issue in alpha.6 latest release. it's blocking the cache implementation. any updates on this fix? or any other workaround for now?

**Comment by sameerag** [comment]
@eanders-MS @smhnkmr Can you please confirm if you have installed the prerequisites needed for `node-gyp` listed [here](https://github.com/nodejs/node-gyp#on-windows)?

**Comment by samuelkubai** [comment]
@eanders-MS @smhnkmr I tried to reproduce this and was not successful. Could you give us a more detailed step by step instruction for the reproduction?

**Comment by sameerag** [comment]
Closing this. We are working on a feature to improve the experience of installing dependencies for `msal-node-extensions`. Please check our [roadmap](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/roadmap.md) for updates, we plan to add this soon with a projected timeline.

Regarding this specific issue, a clean install usually solves most of the installation issues seen by our customers.
