### ISSUE TITLE
Unable to Dynamically Set Authority or Tenant ID for MSAL V1

### ISSUE THREAD

**Issue by southpolesteve** [AzureAD/microsoft-authentication-library-for-js#2832]
## Library

- [x] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [ ] Angular
- [ ] React
- [x] Other

## Description
I am unable to dynamically login a user to another tenant attached to their account. This was possible using ADAL, but with MSALv1 I cannot seem to figure out how to accomplish this. Passing a custom authority and using multiple application instances does not work. The token in the attached examples always comes back attached to my default tenant and returns the same list of subscriptions regardless of which tenant was specified

## Error Message
N/A

## MSAL Configuration

```js
  return new Msal.UserAgentApplication({
    auth: {
      authority: `https://login.microsoftonline.com/${tenantId}`,
      clientId: "203f1145-856a-4232-83d4-a43568fba23d",
      redirectUri: "https://dataexplorer-dev.azurewebsites.net",
    },
  });
```

## Reproduction steps

- Stand alone repro dynamically setting authority: https://github.com/southpolesteve/msal-v1-switch-tenant/tree/master
- Stand alone repro using multiple app instances: https://github.com/southpolesteve/msal-v1-switch-tenant/pull/1/files

## Expected behavior

I can login a user to another tenant and get tokens that are issued for that tenant. This was possible using ADAL

## Identity Provider

- [x] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [x] Did this behavior work before?
Version: ADAL

## Security

- [ ] Is this issue security related?

## Source

- [x] Internal (Microsoft)
- [ ] Customer request

**Comment by jo-arroyo** [comment]
Issue closed, worked with customer offline. We encourage anyone who experiences this issue to upgrade to MSAL.js v2 where this scenario is supported.
