### ISSUE TITLE
Open 2 pages on Sharepoint 365 with web-part using MSAL fails

### ISSUE THREAD

**Issue by drweb86** [AzureAD/microsoft-authentication-library-for-js#2833]
## Library
- [x] `msal@1.4.4`, `msal@1.4.0`,
- [x] `@azure/msal-browser@2.8.0`

## Framework
- [x] React

## Description

The token request could not be fetched from the cache correctly. Error Detail: TypeError: Cannot read property 'replace' of null.

## Error Message
Error on one page: The token request could not be fetched from the cache correctly. Error Detail: TypeError: Cannot read property 'replace' of null
Error on second page: The reply address 'web-site/Test1' does not match the reply address 'web-site/Test2' provided when requesting Authorization code

## MSAL Configuration

```js
 this._app = new PublicClientApplication({
            auth: {
                authority: 'AUTHORITY',
                clientId: 'CLIENT_ID' 
                navigateToLoginRequestUrl: false,
            },
            cache: {
                cacheLocation: 'localStorage',
            },
        });
```

## Reproduction steps
Important configuration options:
- **cacheLocation** is **localStorage**,
- **redirectUri** is **null** (Sharepoint Online, we cannot navigate from Web-Part to root of Sharepoint out of a page user is on)

1. Open anonymous browser (Edge/Chrome). Not reproduced with certainty without anonymous tab.
2. Authorize using MSAL in some domain e.g. other web-site.
3. Open web-site/Test1 and web-site/Test2 pages at the same time from one page (using middle mouse click). Each page should instruct MSAL to redirect to itself (it is important)
where web-site is a web-site created on Sharepoint.

## Expected behavior

In both pages authentication silently succeeds OR
Authorize using Sharepoint 365 silently

## Identity Provider

- [x] Azure AD

## Browsers/Environment

- [x] Chrome
- [x] Edge

## Regression

- [x] Did this behavior work before?

**Actual result in react msal 1.4.0:**
Page 1: Authorization silently succeeds
Page 2: state_not_found. 

**Actual result if to wait between opening pages enough time for them to complete authrosization** via **await this._app.handleRedirectPromise();**
Page 1: Authorization silently succeeds
Page 2: Authorization silently succeeds

Behavior is not reproduced if
- use sessionStorage for cache -or- (not applicable, since we need the same app working in Teams)
- provide redirectUrl to '/' (not applicable to Sharepoint Web-Part case because they are located in different pages and redirecting to site catalog after opening the page is not an option at all!)
- wait between opening first and second page

## Security

- [-] Is this issue security related?

## Source

- [x] QA

**Comment by jasonnutter** [comment]
@drweb86 Out of curiosity, is there a specific reason why you are using MSAL directly, instead of using the authentication APIs provided by [SPFX](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-framework-overview)?

**Comment by drweb86** [comment]
@jasonnutter , thanks for the comment. I will check why msal was used.

**Comment by drweb86** [comment]
@jasonnutter Can you please clarify, is **MSAL** used **Sharepoint Online** behind the scenes?
Our project used **ADAL** for a quite time. And it took a huge effort to migrate to **MSAL**. And now we have to move to Sharepoint Framework, so page reloading will disappear when a web-part is wanting to get the authorization token?

**Comment by jasonnutter** [comment]
@drweb86 Yes, SPFx uses MSAL.js v1, and they will updating to MSAL.js v2 at some point in the future. It is recommended that SPFx webparts use their token APIs, instead of using MSAL.js directly: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/connect-to-api-secured-with-aad#use-the-aadtokenprovider-to-retrieve-access-token

**Comment by drweb86** [comment]
Thank you so much! Seems, like we have to wait and then upgrade from MSAL 2 to its Sharepoint wrapper.
