### ISSUE TITLE
acquireTokenByCode does not return a refresh token

### ISSUE THREAD

**Issue by AmitFidler** [AzureAD/microsoft-authentication-library-for-js#2836]
tried working with msal-node for oauth code flow,
getAuthCodeUrl works perfectly fine
and helps to construct the url and returns the code.

when trying to use the acquireTokenByCode method even when defining a "offline_access" within the scope,
it does not return a refresh token.

it is important to mention that when using the same code and firing a post request to:
https://login.microsoftonline.com/common/oauth2/v2.0/token
it does return a refresh token.

**Comment by sameerag** [comment]
`RefreshToken` is not returned to the users for MSAL libraries by design. A user would need `idToken` and `accessToken` to access the resources, and we provide them in `authenticationResult`. The `RefreshToken` is cached, and refreshed as needed depending on the expiry and renewal needs. Since the user never accesses `RefreshToken` directly and would need to swap it for a token that can be played against a resource, we would like to keep it in the cache rather than return it in the response.

Can you please confirm the cache has `RefreshToken` stored in your case to ensure this is working correctly?

Hope this clarifies!

**Comment by gautamsi** [comment]
Microsoft is worse in developer experience.

there has been several ask, at least you could have given option to return refresh token for greedy code. I don't need to depend on you to rotate refresh token. You are unnecessarily forcing people to move away from your lib.

for scalable apps it is app's responsibility to make sure how their flow is. complex architecture, hindrance in using what is in the protocol (dosen't OAuth protocol return refresh token) wasted my 2 day figuring out how to use this lib and get refresh token.  no wonder why Microsoft sdk and libs are incompetent and requires several partner libs and components. I can go on and on for several instances of arrogance or blunders in name of open source by MS

**Comment by AmitFidler** [comment]
Hi @sameerag, thanks, I quite agree with @gautamsi, the sdk should allow the retrieval of a refresh token.
we are working in a architecture that would not support the use of cached refresh token that is not exposed to the developer.
if it's ok, it could be extremely helpful to request a new feature for this specific use case,
at the moment it means that we are not using the sdk and we sure want to.

Thanks,
Amit

**Comment by alilland** [comment]
I agree that requesting a user token through the SDK is needed, I have spent around 3 days trying to read through microsoft docs and hours of youtube videos trying to figure out how and still havent figured it out. I dont need the library to manage the refresh for me... I can handle that... I just need the ability to get the refresh token which I can then use to refresh on my own. Im literally about to download wireshark just to see what traffic the SDK is generating so I can implement on my own...

**Comment by AmitFidler** [comment]
Any news on this issue?
Thanks,
Amit

**Comment by pkanher617** [comment]
Hi all. Apologies for the delay in answering.

@gautamsi This is your first warning: by participating in this repository, you agree to follow Microsoft's Code of Conduct: https://opensource.microsoft.com/codeofconduct/

Further violations may result permanent banishment. Happy to have a constructive conversation about why refresh tokens should be returned.

> I agree that requesting a refresh token through the SDK is a fundamental need

> we are working in a architecture that would not support the use of cached refresh token that is not exposed to the developer.

This is something that is not unique to MSAL.js, we have had these discussions in other MSAL libraries as well. I recommend reviewing [this discussion](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1234). 

**We are happy to consider adding this feature as an opt-in configuration for advanced users, but** after reading the above comments, it is still not clear on what use cases require the developer to use a refresh token. There are a few reasons we do not return the refresh token to developers:
- Refresh tokens need to be persisted, and it adds another security consideration if they are persisted in a location other than where you have designated the MSAL library to store them. 
- Reducing the number of refresh token requests to the authentication service by ensuring refresh token is ONLY used when a new access token is required.
- We recommend developers to retrieve access tokens using the acquireTokenSilent method, which will ensure you always have an access token that is not expired. This removes the need to track access token lifetime in the application.

> I dont need the library to manage the refresh for me... I can handle that... I just need the ability to get the refresh token which I can then use to refresh and cache on my own.

@alilland I'm not sure this is a compelling reason to allow refresh tokens. The entire point of the MSAL libraries is to abstract away the token retrieval and renewal from the application. `msal-node` [provides APIs](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-node-samples/standalone-samples/silent-flow/index.js) to customize where the tokens and account objects are stored, so you could potentially put those tokens in a place that your app can access afterwards. As I said above, we are happy to consider adding refresh tokens to the result, but it seems like you are only taking advantage of a fraction of what the library is offering.

cc @jmprieur @bgavrilMS for further discussion.

**Comment by gautamsi** [comment]
@pkanher617 dont worry, I will not be jumping here again. Happy without it until the approach changes.

**Comment by amitava82** [comment]
May be I'm not getting this. I have a Node background process that periodically sync OneDrive files for user. After I have access to user access_token and refresh_token I save them to database and my background process uses these tokens when needed. The process will request new tokens when old ones expire. Which flow an I supposed to use here? How will the msal-node library refresh the tokens of it's own if I can't persist them?

**Comment by bgavrilMS** [comment]
@gautamsi - ultimately AAD service is an OAuth2 certified service. You can use any OAuth2 library you like if you really want to or even make HTTP web requests on your own. By the way, OAuth protocol does not require IdP to issue refresh token, AAD does issue refresh tokens, but others do not. 

MSAL libraries are higher level abstractions over OAuth2. MSAL aims to remove some of the complexity in combining authorization grant with refresh_token grant and handling expiration. By the way, MSAL.NET has 1000s of apps developed, including Visual Studio and Git Credentials Manager, and they never needed access to refresh tokens. I'm sure we can figure out a solution here. Calling `AcquireTokenSilent` and making sure MSAL can persist the token cache is all you need.

@amitava82 - MSAL will persist all tokens (access tokens, refresh tokens, id tokens) and some metadata about accounts to its cache. You only need to tell MSAL where to persist a blob. For public client apps (i.e. desktop apps, console apps)  on Windows you typically store it to a file and encrypt the file with Windows' Data Protection API, on Mac you'd use the KeyChain etc. For confidential client apps, i.e. web sites, web apis, you can store it in a distributed cache or in the session. Depending on your scenario, we can point you to some samples that do the heavy lifting. We currently do not provide a default persistence strategy, but we probably should for public clients.

**Comment by amitava82** [comment]
@bgavrilMS Thanks for the explanation. We use serverless functions so a file storage like in the example won't work. I think what we need a storage api interface that we can implement. I just finished Box integration where their javascript api does it similar way and I just had to implement my own strategy for token store/retrieval logic. Can you please point me to the sample you're referring to (that isn't based on filesystem storage)?

**Comment by bgavrilMS** [comment]
@amitava82 - just to understand your scenario better. You have a front end where you ask the user to login and you collect the authorization code. You then send the authorization code to your backend (a serverless function) and redeem it for tokens using MSAL? Or does your front end also redeem the auth code ?

The MSAL mechanism that allows you to customize the token cache storage has a sample [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-node-samples/standalone-samples/silent-flow/index.js#L21) - but it uses a file. Not sure if @sameerag and team have a sample showing other persistence mechanisms, but should be easy to adapt to your needs - you need to persist a blob and to give it back to MSAL when it asks for it.

**Comment by amitava82** [comment]
@bgavrilMS Yes, the token exchange happens in backend using the `code`. From the look of the code it looks like it writes entire cache into the blob. I'd want to only update the one that changed in the given request context. Is there any document for the cache storage?

**Comment by bgavrilMS** [comment]
I'll let the JS team respond to the request for sample, I don't how far the token caching got for this confidential client scenario. @jmprieur may be able to help as well.

**Comment by sameerag** [comment]
Thankyou @bgavrilMS. Appreciate the help.

@amitava82 Some points to note:
* Currently msal-node cache is always written and read as a single blob, MSAL manages to merge the old data with new one to be in sync with the latest changes made by the application in run time. We are working on making this more flexible, the design to write and read single credentials to disk is not yet finalized. 
* We have a default implementation of file encryption as an additional library that can be opted in for a cross platform file storage [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/extensions/docs/msal-node-extensions.md)
* I understand for your use case you do not want a file, and I believe it is possible to send any blob of data into `msal-node` as long as you implement ICachePlugin - referenced [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/713e4bd2bc6569a916913ea5c502437e33fa4ea8/lib/msal-common/src/cache/interface/ICachePlugin.ts#L8) and [here](https://azuread.github.io/microsoft-authentication-library-for-js/ref/interfaces/_azure_msal_common.icacheplugin.html).
* Can you please check the msal-node-extensions documentation above and see if we can tailor that to your needs? We can work with you to develop a sample. 

cc @sangonzal @samuelkubai

**Comment by amitava82** [comment]
Thanks @sameerag for the pointers. I'll try to come up with a solution with ICachePlugin implementation. As long as I can pick the single credential that changed and `msal-node` can accept the blob then it should work.
