### ISSUE TITLE
Problem when using ngx translator with MSAL interceptor - HttpClient for Angular translation 

### ISSUE THREAD

**Issue by SibeeshVenu** [AzureAD/microsoft-authentication-library-for-js#2839]
I am using the MSAL version of `"^1.4.2"` and below is my MSAL configuration in the `app.module.ts`.

```
function MSALConfigFactory(): Configuration {
  return {
    auth: {
      clientId: environment.clientId,
      authority: environment.authority,
      validateAuthority: true,
      redirectUri: environment.redirectUrl,
      postLogoutRedirectUri: environment.redirectUrl,
      navigateToLoginRequestUrl: true
    },
    cache: {
      storeAuthStateInCookie: false,
    },
    system: {
      logger: new Logger((level, message) => console.log(`${level} - ${message}`), { level: LogLevel.Warning })
    }
  };
}
function MSALAngularConfigFactory(): MsalAngularConfiguration {
  return {
    popUp: false,
    consentScopes: [
      environment.backendConfig.resourceScope
    ],
    protectedResourceMap: [
      [environment.backendConfig.url, [environment.backendConfig.resourceScope]]
    ],
  };
}
```
I am also using the ` "@ngx-translate/core": "^13.0.0"` with the below configuration. 

```
export function HttpLoaderFactory(http: HttpClient) {
  return new TranslateHttpLoader(http, './assets/i18n/', '.json');
}
```
And 

```
TranslateModule.forRoot({
      loader: {
        provide: TranslateLoader,
        useFactory: HttpLoaderFactory,
        deps: [HttpClient]
      }
    })
```
As you can imagine that this will get the values from the `'./assets/i18n` folder for the translation. even though this is not included in the `protectedResourceMap`, it still uses the MSAL interceptor when this call happens. 

![image](https://user-images.githubusercontent.com/4262147/103925892-7772a880-5118-11eb-98e1-fd0679578a16.png)

And of course, I can use the [HttpBackend](https://angular.io/api/common/http/HttpBackend) handler to fix this as proceeding. 

```
TranslateModule.forRoot({
      loader: {
        provide: TranslateLoader,
        useFactory: HttpLoaderFactory,
        deps: [HttpBackend]
      }
    })
```
```
export function HttpLoaderFactory(handler: HttpBackend) {
  return new TranslateHttpLoader(new HttpClient(handler), './assets/i18n/', '.json');
}
```
I would expect that the MSAL interceptor to skip this call.

**Comment by jasonnutter** [comment]
Please see this comment for how to mitigate this issue: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2515#issuecomment-727108424

**Comment by SibeeshVenu** [comment]
@jasonnutter Thanks. That did the trick, however, I was getting an error as preceding.

```
ERROR in src/app/app.module.ts:47:30 - error TS2322: Type 'null' is not assignable to type 'string[]'.
47       ["assets/i18n/*.json", null]
```
So I had to change the code a bit. 

```
protectedResourceMap: [
      [environment.backendConfig.url, [environment.backendConfig.resourceScope]],
      ['./assets/i18n/*.json', null as any]
    ]
```

But now, the images are not loading in the application. 

![image](https://user-images.githubusercontent.com/4262147/103933269-611e1a00-5123-11eb-9fdc-7c17857fa703.png)

**Comment by SibeeshVenu** [comment]
I had to change the `url` styles from `background: url(../../assets/img/background.svg)`  to `background: url(/assets/img/background.svg)`.
