### ISSUE TITLE
Angular 10/11 Samples multi-tenant requirement

### ISSUE THREAD

**Issue by keith-maddox** [AzureAD/microsoft-authentication-library-for-js#2840]
Hello, we are trying to build an application in Angular 10 and secure against Azure AD. We have the app registration setup and attempting to use auth code flow. implicit disabled. I have followed along tutorials for angular 10 and 11, using the download samples, and I get errors using them. Both Angular 10 and 11 samples says that the app registration must be multi tenant. Ours is not multi tenant so how can we alter the sample to not require that? Also, in Angular 10 and 11, this error can not be displayed if using redirect. The error cant find the redirect route so I had to force popup to see the real error, which is the multi tenant requirement. 
1. Need error route added
2. Need flag to allow single tenant app which avoids '/common' endpoint

**Comment by jasonnutter** [comment]
@keith-maddox In regards to single-tenant app, you should replace the configuration values for clientId and authority with the values needed for your application. For single tenant applications, you can set the authority to `https://login.microsoftonline.com/{tenantid}`.

>  Also, in Angular 10 and 11, this error can not be displayed if using redirect. The error cant find the redirect route so I had to force popup to see the real error, which is the multi tenant requirement.

I don't understand the issue you describe here, can you please provide more details (e.g. logs, screenshots)? Thanks!

Also, in the future, please fill out one of the issue templates: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/new/choose
