### ISSUE TITLE
Redirect the user to the page he is trying to access by having it in the browser memory

### ISSUE THREAD

**Issue by sneha-boopal** [AzureAD/microsoft-authentication-library-for-js#2843]
Requirement  is that after a user logs in via Azure AD (or any identity provider really), they should be redirected to the page they tried to access. Meaning a flow like this:

1) User tries to access http://localhost:3000/products
2) App redirects them to log in with Azure AD
3)User is redirected back to the application, and should now see the product list instead of getting redirected to index page(http://localhost/products).

I tried by adding http://localhost:3000/products in redirectUri but still it is getting redirected to http://localhost:3000.  
Is it achievable using msal and please provide if there are any sample apps

**Comment by jasonnutter** [comment]
@sneha-boopal This can be accomplished by passing the `redirectStartPage` parameter to `acquireTokenRedirect` or `loginRedirect`.  You will also need to set `auth.navigateToLoginRequestUrl` in your configuration to `true.

Futhermore, in the future please fill out one of the issue templates, thanks! https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/new/choose

**Comment by sneha-boopal** [comment]
Sure @jasonnutter Thank you for your reply!!

What if i'm using 'react-aad-msal' ? How to achieve redirect in the below case could you please suggest ->

import { MsalAuthProvider, LoginType } from 'react-aad-msal';
import { cacheLocation, defaultAuthority, defaultScope, token} from './utilities';

function AuthProvider() {
  try {
    sessionStorage.setItem('local-url', window.location.href);
    return new MsalAuthProvider(
      {
        auth: {
          authority: <defaultAuthority>,
          clientId: <clientID>,
          postLogoutRedirectUri: window.location.origin,
          redirectUri: window.location.origin + '/pmthome',
          validateAuthority:  false,
          navigateToLoginRequestUrl: true,
        },
        cache: {
          cacheLocation: appConfigData.cacheLocation || cacheLocation,
          storeAuthStateInCookie: appConfigData.storeAuthStateInCookie || true,
        },
      },
      {
        scopes: [ defaultScope ],
      },
      LoginType.Redirect,
    );
  }
  catch(error) {
    window.location.href = "/";
  }
}

**Comment by jo-arroyo** [comment]
@sneha-boopal Unfortunately, react-aad-msal is not a library we maintain, and we do not have suggestions on how to use the library.

@AndrewCraswell Can you offer some insight on how this can be done?
