### ISSUE TITLE
msal-browser@2.9.0 release date??

### ISSUE THREAD

**Issue by alan994** [AzureAD/microsoft-authentication-library-for-js#2848]
## Library
@azure/msal-browser@2.9.0

## Description
When do you plan to release version 2.9.0? I see that all work is done for this version, but I can't find it on npm. I just started to work on small project that uses Azure B2C and found your sample for Angular. In this sample there are multiple calls to setActiveAccount on IPublicClientApplication. I see that in new version, this method is available. Do you have a timeframe?

https://github.com/AzureAD/microsoft-authentication-library-for-js/milestone/71

## Source
Customer request

**Comment by gwenael-louandre** [comment]
+1

**Comment by jo-arroyo** [comment]
@alan994 @gwenael-louandre Thanks for your interest. We are planning on having `@azure/msal-browser@2.9.0` released this week.

**Comment by jo-arroyo** [comment]
Closing as `@azure/msal-browser@2.9.0` was released on 01/12/2021 and `@azure/msal-browser@2.10.0` was released on 01/21/2021.
