### ISSUE TITLE
When will MSAL.JS be released (General Availability Release)?

### ISSUE THREAD

**Issue by mmushatt** [AzureAD/microsoft-authentication-library-for-js#285]
Currently the documentation for Microsoft Authentication Library Preview for JavaScript (MSAL.js) - https://github.com/AzureAD/microsoft-authentication-library-for-js states the following:

When we provide the General Availability release we will require you to update to the General Availability version within six months, as applications written using a preview version of library may no longer work.

Are there any upcoming features that are slated to be released with the GA build? Do we have an available Roadmap of what to expect for the GA build? And, is an approximate GA release date available?

This information would be helpful in determining the usage of this library for our upcoming and future Production Application builds.

**Comment by navyasric** [comment]
@mmushatt Thanks for the feedback and interest in the library. We are working on the plans for GA but do not have a timeline to share yet.

**Comment by navyasric** [comment]
Closing this issue as it is more of a question. Please watch the repo(Readme, etc) for the updates about GA in future.
