### ISSUE TITLE
Option to make cookies httpOnly and Secure

### ISSUE THREAD

**Issue by collegewap** [AzureAD/microsoft-authentication-library-for-js#2854]
## Library

- [ ] `msal@1.3.2` 
## Framework

- [ ] React 16.13.1

## Description
There is no option to make cookies httpOnly and Secure. When we run the Pen Test report, we get errors for the same.

## Error Message
![image](https://user-images.githubusercontent.com/9767383/104181837-72be3500-5435-11eb-8d6c-10a89edafdfd.png)

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.

export const config = {
  authority: "https://login.microsoftonline.com/xxx",
  clientId: process.env.REACT_APP_CLIENT_ID,
  redirectUri: window.location.origin + "/auth.html",
  postLogoutRedirectUri: window.location.origin,
  scopes: ["https://graph.microsoft.com/User.Read", 'https://graph.microsoft.com/OnlineMeetings.ReadWrite']
};

```

## Expected behavior
Cookies should be set as httpOnly and secure.

## Identity Provider

- [ ] Azure AD

## Browsers/Environment

- [ ] Chrome

## Security

- [ ] Is this issue security related?: Yes

**Comment by jo-arroyo** [comment]
@collegewap HttpOnly will not work, as cookies are read and written from JavaScript. We will look into setting the secure flag.
