### ISSUE TITLE
React loginRedirect() doesn't return a response object for a handleRedirectPromise

### ISSUE THREAD

**Issue by visualjeff** [AzureAD/microsoft-authentication-library-for-js#2857]
## Library
```
"@azure/msal-browser": "^2.8.0",
"@azure/msal-react": "^1.0.0-alpha.1",
```

## Framework
```
React 16.13.1
Gatsby 2.29.2
```

## Description
According to the documentation loginRedirect doesn't receive a response object for a handleRedirectPromise.  

## Error Message
No error message

## MSAL Configuration

```js
const configuration = {
  auth: {
    clientId,
    authority,
    redirectUri,
  },
  system: {
    loggerOptions: {
      loggerCallback: (level, message, containsPii) => {
        if (containsPii) {
          return;
        }
        /* eslint-disable default-case */
        switch (level) {
          case LogLevel.Error:
            console.error(message);
            return;
          case LogLevel.Info:
            console.info(message);
            return;
          case LogLevel.Verbose:
            console.debug(message);
            return;
          case LogLevel.Warning:
            console.warn(message);
            
          /* eslint-enable default-case */
        }
      },
      piiLoggingEnabled: false,
    },
  },
};
```

## Reproduction steps

```js
  function handleResponse(resp) {
      if (resp !== null) {
        setHomeAccountId(resp.account.homeAccountId); // alternatively: resp.account.homehomeAccountId or resp.account.username
      } else {
        const currentAccounts = msalInstance.getAllAccounts();
        if (!currentAccounts || currentAccounts.length < 1) {
          // No cached accounts
          return;
        } else if (currentAccounts.length > 1) {
          // Multiple account scenario
          // Add account selection code here
          // TODO: homeAccountId = ...
          return;
        } else if (currentAccounts.length === 1) {
          setHomeAccountId(currentAccounts[0].homeAccountId); // Single account scenario
        }
      }
    };

    const login = () => {
      msalInstance.loginRedirect().then(resp => handleResponse(resp));
    };
```

## Expected behavior
Callback should be invoked so can get access to the homeAccountId.

## Identity Provider
Azure AD

## Browsers/Environment
Chrome

## Regression
Authentication works fine.  Getting access token works too.  But first time trying to getting homeAccountId and it doesn't seem to work.  **BTW, there is a typo in the documentation on Github.  homehomeAccountId I believe should be homeAccountId.**

Version:
?

## Security
No

## Source
Customer request

**Comment by visualjeff** [comment]
This is the page I'm looking at for reference:
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/accounts.md

**Comment by visualjeff** [comment]
Sorry for any confusion. What I'm getting at is how can I get homeAccountId after performing a loginRedirect?   acquireTokenRedirect isn't what I really want to do.

**Comment by tnorling** [comment]
@visualjeff `loginRedirect` will never resolve because it will invoke a full frame redirect. When using `msal-react` there are a couple ways you can get the response or `homeAccountId` after returning from the redirect. 

1. If you just need `homeAccountId` you can call `msalInstance.getAllAccounts()`
2. If you need the full response you should use `msalInstance.addEventCallback()` to register your `handleResponse` function on the `LOGIN_SUCCESS` or `ACQUIRE_TOKEN_SUCCESS` events. For example:

```javascript
const callbackId = msalInstance.addEventCallback(message => {
    switch (message.eventType) {
        Case EventType.LOGIN_SUCCESS:
        Case EventType.ACQUIRE_TOKEN_SUCCESS:
            if (message.interactionType === InteractionType.Redirect) {
                handleResponse(message.payload);
            }
    }
});
```

You can take a look at our [gatsby sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/gatsby-sample) which does demonstrate the redirect flow.

**Comment by visualjeff** [comment]
Thank you for the response and your time!

Jeff
