### ISSUE TITLE
BrowserAuthError: interaction_in_progress: Interaction is currently in progress. 

### ISSUE THREAD

**Issue by anandk95** [AzureAD/microsoft-authentication-library-for-js#2858]
We are trying to integrate our chat widget in 3rd party website, where the user will login using Azure AD credentials. we need to fetch email of the logged in user into our widget, for which we are using "\me" graph api. So, when we are tring to login through our widget, we are getting the following error.

Error: Uncaught (in promise): BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API. BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API. at t [as constructor] (chat-widget.js:1315) at new t (chat-widget.js:1315) at Function.t.createInteractionInProgressError (chat-widget.js:1315) at t.e.preflightInteractiveRequest.

**Comment by jo-arroyo** [comment]
@anandk95 Please fill out one of our [pre-configured issue templates](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/new/choose), as we need a bit more information to address your issue. Thank you!
