### ISSUE TITLE
No possibility to set responseType to 'code' in loginPopup

### ISSUE THREAD

**Issue by JerryDoubleU** [AzureAD/microsoft-authentication-library-for-js#286]
I wanted to use the MSAL to let the web app get an authorization code for the backend server. To do that, I need to set the response_type parameter to 'code'. It is not possible with the current MSAL implementation. If I add this to extraQueryParameters, there would be a duplicate key error.

**Comment by spottedmahn** [comment]
That would be a security issue; it would be **insecure**.

What are you trying to achieve?

**Comment by JerryDoubleU** [comment]
I have a dashboard page, where I setup the account, and then the data would be fetched by a C# server.
It's a scheme/flow described in both Microsoft and Google docs, where you fetch authorization code on the frontend and the process is continued on the backend server.

**Comment by rohitnarula7176** [comment]
@JerryDoubleU By design, we do not support responseType = 'code' . The library supports only implicit flow with responseType='token' or id_token'. Closing this issue.
