### ISSUE TITLE
While implementing the OAuth 2.0 authorization code flow with PKCE, Accesstoken is not returned, but if manually calls  acquireTokenRedirect 2 times, it will return accesstoken

### ISSUE THREAD

**Issue by faiyazAbdul** [AzureAD/microsoft-authentication-library-for-js#2860]
## Library

- [ ] `@azure/msal-browser@2.x.x`

## Framework

- [ ] ReactJs

## Description

We are in progress of implementing the OAuth 2.0 authorization code flow with PKCE in our website using JS-MSAL 2.0.

But when we authenticate, the access token is not returned in the response. After doing multiple calls manually, we see the access token returning in the response.

In the first call  signIn (loginRedirect),  i am getting **Authorization Code**, and after that **/token API** is getting called and invoking HandleRedirectResponse with a response ( accountId and IDToken details)  but no accesstoken.

then i am calling   **acquireTokenSilent** with request ( scope and accountInfo ) stills returns response with empty accessToken.

again if i am calling **acquireTokenRedirect** then it returns accessToken.

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```
//azureService is service file which i created
```js
azureService.msalConfig = {
  auth: {
    clientId,
    authority : https://xyz.b2clogin.com/xyz.onmicrosoft.com/B2C_1A_signup_signin,
    knownAuthorities : [https://xyz.b2clogin.com/xyz.onmicrosoft.com/B2C_1A_signup_signin]
    redirectUri,
    scope : ["read","offline_access","https://xyz.onmicrosoft.com/api/read"]
  }
};

  azureService.msalInstance = new PublicClientApplication( azureService.msalConfig );

  azureService.msalInstance.handleRedirectPromise().then(authResult => {
    azureService.HandleRedirectResponse(authResult);
  });

  azureService.msalInstance.loginRedirect(loginRedirectRequestPayload);

azureService.HandleRedirectResponse = authResult => {
  if (authResult !== null) {
    azureService.account =  authResult ? authResult.account : azureService.msalInstance.getAllAccounts()[0];
       azureService.accquireToken(azureService.account);
    }
};

azureService.accquireToken =  account => {
  var request = {
    scopes: ["scopes"],
    account: account,
  };

  azureService.msalInstance.acquireTokenSilent(request)
    .then(tokenResponse => {

        // here I am getting response but without access token

        // if i call again then i will get access token
      if(!tokenResponse.accessToken){
        return azureService.msalInstance.acquireTokenRedirect(request);
      }
   
    })
    .catch(async error => {
      if (error instanceof InteractionRequiredAuthError) {
        // fallback to interaction when silent call fails
        return azureService.msalInstance.acquireTokenRedirect(request);
      }
    })
    .catch(error => {
      console.log(error);
    });
};
```
## Reproduction steps

```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Expected behavior

once successful signing, it should return a accesstoken in response but receiving empty accesstoken.

## Identity Provider

- [ ] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [ ] Chrome
- [ ] Firefox
- [ ] Safari

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by jo-arroyo** [comment]
@faiyazAbdul Please provide the configuration and your usage, as we need a little more information. Thank you!

**Comment by faiyazAbdul** [comment]
@jo-arroyo  Edited the issue, added configurations. Thank you!

**Comment by jo-arroyo** [comment]
@faiyazAbdul Can you please provide your configuration, the scopes you are using, and a fiddler trace? That would help a lot. You can send the fiddler trace to my email.

**Comment by faiyazAbdul** [comment]
Updated the  configurations,  the scenarios is After calling  **loginRedirect()** method, it successfully redirects to our custom login screen, then after entering credentials, it returns to our site with **code** & **state**  in the url as a params. then its internally calls /token url which returns
response object  with account, idtoken, idtokenClaims etc but without access_token, then again if i call **acquireTokenSilent()**, it will return same object, then again if i call **acquireTokenRedirect()** now it returns Access_token.
is this the correct way?

**Comment by jo-arroyo** [comment]
@faiyazAbdul Thanks for the update. Can you please send a fiddler trace to my email? It is in my profile. Thanks.

**Comment by faiyazAbdul** [comment]
Sorry, not able to create fiddler trace.  
Do we need to call  **acquireTokenSilent** method  to get access token, every time before calling API's, as we have to call more than 10 apis on dashboard.
getting issues while page reload, is there any callback in MSAL  to capture  page reload and acquire Token?

**Comment by jo-arroyo** [comment]
@faiyazAbdul Yes, you should call `acquireTokenSilent` with the scopes you need before calling API's.

Can you clarify what you mean in the second question?

**Comment by faiyazAbdul** [comment]
once we reload / refresh our application, we need to call acquireTokenSilent, to get the access token, so i was asking do we have a built-In method in msal that detects page reload and get the accessToken silently. (but i figured it out.)

**Comment by faiyazAbdul** [comment]
@jo-arroyo 
After successful signing, still i need to call **acquireTokenSilent**, which will get success  response without accessToken, then need to call **acquireTokenRedirect** method which returns accessToken.
Is this the way to get accessToken.

after signIn,  in the first call to acquireTokenSilent, I am not getting accessToken, but later for consecutive calls I am getting accessToken.

**Comment by jo-arroyo** [comment]
@faiyazAbdul Unfortunately, this is a known issue with the B2C service. Your current method is our recommendation for mitigation. This will be fixed in the B2C service in the future. We can let you know when the fix has been deployed.

**Comment by nmilleson** [comment]
@jo-arroyo ,

I am facing this same issue with getting the access token.  Is there anywhere we can track the status of that issue with the B2C service?  Thanks!

**Comment by faiyazAbdul** [comment]
@jo-arroyo ,

With this issue, and also sometimes i get Interaction in progress issue, would you recommend to move for prod.

**Comment by jo-arroyo** [comment]
@nmilleson To track this issue with the B2C service, please file a support ticket with the B2C team by following the instructions here: https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options. They can help you out further, they may ask for a public repro link or additional data. You can also link this Github issue in the support request.

@faiyazAbdul Could you explain what you mean by move for prod?
