### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by johnbatty** [AzureAD/microsoft-authentication-library-for-js#2864]
## Library

- [X] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.x.x`
- [X] `@azure/msal-node@1.x.x`
- [X] `@azure/msal-react@1.x.x`
- [X] `@azure/msal-angular@0.x.x`
- [X] `@azure/msal-angular@1.x.x`
- [X] `@azure/msal-angular@2.x.x`
- [X] `@azure/msal-angularjs@1.x.x`

## Documentation location

- [ ] docs.microsoft.com
- [ ] MSAL.js Github Wiki
- [ ] README file
- [ ] Other (please fill in)
- [X] Documentation does not exist

## Description
The repo is missing a LICENSE file - please could you add one to make the licensing clear.

According to the README, the library is being made available under the MIT license, so there should be a LICENSE file containing the MIT license text.  Currently Github cannot determine the license type, whereas it can with other repos that include a LICENSE file (e.g. https://github.com/AzureAD/microsoft-authentication-library-for-go/blob/dev/LICENSE).

Many thanks!

**Comment by jasonnutter** [comment]
@johnbatty Given this is a monorepo, each of the individual folders should have LICENSE files for the respective libraries, e.g. https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/LICENSE, although I now see we are missing a couple, so I'll make sure that gets fixed. We can add one in the root of the repo as well (even though the root isn't published).

**Comment by johnbatty** [comment]
Many thanks for the quick response Jason - sounds good to me.
