### ISSUE TITLE
Edge specific issues with msal-react library.

### ISSUE THREAD

**Issue by shmehltr** [AzureAD/microsoft-authentication-library-for-js#2867]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.8.0`
- [ ] `@azure/msal-node@1.x.x`
- [x] `@azure/msal-react@1.0.0-alpha.0`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [ ] Angular
- [x] React
- [ ] Other

## Description

  We are using the msal-react library's useMsalAuthentication hook for login with the redirect flow and noticing some users having intermittent issues specifically in Edge (Chromium), the same users report they are able to use Chrome without any issues. We have been trying to learn more about the issues and get to the bottom of it and were hoping you all may have some ideas.

**No_tokens_found**
The first issue encountered was after the Authenticated template was rendered and a call was made to aquireTokenSilent() we would sometimes see a "no_tokens" error. Upon further investigation we found that the msal interaction status entry in local storage was stuck on "interaction_in_progress" and persisted even after closing the browser and reopening. The only way to clear it was to manually clear storage and refresh. I found an older issues that seemed very similar (issue #1616) that points to this being a race condition and simply awaiting handleRedirectPromise() before calling aquireTokenSilent() resolved the issue for them. I thought the react msalProvider already handled the redirect promise though and the Authenticated template was only rendered after login was complete? As a work around for the time being we are actively checking the the msal status from the useMsal hook before returning the Authenticated/Unauthenticated templates. 

**No accounts**
The other issue encountered specifically in edge is a case where msal seems to be unable to login at all or find any account following the redirect. In this case the inProgress and accounts returned from useMsal were observed. The interaction status seemed to change as expected from startup, login, handle redirect, and finally none. However the accounts returned from was empty and the Unauthenticated template was rendered. Looking at the local and session storage I did not observe any msal entries which seemed odd. I did not observe any errors or network calls failing here. In this case clearing the application storage manually and refreshing again resolved the issue.

To my knowledge we have only seen the the above issues intermittently using Edge. 

## Error Message
Uncaught (in promise) BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.

## MSAL Configuration

```js
const config: Configuration = {
  auth: {
    authority: 'https://login.microsoftonline.com/microsoft.onmicrosoft.com',
    clientId: AppId[environmentConfig.aad],
    redirectUri: window.location.origin,
    navigateToLoginRequestUrl: true,
    knownAuthorities: ['microsoft.onmicrosoft.com', 'login.microsoftonline.com'],
  },
  cache: {
    cacheLocation: 'localStorage',
    storeAuthStateInCookie: true,
  },
  system: {
    loadFrameTimeout: 10000,
    loggerOptions: {
      logLevel: LogLevel.Warning,
      loggerCallback: (level, message, containsPii) => {
        if (containsPii) {
          return;
        }
        switch (level) {
          case LogLevel.Error:
            loggerService.error({
              error: new Error(`Authentication Error :: level ${level || ''} :: ${message || ''}`),
            });
            return;
          case LogLevel.Info:
            return;
          case LogLevel.Verbose:
            return;
          case LogLevel.Warning:
            loggerService.log({
              name: 'Authentication Warning',
              properties: [`level: ${level}`, `message: ${message}`],
            });
            return;
        }
      },
    },
  },
};
```

## Reproduction steps

```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Identity Provider

- [X] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [ ] Chrome
- [ ] Firefox
- [X] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [X] Did this behavior work before?
Version: msal 1.x 
This is a new issue for us since migrating from msal 1.x to msal 2.x

## Security

- [ ] Is this issue security related?

## Source

- [X] Internal (Microsoft)
- [ ] Customer request

**Comment by jasonnutter** [comment]
@tnorling Curious if #2842 will help here?

**Comment by shmehltr** [comment]
We are using redirects instead of popups but we do use local storage. Would this change apply to redirect or only popups?

**Comment by jasonnutter** [comment]
@shmehltr That PR would help popups and redirects, as it would put temporary cache values into session storage (which is not shared between tabs).

**Comment by shmehltr** [comment]
That sounds like it would certainly help for the case we had where the interaction status was hung up in local storage and required manual intervention.

**Comment by tnorling** [comment]
@shmehltr Can you try version `msal-browser@2.11.0` and let us know if this is still an issue?

**Comment by shmehltr** [comment]
thanks I am updating my packages and I will test this over the next few days.

**Comment by shmehltr** [comment]
So far so good with the updated package testing locally. I will be deploying to our test environment for further testing. I think this takes care of the problem though

**Comment by shmehltr** [comment]
Haven't seen this issue come up again since the update. Thanks so much for all the help
