### ISSUE TITLE
Not able to fetch cached users using msal-angular ^1.0.0

### ISSUE THREAD

**Issue by jerk05** [AzureAD/microsoft-authentication-library-for-js#2871]
## Library
- [ ] `@azure/msal-angular@^1.0.0`

## Description
> How to fetch logged in user from cache if user is logging in to Application1 using MSAL to sign In and there is redirection link from Application1 to Application2, where Application2 is using MSAL for authentication and I want to check authentication for user logged in in Application1 and if it fails will prompt him to login.. Basically a SSO.

The issue I'm facing here is I'm not able to get the user cached(Application1) in Application2. I'm using getAllAccounts() method.
Don't have control over Application1. Got to know from their session storage in browser about them using msal.

-->

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by jo-arroyo** [comment]
@rawl05 Are these applications on the same domain?

**Comment by rawl05** [comment]
@jo-arroyo No, these applications are on the different domain.

**Comment by jo-arroyo** [comment]
@rawl05 If two applications are on separate domains, they will have separate caches. Calling `getAllAccounts` will not return any users until the user authenticates in the second application.

**Comment by rawl05** [comment]
@jo-arroyo 1) We had one more App 3 which was able to get the same cached user through App 1 using ADAL.js. Both on different domains. So we wanted to know how can we achieve the same behaviour in msal if ADAL.js could do it(Please refere the code for ADAL.js above).

Our main question is how do we get the cached user in App 2 in msal? Is there any way in msal( like ADAL.JS method getCachedUser)?

**Comment by jo-arroyo** [comment]
@rawl05 You can use the `ssoSilent` API to SSO to an existing session that was started by another application. Note that this API requires the `login_hint` or `sid` of the account that you want to SSO to, and also requires a network request as two applications on different domains cannot share cached accounts.

**Comment by Mamta92** [comment]
@jo-arroyo We were also under the same impression that we would need login_hint or sid for SSO until we found the ability of ADAL.js to get cached users from a completely different domain. Please find the code below:-

```
export const adalConfig = {
tenant: 'xxxxx.onmicrosoft.com',
tenantId: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
clientId: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
endpoints: {
api:
'https://login.microsoftonline.com/xxxxxxxxxxxxxxxxxxxxxxxxxxxx',
},
cacheLocation: 'localStorage',
};

export const authContext = new AuthenticationContext(adalConfig);
let userInfo = authContext.getCachedUser();
```

Could you please help us out  in finding if this is possible only in ADAL.js and not msal?

**Comment by jo-arroyo** [comment]
@Mamta92 As stated above, it is not possible for MSAL.js (or ADAL.js) to read local storage data from other domains. If ADAL.js appears to be returning the same users from two different domains, it is possibly because the user authenticated in both domains.
