### ISSUE TITLE
msal-browser 2.9.0 lib not available on CDN

### ISSUE THREAD

**Issue by idri** [AzureAD/microsoft-authentication-library-for-js#2872]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework
- [x] Angular
- [x] React
- [x] Other

## Description
The CDN URL to retrieve v2.9.0 of msal-broser doesn't work:
https://alcdn.msauth.net/browser/2.9.0/js/msal-browser.min.js

## Error Message
<Error>
<Code>BlobNotFound</Code>
<Message>The specified blob does not exist. RequestId:5269ae13-701e-001c-6caf-e97348000000 Time:2021-01-13T13:24:26.5488406Z</Message>
</Error>

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps

```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Identity Provider

- [ ] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by jasonnutter** [comment]
@idri Unfortunately, there's been a delay in getting the latest build onto the CDN, I'll follow up when we have it resolved, apologies for the delay!

**Comment by jasonnutter** [comment]
The CDN build has been uploaded, apologes for the delay!

**Comment by idri** [comment]
Thank you! No worries, I just brought this up to your attention so that you know about it.
All the best.
