### ISSUE TITLE
Support API that returns whether the user's authentication status is currently being determined

### ISSUE THREAD

**Issue by Drew-Kimberly** [AzureAD/microsoft-authentication-library-for-js#2877]
## Library
- [ ] `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.9.0`
- [ ] `@azure/msal-node@1.x.x`
- [x] `@azure/msal-react@^1.0.0-alpha.2`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
I'm currently having trouble with proper gating of my application based on the user account being available in state and determined as either authenticated or unauthenticated. Using the hooks provided by this library, the unauthenticated content always renders prior to the authenticated content when a user is signed in. This can cause poor UX as the unauthenticated content is flashed to the user prior to being replaced by the authenticated content. I'm looking for an API similar to Auth0's [`isLoading`](https://auth0.com/docs/quickstart/spa/react/01-login#show-user-profile-information) so that I can gate rendering until I can guarantee the user's authentication status is determined.

Note, I did also test this against the [`fix-useMsalAuthentication`](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/2865) branch with no luck, as this might be expected behavior that has a bug instead of a new feature.

Examples of what is currently happening:
```tsx
const Content = () => {
    const isAuthenticated = useIsAuthenticated();
    return (
        <div className="App">
            {isAuthenticated ? <ProfileContent /> : <PleaseSignIn />} // PleaseSignIn always renders prior to ProfileContent when the user is authenticated
        </div>
    );
};
```
```tsx
const Content = () => {    
  return (
      <div className="App">
          <AuthenticatedTemplate>
              <ProfileContent />
          </AuthenticatedTemplate>

          <UnauthenticatedTemplate>
              <PleaseSignIn /> // Always renders prior to ProfileContent when user is authenticated
          </UnauthenticatedTemplate>
      </div>
  );
};
```
Example of desired API / behavior:
```tsx
const Content = () => {
    const { isLoading } = useMsal();
    const isAuthenticated = useIsAuthenticated();
    if (isLoading) return <Loading />;

    return (
        <div className="App">
            {isAuthenticated ? <ProfileContent /> : <PleaseSignIn />} // PleaseSignIn ONLY renders when the user is unauthenticated
        </div>
    );
};
```

## Source

- [ ] Internal (Microsoft)
- [x] Customer request

**Comment by tnorling** [comment]
@Drew-Kimberly Can you use `inProgress` returned by `useMsal`?

If you need a boolean you can do something like this: 
```js
import { useMsal, InteractionStatus } from "@azure/msal-react";

const { inProgress } = useMsal();
const isLoading = inProgresss !== InteractionStatus.None;
```

**Comment by Drew-Kimberly** [comment]
@tnorling thanks for the fast response!

Yes, you are right! I had attempted to use `inProgress` for this on @latest but did not get the expected behavior. Using `inProgress` _in combination w/ pulling in_ #2865 did the trick 👍 

As another note, `InteractionStatus` is not currently importable from the `@azure/msal-react` package.

**Comment by tnorling** [comment]
Great, thanks for confirming and thanks for pointing out the missing export. I'll make sure that gets exported in the next release. For now you should be able to use the string "none" instead.
