### ISSUE TITLE
Msal-browser: AuthenticationResult.expiresOn !== AuthenticationResult.accessToken's expiration

### ISSUE THREAD

**Issue by thoo1** [AzureAD/microsoft-authentication-library-for-js#2883]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.6.1`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
I was investigating some api errors in our app, where the service is responding with 401: ExpiredAuthenticationToken. It is saying that the token has expired. In our logs, we also log the tokenExpiry from `AuthenticationResult.expiresOn`. When I compare this with `AuthenticationResult.accessToken`'s "exp" field, I find the two values are different

When going through the method call chain, I noticed this: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/9976fa5e0e514f1429b08c83334ad810c2db87da/lib/msal-common/src/response/ResponseHandler.ts#L322, where `expiresOn` is not based on the returned `accessToken`property.

Is it expected that the `AuthenticationResult.expiresOn` is not equal to `AuthenticationResult.accessToken`'s "exp" field? I feel they should be equal

## Source
- [X] Internal (Microsoft)
- [ ] Customer request

**Comment by jo-arroyo** [comment]
@thoo1 Can you provide what the `expiresOn` and `exp` fields are? Please also provide a fiddler trace, via Teams or email. Thanks.

**Comment by thoo1** [comment]
Sure, they are from `AuthenticationResult` interface, which is returned by `PublicClientApplication.acquireTokenSilent`

`expiresOn` field: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/c6a7aada4a6644dc173b39208d5421178fa9ae78/lib/msal-common/src/response/AuthenticationResult.ts#L33
`exp` field: is from parsing `AuthenticationResult.accessToken` https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/c6a7aada4a6644dc173b39208d5421178fa9ae78/lib/msal-common/src/response/AuthenticationResult.ts#L31
- parsed by: `JSON.parse(decodeBase64(accessToken.split(".")[1]..replace(/-/g, "+").replace(/_/g, "/")))`
- the returned object has a field `exp` - this is the unix timestamp (in seconds) when the token should expire

I find that the dates represented by `expiresOn` and the accessToken's `exp` field do not match
Not really sure if this requires a fiddler trace, I think it is more a client side issue, in how we extract when the access token expires

**Comment by thoo1** [comment]
acquireTokenSilent
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/9976fa5e0e514f1429b08c83334ad810c2db87da/lib/msal-browser/src/app/PublicClientApplication.ts#L78
calls
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/9976fa5e0e514f1429b08c83334ad810c2db87da/lib/msal-common/src/client/SilentFlowClient.ts#L49
calls
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/9976fa5e0e514f1429b08c83334ad810c2db87da/lib/msal-common/src/client/SilentFlowClient.ts#L78
calls
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/9976fa5e0e514f1429b08c83334ad810c2db87da/lib/msal-common/src/response/ResponseHandler.ts#L296

It is in this function where I see that the returned `expiresOn` is not derived from the returned `accessToken`
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/9976fa5e0e514f1429b08c83334ad810c2db87da/lib/msal-common/src/response/ResponseHandler.ts#L322

I'm not very familiar with the code/reasoning for this but I think that is why the `expiresOn` and the `exp` fields are not matching

**Comment by jo-arroyo** [comment]
@thoo1 Apologies, I meant the actual values from the access token itself. Seeing the access token may be useful. However, we intentionally do not try to open the access tokens, but instead use the `expires_in` value from the server response to calculate token expiration. A fiddler trace could still be helpful in trying to figure out your issue though.

**Comment by thoo1** [comment]
I see, ok I'll send them to you on teams

**Comment by jessemartin** [comment]
Our telemetry is showing (and we've a user report of) the same issue -- `acquireTokenSilent` sometimes returns tokens whose `exp` has already elapsed, resulting in our API calls failing with 401s.

@jasonnutter and I have been chatting about this over email.

This may not be the cause of the issue, but I did notice one potentially problematic bit of `acquireTokenSilent`'s `SilentFlowClient`:
[isRefreshRequired](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/43f6d9895b4d6823b6085f118b000fbf167132e6/lib/msal-common/src/client/SilentFlowClient.ts#L64) is called before running [generateResultFromCacheRecord](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/43f6d9895b4d6823b6085f118b000fbf167132e6/lib/msal-common/src/client/SilentFlowClient.ts#L78), but generateResultFromCacheRecord is asynchronous, meaning that if the tab is sent to the background or the computer is slept, its execution could be deferred. When its execution is later resumed, the token could then be expired, but the isRefreshRequired condition has already been passed. The expired token would then be returned to the consumer and cause the issue.

**Comment by jessemartin** [comment]
After more digging, it seems there is a problem with how MSAL calculates cache entry expiration, which can cause this issue.

I've surfaced [a ticket](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2921) that describes the problem in more depth and outlines two potential solutions.

**Comment by thoo1** [comment]
@jessemartin nice find! Just for my information, I was wondering why msal does not use the "exp" field in the token but uses "expires_in" field? Is it because of clock skew, or other issues?

**Comment by jessemartin** [comment]
@thoo1 My understanding is that the server-provided `expires_in` field + a timestamp is used instead of the token's `exp` in order to avoid decoding the token, as that wouldn't work with non-JWTs or encrypted tokens. Perhaps an MSAL contributor can correct my understanding if this is incorrect :) @jo-arroyo @jasonnutter

**Comment by jasonnutter** [comment]
> @thoo1 My understanding is that the server-provided `expires_in` field + a timestamp is used instead of the token's `exp` in order to avoid decoding the token, as that wouldn't work with non-JWTs or encrypted tokens. Perhaps an MSAL contributor can correct my understanding if this is incorrect :) @jo-arroyo @jasonnutter

This is correct.

**Comment by thoo1** [comment]
thanks all! makes sense
