### ISSUE TITLE
Making multiple calls to acquireTokenSilent, may result in multiple requests to service POST /token, is there a way to use whichever request succeeded?

### ISSUE THREAD

**Issue by thoo1** [AzureAD/microsoft-authentication-library-for-js#2884]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.6.1`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Currently in our app, we make a call to `acquireTokenSilent` before any api request. We can make api requests in parallel which result in parallel calls to `acquireTokenSilent`. 
When needed, `acquireTokenSilent` will make network calls to POST /token to get a new token. Currently this results in multiple calls to POST /token.

In some of our logs, we see that one or two of them will fail with status code 0: Failed to fetch.
1. I'm not sure why status code 0 is happening for some requests, but other requests succeed
2. In the same batch of parallel requests to POST /token, if only 1 fails, does the library return the result of any previously successful request?
3. For example say request A and request B both start at the same time. Request A succeeds first, and then request B fails. Can the `acquireTokenSilent` method return the result of request A for both calls?

## Source

- [X] Internal (Microsoft)
- [ ] Customer request

**Comment by jo-arroyo** [comment]
@thoo1 To confirm, do request A and request B have the same sets of scopes? 

MSAL 2.x doesn't have logic for sharing outgoing requests for silent calls, and makes distinct network requests. At the moment there is no way for both requests to return the result from one successful call if the requests are made in parallel.

**Comment by thoo1** [comment]
@jo-arroyo yes, it would be for the same scope.
I guess my question is more a feature ask :D, wonder if it makes sense and could be done?

**Comment by jo-arroyo** [comment]
@thoo1 That's a reasonable request and we will look into it.

**Comment by JosephThomas** [comment]
Any ETA on this issue? I believe MSAL 1.x had support for this so I was surprised this regression wasn't mentioned anywhere.

**Comment by jacknewberry** [comment]
If I understand your issue, I think I have solved this by saving the promise returned from getTokenSilently and returning this promise to the calling code rather than calling acquireTokenSilent again.

The issue presented to me as multiple "Cancelled" network requests in the Chrome dev console.

Something like:
```ts
let tokenPromise: Promise<AuthenticationResult> | null

//...
const getTokenSilent = (p) => {
  if(!tokenPromise) tokenPromise = msalInstance.acquireTokenSilent(p)
  return tokenPromise.then(response => {
    tokenPromise = null
    return response
  }
}

```

I agree it would be nicer for the library to do this, especially to take into account changes in scope and perhaps other config.

**Comment by JosephThomas** [comment]
I actually noticed this functionality was removed from the code in PR #2290

"Removes logic to attempt to reuse an iframe based on scope, in the interest of simplicity in the library."

**Comment by thoo1** [comment]
I ended up implementing it in a wrapper function like @jacknewberry did. I have some map that's keyed by the scope and authority (am I missing anything else?), and the map stores and returns any existing promise for an `acquireTokenSilent` call.
But yes, if we could have this by default in the library, that'd be much appreciated!

**Comment by jasonnutter** [comment]
Correct, it was removed because it was causing other issues. We are planning to look at readdressing this in v2.

**Comment by JWess** [comment]
I am very excited to hear this will be implemented. Hopefully soon!

**Comment by jeevanbalanmanoj** [comment]
@jasonnutter  Is this feature now available in msal browser? If multiple simultaneous aquireTokenSilent requests are made will only one result in a network call?

**Comment by jasonnutter** [comment]
> @jasonnutter Is this feature now available in msal browser? If multiple simultaneous aquireTokenSilent requests are made will only one result in a network call?

Yes, as long as those requests are for the same requests parameters. Multiple requests for different parameters (e.g. different scopes, authority) will still result in multiple network calls.
