### ISSUE TITLE
Unable to run ElectronTestApp (msal-node-samples) with Azure B2C

### ISSUE THREAD

**Issue by amrit-moomie** [AzureAD/microsoft-authentication-library-for-js#2894]
## Library

- [ ] `@azure/msal-node@1.0.0-beta.1`

## Description

I am trying to run a sample project here https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/standalone-samples/ElectronTestApp
I set up my MSAL_CONFIG configuration but when I click log in, the page fails to load and I receive a blank page. Going to the source code of the page I was able to get this code from HTML page

`<body><noscript><div id="no_js" ><div class="error_container"><div><h1>We can't sign you in</h1><p>Your browser is currently set to block JavaScript. You need to allow JavaScript to use this service.</p><p>To learn how to allow JavaScript or to find out whether your browser supports JavaScript, check the online help in your web browser.</p></div></div></div></noscript><div id="no_cookie" class="no_display"><div class="error_container"><div><h1>We can't sign you in</h1><p>Your browser is currently set to block cookies. You need to allow cookies to use this service.</p><p>Cookies are small text files stored on your computer that tell us when you're signed in. To learn how to allow cookies, check the online help in your web browser.</p></div></div></div></body>`
## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by hectormmg** [comment]
Hi @ammritt! Could you please provide your MSAL configuration so we can have a little more information and try to help you debug this?

**Comment by ammritt** [comment]
Hi @hectormmg This is a production B2C account

I am sending you an email with my MSAL Configuration

**Comment by ammritt** [comment]
Hi @hectormmg just following up to see if you have been able to reproduce my issue.

**Comment by hectormmg** [comment]
Hey @ammritt ! I haven't been able to reproduce it yet, but I'll let you know when I have more information!

**Comment by hectormmg** [comment]
@ammritt I'm able to reproduce your issue now. It seems the B2C login page requires cookies and javascript to be enabled wherever they are rendered. I've tested enabling javascript on the `BrowserWindow` object and registering the custom protocol as privileged so cookies are enabled, but no success yet. I'm investigating what other configuration changes need to be made on the sample to support that. I'll update this issue when I figure it out.

**Comment by ammritt** [comment]
hi @hectormmg 
Do you have any updates? Do you think it's an issue with the Azure B2C service or an issue with the sample app?

**Comment by hectormmg** [comment]
@ammritt apologies for the delay. I'm updating the sample to use a Popup to load the B2C login screen, given that the main window shouldn't allow the execution of external scripts. It seems for now doing auth in a second window (instead of the main application window through redirects as the sample does now) is going to be the recommended usage pattern for B2C. I'll keep investigating to make sure that's the right approach.
