### ISSUE TITLE
Refresh token is not being used

### ISSUE THREAD

**Issue by zhangxAmtrak** [AzureAD/microsoft-authentication-library-for-js#2895]
## Library
https://alcdn.msauth.net/browser/2.6.1/js/msal-browser.js

## Framework
Angular

## Description
We purposely setting access token 5 mins, refresh token 1 day and web session timeout 15mins.  After login, we are able to access APIs OK.  Idle for 5 mins.  We start to see invalid token.  We assume MSAL library will automatically exchange a new access token from refresh token.  It doesn't happen.  How can enforce the exchange occur?

## Error Message

Invalid token

## Reproduction steps

1.Go to https://aemtest.amtrak.com
2. Login with john.mem88@gmail.com/Amtrak@123
3. Check account profile, 
4. Idle for 5 mins
5. Check "Account Overview", "Invalid Token" appears

## Expected behavior
MSAL library exchanges new access token using refresh token before sending to API calls

## Identity Provider

- [ ] Azure AD
- [ ] Azure B2C Basic Policy
- [x] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment
Chrome

## Regression

This is our first implementation

## Security

No

## Source

Custom Request

**Comment by jo-arroyo** [comment]
@zhangxAmtrak Can you please provide your configuration and usage?

**Comment by deepti1805** [comment]
@jo-arroyo  on behalf of @zhangxAmtrak  I am providing you the configuration. Please find the below configuration for sign in and check if that will be enough for refresh token scenario ?

    const msalConfigSignInSignUp = {
        auth: {
            clientId: clientId,
            authority: b2cPolicies.authorities.signUpSignIn.authority,
            validateAuthority: false,
            knownAuthorities: [b2cPolicies.authorityDomain],
            redirectUri:signInRedirectValue,
            postLogoutRedirectUri: logOutRedirectValue
        },
        cache: {
            cacheLocation: "localStorage",
            storeAuthStateInCookie: false
        }
    };

    const loginRequest = {
        scopes: [openid offline_access email profile https://amtrakb2ctst.onmicrosoft.com/api/profile.readwrite],
        extraQueryParameters: { ui_locales: 'en' }
    };

    const tokenRequest = {
        scopes: [openid offline_access email profile https://amtrakb2ctst.onmicrosoft.com/api/profile.readwrite],
        forceRefresh: false,
    };

**Comment by jo-arroyo** [comment]
@deepti1805 @zhangxAmtrak While you can request all the scopes in your login scopes, you will need to separate your scopes for the acquire token calls. The Graph scopes (openid, profile, etc) should be in a separate token request from the `https://amtrakb2ctst.onmicrosoft.com/api/profile.readwrite` scope. Please give that a try.
