### ISSUE TITLE
When using @azure/msal-angula 2.0.0-alpha.3, I get this error message on ClientAuthError: state_not_found: State not found

### ISSUE THREAD

**Issue by jitendraP-ashutec** [AzureAD/microsoft-authentication-library-for-js#2896]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [X] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

I'm developing an using @azure/msal-browser 2.9.0 on http://localhost using Angular, when trying to login via msal.loginRedirect() the browser reruns to the site, and correct page however the user is not logged in and the following error is in the console (from the handleRedirectObservable method) ClientAuthError: state_not_found: State not found:  Cached State
## Source

``` 
export function MSALInstanceFactory(): IPublicClientApplication {
  return new PublicClientApplication({
    auth: {
      clientId: 'clientId',
      authority: 'authority',
      redirectUri: 'http://localhost:4200',
      postLogoutRedirectUri: 'http://localhost:4200',
      knownAuthorities: ['knownAuthorities.b2clogin.com',
      'knownAuthorities.onmicrosoft.com'],
      navigateToLoginRequestUrl:true
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE, // set to true for IE 11
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Info,
        piiLoggingEnabled: false
      }
    }
  });
}

  this.msal.handleRedirectObservable().subscribe({
      next: (result: AuthenticationResult) => {
        console.error('result called', result);
        if (result) {
          // this.authService.instance.setActiveAccount(result.account);
          console.log(result);
        }
      },
      error: (error) => console.log(error)
    });


```

**Comment by jitendraP-ashutec** [comment]
@jo-arroyo 

Some how error is not display now but I am getting accessToken null  after login. I am using B2C for login. Does I need to do other settings to get accessToken ?

**Comment by jo-arroyo** [comment]
@jitendraP-ashutec Can you clarify where you are calling handleRedirectObservable above?

**Comment by jitendraP-ashutec** [comment]
@jo-arroyo Thanks for reply.

Yes I am calling handleRedirectObservable in app.component.

I have written below code in ngOnInit in msal 1.0:

```
 this.isAuthenticated = !!this.msal.getAccount();
    if (!this.isAuthenticated) {
      if (!this.msal.getLoginInProgress()) {
        this.handleLoginRedirect();
      }
    }
```
Here I am checking if is no Authenticated then check if he is not in login progress then handleLoginRedirect will call.

Is there getLoginInProgress method exist in msal 2.0 ?

**Comment by jitendraP-ashutec** [comment]
@jo-arroyo  for now I have get status from local storage which is maintain by msal. 

``` msal.${ClientId}.interaction.status ```

**Comment by jo-arroyo** [comment]
@jitendraP-ashutec Is `handleLoginRedirect` just calling `loginRedirect`?

The method `getLoginInProgress` currently does not exist in MSAL 2.x.

**Comment by jo-arroyo** [comment]
@jitendraP-ashutec The latest versions of msal-browser and msal-angular were released last night. This new version has guidance on using redirects, as well as a new `inProgress$` observable that you can subscribe to, to ensure no interactions are in progress when you check for accounts. Please update using `npm install @azure/msal-browser@2.11.0 @azure/msal-angular@alpha` and give the new version a try. You can find documentation on `inProgress$` [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/events.md#the-inprogress-observable).

**Comment by jitendraP-ashutec** [comment]
@jo-arroyo  Thanks for updates.

**Comment by pkanher617** [comment]
@jitendraP-ashutec Are you still seeing issues with this in the latest version of msal-angular?
