### ISSUE TITLE
no_cached_authority_error: No cached authority found.

### ISSUE THREAD

**Issue by hrc7505** [AzureAD/microsoft-authentication-library-for-js#2897]
## Library

- [x] `@azure/msal-browser@2.9.0`

## Framework

- [x] React@16.8.0

## Description
I am working on one application and using auth code flow there. I have two policies there; one is for signup-signin and the second is for password-reset. Handling password reset using the error code "AADB2C90118". 

On the password reset page, we have a button called back to sign in. This page is an HTML page and coming from azure-portal(aadhtmlbetacontent | Storage Explorer).  I am adding the "Back to sign in" DOM element using the Javascript on the page(not available as default so). By clicking on this link, I am running a signup-signin policy to navigate to a sign-in page. And it is working fine. But when I am clicking on forgot password link of the login page it is giving an error.
## Error Message

no_cached_authority_error: No cached authority found.
## MSAL Configuration

```js
const msalConfig: Configuration = {
  auth: {
    knownAuthorities: [policies.signUpSignInAuthority],
    clientId: authConstants.clientId,
    authority: policies.signUpSignInAuthority,
    navigateToLoginRequestUrl: false,
  },
  cache: {
    cacheLocation: BrowserCacheLocation.SessionStorage,
    storeAuthStateInCookie: false,
  },
};
```

## Reproduction steps
1. http://localhost:3000 (will run signup-signin policy and display login page)
2. Click on _Forgot password_ link(will run password-reset policy)
3. Click on "Back to sign in" link(will run signup-signin policy and display login page)
4. Click on _Forgot password_ link(will run password-reset policy) - _**This should run the password-reset policy but giving an error**_

Showing code to handle the authentication process.
```
const FORGOT_PASSWORD_CODE = "AADB2C90118";
const msalObj = new Msal.PublicClientApplication(msalConfig);
const loginRequest: RedirectRequest = {
    scopes: authConstants.scopes,
};

const forgotPasswordRequest: RedirectRequest = {
    scopes: authConstants.scopes,
    authority: policies.forgotPasswordAuthority,
};

async function loadAuthModule(): Promise<void> {
    try {
        const response = await msalObj.handleRedirectPromise();
        if (response) {
            handleResponse(response);
        } else {
            signIn();
        }
    } catch (error) {
        // Error handling
        if (error) {
            const err = error as { errorMessage: string; errorCode: string };
            // Check for forgot password error
            if (err.errorMessage.search(FORGOT_PASSWORD_CODE) > -1) {
                forgotPassword();
            }
        }
    }
}

function signIn(): void {
    void msalObj.loginRedirect(loginRequest);
}

function forgotPassword(): void {
    void msalObj.loginRedirect(forgotPasswordRequest);
}
```
## Expected behavior
Should show the password reset page.
## Identity Provider

- [ ] Azure B2C Custom Policy

## Browsers/Environment

- [ ] Chrome

## Regression

- [ ] Did this behavior work before?
Version: 2.7.0 - No, before it was giving an error of _`state_not_found`_. After upgrading the package it is giving this error.
## Security

- [ ] Is this issue security related?
No
## Source

- [ ] Customer request

**Comment by jo-arroyo** [comment]
@tnorling Do you have any insight?

**Comment by tnorling** [comment]
@hrc7505 Changing your policy outside the context of MSAL is not currently supported. What's happening under the hood is: 

1. Go to SignIn Policy
2. Click Password Reset
3. Go back to app which catches error and msal redirects to Password Reset policy
4. Click go to SignIn Policy
5. Click Password Reset
6. Go back to app and now msal breaks because it last made a request to Password Reset policy but just received a response from SignIn policy.

In step 4 above you should instead return to the app with an error which your app can catch and redirect back to the SignIn policy. Msal validates all responses against what it requested. If it receives a response that is unexpected or conflicts with the request it made you will get an error such as the one you're experiencing.

**Comment by hrc7505** [comment]
@tnorling Thank you for the quick reply.

Now I am using the cancel button click event for the "Back to sign in" link. It will redirect to the app with an error code and I am handling that error code to navigate on the login page by running the signup-signin policy. It is working fine.

**Comment by tnorling** [comment]
Great thanks for confirming! Closing as answered, please open a new issue if you have further questions.
