### ISSUE TITLE
MSAL 2.0, msal-browser 2.9.0, PublicClientApplication is not implementing setActiveAccount and getActiveAccount methods from interface IPublicClientApplication

### ISSUE THREAD

**Issue by Hamedfal** [AzureAD/microsoft-authentication-library-for-js#2900]
## Library

- [ ] `@azure/msal-browser@2.9.0`
- [ ] `@azure/msal-angular@2.0.0-alpha.3`

## Framework
- [ ] Angular

## Description
Recent update of msal-browser (2.9.0) fixed could of errors, but is missing the implementation of setActiveAccount and getActiveAccount methods.

## Identity Provider

- [x] Azure AD
- [x] Azure B2C Custom Policy

## Browsers/Environment

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by zebslc** [comment]
This occurs within the angular samples too.  To replicate just clone the angular 10 or 11 projects in https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular11-sample-app then run `npm i` and look at `home.component.ts` which shows the following.

![image](https://user-images.githubusercontent.com/3459059/105076848-88f67180-5a83-11eb-8a1c-0870d5a04547.png)

**Comment by jo-arroyo** [comment]
@Hamedfal @zebslc Can you try reinstalling `npm install @azure/msal-browser @azure/msal-angular`. We will make sure to update our samples so this no longer occurs.

**Comment by zebslc** [comment]
Hi, this is still occurring - I uninstalled those two libraries first then re-installed and the same thing happens.  Is there an interim fix or workaround for these as currently they are both broken?  

I am trying to evaluate this library atm as MSAL 2 is recommended by your documentation here:- https://docs.microsoft.com/en-gb/azure/active-directory/develop/scenario-spa-app-registration#redirect-uri-msaljs-20-with-auth-code-flow 

![image](https://user-images.githubusercontent.com/3459059/105153049-e203eb00-5aff-11eb-8255-4a294b24c518.png)

**Comment by zebslc** [comment]
Sorry, just noticed you had the PR there too so I have manually incorporated those changes in my sample :-)

**Comment by Hamedfal** [comment]
> @Hamedfal @zebslc Can you try reinstalling `npm install @azure/msal-browser @azure/msal-angular`. We will make sure to update our samples so this no longer occurs.

Thank you very much. It is working now.

**Comment by Hamedfal** [comment]
issue resolved
