### ISSUE TITLE
monitor_window_timeout error when multiple tokens are fetched after the refresh token is expired.

### ISSUE THREAD

**Issue by sharmar999** [AzureAD/microsoft-authentication-library-for-js#2901]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

Hi everyone, we recently moved to Production with MSAL 😄 with really happy results. 

One issue that we are seeing is related to long lived sessions. We fetch a total of 3 tokens in parallel (using a simple `Promise.all()`) and we have a background job that refreshes all the tokens when they expire. All of the token fetches use `acquireTokenSilent` API. 

After the refresh token expires (i.e after 24 hours+) , when the refresh job runs, we see that at least one of the tokens is failing with `monitor_window_timeout` errorCode. This is only specific to the case when the refresh token has expired. 

I am guessing since we are fetching 3 tokens parallely, 3 iFrames may have been spawned, so we are thinking of switching to a 1 + 2 token fetch strategy so that only one iFrame will be spawned. 

Would love to hear your thoughts on this. 
I am not sure if this was a bug, wanted to confirm the same.

Thanks!
## Source

- [x] Internal (Microsoft)
- [ ] Customer request

**Comment by jo-arroyo** [comment]
@sharmar999 Can you confirm what version of msal-browser you are using? Could you also share your configuration and usage of `acquireTokenSilent` with `Promise.all()` as well?

**Comment by sharmar999** [comment]
`"@azure/msal-browser": "2.8.0"`

Configuration

```javascript
  return {
    auth: {
      clientId: clientId, // from config
      authority: 'https://login.microsoftonline.com/common',
      redirectUri: CALLBACK_URL, // from config
      navigateToLoginRequestUrl : false
    },
    cache: {
      cacheLocation: 'localStorage',
      storeAuthStateInCookie: true,
    },
    system: {
      loggerOptions: {
        loggerCallback: (level, message, containsPii) => {
            // logs   
        },
      },
      windowHashTimeout: 30000,
      iframeHashTimeout: 30000,
    },
  }
```

acquireTokenSilent calls

```javascript
const silentRequest1 = { forceRefresh: true, scopes: []} // scopes are intentionally left blank here

```

**Comment by sharmar999** [comment]
`"@azure/msal-browser": "2.8.0"`

Configuration

```javascript
  return {
    auth: {
      clientId: clientId, // from config
      authority: 'https://login.microsoftonline.com/common',
      redirectUri: CALLBACK_URL, // from config
      navigateToLoginRequestUrl : false
    },
    cache: {
      cacheLocation: 'localStorage',
      storeAuthStateInCookie: true,
    },
    system: {
      loggerOptions: {
        loggerCallback: (level, message, containsPii) => {
            // logs   
        },
      },
      windowHashTimeout: 30000,
      iframeHashTimeout: 30000,
    },
  }
```

acquireTokenSilent calls

```javascript
    const silentRequest1 = { forceRefresh: true, account: {}, scopes: [] } // scopes/account are intentionally left blank here
    const silentRequest2 = { forceRefresh: true, account: {}, scopes: [] } // scopes/account are intentionally left blank here
    const silentRequest3 = { forceRefresh: true, account: {}, scopes: [] } // scopes/account are intentionally left blank here

    Promise.all([
      myMSALObj.acquireTokenSilent(silentRequest1),
      myMSALObj.acquireTokenSilent(silentRequest2),
      myMSALObj.acquireTokenSilent(silentRequest3)
    ]).then(([token1, token2, token3]) => {
      // handle tokens
    }).catch(err => {
     // fallback to acquireTokenRedirect or login 
    })
```

**Comment by jo-arroyo** [comment]
@sharmar999 Thanks for that. Could you also send us a fiddler trace? Either on teams or to my email which is in my profile. Thank you.

**Comment by sharmar999** [comment]
Thank you @jo-arroyo 
also is there a way to simulate refresh token expiry? 
Its not always reproducible for me, so I don't want to wait for 24 hours to try it again.

**Comment by jo-arroyo** [comment]
@sharmar999 You could try manually deleting the refresh token from your cache, which would trigger MSAL to get a new refresh token.

**Comment by sharmar999** [comment]
Deleting the refresh token produces the following error on token refresh.  
```js
{"errorCode":"no_tokens_found","errorMessage":"No tokens were found for the given scopes, and no authorization code was passed to acquireToken. You must retrieve an authorization code before making a call to acquireToken().","subError":"","name":"ClientAuthError"}
```

**Comment by sharmar999** [comment]
Hey @jo-arroyo 
We have implemented a 1 + 2 token fetch with retries. Will update with the results in a week.

Just for my understanding, I had a question.

I see that even when the refresh token is expired and an IFrame is spawned to re-authenticate the user, MSAL may return an `interaction_required` error. How is an `interaction_required` differentiated from a `monitor_window_timeout` ?
  Is it safe to assume that for the timeout, we should always fallback to a re-login?

**Comment by sharmar999** [comment]
This question is an extension of what I asked earlier. 

is there a way we can simulate token expiry for all kinds of tokens (access token, refresh token etc.)? I see an `expiresOn` and `extendedExpiresOn` property for the regular tokens (changing which seems to work) in cache but don't see one for the refresh token or the identity token.

We want to test different scenarios especially for long lived sessions, and currently we have to rely on just waiting for that period of time.

**Comment by sharmar999** [comment]
Updating on the issue
we see that retrying after we receive a `monitor_window_timeout` further throws a `no_tokens_found` error. 

Does the former error clear MSAL cache?

**Comment by pkanher617** [comment]
@sharmar999 sorry for the delay. 

> I am guessing since we are fetching 3 tokens parallely, 3 iFrames may have been spawned, so we are thinking of switching to a 1 + 2 token fetch strategy so that only one iFrame will be spawned.

I think this is a good idea, this will ensure that you will always check that a refresh token is in the cache before making calls in parallel using that refresh token. We are looking at ways to improve the experience to make concurrent `acquireTokenSilent()` calls easier to implement. 

> is there a way we can simulate token expiry for all kinds of tokens (access token, refresh token etc.)? I see an expiresOn and extendedExpiresOn property for the regular tokens (changing which seems to work) in cache but don't see one for the refresh token or the identity token.

You can do this for the id token and access token exactly as you described, by changing the `expiresOn` field. Unfortunately there is no way to do this for the refresh token. You could possibly save a refresh token value that has already expired and manually replace it in the cache. 

> I see that even when the refresh token is expired and an IFrame is spawned to re-authenticate the user, MSAL may return an interaction_required error. How is an interaction_required differentiated from a monitor_window_timeout ?
Is it safe to assume that for the timeout, we should always fallback to a re-login?

`interaction_required` means that the user's session is not valid, they have not consented to one of the scopes, or for some reason there is not enough data to complete silent sso in a hidden iframe, and it must be handled with an interactive API (redirect or popup). `monitor_window_timeout` usually means that the hidden iframe is not redirecting to the expected app, or there is some network latency causing a timeout. Falling back to interactive APIs is probably the best mitigation, but it would be good to log these errors in case you are seeing them frequently.

> we see that retrying after we receive a monitor_window_timeout further throws a no_tokens_found error.

> Does the former error clear MSAL cache?

No, this should not clear the cache of tokens that are already there.

**Comment by sharmar999** [comment]
Thank you for the response @pkanher617 

Would there be an enhancement from the MSAL team to change the `monitor_window_timeout` to `interaction_required` in the future? It seems to be more useful from a developer's perspective as the only mitigation would be to use `acquireTokenRedirect` in this case (which we already do) 

And also just to confirm, currently we are logging all the errors we get during the token fetch. Should this (`monitor_window_timeout`) not be treated as an error? (or rather, as of same category as `InteractionRequiredAuthError`)

**Comment by pkanher617** [comment]
@sharmar999 `monitor_window_timeout` usually occurs when a silent request to the iframe doesn't work due to either the server page not redirecting back to the application in the iframe (this happens when there is a problem with the authentication request) or if the iframe does not redirect in a specified amount of time. It is an unexpected error, and if it happens too frequently there is probably some other issue that is contributing to the failures. This is why I think you should log these errors and see how frequently it happens (i.e. 1% of requests?). Something else you can try is increasing the `iframeHashTimeout` in your config to see if that reduces the frequency of the timeout errors.

The `InteractionRequiredAuthError` are expected errors thrown by the server when a session is expired or consent is incomplete. Let me know if this makes sense.

**Comment by sharmar999** [comment]
@pkanher617 
We are seeing this for almost 20k users per day. 
We haven't been able to reproduce the same, and the above number is based on our logs. 

We currently have a `iframeHashTimeout` of 30000 (30 seconds). I believe this should be a big enough number.
