### ISSUE TITLE
loginPopup to B2c intermittently displays home page rather than custom policy. How would i troubleshoot this? 

### ISSUE THREAD

**Issue by dsingle** [AzureAD/microsoft-authentication-library-for-js#2905]
## Library

- [x] `@azure/msal-browser@2.x.x` 2.8.0
- [x] `@azure/msal-react@1.x.x` 1.0.0-alpha.1

## Description

How do i diagnose an issue where the login popup is not displaying my custom policy for change password but instead displays my home page (which is also the redirect url). This issue only occurs about 1 out of 10 or twenty attempts for my tester. I'm not seeing any errors in the loginPopup catch promise and popup doesn't show anything but the home page.

**Scenario**

1.  User logs in using loginPopoup using my login custom policy.
2.  After they login and the inprogress flag = "none", I call my database to see if they are required to change their password.
3. If yes, I issue a second loginPopup using my changePassword custom policy. This is the point where the popup opens but it displays my home page rather than the change password. The vast majority of the time it displays my change password page as it should.

I have my application insights instrumentation setup for my custom policies and I'm getting logs, but I'm not sure what i might need to look for. I have har files for the entire failing process. 

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by jo-arroyo** [comment]
@dsingle Can you please share your configuration and code usage for msal? A fiddler trace would also be helpful.

**Comment by dsingle** [comment]
@jo-arroyo I have included my msal instance config and the two different request configs I discussed above at the bottom of the very long comment. I have redacted some identifying information from the configs. 

Because the problem is so intermittent, I'm not sure I can get a fiddler trace of the failure. I could provide one for a successful process if you think that would help.

Below is the react code I am using to check whether the user needs to change their password and if so kickoff the change password request.
```
    //Checks whether the user needs to change their password.
    useEffect(() => {
        const account = instance.getAllAccounts()[0];
        if (account && inProgress === "none" && !isChangingPassword) {
            checkRequiredPasswordChange(account.idTokenClaims.sub)
        }
    }, [checkRequiredPasswordChange, inProgress, instance, isChangingPassword]);

    //This checks if the user needs to change their password according to the database.
    const checkRequiredPasswordChange = useCallback((userId) => {
        axiosSvc.get("Users/GetIsPasswordChangeRequired/" + userId)
            .then((resp) => {
                if (resp.data === true) {
                    //This is to give time for msal to resolve any current popup closing processing. 
                    setIsChangingPassword(true)
                    setTimeout(() => { forceChangeB2cPassword(instance) }, 2000); //timeout is  grasping at straws to fix this bug. 
                }
                else {
                    setIsChangingPassword(false)
                    setUserId(`user^${userId}`)
                }
            })
            .catch((error) => {
                setIsChangingPassword(false)
                handleException('GetIsPasswordChangeRequired',error)
            })

    }, [forceChangeB2cPassword, setUserId, instance])

    // begins the forced password change process. This is different from the voluntary password change process.
    const forceChangeB2cPassword = useCallback((instance) => {
        setIsChangingPassword(true)

        //start the change password custom policy.
        instance.loginPopup(pwChangeB2cRequest).then((response) => {
            axiosSvc.post("Users/FinishPwChange/" + response.account.idTokenClaims.sub)
                .then(() => setIsChangingPassword(false))
                .catch((error) => {handleException('finishPwChange', error)})
        })
            .catch((error) => {
                setIsChangingPassword(false)
                if (error.errorMessage && error.errorMessage.indexOf("cancelled") > -1) {
                    //Not really an error
                }
                else {
                    handleException('forceChangeB2cPassword', error)
                }
                //Logout the user they don't actually change their password.
                logout()

            })
    }, [logout])








```

**msal Instance Config**
```
export const msalB2cConfig = {
    auth: {
        clientId: process.env.REACT_APP_B2C_CLIENTID, 
        knownAuthorities: process.env.REACT_APP_B2C_KNOWN_AUTHORITIES,
        redirectUri: process.env.REACT_APP_B2C_LOGIN_REDIRECT_URL, //This is the base url for the application
           },
    cache: {
        cacheLocation: "localStorage",
        storeAuthStateInCookie: false
    }
    ,
    system: {
        loggerOptions: {
            loggerCallback: (level, message, containsPii) => {
                if (containsPii) {
                    return;
                }
                switch (level) {
                    case LogLevel.Error:
                        console.error(message);
                        return;
                    case LogLevel.Info:
                        console.info(message);
                        return;
                    case LogLevel.Verbose:
                        console.debug(message);
                        return;
                    case LogLevel.Warning:
                        console.warn(message);
                        return;
                    default:
                        console.debug(message)
                        return;
                }
            },
            logLevel: LogLevel.Verbose
        }
    }
};

```

**Request Configs**
```
export const loginB2cRequest = {
    authority: process.env.REACT_APP_B2C_SIGNIN_AUTHORITY,
    scopes: ["customScope1", "customScope2", "openid"],
    webApi: ["webapiScope"]
};


export const pwChangeB2cRequest = {
    authority: process.env.REACT_APP_B2C_CHANGEPW_AUTHORITY,
    scopes: ["customScope1", "customScope2", "openid"],
    webApi: ["webapiScope"]
};
```

**Comment by tnorling** [comment]
@dsingle I think as a first step it would be helpful if you could determine which policy is being used when the popup shows your app. If the password reset policy is being called and is redirecting you back to your app before you've had a chance to enter a new password this would be a service issue. If, however, the login policy is being called instead of the password reset policy then you'll need to do some debugging to determine why your logic is not working the way you expect.

We also typically recommend you set your `redirectUri` to a blank page that does not implement msal when using the popup or silent flows. This can prevent some unintended behavior, such as displaying your app in the popup.
