### ISSUE TITLE
Angular msal 2.0 forgot password did not work

### ISSUE THREAD

**Issue by jitendraP-ashutec** [AzureAD/microsoft-authentication-library-for-js#2906]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [x] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

 I have tried angular 11 b2c project which you provided. I have used same credentials which you provided in sample but forgot password is not working. it redirecting to login page itself.
 
 I have also tried with my credentials but it redirecting to change password instead of redirecting to forgot password.

## Source
```
 let resetPasswordFlowRequest = {
            scopes: ["openid","profile"], // I have tried with openid
    authority: environment.b2cPasswordReset,
  }
  this.msal.loginRedirect(resetPasswordFlowRequest);
```
same b2cPasswordReset url is working in msal 1.0 but not working in msal2.0

@jo-arroyo  could you please let me know if I am doing something wrong.

**Comment by jo-arroyo** [comment]
@jitendraP-ashutec Can you please share what the value of `environment.b2cPasswordReset` is?

**Comment by jitendraP-ashutec** [comment]
@jo-arroyo   Thanks For response. It was my mistake. I am passing wrong passwordReset URL.

``` 
    this.broadcastService.msalSubject$.subscribe((result: EventMessage) => {
        if (result.error instanceof AuthError){}   
     });
``` 

In Sample code you checked instanceOf AuthError but it is not working.

**Comment by jitendraP-ashutec** [comment]
I was using wrong wrong url in password resetting so that its was not working.

Thanks @jo-arroyo
