### ISSUE TITLE
Chrome extension calls the launchWebAuthFlow callback with an undefined responseUrl

### ISSUE THREAD

**Issue by ivarvh** [AzureAD/microsoft-authentication-library-for-js#2907]
I am trying to get msal to work with a chrome extension. I followed the chrome extension sample in this repo almost word for word. The only difference is that we do not use the common tenant, but our own enterprise tenant. 

I click my button in the extension popup, a new window is created and navigates to microsoft login, I fill in the e-mail, click next, it shows the loading dots and then the window closes with an error in the console:

"Unchecked runtime.lastError: Authorization page could not be loaded."

I added the redirect uri (https://<extension-id>.chromeapp.org) to the azure app registration. My manifest.json is as follows:

`{
  "name": "my extension",
  "version": "1.1",
  "description": "my extension",
  "manifest_version": 2,
  "permissions": [
    "identity",
    "identity.email",
    "activeTab",
    "tabs",
    "storage"
  ],
  "web_accessible_resources": [
    "index.html",
    "assets/*"
  ],
  "browser_action": {
    "default_popup": "index.html"
  },
  "content_scripts": [
    {
      "matches": [
        "https://*/*"
      ],
      "js": [
        "polyfills.js",
        "main.js",
        "runtime.js"
      ]
    }
  ]
}
`

The javascript code is more or less the same as the sample.

**Comment by jo-arroyo** [comment]
@ivarvh Could you please fill in one of our [pre-configured issue templates](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/new/choose)? We need a bit more information to be able to help you. Thanks.

**Comment by ivarvh** [comment]
## Library
@azure/msal-browser v2.7.0

## Description

## Error Message
`Unchecked runtime.lastError: Authorization page could not be loaded.`

## MSAL Configuration

```js
if (typeof chrome !== 'undefined' && chrome.identity) {
  redirectUri = chrome.identity.getRedirectURL();
// This redirect URI is something like https://<extension-id>.chromeapp.org
}

const msalInstance = new msal.PublicClientApplication({
  auth: {
    authority: msalConfig.authority,
    clientId: msalConfig.clientId,
    redirectUri,
    postLogoutRedirectUri: redirectUri
  },
  cache: {
    cacheLocation: 'localStorage'
  }
});
```

## Reproduction steps

```js
const signIn = async () => {
  const url = await getLoginUrl();
  result = await launchWebAuthFlow(url);
};

const getLoginUrl = async (request) => {
  return new Promise((resolve) => {
    msalInstance.loginRedirect({
      ...request,
      onRedirectNavigate: (url) => {
        resolve(url);
        return false;
      }
    });
  });
};

const launchWebAuthFlow = async (url) => {
  return new Promise((resolve, reject) => {
    chrome.identity.launchWebAuthFlow({
      interactive: true,
      url
    }, (responseUrl) => {
      // Here the responseUrl is always undefined
      if (responseUrl?.includes('#')) {
        msalInstance.handleRedirectPromise(`#${responseUrl.split('#')[1]}`)
          .then(resolve)
          .catch(reject);
      } else {
        resolve();
      }
    });
  });
};
```

## Expected behavior

## Identity Provider

- [ ] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [X] ADFS
- [ ] Other

## Browsers/Environment

- [X] Chrome (extension)
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Source

- [ ] Internal (Microsoft)
- [X ] Customer request

**Comment by jasonnutter** [comment]
@ivarvh Do you have a fiddler trace you can share? Email is in my profile, thanks!

**Comment by jasonnutter** [comment]
Also, can you provide which version of Chrome/Edge you are using?

**Comment by ivarvh** [comment]
We have discovered that it works when we turn off the corporate VPN. But I can reach the authorization page from the browser. Is there any difference between the little login window chrome creates and the browser itself?

**Comment by jasonnutter** [comment]
> We have discovered that it works when we turn off the corporate VPN. But I can reach the authorization page from the browser. Is there any difference between the little login window chrome creates and the browser itself?

Interesting, I have not heard of this issue before. Might be an issue with loading the `chromiumapp.org` domain on your vpn?

My understanding is the browser auth dialogue has its own context, meaning while it can store cookies, those cookies (and other storage) is separate from the main browser window (and gets cleared when the browser is closed).

**Comment by ivarvh** [comment]
Ok, thanks for the information. I will close this as the issue does not seem to be related to the library after all.
