### ISSUE TITLE
Additional query parameters when calling openid-configuration

### ISSUE THREAD

**Issue by AntonioRedondo** [AzureAD/microsoft-authentication-library-for-js#2909]
Hi Azure AD team,

My issue is the same than this one already closed but no solution provided:
[Is it possible to have additional query parameters when calling openid-configuration endpoint?](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1727)

I'm using `@azure/msal-browser` v2.8.0 with Microsoft Azure AD B2C as the authority. And my MSAL code is as follows:

```js
const msalInstance = new PublicClientApplication({
  auth: {
    clientId: '523c07bb-fb03-45e4-90af-f8354f4a1234',
    authority: 'https://myapp.b2clogin.com/app.mydomain/v2.0',
    knownAuthorities: ['b2clogin.com'],
    protocolMode: ProtocolMode.OIDC
})

// Somewhere in a button:
msalInstance.loginRedirect(scopes)
```

When I call `msalInstance.loginRedirect()` the browser first makes an Ajax call to the OpenID configuration end-point. The URL of this end-point is:

```
https://myapp.b2clogin.com/app.mydomain/v2.0/.well-known/openid-configuration?p=b2c_signup_signin
```

Instead the MSAL library omits/doesn't include the query parameter `p` `?p=b2c_signup_signin` and makes a call to:

```
https://myapp.b2clogin.com/app.mydomain/v2.0/.well-known/openid-configuration
```

and the server returns a 404 error.

If on the `auth` config I set `authority` to:

```js
auth: {
  authority: 'https://myapp.b2clogin.com/app.mydomain/v2.0?p=b2c_signup_signin',
  // ...
})
```

the Ajax call to the OpenID configuration end-point will be made to

```
https://myapp.b2clogin.com/app.mydomain/v2.0?p=b2c_signup_signin/.well-known/openid-configuration < Incorrect
https://myapp.b2clogin.com/app.mydomain/v2.0/.well-known/openid-configuration?p=b2c_signup_signin < Correct
```

which the response will be another 404 error.

I also tried using the [`authorityMetadata`](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/master/lib/msal-core/docs/performance.md) property:

```js
const msalInstance = new PublicClientApplication({
  auth: {
    authority: 'https://myapp.b2clogin.com/app.mydomain/v2.0?p=b2c_signup_signin',
    authorityMetadata: 'json content',
    // ...
  }
})
```

But this property just seems to be ignored, in addition to no exist on the [auth config object msal-browser source code](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/src/config/Configuration.ts#L28). Do I correctly assume `msal-browser` uses `msal-core` under the hood? Is `msal-core` the old 1.x version and instead `msal-browser` 2.x uses now `msal-common`? Is `authorityMetadata` property implemented for `msal-common`?

Is there a way to add extra params to the query? Otherwise it seems it will be impossible to use Azure AD B2C as authority? Am I missing something?

## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Source

- [ ] Internal (Microsoft)
- [x] Customer request

**Comment by AntonioRedondo** [comment]
So I see on the Dev branch the `authorityMetadata` property is added to [`Configuration.ts`](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/src/config/Configuration.ts#L28). But this change isn't merged yet to Master ([`Configuration.ts`](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/master/lib/msal-browser/src/config/Configuration.ts#L28) on Master).

Any idea when Dev is going to be merged into Master for a public release?

**Comment by tnorling** [comment]
@AntonioRedondo We do not support query parameters on the openid-configuration call. In order to support B2C you should set your authority to `https://myapp.b2clogin.com/app.mydomain/b2c_signup_signin` and remove `protocolMode` from your config. Can you let us know if that resolves this?

**Comment by AntonioRedondo** [comment]
Hey @tnorling,

Yeah, that works. Thanks! 💝
