### ISSUE TITLE
Uncorrect docs

### ISSUE THREAD

**Issue by marcosilvestroni** [AzureAD/microsoft-authentication-library-for-js#2910]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Documentation location

- [ ] docs.microsoft.com
- [ ] MSAL.js Github Wiki
- [ x] README file
- [ ] Other (please fill in)
- [ ] Documentation does not exist

## Description

The steps to provide the authentication are not completed, once I make a loginRedirect and come back to my app I've no logged users with getAllAccounts, but I'm still in_progress/pending action, I have to send acces_token to have logged my account.

**Comment by jo-arroyo** [comment]
@marcosilvestroni Can you please clarify which specific doc you are looking at?
