### ISSUE TITLE
Logout and directly redirect to AD B2C login page. Angular MSAL 2

### ISSUE THREAD

**Issue by nilsi** [AzureAD/microsoft-authentication-library-for-js#2914]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [x] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

How can I redirect to login page when logging out with MSAL angular and Azure AD B2C?

Today Im setting a postLogoutRedirectUri like this:

```
  return new PublicClientApplication({
    auth: {
      clientId: clientId,
      authority: b2cPolicies.authorities.signUpSignIn.authority,
      redirectUri: redirectUri,
      postLogoutRedirectUri: redirectUri,
      knownAuthorities: [b2cPolicies.authorityDomain]
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE, // set to true for IE 11
    },
```

The problem is that I want it to redirect to the AD login page directly without redirecting to localhost first.

So I started to construct the login URL myself but realized that it's too complex with code_challange parameters etc.

`const postLogoutRedirectUri: string = `${b2cPolicies.authorities.signUpSignIn.authority}/oauth2/v2.0/authorize?client_id=${clientId}&scope=${apiConfig.scopes}%20openid%20profile&redirect_uri=${redirectUri}&client-request-id=1bf73fe7-17f5-4b5c-ba3c-e7c59375c832&response_mode=fragment&response_type=code&x-client-SKU=msal.js.browser&x-client-VER=2.9.0&x-client-OS=&x-client-CPU=&client_info=1&code_challenge=ZQHROiwZr1-0m6jbtYgzFPysqN7cZkxiQAEZOCnI-aM&code_challenge_method=S256&nonce=123asdad-7709-4eb1-8b05-900e2e578fcc&state=eyJpZCI6Imasdqwe123123NGJjYy05OWY1LTAyYjA2YmM2YjczNyIsInRzIjoxNjExMTc3OTAzLCJtZXRhIjp7ImludGVyYWN0aW9uVHlwZSI6InJlZGlyZWN0In19`;`

It still kind of works but it feels wrong.

I either want to clear all cookies with the logout method and not redirect the user after. Then use `loginRedirct` to get the user to the right login page directly.

Or find a way to get a proper login URL and set that to postLogoutRedirectUri.

Right now:
logout clicked -> redirect azure -> redirect localhost -> MSAL guard kicks in -> azure login page shows.

I would want:
logout clicked -> azure login page shows.

**Comment by jo-arroyo** [comment]
@nilsi Unfortunately, it is not possible to set the AAD B2C Login screen as your `postLogoutRedirectUri`. Your current solution of redirecting back to the app and then redirecting to the login page would be our recommended solution.
