### ISSUE TITLE
Property 'canLoad' in type 'MsalGuard' is not assignable to the same property in base type 'CanLoad'

### ISSUE THREAD

**Issue by DrJuriko** [AzureAD/microsoft-authentication-library-for-js#2923]
Hello,

I wonder, am I the only one who have this problem?

## Library
- [x] "@azure/msal-angular": "^2.0.0-alpha.3",
- [x] "@azure/msal-browser": "^2.9.0",

## Framework
- [x] Angular
- [ ] React
- [ ] Other

## Description
Angular CLI: 9.1.13
Node: 12.18.3
OS: win32 x64

Angular: 9.1.13
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.13
@angular-devkit/build-angular      0.901.13
@angular-devkit/build-ng-packagr   0.901.13
@angular-devkit/build-optimizer    0.901.13
@angular-devkit/build-webpack      0.901.13
@angular-devkit/core               9.1.13
@angular-devkit/schematics         9.1.13
@angular/cdk                       9.2.4
@angular/material                  9.2.4
@ngtools/webpack                   9.1.13
@schematics/angular                9.1.13
@schematics/update                 0.901.13
ng-packagr                         9.1.5
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0

## Error Message

    ERROR in node_modules/@azure/msal-angular/msal.guard.d.ts:29:5 - error TS2416: Property 'canLoad' in type 'MsalGuard' is not assignable to the same property in base type 'CanLoad'.
      Type '() => Observable<boolean | UrlTree>' is not assignable to type '(route: Route, segments: UrlSegment[]) => boolean | Promise<boolean> | Observable<boolean>'.
        Type 'Observable<boolean | UrlTree>' is not assignable to type 'boolean | Promise<boolean> | Observable<boolean>'.
          Type 'Observable<boolean | UrlTree>' is not assignable to type 'Observable<boolean>'.
            Type 'boolean | UrlTree' is not assignable to type 'boolean'.
              Type 'UrlTree' is not assignable to type 'boolean'.
    
    29     canLoad(): Observable<boolean | UrlTree>;

## Reproduction steps
I just tried to serve my test app:

ng serve my-app

The same behavior for build. Also I tried to remove completely @azure folder from node_modules and install it again, the same problem. If I correct msal.guard.d.ts, it works and compiles fine:

    // canLoad(): Observable<boolean | UrlTree>;
    canLoad(): Observable<boolean> | Promise<boolean> | boolean;

## Expected behavior
A project should be compiled without errors.

## Identity Provider
- [X] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Source
- [ ] Internal (Microsoft)
- [X] Customer request

**Comment by jo-arroyo** [comment]
@DrJuriko Unfortunately, this is a known issue that we are investigating. Angular 9 `canLoad`'s return type does not include `UrlTree`, which can be returned in Angular 10 onwards. We will add it as a known issue to our docs while it is being fixed.

**Comment by jo-arroyo** [comment]
@DrJuriko The latest versions of msal-browser and msal-angular were released last night and contains the fix for this issue. Please update using `npm install @azure/msal-browser@2.11.0 @azure/msal-angular@alpha` and give the new version a try.

**Comment by DrJuriko** [comment]
Thank you, already did it, everything is fine!
