### ISSUE TITLE
msal-react acquiring tokens prior to API calls

### ISSUE THREAD

**Issue by richardrobberse** [AzureAD/microsoft-authentication-library-for-js#2927]
## Library
- [X] `@azure/msal-react@1.0.0-alpha.3`

## Description
I'm facing some issues with the way tokens have to be acquired in msal-react.

In short: I have all my async data fetch logic written in Redux actions (thunks to be more precise), my components only dispatch actions to trigger the data fetch and the data flows in once it's retrieved from the server.
Those async actions require a valid access token and as stated in the docs I should retrieve a fresh token for every API call, meaning that I'd have to bloat every component with access token logic and pass the the token to the action that fetches the data.
I could put this logic in a hook and call the hook in every component, but the logic that acquires the token (`IPublicClientApplication.acquireTokenSilent`) is async, meaning that I'd have to return some kind of promise or state object from the hook and wait for it to complete, before I can fetch my data.

Ideally I'd like to have a valid token in my Redux store at all times and keep my components "clean" from token logic OR have the ability to retrieve a token outside of a React component (but this won't be possible since it's based on React Context)
Any ideas on how to achieve a clean and scalable solution?

Thanks in advance!

## Source

- [ ] Internal (Microsoft)
- [X] Customer request

**Comment by tnorling** [comment]
@richardrobberse I'm not familiar enough with Redux 

> I could put this logic in a hook and call the hook in every component, but the logic that acquires the token (IPublicClientApplication.acquireTokenSilent) is async, meaning that I'd have to return some kind of promise or state object from the hook and wait for it to complete, before I can fetch my data.

Every solution will require that you wait for `acquireTokenSilent` to complete before fetching your data. From a performance perspective this should not be a big deal because `acquireTokenSilent` will first attempt to retrieve a valid token from local/session/in-memory storage so in most cases the promise will resolve almost immediately. This is typically the recommended approach, can you clarify what about it does not work for you?

> have the ability to retrieve a token outside of a React component (but this won't be possible since it's based on React Context)

You actually can do this using the `PublicClientApplication` instance you pass into the `MsalProvider` or by creating a new one with the same configuration options. The only things you cannot access from outside the React Context are the components and hooks exposed by `msal-react`. For APIs like `acquireTokenSilent` and `getAllAccounts` this should be fine to do, calling login APIs outside the context, however, may lead to some issues updating state inside the context and would not be recommended.

**Comment by richardrobberse** [comment]
@tnorling 
> This is typically the recommended approach, can you clarify what about it does not work for you?

This could work for me, however, I prefer to keep this kind of repetitive logic outside of my components.

> You actually can do this using the PublicClientApplication instance you pass into the MsalProvider or by creating a new one with the same configuration options. The only things you cannot access from outside the React Context are the components and hooks exposed by msal-react. For APIs like acquireTokenSilent and getAllAccounts this should be fine to do, calling login APIs outside the context, however, may lead to some issues updating state inside the context and would not be recommended.

I already have the user logged in so this should do the job, I'll give it a shot on Monday and let you know.
I think this would be a great addition to the docs, I can provide some examples if needed.

Keep up the good work, this library makes AAD auth really easy!

**Comment by richardrobberse** [comment]
@tnorling I've removed all the access token logic from my components and created a straight-forward function that wraps `acquireTokenSilent`, which I then call before my API is called and it works as expected.

Thanks a lot for your suggestion!

Would it help if I create a PR to add this example to [Acquiring an access token](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/getting-started.md#acquiring-an-access-token)?

**Comment by janusch** [comment]
Hi,
thanks for the great work on react-msal and for posing this very common and relevant use case!

I have been wondering the exact same, though without redux in my app. It is quite common to have the api call logic outside react context or in its own hook.

From my point of view it would be a very valuable addition to react-msal to provide a utility function that is react independent and gets the current access token.

For now I will go with the approach described above (I wish it was recommended):

> You actually can do this using the PublicClientApplication instance you pass into the MsalProvider or by creating a new one with the same configuration options. The only things you cannot access from outside the React Context are the components and hooks exposed by msal-react. For APIs like acquireTokenSilent and getAllAccounts this should be fine to do, calling login APIs outside the context, however, may lead to some issues updating state inside the context and would not be recommended.



Thank you again for creating this library it will unify by being the go to library for integrating react apps with AD and alike.

**Comment by tnorling** [comment]
>From my point of view it would be a very valuable addition to react-msal to provide a utility function that is react independent and gets the current access token.

@janusch This exists today in the form of `acquireTokenSilent` on `@azure/msal-browser`. `msal-react` is just a convenience wrapper around `msal-browser` so you are free to use `msal-browser` directly inside or outside of context if you need to...with one caveat:

I do not recommend calling functions that change user state (login, logout) **outside** of context when you also have other bits of code that are using `msal-react`, which manages user state **inside** context. Acquiring an access token does not fall under "user state" and can be done with the methods available today both inside and outside context. Does that help clarify?

I'll make sure this is clarified in the docs.

**Comment by janusch** [comment]
@tnorling thank you for the reply!
It makes me confident that I am using the right approach, using `acquireTokenSilent ` for each api call no matter if I already have the token stored locally or need to fetch a fresh one.

**Comment by richardrobberse** [comment]
@janusch I use a simple wrapper around fetch that takes care of getting a fresh token for each API call, all my Redux data fetch actions call this wrapper to not duplicate the logic.
You've probably done something similar yourself, just putting it here for future reference.

**Comment by Seddy24** [comment]
@janusch I'm looking to do something similar, can you please share the method that gets a new token outside of context.

**Comment by richardrobberse** [comment]
@Seddy24 Here you go, my configuration is stored in Redux and the graphToken parameter just determines which scopes to request a token for.

`
import { Configuration, PublicClientApplication } from '@azure/msal-browser'
import { store } from 'store'

const getToken = async (graphToken: boolean = false): Promise<string> => {
  const appCfg = store.getState().app.configuration
  const cfg: Configuration = {
    auth: {
      clientId: appCfg.msalClientId,
      redirectUri: appCfg.msalRedirectUri,
    },
  }

  const pca = new PublicClientApplication(cfg)
  const accounts = pca.getAllAccounts()
  const account = accounts[0]

  const resp = await pca.acquireTokenSilent({
    scopes: graphToken ? appCfg.graphScopes : appCfg.apiScopes,
    account,
  })

  return resp.accessToken
}
`

**Comment by Seddy24** [comment]
@richardrobberse I was trying to do it with my msal-react public client instance.  Was not aware you can have multiple instances with any issues.  I guess this isn't being used as context so it does impact the provider wrapper.  Thank you for your help!

**Comment by janusch** [comment]
Hi @richardrobberse ,
my implementation looks  very similar. I just moved the `pca` instance and configuration outside the getToken helper function. And I am not using redux.

Thank you for sharing!

**Comment by richardrobberse** [comment]
@janusch You're welcome! This is also what @tnorling advised me to do so I'll revisit my code :)
