### ISSUE TITLE
Remove Build Output from Repo

### ISSUE THREAD

**Issue by spottedmahn** [AzureAD/microsoft-authentication-library-for-js#293]
Why is the build output in the repo?  Makes it very hard to read PRs.  Example #210.

- What are the real changes?
vs
- What are the build output changes (I don't care about those...)

![image](https://user-images.githubusercontent.com/14079228/39708038-120c17be-51e4-11e8-9276-853b9785fe0f.png)

![image](https://user-images.githubusercontent.com/14079228/39708578-905f3f3c-51e5-11e8-96fc-6de3e4d55972.png)

![image](https://user-images.githubusercontent.com/14079228/39708612-a275468a-51e5-11e8-9f1d-40bb18176785.png)

**Comment by spottedmahn** [comment]
https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/200

**Comment by rohitnarula7176** [comment]
@spottedmahn We are using the build output so we can refer to the files while writing dev apps for testing.

**Comment by spottedmahn** [comment]
Oh, interesting.

This is not a common practice.  I can't think of any other libraries that put their build output in their source repo.  I hope you guys re-evaluate 😜

**Comment by cicorias** [comment]
This really needs to be re-opened.  There should be no build output in the src repo. I'm struggling to understand why you need to refer to these output files for dev apps in testing?

**Comment by sameerag** [comment]
@spottedmahn we are removing /dist in the upcoming release. We are working on a strategy for /docs, and they will have to remain for some time in github.

**Comment by cicorias** [comment]
so, there's nothing wrong with the docs unless they're auto-generated. the /dist/*.js are all TSC emitted and non-sensical from a Git perspective to be within the repo.  However, they DO need to be in any NPM or other package manager assets.

The Docs imho probably are OK - unless there is a move shift all docs and the pr/change process within the repo to docs.microsoft.com

**Comment by sameerag** [comment]
@cicorias Sure. Yeah, we took some time since we were working on removing a legacy dependency on /dist in the test code. We already made the separation in our dev now and hence yes, we are on track.

For now we are stabilizing the comments to make the docs more relevant, but the strategy is evolving in parallel for the /docs.
