### ISSUE TITLE
Message: AADSTS900144: The request body must contain the following parameter: 'client_id'.

### ISSUE THREAD

**Issue by mars76** [AzureAD/microsoft-authentication-library-for-js#2932]
Hi,

  I have cloned the react-router-simple and changed the clientId in authConfig.js and when i tried to run it locally it is showing the following error:
 
  AADSTS900144: The request body must contain the following parameter: 'client_id'.

 Request Id: b727ed84-61c5-4cdb-90aa-21547b95be00
Correlation Id: 1bfbc8c4-3657-4341-8b37-3065b98616f3
Timestamp: 2021-01-23T02:48:25Z
Message: AADSTS900144: The request body must contain the following parameter: 'client_id'. 

The App is registered as SPA in Azure AD and the redirect URI is "http://localhost:3000"

Not sure why i am getting this error.

I am trying to use Authorization Code Flow. Initially i had the Implicit grant and hybrid flows turned on. I am getting the same error whether they are turned on or off.

Thanks
Sateesh

**Comment by mars76** [comment]
Library :

@azure/masl-browser: 2.10.0
@azure/msal-react: 1.0.0-alpha.3
react: 17.0.1
react-dom: 17.0.1
react-router-dom: 5.2.0
react-scripts: 4.0.1

   

Framework

React

Error Message

AADSTS900144: The request body must contain the following parameter: 'client_id'.
Security

    Is this issue security related?

Regression

    Did this behavior work before? No

MSAL Configuration

`export const msalConfig = {
    auth: {
        clientId: clientId,
        //client_id: clientId,
        redirectUri: "http://localhost:3000",
        postLogoutRedirectUri: "http://localhost:3000",
        //authority: 'https://login.microsoftonline.com/2b69d099-dc61-447b-84c8-001733d8be3a'
    }
};

// Add here scopes for id token to be used at MS Identity Platform endpoints.
export const loginRequest = {
    scopes: ["User.Read"]
};

// Add here the endpoints for MS Graph API services you would like to use.
export const graphConfig = {
    graphMeEndpoint: "https://graph.microsoft.com/v1.0/me"
};`

**Comment by tnorling** [comment]
@mars76 You have both `clientId` and `client_id` shown above. Can you confirm that you are using `clientId` (this is the correct one)?
