### ISSUE TITLE
Does MSAL-React support class components?

### ISSUE THREAD

**Issue by riktimmondal** [AzureAD/microsoft-authentication-library-for-js#2933]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [X] `@azure/msal-react@1.0.0-alpha.3`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

Am using https://www.npmjs.com/package/@azure/msal-react in my react project. The library provides hooks to perform auth very easliy.

So in functional component, for getting access token,
```
if (account && inProgress === "none") {
instance.acquireTokenSilent({
...loginRequest,
account: account
}).then((response) => {
callMsGraph(response.accessToken).then(response => setGraphData(response));
});
}
```
needs to be called where ```const { instance, accounts, inProgress } = useMsal();``` is used.

But I need to call api to fetch data from class components.
So, how to achieve the same functionality in class component
## Source

- [X] Internal (Microsoft)
- [ ] Customer request

**Comment by tnorling** [comment]
@riktimmondal When using class components you have 2 options: 

1. Use the raw context as shown [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/getting-started.md#consuming-the-raw-context)
2. Use the `withMsal` higher order component to wrap your class component and inject the context into its props. I see now that this approach has not yet been documented, I will make sure to add this to our docs.
