### ISSUE TITLE
Infinite loop for redirect

### ISSUE THREAD

**Issue by zhangxAmtrak** [AzureAD/microsoft-authentication-library-for-js#2938]
## Library
https://alcdn.msauth.net/browser/2.6.1/js/msal-browser.js
## Framework
Angular

## Description
We want to implement a static enrollment URL to be imbedded in email to send to customers.  We use on page load to invoke msal library for signup policy.  But we end up infinite loop instead of going back to home page.  Here is the example of static page

https://aemtest.amtrak.com/guestrewards/enrollment.html

## Reproduction steps

1. Go to https://aemtest.amtrak.com/guestrewards/enrollment.html
2. Enroll with email
3. Page redirect to home but not login.  Click on "SignIN" button, it goes back to B2C when access token has been granted

## Expected behavior

User shall be signed in

## Identity Provider

- [ ] Azure B2C Custom Policy

## Browsers/Environment

 Chrome

## Regression

- [ ] Did this behavior work before? No
Version:

## Security

 Is this issue security related? No

## Source

Customer request

**Comment by jo-arroyo** [comment]
@zhangxAmtrak Could you provide us with your configuration and usage code? You could also try upgrading to the latest version of `@azure/msal-browser` which is at version 2.10.

**Comment by hectormmg** [comment]
@zhangxAmtrak we have recently released version 2.11. Could you please upgrade and tell us if that resolves your issue? Thanks.
