### ISSUE TITLE
MSAL2/Angular, B2C SSO between Apps/Apis

### ISSUE THREAD

**Issue by schokolateur** [AzureAD/microsoft-authentication-library-for-js#2939]
## Library
- [X] `@azure/msal-angular@2.0.0-alpha.3`

## Description
Hi there, 

my point is, that i have to setup a bunch of web application, each with its own api backend and all should share the login.
So i started with one angular page and .net core 3 backend. I can aquire a token and call the api. Works. I used the angular11-b2c-sample sample.

I setup a second angular page/,net core backend, i need the app to pickup the login, aquire a token with the new scope and call the api. 
From my point of understanding this should be sso stuff. But i cant get it to work. 

I am reading and reading and my level of confusion rises and i understand nothing anymore...

Is it possible? Are there samples? Could you hint me to the correct documentation?

Thank you

**Comment by jo-arroyo** [comment]
@schokolateur You can use the `ssoSilent` API to attempt to sso to an existing session. This API requires a `login_hint` (usually the user's email) which may require one application manually passing the `login_hint` to the second application, e.g. through query parameters. If you're unable to provide a `login_hint` to the second application, you will need to invoke interaction. 

We don't currently have a sample for angular or b2c specifically for ssoSilent, but you can look at the sample for msal-browser [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/3104ba876553f3cbae5d24624375e71ba895ca15/samples/msal-browser-samples/VanillaJSTestApp2.0/app/ssoSilent/auth.js#L35). We will look into adding either ssoSilent examples to our samples or documentation in the future.

**Comment by schokolateur** [comment]
@jo-arroyo Thank you very much. The login_hint was my problem, and maybe  a scope configuration problem too. Now i can call multiple apis from a page and can do the login on the second page also without another prompt.

Thanks
