### ISSUE TITLE
Question: Usage with Angular 10+

### ISSUE THREAD

**Issue by akshaybabloo** [AzureAD/microsoft-authentication-library-for-js#2950]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.x.x`
- [x] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

Will I able to use the library with Angular 11. Your documentation says that only version 2 can be used but it's in alpha. So, I was wondering how I should go about it?

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by jo-arroyo** [comment]
@akshaybabloo We would encourage you to try out our msal-angular v2 library and send us any feedback you have. We are working on it, and msal-angular v2 should be in public preview soon. 

Alternatively, you can try implementing your own version of msal inside your Angular 11 application to wrap msal-browser. While it does not have the up-to-date features that are in msal-angular v2, you can try referencing our [angular10-browser-sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular10-browser-sample), which implements msal in the application and uses msal-browser.

**Comment by akshaybabloo** [comment]
OK got it. Thanks.
