### ISSUE TITLE
msal-node sets the global axios setting rather than setting locally

### ISSUE THREAD

**Issue by jonathandturner** [AzureAD/microsoft-authentication-library-for-js#2951]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [x] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [ ] Angular
- [ ] React
- [x] Other

## Description

MSAL currently sets a global Axios setting which may impact other uses of Axios. We recently received a customer-reported issue for this on the Azure Identity repo: https://github.com/Azure/azure-sdk-for-js/issues/13343

For this to be addressed, I believe msal-node will also need to be updated:

```
lib\msal-node\src\network\HttpClient.ts
19:        axios.defaults.validateStatus = () => true;
```

This is the PR we're working on for the fix to identity: https://github.com/Azure/azure-sdk-for-js/pull/13468

**Comment by sameerag** [comment]
Yes, will address this in the next release!
