### ISSUE TITLE
interaction_in_progress when cache is enabled in Configuration

### ISSUE THREAD

**Issue by Luperi** [AzureAD/microsoft-authentication-library-for-js#2954]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [X] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [ ] Angular
- [X] React
- [ ] Other

## Description
_interaction_in_progress_ error is triggered if the cache is enabled in msal Configuration. When disabling the cache, the error does not appear.

## Error Message
`interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.`

The issue seems to be with this cookie: `msal.<my_client_id>.interaction.status = interaction.status`

## MSAL Configuration

```js
auth: {
    clientId: "<my_client_id>",
},
cache: {
    cacheLocation: 'localStorage',
    storeAuthStateInCookie: true
}
```

## Reproduction steps

1. Chechout [https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/typescript-sample](url) code
2. In _authConfig.ts_ replace _msalConfig_ with:
```
// Config object to be passed to Msal on creation
export const msalConfig: Configuration = {
    auth: {
        clientId: "<your_application_id>",
    },
    cache: {
        cacheLocation: 'localStorage',
        storeAuthStateInCookie: true
    }
};
```
3. Run the project
4. Click on _Sign in using Redirect_ button and then, instead of completing the login, in the URL bar, type the homepage URL
5. Click **again** on _Sign in using Redirect_
6. The error is shown

## Identity Provider

- [ ] Azure AD
- [X] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jo-arroyo** [comment]
@Luperi This is a known regression in `msal-browser@2.10.0` that will be fixed in the next release by the PR linked above. In the meantime, you can downgrade to version 2.9.0 or use `sessionStorage` to mitigate.

**Comment by Luperi** [comment]
Hi @jo-arroyo thanks for the reply, what is the added value of having the cache? Without the configuration, is behaving good.

**Comment by tnorling** [comment]
@Luperi When you do not provide the cache configuration explicitly it defaults to sessionStorage. If you'd like to use localStorage or in-memory storage instead you can specify that in the config. 

`msal-browser@2.11.0` was just released and contains the fix for this issue. Closing, please open a new issue if you have further questions. Thanks!
