### ISSUE TITLE
postLogoutRedirectUri does not work

### ISSUE THREAD

**Issue by k-mehta** [AzureAD/microsoft-authentication-library-for-js#2957]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.10.0`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [ ] Angular
- [x] React
- [ ] Other

## Description
I am not redirected to my postLogoutRedirectUri after invoking PublicClientApplication.logout

## MSAL Configuration
```js
const msalConfig: Configuration = {
  auth: {
    clientId: XXX,
    authority: 'https://login.microsoftonline.com/consumers/',
    postLogoutRedirectUri: `${window.location.origin}/logout`,
  },
  cache: { cacheLocation: 'localStorage' },
};
```

## Reproduction steps

```js
const account = msalApplication.current.getAccountByUsername(authData.user.email) ?? undefined;
if (account) {
  const logoutRequest: EndSessionRequest = { account };
  await msalApplication.current.logout(logoutRequest);
}
```
My App Registration on Azure has the "Front-channel logout URL" set to the same URI as postLogoutRedirectUri.

My console history shows the following navigations:

15:51:56.890 Navigated to https://login.microsoftonline.com/consumers/oauth2/v2.0/logout?post_logout_redirect_uri=XYZ&client-request-id=ABC
15:51:57.359 Navigated to https://login.microsoftonline.com/consumers/oauth2/v2.0/logoutsession

(Note: the post_logout_redirect_uri and client-request-id are actually filled out; I've just obfuscated them for this bug report)

## Expected behavior
When the user logs out, they should be taken to the postLogoutRedirectUri

## Identity Provider

- [x] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [x] Chrome
- [ ] Firefox
- [x] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

**Comment by jasonnutter** [comment]
Is your `postLogoutRedirectUri` also registered as a redirect URI for your app (in addition to front-channel logout url)?

**Comment by k-mehta** [comment]
No

**Comment by k-mehta** [comment]
Ahh, adding it to the redirect URI list fixed it, thanks!
