### ISSUE TITLE
Client Credentials Grant Type Availability Date

### ISSUE THREAD

**Issue by Zerryth** [AzureAD/microsoft-authentication-library-for-js#2958]
## Description
Simple question: **is there a release date for client credentials grant type in MSAL.js?**

___
I've tried searching the issues for "client credentials" and couldn't find anything, however directly in the [root README of the repo](https://github.com/AzureAD/microsoft-authentication-library-for-js#core-and-wrapper-libaries), you can see it says

> - Client Credential Grant (Coming soon)

There's interest on the MS Bot Framework Team to migrate from ADAL to MSAL ([botbuilder-js#2782](https://github.com/microsoft/botbuilder-js/issues/2782)), however the [framework supports client credentials flow](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-authentication?view=azure-bot-service-4.0). 

Roadmap insight regarding this feature would be appreciated 📅 ☺️

**Comment by jasonnutter** [comment]
Client credential flows are supported in MSAL Node: https://www.npmjs.com/package/@azure/msal-node

**Comment by Zerryth** [comment]
Thanks @jasonnutter . Have to discuss with the team if we want to migrate this yet on basis that the bits are still preview. Appreciate link to the sample and pointing in the right direction

**Comment by sameerag** [comment]
@Zerryth Thanks. `msal-node` will GA soon (projection is this month) and will be announced in this repo. In case you have further questions, please feel free to reach out.
