### ISSUE TITLE
RefreshToken

### ISSUE THREAD

**Issue by rnkpareek** [AzureAD/microsoft-authentication-library-for-js#2962]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

Unable to use refresh Token,
Can any one suggest how to refresh the token silently.

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by hectormmg** [comment]
Hi @rnkpareek! I took the liberty to add our Question template markdown to your issue description, could you please fill it out so we can have all the information you need to answer your question? Thanks!
