### ISSUE TITLE
msal-browser@2.10.0 loginRedirect bug

### ISSUE THREAD

**Issue by momdim** [AzureAD/microsoft-authentication-library-for-js#2966]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.10.0`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [ ] Angular
- [x] React 17
- [ ] Other

## Description
Call to loginRedirect(authority, redirectUri?) ignores the authority paramater passed to method call. Msal redirects instead to a default authority from msal configuration, but with redirectUri supplied in the method call. I am using this call to handle "forgot password" error thrown from Azure B2C (to redirect the user to reset password policy).

## MSAL Configuration

const MsalConfig = {
  auth: {
    knownAuthorities: [
      B2cPolicies.authorities.signupsignin.authority,
      B2cPolicies.authorities.passwordReset.authority
    ],
    authority: B2cPolicies.authorities.signupsignin.authority,
    clientId: #msal client id#,
    redirectUri: window.location.origin,
    validateAuthority: false
  },
  cache: {
    cacheLocation: 'localStorage',
    storeAuthStateInCookie: false
  }
};

## Reproduction steps
Set an authority url in msal config (in B2C this could be signinsignup custom policy). Then call loginRedirect by passing a different authority (we are passing a reset password B2C authority). Same code works on version 2.8.0 and MSAL redirects properly.

## Expected behavior
Msal is expected to redirect to a correct url.

## Identity Provider

- [ ] Azure AD
- [ ] Azure B2C Basic Policy
- [x] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression
Passing a different authority to loginRedirect method results in a correct redirection in version 2.8.0.
- [x] Did this behavior work before?
Version:
2.8.0

**Comment by hectormmg** [comment]
Hi, @momdim ! This is a known issue that was fixed in `v2.11`. Could you please upgrade and let us know if your issue is solved?

**Comment by momdim** [comment]
Hi Hector! Thanks for the information. I have updated to 2.11.0 and I can confirm that this bug is now gone. Thanks again! :)

**Comment by hectormmg** [comment]
Great! Thanks for the update @momdim! Closing the issue!
