### ISSUE TITLE
Handling IE11's cache-control issues

### ISSUE THREAD

**Issue by jamesots** [AzureAD/microsoft-authentication-library-for-js#2974]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.11.0`
- [ ] `@azure/msal-node@1.x.x`
- [x] `@azure/msal-react@1.0.0-alpha.4`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

We came across an interesting problem trying to use our site, msal and IE11.

We have a site which is available in two languages, so each site is on a separate subdomain. I don't want to publish the URLs here, but they're similar to lang1.web.core.windows.net and lang2.web.core.windows.net, while we're testing them. The user can click a button which redirects them to the same location on the other language site, and they should stay logged in.

On IE11 the problem is that when you're on the lang1 site, MSAL makes a request to the openid-configuration endpoint. When it comes back, it has an Access-Control-Allow-Origin header set to the lang1 domain, and a Cache-Control header set to 'private'. This should mean that when you switch to lang2 and request the config, it should re-request the config, as it's a different domain.

Unfortunately, IE11 thinks that sub-domains are the same domain for the sake of caching, so when you request the config from the lang1 domain then again from the lang2 domain, it gives you the cached version the second time. This shouldn't be a problem, as the content is identical.

Unfortunately, IE11 thinks that sub-domains are different domains for sake of CORS, and so it then rejects its own cached copy of the config.

We have got(ten) around this by passing a patched version of XhrClient in config.system.networkClient when we create the PublicClientApplication instance and the browser is IE11, which sends "Cache-Control: no-cache", "Pragma: no-cache" and "Expires: -1" headers with GET requests, which seems to do the job.

But I was wondering if I'm missing something here. And also wondering if there should be an option to do this in the library instead of having to patch it like this. I don't think you'd necessarily want to always send the cache busting headers, as caching would still be useful if you weren't using subdomains. (I'm guessing. Unless there are other IE11 issues I haven't come across yet, which is quite possible.)

## Source

- [ ] Internal (Microsoft)
- [x] Customer request

**Comment by pkanher617** [comment]
@jamesots Thanks for bringing this to our attention. Is this something you only see in IE11? As far as I can tell this is how most of the browsers work - subdomains are considered the same for caching, but different for CORS.

**Comment by liu351** [comment]
I am also seeing this issue, never noticed until yesterday. It is happening to us for IE11 only as well. Right now we have not implemented a workaround in the code except disabling all cache in ie11 to get the new request headers.

   "@azure/msal-angular": "^1.1.2",
    "msal": "^1.4.4",
    angular 9

**Comment by jamesots** [comment]
Yes, it's only in IE11 (out of the browsers I tested).

**Comment by jamesots** [comment]
Hi bot, this issue hasn't been answered or solved yet!

**Comment by jamesots-tq** [comment]
Not resolved.

**Comment by jamesots** [comment]
Not resolved.

**Comment by tnorling** [comment]
@jamesots Another potential workaround you can use instead of overriding the network client is to provide the data from the `openid-configuration` call statically to your msal config. This will skip the network call and use your provided config instead. Docs on that [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/performance.md#bypass-authority-metadata-resolution). 

Given that there are a couple workarounds and IE11 will be EOL soon we likely aren't going to spend much time, if any, investigating or attempting to find a cleaner solution to this but we are always open to contributions if you'd like to take a crack at it! In the meantime we will add a section about this to the FAQ in case anyone else runs into this.

**Comment by jasonnutter** [comment]
Reopening, will updating our list of known issues to include this.
