### ISSUE TITLE
Uncaught Promise from UserAgentApplication.aquireTokenSilent

### ISSUE THREAD

**Issue by lqdchrm** [AzureAD/microsoft-authentication-library-for-js#298]
Hi, thanks for this awesome lib!

I'm testing to integrate msal in a PWA. The problem is, when logged-in and then temporarily offline, I get an uncaught Promise, which I believe originates in UserAgentApplication.ts@line 1128:

The function aquireTokenSilent creates a new Promise((resolve, reject) => ...
So in line 1128 we probably shouldn't return a Promise, but catch possible errors and call reject...

Sorry, if my analysis is misleading, I'm relatively new to Promises... but I will try to valide and submit a PR

**Comment by rohitnarula7176** [comment]
@lqdchrm I have merged your pull request in the latest version 0.1.6 that we released yesterday. Thank you for your contribution.
