### ISSUE TITLE
With multiple accounts, user is redirected through login experience twice

### ISSUE THREAD

**Issue by 0lukasz0** [AzureAD/microsoft-authentication-library-for-js#2981]
## Library

- [x] `msal@1.4.5` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
I'm aware that there is that issue: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/842, but since it is closed and I cannot add more comments I'm creating this one with my input and my investigations.

If you are logged in two IdPs then you need to pick account twice: once for id_token then for access_token, (login hint and domain hint are not being respected)

- Azure AD B2C scenario with two external IdP
- userName field in id_token is null
- each acquire token silent call is performing new request ignoring data in cache (it can be the root cause)
- login_hint is not passed to external IdP after redirecting from our primary Azure AD instance (using domain hint)
- email claims are set in login user flow
- same behavior with both acquireTokenSilent and with acquireTokenRedirect
- providing in authentication parameters domain hint, login hint and account, also tried with either of them
- scopes for id_token are: "openid profile", for access token: read claim for API (https://mytenant.onmicrosoft.com/application_name/read)
- using MSAL v. 1.4.5, but same problem with 1.4.3

also I think there is Azure AD bug, because when I'm forwarded (with domain hint) to one of my identity providers (separate Azure AD tenants) there is a list of accounts in which I'm logged in and it is displaying accounts from both IdPs in spite of being in context of one of them. Clicking on account not associated with that IdP results in following error message: "Selected user account does not exist in tenant 'Tenant name' and cannot access the application '<guid>' in that tenant. The account needs to be added as an external user in the tenant first. Please use a different account.", which is ok, but why are accounts from different IdP displayed in each IdP? Is it "by design" or a bug?

## Error Message
"AADB2C90273: An invalid response was received: 'Error: interaction_required, Error Description: AADSTS16000: Either multiple user identities are available for the current request or selected account is not supported for the scenario.'" - both accounts are working well if you are logged just in one account so "multiple user identities are available" is a problem here.

## MSAL Configuration

scopes for id_token are: "openid profile", 
for access token: read claim for API (https://mytenant.onmicrosoft.com/application_name/read),

user flow is sign up and sign in

![Screenshot_13](https://user-images.githubusercontent.com/793789/107042835-7b9af000-67c2-11eb-9a10-82dee65fb7c4.png)

## Reproduction steps

- you need to have Azure AD B2C instance with two external IdPs
- you need to login in both IdP with two different accounts
- easiest way to do so is to use two different applications
- then clear all local site data
- try to login again to your app using one of those two accounts
- both calls loginRedirect and acquireToken will result in displaying account selection page

```js
    private async acquireToken(useRedirectFlow: boolean): Promise<any> {
   	const account = msalApp!.getAccount();
	const userEmail = account.idToken.emails[0];
		
        account.userName = userEmail;

        const tenantInfo = await LoginService.getUserTenant(userEmail);
			
	const request = {
		scopes: [
                    "https://mytenant.onmicrosoft.com/myapp/read"
                ],
		loginHint: userEmail,
		redirectUri: AppConsts.authorization.redirectUri,
		extraQueryParameters: { domain_hint: tenantInfo.domainHint }
	};
			
        const requestSilent : AuthenticationParameters = {
            ...request,
            account: account
        }

        return msalApp!.acquireTokenSilent(requestSilent)
            .catch(error => {
                if (requiresInteraction(error.errorCode + error.errorMessage)) {
                    return this.acquireTokenInteractive(request, useRedirectFlow);
                } else {
                    return Promise.reject(error);
                }
            });
    }
```

## Expected behavior
After choosing account at loginRedirec/Popup step I expect that acquireTokenSilent will use "account context" and will perform token aquisition without need to pick account for second time. 

## Identity Provider

- [ ] Azure AD <- this using as external IdP (with domain hint)
- [x] Azure B2C Basic Policy <- this using as primary IdP
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [x] Customer request

**Comment by hectormmg** [comment]
Hi @0lukasz0 , this is a known-issue that the B2C service is currently working to fix. I suggest you raise a support ticket with them https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options. Thanks!
