### ISSUE TITLE
request.origin key is overwriting

### ISSUE THREAD

**Issue by roopeshreddy** [AzureAD/microsoft-authentication-library-for-js#2982]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [x] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [x] Angular
- [ ] React
- [ ] Other

## MSAL Configuration

```js
 auth: {
      authority: 'https://login.microsoftonline.com/************/',
      clientId: '***************************',
      redirectUri: 'http://localhost:4200',
      postLogoutRedirectUri: '******************',
      navigateToLoginRequestUrl: true
    },
    cache: {
      cacheLocation: 'sessionStorage'
    }
```

## Reproduction steps

```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.

When we hit any deep link url, let's - **http://localhost:4200/mypage** and initiate login, it's redirecting back to home - **http://localhost:4200** which is happening intermittently. Some times, it redirects to the required page, but sometimes, it goes back to home.

When we debug this issue, we found that, MSAL updated the redirectStartPage to browser storage with key *****.request.origin**. What we observed is, it set the correct redirect and immediately it overwrites with the default one.

The URL is protected with MsalGuard.

```

## Expected behavior

It should work as expected.

## Identity Provider

- [ x] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [x] ADFS
- [ ] Other

## Browsers/Environment

- [x ] Chrome
- [ x] Firefox
- [ x] Edge
- [ x] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by jo-arroyo** [comment]
@roopeshreddy Can you please confirm what versions of msal-angular and msal-browser are being used? Also, could you provide your usage, i.e. whether you are handling redirects yourself, and which pages they are being handled on?

**Comment by roopeshreddy** [comment]
@jo-arroyo Thanks for the response!

msal-browser - **^2.11.0**. We're using the MsalGuard for redirecting!

We're making a MS Graph call to fetch the user details. We suspect this call is happening before the login and hence this issue.
