### ISSUE TITLE
Latest release (1.4.5) breaks es6 usage in MGT

### ISSUE THREAD

**Issue by shweaver-MSFT** [AzureAD/microsoft-authentication-library-for-js#2983]
## Library

- [x] `msal@1.4.5`

## Framework

- [ ] Angular
- [ ] React
- [ ] Other

## Description
A recent update to msal.js (1.4.5) has broken our ability to load the library in the [Microsoft Graph Toolkit](https://github.com/microsoftgraph/microsoft-graph-toolkit). Version 1.4.4 works as expected.

## Error Message

This is the error we see on the Microsoft Graph Toolkit test page in Edge:

![mime](https://user-images.githubusercontent.com/25832310/107095229-3f18c580-67bd-11eb-9448-e37f1804c3ee.png)

This is the same page in Firefox:

![image](https://user-images.githubusercontent.com/25832310/107096646-134b0f00-67c0-11eb-995c-05db70f075a9.png)

## MSAL Configuration

```js
// Provide configuration values here.
<mgt-msal-provider
    client-id="a974dfa0-9f57-49b9-95db-90f04ce2111a"
    scopes="user.read,people.read,user.readbasic.all,contacts.read,calendars.read,presence.read.all,tasks.readwrite,presence.read,user.read.all,group.read.all,tasks.read"
    redirect-uri="http://localhost:3000"
    depends-on="mgt-teams-provider"
  ></mgt-msal-provider>
```

## Reproduction steps

Follow these steps to see the error on the MGT test page:

1. `git clone https://github.com/microsoftgraph/microsoft-graph-toolkit.git`
1. `cd microsoft-graph-toolkit`
1. `yarn`
1. `yarn build`
1. `yarn start`
1. Navigate to `http://localhost:3000`

You will see a blank page, because this bug prevents the components from loading properly.

## Expected behavior
Components should load on the test page.

## Identity Provider

- [ ] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

Tested in:
- [x] Chrome
- [x] Firefox
- [x] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [x] Did this behavior work before?
Version: 1.4.4

## Security

- [ ] Is this issue security related?

## Source

- [x] Internal (Microsoft)
- [ ] Customer request

**Comment by jasonnutter** [comment]
@tnorling Looks like we need to make the `version.json` file `version.js` instead.

**Comment by shweaver-MSFT** [comment]
You got it! Thanks @jasonnutter :)
