### ISSUE TITLE
After logout, in the same tab, user cannot login, and get the exception "BrowserAuthError: interaction_in_progress"

### ISSUE THREAD

**Issue by SamuelQZQ** [AzureAD/microsoft-authentication-library-for-js#2989]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.11.0`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [ ] Angular
- [x] React 16
- [ ] Other

## Description
After call `logout`, will be directed to "pick an account" page. Do not pick any account at "pick an account" page. Click "go back" button in the browser. Then call `login`, but nothing happened with the exception.

If the user opens a new tab, login will work.

## Error Message
```
BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.
    at BrowserAuthError.AuthError [as constructor] (https://localhost:44335/vendors~main.a960f583968d3ded0bc3.js:549:24)
    at new BrowserAuthError (https://localhost:44335/vendors~main.a960f583968d3ded0bc3.js:7083:28)
    at Function.push../node_modules/@azure/msal-browser/dist/index.es.js.BrowserAuthError.createInteractionInProgressError (https://localhost:44335/vendors~main.a960f583968d3ded0bc3.js:7144:16)
    at PublicClientApplication.push../node_modules/@azure/msal-browser/dist/index.es.js.ClientApplication.preflightInteractiveRequest (https://localhost:44335/vendors~main.a960f583968d3ded0bc3.js:10509:36)
    at PublicClientApplication.push../node_modules/@azure/msal-browser/dist/index.es.js.ClientApplication.acquireTokenPopup (https://localhost:44335/vendors~main.a960f583968d3ded0bc3.js:9964:33)
    at PublicClientApplication.push../node_modules/@azure/msal-browser/dist/index.es.js.PublicClientApplication.loginPopup (https://localhost:44335/vendors~main.a960f583968d3ded0bc3.js:10751:21)
    at UserAgent._callee2$ (https://localhost:44335/main.a960f583968d3ded0bc3.js:6611:33)
    at tryCatch (https://localhost:44335/vendors~main.a960f583968d3ded0bc3.js:225954:40)
    at Generator.invoke [as _invoke] (https://localhost:44335/vendors~main.a960f583968d3ded0bc3.js:226184:22)
    at Generator.next (https://localhost:44335/vendors~main.a960f583968d3ded0bc3.js:226009:21)
```
## MSAL Configuration

```js
return new PublicClientApplication({
        cache: {
          cacheLocation: "localStorage",
        },
        auth: {
          authority: this.authority,
          clientId: this.clientId,
          postLogoutRedirectUri: undefined,
          redirectUri: window.location.origin,
        },
      });
```

## Reproduction steps
- call `login`
- call `logout`. You will be directed to "pick an account" page. 
- Do not pick any account at "pick an account" page. Click "go back" button in the browser. 
- call `login`, get the exception. And cannot login at all.

## Expected behavior
No this exception

## Identity Provider

- [X] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [X] Internal (Microsoft)
- [ ] Customer request

**Comment by tnorling** [comment]
@SamuelQZQ This along with your other issue #2990 leads me to believe your app is calling `loginPopup` after calling `logout` but before the logout redirects to the AAD sign-out page. If you have logic that automatically calls `loginPopup`  when a user is not signed-in you should be careful to block this from being called if a logout is in progress. If you can share a couple code snippets of how you're calling login and logout that would be helpful.

As an aside, since you're using react, I would also suggest taking a look at our [react wrapper](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-react) which handles some of these complexities for you.

**Comment by SamuelQZQ** [comment]
@tnorling I tried a lot and confirmed that I haven't called the `loginPopup` after calling `logout`. I find a solution to solve this, but do not know why it works.

My code:
```typescript
class UserAgent {
  public app!: PublicClientApplication;
  graphScopes = [
    "User.ReadBasic.All",
    "Organization.Read.All",
    "Domain.Read.All",
  ];
  clientId = "";
  authority = "";
  callbacks: (() => Promise<void>)[] = [];

  public async init(): Promise<void> {
    this.clientId = settingService.getConfig("appAuthClientId");
    this.authority = settingService.getConfig("appAuthAuthority");
    this.app = await this.getUserAgentApplication();
  }

  public async login(): Promise<void> {
    let result: AuthenticationResult;
      result = await this.app.loginPopup({
        scopes: this.graphScopes,
      });
    }

    this.account = result.account;
    this.userId = result.uniqueId;
    await this.onLoginSuccess();
  }

  public logout(): void {
    this.app.logout();
  }

  private async onLoginSuccess(): Promise<void> {
    ...
  }

  private async getUserAgentApplication(): Promise<PublicClientApplication> {
    try {
      return new PublicClientApplication({
        cache: {
          cacheLocation: "localStorage",
        },
        auth: {
          authority: this.authority,
          clientId: this.clientId,
          postLogoutRedirectUri: window.location.origin,
          redirectUri: window.location.origin,
        },
      });
    } catch (e) {
      console.log("Get UserAgentApplication fail: " + e.desc);
      throw e;
    }
  }
}
```

If I use like this, everything works fine:
```
const userAgent = new UserAgent();
await userAgent.init();
await userAgent.login();
await userAgent.logout();
```

But if I bind the `userAgent.logout()` to `onClick` method of a React Element, the bug comes. My final solution is use `setTimeout` to wrap the `userAgent.logout()` before bind to `onClick`.

Anyway, thanks for your help. I close this issue.
