### ISSUE TITLE
A unexpected window popup when logout

### ISSUE THREAD

**Issue by SamuelQZQ** [AzureAD/microsoft-authentication-library-for-js#2990]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.11.0`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [ ] Angular
- [X] React 16
- [ ] Other

## Description

When the user logout, user will be redirect to the page "pick an account". But at the same time a unexpected window popup which redirects to my website.

## MSAL Configuration

```js
return new PublicClientApplication({
  cache: {
    cacheLocation: "localStorage",
  },
  auth: {
    authority: this.authority,
    clientId: this.clientId,
    redirectUri: window.location.origin,
  },
});
```

## Reproduction steps

- login with popup.
- logout

## Expected behavior

No unexpected popup when logout.

## Identity Provider

- [X] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [X] Internal (Microsoft)
- [ ] Customer request

**Comment by hectormmg** [comment]
Hi @SamuelQZQ . Could you please provide your MSAL API usage code so we can better understand your problem?

**Comment by SamuelQZQ** [comment]
I think this is a bug of myself.
#2989
