### ISSUE TITLE
Null expiresOn for tokens?

### ISSUE THREAD

**Issue by k-mehta** [AzureAD/microsoft-authentication-library-for-js#2991]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.10.0`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

When can AuthenticationResult.expiresOn be null? I get this object back from handleRedirectPromise, acquireTokenSilent, etc.

```
const msalConfig: Configuration = {
  auth: {
    clientId: 'XXX',
    authority: 'https://login.microsoftonline.com/consumers/',
    postLogoutRedirectUri: `${window.location.origin}/logout`,
  },
  cache: { cacheLocation: 'localStorage' },
};
```

**Comment by pkanher617** [comment]
@k-mehta I have opened a PR for this, but as it is a breaking change we are looking for the right time to add it to the library. I will try to get this in as soon as possible.
