### ISSUE TITLE
Error: Should not import the named export 'version' (imported as 'libraryVersion') from default-exporting module (only default export is available soon)

### ISSUE THREAD

**Issue by 6ygga** [AzureAD/microsoft-authentication-library-for-js#2992]
## Library

- [X ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [X ] Angular
- [ ] React
- [ ] Other

## Error Message
./node_modules/msal/lib-es6/Logger.js:39:63-77 - Error: Should not import the named export 'version' (imported as 'libraryVersion') from default-exporting module (only default export is available soon)

./node_modules/msal/lib-es6/Logger.js:42:36-50 - Error: Should not import the named export 'version' (imported as 'libraryVersion') from default-exporting module (only default export is available soon)

./node_modules/msal/lib-es6/ServerRequestParameters.js:40:26-40 - Error: Should not import the named export 'name' (imported as 'libraryVersion') from default-exporting module (only default export is available soon)

./node_modules/msal/lib-es6/telemetry/TelemetryManager.js:23:92-106 - Error: Should not import the named export 'version' (imported as 'libraryVersion') from default-exporting module (only default export is available soon)

## MSAL Configuration

```js
/*

 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License.
 */

import { StringUtils } from "./utils/StringUtils";
import { version as libraryVersion } from "./version.json";        //   <---------  3 String like that in 3 files. Defailt export required.

```

## Reproduction steps

```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Identity Provider

- [ ] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by tnorling** [comment]
@6ygga Please keep an eye out for version 1.4.6 which will address this with the PR linked.
