### ISSUE TITLE
Not returning a token from B2C

### ISSUE THREAD

**Issue by leskodan** [AzureAD/microsoft-authentication-library-for-js#2997]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [x ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [ ] Angular
- [ x] React
- [ ] Other

## Description
I was happy to see a msal-react example specifically for B2C in [this pull request](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/2967) as this has been something that I have been trying to get to work. I pulled down the sample project and plugged in my own client id, authority, and scope. The sign in process is triggered with my specified policy, but it seems that the token is never returned.

## Error Message
I get a 400 error at:

https://mytenant.b2clogin.com/mytenant.onmicrosoft.com/mypolicy/oauth2/v2.0/token

I assume the library appends the "oauth2/v2.0/token" as I am not specifying this as shown in the example. 

## MSAL Configuration
```
export const msalConfig = {
    auth: {
        clientId: "my client id",
        authority: "https:/<tenant>.b2clogin.com/<tenant>.onmicrosoft.com/<policy>",
        knownAuthorities: ["<tenant>.b2clogin.com"],
        redirectUri: "http://localhost:3001",
        postLogoutRedirectUri: "http://localhost:3001"
    }
};
```
Policy: Standard sign up sign in

## Reproduction steps

Run the B2C sample with your own B2C tenant information (I did not change application code from the pull request linked above).

## Expected behavior
Receive a token from B2C.

## Identity Provider

- [ ] Azure AD
- [x ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [ x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by pkanher617** [comment]
@leskodan Do you have any more info about the 400 error? Is it a CORS related issue? If it is related to CORS, make sure your redirect URI in the portal is of type `SPA`.

**Comment by leskodan** [comment]
Thanks @pkanher617, that did the trick! Heads up for anyone else experiencing a similar issue, this isn't abundantly clear on the URI configuration page. I was able to configure accordingly by following this link.

![image](https://user-images.githubusercontent.com/51446532/107290544-ba37e100-6a34-11eb-82ea-a23035fb12c4.png)
