### ISSUE TITLE
acquireTokenSilent making requests instead of using cache (Azure AD B2C)

### ISSUE THREAD

**Issue by 0lukasz0** [AzureAD/microsoft-authentication-library-for-js#2999]
## Library

- [x] `msal@1.4.5` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## MSAL Configuration

```js
const msalApp = new UserAgentApplication({
    auth: {
        clientId: "<client_id>",
        authority: "https://<mytenant>.b2clogin.com/tfp/<mytenant>.onmicrosoft.com/b2c_1_login",
        redirectUri: "https://localhost:3000/user/login/process",
        validateAuthority: false,
        postLogoutRedirectUri: "https://localhost:3000",
        navigateToLoginRequestUrl: false
    },
    cache: {
        cacheLocation: "sessionStorage",
        storeAuthStateInCookie: isIE()
    },
    system: {
        navigateFrameWait: 4000,
        loadFrameTimeout: 20000,
        logger: new Logger((logLevel, message) => {
            console.log(message);
        }, {
            level: LogLevel.Verbose,
            piiLoggingEnabled: AppConsts.logging
        }),
        telemetry: {
            applicationName: "APP",
            applicationVersion: "1.0.0",
            telemetryEmitter: (events) => {
                console.log('Telemetry Events:', events);
            }
        }
    }
})
```

## Reproduction steps

```js
    private async acquireToken(): Promise<void> {
        debugger;
        const account = msalApp!.getAccount();
        const userEmail = account.idToken.emails[0];
         
        account.userName = userEmail;
 
        const tenantInfo = await LoginService.getUserTenant(userEmail);
             
        const request = {
            scopes: [
                        "https://<mytenant>.onmicrosoft.com/<myapp>/read"
                    ],
            loginHint: userEmail,
            redirectUri: AppConsts.authorization.redirectUri,
            extraQueryParameters: { domain_hint: tenantInfo.domainHint },
            account: account
        };
         
         debugger;
         // Call to b2clogin.com
         let token1 = await msalApp!.acquireTokenSilent(request);
         debugger;
         // Call to b2clogin.com
         let token2 = await msalApp!.acquireTokenSilent(request);
         debugger;
         // Call to b2clogin.com
         let token3 = await msalApp!.acquireTokenSilent(request);
         debugger;

 
         return;
    }
```

## Description

My problem is that each call for acquireTokenSilent is making requests instead of using cache. I already found a buch of similar issues (listed below), but none of them was helpful for my problem, I'm using MSAL 1.4.5.

First call:
https://<mytenant>.b2clogin.com/<mytenant>.onmicrosoft.com/b2c_1_login/oauth2/v2.0/authorize?response_type=token&scope=https%3A%2F%2F<mytenant>.onmicrosoft.com%2Fmyapp%2Fread%20**openid**%20**profile**&client_id=<clientid>&redirect_uri=https%3A%2F%2Flocalhost%3A3000%2Fuser%2Flogin%2Fprocess&state=eyJpZCI6ImE3YmFkZTQxLTY2MTYtNDg3ZC1hNDA0LTA3OTM3MzM4MTExZSIsInRzIjoxNjEyODcyMTU5LCJtZXRob2QiOiJzaWxlbnRJbnRlcmFjdGlvbiJ9&nonce=a4b84590-288d-4a3e-a960-b05559e2b15f&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=msal&login_hint=<myemail>&client-request-id=79ed6b09-4cbb-4df9-ad26-a461fabf76fd&prompt=none&response_mode=fragment

Second call:
https://<mytenant>.b2clogin.com/<mytenant>.onmicrosoft.com/b2c_1_login/oauth2/v2.0/authorize?response_type=token&scope=https%3A%2F%<mytenant>.onmicrosoft.com%2Fmyapp%2Fread%20**openid**%20**profile**&client_id=<clientid>&redirect_uri=https%3A%2F%2Flocalhost%3A3000%2Fuser%2Flogin%2Fprocess&state=eyJpZCI6IjI4OTRmNzBkLTljODUtNGQzYi05NThhLTkzYTQxYjA0ZTQxNyIsInRzIjoxNjEyODcyMjMyLCJtZXRob2QiOiJzaWxlbnRJbnRlcmFjdGlvbiJ9&nonce=ad6f6fb0-85f2-4f81-889f-4b010112c062&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=msal&login_hint=<myemail>&client-request-id=4ccff84d-9f6e-407a-b7ce-1ccf91be3c36&prompt=none&response_mode=fragment

As you can see scopes "openid profile" are added internally for each call, as I understand what was written in other tickets it is a reason why calls are being made each time. The question is why this scopes are being added? I think that problem might be that id token userName field is null.

Relevant log I think might be as follows:

auth-utils.ts:106 Tue, 09 Feb 2021 12:03:51 GMT:1.4.5-Verbose No matching tokens of type id_token found
auth-utils.ts:106 Tue, 09 Feb 2021 12:03:51 GMT:1.4.5-Verbose No tokens found
auth-utils.ts:106 Tue, 09 Feb 2021 12:03:51 GMT:1.4.5-Verbose Getting all cached tokens of type Access Token
auth-utils.ts:106 Tue, 09 Feb 2021 12:03:51 GMT:1.4.5-Verbose Evaluating access token found
auth-utils.ts:106 Tue, 09 Feb 2021 12:03:51 GMT:1.4.5-Verbose Access token expired, removing from cache

maybe checking expiration time is culture sensitive or is ignoring timezone? Just my guessing.

Similar issues, which was not helpful for me:
https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1240
https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1623
https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1619
https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2299
https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2238
https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2456

## Logs
Tue, 09 Feb 2021 14:36:25 GMT:1.4.5-Verbose AcquireTokenSilent has been called
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:25 GMT:1.4.5-Verbose Telemetry Event started: bfa8e846-1619-4797-b479-04cab4b1c01a_278cd509-5f5d-4a37-b9b6-df30d03d746f-msal.api_event
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:25 GMT:1.4.5-Verbose Account set from request
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:25 GMT:1.4.5-Verbose Response type: token
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:25 GMT:1.4.5-Verbose Finished building server authentication request
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:25 GMT:1.4.5-Verbose Query parameters populated from existing SSO or account
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:25 GMT:1.4.5-Verbose GetCachedToken has been called
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:25 GMT:1.4.5-Verbose Getting all cached tokens of type ID Token
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:25 GMT:1.4.5-Verbose No matching tokens of type id_token found
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:25 GMT:1.4.5-Verbose No tokens found
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:25 GMT:1.4.5-Verbose Getting all cached tokens of type Access Token
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:25 GMT:1.4.5-Verbose Evaluating access token found
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:25 GMT:1.4.5-Verbose Access token expired, removing from cache
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:25 GMT:1.4.5-Verbose No valid token found in cache lookup
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:25 GMT:1.4.5-Verbose Cached metadata found for authority
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:25 GMT:1.4.5-Verbose Renewing access token
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:25 GMT:1.4.5-Verbose RenewToken has been called
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:25 GMT:1.4.5-Verbose Set window.renewState and requestType
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:29 GMT:1.4.5-Verbose monitorWindowForIframe polling started
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:37 GMT:1.4.5-Verbose monitorIframeForHash found url in hash
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:38 GMT:1.4.5-Verbose HandleAuthenticationResponse has been called
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:38 GMT:1.4.5-Verbose GetResponseState has been called
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:38 GMT:1.4.5-Verbose Hash contains state. Creating stateInfo object
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:38 GMT:1.4.5-Verbose State does not match cached state, setting requestType to type from window
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:38 GMT:1.4.5-Verbose Matching state found for request
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:38 GMT:1.4.5-Verbose Obtained state from response
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:38 GMT:1.4.5-Info ProcessCallBack has been called. Processing callback from redirect response
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:38 GMT:1.4.5-Verbose SaveTokenFromHash has been called
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:38 GMT:1.4.5-Info State status: true; Request type: RENEW_TOKEN
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:38 GMT:1.4.5-Verbose Server returns success
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:38 GMT:1.4.5-Info State is right
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:38 GMT:1.4.5-Info Fragment has access token
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:38 GMT:1.4.5-Verbose No idToken on fragment, getting idToken from cache
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:38 GMT:1.4.5-Verbose PopulateAuthority has been called
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:38 GMT:1.4.5-Verbose Got authority from cache
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:38 GMT:1.4.5-Verbose Fragment has clientInfo
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:38 GMT:1.4.5-Verbose Account object created from response
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:38 GMT:1.4.5-Verbose AccountKey set
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:38 GMT:1.4.5-Verbose AcquireTokenAccountKey generated
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:38 GMT:1.4.5-Verbose AcquireToken request account retrieved from cache
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:38 GMT:1.4.5-Verbose SaveAccessToken has been called
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:38 GMT:1.4.5-Verbose Retrieving all access tokens from cache and removing duplicates
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:38 GMT:1.4.5-Verbose Saving access token to cache
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:38 GMT:1.4.5-Verbose New expiration set for token
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:38 GMT:1.4.5-Info The user object received in the response is the same as the one passed in the acquireToken request
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:38 GMT:1.4.5-Verbose Status set to complete, temporary cache cleared
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:38 GMT:1.4.5-Verbose Acquiring token interactive in progress
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:38 GMT:1.4.5-Verbose Response tokenType set to access_token
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:38 GMT:1.4.5-Verbose Calling callback provided to processCallback
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:38 GMT:1.4.5-Verbose Successfully acquired token
auth-utils.ts:106 Tue, 09 Feb 2021 14:36:38 GMT:1.4.5-Verbose Telemetry Event stopped: bfa8e846-1619-4797-b479-04cab4b1c01a_278cd509-5f5d-4a37-b9b6-df30d03d746f-msal.api_event

## Identity Provider

- [ ] Azure AD
- [x] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [x] Customer request

**Comment by hectormmg** [comment]
Hi @0lukasz0

> As you can see scopes "openid profile" are added internally for each call, as I understand what was written in other tickets it is a reason why calls are being made each time. The question is why this scopes are being added?

The OIDC scopes (openid, profile) are added by MSAL v1 to every request that goes out to the token service because the service expects them and requires them, even when you're not requesting an ID Token. However, they are only added to the request that goes out to the network, but they should be ignored in the caching logic. Are you seeing these scopes in the cache keys for the access tokens that show up as expired?

>maybe checking expiration time is culture sensitive or is ignoring timezone? Just my guessing.

This shouldn't be the case since the expiration time is set based on the client's clock. If you look at the browser cache, do the expiration timestamps look right? (i.e. are they an hour from when the token is requested?)

I'll try to reproduce your issue to make sure it's not a bug.

**Comment by 0lukasz0** [comment]
Ok, I found issue here. Token lifetime on Azure for testing purpose was set to 5 minutes, token was still valid, but internal logic was renewing token each time, because it's lifetime was too short.
