### ISSUE TITLE
Can this library be used in multiple React apps?

### ISSUE THREAD

**Issue by StefH** [AzureAD/microsoft-authentication-library-for-js#3011]
## Library
- [x ] `@azure/msal-react@1.x.x`

## Description
In our solution, multiple React applications are defined and used. Like every page in a .NET Core c# Razor web-site has a separate React application (own webpack compiled .js file)

Can this library + the azure AD flow be used in such a way that the user only needs to login once, and then the tokens are reused across the different apps?

**Comment by pkanher617** [comment]
@StefH As long as the app configuration is the same across all of these React applications, they will be able to share the tokens, most importantly `clientId`. These apps also need to be on the same domain (if you are using browser storage). If these conditions are met you will be able to share tokens across applications.

**Comment by StefH** [comment]
The app configuration and the clientId will be that same.

But can the different apps read the same token e.g. from local storage (or where are the tokens stored?).


My main question is if the users will be presented a new login screen when the other app is activated.

**Comment by pkanher617** [comment]
As long as those values are the same, yes you will be able to read the same tokens from the cache, you shouldn't have to make an interactive call.

**Comment by StefH** [comment]
Hello @pkanher617,

How can I read the tokens from the cache, will just calling the code below be enough?
``` javascript
instance.acquireTokenSilent(. . .
```

Or should I manually get the data from the local-storage?

**Comment by pkanher617** [comment]
Yes calling ATS (`acquireTokenSilent`) will be enough, it will fetch the tokens from whichever cache you have selected (localStorage, in this case). If you'd like to make sure you are signed in before you call ATS, you can use any of our [account APIs](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/docs/Accounts.md) to check whether or not an account object exists.

**Comment by StefH** [comment]
Thanks again for your help.

Another related scenario:
What if besides multiple React apps (which use the React specific npm library), I also have 'plain' JavaScript which also needs to call authenticated API's.

Can I also just use the msal.js and also acquire a token which will follow the same logic as you describe above?

**Comment by pkanher617** [comment]
Yeah you can definitely do this. The `@azure/msal-react` library is a wrapper around the `@azure/msal-browser` library. You can use the `@azure/msal-browser` library for these apps, and they should work the exact same way. Also wanted to point out that I posted the wrong docs link for the react library above, [here is the correct one](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-react#usage).
