### ISSUE TITLE
Angular InteractionRequiredAuthError after login

### ISSUE THREAD

**Issue by sdanko** [AzureAD/microsoft-authentication-library-for-js#3014]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [x] Angular
- [ ] React
- [ ] Other

## Description
Im using MSAL library to fetch data from Graph API. This issue appeared few days ago, before that everything was working regulary. After logging in and granting the permissions I try to fetch data from Graph API. But then I get popup with text: "Are you trying to sign in to application_name? Only continue if you downloaded the app from a store or website that you trust." Afer I click continue I get an InteractionRequiredAuthError. Im using Azure AD on my personal account to register the app.

## Error Message

```
InteractionRequiredAuthError: Silent authentication was denied. The user must first sign in and if needed grant the client application access to the scope 'User.ReadWrite Calendars.Read Calendars.ReadWrite Mail.Read openid profile'.
      at InteractionRequiredAuthError.AuthError [as constructor] (http://localhost:4200/vendor.js:80485:28)
      at InteractionRequiredAuthError.ServerError [as constructor] (http://localhost:4200/vendor.js:80990:28)
      at new InteractionRequiredAuthError (http://localhost:4200/vendor.js:80927:28)
      at MsalService.push../node_modules/msal/lib-es6/UserAgentApplication.js.UserAgentApplication.saveTokenFromHash (http://localhost:4200/vendor.js:78822:25)
      at MsalService.push../node_modules/msal/lib-es6/UserAgentApplication.js.UserAgentApplication.processCallBack (http://localhost:4200/vendor.js:78260:29)
      at MsalService.push../node_modules/msal/lib-es6/UserAgentApplication.js.UserAgentApplication.handleAuthenticationResponse (http://localhost:4200/vendor.js:78319:14)
      at MsalService.<anonymous> (http://localhost:4200/vendor.js:78036:34)
      at step (http://localhost:4200/vendor.js:147612:23)
      at Object.next (http://localhost:4200/vendor.js:147593:53)
      at fulfilled (http://localhost:4200/vendor.js:147583:58)
```

## MSAL Configuration

```js
 MsalModule.forRoot({
      auth: {
          clientId: 'client_id',
          authority: 'https://login.microsoftonline.com/consumers',
          redirectUri: 'http://localhost:4200/'
      }
  }, {
      popUp: true,
      consentScopes: ['User.ReadWrite', 'Calendars.Read', 'Calendars.ReadWrite', 'Mail.Read','openid', 'profile'],
      protectedResourceMap: [
          ['https://graph.microsoft.com/v1.0/me', ['User.ReadWrite', 'Calendars.Read', 'Calendars.ReadWrite', 'Mail.Read', 'openid', 'profile']]
      ]
  })
```

## Reproduction steps
Call Graph API after logging in and granting permissions.

## Expected behavior
Data from Graph API is returned.

## Identity Provider

- [x] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [x] Customer request

**Comment by hectormmg** [comment]
Hi @sdanko .

Since silent token requests will fail with `InteractionRequiredError` when there isn't a valid token in the cache or when the scopes/permissions change for the resource, we recommend falling back to an interactive request (acquireTokenRedirect/acquireTokenPopup, or loginRedirect/loginPopup for login requests) if the error is of the `InteractionRequiredError` type.

Is it possible that the scopes/required permissions changed before you started seeing this error?

**Comment by sdanko** [comment]
Hi,I am pretty sure that scopes did not change before this error. Besides, I have logged out, cleared all the cache and tokens , and then logged in and granted permissions again. This is how I currently handle token failures:

```
const accessTokenRequest = {
    scopes: ['User.ReadWrite', 'Calendars.Read', 'Calendars.ReadWrite', 'Mail.Read','openid', 'profile']
}

@Injectable()
export class MsalEventsHandlerService implements OnDestroy {
    private acquireTokenFailureSubscription: Subscription;
    private loginFailureSubscription: Subscription;
    private ssoFailureSubscription: Subscription;

    constructor(broadcastService: BroadcastService, msalService: MsalService) {
        this.acquireTokenFailureSubscription = broadcastService.subscribe('msal:acquireTokenFailure', (payload) => {
            msalService.acquireTokenPopup(accessTokenRequest);
        });
        this.loginFailureSubscription = broadcastService.subscribe('msal:loginFailure', (payload) => {
            msalService.loginPopup();
        });
        this.ssoFailureSubscription = broadcastService.subscribe('msal:ssoFailure', (payload) => {
            msalService.loginPopup();
        });
    }

    ngOnDestroy(): void {
        this.acquireTokenFailureSubscription && this.acquireTokenFailureSubscription.unsubscribe();
        this.loginFailureSubscription && this.loginFailureSubscription.unsubscribe();
        this.ssoFailureSubscription && this.ssoFailureSubscription.unsubscribe();
    }
}
```
