### ISSUE TITLE
In the CommonDeviceCodeRequest type, add unit to the timeout property description

### ISSUE THREAD

**Issue by waldekmastykarz** [AzureAD/microsoft-authentication-library-for-js#3016]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [x] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Documentation location

- [ ] docs.microsoft.com
- [ ] MSAL.js Github Wiki
- [ ] README file
- [x] Other (code comment)
- [ ] Documentation does not exist

## Description

In the code comment of the `CommonDeviceCodeRequest` type, specify the unit for the `timeout` property in its description. Right now, it's impossible to decide what value should be specified because it's not clear if the value is `ms`, `s` or something else.

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/a58a54972e89cd85abd23a8ad1af4fe1309b989a/lib/msal-common/src/request/CommonDeviceCodeRequest.ts#L18

**Comment by hectormmg** [comment]
Closing since this was addressed in #3031.
