### ISSUE TITLE
In the msal-node device code sample, increase the timeout value from 5 to prevent the login from timing out by default

### ISSUE THREAD

**Issue by waldekmastykarz** [AzureAD/microsoft-authentication-library-for-js#3017]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [x] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Documentation location

- [ ] docs.microsoft.com
- [ ] MSAL.js Github Wiki
- [ ] README file
- [x] Other (code samples)
- [ ] Documentation does not exist

## Description

In the msal-node device code auth sample, increase the `timeout` value from 5 to something else or consider removing it altogether. With timeout set to 5, the login times out every time while you're going navigating to the device login page and pasting the device code.

Additionally, it would be good to specify why this value is needed as the device code response sent initially from AAD already has a timeout of 900 specified. Is the timeout in the deviceCodeRequest meant to override it? If so, what's the purpose? It would be helpful to clarify this.

**Comment by hectormmg** [comment]
Hi @waldekmastykarz thanks for the feedback! We're in the process of polishing our samples and should have things like this updated soon. Some of these details are defaults that we use for testing purposes that we need to change for the usage samples.

**Comment by hectormmg** [comment]
Closing since this was addressed in #3031.
