### ISSUE TITLE
Kudos for msal-node code samples 👏

### ISSUE THREAD

**Issue by waldekmastykarz** [AzureAD/microsoft-authentication-library-for-js#3018]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [x] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Documentation location

- [ ] docs.microsoft.com
- [ ] MSAL.js Github Wiki
- [ ] README file
- [x] Other (code samples)
- [ ] Documentation does not exist

## Description

Kudos for the msal-node code samples 👏 Samples are clear and it's easy to follow what's needed and how the different flows need to be set up.

**Comment by pkanher617** [comment]
Thanks for the props @waldekmastykarz!
