### ISSUE TITLE
Extend the adal-node to msal-node migration docs with info on refresh tokens

### ISSUE THREAD

**Issue by waldekmastykarz** [AzureAD/microsoft-authentication-library-for-js#3019]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [x] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Documentation location

- [x] docs.microsoft.com
- [ ] MSAL.js Github Wiki
- [ ] README file
- [ ] Other (please fill in)
- [ ] Documentation does not exist

## Description

One of the biggest points of confusion when migrating from adal-node to msal-node was for me the fact that msal-node (or MSAL in general) no longer exposes refresh tokens. Unless I totally missed it, the migration docs don't mention this and I found the explanation in one of the issues in the repo. Since this is a big design change for folks coming from adal, it would be helpful to explain it upfront in the migration guidance including what's the reasoning behind it and how it should be addressed.

**Comment by sameerag** [comment]
@waldekmastykarz Thanks for this. We have been considering this, I believe this can be possible but would need some kind of migration code to handle the cache changes and other assumptions to build a bridge between these two libraries. Our initial thought was to not restrain `msal-node` design with `adal-node` assumptions since the changes are years apart and hence we did not bake it into the code.

Let us do some experiments to understand the complexity this may entail and will reach out to you. I agree that this will be a great value add to the customers though.

**Comment by waldekmastykarz** [comment]
Sorry if I wasn't clear: my suggestion was to explain the difference in the migrations docs rather than change the library. Because refresh tokens are no longer exposed and the current docs don't mention this difference, I was stuck for a bit during the migration trying to wrap my head around it. Extending the migration docs would experience the migration experience for devs.

**Comment by sameerag** [comment]
@waldekmastykarz This is now addressed in the docs [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-node-migration#remove-logic-around-refresh-tokens).

**Comment by waldekmastykarz** [comment]
Thanks for the update @sameerag. The document you mentioned only explains removing the logic for handling refresh tokens from old apps using ADALJS, but doesn't mention anything related to removing the refresh token from MSAL cache.

**Comment by sameerag** [comment]
Well, msal-node creates a new cache and hence we no longer refer to the older cache. You make a good point though, there can be a guidance for folks migrating to remove the older cache instance/data once we have fetched a new `refreshToken`. Let me work with my docs team and reach out.

**Comment by derisen** [comment]
@waldekmastykarz good point! @sameerag picking this up.

**Comment by derisen** [comment]
@waldekmastykarz apologies for delay. I've updated the migration guide with how to migrate the still valid refresh tokens and a note on destroying the older adal-node token cache afterwards [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-node-migration#remove-logic-around-refresh-tokens). Hope this captures your concern, but let me know!

**Comment by sameerag** [comment]
@waldekmastykarz Closing this. In case you have more concerns, please let us know and we can track it as needed.

**Comment by waldekmastykarz** [comment]
Thank you!
