### ISSUE TITLE
Could ILoggerCallback's message include correlationId if correlationId was provided to the request?

### ISSUE THREAD

**Issue by thoo1** [AzureAD/microsoft-authentication-library-for-js#3022]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.11.0`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
`BaseAuthRequest` accepts a correlationId, which is useful in debugging logs in AAD. Could the logs that are provided in the `ILoggerCallback`, include this correlationId as well? That way we can see all logs for one request neatly

## Source

- [X] Internal (Microsoft)
- [ ] Customer request

**Comment by thoo1** [comment]
Hi, wondering if there was any traction on this task? The reason I ask is because our app makes parallel calls to acquireTokenSilent and it is hard to figure out which log from msal corresponds to which call to acquireTokenSilent (the logs dont have correlationId)

**Comment by tnorling** [comment]
@thoo1 We haven't had a chance to look into this yet but PRs are always welcome if you'd like to take a stab at it yourself.
