### ISSUE TITLE
How to use msal-node with Managed Identity?

### ISSUE THREAD

**Issue by waldekmastykarz** [AzureAD/microsoft-authentication-library-for-js#3023]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [x] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

How can I use msal-node with Managed Identity?

I’m co-maintaining CLI for Microsoft 365 where we support a number of ways for users to authenticate. We’re looking into migrating from adal-node to msal-node but couldn’t find any examples of using Managed Identity in conjunction with MSAL token cache.

## Source

- [ ] Internal (Microsoft)
- [x] Customer request

**Comment by derisen** [comment]
@waldekmastykarz I had this in the backlog but didn't had time to get to it yet. I'll try to pull together a guide soon.

**Comment by waldekmastykarz** [comment]
Awesome! Looking forward to it!

**Comment by derisen** [comment]
@waldekmastykarz a [PR](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/3128) is in draft stage now.

**Comment by waldekmastykarz** [comment]
Awesome! Thank you for the heads up 👏
