### ISSUE TITLE
How to clear cache when using cert-based auth?

### ISSUE THREAD

**Issue by waldekmastykarz** [AzureAD/microsoft-authentication-library-for-js#3024]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [x] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

After obtaining a token using certificate (ConfidentialClientApplication.acquireTokenByClientCredential), how can I clear the MSAL cache on logout? As far as I can tell, the only way to do it is by retrieving the account and removing it from the cache but since it’s app-only auth the Account property is empty.

## Source

- [ ] Internal (Microsoft)
- [x] Customer request

**Comment by sameerag** [comment]
@waldekmastykarz This is a good point. We have missed this use case and marked it as an enhancement. We plan to pick this up in a couple weeks.

**Comment by waldekmastykarz** [comment]
Will this enhancement be included in the GA version of msal-node or will it be added later?

**Comment by sameerag** [comment]
@samuelkubai will be picking this up in the next few days

**Comment by sameerag** [comment]
@samuelkubai can we start tracking this? @EmLauber Please add this to the backlog, this issue is missing traction.

**Comment by bgavrilMS** [comment]
@waldekmastykarz Is memory pressure really a concern or is latency of getting token out of the cache a problem? There will be 1 token (~2KB) per **tenant** and per **resource**. So, a multi-tenant service that talks to downstream service for 1M tenants, each trying to get a token for Graph and one for SharePoint, would see a memory pressure of `1M * 2 resources * 2KB = 2 GB`. How many tenants / resources do you serve?

The more concerning aspect is probably the perf impact of having 2M tokens in the cache, as cache lookup generally is O(n) and at this scale you really feel it... Same for inserting a new token in the cache, it's O(n). Note that I have not assessed the cache lookup logic in detail, it may not be a problem.

The solution to all of this is to use external token caching, at least an in-memory cache. Better yet to use memory cache + distributed cache (e.g. Redis)

- external caches support setting eviction policies
- MSAL loads only 1 token in its internal memory to perform the cache lookup, ensuring that cache lookup is super-fast
- MSAL can suggest cache key as being `client_id` + `tenant_id` 
- MSAL can suggest expiration as `max_lifetime(AT in cache node)` 

This is possible to be done today (in memory, without eviction), by maintaining a dictionary of `[tenant_id] -> [ConfidentialClientApplication]` but we can enhance the experience, have a sample and provide better support from within MSAL.

**Comment by waldekmastykarz** [comment]
It's been a while, but if I recall correctly, I wanted to ensure that no unnecessary resources are left after logging out.

**Comment by bgavrilMS** [comment]
It is unlikely that you'll be able to clear all the data associated with the service principal, because the certificate or secret can simply be used to fetch new data. 

In any case, this is possible by taking control of your token cache and wiping the cache on your own.
