### ISSUE TITLE
Access token caching is not working

### ISSUE THREAD

**Issue by simon-ittmann** [AzureAD/microsoft-authentication-library-for-js#3025]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [x] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework
- [x] Angular 11
- [ ] React
- [ ] Other

## Description

The caching of the access token is not working. On every intercepted XHR-Request the msal lib is requesting a new access token.

Networktraffic looks like:
POST /oauth2/v2.0/token
GET /some-xhr
POST /oauth2/v2.0/token
POST /some-other-xhr
POST /oauth2/v2.0/token
GET /some-xhr

## Error Message
-

## MSAL Configuration

```js
export const appInitializer = (moduleType: Type<any>): Promise<void> => fetch('/initialize')
  .then(response => response.json())
  .then(initialConfig => {
    const authCfg = initialConfig.ciamOptions;
    const msalConfig: Configuration = {
      auth: {
        clientId: authCfg.clientId as string,
        authority: `https://${authCfg.tenantName}.b2clogin.com/${authCfg.tenantName}.onmicrosoft.com/${authCfg.signInPolicy}`,
        redirectUri: /.*:\/\/[^\/]+(?:\/admin|\/studio)?/.exec(location.href)[0],
        knownAuthorities: [`${authCfg.tenantName}.b2clogin.com`],
      },
      system: {
        loggerOptions: {
          logLevel: LogLevel.Verbose,
          piiLoggingEnabled: true,
          loggerCallback: (level, msg) => {
            console.log(msg)
          }
        }
      },
      cache: {
        cacheLocation: BrowserCacheLocation.LocalStorage,
      },
    };

    /**
     * 00000000-0000-0000-0000-000000000000 -
     * Using the client ID as the scope indicates that your app needs an access token that can be used
     * against your own service or web API, represented by the same client ID.
     */
    const scopes = [authCfg.clientId];


    const protectedResourceMap = new Map();
    protectedResourceMap.set(`/api/*`, scopes);

    const msalConfigAngular: MsalInterceptorConfiguration = {
      interactionType: InteractionType.Redirect,
      protectedResourceMap
    };

    const msalGuardFactory = (): MsalGuardConfiguration => ({
      interactionType: InteractionType.Redirect,
      authRequest: {
        scopes
      },
    });

    platformBrowserDynamic(
      [
        {
          provide: MSAL_INSTANCE,
          useValue: new PublicClientApplication(msalConfig)
        },
        {
          provide: MSAL_INTERCEPTOR_CONFIG,
          useValue: msalConfigAngular
        },
        {
          provide: MSAL_GUARD_CONFIG,
          useFactory: msalGuardFactory
        }
      ]
    ).bootstrapModule(moduleType)
      // eslint-disable-next-line no-console
      .catch(err => console.error(err));
  });

```

## Expected behavior

The POST /oauth2/v2.0/token should only occur if the access token is expired, other wiese the token should be taken from the local storage.
 
## Identity Provider

- [ ] Azure AD
- [ ] Azure B2C Basic Policy
- [x] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [x] Customer request

**Comment by pkanher617** [comment]
@simon-ittmann There is currently a [known issue](#2451) with passing client id as a B2C scope. Instead, you can create a custom B2C scope and use that in the request.

**Comment by simon-ittmann** [comment]
@pkanher617 thanks for the quick answer 👍 Your link is not working. Do you mean [this](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2451) issue?

So it is possible to configure a custom scope in azure, to return an access_token in response as well?

**Comment by pkanher617** [comment]
@simon-ittmann Sorry about that, yes that is the issue I am referencing. 

> So it is possible to configure a custom scope in azure, to return an access_token in the POST /oauth2/v2.0/token response as well

Yes, I am assuming that you have a web api you are trying to access with `client id` as the scope, you can define a custom scope on that web api and request that as the scope instead of the `client id`.

**Comment by simon-ittmann** [comment]
@pkanher617 With a custom scope the caching is working fine 👍 
Thank you 😃

**Comment by pkanher617** [comment]
Great! Closing for now since issue was resolved, open another issue if you are still having problems. Thanks!
