### ISSUE TITLE
MSAL React Router: 9002327 - [2021-02-17 08:53:27Z]: AADSTS9002327: Tokens issued for the 'Single-Page Application' client-type may only be redeemed via cross-origin requests.

### ISSUE THREAD

**Issue by shamprasadrh** [AzureAD/microsoft-authentication-library-for-js#3032]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [X] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [ ] Angular
- [X] React
- [ ] Other

## Description
Trying to run the React Router example and getting error. 
## Error Message

![image](https://user-images.githubusercontent.com/28918386/108180722-1e416000-712d-11eb-9f37-3e50cc97b451.png)

## MSAL Configuration

```js
        clientId: "MyAPPID",
        authority: 'https://login.microsoftonline.com/MYTENANTID',
        redirectUri: "http://localhost:3000/",
        postLogoutRedirectUri: "http://localhost:3000/"
```

## Reproduction steps

```js
Run the dev server with above values. 
```

## Expected behavior
Should login user successfully. 
## Identity Provider

- [X] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by pkanher617** [comment]
@shamprasadrh Could you verify that the "Origin" header is present in the network request? MSAL uses fetch to retrieve tokens for the user, but there are some environments where the correct headers are not added. The server will throw this error if it cannot find the "Origin" header present.

**Comment by shamprasadrh** [comment]
@pkanher617 No `Origin` header is not available. How can we solve this issue?  

`Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Connection: keep-alive
Content-Length: 1365
content-type: application/x-www-form-urlencoded;charset=utf-8
Cookie: esctx=AQABAAAAAAD--DLA3VO7QrddgJg7WevrdtcPp0UMwiQf-fWJ0sT36OV7IbSoqUsSNurZEWLmeZEVW_7CDVwKVw5HGU4OPSUj68NX5_DWJLRMAIaQ5n4ARpNuzcUprC38EuA-aLmhMVwMw5dDpFxyIXb-tLib-ktirHCTG-9WduMBl-saBYIXdZ-uJiapEqGSoFIUi6cItmUgAA; stsservicecookie=estsfd; brcap=0; ESTSAUTHLIGHT=+0927d010-6444-47ab-8cb3-4d29f1f81a76; ESTSSC=00; CCState=RWhJS0VGalo3Tys1UDI5RG9iTmRQVDRaRktNaWVnRUFBUUFCQUFBQS92Z3l3TjFUdTBLM1hZQ1lPMW5yNndKdDh5cXRKR3pPZ1VUSTlDeFpZWFFwY1E2cG1VUFVZY3BuRjdoVzRESDYvb08wZmZyM0hRRk0vNnlXVXRoUXdFWEtoc2lZTklVQlJsTEhJQzJFZmZ1UU16UlRBY2ZOWUl4NlRHU05XTm5Zc0VlVGVCeGtJZERVZWEzTHVmeVcyeUFBS29BR0FRQUJBQUVBQUFEMElRRGZ2cmpjQUlUUVB2WFFBUHJmTUlJQjRnWUpLb1pJaHZjTkFRY0RvSUlCMHpDQ0FjOENBUUF4Z2dGN01JSUJkd0lCQURCZk1Fc3hDekFKQmdOVkJBWVRBbFZUTVJVd0V3WURWUVFLRXd4RWFXZHBRMlZ5ZENCSmJtTXhKVEFqQmdOVkJBTVRIRVJwWjJsRFpYSjBJRU5zYjNWa0lGTmxjblpwWTJWeklFTkJMVEVDRUFwUkpqR3VMNEpKVGRwUkRWVDNuNm93RFFZSktvWklodmNOQVFFQkJRQUVnZ0VBNHdkVU5Zd25WZWFHR1J0OFVqYTkwNWg4VkVQejVkWjliRDY0Q3htTHVSS0Q4c24wRDJ1bGEvcy8yUjJ0QnFPZk52d3NkTFQ3VmlFQjl3S3czcEtIMk8ydDJJU3JxeG51RVJSMC9YN1dNd2dsYXN6V0p3MkZVWE41d09JL091RnJCdEl6MXVqUjJSK3I2RCtNNmpoVkZhc3lsWGd4aW9yRHM2d0NJazdkREwwVjV0THVOVU5oMndFUWpqZ3hXOXZtL1NEcWQ4bW5PVlF6QTgrQlE1MFJEZ3F0VzZYUTk2Q05TSHpZbGVKL0RIc1o1MzFPZXBBZnI2Z0RWaXF6NVB6Y1NYeDl5WDA0b0x1VUlJdHdFN2NObHJrVWhXQy9yZ0F2VE5sRWF4SlU0NERNMjRzTW8yc0ptZFNEYisraDlxMG9QaEpTOHMwV0FXblZqVytsZi8xQ0ZEQkxCZ2txaGtpRzl3MEJCd0V3RkFZSUtvWklodmNOQXdjRUNDNUVQeEdGOXRlQWdDZzRXeFVxOWk3Slo1bkdWc1ZtMlVRaEhpL0NxSFpvS0pMNDNxTlBJRUJmL2NzaUFlZnBHTVdaRG80RkFCZ3FESElGSm92c3Q3UnlBV2tOYzV5L0NKbnlXM2ZCemxZR3Q4SE54cVViQS9rTnRrV0d6UFVlU0Vod204UGovUTdPK1Z2VkJNYmc1djJXT1RkMmpoODc5a3grbHBNSFpmcHNUQTNCZVdVRWFwUEpzNitDUUpDNkoyMyt3UlZZYk5zT25lSlBXdVlBVW1HNWVIWHRSejZyd0ltVVByc3dYZGNGaG1tR0dWNFJpd2tsd1FUdGRwVnd3NWF1Y1B1UE9JeGVlNDZiT0NXcVdWWmJyc0JWQkkvcEQ5QzFvNXVTeE9wekpqL0NiOUJoZmtYcWhSbnBwUmhqTUcweGtuVFkwU3hBa3hqT3pLeEx6RGR2R09FcUxRK1djUzdrRGxtNnVqZFNMNmNTcTJXOExyZUhXT3VNK3M2VGxiWnFnaGhyZXUwUVJzODRXbDJpVGkveTFBQUI=; x-ms-gateway-slice=estsfd; clrc={%2218674%22%3a[%22oqAgzl8b%22]%2c%2218675%22%3a[%22lp8opkEy%22%2c%22ej1sIdDK%22%2c%22lgXZKHa4%22%2c%22fbd9tt2z%22]}; ESTSAUTHPERSISTENT=0.ASwA1BfKctvRa0mOESYXrjcvT2cAJAbr95xLiUGO2OwmSfMsAB4.AgABAAQAAAD--DLA3VO7QrddgJg7WevrAgDs_wQA9P-0QaCt4gIf1Dyb3VFVrB5xMJaO-iHjnNmfrDxOuqln7m_lX7MjVXaFFXUkHqoIxTzQjIaBAU_x2pPbtAyRihhF8ndt2l74bKn6OR8hrarMdRP4Y8lKbvI0mzmq1z6YojvIYZgaihbQsgqODGgvPPgM-aUS6d_gR-LXdATzT0rdGXSzIMBepqWpAsSpkZSnk8mAQjRJDse278AztVfvZ3Mcj32oyfwOcZ8JB6M_XnG7dHvy9B9XtYcSVMZSluVIugBQa6WJQIxm7IYkY5USuZuFDJRiWYKMqjObBprpwc_1xTjlUJUjYL29Rj2KV5gijruvI9hLcpIMNeXsRXVIJWgUZG-RY94NqWjsutoAIgqJlcuhFbFHHy-destKCXSlZ90pE6Fh9vvSsL745Hmwg2TuSfgnvHzYFBdBVpDYYkn8vXjdqTxB1I5qZs5U5KF9Vue7GU3Q027e__ra_rIhYoq5_Z2-kpnNHZQvaJLSwJVJXu4ByKLzy288AGKpWDbvkDbHHFW67-h9Dug2cVjS34r3; ESTSAUTH=0.ASwA1BfKctvRa0mOESYXrjcvT2cAJAbr95xLiUGO2OwmSfMsAB4.AgABAAQAAAD--DLA3VO7QrddgJg7WevrAgDs_wQA9P916fYF8I-TaexVrR1mDefsAgIT1JsidDen9dLNQvqN5BfVdy6glhX9uQLM9UkmLng4Gh506NkumvLP5JQdK8sGP1OrzHY78EVhgJb_g_MrWw1dnfSEo1qkiBf5GA_-dEboHq3rxJGpPiWP0X4KZPtz66LQ_cbMjJK2inB2utGu9CXrNt8WWdsLGPlCtkJrwWwz_pBlY3QPdZaGapMSECtGhYGtJxppdbvOiUNWpW4TywZppODXuIgCb4Fo8HbQMTL6ilUojsnFbv1QF6cIvBJoVvHGQj-4K98AVU74br0vaWfdWH7mh-Sydrt48M4QTeF47d4MwDNpqvJJeZQzskVJ3LqnNoXvwBa8u4eF-dyyH_hEUDrhGCNB1FzAcdiftEvnO9h48stWJmu38wO-8BIiayu_x7XppTRtjEu7czSOWqAEEyisH_6AuHYSUrGJrKLCBLhncuKhqZ0C2MFS5jy7liX3ZQsmiQ9-18NMNE7qY7HqpoXs3JHfj3CRS47vYPPqOmc_diiNbxTcbFwVcHsmAVuTI1bJrxuwlNCrwzgyb5BbEobdwpvxgPesJgkPnpKUh7hz0DxrgCK5yWhfrPpDAbBKEbGwxlsxijtg_AhxLrgVyyG3T2Qt48cc11yapakxDQ_JrrWlV9swdiTajQnA7IRz5pQbY7FcDE99KCu7JA6FTjt6BpkoTNPCnI2_PeUv5f8rN7wX0ZOOIqecryftPvncQgijIXbl0YOhR6zozbrEdwvGrqJ9mBT27W8oVjSc3pdPL_qRiI1DtFnyJs6Z; ch=0XwwQ0jxUWZsoShsW2yyVIbLJ0J0t_EQBqQgOAP0eTw; buid=0.ASwA1BfKctvRa0mOESYXrjcvT2cAJAbr95xLiUGO2OwmSfMsAB4.AQABAAEAAAD--DLA3VO7QrddgJg7WevrVaHfkdy-8GZn3-oXtvjvuP0Ry2GjTqc6EVY-6oMeeY2zddOGquYDrnu_azR4pAC2bQ4jjpJs85fQXP6ohieB1jLZc3TEMUNCmWLkcTZVyXHb1dg5y4jdktGY3ADSWolSWUjKw5gVVLipih9UtAdI_u15NnEdw9YaRZsTFq5poRJyve1v8FlQIj41Ya1PC0Ts5wK7sa4KblZW1MVKQVoyNvmjuH6fbinfKzUSq3OellMFBLGjbq4vCmF2ua8QfSnesTHb8-y-W7njST8rljhrPCAA; SignInStateCookie=CAQABAAIAAAD--DLA3VO7QrddgJg7Wevr1jGZTr0hFPnIAluaCHW90Ey9ceTjU02nAYQb72zgjyhX0ZWnjeKRyU4-qrlBiIYrPbSr_BJOjqH8hKqEHtomFXVLYJ1jcqhmSJvWa0J06w15sX0zNp8CtMdUJctZ6mnACdysMIq0O-xsxXRoMVI_JmZ4AWbodZBQS7f5u2ZFPD4rQ1scw9h7dcXe_VKd6dHegpkdpj1thaEVn9C5kOMVHzkeq5nz_DXTuy8NCXKotSPfvT2IQrMVfqHHXPiqLR9g1a-ivppowEN4BY18EBbneVNBYIeOKxEsGKv8CINp7T2OjaB4ZlrAcax2CeaLJt0B_kSmZH1XQp1B59EiQDp8VSGnM6obN9sEcKgf8_u7JqIFb7MG4Jqv_QjJF1dEkDXj7WqZr_GBM6elCn479tmOY75WLZG3ezDPucp-QdfU321Yd88O7zxEVXgz9FFsysBQZcjPFcFtLomNPtwbhGrmy6DRx1oo0j-LWhUbIkENfNoIrHXNCp-GhUHI0RT2zXFgeFBInxtPtUzN5-73dIdkDVJMr3w364C32BerRfhAFiyVKe2zgfdCPF2f9S5m9e3dX5rtcZc2_fRgKKO9PeJ0CyAA; fpc=ArdfxIgQ-UtIgqxLYyjUU9hoEb0bAgAAAIH5v9cOAAAA
Host: login.microsoftonline.com
Referer: http://localhost:3000/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36
x-client-cpu
x-client-current-telemetry: 2|862,0|@azure/msal-react,1.0.0-alpha.5
x-client-last-telemetry: 2|0|862,12ec98a3-3027-4dc3-95b6-717368252d1b|invalid_request|1,0
x-client-os
x-client-sku: msal.js.browser
x-client-ver: 2.11.1
x-ms-lib-capability: retry-after, h429`

**Comment by pkanher617** [comment]
I would try to figure out why the header is not being included, as it should be sent on fetch requests by default. There some test environments like `Cypress` which will remove the `Origin` header when the chromeWebSecurity flag is set to `false`. Most modern browsers should be adding this header without issue.

If you are still seeing issues with this in a dev or prod environment in a modern browser, you can try overriding the network module interface used to send requests and add the "Origin" header yourself. Unfortunately it appears we don't have docs on this, but I will work on adding those shortly. [Here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/5e816b065be44b8f7c5e216ec25b96bccd1a2031/lib/msal-browser/src/config/Configuration.ts#L68) is the place in the configuration object you can provide the implementation of the interface, and [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/src/network/INetworkModule.ts) is the interface to implement. The [FetchClient.ts class](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/src/network/FetchClient.ts) is our default for browser not named IE or Edge Legacy.
