### ISSUE TITLE
How to get Pop Up Window Working to implement the Authorization Code Grant with a client credential using msal node

### ISSUE THREAD

**Issue by rizvirashid** [AzureAD/microsoft-authentication-library-for-js#3033]
## Library

- [x] `@azure/msal-node@1.0.0-beta.6`
- [x] @azure/msal-node@1.x.x

## Description

I am using the Backend for frontend pattern to implement the Authorization code grant, where I have React JS based SPA and Express Server based Backend. I am using Express Server to integrate with Azure AD and implement the Authorization Code Grant. The reason I am using Backend for front end pattern is that I don't want to expose the Tokens in browser. 
I would like use a Pop Window for showing Azure AD Login screens but currently I am getting redirect screens. Is it possible to Authorization code grant using a Pop window while using msal-node?

## Source

- [ ] Customer request

**Comment by rizvirashid** [comment]
If its possible to show a Pop Up Screen using msal node for Authorization code grant. please let me know.

**Comment by rizvirashid** [comment]
If its possible to show a Pop Up Screen to login a User using msal-node for Authorization code grant. please let me know.

**Comment by tnorling** [comment]
@rizvirashid So sorry nobody has addressed this yet. There is currently no built-in way to use msal-node and open a popup as `msal-node` is not intended to run in the browser. If you want popups you'll have to open one yourself using `window.open` with the url you get from `msal-node`

**Comment by rizvirashid** [comment]
Hi @tnorling Thank You for the response. I will close this ticket.
