### ISSUE TITLE
Log Cache Miss

### ISSUE THREAD

**Issue by spottedmahn** [AzureAD/microsoft-authentication-library-for-js#304]
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/master/src/UserAgentApplication.ts#L1080

```typescript
const cacheResult = this.getCachedToken(authenticationRequest, userObject);
if (cacheResult) {
  if (cacheResult.token) {
	this._logger.info("Token is already in cache for scope:" + scope);
	resolve(cacheResult.token);
	return;
  }
  else if (cacheResult.errorDesc || cacheResult.error) {
	this._logger.infoPii(cacheResult.errorDesc + ":" + cacheResult.error);
	reject(cacheResult.errorDesc + ": " + cacheResult.error);
	return;
  }
}
//ADD THIS LINE HERE
else{
   this._logger.verbose("Token is not in cache for scope:" + scope);
}
```

Can we add a `this._logger.verbose()` to the else for cache misses?

I'm debugging why I'm frequently requesting access tokens from B2C...

Happy to do it if you will merge PR?!

**Comment by rohitnarula7176** [comment]
@spottedmahn I have added the log statement for cache miss. Thanks a lot for your contribution.

**Comment by spottedmahn** [comment]
Great 🤗, thanks @rohitnarula7176!

Shall I close the issue?

**Comment by rohitnarula7176** [comment]
@spottedmahn Closing this issue.
