### ISSUE TITLE
MSAL 2.0 Auth in React JS - Incognito issue

### ISSUE THREAD

**Issue by Victor-Varghese** [AzureAD/microsoft-authentication-library-for-js#3041]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [x] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [ ] Angular
- [x] React
- [ ] Other

## Description

Im using azure-msal-react for user-auth in react. The code snippet used is as follows.

```
import React, { useEffect } from 'react';
import { useMsal, useIsAuthenticated, useMsalAuthentication } from '@azure/msal-react';
import './App.scss';
import { useDispatch } from 'react-redux';
import { InteractionType } from '@azure/msal-browser';
import { AuthActions } from './store/actions/authActions';

import Routes from './routes';

function App() {
  const { instance, accounts } = useMsal();
  const dispatch = useDispatch();
  const isAuthenticated = useIsAuthenticated();
  const request = {
    scopes: ['User.Read', 'User.ReadBasic.All', 'email'],
  };
  useMsalAuthentication(InteractionType.Redirect, request);

  useEffect(() => {
    async function getTokenSilently() {
      const tokenRequest = {
        scopes: ['User.Read', 'User.ReadBasic.All', 'email'],
        loginHint: accounts[0].username,
      };
      const res = await instance.ssoSilent(tokenRequest);
      dispatch({ type: AuthActions.SET_TOKEN, payload: res.accessToken });

      dispatch({ type: AuthActions.SET_CLAIMS, payload: accounts[0].username });

      // TODO - Victor Let's remove sessionStorage dependency for Token passing
      sessionStorage.setItem('accessToken', res.accessToken);
      sessionStorage.setItem('loginUser', accounts[0].username);
    }
    if (isAuthenticated) {
      getTokenSilently();
    }
  }, [isAuthenticated]);

  return <Routes />;
}
export default App;
```
Can someone point me in right direction to fix this issue? Is there a better way to achieve redirect auth using msal?

Can someone point me to any code snippet that does msal 2.0 auth in react. Most of the articles available are really old.

PS: **This issue happens after redirect auth**

## Error Message

<img width="669" alt="err-msal" src="https://user-images.githubusercontent.com/44889920/108312486-ccf0a980-71dc-11eb-9ab4-ccba77edbe62.png">

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps

```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Identity Provider

- [x] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by Victor-Varghese** [comment]
Also tried handling this error using something like this, but ends up in recursive loop.

```
const silentRequest = {
    scopes: ["User.Read", "Mail.Read"],
    loginHint: "user@contoso.com"
};

try {
    const loginResponse = await msalInstance.ssoSilent(silentRequest);
} catch (err) {
    if (err instanceof InteractionRequiredAuthError) {
        const loginResponse = await msalInstance.loginPopup(silentRequest).catch(error => {
            // handle error
        });
    } else {
        // handle error
    }
}
```

**Comment by pkanher617** [comment]
@Victor-Varghese the reason the loop is happening is that `ssoSilent` will always make a network request by opening a hidden iframe. This will always fail since most likely 3p cookies are blocked, which results in the popup being called again.

You should change the `ssoSilent` call to `acquireTokenSilent()` instead. See the sample [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-react-samples/react-router-sample/src/pages/Profile.jsx) for more info.

**Comment by Victor-Varghese** [comment]
Thank you @pkanher617 
Used acquireTokenSilent instead of ssoSilent and added check with inProgress
