### ISSUE TITLE
acquireTokenSilent doesn't refresh ID token, instead redirects

### ISSUE THREAD

**Issue by forellendev** [AzureAD/microsoft-authentication-library-for-js#3045]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ X ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [ ] Angular
- [ ] React
- [ X ] Other

## Description

The login works and I get an ID token (Scopes: "openid", "profile", "offline_access"). I would like to refresh the ID token with acquireTokenSilent (Scopes: "openid", "profile", "offline_access"), but instead get a redirect to /v2.0/.well-known/openid-configuration and no ID token.

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps

```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Expected behavior

I expected that acquireTokenSilent called with the same scopes during login would give me an updated ID and Access Token.

## Identity Provider

- [ X ] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [ X ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by pkanher617** [comment]
@forellendev Thanks for opening this. I was able to reproduce this, I will debug this and update here.

**Comment by pkanher617** [comment]
@forellendev Could you try just sending `openid` and `profile` for the scopes values? It seems like the issue is stemming from sending the `offline_access` scope. We are looking at ways to mitigate this.

**Comment by forellendev** [comment]
I'll open this issue again, because it seems to be common and the solutions differ too much. I tried pasting in the client ID into the scopes for the silent request, but that didn't work either. It began to work when I only added the account field:

`const result = await msalObj.acquireTokenSilent({
      account: this.application.getAllAccounts()[0],
    });`

**Comment by pkanher617** [comment]
@forellendev Using client ID as scope wont help here. As I said above, can you try omitting `offline_access` from the scopes you are sending in the request object? I've also merged a PR to dev that will fix this, we will push out a patch early next week.
