### ISSUE TITLE
Is Creating Socket IO Connection Within MsalAuthenticationTemplate Secure?

### ISSUE THREAD

**Issue by pjchungmd** [AzureAD/microsoft-authentication-library-for-js#3050]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [X] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

Forgive me if this is an extremely naive question. I am trying to use socket IO with my SPA that I've implemented authentication using auth code flow. Simply put, if I create a new socket connection between the client and server, but the client-side connection code is within `MsalAuthenticationTemplate` (also utilizing WSS and ensuring CORS is not allowed), are there any obvious security risks with this?

## Source

- [ ] Internal (Microsoft)
- [X] Customer request

**Comment by pkanher617** [comment]
@pjchungmd It depends on what the socket connection is doing, but the `MsalAuthenticationTemplate` does not render children if the client has not been authenticated yet.
