### ISSUE TITLE
MSAL method to get if a user is logged in or not

### ISSUE THREAD

**Issue by Mamta92** [AzureAD/microsoft-authentication-library-for-js#3056]
Hi @jo-arroyo ,

I have two web apps A and B both are using msal to login and are using Angular. Both the sessions are active and are on search page. If I logout on App A using this.msalService.logout()..and refresh on the search page on App B, can I get to know by some method or some guard in MSAL if user has signedout already and then we can redirect them to login page?

Note:- Any new session on App B(login page) asks for a password. But need solution for existing sessions.

**Comment by pkanher617** [comment]
@Mamta92 Could you please fill out one of the [issue templates] so that we can better debug your issue?

**Comment by Mamta92** [comment]
## Library


- [ ] `@azure/msal-angular@1.1.2`

## Description

Hi @jo-arroyo ,

I have two web apps A and B both are using msal to login and are using Angular. Both the sessions are active and are on search page. If I logout on App A using this.msalService.logout()..and refresh on the search page on App B, can I get to know by some method or some guard in MSAL if user has signedout already and then we can redirect them to login page?

Note:- Any new session on App B(login page) asks for a password. But need solution for existing sessions.
## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by jo-arroyo** [comment]
@Mamta92 In order for single-sign out to work, you should set the Front-channel logout URL in Azure Portal for your app. This should be set to a page that automatically invokes the MSAL logout API (e.g. myapplication.com/logout). AAD will clear the user's session data. You will then have to invoke some trigger in App B to inspect the account state or look for tokens.
