### ISSUE TITLE
 AADSTS90020:The SAML 1.1 assetion is missing immutable ID of the user on VM (Works fine on local machine)

### ISSUE THREAD

**Issue by nick17728** [AzureAD/microsoft-authentication-library-for-js#3057]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

### Library

 msal@1.x.x or @azure/msal@1.x.x
 @azure/msal-browser@2.x.x
 @azure/msal-angular@0.x.x
 @azure/msal-angular@1.x.x
 @azure/msal-angularjs@1.x.x

### I'm submitting a...

[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:

### Browser:
Chrome Version 88.0.4324.182

### Library version

1.4.5

### Current behavior

Msal login is failing on virtual machine with different domain, But works fine on local machine 

<img width="341" alt="HVD" src="https://user-images.githubusercontent.com/29074273/108750587-379c3f00-7567-11eb-9eca-ca70ca94ee77.png">

### app.component.ts 

`this.authService.handleRedirectObservable().subscribe({
      next: (result: AuthenticationResult) => {
        this.getProfile();
      },
      error: (error) => console.log(error)
    });
  }`

### app.module.ts

`  function MSALInstanceFactory(): IPublicClientApplication {
    return new PublicClientApplication({
      auth: {
        clientId: 'XXXXXXXXXXXXX',
        authority: 'XXXXXXXXXXXXXXX',
        redirectUri: 'XXXXXXXXXXXXXXXXX'
      }
    });
  }`

`function MSALInterceptorConfigFactory(): MsalInterceptorConfig {
    const protectedResourceMap = new Map<string, Array<string>>();
    protectedResourceMap.set('https://graph.microsoft.com/v1.0/me', ['user.read']);`

   ` return {
      interactionType: InteractionType.Redirect,
      protectedResourceMap,
    };
  }`

` providers: [
      HomeService,
      DashboardService,
      AlertService,
      BsModalRef,
      {
        provide: HTTP_INTERCEPTORS,
        useClass: MsalInterceptor,
        multi: true
      },
      {
        provide: MSAL_INSTANCE,
        useFactory: MSALInstanceFactory
      },
      {
        provide: MSAL_GUARD_CONFIG,
        useValue: {
          interactionType: InteractionType.Redirect
        } as MsalGuardConfiguration
      },
      {
        provide: MSAL_INTERCEPTOR_CONFIG,
        useFactory: MSALInterceptorConfigFactory
      },
      MsalService,
      MsalGuard,
      MsalBroadcastService
    ]`

Not sure what im doing wrong any help regrading this will be appreciated ,thank you

**Comment by pkanher617** [comment]
@nick17728 I'm a bit confused by the information you have provided. The version number you gave indicates that this is for the [`msal v1` library](https://www.npmjs.com/package/msal), but the code you have provided is using the `PublicClientApplication` class, which is used in the [`msal-browser` library](https://www.npmjs.com/package/@azure/msal-browser). Could you clarify which library you are using? 

I have not seen this error before, let me see if I can find how this error is occurring.

**Comment by nick17728** [comment]
Hi @pkanher617  apologies for the wrong version number provided  my bad ,this issue was occurring due to a  domain mismatch ,you can close the issue .
Thanks again for the response.

**Comment by pkanher617** [comment]
@nick17728 No worries! Thanks for letting us know your issue was resolved. Closing now, please open another issue if you have further questions.
