### ISSUE TITLE
Chromium extension sample fails because redirect uris don't match

### ISSUE THREAD

**Issue by arcadiogarcia** [AzureAD/microsoft-authentication-library-for-js#3059]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [ ] Angular
- [ ] React
- [ ] Other

## Description

The code in provided Chromium extension sample fails to log in, it compails about the redirect_uri not matching.

The cause of this seems to be that the chromium redirect uri is missing in the parameters of the original auth url, after adding it it logins correctly.

## Error Message

index.es.js:8747 POST https://login.microsoftonline.com/common/oauth2/v2.0/token 400 (Bad Request)
index.es.js:524 Uncaught (in promise) ServerError: invalid_grant: 70000 - [2021-02-22 19:34:37Z]: AADSTS70000: The provided value for the 'redirect_uri' is not valid. The value must exactly match the redirect URI used to obtain the authorization code.
Trace ID: e32a97ed-a580-43a6-b931-37ecd3081b00
Correlation ID: 40c82ca9-081b-46f5-8965-ab768228a3c5
Timestamp: 2021-02-22 19:34:37Z - Correlation ID: 40c82ca9-081b-46f5-8965-ab768228a3c5 - Trace ID: e32a97ed-a580-43a6-b931-37ecd3081b00
    at t [as constructor] (chrome-extension://okmgenonbcmbmhkaljgdaaadkjjaipjm/flyout.bundle.js:32:6666)
    at new t (chrome-extension://okmgenonbcmbmhkaljgdaaadkjjaipjm/flyout.bundle.js:32:42748)
    at e.validateTokenResponse (chrome-extension://okmgenonbcmbmhkaljgdaaadkjjaipjm/flyout.bundle.js:32:60761)
    at t.<anonymous> (chrome-extension://okmgenonbcmbmhkaljgdaaadkjjaipjm/flyout.bundle.js:32:65741)
    at chrome-extension://okmgenonbcmbmhkaljgdaaadkjjaipjm/flyout.bundle.js:32:1863
    at Object.next (chrome-extension://okmgenonbcmbmhkaljgdaaadkjjaipjm/flyout.bundle.js:32:1968)
    at a (chrome-extension://okmgenonbcmbmhkaljgdaaadkjjaipjm/flyout.bundle.js:32:707)

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps

Use the js code in the Chromium sample and try to login against a new app.

## Identity Provider

- [x] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [ ] Chrome
- [ ] Firefox
- [x] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [x] Internal (Microsoft)
- [ ] Customer request

**Comment by jasonnutter** [comment]
@arcadiogarcia I'm unable to reproduce the behavior you describe. The Chromium extension sample will print out a log statement with the redirect URI that you must include as a "Single-Page Application" redirect URI in your app registration. This is set on the `PublicClientApplication`, meaning it will automatically added to each request, and it should not need to be added on each request. 

Did you add this redirect to your app registration?

**Comment by arcadiogarcia** [comment]
Yeah, I added the redirect URI in the azure portal and the same URI is set in the PublicClientApplication constructor (I just copied the sample code), but for me it doesn't work until I pass the same uri to getLoginUrl manually.

**Comment by arcadiogarcia** [comment]
I gave it a try multiples times and it turns out that what I saw before was just random luck, the auth attempts are failing at random and I happened to get a bunch of successes in a row when I added the redirectUri.

What could be causing that? My code is a TS version of the sample:

```
async function getLoginUrl(request: any): Promise<string> {
    return new Promise((resolve) => {
        msalInstance.loginRedirect({
            ...request,
            onRedirectNavigate: (url) => {
                resolve(url);
                return false;
            }
        });
    });
}

async function launchWebAuthFlow(url: string): Promise<AuthenticationResult> {
    return new Promise<AuthenticationResult>((resolve, reject) => {
        chrome.identity.launchWebAuthFlow({
            interactive: true,
            url
        }, (responseUrl: string) => {
            debugger;
            // Response urls includes a hash (login, acquire token calls)
            if (responseUrl.includes("#")) {
                msalInstance.handleRedirectPromise(`#${responseUrl.split("#")[1]}`)
                    .then(resolve)
                    .catch(reject)
            } else {
                // Logout calls
                resolve(null);
            }
        })
    })
}

 const url = await getLoginUrl({
                loginHint: user.email,
                redirectUri: redirectUri
            });

            return await launchWebAuthFlow(url);
```
![image](https://user-images.githubusercontent.com/9416356/108768971-3b02dc80-750d-11eb-8855-b462339c5b5d.png)
