### ISSUE TITLE
While building in prod mode in ES6 targeted project is not working as @azure/msal-angular library is targeting es5

### ISSUE THREAD

**Issue by sameerrswt** [AzureAD/microsoft-authentication-library-for-js#3066]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
-  `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- Angular
- [ ] React
- [ ] Other

## Description
My application is targeting ES6.

As I can see that @azure/msal-angular library is targeting ES5.

So when i am building my application in prod mode with build-optimizer=true and optimization=true. It works fine when I am set either of these properties to false.

it is not working and giving error.
"Must call super constructor in derived class before accessing 'this' or returning from derived constructor."
## Error Message
![image](https://user-images.githubusercontent.com/17155131/108823678-c43a1200-75e6-11eb-9177-e7dfb8beb2a6.png)

"Must call super constructor in derived class before accessing 'this' or returning from derived constructor."

I am able to replicate this issue on sample application provided in below repo by changing its target to ES6.

path for sample app:
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-angular-samples/angular6-sample-app/tsconfig.json

just change target to es6 and build in prod mode. application will stop working.

## MSAL Configuration
No change. As provided in sample.
```js
```

## Reproduction steps
I am able to replicate this issue on sample application provided in below repo by changing its target to ES6 in tsconfig file.

path for sample app:
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-angular-samples/angular6-sample-app/tsconfig.json

just change target to es6 and build in prod mode. application will stop working.

tsconfig.json
{
"compileOnSave": false,
"compilerOptions": {
"baseUrl": "./",
"outDir": "./dist/out-tsc",
"sourceMap": true,
"declaration": false,
"module": "esnext",
"moduleResolution": "node",
"emitDecoratorMetadata": true,
"experimentalDecorators": true,
"target": "es6",
"typeRoots": [
"node_modules/@types"
],
"paths": {
"jszip": [
"node_modules/jszip/dist/jszip.min.js"
]
},
"lib": [
"es2017",
"dom"
]
}
}
```js
```

## Expected behavior
It should work with ES6 in prod mode with build-optimizer=true and optimization=true in angular.json.
## Identity Provider

- [ ] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- Chrome
- Firefox
- Edge
- Safari
- IE
- Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by pkanher617** [comment]
@sameerrswt Thanks for opening this issue. It looks like you've opened this before as well, sorry for not getting back to you on this.

`msal-angular v1` is compiled for es5 to support IE11 browsers. Have you looked at `msal-angular v2`?
