### ISSUE TITLE
Setting active account doesn't persist between page loads

### ISSUE THREAD

**Issue by akshaybabloo** [AzureAD/microsoft-authentication-library-for-js#3075]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [x] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [x] Angular
- [ ] React
- [ ] Other

## Description

From the Angular B2C example

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/df55fda194a733a861c5ad08f12e5b2a3ff2108f/samples/msal-angular-v2-samples/angular11-b2c-sample/src/app/home/home.component.ts#L24-L26

I am using the redirect way of authentication (instead of pop up), the above line should set the account after authentication. But instead, this doesn't happen.

I confirmed it with - `console.log(this.authService.instance.getActiveAccount());` - this shows null. But `console.log(this.authService.instance.getAllAccounts());` - does print all the accounts.

## Error Message

No error messages

## MSAL Configuration

```js
export const b2cPolicies = {
  names: {
    signUpSignIn: 'B2C_1_SignUpSignInFlow',
    forgotPassword: 'B2C_1_PasswordReset',
    editProfile: 'B2C_1_ProfileEditing'
  },
  authorities: {
    signUpSignIn: {
      authority: 'https://gollahalliauth.b2clogin.com/gollahalliauth.onmicrosoft.com/B2C_1_SignUpSignInFlow',
    },
    forgotPassword: {
      authority: 'https://gollahalliauth.b2clogin.com/gollahalliauth.onmicrosoft.com/B2C_1_PasswordReset',
    },
    editProfile: {
      authority: 'https://gollahalliauth.b2clogin.com/gollahalliauth.onmicrosoft.com/B2C_1_ProfileEditing'
    }
  },
  authorityDomain: 'gollahalliauth.b2clogin.com'
};
```

## Reproduction steps

```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Identity Provider

- [ ] Azure AD
- [x] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by jo-arroyo** [comment]
@akshaybabloo Unfortunately, the current implementation of active account means that it does not persist, but must be set per page load. This is an enhancement we are looking to make. Today, please set the active account on each page load, after checking that interaction is complete. Please see our [FAQ](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/FAQ.md#how-do-i-get-and-set-active-accounts) and [sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/d5509a061349a67558abe543aa3845cc0d7119cb/samples/msal-angular-v2-samples/angular11-sample-app/src/app/app.component.ts#L42) for more details.
