### ISSUE TITLE
SyntaxError: Failed to execute 'measure' on 'Performance'

### ISSUE THREAD

**Issue by HristoStoevZ** [AzureAD/microsoft-authentication-library-for-js#3077]
Hello ,

After upgrade from 1.2.2 to 1.4.6 I start getting exception on this.msalAgent.acquireTokenSilent: 

## Library
 - [ ] `msal@1.4.6` 

## Framework
 - [ ] Other

## Description
After upgrade from 1.2.2 to 1.4.6 I start getting exception on this.msalAgent.acquireTokenSilent, and I am not able to get token 

## Error Message
Wed, 24 Feb 2021 12:59:54 GMT:1.4.6-Error SyntaxError: Failed to execute 'measure' on 'Performance': The mark 'start-fc4f7d01-a05b-4678-aeda-1f85e4bf19c9_c29040c3-f4f1-4faf-a730-0213d05a39c9-msal.http_event' does not exist.

## MSAL Configuration

```js
{
			auth: {
				authority: `${AUTHORITY}${SIGN_IN_POLICY}`,
				clientId: CommonSettings.b2cClientId,
				validateAuthority: false,
			},
			cache: {
				cacheLocation: 'localStorage',
				storeAuthStateInCookie: false,
			},
			framework: {
				isAngular: false,
			},
			system: {
				logger: new Logger((level, message, containsPii) => {
					if (containsPii) {
						return;
					}
					switch (level) {
						case LogLevel.Error:
							logger.error(message);
							return;
						case LogLevel.Info:
							logger.info(message);
							return;
						case LogLevel.Verbose:
							logger.debug(message);
							return;
						case LogLevel.Warning:
							logger.warn(message);
							return;
					}
				}),
			},
		}
```

## Reproduction steps
try to acquire token silently with: 
```js
const authResponse = await this.msalAgent.acquireTokenSilent({
				scopes: [SILENT_SCOPE],
			});
```

## Expected behavior
To be able to acquire token with no issues 

## Identity Provider
- [ ] Azure B2C Basic Policy

## Browsers/Environment
- [ ] Chrome

## Regression - Yes

- [ ] Did this behavior work before? - Yes
Version: 1.2.2.

**Comment by tnorling** [comment]
@HristoStoevZ I don't seem to be able to reproduce this. Are you able to reproduce this using our [B2C sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-core-samples/VanillaJSTestApp/app/b2c)? Can you share the verbose level logs and/or do some debugging to determine what's going on here?
