### ISSUE TITLE
Angular V2 First login event where is it?

### ISSUE THREAD

**Issue by whittssg** [AzureAD/microsoft-authentication-library-for-js#3079]
## Library
- [x] `@azure/msal-angular@2.x.x`

## Description
Hello, a few alpha versions ago i was able to hook into the first login using LOGIN_SUCCESS, i am using this to write the user to an SQL db on the server end but since i updated it no longer fires? 

I basically want to try and create the logged in user on their first login (not on view changes or api calls). This is what i had before:

 
    this.msalBroadcastService.msalSubject$
      .pipe(
        filter((msg: EventMessage) =>msg.eventType === EventType.LOGIN_SUCCESS      
        takeUntil(this._destroying$)
      )
      .subscribe((result) => {
         // check sql db for user an create if it does not exist

Thanks for any help.

**Comment by jo-arroyo** [comment]
@whittssg Which alpha version of msal-angular are you using? Can you also update the template above with your configuration? If you could enable logs and send us verbose logs, that would help too.
