### ISSUE TITLE
how to add redirect / popup to MS login in config

### ISSUE THREAD

**Issue by wy10cheng** [AzureAD/microsoft-authentication-library-for-js#3082]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [x] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

Hi All,

I am trying to impose MSAL to my React application, with the below guide:
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/initialization.md#redirect-apis

The guide does not mentioned clearly that, where should I add the redirect API in order to make my application redirect to MS login page?

Below is my index.js, which would show directly returned my App.js without logging in:

```
import React from 'react';
import ReactDOM from 'react-dom';
import 'index.css';
import App from 'App';
import * as serviceWorker from 'serviceWorker';
import { createStore } from 'redux'
import { Provider } from 'react-redux'
import reducer from 'store/reducer'

import { MsalProvider } from "@azure/msal-react";
import { Configuration,  PublicClientApplication } from "@azure/msal-browser";

//, window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()
const store = createStore(reducer);

const configuration = {
  auth: {
    clientId: '*************',
    authority: 'https://login.microsoftonline.com/*************'
  }
};

const pca = new PublicClientApplication(authProvider);

ReactDOM.render(
<Provider store={store}>
  <MsalProvider instance={pca}>
        <App />
    </MsalProvider>,
   </Provider>,

  document.getElementById('root')
);
serviceWorker.unregister();

```
Thank you in advance.

## Source

- [ ] Internal (Microsoft)
- [x] Customer request

**Comment by wy10cheng** [comment]
Anybody have some insights? Thanks

**Comment by pkanher617** [comment]
@wy10cheng Could you please make sure to fill out one of the [issue templates](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/.github/ISSUE_TEMPLATE)? I can see you are using react and browser, but may help speed things up in the future.

You may want to read through the [msal-react docs](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/typescript-sample/src) which should walk you through how to set up your react application correctly. The docs you reference are specific to msal-browser, which does not account for react-specific concepts.

If you have more questions after that, happy to answer them.

**Comment by wy10cheng** [comment]
@pkanher617 

Thanks a lot, i had updated the template, but now I had come another question.
Will open a new question.
