### ISSUE TITLE
After authentication, the auth redirect is not handled correctly by the msal-browser package on IOS safari

### ISSUE THREAD

**Issue by WilmsJochen** [AzureAD/microsoft-authentication-library-for-js#3086]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [ ] Angular
- [ ] React
- [ ] Other

## Error Message

After authentication, got redirected to this url
#state=eyJpZCI6Ijk1YjlhMGVjLWQ5ZDMtNDg0MS04MzcyLTQ3MWMxMjBiMDIxOCIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicmVkaXJlY3QifX0%3d&client_info=eyJ1aWQiOiI5Y2E4N2QxYy05Njc4LTQ2NDktYjc1Zi1mYmVmNmViYWViMDYtYjJjXzFhX3NpZ25pbiIsInV0aWQiOiJiYTkyZDRmMC1mMTJhLTRmNDMtOWM2ZS05Mzc5MGRlYjM1M2MifQ&code=eyJraWQiOiJMaE9BeEh1ZE9BS2xlbHNYOFFrTzdueG1wX3R2WU9HemlIM0Rqbm5nMXJZIiwidmVyIjoiMS4wIiwiemlwIjoiRGVmbGF0ZSIsInNlciI6IjEuMCJ9.Lh7i1uMJXhX3r5SUBDRPZfQCtGtnDLkiZBPWhF74qszv3tO8_-caWjRVknYGGiap-LIl0ov3_hCYRHyjyLI4_afxBEn2p8kA6Qv54_pQCvBWRubsC78ojWqNtYxlMZsCg778RR-FAZmUDmlErgqjqqhjgcd5C7tEHBbOAhvGkhEW942gL76vMWRcEFvMQMofVia0gggo_NPRGmOrGZgQCX4aZbRj0BYAGbgdShKfQwq_L_pUu--2ZaaND26yVq5IlaQxWgMTesvDey0r-vpvrzGC3o4m8U-lZoiIJsY-4JhutoDJOLR5bdExtXVLDtPEuKoxAjwSHgFtDTB-fkVHXw.oRyr--dokAtFjuk1.rHONCT7uhmdwtruFJLjejqjkwd73XwIs6xjf-ixlIUV0Nn2DSkG0iALhVjyZ1Y4cfLfBRVLZmh4O9ZQwbUgfyDghtzfLp_MGyP1EZ-SNTYzWrq-z9dVJ9C5tHzVEPOwxWi6iOTFHClOFpw5RvZM0lfzMpcExYcV0_nf0syeojhBwHZto4oMOmAHWoN3yFgLgyQsrawJ13P38f05zCDLsTjGR6vKg-afEaVatKITj-4oYR4BYNIIt0lEr3dOtaRfmrHi7aTdyxGlSMsDqnUJkNhw5v0ynD1rVxNv03MVVAQwhSV9rF8eNi9SrRFiVFtmREVHwXURarsck1lwmWI3Cv7OphzFPk8gUNiwSRiSa7KGdBAEkdgVJXM6rlNFR2RArdc4HsuOYg6EHs8BYn04fv5mUAg-vc_MCrXgZ3zdfGx0_wF_ukomVEbhxHM1FnLKK-D6Cgme2Mwcf5UrWkKRh6mIBDdmvlwhfi9kJYeBskhmWmZ3LjLAelO1mqAqXlfZH0s-gyiRadLzAq7P5S5nxw0kB0YrYhf8d4vQHocLouovxm3HxgDceKDpI4Uqx9emSMV3bDM6KMlZ4ndomyhpWU9MIweab9z_fY2zlSU-cRY8duUJOAnamqZbi0izS8fI0yqAYjJ-Qqrtq_rMXURRqZoXjb61XPpI32ClGZjTtkUAcL8uUWVOwPsc5RqT_zLwzDZX-gpY09-YU80Sx3Hyx5hwHWxhUJBPMbRKOecCYqRKVnEPkbLuFZswqrcdaoWNzuM6swGvnxvRe8cO8LHwPAv9F5zyzQjMfFEMLSIU.cdVYnpuJTMPN1sz-jjDE0w

This redirect opened in a new tab in the safari browser. As a user i see the home page of the application as if he is not logged in. Even the cookies need to be accepted again. 

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps
Use the msal-browser package @azure/msal-browser": "^2.11.2. 
Bug appears on both normal AD and B2C AD.

1) Open your app on IOS safari
2) Login with msal loginRedirect
3) User provides credentials
4) auth redirect to home page
5) New tab is opened in safari
6) User is not logged in. 

```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.

cacheLocation: "localStorage",
storeAuthStateInCookie: false

Using the loginRedirect function of the msal package.
```

## Expected behavior
User should be logged in. Our setup is working in chrome. 

## Identity Provider

- [ X] Azure AD
- [ ] Azure B2C Basic Policy
- [ X] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [ ] Chrome
- [ ] Firefox
- [ ?] Edge
- [ X] Safari
- [ ?] IE
- [ ?] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Testers confirmed it worked before.
Version: Unknown

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by pkanher617** [comment]
@WilmsJochen Could you post a snippet of code showing how you are invoking the redirect and how you are handling the response? Are you making sure to call `handleRedirectPromise()` on the page that is registered as the redirect URI? Please make sure you read through the [docs](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-browser#usage) for `msal-browser`
