### ISSUE TITLE
SSO works sometimes but fails often with  invalid_grant error. AADSTS9002313.

### ISSUE THREAD

**Issue by cghaddar** [AzureAD/microsoft-authentication-library-for-js#3088]
I am using SSO for Office add-in.  I obtain an authorization code with a request to https://login.microsoftonline.com/common/oauth2/v2.0/authorize
and redeem the code for an access token with a post to https://login.microsoftonline.com/common/oauth2/v2.0/token. The SSO works for some users but fails for others.  Here is a typical response received from the token server: 

{"error":"invalid_grant","error_description":"AADSTS9002313: Invalid request. Request is malformed or invalid.\r\nTrace ID: f351e59c-dc4f-4b10-8293-4e6fe8c8c600\r\nCorrelation ID: 196c96ec-1310-4afb-8d4b-ab70d77bb816\r\nTimestamp: 2021-02-22 00:34:40Z","error_codes":[9002313],"timestamp":"2021-02-22 00:34:40Z","trace_id":"f351e59c-dc4f-4b10-8293-4e6fe8c8c600","correlation_id":"196c96ec-1310-4afb-8d4b-ab70d77bb816","error_uri":"https://login.microsoftonline.com/error?code=9002313"} 

The App is configured in Azure portal to support accounts in any organizational directory and personal Microsoft accounts.

**Comment by pkanher617** [comment]
@cghaddar Could you please fill out one of our [issue templates](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/.github/ISSUE_TEMPLATE)? Without more information about what library you are using we cannot debug this issue.

**Comment by cghaddar** [comment]
@pkanher617 Thank you for the reply.  I did figure out the error eventually.  The auth. code should be url decoded before redeeming. Some codes apparently did not require decoding while others did.
