### ISSUE TITLE
After clicking on a button to open the login popup, it redirects me to the same page I was previously

### ISSUE THREAD

**Issue by ncesar** [AzureAD/microsoft-authentication-library-for-js#3091]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [X] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [ ] Angular
- [X] React
- [ ] Other

## Error Message

![image](https://user-images.githubusercontent.com/29064514/109299226-8968f180-7813-11eb-882c-1a236934a5d4.png)
Hi all! I have setup my react application following the silento token example from this repo. The problem I'm having is that sometimes, randomly when I try to login using the button it opens a new tab but instead of being the redirect from Microsft it opens my application login url. Anyone knows why?

## Reproduction steps

```js
const AuthWidget = ({ showLogo, color }) => {
  const dispatch = useDispatch();
  const { message, resultType } = useSelector(({ login }) => login.loginForm);
  const { instance, accounts, inProgress } = useMsal();
  const [clicked, setClicked] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(false);

  const account = useAccount(accounts[0] || {});

  useEffect(() => {
    if (account && inProgress === "none" && clicked) {
      setLoading(true);
      setError(false);
      instance
        .acquireTokenSilent({
          ...apiRequest,
          account,
        })
        .then(response => {
          setError(false);
          dispatch(loginUseCases.auth(response));
        })
        .catch(error => {
          console.log(error);
          setLoading(false);
          setError(true);
        });
    }
  }, [account, inProgress, instance]);

  const handleLogin = () => {
    localStorage.clear();
    setClicked(true);
    instance.loginPopup();
  };

  return (
    <>
      <div className="container-fluid fade-in">
        <div className="row login-container align-items-center">
          <div className="col">
            <section className="login-card">
              <div className="row m-0">
                <div className="col-12 p-0 login-content__logo">{showLogo && <Logo />}</div>
              </div>
              <div className="login-card__body">
                <Loading isActive={loading} color={color} onlyHide>
                  <div className="container-fluid">
                    <MicrosoftButton onClick={handleLogin} />
                  </div>
                </Loading>
              </div>
            </section>
          </div>
        </div>
      </div>
      {error && (
        <div className="alert-holder">
          {message && <AlertDialog message={message} type={resultType || "error"} />}
        </div>
      )}
    </>
  );
};
```

my msalConfig:

```js
const msalConfig = {
  auth: {
    clientId: getClientId(),
    authority: "https://login.microsoftonline.com/my-id",
    redirectUri: `${currentLocationURL}`, //this is my homepage - const currentLocationURL = window.location.origin;
  },
  cache: {
    cacheLocation: "sessionStorage", //i have tried localstorage previously
    storeAuthStateInCookie: false,
  },
};

const loginRequest = {
  scopes: ["openid", "profile", "User.Read"],
  forceRefresh: false,
};

const apiRequest = {
  scopes: ["user.read"],
  forceRefresh: false,
};
```

## Expected behavior
It was expected that it would login without problems
## Identity Provider

- [X] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [X] Chrome
- [ ] Firefox
- [X] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by pkanher617** [comment]
@ncesar Could you add some code showing how the PublicClientApplication instance is being initialized?

If you have any logs from the browser that would also be helpful.

**Comment by ncesar** [comment]
> @ncesar Could you add some code showing how the PublicClientApplication instance is being initialized?
> 
> If you have any logs from the browser that would also be helpful.

Hey, the pca is being initialized in our index.js file

```
import React from "react";
import { render } from "react-dom";
import { Provider } from "react-redux";
import { ThemeProvider } from "styled-components";
import { store, history, persistor } from "store/store";
import API, { appClientAPI, authAPI } from "utils/api";
import { startTrackingUser, uncoverText } from "utils/utility";
import ls from "local-storage";
import { PersistGate } from "redux-persist/lib/integration/react";
// MSAL IMPORTS
import { msalConfig } from "utils/config";
import { PublicClientApplication } from "@azure/msal-browser";
// MSAL IMPORTS
import App from "./App";
import * as serviceWorker from "./serviceWorker";
import GlobalStyle from "./assets/style/global";
import theme from "./assets/style/theme";
import "./assets/css/colors.css";
import "./assets/sass/main.scss";

API.defineRequestInterceptor(localStorage);
API.defineResponseInterceptor(history);
appClientAPI.defineResponseInterceptor(history);
authAPI.defineRequestInterceptor();


startTrackingUser();
const msalInstance = new PublicClientApplication(msalConfig);
render(
  <Provider store={store}>
    <PersistGate loading={null} persistor={persistor}>
      <ThemeProvider theme={theme}>
        <GlobalStyle />
        <App history={history} pca={msalInstance} />
      </ThemeProvider>
    </PersistGate>
  </Provider>,
  document.getElementById("root"),
);

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: http://bit.ly/CRA-PWA
serviceWorker.unregister();

```

**Comment by pkanher617** [comment]
Are you seeing any logs on the browser console relating to popup errors (such as a `user_cancelled` or a `monitor_window_timeout`)? 

We are not able to reproduce this in our current samples. Could you try using one of our [samples](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/react-router-sample) and see if you are getting the same behavior? If you are, you can post the link to the sample here.

**Comment by ncesar** [comment]
> Are you seeing any logs on the browser console relating to popup errors (such as a `user_cancelled` or a `monitor_window_timeout`)?
> 
> We are not able to reproduce this in our current samples. Could you try using one of our [samples](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/react-router-sample) and see if you are getting the same behavior? If you are, you can post the link to the sample here.

I will try to reproduce the error but it seems to be in my end. Thanks for your time .
