### ISSUE TITLE
Typescript definitions of IPublicClientApplication.getActiveAccount and IPublicClientApplication.logout do not match

### ISSUE THREAD

**Issue by tcc-sejohnson** [AzureAD/microsoft-authentication-library-for-js#3111]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.11.2`
- [ ] `@azure/msal-node@1.x.x`
- [x] `@azure/msal-react@1.0.0-alpha.6`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [ ] Angular
- [ ] React
- [ ] Other

## Error Message
`Type 'AccountInfo | null' is not assignable to type 'AccountInfo | undefined'.
  Type 'null' is not assignable to type 'AccountInfo | undefined'.ts(2322)`

## MSAL Configuration

Not providing this, as it has no bearing on the bug!

## Reproduction steps

This is a super simple issue. The definition of `IPublicClientApplication.logout` has its `account` key defined as `AccountInfo | undefined`, while the return type of `IPublicClientApplication.getActiveAccount` is `AccountInfo | null`. It seems like these two signatures should match, so that you can do the following:

```typescript
() => instance.logout({ account: instance.getActiveAccount() });
```

Instead of having to do this:

```typescript
() => instance.logout({ account: instance.getActiveAccount() ?? undefined });
```

Obviously not a game-breaker, but seems like a pretty simple QOL change.

## Identity Provider

- [x] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [x] Customer request

**Comment by pkanher617** [comment]
@tcc-sejohnson Thanks for opening this! This is definitely something we can take a look at. I will try to push a fix for this shortly.

**Comment by tcc-sejohnson** [comment]
@pkanher617 Awesome! There are a few of these I've noticed. I'll see if I can catalogue them as I come upon them.
