### ISSUE TITLE
Best practice to retrieve a token, access backend and Graph API

### ISSUE THREAD

**Issue by m2nhawk** [AzureAD/microsoft-authentication-library-for-js#3113]
## Library
- [x] `@azure/msal-react@1.x.x`

## Frontend Framework
- [x] `React with TypeScript`

## Backend Framework
- [x] `Spring Boot with Java`

## Identity Provider
- [x] `Azure AD`

## Description

What are the best practices for SSO (single sign-on) in the frontend with OAuth 2.0 using authorization code flow with PKCE and accessing the Graph API in the backend? 

Earlier I was using react-adal and the implicit flow to retrieve a token in the frontend and access the backend with that. The backend uses the `azure-active-directory-spring-boot-starter` Library. 
After the request the backend accesses the Graph API to get needed Information. It was a Web Application in Azure AD.

Currently I access the id token and the access token in the frontend with the msal-react. So this means now I'm using the SPA (single-page application in Azure AD) with authorization code flow. In the frontend I retrieve both: the access token and the id token. To access the backend I need the id token. But I need the access token too, so that the backend could access the Graph API. I don't think this is a good idea to send both of them in Header or to send it at all. Both the frontend and the backend use the same Azure Application. The backend has a Secret. Important is that I **do not need the frontend directly access the Graph API**.
 But is this a good approach to send both the id token for the backend authentication and the access token to access Graph API on the backend side?

## Source

- [x] Internal (Microsoft)
- [ ] Customer request

**Comment by pkanher617** [comment]
@m2nhawk Thanks for opening this. Could you make sure to add the [question template](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/.github/ISSUE_TEMPLATE/question.md) to your issue?

Could you explain a few things about the scenario you are describing?

- Could you explain what you mean by SSO? Does this just mean the ability to get tokens without user interaction?
- How are you sending the id token and access token to your backend from the front-end?
- Are these apps configured in the same way? (i.e. client id, etc.)

**Comment by m2nhawk** [comment]
I've updated the issue.

**Comment by drinkingjasminegreentea** [comment]
I'm interested in the same topic. I have a front end built in nextjs and backend in ,net core web api. 
Front end is using Azure ad b2c with social login. Azure is sending the IdToken that includes idp_access_token claim in it. I'm not sure if I should be sending that to my API and how will my API know which user is accessing its resource. 

I need to restrict the access so users can only read the data that belongs to them.

**Comment by joshwilson00** [comment]
I am also interested in the same topic, I am looking at using react for the front end and have an express or koa backend for example, not sure if i should go all the authentication on the front end and send the bearer token to the backend to make the requests, or how to do the authentication on the backend with a react front end.

**Comment by derisen** [comment]
@m2nhawk @drinkingjasminegreentea @joshwilson00 take a look at this sample [React SPA calling Express web API](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/tree/main/3-Authorization-II/1-call-api). You can plug-in a different web API, for instance .NET via [Angular SPA calling .NET web API](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi). You can further use [app roles & security groups](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-dotnetcore-webapi-roles-groups) to control access to your back-end.

**Comment by joshwilson00** [comment]
@derisen Many thanks for that example, it is very useful! One question I have is that say for example I have multiple different endpoints on the express server, all with their own scope, can I just create a new BearerStrategy for each since the options will need to be slightly different (scope will need to be different).

**Comment by derisen** [comment]
You can certainly create multiple strategies (for example, [see](https://stackoverflow.com/questions/43885351/multiple-policies-for-oidcstrategy-using-passport-azure-ad/43945140#43945140)). But in this case you don't necessarily need that. Instead, configure the options as shown below:

```javascript
const options = {
    // ...
    scope: ["scope1", "scope2"]
};
```

From the [passport-azure-ad documentation](https://github.com/AzureAD/passport-azure-ad#4212-options):

> scope (Optional)
> 
> This value is an array of scopes you accept. If this value is provided, we will check if the token contains one of these accepted scopes. If this value is not provided, we won't check token scopes.

Keep in mind that the access token you obtain for your API will contain all the previously consented scopes for that API, in addition to the scope you currently requested. 

Finally, you can also omit the `scope` parameter, and manually check if the ` req.authInfo['scp']` matches the scope you expect.
