### ISSUE TITLE
msal-browser - Error: Uncaught (in promise): BrowserAuthError: interaction_in_progress: Interaction is currently in progress.

### ISSUE THREAD

**Issue by voigtd** [AzureAD/microsoft-authentication-library-for-js#3117]
## Library

- [ x ] `@azure/msal-browser@2.11.2`

## Framework

- [ x ] Angular 7

## Description
I'm getting what seems to be a common error:  `BrowserAuthError: interaction_in_progress`. On initial login and redirection, everything works. However, when a second attempt is made, then the error appears. It seems that the initial promise is not resolving because of the redirect that is occurring. I've read a few issues about the same error being thrown. The app is currently Angular 7 but it will be upgraded to the most recent Angular soon, so I'd prefer to use the general MSAL library and not the Angular specific lib.

## Error Message

```
Error: Uncaught (in promise): BrowserAuthError: interaction_in_progress: 
Interaction is currently in progress. 
Please ensure that this interaction has been completed before calling an interactive API.
BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.
```

## Reproduction steps
This is the current code:
```
        const msalConfig = {
          auth: {
            clientId: example-client-id,
            redirectUri: localhost:3000/example-redirect,
          },
        };

        const msalInstance = new msal.PublicClientApplication(msalConfig);

        msalInstance.loginRedirect();

        msalInstance
          .handleRedirectPromise()
          .then((tokenResponse) => {
            if (tokenResponse === null) {
              // If the tokenResponse === null, you are not coming back from an auth redirect.
            } else {
              // If the tokenResponse !== null, then you are coming back from a successful authentication redirect.
            }
          })
          .catch((error) => {
            // handle error, either in the library or coming back from the server
          });
```

## Expected behavior
No errors when attempting to login for a second time.

## Identity Provider

- [ x ] Azure AD

## Browsers/Environment

- [ x ] Chrome

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [ x ] Customer request

**Comment by pkanher617** [comment]
@voigtd You need to make sure that `handleRedirectPromise` resolves before the `loginRedirect` API is invoked. 
```javascript
const msalConfig = {
          auth: {
            clientId: example-client-id,
            redirectUri: localhost:3000/example-redirect,
          },
        };

        const msalInstance = new msal.PublicClientApplication(msalConfig);

        msalInstance
          .handleRedirectPromise()
          .then((tokenResponse) => {
            if (tokenResponse === null) {
              // If the tokenResponse === null, you are not coming back from an auth redirect.
              msalInstance.loginRedirect();
            } else {
              // If the tokenResponse !== null, then you are coming back from a successful authentication redirect.
            }
          })
          .catch((error) => {
            // handle error, either in the library or coming back from the server
          });
```

**Comment by pkanher617** [comment]
> The app is currently Angular 7 but it will be upgraded to the most recent Angular soon, so I'd prefer to use the general MSAL library and not the Angular specific lib.

The Angular wrapper library should support the latest versions of Angular, so I highly recommend taking a look at the v2 library when it is generally available, as it will take care of a lot of the heavy lifting in Angular.

**Comment by voigtd** [comment]
@pkanher617 Thank you.

Resolving `handleRedirectPromise` before the `loginRedirect` API is used solves this issue.
