### ISSUE TITLE
Login popup not working on mobile

### ISSUE THREAD

**Issue by goldylucks** [AzureAD/microsoft-authentication-library-for-js#3118]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.3.1`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework
- [ ] Angular
- [x] React 16.13.1
- [ ] Other

## Description

The calling the logging popup opens a new window, starts the logging process, and then stays on the new window and nothing hppens. On desktop/laptop it works fine.

## Error Message
no error message

## MSAL Configuration

```js
import * as msal from '@azure/msal-browser'
const msalConfig = {
  auth: {
    clientId: process.env.REACT_APP_MICROSOFT_CLIENT_ID,
    redirectUri: window.location.origin,
  },
}

const msalInstance = new msal.PublicClientApplication(msalConfig)

// inside async function
const response = await msalInstance.loginPopup({ scopes: [] })
console.log(response) // <-- this never gets called on mobile
```

## Reproduction steps
Stated above

## Expected behavior
Calling msalInstance.loginPopup should return info about the user and continue the execution flow

## Identity Provider

- [x] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
no

## Security

- [ ] Is this issue security related?
- [ ] No

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by goldylucks** [comment]
Here's a screencap video 

https://user-images.githubusercontent.com/6963212/109619452-76bb2900-7b41-11eb-9fed-04cc0d7b33de.mp4

**Comment by pkanher617** [comment]
@goldylucks Is it a requirement for you to use the popup flow? Or could you use the redirect flow for login?

Do you know if you have any error messages in the browser?

Also, I'd recommend upgrading to the latest version of msal-browser (v2.12.0) and making sure you are still having the same issues.

**Comment by goldylucks** [comment]
not a requirement, just better UX :)

**Comment by hazard2k** [comment]
I'm also experiencing this with the Angular wrapper of the MSAL 2.x library.

**Comment by jasonnutter** [comment]
Apologies for the delay, we'll look into this and follow up if we need more information.

**Comment by tnorling** [comment]
@goldylucks Is this still an issue with the latest version of msal-browser v2.14.2? If so are you getting any error messages?

**Comment by goldylucks** [comment]
dunno, I no longer work on that project, closing

**Comment by Gameboy98** [comment]
Still facing this issue, Please Refer This:
const { instance } = useMsal();
instance
  .loginPopup(loginRequest)
  .then((res) => {
    localStorage.setItem('msToken', JSON.stringify(res))
    callMsGraph(res.accessToken).then((response) => {
      handleLogin(employee_code);
    }); // <-- This never gets called on Mobile Devices
  })
  .catch((e) => {
    console.log(e);
  });

**Comment by Bhavin-Repo** [comment]
@Gameboy98  did you find the solution? i am also facing issue while login to my app using mobile browser.
I cant even see the redirection to microsoft login page while using chome without incognito in mobile browser.
For desktop browser everything works fine

**Comment by rwilliams3088** [comment]
Still an issue

**Comment by egbertn** [comment]
Indeed. Problematic

**Comment by alisonsandrade** [comment]
Still no solution? Has anyone managed to sort this out?

**Comment by clemlesne** [comment]
Same there.[As mentioned in the documentation](https://learn.microsoft.com/en-us/azure/active-directory/develop/reference-third-party-cookies-spas#overview-of-the-solution), an idea would be to use authorization code flow for initial authentication then refresh token flow.

I didn’t found yet any samples.

Seems related to:

- https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1248
- https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/3407
- https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Known-issue-on-Safari

**Comment by egbertn** [comment]
At the end, it for now only can work with redirect login.  The popup really does too much which not all browsers  allow especially on the Mobile. My collegue finally got it working.

**Comment by clemlesne** [comment]
@egbertn I confirm that is working, with redirect instead of popups.

Code example: https://github.com/clemlesne/private-gpt/commit/87be7258bec070e4fffec80d45cf8c4ea6bd8bf3.

**Comment by dijitald** [comment]
wow. 2025 and this is still a problem.
