### ISSUE TITLE
How to debug msal:loginFailure, AADB2C90085?

### ISSUE THREAD

**Issue by voloszad** [AzureAD/microsoft-authentication-library-for-js#3119]
## Library
- [ ] `@azure/msal-browser@2.11.2`
- [ ] `@azure/msal-react@1.0.0-alpha.6`

## Framework
- [ ] React 16.14 (CRAv3)

## Description

~3 weeks ago I switched from MSAL v1 to MSAL-Browser  and MSAL-React. Everything worked as expected for about two weeks, when suddenly 2 of the 3 envs started to misbehaving at login with the custom policies.
Most of the issues are resolved (reverting a change in the policy and regenerating the singing key), but still facing a mysterious one. Not sure what and where is failing.

I'm using the the useMsal() hook to get the instance and initiate a loginRedirect with a signed token if there is no authenticated user:

```
      await instance.loginRedirect({
        authority: authority for the policy,
        scopes: [api endpoint for access token],
        extraQueryParameters: {
          id_token_hint: signed id token ,
        },
      });
```

If it fails, it fails for the  '.../oauth2/v2.0/token' endpoint POST request. Seemingly all the required data is provided (code/code_verifier etc.), but the response is:

``
{
  "error": "invalid_grant",
  "error_description": "AADB2C90085: The service has encountered an internal error. Please reauthenticate and try again.\r\nCorrelation ID: 84......2b\r\nTimestamp: 2021-03-02 13:41:45Z\r\n"
}
``  

Now I cannot see or catch this error in any way. B2C trace says everything was ok, 'JourneyCompleted' so no exceptions in AppInsights and it does not go to catch either with the loginRedirect, I see it only in the browser network tab and Fiddler. Although msal-browser emits loginFailure:

```
 @azure/msal-browser@2.11.2 : Info - Emitting event: msal:handleRedirectStart
 @azure/msal-react@1.0.0-alpha.6 : Info - MsalProvider - msal:handleRedirectStart results in setting inProgress to handleRedirect
 @azure/msal-common@4.0.1 : Info - in acquireToken call
 
 POST https://xxx.b2clogin.com/xxx.onmicrosoft.com/b2c_1a_xxx/oauth2/v2.0/token 400 (Bad Request)
 
 @azure/msal-browser@2.11.2 : Info - BrowserCacheManager.cleanRequestByInteractionType: Removing temporary cache items for state: eyJ...
 @azure/msal-browser@2.11.2 : Info - Emitting event: msal:loginFailure
 @azure/msal-react@1.0.0-alpha.6 : Info - MsalProvider - no account changes
 @azure/msal-react@1.0.0-alpha.6 : Info - MsalProvider - msal:loginFailure results in setting inProgress to none
 @azure/msal-browser@2.11.2 : Info - Emitting event: msal:handleRedirectEnd
 @azure/msal-react@1.0.0-alpha.6 : Info - MsalProvider - no account changes
```

Any idea how to approach this? Can it be an MSAL bug or  it must be a custom policy issue?
This solution worked for weeks (with implicit flow and now with the authorization code flow).

**Comment by pkanher617** [comment]
@voloszad Could you open a ticket with the B2C support service? It sounds like this is an issue with the B2C service. You can file a support ticket [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options) and link this issue in that ticket.

**Comment by voloszad** [comment]
@pkanher617 Thank you for the response. We did that in the same time. No conclusion from the support yet, but it's definitely either or a combination of the custom policy or identity server.

Still curious if there is a token endpoint error, why can't I catch it in the application with MSAL?
Currently if the root page is protected and the user tries to sign in, after redirecting back to the app the user gets in a loop. MSAL knows there was a failure, but the interesting part, that the authentication was successful from B2C side , just the tokens never arrived, hence the loop.  
Login page is not showing up again. Because there is a valid session from the user, MSAL calls for token, but never gets them, page reloads MSAL calls B2C again and it goes around again.

**Comment by pkanher617** [comment]
> Still curious if there is a token endpoint error, why can't I catch it in the application with MSAL?

The error you posted looks like it is in the format of an error object created by MSAL. Where is this error object coming from?

MSAL should be throwing the error in `handleRedirectPromise`, so you should be able to surround this with a `try/catch` or using a `.catch` block on the promise returned from this API. If you aren't seeing a ServerError coming from this we can investigate it. 

> Currently if the root page is protected and the user tries to sign in, after redirecting back to the app the user gets in a loop. MSAL knows there was a failure, but the interesting part, that the authentication was successful from B2C side , just the tokens never arrived, hence the loop

If we aren't getting tokens from the service, there isn't much we can do other than forward whatever error the service has given us. The easiest way to ensure that the app doesn't loop is to only call loginRedirect when `handleRedirectPromise` returns null, because that means that it has not detected an authentication response hash. However if, as you are describing, the `handleRedirectPromise` API is not returning any values, there is probably some other issue going on. If you can, please post a snippet of how your app is handling redirects and we can assist you further.
