### ISSUE TITLE
Version 0.1.6 not working on npm

### ISSUE THREAD

**Issue by DavidHenri008** [AzureAD/microsoft-authentication-library-for-js#312]
The new version 0.1.6 cannot be installed from npm. It seems to have a version mismatch. 
Here is the log file:

> info outdated updating [ { dep:
703 info outdated      { package: [Object],
703 info outdated        path: 'C:\\Git\\my-pjt',
703 info outdated        parent: [Object],
703 info outdated        isMissing: true },
703 info outdated     depname: 'msal',
703 info outdated     current: '0.1.5',
703 info outdated     wanted: '0.1.6',
703 info outdated     latest: '0.1.6',
703 info outdated     req: '0.1.6',
703 info outdated     what: 'msal@0.1.6' } ]
704 silly install loadCurrentTree
705 silly install readLocalPackageData
706 http fetch GET 200 https://registry.npmjs.org/msal 24ms (from cache)
707 silly registry:manifest no matching version for msal@0.1.6 in the cache. Forcing revalidation
708 http fetch GET 304 https://registry.npmjs.org/msal 73ms (from cache)
709 silly fetchPackageMetaData error for msal@0.1.6 No matching version found for msal@0.1.6
710 timing stage:rollbackFailedOptional Completed in 1ms
711 timing stage:runTopLevelLifecycles Completed in 1863ms
712 verbose type version
713 verbose stack msal: No matching version found for msal@0.1.6
713 verbose stack     at pickManifest (C:\Users\AppData\Roaming\npm\node_modules\npm\node_modules\npm-pick-manifest\index.js:65:11)
713 verbose stack     at fetchPackument.then.packument (C:\Users\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\fetchers\registry\manifest.js:52:18)
713 verbose stack     at tryCatcher (C:\Users\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
713 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
713 verbose stack     at Promise._settlePromise (C:\Users\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
713 verbose stack     at Promise._settlePromise0 (C:\Users\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
713 verbose stack     at Promise._settlePromises (C:\Users\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
713 verbose stack     at Async._drainQueue (C:\Users\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
713 verbose stack     at Async._drainQueues (C:\Users\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
713 verbose stack     at Immediate.Async.drainQueues (C:\Users\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
713 verbose stack     at runCallback (timers.js:794:20)
713 verbose stack     at tryOnImmediate (timers.js:752:5)
713 verbose stack     at processImmediate [as _immediateCallback] (timers.js:729:5)

**Comment by nehaagrawal** [comment]
@DavidHenri008  This looks like an issue with npmjs. We are following up with them. We will get back to you once we hear from them.

**Comment by rohitnarula7176** [comment]
@DavidHenri008 We just received a response from npm and the issue is resolved now. You should now be able to download the latest version of msal.
