### ISSUE TITLE
Trying to find what changed for msal-angular 1.1.2 and msal 1.4.4

### ISSUE THREAD

**Issue by mike-little** [AzureAD/microsoft-authentication-library-for-js#3120]
## Library

- [ X] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [X ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

I am trying to see what was changed from msal-angular 1.1.1 to 1.1.2 and msal 1.4.3 to 1.4.4.  I have looked at code branches and closed PRs but having trouble determining which branches and PRs to look at.  Can you please guide me on which branch or PRs to look at.

## Source

- [ ] Internal (Microsoft)
- [ X] Customer request

**Comment by pkanher617** [comment]
@mike-little There are changelogs available for msal [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/changelog.md#144) and msal-angular [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/changelog.md#112). If you would like to see the branches, you can visit our [Releases](https://github.com/AzureAD/microsoft-authentication-library-for-js/tags?after=msal-browser-v2.8.0) page and look at the tags for the versions you want to find.
