### ISSUE TITLE
Compilation error at node_modules/@azure/msal-react/index.d.ts

### ISSUE THREAD

**Issue by fan-boy** [AzureAD/microsoft-authentication-library-for-js#3121]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [x] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [ ] Angular
- [x] React v 16.3.1
- [ ] Other

## Description
Added image in next comment.
## Error Message
Build time error in node_modules/@azure/msal-react/dist/index.d.ts(5,1)
Declaration or statement expected.

## MSAL Configuration

```js
// Provide configuration values here.
{
auth: {
    clientId: AzureActiveDirectoryAppClientId,
    authority: b2cPolicies.authorities.signUpSignIn.authority,
    knownAuthorities: [b2cPolicies.authorityDomain,b2cPolicies.authorities.forgotPassword.authority],
    redirectUri: "http://localhost:3000/auth", window.location.origin
    postLogoutRedirectUri: "/", 
    navigateToLoginRequestUrl: true,
    
  },
  cache: {
    cacheLocation: "sessionStorage",
    storeAuthStateInCookie: false,
  },
  system: {
    loggerOptions: {
      loggerCallback: (level, message, containsPii) => {
        if (containsPii) {
          return;
        }
        switch (level) {
          case LogLevel.Error:
            console.error(message);
            return;
          case LogLevel.Info:
            console.info(message);
            return;
          case LogLevel.Verbose:
            console.debug(message);
            return;
          case LogLevel.Warning:
            console.warn(message);
            return;
        }
      },
    },
  },
}

// For Azure B2C issues, please include your policies.
names: {
        signUpSignIn: "b2c_1_susi",
        forgotPassword: "b2c_1_reset",
        editProfile: "b2c_1_edit_profile"
    },

```
## Reproduction steps
import * from "@azure/msal-react" in any file

## Expected behavior
No compile time error
## Identity Provider

- [ ] Azure AD
- [x] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [x] Internal (Microsoft)
- [ ] Customer request

**Comment by fan-boy** [comment]
![image (1)](https://user-images.githubusercontent.com/16851801/109688381-36dc5c00-7baa-11eb-9e85-7042f7ad0f5c.png)

**Comment by tnorling** [comment]
@fan-boy I'm not able to reproduce this. Can you check your typescript environment? Are you able to reproduce this using our [Typescript sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/typescript-sample)?

**Comment by fan-boy** [comment]
I upgraded my typescript to 4.0.5 from 3.7.5 . Works fine now. Thanks for your help :)
