### ISSUE TITLE
Question about auth-config.json file

### ISSUE THREAD

**Issue by dmccolloughOneGas** [AzureAD/microsoft-authentication-library-for-js#3125]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.11.0`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [X] `@azure/msal-angular@2.0.0-alpha.6`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Question about auth-config.json file

If I produce a production build using the command ng build —prod, it appears the values of auth-config.json file read at compile time and embedded in the compiled code.

I’m running our Angular Web Application in IIS.

I want to change these values when I move the web application from one environment to another (Dev - Test - Qual - Prod) without recompiling the code between environments.

I have a TFS On-Prem automated build pipeline that produces the build.

I then use a TFS On-Prem automated release to put the files on our Web Server, as part of that process we are using variables in the release template to replace the values.
I’m changing the values of the redirectUri and the postLogoutRedirectUri

I can see that the files have been changed on the file system when I look at each environment, but at runtime as an example for Test I’m getting an error because once the login occurs and the redirect happens it’s trying to redirect to http://localhost:4200

I’ve tried:
    Adding an exclude section to the tsconfig.app.json file that excludes the auth-config.json file. Didn’t work.
    I’ve tried moving the auth-config.json file to a different location and updating the import so that it can be found. Didn’t work.

So how do I accomplish this?

**Comment by pkanher617** [comment]
@dmccolloughOneGas I don't think this can be done with a .json file. You could use a templating engine or a JS/TS file to accomplish this, but the JSON itself cannot do variable replacement.

**Comment by dmccolloughOneGas** [comment]
@pkanher617 Would you have an example of how to do this with a templating engine or a JS/TS file?

**Comment by tnorling** [comment]
@dmccolloughOneGas You can take a look at our samples [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-browser-samples/VanillaJSTestApp2.0/app/default/authConfig.js)

Since the config is an object you should be able to manipulate it as needed.

**Comment by dmccolloughOneGas** [comment]
Thomas,

I appreciate you taking the time to look at and respond to my question.

I have reviewed the samples you suggested and it doesn't solve my issue.

Let me explain what I’m trying to accomplish.

Our organization, wants to build / compile the code once and deploy to multiple environments without re-building / compiling the code for each environment. We want to be able to change the endpoint Uri’s at runtime.

So our Dev environment, the website address that the users type in the browser is: https://somewebsitename-D.domainname.com and the corresponding API endpoint is: https://SomeWebSiteAPI-D.domainname.com/api/
Our Test environment, the URL’s are the same with the exception of -D becomes -T
Our Qual environment, the URL’s are the same with the exception of -D becomes -Q
Our Production environment, drops the -D completely and the website name becomes https://somewebsitename.domainname.com and the corresponding API endpoint is https://SomeWebSiteAPI.domainname.com/api/

The only items that changes in auth-config.json between our environments is the redirectUri, postLogoutRedirectUri and apiBaseUrl, here is a snippet of our auth-config.json file.
    "configuration": {
        "redirectUri": "https://somewebsitename-D.domainname.com",
        "postLogoutRedirectUri": " https://somewebsitename-D.domainname.com "
    },
    "apiBaseUrl": https://SomeWebSiteAPI-D.domainname.com/api/

What I’m finding is when I produce a build of my angular application with the command: ng build –prod, the auth-config.json file values get hard coded into the app.module.ts file

If I take the dist folder and copy / host the files on our dev servers, the application will work fine.
If I then take the same dist folder and copy / host the files on our test servers, modify the auth-config.json file to have the appropriate values for redirectUri, postLogoutRedirectUri and apiBaseUrl then when I attempt to navigate to https://somewebsitename-T.domainname.com, I can see the app go through the MSAL login sequence and when it redirects it comes back to the wrong URL. It’s coming back to https://somewebsitename-D.domainname.com

It's not reading the auth-config.json file at run time and substituting the values.

This is what I’m trying to accomplish, compile once, deploy across multiple environments with only changing the endpoint names.

**Comment by pkanher617** [comment]
@dmccolloughOneGas I think what Thomas is alluding to here is how to do this in a non-json scenario. That is, rather than using a json file for your authConfig, you can use a script that can programmatically read environment variables.

However if your scenario requires the json file, you can either replace these values by traversing the JSON object and replacing the values in your build scripts, or use a templating engine that can replace these values for you. For example, [mustache](https://www.npmjs.com/package/mustache). But it would have to be something done at build time, as I don't think JSON values can be runtime variables.
