### ISSUE TITLE
What is correct platform for using the PublicClientApplication, Web or SPA?

### ISSUE THREAD

**Issue by kwoxer** [AzureAD/microsoft-authentication-library-for-js#3127]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [x] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework
- [ ] Angular
- [ ] React
- [x] Other

## Expected behavior

Login works.

## Identity Provider

- [x] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [ ] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [x] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [x] Customer request

## Description

I was using the **[silent-flow][1]** example and everything worked out fine. But then I saw that I have created 2 (Web & SPA) platforms. So I decided to do a **cleanup**. As I thought I just use the `Web` platform, I just deleted the `SPA`. But then the trouble came as I'm now getting always an error when trying to login.

So this is the current state when I have only one platform enabled.

When using `SPA`:

[![setup 1][2]][2]

then I get

[![error 1][3]][3]

> AADSTS9002325: Proof Key for Code Exchange is required for
> cross-origin authorization code redemption.

And when I use `Web`:

[![setup 2][4]][4]

I get:

[![error 2][5]][5]

	

> "xxx: The request body
> must contain the following parameter: 'client_assertion' or
> 'client_secret'.\r\nTrace ID:
> xxx\r\nCorrelation ID:
> xxx\r\nTimestamp: 2021-03-03
> 09:59:07Z - Correlation ID: xxx -
> Trace ID: xxx"

Maybe I do not understand something, but I only need one platform, correct? 

I also tested with both enabled but getting the same issue you see above. Is my Azure Portal buggy maybe? Because I did not change anything except removing and adding platforms.

And for sure the setting `Allow public client flows` is set to `Yes`.

  [1]: https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/standalone-samples/silent-flow
  [2]: https://i.stack.imgur.com/YrKhe.png
  [3]: https://i.stack.imgur.com/QjvNA.png
  [4]: https://i.stack.imgur.com/WJ5ri.png
  [5]: https://i.stack.imgur.com/1qwoD.png

**Comment by pkanher617** [comment]
@kwoxer I may have misunderstood your scenarios in the previous issue, apologies for that. You can find a breakdown of Public vs Confidential Client Apps [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-client-applications). Public Clients can only be Desktop Apps, Browserless Apps and Mobile apps, this also includes SPAs, although they are specified as a different platform in the app registration for the portal. Confidential Clients include Web Apps such as the one you are using.

You can replace the PublicClientApplication used in the silent-flow sample and instead use the ConfidentialClientApplciation class. This will require you to create a client_secret in the app registration for the portal. I agree that this needs to be better documented, we will add this to our backlog.

**Comment by kwoxer** [comment]
I understand the difference between PCA and CCA.

But that silent-flow worked like a charm, before I did the cleanup in Azure with the platforms. And the code was using the PCA also before. So I dunno what happened internally actually in Azure? Maybe a bug.

Maybe can you tell me what my setting should look like? So have a look on the silent-flow example. For me that looks like I should only use Web as platform. Is that wrong? And if true why it fails for me? Thank you.

**Comment by pkanher617** [comment]
As I said, in the `silent-flow` sample you should use the ConfidentialClientApplication constructor instead of PublicClientApplication. This is because your app is a web app, not a SPA. I'm also not sure why your app was working before, it may have been a bug. However your app is a Web app, so yes, you should only use the Web platform. Which means you need to support the Confidential Client flow. Set up a client_secret in your app registration, and then use that client secret in the configuration you pass to the ConfidentialClientApplication constructor.

**Comment by kwoxer** [comment]
Ok, I switched to `ConfidentialClientApplication `and added the `clientSecret`. And remove `SPA `platform and added a fresh `Web `platform.

But when I try to login. I still get the error message: 

> AADSTS9002325: Proof Key for Code Exchange is required for cross-origin authorization code redemption.

**Comment by kwoxer** [comment]
Ok strange, just tested **another account** and there it works:

![grafik](https://user-images.githubusercontent.com/1167229/110080298-89746e80-7d8a-11eb-9636-f332e5be4d36.png)

and just tested on the just failed account and there it now also works. Very strange, maybe cachings.

Ok so please update that silent-flow as it does not work with the `PublicClientApplication`. I think this helps a lot when the example is correct and not even more confusing. :)
