### ISSUE TITLE
'prompt' parameter is not customizable for Authentication Experience

### ISSUE THREAD

**Issue by itanex** [AzureAD/microsoft-authentication-library-for-js#313]
I need to allow the authentication experience to utilize 'login_hint' parameter. However this is not possible when the `loginPopup(...)` method and several other methods force the use of `prompt=select_account`.

The authentication URI that i expect to be built resembles the following:

```
    https://login.microsoftonline.com/{tenant}/oauth2/v2.0/authorize?
    client_id=6731de76-14a6-49ae-97bc-6eba6914391e
    &response_type=id_token+token
    &redirect_uri=http%3A%2F%2Flocalhost%2Fmyapp%2F
    &scope=openid%20https%3A%2F%2Fgraph.microsoft.com%2Fmail.read
    &response_mode=fragment
    &state=12345
    &nonce=678910
    &login_hint=user@domain.ext
```

Similar to #284 
[Secure SPA - OAUTH 2.0 Implicit Grant](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols-implicit)

**Comment by spottedmahn** [comment]
Seems like the same issue as [Allow Controlling the prompt parameter](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/208), no?

**Comment by nehaagrawal** [comment]
@itanex login_hint allows user to pre-fill the username and email address field of the sign-in page for the user but user still need to enter the password. prompt=none wouldn't work here. How will you enter the password?

**Comment by itanex** [comment]
@spottedmahn Similar. I read through #208 and the use case is different, but the code in question is the same. I am working on a code example for this and will post it later.

**Comment by itanex** [comment]
@nehaagrawal First off. I am not using `prompt=none`. The expected behavior is that the user, when providing the `tenant url` so that an authority url can be built, the user should be presented with the assigned account (`login=admin@my.tenant.com`) within the tenant.
