### ISSUE TITLE
@azure/msal-angular changed to sessionstorage still stores in both session and local

### ISSUE THREAD

**Issue by johnfabian** [AzureAD/microsoft-authentication-library-for-js#3139]
## Library
- [ x] `@azure/msal-angular@2.x.x`

## Framework
- [ x] Angular

## Description
I changed the configuration to use session storage and the tokens are now saved in local and session storage both. When I open new tab to login it doesn't force a new login

## Reproduction steps
use the MSAL Angular v2 B2C Sample
change to sessionstorage in cache: {
      cacheLocation: BrowserCacheLocation.SessionStorage      
    },
login
session and local have the same information

**Comment by tnorling** [comment]
@johnfabian Just to confirm, did you clear localStorage after switching to sessionStorage?
