### ISSUE TITLE
BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API

### ISSUE THREAD

**Issue by VladBozhinovski** [AzureAD/microsoft-authentication-library-for-js#3141]
## Library

    "@azure/msal-angular": "^2.0.0-alpha.6",
    "@azure/msal-browser": "^2.11.2",

## Framework

- [x] Angular

## Description

User visits the application site, on initialization of the app (ngOnInit) msalService.loginRedirect() is activated.
User successfully logs in but the error happens.
This happens only when I use loginRedirect method in ngOnInit.

## Error Message

BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API

## MSAL Configuration

```js
export function MSALInstanceFactory(): IPublicClientApplication {
  return new PublicClientApplication({
    auth: {
      clientId: "",
      redirectUri: "http://localhost:4200",
      authority:
        "https://login.microsoftonline.com/myteenantvalue/",
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE,
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Info,
        piiLoggingEnabled: false,
      },
    },
  });
}

export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
  const protectedResourceMap = new Map<string, Array<string>>();
  protectedResourceMap.set("https://graph.microsoft.com/v1.0/me", [
    "user.read",
  ]);

  return {
    interactionType: InteractionType.Redirect,
    protectedResourceMap,
  };
}

export function MSALGuardConfigFactory(): MsalGuardConfiguration {
  return {
    interactionType: InteractionType.Redirect,
    authRequest: {
      scopes: ["user.read"],
    },
    loginFailedRoute: "/failed",
  };
}
```

## Reproduction steps

```js
The msal service is registered in the app.module.
The msal service is injected into the app.component.ts constructor
The msal service call the loginRedirect methos => this.msalService.loginRedirect();
User is redirected and logged but error occures
```

## Expected behavior
The overall outcome is fine, except the error.

## Identity Provider

- [x] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [x] Chrome

## Regression

- [ ] Did this behavior work before?
Version:

## Security
- No

## Source
- Customer request

![Screenshot_5](https://user-images.githubusercontent.com/8876745/109937126-ec083480-7cce-11eb-84ed-d9f66d5a7c2d.png)

**Comment by pkanher617** [comment]
@VladBozhinovski Could you upgrade to the latest version of `msal-angular` and `msal-browser` (if you are just using `msal-angular`, you can upgrade to the latest beta version)?

Also make sure you read through [these docs](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/redirects.md) to make sure the redirect is being handled correctly. You can also look at the [error doc for `msal-angular` v2](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/errors.md) which calls out some mitigation steps for this error.

**Comment by VladBozhinovski** [comment]
@pkanher617 when I'm using the InteractionStatus I'm getting empty string. Please see the picture belowe
![image](https://user-images.githubusercontent.com/8876745/110104839-f1857d80-7da7-11eb-8e62-2706ee9ec880.png)

**Comment by VladBozhinovski** [comment]
@pkanher617 I have updated the packages and when I use this code below I'm getting into indefinite loop of authentication.

```
ngOnInit(): void {
    this.isIframe = window !== window.parent && !window.opener; // Remove this line to use Angular Universal

    this.msalBroadcastService.inProgress$
      .pipe(
        filter(
          (status: InteractionStatus) => status === InteractionStatus.None
        ),
        takeUntil(this._destroying$)
      )
      .subscribe(() => {
          this.authService.loginRedirect();
      });
  }

```

**Comment by jo-arroyo** [comment]
@VladBozhinovski We do not recommend calling `loginRedirect()` in app.component.ts `ngOnInit`. Are you trying to call it there to invoke login before the home page loads? If so, we recommend setting the guard on the home page instead.

**Comment by VladBozhinovski** [comment]
@jo-arroyo MsalGuard for each route worked perfectly .  Thank you very much. I think this can be closed now.
