### ISSUE TITLE
Current Status of MSAL React Library

### ISSUE THREAD

**Issue by dwatty** [AzureAD/microsoft-authentication-library-for-js#3142]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [X] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

I see that the MSAL React library is now tagged as beta/pre-release as of March 3, 2021.  The project roadmap mentions that once the library reaches public preview, that will include production support.  

My question was whether this beta release is considered the public preview meaning this _could_ be adopted in our production environment.  Or is the public preview for the library still to come?

Thanks!

## Source

- [ ] Internal (Microsoft)
- [X] Customer request

**Comment by jasonnutter** [comment]
@dwatty We are preparing to go to public preview very soon, and the beta release was part of that process. When public preview is announced, we will have full production support. We'll have more information next week on expected public preview and GA dates. Appreciate your patience!

**Comment by dwatty** [comment]
Thanks @jasonnutter - I'll keep an eye out for it
