### ISSUE TITLE
prod build error for msal-angular in custom library

### ISSUE THREAD

**Issue by sidyes** [AzureAD/microsoft-authentication-library-for-js#3149]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.12.0`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [x] `@azure/msal-angular@2.0.0-beta.0`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [x] Angular
- [ ] React
- [ ] Other

## Description
I have integrated the msal angular solution into a library of a NX workspace. It is working just fine, when I use my library (that kind of wraps the msal lib) within an application.
But when I try to make a production build of this library, the build fails.

## Error Message

```
Building Angular Package

------------------------------------------------------------------------------
Building entry point 'my-shared-auth-lib'
------------------------------------------------------------------------------
× Compiling TypeScript sources through NGC
ERROR: Cannot determine the module for class MsalRedirectComponent in C:/path/to/project/node_modules/@azure/msal-angular/azure-msal-angular.d.ts! Add MsalRedirectComponent to the NgModule to fix it.

Cannot determine the module for class MsalRedirectComponent in C:/path/to/project/node_modules/@azure/msal-angular/azure-msal-angular.d.ts! Add MsalRedirectComponent to the NgModule to fix it.
```

## MSAL Configuration

```js
@NgModule({
  imports: [MsalModule, StoreModule],
  providers: [AzureAuthService, MsalService, MsalGuard, MsalBroadcastService]
})
export class SharedAzureAuthModule {
  static forRoot(
    azureConfig: AzureConfig
  ): ModuleWithProviders<SharedAzureAuthModule> {
    return {
      ngModule: SharedAzureAuthModule,
      providers: [
        {
          provide: HTTP_INTERCEPTORS,
          useClass: MsalInterceptor,
          multi: true,
        },
        {
          provide: MSAL_INSTANCE,
          useValue: getMsalInstanceConfig(azureConfig.msalInstance), // basically same setup as in the sample app but parametrized
        },
        {
          provide: MSAL_INTERCEPTOR_CONFIG,
          useValue: getMsalInterceptorConfig(azureConfig.msalInterceptor), // basically same setup as in the sample app but parametrized
        },
        {
          provide: MSAL_GUARD_CONFIG,
          useValue: getMsalGuardConfig(azureConfig.msalGuard), // basically same setup as in the sample app but parametrized
        },
      ],
    };
  }

  constructor(@Optional() @SkipSelf() parentModule: SharedAzureAuthModule) {
    if (parentModule) {
      throw new Error(
        'SharedAzureAuthModule is already loaded. Import it in the AppModule only'
      );
    }
  }
}
```

## Reproduction steps

Create a library, that wraps msal angular and handles communication with it through a NGRX store - meaning it provides actions for the consumer apps and auth information within its internal store that can be accessed via selectors.
Try to run a production build of the lib.

## Expected behavior

It should build as expected, especially because the affected `MsalRedirectComponent` is nowhere used within the library itself. 
Only the consuming apps bootstrap it. So I do not really get why this error occurs at all.

## Identity Provider

- [x] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [x] Customer request

**Comment by jo-arroyo** [comment]
@sidyes There may be an issue with the node modules. Can you npm uninstall and reinstall @azure/msal-angular again?

**Comment by roopeshreddy** [comment]
@jo-arroyo I see that the component is not added to the declarations array!

If we add this MsalRedirect Component to the msal.module.ts file declarations array, then it may solves this issue!

**Comment by digitalcraftco** [comment]
Same problem here. I'm trying to use it in a app-shell lib and get the same error. In Ivy, you cannot import a component from a library and declare it in one of your own NgModules. Instead, you should import the module from within the library which declared that component.

**Comment by jo-arroyo** [comment]
Thank you for all the contributions! The PR addressing this issue has been merged and will be part of the next MSAL Angular release. Please open a new issue if you are still encountering this problem.
