### ISSUE TITLE
MSAL logout frame issue

### ISSUE THREAD

**Issue by chinmayembedded** [AzureAD/microsoft-authentication-library-for-js#315]
After i do logout i get this screen saying frameloader null
![2aa1a680-a514-4977-a1dc-82e6c0ad91a2](https://user-images.githubusercontent.com/18334906/40706295-f8b0849c-640a-11e8-9339-65219a36ff7a.png)

**Comment by rohitnarula7176** [comment]
@chinmayembedded Can you attach the fiddler trace for the above use case.

**Comment by chinmayembedded** [comment]
Sorry I cannot share the details with you. 
Following are the methods used in my code - 
1. The constructor called for B2C
clientApplication = new Msal.UserAgentApplication(
        this.tenantConfig.clientID, this.authority, 
        function (errorDesc: any, token: any, error: any, tokenType: any) {            
            localStorage.setItem("accesstoken",token);     
        },
        {
            postLogoutRedirectUri: window.location.origin + '/login' 
        }
);
2. The B2C logout method
logout(): void {
        this.clientApplication.logout();
};

Apart from this I am using MSAL 0.1.5 version. 
The flow of the issue is - 
Logout function called -> **_Frameloader numm issue_** -> login page as per the postLogoutRedirectUri

**Comment by nehaagrawal** [comment]
@chinmayembedded  Can you please confirm if this issue still exists?
