### ISSUE TITLE
Enable multi user access in silent-flow to be able to use server with different accounts parallel

### ISSUE THREAD

**Issue by kwoxer** [AzureAD/microsoft-authentication-library-for-js#3151]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [x] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework
- [ ] Angular
- [ ] React
- [x] Other

## Expected behavior

Multi user access possible.

## Identity Provider

- [x] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [ ] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [x] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [x] Customer request

## Description

The **[silent-flow](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/standalone-samples/silent-flow)** example works perfectly. I can login and logout.

But when I try to login in 2 different browsers with 2 different accounts. Then the old browser will be logged in with the last logged-in account when page was reloaded.

![grafik](https://user-images.githubusercontent.com/1167229/110115244-1aad0a80-7db6-11eb-9ce8-50a74e5df6cd.png)

I know that it always takes the last `homeAccountId` from cache as the code says:

`const account = await msalTokenCache.getAccountByHomeId(app.locals.homeAccountId);`

My question is now, how to enable multi users? How to rewrite the `app.locals`?  Is there any example?

Otherwise is need to create some custom code for that?

**Comment by pkanher617** [comment]
@kwoxer If you need to get all of the accounts currently tracked by msal-node, you can use the `getAllAccounts` API exposed on the token cache. However this does mean that your app has to have some way to choose or identify which account you are using. You could do this by presenting an account selection screen to the user.

`app.locals.homeAccountId` is set when the response is retrieved from `acquireTokenByCode` so that is why it is always taking the last homeAccountId.

**Comment by kwoxer** [comment]
What you mean with account selection?

I don't usually want 1 user to use different accounts. Instead I want multiple users to use their accounts without an impact from others.

So you mean `const accounts = await msalTokenCache.getAllAccounts();`?

Yeah that gives me back the users that have been logged in at all time. But now how to get the `homeAccountId`. My idea is to set save it to a cookie or something like that. But that's very insecure. How to do it better?

**Comment by kwoxer** [comment]
As noone can help me, I now just saved the homeAccountId to the cookies of the browser. Then send it as cookie in the request. Now it works. Also on different browsers.

So this makes it possible to be used by different users at the same time.

But yeah I am still interested in a version where I dont have to got the cookie workaround. If there is some.

Thanks in advance.

**Comment by kwoxer** [comment]
Well it works for me since weeks now, but its still not a super secure solution with the cookie workaround. But I cannot see someone with a more advanced solution. Is that right?

**Comment by jasonnutter** [comment]
@kwoxer Using a cookie seems like a fine approach. Can you clarify whe you don't consider it secure? You can mark the cookie as secure and http only. Furthermore, `homeAccountId` is just an identifier, and it cannot be used alone to authenticate.

If you still have concerns with storing it in an http only secure cookie, you can encrypt it before you put it in the cookie, and decrypt when reading (although that is not really needed).

**Comment by kwoxer** [comment]
Thanks for telling me my way is ok. But I must assume that I don't see a difference between a secure and a usual cookie. Sure the delivering is secure OK. 

Anyway. Here is why I think my cookie with the `homeAccountId` is not secure. So let's say I have **2 browsers**. The first browser has that cookie set:
![image](https://user-images.githubusercontent.com/1167229/114661617-8d839c80-9cf7-11eb-87b7-3bbfcbcbe1ee.png)

and the second browser does not. But let's say somehow the second browser finds out my `homeAccountId` and sets the cookie manually. Now that browser is logged in with my account.

And as this ID is never changing and not generated it is super easy to hijack someone.

So what is the best approach now to deny this?

You said to encrypt and decrypt. Can you go into detail here? Or do you mean I create a salted table on my node.js server? And that salt is just for encryption and decryption?

Thanks so much for helping and a really appreciate you create a tutorial on this.

**Comment by jasonnutter** [comment]
> and the second browser does not. But let's say somehow the second browser finds out my homeAccountId and sets the cookie manually. Now that browser is logged in with my account.

This is not correct. `homeAccountId` is just an identifier, knowing it does not allow another person to be logged in with your account.

> You said to encrypt and decrypt. Can you go into detail here? Or do you mean I create a salted table on my node.js server? And that salt is just for encryption and decryption?

I was just referring to encrypting the string you put into the cookie value (so it can't be read by others).

**Comment by kwoxer** [comment]
Well @jasonnutter I can create a short screenshot to demonstrate it if you want?

This is the line I use for the authentication, maybe I am using it wrong?

`const account = await msalTokenCache.getAccountByHomeId(req.cookies.homeAccountId);`
