### ISSUE TITLE
AADB2C90079: Clients must send a client_secret when redeeming a confidential grant

### ISSUE THREAD

**Issue by tamilvjm** [AzureAD/microsoft-authentication-library-for-js#3153]
## Library

- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-angular@2.x.x`

## Framework

- [ ] Angular
- [ ] React
- [ ] Other

## MSAL Configuration

```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps

```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Identity Provider

- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy

## Browsers/Environment

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by pkanher617** [comment]
@tamilvjm Could you please fill out the issue template? Thanks.

**Comment by tnorling** [comment]
Closing as no information has been provided to understand what this is about. Please open a new issue if you still need help.
