### ISSUE TITLE
msal-node doesn't have getAccount 

### ISSUE THREAD

**Issue by danieljaguiar** [AzureAD/microsoft-authentication-library-for-js#3154]
## Library

- [x] `@azure/msal-node@1.x.x`

## Description
I am not sure if this is a bug or not, I am trying to implement Microsoft Graph Client (https://www.npmjs.com/package/@microsoft/microsoft-graph-client) with msal-node, but it seems all clients inside msal-node doesn't implement getAccount.

getAccount is used by @microsoft/microsoft-graph-client and if you pass a msal client acquired from msal-node, it will fail with

```
TypeError: this.msalApplication.getAccount is not a function
    at ImplicitMSALAuthenticationProvider.<anonymous> (C:\Users\xxx\Documents\codeMSFT\xxx\server\node_modules\@microsoft\microsoft-graph-client\src\ImplicitMSALAuthenticationProvider.ts:71:28)
    at step (C:\Users\xxx\Documents\codeMSFT\xxx\server\node_modules\tslib\tslib.js:141:27)
    at Object.next (C:\Users\xxx\Documents\codeMSFT\xxx\server\node_modules\tslib\tslib.js:122:57)
    at C:\Users\xxx\Documents\codeMSFT\xxx\server\node_modules\tslib\tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\xxx\Documents\codeMSFT\xxx\server\node_modules\tslib\tslib.js:111:16)
    at ImplicitMSALAuthenticationProvider.getAccessToken (C:\Users\xxx\Documents\codeMSFT\xxx\server\node_modules\@microsoft\microsoft-graph-client\lib\src\ImplicitMSALAuthenticationProvider.js:40:24)     
    at AuthenticationHandler.<anonymous> (C:\Users\xxx\Documents\codeMSFT\xxx\server\node_modules\@microsoft\microsoft-graph-client\src\middleware\AuthenticationHandler.ts:78:55)
    at step (C:\Users\xxx\Documents\codeMSFT\xxx\server\node_modules\tslib\tslib.js:141:27)
    at Object.next (C:\Users\xxx\Documents\codeMSFT\xxx\server\node_modules\tslib\tslib.js:122:57)
```

Microsoft Graph requires the MSAL Application to have getAccount implemented, which doesn't seem that the clients available in MSAL-NODE implement it.

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by samuelkubai** [comment]
Hi @danieljaguiar,

Apologies for the late reply to this. 

You are right the msal-node library doesn't expose a function named `getAccount` but in turn exposes the function `getAccountByHomeId` and `getAllAccounts` among others, like shown [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/310ab2c2c11be3765f22daee5f4fafa34369eb0d/samples/msal-node-samples/standalone-samples/silent-flow/index.js#L138) for a list of all methods you can use to retrieve accounts you can find them all [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/310ab2c2c11be3765f22daee5f4fafa34369eb0d/lib/msal-node/src/cache/ITokenCache.ts#L12)

**Comment by danieljaguiar** [comment]
Thanks @samuelkubai !

Any plans to implement `getAccount` to fully `@microsoft/microsoft-graph-client` ?

**Comment by sameerag** [comment]
Guess we can expose a general purpose API with a filter against all account properties. Can we mull over the implications and reach out?

**Comment by danieljaguiar** [comment]
I am trying to implement [Microsoft Graph Client](https://www.npmjs.com/package/@microsoft/microsoft-graph-client).

If you check Microsoft Graph Client, they require the MSAL to have `getAccount` exposed. Check their code [here](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/a95a762b9b7f66fb843aa1e134014f4214bc093a/src/ImplicitMSALAuthenticationProvider.ts#L71):

```JS
	public async getAccessToken(authenticationProviderOptions?: AuthenticationProviderOptions): Promise<string> {
		//(...)
		if (this.msalApplication.getAccount()) { // <==== getAccount is called here
			const tokenRequest: AuthenticationParameters = {
				scopes,
			};
			try {
				const authResponse: AuthResponse = await this.msalApplication.acquireTokenSilent(tokenRequest);
				return authResponse.accessToken;
			} catch (error) {
```

Please note I don't own Microsoft Graph Client. I was just trying to use Microsoft Graph in my project that already uses MSAL-NODE, but I see the functions Microsoft Graph Client expected are not exposed by Microsoft MSAL-Node making it incompatible.

**Comment by tnorling** [comment]
@danieljaguiar Looks like the Microsoft Graph Client uses the `msal-core` library as described in their readme [here](https://github.com/microsoftgraph/msgraph-sdk-javascript#2-authenticate-for-the-microsoft-graph-service). `msal-core` is different library and is intended for SPA applications. I would recommend opening an issue on Microsoft Graph Client to find out if they have a different version for node applications or what their recommendation is.

**Comment by tnorling** [comment]
Closing as this issue is regarding a library we don't own. Please open a new issue if you have further questions. Thanks!
