### ISSUE TITLE
postLogoutRedirectUri not working

### ISSUE THREAD

**Issue by markholst** [AzureAD/microsoft-authentication-library-for-js#3157]
## Library
- [X] `msal-browser@2.12.0`

## Framework
- [X] React 17

## Description
Are there any special requirements for getting the 'postLogoutRedirectUri' to work?
It doesn't matter what value I put in there, it just leaves me on the same page I was on when the user hit the sign-out button.  Which isn't ideal, I'd like the app to redirect back to the root page.

## Error Message
N/A

## MSAL Configuration
const configuration: Msal.Configuration = {
    auth: {
        clientId: clientId,
        knownAuthorities: [knownAuthority],
        redirectUri: redirectUri,
        postLogoutRedirectUri: "https://anything.com",
    },
    cache: {
        cacheLocation: "localStorage",
        storeAuthStateInCookie: false,
    },
};

```js
```

## Reproduction steps
Sign in to app
Navigate to some random page
Invoke 'sign-out', it leaves me on the same URI after sign-out.

```js
```

## Expected behavior
Honour whatever has been configured in the postLogoutRedirectUri

## Identity Provider
- [X] Azure B2C Basic Policy

## Browsers/Environment
- [X] Chrome 89

## Regression
- [ ] Did this behavior work before?
Version:
Unknown

## Security
- [ ] Is this issue security related?
No

## Source
- [X] Customer request

**Comment by tnorling** [comment]
@markholst When you say it "leaves me on the same Uri" can you clarify what you mean by this? When you invoke `logout` you should be redirected to the logout page of the server and then the server will redirect back to whatever was passed as the `postLogoutRedirectUri`. Are you saying that you are not being redirected to the server logout page or that the server is not redirecting you back to your `postLogoutRedirectUri`? 

Also check to make sure the `postLogoutRedirectUri` is registered as a `redirectUri` on your app registration.

**Comment by markholst** [comment]
Hi @tnorling,

I've followed up on your thought, the postLogoutRedirectUri is actually being set to the same value as the redirectUri.  This has been set in Azure B2C under "Single-page Application - Redirect URIs".

This is interesting.

In our Test environment, I am seeing this -
![image](https://user-images.githubusercontent.com/56993727/111269236-4c04c080-8669-11eb-8a21-974a7dd5beda.png)

In our Development environment, I am now seeing this as below.  It was definitely mis-behaving before, and it is definitely behaving properly now.
![image](https://user-images.githubusercontent.com/56993727/111269525-b87fbf80-8669-11eb-895a-e71d84a3946a.png)

Something appears to be cancelling the request?

When I previously raised this issue, it was out of the Development environment.  Both environments are running 2.12.0.

**Comment by tnorling** [comment]
@markholst Requests can be cancelled if a 2nd redirect is initiated while the 1st has not left the page yet or if the component that initiated the redirect is unmounted before the navigation happens. Try to do some debugging to see if either of these scenarios might be happening when it breaks.

> The other clue is that, despite hitting sign-out, I can sign-in again without entering any credentials. Which suggest, yes, it's not signing out properly.

This is a nuance of how sign-out in B2C works. See [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md#i-logged-out-of-my-application-why-am-i-not-asked-for-credentials-when-i-try-to-log-back-in) and [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/working-with-b2c.md#b2c-and-sign-out-experience) for more on this.

**Comment by markholst** [comment]
Hi @tnorling 

Okay, I have finally managed to clear some time.  I have added a lot of logging, and updated to msal-browser@2.12.1.

I can no longer reproduce the problem in Chrome, Edge or Firefox.

I'm closing this issue, thanks for your assistance with this.
