### ISSUE TITLE
HTTP interceptor for localhost api

### ISSUE THREAD

**Issue by VladBozhinovski** [AzureAD/microsoft-authentication-library-for-js#3158]
## Source

- [x] Customer request

## Library

- [x] `@azure/msal-browser@2.12.0`
- [x] `@azure/msal-angular@2.0.0-beta.0`

## Framework

- [x] Angular

## Description

I'm trying to call an localhost API and to attach bearer token on the header. For now I have added the localhost api route  to the protectedResourceMap but there is no bearer token inside the header. Tried to add jsonplaceholder to make an http post call to it and it works. The only issue is when I try to make http call to localhost api. 
```
protectedResourceMap.set('http://localhost:5000/add/',  ['user.read']);
```
![Screenshot_4](https://user-images.githubusercontent.com/8876745/110346597-007e6100-8030-11eb-80ca-a2345e90b79a.png)

## Error Message
No error, just no bearer token in the header section

## MSAL Configuration

```js
I'm using AD for authentication.
```

## Reproduction steps

```js
The URL is registered in the MsalInterceptorConfiguration:
```
protectedResourceMap.set('http://localhost:5000/add/', [
    ['api://consent-id']
]);
```
localhost:5000 is registered in Redirect URIs of Azure portal

I'm using MsalInterceptor which is registered in the app.module.ts provider array.

```

## Expected behavior
To have bearer token in the header section

## Identity Provider

- [x] Azure AD

## Browsers/Environment

- [x] Chrome

## Regression

- [x] Did this behavior work before?
Version: NaN

## Security

- [x] Is this issue security related?

## Source

- [x] Customer request

**Comment by jo-arroyo** [comment]
@VladBozhinovski It looks like you might be adding an extra array when setting your protected resource map. Please see our [configuration doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/configuration.md#factory-providers) or a [sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/524c2261218ad94bf020c0194c15ff0d57d5ea22/samples/msal-angular-v2-samples/angular11-sample-app/src/app/app.module.ts#L47) for an example of how to set it.

**Comment by nicholashendrickx-tomtom** [comment]
I have the same issue. I'm doing [what the msal-angular docs](https://azuread.github.io/microsoft-authentication-library-for-js/ref/msal-angular/) say, but no luck:
```js
protectedResourceMap: [
  ['https://graph.microsoft.com/v1.0/me', ['user.read']],         // <-- this has the auth headers
  ['https://api.myapplication.com/users/*', ['customscope.read']] // <-- this does *not* have the auth headers
]
```

**Comment by VladBozhinovski** [comment]
@jo-arroyo I checked many time and it seems like everything on the code side is fine. Please correct me if I'm wrong.

Please see the picture:
![image](https://user-images.githubusercontent.com/8876745/110440090-91008400-80b8-11eb-96cf-2051afcfb7be.png)

When I console.log the protectedResourceMap I'm getting: 
![image](https://user-images.githubusercontent.com/8876745/110440213-b5f4f700-80b8-11eb-8366-b6cc297393b6.png)
Pretty much as @nicholashendrickx-tomtom said.

**Comment by VladBozhinovski** [comment]
@jo-arroyo Any suggestion?

**Comment by jo-arroyo** [comment]
@VladBozhinovski Can you try using `/add/` or `add/` in your protectedResourceMap? Sometimes the relative url will work. We are looking into ways to more gracefully handle that scenario.

**Comment by VladBozhinovski** [comment]
@jo-arroyo This worked like a charm. Will give a try when app is hosted and let you know if everything works so we can close this issue. Thank you @jo-arroyo

**Comment by jo-arroyo** [comment]
@nicholashendrickx-tomtom It looks like you may be referencing the `@azure/msal-angular@1` docs. Please see our updated [initialization](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/initialization.md#get-tokens-for-web-api-calls) and [configuration](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/configuration.md#factory-providers) docs for the new shape of the `protectedResourceMap`, as well as the [upgrade guide](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/1.x-2.x-upgrade-guide.md#protected-resources) for more information about protected resources in MSAL Angular v2.

**Comment by nicholashendrickx-tomtom** [comment]
@VladBozhinovski can you please share how you got it to work?

I have a proxy on my dev server from `localhost:4200/api` to `localhost:8080/api` but I can't get the `protectedResourceMap` to work. I want to add the `['customscope.read']` scope to the my api requests, e.g. `protectedResourceMap.set("http://localhost:8080/api/*", ['customscope.read']);`

The following keys in the map do _not_ add a bearer token to my requests:
```
http://localhost:8080/api/*
http://localhost:4200/api/*
```

The following keys fail with `BrowserAuthError: interaction_in_progress` and redirect to an "error" page:
```
 api/*
/api/*
 api
 api/
/api
/api/
```

**Comment by nicholashendrickx-tomtom** [comment]
For the record, when I replace `customscope.read` with e.g. `user.read` then it does add the authentication header to my requests. But I need `customscope.read` and when I add that there are no headers added anymore.

**Comment by VladBozhinovski** [comment]
@nicholashendrickx-tomtom what I have used is 
`protectedResourceMap.set("/api/", ['customscope.read']);`

This one worked for me since it can be for example localhost/api or somewebsite/api it doesn't matter. I hope this will work for you

**Comment by nicholashendrickx-tomtom** [comment]
Thanks @VladBozhinovski, it seems to do _something_, I guess I need to figure out why `customscope.read` fails. It says it doesn't know this scope. I'm pretty sure it worked with v1 os msal-angular, but we were using implicit grant back then.

**Comment by VladBozhinovski** [comment]
@nicholashendrickx-tomtom that's good to hear that it helped buddy :)
