### ISSUE TITLE
SPA - unable to complete authentication from another route

### ISSUE THREAD

**Issue by jbockle** [AzureAD/microsoft-authentication-library-for-js#316]
I have a SPA with Aurelia, and configured it with MSAL.  

When I load app from the base route http://localhost:8080 it authenticates user, then redirects to homepage and am able to get the logged in User and display it on navbar. 

When I load from another route, like http://localhost:8080/#/counter, it authenticates user, redirecters to counter page, but getUser() returns null.

Is there something I'm missing that would prevent authentication from completing on a different route?

Sample Repository:
https://github.com/jbockle/aurelia-azure-active-directory

**Comment by jbockle** [comment]
if `loginInProgress` I force a page reload and all is fine, not sure why that step is needed

**Comment by dougmolineux** [comment]
I couldn't get the hashtag to work in my Angular 5 app either. I had to take out the `useHash: true` inside my app-routing.module.ts file. RouterModule.forRoot should define useHash as false by default.

**Comment by nehaagrawal** [comment]
@dougmolineux  There is an issue with angular library itself for hashbang urls. https://github.com/angular/angular/issues/16710
We are currently waiting on them to fix it. If it doesn't get fix by angular team, we will provide a workaround.

**Comment by navyasric** [comment]
Closing this issue as the original issue seems to be resolved.

**Comment by tuanna2704** [comment]
I still have this problem when using useHash: true. Seemingly this issue cannot fix in angular 6 and more :(
