### ISSUE TITLE
Multiple OpenID Connect Requests from Concurrent Access Token Requests

### ISSUE THREAD

**Issue by spottedmahn** [AzureAD/microsoft-authentication-library-for-js#317]
We have an [Angular interceptor](https://medium.com/@ryanchenkie_40935/angular-authentication-using-the-http-client-and-http-interceptors-2f9d1540eb8) to obtain our access tokens.  We might fire numerous http requests that need an access token.

I've noticed the library handles this in that it only issues one access token request and tells the others to wait which is great.  But it still fires multiple requests for the OpenID configuration.

Is that expected?  Seems wasteful...

![image](https://user-images.githubusercontent.com/14079228/40932367-1f961bb8-67fc-11e8-8e44-2f96deb7e88b.png)

**Comment by sameerag** [comment]
@spottedmahn We are tracking this issue after our 1.0.0 release.

**Comment by jasonnutter** [comment]
@spottedmahn Is this still an issue?

**Comment by spottedmahn** [comment]
no clue, sorry, not doing B2C stuff these days

**Comment by RobARichardson** [comment]
I haven't seen this issue since the release of [v1.1.2](https://github.com/AzureAD/microsoft-authentication-library-for-js/releases/tag/v1.1.2).  The fix might be related to #875 as was [mentioned](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/762#issuecomment-521455905) by @sameerag over on issue #762

**Comment by pkanher617** [comment]
@spottedmahn @RobARichardson We reviewed this as a team and found that these request responses are being served from the browser cache, not making network calls. Can you please verify the Size column and see if this is the case? It should say (disk cache) in the Size field for the relevant requests.

**Comment by sameerag** [comment]
Closing this as we did not get a response. As mentioned above the responses are being served from the browser cache and should not have a performance impact.
