### ISSUE TITLE
Question:   The reply URL specified in the request does not match the reply URLs configured for the application:

### ISSUE THREAD

**Issue by levalencia** [AzureAD/microsoft-authentication-library-for-js#3173]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.12.0`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

My app.tsx is like this:

```
import React from 'react';
import { AuthenticatedTemplate, UnauthenticatedTemplate, useMsal, useMsalAuthentication } from "@azure/msal-react";
import { MsalProvider } from "@azure/msal-react";
import { Configuration,  PublicClientApplication } from "@azure/msal-browser";
import { InteractionType } from '@azure/msal-browser';

export function App() {
    const {login, result, error} = useMsalAuthentication(InteractionType.Redirect);

    return (
        <React.Fragment>
            <p>Anyone can see this paragraph.</p>
            <AuthenticatedTemplate>
                <p>At least one account is signed in!</p>
            </AuthenticatedTemplate>
            <UnauthenticatedTemplate>
                <p>No users are signed in!</p>
            </UnauthenticatedTemplate>
        </React.Fragment>
    );
}

export default App;
```

My index.tsx is like this:

```

import React from "react";
import ReactDOM from "react-dom";

import './index.css';
import { MsalProvider } from "@azure/msal-react";
import { Configuration,  PublicClientApplication } from "@azure/msal-browser";

//import App from "./app.jsx";
import App from './App';

// MSAL configuration
const configuration: Configuration = {
    auth: {
        clientId: "xxx-bf88-4aa0-ad1a-6fd14b8462db"
    }
};

const pca = new PublicClientApplication(configuration);

// Component
const AppProvider = () => (
    <MsalProvider instance={pca}>
        <App />
    </MsalProvider>
);

ReactDOM.render(<AppProvider />, document.getElementById("root"));
```

I created the app registration and set the reply urls like this

```
"replyUrlsWithType": [
		{
			"url": "https://localhost:3000",
			"type": "Spa"
		}
	],
```

However after authenticating I get the error:
The reply URL specified in the request does not match the reply URLs configured for the application:

## Source

- [ ] Internal (Microsoft)
- [x ] Customer request

**Comment by tnorling** [comment]
@levalencia Are you initiating login from a page that is not `https://localhost:3000`? Msal will default to using the current page as `redirectUri` if one is not provided in the configuration and this error will be thrown if that url is not registered.

You can try explicitly providing the redirectUri in your configuration: 

```javascript
const configuration: Configuration = {
    auth: {
        clientId: "xxx-bf88-4aa0-ad1a-6fd14b8462db",
        redirectUri: "https://localhost:3000"
    }
};
```

**Comment by levalencia** [comment]
I was able to fix and it has nothing to do with MSAL.

The problem is by default the app starts with htttp not https

So I added this in package.json

    "start": "HTTPS=true react-scripts start",

It works perfectly fine,
