### ISSUE TITLE
Outdated react wrapper library version

### ISSUE THREAD

**Issue by TiagoPereira06** [AzureAD/microsoft-authentication-library-for-js#3175]
## Library

- [x] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Documentation location

- [ ] docs.microsoft.com
- [ ] MSAL.js Github Wiki
- [x] README file
- [ ] Other (please fill in)
- [ ] Documentation does not exist

## Description

Please change the react wrapper library, to the newest version. It's currently in `beta`, not [`alpha`](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-browser#framework-wrappers).

![image](https://user-images.githubusercontent.com/38113135/110536315-3c412580-8119-11eb-80c7-2775d2224a7b.png)

**Comment by tnorling** [comment]
@TiagoPereira06 Thanks for pointing out this miss, linked PR will address. For any future issues like this, PRs are also welcome!
