### ISSUE TITLE
Using MSAL in SPA that has multiple React apps

### ISSUE THREAD

**Issue by shamprasadrh** [AzureAD/microsoft-authentication-library-for-js#3178]
## Library

- [X] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

I have a React App that has two apps on same page. The second one is injected as widget like app. Both use MSAL for authentication and for generating API token. When we run the apps individually it works fine. but when both of them are there I get a timeout error and invalid state error as well and this behaviour in inconsistent.  

This is what we get in cache

![image](https://user-images.githubusercontent.com/28918386/110575865-a5f71900-8185-11eb-97af-35c0323b4b46.png)

 and this is MSAL Log ends up in invalid_state error.

![image](https://user-images.githubusercontent.com/28918386/110576024-fa9a9400-8185-11eb-9da5-e20fa85acd8a.png)

Please suggest what is the recommended way to implement MSAL in such scenario?

**Comment by tnorling** [comment]
@shamprasadrh Are both apps using the same clientId or different ones? Also it looks like this is happening when you call `acquireTokenSilent`. Can you confirm? Code snippets showing what you're trying to do when this error occurs would be helpful. If this is happening when calling `acquireTokenSilent` I would suggest setting your redirectUri to a blank page that does not implement msal for the silent request.

I would also highly recommend upgrading to `msal-browser@2.12.0` and potentially `msal-react@1.0.0-beta.0` as these libraries handle multiple app scenarios better than `msal@1.x`

**Comment by shamprasadrh** [comment]
@tnorling Thanks for the response. Both apps are using different app ids. Issue actually happens during `acquireTokenSilent` call for getting the API tokens. 

Below is the code to get the token 

```
async getToken(scopes, hint) {
      try {
        // Get the access token silently
        // If the cache contains a non-expired token, this function
        // will just return the cached token. Otherwise, it will
        // make a request to the Azure OAuth endpoint to get a token
        const silentResult = await this.userAgentApplication.acquireTokenSilent(
          {
            scopes,
            loginHint: hint,
            extraQueryParameters: { domain_hint: 'organizations' },
          }
        );
        return silentResult.accessToken;
      } catch (err) {
        // If a silent request fails, it may be because the user needs
        // to login or grant consent to one or more of the requested scopes
        if (this.isInteractionRequired(err)) {
          const interactiveResult = await this.userAgentApplication.acquireTokenPopup(
            {
              scopes,
              loginHint: hint,
            }
          );

          return interactiveResult.accessToken;
        }
        throw err;
      }
    }
```
We are planning to upgrade to `msal-browser@2.12.0`, is it ok that we do it incrementally APP1 first and then APP2 ? or it will cause any conflict? 

As a workaround we are acquiring the token immediately after login for API scopes which seems to be little consistent but still do see `invalidstate` error in cache.

**Comment by tnorling** [comment]
@shamprasadrh Yes you should be able to incrementally update 1 app at a time, token cache should not conflict between the two. 

I would still suggest first trying to set your redirectUri to a blank page for the silent and popup calls as we've seen this fix other odd issues. I think what may be happening here is that one app is clearing local/session storage for both apps resulting in a mismatch for the other.

**Comment by shamprasadrh** [comment]
@tnorling Thanks for the response. I will give it a try. Do you have any example where blank page is implemented?

**Comment by tnorling** [comment]
@shamprasadrh We do not, however, you can just create a `blank.html` page and set that as the redirectUri. Just make sure this redirectUri is registered in the Portal.

For example: 
```javascript
await acquireTokenSilent({
    scopes: ["openid", "profile"],
    redirectUri: "http://localhost/blank.html"
});
```

> Also this issue is same in msal-browser@2.12.0?

Setting a blank page as redirectUri for silent and popup calls is still a great idea in msal-browser, however, I do not expect your scenario to cause issues in msal-browser.
