### ISSUE TITLE
Angular app stays on white page when AADB2C90091 error is returned from B2C

### ISSUE THREAD

**Issue by BozidarPolic** [AzureAD/microsoft-authentication-library-for-js#3180]
## Library

- [X] `@azure/msal-browser@2.12.0`
- [X] `@azure/msal-angular@2.0.0-beta.0` 

## Framework

- [X] Angular 10

## Description
When clicking on cancel button in Password reset flow b2c returns AADB2C90091 | User cancellation error. 
Angular app stays on white page after redirect.
Using PathLocationStrategy ( useHash: false,) and setting HomeComponent under MsalGuard
` {
    path: '',
    component: HomeComponent,
    pathMatch: 'full',
    canActivate: [
      MsalGuard
    ]
  }.`

When using HashLocationStrategy app shows home page even though its under guard.

## Reproduction steps

I was able to reproduce it using angular 10 sample app (https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular10-sample-app)

PathLocationStrategy:
![PathLocation2](https://user-images.githubusercontent.com/78795513/110624879-10688300-819f-11eb-8e12-23a50796ddd4.gif)

HashLocationStrategy:
![HashLocation2](https://user-images.githubusercontent.com/78795513/110624902-152d3700-819f-11eb-8f85-f2bebf9c84e6.gif)

## Identity Provider

- [X] Azure B2C Basic Policy

## Browsers/Environment
- [X] Chrome

## Source
- [X] Customer request

**Comment by jo-arroyo** [comment]
@BozidarPolic We have made some recent updates to our library which should better support the path routing strategy. Could you please upgrade using `npm install @azure/msal-angular@latest @azure/msal-browser@latest` and let us know if you are still seeing these issues?

**Comment by BozidarPolic** [comment]
@jo-arroyo Can confirm that by using latest msal-angular and msal-browser ( "@azure/msal-angular 2.0.0-beta.2",
    "@azure/msal-browser 2.13.0",) and following https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/FAQ.md#pathlocationstrategy 
login failure is now being raised.
