### ISSUE TITLE
400 (Bad Request) on Login,  AADB2C90079: Clients must

### ISSUE THREAD

**Issue by HristoStoevZ** [AzureAD/microsoft-authentication-library-for-js#3181]
## Library
- [x] `@azure/msal-browser@2.12.0`

## Framework
- [x] React

## Description
We are trying to migrate from msal 1.2.2 to @azure/msal-browser. We have b2c configuration which works fine with msal 1.2.2, but it constantly gets  "AADB2C90079: Clients must send..." after we are returned from the login page. 

What I noticed during the investigation of this issue is that msal 1.2.2 and msal-browser are using totally different parameters for requesting access tokens - **response_type, code_challenge and code_challenge_method.** For example when we call loginRedirect, both redirects us to different URLs:

msal1.2.2: https://wilob2ctest.b2clogin.com/wilob2ctest.onmicrosoft.com/b2c_1_test_smartconnect_signuporsignin/oauth2/v2.0/authorize?__response_type=id_token__&scope=openid%20profile&client_id=client-id-here&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&state=2e0d964a-7030-422a-a55f-d216208a5ae8&nonce=1520dab8-9f07-4cdf-9e8c-60ad19058578&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=1.2.2&prompt=login&client-request-id=07707591-342a-4014-81ef-fd21c0bd008f&response_mode=fragment

msal-browser 12.2.0: 
https://wilob2ctest.b2clogin.com/wilob2ctest.onmicrosoft.com/b2c_1_test_common_signupsignin/oauth2/v2.0/authorize?client_id=client-id-here&scope=openid%20profile%20offline_access&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&client-request-id=d36da4e6-3d55-4fc8-911a-7857b34314e3&response_mode=fragment&__response_type=code__&x-client-SKU=msal.js.browser&x-client-VER=2.12.0&x-client-OS=&x-client-CPU=&client_info=1&code_challenge=uQIi6cADCav5gzTzAdnq95KAHDawLIhHWbcJjt1MRX4&code_challenge_method=S256&prompt=login&nonce=04c12a3b-307e-47cb-a818-a844b65473d8&state=eyJpZCI6ImE3MTM5YTlmLWQ3ODAtNGU4ZS1iODE4LTBiZGEyODAxZDJiMSIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicmVkaXJlY3QifX0%3D
 
## Error Message
invalid_request: undefined - [undefined]: AADB2C90079: Clients must send a client_secret when redeeming a confidential grant.

## MSAL Configuration

```js
{
auth: {
		clientId: CommonSettings.b2cClientId,
		authority: `${AUTHORITY}${SIGN_IN_POLICY}`,
		knownAuthorities: [`${CommonSettings.b2cName}.b2clogin.com`],
		redirectUri: CommonSettings.b2cRedirectUrl,
		postLogoutRedirectUri: CommonSettings.b2cRedirectUrl,
	},
	cache: {
		cacheLocation: 'localStorage',
		storeAuthStateInCookie: false,
	},
}
```

## Reproduction steps
1. Download and change configuration of the sample - https://github.com/HristoStoevZ/msal-browser-react
2. Use npm start to start this ample 
3. Open dev tools with F12
4. Press Login button 

## Expected behavior
Login should pass with no errors, with the existing configuration  

## Identity Provider

- [x] Azure B2C Basic Policy

## Browsers/Environment

- [x] Chrome

## Regression - Yes 

- [x] Did this behavior work before?
Version: masl 1.2.2

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by tnorling** [comment]
@HristoStoevZ Please check your app registration in the Azure Portal and make sure your redirectUri is registered as type "SPA"

**Comment by tnorling** [comment]
Closing as we assume this has been resolved. Please open a new issue if registering the `redirectUri` as type "SPA" does not resolve. Thanks!
