### ISSUE TITLE
First acquireTokenSilent Is Not Extending The Session

### ISSUE THREAD

**Issue by BarishSarac** [AzureAD/microsoft-authentication-library-for-js#3187]
## Library

- [x] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [ ] Angular
- [x] React 16.14.0
- [ ] Other

## Description
All of my API calls follow same pattern of calling acquireTokenSilent to get token then utilizing that to call APIs. Each time I call API, I utilize acquireTokenPossibly then that utilizes aquireToken. acquireTokenPossibly will send in forceRefresh true if user has less than 30 minutes left to their session. Problem is, even when forceRefresh set to true it takes 2 try to get the session length actually extended. First call does not extend the session and then second call does extend it.

## Error Message

Session for the user is not extending at first request no error message.

## MSAL Configuration
```
export const msalApp = new UserAgentApplication({
  auth: {
    domain: ***************,
    clientId: ***************, //B2C Client ID
    authority: ***************,
    validateAuthority: false,
    storeAuthStateInCookie: true,
    redirectUri: ***************,
    postLogoutRedirectUri:***************,
    navigateToLoginRequestUrl: false,
    loadFrameTimeout: 90000,
  },
  cache: {
    cacheLocation: "localStorage",
    storeAuthStateInCookie: false,
  },
  system: {
    navigateFrameWait: 500,
    // logger: new Logger(
    //   (logLevel, message) => {
    //     console.log(message);
    //   },
    //   {
    //     level: LogLevel.Verbose,
    //     piiLoggingEnabled: true,
    //   }
    // ),
  },
});
```

## Reproduction steps
Utilizing acquireTokenSilent with forceRefresh true will extend actual session length at second request. You'd setup a new project and make an acquireTokenSilent call with forceRefresh to observe.

Each API Call
```
acquireToken = async (forceRefresh = false) => {
      let obj = { forceRefresh, scopes: [...apiScopes, "openid"] };
 return await msalApp
        .acquireTokenSilent(obj)
        .then((i) => {
          if (i.accessToken) return i.accessToken;
          else return "";
        })
        .catch((err) => {
          console.log("error:" + err);
          this.logout();
        });}
API Call conditional logic

    acquireTokenPossibly = async (forceRefresh = false) => {
      let timeLeftToExpire = this.getAccExpTime();

      let SessionTimeLeft = Math.round(
        (timeLeftToExpire - Math.round(Date.now() / 1000)) / 60
      );
      if (SessionTimeLeft <= 29) forceRefresh = true;
      return await this.acquireToken(forceRefresh);
    };
```
## Expected behavior
First forceRefresh should extend user's session

## Identity Provider
- [ ] Azure AD
- [x] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression
- [ ] Did this behavior work before? No

## Security
- [ ] Is this issue security related? No

## Source
- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by tnorling** [comment]
@BarishSarac Can you provide MSAL verbose logs and also confirm that the first request is indeed passing forceRefresh?

**Comment by BarishSarac** [comment]
> @BarishSarac Can you provide MSAL verbose logs and also confirm that the first request is indeed passing forceRefresh?

So to quickly do this test, I set the session length in azure to be 31 minutes, and I have a module called IdleCheck, it checks if user's session is expired every second, when the session had 28 minutes left I made it open up a popup with a button on it. The button does the acquireTokenSilent call with forceRefresh set to true. First time I clicked, I got same 28 minute left result. Then I clicked again, sure enough session got extended to 31 again and popup disappeared.

[log.txt](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/6125976/log.txt)

**Comment by tnorling** [comment]
@BarishSarac I'm seeing in the log that it did skip the cache due to `forceRefresh` and went to the network for a new token. Can you email me a network trace so I can examine what the server is sending back?

Also as a side note, can you explain why you are polling every second to force a refresh? The library has a built in mechanism to ensure you always have a valid token and the offset time is configurable.

**Comment by BarishSarac** [comment]
@tnorling Sure, done. So what happens is that IdleCheck checks if user is active or not utilizing this package (https://www.npmjs.com/package/react-idle-timer). It does this check by `let ExpirationTime 
 = msalApp.getAccount().idToken.exp` this then once it gets the time, it compares by `Math.round( (ExpirationTime - Math.round(Date.now() / 1000)) / 60 )`. This way we know each second how long user has remainder left in their session. This serves us 2 purpose.1) if user is idle, we show box for user to click to extend their session and 2) if user is idle let's say 30 minutes we log them out even though their session may have longer to expire. At times, user is active but they're not taking any action which would cause them to extend their session length if it's less than 30 minutes (in a 60 minute session length setup). So we also added a logic that shows the warning to the user if their session is going to end in 5 minutes so they need to click to extend their session. This specific click send the forceRefresh only and it would be for helping user extend their session. It works fine in the second click not the first.
