### ISSUE TITLE
Control navigateToLoginRequestUrl on the Front Side

### ISSUE THREAD

**Issue by spottedmahn** [AzureAD/microsoft-authentication-library-for-js#319]
We're having problems w/ `navigateToLoginRequestUrl` in that it was implemented on `handleAuthenticationResponse` and not before redirecting to B2C.  When I say before, I mean something like setting `self._cacheStorage.setItem(Constants.loginRequest, '')` when `navigateToLoginRequestUrl` is false.

We have cases where we want `navigateToLoginRequestUrl` to be `true` and some to be `false`.

We created different `UserAgentApplication` instances before the redirect to control this but it didn't work.

Thoughts? 💭

Reference: [Previous Issue](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/238#issuecomment-365453972)

**Comment by spottedmahn** [comment]
Hi @nehaagrawal - sure I'll work on something.  I'll update an [Angular sample](https://github.com/Gimly/simpleAngularAzureB2C).

**Comment by nehaagrawal** [comment]
@spottedmahn I went through all the issues reported by you for b2c policies.  I understand that there are 2 major issues:-
1) We return the error code for forget password policy whereas user is expecting the library to handle it.
2) We don't provide the option to configure multiple b2c policies. 
We are going to discuss this internally within our team and I will get an answer for you in this week. Thanks for your patience.

**Comment by spottedmahn** [comment]
>We return the error code for forget password policy whereas user is expecting the library to handle it.

I'm ok with handling it but there's no good way to handle it w/o reaching into the **private** parts of MSAL.js.  Reference:  [#211 Provide Public Access to msal.error and desc](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/211)

>We don't provide the option to configure multiple b2c policies

Basically, yes 👍

And thanks 🙏 for your reply!

**Comment by nehaagrawal** [comment]
@spottedmahn Meanwhile, I saw this issue https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp/issues/9. Did you try the solution provided by mikelunn? He is handling it for password reset policy without accessing the error from _cacheStorage.

**Comment by spottedmahn** [comment]
Hi @nehaagrawal - yes but please [read more details here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/211#issuecomment-359438043).  In short, we need to do this b/c we require you to be signed in to access our app.

**Comment by marilag** [comment]
Hi we also seem to have the same issue. We require the users to be signed in at all times in the app. Creating a new instance of the UserAgentApplication on authcallback to redirect with a password reset policy sometimes works, sometimes not depends on which UserAgentApplication gets redirected first.

**Comment by sameerag** [comment]
@spottedmahn I am curious if the opening up of error interface solves this one too or would you still need multiple instances of msal supported? I can tag this issue accordingly.

**Comment by AndrewCraswell** [comment]
My team is also hitting this issue in a sense. We have a Registration workflow, and a generic Login workflow. Each workflow requires the user to be redirected back to a different page. For registration, when the user authenticates we redirect back to a Terms of Service page where user must agree to terms. In the generic login workflow, the user should be redirected to wherever authentication was initiated from.

These scenarios require different values `navigateToLoginRequestUrl`. At the moment, I think the only way to modify the configuration value is to instantiate another instance of the `UserAgentApplication`, which can cause issues as noted by @nehaagrawal.

**Comment by jasonnutter** [comment]
@spottedmahn Are there any unresolved questions around `navigateToLoginRequestUrl`  specifically? We're currently investigating how to support multiple policies on B2C, which will be tracked separately in #440 .

**Comment by spottedmahn** [comment]
sorry, not sure and I'm not actively working on B2C anymore

**Comment by sameerag** [comment]
@spottedmahn Closing this then for now. We will work on #440 and please feel free to open a new issue if any bug around `navigateToLoginRequestUrl` is found. Thanks for the prompt response.
