### ISSUE TITLE
Testing with @azure/msal-react AuthenticatedTemplate and UnauthenticatedTemplate

### ISSUE THREAD

**Issue by HannahZhuSWE** [AzureAD/microsoft-authentication-library-for-js#3197]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [x] `@azure/msal-react@1.0.0-alpha.6`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

I was wondering if I could get some guidance on how I could use jest to test components that have AuthenticatedTemplate and UnauthenticatedTemplate in them? (Or if I could get a link to an example/documentation for this if I missed it) 

For example I have a log in button component that should display different text (and call a different method when clicked) depending on if the user is authenticated or not however I'm not sure how I would go about testing it. 
```
import React from 'react';
import classes from './LoginButton.module.css';
import { AuthenticatedTemplate, UnauthenticatedTemplate, useMsal } from "@azure/msal-react";
import { loginRequest } from "../../../external/MsGraph/authConfig";

const LoginButton = () =>{
    const { instance } = useMsal();
    return( 
        <div>
            <AuthenticatedTemplate>
                <button 
                    onClick={() => instance.logout()} 
                    className={classes.LoginButton}>
                        Log Out
                </button>
            </AuthenticatedTemplate>
            <UnauthenticatedTemplate>
                <button 
                    onClick={() => instance.loginPopup(loginRequest)}
                    className={classes.LoginButton}>
                        Log In
                </button>
            </UnauthenticatedTemplate>
        </div>
    );    
}

export default LoginButton;
```

I tried to test as if there was only one button (using ```wrapper.find('button').simulate('click')```) however I got an error saying that there were two buttons (which I'm assuming is because it found one from the AuthenticatedTemplate and one from the UnauthenticatedTemplate). If I could get some insight as to how to set up a test so that it takes into account whether the app is authenticated or not that would be really helpful. Thank you!

## Source

- [x] Internal (Microsoft)
- [ ] Customer request

**Comment by tnorling** [comment]
@HannahZhuSWE You can take a look at our react unit tests [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-react/test/components) for examples

**Comment by HannahZhuSWE** [comment]
Thank you!
