### ISSUE TITLE
Improve documentation for redirects in msal-react

### ISSUE THREAD

**Issue by janusch** [AzureAD/microsoft-authentication-library-for-js#3198]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [X ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Documentation location

- [ ] docs.microsoft.com
- [X ] MSAL.js Github Wiki
- [ ] README file
- [ ] Other (please fill in)
- [ ] Documentation does not exist

## Description

Hi,
first of all thank you for maintaining this library and for the rapid development to stabilize the wrapper packages.
I have several times being confused by the documentation.
The latest example is that I would like to switch from the popup to the redirect flow in react-msal.

How does the documentation guide me through the process is confusing.
I started reading here: [redirect-apis](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/initialization.md#redirect-apis)

To find out that this does not apply for react or angular. I followed the link to the react-msal docs [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/FAQ.md#how-do-i-handle-the-redirect-flow-in-a-react-app) 
There it is not really explained on how to use the redirect flow either.

I think future users of the library would benefit from a bit more explicit explanation instead of saying that it just-works™

Could you point me to the relevant docs implementing the redirect flow in msal-browser when it is wrapped in react-msal?

Thank you againfor the creation of this library and maintaining it open source!

**Comment by tnorling** [comment]
@janusch Thanks for the feedback. We agree the redirect flow can be better documented and we have an item on our backlog to do so. If you can state what is confusing for you or is not working I can try to help get you the clarity you need in the meantime. 

Generally speaking, most of the heavy lifting is done under the hood in `msal-react`. We abstract away from you all the messy bits so you can just call `msal.loginRedirect()` and expect when you return from the AAD signin page you will be signed in. No special or additional configuration needed. (this is what we mean by "redirects should just work")

If you need id or access tokens you should call `acquireTokenSilent` after you've signed in. And, as stated in the FAQ you linked, if for any reason you need direct access to the result of the `loginRedirect` you can use the event API which is also linked there.

Additionally, all of our react samples implement the redirect flow as well as the popup flow. [This would be a good place to start](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples)

Please let me know if you have specific questions and I would love to help answer them!

**Comment by janusch** [comment]
Thank you @tnorling for the clarification!

I got it working and it was as you state very straight forward, once I had figured it out. It was literally exchanging popup with redirect like this: `instance.popupRedirect(loginRequest)` becomes `instance.loginRedirect(loginRequest)`

You say that each example in the react samples implements the redirect flow. I cannot find that. Initially i was grepping for redirect in the samples directory and nothing but some vanilla example came up.

What I was missing was an api documentation that shows the methods on the msal instance. Maybe it would help future readers to add a link in the FAQ section to the api docs. I am still not sure where to find them, where could I have seen that there is a `loginRedirect` method on the msal instance?

Lastly, I would like to ask you if the example of logging in on page load from [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-browser-samples/VanillaJSTestApp2.0/app/onPageLoad/auth.js) will work with react-msal. Ideally I would like to login the user without having to click the sign in button in a react app.

Thank you for taking the time to helping me figuring out a convenient msal flow!

**Comment by tnorling** [comment]
@janusch 

> You say that each example in the react samples implements the redirect flow. I cannot find that. Initially i was grepping for redirect in the samples directory and nothing but some vanilla example came up.

You'll find the redirect code in our react router sample [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/8bc85a4eeab142e4fe2103530c21086e604c7564/samples/msal-react-samples/react-router-sample/src/ui-components/SignInButton.jsx#L19) and [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/8bc85a4eeab142e4fe2103530c21086e604c7564/samples/msal-react-samples/react-router-sample/src/pages/ProfileWithMsal.jsx#L65). There's something similar in each of our react samples.

> What I was missing was an api documentation that shows the methods on the msal instance. Maybe it would help future readers to add a link in the FAQ section to the api docs. I am still not sure where to find them, where could I have seen that there is a loginRedirect method on the msal instance?

API Docs for msal instance [here](https://azuread.github.io/microsoft-authentication-library-for-js/ref/interfaces/_azure_msal_browser.ipublicclientapplication.html) which are linked in each of our library's READMEs and additional login docs [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/login-user.md)

> Lastly, I would like to ask you if the example of logging in on page load from here will work with react-msal. Ideally I would like to login the user without having to click the sign in button in a react app.

For this use case I would suggest using the `useMsalAuthentication` hook documented [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/hooks.md#usemsalauthentication-hook) or the `MsalAuthenticationTemplate` documented [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/getting-started.md#msalauthenticationtemplate-component). This is also demonstrated on the /profile page in each of our react samples, please go take a look at those.

I would suggest spending some time going through our `msal-react` [docs](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-react/docs), `msal-browser` [docs](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-browser/docs) and especially the `msal-react` [samples](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples) as these things may become more clear.

**Comment by janusch** [comment]
@tnorling thank you for gathering the documentation resources for me!
It makes all sense now. I will keep them close.

I feel a bit stupid now that I missed it and did not find it on my own, not sure what went wrong on my search.
Looking forward to implement the onPageload flow with the react hook.

Have a great day!

Closing.
