### ISSUE TITLE
Webpack error with msal extensions for node in electron.

### ISSUE THREAD

**Issue by IIrafail** [AzureAD/microsoft-authentication-library-for-js#3200]
## Library

- [ ] `@azure/msal-node-extensions`

## Description
I want to create a persistent login in my electron application. I followed the  guide [here](https://docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app) and my app works but I wave to login each time I restart. 
So I used the msal extensions for node. I created a plugin using [this](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/extensions/docs/msal-node-extensions.md) guide. My plugin:
```
  const cachePath = "./cache.json";
  let filePersistence;
  await FilePersistence.create(cachePath)
  .then(fileP => {filePersistence = fileP})
```
----
*Sidenote*
In case you are wondering I tried using the way the docs said like this:
`const filePersistence = FilePersistence.create(cachePath);`
but later I got an error here:
`cachePlugin: new PersistenceCachePlugin(filePersistence)`
The error:
```
Argument of type 'Promise<FilePersistence>' is not assignable to parameter of type 'IPersistence'.
  Type 'Promise<FilePersistence>' is missing the following properties from type 'IPersistence': save, load, delete, reloadNecessary, and 2 more.ts(2345)
main.ts(34, 47): Did you forget to use 'await'?
```
----
Anyways so in the end I use the persistence layer created above in my config. Here is the config:
```
   const config: MsalElectronConfig = {
    clientId: 'removed',
    mainWindow: mainWindow, //This is the BrowserWindow instance that requires authentication
    scopes: [
      'user.read',
          'user.read',
          'people.read',
          'user.readbasic.all',
          'contacts.read',
          'presence.read.all',
          'presence.read',
          'user.read.all',
          'calendars.read'
    ],cachePlugin: new PersistenceCachePlugin(filePersistence)
    
  };
```
Then when I compile my application with `npm start` I get the following error:

```
ERROR in ./node_modules/keytar/build/Release/keytar.node 1:0
Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
 @ ./node_modules/keytar/lib/keytar.js 1:13-52
 @ ./node_modules/@azure/msal-node-extensions/dist/msal-node-extensions.cjs.development.js 9:13-30
 @ ./node_modules/@azure/msal-node-extensions/dist/index.js 7:2-71
 @ ./src/main.ts 42:29-67
```
Thanks in advance for any help

## Source

- [ ] Customer request

**Comment by IIrafail** [comment]
Just realized it has to do with webpack. Here is my webpack.config.js that I got from the aforementioned microsoft guide.
```
const path = require('path');
module.exports = [
 {
   mode: 'development',
   entry: './src/renderer.ts',
   target: 'electron-renderer',
   module: {
     rules: [
       {
         test: /\.ts$/,
         include: [/src/],
         use: [{ loader: 'ts-loader' }]
       }
     ]
   },
   output: {
     path: __dirname + '/dist',
     filename: 'renderer.js'
   },
   resolve: {
     extensions: ['.ts', '.js'],
     modules: ['node_modules', path.resolve(__dirname + 'src')]
   }
 },
 {
   mode: 'development',
   entry: './src/main.ts',
   target: 'electron-main',
   module: {
     rules: [
       {
         test: /\.ts$/,
         include: [/src/],
         use: [{ loader: 'ts-loader' }]
       }
     ]
   },
   output: {
     path: __dirname + '/dist',
     filename: 'main.js'
   },
   resolve: {
     extensions: ['.ts', '.js'],
     modules: ['node_modules', path.resolve(__dirname + 'src')]
   }
 }
];
```
Does anyone know what I need to add so that it may work?

**Comment by sameerag** [comment]
@IIrafail We have seen some other teams report this as well, and we aren't sure if the issue can be fixed on msal-node-extensions. We do plan to investigate and see if we need some tooling updates on our end. I am also trying to reach out to a customer who faced this issue and let them help with the workarounds they managed to put in place, will update once I have the info.

**Comment by sameerag** [comment]
cc @amrutha95

**Comment by amrutha95** [comment]
For this issue, you might need to add a [node-loader](https://webpack.js.org/loaders/node-loader/)  to your webpack config.
First, run 
```cmd
npm install node-loader --save-dev
```
Then, add another rule in the ```rules``` array in the ```module``` object in your webpack.config.js (similar to what you have already for ts-loader):
```
{
   test: /\.node$/,
   loader: 'node-loader',
},
```
This indicates webpack to use the node-loader when it encounters a .node file extension. Hope this helps!
