### ISSUE TITLE
React Web App - reset password B2C not working with MsalAuthenticationTemplate

### ISSUE THREAD

**Issue by AshTappin** [AzureAD/microsoft-authentication-library-for-js#3201]
## Library

- [@azure/msal-browser@2.12.0] `msal@1.x.x` or `@azure/msal@1.x.x`
- [@azure/msal-react@1.0.0-beta.0] `@azure/msal-react@1.x.x`

## Description

We are currently using this library to implement the Azure B2C reset password flow in our react app. We downloaded the sample [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/b2c-sample), changed the config so it is using our B2C tenant and it worked; we were able to reset our password and we become authenticated.

However, when we start using `MsalAuthenticationTemplate` we run into problems. We are using `MsalAuthenticationTemplate` to force the user to sign in if they are unauthenticated. I can go through the reset password flow until the end, where 
I receive multiple failed bad requests on `https://<tenant>.b2clogin.com/<tenant>.onmicrosoft.com/<signinuserflow>/oauth2/v2.0/token`

Here is the code:

```
const SecureContent = (props) => {
  const { instance } = useMsal();

  useEffect(() => {
    const callbackId = instance.addEventCallback((event) => {
      if (event.eventType === "msal:loginFailure") {
        if (
            event.error &&
            event.error.errorMessage.indexOf(b2cErrorCodes.FORGOTTEN_PASSWORD) >
            -1
        ) {
          instance.loginRedirect({
            authority:
                "https://<tenant>.b2clogin.com/tfp/<tenant>.onmicrosoft.com/<resetPasswordAuthority>",
          }).then(() => {
          });
        }
      }
    });
    return () => {
      if (callbackId) {
        instance.removeEventCallback(callbackId);
      }
    };
  }, []);

  return props.children;
};

const WebSecurityContainer = (props) => {

  const pca = new PublicClientApplication(ourConfiguration);

  return (
      <MsalProvider instance={pca}>
        <SecureContent>
          <MsalAuthenticationTemplate
            interactionType={InteractionType.Redirect}
            authenticationRequest={scopes: [
      "https://<tenant>.onmicrosoft.com/<clientId>/authentication",
    ]}>
            {props.children}
          </MsalAuthenticationTemplate>
        </SecureContent>
      </MsalProvider>
  );
};
```
Any ideas on what I am doing wrong? If you need more info around the configuration then let me know. 

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by tnorling** [comment]
@AshTappin Thanks for raising this. This appears to be a bug in our sample. The issue in this case is that when you return from the password reset policy B2C is giving you an idToken, accessToken and refreshToken from the forgotPassword policy. These tokens cannot be used for any other policy. If you attempt to call `acquireTokenSilent` to acquire tokens from your sign-in policy but provide the refresh token from the passwordReset policy (which is the only one in cache at this point), this error will occur.

In order to resolve you need to explicitly call `logout` after returning from the passwordReset policy and then sign back in with your sign-in policy.

**Comment by AshTappin** [comment]
Thanks @tnorling ! Will I need to call `logout` in an event handler?

**Comment by tnorling** [comment]
Yes you should be able to do something like this:

```javascript
if (event.eventType === EventType.LOGIN_SUCCESS) {
        if (event.payload.idTokenClaims["acr"] === "forgotPasswordPolicy") {
            instance.logout({account: event.payload.account});
        }
}
```

**Comment by AshTappin** [comment]
That has worked for me (in our case the policy is stored on the tfp claim). Thank you!

**Comment by AshTappin** [comment]
@tnorling The issue that you mentioned about the tokens returned from the reset password policy not being valid for sign in (or another policy), is that an intended feature of B2C or is it a bug?

**Comment by tnorling** [comment]
@AshTappin This is by design.
