### ISSUE TITLE
How to pass custom parameters during token exchange?

### ISSUE THREAD

**Issue by dopsonbr** [AzureAD/microsoft-authentication-library-for-js#3204]
## Library

- [] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

How do I pass custom parameters to the token request? I have a use case where I need to pass a custom parameter (`roles`) during the token exchange. I didn't see anything in the [configuration docs](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/configuration.md). If it is not possible, would you be open to accepting a PR that enables this behavior? 

## Source

- [ ] Internal (Microsoft)
- [x] Customer request

**Comment by tnorling** [comment]
@dopsonbr We currently do not support this, but this is something we've been wanting to add and is currently sitting on the backlog. PRs are always welcome!

**Comment by dopsonbr** [comment]
Have you had any preliminary design talks or advice on what the implementation should look like? I can see this being done a few different ways.

**Comment by tnorling** [comment]
There's prior art with `extraQueryParameters` which is attached to the /authorize call. You can try to mimic that and call it `tokenQueryParameters` or something along those lines

**Comment by dopsonbr** [comment]
thanks. I'll take a look

**Comment by tnorling** [comment]
Closing as there's another ticket open for this feature. Please track #2785
