### ISSUE TITLE
Access token returned by PublicClientApplication.acquireTokenSilent is sometimes expired

### ISSUE THREAD

**Issue by thoo1** [AzureAD/microsoft-authentication-library-for-js#3206]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.11.1`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [ ] Angular
- [X] React
- [ ] Other

## Description
This ticket is related to this #2883.
The conclusion of #2883 was to edit the logic to calculate the expiry of the token using the token's `expires_in` property + the client side timestamp for when the request was started. 
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/msal-browser-v2.11.1/lib/msal-common/src/response/ResponseHandler.ts#L214

However I am observing that for some users, this time and the token's `exp` property represents are vastly different.
The problem is when msal-browser library thinks the token is still valid and returns it to the caller. However, when the caller uses this token to make some api call, they get a 401, ExpiredAuthenticationToken error.
This happens when the time is X, 
the `token.expiresOn` determine by msal-browser > X,
but the actual expiry of the token (represented in the token's `exp` property) < X

## Error Message
Example logs: 
where RealTokenExpiry == token's exp property
where MsalTokenExpiry == AuthenticationResult.expiresOn (returned by acquireTokenSilent)

timestamp | name | resultCode | customDimensions_msalMessage | RealTokenExpiry | MsalTokenExpiry | customDimensions_audience | customDimensions_tokenSource
-- | -- | -- | -- | -- | -- | -- | --
2021-03-03T14:15:05.276Z | Core_MSALAuthContext_getToken_Success |   |   | Wed, 03 Mar 2021 07:49:26 GMT | Wed, 03 Mar 2021 20:29:43 GMT |   | localStorage
2021-03-03T14:15:05.277Z | Core_MSALAuthContext_getToken_Success |   |   | Wed, 03 Mar 2021 07:49:26 GMT | Wed, 03 Mar 2021 20:29:43 GMT |   | localStorage
2021-03-03T14:15:05.36Z | POST https://management.azure.com/batch | 401 |   |   |   |   |  
2021-03-03T14:15:05.37Z | POST https://management.azure.com/batch | 401 |   |   |   |   |  

## MSAL Configuration

```js
    const publicClientApp = new PublicClientApplication({
      auth: {
        clientId: this.clientId,
        authority: this.authority,
        redirectUri: this.loginRedirectUri,
        postLogoutRedirectUri: this.postLogoutRedirectUri
      },
      cache: {
        cacheLocation: "localStorage",
        storeAuthStateInCookie: isIEOrOldEdge // https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1188#issuecomment-634281307
      },
      system: {
        tokenRenewalOffsetSeconds: Constants.tokenRenewalOffsetSeconds,
        iframeHashTimeout: 30000, // iframe is used to refresh the refresh_token as it has a 24h lifetime
        loggerOptions: {
          loggerCallback: MsalAuthContext.msalLoggerCallback,
          piiLoggingEnabled: false,
          logLevel: LogLevel.Verbose
        }
      }
    });
```

## Reproduction steps
Could not reproduce myself, I'm just seeing this in telemetry

## Expected behavior
That msal-browser only returns tokens that are valid.

## Identity Provider

- [X] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [X] Internal (Microsoft)
- [ ] Customer request

**Comment by thoo1** [comment]
In the discussion in #2883, I asked why the `exp` property of the access token is not used directly, but it seems like this field is not always present. Is there a precise scenario where the `exp` field in the access token is not there?
I ask because in our application's logs, we always have this field and can read it, for a mitigation, we are thinking of just using the time represented by the `exp` field to determine if we should
- return the accessToken if not expired
- called `acquiredTokenSilent` again, this time passing the argument `{forceRefresh: true}`

**Comment by thoo1** [comment]
if you notice the MsalTokenExpiry is Wed, 03 Mar 2021 20:29:43 GMT, which doesn't really make sense because that is about 6 hours ahead of the time the user made the request and by default, tokens are valid for at most 1 hour.
This looks to me like there is either
- a bug in the code but I can't seem to see any, it looks correct to me
- the client's clock is messed up at the time the request was made

So I took a look to see if there were any logs about an hour before Wed, 03 Mar 2021 20:29:43 GMT, but could not find any logs for the user, from our application during that time. Thus I am not able to confirm if the user's clock was incorrect.

I have some other info about the logs I was able to find internally but I can discuss that on Teams if you want

**Comment by tnorling** [comment]
@thoo1 Network logs would be useful here. The AAD server should always send back an `expires_in` property with the value 3599 (60 minutes) and the `exp` claim on the token should be a timestamp 1hr from the time the token was requested based on the auth server's clock. If msal is returning to you a cached token and the resource server then rejects this token due to expiration that suggests the resource server clock is skewed.

> But I'm not sure in what scenarios does my application not receive a non-JWT or encrypted token? Is this something my application controls or it is out of the application control?

Access tokens should be considered opaque strings and you should not rely on it being a JWT.

> A follow up question is, if we know that we can access the accessToken's exp property, can we pass some configuration to the library so that we can use this time as the token expiry time (instead of the reqTimestamp + expires_in time it is currently using?)

We do not crack open access tokens for the reason stated above and due to the fact that tokens should only be inspected by the resource it is intended for.

**Comment by thoo1** [comment]
I see, makes sense, and from reading the docs, I now understand why access tokens should be treated as opaque strings https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens

> Network logs would be useful here
I unfortunately dont have network logs since this is just from one user, I only have logs from the telemetry our app insights collects. I was able to find the AAD logs as well using LogsMiner but we can discuss that offline

> suggest the resource server clock is skewed
I'm actually thinking it is the client clock that is skewed. In looking at our app insight logs, the user's tokens usually expires an hour after it was issued however for the problematic request, I saw in the logs that the token returned by msal said it would expire in 6 hours. This suggests that at the time of calculating the token expiry in msal (expires_in + current time), the current time was skewed 5 hours forward.

With this in mind, I was thinking if msal should include extra logic that says "this token is not valid before some time" and that time would be the time that the token expiry calculation occurs
This would result in the token being refreshed via network call in this scenario
User gets a token at 1pm (client time), the token lasts for 1 hour so msal says the token is valid until 2pm.
User's clock moves back 5 hours, the time is now 8am (client time).
When `acquiredTokenSilent` is called, code checks that the current time is 8am but the token is not valid before 1pm.
This triggers the token to be fetched using network call

Let me know if this suggestion makes sense

**Comment by tnorling** [comment]
@thoo1 Unfortunately, this is an unsupported scenario. This is a very specific edge case that we are unlikely to handle in the library. Instead, your application should implement fallback logic that calls acquireTokenSilent with forceRefresh: true if the resource rejects a token due to expiration. Happy to discuss this in more detail if you'd like to reach out over Teams.

**Comment by thoo1** [comment]
@tnorling sorry to bring this back up again but our users are still having issue related to clock skew. I was wondering if msal could return the timestamp for when the token was received in the `AuthenticationResult`. The reason why is because we would like to try to use that timestamp as a "not valid before" time, and if the token is not valid, we force refresh

I know we spoke offline and the outcome was not to add this into the library, but we want to do this in our application side
Thanks!

**Comment by tnorling** [comment]
@thoo1 Can you use `expiresOn` to derive acquisition time by subtracting an hour?

**Comment by thoo1** [comment]
@tnorling we could but I'm not sure, are tokens always 1h lifetime?

**Comment by tnorling** [comment]
@thoo1 Yes, unless you [explicitly configure a different lifetime](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes) in which case you would know what your lifetime is expected to be.

**Comment by tnorling** [comment]
@thoo1 

>You can set token lifetimes for all apps in your organization, for a multi-tenant (multi-organization) application, or for a specific service principal in your organization.

It's set for the application. 

Another potential solution would be for your application to save the current time if the `AuthenticationResult` has `fromCache: false`.

**Comment by thoo1** [comment]
> It's set for the application.
I see.. for now I don't think we have a good enough reason to configure our app's token lifetime. Our app is also first party so maybe that changes things, we can take this as a separate issue later

> Another potential solution would be for your application to save the current time if the AuthenticationResult has fromCache: false.
Thanks for this suggestion, this would seem to work but if we save this time in memory, it wouldn't be consistent with how we are currently configuring msal to store stuff in `localStorage`. So say we have a token in cache already, and user comes to our site, we don't know when that token was received at (unless we subtract 1h from the expiresAt time)

**Comment by tnorling** [comment]
@thoo1 Understood. I'll see what we can do, but quite honestly this is pretty low priority for us in comparison to other efforts we have ongoing so not sure when we'll get to it. What exactly is the problem with just making a new ATS request with `forceRefresh: true` when the resource rejects the token?

**Comment by thoo1** [comment]
@tnorling thanks! I'll also see if I have some time to open a PR to do this but thanks for thinking about it

>What exactly is the problem with just making a new ATS request with forceRefresh: true when the resource rejects the token?

The main problem is that our application calls many different services (ARM, graph, other services) and we essentially have to maintain some mapping of "this service A throws error code C when the token is expired, and in that case we should try forceRefresh and retry".
- the mapping has to be maintained as we add more services or as api versions change and error codes change
- there is one more roundtrip and that impacts user experience, we want to try to apply as much mitigation as possible before we do this retry
That being said, it does sound correct to me that we have to have a worst case retry mechanism here, but at the same time, it'd be nice if we were able to make it first on the first time
