### ISSUE TITLE
Requesting token on every API call.

### ISSUE THREAD

**Issue by cagricaymaz** [AzureAD/microsoft-authentication-library-for-js#3207]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [X] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

MSAL requests access token on every backend API call. I have seen similar topics but I couldn't find my answer. I think requesting the token on every API call is not necessary. I assume there is a way to cache it and only request when needed. 

I have also checked that the access token is always changing. 

![image](https://user-images.githubusercontent.com/72180303/111021472-6268fe80-8381-11eb-9770-1941fa56a1f4.png)
 
Maybe, I am missing some settings part. I hope you guys can help me with this situation. 

```
export const b2cPolicies = {
    names: {
        signUpSignIn: 'B2C_1_SIGN-UP-SIGN-UP-IN-POLICY',
        resetPassword: 'B2C_1_PASSWORD-RESET-POLICY',
        forgotPassword:'B2C_1_PASSWORD-RESET-POLICY'
    },
    authorities: {
        signUpSignIn: {
            authority: 'https://xxx/B2C_1_SIGN-UP-SIGN-UP-IN-POLICY'
        },
        resetPassword: {
            authority: 'https://xxx/B2C_1_PASSWORD-RESET-POLICY'
        },
        forgotPassword: {
            authority: 'https://xxx/B2C_1_PASSWORD-RESET-POLICY'
        }
    },
    authorityDomain: "xxx"
};


export const apiConfig: { scopes: string[]; uri: string } = {
    scopes: ['https://xxx/Scope.Read'],
    uri: environment.baseApiUrl + '/api/'
};

export function loggerCallback(logLevel: LogLevel, message: string) {
    console.log(message);
}

export function MSALInstanceFactory(): IPublicClientApplication {
    return new PublicClientApplication({
        auth: {
            clientId: 'xxx',
            authority: b2cPolicies.authorities.signUpSignIn.authority,
            redirectUri: 'http://localhost:4200',
            postLogoutRedirectUri: 'http://localhost:4200',
            knownAuthorities: [b2cPolicies.authorityDomain]
        }, 
        cache: {
            cacheLocation: BrowserCacheLocation.LocalStorage,
            storeAuthStateInCookie: isIE,
        },
        system: {
            loggerOptions: {
                loggerCallback,
                logLevel: LogLevel.Info,
                piiLoggingEnabled: false
            }
        }
    });
}

```

## Source

- [ ] Internal (Microsoft)
- [X] Customer request

**Comment by devInterests** [comment]
I had the same issue. In my case it was with msal version 2.x. 
The problem was the scope. The answer had a different scope than that which had been requested.
In this case, no token is found in the cache for the requested scope and a new token is requested.
So check if the response contains a token for your requested scope.

**Comment by tnorling** [comment]
@cagricaymaz Can you share your usage where you make your token and API call? `acquireTokenSilent` does lookup tokens in the cache first before making a network request. Enabling verbose logs would also be helpful here. [Instructions for enabling logs](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/configuration.md)

**Comment by cagricaymaz** [comment]
Hi, @devInterests 
My token response's scope is the same as the requested scope. 

![image](https://user-images.githubusercontent.com/72180303/111189834-b6d3d000-8573-11eb-9c71-b436b4ec6abf.png)

---

Hi @tnorling 
Seems like in my case, I always have "msal:acquireTokenFromNetworkStart" in the logs. I actually followed the same steps in angular_v11. 

![image](https://user-images.githubusercontent.com/72180303/111191142-fe0e9080-8574-11eb-93a9-778ec448e517.png)

**Comment by devInterests** [comment]
@cagricaymaz  As far as I understood, your scope in the example is ''https://xxx/Scope.Read''. But in the response the scope is  "https://..../466". So there is a token in the cache for "https://..../466" but not for ''https://xxx/Scope.Read" scope. But I am not sure about that.
However, what I did was debugging through  msal js lib. I started by acquireTokenSilent call and get inside the call stack. There I saw what was in the cache and what I was requesting.

**Comment by cagricaymaz** [comment]
I have debugged all steps in msal-angular and found my solution I think. There is a system.Options.tokenRenewalOffsetSeconds set for 300seconds. 

Where does it come from? Can I change it to 60 seconds? 

In my development environment, the access tokens expire in 300 seconds. So in my case, it is always expired. Changed it to 15 minutes and it is working as expected. 


```
...
else if (!cachedAccessToken || TimeUtils.isTokenExpired(cachedAccessToken.expiresOn,this.config.systemOptions.tokenRenewalOffsetSeconds)) {
            // Must refresh due to expired or non-existent access_token
            return true;
        }
...
```

**Comment by cagricaymaz** [comment]
I have fixed the issue that I am having so I can close the topic. Thank you.
