### ISSUE TITLE
Reduce bundle size 

### ISSUE THREAD

**Issue by badsyntax** [AzureAD/microsoft-authentication-library-for-js#3210]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

How can I reduce the bundle size of `@azure/msal-browser`? As seen in the screenshot below, this package is rather large. at 173KB (uncompressed). I don't think I'm using the full library so this large size is a bit of a surprise. It's not clear if my bundler is tree shaking or not. Do you have any guidance on steps I can take to reduce the size of this package?

<img width="795" alt="Screenshot 2021-03-14 at 14 46 52" src="https://user-images.githubusercontent.com/102141/111072918-8d179c00-84d4-11eb-8bf4-f0f661a7024e.png">

## Source

- [ ] Internal (Microsoft)
- [x] Customer request

**Comment by thoo1** [comment]
I found the same and am trying to open a PR to fix tree-shaking

I found this: https://github.com/rollup/rollup/issues/2807#issuecomment-484798155
looks like if as this library targets es5 rollup isn't able to tree shake properly

Not really familiar with all the different compilers (ts, rollup, babel) so I don't know the exact fix yet but hope this helps a bit
