### ISSUE TITLE
How to handle page reload with authorization code flow

### ISSUE THREAD

**Issue by devInterests** [AzureAD/microsoft-authentication-library-for-js#3213]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Hello,
we have currently updated to authorization code flow with msal 2.x. Login and acquireTokenSilent are working without problems.
However, on page reload acquireTokenSilent call can not get a token.

The problem is that after the reload I do not get the homeAccountId.

This is how i get it normally:

```js
public init(configuration): void
{

  this.msal = new Msal.PublicClientApplication({
      auth: {
        clientId: configuration.applicationId,
        authority: configuration.authority,
        knownAuthorities: [authorityDomain],
        redirectUri: configuration.callbackUrl,
        navigateToLoginRequestUrl: false,
        postLogoutRedirectUri: configuration.logoutUrl
      },
      system: {
        loggerOptions: {
          logLevel: Msal.LogLevel.Verbose,
          piiLoggingEnabled: false
        }
      }
    });

    this.msal.handleRedirectPromise()
      .then(response => {
        // response == null on page reload
        if (response) {
          this.accountId = response.account.homeAccountId;
        }
      })
      .catch(error => {
        console.error(error);
      });
}
```
The first time everything works as it should. With the reload, however, the promise is resolved with null.

Without the id the acquireTokenSilent call fails. Also, msal also does not have an active account, msal.getActiveAccount () returns null.

I found a workaround. But I would like to know:
 - what is wrong with my process? 
 - why don't I get an account on page reload?
 - is the workaround a valid solution?

Here is the workaround i'm doing:
```js

  public getAuthenticationToken(): Promise<string> {
    // is null by page reload. But there is an account with msal.
    if (this.accountId == null) {
     // this.msal.getActiveAccount() returns null.
      const accounts = this.msal.getAllAccounts();
      if (accounts.length !== 1) {
        return Promise.resolve(null);
      }

      this.accountId = accounts[0].homeAccountId;

    }

    const request = {
      scopes: [this.scope],
      account: this.msal.getAccountByHomeId(this.accountId),
    };

    return this.msal
      .acquireTokenSilent(request)
      .then(response => {
        return Promise.resolve(response.accessToken || response.idToken);
      })
      .catch(error => {
        console.warn(error);
    }
  }
```

## Source

- [ ] Internal (Microsoft)
- [x] Customer request

**Comment by tnorling** [comment]
@devInterests `handleRedirectPromise` will only receive a response after returning from a redirect, not on every page load. Your workaround of calling `getAllAccounts` is the suggested solution. Alternatively you can include this logic inside `handleRedirectPromise` in an else condition, which is demonstrated in our samples [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-browser-samples/VanillaJSTestApp2.0/app/default/auth.js)

**Comment by devInterests** [comment]
@tnorling Thanks, will do.
