### ISSUE TITLE
Verifying ID Tokens With msal-node

### ISSUE THREAD

**Issue by bezi** [AzureAD/microsoft-authentication-library-for-js#3221]
## Library
- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [x] `@azure/msal-node@1.0.1`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
Both the [API](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/api/msal-node.api.md) and the [documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens#validating-tokens)  on verifying client ID tokens means that anyone who wants to do so in Node.js must implement it themselves.  I have just gone through the process of doing so, and would greatly prefer if it were a solution that Microsoft maintained and supports, as I have no interest in staying up to date on security nuances of token ID flows. Is there an existing way to do this within `msal-node` that I'm missing, or if not I'm happy to contribute what I have built and iterate it as necessary to make y'all happy with it.

Note: I see that there is [a passport strategy](https://github.com/AzureAD/passport-azure-ad/blob/dev/lib/jsonWebToken.js) for doing this, which is great, but I do not use passport, and perhaps it would be simplest to pull it into `msal-node`, and then have the passport strategy import it?

Thanks!

**Comment by sameerag** [comment]
We are currently designing node middleware and this work may take a quarter to be in code. We will consider this request and see if we can provide some options. cc @pkanher617

**Comment by pkanher617** [comment]
@bezi Thanks for opening this! I am working on adding this to msal-node, but as @sameerag said above, it may take some time. I will try to see if I can add this feature before we release an updated version of the passport library.

**Comment by bezi** [comment]
Thanks for the follow-up!

**Comment by sameerag** [comment]
Tagging with the new node-validation library in works, cc @jo-arroyo

**Comment by jasonnutter** [comment]
Ability to validate id tokens will be in the new Node Token Validation library, closing.

**Comment by DevRCRun** [comment]
Is there any indication please as to when the new library is targeted to be available for production use? (I've found the work in progess at https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/node-token-validation )
