### ISSUE TITLE
ClientAuthError: request_cannot_be_made:  Token request cannot be made without authorization code or refresh token.

### ISSUE THREAD

**Issue by IIrafail** [AzureAD/microsoft-authentication-library-for-js#3224]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [x] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [ ] Angular
- [ ] React
- [x] Electron

## Description
I have created an application that needs accesses the outlook calendar of a user. When I test with my personal outlook account it works without any issues, but when attempting to log in with an organization it throws the following error.  Does it have to do with any policies of my organization or is it a problem with my code? Should I handle organization accounts differently using the msal library or contact my administrator?
## Error Message

Uncaught (in promise) Error: 
Error invoking remote method 'login': 
ClientAuthError: request_cannot_be_made: 
Token request cannot be made without authorization code or refresh token.

i.send.i.invoke  @  electron/js2c/renderer_init.js:75

   Promise.then (async)
   step  @  mgt-login.js:33
  eval  @  mgt-login.js:34
   __awaiter @  mgt-login.js:30
   login  @  mgt-login.js:118
   onClick  @  mgt-login.js:363
   handleEvent  @  parts.js:480
   EventPart.__boundHandleEvent  @  parts.js:446

## MSAL Configuration

```js
   const config: MsalElectronConfig = {
    clientId: "my id",
    mainWindow: mainWindow, //This is the BrowserWindow instance that requires authentication
    scopes: [
      'user.read',
          'user.read',
          'people.read',
          'user.readbasic.all',
          'contacts.read',
          'presence.read.all',
          'presence.read',
          'user.read.all',
          'calendars.read'
    ],//cachePlugin: new PersistenceCachePlugin(filePersistence)
    
  };
  ElectronAuthenticator.initialize(config); 
```

## Reproduction steps

```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Identity Provider

- [ ] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [x] Not sure

## Browsers/Environment

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [x] Electron 11

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [x] Customer request

**Comment by sameerag** [comment]
Can you please share your request calls, the initial interactive call and the following silent call? And can you please turn on logs? The sample code to turn on logs can be found [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/configuration.md).

**Comment by IIrafail** [comment]
@sameerag  Actually I am using `@microsoft/mgt-electron-provider` in electron which from what I understand has a different config. Any info on that config because I cannot find the options for it. I am using the `<mgt-login></mgt-login>` element so I don't make the requests manually to log in. All I know is that I click sign in, enter my credentials and once the window closes I am logged in and can make requests. 

Problem is that with a consumer outlook account it works without any problems while with two organization accounts that I tested it throws the aforementioned error. I used [this](https://docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app) tutorial from Microsoft to create the application.

**Comment by sameerag** [comment]
@IIrafail Did you contact the dev team that manages @microsoft/mgt-electron-provider? @amrutha95 can you take a look?

**Comment by amrutha95** [comment]
Hi @IIrafail! I'm curious to know what option is selected under "Supported Account Types" in your app registration on Azure.
![image](https://user-images.githubusercontent.com/22471775/114428111-a6ae1100-9b70-11eb-8a4b-b35ad85a05be.png)

Could you let me know if the third option is checked? (Accounts in any directory and personal Microsoft accounts)

**Comment by IIrafail** [comment]
@amrutha95 This is the option I have selected. It turns out that if I try to login a second time it then shows me a message that I need administrator permission. Not sure why it didn't show the first time. I later found out [here](https://stackoverflow.com/questions/66749567/admin-aproval-required-even-for-basic-microsoft-graph-permissions) that even for basic permissions like calendar organizations might choose to block them by default. Note I am not an admin so I have no control. 

I think the bug in this case is that the "approval required" message should show the first time you try to log in.

**Comment by amrutha95** [comment]
Hi @IIrafail ! Do you mind raising an issue for this on the Microsoft Graph Toolkit [repository](https://github.com/microsoftgraph/microsoft-graph-toolkit)?

**Comment by IIrafail** [comment]
@amrutha95  I will open the issue there, thanks
