### ISSUE TITLE
MSAL Token Issue | Error: Token Renewal Time out error

### ISSUE THREAD

**Issue by yoursnikhilsinha** [AzureAD/microsoft-authentication-library-for-js#3228]
## Library
- [x] `msal@1.4.6'

## Framework

- [ ] React

## Description
We  have a  SPFx(React) solution and MSAL.js v1.4. 

Initial page start / authentication works however, post token expiry(1 hour) MSAL is not regenerating the token and we are getting “Token Renewal Time out error”.

Also as per implementation we have set the configuration to “LocalStorage” as then the token cache will be shared amongst the other tabs in same browser(Edge Chromium and Google Chrome).  

## Error Message
Token Renewal Time out error

## MSAL Configuration
```javascript
const msalConfig = {
            
            authority: 'https://login.microsoftonline.com/<tenantID>',
            
            clientId: '<Azure Ad App Client Id>', //PROD
            navigateToLoginRequestUrl: true,
            
           redirectUri: () => 'https://xx.com'
            };
          const myMSALObj= new MSAL.UserAgentApplication({
            auth:msalConfig,
            cache:{
              cacheLocation:'localStorage',
              storeAuthStateInCookie: true
            },
            system:{
                tokenRenewalOffsetSeconds:300,
                logger: new MSAL.Logger(()=>{

                },{
                    level:MSAL.LogLevel.Verbose,
                    piiLoggingEnabled:false,
                    correlationId:"1234"
                }
                )
            }
          });
          const accessTokenRequest: MSAL.AuthenticationParameters = {
            scopes: ["<Azure Ad App Client Id>/user.read", "<Azure Ad App Client Id>/user_impersonation"],
                          loginHint: this._pageContext.user.email,
             authority: "https://login.microsoftonline.com/<tenantID>"
           };
           var token = await (await myMSALObj.acquireTokenSilent(accessTokenRequest)).accessToken
           console.log('Token from Msal 1.4', token)
           localStorage.setItem('Token',token)
           console.log('Storing into localStorage',localStorage.getItem('Token'))

```

## Reproduction steps
After 1 hour of token expiry navigating from Tab 1 to Tab 2 of same browser.

## Expected behavior
The Token should generate and data should be pulled on the screen.
## Identity Provider
- [x] Azure AD

## Browsers/Environment

- [ ] Chrome
- [ ] Edge

@jasonnutter 
## Regression

- [ ] Did this behavior work before?No
Version:

## Security

- [ ] Is this issue security related? No

## Source

- [ ] Customer request

**Comment by yoursnikhilsinha** [comment]
@tnorling I have provided all the information as was there in the template anything specific you are looking for do let me know?

**Comment by tnorling** [comment]
@yoursnikhilsinha Timeouts can happen for a number of reasons. Can you start by reviewing our [documentation](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/docs/errors.md#token-renewal-operation-failed-due-to-timeout) about this particular error and let me know if you need more help?

**Comment by yoursnikhilsinha** [comment]
@tnorling yeah we checked the aspect mentioned in the document which we have gone through and as you mentioned about acquireTokenPopup.We have set up redirect to a blank html page also we cant use acquireTokenPopup as the user will not put their credential again for this. Please do let me know if you have any other recommendations.

**Comment by tnorling** [comment]
@yoursnikhilsinha Can you clarify, are 3rd party cookies disabled in your browser?

**Comment by yoursnikhilsinha** [comment]
@tnorling yes it is disabled.

**Comment by tnorling** [comment]
Unfortunately 3rd party cookies are **required** for the silent flow to work. Your only options are:

1. Enable 3rd party cookies
2. Call an interactive method (acquireTokenPopup or acquireTokenRedirect)
3. Upgrade to `msal-browser@2.x`

**Comment by yoursnikhilsinha** [comment]
@tnorling as you have mentioned I have enable the 3rd party cookie and will let you know the outcome. But is it really required to do item 2 as told earlier that user will not prefer to relog in after the Token Expire .And for item 3 we updated from version 1.3 to 1.4.6 how does version upgrade to 2.x help here.

**Comment by tnorling** [comment]
@yoursnikhilsinha Msal@1.x uses hidden iframes to do silent token renewal which rely on 3rd party cookies. If these are disabled the only way to renew your token is to call an interactive method.

Version 2.x uses the Auth Code Flow with PKCE which utilizes a refresh token and a POST request instead of the hidden iframe so it does not use hidden iframes until the refresh token expires (24 hours).

You can read more about the limitations of 3rd party cookie blocking and how the Auth Code Flow mitigates this [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-third-party-cookies-spas) and you'll find a migration guide from version 1 to version 2 [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/v1-migration.md)

**Comment by yoursnikhilsinha** [comment]
@tnorling I see your point to update to version 2.x but what I read in the link your shared says its for only Single Page Application but ours is a web application not SPA, so do you think this would be a limitation and I may get into same situation or something else if we uppgrade.Also are you saying that Token expiry is 24 hours with version 2.x but with previous version it is 1 hour can you please confirm both the point.

**Comment by tnorling** [comment]
@yoursnikhilsinha 

> what I read in the link your shared says its for only Single Page Application but ours is a web application not SPA

Both msal 1.x and 2.x are only for Single Page Applications. What we mean by that is that your application does not have a server component. If your application does have a server component you should use a server side library for auth.

> Also are you saying that Token expiry is 24 hours with version 2.x but with previous version it is 1 hour

In both 1.x and 2.x, access token expiry is 1 hour. In version 2 we also use a refresh token that has a 24 hour expiry and can be used to obtain a new 1 hr access token. Version 1 does not use a refresh token and thus is reliant on hidden iframes to renew access tokens and this scenario is broken without 3rd party cookies.

**Comment by jasonnutter** [comment]
Closing, as no further action needed at this time.
