### ISSUE TITLE
Can not logout from different zone?

### ISSUE THREAD

**Issue by zzbxd** [AzureAD/microsoft-authentication-library-for-js#3231]
## Library

- [ ] `msal@1.4.5` 

## Description

I have a React using AzureAD MSAL.js (version "^1.4.5",) and Dotnetcore 3.1 SPA program. I deployed the program on Azure US East2 region, so the deployed url is **{projece_name}.azurewebsites.net**

Everything went fine if we browser from US Eastern, we can log in, log out success; 
However, offshore team(non US region) can login success, but they cannot logout the program. During debug they found they failed on this network call during logout, the status is 'Canceled'
https://login.microsoftonline.com/{ hide }/oauth2/v2.0/logout?client-request-id=xxxxx1&post_logout_redirect_uri=https%3A%2F%2Flogin.microsoftonline.com%common%2Foauth2%2Flogout

## Source
Here is some code from C# and React:
c# code:
`services.AddCors(options => { options.AddPolicy("CorsPolicy", builder => builder.SetIsOriginAllowed(_ => true) .AllowAnyMethod() .AllowAnyHeader() .SetIsOriginAllowedToAllowWildcardSubdomains() .AllowCredentials()); });`

React Code:
`export const msalAuth = new UserAgentApplication({ auth: msalConfig, cache: msalCache,});`

`export const msalConfig = { authority: 'https://login.microsoftonline.com/myCompanyTenantId', clientId: 'myCompanyClientId', redirectUri: document.getElementById('root').baseURI, postLogoutRedirectUri: 'https://login.microsoftonline.com/common/oauth2/logout', validateAuthority: false, navigateToLoginRequestUrl: false, };`

`export const msalCache = { cacheLocation: 'sessionStorage', storeAuthStateInCookie: false, }; // also tried cacheLocation: 'localStorage',`

`onSignOut() { msalAuth.logout(); }`
- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by tnorling** [comment]
@zzbxd Are there any errors thrown that might explain why it's failing? I would suggest opening a ticket with Azure support as this does not sound library related.

**Comment by zzbxd** [comment]
The error status is 'Canceled', I update the description.

**Comment by tnorling** [comment]
Cancelled status can happen if the component that initiated the logout unmounts before the redirect to the logout endpoint occurs.

I'm also noticing your `postLogoutRedirectUri` is set to `https://login.microsoftonline.com/common/oauth2/logout`. This should be set to a page in your app, not the server logout page.

**Comment by zzbxd** [comment]
ok, I will change  `postLogoutRedirectUri` to a local page. 

Meanwhile, change logout function like below will help my component unmounted later?
`    async onSignOut() {
      await msalAuth.logout();
    }
`

**Comment by tnorling** [comment]
@zzbxd That could help but I can't say for sure. You'll need to do some debugging to determine if this is the cause and if so, how to prevent it. This is highly dependent on the details of your specific app so I can't be of assistance in that aspect.

**Comment by zzbxd** [comment]
@tnorling No luck, offshore team still has same issue after I `await msalAuth.logout();` and change redirect to local.

I also add new function `componentWillUnmount()`, but from console log it never get triggered;
`    componentWillUnmount() {
      console.log('unmount component');
    }`

Is there anything else could cause logout() cancel ?

I asked company Azure team and they do not know.

**Comment by zzbxd** [comment]
@tnorling You are correct, it is my code bug. My component unmounts earlier.
