### ISSUE TITLE
React-admin and msal-react

### ISSUE THREAD

**Issue by ducalai** [AzureAD/microsoft-authentication-library-for-js#3232]
## Library
- [ ] `@azure/msal-browser@2.12.1`
- [ ] `@azure/msal-react@1.0.0-beta.0`

## Description
I am trying to protect a React-admin application with Azure AD B2C using msal-react lib. I cannot make it run.

What is the recommended approach to integrate msal-react with React Admin app? Should I use build-in React Admin Authentication concepts (authProvider, loginPage, loginButton) or should MsalProvider and explictly call loginPopup/loginRedirect methods?

**Comment by tnorling** [comment]
@ducalai I am not familiar with React-admin and how that can be integrated with msal-react so I unfortunately don't have specific guidance I can provide. If you run into any specific issues with msal-react though we would be happy to help you solve them.

**Comment by tnorling** [comment]
Closing, please open a new issue if you run into issues with `msal-react`. Thanks!
