### ISSUE TITLE
Configuring PKCE with MSAL 2.0

### ISSUE THREAD

**Issue by forellendev** [AzureAD/microsoft-authentication-library-for-js#3239]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ X ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

Hi guys, I'm not sure how to configure PKCE (codeChallenge, codeChallengeMethod) by not creating the URL manually, but by configuring the [PublicClientApplication](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/initialization.md) instance.

## Source

- [x] Internal (Microsoft)
- [ ] Customer request

**Comment by tnorling** [comment]
@forellendev PKCE params are added internally in the library. Are you running into any specific issue?

**Comment by forellendev** [comment]
@tnorling thank you and sorry for the delay. That's good to hear that PKCE is used by default, but I thought that it would be convenient to allow choosing the secret to be hashed manually

**Comment by tnorling** [comment]
@forellendev Can you explain a little bit more about your use case and why you need to provide this value manually?

**Comment by forellendev** [comment]
@tnorling The RFC 7636 states that a high-entropy cryptographic random String should be used in order to avoid guessing. I know this is a little bit over the top, but some laptops have a TMP that act as a TRNG which would be nice to use for random values.

**Comment by tnorling** [comment]
@forellendev Do you mean TPM? I'm curious how you plan to access the TPM from the browser?

**Comment by forellendev** [comment]
It's early stage really, but I think will be common in laptops once manufacturers add them by default:
https://google.github.io/tpm-js/

**Comment by tnorling** [comment]
Closing as we do not have plans to support software TPM. We have a [feature currently in preview](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/device-bound-tokens.md) which will allow you to broker requests through the Web Account Manager on Windows, which uses the hardware TPM to bind tokens to the machine on which they were requested.
