### ISSUE TITLE
MSAL.js 1.4.6 single sign out with Multiple tabs

### ISSUE THREAD

**Issue by maacaro** [AzureAD/microsoft-authentication-library-for-js#3244]
## Library

- [x] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

is there a way to sign out at once in multiples tabs? I am running into a situation where the user login in tab1 then the user open another tab for the same app, then the user logout on tab1 while the user is still logged in tab2, then the user reload tab 2 and still logged,
## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by tnorling** [comment]
@maacaro Are you using local or session storage? If you're using local storage cache should be cleared for both tabs when you log out of one. If you're using session storage each tab has it's own storage so the only way to clear tab 2 would be to either close the window or call logout on that tab as well.

**Comment by maacaro** [comment]
@tnorling thanks you, I changed session storage by local storage, and it works

**Comment by tnorling** [comment]
Great, thanks for the update!
