### ISSUE TITLE
Use HTTP verbs when mapping protected resources

### ISSUE THREAD

**Issue by NDalvise** [AzureAD/microsoft-authentication-library-for-js#3246]
## Library
- [x] `@azure/msal-angular@2.0.0-beta.1`
- [ ] `@azure/msal-browser@2.12.1`

## Description
In the Angular wrapper for MSAL the MsalInterceptorConfiguration maps the protected endpoints through the protectedResourceMap object. The mapping is done by matching a URI and an array of scopes.

Suppose to interact with a RESTful web API backend that expose an endpoint (https://example.com/api/resource). That endpoint produces different results based on the HTTP verb used to call it. By design the GET call is unprotected (everyone can call it) and the POST call is protected (only authorized users should call it).

In this scenario the Angular interceptor is not able to see the difference between the two calls because it works mapping the bare URI to a set of scopes. It could use the "HTTP verb + URI" pair to map endpoints that at the same URI have different authorization scopes based on the HTTP verb used.

## Source

- [ ] Internal (Microsoft)
- [x] Customer request

**Comment by jasonnutter** [comment]
@NDalvise Thanks for the feature request, we have also been considering adding this enhacement. We'll add it to the backlog.
