### ISSUE TITLE
The Code_Verifier does not match the code_challenge

### ISSUE THREAD

**Issue by mbrevda** [AzureAD/microsoft-authentication-library-for-js#3248]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [ ] Angular
- [x] React
- [ ] Other

## Error Message

```
Uncaught (in promise) ServerError: invalid_grant: 501481 - [2021-03-19 13:18:03Z]: AADSTS501481: The Code_Verifier does not match the code_challenge supplied in the authorization request.
```
## MSAL Configuration

```js
const initMsal = ({msalConfig}) => {
  const postLogoutRedirectUri =
    process.env.AZURE_AD_REDIRECT_URL + '?redirectTo=' + origin + '/logout'

  const auth = {
    postLogoutRedirectUri,
    cloudDiscoveryMetadata,
    authorityMetadata,
    ...msalConfig.auth
  }

  const cache = {cacheLocation: 'localStorage', ...msalConfig.cache}
  const config = {...msalConfig, auth, cache}

  return new PublicClientApplication(config)
}

```

## Reproduction steps
I'm using silent SSO and using a [cross-domain postMessage broker](https://www.npmjs.com/package/scania-cross-storage) to retrieve the login hint. The first time the page is loaded (clean cache) I get the above error. It would further seem that the user is actually logged in: `.getAllAccounts()` has an account and the next load logs the user in instantly. Didn't include code as it doesn't seem pertinent, would be happy to provide anything necessary.

## Expected behavior
The user should log in with no interaction

## Identity Provider

- [x] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by tnorling** [comment]
@mbrevda This is likely a usage issue, can you provide as much relevant code so that I can try to reproduce? Also a fiddler trace would be helpful so I can check against server logs. You can email it to me, my emails on my profile. Thanks!

**Comment by mbrevda** [comment]
responded via email

**Comment by tnorling** [comment]
Found that the page used as `redirectUri` is also invoking `ssoSilent` and application code is adding the current url to `state` resulting in an iframe within an iframe with the 2nd iframe being returned to a url that has 2 codes in it: the `code` returned from the server and the `code` from the first iframe that was added to `state`. This resulted in a mismatch when exchanging the code for a token.

Mitigations are to:
1. Strip the hash off of the url before passing into `state`
2. Make sure the page used as `redirectUri` is not invoking msal APIs on page load (you can use a blank page for silent and popup scenarios)

MSAL Team will work on adding an enhancement to the library to throw a descriptive error when attempting to call msal APIs from within iframes opened by MSAL to prevent this scenario from happening to others in the future.

**Comment by tnorling** [comment]
Closing as resolved offline. Please open a new issue if you have further questions. Thanks!
