### ISSUE TITLE
@azure/msal-angular - MsalBroadcastService: inProgress$ does not emit last value

### ISSUE THREAD

**Issue by mdarefull** [AzureAD/microsoft-authentication-library-for-js#3253]
## Library

- @azure/msal-browser": "^2.12.1"
- @azure/msal-angular": "^2.0.0-beta.1",

## Framework

- [ X] Angular
- [ ] React
- [ ] Other

## Description
In the documentation for [handling redirects](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/redirects.md) it is recommended to use `MsalRedirectComponent `to handle the redirects and `MsalBroadcastService.inProgress$` for, quote `Pages that wish to perform functions following redirects...`

The problem is that inProgress$ won't emit the last value, so if the page subscribes after the redirect has been handled by MsalRedirectComponent, the subscription will never execute.
It is a nuance mainly because of race conditions, I cannot ensure a given component will subscribe before/after the redirects are handled causing the code to no execute. Not using the subscription means the opposite, the possibility for the code to run while the interaction is still in progress.

## Identity Provider

- [ ] Azure AD
- [X ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

**Comment by jo-arroyo** [comment]
@mdarefull Thanks for your feedback. We are aware this has been an issue for our customers, and a fix with updated documentation scheduled for the next release.
