### ISSUE TITLE
Allow setting a custom logger

### ISSUE THREAD

**Issue by davidrapin** [AzureAD/microsoft-authentication-library-for-js#3256]
We have a custom logger and don't want this library to write to stdout by itself.

For now, this is how we overwrite the default bunyan logger:

``` JavaScript
  var Logging = require('passport-azure-ad/lib/logging');
  class CustomLogger {
    info(m) {}
    warn(m) {
      Log.warn('Azure AD: ' + m);
    }
    error(m) {
      Log.warn('Azure AD: ' + m);
    }
    levels(m) {}
  }
  Logging.getLogger = CustomLogger;
  var OIDCStrategy = require('passport-azure-ad').OIDCStrategy;
```

It seems to be working but we'd prefer to have a `OIDCStrategy` constructor option to do that.

**Comment by Sefriol** [comment]
Probably a different issue, but it would be nice if [MSAL Logger](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/src/logger/Logger.ts) would allow a configuration parameter to return log message as a JSON instead. Then the end user could define their own logging message style instead on relying on the provided one.

**Comment by jo-arroyo** [comment]
We are working on middleware scenarios that will be built on top of msal-node, where the MSAL Logger with customizations is available. Keep an eye out for future msal-node updates. 

@Sefriol Please open up a separate issue [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/new/choose) for returning a log message as JSON.
