### ISSUE TITLE
Supporting both AAD v1 and AAD v2 from the same service

### ISSUE THREAD

**Issue by ydogandjiev** [AzureAD/microsoft-authentication-library-for-js#3259]
Hey guys, I am trying to build an app that can work with both token issued by the AAD v1 endpoint (for the case where I am fetching the token from an Office app host) as well as the AAD v2 endpoint (for the case where I am using MSAL.js to authenticate users on my site). Unfortunately, when using the OIDCBearerStrategy I am only able to provide one endpoint and it doesn't seem like there is a way to change that on a per-request basis:
```
passport.use(
  new OIDCBearerStrategy(
    {
      identityMetadata:
        "https://login.microsoftonline.com/common/.well-known/openid-configuration"
```

My client app always sends a QSP indicating which AAD endpoint was used to generate the access token. In the case where I know the token has been issued by the AAD v2 endpoint I need to set my identityMetadata to the corresponding v2 endpoint:
```
"https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration"
```

Is there some way to do this, e.g.:
- Allowing the identityMetadata endpoint to be changed on a per request basis (i.e. when calling ```passport.authenticate```)
- Allowing multiple instances of the OIDCBearerStrategy to be registered (i.e. one for v1 and another for v2)

**Comment by pkanher617** [comment]
We are working on an update for the passport library that will encompass this ask, you can track the progress [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/projects/9).

**Comment by jasonnutter** [comment]
Ability to set metadata per request for new Node Token Validation library will be tracked internally in ADO, closing. @jo-arroyo
