### ISSUE TITLE
Update npm bunyan to fix moment 2.18.1 vulnerability

### ISSUE THREAD

**Issue by tmschbgr** [AzureAD/microsoft-authentication-library-for-js#3261]
Hi,

there is a regular expression denial of service vulnerability in the npm package moment, which is a dependency of bunyan.

Please update the bunyan dependency in order to fix this issue.

Cheers

![capture](https://user-images.githubusercontent.com/22215462/39737385-ddad2062-52d8-11e8-9b6b-2dd7a2a68f5e.PNG)

**Comment by jo-arroyo** [comment]
No longer a security vulnerability. Closing.
