### ISSUE TITLE
Seeing collectInfoFromReq error after app is up for a period of time

### ISSUE THREAD

**Issue by billytrend** [AzureAD/microsoft-authentication-library-for-js#3264]
We have a node application running with 3 instances and using express-session to persist sessions. Everything works fine until a period of time has elapsed, around a week. After that time, no one is able to authenticate and we see `authentication failed due to: In collectInfoFromReq: invalid state received in the request` in the logs.

When we bounce the service, everything works fine. I have tried to replicate the issue without waiting for the period of time to elapse however I haven't managed to trigger it.

The problem seems somewhat similar to AzureAD/passport-azure-ad#289 but that doesn't seem to have a clear resolution.

**Comment by pkanher617** [comment]
We will investigate this issue further in the latest version of the passport library. You can track the progress [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/projects/9)

**Comment by jo-arroyo** [comment]
As passport-azure-ad is now in maintenance, we will not be addressing this issue in the library. Please watch out for future middleware scenarios built on top of msal-node.
