### ISSUE TITLE
SAML & WS-Fed Support

### ISSUE THREAD

**Issue by KurtPattyn** [AzureAD/microsoft-authentication-library-for-js#3265]
Why was the SAML and WS-Fed support removed from version 3.x? Is there a specific reason for this?
According to the README.md "It includes OpenID Connect, **WS-Federation**, and **SAML-P** authentication and authorization."

**Comment by pkanher617** [comment]
We will investigate this issue and update here when we have a definitive answer, thanks for your patience.

**Comment by jo-arroyo** [comment]
As passport-azure-ad is now in maintenance and future middleware scenarios will be built on top of msal-node, please watch for msal-nodes announcements regarding this SAML and WS-Fed. 

@EmLauber for your prioritization.
