### ISSUE TITLE
Pass state cookie domain in configuration

### ISSUE THREAD

**Issue by fchoquet** [AzureAD/microsoft-authentication-library-for-js#3267]
Hi

The state cookie domain is currently not explicitly set and is therefore linked to the request's subdomain. The consequence is that the cookie is not available when we try to read it from another subdomain.

This situation occurs when the login page can be served from 2 distinct subdomains (via a rewrite), for instance `app.mydomain.com` and `login.mydomain.com`.

If the user enters the application via the `app` subdomain we get this error: `authentication failed due to: In collectInfoFromReq: invalid state received in the request`. This is caused by the impossibility to read the state cookie (because it is linked to another domain).
 
We've forked the project to pass the state cookie domain in the configuration. This way it is possible to set it to `mydomain.com` and share it across subdomains. 

Here's the PR: https://github.com/AzureAD/passport-azure-ad/pull/400

**Comment by pkanher617** [comment]
We are working on a new version of the passport-azure-ad library and will include this feature. You can follow the progress [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/projects/9).

**Comment by jo-arroyo** [comment]
Closing issue as PR has been merged.
