### ISSUE TITLE
Lots  of msal.acquireTokenUser in storage

### ISSUE THREAD

**Issue by spottedmahn** [AzureAD/microsoft-authentication-library-for-js#327]
I'm seeing lots of `msal.acquireTokenUser|` in storage.  I suspect there is only supposed to be one?

![image](https://user-images.githubusercontent.com/14079228/41371283-de360250-6f17-11e8-932d-e4036db09ac5.png)

<details><summary>Log file</summary>
11:48:34.083 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:34 GMT:12345-0.1.6-Verbose Token is not in cache for scope:https://our-tenant.onmicrosoft.com/our-scope<br/>
11:48:34.121 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:34 GMT:12345-0.1.6-Verbose Token is not in cache for scope:https://our-tenant.onmicrosoft.com/our-scope<br/>
11:48:34.127 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:34 GMT:12345-0.1.6-Verbose Token is not in cache for scope:https://our-tenant.onmicrosoft.com/our-scope<br/>
11:48:34.252 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:34 GMT:12345-0.1.6-Verbose Token is not in cache for scope:https://our-tenant.onmicrosoft.com/our-scope<br/>
11:48:34.261 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:34 GMT:12345-0.1.6-Verbose Token is not in cache for scope:https://our-tenant.onmicrosoft.com/our-scope<br/>
11:48:34.279 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:34 GMT:12345-0.1.6-Verbose Token is not in cache for scope:https://our-tenant.onmicrosoft.com/our-scope<br/>
11:48:34.299 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:34 GMT:12345-0.1.6-Verbose Token is not in cache for scope:https://our-tenant.onmicrosoft.com/our-scope<br/>
11:48:34.756 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:34 GMT:12345-0.1.6-Verbose renewing accesstoken<br/>
11:48:34.758 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:34 GMT:12345-0.1.6-Verbose renewToken is called for scope:https://our-tenant.onmicrosoft.com/our-scope<br/>
11:48:34.770 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:34 GMT:12345-0.1.6-Verbose Renew token Expected state: 0e9ea888-c279-4a70-8ec3-723392884abe<br/>
11:48:34.774 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:34 GMT:12345-0.1.6-Verbose Set loading state to pending for: https://our-tenant.onmicrosoft.com/our-scope:0e9ea888-c279-4a70-8ec3-723392884abe<br/>
11:48:35.284 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:35 GMT:12345-0.1.6-Verbose Renew token for scope: https://our-tenant.onmicrosoft.com/our-scope is in progress. Registering callback<br/>
11:48:35.717 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:35 GMT:12345-0.1.6-Verbose Renew token for scope: https://our-tenant.onmicrosoft.com/our-scope is in progress. Registering callback<br/>
11:48:36.097 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:36 GMT:12345-0.1.6-Verbose Renew token for scope: https://our-tenant.onmicrosoft.com/our-scope is in progress. Registering callback<br/>
11:48:36.439 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:36 GMT:12345-0.1.6-Verbose Renew token for scope: https://our-tenant.onmicrosoft.com/our-scope is in progress. Registering callback<br/>
11:48:36.914 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:36 GMT:12345-0.1.6-Verbose Renew token for scope: https://our-tenant.onmicrosoft.com/our-scope is in progress. Registering callback<br/>
11:48:37.092 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:37 GMT:12345-0.1.6-Verbose Renew token for scope: https://our-tenant.onmicrosoft.com/our-scope is in progress. Registering callback<br/>
11:48:37.958 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:37 GMT:12345-0.1.6-Verbose Window is in iframe, acquiring token silently<br/>
11:48:46.469 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:46 GMT:12345-0.1.6-Verbose Token is not in cache for scope:https://our-tenant.onmicrosoft.com/our-scope<br/>
11:48:46.514 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:46 GMT:12345-0.1.6-Verbose Token is not in cache for scope:https://our-tenant.onmicrosoft.com/our-scope<br/>
11:48:46.521 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:46 GMT:12345-0.1.6-Verbose Token is not in cache for scope:https://our-tenant.onmicrosoft.com/our-scope<br/>
11:48:46.827 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:46 GMT:12345-0.1.6-Verbose renewing accesstoken<br/>
11:48:46.828 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:46 GMT:12345-0.1.6-Verbose renewToken is called for scope:https://our-tenant.onmicrosoft.com/our-scope<br/>
11:48:46.830 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:46 GMT:12345-0.1.6-Verbose Renew token Expected state: 1fa26ab0-ce9a-4c92-84ea-1aeedb5d38b9<br/>
11:48:46.832 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:46 GMT:12345-0.1.6-Verbose Set loading state to pending for: https://our-tenant.onmicrosoft.com/our-scope:1fa26ab0-ce9a-4c92-84ea-1aeedb5d38b9<br/>
11:48:47.535 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:47 GMT:12345-0.1.6-Verbose Renew token for scope: https://our-tenant.onmicrosoft.com/our-scope is in progress. Registering callback<br/>
11:48:48.265 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:48 GMT:12345-0.1.6-Verbose Renew token for scope: https://our-tenant.onmicrosoft.com/our-scope is in progress. Registering callback<br/>
11:48:48.929 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:48 GMT:12345-0.1.6-Verbose Window is in iframe, acquiring token silently<br/>
11:48:49.375 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:49 GMT:12345-0.1.6-Verbose Token is not in cache for scope:https://our-tenant.onmicrosoft.com/our-scope<br/>
11:48:49.473 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:49 GMT:12345-0.1.6-Verbose Token is not in cache for scope:https://our-tenant.onmicrosoft.com/our-scope<br/>
11:48:49.562 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:49 GMT:12345-0.1.6-Verbose renewing accesstoken<br/>
11:48:49.565 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:49 GMT:12345-0.1.6-Verbose renewToken is called for scope:https://our-tenant.onmicrosoft.com/our-scope<br/>
11:48:49.568 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:49 GMT:12345-0.1.6-Verbose Renew token Expected state: 3458ba5d-e942-41dc-a3c4-8e0fa7e63e40<br/>
11:48:49.571 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:49 GMT:12345-0.1.6-Verbose Set loading state to pending for: https://our-tenant.onmicrosoft.com/our-scope:3458ba5d-e942-41dc-a3c4-8e0fa7e63e40<br/>
11:48:49.741 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:49 GMT:12345-0.1.6-Verbose Renew token for scope: https://our-tenant.onmicrosoft.com/our-scope is in progress. Registering callback<br/>
11:48:51.641 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:51 GMT:12345-0.1.6-Verbose Window is in iframe, acquiring token silently<br/>
11:48:52.224 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:52 GMT:12345-0.1.6-Verbose Token is not in cache for scope:https://our-tenant.onmicrosoft.com/our-scope<br/>
11:48:52.234 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:52 GMT:12345-0.1.6-Verbose Token is not in cache for scope:https://our-tenant.onmicrosoft.com/our-scope<br/>
11:48:52.557 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:52 GMT:12345-0.1.6-Verbose renewing accesstoken<br/>
11:48:52.560 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:52 GMT:12345-0.1.6-Verbose renewToken is called for scope:https://our-tenant.onmicrosoft.com/our-scope<br/>
11:48:52.575 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:52 GMT:12345-0.1.6-Verbose Renew token Expected state: 12ac810d-e582-43cc-bcd9-5da2f5a54d99<br/>
11:48:52.578 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:52 GMT:12345-0.1.6-Verbose Set loading state to pending for: https://our-tenant.onmicrosoft.com/our-scope:12ac810d-e582-43cc-bcd9-5da2f5a54d99<br/>
11:48:52.747 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:52 GMT:12345-0.1.6-Verbose Renew token for scope: https://our-tenant.onmicrosoft.com/our-scope is in progress. Registering callback<br/>
11:48:54.694 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:54 GMT:12345-0.1.6-Verbose Window is in iframe, acquiring token silently<br/>
11:48:55.216 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:55 GMT:12345-0.1.6-Verbose Token is not in cache for scope:https://our-tenant.onmicrosoft.com/our-scope<br/>
11:48:55.231 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:55 GMT:12345-0.1.6-Verbose Token is not in cache for scope:https://our-tenant.onmicrosoft.com/our-scope<br/>
11:48:55.237 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:55 GMT:12345-0.1.6-Verbose Token is not in cache for scope:https://our-tenant.onmicrosoft.com/our-scope<br/>
11:48:55.246 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:55 GMT:12345-0.1.6-Verbose Token is not in cache for scope:https://our-tenant.onmicrosoft.com/our-scope<br/>
11:48:55.252 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:55 GMT:12345-0.1.6-Verbose Token is not in cache for scope:https://our-tenant.onmicrosoft.com/our-scope<br/>
11:48:55.261 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:55 GMT:12345-0.1.6-Verbose Token is not in cache for scope:https://our-tenant.onmicrosoft.com/our-scope<br/>
11:48:55.269 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:55 GMT:12345-0.1.6-Verbose Token is not in cache for scope:https://our-tenant.onmicrosoft.com/our-scope<br/>
11:48:55.275 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:55 GMT:12345-0.1.6-Verbose Token is not in cache for scope:https://our-tenant.onmicrosoft.com/our-scope<br/>
11:48:55.472 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:55 GMT:12345-0.1.6-Verbose renewing accesstoken<br/>
11:48:55.475 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:55 GMT:12345-0.1.6-Verbose renewToken is called for scope:https://our-tenant.onmicrosoft.com/our-scope<br/>
11:48:55.480 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:55 GMT:12345-0.1.6-Verbose Renew token Expected state: 15a22508-b5e4-421b-9d4c-c9cb2aa15ac0<br/>
11:48:55.483 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:55 GMT:12345-0.1.6-Verbose Set loading state to pending for: https://our-tenant.onmicrosoft.com/our-scope:15a22508-b5e4-421b-9d4c-c9cb2aa15ac0<br/>
11:48:55.641 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:55 GMT:12345-0.1.6-Verbose Renew token for scope: https://our-tenant.onmicrosoft.com/our-scope is in progress. Registering callback<br/>
11:48:55.820 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:55 GMT:12345-0.1.6-Verbose Renew token for scope: https://our-tenant.onmicrosoft.com/our-scope is in progress. Registering callback<br/>
11:48:55.975 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:55 GMT:12345-0.1.6-Verbose Renew token for scope: https://our-tenant.onmicrosoft.com/our-scope is in progress. Registering callback<br/>
11:48:56.147 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:56 GMT:12345-0.1.6-Verbose Renew token for scope: https://our-tenant.onmicrosoft.com/our-scope is in progress. Registering callback<br/>
11:48:56.345 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:56 GMT:12345-0.1.6-Verbose Renew token for scope: https://our-tenant.onmicrosoft.com/our-scope is in progress. Registering callback<br/>
11:48:56.815 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:56 GMT:12345-0.1.6-Verbose Renew token for scope: https://our-tenant.onmicrosoft.com/our-scope is in progress. Registering callback<br/>
11:48:56.985 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:56 GMT:12345-0.1.6-Verbose Renew token for scope: https://our-tenant.onmicrosoft.com/our-scope is in progress. Registering callback<br/>
11:48:58.604 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:58 GMT:12345-0.1.6-Verbose Window is in iframe, acquiring token silently<br/>
11:48:59.222 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:59 GMT:12345-0.1.6-Verbose Token is not in cache for scope:https://our-tenant.onmicrosoft.com/our-scope<br/>
11:48:59.424 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:59 GMT:12345-0.1.6-Verbose Token is not in cache for scope:https://our-tenant.onmicrosoft.com/our-scope<br/>
11:48:59.632 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:59 GMT:12345-0.1.6-Verbose Token is not in cache for scope:https://our-tenant.onmicrosoft.com/our-scope<br/>
11:48:59.663 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:59 GMT:12345-0.1.6-Verbose renewing accesstoken<br/>
11:48:59.665 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:59 GMT:12345-0.1.6-Verbose renewToken is called for scope:https://our-tenant.onmicrosoft.com/our-scope<br/>
11:48:59.670 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:59 GMT:12345-0.1.6-Verbose Renew token Expected state: f9c5b42c-6bea-4dce-9c66-378a70ae08dd<br/>
11:48:59.672 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:59 GMT:12345-0.1.6-Verbose Set loading state to pending for: https://our-tenant.onmicrosoft.com/our-scope:f9c5b42c-6bea-4dce-9c66-378a70ae08dd<br/>
11:48:59.843 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:59 GMT:12345-0.1.6-Verbose Token is not in cache for scope:https://our-tenant.onmicrosoft.com/our-scope<br/>
11:48:59.961 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:48:59 GMT:12345-0.1.6-Verbose Renew token for scope: https://our-tenant.onmicrosoft.com/our-scope is in progress. Registering callback<br/>
11:49:00.139 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:49:00 GMT:12345-0.1.6-Verbose Renew token for scope: https://our-tenant.onmicrosoft.com/our-scope is in progress. Registering callback<br/>
11:49:00.341 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:49:00 GMT:12345-0.1.6-Verbose Renew token for scope: https://our-tenant.onmicrosoft.com/our-scope is in progress. Registering callback<br/>
11:49:02.078 our-app.bundle.js:1 msal.js: Wed, 13 Jun 2018 15:49:02 GMT:12345-0.1.6-Verbose Window is in iframe, acquiring token silently<br/>

</details>

**Comment by MarkHerhold** [comment]
I'm seeing this as well and am worried about running out of localstorage space after the app runs for months/years.

**Comment by nehaagrawal** [comment]
@spottedmahn  We are able to reproduce this issue and we will provide a fix in the future release.

**Comment by rohitnarula7176** [comment]
@spottedmahn @MarkHerhold  I have added additional code in the dev branch to delete temporary cache entries in cases of errors like state_mismatch or invalid id_token (nonce missing). Earlier I was only running the cache clean up code in the cases of a successful response. Can you please test with the dev branch and confirm if it is resolved for you.
