### ISSUE TITLE
@azure/msal-node does not install with Node 15

### ISSUE THREAD

**Issue by wvffle** [AzureAD/microsoft-authentication-library-for-js#3270]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [x] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [ ] Angular
- [ ] React
- [ ] Other

## Error Message
```
error @azure/msal-node@1.0.1: The engine "node" is incompatible with this module. Expected version "10 || 12 || 14". Got "15.12.0"
```

## MSAL Configuration
none yet

## Reproduction steps

```sh
yarn add @azure/msal-node
```

## Expected behavior
install flawlesly

## Identity Provider

- [ ] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by SpencerGreene** [comment]
I have the same issue.  Not sure what missing information is requested but here is a very easy way to reproduce:

1. Make sure you're running node 15.x,
2. Create an empty directory ```mkdir testIssue; cd testIssue```
3. Run ```npm install @azure/msal-node```; or, install any other package that depends on it.

The rest of the fields in the template are all don't-cares; same issue will arise no matter what browser, identity provider, etc., since the package never even installs under node15.

Error is:
```
sgreene> npm install
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: @azure/msal-node@1.0.1
npm ERR! notsup Not compatible with your version of node/npm: @azure/msal-node@1.0.1
npm ERR! notsup Required: {"node":"10 || 12 || 14"}
npm ERR! notsup Actual:   {"npm":"7.6.3","node":"v15.12.0"}
```

**Comment by tnorling** [comment]
`msal-node` only officially supports even numbered stable LTS releases as documented [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-node#node-version-support). 

If using yarn you can bypass this error using the  `--ignore-engines` flag
If using npm you can bypass this error by adding `engine-strict=false` to your .npmrc file

**Comment by sameerag** [comment]
Added in [FAQs](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/faq.md) - #3290

**Comment by sameerag** [comment]
Apologies, we also support current `node` version which is 15 and I added the support. Please note though we will always stick to supporting only the `Maintenance, Active and Current` versions listed [here](https://nodejs.org/en/about/releases/) and will stop supporting any versions that are discontinued.
