### ISSUE TITLE
@azure/msal-browser PublicClientApplication - AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'

### ISSUE THREAD

**Issue by paulpopiel** [AzureAD/microsoft-authentication-library-for-js#3273]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.12.1`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [ ] Angular
- [ ] React
- [x] Other

## Description

I have written a Flutter wrapper for the MSAL.js 2.x @azure/msal-browser library.
I have followed all the guides for setting up Azure AD and the MSAL configuration for a `PublicClientApplication`.
Using the popup login method, the dialog is correctly displayed for the right tenant/client, I can enter a valid users credentials and they validate with no problem.
However, once the sign-in process completes and the popup is dismissed, I am getting the following error:

## Error Message
```
MSAL: invalid_client:7000218 - [2021-03-20 19:32:54Z]: AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
```

## MSAL Configuration

```
final auth = BrowserAuthOptions()
  ..authority = 'https://login.microsoftonline.com/$tenantId'
  ..clientId = clientId
  ..redirectUri = 'https://localhost:65411';

final configuration = Configuration()..auth = auth;
final publicClientApplication = PublicClientApplication(configuration);

...

const List<String> scopes = ['User.Read'];
final request = PopupRequest()..scopes = scopes;
final response = await widget.publicClientApplication.loginPopup(request);
```
## Azure AD Configuration

<img width="1025" alt="Screen Shot 2021-03-21 at 3 53 39 am" src="https://user-images.githubusercontent.com/8855763/111883912-1e1cd480-89f9-11eb-9071-2bc37d97dfa4.png">

<img width="740" alt="Screen Shot 2021-03-21 at 3 54 53 am" src="https://user-images.githubusercontent.com/8855763/111883928-34c32b80-89f9-11eb-9b7e-5c02e6e7be2f.png">

<img width="712" alt="Screen Shot 2021-03-21 at 3 55 11 am" src="https://user-images.githubusercontent.com/8855763/111883938-3e4c9380-89f9-11eb-992a-046c7f0b9ebe.png">

<img width="1007" alt="Screen Shot 2021-03-21 at 3 55 38 am" src="https://user-images.githubusercontent.com/8855763/111883949-4efd0980-89f9-11eb-94ca-318965f74474.png">

## Reproduction steps

see above

## Expected behavior

I have spent hours looking through stackoverflow and git issues. The key thing missing in most cases, and which I subsequently added was the "Allow public client flows" setting in AAD. However, even after setting this to true the error is still persisting.

Any assistance on the matter would be greatly appreciated. We already have over half a dozen Flutter applications, being used by hundreds of key users, across our enterprise. We have used an MSAL.js 1.x wrapper to date but have been facing too many third-party cookie policy issues on browsers. 
We need a solution otherwise we may need to consider alternatives.

Any assistance, ideas, suggestions, etc would be greatly appreciated. Thanks!

## Identity Provider

- [x] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version: n/a

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by paulpopiel** [comment]
Ok, some progress and new error message now.

This is what I get for staring at a screen for over 12hrs straight.

Accidentally had the wrong Uri scheme for the localhost, updated it from https to http in both the MSAL and AAD settings.

Now getting the following error:
```
MSAL: invalid_request:9002326 - [2021-03-20 20:56:07Z]: AADSTS9002326: Cross-origin token redemption is permitted only for the 'Single-Page Application' client-type.
```

**Comment by derisen** [comment]
@paulpopiel I'm not well versed in Flutter, but if your app is running on a browser with a dedicated redirect URI than you shouldn't check the "Allow public client flows", which are meant for native mobile & desktop apps usually.

The last error you got (AADSTS9002326) is because you have added both "Single-page application" and "Web" platforms in the **Authentication** blade with the same redirect URI. Either have them different redirect URIs or create a separate app registration for the web platform.

**Comment by paulpopiel** [comment]
Hi @derisen , regarding "Allow public client flows", if I turn it off/false then I definitely go back to getting the error:
```
AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
```

Your point on AADSTS9002326 however - you are correct we do have both Web and SPA redirect URIs setup. However they are not the same. Would this still cause issues?

**Comment by paulpopiel** [comment]
NOTE: I dont really want to mess with the existing web redirects at this stage as this is a pre-existing app registration.
I have created a fresh app registration with just SPA redirects, however I get blocked by missing admin consent on the API permissions, so won't be able to proceed down that path until I get one of our admins to grant that.

**Comment by derisen** [comment]
@paulpopiel can you check [this guidance](https://docs.microsoft.com/en-us/azure/active-directory/develop/reply-url#localhost-exceptions) on URI differentiation? Its talks about localhost but should give insight nonetheless.

**Comment by derisen** [comment]
And I think AADSTS7000218 is because Azure AD thinks your app is a web app and web apps have client credentials (assertion or secret)

**Comment by paulpopiel** [comment]
Sorry, I should have elaborated - it is a web app, i.e. Flutter Web.

On the other hand thank you so much for that URI guidance link.

> Due to ephemeral port ranges often required by native applications, the port component (for example, :5001 or :443) is ignored for the purposes of matching a redirect URI. 

This was the issue! removed all localhost:XXXX Uris from the Web platform in AAD and everything now works!
Much much appreciated!

**Comment by derisen** [comment]
Cheers!

**Comment by tnorling** [comment]
Closing as resolved.
