### ISSUE TITLE
When can PublicClientApplication.getAllAccounts() return more than one account?

### ISSUE THREAD

**Issue by k-mehta** [AzureAD/microsoft-authentication-library-for-js#3275]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.12.1`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description
I can't find any documentation which explains when PublicClientApplicaiton.getAllAccounts() would return multiple accounts.

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by svrooij** [comment]
It's possible to login with one account and then call `.loginPopup(...)` or `loginRedirect(...)` on the `msalObject`. That way it's possible to have multiple-accounts "logged-in" at the same time. Your application will (by default) only use the first account for all it's token stuff, but you can set change that by calling `setActiveAccount(accounts[1])`.

**Comment by k-mehta** [comment]
Thanks. How does this work with SSO? If the user logged in using different accounts on two other websites before coming to mine, would I get two accounts? Are they sorted in any order?

**Comment by svrooij** [comment]
You will not receive two accounts with sso. Only one and I'm not really sure, my guess that if you have multiple accounts logged in (and your application doesn't provide a `domainhint`) the user is presented with a screen to choose the correct account. After that (first loging succeeded) your application can choose to call `.login...(...)` for the second time. If the second time you add the `prompt` parameter with the value `select_account` the user is again prompted with a screen to choose an account.

**Comment by tnorling** [comment]
Thanks for raising this. We've added an item to our backlog to improve the documentation around this. Most of what has been discussed here is accurate but I'd like to clear a few things up:

> Your application will (by default) only use the first account for all it's token stuff, but you can set change that by calling setActiveAccount(accounts[1]).

This is not accurate. MSAL does not make assumptions about what account to use. It will either use the account passed in to the API or the active account that was previously set by calling `setActiveAccount`. In other words, the onus is always on the application to specify which account to use.

> If the user logged in using different accounts on two other websites before coming to mine, would I get two accounts? Are they sorted in any order?

Each call to `loginPopup` or `loginRedirect` will always result in exactly one account. `getAllAccounts` is not guaranteed to be sorted in any order, nor is it guaranteed to return the same order across calls.
