### ISSUE TITLE
HTTP 500 Error using function createAuthenticationContext method. 

### ISSUE THREAD

**Issue by shsuman** [AzureAD/microsoft-authentication-library-for-js#3279]
We are Azure Machine Learning - Remote extension in VSCode team. We are using your package to acquire a bearer token from refresh token which is provided to us by another extension. Specifically, we are using createAuthenticationContext(authority: string, validateAuthority?: boolean) method to create an auth context. We had set the validateAuthority parameter to true until one of our customers today got this error:

![image](https://user-images.githubusercontent.com/44413557/110148415-ca0fce80-7e02-11eb-8747-e6a21589c2d6.png)

The issue resolved after we set the validateAuthority to false
Now the question that we want to ask you is: **Why is the authority not recognized in their particular case and how does disabling impact the user from a security standpoint?**

Regards,
Shantnu Suman on behalf of Azure ML Extension team

**Comment by shsuman** [comment]
This can be closed now we have decided to upgrade to the msal-node library. We will open another issue if we have problems with that as well.

**Comment by sameerag** [comment]
Thanks @shsuman. Closing this issue.
