### ISSUE TITLE
Question about PWA when user is offline

### ISSUE THREAD

**Issue by jakehockey10** [AzureAD/microsoft-authentication-library-for-js#3283]
## Library

- [x] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

Hello,

We are hoping to convert our angular application into a PWA so that we can offer some of the application up to a user that loses internet connection. The more I read about how authentication works, the more my guess is confirmed that without internet, you really can't trust who the user is in the application.

But I'd like to ask the question: will this library let me have certain feature modules that don't require authentication to be able to be used longer than the token expiration normally allows them to? In other words, it seems like this library automatically tries to refresh tokens behind the scenes, and I'd imagine those would fail without an internet connection. Do those token refreshes only happen when a resource is requested that is in the protected resource map? Or will the token refresh happen on its own when the token expires?

If we prevent making http calls to resources that are protected, can the user, even if their token is expired, still navigate the rest of the site as long as they don't try to make calls to protected resources?

I'm trying to figure out if this is even going to be possible while using this library, and I'm looking through the source code. I feel like it'll be possible, but I was hoping to get a response from one of the maintainers in regards to their opinion on how to go about this.

## Source

- [ ] Internal (Microsoft)
- [x] Customer request

**Comment by jasonnutter** [comment]
> In other words, it seems like this library automatically tries to refresh tokens behind the scenes, and I'd imagine those would fail without an internet connection.

Correct, if an app invokes `acquireTokenSilent` and there are no valid tokens in the cache, MSAL will attempt to silently acquire a new token.

> Do those token refreshes only happen when a resource is requested that is in the protected resource map? Or will the token refresh happen on its own when the token expires?

For MSAL Angular when using the interceptor, this is correct (assuming you aren't making any manual calls to `acquireTokenSilent`. Tokens will only be renewed as a result of invoking `acquireTokenSilent`. 

> If we prevent making http calls to resources that are protected, can the user, even if their token is expired, still navigate the rest of the site as long as they don't try to make calls to protected resources?

In MSAL Angular v1, the MSAL Guard [will make a call to `acquireTokenSilent`](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/msal-angular-v1/lib/msal-angular/src/msal-guard.service.ts#L98) to retrieve an ID token when navigating to a protected route. So if the ID token has expired, this could result a network request. MSAL Angular v2 does not do this.

I'd be interested in any learnings you have for offline PWAs with our libraries, as this is not an area we have looked into.

**Comment by jakehockey10** [comment]
@jasonnutter thanks for the response!  I've looked and I can't find any use of `acquireTokenSilent` that we call explicitly.  When you say that MSAL Angular v2 does not make a network request when the ID token has expired, what does it do instead?

I'm just trying to decide whether it is worth doing my testing while focusing on v1 or v2.  I know v2 has been in beta for a bit now, would you suggest I do my testing in v2 with the assumption that we'll be moving to that shortly anyway?  Or would it make sense to stay focused on v1 at this time?

**Comment by jakehockey10** [comment]
I'm also trying to stay up to date with the latest version of angular in general.  Is there any danger in forcing my update from 11.0.0 to 11.2.6 when I'm using v1 of this library?  I know that 9 is the latest officially supported version of Angular, but is this reason to try moving to v2 of this library while in beta?  Our app is in production right now, so I'm a little lost on which way to go on this.

**Comment by jasonnutter** [comment]
> When you say that MSAL Angular v2 does not make a network request when the ID token has expired, what does it do instead?

Sorry, to be clear, MSAL Angular v1 invokes `acquireTokenSilent` with the client id scope in the MSAL Guard, which is how an ID token is acquired in MSAL.js v1.

The MSAL Guard for MSAL Angular v2 only looks at the cached accounts, and does not call acquireTokenSilent (and thus will not potentially make a network request).

And yes, we would recommend moving to MSAL Angular v2, especially if you are upgrading your version of Angular. We'll have more details on GA soon.

**Comment by jakehockey10** [comment]
Thanks for the reply and clarification and all the hard work. I'll give v2 a shot and let you know how it goes.

**Comment by jakehockey10** [comment]
I'm having a bit of trouble converting to the newest version (v1 -> v2).  I'm getting an error I've never gotten before: ERROR ServerError: unauthorized_client: AADB2C90058: The provided application is not configured to allow public clients.

In order to see this error, I had to add a route for {path: 'error', redirectTo: '' } in my routes in order for this error to appear long enough to read it.

The error seems odd as with v1, this is not an issue.  I'm using the same clientId and same authority urls, I haven't changed anything in Azure B2C.

Any idea what could be going on here?

**Comment by jasonnutter** [comment]
@jakehockey10 Apologies for the delay in responding. Can you share how you have your application configured in teh Azure Portal? Are you redirect URIs set to SPA? Do you have the implicit flow boxes checked or not? Is "Allow public client flows" enabled or disabled?

**Comment by jakehockey10** [comment]
@jasonnutter Thanks for the response and sorry for my own delay in responding.  I haven't been able to focus on this lately, so I was hoping that I could get back to you soon still.  We are still trying to find the right time to make the switch to the new msal-angular v2 relative to our other priorities (PWA has fallen in priority, but I would assume v2 would still be a good thing to move to).  What is the latest estimate for when v2 will be out of beta from your perspective?

**Comment by jasonnutter** [comment]
@jakehockey10 No worries. MSAL Angular v2 is currently scheduled to GA in May.

**Comment by jakehockey10** [comment]
Cool thanks for the update. I'll try to find the time to attempt the migration on a new branch in preparation
