### ISSUE TITLE
single sign out frma a SPA and ,net app

### ISSUE THREAD

**Issue by maacaro** [AzureAD/microsoft-authentication-library-for-js#3284]
## Library

- [x] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

is there a way that I can sign out on a SPA and also from a .net app? 
this is because we are migrating from a web app from .net to SPA with react and we got our login page on .net yet but the app is in react. 
in our react app there is a logout button we are using MSAL.js, we are  able to logout from our React app but when we go back to the .net app that app the user is still logged in

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by tnorling** [comment]
@maacaro You can register a "Front Channel Logout Url" on each of your app registrations you would like to be signed out. When one app calls logout, AAD will check which applications that user is signed in to and open an iframe to each corresponding front channel logout url. You'll need to ensure that url that you register calls the relevant logout APIs to clear local cache.

**Comment by jasonnutter** [comment]
Closing, let us know if you have further questions.
