### ISSUE TITLE
Invalid Token: Error 431 -  Request Header Fields Too Large

### ISSUE THREAD

**Issue by francesco-clementi-92** [AzureAD/microsoft-authentication-library-for-js#3291]
## Library
-  `@azure/msal-browser@2.12.1`
-  `@azure/msal-react@1.0.0-beta.0`

## Framework
- [x] React

## Description
The login process seems to working, but each request made to the backend for one of our user is getting error 431 Request Header Fields Too Large.

## MSAL Configuration
const config = {
    auth: {
        authority:
          "https://login.microsoftonline.com/yyyyyyyyyyyyyyyyyyyy/",
        clientId: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        redirectUri: env.REDIRECT_URI,
        audience: 'xxxxxxxxxxxxxxxxxxxxxxx',
    },
  cache: {
    cacheLocation: "sessionStorage",
    storeAuthStateInCookie: false
  },
  system: {
      loggerOptions: {
          loggerCallback: (level, message, containsPii) => {
              if (containsPii) {
                  return;
              }
              console.log(message)
          },
          piiLoggingEnabled: false
      },
      windowHashTimeout: 60000,
      iframeHashTimeout: 6000,
      loadFrameTimeout: 0
  }
};

## Identity Provider
- [x] Azure AD

## Browsers/Environment
- [x] Chrome
- [x] Safari

The application is deployed on Google App Engine which has a request header limit of 15 kb

**Comment by sameerag** [comment]
@francesco-clementi-92 Can you please give us more details here? If you can send us the header that is causing this issue, we can try root cause it.

**Comment by francesco-clementi-92** [comment]
I found the problem, the token is not correct (I omitted part of the token for security reason, ma I added the numbers of characters removed):

```
Request Headers
	

		
		:authority:
		
		xxxx.ew.r.appspot.com
		
		
		:method:
		
		GET
		
		
		:path:
		
		/api/v1/config
		
		
		:scheme:
		
		https
		
		
		accept:
		
		application/json, text/plain, */*
		
		
		accept-encoding:
		
		gzip, deflate, br
		
		
		accept-language:
		
		en-US,en;q=0.9,it;q=0.8
		
		
		 
		authorization:
		
		Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyJ9.eyJhdWQiOiI5ZGJlOWNmNS0yMGE2LTRmMGQtOTA3ZC1mZmQwZjliZjliYjIiLCJpc3MiOiJodHRwczovL2xvZ2luLm1pY3Jvc29mdG9ubGluZS5jb20vYmIxYTYzZWItZWIwOS00NzFhLWEwMDUtMzdiMDc3OTJhNWI1L3YyLjAiLCJpYXQiOjE2MTY2MDUyNjMsIm5iZiI6MTYxNjYwNTI2MywiZXhwIjoxNjE
**[OTHER 6620 CHARACTERS]**
ImJiMWE2M2ViLWViMDktNDcxYS1hMDA1LTM3YjA3NzkyYTViNSIsInV0aSI6IkpnTndYakRVSTAyRy1sVUM5VXByQUEiLCJ2ZXIiOiIyLjAiLCJ3aWRzIjpbImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdfQ.R6yZnV_p2m7ihDw95eYgcVvZ0v2bm5P1URyTpglccbe23E0a_MRLkeiWtHZjV0_DzpVyP8KgT8xyzQlPgIuSAj8zCwkcKb71CO0MlTAr4HWHoCvhPOqLhtmfdNq7Ffn7aNLyTRek-PDn1-ctCMx5D3f7SqSrLlhVJPzq7JvwNwRioQerNRikpqfeKEijkrPmHspbNShrG-6yxWfO0CLx07ijJdiKaFrrt4Z8UQK5EcBd2Q1Cu96BfjhdaF6v3EQSAlSPV7ShOAYrr4fdEIEkN4YfMy4pnhPRILEnOToxBuPnsIso-baDeJL8eqzleoENglebl-U3h9JvmI1HJ4kQTA
		
		
		origin:
		
		https://XXXX.com
		
		
		referer:
		
		https://XXXXX.com/
		
		
		sec-ch-ua:
		
		"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"
		
		
		sec-ch-ua-mobile:
		
		?0
		
		
		sec-fetch-dest:
		
		empty
		
		
		sec-fetch-mode:
		
		cors
		
		
		sec-fetch-site:
		
		cross-site
		
		
		user-agent:
		
		Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
```
At the moment I can't verify if is msal.acquireTokenSilent that is returning this token, but I'm using axios and this is the part on my code that set the token:
`const setAuthToken = token => {
  axios.defaults.params = {}
  axios.defaults.headers["authorization"] = `Bearer ${token}`;
};`

**Comment by francesco-clementi-92** [comment]
The path of characters in the token is not repeated, so I assume is acquireTokenSilent that is returning this huge and invalid token

**Comment by francesco-clementi-92** [comment]
This my code:
App.js:
`import 'react-app-polyfill/stable'
import React from "react"
import ReactDOM from "react-dom"
import { unregister } from "./registerServiceWorker"
import { HashRouter } from "react-router-dom"
import Main from "./Pages/Index"
import Unauthorized from "./Pages/Index/unauthorized"
import ServerError from "./Pages/Index/serverError"
import configureStore from "./config/configureStore"
import { AuthProvider, useAuth, PCA } from './Context/auth';
import { AbilityContext } from './Context/ability';
import { Provider } from "react-redux"
import axios from "axios"
import { MsalAuthenticationTemplate, MsalProvider,useAccount , useMsal   } from "@azure/msal-react";
import createAuthRefreshInterceptor from 'axios-auth-refresh';
const store = configureStore()

const setAuthToken = token => {
  axios.defaults.params = {}
  axios.defaults.headers["authorization"] = `Bearer ${token}`;
};

const ErrorComponent = ({error}) => {
  console.log(JSON.stringify(error.errorCode || error))
  return <h5>An error occurred during authentication</h5>;
}

const InProgressComponent = ({inProgress}) => {
  return <LoadPanel visible={true} indicatorSrc={`data:image/svg+xml;utf8,${require("./assets/rolling.svg")}`}/>;
}

function AppContent({userEmail, Component}) {
  const { user, loading, error, config } = useAuth(userEmail);

  if(error){
    return <ServerError/>
  }

  if (user) {
    return <AbilityContext.Provider value={userData.capabilities}>
                <Component/>
              </AbilityContext.Provider>
  }else{
	return <div></div>
  }
}

const App = ({Component}) => {
  const [apiData, setApiData] = React.useState(null);
  const { instance, accounts } = useMsal();
  const account = useAccount(accounts[0] || {});

  createAuthRefreshInterceptor(axios, failedRequest => {
    console.log("AUTH REFRESH INTERCEPTOR")
    return PCA
      .acquireTokenSilent({
        account: JSON.parse(sessionStorage.getItem('account')),
        scopes: [`openid`],
      })
      .then(response => {
        failedRequest.response.config.headers[
          "authorization"
        ] = `Bearer ${response.accessToken}`;
        setAuthToken(response.accessToken)
      })
      .catch(e => {
        console.log("Error while acquireTokenSilent", e);
        sessionStorage.clear();
      })
      .finally(() => Promise.resolve());
  },{statusCodes: [401,403], pauseInstanceWhileRefreshing: true});
  
  React.useEffect(()=>{
    if(account){
      sessionStorage.setItem('account', JSON.stringify(account))
      instance.acquireTokenSilent({
        scopes: ['openid'],
        account
        ,forceRefresh: true
      }).then((response) => {
        setAuthToken(response.accessToken)
        setApiData(response);
      }).catch(err => {

        if (err) {
          instance.acquireTokenRedirect({
            scopes: ['openid'],
            account,
            forceRefresh: true
          }).then((response) => {
            setAuthToken(response.idToken)
            setApiData(response);
          })
        };
        console.log("ERRORE ACQUIRE TOKEN", err)
      })
    }
  },[account])

  if(apiData){
    return (
    <AuthProvider>
      <AppContent Component={Component}/>
    </AuthProvider>)
  }

  return <InProgressComponent/>
}

const renderApp = (Component) => {
  ReactDOM.render(
    <React.Fragment>
      <MsalProvider instance={PCA}>
        <Provider store={store}>
          <HashRouter>
            <MsalAuthenticationTemplate 
              interactionType="redirect" 
              errorComponent={ErrorComponent} 
              loadingComponent={InProgressComponent}
            >
              <App Component={Component}/>
            </MsalAuthenticationTemplate>
          </HashRouter>
        </Provider>
      </MsalProvider>
    </React.Fragment>,
  document.getElementById('root')
  )
}

renderApp(Main)

if (module.hot) {
  module.hot.accept("./Pages/Main/Profile", () => {
    const NextApp = require("./Pages/Main/Profile").default
    renderApp(NextApp)
  })
}
unregister()

`


Auth.js:
`import React, { useState, useEffect, createContext, useContext } from 'react';
import { PublicClientApplication } from "@azure/msal-browser";
import env from "react-dotenv";
import axios from "axios";

// Msal Configurations
const config = {
    auth: {
        authority:
          "https://login.microsoftonline.com/XXXXXXXXXXXXXXXXXX/",
        clientId: "XXXXXXXXXXXXXXXXXXXXXXXXXX",
        redirectUri: env.REDIRECT_URI,
        audience: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    },
  cache: {
    cacheLocation: "sessionStorage",
    storeAuthStateInCookie: false
  },
  system: {
      loggerOptions: {
          loggerCallback: (level, message, containsPii) => {
              if (containsPii) {
                  return;
              }
              console.log(message)
          },
          piiLoggingEnabled: false
      },
      windowHashTimeout: 60000,
      iframeHashTimeout: 6000,
      loadFrameTimeout: 0
  }
};


function AuthProvider(props) {
  const [user, setUser] = useState();
  const [config, setConfig] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(()=>{
    (async ()=>{
      try{
        //set user data
        setLoading(false);
      }catch(e){
        console.log(e)
        setError(e.response?.status || 500)
        setLoading(false);
      }
    })()

  },[])

  return (
    <AuthContext.Provider value={{ user, loading, error, config }} {...props} />
  );
}

const AuthContext = createContext({});
const useAuth = () => useContext(AuthContext);
const PCA = new PublicClientApplication(config);
export { AuthProvider, useAuth, PCA }
`

**Comment by francesco-clementi-92** [comment]
I confirm that the issue is only with one of our customer and it seems that he recently changed the password of the account.

**Comment by tnorling** [comment]
@francesco-clementi-92 Can you look at the network trace and determine if the correct token is being returned? You can email me the network trace if you don't know what to look for.

Generally speaking we can't offer support on issues with external APIs but if you determine MSAL is returning an incorrect token that's something we can take a look at.

**Comment by francesco-clementi-92** [comment]
@tnorling as you can see, the token that I posted is not a valid token and has too many characters which are causing error 431. 
Can't post the network trace at the moment.

**Comment by tnorling** [comment]
@francesco-clementi-92 Without a network trace or a reproduction we cannot determine if this is an issue with the service, with the library or something else.

**Comment by francesco-clementi-92** [comment]
@tnorling is there any possibility that acquireTokenSilent is generating a completely wrong and bad formatted token?

**Comment by tnorling** [comment]
@francesco-clementi-92 `acquireTokenSilent` does not generate tokens. It requests tokens from the AAD service and returns whatever AAD sends back. This is why network traces would be helpful. If we can determine AAD is sending back a bad token I can take that to the server team and ask why. If AAD is sending back a valid token then we need to understand how and why it gets into the bad state.

**Comment by francesco-clementi-92** [comment]
Hi @tnorling I have the network trace. The token seems to be valid, but being too large (almost 7000 characters) it's not accepted from our backend with a max limit size of 15 kb. The problem is the number of security groups of our customer.  
Is there a way to reduce the token limit?

**Comment by francesco-clementi-92** [comment]
Resolved by configuring `"groupMembershipClaims":  null` on the azure application manifest
