### ISSUE TITLE
/#code becomes anchor after redirect

### ISSUE THREAD

**Issue by Marcel0024** [AzureAD/microsoft-authentication-library-for-js#3293]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [x] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

I have a SPA with msal guards on all routes.
After successfully login the user gets redirected to the app, but the 'code' stays visible on the url.

![image](https://user-images.githubusercontent.com/14852157/112353259-e00b0380-8ccb-11eb-841d-841a095c04eb.png)

In the routing root i have:  

```useHash: false```

How can i make sure that ``'#code=abc...``' gets removed after the redirect?
Most example are using hash, so i couldn't find anything in the samples or docs.

## Source

- [ ] Internal (Microsoft)
- [x] Customer request

**Comment by jo-arroyo** [comment]
@Marcel0024 Is the `MsalGuard` set on the home route too? Do you have the `MsalRedirectComponent` bootstrapped? 

If your home page has the MsalGuard, when redirecting back to your home page after signing in, unless you explicitly call `handleRedirectObservable`, the returning redirect is not being handled. We recommend having the `MsalRedirectComponent` bootstrapped in your app to handle these redirects, even if your routes are protected by the MsalGuard. Please see our [redirect doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/redirects.md) for more details. 

I will also link a PR we have up that updates one of our samples to not use the HashLocationStrategy, with updated documentation, which you can refer to also.

**Comment by Marcel0024** [comment]
@jo-arroyo Thanks for the reply!

I added this for further debugging:

`msalBroadcast.msalSubject$.subscribe((log) => console.log(log));`

the redirect does seem to get hit:

![image](https://user-images.githubusercontent.com/14852157/112393296-23c93180-8cfb-11eb-8c03-b9056ae02578.png)

I added the `MsalRedirectComponent` and the problem still persists.

So `MsalGuard` is definitely set on home, i get logged in and able to get the user data. 

Other things i do differently to your sample, is everything from Msal has it's own module and feature module's has their own routing module with msal guard.

I'll try to reproduce it tomorrow on a clean project.

**Comment by jo-arroyo** [comment]
@Marcel0024 We have just released a new version of `@azure/msal-angular` with changes that may help. Please upgrade with `npm install @azure/msal-angular@latest and @azure/msal-browser@latest`, and let me know if you are still experiencing issues.

**Comment by Marcel0024** [comment]
Managed to reproduce this on a new project:

https://github.com/Marcel0024/MsalTest

Change the client id and url on https://github.com/Marcel0024/MsalTest/blob/master/src/core/user/user.module.ts#L12
And add the proper callback url on Azure AD

after starting the project you get immediately redirect to MS -> log in -> redirect back to app ->  Successfully logged in -> `/#code=123...` in the url

**Comment by matteocusinato** [comment]
Same problem @Marcel0024 , /#code=123... in the url after login. @azure/msal-angular

**Comment by Marcel0024** [comment]
Hi @jo-arroyo,

Any news on this?

Was the sample sufficient? 
Were you able to reproduce? 
Did i do something wrong?
Do you require more detailed steps to reproduce?

**Comment by jasonnutter** [comment]
@Marcel0024 Apologies for the delayed response. I can reproduce the behavior you describe. While I investigate, please follow our recommended best practice using a dedicated redirect route that is not protected by the MSAL Guard, which should mitigate the issue: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/FAQ.md#pathlocationstrategy

**Comment by Marcel0024** [comment]
Thanks @jasonnutter i must have missed that in the docs. It does mitigate it! Is this the correct way of using it or is this a workaround?

**Comment by jasonnutter** [comment]
@Marcel0024 Yes, this is our recommended best practice.

**Comment by jasonnutter** [comment]
We have root caused this issued, and should have a fix in the next version of MSAL Angular v2.

**Comment by matteocusinato** [comment]
Hi @jasonnutter , I got to test the new version, in fact the url is now clean after the redirect, but only if you have the Guard canActivate. My route for example is canLoad and the problem still exists. Thank you!

**Comment by jasonnutter** [comment]
> Hi @jasonnutter , I got to test the new version, in fact the url is now clean after the redirect, but only if you have the Guard canActivate. My route for example is canLoad and the problem still exists. Thank you!

This is a known limitation (path routing, redirect uri set to page using MSAL Guard via canLoad) that is not supported at this time. Please use a dedicated redirect URI that either does not use the MSAL Guard or uses canActivite.
