### ISSUE TITLE
Uncaught (in promise): BrowserAuthError: interaction_in_progress:

### ISSUE THREAD

**Issue by RomaRathi** [AzureAD/microsoft-authentication-library-for-js#3301]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [x] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Source

- [x] Internal (Microsoft)
- [ ] Customer request

**Comment by RomaRathi** [comment]
Navigated to http://localhost:3000/
jquery-migrate-3.0.0.min.js:2 JQMIGRATE: Migrate is installed, version 3.0.0
[Violation] Forced reflow while executing JavaScript took 42ms
app.module.ts:82 [Thu, 25 Mar 2021 12:52:28 GMT] :  : @azure/msal-browser@2.12.1 : Info - Emitting event: msal:loginStart
error-page.service.ts:30 Error: Uncaught (in promise): BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.  For more visit: aka.ms/msaljs/browser-errors.
BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.  For more visit: aka.ms/msaljs/browser-errors.
    at BrowserAuthError.AuthError [as constructor] (index.es.js:524)
    at new BrowserAuthError (index.es.js:7129)
    at Function.push.u8tD.BrowserAuthError.createInteractionInProgressError (index.es.js:7190)
    at PublicClientApplication.push.u8tD.ClientApplication.preflightInteractiveRequest (index.es.js:10817)
    at PublicClientApplication.<anonymous> (index.es.js:10178)
    at step (index.es.js:75)
    at Object.next (index.es.js:56)
    at index.es.js:49
    at new ZoneAwarePromise (zone-evergreen.js:960)
    at __awaiter (index.es.js:45)
    at resolvePromise (zone-evergreen.js:798)
    at resolvePromise (zone-evergreen.js:750)
    at zone-evergreen.js:705
    at step (index.es.js:48)
    at index.es.js:49
    at new ZoneAwarePromise (zone-evergreen.js:960)
    at __awaiter (index.es.js:45)
    at PublicClientApplication.push.u8tD.PublicClientApplication.loginRedirect (index.es.js:11083)
    at MsalService.loginRedirect (azure-msal-angular.js:55)
    at AppService.<anonymous> (app.service.ts:75)
core.js:27686 Navigation triggered outside Angular zone, did you forget to call 'ngZone.run()'?
warn @ core.js:27686
navigateByUrl @ router.js:4306
goToErrorPage @ error-page.service.ts:143
sendException @ error-page.service.ts:47
handleError @ exception-handler.ts:20
next @ core.js:28881
schedulerFn @ core.js:25646
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
next @ Subject.js:39
emit @ core.js:25636
(anonymous) @ core.js:28304
invoke @ zone-evergreen.js:364
run @ zone-evergreen.js:123
runOutsideAngular @ core.js:28209
onHandleError @ core.js:28304
handleError @ zone-evergreen.js:368
runGuarded @ zone-evergreen.js:136
api.microtaskDrainDone @ zone-evergreen.js:670
drainMicroTaskQueue @ zone-evergreen.js:576
Promise.then (async)
scheduleMicroTask @ zone-evergreen.js:552
scheduleTask @ zone-evergreen.js:388
scheduleTask @ zone-evergreen.js:210
scheduleMicroTask @ zone-evergreen.js:230
scheduleResolveOrReject @ zone-evergreen.js:847
then @ zone-evergreen.js:979
bootstrapModule @ core.js:28923
boVJ @ main.ts:11
__webpack_require__ @ bootstrap:79
0 @ xbrl-taxonomies-save.ts:86
__webpack_require__ @ bootstrap:79
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ vendor.js?b=0:1
error-page.service.ts:40 Exception sent to the server.

**Comment by RomaRathi** [comment]
Where exactly to call handleRedirectPromise() before login ?

**Comment by tnorling** [comment]
@RomaRathi Please see our [error doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/errors.md#interaction_in_progress) on this error. You can also check out our [samples](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples) for more end-to-end guidance.

**Comment by RomaRathi** [comment]
Thanks for the help. I have solved the issue by calling the handleRedirectPromise method on the correct place before loginRedirect.
