### ISSUE TITLE
msal-browser with Electron/React

### ISSUE THREAD

**Issue by Xecuter34** [AzureAD/microsoft-authentication-library-for-js#3305]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

So I am trying to currently get this working with Electron and have followed the following example on here by getting it listening to a custom protocol and it works... kind of. I can call PublicClientApplication.acquireTokenRedirect() and get a token fine but then I need to pass it to another page with hash, as I am using react-router-dom, I can't actually do this. Because of this I pass it as a search parameter and then pass it manually to PublicClientApplication.handleRedirectProimise().

Once I do this, it fails on the handleRedirectPromise() with the following message: "ClientAuthError: state_not_found: State not found:  Server State"

Anyoen have any ideas what might be causing this?

This is the following issue I have been going from: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/324

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by tnorling** [comment]
@Xecuter34 `msal-browser` is for browser based SPA apps and does not support Electron. To authenticate an Electron app you should use `msal-node` instead and can find our Electron sample app [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/ElectronTestApp)
