### ISSUE TITLE
msal-browser-samples/TestingSample failing testing sample

### ISSUE THREAD

**Issue by HannahZhuSWE** [AzureAD/microsoft-authentication-library-for-js#3308]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [X] `@azure/msal-node@1.0.1`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [ ] Angular
- [X] React
- [ ] Other

## Description
After following the instructions to set up the test, running npm test still results in the testing sample failing. I've tried going through the app (using npm start) and everything seems to be working fine however when I run npm test only this page shows up before the test fails.
![image](https://user-images.githubusercontent.com/76960450/112549556-5ffca080-8d94-11eb-98bc-9edb8c3e2b51.png)
When I run through the test line by line it looks like it never returns from calling 
```await pca.acquireTokenByUsernamePassword(usernamePasswordRequest);``` (line 38 in browser-test.spec.ts) because it skips the last two lines in beforeAll()

## Error Message

Tests › Tests sign-out button is displayed when user is signed-in

    expect(received).toBeGreaterThan(expected)

    Expected: > 0
    Received:   0

      46 |     let signInButton = await page.$x("//button[contains(., 'Sign In')]");
      47 |     let signOutButton = await page.$x("//button[contains(., 'Sign Out')]");
    > 48 |     expect(signInButton.length).toBeGreaterThan(0);
         |                                 ^
      49 |     expect(signOutButton.length).toEqual(0);
      50 |     await setSessionStorage(tokenCache);
      51 |     signInButton = await page.$x("//button[contains(., 'Sign In')]");

      at test/browser-test.spec.ts:48:33

## MSAL Configuration
Note clientId and authority values were omitted 
```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
const msalConfig = {
    auth: {
        clientId: "some-string",
        authority:
            "https://login.microsoftonline.com/another-string/",
    },
    cache: {
        cacheLocation: "sessionStorage", // This configures where your cache will be stored
        storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
    },
    system: {
        loggerOptions: {
            loggerCallback: (level, message, containsPii) => {
                if (containsPii) {
                    return;
                }
                switch (level) {
                    case msal.LogLevel.Error:
                        console.error(message);
                        return;
                    case msal.LogLevel.Info:
                        console.info(message);
                        return;
                    case msal.LogLevel.Verbose:
                        console.debug(message);
                        return;
                    case msal.LogLevel.Warning:
                        console.warn(message);
                        return;
                }
            },
        },
    },
};
```

## Reproduction steps
-clone the repo and run npm install
-switch out config values in authConfig and in the test for your own client's values 
-switch out username and password for your own
-run npm test 

```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Expected behavior
Test should pass
## Identity Provider

- [X] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [X] Internal (Microsoft)
- [ ] Customer request

**Comment by diberry** [comment]
Watching this...

**Comment by tnorling** [comment]
@HannahZhuSWE Is there any error thrown by `acquireTokenByUsernamePassword`? Can you check your app registration and make sure "Allow Public Client Flows" is set to "Yes"?

**Comment by HannahZhuSWE** [comment]
I changed Allow Public Client Flows to yes but it still isn't working. I missed this earlier but the app is throwing the following error:
`InteractionRequiredAuthError: invalid_grant: AADSTS50079: Due to a configuration change made by your administrator, or because you moved to a new location, you must enroll in multi-factor authentication to access '00000003-0000-0000-c000-000000000000'`

**Comment by tnorling** [comment]
@HannahZhuSWE The UsernamePassword flow will not work on accounts that require MFA. You can find a more detailed list of requirements for using this flow [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth-ropc)

**Comment by HannahZhuSWE** [comment]
Is there a way to remove the requirement for 2FA?

**Comment by tnorling** [comment]
@HannahZhuSWE It's up to the administrator of the tenant which your account belongs to. If you have your own tenant you can try creating a new user, but I'm unfortunately not familiar with the specific configurations

**Comment by HannahZhuSWE** [comment]
Oh ok I see, thank you!
