### ISSUE TITLE
fromCache is incorrect when using .default scope

### ISSUE THREAD

**Issue by k290** [AzureAD/microsoft-authentication-library-for-js#3311]
## Library

- [ x]`@azure/msal-browser@2.13.0`

## Framework

- [ x] Angular 8

## Description

When using authScopes as follows:
```
[
         [
        "https://graph.microsoft.com/v1.0/me",
        [ "User.Read", "User.ReadBasic.All" ]
      ],
      [
        "api/**",
        [ "api://<some-guid>/Api.Access" ]
      ]
    ]
```
After an sign-in redirect, when control returns to our application's javascript, fromCache correctly returns false.

However, for onBehalfFlow one has to alter the above scope to be as follows (remove the graph scopes, and change Api.Access to .default):

```
  [
        "api/**",
        [ "api://<some-guid>/.default" ]
      ]
```

However, msal incorrectly returns fromCache as true after the sign-in redirect has returned with a successful authentication.

I debugged through the msal code a little. When the scope is configured for onBehalfOf flow the following happens:

1. fetchClient.sendPostRequestAsync is called
2. Later on generateAuthenticationResult is called with fromCache set to false as expected
3. Before returning to my application's javascript SilentFlowClient.acquireCachedToken is called
4. generateAuthenticationResult is called with fromCache set to true
5. Control returns to my javascript with fromCache set to true

In comparison, if I change the scopes back to my first example, it doesn't do the SilentFlowClient call before returning and returns fromCache set to false as expected.

## Expected behavior
When scopes are adjusted for onBehalfOfFlow, after a successful redirect authentication, fromCache should be set to false so that when control returns to the client application's javascript, we know that the token was not originally acquired from the cache.

## Identity Provider

Azure AD

## Browsers/Environment
Chrome

## Regression

- [ x] Did this behavior work before? No
Version:

## Security

- [ ] Is this issue security related?
No

## Source

 Customer request

**Comment by tnorling** [comment]
@k290 Can you please clarify what APIs you are calling? A snippet of sample code would help me better understand the scenario you're describing.

From the steps you describe, it sounds like after you return from the redirect you're calling `acquireTokenSilent`, which is expected to return `fromCache: true` as the tokens were just acquired from the redirect - `acquireTokenSilent` would then be able to retrieve them from the cache. I'm not sure I understand the unexpected behavior.

**Comment by k290** [comment]
Apologies,  you're right. There seems to be something else going on when we switch to an onbehalf of flow. I will reopen a new ticket once we drill down closer to the cause of the issue
