### ISSUE TITLE
ClientAuthError: User login is required. For silent calls, request must contain either sid or login_hint when loading values from http

### ISSUE THREAD

**Issue by bladmorenoacn** [AzureAD/microsoft-authentication-library-for-js#3317]
## Library

- [X] `msal@1.4.4` 
- [X] `@azure/msal-angular@^1.1.2`

## Framework
- [X] Angular 11
- [ ] React
- [ ] Other

## Error Message
ERROR Error: Uncaught (in promise): ClientAuthError: User login is required. For silent calls, request must contain either sid or login_hint
ClientAuthError: User login is required. For silent calls, request must contain either sid or login_hint
    at ClientAuthError.AuthError [as constructor] (AuthError.js:22)
    at new ClientAuthError (ClientAuthError.js:100)
    at Function.push.7ZR7.ClientAuthError.createUserLoginRequiredError (ClientAuthError.js:149)
    at MsalService.<anonymous> (UserAgentApplication.js:566)
    at step (tslib.es6.js:100)
    at Object.next (tslib.es6.js:81)
    at tslib.es6.js:74
    at new ZoneAwarePromise (zone-evergreen.js:960)
    at Module.__awaiter (tslib.es6.js:70)
    at UserAgentApplication.js:544
    at resolvePromise (zone-evergreen.js:798)
    at zone-evergreen.js:705
    at SafeSubscriber._error (Observable.js:91)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:183)
    at SafeSubscriber.error (Subscriber.js:135)
    at Subscriber._error (Subscriber.js:75)
    at Subscriber.error (Subscriber.js:55)
    at MapSubscriber._error (Subscriber.js:75)
    at MapSubscriber.error (Subscriber.js:55)
    at MapSubscriber._error (Subscriber.js:75)

## MSAL Configuration

```js
    "msal": {
        "auth": {
            "authority": "https://login.microsoftonline.com/XXXXXX-XXXX-XXXX-86db-322b19a65a22",
            "clientId": "XXXXXXX-XXXX-XXXXX-b357-8e4cf97e4cc2",
            "redirectUri": "https:/XXXXXXX.accenture.com"
        },
        "system": {
            "loadFrameTimeout": 200000
        },
        "consentScopes": [
            "user.read",
            "openid",
            "profile"
          ],
        "protectedResourceMap": [
                "https://XXXXXXX.accenture.com/api/v1",
                [
                    "user.read",
                    "openid",
                    "profile"
                ],"https://graph.microsoft.com/beta/",
                [ "user.read",
                    "openid",
                    "profile"
                ]
            ]
    },
```

## Reproduction steps
It happens when I load through httpClient in the App Initializer method

```js
provide: APP_INITIALIZER,
      useFactory: (config: AppConfigService) => () => config.load(),
      deps: [AppConfigService], multi: true
```

```js
 public async load(): Promise<boolean> {
    let initConfig;
    return new Promise<boolean>((resolve, reject) =>{
      
       this.httpClient.get(this.config.CIOuhConfigurationVariablesAPIAdminUI).pipe(map(confData => {
            let confDataObj = <any>confData;
            let configItem = confDataObj.ConfigItems.Configurations.ConfigItemValue;
            let configItemObj = JSON.parse(configItem);
            let configUI = Object.assign({},this.config, configItemObj);
            this.config = configUI;
            sessionStorage[AppConfigService.configPath] = JSON.stringify(configItemObj);
           resolve(true);
          }
        )
      ).toPromise();
      });
}
```

## Identity Provider

- [X] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [X] Customer request

**Comment by bladmorenoacn** [comment]
I was able to detect the exact line where the error is happening

UserAgentApplication.js Line 557 - where this code tries to adquire the Account it come null, therefore the error is being thrown, it does work when I adquire the values from an static file and not from a service where the Access token has to be added to the Headers, but it does not if I try to do a request from the APP_INITIALIZER

```js
else {
                            account = this.getAccount();
                            this.logger.verbose("Account set from MSAL Cache");
                        }
                        adalIdToken = this.cacheStorage.getItem(Constants.adalIdToken);
                        // In the event of no account being passed in the config, no session id, and no pre-existing adalIdToken, user will need to log in
                        if (!account && !(request.sid || request.loginHint) && StringUtils.isEmpty(adalIdToken)) {
                            this.logger.info("User login is required");
                            // The promise rejects with a UserLoginRequiredError, which should be caught and user should be prompted to log in interactively
                            return [2 /*return*/, reject(ClientAuthError.createUserLoginRequiredError())];
                        }
```

**Comment by jasonnutter** [comment]
@bladmorenoacn Please see this issue for details on how to use APP_INITIALIZER with MSAL Angular v1: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1403

Try that out and let us know if you still have questions, thanks!

**Comment by jasonnutter** [comment]
I believe the issue is that if you try to use the injected `HttpClient` before MSAL has been initialized, you will get this error (because the MSAL Interceptor will attempt to call acquireTokenSilent). Instead, you should instantiate a separate httpclient (that does not use the interceptors) to load your configuration.

**Comment by bladmorenoacn** [comment]
I am loading this values with no issues, the issue comes when I try to do a request after the MSAL is initialized,  I am not using exactly your solution, but it works.
Just to make sure 100%, I will try to get as close as possible to your solution on Monday to see if that helps.

Thank you

________________________________
From: Jason Nutter ***@***.***>
Sent: Friday, March 26, 2021 5:50:48 PM
To: AzureAD/microsoft-authentication-library-for-js ***@***.***>
Cc: Moreno, Blad ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [AzureAD/microsoft-authentication-library-for-js] ClientAuthError: User login is required. For silent calls, request must contain either sid or login_hint when loading values from http (#3317)

This message is from an EXTERNAL SENDER - be CAUTIOUS, particularly with links and attachments.
________________________________


I believe the issue is that if you try to use the injected HttpClient before MSAL has been initialized, you will get this error (because the MSAL Interceptor will attempt to call acquireTokenSilent). Instead, you should instantiate a separate httpclient (that does not use the interceptors) to load your configuration.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_AzureAD_microsoft-2Dauthentication-2Dlibrary-2Dfor-2Djs_issues_3317-23issuecomment-2D808568942&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=GYWY4qXuRT-F4VRs_HJE0s5ki_f2K7_iCaYaezozbtA&m=IaIDq6t--of9JdyyNMxgKvY4Pt0fS-OwSuPJ18Tk4V0&s=m3eCZeG_cKiU1KJlfb6QvmseQ7ILN2e0bizjkLMu0ks&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ASADBH4XA5IY3RQFHKEG4GLTFUFURANCNFSM4Z33TCYA&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=GYWY4qXuRT-F4VRs_HJE0s5ki_f2K7_iCaYaezozbtA&m=IaIDq6t--of9JdyyNMxgKvY4Pt0fS-OwSuPJ18Tk4V0&s=Pfy76RAsORfHHjWkG2b1zNaBLu6fKHKLbW4qZjbQ1x8&e=>.

________________________________

This message is for the designated recipient only and may contain privileged, proprietary, or otherwise confidential information. If you have received it in error, please notify the sender immediately and delete the original. Any other use of the e-mail by you is prohibited. Where allowed by local law, electronic communications with Accenture and its affiliates, including e-mail and instant messaging (including content), may be scanned by our systems for the purposes of information security and assessment of internal compliance with Accenture policy. Your privacy is important to us. Accenture uses your personal data only in compliance with data protection laws. For further information on how Accenture processes your personal data, please see our privacy statement at https://www.accenture.com/us-en/privacy-policy.
______________________________________________________________________________________

www.accenture.com

**Comment by jasonnutter** [comment]
@bladmorenoacn Which scopes are needed for the http request against the `CIOuhConfigurationVariablesAPIAdminUI` endpoint?

If an application needs access tokens for an http request (that is initiated with the injected http client), the user must be first logged in before your application can invoke `acquireTokenSilent`. Is your application logging in the user before making this request? If not, this error is expected.

**Comment by jasonnutter** [comment]
Given the above, aside from removing the `CIOuhConfigurationVariablesAPIAdminUI` endpoint from the protected resource map, you can mitigate this error in one of two ways:

1. Ensure the user is logged in before initiating the http request for the `CIOuhConfigurationVariablesAPIAdminUI` endpoint, or
2. Catch the error thrown when your app makes the request to `CIOuhConfigurationVariablesAPIAdminUI`, invoke one of the interactive methods (loginPopup, loginRedirect), and then make the http request again.

**Comment by bladmorenoacn** [comment]
On it. Thanks.

________________________________
From: Jason Nutter ***@***.***>
Sent: Monday, March 29, 2021 1:25:17 PM
To: AzureAD/microsoft-authentication-library-for-js ***@***.***>
Cc: Moreno, Blad ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [AzureAD/microsoft-authentication-library-for-js] ClientAuthError: User login is required. For silent calls, request must contain either sid or login_hint when loading values from http (#3317)

This message is from an EXTERNAL SENDER - be CAUTIOUS, particularly with links and attachments.
________________________________


Given the above, aside from removing the CIOuhConfigurationVariablesAPIAdminUI endpoint from the protected resource map, you can mitigate this error in one of two ways:

  1.  Ensure the user is logged in before initiating the http request for the CIOuhConfigurationVariablesAPIAdminUI endpoint, or
  2.  Catch the error thrown when your app makes the request to CIOuhConfigurationVariablesAPIAdminUI, invoke one of the interactive methods (loginPopup, loginRedirect), and then make the http request again.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_AzureAD_microsoft-2Dauthentication-2Dlibrary-2Dfor-2Djs_issues_3317-23issuecomment-2D809608685&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=GYWY4qXuRT-F4VRs_HJE0s5ki_f2K7_iCaYaezozbtA&m=HHssG1FN6pA-Ikt0U9usdtBOKoqWZEpYWgQhyuMy4Zs&s=MKOWti6ggoesuU9hEHENv3UrP3j4zHgHBSGAUFY8meg&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ASADBH7ELBTPTZPTAW6P3ATTGDAY3ANCNFSM4Z33TCYA&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=GYWY4qXuRT-F4VRs_HJE0s5ki_f2K7_iCaYaezozbtA&m=HHssG1FN6pA-Ikt0U9usdtBOKoqWZEpYWgQhyuMy4Zs&s=ihzMK7qnTLzx5X7unWuwjnphLTzg3iMI4rW5unEGhUU&e=>.

________________________________

This message is for the designated recipient only and may contain privileged, proprietary, or otherwise confidential information. If you have received it in error, please notify the sender immediately and delete the original. Any other use of the e-mail by you is prohibited. Where allowed by local law, electronic communications with Accenture and its affiliates, including e-mail and instant messaging (including content), may be scanned by our systems for the purposes of information security and assessment of internal compliance with Accenture policy. Your privacy is important to us. Accenture uses your personal data only in compliance with data protection laws. For further information on how Accenture processes your personal data, please see our privacy statement at https://www.accenture.com/us-en/privacy-policy.
______________________________________________________________________________________

www.accenture.com

**Comment by jasonnutter** [comment]
I will also note that `openid profile user.read` are scopes for Microsoft Graph, and so the access token you will be issued will be for MS Graph (and should not be used for your custom web API). Instead of using MS graphs, your application should register a custom scope(s) in the Azure Portal, and then use those scopes when requesting the configuration data.
