### ISSUE TITLE
Token acquisition in iframe failed due to timeout - SSO Silent with B2C custom policy

### ISSUE THREAD

**Issue by azuregurus** [AzureAD/microsoft-authentication-library-for-js#3318]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [ ] Angular
- [ ] React
- [x] Other

## Description
I've built a B2C custom policy using the starter pack and the instructions for multi-tenant AAD support. The policy works fine when I use it in my SPA application. However, when I want to navigate to another application from the same tenant in the same tab I'm always redirected to the B2C login page (I use the ssoSilent method to get the user session, and the the loginRedirect method if the session doesn't exist).
I've checked in the browser, and I can see the B2C SSO cookie: x-ms-cpim-sso:_0. But it is not picked up by my App.
In my policy the Relaying Party has the SSO scope set to Tenant, as well as a Session Management Provider for the JWT Issuer to use the OAuthSSOSessionProvider.

## Error Message

BrowserAuthError: monitor_window_timeout: Token acquisition in iframe failed due to timeout.
    at BrowserAuthError.AuthError [as constructor] (webpack-internal:///./node_modules/@azure/msal-browser/dist/index.es.js:550:24)
    at new BrowserAuthError (webpack-internal:///./node_modules/@azure/msal-browser/dist/index.es.js:7174:28)
    at Function.BrowserAuthError.createMonitorIframeTimeoutError (webpack-internal:///./node_modules/@azure/msal-browser/dist/index.es.js:7275:16)
    at eval (webpack-internal:///./node_modules/@azure/msal-browser/dist/index.es.js:9814:45)

## MSAL Configuration
MSAL Config:
```js
// authCallback.html is an empty page, additionally I've played with iframeHashTimeout but nothing changed
try {
  await this.myMSALObj.ssoSilent({ scopes: ["openid"], loginHint: "username", redirectUri: "https://localhost:8081/authCallback.html" })
} catch (error) {
  if (error instanceof InteractionRequiredAuthError || error instanceof BrowserAuthError) {
    await this.msalApplication.loginRedirect({ scopes: ["openid"], prompt: "login" })}
```
B2C policy
```xml
<!-- Relaying Party config -->
<SingleSignOn Scope="Tenant" KeepAliveInDays="7"/>

<!-- JwtIssuer Technical Profile references a new Session Management Profile -->
<TechnicalProfile Id="SM-JWTIssuer">
  <DisplayName>JWT Session Management Provider</DisplayName>
  <Protocol Name="Proprietary" Handler="Web.TPEngine.SSO.OAuthSSOSessionProvider, Web.TPEngine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" />
</TechnicalProfile>
```
I'm still confused if I need to add `<IncludeInSso>true</IncludeInSso>` in my technical profiles?

## Reproduction steps
Navigate to an app (e.g. app1.example.com) and sign in. In the same tab navigate to the other app on the same domain (e.g. app2.example.com).

## Expected behavior
The second app can acquire the token silently using the B2C session (x-ms-cpim-sso cookie) and not need to redirect to the sign in page.

## Identity Provider

- [ ] Azure AD
- [ ] Azure B2C Basic Policy
- [x] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [x] Chrome
- [x] Firefox
- [x] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [x] Customer request

**Comment by sameerag** [comment]
@nickgmicrosoft Can you please help with this?

**Comment by jasonnutter** [comment]
@azuregurus What version of MSAL.js are you using? Can you please try updating the latest?

Timeouts can happen for many reasons. Can you try debugging MSAL and see if you can determine what is happening to cause the timeout? Is the iframe not getting redirected back to your redirect URI? Or is it being redirected, but something else is causing the library to timeout?

**Comment by azuregurus** [comment]
The method fails, so it is not redirect to the URI.

We will follow-up on this issue next week with some debug information.
