### ISSUE TITLE
JavaScript critical error at line 1, column 11 in .../msal.js.map\n\nSCRIPT1004: Expected ';'

### ISSUE THREAD

**Issue by cognologixguru** [AzureAD/microsoft-authentication-library-for-js#332]
Hi,
I am trying to use MSAL to get access token in my office add-in. When I linked following files in my Home.html, it shows error -
**JavaScript critical error at line 2, column 12 in https://localhost:44302/.../msal.js.map\n\nSCRIPT1004: Expected ';'**
Files : 
msal.js
msal.js.map
msal.min.js
msal.min.js.map

Visual Studio Community 2017 Version : 15.7.3
Office 2016 Version : 1805 (Build : 9330.2124 Click-to-Run)

**Comment by nehaagrawal** [comment]
@cognologixguru   I am assuming that you are using the CND link to download the library. Could you please tell us which version of library you are using from CDN?

**Comment by nehaagrawal** [comment]
@cognologixguru  Can you please confirm what version of library you are using.

**Comment by nehaagrawal** [comment]
closing the issue due to lack of information from the user. Please feel free to open a new issue if this issue still exists.
