### ISSUE TITLE
msal-react useMsal hook documentation example destructures array instead of object properties

### ISSUE THREAD

**Issue by MarcAnnous** [AzureAD/microsoft-authentication-library-for-js#3323]
## Library
- [X] `@azure/msal-react@1.0.0-beta.1`

## Documentation location

- [ ] docs.microsoft.com
- [ ] MSAL.js Github Wiki
- [X] README file
- [ ] Other (please fill in)
- [ ] Documentation does not exist

## Description

The [useMsal hook documentation](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/hooks.md#usemsal-hook) has this minor bug.

This line
`const [instance, accounts, inProgress] = useMsal();`

will result in the following error:
`Invalid attempt to destructure non-iterable instance.`

It should be:
`const { instance, accounts, inProgress } = useMsal();`

**Comment by sameerag** [comment]
@tnorling Can you please take a look and update the docs as needed?

**Comment by tnorling** [comment]
@MarcAnnous Thanks for pointing this out, I've linked a PR that will close this.
