### ISSUE TITLE
Access to fetch at 'https://login.microsoftonline.com/common/oauth2/v2.0/token' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled

### ISSUE THREAD

**Issue by RomaRathi** [AzureAD/microsoft-authentication-library-for-js#3325]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by RomaRathi** [comment]
I have already migrated the rediect uri which is http://localhost:3000 to msal 2js. what else is required in this?
Also i have set the headers in iis to Access-Control-Allow-Origin : *

**Comment by RomaRathi** [comment]
[Mon, 29 Mar 2021 12:38:48 GMT] :  : @azure/msal-browser@2.12.1 : Info - Emitting event: msal:handleRedirectStart
app.module.ts:90 [Mon, 29 Mar 2021 12:38:48 GMT] :  : @azure/msal-browser@2.12.1 : Info - handleRedirectPromise called but there is no interaction in progress, returning null.
app.module.ts:90 [Mon, 29 Mar 2021 12:38:48 GMT] :  : @azure/msal-browser@2.12.1 : Info - Emitting event: msal:handleRedirectEnd
app.module.ts:90 [Mon, 29 Mar 2021 12:38:48 GMT] :  : @azure/msal-browser@2.12.1 : Info - Emitting event: msal:loginStart
Navigated to http://localhost:3000/
jquery-migrate-3.0.0.min.js:2 JQMIGRATE: Migrate is installed, version 3.0.0
app.module.ts:90 [Mon, 29 Mar 2021 12:38:56 GMT] :  : @azure/msal-browser@2.12.1 : Info - Emitting event: msal:handleRedirectStart
app.module.ts:90 [Mon, 29 Mar 2021 12:38:56 GMT] :  : @azure/msal-common@4.0.3 : Info - in acquireToken call
(index):1 Access to fetch at 'https://login.microsoftonline.com/b8f01a97-60c1-471f-b65a-d0bf1951db8c/oauth2/v2.0/token' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
zone-evergreen.js:1068 POST https://login.microsoftonline.com/b8f01a97-60c1-471f-b65a-d0bf1951db8c/oauth2/v2.0/token net::ERR_FAILED
(anonymous) @ zone-evergreen.js:1068
(anonymous) @ index.es.js:8915
step @ index.es.js:75
(anonymous) @ index.es.js:56
(anonymous) @ index.es.js:49
ZoneAwarePromise @ zone-evergreen.js:960
__awaiter @ index.es.js:45
push.u8tD.FetchClient.sendPostRequestAsync @ index.es.js:8906
(anonymous) @ index.es.js:3000
step @ index.es.js:177
(anonymous) @ index.es.js:158
(anonymous) @ index.es.js:151
ZoneAwarePromise @ zone-evergreen.js:960
__awaiter$1 @ index.es.js:147
push.u8tD.NetworkManager.sendPostRequest @ index.es.js:2991
(anonymous) @ index.es.js:3085
step @ index.es.js:177
(anonymous) @ index.es.js:158
(anonymous) @ index.es.js:151
ZoneAwarePromise @ zone-evergreen.js:960
__awaiter$1 @ index.es.js:147
push.u8tD.BaseClient.executePostToTokenEndpoint @ index.es.js:3081
(anonymous) @ index.es.js:4602
step @ index.es.js:177
(anonymous) @ index.es.js:158
fulfilled @ index.es.js:148
invoke @ zone-evergreen.js:364
onInvoke @ core.js:28281
invoke @ zone-evergreen.js:363
run @ zone-evergreen.js:123
(anonymous) @ zone-evergreen.js:857
invokeTask @ zone-evergreen.js:399
onInvokeTask @ core.js:28269
invokeTask @ zone-evergreen.js:398
runTask @ zone-evergreen.js:167
drainMicroTaskQueue @ zone-evergreen.js:569
Promise.then (async)
scheduleMicroTask @ zone-evergreen.js:552
scheduleTask @ zone-evergreen.js:388
onScheduleTask @ zone-evergreen.js:272
scheduleTask @ zone-evergreen.js:378
scheduleTask @ zone-evergreen.js:210
scheduleMicroTask @ zone-evergreen.js:230
scheduleResolveOrReject @ zone-evergreen.js:847
resolvePromise @ zone-evergreen.js:785
(anonymous) @ zone-evergreen.js:705
Promise.then (async)
(anonymous) @ zone-evergreen.js:1060
ZoneAwarePromise @ zone-evergreen.js:960
Ctor.then @ zone-evergreen.js:1060
resolvePromise @ zone-evergreen.js:754
(anonymous) @ zone-evergreen.js:705
(anonymous) @ index.es.js:44
ZoneAwarePromise @ zone-evergreen.js:960
adopt @ index.es.js:44
step @ index.es.js:48
fulfilled @ index.es.js:46
invoke @ zone-evergreen.js:364
onInvoke @ core.js:28281
invoke @ zone-evergreen.js:363
run @ zone-evergreen.js:123
(anonymous) @ zone-evergreen.js:857
invokeTask @ zone-evergreen.js:399
onInvokeTask @ core.js:28269
invokeTask @ zone-evergreen.js:398
runTask @ zone-evergreen.js:167
drainMicroTaskQueue @ zone-evergreen.js:569
Promise.then (async)
scheduleMicroTask @ zone-evergreen.js:552
scheduleTask @ zone-evergreen.js:388
onScheduleTask @ zone-evergreen.js:272
scheduleTask @ zone-evergreen.js:378
scheduleTask @ zone-evergreen.js:210
scheduleMicroTask @ zone-evergreen.js:230
scheduleResolveOrReject @ zone-evergreen.js:847
resolvePromise @ zone-evergreen.js:785
(anonymous) @ zone-evergreen.js:705
Promise.then (async)
(anonymous) @ zone-evergreen.js:1060
ZoneAwarePromise @ zone-evergreen.js:960
Ctor.then @ zone-evergreen.js:1060
resolvePromise @ zone-evergreen.js:754
(anonymous) @ zone-evergreen.js:705
(anonymous) @ index.es.js:44
ZoneAwarePromise @ zone-evergreen.js:960
adopt @ index.es.js:44
step @ index.es.js:48
(anonymous) @ index.es.js:49
ZoneAwarePromise @ zone-evergreen.js:960
__awaiter @ index.es.js:45
push.u8tD.FetchClient.sendGetRequestAsync @ index.es.js:8861
(anonymous) @ index.es.js:6062
step @ index.es.js:177
(anonymous) @ index.es.js:158
(anonymous) @ index.es.js:151
ZoneAwarePromise @ zone-evergreen.js:960
__awaiter$1 @ index.es.js:147
push.u8tD.Authority.getEndpointMetadataFromNetwork @ index.es.js:6056
(anonymous) @ index.es.js:6014
step @ index.es.js:177
(anonymous) @ index.es.js:158
(anonymous) @ index.es.js:151
ZoneAwarePromise @ zone-evergreen.js:960
__awaiter$1 @ index.es.js:147
push.u8tD.Authority.updateEndpointMetadata @ index.es.js:6000
(anonymous) @ index.es.js:5979
step @ index.es.js:177
(anonymous) @ index.es.js:158
fulfilled @ index.es.js:148
invoke @ zone-evergreen.js:364
onInvoke @ core.js:28281
invoke @ zone-evergreen.js:363
run @ zone-evergreen.js:123
(anonymous) @ zone-evergreen.js:857
invokeTask @ zone-evergreen.js:399
onInvokeTask @ core.js:28269
invokeTask @ zone-evergreen.js:398
runTask @ zone-evergreen.js:167
drainMicroTaskQueue @ zone-evergreen.js:569
Promise.then (async)
scheduleMicroTask @ zone-evergreen.js:552
scheduleTask @ zone-evergreen.js:388
onScheduleTask @ zone-evergreen.js:272
scheduleTask @ zone-evergreen.js:378
scheduleTask @ zone-evergreen.js:210
scheduleMicroTask @ zone-evergreen.js:230
scheduleResolveOrReject @ zone-evergreen.js:847
resolvePromise @ zone-evergreen.js:785
(anonymous) @ zone-evergreen.js:705
Promise.then (async)
(anonymous) @ zone-evergreen.js:1060
ZoneAwarePromise @ zone-evergreen.js:960
Ctor.then @ zone-evergreen.js:1060
resolvePromise @ zone-evergreen.js:754
(anonymous) @ zone-evergreen.js:705
(anonymous) @ index.es.js:44
ZoneAwarePromise @ zone-evergreen.js:960
adopt @ index.es.js:44
step @ index.es.js:48
fulfilled @ index.es.js:46
invoke @ zone-evergreen.js:364
onInvoke @ core.js:28281
invoke @ zone-evergreen.js:363
run @ zone-evergreen.js:123
(anonymous) @ zone-evergreen.js:857
invokeTask @ zone-evergreen.js:399
onInvokeTask @ core.js:28269
invokeTask @ zone-evergreen.js:398
runTask @ zone-evergreen.js:167
drainMicroTaskQueue @ zone-evergreen.js:569
Promise.then (async)
scheduleMicroTask @ zone-evergreen.js:552
scheduleTask @ zone-evergreen.js:388
onScheduleTask @ zone-evergreen.js:272
scheduleTask @ zone-evergreen.js:378
scheduleTask @ zone-evergreen.js:210
scheduleMicroTask @ zone-evergreen.js:230
scheduleResolveOrReject @ zone-evergreen.js:847
resolvePromise @ zone-evergreen.js:785
(anonymous) @ zone-evergreen.js:705
Promise.then (async)
(anonymous) @ zone-evergreen.js:1060
ZoneAwarePromise @ zone-evergreen.js:960
Ctor.then @ zone-evergreen.js:1060
resolvePromise @ zone-evergreen.js:754
(anonymous) @ zone-evergreen.js:705
(anonymous) @ index.es.js:44
ZoneAwarePromise @ zone-evergreen.js:960
adopt @ index.es.js:44
step @ index.es.js:48
(anonymous) @ index.es.js:49
ZoneAwarePromise @ zone-evergreen.js:960
__awaiter @ index.es.js:45
push.u8tD.FetchClient.sendGetRequestAsync @ index.es.js:8861
(anonymous) @ index.es.js:6148
step @ index.es.js:177
(anonymous) @ index.es.js:158
(anonymous) @ index.es.js:151
ZoneAwarePromise @ zone-evergreen.js:960
__awaiter$1 @ index.es.js:147
push.u8tD.Authority.getCloudDiscoveryMetadataFromNetwork @ index.es.js:6138
(anonymous) @ index.es.js:6095
step @ index.es.js:177
(anonymous) @ index.es.js:158
(anonymous) @ index.es.js:151
ZoneAwarePromise @ zone-evergreen.js:960
__awaiter$1 @ index.es.js:147
push.u8tD.Authority.updateCloudDiscoveryMetadata @ index.es.js:6080
(anonymous) @ index.es.js:5975
step @ index.es.js:177
(anonymous) @ index.es.js:158
(anonymous) @ index.es.js:151
ZoneAwarePromise @ zone-evergreen.js:960
__awaiter$1 @ index.es.js:147
push.u8tD.Authority.resolveEndpointsAsync @ index.es.js:5965
(anonymous) @ index.es.js:6250
step @ index.es.js:177
(anonymous) @ index.es.js:158
(anonymous) @ index.es.js:151
ZoneAwarePromise @ zone-evergreen.js:960
__awaiter$1 @ index.es.js:147
push.u8tD.AuthorityFactory.createDiscoveredInstance @ index.es.js:6241
(anonymous) @ index.es.js:10686
step @ index.es.js:75
(anonymous) @ index.es.js:56
(anonymous) @ index.es.js:49
ZoneAwarePromise @ zone-evergreen.js:960
__awaiter @ index.es.js:45
push.u8tD.ClientApplication.getDiscoveredAuthority @ index.es.js:10672
(anonymous) @ index.es.js:10775
step @ index.es.js:75
(anonymous) @ index.es.js:56
(anonymous) @ index.es.js:49
ZoneAwarePromise @ zone-evergreen.js:960
__awaiter @ index.es.js:45
push.u8tD.ClientApplication.getClientConfiguration @ index.es.js:10769
(anonymous) @ index.es.js:10715
step @ index.es.js:75
(anonymous) @ index.es.js:56
(anonymous) @ index.es.js:49
ZoneAwarePromise @ zone-evergreen.js:960
__awaiter @ index.es.js:45
push.u8tD.ClientApplication.createAuthCodeClient @ index.es.js:10709
(anonymous) @ index.es.js:10137
step @ index.es.js:75
(anonymous) @ index.es.js:56
(anonymous) @ index.es.js:49
ZoneAwarePromise @ zone-evergreen.js:960
__awaiter @ index.es.js:45
push.u8tD.ClientApplication.handleHash @ index.es.js:10122
(anonymous) @ index.es.js:10025
step @ index.es.js:75
(anonymous) @ index.es.js:56
(anonymous) @ index.es.js:49
ZoneAwarePromise @ zone-evergreen.js:960
__awaiter @ index.es.js:45
push.u8tD.ClientApplication.handleRedirectResponse @ index.es.js:9993
(anonymous) @ index.es.js:9946
step @ index.es.js:75
(anonymous) @ index.es.js:56
(anonymous) @ index.es.js:49
ZoneAwarePromise @ zone-evergreen.js:960
__awaiter @ index.es.js:45
push.u8tD.ClientApplication.handleRedirectPromise @ index.es.js:9934
(anonymous) @ app.service.ts:49
(anonymous) @ tslib.es6.js:74
ZoneAwarePromise @ zone-evergreen.js:960
__awaiter @ tslib.es6.js:70
(anonymous) @ app.service.ts:48
ZoneAwarePromise @ zone-evergreen.js:960
Unpack @ app.service.ts:48
(anonymous) @ app.service.ts:184
runInitializers @ core.js:27576
(anonymous) @ core.js:28891
_callAndReportToErrorHandler @ core.js:28992
(anonymous) @ core.js:28889
invoke @ zone-evergreen.js:364
onInvoke @ core.js:28281
invoke @ zone-evergreen.js:363
run @ zone-evergreen.js:123
run @ core.js:28164
bootstrapModuleFactory @ core.js:28871
(anonymous) @ core.js:28923
invoke @ zone-evergreen.js:364
run @ zone-evergreen.js:123
(anonymous) @ zone-evergreen.js:857
invokeTask @ zone-evergreen.js:399
runTask @ zone-evergreen.js:167
drainMicroTaskQueue @ zone-evergreen.js:569
Promise.then (async)
scheduleMicroTask @ zone-evergreen.js:552
scheduleTask @ zone-evergreen.js:388
scheduleTask @ zone-evergreen.js:210
scheduleMicroTask @ zone-evergreen.js:230
scheduleResolveOrReject @ zone-evergreen.js:847
then @ zone-evergreen.js:979
bootstrapModule @ core.js:28923
boVJ @ main.ts:11
__webpack_require__ @ bootstrap:79
0 @ xbrl-taxonomies-save.ts:86
__webpack_require__ @ bootstrap:79
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ vendor.js?b=0:1
Show 155 more frames
app.module.ts:90 [Mon, 29 Mar 2021 12:38:57 GMT] :  : @azure/msal-browser@2.12.1 : Info - BrowserCacheManager.cleanRequestByInteractionType: Removing temporary cache items for state: eyJpZCI6IjMzNzQ2ZTA1LTAwNjMtNGQ1My05MjUzLWFkMTIzYjUzY2VjZSIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicmVkaXJlY3QifX0=
app.module.ts:90 [Mon, 29 Mar 2021 12:38:57 GMT] :  : @azure/msal-browser@2.12.1 : Info - Emitting event: msal:loginFailure
app.module.ts:90 [Mon, 29 Mar 2021 12:38:57 GMT] :  : @azure/msal-browser@2.12.1 : Info - Emitting event: msal:handleRedirectEnd
error-page.service.ts:30 Error: Uncaught (in promise): BrowserAuthError: post_request_failed: Network request failed: If the browser threw a CORS error, check that the redirectUri is registered in the Azure App Portal as type 'SPA' | Network client threw: TypeError: Failed to fetch | Attempted to reach: https://login.microsoftonline.com/b8f01a97-60c1-471f-b65a-d0bf1951db8c/oauth2/v2.0/token
BrowserAuthError: post_request_failed: Network request failed: If the browser threw a CORS error, check that the redirectUri is registered in the Azure App Portal as type 'SPA' | Network client threw: TypeError: Failed to fetch | Attempted to reach: https://login.microsoftonline.com/b8f01a97-60c1-471f-b65a-d0bf1951db8c/oauth2/v2.0/token
    at BrowserAuthError.AuthError [as constructor] (index.es.js:524)
    at new BrowserAuthError (index.es.js:7129)
    at Function.push.u8tD.BrowserAuthError.createPostRequestFailedError (index.es.js:7315)
    at FetchClient.<anonymous> (index.es.js:8926)
    at step (index.es.js:75)
    at Object.throw (index.es.js:56)
    at rejected (index.es.js:47)
    at ZoneDelegate.invoke (zone-evergreen.js:364)
    at Object.onInvoke (core.js:28281)
    at ZoneDelegate.invoke (zone-evergreen.js:363)
    at resolvePromise (zone-evergreen.js:798)
    at zone-evergreen.js:705
    at rejected (tslib.es6.js:72)
    at ZoneDelegate.invoke (zone-evergreen.js:364)
    at Object.onInvoke (core.js:28281)
    at ZoneDelegate.invoke (zone-evergreen.js:363)
    at Zone.run (zone-evergreen.js:123)
    at zone-evergreen.js:857
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:28269)

**Comment by sameerag** [comment]
@RomaRathi This could be a usage issue, where `redierectUri` isn't registered in the portal appropriately. We have docs which can help you [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/errors.md#Access-to-fetch-at-%5Burl%5D-has-been-blocked-by-CORS-policy). Can you please check this and let us know how that goes?

**Comment by RomaRathi** [comment]
I was able to solve the issue.
I have configured the redirectUri correct under SPA but also there was another localhost registered under Web./'
When i migrated all the localhost under SPA it started working fine.

Is that so that we need to register all localhost under SPA for this to resolve the CORS issue?

**Comment by derisen** [comment]
@RomaRathi you have to make sure that Azure AD is able to distinguish your redirect URIs and match the correct auth flow with them. See the [documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/reply-url#localhost-exceptions):

> Due to ephemeral port ranges often required by native applications, the port component (for example, :5001 or :443) is ignored for the purposes of matching a redirect URI. As a result, all of these URIs are considered equivalent:
> http://localhost/MyApp
> http://localhost:1234/MyApp
> http://localhost:5000/MyApp
> http://localhost:8080/MyApp
> From a development standpoint, this means a few things:
> 
> Do not register multiple redirect URIs where only the port differs. The login server will pick one arbitrarily and use the behavior associated with that redirect URI (for example, whether it's a web-, native-, or spa-type redirect).
> 
> This is especially important when you want to use different authentication flows in the same application registration, for example both the authorization code grant and implicit flow. To associate the correct response behavior with each redirect URI, the login server must be able to distinguish between the redirect URIs and cannot do so when only the port differs.
> 
> To register multiple redirect URIs on localhost to test different flows during development, differentiate them using the path component of the URI. For example, http://localhost/MyWebApp doesn't match http://localhost/MyNativeApp.

**Comment by RomaRathi** [comment]
@derisen thanks for the reply and the information. It is not clear
