### ISSUE TITLE
MSAL Conflict with Infopath in Sharepoint 2013 on premise 

### ISSUE THREAD

**Issue by bbarnwell** [AzureAD/microsoft-authentication-library-for-js#3330]
## Library
- [ ] `@azure/msal-browser@2.13.0

## Framework
None

## Description
We have a javascript SPA using MSAL to display users Office 365 mail and calendar inside Sharepoint 2013 On Premise. The app works on dev and test servers, on production it throws auth related error for some users.

## Error Message
Uncaught (in promise) TypeError: t.scopes.add is not a function
    at msal-browser.min.js:32
    at Array.forEach (<anonymous>)
    at new e (msal-browser.min.js:32)
    at t.addScopes (msal-browser.min.js:32)
    at r.createAuthCodeUrlQueryString (msal-browser.min.js:32)
    at r.<anonymous> (msal-browser.min.js:32)
    at msal-browser.min.js:32
    at Object.next (msal-browser.min.js:32)
    at msal-browser.min.js:32
    at i.e._execute (bluebird.min.js:29)
    at i._resolveFromExecutor (bluebird.min.js:30)
    at new i (bluebird.min.js:30)
    at d (msal-browser.min.js:32)
    at r.getAuthCodeUrl (msal-browser.min.js:32)
    at a.<anonymous> (msal-browser.min.js:32)
    at msal-browser.min.js:17

## Expected behavior
User is authenticated and call to graph mail and calendar returns user's mail and calendar data to display in app.

## Identity Provider
- [ ] Azure AD

## Browsers/Environment
- [ ] Chrome
- [ ] Firefox
- [ ] Edge

## Regression
- [ ] Did this behavior work before?
It works on our own DEV and TEST servers.

## Security
N/A

## Source
Internal

**Comment by bbarnwell** [comment]
Error at msal-browser.min.js:32:25592

**Comment by sameerag** [comment]
@bbarnwell I believe this may be specific to the user's environment. One common occurrence is an `async` call or an `await` statement following a statement with no semicolon, which can cause JS to not identify the call as a function. There are numerous JS specific use cases that could cause this error.

Can we get more information on the specifics of this error for the production environment? Sample code, the browser environment and steps to reproduce and any other info you believe will help us debug this as needed.

**Comment by bbarnwell** [comment]
Thanks! Checked over the code and I don't think it's a missing semi colon. Code worked in our Dev and Testing environments. I'm only getting this error in our production environment, so I think it is something to do with our production enviro.

The app is based on this: https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-javascript-auth-code

I suspect it's failing in authRedirect.js

`// Create the main myMSALObj instance
// configuration parameters are located at authConfig.js
const myMSALObj = new msal.PublicClientApplication(msalConfig);

let accessToken;
let username = "";

let signInType;
let accountId = "";

// Redirect: once login is successful and redirects with tokens, call Graph API
myMSALObj.handleRedirectPromise().then(handleResponse).catch(err => {
    console.error(err);
});

function handleResponse(resp) {
    if (resp !== null) {
        username = resp.account.username;
        //showWelcomeMessage(resp.account);
        readMail2();
        readCal();
        document.cookie = "msal_username=" + username + ";.domain=xxxx;path=/";
        console.log(resp);
    } else {
        /**
         * See here for more info on account retrieval:
         * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/docs/Accounts.md
         */
        const currentAccounts = myMSALObj.getAllAccounts();
      //  if (currentAccounts === null) {
        if (!currentAccounts || currentAccounts.length < 1) {
        	signIn3("loginRedirect");
        	
           // return;
        } else if (currentAccounts.length > 1) {
            // Add choose account code here
            //signIn3("loginRedirect");
            username = currentAccounts[0].username;
            //showWelcomeMessage(currentAccounts[0]);
            readMail2(currentAccounts[0]);
            readCal(currentAccounts[0]);
            console.warn("Multiple accounts detected.");
            console.log(currentAccounts);
        } else if (currentAccounts.length === 1) {
            username = currentAccounts[0].username;
            //showWelcomeMessage(currentAccounts[0]);
            readMail2(currentAccounts[0]);
            readCal(currentAccounts[0]);
        }
    }
}

function signIn2() {
	// myMSALObj.loginRedirect(loginRequest);
	}

async function signIn3(method) {
    signInType = isIE ? "loginRedirect" : method;
    if (signInType === "loginPopup") {
        return myMSALObj.loginPopup(loginRequest).then(handleResponse).catch(function (error) {
            console.log(error);
        });
    } else if (signInType === "loginRedirect") {
    	var username = getCookie("msal_username"); // find some code to do that
        return myMSALObj.loginRedirect(loginRequest, "&login_hint=" + username);
    }
}
 // A custom function to get cookies
    function getCookie(name) {
        // Split cookie string and get all individual name=value pairs in an array
        var cookieArr = document.cookie.split(";");
    
        // Loop through the array elements
        for(var i = 0; i < cookieArr.length; i++) {
            var cookiePair = cookieArr[i].split("=");
    
            /* Removing whitespace at the beginning of the cookie name
            and compare it with the given string */
            if(name == cookiePair[0].trim()) {
                // Decode the cookie value and return
                return decodeURIComponent(cookiePair[1]);
            }
        }
    
        // Return null if not found
        return null;
    }
    
function signOut() {
    const logoutRequest = {
        account: myMSALObj.getAccountByUsername(username)
    };

    myMSALObj.logout(logoutRequest);
}

function getTokenRedirect(request) {
    /**
     * See here for more info on account retrieval:
     * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/docs/Accounts.md
     */
    request.account = myMSALObj.getAccountByUsername(username);
    return myMSALObj.acquireTokenSilent(request).catch(error => {
            console.warn("silent token acquisition fails. acquiring token using redirect");
           if (error instanceof msal.InteractionRequiredAuthError) {
                // fallback to interaction when silent call fails
                return myMSALObj.acquireTokenRedirect(request);
            } else {
                console.warn("The error is: " + error);
            //  signIn3("loginPopup");
            }
        });
}

function seeProfile2() {
    getTokenRedirect(loginRequest).then(response => {
        callMSGraph(graphConfig.graphMeEndpoint, response.accessToken, updateUI);
        profileButton.classList.add('d-none');
        mailButton.classList.remove('d-none');
    }).catch(error => {
        console.error(error);
    });
}

function readMail2() {
    getTokenRedirect(tokenRequest).then(response => {
        callMSGraph(graphConfig.graphMailEndpoint, response.accessToken, updateUI);
    }).catch(error => {
        console.error(error);
    });
}
function readCal() {
    getTokenRedirect(tokenRequest).then(response => {
        callMSGraph(graphConfig.graphCalendarEndpoint, response.accessToken, updateUI);
    }).catch(error => {
        console.error(error);
    });
}`

**Comment by bbarnwell** [comment]
I should qualify this. handleRedirectPromise() returns null for some users. I have some user accounts that do authenticate.

**Comment by bbarnwell** [comment]
I have determined that the issue is a conflict between MSAL and Infopath on a Sharepoint 2013 page. When our SPA page loads and the page includes an Infopath form, there is some sort of conflict that prevents acquireTokenSilent from acquiring a token. Anyone else run into this?

**Comment by jasonnutter** [comment]
@bbarnwell Based on the error it looks like it a potential clash with the `Set` class: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/56592a0082855e6395bd54fde77de24b772f7bea/lib/msal-common/src/request/ScopeSet.ts#L18-L29

I am guessing that some JS on teh page is adding a global `Set` class that is overwriting the built in `Set` class.

**Comment by bbarnwell** [comment]
Thanks. It was definitely the InfoPath form on the same page that caused the error. However, I have fixed this by putting the InfoPath form in an iframe on the same page and now I have a redirect loop issue - the page keeps reloading.

**Comment by jasonnutter** [comment]
@bbarnwell The entire page keeps reloading, or the iframe? Can you please share logs from MSAL?

**Comment by bbarnwell** [comment]
Thanks Jason. The entire page keeps reloading. I'll try to get some logging set up...

**Comment by jasonnutter** [comment]
@bbarnwell I'm guessing your app is attempting to do something (e.g. inspecting cached accounts) before the previous request is processed. When using redirects, you should invoke `handleRedirectPromise` and not perform any MSAL actions until that promise is resolved.

**Comment by bbarnwell** [comment]
Thanks. Actually, I just realized that on the page I'm loading in the iframe, it is also loading MSAL js file and attempting auth in the iframe.  Just caught this in my DEV environment.

``Uncaught (in promise) BrowserAuthError: redirect_in_iframe: Code flow is not supported inside an iframe. Please ensure you are using MSAL.js in a top frame of the window if using the redirect APIs, or use the popup APIs. (window.parent !== window) => true``

**Comment by jasonnutter** [comment]
@bbarnwell Yep, pages that are loaded inside iframes cannot auth via redirects. Apps running in iframes can only silent and popup based requests.
