### ISSUE TITLE
How to recover from BrowserAuthError: interaction_in_progress? Logout now throws this error

### ISSUE THREAD

**Issue by restfulhead** [AzureAD/microsoft-authentication-library-for-js#3331]
## Library
- [x] `@azure/msal-browser@2.13.0`
- [x] `@azure/msal-angular@2.0.0-beta.2`
 
## Framework
- [x] Angular

## Description
In very rare, hard to reproduce cases, we see the `BrowserAuthError: interaction_in_progress` error. I'm aware of the FAQ and this error usually does not happen. However, I assume that if the user quits the browser in the middle of the process or something similar, it can happen. We therefore implemented an error handler, that would call the `logout` function to clear the state and have the user recover from this situation. 

Now, with the recent upgrade this no longer works, because `initializeLogoutRequest` now throws this error. I can see that the "Interaction in progress" check was added to the logout function in this commit: https://github.com/AzureAD/microsoft-authentication-library-for-js/commit/3e8bfa2f4107241c35bedccd8e691009982d3ccb

If it's no longer possible to logout the user, how can we recover from this situation? Currently the only option is to ask the user to clear cookies/cache. This is a very bad user experience...

@tnorling Can this change be reverted? If not, how else to recover?

## Error Message
```
BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.  For more visit: aka.ms/msaljs/browser-errors.
    at BrowserAuthError.AuthError [as constructor] (http://localhost:4200/vendor.js:168843:24)
    at new BrowserAuthError (http://localhost:4200/vendor.js:175467:28)
    at Function.push.u8tD.BrowserAuthError.createInteractionInProgressError (http://localhost:4200/vendor.js:175534:16)
    at PublicClientApplication.push.u8tD.ClientApplication.initializeLogoutRequest (http://localhost:4200/vendor.js:179418:36)
    at PublicClientApplication.<anonymous> (http://localhost:4200/vendor.js:178875:51)
```

## Expected behavior
Logout should always work and always clear up any in progress state. If this is not intended, please provide a method to clear the state so that we can recover from a broken login.

## Identity Provider

- [x] Azure AD

## Browsers/Environment

- [x] Chrome

## Regression

- [x] Did this behavior work before?
Version:   `"@azure/msal-browser": "^2.12.1",`

## Security
- [ ] Is this issue security related?

## Source
- [x] Customer request

**Comment by tnorling** [comment]
@restfulhead We should understand why interaction is left in progress rather than applying a bandaid to the real problem. In progress state is stored in session storage so opening a new tab or browser should clear this, can you confirm whether or not this is the case? Can you provide any additional information about how you end up in this state?

**Comment by restfulhead** [comment]
Right, I can confirm that it is left over session state. Reloading the page does not help. I imagine closing the browser would, but it's not great to ask the user to do that. I cannot easily reproduce this state. I assume it may happen when using multiple tabs and closing a tab in the middle of things, but it's only a guess...

**Comment by tnorling** [comment]
@restfulhead Closing a tab will clear session storage and should not result in this error. If it is, we need a reproduction so we can debug why this is crossing tabs. If you're using redirect logins I would also expect reloading the page to clear the state (`handleRedirectPromise` will clear in progress redirect state), if it's not we should also debug why this isn't happening. If you're using popups this should be cleared when either the top frame or the popup window are closed. Can you clarify which flow you're using in your app?

Generally, interaction in progress errors should be expected if interaction is actually in progress and if interaction is not in progress that means there's either something wrong with the way your app is using the library or there's a bug in the library. Either way we should try to understand it and fix the root cause.

**Comment by restfulhead** [comment]
So what I can say is that when the session state contains `interaction_in_progress`, then all subsequent login attempts of a user fail with the `BrowserAuthError: interaction_in_progress` error. 

To login, I call `MsalService.loginRedirect( { redirectStartPage: fromUri, scopes: this.defaultAdScopes, prompt: 'select_account' })`

The stack trace here is:
```
BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.  For more visit: aka.ms/msaljs/browser-errors.
    at BrowserAuthError.AuthError [as constructor] (http://localhost:4200/vendor.js:168843:24)
    at new BrowserAuthError (http://localhost:4200/vendor.js:175467:28)
    at Function.push.u8tD.BrowserAuthError.createInteractionInProgressError (http://localhost:4200/vendor.js:175534:16)
    at PublicClientApplication.push.u8tD.ClientApplication.preflightInteractiveRequest (http://localhost:4200/vendor.js:179297:36)
    at PublicClientApplication.<anonymous> (http://localhost:4200/vendor.js:178536:45)
    at step (http://localhost:4200/vendor.js:168394:23)
    at Object.next (http://localhost:4200/vendor.js:168375:53)
    at http://localhost:4200/vendor.js:168368:71
    at new ZoneAwarePromise (http://localhost:4200/polyfills.js:1321:33)
    at __awaiter (http://localhost:4200/vendor.js:168364:12)
```

I also noticed that when doing `acquireTokenSilent`, I see `BrowserCacheManager.cleanRequestByState`. I do not see this message when calling `MsalService.loginRedirect`. Maybe that is the problem?

**Comment by tnorling** [comment]
@restfulhead This means that `handleRedirectPromise` isn't being called on page load or isn't finished before attempting to login again. `handleRedirectPromise` will clear in progress state when returning from a back button or when reloading the page.

Please read [these docs](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/redirects.md) and make sure you're either using the `MsalRedirectComponent` or are calling `handleRedirectObservable` on every page that will call `loginRedirect` or return from a redirect

**Comment by restfulhead** [comment]
Oh I see. I was calling `handleRedirectObservable()` when returning from the redirect, but I missed the fact that I need to call it before the redirect as well. Changing my code to `this.msalAuth.handleRedirectObservable().pipe(concatMap(() => this.msalAuth.loginRedirect({...})))` fixes the issue with the back button. 

(I cannot simply add `<app-redirect>` to every page as the documentation suggests, because we support multiple identity providers and MSAL is not always active...)

This solves my issue. @tnorling Thank you so much for your prompt help!
