### ISSUE TITLE
Upgrade KeyTar to 7.4.0 on msal-node-extensions

### ISSUE THREAD

**Issue by sadasant** [AzureAD/microsoft-authentication-library-for-js#3333]
## Library
- [x] `@azure/msal-node-extensions@1.0.0-alpha.6`

## Description

`@azure/msal-node-extensions@1.0.0-alpha.6` currently depends on KeyTar v7.0.0. KeyTar has released some updates that would improve the developer experience since then. The latest version available on KeyTar is 7.4.0.

One of the reasons this will be useful is because of: https://github.com/atom/node-keytar/issues/317 where it's stated that the following pre-builds are missing:

• Node 12 - API Version 76
• Node 13 - API Version 79
• Node 14 - API Version 83
• Node 15 - API Version 88

## Source

- [x] Internal (Microsoft)
- [ ] Customer request

**Comment by sameerag** [comment]
This is in progress, will link a PR soon.

**Comment by sameerag** [comment]
@sadasant The latest is 7.6.0, #3343 addresses this and also adds caret version support. cc @samuelkubai

**Comment by sadasant** [comment]
@sameerag sounds awesome!
