### ISSUE TITLE
DPAPI binaries on @azure/msal-node-extensions do not work on Windows, on Node 15

### ISSUE THREAD

**Issue by sadasant** [AzureAD/microsoft-authentication-library-for-js#3334]
## Library
- [x] `@azure/msal-node-extensions@1.0.0-alpha.6`

## Description

If one installs `@azure/msal-node-extensions@1.0.0-alpha.6` on Windows, using Node 15, the FilePersistenceWithDataProtection class (that uses the DPAPI binaries) throws when one attempts to use it.

## Error Message

```
Uncaught PersistenceError: DPAPIEncryptedFileError: Encryption/Decryption failed. Error code: 87
```

## Identity Provider

- [x] Azure AD

## Browsers/Environment

Node v15.12.0 on Microsoft Windows 10 Pro.

## Source

- [x] Internal (Microsoft)
- [ ] Customer request

**Comment by sameerag** [comment]
@samuelkubai can you please take a look at this?

**Comment by sameerag** [comment]
@sadasant We are not currently supporting `node 15` for `msal-node`.  However since we plan to support `node 16` which will be released soon and some of the `node 15` api will carry over, we want to root cause this issue and determine if there is any change needed from our end. Please understand this will be of a lesser priority over other issues in our queue right now.

**Comment by joshfree** [comment]
@sameerag This issue, along with the other Node 8 issue https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/3337, blocks the Azure.Identity Client library for Javascript release we're planning for May.

Can this be prioritized higher?

**Comment by sadasant** [comment]
@sameerag @samuelkubai Found how to narrow down the issue!

This code doesn't work on Node 15:

```ts
  const {
    FilePersistenceWithDataProtection,
    DataProtectionScope,
    PersistenceCachePlugin
  } = require("@azure/msal-node-extensions");
  const persistence = await FilePersistenceWithDataProtection.create(
    "file-name",
    DataProtectionScope.CurrentUser
  );
  persistence.save("");
```

On Node 14, this code does produce the error, but the error doesn't bubble up, it shows as: `UnhandledPromiseRejectionWarning: PersistenceError: DPAPIEncryptedFileError: Encryption/Decryption failed. Error code: 87`. The code echoes a full error with a trace, but it doesn't break at that point, it continues, which is why I wasn't able to see the problem.

On Node 15, the code above produces the error: `PersistenceError: DPAPIEncryptedFileError: Encryption/Decryption failed. Error code: 87`. This error bubbles up and the program stops.

Also worth noting, this error goes away if I change the last line to: `persistence.save("{}");`.

So, seems like Node 15 actually *fixes* a bug on Node 14! Unexpected. Anyway, I will close this for the time being. Thank you!

**Comment by sameerag** [comment]
Thank you @sadasant. Great find. Follow up: Should we change our sample to reflect these changes? Can you please let us know if you can contribute a doc to help the community?

We would like to highlight this for anyone relevant.
