### ISSUE TITLE
Provide Node 8 support, specially for @azure/msal-node-extensions

### ISSUE THREAD

**Issue by sadasant** [AzureAD/microsoft-authentication-library-for-js#3337]
## Library
- [x] `@azure/msal-node@1.x.x`
- [x] `@azure/msal-node-extensions@1.0.0-alpha.6`

## Description

Although the Node.js 8 runtime was deprecated on June 5th, 2020, arguably many consumers could still be using Node 8. Would it be too hard to add Node.js 8.x.x support?

In the Azure SDK for JS, we haven't yet stopped supporting Node 8. To depend on @azure/msal-node-extensions, we would need to drop Node 8 support.

## Source

- [x] Internal (Microsoft)
- [ ] Customer request

**Comment by jasonnutter** [comment]
@sadasant How long does Azure SDK plan to support Node 8? Generally speaking, when a major version of one of our libraries is released, we only support versions of a runtime or framework that the maintainers of that dependency still support. This is to avoid a situation where a bug in the library is caused by a bug in the dependency (especially a security bug) that the maintainers will not fix.

**Comment by sameerag** [comment]
Adding to what @jasonnutter said, we developed `msal-node` on Node.js version 10. Trying to add `node 8` support would open us to issues that may pertain node API changes and not `msal-node`

**Comment by ramya-rao-a** [comment]
@sameerag, @jasonnutter,
 
We (Azure SDK for JS) have just started the discussions around dropping support for Node 8.

Can you share the challenges you see when trying to support Node 8? We are collecting data around the efforts and cost around supporting Node 8 and your inputs would be valuable. From the comments above, it looks like we started off on Node 10 and never really gave Node 8 a try. Would that be an accurate statement?

**Comment by sameerag** [comment]
>  From the comments above, it looks like we started off on Node 10 and never really gave Node 8 a try. Would that be an accurate statement?

Yes, that would be right!

**Comment by sameerag** [comment]
Our current recommendation is for the users to bypass our engines check on their volition if they want to support versions we do not approve of, and there is a PR in works listing that in our FAQ [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/3290)

**Comment by bterlson** [comment]
@sameerag fwiw, [engine-strict defaults to false](https://docs.npmjs.com/cli/v7/using-npm/config#engine-strict), so getting an actual blocking error on mismatched engine is quite unlikely.

**Comment by sameerag** [comment]
We currently do not have the bandwidth to test node8 and report the status. We also do not see the point in testing it later, as the support is already discontinued by the official Node.js release support. Is Azure SDK planning to discontinue `node 8` support?

**Comment by sameerag** [comment]
Closing this issue as it is decided to not take up `node 8` support for `msal-node` as discussed offline @sadasant
