### ISSUE TITLE
Allow configuring polling intervals on @azure/msal-node

### ISSUE THREAD

**Issue by sadasant** [AzureAD/microsoft-authentication-library-for-js#3338]
## Library
- [x] `@azure/msal-node@1.x.x`

## Description

While we move to use `@azure/msal-node` as a dependency on the Azure SDK for JS/TS, we've added recorded tests that help us see what changes happen on the network requests over time, and also test the full behavior of MSAL as if we were always online without actually reaching out to the authentication endpoint.

For this purpose, we would really appreciate if we could alter the intervals used on authentication methods such as DeviceCode to verify if the user has authenticated. At the moment, our playback tests that don't reach to the actual servers need to wait as if they were used by a real user. If we could customize them, we could run our tests on playback instantly.

## Source

- [x] Internal (Microsoft)
- [ ] Customer request

**Comment by sameerag** [comment]
We can potentially provide this enhancement for msal-node. Only concern I have with this is the throttling we may introduce to the server, by polling frequently. Will update this issue once I have more information regarding the impact of adding variable, and user controllable polling.

**Comment by sadasant** [comment]
@sameerag in our case, our recordings can be cleaned so the first response is always a good response. This means that on playback there is no second request. There's no throttling on playback, of course.

@sameerag one alternative could be to mock the pollers. Two designs that come to mind:

- If the poller is its own class, and the method that does the polling is a public method in that class, then we can use Sinon to replace that method with something that returns a custom response.
- If the poller is its own class, and the method that defines the interval is a public method in that class, then we could use Sinon to replace that method and return a custom interval.

**Comment by jasonnutter** [comment]
@sadasant The polling interval is [returned from the server](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/3463bc62eb06d1a18cdf76d0a8747e1987ec80b1/lib/msal-common/src/client/DeviceCodeClient.ts#L95), so you could change the polling interval by mocking the http request.

**Comment by sameerag** [comment]
We discussed this offline, apologies did not update the ticket. And @sadasant should be able to mock his tests as per our last discussion. I am closing this issue with this information, @sadasant feel free to reach out in case you have more questions.
