### ISSUE TITLE
MSAL React alpha version

### ISSUE THREAD

**Issue by yingying96** [AzureAD/microsoft-authentication-library-for-js#3340]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [X ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

Hi team,

May i know when will the alpha version for MSAL react be launched? I noticed that it's still stated as beta in the roadmap.

Thanks!

## Source

- [ ] Internal (Microsoft)
- [X ] Customer request

**Comment by jasonnutter** [comment]
@yingying96 The alpha version (private preview) was released earlier this year, and beta (public preview) was released earlier this month.

**Comment by yingying96** [comment]
Apologies, i mean the GA version. Thanks!

**Comment by jasonnutter** [comment]
This will be noted in the updated roadmap. Currently planned for May.

**Comment by yingying96** [comment]
Noted with thanks!
