### ISSUE TITLE
Binding access token to user certificate

### ISSUE THREAD

**Issue by forellendev** [AzureAD/microsoft-authentication-library-for-js#3348]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ X ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

Hey together, could you please tell me whether this library allows binding the access and id tokens stored in localstorage to a user certificate? I would like to ensure proof-of-possession of the token (the user requesting the internal resource is exactly the user that obtained the access/id token in the first place) to prevent token theft and replay attacks (mTLS).

Thank you for helping

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by jasonnutter** [comment]
@forellendev MSAL.js v2 supports access token proof of possession using the browser crypto APIs. More details here: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/ef11fd7eb7f523fba1cf2002579ec75e4179b619/lib/msal-browser/docs/access-token-proof-of-possession.md

This cryptographically binds the access tokens to the browser that requested them. Note, using AT PoP requires that the resource that validates the tokens supports validating PoP requests.
