### ISSUE TITLE
Not gettiing user email information on login failures

### ISSUE THREAD

**Issue by SreekanthOAuth** [AzureAD/microsoft-authentication-library-for-js#3349]
## Library

- [ ] `"msal": "^1.4.4",` 

## Framework

- React

## Description
We are using this library in our react app (ms bot webchat channel). Recently, we have got a requirement to log the user login failure event into application insights and as part of this event, we need to add user email as one of the properties. So that we can cross-check when any customer complains about the login issue.

## Error Message

We are actually looking for user email information on login failure.

## MSAL Configuration

```
const loginRequest = {
    scopes: ['openid', 'profile', 'User.Read']
  };
```

## Reproduction steps

Checkout below repo
https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/06.recomposing-ui/a.minimizable-web-chat

## Expected behavior

Need user email information on user login failure.

## Identity Provider

- Azure AD

## Browsers/Environment

- Chrome
- Edge
- Safari

## Regression

- [ ] Did this behavior work before? **No**
Version: 

## Security

- [ ] Is this issue security related? **Yes**

## Source

- [ ] Internal (Microsoft)

Please let us know if you need any further information on this

**Comment by sameerag** [comment]
@SreekanthOAuth The user login failure can happen for varied reasons and we throw back the server error we receive to the user as is. We do not have the info for the user email to send it back to you. Also since this is PII (Personally Identifiable Information) we cannot give the info in our client by default.

**Comment by SreekanthOAuth** [comment]
@sameerag  - Thanks for the information. We will use the server error in our insights.
