### ISSUE TITLE
PKCE Error with MSAL on production URL

### ISSUE THREAD

**Issue by jcharnley** [AzureAD/microsoft-authentication-library-for-js#3350]
## Library

- [ ] ` "@azure/msal-browser": "^2.8.0",`

## Framework

- [ ] JavaScript

## Description

I'v setup an azure b2b application using both ID and access Tokens. Part of auth includes using msal to sign in etc, it works on localhost, dev and production urls that we own. however, we have a reverse proxy to another site on our production url.  I cannot seem to login via that url. anyone have any ideas I could try pls?

My onedrive picker auth flow allows me to login on the issue site. Also ive added all the redirect-url on azure,  i had a single tenant enviroment setup previously and it worked from url

## Error Message

 Uncaught (in promise) BrowserAuthError: pkce_not_created: The PKCE code challenge and verifier could not be generated. Detail:TypeError: Cannot read property 'digest' of undefined

## MSAL Configuration

azure b2b multi-tenant
```js
export const msalConfig = {
  auth: {
    clientId: "0812fc81-7144-4f72-a309-1ad7da1078e0",
    authority:
      "https://login.microsoftonline.com/common",
    redirectUri: window.location.origin
    // navigateToLoginRequestUrl: true
  },
  cache: {
    cacheLocation: "sessionStorage", // This configures where your cache will be stored
    storeAuthStateInCookie: false // Set this to "true" if you are having issues on IE11 or Edge
  }
};

// Add scopes here for ID token to be used at Microsoft identity platform endpoints.
export const loginRequest = {
  scopes: [
    "openid",
    "profile",
    "User.Read",
    "Files.ReadWrite",
    "Files.ReadWrite.All"
  ]
};
// Add scopes here for access token to be used at Microsoft Graph API endpoints.
export const tokenRequest = {
  scopes: [
    "openid",
    "profile",
    "User.Read",
    "Files.ReadWrite",
    "Files.ReadWrite.All"
  ]
};

```

## Reproduction steps

```js
// Create the main myMSALObj instance
// configuration parameters are located at authConfig.js
import * as Msal from "@azure/msal-browser";

import { load3dModel } from "../../index";
import { fetchNetworkRequest } from "../cloud/api-progress/fetch-api-progress";

import { msalConfig, loginRequest, tokenRequest } from "./auth-config";
import {
  callMSGraph,
  grantOrgPermissions,
  getUsername,
  sendInvite
} from "./graph";


const myMSALObj = new Msal.PublicClientApplication(msalConfig);

let username = "";

const handleResponse = (resp) => {
  if (resp !== null) {
    username = resp.account.username;
    document.getElementById("welcomeMessage").textContent =
      "Welcome " + username;
    downloadModelFromUrl();
  } else {
  }
};
myMSALObj
  .handleRedirectPromise()
  .then(handleResponse)
  .catch((err) => {
    console.error(err);
  });

const getTokenRedirect = (request) => {
  request.account = myMSALObj.getAccountByUsername(username);
  return myMSALObj.acquireTokenSilent(request).catch((error) => {
    console.warn(
      "silent token acquisition fails. acquiring token using redirect"
    );
    if (error) {
      // fallback to interaction when silent call fails
      return myMSALObj.acquireTokenRedirect(request);
    } else {
      console.warn(error);
    }
  });
};

export const downloadModelFromUrl = () => {
  // construct encodedString from shared url and load model
  const splitHref = window.location.href.split("?model_link=");
  const sharingUrl = splitHref[1];
  const encodedString = btoa(sharingUrl);

  const url = `https://graph.microsoft.com/v1.0/shares/u!${encodedString}/driveItem/`;
  // get temp token for API request
  getTokenRedirect(loginRequest)
    .then((response) => {
      response = response;
      callMSGraph(url, response.accessToken, load3dModel, fetchNetworkRequest);
    })
    .catch((error) => {
      console.error(error);
    });
};

export const createSharedURL = async (driveId, itemId, accessToken) => {
  // get current users email address
  const myProfile = `https://graph.microsoft.com/v1.0/me/`;
  const email = await getUsername(myProfile, accessToken);
  // create sharing link
  const createLink = `https://graph.microsoft.com/v1.0/drives/${driveId}/items/${itemId}/createLink`;
  // grant persmissions
  const sharedUrl = await grantOrgPermissions(createLink, accessToken);
  const inviteLink = `https://graph.microsoft.com/v1.0/drives/${driveId}/items/${itemId}/invite`;
  await sendInvite(inviteLink, accessToken, sharedUrl);
};

export const signIn = () => {
  myMSALObj.loginRedirect(loginRequest);
};

export const signOut = () => {
  const logoutRequest = {
    account: myMSALObj.getAccountByUsername(username)
  };
  myMSALObj.logout(logoutRequest);
};

```

## Identity Provider

- [x] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [x] Did this behavior work before?
Version: yes when i was connected via single tenant

**Comment by jasonnutter** [comment]
@jcharnley Is your website loaded on http or https? I believe this error is due to the browser crypto APIs (`window.crypto.subtle`) not being present, which happens when your site is loaded on http. Https is a requirement in order to use MSAL.js.

**Comment by jcharnley** [comment]
Thanks for getting back. I read in another post that there was a load balancing issue between port 80 and 442. All the urls a apart from localhost are https. do service workers effect msal.js?

**Comment by jasonnutter** [comment]
Given service works do not have access to the DOM or browser storage, and that the crypto APIs are on `self.crypto` instead of `window.crypto`, it would be expected that MSAL.js would not work. We can look at improving this.

**Comment by jasonnutter** [comment]
I take it your MSAL related code is running in a service worker when this error occurs?

**Comment by jcharnley** [comment]
no not at all,am just having issues with my service worker acrross different origin.I dont believe it's related. Am I save to post my azure app manfiest in here? as the only thing differently I have done it setup a b2b with personal accounts app on a  different tenant. as If i go back to my old one it works fine

**Comment by jcharnley** [comment]
Yeah just doubled checked it,seems to work on the older tenant without any issues. and from my knowledge its a simliar setup, just using b2b instead

**Comment by jcharnley** [comment]
Thanks for your help, its unrelated to msal. closed
