### ISSUE TITLE
Multiple scopes for different apis

### ISSUE THREAD

**Issue by shanavaz79** [AzureAD/microsoft-authentication-library-for-js#3363]
Hello,

## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`
@azure/msal-browser@2.13.0

## Framework

- [ ] Angular
- [x] React
- [ ] Other

## Description
We have migrated from 1.4.6 to 2.13.0 because we wanted to switch from implicit auth to auth code flow.  I have observed that its not storing multiple access tokens for different scopes in local storage.  There is only one and it returns that same access token for different scopes, which is wrong.

## MSAL Configuration
const msalConfig = {
  auth: {
    clientId: appConfig.APPLICATION_CLIENT_ID!,
    authority: appConfig.AUTHORITY_URL!,
    redirectUri: window.location.origin,
  },
}
```js
// Provide configuration values here.
// For Azure B2C issues, please include your policies.
```

## Reproduction steps

```js
// Provide relevant code snippets here.
// For Azure B2C issues, please include your policies.
```

## Identity Provider

- [ ] Azure AD
- [ ] Azure B2C Basic Policy
- [x] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [x] Did this behavior work before?
Yes in version: 1.4.6

## Security

- [ ] Is this issue security related?
No
## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by AdamMYoung** [comment]
+1 to this, we're requesting two access tokens with different scopes, and MSAL seems to recycling one token and requesting a new one, both with the same scope

**Comment by AdamMYoung** [comment]
One workaround currently is to set `forceRefresh: true` within `acquireTokenSilent`, not ideal currrently

**Comment by gridpatrik** [comment]
+1 
When requesting an access token for the second resource this breaks the cache. Looks like it's always being written to the cache with the scope from the first token request. Current workaround is same as @AdamMYoung but this is of course something that needs to be fixed!

**Comment by sameerag** [comment]
@AdamMYoung @ratnapraveen Thank you for the context. Can you guys please file a B2C service issue as instructed [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md#what-should-i-do-if-i-believe-my-issue-is-with-the-b2c-service-itself-rather-than-with-the-library)?

**Comment by tnorling** [comment]
Thanks for the info shared here. We're working with the B2C service to patch or revert a change that was rolled out late last week, ASAP. If you need an immediate resolution, setting `forceRefresh: true`, as mentioned above, is the suggested workaround.

**Comment by gridpatrik** [comment]
Is there an external issue tracker, related to B2C, on this?

**Comment by sameerag** [comment]
@gridpatrik 

* The bug is now rolled back and being deployed to customers. 
* The fix is coming in a week, and will be rolled out soon.

I will check with the service team if there is an external tracker, nevertheless, you can check here for updates. We have an internal issue filed on the b2c service team and tracking it.

**Comment by murrayw24** [comment]
This is currently causing intermittent auth problems in our environment

**Comment by tnorling** [comment]
All, the server team has notified us that the rollback for this bug completed this afternoon. Closing, but let us know if this is still an issue and we can reopen.

The bug for this was related to a feature to allow refresh tokens to be redeemed for different access tokens. If your application needs to use more than 1 access token and you are receiving a blank access token in the server response please track issue #2315 for that feature. The bug has been fixed and the feature has begun rolling out again.
