### ISSUE TITLE
Msal-browser refresh token

### ISSUE THREAD

**Issue by ManishKiranagi** [AzureAD/microsoft-authentication-library-for-js#3365]
## Library

- [ ] `@azure/msal-browser@2.x.x`

## Description
In MSAL browser, acquireTokenSlient get's a refresh token on every call to the token end point. The first refresh token has a duration of 1 day. Subsequent refresh tokens all have reduced (the remaining) expiry time. After the refresh token expires eventually, if an AD Session exists than the authorisation code is returned in an iframe before making the token call. If this silent retrieval of auth code fails we have to use an interactive method call.

Now the AD Session typically lasts a day. So are we saying that the user will always be forced to do an interactive login after a day because the refresh token has expired and the AD Session has expired?

Or does the AD Session roll on for each token call, so that the expired refresh token can come silently through iframe call mentioned above?

I need the user to be able to access the token without login if he has been making the token calls without break of a day. Would that be possible using msal-browswr refresh tokens? MSAL.js does seem to roll on the AD session after every authorisation endpoint call via aquireTokenSilent - so it doesnt have a problem. But I cant use it as Safari blocks 3rd party cookies requiring an interactive call every hour - which is essentially a refresh of the app.

## Source

- [ ] Customer request

**Comment by sameerag** [comment]
@ManishKiranagi If the user is consistently making token calls without a halted browser session, `acquireTokenSilent` should take care of getting a new `refreshToken` before the expiry. What you see - the reduced time - is only until we near the actual expiry, MSAL will continue to consider a token to be expired where there is less than 5 minutes remaining for the token and makes a network call at that point to hydrate the current `refreshToken`.

This expiry time is controlled by `tokenRenewalOffsetSeconds`, the docs can be referenced [here](https://azuread.github.io/microsoft-authentication-library-for-js/ref/modules/_azure_msal_browser.html#browsersystemoptions). The default value is 5 min before the actual expiry.

Hope this clarifies.

**Comment by sameerag** [comment]
@ManishKiranagi 
* For SPA type apps, RefreshTokens cannot be rolled out beyond their initial expiry. It means that an RT is only valid 24hrs from when the code is exchanged.
* `acquireTokenSilent` if it detects an expired `refreshToken` will attempt to fetch an authorization code silently using an iframe
* However as you called out, this will not work if third party cookies are blocked, as they block iframes too, and the only fallback today is to make an interactive request. This will also happen if the AAD session is invalid.

We are working on a solution to leverage `storageAccessAPI` which should allow end users to consent to allowing third party cookies inside of iframes. This solution is still in design phase and is not yet available in the library.

Hope this clarifies.

**Comment by sameerag** [comment]
@sameerag To follow up on adding docs regarding RT refresh logic. cc @pkanher617

**Comment by ManishKiranagi** [comment]
@sameerag Thanks for your reply.
When is the storageAccessAPI based solution expected? And will that be availaible for both MSAL.js and Msal-browser.

**Comment by sameerag** [comment]
@ManishKiranagi We are still in the design phase for this. Please check our [roadmap](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/roadmap.md) for the announcement.

**Comment by sameerag** [comment]
Closing this as this is a feature that will be tracked in the MSAL JS [roadmap](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/roadmap.md). cc @jasonnutter, please add this when we have more clarity on the timelines for this.
