### ISSUE TITLE
Authentication redirect exposes Id token 

### ISSUE THREAD

**Issue by Gyalomalom** [AzureAD/microsoft-authentication-library-for-js#3367]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [x] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

I'm using the Angular MSAL library and Azure AD implicit flow to authorize users. 

After signing in through the Microsoft page, I first get a redirect url that exposes the id token and other response information in it before being redirected to the provided redirect uri. This url with the token hash is then saved in the browser history, which is an obvious security risk.

So far I had no luck finding a solution to the issue anywhere. 

## Source

- [ ] Internal (Microsoft)
- [x] Customer request

**Comment by jasonnutter** [comment]
@Gyalomalom Can you please clarify which version of `msal` and `@azure/msal-angular` you are using? Our libraries should remove the hash from the url without adding it to the browser history.

**Comment by Gyalomalom** [comment]
> @Gyalomalom Can you please clarify which version of `msal` and `@azure/msal-angular` you are using? Our libraries should remove the hash from the url without adding it to the browser history.

I'm using MSAL-angular 1.1.1

**Comment by jasonnutter** [comment]
And which version of `msal`?

**Comment by Gyalomalom** [comment]
> And which version of `msal`?

1.3.1

**Comment by jasonnutter** [comment]
Can you please try the latest version of `msal` (1.4.8)?

**Comment by Gyalomalom** [comment]
> Can you please try the latest version of `msal` (1.4.8)?

Hello @jasonnutter, I tried it with the latest msal and the token is still saved in the browser history.

**Comment by jasonnutter** [comment]
@Gyalomalom Okay thanks we'll take a look.

**Comment by Gyalomalom** [comment]
> @Gyalomalom Okay thanks we'll take a look.

Also, I would like to mention that the access token is properly removed from the url, only the id token is saved for some reason.

**Comment by hectormmg** [comment]
@Gyalomalom I'm able to reproduce this behavior. I'll provide and update when we have a fix. Thanks!

**Comment by hectormmg** [comment]
@Gyalomalom I have a fix for this issue in #3587 . If you could try pulling the branch locally and testing to see if the problem is solved for you, we'd really appreciate it. Thanks!

**Comment by Gyalomalom** [comment]
@hectormmg Sorry, I didn't see your comment. So the fix was merged into the main branch?
