### ISSUE TITLE
Wiki documentation is non-existent

### ISSUE THREAD

**Issue by aszalacinski** [AzureAD/microsoft-authentication-library-for-js#337]
I get we are all busy but when all MS documentation points to MSAL as the way to go for SPA apps, then documentation needs to be a first class citizen.

**Comment by nehaagrawal** [comment]
@aszalacinski  - I apologize that you are not able to find what you are looking for. We do have the documentation and we are currently working on improving it. Could you please  explain why do you say that it's non-existent?

**Comment by nartc** [comment]
@nehaagrawal the Wiki on this Github Repository does not show any useful information. Every item links back to Home. The only link that works is `Register your app with AAD` that links you to Microsoft website.

**Comment by nehaagrawal** [comment]
@aszalacinski I have fixed the wiki. Please check.
