### ISSUE TITLE
ConfidentialClientApplication.acquireTokenOnBehalfOf() fail to get token from cache first and will always execute token request to get new token

### ISSUE THREAD

**Issue by dilin-MS** [AzureAD/microsoft-authentication-library-for-js#3375]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [ ] `@azure/msal-browser@2.x.x`
- [x] `@azure/msal-node@1.0.1`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [ ] Angular
- [ ] React
- [x] NodeJS

## Description

We leverage MSAL confidential client application to acquire on-behalf-of user token. From the implementation of `ConfidentialClientApplication.acquireTokenOnBehalfOf()`, this function will first try get token from cache. If there is no token in cache, the function will execute token request to get a new token. 

However, during my test, it seems the function fails to read token from cache, it will always execute token request to acquire obo token.

## Reproduction steps

I call `ConfidentialClientApplication.acquireTokenOnBehalfOf()` multiple times, all the tokens are new token, none of them is read from cache. Could you please help check whether the cache manager is working correctly?

```typescript
const cca = new ConfidentialClientApplication({
  auth: {
    clientId: myClientId,
    authority: "https://login.microsoftonline.com/<my-tenant-id>",
    clientSecret: myCclientSecret
  }
});
result = await cca.acquireTokenOnBehalfOf({
  oboAssertion: ssoToken,
  scopes: ["User.Read"]
});
```

## Expected behavior
First time call `ConfidentialClientApplication.acquireTokenOnBehalfOf()` should execute token request to AAD, but the second time token requirement of the same scope should read from cache first.

## Identity Provider

- [x] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [x] Internal (Microsoft)
- [ ] Customer request

**Comment by sameerag** [comment]
Apologies for the delay @dilin-MS, I am trying to reproduce this on my end and will reach out once I am able to reproduce and debug it.

**Comment by dilin-MS** [comment]
Hi @sameerag , any update?

**Comment by sameerag** [comment]
@dilin-MS Are you explicitly calling `acquireTokenSilent()` to access cached tokens?

**Comment by dilin-MS** [comment]
No. Am I supposed to do so?

**Comment by dilin-MS** [comment]
I study the implementation of `cca.acquireTokenOnBehalfOf()` and seems it should read from cache first before execute token request. Have I missed anything? Or, what's the recommended practice to acquire token and read from cache first?

**Comment by sameerag** [comment]
@samuelkubai is able to reproduce this. We are currently debugging now and will post an update soon.

**Comment by samuelkubai** [comment]
@dilin-MS we are currently reviewing a solution for this issue and we'll update the thread with any updates on the solution.
