### ISSUE TITLE
postLogoutRedirectUri not working in Angular 11 sample app running in Chrome

### ISSUE THREAD

**Issue by workingtitledk** [AzureAD/microsoft-authentication-library-for-js#3378]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [X] `@azure/msal-browser@2.13.0`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [X] `@azure/msal-angular@2.0.0-beta.2`
- [ ] `@azure/msal-angularjs@1.x.x`

## Framework

- [X] Angular 11
- [ ] React
- [ ] Other

## Description
When logging out of the Angular 11 sample app (running on localhost) I'm redirected to the Azure sign out page, but after signing out I'm not being redirected back to the postLogoutRedirectUri. The logout procedure stops at this URL: https://login.microsoftonline.com/my_tenant_id_here/oauth2/v2.0/logoutsession

## Error Message
No errors messages are being thrown.

## MSAL Configuration

```js
auth: {
    clientId: 'my application client id here',
    redirectUri: '/',
    postLogoutRedirectUri: '/',
    authority: 'https://login.microsoftonline.com/my tenant id here'
},
cache: {
    cacheLocation: BrowserCacheLocation.LocalStorage,
    storeAuthStateInCookie: isIE, // set to true for IE 11. Remove this line to use Angular Universal
},
```
I've added the locahost uri to Redirect URI's
![Skærmbillede 2021-04-02 kl  13 25 58](https://user-images.githubusercontent.com/6696179/113411802-fb0a0180-93b6-11eb-8612-a1a47ed25119.png)

## Reproduction steps
1. Download the Angular 11 MSAL Angular v2 Sample from this repository.
2. Change the config as shown above.
3. Run the application.
4. Sign in and sign out.

## Expected behavior
Expected to be redirect back to the Angular 11 sample app after signing out.

## Identity Provider

- [X] Azure AD
- [ ] Azure B2C Basic Policy
- [ ] Azure B2C Custom Policy
- [ ] ADFS
- [ ] Other

## Browsers/Environment

- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari
- [ ] IE
- [ ] Other (Please add browser name here)

## Regression

- [ ] Did this behavior work before?
Version:

## Security

- [ ] Is this issue security related?

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by jo-arroyo** [comment]
@workingtitledk Are you experiencing this in other browsers, or just in Chrome?

**Comment by workingtitledk** [comment]
@jo-arroyo I've just tried a few browsers and the results are mixed. I'm on macOS.
Chrome v. 89.0.4389.114: doesn't work.
Chrome v. 89.0.4389.114 (incognito): works.
Firefox v. 87.0 (regular and incognito): doesn't work.
Safari v. 14.0.3: works.

**Comment by coreyleelarson** [comment]
Same issues using `@azure/msal-browser` and `@azure/msal-react`. Same results as @workingtitledk.

**Comment by jasonnutter** [comment]
@workingtitledk @coreyleelarson Please confirm the following:

- Is the url used for the post logout redirect uri set as a redirect uri in your app registration?
- Do you have a front-channel logout uri configured for your app?

**Comment by coreyleelarson** [comment]
@jasonnutter We have the post logout redirect ui set both in the PublicClientApplication initialization and the app registration, but no front-channel logout uri configured as we have not implemented that yet.

Any reason why the redirect would work in Chrome incognito but not in a regular window? We also observed that it asks us which account to log out, even though we're passing the `AccountInfo` object with the logout request, and there's only one account to select from.

**Comment by jasonnutter** [comment]
> We have the post logout redirect ui set both in the PublicClientApplication initialization and the app registration, but no front-channel logout uri configured as we have not implemented that yet.

Please try setting a front channel logout (don't worry for now if it doesn't perform anything logout related) and see if it fixes this.

> Any reason why the redirect would work in Chrome incognito but not in a regular window?

Not sure. Are 3p cookies enabled or disabled?

> We also observed that it asks us which account to log out. We're passing the AccountInfo object with logoutRedirect, and there's only one account to select.

This is a known issue, as the service doesn't currently honor the account passed to the MSAL logout API. This will be improved in the future (ETA TBD).

**Comment by coreyleelarson** [comment]
> Please try setting a front channel logout (don't worry for now if it doesn't perform anything logout related) and see if it fixes this.

I tried setting a URL here and observed no change, unfortunately.

**Comment by jasonnutter** [comment]
@coreyleelarson @workingtitledk I've been unable to reproduce the lack of redirection with our Angular 11 sample in Edge and Chrome. Can you please share a Fiddler trace demonstrating this behavior? Email in my profile.

Also, are 3p cookies enabled or disabled in these browsers?

**Comment by Kumar-Aakash** [comment]
I am also facing the exact same issues. My Angular app have redirect flows only for single sign-on. For Google, Apple It is fine but for Microsoft login, I am getting exact same error. Post logout, it should redirect back to the app.

**Comment by jasonnutter** [comment]
@Kumar-Aakash Please confirm you have a front-channel logout uri set, that the post logout redirect uri is also registered as a reply url for your app, and it is configured in MSAL. If you still do not get a post logout redirect, please share a Fiddler (email in profile). Thanks!

**Comment by jasonnutter** [comment]
I'd also be interested if using the `/common` or `/organizations` authority makes a difference.
