### ISSUE TITLE
not possible to force locale 

### ISSUE THREAD

**Issue by kyma** [AzureAD/microsoft-authentication-library-for-js#338]
I can't see a way to pass in the desired locale in methods such as loginRedirect.
Can this be added, or is there a way to force locale using this library?

**Comment by nehaagrawal** [comment]
@kyma  Currently we don't provide the option to configure locale in our library. What is your use  case?

**Comment by kyma** [comment]
I have a website that allow the user to change language. We would like the log in flow to follow the user's choice as it feels odd if it changes when they login/register

**Comment by nehaagrawal** [comment]
@kyma  There is a way to configure locale. I can create PR tomorrow.

**Comment by nehaagrawal** [comment]
@kyma - You can pass locale as extraQueryParameter in  loginRedirect() or loginPopup() APIs. MKT is the parameter name and which takes the LanguageCode-CountryCode format (e.g.: en-US, fr-CA).

` userAgentApplication.loginPopup(applicationConfig.graphScopes, "mkt=fr-CA")`

**Comment by kyma** [comment]
great, thanks I'll try it today

**Comment by kyma** [comment]
this works. Thanks for the fast response. Don't think this is in the documentation though so it'd be great to add it for future users
