### ISSUE TITLE
Integration with OpenTelemetry

### ISSUE THREAD

**Issue by sadasant** [AzureAD/microsoft-authentication-library-for-js#3380]
## Library
- [x] `@azure/msal-browser@2.x.x`
- [x] `@azure/msal-node@1.x.x`

## Description

On the Azure SDKs we use [OpenTelemetry](https://opentelemetry.io/) to increase the observability of our libraries. In our case, we use a telemetry layer we call "@azure/core-tracing" ([link](https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/core/core-tracing)).

This feature request is not blocking us. Consider this issue as a question: Would it make sense for you to eventually add OpenTelemetry support?

Once MSAL integrates with OpenTelemetry (if eventually), we'll be able to link our telemetry span tree into MSAL and the end users would be able to have full observability of the internals.

**IMPORTANT:**
OpenTelemetry hasn't GAd yet, I believe. If you don't mind my super early suggestion, we could keep this issue, but our team doesn't recommend adopting OpenTelemetry until it GAs.

## Source

- [x] Internal (Microsoft)
- [ ] Customer request

**Comment by sameerag** [comment]
Thank you @sadasant for bringing this up. I think it will be useful to add this support to msal-node. However, we need some time to plan for this work. I will keep this feature open until we have an internal item tracking this.

**Comment by sadasant** [comment]
@sameerag Thank you!

**Comment by jasonnutter** [comment]
@sadasant What is the scope of telemetry you are interested in? Just http requests, or everything in MSAL? If just interested in http requests, you can implement your own network client via [system.networkClient](https://azuread.github.io/microsoft-authentication-library-for-js/ref/modules/_azure_msal_browser.html#browsersystemoptions).

**Comment by sameerag** [comment]
@sadasant As discussed offline, added an internal tracker and tagged you. Closing this.
