### ISSUE TITLE
Is it possible to update browser cache after updating account details?

### ISSUE THREAD

**Issue by badsyntax** [AzureAD/microsoft-authentication-library-for-js#3381]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [x] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [ ] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Description

Hi there. I'm providing a form to allow users to update their profile data without leaving the app (SPA). The form posts data via `fetch` to an API which is turn calls the graph API to update (patch) the user account (eg givenName, surname, and some custom attributes.)

This works great, but after successfully patching the user account, if I refresh the page, the msal library still has the old id claims in cache.

I need to update the browser cache to reflect the updated data. Is there an API I can use to do this?

## Source

- [ ] Internal (Microsoft)
- [x] Customer request

**Comment by sameerag** [comment]
@badsyntax This would need a network call to update the msal cache in your browser. Can you please try calling`acquireTokenSilent` with `forceRefresh:true` and let us know if it updates the tokens as needed (and therefore the cache)?

**Comment by badsyntax** [comment]
@sameerag thanks for the suggestion.

I'm now calling `acquireTokenSilent` using the same scopes as login, and using the current signed in account. I can see the network request being sent to the token endpoint, but the `id_token` in the response still does not have my updated claims.  Btw i'm using Azure B2C and this is the token endpoint it calls: `https://tenant.b2clogin.com/tenant.onmicrosoft.com/b2c_1_signupsignin1/oauth2/v2.0/token`

Here's the code i'm using:

```ts
const userAccount = msal.getAllAccounts()[0];
await authClient.acquireTokenSilent({
  scopes: loginRequest.scopes,
  forceRefresh: true,
  account: userAccount,
});
```

Is this the correct api usage?

Do you know why does the token endpoint not give me a fresh id token claims object? 

From my various testing, it seems the only way to get Azure to refresh id token claims, is to log the user out and ask them to log back in, and if that's the case I will need to redesign our entire login flow :(

**Comment by jasonnutter** [comment]
@badsyntax That is correct syntax. 

@nickgmicrosoft @ktsakas Is it expected that ID token claims won't be updated until the user initiates a new session (i.e. logout or login)?
