### ISSUE TITLE
httpactioncontext identity name is null for msal 2.0 authentication for code flow

### ISSUE THREAD

**Issue by RomaRathi** [AzureAD/microsoft-authentication-library-for-js#3382]
## Library

- [ ] `msal@1.x.x` or `@azure/msal@1.x.x`
- [x] `@azure/msal-browser@2.x.x`
- [ ] `@azure/msal-node@1.x.x`
- [ ] `@azure/msal-react@1.x.x`
- [ ] `@azure/msal-angular@0.x.x`
- [ ] `@azure/msal-angular@1.x.x`
- [x] `@azure/msal-angular@2.x.x`
- [ ] `@azure/msal-angularjs@1.x.x`

## Source

- [ ] Internal (Microsoft)
- [ ] Customer request

**Comment by RomaRathi** [comment]
var isAuthorized = base.IsAuthorized(actionContext);
It always returns false while doing SPA authorization without implicit code flow (MSAL).
With adal library it was returning true.
It was unable to fetch the user in the principal.identity.

**Comment by RomaRathi** [comment]
Is there some other configuration to set in AzureAD or frontend angular 11?
It is adding the access token in the header of API call but while proceeding to backend it fails the authentication as the var isAuthorized = base.IsAuthorized(actionContext) is false.

**Comment by sameerag** [comment]
@RomaRathi This code looks like ASP.net backend, can you please give us more details about your use case? We would need:

* Sample code
* Expected scenario
* Steps to reproduce

The description above is not enough for us to parse the problem.

**Comment by RomaRathi** [comment]
[Frontend code to append token.docx](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/6259180/Frontend.code.to.append.token.docx)
@sameerag

**Comment by RomaRathi** [comment]
Resolved.
By setting the correct audience.
