### ISSUE TITLE
jwt verification checks token signature against public key returned in kid

### ISSUE THREAD

**Issue by ericprocop** [AzureAD/microsoft-authentication-library-for-js#3389]
Using 4.0.0 implicit flow.  I don't see an easy way for me to obtain the public key to check against the list maintained at login.microsoftonline.com/common/.well-known/openid-configuration.  Actually, I feel that should be done as a matter of course.

**Comment by pkanher617** [comment]
@ericprocop I'm not sure I understand the question, could you clarify? Are you asking for a way to validate a specific key against the jwks? The passport library should be validating the id_token against the keyset from the jwks_uri.

**Comment by jo-arroyo** [comment]
No further activity on this issue. Passport-azure-ad is now in maintenance and all future middleware scenarios will be build on top of msal-node. Please watch msal-node for updates. Closing.
