### ISSUE TITLE
Redirect after login by using the state parameter

### ISSUE THREAD

**Issue by enerdgumen** [AzureAD/microsoft-authentication-library-for-js#3390]
I would use the "state" parameter supported by the [authorize](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc#send-the-sign-in-request) endpoint to keep the url originnally requested before the initial redirect to the authentication provider.

Then after the login, in the callback endpoint, I would read the state to perform the final redirect.

I've seen a configurable `customState` in the `authenticate` method, but it does not seem exposed by the library, so I cannot figure out how to complete the flow.

Have you some suggestion about it?

Thanks.

---
Version: 4.0.0

**Comment by pkanher617** [comment]
This is something we will take a look at in the new version of the middleware library that we are designing.

**Comment by jo-arroyo** [comment]
We are working on middleware scenarios that will be built on top of msal-node, which will support using state. Keep an eye out for future msal-node updates. Closing as no issue activity.
