### ISSUE TITLE
Inconsistent override capability between OIDCStrategy and BearerStrategy

### ISSUE THREAD

**Issue by przemos** [AzureAD/microsoft-authentication-library-for-js#3391]
In OIDCStrategy one can override a couple of important strategy properties such as client id, client secret, redirect url and so forth in passport.authenticate() call through options. This is very important if one needs to apply strategies dynamically on a request basis.

BearerStrategy does not allow to override it in such a way which makes the whole approach inconsistent.

**Comment by pkanher617** [comment]
@przemos The OIDCStrategy and BearerStrategy are meant for different scenarios, which is why they have different configurations, but I agree that we should be allowing for override of key options. We will address this in the new version of the middleware library.

**Comment by jo-arroyo** [comment]
We are working on middleware scenarios that will be built on top of msal-node, and will keep this issue in mind. Closing as no issue activity.
