### ISSUE TITLE
authentication failed due to: In setOptions: Unable to fetch metadata

### ISSUE THREAD

**Issue by nonongodup** [AzureAD/microsoft-authentication-library-for-js#3392]
I am running behind company proxy. After i added some proxy for http call, i am getting this when tried to call login authentication. Before adding proxy, i was getting connectiontimeout when without VPN and econnrefused when using corporate VPN. Not sure what is the issue.

**Comment by jo-arroyo** [comment]
Closing as no issue activity. Passport-azure-ad is now in maintenance, and future middleware scenarios will be built on msal-node.
