### ISSUE TITLE
acquireTokenSilent method is not fetching the token from cache (localStorage) . As a result multiple token requests are triggered on page load impacting the over all application performance.

### ISSUE THREAD

**Issue by johnvittneyk** [AzureAD/microsoft-authentication-library-for-js#3394]
### Core Library

@azure/msal-browser

### Core Library Version

2.11.2

### Wrapper Library

Not Applicable

### Wrapper Library Version

2.11.2

### Description

MSAL caches a token after it's been acquired.  Application code should first try to get a token silently from the cache before attempting to acquire a token by other means.

But in our case, this is failing and directly acquiring token every time, hence impacting the performance of the application.

This is the method used in the Application:
/**
     * Silently acquire an access token for a given set of scopes. Will use cached token if available, otherwise will attempt to acquire a new token from the network via refresh token.
     *
     * @param {@link (SilentRequest:type)}
     * @returns {Promise.<AuthenticationResult>} - a promise that is fulfilled when this function has completed, or rejected if an error was raised. Returns the {@link AuthResponse} object
     */
    acquireTokenSilent(request: SilentRequest): Promise<AuthenticationResult>;

### Error Message

No Error Message

### Msal Logs

NA

### MSAL Configuration

```javascript
const msalConfig = {
	auth: {
		authority: `https://login.microsoftonline.com/microsoft.onmicrosoft.com`,
		clientId: config.default.AppSettings.msalClientId,
		redirectUri: loc
	},
	cache: {
		cacheLocation: 'localStorage',
		storeAuthStateInCookie: false
	}
};
```

### Relevant Code Snippets

```javascript
constructor(wpContext: any, AuthContextCallback?: any, username?: any, isLogin?: boolean) {
		this.httpClient = wpContext.httpClient;
		this.userName = username;
		this.myMSALObj = new PublicClientApplication(msalConfig);
	}

	public async Authenticate(isLogin?: boolean) {
		await this.myMSALObj
			.handleRedirectPromise()
			.then(async (tokenResponse) => {
				if (tokenResponse !== null) {
					this.accessTokenCommon = tokenResponse.accessToken;
				} else {
					if (isLogin) {
						await this.loginForAccessTokenByMSAL();
					} else {
						const currentAccounts = this.myMSALObj.getAllAccounts();
						await this.handleLoggedInUser(currentAccounts);
					}
				}
			})
			.catch((error) => {
				return null;
			});
	}

public GetCustomWebAPI(apiSource: APISource, apiRelativePath: string, jsonbody: string = null): Promise<any> {
		return new Promise<any>((resolve: (result: any) => void, reject: (error: any) => void): void => {
			this.getCustomAPIAccessToken(apiSource).then(
				async (accessToken: string): Promise<void> => {
					let fullAPIUrl: string;
					const requestHeaders: Headers = new Headers();
					requestHeaders.append('Authorization', 'Bearer ' + accessToken);
					requestHeaders.append('Content-type', 'application/json');
					const httpClientOptions: IHttpClientOptions = {
						body: jsonbody,
						headers: requestHeaders
					};
					try {
						if (apiSource == APISource.MSGraph) fullAPIUrl = apiSource + '/' + apiRelativePath;
						else fullAPIUrl = this.getAPIBaseURL(apiSource) + apiRelativePath;
						const response = await this.httpClient.get(
							fullAPIUrl,
							HttpClient.configurations.v1,
							httpClientOptions
						);
						const output = await response.json();
						resolve(output);
					} catch (error) {
						reject(error);
					}
				},
				(error: any): void => {
					reject('token error' + error);
				}
			);
		});
	}

private async fetchAccessTokenByScopeMSAL(specificScope: any): Promise<string> {
		const accessTokenRequest = {
			scopes: specificScope,
			account: this.myMSALObj.getAccountByUsername(this.userName)
		};
		this.ssoRequest.loginHint = this.userName;
		this.ssoRequest.scopes = specificScope;
		return this.myMSALObj
			.acquireTokenSilent(accessTokenRequest)
			.then((response) => {
				return response.accessToken;
			})
			.catch((silentError) => {
				if (silentError instanceof InteractionRequiredAuthError) {
					return this.myMSALObj
						.loginPopup()
						.then((response) => {
							return response.accessToken;
						})
						.catch((popupError) => {
							if (popupError.message.indexOf('popup_window_error') > -1) {
								// Popups are blocked
								return this.redirectLogin(this.ssoRequest);
							}
						});
				} else {
					return null;
				}
			});
	}

private getCustomAPIAccessToken(apiSource: APISource): Promise<string> {
		return new Promise<
			string
		>(async (resolve: (accessToken: string) => void, reject: (error: any) => void): Promise<void> => {
			try {
				var accessToken = null;

				accessToken = await this.fetchAccessTokenByScopeMSAL(allScopes.customAPIScopes);
				if (accessToken) {
					resolve(accessToken);
				} else {
					reject("Couldn't retrieve access token");
				}
			} catch (ex) {
				reject(ex);
			}
		});
	}
```

### Reproduction Steps

1. Build an SPFx Webpart Solution with MSAL authentication.
2. Initiate multiple custom api calls on page login, this triggers multiple calls to fetch tokens for each custom webapi.

### Expected Behavior

MSAL caches a token after it's been acquired. Your application code should first try to get a token silently from the cache before attempting to acquire a token by other means.

### Identity Provider

Other

### Browsers Affected (Select all that apply)

Edge

### Regression

@azure/msal-browser 2.11.2

### Source

Internal (Microsoft)

Kindly help us in resolving this issue

**Comment by jasonnutter** [comment]
@johnvittneyk Please capture and share logs from MSAL, as that will help us debug this issue. 

Also, please see if you can reproduce this issue with one of our samples, if possible.

**Comment by alinbujor** [comment]
I also have this issue, we have an Angular 10 App, we use the MSALInterceptorConfigFactory to automatically add the token to all our requests. And the MsalGuard to protect our routes. The loginRedirect is triggered by the guard. We don't have a login button. The login works fine, but after that for each request to our API a request for the token is made.

I read lots of posts regarding this issue and I'm not sure if it's an issue with the scopes. We have a custom API and we don't have a custom scope for it (don't know if we should have). For the scope we just send the client Id.

I also did a test on the Angular 11 B2C Sample. If you change the scope from 'https://fabrikamb2c.onmicrosoft.com/helloapi/demo.read' and replace it with the client id then a request for the token will be made for each API call.
<img width="750" alt="Screenshot 2021-04-21 at 13 48 27" src="https://user-images.githubusercontent.com/16489857/115542345-dbc10e80-a2a8-11eb-9765-8296486d3e9f.png">
<img width="736" alt="Screenshot 2021-04-21 at 13 46 57" src="https://user-images.githubusercontent.com/16489857/115542358-de236880-a2a8-11eb-8b9d-e42702d7d49f.png">



Here are some screenshots with the logs.

**Comment by johnvittneyk** [comment]
I upgraded my package to latest version and it solved the issue.
