### ISSUE TITLE
acquireTokenSilent unable to renew token (idToken) after certain time

### ISSUE THREAD

**Issue by AyaanRanosys** [AzureAD/microsoft-authentication-library-for-js#3395]
### Core Library

@azure/msal or msal

### Core Library Version

1.4.6

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

We are trying to renew idToken just before (x minutes) it get expired. We are able to perform the renew token operation by using acquireTokenSilent method. But it's start failing after a certain time (20-23 minutes approx) and application were unable to renew the token after it. Only possible option left is the interactive way to update the token by forcing user to get log in again which is working as expected.

### Error Message

AADB2C90077: User does not have an existing session and request prompt parameter has a value of 'None'.
Correlation ID: f8259bb8-79a6-416c-83d5-fb8f66346311
Timestamp: 2021-04-06 10:39:20Z

### Msal Logs

[MSAL] Tue, 06 Apr 2021 10:39:13 GMT:1.4.6-Verbose AcquireTokenSilent has been called
[MSAL] Tue, 06 Apr 2021 10:39:13 GMT:1.4.6-Verbose Telemetry Event started: f4b33bfd-246b-48d1-ae99-640128856776_d9de98b7-ba66-408a-8eef-c8a37379cd80-msal.api_event
[MSAL] Tue, 06 Apr 2021 10:39:13 GMT:1.4.6-Verbose-pii Serialized scopes: openid profile
[MSAL] Tue, 06 Apr 2021 10:39:13 GMT:1.4.6-Verbose Account set from MSAL Cache
[MSAL] Tue, 06 Apr 2021 10:39:13 GMT:1.4.6-Verbose Response type: id_token
[MSAL] Tue, 06 Apr 2021 10:39:13 GMT:1.4.6-Verbose Finished building server authentication request
[MSAL] Tue, 06 Apr 2021 10:39:13 GMT:1.4.6-Verbose Query parameters populated from existing SSO or account
[MSAL] Tue, 06 Apr 2021 10:39:13 GMT:1.4.6-Verbose Skipped cache lookup since request.forceRefresh option was set to true
[MSAL] Tue, 06 Apr 2021 10:39:13 GMT:1.4.6-Verbose-pii Authority instance: https://custom-domain/masked.onmicrosoft.com/masked/
[MSAL] Tue, 06 Apr 2021 10:39:13 GMT:1.4.6-Verbose Cached metadata found for authority
[MSAL] Tue, 06 Apr 2021 10:39:13 GMT:1.4.6-Verbose OpenID Connect scopes only, renewing idToken
[MSAL] Tue, 06 Apr 2021 10:39:13 GMT:1.4.6-Info RenewIdToken has been called
[MSAL] Tue, 06 Apr 2021 10:39:13 GMT:1.4.6-Info-pii Add msal frame to document:msalIdTokenFrame|openid profile|undefined
[MSAL] Tue, 06 Apr 2021 10:39:13 GMT:1.4.6-Verbose RenewIdToken expected state: eyJpZCI6IjA4YmNmOTE3LTViOWUtNDMyYi1iMjcxLTZlN2UxZGIyMDFmZCIsInRzIjoxNjE3NzA1NTU0LCJtZXRob2QiOiJzaWxlbnRJbnRlcmFjdGlvbiJ9
[MSAL] Tue, 06 Apr 2021 10:39:13 GMT:1.4.6-Verbose Silent login is true, set silentAuthenticationState
[MSAL] Tue, 06 Apr 2021 10:39:13 GMT:1.4.6-Info-pii Navigate to:" https://custom-domain/masked.onmicrosoft.com/masked/oauth2/v2.0/authorize?response_type=id_token&scope=openid%20profile&client_id=<client_id>&redirect_uri=http%3A%2F%2Flocalhost%3A8081%2Fauth.html&state=eyJpZCI6IjA4YmNmOTE3LTViOWUtNDMyYi1iMjcxLTZlN2UxZGIyMDFmZCIsInRzIjoxNjE3NzA1NTU0LCJtZXRob2QiOiJzaWxlbnRJbnRlcmFjdGlvbiJ9&nonce=00882293-088d-4bef-ae0f-3af93bb02f0c&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=msal&sessionId=48742313-96c0-11eb-a4f1-ab7fd645b7c9&client-request-id=f4b33bfd-246b-48d1-ae99-640128856776&prompt=none&response_mode=fragment
[MSAL] Tue, 06 Apr 2021 10:39:13 GMT:1.4.6-Verbose-pii Set loading state to pending for: openid profile|undefined:eyJpZCI6IjA4YmNmOTE3LTViOWUtNDMyYi1iMjcxLTZlN2UxZGIyMDFmZCIsInRzIjoxNjE3NzA1NTU0LCJtZXRob2QiOiJzaWxlbnRJbnRlcmFjdGlvbiJ9
[MSAL] Tue, 06 Apr 2021 10:39:13 GMT:1.4.6-Info-pii LoadFrame: msalIdTokenFrame|openid profile|undefined
[MSAL] Tue, 06 Apr 2021 10:39:14 GMT:1.4.6-Info-pii Add msal frame to document:msalIdTokenFrame|openid profile|undefined
[MSAL] Tue, 06 Apr 2021 10:39:14 GMT:1.4.6-Info-pii Frame Name : msalIdTokenFrame|openid profile|undefined Navigated to: https://custom-domain/masked.onmicrosoft.com/masked/oauth2/v2.0/authorize?response_type=id_token&scope=openid%20profile&client_id=<client_id>&redirect_uri=http%3A%2F%2Flocalhost%3A8081%2Fauth.html&state=eyJpZCI6IjA4YmNmOTE3LTViOWUtNDMyYi1iMjcxLTZlN2UxZGIyMDFmZCIsInRzIjoxNjE3NzA1NTU0LCJtZXRob2QiOiJzaWxlbnRJbnRlcmFjdGlvbiJ9&nonce=00882293-088d-4bef-ae0f-3af93bb02f0c&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=msal&sessionId=48742313-96c0-11eb-a4f1-ab7fd645b7c9&client-request-id=f4b33bfd-246b-48d1-ae99-640128856776&prompt=none&response_mode=fragment
[MSAL] Tue, 06 Apr 2021 10:39:14 GMT:1.4.6-Verbose monitorWindowForIframe polling started
[MSAL] Tue, 06 Apr 2021 10:39:16 GMT:1.4.6-Verbose monitorIframeForHash found url in hash
[MSAL] Tue, 06 Apr 2021 10:39:16 GMT:1.4.6-Verbose HandleAuthenticationResponse has been called
[MSAL] Tue, 06 Apr 2021 10:39:16 GMT:1.4.6-Verbose GetResponseState has been called
[MSAL] Tue, 06 Apr 2021 10:39:16 GMT:1.4.6-Verbose Hash contains state. Creating stateInfo object
[MSAL] Tue, 06 Apr 2021 10:39:16 GMT:1.4.6-Verbose State matches cached state, setting requestType to login
[MSAL] Tue, 06 Apr 2021 10:39:16 GMT:1.4.6-Verbose Obtained state from response
[MSAL] Tue, 06 Apr 2021 10:39:16 GMT:1.4.6-Info ProcessCallBack has been called. Processing callback from redirect response
[MSAL] Tue, 06 Apr 2021 10:39:16 GMT:1.4.6-Verbose SaveTokenFromHash has been called
[MSAL] Tue, 06 Apr 2021 10:39:16 GMT:1.4.6-Info State status: true; Request type: LOGIN
[MSAL] Tue, 06 Apr 2021 10:39:16 GMT:1.4.6-Verbose Server returned an error
[MSAL] Tue, 06 Apr 2021 10:39:16 GMT:1.4.6-Info-pii Error : interaction_required; Error description: AADB2C90077: User does not have an existing session and request prompt parameter has a value of 'None'.
Correlation ID: f8259bb8-79a6-416c-83d5-fb8f66346311
Timestamp: 2021-04-06 10:39:20Z

[MSAL] Tue, 06 Apr 2021 10:39:16 GMT:1.4.6-Verbose RequestType is login, caching login error, generating authorityKey
[MSAL] Tue, 06 Apr 2021 10:39:16 GMT:1.4.6-Verbose Status set to complete, temporary cache cleared
[MSAL] Tue, 06 Apr 2021 10:39:16 GMT:1.4.6-Verbose Calling callback provided to processCallback
[MSAL] Tue, 06 Apr 2021 10:39:16 GMT:1.4.6-Verbose Telemetry Event stopped: f4b33bfd-246b-48d1-ae99-640128856776_d9de98b7-ba66-408a-8eef-c8a37379cd80-msal.api_event
[MSAL] Tue, 06 Apr 2021 10:39:16 GMT:1.4.6-Verbose Flushing telemetry events: f4b33bfd-246b-48d1-ae99-640128856776

### MSAL Configuration

```javascript
{
    auth: {
      authority: AUTHORITY_SIGN_IN,
      clientId: CLIENT_ID,
      redirectUri: window.location.origin + "/auth/redirect",
      validateAuthority: false,
    },
    system: {
      tokenRenewalOffsetSeconds: 10,
    },
    cache: {
      cacheLocation: typeof window !== "undefined" && localStorage ? "localStorage" : false,
      storeAuthStateInCookie: false,
    }
}
```

### Relevant Code Snippets

```javascript
import { authProvider } from "./auth-provider"; 

const Config = Object.freeze({
  auth: {
    msal: {
      authority: AUTHORITY_SIGN_IN,
      authoritySignup: AUTHORITY_SIGN_UP,
      clientId: CLIENT_ID,

      redirectUri: window.location.origin + "/auth/redirect",
      tokenRefreshUri: window.location.origin + "/auth.html",
      postLogoutRedirectUri: window.location.origin + "/auth/logout/",
      scopes: ["openid"],
      tokenRenewalOffsetSeconds: 10,
      validateAuthority: false,
      cacheLocation:
        typeof window !== "undefined" && localStorage ? "localStorage" : false, 
      storeAuthStateInCookie: false,
    },
  },
}); 

const refreshToken = () => {
  const { clientId, tokenRefreshUri } = Config?.auth?.msal || {};

  const params = {
    forceRefresh: true,
    scopes: [clientId],
    redirectUri: tokenRefreshUri,
  };

  try {
    authProvider
      .acquireTokenSilent(params)
      .then((response) => {
        // handle success case 
      })
      .catch((error) => {
        console.error(error);
      });
  } catch (error) {
    console.error(error);
  }
};
```

### Reproduction Steps

1. Configure idToken expiration time to 5 or 10 minutes (Something smaller to test)
2. Get Logged in  
3. Start renewing the token in every X minutes (says few minutes before it get expired - I am doing it 4 minutes before expiry)
4. Verify if token get renewed
5. Keep verifying it form 30 minutes.
6. Notice if there is any error in the console 
(In our case for idToken, we have configured idToken expiry to 5 minutes and after 20-23 minutes and some seconds the error starts coming and interactive way is required to update the token by force user to log in again) 

### Expected Behavior

idToken should keep getting renewed forever if it's been renewed before expiry using acquireTokenSilent 

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by sameerag** [comment]
@AyaanRanosys This error:

> [MSAL] Tue, 06 Apr 2021 10:39:16 GMT:1.4.6-Verbose Server returned an error
> [MSAL] Tue, 06 Apr 2021 10:39:16 GMT:1.4.6-Info-pii Error : interaction_required; Error description: AADB2C90077: User does not have an existing session and request prompt parameter has a value of 'None'.
Correlation ID: f8259bb8-79a6-416c-83d5-fb8f66346311
Timestamp: 2021-04-06 10:39:20Z

would mean that the Server returned this error. We, as the client library, throw the error back to the user as is. This happens if the server session is expired and MSAL JS cannot ideally control it. 

I also see a couple logs that may indicate you are always trying to go to the network always:
> [MSAL] Tue, 06 Apr 2021 10:39:13 GMT:1.4.6-Verbose Query parameters populated from existing SSO or account
> [MSAL] Tue, 06 Apr 2021 10:39:13 GMT:1.4.6-Verbose Skipped cache lookup since request.forceRefresh option was set to true

Can you turn `forceRefresh: off` and see if it helps? Ideally we look into the cache until we have ~5mins to expiry and then silently fetch the token for you from the network if needed.

Note: Is it possible for you to migrate to MSAL V2? We recommend all our users to use the latest version of our library. The migration guidance is available [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/migrate-spa-implicit-to-auth-code)

**Comment by AyaanRanosys** [comment]
Let me try with `forceRefresh: off`, I will update you further over it. 

> Is it possible for you to migrate to MSAL V2? We recommend all our users to use the latest version of our library.

It is not possible to migrate to v2 at the moment. The application is in React, we are waiting for [@azure/msal-react](https://www.npmjs.com/package/@azure/msal-react) stable release. We will migrate to it once it's production ready as it's based on v2.

**Comment by AyaanRanosys** [comment]
I have tried using `forceRefresh: off` but still facing the same error after approximately same interval of time. 

**Following are the new logs:**
[MSAL] Wed, 07 Apr 2021 05:09:06 GMT:1.4.6-Verbose AcquireTokenSilent has been called
[MSAL] Wed, 07 Apr 2021 05:09:06 GMT:1.4.6-Verbose Telemetry Event started: d6e23176-7708-4274-a851-8e5948991c22_4643305c-66c3-4fad-8571-c130b29bbfb7-msal.api_event
[MSAL] Wed, 07 Apr 2021 05:09:06 GMT:1.4.6-Verbose-pii Serialized scopes: openid profile
[MSAL] Wed, 07 Apr 2021 05:09:06 GMT:1.4.6-Verbose Account set from MSAL Cache
[MSAL] Wed, 07 Apr 2021 05:09:06 GMT:1.4.6-Verbose Response type: id_token
[MSAL] Wed, 07 Apr 2021 05:09:06 GMT:1.4.6-Verbose Finished building server authentication request
[MSAL] Wed, 07 Apr 2021 05:09:06 GMT:1.4.6-Verbose Query parameters populated from existing SSO or account
[MSAL] Wed, 07 Apr 2021 05:09:06 GMT:1.4.6-Verbose GetCachedToken has been called
[MSAL] Wed, 07 Apr 2021 05:09:06 GMT:1.4.6-Verbose Getting all cached tokens of type ID Token
[MSAL] Wed, 07 Apr 2021 05:09:06 GMT:1.4.6-Verbose No matching tokens of type id_token found
[MSAL] Wed, 07 Apr 2021 05:09:06 GMT:1.4.6-Verbose No tokens found
[MSAL] Wed, 07 Apr 2021 05:09:06 GMT:1.4.6-Verbose Getting all cached tokens of type Access Token
[MSAL] Wed, 07 Apr 2021 05:09:06 GMT:1.4.6-Verbose No matching tokens of type access_token found
[MSAL] Wed, 07 Apr 2021 05:09:06 GMT:1.4.6-Verbose No matching token found when filtering by scope and authority
[MSAL] Wed, 07 Apr 2021 05:09:06 GMT:1.4.6-Verbose GetUniqueAuthority has been called
[MSAL] Wed, 07 Apr 2021 05:09:06 GMT:1.4.6-Verbose Single authority used, setting authorityInstance
[MSAL] Wed, 07 Apr 2021 05:09:06 GMT:1.4.6-Verbose No valid token found in cache lookup
[MSAL] Wed, 07 Apr 2021 05:09:06 GMT:1.4.6-Verbose-pii Authority instance: https://custom-domain/masked.onmicrosoft.com/masked/
[MSAL] Wed, 07 Apr 2021 05:09:06 GMT:1.4.6-Verbose Cached metadata found for authority
[MSAL] Wed, 07 Apr 2021 05:09:06 GMT:1.4.6-Verbose OpenID Connect scopes only, renewing idToken
[MSAL] Wed, 07 Apr 2021 05:09:06 GMT:1.4.6-Info RenewIdToken has been called
[MSAL] Wed, 07 Apr 2021 05:09:06 GMT:1.4.6-Info-pii Add msal frame to document:msalIdTokenFrame|openid profile|undefined
[MSAL] Wed, 07 Apr 2021 05:09:06 GMT:1.4.6-Verbose RenewIdToken expected state: eyJpZCI6ImVhMWE1OTRkLWEwMjAtNGU1OS1iZTZjLTA4Y2NmOGQ2NDJkMyIsInRzIjoxNjE3NzcyMTQ3LCJtZXRob2QiOiJzaWxlbnRJbnRlcmFjdGlvbiJ9
[MSAL] Wed, 07 Apr 2021 05:09:06 GMT:1.4.6-Verbose Silent login is true, set silentAuthenticationState
[MSAL] Wed, 07 Apr 2021 05:09:06 GMT:1.4.6-Info-pii Navigate to:" https://custom-domain/masked.onmicrosoft.com/masked/oauth2/v2.0/authorize?response_type=id_token&scope=openid%20profile&client_id=client_id&redirect_uri=http%3A%2F%2Flocalhost%3A8081%2Fauth.html&state=eyJpZCI6ImVhMWE1OTRkLWEwMjAtNGU1OS1iZTZjLTA4Y2NmOGQ2NDJkMyIsInRzIjoxNjE3NzcyMTQ3LCJtZXRob2QiOiJzaWxlbnRJbnRlcmFjdGlvbiJ9&nonce=614e369e-2fec-4be2-93da-f013fd5e1ed4&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=msal&sessionId=425e5aa4-975b-11eb-a4f1-f57a6641833a&client-request-id=d6e23176-7708-4274-a851-8e5948991c22&prompt=none&response_mode=fragment
[MSAL] Wed, 07 Apr 2021 05:09:06 GMT:1.4.6-Verbose-pii Set loading state to pending for: openid profile|undefined:eyJpZCI6ImVhMWE1OTRkLWEwMjAtNGU1OS1iZTZjLTA4Y2NmOGQ2NDJkMyIsInRzIjoxNjE3NzcyMTQ3LCJtZXRob2QiOiJzaWxlbnRJbnRlcmFjdGlvbiJ9
[MSAL] Wed, 07 Apr 2021 05:09:06 GMT:1.4.6-Info-pii LoadFrame: msalIdTokenFrame|openid profile|undefined
[MSAL] Wed, 07 Apr 2021 05:09:07 GMT:1.4.6-Info-pii Add msal frame to document:msalIdTokenFrame|openid profile|undefined
[MSAL] Wed, 07 Apr 2021 05:09:07 GMT:1.4.6-Info-pii Frame Name : msalIdTokenFrame|openid profile|undefined Navigated to: https://custom-domain/masked.onmicrosoft.com/masked/oauth2/v2.0/authorize?response_type=id_token&scope=openid%20profile&client_id=client_id&redirect_uri=http%3A%2F%2Flocalhost%3A8081%2Fauth.html&state=eyJpZCI6ImVhMWE1OTRkLWEwMjAtNGU1OS1iZTZjLTA4Y2NmOGQ2NDJkMyIsInRzIjoxNjE3NzcyMTQ3LCJtZXRob2QiOiJzaWxlbnRJbnRlcmFjdGlvbiJ9&nonce=614e369e-2fec-4be2-93da-f013fd5e1ed4&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=msal&sessionId=425e5aa4-975b-11eb-a4f1-f57a6641833a&client-request-id=d6e23176-7708-4274-a851-8e5948991c22&prompt=none&response_mode=fragment
[MSAL] Wed, 07 Apr 2021 05:09:07 GMT:1.4.6-Verbose monitorWindowForIframe polling started
[MSAL] Wed, 07 Apr 2021 05:09:08 GMT:1.4.6-Verbose monitorIframeForHash found url in hash
[MSAL] Wed, 07 Apr 2021 05:09:08 GMT:1.4.6-Verbose HandleAuthenticationResponse has been called
[MSAL] Wed, 07 Apr 2021 05:09:08 GMT:1.4.6-Verbose GetResponseState has been called
[MSAL] Wed, 07 Apr 2021 05:09:08 GMT:1.4.6-Verbose Hash contains state. Creating stateInfo object
[MSAL] Wed, 07 Apr 2021 05:09:08 GMT:1.4.6-Verbose State matches cached state, setting requestType to login
[MSAL] Wed, 07 Apr 2021 05:09:08 GMT:1.4.6-Verbose Obtained state from response
[MSAL] Wed, 07 Apr 2021 05:09:08 GMT:1.4.6-Info ProcessCallBack has been called. Processing callback from redirect response
[MSAL] Wed, 07 Apr 2021 05:09:08 GMT:1.4.6-Verbose SaveTokenFromHash has been called
[MSAL] Wed, 07 Apr 2021 05:09:08 GMT:1.4.6-Info State status: true; Request type: LOGIN
[MSAL] Wed, 07 Apr 2021 05:09:08 GMT:1.4.6-Verbose Server returned an error
[MSAL] Wed, 07 Apr 2021 05:09:08 GMT:1.4.6-Info-pii Error : interaction_required; Error description: AADB2C90077: User does not have an existing session and request prompt parameter has a value of 'None'.
Correlation ID: 80cf5597-e9cb-4654-a2e3-caf12ad5154c
Timestamp: 2021-04-07 05:09:12Z

[MSAL] Wed, 07 Apr 2021 05:09:08 GMT:1.4.6-Verbose RequestType is login, caching login error, generating authorityKey
[MSAL] Wed, 07 Apr 2021 05:09:08 GMT:1.4.6-Verbose Status set to complete, temporary cache cleared
[MSAL] Wed, 07 Apr 2021 05:09:08 GMT:1.4.6-Verbose Calling callback provided to processCallback
[MSAL] Wed, 07 Apr 2021 05:09:08 GMT:1.4.6-Verbose Telemetry Event stopped: d6e23176-7708-4274-a851-8e5948991c22_4643305c-66c3-4fad-8571-c130b29bbfb7-msal.api_event
[MSAL] Wed, 07 Apr 2021 05:09:08 GMT:1.4.6-Verbose Flushing telemetry events: d6e23176-7708-4274-a851-8e5948991c22

**Comment by AyaanRanosys** [comment]
@sameerag 

Any update here?

Let me know if you need anything from my side. Thanks.

**Comment by jasonnutter** [comment]
@AyaanRanosys First, `forceRefresh` should be set to `false` (or not included), not `off`. Second, if you receive that error, it means the user no longer has an active session, and your app needs to perform interaction to resolve.

Third, we do not recommend proactively renewing tokens, as it introduces complexity into your application and can result in problems, such as the issue you describe here. Our recommended best practice is to invoke `acquireTokenSilent` right before you need a token, and reactively handle errors, such as the `interaction_required` error you are getting here.

**Comment by AyaanRanosys** [comment]
@jasonnutter 

Thanks for the response.

My comments are as follows:
>forceRefresh should be set to false (or not included), not off. 

I did used `forceRefresh: false` not `forceRefresh: off `, Just replied in the same terminology as @sameerag 

 
> if you receive that error, it means the user no longer has an active session, and your app needs to perform interaction to resolve.

I totally get that thanks, but just want to know how user session is getting expired (or Session going inactive) even when user/app has requested for token and has successfully renewed it just a few minutes ago. 

Is there any limit or rule or something that I am missing to notice? 

Isn't renew token operation supposed to prevent user session from getting expired?

Kindly help me understand. Thanks. 


> we do not recommend proactively renewing tokens, as it introduces complexity into your application and can result in problems, such as the issue you describe here. Our recommended best practice is to invoke acquireTokenSilent right before you need a token, and reactively handle errors, such as the interaction_required error you are getting here.

Thanks for letting me know the best practice. We actually has that mechanism build with the application as well. The proactive renew token mechanism were introduced to avoid user session from being expired in case user actively using the application. I can think about removing it as you said if it's not recommended but I am suspecting same behavior (User session expired after 20-23 minutes) from the other recommended mechanism (invoke acquireTokenSilent right before you need a token) as in both cases we will be calling the same method. 

I am going to let my application work with only recommended way by disabling the proactive renew token mechanism and update you if I am noticing the same issue/behavior with it or not. I will update you further over it. Thanks again.

**Comment by AyaanRanosys** [comment]
@jasonnutter 

Waiting for your response here. Thanks.

**Comment by AyaanRanosys** [comment]
@jasonnutter 

Any update here?

Thanks.

**Comment by hectormmg** [comment]
Hi @AyaanRanosys .

I've gone over your issue and I can't see anything wrong with your `msal` usage here. Here's the link to [Configure Azure AD B2C session behavior](https://docs.microsoft.com/en-us/azure/active-directory-b2c/session-behavior?pivots=b2c-user-flow#configure-azure-ad-b2c-session-behavior). There's a lot of information there on how you can configure your application to handle session lifetimes.

If you are able to silently refresh ID tokens for 20-23 minutes consistently, it seems like the session lifetime must be configured to about 20 minutes for your application.

Please make sure you have the right configuration there and let me know if that solves your issue. Thanks!

**Comment by AyaanRanosys** [comment]
Hi @hectormmg 

Thanks for your response.

The link you have provided to understand Azure AD B2C session behavior configuration has really helped me to understand the required configuration. I  am able to resolve the issue after going through the same. I was using wrong **SessionExpiryType** as **Absolute** which was creating the problem. Changes it to **Rolling** has fixed the issue. 

Thanks again. We really appreciate your support.

@jasonnutter, @sameerag - Thanks for helping us while resolving the issue.
