### ISSUE TITLE
BearerStrategies use of `async.waterfall` creates unresolving async code

### ISSUE THREAD

**Issue by oehm-smith** [AzureAD/microsoft-authentication-library-for-js#3398]
I first started to work out the problems I was having with using this library in AzureAD/passport-azure-ad#427.  I fixed my issues and I found one big one with this lib.

At https://github.com/AzureAD/passport-azure-ad/blob/e9684341920ac8ac41c55a1e7150d1765dced809/lib/bearerstrategy.js#L404 is the start of the use of `async.waterfall`.  I've never used this before though it seems to run asynchronously so that when I call `passport.authenticate('oauth-bearer',..)` it returns immediately and my code to check `request.isAuthenticated()` always fails. 

I proved this async behaviour by performing the `request.isAuthenticated()` in a timeout of 1.5 seconds.  And it worked (authentication happened within that time).

I've looked at a random couple other passport strategies and all seem to employ synchronous code in the `authenticate` method.  Both strategies in passport-azure-ad use this `async.waterfall`.  So I don't know how they have worked for you, in your testing or for others.  

Could you please confirm this behaviour and provide a fix.  In the meantime I will continue to. use a timeout with intervals to check if `request.isAuthenticated()` is true so the timeout can terminate early.

**Comment by jo-arroyo** [comment]
Passport-azure-ad is now in maintenance. Future middleware scenarios will be built on top of msal-node. Closing.
