### ISSUE TITLE
Support for both session cookie and Authorisation Header

### ISSUE THREAD

**Issue by Sharathmk99** [AzureAD/microsoft-authentication-library-for-js#3400]
Hello,
I have built application using passport-azure-ad library with OIDC strategy. This strategy uses session cookie to authenticate users, it works well. Now I have to support Bearer token strategy also for same endpoints. Example I have endpoint called /hello, when user calls this API without token, he will be redirected to Microsoft login page, once authenticated session cookie is set and it works fine. Second flow, user calls /hello from postman client by passing Bearer token, this should also work. 

I have tried to build 2seperate application using OIDC and Bearer strategy, it works fine. How can use both for single endpoint??

Thanks!

**Comment by jasonnutter** [comment]
Ability to leverage cookies for authorization for new Node Token Validation library will be tracked internally in ADO, closing. @jo-arroyo
