### ISSUE TITLE
OIDCStrategy authenticate method does not check token expiry

### ISSUE THREAD

**Issue by sbanerjee302** [AzureAD/microsoft-authentication-library-for-js#3401]
The `authenticate()` method does not validate the token expiry value using OIDCstaregy.

**Comment by jo-arroyo** [comment]
Closing as passport-azure-ad is now in maintenance mode and will not have further fixes. This functionality will be added in the new token validation library built on top of msal-node. Keep an eye out for msal-node updates and announcements.
