### ISSUE TITLE
Localhost Token not accept by Graph API

### ISSUE THREAD

**Issue by jonatansantana** [AzureAD/microsoft-authentication-library-for-js#3403]
### Core Library

@azure/msal or msal

### Core Library Version

1.4.4

### Wrapper Library

@azure/msal-angular

### Wrapper Library Version

1.1.2

### Description

When using a token generated by azure ad through msal to query data in the API "https://graph.microsoft.com/v1.0/me", it does not work.

I always get error 400 with a message like this:

This occurs only in the localhost environment.

### Error Message

{
     "error": {
         "code": "InvalidAuthenticationToken",
         "message": "Invalid x5t claim.",
         "innerError": {
             "date": "2021-04-07T02: 15: 22",
             "request-id": "e35df8b8-889d-4b4c-9f2f-b354e975accf",
             "client-request-id": "e35df8b8-889d-4b4c-9f2f-b354e975accf"
         }
     }
}

### Msal Logs

{
     "error": {
         "code": "InvalidAuthenticationToken",
         "message": "Invalid x5t claim.",
         "innerError": {
             "date": "2021-04-07T02: 15: 22",
             "request-id": "e35df8b8-889d-4b4c-9f2f-b354e975accf",
             "client-request-id": "e35df8b8-889d-4b4c-9f2f-b354e975accf"
         }
     }
}

### MSAL Configuration

```javascript
const isIE = window.navigator.userAgent.indexOf('MSIE ') > -1 || window.navigator.userAgent.indexOf('Trident/') > -1;
const isInIframe = window !== window.parent && !window.opener;

MsalModule.forRoot({
    auth: {
      clientId: CLIENT_ID_HERE,
      authority: AUTHORITY_URL,
      redirectUri: REDIRECT_URL,
    },
    framework: { isAngular: true },
    cache: {
      cacheLocation: 'localStorage',
      storeAuthStateInCookie: isIE || isInIframe,
    },
  },
    {
      popUp: isIE || isInIframe,
      consentScopes: AZURE_AUTH_SCOPES,
      protectedResourceMap: [
        [environment.AZURE_OPEN_GRAPH_V1_URL, ['user.read']],
      ],
      extraQueryParameters: {}
}),
```

### Relevant Code Snippets

```javascript
import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { AuthError, InteractionRequiredAuthError } from 'msal';
import { MsalService } from '@azure/msal-angular';
import { BehaviorSubject } from 'rxjs';
import { User } from 'src/app/shared/models/user.model';
import { BaseHttpClientService } from 'src/app/shared/services/base-http-client.service';
import { environment } from 'src/environments/environment';

@Injectable({
  providedIn: 'root'
})
export class AzureAdService extends BaseHttpClientService {

  private authenticatedUser: BehaviorSubject<User> = new BehaviorSubject<User>(null);

  constructor(protected _http: HttpClient, private _msalService: MsalService) {
    super(_http, environment.AZURE_OPEN_GRAPH_V1_URL);

    this.getUserInAD();
  }

  getAuthenticatedUser(): BehaviorSubject<User> {
    return this.authenticatedUser;
  }

  redirectToLogin(): void {
    const ehInternetExplorer = window.navigator.userAgent.indexOf('MSIE ') > -1 || window.navigator.userAgent.indexOf('Trident/') > -1;
    ehInternetExplorer ? this._msalService.loginRedirect() : this._msalService.loginPopup();
  }

  logout(): void {
    localStorage.clear();

    this.authenticatedUser.next(null);
    this._msalService.logout();
  }

  getAuthenticatedUserFullname(): string {
    const first_name = JSON.parse(localStorage.getItem('authenticatedUser.first_name'));
    const surname = JSON.parse(localStorage.getItem('authenticatedUser.surname'));

    return first_name + ' ' + surname;
  }

  private getUserInAD() {
    this._http.get('').subscribe({
      next: (foundedUser) => {
        this.authenticatedUser.next(User.criar(foundedUser));
      },
      error: (error: AuthError) => {
        if (InteractionRequiredAuthError.isInteractionRequiredError(error.errorCode)) {
          this._msalService.acquireTokenPopup({
            scopes: this._msalService.getScopesForEndpoint(environment.AZURE_OPEN_GRAPH_V1_URL)
          })
            .then(() => {
              this._http.get(environment.AZURE_OPEN_GRAPH_V1_URL)
                .toPromise()
                .then(foundedUser => {

                  this.authenticatedUser.next(User.criar(foundedUser));
                });
            });
        }
      }
    });
  }
}


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {

  authenticatedUser: any;

  constructor(public _azureAdService: AzureAdService) {
  }

  ngOnInit(): void {
    if (this.userNotAuthenticated()) {
      this._azureAdService.redirectToLogin();
    }

    this.loadAuthenticatedUser();
  }

  userNotAuthenticated(): boolean {
    return this.authenticatedUser === null;
  }

  logout(): void {
    this._azureAdService.logout();
  }

  private loadAuthenticatedUser(): void {
    this._azureAdService.obterUsuarioLogado().subscribe((authenticatedUser) => this.authenticatedUser = authenticatedUser);
  }
}
```

### Reproduction Steps

Install npm package "@azure/msal-angular": "^1.1.2",
Configure with MSAL Configuration
Create a Service from Relevant Code Snippets
Add code  in app.component based Relevant Code Snippets
Do login in system
Go to application inspect tab and get access token
Open postman and send get request to https://graph.microsoft.com/v1.0/me with Authorization header and access token
Waiting for response

### Expected Behavior

Response status code 200 and user data.

"@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users/$entity",
"businessPhones": [],
"displayName": "Full name here",
"givenName": "Name here",
"jobTitle": null,
"mail": "name@site.com.br",
"mobilePhone": null,
"officeLocation": null,
"preferredLanguage": null,
"surname": "Santos",
"userPrincipalName": "name@site.com.br#EXT#@BUSINESS.onmicrosoft.com",
"id": "XXXXXXXXXXXXXXXXXXXXXXXXXXX"

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge

### Source

Internal (Microsoft)

When using a token generated by azure ad through msal to query data in the API "https://graph.microsoft.com/v1.0/me", it does not work.

I always get error 400 with a message like this:

This occurs only in the localhost environment.

**Comment by sameerag** [comment]
@jonatansantana This looks like the `token` generated in this case is not a valid one for the `graph` API to accept. `msal js` does not generate the tokens itself, it passes the token granted by STS (secure token service) to the app; 

Can you expand on the scopes used to generate this token? All our samples work for `localhost` redirect URIs, so I am not sure what is going on here.
