### ISSUE TITLE
MSAL on safari/iphone

### ISSUE THREAD

**Issue by mylle** [AzureAD/microsoft-authentication-library-for-js#3407]
### Core Library

@azure/msal or msal

### Core Library Version

1.2.2-beta.0

### Wrapper Library

@azure/msal-angular

### Wrapper Library Version

1.1.1

### Description

Hi,

Is there already a fix to use this library on safari/iphone?
Now you can't login due to the cross-site tracking:
https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Known-issue-on-Safari

Thank you.

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by sameerag** [comment]
@mylle If you are using `msal v1`, currently the only workaround is to login with interactive flow. `msal v2` helps with this use case and we also generally recommend to move to the latest msal version and in your case, the latest angular library can be referenced [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-angular)
