### ISSUE TITLE
B2C loginRedirect invalid_request error

### ISSUE THREAD

**Issue by enaSo97** [AzureAD/microsoft-authentication-library-for-js#3409]
### Core Library

@azure/msal-browser

### Core Library Version

2.13.1

### Wrapper Library

@azure/msal-react

### Wrapper Library Version

1.0.0-beta.1

### Description

When sign in button is clicked the loginRedirect is called and I am able to put down my email and password but when it redirects to homepage authentication has failed and I get this network error. 
```
{"error":"invalid_request","error_description":"AADB2C90083: The request is missing required parameter: grant_type.\r\nCorrelation ID: 69ae8ca2-d509-4125-a8af-178b8cd06062\r\nTimestamp: 2021-04-07 14:58:35Z\r\n"}
```

I've registered the app for SPA and enabled Access token and ID tokens for implicit grant and hybrid flows. 

### MSAL Configuration

```javascript
const msalConfig = {
    auth: {
        authority: signInAuthority,
        clientId: applicationID,
        redirectUri: window.location.origin,
        postLogoutRedirectUri: window.location.origin,
        validateAuthority: false,
        knownAuthorities: [`${tenantSubdomain}.b2clogin.com`],
    },
    cache: {
        cacheLocation: "sessionStorage",
        storeAuthStateInCookie: false,
    },
    tokenRefreshUri: window.location.origin,
};

const loginRequest = {
    scopes: ["https://TENANT.onmicrosoft.com/api/read",]
};
```

### Relevant Code Snippets

```javascript
// loginRequest comes from MSAL Config
<Link to="/" onClick={() => instance.loginRedirect(loginRequest)}>Sign in</Link>
```

### Identity Provider

Azure B2C Basic Policy

### Source

External (Customer)

**Comment by sameerag** [comment]
>> I've registered the app for SPA and enabled Access token and ID tokens for implicit grant and hybrid flows.

Can you please confirm that your app is registered as a `SPA` type and the redirect URI is correct? The guidance to do that is available [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/migrate-spa-implicit-to-auth-code#switch-redirect-uris-to-spa-platform), can you please confirm this and reach out?

**Comment by derisen** [comment]
@enaSo97 please uncheck the boxes for ID and access token under implicit flow section, as your package does not support implicit flow

**Comment by enaSo97** [comment]
@sameerag 
![image](https://user-images.githubusercontent.com/32780832/113920047-460a8700-97b2-11eb-8e89-3b1a67510e54.png)
I have the application type set as SPA

**Comment by enaSo97** [comment]
Removing implicit flow and configuring the registration policy to allow public clients solved the issue. 

Thanks!!
