### ISSUE TITLE
Add login hint to msal-angular when using HttpInterceptor

### ISSUE THREAD

**Issue by web265p3** [AzureAD/microsoft-authentication-library-for-js#3416]
### Core Library

@azure/msal or msal

### Wrapper Library

@azure/msal-angular

### Description

It can be useful to add a login hint (in my case if the app runs in MS Teams and some basic user info is known)
How can a login hint be added easily when using msal for angular with an Interceptor? 
I am talking about this function: https://azuread.github.io/microsoft-authentication-library-for-js/ref/modules/_azure_msal.html#authenticationparameters.__type-1.loginhint

So there is a parameter in MSAL - I just have no idea where to add this when using a wrapper library with interceptor. 

### Source

External (Customer)

[https://azuread.github.io/microsoft-authentication-library-for-js/ref/modules/_azure_msal.html#authenticationparameters.__type-1.loginhint](url)

**Comment by jasonnutter** [comment]
@web265p3 Unfortunately, this is not possible in MSAL Angular v1. It is possible in MSAL Angular v2 via the `authRequest` property which enables you to pass additional parameters to the underlying `acquireTokenSilent` call: https://azuread.github.io/microsoft-authentication-library-for-js/ref/modules/_azure_msal_angular.html#msalinterceptorconfiguration

You can use the `setActiveAccount` API to set which account is used in the interceptor. And when #3281 is released, you will be able to set those properties dynamically at runtime.

**Comment by jasonnutter** [comment]
Closing, as this is addressed in v2.
