### ISSUE TITLE
Problem updating v1.1.1 to v2.0.0

### ISSUE THREAD

**Issue by mylle** [AzureAD/microsoft-authentication-library-for-js#3417]
### Core Library

@azure/msal-browser

### Core Library Version

2.13.1

### Wrapper Library

@azure/msal-angular

### Wrapper Library Version

2.0.0-beta.3

### Description

Hi,

I tried updating my project to v2 (as adviced in previous question) but I'm stuck with an error.
To be honest, I'm not an expert, but average at most in Angular.

I tried replacing my code with the new code. Also I'm using an Auth service instead of using the app.component.ts like in the examples.

My problem is, when clicking on my login button, I'm getting redirected to a page (very fast) and then back to my original website, but nothing changes. My '.. getAllAccounts().length' is still zero.

When clicking the login again i'm getting the console error message: "BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API."

### MSAL Configuration

```javascript
export function MSALInstanceFactory(): IPublicClientApplication {
  return new PublicClientApplication({
    auth: {
      clientId: '3454d924-4412-4505-9af6-e954fde72d57',
      authority: 'https://login.microsoftonline.com/510df548-a539-40b9-8716-eb24afaccf1f',
      redirectUri: environment.MSAL_redirectUri,
      postLogoutRedirectUri: environment.MSAL_postLogoutRedirectUri,
      // navigateToLoginRequestUrl: true
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE,
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Info,
        piiLoggingEnabled: false
      }
    }
  });
}

export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
  const protectedResourceMap = new Map<string, Array<string>>();
  protectedResourceMap.set('https://graph.microsoft.com/v1.0/me', ['user.read']);
  protectedResourceMap.set(environment.API_URL, ['api://f1c2d297-0e55-4c4f-9a97-f327b500e832/api-access']);

  return {
    interactionType: InteractionType.Redirect,
    protectedResourceMap
  };
}

export function MSALGuardConfigFactory(): MsalGuardConfiguration {
  return {
    interactionType: InteractionType.Redirect,
    authRequest: {
      scopes: ['user.read']
    }
  };
}
```

### Relevant Code Snippets

```javascript
Auth.service.ts:
import { Injectable } from '@angular/core';

import { AppSandbox } from '../app.sandbox';

import { Inject } from '@angular/core';
import { Router } from '@angular/router';
import { Location } from "@angular/common";
import { MsalService, MsalBroadcastService, MSAL_GUARD_CONFIG, MsalGuardConfiguration, MsalCustomNavigationClient } from '@azure/msal-angular';
import { AuthenticationResult, InteractionType, InteractionStatus, PopupRequest, RedirectRequest } from '@azure/msal-browser';
import { Subject } from 'rxjs';
import { filter, takeUntil } from 'rxjs/operators';

@Injectable({
  providedIn: 'root'
})
export class AuthService {
  isAuthenticated$ = this.sb.isAuthenticated$;
  isRegAuthenticated$ = this.sb.isRegAuthenticated$;
  currentUser$ = this.sb.getCurrentUser$;

  loginDisplay = false;
  private readonly _destroying$ = new Subject<void>();

  constructor(
    @Inject(MSAL_GUARD_CONFIG) private msalGuardConfig: MsalGuardConfiguration,
    private authService: MsalService,
    private msalBroadcastService: MsalBroadcastService,
    private location: Location,
    private sb: AppSandbox,
    private router: Router
  ) {
    // Custom navigation set for client-side navigation. See performance doc for details: https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-angular/docs/v2-docs/performance.md
    const customNavigationClient = new MsalCustomNavigationClient(authService, this.router, this.location);
    this.authService.instance.setNavigationClient(customNavigationClient);
  }

  checkADlogin(): void {
    console.log('checkADlogin');

    this.setLoginDisplay();

    this.msalBroadcastService.inProgress$
      .pipe(
        filter((status: InteractionStatus) => status === InteractionStatus.None),
        takeUntil(this._destroying$)
      )
      .subscribe(() => {
        this.setLoginDisplay();
      })
  }

  setLoginDisplay() {
    console.log('setLoginDisplay');

    this.loginDisplay = this.authService.instance.getAllAccounts().length > 0;

    if (this.loginDisplay) {
      console.log('getAllAccounts().length > 0');
    } else {
      console.log('getAllAccounts().length = 0');
    }
  }

  loginAD() {
    console.log('loginAD');

    if (this.msalGuardConfig.interactionType === InteractionType.Popup) {
      console.log('InteractionType.Popup');
      if (this.msalGuardConfig.authRequest) {
        this.authService.loginPopup({ ...this.msalGuardConfig.authRequest } as PopupRequest)
          .subscribe((response: AuthenticationResult) => {
            this.authService.instance.setActiveAccount(response.account);
          });
      } else {
        this.authService.loginPopup()
          .subscribe((response: AuthenticationResult) => {
            this.authService.instance.setActiveAccount(response.account);
          });
      }
    } else {
      console.log('NOT InteractionType.Popup');
      if (this.msalGuardConfig.authRequest) {
        console.log('if (this.msalGuardConfig.authRequest){');
        this.authService.loginRedirect({ ...this.msalGuardConfig.authRequest } as RedirectRequest);
      } else {
        console.log('NOT if (this.msalGuardConfig.authRequest){')
        this.authService.loginRedirect();
      }
    }
  }

  logoutAD() {
    if (this.msalGuardConfig.interactionType === InteractionType.Popup) {
      this.authService.logoutPopup({
        mainWindowRedirectUri: "/"
      });
    } else {
      this.authService.logoutRedirect();
    }
  }

}
```

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by sameerag** [comment]
@jo-arroyo Will you be able to help @mylle here?

**Comment by jo-arroyo** [comment]
Hi @mylle, have you bootstrapped the `MsalRedirectComponent`? Interaction_in_progress errors are usually related to improperly handled redirects. See our [redirect doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/redirects.md) for more details on how to handle your redirect.

**Comment by mylle** [comment]
Hi @jo-arroyo, I did not, as I didn't see it in the Angular 9 V2 example.
I added the component to the bootstrap of app.module.ts
`bootstrap: [AppComponent, MsalRedirectComponent]`
Now when visiting my page, I'm getting 2 of the same errors instantly:
ERROR Error: The selector "app-redirect" did not match any elements

I tried clicking my login button, but the same thing happens. 

I forgot to mention that after the fast redirect my URL changes with the addition of #code=....:
http://localhost:4200/home#code=0.ASAASPUNUTmluUCHFuskr6zPHyTZVDQSRAVFmvbpVP3nLVcgAPU.AQABAAIAAAD--DLA3VO7QrddgJg7Wevrko5iTHdT6oJe6FZUCBGLJYJWOFeuxR0JApKudUhtnoS2VYttDAbOp5wzmpuQ8sOGIWofhPl-Uhx56veUefKg_m5J-YBA9rJrL8DbZjCXH1yS3N9mBTn0-e3wvf6qBoAZSo644V6qAXGTEeJIUQHPIqWgyNx4HCTBnm0jLl3rvf9OxXDYkGnkyE7htWecUTIjJ6d_yFCVd-nv2Atowf6eKeoafIfkkGUvs0t0FZ3iP51X-SKgjqSF5sU7ERlXi0-018QI8XWtjLT440e4-f0quZXWGHkQmS4JKUqSjJ9d0B1L6Dg2BM6bfCblm_TCbLPppyZhlsdNcP6PFo-ILW-Z6cJf5EguV-hPKEd6QvXpdGC8x9ICHj4KtTwVYsTJT0BkW-AJfgo-vEzxW2lwuupTjYdMZGM76Ec7CH7gZr3U3K6Ctx1Q9CtXlfVsggLkykfBGdjcJqCdVs-UwK11irpzmEyU0s3h6Xq4WEZENKZ4t11ywjqQosodnFH35aODJpNgIaFhT1oOKYB6V1UImc6Y_I3YafFJsg3gpXYBTlcB9uaPox38gTLl2Ggo2hQvkWUCSW0ihNEX3QRLDPuYkJlUkhlAOt4DUgHumGhitWqVqTqMStWF2yCRjEZMRfzuwDXl7IlymdxGlsdlu1GOCrQHEWEjPgHznDjQC60ADZcouYScB0zhgb8lFxON5Ffhc-CMVkDxpuAi--B2F_EXHXKwCz4VHnkWKoMmEi7vUS5_4Dm36sAcZkyXe4oDK4PUyNjX_W7qBtLbp1hC_4jVW-U0KT4IQ4YIdHwIccry-T6COFsMhh2ks4Q414r7kIsAIObVc1QgWrvpC0UC3ovcprU3FeAAvGPySA-yaBtxAO4AO_LndBmdNmQhQuqpG1GzgICiIAA&client_info=eyJ1aWQiOiIxMDRmZTJmNS1iM2FhLTRjNzQtOGUxYi01MmVkNTAzMTkyNDAiLCJ1dGlkIjoiNTEwZGY1NDgtYTUzOS00MGI5LTg3MTYtZWIyNGFmYWNjZjFmIn0&state=eyJpZCI6IjlmN2RhOTQ4LTk5NDUtNGFmNC04YTdmLTUxMjBmOGYyNGZkMSIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicmVkaXJlY3QifX0=&session_state=a75f561d-18f9-443d-bfde-3381fadd236a_

**Comment by mylle** [comment]
Hi @jo-arroyo , I also tried to change the InteractionType to Popup and I got these errors in console:
![image](https://user-images.githubusercontent.com/18067020/114138310-be398f80-990d-11eb-8f54-9b07789a0813.png)

**Comment by jo-arroyo** [comment]
@mylle A few points: 
> Hi @jo-arroyo, I did not, as I didn't see it in the Angular 9 V2 example.

The Angular 9 v2 sample does not use the `MsalRedirectComponent`, as it demonstrates the use of `handleRedirectObservable`. However, `MsalRedirectComponent` works in Angular 9 apps too. Our [samples readme](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples) shows what each sample demonstrates, 

> I added the component to the bootstrap of app.module.ts
> `bootstrap: [AppComponent, MsalRedirectComponent]`
> Now when visiting my page, I'm getting 2 of the same errors instantly:
> ERROR Error: The selector "app-redirect" did not match any elements

The `MsalRedirectComponent` has a selector, "app-redirect". This selector should be added to your index.html as well. See our [redirect doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/redirects.md) for what this looks like.

> I tried clicking my login button, but the same thing happens.
> 
> I forgot to mention that after the fast redirect my URL changes with the addition of #code=....:

The #code that is being returned shows that the redirect has not yet been handled. When the redirect is not handled, and you click login again, it will cause an `interaction_in_progress` error, as the previous interaction is not handled before you start another one. This is expected behavior when a redirect has not been handled.

As for the error you are getting with popups, please check your app registration in the Azure Portal and make sure your `redirectUri` is registered as type "SPA".

**Comment by mylle** [comment]
Hi @jo-arroyo ,

I managed to get everything to work.
I also had to change my Azure App URL redirects to SPA (instead of Web) and then everything worked.

Thanks for all the help!

Kind regards,
Niels
