### ISSUE TITLE
Prevent child components loading numerous times

### ISSUE THREAD

**Issue by cheslijones** [AzureAD/microsoft-authentication-library-for-js#3418]
### Core Library

@azure/msal-browser

### Core Library Version

2.12.0

### Wrapper Library

@azure/msal-react

### Wrapper Library Version

1.0.0-beta.0

### Description

Basically child components of `<AuthenticatedTemplate>` are being loaded multiple times which hits my API each time. I'm trying to prevent this so it only happens once.

### MSAL Configuration

```javascript
import { Configuration, RedirectRequest } from '@azure/msal-browser';

// Config object to be passed to Msal on creation
export const msalConfig: Configuration = {
  auth: {
    clientId: '<client_id>',
    authority: 'https://login.microsoftonline.com/<tenant_id>',
  },
};

// Add here scopes for id token to be used at MS Identity Platform endpoints.
export const loginRequest: RedirectRequest = {
  scopes: ['User.Read'],
};

// Add here the endpoints for MS Graph API services you would like to use.
export const graphConfig = {
  graphMeEndpoint: 'https://graph.microsoft.com/v1.0/me',
};
```

### Relevant Code Snippets

```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import App from './components/App';
import { PublicClientApplication } from '@azure/msal-browser';
import { MsalProvider } from '@azure/msal-react';
import { msalConfig } from './utils/authConfig';

const msalInstance = new PublicClientApplication(msalConfig);

ReactDOM.render(
  <React.StrictMode>
    <MsalProvider instance={msalInstance}>
      <App />
    </MsalProvider>
  </React.StrictMode>,
  document.getElementById('root')
);

---

import React, { useEffect } from 'react';
import {
  AuthenticatedTemplate,
  useMsal,
  useAccount,
  useIsAuthenticated,
} from '@azure/msal-react';
import { graphConfig, loginRequest } from '../utils/authConfig';
import { InteractionStatus } from '@azure/msal-browser';
import axios from 'axios';

const Token = (props: any) => {
  if (props.account) {
    props.instance
      .acquireTokenSilent({
        ...loginRequest,
        account: props.account,
      })
      .then((response: any) => {
        axios
          .post('/api/v2/auth/aad_token/validate/', {
            access_token: response.accessToken,
            id_token: response.idToken,
            oid: response.uniqueId,
          })
          .then((response) => {
            console.log(response.data);
          })
          .catch((error) => {
            console.log(error);
          });
      });
  }
  return <div>Test</div>;
};

const App = () => {
  const isAuthenticated = useIsAuthenticated();
  const { instance, inProgress, accounts } = useMsal();
  const account = useAccount(accounts[0] || {});

  useEffect(() => {
    if (inProgress === InteractionStatus.None && !isAuthenticated) {
      instance.loginRedirect(loginRequest);
    }
  });

  return (
    <div className='App'>
      <AuthenticatedTemplate>
        <Token account={account} instance={instance} />
      </AuthenticatedTemplate>
    </div>
  );
};

export default App;
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

---

I'm not too far into the implementation and have it pretty bear bones and not refactored (and not great coding practices). 

This is an Admin portal that uses the company's Azure Active Directory to validate users as opposed to username/password, etc. The flow is this:

1. User navigates to `/admin`.
2. `useEffect()` starts checking if user `isAuthenticated`.
3. If not, they are automatically redirected to login.
4. Once they have logged in, or are verified as already being `isAuthenticated`, they can now access components that are children of `<AuthenticatedTemplate>`.

The only child component currently is `<Token>`, which for testing purposes, just prints out the JWT token returned from the API. Essentially what happens here is:

1. The `accessToken`, `idToken`, `oid` are automatically sent to my API for validation server-side as well.
2. When they are validated, the user is checked against the DB... if they exist, send a JWT... if not, add them and send a JWT.
3. JWT is saved to `sessionStorage` and is used subsequently for client-API communication.

The problem I'm running into my API is getting queried four or more times:

[![enter image description here][1]][1]

[1]: https://i.stack.imgur.com/oqTP9.png

**Comment by jasonnutter** [comment]
@cheslijones A couple of things to point out:

1. `<React.StrictMode>` will render your app multiple times in development: https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects
2. I don't think we would recommend invoking `acquireTokenSilent` on every render. Instead, proactively invoke it inside a `useEffect`, or reactively as a result of user interaction (as a result of triggering an http request that needs a token).

@tnorling For any additional insight.

**Comment by cheslijones** [comment]
@jasonnutter Thanks for pointing those two things out.

I did remove the `<React.StrictMode>` for testing purposes and refactored the logic where the call to my API is, into a `useEffect`. This has reduced it down to two API calls:

```
const Token = () => {
  const { accounts, instance } = useMsal();
  const account = useAccount(accounts[0] || {});

  useEffect(() => {
    // Check if account object exists
    if (account) {
      // If it does then acquire an accessToken
      instance
        .acquireTokenSilent({
          ...loginRequest,
          account: account,
        })
        .then((response: any) => {
          axios
            .post('/api/v2/auth/aad_token/validate/', {
              access_token: response.accessToken,
              id_token: response.idToken,
              oid: response.uniqueId,
            })
            .then((response) => {
              console.log(response.data);
            })
            .catch((error) => {
              console.log(error);
            });
        });
    }
  });

  return <div>Test</div>;
};
```
I'm looking at a reactive implementation that somehow doesn't involve the user's interaction. I'd rather it be an automatic "you're signed in" or redirect to signin since having them click an additional button to sign just doesn't feel like a necessary step.

**Comment by tnorling** [comment]
@cheslijones Can you try giving your useEffect an empty dependency array as per [react docs](https://reactjs.org/docs/hooks-effect.html#tip-optimizing-performance-by-skipping-effects)?

This should ensure it's only called once per component mount whether or not you have Strict mode turned on.

**Comment by cheslijones** [comment]
That did the trick, I appreciate the help.
