### ISSUE TITLE
Login with facebook fails on iPad

### ISSUE THREAD

**Issue by kyma** [AzureAD/microsoft-authentication-library-for-js#342]
I'm able to login with Facebook on desktop fine, but on an iPad I get this error:

Refused to display 'https://m.facebook.com/v3.0/dialog/oauth?redirect_uri=https%3A%2F%2Flogin.microsoftonline.com%2Fte%2Flynkcob2c.onmicrosoft.com........

in a frame because it set 'X-Frame-Options' to 'DENY'.

And the login fails.

**Comment by kyma** [comment]
Thanks for your response.
We're using the B2C flow. The login process with Facebook works fine on desktop. We're not running it in an iFrame.

The only difference I can see is that on desktop you seem to pass straight though FB systems and log in, and on mobile it takes you to an intermediary confirmation screen:
https://m.facebook.com/v3.0/dialog/oauth?redirect_uri=https%3A%2F%2Flogin.microsoftonline.com%2Fte%2Fly/........

this has the header X-Frame-Options: DENY

When you click through this screen, you are returned to our site, but then a few seconds later get the error mentioned above and we can't retrieve the user token. Perhaps the getTokenSilent request gets forwarded to the same intermediary screen?

You can test this here: https://colab.lynkco.com/lang/en

**Comment by navyasric** [comment]
This issue seems similar to #352.
@kyma   Since the intermediary screen is rendered by Facebook, it does not seem an issue related to library. Please let us know if this issue is resolved for you.

**Comment by sameerag** [comment]
Closing this as no response since some time. Please reopen if the issue still persists.
