### ISSUE TITLE
Produce better error message when user not set in verifyCallback (done) function

### ISSUE THREAD

**Issue by ArashMotamedi** [AzureAD/microsoft-authentication-library-for-js#3423]
This misleading error message gave me hours of headache. It appears that the `verify` function in `BearerStrategy` constructor **expects the `done` method to be called with `user` parameter set**. 

See: https://github.com/AzureAD/passport-azure-ad/blob/ee2ec66e8d1b393809f846547d36edb24a2fd2c8/lib/bearerstrategy.js#L552-L553

And the corresponding type: 
```ts
export interface VerifyCallback {
    (error: any, user?: any, info?: any): void;
}
```

In my code, I was calling `done` without setting `user`, which was producing error message: 
> authentication failed due to: error: invalid_token

Which is misleading, because token was valid. The referenced line in `bearerstrategy.js` must be updated to throw a different error, e.g. `user_not_set`.

Additionally, the corresponding type should be updated to guard against incorrect use of the API. Here's an overload that might work:

```ts
export interface VerifyCallback {
    (error: null | undefined, user: {}, info?: any): void;
    (error: {}, user?: any, info?: any): void;
}
```

**Comment by pkanher617** [comment]
We will address this in the new version of the passport-azure-ad library.

**Comment by jo-arroyo** [comment]
Closing as passport-azure-ad is now in maintenance. We are working on middleware scenarios that will be built on top of msal-node, which will have improved error handling. Keep an eye out for future msal-node updates.
