### ISSUE TITLE
msal-browser throws error code endpoints_resolution_error/openid_config_error

### ISSUE THREAD

**Issue by deasems** [AzureAD/microsoft-authentication-library-for-js#3428]
### Core Library

@azure/msal-browser

### Core Library Version

2.12.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

n/a

### Description

My app's error telemetry is showing MSAL's `endpoints_resolution_error` is the most common error for our users. From what I can tell MSAL throws this error if it can't load metadata during initialization. I'm unable to repro the error myself so I'm interested to hear from your team what might cause this error for users and if there's any recommended fix or debug steps. 

A couple other data points from the telemetry data - The error only occurs on Chrome running Windows 10. I only see this error occurring in our production environment yet our int environment uses the same MSAL configuration. 

Here's the error details:
```json
 {
    "errorCode": "endpoints_resolution_error",
    "errorMessage": "Error: could not resolve endpoints. Please check network and try again. Detail: ClientAuthError: openid_config_error: Could not retrieve endpoints. Check your authority and verify the .well-known/openid-configuration endpoint returns the required endpoints. Attempted to retrieve endpoints from: https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration",
    "subError": "",
    "name": "ClientAuthError",
    "message": "endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientAuthError: openid_config_error: Could not retrieve endpoints. Check your authority and verify the .well-known/openid-configuration endpoint returns the required endpoints. Attempted to retrieve endpoints from: https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration",
    "stack": "ClientAuthError: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientAuthError: openid_config_error: Could not retrieve endpoints. Check your authority and verify the .well-known/openid-configuration endpoint returns the required endpoints. Attempted to retrieve endpoints from: https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration\n at t [as constructor] (https://pi.dynamics.com/static/js/1b75e6aa3e0261f15c89.js:2:9024)\n at new t (https://pi.dynamics.com/static/js/1b75e6aa3e0261f15c89.js:2:15326)\n at Function.t.createEndpointDiscoveryIncompleteError (https://pi.dynamics.com/static/js/1b75e6aa3e0261f15c89.js:2:15856)\n at Function.<anonymous> (https://pi.dynamics.com/static/js/1b75e6aa3e0261f15c89.js:2:99917)\n at https://pi.dynamics.com/static/js/1b75e6aa3e0261f15c89.js:2:4216\n at Object.throw (https://pi.dynamics.com/static/js/1b75e6aa3e0261f15c89.js:2:4321)\n at s (https://pi.dynamics.com/static/js/1b75e6aa3e0261f15c89.js:2:3110)"
}
```

Incase it's helpful, we also saw this error code when running v2.9.0 and the error was this:
```json
{
    "errorCode": "endpoints_resolution_error",
    "errorMessage": "Error: could not resolve endpoints. Please check network and try again. Detail: SyntaxError: Unexpected end of JSON input",
    "subError": "",
    "name": "ClientAuthError",
    "message": "endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: SyntaxError: Unexpected end of JSON input",
    "stack": "ClientAuthError: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: SyntaxError: Unexpected end of JSON input\n at t [as constructor] (https://pi.dynamics.com/static/js/3030e6970db3ac7895af.js:2:8843)\n at new t (https://pi.dynamics.com/static/js/3030e6970db3ac7895af.js:2:14857)\n at Function.t.createEndpointDiscoveryIncompleteError (https://pi.dynamics.com/static/js/3030e6970db3ac7895af.js:2:15387)\n at Function.<anonymous> (https://pi.dynamics.com/static/js/3030e6970db3ac7895af.js:2:94906)\n at https://pi.dynamics.com/static/js/3030e6970db3ac7895af.js:2:4161\n at Object.throw (https://pi.dynamics.com/static/js/3030e6970db3ac7895af.js:2:4266)\n at s (https://pi.dynamics.com/static/js/3030e6970db3ac7895af.js:2:3055)"
}
```

### MSAL Configuration

```javascript
{
    auth: {
      authority: 'https://login.microsoftonline.com/common',
      clientId: process.env.CLIENT_ID,
      navigateToLoginRequestUrl: false,
      redirectUri: window.location.origin,
      postLogoutRedirectUri: null,
    },
    cache: {
      cacheLocation: 'localStorage',
    },
    system: {
      loggerOptions: {
        piiLoggingEnabled: process.env.NODE_ENV === 'development',
      },
    },
  }
```

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by jasonnutter** [comment]
@deasems A simple mitigation you can try is to retry a request that gets this error (just retry once). I would be interested to know how often retrying fixes it. In lieu of a repro, correlation IDs of failed requests might be helpful for us to determine what went wrong.

**Comment by deasems** [comment]
Thanks for the tip @jasonnutter, we'll work on adding retry logic and check the success rate.

Is it possible to programmatically get correlation IDs for failed MSAL requests so we can send those in our telemetry? Currently we're logging the error object that MSAL provides which doesn't include a correlation ID.

**Comment by jasonnutter** [comment]
@deasems You can generate your own correlation id and pass it into the request.

**Comment by deasems** [comment]
@jasonnutter will that correlation ID be included in the error object for `endpoints_resolution_error` or would I need to keep track of the ID used for each request to send it to my telemetry if the request fails.

**Comment by sameerag** [comment]
@deasems We can add that I suppose, but under a conditional to not expose it by default to all users, in case some folks prefer otherwise. We have some work pending on correlation ids this quarter, we will consider this during the design.

**Comment by jasonnutter** [comment]
> @jasonnutter will that correlation ID be included in the error object for `endpoints_resolution_error` or would I need to keep track of the ID used for each request to send it to my telemetry if the request fails.

You will need to keep track of it.
