### ISSUE TITLE
Cannot find kid when SAML SSO is configured

### ISSUE THREAD

**Issue by a129722** [AzureAD/microsoft-authentication-library-for-js#3429]
I have an app registration where the associated enterprise application allows for SSO access via SAML.  I would also like to be able to authenticate via OAuth.  I get the following error: 

```
Authentication failed due to: In _validateResponse: failed to generate PEM key due to: a key with the specific kid cannot be found"
```

This seems to be due to there being an app-specific signing key generated when SAML is configured.  This library tries to find the signing keys via the URL supplied within the identity metadata URL.  However, it does not try supplying the `appid` parameter for that URL in the case where it cannot find the `kid` supplied in the token in the base URL.  

The identity metadata URL: 

https://login.microsoftonline.com/<my_tenant_id>/v2.0/.well-known/openid-configuration

The `jwks_uri` value within that document: 

https://login.microsoftonline.com/<my_tenant_id>/discovery/v2.0/keys

The URL which actually contains the kid specified in the token:

https://login.microsoftonline.com/<my_tenant_id>/discovery/v2.0/keys?appid=<my_app_id>

**Comment by jo-arroyo** [comment]
@EmLauber for your prioritization of SAML.

**Comment by urgn** [comment]
@a129722 hit the same issue, adding the `?appid=<client_id>` identity metadata URL, does change the `jwks_uri` to also contain the `?appid=<client_id>`.
Testing this approach now.

**Comment by jasonnutter** [comment]
Ability to use app specific signing keys for Node Token Validation library will be tracked internally in ADO, closing. @jo-arroyo
