### ISSUE TITLE
How can we implement PKCE with Open ID Connect in passport-azure-ad

### ISSUE THREAD

**Issue by nikhil-nomula** [AzureAD/microsoft-authentication-library-for-js#3431]
I am using passpot-azure-ad with auth code flow for building a web application with Express JS and Node JS. I am currently using Open ID connect to log users into the application. The flow that I want to use is auth code flow and PKCE is recommended. 

However when I look at OIDCStrategy we do not have options to include the code challenge and code challenge method. Can you let us now how do we do that with passport-azure-ad?

**Comment by jo-arroyo** [comment]
@nikhil-nomula PKCE is supported in msal-node today. Please try using msal-node, and open a new issue if you are still experiencing problems with msal-node.
