### ISSUE TITLE
cors error

### ISSUE THREAD

**Issue by sang17218** [AzureAD/microsoft-authentication-library-for-js#3434]
### Core Library

@azure/msal-node

### Core Library Version

2

### Wrapper Library

Not Applicable

### Wrapper Library Version

-

### Description

getting error:
Access to XMLHttpRequest at 'https://login.microsoftonline.com/{my-tenant-id}/oauth2/v2.0/token' from origin 'http://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource,
while trying to get access token using ConfidentialClientApplicationObj.acquireTokenByClientCredential()  method.

### Source

External (Customer)

**Comment by c2r0b** [comment]
I encountered the same error while using @azure/msal-react with a custom Authority

**Comment by sameerag** [comment]
@sang17218 I am a little confused about the use case here. CORS error is generally seen in the browser use case which matches with not registering a app as a `SPA` type and also registering a `redirectUri` in the same domain.

`msal-node` however shouldn't see this specific error. Can you please detail your use case, steps to reproduce, configuration and any other relevant details?

**Comment by jjalonso** [comment]
same error.
