### ISSUE TITLE
ERROR Error: Uncaught (in promise): ClientConfigurationError: No redirect callbacks have been set. Getting Error when try to call API of Login !!

### ISSUE THREAD

**Issue by kartikchandra14** [AzureAD/microsoft-authentication-library-for-js#3439]
### Core Library

@azure/msal or msal

### Core Library Version

^1.0.0-beta.4

### Wrapper Library

@azure/msal-angular

### Wrapper Library Version

 "^1.0.0-beta.4"

### Description

when i try to login using Microsoft login pop up !!
i stuck with this !!

Package.json contain:
  "msal": "^1.2.1",
   "@azure/msal-angular": "^1.0.0-beta.4",

### Error Message

ERROR Error: Uncaught (in promise): ClientConfigurationError: No redirect callbacks have been set. Please call handleRedirectCallback() with the appropriate function arguments before continuing. More information is available here: https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL-basics.

### Msal Logs

core.js:5882 ERROR Error: Uncaught (in promise): ClientConfigurationError: No redirect callbacks have been set. Please call handleRedirectCallback() with the appropriate function arguments before continuing. More information is available here: https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL-basics.
ClientConfigurationError: No redirect callbacks have been set. Please call handleRedirectCallback() with the appropriate function arguments before continuing. More information is available here: https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL-basics.

### MSAL Configuration

```javascript
MsalModule.forRoot({
      auth: {
        clientId: OAuthSettings.appId
      }
    })
```

### Relevant Code Snippets

```javascript
// Silently request an access token
  async getAccessToken(): Promise<string> {
    let result = await this.msalService.acquireTokenSilent(OAuthSettings).catch((reason) => {
        if(reason?.name == "InteractionRequiredAuthError"){
          this.msalService.acquireTokenRedirect(OAuthSettings).;
        }
        else{
          this.alertsService.add('Get token failed', JSON.stringify(reason, null, 2));
        }
      });

    if (result) {
      return result.accessToken;
    }
    return null;
  }
```

### Reproduction Steps

Try to login using Microsoft Account !!

### Expected Behavior

  // Silently request an access token
The token will be provided by method
But it is giving error !!

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox

### Regression

1

### Source

Internal (Microsoft)

**Comment by jasonnutter** [comment]
@kartikchandra14 The error message describes the problem and solution. Your app needs to implement `handleRedirectCallback` when using the redirect methods.

Furthermore, it looks like you are using old versions of MSAL and MSAL Angular. We highly recommend looking at upgrading to MSAL.js v2 and MSAL Angular v2.
