### ISSUE TITLE
MsalGuard navigates to wrong Path

### ISSUE THREAD

**Issue by AndreasHellmiss** [AzureAD/microsoft-authentication-library-for-js#3440]
### Core Library

@azure/msal or msal

### Core Library Version

1.4.4

### Wrapper Library

@azure/msal-angular

### Wrapper Library Version

2.0.0-beta.3

### Description

MsalGuard secures routes. If I want to open a specific route directly e.g.: http://localhost:4200/#/test/10, then I get loggd in successfully, but I get redirected to http://localhost:4200/#/home. I can see that it redirects shortly to my desired page but then gets overwritten somehow. Deleting `{ path: '**', redirectTo: 'home' }` from my routes solves this issue but I want to keep that path for missspelled routes.

### MSAL Configuration

```javascript
export function MSALInstanceFactory(): IPublicClientApplication{
  return new PublicClientApplication({
    auth: {
      clientId: 'xxxxx',
      authority: 'https://login.microsoftonline.com/xxxx',
      navigateToLoginRequestUrl: true 
    }
  });
}

export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
  const protectedResourceMap = new Map<string, Array<string>>();
  protectedResourceMap.set('http://localhost:51140/*', ['api://xxxx']);
  protectedResourceMap.set('https://graph.microsoft.com', ['user.readbasic.all']);

  return {
    interactionType: InteractionType.Redirect,
    protectedResourceMap
  }
}

export function MSALGuardConfigFactory(): MsalGuardConfiguration {
  return { 
    interactionType: InteractionType.Redirect,
    authRequest: {
      scopes: ['user.readbasic.all', 'api://xxxx']
    }
  };
}
```

### Relevant Code Snippets

```javascript
const routes: Routes = [
  {path: '', canActivate: [MsalGuard], children: [
    { path: '', redirectTo: 'home', pathMatch: 'full' },
    { path: 'home', component: HomeComponent},
    { path: 'test/:id', component: ProjectDetailsComponent},
    { path: '**', redirectTo: 'home' },
  ]}
  
];

const isIframe = window !== window.parent && !window.opener;

@NgModule({
  imports: [RouterModule.forRoot(routes, { useHash: true, relativeLinkResolution: 'legacy', initialNavigation: !isIframe ? 'enabled' : 'disabled' })],
  exports: [RouterModule]
})
```

### Reproduction Steps

Opening an URL directly thats not the home component

### Expected Behavior

After loginRedirect it should route me to the desired URL and not the HomeComponent.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@AndreasHellmiss First, to confirm, you are using MSAL.js v2, not v1?

Second, it looks like you do not set an explicit redirect uri, which means MSAL will use the current page. All of your pages use the MSAL Guard, and there is a known issue that when hash routing is used, this problem can happen if the guard is used on the page used for the redirect URI. Please see: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/3292#issuecomment-815104801

As a mitigation, when using hash routing, our recommendation is to set the MSAL redirect URI to a page that does not use the MSAL Guard.
