### ISSUE TITLE
When using Signup/Signin user flow w/ MSAL 2.0 - when user cancels they get blank page

### ISSUE THREAD

**Issue by teresahoes** [AzureAD/microsoft-authentication-library-for-js#3442]
### Core Library

@azure/msal or msal

### Core Library Version

2.13.0

### Wrapper Library

@azure/msal-angular

### Wrapper Library Version

2.0.0-beta

### Description

i have set up the user flow b2c as per the sample with angular 11. Everything works great, except when the user cancels the signup box, or the reset password flow - they are redirected back to the application and the page is blank. it does not load the application. i can see the selfasserted/cancelled call in the network log 

https://xxxx/B2C_1_csea_member_signup/api/SelfAsserted/cancelled?csrf_token=RFFQTVFaaWJzbzR3QVhRMXZRM3BOV1NIRTB1LzFTYUJ6bnBJckxDajJYSFJyUHhUMHlINHZIRFNzU1UvVkc5M0JXbFJUQ0o0UUhYK1ZPd0NFd2dEZHc9PTsyMDI.....

and i am subscribed to all events using the msalSubject observable
this.msalBroadcastService.msalSubject$ 

but the cancellation event is never emitted and the application just redirects to the home page (not /auth  uri). and the resulting page is just blank. 

is there a way to handle the cancelled assertion so i can either manually redirect to a page or have the application be reloaded?

### MSAL Configuration

```javascript
{
    auth: {
      clientId: 'e81dea5b-8e0f-4b60-a87a-1a0856e9e0f3',
      authority: b2cPolicies.authorities.signUpSignIn.authority,
      redirectUri: '/auth',
      postLogoutRedirectUri: '/logout',
      knownAuthorities: [b2cPolicies.authorityDomain]
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE, // set to true for IE 11
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Info,
        piiLoggingEnabled: false
      }
    }
```

### Identity Provider

Azure B2C Basic Policy

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@teresahoes Can you please clarify, are you using MSAL.js v1 (`msal`) or MSAL.js v2 (`@azure/msal-browser`)?

Are there other errors in the browsers? Can you please share verbose logs from MSAL?

**Comment by teresahoes** [comment]
Hi @jasonnutter -- thanks!!  
Here are my versions. 
    "@azure/msal-angular": "^2.0.0-beta.2",
    "@azure/msal-browser": "~2.13.1",


Here is the verbose log from the following actions:  hit home page to prompt login, select 'signup', hit cancel on the signup dialog.

[Tue, 13 Apr 2021 19:02:49 GMT] :  : @azure/msal-browser@2.13.1 : Verbose - Event callback registered with id: 035bfb10-472a-474b-b7d2-dd13bbd41f29
app.module.ts:40 [Tue, 13 Apr 2021 19:02:49 GMT] :  : @azure/msal-angular@2.0.0-beta.3 : Verbose - Guard - canActivate
app.module.ts:40 [Tue, 13 Apr 2021 19:02:49 GMT] :  : @azure/msal-angular@2.0.0-beta.3 : Verbose - MSAL Guard activated
app.module.ts:40 [Tue, 13 Apr 2021 19:02:49 GMT] :  : @azure/msal-browser@2.13.1 : Info - Emitting event: msal:handleRedirectStart
app.module.ts:40 [Tue, 13 Apr 2021 19:02:49 GMT] :  : @azure/msal-browser@2.13.1 : Verbose - Emitting event to callback 035bfb10-472a-474b-b7d2-dd13bbd41f29: msal:handleRedirectStart
app.module.ts:40 [Tue, 13 Apr 2021 19:02:49 GMT] :  : @azure/msal-angular@2.0.0-beta.3 : Verbose - BroadcastService - msal:handleRedirectStart results in setting inProgress to handleRedirect
app.module.ts:40 [Tue, 13 Apr 2021 19:02:49 GMT] :  : @azure/msal-browser@2.13.1 : Verbose - handleRedirectPromise called
app.module.ts:40 [Tue, 13 Apr 2021 19:02:49 GMT] :  : @azure/msal-browser@2.13.1 : Verbose - getAllAccounts called
app.module.ts:40 [Tue, 13 Apr 2021 19:02:49 GMT] :  : @azure/msal-browser@2.13.1 : Verbose - handleRedirectPromise has been called for the first time, storing the promise
app.module.ts:40 [Tue, 13 Apr 2021 19:02:49 GMT] :  : @azure/msal-browser@2.13.1 : Verbose - BrowserCacheManager.getTemporaryCache called
app.module.ts:40 [Tue, 13 Apr 2021 19:02:49 GMT] :  : @azure/msal-browser@2.13.1 : Verbose - getRedirectResponseHash called
app.module.ts:40 [Tue, 13 Apr 2021 19:02:49 GMT] :  : @azure/msal-browser@2.13.1 : Verbose - BrowserCacheManager.getTemporaryCache called
app.module.ts:40 [Tue, 13 Apr 2021 19:02:49 GMT] :  : @azure/msal-browser@2.13.1 : Verbose - Hash does not contain known properties, returning cached hash
app.module.ts:40 [Tue, 13 Apr 2021 19:02:49 GMT] :  : @azure/msal-browser@2.13.1 : Verbose - validateAndExtractStateFromHash called
app.module.ts:40 [Tue, 13 Apr 2021 19:02:49 GMT] :  : @azure/msal-browser@2.13.1 : Verbose - Returning state from hash
app.module.ts:40 [Tue, 13 Apr 2021 19:02:49 GMT] :  : @azure/msal-browser@2.13.1 : Verbose - State extracted from hash
app.module.ts:40 [Tue, 13 Apr 2021 19:02:49 GMT] :  : @azure/msal-browser@2.13.1 : Verbose - BrowserCacheManager.getTemporaryCache called
app.module.ts:40 [Tue, 13 Apr 2021 19:02:49 GMT] :  : @azure/msal-browser@2.13.1 : Verbose - Current page is loginRequestUrl, handling hash
app.module.ts:40 [Tue, 13 Apr 2021 19:02:49 GMT] :  : @azure/msal-browser@2.13.1 : Verbose - handleHash called
app.module.ts:40 [Tue, 13 Apr 2021 19:02:49 GMT] :  : @azure/msal-browser@2.13.1 : Verbose - BrowserCacheManager.getCachedRequest called
app.module.ts:40 [Tue, 13 Apr 2021 19:02:49 GMT] :  : @azure/msal-browser@2.13.1 : Verbose - BrowserCacheManager.getTemporaryCache called
app.module.ts:40 [Tue, 13 Apr 2021 19:02:49 GMT] :  : @azure/msal-browser@2.13.1 : Verbose - initializeServerTelemetryManager called
app.module.ts:40 [Tue, 13 Apr 2021 19:02:49 GMT] :  : @azure/msal-browser@2.13.1 : Verbose - BrowserCacheManager.getTemporaryCache called
app.module.ts:40 [Tue, 13 Apr 2021 19:02:49 GMT] :  : @azure/msal-browser@2.13.1 : Verbose - BrowserCacheManager.getTemporaryCache called
app.module.ts:40 [Tue, 13 Apr 2021 19:02:49 GMT] :  : @azure/msal-browser@2.13.1 : Verbose - createAuthCodeClient called
app.module.ts:40 [Tue, 13 Apr 2021 19:02:49 GMT] :  : @azure/msal-browser@2.13.1 : Verbose - getClientConfiguration called
app.module.ts:40 [Tue, 13 Apr 2021 19:02:49 GMT] :  : @azure/msal-browser@2.13.1 : Verbose - getDiscoveredAuthority called
app.module.ts:40 [Tue, 13 Apr 2021 19:02:49 GMT] :  : @azure/msal-browser@2.13.1 : Verbose - Creating discovered authority with request authority
app.module.ts:40 [Tue, 13 Apr 2021 19:02:50 GMT] :  : @azure/msal-browser@2.13.1 : Verbose - BrowserCacheManager.setAuthorityMetadata called
app.module.ts:40 [Tue, 13 Apr 2021 19:02:50 GMT] :  : @azure/msal-browser@2.13.1 : Verbose - BrowserCacheManager.getTemporaryCache called
app.module.ts:40 [Tue, 13 Apr 2021 19:02:50 GMT] :  : @azure/msal-browser@2.13.1 : Verbose - BrowserCacheManager.getServerTelemetry called
app.module.ts:40 [Tue, 13 Apr 2021 19:02:50 GMT] :  : @azure/msal-browser@2.13.1 : Verbose - BrowserCacheManager.getServerTelemetry: cache hit
app.module.ts:40 [Tue, 13 Apr 2021 19:02:50 GMT] :  : @azure/msal-browser@2.13.1 : Verbose - BrowserCacheManager.setServerTelemetry called
app.module.ts:40 [Tue, 13 Apr 2021 19:02:50 GMT] :  : @azure/msal-browser@2.13.1 : Verbose - BrowserCacheManager.cleanRequestByInteractionType called
app.module.ts:40 [Tue, 13 Apr 2021 19:02:50 GMT] :  : @azure/msal-browser@2.13.1 : Info - BrowserCacheManager.cleanRequestByInteractionType: Removing temporary cache items for state: eyJpZCI6ImYxM2I1ZjJlLTdhNmItNDIwMy1hMzc4LTI0MzE4NDMxZWM3ZiIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicmVkaXJlY3QifX0=
app.module.ts:40 [Tue, 13 Apr 2021 19:02:50 GMT] :  : @azure/msal-browser@2.13.1 : Verbose - BrowserCacheManager.resetRequestCache called
app.module.ts:40 [Tue, 13 Apr 2021 19:02:50 GMT] :  : @azure/msal-browser@2.13.1 : Info - Emitting event: msal:loginFailure
app.module.ts:40 [Tue, 13 Apr 2021 19:02:50 GMT] :  : @azure/msal-browser@2.13.1 : Verbose - Emitting event to callback 035bfb10-472a-474b-b7d2-dd13bbd41f29: msal:loginFailure
app.module.ts:40 [Tue, 13 Apr 2021 19:02:50 GMT] :  : @azure/msal-angular@2.0.0-beta.3 : Verbose - BroadcastService - msal:loginFailure results in setting inProgress to none
app.module.ts:40 [Tue, 13 Apr 2021 19:02:50 GMT] :  : @azure/msal-browser@2.13.1 : Info - Emitting event: msal:handleRedirectEnd
app.module.ts:40 [Tue, 13 Apr 2021 19:02:50 GMT] :  : @azure/msal-browser@2.13.1 : Verbose - Emitting event to callback 035bfb10-472a-474b-b7d2-dd13bbd41f29: msal:handleRedirectEnd
app.module.ts:40 [Tue, 13 Apr 2021 19:02:50 GMT] :  : @azure/msal-angular@2.0.0-beta.3 : Verbose - BroadcastService - msal:handleRedirectEnd results in setting inProgress to none
app.module.ts:40 [Tue, 13 Apr 2021 19:02:50 GMT] :  : @azure/msal-angular@2.0.0-beta.3 : Verbose - Guard - error while logging in, unable to activate

**Comment by pkanher617** [comment]
@teresahoes Apologies for the delay in getting back on this issue. Can you try this on the 2.0.0 version of the library and see if this issue still persists?
