### ISSUE TITLE
Example states 'response: res' is required for use with cookies but actually is optional

### ISSUE THREAD

**Issue by MRoc** [AzureAD/microsoft-authentication-library-for-js#3443]
Minor documentation issue: `app.js` example says `response: res` is required when using cookies. But it is actually NOT required and works without. Excerpt from App.js:

```
    passport.authenticate("azuread-openidconnect", {
      response: res, // required      <----------- SAYS REQUIRED BUT IS NOT
      resourceURL: config.resourceURL, // optional. Provide a value if you want to specify the resource.
      failureRedirect: "/",
      session: false,
    })(req, res, next);
```

If the response is not provided via options, then `passport-azure-ad/lib/oidcstrategy.js` resolves response from request:

```
var response = options && options.response || req.res;
```

One of the first middleware running in express.js is `express/lib/middleware/init.js` which makes request and response know each other:

```
exports.init = function(app){
  return function expressInit(req, res, next){
    if (app.enabled('x-powered-by')) res.setHeader('X-Powered-By', 'Express');
    req.res = res;  // <--------- MAKES REQUEST KNOW RESPONSE :)
    res.req = req;
    req.next = next;
    ...
    next();
  };
};
```

I assume it is not important but I read sources and wanted to share my findings. In the end it makes a small difference when the middleware is called as it does not need to be wrapped:

Before:

```
router.get(
  "/authentication/microsoft/signin",
  function (req, res, next) {
    passport.authenticate("azuread-openidconnect", {
      response: res,
      failureRedirect: "/authentication/signin",
      session: false,
    })(req, res, next);
  },
  function (req, res) {
  }
);
```

After:

```
router.get(
  "/authentication/microsoft/signin",
  passport.authenticate("azuread-openidconnect", {
    failureRedirect: "/authentication/signin",
    session: false,
    failureFlash: true,
  })
);
```

**Comment by jo-arroyo** [comment]
Closing as passport-azure-ad is in maintenance and will no longer receive updates. This issue will be addressed in future middleware scenarios built on top of msal-node.
