### ISSUE TITLE
Expose `end_session_endpoint` from metadata

### ISSUE THREAD

**Issue by thraidh** [AzureAD/microsoft-authentication-library-for-js#3447]
To properly log out of AzureAD it is necessary to go to
```
https://login.microsoftonline.com/${tenantID}/oauth2/logout
```
Given that only the `identityMetadata` URL is a required part of the configuration, we can either extract the tenant ID from that using regular expressions, but that is complicated, if that can be either a URL for B2C or V1 or V2 non-B2C URLs.

The correct link is already part of the metadata, which is fetched through that URL. Unfortunately there is no way for to access the metadata or especially the `end_session_endpoint`, except for fetching all the metadata again.

For this reason, it would be great, if the `end_session_endpoint` was somewhere exposed in the request, session or strategy object.

**Comment by sameerag** [comment]
#3399

**Comment by jo-arroyo** [comment]
Tagging @sameerag for msal-node consideration.

**Comment by jasonnutter** [comment]
Closing, let us know if what is provided in MSAL Node does not meet your needs.
