### ISSUE TITLE
Latest version on CDN

### ISSUE THREAD

**Issue by volosovich** [AzureAD/microsoft-authentication-library-for-js#345]
Hi.
Latest version doesn't exists on Microsoft CDN
https://secure.aadcdn.microsoftonline-p.com/lib/0.1.7/js/msal.min.js
https://secure.aadcdn.microsoftonline-p.com/lib/0.1.7/js/msal.js
the same problem with version 0.1.6

Good idea is adding some tag  for latest version
https://secure.aadcdn.microsoftonline-p.com/lib/@latest/js/msal.min.js

**Comment by nehaagrawal** [comment]
MSAL 0.1.7 is on CDN now. Please check.

https://secure.aadcdn.microsoftonline-p.com/lib/0.1.7/js/msal.min.js
https://secure.aadcdn.microsoftonline-p.com/lib/0.1.7/js/msal.js

**Comment by volosovich** [comment]
@nehaagrawal what about `@latest`, can you provide some solution for this case?
