### ISSUE TITLE
Return WWW-Authenticate: Bearer when no incoming token is found

### ISSUE THREAD

**Issue by jelledruyts** [AzureAD/microsoft-authentication-library-for-js#3450]
(Logging this on behalf of a customer for proper visibility.)

The library isn't following the standards when a bearer token isn't found in the request. It responds with a "www-authenticate" header that contains the text "token: false, info: token is not found" which client apps incorrectly interpret that the resource wants to use the "token" scheme (taking the first word from that text). It should just reply with "bearer" instead of the log/debug text here. The code can be seen at https://github.com/AzureAD/passport-azure-ad/blob/master/lib/bearerstrategy.js#L545-L546.

**Comment by jo-arroyo** [comment]
Closing as passport-azure-ad is in maintenance and no longer receiving updates. We are working on middleware scenarios that will be built on top of msal-node, where this issue will be addressed. Keep an eye out for msal-node updates.
