### ISSUE TITLE
Page not found on link for msal-angular errors

### ISSUE THREAD

**Issue by Flywheel** [AzureAD/microsoft-authentication-library-for-js#3456]
### Core Library

@azure/msal or msal, @azure/msal-browser

### Wrapper Library

@azure/msal-angular

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/errors.md

### Description

The document https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/errors.md in the section on wrapper libraries has a dead link for msal-angular errors.
404 at https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/errors.md   The React version listed immediately above it does resolve correctly.

These errors generally revolve around the frequently reported (and show stopping)  interaction_in_progress issue. I hope that any future Angular sample that's created can provide stronger guidance on this.

**Comment by jasonnutter** [comment]
@Flywheel Thanks, we'll make sure that link gets fixed. Correct link: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/errors.md

In regards to `interaction_in_progress` errors, they are result of an application invoking interaction while a previous interaction is still in progress. This commonly occurs when using redirects, as applications need to wait for the previous redirect operation to complete. 

Docs on redirects: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/redirects.md
Sample showing how to use the `inProgress$` subject: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-angular-v2-samples/angular11-sample-app/src/app/app.component.ts#L29

Let us know if you have any further questions!

**Comment by Flywheel** [comment]
Thanks for your response. I had been using the sample explicitly marked B2C at https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-angular-v2-samples/angular11-b2c-sample/src/app/app.component.ts  So far, this approach appears to be more stable.
