### ISSUE TITLE
Support transporting the Bearer token in a HttpOnly cookie

### ISSUE THREAD

**Issue by danquah** [AzureAD/microsoft-authentication-library-for-js#3464]
Working on a Single Page App where I would like to keep the authorization token out of reach of the client-side javascript as much as possible. A way to achieve this is to do a single request against an endpoint with an auth header, and then have the endpoint return a response that sets the value of the header as a HttpOnly cookie. This way we don't have to persist the token on the client-side.

Would you consider expanding the conditionals in https://github.com/AzureAD/passport-azure-ad/blob/fcf9b755a1bbe7a70c7340e2fdd36e8813aa8546/lib/bearerstrategy.js#L518 to include the fetch of the token from a cookie?

**Comment by danquah** [comment]
Yeah, I think I got some things mixed around here. My idea was that I want to avoid having the SPA touch the bearer-token at all. Something like this can be archived by either allowing the SPA to have access to the token for an instant, where it then immediately calls a "please store this for me" endpoint on the API which then replies with a response that sets a HttpOnly cookie with the token. Or, you could have the entire auth-flow finish off with a response that sets the same token, and then have the client periodically ping an endpoint to have the httponly cookie renewed. 

But the SPA will not be able to actually access the token in either case, and as I understand the current architecture of the library, that would not really be a supported state (which is fine for me - you have to pick your features :))

**Comment by samuelkubai** [comment]
Closing this issue.
