### ISSUE TITLE
How to avoid post request getting replayed by browser back button

### ISSUE THREAD

**Issue by deasems** [AzureAD/microsoft-authentication-library-for-js#3465]
I'm using the `form_post` response mode, lib version 4.2.1. 
After the user login is successful a POST to my domain is made in the browser. My server handles that request with this library and redirects the user to my app.
The problem is, at this point if the user hits the back button in the browser, I'm seeing the post request getting resubmitted which now fails to authenticate when this lib handles the request and I show an error page to the user.
How can we avoid this issue? Is the only option to switch to the query response mode?

**Comment by jasonnutter** [comment]
Closing, please let us know if this is still a concern.
