### ISSUE TITLE
oidcstrategy.js line 709: state is not defined (Should be source.state ?)

### ISSUE THREAD

**Issue by Jantolick** [AzureAD/microsoft-authentication-library-for-js#3467]
For some reason when trying to authenticate with Azure AD through React-Native with expo, an attempt at returning an error is not going through.

 ReferenceError: state is not defined
     at Strategy.collectInfoFromReq (/app/node_modules/passport-azure-ad/lib/oidcstrategy.js:709:78)

Looking at lines 708-709:

      if (!source.state.startsWith('CUSTOM'))
        return next(new Error(`In collectInfoFromReq: invalid custom state ${state}`));

I take it this should be:

      if (!source.state.startsWith('CUSTOM'))
        return next(new Error(`In collectInfoFromReq: invalid custom state ${source.state}`));

**Comment by jo-arroyo** [comment]
@Jantolick Can you see if using msal-node would be appropriate? Passport-azure-ad is in maintenance and will not be receiving further updates. Closing.
