### ISSUE TITLE
[Question] Is it best practice to use sessions?

### ISSUE THREAD

**Issue by DarkLite1** [AzureAD/microsoft-authentication-library-for-js#3470]
I've asked the same [question on StackOverflow](https://stackoverflow.com/questions/63464229/are-sessions-needed-for-passport-azure-ad-with-graphql) without any response so I'll try it here again.

I'm very new to web development but I've manged to set up a [client][1] and [server][2] app. The front-end uses [msal.js][3] to authenticate the user to Azure AD and the backend receives the `access_token` and verifies if the token is valid with [passport-azure-ad][4]. This is the [token flow][5]:
[![enter image description here][6]][6]

So far all is working fine except that I'm wondering how it would work on heavy load. In the [Microsoft example][7] they set the `session` to `false`. 

```javascript
// API endpoint
app.get("/hello",
    passport.authenticate('oauth-bearer', {session: false}),
```

This probably makes passport verify each and every call. Might this be an issue when invoked many times? We use `passport` as middlewware for graphql queries, nutations, resolvers, ... 

```javascript
  app.use(passport.initialize())
  passport.use(bearerStrategy)

  app.use(
    passport.authenticate('oauth-bearer', { session: false }),
    (req, _res, next) => {
      console.log('User info: ', req.user)
      console.log('Validated claims: ', req.authInfo)
      next()
    }
  )
```

This is a bit unclear from the docs of the bearerStrategy for our `v2` endpoint. If this becomes an issue it might be needed to create a graphql `login` and `logout` resolver that is only called when a user logs in and set up a `session` on the backend. 

Thank you for helping to clear up my confusion. 

  [1]: https://github.com/DarkLite1/hip
  [2]: https://github.com/DarkLite1/backend
  [3]: https://github.com/AzureAD/microsoft-authentication-library-for-js
  [4]: https://github.com/AzureAD/passport-azure-ad
  [5]: https://docs.microsoft.com/en-us/azure/active-directory/azuread-dev/v1-oauth2-client-creds-grant-flow#client-credentials-grant-flow-diagram
  [6]: https://i.stack.imgur.com/DgNa8.png
  [7]: https://github.com/Azure-Samples/active-directory-javascript-nodejs-webapi-v2/blob/master/index.js

**Comment by jasonnutter** [comment]
Closing, please open a new issue if there are still concerns.
