### ISSUE TITLE
msal logout without account selection and without redirection

### ISSUE THREAD

**Issue by deepti1805** [AzureAD/microsoft-authentication-library-for-js#3472]
### Core Library

@azure/msal-browser

### Core Library Version

2.6.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

Not applicable

### Description

We are having one scenario where we need to trigger the logout from trips.amtrak.com but the msal code resides in amtrak.com. So is it possible to log out without redirect and without account selection?

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@deepti1805 In the latest version of MSAL Browser, you can use `logoutPopup`, which perform popup-based logout. Account selection may still be required, unfortunately.
