### ISSUE TITLE
Object literal may only specify known properties, and 'provide' does not exist in type 'IPublicClientApplication'.

### ISSUE THREAD

**Issue by tlaskowski** [AzureAD/microsoft-authentication-library-for-js#3477]
### Core Library

@azure/msal-browser

### Core Library Version

2.14.0

### Wrapper Library

@azure/msal-angular

### Wrapper Library Version

2.0.0.beta-4

### Description

Hi,
I'm trying to create Angular Library using msal-angular with the following config. I have a trouble to add MsalModule.forRoot(). I was inspired https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/configuration.md. Could you help me understand what is wrong with my example? Thanks in advance

<img width="823" alt="Screenshot 2021-04-16 at 09 54 43" src="https://user-images.githubusercontent.com/19552442/114991370-cbb8c180-9e99-11eb-9681-4e198557ceed.png">

### MSAL Configuration

```javascript
export function MSALInstanceFactory(config: any): IPublicClientApplication {
  return new PublicClientApplication({
    auth: {
      clientId: config.clientId,
      authority: config.authority,
      redirectUri: config.redirectUri,
      postLogoutRedirectUri: config.postLogoutRedirectUri,
      navigateToLoginRequestUrl: false,
    },
    cache: {
      cacheLocation: 'sessionStorage',
      storeAuthStateInCookie: isIE, // set to true for IE 11
    },
  });
}
```

### Relevant Code Snippets

```javascript
export class AzureAdModule {
  static forRoot(config: any): ModuleWithProviders {
    return {
      ngModule: AzureAdModule,
      providers: [
        {provide: CONFIG, useValue: config},
        {
          provide: HTTP_INTERCEPTORS,
          useClass: MsalInterceptor,
          multi: true,
        },
        MsalModule.forRoot({
            provide: MSAL_INSTANCE,
            deps: [config],
            useFactory: MSALInstanceFactory,
          },
          {
            provide: MSAL_GUARD_CONFIG,
            useFactory: MSALGuardConfigFactory,
          },
          {
            provide: MSAL_INTERCEPTOR_CONFIG,
            deps: [config],
            useFactory: MSALInterceptorConfigFactory,
          },
        ),
      ],
    };
  }
}
```

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@tlaskowski The first argument to `MsalModule.forRoot` should be the `IPublicClientApplication` instance itself:

```js
MsalModule.forRoot(
  MSALInstanceFactory(config), 
  MSALGuardConfigFactory(),
  MSALInterceptorConfigFactory()
);
```

**Comment by tlaskowski** [comment]
It helps:) thank a lot @jasonnutter
