### ISSUE TITLE
MSAL version 2 beta - missing entities?

### ISSUE THREAD

**Issue by parmjitv** [AzureAD/microsoft-authentication-library-for-js#3479]
### Core Library

@azure/msal-browser

### Core Library Version

2.14.0

### Wrapper Library

@azure/msal-angular

### Wrapper Library Version

2.0.0-beta.4

### Description

Hello All,

Thank you for providing such a great product!

I am updating an angular application to use the latest v2 betas of the MSAL libraries for JS.  Apparently, a number of entities that were previously available in v1 are now missing:

1) @azure/msal-angular => `MsalService` class
- function `getScopesForEndpoint()`
- function `clearCacheForScope()`

2) msal (replaced in v2, I believe, by @azure/msal-common)
- class `CryptoUtils`
- type `AuthResponse`
- enum `ServerHashParamKeys`

I do not see any reference to these in the latest documentation.  Can these entities still be found in v2 of the libraries, or have they been retired?

Many Thanks!

Parmjit V.

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by jasonnutter** [comment]
> function getScopesForEndpoint()

This is now a private function of the MSAL Interceptor class: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/src/msal.interceptor.ts#L107

> function clearCacheForScope()

This function has been removed.

> class CryptoUtils

This has been renamed to `CryptoOpts`: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/src/crypto/CryptoOps.ts

> type AuthResponse

This has been renamed to `AuthenticationResult`: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/src/response/AuthenticationResult.ts

> enum ServerHashParamKeys

This has been renamed to `AADServerParamKeys`: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/src/utils/Constants.ts#L90

Do you have specific questions regarding any of these?

**Comment by parmjitv** [comment]
Thanks Jason!  I believe this will be adequate, if I have any specific questions I will submit as a new issue.

Cheers,

Parmjit V.
