### ISSUE TITLE
MSAL.js with Server Side auth

### ISSUE THREAD

**Issue by pra7eek** [AzureAD/microsoft-authentication-library-for-js#3485]
### Core Library

@azure/msal-browser

### Core Library Version

2.14.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

NA

### Description

Hi Team,

How can we retrieve an `authorization code` from MSAL.js and send it to backend for further processing? The UI doesn't have to handle anything there but retrieve a permanent authorization code. Backend will do modifications in background to user's calendar based on some actions.

I have gone through multiple documents and samples, I couldn't find anyway to do so. Please guide and help.

Thanks.

### Source

External (Customer)

**Comment by derisen** [comment]
@pra7eek this is not supported and in general, moving around sensitive information like `authorization code` is not a good idea. Instead, have you considered the [on-behalf-of flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow)? This should be able cover your use case. 

You can find a [sample project here](https://github.com/Azure-Samples/ms-identity-javascript-tutorial/tree/main/4-AdvancedGrants/1-call-api-graph). If you run into any problems, feel free to raise an issue there.

**Comment by pra7eek** [comment]
@derisen thank you for the response. The "on-behalf-of flow" might work out but I need to test it first. I cloned the sample project to try it out. I did all the steps which are mentioned in the sample app readme, but I'm seeing the following error once the login popup closes after I authorize it:

`AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'`

After searching on the interest, I tried enabling "Allow public client flows", but I still see this error.

**Comment by derisen** [comment]
@pra7eek just [answered](https://github.com/Azure-Samples/ms-identity-javascript-tutorial/issues/16).

**Comment by pra7eek** [comment]
@derisen , In the example, I see that every request to the server has a bearer token. So in theory, can this bearer token be saved in some database permanently? As I mentioned earlier, there is no UI interaction once we retrieve the token, everything has to run on the server based on some actions. What is the expiry time of the token?

**Comment by pra7eek** [comment]
I noticed that UI refreshes the token after a while. This solution won't work for us. UI just needs to have one time connect and give that token to the server api and things will be handled by a backend service. Is there anyway to refresh this token on the server side like the other OAuth apps?

**Comment by derisen** [comment]
> @derisen , In the example, I see that every request to the server has a bearer token. So in theory, can this bearer token be saved in some database permanently? As I mentioned earlier, there is no UI interaction once we retrieve the token, everything has to run on the server based on some actions. What is the expiry time of the token?

@pra7eek This is possible. In this case your frontend and backend apps should share the same app registration (i.e. client Id). Your backend app then can use MSAL's `AcquireTokenSilent()` API to refresh the tokens as needed.

You would also need a mechanism that would trigger the front-end to prompt the user for interactive token acquisition when the back-end can no longer use the token for some reason (token is expired, MFA required etc.). For instance, when the backend receives an interaction required error from Graph API, you would propagate this error to front-end). 

See here for instance a [.NET sample project](https://github.com/Azure-Samples/ms-identity-dotnet-advanced-token-cache) that implements a scenario similar to yours. We don't have a similar sample for JavaScript, but in principle you should be able to replace the .NET frontend there with a JS frontend. 

cc @jasonnutter

**Comment by pra7eek** [comment]
@derisen, That's the issue. 

We can't rely on the UI for the further authentication. For example: 

A person connects their calendar with our project using the lib so that we can add events to his calendar on his behalf. We save the access token in the database for further use. Now after a day or so, we have an action which needs us to add an event to the calendar, but the token has expired, and it's all happening somewhere in API communication. Frontend is not involved there. We need to refresh that token right there in the backend. 

I feel it's a pretty common scenario where we need to save the `refresh token` in the backend so that things happen in background. Please let me know if there is anyway to handle this.

**Comment by derisen** [comment]
@pra7eek sorry if I haven't made it clear -you will still refresh the token in the backend, its just that if (for whatever reason) the backend is not able to refresh it, you'll need to notify the frontend to prompt the user.

Please go through [this sample](https://github.com/Azure-Samples/ms-identity-dotnet-advanced-token-cache/tree/master/1-Integrated-Cache/1-2-WebAPI-BgWorker) once and see if that corresponds to your case.
FE authenticates user and gets token and user account object
