### ISSUE TITLE
URIError on Safari

### ISSUE THREAD

**Issue by saadataz** [AzureAD/microsoft-authentication-library-for-js#3491]
### Core Library

@azure/msal-browser

### Core Library Version

2.12.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

NA

### Description

When passing "viva-pi%C3%B1ata-tip" as state in loginRedirect, it somehow gets converted into "viva-pi%25u00f1ata-tip". when [StringUtils](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/fee7efbd7616e144918c969af5cce2c927db0ba0/lib/msal-common/src/utils/StringUtils.ts#L66) tries to run that through decodeURIComponent, it fails with URIError

Temporary work around is to URIEncode the state before passing it to loginRedirect using encodeURIComponent.

Could be a [similar issue](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2088) 

### Error Message

URIError

### MSAL Configuration

```javascript
{
  "auth": {
    "clientId": "1f907974-e22b-4810-a9de-d9647380c97e",
    "authority": "https://login.microsoftonline.com/consumers",
    "navigateToLoginRequestUrl": false
  },
  "cache": { "cacheLocation": "localStorage" }
}
```

### Relevant Code Snippets

```javascript
// On app startup
const pca = new PublicClientApplication(msalConfig);
await pca.loginRedirect({
  scopes: [
    "service::http://Passport.NET/purpose::PURPOSE_XBOX_CLOUD_CONSOLE_TRANSFER_TOKEN",
  ],
  state: "viva-pi%C3%B1ata-tip",
});

// Or successful redirect
try {
  const redirectResult = await pca.handleRedirectPromise();
} catch (err) {
  // err = URIError
}
```

### Reproduction Steps

see above code snippet

### Expected Behavior

`handleRedirectPromise` should not throw an error and `viva-pi%C3%B1ata-tip` should be returned as is in the state

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Safari

### Source

Internal (Microsoft)

**Comment by jasonnutter** [comment]
@saadataz Thanks for the report, we'll look into this. For now, I would recommend using the workaround of encoding your state value before you pass it to MSAL, and then decoding it when handling the response. This should mitigate encoding issues.

**Comment by bmahall** [comment]
@saadataz  I am not able to reproduce this on Safari. Can you please share a network trace of this behavior? Feel free to share on email or here. 
Also, can you verify what version of msal-browser you are using. Kindly update to the latest published version and let us know if you run into this issue again.
