### ISSUE TITLE
User can login twice

### ISSUE THREAD

**Issue by aosyatnik** [AzureAD/microsoft-authentication-library-for-js#3492]
### Core Library

@azure/msal or msal

### Core Library Version

1.4.4

### Wrapper Library

@azure/msal-angular

### Wrapper Library Version

1.1.2

### Description

It's worth to mention, that issue is not constantly reproducible. The main issue, that a user can log in with different accounts in 1 browser, which leads to other issues.

### MSAL Configuration

I can provide you my msal configs, but I'm not sure if it's secure to post them here.

### Relevant Code Snippets

There is not really any code snippets, just the usual `this.authService.loginRedirect(authParams);`, where `authParams` is an object with some additional params, that we need to use after login. And usual b2c login form:

![image](https://user-images.githubusercontent.com/8158404/115359937-70e7d880-a1bf-11eb-8ac5-dcc657a751f1.png)

### Reproduction Steps

I could reproduce it once like this:
1. Open 2 tabs.
2. In the first tab sign in with your b2c user.
3. In the second tab sign-up as a new user.
4. From the second tab you will be redirected to web site and in the first tab you are logged in as well as in the second tab you are logged in but with a different user. This may lead to other issues.

My testers could reproduce a similar issue, but just with the sign-in flow:
1. Open 2 tabs.
2. Sign in with 1 user.
3. Sign in with another user in some time (not sure how long you should wait?)
4. From the second tab you will be redirected to web site and in the first tab, you are logged in as well as in the second tab you are logged in but with a different user. This may lead to other issues.
(c) Testers

Tested only in Chrome.

Looks like `SelfAsserted` endpoint is not consistent and randomly fails when it comes to the simultaneous logins.

### Expected Behavior

Usually, `SelfAsserted` fails with 400 error, which is fine. But it's not robust. It would be nice either to test it more with the simultaneous logins or restrict the user from navigation to this page if the user already opened another login page.

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@aosyatnik To clarify, you don't want a user to be able to log in with multiple accounts in the same browser? If you want to prevent multiple accounts, your app should check if MSAL has a cached account, and not allow the user to initiate login if they are already logged in.

And please provide your MSAL configuration (this is not sensitive data), thanks!

**Comment by aosyatnik** [comment]
@jasonnutter hi, thank you for such a fast reply.

> you don't want a user to be able to log in with multiple accounts in the same browser? 
Yes, exactly, that's what we want.

MSAL config for dev:

`environment.ts`
```
export const environment = {
  production: false,
  debug: true,
  endpoint: 'http://localhost:7071/api/',
  scopeUri: ['https://portmonsysdevb2c.onmicrosoft.com/c878f897-9c92-4ee1-abae-53311382f537/Backend'],
  clientId: '5d460340-2df0-4e1c-80ed-bb452620f735',
  b2cPolicies: {
    names: {
      signUpSignIn: 'B2C_1_Signup',
      resetPassword: 'B2C_1_PasswordReset',
      profileEdit: 'B2C_1_Edit_Profile'
    },

    authorities: {
      signUpSignIn: {
        authority: 'https://portmonsysdevb2c.b2clogin.com/portmonsysdevb2c.onmicrosoft.com/B2C_1_Signup'
      },
      resetPassword: {
        authority: 'https://portmonsysdevb2c.b2clogin.com/portmonsysdevb2c.onmicrosoft.com/B2C_1_PasswordReset'
      },
      editProfile: {
        authority: 'https://portmonsysdevb2c.b2clogin.com/portmonsysdevb2c.onmicrosoft.com/B2C_1_Edit_Profile',
      }
    }
  }
};
```

Used in `app.module.msal.factory.ts`:
```
import { MsalAngularConfiguration } from '@azure/msal-angular';
import { Configuration } from 'msal';
import { environment } from 'src/environments/environment';

export const protectedResourceMap: [string, string[]][] = [
  [environment.endpoint, environment.scopeUri],
  ['./assets', null] // Assets are not protected resources.
];

// Default route after msal login redirect.
const LOGIN_ROUTE = '/login';

export function MSALConfigurationFactory(): Configuration {
  return {
    auth: {
      clientId: environment.clientId,
      authority: environment.b2cPolicies.authorities.signUpSignIn.authority,
      validateAuthority: false,
      redirectUri: window.origin + LOGIN_ROUTE,
      postLogoutRedirectUri: window.origin,
      navigateToLoginRequestUrl: true
    },
    cache: {
      storeAuthStateInCookie: false
    },
    system: {
      loadFrameTimeout: 10000
    }
  };
}

export function MSALAngularConfigFactory(): MsalAngularConfiguration {
  return {
    popUp: false,
    protectedResourceMap
  };
}

```

Connected in `app.module.ts` as this:
```
@NgModule({
  declarations: [...],
  imports: [...],
  providers: [
      ....,
      {
      provide: MSAL_CONFIG,
      useFactory: MSALConfigurationFactory
    },
    {
      provide: MSAL_CONFIG_ANGULAR,
      useFactory: MSALAngularConfigFactory
    },
]);
```

We are using `MsalGuard` and as I said, usually, it works, but sometimes different users can log in with 1 browser.

**Comment by hectormmg** [comment]
Hi @aosyatnik ! As @jasonnutter suggests, your app needs to check if MSAL already has an account in the cache and block the login if that's the case. You can see our [account APIs' documentation here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/login-user.md#account-apis). Please let us know if this helps so we can close the issue!

**Comment by aosyatnik** [comment]
@hectormmg ok, yes, we can close the issue.
