### ISSUE TITLE
interaction_in_process

### ISSUE THREAD

**Issue by ghost** [AzureAD/microsoft-authentication-library-for-js#3493]
### Core Library

@azure/msal-browser

### Core Library Version

2.14.0

### Wrapper Library

@azure/msal-angular

### Wrapper Library Version

2.0.0-beta.4

### Description

I am using MSAL Library v 2.13 for authentication and authorization my angular a of app, consider a scenario - I hit the browser with my hosting/redirect URI, it auth/auth me and lands me back to the same page but the session storage shows interaction_in_process and I have to click to any route that has msal guard so that I force msal:handleRedirectStart event.
It only happens when we login for first time, if I open the duplicate tab I don't see any issue. I have SSO enabled and don't have any method for login and logout as that is the expectation. I tried same on localhost, but over there I don't have to force msal:handleRedirectStart and works as expected.

### MSAL Configuration

```javascript
export function MSALInstanceFactory(): IPublicClientApplication {
  return new PublicClientApplication({
    auth: {
      clientId: '---------',
      authority: '------',
      redirectUri: '------------',
      postLogoutRedirectUri: '/',
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Info,
        piiLoggingEnabled: false
      }
    }
  });
}

export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
  const protectedResourceMap = new Map<string, Array<string>>();
  protectedResourceMap.set('https://graph.microsoft.com/v1.0/me', ['user.read']);

  return {
    interactionType: InteractionType.Redirect,
    protectedResourceMap
  };
}

export function MSALGuardConfigFactory(): MsalGuardConfiguration {
  return { 
    interactionType: InteractionType.Redirect,
    authRequest: {
      scopes: ['user.read']
    },
    loginFailedRoute: '/login-failed'
  };
}
```

### Relevant Code Snippets

```javascript
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { MsalGuard } from '@azure/msal-angular';
import { HistoryComponent } from './history/history.component';
import { HomeComponent } from './home/home.component';
import { LoginFailedComponent } from './login-failed/login-failed.component';

const routes: Routes = [
  { path: '', component : HomeComponent,  canActivate: [MsalGuard]},
  { path: 'home', component: HomeComponent ,  canActivate: [MsalGuard]},
  { path: 'history', component: HistoryComponent,  canActivate: [MsalGuard] },
  { path: 'login-failed', component: LoginFailedComponent },
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }
```

### Reproduction Steps

I am hosting application on AWS S3 Bucket.

### Expected Behavior

I want user to enter URL and after auth/auth should land on page with specific msalguard enabled home component.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge

### Regression

@azure/msal-browser 2.14.0

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@kimayapawaskar This error happens because your app is making an interactive request while another request is still in progress. See: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/redirects.md

We recommend that Angular applications use a dedicated redirect URI that does not have the MSAL Guard to help mitigate these sorts of issues. Please see this document for more details: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/FAQ.md#pathlocationstrategy

**Comment by kimayapawaskar** [comment]
I implemented https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/redirects.md but initially it is not auth/auth user. It is auth/auth when I route to component with MSALGuard.
