### ISSUE TITLE
logoutRedirect() does not clear session storage nor logs out the user. 

### ISSUE THREAD

**Issue by enaSo97** [AzureAD/microsoft-authentication-library-for-js#3494]
### Core Library

@azure/msal-browser

### Core Library Version

2.13.1

### Wrapper Library

@azure/msal-react

### Wrapper Library Version

1.0.0-beta.1

### Description

I am calling logoutRedirect() on signout button click, but it only redirects to homepage and does not logs out the user. 

I've looked into session storage, and when signout button is clicked it doesn't clear, it would just redirect to the post-redirect-uri. 

Also, is it expected to not ask credentials again when user tries to log back in? 

### MSAL Configuration

```javascript
export const msalConfig = {
    auth: {
        authority: signInAuthority,
        clientId: applicationID,
        redirectUri: window.location.origin,
        postLogoutRedirectUri: window.location.origin,
        validateAuthority: false,
        knownAuthorities: [`${tenantSubdomain}.b2clogin.com`],
    },
    cache: {
        cacheLocation: "sessionStorage",
        storeAuthStateInCookie: false,
    },
    tokenRefreshUri: window.location.origin,
};
```

### Relevant Code Snippets

```javascript
<a id="signOut" className="menu-item" href="/" onClick={() => instance.logoutRedirect({
                    account: instance.getActiveAccount,
                    postLogoutRedirectUri: "http://localhost:3000",
                })}>
                    Sign out
                </a>
```

### Identity Provider

Azure B2C Basic Policy

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@enaSo97 To clarify, are you saying nothing is cleared from session storage? Note, MSAL will only clear MSAL-related cache entries from browser storage.

> Also, is it expected to not ask credentials again when user tries to log back in?

Yes, please see here: https://docs.microsoft.com/en-us/azure/active-directory-b2c/session-behavior?pivots=b2c-user-flow#sign-out

**Comment by enaSo97** [comment]
> Yes, please see here: https://docs.microsoft.com/en-us/azure/active-directory-b2c/session-behavior?pivots=b2c-user-flow#sign-out

All the accounts that are in B2C right now is just local accounts using, email and password. no IDP is used. In the document you provided it says 
> However, if local accounts are used, the user's session ends properly.

**Comment by enaSo97** [comment]
@jasonnutter 

I'm getting same behaviour every time I try to logout. I am able to logout from the home component but it seems like I can't logout if I go to another react router. It returns `endpoint_resolution_error` in session storage. 

I've tried on Microsoft Edge, Chrome, and Brave.

**Comment by hectormmg** [comment]
Hi @enaSo97 . I believe your issue is happening because of the way you are calling `instance.getActiveAccount`. You are passing the function reference instead of the actual account

Can you try adjusting your code to use parentheses in the getActiveAccount call and let me know if that solves your issue?


```typescript
<a id="signOut" className="menu-item" href="/" onClick={() => instance.logoutRedirect({
                    account: instance.getActiveAccount(),
                    postLogoutRedirectUri: "http://localhost:3000",
                })}>
                    Sign out
                </a>
```
