### ISSUE TITLE
ms-msal-angular is not in npm?

### ISSUE THREAD

**Issue by erickbp** [AzureAD/microsoft-authentication-library-for-js#350]
[doc says npm install ms-msal-angular --save](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/na/msalAngular/lib/msalAngular/README.md#installation)

**Comment by navyasric** [comment]
@erickbp This is work in progress as it is on a feature branch and not yet merged to dev or released. Therefore, we have not yet published to npm. Please watch the dev branch readme and Releases for updates on Angular support.
