### ISSUE TITLE
Proof-of-Possession flow error

### ISSUE THREAD

**Issue by forellendev** [AzureAD/microsoft-authentication-library-for-js#3503]
### Core Library

@azure/msal-browser

### Core Library Version

2.14.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

No wrapper

### Description

Hi,

I'm trying to implement the [Proof-of-Possession flow](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/ef11fd7eb7f523fba1cf2002579ec75e4179b619/lib/msal-browser/docs/access-token-proof-of-possession.md), but get an error.

I tried both `myMSALObj.acquireTokenRedirect` and `myMSALObj.acquireTokenSilent` as requests (acquireTokenSilent seems to never work, even when not using a PoP flow), but with no success. I suspect that some flags are wrongly set in the cookies or localStorage and bring the redirection to a halt.

### Error Message

`BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.`

### MSAL Configuration

```javascript
auth: {
  clientId: "<own-client-id",
  authority: "<own-authority",
  redirectUri: "http://localhost:8081/,
  navigateToLoginRequestUrl: true
},
cache: {
  cacheLocation: "localStorage",
  storeAuthStateInCookie: false
}
```

### Relevant Code Snippets

```javascript
// PoP configuration
export const popTokenRequest = {
  scopes: ["openid", "profile", "offline_access"],
  authenticationScheme: msal.AuthenticationScheme.POP,
  resourceRequestMethod: "POST",
  resourceRequestUri: '<my-own-backend-resource-server>'
};
```

### Reproduction Steps

Just one step really, to pass popTokenRequest into
`await msalInstance.acquireTokenRedirect(popTokenRequest);`

### Expected Behavior

I suspected a redirect to the login screen when not logged in, or to the homepage of my site when logged in. Instead I get an `interaction_in_progress` and the application hangs.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge

### Source

Internal (Microsoft)

**Comment by jasonnutter** [comment]
@forellendev It seems like there are temporary cache values stuck in teh cache. Can you try logging out and trying the requests again? Also, make sure you are invoking `handleRedirectPromise` to process the redirect request.

**Comment by forellendev** [comment]
Thank you jason! I emptied the local storage and ran the application again, but with no success. I get redirected to the login page, get an authorization code, but then the local storage is quickly filled up with msal entries, one of them being `*.interaction.status` set to `interaction_in_progress`.
I followed the [documentation](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/ef11fd7eb7f523fba1cf2002579ec75e4179b619/lib/msal-browser/docs/access-token-proof-of-possession.md) but a sample app would be nice to see if PoP is functioning.

**Comment by derisen** [comment]
@forellendev another PoP sample here: [Angular SPA calling .NET web API](https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/tree/main/7-AdvancedScenarios/2-call-api-pop)

**Comment by hectormmg** [comment]
@forellendev following up, did our sample help resolve your issue?

**Comment by forellendev** [comment]
@hectormmg Unfortunately I still get `interaction_in_progress`, despite following the sample.

**Comment by tnorling** [comment]
@forellendev Is this still an issue?
