### ISSUE TITLE
The provided value for the input parameter 'scope' is not valid

### ISSUE THREAD

**Issue by jrmcdona** [AzureAD/microsoft-authentication-library-for-js#3504]
### Core Library

@azure/msal-browser

### Core Library Version

2.14

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

I have a Microsoft first party app id.   I only care about MSA so I use consumers.  This app only is checked for Microsoft Accounts and not for AAD.

I am getting an error message about not valid scope.  However, I am only passing in one value for scope which is ['9550e889-e1b2-4c54-96b5-f09de31ba11e/User.Access'].   But the error mentions opendid profile and offline_access which maybe causing my issue here.

### Error Message

The provided value for the input parameter 'scope' is not valid. The scope '9550e889-e1b2-4c54-96b5-f09de31ba11e/User.Access openid profile offline_access' does not exist

### MSAL Configuration

```javascript
const msalConfig: msal.Configuration = {
            auth: {
              clientId: "074c36cd-684f-47b8-a8bc-b4e100b693b6",
              authority: "https://login.microsoftonline.com/consumers",
              redirectUri: "https://debug-community.windows.com:4443/en-us/redirect",
              navigateToLoginRequestUrl: false,
            },
            cache: {
              cacheLocation: "localStorage",
              storeAuthStateInCookie: false,
            }
          };
```

### Relevant Code Snippets

```javascript
public loginRedirect(redirectUrl: string = undefined) {
        let url = redirectUrl ? redirectUrl : this.router.url;
        this.msalInstance.loginRedirect({
            scopes: ['9550e889-e1b2-4c54-96b5-f09de31ba11e/User.Access'],
            state: url,
        });
    }
```

### Reproduction Steps

If you use my configuration you could reproduce this.

### Expected Behavior

My scope would be valid.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Regression

@azure/msal-browser": "^2.14.0"

### Source

Internal (Microsoft)

**Comment by jasonnutter** [comment]
@jrmcdona `openid profile offline_access` are the default OIDC scopes, so they are not the problem. Can you please verify the value you registered for your custom scope? They are often in the format of `api://9550e889-e1b2-4c54-96b5-f09de31ba11e/User.Access`.

**Comment by jrmcdona** [comment]
@jasonnutter  in the first party portal here at Microsoft (not the Azure portal) you don't have that option to do it like that.   I have it working like this in a different project.

I went ahead and tried it but same error:

The+provided+value+for+the+input+parameter+'scope'+is+not+valid.+The+scope+'api://9550e889-e1b2-4c54-96b5-f09de31ba11e/User.Access+openid+profile+offline_access'+does+not+exist.

I can confirm that this scope exists in the First party portal for ID 9550e889-e1b2-4c54-96b5-f09de31ba11e.

**Comment by jrmcdona** [comment]
@jasonnutter  I just noticed on the API MSA isn't checked only AAD is.  So  that could be the issue, will have to redo that and try again.

**Comment by jrmcdona** [comment]
Yup that was the issue.
