### ISSUE TITLE
loginPopup is not storing token in localStorage

### ISSUE THREAD

**Issue by Umbreonn** [AzureAD/microsoft-authentication-library-for-js#3507]
### Core Library

@azure/msal-browser

### Core Library Version

2.13.1

### Wrapper Library

@azure/msal-angular

### Wrapper Library Version

2.0.0-beta.4

### Description

Hello,

I'm trying to upgrade my msal version to 2 but I'm facing some issues. After successfully login on my app I can't find my token in my localStorage.

### Error Message

no error message

### MSAL Configuration

```javascript
export function MSALInstanceFactory(): IPublicClientApplication {
  return new PublicClientApplication({
    auth: {
      clientId: environment.authenticationConfiguration.msClientId,
      authority: environment.authenticationConfiguration.msIssuer,
      postLogoutRedirectUri: '/',
      navigateToLoginRequestUrl: true
    },
    cache: {
      cacheLocation: 'localStorage',
      storeAuthStateInCookie: true
    }
  });
}

export function MsalGuardConfigFactory(): MsalGuardConfiguration {
  return {
    interactionType: InteractionType.Popup,
    authRequest: {
      scopes: [
        'user.read',
        'openid',
        'profile',
      ]
    }
  };
}

export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
  const protectedResourceMap = new Map<string, Array<string>>();
  protectedResourceMap.set(environment.API_URL, ['user.read']);

  return {
    interactionType: InteractionType.Redirect,
    protectedResourceMap
  };
}

  providers: [
    {
      provide: HTTP_INTERCEPTORS,
      useClass: MsalInterceptor,
      multi: true
    },
    {
      provide: MSAL_INSTANCE,
      useFactory: MSALInstanceFactory
    },
    {
      provide: MSAL_GUARD_CONFIG,
      useFactory: MsalGuardConfigFactory
    },
    {
      provide: MSAL_INTERCEPTOR_CONFIG,
      useFactory: MSALInterceptorConfigFactory
    },
    MsalService,
    MsalBroadcastService
  ]
```

### Relevant Code Snippets

```javascript
public login(): void {
    this.msalService.loginPopup().subscribe(
      {
        next: (response: AuthenticationResult) => {
          if(response.account) {
            this.onSuccessLogin(response.account);
          }
        },
        error: (error) => {
          console.log(error)
          this.onFailedLogin();
        }
      });
  }
```

### Reproduction Steps

1.Use my config
2.Use my login function
3. See if token is stored in localStorage

### Expected Behavior

This should store my token in localStorage 

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Safari

### Source

Internal (Microsoft)

**Comment by jasonnutter** [comment]
@Umbreonn Are you able to reproduce this with one of our samples?

**Comment by jasonnutter** [comment]
@Umbreonn And to be clear, are you saying a token that was present in localStorage before you performed the upgrade was removed after you logged in?

**Comment by Umbreonn** [comment]
> @Umbreonn Are you able to reproduce this with one of our samples?

I will try this!



> @Umbreonn And to be clear, are you saying a token that was present in localStorage before you performed the upgrade was removed after you logged in?

Before the upgrade when I was logged my token was in the localstorage, that's not the case anymore, I can't find it.

**Comment by hectormmg** [comment]
@Umbreonn have you been able to reproduce the issue with one of our samples?
