### ISSUE TITLE
what do i pass in response_type and scope to get access_token instead of id_token

### ISSUE THREAD

**Issue by iaakash19** [AzureAD/microsoft-authentication-library-for-js#351]

**Comment by nehaagrawal** [comment]
You need to use login api to get the id_token and acquireToken api for access_token. More information can be found here.

https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Public-APIs

**Comment by iaakash19** [comment]
Thanks Neha!! i will get the id_token and then use the acquireToken fns to get the desired access_token. Will update.

**Comment by iaakash** [comment]
hello @nehaagrawal, well i've tried the underlying api method but it returns the same token as i get from id_token in url. I need to send *token* in url so i can get *access_token* in return. can you suggest some alternate way?
