### ISSUE TITLE
Twitter popup login does not work

### ISSUE THREAD

**Issue by vladkosarev** [AzureAD/microsoft-authentication-library-for-js#352]
I am not sure why issue #177 was closed. Twitter login still does now work.
Here's the error -
```
Refused to display 'https://api.twitter.com/oauth/authenticate?oauth_token=VRVdnwAAAAAA6-NZAAAFGHgZffG' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self' https://tweetdeck.twitter.com https://tdapi-staging.smf1.twitter.com https://tdapi-staging.atla.twitter.com https://tweetdeck.localhost.twitter.com".
```

**Comment by jrebagliatti** [comment]
I think I have a similar issue. I got:
```
Refused to display 'https://accounts.google.com/o/oauth2/auth.....' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
```
When I'm trying to authenticate a Google user. Seems that the issue is being thrown during ``acquireTokenSilent`` operation.

I configured my Azure B2C with both Multi-Tenant AD and Google, with AD authentication works fine.

**Comment by sameerag** [comment]
@vladkosarev @jrebagliatti Is this issue still seen? I am able to login with twitter using the basic SUSI policy. Please let us know if this issue still persists.

**Comment by jrebagliatti** [comment]
Thanks @vladkosarev . We ended up implementing [hello.js|https://adodson.com/hello.js/] due to the limitation described above. I'll give a try to the new version of MSAL and let you know.
Thanks!
