### ISSUE TITLE
React B2C Sample - Token is requested twice

### ISSUE THREAD

**Issue by aron89682** [AzureAD/microsoft-authentication-library-for-js#3522]
### Core Library

@azure/msal or msal

### Core Library Version

2.14.0

### Wrapper Library

@azure/msal-react

### Wrapper Library Version

1.0.0-beta.0

### Description

When requesting an access token, it is making 2 requests.

### MSAL Configuration

```javascript
// Config object to be passed to Msal on creation
export const msalConfig = {
    auth: {
        clientId: "9067c884-9fa6-414f-9aa4-a565b1cb46be",
        authority: "https://fabrikamb2c.b2clogin.com/fabrikamb2c.onmicrosoft.com/b2c_1_susi",
        knownAuthorities: ["fabrikamb2c.b2clogin.com"],
        redirectUri: "http://localhost:4200",
        postLogoutRedirectUri: "http://localhost:4200"
    }
};

// Add here scopes for id token to be used at MS Identity Platform endpoints.
export const loginRequest = {
    scopes: ["https://fabrikamb2c.onmicrosoft.com/helloapi/demo.read"]
};

export const forgotPasswordRequest = {
    authority: "https://fabrikamb2c.b2clogin.com/fabrikamb2c.onmicrosoft.com/b2c_1_reset"
}
```

### Relevant Code Snippets

```javascript
useEffect(() => {
        if (account && inProgress === "none") {
            instance.acquireTokenSilent({
                ...loginRequest,
                account: account
            }).then((response) => {
                setAtsResponse(response);
                console.log('Getting Token')
            });
        }
    }, [account, inProgress, instance]);
```

### Reproduction Steps

Replace the matching code within Protected.jsx as it has the console log section:
console.log('Getting Token')

Then run and look at the console log.

### Expected Behavior

It should only be ran once

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@tnorling Can you please take a look this issue?

**Comment by tnorling** [comment]
@aron89682 Thanks for raising this. There appears to be a bug in the `useAccount` hook causing an extra state update which is causing this behavior. I'll work on a fix, but in the meantime you can try using the `accounts` array returned from the `useMsal` hook

**Comment by aron89682** [comment]
Yep that's what I did to fix it.
