### ISSUE TITLE
acquireTokenSilent always gets new token via network, ignoring cache

### ISSUE THREAD

**Issue by arsenzavialov** [AzureAD/microsoft-authentication-library-for-js#3526]
### Core Library

@azure/msal-browser

### Core Library Version

2.14.0

### Wrapper Library

@azure/msal-react

### Wrapper Library Version

1.0.0-beta.1

### Description

Hi, i use acquireTokenSilent every time to call .net core api which requires idToken as bearer jwt, but i faced the problem that this method always acquires new idToken through network ignoring my cache in sessionStorage. Can someone explain me what am i doing wrong. Code snippets and my msal config are provided below.
Also my session storage looks like this: 
![image](https://user-images.githubusercontent.com/79301784/115923168-84789500-a486-11eb-9f05-a2b90f93a800.png)
Thank you!

### MSAL Configuration

```javascript
export const msalConfig = {
    auth: {
        clientId: "[my_clien_id]",
        authority: "https://login.microsoftonline.com/[guid]",
        redirectUri: "http://localhost:3000/",
    },
    cache: {
        cacheLocation: "sessionStorage", 
        storeAuthStateInCookie: false,
    },
    system: {
        loggerOptions: {
            loggerCallback: (level, message, containsPii) => {
                if (containsPii) {
                    return;
                }
            }
        }
    }
};
```

### Relevant Code Snippets

```javascript
import React, {useState, useMemo, useEffect} from "react";
import logo from "./assets/logo.png";
import "./styles.css";
import Form from "./Form";
import Output from "./Output";
import {EventType, InteractionType} from "@azure/msal-browser";
import {
  useMsal,
  useAccount,
  useIsAuthenticated,
  MsalAuthenticationTemplate,
  useMsalAuthentication
} from "@azure/msal-react";
import { getHomeInsuranceAddresses } from './api/getHomeInsuranceAddresses';
import {Button, Menu, MenuItem} from "@material-ui/core";
import {trustedGroups} from "./configuration";

const ErrorComponent = ({ error }) => {
  return <div className="m-4">
    <h4>An error occurred: {error.errorMessage}</h4>
    <div>Refresh the page to retry the login attempt</div>
  </div>;
};


const shapeResponse = (response) => {
  if (response === null
    || response.getHomeInsuranceAddressesResponse === null
    || response.getHomeInsuranceAddressesResponse.Addresses === null
    || response.getHomeInsuranceAddressesResponse.Addresses.length === 0) {
    //TODO: if the Array is empty, should we display something like "no data was found"?
    return [];
  } else {
    const allAdresses = response.getHomeInsuranceAddressesResponse.Addresses;
   // allAdresses.push(allAdresses[0]);
    return allAdresses
  }
}

const App = () => {
  const [loading, setLoading] = useState(false);
  const [response, setResponse] = useState(null);
  const [error, setError] = useState(null);
  const [isInAllowedGroup, setIsInAllowedGroup] = useState(false);


  const {instance, accounts} = useMsal();
  const account = useAccount(accounts[0] || {});
  const isAuthenticated = useIsAuthenticated();


  const handleSubmit = async (data) => {
    //...
    try {
      debugger
      const tokenResp = await instance.acquireTokenSilent({account: account});
      const body = {
        getHomeInsuranceAddresses: {
          ...data
        }
      };
      const dataResp = await getHomeInsuranceAddresses(body, tokenResp.idToken);

      setResponse(dataResp);
    } catch (error) {
      console.error(error);
      setError(error);
    } finally {
      setLoading(false);
    }
  };

 

  const handleLogout = () => instance.logout()

 //....
  const responseShaped = useMemo(() => shapeResponse(response), [response]);

  return <>
   
    <main>
      <div className="container-sm">
        <MsalAuthenticationTemplate
            interactionType={InteractionType.Redirect}
            errorComponent={ErrorComponent}
            loadingComponent={Loading}>
          {isInAllowedGroup ?
          <>
            <Form onSubmit={handleSubmit} onCancel={handleCancel} loading={loading}/>
            {(response || error) && <Output value={responseShaped} error={error}/>}
          </>
              :<Forbidden/>
          }
        </MsalAuthenticationTemplate>
      </div>
    </main>
  </>
}

export default App;
```

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by hectormmg** [comment]
Hi @arsenzavialov . The `acquireTokenSilent` API does not support empty scopes requests. If you want to get an ID token using `acquireTokenSilent`, you need to pass in a valid scopes array as part of the request. For this use case you can pass in the account and a scopes array containing the OIDC scopes: ["openid", "profile"].

I recommend you read the documentation on [silent login](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/login-user.md), which allows you to pass in either an `account`, `login_hint`, or `sid` in the request, without scopes (MSAL adds the openid and profile scopes by default on login requests).

The reason your app is going to the network every time is that a scopes required error is being thrown inside `acquireTokenSilent`, which then sends a network request containing the default OIDC scopes (openid and profile) so you still get an ID token, just not from the cache. 

Please let us know if this solves your problem!

**Comment by arsenzavialov** [comment]
> Hi @arsenzavialov . The `acquireTokenSilent` API does not support empty scopes requests. If you want to get an ID token using `acquireTokenSilent`, you need to pass in a valid scopes array as part of the request. For this use case you can pass in the account and a scopes array containing the OIDC scopes: ["openid", "profile"].
> 
> I recommend you read the documentation on [silent login](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/login-user.md), which allows you to pass in either an `account`, `login_hint`, or `sid` in the request, without scopes (MSAL adds the openid and profile scopes by default on login requests).
> 
> The reason your app is going to the network every time is that a scopes required error is being thrown inside `acquireTokenSilent`, which then sends a network request containing the default OIDC scopes (openid and profile) so you still get an ID token, just not from the cache.
> 
> Please let us know if this solves your problem!

Thanks, i forgot about the scopes, that solved my issue!
