### ISSUE TITLE
 acquireTokenSilent not working as expected

### ISSUE THREAD

**Issue by forellendev** [AzureAD/microsoft-authentication-library-for-js#3529]
### Core Library

@azure/msal-browser

### Core Library Version

2.14.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

Not Applicable

### Description

I want to pick up the issue with acquireTokenSilent from #2579. There seems to be an incoherence with the [documentation](https://docs.microsoft.com/de-de/azure/active-directory/develop/scenario-spa-acquire-token?tabs=javascript).

For my use case with Vue, I would actually execute `acquireTokenSilent` with every backend call, because lookups in the cache are cheap operations. But as stated in issue #2579 acquireTokenSilent is not guaranteed to work, so the only other option would be `forceRefresh`at certain intervals, which isn't a good solution.

Are there any plans to put the refresh logic and its error handling into `acquireTokenSilent`? This would save a lot of code and error handling. An optimal flow would be:
1. Access backend
2. `acquireTokenSilent`
3. Valid? => continue, Invalid => update access/id token with refresh token
4. Continue with backend call

### MSAL Configuration

```javascript
/
```

### Relevant Code Snippets

```javascript
function authCallback(error, response) {
    // Handle redirect response
}

userAgentApplication.handleRedirectCallback(authCallback);

const accessTokenRequest: AuthenticationParameters = {
    scopes: ["user.read"]
}

userAgentApplication.acquireTokenSilent(accessTokenRequest).then(function(accessTokenResponse) {
    // Acquire token silent success
    // Call API with token
    let accessToken = accessTokenResponse.accessToken;
}).catch(function (error) {
    //Acquire token silent failure, and send an interactive request
    console.log(error);
    if (error.errorMessage.indexOf("interaction_required") !== -1) {
        userAgentApplication.acquireTokenRedirect(accessTokenRequest);
    }
});
```

### Reproduction Steps

/

### Expected Behavior

/

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge

### Source

Internal (Microsoft)

**Comment by hectormmg** [comment]
Hi, @forellendev . `acquireTokenSilent` does do an automatic token refresh when there is a valid refresh token in the cache. It will also throw an error when the refresh isn't possible. MSAL doesn't do error handling by design, so could you clarify what you mean by an incoherence with the documentation? Thanks!
