### ISSUE TITLE
sign in and request bearer token for bespoke api - react

### ISSUE THREAD

**Issue by lvasiliou** [AzureAD/microsoft-authentication-library-for-js#3532]
### Core Library

@azure/msal-browser

### Core Library Version

2.14

### Wrapper Library

@azure/msal-react

### Wrapper Library Version

1.0.0-beta.1

### Description

Hi I am trying to sign in the user and retrieve an access token for my custom API. However, I end up in an endless redirect loop.

### MSAL Configuration

```javascript
import { Configuration, LogLevel } from "@azure/msal-browser";
export const msalConfig: Configuration = {
    auth: {
        clientId: "xxxxxxxxx",
        authority: "https://login.microsoftonline.com/xxxxxxxx"
    },
    cache: {
        cacheLocation: "sessionStorage", // This configures where your cache will be stored
        storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
    },
    system: {
        loggerOptions: {
            loggerCallback: (level: LogLevel, message: string, containsPii: boolean) => {
                if (containsPii) {
                    return;
                }
                switch (level) {
                    case LogLevel.Error:
                        console.error(message);
                        return;
                    case LogLevel.Info:
                        console.info(message);
                        return;
                    case LogLevel.Verbose:
                        console.debug(message);
                        return;
                    case LogLevel.Warning:
                        console.warn(message);
                        return;
                }
            }
        }
    }
};
export const loginRequest = {
    scopes: ["api://xyz/acces_as_user"]
};

export const graphConfig = {
    graphMeEndpoint: "https://graph.microsoft.com/v1.0/me"
};
```

### Relevant Code Snippets

```javascript
`function App() {
  const { instance, inProgress } = useMsal();
  const isAuthneticated = useIsAuthenticated();

  instance.handleRedirectPromise().then(x => {
    if (!isAuthneticated && inProgress === InteractionStatus.None) {
      instance.loginRedirect(loginRequest).then(y => {
        if (!isAuthneticated && inProgress === InteractionStatus.None) {
          instance.acquireTokenRedirect({ scopes: ["api://.../acces_as_user"] }).then(y => {
            AjaxFetchAdapter.register().requestInterceptor = ((req: any) => {
              console.log(req);
              req.config.headers.Authorization = "Bearer " + y;
            }) as any;

            history.push('/home');
          });
        }
      })
    }
  });

  return (...`
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by tnorling** [comment]
@lvasiliou A couple things to point out here:

1. We [don't recommend](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/FAQ.md#how-do-i-handle-the-redirect-flow-in-a-react-app) calling `handleRedirectPromise` yourself when using `msal-react` as this is done under the hood by the library.
2. The `loginRedirect` and `acquireTokenRedirect` APIs are not expected to resolve as they will initiate a redirect away from the page. You should not hang a `.then` off of them.
3. We generally recommend using `acquireTokenSilent` instead of `acquireTokenRedirect` when you need to get a token for an API. `acquireTokenRedirect` should be used to resolve `interaction_required` errors if `acquireTokenSilent` fails.

I would recommend reading through our [getting started doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/getting-started.md#protecting-components) and playing around with one of our [react samples](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples) as they all demonstrate logging in a user then acquiring a token and calling an API. Let me know if you have additional questions after looking through those.

**Comment by lvasiliou** [comment]
loginRedirect not resolving causes serious race conditions. I am in a situation where my code progresses before I am signed in and before I acquired an API token, resulting in an unauthorised exception. Or maybe I am doing something wrong. So short of re-engineering the entire app to fit in MSAL, I dont see it working otherwise.

`function App() {
  const { instance, inProgress } = useMsal();
  const isAuthenticated = useIsAuthenticated();
  if (!isAuthenticated && inProgress == InteractionStatus.None) {
    instance.loginRedirect(loginRequest);
  }

  if (isAuthenticated === true && inProgress == InteractionStatus.None) {
    return (
      <AppContext.Provider value={{ EntityManagerProvider: new EntityManagerProvider(instance) }}>`

`export class EntityManagerProvider {

  protected masterManager: EntityManager;

  constructor(instance: IPublicClientApplication) {

    ModelLibraryBackingStoreAdapter.register();
    UriBuilderJsonAdapter.register();

    let activeAccount = instance.getActiveAccount();
    let accounts = instance.getAllAccounts();
    if (accounts.length > 0 || activeAccount !== null) {

      instance.acquireTokenSilent({ scopes: loginRequest.scopes, account: activeAccount || accounts[0] }).then(x => {
        AjaxFetchAdapter.register().requestInterceptor = ((req: any) => {
          req.config.headers.Authorization = "Bearer " + x.accessToken;
        }) as any;
      }).catch(e => {
        throw (e);
      });

      DataServiceWebApiAdapter.register();`

**Comment by tnorling** [comment]
> loginRedirect not resolving causes serious race conditions. 

If you need to block code from running you can await `loginRedirect`. By its very nature, the page will redirect away from your app before the promise resolves. If you would like a more straightforward API you can use `loginPopup` instead which will not leave the page.

> I am in a situation where my code progresses before I am signed in and before I acquired an API token, resulting in an unauthorised exception

Can you please clarify what code is running before you acquired a token? I would again suggest reading through our docs and looking through our samples as we provide components that will handle login for you and prevent components from being rendered before authentication is complete.

**Comment by lvasiliou** [comment]
Give us an example of a scalable app in react strict with routing instead of function components. Also, nobody wants to have a screen with a sign in button. And considering how all borwsers block popups, that feels like an outdated scenario.

**Comment by tnorling** [comment]
> Give us an example of a scalable app in react strict with routing instead of function components. 

All of our [samples](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples) use React Strict and most demonstrate routing; for example [react-router sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/react-router-sample).

If you're specifically interested in class components over function components please see:
- [Documentation about using msal-react with class components](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/class-components.md)
- [Sample page using class components with raw context](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-react-samples/react-router-sample/src/pages/ProfileRawContext.jsx)
- [Sample page using class components with HOC](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-react-samples/react-router-sample/src/pages/ProfileWithMsal.jsx)

> Also, nobody wants to have a screen with a sign in button.

Please see docs and samples about signing a user in on page load without buttons:
- [Documentation](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/getting-started.md#protecting-components)
- [Documentation specifically for class components](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/class-components.md#logging-in-on-page-load)
- [Sample page using function components](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-react-samples/react-router-sample/src/pages/Profile.jsx)
- [Sample page using class components with raw context](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-react-samples/react-router-sample/src/pages/ProfileRawContext.jsx)
- [Sample page using class components with HOC](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-react-samples/react-router-sample/src/pages/ProfileWithMsal.jsx)

Closing, please open a new issue if you have specific questions or actionable feedback after reviewing the docs. Thanks!
