### ISSUE TITLE
UnauthenticatedTemplate is rendered right after successful redirect login

### ISSUE THREAD

**Issue by ChaithanyaGK** [AzureAD/microsoft-authentication-library-for-js#3538]
### Core Library

@azure/msal-browser

### Core Library Version

2.14.0

### Wrapper Library

@azure/msal-react

### Wrapper Library Version

1.0.0-beta.1

### Description

**UnauthenticatedTemplate**  is rendered for a split second before **AuthenticatedTemplate** is being rendered immediately after redirect login.

This behavior can be reproducible with [react-router-sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/926f1c2ba0598575e23dfd8cdd8b79fa3a3d19ff/samples/msal-react-samples/react-router-sample)

Is there a way to avoid this behaviour ? 

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
@ChaithanyaGK Thanks for bringing this up. This a bug in the library, which I will make sure gets fixed in the next release. If you need a workaround in the interim you can add a check to your component that blocks rendering if `inProgress === InteractionStatus.HandleRedirect`
