### ISSUE TITLE
In which scenario I should use Authentication link from Web App Azure Portal and in which scenario I have to use MSAL Library

### ISSUE THREAD

**Issue by SujeetKulkarnii** [AzureAD/microsoft-authentication-library-for-js#3540]
### Core Library

@azure/msal or msal

### Core Library Version

2.0

### Wrapper Library

@azure/msal-angular

### Wrapper Library Version

2.0

### Description

I want to Authenticate user using Azure AD. I had application registration in Azure AD and everything is set up ,I am using Authentication link from Azure Portal Web app settings section. According to Microsoft dcoumentation MSAL library is recommended when to use MSAL library and when to use Azure Portal Authentication Azure Portal => Settings=> Authentication.

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by derisen** [comment]
@SujeetKulkarnii the **Authentication** service on **App Service** is a simpler but less flexible alternative to MSAL. If you are using MSAL, you should just disable it, as you have no need for it. See one of the deployment guides [here](https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/tree/main/4-Deployment).

**Comment by SujeetKulkarnii** [comment]
Thank you @Doğan Erişen
