### ISSUE TITLE
MSAL.js Twitter popup not redirecting after second login attempt

### ISSUE THREAD

**Issue by jml88** [AzureAD/microsoft-authentication-library-for-js#3541]
### Core Library

@azure/msal-browser

### Core Library Version

2.14.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

Using Azure MSAL library in a vanilla js application running in localhost. I step up with a problem in the login flow with Twitter.

I am using the loginPopup() approach and it seems to work fine. When I choose to sign in with Twitter it asks for my credentials and if I enter them right, the popup closes and the login works.

The problem appears when in the login popup I type the wrong credentials, this redirects me to another twitter page inside the popup windows that ask my credentials again. If I put my correct credentials in this page then I get redirected to my app inside the popup and it does not close itself.

The redirect URL that I see in the popup windows is something like this:
`https://localhost:3001/#state=asdasdasd...&client_info=asdasdasd....&code=asdasdasd...`

### MSAL Configuration

```javascript
export const msalConfig = {
    auth: {
        clientId: process.env.B2C_CLIENTID,
        authority: process.env.B2C_AUTHORITY,
        knownAuthorities: [process.env.B2C_KNOWN_AUTHORITIES],
        redirectUri: process.env.B2C_REDIRECT_URL
    },
    cache: {
        cacheLocation: "localStorage",
        storeAuthStateInCookie: false
    }
};
```

### Relevant Code Snippets

```javascript
constructor() {
        this.account = null;
        this.myMSALObj = new msal.PublicClientApplication(msalConfig);
        this.myMSALObj.handleRedirectPromise()
            .then((resp) => { this.handleResponse(resp); })
            .catch(console.error);
    }

    loginWithTwitter() {
        this.myMSALObj.loginPopup()
            .then(response => {
                utils.setSocialId(response.uniqueId);
                utils.setSocialApplication(Constants.SOCIAL_APPLICATION.TWITTER);

                const socialIdentity = {
                    email: response.idTokenClaims.emails[0],
                    name: response.idTokenClaims.name,
                    socialApplication: Constants.SOCIAL_APPLICATION.TWITTER,
                    userId: response.uniqueId
                };
                login.loginPlayerWithSocialIdentity(socialIdentity);
            })
            .catch(error => {
                console.log(`Error signing in with Twitter: ${error}`);
            });
    }
```

### Reproduction Steps

1. Logout from Twitter in the Twitter page.
2. In the app, choose to log in with Twitter.
3. In the popup page type the wrong credentials. This will redirect you to another Twitter page.
4. Login with the right credentials.
5. The app is opened in the popup windows instead of the the original.

### Expected Behavior

In the last step, the app is opened in the original window and the user data is stored in localStorage

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge

### Source

External (Customer)

**Comment by hectormmg** [comment]
Hi @jml88 . Do you see any errors from MSAL in the browser console? That would be helpful so we can diagnose your issue.

**Comment by jml88** [comment]
Hi @hectormmg ,

Thanks for the reply.

On the source page (where the login attempt is initiated) there are no messages at all in the console.
Inside the popup there is a warning from twitter.

`Error parsing a meta element's content: ';' is not a valid key-value pair separator. Please use ',' instead.`

I let you a screenshot of this.

![image](https://user-images.githubusercontent.com/4543817/116458677-4a6b1280-a83b-11eb-8223-5edca958d1fd.png)

Thanks.

**Comment by pkanher617** [comment]
@jml88 Sorry for the delayed response on this. Is the `https://localhost:3001/` redirect URI the same as the one used in the successful popup flow? I'm immediately sure why this is happening, it appears the main window is not able to parse the url after the redirect occurs in the popup.
