### ISSUE TITLE
How to authenticate a user in a asp.net core web api

### ISSUE THREAD

**Issue by anhaehne** [AzureAD/microsoft-authentication-library-for-js#3547]
### Core Library

@azure/msal-browser

### Core Library Version

2.14.0

### Wrapper Library

@azure/msal-angular

### Wrapper Library Version

2.0.0-beta.4

### Description

Hi, 
i'm currently trying implement a authentication flow for azure ad users to sign in to a angular front end which will pass the authentication to the asp.net core api.

Right now i get the error in the backend that the access token signature can't be verified. As far as i have seen the reason for that is the nonce in the JWT and that the nonce is an indication that i'm actually requesting a Graph API Token.

So how do i request an access token to authenticate the user in my application? I only need authentication and no authorization since that will be handled by our own system.

Also we need to be able to allow users from mulitple tenants to log in out applicaton.

The JWT:
`eyJ0eXAiOiJKV1QiLCJub25jZSI6ImpTX09OcHhLX0R1RmxQbFQ0b2w0QnRvV05Ga09RR2k0OENZMjFNQ1lSLUUiLCJhbGciOiJSUzI1NiIsIng1dCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyIsImtpZCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9hNjNkNDk5MS1mYWZhLTQ1ZTktOTdhMS1lYzA4NzNlOTg3MTUvIiwiaWF0IjoxNjE5NTk5NDE3LCJuYmYiOjE2MTk1OTk0MTcsImV4cCI6MTYxOTYwMzMxNywiYWNjdCI6MCwiYWNyIjoiMSIsImFjcnMiOlsidXJuOnVzZXI6cmVnaXN0ZXJzZWN1cml0eWluZm8iLCJ1cm46bWljcm9zb2Z0OnJlcTEiLCJ1cm46bWljcm9zb2Z0OnJlcTIiLCJ1cm46bWljcm9zb2Z0OnJlcTMiLCJjMSIsImMyIiwiYzMiLCJjNCIsImM1IiwiYzYiLCJjNyIsImM4IiwiYzkiLCJjMTAiLCJjMTEiLCJjMTIiLCJjMTMiLCJjMTQiLCJjMTUiLCJjMTYiLCJjMTciLCJjMTgiLCJjMTkiLCJjMjAiLCJjMjEiLCJjMjIiLCJjMjMiLCJjMjQiLCJjMjUiXSwiYWlvIjoiQVNRQTIvOFRBQUFBQkxmMVNMNDNlRVNSdEhoOTNUZXh2K0xQMS9SdUdZc05maWZtTEt4V2YrYz0iLCJhbXIiOlsicHdkIl0sImFwcF9kaXNwbGF5bmFtZSI6Imd1ZW5zdGlnZXIuZGUgQmFja29mZmljZSIsImFwcGlkIjoiNWYxOWRkYWUtOGU4Yi00OTZlLWIyZjQtYTMwNGM1Njk0YWE0IiwiYXBwaWRhY3IiOiIwIiwiZmFtaWx5X25hbWUiOiJIw6RobmVsIiwiZ2l2ZW5fbmFtZSI6IkFuZHJlIiwiaWR0eXAiOiJ1c2VyIiwiaXBhZGRyIjoiMzEuMTguODEuMzQiLCJuYW1lIjoiQW5kcmUgSMOkaG5lbCIsIm9pZCI6ImNmNzY0Y2Y2LTM0MzctNDAyMi1hMTAxLTBkNjY3NTY4MmJkZSIsInBsYXRmIjoiMyIsInB1aWQiOiIxMDAzMjAwMTA3RDgxRTVCIiwicmgiOiIwLkFSOEFrVWs5cHZyNjZVV1hvZXdJYy1tSEZhN2RHVi1Mam01SnN2U2pCTVZwU3FRZkFNRS4iLCJzY3AiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsInNpZ25pbl9zdGF0ZSI6WyJrbXNpIl0sInN1YiI6IkloYjNfVjFJOVc3U2R3Q2d2T29WUEp6TlF6UkNGTFVndmo1WXAzM0tJak0iLCJ0ZW5hbnRfcmVnaW9uX3Njb3BlIjoiRVUiLCJ0aWQiOiJhNjNkNDk5MS1mYWZhLTQ1ZTktOTdhMS1lYzA4NzNlOTg3MTUiLCJ1bmlxdWVfbmFtZSI6ImFuZHJlLmhhZWhuZWxAZ3VlbnN0aWdlci5kZSIsInVwbiI6ImFuZHJlLmhhZWhuZWxAZ3VlbnN0aWdlci5kZSIsInV0aSI6Im1xQndVT20tYjBpc3lucDh4cWRMQVEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdLCJ4bXNfc3QiOnsic3ViIjoicEJtZ1ZMN0JLbWEtTGl6dW9LOWNkbUpHdDlRRENsbl9US1I3WFhjS0QxVSJ9LCJ4bXNfdGNkdCI6MTQ5NzQ1MTMzMX0.FAea49uJd3hy53KM11w126JP6s0XnfGpoK73FlJ_dFRt243FgJxRWB33H7K5se4dOgDK3eNFJ-yUkQDKfEk6rVBkFFkQo4516kyUqcizR5wbIQEf0h2lO0fp8SKX-XizyGkZ2sX1alNEX1eFL5cxAti0e7BBSxzcQVJ2yGImmhfBZd-DZGw62L2UdwBgyoM4P4afOTYjkPO1vga22KxwwUlSaRIzOAa0voYwb6Gn45-JdwSlIwKTtc17u9rHsuuklUh4-30-E-SGDYwTccBOkM-YWDfBb8jw257_9_mzJArz4vPSWP6zlUHZHdiF4qZ1nudZW5PueQHTSgKktkePIA`

The exception in the asp.net core API: 
```
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidSignatureException: IDX10511: Signature validation failed. Keys tried: 'System.Text.StringBuilder'. 
kid: 'System.String'.
Exceptions caught:
 'System.Text.StringBuilder'.
token: 'System.IdentityModel.Tokens.Jwt.JwtSecurityToken'.
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
[10:52:08 INF] Bearer was not authenticated. Failure message: IDX10511: Signature validation failed. Keys tried: 'System.Text.StringBuilder'. 
kid: 'System.String'.
Exceptions caught:
 'System.Text.StringBuilder'.
token: 'System.IdentityModel.Tokens.Jwt.JwtSecurityToken'.
```

### MSAL Configuration

```javascript
export function MSALInstanceFactory(settingsService: SettingsService): PublicClientApplication {
    
    return new PublicClientApplication({
        auth: {
            clientId: '5f19ddae-8e8b-496e ...', 
            authority: 'https://login.microsoftonline.com/common', 
            redirectUri: '/',
            postLogoutRedirectUri: '/',
        },
        cache: {
            cacheLocation: BrowserCacheLocation.LocalStorage,
        },
        system: {
            loggerOptions: {
                loggerCallback,
                logLevel: LogLevel.Info,
                piiLoggingEnabled: false
            }
        }
    });
}

export function MSALInterceptorConfigFactory(settingsService: SettingsService): MsalInterceptorConfiguration {
    const protectedResourceMap = new Map<string, Array<string>>();
    protectedResourceMap.set(settingsService.settings.tableApiUrl, ['openid']);
    protectedResourceMap.set(settingsService.settings.identityApiUrl, ['openid']);
    protectedResourceMap.set(settingsService.settings.productApiUrl, ['openid']);

    return {
        interactionType: InteractionType.Redirect,
        protectedResourceMap,
    };
}

@NgModule({
    declarations: [AppComponent],
    imports: [
        [...]
        MsalModule
    ],
    bootstrap: [AppComponent],
    exports: [HttpClientModule],
    providers: [
        {
            provide: APP_INITIALIZER,
            useFactory: appLoadFactory,
            deps: [SettingsService],
            multi: true,
        },
        {
            provide: HTTP_INTERCEPTORS,
            useClass: MsalInterceptor,
            multi: true
        },
        {
            provide: MSAL_INTERCEPTOR_CONFIG,
            useFactory: MSALInterceptorConfigFactory,
            deps: [SettingsService]
        },
        {
            provide: MSAL_INSTANCE,
            useFactory: MSALInstanceFactory,
            deps: [SettingsService]
        },
        MsalService,
        MsalGuard,
        MsalBroadcastService
    ]
})
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by wertzui** [comment]
To give some more information on how we fixed this issue

The problem was the `'openid'` scope requested which is a shorthand for `graph.microsoft.com/openid` as described at https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/resources-and-scopes.md#working-with-multiple-resources

When we changed it to `'api://<client_id>/access'` it worked. `'access'` is just a random scope we came up with, anything can be used here.

Background:
If you request a scope for the Microsoft Graph API, the `aud` claim in the token will be `00000003-0000-0000-c000-000000000000` which is the Microsoft Graph API. However when using The Web API Authorization, it will make sure that the `aud` claim is the same as the one defined in your `appsettings.json` under `AzureAd:ClientId`. Otherwise it will not populate the User in your HttpContext.

**Comment by derisen** [comment]
@wertzui @anhaehne that's right, each access token is meant for a specific resource (represented by the [aud](https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens#payload-claims) claim), so Graph API and your own web API would be different resources here, and the valid tokens for each wouldn't contain the scopes meant for the other (you decide what to name the scopes for your own web API).
