### ISSUE TITLE
Authentication Flow for Separate Frontend/API

### ISSUE THREAD

**Issue by tcc-sejohnson** [AzureAD/microsoft-authentication-library-for-js#3556]
### Core Library

@azure/msal-node

### Core Library Version

1.0.3

### Wrapper Library

Not Applicable

### Wrapper Library Version

NA

### Description

I'm trying to figure out what flow/library I should be using to authenticate our app. 

Our frontend is a SSR React app. It lives on <site_name>.mydomain.com. Our backend lives on api.mydomain.com and is a set of C# Azure Functions. We're using role-based access control through our Azure AD tenant, so I'm pulling the roles from the user's ID Token. 

Ideally, we'd be able to share the same set of roles and app registration between the frontend and backend. There is not a situation where we'd need different roles between the two. However, the only way I can figure out to set this up is with the backend on a separate registration.

Additionally, with the SSR app, I'm unclear on whether we should be using `msal-node` or `msal-browser`. Obviously, we have the ability to work between the server and the client (unlike a true SPA), and it seems like it would make more sense to handle auth on the server, but I don't know for sure, and I can't find any good examples of a situation like this.

Any advice would be helpful, especially around whether or not it's possible to share an app registration between both the API and the app.

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by tnorling** [comment]
While `msal-browser` and `msal-react` won't break SSR, they can only actually handle authentication on the client side due to needing access to the window object. If you want to do server-side auth `msal-node` is the right choice. If you'll be doing all your API calls from the server and don't need tokens on the frontend this should be fine, however, if your front-end code will be making API calls directly then you should use `msal-browser`, and optionally, `msal-react`. Hope that helps!

**Comment by tcc-sejohnson** [comment]
@tnorling - That's literally _all_ I needed to hear to make that decision! All API calls are made server-side, so `msal-node` is the way to go. The only thing needed on the frontend is the array of roles for the user to contextually render components ("Log in" vs "Log out", etc). 

@tnorling and @derisen - That does lead to a couple of questions, though. (Please note I _might_ mis-name some functions, as I'm not super experienced with the library yet, but hopefully I can get the points across.)

How does the "magical" token cache in `msal-node` work? I'm mainly a bit mystified about how to acquire tokens silently. The call to `acquireTokenSilent` requires an instance of `AccountInfo`. It seems the only way to get that instance is to 1) Cache it myself on the backend after interactive login occurs (through `acquireTokenByCode`) or to get the cache through `PublicClientApplication.getCache().getAllAccounts()`. What scares me a little bit is that `getAllAccounts` returns an array. All of the examples I've seen just grab the first account in that array and seem to hope that it's correct. What circumstances would cause multiple accounts to be returned by this function?

Related to that, is the token cache I'm working with on the server automatically session-specific (i.e. does `msal-node` automatically add a cookie to the browser and then use that to associate the user with its cache), or does the cache I'm working with when I use `getCache` contain the accounts for all active sessions? And how long are these accounts persisted in the cache?

As far as sharing an app registration between the API and the frontend app... how would I authenticate calls from the frontend to the backend? Would I still just pass the authorization token in the Authorization header?

These are probably pretty silly questions, but I've fought my way through the documentation and have either misunderstood or not found the answers to them :)

**Comment by tnorling** [comment]
Closing as the question was answered. Please feel free to open a new issue if you have further questions. Thanks!
