### ISSUE TITLE
Prompting to select an account to sign out of after logout, although a single user is logged in.

### ISSUE THREAD

**Issue by ChaithanyaGK** [AzureAD/microsoft-authentication-library-for-js#3559]
### Core Library

@azure/msal-browser

### Core Library Version

2.14.0

### Wrapper Library

@azure/msal-react

### Wrapper Library Version

1.0.0-beta.2

### Description

After logout (using `msalInstance.logoutRedirect()`), I'm prompted to pick an account to sign out of -- although a single user is logged in. Can it be avoided or is it a mandatory step ?

![prompt](https://user-images.githubusercontent.com/28896513/116645306-291d3a00-a993-11eb-92ad-837c1627b851.png)

### Source

Internal (Microsoft)

**Comment by hectormmg** [comment]
Hi @ChaithanyaGK . We've documented the way logoutRedirect works and what it does [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md#logoutredirect. As the doc explains, it is possible to skip the account selection from the server, but doing so would mean the user is only logged out locally (i.e. MSAL clears the credentials cache), but their session with the server will remain active.

If you want to terminate their session with the authorization server, the account selection prompt is unavoidable.
