### ISSUE TITLE
MSAL Error: AADSTS9001023

### ISSUE THREAD

**Issue by v-zhangw** [AzureAD/microsoft-authentication-library-for-js#3561]
### Core Library

@azure/msal or msal

### Core Library Version

1.9.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

N/A

### Description

After moving from ADAL 1.6.6 to MSAL 1.91, an error was encountered when trying to connect to an Azure Data Explorer endpoint.

Error reads as follows:
AADSTS9001023: The grant type is not supported over the /common or /consumers endpoints. Please use the /organizations or tenant-specific endpoint.

Could I get some information on what this error means and how it could be resolved?

### Source

Internal (Microsoft)

**Comment by jasonnutter** [comment]
@v-zhangw Can you please clarify which MSAL library you are using? There is no version 1.6.6 or 1.91 of MSAL.js or ADAL.js.

**Comment by v-zhangw** [comment]
Sorry, I made this issue on the wrong repository, this was intended for MSAL4J not for JS. My apologies.
