### ISSUE TITLE
Principal Identity Name null

### ISSUE THREAD

**Issue by ursmeier-mercatus** [AzureAD/microsoft-authentication-library-for-js#3562]
### Core Library

@azure/msal or msal

### Core Library Version

2.14.1

### Wrapper Library

@azure/msal-angular

### Wrapper Library Version

2.0.0-beta.5

### Description

- Azure function app secured with AD and checking the user identity in the function
- Calling a function in browser: the Principal object is fully populated
- Calling a function in angular / msal: some attributes in the Principal object are missing, e.g. the "name"

<img width="1020" alt="principal" src="https://user-images.githubusercontent.com/22747183/116751759-ccf2fe00-aa04-11eb-9374-ed043fa67ae7.png">

Is this related to the msal library? We would expect that the Principal object is always populated the same.

### MSAL Configuration

```javascript
export function MsalInstanceFactory(): IPublicClientApplication {
	return new PublicClientApplication({
		auth: {
			clientId: '.........',
			authority: 'https://login.microsoftonline.com/......', 
			redirectUri: 'http://localhost:4200',
			postLogoutRedirectUri: 'http://localhost:4200'
		},
		cache: {
			cacheLocation: BrowserCacheLocation.LocalStorage,
			storeAuthStateInCookie: isIE
		},
		system: {
			loggerOptions: {
				loggerCallback,
				logLevel: LogLevel.Error,
				piiLoggingEnabled: true
			}
		}
	})
```

### Relevant Code Snippets

```javascript
Server side c#: 
- the principal is passed via HttpRequest.HttpContext.User
- same behaviour when ClaimsPrincipal is bound via function signature

        public static string GetPrincipalName(ClaimsPrincipal principal)
        {
            string name = principal.Identity.Name;
            return string.IsNullOrEmpty(name) ? "anonymous" : name;
        }
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by hectormmg** [comment]
Hi @ursmeier-mercatus . Could you provide some more context on how you are using msal on the client side? The Principal object you refer to is not something that MSAL JS deals with explicitly, so your issue is probably not coming from MSAL here.

**Comment by ursmeier-mercatus** [comment]
Thank you for having a look at this issue.
The principal object has nothing do to with MSal, however MSal is used for the authentication which then creates the principal object.

e.g.  the following call succeeds only if the user has successfully logged with MSal (Function App protected by Active Directory)

` updateOrganiatonTeamMember(organisationTeamMember: OrganisationTeamMemberType): Observable<OrganisationTeamMemberType> {
      return this.http.put<OrganisationTeamMemberType>(`${this.organisationTeamMemberUrl}/${organisationTeamMember.id}`, organisationTeamMember)
    }`

`${this.organisationTeamMemberUrl}/${organisationTeamMember.id}` 
will be
`https://ourapp-admin-api-v3.azurewebsites.net/api/{id}`

In this case with MSal Login the Principal Object in the Azure Function App has the Name attribute null. Other attributes and the claims are correct.

If I call the url `https://ourapp-admin-api-v3.azurewebsites.net/api/{id} `in the browser (Safari, Chrome etc.) the following steps are performed

1. User gets redirected to the Active Directory Login and logs in (**same user** as with Angular, **same app registration**)
2. The Function is called

In this case the the Azure Function App Principal Object contains all attributes, also the name

Our observation:
Log-in via MSal and Log-In via Browser (without MSal) do not create the same Principal object on the Server.  The Principal object is populated with the `HttpRequest.HttpContext.User` and this should be always identical.

**Comment by jo-arroyo** [comment]
@ursmeier-mercatus The principal object and claims are not controlled by the MSAL libraries, but is part of the app's manifest. You may need to reach out to Azure Support regarding the difference in the principal object on the server.

**Comment by ursmeier-mercatus** [comment]
Thank you.
