### ISSUE TITLE
endless loop of acquireTokenSuccess when making call to b2c protected web api from angular app.

### ISSUE THREAD

**Issue by jakehockey10** [AzureAD/microsoft-authentication-library-for-js#3566]
### Core Library

@azure/msal-browser

### Core Library Version

2.14.1

### Wrapper Library

@azure/msal-angular

### Wrapper Library Version

2.0.0-beta.5

### Description

I have a Web API registered as well as an Angular app registered in B2C.  The API has a scope defined on it, and I've added the scope to my b2c-config.ts.  When I visit an `MsalGuard` protected angular route that initiates an http call to the controller action that now has `[Authorize]` on its controller definition (ASP.NET Core 5), I'm stuck in an endless loop of events in the logger.  At the end of each round, I see an acquireTokenSuccess event.  But then it hits the `HttpInterceptor` over and over and over, freezing the browser.

### Error Message

No error message, just the browser freezing.

### Msal Logs

[Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - setActiveAccount: Active account set
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - getAllAccounts called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getRefreshTokenCredential called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getRefreshTokenCredential: cache hit
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getIdTokenCredential called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getIdTokenCredential: cache hit
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAccessTokenCredential called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAccessTokenCredential: cache hit
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - Account matching localAccountId found, returning
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-angular@2.0.0-beta.5 : Verbose - MSAL Interceptor activated
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-angular@2.0.0-beta.5 : Verbose - Interceptor - getting scopes for endpoint
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - getAllAccounts called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getRefreshTokenCredential called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getRefreshTokenCredential: cache hit
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getIdTokenCredential called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getIdTokenCredential: cache hit
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAccessTokenCredential called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAccessTokenCredential: cache hit
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - Account matching localAccountId found, returning
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-angular@2.0.0-beta.5 : Verbose - Interceptor - active account selected
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - getAllAccounts called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getRefreshTokenCredential called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getRefreshTokenCredential: cache hit
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getIdTokenCredential called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getIdTokenCredential: cache hit
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAccessTokenCredential called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAccessTokenCredential: cache hit
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - Account matching localAccountId found, returning
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-angular@2.0.0-beta.5 : Info - Interceptor - 1 scopes found for endpoint
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - preflightBrowserEnvironmentCheck started
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - acquireTokenSilent called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - Initializing BaseAuthRequest
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - Authentication Scheme wasn't explicitly set in request, defaulting to "Bearer" request
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Info - Emitting event: msal:acquireTokenStart
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - Emitting event to callback 678d68a2-dadf-4693-a033-0e6d021d57c7: msal:acquireTokenStart
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - initializeServerTelemetryManager called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - createSilentFlowClient called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - getClientConfiguration called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - getDiscoveredAuthority called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - Creating discovered authority with request authority
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.setAuthorityMetadata called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getRefreshTokenCredential called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getRefreshTokenCredential: cache hit
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getIdTokenCredential called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getIdTokenCredential: cache hit
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAccessTokenCredential called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAccessTokenCredential: cache hit
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getRefreshTokenCredential called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getRefreshTokenCredential: cache hit
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getIdTokenCredential called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getIdTokenCredential: cache hit
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAccessTokenCredential called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAccessTokenCredential: cache hit
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getRefreshTokenCredential called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getRefreshTokenCredential: cache hit
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getIdTokenCredential called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getIdTokenCredential: cache hit
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAccessTokenCredential called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAccessTokenCredential: cache hit
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getAuthorityMetadata: cache hit
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getServerTelemetry called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.getServerTelemetry: cache hit
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - BrowserCacheManager.setServerTelemetry called
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Info - Emitting event: msal:acquireTokenSuccess
auth.module.ts:30 [Mon, 03 May 2021 05:11:57 GMT] :  : @azure/msal-browser@2.14.1 : Verbose - Emitting event to callback 678d68a2-dadf-4693-a033-0e6d021d57c7: msal:acquireTokenSuccess

### MSAL Configuration

```javascript
{
    auth: {
        clientId: '<my-client-id>',
        authority: b2cPolicies.authorities.signUpSignIn.authority,
        redirectUri: '/',
        postLogoutRedirectUri: '/',
        knownAuthorities: [b2cPolicies.authorityDomain]
    },
    cache: {
        cacheLocation: BrowserCacheLocation.LocalStorage,
        storeAuthStateInCookie: isIE // set to true for IE 11
    },
    system: {
        loggerOptions: {
            loggerCallback,
            logLevel: LogLevel.Verbose,
            piiLoggingEnabled: false
        }
    }
}
```

### Relevant Code Snippets

```javascript
/**
 * Enter here the user flows and custom policies for your B2C application,
 * To learn more about user flows, visit https://docs.microsoft.com/en-us/azure/active-directory-b2c/user-flow-overview
 * To learn more about custom policies, visit https://docs.microsoft.com/en-us/azure/active-directory-b2c/custom-policy-overview
 */
export const b2cPolicies = {
    names: {
        signUpSignIn: 'B2C_1_susi',
        forgotPassword: 'B2C_1_forgotpassword'
    },
    authorities: {
        signUpSignIn: {
            authority:
                'https://<my-b2c>.b2clogin.com/<my-b2c>.onmicrosoft.com/B2C_1_susi'
        },
        forgotPassword: {
            authority:
                'https://<my-b2c>.b2clogin.com/<my-b2c>.onmicrosoft.com/B2C_1_forgotpassword'
        }
    },
    authorityDomain: '<my-b2c>.b2clogin.com'
};

/**
 * Enter here the coordinates of your Web API and scopes for access token request
 * The current application coordinates were pre-registered in a B2C tenant.
 */
export const apiConfig: { scopes: string[]; uri: string } = {
    scopes: ['https://<my-b2c>.onmicrosoft.com/api/demo'],
    uri: runtimeConfig.apiUrl
};





import { CommonModule } from '@angular/common';
import { HTTP_INTERCEPTORS } from '@angular/common/http';
import { NgModule } from '@angular/core';
import {
    MSAL_GUARD_CONFIG,
    MSAL_INSTANCE,
    MSAL_INTERCEPTOR_CONFIG,
    MsalBroadcastService,
    MsalGuard,
    MsalGuardConfiguration,
    MsalInterceptor,
    MsalInterceptorConfiguration,
    MsalService
} from '@azure/msal-angular';
import {
    BrowserCacheLocation,
    InteractionType,
    IPublicClientApplication,
    LogLevel,
    PublicClientApplication
} from '@azure/msal-browser';

import { apiConfig, b2cPolicies } from './b2c-config';

const isIE =
    window.navigator.userAgent.indexOf('MSIE ') > -1 ||
    window.navigator.userAgent.indexOf('Trident/') > -1;

export function loggerCallback(logLevel: LogLevel, message: string) {
    console.log(message);
}

export function MSALInstanceFactory(): IPublicClientApplication {
    return new PublicClientApplication({
        auth: {
            clientId: '<my-client-id>',
            authority: b2cPolicies.authorities.signUpSignIn.authority,
            redirectUri: '/',
            postLogoutRedirectUri: '/',
            knownAuthorities: [b2cPolicies.authorityDomain]
        },
        cache: {
            cacheLocation: BrowserCacheLocation.LocalStorage,
            storeAuthStateInCookie: isIE // set to true for IE 11
        },
        system: {
            loggerOptions: {
                loggerCallback,
                logLevel: LogLevel.Verbose,
                piiLoggingEnabled: false
            }
        }
    });
}

export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
    const protectedResourceMap = new Map<string, Array<string>>();
    protectedResourceMap.set(apiConfig.uri, apiConfig.scopes);

    return {
        interactionType: InteractionType.Redirect,
        protectedResourceMap
    };
}

export function MSALGuardConfigFactory(): MsalGuardConfiguration {
    return {
        interactionType: InteractionType.Redirect,
        authRequest: {
            scopes: [...apiConfig.scopes, 'openid']
        }
    };
}

@NgModule({
    imports: [CommonModule],
    providers: [
        {
            provide: HTTP_INTERCEPTORS,
            useClass: MsalInterceptor,
            multi: true
        },
        {
            provide: MSAL_INSTANCE,
            useFactory: MSALInstanceFactory
        },
        {
            provide: MSAL_GUARD_CONFIG,
            useFactory: MSALGuardConfigFactory
        },
        {
            provide: MSAL_INTERCEPTOR_CONFIG,
            useFactory: MSALInterceptorConfigFactory
        },
        MsalService,
        MsalGuard,
        MsalBroadcastService
    ]
})
export class AuthModule {}







import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { MsalGuard } from '@azure/msal-angular';

import { AccountComponent } from './account.component';
import { PasswordComponent, PersonalInformationComponent } from './pages';

const routes: Routes = [
    {
        path: 'account',
        component: AccountComponent,
        canActivate: [MsalGuard],
        children: [
            {
                path: 'personal-information',
                component: PersonalInformationComponent
            },
            { path: 'password', component: PasswordComponent },
            { path: '', redirectTo: 'personal-information', pathMatch: 'full' }
        ]
    }
];

@NgModule({
    imports: [RouterModule.forChild(routes)],
    exports: [RouterModule]
})
export class AccountRoutingModule {}
```

### Reproduction Steps

1. register web api in b2c
2. add scope to web api
3. use scope in angular config
4. make http call to controller endpoint in web api with `[Authorize]`
5. observe infinite loop of successful token acquisition

### Expected Behavior

I expect there to be no endless loop.  If I have configured something wrong, I should see an error to help mitigate the issue.  I cannot diagnose what is wrong when I can't interact with the browser.

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@jakehockey10 I'm going to try to reproduce this issue and get back to you. In the meantime, can you tell me how you're handling redirects?

**Comment by jakehockey10** [comment]
@jo-arroyo thanks for the response!  I'm using the MsalRedirectComponent as follows: 
![image](https://user-images.githubusercontent.com/1821383/117035064-22f3ca00-acc1-11eb-85b0-b8a05bf16a10.png)
![image](https://user-images.githubusercontent.com/1821383/117035172-3e5ed500-acc1-11eb-99d2-3d148523b688.png)

My angular router is configured like so (in app.module.ts):
![image](https://user-images.githubusercontent.com/1821383/117035132-34d56d00-acc1-11eb-9251-d083e15a65e0.png)

My MsalAngular configuration is using this redirect logic: 
![image](https://user-images.githubusercontent.com/1821383/117035253-546c9580-acc1-11eb-97b7-09cbd71ede9a.png)

And the protected feature module (not lazily loaded at this time), has its routes defined as: 
![image](https://user-images.githubusercontent.com/1821383/117035360-736b2780-acc1-11eb-972c-669d55ef5885.png)

Please let me know if I misunderstood your question, and I'll share with you the information I have

**Comment by svrooij** [comment]
Both the MsalInterceptor and the MsalGuard are capable of getting an access token.

Are you loading stuff in the constructor? That might cause an issue. Can you try to move the loading of data to the ngOnInit method?

**Comment by jakehockey10** [comment]
They definitely seem capable of getting the access token. I keep seeing token acquisition was successful messages. This is when navigating to a protected route after the app has been loaded and bootstrapped already

**Comment by jo-arroyo** [comment]
@jakehockey10 Thanks for the redirect information, that was indeed what I was looking for. However, I've been unable to reproduce this behavior, based on your code examples above. Are you able to reproduce this looping in one of our [sample apps](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples)?

**Comment by jakehockey10** [comment]
I'll try and let you know.  Thank you for spending the time looking into it.  I'll keep you posted.
