### ISSUE TITLE
MsalModule.forRoot example code uses outdated parameters

### ISSUE THREAD

**Issue by dzoech** [AzureAD/microsoft-authentication-library-for-js#3567]
### Wrapper Library

@azure/msal-angular

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/initialization.md#include-and-initialize-the-msal-module-in-your-app-module

### Description

Although the documentation indicates it is for V2, it doesn't use the update method signature for the `forRoot` method in the example code.

```js
MsalModule.forRoot({
  auth: {
    clientId: "Your client ID"
  }
})
```

**Comment by jo-arroyo** [comment]
@dzoech We are currently working on updating these docs. I will link the PR once it is up.
