### ISSUE TITLE
MSAL Angular v2: Logout with ID Token

### ISSUE THREAD

**Issue by eluchsinger** [AzureAD/microsoft-authentication-library-for-js#3569]
### Core Library

@azure/msal-browser

### Core Library Version

2.14.1

### Wrapper Library

@azure/msal-angular

### Wrapper Library Version

2.0.0-beta.5

### Description

In Azure AD B2C, one can enable the option to require the ID Token for logouts. This option does not seem to be supported out of the box by the MSAL Angular (v2) wrapper.

Are there any plans to support this feature before coming out of beta? I probably could include the ID token myself, if I replicate the whole MSAL Angular Interceptor logic where the `acquireTokenSilent()` call is made, but looking at the code it looks a bit cumbersome. The [EndSessionRequest](https://azuread.github.io/microsoft-authentication-library-for-js/ref/modules/_azure_msal_browser.html#endsessionrequest) looks like it already supports the `idTokenHint`.

### Relevant Code Snippets

```javascript
logout(): Observable<void> {
  return this.msal.logout({idTokenHint: "missing-token-here"});
}
```

### Identity Provider

Azure B2C Basic Policy

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@eluchsinger `logoutPopup` and `logoutRedirect` on the MSAL Angular wrapper does support passing in an `EndSessionRequest`, which can include the `idTokenHint`. Have you tried passing in the ID token there? Or is your question how to get the ID token to be passed in?

**Comment by eluchsinger** [comment]
@jo-arroyo the question is how do I get the ID token to be passed in.

**Comment by svrooij** [comment]
Isn’t it available in `this.msal.instance.getAccounts()[0]`?

**Comment by eluchsinger** [comment]
@svrooij  I guess I need the JWT, but in `this.msal.instance.getAccounts()[0]` I have got the claims.

```ts
this.msal.instance.getAllAccounts()[0].idTokenClaims["emails"]
```

**Comment by svrooij** [comment]
We are using this code to logout, and it picks up the id token in the logout request (I always assumed at least):

```js
// Select account you want to signout, first one in this case
var account = this.msal.instance.getAllAccounts()[0];
// Unset active account (we are using multiple accounts in our app, not sure if this is needed in your case).
this.msal.instance.setActiveAccount(undefined);
// Signout (with account set)
this.msal.instance.logout({ account: account, postLogoutRedirectUri: '...' });
```

**Comment by eluchsinger** [comment]
To be honest, the only thing I see the `account` parameter doing is setting the account to `null` (you set it to `undefined`).

I don't see anything to do with `idToken` in the code here: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/b4cda68b9c2708976e2b794c71344a8b9dfdd627/lib/msal-browser/src/app/ClientApplication.ts#L686

**Comment by svrooij** [comment]
Sorry I might have assumed incorrectly that it would use that information to do something to the logout request.

If you really want the ID token that was used for authentication, they are stored in the **Local Storage** under the key `<user-id>.<tenant-id>-login.windows.net-idtoken-<app-id>` which should contain an object where the `secret` property has the identity token.

But this is completely unsupported because you're directly accessing the data as stored by this library, and that might change at any moment.

**Comment by eluchsinger** [comment]
@svrooij  exactly. I guess I could also use the `acquireTokenSilent`, but I would have to replicate lots of code from the Angular Wrapper to call it.

**Comment by jo-arroyo** [comment]
@eluchsinger Thanks for your patience. `acquireTokenSilent` is our recommendation for getting tokens to use in requests. Please see an example below:
```javascript
  logout() {
    this.authService.instance.setActiveAccount(this.authService.instance.getAllAccounts()[0]); // If you have not set an active account, you may need to set one

    const request = {
      redirectStartPage: "/",
      scopes: ["openid", "profile", `${your_app_id}`] // This is added to address issue raised in #3530
    };

    this.authService.acquireTokenSilent(request as SilentRequest).subscribe({
      next: (result: AuthenticationResult) => {
        this.authService.logoutRedirect({idTokenHint: result.idToken});
      },
      error: (error) => {
        // Do something with error here
      }
    });
  }
```
The point is calling `acquireTokenSilent` and then using the result to call `logoutPopup` or `logoutRedirect` with the idToken. As the most recent version of msal-common has not been released yet, with the fix for #3530, I've included lines that mitigate a possible `access_token_entity_null` error. These lines may not be necessary once that fix is available. 

@svrooij Thanks for your input. We do not, however, recommend directly accessing the data in Local Storage, and kindly ask you to remove the suggestion so as not to confuse other people looking for a solution.

**Comment by svrooij** [comment]
@jo-arroyo removed my suggestion, but wouldn't it be nice if you can just add the `account` to the logout request and have it automatically add the Id token (if existing) to the logout request.

That was what I was expecting to happen to begin with.

**Comment by eluchsinger** [comment]
@jo-arroyo That's what I meant in my problem description.

> I probably could include the ID token myself, if I replicate the whole MSAL Angular Interceptor logic where the acquireTokenSilent() call is made, but looking at the code it looks a bit cumbersome.

The code you posted is only handling the `logoutRedirect` and not the `logoutPopup`. If I want to support both or want to switch from one to the other, the code grows a lot. Hence my question if there is anything planned regarding support for the ID Token out of the box. Actually, what @svrooij  said might be an option or it should be as easy as setting a flag like `sendIdToken: true` in the logout function of the wrapper and let the wrapper reuse the already implemented logic to get a token silently regardless of my logout type.

**Comment by jo-arroyo** [comment]
@svrooij @eluchsinger Thanks for your input and suggestions. We do not have any plans to make changes to the logout APIs currently, but we can look into exposing the idToken on the account object in the future.

**Comment by jasonnutter** [comment]
#5036 will expose the raw id token, which applications can pass to the logout APIs if desired (the library will not automatically include it as `id_token_hint` if an account is passed).
