### ISSUE TITLE
ClientAuthError: The client info AuthError.ts 26 could not be parsed/decoded correctly

### ISSUE THREAD

**Issue by DiegoMouts** [AzureAD/microsoft-authentication-library-for-js#3575]
### Core Library

@azure/msal or msal

### Core Library Version

1.4.6

### Wrapper Library

@azure/msal-react

### Wrapper Library Version

1.4.6

### Description

React project using the libraries:
"msal": "^1.4.6",
"react-aad-msal": "^2.3.5",
![Captura de tela de 2021-05-04 11-04-18](https://user-images.githubusercontent.com/68430254/117018071-8df5ce80-acca-11eb-98e1-584b1039b158.png)

presents the following error, when accessing the page, for the user who recently changed the password.

### Error Message

attached

### Msal Logs

getAccount()
Autherror.ts line 26

### MSAL Configuration

```javascript
import { MsalAuthProvider, LoginType } from 'react-aad-msal';
import configs from '../configs';

// Msal Configurations
const config = {
  auth: {
    authority: configs.ad_authority_url,
    clientId: configs.ad_client_id,
    redirectUri: configs.ad_redirect_url,
  },
  cache: {
    cacheLocation: "localStorage",
    storeAuthStateInCookie: true
  }
};

// Authentication Parameters
const authenticationParameters = {
  scopes: [
    "User.Read", 
    'openid',
    'profile',
  ],
  extraScopesToConsent: [
    "User.Read",
  ]
}

// Options
const options = {
  loginType: LoginType.Redirect,
  tokenRefreshUri: window.location.origin 
}

export const authProvider = new MsalAuthProvider(config, authenticationParameters, options)
```

### Relevant Code Snippets

```javascript
Presents the error, when accessing the page, for the user who recently changed the password.
```

### Reproduction Steps

Presents the error, when accessing the page, for the user who recently changed the password.

### Expected Behavior

Without error

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

Internal (Microsoft)

**Comment by hectormmg** [comment]
Hi @DiegoMouts .

Could you elaborate on how to reproduce the issue? Does this only happen immediately after a user changes their password? Or does it persist for future authentication?

**Comment by DiegoMouts** [comment]
The error persists, it was solved by cleaning the local storage.

**Comment by hectormmg** [comment]
And after clearing localStorage, have you seen the error again?

**Comment by DiegoMouts** [comment]
No, the error happens when you change the password.
After cleaning the localstorage, there are no errors.

**Comment by DiegoMouts** [comment]
![image](https://user-images.githubusercontent.com/68430254/122050726-24350e00-cdba-11eb-9768-d31860212b54.png)

**Comment by DiegoMouts** [comment]
![image](https://user-images.githubusercontent.com/68430254/122051016-80982d80-cdba-11eb-8a81-56d4a2654a2f.png)

**Comment by DiegoMouts** [comment]
![image](https://user-images.githubusercontent.com/68430254/122051093-93aafd80-cdba-11eb-82a2-9a21e6c5ff8a.png)

follow the error, after clearing the localstorage and changing the password

**Comment by tnorling** [comment]
@DiegoMouts This is a different error. The "User login required" error means that `acquireTokenSilent` was called without a `sid` or `login_hint` which tells MSAL which account you want to acquire a token for. To resolve you should provide the `sid` or `login_hint` or call an interactive method if you don't have those available yet. Let us know if you need more clarification or if that does not resolve the issue
