### ISSUE TITLE
Resource and state query parameters

### ISSUE THREAD

**Issue by jjalonso** [AzureAD/microsoft-authentication-library-for-js#3578]
### Core Library

@azure/msal or msal

### Core Library Version

2.14.01

### Wrapper Library

@azure/msal-react

### Wrapper Library Version

1.0.0-beta.2

### Description

Hi guys, Im trying to integrate a SPA with a currently working ADFS system that the guys have in my company, I have no previous experience in microsoft authentication and im trying to read and learn.

I got this URL in some internal documentation that appear to work and im trying to replicate the behaviour using the library for react (I will replace sensitive information):

https://my.adfs.server.com/adfs/oauth2/authorize/?
**client_id=MYCLIENTID
&scope=openid
&redirect_uri=mycallback.com/callback
&response_type=code
&state=L2FkbWluLw%3D%3D
&resource=A_NUMBER**

and with the current MSAL configuration (attached), I checked the browser request and is this:

https://my.adfs.server.com/adfs/oauth2/authorize/?
**client_id=MYCLIENTID
&scope=openid
&redirect_uri=https%3A%2F%2Flocalhost%3A3000
&response_type=code
&state=eyJpZCI6IjVmYjc1ZmExLTZiZWItNDcyNi05NjFjLTVmNmY2Y2JlOTgxZiIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicmVkaXJlY3QifX0%3D**
&client-request-id=f8397445-2772-4e97-87bc-8812dc569eed
&response_mode=fragment
&x-client-SKU=msal.js.browser
&x-client-VER=2.14.1
&x-client-OS=
&x-client-CPU=
&client_info=1
&code_challenge=wwwEa73curtsyA2_56cusCw0kBMW-X2fRJHkzkf0wz8
&code_challenge_method=S256
&nonce=0dd56898-6e69-4f65-858b-e82debf9db30

as you can see, the library one (second) add extra fields, i guess that will not be bad, im not totally sure about the state, is different but not sure if that is critical, but the resource parameter is missing in the library, At the moment im getting an error that just say "contact your administrator".

Would be great if you guys can see anything wrong or tell me how could I replicate the resource or state as the first call.
Im assuming that it could be the problem, just assuming.

Apologies for my ignorance, and thanks in advance.

### MSAL Configuration

```javascript
{
  auth: {
    clientId: 'MYCLIENTID',
    redirectUri: 'https://localhost:3000',
    authority: 'https://my.adfs.server.com/adfs'
  }
}
```

### Identity Provider

ADFS

### Source

External (Customer)

**Comment by hectormmg** [comment]
Hi, @jjalonso. The `state` value you see on the URL generated by MSAL is a GUID that MSAL generates for each request. This `state` value is also returned in the `/token` response and it should match exactly when the server returns it. You can also add your own value for `state` to the token request, but it's not necessary since MSAL can generate a unique state for you. 

Could you elaborate on what error you are getting and how you are making the request with MSAL? Your configuration seems fine and I don't see anything wrong with the Auth Code URL that you are getting from MSAL.

**Comment by jjalonso** [comment]
Hi @hectormmg thanks for your reply, I was not able to do the full flow, but i just figured out that If I pass a different domain as redirectUri (the production one) it doesnt fail, but if I pass localhost it fail, it is because need to be whitelisted on the server guys?

**Comment by hectormmg** [comment]
Yes, the redirect URI has to be registered on the B2C App registration. You can check [this tutorial](https://stackoverflow.microsoft.com/questions/256879) out for more information. Let us know if this solves your issue!

**Comment by hectormmg** [comment]
Hi @jjalonso yes. The redirect URI has to be registered on the app registration. Adding `http:localhost:3000` as a "Web" type reply/redirect URI should solve your issue. Please let us know if it does!

**Comment by jjalonso** [comment]
thanks @hectormmg 

Since adding localhost appear not to be a valid option at the moment (security) i tried to start playing using a valid redirect url despite the library (msal) is not there to collect the code, 


but after succesfullly login i see the redirect was called with: (I have modified to token for security reasons)
`
https://my.adfs.server.com/oauth2/callback#code=nnciR-rgXUWXmaaD200oog.GOZ22nMQ2QgFAAZ59uoAlZDqOho.exs8ib0npXivBa2Zz5qnei5MtL0lJ2PgobaLKpZww3AMkek6-U6Aat_QxRzE5qgWTycABcfPYKwEqKZ6_ioXnx8EgBRMq-KloBlwwR31M95A7E4KgMtbmh4Zdp858PqkdZ0r9AA5N9FEZp0w3RSRvclEYvUCWRnfavvyaRZMkjHAfbBCMqZl9qf5dHecKUvQrQX-24sir2gw&state=eyJpZCI6IjQzYzMwN4YS1hNjYzLWNiZWVlYmIzYzk3YiIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicmVkaXJlY3QifX0=


is this the final token or the auth code and the library will still work in the background to achieve the token?

thanks.

**Comment by hectormmg** [comment]
That is the auth code, MSAL will use it to obtain a token after the redirect.
