### ISSUE TITLE
acquireTokenByUsernamePassword won't work because client_secret is missing

### ISSUE THREAD

**Issue by decpio** [AzureAD/microsoft-authentication-library-for-js#3582]
### Core Library

@azure/msal-node

### Core Library Version

1.0.3

### Wrapper Library

Not Applicable

### Wrapper Library Version

n/a

### Description

new PublicClientApplication(msalConfig).acquireTokenByUsernamePassword(...) can't get acces_token succesfully because authority service required client_secret, which is not possible to pass.

I know that 'acquireTokenByUsernamePassword' is not recomended way to get access token, but for now, in my case, this is the only solution.

**I don't know if this is issue of @azure/msal_node or authority service.** I can't find out appropriate documentation about client_secret and Azure AD OAuth2 ROPC.

I've tried to modify by hand source files, so I added in
@azure\msal-common\UsernamePasswordClient.createTokenRequestBody(request) {
     var parameterBuilder = new RequestParameterBuilder();
     parameterBuilder.addClientSecret(request.clientSecret); // << this line added
...
}
and then it works.

Maybe bug is in authority service and this parameter is unnecessarily required? - I don't know.

### Error Message

{
    "error": "invalid_client",
    "error_description": "AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.\r\nTrace ID: 7d3b82f2-1456-41ba-ac90-5086654fb102\r\nCorrelation ID: 51a8fbef-b4ee-4aff-8357-4670dee3edaa\r\nTimestamp: 2021-05-05 06:50:34Z",
    "error_codes": [
        7000218
    ],
    "timestamp": "2021-05-05 06:50:34Z",
    "trace_id": "7d3b82f2-1456-41ba-ac90-5086654fb102",
    "correlation_id": "51a8fbef-b4ee-4aff-8357-4670dee3edaa",
    "error_uri": "https://login.microsoftonline.com/error?code=7000218"
}

### MSAL Configuration

```javascript
{
    auth: {
        clientId: 'my-client-id',
        authority: 'https://login.microsoftonline.com/my-tenant-name/'
    },
    graphEndpoint: 'https://graph.microsoft.com/',
}
```

### Relevant Code Snippets

```javascript
import { AuthenticationResult, ClientCredentialRequest, ConfidentialClientApplication, PublicClientApplication } from "@azure/msal-node";

const msalConfig = {
    auth: {
        clientId: 'my-client-id',
        authority: 'https://login.microsoftonline.com/my-tenant-name/'
    },
    graphEndpoint: 'https://graph.microsoft.com/',
};

const tokenRequest = {
    scopes: [msalConfig.graphEndpoint + '.default'],
};

const pca = new PublicClientApplication(msalConfig);

async function getPcaToken(tokenRequest: ClientCredentialRequest): Promise<AuthenticationResult | null> {
    return await pca.acquireTokenByUsernamePassword({
        scopes: tokenRequest.scopes,
        username: 'my-email',
        password: 'secretPWD',
    });
}

getPcaToken(tokenRequest);
```

### Reproduction Steps

All sample is in 'Relevant Code Snippets' section.

### Expected Behavior

Exprect no error result from authority service.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Source

External (Customer)

**Comment by jp185357** [comment]
I'm having this identical issue with msal-react

**Comment by hectormmg** [comment]
Hi @decpio. By any chance, do you have a Web redirect URI in your app registration? If so, the app registration will assume that yours is a Confidential Client, which is why AAD requires a client secret (which a Public Client does not have). If you could elaborate on where your application is running (web server, SPA, desktop/native app) it would help give you a better answer of how to better deal with this issue.

@jp185357 in msal-react, please make sure that your redirect URI is registered as a SPA, not a Web redirect URI.

**Comment by decpio** [comment]
Hi,

SOLUTION
to deal with that issue you have to check one option:

Microsoft_AAD_RegisteredApps -> yours app -> Authentication -> Advanced settings -> Allow public client flows -> Enable the following mobile and desktop flows: YES

After that it works.

Returned error message is strange and not helping with that situation.
