### ISSUE TITLE
Token Validation

### ISSUE THREAD

**Issue by visualjeff** [AzureAD/microsoft-authentication-library-for-js#360]
How much much validation takes place when MSAL retrieves an **id_token** for the first time?  

I noticed that msal is not making any calls to the **discovery/v2.0/keys** endpoint for signing certificate (x5c).  Is this the expected behavior?  

Thank you for your time.

Jeff

PS. The application I'm testing with is a SPA (implicit flow) and uses sample code provided by the project.  I'm also using the latest version of MSAL.

**Comment by visualjeff** [comment]
Any updates on this question?

**Comment by nehaagrawal** [comment]
@visualjeff  MSAL doesn't make any calls to discovery/v2.0/keys endpoint for signing certificate (x5c).  This is expected behavior. Can you please give more context why do you nee this?

**Comment by visualjeff** [comment]
From the openId spec:   http://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation

If the ID Token is received via direct communication between the Client and the Token Endpoint (which it is in this flow), the TLS server validation **MAY** be used to validate the issuer in place of checking the token signature. The Client **MUST** validate the signature of all other ID Tokens according to JWS [JWS] using the algorithm specified in the JWT alg Header Parameter. The Client **MUST** use the keys provided by the Issuer.

I believe MSAL is getting the token passed back **indirectly** from the token endpoint.

**Comment by visualjeff** [comment]
So is the tokenReceivedCallBack a clients opportunity to perform additional token validation?  
```
new Msal.UserAgentApplication(clientId, authority, tokenReceivedCallBack);
```
Is that the intended use for this callback?

**Comment by visualjeff** [comment]
Bummer.  I believe CORS restrictions (on the discovery/v2.0/keys endpoint) block the ability to validate an id_token for spa.
