### ISSUE TITLE
Login and token requests are not supported in non-browser environments.

### ISSUE THREAD

**Issue by anderskitson** [AzureAD/microsoft-authentication-library-for-js#3600]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

I am trying to check if a user is signed in first via a silent request, if they are not signed in I want them to be automatically redirected to the login user flow I have set up. I am able to get a login flow to work with `msalInstance.loginRedirect(loginRequest);` on a button click where I get an id token an on another button click I can run a silent request and get the access token. But my goal is to check if the user is signed in first which from what I read is where you would use the silent request first, and if that fails your would run the redirect, I think that is what my code is supposed to be doing, but I could have something wrong. 

I am using Next JS.

So the end goal is.

User lands on page -> checks if signed in -> redirects if not logged in to user flow.

What is happening at this point is that supposed to trigger a redirect to the login flow???

```
return msalInstance.acquireTokenRedirect(request)
```

The error I am getting is the following
```
errorCode: 'non_browser_environment',
errorMessage: 'Login and token requests are not supported in non-browser environments.',
```

### MSAL Configuration

```javascript
const msalConfig = {
  auth: {
    clientId: process.env.NEXT_PUBLIC_AUTH_CLIENT_ID,
    authority: process.env.NEXT_PUBLIC_AUTHORITY,
    redirectUri: "http://localhost:3000/auth-verify",
  },
  cache: {
    cacheLocation: "localStorage", // This configures where your cache will be stored
    storeAuthStateInCookie: false, // Set this to "true" to save cache in cookies 
  }
};
```

### Relevant Code Snippets

```javascript
export default function Test() {

    var request = {
        scopes: [process.env.NEXT_PUBLIC_AUTH_CLIENT_ID]
    };

    const checkLogin = async () =>{

        await msalInstance.acquireTokenSilent(request).then(tokenResponse => {
            // Do something with the tokenResponse
            console.log(tokenResponse)
        }).catch(error => {
            if (error) {
                // fallback to interaction when silent call fails
                console.log(error);
                return msalInstance.acquireTokenRedirect(request)
                // * Is this redirecting? or what is happening here exactly // *
            }
        });
    }

    checkLogin()
    

  return <h1>Sign-Up</h1>;
}
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by anderskitson** [comment]
Yes the resolves my question, thanks.

And just for anyone out there this worked for using the `msal-browser` package. I would like to use the React one, but waiting for it to come out of beta.

```
if (typeof window !== 'undefined') {
   checkLogin()
}
```

**Comment by hectormmg** [comment]
Thanks for posting the workaround! Glad it worked!
