### ISSUE TITLE
CORS Error with Azure AD Application Proxy 

### ISSUE THREAD

**Issue by sschimpf** [AzureAD/microsoft-authentication-library-for-js#3604]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

1.1.12

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

1.1.2

### Description

Hi!

I'm currently trying to set up a project with the following setup:

- Angular App packaged with Capacitor as an iPad App

- Backend behind an Azure AD Application Proxy 

Login with MSAL works, the app acquires a token and tries to connect to the Azure Proxy. The request fails immediately with a CORS error (local):
Access to XMLHttpRequest at 'https://{app-url}.msappproxy.net/…' from origin 'http://localhost:6700' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
Same thing happens on the iPad.

That's somehow expected, since localhost (frontend) and msapproxy.net are not the same origin.

Accessing the API directly (without the proxy) works without any CORS error, the backends response header is "Access-Control-Allow-Origin: *"

There's a document by microsoft how to solve CORS-Issues with Azure AD Proxy: https://docs.microsoft.com/en-us/azure/active-directory/app-proxy/application-proxy-understand-cors-issues

Correct me, if I'm wrong, but neither of these solutions work for my particular setup:
1.) Custom domain doesn't work, since on the iPad the app is running on localhost as well
2.) Same, this only applies if back and frontend are running on the same domain (separated by subdomains)
3.) I'm not familiar with Azure, but this seems like a configuration of the webserver. Our backend already implements the Access allow origin header (see above). The request never reaches the backend, so the issue seems to be with the AD Proxy.
4.) Not possible, since its a "webapp" and you can't turn off CORS for that
5.) Not the problem

Is it possible this is due to a configuration problem in Azure? We don't have access to azure, the configuration is managed by another party. Could you point me in some direction, on how to proceed with that problem?

Thanks a lot in advance,
Stephan

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by tnorling** [comment]
@sschimpf So sorry this was missed for so long. You may be able to configure this via the CORS blade on Azure App Service. You can take a look at this [tutorial](https://github.com/Azure-Samples/ms-identity-javascript-tutorial/tree/main/5-Deployment#step-3-enable-cross-origin-resource-sharing-cors) for a brief walkthrough. However, this is outside the scope of MSAL.js and [Azure Support](https://azure.microsoft.com/en-us/support/create-ticket/) may be better able to assist you if this is still an issue. Let us know if that helps!
