### ISSUE TITLE
Can't obtain signed v2 access token for PoP

### ISSUE THREAD

**Issue by derisen** [AzureAD/microsoft-authentication-library-for-js#3605]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.13.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.0-beta.1

### Description

This looks like an issue with the STS -hoping to understand and track it here. 

I'm trying to specify the version of access tokens issued by AAD. v1 access tokens have the necessary `cnf` claim, but it seems v2 tokens lack this. This is causing msal to throw an error:

```typescript
    async signPopToken(accessToken: string, request: BaseAuthRequest): Promise<string> {
        const tokenClaims: TokenClaims | null = AuthToken.extractTokenClaims(accessToken, this.cryptoUtils);

        // Deconstruct request to extract SHR parameters
        const { resourceRequestMethod, resourceRequestUri, shrClaims } = request;

        const resourceUrlString = (resourceRequestUri) ? new UrlString(resourceRequestUri) : undefined;
        const resourceUrlComponents = resourceUrlString?.getUrlComponents();

        if (!tokenClaims?.cnf?.kid) {
            throw ClientAuthError.createTokenClaimsRequiredError();
        }

        return await this.cryptoUtils.signJwt({
            at: accessToken,
            ts: TimeUtils.nowSeconds(),
            m: resourceRequestMethod?.toUpperCase(),
            u: resourceUrlComponents?.HostNameAndPort,
            nonce: this.cryptoUtils.createNewGuid(),
            p: resourceUrlComponents?.AbsolutePath,
            q: (resourceUrlComponents?.QueryString) ? [[], resourceUrlComponents.QueryString] : undefined,
            client_claims: shrClaims || undefined
        }, tokenClaims.cnf.kid);
    }
```

### Error Message

Uncaught (in promise) ClientAuthError: token_claims_cnf_required_for_signedjwt: Cannot generate a POP jwt if the token_claims are not populated
    at ClientAuthError.AuthError [as constructor] (http://localhost:3000/static/js/0.chunk.js:858:20)
    at new ClientAuthError (http://localhost:3000/static/js/0.chunk.js:1110:24)
    at Function.ClientAuthError.createTokenClaimsRequiredError (http://localhost:3000/static/js/0.chunk.js:1431:12)
    at Function.AccessTokenEntity.createAccessTokenEntity (http://localhost:3000/static/js/0.chunk.js:4715:31)
    at ResponseHandler.generateCacheRecord (http://localhost:3000/static/js/0.chunk.js:5608:45)
    at ResponseHandler.<anonymous> (http://localhost:3000/static/js/0.chunk.js:5496:32)
    at step (http://localhost:3000/static/js/0.chunk.js:444:17)
    at Object.next (http://localhost:3000/static/js/0.chunk.js:375:14)
    at http://localhost:3000/static/js/0.chunk.js:347:67
    at new Promise (<anonymous>)
    at __awaiter$1 (http://localhost:3000/static/js/0.chunk.js:326:10)
    at ResponseHandler.handleServerTokenResponse (http://localhost:3000/static/js/0.chunk.js:5474:12)
    at AuthorizationCodeClient.<anonymous> (http://localhost:3000/static/js/0.chunk.js:5813:31)
    at step (http://localhost:3000/static/js/0.chunk.js:444:17)
    at Object.next (http://localhost:3000/static/js/0.chunk.js:375:14)
    at fulfilled (http://localhost:3000/static/js/0.chunk.js:329:24)

### Msal Logs

[Fri, 07 May 2021 15:14:20 GMT] :  : @azure/msal-browser@2.14.1 : Info - Emitting event: msal:handleRedirectStart
authConfig.js:36 [Fri, 07 May 2021 15:14:20 GMT] :  : @azure/msal-react@1.0.0-beta.2 : Info - MsalProvider - msal:handleRedirectStart results in setting inProgress to handleRedirect
authConfig.js:36 [Fri, 07 May 2021 15:14:20 GMT] :  : @azure/msal-browser@2.14.1 : Info - handleRedirectPromise called but there is no interaction in progress, returning null.
authConfig.js:36 [Fri, 07 May 2021 15:14:20 GMT] :  : @azure/msal-browser@2.14.1 : Info - Emitting event: msal:handleRedirectEnd
authConfig.js:36 [Fri, 07 May 2021 15:14:20 GMT] :  : @azure/msal-react@1.0.0-beta.2 : Info - MsalProvider - no account changes
authConfig.js:36 [Fri, 07 May 2021 15:14:20 GMT] :  : @azure/msal-react@1.0.0-beta.2 : Info - MsalProvider - msal:handleRedirectEnd results in setting inProgress to none
authConfig.js:36 [Fri, 07 May 2021 15:14:25 GMT] :  : @azure/msal-browser@2.14.1 : Info - Emitting event: msal:loginStart
authConfig.js:36 [Fri, 07 May 2021 15:14:25 GMT] :  : @azure/msal-react@1.0.0-beta.2 : Info - MsalProvider - msal:loginStart results in setting inProgress to login
authConfig.js:36 [Fri, 07 May 2021 15:14:26 GMT] :  : @azure/msal-browser@2.14.1 : Info - Emitting event: msal:popupOpened
authConfig.js:36 [Fri, 07 May 2021 15:14:33 GMT] :  : @azure/msal-common@4.2.1 : Info - in acquireToken call
authConfig.js:36 [Fri, 07 May 2021 15:14:33 GMT] :  : @azure/msal-browser@2.14.1 : Info - Emitting event: msal:loginFailure
index.js:32 {"eventType":"msal:loginFailure","interactionType":"popup","payload":null,"error":{"errorCode":"token_claims_cnf_required_for_signedjwt","errorMessage":"Cannot generate a POP jwt if the token_claims are not populated","subError":"","name":"ClientAuthError"},"timestamp":1620400473583}
authConfig.js:36 [Fri, 07 May 2021 15:14:33 GMT] :  : @azure/msal-react@1.0.0-beta.2 : Info - MsalProvider - no account changes
authConfig.js:36 [Fri, 07 May 2021 15:14:33 GMT] :  : @azure/msal-react@1.0.0-beta.2 : Info - MsalProvider - msal:loginFailure results in setting inProgress to none
authConfig.js:36 [Fri, 07 May 2021 15:14:33 GMT] :  : @azure/msal-browser@2.14.1 : Info - BrowserCacheManager.cleanRequestByState: Removing temporary cache items for state: eyJpZCI6ImU2NDk0MmM1LTE0MzctNDdmYi04NzNhLTg2NjgzYTY3YWI1NiIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicG9wdXAifX0=

### MSAL Configuration

```javascript
const msalConfig = {
    auth: {
        clientId: 'dee30851-8c0d-474c-83f0-f2e982102882',        
        authority: 'https://login.microsoftonline.com/cbaf2168-de14-4c72-9d88-f5f05366dbef',
        redirectUri: "/",
        postLogoutRedirectUri: "/", 
        navigateToLoginRequestUrl: false, 
    },
    cache: {
        cacheLocation: "sessionStorage",
        storeAuthStateInCookie: false, 
    },
};
```

### Relevant Code Snippets

```javascript
import { useMsal } from "@azure/msal-react";

const { instance } = useMsal();

instance.loginPopup(loginRequest);
```

### Reproduction Steps

1. On **Azure portal** > **App Registration** > **MyApp** > **Manifest**, set `accessTokenAcceptedVersion` to **2**
2. Attempt login with `loginRequest`:

```javascript
export const loginRequest = {
    scopes: ["api://9f021487-9213-4f6d-b720-93dc2ebf6730/access_as_user"],
    authenticationScheme: AuthenticationScheme.POP,
    resourceRequestMethod: "GET",
    resourceRequestUri: "http://localhost:5000/api/todolist",
};
```

3. Login fails with error: `ClientAuthError: token_claims_cnf_required_for_signedjwt` 

### Expected Behavior

Can obtain v2 access tokens for PoP

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by hectormmg** [comment]
@derisen can you inspect the requests being made to ESTS and see if the /token request has a property called req_cnf? I think it's likely that that the token being returned isn't a POP token because the req_cnf isn't being sent. Also, could you try upgrading the msal-browser version and see if the problem persists? We 've been shipping updates/enhancements to POP since I 2.14 I believe. Thanks for tracking this issue!

**Comment by derisen** [comment]
Ok, upgraded to msal-browser 2.14.1, msal-react 1.0.0-beta.2. 
Set `accessTokenAcceptedVersion` to 2

**Request:**

```txt
POST https://login.microsoftonline.com/cbaf2168-de14-4c72-9d88-f5f05366dbef/oauth2/v2.0/token HTTP/1.1
Host: login.microsoftonline.com
Connection: keep-alive
Content-Length: 1573
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
content-type: application/x-www-form-urlencoded;charset=utf-8
Accept: */*
Origin: http://localhost:3000
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: http://localhost:3000/
Accept-Encoding: gzip, deflate, br
Accept-Language: en
```

```txt
client_id=dee30851-8c0d-474c-83f0-f2e982102882
&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2F&scope=api%3A%2F%2F9f021487-9213-4f6d-b720-93dc2ebf6730%2Faccess_as_user%20openid%20profile%20offline_access
&code=//...
&x-client-SKU=msal.js.browser
&x-client-VER=2.14.1
&x-client-OS=
&x-client-CPU=
&x-ms-lib-capability=retry-after, h429
&x-client-current-telemetry=2|862,0|@azure/msal-react,1.0.0-beta.2
&x-client-last-telemetry=2|0|||0,0&code_verifier=x8tjMzgroWJvMAkp1f90Eg--30mYGeRWEHoBFKBwVUc
&grant_type=authorization_code
&client_info=1
&token_type=pop
&req_cnf=eyJraWQiOiJuVnhfcjJFelBQaW00d2wzaERkWHVqeGY3c3QwTHllRWtxMlpGT3AxNEIwIiwieG1zX2tzbCI6InN3In0%3D
&client-request-id=f23cfd27-a8f8-446e-93b6-817f62f13c15
```

**Response:**

```txt
HTTP/1.1 200 OK
Cache-Control: no-store, no-cache
Pragma: no-cache
Content-Type: application/json; charset=utf-8
Expires: -1
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Content-Length,Content-Encoding
Access-Control-Allow-Methods: POST, OPTIONS
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
x-ms-request-id: 0ce414c4-50d7-4bff-8b8b-953dae02c300
x-ms-ests-server: 2.1.11654.25 - NCUS ProdSlices
report-to: {"group":"network-errors","max_age":86400,"endpoints":[{"url":"https://identity.nel.measure.office.net/api/report?catId=GW+estsfd+chi"}]}
x-ms-clitelem: 1,0,0,,
nel: {"report_to":"network-errors","max_age":86400,"success_fraction":0.001,"failure_fraction":1.0}
Set-Cookie: fpc=Aq3SUMaA0JxLg6BqUrE-qfCAx7QHAQAAAPaRJ9gOAAAA; expires=Sun, 06-Jun-2021 19:54:30 GMT; path=/; secure; HttpOnly; SameSite=None
Set-Cookie: x-ms-gateway-slice=estsfd; path=/; secure; samesite=none; httponly
Set-Cookie: stsservicecookie=estsfd; path=/; secure; samesite=none; httponly
Referrer-Policy: strict-origin-when-cross-origin
Date: Fri, 07 May 2021 19:54:30 GMT
Content-Length: 3929
```

```JSON
{
"token_type":"pop",
"scope":"api://9f021487-9213-4f6d-b720-93dc2ebf6730/access_as_user",
"expires_in":3599,
"ext_expires_in":3599,
"access_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyJ9.eyJhdWQiOiI5ZjAyMTQ4Ny05MjEzLTRmNmQtYjcyMC05M2RjMmViZjY3MzAiLCJpc3MiOiJodHRwczovL2xvZ2luLm1pY3Jvc29mdG9ubGluZS5jb20vY2JhZjIxNjgtZGUxNC00YzcyLTlkODgtZjVmMDUzNjZkYmVmL3YyLjAiLCJpYXQiOjE2MjA0MTY5NzAsIm5iZiI6MTYyMDQxNjk3MCwiZXhwIjoxNjIwNDIwODcwLCJhaW8iOiJBVFFBeS84VEFBQUFZM0wrcXZEb3lsQ3JnOHJTWE4zeElDZUVKQ2hqOXd5eTNOdUpHVmdNU2FRTS9qdWpONkJ6UHRYSHptOUk5MHNDIiwiYXpwIjoiZGVlMzA4NTEtOGMwZC00NzRjLTgzZjAtZjJlOTgyMTAyODgyIiwiYXpwYWNyIjoiMCIsIm5hbWUiOiJEb2dhbiBFcmlzZW4iLCJvaWQiOiJhMjgzYTYwMS02YWQ0LTQ1MjgtOTc1ZC02YWJiZWZhNWVkZDciLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbkBtc2FsdGVzdGluZ2pzLm9ubWljcm9zb2Z0LmNvbSIsInJoIjoiMC5BVVVBYUNHdnl4VGVja3lkaVBYd1UyYmI3MUVJNDk0TmpFeEhnX0R5NllJUUtJSkZBRGcuIiwic2NwIjoiYWNjZXNzX2FzX3VzZXIiLCJzdWIiOiJicnFwMHhxZS1oSHhmNkZveUFFZkNubGZRWldXOXNXWFdycVJGMF9ldEYwIiwidGlkIjoiY2JhZjIxNjgtZGUxNC00YzcyLTlkODgtZjVmMDUzNjZkYmVmIiwidXRpIjoieEJUa0ROZFFfMHVMaTVVOXJnTERBQSIsInZlciI6IjIuMCJ9.OsKdQbymPmr3yNyMegim3WEFXmYGYfVd8Y9vBpa5P2FpLrJWP4a_Ka5zQe_yIRKszHTqNtqR4HD6w6crA1sAw5--wui91ZmZwFQX7yZsdXPMnoZg2QVRZNXwSnENzhrZYhkVWqzlw-3ebNYMUJa7niJLNjLOl4OhACOHcaGch4lz0dRy12fFNBB-ShzUl0U82bsa4SDYvzNai0gk-Z0qnpd6J0v7B_Kzc7RkCrPZtKL_ZSvrhqSggVlyQnp1FpvVmSU2g7H2r5EJ5f9vszTf5glkC1t6R-HqKPOHstr9cfjcRusD6PL6YoFHpY8stAl_gMeXMtXQny2FBXlkttFRPg",
"refresh_token":"0.AUUAaCGvyxTeckydiPXwU2bb71EI494NjExHg_Dy6YIQKIJFADg.AgABAAAAAAD--DLA3VO7QrddgJg7WevrAgDs_wQA9P9y9hSkYaP7vUBLq1pa5GzeS7TmG5oyVEFgDjdZWJRNIGtbjWmCk18VfLq90bZM-a0Y5KyYxnti7BSg3btcnc9ajOdme583gd5SRQ5tjTfZmDIF-R0di8UrmQOrT4W5VP4IN4SBf_yP-d009K0cuheL1PTAkgdQJdValT3RICuvc07F3zve8rIBBXXmxn0a3QCnBA-_kvhh1Gg0tPwDK1jvFsiA38h3f-xHfJuHu_GnKqQuS2gdZAKatMQTjiLtic7dKJlCEfsLPNGzKLh0Rwvxu5pq1J1OOrIKSOFR8gSx3sva_GiFBLo-PvwKS8MgUeEYWZ1-HmANCWnjb6UP3HFhz8cwY69FqI5gTBRx144fucjlunqCfEPWxDpkzkBe1F1p0O5aSVAL-sv7DYS_1EtpI53_Lq4lx1Oq-iBINRJXXpBKfDO2GxGQulhyD7ymb-TTLcfJTRb_6fpIsSk8HMeidOALtwWSkzbO8UHY_97EPYU8Au-asl0Whqnt77xoSYYGXrCKw1cIYAYEGitGIlpVe24pSIH8yIfpc97r35sP150yI0D9-xMIebajNF9fzME_OPxhJ2cBl6WdmRTlti3HpyKPuzP1D_F4vNIXYP4Fyf97p6kFeLdMGdVeRTwnFI7v2rAKgBmgVufJMxcvfCqeSOppvt6kIR09Nn6GKyY_jIJ9V2CBlikbda-0WgmgOLsD8qFgWY6L_LqA7nwAt1DVqHMkGjNioAPBr2DYH50bLfMqk1esmE-Oug_FLe7ANis-aBUQqSFQ1CUvYLSA_q-MX96Pz4R0U8cOugBYEKj3BLDtzNv2YjzPihMKcFBCzDuGV1GROv05cfUTfxg_U8C6AJ5SRepBGua4zu59XkX_I6tOmP2xhDQS-wA14bPG-Q0OYaawiY9iYMlaZSu4JqQfpurYgyrI2xPdz7ykVsFJn_yEBJlKts_VbZSf8LQ-KdXDAFoiwTdFEgikjFRaklTgvE8EvgDPJ8VNq1tTZsI1flDB7n8MmzPvAg",
"id_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyJ9.eyJhdWQiOiJkZWUzMDg1MS04YzBkLTQ3NGMtODNmMC1mMmU5ODIxMDI4ODIiLCJpc3MiOiJodHRwczovL2xvZ2luLm1pY3Jvc29mdG9ubGluZS5jb20vY2JhZjIxNjgtZGUxNC00YzcyLTlkODgtZjVmMDUzNjZkYmVmL3YyLjAiLCJpYXQiOjE2MjA0MTY5NzAsIm5iZiI6MTYyMDQxNjk3MCwiZXhwIjoxNjIwNDIwODcwLCJuYW1lIjoiRG9nYW4gRXJpc2VuIiwibm9uY2UiOiI3NDRlMmMwNC1jMzI0LTRlNjAtODIwMy0yOGU4NWU0ZDJmZGIiLCJvaWQiOiJhMjgzYTYwMS02YWQ0LTQ1MjgtOTc1ZC02YWJiZWZhNWVkZDciLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbkBtc2FsdGVzdGluZ2pzLm9ubWljcm9zb2Z0LmNvbSIsInJoIjoiMC5BVVVBYUNHdnl4VGVja3lkaVBYd1UyYmI3MUVJNDk0TmpFeEhnX0R5NllJUUtJSkZBRGcuIiwic3ViIjoiT0cwSlkxQndYWEcxZ3ptT3hURVFVUXl3clRrZ2ZNTi15a3ZWeUlUMkwyNCIsInRpZCI6ImNiYWYyMTY4LWRlMTQtNGM3Mi05ZDg4LWY1ZjA1MzY2ZGJlZiIsInV0aSI6InhCVGtETmRRXzB1TGk1VTlyZ0xEQUEiLCJ2ZXIiOiIyLjAifQ.J6l5028eO89d3Gexzref5ohlTe7Pv2JzlFUa4s0gZbW-vCmqhsrmdsOyLn83GNKJ0VhVRgo0U7nIfYwWQur7KIBhdWm2J8grXGON4cC3mLQVed9eaS7zdmOrrvEElmtOfQ2xXJP5_hPu11byY4C_bm5CymwghaXk0_2OkW6TNbU-aLKKAvZx0HfPzEuPHaWG7bSU622IdaYWBXwp8ZWMmnkDb9bUOYPACETl49ZdNWgRc7s0rAy_qoAJrDa3GTdmS3dOXsUbjxu0057Nln5Y3Bh3dnquolLw75pV8UcFurSVCKvQMrR8CkPXsiuYMayDxxeRwcOAaPGxvDPNVl3XqQ",
"client_info":"eyJ1aWQiOiJhMjgzYTYwMS02YWQ0LTQ1MjgtOTc1ZC02YWJiZWZhNWVkZDciLCJ1dGlkIjoiY2JhZjIxNjgtZGUxNC00YzcyLTlkODgtZjVmMDUzNjZkYmVmIn0"
}
```

Looks like the access token issued just doesn't have the `cnf` claim.

**Comment by PraveenVerma17** [comment]
Any update on this , i am also facing same issue.

**Comment by waza-ari** [comment]
I'm facing the same issue right now and I'm a bit lost on what to check next.

**Comment by yozik04** [comment]
Facing the same problem with:

- @azure/msal-browser 3.26.1
- @azure/msal-react 2.1.1
