### ISSUE TITLE
getAccessTokenSilent hits openid-configuration endpoint every time instead of using cache

### ISSUE THREAD

**Issue by danishuahmad** [AzureAD/microsoft-authentication-library-for-js#3607]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

Hello,

My application calls `getAccessTokenSilent` at several places and it creates a cluster of ` .../v2.0/.well-known/openid-configuration` request which also affects the overall performance of my application. 

Is there anything I am doing wrong here ?

### MSAL Configuration

```javascript
{
    auth: {
        clientId: process.env.REACT_APP_AAD_CLIENT_ID,
        authority: `https://${process.env.REACT_APP_AAD_AUTHORITY}/${process.env.REACT_APP_AAD_TENANT_ID}/${process.env.REACT_APP_AAD_SIGN_IN_POLICY}`,
        knownAuthorities: [process.env.REACT_APP_AAD_AUTHORITY],
        postLogoutRedirectUri: process.env.REACT_APP_AAD_REDIRECT_URI,
        redirectUri: process.env.REACT_APP_AAD_REDIRECT_URI,
    },
    cache: {
        cacheLocation: BrowserCacheLocation.LocalStorage, // This configures where your cache will be stored
        storeAuthStateInCookie: true, // Set this to "true" if you are having issues on IE11 or Edge
        secureCookies: true,
    },
}
```

### Relevant Code Snippets

```javascript
getAccessTokenSilent(msalClient, accountId) {
    if (!accountId) {
        return null
    }

    let request = {
        scopes: [
            "https://<THE_URL_PART>/scope",
        ],
        authority: `https://${process.env.REACT_APP_AAD_AUTHORITY}/${process.env.REACT_APP_AAD_TENANT_ID}/${process.env.REACT_APP_AAD_SIGN_IN_POLICY}`,
        forceRefresh: false, // Set this to "true" to skip a cached token and go to the server to get a new token    
    }
    request.account = msalClient.getAccountByHomeId(accountId)
    let authResult = await msalClient.acquireTokenSilent(request)
    return authResult
}
```

### Reproduction Steps

1. You can simply copy these code snippets and use your data.

### Expected Behavior

Request `.../openid-configuration` to be only called 1 time.

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox

### Source

External (Customer)

**Comment by tnorling** [comment]
@danishuahmad The openid-configuration metadata should be saved in-memory on the `PublicClientApplication` instance. There are a couple reasons you may see multiple calls to this endpoint: 

1. You're making several concurrent requests before the metadata has been cached
2. You're re-instantiating `PublicClientApplication` between token calls
3. Each token call uses a different authority (will cause one network call per authority)

Additionally:
1. A page reload will clear in-memory cache
2. If it's been longer than 24 hours since the last refresh, a network call will be made

I was unable to reproduce this with the code you've shared above. Can you please confirm you're not doing any of the above and then share a link to a minimal reproduction? Thanks!

**Comment by mmarshad** [comment]
I'm having the issue with IE11 as well that the response in handleRedirectPromise method is null.
  ```
instance.handleRedirectPromise().then((res) => {
        console.log("Response: ", res);
      
      });
```
and my config settings are as below
```
export const msalConfig: Configuration = {
  auth: {
    clientId: "xxxx",
    authority: configParams.IDP_SERVER_URL,
    knownAuthorities: [configParams.IDP_SERVER_URL],
    protocolMode: ProtocolMode.OIDC,
    redirectUri: window.location.href   
  },
  cache: {
    cacheLocation: "localStorage", // This configures where your cache will be stored
    storeAuthStateInCookie: true, // Set this to "true" if you are having issues on IE11 or Edge
  },
};
```

**Comment by tnorling** [comment]
@mmarshad Can you please open a new issue as this is off-topic. Thanks!

**Comment by danishuahmad** [comment]
Sorry for replying so late. I think this is the issue 

> You're making several concurrent requests before the metadata has been cached

Hence this is my application-specific and isn't related to `
microsoft-authentication-library-for-js`. Sorry for the trouble and thanks for your time.
