### ISSUE TITLE
Can MSAL JS accept id-token issued from another application with a different client-id?

### ISSUE THREAD

**Issue by clivecham** [AzureAD/microsoft-authentication-library-for-js#3612]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

I am using Azure B2C.
I have an application A using MSAL JS 2.0. Application B is using implicit grant flow with Custom policy and the authentication is handle on the server side. My use case is if there is a way to SSO the user from application B to application A without going through the login flow of Azure B2C? When navigating to Application A, can Application B's id-token be passed and using that id-token to SSO the user?

### Identity Provider

Azure B2C Basic Policy

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@clivecham MSAL does not expose a function to set the idToken. IdTokens should be for a specific audience, and apps cannot share idTokens.

**Comment by derisen** [comment]
@clivecham may I ask why you need to validate the ID token or what is your goal here? As far as I know Azure B2C service does not offer a token validation endpoint. 

When you receive an ID token directly from the IdP on a secure channel (e.g. HTTPS), there’s no need to validate the signature. If you were to do it, you would validate it by asking the same server that gave you the ID token to give you the keys needed to validate it, which renders it pointless, as if one is compromised so is the other.

If you really need to validate the ID token though, you can use a package like [jose](https://github.com/panva/jose) for browser, or you can pair your SPA with a backend and use [jsonwebtoken](https://www.npmjs.com/package/jsonwebtoken) and [jwks-rsa](https://www.npmjs.com/package/jwks-rsa) packages. The process is the same with validating access tokens. See the doc: [Validating ID tokens](https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens#validating-an-id_token)

Code might look like this (for an access token):

 ```javascript
    import jwt from 'jsonwebtoken';
    import jwksClient from 'jwks-rsa';
    
   validateAccessToken = async (accessToken) => {
        const now = Math.round((new Date()).getTime() / 1000); // in UNIX format

        if (!accessToken || accessToken === "" || accessToken === "undefined") {
            return false;
        }

        // we will first decode to get kid parameter in header
        let decodedToken;

        try {
            decodedToken = jwt.decode(accessToken, { complete: true });
        } catch (error) {
            console.log(error);
            return false;
        }

        // obtains signing keys from discovery endpoint
        let keys;

        try {
            keys = await this.getSigningKeys(decodedToken.header);
        } catch (error) {
            console.log(error);
            return false;
        }

        // verify the signature at header section using keys
        let verifiedToken;

        try {
            verifiedToken = jwt.verify(accessToken, keys);
        } catch (error) {
            console.log(error);
            return false;
        }

        /**
         * At the very least, validate the token with respect to issuer, audience
         * and timestamp, though implementation and extent vary. For more information, visit:
         * https://docs.microsoft.com/azure/active-directory/develop/access-tokens#validating-tokens
         */
        const checkIssuer = verifiedToken['iss'].includes("<YOUR_TENANT_ID>") ? true : false;
        const checkTimestamp = verifiedToken["iat"] <= now && verifiedToken["exp"] >= now ? true : false;
        const checkAudience = verifiedToken['aud'] === "<YOUR_CLIENT_ID>" || verifiedToken['aud'] === 'api://' + "<YOUR_CLIENT_ID>" ? true : false;

        if (checkAudience && checkIssuer && checkTimestamp) {
            return true
        }
        return false;
    }

    getSigningKeys = async (header) => {

         const jwksUri = `https://https://login.microsoftonline.com/${<YOUR_TENANT_ID>}/discovery/v2.0/keys` 
        const client = jwksClient({
            jwksUri: jwksUri
        });

        return (await client.getSigningKeyAsync(header.kid)).getPublicKey();
    }
```

**Comment by clivecham** [comment]
@derisen I have multiple apps, each with its own domain name. When a user login to one of these apps and subsequently navigates to another app, instead of redirecting to Azure B2C server to check if user is already login and issue an id-token, I wanted to pass the id-token of the first app to the second app to avoid the redirect. To add on a layer of security, I wanted to validate the id-token received to make sure it is valid. The main objective is not having to redirect to Azure B2C authorize link and back.

I personally do not like the idea and feels like a hack but was told that this is a common use case when implemented on the backend.

I hope what I describe above make sense to you.

TIA

**Comment by derisen** [comment]
@clivecham I see. Have you considered the [single-sign on](https://docs.microsoft.com/en-us/azure/active-directory-b2c/session-behavior?pivots=b2c-user-flow) (with msal's [ssoSilent](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/login-user.md#silent-login-with-ssosilent)) and [keep me signed in](https://docs.microsoft.com/en-us/azure/active-directory-b2c/session-behavior?pivots=b2c-user-flow#enable-keep-me-signed-in-kmsi) features though? These should allow for a relatively seamless experience. Passing ID tokens around between apps on different domains is not in line with best practices (and as mentioned, msal doesn't expose a method to set ID tokens).

I should also mention, ID tokens are mostly for customizing user experience. Whenever a user needs to access a protected resource, it is the access token that counts.

Regardless, if you want to validate the ID tokens, I hope the snippet above gives an idea. Let me know if there's anything else we can help with.

**Comment by clivecham** [comment]
@derisen thanks for the reply. I will close the issue.
