### ISSUE TITLE
Authentication with msal-node working in incognito only

### ISSUE THREAD

**Issue by Upamanyu2** [AzureAD/microsoft-authentication-library-for-js#3619]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.0.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

0.0.0

### Description

I am using msal-node in server side code for authentication. My node version is 12.13.1. Using msal-node I am getting the access token to call the graph api. Everything works fine in incognito mode. But in the normal browsing mode(any browser IE, chrome, mozilla and edge), after login happens the redirect URI fails and throwing 404 error. Where I could not receive my auth code.
https://xxxdev.azurewebsites.net/redirect?code=yyy&session_state=a3986a20-6709-469b-91fe-23d565279588

### Relevant Code Snippets

```javascript
app.get('/', (req, res) => {

    const authCodeUrlParameters = {

        scopes: ["user.read"],

        redirectUri: REDIRECT_URI,

    };


    pca.getAuthCodeUrl(authCodeUrlParameters).then((response) => {

        res.clearCookie('cookieName');

        res.redirect(response);

    }).catch((error) => console.log(JSON.stringify(error)));

});


app.get('/redirect', (req, res) => {

if(req.cookie.cookieName){

  const msalTokenCache = pca.getTokenCache();

            const account = msalTokenCache.getAccountByHomeId(req.cookie.cookieName);

            const silentRequest = {

                account: account,

                scopes: ["user.read"]

            };

            pca.acquireTokenSilent(silentRequest).then((response) => {

                res.sendStatus(200);

            }).catch((error) => {

                res.status(500).send(error);

            });

}
else{
   const tokenRequest = {

        code: req.query.code,

        scopes: ["user.read"],

        redirectUri: "http://localhost:3000/redirect",

    };

    pca.acquireTokenByCode(tokenRequest).then((response) => {

        console.log("\nResponse: \n:", response);

        res.sendStatus(200);

    }).catch((error) => {

        console.log(error);

        res.status(500).send(error);

    });

}
 
});
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@Upamanyu2 Is there any chance you could provide us with a Fiddler trace? Additionally, is there a reason you are clearing cookies before redirecting?

**Comment by Upamanyu2** [comment]
I am getting an auth code in normal browsing mode, but that auth code is not going inside app.get('/redirect') api in my code. While in incognito I am getting an auth code which is going inside the app.get('/redirect') API.

**Comment by jo-arroyo** [comment]
@Upamanyu2 We will try reproducing this behavior in our samples. In the meantime, can you tell us why your code is dependent on cookie states, and not following the pattern of our samples?

**Comment by Upamanyu2** [comment]
@jo-arroyo I chose to store the user specific info into the browser cookie- to manage multiple user in a server. OAuth 2.0 remembers the signed in user once he is signed in. So I used a cookie to fetch the present user details from MSAL cache, and maintain the SSO for the user.

**Comment by Upamanyu2** [comment]
While in incognito it is allowing me to login
![image](https://user-images.githubusercontent.com/42129903/118081376-dc951e00-b3d8-11eb-8962-792951d27b12.png)
But in normal browsing mode(specially in Microsoft Edge)
![image](https://user-images.githubusercontent.com/42129903/118081301-b2436080-b3d8-11eb-9435-b4b6b98cf6d3.png)

**Comment by jo-arroyo** [comment]
@Upamanyu2 From your photos attached, it looks like the authorize call to AAD is working and it is signing in to the server, but the browser is unable to find your node server in non-incognito. We have not been able to reproduce this behavior in our samples with your code snippet. Is there a chance that there are caching issues with your app or other cache entries that may be interfering? There may also be extensions that are being disabled in incognito that would prevent your app from running in a regular browser.

**Comment by bclevering** [comment]
We have the same problem

**Comment by bclevering** [comment]
@jo-arroyo what is the status? this problem isn't resolved...

**Comment by Upamanyu2** [comment]
Sorry, did not check my personal email for a a week or two.. Yes this
problem is resolved..

**Comment by bclevering** [comment]
@Upamanyu2 how did you resolve this?? We have the same problem.

**Comment by Upamanyu2** [comment]
Just add in the domain name in the REQUEST_URI in web.config of the azure web application. It will solve the issue on every redirection.

**Comment by Upamanyu2** [comment]
Just add the domain name (for example: example.azurewebsites.net) into the
web.config of the web application. Where it filters the "REQUEST_URI", with
a rewrite rule.
This will be able to recognize the domain at every redirection.
