### ISSUE TITLE
Need a way to catch redirect errors when not using MsalAuthenticationTemplate

### ISSUE THREAD

**Issue by madmaxlax** [AzureAD/microsoft-authentication-library-for-js#3622]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.0-beta.1

### Description

Hi

I am trying to set up my React SPA to allow for unauthenticated routes (for now, just a page with a login button) as well as authenticated routes (most of the routes, once user is logged in). 
because of this, i am using 
`<UnauthenticatedTemplate>` and `<AuthenticatedTemplate>` instead of `<MsalAuthenticationTemplate>` (which would automatically popup or redirect the users to auth all the time, which I don't want)

however, I can't seem to find a way to catch the errors this way
MsalAuthenticationTemplate  has the `errorComponent` prop and that passes an `{error}` prop to whatever component you give it, so you can get the details of the error, 

however, 
there's no errorComponent option for `<UnauthenticatedTemplate>` and i don't see a way to pick up errors from the instance or other parts of the hook
note: i am using redirect auth, not popup, 
so i try to catch errors from the login redirect call (when a login button is clicked), but i dont think that will work with redirect

so when there's an error, I see flash of a hash with params in the URL, such as `http://localhost:3000/#error=access_denied&error_description=AADB...` but then it goes away

### Relevant Code Snippets

```javascript
<Button
   
          onClick={() => {
            azureAADPublicClientApplication.loginRedirect().catch((error) => {
              console.log(error);
              setLoginError(error);
            });
          }}
        >
          Login
        </Button>
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by tnorling** [comment]
@madmaxlax You can use the [event API](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/events.md) for this. You'll want to filter on the `LOGIN_FAILURE` and/or `ACQUIRE_TOKEN_FAILURE` events.

**Comment by madmaxlax** [comment]
wonderful, that worked 
thank you so much for the response! might i suggest adding something around this to the newer msal-react or msal-browser docs specifically around error handling? ie: 
>if youre using UnauthenticatedTemplate and AuthenticatedTemplate instead of MsalAuthenticationTemplate, use event API to catch errors. otherwise with MsalAuthenticationTemplate you can use the errorComponent as shown here...


code sample in case anyone comes across this and finds it helpful later: 

```
export const myComponent = () => {
const [loginError, setLoginError] = useState<Error>();

  useEffect(() => {
    // This will be run on component mount
    const callbackId = instance.addEventCallback((message: { eventType: EventType; error: Error }) => {
      // This will be run every time an event is emitted after registering this callback
      if (message.eventType === EventType.LOGIN_FAILURE || message.eventType === EventType.ACQUIRE_TOKEN_FAILURE) {
        console.error(message);
        setLoginError(message.error);
        // Do something with the result
      }
    });

    return () => {
      // This will be run on component unmount
      if (callbackId) {
        instance.removeEventCallback(callbackId);
      }
    };
  }, []);

return (<div>{loginError}</div>);
```
