### ISSUE TITLE
Can `protectedResourceMap` of MSALInterceptor be updated after application start up?

### ISSUE THREAD

**Issue by pradeepKaatnam** [AzureAD/microsoft-authentication-library-for-js#3624]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

^1.1.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

None

### Description

I have a scenario where some of the endpoints will come from a protected backend api. So from client, I should be calling the backend api which is protected by making use of MSALInterceptor and have to update protectedResourceMap with these new endpoints and scopes. Is this supported? 

### Source

Internal (Microsoft)

**Comment by jo-arroyo** [comment]
@pradeepKaatnam While we have not provided specific methods in msal-angular to directly update the `protectedResourceMap`, this shouldn't be a problem. The easiest way is to provide the configuration options via factory providers, and write your own function to update the `protectedResourceMap`. The docs on configuring via factory providers can be found [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v1-docs/configuration.md#factory-providers).
