### ISSUE TITLE
ProtectedResourceMap not matching properly for B2C auth

### ISSUE THREAD

**Issue by uberchris2** [AzureAD/microsoft-authentication-library-for-js#3633]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.0-beta.5

### Description

When I use a somewhat specific key in my protectedResourceMap (such as "https://maintenance-tracker-api.azurewebsites.net/*" or even "https://maintenance-tracker-api.azurewebsites.net/api/vehicles"), the MsalInterceptor never applies the bearer token to the request.

If, however, I change the key in protectedResourceMap to "*", it works properly. This will not work for my application because it makes some requests that must be unauthenticated.

### Error Message

The error condition is that the request is sent without the bearer token, resulting in an unexpected 302 from the API.

### MSAL Configuration

```javascript
export function MSALInstanceFactory(): IPublicClientApplication {
  return new PublicClientApplication({
    auth: {
      clientId: '4a74cf5a-08f1-43a6-be67-b30dbe68e4ff',
      authority: 'https://maintenancetracker.b2clogin.com/tfp/maintenancetracker.onmicrosoft.com/B2C_1_sign_up_sign_in/',
      redirectUri: '/',
      knownAuthorities: ['maintenancetracker.b2clogin.com']
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Info,
        piiLoggingEnabled: true
      }
    }
  });
}

export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
  const protectedResourceMap = new Map<string, Array<string>>();
  protectedResourceMap.set(`https://maintenance-tracker-api.azurewebsites.net/*`, ['https://maintenancetracker.onmicrosoft.com/4a74cf5a-08f1-43a6-be67-b30dbe68e4ff/user_impersonation']);
  return {
    interactionType: InteractionType.Redirect,
    protectedResourceMap
  };
}

export function MSALGuardConfigFactory(): MsalGuardConfiguration {
  return {
    interactionType: InteractionType.Redirect,
    authRequest: {
      scopes: ['https://maintenancetracker.onmicrosoft.com/4a74cf5a-08f1-43a6-be67-b30dbe68e4ff/user_impersonation']
    }
  };
}
```

### Relevant Code Snippets

```javascript
n/a
```

### Reproduction Steps

1. Using the above MSAL configuration, hit an endpoint such as https://maintenance-tracker-api.azurewebsites.net/api/vehicles

### Expected Behavior

The Authorization bearer token should be applies to the request

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

External (Customer)

**Comment by pim3nt3l** [comment]
What's the error are you getting at the browser console?

**Comment by uberchris2** [comment]
As mentioned, the error is an unexpected 302 from the API due to the missing Authorization header.

**Comment by pim3nt3l** [comment]
I'm using a custom httpInterceptor like this 

`constructor(
    @Inject(MSAL_INTERCEPTOR_CONFIG)
    private msalInterceptorConfig: MsalInterceptorConfiguration,
    private authService: MsalService
  ) {}

  intercept(
    req: HttpRequest<any>,
    next: HttpHandler
  ): Observable<HttpEvent<any>> {
    let account: AccountInfo;
    if (!!this.authService.instance.getActiveAccount()) {
      account = this.authService.instance.getActiveAccount() as AccountInfo;
    } else {
      account = this.authService.instance.getAllAccounts()[0];
    }

    //This is a workaround to prevent error "ClientAuthError: access_token_entity_null: Access token entity is null, please check logs and cache to ensure a valid access"
    //https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/3530
    const scopes: Array<string> | null = ['openid', 'offline_access', 'profile', '<your_client_id>'];

    const authRequest = { ...this.msalInterceptorConfig.authRequest, account };

    return this.authService
      .acquireTokenSilent({ ...authRequest, scopes, account })
      .pipe(
        catchError(() => {
          return this.acquireTokenRedirect(authRequest, scopes);
        }),
        switchMap((result: AuthenticationResult) => {
          const headers = new HttpHeaders().set(
            'Authorization',
            `Bearer ${result.idToken}`
          );
          const requestClone = req.clone({ headers });
          return next.handle(requestClone);
        })
      );`
      
      In the app.module I have this
      
      `{
      provide: MSAL_INTERCEPTOR_CONFIG,
      useFactory: yourFactory()
    },`

**Comment by jo-arroyo** [comment]
@uberchris2 Is there any chance your app is using relative paths? We have seen some customers who needed to add relative endpoints to the protectedResourceMap instead. Are you also able to provide a code snippet from when you call the API endpoint in a component?

**Comment by uberchris2** [comment]
@jo-arroyo Sure, here is an example API call; pretty basic stuff.
`  getAll(): Observable<Vehicle[]> {
    return this.http.get<Vehicle[]>('api/vehicles');
  }`
  
  Here is the complete codebase on a branch with the issue: https://github.com/uberchris2/maintenance-tracker/tree/auth-update

**Comment by jo-arroyo** [comment]
@uberchris2 I wasn't able to identify anything in your code that could be causing this issue, and was not able to reproduce it. The fact that the header is attached when you use `"*"` suggests that there may be an issue with the endpoint you are putting in your protectedResourceMap. You can try relative endpoints, or try to debug in the `MsalInterceptor` to see if the endpoint that is actually used in the call is different from what is in your protectedResourceMap.

**Comment by uberchris2** [comment]
Good suggestion, @jo-arroyo. I debugged the interceptor and found the issue. My code uses an interceptor to dynamically add the base URL to each API call. because the MsalInterceptor was running before the base interceptor, the MsalInterceptor was only matching against a partial path. Reordering the interceptors in app.module.ts fixed the problem.
