### ISSUE TITLE
AADSTS9002327: Tokens issued for the 'Single-Page Application' client-type may only be redeemed via cross-origin requests.

### ISSUE THREAD

**Issue by Turbocarte** [AzureAD/microsoft-authentication-library-for-js#3637]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.1.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

I'm using the auth-code-pkce sample for a nodejs app. I registered the app in our Azure AD tenant (with the appropriate administrator grant). 

### Error Message

{"errorCode":"invalid_request","errorMessage":"9002327 - [2021-05-13 20:33:14Z]: AADSTS9002327: Tokens issued for the 'Single-Page Application' client-type may only be redeemed via cross-origin requests.\r\nTrace ID: fb09bc37-d6e8-4948-b708-71b1b99a8b00\r\nCorrelation ID: 57e0a1a6-4380-4ef0-9e68-2a5b3f412bee\r\nTimestamp: 2021-05-13 20:33:14Z - Correlation ID: 57e0a1a6-4380-4ef0-9e68-2a5b3f412bee - Trace ID: fb09bc37-d6e8-4948-b708-71b1b99a8b00","subError":"","name":"ServerError"}

### MSAL Configuration

```javascript
const config = {
    auth: {
        clientId: "b6a0bc45-732a-(...)",
        authority: "https://login.microsoftonline.com/3143a543-edee-(...)"
    },
    system: {
        loggerOptions: {
            loggerCallback(loglevel, message, containsPii) {
                console.log(message);
            },
            piiLoggingEnabled: false,
            logLevel: msal.LogLevel.Verbose,
        }
    }
};
```

### Relevant Code Snippets

```javascript
I'm using the sample project.
```

### Reproduction Steps

1. I copied the msal-node sample from the github repository.
2. I register the app in the AD tenant (as a SPA app with the authorization flow with PKCE).
3. I add the client id and the tenant id in the config.
4. launch the nodejs app...
5. I go through the auth process (username, password)
6. bug...

### Expected Behavior

I'm expecting the authentication process to work... 

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

External (Customer)

**Comment by derisen** [comment]
@Turbocarte this is an issue with registration settings. On the **Authentication** blade, please remove the **Single-Page Application** platform, and add "Mobile and desktop applications". Can you give this a try and let me know?

I realize that app registration with msal-node PKCE is not clear. I'll get this documented.

**Comment by Turbocarte** [comment]
Hi @derisen. Thank you for the quick response. Generally, when we hear about nodejs, it's about a web server backend. In my case, it's a straigth forward console app. 
I'm gonna try your solution in the morning and give you feedback  as fast as possible. 
Again, thank you.

**Comment by Turbocarte** [comment]
Thank you @derisen. It's now working. 
As a side question, isn't the authentication flow with PKCE more secure than the Oauth 'Bearer' strategy used in the msal-browser template?
Again, thank you for the fast reply.

**Comment by derisen** [comment]
@Turbocarte can you mention which msal-browser template is that? PKCE vs. oauth bearer is a bit like apples vs oranges. PKCE is a method that allows you to securely acquire tokens for your client (for public clients where a client secret or certificate cannot be stored without exposing it to public); bearer strategy is a method for authenticating/authorizing a request (mostly by service or resource apps) by checking the bearer token in the authorization header of the request.

**Comment by Turbocarte** [comment]
I get that you can't use them interchangeably. Thank you.
