### ISSUE TITLE
 Hash value cannot be processed because it is empty.

### ISSUE THREAD

**Issue by nilact** [AzureAD/microsoft-authentication-library-for-js#3638]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

I raised [an issue](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/3574) that MSAL.js v2.0 adds "?" even if one is present in the URL. That issue is now resolved with version 2.14.2. 

Now with version 2.14.2, I tried to proceed further. However, as soon as the user is redirected back to my application (in localhost) after login, I see the below error in the console:

BrowserAuthError: hash_empty_error: Hash value cannot be processed because it is empty. Please verify that your redirectUri is not clearing the hash.

I am getting the above error when I use `loginPopup` method. 

Nothing is logged in when I use the `loginRedirect` method, however, no token is present in the local storage as well. 

I'm just extending the sample available [here](https://github.com/Azure-Samples/ms-identity-b2c-javascript-spa) for Azure B2C AD. 

**Note:** I'm able to complete all the flows (login, renew the token, logout) using [oidc-client.js](https://github.com/IdentityModel/oidc-client-js) without any issue.

### Error Message

 BrowserAuthError: hash_empty_error: Hash value cannot be processed because it is empty. Please verify that your redirectUri is not clearing the hash. Given Url: https://localhost:6420/?client_info=eyJ1aWQiOiJhZDIyMmJmZC1mMWNmLTQ4MzEtOGQ1NS0yOWYyYTM5MTdhMzYtYjJjXzFhX3plaXNzaWRub3JtYWxzaWduaW4iLCJ1dGlkIjoiN2M4OTY5ZDEtM2QxYy00NjBjLWEzMmYtODc5ZDg5NDEyNTVmIn0&code=eyJraWQiOiJUb2tlbkVuY3J5cHRpb25LZXlDb250YWluZXIiLCJ2ZXIiOiIxLjAiLCJ6aXAiOiJEZWZsYXRlIiwic2VyIjoiMS4wIn0.BF4thnn60Mo0bLprS_Md7CTcojI_yGTzrxuB-LDC4nAG8Az-kdLuBeUDbGXhG6vR46wdkZ0c-Jgrmg2rmbCVsMS_Jv6cSFPDkd9JQddvXhf7G4CfGQWPt3FFUstbUn6eq2p0RNiXbbJ2NKTBZFJ5ETA_GGkZMojd9bE0EG_GYhDfBJAraFOgmjsjonSrpp64Whzm6jAcRAGwdHqiONCA8KAIzHrJtWlXPbDG_m0PSYXwJNVzGA2NEw7bgoKrg9rlYjuyHo9ooCj7VmKe1FpxHFk9RIlKOWMETfolYzq1fVQyLpDEIsCwVmUViWwMtoVvXP64KCIB18iYrWu0Ik-87w._GVAZpu7qeOwUrSD.-hXwnCfPMQKPvQnHGEzFaKvxXMcgzZi_9i6cz8aGUXUdfcNcZx3bAew7SOQv-Hlbhl3He556XbuAjKl1fPOnVRlOBsXlLjvSYOxznmuFeIKDZlAbDTAXm9oMTRdZ6T5ik57rV6np3snFTRZGWVXHIHCLwedm1BXnU2uYe3qMf5ujx6Pdmmxum7jRoP5khdMAgmcDcMCZnouisUgUV45NNGEtwam2XajaUHvORJMuMFi2CS8brPUfP5mh-XaHoZfIGH3KFCPe0MZDpTgz2IzspRl1jX03JCEPo4OqSHMyAOxxWeH_7xRF9iy6lUT4aMUIk5-6VjgppAPbl-um-ZWeglfWcmz9gn_6br0t93YPo5uQOSUpNYgKM0_adeZIgz04EN5nwYC7eyJsx6pTeKYwJt-18yWQNFjXZ4c0weFqcngBcYhvDrY4kG4cQjJA7Cj-Z9C1gjXM3o5aUP5li_wZVtEwUTLF3MSsO2DuXhhBnkK6yNhafHnY1_ki_qxRR8G2WUb0oVRFwYwVCM9lvlvQ_ENnWnMIxy_eCr90FTZcp_ubRLmUT4ZOibJaoIy5TaWHehN6qmfF_ENexBaKjTh7x00g7atLdb2vsRGwfwEmVOdP4_foARGcBZ4aFesBSrQzajqXIbR0Hv5V-n3w8rn7GZ6iIsMqMUOFhO9N-4F3a62--go02bibqAiFEYf1ZG9m8-xbsBbhwsy68iAZL0Tkw1Ij6Vxl6yGlsiN9KyqlF3roAEynWI7cAbu-MmtRo4aAOqXOneujGKjbRmpxQmbmXo8SF9oqwlTkpR2iXqJEtTo3JGwbPE1SoRITupsmrKLX7ebzgjR-nbNaATn50Ji4ugg1LQDIXAF1DisLJzHc2bokQ0zlHFXjRn494yoY5dNhgo2zGw-BMo6963mha8mtIR4NXpwwtf8678zr9aTiU7r5F5HV41fpAgS3VLfxYNsQaVf3N8TvTaw3CRKJrfLpag79RC8qQbGNZjr9wgu5zXrTroPYVNyENUMbgEJBzKEe8B_X7j5eubbf_I6a_5GyimRFQ-n0Xy7-EF3I-RQ1sjDFQF4PaksyMM0M4sCKcs7FiJkNePLfDcKBpHlLVF5uKffT7-wVV1Zq3d3KBVYPrYSFglkVnQWtB2Ui5s-hPeDs3FL09RMmNr3kdskILpACeVaMGPO_f5ooa674dAk0jYlgzpvxXjDJNTdgJ7gGW3cfvRrZ-UgHFuc1Ic6LXoJLYX8WYhPNKNSD8k8Mb0180a7KEWXFZywxSij9n7IvFqGD__j3yjjfZ-DIaftErj_tTZrbv64JxV5qm8oN-8c7Vp3gX2v16gjZa9oJVk8_BJCadZH_e-sFxHDR_0_9nC_CCoWxlW18yhPmSIPLP60SZyPtxITj-jkFOL-8ik4O2kBVPxgXVwg6OlNFhoUdZyXX-QJQluC6kiKDglxmQxzkHJopqoktT-hT4-1aQzY2fZClVY66feFRu6mvWeLXt3qS--MxxKsHQxdcUs-PhSv-4u3IO5i16jIp0Db4UA0VZSjTzWaiHNZuVswdw5Dk51S4-7BzeylWQgZuktnmSotqjrGAbHyjBLkfwdfQPm7jHwV44qnrVcWUWEeuQvFsRGeItYI.WmlN4iNmfs6NBsk174A-OQ&state=eyJpZCI6IjUxMTkyNTU3LTA0NjMtNGY0MS04NTMxLTU1MzAyZjM4M2Q1MCIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicG9wdXAifX0%3D
    at BrowserAuthError.AuthError [as constructor] (https://alcdn.msftauth.net/browser/2.14.2/js/msal-browser.js:544:28)
    at new BrowserAuthError (https://alcdn.msftauth.net/browser/2.14.2/js/msal-browser.js:6921:32)
    at Function.BrowserAuthError.createEmptyHashError (https://alcdn.msftauth.net/browser/2.14.2/js/msal-browser.js:6958:20)
    at https://alcdn.msftauth.net/browser/2.14.2/js/msal-browser.js:9501:44

### MSAL Configuration

```javascript
const msalConfig = {
    auth: {
      clientId:"d9876389-ecc6-4105-9af8-08a52f0ba51f",
      authority: "https://test.abc.com/accounts-test.abc.com/abc_abcidnormalsignin", 
      knownAuthorities: ["test.abc.com"], 
      redirectUri: "https://localhost:6420" 
    },
    cache: {
      cacheLocation: "localStorage", 
      storeAuthStateInCookie: false, 
    },
  };
  
const loginRequest = {
  scopes: ["openid"]
};

const tokenRequest = {
  scopes: ["openid"],  
  forceRefresh: false 
};
```

### Relevant Code Snippets

```javascript
Provided.
```

### Reproduction Steps

Please refer to the sample application link provided in the description.

### Expected Behavior

This should work without any issue.

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge

### Regression

None

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@nilact Are you able to provide a fiddler/network trace?

**Comment by nilact** [comment]
@jo-arroyo 

Firstly, I'm getting the error when I use the loginPopup method. Because of the error when the popup window gets closed, developer tools also get closed for that Window and I can not get the network traffic. I don't have a fiddler installed on my machine as of now.

Secondly, I also tried the loginRedirect method and handleResponse method receives a response as null.

Can you please confirm that whether I am facing this issue because of fixed bug #3609?

**Comment by tnorling** [comment]
@nilact The issue is that your `id-ip-test.abc.com` Identity Provider is returning the response directly back to your application and in the query string, when MSAL is expecting it in the hash. Instead your custom policy should pass a b2c redirectUri to your custom IDP and let B2C redirect back to your application. See this [doc](https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-identity-provider for more on this.

localhost -> b2c authority -> id-ip-test.abc.com -> b2c authority -> localhost

**Comment by nilact** [comment]
I'll check it and get back to you. Thanks.
