### ISSUE TITLE
aquireTokenSilent with forceRefresh is not pulling new token w/ updated claims (custom attribute)

### ISSUE THREAD

**Issue by vanpyrzericj** [AzureAD/microsoft-authentication-library-for-js#3639]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

Unable to force a new access token to be retrieved with updated claims (custom attribute was added by backend server via Graph API). It is just using the cached token, despite setting force refresh in the `aquireTokenSilent` call.

### Msal Logs

[Sun, 16 May 2021 04:04:19 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getAllAccounts called 2 v1.js:1:616082
[Sun, 16 May 2021 04:04:19 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - preflightBrowserEnvironmentCheck started v1.js:1:616082
[Sun, 16 May 2021 04:04:19 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - acquireTokenSilent called v1.js:1:616082
[Sun, 16 May 2021 04:04:19 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Initializing BaseAuthRequest v1.js:1:616082
[Sun, 16 May 2021 04:04:19 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Authentication Scheme wasn't explicitly set in request, defaulting to "Bearer" request v1.js:1:616082
[Sun, 16 May 2021 04:04:19 GMT] :  : @azure/msal-browser@2.14.2 : Info - Emitting event: msal:acquireTokenStart v1.js:1:616082
[Sun, 16 May 2021 04:04:19 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - initializeServerTelemetryManager called v1.js:1:616082
[Sun, 16 May 2021 04:04:19 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - createSilentFlowClient called v1.js:1:616082
[Sun, 16 May 2021 04:04:19 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getClientConfiguration called v1.js:1:616082
[Sun, 16 May 2021 04:04:19 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getDiscoveredAuthority called v1.js:1:616082
[Sun, 16 May 2021 04:04:19 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Creating discovered authority with request authority v1.js:1:616082
[Sun, 16 May 2021 04:04:19 GMT] :  : @azure/msal-browser@2.14.2 : Info - Emitting event: msal:acquireTokenFromNetworkStart v1.js:1:616082
[Sun, 16 May 2021 04:04:19 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Initializing BaseAuthRequest v1.js:1:616082
[Sun, 16 May 2021 04:04:19 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Authentication Scheme set to "Bearer" as configured in Auth request v1.js:1:616082
[Sun, 16 May 2021 04:04:19 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - initializeServerTelemetryManager called v1.js:1:616082
[Sun, 16 May 2021 04:04:19 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - createRefreshTokenClient called v1.js:1:616082
[Sun, 16 May 2021 04:04:19 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getClientConfiguration called v1.js:1:616082
[Sun, 16 May 2021 04:04:19 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getDiscoveredAuthority called v1.js:1:616082
[Sun, 16 May 2021 04:04:19 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Creating discovered authority with request authority v1.js:1:616082
[Sun, 16 May 2021 04:04:20 GMT] :  : @azure/msal-browser@2.14.2 : Info - Emitting event: msal:acquireTokenSuccess

### MSAL Configuration

```javascript
const msalConfig = {
    auth: {
        clientId: 'client id',
        authority: 'https://myname.b2clogin.com/myname.onmicrosoft.com/B2C_1_SignUpSignIn',
        knownAuthorities: ['myname.b2clogin.com']
    }
};
```

### Relevant Code Snippets

```javascript
const request: SilentRequest = {
scopes: ['My.Scope', 'openid', 'profile'],
forceRefresh: true
};

msalInstance.acquireTokenSilent(request).then(response => {
                if (!response.accessToken || response.accessToken === "") {
                    throw new InteractionRequiredAuthError;
                } else {
                    console.log(response.accessToken);
                }
            }).catch(error => {
                if (error instanceof InteractionRequiredAuthError) {
                    // fallback to interaction when silent call fails
                    return msalInstance.acquireTokenPopup(request).then(response => {
                        console.log(response.accessToken);
                    });
                }
            });
```

### Reproduction Steps

1. Authenticate user using a standard signin/signup flow and be redirected back to application
2. User interacts with application, and then invokes a backend API call to my server, which in turn uses Graph API to add a value to a custom attribute. (Confirmed that this is added when querying the user in Graph API)
3. After API call completes, the client application then calls the above code snippet to try to refresh the token, which should return with the new claim `extension_clientid_MyCustomAttribute` in the token.

### Expected Behavior

Step #3 returns a token, but it is not a refreshed one with the new claim/attribute. Refreshing the page does not resolve this either. The only way to force this to work is by manually deleting the `sessionStorage` cache, which forces a silent _reauthentication_ at which time the access token that is returned contains the desired updated claims.

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@vanpyrzericj At this time, this is the expected behavior. The claims from the new token are the same as in the original authorization request. We're evaluating an enable fresh claims as an option for custom policies. We will update this Github issue if that becomes available.

**Comment by vanpyrzericj** [comment]
@jo-arroyo given that context, do you recommend a way to get those fresh claims? Or is manually clearing session storage the only way to accomplish this (without logging out the user and forcing them to re-authenticate).

**Comment by JasSuri** [comment]
The only way right now would be to clear the MSAL objects, and call acquireTokenRedirect(). You do not want to call logout from MSAL, as that will remove the session cookie, and then the user has to login again. We are working on getting a custom refresh token flow released in the next few months.

**Comment by vanpyrzericj** [comment]
@JasSuri what would be the best way to clear the MSAL objects? For context, I am in a VueJs application, set up via: `export const msalInstance = new PublicClientApplication(msalConfig);

**Comment by tnorling** [comment]
@vanpyrzericj You should not need to clear any storage, when MSAL gets new tokens it will update the cache. You can call `ssoSilent`,  `acquireTokenRedirect` or `acquireTokenPopup` to guarantee a call is made to the /authorize endpoint which should return the updated claims.

**Comment by vanpyrzericj** [comment]
@tnorling gotcha, so basically I shouldn't have been calling `acquireTokenSilent` as that will always pull from cache first. I'll give your guidance a try and see if it pulls the updated claims.

**Comment by vanpyrzericj** [comment]
Confirmed, @tnorling's guidance works. Closing this out. Thanks, Thomas!
