### ISSUE TITLE
Admin consent not working

### ISSUE THREAD

**Issue by tipsanemonk** [AzureAD/microsoft-authentication-library-for-js#364]
As per the [documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-scopes) on permissions and consent, there should be an option to add `adminconsent`. 

Since there was no direct way in the API, I tried providing with the `extraQueryParameters `to `loginRedirect(scopes?: Array<string>, extraQueryParameters?: string): void;`

And it doesn't really get the admin flow, which grants permission for all the users of the tenant the signing in user is an admin. 

Something seems to be missing.

**Comment by nehaagrawal** [comment]
@tipsanemonk MSAL  currently don't support admin consent.

**Comment by navyasric** [comment]
@tipsanemonk As mentioned in above comment, MSAL doesn't support a way to invoke the admin consent flow. As explained in [this document](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent#using-the-admin-consent-endpoint) your application can provide a link or interface to redirect the user to the admin consent endpoint. Here is a [sample](https://github.com/Azure-Samples/active-directory-dotnet-admin-restricted-scopes-v2) which is in .Net but can provide you an idea of this flow.

**Comment by cvburgess** [comment]
Please consider this, its a huge issue for our organization as well.

Why does MSAL not support adminconsent ?
