### ISSUE TITLE
Angular SSR: ReferenceError - window is not defined

### ISSUE THREAD

**Issue by JuanGarciaCarmona** [AzureAD/microsoft-authentication-library-for-js#3640]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.0-beta.2

### Description

We are using MsalGuard to protect certain routes, as always, and we have noticed that this routes are broken in production due to SSR. Our error points directly to MsalGuard.ActivateHelper.

Taking a look at the code we have seen that there are references to window object, concreteñy in msal.guard.ts, un line 113 
 if (UrlString.hashContainsKnownProperties(**window.location.hash**) && BrowserUtils.isInIframe()) {

I'd say that the same hint that is given the the msal angular developers that want to use with SSR should be used here... 

### MSAL Configuration

```javascript
msalConfig: {
    logLevel: LogLevel.Warning,
    piiLoggingEnabled: false,
    authorityDomain: '###{TenantName}###.b2clogin.com',
    credentials: {
      clientId: '###{SPA-ClientId}###',
      tenantId: '###{TenantId}###'
    },
    authorities: {
      signUpSignIn: {
        authority: 'https://###{TenantName}###.b2clogin.com/###{TenantName}###.onmicrosoft.com/b2c_1_susi',
      },
      forgotPassword: {
        authority: 'https://###{TenantName}###.b2clogin.com/###{TenantName}###.onmicrosoft.com/b2c_1_reset',
      },
      editProfile: {
        authority: 'https://###{TenantName}###.b2clogin.com/###{TenantName}###.onmicrosoft.com/b2c_1_edit_profile'
      }
    },
    b2cPolicies: {
      names: {
        signUpSignIn: 'b2c_1_susi',
        forgotPassword: 'b2c_1_reset',
        editProfile: 'b2c_1_edit_profile'
      }
    },
    resources: {
      logtripApi: {
        resourceUri: '###{API-BaseUrl}###',
        resourceScopes: ['openid ###{SPA-ApiScope}###']
      }
    }
  },
```

### Relevant Code Snippets

```javascript
{
    path: 'protected-path',
    component: ProtectedComponent,
    canActivate: [ MsalGuard ]
  },
```

### Reproduction Steps

1. Follow the steps to use MSAL Angular with SSR (https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/angular-universal.md)
2. build SSR
3. run
4. go to a protected URL 

### Expected Behavior

This protected URL should redirect the user to AD B2C in order to login or register

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@JuanGarciaCarmona Thanks for your patience. I haven't been able to reproduce this error, however this seems like a reasonable ask, and I have made a change to the line you described in the linked PR. Can you check if this solves your reference error?

**Comment by JuanGarciaCarmona** [comment]
I've just seen your changes and it looks like it will fix the issue. I've just told our team to check it out. I'll let you know.

Thank you!

**Comment by JuanGarciaCarmona** [comment]
Hi,

We haven't found an easy way to test this part of the code in a real scenario. Use SSR and security mechanisms (API calls over SSL) in our environments requires to pass through our build and release pipelines, even in DEV environment.

We've seen the changes and that protection against null reference using the window object seems enough. There is another usage of window in the guard, but that shouldn't be a problem in an SSR scenario.

We can wait to see it in next release (Alpha / Beta) so let us know.

BR,

Juan (and the entire Logtrip Development Team)

**Comment by jo-arroyo** [comment]
@JuanGarciaCarmona Can you or someone on your team provide a simple working sample demonstrating this issue? Or you can try to reproduce it on one of our samples. Our team feels it would be good to be able to reproduce this issue before making a change.

**Comment by JuanGarciaCarmona** [comment]
@jo-arroyo ,

Hi, the only thing that we can do is to give you a recipe, it is simple:

1. Create an Angular project. You could use your own sample project, the one referenced in the SSR documentation section should be perfect. (https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/angular-universal.md )
2. Follow those instructions to use angular universal (is just a matter of installing it and apply very basic configuration, probably your sample will work at the first try if it follows the SSR rules (don't use browser objects or be protected and ensure they exists before use them)
3. Create a route and protect it with Msalguard, you could try both, can load and can activate mechanisms.
4. Build (with the SSR command) & deploy it in a testing environment similar to a real one, with an AD B2C, Https traffic, and, what is most important, using SSR, which will require to use Node Js & express and maybe deal with your web.config regarding the paths and routes (it will depend on your environment and your pipelines).
5. Once it runs (not an easy goal) then you could try the protected route. If the usage of browser objects like window is well protected then you should be forced to login, as usual, otherwise you'll see an exception in the server output and probably nothing will hapen the browser.

I hope you have more time and resources to setup all this stuff than us. I am not even sure on how to do it to grab your changes considering that in order to be tested this have to be build which gets npm packages.

Another possibility: I am open for a call and maybe I could follow some instructions from your side to build locally with these changes and deploy manually. 

I hope you can try it and automate my suggestions for next SSR rekated tests.

BR,

**Comment by jo-arroyo** [comment]
@JuanGarciaCarmona Thank you for your patience. We were able to reproduce the error, and after some consideration, have updated the `MsalGuard` as well as our guidance around using Angular SSR with msal-angular. As the core libraries do use browser-only objects, much of msal-angular's login and token acquisition would have to occur client-side, although we have made a few changes so that using msal-angular should no longer break your app. Please take a look at the linked PR for other mitigating steps for your app, and let us know if you have further questions. We will continue to make changes to msal-angular that make it more SSR-friendly, and this current change will be available in the next msal-angular release.
