### ISSUE TITLE
@azure/msal-react v1.0.0 upgrade not working in IE11 anymore

### ISSUE THREAD

**Issue by mmarshad** [AzureAD/microsoft-authentication-library-for-js#3643]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.0

### Description

we were using version 1.0.0.beta.1 previously and the code was working fine for IE11 but since last week I have upgraded to version 1.0.0 , it stops working in IE11.  
the handleRedirectPromise method return null response.

### Error Message

There is no error message, just the token is not get created

### MSAL Configuration

```javascript
{
  auth: {
    clientId: "xxxx",
    authority: configParams.IDP_SERVER_URL,
    knownAuthorities: [configParams.IDP_SERVER_URL],
    protocolMode: ProtocolMode.OIDC,    
    redirectUri: window.location.href,
    postLogoutRedirectUri: window.location.href
  },
  cache: {
    cacheLocation: "localStorage", // This configures where your cache will be stored
    storeAuthStateInCookie: true, // Set this to "true" if you are having issues on IE11 or Edge
  },
};
```

### Relevant Code Snippets

```javascript
instance.handleRedirectPromise().then((res) => {
        console.log("Response: ", res);
});
```

### Reproduction Steps

1. IE11

### Expected Behavior

it should return the response object

### Identity Provider

Other

### Browsers Affected (Select all that apply)

Internet Explorer

### Regression

@azure/msal-browser 2.13.1, @azure/msal-react 1.0.0.beta.1

### Source

External (Customer)

**Comment by tnorling** [comment]
@mmarshad Can you please provide verbose logs and email me a network trace? I was not able to reproduce this behavior with our [sample app](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/react-router-sample) in IE 11.
