### ISSUE TITLE
Is my legacy tenant affecting MSAL 1.0 and 2.0 integrations with LiveID, Passport, MSN ID?

### ISSUE THREAD

**Issue by ExperimentsAndIdeas** [AzureAD/microsoft-authentication-library-for-js#3644]
### Core Library

Passport Azure AD (passport-azure-ad)

### Core Library Version

1

### Wrapper Library

Not Applicable

### Wrapper Library Version

1

### Description

Last year I was working as a temporary contractor for Azure B2C deployments. Please see the following GUID for problems integrating the many disconnected teams that MSAL 2.0 involves. (route this to product manager??)

lamontdcpromo764.onmicrosoft.com
3acd7c37-3881-469d-9f34-5e92a385dbab

I suspect many migrations are delayed due to the "location of where this GUID is hosted", and it being integrated with legacy Hotmail/BPOS/AAD before 2007 when "mesh" product was introduced, as well as the Sharepoint "take the kid gloves off " deployment. (The Tech manager of that solution might recognize that phrase)

### Error Message

stated previously, the messages would vary 

### MSAL Configuration

```javascript
tbd
```

### Relevant Code Snippets

```javascript
tbd
```

### Reproduction Steps

tbd

### Expected Behavior

tbd

### Identity Provider

Other

### Browsers Affected (Select all that apply)

Other

### Source

Internal (Microsoft)

**Comment by jo-arroyo** [comment]
@ExperimentsAndIdeas Can you clarify which library you are referencing, Passport AD or MSAL? Can you also clarify what issues you are seeing here?
