### ISSUE TITLE
MSAL Guard navigates to wrong path

### ISSUE THREAD

**Issue by andhe27** [AzureAD/microsoft-authentication-library-for-js#3647]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.0.

### Description

I opened https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/3440#issue-857036849 a few weeks ago.
According your repository this should be fixed. Unfortunately I still see the same behavior like before. Am I missing something out? I don't have a page that doesn't use MSAL Guard (see code snipped of app.routing).

MsalGuard secures all my routes. If I want to open a specific route directly e.g.: http://localhost:4200/#/test/10, then I get logged in successfully, but I get redirected to http://localhost:4200/#/home. I can see that it redirects shortly to my desired page but then gets overwritten somehow. Deleting { path: '**', redirectTo: 'home' } from my routes solves this issue but I want to keep that path for misspelled routes.

### MSAL Configuration

```javascript
export function MSALInstanceFactory(): IPublicClientApplication{
  return new PublicClientApplication({
    auth: {
      clientId: 'xxxxx',
      authority: 'https://login.microsoftonline.com/xxxx',
      navigateToLoginRequestUrl: true 
    }
  });
}

export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
  const protectedResourceMap = new Map<string, Array<string>>();
  protectedResourceMap.set('http://localhost:51140/*', ['api://xxxx']);
  protectedResourceMap.set('https://graph.microsoft.com', ['user.readbasic.all']);

  return {
    interactionType: InteractionType.Redirect,
    protectedResourceMap
  }
}

export function MSALGuardConfigFactory(): MsalGuardConfiguration {
  return { 
    interactionType: InteractionType.Redirect,
    authRequest: {
      scopes: ['user.readbasic.all', 'api://xxxx']
    }
  };
}
```

### Relevant Code Snippets

```javascript
const routes: Routes = [
  {path: '', canActivate: [MsalGuard], children: [
    { path: '', redirectTo: 'home', pathMatch: 'full' },
    { path: 'home', component: HomeComponent},
    { path: 'test/:id', component: ProjectDetailsComponent},
    { path: '**', redirectTo: 'home' },
  ]}
  
];

const isIframe = window !== window.parent && !window.opener;

@NgModule({
  imports: [RouterModule.forRoot(routes, { useHash: true, relativeLinkResolution: 'legacy', initialNavigation: !isIframe ? 'enabled' : 'disabled' })],
  exports: [RouterModule]
})
```

### Reproduction Steps

Opening an URL directly thats not the home component. For example http://localhost:4200/#/test/10.

### Expected Behavior

After loginRedirect it should route me to the desired URL and not the HomeComponent.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

External (Customer)

**Comment by celluj34** [comment]
I am having the same or similar issue. Routing worked to redirect to the default in 2-beta.5, but 2.beta-6 and 2.0 do not navigate to our catch-all route. Reload works just fine, as does logging in and navigating manually (or using the navbar).

**Comment by roopeshreddy** [comment]
@jasonnutter This was the issue with 2.14.2 which I mentioned.

@celluj34 @andhe27 Please use 2.14.1 and it should work fine.

All, I've opened an issue, where if the deep link URL is case-sensitive, then after redirect, it's coming a lower-case. Refer (#3621 )

**Comment by celluj34** [comment]
@roopeshreddy That does fix my issue for now - thank you!

**Comment by jasonnutter** [comment]
@andhe27 Can you please try adding placeholder routes for things like `code`? This is usually needed when doing hash routing with redirects: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/9eab0f4be2be20dd828a033941fbd9a30fb92f1e/samples/msal-angular-v2-samples/angular11-sample-app/src/app/app-routing.module.ts#L32

Note, due to the way redirects are processed, you may need to remove the catch all logic if the above adjustments don't work. 

cc: @jo-arroyo

**Comment by celluj34** [comment]
@jasonnutter We're not using hash routing, but I will see if it helps.

**Comment by jasonnutter** [comment]
> @jasonnutter We're not using hash routing, but I will see if it helps.

The placeholder routes are only needed for hash routing.

**Comment by andhe27** [comment]
ok thanks for your answer. 
I got rid of hashRouting and everything works as expected. 

With hashRouting I don't know where the placeholder Routes should navigate to, since every other Route is also protected (see app-routing configuration).

**Comment by jasonnutter** [comment]
> ok thanks for your answer.
> I got rid of hashRouting and everything works as expected.
> 
> With hashRouting I don't know where the placeholder Routes should navigate to, since every other Route is also protected (see app-routing configuration).

In our samples, we have the placeholder routes render the `HomeComponent` (i.e. the home page of your app).

**Comment by eluchsinger** [comment]
I am having the same issue. For me it redirect to the root path, causing a loop...
