### ISSUE TITLE
Is it possible to see if a user has KMSI enabled

### ISSUE THREAD

**Issue by code-by-gijs** [AzureAD/microsoft-authentication-library-for-js#3648]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.11.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

none

### Description

Hi!

I was wondering if the msal-browser package can give any information about the user having kmsi enabled. For example, I would like to redirect straight to the adb2c login page when a user has kmsi enabled and their access token has expired. If not, I would like to take a different approach in my application. I could not find anything in the authResponse, but I really hope it is possible. Thanks!

### Identity Provider

Azure B2C Basic Policy

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@code-by-gijs We recommend using `acquireTokenSilent` to renew expired access tokens. KMSI is more for the server-side session to extend the session lifetime, and MSAL doesn't get a signal from the server that KMSI is enabled.

**Comment by jo-arroyo** [comment]
@code-by-gijs Yes, unfortunately extending the token expiration by KMSI cannot be supported by MSAL because the setting is server-rendered and the client doesn't have a context. Closing as there's nothing further MSAL can do.
