### ISSUE TITLE
offline_access is incorrectly always added to scopes

### ISSUE THREAD

**Issue by wparad** [AzureAD/microsoft-authentication-library-for-js#3649]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

2.0.0

### Description

The `offline_access` scope is always being added even when it isn't necessary, and it cannot be removed.

### MSAL Configuration

```javascript
{}
```

### Relevant Code Snippets

```javascript
const loginRequest = {
      scopes: ['profile', 'email', 'openid']
};
const result = await myMSALObj.acquireTokenPopup(loginRequest);
```

### Reproduction Steps

Run the code
lookup at the requested scopes

### Expected Behavior

When scopes is specificied they are used and NOT added to.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@wparad Are you seeing any issues or errors occurring in your app with the `offline_access` scope being present?

**Comment by wparad** [comment]
Of course, users don't want to approve access to offline when there is no reason. Our users are telling us, they don't want to approve apps, if we ask for email or offline access. We don't need those scopes, so we should be able to remove them, but the library prevents that.

Additionally it is just good security practice: `principle of least privilege`. This is common best security practice, which basically says: do not request more data or access than you absolutely need. And with OAuth, if we choose later to actually need that access we can ask the user for additional scopes.

**Comment by pkanher617** [comment]
@wparad The `offline_access` scope is required for refresh tokens to be issued to the application. It is considered as part of OIDC scopes for AAD/MSA auth, which is why it is added by default to all requests, similar to `openid` and `profile`.

**Comment by wparad** [comment]
Yes it is a scope, no it is a `default` scope. That parts wrong. There are lots of scopes, and it is for the app developer to decide what scopes they want, not this library. The API works without the scopes, the library needs to be fixed.

Additionally, correct, the `offline_access` scope is required for refresh tokens. We don't need refresh token, ergo we don't need this scope.

**Comment by pkanher617** [comment]
I'm not saying it is a default scope, I am saying it is added by default by the MSAL library because refresh tokens are used in the basic SPA flow. While we understand the app developer should have control over the scopes they want to use, we add specific scopes by default, namely OIDC scopes (`openid`, `profile`, `offline_access`). The API does work without the offline_access scope, but there are nuances to this that we have had to account for in the past (for example, the offline_access scope being sent back in the response regardless of whether it was sent in the request). We will discuss whether we can add a scenario for access-token only flows for SPAs. I can update here when we decide how to progress. 

Be aware the access_tokens in the SPA flow are restricted to 1 hour lifetimes, and will require a redirect or popup to renew once expired if no refresh tokens are used for your application. This can result in a degradation of performance and in user experience.

**Comment by wparad** [comment]
Why the hell does the auth server require `offline_access` to keep the user logged in to an SPA. Please go back and validate this, if so that's a huge concern, we expect that silent-auth would use a azure domain HttpOnly/SameSite=Strict cookie or PostMessage to a secure iframe to continue the session and generate a new access token, and **not use a "refresh token" to generate a new access token**.

**Comment by pkanher617** [comment]
@wparad We will probably add some APIs to skip default scopes, please be on the lookout for PRs.

**Comment by wparad** [comment]
.

**Comment by javafrog** [comment]
We are also experiencing this issue. With the "new" default oauth code flow, there is no more need for refresh tokens, so it should not be any default and most certainly not mandatory for my app. The less such sensitive data is transferred across the Web, the better.

**Comment by mexmirror** [comment]
Is this is issue planned or on a roadmap? Having a 30 day refresh token in browser storage is insecure and would force us to use another library if this is not fixed soon.

**Comment by tnorling** [comment]
> Is this is issue planned or on a roadmap? Having a 30 day refresh token in browser storage is insecure and would force us to use another library if this is not fixed soon.

Refresh tokens for SPAs have a 24 hour lifetime. We currently do not have plans to remove the defaults, however, we will look into providing a way to turn off the defaults for those that don't want them, though this work has not yet been scheduled. Please do be aware that not using the refresh token may result in more frequent interactive sign-ins, especially in browsers that block 3rd party cookies.

**Comment by nemeros** [comment]
hello, we are also looking forward that kind of customization.

**Comment by lemt93** [comment]
Is there any updates on this?
> Refresh tokens for SPAs have a 24 hour lifetime. We currently do not have plans to remove the defaults, however, we will look into providing a way to turn off the defaults for those that don't want them, though this work has not yet been scheduled. Please do be aware that not using the refresh token may result in more frequent interactive sign-ins, especially in browsers that block 3rd party cookies.
In our application, we are fully aware of this could harm the user experience. But that's also exactly what we want for our application.

Any workarounds that I can use atm?

**Comment by VinoY27** [comment]
any update on enabling the user to exclude the "offline_access" scope? seems like the discussion happened a long time ago.  or any work around for this?

**Comment by peterzenz** [comment]
The offline_access scope will not be removed from the defaults.  If you want to control sign-in frequency to make sign more frequent for your users, please look into enabling [Conditional Access and Sign-in Frequency](https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/howto-conditional-access-session-lifetime).

**Comment by wparad** [comment]
> The offline_access scope will not be removed from the defaults. If you want to control sign-in frequency to make sign more frequent for your users, please look into enabling [Conditional Access and Sign-in Frequency](https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/howto-conditional-access-session-lifetime).

Or you know use any of the other providers where this works correctly:
* [AWS Cognito](https://aws.amazon.com/cognito/)
* [Auth0](https://auth0.com)
* [Authress](https://authress.io)

Or one of the hundreds of others that get this correct!

**Comment by PanicRide** [comment]
This is super frustrating... It's not about sign-in frequency.

In my case, I need to use the xbox specific scopes instead of the default ones. When I set the scopes to `XboxLive.signin Xboxlive.offline_access` it instead prompts my users to approve these ones on the consent screen: `XboxLive.signin Xboxlive.offline_access offline_access openid profile`

This gives my users the impression that I'm requesting much more information about their account than I need. They're absolutely right to be warry and now I have to find a way to implement the auth flows without this otherwise helpful library. :(

**Comment by wparad** [comment]
We gave up and released our own library to integration OAuth and support user login flows. I believe xbox live works with our provider, but I don't want to swear to it. Since we have given up on this, we've fully converted to 100% using https://authress.io/.

**Comment by PanicRide** [comment]
Just an FYI... when searching for my problem, I found and commented on this issue not yet realizing that it was for the js version of the msal library and not the python version I'm using. * _embarrassed_ *

I later found out that the python version of msal allows the exclusion of default scopes (including `offline_access`). For some reason, it does not allow the exclusion of the `openid` scope, so I submitted a [new issue](https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/528) there.

**Comment by wedevops1** [comment]
Just want to link [this issue](https://github.com/MicrosoftDocs/azure-docs/issues/107811) which is mine as well as [this issue](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5674). 

If one wants to control the session time of in a B2C tenant (according to the multiple sources as seen in the first linked issue) the `offline_access` scope **has** to be omitted. 

Just closing the issue won't solve the problem folks.

**Comment by pastinepolenta** [comment]
@wparad is your client library OSS? could you share the link? thanks

**Comment by wparad** [comment]
@pastinepolenta the problem isn't actually this library, it's AzureAD itself. It incorrectly implements OAuth, so even if you had a different library that did the same thing, it wouldn't actually work with AzureAD, because AzureAD is broken by design. :( That is why we completely switched to a different Auth provider.

**Comment by pastinepolenta** [comment]
> @pastinepolenta the problem isn't actually this library, it's AzureAD itself. It incorrectly implements OAuth, so even if you had a different library that did the same thing, it wouldn't actually work with AzureAD, because AzureAD is broken by design. :( That is why we completely switched to a different Auth provider.

Indeed I am not using Azure AD and I am looking for a good quality OAuth OIDC client

**Comment by wparad** [comment]
> > @pastinepolenta the problem isn't actually this library, it's AzureAD itself. It incorrectly implements OAuth, so even if you had a different library that did the same thing, it wouldn't actually work with AzureAD, because AzureAD is broken by design. :( That is why we completely switched to a different Auth provider.
> 
> Indeed I am not using Azure AD and I am looking for a good quality OAuth OIDC client

Oh, did you write your own oauth service? Most if not all oauth SaaS/open source oauth services have a coupled SDK which makes it easy to integrate with. Is there a reason you are looking for something special? I haven't tested our library with other providers, but it does implement most of the necessary pieces of an OAuth web client, which might even work for you: https://github.com/Authress/authress-login.js#platform-extension-login That being said if you try that and it doesn't work, feel free to file issues with that library, and we can evaluate if it makes sense to improve.

**Comment by pastinepolenta** [comment]
> oauth services have a coupled SDK

I see your point. Indeed I am investigating solutions for ~ 30 apps that connect to different identity providers (ADFS, OpenAM and Azure AD). I was first hoping to unify clients (and with a React adapter) as the providers are all (supposed to be) fully OAuth 2.0 OIDC compliant. But I see now that providers have their own specificity and that might call for multiple dedicated SDKs.

I will take a look at Authress anyways, thanks.

**Comment by kvisscher** [comment]
If there's anybody hitting this page through a search engine. I've managed to work-a-round this problem by doing this:

```ts
import { OIDC_DEFAULT_SCOPES } from "@azure/msal-common";
...
OIDC_DEFAULT_SCOPES.splice(OIDC_DEFAULT_SCOPES.indexOf('offline_access'), 1);
```

This will mutate the default scopes and make sure `offline_access` is no longer send in.

**Comment by hardsree123** [comment]
> If there's anybody hitting this page through a search engine. I've managed to work-a-round this problem by doing this:
> 
> ```ts
> import { OIDC_DEFAULT_SCOPES } from "@azure/msal-common";
> ...
> OIDC_DEFAULT_SCOPES.splice(OIDC_DEFAULT_SCOPES.indexOf('offline_access'), 1);
> ```
> 
> This will mutate the default scopes and make sure `offline_access` is no longer send in.
Where is this mutating?

**Comment by kvisscher** [comment]
> > If there's anybody hitting this page through a search engine. I've managed to work-a-round this problem by doing this:
> 
> > 
> 
> > ```ts
> 
> > import { OIDC_DEFAULT_SCOPES } from "@azure/msal-common";
> 
> > ...
> 
> > OIDC_DEFAULT_SCOPES.splice(OIDC_DEFAULT_SCOPES.indexOf('offline_access'), 1);
> 
> > ```
> 
> > 
> 
> > This will mutate the default scopes and make sure `offline_access` is no longer send in.
> 
> Where is this mutating? 
> 
> 

@hardsree123 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice

**Comment by jimdigriz** [comment]
Though Entra still seemingly hands out a refresh token even when you ask for it not to, you can strip `offline_access` being sent with more recently versions of MSAL using:
```
const msalConfig = {
  auth: {
    ..
    OIDCOptions: {
      defaultScopes: [ 'openid', 'email', 'profile' ]
    }
  }
};
```

...cause it is insane https://learn.microsoft.com/entra/identity-platform/scopes-oidc#the-offline_access-scope

Also conflicting behaviour to the documentation:
> On the Microsoft identity platform (requests made to the v2.0 endpoint), your app must explicitly request the offline_access scope, to receive refresh tokens.

...this is why we cannot have nice things.
