### ISSUE TITLE
Wiki page does not work

### ISSUE THREAD

**Issue by jhossy** [AzureAD/microsoft-authentication-library-for-js#365]
Attempting to navigate to https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Single-sign-on

results in the following errormessage "You do not have permission to update this wiki."

**Comment by nehaagrawal** [comment]
@jhossy  This is a work in progress.  I have removed the page for now to avoid any confusion but I will put it back soon.   Do have any specific question on single sign on that I can answer here?

**Comment by jhossy** [comment]
Ah, thanks for removing it then - that will avoid any future confusion.

Actually, I already posted this issue #340 , but since there was no feedback (maybe my question was unclear), I wanted to look closer at the documentation :)

Anyhow, I was wondering if msal.js supported SSO between a .NET MVC app that does NOT use MSAL and a SPA that uses MSAL.

**Comment by LeidyOcampo** [comment]
Hello @jhossy 

I have exactly the same problem you raise.

Have you already got any answer or solution about it that you can share with me?

Thank you

**Comment by jhossy** [comment]
@LeidyOcampo I did not get an answer, sorry

**Comment by nehaagrawal** [comment]
@jhossy  @LeidyOcampo  We already have a PR for SSO  and we are hoping to release it in a couple of weeks. Closing this issue in favour of https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/340.

**Comment by navyasric** [comment]
Please check the SSO wiki page now:
https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Sso
