### ISSUE TITLE
Wrong umdModuleIds for @azure/msal-browser in @azure/msal-angular

### ISSUE THREAD

**Issue by Droidlover** [AzureAD/microsoft-authentication-library-for-js#3650]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.0

### Description

Hi there,

In `microsoft-authentication-library-for-js-dev/lib/msal-angular/ng-package.json` umdModuleIds is as following : 
```
 "umdModuleIds": {
      "@azure/msal-browser": "@azure/msal-browser"
    }
```
After build this makes UMD file search for **msal-browser** in **global['@azure/msal-browser']** . But js file of msal-browser creates msal-browser instance as msal in global instance.

I think this is an issue. Can someone please help me out here.

### Error Message

Uncaught TypeError: Cannot read property 'NavigationClient' of undefined
    at azure-msal-angular.umd.js:864
    at azure-msal-angular.umd.js:4
    at azure-msal-angular.umd.js:5

### MSAL Configuration

```javascript
Not important
```

### Relevant Code Snippets

```javascript
Important statement : 
 {
                "bundleName": "msal-browser",
                "input": "node_modules/@azure/msal-browser/lib/msal-browser.js"
              },
              {
                "bundleName": "msal-angular",
                "input": "node_modules/@azure/msal-angular/bundles/azure-msal-angular.umd.js"
              }
```

### Reproduction Steps

1) Import msal-browser UMD script
2) Import msal-browser.js

### Expected Behavior

I should be able to import above scripts and get no error.

### Identity Provider

Other

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@Droidlover I've been unable to reproduce your issue. You're welcome to submit a PR for the change you want to see, and our team will review it with our libraries.
