### ISSUE TITLE
Where is Xbox Live Scope? 

### ISSUE THREAD

**Issue by Nishant1500** [AzureAD/microsoft-authentication-library-for-js#3652]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.1.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

I am making a Application Which uses Microsoft Authentication To Get Xbox Live Infos but I am unable to find a Xbox Live scope in API Permission Tab. So can you please tell me where is the Xbox live scope in Azure AD

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@Nishant1500 While you may find the [official XBox Live REST API documentation](https://docs.microsoft.com/en-us/gaming/xbox-live/api-ref/xbox-live-rest/additional/httpstandardheaders) useful, this isn't an issue that involves MSAL, so unfortunately we are not able to assist you. Please try contacting Azure Support for more help.

**Comment by Nishant1500** [comment]
Oh then I will contact Azure Support. Thanks anyways! :)

**Comment by jo-arroyo** [comment]
Closing as not involving MSAL.
