### ISSUE TITLE
Using prompt=login RedirectRequest parameter does not get passed to B2C Identity Provider

### ISSUE THREAD

**Issue by c0d3blooded** [AzureAD/microsoft-authentication-library-for-js#3656]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.0-beta.3

### Description

I'm working the include the `prompt=login` flag in an custom AD B2C flow which includes an Azure AD Identity Provider (in addition to email login). When the `prompt: 'login'` flag is added into the `loginRedirect` call, it's included in the initial B2C login URI (as a query parameter) but it is not included when using the Azure AD Identity provider.

### MSAL Configuration

```javascript
{
  auth: {
    clientId: xxxxx-xxxxx-xxxxx,
    authority: `https://xxxxxx.b2clogin.com/xxxxx.onmicrosoft.com/B2C_1_signin`,
    knownAuthorities: [
      `https://xxxxx.b2clogin.com/xxxxx.onmicrosoft.com/B2C_1_signin`
    ],
    cloudDiscoveryMetadata: '',
    redirectUri: window.location.origin,
    postLogoutRedirectUri: window.location.origin,
    navigateToLoginRequestUrl: true,
    clientCapabilities: ['CP1']
  },
  cache: {
    cacheLocation: BrowserCacheLocation.SessionStorage,
    storeAuthStateInCookie: false
  },
  system: {
    windowHashTimeout: 60000,
    iframeHashTimeout: 6000,
    loadFrameTimeout: 0,
    asyncPopups: false
  }
}
```

### Relevant Code Snippets

```javascript
const loginRequest: RedirectRequest = {
  authority: `https://xxxxx.b2clogin.com/xxxxx.onmicrosoft.com/B2C_1_signin`,
  scopes: ['openid', 'offline_access'],
  prompt: 'login'
};
...

<MsalAuthenticationTemplate interactionType={InteractionType.Redirect} authenticationRequest={loginRequest}>
   ...
</MsalAuthenticationTemplate>
```

### Reproduction Steps

1. Create and add Custom B2C Identity Provider for Azure AD
2. Configure MSAL login request to include the `prompt=login` field
3. Trigger loginRedirect in the MSAL library to go to the login page
4. Click on the Azure AD option included in the login page
5. Observe that the `prompt=login` field is not passed to the query parameters (although included on the initial page)

### Expected Behavior

The Identity provider selected should include the `prompt` flag in the query parameters if added in the base MSAL configuration

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@c0d3blooded This is a known issue that is currently being addressed by the B2C service. If you'd like to track this with them directly you can open a support ticket [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options) and in the meantime we'll leave this open until we've verified the fix has been rolled out.

**Comment by c0d3blooded** [comment]
ok, thank you @jo-arroyo!

**Comment by l-o-l** [comment]
Is there an update on this issue? I just hit the same issue with prompt=login not being included in the redirect.

**Comment by sameerag** [comment]
B2C service team addressed this for specific IDPs (google for example) but if it is a custom policy, the details are user specific. They had plans to roll it out eventually for a list of IDPs. To get the status for your specific use case, can you please follow up with the service team on the status by raising an issue [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options)?

**Comment by tnorling** [comment]
Closing as this is a service issue. If you're still experiencing issues please consider opening an issue with B2C. Thanks!
