### ISSUE TITLE
Double slash in logout url

### ISSUE THREAD

**Issue by yakimko** [AzureAD/microsoft-authentication-library-for-js#366]
Hi!
Sometimes the following line 
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/src/UserAgentApplication.ts#L551

makes double slash in url
for example

https://login.microsoftonline.com/tfp/myapp.onmicrosoft.com/b2c_1_base//oauth2/v2.0/logout...

I suppose that sometimes this.authority has a slash sign at the end.

**Comment by nehaagrawal** [comment]
@yakimko  this.authority is pass by the user in the MSAl config. Are you passing the authority with a slash at the end?  If yes, can you remove it and try again? If you don't want to remove it, what is the error that you are getting?

**Comment by yakimko** [comment]
@nehaagrawal I do not have a slash at end of my authority.

**Comment by nehaagrawal** [comment]
@yakimko  Can you please confirm 2 things. Is it a B2C scenario? What is the error you are getting because of double slash?

**Comment by lutzleonhardt** [comment]
The problem is the following line:
`var urlNavigate = this.authority + "/oauth2/v2.0/logout?" + logout;`

in this block:

```
    UserAgentApplication.prototype.logout = function () {
        this.clearCache();
        this._user = null;
        var logout = "";
        if (this._postLogoutredirectUri) {
            logout = "post_logout_redirect_uri=" + encodeURIComponent(this._postLogoutredirectUri);
        }
        var urlNavigate = this.authority + "/oauth2/v2.0/logout?" + logout;
        this.promptUser(urlNavigate);
    };
```

`this.authority` is a property:

```
    Object.defineProperty(UserAgentApplication.prototype, "authority", {
        get: function () {
            return this.authorityInstance.CanonicalAuthority;
        },
        set: function (val) {
            this.authorityInstance = AuthorityFactory_1.AuthorityFactory.CreateInstance(val, this.validateAuthority);
        },
        enumerable: true,
        configurable: true
    });
```

the getter calls `this.authorityInstance.CanonicalAuthority`

which is a property as well:

```
    Object.defineProperty(Authority.prototype, "CanonicalAuthority", {
        /*
         * A URL that is the authority set by the developer
         */
        get: function () {
            return this.canonicalAuthority;
        },
        set: function (url) {
            this.canonicalAuthority = Utils_1.Utils.CanonicalizeUri(url);
            this.canonicalAuthorityUrlComponents = null;
        },
        enumerable: true,
        configurable: true
    });
```

the setter uses `CanonicalizeUri()`:

```
    Utils.CanonicalizeUri = function (url) {
        if (url) {
            url = url.toLowerCase();
        }
        if (url && !Utils.endsWith(url, "/")) {
            url += "/";
        }
        return url;
    };
```

which adds a slash to end.

see:
![image](https://user-images.githubusercontent.com/11898898/44337467-1da3b200-a47b-11e8-953e-0773d2b2df00.png)

At the end it would help to optimize this path joining:
`this.authority + "/oauth2/v2.0/logout?"`
