### ISSUE TITLE
With Azure B2C App setting isB2C to true returns 401 response but not when it's false

### ISSUE THREAD

**Issue by mrs-eload** [AzureAD/microsoft-authentication-library-for-js#3660]
Using Azure B2C application to test authentication I used the following configuration with OIDCStrategy.
Being in a NestJS application I also use @nestjs/passport as passport wrapper.
passport-azure-ad version : `4.3.0`

```javascript
{
    identityMetadata: 'https://mytenant.b2clogin.com/mytenant.onmicrosoft.com/MY_POLICY/v2.0/.well-known/openid-configuration',
    clientID: 'xxxxx-xxxxx-xxxx-xxxxx',
    clientSecret: 'xxxxxxxx',
    isB2C: true,
    responseType: 'id_token code',
    responseMode: 'form_post',
    redirectUrl: 'xxxxxxx',
    profile: ['email','profile']
}
```

This configuration always returns the following

```json
{
  "statusCode": 401,
  "message": "Unauthorized"
}
```

After playing around with B2C for a while, it appears that setting `isB2C` to `false` is properly authenticating me against Azure B2C, when the opposite should happen I guess .

**Comment by jo-arroyo** [comment]
Closing as passport-azure-ad is in maintenance and no longer receiving updates. This issue will be addressed in future middleware scenarios built on top of msal-node. Keep an eye out for msal-node updates.
