### ISSUE TITLE
How to provide Metadata endpoint just like AAD? 

### ISSUE THREAD

**Issue by nilact** [AzureAD/microsoft-authentication-library-for-js#3661]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

I'm using MSAL.jx v2.x for authentication and other flow of Azure B2C AD.

Can we provide a metadata endpoint ourselves, just like AAD for Azure B2C [as mentioned in the documentation](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/performance.md)?

At present, the library hits the discovery endpoint and uses its response for all the flows.

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@nilact Can you clarify what you mean by the following:

> At present, the library hits the discovery endpoint and uses its response for all the flows.

**Comment by nilact** [comment]
@jo-arroyo 

It is working as expected. It should hit the Metadata endpoint and use it for all the other flows and grab the appropriate endpoint, for example, /token.

However, as per the documentation, we can provide the Metadata for AAD as a part of the configuration.

Can we do the same for Azure B2C AD? Is it supported?

**Comment by tnorling** [comment]
@nilact Yes this is supported for B2C

**Comment by nilact** [comment]
@tnorling 

But the [documentation ](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/performance.md)reads for B2C, it is not supported. One has to see whether it is working or not despite in documentation says it doesn't? I've added the same note below from the documenation.


> Note: If you are using B2C or ADFS authorities this document is not applicable. You will need to provide your authority domains to the auth.knownAuthorities property instead.

**Comment by tnorling** [comment]
This is a mistake in the docs, I will make sure this gets fixed. Thanks for pointing this out.

To set the record straight: The first section of the doc "Bypass cloud instance discovery resolution" **is not** supported for B2C because the B2C service doesn't expose this endpoint or metadata. The second section of the doc "Bypass authority metadata resolution" **is** supported for B2C.

**Comment by nilact** [comment]
I believe [this](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/configuration.md) page also needs to be updated to indicate that cloudDiscoveryMetaData is for the AAD scenario and authorityMetadata is for Azure B2C.
