### ISSUE TITLE
Proper Types not mentioned in the docs for `instance.acquireTokenSilent ` function

### ISSUE THREAD

**Issue by Shivam60** [AzureAD/microsoft-authentication-library-for-js#3665]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL React (@azure/msal-react)

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/hooks.md

### Description

As per the docs there is no typescript issue for using `acquireTokenSilent` funciton from useMsal lib.

However in practice this issue is observed
![image](https://user-images.githubusercontent.com/13963817/119093168-f95ed080-ba2c-11eb-8747-23e84d661938.png)

Error is 
Type 'Partial<Pick<AccountInfo, "homeAccountId" | "localAccountId" | "username">>' is missing the following properties from type 'AccountInfo': environment, tenantIdts(2739)
SilentRequest.d.ts(20, 5): The expected type comes from property 'account' which is declared here on type 'SilentRequest'

**Comment by tnorling** [comment]
@Shivam60 thanks for bringing this up, I'll make sure the docs get updated. 

To resolve, you can either cast this to the right type `accounts[0] as AccountInfo` or use the `useAccount` hook to get the `AccountInfo` object. `const account = useAccount(accounts[0])`

**Comment by RonaldRegan69** [comment]
Thanks
