### ISSUE TITLE
Why msal-core and msal-browser doesnt support stateless login (or redirections from other login origin)?

### ISSUE THREAD

**Issue by menosprezzi** [AzureAD/microsoft-authentication-library-for-js#3668]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

latest

### Wrapper Library

Not Applicable

### Wrapper Library Version

none

### Description

Hello guys!!

We have one application that redirects to our Azure ADB2C login URL.
Let's say that this application lives in `https://my.app.com`.

So this application do a `window.location.assign` to:
```
https://<tenant>.b2clogin.com/<tenant>.onmicrosoft.com/oauth2/v2.0/authorize?
p=B2C_1A_SignUpOrSignin_TOU
&client_id=<client_id>
&nonce=defaultNonce
&redirect_uri=<app URL already registered. let's say https://another.app.com>
&scope=openid%20profile
&response_type=id_token
```

When the user completes the login, the browser redirects to the redirect_uri (`https://another.app.com` for instance).

This another application initialize the `UserAgentApplication` from `msal` and it runs the following assertion:
[UserAgentApplication.ts#L233](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/src/UserAgentApplication.ts#L233)
```ts
        if (urlContainsHash) {
            const stateInfo = this.getResponseState(urlHash);
            if (stateInfo.method === Constants.interactionTypeRedirect) {
                this.handleRedirectAuthenticationResponse(urlHash);
            }
        }
```

The `handleRedirectAuthenticationResponse` will check if the URL has a `state` query param, and if isn't present, it throws the following error message.

So, if we pass a blank value or a random value (as described in [Microsoft identity platform and implicit grant flow docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-implicit-grant-flow)) to the state param, msal cant validate it because it required to match a `ResponseStateInfo` encoded in base64. Even if we pass a fake `ResponseStateInfo` to it, it will crash, [redirecting to '/' because it doesn't is set in the cacheStorage and it will ignore the id_token that came with it](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/9eab0f4be2be20dd828a033941fbd9a30fb92f1e/lib/msal-core/src/UserAgentApplication.ts#L1249) and it has be in there, created by the `msal` when we calls `loginRedirect` function. But in my point of view it doesn't do anything, even the `state` param is marked as **recomended** in the implicit grant flow docs, but msal requires it and it doesn't is documented anywhere.

So, we can't create a login flow independent from `msal` library, it interaction has to start from it. Even if `https://my.app.com` instantiate the `msal` library, it has to be in the same origin because `localStorage` won't be shared between different origins.
Ok, cookies can do the job. But it won't support different sites :(.

I've checked the code in the `msal-browser` lib and it has the same functionality.

Also, congrats for your codebase! It's awesome work and the code is readable to figure out what is happening!
Thanks!

### Error Message

AuthError: Unexpected error in authentication.: Hash does not contain state

### MSAL Configuration

```javascript
{
  auth: {
    clientId: process.env.AADB2C_CLIENT_ID,
    validateAuthority: false,
  },
  cache: {
    cacheLocation: 'localStorage',
    storeAuthStateInCookie: false
  }
}
```

### Relevant Code Snippets

```javascript
None
```

### Reproduction Steps

1. Initialize a SPA with `msal` and run it locally
2. Open the URL https://<tenant>.b2clogin.com/<tenant>.onmicrosoft.com/oauth2/v2.0/authorizep=B2C_1A_SignUpOrSignin_TOU&client_id=<client_id>&nonce=defaultNonce&redirect_uri=<local URL here>&scope=openid%20profile&response_type=id_token
3. Do login

### Expected Behavior

Load user id_token and don't show any errors

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer

### Source

External (Customer)

**Comment by pkanher617** [comment]
@menosprezzi We don't support handling a login from another application in MSAL. In order for MSAL login flows to work, the request must originate from the MSAL library. Our authentication relies on the fact that your application's sign-in is bound to a single domain. 

We also send other information in the state parameter to inform MSAL how to handle responses in redirect vs popup cases, so while the state parameter is only recommended and not required for OAuth flows, we will use on every request.

> Also, congrats for your codebase! It's awesome work and the code is readable to figure out what is happening!

Thank you for the feedback :)

**Comment by menosprezzi** [comment]
@pkanher617 

Thanks for your quick and awesome response!

Any plans to msal support this flow, ignoring the necessity of the state param and reading the id_token param coming in url  by default? What block this? Security reasons?

**Comment by pkanher617** [comment]
@menosprezzi We unfortunately won't be supporting this at this time. MSAL will only consume the tokens and redirect parameters if MSAL initiated the request. This is mostly to prevent the app authentication from ending up in a bad state.
