### ISSUE TITLE
@azure/msal-angularjs: 404 not found during NPM Install

### ISSUE THREAD

**Issue by RobARichardson** [AzureAD/microsoft-authentication-library-for-js#367]
I'm trying to install the AngularJS wrapper per the [documentation](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angularjs/README.md) but it doesn't appear to actually be available on NPM; getting a 404 Not Found.

**Comment by alyssaw90** [comment]
I am getting the same error when I try to install @azure/msal-angular.

**Comment by ahenaol** [comment]
It could be because the MSAL version that uses the 3 libraries as separate packages is still in the dev branch.

**Comment by RobARichardson** [comment]
@ahenaol Ooops, you're correct - didn't realize I was looking at the dev documentation. Closing this since it's not technically an issue. Thanks.
