### ISSUE TITLE
Errors in the Documentation

### ISSUE THREAD

**Issue by eluchsinger** [AzureAD/microsoft-authentication-library-for-js#3671]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/initialization.md

### Description

Trying to follow the MSAL Angular documentation step by step, there seem to be some inconsistencies.

[Step one](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/initialization.md#include-and-initialize-the-msal-module-in-your-app-module) is adding the `clientId`, but the `MsalModule.forRoot` method requires three parameters, so the code will not run:

```ts
@NgModule({
    imports: [
        MsalModule.forRoot( new PublicClientApplication({
            auth: {
                clientId: "Your client ID"
            }
        })
    ]
})
export class AppModule {}
```

[Step three](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/initialization.md#get-tokens-for-web-api-calls) is about getting the tokens for the Web API calls, but there are now missing code parts which lead to compilation errors. For example, the `PublicClientApplication` is not initialized anymore, leading the following error:

> TS2345: Argument of type '{ auth: { clientId: string; }; }' is not assignable to parameter of type 'IPublicClientApplication'.   Object literal may only specify known properties, and 'auth' does not exist in type 'IPublicClientApplication'.

```ts
@NgModule({
    imports: [
        MsalModule.forRoot({ // MSAL Configuration
            auth: {
                clientId: "Your client ID"
            }
        }, {
            interactionType: InteractionType.Popup, // MSAL Guard Configuration
            authRequest: PopupRequest
        }, {
            protectedResourceMap: new Map([ // MSAL Interceptor Configuration
                ['https://graph.microsoft.com/v1.0/me', ['user.read']],
                ['https://api.myapplication.com/users/*', ['customscope.read']],
                ['http://localhost:4200/about/', null] 
            ])
        })
    ],
    providers: [
        ProductService, 
        {
            provide: HTTP_INTERCEPTORS,
            useClass: MsalInterceptor,
            multi: true
        }
    ]
})
export class AppModule {}
```
After adding the `new PublicClientApplication`, the next error is about `PopupRequest`:

> TS2693: 'PopupRequest' only refers to a type, but is being used as a value here.

And at the same time, I get the error about the `protectedResourceMap`:

> TS2345: Argument of type '{ protectedResourceMap: Map<string, string[]>; }' is not assignable to parameter of type 'MsalInterceptorConfiguration'.   Property 'interactionType' is missing in type '{ protectedResourceMap: Map<string, string[]>; }' but required in type 'MsalInterceptorConfiguration'.

These samples are crucial for a good DX. If I were to make another suggestion, maybe make the samples to give more context (i.e. show the imports). They do not have to be step by step because everything is very coupled. Maybe just post the whole code and then explain it below step by step.

**Comment by jo-arroyo** [comment]
@eluchsinger Thanks for your feedback. We will work on making the docs and code samples more comprehensive and link the PR here once it's up.

**Comment by jo-arroyo** [comment]
@eluchsinger I've recently merged a PR that addresses the concerns you raised. Thanks again for your feedback. Closing this issue, if you have any further feedback please feel free to open a new issue.
