### ISSUE TITLE
how to sign in a user using id token hint

### ISSUE THREAD

**Issue by clivecham** [AzureAD/microsoft-authentication-library-for-js#3672]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

Does MSAL JS support id token hint to SSO a user? The use case is the user is sign in to a mobile app and attempt to access a website launched from webview. The mobile app will pass the id_token_hint to the website to SSO to the website so that the user will not need to enter credential.

The website is using MSAL.JS v2. If it does support this use case, can someone advise how to do that? Is there a sample code for reference? Any known limitation?

TIA.

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by pkanher617** [comment]
@clivecham We do not support id_token_hint on the login flows today, but you can pass the id_token_hint by using the [`extraQueryParameters` request option](https://azuread.github.io/microsoft-authentication-library-for-js/ref/modules/_azure_msal_browser.html#redirectrequest). Example:

```javascript
const request = {
    scopes: ["scope1"],
    extraQueryParameters: {
        "id_token_hint": "ey...."
    }
};
```

However this won't achieve the silent sign-in that you are looking for. You can achieve this by extracting the username from the id_token and passing it to the `login_hint` request option.

**Comment by clivecham** [comment]
@pkanher617  thank you for the reply. Isn't this what id_token_hint should do? I am looking at this doc and looks like it will sign the user in : https://docs.microsoft.com/en-us/azure/active-directory-b2c/id-token-hint

TIA.

**Comment by pkanher617** [comment]
You can try it, but I was informed that it will only work for a sign-up flow, such as the an invite email (see [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/id-token-hint#use-cases). To get the SSO that you are looking for you will need to extract the username from the token claims and pass it to the login_hint.
