### ISSUE TITLE
msal-node’s configuration types doesn’t allow elements on the clientCapabilities (type [] does not allow elements)

### ISSUE THREAD

**Issue by sadasant** [AzureAD/microsoft-authentication-library-for-js#3676]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

Latest

### Wrapper Library

Not Applicable

### Wrapper Library Version

Not applicable

### Description

The type of clientCapabilities On msal-node is `[]`, but that type does not allow properties to be set. It should be at least `string[]`.

This is what I’m seeing when I try to pass values in that property. Let me know if I’m missing something.

### Error Message

`[string] is not assignable to type []` or `string[] is not assignable to type []`

### MSAL Configuration

```javascript
{ auth: { clientCapabilities: [“CP1”] } }
```

### Relevant Code Snippets

```javascript
{ auth: { clientCapabilities: [“CP1”] } }
```

### Reproduction Steps

TypeScript would probably give the error out if a TypeScript sample is made in which any string array is passed to this property.

### Expected Behavior

String arrays should be allowed.

### Identity Provider

Other

### Browsers Affected (Select all that apply)

Other

### Source

Internal (Microsoft)

**Comment by sameerag** [comment]
I am not sure if this is supposed to be string. @tnorling to comment once.

**Comment by tnorling** [comment]
@sameerag Yes it should be type `string[]`. Thanks @sadasant, I'm surprised this didn't get caught earlier...
