### ISSUE TITLE
suggestion to make configuration value in PublicClientApplication dynamic 

### ISSUE THREAD

**Issue by deepti1805** [AzureAD/microsoft-authentication-library-for-js#3692]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.6.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

Not applicable

### Description

We have one scenario where we have 3 policy signin, signup and forgot password, and we are handling their response in single js file. Initially we are having signin policy as a default and whenever the page redirect back to home page it only trigger that default policy. My question is that is there any way if we can make this configuration dynamic.

Please suggest any way to do this.

### MSAL Configuration

```javascript
const msalConfigSignInSignUp = {
        auth: {
            clientId: clientId,
            authority: b2cPolicies.authorities.signUpSignIn.authority,
            validateAuthority: false,
            knownAuthorities: [b2cPolicies.authorityDomain],
            redirectUri:signInRedirectValue,
            postLogoutRedirectUri: logOutRedirectValue
        },
        cache: {
            cacheLocation: "sessionStorage", // This configures where your cache will be stored
            storeAuthStateInCookie: false // Set this to "true" to save cache in cookies to address trusted zones limitations in IE (see: https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Known-issues-on-IE-and-Edge-Browser)
        }
    };
```

### Relevant Code Snippets

```javascript
initMsalConfig(msalConfigSignInSignUp);

    function initMsalConfig(configuration) {

        if ( configuration.auth && configuration.auth.clientId) {
            msalInstance = new msal.PublicClientApplication(configuration);
        }
        if (msalInstance != null) {
            msalInstance.handleRedirectPromise()
                .then(handleResponse)
                .catch(error => {
                    console.error(error);
                    console.log(error.errorMessage);
                    if (error && error.errorMessage && error.errorMessage.indexOf("AADB2C90118") > -1) {
                        try {
                            msalInstance.loginRedirect(b2cPolicies.authorities.forgotPassword);
                        } catch (err) {
                            console.log(err);
                        }
                    }
                });
        }
    }
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by pkanher617** [comment]
@deepti1805 You can set the authority per request, which it appears you are doing. 

> Initially we are having signin policy as a default and whenever the page redirect back to home page it only trigger that default policy. My question is that is there any way if we can make this configuration dynamic.

Are you saying you don't want the signUpSignIn policy to be the default every time? I think that is something that you can better handle in the application, rather than updating the configuration in MSAL.

**Comment by deepti1805** [comment]
> @deepti1805 You can set the authority per request, which it appears you are doing.
> 
> > Initially we are having signin policy as a default and whenever the page redirect back to home page it only trigger that default policy. My question is that is there any way if we can make this configuration dynamic.
> 
> Are you saying you don't want the signUpSignIn policy to be the default every time? I think that is something that you can better handle in the application, rather than updating the configuration in MSAL.
ok @pkanher617 I was thinking some other solution for this condition but its fine will work on our application. Thanks.
