### ISSUE TITLE
After Upgrading to msal v2 in angular, MSAL Guard not considering the --base-href parameter while redirecting after loggin in

### ISSUE THREAD

**Issue by johnvinosh** [AzureAD/microsoft-authentication-library-for-js#3693]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.0

### Description

I was using msal v1 and it was working fine. I tried to update to v2 and I made all the configuration. Application was working on my local computer. But I am facing issue while deploying to server.

I don't host my application on a root path instead in a folder named "mywebsite", So while building the application I use the following command.

`ng build --base-href=/mywebsite/`

Application is running fine in this URL `www.test.com/mywebsite`. Please find the below logs.

![image](https://user-images.githubusercontent.com/26540475/119945077-a21fa980-bfb2-11eb-85a6-23083e824041.png)

But After the login it is redirecting me to

`https://www.test.com/abc` instead of `www.test.com/mywebsite/abc` and it says page can't be found.

But if I access the url directly `www.test.com/mywebsite/abc`, application is working fine without any issues

Please let me know how to fix this issue.

### Error Message

404 Error: This page www.test.com/abc can't be found
No webpage was found for the web address: https://www.test.com/abc 

![image](https://user-images.githubusercontent.com/26540475/120648193-fa661800-c498-11eb-8f6f-39a97d9a78ff.png)

### MSAL Configuration

```javascript
export function MSALInstanceFactory(): IPublicClientApplication{
  return new PublicClientApplication({
    auth: {
      clientId: 'xxxxx',
      authority: 'https://login.microsoftonline.com/xxxx',
      redirectUri: 'https://www.test.com/mywebsite'
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE, // set to true for IE 11
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Info,
        piiLoggingEnabled: false,
      },
    },
  });
}

export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
  const protectedResourceMap = new Map<string, Array<string>>();
  protectedResourceMap.set('https://www.test.com/api/v1', ['api://xxxx']);
  protectedResourceMap.set('https://graph.microsoft.com/v1.0/m', ['user.read']);

  return {
    interactionType: InteractionType.Redirect,
    protectedResourceMap
  }
}

export function MSALGuardConfigFactory(): MsalGuardConfiguration {
  return { 
    interactionType: InteractionType.Redirect,
    authRequest: {
      scopes: ["user.read",
    "openid",
    "profile",'api://xxxx']
    }
  };
}
```

### Relevant Code Snippets

```javascript
const routes: Routes = [
  {
    path: "abc",
    loadChildren: () => import("./abc/abc.module").then((m) => m.AbcModule),
    canActivate: [MsalGuard],
  },
  {
    path: "help",
    component: HelpComponent,
  },
  {
    path: "home",
    component: HomeComponent,
  },
  { path: "**", redirectTo: "home" },
];

export function isInIframe() {
  return window !== window.parent && !window.opener;
}

@NgModule({
  imports: [
    RouterModule.forRoot(routes, {
      useHash: false,
      initialNavigation: isInIframe() ? "disabled" : undefined,
    }),
  ],
  exports: [RouterModule],
})
export class AppRoutingModule {}
```

### Reproduction Steps

Open a URL which has MSALGuard

### Expected Behavior

It should redirect to https://www.test.com/mywebsite/abc

instead of https://www.test.com/abc

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

External (Customer)

**Comment by mmanikandan123** [comment]
we are using the "**@azure/msal-browser": "^2.14.0"** in **angular 10**.  Created the azure app service root and subfolder virtual directory, deployed the angular applications respectively into root and subfolder. 
For example
Root site :  https://domain.com/
Subfolder site :  https://domain.com/site1

we are this build command for 
root app: ng build --configuration=dev
subfolder site : ng build --configuration=dev **--base-href /site1/**

**Scenario 1:**
when browse the url https://domain.com/site1, but it redirects to the root app (https://domain.com/) instead of subfolder site (https://domain.com/site1). 

**Scenario 2**
when browse the url https://domain.com/, it's login to root app. then if click on subfolder site (https://domain.com/site1), it works fine that redirecting to subfolder site(site1). when refresh from the page from subfolder site(site1). MSAL browser redirects to root app instead of subfolder site(site1).

**Expected Behavior**
when **refresh the page from https://domain.com/site1** It should redirect to **https://domain.com/site1 instead of https://domain.com/**

Please provide the solution if anyone has fixed the issue.

**Comment by jasonnutter** [comment]
Apologies for the delay, we'll look into fixing this soon, thanks!

**Comment by jasonnutter** [comment]
As a workaround, make sure that the correct base url is set in the `base` element that is rendered on the page. We'll look into making the interceptor smarter to be able to pick up a base url that is passed via the command line.

**Comment by johnvinosh** [comment]
Hello @jasonnutter , Thanks for looking into this issue. Could you please let me know where to add this base element ?

Because, when I use this command to build `ng build --base-href=/mywebsite/`, It will automatically add the base element to index.html. Please find the index.html which is generated using this command. But still it doesn't work.

```
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>NexGenPIRL</title>
  <base href="/mywebsite/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="./assets/images/LIILogo.png">
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link rel="stylesheet" href="styles.543307f9231b15d56c24.css"></head>

<body class="mat-typography">
  <app-root></app-root>
  <app-redirect></app-redirect>
<script src="runtime.cc17d9430dd5a0d7c3c2.js" defer></script><script src="polyfills-es5.656e0eeb03cdcf39fd05.js" nomodule defer></script><script src="polyfills.ff0a62850b88009ad471.js" defer></script><script src="scripts.7b3488e34fce5c5db494.js" defer></script><script src="main.f6f5aff155e5e807d521.js" defer></script></body>

</html>
```

**Comment by jasonnutter** [comment]
@johnvinosh Unfortunately, I am unable to reproduce your issue. When setting `--base-href` (and correct redirect uri in msal), I get redirected back to the correct app. Can you please try reproducing this with one of our samples? https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples

**Comment by johnvinosh** [comment]
Hello @jasonnutter , I can able to reproduce the issue using Angular 10 Sample App which is taken from this repository. 

[Angular 10 Sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular10-sample-app)

Please find the steps which I did to reproduce the issue.
1. Downloaded the sample app from [Angular 10 Sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular10-sample-app)
2. Ran `npm install`
3. Updated the cliendId, authority and redirectUri in app.module.ts
4. Updated the graph url in app.module.ts and profile.component.ts
5. Ran build command `ng build --base-href=/mywebsite/`
6. Build generated the folder in dist.
7. Renamed the folder to 'mywebsite'
8. Deployed the folder to my tomcat server.
9. App was running fine in the following URL `https://www.test.com/mywebsite`. Please find the screenshot for the same.

![image](https://user-images.githubusercontent.com/26540475/121473891-ef534080-c9e0-11eb-858d-b28c485d5cb9.png)

Now when I click on Login, Everything was working fine. It is redirected to the login in screen and it is coming back to the `https://www.test.com/mywebsite` URL.

![image](https://user-images.githubusercontent.com/26540475/121474242-6a1c5b80-c9e1-11eb-955f-7817978c4e11.png)

But here is the issue. Without logging in, Click on the Profile button. MSALGuard is redirecting me to login screen.

![image](https://user-images.githubusercontent.com/26540475/121474375-a059db00-c9e1-11eb-8aff-78b53f0c8b0c.png)

Once After login is completed it is navigating back to `https://www.test.com/profile` instead of `https://www.test.com/mywebsite/profile` and shows page cannot found.

![image](https://user-images.githubusercontent.com/26540475/121474467-be274000-c9e1-11eb-8978-9360deed18b7.png)

But if I navigate to the URL `https://www.test.com/mywebsite/profile` manually, It is working fine.

![image](https://user-images.githubusercontent.com/26540475/121474654-ffb7eb00-c9e1-11eb-875c-9671208ce253.png)

**Comment by jasonnutter** [comment]
@johnvinosh This appears to be a bug with the `MsalCustomNavigationClient`. Please try commenting these lines out: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/319600946963c68d1bd8f6f001f05c3637213cfc/samples/msal-angular-v2-samples/angular10-sample-app/src/app/app.component.ts#L28-L29

**Comment by johnvinosh** [comment]
@jasonnutter You are right. After commenting out that line. It is working now as expected.

But just want to understand, What will be the impact of removing it. Will there be any performance issues ?

Will it be fixed on future release ?

**Comment by jasonnutter** [comment]
@johnvinosh The custom navigation client is provided to make navigating between pages in your site (in the context of MSAL) faster, so removing will mean actions like navigating between the redirect uri and redirect start page will take longer (as it will no longer use the Angular router).

And yes, we'll look into fixing this.
