### ISSUE TITLE
Invalid code example for setLogger in MSAL 2 Angular

### ISSUE THREAD

**Issue by dvut** [AzureAD/microsoft-authentication-library-for-js#3694]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/logging.md

### Description

The code example for setting a logger seems to be invalid code:

_The logger can also be set dynamically by using MsalService.setLogger()._

```
this.authService.setLogger(new Logger((logLevel, message, piiEnabled) => {
        console.log('MSAL Logging: ', message);
    },
    correlationId: CryptoUtils.createNewGuid(),
    piiLoggingEnabled: false
));
```

**Comment by jasonnutter** [comment]
@jo-arroyo Can you please look at this when you get a chance?
