### ISSUE TITLE
npm install @azure/msal-node

### ISSUE THREAD

**Issue by RoystonGates** [AzureAD/microsoft-authentication-library-for-js#3697]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

N/A

### Wrapper Library

MSAL Node Extensions (@azure/msal-node-extensions)

### Wrapper Library Version

N/A

### Description

When i use command:
npm install @azure/msal-node i continually get following error:
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t ssh://git@github.com/pemrouz/buble.git
npm ERR!
npm ERR! ssh: connect to host github.com port 22: Connection timed out
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XXXX\AppData\Roaming\npm-cache\_logs\2021-05-28T13_50_52_217Z-debug.log

### MSAL Configuration

```javascript
N/A
```

### Relevant Code Snippets

```javascript
N/A
```

### Reproduction Steps

N/A

### Expected Behavior

N/A

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by sameerag** [comment]
@RoystonGates Does this happen on a clean install?

**Comment by RoystonGates** [comment]
No I will try adding to clean install to see what happens,  currently I'm adding to existing project which has also had node/npm upgraded V10 to v14 


Get Outlook for Android

**Comment by RoystonGates** [comment]
@sameerag Thankyou I took your advice and tried a clean install by deleting node modules and adding "@azure/msal-node": "^1.0.0" to the package.json and reinstalled. This worked and completed the installation though this time there was a warning rather than an error and was treated as an optional dependancy, which is fine by me, thanks again for your help :)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Error while executing:
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: C:\Program Files\Git\cmd\git.EXE ls-remote -h -t ssh://git@github.com/pemrouz/buble.git
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ssh: connect to host github.com port 22: Connection timed out
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fatal: Could not read from remote repository.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY:
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Please make sure you have the correct access rights
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: and the repository exists.

**Comment by sameerag** [comment]
Great!
