### ISSUE TITLE
Using the Azure AD B2C Localization Feature in msal-angular v2

### ISSUE THREAD

**Issue by lukas-mertens** [AzureAD/microsoft-authentication-library-for-js#3704]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.12.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.0

### Description

How can I use the localization option of Azure AD B2C in the msal-angular library v2? I wasn't able to find any documentation. I tried adding a `lang: 'de'` parameter to the `extraQueryParameters` in the `MsalGuardConfiguration` already,  as it was recommended in [this issue](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1530), but that didn't help. What am I doing wrong? Could an example be added to the docs, I believe this is an issue many people have.

### MSAL Configuration

```javascript
see below
```

### Relevant Code Snippets

```javascript
private static MSALInstanceFactory(): IPublicClientApplication {
    return new PublicClientApplication({
      auth: {
        clientId: environment.oauth.clientId,
        authority: environment.oauth.authority,
        redirectUri: environment.oauth.redirectUri,
        postLogoutRedirectUri: environment.oauth.postLogoutRedirectUri
      },
      cache: {
        cacheLocation: BrowserCacheLocation.LocalStorage,
        storeAuthStateInCookie: OauthService.isIE(), // set to true for IE 11
      },
      system: {
        loggerOptions: {
          loggerCallback: (logLevel: LogLevel, message: string) => {
            console.log(message);
          },
          logLevel: LogLevel.Info,
          piiLoggingEnabled: false
        }
      }
    });
  }

  private static isIE() {
    return window.navigator.userAgent.indexOf('MSIE ') > -1 || window.navigator.userAgent.indexOf('Trident/') > -1;
  }

  private static MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
    const protectedResourceMap = new Map<string, Array<string>>();
    protectedResourceMap.set('https://graph.microsoft.com/v1.0/me', ['user.read']);

    return {
      interactionType: InteractionType.Redirect,
      protectedResourceMap
    };
  }

  private static MSALGuardConfigFactory(): MsalGuardConfiguration {
    return {
      interactionType: InteractionType.Redirect,
      authRequest: {
        scopes: ['user.read', 'openid', 'profile', 'email', 'phone'],
        extraQueryParameters: {
          lang: 'de'
        }
      }
    };
  }

  public static MMSALProviders(): Array<Provider> {
    return [
      {
        provide: HTTP_INTERCEPTORS,
        useClass: MsalInterceptor,
        multi: true
      },
      {
        provide: MSAL_INSTANCE,
        useFactory: OauthService.MSALInstanceFactory
      },
      {
        provide: MSAL_GUARD_CONFIG,
        useFactory: OauthService.MSALGuardConfigFactory
      },
      {
        provide: MSAL_INTERCEPTOR_CONFIG,
        useFactory: OauthService.MSALInterceptorConfigFactory
      },
      MsalService,
      MsalGuard,
      MsalBroadcastService
     ];
  }
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by pkanher617** [comment]
@lukas-mertens Do you see the `lang=de` query parameter added to the url?

**Comment by lukas-mertens** [comment]
@pkanher617 no, at least in my setup it adds another parameter to the request in which it requests the custom html: some-domain-where-i-host-the-html.org/en/idpSelector.html?ui_locales=en

I couldn't find a lang=de parameter in another url, which one should it be?

**Comment by pkanher617** [comment]
It should show up in the call to the `https://<authority-url>/authorize/...` endpoint (the one which the page is redirected to or is opened inside of a popup). I will check with the B2C team what the expected behavior here should be.

**Comment by lukas-mertens** [comment]
No, there isn't any: `https://<my-adb2c-name>.b2clogin.com/<my-adb2c-name>.onmicrosoft.com/b2c_1_registration_login/oauth2/v2.0/authorize?client_id=<my-client-id>&scope=openid%20profile%20offline_access&redirect_uri=http%3A%2F%2Flocalhost%3A4200%2F&client-request-id=<my-client-request-id>&response_mode=fragment&response_type=code&x-client-SKU=msal.js.browser&x-client-VER=2.12.0&x-client-OS=&x-client-CPU=&client_info=1&code_challenge=<my-code-challenge>&code_challenge_method=S256&nonce=<my-nonce>&state=<my-state>`

**Comment by samuelkubai** [comment]
@lukas-mertens the parameter to be passed should be `ui_locales` in the `extraQueryParameters ` object. If you try this and the parameter is not propagated as expected, please provide a network trace.

**Comment by lukas-mertens** [comment]
Before this is getting closed: It didn't work yet, I am currently trying to fix another problem though. It is unlikely that it is related, but I want to be sure... The ui_locales parameter is still not present. Is there any minimal example which includes this? Where can I find documentation? Probably this could serve as a documentation task issue in the meantime.

**Comment by jasonnutter** [comment]
@lukas-mertens Documentation is available here: https://docs.microsoft.com/en-us/azure/active-directory-b2c/language-customization?pivots=b2c-user-flow

**Comment by samuelkubai** [comment]
@lukas-mertens you could also go through the sample [here](https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp/tree/master#optional) to get a better feel of how to implement the ui locale.

Note: The example is a v1 sample but I would expect it works the same in v2

**Comment by lukas-mertens** [comment]
@samuelkubai 
```
  private static MSALGuardConfigFactory(): MsalGuardConfiguration {
    return {
      interactionType: InteractionType.Redirect,
      authRequest: {
        scopes: ['user.read', 'openid', 'profile', 'email', 'phone'],
        extraQueryParameters: {
          ui_locales: 'en'
        }
      }
    };
  }
```
Am I doing it in the right place? I wanted to look into the source code of the library to find out what's going on, but a search for `ui_locales` yields no results. That means that the library just passes on whatever I add there to Azure AD, right? So there are only two options left: 
1. Something in my configuration of AD B2C in Angular is broken, so that it isn't able to add those parameters.
2. I added it to the wrong MsalGuardAuthRequest.

The second option seems more likely to me. Should it be added to the `loginRedirect()` method somehow? The method accepts a RedirectRequest, I used `undefined` as a value for the standard loginFlow so far, though. What's even the exact responsibility of the MsalGuardConfig and how is it related to the RedirectRequest passed to loginRedirect? Probably I am looking at the wrong docs, but I couldn't find any full explanation. Maybe I am just bad at using google, but I can't find it.

**Comment by tnorling** [comment]
@lukas-mertens 

> That means that the library just passes on whatever I add there to Azure AD, right?

Correct. `extraQueryParameters` is the mechanism provided by MSAL to add any additional query parameters to the /authorize request that we don't already account for on the public API surface. So this would be the correct way to include the `ui_locales` parameter.

> Should it be added to the loginRedirect() method somehow?

Yes, if you are calling `loginRedirect` directly you will need to pass the authRequest to that function

> What's even the exact responsibility of the MsalGuardConfig and how is it related to the RedirectRequest passed to loginRedirect?

The `MsalGuardConfig` is used to configure the Guard that ships with `msal-angular`. The `authRequest` you provide here will be passed to the login calls invoked by the Guard. If you are writing your own custom Guard instead of using the one provided you'll want to make sure that you pass the request object to `loginRedirect` either directly or by using this config value. For most scenarios, using the provided Guard should be sufficient.
