### ISSUE TITLE
Provide a way to only retrieve cached tokens when calling acquireTokenSilent

### ISSUE THREAD

**Issue by JWess** [AzureAD/microsoft-authentication-library-for-js#3705]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.0

### Description

My app uses Axios to make API calls. I have created and added an interceptor (see snippet below) for all outgoing requests. The interceptor calls `msalApp.acquireTokenSilent()` to get the access token and then adds it to the request via the request's `Authorization` header.

This all works fine, except for cases where I let the app sit for an hour, then perform an action that causes two API calls to happen simultaneously. Because the access token has expired, each API call causes the interceptor (via acquireTokenSilent()) to attempt a token refresh, so two happen simultaneously. When the refreshes finish, the API calls succeed.

Now for my question. Does this library supply any way to only auto-attempt the token refresh if there are no pending attempts to refresh the token?

In the past, when working with Axios but not MSAL, I have used the package [axios-auth-refresh](https://github.com/Flyrell/axios-auth-refresh) to create an Axios interceptor that automatically holds and then retries all API calls that occur while the token refresh is pending.

This leads to a possible feature request. It would be great if `acquireTokenSilent()` could take in a config object which would allow the caller to dictate how far down the chain (steps 1-5 pictured directly below) the method is allowed to proceed.

![image](https://user-images.githubusercontent.com/8697891/120531612-d4634980-c3ac-11eb-8794-531b03e351cf.png)

This would give developers more freedom/flexibility/control to use this function in different scenarios such as this one. Then I could tell my interceptor to do something like: 
`msalApp.acquireTokenSilent(request, { aggressionLevel: AcquisitionMethod.CACHE_ONLY })` 
I could then leverage `axios-auth-refresh` to do a full refresh if an API call returns a `401` like this:

```
  // This function call causes `axios-auth-refresh` to create and attach an interceptor that only gets applied
  // to responses with a `401` status code. If simultaneous calls both return `401`, the call that first
  // returns is the one that triggers the call below, `_getRefreshToken()`, while the other call(s) is forced
  // to hang and wait. Once the refresh call finishes, if successful, all calls will be retried with the
  // newly-returned JWT token credentials applied.
  createAuthRefreshInterceptor(
    axiosInstance,
    (failedRequest: AxiosError) => msalApp.acquireTokenSilent(request)  // No `aggressionLevel` specified, so it will proceed down the chain to the actual refresh call
  );
```

Thoughts on my question and my feature request?

### Relevant Code Snippets

```javascript
Axios.interceptors.request.use(async (config: AxiosRequestConfig) => {
  const accessToken = await _acquireAccessToken(msalInstance);

  if (accessToken) {
    config.headers['Authorization'] = `Bearer ${accessToken}`;
  }

  return config;
});

async function _acquireAccessToken(msalApp: PublicClientApplication) {
  const activeAccount = msalApp.getActiveAccount();
  const accounts = msalApp.getAllAccounts();

  if (!activeAccount && accounts.length === 0) {
    /*
     * User is not signed in. Throw error or wait for user to login.
     * Do not attempt to log a user in outside of the context of MsalProvider
     */
  }

  const request = {
    ...loginRequest,
    account: activeAccount || accounts[0],
  };

  const authResult = await msalApp.acquireTokenSilent(request);

  return authResult.accessToken;
}
```

### Source

External (Customer)

**Comment by tnorling** [comment]
@JWess We have a feature request #2884 open to support multiple concurrent calls to `acquireTokenSilent` which we hope to get to soon. This would make it so that if 2 or more of the same requests are made at the same time only one would go to the network but all would receive the response. Would this help solve your issue?

**Comment by JWess** [comment]
Thank you...I do think that would alleviate my issue. Though I do still think it would be useful to make `acquireTokenSilent()` more flexible/configurable.

**Comment by tnorling** [comment]
Great thanks for confirming. We have had heard this feedback before, I'll mark this as an enhancement for now and someone will get back if and when there's an update. PRs are always welcome if this is something you need prioritized.

**Comment by sameerag** [comment]
Tracked with #4153
