### ISSUE TITLE
Unable to login and acquireTokenSilent for Microsoft Personal Accounts with ARM Scope

### ISSUE THREAD

**Issue by ChaithanyaGK** [AzureAD/microsoft-authentication-library-for-js#3706]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.0

### Description

Login or acquireTokenSilent using Microsoft Personal Account with ARM scope is failing with error "invalid_scope", the same request is working fine with organization accounts.

The login URL is "https://login.microsoftonline.com/common/".

### Error Message

error=invalid_scope&
error_description=The+provided+value+for+the+input+parameter+'scope'+is+not+valid.+The+scope+
'User.Read+Application.Read.All+User.ReadBasic.All+https://management.core.windows.net/user_impersonation+openid+profile+offline_access'+
does+not+exist

### MSAL Configuration

```javascript
{
    auth: {
      clientId: "clientId",
      authority: "https://login.microsoftonline.com/common/",
      redirectUri: window.location.origin,
      postLogoutRedirectUri: window.location.origin,
    },
    cache: {
        cacheLocation: "sessionStorage",
        storeAuthStateInCookie: isIE || isEdge || isFirefox
    }
}
```

### Relevant Code Snippets

```javascript
const loginRequest = {
    scopes: ["User.Read", "Application.Read.All", "User.ReadBasic.All"],
    extraScopesToConsent: ["https://management.core.windows.net/user_impersonation"],
    extraQueryParameters: getQueryParamsDict()
};


this.context.instance.loginRedirect({...loginRequest, prompt: "select_account"})
```

### Reproduction Steps

const loginRequest = {
    scopes: ["User.Read", "Application.Read.All", "User.ReadBasic.All"],
    extraScopesToConsent: ["https://management.core.windows.net/user_impersonation"],
    extraQueryParameters: getQueryParamsDict()
};

this.context.instance.loginRedirect({...loginRequest, prompt: "select_account"})

### Expected Behavior

Able to successfully login or acquireTokenSilent using Microsoft Personal Account with ARM scope

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

Internal (Microsoft)

**Comment by jasonnutter** [comment]
@ChaithanyaGK In order to use ARM scopes with MSA accounts, you need to use `https://login.microsoftonline.com/organizations` instead of `/common`, and then enable MSA passthrough. Please try that and let us know if that works.

**Comment by ChaithanyaGK** [comment]
@jasonnutter Thanks for the reply. Could you please share any documentation around enabling MSA passthrough.

**Comment by jasonnutter** [comment]
Resolved offline using instructions provided above, closing.
