### ISSUE TITLE
@azure/msal-react  how to use it with microservices? 

### ISSUE THREAD

**Issue by murutchan** [AzureAD/microsoft-authentication-library-for-js#3710]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

1.4.10

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

none

### Description

Hello,
we have been trying to resolve the issue for almost 2 weeks now. We have a website that has 5-6 microservices. All of them live separately, and we use msal b2c for authentication. The problem is, when I log out from one microservice, it logs out from all the other services too. Is there a way not to delete the cache or token in the local storage when logging out?

### MSAL Configuration

```javascript
export const msalApp = new UserAgentApplication({
  auth: {
    domain: appDomain,
    clientId: process.env.REACT_APP_AZURE_APP_ID, //B2C Client ID
    authority: authLink + "B2C_1_SignInSignUp",
    validateAuthority: false,
    storeAuthStateInCookie: true,
    redirectUri: appLink,
    postLogoutRedirectUri: appDomain + "logout/" + appLink,
    navigateToLoginRequestUrl: false,
    loadFrameTimeout: 90000,
  },
```

### Relevant Code Snippets

```javascript
//using this to logout when token is about to expire

const logout = ()=>{  
msalApp.logout()
};
```

### Source

External (Customer)

**Comment by pkanher617** [comment]
Unfortunately in v1 we do not provide an API to only clear cache and not navigate to the logout API. This functionality does exist in v2, but we don't have any plans to implement this in v1 today. You can try clearing the cache yourself.

**Comment by murutchan** [comment]
Thank you for the response, we still havent figure it out. We will probably switch to v2.

**Comment by samuelkubai** [comment]
Closing this issue, feel free to re-open the issue if necessary.
