### ISSUE TITLE
MSAL with Windows Virtual Desktop (WVD°

### ISSUE THREAD

**Issue by hhertogh** [AzureAD/microsoft-authentication-library-for-js#3715]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

1.1.3

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

Hello,
We have a VueJS application which is using MSALJS to make use of the Azure AD authentication in a corporate environment (we enforce MFA for our users).
Our application is working perfectly in our offices but recently we began to work with Windows Virtual Desktops.
There we have issues with the login as users are not requested to enter the MFA codes. It's not asked while in the office it's asked and working correctly. When surfing to office.com , logging in, mfa code, authenticated, going back to our custom application, then it's ok, so I'm suspecting something with the claims that is not correctly set for WVD.
Anyone experiencing similar issues ?
Thanks.

### Source

External (Customer)

**Comment by pkanher617** [comment]
@hpsin any ideas here? Probably something to do with configuration for the app?

**Comment by hpsin** [comment]
Seems like a conditional access concern.  Ravi Vennapusa may have ideas?

**Comment by sameerag** [comment]
Will connect Ravi with the customer soon

**Comment by RavennMSFT** [comment]
@hhertogh is this behavior when logging into the WVD web client, or the WVD VMs

**Comment by hhertogh** [comment]
@RavennMSFT we are using the Remote Desktop App to connect to WVD VMs.

**Comment by RavennMSFT** [comment]
Perhaps I misunderstood your use case. Are you saying that VueJS enforces MFA as expected on desktops but when the same app is used within a VM, it does not?

**Comment by hhertogh** [comment]
Yes, from a desktop no issue, from WVD (VM), MSAL is not working properly probably because of conditional access.
I have encountered similar issues when using MSAL on an Outlook add-in. From desktop working, but not from Outlook on WVD...

**Comment by RavennMSFT** [comment]
@sameerag this isnt an RDP issue, but MSAL within a VM. I am not sure why it would behave differently, but pls check.

**Comment by sameerag** [comment]
@hhertogh Is it possible to share fiddler logs for the failure cases? My email is available in my profile.

**Comment by sameerag** [comment]
Responded over email. We need traces for the authentication calls made from MSAL to the AAD in the fiddler log.
