### ISSUE TITLE
Angular app is not being bootstrapped after B2C error

### ISSUE THREAD

**Issue by nicolaszawada** [AzureAD/microsoft-authentication-library-for-js#3722]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.0

### Description

We have an Angular application where all of our routes are protected by the `MsalGuard`. So when a user navigates to our application, it gets redirected automatically to our Azure AD B2C login page. The user logs in and gets redirected to the Angular app. Up to this point there are no issues.

When the user wants to change his password, we send a login request to the forgotten password authority, so the user gets redirected to the Azure AD B2C forgotten password page.
However here is where the problem occurs. When the user **cancels**, it gets redirected back to the Angular application with an error (provided here below), and the Angular application is not being bootstrapped. It freezes on a blank page.

We had did not have this issue with the previous msal-angular version. This problem is occurring after the v2.0.0 upgrade.

### Error Message

```
http://localhost:4200/#error=access_denied&error_description=AADB2C90091: he user has cancelled entering self-asserted information
Correlation ID: ab4715aa-1245-43bd-9a06-546cc7daa047
Timestamp: 2021-06-07 13:56:31Z
&state=....
```

### MSAL Configuration

```javascript
return new PublicClientApplication({
    auth: {
      clientId: 'ec53373e-be8b-49ef-83cc-7d9449433088',
      authority: b2cPolicies.authorities.signUpSignIn.authority,
      redirectUri: '/',
      postLogoutRedirectUri: '/',
      knownAuthorities: [b2cPolicies.authorityDomain]
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE, // set to true for IE 11
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Info,
        piiLoggingEnabled: false
      }
    }
  });
```

### Relevant Code Snippets

```javascript
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { ProfileComponent } from './profile/profile.component';
import { HomeComponent } from './home/home.component';
import { MsalGuard } from '@azure/msal-angular';

const routes: Routes = [
  {
    path: 'profile',
    component: ProfileComponent,
    canActivate: [
      MsalGuard,
    ]
  },
  {
    // Needed for hash routing
    path: 'error',
    component: HomeComponent
  },
  {
    // Needed for hash routing
    path: 'state',
    component: HomeComponent
  },
  {
    // Needed for hash routing
    path: 'code',
    component: HomeComponent
  },
  {
    path: '',
    component: HomeComponent,
	canActivate: [
		MsalGuard
	]
  }
];

const isIframe = window !== window.parent && !window.opener;

@NgModule({
  imports: [RouterModule.forRoot(routes, {
    // Don't perform initial navigation in iframes
    initialNavigation: !isIframe ? 'enabled' : 'disabled'
  })],
  exports: [RouterModule]
})
export class AppRoutingModule { }
```

### Reproduction Steps

1. Start from Angular 11 MSAL Angular v2 B2C Sample
2. Replace the configs
3. Add `canActivate MsalGuard` to the default route & remove `useHash: true` from AppRoutingModule (cfr. Relevant Code Snippets above)
4. Click "Edit profile"
5. Click "Cancel"
6. Angular app is not being bootstrapped

### Expected Behavior

When the user clicks cancel, we want the Angular application to be bootstrapped so we can handle this error on the `msalSubject$`.

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge

### Regression

@azure/msal-angular 1.1.2

### Source

External (Customer)

**Comment by derisen** [comment]
@nicolaszawada **MsalGuard** should not be added to the route that serves as `redirectUri` (here, `path: '/'` for **HomeComponent**). Can you either remove **MsalGuard** from there or use a different `redirectUri`, like `localhost:4200/redirect`? Does this help? (see [also](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md#what-should-i-set-my-redirecturi-to)).

Also, I would recommend using the new [Self-service password reset](https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-password-reset-policy?pivots=b2c-user-flow#self-service-password-reset-recommended), which integrates the password reset flow with the standard sign-up/sign-in flow, eliminating the need to use a separate policy for this (the [current B2C sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular11-b2c-sample#how-to-handle-b2c-user-flows) reflects that)

**Comment by nicolaszawada** [comment]
Hi @derisen thanks for your reply. However there still seems to be an issue with this approach. 
When adding an unprotected 'redirect' route and configuring, the app is being bootstrapped, but then a white screen occurs.

This is also reproducible in the B2C Sample by configuring `'/redirect'` as the `redirectUri` and adding following route to the `AppRoutingModule`
```
 {
    path: 'redirect',
    component: HomeComponent
  },
```

Keep in mind that all the other routes are still `MsalGuard` protected, including our default `'' - HomeComponent` route.
It works when removing the `MsalGuard` on our default route, but this is not acceptable for our customer as the whole application needs to be protected.

**Comment by derisen** [comment]
@nicolaszawada apologies, I did not realize you're not using hash routing. Please use the `MsalRedirectComponent` as component for the `redirect` route in AppRoutingModule. More on this [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/FAQ.md#how-do-i-log-users-in-when-they-hit-the-application).

I was able to reproduce this. Will get back to you once we have more information.

**Comment by derisen** [comment]
@nicolaszawada can you setup a [login-failed route](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/msal-guard.md#login-failed-route) as discussed in the docs? You can then show a component that displays a button to take users back to login page -would that cover your use case?

**Comment by nicolaszawada** [comment]
This works when using a login-failed route which is not guarded, but this doesn't seem to be an elegant solution. 
This means an authenticated user in our application clicks on 'Password Reset', then **cancels** in the password reset flow, gets redirected to the newly introduced _DummyComponent_, where he has to click on another 'Take me back' button. It just seems like an extra useless step.

To eleminate the extra user interaction, we will automatically redirect the user from the DummyComponent back to our authenticated app. This seems _acceptable._

When we use a login-failed route with an `MsalGuard`, it looks like the guard is stuck in an endless loop. This scenario was not an issue in @azure/msal-angular version 1.1.2.
```
...
​ [Thu, 10 Jun 2021 08:27:58 GMT] :  : @azure/msal-angular@2.0.0 : Error - Guard - error while logging in, unable to activate
​ [Thu, 10 Jun 2021 08:27:58 GMT] :  : @azure/msal-browser@2.14.2 : Info - Emitting event: msal:handleRedirectStart
​ [Thu, 10 Jun 2021 08:27:58 GMT] :  : @azure/msal-angular@2.0.0 : Error - Guard - error while logging in, unable to activate
​ [Thu, 10 Jun 2021 08:27:58 GMT] :  : @azure/msal-browser@2.14.2 : Info - Emitting event: msal:handleRedirectStart
​ [Thu, 10 Jun 2021 08:27:58 GMT] :  : @azure/msal-angular@2.0.0 : Error - Guard - error while logging in, unable to activate
​ [Thu, 10 Jun 2021 08:27:58 GMT] :  : @azure/msal-browser@2.14.2 : Info - Emitting event: msal:handleRedirectStart
​ [Thu, 10 Jun 2021 08:27:58 GMT] :  : @azure/msal-angular@2.0.0 : Error - Guard - error while logging in, unable to activate
...
```

**Comment by derisen** [comment]
@jasonnutter @jo-arroyo any insights on this?

**Comment by jasonnutter** [comment]
> This works when using a login-failed route which is not guarded, but this doesn't seem to be an elegant solution.

I don't understand why this isn't an option. I would not expect a page that is intended to be shown to users who can't login to require them to log in.

**Comment by BeejeeDS** [comment]
In this scenario the user is already logged in properly, goes to the profile page (on our webapp) and decides to change his password. Because the passwords are managed by Azure B2C we redirect them to the correct flow. 

But here comes the tricky part, on this page the user has the possibility to cancel, which should result in him being redirected to the original page again (on our webapp). The user only wanted to change his password, so at this point he should **still be logged in**. What you guys consider as the solution results in an extra page that is not protected to serve as an extra redirect layer.

Although this fixes the problem, you can’t deny that this solution is only half backed. Especially considering that this wasn’t even an issue in the previous versions.
