### ISSUE TITLE
How do I get Bearer (Access) Token in v2 format using @azure/msal-react?

### ISSUE THREAD

**Issue by a2441918** [AzureAD/microsoft-authentication-library-for-js#3723]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.0

### Description

I created a new app service and set accessTokenAcceptedVersion to 2 in manifest.json as I am looking for a v2 token similar to [here][1]. However the accessToken generated by Microsoft always has an iss value of sts.windows.net when decoded. I would like it to be login.microsoftonline.com. Please advice.

This is my implementation:

[![enter image description here][2]][2]

This is my token when decoded:

[![enter image description here][3]][3]

Please advice.

  [1]: https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens#sample-tokens
  [2]: https://i.stack.imgur.com/PAN8W.png
  [3]: https://i.stack.imgur.com/tj5Tk.png

### Relevant Code Snippets

```javascript
let token;
msalInstance.acquireTokenSilent({
      ...loginRequest
    }).then((accessTokenResponse) => {
       // Acquire token silent success
       token = accessTokenResponse.accessToken;
     })
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by derisen** [comment]
@a2441918 the access token version that your app gets is dictated by the resource server that the token is intended for. Here it looks like this access token is meant for calling MS Graph API, in that case there isn't much you can do, its up to the Graph API. If you were acquiring a token to call your own web API, you could set this the same way (Manifest> `accessTokenAcceptedVersion`) in your web API's app registration (not your client app's).

**Comment by a2441918** [comment]
So do I need two app registrations, one for the API and one for the UI? The aud given by the token belongs to the Graph API and I need to get my API's aud in the token. My goal is to send the accessToken to the backend, decode the JWT in the backend and verify the signature, validate the OID against my database to verify user authentication.

This is my implementation of my configuration. 

![image](https://user-images.githubusercontent.com/4927454/121108240-687f4780-c7d7-11eb-9a2e-c00f5de301cd.png)

![image](https://user-images.githubusercontent.com/4927454/121108361-9e243080-c7d7-11eb-8f67-77b734ec67bd.png)

**Comment by derisen** [comment]
@a2441918 every access token is meant for a resource, represented in the `aud` claim. To get a token for your backend API, you need to use the scope(s) that you expose in your access token request. [Check out the docs](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/resources-and-scopes.md) for more on this.

And yes, it is best practice to create separate app registrations for your client and service apps. [Check out this tutorial](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/tree/main/3-Authorization-II/1-call-api), which covers the scenario you describe here.

**Comment by a2441918** [comment]
Thanks @derisen it worked

**Comment by derisen** [comment]
@a2441918 cheers! Closing this. Let us know if you need further help.
