### ISSUE TITLE
Logout redirect does not work if permissions for app are not granted

### ISSUE THREAD

**Issue by EPilz** [AzureAD/microsoft-authentication-library-for-js#3725]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.0

### Description

If I refuse the App authorization when forwarding to the login, the redirect no longer works during the subsequent logout. In every other case it works.

Deny the app permission (Cancel):

![grafik](https://user-images.githubusercontent.com/6795717/121135386-bbd3b300-c834-11eb-98a2-73c3ddaa9ea1.png)

Redirect don't work (Stop on this site):

![grafik](https://user-images.githubusercontent.com/6795717/121135577-efaed880-c834-11eb-9370-4c8b50b1cdc2.png)

### MSAL Configuration

```javascript
auth: {
  authority: authority,
  clientId: clientId,
  navigateToLoginRequestUrl: true,
  postLogoutRedirectUri: defaultUrl
},
cache: {
  cacheLocation: BrowserCacheLocation.SessionStorage,
  storeAuthStateInCookie: isIE, 
}
```

### Relevant Code Snippets

```javascript
if (this.loginFailure) {
  sessionStorage.clear();
  this.msalService.logoutRedirect({postLogoutRedirectUri: environment.redirecturl});
}
```

### Reproduction Steps

1. Login
2. Deny the app permission
3. Logout (redirect to login page not work)

### Expected Behavior

Redirect to login page work

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@EPilz This is by design, as we only allow an application to complete sign out for a user if they have consented to the app, in order to prevent applications from signing out a user without their consent.
