### ISSUE TITLE
IE11/Edge do not work with MSAL

### ISSUE THREAD

**Issue by vladkosarev** [AzureAD/microsoft-authentication-library-for-js#373]
I am aware of -
https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/Known-issues-on-Edge#issues

Does that mean that MSAL (just like ADAL) does not support IE/Edge?

According to this doc -
https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Using-msal.js-with-Internet-Explorer

we just need to make sure to enable polyfills and everything will work.
I was not able to get IE to work until I added login.microsoftonline.com to trusted sites. Obviously that won't work in a b2c scenario.

What browsers are supported by MSAL? We've sunk a lot of time into b2c and this would obviously be a showstopper.

Thanks.

**Comment by nehaagrawal** [comment]
@vladkosarev  We are working on a fix to support to IE and Edge and it would be release in one of our future releases. Unfortunately it doesn't work currently.

**Comment by vladkosarev** [comment]
@nehaagrawal any approximate ETA on the fix? 

Thanks.

**Comment by nehaagrawal** [comment]
duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/347

**Comment by nehaagrawal** [comment]
@vladkosarev  This is fixed and released in msal 0.2.2. Please check the release notes for more details.
