### ISSUE TITLE
angular b2c sample - no access token 'known error'

### ISSUE THREAD

**Issue by jacksonhart** [AzureAD/microsoft-authentication-library-for-js#3730]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.0

### Description

I am using an essentially unchanged angular11-b2c-sample app.

I have only changed:

1. the clientID in app.module.ts to point at a new (SPA) b2c app registration created using https://docs.microsoft.com/en-au/azure/active-directory-b2c/tutorial-register-spa

2. the b2c config in b2c-config.ts to point at a standard signup-signin user flow created using https://docs.microsoft.com/en-au/azure/active-directory-b2c/tutorial-create-user-flows?pivots=b2c-user-flow.

When running the app, login is successful.

When attempting to navigate to the guarded 'Web API' page, the below error is encountered.
No access token is present on the oauth2/v2.0/token call.
This causes an infinite loop.
It doesn't get to the stage of actually calling our api (error still occurs if leaving the sample apiConfig).
The app is running locally (and hence using a 'http://localhost:4200' reply URI, have also tried 'http://127.0.0.1:4200').

This was just supposed to be a test before upgrading our app to msal v2.

The error message suggests this is a known issue but I have not found anything useful.

### Error Message

Error - Interceptor - acquireTokenSilent resolved with null access token.
Known issue with B2C tenants, invoking interaction to resolve.

### Msal Logs

{eventType: "msal:loginSuccess", interactionType: "redirect", payload: {…}, error: null, timestamp: 1623213333923}
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - setActiveAccount: Active account set
​ {eventType: "msal:loginSuccess", interactionType: "redirect", payload: {…}, error: null, timestamp: 1623213333923}
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - setActiveAccount: Active account set
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-angular@2.0.0 : Verbose - BroadcastService - msal:loginSuccess results in setting inProgress to none
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getAllAccounts called
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getAllAccounts called
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Account matching localAccountId found, returning
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - handleRedirectResponse returned result, login success
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Info - Emitting event: msal:handleRedirectEnd
app.module.ts:23 [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Emitting event to callback 5df802cf-4c14-4167-b9e5-ba0939ed9c62: msal:handleRedirectEnd
app.module.ts:23 [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-angular@2.0.0 : Verbose - BroadcastService - msal:handleRedirectEnd results in setting inProgress to none
app.module.ts:23 [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getAllAccounts called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getAllAccounts called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Account matching localAccountId found, returning
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-angular@2.0.0 : Verbose - Guard - canActivate
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-angular@2.0.0 : Verbose - MSAL Guard activated
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Info - Emitting event: msal:handleRedirectStart
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Emitting event to callback 5df802cf-4c14-4167-b9e5-ba0939ed9c62: msal:handleRedirectStart
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-angular@2.0.0 : Verbose - BroadcastService - msal:handleRedirectStart results in setting inProgress to handleRedirect
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - handleRedirectPromise called
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getAllAccounts called
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - handleRedirectPromise has been called previously, returning the result from the first call
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getAllAccounts called
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-angular@2.0.0 : Verbose - Guard - at least 1 account exists, can activate or load
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-angular@2.0.0 : Verbose - MSAL Interceptor activated
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-angular@2.0.0 : Verbose - Interceptor - getting scopes for endpoint
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getAllAccounts called
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Account matching localAccountId found, returning
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-angular@2.0.0 : Verbose - Interceptor - active account selected
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getAllAccounts called
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Account matching localAccountId found, returning
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-angular@2.0.0 : Info - Interceptor - 1 scopes found for endpoint
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - preflightBrowserEnvironmentCheck started
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - acquireTokenSilent called
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Initializing BaseAuthRequest
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Authentication Scheme wasn't explicitly set in request, defaulting to "Bearer" request
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Info - Emitting event: msal:acquireTokenStart
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Emitting event to callback 5df802cf-4c14-4167-b9e5-ba0939ed9c62: msal:acquireTokenStart
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - initializeServerTelemetryManager called
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - createSilentFlowClient called
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getClientConfiguration called
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getDiscoveredAuthority called
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Creating discovered authority with request authority
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Info - Emitting event: msal:acquireTokenFromNetworkStart
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Emitting event to callback 5df802cf-4c14-4167-b9e5-ba0939ed9c62: msal:acquireTokenFromNetworkStart
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Initializing BaseAuthRequest
​ [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Authentication Scheme set to "Bearer" as configured in Auth request
app.module.ts:23 [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - initializeServerTelemetryManager called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - createRefreshTokenClient called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getClientConfiguration called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getDiscoveredAuthority called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:39 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Creating discovered authority with request authority
app.module.ts:23 [Wed, 09 Jun 2021 04:35:40 GMT] :  : @azure/msal-browser@2.14.2 : Info - Emitting event: msal:acquireTokenSuccess
app.module.ts:23 [Wed, 09 Jun 2021 04:35:40 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Emitting event to callback 5df802cf-4c14-4167-b9e5-ba0939ed9c62: msal:acquireTokenSuccess
​ [Wed, 09 Jun 2021 04:35:47 GMT] :  : @azure/msal-angular@2.0.0 : Error - Interceptor - acquireTokenSilent resolved with null access token. Known issue with B2C tenants, invoking interaction to resolve.
​ [Wed, 09 Jun 2021 04:35:47 GMT] :  : @azure/msal-angular@2.0.0 : Verbose - Interceptor - error acquiring token silently, acquiring by redirect
​ [Wed, 09 Jun 2021 04:35:47 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - preflightBrowserEnvironmentCheck started
​ [Wed, 09 Jun 2021 04:35:47 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - acquireTokenRedirect called
​ [Wed, 09 Jun 2021 04:35:47 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getAllAccounts called
​ [Wed, 09 Jun 2021 04:35:47 GMT] :  : @azure/msal-browser@2.14.2 : Info - Emitting event: msal:acquireTokenStart
​ [Wed, 09 Jun 2021 04:35:47 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Emitting event to callback 5df802cf-4c14-4167-b9e5-ba0939ed9c62: msal:acquireTokenStart
​ [Wed, 09 Jun 2021 04:35:47 GMT] :  : @azure/msal-angular@2.0.0 : Verbose - BroadcastService - msal:acquireTokenStart results in setting inProgress to acquireToken
​ [Wed, 09 Jun 2021 04:35:47 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - preflightInteractiveRequest called, validating app environment
​ [Wed, 09 Jun 2021 04:35:47 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - initializeAuthorizationRequest called
​ [Wed, 09 Jun 2021 04:35:47 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getRedirectUri called
​ [Wed, 09 Jun 2021 04:35:47 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Initializing BaseAuthRequest
​ [Wed, 09 Jun 2021 04:35:47 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Authentication Scheme wasn't explicitly set in request, defaulting to "Bearer" request
​ [Wed, 09 Jun 2021 04:35:47 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Setting validated request account
app.module.ts:23 [Wed, 09 Jun 2021 04:35:47 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - initializeServerTelemetryManager called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:47 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - createAuthCodeClient called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:47 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getClientConfiguration called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:47 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getDiscoveredAuthority called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:47 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Creating discovered authority with request authority
app.module.ts:23 [Wed, 09 Jun 2021 04:35:47 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getRedirectStartPage called
Navigated to http://127.0.0.1:4200/
app.module.ts:23 [Wed, 09 Jun 2021 04:35:49 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Event callback registered with id: e6352848-b6f7-44dc-ab41-71360c555e71
app.module.ts:23 [Wed, 09 Jun 2021 04:35:49 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getAllAccounts called
core.js:27701 Angular is running in development mode. Call enableProdMode() to enable production mode.
app.module.ts:23 [Wed, 09 Jun 2021 04:35:49 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getAllAccounts called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:49 GMT] :  : @azure/msal-angular@2.0.0 : Verbose - MsalRedirectComponent activated
app.module.ts:23 [Wed, 09 Jun 2021 04:35:49 GMT] :  : @azure/msal-browser@2.14.2 : Info - Emitting event: msal:handleRedirectStart
app.module.ts:23 [Wed, 09 Jun 2021 04:35:49 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Emitting event to callback e6352848-b6f7-44dc-ab41-71360c555e71: msal:handleRedirectStart
app.module.ts:23 [Wed, 09 Jun 2021 04:35:49 GMT] :  : @azure/msal-angular@2.0.0 : Verbose - BroadcastService - msal:handleRedirectStart results in setting inProgress to handleRedirect
app.module.ts:23 [Wed, 09 Jun 2021 04:35:49 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - handleRedirectPromise called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:49 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getAllAccounts called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:49 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - handleRedirectPromise has been called for the first time, storing the promise
app.module.ts:23 [Wed, 09 Jun 2021 04:35:49 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getRedirectResponseHash called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:49 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Hash contains known properties, returning response hash
app.module.ts:23 [Wed, 09 Jun 2021 04:35:49 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - validateAndExtractStateFromHash called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:49 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Returning state from hash
app.module.ts:23 [Wed, 09 Jun 2021 04:35:49 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - State extracted from hash
app.module.ts:23 [Wed, 09 Jun 2021 04:35:49 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Current page is loginRequestUrl, handling hash
app.module.ts:23 [Wed, 09 Jun 2021 04:35:49 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - handleHash called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:49 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - initializeServerTelemetryManager called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:49 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - createAuthCodeClient called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:49 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getClientConfiguration called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:49 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getDiscoveredAuthority called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:49 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Creating discovered authority with request authority
core.js:27701 Angular is running in development mode. Call enableProdMode() to enable production mode.
app.module.ts:23 [Wed, 09 Jun 2021 04:35:49 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getAllAccounts called
client:52 [WDS] Live Reloading enabled.
app.module.ts:23 [Wed, 09 Jun 2021 04:35:49 GMT] :  : @azure/msal-common@4.3.0 : Info - in acquireToken call
app.module.ts:23 [Wed, 09 Jun 2021 04:35:50 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getAllAccounts called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:50 GMT] :  : @azure/msal-browser@2.14.2 : Info - Emitting event: msal:acquireTokenSuccess
app.module.ts:23 [Wed, 09 Jun 2021 04:35:50 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Emitting event to callback e6352848-b6f7-44dc-ab41-71360c555e71: msal:acquireTokenSuccess
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-angular@2.0.0 : Verbose - BroadcastService - msal:acquireTokenSuccess results in setting inProgress to none
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getAllAccounts called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getActiveAccount: No active account
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getAllAccounts called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getAllAccounts called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - setActiveAccount: Active account set
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - handleRedirectResponse returned result, acquire token success
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Info - Emitting event: msal:handleRedirectEnd
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Emitting event to callback e6352848-b6f7-44dc-ab41-71360c555e71: msal:handleRedirectEnd
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-angular@2.0.0 : Verbose - BroadcastService - msal:handleRedirectEnd results in setting inProgress to none
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getAllAccounts called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getAllAccounts called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Account matching localAccountId found, returning
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-angular@2.0.0 : Verbose - Guard - canActivate
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-angular@2.0.0 : Verbose - MSAL Guard activated
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Info - Emitting event: msal:handleRedirectStart
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Emitting event to callback e6352848-b6f7-44dc-ab41-71360c555e71: msal:handleRedirectStart
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-angular@2.0.0 : Verbose - BroadcastService - msal:handleRedirectStart results in setting inProgress to handleRedirect
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - handleRedirectPromise called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getAllAccounts called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - handleRedirectPromise has been called previously, returning the result from the first call
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getAllAccounts called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-angular@2.0.0 : Verbose - Guard - at least 1 account exists, can activate or load
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-angular@2.0.0 : Verbose - MSAL Interceptor activated
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-angular@2.0.0 : Verbose - Interceptor - getting scopes for endpoint
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getAllAccounts called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Account matching localAccountId found, returning
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-angular@2.0.0 : Verbose - Interceptor - active account selected
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getAllAccounts called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Account matching localAccountId found, returning
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-angular@2.0.0 : Info - Interceptor - 1 scopes found for endpoint
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - preflightBrowserEnvironmentCheck started
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - acquireTokenSilent called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Initializing BaseAuthRequest
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Authentication Scheme wasn't explicitly set in request, defaulting to "Bearer" request
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Info - Emitting event: msal:acquireTokenStart
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Emitting event to callback e6352848-b6f7-44dc-ab41-71360c555e71: msal:acquireTokenStart
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - initializeServerTelemetryManager called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - createSilentFlowClient called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getClientConfiguration called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getDiscoveredAuthority called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Creating discovered authority with request authority
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Info - Emitting event: msal:acquireTokenFromNetworkStart
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Emitting event to callback e6352848-b6f7-44dc-ab41-71360c555e71: msal:acquireTokenFromNetworkStart
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Initializing BaseAuthRequest
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Authentication Scheme set to "Bearer" as configured in Auth request
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - initializeServerTelemetryManager called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - createRefreshTokenClient called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getClientConfiguration called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - getDiscoveredAuthority called
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Creating discovered authority with request authority
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Info - Emitting event: msal:acquireTokenSuccess
app.module.ts:23 [Wed, 09 Jun 2021 04:35:52 GMT] :  : @azure/msal-browser@2.14.2 : Verbose - Emitting event to callback e6352848-b6f7-44dc-ab41-71360c555e71: msal:acquireTokenSuccess

### MSAL Configuration

```javascript
// apart from the clientId in app.module and the below, identical to sample.

export const b2cPolicies = {
    names: {
        signUpSignIn: "B2C_1_signup-signin", 
    },
    authorities: {
        signUpSignIn: {
            authority: "https://xx.b2clogin.com/xx.onmicrosoft.com/B2C_1_signup-signin",
        },
    },
    authorityDomain: "xx.b2clogin.com"
}

// error remains if below left as the sample code
export const apiConfig: { scopes: string[]; uri: string } = {
    scopes: ['https://xx.onmicrosoft.com/xxWebApiDev/Access'],
    uri: 'https://xxwebapidev.azurewebsites.net/api/v1'
};
```

### Relevant Code Snippets

```javascript
see above and the b2c angular sample app.
```

### Reproduction Steps

run sample app pointing to a new app registration and a default signup-signin flow.

### Expected Behavior

Given just following guides and using sample code, expected to work out of the box with no errors.

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome

### Regression

n/a

### Source

External (Customer)

**Comment by derisen** [comment]
@jacksonhart can you confirm that you've granted admin consent to scope `https://xx.onmicrosoft.com/xxWebApiDev/Access` in your SPA's app registration, and if not, can you do that and give it a try again?

**Comment by jacksonhart** [comment]
@derisen thanks for the reply.

I am not familiar with these Azure settings but I found the following in the App Registration > 'Expose an API' screen.
Does it appear correct?
![image](https://user-images.githubusercontent.com/17895642/121801173-8b42ad80-cc68-11eb-9b47-3c07289908d5.png)


However note that if I leave the apiConfig the same as the sample (as below) I still get the issue.
This rules out an issue with our webApi scope right?
No call is made to the below URI - the error occurs beforehand.

Note the inital msalSubject$ payload recieved on a successful login on the first page has an empty accessToken.
But its not until you try to navigate to the 'Web API' page that the missing token is deemed an error (I assume its the guard that checks for it?)

`export const apiConfig: { scopes: string[]; uri: string } = {
    scopes: ['https://fabrikamb2c.onmicrosoft.com/helloapi/demo.read'],
    uri: 'https://fabrikamb2chello.azurewebsites.net/hello'
};`

**Comment by derisen** [comment]
@jacksonhart you still need to provide admin consent though. Go to App registrations > your app > API Permissions blade, you'll find the **Grant admin consent for {your tenant}** button there. Can you do that and try again? 

![ss](https://user-images.githubusercontent.com/13197548/121913851-9805e680-cce6-11eb-9652-3b0dcd04b342.png)

**Comment by jacksonhart** [comment]
beautiful that was it thanks.
