### ISSUE TITLE
Ionic framework Msal React not working in Native devices (iOS and Android) [works perfectly in Web]

### ISSUE THREAD

**Issue by dipankarmedhi91** [AzureAD/microsoft-authentication-library-for-js#3733]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.0

### Description

Msal React in Ionic framework not working in Native devices (iOS and Android) [works perfectly in Web]
In iOS the accounts array returned by `useMsal` is always empty
`import { useMsal } from '@azure/msal-react';`

In Android the `instance.loginRedirect` function fails with below error:
BrowserAuthError: pkce_not_created: The PKCE code challenge and verifier could not be generated.

### Error Message

**iOS:**
No Error stack, we just don't get any account within the `accounts` array returned by `useMsal`

**Error Stack in Android:**
`Uncaught (in promise) BrowserAuthError: pkce_not_created: The PKCE code challenge and verifier could not be generated. Detail:TypeError: Cannot read property 'digest' of undefined
    at BrowserAuthError.AuthError [as constructor] (com.mlf.app://localhost/main.bundle.js:765:24)
    at new BrowserAuthError (com.mlf.app://localhost/main.bundle.js:7476:28)
    at Function../node_modules/@azure/msal-browser/dist/index.es.js.BrowserAuthError.createPkceNotGeneratedError (com.mlf.app://localhost/main.bundle.js:7486:16)
    at PkceGenerator.<anonymous> (com.mlf.app://localhost/main.bundle.js:7762:48)
    at step (com.mlf.app://localhost/main.bundle.js:312:23)
    at Object.throw (com.mlf.app://localhost/main.bundle.js:293:53)
    at rejected (com.mlf.app://localhost/main.bundle.js:284:65)`

### MSAL Configuration

```javascript
{
    clientId: `NOT_ADDING_REAL_ID`, 
    authority: `NOT_ADDING_REAL_AUTH`,
    knownAuthorities: ['NOT_ADDING_REAL_TENANT'],
    redirectUri: 'NOT_ADDING_REAL_URL',
    postLogoutRedirectUri: '/',
    navigateToLoginRequestUrl: false,
scopes:['NOT_ADDING_REAL_SCOPE']
  }
```

### Relevant Code Snippets

```javascript
const { instance, accounts } = useMsal();
  const account: AccountInfo | null = useAccount(accounts[0] || {});
  const request: SilentRequest = {
    scopes: protectedResources.apiHello.scopes,
    account: account || undefined,
  };

  useEffect(() => {
    if (account) {
      instance
        .acquireTokenSilent(request)
        .then((tokenResponse: AuthenticationResult) => {
          if (tokenResponse) setAccessToken(tokenResponse);
        })
        .catch((error) => {
          if (error instanceof InteractionRequiredAuthError) {
            return instance.acquireTokenRedirect(request);
          }
        });
    }
  }, [account]);
```

### Reproduction Steps

1. Configure msal react in ionic app
2. Run the app in iOS or Android

### Expected Behavior

Expect msal to work correctly in Native devices i.e. similar to Web

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Other

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@dipankarmedhi91 

> BrowserAuthError: pkce_not_created: The PKCE code challenge and verifier could not be generated.

This error happens when the browser doesn't have access to the crypto APIs, which are needed by MSAL. Normally, this is not an issue if your app is served on https (which is also required for the redirect uris). If you are running in an environment where they do not exist, you will need to provide a `window.crypto` polyfill, such as MSR crypto: https://github.com/microsoft/MSR-JavaScript-Crypto

> No Error stack, we just don't get any account within the accounts array returned by useMsal

This is potentially a caching issue. Have you tried debugging MSAL for this error? Are you able to login?

Note, unfortunately Ionic is not an environment we fully support, so we cannot guarantee MSAL.js will work fully with Ionic.

**Comment by dipankarmedhi91** [comment]
@jasonnutter Thanks for the reply
Yes we have tried debugging MSAL, the accounts array remains empty even after we get successfully redirected from AD B2C after correct Login.

Also just to understand on the Note above;
Does that mean that MSAL libraries will not work with Ionic currently ?
Or is there any existing limited support for it ?

**Comment by jasonnutter** [comment]
> ionic iOS : Yes we have tried debugging MSAL, the accounts array remains empty even after we get successfully redirected from AD B2C after correct Login.

You do not appear to set a cacheStorage option, which means MSAL will default to `sessionStorage`. Is there anything in sessionStorage? Is sessionStorage even available?

> Also just to understand on the Note above;
> Does that mean that MSAL libraries will not work with Ionic currently ?
> Or is there any existing limited support for it ?

We do not have documentation or samples for MSAL with Ionic, nor do we do any testing or have considerations for Ionic in the library, and are unlikely to prioritize Ionic specific features or fixes.

**Comment by dipankarmedhi91** [comment]
@jasonnutter 
As we didn't see cacheStorage option, we tried updating the **cache : cacheLocation** value to both the applicable values on that configuration i.e. sessionStorage & localStorage
```
cache: {
        cacheLocation: "sessionStorage",
        storeAuthStateInCookie: false,
        secureCookies: false
    },
```
But had no luck, The accounts array from `useMsal` still returns empty Array

What we can see in Native devices is;
The storage has some values related to Ad B2C before being migrated to Custom policy:
![2021-06-10](https://user-images.githubusercontent.com/10825788/121570639-0b121300-c9f0-11eb-81bc-2af5c6a87c44.png)

But after we migrate back to the App after successfully Logging In the values in storage gets removed

**Comment by jasonnutter** [comment]
@dipankarmedhi91 There are temporary values in sessionStorage that are set by MSAL when the request starts and are deleted when the rquest is completed. From the screenshot, what you see in sessionStorage are those temporary values, so those being deleted in expected. Have you tried localStorage as the `cacheLocation`?

**Comment by dipankarmedhi91** [comment]
yes we did try out localStorage, it had the same Issues
I think cacheLocation only supports those 2 values

**Comment by dipankarmedhi91** [comment]
There is one more observation, the token url (`oauth2/v2.0/token`) is not getting called from the simulator, 

**IOS Simulator:**
![Screenshot 2021-06-11 at 7 57 52 PM](https://user-images.githubusercontent.com/10825788/121705084-54bb3600-caa2-11eb-9740-695848f4cf35.png)

**Web:**
![Screenshot 2021-06-11 at 8 00 08 PM](https://user-images.githubusercontent.com/10825788/121705231-6f8daa80-caa2-11eb-9f70-097c818414f0.png)

The response from the token gets stored in LocalStorage 
& the keys available in LocalStorage are getting used to collect more information like User and Account Details. 

Are there any OS specific checks over this token call? or Client has to call it explicitly to have more information over MSAL Instance.

**Comment by nikhil1746** [comment]
@jasonnutter I tried one more approach to verify if the data missing in localStorage is the reason behind this issue. I tried explicitly feeding the LocalStorage data picked from web chrome browser and with this Im able to get the account info and token API also getting called.
It's not working perfectly but the logic which requires data in localStorage is working correctly with this.

**Comment by jasonnutter** [comment]
@dipankarmedhi91 

> Are there any OS specific checks over this token call? or Client has to call it explicitly to have more information over MSAL Instance.

No, there are no OS specific checks. After MSAL receives an auth code, it will be immediately traded for tokens. Did you try debugging MSAL to see what is happening?

**Comment by jasonnutter** [comment]
The main question I am interested in currently is what happens when MSAL writes data to localStorage in Ionic? Does the data persist, or is it erased? This will likely require debugging MSAL itself.

**Comment by jasonnutter** [comment]
This has been solved offline, issue was a mismatch in the origin that initialized the request and the redirect uri.
