### ISSUE TITLE
Access token does not get picked up from cache when using clientId as scope

### ISSUE THREAD

**Issue by jakobgn** [AzureAD/microsoft-authentication-library-for-js#3737]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

Not Applicable

### Wrapper Library Version

2

### Description

Using MSAL 2.x with Angular (no wrapper lib), B2C and a first party API that validates access tokens,  MSAL fetches a new access token on each request instead of picking it up from cache. We are using the B2C clientId as the only scope. 
The issue seems to be in the  `ResponseHandler.prototype.generateCacheRecord` where the line

`var responseScopes = serverTokenResponse.scope ? ScopeSet.fromString(serverTokenResponse.scope) : new ScopeSet(requestScopes || []);`
returns` "/"` instead of using the `clientId `scope.
Since the target is just `"/"` hereafter, the tokens are saved in cache but never picked up due to inequality between `"/"` and our `clientId `when reading from cache. 

We will try adding a default scope and use that as a work around, but would like to let you guys know about the issue

### MSAL Configuration

```javascript
const authority = `https://${b2cSettings.tenant}.b2clogin.com/${b2cSettings.domain}/${b2cSettings.signInPolicy}`;
  return new PublicClientApplication({
    auth: {
      clientId: b2cSettings.clientId,
      redirectUri: `${window.location.origin}`,
      authority,
      knownAuthorities: [`${b2cSettings.tenant}.b2clogin.com`]
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage
    }
  });
```

### Relevant Code Snippets

```javascript
function MSALInterceptorConfigFactory(
  appConfig: RuntimeConfigService
): MsalInterceptorConfig {
  const b2cSettings = appConfig.getAzureB2CTenantSettings();
  const protectedResourceMap = new Map<string, Array<string>>();
  protectedResourceMap.set(appConfig.getApiSettings().xApi, [
    b2cSettings.clientId
  ]);
  protectedResourceMap.set(appConfig.getApiSettings().engageCompanyApi, [
    b2cSettings.clientId
  ]);
  return {
    interactionType: InteractionType.Redirect,
    authRequest: {
      scopes: [b2cSettings.clientId]
    },
    protectedResourceMap
  };
}
```

### Reproduction Steps

1. Setup with B2C, angular and a protected API and configure as described
2. Call API several times, getting a token using acquireTokenSilent with client as only scope before each request (i.e. using interceptor)
3. Notice that access token is not cached as expected from docs - a new token is fetched each time using refresh tokens.

### Expected Behavior

Access token is cached after first API request

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by jakobgn** [comment]
Update: using user_impersonation scope does not fix this as target from server token response is still "/"

**Comment by tnorling** [comment]
@jakobgn This is a known issue being tracked in #2451. The B2C service team is aware and is working on a fix. In the meantime the mitigation is to create a custom scope on your app registration and use that instead. Closing as duplicate but feel free to track the linked issue for resolution. Thanks!
