### ISSUE TITLE
Program way to log off(clear authentication data)

### ISSUE THREAD

**Issue by todortestnow** [AzureAD/microsoft-authentication-library-for-js#3738]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

Not Applicable

### Wrapper Library Version

NA

### Description

Is there a program way to sign out a user without redirecting to MS log out page? 

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@todortestnow Yes, see here: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md#skipping-the-server-sign-out

**Comment by todortestnow** [comment]
I replaced:
 await msalInstance.logoutRedirect({
    account: currentAccount,
    postLogoutRedirectUri: "https://contoso.com/loggedOut"
});

with:
msalInstance.logoutRedirect({
    onRedirectNavigate: (url) => {
        // Return false if you would like to stop navigation after local logout
        return false;
    }
});
but now after the log off finished in:
msalInstance.handleRedirectPromise().then(tokenResponse => {})
tokenResponse is not null which in our case trigger the whole login process again. Am I missing something or it is standard behaviour
