### ISSUE TITLE
Validating Expiration Time of JWT's

### ISSUE THREAD

**Issue by JJHakiLe** [AzureAD/microsoft-authentication-library-for-js#3744]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.11.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

This is more of a general question for validating json web tokens, but is there an public API or endpoint available from Azure Ad B2C that can be used to get a UNIX timestamp to compare against the json web tokens expiration and issued timestamp claims?

### Source

External (Customer)

**Comment by samuelkubai** [comment]
Hi @JJHakiLe, to the best of our knowledge we don't have such a public API or endpoint from Azure AD B2C to provide timestamps or validate JWT expiration time.

**Comment by JJHakiLe** [comment]
Hi @samuelkubai Thank you for your clear reply. That's unfortunate to hear but understandable. Thanks for your time
