### ISSUE TITLE
how to use loginRedirect with msal 2.0

### ISSUE THREAD

**Issue by graphicsxp** [AzureAD/microsoft-authentication-library-for-js#3749]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0

### Description

My application was working just fine with msal-angular 1.1 but we have to migrate to the latest version and I need help to do the login redirect when user is not logged in.

Before my app is loaded, I take a number of steps inside an initialization function passed to APP_INITIALIZER 
` { provide: APP_INITIALIZER, useFactory: initApp, multi: true, deps: [AppLoadService] },`

This is the `initApp` function : 
```

export const initApp = (appLoadService: AppLoadService) =>
    () =>
        appLoadService.isUserLoggedIn().then(
            // do some more initialization stuff here
                ));
```

As you can see, the first promise is to check whether the user is logged in or not. This is how it used to be done in 1.1 

```
public isUserLoggedIn(): Promise<any> {
        return new Promise((resolve, reject) => {
            this._authService.isUserLoggedIn().then(loggedIn => {
                if (!loggedIn) {
                    this._authService.msalService.loginRedirect();
                    reject('User is not signed in. Redirecting to login page.');
                } else {                  
                    resolve();
                }
            });
        });
    }
```

the `isUserLoggedIn ` fuction was the following :  

```
isUserLoggedIn(): Promise<boolean> {
    return this.msalService.acquireTokenSilent({ scopes: [environment.scopes.microsoftGraphApi.profile] })
      .then(() => true)
      .catch(() => false);
  }
```

However this code needs to be changed for the new version of msal-angular. This is what I have so far : 

```
 public isUserLoggedIn(): Promise<any> {

        return new Promise((resolve, reject) => {

            this._authService.msalBroadcastService.inProgress$
                .pipe(
                    filter((status: InteractionStatus) => status === InteractionStatus.None),
                )
                .subscribe(() => {
                    this._authService.msalService.loginRedirect();
                    reject('User is not signed in. Redirecting to login page.');
                });
        });
```

At first I tried to call loginRedirect() but I was getting this error : 
`interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API`
So I followed the[ guidance from documentation](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/errors.md#interaction_in_progress) to wrap this call inside an observable. 

However now it is never called so I'm not sure what to do. Could you help me to get loginRedirect to work in the context of my application ? 

### MSAL Configuration

```javascript
export function MSALInstanceFactory(): IPublicClientApplication {
    return new PublicClientApplication({
        auth: {
            clientId: environment.aadClientId,
            authority: `https://login.microsoftonline.com/${environment.aadTenantId}`,
            redirectUri:environment.redirectUrl,
            postLogoutRedirectUri: '/'
        },
        cache: {
            cacheLocation: BrowserCacheLocation.LocalStorage,
            storeAuthStateInCookie: isIE, // set to true for IE 11
        },
        system: {
            loggerOptions: {
                loggerCallback,
                logLevel: LogLevel.Info,
                piiLoggingEnabled: false
            }
        }
    });
}

export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
    const protectedResourceMap = new Map<string, Array<string>>();
    // protectedResourceMap.set('https://graph.microsoft.com/v1.0/me', ['user.read']); // Prod environment. Uncomment to use.
    protectedResourceMap.set('https://graph.microsoft-ppe.com/v1.0/me', ['user.read']);

    return {
        interactionType: InteractionType.Redirect,
        protectedResourceMap
    };
}

export function MSALGuardConfigFactory(): MsalGuardConfiguration {
    return {
        interactionType: InteractionType.Redirect,
        authRequest: {
            scopes: ['user.read']
        }
    };
}
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by samuelkubai** [comment]
@graphicsxp have you followed the documentation [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/redirects.md) on redirects in msal-angular v2.0?

**Comment by graphicsxp** [comment]
@samuelkubai Yes I have. The documentation recommends to use a handleRedirectObservable component, which is out of the question for me if you take a look at my code. I must check if the user is authenticated and call redirectLogin from within the APP_INITIALIZER when my Angular app is boostrap. There is no component at this stage.

The other way is to subscribe to handleRedirectObservable  manually. But I don't really understand if I should do that and what is the purpose of doing so. 

Can I not just use loginRedirect as shown in my code above ?

**Comment by jasonnutter** [comment]
@graphicsxp If your application uses redirect-based interaction, you will need to invoke `handleRedirectObservable` before making any further MSAL requests. This is because processing redirects in v2 is asynchronous. You can do this by using the `MsalRedirectComponent` (which invokes this method for you), or by manually invoking `handleRedirectObservable`.

This could look something like this:

```js
 public async isUserLoggedIn(): Promise<boolean> {
    try {
     // If you want to work with promises, just invoke `handleRedirectPromise` on teh PCA instance directly
      const redirectResult = await this._authService.instance.handleRedirectPromise();
      if (this._authService.instance.getAllAccounts().length > 0) {
        return true;
      } else {
         reject('User is not signed in. Redirecting to login page.');
      }
   } catch (e) {
      this._authService.msalService.loginRedirect();
      return false;
    }
```
