### ISSUE TITLE
Running "npm install @azure/msal-angular --save" returns 404

### ISSUE THREAD

**Issue by M-Medhat** [AzureAD/microsoft-authentication-library-for-js#375]
I was trying the Angular wrapper for MSAL. It seems the package is not published yet. Running:

```
npm install @azure/msal-angular --save
```

returns a 404 error:

```
npm ERR! code E404
npm ERR! 404 Not Found: @azure/msal-angular@latest
```

**Comment by simonscoffins** [comment]
Also get this.

**Comment by jay-pillai** [comment]
Same here. Is it not published to npmjs

**Comment by nehaagrawal** [comment]
@M-Medhat  @simonscoffins @jay-pillai . This is currently under development and it's only merged to the dev branch and not master. We will be releasing it soon. Thank you for your patience!
