### ISSUE TITLE
Still not working - Re: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2524

### ISSUE THREAD

**Issue by gomobileas** [AzureAD/microsoft-authentication-library-for-js#3750]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

None

### Description

I still get null when I try to get all or the current accountId.

// APIClient.getMsAccountHomeAccountId() is our cookie stored version of account.HomeAccountId which we aquired when we logged in the first time with  msalInstance.acquireTokenPopup().
// When we try to refresh we would like to use the acquireTokenSilent function of msalbrowser. But it requires the account object.
// But it returns a null value

    const currentAccount = msalInstance.getAccountByHomeId(APIClient.getMsAccountHomeAccountId());

// So instead we use the account.username value (our cookie stored version is: APIClient.getMsAccountUserName())
// to refresh.
// this works perfectly.
// But we would ideally like to use the acquireTokenSilent function of msalbrowser

    const refreshTokenRequest = {
      loginhint: APIClient.getMsAccountUserName(),
    };
    var refreshTokenResponse = await msalInstance.acquireTokenPopup(refreshTokenRequest);

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by gomobileas** [comment]
Ps. We use @azure/msal-browser directly in our reactjs code. We do not use MSAL React (@azure/msal-react).

**Comment by samuelkubai** [comment]
@gomobileas what gets returned by `getAllAccounts()`, do you see you `homeAccountId` in the list of accounts that are returned?
