### ISSUE TITLE
[PublicClientApplication.getAllAccounts() - (msal-browser)] Proper documentation not available describing multiple logged in accounts scenarios.

### ISSUE THREAD

**Issue by Rinki-MSFT** [AzureAD/microsoft-authentication-library-for-js#3751]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

Not Applicable

### Documentation Location

https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-acquire-token?tabs=javascript2; https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-java-get-remove-accounts-token-cache

### Description

PublicClientApplication.getAllAccounts() - (msal-browser):
No Documentation to address the developer/customer questions like below -
- When can PublicClientApplication.getAllAccounts() return more than one account?
- How does this work with SSO? If the user logged in using different accounts on two other websites before coming to mine, would I get two accounts? Are they sorted in any order?
- If PublicClientApplication.getAllAccounts() returns some account/accounts then does it guarantee that user is logged in? 
- If I want to check authentication on startup do I need to force loginRedirect/loginPopup or I can first check that getAllAccounts() already has something? What is the best practice?
- Link to Sample/documentation that demonstrates how to switch between multiple logged in accounts.

Please validate the below information and add it in the documentation along with additional info-
 - MSAL does not make assumptions about what account to use. It will either use the account passed into the API or the active account that was previously set by calling setActiveAccount. Each call to loginPopup or loginRedirect will always result in exactly one account. getAllAccounts is not guaranteed to be sorted in any order, nor is it guaranteed to return the same order across calls.

**Comment by samuelkubai** [comment]
@Rinki-MSFT thanks of the feedback, we will ensure we update the docs. In the meantime here are the answers to your questions:

> When can PublicClientApplication.getAllAccounts() return more than one account?

If you have made multiple interactive calls (redirect or popup) and the user has chosen different accounts in two or more of the interactions.

> How does this work with SSO? If the user logged in using different accounts on two other websites before coming to mine, would I get two accounts? Are they sorted in any order?

No and No, unless the other two websites are on the same domain.

> If PublicClientApplication.getAllAccounts() returns some account/accounts then does it guarantee that user is logged in?

No, `getAllAccounts` returns local account state and does not guarantee that the user has an active sessions on the server

> If I want to check authentication on startup do I need to force loginRedirect/loginPopup or I can first check that getAllAccounts() already has something? What is the best practice?

You can first check getAllAccounts() and then acquireTokenSilent(), if acquireTokenSilent throws an interaction_required error then call loginRedirect() or loginPopup().

>Link to Sample/documentation that demonstrates how to switch between multiple logged in accounts.

This is business logic that varies from app to app, we have a ticket open to add a sample for this. #3189 

> MSAL does not make assumptions about what account to use. It will either use the account passed into the API or the active account that was previously set by calling setActiveAccount. Each call to loginPopup or loginRedirect will always result in exactly one account. getAllAccounts is not guaranteed to be sorted in any order, nor is it guaranteed to return the same order across calls.

That is correct

**Comment by Rinki-MSFT** [comment]
@samuelkubai Thank you so much for the answers :).
