### ISSUE TITLE
Call interactive API, before logging in user

### ISSUE THREAD

**Issue by adodrndarr** [AzureAD/microsoft-authentication-library-for-js#3752]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.0

### Description

I'm using **MSAL** to authenticate and later b2c flows to sign in users to the application, everything works fine so far.

However, I'd like to **register** (sign up) users not using the b2c user flow, but rather use a custom page (**component**),
where I will **gather user information**, **call an interactive API** and continue on with the **application**.

The issue is while using ngrx, when dispatching an action after form submit (calling interactive API), 
MSAL **immediately** redirects to "Login b2c user flow page" or sometimes **throws** BrowserAuthError: Interaction_in_progress.

Now I'm familiar with Interaction_in_progress, usually one would wait for **InteractionStatus.None** in order to execute some code.
But in this case the status **never** gets to "InteractionStatus.None", since the user is **never** **logged in** (as pointed out I would like to **register** (sign up) the user). Therefore the status **stays** in **InteractionStatus.Startup**. 

Short version:
1. Anonymous user visits the application, fills out form to register, clicks **submit**.
2. An interactive API call is made to the backend to save user data.
3. After the dispatch of action **2.** is being made, MSAL **immediately**, either redirects to **login**
or throws Interaction_in_progress error.

- In case I wait for **"InteractionStatus.None"** in order to prevent the error,
code never executes, since user is not logged in, 
therefore the interaction status stays **"InteractionStatus.Startup"** forever.

The **main** **question**:
Any advice or recommendation, to make an API call, before user is logged in,
**without** MSAL interfering with this action?

- Interfering in the way that it requires the user to be logged in (by redirecting to login page)
- Interfering in another way that keeps **"InteractionStatus.Startup"** forever (until user logs in),
therefore **preventing** the app on executing api call on **InteractionStatus.None** (by throwing
BrowserAuthError: Interaction_in_progress in case you do not wait for **InteractionStatus.None** ).

The following would answer my question/resolve the issue:
1. Some way or suggestion if possible to change the InteractionStatus (this would allow to make API call when status is None).
2. Some way or suggestion  to prevent MSAL from redirecting the user to login page (this would allow the **app** to continue in normal flow, registering the user, making API call, continuing on..).
4. Any other suggestion on making API call before user is logged in, without MSAL interfering with it, is welcomed.

### MSAL Configuration

```javascript
// Configuration is great no problems here...


const isIE = window.navigator.userAgent.indexOf("MSIE ") > -1 || window.navigator.userAgent.indexOf("Trident/") > -1; // Remove this line to use Angular Universal

export function loggerCallback(logLevel: LogLevel, message: string) {
  console.log(message);
}

export function MSALInstanceFactory(): IPublicClientApplication {
  return new PublicClientApplication({
    auth: {
      clientId: B2CPolicies.clientId,
      authority: `${B2CPolicies.authority}/${B2CPolicies.names.signIn}`,
      redirectUri: B2CPolicies.redirectUrl,
      postLogoutRedirectUri: B2CPolicies.redirectUrl,
      knownAuthorities: [B2CPolicies.authorityDomain]
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE, // Set this to 'true' to save cache in cookies to address trusted zones limitations in IE
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Info,
        piiLoggingEnabled: false
      },
    }
  });
}

export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
  const protectedResourceMap = new Map<string, Array<string>>();
  protectedResourceMap.set(`${APP_CONFIG.apiBaseUrl}/endpoint1`, []);
  protectedResourceMap.set(`${APP_CONFIG.apiBaseUrl}/endpoint2`, []);
  protectedResourceMap.set(APP_CONFIG.apiBaseUrl, [...B2CPolicies.b2cScopes]);
  return {

    interactionType: InteractionType.Redirect,
    protectedResourceMap,
    authRequest: {}
  };
}

export function MSALGuardConfigFactory(tenantService: TenantService): MsalGuardConfiguration {
  return {
    interactionType: InteractionType.Redirect,
    authRequest: (authService, state) => {
      var tenantConfig = tenantService.getTenantB2cConfiguration(state.url, routes);
      var authority = tenantConfig.authority != null ? tenantConfig.authority : B2CPolicies.authority
      var signInFlow = tenantConfig.signInFlow != null ? tenantConfig.signInFlow : B2CPolicies.names.signIn;

      return {
        scopes: [...B2CPolicies.b2cScopes],
        authority: `${authority}/${signInFlow}`,
        redirectUri: tenantConfig.redirectUrl != null ? tenantConfig.redirectUrl : window.location.origin
      }
    },
  };
}

@NgModule({
  declarations: [LoginComponent],
  imports: [
    StoreModule.forRoot(appReducers),
    EffectsModule.forRoot([
      UserEffects,
      AuthenticationEffects
    ]),
    CommonModule,
    MsalModule
  ],
  providers: [
    AuthService,
    {
      provide: MSAL_INSTANCE,
      useFactory: MSALInstanceFactory
    },
    {
      provide: MSAL_GUARD_CONFIG,
      useFactory: MSALGuardConfigFactory,
      deps: [TenantService]
    },
    {
      provide: MSAL_INTERCEPTOR_CONFIG,
      useFactory: MSALInterceptorConfigFactory
    },
    {
      provide: HTTP_INTERCEPTORS,
      useClass: MsalInterceptor,
      multi: true
    },
    MsalService,
    MsalGuard,
    MsalBroadcastService],
  bootstrap: [MsalRedirectComponent]
})
```

### Relevant Code Snippets

```javascript
// Would like to call interactive API:
this.store.dispatch(new CreateUser(...));

// - Without MSAL interfering with this action and redirecting(forcing) the user to login.


    this.msalBroadcastService.inProgress$
      .pipe(
 ////// The log below, stays for user that is not logged in, always InteractionStatus.Startup
        tap(status => console.log(status)), 
        filter((status: InteractionStatus) => status === InteractionStatus.None),
      )
      .subscribe(() => {
////// The Api call Never executes since Status is Startup...
        this.store.dispatch(new CreateUser(...)); 
      });


//// If you choose not to wait on InteractionStatus.None like so then:
 this.store.dispatch(new CreateUser(...)); // --> throws error Interaction_in_progress...
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by samuelkubai** [comment]
Hi @adodrndarr, in an effort to best debug the issue, please provide the msal-angular configuration

**Comment by adodrndarr** [comment]
Hi @samuelkubai, the issue was updated with the msal-angular configuration

**Comment by adodrndarr** [comment]
Thanks @samuelkubai  for the support, you're right the config was the issue.
Issue was resolved by:

export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
  const protectedResourceMap = new Map<string, Array<string>>();

  return {

    interactionType: InteractionType.Redirect,
    protectedResourceMap,
    authRequest: {}
  };
}

Configuring the correct protectedResourceMap sets, by allowing the /registration routes to be unprotected 
- Therefore MSAL allows user to interact with the app, make API calls etc.. without requiring a Login (the login redirect issue) or throwing any interaction in progress error..)
