### ISSUE TITLE
How can we receive the refresh token?

### ISSUE THREAD

**Issue by cwardcode** [AzureAD/microsoft-authentication-library-for-js#3753]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.0

### Description

I'm not exactly sure how I can retrieve the refresh token from the `/token` request's response using the MSAL library. I have a use case where I need to supply the Access, ID, and Refresh tokens to an external client. (ID token so the client can fetch claims, the Access token to call APIs on behalf of the user, and the Refresh token to provide long-lived authentication on the client). The gist of it is that I have a SPA that will receive the tokens, and then push it to a headless device.

I'm calling the acquireTokenPopup function to retrieve the tokens, but Refresh is missing. This has been stated as to be by design, so how would I be able to retrieve the token, since it is not included as part of the authentication result?

I know it's still cached in local storage, but I can't find a way to access the refresh token's key. It seems to built by convention with a unique prefix, but is there an accessor for that prefix?

A question you may be wondering - why not use device code flow - that seems perfect? 
* The end-client that is receiving the tokens from the SPA _is_ headless, but the client cannot make the /devicecode or /token requests directly because it does not have the ability to do so, so the SPA is a middle-man of sorts.
* I can't create the device code request through the SPA because it is blocked due to having an 'Origin' header. The endpoint returns a message that states I should use a different auth flow.

### MSAL Configuration

```javascript
{
  auth: {
    clientId: this.clientId.value,
    authority: `https://login.microsoftonline.com/${this.tenantId.value}`,
    redirectUri: `${window.location.origin}`
  },
  cache: {
    cacheLocation: BrowserCacheLocation.LocalStorage
  }
}
```

### Relevant Code Snippets

```javascript
// Would like to be able to do something like this

try {
      const tokenResult: AuthenticationResult = await pca.acquireTokenPopup({
        ...this.msalGuardConfig.authRequest
      } as PopupRequest);

      if (tokenResult) {
        localStorage.setItem('MSAL.idToken', tokenResult.idToken);
        localStorage.setItem('MSAL.accessToken', tokenResult.accessToken);
        localStorage.setItem('MSAL.refreshToken', tokenResult.refreshToken);
      }
    } catch (error) {
      this.credentialError = error.message;
    }
  }
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by samuelkubai** [comment]
Hi @cwardcode, in an effort to better understand the issue, why can't the headless device do the device code flow?

**Comment by cwardcode** [comment]
Hi @samuelkubai,

Unfortunately, the device is not equipped with the functionality to do the extra steps necessary to initiate and validate a device-code flow, but it is capable of receiving the tokens as part of a configuration object, and knows how to work with them from that point.

**Comment by cwardcode** [comment]
The device doesn't support it at all. There isn't any way to proxy an HTTP request through it, or an API to initiate a device code request. It does expose a configuration that allows me to pass in the tokens individually, though

**Comment by samuelkubai** [comment]
Thank you @cwardcode for expounding on the limitations, since the headless device cannot handle an HTTP request, how do you intend to use the token on the device?

**Comment by cwardcode** [comment]
@samuelkubai It can make HTTP requests, it just cannot make any custom HTTP requests like I would need in order to initiate and verify a device though device code flow. After it receives the tokens, it can call any Azure-related web api to fetch necessary data and refresh the access token when needed. It knows how to do all of that, but it needs to have all three tokens supplied to it, as per the API specs.

**Comment by cwardcode** [comment]
@samuelkubai The device can take in the tokens if provided separately and make requests to receive calendar information for a user, it just does not have the ability to initially retrieve those tokens itself. Once the Access, ID, and Refresh tokens are provided, it can use the refresh token to generate new Access and ID tokens.

It seems as if I'm repeating myself. The original question was - How can I get the Refresh Token after calling `acquireTokenPopup`?

**Comment by samuelkubai** [comment]
Hi @cwardcode, apologies for the late reply, the msal library does not avail the refresh token by design. As the library is designed to handle token refreshes for it's users.

What we would implore you to do is try implement the [Device code flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-device-code) as that is the flow that best suites your scenario. Feel free to consult this [sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/device-code).

**Comment by cwardcode** [comment]
Unfortunately it’s not possible due to limitations of the third party device that I cannot modify. I’ll stick with using my forked version instead. 

I’m a little disappointed that it was a conscious effort to not supply the refresh token to consumers, especially since it is returned in the network request.
