### ISSUE TITLE
Token is not refreshing before it expires

### ISSUE THREAD

**Issue by muratygt** [AzureAD/microsoft-authentication-library-for-js#3756]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

1.4.11

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

I have an SPA (React) using MSAL for user authentication. The app is throwing 401 Auth error at 60 min mark regardless of user being active or not.

The token is not refreshing before it expires. I think the app is passing the old token at 60 min. mark for the JWT validator service then it fails the authentication. After the failure, it looks like acquireTokenSilent is refreshing the token but the app is already displays the error and blocks user interaction. User needs to do hard refresh to continue using the app.  

I am not saying that there might be something wrong with the library. I feel like there is a misconfiguration on our app which creates the problem. 

Help Needed to make sure everything is aligned. 

### MSAL Configuration

```javascript
auth: {
            instance: 'https://login.microsoftonline.com/',
            tenant: mytenant, // my tenant id
            clientId: myclient, // my client id
            authority: myauthority, // my authority
            validateAuthority: true,
            extraQueryParameters: { domain_hint: mydomainHint},
            redirectUri: 'http://localhost:3000',
            navigateToLoginRequestUrl: true,
            expireOffsetSeconds: 300
        },
        cache: {
            cacheLocation: 'localStorage',
            storeAuthStateInCookie: false
        },
        system: {
            loggerOptions: {
                loggerCallback: (level, message, containsPii) => {
                    if (containsPii) {
                        return;
                    }
                    console.log('loggerCallback Error Message', message);
                }
            },
            loadFrameTimeout: 9000,
            tokenRenewalOffsetSeconds: 0,
            ignoreExpiration: true
        }
    }
```

### Relevant Code Snippets

```javascript
// Function Logic that creates User Authentication flow

import * as Msal from 'msal';
import { axiosInstance as axios } from '../helpers/axiosInstance';

const msalInstance = new Msal.UserAgentApplication(MSAL_CONFIG);
const loginRequest = {
    scopes: ['openid', 'profile', 'User.Read.All']
};

const requiresInteraction = (errorMessage) => {
    if (!errorMessage || !errorMessage.length) {
        return false;
    }
    return (
        errorMessage.indexOf('consent_required') > -1 ||
        errorMessage.indexOf('interaction_required') > -1 ||
        errorMessage.indexOf('login_required') > -1
    );
};

const acquireToken = async (request) => {
    return msalInstance.acquireTokenSilent(request).catch((error) => {
        if (requiresInteraction(error.errorCode)) {
            return msalInstance.acquireTokenPopup(request);
        }
    });
};

const signIn = async () => {
    const loginResponse = await msalInstance.loginRedirect(loginRequest)?.catch((error) => {});
    if (loginResponse) {
        const token = await acquireToken(loginRequest).catch((error) => {});
        axios.defaults.headers.common.Authorization = `Bearer ${token.idToken.rawIdToken}`;
        return token;
    }
};

// First function is being called before rendering the app. //
 
const autoMsalSignIn = async () => {
    msalInstance.handleRedirectCallback((error, response) => {});

    if (window === window.parent && window === window.top) {
        let account = msalInstance.getAccount();
        if (account) {
            const token = await acquireToken(loginRequest).catch((error) => {});

            axios.defaults.headers.common.Authorization = `Bearer ${token.idToken.rawIdToken}`;
            return token;
        } else if (!msalInstance.isCallback(window.location.hash)) {
            signIn();
        }
    }
};

// Axios Instance being imported by the above functions //

import axios from 'axios';

export const axiosInstance = axios.create({
    baseURL: `${BASE_URL}`,
    withCredentials: true
});
```

### Identity Provider

Azure AD / MSA

### Source

@jasonnutter ^^^

External (Customer)

**Comment by pratapdev** [comment]
I am looking for the same kind of auto login in my application, can you please provide a basic code for this approach, thanks

**Comment by tnorling** [comment]
@muratygt Can you try setting `tokenRenewalOffsetSeconds` to 300? This will tell MSAL to renew the token if it's within 5 minutes of expiration. A value of 0 means that MSAL will not attempt to renew the token until it is expired which can lead to behaviors such as the one you describe.

**Comment by muratygt** [comment]
Thanks @tnorling. I am doing it now and will update the thread with findings. But with more reading the docs, I feel like our app is using Implicit Grant Flow which is not refreshing the token implicitly as mentioned here

https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-implicit-grant-flow#prefer-the-auth-code-flow

I feel like `tokenRenewalOffsetSeconds: 300` won't be enough to solve my problem. I need to either refresh the token periodically or migrate to Auth Grant Flow (PKCE) as the documentation suggests. Will definitely update the thread either ways.

**Comment by tnorling** [comment]
Yes msal.js v1 uses Implicit Grant Flow and we highly recommend upgrading to v2 if you are able to. The `tokenRenewalOffsetSeconds` will be relevant in either version however. Both libraries will only return a token if it thinks it is valid, if it's unable to renew for any reason it should throw an error.

**Comment by AimeSoleil** [comment]
hi @tnorling, could you explain more about `tokenRenewalOffsetSeconds`? When set this flag to `300`, does it mean a background task will refresh the token before 5 minutes when token get expired or we have to call `acquireToken` explicitly?

**Comment by muratygt** [comment]
Update from adding `tokenRenewalOffsetSeconds: 300` into the configuration. It did not fix the problem of refreshing token before it expires. App is still throwing 401 auth error. I guess it fits into the @tnorling 's last statement of `Both libraries will only return a token if it thinks it is valid, if it's unable to renew for any reason it should throw an error.`

**Comment by tnorling** [comment]
> hi @tnorling, could you explain more about tokenRenewalOffsetSeconds? When set this flag to 300, does it mean a background task will refresh the token before 5 minutes when token get expired or we have to call acquireToken explicitly?

You still need to call `acquireTokenSilent`. If the token is expired or within 5 minutes of being expired MSAL will attempt to renew it instead of returning the cached token. We do this to account for any sort of clock skew that might cause MSAL to return a token that is already expired.

>App is still throwing 401 auth error. I guess it fits into the @tnorling 's last statement of Both libraries will only return a token if it thinks it is valid, if it's unable to renew for any reason it should throw an error.

The 401 is being thrown by the resource, not MSAL, correct? To clarify my previous statement, barring some edge cases around clock skew, MSAL should never return to you an expired token. If you're getting a 401 from the resource is it possible that you aren't using the token that was returned by `acquireTokenSilent` and are instead still using a stale value from before? 

The code you've shared above shows you setting your axios headers with the idToken in your `signIn` function and not the `acquireToken` function. Was this intentional? Also this way of providing the token to API calls may cause race conditions if your API calls aren't waiting for acquireTokenSilent to complete. I'd suggest doing some debugging here to determine if `acquireTokenSilent` is returning valid tokens and if those same tokens are being sent to the resource. You can use a site like jwt.ms to decode the tokens and inspect their expiry. Lastly is there a reason you are using the idToken instead of the accessToken?
