### ISSUE TITLE
Migrating to msal-angular v2 - issue loading in iframe.

### ISSUE THREAD

**Issue by sbsdcorp** [AzureAD/microsoft-authentication-library-for-js#3759]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.0

### Description

Hi all, 

We were able to successfully migrate from v1 to v2 authorization code flow with PKCE (redirect flow), the upgrade documentation really help through the process. The app is working fine, but we haven't been able to get it to load within an iframe.

Without the following router module setting, the app gets into an infinite login loop (see verbose logs below) We were wondering if the initial navigation == 'disabled' is preventing the app from loading in iframe.

`initialNavigation: !isIframe ? 'enabled' : 'disabled' // Remove this line to use Angular Universal`

Is there anything we can do to fix the "not loading in iframe" issue?

![image](https://user-images.githubusercontent.com/46551560/122087807-248dd300-cdd3-11eb-8704-be0ada445add.png)

Thanks in advance for the support!

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@sbsdcorp Yes, if your app is loaded in an iframe, you will need to change the logic provided in the samples for `initialNavigation`. 

> We were wondering if the initial navigation == 'disabled' is preventing the app from loading in iframe.

Likely yes. This logic is provided to prevent issues when your app is loaded in an iframe or popup when acquiring new tokens, so will need to make this logic smarter to handle your scenario.

> Without the following router module setting, the app gets into an infinite login loop (see verbose logs below) 

Please provide your MSAL Angular configuration. Note, applications that render in iframes cannot use redirects for interaction and will have to use popups.

**Comment by sbsdcorp** [comment]
Hey @jasonnutter, thanks for the feedback. I think you nailed the issue pointing out that applications rendering in iframes cannot use redirects for interaction and will have to use popups. I will give it a shot, hopefully I will be able to have a conditional flow so the app uses redirect when not loaded in iframe and popup when it does, otherwise we will need to switch it all to popup.

Thank you gain,

**Comment by sbsdcorp** [comment]
Thank you guys for supporting this libraries.
