### ISSUE TITLE
Request help refreshing tokens/getting new token after expiration

### ISSUE THREAD

**Issue by PumpkinVision** [AzureAD/microsoft-authentication-library-for-js#3760]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

Hello,

I have had success using @azure/msal-browser with a Vue SPA and Azure AD in the past but now am having trouble refreshing tokens.
At least two things have changed:
1. My company has started requiring 2FA for IT users, which applies to me.
2. I have switched from Chrome to Edge as my primary browser.
3. A third change may be updates to @azure/msal-browser. I am now using version 2.14.2.

Symptom:
I log in. I use my app. I leave it for over a day. I come back and my UI still thinks I'm logged in. I go to pages requesting api resources and fail. The only way that I see to 'get going' again is to fully log out. If I need to request a new 'from scratch' token, I'm fine with that, but I think I should be able to do so without fully logging out from my Azure AD account. At least, I used to be able to do so with Chrome, and I would like to get that experience again. (With Chrome, I never had to worry about any kind of interactivity after the initial login. All of the refreshing or even new token acquisition was handled so long as I logged in with 'stayed logged in'.)

Summary of code snippets:
1. a custom object wrapper using code from wiki samples (added to the msal config section)
2. a list of error messages with comments (added to the additional snippets section)

Thank you for your time!

### MSAL Configuration

```javascript
// 1. code for myMSALObjWrapper.js, with tenantID, clientID, scopeID removed
import * as msal from '@azure/msal-browser';

const msalConfig = {
  auth: {
    // clientId is the applicationID.
    clientId: 'myClientID',

    // The authority is a URL that indicates a directory from which MSAL can request tokens.
    authority: 'https://login.microsoftonline.com/<tenantID>',

    // The tenant id goes at the end of the authority url
    // if we want to limit logins to our tenant.
    tenantID: '<tenantID>',

    // redirect uri is where we are redirected after authenticating
    // this may be optional; we will try skipping so that we don't adjust the user's url
    // as they could be logging in from any url
    // (the sign-in logic is in the header component which
    // appears on every page)
    // This appears to do nothing if we are using the pop-up flow (which we are).
    // However, this has turned out to not be optional and must match
    // one of the redirectUris configured in app config in Azure AD.
    redirectUri: process.env.VUE_APP_SPA,

    // postLogoutRedirectUri is where we are redirected after logging out
    postLogoutRedirectUri: '<myAppSignInUrl>',
  },
  cache: {
    // This configures where your cache will be stored
    cacheLocation: 'localStorage',
    // Set this to "true" if you are having issues on IE11 or Edge
	// I have tried false and true for storeAuthStateInCookie
    storeAuthStateInCookie: true,
  },
};

const myMSALObj = new msal.PublicClientApplication(msalConfig);

const myMSALObjWrapper = {
  myMSALObj,
  loginRequest: {
    scopes: ['User.Read'],
  },
  tokenRequest: {
    scopes: ['api://<long id>/access_as_user'],
    // For core Microsoft apis, you can get away (and should get away) with simple scopes
    // like "User.Read".
    // But for our own apis, we must use this longer form. That is how Azure AD
    // knows which api's "access_as_user" token we are requesting.
    forceRefresh: false,
  },
  username: null,
  isAuthenticated: false,
  roles: null,
  // login/logout logic
  selectAccount() {
    /**
     * See here for more info on account retrieval:
     * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/docs/Accounts.md
     */
    const currentAccounts = this.myMSALObj.getAllAccounts();
    if (currentAccounts.length > 1) {
      // Add choose account code here
      console.warn('Multiple accounts detected.');
    } else if (currentAccounts.length === 1) {
      this.username = currentAccounts[0].username;
      this.isAuthenticated = true;
      this.roles = currentAccounts[0].idTokenClaims.roles;
    }
  },
  handleResponse(response) {
    /**
     * To see the full list of response object properties, visit:
     * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/request-response-object.md#response
     */
    if (response !== null) {
      return {
        response,
        username: response.account.username,
        isAuthenticated: true,
        roles: response.idTokenClaims.roles,
      };
    }
    this.selectAccount();
    return {};
  },
  signIn() {
    /**
    * You can pass a custom request object below.
    * This will override the initial configuration. For more information, visit:
    * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/request-response-object.md#request
    */
    this.myMSALObj.loginPopup(this.loginRequest)
      .then(this.handleResponse)
      .then((value) => {
        if ('username' in value) {
          this.username = value.username;
          this.isAuthenticated = value.isAuthenticated;
          this.roles = value.roles;
        }
      })
      .catch((error) => { console.error(error); });
  },
  signOut() {
    /**
     * You can pass a custom request object below.
     * This will override the initial configuration. For more information, visit:
     * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/request-response-object.md#request
     */
    // Choose which account to logout from by passing a username.
    const logoutRequest = {
      account: this.myMSALObj.getAccountByUsername(this.username),
    };
    this.myMSALObj.logoutPopup(logoutRequest);
    this.username = null;
    this.isAuthenticated = false;
  },
  async authorizationHeader() {
    if (process.env.VUE_APP_SKIP_AUTH === 'false') {
      const tokenRequestResponse = await this.getTokenPopup(this.tokenRequest);
      const { accessToken } = tokenRequestResponse;
      return { Authorization: `Bearer ${accessToken}` };
    }
    return {};
  },
  // api authorization logic
  getTokenPopup(request) {
    /**
     * See here for more info on account retrieval:
     * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/docs/Accounts.md
     */
    const requestCopy = request;
    requestCopy.account = myMSALObj.getAccountByUsername(this.username);

    return myMSALObj.acquireTokenSilent(requestCopy)
      // eslint-disable-next-line consistent-return
      .catch((error) => {
        console.warn('silent token acquisition fails. acquiring token using popup.');
        if (error instanceof msal.InteractionRequiredAuthError) {
          // fallback to interaction when silent call fails
          return myMSALObj.acquireTokenPopup(requestCopy)
            .then((tokenResponse) => tokenResponse).catch((error2) => {
              console.error(error2);
            });
        }
        console.warn(error);
        // return new Promise<msal.AuthenticationResult>();
      });
  },
};

export default myMSALObjWrapper;
```

### Relevant Code Snippets

```javascript
// 2. console error messages with comments
// I get a variety of error messages depending upon the details of the situation
// (e.g. did I just come back to the app, did I try to login with Chrome,
// did I try the sign-in function with Edge without signing out (i.e. to just
// get a token without having to fully sign out of my Azure AD account),
// did I go ahead and sign out of the Azure AD account and then try to sign in, etc.)

https://login.microsoftonline.com/<tenant id>/oauth2/v2.0/token
Failed to load resource: the server responded with a status of 400 (Bad Request)
VM1016 log.js:24 [HMR] Waiting for update signal from WDS...
myMSALObjWrapper.js?2df5:137 silent token acquisition fails. acquiring token using popup.
eval @ myMSALObjWrapper.js?2df5:137
myMSALObjWrapper.js?2df5:145 BrowserAuthError: monitor_window_timeout: Token acquisition in iframe failed due to timeout.
    at BrowserAuthError.AuthError [as constructor] (AuthError.js?d98c:27)
    at new BrowserAuthError (BrowserAuthError.js?be02:153)
    at Function.BrowserAuthError.createMonitorIframeTimeoutError (BrowserAuthError.js?be02:254)
    at eval (SilentHandler.js?da2f:71)
eval @ myMSALObjWrapper.js?2df5:145
myMSALObjWrapper.js?2df5:120 Uncaught (in promise) TypeError: Cannot read property 'accessToken' of undefined
    at _callee$ (myMSALObjWrapper.js?2df5:120)
    at tryCatch (runtime.js?96cf:63)
    at Generator.invoke [as _invoke] (runtime.js?96cf:293)
    at Generator.eval [as next] (runtime.js?96cf:118)
    at asyncGeneratorStep (asyncToGenerator.js?1da1:3)
    at _next (asyncToGenerator.js?1da1:25)


web page error when browsing to token url (first link in above error messages)
https://login.microsoftonline.com/<tenant id>/oauth2/v2.0/token
Sorry, but we’re having trouble signing you in.

AADSTS900561: The endpoint only accepts POST, OPTIONS requests. Received a GET request.


token error message from network tab in Edge developer tools (after signing in with Chrome)
{error: "invalid_grant",…}
correlation_id: "<correlation id>"
error: "invalid_grant"
error_codes: [700081]
error_description: "AADSTS700081: The refresh token has expired due to maximum lifetime. The token was issued on 2021-06-11T14:41:07.2876675+00:00 and the maximum allowed lifetime for this application is 1.00:00:00.\r\nTrace ID: <trace id>\r\nCorrelation ID: <correlation id>\r\nTimestamp: 2021-06-15 16:45:08Z"
error_uri: "https://login.microsoftonline.com/error?code=700081"
suberror: "bad_token"
timestamp: "2021-06-15 16:45:08Z"
trace_id: "<trace id>"


error message when trying to sign in without signing out
myMSALObjWrapper.js?2df5:101 BrowserAuthError: hash_empty_error: Hash value cannot be processed because it is empty. Please verify that your redirectUri is not clearing the hash. Given Url: http://localhost:8080/products/browse
    at BrowserAuthError.AuthError [as constructor] (AuthError.js?d98c:27)
    at new BrowserAuthError (BrowserAuthError.js?be02:153)
    at Function.BrowserAuthError.createEmptyHashError (BrowserAuthError.js?be02:190)
    at eval (PopupHandler.js?f2c2:58)
	
// As of the time of submitting this issue, I am currently stuck with the hash_empty_error message.
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by PumpkinVision** [comment]
Additional details: I am using the v2 workflow and the popup flow.

**Comment by samuelkubai** [comment]
Hi @PumpkinVision, could you please provide the correlation id and email me the fiddler trace.

**Comment by PumpkinVision** [comment]
Hello and thank you for the reply.
I tried just now hoping to reproduce the issue, but I had no errors in Edge.
Is there a way to force my token to expire?

**Comment by PumpkinVision** [comment]
I was able to reproduce the error.
The full error message (with correlation id b9bc8029-946d-4b65-b40a-50350e00645b) is {"error":"invalid_grant","error_description":"AADSTS700081: The refresh token has expired due to maximum lifetime. The token was issued on 2021-06-16T12:09:11.5199847+00:00 and the maximum allowed lifetime for this application is 1.00:00:00.\r\nTrace ID: 084af7f0-f422-4005-862d-c27df2612100\r\nCorrelation ID: b9bc8029-946d-4b65-b40a-50350e00645b\r\nTimestamp: 2021-06-17 13:20:09Z","error_codes":[700081],"timestamp":"2021-06-17 13:20:09Z","trace_id":"084af7f0-f422-4005-862d-c27df2612100","correlation_id":"b9bc8029-946d-4b65-b40a-50350e00645b","error_uri":"https://login.microsoftonline.com/error?code=700081","suberror":"bad_token"}

I have attached two sessions from fiddler reaching out to login.microsoftonline.com:443. I believe that there are two sessions due to the attempted token retry that is in my code and copied from the examples.
if (error instanceof msal.InteractionRequiredAuthError) {
          // fallback to interaction when silent call fails
          return myMSALObj.acquireTokenPopup(requestCopy)
            .then((tokenResponse) => tokenResponse).catch((error2) => {
              console.error(error2);
            });
        }
[9_Full.txt](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/6670519/9_Full.txt)
[10_Full.txt](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/6670520/10_Full.txt)

**Comment by PumpkinVision** [comment]
Ran into the issue again today.
{"error":"invalid_grant","error_description":"AADSTS700081: The refresh token has expired due to maximum lifetime. The token was issued on 2021-06-17T13:27:58.3361948+00:00 and the maximum allowed lifetime for this application is 1.00:00:00.\r\nTrace ID: c50baa14-2e35-4a23-abd1-5276cb5f1f00\r\nCorrelation ID: cedab5ae-790a-42a2-ac97-f209ee908a07\r\nTimestamp: 2021-06-18 14:41:34Z","error_codes":[700081],"timestamp":"2021-06-18 14:41:34Z","trace_id":"c50baa14-2e35-4a23-abd1-5276cb5f1f00","correlation_id":"cedab5ae-790a-42a2-ac97-f209ee908a07","error_uri":"https://login.microsoftonline.com/error?code=700081","suberror":"bad_token"}
[2_Full.txt](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/6677753/2_Full.txt)
[3_Full.txt](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/6677754/3_Full.txt)
[32_Full.txt](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/6677755/32_Full.txt)
[33_Full.txt](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/6677756/33_Full.txt)
![error 2021-06-18](https://user-images.githubusercontent.com/43766736/122579279-bf302100-d022-11eb-83d1-f56d57751730.png)

**Comment by PumpkinVision** [comment]
I want to add that I must have been confused when I said earlier that using Chrome fixed my Edge refresh, as I now understand that whether tokens are kept as cookies or in local storage, Chrome and Edge use different cookie sets and different areas of local storage.

But in any event, I encountered the refresh issue again (morning of Monday 6/21/2021). I was able to resolve by fully logging out of my Azure AD/O365 account and then logging back in, but this is not something I want to ask my users to do. It seems that I don't need to do so with Chrome, and I would like to support Edge as well.

**Comment by tnorling** [comment]
@PumpkinVision The `invalid_grant` error is expected every 24 hours as it means the Refresh Token has expired. The MSAL library should silently catch this error and attempt to acquire a new Refresh Token and Access Token using a hidden iframe, which may result in the `monitor_window_timeout` error you've shown in the screenshot if 3rd party cookies are blocked.

Can you please confirm a couple things for me?

1. Is the `invalid_grant` error being thrown back to your application or are you only seeing this in the network logs?
2. Are 3rd party cookies blocked?
3. When you get the `monitor_window_timeout` error are you falling back to `acquireTokenPopup`?

You should not need to logout when this happens, you should be able to resolve this by calling an interactive method, such as `acquireTokenPopup`. Have you tried that and does it help?

**Comment by PumpkinVision** [comment]
@tnorling Hi and thank you for the comment.
1. I'm not sure how to answer. I am not checking for errors apart from checking for instances of msal.InteractionRequiredAuthError within an attempt to acquireTokenSilent. Functionally, my app is trying to fill a grid with data acquired from a secured api. Since I don't have a valid token, I'm unable to get the data. I see the errors in the console tab of Edge's developer tools panel.
2. I can confirm 3rd party cookies are not blocked in either Edge or Chrome. (screenshot attached for Edge).
3. Currently, I am only falling back to acquireTokenPopup when I receive a specific error type, namely msal.InteractionRequiredAuthError.

Here is my code, which I copied from the msal documentation examples:
`// api authorization logic
  getTokenPopup(request) {
    /**
     * See here for more info on account retrieval:
     * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/docs/Accounts.md
     */
    const requestCopy = request;
    requestCopy.account = myMSALObj.getAccountByUsername(this.username);

    return myMSALObj.acquireTokenSilent(requestCopy)
      // eslint-disable-next-line consistent-return
      .catch((error) => {
        console.warn('silent token acquisition fails. acquiring token using popup.');
        if (error instanceof msal.InteractionRequiredAuthError) {
          // fallback to interaction when silent call fails
          return myMSALObj.acquireTokenPopup(requestCopy)
            .then((tokenResponse) => tokenResponse).catch((error2) => {
              console.error(error2);
            });
        }
        console.warn(error);
        // return new Promise<msal.AuthenticationResult>();
        this.isAuthenticated = true;
      });
  },`

I can try invoking acquireTokenPopup whenever acquireTokenSilent fails, regardless of error type. I'm not sure how to early expire my tokens, and so I'll need to wait for expiration before I can try, but I will do so.

![not blocking 3rd party cookies Edge](https://user-images.githubusercontent.com/43766736/122822773-85724b00-d2ac-11eb-9b56-d7c22797739e.png)

**Comment by tnorling** [comment]
@PumpkinVision 

> I'm not sure how to answer. I am not checking for errors apart from checking for instances of msal.InteractionRequiredAuthError within an attempt to acquireTokenSilent. Functionally, my app is trying to fill a grid with data acquired from a secured api. Since I don't have a valid token, I'm unable to get the data. I see the errors in the console tab of Edge's developer tools panel.

Where did you copy the `invalid_grant` error you shared above from? Was it outputted directly to the console or did you copy it from the network tab? The screenshot you shared of the console does not show this error and instead shows `monitor_window_timeout` error. I want to make sure we're chasing the correct error, as it's expected that the network would respond with the `invalid_grant` error but it should never be exposed to your code or the console.

Assuming for a second that everything is behaving as I expect, the `monitor_window_timeout` error is the one we need to focus on. This can happen for a variety of reasons but most commonly it happens because the page you use as your `redirectUri` is either automatically invoking its own navigation or clearing/changing the url hash. The first thing I want to have you try is setting your `redirectUri` to a blank page that doesn't implement MSAL or do anything else.

> I can try invoking acquireTokenPopup whenever acquireTokenSilent fails, regardless of error type. I'm not sure how to early expire my tokens, and so I'll need to wait for expiration before I can try, but I will do so.

To trigger this behavior you can open local/sessionStorage and delete the refresh token entry. The cache value will have a `credentialType: RefreshToken` parameter. You may also set `forceRefresh: true` in your `acquireTokenSilent` call to make sure it skips looking for cached access tokens.

**Comment by PumpkinVision** [comment]
You are correct; I did get the invalid_grant error from the network tab. I forgot that I had checked both the console tab and the network tab for error messages.

I first tried just updating my redirect uri to http://localhost:8080/test, both in the app and in Azure AD registration.
That didn't seem to work on its own.
I then updated my getPopup method to always try acquireTokenPopup if acquireTokenSilent failed (regardless of error type).
This didn't seem to work immediately, but I clicked on several pages in succession and eventually I was reauthenticated. I think I may have seen a popup flash on and then off, but I never fully logged out.

So I think I'm mostly the way there.

I do have some redirect coding in my app.
Location 1:
In my vue-router logic, I redirect from the "/" (which was my original redirect uri from authentication) to another path.
{
      name: 'default',
      path: '/',
      redirect: { name: 'productBrowse' },
},

Location 2:
I'm trying to offer users the ability to copy-paste a url when they are not signed in, then get bounced to a signin page, then force them to sign in, and then when sign-in is complete, they get redirected to their original destination. This would be particularly useful when they are punching out from another application (and don't have any url in their clipboard that to simply 'paste and try again').

The following code is in a header component that is present in all routes (i.e. static part of top-level component template):
watch: {
    isLoggedIn(newValue, oldValue) {
      if (newValue === true && oldValue === false) {
        const redirectUri = this.redirectUri || '/';
        this.$router.push(redirectUri);
      }
    },
  },

Do you think either of these is at issue?

I can easily let go of the redirect from "/", but I would like to maintain the ability for the user to be automatically re-routed to their original destination.
Is that possible without breaking the url hash that is involved in authentication?

**Comment by tnorling** [comment]
@PumpkinVision It sounds like both of these are the culprit (Redirect1 originally, and Redirect2 after you switched to using /test). You don't have to give up either approach if you have a dedicated route you use as your `redirectUri` that doesn't re-route (best is if you make this page completely blank with no logic). If you're only using the popup and silent flows the `redirectUri` will only ever be opened inside the popup or a hidden iframe so it will never be visible to users and doesn't have to affect the rest of your app.

I recognize it's not always possible to have a dedicated route for this and so the 2nd best option is to add some additional logic to your redirect code that checks if it's inside an iframe or not before redirecting.

It's also worth mentioning that MSAL's redirect flow implements the logic you describe for Redirect2 out of the box. However, then interactive authentication is done in a full frame redirect to AAD instead of in the popup, but want to throw that out there as another option.

**Comment by PumpkinVision** [comment]
Thank you very much for the info and your time!
I'm not sure which approach I will choose, but I think I am sufficiently unstuck to proceed on my own and will close the the issue.
Thanks again!
