### ISSUE TITLE
Will the error catched in handleRedirectPromise method contain user privacy data?

### ISSUE THREAD

**Issue by Chun817** [AzureAD/microsoft-authentication-library-for-js#3763]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

Since we have a requirement to log all error info into our telemetry for debugging. I searched the web, I cannot find clearly explanations what kind of error will be throw from handleRedirectPromise. If the error contains customer user privacy data, we're not allowed to log it into our telemetry.

I did some investigation. I am wondering if the error catched in handleRedirectPromise just the errors defined in BrowserAuthErrorMessage, the list like below:

![image](https://user-images.githubusercontent.com/86034042/122324200-fa671d00-cf5a-11eb-85f0-b15d942a2d3e.png)

Really appreciated for your help~

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by samuelkubai** [comment]
Hi @Chun817, Yes the errors thrown for `handleRedirectPromise` are only the errors in `BrowserAuthErrorMessage` that pertain to the flow.

**Comment by Chun817** [comment]
> Hi @Chun817, Yes the errors thrown for `handleRedirectPromise` are only the errors in `BrowserAuthErrorMessage` that pertain to the flow.

Thanks for your response. Will the errors in BrowserAuthErrorMessage contains any customer privacy data? like user id, client id and etc.

**Comment by samuelkubai** [comment]
> Will the errors in BrowserAuthErrorMessage contains any customer privacy data? like user id, client id and etc.

No, customer privacy data like user id, client id and the like are not included in the errors.
