### ISSUE TITLE
How to feed sessionStorage for be connected in e2e test in cypress ?

### ISSUE THREAD

**Issue by MaxEleg** [AzureAD/microsoft-authentication-library-for-js#3768]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.10.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

2.10.0

### Description

Hi

I'm using @azure/msal-browser for handle auth on my app, i wrote e2e tests with [cypress](https://www.cypress.io/) but i would like be connected on azure ad when cypress run the tests.

I use the webservice https://login.microsoftonline.com/XXXX/oauth2/v2.0/token for get a token, but I don't know how to feed the sessionStorage for be connected on msal/browser library.

I try to use this code https://github.com/juunas11/AzureAdUiTestAutomation but it doesn't work anymore.

Can you help me please ?

### Source

External (Customer)

**Comment by tnorling** [comment]
@MaxEleg Check out our [testing sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-browser-samples/TestingSample) which uses `msal-node` to acquire tokens in the test suite and hydrates sessionStorage with those tokens. What you're interested in can be found in [this file](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-browser-samples/TestingSample/test/browser-test.spec.ts). Let us know if that helps!

**Comment by MaxEleg** [comment]
I try to implement the code but I got CORS error, where can i fix this ? 

![image](https://user-images.githubusercontent.com/25806663/123440303-ea8eaf00-d5d2-11eb-9b43-66173d6d73c5.png)

**Comment by tnorling** [comment]
@MaxEleg Your `redirectUri` needs to be registered as type "Spa" in your app registration. Can you please verify this?

**Comment by MaxEleg** [comment]
@tnorling it is
![image](https://user-images.githubusercontent.com/25806663/124720943-f484ac00-df08-11eb-9fad-43b00e2868d2.png)

**Comment by tnorling** [comment]
@MaxEleg Do you happen to have any other redirect Uris registered as type "web"? Are all of them type "SPA"? If you have a localhost uri registered as both types the server may choose either one (even if the ports don't match)

**Comment by MaxEleg** [comment]
@tnorling we got only SPA

**Comment by tnorling** [comment]
@MaxEleg Can you please email me a fiddler trace and a copy of your app manifest? Thanks!

**Comment by MaxEleg** [comment]
ok i will thanks!

**Comment by MaxEleg** [comment]
It works ! Thank you but be careful ⚠️ **this script works only in nodejs env, not on the browser**
