### ISSUE TITLE
Authentication prompt while 401 request failure - MSAL renew token after expiry takes time

### ISSUE THREAD

**Issue by RomaRathi** [AzureAD/microsoft-authentication-library-for-js#3769]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

^2.12.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.0-beta.1

### Description

The access token gets expired in half an hour and after that when the api request is made the same expiry token gets appended in the headers and thus 401 response is thrown and that results in the authentication prompt asking for username and password.

According to msal and await async the tasks till the response is not processed it should not proceed further but in this case it is behaving wrong.

i have attached an text file with the code.
[msal.txt](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/6671820/msal.txt)

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by tnorling** [comment]
@RomaRathi Is there a reason you aren't using the [Interceptor](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/msal-interceptor.md) provided by msal-angular? 

The code you've shared isn't working because you need to await your `getAccessToken()` call in the `_setAuthHeaders` function and await that before calling your API.

**Comment by RomaRathi** [comment]
@tnorling I'm using interceptor in the app.module file as follows.
{ provide: HTTP_INTERCEPTORS, useClass: MsalInterceptor, multi: true }
It dos not append the accesstoken for the API calls that is why I have to append it by calling acquiretokensilent.

**Comment by tnorling** [comment]
@RomaRathi 

> It does not append the accesstoken for the API calls in the headers that is why I have to append it by calling acquiretokensilent.

It should. Let's figure out why it's not. Can you share your interceptor config?

**Comment by RomaRathi** [comment]
@tnorling 
[Interceptor config.txt](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/6678095/Interceptor.config.txt)

**Comment by tnorling** [comment]
@RomaRathi Thanks. For your `window.location.origin + /api/*` and `window.location.origin + /api/*/*` routes can you try providing the relative path instead, both with and without the leading slash? There's a note at the bottom of [this doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/msal-interceptor.md) about relative resources.

Also can you please try upgrading to the GA version of msal-angular as it is now out of beta?

**Comment by RomaRathi** [comment]
@tnorling 

I have awaited the getAccessToken as suggested but this still does not work.

private async _setAuthHeaders(token_type = 'Bearer') {
    //access_token = access_token || this.getAccessToken();
    if (this.accessToken == "" || this.tokenExpiry < Date.now() + 60000) 
      await this.getAccessToken();

    this.authHeaders = new HttpHeaders();
    this.authHeaders = this.authHeaders.append('Authorization', token_type + ' ' + this.accessToken);
    this.authHeaders = this.authHeaders.append('Content-Type', 'application/json');
  }

**Comment by RomaRathi** [comment]
> @RomaRathi Thanks. For your `window.location.origin + /api/*` and `window.location.origin + /api/*/*` routes can you try providing the relative path instead, both with and without the leading slash? There's a note at the bottom of [this doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/msal-interceptor.md) about relative resources.
> 
> Also can you please try upgrading to the GA version of msal-angular as it is now out of beta?

Actually this approach will be a bit of a work for the organization as every time the new api is added we need to add the path here.
also there are too many api calls in the project.
Will this be a better approach?

**Comment by tnorling** [comment]
@RomaRathi You can still use the wildcards, just omit the `window.location.origin` part.

Try `/api/*` and `/api/*/*` and `api/*` and `api/*/*`

**Comment by RomaRathi** [comment]
> @RomaRathi You can still use the wildcards, just omit the `window.location.origin` part.
> 
> Try `/api/*` and `/api/*/*` and `api/*` and `api/*/*`

@tnorling 
Yeah gotcha...! I removed the window.location.origin and removed the implementation of setting the headers from the AcquireTokensilent method.
Happy to see the token is getting appended in the headers without it.
Now I just need to test that what happens if I make a call after the expiry of the token.

**Comment by RomaRathi** [comment]
@tnorling  

One observation though.
Every time the new token is appended for every API request but that is not the case with the AcquireTokensilent method.
With AcquireTokensilent one token is utilized unless and until it is expired.

**Comment by RomaRathi** [comment]
> @tnorling
> 
> One observation though.
> Every time the new token is appended for every API request but that is not the case with the AcquireTokensilent method.
> With AcquireTokensilent one token is utilized unless and until it is expired.

**Comment by tnorling** [comment]
@RomaRathi I noticed you had set `tokenRenewalOffsetSeconds` in your msal config to 60,000. This is way too high and likely why it's not using the cached token. We typically recommend a value of around 300 which means the token will only be renewed if it is within 5 minutes of expiration. 60,000 is much higher than the lifetime of the token so it will always try to renew
