### ISSUE TITLE
useIsAuthenticated hook returns false on every refresh

### ISSUE THREAD

**Issue by a2441918** [AzureAD/microsoft-authentication-library-for-js#3772]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.0

### Description

I try to use the useIsAuthenticated hook to see if I am logged in or not. If not, I render a login screen and clicking the button will call instance.loginRedirect(). I see the login screen on every fresh login (which is correct). I go through the login process and after navigating through the app, when I refresh the browser, I keep coming back to the login screen. Instead I expect to see the same page since I am already logged in.

### MSAL Configuration

```javascript
import {
  BrowserCacheLocation,
  Configuration,
  RedirectRequest,
} from '@azure/msal-browser';

const CLIENT_ID = process.env.REACT_APP_MSAL_CLIENT_ID || '';
const TENANT_ID = process.env.REACT_APP_MSAL_TENANT_ID || '';
const AUTHORITY = `https://login.microsoftonline.com/${TENANT_ID}`;

const REDIRECT_URI = `${window.location.protocol}//${window.location.host}/`;

/**
 * Config object to be passed to Msal on creation
 */
export const msalConfig: Configuration = {
  auth: {
    clientId: CLIENT_ID,
    authority: AUTHORITY,
    redirectUri: REDIRECT_URI,
    postLogoutRedirectUri: REDIRECT_URI,
  },
  cache: {
    cacheLocation: BrowserCacheLocation.LocalStorage,
    storeAuthStateInCookie: false,
  },
};

/**
 *  Add here scopes for access token to be used at MS Identity Platform endpoints.
 */
export const apiRequest: RedirectRequest = {
  scopes: [process.env.REACT_APP_API_SCOPE || ''],
};

/**
 *  Add here the endpoints for MS Graph API services you would like to use.
 */
export const graphConfig = {
  graphMeEndpoint: 'https://graph.microsoft.com/v1.0/me',
};
```

### Relevant Code Snippets

```javascript
const App: FunctionComponent = () => {
  const { instance, inProgress } = useMsal();
  const isAuthenticated = useIsAuthenticated();

  // useEffect(() => {
  //   instance
  //     .handleRedirectPromise()
  //     .then((authResult) => {
  //       // Check if user signed in
  //       const account = instance.getActiveAccount();
  //       if (!account) {
  //         // redirect anonymous user to login page
  //         instance.loginRedirect(apiRequest);
  //       }
  //     })
  //     .catch((err) => {
  //       // TODO: Handle errors
  //       console.log(err);
  //     });
  // }, [instance]);



  return (
    <ThemeProvider theme={theme}>
      {isAuthenticated ? (
        <ProfileComponent>
                <Routes />
        </ProfileComponent>
      ) : <Login /> }
    </ThemeProvider>
  );
};
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by tnorling** [comment]
@a2441918 Can you please confirm that the `MsalProvider` component is rendered above the `App` component?

If so it's possible the login is not succeeding. Can you try calling `handleRedirectPromise` and see if it returns a result or throws an error?

**Comment by a2441918** [comment]
> @a2441918 Can you please confirm that the `MsalProvider` component is rendered above the `App` component?
> 
> If so it's possible the login is not succeeding. Can you try calling `handleRedirectPromise` and see if it returns a result or throws an error?

Yeah.

    import './support/polyfills';
    import './index.scss';

    import React from 'react';
    import ReactDOM from 'react-dom';

    import {
      AuthenticationResult,
      EventMessage,
      EventType,
      PublicClientApplication,
    } from '@azure/msal-browser';

    import { MsalProvider } from '@azure/msal-react';

    import App from './components/shared/App';
    import { msalConfig } from './services/AuthConfig';

    /**
     * Initialize a PublicClientApplication instance which is provided to the MsalProvider component
     * We recommend initializing this outside of your root component to ensure it is not re-initialized on re-renders
     */
    export const msalInstance = new PublicClientApplication(msalConfig);

    // Account selection logic is app dependent. Adjust as needed for different use cases.
    const accounts = msalInstance.getAllAccounts();
    if (accounts.length > 0) {
      msalInstance.setActiveAccount(accounts[0]);
    }

    msalInstance.addEventCallback((event: EventMessage) => {
      if (event.eventType === EventType.LOGIN_SUCCESS && event.payload) {
        const payload = event.payload as AuthenticationResult;
        const account = payload.account;
        msalInstance.setActiveAccount(account);
      }
    });


    ReactDOM.render(
      <MsalProvider instance={msalInstance}>
        <App />
      </MsalProvider>,
      document.getElementById('root')
    );

**Comment by tnorling** [comment]
> Is it because I clear localStorage in index.ts?

This could definitely be it. What happens if you don't clear localStorage?

**Comment by a2441918** [comment]
> > Is it because I clear localStorage in index.ts?
> 
> This could definitely be it. What happens if you don't clear localStorage?

If I dont clear it, it works great. The reason I clear localStorage is that I am accessing this app from a portal. The portal sends me a token and I store that token in localStorage and use that for API calls. There are cases where I can access this app directly instead through the portal. The existing token in localStorage is expired but still the expired token is being used as a Bearer token.

**Comment by tnorling** [comment]
@a2441918 Can you clear just the token in question (I would also suggest adding an expiration check if this is an issue)? MSAL needs to maintain state between page loads so clearing all storage will definitely break MSAL.

**Comment by a2441918** [comment]
Sure, yeah I'll do that. My other plan is to validate the token from the portal and if its a good one, I'll make a call to MS and get the token through msal and use this new token for Bearer auth. Is this a good approach?

**Comment by tnorling** [comment]
If you have a valid token why do you need to get a new one? If you want to make sure all tokens are obtained by MSAL I'd suggest not passing the token in from the portal at all. But it's ultimately up to you and what makes sense for your app and the scenarios you need to support.

**Comment by a2441918** [comment]
Got it. Thanks man. Appreciate the help.
