### ISSUE TITLE
Missing information in msal-react FAQ code snippet

### ISSUE THREAD

**Issue by svdHero** [AzureAD/microsoft-authentication-library-for-js#3777]
### Wrapper Library

MSAL React (@azure/msal-react)

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/FAQ.md#how-do-i-handle-the-redirect-flow-in-a-react-app

### Description

In said documentation there is the following code snippet:

```javascript
const GetDataFromAPI = () => {
    const { instance, accounts } = useMsal();
    const isAuthenticated = useIsAuthenticated();
    const [graphData, setGraphData] = useState(null);

    useEffect(() => {
        if (isAuthenticated && inProgress === InteractionStatus.None) {
            instance.acquireTokenSilent({
                account: accounts[0],
                scopes: ["User.Read"]
            }).then(response => {
                callAPI(response.accessToken);
            })
        }
    }, [inProgress, isAuthenticated, accounts, instance]);
};
```
What exactly is `inProgress` here? Is it some local state or is it part of the `msal-react` library or where does it come from?

**Comment by derisen** [comment]
@svdHero `inProgress` value comes from [useMsal()](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/hooks.md#usemsal-hook) hook. It indicates whether msal is performing any interactions at the moment (acquiring a token, handling redirect response etc.)

The snippet should've been like this (will make sure to update the docs):

```javascript
const GetDataFromAPI = () => {
    const { instance, accounts, inProgress } = useMsal();
    const isAuthenticated = useIsAuthenticated();
    const [graphData, setGraphData] = useState(null);

    useEffect(() => {
        if (isAuthenticated && inProgress === InteractionStatus.None) {
            instance.acquireTokenSilent({
                account: accounts[0],
                scopes: ["User.Read"]
            }).then(response => {
                callAPI(response.accessToken);
            })
        }
    }, [inProgress, isAuthenticated, accounts, instance]);
};
```

**Comment by derisen** [comment]
@svdHero just updated the docs. Feel free to close this if your issue is resolved.

**Comment by svdHero** [comment]
@derisen Thank you for your help. I have one follow-up question, though. When should I check the condition `inProgress === InteractionStatus.None`? Every time I interact with MSAL? I haven't seen such a check in former code snippets and MS tutorials (like 6 months ago). Is this new?

**Comment by derisen** [comment]
@svdHero ensuring that there is no other interaction taking place when using an interactive API is the standard recommendation with msal.js (there might be a doc/sample where this is not reflected, do you remember where you saw it?). This is especially true in hooks like `useEffect()` that updates dom upon component mount and update. Pretty much all the code samples and tutorials at this point reflect this. 

So not necessarily everytime you interact with msal but its a good idea when using an interactive msal API (acquireTokenPopup etc).

**Comment by svdHero** [comment]
@derisen I have three folders on ma hard-disk with official microsoft samples that do not reflect any `InteractionStatus` checks when retrrieving a token. The folder names are

- msal-browser-samples
- msal-react-samples
- ms-identity-javascript-react-spa-main

Unfortunately, I do not know from which Github repo I downloaded them originally. So probably the folder names above do not help really, do they? I am sorry.

Coming back to your explanations: I can see how checking the `InteractionStatus` via `inProgress` works when using the `useEffect` hook, because once `inProgress` changes, the effect is triggered again. But how would that work with a button click handler, e.g. for a form's submit button? For example:
```javascript
    const handleSubmitButtonClick = async () => {
        if (isAuthenticated && inProgress === InteractionStatus.None) {
            instance.acquireTokenSilent({
                account: accounts[0],
                scopes: ["MyBackEnd.ReadWrite"]
            }).then(response => {
                submitFormToBackEnd(response.accessToken, formContent);
            })
        }        
    }
```
If `inProgress` is not `None`, the button click doesn't do nothing. What should I do then? Present some "try again"-dialog to the user? Of course, I could disable the button in the first place, until `inProgress` is `None`, but then there could still be a race condition between the user clicking the enabled submit button and MSAL having some issues with `inProgress` not being `None` anymore, right?

What's the recommended way to implement this use case? Should I check `inProgress` at all inside event handlers (`<button onClick=...>`, `<select onChange=...>`, etc.)?
Maybe this could also be added to the documentation? Or did I just miss that part?

**Comment by svdHero** [comment]
No, I am not trying to avoud the check for performance reasons. I was merely wondering how to design the "UX flow" and what to do, in case a user presses the button, the check fails and `inProgress` is not `None`.

Maybe it would be worthwhile to add some submit button code snippet to the code samples for noobies like me? Other than that, the documentations has really been improved and is much clearer now. Great job!

**Comment by tnorling** [comment]
@svdHero It's really up to you how you want to handle this scenario, there's no right or wrong way to do this (which is also why it's not explicitly documented). MSAL will throw an error if interaction is in progress and you try to invoke another interaction so if you want to avoid this error it would be wise to check if anything is in progress before invoking interaction. Other ways you could handle this are:
- Disabling the button when interaction is in progress to prevent someone from clicking it a second time
- Catching the error thrown and doing nothing if the button is clicked again
- Notifying the user to complete in progress interaction when the button is clicked again

Our samples all demonstrate login button usage and throw the interaction_in_progress error to the console if the button is clicked while another is in progress. We can consider updating one of the samples with one of the above solutions instead.

**Comment by svdHero** [comment]
Thank you @tnorling for your explanations. I will consider your points and will have a look at the latest examples again.

Maybe it could help to add the explanations in this issue to the documentation. Or is there already a paragraph dedicated to `InteractionStatus` and check failure handling?

**Comment by tnorling** [comment]
@svdHero From the [FAQ on redirects](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/FAQ.md#how-do-i-handle-the-redirect-flow-in-a-react-app):

> Be sure to check that a user is signed in and interaction isn't in progress before you attempt to retrieve the token.

Additionally, most of our code snippets and all of our samples demonstrate checking `inProgress`/`InteractionStatus` before invoking MSAL APIs. You'll also find a detailed explanation specifically about the `interaction_in_progress` error, why it's thrown and how to fix it in the [error doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/errors.md#interaction_in_progress) which is referenced in the error message. Was there anything specific you think is missing from the docs?
