### ISSUE TITLE
What order are user roles returned?

### ISSUE THREAD

**Issue by BrandonSchreck** [AzureAD/microsoft-authentication-library-for-js#3778]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

1.4.4

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

1.1.2

### Description

Is there was a specific order in which user roles are returned (roles that were created/assigned first, alphabetic, etc.) from Azure, if it was static (the same order on each request), or some type of random order?

### MSAL Configuration

```javascript
auth: {
  clientId: environment.apimClientId,
  authority: environment.apimAuthority,
  validateAuthority: true,
  redirectUri: environment.redirectUrl,
  postLogoutRedirectUri: environment.redirectUrl,
  navigateToLoginRequestUrl: true,
},
cache: {
  cacheLocation: 'localStorage',
  storeAuthStateInCookie: isIE, // set to true for IE 11
},
```

### Relevant Code Snippets

```javascript
In an internal application I inherited a user can have multiple roles and based upon certain roles the user is routed to different parts of the application. An interesting bug has popped up that I am investigating, but I was curious if there was a specific order in which user roles are retrieved from Azure AD?
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by derisen** [comment]
@BrandonSchreck there is no mention of this in any of the roles documentation that I know of. I've just did a few tests and it doesn't seem that like they are sorted by date of creation or the order of user assignment.

@hpsin do you have any insight on this?

**Comment by hpsin** [comment]
There are no orderings or set pattern to how roles are put into the array I'm afraid.  You should always be doing full existence checks on the values in roles, and there should be no roles that imply _lesser_ authorization than another. E.g. a role of "CannotAccessSentMail" would be inappropriate to build, as it's very easy to write buggy code around it.

**Comment by BrandonSchreck** [comment]
I think this is where the big was introduced. While a user may have multiple roles, the code is using the first value from the array as the user’s role. Thank you all for the quick feedback.

**Comment by tnorling** [comment]
Closing as resolved. Please do let us know if you need further assistance. Thanks!
