### ISSUE TITLE
Listen to logout event

### ISSUE THREAD

**Issue by yakimko** [AzureAD/microsoft-authentication-library-for-js#378]
Hi!
I use localStorage as cacheLocation.
I have 2 pages opened and I logginned in on both.
When I log out on the first page, I would like to catch this event on my second page.
Now I see only one way to handle it: listen to localStorage
Do you know another proper way to handle it?

**Comment by nehaagrawal** [comment]
@yakimko  did you try calling getUser(). GetUser() should return null when you logout.

**Comment by yakimko** [comment]
@nehaagrawal I can call getUser() but when I should do it? I do not know that user is logged out on another page.

**Comment by nehaagrawal** [comment]
@yakimko  Can you please give more details about your use case? When you said 2 pages, are you talking about 2 instances of the same spa opened in different tabs and you logout from one instance and the other instance doesn't know that you logout?

**Comment by yakimko** [comment]
@nehaagrawal 
> are you talking about 2 instances of the same spa opened in different tabs and you logout from one instance and the other instance doesn't know that you logout?

exactly

**Comment by nehaagrawal** [comment]
@yakimko  currently we don't have any such event for logout. If you refresh the page on the 2nd app, you should see that the user is logged out.
