### ISSUE TITLE
Identity is not authenticated and has empty claims when it reaches API

### ISSUE THREAD

**Issue by robsierra** [AzureAD/microsoft-authentication-library-for-js#3780]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.0

### Description

I've been trying to implement this library with Azure B2C but I've hit a roadblock with authentication. I'm able to login to the app with the front-end code and push the access token to the API but by the time the request gets to the 'AuthorizationHandler' implementation on the API the user identity is completely blank. It has one identity but all the values are null and 'Authenticated' is false. I presume this is the reason that my requests are redirected to '<myUrl>/Account/Login?ReturnUrl='actualUrlNeeded''. Originally I was using the MsalService and our own interceptor but I've since switched to using the MSALInterceptor and I have the same problem, any and all help is greatly appreciated as this one has me stumped.

### MSAL Configuration

```javascript
const isIE = window.navigator.userAgent.indexOf('MSIE ') > -1 || window.navigator.userAgent.indexOf('Trident/') > -1;

export function MSALInstanceFactory(): IPublicClientApplication {
   return new PublicClientApplication({
      // MSAL Configuration
      auth: {
         clientId: <our client id>,
         authority: 'https://<our tenant>.b2clogin.com/<our tenant>.onmicrosoft.com/B2C_1_sign-in',
         knownAuthorities: ['https://<our tenant>.b2clogin.com'],
         redirectUri: 'https://localhost:5001/login',
         postLogoutRedirectUri: 'https://localhost:5001/login'
      },
      cache: {
         cacheLocation: BrowserCacheLocation.LocalStorage,
         storeAuthStateInCookie: isIE, // set to true for IE 11
      },
      system: {
         loggerOptions: {
            loggerCallback: () => {},
            piiLoggingEnabled: false,
         },
      },
   });
}

export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
   return {
      interactionType: InteractionType.Popup, // MSAL Interceptor Configuration
      protectedResourceMap: new Map([
      ['/api/', ['https://<our tenant>.onmicrosoft.com/<our client id>/access_as_user', 'openid', 'profile']],
      ]),
   };
}


@NgModule({
   declarations: [AppComponent, NavMenuComponent, HomeComponent],
   imports: [
...
MsalModule
...
],
   providers: [
...
       { provide: HTTP_INTERCEPTORS, useClass: MsalInterceptor, multi: true },
      {
        provide: MSAL_INSTANCE,
        useFactory: MSALInstanceFactory
      },
      {
        provide: MSAL_GUARD_CONFIG,
        useFactory: MSALGuardConfigFactory
      },
      {
        provide: MSAL_INTERCEPTOR_CONFIG,
        useFactory: MSALInterceptorConfigFactory
      },
      MsalService,
      MsalGuard,
      MsalBroadcastService,
...
  ],
   bootstrap: [AppComponent, MsalRedirectComponent],
```

### Relevant Code Snippets

```javascript
Api in Startup.cs:

services.AddSingleton<IAuthorizationPolicyProvider, CustomAuthorizationPolicyProvider>();
            services.AddSingleton<IAuthorizationHandler, ValidUserAuthorizationHandler>();
            services
               .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
               .AddMicrosoftIdentityWebApi(options =>
               {
                  options.TokenValidationParameters.NameClaimType = "name";
               },
               options => {
                  options.Instance = "https://<our tenant>.b2clogin.com";
                  options.ClientId = "<our client id>";
                  options.Domain = "<our tenant>.onmicrosoft.com";
                  options.TenantId = "<our tenant id>";
                  options.SignUpSignInPolicyId = "B2C_1_sign-in";
               });


In CustomAuthorizationPolicyProvider:

public Task<AuthorizationPolicy> GetDefaultPolicyAsync()
      {
         var policy = new AuthorizationPolicyBuilder();
         policy.AddRequirements(new ValidUserAuthorizationRequirement());
         policy.Combine(options.Value.DefaultPolicy);
         return Task.FromResult(policy.Build());
      }

//placeholder
internal class ValidUserAuthorizationRequirement : IAuthorizationRequirement
   {
   }
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by tnorling** [comment]
@robsierra Can you please clarify, is your API receiving the token but with missing claims or is it not receiving a token at all?

**Comment by robsierra** [comment]
@tnorling Yes, thank you for examining the question. I receive the token but all of the information in the identity is null:
![image](https://user-images.githubusercontent.com/86315244/122983735-4e626f00-d36a-11eb-869f-39b0955d5e53.png)

**Comment by tnorling** [comment]
@robsierra Since MSAL is successfully acquiring the token and attaching it to the request I'm going to suggest you reach out to Azure B2C Support. MSAL has no control over the contents of the token, that is likely controlled by your tenant settings, policy configuration, app registration and/or specific claims/scopes you need to request. Unfortunately we are not the experts in this area so I can't give you any suggestions, however, support should be better able to help you get this resolved. You can open a ticket with them [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options)

**Comment by robsierra** [comment]
@tnorling Okay, thank you very much I'll do just that.
