### ISSUE TITLE
Does MSAL.js v2.x support hybrid flow?

### ISSUE THREAD

**Issue by nilact** [AzureAD/microsoft-authentication-library-for-js#3789]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

I got to know from the FAQ that MSAL.js V2.x only supports response_mode=fragment.

However, I couldn't find anywhere that whether the library supports hybrid flow.

I also tried providing response_type: id_token as extraQueryParameters but it did not consider it.

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@nilact To clarify, are you referring to the hybrid flow defined here? https://openid.net/specs/openid-connect-core-1_0.html#HybridFlowAuth

**Comment by nilact** [comment]
@jasonnutter Please refer to the below link:

https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#request-an-id-token-as-well-hybrid-flow

**Comment by jasonnutter** [comment]
@nilact Right, thanks. MSAL.js v2 does not currently support the hybrid flow. I will add this to our backlog as an enhancement.

**Comment by nilact** [comment]
@jasonnutter Thanks for clarifying it. It should have been mentioned somewhere in the FAQ at least.

**Comment by jasonnutter** [comment]
@nilact You're welcome, and yeah, that's fair, I'll see that it gets added.

**Comment by bladmoreno** [comment]
Hi Team, I have been trying to migrate our app to V2, I migrated the Redirect URLS to SPA and disabled Access Token and Hybrid flow from Azure AD but I am getting this error, that supposed to be the right configuration for code flow.

#error=unsupported_response_type&error_description=AADSTS700054%3a+response_type+%27id_token%27+is+not+enabled+for+the+application.%0d%0aTrace+ID%3a+94f892c9-3f75-46b2-9fe9-09e5371b2200%0d%0aCorrelation+ID%3a+b16b473f-d2bd-4070-9640-cf2b7181300b%0d%0aTimestamp%3a+2021-09-21+14%3a14%3a39Z&error_uri=https%3a%2f%2flogin.microsoftonline.com%2ferror%3fcode%3d700054&state=d3b85a01-15ef-43b8-9828-48096ba01e4e

What Can I do to solve this issue?

**Comment by jasonnutter** [comment]
Closing, as we have no plans to support `code id_token` for MSAL Browser.

@bladmoreno Please open a new issue if this is still an issue, thanks.
