### ISSUE TITLE
Integration with Azure App Service Authentication (Easy Auth)?

### ISSUE THREAD

**Issue by watabtme** [AzureAD/microsoft-authentication-library-for-js#379]
Azure App Service Authentication requires calling an `/.auth/me` endpoint from the client-side in order to obtain an API access token. The documentation (https://docs.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-auth-aad) says that this can be managed by the ADAL library, but obviously I would prefer to use MSAL since it's the new standard. I'm not seeing any functions in the public API that would allow me to perform this sort of flow. Is it currently supported in MSAL?

**Comment by visualjeff** [comment]
The OpenID Connect UserInfo endpoint is not implemented on the v2.0 endpoint. 

However, all user profile data that you potentially would receive at this endpoint is available from the Microsoft Graph /me endpoint.

**Comment by visualjeff** [comment]
I don't believe so.  

The public API's don't give any indication of such support:
https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Public-APIs

I grep'd the source for **authorityInstance.AuthorizationEndpoint** and it didn't look as if it had such a feature or flexibility built-in.

**Comment by navyasric** [comment]
@watabtme I am not sure I understand your scenario. MSAL.js provides authentication with AAD and gets the user info from the id token claims. It does not make the API calls for you. Using the tokens it gets your app can call APIs. In your case, if you have already authenticated in your app using Easy Auth redirecting to AAD, why do you still need MSAL? Is there a reason your app cannot call the /.auth/me endpoint you mention directly like you would call any API endpoint?

**Comment by watabtme** [comment]
@navyasric there is still a need for something like MSAL because Azure Easy Auth only provides the initial login logic. Once the client-side code calls /.auth/me, the application is now responsible for actually maintaining the auth state, refreshing the token when necessary, monitoring validity of the token, etc etc. In other words, all the things that MSAL provides (other than the very first login call).

**Comment by kraihn** [comment]
I was able to get my MSFT Org based login working with this library and additionally getting an access token for App Authentication on an App Service/Azure Functions. The key is that although your primary login might be using v2, the app service auth request expects the v1 designation of resource access requests instead of scopes. If you try to access your resources using scopes similar as to defined below, you shouldn't have a problem.

protectedResourceMap
```
[
    'https://your-site-url-with-auth.azurewebsites.net',
    ['https://your-site-url-with-auth.azurewebsites.net/user_impersonation']
  ]
```

consentScopes
```
consentScopes: [
    ...,
    'https://your-site-url-with-auth.azurewebsites.net/user_impersonation'
  ]
```

This FAQ is what let me to the answer.
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Adal-to-Msal#scopes-for-a-v1-application

**Comment by navyasric** [comment]
Closing this issue since the above comment provides information to resolve this.
