### ISSUE TITLE
Msal angular

### ISSUE THREAD

**Issue by ssunkara79** [AzureAD/microsoft-authentication-library-for-js#3790]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0

### Description

Upgraded msal version to 2.

After login ,not able to get active account,retuns null as active account.

### Error Message

BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.  For more visit: aka.ms/msaljs/browser-errors.
BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.

### MSAL Configuration

```javascript
this.clientApplication = new PublicClientApplication({
      auth: {
        clientId: _env.clientID,
        authority: this.authority,
        redirectUri: _env.postLogoutRedirectUri, //this.getFullUrl(window.location.href),
        postLogoutRedirectUri: _env.postLogoutRedirectUri, //this.getFullUrl(window.location.href),
        knownAuthorities: ["acktenant.b2clogin.com"]
        //validateAuthority: false,
      },
      cache: {
        cacheLocation: BrowserCacheLocation.LocalStorage,
        storeAuthStateInCookie: isIE, // set to true for IE 11
      },

    });
```

### Relevant Code Snippets

```javascript
below are msal versions in package.json
@azure/msal-angular": "^2.0.0",
@azure/msal-browser": "^2.14.2"

below code is included in appmodule.ts
export const apiConfig: { scopes: string[]; uri: string } = {
  scopes: ['https://acktenant.onmicrosoft.com/demoapi/demo.read'],
  uri: 'https://localhost:44356'
};
export function MSALInstanceFactory(): IPublicClientApplication {
  return msalconfig;
}
export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
  const protectedResourceMap = new Map<string, Array<string>>();
  protectedResourceMap.set(apiConfig.uri, apiConfig.scopes);

  return {
    interactionType: InteractionType.Redirect,
    protectedResourceMap,
  };
}
```

### Reproduction Steps

after login redirect to home page but login fails with above error

### Expected Behavior

after login it should goes into login success event.

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer, None (Server)

### Source

Internal (Microsoft)

**Comment by jasonnutter** [comment]
@ssunkara79 If your app uses redirect-based interaction, you need to wait until any in progress redirect operations are completed before making further MSAL requests. Please see this document for more details on using redirects: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/redirects.md

**Comment by ssunkara79** [comment]
@jasonnutter ,

I have included MsalRedirectComponent but still had same issue.

getting below errors
AADB2C90079: Clients must send a client_secret when redeeming a confidential grant.
interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.  For more visit: aka.ms/msaljs/browser-errors.
BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.

please let me know what is the issue

**Comment by jasonnutter** [comment]
@ssunkara79 Please verify that all redirect URIs used with MSAL.js are marked as "spa".

**Comment by ssunkara79** [comment]
It works fine in MSAL 1.0, while upgrading angular version 1.0 to 2.0 I am getting the above issues.
Is there any Azure B2C related changed in Msal version 2.0?

**Comment by jasonnutter** [comment]
@ssunkara79 Setting your redirect URI to spa is a requirement for MSAL v2: https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-app-registration#redirect-uri-msaljs-20-with-auth-code-flow

**Comment by ssunkara79** [comment]
I have followed above URL and marked all the redirect url's as SPA, but still having same issue.

**Comment by ssunkara79** [comment]
yes, getting 2 issues after setting the redirect Urls to SPA,

**Comment by tnorling** [comment]
@ssunkara79 Can you please also confirm that you don't have other localhost reply urls registered as type "web" on the same registration? If localhost exists as both type web and spa the login server will arbitrarily choose one to use, which can cause the client_secret error.

**Comment by ssunkara79** [comment]
hi @tnorling 
yeah I have same localhost url's  registered in WEB and SPA.
Now we modified the ports.so in WEB the localhost url is different and in SPA It is different.
Now I am getting the only Client secret error
invalid_request: undefined - [undefined]: AADB2C90079: Clients must send a client_secret when redeeming a confidential grant.
Correlation ID: 1a2da4e5-e14d-47c1-9d03-e0bbd80df85d
![Capture](https://user-images.githubusercontent.com/70937077/124269291-55526400-db58-11eb-81ef-9e60cdaeaff6.PNG)

**Comment by tnorling** [comment]
@ssunkara79 localhost URIs are all treated the same by the portal, changing the port is not enough. See [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/reply-url#localhost-exceptions) and please make sure localhost is only defined as type SPA

**Comment by ssunkara79** [comment]
hi @tnorling ,
thanks for the quick response.
I have removed localhost URLs in web. kept localhost URLs as SPA.
still having same issue, please help me on this asap

**Comment by tnorling** [comment]
@ssunkara79 Can you please email me a fiddler trace and your app registration manifest?

**Comment by ssunkara79** [comment]
![MSALError](https://user-images.githubusercontent.com/70937077/125454080-b219d8c3-93d5-48d4-a0a3-000fc5189ddd.PNG)
[FiddlerTrace.zip](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/6808922/FiddlerTrace.zip)
Hi
I have attached fiddler trace and app registration manifest.
I have created new active directory and app ,now I am getting different error.
can you please check attached Msal error.
Let me know any other information is required.

**Comment by tnorling** [comment]
@ssunkara79 This fiddler trace is empty, and the manifest is not included in the .zip

Regarding the `untrusted_authority` error, did you update your `knownAuthorities` config parameter after you created the new directory?

**Comment by ssunkara79** [comment]
Hi
thanks for quick response.
I have updated knownAuthorities, now I am able to login but after login getting Interaction is In progress error. please check the attached error.

I have added fiddler trance and manifest  again please check.
![error](https://user-images.githubusercontent.com/70937077/125573199-0fbac8ed-6db2-479e-889c-80687f78aa47.PNG)
[fiddlertrace.zip](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/6813987/fiddlertrace.zip)
[QA.zip](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/6813990/QA.zip)

**Comment by tnorling** [comment]
@ssunkara79 Can you please review [this doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/errors.md#interaction_in_progress) about the `interaction_in_progress` error?

**Comment by ssunkara79** [comment]
Hi,
Login success event is raising multiple times.
I have kept the below event in app component
ngOnInit() {
    
    if (this.authService.instance.getActiveAccount() == null) {
      this.broadcastService.msalSubject$
        .pipe(
          filter((msg: EventMessage) => msg.eventType === EventType.LOGIN_SUCCESS),
        )
        .subscribe({
          next: (result: EventMessage) => {
            console.log(result);
            const payload = result.payload as AuthenticationResult;
            this.authService.instance.setActiveAccount(payload.account);

            //  //console.log("acquire token success " + JSON.stringify(payload));
          },
          error: (error) => console.log(error)
        });
    }
  }

can you please check is there any problem with above code.

**Comment by tnorling** [comment]
@ssunkara79 Can you please provide verbose level logs?

**Comment by ssunkara79** [comment]
![log1](https://user-images.githubusercontent.com/70937077/126747950-cb844f4c-4edb-4ec5-b438-87f8510fb3a2.png)
Hi
I have attached verbose level logs.

**Comment by tnorling** [comment]
@ssunkara I'm not seeing any login success events here. Can you please include all the logs, additionally this appears to be log level `info`. Please set the log level to `verbose`. Thanks!
