### ISSUE TITLE
Inconsistent type definitions between retrieving account and silent request [TS]

### ISSUE THREAD

**Issue by sondrf14** [AzureAD/microsoft-authentication-library-for-js#3791]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.0

### Description

Using React Typescript, when retrieving the active account from the MSAL instance, the type definition is AccountInfo | Null. 
While e.g. the SilentRequest account property requires a type of AccountInfo | Undefined, causing the need of something like this:

![image](https://user-images.githubusercontent.com/86408662/123246066-b2f60900-d4e5-11eb-8f7e-594a657492dd.png)

This currently forces me to re-map the account object when passing it in for silent requests, which seems like a slightly unnecessary step. 

It would be beneficial if we could have consistent definitions, that don't require any extra steps of converting between null and undefined. 

### MSAL Configuration

```javascript
auth: {
        clientId: '',
        redirectUri: '',
        postLogoutRedirectUri: '',
        knownAuthorities: ['']
    },
```

### Relevant Code Snippets

```javascript
getAccessToken(context: IMSalContext) {
  const {instance} = context;
  const account = instance.getActiveAccount();
  instance.acquireTokenSilent({
            ...loginRequest,
            account: account 
        })
 ...
}
```

### Reproduction Steps

1. Get the active account from your MSAL context
2. Attempt to pass the account as a property to any SilentRequest

### Expected Behavior

Expecting consistent type definitions across different functions

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer, Other

### Source

External (Customer)

**Comment by sameerag** [comment]
> the SilentRequest account property requires a type of AccountInfo | Undefined

Silent calls have `AccountInfo` as a mandated parameter. I believe this is converted to `AccountInfo/Undefined` post compilation?

> Using React Typescript, when retrieving the active account from the MSAL instance, the type definition is AccountInfo | Null.

`getActiveAccount()` can return a null, since there is a possibility of no accounts in the cache/memory. 

I can check if there is a better way to avoid this.
