### ISSUE TITLE
@azure/msal-react with PublicClientApplication gives error "AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret"'.

### ISSUE THREAD

**Issue by sandeshindi** [AzureAD/microsoft-authentication-library-for-js#3792]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

@azure/msal-react 1.0.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

@azure/msal-react 1.0.0

### Description

When we use @azure/msal-react and PublicClientApplication initialize the config we get an error after login

"AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'."

### Error Message

"AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'."

### MSAL Configuration

```javascript
export const config = {
  auth: {
    clientId: msClientId, 
    authority: msAuthUrl,
    redirectUri: window.location.origin,
    clientSecret: msClientSecret
  },
  cache: {
    cacheLocation: "localStorage",
    storeAuthStateInCookie: true
  }
};
 
// Authentication Parameters
export const authenticationRequest = {
  scopes: [
    msScope
  ]
}
```

### Relevant Code Snippets

```javascript
export const pca = new PublicClientApplication(config);

function App() {
  return (
    <MsalProvider instance={pca}>
      <MsalAuthenticationTemplate interactionType={InteractionType.Redirect} authenticationRequest={authenticationRequest}>
          <Layout />
      </MsalAuthenticationTemplate>
    </MsalProvider>
  );
}

export default App;
```

### Reproduction Steps

Login and then check the console for error

### Expected Behavior

it should allow login

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox

### Source

External (Customer)

**Comment by sameerag** [comment]
@sandeshindi Can you please check your app'e portal configuration if it is registered as a `publicClientApplication`? The only time we encounter this error if the app is configured as `Confidential` prompting the server to throw this.

**Comment by sandeshindi** [comment]
@sameerag yes its confidential application we do not want it public . Is there a way we can resolve it if it is Confidential Application ?

**Comment by sandeshindi** [comment]
Update changed the Redirect URI in Azure AD from WEB to SPA. then it works fine

**Comment by suresh777** [comment]
@sandeshindi i am facing same issue, where should i do this change WEB to SPA
