### ISSUE TITLE
State Parameter for logout / end session requests

### ISSUE THREAD

**Issue by JosNun** [AzureAD/microsoft-authentication-library-for-js#3793]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL React (@azure/msal-react)

### Description

In the [OpenID Connect RP-Initiated Logout draft](https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RPLogout), they define a state parameter parameter that get's passed back to the RP using the `state` parameter when redirecting the User Agent back to the RP. As far as I can tell from the documentation, and from the types included with `msal-browser`, this is not currently supported.

In my particular case, the issue I am trying to resolve is to tell the client _why_ they were logged out (ie, due to inactivity, manually logging out, etc.). While this is, technically, doable by manually adding a query parameter to the post-logout redirect URI, it is discouraged by [oauth.com](https://www.oauth.com/oauth2-servers/redirect-uris/redirect-uri-registration/).

### Source

External (Customer)

**Comment by sameerag** [comment]
Yep. @JosNun we do not support `state` for logout/end session requests currently.  I am keeping this open since this is marked as a `feature` for future traction. Once we decide if we want to support it, I can update here.
