### ISSUE TITLE
Auto-renew accesstoken?

### ISSUE THREAD

**Issue by blacktea** [AzureAD/microsoft-authentication-library-for-js#380]
Does this lib automatically renew an accessToken?

**Comment by visualjeff** [comment]
acquireTokenSilent - Used to get the token from cache.  MSAL will return the cached token if it is not expired.  **Or it will send a request to the STS to obtain an access_token using a hidden iframe.**

**Comment by blacktea** [comment]
It seems that it does not have auto-reneval logic when the browser window is open.
I assume it was out of scope
