### ISSUE TITLE
Empty Hash Error while login in via pop up

### ISSUE THREAD

**Issue by Shrikan14443** [AzureAD/microsoft-authentication-library-for-js#3800]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.0

### Description

Hi,
I'm using a Azure ADB2C for my application.
When i try log in via pop up and do a tab change such as go to notepad to get email and password after adding those and clicking on login-in, I get the below error:

"BrowserAuthError: hash_empty_error: Hash value cannot be processed because it is empty. Please verify that your redirectUri is not clearing the hash. Given Url: http://localhost:4200/
    at BrowserAuthError.AuthError [as constructor] (http://localhost:4200/vendor.js:2239:24)
    at new BrowserAuthError (http://localhost:4200/vendor.js:103055:28)
    at Function.push.vgJv.BrowserAuthError.createEmptyHashError (http://localhost:4200/vendor.js:103092:16)
    at http://localhost:4200/vendor.js:13172:99
    at ZoneDelegate.invoke (http://localhost:4200/polyfills.js:9765:26)
    at Object.onInvoke (http://localhost:4200/vendor.js:61382:33)
    at ZoneDelegate.invoke (http://localhost:4200/polyfills.js:9764:52)
    at Zone.run (http://localhost:4200/polyfills.js:9527:43)
    at http://localhost:4200/polyfills.js:10669:36
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:9799:31)"

I have the redirect URI set to a page with is protected by my MSAL Guard

### MSAL Configuration

```javascript
auth:{
      clientId: AppConfigService.settings["b2cConfig"].clientId,
      authority: "https://"+ tenantName +".b2clogin.com/"+ tenantName +".onmicrosoft.com/"+ AppConfigService.settings["b2cConfig"].signUpSignIn,
      redirectUri: AppConfigService.settings["b2cConfig"].redirectUri,
      knownAuthorities: [tenantName +".b2clogin.com/"],
      postLogoutRedirectUri: AppConfigService.settings["b2cConfig"].postLogoutRedirectUri,
      navigateToLoginRequestUrl: false    
    },
    cache:{
      cacheLocation: AppConfigService.settings["b2cConfig"].cacheLocation,
      storeAuthStateInCookie: AppConfigService.settings["b2cConfig"].storeAuthStateInCookie
    }
```

### Source

External (Customer)

**Comment by tnorling** [comment]
@Shrikan14443 

> I have the redirect URI set to a page with is protected by my MSAL Guard

This is most likely why this error is being thrown. Your redirectUri will be opened in the popup when authentication is complete and if the redirectUri is auto-navigating to a different page or clearing the hash this error will be thrown. Can you try setting the redirectUri to a page that is not protected by the MSAL Guard?

**Comment by Shrikan14443** [comment]
Hi @tnorling 
i changed the redirect url and its working but when i deployed the application without using hash i get an http error and to tackle that i implemented HashLocationStrategy than im getting the below error:
ERROR BrowserAuthError: hash_does_not_contain_known_properties: Hash does not contain known properites. Please verify that your redirectUri is not changing the hash.
    at BrowserAuthError.AuthError [as constructor] (AuthError.js:27)
    at new BrowserAuthError (BrowserAuthError.js:153)
    at Function.push.vgJv.BrowserAuthError.createHashDoesNotContainKnownPropertiesError (BrowserAuthError.js:202)
    at PopupHandler.js:64
    at ZoneDelegate.invoke (zone-evergreen.js:372)
    at Object.onInvoke (core.js:28591)
    at ZoneDelegate.invoke (zone-evergreen.js:371)
    at Zone.run (zone-evergreen.js:134)
    at zone-evergreen.js:1276
    at ZoneDelegate.invokeTask (zone-evergreen.js:406)

When i try log in via pop up and do a tab change such as go to notepad to get email and password after adding those and clicking on login-in

**Comment by tnorling** [comment]
@Shrikan14443 You need to ensure the page you use as your `redirectUri` is not changing or removing the hash. This error means that the hash appended by AAD was unexpectedly replaced by something else once your application was loaded in the popup.

**Comment by Shrikan14443** [comment]
Hi @tnorling 
Actually i tried some solutions but none are working.
Basically, when we are trying with redirecturi as http://localhost:4200/ it is working but when we are enabling hashLocationStrategy and moving to another window as mentioned like notepad for signing in it is throwing an error.
Is there a way in msal to work with hashLocationStartegy i.e. http://localhost:4200/#/ in the scenario of changing tabs.
I tried in the msal samples of angular 11 v2 b2c it is also throwing the same error.
It would really help if there is anything provided by msal to work with hashLocationStrategy on changing tabs while loginPopup.

**Comment by tnorling** [comment]
@Shrikan14443 I am not able to reproduce this with our Angular 11 B2C sample, which does use the hash location strategy. Did you make any changes to the sample other than changing the interaction type to Popup [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/c9d7d774b3af38f3cad1963c0af18c19d5cce40c/samples/msal-angular-v2-samples/angular11-b2c-sample/src/app/app.module.ts#L62)?

**Comment by Shrikan14443** [comment]
Hi @tnorling 
![Screenshot (56)](https://user-images.githubusercontent.com/85301574/124056308-0f57ac00-da43-11eb-8a87-b0fd9a174a63.png)
when you try twice or thrice by changing tab to notepad and opening popup on notepad it does not work.
This is the only change i made
![image](https://user-images.githubusercontent.com/85301574/124056512-7c6b4180-da43-11eb-8d36-3abcaf17edc2.png)

**Comment by Shrikan14443** [comment]
Hi @tnorling 
I added debug on PopupHandler.js
As you can see in the below image it is getting only #/state and not the whole hash token
![image](https://user-images.githubusercontent.com/85301574/124063707-1d142e00-da51-11eb-8122-801638eb0c10.png)

**Comment by Shrikan14443** [comment]
Hi @tnorling 
I added debug on popuphandler.js and it is getting only #/state and not the contentHash token
![Screenshot (61)](https://user-images.githubusercontent.com/85301574/124063903-754b3000-da51-11eb-86be-72a32caf5ad1.png)

**Comment by Shrikan14443** [comment]
This issue is intermittent it works sometimes and it doesn't work sometimes.

**Comment by Shrikan14443** [comment]
Hi @tnorling 
When we are signing in and staying on the browser it is working.

But when we use hashEnabledRouting while signing in if i switch my login popup window to another parent window i.e. notepad and sign in and stay over notepad till the sign in completes and pop up closes than we are getting the error of hash does not contain known properties on the browser window console.

![image](https://user-images.githubusercontent.com/85301574/124109844-3505a500-da85-11eb-8fe3-d015feb72966.png)
In the pop up window you can see that only #/state is seen.
Please take a look into this issue.

**Comment by tnorling** [comment]
@Shrikan14443 Thanks, I am able to reproduce this now. What appears to be happening is that when the main window is minimized the popup window is auto navigating to the `/#/` route **before** the main window can extract the hash, creating a race condition.

To resolve this you'll need to set `initialNavigation` to `disabled` in your `app-routing.module.ts` when the app is loaded inside the popup. You can use this to check if you're in a popup window: `window.opener && window !== window.opener`.

I'll see to it that the samples are updated to take this into account. Thanks for the detailed explanation and screenshots, this really helps us get to the bottom of issues much quicker!
