### ISSUE TITLE
Not able to use ssoSilent in msal-angular v1

### ISSUE THREAD

**Issue by sanjaysarena** [AzureAD/microsoft-authentication-library-for-js#3801]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

1.4.11

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

1.1.2

### Description

HI,

I am trying to achieve an sso solution for my apps.
One uses msal-angular v2 and other uses msal-angular v1.

The flow:
User signs in using Azure b2c flow on one app->
The account preffered_username is saved in local storage for use in second app->
User clicks on a link that loads up the second add on subdomain->
On APP_INITIALIZER ssoSilent() is invoked with the saved preferred_username->

Then I get the following error on console-> 
![image](https://user-images.githubusercontent.com/42990692/123548534-b954e100-d782-11eb-96fa-2b9adacf0e13.png)

Code: 
App initializer factory on 2nd app:
![image](https://user-images.githubusercontent.com/42990692/123548568-e608f880-d782-11eb-8240-06692cb9f2b9.png)

Please help. I am not sure if this is the correct way to handle sso. Is there an easier way to get login_hint from the token cache rather than explicitly setting under a specific key?

### MSAL Configuration

```javascript
{
        auth: {
          clientId: "9a92b1f6-f329-40a3-a8cc-63386355d825",
          redirectUri: "http://localhost:8080/azureb2cAngApp",
          navigateToLoginRequestUrl: true,
          postLogoutRedirectUri: "http://localhost:8080",
          authority:'https://login.microsoftonline.com/common/',
        },
        cache: {
          cacheLocation: "localStorage",
          storeAuthStateInCookie: true,
        },
      },
      {
        popUp: false,
        protectedResourceMap: [['https://graph.microsoft.com/v1.0/me', ['user.read']]]
      }
```

### Identity Provider

Azure B2C Basic Policy

### Source

Internal (Microsoft)

**Comment by sanjaysarena** [comment]
I see that the GET call has '/undefined' at the end. Not sure what is causing this.

**Comment by tnorling** [comment]
@sanjaysarena localStorage is not shared across domains and thus I don't expect app 2 to have access to the preferred_username from app 1. Can you please confirm that this is the case? You may have to find a different way to pass the loginHint between apps.

The `/undefined` is unexpected and I'd like to understand what's happening here. Is this happening in msal-angular v1 or v2? Can you send me a network trace when this happens (email is on my profile)? Thanks.
