### ISSUE TITLE
Microsoft Authentication Library(MSAL) not working with PNPJS to create SharePoint List Item

### ISSUE THREAD

**Issue by kanakanaidu** [AzureAD/microsoft-authentication-library-for-js#3803]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

Not Applicable

### Wrapper Library Version

Not Applicable

### Description

Using below article we are trying to perform CRUD(Create, Read, Update & Delete) operations. 
[Calling SharePoint via MSAL](https://pnp.github.io/pnpjs/authentication/msaljsclient/#calling-sharepoint-via-msal)

But currently we can only access the data but not able to update/write data to SharePoint list. Here is the code snippet which we are using in our solution.
`import { MsalClientSetup  } from "@pnp/msaljsclient";
import { sp } from "@pnp/sp/presets/all";

sp.setup({
sp: {
    baseUrl: "https://{my tenant}.sharepoint.com/sites/dev/",
    fetchClientFactory: MsalClientSetup({
        auth: {
            authority: "https://login.microsoftonline.com/mytentant.onmicrosoft.com/",
        clientId: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxx",
        redirectUri: "https://mytentant.sharepoint.com/sites/dev/SitePages/test.aspx",
         },
     }, ["https://mytentant.sharepoint.com/.default"]),
 },
});
const r = await sp.web();

//create list item
await sp.web.lists.getByTitle('FoodOrder')
  .items
  .add({
    Title: 'Chicken Fry',
    Quantity: 5,
    Remarks: 'Extra Spicy'
  })
 .then(async results => {
   console.dir(results);
 })
 .catch(err => {
   console.error(err.message);
 });`

Below are the permissions granted through Azure APP. 
![MSAL App Permission](https://user-images.githubusercontent.com/37686875/123618462-da224280-d825-11eb-919b-3549c33dff5e.JPG)

When we are trying to create/update item in SharePoint list it throws the below error.
> Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))

Any ideas will be appreciated, thanks a lot.

### Error Message

> Error: Error making HttpClient request in queryable [403]  ::> {"odata.error":{"code":"-2147024891, System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))"}}}

### Msal Logs

Error: Error making HttpClient request in queryable [403]  ::> {"odata.error":{"code":"-2147024891, System.UnauthorizedAccessException","message":{"lang":"en-US","value":"Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))"}}}

### MSAL Configuration

```javascript
sp.setup({
      sp: {
        baseUrl: this.context.pageContext.web.absoluteUrl,
        fetchClientFactory: MsalClientSetup({
          auth: {
            authority: "https://login.microsoftonline.com/microsofto365competency.onmicrosoft.com/",
            clientId: "xxxxxxx-19a4-4e90-9d62-01043be04ae5",
            redirectUri: "https://mytenant.sharepoint.com/sites/SPDemo/_layouts/15/workbench.aspx",
          },
          cache: {
            cacheLocation: "sessionStorage",
          }
        }, ["https://microsofto365competency.sharepoint.com/.default"]),
      },
    });
```

### Relevant Code Snippets

```javascript
protected async onInit(): Promise<void> {
    await super.onInit();
    sp.setup({
      sp: {
        baseUrl: this.context.pageContext.web.absoluteUrl,
        fetchClientFactory: MsalClientSetup({
          auth: {
            authority: "https://login.microsoftonline.com/mytenant.onmicrosoft.com/",
            clientId: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxx",
            redirectUri: "https://mytenant.sharepoint.com/sites/SPDemo/_layouts/15/workbench.aspx",
          },
          cache: {
            cacheLocation: "sessionStorage",
          }
        }, ["https://mytenant.sharepoint.com/.default"]),
      },
    });
  }

  private async DeleteListItem(ID: number) {
    await sp.web.lists.getByTitle('orders').items.getById(ID).recycle()
      .then(results => {
        console.log(results);
      })
      .catch(err => {
        console.error(err);
      });
  }
```

### Reproduction Steps

1. Create SPFx webpart, add onInit() method and copy the code mentioned above.
2. Create DeleteListItem() method and copy the code mentioned above.
3. Call the DeleteListItem() method by passing the valid Item number.
3. Run the SharePoint workbench and check the result.

### Expected Behavior

We should be able to perform CRUD operations as per the Microsoft documentation.
[Calling SharePoint via MSAL](https://pnp.github.io/pnpjs/authentication/msaljsclient/#calling-sharepoint-via-msal)

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Internet Explorer

### Source

External (Customer)

**Comment by tnorling** [comment]
@kanakanaidu @pnp/msaljsclient is not a library we support. Can you please open an issue on their [repo](https://github.com/pnp/pnpjs/) instead?
