### ISSUE TITLE
LoginPop method is opening a microsoft login page in new tab on macbook pro (google chrome- Version 91.0.4472.114))

### ISSUE THREAD

**Issue by veenagadag** [AzureAD/microsoft-authentication-library-for-js#3811]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.0.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.0

### Description

I would like to have pop up on my existing application when I click on the login button(  login method is called )which is inside one of the dialog. But currently its opening up in new tab.
I am using macbook pro and Google chrome version - Version 91.0.4472.114
and my login() method is as follows
  public login(): void {
    this.authService.loginPopup({ scopes: authConfig.resourceScopes }).subscribe();
 }

kindly help me to get a pop up instead of moving to a new tab.

### MSAL Configuration

```javascript
export const MSALInstanceFactory = () =>
  new PublicClientApplication({
    auth: {
      clientId: authConfig.clientId,
      authority: 'https://login.microsoftonline.com/' + authConfig.tenantId,
      redirectUri: authConfig.redirectUri,
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
    },
  });
```

### Relevant Code Snippets

```javascript
public login(): void {
    this.authService.loginPopup({ scopes: authConfig.resourceScopes }).subscribe();
 }
```

### Reproduction Steps

Invoke the login() method.

### Expected Behavior

microsoft login page should pop up on the same tab where the application is opened instead of opening up in a new tab.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Safari

### Source

External (Customer)

**Comment by tnorling** [comment]
@veenagadag We were able to reproduce this. Given this is happening on all browsers on Mac we're inclined to believe there is some system setting that is causing this but have, as of yet, been unable to find it. We're looking into this and will get back to you when we have a solution or workaround.

**Comment by veenagadag** [comment]
@tnorling - Hi , Can we customize the login pop up from msal . For example if I don't want to have 'can't access your account'? in the login screen then is there a way to get rid off . Please let me know .

**Comment by tnorling** [comment]
@veenagadag I don't believe so. You can [customize the branding of the page](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/customize-branding) for your organization but I don't think you can remove individual elements. We are, however, not responsible for the sign-in pages so there may be certain features we are unaware of. These types of questions should be directed at Azure Support and they can give you a definitive answer.
