### ISSUE TITLE
Can't get AcountInfo for acquireTokenSilent

### ISSUE THREAD

**Issue by amshalev** [AzureAD/microsoft-authentication-library-for-js#3812]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

0.1.28

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

I'm trying to use acquireTokenSilent but I don't manage to get the AccountInfo which require for the silent flow.
I acquired the token successfully using ConfidentialClientApplication.acquireTokenByClientCredential with clientId and clientSecrete.
I looked on [your docs](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/accounts.md) (btw the samples links at the end of this page are broken).
If I try to get the AccountInfo from:
```
resp = await msalTokenCache.getAllAccounts();
```
I get an empty array

and if i try try to get the account from the response like that:
```
response = await msalClient.acquireTokenByClientCredential (tokenRequest);
omeAccountId = response.account.homeAccountId; 
```
response.account is null

### MSAL Configuration

```javascript
{
auth: {
clientId: this.appClientId,
clientSecret: this.appKey,
authority: this.authorityId,
}
}
```

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
@amshalev This is because the Client Credential flow authenticates an application, not a user. `acquireTokenByClientCredential` should first check the cache for tokens before going to the network. Can you please explain your scenario and why you need to call `acquireTokenSilent`?

**Comment by amshalev** [comment]
Thanks @tnorling, I guess I didn't understand correctly the usage acquireTokenSilent. 
So in any aquireToken flow the client will first check the cache, right? 
If so, can you please explain me for when should I use the acquireTokenSilent?

**Comment by tnorling** [comment]
> So in any aquireToken flow the client will first check the cache, right?

Not all acquireToken functions will do cache lookups, however, `acquireTokenByClientCredential` is one of the ones that does, as is `acquireTokenSilent`.

> If so, can you please explain me for when should I use the acquireTokenSilent?

`acquireTokenSilent` is currently only used when you are acquiring tokens for a **user** (Authorization Code flow, On Behalf Of flow, ROPC flow, etc.), hence why Account is a required parameter for that API. `acquireTokenByClientCredential` acquires a token for an **application**, not a user.

**Comment by amshalev** [comment]
Thanks!
