### ISSUE TITLE
Invalid token: aud is empty 

### ISSUE THREAD

**Issue by kirikou12** [AzureAD/microsoft-authentication-library-for-js#3819]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

1.4.4

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

1.1.2

### Description

I'm using angular msal V1 with spring boot 2.2.6.RELEASE

My frontend app generates tokens automatically that seams incorrect, because the audiance part contains only zeros:

```
{
  "aud": "00000003-0000-0000-c000-000000000000",
  "iss": "https://sts.windows.net/tenantId/",
  "iat": 1625044054,
  "nbf": 1625044054,
  "exp": 1625047954,
  "acct": 0,
  "acr": "1",
  "acrs": [
    "urn:user:registersecurityinfo",
    "urn:microsoft:req1",
    "urn:microsoft:req2",
    "urn:microsoft:req3",
    "c1",
    "c2",
    "c3",
    "c4",
    "c5",
    "c6",
    "c7",
    "c8",
    "c9",
    "c10",
    "c11",
    "c12",
    "c13",
    "c14",
    "c15",
    "c16",
    "c17",
    "c18",
    "c19",
    "c20",
    "c21",
    "c22",
    "c23",
    "c24",
    "c25"
  ],
  "aio": "ASQA2/8TAAAAzieePVG9usFKBbe8uUPs4MdqFo+/IWqHWz/cwOQW9Xc=",
  "amr": [
    "pwd"
  ],
  "app_displayname": "STORIA-REC",
  "appid": "apID",
  "appidacr": "0",
  "family_name": "xx",
  "given_name": "yy",
  "idtyp": "user",
  "ipaddr": "Z.Z.X.Y",
  "name": "zzzzzzz",
  "oid": "xxxxxxxxxxxxxxxx",
  "onprem_sid": "cccccccccccccccccccccccc",
  "platf": "3",
  "puid": "100320013A2AA9D4",
  "rh": "0.ATkAQfeKswwPHEm06rLYt6c16rvcYx5tkD5CkWlgzwnsZpY5AP4.",
  "scp": "User.Read profile openid email",
  "signin_state": [
    "kmsi"
  ],
  "sub": "_9T-AHrHom-UmgFAeATh1td2Exuyfcv8otrSyTnoCKU",
  "tenant_region_scope": "EU",
  "tid": "b38af741-0f0c-xxxxxxxxxxxxx",
  "unique_name": "xxxxxxxx",
  "upn": "xxxxxxxxxxxxxx",
  "uti": "h4Y78uU91k2DSUQGyAS5AA",
  "ver": "1.0",
  "xms_st": {
    "sub": "xxxxxxxxxxxx"
  },
  "xms_tcdt": 1111111111111
}
```

Here is my msal config:

```
MsalModule.forRoot({
      auth: {
        clientId: azureAdConfig.applicationID,
        authority: "https://login.microsoftonline.com/" + azureAdConfig.tenantID,
        validateAuthority: true,
        redirectUri: azureAdConfig.rediretUri,
        postLogoutRedirectUri: azureAdConfig.rediretUri,
        navigateToLoginRequestUrl: true,
      },
      cache: {
        cacheLocation: "localStorage",
        storeAuthStateInCookie: true,
      },
    },
      {
        popUp: false,
        consentScopes: ["User.Read.All"],
        unprotectedResources: unprotectedResource,
        protectedResourceMap: protectedResourceMap,
        extraQueryParameters: {}
      }
    )

```
Should'nt the audience contain the app id ?

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by derisen** [comment]
@kirikou12 the access token you shared looks valid -it's a token meant for Microsoft Graph (00000003-0000-0000-c000-000000000000 is the app id of MS Graph). The `aud` claim in the token will indicate the intended recipient of the access token; only in ID tokens the `aud` will be your app's app/client Id, otherwise it will be for another app/resource. See this doc for more: [resources and scopes](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/resources-and-scopes.md)

**Comment by kirikou12** [comment]
@derisen Thanks for the detailed answer.
I don't understant then why my api app is not able to validate it? I get a 401 error.

I'm using Spring Boot Starter for Azure Active Directory

pom.xml:

```
<dependency>
	<groupId>com.azure.spring</groupId>
	<artifactId>azure-spring-boot-starter-active-directory</artifactId>
	<version>3.5.0</version>
</dependency>
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-oauth2-resource-server</artifactId>
</dependency>
<dependency>
	<groupId>org.springframework.security</groupId>
	<artifactId>spring-security-oauth2-jose</artifactId>
</dependency>
```

webSecurityConfig:

```
@EnableWebSecurity
public class WebSecurity extends WebSecurityConfigurerAdapter {

  @Override
  protected void configure(HttpSecurity http) throws Exception {
    http.cors().and() // (1)
            .authorizeRequests().anyRequest().authenticated() // (2)
            .and()
            .oauth2ResourceServer().jwt(); // (3)
  }
}
```


application.properties
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://sts.windows.net/tenantId

**Comment by derisen** [comment]
@kirikou12 apologies, I wasn't exactly clear. The token you shared is a valid access token, but it is an access token for Microsoft Graph, not for your web API. So you need to request an access token for your web API by passing the scopes of your web API to the token request, like: 

```javascript
const customApiToken = await msalInstance.acquireTokenSilent({
     scopes: [ "api://<myCustomApiClientId>/My.Scope" ]
});
```

And the token you get should have the claims `aud`: "myCustomApiClientId" and `scp`: "My.Scope"

**Comment by kirikou12** [comment]
Thanks @derisen 
Ok, I will try to configure my app and on azure and test and let you know if it works.

I have another question: is it normal that I get invalid signature error when I parse jwt.io ?

**Comment by derisen** [comment]
Judging by the token you shared I wouldn't say so. Can you please use https://jwt.ms/ instead?

**Comment by kirikou12** [comment]
I used it and it shows [Signature] in green, I suppose that means the signature is ok?
I still can't understand why my api tells me that the token signature is invalid?


I've tried, as you advised me, to get an access token for my api: first I changed my azure app config. Under "expose an API" I added an id uri: api://appId/MyApiScope. Under "Authorized API" I added my api.
Now when I send the access_token to the API I get this error: 

`An error occurred while attempting to decode the Jwt: Signed JWT rejected: Invalid signature`

**Comment by derisen** [comment]
@kirikou12 If you can parse your access token on https://jwt.ms/ and you see the claims as should be (correct `aud` and `scp` etc.), then it must be something do with the validation logic on the web API side. Unfortunately I'm not familiar with the Spring Boot Starter. May I suggest you to take this issue to the [ms-identity-java-spring-tutorial](ms-identity-java-spring-tutorial) repo?

Before doing so though, I would also suggest going through this tutorial on the same repo: [protecting a web API](https://github.com/Azure-Samples/ms-identity-java-spring-tutorial/tree/main/3-Authorization-II/protect-web-api), which shows how to properly configure Spring Boot Starter to validate incoming access tokens.

**Comment by kirikou12** [comment]
@derisen I finally got it working locally. I just forgot to add my scope in the protected resources map like this:

```
protectedResourceMap:[
    ['https://localhost:44389/weatherforecast, ['api://5e971e5c-a661-4d82-ba97-935480492129/access_as_user']],
    ['https://graph.microsoft.com/v1.0/me, ['user.read']]
  ],
```

But when I deploy my app on production env, I get a 401 error. Is there a sepcic config when passing from http to https ?

**Comment by derisen** [comment]
@kirikou12 are you saying that when you deploy both your SPA and the web API behind https, calls to the web API result in 401 error? Hard to say before knowing more about the error: Anything in the console on the web API side? Regardless, there should be no special configs on the SPA side, so I would say you should look into Spring Boot Starter configuration. Again, I can't help much with Spring.
