### ISSUE TITLE
404 Not Found: @azure/msal-angular@0.1.0

### ISSUE THREAD

**Issue by Wigent** [AzureAD/microsoft-authentication-library-for-js#382]
Running `npm install @azure/msal-angular --save` triggers an error: ERR! 404 Not Found: @azure/msal-angular@0.1.0

I found that others have the same error but they're on the Dev branch. I just got mine from the Master branch. Any thoughts?

Thank you in advance.

**Comment by penkin** [comment]
I'm having the same issue. There are no packages in NPM. Is there another way to install the package?

**Comment by nehaagrawal** [comment]
@Wigent @penkin  Released.
