### ISSUE TITLE
Storing scope in Storage

### ISSUE THREAD

**Issue by yakimko** [AzureAD/microsoft-authentication-library-for-js#383]
Hi!
Sometimes an accessTokenKey that stores stringified data
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/src/UserAgentApplication.ts#L1488
contains a scopes value like below.

`
{"authority":"....","clientId":"...","scopes":"https%3a%2f%2f{some_tenant}%2f{some_app}%2fuser.read","userIdentifier":"..."}
`

As you can see the url is encoded by encodeURIComponent.
because of this when I want to get a cashed token it could not be found because comparing 2 strings
https%3a%2f%2f{some_tenant}%2f{some_app}%2fuser.read and https://{some_tenant}/{some_app}/user.read

**Comment by nehaagrawal** [comment]
@yakimko  We don't expect the users of the library to read the local storage entry for getting the cached token. Could you please tell us what is your use case?
