### ISSUE TITLE
Msal SSO with Teams Javascript SDK

### ISSUE THREAD

**Issue by rhalaly** [AzureAD/microsoft-authentication-library-for-js#3830]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.15.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.1

### Description

We are developing a web app that is accessible from the browser and everything works fine. But we want to be able to use our web app as Teams Tab App as well.

For Teams Tab App, we have to use the Teams JavaScript SDK client, which managing the authentication as well with their `microsoftTeams.authentication.getAuthToken`

Is there any way to be able to do SSO if the app runs inside Teams Tab App, but keep it working regularly in the browser itself?

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by derisen** [comment]
@rhalaly  It's unlikely that you'll be able to use the same code for both browser and Teams environments -you'll have to make use of Teams JavaScript SDK client as you mention. For doing SSO in a Teams Tab app, you can use MSAL in conjunction with Teams JS SDK. See [this sample](https://github.com/pnp/teams-dev-samples/tree/main/samples/tab-sso/src/nodejs) for an implementation. Also good to check: [Silent login with ssoSilent()](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/login-user.md#silent-login-with-ssosilent)

**Comment by rhalaly** [comment]
I don't need a deep integration. It is more for being able to be displayed inside Teams as a Tab. 

About the `ssoSilent()`, I'm using the `msal-react` lib and use `MsalAuthenticationTemplate` for the login. I didn't dig inside the source code but I want to believe that it uses `ssoSilent` first before the acutal interaction.

**Comment by derisen** [comment]
> I don't need a deep integration. It is more for being able to be displayed inside Teams as a Tab.

@rhalaly not sure how this relates to msal then. You can display web page in Teams as a tab in general. You'll need to look into Teams app development for more on this. Keep in mind that you can achieve sso between apps on the same domain if you [configure msal to use localStorage](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/configuration.md#cache-config-options)

> About the `ssoSilent()`, I'm using the `msal-react` lib and use `MsalAuthenticationTemplate` for the login. I didn't dig inside the source code but I want to believe that it uses `ssoSilent` first before the acutal interaction.

`MsalAuthenticationTemplate` does not use `ssoSilent()` API by default, you'll need to [configure it to do so](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/getting-started.md#msalauthenticationtemplate-component). For a silent sso request to succeed, you'll need to provide either a login hint, a session id or an account object (of course, the user also needs to have an active session with the AAD)

**Comment by rhalaly** [comment]
@derisen sorry if some context was missing. I have a web app that has a protected area that the user must login to see it. I want to show one of the protected pages in the Microsoft Teams Tab.
Microsoft Team handles the authentication for its tabs and with Teams Javascript SDK Client you can get the login info. 

But in some cases, MSAL doesn't see that Teams already authenticated and redirects the user to the Microsoft Login page inside the tab, which is an undesired behavior.

I want to let MSAL know somehow that the user is logged in in Teams and prevent the MSAL login in that case.

> rhalaly not sure how this relates to msal then. You can display web page in Teams as a tab in general. You'll need to look into Teams app development for more on this. Keep in mind that you can achieve sso between apps on the same domain if you configure msal to use localStorage

Unfortunately, `localStorage` can do so between **tabs** in the same browser only, so it doesn't work in that case.

**Comment by derisen** [comment]
@rhalaly sounds like the [sample](https://github.com/pnp/teams-dev-samples/tree/main/samples/tab-sso/src/nodejs) I shared covers your use-case here. Are you having this issue with the sample? If the user has an active session with Azure AD, the `ssoSilent()` API would be able to leverage that. The login page you mention shouldn't require user to enter credentials, only to choose an account (which you can bypass by providing a `loginHint`).

**Comment by rhalaly** [comment]
I will try it. I will close the issue now. Thank you!
