### ISSUE TITLE
MSAL logout doesn't land me on microsoft logout page

### ISSUE THREAD

**Issue by r4hulp** [AzureAD/microsoft-authentication-library-for-js#3831]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.15.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.1

### Description

Hi,

I am using Angular wrapper of MSAL.js v2 in one of my clients' applications. We have a logout button, click on which should redirect the user to the Microsoft identity page where the user can select which account to log out from, and then it should redirect to the post logout redirect URL. 

Right now, when I call `.logoutRedirect()` or ',logout()` the app redirects back to its root.. It skips the intermediate step where we can choose an account that the user wants to log out from.

I have also configured **Front-channel logout URL** in Azure but no luck here as well.. 

I am not sure what am I missing. 

### MSAL Configuration

```javascript
auth:{
        "clientId" : "{client_id}",
        "authority": "https://login.microsoftonline.com/{tenant_id}",
        "redirectUri" : "http://localhost:4200/auth-callback",
        "postLogoutRedirectUri" : "https://localhost:4200/logout"
    }
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by derisen** [comment]
@r4hulp have you registered your `postLogoutRedirectUri` as a Redirect URI (in addition to `http://localhost:4200/auth-callback`). Is there any argument you are passing to [logout()](url) or [logoutRedirect()](url) (in [particular](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md#skipping-the-server-sign-out))? Btw, your `redirectUri` is on *http*, can you try using *https* as in your `postLogoutRedirectUri` and see if it helps?

Also, sharing msal logs would be helpful here ([set the logger to Verbose](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/configuration.md#logger-config-options)).
