### ISSUE TITLE
MSAL with Windows Virtual Desktop (WVD)

### ISSUE THREAD

**Issue by hhertogh** [AzureAD/microsoft-authentication-library-for-js#3832]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

1.1.3

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

Hello,
I opened this question a month ago but it was closed without answer (https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/3715).
We have a VueJS application which is using MSALJS to make use of the Azure AD authentication in a corporate environment (we enforce MFA for our users).
Our application is working perfectly in our offices but recently we began to work with Windows Virtual Desktops.
There we have issues with the login as users are not requested to enter the MFA codes (we have conditional access policies). It's not asked while in the office it's asked and working correctly. When surfing to office.com , logging in, mfa code, authenticated, going back to our custom application, then it's ok, so I'm suspecting something with the claims that is not correctly set for WVD.
Anyone experiencing similar issues ?
Thanks.

### MSAL Configuration

this.msalConfig = {
          auth: {
            clientId: Configuration.value('VUE_APP_AZURE_APP_ID'),
            redirectUri: redirectUri,
            authority: `https://login.microsoftonline.com/${Configuration.value('VUE_APP_AZURE_TENANT_ID')}`
          },
          cache: {
              cacheLocation: "sessionStorage", // localStorage works too
              storeAuthStateInCookie: true
          }
      };

this.graphScopes = {
        scopes: [`api://${Configuration.value('VUE_APP_AZURE_APP_ID')}/access_as_user`], // Pass an array of scope strings to the graphScopes object
        extraQueryParameters: {
          claims: '{"access_token":{"capolids":{"essential":true,"values":["id1","id2"]}}}',
        },
      };

### Source

External (Customer)

**Comment by sameerag** [comment]
@hhertogh Sorry the original issue is closed as there was no response from server team. MSAL JS cannot solve this issue. I will keep the issue #3715 open and send a reminder, closing this one.
