### ISSUE TITLE
Does msal.js support ADFS 2016?

### ISSUE THREAD

**Issue by RomanHubyak** [AzureAD/microsoft-authentication-library-for-js#3839]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

none yet

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

none yet

### Description

I found the mention about ADFS 2019 support (https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/99) but there is no information about other versions of ADFS. So, does msal.js support ADFS 2016?

### Source

External (Customer)

**Comment by sameerag** [comment]
@RomanHubyak We do not. We support any federated ADFS flow, as long as AAD supports it. For direct endpoints, we only support ADFS 2019, since it is OIDC compliant.

**Comment by RomanHubyak** [comment]
Thanks!
