### ISSUE TITLE
TypeError: cannot read property initializeWrapperLibrary of undefined

### ISSUE THREAD

**Issue by jcox86** [AzureAD/microsoft-authentication-library-for-js#3842]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.15.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.1

### Description

I have upgraded to the latest versions of Angular 12 and msal packages coming from Angular 11 and @azure/msal-angular 1.1.1 (no @azure/msal-browser) where everything worked fine.

I have added in all code from the Angular 12 sample and tweaked to meet my needs.  The application builds just fine (`ng build`) and I can successfully serve the app up (`ng serve`).  However, when I navigate to `localhost:4200` the app cannot make it past my splash screen and does not reach the landing page (no msal guard).  The console always shows the following error message.

Investigating deeper in the compiled code, it is failing from the following spot `webpack:///./node_modules/@azure/msal-angular/__ivy_ngcc__/fesm2015/azure-msal-angular.js:36` where the code is supposed to call `initializeWrapperLibrary` at the end of the constructor.  Adding a breakpoint here in the Chrome Dev Tools does in fact show that `this.instance` is undefined, which is passed to the constructor on line 29.

Looking down further on line 86 (same file) you define the ctorParameters and do register the type as `undefined` and inject the MSAL_INSTANCE in its place.  Somehow this is failing to register or get picked up from my `app.module.ts`?

What would cause the `instance` that is passed into the MsalService constructor to be undefined?  Would this be a configuration issue somewhere?  Where is the instance passed in from?

### Error Message

```
main.ts:23 TypeError: Cannot read property 'initializeWrapperLibrary' of undefined
    at new MsalService (azure-msal-angular.js:36)
    at Object.MsalService_Factory [as factory] (azure-msal-angular.js:84)
    at R3Injector.hydrate (core.js:11416)
    at R3Injector.get (core.js:11236)
    at injectInjectorOnly (core.js:4728)
    at Module.ɵɵinject (core.js:4732)
    at Object.MsalBroadcastService_Factory [as factory] (azure-msal-angular.js:120)
    at R3Injector.hydrate (core.js:11416)
    at R3Injector.get (core.js:11236)
    at injectInjectorOnly (core.js:4728)
```
![image](https://user-images.githubusercontent.com/4613034/124801742-07e54680-df0c-11eb-90bb-b0dd37da8293.png)

### MSAL Configuration

```javascript
{
                    auth: {
                        clientId: environment.clientId, // Prod enviroment. Uncomment to use.
                        postLogoutRedirectUri: '/'
                    },
                    cache: {
                        cacheLocation: BrowserCacheLocation.SessionStorage
                    },
                    system: {
                        loggerOptions: {
                            logLevel: LogLevel.Verbose,
                            piiLoggingEnabled: false
                        }
                    }
                }
```

### Relevant Code Snippets

```javascript
public subscribeToMsalService(): void {
        this.subs.add(
            this.bs.msalSubject$.pipe(filter((message: EventMessage) => message.eventType === EventType.LOGIN_FAILURE)).subscribe((error) => {
                this.ms.showToastError({ header: 'Log In Failure', description: error.error?.message || '' });
            }),
            this.bs.msalSubject$.pipe(filter((message: EventMessage) => message.eventType === EventType.ACQUIRE_TOKEN_FAILURE)).subscribe((error) => {
                this.ms.showToastError({ header: 'Acquire Token Failure', description: error.error?.message || '' });
            }),
            this.bs.msalSubject$.pipe(filter((message: EventMessage) => message.eventType === EventType.SSO_SILENT_FAILURE)).subscribe((error) => {
                this.ms.showToastError({ header: 'SSO Failure', description: error.error?.message || '' });
            }),
            this.bs.msalSubject$.pipe(filter((message: EventMessage) => message.eventType === EventType.LOGIN_SUCCESS)).subscribe((event) => {
                this.setUserOnLoginSuccess(event);
            }),
            this.bs.msalSubject$.pipe(filter((message: EventMessage) => message.eventType === EventType.ACQUIRE_TOKEN_SUCCESS)).subscribe((event) => {
                this.setUserOnLoginSuccess(event);
            })
        );
        this.msal.handleRedirectObservable().subscribe((result: AuthenticationResult) => {
            if (result.account?.username) {
                this.ms.showToastSuccess({ header: 'Successfully Logged In', description: '' });
            }
        });
    }
```

### Reproduction Steps

1. Add sample from Angular 12
2. Run `ng serve`
3. Open browser developer tools
4. Observe console logs

### Expected Behavior

Application continues through the splash page (index.html) and hits the landing page (no msal guard).  Application functions (login) function as normal.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Regression

@azure/msal-angular@1.1.1

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@jcox86 Can you please share a repo that includes a sample app that reproduces your issue? Thanks!
