### ISSUE TITLE
PKCE for msal-node auth code flow with confidential client best practise?

### ISSUE THREAD

**Issue by DevRCRun** [AzureAD/microsoft-authentication-library-for-js#3847]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.2.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

I am assuming playing with the below samples that the implementation should be largely the same for a confidential client?

[1] https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/auth-code
[2] https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/auth-code-pkce

The samples both appear to still work if I switch in ConfidentialClient per the docs for the auth-code demo

Playing with [3] https://github.com/microsoftgraph/msgraph-training-nodeexpressapp and having read https://oauth.net/2/grant-types/authorization-code/ I gather it is sensible to use PKCE for auth-code even in the case of a confidential client? Can I check my understanding of that is correct?

I've added the PKCE code from [2] to [3] and all seems to work fine testing locally with only a single user. But I can spot a possible problem with doing this, but before I move on to ask about that can I check if my understanding up to this point is correct? Many thanks in advance!

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by sameerag** [comment]
@DevRCRun PKCE can be used by all clients (Confidential & Public). We did not specify samples for confidentialClient since we do not have too many clients using PKCE on `ConfidentialClientApplication`.
We can add the support, however. 

Can you please elaborate the possible problem you envision here?

**Comment by DevRCRun** [comment]
@sameerag thanks for your reply, it would be a helpful clarification in the samples for me, given that the Oauth site and various MS pages recommend PKCE for both client types (unless I'm reading them wrong?)

The query I have may be a flaw in my understanding of the flow in the auth code PKCE example.

First the PKCE code object is initialised:

     // Set up PKCE Code object in app's local memory so it's shared between routes
     app.locals.pkceCodes = {
     challengeMethod: 'S256', // Use SHA256 Algorithm
     verifier: '', // Generate a code verifier for the Auth Code Request first
     challenge: '' // Generate a code challenge from the previously generated code verifier
    }

Then in the route that kicks off the first leg the verifier and challenge are generated for the request and the PKCE code object updated

    // Initialize CryptoProvider instance
    const cryptoProvider = new msal.CryptoProvider()

    // Generate PKCE Codes before starting the authorization flow
    const { verifier, challenge } = await cryptoProvider.generatePkceCodes()

    // Set generated PKCE Codes as app variables
    app.locals.pkceCodes.verifier = verifier
    app.locals.pkceCodes.challenge = challenge

In the redirect route the previously generated codeVerifier from the PKCE code object is again supplied for the second leg

    // Add PKCE code verifier to token request object
    const tokenRequest = {
        code: req.query.code,
        scopes: ["user.read"],
        redirectUri: "http://localhost:3000/redirect",
        codeVerifier: app.locals.pkceCodes.verifier, // PKCE Code Verifier
        clientInfo: req.query.client_info
    };

My understanding is that the codeVerifier needs to match otherwise Azure will reject the transaction? (if I take codeVerifier out of tokenRequest this indeed seems to be what happens).

What I'm confused about, is on a busy enough app I feel it might be possible for another request to hit the first route before the users browser hits the redirect route. Because the verifier and challenger appear to be overwritten in app.locals by the first route, the verifier taken from app.locals and used in the redirect route would then be different from that generated for the corresponding initial request.

Otherwise I think I must be misunderstanding how things work behind the scenes?

Thanks for your time

**Comment by derisen** [comment]
@DevRCRun you're basically right. The sample is using `app.locals` since it's primarily meant for testing and not for actual usage (and also to avoid having an extra dependency), but in reality you should consider using a session solution that would allow you to store these variables on a user/request basis. We'll consider revising the samples to make this point clear.

**Comment by DevRCRun** [comment]
Thanks for the clarification, a note in the sample would be helpful.

**Comment by sameerag** [comment]
@DevRCRun Thank you for the feedback.
@derisen Let's note this in the sample work we are planning. Closing this.
