### ISSUE TITLE
Client ID? Or AppID URL?

### ISSUE THREAD

**Issue by mbearup** [AzureAD/microsoft-authentication-library-for-js#3848]
When configuring the server, the guidance here and [here](https://github.com/Azure-Samples/active-directory-node-webapi-basic) say to use the **client ID,** which is clarified in both cases to mean the **Application ID**. But in my testing, I actually had to provide the "**App ID URL**." If I provided the Application ID, my client would get a 401 error indicating that the audience is invalid. Which makes sense - the server is expecting tokens for a GUID and the client is providing a token that's valid for a URL. In turn if I configure my client to use the server's Application ID instead of App ID URL, I get an error from AAD indicating that the token cannot be issued.
- So am I the only one that's stumbled over this? Should the docs be updated to say App ID URL?
- Or am I doing something wrong in the server side config?
- In my case, my server's identity is an AAD "App Registration" but maybe these directions are for "Enterprise Applications" which have different rules/IDs?

Thanks,

**Comment by sameerag** [comment]
Track this for the new middleware - if we still need to support the App ID URL. Need clarity from portal/app model teams.

**Comment by jasonnutter** [comment]
Documentation for how to set audience claim for new Node Token Validation library will be tracked internally in ADO, closing. @jo-arroyo
