### ISSUE TITLE
Multi ClientID B2C

### ISSUE THREAD

**Issue by MonksterFX** [AzureAD/microsoft-authentication-library-for-js#3850]
We have an B2C instance and multiple applications. Our Api should accept any token of these applications. 

```json
"settings": {
    "isB2C": true,
    "validateIssuer": true,
    "issuer": "https://<domain>.b2clogin.com/<tenantID>/v2.0/",
    "audience": [
        "GUID1",
        "GUID2"
    ],
}
```

Which didnt't work. Just the Token from the application set in "clientID" worked. But I was curious and changed clientID to:

```json
  "credentials": {
    "tenantName": "<tenant>",
    "clientID": [
        "GUID1",
        "GUID2"
    ]
  },
```

Strangly that worked, altough the documentation states that clientID should be a string. Is this intentional or how can this be achieved.

**Comment by sameerag** [comment]
@jo-arroyo Are we tracking this scenario for the node-validation library?

**Comment by jasonnutter** [comment]
Ability to validate tokens for multiple audiences will be in the new Node Token Validation library, closing.
