### ISSUE TITLE
Update dependency on `https-proxy-agent` (and, transitively, `base-agent`)

### ISSUE THREAD

**Issue by mpsijm** [AzureAD/microsoft-authentication-library-for-js#3851]
The version of `base-agent` that this package currently uses as a dependency, patches Node's core `https.request` method, causing trouble in unrelated code: https://github.com/TooTallNate/node-agent-base/issues/35

This has been fixed in [`agent-base`@5.0.0](https://github.com/TooTallNate/node-agent-base/releases/tag/5.0.0), and `https-proxy-update` bumps their dependency on this package in [version 4.0.0](https://github.com/TooTallNate/node-https-proxy-agent/compare/3.0.1...4.0.0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R26).

In one of my own projects, I have manually set the dependency for `https-proxy-update` to 5.0.0 by editing `package-lock.json`, and it all still seems to work.

**Comment by jo-arroyo** [comment]
`https-proxy-agent` has been updated to version 5.0.0 in [this PR](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/3996) and will be available in the next release.
