### ISSUE TITLE
Error: In Strategy.prototype.jwtVerify: cannot verify token

### ISSUE THREAD

**Issue by pascalgn** [AzureAD/microsoft-authentication-library-for-js#3852]
We are using permission `user_impersonation` for our app registration when requesting an access token (`scope=api://123-our-client-id-456/user_impersonation`) and we get the following error:
```
authentication failed due to: In Strategy.prototype.jwtVerify: cannot verify token
```

When adding `loggingNoPII: false` to our config, we also see the following error:
```
authentication failed due to: jwt audience is invalid
```

**Comment by sameerag** [comment]
@pkanher617 to track this for the new version

**Comment by jasonnutter** [comment]
Audience claim will be set explicitly in new Node Token Validation library, closing.
