### ISSUE TITLE
ReferenceError: state is not defined

### ISSUE THREAD

**Issue by emmansun** [AzureAD/microsoft-authentication-library-for-js#3853]
We used 4.0.0, but it seems the issue is still there in latest version.

![image](https://user-images.githubusercontent.com/7235232/122320280-95102d80-cf54-11eb-85c8-15064962ad94.png)

![image](https://user-images.githubusercontent.com/7235232/122320426-c2f57200-cf54-11eb-9cba-1ecfa5ec439c.png)

**Comment by sameerag** [comment]
We will work on a repro and get back.

**Comment by jo-arroyo** [comment]
Closing as passport-azure-ad is in maintenance and no longer receiving updates. Future middleware scenarios will be built on top of msal-node, where this issue will be addressed. Keep an eye out for msal-node updates.
