### ISSUE TITLE
Readme.md for msal-node states that the confidential client supports username and password flow

### ISSUE THREAD

**Issue by larskaare** [AzureAD/microsoft-authentication-library-for-js#3858]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

4.3.0

### Wrapper Library

MSAL Node Extensions (@azure/msal-node-extensions)

### Wrapper Library Version

1.1.0

### Description

The readme.md file for msal-node states that the confidential client support the username and password flow.

(https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-node#confidential-client)

The support for this would be very nice for testing purposes, but either the readme file is wrong or I am missing something?

### MSAL Configuration

```javascript
.
```

### Relevant Code Snippets

```javascript
.
```

### Reproduction Steps

.

### Expected Behavior

.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@larskaare Apologies for the confusion. Support for this is currently in PR review: https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/3838

**Comment by larskaare** [comment]
Ok,no problem @jasonnutter Any ETA for when this will be available?

**Comment by sameerag** [comment]
@larskaare This is merged now and we plan to make a release early next week for `msal-node`.
