### ISSUE TITLE
No information about @azure/msal-angularjs

### ISSUE THREAD

**Issue by ashinzekene** [AzureAD/microsoft-authentication-library-for-js#3860]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

None

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

I can get any up-to-date information concerning [@azure/msal-angularjs](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/052f3c3d98acce53852d441a0c9a87930a011a43/lib/msal-angularjs). The README says it's in preview, but it was last updated about 3 years ago, the folder has also been removed from the `dev` branch. I just want to know if it's fine to use it. We're updating an application using angularjs from ADAL to MSAL

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by jasonnutter** [comment]
@ashinzekene Apologies for the confusion. We have moved the code for `msal-angularjs` to the `maintenance` folder, as it is currently deprecated: https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/maintenance/msal-angularjs

We encourage developers to use MSAL.js v2 and if possible, upgrade to Angular and use MSAL Angular v2.

**Comment by ashinzekene** [comment]
Alright, thank you!
