### ISSUE TITLE
reproduce refresh token has expired error

### ISSUE THREAD

**Issue by omri08** [AzureAD/microsoft-authentication-library-for-js#3863]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.15.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.1

### Description

After more than 24 hours I wasn't active (but I was still logged in), I received `the refresh token has expired due to maximum lifetime` error when `acquireTokenSilent` was called.
Now Im trying to reproduce this error so I will be able to test and fix this when it happens.
Is there an option to somehow fake/make this error to happen again without waiting 24 hours?

I tried to change the time for each object in my localStorage that has these attributes `expiresOn`, `extendedExpiresOn`, `cachedAt` but it didnt helped.

### MSAL Configuration

```javascript
const msalConfig = {
  auth: {
    clientId: myId,
    redirectUri: '/',
    postLogoutRedirectUri: '/',
  },
  cache: {
    cacheLocation: 'localStorage',
  },
};
```

### Relevant Code Snippets

```javascript
export const getTokenAsync = async (resource: ResourceType) => {
  const request = getRequestByResource(resource);
  const account = authContext.getActiveAccount() ?? authContext.getAllAccounts()[0];
  const response = await authContext.acquireTokenSilent({ ...request, account });
  return response.accessToken;
};
```

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by jasonnutter** [comment]
@omri08 Unfortunately, there isn't an easy to trigger this, as the library intentionally relies on AAD to inform us if an RT is no longer valid. 

Our guidance is to check the error class type for `InteractionRequiredAuthError`: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/15b76527f1efb056edd212bc7a84f849c08ae4a6/samples/msal-browser-samples/VanillaJSTestApp2.0/app/default/auth.js#L72
