### ISSUE TITLE
Upgrading msal v1.3.2 -> v1.3.3

### ISSUE THREAD

**Issue by paulmorar** [AzureAD/microsoft-authentication-library-for-js#3864]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

1.3.3

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

Upgrading msal dependency from 1.3.2 to 1.3.3 introduces breaking changes in functionality. As far as I observed, there is a new call to https://login.microsoftonline.com/common/discovery/instance which gets introduced, and that call is the one that fails, breaking the functionality.

### MSAL Configuration

```javascript
auth: {
    clientId: stringClientID,
    authority: `https://login.microsoftonline.com/tfp/${tennant}/${policy}`,
    redirectUri: redirectURI,
    postLogoutRedirectUri: logoutRedirectURI,
    navigateToLoginRequestUrl: true,
  },
  cache: {
    cacheLocation: 'sessionStorage',
    storeAuthStateInCookie: false,
  }
```

### Identity Provider

Azure B2C Custom Policy

### Source

Internal (Microsoft)

**Comment by jasonnutter** [comment]
@paulmorar Please add `login.microsoftonline.com` to the `knownAuthorities` array to mitigate. Example: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-core-samples/VanillaJSTestApp/app/b2c/authConfig.js#L6

cc @tnorling

**Comment by paulmorar** [comment]
@jasonnutter You are correct. It seems I overlooked that. Thank you for the prompt reply!

Cheers
