### ISSUE TITLE
Extra redirect to a current page when route is changed.

### ISSUE THREAD

**Issue by jonybekov** [AzureAD/microsoft-authentication-library-for-js#3865]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.15.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

Recently, I've migrated from msal v1.x to @azure/msal-browser. In the msal v1.x I had issue with Firefox where after loginRedirect page redirected to wrong url. It worked good on localhost but failed at staging preview. After migrating to msal-browser it correctly navigates to a page where login requested and there's no issue on Firefox. But now embed page where I integrated auth with PowerBI embed is redirecting to a page with hash every time when I refresh the page or navigate from another route. In the console it's showing me _BrowserAuthError: interaction_in_progress. acquireTokenSilent fails._ error.

Here as you can see when I navigate to analytics page token acquition happens silently and doesn't change url hash. It works as I expected.
[Using msal v1.x](https://drive.google.com/file/d/1GTZJ1ElIso10raxFD-F91FalE0yZc0Cs/view?usp=sharing)

In the screencapture below where I used @azure/msal-browser, every time I navigate to analytics page, route hash is changing and page is reloading. You can see it in address bar.
[Using @azure/msal-browser](https://drive.google.com/file/d/1gGCzNbOYY8ouf0U8W5oiMnl6Dg1vyvQS/view?usp=sharing)

All I want to provide the UX shown in the first gif.

### Error Message

```
BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.  For more visit: aka.ms/msaljs/browser-errors.
    AuthError AuthError.ts:40
    BrowserAuthError BrowserAuthError.ts:151
    node_modules vendors~main.chunk.js:4923
    node_modules vendors~main.chunk.js:1764
    node_modules vendors~main.chunk.js:700
    step vendors~main.chunk.js:198
    verb vendors~main.chunk.js:129
    __awaiter vendors~main.chunk.js:101
    __awaiter vendors~main.chunk.js:80
    node_modules vendors~main.chunk.js:684
    getTokenRedirect auth-msal-browser.ts:52
    signInRedirect auth-msal-browser.ts:60
    auth auth-msal-browser.ts:82
```

### Msal Logs

N/A

### MSAL Configuration

```javascript
const config: Configuration = {
  auth: {
    authority: `https://login.microsoftonline.com/${MsalConfig.Azure_AAD}`,
    clientId: MsalConfig.ClientId,
    navigateToLoginRequestUrl: true,
  },
  cache: {
    cacheLocation: 'localStorage',
    storeAuthStateInCookie: true,
  },
};
```

### Relevant Code Snippets

```javascript
const authenticationParameters = {
  scopes: [
    'https://analysis.windows.net/powerbi/api/App.Read.All',
    'https://analysis.windows.net/powerbi/api/Dataset.Read.All',
    'https://analysis.windows.net/powerbi/api/Dashboard.Read.All',
    'https://analysis.windows.net/powerbi/api/Report.Read.All',
  ],
};

const msalObj = new PublicClientApplication(config);

const getTokenSilent = async (): Promise<string> => {
  try {
    const response: AuthenticationResult = await msalObj.acquireTokenSilent(
      authenticationParameters
    );

    return response.accessToken;
  } catch (e) {
    console.error(
      'silent token acquisition fails. acquiring token using redirect'
    );
    return;
  }
};

const getTokenRedirect = async (): Promise<void> => {
  try {
    return await msalObj.acquireTokenRedirect(authenticationParameters);
  } catch (error) {
    console.error('acquireTokenRedirect:', error);
  }
};

const signInRedirect = async (): Promise<string | void> => {
  try {
    await getTokenRedirect();

    const tokenResponse = await msalObj.handleRedirectPromise();

    if (!tokenResponse) {
      return await msalObj.loginRedirect(authenticationParameters);
    }

    return tokenResponse.accessToken;
  } catch (err) {
    console.error(err);
  }
};

export const auth = async (): Promise<string | void> => {
  try {
    // Try to get token silently
    const token = await getTokenSilent();

    if (token) {
      return token;
    }

    return await signInRedirect();
  } catch (err) {
    console.error('Error', err);
  }
};

// Then in somewhere of my component I am calling that auth method.

useEffect(() => {
   auth().then(token => 
      if(token) getReport(token)
   ); 
}, [])
```

### Reproduction Steps

1. Try to call acquireTokenSilent
2. If it fails then call getTokenRedirect where redirect promise is handled

### Expected Behavior

I want redirect to happen only when user is not signed in. In other cases it should get tokens silently so that user won't notice it. This behaviour is already working on msal v1.x. But I had to migrate to v2.x due to some bugs on Firefox.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari

### Regression

msal v1.4.9

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@jonybekov First thing is that if your app uses redirect-based interaction, `handleRedirectPromise` should be invoked on every page load, not only when you are about to perform a redirect operation.

Generally speaking, the flow should look like:

1. On page load, invoke `handleRedirectPromise` (this will process any in progress interactive requests), and await the response.
2. When `handleRedirectPromise`, you can perform other MSAL operations.
3. Check to see if the user is logged in. If not, prompt them to login.
4. If they are logged in, call `acquireTokenSilent` right before you need an access token.
5. If this fails with an interaction/login/consent required error, perform interaction to get a new token.

**Comment by jasonnutter** [comment]
@jonybekov First thing is that if your app uses redirect-based interaction, `handleRedirectPromise` should be invoked on every page load, not only when you are about to perform a redirect operation.

Generally speaking, the flow should look like:

1. On page load, invoke `handleRedirectPromise (this will process any in progress interactive requests), and await the response.
2. When

**Comment by jasonnutter** [comment]
Furthermore, if you are using React, we highly suggest looking at our MSAL React wrapper library, which provides nice abstractions for this logic.

**Comment by jonybekov** [comment]
Thank you. I've managed it using hooks and it works pretty well.
