### ISSUE TITLE
loginRedirect fails when angular index.html base href is different from the origin

### ISSUE THREAD

**Issue by Rishanthakumar** [AzureAD/microsoft-authentication-library-for-js#3869]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.15.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.1

### Description

Msal login fails if the base href of the angular index.html is different from origin URL.

### Error Message

Failed to execute 'replaceState' on 'History': A history state object with URL 'https://cdn-url/redirect' cannot be created in a document with origin 'http://localhost:4202' and URL 'http://localhost:4202/redirect'.

### MSAL Configuration

```javascript
auth: {
	clientId: environment.msal.clientId,
	authority: b2cPolicies.authorities.signUpSignIn.authority,
	redirectUri: 'http://localhost:4202/redirect',
	postLogoutRedirectUri:  'http://localhost:4202/logout',
	knownAuthorities: [b2cPolicies.authorityDomain],
	navigateToLoginRequestUrl: false
},
cache: {
	cacheLocation: BrowserCacheLocation.SessionStorage,
	storeAuthStateInCookie: false,
	secureCookies: false
},
system: {
	loggerOptions: {
		loggerCallback,
		logLevel: LogLevel.Verbose,
		piiLoggingEnabled: true
	},
	windowHashTimeout: 9000, // Applies just to popup calls - In milliseconds
	iframeHashTimeout: 9000, // Applies just to silent calls - In milliseconds
	loadFrameTimeout: 9000 // Applies to both silent and popup calls - In milliseconds
}
```

### Relevant Code Snippets

In index.html file:

```javascript
<base href="https://cdn-url/">

OR

ng build -c=qa --base-href https://cdn-url/
```

### Reproduction Steps

1.  Change the angular project index.html base href to the following: `<base href="https://cdn-url/">` or build the app using 
`` ng build -c=qa --base-href https://cdn-url/ `` (make sure that applications assets and js files  can loaded from the given base href)

2. Try to login using loginRedirect

### Expected Behavior

Login should work successfully regardless of the base href set to the index.html file.

I did a bit of debugging in the library level and found that BrowserUtil.js clearHash function uses the following way to replace the current content window history state:

```javascript
contentWindow.history.replaceState(null, Constants.EMPTY_STRING, "" + contentWindow.location.pathname + contentWindow.location.search);
```

This replaces the state with "https://cdn-url/redirect" since it gets the origin url from the base href of html document. Where this causes a DOMException with the following message 

> Failed to execute 'replaceState' on 'History': A history state object with URL 'https://cdn-url/redirect' cannot be created in a document with origin 'http://localhost:4202' and URL 'http://localhost:4202/redirect'.

It will work fine if I change the clearHash function with contentWindow.location.origin instead of pathname only:

```javascript
contentWindow.history.replaceState(null, Constants.EMPTY_STRING, contentWindow.location.origin + contentWindow.location.pathname + contentWindow.location.search);
```
I can put a PR to the library if this solution work with you.

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@Rishanthakumar Thanks for the information, feel free to open a PR with a fix.
