### ISSUE TITLE
Reactjs sample

### ISSUE THREAD

**Issue by prashanthmadi** [AzureAD/microsoft-authentication-library-for-js#387]
Trying to use this in my react app. Is there any sample or documentation on how to use this in my react app ?

**Comment by visualjeff** [comment]
Here are a few links...  Hope it helps.

https://www.azurefromthetrenches.com/category/react/
https://github.com/sunilbandla/react-msal-sample
https://github.com/syncweek-react-aad/react-aad/tree/master/sample

**Comment by nehaagrawal** [comment]
@prashanthmadi Currently there is no official documentation from MSAL for react application. But as @visualjeff pointed out there are few samples available on internet. We will try to provide a react sample with some documentation in future. Please close this issue if it resolved your issue.

**Comment by prashanthmadi** [comment]
thanks @nehaagrawal .. looking forward for official doc on it :)

**Comment by himadrinath** [comment]
@prashanthmadi any update on that react docs

**Comment by AndrewCraswell** [comment]
In the meantime, why don't we add a link to the `react-aad-msal` project in the `readme.md` under the "Wrapper libraries" section and denote it as a community-driven project? Microsoft as a company is betting very big on React, and it seems a shame to not have better support for it. It would be awesome to get more engagement on the only community project that has implemented decent support.

https://github.com/syncweek-react-aad/react-aad

**Comment by alexandrtovmach** [comment]
[https://www.npmjs.com/package/react-microsoft-login](https://www.npmjs.com/package/react-microsoft-login)
