### ISSUE TITLE
idTokenClaims roles using Typescript

### ISSUE THREAD

**Issue by sgreco-dev** [AzureAD/microsoft-authentication-library-for-js#3870]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.0

### Description

I am currently using the `useAccount` hook to retrieve account information for the logged in user, I am attempting to access the roles information that is part of the `idTokenClaims` object.

When attempting to access `account.idTokenClaims.roles` I am getting the following error.

`Property 'roles' does not exist on type 'object'`

Account is using the following `AccountInfo` type, which I have attempted to extend with my own type, but it is also telling me that it is not compatible.  

```
AccountInfo = {
    homeAccountId: string;
    environment: string;
    tenantId: string;
    username: string;
    localAccountId: string;
    name?: string;
    idTokenClaims?: object;
}
```

How would I properly access the `roles` property while using Typescript?

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@sgreco-dev `account.idTokenClaims["roles"]`

**Comment by sgreco-dev** [comment]
> @sgreco-dev `account.idTokenClaims["roles"]`

This also does not work for me.  I get the following error when trying this.

```
Element implicitly has an 'any' type because expression of type '"roles"' can't be used to index type '{}'.
  Property 'roles' does not exist on type '{}'.
```

**Comment by jasonnutter** [comment]
Ah right, sorry. You can create your own type for the properties you will use from idTokenClaims, and then cast the idTokenClaims object to that type.

```js
type IdTokenClaims  = {
    roles: string[]
};

const roles = (account.idTokenClaims as IdTokenClaims).roles;
```

**Comment by bodrick** [comment]
Just to add here is a more fleshed out IdTokenClaims.

```
export interface IDTokenClaims {
    aud?: string;
    iss?: string;
    iat?: number;
    nbf?: number;
    exp?: number;
    aio?: string;
    email?: string;
    name?: string;
    nonce?: string;
    oid?: string;
    preferred_username?: string;
    rh?: string;
    roles?: string[];
    sub?: string;
    tid?: string;
    uti?: string;
    ver?: string;
}

```

**Comment by sgreco-dev** [comment]
> Ah right, sorry. You can create your own type for the properties you will use from idTokenClaims, and then cast the idTokenClaims object to that type.
> 
> ```js
> type IdTokenClaims  = {
>     roles: string[]
> };
> 
> const roles = (account.idTokenClaims as IdTokenClaims).roles;
> ```

This solution worked.  Thank you for this, learn something new every day.
