### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by garbledTech** [AzureAD/microsoft-authentication-library-for-js#388]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ x] Chrome version  68.0.3440.106 (Official Build) (64-bit)
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 0.1.0

## Current behavior

Failed to load https://login.microsoftonline.com/tenantonmicrosoft.com/oauth2/v2.0/authorize?
p=policy&clientid=ClientId/v2.0/.well-known/openid-configuration: No 'Access-Control-Allow-Origin' 
header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed 
access.

## Expected behavior

Successful authentication. 

## Minimal reproduction of the problem with instructions

I am using Angular 6 so I made the appropriate adjustments to rxjs and was able to authenticate with azureAd. 

This is the configuration i have in my app.module.ts 

 MsalModule.forRoot({
      clientID: 'ClientId',
      authority: 'https://login.microsoftonline.com/<tenant>.onmicrosoft.com/oauth2/v2.0/authorize?
p=Policy&clientID=ClientId',
      popUp: false,
      isAngular: true,
      redirectUri: 'http://localhost:4200/'
    })

</code></pre>

It looks like i get a CORS error when i make the original request, I found a few other bugs that had the same issue but didnt find a resolution that worked for me. 
Thanks in advance.

**Comment by nehaagrawal** [comment]
@garbledTech Your authority url seems incorrect.

authority: A URL indicating a directory that MSAL can request tokens from. In Azure AD, it is of the form https://<instance>/<tenant>>, where <instance> is the directory host (e.g. https://login.microsoftonline.com) and <tenant> is an identifier within the directory itself (e.g. a domain associated to the tenant, such as contoso.onmicrosoft.com, or the GUID representing the TenantID property of the directory) In Azure AD B2C, it is of the form https://<instance>/tfp/<tenantId>/<policyName>/. Default value is: "https://login.microsoftonline.com/common".

You can find more details about all the config parameter here https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL-basics. Please try with a valid authority url.

**Comment by garbledTech** [comment]
Ah thats embarrassing. Thanks for the help.
