### ISSUE TITLE
Upgrade to uuid 7+

### ISSUE THREAD

**Issue by miguel-orange** [AzureAD/microsoft-authentication-library-for-js#3881]
Please upgrade to uuid version 7+.

> npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

`npm list uuid`
<img width="357" alt="Screen Shot 2021-07-13 at 1 55 25 PM" src="https://user-images.githubusercontent.com/13228659/125523623-20dbfdac-97e5-4f53-b1cb-d71bfdc0aded.png">

**Comment by jasonnutter** [comment]
@miguel-orange `Math.random` is only used by `uuid@3.x` in browser scenarios, which is out of scope for ADAL Node: https://github.com/uuidjs/uuid/blob/e2d731463b680c5b816d144f66feef902586410e/lib/rng-browser.js#L28

Furthermore, please consider updating to [MSAL Node](https://www.npmjs.com/package/@azure/msal-node), as ADAL Node is no longer actively maintained.

**Comment by jasonnutter** [comment]
Tedious has completed the upgrade to @azure/identity: https://github.com/tediousjs/tedious/pull/1335

Closing.
