### ISSUE TITLE
acquireTokenByUsernamePassword (ROPC) will not return an id_token in Azure AD B2C

### ISSUE THREAD

**Issue by pascalu** [AzureAD/microsoft-authentication-library-for-js#3883]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.2.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

When using the Resource Owner Password Credential Flow with Azure AD B2C an id_token seems to be only returned when:

- scopes include `openid`
- response_type is `id_token` or `token id_token`

See [Test the ROPC Flow](https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-ropc-policy?tabs=app-reg-ga&pivots=b2c-user-flow#test-the-ropc-flow) in the Azure AD B2C Doumentation for a sample request returning both `access_token` and `id_token`:

**Request:**

```
POST /<tenant-name>.onmicrosoft.com/B2C_1A_ROPC_Auth/oauth2/v2.0/token HTTP/1.1
Host: <tenant-name>.b2clogin.com
Content-Type: application/x-www-form-urlencoded

username=contosouser.outlook.com.ws&password=Passxword1&grant_type=password&scope=openid+bef22d56-552f-4a5b-b90a-1988a7d634ce+offline_access&client_id=bef22d56-552f-4a5b-b90a-1988a7d634ce&response_type=token+id_token
```

**Response**

```
{
    "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik9YQjNhdTNScWhUQWN6R0RWZDM5djNpTmlyTWhqN2wxMjIySnh6TmgwRlki...",
    "token_type": "Bearer",
    "expires_in": "3600",
    "refresh_token": "eyJraWQiOiJacW9pQlp2TW5pYVc2MUY0TnlfR3REVk1EVFBLbUJLb0FUcWQ1ZWFja1hBIiwidmVyIjoiMS4wIiwiemlwIjoiRGVmbGF0ZSIsInNlciI6Ij...",
    "id_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik9YQjNhdTNScWhUQWN6R0RWZDM5djNpTmlyTWhqN2wxMjIySnh6TmgwRlki..."
}
````
When using acquireTokenByUsernamePassword the `response_type` parameter does not appear to be set. Therefore, no `id_token` will be returned by Azure AD B2C, even when list of scopes include `openid`

Expected behaviour:
- set the `response_type` in acquireTokenByUsernamePassword to `token id_token` when the scopes include `openind`

### MSAL Configuration

```javascript
auth: {
        clientId: "clientID",
        authority: "https://yourtenant.b2clogin.com/yourtenant.onmicrosoft.com/b2c_1a_signinwithropc", 
        knownAuthorities: ["https://yourtenant.b2clogin.com"]
      },
      cache: {
          cacheLocation: "sessionStorage",
          storeAuthStateInCookie: false
      }
```

### Relevant Code Snippets

```javascript
import * as msal from "@azure/msal-node"

const username = "email@example.com"
const password = "superSecret"

   const config = {
     auth: {
        clientId: "clientID",
        authority: "https://yourtenant.b2clogin.com/yourtenant.onmicrosoft.com/b2c_1a_signinwithropc", 
        knownAuthorities: ["https://yourtenant.b2clogin.com"]
      },
      cache: {
          cacheLocation: "sessionStorage",
          storeAuthStateInCookie: false
      }

    }
    
const msalInstance = new msal.PublicClientApplication(config);
         
const usernamePasswordRequest = {
            scopes: ["clientId", "openid"],
            username: username,
            password: password
        };
      
msalInstance.acquireTokenByUsernamePassword(usernamePasswordRequest).then(response => {
            console.log("acquired token by password grant");
        }).catch((error) => {
          console.log(error);
      });
```

### Reproduction Steps

1. request both access_token and id_token by calling acquireTokenByUsernamePassword with the following scopes: 

```
scopes: ["clientId", "openid"]
```

### Expected Behavior

- acquireTokenByUsernamePassword should set the response_type to `token id_token` when the scopes include `openind`
- get both `access_token` and `id_token` in the response

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by jasonnutter** [comment]
I can confirm this is a bug, thanks! We'll add it to our backlog. We'd also accept a pull request with a fix.

**Comment by janiek** [comment]
any progress on this one? Bug is still present...

**Comment by EmLauber** [comment]
We are planning on addressing it next quarter, FY22Q2.

**Comment by ckumpe** [comment]
I've submitted a PR to fix this issue. This PR adds the `response_type=token+id_token` parameter for the request send by _acquireTokenByUsernamePassword_ to retrieve the ID Token. 
This enables later calls to _acquireTokenSilent_ to retrieve the tokens from cache.
