### ISSUE TITLE
Silently log out a user, w/o page redirection or popup

### ISSUE THREAD

**Issue by Miwa199739** [AzureAD/microsoft-authentication-library-for-js#3886]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.15.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

N/A

### Description

Is there any way to silently log out a user without redirect or popup? We have a me control component as the following to list all the logged-in users, and we want to silently sign out a user from our site and also end the server session after the user clicks sign out. 
![image](https://user-images.githubusercontent.com/14820833/126447341-e2447574-1caa-430c-a8c5-a786876c33e1.png)

We can write sth like as the following to avoid the page redirection but that doesn't clear the server session which is not expected for us.
this._msalInstance.logout({
            account: this._msalInstance.getAccountByUsername(userName),
            onRedirectNavigate: (url) => {
                return false;
            }

        });

And we also noticed that the Azure portal is using a hidden iframe to attain the same purpose, not sure about the underlying implementation though.
![image](https://user-images.githubusercontent.com/14820833/126447896-73a5a05a-be21-49ee-b0a5-807cbfb866fd.png)

### MSAL Configuration

```javascript
{
            auth: {
                clientId: 'xxxxxx',
                authority: 'https://login.microsoftonline.com/organizations',
                redirectUri: window.location.origin,
                postLogoutRedirectUri: window.location.origin + baseHref,
                navigateToLoginRequestUrl: true
            },
            cache: {
                storeAuthStateInCookie: false,
                cacheLocation: 'sessionStorage'
            },
            system: {
                loggerOptions: {
                    loggerCallback: (level: LogLevel, message: string, containsPii: boolean): void => {
                        if (containsPii) {
                            return;
                        }
                        switch (level) {
                            case LogLevel.Error:
                                console.error(message);
                                return;
                            case LogLevel.Info:
                                console.info(message);
                                return;
                            case LogLevel.Verbose:
                                console.debug(message);
                                return;
                            case LogLevel.Warning:
                                console.warn(message);
                                return;
                        }
                    },
                    piiLoggingEnabled: false
                }
            }
        };
```

### Relevant Code Snippets

```javascript
public async logOutByAccountName(userName: string): Promise<void> {
        return this._msalInstance.logout({
            account: this._msalInstance.getAccountByUsername(userName),
            onRedirectNavigate: (url) => {
                // Return false to stop navigation after local logout
                return false;
            }
        });
    }
```

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by hectormmg** [comment]
Hi @Miwa199739 , AAD does not currently support silent login at the moment. Please consult the discussion on issue #3833 for more information.
