### ISSUE TITLE
Cannot set log level to Error with configuration

### ISSUE THREAD

**Issue by PetrSnobelt** [AzureAD/microsoft-authentication-library-for-js#3887]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

2.14.1

### Description

It is not possible to specify ErrorLevel (0) as default log level due to or condition:
`this.level = loggerOptions.logLevel || LogLevel.Info;`
if logLevel is 0 (Error) then it is set to Info instead.

Fix should be simple, just change it to 
`this.level = loggerOptions.logLevel ?? LogLevel.Info;`

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/2f66302660169c12ee8bb4622ecc0c497e1c7471/lib/msal-common/src/logger/Logger.ts#L65

### MSAL Configuration

```javascript
{
  auth: {
    not important for this case
  },
  system: {
    loggerOptions: {
      loggerCallback: (level, message, containsPii) => {
        if (containsPii) {
          return;
        }
        switch (level) {
          case msal.LogLevel.Error:
            console.error(message);
            return;
          case msal.LogLevel.Info:
            console.info(message);
            return;
          case msal.LogLevel.Verbose:
            console.debug(message);
            return;
          case msal.LogLevel.Warning:
            console.warn(message);
            return;
        }
      },
      piiLoggingEnabled: false,
      logLevel: msal.LogLevel.Error, // cannot be set because it is zero and there is or condition
    },
```

### Relevant Code Snippets

```javascript
just create new myMSALObj and verify level
```

### Reproduction Steps

create new myMSALObj object with the provided configuration

### Expected Behavior

myMSALObj.logger.level should be set to 0 (Error)

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer

### Source

Internal (Microsoft)

**Comment by PetrSnobelt** [comment]
Workaround: 
`myMSALObj.logger.level = msal.LogLevel.Error;`
after creating myMSALObj

**Comment by hectormmg** [comment]
Hi @PetrSnobelt , thanks for raising the issue. I'll update the issue when a PR to fix this is ready.
