### ISSUE TITLE
Content Security Policy Issues

### ISSUE THREAD

**Issue by alam-R** [AzureAD/microsoft-authentication-library-for-js#3888]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.15.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.1

### Description

There is some kind of Content Security Policy problem when using msal.
We do not use any proxy.

Our configuration:
```js
export const msalConfig: Configuration = {
  auth: {
    clientId: '**********************************',
    authority: 'https://login.microsoftonline.com/[tenant]',
    knownAuthorities: [],
    redirectUri: 'http://localhost',
    postLogoutRedirectUri: 'https://localhost/myApp/logout',
    navigateToLoginRequestUrl: false
  },
  cache: {
    cacheLocation: 'localStorage' // This configures where your cache will be stored
  }
};
```
With the above configuration we get:
_Uncaught (in promise) ClientAuthError: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter._

When we add the authority
```js
export const msalConfig: Configuration = {
  auth: {
    clientId: '**********************************',
    authority: 'https://login.microsoftonline.com/[tenant]',
    knownAuthorities: ['https://login.microsoftonline.com/<tenant>/oauth2/v2.0/authorize'],
    redirectUri: 'http://localhost',
    postLogoutRedirectUri: 'https://localhost/myApp/logout',
    navigateToLoginRequestUrl: false
  },
  cache: {
    cacheLocation: 'localStorage' // This configures where your cache will be stored
  }
};
```
we get:
_Content Security Policy: The page’s settings blocked the loading of a resource at https://login.microsoftonline.com/<tenant>/v2.0/.well-known/openid-configuration (“default-src”). FetchClient.ts:24
Uncaught (in promise) ClientAuthError: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientAuthError: openid_config_error: Could not retrieve endpoints. Check your authority and verify the .well-known/openid-configuration endpoint returns the required endpoints. Attempted to retrieve endpoints from: https://login.microsoftonline.com/<tenant>/v2.0/.well-known/openid-configuration_

Our site is served on port 9000 @ localhost but with an extra path:
http://localhost:9000/dev-aaa/

When we reach it without the / in the location everything works fine!!!

Application has been configured as SPA with redirectUri the one from the config. We have also tried to change it to http://localhost:9000/dev-aaa and http://localhost:9000/dev-aaa/ but we had the same problem.

### MSAL Configuration

```javascript
auth: {
    clientId: '**********************************',
    authority: 'https://login.microsoftonline.com/<tenant>',
    knownAuthorities: ['https://login.microsoftonline.com/<tenant>/oauth2/v2.0/authorize'],
    redirectUri: 'http://localhost',
    postLogoutRedirectUri: 'https://localhost/myApp/logout',
    navigateToLoginRequestUrl: false
  },
  cache: {
    cacheLocation: 'localStorage' // This configures where your cache will be stored
  }
```

### Source

External (Customer)

**Comment by hectormmg** [comment]
Hi @alam-R . The authority specified in the first MSAL configuration object you listed is incomplete because it's missing the sign-in audience (this can be your tenantId, "common", "organizations", or consumers.

Please consult the [AAD Authority docs] (https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-client-application-configuration#authority) for more information and let us know if your issue is resolved so we can close it.

Thanks!

**Comment by alam-R** [comment]
Thank you very much for the quick response @hectormmg.
We do use the tenantId, please check the provided MSAL conf above. I've just wrote tenant inside <> and it is omitted from the url... I've edited it with [].
It doesn't seem valid this one: _Once you add the audience, since login.microsoftonline.com authorities are trusted authorities by default, you shouldn't need to add the knownAuthorities array to the configuration._
We provide the tenantId but it seems that if we do not specify the authorize endpoint to knownAuthoritites the CSP is triggered...

**Comment by hectormmg** [comment]
@alam-R I haven't been able to reproduce your issue. You shouldn't need to add `https://login.microsoftonline.com/<tenant>` to `knownAuthorities`, so its unclear to me why you are getting the initial error. For the CSP error you get when adding the authorize endpoint to the knownAuthorities array, that content security policy is something configured in your React application, so you would need to look into changing that policy to unblock MSAL's endpoint discovery requests.

**Comment by alam-R** [comment]
The error is:
Refused to connect to 'https://login.microsoftonline.com/[tenant]/v2.0/.well-known/openid-configuration' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.

FetchClient.ts:24
export class FetchClient implements INetworkModule {

    /**
     * Fetch Client for REST endpoints - Get request
     * @param url 
     * @param headers 
     * @param body 
     */
    async sendGetRequestAsync<T>(url: string, options?: NetworkRequestOptions): Promise<NetworkResponse<T>> {
        let response;
        try {
            response = await fetch(url, {
                method: HTTP_REQUEST_TYPE.GET,
                headers: this.getFetchHeaders(options)
            });
        } catch (e) {
            if (window.navigator.onLine) {
                throw BrowserAuthError.createGetRequestFailedError(e, url);
            } else {
                throw BrowserAuthError.createNoNetworkConnectivityError();
            }
        }

I've tried to change my page's CSP settings and especially connect-src but I am not sure that this error is generated by my client's policy. Could you please check again and return with your feedback?
Thanks!

**Comment by samuelkubai** [comment]
Hi @alam-R, could you share with me a fiddler trace of this, so we can inspect how the content security headers are being set for the application.

**Comment by alam-R** [comment]
Missing configuration on the web security level was the key. Indeed the problem was on the application part, so I guess we can close the issue.
Thanks for your time and your effort!
