### ISSUE TITLE
On behalf of workflow using Token from another app on the same tenant

### ISSUE THREAD

**Issue by oliverjanik** [AzureAD/microsoft-authentication-library-for-js#389]
AADSTS70002: Error validating credentials. AADSTS50013: Assertion audience does not match the Client app presenting the assertion. The audience in the assertion was 'abc' and the expected audience is 'def' or one of the Application Uris of this application with App ID 'def'.

Is this not a supported scenario?

I'm trying to implement a SSO where my API would accept a user accessToken from another app (same tenant) and then perform On-Behalf-Of requests.

Is this scenario not supported? Will it ever be?

**Comment by nehaagrawal** [comment]
@navyasric  can you help?

**Comment by oliverjanik** [comment]
OK, so I believe I got this working by creating a scope for my WebAPI and then requesting token for that scope before it's passed to UserAssertion
