### ISSUE TITLE
Self-Service change password flow considers user as logged out, despite valid access token present in local storage

### ISSUE THREAD

**Issue by mleimer** [AzureAD/microsoft-authentication-library-for-js#3896]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.15.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

1.2.0

### Description

Given:
- A self-service change password flow based on a custom policy identical to: https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-password-change-policy?pivots=b2c-custom-policy
- MSALs `cacheLocation` property defined as `localStorage`

When:
1. Logging in through the exposed `loginRedirect`on the `PublicClientApplication` instance
2. Awaiting successful login and redirects
3. Closing the browser
4. Reopening the browser
5. Calling self-service change password flow through the exposed `acquireTokenRedirect `on the `PublicClientApplication` instance

Then:
- `OrchestrationStep` 2 with `TechnicalProfileReferenceId="SelfAsserted-LocalAccountSignin-Email"` is shown

### Expected behavior

- `OrchestrationStep` 3 with `TechnicalProfileReferenceId="LocalAccountWritePasswordChangeUsingObjectId"` is shown, as the user has a valid access token in the local storage after step 2, 3 and 4.

### Actual behavior

- `OrchestrationStep` 2 with `TechnicalProfileReferenceId="SelfAsserted-LocalAccountSignin-Email"` is shown and user has to login one more time

### Further details

- This issue only occurs if the browser gets closed and reopend as described in step 3 and 4 of steps to reproduce.
- If steps 3 and 4 are not executed, `OrchestrationStep` 3 with `TechnicalProfileReferenceId="LocalAccountWritePasswordChangeUsingObjectId"` is shown as expected
- Based on the network call which appears in the DEV-Tool upon calling `acquireTokenRedirect `on the `PublicClientApplication`, the following differences could be identified where it is working (without step 3 & 4) and not working (with step 3 & 4). The request has different:
-- `client-request-id`
-- `code-challenge`
-- `nonce`
-- `state`
as query parameters when calling the customized password-edit flow.
In addition, the working request sends the following cookies:
-- `s_fid`
-- `x-ms-cpim-csrf`
-- `x-ms-cpim-sso`
while the failing request only sends the `s_fid` cookie in the request.
We believe that the missing cookies could be the root cause for this issue. Those cookies should be added by the MSAL-library.

### Error Message

POST https://xxxxxxxxxxx/someId/B2C_1A_ProfileEditPasswordChange/client/perftrace?tx=StateProperties=eyXXXXXXXXX&p=B2C_1A_ProfileEditPasswordChange 400

### MSAL Configuration

```javascript
{
  auth: {
    clientId: `${process.env.NEXT_PUBLIC_AUTH_CLIENT_ID}`,
    authority: MSAL_AUTHORITY_SIGNIN_SIGNUP,
    knownAuthorities: [`${process.env.NEXT_PUBLIC_AUTH_TENANT_URL}`],
    redirectUri: process.env.NEXT_PUBLIC_AUTH_REDIRECT_URL,
    navigateToLoginRequestUrl: true,
  },
  cache: {
    cacheLocation: 'localStorage',
  },
};
```

### Relevant Code Snippets

```javascript
changePassword(locale: string): Promise<void> {
    if (this.userAgentApplication.getAllAccounts().length === 0) {
      throw new Error('User has no accounts');
    }

    const redirectRequest: RedirectRequest = {
      scopes: SCOPES,
      account: this.userAgentApplication.getAllAccounts()[0],
      authority: MSAL_AUTHORITY_CHANGE_PASSWORD,
      redirectUri: MSAL_CONFIG.auth.redirectUri,
      extraQueryParameters: { ui_locales: locale },
    };

    return this.userAgentApplication.acquireTokenRedirect(redirectRequest);
  }
```

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@mleimer This seems like a B2C service issue. Please file a support ticket with the B2C team by following the instructions [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options). Please also be aware that cookies are the service's responsibility, not MSAL.

**Comment by mleimer** [comment]
@jo-arroyo Kindly note that I already opened a service request with TrackingID#2107260050000997 where I was informed that "we at the Azure active directory department do not handle issues related to the MSAL.js v2 (Microsoft authentication library". Please inform what kind of support ticket and service type I should create to get further help on this matter.

**Comment by jo-arroyo** [comment]
@nickgmicrosoft Is anyone from your team able to provide assistance with this issue? Looks like it's related to the B2C service.

**Comment by jo-arroyo** [comment]
@mleimer After conversing with the B2C team, they are happy to look at this issue. Please open a service request [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options) directly for the B2C team so they can help you with this. Additionally, you are welcome to email me the network trace, and I can pass it onto the team to look at. My email is in my profile.

**Comment by mleimer** [comment]
I just received an answer from the Microsoft support team informing me that 

> ...they [backend team] had let us know that in order for the session to remains active after the browser is closed the users can use the option for Keep me sign in. This option will keep the session active even after the browser is closed.
Refer to:
“You can enable the KMSI feature for users of your web and native applications who have local accounts in your Azure AD B2C directory. When you enable the feature, users can opt to stay signed in so the session remains active after they close the browser. Then they can reopen the browser without being prompted to reenter their username and password. This access is revoked when a user signs out.”
https://docs.microsoft.com/en-us/azure/active-directory-b2c/session-behavior?pivots=b2c-custom-policy#enable-keep-me-signed-in-kmsi
Please keep in mind that the option is available only for local accounts in the Azure B2C directory.

Although that I haven't tried that out yet, I believe that this would resolve this bug.

My current understanding is now that
* User must enable KMSI with SSO on a local Azure AD B2C account to remain authenticated after having closed the browser when starting a policy like self-service password change
* Retrieving a new access token  after having closed the browser does not require KSMI with SSO (provided there is a valid session & refresh token).
