### ISSUE TITLE
Acquiring token & Login confusion

### ISSUE THREAD

**Issue by Glideh** [AzureAD/microsoft-authentication-library-for-js#3897]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

Not Applicable

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/acquire-token.md

### Description

There seems to have a confusion in the [acquireToken doc page](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/acquire-token.md)

On the top we are saying:

> In MSAL, you can get access tokens for the APIs your app needs to call using the acquireToken methods provided by the library which make requests to Azure AD to obtain an authorization code. The MSAL library then exchanges that code for an access token containing the user consented scopes to allow your app to securely call the API.

First sentence in short: "you can get access tokens [...] using the acquireToken methods [...] which make requests [...] to obtain an authorization code"

`acquireToken` methods seem to get the access token more than the authorization code. Login methods are retrieving the authorization code, isn't it ?

Or does `acquireToken` manage both ? In which case I didn't find any good practice suggestion on how to manage the login fallback when required.

**Comment by derisen** [comment]
@Glideh the [OAuth authorization code flow](https://docs.microsoft.com/azure/active-directory/develop/v2-oauth2-auth-code-flow) is a two-step process i.e. you get an auth code and then exchange it for tokens. `acquireToken*` methods handle both steps. I guess this could be made more explicit in the docs.

The `login*` methods are only a special case of `acquireToken*` methods (i.e internally uses `acquireTokenPopup` or `acquireTokenRedirect`, gets you an ID token in addition).

Can you clarify what do you mean by login fallback? If you are looking for something equivalent to the suggestion that the code should fallback to `acquireTokenPopup` or `acquireTokenRedirect` when `acquireTokenSilent` fails, I guess it would be to fallback to `loginPopup` or `loginRedirect` when `ssoSilent` fails.

**Comment by Glideh** [comment]
Thank you for your quick answer.

> `acquireToken*` methods handle both steps. I guess this could be made more explicit in the docs.

I admit that I didn't get that at first read.

> The `login*` methods are only a special case of `acquireToken*` methods (they internally use `acquireTokenPopup` or `acquireTokenRedirect`).

Ok ! So once logged in with that methods the browser already has his access token ? This didn't appear clearly for me when following the SPAs steps, especially from [the login instructions](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-sign-in?tabs=javascript2) through next [acquiring tokens](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-acquire-token?tabs=javascript2) step. I though we were suggesting to acquire a token once the user is logged in (which seemed legit for me)

> Can you clarify what do you mean by login fallback? If you are looking for something equivalent to the suggestion that the code should fallback to `acquireTokenPopup` or `acquireTokenRedirect` when `acquireTokenSilent` fails, I guess it would be to fallback to `loginPopup` or `loginRedirect` when `ssoSilent` fails.

Let me give you a simple scenario: The user is requesting a page requiring some permission.
So we first need to make sure he is logged in, then check whether he has the permission.

For that, here what I'm currently doing:
- Prepare to receive data from the redirections with `handleRedirectPromise()`
- Check if there is any account logged in with `getAllAccounts()`, if no:
  - Try to log the user in with one of the `logginXXX()`  methods
- Try to acquire a token silently with `acquireTokenSilent()`, if failing:
  - Try to acquire a token "loudly" with one of the `acquireTokenXXX()` methods
- Consume the needed API

But I think you are going to tell me that I'm doing too much things :)

**Comment by derisen** [comment]
@Glideh So when the user signs in, they get an access token containing permissions for the [userinfo endpoint](https://docs.microsoft.com/en-us/azure/active-directory/develop/userinfo) (which is hosted on Graph API, so it's an access token _meant for_ Graph). During that step you can also prompt the user to consent to additional resources (like your web API) by passing their scope to the login request. Later on, the acquireToken* methods need to be used to get an access token _meant for_ your web API (i.e. you pass the scope for your web API in the acquireToken* request). Take a look at [this document](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/resources-and-scopes.md) to understand the relation between scopes and resources.

What you're doing looks fine to me. In the 2nd step you can also rely on the [Events API](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/events.md) to monitor for login success or failure, and handle appropriately. I would also recommend you to check the samples in this [tutorial](https://github.com/Azure-Samples/ms-identity-javascript-tutorial).

**Comment by Glideh** [comment]
That's all clear, thank you again
