### ISSUE TITLE
TypeScript Typings for msal-angularjs wrapper

### ISSUE THREAD

**Issue by RobARichardson** [AzureAD/microsoft-authentication-library-for-js#390]
## I'm submitting a...

[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:

## Library version
@azure/msal-angularjs: 0.1.0

## Current behavior
No TypeScript Typings available for msal-angularjs

## Expected behavior
If you're using AngularJS + TypeScript + msal-angularjs, it would be really nice to have TypeScript Typings for msal-angularjs

## Minimal reproduction of the problem with instructions
n/a

**Comment by rodrraul** [comment]
How do you import msal-angularjs in angularjs + typescript?  I just cannot find a way.
I have tried _import * as msal from '@azure/msal-angularjs';_ and _require('@azure/msal-angularjs');_ with no success at all.

**Comment by DarylThayil** [comment]
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angularjs/samples/MsalAngularjsDemoApp/app.js#L3 
this is how the sample does it, does this not work?

**Comment by rodrraul** [comment]
Yes, I got it working.  I had to use _import * from msal;_ as we are using Typescript on top of AngularJS.  Thanks Daryl.

**Comment by jasonnutter** [comment]
I noticed `msal-angular` didn't have a `types` field in its `package.json` when looking into the IE11 issue, so I'm hoping this can be fixed when that issue is fixed.

**Comment by DarylThayil** [comment]
@negoe to add context on angularjs support

**Comment by jasonnutter** [comment]
We are no longer supporting the AngularJS wrapper, and will concentrate on `msal-angular`. If there any issues with typings in that library, please open a new issue, thanks!
