### ISSUE TITLE
msal accounts are empty after browser refresh

### ISSUE THREAD

**Issue by skyshine999** [AzureAD/microsoft-authentication-library-for-js#3901]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.16.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.1

### Description

i added @azure/msal-react in my react application. Based on accounts length i am showing signout button. After login if i refresh browser msal accounts length is zero, After some time it is showing accounts. Is this expected behaviour or am i doing anything wrong in configuration.

### Error Message

no error

### MSAL Configuration

```javascript
export const msalConfig: Configuration = {
    auth: {
        clientId: clientId,
        authority: "https://login.microsoftonline.com/xxxxxxxxxxxxxxxx/“,
        redirectUri: "http://localhost:3000",
        postLogoutRedirectUri: redirectUri
    },
    cache: {
        cacheLocation: "localStorage",
        storeAuthStateInCookie: true,
    },
};
```

### Relevant Code Snippets

```javascript
export const msalInstance = new PublicClientApplication(msalConfig);

msalInstance.addEventCallback((event: EventMessage) => {
    if (event.eventType === EventType.LOGIN_SUCCESS && event.payload) {
        const payload = event.payload as AuthenticationResult;
        const account = payload.account;
        msalInstance.setActiveAccount(account);
    }
})

 const { instance,accounts } = useMsal();
accounts.length ===> 0
```

### Reproduction Steps

first do login get the accounts
refresh the browser, check immediately accounts are empty

### Expected Behavior

After refreshing immediately accounts should be visible

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@skyshine999 Where are you calling `useMsal()` and checking for accounts? Are you able to use one of our msal-react samples to reproduce this behavior?

**Comment by skyshine999** [comment]
I have seen msal-react sample there also we are msal accounts using useMsal(), below i shared sample
```
import { useEffect, useState } from "react";
import { useMsal } from "@azure/msal-react";
import Typography from "@material-ui/core/Typography";

const WelcomeName = () => {
    const { accounts } = useMsal();
    const [name, setName] = useState(null);

    useEffect(() => {
        if (accounts.length > 0) {
            setName(accounts[0].name.split(" ")[0]);
        }
    }, [accounts]);

    if (name) {
        return <Typography variant="h6">Welcome, {name}</Typography>;
    } else {
        return null;
    }
};

export default WelcomeName;
```

**Comment by jo-arroyo** [comment]
@skyshine999 Have you tried checking that the `inProgress` value is none? Please see [this doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/hooks.md#usemsal-hook) on how to check for `inProgress` status and ensure that all initialization and interactions are done before accessing accounts.

We will also update our samples to make this process clearer.
