### ISSUE TITLE
msal query param fetch

### ISSUE THREAD

**Issue by router19** [AzureAD/microsoft-authentication-library-for-js#3904]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.0

### Description

I need to switch between Idps based on the url query parameter. In the below snippet given below if url query parameters has xxx=yyy then I should use auth1 Idp else auth2.

I have MSAL configuration and instance creation in the app.module.ts file of my angular project. 
Q1) Is there a way in MSAL to intercept the url parameter before MSAL instance creation. My 

Q2) I have my MSAL config in Angular module. I even tried using the constructor and call populareQueryParamMap from there but the msalInstance is created before constructor is even called.

I would prefer if MSAL has a way to intercept the query param and which can be used to change the Idp between auth1 and auth2.

Experts, please suggest if it is possible?

### MSAL Configuration

```javascript
const auth1 = {
      clientId : 'abcefxxxxxx'
}
const auth2 = {
      clientId: 'xyzpqrxxxx'
}

export function MSALINstanceFactory() : IPublicClientApplication {
return new PublicClientApplication({
auth : this.appInitService.queryParamMap['xxx'] === 'yyy' ? auth1 : auth2,

}
}

const msalInstance = new MSALInstanceFactory();
```

### Relevant Code Snippets

```javascript
//Constructor inside AppModule to populate the queryParamMap.
export Class AppModule{
constructor(public appInitService: AppInitService)
{
   this.appInitService.populateQueryParamMap():
}
}
```

### Identity Provider

Other

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@router19 To clarify, are you looking to authenticate to two different endpoints? Or use two different IdPs with the same app? 
While MSAL has multi-tenant support and the ability to set the tenant dynamically (see documentation [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/multi-tenant.md)), MSAL does not include a way to intercept the URL for you.

**Comment by router19** [comment]
@jo-arroyo Thanks for your response. I want to authenticate using two different IdPs with the same app based on some query param. e.g. if the query param has flow=b2c then I would use b2c otherwise third-party IdP like Ping. Is it possible to use third-party Idp with MSAL?

**Comment by jo-arroyo** [comment]
@router19 We don't generally support 3rd party IdPs. MSAL is designed to work with AAD, so while you can try using 3rd party IdPs, we cannot guarantee it will work.
