### ISSUE TITLE
Opening the browser in --disbale-web-security mode, I get AADSTS9002327 Tokens issued for the 'Single-Page Application' client-type may only be redeemed via cross-origin requests

### ISSUE THREAD

**Issue by selenajosephine** [AzureAD/microsoft-authentication-library-for-js#3905]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.15.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.1

### Description

I tried opening my Chrome browser with the below command. 
chrome.exe --user-data-dir="C:/Chrome dev session" --disable-web-security --allow-file-access-from-file

I am using sample app, and it redirects to authentication ( i am using loginRedirect), when it redirects back to the App, 
the token API fails with the below error. 

{"error":"invalid_request","error_description":"AADSTS9002327: Tokens issued for the 'Single-Page Application' client-type may only be redeemed via cross-origin requests.\r\nTrace ID: 20eb92a0-8ef5-4d2b-8966-d996761f2400\r\nCorrelation ID: 26f357fd-11f0-45b1-9783-dce610d51632\r\nTimestamp: 2021-07-28 08:45:42Z","error_codes":[9002327],"timestamp":"2021-07-28 08:45:42Z","trace_id":"20eb92a0-8ef5-4d2b-8966-d996761f2400","correlation_id":"26f357fd-11f0-45b1-9783-dce610d51632"}

### Error Message

{"error":"invalid_request","error_description":"AADSTS9002327: Tokens issued for the 'Single-Page Application' client-type may only be redeemed via cross-origin requests.\r\nTrace ID: 20eb92a0-8ef5-4d2b-8966-d996761f2400\r\nCorrelation ID: 26f357fd-11f0-45b1-9783-dce610d51632\r\nTimestamp: 2021-07-28 08:45:42Z","error_codes":[9002327],"timestamp":"2021-07-28 08:45:42Z","trace_id":"20eb92a0-8ef5-4d2b-8966-d996761f2400","correlation_id":"26f357fd-11f0-45b1-9783-dce610d51632"}

### MSAL Configuration

```javascript
auth: {
      clientId: "2eafee83-fbe0-4fd7-b8c3-52a3b53a8c88",
      authority: "https://login.microsoftonline.com/45ef2f1e-d720-408f-a39f-51709435eba3",
      redirectUri: "http://localhost:3000/",
    },
    cache: {
      cacheLocation: "sessionStorage",
      storeAuthStateInCookie: false, 
    }
```

### Relevant Code Snippets

```javascript
function handleLogin(instance) {
    instance.loginRedirect(loginRequest).catch(e => {
        console.error(e);
    });
}


    <React.StrictMode>
        <MsalProvider instance={msalInstance}>
            <App />
        </MsalProvider>
    </React.StrictMode>,
```

### Reproduction Steps

1. I tried opening my Chrome browser with the below command. 
chrome.exe --user-data-dir="C:/Chrome dev session" --disable-web-security --allow-file-access-from-file

2. Click on Sign in button
3. Sign in
4. Redirect back to the app, token fails with 400.

### Expected Behavior

Authentication should be successful. 

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@selenajosephine This is expected behavior, as `--disable-web-security` is not meant as a production-level setting. When `--disable-web-security` is set, fetch requests do not set an origin header, and AAD is not able to determine that a user is making a CORS request from the browser, and this error is thrown. If you remove the flag, authentication should work as usual.

**Comment by selenajosephine** [comment]
Thanks!
