### ISSUE TITLE
MSAL with third party IDP

### ISSUE THREAD

**Issue by router19** [AzureAD/microsoft-authentication-library-for-js#3906]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.0

### Description

Is it possible to use third-party authority with MSAL. I want to try an integration with PingFederate but as per the documentation at https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-client-application-configuration , it seems that we can have only Azure based authority. 
Could you please confirm if we can use third part Idp as an authority?

### Identity Provider

Other

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
Closing as duplicate. Answered on #3904.
