### ISSUE TITLE
InteractionRequiredAuthError: Silent authentication was denied. The user must first sign in and if needed grant the client application access to the scope 'user.read mail.send openid profile'.

### ISSUE THREAD

**Issue by sundariragavan** [AzureAD/microsoft-authentication-library-for-js#3907]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

1.4.12

### Wrapper Library

Not Applicable

### Wrapper Library Version

000

### Description

Hello, 
       I have created the outlook add in web. I need to read and write the calendar events. I have created the application in microsoft azure. Added the required permission. But i'm getting this error after the login. 
<img width="965" alt="Screenshot 2021-07-29 at 4 36 16 AM" src="https://user-images.githubusercontent.com/37138727/127460026-c8456eb8-051e-4ec0-96c8-2448b1bdb27d.png">
<img width="945" alt="Screenshot 2021-07-29 at 4 36 25 AM" src="https://user-images.githubusercontent.com/37138727/127460037-48c81ab4-93c9-435d-9d5e-557d34f164b4.png">

I have added the all the user and calendar permission. Unable to resolve this issue.

### Error Message

 InteractionRequiredAuthError: Silent authentication was denied. The user must first sign in and if needed grant the client application access to the scope 'user.read mail.send openid profile'.

### MSAL Configuration

```javascript
import { UserAgentApplication } from "msal";
import { Client } from "@microsoft/microsoft-graph-client";
import { ImplicitMSALAuthenticationProvider } from "@microsoft/microsoft-graph-client/lib/src/ImplicitMSALAuthenticationProvider";
import { MSALAuthenticationProviderOptions } from "@microsoft/microsoft-graph-client/lib/src/MSALAuthenticationProviderOptions";

const msalConfig = {
  auth: {
    clientId: CLIENT_ID, // Client Id of the registered application
    redirectUri: REDIRECT_URL,
  },
};

const graphScopes = ["user.read", "mail.send"]; // An array of graph scopes
const msalApplication = new UserAgentApplication(msalConfig);
const options = new MSALAuthenticationProviderOptions(graphScopes);

const authProvider = new ImplicitMSALAuthenticationProvider(
  msalApplication,
  options
);
const option = {
  authProvider, // An instance created from previous step
};
const client = Client.initWithMiddleware(option);
```

### Relevant Code Snippets

```javascript
client.api("/me/events").post(event, (err, res) => {
        // Getting error -  InteractionRequiredAuthError: Silent authentication was denied.
});
```

### Reproduction Steps

Add outlook add in web
Get and POST the calendar events.

### Expected Behavior

Able to create the events in outlook calendar.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

Internal (Microsoft)

**Comment by jo-arroyo** [comment]
@sundariragavan Are you able to provide a code snippet of where the login occurs? In general, `InteractionRequiredAuthErrors` should be handled, and the user prompted to sign in interactively. [Here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/54562e777ed6c99ba882beeeefc414181d5de015/samples/msal-core-samples/VanillaJSTestApp/app/default/auth.js#L63) is an example of this being done in our sample apps.

Additionally, you can try upgrading to MSAL v2 and trying [this sample app](https://github.com/Azure-Samples/ms-identity-javascript-tutorial/tree/main/2-Authorization-I/1-call-graph), which has a graph SDK implementation with MSAL Browser.

**Comment by samuelkubai** [comment]
Now that you can get a valid access token, this seems like a graph problem, are you able to decode the access token and share with us the scopes from the token just to ensure, the necessary scopes are being passed as expected?
