### ISSUE TITLE
IE 11 has Unhandled promise rejection

### ISSUE THREAD

**Issue by selenajosephine** [AzureAD/microsoft-authentication-library-for-js#3908]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.15.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.1

### Description

My Azure Authentication works fine on Chrome, but It causes a script error on IE 11. 

I tried adding in the index.html <script src="https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.min.js" class="pre"></script>

But still get this error. Please advise

### Error Message

Unhandled promise rejection SyntaxError: Syntax error

### MSAL Configuration

```javascript
"auth": {
                "clientId": "ab263b72-0a50-498a-81d9-72e7811f4db6",
                "authority": "https://login.microsoftonline.com/45ef2f1e-d720-408f-a39f-51709435eba3",
                "redirectUri": "http://localhost/tabletdashboard"
            },
            "cache": {
                "cacheLocation": "sessionStorage",
                "storeAuthStateInCookie": false
            }
```

### Relevant Code Snippets

```javascript
Same as sample app
```

### Reproduction Steps

Run application
Open in IE

### Expected Behavior

It should open in IE

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Internet Explorer

### Source

External (Customer)

**Comment by tnorling** [comment]
@selenajosephine Please see the IE11 instructions in our react sample [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/react-router-sample#running-the-sample-in-ie11)

**Comment by selenajosephine** [comment]
Thanks. I added the two packages mentioned (uncommented them, installed and tested) and I still got the same error. Is there anything else I can try?

**Comment by tnorling** [comment]
@selenajosephine I am not able to reproduce this behavior with the sample mentioned above in IE11. The app is able to load and able to sign in. Are you using the sample as is or did you make changes? Are you able to determine what line of code it's complaining about?

**Comment by selenajosephine** [comment]
I was working through this - Expected identifier - this is the new error. function v({instance:e,children:t}){ at this line. 
![image](https://user-images.githubusercontent.com/43022347/129181434-a0b4d41b-a356-4ff8-9311-af700a667b43.png)

**Comment by selenajosephine** [comment]
I use MSAL within my application, for IE, I dont want it to load at all, so I added the polyfills, configured lazy loading and everything, but still the page does not load. From my local workspace, it works, but after I take the build, it does not work.

**Comment by selenajosephine** [comment]
@tnorling , please use this repo - git@github.com:selenajosephine/azure-react-msal-test-app.git

The repository can be found here - https://github.com/selenajosephine/azure-react-msal-test-app. I basically cloned the app given here - git clone https://github.com/Azure-Samples/ms-identity-javascript-react-spa and followed steps mentioned here - https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-react

My IE Version is 
![image](https://user-images.githubusercontent.com/43022347/129397151-27eab8bc-7e6e-4c7c-a695-c894c08ffa21.png)

The error I get on my IE11 is - 
![image](https://user-images.githubusercontent.com/43022347/129397262-467c5ddb-d68e-4d59-8c42-795a4a41bb52.png)

Line 90 of main.chunk.js is 

![image](https://user-images.githubusercontent.com/43022347/129397423-e4ecffa2-9fb2-4a0c-87b8-b782d3d58f56.png)

Line 17869 of vendors-main.chunk.js is 
![image](https://user-images.githubusercontent.com/43022347/129397600-3ca5613b-051c-4e61-bd29-5c0b9caa51e5.png)

I have run the application in both protected and unprotected modes - 
![image](https://user-images.githubusercontent.com/43022347/129397749-455c6421-797a-41d9-b090-6ea014f33144.png)


Can you help me resolve this error? I can implement it the same way in my application then. 

I am not trying to get the AD Authentication to work on IE, I just want the page to load.

**Comment by tnorling** [comment]
@selenajosephine It says the repo is empty 

![image](https://user-images.githubusercontent.com/5307810/129399803-7518c4f2-0489-408c-9db9-a52964a00b4e.png)

Can you also double check your browserslist includes ie 11? The sample you linked does not include ie 11 by default.

**Comment by selenajosephine** [comment]
Yes, after adding the browserslist, I see that it works in the sample app. I tried doing the same thing in my actual app, and it still doesnt work. 

I get an error in the highlighted section. 

![image](https://user-images.githubusercontent.com/43022347/129532515-8aec0328-cf93-412f-a978-55009285ad3e.png)


/*!***************************************************************!*\
  !*** ./node_modules/@azure/msal-react/dist/msal-react.esm.js ***!
  \***************************************************************/
/*! exports provided: AuthenticatedTemplate, MsalAuthenticationTemplate, MsalConsumer, MsalContext, MsalProvider, UnauthenticatedTemplate, useAccount, useIsAuthenticated, useMsal, useMsalAuthentication, withMsal */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
**eval("__webpack_require__.r(__webpack_exports__);\n/* harmony export (binding) */** __webpack_require__.d(__webpack_exports__, \"AuthenticatedTemplate\", function() { return AuthenticatedTemplate; });\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"MsalAuthenticationTemplate\", function() { return MsalAuthenticationTemplate; });\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"MsalConsumer\", function() { return MsalConsumer; });\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"MsalContext\", function() { return MsalContext; });\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"MsalProvider\", function() { return MsalProvider; });\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"UnauthenticatedTemplate\", function() { return UnauthenticatedTemplate; });\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"useAccount\", function() { return useAccount; });\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"useIsAuthenticated\", function() { return useIsAuthenticated; });\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"useMsal\", function() { return useMsal; });\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"useMsalAuthentication\", function() { return useMsalAuthentication; });\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"withMsal\", function() { return withMsal; });\n/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! react */ \"0gP4\");\n/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(react__WEBPACK_IMPORTED_MODULE_0__);\n/* harmony import */ var _azure_msal_browser__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! @azure/msal-browser */ \"Czdx\");\n\n\n\n/*\r\n * Copyright (c) Microsoft Corporation. All rights reserved.\r\n * Licensed under the MIT License.\r\n */\n/*\r\n * Stubbed context implementation\r\n * Only used when there is no provider, which is an unsupported scenario\r\n */\n\nc

**Comment by tnorling** [comment]
@selenajosephine If it works in the sample app please try to figure out what your app is doing differently. It sounds to me like your bundler is misconfigured but it's impossible for me to help without a reproduction.
