### ISSUE TITLE
TS Docs for localAccountId in AccountInfo type definition.

### ISSUE THREAD

**Issue by miszo** [AzureAD/microsoft-authentication-library-for-js#3912]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

Not Applicable

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/docs/Accounts.md

### Description

I'm a little confused by TS Docs for `localAccountId` provided in `AccountInfo` type definition.

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/src/account/AccountInfo.ts

Should `localAccountId` be used only in legacy cases? I'm asking because we are using `OID` from `idTokenClaims` to bind user action between several providers (e.g. analytics, error tracking). From what it seems, `localAccountId` is the same thing as `OID`.

We are using Azure AD B2B in this case.

Any comment from you will be appreciated.

**Comment by samuelkubai** [comment]
Hi @miszo, thank you for bringing this up, you are right `localAccountId` is the same thing as `OID`, we'll upgrade the documentation and remove the ".., usually used in legacy cases" part as it is no longer the case and is misleading at this point.

**Comment by miszo** [comment]
@samuelkubai, thanks a million!

**Comment by samuelkubai** [comment]
My pleasure, feel free to re-open and/or create a new issue if you have another question.
