### ISSUE TITLE
Old version of https-proxy-agent

### ISSUE THREAD

**Issue by sammachin** [AzureAD/microsoft-authentication-library-for-js#3914]
Hi,

Could you please take a look at upgrading the version of https-proxy-agent in your dependencies, you are currently on 2.4.0 which uses an old version of agent-base (<6.0.0) and this is causing issues with a package that depends on you.
https://github.com/joeyboey/node-red-contrib-passport-azure-ad/issues/1

**Comment by pkanher617** [comment]
I'll take a look at this.

**Comment by sammachin** [comment]
I don't know what feedback you are wanting from me, all the info I have is in the issue and the parent issue linked.
