### ISSUE TITLE
MSAL for Angular not updated with RXJS changes

### ISSUE THREAD

**Issue by tipsanemonk** [AzureAD/microsoft-authentication-library-for-js#392]
## RxJS is updated and the code needs to be updated
<pre>
<code>
ERROR in ./node_modules/@azure/msal-angular/dist/broadcast.service.js
Module not found: Error: Can't resolve 'rxjs/BehaviorSubject' in 'D:\Projects\Poseidon-Next User Experience\Work\UX.Entitlements\Applications\scope-management\node_modules\@azure\msal-angular\dist'
ERROR in ./node_modules/@azure/msal-angular/dist/msal.interceptor.js
Module not found: Error: Can't resolve 'rxjs/Observable' in 'D:\Projects\Poseidon-Next User Experience\Work\UX.Entitlements\Applications\scope-management\node_modules\@azure\msal-angular\dist'
ERROR in ./node_modules/@azure/msal-angular/dist/msal.interceptor.js
Module not found: Error: Can't resolve 'rxjs/add/observable/fromPromise' in 'D:\Projects\Poseidon-Next User Experience\Work\UX.Entitlements\Applications\scope-management\node_modules\@azure\msal-angular\dist'
ERROR in ./node_modules/@azure/msal-angular/dist/msal.service.js
Module not found: Error: Can't resolve 'rxjs/add/observable/of' in 'D:\Projects\Poseidon-Next User Experience\Work\UX.Entitlements\Applications\scope-management\node_modules\@azure\msal-angular\dist'
ERROR in ./node_modules/@azure/msal-angular/dist/msal.service.js
Module not found: Error: Can't resolve 'rxjs/add/operator/delay' in 'D:\Projects\Poseidon-Next User Experience\Work\UX.Entitlements\Applications\scope-management\node_modules\@azure\msal-angular\dist'
ERROR in ./node_modules/@azure/msal-angular/dist/msal.service.js
Module not found: Error: Can't resolve 'rxjs/add/operator/do' in 'D:\Projects\Poseidon-Next User Experience\Work\UX.Entitlements\Applications\scope-management\node_modules\@azure\msal-angular\dist'
ERROR in ./node_modules/@azure/msal-angular/dist/msal-guard.service.js
Module not found: Error: Can't resolve 'rxjs/add/operator/filter' in 'D:\Projects\Poseidon-Next User Experience\Work\UX.Entitlements\Applications\scope-management\node_modules\@azure\msal-angular\dist'
ERROR in ./node_modules/@azure/msal-angular/dist/broadcast.service.js
Module not found: Error: Can't resolve 'rxjs/add/operator/filter' in 'D:\Projects\Poseidon-Next User Experience\Work\UX.Entitlements\Applications\scope-management\node_modules\@azure\msal-angular\dist'
ERROR in ./node_modules/@azure/msal-angular/dist/broadcast.service.js
Module not found: Error: Can't resolve 'rxjs/add/operator/map' in 'D:\Projects\Poseidon-Next User Experience\Work\UX.Entitlements\Applications\scope-management\node_modules\@azure\msal-angular\dist'
ERROR in ./node_modules/@azure/msal-angular/dist/msal.interceptor.js
Module not found: Error: Can't resolve 'rxjs/add/operator/mergeMap' in 'D:\Projects\Poseidon-Next User Experience\Work\UX.Entitlements\Applications\scope-management\node_modules\@azure\msal-angular\dist'
ERROR in ./node_modules/@azure/msal-angular/dist/msal-guard.service.js
Module not found: Error: Can't resolve 'rxjs/add/operator/pairwise' in 'D:\Projects\Poseidon-Next User Experience\Work\UX.Entitlements\Applications\scope-management\node_modules\@azure\msal-angular\dist'
</code>
</pre>

## Library version

<pre><code>
Library version: @azure/msal-angular@0.1.0

## Current behavior
Throwing errors for improper usage of observables. 

## Expected behavior
The library should work as expected

## Minimal reproduction of the problem with instructions
Install the package via NPM and add to the app module. 

</code></pre>

**Comment by RobARichardson** [comment]
@tipsanemonk I had the same issue - was able to get around it for now by adding [rxjs-compat](https://github.com/ReactiveX/rxjs/tree/master/compat) to my application.

**Comment by tipsanemonk** [comment]
@RobARichardson Yes, in fact, I did the same to get my app running but I believe, this should come with the library dependency at least.

**Comment by nehaagrawal** [comment]
@tipsanemonk  Can you please confirm your application's angular version?

**Comment by maurei** [comment]
@nehaagrawal  Angular 7 has removed support for rxjs 5 thus adding `rxjs-compat` will not work. What are the chances of actually removing the dependency on `fromPromise` ? Afaik this is the only piece of code thats complaining.

I currently cannot use msal-angular with angular 7 :(

**Comment by CraigComeOnThisNameCantBeTaken** [comment]
+ would like to see this fixed to use this great package

**Comment by maurei** [comment]
@ccaymaz this is on my todo list, will get back at this as soon as I have figured it out.

**Comment by ccaymaz** [comment]
Thank you @maurei for your reply. Looking forward  to migrate my application to msal-angular.

**Comment by maurei** [comment]
(im not part of MSAL team, so it will probably be an ugly work around :) )

**Comment by navyasric** [comment]
This issue is related to #421
