### ISSUE TITLE
How to handle PERN(Postgres) authentication

### ISSUE THREAD

**Issue by zettry1** [AzureAD/microsoft-authentication-library-for-js#3920]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.0.0

### Description

Hello. My current app(Nodejs Web app) was using passport-azure-ad to signIn. Now I need to separate  into PERN stack assuming I successfully login using msal react at front-end how do I check authentication at the backend side,  Do I need to  login also backend side.
I could find related a tutorial Do you have example tutorial for MERN stack example?

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by zettry1** [comment]
@samuelkubai 
Hello, I am looking for a best practice.
For SPA app auth handled in the client side, and how do I protect my back-end side? Is there recommended way of request method for only authenticated user can  access to back-end api.

**Comment by derisen** [comment]
@zettry1 in that case, you don't really need to authenticate users to the backend -you only need to make sure they are "authorized" to access data on your backend. For that, the client app calls the backend with a valid access token, attached to the authorization header of the request, and the backend validates the token, and if the token is valid, responds with the data. This sample would be a good starting point: [React SPA calling Node.js web API](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/tree/main/3-Authorization-II/1-call-api)

**Comment by zettry1** [comment]
@derisen  Thanks, Looks like that is the only way :)
