### ISSUE TITLE
Is it possible to get an access token using client credential grant flow?

### ISSUE THREAD

**Issue by syatom** [AzureAD/microsoft-authentication-library-for-js#3927]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

1.4.12

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

None

### Description

I need to get an access token using the client credential grant flow from a React app, this seems impossible to do from the browser side, is there a way it can be done??

### Identity Provider

Other

### Source

External (Customer)

**Comment by samuelkubai** [comment]
Hi @syatom, you cannot use the client credential flow on the browser as this is a flow reserved for server side applications that can ensure the `clientSecret` or `clientCertificate` used is kept secure. Thus the flow is only available through the `ConfidentialApplication` which is only available in `msal-node`.

**Comment by syatom** [comment]
Ok thanks for the reply, I had a feeling that was going to be the answer.
