### ISSUE TITLE
Azure AD B2C Msal.js acquireTokenSilent Performance issue

### ISSUE THREAD

**Issue by srivathsanvlb** [AzureAD/microsoft-authentication-library-for-js#393]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version 68.0.3440.106
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: msal.js 0.1.3

## Current behavior

Works fine, able to get the access token and call my web api endpoints. But it takes 4-5 seconds to get the access token by using acquireTokenSilent  

## Expected behavior

acquireTokenSilent  should be able to get the access token faster

## Minimal reproduction of the problem with instructions

Have the details here
https://social.msdn.microsoft.com/Forums/en-US/22a53bc6-cd7d-4226-ba61-3ba84368dd8b/azure-ad-b2c-msaljs-acquiretokensilent-performance-issue?forum=WindowsAzureAD#1551122f-9a36-43c6-8d64-f94201e7c877

Have also opened one here
https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp/issues/20

</code></pre>

**Comment by srivathsanvlb** [comment]
Hi @nehaagrawal 

1. I researched a  bit and found that <script src="https://secure.aadcdn.microsoftonline-p.com/lib/0.1.7/js/msal.min.js"></script> is the latest version I am able to get via CDN. Even though Release notes says that the latest version is 0.2.1, I am not able to get it via CDN. Correct if I am wrong.

2. I am NOT able to see any considerable performance improvement after upgrade from 0.1.3 to 0.1.7

3. According to documentation, when app launches, I initialize
this.userAgentApplication = new Msal.UserAgentApplication(ServiceUrl.clientId, ServiceUrl.authority, this.authCallback, { cacheLocation: ServiceUrl.cacheLocation, loadFrameTimeout: ServiceUrl.loadFrameTimeout, navigateToLoginRequestUrl: false });

For every subsequent API call I use
return window.msal.acquireTokenSilent(ServiceUrl.b2cScopes).then((accessToken) => {});
To retrieve the access token and call my web api endpoints. 

 For each and every api call, when acquireTokenSilent is used, the entire app reloads and comes back to the "then" block. I have some scenarios, to call 2-3 api endpoints, to get data before loading the page. At that time, when I use the chrome debugger, I am able to see the app reloading for each call and executing the appropriate then blocks. 

Is there anything wrong in what I doing. Is there a way to avoid multiple reloads, I think that is the reason for the app getting too slow. Let me know if you need more info.

**Comment by nehaagrawal** [comment]
@srivathsanvlb  I will release the latest msal version to CDN in this week. MSAl reloading the app during acquireTokenSilent is a known issue and it's a miss on our side that this is not documented properly. Please see this [FAQ](https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/FAQs) from ADAL. This is also relevant to MSAL.  Basically you need to have if-else block to check if this reload is happening because of iframe.

**Comment by srivathsanvlb** [comment]
Hi @nehaagrawal 

Just wanted to clarify what I am doing is right.

1. Mine is a SPA with only one html ie index.html.
2. In that I have
    <script src="https://secure.aadcdn.microsoftonline-p.com/lib/0.1.7/js/msal.min.js"></script>
    <script type="module" src="Scripts/authenticate.js">
3. The authenticate.js, has the js class that does the authentication work. In its constructor I have

constructor() {
        if (window !== window.parent) {
            this.userAgentApplication = new Msal.UserAgentApplication(ServiceUrl.clientId);
        }
        else {
            this.userAgentApplication = new Msal.UserAgentApplication(ServiceUrl.clientId, ServiceUrl.authority, this.authCallback, { cacheLocation: ServiceUrl.cacheLocation, loadFrameTimeout: ServiceUrl.loadFrameTimeout, navigateToLoginRequestUrl: false });
        }
        if (document.getElementById('btnLogin') != null) {
            document.getElementById('btnLogin').addEventListener('click', () => {
                this.login();
            });
            document.getElementById('btnProceed').addEventListener('click', () => {
                this.callApi();
            });
        }
    }
4. On every acquiretokensilent call, the constructor still gets invoked (means app reloads) but does the if block gets called. First time else block is called, rest if block is called. Unfortunately this doesn't improve any performance. Am I missing something?

5. Since acquiretokensilent is causing the peformance issue, do you think I can call it only once during the app load and then store the accesstoken in window object and reuse it?

Thank you very much for helping me so far. Really appreciate it.

**Comment by kwaazaar** [comment]
Caching the access token yourself makes no sense, since this is MSAL's job (and automatically refreshing it once the cached token has expired).

It's very frustrating to see the samples are not working 100% and many Github issues are not answered or go silent for long periods. I'm wondering how serious Microsoft is with Azure AD B2C. I've just 'sold' it to my customer, being convinced MS will deliver. But getting pretty unsure that was a smart choice.

**Comment by sameerag** [comment]
@srivathsanvlb @kwaazaar 

We have recently gone through a redesign of the library's API surface. Please download our [latest preview package](https://www.npmjs.com/package/msal) or pull the [dev branch](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev) and try updating your code and see if the issue still persists. 

If you would like guidance on how to use the new version of the library, please review our wiki page [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL.js-1.0.0-preview-api-release).

We also have a working [B2C sample](https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp/tree/B2C_MsalJS_APIChanges) is picking the preview version if msal mentioned above. We are working on merging the branch soon to the main sample but please go ahead and try and let us know if you are still facing issues.

**Comment by sameerag** [comment]
Please reopen if the issue still persists.

**Comment by srivathsanvlb** [comment]
Thanks @sameerag for the reply. Good to see that msal.js has matured extensively.

I will give it a try and let you know on how it goes, but will take sometime since I have moved to a different project.
