### ISSUE TITLE
Failed authentication. AADSTS700081: The refresh token has expired due to maximum lifetime.

### ISSUE THREAD

**Issue by jonybekov** [AzureAD/microsoft-authentication-library-for-js#3931]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.15.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.1

### Description

I am getting "The refresh token has expired due to maximum lifetime." type of error after being inactive more than 24 hours. I've handled the edge case as mentioned in [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/3863#issuecomment-881045568).

### Error Message

**This is the error I get in the console**
Failed to load resource: the server responded with a status of 400 (Bad Request) https://login.microsoftonline.com/b41b72d0-4e9f-4c26-8a69-f949f367c91d/oauth2/v2.0/token

**Here's the server response.**
correlation_id: "889a429a-dfb0-433e-a7fd-efef79140410"
error: "invalid_grant"
error_codes: [700081]
0: 700081
error_description: "AADSTS700081: The refresh token has expired due to maximum lifetime. The token was issued on 2021-07-22T15:38:26.0767832+00:00 and the maximum allowed lifetime for this application is 1.00:00:00.\r\nTrace ID: ee926e4b-e9f7-4955-9fb1-28495db2b500\r\nCorrelation ID: 889a429a-dfb0-433e-a7fd-efef79140410\r\nTimestamp: 2021-08-05 12:59:49Z"
error_uri: "https://login.microsoftonline.com/error?code=700081"
suberror: "bad_token"
timestamp: "2021-08-05 12:59:49Z"
trace_id: "ee926e4b-e9f7-4955-9fb1-28495db2b500"
}

### MSAL Configuration

```javascript
const config: Configuration = {
  auth: {
    authority: `https://login.microsoftonline.com/${MsalConfig.APP_AAD}`,
    clientId: MsalConfig.ClientId,
    navigateToLoginRequestUrl: true,
  },
  cache: {
    cacheLocation: 'localStorage',
    storeAuthStateInCookie: true,
  },
};
```

### Relevant Code Snippets

```javascript
const { instance, accounts, inProgress } = useMsal();
const account = useAccount(accounts[0] || {});

useEffect(() => {
    if (inProgress === 'none' && accounts.length > 0) {
      // Retrieve an access token silently
      instance
        .acquireTokenSilent({
          ...authenticationParameters,
          account,
        })
        .then((response) => {
          if (response.accessToken) {
            getReport(response.accessToken);
            getVisual(response.accessToken);
          }
          return null;
        })
        .catch((err) => {
          if (err instanceof InteractionRequiredAuthError) {
            instance.acquireTokenRedirect(authenticationParameters);
          }
        });
    }

    // If user is not signed in then login using redirect method
    if (accounts.length === 0 && inProgress === 'none') {
      instance.loginRedirect(authenticationParameters);
    }
  }, [inProgress, accounts, instance]);
```

### Reproduction Steps

1. Authenticate using msal-react
2. Leave and come back after 24 hours

### Alternative solution
Clear cache and reload the page

### Expected Behavior

It should renew auth token silently or at least should redirect user to microsoft login page

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by happycollision** [comment]
How strange. I looked up this error since I am new to the `msal-browser` package. I rewrote my code to call `acquireTokenRedirect` in a very similar fashion as you have, and it works just fine.

Is it possible that your `.catch` function isn't even firing? It doesn't seem like that should be an issue with the code you have shown in your example, but I wonder if you try and log something inside your catch function, you might discover that it is never run at all.

Just a total shot in the dark.

**Comment by tnorling** [comment]
@jonybekov Where are you getting this error from? Is this being returned by an MSAL API or just in the network logs? This particular error should be caught and handled inside `acquireTokenSilent` and should never be returned by the API. If I had to guess based on the code you've shared, `acquireTokenSilent` is throwing a non InteractionRequired error which is why it's not redirecting on failure. Logs would be helpful here.

**Comment by jonybekov** [comment]
As I explained in the question, I'm getting them both, in the console and networks tab. I was also getting `Refused to display <Proxy target URL> in a frame because it set 'X-Frame-Options' to 'deny'` type of error in the console. We are using proxy and I thought that ignoring X-Frame-Options explicitly would help. Fortunately, it did. We re-configured our backend and set X-Frame-Options to SAMEORIGIN, the error above is appearing but refresh-token is being recovered successfully. However, we are thinking about how it can affect the security.
Is it supposed to work like this?

**Comment by tnorling** [comment]
@jonybekov 

> I'm getting them both, in the console and networks tab

The question is: is this being thrown from the MSAL API? As in, can you catch it in your code or is it just showing up in your browser dev tools? This error is not unexpected unless it is directly being thrown by `acquireTokenSilent`.

> I was also getting Refused to display <Proxy target URL> in a frame because it set 'X-Frame-Options' to 'deny' type of error in the console.

When the refresh token is expired `acquireTokenSilent` will fallback to the hidden iframe flow whereby it will open a hidden iframe on your page and navigate that iframe to your identity provider's sign in page. If the user has an active session cookie the IDP will redirect the iframe back to your application's redirectUri with the tokens. If your X-Frame-Options were blocking the page from being rendered in the iframe this is why the error was showing up in your console. If there are specific concerns around allowing your webpage to be rendered in an iframe I would suggest using a dedicated blank page as your redirectUri for silent API calls and allow only this page to be rendered in iframes.
