### ISSUE TITLE
[msal-react] AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'

### ISSUE THREAD

**Issue by cccs-cat001** [AzureAD/microsoft-authentication-library-for-js#3932]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.15.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.1

### Description

When using the msal-react library as defined, I get the title error upon logging in
```
AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'
```

### Error Message

AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.

### MSAL Configuration

```javascript
{
    auth: {
        clientId: "<client id>",
        authority: "https://login.microsoftonline.com/<tenant id>",
        redirectUri: "http://localhost:3000/",
        navigateToLoginRequestUrl: false
    },
    cache: {
        cacheLocation: "sessionStorage", // This configures where your cache will be stored
        storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
    },
    system: {	
        loggerOptions: {	
            loggerCallback: (level, message, containsPii) => {	
                if (containsPii) {		
                    return;		
                }		
                switch (level) {		
                    case LogLevel.Error:		
                        console.error(message);		
                        return;		
                    case LogLevel.Info:		
                        console.info(message);		
                        return;		
                    case LogLevel.Verbose:		
                        console.debug(message);		
                        return;		
                    case LogLevel.Warning:		
                        console.warn(message);		
                        return;		
                }	
            }	
        }	
    }
}
```

### Relevant Code Snippets

```javascript
I'm just running the example: https://github.com/Azure-Samples/ms-identity-javascript-react-spa
```

### Reproduction Steps

Follow the steps in the example repo: https://github.com/Azure-Samples/ms-identity-javascript-react-spa

### Expected Behavior

I'd expect it to successfully login. 

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Firefox

### Source

External (Customer)

**Comment by cccs-cat001** [comment]
.. Forgot to mention in the above that I saw this issue https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/3792 and attempted the fix from there, but that did not fix my issue.

**Comment by viktorlarsson** [comment]
Did you register an App on Azure AD?

**Comment by cccs-cat001** [comment]
Yeah it's set up on AAD, I have a redirect URL for SPA set up as http://localhost:3000

**Comment by tnorling** [comment]
@cccs-cat001 Do you happen to have other localhost reply urls registered or is that your only one?

**Comment by cccs-cat001** [comment]
Yeah I have other localhost ones registered, but not for SPA. I'm in the process of creating a replica app registration which will only have the one reply url to see if that fixes anything

**Comment by samuelkubai** [comment]
Hi @cccs-cat001, feel free to let us know if it fixes the problem.

**Comment by tnorling** [comment]
@cccs-cat001 Thanks for confirming. localhost is a special case in which the server treats localhost urls the same if the only difference is the port. (e.g. localhost:3000 is the same as localhost:4000) When you have multiple localhost urls registered under different app types the server will choose one at random to use which can result in the error you are experiencing if it didn't happen to choose the one registered as type SPA.

**Comment by cccs-cat001** [comment]
Sorry issue still isn't resolved, our cloud team is just taking a while to approve the app registration I'm trying to create

**Comment by cccs-cat001** [comment]
Looks like it works fine with just the one localhost redirect :)
