### ISSUE TITLE
msal logout not returning to login screen

### ISSUE THREAD

**Issue by skyshine999** [AzureAD/microsoft-authentication-library-for-js#3935]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.16.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

none

### Description

msal application doesn't land me in login screen.

### MSAL Configuration

```javascript
export const msalConfig: Configuration = {
  auth: {
    clientId:XXXXXXXXXXXXXX,
    authority:
      "https://login.microsoftonline.com/XXXXXXXXXXXXXXXXXX/",
    redirectUri: redirectUri,
    postLogoutRedirectUri: redirectUri,
  },
  cache: {
    cacheLocation: "localStorage",
    storeAuthStateInCookie: true,
  },
};
```

### Relevant Code Snippets

```javascript
let redirectUri = `${window.location.origin}/`;
const logoutRequest = {
  account: instance.getAccountByHomeId(accounts[0].homeAccountId),
  postLogoutRedirectUri: redirectUri,
};
instance.logoutRedirect(logoutRequest);
```

### Reproduction Steps

msal application logout

### Expected Behavior

msal application logout should redirect to login page

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by samuelkubai** [comment]
Hi @skyshine999, could you recreate this with one of our samples to better understand your code flow and usage?

**Comment by skyshine999** [comment]
I integrated msal in my current react app. Sometimes it is not returning to login screen and i added my react app in electron container there also same behaviour

**Comment by tnorling** [comment]
@skyshine999 In order for post logout redirection to occur you need to:
1. Register your `postLogoutRedirectUri` as a reply url on your app registration
2. Provide the `postLogoutRedirectUri` to the MSAL config and/or the logout API
3. Have a valid, unexpired session on the AAD server

Can you please verify that all 3 of these things are true? If so, please provide a `correlationId` and a timestamp for the logout request or email me a network trace (email is on my profile).
