### ISSUE TITLE
Guidance over status of passport-azure-ad?

### ISSUE THREAD

**Issue by DevRCRun** [AzureAD/microsoft-authentication-library-for-js#3939]
### Core Library

Passport Azure AD (passport-azure-ad)

### Core Library Version

na

### Wrapper Library

Not Applicable

### Wrapper Library Version

na

### Description

Hi

When we initially started looking into the feasibility of authenticating with aad from node last year I first looked at https://github.com/AzureAD/passport-azure-ad/ after following MS documentation / tutorial.

It appears that module is now living within  (or at least in the process of moving to) https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/maintenance/passport-azure-ad (correct me if I'm wrong! - this is a little confusing as there isn't any direct note on https://github.com/AzureAD/passport-azure-ad/ until you dig into the closed issues) 

We've since experimented with the msal-node module and see from viewing the sample at https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/ExpressTestApp that certain things, like validating tokens aren't yet done by msal-node but likely will be in the future per https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/3221

Could you provide some guidance as to how long the passport module now within this repo will be supported?  There are obviously other considerations to the decision, but I find myself in a place where I'm needing to choose between using the passport library, or implementing verification based on the sample / documentation coming back to remove that once the functionality is added into msal-node, per the discussion in 3221 (a timeframe for that would also be great!)

Apologies in advance if this is all clearly stated somewhere and I've just missed it.

Many thanks

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@DevRCRun Apologies for the confusion. Yes, we are moving the `passport-azure-ad` codebase to this repo, and will continue to support it (no set timeline at the moment), albeit the current version is in maintenance (i.e no new features or non-critical bug fixes) while we work on providing a new solution for validating tokens and other middleware functionality based on MSAL Node.

**Comment by DevRCRun** [comment]
Thanks for the reply and clarifying the documentation
