### ISSUE TITLE
MsalAuthenticationTemplate isn't working under Teams Desktop as Tab App

### ISSUE THREAD

**Issue by rhalaly** [AzureAD/microsoft-authentication-library-for-js#3943]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.16.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.1

### Description

`MsalAuthenticationTemplate` not working (nothing at all) under Teams Tab App in Teams Desktop

I'm using the code:
```
function ErrorComponent({ error }) {
  return (
    <p>An Error Occurred: {error}</p>
  );
}

function LoadingComponent() {
  return <p>Authentication in progress...</p>;
}

const loginRequest = {scopes: ['User.Read']};

<MsalAuthenticationTemplate
    authenticationRequest={loginRequest}
    errorComponent={ErrorComponent}
    interactionType={InteractionType.Redirect}
    loadingComponent={LoadingComponent}
    >
    <App />
</MsalAuthenticationTemplate>
```

Everything is working well in the browser. But since I use this component my Teams Tab App stopped working. 

It is not using the `loadingComponent` nor `errorComponent`, no redirect, and there are no issues in the console. But `App` isn't rendered at all.

### Error Message

Nothing...

### Msal Logs

Nothing...

### MSAL Configuration

```javascript
const msalConfig = {
  auth: {
    clientId: <private>,
    redirectUri: '/',
    postLogoutRedirectUri: '/',
  },
  cache: {
    cacheLocation: 'localStorage',
  },
};
```

### Relevant Code Snippets

```javascript
function ErrorComponent({ error }) {
  return (
    <p>An Error Occurred: {error}</p>
  );
}

function LoadingComponent() {
  return <p>Authentication in progress...</p>;
}

const loginRequest = {scopes: ['User.Read']};

<MsalAuthenticationTemplate
    authenticationRequest={loginRequest}
    errorComponent={ErrorComponent}
    interactionType={InteractionType.Redirect}
    loadingComponent={LoadingComponent}
    >
    <div>I'm logged in</div>
</MsalAuthenticationTemplate>
```

### Reproduction Steps

1. Create a simple app that use `MsalAuthenticationTemplate` component
2. Register a Teams Tab App and use the web app as the Tab content

### Expected Behavior

`MsalAuthenticationTemplate` will work under Teams Desktop like in the browser. At least will write some logs

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Other

### Source

Internal (Microsoft)

**Comment by pkanher617** [comment]
@rhalaly The Teams Tab may not support the MsalAuthenticationTemplate. We do have a sample [here](https://github.com/pnp/teams-dev-samples/tree/main/samples/tab-sso/src/nodejs) demonstrating using msal-browser and msal-react to sign in a user. There are updated instructions in [this PR](https://github.com/pnp/teams-dev-samples/pull/137) that may be easier to follow.

The redirect flow will not work inside of a teams tab, so the sample [demonstrates opening a popup and redirecting](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-tab-aad#initiate-authentication-flow) inside of that popup from the tab.

**Comment by rhalaly** [comment]
Thanks for your response, I will try that.

My goal is to create a website that can be **also** a Teams Tab. So I want to share the code as much as possible.

I tried to use the `allowRedirectInIframe` flag, but it throws an error that `X-Frame-Options` is `deny` in microsotonline.com...

**Comment by rhalaly** [comment]
@pkanher617 but I set the `allowRedirectInIframe` to `true` but it still not working. Actually, I tried the `popup` way, it seems to be blocked as well. 
When I use popup, it opens the Windows "Open With" dialog for some reason...

**Comment by rhalaly** [comment]
@pkanher617 I've tested the sample in your first message, but I get this error:

![image](https://user-images.githubusercontent.com/8597700/129028444-db41ac5a-7d33-4df6-9152-d786a5f59b7e.png)

**Comment by pkanher617** [comment]
Just to clarify - invoking popup or redirect APIs in MSAL directly from the Teams Tab will not work today, as popups are blocked inside the Teams Tab (using DOM APIs) and redirects are not allowed, regardless of the `allowRedirectInIframe` flag. You will need to open a popup window using the Teams Tab API and redirect inside of that popup. 

Regarding the device management error above, I'm not sure why this is being shown. There may be some specific policies tied to your account/application registration preventing this from working. Does this happen with a new app registration?

**Comment by rhalaly** [comment]
>Just to clarify - invoking popup or redirect APIs in MSAL directly from the Teams Tab will not work today, as popups are blocked inside the Teams Tab (using DOM APIs) and redirects are not allowed, regardless of the allowRedirectInIframe flag. You will need to open a popup window using the Teams Tab API and redirect inside of that popup.

OK, it seems to be working but sometimes I get the device management error (randomly?)

> Regarding the device management error above, I'm not sure why this is being shown. There may be some specific policies tied to your account/application registration preventing this from working. Does this happen with a new app registration?

No, it is not a new app. We have had this app for years as a web app, and I can sign it inside the browser. Now as a Teams app I get this device management error but sometimes

**Comment by tnorling** [comment]
@rhalaly Do you have a correlationId and a timestamp you can share?

**Comment by rhalaly** [comment]
How can I get them?

**Comment by tnorling** [comment]
@rhalaly You can click "More details" on the error screen and it should give you the details

**Comment by rhalaly** [comment]
Ok next time it happens I will notify you with all the details. I will close this issue now so it not be locked by your policy. This happens randomally so I don't now when it will appear next time
