### ISSUE TITLE
AcquireSilentToken Tokenresponse.accesstoken is empty

### ISSUE THREAD

**Issue by niketk** [AzureAD/microsoft-authentication-library-for-js#3952]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.15.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.1

### Description

 
We deployed msal.js changes in production. We are seeing an interesting issue reported by few users in Japan. The code requests a token for one of our apis and AAD actually returns it. However in our Gettoken function the tokenresponse.accesstoken is empty. The issue is reproduced on all browsers.
 
Fiddler trace to get token:
 
 
 
Fiddler trace with api : 
 
As you can see the api call isn’t executed before the token fetch.
 
 
 
Code :
 
There is no error and the code inside the then block is executed.
 
    const result = await MsalAuthHelper.msalInstance.acquireTokenSilent(request).then(tokenResponse => {
         AriaService.LogClientActionEvent('MsalAuthHelper', LogType.Information, 'GetToken success' + !isNil(tokenResponse.accessToken), resource);
         this.parseJwtAndPopulateUserProfile(tokenResponse.accessToken);
         return tokenResponse.accessToken;
 
I used the test credentials of the support engineer and I wasn’t able to reproduce the issue. But the support engineer using the same credentials always gets an empty token.
 

### Error Message

No errors. aad returns the token as per the trace

### Msal Logs

![fiddlertrace](https://user-images.githubusercontent.com/10676090/128909669-89496910-c12b-4fc5-9b8b-719114afa44a.png)
![fiddlertrace2](https://user-images.githubusercontent.com/10676090/128909674-a6da1b7d-7dc2-4b81-bae7-f772c6b97529.png)

### MSAL Configuration

```javascript
const ua = window.navigator.userAgent;
const msie = ua.indexOf('MSIE ');
const msie11 = ua.indexOf('Trident/');
const msedge = ua.indexOf('Edge/');
const firefox = ua.indexOf('Firefox');
const isIE = msie > 0 || msie11 > 0;
const isEdge = msedge > 0;
const isFirefox = firefox > 0; // Only needed if you need to support the redirect flow in Firefox incognito

const winExt = window as WindowExtensions;

// Config object to be passed to Msal on creation
export const msalConfig = {
    auth: {
        clientId: '3cf6df92-2745-4f6f-bbcf-19b59bcdb62a',
        authority: winExt?.configuration?.aadAuthority + 'common',
        postLogoutRedirectUri: '/',
        navigateToLoginRequestUrl: true
    },
    cache: {
        cacheLocation: 'localStorage',
        storeAuthStateInCookie: isIE || isEdge || isFirefox
    },
    system: {
        loggerOptions: {
            loggerCallback: (level: any, message: any, containsPii: any) => {
                if (containsPii) {
                    return;
                }
                switch (level) {
                    case LogLevel.Error:
                        AriaService.LogExceptionEvent(message, '', ErrorLevel.Medium, 'MSALAuthConfig');
                        return;
                    case LogLevel.Info:
                        AriaService.LogEvent(EventType.ClientAction, 'MSALAuthConfig', LogType.Information, '', '', message);
                        return;
                    case LogLevel.Verbose:
                        AriaService.LogEvent(EventType.ClientAction, 'MSALAuthConfig', LogType.Information, '', '', message);
                        return;
                    case LogLevel.Warning:
                        AriaService.LogEvent(EventType.ClientAction, 'MSALAuthConfig', LogType.Warning, '', '', message);
                        return;
                    default:
                        return;
                }
            }
        }
    }
};

// Add here scopes for id token to be used at MS Identity Platform endpoints.
export const loginRequest = {
    scopes: ['openid', 'profile']
};
```

### Relevant Code Snippets

```javascript
const result = await MsalAuthHelper.msalInstance.acquireTokenSilent(request).then(tokenResponse => {
         AriaService.LogClientActionEvent('MsalAuthHelper', LogType.Information, 'GetToken success' + !isNil(tokenResponse.accessToken), resource);
         this.parseJwtAndPopulateUserProfile(tokenResponse.accessToken);
         return tokenResponse.accessToken;
```

### Reproduction Steps

1. Login to https://config.office.com/officesettings using Admin account
2. Click on Inventory
3. Notice red banner

The error is happening only for users from Japan. Using the same creds from Redmond works.

### Expected Behavior

Expect to get a token for the inventory resource

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

Internal (Microsoft)

**Comment by pkanher617** [comment]
@niketk Could you provide some logs from the browser? This can help us see if the response is being processed successfully. It appears the server is returning an access token from the images of the trace, but MSAL isn't handling it correctly and returning a blank access token when processing the response. This may be due to a caching bug. 

If you can, please send me the whole fiddler trace in an email, which is available in my Github profile description.

**Comment by niketk** [comment]
Hi Prithvi

You can access the full trace here : \\NIKETKWIN10DEV2\msal-jaissue<file://NIKETKWIN10DEV2/msal-jaissue>

Thanks
NIket

Sent from Outlook<http://aka.ms/weboutlook>

**Comment by niketk** [comment]
Hi @Prithvi ***@***.***> - any update on this issue ? This is impacting customers in our portal.

Thanks
Niket

From: Niket Kalgaonkar
Sent: Tuesday, August 10, 2021 9:43 PM
To: AzureAD/microsoft-authentication-library-for-js ***@***.***>; AzureAD/microsoft-authentication-library-for-js ***@***.***>; Prithvi Kanherkar ***@***.***>
Cc: Mention ***@***.***>; Jason Nutter ***@***.***>
Subject: RE: [AzureAD/microsoft-authentication-library-for-js] AcquireSilentToken Tokenresponse.accesstoken is empty (#3952)


Hi Prithvi

You can access the full trace here : \\NIKETKWIN10DEV2\msal-jaissue<file://NIKETKWIN10DEV2/msal-jaissue>

Thanks
NIket

Sent from Outlook<http://aka.ms/weboutlook>
