### ISSUE TITLE
`MsalBroadcastService#inProgress$` can be stuck in `InteractionStatus#HandleRedirect`

### ISSUE THREAD

**Issue by ClemensSchneider** [AzureAD/microsoft-authentication-library-for-js#3961]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.16.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.2

### Description

`MsalBroadcastService#inProgress$` can be stuck in `InteractionStatus#HandleRedirect`.
I cannot provide a repo to reproduce the issue, but when looking at the code and its execution flow, it gets clear that this is possible to happen.

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/0f313aa216ad9620c3e46a028516bb02bc3d118c/lib/msal-browser/src/app/ClientApplication.ts#L128

Here, RedirectStart is emitted.

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/0f313aa216ad9620c3e46a028516bb02bc3d118c/lib/msal-browser/src/app/ClientApplication.ts#L139

Further down, when handling the response, in case the response is undefined, events are emitted as expected. But in case the response has already been processed and the processing promise has already emitted the follow-up events, we'll be stuck with the RedirectStart state.

Shouldn't the RedirecteStart event be only emitted in case the response hasn't already been processed?

### MSAL Configuration

```javascript
...
```

### Relevant Code Snippets

```javascript
...
```

### Reproduction Steps

...

### Expected Behavior

InteractionStatus should never be stuck in a state not allowing the client to recover from.

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@ClemensSchneider While we haven't been able to reproduce this behavior either, we agree that this merits more investigation, and will add it to our backlog.
