### ISSUE TITLE
`no_tokens_found` when using `acquireTokenSilent` or `logoutRedirect` with `Office.Dialog` API

### ISSUE THREAD

**Issue by kdmadej** [AzureAD/microsoft-authentication-library-for-js#3962]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.16.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

I've implemented authentication flow in an Excel add-in using `Office.Dialog` API. The sign in flow seems to be working just fine – the add-in is able to perform actions that require authentication after the user signs in within the dialog (using the `loginRedirect()` flow).

However, using `acquireTokenSilent()` in the add-in when it loads (after signing in ofc) and using `logoutRedirect` in the dialog result in a `no_tokens_found` error and at this point I'm not even sure how to debug the issue.

None of those issues occur when using the popup methods (`loginPopup`, `logoutPopup`) – `acquireTokenSilent` works just fine then (as well as the logout flow).

Any suggestions on how to proceed or what more info I should provide to make sure this is not an msal issue will be greatly appreciated.

### Error Message

// add-in when performing silent-auth after loading
ClientAuthError: no_tokens_found: No tokens were found for the given scopes, and no authorization code was passed to acquireToken. You must retrieve an authorization code before making a call to acquireToken().
    at ClientAuthError.AuthError [as constructor] (AuthError.js:27)
    at new ClientAuthError (ClientAuthError.js:194)
    at Function.ClientAuthError.createNoTokensFoundError (ClientAuthError.js:289)
    at RefreshTokenClient.<anonymous> (RefreshTokenClient.js:98)
    at step (_tslib.js:75)
    at Object.next (_tslib.js:56)
    at _tslib.js:49
    at initializePromise (es6-promise.js:437)
    at new Promise (es6-promise.js:865)
    at __awaiter (_tslib.js:45)

// dialog when performing logout redirect
index.ts:82 ClientAuthError: no_account_found: No account found in cache for given key.
    at ClientAuthError.AuthError [as constructor] (AuthError.js:27)
    at new ClientAuthError (ClientAuthError.js:194)
    at Function.ClientAuthError.createNoAccountFoundError (ClientAuthError.js:383)
    at BrowserCacheManager.CacheManager.removeAccount (CacheManager.js:302)
    at AuthorizationCodeClient.getLogoutUri (AuthorizationCodeClient.js:111)
    at PublicClientApplication.<anonymous> (ClientApplication.js:690)
    at step (_tslib.js:75)
    at Object.next (_tslib.js:56)
    at fulfilled (_tslib.js:46)
    at invokeCallback (es6-promise.js:408)

### Msal Logs

// add-in when performing silent-auth after loading

[Wed, 11 Aug 2021 11:19:17 GMT] : @azure/msal-browser@2.16.1 : Verbose - preflightBrowserEnvironmentCheck started
[Wed, 11 Aug 2021 11:19:17 GMT] : @azure/msal-browser@2.16.1 : Verbose - acquireTokenSilent called
[Wed, 11 Aug 2021 11:19:17 GMT] : @azure/msal-browser@2.16.1 : Verbose - acquireTokenSilent called for the first time, storing active request
[Wed, 11 Aug 2021 11:19:17 GMT] : @azure/msal-browser@2.16.1 : Verbose - Initializing BaseAuthRequest
[Wed, 11 Aug 2021 11:19:17 GMT] : @azure/msal-browser@2.16.1 : Verbose - Authentication Scheme wasn't explicitly set in request, defaulting to "Bearer" request
[Wed, 11 Aug 2021 11:19:17 GMT] : @azure/msal-browser@2.16.1 : Info - Emitting event: msal:acquireTokenStart
[Wed, 11 Aug 2021 11:19:17 GMT] : [8a874eaa-5539-4d0d-8657-a47491a8450b] : @azure/msal-browser@2.16.1 : Verbose - initializeServerTelemetryManager called
[Wed, 11 Aug 2021 11:19:17 GMT] : [8a874eaa-5539-4d0d-8657-a47491a8450b] : @azure/msal-browser@2.16.1 : Verbose - getClientConfiguration called
[Wed, 11 Aug 2021 11:19:17 GMT] : [8a874eaa-5539-4d0d-8657-a47491a8450b] : @azure/msal-browser@2.16.1 : Verbose - getDiscoveredAuthority called
[Wed, 11 Aug 2021 11:19:17 GMT] : [8a874eaa-5539-4d0d-8657-a47491a8450b] : @azure/msal-browser@2.16.1 : Verbose - Creating discovered authority with request authority
[Wed, 11 Aug 2021 11:19:17 GMT] : [8a874eaa-5539-4d0d-8657-a47491a8450b] : @azure/msal-browser@2.16.1 : Verbose - Silent auth client created
[Wed, 11 Aug 2021 11:19:17 GMT] : @azure/msal-browser@2.16.1 : Info - Emitting event: msal:acquireTokenFromNetworkStart
[Wed, 11 Aug 2021 11:19:17 GMT] : [8a874eaa-5539-4d0d-8657-a47491a8450b] : @azure/msal-browser@2.16.1 : Verbose - Initializing BaseAuthRequest
[Wed, 11 Aug 2021 11:19:17 GMT] : [8a874eaa-5539-4d0d-8657-a47491a8450b] : @azure/msal-browser@2.16.1 : Verbose - Authentication Scheme set to "Bearer" as configured in Auth request
[Wed, 11 Aug 2021 11:19:17 GMT] : [8a874eaa-5539-4d0d-8657-a47491a8450b] : @azure/msal-browser@2.16.1 : Verbose - initializeServerTelemetryManager called
[Wed, 11 Aug 2021 11:19:17 GMT] : [8a874eaa-5539-4d0d-8657-a47491a8450b] : @azure/msal-browser@2.16.1 : Verbose - getClientConfiguration called
[Wed, 11 Aug 2021 11:19:17 GMT] : [8a874eaa-5539-4d0d-8657-a47491a8450b] : @azure/msal-browser@2.16.1 : Verbose - getDiscoveredAuthority called
[Wed, 11 Aug 2021 11:19:17 GMT] : [8a874eaa-5539-4d0d-8657-a47491a8450b] : @azure/msal-browser@2.16.1 : Verbose - Creating discovered authority with request authority
[Wed, 11 Aug 2021 11:19:17 GMT] : [8a874eaa-5539-4d0d-8657-a47491a8450b] : @azure/msal-browser@2.16.1 : Verbose - Refresh token client created
[Wed, 11 Aug 2021 11:19:17 GMT] : @azure/msal-browser@2.16.1 : Info - Emitting event: msal:acquireTokenFailure

// dialog when performing logout redirect
[Wed, 11 Aug 2021 12:07:02 GMT] : @azure/msal-browser@2.16.1 : Verbose - preflightBrowserEnvironmentCheck started
[Wed, 11 Aug 2021 12:07:02 GMT] : @azure/msal-browser@2.16.1 : Verbose - logoutRedirect called
[Wed, 11 Aug 2021 12:07:02 GMT] : @azure/msal-browser@2.16.1 : Verbose - initializeLogoutRequest called
[Wed, 11 Aug 2021 12:07:02 GMT] : [c73dcb25-3777-4da5-b8b6-cf2abee61609] : @azure/msal-browser@2.16.1 : Verbose - Setting postLogoutRedirectUri to configured uri
[Wed, 11 Aug 2021 12:07:02 GMT] : [c73dcb25-3777-4da5-b8b6-cf2abee61609] : @azure/msal-browser@2.16.1 : Verbose - initializeServerTelemetryManager called
[Wed, 11 Aug 2021 12:07:02 GMT] : @azure/msal-browser@2.16.1 : Info - Emitting event: msal:logoutStart
[Wed, 11 Aug 2021 12:07:02 GMT] : [c73dcb25-3777-4da5-b8b6-cf2abee61609] : @azure/msal-browser@2.16.1 : Verbose - getClientConfiguration called
[Wed, 11 Aug 2021 12:07:02 GMT] : [c73dcb25-3777-4da5-b8b6-cf2abee61609] : @azure/msal-browser@2.16.1 : Verbose - getDiscoveredAuthority called
[Wed, 11 Aug 2021 12:07:02 GMT] : [c73dcb25-3777-4da5-b8b6-cf2abee61609] : @azure/msal-browser@2.16.1 : Verbose - Creating discovered authority with configured authority
[Wed, 11 Aug 2021 12:07:02 GMT] : [c73dcb25-3777-4da5-b8b6-cf2abee61609] : @azure/msal-browser@2.16.1 : Verbose - Auth code client created
[Wed, 11 Aug 2021 12:07:02 GMT] : @azure/msal-browser@2.16.1 : Info - Emitting event: msal:logoutFailure

### MSAL Configuration

```javascript
{
    "auth": {
        "authority": "https://login.microsoftonline.com/e40...",
        "clientId": "77f...",
        "redirectUri": "https://localhost:3000/login.html",
        "postLogoutRedirectUri": "https://localhost:3000/login.html?logout"
    },
    "system": {
        "loggerOptions": {
            "logLevel": 3
        }
    }
}
```

### Relevant Code Snippets

```javascript
// when silently acquiring a token
const request: PopupRequest = {
  account: authState.account ?? undefined,
  scopes: [authConfig.scope],
};
try {
  const authResult = await msalInstance.acquireTokenSilent(request);
  // ... persists the `authResult`
} catch (error) {
  // ... cleans the persisted auth state
}

// login + logout flows inside the dialog
// dispatchToHost is a helper method that ensures a convention for the messages sent between the host add-in and the dialog
const handleLogin = async (): Promise<void> => {
  try {
    const response = await msalInstance.handleRedirectPromise();

    if (response) {
      dispatchToHost(authLoginSuccess(response));
    } else {
      msalInstance.loginRedirect({
        scopes: [authConfig.scope],
      });
    }
  } catch (error) {
    const errorMessage: string = prepareErrorMessage(error);
    dispatchToHost(authLoginFailure(errorMessage));
  }
};

const handleLogout = async ({
  accountInfo,
}: HandleLogoutArgs): Promise<void> => {
  try {
    const response = await msalInstance.handleRedirectPromise();

    if (response) {
      dispatchToHost(authLogoutSuccess());
    } else {
      await msalInstance.logoutRedirect({
        account: accountInfo,
      });
    }
  } catch(error) {
    console.error(error)
    const errorMessage: string = prepareErrorMessage(error);

    dispatchToHost(authLogoutFailure(errorMessage));
  }
};
```

### Reproduction Steps

1. sign in with a redirect flow inside a new window opened using `Office.Dialog` API
2. try to acquire a token silently or log out with a redirect flow inside a new window opened using `Office.Dialog` API

### Expected Behavior

`acquireTokenSilent` getting the access token and `logoutRedirect` logging the user out.
Both without the `no_tokens_found` error.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer

### Source

External (Customer)

**Comment by pkanher617** [comment]
Are you calling `handleRedirectPromise` before the `acquireTokenSilent` method when coming back from a successful login? The app needs to resolve the `handleRedirectPromise()` Promise before attempting to retrieve something from the cache with `acquireTokenSilent`.

**Comment by kdmadej** [comment]
I'm not calling `acquireTokenSilent` after coming back from a successful login. I'm using a dialog-based flow as described [here](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins) and [here](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/auth-with-office-dialog-api).

The login/logout flows are performed using the redirect methods in a separate window. `acquireTokenSilent` is used inside the add-in when it loads so the user doesn't have to manually go through the sign in flow. At least that was my intention.

**Comment by tnorling** [comment]
@kdmadej I'm noticing in your config you haven't specified a cache location (default is `sessionStorage`). This is very likely your issue. Can you try setting cache location to `localStorage` in your config? If you haven't seen this already you may also find [this sample](https://github.com/OfficeDev/PnP-OfficeAddins/tree/main/Samples/auth/Office-Add-in-Microsoft-Graph-React), which demonstrates using `msal-browser` in an Office add-in, helpful.

**Comment by kdmadej** [comment]
Oh boy... of course! 🤦‍♂️  I was so sure I set it that my mind just kept skipping over that part of the code.
This fixed the issue right away! Thank you so much for your help and sorry for the trouble 🙈

**Comment by tnorling** [comment]
Thanks for confirming that fixed it! Closing.
