### ISSUE TITLE
Skip authentication when writing UI tests in cypress

### ISSUE THREAD

**Issue by JamesBaxterSoftware** [AzureAD/microsoft-authentication-library-for-js#3968]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.15.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.1

### Description

I have setup msal-broswer and msal-react authentication and it's working well but we need to be able to skip authentication so we can test features in isolation via cypress/selenium and not have to spend 10-15 seconds logging in via the UI each time a test spec is ran. Is there any information on doing this? My initial thoughts would be to mock out the msal provider and msal context to return a token/account which I would use ROPC policy to populate but no idea if/how this would work right now? thanks

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by pkanher617** [comment]
@JamesBaxterSoftware We have some docs [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/testing.md) around sideloading tokens in v2.17.0. You can use this to initialize the msal cache for testing, as well as implement some level of mocking as you said.

**Comment by afoures** [comment]
it seems that the v2.17.0 is not published, when will it be available ?

**Comment by tnorling** [comment]
@afoures We typically release new versions on the first Monday of the month, making the next release scheduled for 9/6. If you need a solution before then we also have a sample [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-browser-samples/TestingSample/test/browser-test.spec.ts) demonstrating how you can obtain tokens using msal-node's ROPC flow and sideload them into the browser manually. Hope that helps!
