### ISSUE TITLE
MsalAuthenticationTemplate is rendering children despite having logged out in other tab

### ISSUE THREAD

**Issue by mleimer** [AzureAD/microsoft-authentication-library-for-js#3969]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.16.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.1

### Description

MsalAuthenticationTemplate does not get reevaluated upon reoping the browser tab containing that component.
This is a problem for NextJS applications using the SWR-Library with an MSAL-Access-Token to fetch data, as data is refetched upon focus.

### MSAL Configuration

```javascript
{
  auth: {
    clientId: `${process.env.NEXT_PUBLIC_AUTH_CLIENT_ID}`,
    authority: MSAL_AUTHORITY_SIGNIN_SIGNUP,
    knownAuthorities: [`${process.env.NEXT_PUBLIC_AUTH_TENANT_URL}`],
    redirectUri: process.env.NEXT_PUBLIC_AUTH_REDIRECT_URL,
    navigateToLoginRequestUrl: true,
  },
  cache: {
    cacheLocation: 'localStorage',
  },
};
```

### Relevant Code Snippets

```javascript
<MsalAuthenticationTemplate
    interactionType={InteractionType.Redirect}
    authenticationRequest={{
        scopes: SCOPES,
        redirectUri: MSAL_CONFIG.auth.redirectUri,
        extraQueryParameters: { ui_locales: locale },
        prompt: 'select_account',
    }}
    errorComponent={x}
    loadingComponent={y}
>
    {children}
</MsalAuthenticationTemplate>
```

### Reproduction Steps

Given a React or Next.JS Application similar to the sample https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/nextjs-sample

1.) Open the browser
2.) Open a page / route containing `MsalAuthenticationTemplate` using `InteractionType.Redirect`
3.) Login & await Login to be successful
4.) Open a new tab and open the same page / route as in the first tab
=> You are immediately logged in in the second tab due to `cacheLocation: 'localStorage'`

5.) Logout in tab 2 & await Logout to be completed
6.) Switch to tab 1
=> MsalAuthenticationTemplate is still rendering the child
=> useIsAuthenticated() hook is still returning true

### Expected Behavior

=> The children of MsalAuthenticationTemplate are not rendered as user logged out in tab 2 and access token is shared through local storage.
=> useIsAuthenticated() hook returns false

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by jasonnutter** [comment]
In step 6, are you refreshing the page?

**Comment by mleimer** [comment]
@jasonnutter: No, I just open the browser tab without conditional or explicit page reload / refresh.

Due to the nature of how SWR works (in its default configuration), it will revalidate all data requested by child components upon focus (eg. when opening a browser tab with a page where those child components are rendered in). This then fails when it wants to try to get an access token, as there is obviously none because the user has logged out in the other tab before.

I would like to try to avoid to create my own wrapper component where I listen on the visiblitychange event of the window and read out the msalInstance.getActiveAccount() to identify if the children may still be rendered or not.

**Comment by tnorling** [comment]
@mleimer The components we provide are meant to cover the most common use cases and may not meet all your requirements. The logic you describe is something you will likely need to implement yourself. What is the desired behavior when tab 1 is refocused? If `MsalAuthenticationTemplate` thinks no user is signed in it will auto redirect back to the login screen to attempt to sign a user in. That sounds undesirable after just logging out, no?

**Comment by mleimer** [comment]
@tnorling May I ask how I can implement said logic myself. Is it sufficient just to check whether there is at least 1 account or an active account and/or should I also try to fetch an access token to identify if a user is still authorized or not?

Actually, the redirect to the login screen upon opening tab 1 again is desired in our use case. I understand that other teams might want to have special behaviors like forwarding the user to a special logout screen or alike. However, I disbelief that the common scenario should be to pretend that the user is logged in when he has logged out from another tab.

Kindly note that the issue also exists the other way round. E.g. if I am logged out in tab 1 and 2; When I log in in tab 2; the useIsAuthenticated-Hook in tab 1 still returns "false" because it does not get refreshed either upon opening tab 1.

Maybe this could be considered for a future improvement to fully support multiple tabs?

**Comment by tnorling** [comment]
@mleimer 

> May I ask how I can implement said logic myself. Is it sufficient just to check whether there is at least 1 account or an active account and/or should I also try to fetch an access token to identify if a user is still authorized or not?

Checking if there is 1 account or an active account should be sufficient to tell you whether or not you need to "login". When you need a token the pattern should always be to call `acquireTokenSilent` and if that fails call `acquireTokenRedirect` or `acquireTokenPopup`.

> Kindly note that the issue also exists the other way round. E.g. if I am logged out in tab 1 and 2; When I log in in tab 2; the useIsAuthenticated-Hook in tab 1 still returns "false" because it does not get refreshed either upon opening tab 1.
>Maybe this could be considered for a future improvement to fully support multiple tabs?

I agree this does sound like a reasonable request. I'll mark this as an enhancement and see what can be done on our end to better support these scenarios.
