### ISSUE TITLE
How to (correctly) get an access token with "aud" claim set to AAD app registration's ClientId?

### ISSUE THREAD

**Issue by scale-tone** [AzureAD/microsoft-authentication-library-for-js#3972]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.15.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

.

### Description

The scenario is the simplest ever: 
* Azure Function App acting as an API and protected by [EasyAuth](https://docs.microsoft.com/en-us/azure/app-service/overview-authentication-authorization) module.
* Client-side JavaScript SPA, that only wants to call that API. To uderscore: it doesn't need to call MS Graph or anything else, just its own backend - it is that simple.

To make that work I need an access token, that has `my-client-id` set as an audience, where `my-client-id` is a GUID and nothing else. I need it to be like that, because a) this is how EasyAuth Express setup always worked - default audience value was always set to relevant ClientId and b) my app is already deployed en-masse across the globe, I can't afford breaking those deployments (all using their own AAD app registrations) with a new version that now uses MSAL.js v2 and c) this basic scenario was supported like that by adal.js, msal.js v1 etc. ever since.

I could instead use the id_token, but for some reason this approach is [not recommended](https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens) (why?).

After tons of experiments, I managed to get a proper access token by setting scopes = ['my-client-id/.default'] :
![image](https://user-images.githubusercontent.com/5447190/129594504-a7253850-6898-4d43-a447-5d457a5872a4.png)

**Question: did I get it right?**
Is this the recommended approach? If yes, is it documented somewhere? 
Is there a code sample, that illustrates this exact flow (digged through the entire repo and all the docs and failed to find any - all samples concentrate on calling MS Graph/other external APIs)?

### Relevant Code Snippets

```javascript
const tokenRequest = {
    scopes: [`2437fdc6-a893-42b9-adf8-4b807b8e3515/.default`],
};
```

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
@scale-tone The way to do this is to expose an API on your app registration and request this custom scope when acquiring a token using MSAL. [This tutorial](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-configure-app-expose-web-apis) walks you through the process of exposing an API on your app registration.

**Comment by scale-tone** [comment]
Thanks @tnorling , but as I was trying to explain, **this is not an option**.
I do not have control over those hundreds of AAD app registrations out there and I do not have an option to drop backward compatibility. I can't just break all those deployments with a new version and then say 'hey, you now need to add custom scopes to your AAD app'.

Do you have any better ideas?

**Comment by tnorling** [comment]
@scale-tone How are the existing apps working today? What scopes are they requesting?

**Comment by scale-tone** [comment]
@tnorling , as I was trying to explain, with adal.js and msal.js v1 people have always just put AAD app registration's ClientId (plain GUID) as a requested scope. This matched well EasyAuth Express settings. And always resulted in an access token containing that ClientId in its `aud` claim.

To underscore again, there're billions of existing AAD app registrations out there, that do not have any custom scopes defined. It would be **very customer-unfriendly** to break all of these.

**Comment by tnorling** [comment]
@scale-tone In Adal.js and Msal.js v1 requesting clientId as scope results in an `idToken` **not** an `accessToken`. Msal.js v1 API may return the token in the `accessToken` field but if you crack it open (using jwt.ms or other jwt decoder) you'll see that it is actually an `idToken`. To avoid breaking changes during migration to v2, use the `idToken`. However, idTokens should be used to identify users not to secure APIs, so if you are currently using idTokens to obtain access to APIs you may need to come up with a migration plan to using access tokens if you want to do this correctly moving forward.

**Comment by scale-tone** [comment]
> Msal.js v1 API may return the token in the accessToken field but if you crack it open (using jwt.ms or other jwt decoder) you'll see that it is actually an idToken

OK, that was my suspicion as well...

> However, idTokens should be used to identify users not to secure APIs, 

Can you explain *why exactly they should not* be used? I mean, I know, that the documentation page says so, but it doesn't explain that either. Are they less secure or what?

>  you may need to come up with a migration plan to using access tokens if you want to do this correctly moving forward.

As I was trying to explain, the above-described workaround with `client-id/.default` scope does produces an actual **access token** (not an id_token). 
Are you saying that this approach is not recommended, should be avoided and might suddenly stop working at some point?

**Comment by tnorling** [comment]
@scale-tone 

> Can you explain why exactly they should not be used? I mean, I know, that the documentation page says so, but it doesn't explain that either. Are they less secure or what?

IdTokens only contain information about **who** the user is, not about **what** they can access (scopes). There's also the issue of validating tokens, the API should only ever accept tokens issued for its own clientId and reject those that don't match.
Access tokens can also benefit from additional security mechanisms including [Proof of Possession](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/access-token-proof-of-possession.md)

> As I was trying to explain, the above-described workaround with client-id/.default scope does produces an actual access token (not an id_token).
Are you saying that this approach is not recommended, should be avoided and might suddenly stop working at some point?

The `/.default` scope means "give me an access token for every scope registered on this app registration for this resource". If that's what you want, this is a fine approach. It does mean, however, that if you add scopes to your app registration, for this resource in the future your users will be prompted for consent to the new scopes at that time. It is usually recommended practice to request only as much permission as you need, when you need it. (If you only have a single API this may be irrelevant). You can read more about the `/.default` scope [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent#the-default-scope)

**Comment by scale-tone** [comment]
> Access tokens can also benefit from additional security mechanisms including Proof of Possession

This makes sense, thanks for explanation.

>  if you add scopes to your app registration, for this resource in the future your users will be prompted for consent to the new scopes at that time. It is usually recommended practice to request only as much permission as you need, when you need it. (If you only have a single API this may be irrelevant)

Again, yes, here we're talking about the simplest yet most typical "SPA+its own API" scenario, where the app registration doesn't have nor will ever have any custom scopes. Therefore this approach really seems to be the way to go. I suggest it to be explicitly documented and/or illustrated with a dedicated sample.

**Comment by tnorling** [comment]
@scale-tone You'll find a sample for this scenario [here](https://github.com/Azure-Samples/ms-identity-javascript-tutorial#chapter-3-protect-an-api-and-call-the-api-from-your-client-app). Closing as the original question has been answered.

**Comment by scale-tone** [comment]
Thanks, @tnorling , but again, as I was trying to explain, that sample requires creating custom scopes.
The goal is to _avoid_ requiring that, so that your library **remains backward-compatible**.

People are very much outraged already by this never-ending migration saga (adal->msal v1->msal v2->...) , can we please try to not complicate things even more?
