### ISSUE TITLE
npmjs has no licence for @azure/msal-angular

### ISSUE THREAD

**Issue by StefanSchoof** [AzureAD/microsoft-authentication-library-for-js#3976]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Documentation Location

https://www.npmjs.com/package/@azure/msal-angular

### Description

![grafik](https://user-images.githubusercontent.com/4662023/129725548-cc27837c-b3be-4ac9-8709-e113a7045586.png)

On https://www.npmjs.com/package/@azure/msal-angular the License field says None, but in 
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/LICENSE a MIT License is located.

**Comment by tnorling** [comment]
@StefanSchoof Thanks for pointing this out. Will make sure this gets addressed.
