### ISSUE TITLE
The token can't be found in request header

### ISSUE THREAD

**Issue by zhshqzyc** [AzureAD/microsoft-authentication-library-for-js#3979]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0

### Description

I use MsalInterceptor to do authentication. I can see the token the localstorage but in Network TAB, click any api it won't show the token in the header. I am not sure if it related protectedResourceMap.

I have tried 
```
protectedResourceMap.set('https://graph.microsoft.com/v1.0/me', [
     'user.read',
   ]);
```
or if the endpoint is localhost:4200/api/projects, but I have many endpoints.
```
protectedResourceMap.set('/api/', [
     'user.read',
   ]);
```

### Relevant Code Snippets

```javascript
const protectedResourceMap = new Map<string, Array<string>>();
   protectedResourceMap.set('https://graph.microsoft-ppe.com/v1.0/me', ['user.read']);

export function MSALGuardConfigFactory(): MsalGuardConfiguration {
  return { 
    interactionType: InteractionType.Popup,
    authRequest: {
      scopes: ['user.read']
    }
  };
}

providers: [
    {
      provide: HTTP_INTERCEPTORS,
      useClass: MsalInterceptor,
      multi: true
    },
    {
      provide: MSAL_INSTANCE,
      useFactory: MSALInstanceFactory
    },
    {
      provide: MSAL_GUARD_CONFIG,
      useFactory: MSALGuardConfigFactory
    },
    {
      provide: MSAL_INTERCEPTOR_CONFIG,
      useFactory: MSALInterceptorConfigFactory
    },
    MsalService,
    MsalGuard,
    MsalBroadcastService
  ],
```

### Source

External (Customer)

**Comment by tnorling** [comment]
@zhshqzyc Can you please provide your msal configuration? The code snippet you shared does not show where you are providing the `protectedResourceMap` to msal. Please review [this doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/msal-interceptor.md) for interceptor usage directions.

**Comment by zhshqzyc** [comment]
It is something like
```
export function MSALInstanceFactor(): IPublicClientApplication {
      return new PublicClientApplication(
          auth: {
               clientId: id,
               authority: 'https://login.microsoftonline.com/2eerrrrrrtr/',
               redirectUri: windows.location.origin
         },
        cache: { 
              cacheLocation: 'localStorage'
        }
}
```
and
```
export function MSALInterceptorConfigFactor(): MsalInterceptorConfiguration {
      const protectedResourceMap = new Map<string, Array<string>>();
      protectedResourceMap.set('https://graph.microsoft.com/ v1.0/me', ['user.read']);
      protectedResourceMap.set('http://localhost:4200/apps/project', ['user.read']);
      return {
            interactionType: InteractionType.Popup,
            protectedResourceMap 
     };
 }
```

**Comment by tnorling** [comment]
@zhshqzyc Are both the graph api call and your app's api call missing the access token, or is it just your own local api call that's not working as expected? Also you should not send your Graph access token (User.Read scope) to your own api. That token is intended only for MS Graph. 

Please provide a link to a minimal reproduction of this issue using one of our samples [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples) so we can help you debug. Thanks!

**Comment by zhshqzyc** [comment]
try https://github.com/zhshqzyc/FullStack

**Comment by tnorling** [comment]
@zhshqzyc Each resource (MS Graph or your API) has their own scopes (permissions) associated with them. User.Read, for example, is a MS Graph scope and is used to acquire an access token for MS Graph. If you are implementing your own custom API you need to create a custom scope on your app registration and request that. "customscope.read" is meaningless unless you've previously created a scope with that name. Read more about scopes and resources [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/resources-and-scopes.md). 

Given the above, the token is not being added to your headers because you haven't acquired an access token with the given scopes (because the scope doesn't exist). First, expose an api on your app registration and add the new scope(s) as permissions, then update your protectedResourceMap to request this new scope when calling your custom API.

**Comment by zhshqzyc** [comment]
We are close the final line. Say the clientId is `d16e1a06-3be2-4ae1-8bd4-718c19cecac3` Please tell me which one is correct if I want use wildcard for all? 
One
` protectedResourceMap.set('http://localhost:8080/api', ['api://d16e1a06-3be2-4ae1-8bd4-718c19cecac3/api']);`
Two
 ` protectedResourceMap.set('http://localhost:8080/*', ['api://d16e1a06-3be2-4ae1-8bd4-718c19cecac3/.read']);`
Three
` protectedResourceMap.set('http://localhost:8080', ['api://d16e1a06-3be2-4ae1-8bd4-718c19cecac3.read']);`
Four
` protectedResourceMap.set('http://localhost:8080', ['api://d16e1a06-3be2-4ae1-8bd4-718c19cecac3/.read']);`
Five: all above are wrong, should be .....

**Comment by tnorling** [comment]
@zhshqzyc Regarding the resource if all your apis reside under `/api` you may need to try the following as it can depend on how your app is configured:

`http://localhost:8080/api/*` or `/api/*` or `api/*`

For more information please read [this doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/msal-interceptor.md)

Regarding the scope you will find the correct uri on your app registration when you click on it.

**Comment by zhshqzyc** [comment]
For the right side of protectedResourceMap.set.
`['api://d16e1a06-3be2-4ae1-8bd4-718c19cecac3/api']`
Is the `d16e1a06-3be2-4ae1-8bd4-718c19cecac3` clientId or application Id? I think clientId is different from applicationId.

**Comment by tnorling** [comment]
@zhshqzyc 
> Is the d16e1a06-3be2-4ae1-8bd4-718c19cecac3 clientId or application Id? I think clientId is different from applicationId.

ClientId and ApplicationId are the same thing.

> I forked the code from https://www.youtube.com/watch?v=xDkvoAV55F4. The author didn't setup scope in his application. Is that okay for still using protectedResource?

He did. See [here](https://github.com/tamani-coding/angular-msal-interceptor-example/blob/main/src/app/app.module.ts#L20). If you need an access token for an API you need to specify at least 1 scope in the `protectedResourceMap`. If the API does not require an access token (unprotected) then you do not need to specify a scope in the `protectedResourceMap` and can pass `null` instead.

**Comment by zhshqzyc** [comment]
That is my confusion. My thought is to add a scope is through portal setting something such as the 'read' in the image
![portal-02-expose-api](https://user-images.githubusercontent.com/7240266/130318495-22dbf2f3-f366-40bf-90ae-17c548ecd343.png).

Then adding the code in app.module.ts. But the author of the video didn't set it in portal. Do I miss something? Because I still can't get the token attached in the header. I worried that I maybe miss some setting in azure portal.

**Comment by tnorling** [comment]
@zhshqzyc 

> My thought is to add a scope is through portal setting something such as the 'read' in the image

Yes, you need to do this.

> Then adding the code in app.module.ts. But the author of the video didn't set it in portal. Do I miss something?

I've taken a quick look at the video. He actually does do this, starting at the 11:00 mark.

> It doesn't work well if I put them into protectedResourceMap together. Because I still can't get the token attached in the header. It popups more login windows then gone immediately.

This is likely because you haven't registered the scope in the portal. The access token will only be acquired if a scope is both registered **and** requested.

**Comment by zhshqzyc** [comment]
Yes, I think that I am close the final line. I can see the Bearer token in the header. One more question.
`loginPopup() {
    if (this.msalGuardConfig.authRequest){
      this.authService.loginPopup({...this.msalGuardConfig.authRequest} as PopupRequest)
        .subscribe((response: AuthenticationResult) => {
          console.log(response);
          this.authService.instance.setActiveAccount(response.account);
        });
      } else {
        this.authService.loginPopup()
          .subscribe((response: AuthenticationResult) => {
            this.authService.instance.setActiveAccount(response.account);
      });
    }
  }`
In the above code, I want to see what is response after I login. So I added console.log(response). I can't find the refresh token in the response. Why?

**Comment by tnorling** [comment]
@zhshqzyc The refresh token is not exposed by design, it is managed internally by MSAL. Can you please explain why you need it?

**Comment by zhshqzyc** [comment]
I don't know. Just the old applications used the fresh token. I am not sure how msal 2.0 works if the access token expired. Does a new window pops up if the token is expired?

**Comment by tnorling** [comment]
No. Msal.js will use the refresh token (which it manages internally) to acquire a new access token when the access token is expired. When the refresh token is expired, msal.js will attempt to silently acquire a new set of both access and refresh tokens and if that fails only then will you be prompted to sign in again. You can read more about how msal.js manages token expiration/renewal [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/token-lifetimes.md#token-renewal)
