### ISSUE TITLE
MSAL Angular shows blank page on IE11 with an error "Syntax Error"

### ISSUE THREAD

**Issue by r4hulp** [AzureAD/microsoft-authentication-library-for-js#3985]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.16.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.2

### Description

When I try to locally debug my Angular 9 project on IE11 (unfortunately, my client expects the app to work on IE11 too),

I get a blank app and this error in console - 

![image](https://user-images.githubusercontent.com/292704/130106540-26bd2fbc-7428-40e2-b8d8-18a33bb9b6a0.png)

Clicking on it redirects me to `MsalService` line in `vendor.js`
![image](https://user-images.githubusercontent.com/292704/130106639-019fe1a1-3f82-465e-a368-aa5b1da11358.png)

### Error Message

```
SCRIPT1002: Syntax error
vendor.js (64083,1)
```

### MSAL Configuration

```javascript
const ua = window.navigator.userAgent;
const msie = ua.indexOf('MSIE ');
const msie11 = ua.indexOf('Trident/');
const msedge = ua.indexOf('Edge/');
const isIE = msie > 0 || msie11 > 0;
const isEdge = msedge > 0;


export const MsalConfiguration: Configuration = {
  auth: {
    clientId: msalConfig.clientId,
    authority: msalConfig.authority,
    redirectUri: msalConfig.redirectUri,
    postLogoutRedirectUri: msalConfig.postLogoutRedirectUri,
  },
  cache: {
    cacheLocation: BrowserCacheLocation.LocalStorage,
    storeAuthStateInCookie: isIE || isEdge, 
  },
};
```

### Relevant Code Snippets

```javascript
n/a
```

### Reproduction Steps

1. `ng s` on local machine
2. open `http://localhost:4200` on IE11
3. it shows a blank page with the error message

### Expected Behavior

The app should load just fine

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Internet Explorer

### Source

External (Customer)

**Comment by tnorling** [comment]
@r4hulp You've selected `msal-browser` but specified version 1.4.12. Can you please confirm if you are using msal.js v1 or v2? 

Please review [this doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/ie-support.md) for instructions on supporting IE11 with msal-angular and let us know if you're still having issues.

**Comment by r4hulp** [comment]
> @r4hulp You've selected `msal-browser` but specified version 1.4.12. Can you please confirm if you are using msal.js v1 or v2?
> 
> Please review [this doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/ie-support.md) for instructions on supporting IE11 with msal-angular and let us know if you're still having issues.

Updated the issue.. I am using `2.16.1`. I made the required changes for IE11 but somehow I can not open `http://localhost:4200` on IE11..

**Comment by tnorling** [comment]
> somehow I can not open http://localhost:4200 on IE11..

@r4hulp Are you saying it is still giving you the syntax error?

**Comment by r4hulp** [comment]
> > somehow I can not open http://localhost:4200 on IE11..
> 
> @r4hulp Are you saying it is still giving you the syntax error?

That's correct. It gives me the Syntax Error as mentioned in the screenshot. I tried running the MSAL examples too, I get the same error.. Is MSAL compatible with IE11 anymore?

**Comment by jasonnutter** [comment]
@r4hulp Unfortunately, there is a known issue where Angular 9 applications using MSAL Angular do not work in IE11. See #3277.

Are you able to upgrade to newer version of Angular?
