### ISSUE TITLE
Dead Link on angular readme

### ISSUE THREAD

**Issue by StefanSchoof** [AzureAD/microsoft-authentication-library-for-js#3987]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/README.md

### Description

In Usage -> Advanced Topics -> CORS API is a link to https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-angular/docs/v2-docs/cors-api.md which results into a 404.

**Comment by tnorling** [comment]
@StefanSchoof Thanks, looks like this link wasn't removed when the doc was removed, will make sure this gets fixed. Was there something in particular you were looking for?

**Comment by StefanSchoof** [comment]
No, I am using CORS and was curious about this link. Ao I wanted to read if there was something good to know.

**Comment by tnorling** [comment]
@StefanSchoof All of the information that was in that doc is now in [this doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/msal-interceptor.md)

**Comment by StefanSchoof** [comment]
Thanks, @tnorling
