### ISSUE TITLE
Token timeout

### ISSUE THREAD

**Issue by yakimko** [AzureAD/microsoft-authentication-library-for-js#399]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 0.2.1
</code></pre>

How I can increase or decrease token's timeout? AFAIK it's 3600 seconds

**Comment by nehaagrawal** [comment]
@yakimko  You need to create a policy. Please check this document. https://docs.microsoft.com/en-us/azure/active-directory/active-directory-configurable-token-lifetimes

**Comment by yakimko** [comment]
@nehaagrawal thanks!
