### ISSUE TITLE
[adal-node -> msal-node] ADFS auth no longer working in CLI for Microsoft 365 after migration

### ISSUE THREAD

**Issue by garrytrinder** [AzureAD/microsoft-authentication-library-for-js#3991]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.2.0

### Wrapper Library

MSAL Node Extensions (@azure/msal-node-extensions)

### Wrapper Library Version

None

### Description

Related to https://github.com/pnp/cli-microsoft365/issues/2637

A user has reported an issue with authenticating to Microsoft 365 using ADFS authentication flow since we migrated from `adal-node` to `msal-node`. 

This has been confirmed by the user, as they have rolled back to a previous version (v3.8.0) that uses `adal-node` and they can log in successfully.

The user is using ADFS 3 in their environment and runs on Windows Server 2012.

### Error Message

```
(...)
Logging out from Microsoft 365...
Signing in to Microsoft 365...
No token found for resource https://graph.microsoft.com
[Tue, 10 Aug 2021 07:57:25 GMT] : @azure/msal-node@1.2.0 : Info - getTokenCache called
Retrieving new access token using credentials...
[Tue, 10 Aug 2021 07:57:25 GMT] : @azure/msal-node@1.2.0 : Info - acquireTokenByUsernamePassword called
[Tue, 10 Aug 2021 07:57:25 GMT] : @azure/msal-node@1.2.0 : Verbose - initializeRequestScopes called
[Tue, 10 Aug 2021 07:57:25 GMT] : [8f7c72a9-b1f6-458f-86fc-5deb09324a53] : @azure/msal-node@1.2.0 : Verbose - buildOauthClientConfigur
ation called
[Tue, 10 Aug 2021 07:57:25 GMT] : [8f7c72a9-b1f6-458f-86fc-5deb09324a53] : @azure/msal-node@1.2.0 : Verbose - building oauth client co
nfiguration with the authority: https://login.microsoftonline.com/{TenantID}
[Tue, 10 Aug 2021 07:57:25 GMT] : [8f7c72a9-b1f6-458f-86fc-5deb09324a53] : @azure/msal-node@1.2.0 : Verbose - createAuthority called
[Tue, 10 Aug 2021 07:57:25 GMT] : [8f7c72a9-b1f6-458f-86fc-5deb09324a53] : @azure/msal-node@1.2.0 : Verbose - Username password client
 created
[Tue, 10 Aug 2021 07:57:25 GMT] : [8f7c72a9-b1f6-458f-86fc-5deb09324a53] : @azure/msal-common@4.4.0 : Info - in acquireToken call
Error:
{ ServerError: invalid_grant: 50126 - [2021-08-10 07:57:27Z]: AADSTS50126: Error validating credentials due to invalid username or pas
sword.
(...)
```

### MSAL Configuration

```javascript
{
      auth: {
        clientId: this.service.appId,
        authority: `https://login.microsoftonline.com/${this.service.tenant}`,
        clientCertificate: cert
      },
      cache: {
        cachePlugin: msalCachePlugin
      },
      system: {
        loggerOptions: {
          // loggerCallback is called by MSAL which we're not testing
          /* c8 ignore next 4 */
          loggerCallback: (level: Msal.LogLevel, message: string) => {
            if (level === LogLevel.Error || debug) {
              logger.logToStderr(message);
            }
          },
          piiLoggingEnabled: false,
          logLevel: debug ? LogLevel.Verbose : LogLevel.Error
        }
      }
    };
```
```


### Relevant Code Snippets

```javascript
https://github.com/pnp/cli-microsoft365/blob/bad569e7e2d5f1d678e23b6f2b23ceb3923acc40/src/Auth.ts#L224
```

### Reproduction Steps

Related to https://github.com/pnp/cli-microsoft365/issues/2637

In the Azure release definition (agent vs2017-win2016) I set up the following tasks:

1. Node.js tool installer => version spec set to 14.x
2. npm => npm install -g @pnp/cli-microsoft365
3. Command line => m365 login -t password -u $(user) -p $(pass)
4. (...)

### Expected Behavior

User is logged in successfully

### Identity Provider

ADFS

### Browsers Affected (Select all that apply)

None (Server)

### Regression

adal-node@0.2.2

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
@garrytrinder Unfortunately ADFS 2012 is not supported in msal-node. If you would like to migrate from ADAL to MSAL you will need to also upgrade to ADFS 2019+

**Comment by garrytrinder** [comment]
Thank you for confirming @tnorling 👍🏻
