### ISSUE TITLE
Retrieve the ID token (not access token) from msal-react library?

### ISSUE THREAD

**Issue by jahed-uddin** [AzureAD/microsoft-authentication-library-for-js#3997]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

2.14.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.0.0

### Description

Using @azure/msal-react lib, I am able to retrieve the JWT Access token, but unsure on how to retrieve the JWT ID token from using the MSAL libray (although I can clearly see the claims as an object when I console log the `accounts[0].idTokenClaims`:

### Relevant Code Snippets

```javascript
const {accounts, instance} = useMsal();

console.log(accounts)

const request = {
    scopes: ["User.Read"],
    account: accounts[0]
};

// This gives me the raw JWT for the ACCESS token, HOWEVER, I want ID TOKEN JWT
instance.acquireTokenSilent(req).then((response) => { 
    console.log(response.accessToken)
})
```
```


### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@jahed-uddin Unfortunately, the raw id token is not available via acquireTokenSilent. You are not the first one to request this (e.g. for id_token_hint for logout), so I'll add to our backlog as an enhancement.

You can get the raw idToken as part of the AuthenticationResult returned from login calls (however this may not work for your needs).

**Comment by jahed-uddin** [comment]
@jasonnutter Many thanks for your response, can you please give a snippet how I can get the raw idToken using **AuthenticationResult** returned from login calls.

**Comment by tnorling** [comment]
Is this true? All APIs should return both idToken and accessToken, we don't discriminate in v2


Thomas Norling
Software Engineer II
Azure Identity - Auth Client (MSAL.js)
***@***.******@***.***>

[Microsoft Logo]

________________________________

**Comment by jahed-uddin** [comment]
@tnorling  Thanks for replying. Are you addressing me or @jasonnutter? I'm just asking the questions as I have zero experience with msal until like yest.

**Comment by jasonnutter** [comment]
@jahed-uddin Correction, the raw id token is available when you call `acquireTokenSilent` (response.idToken). It is not available on the `AccountInfo` objects returned from the account APIs. Will still keep in backlog, as others have asked for this.

Can you clarify why you want the id token? In most cases, registering a custom scope and getting an access token for that scope is the correct usage pattern for protecting web apis.

**Comment by jahed-uddin** [comment]
ok many thanks @jasonnutter. Basically, I want to use that JWT so I can send it to my backend Django REST API and use it for protecting my API endpoints. I.e. if a user has managed to sign in from the Front-End using msal-react lib, then  that token can be sent to the Backend REST API (who can verify the JWT) and subsequently return protected API data behind the Django API. It sounds like as if your suggesting I should use an **access** token instead of the **ID** token - is that correct?

**Comment by jahed-uddin** [comment]
@jasonnutter 

> Can you clarify why you want the id token? In most cases, registering a custom scope and getting an access token for that scope is the correct usage pattern for protecting web apis.

Please advise how I can register for a custom scope?

**Comment by jahed-uddin** [comment]
Why does the JWT **ACCESS TOKEN**  `acquireTokenSilent` (response.idToken) contain invalid signature (I have used the following code and also pasted the JWT in jwt.io and it says the signature is invalid):

```
def verify_token(token):

    jwks_uri = 'https://login.microsoftonline.com/common/discovery/v2.0/keys'
    jwkeys = requests.get(jwks_uri).json()['keys']

    token_key_id = jwt.get_unverified_header(token)['kid']
    jwk = [key for key in jwkeys if key['kid'] == token_key_id][0]

    der_cert = b64decode(jwk['x5c'][0])
    cert = x509.load_der_x509_certificate(der_cert, default_backend())
    public_key = cert.public_key()
    pem_key = public_key.public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo
    )
    token_claims = jwt.decode(token, pem_key, algorithms=['RS256'])
    return True
```

**Comment by jahed-uddin** [comment]
Hi @jasonnutter,

> In most cases, registering a custom scope and getting an access token for that scope is the correct usage pattern for protecting web apis.

I created a token using custom scopes and token validation works fine. However, if I want to call MS Graph now, that token is not valid - my question is can I get tokens that will have scope to both the custom APi and Graph, or will I have to create seperate msal instances in my react app (with the API specific scopes in those MSAL instances).

**Comment by EricEzaM** [comment]
I am looking for this as well. If I explain my use case could you let me know if it sounds like a reasonable way of doing things?

I would like my app (react SPA + .NET REST API) to allow login with Microsoft accounts (Azure AD), but don't need it to call downstream API's on the users behalf. I just want to use MS Accounts for authentication, not authorization (I will handle authz on my app side). In this case, I want to get the ID token, send it to my apps web API, validate the ID token and if it is valid, find the app user record with the corresponding `subject` (or create a new user), and then issue an auth cookie for my app to the browser, which is then used from then on for authentication and authorization.

**Comment by jasonnutter** [comment]
> Hi @jasonnutter,
> 
> > In most cases, registering a custom scope and getting an access token for that scope is the correct usage pattern for protecting web apis.
> 
> I created a token using custom scopes and token validation works fine. However, if I want to call MS Graph now, that token is not valid - my question is can I get tokens that will have scope to both the custom APi and Graph, or will I have to create seperate msal instances in my react app (with the API specific scopes in those MSAL instances).

Access tokens are scoped per resource, thus you cannot get an access token that will work for both your web api and ms graph. As a result, you will need to invoke acquireTokenSilent twice, once for each set of scopes for each resource, which will give you an access token you can use for that respective resource. You do not need to create a new instance of MSAL.

Read more here: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/resources-and-scopes.md

**Comment by EricEzaM** [comment]
@jasonnutter Sorry to tag you - any feedback on my comment above?

**Comment by jasonnutter** [comment]
@EricEzaM Can you please open a new issue?
