### ISSUE TITLE
Forgot password 

### ISSUE THREAD

**Issue by BogdanGeorge** [AzureAD/microsoft-authentication-library-for-js#4000]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.16.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.1

### Description

Our home page is redirecting to login page when the user is not authenticated using MsalAuthenticationTemplate. On the b2c login page when i click reset password it redirects back to our website with an error message containing AADB2C90118 code, the event callback is called and is trying to redirect but MsalAuthenticationTemplate is overriding everything and is redirecting back to login flow.

### MSAL Configuration

```javascript
{
	"auth": {
		"clientId": "clientId",
		"authority": "authority"
	},
	cache: {
		"cacheLocation": "localStorage",
		storeAuthStateInCookie: true
	}
}
```

### Relevant Code Snippets

```javascript
`
function AuthenticationProvider(props: AuthenticationProviderProps) {
   const [isReady, setReady] = useState<boolean>(false);

   useEffect(() => {
      initializeMsalInstance(props.authConfig);

      const callbackId = msalInstance.addEventCallback((event: EventMessage) => {
         if (event.eventType === EventType.LOGIN_FAILURE && event.error?.message.includes("AADB2C90118")) {
            console.log("redirecting to reset password");
            window.location.replace(Routes.ResetPassword);
         }
      });

      setReady(true);

      return () => {
         if (callbackId) {
            msalInstance?.removeEventCallback(callbackId);
         }
      };
   }, []);

   return (
      <>
         {isReady ? (
            <MsalProvider instance={msalInstance}>
               <AuthenticationContainer>{props.children}</AuthenticationContainer>
            </MsalProvider>
         ) : (
            <LoadingScreen />
         )}
      </>
   );
}



function AuthenticationContainer(props: AuthenticationContainerProps) {
   return (
      <>
         {console.log("msal auth template")}
         <MsalAuthenticationTemplate
            interactionType={InteractionType.Redirect}
            authenticationRequest={{
               scopes: props.scopes,
            }}
            errorComponent={AuthenticationErrorContainer}
            loadingComponent={AuthenticationLoadingContainer}
         >
            <AuthenticationSuccessContainer setUserIdentityContext={props.setUserIdentityContext} scopes={props.scopes}>
               {props.children}
            </AuthenticationSuccessContainer>
         </MsalAuthenticationTemplate>
      </>
   );
}
`
```

### Reproduction Steps

1. Go to the website as unauthenticated user
2. Website automatically redirects to b2c login page
3. Click on the reset password
4. B2C automatically redirect back to website with error code
5. Callback getting called and trying to set window.location.href = "/reset-password"
6. MsalAuthenticationTemplate gets rendered and automatically redirect to login page

### Expected Behavior

1. Go to the website as unauthenticated user
2. Website automatically redirects to b2c login page
3. Click on the reset password
4. B2C automatically redirect back to website with error code
5. Callback getting called and trying to set window.location.href = "/reset-password"
6. MsalAuthenticationTemplate not overring anything and location is redirected to /reset-password

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge

### Source

External (Customer)

**Comment by tnorling** [comment]
@BogdanGeorge What does `initializeMsalInstance` do? Does it just instantiate `PublicClientApplication` and return it or is it also calling `handleRedirectPromise` (if it is it should not be)? `MsalAuthenticationTemplate` should also be listening for the `LOGIN_FAILURE` event and rendering the error component. The fact that it's invoking the login tells me it may not have registered the event callback before `handleRedirectPromise` was called. Verbose level msal logs would be helpful in determining if that's getting fired or not. 

You may also be interested in the new self service password reset policy which integrates the password reset functionality into the login policy so you don't need to catch an error and redirect to a different policy. You can read more about that [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-password-reset-policy?pivots=b2c-user-flow#self-service-password-reset-recommended)

**Comment by tnorling** [comment]
@BogdanGeorge Thanks for providing a reproduction. I was able to determine root cause here and it is indeed a bug in the library. I will have a fix up shortly.
