### ISSUE TITLE
[Question] Get Authorization Code URL

### ISSUE THREAD

**Issue by JJHakiLe** [AzureAD/microsoft-authentication-library-for-js#4001]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.11.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

Hi All,

I was playing around with MSAL-Browser library and was wondering if there was a way for a developer to get the query string parameters of the authorization code URL when a user uses the loginRedirect() function (or any interactive function for acquiring tokens)?

### Source

External (Customer)

**Comment by jasonnutter** [comment]
Yes, the `onRedirectNavigate` callback will be invoked with the full url. Returning `false` in this callback will stop the pending navigation: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/6b257b717/lib/msal-browser/src/request/RedirectRequest.ts#L37

**Comment by JJHakiLe** [comment]
Thank you @jasonnutter for the swift response! So the redirectRequest property onRedirectNavigate can be provided so that the callback will return false to stop the pending navigation. During which, the full URL will be available to use within that a callback?

**Comment by jasonnutter** [comment]
> Thank you @jasonnutter for the swift response! So the redirectRequest property onRedirectNavigate can be provided so that the callback will return false to stop the pending navigation. During which, the full URL will be available to use within that a callback?

Yes. Example: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-browser-samples/ChromiumExtensionSample/auth.js#L83-L93

**Comment by JJHakiLe** [comment]
Great thank you for the example @jasonnutter . One last question I have is if a user invokes a `loginRedirect() `function with the `onRedirectNavigate `callback set to `false`, and then invokes another `loginRedirect `with a different `redirectRequest` where the  `onRedirectNavigate` callback is set to` true` or doesn't exist, will the user then be redirected or will the subsequent `loginRedirect()` function not redirect due to the msal items in the `browserStorage`?

**Comment by sameerag** [comment]
@JJHakiLe You will get an `InteractionInProgress` error in this case. Since we set the temporary cache variables when `loginRedirect` is invoked, until you resolve the call with a `handleRedirectPromise()` call, MSAL JS tracks this as a token request in progress.

**Comment by JJHakiLe** [comment]
@sameerag Great, that makes sense. Thank you very much @sameerag and @jasonnutter for your explanations. So `handleRedirectPromise()` needs to resolve those `InteractionInProgress` errors. I believe that should resolve any questions I have now. Thanks again!
