### ISSUE TITLE
AccountInfo -> TokenClaim missing custom claim

### ISSUE THREAD

**Issue by melloware** [AzureAD/microsoft-authentication-library-for-js#4004]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.16.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.1

### Description

We are migrating from the old https://github.com/syncweek-react-aad/react-aad MSAL 1.0 to 2.0 library to this library and we have most of our code working.  However one major difference in the old library and new library is with the old library allowed "custom" claims to come through.  For example,  we currently pass **immutable_id** through to get the users **onPremisesImmutableId** in our token claims.

The old library had idTokenClaims defined as a StringDict so custom claims like immutable_id came through:
```javascript
idTokenClaims: StringDict;
```
Payload:
![image](https://user-images.githubusercontent.com/4399574/131131226-3d11a8b8-b10b-4023-88db-a3b3b6db18a7.png)

The new library is bound to an object that does not seem to allow for any unbound custom claims properties to come through:
```javascript
 idTokenClaims?: object;
 ```

Object is of course missing the **immutable_id**:
![image](https://user-images.githubusercontent.com/4399574/131131333-a00a9665-8a01-4b3c-943e-10d5e0eb846e.png)

Defined as:
```javascript
/**
 * Type which describes Id Token claims known by MSAL.
 */
export type TokenClaims = {
    iss?: string,
    iat?: number,
    oid?: string,
    sub?: string,
    tid?: string,
    ver?: string,
    upn?: string,
    preferred_username?: string,
    emails?: string[],
    name?: string,
    nonce?: string,
    exp?: number,
    home_oid?: string,
    sid?: string,
    cloud_instance_host_name?: string,
    cnf?: {
        kid: string;
    };
    x5c_ca?: string
};
```

So the question is how to do we go about getting our custom claim such as "immutable_id" in the new MSAL 2.0 library?

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by sameerag** [comment]
@melloware Thanks for bringing this to our attention. We do strive to send all claims and the `idToken` type is mostly for internal reference. Let me try reproducing this and reach out.

**Comment by melloware** [comment]
OK thank you!

**Comment by melloware** [comment]
@sameerag I am closing this ticket.  The issue was on our end where the custom claim was not added to our account. Our admins adjusted our profile and now we get our immutable id.  I thought the above TS object was the issue but it was not!   Closing ticket.

**Comment by sameerag** [comment]
Thank you @melloware
