### ISSUE TITLE
CORS error in localhost but the Bearer Token does show in the request header

### ISSUE THREAD

**Issue by zhshqzyc** [AzureAD/microsoft-authentication-library-for-js#4005]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0

### Description

My uris like
```
http://localhost:8080/apis/a
http://localhost:8080/apis/b
http://localhost:8080/apis/c
http://localhost:8080/apis/d
http://localhost:8080/apis/e
http://localhost:8080/apis/x/abcd
...
// many many
```
So I set the protectedResourceMap by wildcard
`protectedResourceMap.set('/apis/*', ['api://d16e1a06-3be2-4ae1-8bd4-718c19cecac3/api']);`

By debugging, I print `console.log(requestClone) ` in `msalInterceptor`, it does apply the token in the header. Also in Network TAB in chrome devtools, I can see the token in the header. However it still shows errors in the console.

Th error message likes:
`Access to XMLHttpRequest at 'http://localhost:8080/apis/' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.`

My backend has cors enabled. Any setting in azure or something else?

### Relevant Code Snippets

```javascript
return this.authService.acquireTokenSilent({...authRequest, scopes, account })
            .pipe(
                catchError(() => {
                    this.authService.getLogger().error("Interceptor - acquireTokenSilent rejected with error. Invoking interaction to resolve.");
                    return this.acquireTokenInteractively(authRequest, scopes);
                }),
                switchMap((result: AuthenticationResult)  => {
                    if (!result.accessToken) {
                        this.authService.getLogger().error("Interceptor - acquireTokenSilent resolved with null access token. Known issue with B2C tenants, invoking interaction to resolve.");
                        return this.acquireTokenInteractively(authRequest, scopes);
                    }
                    return of(result);
                }),
                switchMap((result: AuthenticationResult) => {
                    this.authService.getLogger().verbose("Interceptor - setting authorization headers");
                    const headers = req.headers
                        .set("Authorization", `Bearer ${result.accessToken}`);

                    const requestClone = req.clone({headers});
                    console.log(requestClone); // I can see the token here.
                    return next.handle(requestClone);
                })
            );
```
**But it WORKS in our dev environment, just failed in localhost**

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by sameerag** [comment]
@zhshqzyc MSAL JS has a requirement that the registered `redirectUri` should be of the same domain as the origin request. In your case it looks like they are different, hence this error is expected.

**Comment by zhshqzyc** [comment]
In my app.module.ts, I set

`redirectUri: window.location.origin`

In azure, I have redirectUri as `http://localhost`. Anything wrong?
In my backend spring boot, I found the error `did not process request since did not find bearer token`.

But my code just works find in dev but in localhost.

**Comment by jasonnutter** [comment]
> Th error message likes:
> Access to XMLHttpRequest at 'http://localhost:8080/apis/' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

> My backend has cors enabled. Any setting in azure or something else?

CORS errors like this are outside the scope of MSAL, as your resource (localhost:8080) needs to be configured to allow cross-origins requests from `localhost:4200` for the API and http request method. 

This error message ("Redirect is not allowed for a preflight request.") indicates that your resource is responding to the [browser's preflight (`OPTIONS`) request](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS) with a redirect, instead of a response indicate which CORS options are allowed. Please make sure your resource is properly configured to return a valid response when an `OPTIONS` request is made to the API endpoint in question.

**Comment by zhshqzyc** [comment]
I will double check the backend code. But I have a question for redirectUri, this is an angular application. So I set 
`redirectUri` as `http://localhost` in SPA platform. Is it right?

Or I need to set it in Web platform or both places. Or it doesn't matter.

**Comment by jasonnutter** [comment]
> So I set redirectUri as http://localhost in SPA platform. Is it right?

Yes, this is right. Do not set it as a web redirect.

**Comment by zhshqzyc** [comment]
In another online board, I was told my setting is wrong. I am not sure. My backend is spring boot and front end is angular. So we registered the application as SPA rather than web. Is it right?
