### ISSUE TITLE
Password Reset issue

### ISSUE THREAD

**Issue by brriann** [AzureAD/microsoft-authentication-library-for-js#4006]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.1

### Description

I am seeing a possible issue with this implementation of Password Reset
https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-password-reset-policy?pivots=b2c-custom-policy

We are using Custom Policies, and our SignUpSignIn UserJourney/ all config came from the provided LocalAccounts starterpack.
https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack

We are using a React SPA as our client, with @azure/msal-browser v2.14.0 and @azure/msal-react v1.0.1
https://www.npmjs.com/package/@azure/msal-browser

The issue is:
- when a user follows the Password Reset ('forgot your password?') steps and lands in the React SPA
- and immediately tries to Edit Profile or Change Password
- they are confronted with a sign in screen before seeing the Edit Profile or Change Password self-asserted technical profile screen
- users who are logged in, in the React SPA, who have NOT just reset their password, do not see this additional sign in screen
- This suggests that a user who has just finished the Password Reset flow is not properly authenticated / logged in as a user

More info:
- We are using the starter pack ProfileEdit UserJourney and RelyingParty file, as seen below
https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-profile-editing-policy?pivots=b2c-custom-policy
- We are using a PasswordChange User Journey and RelyingParty file as seen below
https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-password-change-policy?pivots=b2c-custom-policy
- We provide the user with menu options to Edit Profile or Change Password within the React SPA
- The extra sign in screen seems to be coming from SelfAsserted-LocalAccountSignin-Email, the first TechnicalProfile in both our ProfileEdit and PasswordChange UserJourneys

Observed:
- Using AppInsights logging with AADB2C, we observed differences in both claims and tokens, during a SignUpSignIn with PasswordReset, vs a happy path SignUpSignIn
- PasswordReset: email claim exists, userPrincipalName claim exists, signInName claim is in GUID/UPN format 
- happy path: email claim does not exist, userPrincipalName claim does not exist, signInName claim is of form "email => GUID/UPN format"
- PasswordReset: no tokens captured
- happy path: tokens from login-NonInteractive are captured

Theories:
- The Password Reset tutorial (above) mentions enabling Implicit Grant Flow.  However, MSAL 2 is not compatible with Implicit Grant Flow.  Maybe this explains absence of tokens visible in AppInsights, or is causing some other issue with MSAL not being able to properly sign in a user using Implicit Grant Flow
- We are missing some sort of OutputClaim or PartnerClaimType mapping between email and signInName, in one of the starterpack technical profiles (AAD, or one of the self-asserted login related)

I'm wondering if anyone else has observed issues like this, using the MS provided Password Reset instructions.  Thank you!  And please let me know if I can provide any more information.

### MSAL Configuration

```javascript
const msalConfig: Configuration = {
    auth: {
      authority: getAuthorityUrl(azureSettings.AD_B2C_SignUpSignIn_Policy),
      clientId: azureSettings.AD_B2C_ClientId,
      knownAuthorities: [getAuthorityDomain()],
    },
  };
```

### Relevant Code Snippets

```javascript
Custom Policy config / SignUpSignIn UserJourney
https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack

PasswordReset ClaimsExchange/SubJourney implementation
https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-password-reset-policy?pivots=b2c-custom-policy

Client-side call to Edit Profile policy (using MS starterpack / Base ProfileEdit)

// config file
export const editProfileRequest: RedirectRequest = {
  authority: getAuthorityUrl(azureSettings.AD_B2C_ProfileEdit_Policy),
  redirectUri: azureSettings.SPA_Root_URL,
  scopes: [],
};

// runtime file
instance.loginRedirect(editProfileRequest);
```

### Reproduction Steps

1. Use the AD B2C LocalAccounts starter pack config for custom policy
2. Implement Password Reset using this tutorial https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-password-reset-policy?pivots=b2c-custom-policy
3. Configure a React SPA with MSAL 2, giving an authenticated user options to change password / edit profile
4. as a user, execute the Password Reset / 'forgot your password?' flow
5. Finishing the flow, be redirected to the React SPA, seemingly in an authenticated state
6. Interact with SPA to choose Change Password or Edit Profile (which loginRedirect to a certain RelyingParty/Policy)
7. EXPECTED: user immediately sees change password/ edit profile screen
8. BUG/ACTUAL: user is confronted with another sign in screen, before seeing change password/ edit profile screen

### Expected Behavior

7. EXPECTED: user immediately sees change password/ edit profile screen
8. BUG/ACTUAL: user is confronted with another sign in screen, before seeing change password/ edit profile screen

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@brriann Thanks for the detailed issue. This was identified as an issue with the B2C service. Please file a support ticket with the B2C team by following the instructions here: https://docs.microsoft.com/azure/active-directory-b2c/support-options

They can help you out further, they may ask for a public repro link or additional data. You can also link this Github issue in the support request.

**Comment by brriann** [comment]
Thank you @jasonnutter !
More info:
Fix is demonstrated here: https://github.com/brriann/b2c-msal-pwreset
Answer from responder here: https://github.com/azure-ad-b2c/samples/issues/274
