### ISSUE TITLE
[Safari] handleRedirectPromise not called if login request url is the same path as the reply url

### ISSUE THREAD

**Issue by thoo1** [AzureAD/microsoft-authentication-library-for-js#4008]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.13.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

This is only reproducible in Safari (I'm on Safari v14.0.3) and is more of a description of what I think is a Safari bug that impacts this library. We're noticing on our application that if the user goes to our page (eg someExamplePage.com) and the reply url is also set up to be someExamplePage.com the following happens.

user goes to someExamplePage.com -> our application calls `handleRedirectPromise`, sees that there is no account and calls `loginRedirect` -> user is redirect to AAD page and the response is 302 and the redirect url is someExamplePage.com/#code=....... -> user is redirected back to someExamplePage.com/#code=....... BUT in safari only, it appears that the document is not loaded again. 

This library says to call handleRedirectPromise in order to handle the code that is returned in the hash however handleRedirectPromise is not called again since the document is not loaded again in safari.

I was able to test this out by having the login request url be different than the reply url by adding a subpath. So for example if user initially comes to our site at someExamplePage.com/somePath, the redirection from AAD to someExamplePage.com/#code=..... does trigger the page to load again and our application will call handleRedirectPromise which successfully completes the login process

I want to file this bug to see if others are facing the same issue and are seeing the same behavior

### Error Message

No error message. The redirection from AAD page back to our application's reply url does not trigger a page load in Safari and because our application only calls handleRedirectPromise on page load, the returned authorization code is never handled and parsed.

### MSAL Configuration

```javascript
{
      auth: {
        clientId: this.clientId,
        authority: this.authority,
        redirectUri: this.loginRedirectUri,
        postLogoutRedirectUri: this.postLogoutRedirectUri
      },
      cache: {
        cacheLocation: "localStorage",
        storeAuthStateInCookie: isIEOrOldEdge // https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1188#issuecomment-634281307
      },
      system: {
        tokenRenewalOffsetSeconds: Constants.tokenRenewalOffsetSeconds,
        iframeHashTimeout: 30000, // iframe is used to refresh the refresh_token as it has a 24h lifetime
        loggerOptions: {
          loggerCallback: MsalAuthContext.msalLoggerCallback,
          piiLoggingEnabled: false,
          logLevel: LogLevel.Warning
        },
        navigationClient: this.navigationClient // this client only implements the `navigateInternal` function.
      }
    }
```

### Relevant Code Snippets

```javascript
const browser = Bowser.getParser(window.navigator.userAgent);
    const isIEOrOldEdge =
      browser.satisfies({ edge: "<79" }) || browser.getBrowserName().toLowerCase() === "internet explorer";
    const publicClientApp = new PublicClientApplication({
      auth: {
        clientId: this.clientId,
        authority: this.authority,
        redirectUri: this.loginRedirectUri,
        postLogoutRedirectUri: this.postLogoutRedirectUri
      },
      cache: {
        cacheLocation: "localStorage",
        storeAuthStateInCookie: isIEOrOldEdge // https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1188#issuecomment-634281307
      },
      system: {
        tokenRenewalOffsetSeconds: Constants.tokenRenewalOffsetSeconds,
        iframeHashTimeout: 30000, // iframe is used to refresh the refresh_token as it has a 24h lifetime
        loggerOptions: {
          loggerCallback: MsalAuthContext.msalLoggerCallback,
          piiLoggingEnabled: false,
          logLevel: LogLevel.Warning
        },
        navigationClient: this.navigationClient // this client only implements the `navigateInternal` function.
      }
    });
    const handleRedirectPromise = publicClientApp
      .handleRedirectPromise()
      .then(response => {
        if (response?.account) {
          CoreLogger.trackEvent(TelemetryEventName.Core_MSALAuthContext_NewUserLoggedIn);
        } else if (this.getAccount()) {
          CoreLogger.trackEvent(TelemetryEventName.Core_MSALAuthContext_ExistingUserLoggedIn);
        } else {
          CoreLogger.trackEvent(TelemetryEventName.Core_MSALAuthContext_NoUserLoggedIn);
        }
        this.account = (response ? response.account : this.getAccount()) || undefined;
        if (!this.account) {
          const correlationId = v4();
          CoreLogger.trackEvent(TelemetryEventName.Core_MSALAuthContext_login, undefined, { correlationId });
          return this.publicClientApp.loginRedirect({
            scopes: this.scopes,
            authority: this.authority,
            redirectStartPage: returnUrl,
            correlationId
          });
        } else {
          this.setTenantId(this.account.tenantId);
        }
        return undefined;
      })
      .catch(error => {
        if (error instanceof Error) {
          this.trackError(error);
        }
        this.loginToTenantRedirect(MsalAuthContext.defaultTenantId);
      });
    return { publicClientApp, handleRedirectPromise };
```

### Reproduction Steps

1. Have reply url be your application's base url.
2. Go to your application's base url in Safari
3. Notice that it redirects to AAD and comes back to your application's base url with a code in the url
4. Notice that the page does not load again which causes handleRedirectPromise not to be called

### Expected Behavior

Safari should load the page again once it redirects back regardless if the initial and final page urls are same or not

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Safari

### Source

Internal (Microsoft)

**Comment by thoo1** [comment]
I did however find that when the authorization code in the hash comes back from AAD's redirect, that the safari browser emits a "hashchange" event

So maybe that is the way forward, that we should also listen on "hashchange" to try to handle the authorization code. I can show a repro of this, just contact my alias on teams (I'm internal MSFT)

**Comment by jasonnutter** [comment]
@thoo1 Thanks for the descriptive bug report, I'll see if I can reproduce this and follow up with further questions.

**Comment by thoo1** [comment]
@jasonnutter were you able to reproduce the issue? I can repro on our site, we can hop on a call to discuss

**Comment by huberchrigu** [comment]
We have the same issue and it makes our app unusable for any customer using Safari. Any workaround is highly appreciated.

**Comment by jasonnutter** [comment]
@thoo1 

> Safari should load the page again once it redirects back regardless if the initial and final page urls are same or not

We intentionally do not do this. If the redirect uri is the same as the login request url, we just process and return the hash there: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/src/interaction_client/RedirectClient.ts#L99-L109

Furthermore, I'm not able to see any issues when loading the [default sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-browser-samples/VanillaJSTestApp2.0) in Safari.

Am I correctly understanding that in this scenario, the hash isn't being processed when `handleRedirectPromise` is called? It seems like that is the issue.

**Comment by jasonnutter** [comment]
Debugging `handleRedirectPromise` and/or sharing verbose logs will be helpful in understanding why the hash isn't being processed.

**Comment by thoo1** [comment]
>Safari should load the page again once it redirects back regardless if the initial and final page urls are same or not

This is more a point about the difference between Safari and Chrome's handling of redirecting, it appears that Safari will not load the page but Chrome will which makes a difference because that means in Safari, it will not execute the initial scripts again when the page loads (which includes the script to even call `handleRedirectPromise`)

I'll try to repro this again on Safari and attach a gif shortly

**Comment by jasonnutter** [comment]
@thoo1 Any update on a reproduction? And if possible, a reproduction using one of our samples would be best. Thanks!

**Comment by thoo1** [comment]
I'm able to consistently repro on our site but not using one of the samples. In the samples, when it does loginRedirect, the address bar changes to AAD and then AAD redirects back to the original site. However in our site, when we do loginRedirect it does not change address bar to AAD site but after a small delay, it changes the address bar to our site but with an additional #code hash. I'm not sure how that is possible as I believe the authorization code is from server side so it has to have redirected to AAD for a brief moment.. Here is a gif where I was able to reproduce the issue
![ezgif com-gif-maker](https://user-images.githubusercontent.com/55852795/134234801-61469b59-8486-487d-9a29-07a0a8dc19f8.gif)

**Comment by thoo1** [comment]
Perhaps it'll be simpler to ask the question, is the #code hash only from server side - if so, how is our application getting this #code hash added without a (visible) redirect to AAD

**Comment by jasonnutter** [comment]
> Perhaps it'll be simpler to ask the question, is the #code hash only from server side - if so, how is our application getting this #code hash added without a (visible) redirect to AAD

Yes, it is. Do you see an outgoing request to AAD in the network tab?

**Comment by jasonnutter** [comment]
Can you share a network trace (fiddler or har)? Thanks!

**Comment by jasonnutter** [comment]
Also, I'll note that `handleRedirectPromise` will take a response hash as a parameter, so as a workaround, you could write logic to detect this scenario, and then parse the hash and pass it to MSAL explicitly.
