### ISSUE TITLE
Best way to determine if user is still logged in? 

### ISSUE THREAD

**Issue by ktikku** [AzureAD/microsoft-authentication-library-for-js#4010]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.16.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

Hi Team,

What is the best way to determine if the user has a valid session?
I read on a few stackoverflow threads that we can use `getAllAccounts` nut that returns cached accounts as per my knowledge.
Is there a better way?
Thanks!

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@ktikku Correct, the MSAL account APIs will read cached accounts, which may be out of sync with the server. To check if the user still has an active session, you will need to invoke a network request to the server, either via `loginPopup`, `loginRedirect`, `ssoSilent`, or `acquireTokenSilent` (with `forceRefresh` set to `true`). Which one you use depends on your scenario and your desired user experience. Can you provide more details on your desired outcome in this context?

**Comment by jasonnutter** [comment]
And generally speaking, we tend to recommend that applications invoke network requests _reactively_ (as a result of an error, e.g. `acquireTokenSilent` returning an interaction required error), as opposed to _proactively_.

**Comment by ktikku** [comment]
@jasonnutter 
We wanted to have a method which checks for the active session and returns false if the user's session has expired.
Currently we're invoking `acquireTokenSilent` to check if we're able to renew the token, and if not we're catching the error and returning false.
But this method renews the token, and is just promoting keeping tokens alive forever without the user’s knowledge :/
Thoughts? 😄

**Comment by jasonnutter** [comment]
> We wanted to have a method which checks for the active session and returns false if the user's session has expired.

@ktikku Out of curiosity, why do you want to do this? What are doing based on the result of this operation?

**Comment by ktikku** [comment]
@jasonnutter we have a middleware which is invoked on client side routing, we want to logout the user of SPA if they don't have a valid token.

**Comment by jasonnutter** [comment]
> @jasonnutter we have a middleware which is invoked on client side routing, we want to logout the user of SPA if they don't have a valid token.

If they don't have a valid access (or id) token, or their AAD session has ended? Those are not necessarily the same. 

We usually recommend applications leveraged cached tokens for as long as they are valid, and they perform actions such as automatically logging out if you receive an error using or renewing the token. Going to the network routinely to check if the user still has an active sessions adds complexity and is an expensive operation which can impact perf and UX.
