### ISSUE TITLE
adal-node depends on xmldom that has a security vulnerability

### ISSUE THREAD

**Issue by ramya-rao-a** [AzureAD/microsoft-authentication-library-for-js#4011]
### Core Library

ADAL Node (adal-node)

### Core Library Version

0.2.2

### Wrapper Library

Not Applicable

### Wrapper Library Version

N/A

### Description

The `adal-node` package has a dependency on `xmldom` which in turn has a security vulnerability. Please see https://www.npmjs.com/advisories/1769

As per the discussion in https://github.com/Azure/ms-rest-nodeauth/issues/134#issuecomment-905810709, looks like xmldom might not be releasing an update. This dependency may need to be replaced with `@xmldom/xmldom`

### MSAL Configuration

```javascript
N/A
```

### Relevant Code Snippets

```javascript
https://www.npmjs.com/advisories/1769
```

### Reproduction Steps

https://www.npmjs.com/advisories/1769

### Expected Behavior

Package should be installable without any npm audit errors

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Source

Internal (Microsoft)

**Comment by sameerag** [comment]
Thanks @ramya-rao-a. Will be tracking this.

**Comment by sameerag** [comment]
#3988 merged a fix for this. This will be a part of the next release we make on adal-node.

**Comment by fennibay** [comment]
When is the next release planned?

**Comment by jasonnutter** [comment]
`adal-node@0.2.3` has been released with `@xmldom/xmldom`. Closing.
