### ISSUE TITLE
acquireTokenSilent function failed with error 'ServerError: temporarily_unavailable: 50033 - [2021-08-02 15:36:10Z]: CCS could not serve the request that had failed at ESTS due to server error and got auto failed over to CCS. '

### ISSUE THREAD

**Issue by SummerCat200** [AzureAD/microsoft-authentication-library-for-js#4019]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.16.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

none

### Description

On 08/02 and 08/03, 4 of our acquireTokenSilent requests failed with error 'ServerError: temporarily_unavailable: 50033 - [2021-08-02 15:36:10Z]: CCS could not serve the request that had failed at ESTS due to server error and got auto failed over to CCS. - Correlation ID: 672dcda1-8537-45a8-b53a-69f423ef2033 - Trace ID: 13e2fdb7-b1fe-4f45-a98d-1d1679d40300', and we don't receive these errors any more, but we still want to understand the root cause for these errors and whether we should exclude these errors from our metrics in the future.

Correlation ID: 672dcda1-8537-45a8-b53a-69f423ef2033 - Trace ID: 13e2fdb7-b1fe-4f45-a98d-1d1679d40300
Correlation ID: fe970be4-a9bb-4407-a534-08fc28b278f5 - Trace ID: e3ae67c0-b0e9-4b26-a01e-7d5568110500
Correlation ID: 2b03c987-d258-4fe6-aaf0-b423b4197e7e - Trace ID: 2aa97141-df72-4077-96f6-dec9d77d0000
Correlation ID: a7226f3b-2126-4045-8bc2-f220e3bc8bdc - Trace ID: d6b84ae8-0b9a-40f8-8faa-d0118a820000

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by peterzenz** [comment]
These represent an authentication failure at the server where an attempt was made to process the request on our backup authentication service and failed as well.  You should include these in your metrics as failures and they should be extremely rare.   You can read more about out [Backup authentication service](https://techcommunity.microsoft.com/t5/azure-active-directory-identity/99-99-uptime-for-azure-active-directory/ba-p/1999628) if you are interested.
