### ISSUE TITLE
CORS issue for trying to fetch an access token for Confidential Client App

### ISSUE THREAD

**Issue by anshammer** [AzureAD/microsoft-authentication-library-for-js#4023]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.3.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

I am trying to fetch an access token for a confidential client application but it fails to fetch the token with a CORS error - I am making the call to fetch access token by client credentials - **acquireTokenByClientCredential**

"_Access to XMLHttpRequest at 'https://login.microsoftonline.com/tenantid.../oauth2/v2.0/token' from origin 'https://localhost:44355' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource._"

_ClientAuthError: network_error: Network request failed. Please check network trace to determine root cause. | Fetch client threw: Error: Network Error | Attempted to reach: https://login.microsoftonline.com/tenantid.../oauth2/v2.0/token_

The SPA is wrapped in a .Net backend server.

Version 1 of the application was first created to build a public client application with MSAL and it successfully handles the user interactions, fetching access token and interacting with the APIs. - Package : MSAL BROWSER

`_this.authContext = new PublicClientApplication(this.authConfig);_
`
With version 2, I am adding another layer (for an automation test client) to build a confidential client app to fetch access token non-interactively using client secret. (Package : MSAL NODE).

		_this.authContext = new ConfidentialClientApplication(this.authConfig);_

The permission has been granted and I created a local node application to test it and it works there. I am able to generate the access token with the same setup on the node js app but not on my React app.

### MSAL Configuration

```javascript
auth: {
				clientId: `xxx`,
				authority: `https://login.microsoftonline.com/xxx`,
				clientSecret: `xxx`,
			}
	
		this.authContext = new ConfidentialClientApplication(this.authConfig);
```

### Relevant Code Snippets

```javascript
tokenRequest = {
			scopes: [`appregxx/` + '.default'],
		};

const response = await this.authContext.acquireTokenByClientCredential(this.tokenRequest);

This call fails and throws the CORS exception.
```

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by jasonnutter** [comment]
@anshammer Confidential clients cannot obtain tokens client side in the browsers, as requests to token endpoint must be made server-side. Can you clarify if you are just using the confidential client for test automation?

If so, we recommend the approach used in this sample, which uses ROPC to authenticate teh user, and the sideload the tokens in the MSAL browser cache: https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-browser-samples/TestingSample

**Comment by jasonnutter** [comment]
> I assume we would need to create an AD account for the cypress test client?

Yes, you will need to create a test user. This can be done in your own test tenant, or you can onboard to MSID Labs, which offers test accounts for first-party applications.

> Would there be an interaction needed for the credentials and multifactor authentication?

No. If your test user is setup to not require MFA, you can complete login using ROPC without interaction.

**Comment by jasonnutter** [comment]
And we have a new API to make sideloading tokens easier, however, our testing sample is not updated to use that. I'll make sure we do that: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/testing.md

**Comment by anshammer** [comment]
> > Currently, the app has MSAL built in for authentication, which kicks-off a redirection for the user to sign in and handle redirects, would you think, having a ROPC flow (having the account added in the storage) would bypass that redirection flow?
> 
> Yes. The point is that you use ROPC for authenticating (to by pass interaction), and the sideload the tokens into the MSAL Browser cache.

Ok, that sounds re-assuring.

Here's the MSAL flow in my app: 
When the UI loads, it does the handleredirects and checks for the response :
`			const response = await this.authContext.handleRedirectPromise(); 
`to check if this request was an auth redirect. 

If a response was present, it looks for the active accounts 
```
if (response) {
	this.activeAccount = response.account;
```
if it was not a redirect, it checks if there are any active accounts otherwise, it will redirect the user for a login.

`			const currentAccounts = this.authContext.getAllAccounts();
`

So with the ROPC flow, should it go through these logic to check for redirects/active accounts for authentication or should it be a complete separate login flow by itself?

**Comment by jasonnutter** [comment]
> So with the ROPC flow, should it go through these logic to check for redirects/active accounts for authentication or should it be a complete separate login flow by itself?

ROPC is done completely separately from your app logic. The testing sample shows that is done.

One change you may make is if you detect that it was not a redirect, and there is not active account, check for any cached accounts via `getAllAccounts`, and if you have sideloaded your tokens properly, it should be populated with the account from the ROPC flow. You can then set that account as the active account.

**Comment by anshammer** [comment]
> > So with the ROPC flow, should it go through these logic to check for redirects/active accounts for authentication or should it be a complete separate login flow by itself?
> 
> ROPC is done completely separately from your app logic. The testing sample shows how that is done.
> 
> One change you may make is if you detect that it was not a redirect, and there is not active account, check for any cached accounts via `getAllAccounts`, and if you have sideloaded your tokens properly, it should be populated with the account from the ROPC flow. You can then set that account as the active account.

Alright, thanks. I will try it out. 

I will close this issue for now and will reach out if I need any help.
