### ISSUE TITLE
msal-angular : How to Fetch latest payload after edit profile.

### ISSUE THREAD

**Issue by vinod01** [AzureAD/microsoft-authentication-library-for-js#4028]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.0.2

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.2

### Description

I am facing issue with how to fetch updated user profile information. Right now in chrome Inspect : Application Session storage is showing both information, old first name, last name and after edit profile updated first name, last name. My below script is fetching old info - first name and last name.

Which event i have to use to get latest payload.

I have try below event but not able to fetch.

    // SSO_SILENT_SUCCESS
    // ACQUIRE_TOKEN_SUCCESS
    //HANDLE_REDIRECT_START
    // SSO_SILENT_START
    //ACQUIRE_TOKEN_START
    // ACQUIRE_TOKEN_NETWORK_START

Please help.

### Relevant Code Snippets

```javascript
this.msalBroadcastService.msalSubject$
      .pipe(
        filter((msg: EventMessage) => msg.eventType === EventType.LOGIN_SUCCESS),
        takeUntil(this._destroying$)
      )
      .subscribe((result: EventMessage) => {
        console.log(result);
        const payload = result.payload as AuthenticationResult;

        localStorage.setItem('IdToken', payload.idToken);
        this.authService.instance.setActiveAccount(payload.account);
      });
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by hectormmg** [comment]
Hi @vinod01 . I see that you are caching the ID token in the response yourself, which is why you may be seeing both the old and new ID Token claims in the cache. Since MSAL handles caching, you don't need to cache the tokens yourself.

After the profile information is updated, you will find the updated ID Token in the result of the next acquire token request, so the `ACQUIRE_TOKEN_SUCCESS` event is most likely the one you are looking for.

**Comment by vinod01** [comment]
After login we are able to see payload.idToken but after edit profile when page redirecting to home application. payload.idToken is not showing under ACQUIRE_TOKEN_SUCCESS event. I am also trying with sessionStorage.clear(); when application redirect from Home application to edit profile page.  

Below is my script.

App Component
-------------------
ngOnInit(): void {
    //console.log("App component");
    this.isIframe = window !== window.parent && !window.opener;

    this.msalBroadcastService.msalSubject$.pipe(
      filter((msg: EventMessage) => msg.eventType === EventType.ACQUIRE_TOKEN_SUCCESS)
    )
      .subscribe((result: EventMessage) => {
        const payload = result.payload as AuthenticationResult;
        console.log("ACQUIRE_TOKEN_SUCCESS APP = " + payload.idToken);
        //localStorage.setItem('mEncKey', payload.idToken);
        this.idToken = payload.idToken;
        this.authService.instance.setActiveAccount(payload.account);
      });
      
    this.msalBroadcastService.inProgress$
      .pipe(
        filter((status: InteractionStatus) => status === InteractionStatus.None),
        takeUntil(this._destroying$)
      )
      .subscribe(() => {
        console.log("iN progress App Component");
        console.log("InteractionStatus APP = " + this.idToken);
        this.setLoginDisplay();
      });

    this.router.events.subscribe((evt) => {
      if (!(evt instanceof NavigationEnd)) {
        return;
      }
      window.scrollTo(0, 0);
    });
  }

  setLoginDisplay() {
    this.loginDisplay = this.authService.instance.getAllAccounts().length > 0;

    if (!this.loginDisplay) {
      this.loginRedirect();
    } else {
      this.router.navigate(['/home']);
    }
  }

  loginRedirect(userFlowRequest?: RedirectRequest | PopupRequest) {
    if (this.msalGuardConfig.authRequest) {
      this.authService.loginRedirect({
        ...this.msalGuardConfig.authRequest,
        ...userFlowRequest,
      } as RedirectRequest);
    } else {
      this.authService.loginRedirect(userFlowRequest);
    }
  }

  ngOnDestroy(): void {
    this._destroying$.next(null);
    this._destroying$.complete();
  }

Home Component
---------------------

ngOnInit(): void {
    this.msalBroadcastService.msalSubject$.pipe(
        filter((msg: EventMessage) => msg.eventType === EventType.LOGIN_SUCCESS),
        takeUntil(this._destroying$)
    )
        .subscribe((result: EventMessage) => {
            const payload = result.payload as AuthenticationResult;
            console.log("payload.idToken Home = " + payload.idToken);
            localStorage.setItem('mEncKey', payload.idToken);
            this.idToken = payload.idToken;
            this.authService.instance.setActiveAccount(payload.account);
        });

    this.msalBroadcastService.msalSubject$.pipe(
        filter((msg: EventMessage) => msg.eventType === EventType.ACQUIRE_TOKEN_SUCCESS)
    )
        .subscribe((result: EventMessage) => {
            const payload = result.payload as AuthenticationResult;
            console.log("ACQUIRE_TOKEN_SUCCESS Home = " + payload.idToken);
            //localStorage.setItem('mEncKey', payload.idToken);
            this.idToken = payload.idToken;
            this.authService.instance.setActiveAccount(payload.account);
        });

    this.msalBroadcastService.inProgress$.pipe(
        filter((status: InteractionStatus) => status === InteractionStatus.None)
    )
        .subscribe(() => {
            console.log("InteractionStatus Home = " + this.idToken);
            this.setLoginDisplay();
            this.checkAndSetActiveAccount();
            this.getClaims(this.authService.instance.getActiveAccount()?.idTokenClaims);
        });
}

checkAndSetActiveAccount() {
    let activeAccount = this.authService.instance.getActiveAccount();

    if (!activeAccount && this.authService.instance.getAllAccounts().length > 0) {
        let accounts = this.authService.instance.getAllAccounts();
        this.authService.instance.setActiveAccount(accounts[0]);
    }
}

setLoginDisplay() {
    this.loginDisplay = this.authService.instance.getAllAccounts().length > 0;
}

getClaims(claims: any) {
   console.log(claims);
   console.log(this.idToken); 
}

ngOnDestroy(): void {
    this._destroying$.next(undefined);
    this._destroying$.complete();
}

Please help.

**Comment by vinod01** [comment]
how can we handle Cancel event, when coming from third party to Home App in Angular? How to check form which policy it is coming back. Policy like edit profile, Reset-Password, Change Phone?

**Comment by hectormmg** [comment]
@vinod01 I wouldn't recommend clearing the cache yourself, even between network calls. MSAL should update the cache correctly for you.

We haven't been able to reproduce the issue, the cached ID token should contain the correct/updated information in the claims after editing the profile info.

Have you tried calling acquireToken after you've already come back from the profile edit? Not based on the result of the profile edit, but a separate acquireToken call?
