### ISSUE TITLE
[MSAL with REACT] loading configuration from json

### ISSUE THREAD

**Issue by Shyam268** [AzureAD/microsoft-authentication-library-for-js#4029]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

    "@types/react": "^17.0.16",

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

 "@azure/msal-browser": "^2.16.1",

### Description

Configuration:
    "@azure/msal-browser": "^2.16.1",
    "@azure/msal-react": "^1.0.1",
    "@types/node": "^12.20.19",
    "@types/react": "^17.0.16",
    "@types/react-dom": "^17.0.9",

I have added config.json file in public folder. in App.tsx file   we have to use  <MsalProvider instance={pca}> . here the pcs should be initialized with config.json values . any example reading values from json and initialize authentication 

### MSAL Configuration

```javascript
auth: {
        clientId: "clientid",
        authority: "https://login.microsoftonline.com/b2c_tententid",
        redirectUri: "http://localhost:3001/",
        navigateToLoginRequestUrl: true,
      
    },
```

### Identity Provider

Azure B2C Custom Policy

### Source

Internal (Microsoft)

**Comment by derisen** [comment]
hey @Shyam268 sorry for late response. We recommend initializing msal instance outside of your React component tree, for example in your `index.js` file:

```javascript
import React from "react";
import ReactDOM from "react-dom";

import { MsalProvider } from "@azure/msal-react";
import { Configuration,  PublicClientApplication } from "@azure/msal-browser";

import App from "./app.jsx";

// MSAL configuration
const configuration: Configuration = {
    auth: {
        clientId: "client-id"
    }
};

const pca = new PublicClientApplication(configuration);

// Component
const AppProvider = () => (
    <MsalProvider instance={pca}>
        <App />
    </MsalProvider>
);

ReactDOM.render(<AppProvider />, document.getElementById("root"));
```

As such, you can simply delay rendering your app until the `json` file is fetched. For example:

```javascript
import React from "react";
import ReactDOM from "react-dom";

import { MsalProvider } from "@azure/msal-react";
import { Configuration,  PublicClientApplication } from "@azure/msal-browser";

import App from "./app.jsx";

fetch(window.location.origin + '/config.json') // from your "public" folder
  .then((response) => response.json())
  .then((config) => {
      const pca = new PublicClientApplication(config);
      
      // Component
      const AppProvider = () => (
          <MsalProvider instance={pca}>
              <App />
          </MsalProvider>
      );
      
      ReactDOM.render(<AppProvider />, document.getElementById("root"));
  });
```

Let me know if that's not what you had in mind.
