### ISSUE TITLE
Specify Authorization header for /token request

### ISSUE THREAD

**Issue by ViieeS** [AzureAD/microsoft-authentication-library-for-js#4032]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.0

### Description

I want `/token` request includes the `client_id` as username and the `client_secret` as password in the `Authorization` header using the `Basic` schema. Is it possible and how?

### Identity Provider

Other

### Source

External (Customer)

**Comment by ViieeS** [comment]
Found a solution:

```ts
import {NetworkRequestOptions, NetworkResponse} from "@azure/msal-common";
import {msalConfig} from "../authConfig";
import {FetchClient} from "@azure/msal-browser/dist/network/FetchClient";

/**
 * Overriding the default  MSAL post request adding Authorization header
 */
export class CustomFetchClient extends FetchClient {
    sendPostRequestAsync<T>(url: string, options: NetworkRequestOptions = {}): Promise<NetworkResponse<T>> {
        const username = "<username>";
        const password = "<password>";

        if (url === `${msalConfig.auth.authority}/token`) {
            options = {
                ...options,
                headers: {
                    ...options?.headers,
                    "Authorization": `Basic ${btoa(`${username}:${password}`)}`
                }
            }
        }
        return super.sendPostRequestAsync(url, options);
    }
}

/*****/

export const msalConfig: Configuration = {
    /****/
    system: {
        networkClient: new CustomFetchClient(),
    }
};
```

Is there other way?

**Comment by jasonnutter** [comment]
@ViieeS MSAL.js only supports public clients, which do not use client secrets, as they run in an environment (e.g. a web browser) which is not capable of securely storing secrets (e.g. client secrets). Can you detail why you want to authenticate this way? We have no plans to formally support the functionality you demonstrate here.

Generally speaking, yes, providing your own network client is how you can override the built it in behavior.
