### ISSUE TITLE
Support longer refresh tokens for b2c msal-browser

### ISSUE THREAD

**Issue by frikkf** [AzureAD/microsoft-authentication-library-for-js#4037]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL React (@azure/msal-react)

### Description

Due to security constraints azure ad b2c refresh tokens for the browser-library only issues refresh tokens valid for 24 hours.

It would be great to be able to provide a real consumer level experience to login with longer refresh tokens that can be defined in the custom policies.

I understand the security measures, but still I would like my end users be able to stay logged in for longer times even though they are not using the native app.

Would it be possible to support issuing longer refresh tokens also for the browser libraries using azure ad b2c?

### Source

External (Customer)

**Comment by hectormmg** [comment]
@hpsin @nickgmicrosoft I believe this is a question for the service side. Thanks.

**Comment by tnorling** [comment]
@frikkf Token lifetime is not something the library controls. Please [open a ticket](https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options) with B2C support.

It's worth noting that even though the refresh token lifetime is 24 hours, that does not necessarily mean the user needs to enter their credentials again every 24 hours. If the session is still active on the server the user should be able to silently re-authenticate and obtain a new RT as long as their browser does not block 3P cookies. If that is not happening, B2C support should be able to help you with that as well.
