### ISSUE TITLE
Handling `logoutRedirect` in a window opened with `Office.Dialog` API

### ISSUE THREAD

**Issue by kdmadej** [AzureAD/microsoft-authentication-library-for-js#4038]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.16.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

none

### Description

I have an auth flow implemented with the help of `Office.Dialog` API (this is a bit of a followup on a [different issue](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/3962) I used to have). Everything works fine but I'm having trouble getting the logout flow to work as expected.

I'll start by describing what I expect the process to look like:
1. the user clicks on the "logout" button in the add-in
2. a separate window is opened using the `Office.Dialog` API (which I assume is required in order for this to work with the desktop Excel)
3. some back-and-forth messaging happens between the add-in (host) and the dialog in order to ensure proper communication channels have been established (and the dialog initialization did not fail)
4. when the add-in receives info the dialog is ready to proceed, it sends a message to the dialog indicating the logout flow should begin
5. the dialog, in response to that message, begins the logout flow using the `logoutRedirect()` method
6. the user is taken through the steps on `login.microsoftonline.com`
7. afterwards, the user is redirected back to the initial logout page in the dialog, which sends a message back to the host add-in that the flow finished successfully

However this does not happen as the flow triggered with `logoutRedirect()` stops at the following screen:
<img src="https://user-images.githubusercontent.com/2098250/132506042-e8e2e199-f8ba-4f60-b540-020675d1ed3f.png" width="459" />

I see that the `postLogoutRedirectUri` is loaded in an iframe on that page, which would be enough to complete the flow but it seems not to have access to the `Office` APIs (`Office.initialize` method is not called). Even if it did, I'm not entirely sure it would recognize the host add-in as the recipient of the `Office.context.ui.messageParent()`. Without that I'm not entirely sure how to communicate back to the add-in that the logout succeeded 🤔

Since the success message is never triggered the add-in is unaware that the flow is finished. Moreover, if the user decides to close the dialog manually the add-in is informed that the window closed prematurely (thanks to the magic of `Office.Dialog` API – gotta love the error codes ❤️ ) and shows a notification to the user asking them to retry the process.

I tried working around this issue using [event API](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md#events) but to no avail – the add-in does not receive any events so I assume this doesn't work across windows? 🤔

Any suggestions on how to proceed would be most welcome 😅

### MSAL Configuration

```javascript
{
  "auth": {
    "authority": "https://login.microsoftonline.com/e4...",
    "clientId": "77...",
    "redirectUri": "https://localhost:3000/login.html",
    "postLogoutRedirectUri": "https://localhost:3000/login.html?logout"
  },
  "cache": {
    "cacheLocation": "localStorage"
  }
}
```

### Relevant Code Snippets

```javascript
const response = await msalInstance.handleRedirectPromise();

if (response) {
  // dispatchToHost – that wraps `Office.context.ui.messageParent()`
  // authLogoutSuccess – prepares the proper message to indicate a successfull logout
  dispatchToHost(authLogoutSuccess());
} else {
  await msalInstance.logoutRedirect({
    account: accountInfo,
  });
}
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by hectormmg** [comment]
Hi @kdmadej , could you please confirm that the `postLogoutUri ("https://localhost:3000/login.html?logout")` is registered as a replyUrl in your app registration? Thanks.

Here's our documentation on logout, please ensure that your configuration is correct and see if anything there can help fix your issue.
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md

**Comment by kdmadej** [comment]
Yup, it is:
![image](https://user-images.githubusercontent.com/2098250/132584248-e66ea603-5c5b-4c4c-9574-4bba0f2c5596.png)

I even set it as a front-channel logout URL although I think that's redundant as I don't want to [sign the user out across all apps](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md#front-channel-logout).

I tried providing the `postLogoutUri` both on the config as well as the logout request just to be sure but both yield the same result. The final step is not redirecting back to it but instead it is loaded as an iframe in the dialog window.

**Comment by hectormmg** [comment]
@kdmadej can you try changing the URL to `http://` instead of `https://` and seeing if that changes anything. Usually redirect URIs have to use `https://`, but localhost is an exception to this rule.

**Comment by kdmadej** [comment]
The same result – stays on the "close all browser windows" screen and loads the redirect url in an iframe.

**Comment by hectormmg** [comment]
@kdmadej could you send me a Fiddler or network trace of this flow so I can see what's going on between the app and server? You can find my work e-mail on my GitHub profile so you can send it privately.
