### ISSUE TITLE
React Javascript Sample Code - Not Logging In / Can't Find Email

### ISSUE THREAD

**Issue by rdick** [AzureAD/microsoft-authentication-library-for-js#4039]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

Code Sample React Version

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

None

### Description

**React Sample Code Problem**

When I download the sample MSAL code from the github repo I get the following error.

"We couldn't find an account with that username. Try another, or get a new Microsoft account." 

I have tried multiple accounts that are registered with Microsoft and have not found a solution to this problem. Additionally I have updated my Client ID and registered an application on the Microsoft Under the following name "Graph Quick Start 2"

### Error Message

"We couldn't find an account with that username. Try another, or get a new Microsoft account." 

### Msal Logs

"We couldn't find an account with that username. Try another, or get a new Microsoft account." 

### MSAL Configuration

```javascript
auth: {
        clientId: "c272606f-1c2d-462a-9b3e-a778cc1be633",
        authority: "https://login.windows-ppe.net/common",
        redirectUri: "/",
        postLogoutRedirectUri: "/"
    },
    cache: {
        storeAuthStateInCookie: isIE || isEdge || isFirefox
    },
```

### Relevant Code Snippets

```javascript
Download your own code sample and following the guide.
```

### Reproduction Steps

1. Fork Repo
2. git clone code
3. npm install - main directory
4. cd samples/msal-react-samples/react-router-sample
5. npm run build:package                                                        (another error this doesn't work)
6. npm run install:local 
7. npm start                                                                                (application doesnt start after this)
8. npm run install:published          
9. npm install
10. npm start - application starts

### Expected Behavior

I want the application to recognize my email and login

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by derisen** [comment]
@rdick your request is going to the wrong authority (`login.windows-ppe.net` is for internal use). Please update the authority field in your configuration file. Depending on your app's [audience](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-supported-account-types), this will most likely be `https://login.microsoftonline.com/common` or `https://login.microsoftonline.com/YOUR_TENANT_ID`.

See [these samples](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial) for more guidance.
