### ISSUE TITLE
Support for the response_type=none workflow

### ISSUE THREAD

**Issue by jrmcdona** [AzureAD/microsoft-authentication-library-for-js#404]
Hello,

I need to generate two different tokens because I am connecting to two different services.  Each serviceh has its own scope.

The worfkflow would look like this:

1.	response_type=**none**&scope=scope1+scope2
2.	response_type=**token**&scope=scope1&prompt=**none**
3.	response_type=**token**&scope=scope2&prompt=**none**

The latter two could be done in an iframe perhaps

Do you have any kind of support for this?

**Comment by navyasric** [comment]
@jrmcdona The library does not support response_type=none. You can get the consent for scopes for two different services by passing the scopes in the loginRedirect or loginPopup method.
When you want to get the tokens, you can call acquireTokenSilent method to get the token with prompt=none.
