### ISSUE TITLE
Log in a user when open a new tab with the same application. 

### ISSUE THREAD

**Issue by yakimko** [AzureAD/microsoft-authentication-library-for-js#405]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x ] Other... Please describe:
</code></pre>

## Library version

<pre><code>
Library version: 0.2.1

</code></pre>

Hi! I develop angular 6 app using B2C auth. I use **sessionStorage** to store user's session. 
When I already logged in to the app and when I open the same app in a new tab I want to be logged in here too.
How I can make it possible without using localStorage?
Thanks!

**Comment by navyasric** [comment]
@yakimko SessionStorage cannot be shared between tabs. You will need to use localStorage for this. Is there a reason you cannot or don't want to use the localStorage?

**Comment by yakimko** [comment]
@navyasric 
I have a few opened tabs with logged in user.
When I close the last tab with opened application I need to be logout from the app(just clean storage. when I use sessionStorage it cleans automatically).

When I use localStorage I can share a session between tabs but I can't logout a user from the app when the user close the last tab, because I do not know is he close the tab or just refresh the page.

**Comment by visualjeff** [comment]
A possible alternative to using localStorage events for cross-tab communication might be to use the **Broadcast Channel API**.   At one time not all browsers provided support for it.  But that was a while ago.

**Comment by nehaagrawal** [comment]
@yakimko MSAL currently doesn't provide any API to support this feature. I am closing this for now.
