### ISSUE TITLE
skip offline_access scope while signing in user

### ISSUE THREAD

**Issue by manishpatil8149** [AzureAD/microsoft-authentication-library-for-js#4051]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.16.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.1

### Description

I am using MSAL libraries in my React SPA. With Default configuration as shown below I haven't added 'offline_access' scope while requesting id tokens. But When I try to login as a user offline_access is automatically added. I see in your FAQs you have mentioned that as default scope but my tenant admin has reservations to allow this scope for my app. Is there any way I can avoid using this scope? 

### MSAL Configuration

```javascript
export const msalConfig = {
  auth: {
    clientId: "Enter_the_Application_Id_Here",
    authority: "Enter_the_Cloud_Instance_Id_Here/Enter_the_Tenant_Info_Here",
    redirectUri: "Enter_the_Redirect_Uri_Here",
  },
  cache: {
    cacheLocation: "sessionStorage", // This configures where your cache will be stored
    storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
  }
};

// Add scopes here for ID token to be used at Microsoft identity platform endpoints.
export const loginRequest = {
 scopes: ["User.Read"]
};

// Add the endpoints here for Microsoft Graph API services you'd like to use.
export const graphConfig = {
    graphMeEndpoint: "Enter_the_Graph_Endpoint_Here/v1.0/me"
};
```

### Identity Provider

Other

### Source

Internal (Microsoft)

**Comment by hectormmg** [comment]
Hi @manishpatil8149 , MSAL v2 doesn't currently support opting out of any default scopes. One available workaround is to use MSAL v1, which doesn't include `offline_access` as one of the default scopes. The main drawback is that we're only maintaining MSAL v1 for security updates at the moment, and will not be providing much additional maintenance or support for it in the future.
