### ISSUE TITLE
One msalInstance for multiple MsalProvider components

### ISSUE THREAD

**Issue by LukasCornille** [AzureAD/microsoft-authentication-library-for-js#4059]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.17.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.2

### Description

Hi,

I'm trying to create several custom elements that make use of the react-msal library to authenticate user. 
The use case for this is that I have a static website, which will implement these elements to allow for a nice user experience. 

Currently, I have two elements, one element is a simple login/logoff button and the actual SPA that implements some functionality, such as retrieving information from an API that requires an access token. An important note is that the SPA element requires the user to be logged in before being able to render it, if the user is not logged in this component wil also automatically redirect the user to log in.

At the moment, I'm initialising the MsalInstance in the register function, which is then passed as a prop to both elements so both can render the MsalProvider and pass down the required functionality. Everything seems to work unless when the user navigates to the SPA page, without actually being logged in. This causes a redirect flow, which then infinitely loops when the user is redirected back to the SPA page.

Is there a way for me to have two components make use of an MsalProvider while both being able to access the msalInstance?

### MSAL Configuration

```javascript
export const msalConfiguration = (clientId: string): Configuration => ({
  auth: {
    clientId,
    authority: '<my-authority>',
    navigateToLoginRequestUrl: true,
    postLogoutRedirectUri: '/',
    knownAuthorities: ['<my-known-authority>'],
  },
  cache: {
    cacheLocation: 'sessionStorage',
    storeAuthStateInCookie: false,
  },
});
```

### Relevant Code Snippets

register.ts:
```typescript

let msalInstance: IPublicClientApplication;

const registerCustomElements = (clientId: string) => {
  msalInstance = new PublicClientApplication(msalConfiguration(clientId));

  register('authentication', () => import(`./customElements/Authentication`), msalInstance);
  register('spa', () => import(`./customElements/spa`), msalInstance);
}
```

Authentication.tsx
```tsx
interface Props {
  msalInstance: IPublicClientApplication;
}

const Authentication = ({ msalInstance }: Props) => {
  return (
    <MsalProvider instance={msalInstance}>
      <AuthenticationButton />
    </MsalProvider>
  );
};
```

SPA.tsx
```tsx
interface Props {
  msalInstance: IPublicClientApplication;
}

const ProfileWrapper = ({ msalInstance }: Props) => {
  return (
    <MsalProvider instance={msalInstance}>
      <SPA />
    </MsalProvider>
  );
};
```

### Identity Provider

Azure B2C Basic Policy

### Source

External (Customer)

**Comment by tnorling** [comment]
@LukasCornille Using multiple instances of the `MsalProvider` component is not a recommended pattern. You should instead render a single MsalProvider component at the top level (or as high up as you can) and then conditionally render your other components underneath. `msal-react` provides components to help you do this. For example to achieve the scenario you've listed above you can use the `MsalAuthenticationTemplate` component which will only render children if a user is signed in and auto-invoke sign in if a user is not signed in. That would look something like this:

```javascript
const ProfileWrapper = () => {
  return (
      <MsalAuthenticationTemplate interactionType={InteractionType.Redirect}>
          <SPA />
      </ MsalAuthenticationTemplate>
  );
};

ReactDOM.render(
    <React.StrictMode>
        <MsalProvider instance={msalInstance}>
          <AuthenticationButton />
          <ProfileWrapper />
        </MsalProvider>
    </React.StrictMode>,
    document.getElementById('root')
);
```

**Comment by LukasCornille** [comment]
I've resolved this issue by using the JS library over the React library. As I stated I'm using a static element with multiple custom elements in which React components live. The solution provided by @tnorling therefore does not work, by using the JS library I was able to handle the redirect promise before registering the custom elements and therefore only initialise the library once.
