### ISSUE TITLE
What to set clientInfo as when side loading tokens for testing?

### ISSUE THREAD

**Issue by JamesBaxterSoftware** [AzureAD/microsoft-authentication-library-for-js#4063]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.17

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

none

### Description

I am following documentation below to side load tokens for testing purposes but I do not know what clientInfo should be set to?

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/testing.md

```
const tokenOptions: msal.LoadTokenOptions = {
   clientInfo: "i do not know what to set this to?",
   extendedExpiresOn: 3600
}
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by pkanher617** [comment]
The client_info should be available on the response from the /authorize endpoint with the authorization code. Please make sure you set `client_info=1` on the request to the /authorize endpoint. If you cannot obtain the client info from the /authorize endpoint, then you won't be able to save tokens correctly in the MSAL library.

**Comment by JamesBaxterSoftware** [comment]
what do you mean by the  /authorize endpoint? we are using signup/signup to login and I was planning on using ROPC to sideload the token for testing. I do not understand your answer. Thanks

**Comment by pkanher617** [comment]
@JamesBaxterSoftware Sorry for the delay in response. When you acquire tokens, you will need to request the client info property alongside the tokens. You can do this by adding `client_info=1` in the url of the request to obtain the ROPC tokens.

**Comment by sbarfurth** [comment]
Where do I get `client_info` when using ADFS?

**Comment by sameerag** [comment]
`client_info` is not issued for ADFS. For ADFS `localAccountId` is populated instead.

```javascript
const accountId = idToken?.claims?.sub ? idToken.claims.sub : Constants.EMPTY_STRING;

        // since ADFS does not have tid and does not set client_info
        if (authType === AuthorityType.Adfs) {
            return accountId;
        }
```

Relevant code can be checked [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/7b5f2eaef2eede43f23765b97547922f0024437d/lib/msal-common/src/cache/entities/AccountEntity.ts#L240)
