### ISSUE TITLE
Deprecate library in npmjs.com

### ISSUE THREAD

**Issue by icazemier** [AzureAD/microsoft-authentication-library-for-js#4065]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

latest

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

Please just deprecate the npm package in npmjs.com also.

This is as easy as: `npm deprecate  msal "Future versions...."`

This makes it clear,easy to understand and npm would give warnings when one tries to install it.

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@icazemier Thanks for the feedback. We are not ready to fully deprecate `msal` v1 yet, but when we are, we will make sure to take this into account.

Closing, as no further action needed at this time.
