### ISSUE TITLE
Samples link broken for B2C

### ISSUE THREAD

**Issue by jasonbrice** [AzureAD/microsoft-authentication-library-for-js#4067]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

Not Applicable

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Samples

### Description

The link for the b2c-javascript-spa sample gives a 404 not found -> https://github.com/Azure-Samples/active-directory-b2c-javascript-spa

**Comment by derisen** [comment]
@jasonbrice thanks for catching this! We'll get that fixed -the link should have been: https://github.com/Azure-Samples/ms-identity-b2c-javascript-spa

**Comment by derisen** [comment]
The link is now fixed. Closing this.
