### ISSUE TITLE
Azure AD B2C sample cannot acquire accessToken

### ISSUE THREAD

**Issue by jasonbrice** [AzureAD/microsoft-authentication-library-for-js#4070]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

azure/msal-browser@2.13.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

Using the Azure AD B2C samples outlined [here ](https://github.com/Azure-Samples/ms-identity-b2c-javascript-spa) and [here](https://github.com/Azure-Samples/active-directory-b2c-javascript-nodejs-webapi), I have successfully been able to authenticate using a signup / signin flow. 

However when I click the Call API button, the response contains an idToken but no accessToken. MSAL goes through the process of acquiring a token through popup, but that fails too. 

I have confirmed that my registered app is set up to issue both access and id tokens: 
![image](https://user-images.githubusercontent.com/1713380/133685774-e8036e69-28a6-4033-a828-748fd97462bd.png)

### Error Message

This error is happening because the accessToken is blank: 

api.js:15 GET http://localhost:5000/hello 401 (Unauthorized)
callApi @ api.js:15
(anonymous) @ authPopup.js:147
Promise.then (async)
passTokenToApi @ authPopup.js:143
onclick @ (index):39
api.js:25 SyntaxError: Unexpected token U in JSON at position 0
(anonymous) @ api.js:25
Promise.catch (async)
callApi @ api.js:24
(anonymous) @ authPopup.js:147
Promise.then (async)
passTokenToApi @ authPopup.js:143
onclick @ (index):39

### Msal Logs

[Thu, 16 Sep 2021 21:06:42 GMT] :  : @azure/msal-browser@2.13.1 : Info - Emitting event: msal:acquireTokenStart
authConfig.js:31 [Thu, 16 Sep 2021 21:06:42 GMT] :  : @azure/msal-browser@2.13.1 : Info - Emitting event: msal:acquireTokenFromNetworkStart
authConfig.js:31 [Thu, 16 Sep 2021 21:06:43 GMT] :  : @azure/msal-browser@2.13.1 : Info - Emitting event: msal:acquireTokenSuccess
authPopup.js:125 Silent token acquisition fails. Acquiring token using popup. 
 InteractionRequiredAuthError
    at InteractionRequiredAuthError.AuthError [as constructor] (index.es.js:422)
    at InteractionRequiredAuthError.ServerError [as constructor] (index.es.js:2778)
    at new InteractionRequiredAuthError (index.es.js:3666)
    at authPopup.js:120
authConfig.js:31 [Thu, 16 Sep 2021 21:06:43 GMT] :  : @azure/msal-browser@2.13.1 : Info - Emitting event: msal:acquireTokenStart
authConfig.js:31 [Thu, 16 Sep 2021 21:06:43 GMT] :  : @azure/msal-browser@2.13.1 : Info - Emitting event: msal:popupOpened
authConfig.js:31 [Thu, 16 Sep 2021 21:06:44 GMT] :  : @azure/msal-common@4.1.1 : Info - in acquireToken call
authConfig.js:31 [Thu, 16 Sep 2021 21:06:45 GMT] :  : @azure/msal-browser@2.13.1 : Info - BrowserCacheManager.cleanRequestByState: Removing temporary cache items for state: eyJpZCI6ImU2MDU2YzJjLWU5MWItNDEyNC05MWJjLWUyNTA3NzdiMTljMiIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicG9wdXAifX0=
authConfig.js:31 [Thu, 16 Sep 2021 21:06:45 GMT] :  : @azure/msal-browser@2.13.1 : Info - Emitting event: msal:acquireTokenSuccess
authPopup.js:130 {authority: 'https://ambaguest.b2clogin.com/ambaguest.onmicrosoft.com/b2c_1_signupsignin1/', uniqueId: '21397728-62d1-4837-bd1d-db3dd9844adf', tenantId: '', scopes: Array(0), account: {…}, …}
authPopup.js:145 access_token acquired at: Thu Sep 16 2021 16:06:45 GMT-0500 (Central Daylight Time)

### MSAL Configuration

```javascript
/**
 * Configuration object to be passed to MSAL instance on creation. 
 * For a full list of MSAL.js configuration parameters, visit:
 * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/configuration.md
 * For more details on using MSAL.js with Azure AD B2C, visit:
 * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/working-with-b2c.md 
 */

const msalConfig = {
    auth: {
      clientId: "eeff946f-5d1a-43db-885f-bbb4f662a848", // This is the ONLY mandatory field; everything else is optional.
      authority: b2cPolicies.authorities.signUpSignIn.authority, // Choose sign-up/sign-in user-flow as your default.
      knownAuthorities: [b2cPolicies.authorityDomain], // You must identify your tenant's domain as a known authority.
      redirectUri: "http://localhost:6420", // You must register this URI on Azure Portal/App Registration. Defaults to "window.location.href".
    },
    cache: {
      cacheLocation: "sessionStorage", // Configures cache location. "sessionStorage" is more secure, but "localStorage" gives you SSO between tabs.
      storeAuthStateInCookie: false, // If you wish to store cache items in cookies as well as browser cache, set this to "true".
    },
    system: {
      loggerOptions: {
        loggerCallback: (level, message, containsPii) => {
          if (containsPii) {
            return;
          }
          switch (level) {
            case msal.LogLevel.Error:
              console.error(message);
              return;
            case msal.LogLevel.Info:
              console.info(message);
              return;
            case msal.LogLevel.Verbose:
              console.debug(message);
              return;
            case msal.LogLevel.Warning:
              console.warn(message);
              return;
          }
        }
      }
    }
  };
  
/**
 * Scopes you add here will be prompted for user consent during sign-in.
 * By default, MSAL.js will add OIDC scopes (openid, profile, email) to any login request.
 * For more information about OIDC scopes, visit: 
 * https://docs.microsoft.com/azure/active-directory/develop/v2-permissions-and-consent#openid-connect-scopes
 */
const loginRequest = {
  scopes: ["openid", ...apiConfig.b2cScopes],
};

/**
 * Scopes you add here will be used to request a token from Azure AD B2C to be used for accessing a protected resource.
 * To learn more about how to work with scopes and resources, see: 
 * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/resources-and-scopes.md
 */
const tokenRequest = {
  scopes: ["https://ambaguest.onmicrosoft.com/eeff946f-5d1a-43db-885f-bbb4f662a848/User.Read", ...apiConfig.b2cScopes],  // e.g. ["https://fabrikamb2c.onmicrosoft.com/helloapi/demo.read"]
  forceRefresh: false // Set this to "true" to skip a cached token and go to the server to get a new token
};
```

### Relevant Code Snippets

```javascript
apiConfig.js:
// The current application coordinates were pre-registered in a B2C tenant.
const apiConfig = {
    b2cScopes: ["https://ambaguest.onmicrosoft.com/eeff946f-5d1a-43db-885f-bbb4f662a848/User.Read"],
    webApi: "http://localhost:5000/hello"
  };

authConfig.js:
/**
 * Configuration object to be passed to MSAL instance on creation. 
 * For a full list of MSAL.js configuration parameters, visit:
 * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/configuration.md
 * For more details on using MSAL.js with Azure AD B2C, visit:
 * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/working-with-b2c.md 
 */

const msalConfig = {
    auth: {
      clientId: "eeff946f-5d1a-43db-885f-bbb4f662a848", // This is the ONLY mandatory field; everything else is optional.
      authority: b2cPolicies.authorities.signUpSignIn.authority, // Choose sign-up/sign-in user-flow as your default.
      knownAuthorities: [b2cPolicies.authorityDomain], // You must identify your tenant's domain as a known authority.
      redirectUri: "http://localhost:6420", // You must register this URI on Azure Portal/App Registration. Defaults to "window.location.href".
    },
    cache: {
      cacheLocation: "sessionStorage", // Configures cache location. "sessionStorage" is more secure, but "localStorage" gives you SSO between tabs.
      storeAuthStateInCookie: false, // If you wish to store cache items in cookies as well as browser cache, set this to "true".
    },
    system: {
      loggerOptions: {
        loggerCallback: (level, message, containsPii) => {
          if (containsPii) {
            return;
          }
          switch (level) {
            case msal.LogLevel.Error:
              console.error(message);
              return;
            case msal.LogLevel.Info:
              console.info(message);
              return;
            case msal.LogLevel.Verbose:
              console.debug(message);
              return;
            case msal.LogLevel.Warning:
              console.warn(message);
              return;
          }
        }
      }
    }
  };
  
/**
 * Scopes you add here will be prompted for user consent during sign-in.
 * By default, MSAL.js will add OIDC scopes (openid, profile, email) to any login request.
 * For more information about OIDC scopes, visit: 
 * https://docs.microsoft.com/azure/active-directory/develop/v2-permissions-and-consent#openid-connect-scopes
 */
const loginRequest = {
  scopes: ["openid", ...apiConfig.b2cScopes],
};

/**
 * Scopes you add here will be used to request a token from Azure AD B2C to be used for accessing a protected resource.
 * To learn more about how to work with scopes and resources, see: 
 * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/resources-and-scopes.md
 */
const tokenRequest = {
  scopes: [...apiConfig.b2cScopes],  // e.g. ["https://fabrikamb2c.onmicrosoft.com/helloapi/demo.read"]
  forceRefresh: false // Set this to "true" to skip a cached token and go to the server to get a new token
};
```

### Reproduction Steps

1. Install and configure both demo apps. 
2. Start both demo apps.
3. Navigate to http://localhost:6420
4. Click 'Call API'
5. 

### Expected Behavior

Expected to get a 200 OK response from the web api app. 

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by derisen** [comment]
@jasonbrice In Azure Portal > App Registration, please **uncheck** the boxes under the **Implicit grant and hybrid flows** section, as this sample was meant to work with [authorization code flow with PKCE](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow), not [implicit flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-implicit-grant-flow).

**Comment by jasonbrice** [comment]
I've unchecked both boxes and saved the app, same results. 
![image](https://user-images.githubusercontent.com/1713380/133778266-0b98174a-f88c-479f-aa65-4889ba51c39c.png)

![image](https://user-images.githubusercontent.com/1713380/133778339-660f244f-26d2-423f-8abd-7234d17ca04c.png)

**Comment by derisen** [comment]
@jasonbrice apologies, my bad this wasn't related to your issue. For some reason the scopes field looks empty in your `acquireTokenPopup` response (the last screenshot), so can you clarify what is the exact request object you are passing to that API?

**Comment by jasonbrice** [comment]
I'm assuming that the scope for the accessToken is in the authConfig.js ? 

![image](https://user-images.githubusercontent.com/1713380/133845029-2b6a3167-8c78-4de9-8929-566caad5d000.png)

I've tried plugging the values "openid", "offline_access", ...apiConfig.b2cScopes, and the URI of the api I exposed: "https://ambaguest.onmicrosoft.com/eeff946f-5d1a-43db-885f-bbb4f662a848/User.Read"

![image](https://user-images.githubusercontent.com/1713380/133845222-cc1c726c-b896-4b26-b598-87ac6257fc68.png)

**Comment by derisen** [comment]
@jasonbrice Ok that must be the issue, you cannot mix scopes for different resources in the same token request, take a look at our [documentation](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/resources-and-scopes.md) on this. Basically, make sure only the scope for your web API goes into the tokenRequest object (i.e. `https://ambaguest.onmicrosoft.com/eeff946f-5d1a-43db-885f-bbb4f662a848/User.Read`), `openid `and `offline_access `are MS Graph scopes.

**Comment by jasonbrice** [comment]
Ok, I've changed the b2cScopes in apiConfig.js to the one I created: 
![image](https://user-images.githubusercontent.com/1713380/133860740-ae05fb1f-09e0-469e-835e-331decd1957c.png)

I've changed the scopes in the authConfig.js to match: 
![image](https://user-images.githubusercontent.com/1713380/133860770-9aeafbb3-3c3d-480a-bc32-396794ccaf2b.png)

I'm still getting a blank access token... I tried both with the boxes unchecked and then rechecking the boxes. 

Any ideas?

**Comment by derisen** [comment]
@jasonbrice are you signing in with an admin account? In the screenshot you shared (the second one [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4070#issuecomment-922040138)), you choose "only admins can consent to this scope". Did you grant [admin consent](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-admin-consent) to this scope in your client application's app registration?
