### ISSUE TITLE
Not getting Groups as a claim in access token.

### ISSUE THREAD

**Issue by Shriyanshmit** [AzureAD/microsoft-authentication-library-for-js#4075]
### Core Library

Passport Azure AD (passport-azure-ad)

### Core Library Version

2.14.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

2.0.0

### Description

I have created custom **API permissions** which include attached setting. 
![image](https://user-images.githubusercontent.com/11751143/134021698-b455e131-3d2e-4872-84f4-b2ca6000fc77.png)

Now In the node js config section I changed the scope to   scope: ['profile', 'offline_access','api://ID/ReadAllScope'] but I am not getting groups info inside access token. Groups are coming under profile variable.

Please let me know is it possible get roles in access token?

### MSAL Configuration

```javascript
I have created custom **API permissions** which include attached setting. 
![image](https://user-images.githubusercontent.com/11751143/134021698-b455e131-3d2e-4872-84f4-b2ca6000fc77.png)

Now In the node js config section I changed the scope to   scope: ['profile', 'offline_access','api://ID/ReadAllScope'] but I am not getting groups info inside access token. Groups are coming under profile variable.

Please let me know is it possible get roles in access token?
```

### Relevant Code Snippets

```javascript
I have created custom **API permissions** which include attached setting. 
![image](https://user-images.githubusercontent.com/11751143/134021698-b455e131-3d2e-4872-84f4-b2ca6000fc77.png)

Now In the node js config section I changed the scope to   scope: ['profile', 'offline_access','api://ID/ReadAllScope'] but I am not getting groups info inside access token. Groups are coming under profile variable.

Please let me know is it possible get roles in access token?
```

### Reproduction Steps

Change scope.+

### Expected Behavior

Group id in access token

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

Internal (Microsoft)

**Comment by derisen** [comment]
@Shriyanshmit do you mean roles claim or groups claim (or both?) Regardless, roles claim should appear in access tokens by default, while groups claim should be configured via custom token claims configuration blade on the app registration portal. Take a look at these samples: [React SPA calling Node.js web API using App Roles](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/tree/main/5-AccessControl/1-call-api-roles) and [React SPA calling Node.js web API using Security Groups](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/tree/main/5-AccessControl/2-call-api-groups).

**Comment by Shriyanshmit** [comment]
Thanks for your quick response.

I am following below article with nodejs
https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-nodejs-webapp

But I am getting groups inside access token. It is coming under profiles.

**In Config File:**
  scope: ['profile', 'offline_access','api://ID/ReadAllScope']

This is custom API permission.

**Comment by derisen** [comment]
@Shriyanshmit no worries : ) The the second sample link I've shared is exactly what you want. Regardless, by "it is coming under profiles" I think you mean it is coming in the ID token. This is configurable via the App registration portal: 

![ss2](https://user-images.githubusercontent.com/13197548/134056777-08d01c46-4fa7-4fec-83ce-ca5a804388e4.png)
