### ISSUE TITLE
error TS2717: Subsequent property declarations must have the same type

### ISSUE THREAD

**Issue by ssack** [AzureAD/microsoft-authentication-library-for-js#408]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [X] Chrome version XX
- [X] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 0.1.1

## Minimal reproduction of the problem with instructions

Recieve the following error when compiling our app...

ERROR in node_modules/msal/lib-commonjs/UserAgentApplication.d.ts(6,9): error TS2717: Subsequent property declarations must have the same type.  Property 'callBackMappedToRenewStates' must be of type '{}', but here has type 'Object'.
node_modules/msal/lib-commonjs/UserAgentApplication.d.ts(7,9): error TS2717: Subsequent property declarations must have the same type.  Property 'callBacksMappedToRenewStates' must be of type '{}', but here has type 'Object'.

Here is a code snippet for my use of the library:

import {MsalService, BroadcastService} from '@azure/msal-angular';
import {Subscription} from 'rxjs';

constructor(private modalService: NgbModal,
              private router: Router,
              private authService: MsalService,
              private broadcastService: BroadcastService ,
              private logger: LogService) {

    // This is to avoid reload during acquireTokenSilent() because of a hidden iFrame
    this.isIframe = window !== window.parent && !window.opener;
    this.loggedIn = !!this.authService.getUser();

  }

ngOnInit() {

    this.broadcastService.subscribe("msal:loginFailure",
      (payload) => {
        console.log("Login Failure", payload);
        this.loggedIn = false;
      });

    this.broadcastService.subscribe("msal:loginSuccess",
      (payload) => {
        console.log("Login Success", payload);
        this.loggedIn = true;
     });   
  }

  // revolving background functionality
  ngAfterViewInit() {
    const test = document.getElementById('landing');
    const num = Math.floor(Math.random() * (this.max - this.min + 1) + this.min);
    test.classList.add(`back${num}`);
  }

  ngOnDestroy() {
    this.broadcastService.getMSALSubject().next(1);
    if (this.subscription) {
      this.subscription.unsubscribe();
    }
  }

login(email) {
    const msg = "This must be a valid email."
    console.log(email, this.regexEmail);
    if (!(this.regexEmail.test(email.value))) {
      this.seeEmailInvalidModal = true;
      // console.log('failed!')
    } else {
      // console.log('passed!')
      this.authService.loginPopup();

    }
  }

</code></pre>

**Comment by nehaagrawal** [comment]
@ssack  Can you please confirm that your application doesn't have a direct dependency on msal? If you are using msal-angular, msal would be bundled along with it.

**Comment by nehaagrawal** [comment]
@ssack  I was able to reproduce this if I have both msal 0.1.3(very old) and @azure/msal-angular 0.1.1 as a dependency in my package.json. As I mentioned earlier, msal-angular has a dependency on msal and it will download it for you. Users of msal-angular don't need to install msal separately. I am closing this issue for now. Please reopen if the issue still exists.
