### ISSUE TITLE
Add IsAuthenticated() method to ConfidentialClient 

### ISSUE THREAD

**Issue by arvindbhairat** [AzureAD/microsoft-authentication-library-for-js#4090]
### Core Library

MSAL Node (@azure/msal-node)

### Wrapper Library

Not Applicable

### Description

Hi,

I am using @azure/msal-node with my express app to authenticate users. When the user if redirected to redirect URL, I am redirecting user to another route (say /dashboard). I need to check if the user visiting /dashboard is authenticated or not. As the authentication is handled by ConfidentialClient in my case, there should be a method called IsAuthenticated() to know if current user visiting /dashboard is authenticated or not.

As a workaround (not really a good idea), I had to pass account.localAccountId from acquireTokenByCode promise to /dashboard and use that to determine if there exists an account in token cache with given id. 

Thanks,
Arvind 

### Source

External (Customer)

**Comment by tnorling** [comment]
@arvindbhairat msal-node exposes a couple account APIs to help you with this. If you just want to know if **any** user is authenticated you can call `getAllAccounts` and verify that at least 1 account is returned. If you want to know if a **specific** user is authenticated you can call `getAccountByHomeId` or `getAccountByLocalId`. [This doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/accounts.md) goes into more detail about these APIs. Can you please check that out and let me know if this addresses your use case?
