### ISSUE TITLE
Outlook add-in - React Web App - MSAL authentication - SSO - Desktop Mode issue

### ISSUE THREAD

**Issue by MahammedAslam** [AzureAD/microsoft-authentication-library-for-js#4095]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.16.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.1

### Description

Authentication implemented using MSAL package ( "@azure/msal-browser": "^2.16.1", "@azure/msal-react": "^1.0.1",) For Outlook Web client - online (O365 version), it's working as expected with login prompt opened for credentials whereas it fails to load login popup window for Outlook desktop mode.  Similar issue was earlier reported by few users under- [#1072](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1072) And team responded that bug was fixed for core MSAL package but currently it's not working for React based Outlook Add-in with msal-react.

@

### Error Message

"You'll need a new app to open this about link"

### MSAL Configuration

```javascript
export const msalConfig = {
  auth: {
    authority:.authority,
    clientId: clientId,
    redirectUri: redirectUri,
    navigateToLoginRequestUrl: true,
  },
  cache: {
    cacheLocation: "localStorage",
    storeAuthStateInCookie: true,
  },
};
```

### Relevant Code Snippets

```javascript
this.context.instance
        .loginPopup(loginRequest)
        .then((response) => {
          this.setState({ currentLoggedInAccount: response.account });
        })
        .catch((e) => {
          console.log(e);
        });
```

### Reproduction Steps

1) Access Outlook Add-in from Outlook desktop client
2) Responded with "You'll need a new app to open this about link"

### Expected Behavior

We expect same behavior for desktop Outlook as working under Outlook web client

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Regression

NA

### Source

External (Customer)

**Comment by MahammedAslam** [comment]
@samuelkubai  - Please let us know for more details(if any) in investigating our issue. We  anticipate quick response and resolution to above issue.

**Comment by MahammedAslam** [comment]
Hi @samuelkubai , Thanks for responding. 

In high level, our team followed different  approach to facilitate SSO along with MSAL authentication for Outlook Add-in by  leveraging  ‘msal-react’ package (MSAL package ( "@azure/msal-browser": "^2.16.1", "@azure/msal-react": "^1.0.1") and ‘acquireTokenSilent’ method. 

**References used in our Approach:-**

1)	[Acquire token for an API](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-acquire-token?tabs=react)
2)	[Authentication for React SPA](https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-react)

Please confirm whether it's feasible to overcome current issue by tweaking some code changes in above approach with some sample. 

If it's not feasible with above approach, please share sample for React based Outlook Add-in with MSAL along with SSO implemented.

**Comment by samuelkubai** [comment]
Hi @MahammedAslam,

To best understand how to support you, we would like to understand where exactly the sample we provided branches out from your current implementation and how exactly you have been unable to integrate our recommended approach.

Because msal-react just adds some additional react specific layers on top of msal-browser, you can use as much or as little as you want but either way msal-browser is still handling most of the logic.

For the initial issue raised, In order to do popup auth in an office addin, the application must open a dialogue using the office sdk, and then perform loginredirect inside that popup, which the sample demonstrates.

**Comment by MahammedAslam** [comment]
Hello @samuelkubai , Thank you once again for confirming on usage of Office SDK and loginredirect method for current issue. Our team started to explore suggested approach in integrating  with current implementation.

We'll let you know on outcome once tested after integration from our end. We would also demonstrate our current case through connect call planned for any assistance and sorting out reported issue.

**Comment by MahammedAslam** [comment]
Hi @samuelkubai, We will keep you posted on outcome  of suggested approach as implementation didn't occurred since team engaged with other priority activities.

**Comment by MahammedAslam** [comment]
Hi @samuelkubai and @tnorling,

We went through the sample code shared to us and understood the flow as follows:

1.	We observed the app.tsx, signinO635 function tries to open a office SDK dialog box in which login html has been called.
2.	This login.html in turn call login.js which does the AD authentication using MSALinstance.handleRedirectPromise()
3.	Response (includes access token) is return to signinO365. Token is saved in variable in app.tsx
4.	If response has success status, dialog box will be closed.
Based on the above understanding, we have retrofitted this logic into our code which has been written in React with JavaScript and using class components.

Only difference between our code and the sample is we are using JavaScript instead of typescript

**Our code flows a follows:**

1.	Initial html file will call parent component (index.js)
2.	index.js parent component will render child component app.js
3.	While rendering app.js under componentdidmount event, we are calling login asynchronous function which embedded the same logic of signinO365 function shared in the sample code and it calls Office.dailog (Office.context.ui.displayDialogAsync)
4.	Inside OfficeDialog function we have called login.html inturn call login.js component which does AD Authentication using MSALinstance.handleRedirectPromise()
5.	Same code which receives the Response (includes access token) has been included in this login asynchronous function.

**Outcome:** Our code flows come till calling login asynchronous function (Refer point #4 from our code flow) after which we expect dialog to open and authenticate the user but this flow gets terminated here and we are not seeing the dialog popup.
Can we have quick WebEx or Teams session to run the code flow and help us with your inputs?

**Comment by jasonnutter** [comment]
@MahammedAslam 

> Our code flows come till calling login asynchronous function (Refer point #4 from our code flow) after which we expect dialog to open and authenticate the user but this flow gets terminated here and we are not seeing the dialog popup.

To clarify, are you saying that when your application calls `Office.context.ui.displayDialogAsync` (as demonstrated [here](https://github.com/OfficeDev/PnP-OfficeAddins/blob/main/Samples/auth/Office-Add-in-Microsoft-Graph-React/utilities/office-apis-helpers.ts#L43)), nothing happens? Is an error thrown?

**Comment by MahammedAslam** [comment]
Hi @jasonnutter ,

In our App component under componentdidmount we are calling login function which inturns calls SIgnINO365 helper function where it reaches there and it runs without opening the dailog popup. **We are not getting any error**

Please find code block where we were calling above method:

```js
export const signInO365 = async (

  setState: (x: AppState) => void,

  setToken: (x: string) => void,

  displayError: (x: string) => void

) => {

  setState({ authStatus: "loginInProcess" });



  await Office.context.ui.displayDialogAsync(

    dialogLoginUrl,

    { height: 40, width: 30 },

    (result) => {

      if (result.status === Office.AsyncResultStatus.Failed) {

        displayError(`${result.error.code} ${result.error.message}`);

      } else {

        loginDialog = result.value;

        loginDialog.addEventHandler(

          Office.EventType.DialogMessageReceived,

          processLoginMessage

        );

        loginDialog.addEventHandler(

          Office.EventType.DialogEventReceived,

          processLoginDialogEvent

        );

      }

    }

  );
```

**Comment by jasonnutter** [comment]
@MahammedAslam 

Please confirm the following:

1. Office JS SDK is loaded correctly.
2. The `dialogLoginUrl` is set.
3. `dialogLoginUrl` is on the same domain as your application
4. Also, please confirm if the provided sample application works as expected.

And please review the documentation for Office addin dialogs here:

- https://docs.microsoft.com/office/dev/add-ins/develop/dialog-api-in-office-add-ins
- https://docs.microsoft.com/office/dev/add-ins/develop/auth-with-office-dialog-api

Unfortunately, we can't provide further help for issues/bugs with the Office JS SDK. Please file an issue with their team here: https://github.com/OfficeDev/office-js/issues

**Comment by skurian123** [comment]
Hello @jasonnutter 

1. Office JS SDK is loaded correctly.  - Yes
2. The dialogLoginUrl is set. - Yes
3. dialogLoginUrl is on the same domain as your application - Yes
4. Also, please confirm if the provided sample application works as expected -No

Ticket - https://github.com/OfficeDev/office-js/issues/2184 is raised under Office JS.

**Comment by MahammedAslam** [comment]
Hello @jasonnutter ,

Please find our respone as quoted by our team in earlier comment below:

1.	Office JS SDK is loaded correctly. - **Yes**
2.	The dialogLoginUrl is set. - **Yes**
3.	dialogLoginUrl is on the same domain as your application - **Yes**
4.	Also, please confirm if the provided sample application works as expected. - **No**

As suggested new Ticket - OfficeDev/office-js#2184  also raised under Office JS SDK forum though unclear if it's root cause. 

**We may once again request for quick connect call with your team to troubleshoot our issue by understanding root cause through demonstration of our Code base. Would like to clear gap in implementation/understanding our case with Connect call**

**Comment by jasonnutter** [comment]
@MahammedAslam Thanks, I'll keep an eye on that issue. Note, I am unable to reproduce your issue, as I am able to get the linked sample addin to work properly by following the instructions provided in the sample README.

**Comment by skurian123** [comment]
Hello @jasonnutter 
Unfortunately we're not able to the make the sample addin worked even after following the instructions. Do we need to make any specific configurations at the o365 tenant end. Also, is there any way we can get into a WebEx or MS team calls so that we can explain through our code ?

**Comment by DChefHarshil** [comment]
@jasonnutter I am facing the same issue but I have a little bit different approach. I want to use SSO token to exchange it with access token for Azure AD App registration. To get SSO token from Outlook, I am using following snippet. 

`
        let bootstrapToken = await OfficeRuntime.auth.getAccessToken(options);
`

I can't see any method in msal-browser that allow me to exchange the SSO Token for an access token. There is a different method suggested in the docs that uses [sample tutorial](https://docs.microsoft.com/en-us/learn/modules/office-add-ins-sso/7-exercise-outlook-sso) and it only works for single scope defined in .ENV file. In my scenario, I have multiple resources (Business Central D365 and Sharepoint) for which I need access tokens to call the endpoints. Please suggest me an approach in which I can provide seamless experience to user without asking to sign in again using msal-browser and msal-react.

Many Thanks

**Comment by jasonnutter** [comment]
@DChefHarshil To exchange the SSO token for an access token, you need to perform an On-Behalf-Of flow trade using a server-side library (e.g. MSAL Node or MSAL.net) or manually, as shown these samples:

- Node: https://github.com/OfficeDev/PnP-OfficeAddins/blob/main/Samples/auth/Office-Add-in-NodeJS-SSO/Complete/routes/authRoute.js#L22-L29
- .NET: https://github.com/OfficeDev/PnP-OfficeAddins/blob/b6ce411d2ed935df4e68ec2185a9164fd64bef77/Samples/auth/Office-Add-in-ASPNET-SSO/Complete/Office-Add-in-ASPNET-SSO-WebAPI/Controllers/ValuesController.cs#L52
