### ISSUE TITLE
MSAL store auth tokens inside cookies instead of sessionStorage or localStorage

### ISSUE THREAD

**Issue by BenediktZoller** [AzureAD/microsoft-authentication-library-for-js#4102]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

Not Applicable

### Description

We currently encounter the problem of `single logout` over multiple subdomain single page applications. As long as the auth tokens are stored in sessionStorage or localStorage by msal.js library we are not able to logout the user at all opened  browser-taps instantly. We do have several apps under different subdomains which do use oauth and `single sing in` with azure b2c.

A problemsolver would be storing the auth tokens inside cookies using the domain attribute. However msal library does not provide this setting. There had been already a request which was closed.

Can you provide me a solution for my problem?

### Source

External (Customer)

**Comment by BenediktZoller** [comment]
I found this Issue: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2384 telling me to use memoryStorage if I like to store tokens in cookies. However, I don´t get it how to access the refresh token in memoryStorage cache-mode, since it is not inside the `getTokenCache()` or `AuthenticationResult`. I use redirect to obtain my tokens.

**Comment by jasonnutter** [comment]
As noted in the issue you linked, we currently do not support storing tokens in cookies. And unfortunately, the work to allow custom storage has been deprioritized, however, may be revisited in the future.

Assuming these applications are different client ids, you can achieve single logout by registering a front-channel redirect uri for each application. This page will be loaded in a hidden iframe when any other application the user is signed into performs logout. More details: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md#front-channel-logout

**Comment by BenediktZoller** [comment]
Thanks for the reply. I would be glad to see this feature in future. At the moment I can life with the iframe solution or at least a sessonStorage-solution with a short expiration date of the id-token.
