### ISSUE TITLE
MsalInterceptor breaks ngx-translate

### ISSUE THREAD

**Issue by garvraj** [AzureAD/microsoft-authentication-library-for-js#4103]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

1.4.6

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

1.1.2

### Description

Translate module seems not working with msal

### Error Message

![image](https://user-images.githubusercontent.com/41892368/135081771-e1085086-9f70-452f-9049-6bbe741935cc.png)

### MSAL Configuration

```javascript
{
      auth: {
        clientId: environment.clientId,
        authority: environment.authority,
        validateAuthority: environment.validateAuthority,
        redirectUri: environment.redirectUri
      },
      cache: {
        cacheLocation: "sessionStorage",
        storeAuthStateInCookie: isIE
      },
       system: {
        logger: new Logger(loggerCallback, {
            // correlationId: '1234',
            level: LogLevel.Verbose,
            piiLoggingEnabled: true,
        }),
    }
    }
```

### Relevant Code Snippets

```javascript
export class LanguageService {
  public languages: string[] = ['en', 'es', 'de'];

  constructor(public translate: TranslateService) {
    let browserLang:any;
    translate.addLangs(this.languages);

    if (sessionStorage.getItem('lang')) {
      browserLang = sessionStorage.getItem('lang');
    } else {
      browserLang = translate.getBrowserLang();
    }
    translate.use(browserLang.match(/en|es|de/) ? 'en' : 'en');
  }

  public setLanguage(lang:any) {
    this.translate.use(lang);
    sessionStorage.setItem('lang', 'en');
  }
}
```

### Reproduction Steps

Without login to msal, translate module is not working

### Expected Behavior

Translate should work

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge

### Regression

"@azure/msal-angular": "^1.1.2"

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@garvraj This is a known issue with known workaround, see this issue for details: #2515

Closing.
