### ISSUE TITLE
Can MSAL RIP in few years ?

### ISSUE THREAD

**Issue by nominds** [AzureAD/microsoft-authentication-library-for-js#4105]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

Not applicable

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

I have used ADAL in my project. I hear the community is suggesting MSAL is the modern library and ADAL will not be active from June 2022. 

I want to know if "MSAL" is backed by a commitment from Microsoft on continual support of the library ? Or within few years this library may also RIP and I may end up with another tech debt in my project.

### MSAL Configuration

```javascript
None. A general query.
```

### Relevant Code Snippets

```javascript
None. A general query.
```

### Source

External (Customer)

**Comment by peterzenz** [comment]
General questions about the Microsoft Support Lifecycle can be found here:  https://docs.microsoft.com/en-us/lifecycle/faq/general-lifecycle

MSAL is under active development so support will last for some time.  New releases that include general security updates and other features, including breaking changes, will come from time to time.  It's in your best interest as an application developer that supports authenticated user flows to not look at authentication as a one-off that might turn into debt in the future, but as an ongoing security component in your product that you have to allocate regular maintenance to.
