### ISSUE TITLE
OBO Token fetch takes a long time

### ISSUE THREAD

**Issue by riteshbhoi** [AzureAD/microsoft-authentication-library-for-js#4108]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.3.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

OBO token fetch call takes more than 15 seconds. Here are few correlation ids which are sent with token request
2aff96ca-48dc-48f3-8a06-e2d1788e644c
44b3cc1c-0c05-4fdc-9b0e-dc134ca4775d
0a4bb391-a9b2-4621-9ac7-793a0981b188
69342148-340c-43cb-a092-b88cc0b6ba15
2aff96ca-48dc-48f3-8a06-e2d1788e644c

### MSAL Configuration

```javascript
None
```

### Relevant Code Snippets

```javascript
None
```

### Reproduction Steps

None

### Expected Behavior

None

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Source

Internal (Microsoft)

**Comment by samuelkubai** [comment]
Hi @riteshbhoi, could you provide timestamps for each of the correlation ids?

**Comment by riteshbhoi** [comment]
Here is the timestamp details
2aff96ca-48dc-48f3-8a06-e2d1788e644c -> 9/28/2021, 12:03:56.574 PM PST
44b3cc1c-0c05-4fdc-9b0e-dc134ca4775d -> 9/28/2021, 12:03:53.249 PM PST
0a4bb391-a9b2-4621-9ac7-793a0981b188 -> 9/28/2021, 12:03:51.905 PM PST
69342148-340c-43cb-a092-b88cc0b6ba15 -> 9/28/2021, 12:03:52.990 PM PST
2aff96ca-48dc-48f3-8a06-e2d1788e644c -> 9/28/2021, 12:03:56.574 PM PST

**Comment by tnorling** [comment]
@riteshbhoi These correlationIds don't seem to be turning anything up. Can you please email me a fiddler trace (email on my profile)? Thanks!

**Comment by tnorling** [comment]
Verbose MSAL logs would also be helpful here to verify the latency isn't coming from MSAL itself
