### ISSUE TITLE
Authentication with OIDC asking for code_challenge when requesting for access tokens

### ISSUE THREAD

**Issue by Dendekky** [AzureAD/microsoft-authentication-library-for-js#4109]
### Core Library

Passport Azure AD (passport-azure-ad)

### Core Library Version

4.3.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

We are trying to authenticate users to the app using Azure AD OIDCStrategy. As stated in the documentation, if the responseType is set as 'code' or 'code id_token' or 'id_token code',  we should get an access token. However, whenever we set the response type to either of these parameters, we get the following error. 

![Screenshot 2021-09-29 at 10-11-21 Error](https://user-images.githubusercontent.com/32454388/135239353-1b0ad0a4-1715-4cf7-8743-d0407b065283.png)

There isn't anything about a code challenge in the docs. 
We've authenticated users with the strategy when the response type is set to 'id_token' only. The behaviour above occurs when we need to request for access token and changed the responseType in the strategy configuration to any of 'code' or 'code id_token' or 'id_token code'.

### MSAL Configuration

```javascript
const options = {
          identityMetadata: process.env.AZUREAD_IDENTITY_METADATA,
          clientID: process.env.AZUREAD_AUTH_CLIENT_ID,
          responseType: 'id_token code',
          responseMode: 'form_post',
          redirectUrl: process.env.AZUREAD_REDIRECT_URL,
          allowHttpForRedirectUrl: true,
          clientSecret: process.env.AZUREAD_AUTH_CLIENT_SECRET,
          validateIssuer: false,
          issuer: null,
          passReqToCallback: true,
          scope: ['offline_access', 'read'],
          loggingLevel: 'info',
};
```

### Relevant Code Snippets

```javascript
passport.use(new OIDCStrategy(options, async function (req,
        iss,
        sub,
        profile,
        jwtClaims,
        access_token,
        refresh_token,
        params,
        done
) {console.log(access_token, refresh_token)})
```

### Reproduction Steps

1. Authenticate a user with the password.authenticate method
2. Use the OIDCStrategy with the responseType set to "code".

### Expected Behavior

Authenticating a user with the password.authenticate method should obtain the access token with the other parameters like the user profile. 

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox

### Source

External (Customer)

**Comment by samuelkubai** [comment]
Hi @Dendekky, a code challenge should not be needed if you provide a secret, could you ensure the secret is being passed in the configuration.

**Comment by Dendekky** [comment]
I can confirm that we are passing the client secret into the configuration. And the AZUREAD_AUTH_CLIENT_SECRET is being picked from the env file. 
`const options = { clientSecret: process.env.AZUREAD_AUTH_CLIENT_SECRET,` ...rest }.

**Comment by tnorling** [comment]
@Dendekky Can you please email me a fiddler trace (email on my profile)? Thanks!

**Comment by Dendekky** [comment]
Okay. I'll get the fiddler trace to you as soon as possible.

**Comment by tnorling** [comment]
This was due to the redirectUri being of type "SPA" which requires PKCE. Issue was resolved by changing the type to "Web"
