### ISSUE TITLE
MSAL inconsistently exports error types

### ISSUE THREAD

**Issue by JasonGore** [AzureAD/microsoft-authentication-library-for-js#4115]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.17.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

I'm writing error handling code around MSAL error constructs but am finding that the error types MSAL can throw outside of its boundaries are inconsistently exported. I'd like to tightly couple to them wherever possible in order to make sure we are properly addressing, identifying and adapting to MSAL errors now and over time. This is easy with some error types like `BrowserAuthError` of which `msal-browser` exports both the class and error codes. However, with other error types sometimes only the class is exported (`InteractionRequiredAuthError`), and for some error types, nothing is exported at all (`ServerError` , `ClientAuthError`).
 
It seems like any error that can be thrown outside of MSAL's boundary should have supporting types. Right now we've having to loosely couple based on error codes and I know for certain we're missing and not properly identifying all possible error types. Thanks!

### MSAL Configuration

```javascript
n/a (library types export issue)
```

### Relevant Code Snippets

```javascript
n/a (library types export issue)
```

### Reproduction Steps

View exports from `msal-browser` and/or try to access error classes and types in consuming software

### Expected Behavior

Any error type that MSAL can throw outside of its boundaries should be exported by MSAL.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Other

### Source

Internal (Microsoft)

**Comment by jasonnutter** [comment]
Thanks @JasonGore. You are probably right that we should be exporting any error classes we throw. Most of these errors come from [msal-common](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/src/index.ts#L80-L85), although not all of them [are re-exported](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/src/index.ts#L49-L52). We'd welcome a PR that exports any error classes that are not currently exported from MSAL Browser, thanks!
