### ISSUE TITLE
@azure/msal-browser not requesting user consent from app registrations api permissions

### ISSUE THREAD

**Issue by christiankaseburg** [AzureAD/microsoft-authentication-library-for-js#4116]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.16.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.1

### Description

When users sign into the client application they are directed through the login redirect flow. Once authenticated the user will be prompted to consent to the application required permissions, which only list the User.Read scope and none of the API permissions listed in the app registration for the client app. I have configured permissions for my client application through the app registration on the azure portal, but these permissions are not showing up on the consent screen. I have read through the documentation and have not found the source to require the API permissions from the application registration on the portal. Do I need to specify in my config or login request the same permissions I have set for my applications registration on the portal or can I modify my config to include these automatically without requiring me to change code to add/remove API permissions for my application?

### Error Message

InteractionRequiredAuthError: invalid_grant: AADSTS65001: The user or administrator has not consented to use the application with ID '{CLIENT_APP_ID}' named '{APP_NAME_FROM_PORTAL}'. Send an interactive authorization request for this user and resource.

### Msal Logs

InteractionRequiredAuthError: invalid_grant: AADSTS65001: The user or administrator has not consented to use the application with ID '{CLIENT_APP_ID}' named '{APP_NAME_FROM_PORTAL}'. Send an interactive authorization request for this user and resource.

### MSAL Configuration

```javascript
// Blurred out authority, clientId, and URIS
const msalConfig: Configuration = {
	auth: {
		authority: "https://login.microsoftonline.com/{TENANT ID}",
		clientId: "{CLIENT_APP_ID}",
		redirectUri: "{REDIRECT_URI_FROM_APP_REG}",
		postLogoutRedirectUri: "{REDIRECT_URI_FROM_APP_REG}"
	}
}

const msalInstance = new PublicClientApplication(msalConfig)
```

### Relevant Code Snippets

```javascript
I believe that I am missing some extra configuration to include the API permissions I have set for my applications registration on the portal.

// I believe I am missing something here with the MsalAuthenticationTemplate for application scopes
<MsalAuthenticationTemplate interactionType={ InteractionType.Redirect }>
   <AppRouter />
</MsalAuthenticationTemplate>
```

### Reproduction Steps

1. Sign into React application.
2. Make Request to web API and receive consent error.

### Expected Behavior

1. Sign into React application.
2. Make request and not get consent error.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari

### Source

External (Customer)

**Comment by christiankaseburg** [comment]
I fixed this by setting the scopes to .default.

```<MsalAuthenticationTemplate interactionType={ InteractionType.Redirect }>
   <AppRouter />
</MsalAuthenticationTemplate>```

**Comment by jasonnutter** [comment]
@christiankaseburg Yes, you will need to also provide those scopes at runtime to MSAL, in addition to configuring them in the portal. Closing.
