### ISSUE TITLE
msal version as property

### ISSUE THREAD

**Issue by PetrSnobelt** [AzureAD/microsoft-authentication-library-for-js#4122]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

Not Applicable

### Description

Hello, 
for telemetry purposes, it would be nice if MSAL can report its version so we can send it to telemetry etc.

something like `msal.varsion` should be enough.

Thx

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
Thanks for the suggestion. This just needed to be exported, the PR linked will address this.
