### ISSUE TITLE
Tabbing flow on login form is email to forgot password then password field

### ISSUE THREAD

**Issue by amrit-moomie** [AzureAD/microsoft-authentication-library-for-js#4125]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

1.3.0

### Wrapper Library

MSAL Node Extensions (@azure/msal-node-extensions)

### Wrapper Library Version

none

### Description

I am running Azure B2C login in an electron app. On the login window when you are in username/email field, navigating using the `tab` button on the keyboard will take you to forgot password link. So the flow is 

> email > forgot password >  password > sign button  

Should be 

>  email> password > sign button > forgot password

### Identity Provider

Azure B2C Basic Policy

### Source

External (Customer)

**Comment by tnorling** [comment]
@amrit-moomie MSAL is not responsible for the login UI. This is a question for the B2C service, you can file a ticket with them by [following these directions](https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options)
