### ISSUE TITLE
MSAL.js does not work with IE11.

### ISSUE THREAD

**Issue by sunrawat** [AzureAD/microsoft-authentication-library-for-js#413]
Even Updated version is not supported.

https://cloud.githubusercontent.com/assets/13203188/25239637/d1872fb4-25f0-11e7-9748-6fc91586d871.png

**Comment by nehaagrawal** [comment]
@sunrawat  Please don't remove our template while creating an issue. This helps us get more details about the issue so that we can support you better.

**Comment by sunrawat** [comment]
I am using loginRedirect and latest version of msal by installing 
npm install msal for my angular 6 project.

**Comment by navyasric** [comment]
@sunrawat  Are you using msal-angular library or msal.js library?

**Comment by taivu** [comment]
related: #414 

seems like #414 isnt labeled with bug, so i thought I'd reference it here to help things move along.

**Comment by navyasric** [comment]
As mentioned above this is related to #414. Closing this as duplicate.
