### ISSUE TITLE
IOS Safari - redirects user to login page, when opens in new tab or new window. even in safari browser

### ISSUE THREAD

**Issue by faiyazAbdul** [AzureAD/microsoft-authentication-library-for-js#4134]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

Not Applicable

### Wrapper Library Version

Not Applicable

### Description

From IOS mobile APP,  we need to navigate to SPA ( Web App in reactJs ) for few functionalities,  but each time we navigate it redirect users to login page. ( which gives bad user experience ).

In safari browser also, if open SPA in new tab or new window, if we already loggedIn in one of the Tab or window.
it does not fetch accessToken, it redirects user to login page.

looks like acquireTokenSilent and acquireTokenRedirect ( without asking credentials ) fails in safari. 

### Error Message

Auth Error.

### MSAL Configuration

```javascript
{
  auth: {
    clientId: config.clientId,
    authority: `${config.azureAuthorityUrl}/${signupSignin}`,
    knownAuthorities: [
      `${config.azureAuthorityUrl}/${signupSignin}`,
      `${config.azureAuthorityUrl}/${passwordChange}`,
      `${config.azureAuthorityUrl}/${emailChange}`,
      `${config.azureAuthorityUrl}/${passwordReset}`,
      `${config.azureAuthorityUrl}/${phonePasswordReset}`
    ],
    redirectUri: window.location.origin,
    scope: ['read', 'offline_access', config.readScope],
    prompt: 'login',
    postLogoutRedirectUri: config.brochureUrl,
    cache: {
      storeAuthStateInCookie: true, 
  },
    navigateToLoginRequestUrl:false
  }
};
```

### Relevant Code Snippets

```javascript
var account = await azureService.msalInstance.getAllAccounts()[0];
  var request = {
    scopes: [config.readScope],
    account: account.length ? account[0] : undefined
  };
// if there is no account calling acquireTokenRedirect()
  if(!request.account) {
    return azureService.msalInstance.acquireTokenRedirect(request);
  } 
  try {
    if(request.account){
      var response = await azureService.msalInstance.acquireTokenSilent(request);
      return response.accessToken;
    }
  } catch (error){
    var request = {
      scopes: [config.readScope],
    };
      console.log("error from get accessToken" + error)
      return azureService.msalInstance.acquireTokenRedirect(request);
  }
```

### Reproduction Steps

1.  after login in successfully, try to open the same app in next tab or in next window. in **safari**

### Expected Behavior

It should auto login user, and  navigate to respective page. Should not ask user for credentials

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Safari

### Source

External (Customer)

**Comment by tnorling** [comment]
@faiyazAbdul Cache location defaults to `sessionStorage` if not specified otherwise. Sessionstorage is not shared across tabs. Setting your cache location to `localStorage` instead will likely resolve this. Try that out and let me know.

Docs you may find helpful:
1. [Configuration Options](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/configuration.md)
2. [Caching Options](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/caching.md)

**Comment by abdulfaiyaz** [comment]
Hi @tnorling,
Does it have any security issues if we changed it to local storage from session. like it will be less secure or anything like that.

**Comment by sameerag** [comment]
@abdulfaiyaz It is more about access. `sessionStorage` is limited to a `browser session`, i.e., you cannot access `sessionStorage` data across tabs. `localStorage` however is limited to the same domain., i.e., the page `https://localhost:3000` cannot access `https://localhost:4000` or `https://mydomain.com` cannot access `https://yourdomain.com`.

The choice between these storages depends on your use case. More info about localStorage can be found [here](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage).
