### ISSUE TITLE
Sign in flow does not complete when running MSAL 2.0 in iframe

### ISSUE THREAD

**Issue by danspano** [AzureAD/microsoft-authentication-library-for-js#4138]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.16.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.2

### Description

I am building an Angular based SPA using MSAL-angular 2.0 and integrating with an Azure B2C custom policy.

I have been able to integrate several policies, including sign up, sign in, forgot password, etc. without any issue as long as the angular application is running in it's own browser window.

However, we have a requirement to use 'journey framing' to perform a sign in when this application is loaded in an iframe. Unfortunately, whenever the application is loaded in an iframe, MSAL triggers a sign in flow, completes the B2C portion, but after returning to the SPA, MSAL fails to complete the sign in flow (session storage shows interaction_in_progress and URL bar contains B2C return values).

There is no error output in console or any warning to suggest why MSAL will not proceed to complete the flow using the values passed in the return URL from B2C. This works completely fine and completes the flow if not running in an iframe.

I have noted the requirements and information in this support article: https://docs.microsoft.com/en-us/azure/active-directory-b2c/embedded-login?pivots=b2c-custom-policy

The article does state that "Running MSAL 2.0 in an iframe is not currently supported.". Does this mean that the issue I am observing is considered normal because MSAL is currently not designed to handle this use case? If so, is there any workaround at this stage?

Thanks

### MSAL Configuration

```javascript
{
    auth: {
      clientId: config.clientId,
      authority: config.signInAuthority,
      redirectUri: "/loading",
      postLogoutRedirectUri: "/",
      knownAuthorities: [config.authorityDomain]
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE,
    },
    system: {
      allowRedirectInIframe: true,
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Verbose,
        piiLoggingEnabled: true
      }
    }
}
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by tnorling** [comment]
@danspano Can you please share the code you are using to login and verbose level logs? Given that the url contains the response hash and sessionStorage shows the interaction in progress, it sounds like `handleRedirectObservable` isn't being called when run in the iframe, for whatever reason. Can you please share how your app is handling the redirect?

**Comment by danspano** [comment]
Hi @tnorling, thanks for your response. I am currently using an MsalGuard on my route which is triggering the login using my sign in policy.

Prior to that I also tried triggering the login flow manually with a simple userFlowRequest object:
`{
      scopes: ["openid", "offline_access", "<removed>/transaction.limited"],
      redirectStartPage: "/loading",
      authority: this.b2cConfig.signInAuthority
 }`

Then passing it into the MsalService loginRedirect method:
`this.authService.loginRedirect(userFlowRequest);`

Then, on redirect back, I am listening to the msalBroadcast
`    this.msalBroadcastService.msalSubject$
    .pipe(
      filter((msg: EventMessage) => msg.eventType === EventType.LOGIN_SUCCESS || msg.eventType === EventType.LOGIN_FAILURE),
    )
    .subscribe((result: EventMessage) => { 
 
      let payload: IdTokenClaims = <AuthenticationResult>result.payload;

}`

I have also listened to the other events, such as AcquireTokenSuccess etc. But none of these fire when the app is inside of an iframe. Only handleRedirectEnd, and if I check the authService, there is no account set. Correction to my previous post: It does appear to remove the local storage but does not remove the hash and subsequent values from the URL inside the iframe.

@azure/msal-angular@2.0.2 : Verbose - MsalRedirectComponent activated
@azure/msal-browser@2.16.1 : Info - Emitting event: msal:handleRedirectStart
@azure/msal-browser@2.16.1 : Verbose - Emitting event to callback 2ec2e34f-62ea-4f1d-a826-6900725b6534: msal:handleRedirectStart
@azure/msal-angular@2.0.2 : Verbose - BroadcastService - msal:handleRedirectStart results in setting inProgress to handleRedirect
@azure/msal-browser@2.16.1 : Verbose - handleRedirectPromise called
@azure/msal-browser@2.16.1 : Verbose - getAllAccounts called
@azure/msal-browser@2.16.1 : Verbose - handleRedirectPromise has been called for the first time, storing the promise
@azure/msal-browser@2.16.1 : Verbose - getRedirectResponseHash called
@azure/msal-browser@2.16.1 : Verbose - Hash contains known properties, returning response hash
@azure/msal-browser@2.16.1 : Verbose - validateAndExtractStateFromHash called
@azure/msal-browser@2.16.1 : Verbose - Returning state from hash
@azure/msal-browser@2.16.1 : Verbose - State extracted from hash
@azure/msal-browser@2.16.1 : Info - Emitting event: msal:handleRedirectEnd
@azure/msal-browser@2.16.1 : Verbose - Emitting event to callback 2ec2e34f-62ea-4f1d-a826-6900725b6534: msal:handleRedirectEnd
[Logging the event object] {eventType: 'msal:handleRedirectEnd', interactionType: 'redirect', payload: null, error: null, timestamp: 1633557592139}error: nulleventType: "msal:handleRedirectEnd"interactionType: "redirect"payload: nulltimestamp: 1633557592139
[Checking the account object] redirect ended without an account
[Checking the presence of a token]  redirect ended without an access token
@azure/msal-angular@2.0.2 : Verbose - BroadcastService - msal:handleRedirectEnd results in setting inProgress to none

There are no further msal events. However, if this SPA is loaded in its own tab/window, it will continue on after redirecting back and create an Auth code client, fetch the token and fire an msal:acquireTokenSuccess event, and an account will be set in the MsalService, which leads me to believe something about the iframe scenario is not supported here.

**Comment by tnorling** [comment]
Thanks. What happens if you set `navigateToLoginRequestUrl: false`? Based on the logs I suspect it's getting stuck on [this line](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/4ad87404f1648cbaa455fdfbc1a6c76030805368/lib/msal-browser/src/interaction_client/RedirectClient.ts#L113), setting that config value should make it handle the hash on the line above. I'll need to update that line to also check if `allowRedirectInIframe` was set to true, but it would be great to get confirmation that this is the only thing blocking.

**Comment by danspano** [comment]
@tnorling  - Thank you so much for this suggestion. I would never have known that this config was related to this issue. I have just tested it and I am now getting the loginSuccess event and it appears to be completing the flow now.

I have added some additional logic to handle the redirection which was disabled by this config change, it all seems to be working. The only thing I found strange was that after the login success fires, I seem to get an MSAL guard warning and cannot directly navigate to a guarded route using the angular router, MSAL guard complains that I am trying to set the redirectUri to a guarded page, even though this is after the login completed. I have just replaced MsalGuard with my own custom authentication guard and this is working fine.

This has resolved the blocker. I will look out for the fix in future and eventually remove the workaround.

Thanks again 👍

**Comment by tnorling** [comment]
@danspano Thanks for confirming! Looks like there's another place we need update to allow redirects in iframes, [we made a note but never implemented it](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/0be7700e5f1b0e83ade9df48327babd33cc9533f/lib/msal-angular/src/msal.guard.ts#L111). I'll reopen this issue until the work is complete, merging the linked PR will close.
