### ISSUE TITLE
Provide external token storage option

### ISSUE THREAD

**Issue by TheJVaughan** [AzureAD/microsoft-authentication-library-for-js#4141]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular), MSAL React (@azure/msal-react), MSAL Node Extensions (@azure/msal-node-extensions)

### Description

Local storage is insecure, session storage has SSO issues and secure cookies are not available to Javascript. A more secure option, which some other vendors libraries offer, is to use an API to store the token within a secure cookie, or other backend storage.

The access_token remains in memory, but the refresh_token is posted to an API and stored in a secure cookie and is obtained from the API when required.

Please provide an interface to support this within MSAL.

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@TheJVaughan Thanks for filing this. We are aware of the desire for applications to store tokens in locations other than local storage or session storage, and will take this into consideration. Note, that unfortunately this will likely require a breaking change in the library to properly support, and thus will most likely not be available until v3 (timing TBD).

Note, that we believe that local storage and session storage are secure if applications do not have XSS (or similar) vulnerabilities, and thus recommend all applications follow best practices for securing their applications from XSS and similar attack vectors. 

Applications who do not wish to store tokens in local or session storage can use the `MemoryStorage` option, or leverage a server-side SDK such as MSAL Node or MSAL.net.

**Comment by sameerag** [comment]
Tracking with #1588
