### ISSUE TITLE
How do I integrated Silent Sign on flow correctly and verify it is working? 

### ISSUE THREAD

**Issue by Shivam60** [AzureAD/microsoft-authentication-library-for-js#4147]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.18.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.1.0

### Description

I have a test URL for a microsoft webapp where I deploy my webapp.

Currently I am noticing that I have to click sign in on it then it redirects me to login.microsoftonline.com, there it does not asks me any credentials and just redirects me back to my site with a token.

I am expecting that if use `ssoSilent` I should  see an iframe being created and my user getting logged in without any redirection.

With this [PR ](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/4123) which merged I am also expecting  not to pass any user details

1. Is the above expectation correct ?

2. Currently I am just deleting my session and local storage cookies and seeing if the  `ssoSilent`. is successful or not. Is this correct and is there a better approach ?

### Relevant Code Snippets

```javascript
`
 if (this.props.msalContext.instance.getAllAccounts()[0]) {
// get token
}
else{
            this.props.msalContext.instance
                .ssoSilent(loginRequest)
                .then(token => {
                 // do stuff                  
                })
                .catch(err => {
                // do stuff
                });
}
`
```

### Source

Internal (Microsoft)

**Comment by sameerag** [comment]
@Shivam60 
> Currently I am noticing that I have to click sign in on it then it redirects me to login.microsoftonline.com, there it does not asks me any credentials and just redirects me back to my site with a token.

The redirection happens when there is no token in MSAL Cache. When your app requests a token, msal first tries to fetch a token from the cache, and if it isn't available, calls the server to check for a session and fetch the token silently. The APIs `ssoSilent` or `acquireTokenSilent` create a iframe for the redirection and fetch the tokens if there is a server session. 

Can you please share your `loginRequest` content? There may be prompt value set which could cause the redirect display than create a silent iframe.

**Comment by sameerag** [comment]
@Shivam60 Are you logging in with an MSA user? Are you passing any login_hint?

**Comment by Shivam60** [comment]
No its AAD and i thought `login_hint` is not required

**Comment by Shivam60** [comment]
@sameerag 
This is my login request object
```
loginRequest = {
    scopes: ["openid", "profile"],
    // We use additional scopes so that when we request token for this scope it can be silent else it needs to be interactive
    extraScopesToConsent: ["some extra scope here"],
    extraQueryParameters: {
        tenant: "",
    },
};
```

**Comment by Shivam60** [comment]
just synced with @pkanher617 
It seems that with MSA I am able to SSO however with AAD it is not working.

**Comment by jasonnutter** [comment]
> just synced with @pkanher617 
> It seems that with MSA I am able to SSO however with AAD it is not working.
> 
> 
> 

Is this with your @microsoft.com corp account? Are you able to reproduce this with an aad account from a test user/tenant?

**Comment by Shivam60** [comment]
Yes that is Microsoft account. 
On my test app id/client id test account is able to SSO.

On my test account corp is not able to SSO however login works
Is that expected?

**Comment by jasonnutter** [comment]
> Yes that is Microsoft account. On my test app id/client id test account is able to SSO.
> 
> On my test account corp is not able to SSO however login works Is that expected?

Yes, we have observed that @microsoft.com corp accounts may not be able to silently SSO, especially if a login_hint or sid is not used.

**Comment by Shivam60** [comment]
Hey @jasonnutter one question

What is the recommended flow of integrating SSoSlient.

As of now my flow is 
App mounts -> see if user account is there (`this.props.msalContext.instance.getAllAccounts()[0]`) -> if it is there i `acquireTokenSilently` else I SSOSilenty

Now problem is if i log out, my App again signs me in with SSOsilently. How do i avoid this?

**Comment by pkanher617** [comment]
Are you fully completing the logout flow by going to the logout page on login.microsoftonline.com?

**Comment by Shivam60** [comment]
Yes i think so. I use logoutRedirect method to logout

**Comment by Shivam60** [comment]
fired an incident for this as discussed with @pkanher617 
LMK if you want the id for tracking

**Comment by samuelkubai** [comment]
Closing this issue as it's been tracked on the incident raised. Feel free to re-open it if necessary.
