### ISSUE TITLE
Confirming Bearer Token validity on backend 

### ISSUE THREAD

**Issue by dankell** [AzureAD/microsoft-authentication-library-for-js#4148]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

We are currently using MSAL on our Vue.js front-end and using the returned Access Token as a Bearer Token to authenticate with our Hapi.js Backend server using JWT/JWKs

I am testing moving to MSAL v2 and am successfully (I think) retrieving an Access Token and attatching it to our back-end API calls. I can see the incoming token on the Back-End.

However the request are being rejected as "Invalid Token" errors. 

Has the method of authenticating Tokens on the back-end changed from MSAL 1.4 to 2.0?

### MSAL Configuration

```javascript
this.msalConfig = {
      auth: {
        clientId: 'redacted',
        authority: 'redacted',
        redirectUri: process.env.VUE_APP_REDIRECT,
        validateAuthority: true
      },
      cache: {
        cacheLocation: 'localStorage',
        storeAuthStateInCookie: true
      }
    }

this.loginRequest = {
      scopes: ['user.read']
    }
```

### Relevant Code Snippets

```javascript
Front-end: 
const tokenData = await this.getTokenPopup(this.loginRequest, resp.account)
  const accessToken = tokenData.accessToken
  Vue.prototype.$http.defaults.headers.common.Authorization = `Bearer ${accessToken}`

Backend (jsonwebtoken/jwks-rsa): 
register: async (server) => {
    await server.register(jwt)
    // Confirm that we are getting the correct PK
    const key = jwksRsa.hapiJwt2KeyAsync({
      cache: true,
      rateLimit: true,
      jwksRequestsPerMinute: 5,
      jwksUri: 'https://login.microsoftonline.com/common/discovery/keys'
    })

    console.log(key)

    server.auth.strategy('jwt', 'jwt', {
      // Get the complete decoded token, because we need info from the header (the kid)
      complete: true,
      // Dynamically provide a signing key based on the kid in the header and the singing keys provided by the JWKS endpoint.
      key: key,
      headerKey: 'authorization',
      tokenType: 'Bearer',
      validate: userCtrl.validate,
      verifyOptions: {
        algorithms: ['RS256'] // or HS256 RS256
      }
    })
    server.auth.default('jwt')
  }
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by derisen** [comment]
@dankell MSAL itself does not validate tokens, only acquires them (for the moment at least, in future msal-node will have support for this). Or are you suggesting that tokens obtained via MSAL v1 was working, but via MSAL v2 are not? 

I assume you are using passport.js on the backend? If so, I would recommend using [passport-azure-ad](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/maintenance/passport-azure-ad) for validating Azure AD / B2C tokens. See an example for this [here](https://github.com/Azure-Samples/ms-identity-javascript-tutorial/blob/main/3-Authorization-II/1-call-api/API/index.js). A less ideal option would be validating them manually, see an example for this [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-node-samples/ExpressTestApp/src/TokenValidator.ts). 

Regardless, for this particular error, we should try to get more detail on why they are deemed invalid. Can you turn on detailed error logs for passport.js?

**Comment by dankell** [comment]
We're not using Passport.js, but that may be the route that we need to go. 

Looking briefly at the manual example that looks similar to what we are doing - I'll hopefully have a deeper look later today and see where we differ.

**Comment by sameerag** [comment]
Thanks @dankell. Please keep us posted.

**Comment by dankell** [comment]
On first blush (trying to convert the Express.js typesctipt to the jwks-rsa javascript there was an obvious difference in URI, however switching to https://login.microsoftonline.com/common/discovery/v2.0/keys (which demonstratably returns a different result) we are still getting "Invalid Token"

I'm going to dig further and perhaps try and see if I can get passport.js to work on my backend example, but in the meantime I have a question about debuggint the tokens.

Am I right in thinking that the `kid/x5t` header values on the public keys above should match the equivalent header values in the tokens acquired by the client?

**Comment by sameerag** [comment]
cc @jo-arroyo @pkanher617 as they are working on validation of tokens.

**Comment by dankell** [comment]
I've been doing a bit more digging and have come up with two seperate strands.

1) There appears to be an issue with the `Hapi/jwks-rsa` implementation. Auth0 have a demo that works with Express.js, but their example for Hapi.js is out of date. If I try and apply the settings from the Express Example to Hapi then I get an "Invalid Token" error. I am persuing this with them.

2) The issue I am having that is pertinant here is which data from Azure should I use with the `jwks-rsa` implementation. The (working) Express implementation is here, but I cannot figure out the relevant values for: `jwksUri`, `audience`, or `issuer`
https://github.com/auth0/node-jwks-rsa/tree/59d47cadd63400319ef368299db2b58b70e8ffcd/examples/express-demo

**Comment by dankell** [comment]
`jwks-rsa issues` have now been resolved and I have a working example with Auth0 credentials. 

I am still trying to reverse engineer the appropriate credentials for `jwks-rsa` for use with an `msal` token if anyone can help

**Comment by dankell** [comment]
I've tried a different tack and have followed the attached StackOverflow question to try and find out where the issue lies. 
https://stackoverflow.com/questions/44330242/azure-ad-b2c-token-validation-does-not-work

I am still getting "Invalid Signature" errors when I use the following values

```
  const jwksUri = "https://login.microsoftonline.com/[ Directory (tenant) ID ]/discovery/v2.0/keys"
  const applicationId = '[ Application (client) ID ]'
  const issuerUri = 'https://login.microsoftonline.com/[ Directory (tenant) ID ]'
  token = [ token from MSAL frontend getTokenPopup.accessToken ]
```
From the example application I can see that I am retrieving a Signing Key that matches the `kid` of the passed accessToken.

However when this publicKey is passed to `jwt.verify` we error out with "Invalid Signature".

I am assuming that I have either missing/incorrectly set up on the back end, or on the Azure Portal. but I am running out of options.

**Comment by jo-arroyo** [comment]
@dankell Unfortunately, tokens from Microsoft Graph in particular are not be able to be validated, as they intended for Microsoft Graph only, and should not be opened in any way. Trying to validate it will generate an "Invalid Signature" error. Can you try registering a custom scope, and validating a token with only that scope, instead of `user.read`? 

[This thread](https://stackoverflow.com/questions/64946041/validating-a-microsoft-graph-jwt-token) may be helpful in explaining further.

**Comment by dankell** [comment]
> @dankell Unfortunately, tokens from Microsoft Graph in particular are not be able to be validated, as they intended for Microsoft Graph only, and should not be opened in any way. Trying to validate it will generate an "Invalid Signature" error. Can you try registering a custom scope, and validating a token with only that scope, instead of `user.read`?
> 
> [This thread](https://stackoverflow.com/questions/64946041/validating-a-microsoft-graph-jwt-token) may be helpful in explaining further.

OK. That certainly sounds like the issue that I am having. My current scope is "User.Read" as all I really care about from the MS side is that the user is a valid user in the company AD, which I can then cross-check the credentials against the application user list.

Will carve out some time to check out the reference and update

**Comment by dankell** [comment]
OK. I'm really missing something here. That thread certainly mirrors what I want to do, and indeed what we are doing with MSAL 1.0.

Adding a new scope, under "Expose an API" on Azure Portal ("custom") and using that in _getTokenPopup/getTokenSilent_ results in an error from the backend. The "user.read" scope however does allow me to grab an accesstoken. However that is "invalid" accoprding to the backend.

The token does however decode using [jwt.ms](jwt.ms) but the "aud" doesn't match my applicationID

All we want to be able to do is a) validate that the access token is valid and not been tampered with, and b) extract the userId to cross reference with out Backend system. (Further validation checks on the token would be nice have)

**Comment by hectormmg** [comment]
Hi @dankell , could you please show us what your token request configuration looks like? Also, what error is the backend returning when you add a new scope?

The "aud" claim will not match your application ID because the token you are requesting is for Microsoft Graph, not your own API. As stated before, you cannot validate a Microsoft Graph access token on a different resource. If you want to request a custom access token for your own API that you can validate, you must make that token request without the Graph scopes.

**Comment by dankell** [comment]
Here is the current Config objects for my front-end
```
    this.msalConfig = {
      auth: {
        clientId: [my Application (client) ID],
        authority: 'https://login.microsoftonline.com/[my domain]',
        redirectUri: 'http://localhost:8080/login',
        validateAuthority: true
      },
      cache: {
        cacheLocation: 'localStorage',
        storeAuthStateInCookie: true
      }
    }
    this.loginRequest = {
      // scopes: ['user.read']
      scopes: ['custom']
    }
    this.silentRequest = {
      // scopes: ['user.read']
      scopes: ['custom']
    }
```    
The error received is as follows
```
ServerError: invalid_client: AADSTS650053: The application 'Max Fordham MSAL 2.0' asked for scope 'custom' that doesn't exist on the resource [redacted resource ID]
```
That resource ID is not my Application ID, and matches the resource ID that I get when I put the token from `user.read` into jwt.ms. I'm assuming that is the MS Graph resource ID.

**Comment by hectormmg** [comment]
@dankell I think this is happening because you added a scope called "custom" under the Microsoft Graph resource in the Azure portal. You'd need to register the custom scope under your own custom API's permissions.

**Comment by dankell** [comment]
> @dankell I think this is happening because you added a scope called "custom" under the Microsoft Graph resource in the Azure portal. You'd need to register the custom scope under your own custom API's permissions.

Sorry for the silence. Had to switch to other tasks. I suspected that I might have been in the wrong place. Can you give me a pointer as to which section of the Azure Portal I need to register the scope in correctly.

**Comment by hectormmg** [comment]
@dankell you can create custom scopes in the "Expose an API" tab in your app registration. After you create it, go to "API Permissions" then "My APIs" and add the new scope to your app registration.
