### ISSUE TITLE
Access token empty but acquire token silently succeeded 

### ISSUE THREAD

**Issue by Oxyrus** [AzureAD/microsoft-authentication-library-for-js#4152]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.18.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.1.0

### Description

While attempting to obtain an access token, even though calling `acquireTokenSilent` succeeds, in the response the access token is an empty string:

![image](https://user-images.githubusercontent.com/11398826/136870622-ee2ec0ca-fe11-4dd1-b6da-a83d72f853df.png)

### MSAL Configuration

```javascript
export const msalConfig: Configuration = {
  auth: {
    clientId: "9227877d-fef2-44fc-883f-59149e9fd8ed",
    authority: "https://myauthority.b2clogin.com/mydomain.onmicrosoft.com/B2C_1_signupsigninflow",
    knownAuthorities: "myauthority.b2clogin.com",
    redirectUri: "/",
    postLogoutRedirectUri: "/",
    navigateToLoginRequestUrl: false,
  },
  cache: {
    cacheLocation: "sessionStorage",
    storeAuthStateInCookie: false,
  },
  system: {
    loggerOptions: {
      loggerCallback: (level: any, message: any, containsPii: any) => {
        if (containsPii) {
          return;
        }
        switch (level) {
          case LogLevel.Error:
            console.error(message);
            return;
          case LogLevel.Info:
            console.info(message);
            return;
          case LogLevel.Verbose:
            console.debug(message);
            return;
          case LogLevel.Warning:
            console.warn(message);
            return;
          default:
            return;
        }
      },
    },
  },
};

export const loginRequest: PopupRequest = {
  scopes: [
    "openid",
    "https://myauthority.b2clogin.com/Server.Access",
  ],
};
```

### Relevant Code Snippets

```javascript
const Home = () => {
  const { instance, accounts, inProgress } = useMsal();
  const account = useAccount(accounts[0] || undefined);

  useEffect(() => {
    if (account && inProgress === InteractionStatus.None) {
      instance
        .acquireTokenSilent({
          account: accounts[0],
          scopes: [...loginRequest.scopes],
        })
        .then((response) => {
          // This succeeds but the access token is empty
          console.log("silent token acquired", response);
        })
        .catch((error) => {
          // This never gets called
          console.log("silent token acquisition failed", error);
        });
    }
  });
 // ...
}
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by sameerag** [comment]
@Oxyrus Can you confirm you have granted admin consent to scope: "https://myauthority.b2clogin.com/Server.Access" in your SPA's app registration, and if not, can you do that and update us?

**Comment by Oxyrus** [comment]
@sameerag this is how my API permission looks like, is it correct?

![image](https://user-images.githubusercontent.com/11398826/136962940-65d478c2-7162-4e59-91c9-12141a01b31c.png)

Those were the settings used during my tests.

**Comment by sameerag** [comment]
@Oxyrus I think mixing multiple scopes is what is causing the issue here. Please read the guidance [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/resources-and-scopes.md) and let me know if it is helpful.

**Comment by Oxyrus** [comment]
@sameerag I tried using just one scope (`openid` and `https://myauthority.b2clogin.com/Server.Access`) and in both scenarios the access token returned was an empty string.

i.e.

```ts
export const loginRequest: PopupRequest = {
  scopes: ["openid"],
};
```

![image](https://user-images.githubusercontent.com/11398826/137002162-3a48d508-4c0d-4d56-b2ed-e5999bdbab03.png)

**Comment by derisen** [comment]
@Oxyrus unlike AAD, B2C does not issue an MS Graph access token (to be used with the [userinfo](https://docs.microsoft.com/en-us/azure/active-directory/develop/userinfo) endpoint) when the user first signs in, but MSAL v2 expects this access token by default, thus the empty string for the `accessToken` field in the response. 

A workaround for this is illustrated in a sample [here](https://github.com/Azure-Samples/ms-identity-b2c-javascript-spa/blob/0af58afa62e8d045fe1fd6d9f2d1e49bfe5b7b41/App/authPopup.js#L115). That is, if the response returns an empty string in place of the access token, detect this and throw an `InteractionRequiredAuthError`, then handle the error with an interactive API like `acquireTokenPopup`. Let us know if that would not help with your issue.
