### ISSUE TITLE
ClientAuthError: multiple_matching_tokens error when cache kept many users

### ISSUE THREAD

**Issue by CrazyBaran** [AzureAD/microsoft-authentication-library-for-js#4158]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.3.2

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

We use msal-node on our nestjs application. We try to do on-behalf-of flow. We get from request access_token and pass it to 
`this.confidentialClientApplication.acquireTokenOnBehalfOf(access_token)`
We implement cachePlugin to kept cache in KeyVault. Cache is properly accessed, but randomly we get error:
ClientAuthError: multiple_matching_tokens: The cache contains multiple tokens satisfying the requirements. Call AcquireToken again providing more requirements such as authority or account..
We made walkaround and by getAccountByLocalId we fetch AccountInfo by oid from access_token and pass it if exist to:
OnBehalfOfRequest but from @azure/msal-node this class didn't had this field so we add this softly.
After this "hack" error didnt occur.
Should OnBehalfOfRequest had field for AccountInfo? Could we do it this way or there is some security breach here?

### Error Message

ClientAuthError: multiple_matching_tokens: The cache contains multiple tokens satisfying the requirements. Call AcquireToken again providing more requirements such as authority or account..
at ClientAuthError.AuthError [as constructor] (/app/node_modules/@azure/msal-common/dist/index.cjs.js:477:24)
at new ClientAuthError (/app/node_modules/@azure/msal-common/dist/index.cjs.js:754:28)
at Function.ClientAuthError.createMultipleMatchingTokensInCacheError (/app/node_modules/@azure/msal-common/dist/index.cjs.js:849:16)
at OnBehalfOfClient.readAccessTokenFromCache (/app/node_modules/@azure/msal-common/dist/index.cjs.js:5808:35)
at OnBehalfOfClient.<anonymous> (/app/node_modules/@azure/msal-common/dist/index.cjs.js:5756:50)
at step (/app/node_modules/@azure/msal-common/dist/index.cjs.js:79:23)
at Object.next (/app/node_modules/@azure/msal-common/dist/index.cjs.js:60:53)
at /app/node_modules/@azure/msal-common/dist/index.cjs.js:53:71
at new Promise (<anonymous>)
at __awaiter (/app/node_modules/@azure/msal-common/dist/index.cjs.js:49:12)
at OnBehalfOfClient.getCachedAuthenticationResult (/app/node_modules/@azure/msal-common/dist/index.cjs.js:5751:16)
at OnBehalfOfClient.<anonymous> (/app/node_modules/@azure/msal-common/dist/index.cjs.js:5734:55)
at step (/app/node_modules/@azure/msal-common/dist/index.cjs.js:79:23)
at Object.next (/app/node_modules/@azure/msal-common/dist/index.cjs.js:60:53)
at /app/node_modules/@azure/msal-common/dist/index.cjs.js:53:71
at new Promise (<anonymous>)

### MSAL Configuration

```javascript
{
          auth: {
            clientId: 'our ClientId from config',
            authority: 'our Authority from config',
            clientSecret: 'our ClientSecret',
          },
          cache: {
            cachePlugin: cachePlugin,
          },
          system: {
            loggerOptions: {
              loggerCallback(loglevel, message, containsPii): void {
                switch (loglevel) {
                  case LogLevel.Error: {
                    logger.error(message);
                    break;
                  }
                  case LogLevel.Warning: {
                    logger.warn(message);
                    break;
                  }
                  case LogLevel.Info: {
                    logger.verbose(message);
                    break;
                  }
                  case LogLevel.Verbose: {
                    logger.debug(message);
                    break;
                  }
                  case LogLevel.Trace: {
                    logger.log(message);
                    break;
                  }
                }
              },
              piiLoggingEnabled: false,
              logLevel: LogLevel.Trace,
            },
          },
        }
```

### Relevant Code Snippets

```javascript
const oboRequest: OnBehalfOfRequest = {
      oboAssertion: accessToken,
      scopes: scopes,
      authority: 'our Authority from config',
    };

    const decodedToken = this.jwtService.decode(accessToken);
    const accountInfo = await this.confidentialClientApplication
      .getTokenCache()
      .getAccountByLocalId(decodedToken['oid']);

    if (accountInfo) {
      oboRequest['account'] = accountInfo;
    }

    let result: AuthenticationResult;
    try {
      result = await this.confidentialClientApplication.acquireTokenOnBehalfOf(
        oboRequest
      );
    } catch (error) {
      this.msOnBehalfOfAuthServiceLogger.error(error);
    }
```

### Reproduction Steps

Try to make multiple onBehalfOf for multiple users by access_token

### Expected Behavior

Cache should resolve proper cached item from access_token which is provided by oboAssertion or OnBehalfOfRequest class should had field AccountInfo

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Source

External (Customer)

**Comment by sameerag** [comment]
@CrazyBaran  `Account` is usually an artifact representing a user. On behalf of flow, even if it is made by a web server, since it is made on behalf of end user, has a user and is issued an `idToken`, hence will also have an account associated with token acquisition. 

Regarding the API interface, can you clarify if you are doing the following:

* Call `acquireTokenOnBehalfOf` and fetch tokens, the response has `account` as a param. Account info can also be fetched post acquiring a token by calling `getAccountBy*()` APIs
* For the subsequent calls, call `acquireTokenSilent()` which has the param for `AccountInfo`

**Comment by CrazyBaran** [comment]
@sameerag Our application kept cache to work onBehalfOf user even without interaction from user. On login to app with SSO we made on first turn always acquireTokenOnBehalfOf to had sure that tokens are new, so you mean we should didn't trigger acquireTokenOnBehalfOf but check if exist and then go with refresh? Rather than eagerly try to acquireToken on login?
For subsequent logic of course we use acquireTokenSilent.

**Comment by CrazyBaran** [comment]
Unfortunetly this didn't solve issue. To be more specific, we use singleton instance of `confidentialClientApplication` and right now we had case that in cache there is two accounts, third account try to make first time a OBO and we get multiple_matching_tokens error.

**Comment by jasonnutter** [comment]
@sameerag Is this potentially fixed by #4081?

**Comment by sameerag** [comment]
Possibly. Some tests have to be fixed but code changes are done and @CrazyBaran can test the branch meanwhile.

**Comment by sameerag** [comment]
Tracking this with #4486
