### ISSUE TITLE
MSAL v1 does not redirect back to loginRequestUrl when app is in iframe (B2C embedded login)

### ISSUE THREAD

**Issue by fhlbdvt** [AzureAD/microsoft-authentication-library-for-js#4159]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

1.4.4

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

1.1.2

### Description

When I am running a angular app inside an iframe, the requested URL is not set after authentication is completed, instead the page stays at the Redirect URL

### Error Message

No error

### Msal Logs

 Thu, 14 Oct 2021 22:26:43 GMT:advances-web-1.4.11-Verbose GetResponseState has been called
​ Thu, 14 Oct 2021 22:26:43 GMT:advances-web-1.4.11-Verbose Hash contains state. Creating stateInfo object
​ Thu, 14 Oct 2021 22:26:43 GMT:advances-web-1.4.11-Verbose State matches cached state, setting requestType to login
​ Thu, 14 Oct 2021 22:26:43 GMT:advances-web-1.4.11-Info Returned from redirect url
​ Thu, 14 Oct 2021 22:26:43 GMT:advances-web-1.4.11-Verbose HandleRedirectAuthenticationResponse has been called
​ Thu, 14 Oct 2021 22:26:43 GMT:advances-web-1.4.11-Verbose Window.location.hash cleared
​ Thu, 14 Oct 2021 22:26:43 GMT:advances-web-1.4.11-Verbose GetResponseState has been called
​ Thu, 14 Oct 2021 22:26:43 GMT:advances-web-1.4.11-Verbose Hash contains state. Creating stateInfo object
​ Thu, 14 Oct 2021 22:26:43 GMT:advances-web-1.4.11-Verbose State matches cached state, setting requestType to login
​ Thu, 14 Oct 2021 22:26:43 GMT:advances-web-1.4.11-Verbose Window.parent is equal to window, not in popup or iframe. Navigation to login request url after login turned on
​ Thu, 14 Oct 2021 22:26:43 GMT:advances-web-1.4.11-Verbose Valid login request url obtained from cache
​ Thu, 14 Oct 2021 22:26:43 GMT:advances-web-1.4.11-Verbose Current url is not login request url, navigating
​

### MSAL Configuration

```javascript
standard configuration
```

### Relevant Code Snippets

```javascript
UserAgentApplication.prototype.handleRedirectAuthenticationResponse
```

### Reproduction Steps

1. Create an angular application uses this library and assign a client id
2. Load this app into a browser, and trigger an authentication and loaded
3. once loaded, click a link on this app and it loads a Requested URL into an iframe
4. The angular application associated with the Requested URL (different client id) is loaded into an iframe
5. The iframe's angular app is also triggered authentication
6. the iframe content is displayed for Redirect URL of the iframe's angular app

### Expected Behavior

Step 6 above should display the content for the Requested URL instead of Redirect URL

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

External (Customer)

**Comment by sameerag** [comment]
@fhlbdvt Can you please share your configuration details? cc @jasonnutter 

On a side note: Can you please consider moving to the latest msal-angular [version 2.x](https://www.npmjs.com/package/@azure/msal-angular)? Most of these scenarios are addressed in the latest version and in case there is still an issue we can work on addressing it.

We are not supporting new features on msal 1.x and hence the request.

**Comment by fhlbdvt** [comment]
Here is the my configuration file:


```
import { Configuration } from 'msal';
import { MsalAngularConfiguration } from '@azure/msal-angular';
import { environment } from '@AppEnvironment/environment';
// this checks if the app is running on IE
export const isIE = window.navigator.userAgent.indexOf('MSIE ') > -1 || window.navigator.userAgent.indexOf('Trident/') > -1;

/** =================== REGIONS ====================
 * 1) B2C policies and user flows
 * 2) Web API configuration parameters
 * 3) Authentication configuration parameters
 * 4) MSAL-Angular specific configuration parameters
 * =================================================
 */
// #region 1) B2C policies and user flows
/**
 * Enter here the user flows and custom policies for your B2C application,
 * To learn more about user flows, visit https://docs.microsoft.com/en-us/azure/active-directory-b2c/user-flow-overview
 * To learn more about custom policies, visit https://docs.microsoft.com/en-us/azure/active-directory-b2c/custom-policy-overview
 */
export const b2cPolicies = {
    names: {
        signUpSignIn: environment.signUpSignInPolicy,
        resetPassword: environment.resetPasswordPolicy,
        changePassword: environment.changePasswordPolicy,
        editAuthenticatorMFA: environment.editAuthenticatorMFAPolicy,
        editPhoneMFA: environment.editPhoneMFAPolicy,
        editProfile: environment.editProfilePolicy,
        editSignInEmail: environment.editSignInEmailPolicy,
        signUp: environment.signUpPolicy,
        switchAccessProfile: environment.switchAccessProfilePolicy,
    },
    authorities: {
        signUpSignIn: {
            authority: environment.b2cURL + environment.signUpSignInPolicy
        },
        resetPassword: {
            authority: environment.b2cURL + environment.resetPasswordPolicy
        },
        changePassowrd: {
            authority: environment.b2cURL + environment.changePasswordPolicy
        },
        editAuthenticatorMFA: {
            authority: environment.b2cURL + environment.editAuthenticatorMFAPolicy
        },
        editPhoneMFA: {
            authority: environment.b2cURL + environment.editPhoneMFAPolicy
        },
        editProfile: {
            authority: environment.b2cURL + environment.editProfilePolicy
        },
        editSignInEmail: {
            authority: environment.b2cURL + environment.editSignInEmailPolicy
        },
        signUp: {
            authority: environment.b2cURL + environment.signUpPolicy
        },
        switchAccessProfile: {
            authority: environment.b2cURL + environment.switchAccessProfilePolicy
        }
    }
};
// #endregion


// #region 2) Web API Configuration
/**
 * Enter here the coordinates of your Web API and scopes for access token request
 * The current application coordinates were pre-registered in a B2C tenant.
 */
export const apiConfig: { b2cScopes: string[]; webApi: string } = {
    b2cScopes: environment.b2cScopes,
    webApi: environment.apiEndpoint.singleSignOn
};
// #endregion



// #region 3) Authentication Configuration
/**
 * Config object to be passed to Msal on creation. For a full list of msal.js configuration parameters,
 * visit https://azuread.github.io/microsoft-authentication-library-for-js/docs/msal/modules/_configuration_.html
 */
export const msalConfig: Configuration = {
    auth: {
        clientId: environment.clientId,
        authority: b2cPolicies.authorities.signUpSignIn.authority,
        redirectUri: environment.redirectUri,
        postLogoutRedirectUri: environment.postLogoutRedirectUri,
        navigateToLoginRequestUrl: true,
        validateAuthority: false,
    },
    cache: {
        cacheLocation: 'sessionStorage',
        storeAuthStateInCookie: isIE, // Set this to 'true' to save cache in cookies to address trusted zones limitations in IE
    },
};

/**
 * Scopes you enter here will be consented once you authenticate. For a full list of available authentication parameters,
 * visit https://azuread.github.io/microsoft-authentication-library-for-js/docs/msal/modules/_authenticationparameters_.html
 */
export const loginRequest: { scopes: string[] } = {
    scopes: environment.loginRequestScopes,
};

// Scopes you enter will be used for the access token request for your web API
export const tokenRequest: { scopes: string[] } = {
    scopes: apiConfig.b2cScopes // i.e. [https://fhlbxb2c.onmicrosoft.com/helloapi/demo.read]
};
// #endregion



// #region 4) MSAL-Angular Configuration
// here you can define the coordinates and required permissions for your protected resources
export const protectedResourceMap: [string, string[]][] = [
    [apiConfig.webApi, apiConfig.b2cScopes]
    // i.e. [https://fhlbxb2chello.azurewebsites.net/hello, ['https://fhlbxb2c.onmicrosoft.com/helloapi/demo.read']]
];

/**
 * MSAL-Angular specific authentication parameters. For a full list of available options,
 * visit https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-angular#config-options-for-msal-initialization
 */
export const msalAngularConfig: MsalAngularConfiguration = {
    popUp: false,
    consentScopes: [
        ...loginRequest.scopes,
        ...tokenRequest.scopes,
    ],
    protectedResourceMap,     // API calls to these coordinates will activate MSALGuard
    extraQueryParameters: {}
};
// #endregion
function MSALConfigFactory(): Configuration {
    return msalConfig;
}

function MSALAngularConfigFactory(): MsalAngularConfiguration {
    return msalAngularConfig;
}

export { MSALAngularConfigFactory, MSALConfigFactory }
```

**Comment by fhlbdvt** [comment]
During my debugging session, here is what I've observed - when the code is running inside a outer frame, the if block for line 1065 is not executed due to `window.parent !== window` and because of that, the requested URL (`finalRedirectURL`) is not set.

![Screenshot-UserAgentApplication-js](https://user-images.githubusercontent.com/92555208/137497199-ddab0c4a-10d5-4248-b451-11d67b1beb75.png)

**Comment by fhlbdvt** [comment]
I am also thinking upgrading to msal 2.x but it also need to upgrade to later version of angular and it takes me sometime and I am on a time crunch at this moment.

**Comment by fhlbdvt** [comment]
Please let me know if you have any updates.

**Comment by jasonnutter** [comment]
Apologies for the delay. This is a bug, and a workaround for now is for your application to manually store the application's starting url before you invoke loginRedirect (in local storage, for example), and then when the redirect is processed, manually redirect the user back to that url.

**Comment by jasonnutter** [comment]
This would look something like this:

```javascript
const redirectStartPage = window.location.href;
localStorage.setItem("redirectStartPage", startingUrl);
msalInstance.loginRedirect();

// Iframe is navigate to b2c login page in iframe, then redirects back to your app

// When your app is loaded after redirecting to b2c
msalInstance.handleRedirectCallback((error, response) => {
  if (response) {
    const redirectStartPage = localStorage.getItem("redirectStartPage");
     window.location.href = redirectStartPage;
  }
});


```

**Comment by fhlbdvt** [comment]
I'll give it a try on the workaround

**Comment by tiennguyen1293** [comment]
I have the issue with `loginRedirect` and `loginPopup` when I implement it on Microsoft Teams Desktop App.

Please update if we have any updates.

Version:

"azure/@msal-browser": "^2.22.0",
"@azure/msal-react": "^1.3.0",

<img width="784" alt="image" src="https://user-images.githubusercontent.com/26110369/156329272-9b103158-f031-4153-b41f-d02661698bb9.png">

**Comment by jasonnutter** [comment]
@tiennguyen1293 Teams apps must leverage the Teams SDK to open a Teams dialog, and then perform loginRedirect inside that dialog. This sample demonstrates how to do that: https://github.com/pnp/teams-dev-samples/tree/main/samples/tab-sso/src/nodejs

If you have further questions, please open a separate issue, thanks!

**Comment by sameerag** [comment]
Closing this, provided workarounds in the above thread. As mentioned, please open a new issue if you have more questions.
