### ISSUE TITLE
MSAL Node OBO Flow docs should include instructions for setting redirect uri

### ISSUE THREAD

**Issue by samkyuseo** [AzureAD/microsoft-authentication-library-for-js#4161]
### Core Library

MSAL Node (@azure/msal-node)

### Wrapper Library

Not Applicable

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/on-behalf-of

### Description

After registering the web-app, tell the user to set redirect URI under web as 'http://localhost:3000/redirect'

**Comment by jasonnutter** [comment]
@samkyuseo Thanks, we'll look at fixing that doc accordingly.

**Comment by jasonnutter** [comment]
@hectormmg Can you please take a look at updating these docs when you get a chance?

**Comment by hectormmg** [comment]
The [Pull Request](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/4243) addressing this is ready
