### ISSUE TITLE
MSAL 2.0 Auth Code Flow with B2C custom policy, after password reset success, acquireTokenSilent fails, need to login user automatically.

### ISSUE THREAD

**Issue by abdulfaiyaza** [AzureAD/microsoft-authentication-library-for-js#4175]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

Not Applicable

### Wrapper Library Version

Not Applicable

### Description

Using MSAL 2.0 Auth Code Flow with B2C custom policy, after password reset success, acquireTokenSilent fails with **got passwordReset authority instead of signUp_SignIn authority**, **please provide correct authority.**
We need the user to loggedIN Automatically after password reset success. Is there any way i can handle this?

### MSAL Configuration

```javascript
{
  auth: {
    clientId: config.clientId,
    authority: `${config.azureAuthorityUrl}/${signupSignin}`,
    knownAuthorities: [
      `${config.azureAuthorityUrl}/${signupSignin}`,
      `${config.azureAuthorityUrl}/${passwordChange}`,
      `${config.azureAuthorityUrl}/${emailChange}`,
      `${config.azureAuthorityUrl}/${passwordReset}`,
      `${config.azureAuthorityUrl}/${phonePasswordReset}`
    ],
    redirectUri: window.location.origin,
    scope: ['read', 'offline_access', config.readScope],
    prompt: 'login',
    postLogoutRedirectUri: config.brochureUrl,
    cache: {
      storeAuthStateInCookie: true, 
  },
    navigateToLoginRequestUrl:false
  }
};
```

### Relevant Code Snippets

```javascript
var account = await azureService.msalInstance.getAllAccounts()[0];
  var request = {
    scopes: [config.readScope],
    account: account.length ? account[0] : undefined
  };
// Here we are getting account with password Reset authority, after successfully reseting the password. which fails in acquireTokenSilent().
  try {
    if(request.account){
      var response = await azureService.msalInstance.acquireTokenSilent(request);
      return response.accessToken;
    }
  } catch (error){
    var request = {
      scopes: [config.readScope],
    };
      console.log("error from get accessToken" + error)
      return azureService.msalInstance.acquireTokenRedirect(request);
  }
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@abdulfaiyaza When using the password reset policy, you need to logout after returning from the password reset flow, as demonstrated in this sample: https://github.com/Azure-Samples/ms-identity-javascript-tutorial/blob/main/1-Authentication/2-sign-in-b2c/App/authRedirect.js#L139

Alternatively, you can use the self-service password reset experience, as documented here: https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-password-reset-policy?pivots=b2c-custom-policy#self-service-password-reset-recommended
