### ISSUE TITLE
msal 1.3.3 - any service/system changes? 

### ISSUE THREAD

**Issue by diberry** [AzureAD/microsoft-authentication-library-for-js#4180]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

1.3.3

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

I've hit the redirect on unauthenticated user issue without changes to impact msal (that I know of). Any chance there was a service/system change in the response JSON that might affect this?  

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by jasonnutter** [comment]
@diberry I'm not sure I understand the issue you are having, can you please provide more details and an example of the code you are using the errors you are getting? Logs from MSAL would also be helpful, thanks!

**Comment by diberry** [comment]
@jasonnutter Thank you for your help. The code may not have been implemented in the best way, this is old code I'm maintaining. 


The two places in the code that were redirecting are now commented out (window.location.replace statements) to stop the redirect but that's just a symptom of something else - I'll turn on the logs and see what is happening:

```
export const msalApp = new UserAgentApplication({
    auth: {
        clientId: clientIdString,
        authority: authorityUri
    },
    cache: {
        cacheLocation: "localStorage"
    }
});
```

```
// used to log in user
export async function login(msalUserAgentApp) {
    try {
        await msalUserAgentApp.loginPopup();
    } catch (e) {
        //window.location.replace("/");
        console.log(`loginPopup crashed ${e}`)
    }
    let msft = await addMsftUser(msalUserAgentApp);
    
    return msalUserAgentApp.getAccount();
}
```

```
/// used to build API auth headers
export async function getAuthHeadersSilent(msalUserAgentApp) {
    let requestParams = {
        scopes: [clientIdString]
    };
    let token = null;
    try {
        token = await msalUserAgentApp.acquireTokenSilent(requestParams);
    } catch (e) {
        console.log(`msalUserAgentApp.acquireTokenSilent error ${JSON.stringify(e)}`)
    }

    if (token == null) {
        console.log(`msalUserAgentApp.acquireTokenSilent token is null`);
        //window.location.replace("/");
    } else {
        let headers = {
            headers: {
                "Content-type": "application/json",
                "Cache-Control": "no-store, no-cache, must-revalidate",
                "Pragma": "no-cache",
                "Authorization": "Bearer " + token.accessToken
            }
        }
        return headers;
    }
}
```

**Comment by diberry** [comment]
Not a service or SDK issue.
