### ISSUE TITLE
correlationId from token request is overridden

### ISSUE THREAD

**Issue by PetrSnobelt** [AzureAD/microsoft-authentication-library-for-js#4185]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.18.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

When I ask for a token and provide `correlationId`, this `correlationId` is overridden inside initializeBaseRequest method

you can see it in the following verbose logs - there is [correlation-Id] but later it is overridden by [cc4f6690-2464-4571-b74c-46fc0615094a]

Solution should be easy, just update line in 
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/0e1e832367ea0c78155217b9b99363268d20a9c7/lib/msal-browser/src/interaction_client/BaseInteractionClient.ts#L88
to `correlationId: request.correlationId ?? this.correlationId,`

But from perf perspective, it might be better to generate new GUID for correlationId only if it is not provided.

### Msal Logs

Fri Oct 22 2021 16:54:29 GMT+0200 (Středoevropský letní čas) '[Fri, 22 Oct 2021 14:54:29 GMT] : @azure/msal-browser@2.18.0 : Verbose - preflightBrowserEnvironmentCheck started'
authConfig.js:56 Fri Oct 22 2021 16:54:34 GMT+0200 (Středoevropský letní čas) '[Fri, 22 Oct 2021 14:54:34 GMT] : [correlation-Id] : @azure/msal-browser@2.18.0 : Verbose - acquireTokenSilent called'
authConfig.js:56 Fri Oct 22 2021 16:54:34 GMT+0200 (Středoevropský letní čas) '[Fri, 22 Oct 2021 14:54:34 GMT] : [correlation-Id] : @azure/msal-browser@2.18.0 : Verbose - acquireTokenSilent called for the first time, storing active request'
authConfig.js:56 Fri Oct 22 2021 16:56:40 GMT+0200 (Středoevropský letní čas) '[Fri, 22 Oct 2021 14:56:40 GMT] : [cc4f6690-2464-4571-b74c-46fc0615094a] : msal.js.browser@2.18.0 : Verbose - Initializing BaseAuthRequest'
authConfig.js:56 Fri Oct 22 2021 16:56:40 GMT+0200 (Středoevropský letní čas) '[Fri, 22 Oct 2021 14:56:40 GMT] : [cc4f6690-2464-4571-b74c-46fc0615094a] : msal.js.browser@2.18.0 : Verbose - Authentication Scheme set to "pop" as configured in Auth request'

### MSAL Configuration

```javascript
not relevant
```

### Relevant Code Snippets

```javascript
just ask for silent token request with 
`tokenRequest.correlationId = "correlation-Id";`
```

### Reproduction Steps

make silent token request with correlation Id

### Expected Behavior

if correlationId is passed as parameter it should be used.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

Internal (Microsoft)

**Comment by jasonnutter** [comment]
@PetrSnobelt Thanks, linked PR will fix.
