### ISSUE TITLE
Does MSAL library automatically retry for token renewal? Any event generated when retry is stopped?

### ISSUE THREAD

**Issue by pashvin** [AzureAD/microsoft-authentication-library-for-js#4187]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.17.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

NA

### Description

My application ask list of meetings using Graph API so UI shows loading animation and then request goes to graph which checks for token and if not valid ask to renew silently and once token renewed and data is received, then loading animation goes away and UI shows meeting list.

We know token expire in 24 hours and sometime require interactive renewal and sometime auto renewed using session.
But we got few report that token renewal fails (which is OK) but want to know if retry from MS library is still going on or stopped.

### MSAL Configuration

```javascript
his.msalauthService = new PublicClientApplication({
      auth: {
        clientId: this.getClientId(),
        redirectUri: window.location.origin + '/office365/login/redirect',
      },
      cache: {
        cacheLocation: 'localStorage',
        storeAuthStateInCookie: false, // set to true for IE 11
      },
      system: {
        iframeHashTimeout: 10000,
        loggerOptions: {...
```

### Relevant Code Snippets

```javascript
private async getAccessToken(): Promise<string> {
    let InteractionRequiredAuth = false;
    let result = await this.msalauthService.acquireTokenSilent({ scopes: this.tokenScope }).catch((reason) => {
      if (reason instanceof InteractionRequiredAuthError) {
        // MS may ask for interactive token renewal so keep that as info instead of error
        Logging.info('Microsoft Enterprise Account: Interaction required:');
        InteractionRequiredAuth = true;
        Logging.info(reason + '');
      } else {
        Logging.error('Microsoft Enterprise Account: ms token acquire failed:');
        Logging.error(reason);
      }
    });

    if (InteractionRequiredAuth) {
      if (!this.isInteractionInProgress) {
        this.isInteractionInProgress = true;
        // use aquiretoken popup instead of login popup to avoid
        // issue of poping login window every day.
        result = await this.msalauthService
          .acquireTokenPopup({ scopes: this.tokenScope })
          .catch((reason) => {
            Logging.error('Microsoft Enterprise Account: ms token interactive acquire failed:');
            Logging.error(reason);
          })
          .finally(() => {
            this.isInteractionInProgress = false;
          });
      } else {
        Logging.info('Microsoft Enterprise Account: previous interactive login in progress. avoiding duplicate popup');
      }
    }

    if (result && result.accessToken) {
      return result.accessToken;
    } else {
      Logging.error('Microsoft Enterprise Account: access token is not received');
    }
    return '';
  }
```

### Source

External (Customer)

**Comment by pashvin** [comment]
As you can see on following log, the 2nd last try has no info about if retry was successful or not and then it started new request after an hour and no response and no new request

"2021-10-20T17:21:24.330Z INFO App Microsoft Enterprise Account: loggerCallback:[Wed, 20 Oct 2021 17:21:24 GMT] : @azure/msal-browser@2.17.0 : Info - Emitting event: msal:acquireTokenStart ",
      "2021-10-20T17:21:24.373Z INFO App Microsoft Enterprise Account: loggerCallback:[Wed, 20 Oct 2021 17:21:24 GMT] : @azure/msal-browser@2.17.0 : Info - Emitting event: msal:acquireTokenSuccess ",
      "2021-10-20T17:39:06.099Z INFO App Microsoft Enterprise Account: loggerCallback:[Wed, 20 Oct 2021 17:39:06 GMT] : @azure/msal-browser@2.17.0 : Info - Emitting event: msal:acquireTokenFromNetworkStart ",
      "2021-10-20T18:34:06.097Z INFO App Microsoft Enterprise Account: loggerCallback:[Wed, 20 Oct 2021 18:34:06 GMT] : @azure/msal-browser@2.17.0 : Info - Emitting event: msal:acquireTokenFromNetworkStart ",
      "2021-10-20T19:29:51.126Z INFO App Microsoft Enterprise Account: loggerCallback:[Wed, 20 Oct 2021 19:29:51 GMT] : @azure/msal-browser@2.17.0 : Info - Emitting event: msal:acquireTokenFromNetworkStart ",
      "2021-10-20T20:25:06.010Z INFO App Microsoft Enterprise Account: loggerCallback:[Wed, 20 Oct 2021 20:25:06 GMT] : @azure/msal-browser@2.17.0 : Info - Emitting event: msal:acquireTokenFromNetworkStart ",
      "2021-10-20T21:20:06.057Z INFO App Microsoft Enterprise Account: loggerCallback:[Wed, 20 Oct 2021 21:20:06 GMT] : @azure/msal-browser@2.17.0 : Info - Emitting event: msal:acquireTokenFromNetworkStart ",
      "2021-10-20T22:15:51.192Z INFO App Microsoft Enterprise Account: loggerCallback:[Wed, 20 Oct 2021 22:15:51 GMT] : @azure/msal-browser@2.17.0 : Info - Emitting event: msal:acquireTokenFromNetworkStart ",
      "2021-10-20T23:49:52.174Z INFO App Microsoft Enterprise Account: loggerCallback:[Wed, 20 Oct 2021 23:49:52 GMT] : @azure/msal-browser@2.17.0 : Info - Emitting event: msal:acquireTokenFromNetworkStart ",
      "2021-10-20T23:49:53.398Z INFO App Microsoft Enterprise Account: loggerCallback:[Wed, 20 Oct 2021 23:49:53 GMT] : @azure/msal-browser@2.17.0 : Info - Emitting event: msal:acquireTokenFailure ",
      "2021-10-20T23:49:53.399Z ERROR App Microsoft Enterprise Account: ms token acquire failed: ",
      "2021-10-20T23:49:53.399Z ERROR App Microsoft Enterprise Account: access token is not received ",
      "2021-10-20T23:50:18.091Z INFO App Microsoft Enterprise Account: loggerCallback:[Wed, 20 Oct 2021 23:50:18 GMT] : @azure/msal-browser@2.17.0 : Info - Emitting event: msal:acquireTokenFromNetworkStart ",
      "2021-10-21T13:01:39.255Z INFO App Microsoft Enterprise Account: loggerCallback:[Thu, 21 Oct 2021 13:01:39 GMT] : @azure/msal-browser@2.17.0 : Info - Emitting event: msal:acquireTokenFromNetworkStart ",
      "2021-10-21T13:01:45.321Z INFO App Microsoft Enterprise Account: loggerCallback:[Thu, 21 Oct 2021 13:01:45 GMT] : @azure/msal-browser@2.17.0 : Info - Emitting event: msal:acquireTokenFailure ",
      "2021-10-21T13:01:45.744Z ERROR App Microsoft Enterprise Account: ms token acquire failed: ",
      "2021-10-21T13:01:45.745Z ERROR App Microsoft Enterprise Account: access token is not received ",
      "2021-10-21T13:02:54.007Z INFO App Microsoft Enterprise Account: loggerCallback:[Thu, 21 Oct 2021 13:02:54 GMT] : @azure/msal-browser@2.17.0 : Info - Emitting event: msal:acquireTokenFromNetworkStart ",
      "2021-10-21T14:19:08.142Z INFO App Microsoft Enterprise Account: loggerCallback:[Thu, 21 Oct 2021 14:19:08 GMT] : @azure/msal-browser@2.17.0 : Info - Emitting event: msal:acquireTokenFromNetworkStart ",

**Comment by jo-arroyo** [comment]
@pashvin MSAL does not do automatic retries for failed requests. You will have to handle that in your own app.

**Comment by pashvin** [comment]
@jo-arroyo  thanks for that info.

So  is it OK to retry for SlientToken again after it returned an error (except interaction required error)? Any suggestion for implementing retry in case of failure? Anything we should be careful to avoid getting into trouble or avoid retry if there are some special return code from previous call.

**Comment by hectormmg** [comment]
@pashvin retry logic is entirely up to each application. However, we recommend you only retry after the kind of errors that can happen sporadically (i.e. timeout errors). Also, we only recommend you retry once or twice at most, this to avoid looping issues in your application.
