### ISSUE TITLE
Token expiry not calculated when sideloading token

### ISSUE THREAD

**Issue by sbarfurth** [AzureAD/microsoft-authentication-library-for-js#4189]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.18.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

When sideloading a token the `expires_in` value is used for the `expiresOn` field in the token cache. This causes values like `3600` to be checked as a timestamp and be deemed invalid. The value of `extendedExpiresOn` that is also required is ignored completely when the token is eventually validated by `SilentFlowClient`.

### MSAL Configuration

```javascript
{
  auth: {
    clientId: process.env.VUE_APP_AUTH_CLIENT,
    authority: "https://stfs.company.com/adfs",
    knownAuthorities: ["https://stfs.company.com/adfs"],
    redirectUri: process.env.BASE_URL,
    protocolMode: "OIDC"
  },
  cache: {
    cacheLocation: "localStorage",
    storeAuthStateInCookie: true
  }
}
```

### Relevant Code Snippets

```javascript
// https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/7b5f2eaef2eede43f23765b97547922f0024437d/lib/msal-browser/src/cache/TokenCache.ts#L137
const expiresOn = response.expires_in;

// Token expiry is validated in `SilentFlowClient`
// https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/51e8f1bbc286c3ce088ec5659deb186822e18be3/lib/msal-common/src/client/SilentFlowClient.ts#L74
TimeUtils.isTokenExpired(cacheRecord.accessToken.expiresOn, this.config.systemOptions.tokenRenewalOffsetSeconds);
```

### Reproduction Steps

1. Attempt to sideload a token with a response containing `"expires_in": 3600`
2. Set `extendedExpiresOn` to a timestamp in the future

### Expected Behavior

The token should be fetched from cache as valid.

### Identity Provider

ADFS

### Browsers Affected (Select all that apply)

Firefox

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@barfurth This does seem to be an issue. We will investigate a fix and update this when it is prioritized.

**Comment by sbarfurth** [comment]
There is a workaround I found. You can simply override the tokens `expires_in` value with its `exp` claim when passing the token response object. This does however require prior decoding of the token and is obviously less than ideal since the field and value are mismatched.

**Comment by narkaTee** [comment]
I did some debugging and located the code which causes this.
Maybe that helps:
https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4265#issue-1056662150
