### ISSUE TITLE
Does MSAL publishes ani events when access token is expiring in the next 5 min?

### ISSUE THREAD

**Issue by vejandla** [AzureAD/microsoft-authentication-library-for-js#4191]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.15.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.1 (react)

### Description

While I understand the `acquireTokenSilent` does not renew the token unless the token is about to expire in the next 5 min, Is there an event that we can subscribe to when the token is about to expire in the next 5 min, which can help us to determine whether we to acquire the token or not based on our user's activity with the sytem.

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@vejandla MSAL does not have an event for when the token is about to expire. If you would like to know when the token will expire, you can use the `expiresOn` property in the response from` acquireTokenSilent` which represents the expiration of the access token. You may find [this discussion](https://github.com/AzureAD/microsoft-authentication-library-for-js/discussions/4120) helpful in understanding token expiry and user sessions.
