### ISSUE TITLE
(msal-react / typescript) How to type event.payload.account in the addEventCallback

### ISSUE THREAD

**Issue by Pixelatex** [AzureAD/microsoft-authentication-library-for-js#4195]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

^2.18.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

^1.1.0

### Description

As per the documentation, I am setting my active account with the msalInstance.addEventCallback

```
  msalInstance.addEventCallback((event: EventMessage) => {
    if (
      event?.payload?.account &&
      event.eventType === EventType.LOGIN_SUCCESS
    ) {
      const account = event.payload.account
      msalInstance.setActiveAccount(account)
    }
  })
```
However, EventMessage > EventPayload doesn't have "account" typed as an option?

Am I using the wrong typing for this or how am I supposed to handle this correctly?

### MSAL Configuration

```javascript
const msalConfig = {
    auth: {
      clientId: clientId,
      authority: `https://login.microsoftonline.com/${tenantId}`,
      redirectUri: '/',
    },
  }
  const msalInstance = new msal.PublicClientApplication(msalConfig)
  const accounts = msalInstance.getAllAccounts()
  if (accounts.length > 0) {
    msalInstance.setActiveAccount(accounts[0])
  }

  msalInstance.addEventCallback((event: EventMessage) => {
    if (
      event?.payload?.account &&
      event.eventType === EventType.LOGIN_SUCCESS
    ) {
      const account = event.payload.account
      msalInstance.setActiveAccount(account)
    }
  })

  return msalInstance
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@Pixelatex You should cast the payload returned from a successful login as the type `AuthenticationResult`. Please see the example in the react sample [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/a81fcef3d82523e03828d91bb0ee8d2ab2cc20d8/samples/msal-react-samples/typescript-sample/src/index.tsx#L22).

**Comment by Pixelatex** [comment]
Alright thanks, that fixed it!
