### ISSUE TITLE
Missing claim `preferred_username` from accessToken returned from AuthenticationResult

### ISSUE THREAD

**Issue by akeemtaiwo** [AzureAD/microsoft-authentication-library-for-js#4197]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.18.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.1.0

### Description

I noticed a difference in the tokenResponse object returned from `acquireTokenSilent` from `AuthResponse` to  `AuthenticationResult` in v2. 

We used to be able to get the claim `preferred_username` from the `accessToken` string, but this seems to be no longer possible.

The `preferred_username` claim from the Bearer token is used in the backend server to get an email value.

Is this advisable?

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by jo-arroyo** [comment]
@Kid-Codi You are right, the `preferred_username` is not returned in the `AuthenticationResult`. Our advice would be to use the `useAccount` hook and get the `preferred_username` from the `idTokenClaims` field on `AccountInfo` object returned, provided your tenant is configured to return it. Please see the [hooks documentation](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/hooks.md) for more details.
