### ISSUE TITLE
How to add client_secret in an auth code flow?

### ISSUE THREAD

**Issue by domiSchenk** [AzureAD/microsoft-authentication-library-for-js#4198]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.18.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.4

### Description

We use a third party IDP to make the logins, and this IDP demands a client_secret in the token endpoint. (i don't know why)

I looked at the code and found basic implementation for adding client_secret in the `AuthorizationCodeClient` but it is not possible to provide the `clientCredentials` in the MSAL config. When the config is built it takes de `DEFAULT_CLIENT_CREDENTIALS` and therefore it's always empty.

Is this correct or did I miss something?

### Identity Provider

Other

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@domiSchenk You are right, there isn't a way to pass in `client_secret` as msal-browser and msal-angular only support public clients, as they run in an environment (a web browser). If you need to support confidential clients you are welcome to try msal-node.

**Comment by domiSchenk** [comment]
Does the nodejs version run in the browser or are there nodejs specific api calls?

i solved it with patching the angular/browser modul, so its reads from localstorage. This works for now.

I have to ask this provider why they wand a client secret in this environment.
