### ISSUE TITLE
After `logoutRedirect({account})` "Pick an Account" to logout is shown 

### ISSUE THREAD

**Issue by izikl** [AzureAD/microsoft-authentication-library-for-js#4200]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.18.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

Even though `account` is passed to `logoutRedirect` 

I am still getting a list of accounts to sign out from:
![image](https://user-images.githubusercontent.com/8294298/139376064-1d813bdb-963b-4ea7-ba35-b8d39012b382.png)

### Msal Logs

[Fri, 29 Oct 2021 04:33:34 GMT] : @azure/msal-browser@2.18.0 : Info - Emitting event: msal:logoutStart
[Fri, 29 Oct 2021 04:33:34 GMT] : @azure/msal-browser@2.18.0 : Info - Emitting event: msal:logoutSuccess

### MSAL Configuration

```javascript
auth: {
                clientId: "f9818e52-50bd-463e-8932-a1650bd3fad2",
                redirectUri: this.redirectUri,
                authority: `https://login.microsoftonline.com/${this.tenant}`,
            },
            cache: {
                cacheLocation: useLocalStorageForTokens ? 'localStorage' : 'sessionStorage',                
                storeAuthStateInCookie: true,
            },
            system: {
                loggerOptions: {
                    loggerCallback: (level: LogLevel, message: string): void => {
                        trackTrace(message, levelToSeverity(level), { flow: 'msalv2' });
                    },
                    logLevel: LogLevel.Info,
                    piiLoggingEnabled: false,
                },
                loadFrameTimeout: 30000,
            },
```

### Relevant Code Snippets

```javascript
const account = this.application.getAccountByHomeId(this.userHomeAccountId);
requestParams = { account };
await this.application.logoutRedirect(requestParams);
```

### Reproduction Steps

See Relevant Code Snippets

### Expected Behavior

The pick an account page should be skipped. 

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari

### Source

Internal (Microsoft)

**Comment by jo-arroyo** [comment]
@izikl As per our [documentation on logout](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md), logging out of MSAL includes both clearing the MSAL cache and clearing the session on the identity server. Providing the account ensures the account is cleared from the cache, whereas the select account page clears the session on the server. 

Silently logging out of the server session without the select account page is not currently supported, please see issue #3833 for more details. However, if you would like to skip the server sign-out and log out locally, you can find instructions in our documentation [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md#skipping-the-server-sign-out).
