### ISSUE TITLE
loginRedirect: how to add dynamic redirectURI to existing request

### ISSUE THREAD

**Issue by garycass** [AzureAD/microsoft-authentication-library-for-js#4202]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.18.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

When calling loginRedirect, I understand that it is possible to set the `redirectUri` per request, as follows:

```js
// Main configuration, sets blank page as default redirect URI (to be used for popup/silent flows)
const msalInstance = new msal.UserAgentApplication({
  auth: {
    redirectUri: "https://mydomain.com/auth.html"
  }
});

// When using a redirect action, set the redirectUri to a page that has MSAL (to process the response)
msalInstance.loginRedirect({
  redirectUri: "https://mydomain.com"
})
```
Is it possible to do this whilst also passing a pre-defined request to loginRedirect? For example. if I have a JS function like so:

```js
const loginRequest = {
    scopes: ["api://" + AADClientID + "/access_as_user"],
};

function signIn() {
     msalObj.loginRedirect(loginRequest);
 }
```
How would I update that loginRedirect call to also provide the parameter redirectUri: "https://mydomain.com"?

### MSAL Configuration

```javascript
const msalConfig = {
    auth: {
        clientId: AADClientID,
        authority: "https://login.microsoftonline.com/" + AADTenantID,
        redirectUri: URI,
        postLogoutRedirectUri: URI,
    },
    cache: {
        cacheLocation: "localStorage", 
        storeAuthStateInCookie: false, 
    },
};
```

### Source

External (Customer)

**Comment by hectormmg** [comment]
Hi @garycass . You can use the [spread operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax) to keep the same general login request object and override specific attributes before sending it to `loginRedirect`. Your code would look something like this:

```typescript
// Original loginRequest stays the same
const loginRequest = {
    scopes: ["api://" + AADClientID + "/access_as_user"],
};

function signIn() {
     // The spread operator creates a copy of the loginRequest object, only with an overrided `redirectUri`
     msalObj.loginRedirect({ ...loginRequest, redirectUri: "https://mydomain.com"}); 
 }
```

Please let us know if this helps, thanks!

**Comment by garycass** [comment]
Thank you @hectormmg , that solution works perfectly.
