### ISSUE TITLE
[Mac-SAFARI] Continuous Redirect is happening in Mac Safari with redirect flow in angular SPA

### ISSUE THREAD

**Issue by hitkumar25** [AzureAD/microsoft-authentication-library-for-js#4203]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.18.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.4

### Description

After the token is acquired. It redirects again and again in loop while using msal-angular in Angular SPA.

### MSAL Configuration

```javascript
msalConfig: {
        auth: {
            clientId: '*******************',
            authority: 'https://login.microsoftonline.com/microsoft.com',
            redirectUri: `${location.origin}/iv`,
            postLogoutRedirectUri: `${location.origin}/iv/login`,
        },
        cache: {
            cacheLocation: 'localStorage',
            storeAuthStateInCookie: false,
        },
    },
```

### Relevant Code Snippets

```javascript
private handleUnAuthenticatedUser(observer: Observer<OAuthData>, resource: string): void {
        const redirectStartPage = window.location.href;
        this.msalBroadcastService.inProgress$
            .pipe(
                filter((status: InteractionStatus) => status === InteractionStatus.None),
            )
            .subscribe(() => {
                const activeAccount = this.msalService.instance.getActiveAccount();
                if (activeAccount) {
                    // If interaction got completed and in between Login is Successful then acquire token silently.
                    this.acquireTokenSilently(observer, resource, activeAccount);
                } else {
                    // If interaction got completed and still no account set then acquire token interactively.
                    this.msalService.acquireTokenRedirect({ scopes: [resource], redirectStartPage });
                }
            })
    }
```

### Reproduction Steps

1. Go to root URL. 
2. It will redirect (not visible though) to login.microsoft.online.com and get the /#code= in the url.
3. #code is removed from the URl and it again redirects get the code and same again on loop

### Expected Behavior

It should redirect only once and then settle down.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Safari

### Source

Internal (Microsoft)

**Comment by jo-arroyo** [comment]
@hitkumar25 Where is your `handleUnAuthenticatedUser` function being called? Please make sure you are not calling `loginRedirect` in your app.component.ts, and that redirects are being handled properly. Please see [our FAQ](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/FAQ.md#why-is-my-app-looping-when-logging-in-with-redirect) and our [redirect documentation](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/redirects.md) for the appropriate way to use redirects.

**Comment by eluchsinger** [comment]
I can confirm we are observing a similar or the same behavior and only on Safari and using `msal-angular`. Our Safari users are mostly unable to log in and have to resort to using different browsers.
