### ISSUE TITLE
Password Reset Flow Error Code

### ISSUE THREAD

**Issue by BobJeronowitz** [AzureAD/microsoft-authentication-library-for-js#4204]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.17.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

None

### Description

Using MSAL 2.14 and in the Password Reset flow, when the password is reset I am getting a generic B2C error: error_description=AADB2C.  Previously was getting: AADB2C90118.  Is this something controllable by the policy or has something else changed?

### MSAL Configuration

```javascript
{
}
```

### Relevant Code Snippets

```javascript
this.authReady = this.msalInstance
      .handleRedirectPromise()
      .then((response) => {
        const accountInfo = this.getAllAccounts();
        if (accountInfo && accountInfo?.length > 0) {
          const loggedInUser = accountInfo[0];

          const tokenRequest = {
            scopes: this.msalConfiguration[UserClaimInfo.SCOPES],
            account: loggedInUser,
            forceRefresh: false,
          };

          return new Promise<boolean>((res) => {
            this.acquireTokenSilent(tokenRequest).subscribe(
              (authenticationResult: AuthenticationResult) => {
                this.SetUserInStore(authenticationResult);

                res(true);
              }
            );
          });
        }
      })
      .catch((error) => {
        if (error) {
          // AADB2C90118 - Password reset code
          if (error.errorMessage.indexOf('AADB2C90118') > -1) {
            this.redirectToPasswordReset();
          } else if (error.errorMessage.indexOf('AADB2C90091') > -1) {
            // Handles user Cancel when restting password
            this.loginRedirect();
          } else {
            console.error('Error: ' + JSON.stringify(error, null, 2));
          }

          return false;
        }
      });
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by hectormmg** [comment]
Hi @BobJeronowitz . This seems like a B2C service issue. Please file a support ticket with the B2C team by following the instructions here. Thank you.

**Comment by BobJeronowitz** [comment]
Thanks @hectormmg, where are the instructions for opening a ticket?

**Comment by hectormmg** [comment]
Apologies @BobJeronowitz . It seems I didn't properly link to the instructions. You can find them [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options).
