### ISSUE TITLE
AADSTS54005: OAuth2 Authorization code was already redeemed

### ISSUE THREAD

**Issue by JosephThomas** [AzureAD/microsoft-authentication-library-for-js#4217]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.16.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

Have been getting this issue recently:

AADSTS54005: OAuth2 Authorization code was already redeemed, please retry with a new valid code or use an existing refresh token.

Was looking at other solutions online but they don't seem to be as applicable to the msal-browser SDK, like this solution:
"To fix the error try changing your code to request a refresh token that will be passed to /used by additional resources as the refresh tokens can still be reused."

I'm not sure if there is a way to do this as I've only been using acquireTokenSilent mainly.

Full error example:
invalid_grant: 54005 - [2021-10-29 08:28:29Z]: AADSTS54005: OAuth2 Authorization code was already redeemed, please retry with a new valid code or use an existing refresh token. Trace ID: 8ce4449f-de7d-495f-8007-104d6d939e00 Correlation ID: 206a9bc3-7644-4be1-b8d1-7560d0ee2ee9 Timestamp: 2021-10-29 08:28:29Z - Correlation ID: 206a9bc3-7644-4be1-b8d1-7560d0ee2ee9 - Trace ID: 8ce4449f-de7d-495f-8007-104d6d939e00

### MSAL Configuration

```javascript
{
        auth: {
            clientId: process.env.CLIENT_ID,
            authority: 'https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/',
            redirectUri: findTopSameOriginWindow().location.origin + '/blank'
        },
        system: {
            redirectNavigationTimeout: 500,
            iframeHashTimeout: 30000
        },
        cache: {
            cacheLocation: 'localStorage',
            storeAuthStateInCookie: isIE()
        }
    }
```

### Relevant Code Snippets

```javascript
let token: AuthenticationResult | undefined = await this.publicClientApplication.acquireTokenSilent(tokenRequest)
            .catch(async error => {
                return await this.acquireTokenErrorHandling(error, endpoint, tokenRequest);
            });
```

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by hectormmg** [comment]
Hi @JosephThomas . I'm curious about when you're getting this error. The `acquireTokenSilent` API doesn't use an authorization code, so you must be falling back to an interactive `acquireToken` API when `acquireTokenSilent` can't perform the token refresh on it's own. Can you provide the code snippet for what `this.acquireTokenErrorHandling(error, endpoint, tokenRequest)` does? Thanks.

**Comment by JosephThomas** [comment]
```
private acquireTokenErrorHandling = async (error: any, endpoint: string, tokenRequest: PopupRequest | RedirectRequest) => {
        let interactionError = error instanceof InteractionRequiredAuthError || error?.name === 'InteractionRequiredAuthError';
        let clientError = error instanceof ClientAuthError || error?.name === 'ClientAuthError';
        let timeoutError = error?.errorCode === 'monitor_window_timeout';
        let interactivePromptNeeded = interactionError || clientError || timeoutError;

        /* 
            * Case - InteractionRequiredAuthError
            *   This means AAD might be asking for Conditional Access
            *   which requires interactive login from user.
            * Case - ClientAuthError
            *   This mostly mean login require, we will hit his case when user has no token in
            *   local storage.
        */
        if (interactivePromptNeeded) {
            if (this.usePopup) {
                let token = await this.popupQueue(tokenRequest);
                if (token instanceof Error) {
                    this.blockedPopupErrorHandling(token, endpoint);
                } else {
                    return token;
                }
            } else {
                let request: RedirectRequest = {
                    scopes: tokenRequest.scopes,
                    account: this.publicClientApplication.getAllAccounts()[0]
                };
                this.publicClientApplication.acquireTokenRedirect(request);
            }
        }
    }
```
This is the helper function popupQueue used in this function:
```
private popupQueue(tokenRequest?: PopupRequest): Promise<AuthenticationResult | Error> {
        this.popupChainHead = this.popupChainHead.then(() => {
            return this.publicClientApplication.loginPopup(tokenRequest)
                .then(token => token)
                .catch(error => (error instanceof Error) ? error : new Error(error));
        });
        return this.popupChainHead;
    }

**Comment by hectormmg** [comment]
@JosephThomas I can't see any obvious issues with your code, could you please send a network trace from a tool like Fiddler that shows the MSAL network requests to the /authorize and /token endpoints to the e-mail address in my profile? So I can see what MSAL is sending to ESTS. Thanks!

**Comment by hectormmg** [comment]
Tracking this issue offline, will keep updating as necessary.

**Comment by jasonnutter** [comment]
@hectormmg Any update on this issue?

**Comment by JosephThomas** [comment]
Seems that the issue seems to be a fluke, happened a handful of times and was not able to reproduce. Hector mentioned that it could be due to some user's having a bad connection.
