### ISSUE TITLE
Can you login to a ADFS using Authorization Code Flow using msal-broswer.js

### ISSUE THREAD

**Issue by jackmcc08** [AzureAD/microsoft-authentication-library-for-js#4238]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

I am trying to authorize a react SPA against an ADFS Server, I have successfully managed to test out the sample application described here: 
- https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2272
- https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-core-samples/VanillaJSTestApp/app/adfs

But my understanding is that this uses the msal-core.js library and hence uses the Implicit Grant Flow. 

Is there a way to use msal-browser.js (or even more ideally the msal-react.js) and the Authorization Code Flow to access my ADFS server? 
@tnorling ( adding you as you wrote the adfs sample for msal-core 😃 )

### Identity Provider

ADFS

### Source

External (Customer)

**Comment by hectormmg** [comment]
Hi @jackmcc08, we're currently working on documentation and samples for using MSAL v2 with ADFS and will update this issue when those are available. Thanks!

**Comment by jackmcc08** [comment]
@hectormmg  thanks for your response, that sounds great, when do you think those will be released? 

Also, what is the best tutorial to follow for building a protect API which is called from an SPA which uses msal-core.js?

**Comment by sjlawton** [comment]
I am working on a similar case and will look forward to any news on this

**Comment by sameerag** [comment]
> @hectormmg thanks for your response, that sounds great, when do you think those will be released?
> 
> Also, what is the best tutorial to follow for building a protect API which is called from an SPA which uses msal-core.js?

@jackmcc08 Any reason why you are not migrating to MSAL JS V2? We would highly recommend to do that since all our new features are hosted in the new version and the Angular/React libraries are based of msal js v2.

**Comment by jackmcc08** [comment]
Hi @sameerag, 

As mentioned we are looking to use msal for Authenticating Users with an **ADFS server**.  My preference would be to use the MSAL JS V2 as it allows Auth code flow, but it does not seem that the package supports ADFS. 

I have tried using the `msal-browser` and `msal-react` samples to connect to the ADFS server directly to login (popup and redirect) but it does not work. I am getting the below CORS error:
`Access to fetch at 'https://_adfsServer_/adfs/oauth2/token/' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.` 

I cannot access the loginPopup/loginRedirect configuration to be able to set 'no-cors'. 

When searching online generally, the only information I found on connecting to ADFS via MSAL was by using the [ADFS msal-core sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-core-samples/VanillaJSTestApp/app/adfs) which uses the msal-core library - as developed by @tnorling. 

When searching on the issue of CORS which I was getting above, all the solutions indicate registering the app as an SPA in AAD, however as this is an ADFS server, the server does not have this option to make an SPA.

Is there a way to solve this CORS issue? Or any other guidance you can give me to use MSAL.js v2.

Many thanks for any help you can give. 

Kind Regards

Jack 

edits: updated language to make points more readable.

**Comment by Mabritoj** [comment]
> 

Hi @jackmcc08 

I am actually going thru this exercise now with ADFS 2019. 

For the CORS issue, you need to enable and set CORS on ADFS: https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/operations/customize-http-security-headers-ad-fs

Set-AdfsResponseHeaders -EnableCORS $true
Set-AdfsResponseHeaders -CORSTrustedOrigins https://example1.com,https://example2.com

Once I did that, the CORS issue went away. 

@hectormmg  Since you mentioned you are creating documentation, I am having an issue on logout that I hope gets addressed :)

I can not get the redirect to work after logout. ADFS has this error event "The specified redirect URL did not match any of the OAuth client's redirect URIs. The logout was successful but the client will not be redirected. " and the webpage is on the ADFS "Sign Out" screen, but didnt redirect to my homepage. 

Back in the ADAL library, I modified the ADAL.JS file to include "id_token_hint" in the URL request. I was hoping this wouldnt be needed anymore?

**Comment by tnorling** [comment]
@Mabritoj Is your post_logout_redirect_uri registered as a reply url on your app registration? 

> Back in the ADAL library, I modified the ADAL.JS file to include "id_token_hint" in the URL request.

If needed, you can provide the `id_token_hint` to the logout API using the `idTokenHint` parameter and it will be appended to the logout url. See the type reference for logout [here](https://azuread.github.io/microsoft-authentication-library-for-js/ref/modules/_azure_msal_browser.html#endsessionrequest)

@j-mantu is working on the ADFS documentation for msal-browser, he will provide an update when it is available.

**Comment by Mabritoj** [comment]
> @Mabritoj Is your post_logout_redirect_uri registered as a reply url on your app registration?
> 
> > Back in the ADAL library, I modified the ADAL.JS file to include "id_token_hint" in the URL request.
> 
> If needed, you can provide the `id_token_hint` to the logout API using the `idTokenHint` parameter and it will be appended to the logout url. See the type reference for logout [here](https://azuread.github.io/microsoft-authentication-library-for-js/ref/modules/_azure_msal_browser.html#endsessionrequest)
> 
> @j-mantu is working on the ADFS documentation for msal-browser, he will provide an update when it is available.

HI @tnorling 

Since its ADFS premise, I do not have any app registration fields for the logout redirect (like you would in Azure). Just a general field for "Redirect URI" is all that is available in ADFS:
![image](https://user-images.githubusercontent.com/22332897/143243815-5227fe42-1622-46eb-a70b-d4fd8d0466d8.png)

I did try the idTokenHint field and that worked! With that said, should this be the solution? Ill wait for the official answer, but at least its working.

**Comment by tnorling** [comment]
@Mabritoj 
> ince its ADFS premise, I do not have any app registration fields for the logout redirect (like you would in Azure). Just a general field for "Redirect URI" is all that is available in ADFS:

Is `http://localhost:8080` what you're trying to use as your post logout redirect url? Whether you're logging in or out the uri that the identity provider redirects you back to needs to be registered as a Redirect URI, if it's not the redirect won't happen. The "logout redirect url" you are referring to in Azure is used for single sign out which is different than what is being discussed here.

**Comment by Mabritoj** [comment]
> @Mabritoj
> 
> > ince its ADFS premise, I do not have any app registration fields for the logout redirect (like you would in Azure). Just a general field for "Redirect URI" is all that is available in ADFS:
> 
> Is `http://localhost:8080` what you're trying to use as your post logout redirect url? Whether you're logging in or out the uri that the identity provider redirects you back to needs to be registered as a Redirect URI, if it's not the redirect won't happen. The "logout redirect url" you are referring to in Azure is used for single sign out which is different than what is being discussed here.

Hi @TomHickling 

Here is my logout code:


function logout() {
    const logoutRequest = {
        account: msalInstance.getAccountByHomeId(accountId),
        postLogoutRedirectUri: "http://localhost:8080",
        idTokenHint : idToken
    };

    msalInstance.logoutRedirect(logoutRequest);
}

Before the idTokenHint suggestion, it was just the first two parameters of account and podLogoutRedirectUri and that would result in no redirection after logout.
