### ISSUE TITLE
acquireTokenSilent fails the first time after B2C login redirects to back to app

### ISSUE THREAD

**Issue by JBrownie77** [AzureAD/microsoft-authentication-library-for-js#424]
## I'm submitting a...
- [x] Bug report

## Browser:
- [x] Chrome version 68.0.3440.106

## Library version
0.1.9

## Current behavior
This is with an Angular client and ASP .NET backend.
1) User is not logged in
2) Angular auth guard (CanActivate) calls UserAgentApplication.acquireTokenSilent( ), which fails because the user is not logged in
3) User is redirected to app signin page
4) User clicks signin link which calls UserAgentApplication.loginRedirect( )
5) User signs in using B2C
6) User is redirected back to app
7) Auth guard is triggered and calls UserAgentApplication.acquireTokenSilent( ) which STILL fails
8) User is redirected back to signin page
9) UserAgentApplication.tokenRecievedCallback is triggered

## Expected behavior
1) User is not logged in
2) Angular auth guard (CanActivate) calls UserAgentApplication.acquireTokenSilent( ), which fails because the user is not logged in
3) User is redirected to app signin page
4) User clicks signin link which calls UserAgentApplication.loginRedirect( )
5) User signs in using B2C
6) User is redirected back to app
7) Auth guard is triggered and calls UserAgentApplication.acquireTokenSilent( ) which **SUCCEEDS**

## Minimal reproduction of the problem with instructions
Working on this. In the meantime if there is any suggestion around using MSAL with authentication guards in Angular that would be very helpful!
We are internal to MSFT so if a skype call / taking a look at code would be helpful we would be happy to do that!

**Comment by nehaagrawal** [comment]
@JBrownie77  Are you using our angular wrapper(msal-angular)?

**Comment by JBrownie77** [comment]
Thanks for the response @nehaagrawal. I started looking into the angular wrapper but got thrown off by the prerequiste. Does registering our app in the AAD 2.0 portal need to be correlated to our azure subscription in any way? My msdn account is a contributor on our azure subscription, but on the AAD 2.0 portal I don't want to create an app under my account. Could you explain this a little more? Thanks!

**Comment by JBrownie77** [comment]
Turns out there is a flag called navigateToLoginRequestUrl that defaults to true, so even if you specify the redirect callback for AAD, the MSAL library takes you back to the page that initiated login. Setting that to false fixed our issue because the app now redirects to the correct page after signin. Would be great to document that flag. It's taken a few days to get this figured out.

**Comment by nehaagrawal** [comment]
@JBrownie77  Glad that you are able to make it work. We will update our documentation to make it more clear. Closing this issue for now.
