### ISSUE TITLE
Angular - MSAL GUARD fails when path is exactly 3 characters

### ISSUE THREAD

**Issue by whittssg** [AzureAD/microsoft-authentication-library-for-js#4248]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

Latest

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.5

### Description

Routes with a path length of 3 characters wont work with **canActivate: [MsalGuard]** I am pretty sure it stopped working after this change:

[Link](https://github.com/AzureAD/microsoft-authentication-library-for-js/commit/5a31b0551d20656f504eb3fb0d24ab303f562116#diff-c2b23c885fc3bdc6e55701f530c6b540dae83b90a3783b384cbf27091cbaad99)

### Error Message

No Error, just wont route to the path.

### Msal Logs

[Mon, 08 Nov 2021 15:00:39 GMT] : @azure/msal-angular@2.0.5 : Verbose - Guard - canActivate
app.module.ts:214 [Mon, 08 Nov 2021 15:00:39 GMT] : @azure/msal-angular@2.0.5 : Verbose - MSAL Guard activated
app.module.ts:214 [Mon, 08 Nov 2021 15:00:39 GMT] : @azure/msal-browser@2.19.0 : Verbose - handleRedirectPromise called
app.module.ts:214 [Mon, 08 Nov 2021 15:00:39 GMT] : @azure/msal-browser@2.19.0 : Verbose - getAllAccounts called
app.module.ts:214 [Mon, 08 Nov 2021 15:00:39 GMT] : @azure/msal-browser@2.19.0 : Verbose - handleRedirectPromise has been called previously, returning the result from the first call
app.module.ts:214 [Mon, 08 Nov 2021 15:00:39 GMT] : @azure/msal-browser@2.19.0 : Verbose - getAllAccounts called
app.module.ts:214 [Mon, 08 Nov 2021 15:00:39 GMT] : @azure/msal-angular@2.0.5 : Verbose - Guard - at least 1 account exists, can activate or load
app.module.ts:214 [Mon, 08 Nov 2021 15:00:43 GMT] : @azure/msal-angular@2.0.5 : Info - Guard - Hash contains known code response, stopping navigation.
app.module.ts:214 [Mon, 08 Nov 2021 15:00:43 GMT] : @azure/msal-angular@2.0.5 : Verbose - Guard - canActivate
app.module.ts:214 [Mon, 08 Nov 2021 15:00:43 GMT] : @azure/msal-angular@2.0.5 : Verbose - MSAL Guard activated
app.module.ts:214 [Mon, 08 Nov 2021 15:00:43 GMT] : @azure/msal-browser@2.19.0 : Verbose - handleRedirectPromise called
app.module.ts:214 [Mon, 08 Nov 2021 15:00:43 GMT] : @azure/msal-browser@2.19.0 : Verbose - getAllAccounts called
app.module.ts:214 [Mon, 08 Nov 2021 15:00:43 GMT] : @azure/msal-browser@2.19.0 : Verbose - handleRedirectPromise has been called previously, returning the result from the first call
app.module.ts:214 [Mon, 08 Nov 2021 15:00:43 GMT] : @azure/msal-browser@2.19.0 : Verbose - getAllAccounts called
app.module.ts:214 [Mon, 08 Nov 2021 15:00:43 GMT] : @azure/msal-angular@2.0.5 : Verbose - Guard - at least 1 account exists, can activate or load

### MSAL Configuration

```javascript
{
    auth: {
      clientId: 'xxxxxxxxxxxxxxxxxxxx',  
      authority: 'https://login.microsoftonline.com/xxx.onmicrosoft.com/',
      redirectUri: window.location.origin,
      postLogoutRedirectUri: 'https://localhost:44300',
      navigateToLoginRequestUrl: true
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE, // set to true for IE 11
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Verbose,
        piiLoggingEnabled: false
      }
    }
  }
```

### Relevant Code Snippets

```javascript
I am pretty sure the problem lies here: (line 282 in azure-msal-angular.js)

includesCode(path) {
        return path.lastIndexOf("/code") === path.length - "/code".length || // 
            path.endsWith("/code")
            path.indexOf("#code=") > -1 ||
            path.indexOf("&code=") > -1;
}
```

### Reproduction Steps

1. Create a route that has a path of 3 characters (e.g. 'abc')
2. Add  canActivate: [MsalGuard]
3. Try and go to the route.

### Expected Behavior

Route routes to the path like it does for any other path that isnt 3 characters long

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox

### Regression

its worked in the angular betas (the last version i used)

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@whittssg Confirmed as a bug, apologies about that. Will be fixed in next month's release by #4249. For now, use 2.0.4, as this was introduced in 2.0.5.
