### ISSUE TITLE
How to grab access token from cache without using acquireTokenSilent?

### ISSUE THREAD

**Issue by ninni426** [AzureAD/microsoft-authentication-library-for-js#4250]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.18.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.1.0

### Description

Inside current implementation, we are using Axios interceptor which calls the acquireTokenSilent every time before any server API is called to provide us a valid token(either from cache or from API when it has fetched it for the first time or refreshed it in case of expiry).
Reference: https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-acquire-token?tabs=javascript2#acquire-a-token-with-a-redirect

The issue with the current approach:
If we have multiple tabs open where the user has logged in, logout from one of the window is not logging them out from other windows. The reason being we are using session Storage which is not getting cleared for other windows. But it also allows other windows to function as expected until the accessToken present in the cache has expired. 

Since we don't want to use local storage to resolve this could you please provide a solution to grab the token present inside the cache? From UI we plan to use this token until it expires and server API returns us an error thus giving us an indication that we need to call acquireTokenSilent for a new token (if refresh token is valid) or initiate a force logout for the user since the session has expired. 

### MSAL Configuration

```javascript
cache: {
        cacheLocation: 'sessionStorage',
        storeAuthStateInCookie: isIE || isEdge || isFirefox
    }
```

### Relevant Code Snippets

```javascript
/**
     * This function calls acquireTokenSilent before API call.
     * 
     * acquireTokenSilent():
     * When this method is called, the library first checks the cache in browser storage to see if a valid token exists and returns it.
     * When no valid token is in the cache, it attempts to use its refresh token to get the token. 
     * If the refresh token's 24-hour lifetime has expired, MSAL.js will open a hidden iframe to silently request a new authorization code,
     * which it will exchange for a new, valid refresh token.
     * 
     * @returns {Object} - response from acquireTokenSilent
     */
    function issueToken() {
        const account = msalInstance.getActiveAccount();
        if ((Object.keys(account || {})).length > 0) {
            return new Promise((resolve, reject) => {
                return msalInstance.acquireTokenSilent({
                    ...loginRequest,
                    account: account
                }).then((response) => {
                    if (!response.accessToken || response.accessToken === "") {
                        window.location.assign("/logout");
                    }
                    resolve(response);
                }).catch((err) => {
                    reject(err);
                });
            });
        }
    }

    // axios interceptor to append JWT token for all API invoked from application.
    axios.interceptors.request.use(
        async config => {
            let response = await issueToken();
            config.headers['Authorization'] = 'Bearer ' + response?.accessToken;
            config.headers['Content-Type'] = 'application/json';
            return config;
        },
        error => {
            Promise.reject(error)
        });
```

### Source

External (Customer)

**Comment by pkanher617** [comment]
@ninni426 `acquireTokenSilent` already retrieves the tokens from the cache up to 5 minutes before the expiration time by default. Within 5 minutes of the expiration time, `acquireTokenSilent` will then attempt to use the any available refresh tokens to renew the access token. If you have logged out already, this refresh should fail. So the functionality you need should already be available.

We are looking at a feature to configure `acquireTokenSilent` to only do the cache lookup in the future.

**Comment by ninni426** [comment]
The acquireTokenSilent is working as expected. But here specifically the issue arises when multiple tabs are open while we are using **sessionStorage**. The accessToken kept inside the cache is not cleared for all tabs and even if the user has logged out from one window(one session) since the token does not become invalid and is present in the cache, the user can continue working on another tab open.

In the documentation provided its mentioned that 'It is recommended that you call acquireTokenSilent in your app before making an API call to get the valid token.'

Reference:
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md#how-do-i-acquire-an-access-token-how-do-i-use-it

I wanted to validate if the usage of acquireTokenSilent before every API call is constructed as expected.

**Comment by pkanher617** [comment]
> From UI we plan to use this token until it expires

> Since the token does not become invalid and is present in the cache, the user can continue working on another tab open.

I'm a bit confused what the desired behavior you are looking for is, the two statements above indicate different things. 

Yes, the usage of acquireTokenSilent before every API call is as expected. You may need to handle errors for Interaction, which your app should handle. Read these docs for more details on handling access token lifetimes: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/token-lifetimes.md#token-renewal
