### ISSUE TITLE
After logout() the user is able to enter the app again without credentials

### ISSUE THREAD

**Issue by SnehalJ1509** [AzureAD/microsoft-authentication-library-for-js#4251]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

1.3.3

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

1.0.0

### Description

My issue is similar to [this](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/3494) issue and the issue described in [this](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/735#issuecomment-575790830) comment

I am calling logout() on signout button click, but it only redirects to post-redirect-uri and does not logs out the user. When the user clicks "login", he is logged in again without being required to enter his credentials.

This is a serious security issue for users who login to our application on devices shared by multiple users, then logout thinking that they have prevented someone from accessing their account.

I have already gone through many closed issues (including the ones mentioned above) hoping to find a proper documented solution but unfortunately did not get it. Hence opening this same again.

### MSAL Configuration

```javascript
msalConfig: {
    auth: {
      clientId: clientId,
      authority: 'https://login.microsoftonline.com/tenantId/',
      validateAuthority: true,
      redirectUri: 'http://localhost:8100/',
      postLogoutRedirectUri: 'http://localhost:8100/',
      navigateToLoginRequestUrl: true
    },
    cache: {
      cacheLocation: 'localStorage',
      storeAuthStateInCookie: isIE, // set to true for IE 11
    },
    framework: {
      unprotectedResources: ['https://www.microsoft.com/en-us/'],
      protectedResourceMap: new Map(protectedResourceMap)
    },
    system: {
      logger: new Logger(loggerCallback)
    }
  }
```

### Relevant Code Snippets

```javascript
import { MsalService } from '@azure/msal-angular';

constructor(
  private authService: MsalService
) {}

logout() {
  this.authService.logout();
}
```

### Reproduction Steps

1. Create an Ionic/Angular app
2. Install the @azure/msal-angular v1.0.0 and msal v1.3.3 plugins
3. Setup the MSAL configurations and other app configurations as mentioned in [this](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-angular) guide
4. Run the app, login in the app with Microsoft account and after successful authentication user should be redirected to the redirectUrl mentioned in the MSAL configuration
5. Call logout() of the MsalService. User is asked to select which account the user wants to log out from. 
6. Select the account and the user will be logged out.
7. Now try to login again in the app, user gets logged in the app without entering credentials.

### Expected Behavior

After logging out of the app, user should be prompted to enter credentials again while trying to log in the app.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, iPad Safari

### Source

Internal (Microsoft)

**Comment by pkanher617** [comment]
@SnehalJ1509 This is a common issue that may be caused by the OS injecting the cookies of the current account into the browser. We are investigating ways to mitigate this on our end. One workaround you can try is to use a client-side cookie to inform you if a user has logged out, and do not call any MSAL APIs if you detect this cookie.

**Comment by SnehalJ1509** [comment]
@pkanher617 thanks for giving some insight. I am not sure how to access/use the client-side cookie as you have mentioned but I'll give it a try.
While going through different issues and docs I came across this [Single sign-out](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc#single-sign-out) doc. So this issue won't be fixed by even after adding a LogoutUrl in the portal right?

**Comment by samuelkubai** [comment]
Hi @SnehalJ1509

To answer you later question, no, [Single sign-out](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc#single-sign-out) is meant to log out a user from multiple applications but as you mentioned you only have one application to logout from. The explanation and solution explained above by @pkanher617 is the current solution as we work on a permanent solution to mitigate the OS injected cookie from our end.

**Comment by SnehalJ1509** [comment]
@samuelkubai thanks for answering. I am not sure how to access/use the client-side cookies. I'll check that and it would be great if you can also give some reference urls for the same.

**Comment by SnehalJ1509** [comment]
@pkanher617 @samuelkubai another question was that this issue is only with v1.x or also for v2.x? Upgrading the plugin to latest @azure/msal-angular version will fix the issue or not?

**Comment by tnorling** [comment]
@SnehalJ1509 

>  I am not sure how to access/use the client-side cookies. I'll check that and it would be great if you can also give some reference urls for the same.

This would be something that you would be responsible for implementing. There are no cookies set by MSAL.js for this purpose.

> another question was that this issue is only with v1.x or also for v2.x? Upgrading the plugin to latest @azure/msal-angular version will fix the issue or not?

This will be an issue on both versions as this is an issue caused by the OS injecting cookies into your browser.

**Comment by SnehalJ1509** [comment]
> This would be something that you would be responsible for implementing. There are no cookies set by MSAL.js for this purpose.

@tnorling ok, then that will require some R&D to implement it.

> This will be an issue on both versions as this is an issue caused by the OS injecting cookies into your browser.

When can we expect this to be fixed? any timeline set for this?

**Comment by SnehalJ1509** [comment]
> One workaround you can try is to use a client-side cookie to inform you if a user has logged out, and do not call any MSAL APIs if you detect this cookie.

@pkanher617 @samuelkubai @tnorling  I've figured out how to use the cookies but I still don't get this approach.

Let us say when the user logs in the app I set a cookie and when user clicks logout, at that time if I find that cookie then instead of calling the MSAL API (this.authService.logout()) should I just clear the localStorage and redirect user to app login page? 
When user clicks on login will he be asked to enter credentials again?

**Comment by SnehalJ1509** [comment]
After doing some testing again, we found that now it is working in desktop Chrome and Firefox. But it is not working in iPad Safari in one specific scenario.

As we have corporate devices, they are MDM enrolled and while enrolling few certificates get installed in the device. So when we try to login we get an option to use the certificate for password-less login. See below screenshot.

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/13345195/143828157-325c99e6-1197-47ad-ad8a-80e5a37ca0b3.jpeg)

If the device is enrolled in 1st user's name and he/she clicks on continue then without asking for password it logs in the app. Now when we do logout and try to login with other account (2nd user), at that time it automatically picks up the previous user and doesn't ask for password and logs in with his/her account (this is where the problem is).

But if the 1st user clicks on cancel and enters the password manually, logs in the app, logs out and then we try to login with other account (2nd user), at this time it again shows the same popup to use the certificate. But now if we click on cancel then the 2nd user can enter his/her password and can login with his/her account. If the 2nd user clicks on continue instead of cancel then again 1st user's account is picked up and logged in.

So when we use the certificate somehow credentials are getting cached and doesn't let the 2nd user use their credentials after 1st user logs out.

The only workaround we found is that if we do 'Clear History and Website Data' in Safari settings only then the 2nd user can log in after cancelling the certificate popup.

Is there a way if we can do 'Clear History and Website Data' from the app via Javascript? I have tried the solutions given [this](https://stackoverflow.com/questions/179355/clearing-all-cookies-with-javascript) stackoverflow link but with no success.

**Comment by sameerag** [comment]
@oldalton Can your team help here? Is this scenario by design for an MDM enrolled device? 

@SnehalJ1509 This may fall out of scope for MSAL JS team, we have tagged our iOS team if they have any clues to sort this issue for you

**Comment by SnehalJ1509** [comment]
Thanks @sameerag for tagging the right team. I understood this is not a MSAL plugin issue anymore. So after getting some proper solution or reply I'll close this ticket.

**Comment by ghost** [comment]
This issue requires attention from the MSAL.js team and has not seen activity in **5 days**. @pkanher617 please follow up.

**Comment by SnehalJ1509** [comment]
Found a solution to our problem.
As this issue was only in iPad Safari, we have asked our customer to re-enroll the corporate device such that it doesn't use certificate which will then solve the issue. And in desktop browsers it was working as expected.

So closing the issue. 

Thank you everyone for your time, inputs and support! And sorry for the trouble. Happy coding. :)
