### ISSUE TITLE
Incorrect case for token_type value when interacting with ADFS 2019

### ISSUE THREAD

**Issue by gaelian** [AzureAD/microsoft-authentication-library-for-js#4252]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.19.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.5

### Description

We are using MSAL.js with ADFS 2019 (on Windows Server 2019 Datacenter, version 10.0.17763 Build 17763), and we are seeing an issue with a case mismatch between the `token_type` value returned from ADFS and the `token_type` value expected by MSAL.js.

What we are seeing is that [this line in MSAL.js](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/src/cache/entities/AccessTokenEntity.ts#L103) expects the `token_type` value to be `"Bearer"`. However, the `token_type` value returned from the ADFS 2019 `/adfs/oauth2/token/` endpoint is `"bearer"` (note lowercase "b"):

![Capture](https://user-images.githubusercontent.com/357458/141038004-4a40f5a3-69a9-4397-be70-aee5ad7b0ffc.PNG)

The token is cached, but on subsequent requests, the attempt to retrieve the cached token fails because the cache key is not of the same case that MSAL.js is expecting. So the token endpoint is called every time.

I take it that AAD uses `"Bearer"` and not `"bearer"`. But I also gather that MSAL.js is committed to supporting ADFS 2019. It would be much appreciated to get comment from the team on this, and/or whether there is any fix/workaround to overcome this issue.

### MSAL Configuration

```javascript
auth: {
    clientId: '<client ID>',
    authority: 'https://<ADFS domain>/adfs',
    redirectUri: '<redirect URI>',
    knownAuthorities: ['<ADFS domain>'],
    protocolMode: ProtocolMode.OIDC
  },
  cache: {
    cacheLocation: BrowserCacheLocation.LocalStorage,
    storeAuthStateInCookie: isIE,
  },
  system: {
    loggerOptions: {
      loggerCallback(logLevel: LogLevel, message: string) {
        console.log(message);
      },
      logLevel: LogLevel.Verbose,
      piiLoggingEnabled: false
    }
```

### Relevant Code Snippets

```javascript
N/A.
```

### Reproduction Steps

1. Configure Angular app (with msal-angular 2.0.5 and msal-browser 2.19.0) to use ADFS 2019 as IDP.
2. Login via ADFS with a valid user.
3. Examine the `token_type` value returned from the ADFS token endpoint using browser dev tools.

### Expected Behavior

MSAL.js should find the cached token, subsequent to successfully caching it.

### Identity Provider

ADFS

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer, Other

### Source

External (Customer)

**Comment by pkanher617** [comment]
@gaelian Thanks for bringing this up. We are exploring options to mitigate this issue and will try to push a fix for this shortly.

**Comment by gaelian** [comment]
@pkanher617 many thanks. Do you have a rough ETA? This would help us to plan.
