### ISSUE TITLE
no_tokens_found with msal-react when there is a second instance of msal present.

### ISSUE THREAD

**Issue by shmehltr** [AzureAD/microsoft-authentication-library-for-js#4254]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.1.1

### Description

We are trying to load our React app using msal-react as a nested application in a portal experience. The portal is also using MSAL and their app reg is on the same tenant. We are trying to use the useMsalAuthentication hook with a silent interaction and providing the account identifiers but keep running into the no_tokens_found error. It seems like the the wrapper recognizes the account logged in on the other instance and never fires the sso for our client. Since they are on the same tenant the local home account ids are the same and the only way to differentiate would be the aud on the token for the account.  I have had some success using msal-browser directly and bypassing the react-wrapper but even going about it that way seems to be a bit unpredictable. 

We were previously running this same app with the react wrapper in an older version of the portal that used ADAL and everything worked fine that way. The only major change is the newer portal is using MSAL. 

Is this a supported use case to have two instances for the same account? If not what is the recommended way to handle a case like this? 

### Error Message

 "no_tokens_found: No tokens were found for the given scopes, and no authorization code was passed to aquireToken"

### MSAL Configuration

```javascript
auth: {
    authority: 'https://login.microsoftonline.com/microsoft.onmicrosoft.com',
    clientId: '...',
    redirectUri: window.location.origin,
    navigateToLoginRequestUrl: true,
  },
  cache: {
    cacheLocation: 'localStorage',
    storeAuthStateInCookie: isIE || isEdge || isFirefox,
  },
```

### Relevant Code Snippets

```javascript
const { login, error } = useMsalAuthentication(InteractionType.Silent, loginRequest, accountIdentifier);
```

### Reproduction Steps

Run a react app nested inside another app that is also using MSAL.
- The "shell" app has an instance of msal client with clientId:  A in configuration.
- The "nested" app has an instance of msal client with clientId: B in configuration.
- Both app registrations are on the same tenant.
- When the nested app uses the useMsalAuthentication hook no login occurs 
- Token calls from "nested" app fail with no_tokens_found

### Expected Behavior

Run a react app nested inside another app that is also using MSAL.
- The "shell" app has an instance of msal client with clientId:  A in configuration.
- The "nested" app has an instance of msal client with clientId: B in configuration.
- Both app registrations are on the same tenant.
- When the nested app uses the useMsalAuthentication hook it can determine that the aud on the id token does not match?
- Token calls from separate instances are successful. 

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
@shmehltr Thanks, this is indeed a bug. As you pointed out, the main issue here is that `ssoSilent` isn't firing because `useMsalAuthentication` thinks you're signed in, which isn't incorrect but it's incomplete. We should be, not only checking if an account exists in the cache, but also if a set of tokens exist. I'll see what we can do to fix this, but in the meantime you'll need to handle this by calling either `ssoSilent`, `loginRedirect` or `loginPopup`.

> Is this a supported use case to have two instances for the same account? If not what is the recommended way to handle a case like this?

Yes this is supported. But when using react you do have to make sure that you don't have nested `MsalProvider` components. You can have more than one on the page but one shouldn't be rendered underneath another.

**Comment by shmehltr** [comment]
Thanks for the update I wasn't 100% sure if it was bug or an unsupported case. With that in mind we can patch in a work around for now until the bug fix makes it to release. We should be ok on the provider part the host shell is just using msal-browser and we only render one in our scope.  Thanks again!
