### ISSUE TITLE
Might be worth exploring esbuild to improve monorepo build times 

### ISSUE THREAD

**Issue by DarylThayil** [AzureAD/microsoft-authentication-library-for-js#4255]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

2.0

### Description

https://mmazzarolo.com/blog/2021-11-06-speed-up-your-typescript-monorepo-with-esbuild/
Stumbled upon this and remembered build times for the mono repo were so high with lerna ... maybe this will help :) 
Hope you are all doing well. 

### Identity Provider

Other

### Source

External (Customer)

**Comment by samuelkubai** [comment]
Thanks @DarylThayil for the referral will definitely look into it, hope you are doing well too

**Comment by sameerag** [comment]
Closing this. We are working on improving build tooling for the next version.
