### ISSUE TITLE
Post method on token request not pasing parameters correctly

### ISSUE THREAD

**Issue by productoptimization** [AzureAD/microsoft-authentication-library-for-js#4256]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

azure/msal-browser 2.19

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

@azure/msal-react 1.1.1

### Description

I trying to authorize the app throw PKCE using   useMsalAuthentication("popup",request) from msal-react wrapper

On the step of getting the token on post  (https://login.microsoftonline.com/{TenantID}/oauth2/v2.0/token)

I got an error (from chrome tools {"error":"invalid_request","error_description":"AADSTS9002326: Cross-origin token redemption is permitted only for the 'Single-Page Application'... )

Comparing with another method that works on postman, appears to me that the post call generated by the msal react wrapper the parameters aren't properly encode or something like that. The postman can't recognize properly the parameters on the Body part of the message.

### Error Message

{"error":"invalid_request","error_description":"AADSTS9002326: Cross-origin token redemption is permitted only for the 'Single-Page Application'... )

### MSAL Configuration

```javascript
const configuration: Configuration = {
    auth: {
        clientId: "client id",
        authority: "https://login.microsoftonline.com/{tetanId}",
        redirectUri: 'https://mysite/oauth2-redirect'},
    cache: {
        cacheLocation: "localStorage", // This configures where your cache will be stored
        storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
        }
};
```

### Relevant Code Snippets

```javascript
import './App.css';

import React from "react";
import Menu_ from "./components/menu";

//import { AuthenticatedTemplate, UnauthenticatedTemplate } from "@azure/msal-react";
import { useIsAuthenticated,useMsalAuthentication  } from "@azure/msal-react";


function App() {

  const request = {scopes: ["api://apiID/user_impersonation"],
                   prompt: 'select_account'};
   const isAuthenticated = useIsAuthenticated();
   const {login, result, error} = useMsalAuthentication("popup",request);
   //const { user, logout, getToken, token, loginError } = useMsal();

  return (
    <div className="App">
      <Menu_/>
      <React.Fragment>
            <p>Anyone can see this paragraph.</p>
            {isAuthenticated && (<p>At least one account is signed in!</p>)}
            {!isAuthenticated && (<p>No users are signed in!</p>)}
        </React.Fragment>
    </div>
  );
}

export default App;
```

### Reproduction Steps

from the SPA try to make a basic login 

### Expected Behavior

Recibe the access token

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by pkanher617** [comment]
The error you are describing here is related to the way the application has been registered in the portal. Please make sure the redirect URI is of type "SPA". You can read more by following the [pre-requisites](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-browser#prerequisites) for the library.
