### ISSUE TITLE
Fail to get token at startup

### ISSUE THREAD

**Issue by pashvin** [AzureAD/microsoft-authentication-library-for-js#4259]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.17.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

NA

### Description

We have report from customer time to time that meeting list is not loading and log shows that token renewal at startup fails.
Each time we get diff reason code so does MSAL handles cases that network may not be ready when asked to get the token or it is a client responsibility to check for network and then call for token renewal?

### Error Message

So far we got two error code 1) iframe timeout and 2) fail to parse network response.

### MSAL Configuration

```javascript
this.msalauthService = new PublicClientApplication({
      auth: {
        clientId: this.getClientId(),
        redirectUri: window.location.origin + '/office365/login/redirect',
      },
      cache: {
        cacheLocation: 'localStorage',
        storeAuthStateInCookie: false, // set to true for IE 11
      },
      system: {
        iframeHashTimeout: 10000,
        loggerOptions: {
```

### Relevant Code Snippets

```javascript
private async getAccessToken(): Promise<string> {
    let InteractionRequiredAuth = false;
    let result = await this.msalauthService.acquireTokenSilent({ scopes: this.tokenScope }).catch((reason) => {
      if (reason instanceof InteractionRequiredAuthError) {
        // MS may ask for interactive token renewal so keep that as info instead of error
        Logging.info('Microsoft Enterprise Account: Interaction required:', reason);
        InteractionRequiredAuth = true;
      } else {
        Logging.error('Microsoft Enterprise Account: ms token acquire failed:', reason);
      }
    });

    if (InteractionRequiredAuth) {
      if (!this.isInteractionInProgress) {
        this.isInteractionInProgress = true;
        // use aquiretoken popup instead of login popup to avoid
        // issue of poping login window every day.
        result = await this.msalauthService
          .acquireTokenPopup({ scopes: this.tokenScope })
          .catch((reason) => {
            Logging.error('Microsoft Enterprise Account: ms token interactive acquire failed:', reason);
          })
          .finally(() => {
            this.isInteractionInProgress = false;
          });
      } else {
        Logging.info('Microsoft Enterprise Account: previous interactive login in progress. avoiding duplicate popup');
      }
    }

    if (result && result.accessToken) {
      return result.accessToken;
    } else {
      Logging.error('Microsoft Enterprise Account: access token is not received');
    }
    return '';
  }
```

### Reproduction Steps

Start app after restarting machine or start client when network having issues and on start app try to call a function to get access token.

### Expected Behavior

Just want to know how MS lib behave in network issues and what client should do for that.

### Identity Provider

ADFS

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by pashvin** [comment]
"2021-11-13T01:12:06.116Z INFO App Microsoft Enterprise Account: loggerCallback:[Sat, 13 Nov 2021 01:12:06 GMT] : @azure/msal-browser@2.17.0 : Info - Emitting event: msal:acquireTokenFromNetworkStart ",
"2021-11-13T01:12:08.396Z INFO App Microsoft Enterprise Account: loggerCallback:[Sat, 13 Nov 2021 01:12:08 GMT] : @azure/msal-browser@2.17.0 : Info - Emitting event: msal:acquireTokenFailure ",
"2021-11-13T01:12:08.399Z ERROR App Microsoft Enterprise Account: ms token acquire failed: {\n  "stack": "BrowserAuthError: failed_to_parse_response: Failed to parse network response. Check network trace. | Attempted to reach: https://login.microsoftonline.com/common/oauth2/v2.0/token\\n    at t [as constructor] (https://one.mitel.io/main.15f833c0cee1a84da645.js:1:6733792)\\n    at new t (https://one.mitel.io/main.15f833c0cee1a84da645.js:1:6742827)\\n    at Function.t.createFailedToParseNetworkResponseError (https://one.mitel.io/main.15f833c0cee1a84da645.js:1:6748818)\\n    at e.<anonymous> (https://one.mitel.io/main.15f833c0cee1a84da645.js:1:6816548)\\n    at https://one.mitel.io/main.15f833c0cee1a84da645.js:1:6719597\\n    at Object.throw (https://one.mitel.io/main.15f833c0cee1a84da645.js:1:6719702)\\n    at c (https://one.mitel.io/main.15f833c0cee1a84da645.js:1:6718491)\\n    at l.invoke (https://one.mitel.io/polyfills.346972adb8a1af4a1ebd.js:1:9121)\\n    at Object.onInvoke (https://one.mitel.io/main.15f833c0cee1a84da645.js:1:9724040)\\n    at l.invoke (https://one.mitel.io/polyfills.346972adb8a1af4a1ebd.js:1:9061)\",\n  "message": "failed_to_parse_response: Failed to parse network response. Check network trace. | Attempted to reach: https://login.microsoftonline.com/common/oauth2/v2.0/token\",\n  "errorCode": "failed_to_parse_response",\n  "errorMessage": "Failed to parse network response. Check network trace. | Attempted to reach: https://login.microsoftonline.com/common/oauth2/v2.0/token\",\n  "subError": "",\n  "name": "BrowserAuthError",\n  "correlationId": "2a45294c-3fc4-4ad3-b9cd-d332bd72e8d1"\n}",
"2021-11-13T01:12:08.399Z ERROR App Microsoft Enterprise Account: ms token acquire failed: {\n  "stack": "BrowserAuthError: failed_to_parse_response: Failed to parse network response. Check network trace. | Attempted to reach: https://login.microsoftonline.com/common/oauth2/v2.0/token\\n    at t [as constructor] (https://one.mitel.io/main.15f833c0cee1a84da645.js:1:6733792)\\n    at new t (https://one.mitel.io/main.15f833c0cee1a84da645.js:1:6742827)\\n    at Function.t.createFailedToParseNetworkResponseError (https://one.mitel.io/main.15f833c0cee1a84da645.js:1:6748818)\\n    at e.<anonymous> (https://one.mitel.io/main.15f833c0cee1a84da645.js:1:6816548)\\n    at https://one.mitel.io/main.15f833c0cee1a84da645.js:1:6719597\\n    at Object.throw (https://one.mitel.io/main.15f833c0cee1a84da645.js:1:6719702)\\n    at c (https://one.mitel.io/main.15f833c0cee1a84da645.js:1:6718491)\\n    at l.invoke (https://one.mitel.io/polyfills.346972adb8a1af4a1ebd.js:1:9121)\\n    at Object.onInvoke (https://one.mitel.io/main.15f833c0cee1a84da645.js:1:9724040)\\n    at l.invoke (https://one.mitel.io/polyfills.346972adb8a1af4a1ebd.js:1:9061)\",\n  "message": "failed_to_parse_response: Failed to parse network response. Check network trace. | Attempted to reach: https://login.microsoftonline.com/common/oauth2/v2.0/token\",\n  "errorCode": "failed_to_parse_response",\n  "errorMessage": "Failed to parse network response. Check network trace. | Attempted to reach: https://login.microsoftonline.com/common/oauth2/v2.0/token\",\n  "subError": "",\n  "name": "BrowserAuthError",\n  "correlationId": "2a45294c-3fc4-4ad3-b9cd-d332bd72e8d1"\n}",
"2021-11-13T01:12:08.399Z ERROR App Microsoft Enterprise Account: access token is not received ",
"2021-11-13T01:12:08.399Z ERROR App Microsoft Enterprise Account: access token is not received ",
"2021-11-13T01:16:05.816Z INFO App Microsoft Enterprise Account: loggerCallback:[Sat, 13 Nov 2021 01:16:05 GMT] : @azure/msal-browser@2.17.0 : Info - Emitting event: msal:acquireTokenFromNetworkStart ",
"2021-11-13T01:16:08.146Z INFO App Microsoft Enterprise Account: loggerCallback:[Sat, 13 Nov 2021 01:16:08 GMT] : @azure/msal-browser@2.17.0 : Info - Emitting event: msal:acquireTokenFailure ",
"2021-11-13T01:16:08.147Z ERROR App Microsoft Enterprise Account: ms token acquire failed: {\n  "stack": "BrowserAuthError: failed_to_parse_response: Failed to parse network response. Check network trace. | Attempted to reach: https://login.microsoftonline.com/common/oauth2/v2.0/token\\n    at t [as constructor] (https://one.mitel.io/main.15f833c0cee1a84da645.js:1:6733792)\\n    at new t (https://one.mitel.io/main.15f833c0cee1a84da645.js:1:6742827)\\n    at Function.t.createFailedToParseNetworkResponseError (https://one.mitel.io/main.15f833c0cee1a84da645.js:1:6748818)\\n    at e.<anonymous> (https://one.mitel.io/main.15f833c0cee1a84da645.js:1:6816548)\\n    at https://one.mitel.io/main.15f833c0cee1a84da645.js:1:6719597\\n    at Object.throw (https://one.mitel.io/main.15f833c0cee1a84da645.js:1:6719702)\\n    at c (https://one.mitel.io/main.15f833c0cee1a84da645.js:1:6718491)\\n    at l.invoke (https://one.mitel.io/polyfills.346972adb8a1af4a1ebd.js:1:9121)\\n    at Object.onInvoke (https://one.mitel.io/main.15f833c0cee1a84da645.js:1:9724040)\\n    at l.invoke (https://one.mitel.io/polyfills.346972adb8a1af4a1ebd.js:1:9061)\",\n  "message": "failed_to_parse_response: Failed to parse network response. Check network trace. | Attempted to reach: https://login.microsoftonline.com/common/oauth2/v2.0/token\",\n  "errorCode": "failed_to_parse_response",\n  "errorMessage": "Failed to parse network response. Check network trace. | Attempted to reach: https://login.microsoftonline.com/common/oauth2/v2.0/token\",\n  "subError": "",\n  "name": "BrowserAuthError",\n  "correlationId": "9da62cd3-827b-43c7-9906-4b2798c9d474"\n}",
"2021-11-13T01:16:08.147Z ERROR App Microsoft Enterprise Account: ms token acquire failed: {\n  "stack": "BrowserAuthError: failed_to_parse_response: Failed to parse network response. Check network trace. | Attempted to reach: https://login.microsoftonline.com/common/oauth2/v2.0/token\\n    at t [as constructor] (https://one.mitel.io/main.15f833c0cee1a84da645.js:1:6733792)\\n    at new t (https://one.mitel.io/main.15f833c0cee1a84da645.js:1:6742827)\\n    at Function.t.createFailedToParseNetworkResponseError (https://one.mitel.io/main.15f833c0cee1a84da645.js:1:6748818)\\n    at e.<anonymous> (https://one.mitel.io/main.15f833c0cee1a84da645.js:1:6816548)\\n    at https://one.mitel.io/main.15f833c0cee1a84da645.js:1:6719597\\n    at Object.throw (https://one.mitel.io/main.15f833c0cee1a84da645.js:1:6719702)\\n    at c (https://one.mitel.io/main.15f833c0cee1a84da645.js:1:6718491)\\n    at l.invoke (https://one.mitel.io/polyfills.346972adb8a1af4a1ebd.js:1:9121)\\n    at Object.onInvoke (https://one.mitel.io/main.15f833c0cee1a84da645.js:1:9724040)\\n    at l.invoke (https://one.mitel.io/polyfills.346972adb8a1af4a1ebd.js:1:9061)\",\n  "message": "failed_to_parse_response: Failed to parse network response. Check network trace. | Attempted to reach: https://login.microsoftonline.com/common/oauth2/v2.0/token\",\n  "errorCode": "failed_to_parse_response",\n  "errorMessage": "Failed to parse network response. Check network trace. | Attempted to reach: https://login.microsoftonline.com/common/oauth2/v2.0/token\",\n  "subError": "",\n  "name": "BrowserAuthError",\n  "correlationId": "9da62cd3-827b-43c7-9906-4b2798c9d474"\n}",
"2021-11-13T01:16:08.147Z ERROR App Microsoft Enterprise Account: access token is not received ",
"2021-11-13T01:16:08.147Z ERROR App Microsoft Enterprise Account: access token is not received ",

**Comment by samuelkubai** [comment]
Hi @pashvin,

Thank you for reaching out about this.

On the question below
> so does MSAL handles cases that network may not be ready when asked to get the token or it is a client responsibility to check for network and then call for token renewal?

No, MSAL does not handle cases that the network may not be ready, for this case you need to detect this error and retry on your client.

Could you send a fiddler trace to best understand what is going on?

**Comment by pashvin** [comment]
@samuelkubai Issue comes from our customer so don't have all network traces and fiddler and most of user don't see any problem including my self who has good network. Some user who complains are having network known instability (some uses repeaters in home and when they move room to room. one of request may fail) and get issue once a while. I feel SDK should react on some common network response and should try to get token in some common cases and make more full proof in those condition. That saves work form every client. Whole goal of this SDK is to get token and manage it so why not handle some common fail cases too?

**Comment by samuelkubai** [comment]
Hi @pashvin, 

As a library we don't think retries due to network errors lies within the scope of the library, as there are many ways our users would decide to handle such cases, and thus we leave it to the client applications to decide how to handle errors due to network connection issues.

But from the logs, it looks like you are getting a response back, but the library is not able to parse the response, thus a fiddler trace recreating this issue would be great, to best help debug this issue.

**Comment by pashvin** [comment]
@samuelkubai I asked original user to reproduce and collect network trace. he may be not familiar with all other tools. Anyway I am thinking to retry getting token if first request for token fail but first of all I don't have list of error can be returned  from acquireTokenSilent and which one I should retry and which one I should not. I know interaction required don't need retry but all other error code are safe to do blind retry? I also got error like iframe timeout. If I retry, then looks like it will not work as timeout setting is low as per user's computer speed so I feel SDK knows much better to try in certain condition and not try in other case. SDK can provide way to pass retry number in the function so that way if SDK user don't want SDK to try or try x amount of time , then it still can within SDK developer control.

**Comment by samuelkubai** [comment]
Hi @pashvin,

Sure thing, waiting for the network trace so as to confirm that the cause of the error is in fact network connection.

To answer your second question, yes, the SDK does throw a specific `noNetworkConnectivity` error with the error code `no_network_connectivity`, you can find the error [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/8afb0be101c2ff51533fce867791efdba6d88ee6/lib/msal-browser/src/error/BrowserAuthError.ts#L128) to learn more about it if interested. So if you are looking to retry in case of loss of network connection, do listen to that error code.

**Comment by pashvin** [comment]
@samuelkubai One more question. If We get noNetworkConnectity error , then I think client can wait for network connectivity restored and then retry but sometime I get following error. Will re-try fix iframe timeout? or there is no point retrying on that error?

\"BrowserAuthError: monitor_window_timeout: Token acquisition in iframe failed due to timeout. For more visit: aka.ms/msaljs/browser-errors.\\n at t [as constructor]

**Comment by samuelkubai** [comment]
Hi @pashvin, we would need the fiddler trace of this too to be able to debug the source of this error.

As, this usually happens if the iframe renders a page that isn't the original page making the silent request, you would have to review a fiddler trace to know what page is actually being rendered.
