### ISSUE TITLE
loginPopup does not redirect to redirectUri in the original tab but opens redirectUri on Popup.

### ISSUE THREAD

**Issue by dhruvildave22** [AzureAD/microsoft-authentication-library-for-js#4266]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.19.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.1.1

### Description

I'm using MSAL in a react based SPA and a PCF component which is imported into a canvas app and this canvas app is embedded into Dynamic365 Field service CRM.
I have created a Azure AAD app registration and added these redirectUri in Single Page Application
1. localhost:3001
2. *.crm.dynamics.com/main.aspx //main.aspx because i referenced this Issue [#190](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/190) earlier.

So when i open my app in localhost:3001, it work fine. It popup a login window ask for login and when close it gives a access token in response. but in second condition pop up is not redirecting back to it's main page but opens in the popup itself.

### Error Message

No response

### Msal Logs

No response

### MSAL Configuration

```javascript
auth: {
  clientId: 'client_id',
  authority: 'https://login.microsoftonline.com/tanent_id',
  redirectUri: '*.crm.dynamics.com/main.aspx',
}
```
I have used this inside PCF component which i am using in D365 Field service.

### Relevant Code Snippets

```javascript
import { PublicClientApplication } from "@azure/msal-browser";

const msalConfig = {
  auth: {
    clientId: 'client_id',
    authority: 'https://login.microsoftonline.com/tanent_id',
    redirectUri: '*.crm.dynamics.com/main.aspx',
  }
};

const msalInstance = new PublicClientApplication(msalConfig);

var loginRequest = {
  responseMode:"query",
  scopes: ["openid", "offline_access", "https://storage.azure.com/user_impersonation"],
};


msalInstance.loginPopup(loginRequest)
  .then(response => {
    console.log(response)
  })
  .catch(err => {
    console.log(err)
  });
```

### Reproduction Steps

1. Create a PCF component with above Code Snippets.
2. Add this PCF component inside a canvas app.
3. Embed new created canvas app inside a D365 Field Service CRM.
4. When you open your PCF component inside the D365 Field Service CRM which runs on this *.crm.dynamics.com/main.aspx, It will open a login Popup. we have to login from that popup.
5. This popup does not close but open the redirect URL inside the popup only.
<img width="1095" alt="Screenshot 2021-11-18 at 6 30 34 PM" src="https://user-images.githubusercontent.com/36095412/142420875-638c71fd-1954-4756-81c6-d4039cd67524.png">
and I have added redirect URI inside App registration like this
<img width="1006" alt="Screenshot 2021-11-18 at 6 38 51 PM" src="https://user-images.githubusercontent.com/36095412/142421345-0d5b86b3-bd86-419f-b6b5-2bdb016b0272.png">
I have already used every variant like *.crm.dynamics.com/main.aspx and *.crm.dynamics.com/ and *.crm.dynamics.com.

### Expected Behavior

A login popup pops up and after the user logs in the pop up closes itself and the loginPopup promise resolves (or rejects).

### Actual Behavior

A login popup pops up and after the user logs in the pop up redirects back to my site in the pop up.
<img width="1095" alt="Screenshot 2021-11-18 at 6 30 34 PM" src="https://user-images.githubusercontent.com/36095412/142420875-638c71fd-1954-4756-81c6-d4039cd67524.png">

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer, Other

### Regression

No response

### Source

External (Customer)

**Comment by dhruvildave22** [comment]
Hi @samuelkubai any update on this?

**Comment by Delwalt** [comment]
Hi @dhruvildave22  I also facing the same issue, did you find any solution ?

**Comment by tnorling** [comment]
@dhruvildave22 @Delwalt Are the main window and popup window running on the same domain? The `redirectUri` must be on the same domain as the window that opened the popup.

**Comment by dhruvildave22** [comment]
@tnorling Main window is opening a Microsoft Authentication login popup, which should redirect back to the same main window domain after successful authentication.
So yes `redirectUri` is same as main window domain.
I have tried *.crm.dynamics.com and *.crm.dynamics.com/main.aspx both as `redierctUri`.

**Comment by tnorling** [comment]
@dhruvildave22 Is there a hash fragment in the url in the popup or has it been cleared?

**Comment by dhruvildave22** [comment]
@tnorling  No, there is not any hash fragment in the login popup I am adding all the urls comes in login Popup.
1. When login Popup asks to select an account or add a new account: ```https://login.microsoftonline.com/<tanent_id>/oauth2/v2.0/authorize?client_id=<client_id>&scope=openid%20offline_access%20https://storage.azure.com/user_impersonation%20profile&redirect_uri=https://my-fs-test2.crm.dynamics.com/main.aspx&client-request-id=<client_request_id>&response_mode=fragment&response_type=code&x-client-SKU=msal.js.browser&x-client-VER=2.19.0&x-client-OS=&x-client-CPU=&client_info=1&code_challenge=nUC_kIEG5k14c9FvDeiJdfGqQTBIUx5agC24GXT3MjQ&code_challenge_method=S256&nonce=d9bdad34-f66d-4534-8651-1bd7e255d7d9&state=eyJpZCI6Ijk2YmI3YzQ0LTZiMjUtNDMyMC1iNjY4LWZiODMyODJiZWNlOSIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicG9wdXAifX0%3D```.
2. When login is successful, It redirects to this url inside the Popup: ```https://my-fs-test2.crm.dynamics.com/main.aspx?appid=<app-id>&forceUCI=1&pagetype=entitylist&etn=msdyn_fieldservicesetting&viewid=5e948912-3d4f-4fd8-9bdd-32db02ff00b0&viewType=1039```

My only issue is that, it is not closing the login popup and redirecting to the `point: 2` url direct inside the popup.

**Comment by tnorling** [comment]
@dhruvildave22 The authentication response is returned in the hash fragment which MSAL needs to extract before closing the popup. If your site is removing the hash or redirecting the page inside the popup before MSAL can read the hash it can result in the behavior you are seeing. Looks like your site is adding some query parameters? Please make sure when this happens it is not also removing the hash, or suppress this behavior when the page is opened in a popup.

**Comment by dhruvildave22** [comment]
@tnorling I tested my response url after i logged in on the popup and then it is taking me to this domain ```https://my-fs-test2.crm.dynamics.com``` but it is not giving me the hash fragment like this ```https://my-fs-test2.crm.dynamics.com/#code=some_code``` in my PCF component. 

Then I added msal.js(and all the code which is required to open a login popup) in different react web app and deployed on Azure App Service. So on Azure App Service, all the process is working fine.
1. It opens a Login Popup.
2. After login, The popup redirects to `https://my-domain.azurewebsites.net/#code=some_code` and close the popup.
3. I get the response as a auth_token with some other details.

So my speculation here is that it works fine for Single Page Applications or web apps but it doesn't work properly in a Dynamic 365 CRM or PCF component canvas app which is embedded on Dynamic 365 CRM.

**Comment by jo-arroyo** [comment]
@dhruvildave22 It is possible that something on the Dynamic 365 side is clearing the hash. You can confirm this by debugging the MSAL library, specifically `monitorPopupForSameOrigin`, [shown here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/67e4af7ed6640ea1e140ed2eb3aec4bf6f5b674c/lib/msal-browser/src/interaction_handler/PopupHandler.ts#L58). If the hash is not in the URL at that point, it is probably being cleared.

**Comment by dhruvildave22** [comment]
@jo-arroyo let me look into it with `monitorPopupForSameOrigin`.
