### ISSUE TITLE
An update to MsalAuthenticationTemplate ran an effect , error when writing unit test with jest

### ISSUE THREAD

**Issue by maddyjolly2112** [AzureAD/microsoft-authentication-library-for-js#4267]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.18.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.1.0

### Description

I am getting errors while writing unit test cases for my application

An update to MsalAuthenticationTemplate ran an effect , error when writing unit test with jest in reactjs

```
console.error
      Warning: An update to MsalAuthenticationTemplate ran an effect, but was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
      
      act(() => {
    /* fire events that update state */
  });
  /* assert on the output */
  
  This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
      at MsalProvider (C:\XXXXXX\node_modules\@azure\msal-react\src\MsalProvider.tsx:25:31)
      at ThemeProvider (C:\XXXXXX\node_modules\@material-ui\core\node_modules\@material-ui\styles\ThemeProvider\ThemeProvider.js:48:24)
      at Provider (C:\XXXXXX\node_modules\react-redux\lib\components\Provider.js:21:20)
```

Is there any solution which somebody have tried and able to remove above errors from console while writing unit test cases

### MSAL Configuration

```
const msalInstance = new PublicClientApplication(msalConfig);`

const msalConfig = {
  auth: {
    clientId: "XXXXX-333333333",
    authority: "https://login.microsoftonline.com/XXXXX-333333333333445",
    redirectUri: `${redirectUri}`,
  },
  cache: {
    cacheLocation: "sessionStorage", 
    storeAuthStateInCookie: false
  },
};

```

### Relevant Code Snippets

**Unit test Config**

```
'use strict';

process.env.BABEL_ENV = 'test';
process.env.NODE_ENV = 'test';
process.env.PUBLIC_URL = '';

process.on('unhandledRejection', err => {
  throw err;
});

require('../config/env');

const jest = require('jest');
const execSync = require('child_process').execSync;
let argv = process.argv.slice(2);

function isInGitRepository() {
  try {
    execSync('git rev-parse --is-inside-work-tree', { stdio: 'ignore' });
    return true;
  } catch (e) {
    return false;
  }
}

function isInMercurialRepository() {
  try {
    execSync('hg --cwd . root', { stdio: 'ignore' });
    return true;
  } catch (e) {
    return false;
  }
}

if (
  !process.env.CI &&
  argv.indexOf('--watchAll') === -1 &&
  argv.indexOf('--watchAll=false') === -1
) {
  const hasSourceControl = isInGitRepository() || isInMercurialRepository();
  argv.push(hasSourceControl ? '--watch' : '--watchAll');
}


jest.run(argv);
```
**App Setup**
```
<Provider store={store}>
    <React.StrictMode>
      <ThemeProvider>
        <MsalProvider instance={msalInstance}>
          <MsalAuthenticationTemplate
            interactionType={InteractionType.Redirect}
          >
            <BrowserRouter>
                <App />
            </BrowserRouter>
          </MsalAuthenticationTemplate>
        </MsalProvider>
      </ThemeProvider>
    </React.StrictMode>
  </Provider>,
  document.getElementById("root")
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by samuelkubai** [comment]
Hi @maddyjolly2112, could you shed more information on how exactly your are structuring your unit tests so as to best help answer your question.

**Comment by maddyjolly2112** [comment]
I have added the configs in the question

**Comment by tnorling** [comment]
@maddyjolly2112 This error is thrown when a state update occurs **after** the test has already completed. Most MSAL.js APIs are asynchronous and thus state is updated several times before stabilizing. To resolve this your tests will need to wait until all renders are complete before running your test assertions. The `react-testing-library` explains this in more detail in their FAQ [here](https://testing-library.com/docs/react-testing-library/faq). You can also take a look at [our unit tests for some examples](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-react/test), though be aware that our unit tests are mocking implementation details of the library (mostly events) which are subject to change and you should not rely on these details for your tests.

**Comment by maddyjolly2112** [comment]
I will have a look into it
