### ISSUE TITLE
MSAL.js login using link? 

### ISSUE THREAD

**Issue by oldorange** [AzureAD/microsoft-authentication-library-for-js#4268]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.18.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.1.0

### Description

Is it possible to log user in with id_token in url? 
I am developing a signin user journey to log user in using a link that sent to their email. When user click this link, B2C will issue an id_token and redirect user back to my react app with id_token in url param, but react app will not log user in.

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by tnorling** [comment]
@oldorange Please read instructions for implementing the invite flow [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/working-with-b2c.md#b2c-and-invite-flow) and let us know if you have further questions

**Comment by oldorange** [comment]
That make sense. Thank you!
