### ISSUE TITLE
Passport-Azure-Ad Authenticate Middleware Stopped Working

### ISSUE THREAD

**Issue by pjchungmd** [AzureAD/microsoft-authentication-library-for-js#4269]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.16.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.1

### Description

I have created an app that uses the Bearer strategy from `passport-azure-ad` (v4.3.0) virtually identical to the code presented in https://github.com/Azure-Samples/active-directory-javascript-nodejs-webapi-v2, which I implemented approximately 6 months ago. I have had no problems until about 2 weeks ago, when my API calls began to return 401. I have reverted my code back without success. When I disable the passport authenticate middleware, the API call works. My react app shows my login credentials and I can generate a token, and am passing that (this code was untouched and working without issue for almost the past 6 months). I have also not changed any settings on Azure AD.

I'm pretty much out of ideas as to what is wrong, and would appreciate help getting back on the right track. I am not sure if admins made a change to my Azure AD settings (I haven't), and frankly wouldn't know what to look for in order to correct this behavior.

### MSAL Configuration

```javascript
{
  auth: {
    clientId: "221121af-2dc7-4eb3-8081-7b1ae3cd3e01",
    authority: "https://login.microsoftonline.com/7f786e85-2b61-4bbe-a796-71e91e5e7e38",
    redirectUri: process.env.NODE_ENV === "development" 
      ? "http://localhost:3000"
      : "http://localhost:4000",
    postLogoutRedirectUri: process.env.NODE_ENV === "development" 
      ? "http://localhost:3000"
      : "http://localhost:4000",
  },
  cache: {
    cacheLocation: "localStorage", // This configures where your cache will be stored
    storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
  },
};
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by sameerag** [comment]
@pjchungmd Will you be able to share us logs and any fiddler trace you have? My email is available in my [profile](https://github.com/sameerag).
