### ISSUE TITLE
Calling `acquireTokenSilent` with `forceRefresh: true` does not give me updated roles.

### ISSUE THREAD

**Issue by vegarringdal** [AzureAD/microsoft-authentication-library-for-js#4273]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.3.3

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

Calling `acquireTokenSilent` with `forceRefresh: true` does not give me updated roles.
Anything special I need to do to, or is this a bug ?

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by sameerag** [comment]
Ideally it should. Can you help is with steps to reproduce this?

**Comment by vegarringdal** [comment]
Made a sample to reproduce... but then it worked..
Looks like it it might be a short delay in my main app, refreshes fine the 2nd time..
closing
