### ISSUE TITLE
AuthorityMetadata cache is lost after calling TokenCache.getAccountByHomeId() causing PublicClientApplication.acquireTokenSilent() very slow due to retrieving AuthorityMetadata on every call

### ISSUE THREAD

**Issue by a1exwang** [AzureAD/microsoft-authentication-library-for-js#4276]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

@azure/msal-node@1.3.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

n/a

## Actual behavior 

```
await publicClientApplication.acquireTokenSilent({
  account: account,
  scopes: scopes,
  forceRefresh: false,
}); // this is slow as expected because it needs to retrieve AuthorityMetdata

// here, publicClientApplication.storage.cache will be filled with 8 entries including "authority-metadata-xxxx"
// It seems that this method call will call beforeCacheAccess() and overwrite data in memory
await publicClientApplication.getTokenCache().getAccountByHomeId(accountCache);

// here, publicClientApplication.storage.cache will be filled with 6 entries without "authority-metadata-xxxx"

publicClientApplication.acquireTokenSilent({
  account: account,
  scopes: scopes,
  forceRefresh: false,
}); // this will be slow because AuthorityMetadata cache is gone
```

## Expected behavior
The second call to `acquireTokenSilent()` will not trigger HTTP request.

And my question is, what should I do to make the second call to `acquireTokenSilent()` hit the cache? I have to call `getAccountByHomeId()` between `acquireTokenSilent()` calls because of bussiness logic.

### MSAL Configuration

```javascript
const config = {
  auth: {
    clientId: "xxxxxxxxxxxxxxxxxxxxxxxxxx",
    authority: "https://login.microsoftonline.com/common",
  },
  system: {
    loggerOptions: {
      // @ts-ignore
      loggerCallback(loglevel, message, containsPii) {
      },
      piiLoggingEnabled: false,
      logLevel: LogLevel.Error,
    },
  },
  cache: {
    cachePlugin, // this is a simple file based plugin, similar to the sample code
  },
};
```

### Relevant Code Snippets

```javascript
See Description
```

### Reproduction Steps

See Description

### Expected Behavior

See Description

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Source

Internal (Microsoft)

**Comment by sameerag** [comment]
@a1exwang Thanks for raising this. Known issue and being fixed by #4081, the PR got delayed but will be prioritized soon.
