### ISSUE TITLE
MsalInterceptor causes timeout on AKS cluster

### ISSUE THREAD

**Issue by salttitan** [AzureAD/microsoft-authentication-library-for-js#4278]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.13.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.5

### Description

I have an Angular SPA that has been using msal-angular with passport-azure-ad for authentication for a couple of months now. About two weeks ago we had an issue that caused the AKS cluster to be restarted and after coming back up any calls to API endpoints in Node that are on MsalInterceptor's protected resources map causes a timeout when the app is hosted on the new clusters. No other applications on the cluster and there are no issues when the app is running on a local machine or when we move it to on-premises hosting.

Removing the /api/ endpoints from Protected Resources or disabling the Interceptor entirely works without any issues. Passport correctly throws an 'Unauthorized' error if I leave it enabled without the Interceptor in place. The cluster is running Ubuntu 18.04.1 Kernel Version 5.4.0-1063. I used the samples at [AzureSamples/ms-identity-javascript](https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial) to set up the configuration.

![error](https://user-images.githubusercontent.com/63205212/143044686-fda32c93-ae53-4374-a34d-a9c0149e4b77.png)

### MSAL Configuration

```javascript
auth: {
    clientId: environment.msalClientId,
    authority: environment.msalAuthority,
    redirectUri: environment.uiUrl
  },
  cache: {
    cacheLocation: BrowserCacheLocation.LocalStorage // Configures cache location. "sessionStorage" is more secure, but "localStorage" gives you SSO between tabs.

  },
  system: {
    loggerOptions: {
      loggerCallback(LogLevel: LogLevel, message: string) {
        console.log(message);
      },
      logLevel: LogLevel.Info,
      piiLoggingEnabled: false
    }
  }
}
```

### Relevant Code Snippets

```javascript
//auth-config.ts
export const protectedResources = {
  graphMe: {
      endpoint: "https://graph.microsoft.com/v1.0/me",
      scopes: ["User.Read"],
  },
  armTenants: {
      endpoint: "https://management.azure.com/tenants",
      scopes: ["https://management.azure.com/user_impersonation"],
  },
  ultron: {
    endpoint: "/api/ultron/",
    scopes: ['api://e4b0aaa6-1210-422c-8a05-4d9d5596f485/access_as_user']
  }
}

//app-module.ts
export function MSALInstanceFactory(): IPublicClientApplication {
  return new PublicClientApplication(msalConfig);
}

 export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
  const protectedResourceMap = new Map();

  protectedResourceMap.set(protectedResources.graphMe.endpoint, protectedResources.graphMe.scopes);
  protectedResourceMap.set(protectedResources.armTenants.endpoint, protectedResources.armTenants.scopes);
  protectedResourceMap.set(protectedResources.ultron.endpoint, protectedResources.ultron.scopes);

  return {
    interactionType: InteractionType.Popup,
    protectedResourceMap
  };
}
 export function MSALGuardConfigFactory(): MsalGuardConfiguration {
  return {
    interactionType: InteractionType.Popup,
    authRequest: loginRequest
  };
}

...

 providers: [
    {
      provide: HTTP_INTERCEPTORS,
      useClass: NoCacheHeadersInterceptor,
      multi: true
    },
    {
      provide: HTTP_INTERCEPTORS,
      useClass: ErrorIntercept,
      multi: true
    },
    {
      provide: HTTP_INTERCEPTORS,
      useClass: MsalInterceptor,
      multi: true
    },
    {
      provide: MSAL_INSTANCE,
      useFactory: MSALInstanceFactory
    },
    {
      provide: MSAL_GUARD_CONFIG,
      useFactory: MSALGuardConfigFactory
    },
    {
      provide: MSAL_INTERCEPTOR_CONFIG,
      useFactory: MSALInterceptorConfigFactory
    },
    MsalService,
    MsalGuard,
    MsalBroadcastService
  ],
  bootstrap: [AppComponent, MsalRedirectComponent]
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by tnorling** [comment]
@salttitan Can you please provide verbose level msal logs and a network trace? (Please email me the network trace)

Is the timeout occurring when acquiring a token or when calling the API with the token?

**Comment by salttitan** [comment]
@tnorling The timeout is occurring when calling the API with the token, the token is acquired successfully first. I emailed you the logs and network trace.

Thanks!

**Comment by tnorling** [comment]
@salttitan Thanks for sending those over. It looks like MSAL is doing everything it's supposed to; it's acquiring a token and attaching it to the HTTP request to your API. Unfortunately, everything that happens after is out of scope for this package. I see a few `net::ERR_CONNECTION_CLOSED` messages in the logs, have you tried debugging your API to determine if it's even receiving the request or if it's getting blocked before? I'd also suggest opening a ticket with AKS as this seems to be an issue caused by the restart, they may have a better answer for you.

**Comment by salttitan** [comment]
@tnorling The API isn't receiving the request when the endpoint is on the Protected Resources Map, but it works fine if it's not (or if we disable the MsalInterceptor entirely). That's why I thought it could be the Interceptor; it's only when the Interceptor steps in that we see those errors; unprotected endpoints are fine.

**Comment by tnorling** [comment]
The API request is made and the token is attached, so the interceptor is doing what it's expected to do. Have you tried making a request without the interceptor by manually attaching the access token yourself?

**Comment by salttitan** [comment]
@tnorling Looks like manually attaching the token doesn't work either, we're working with our AKS team now. Thank you for your help!
