### ISSUE TITLE
Cannot sign in with MSA using msal.js

### ISSUE THREAD

**Issue by davidsk** [AzureAD/microsoft-authentication-library-for-js#428]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 0.2.2
</code></pre>

## Current behavior
After selecting Microsoft account, the following error is returned:

> _The provided value for the input parameter 'redirect_uri' is not valid. The expected value is 'https://login.live.com/oauth20_desktop.srf' or a URL which matches the redirect URI registered for this client application_

The default value for redirect_uri is used and **does match** the value configured for the application.  If the app is run using a different host and / or port, the following error is generated.

> _AADB2C90006:The redirect URI 'http://127.0.0.1:8080/' provided in the request is not registered for the client id 'b205141d-8dac-4db7-8ea4-49e626fbdb41'_

## Expected behavior
On selecting the Microsoft Account login option, the user would be directed to provide credentials

## Minimal reproduction of the problem with instructions
```
git clone https://github.com/davidsk/azureb2c.git
npm install
live-server
```
This will generate an error because the redirect_uri does not match the configured value.  Running the app again but specifying the values for host and port...

`live-server --host=localhost --port=9000`

This will present the identity provider selection screen.  Selecting Microsoft Account will generate another error, "_We're unable to complete your request / Microsoft account is experiencing technical problems. Please try again later_".  Inspecting the values in the querystring shows that, again, there seems to be an issue matching the redirect_uri to that specified in the app registration.

**Comment by visualjeff** [comment]
Did you forget to provide a **redirectUri** in your settings?

**Comment by davidsk** [comment]
Do you mean in the code?  As I understand it, it's not required; if a redirectUri is not specified, it'll default to the current location.

**Comment by visualjeff** [comment]
Yes.

If the default (current location) matches what you've registered in Azure then I guess your fine.

**Comment by nehaagrawal** [comment]
@davidsk It seems there is some issue in your sample or app registration. I was able to login using MSA account(my personal live account) using this sample https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/na/quickstart/lib/msal-core/samples/quickStart  . Can you please try this sample and let me know if it works for you.

**Comment by davidsk** [comment]
The quickStart sample works even when I substitute in my app values.  However, it's not using a b2c policy.  If I pass null rather than the policy in my original code, then I am prompted to select an MSA account.

The issue seems to be with the policy itself, I'll raise an issue against b2c
