### ISSUE TITLE
How to use azure login using electron and angular

### ISSUE THREAD

**Issue by ms1832** [AzureAD/microsoft-authentication-library-for-js#4281]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.19.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.0

### Description

I am trying to implement azure authentication in my electron application, I already created an angular app where all works fine so when the application loads it redirected to azure login page and if auth is done it will redirect back to application I am using msal-angular.

Now I am converting this application to the electron.
In electron, load the dist folder of angular.
After successful login, need to redirect to application, but shows invalid schema error because of file:// schema is there in redirect uri.
also can't register that schema to azure portal.

so, how can we redirect to application.

### Relevant Code Snippets

```javascript
// in main.js (electron)
mainWindow.loadURL(url.format({
        pathname: path.join(__dirname, 'dist/index.html'),
        protocol: 'file:',
        slashes: true,
    }));

// in angular app
redirectUri: '/'
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by sameerag** [comment]
@ms1832 Did you check our electron sample (though it is on the server end) for the `redirectUri` usage? The sample can be accessed [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/ElectronTestApp)

**Comment by ms1832** [comment]
@sameerag  yes, I have checked and it works.

But i am thinking of below two approaches :

1.  Is there any solution that, can use custom redirect uri (msal://auth) to angular (implement login using msal-angular) and handle that redirection to electron side.

2. If use login on electron side (using msal-node) [here,](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/ElectronTestApp) then i want to use the token and account-info in angular app.
     So, how can i get these to angular app ?

**Comment by jasonnutter** [comment]
@ms1832 

1. Unfortunately, I don't believe that is currently supported.
2. You can try using the `loadExternalTokens` API to load tokens into MSAL Angular that were acquired in MSAL Node: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/testing.md#the-loadexternaltokens-api
