### ISSUE TITLE
Update acquireTokenSilent to recoginize and use given extraQueryParameters

### ISSUE THREAD

**Issue by saragibby** [AzureAD/microsoft-authentication-library-for-js#4291]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL React (@azure/msal-react)

### Description

Calling `acquireTokenSilent` from my MSAL instance within React app. Passing `extraQueryParameters` to this request so that I can append the `safe_rollout` query parameter to this request for our application registration.

From reading the code, I see that `acquireTokenSilent` takes a [SilentRequest ](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/src/request/SilentRequest.ts )object. So it accepts that additional parameter with no error, but in readin the code for the [`acquireTokenSilent` function](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/src/app/PublicClientApplication.ts#L86) it does nto appear to utilize the `extraQueryParameters` object. 

Without this in place, I'm unable to utilize the gradual rollout for our applicaiton without the `safe_rollout` parameter being passed to the token request.

Would be helpful if `extraQueryParameters` would spread within `const thumbprint: RequestThumbprint = {....` or had a list of allowable additional fields to use within `extraQueryParameters` such as `safe_rollout`.

### Source

Internal (Microsoft)

**Comment by jasonnutter** [comment]
@saragibby For `acquireTokenSilent`,  `extraQueryParameters` will be passed to the `/authorize` endpoint (if called, e.g. for RT renewal), while `tokenQueryParameters` will be passed on the `/token` endpoint. Please try passing `safe_rollout` in the `tokenQueryParameters` parameter object and let us know if that works, thanks!

**Comment by saragibby** [comment]
@jasonnutter that was it! Thank you for your quick response and help. When I call `loginRedirect` I have it now set to pas both `extraQueryParameters` and `tokenQueryParameters` which seems to do the trick to handle the authentication and fetch of token in the case where I need to `safe_rollout` to pass into both. 

When calling `acquireTokenSilent` I have added only `tokenQueryParameters` (no `extraQueryParameters`) and can see in the refresh token request the `safe_rollout` query param being passed in and used.
