### ISSUE TITLE
Angular app using MSAL library v2 shows the login page after reloading the page

### ISSUE THREAD

**Issue by Arash-Sabet** [AzureAD/microsoft-authentication-library-for-js#4292]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.0.5

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

13.0.2

### Description

I am able to log in and use the app successfully but when I refresh the page, the sign-in prompt shows up to get the user signed in. What is missing in this configuration or what should be done to prevent showing the login prompt?

### MSAL Configuration

```javascript
export const msalConfig: Configuration = {
    auth: {
        clientId: 'MaskedClientId', // This is the ONLY mandatory field that you need to supply.
        authority: b2cPolicies.authorities.signUpSignIn.authority, // Defaults to "https://login.microsoftonline.com/common"
        knownAuthorities: [b2cPolicies.authorityDomain], // Mark your B2C tenant's domain as trusted.
        redirectUri: 'http://localhost:4200', // Points to window.location.origin. You must register this URI on Azure portal/App Registration.
        postLogoutRedirectUri: 'http://localhost:4200', // Indicates the page to navigate after logout.
        navigateToLoginRequestUrl: true, // If "true", will navigate back to the original request location before processing the auth code response.
    },
    cache: {
        cacheLocation: BrowserCacheLocation.LocalStorage, // Configures cache location. "sessionStorage" is more secure, but "localStorage" gives you SSO between tabs.
        storeAuthStateInCookie: isIE, // Set this to "true" if you are having issues on IE11 or Edge
    },
    system: {
        loggerOptions: {
            loggerCallback(logLevel: LogLevel, message: string) {
                console.log(message);
            },
            logLevel: LogLevel.Verbose,
            piiLoggingEnabled: false
        }
    }
}
```

### Identity Provider

Azure B2C Basic Policy

### Source

Internal (Microsoft)

**Comment by sameerag** [comment]
@Arash-Sabet Do you mean that every time you refresh the page are you prompted the login screen? Can you please share the steps to repro in detail, preferably with our angular [sample]() along with the usage details - Calling pattern, MSAL Angular configuration MSAL interceptor and MSAL guard?

Please also provide us verbose logs preferably, since that would help us get more detail here.

**Comment by Arash-Sabet** [comment]
@sameerag Please share your email address so that I can direct you to a live website that exhibits this issue. Thanks.

**Comment by sameerag** [comment]
@Arash-Sabet My email is available in my [profile](https://github.com/sameerag)

**Comment by Arash-Sabet** [comment]
@ sameerag I just invited to a private repo on Github.

**Comment by Arash-Sabet** [comment]
@sameerag Just wondering, did you have a chance to accept the repo invitation request that I sent you a few days ago?

**Comment by sameerag** [comment]
@Arash-Sabet Yes, can you please share it with @jasonnutter as he is working on this? His email is accessible in his profile. Apologies for the delayed notice.

**Comment by Arash-Sabet** [comment]
@jasonnutter I shared a private repo with you and sent you an invitation to it. Thanks for your help in advance.

**Comment by jasonnutter** [comment]
@Arash-Sabet I was not able to run the app, but from looking at the code, it does not look like you are properly handling redirect requests via the `MsalRedirectComponent` or `handleRedirectObservable`. Please [this document](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/redirects.md) for details on how to do that, and you can look at our [samples](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples) as well.

**Comment by Arash-Sabet** [comment]
@jasonnutter Thanks for the feedback. Sorry that you could not run the code. If you run "npm install" and then "ng serve" it has to work. You could also choose to sign up within sign-in popup box.

Regardless, I will review the document to figure out what may have been wrong.

/cc @milad-ghafoori

**Comment by jasonnutter** [comment]
> @jasonnutter Jason Nutter FTE Thanks for the feedback. Sorry that you could not run the code. If you run "npm install" and then "ng serve" it has to work. You could also choose to sign up within sign-in popup box.
> 
> Regardless, I will review the document to figure out what may have been wrong.
> 
> /cc @milad-ghafoori

The application was missing a number of important files, e.g. `tsconfig.json`, etc.

**Comment by Arash-Sabet** [comment]
@jasonnutter I will look into adding those missing files. Regardless, I am closing this ticket as the issue resolved after configuring MSAL per your guidance.
