### ISSUE TITLE
Endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientAuthError: openid_config_error

### ISSUE THREAD

**Issue by xiaolang124** [AzureAD/microsoft-authentication-library-for-js#4293]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.3.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

https://github.com/OfficeDev/TeamsFx/issues/3174

I use pca.acquireTokenSilent to get accessToken, but need to restart multi times to login successfully. This is the error that user has encountered.
```
[Error] - [Login] Failed to retrieve token silently: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientAuthError: openid_config_error: Could not retrieve endpoints. Check your authority and verify the .well-known/openid-configuration endpoint returns the required endpoints. Attempted to retrieve endpoints from: https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration
```

Do you have any idea why this happens?

### Error Message

[Error] - [Login] Failed to retrieve token silently: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientAuthError: openid_config_error: Could not retrieve endpoints. Check your authority and verify the .well-known/openid-configuration endpoint returns the required endpoints. Attempted to retrieve endpoints from: https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration

### MSAL Configuration

```javascript
{
  auth: {
    clientId: "7ea7c24c-b1f6-4a20-9d11-9ae12e9e7ac0",
    authority: "https://login.microsoftonline.com/common",
  },
  system: {
    loggerOptions: {
      // @ts-ignore
      loggerCallback(loglevel, message, containsPii) {
        if (loglevel <= LogLevel.Error) {
          VsCodeLogInstance.error(message);
        }
      },
      piiLoggingEnabled: false,
      logLevel: LogLevel.Error,
    },
  },
  cache: {
    cachePlugin,
  },
}
```

### Relevant Code Snippets

```javascript
return this.pca!.acquireTokenSilent({
          account: this.account,
          scopes: this.scopes!,
          forceRefresh: false,
        })
          .then((response) => {
            if (response) {
              return response.accessToken;
            } else {
              return undefined;
            }
          })
          .catch(async (error) => {
            VsCodeLogInstance.error(
              "[Login] " +
                stringUtil.format(
                  StringResources.vsc.codeFlowLogin.silentAcquireToken,
                  error.message
                )
            );
            await this.logout();
            if (refresh) {
              const accessToken = await this.login();
              return accessToken;
            }
            return undefined;
          });
```

### Reproduction Steps

1. Create a teams tab app hosted on azure using the vscode extension.
2. Launch a debug session ("Debug (Chrome)").
3. Login in the popup (multiple popups).

### Expected Behavior

Can get access token silently.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by sameerag** [comment]
@xiaolang124 Are you using any proxy in your configuration?

**Comment by xiaolang124** [comment]
The user does not use a proxy, and he can open https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration directly.

Any idea why this happens and how to bypass this?

OfficeDev/TeamsFx#3174

**Comment by xiaolang124** [comment]
Hi, any update information? Thanks

**Comment by vs4vijay** [comment]
This issue is very frequent seen in our services as well... Initially we were using proxy then we removed the proxy, still this issue is coming and it is intermittent. Can somebody provide the solution?

@sameerag

**Comment by jo-arroyo** [comment]
@xiaolang124 Please email us a Fiddler trace of this behavior so we can look into it further. My email can be found in my profile.
