### ISSUE TITLE
Can't get response from sdk on web application

### ISSUE THREAD

**Issue by byang35** [AzureAD/microsoft-authentication-library-for-js#4297]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

2.14.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

We use @azure/msal-node to get authority for my teams,
We encountered an unknown situation and were unable to get the response when we change a new environment,
And i sure my config is correct
```
const authCodeUrlParameters = {
   scopes: azureConfig.scopes,
   redirectUri: azureConfig.redirectUri,
}
azure.getAuthCodeUrl(authCodeUrlParameters).then(response => {
   res.redirect(response)
})
```
No specific information is displayed in the log, the last log is the follow
`Verbose - createAuthoritycalled`
and the request is pending for one min then it send error 
`504 Gateway Time-out`

### Source

External (Customer)

**Comment by sameerag** [comment]
@byang35 Can you please share your `Configuration` and fiddlers trace if possible? You can share the trace to via email in my profile.

**Comment by byang35** [comment]
@sameerag 
```javascript
const conf = {
  auth: {
    clientId: azureConfig.clientId,  // b16c0d46-7854-4853-88ed-e9f63a84b366
    authority: azureConfig.authority,  // https://login.partner.microsoftonline.cn/eda1781b-14c5-47c4-aba3-766a6f3a50fd
    clientSecret: azureConfig.clientSecret,
  },
  system: {
    loggerOptions: {
      loggerCallback(loglevel, message) {
        logger.log(loglevel, message)
      },
      piiLoggingEnabled: false,
      logLevel: azure.LogLevel.Verbose,
    },
  },
}

**Comment by byang35** [comment]
@sameerag 
I send the fiddler trace for you, please check it

**Comment by sameerag** [comment]
@byang35 I checked the trace but see only one packet which is a not the microsoft authority you mentioned above. I have tested the well known endpoint to make sure the authority is valid and it does return valid values:
>> (https://login.partner.microsoftonline.cn/eda1781b-14c5-47c4-aba3-766a6f3a50fd/.well-known/openid-configuration

I would need a couple things to proceed:
* A fiddler trace and/or verbose MSAL JS logs capturing the auth flow from the start
* Detailed steps for reproducing on our end
