### ISSUE TITLE
Feature Request: Provide ability to add to trusted host list

### ISSUE THREAD

**Issue by bh3605** [AzureAD/microsoft-authentication-library-for-js#430]
## I'm submitting a...

<pre><code>
[x ] Feature request
</code></pre>

## Browser:
N/A

## Library version

<pre><code>
Library version: 0.2.2

## Current behavior
Providing any host not contained in the trusted host list throws UnsupportedAuthorityValidation error
AadAuthority.TrustedHostList = {
        "login.windows.net": "login.windows.net",
        "login.chinacloudapi.cn": "login.chinacloudapi.cn",
        "login.cloudgovapi.us": "login.cloudgovapi.us",
        "login.microsoftonline.com": "login.microsoftonline.com",
        "login.microsoftonline.de": "login.microsoftonline.de",
        "login.microsoftonline.us": "login.microsoftonline.us"
    };

## Expected behavior
Add ability to add to the trusted host list and validate the supplied host to show it is trusted and can be used as a trusted host.

## Minimal reproduction of the problem with instructions
Use any host not contained in the trusted host list that IS a trusted host.

</code></pre>

**Comment by navyasric** [comment]
@bh3605 MSAL is a client library for authenticating with the Azure AD service. As such, the trusted host list is a list of valid authorities maintained by the MSAL library by validating and checking with the Azure AD service. Hence, we do not plan to expose the list for supplying new authority endpoints (which may not exist on the AAD service).
