### ISSUE TITLE
npm >=7 + angular 13: unable to resolve dependency tree

### ISSUE THREAD

**Issue by eXXeption** [AzureAD/microsoft-authentication-library-for-js#4300]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

-

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.5

### Description

When using the current Version of angular, angular uses rxjs >7.
@azure/msal-angular uses rxjs 6 as a peer dependency.
Since NPM >=7 the npm install will fail for mismatched peer dependencies for direct project dependencies.

### Error Message

66 error ERESOLVE unable to resolve dependency tree

68 error Found: rxjs@7.4.0
68 error node_modules/rxjs
68 error   rxjs@"~7.4.0" from the root project
68 error
68 error Could not resolve dependency:
68 error peer rxjs@"^6.0.0" from @azure/msal-angular@2.0.5

### MSAL Configuration

```javascript
-
```

### Relevant Code Snippets

```javascript
"@angular/animations": "~13.0.0",
    "@angular/common": "~13.0.0",
    "@angular/compiler": "~13.0.0",
    "@angular/core": "~13.0.0",
    "@angular/forms": "~13.0.0",
    "@angular/platform-browser": "~13.0.0",
    "@angular/platform-browser-dynamic": "~13.0.0",
    "@angular/router": "~13.0.0",
    "@azure/msal-angular": "^2.0.2",
    "@azure/msal-browser": "^2.16.0",
    "rxjs": "~7.4.0",
```

### Reproduction Steps

Update Node to the current LTS.
Create a Project with a current Angular version.
Add MSAL/angular
NPM install

### Expected Behavior

Successful npm install with correct peer dependencies.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Other

### Source

External (Customer)

**Comment by slubowsky** [comment]
see #4154

**Comment by jasonnutter** [comment]
We are aware of the issues with Angular 13 and rxjs 7, and so will close this as a duplicate. Thanks!
