### ISSUE TITLE
ssoslient will sometimes return "monitor_window_timeout" error

### ISSUE THREAD

**Issue by KennethBWSong** [AzureAD/microsoft-authentication-library-for-js#4303]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.19.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

When calling msalInstance.ssoSlient() in teams app, sometimes will return "monitor_window_timeout" error.  This can not always reproduce. We want to figure out the root cause of this problem.

### Error Message

Token acquisition in iframe failed due to timeout.

### Msal Logs

![image](https://user-images.githubusercontent.com/63089166/144811085-b390f3ba-c00d-4368-9a00-c3237fe2ee41.png)

### MSAL Configuration

```javascript
const msalConfig = {
      auth: {
        clientId: clientId!,
        authority: authority,
        redirectUri: redirectUri,
        navigateToLoginRequestUrl: false
      },
      cache: {
        cacheLocation: "sessionStorage",
        storeAuthStateInCookie: false,
      }
    };
```

### Relevant Code Snippets

```javascript
/
```

### Reproduction Steps

/

### Expected Behavior

Can always success

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Other

### Source

Internal (Microsoft)

**Comment by jasonnutter** [comment]
@KennethBWSong Do you have a correlation id and timestamp of a request you can share? Thanks!

**Comment by KennethBWSong** [comment]
Hi @jasonnutter. Thank you for your reply. I reproduce the error today and here is the request info:

Date: Wed, 08 Dec 2021 01:34:05 GMT
x-ms-request-id: 98fea366-2a34-4a93-a5ee-2ce86df61e00

**Comment by jasonnutter** [comment]
@KennethBWSong Thanks. This request timed out due to throttling, meaning your app was making too many calls for the same user in a short amount of time. When your Teams app gets a timeout like this, we recommend invoking an interactive request to complete authentication, as shown in [this sample](https://github.com/pnp/teams-dev-samples/blob/main/samples/tab-sso/src/nodejs/src/components/Tab.js#L120).
