### ISSUE TITLE
Unexpected account in 

### ISSUE THREAD

**Issue by Coach-BWise** [AzureAD/microsoft-authentication-library-for-js#4311]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.19.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

When I call pca.getAllAccounts(). I'm not getting the expected response. Specifically, the account I get back has an audience that does not match what I intended. the acquireToken() method returns InteractionRequiredAuthError

### MSAL Configuration

```javascript
const msalConfig = {
  auth: {
    clientId: process.env.VUE_APP_AZURE_AD_CLIENT_ID,
    authority: process.env.VUE_APP_AZURE_AD_AUTHORITY,
  },
  cache: {
    cacheLocation: 'localStorage',
    storeAuthStateInCookie: true,
  },
  system: {
    loadFrameTimeout: 30000,
    logger: new msal.Logger(msalLoggingCallback),
  },
}
```

### Relevant Code Snippets

```javascript
export default class AppAuth {
  authenticationContext
  tokenRequest
  constructor() {
    this.authenticationContext = new msal.PublicClientApplication(msalConfig)
    let accounts = this.authenticationContext.getAllAccounts()
/*
here when I log accounts, the account I get has the wrong audience (does not match my msalConfig.auth.clientId like I'd expect)
*/
    console.log(this.authenticationContext, accounts)
    if (accounts.length > 0) {
      this.authenticationContext.setActiveAccount(accounts[0])
      this.tokenRequest = {
        scopes: [`'${msalConfig.auth.clientId}/.default'`],
        account: this.authenticationContext.getActiveAccount(),
      }
    }
  }

 async acquireToken() {
    return new Promise((resolve, reject) => {
     return this.authenticationContext
        .acquireTokenSilent(this.tokenRequest)
        .then((token) => {
         resolve(token)
        })
        .catch((error) => {
          if (error instanceof InteractionRequiredAuthError) {
            // fallback to interaction when silent call fails
            return this.authenticationContext.acquireTokenRedirect(
              this.tokenRequest
            )
          } else {
            console.log(error)
            reject()
          }
        })
    })
  }
```

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@Coach-BWise Can you please clarify what you mean by "audience"? Are you referring to the "aud" claim in the id token for the account, or a different claim?

**Comment by Coach-BWise** [comment]
> @Coach-BWise Can you please clarify what you mean by "audience"? Are you referring to the "aud" claim in the id token for the account, or a different claim?

yes the aud claim

**Comment by jasonnutter** [comment]
Do you have other apps that use MSAL running on the same domain (this can easily happen with localhost). And does this happen if you manually clear the MSAL cache and then relogin, or in a private window?

**Comment by Coach-BWise** [comment]
> Do you have other apps that use MSAL running on the same domain (this can easily happen with localhost). And does this happen if you manually clear the MSAL cache and then relogin, or in a private window?

I have tested this in incognito (using chrome) and this still occurs

**Comment by Coach-BWise** [comment]
to further add: 
the idTokenClaims: 
aud: 
shows an id that i'm not expecting.
the name: is my account however
i'm expecting the aud: to match my "clientId" that i have set in .env

**Comment by Coach-BWise** [comment]
I believe the account is the problem, but maybe I'm confused. Below is the error being thrown:

InteractionRequiredAuthError: no_tokens_found: No refresh token found in the cache. Please sign-in.

I'm expecting to receive a token which I can then add to the header of an api call.

**Comment by jasonnutter** [comment]
If you can please record and share a fiddler tracer (via my email on my profile), that would be helpful. And please clear the local storage cache before doing so.

> InteractionRequiredAuthError: no_tokens_found: No refresh token found in the cache. Please sign-in.


This error happens when your app invokes `acquireTokenSilent` without a refresh token in the cache, i.e. the user hasn't logged in to your application yet. Invoking an interactive method will resolve.

**Comment by Coach-BWise** [comment]
.catch((error) => {
          if (error instanceof InteractionRequiredAuthError) {
            // fallback to interaction when silent call fails
            return this.authenticationContext.acquireTokenRedirect(
              this.tokenRequest
            )
          } else {
            console.log(error)
            reject()
          }
        })
        
        I am noticing that with the above part of the code the if statement is returning false so my fallback never happens. 
        I would expect this to return true because the error is:
        InteractionRequiredAuthError: no_tokens_found: No refresh token found in the cache. Please sign-in.

**Comment by Coach-BWise** [comment]
> If you can please record and share a fiddler tracer (via my email on my profile), that would be helpful. And please clear the local storage cache before doing so.

I did email you regarding Fiddler; I'm not sure how exactly to get you the information from there. (exporting didn't seem to work)

**Comment by Coach-BWise** [comment]
if I force my .catch(error) to evaluate to true, the .acquireTokenRedirect(this.tokenRequest) gives me a new webpage with the following error:

AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope '16e28010-7f37-4d12-a695-3f94b705be1f/.default' openid profile offline_access is not valid. The scope format is invalid. Scope must be in a valid URI form <https://example/scope> or a valid Guid <guid/scope>.

**Comment by Coach-BWise** [comment]
As a side note: i am running this in a container app. I am authenticated to enter the container app. I then need a separate authentication to hit certain API's. I hope this is making sense.

**Comment by jasonnutter** [comment]
@Coach-BWise Thanks for sharing the trace. The `aud` claim of the id token in the response from the `/token` endpoint matched your client id, which means it is working as expected.
