### ISSUE TITLE
RedirectRequest for login should not require scopes

### ISSUE THREAD

**Issue by Shyam268** [AzureAD/microsoft-authentication-library-for-js#4312]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.18.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

"@azure/msal-react": "^1.1.0",

### Description

not able to implement forgot password policy. and it throws error to provide scopes why its required here ? i thought 
     let req:RedirectRequest = {authority: 'https://mytenent.b2clogin.com/mytenent.onmicrosoft.com/B2C_passwordreset_policy',
      }
        AuthConfig.getMsalInstance().loginRedirect(req);
      }

this should work.
but it always redirect to login page

### MSAL Configuration

```javascript
const msalConfig: Configuration = {
        auth: {
          clientId: config.authConfig.clientId,
          authority: "https://mytenent.b2clogin.com/mytenent.onmicrosoft.com/B2C_signin_policy"
          redirectUri: config.authConfig.redirectUri,
          navigateToLoginRequestUrl: true,
          knownAuthorities: ["mytenent.b2clogin.com"]
        },
        cache: {
          cacheLocation: "localStorage",
          storeAuthStateInCookie: true
        },
        system: {
          tokenRenewalOffsetSeconds: 300
        }
      };
```

### Relevant Code Snippets

```javascript
AuthConfig.getMsalInstance().addEventCallback((event: EventMessage) => {
  if (event.eventType === EventType.LOGIN_SUCCESS && event.payload) {
      const payload = event.payload as AuthenticationResult;
      const account = payload.account;
      AuthConfig.getMsalInstance().setActiveAccount(account);
  }
  if (event.eventType === EventType.LOGIN_FAILURE) {
    if (event.error && event.error.message.indexOf("AADB2C90118") > -1) {
      if (event.interactionType === InteractionType.Redirect) {
        
        let req:RedirectRequest = {authority: 'https://mytenent.b2clogin.com/mytenent.onmicrosoft.com/B2C_passwordreset_policy',
      }
        AuthConfig.getMsalInstance().loginRedirect(req);
      }
    }
  }
});
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@Shyam268 Can you please clarify the exact error message you are getting? And can you please provide verbose logs from MSAL? Thanks!

**Comment by Shyam268** [comment]
i tried to implement forgot password with this snippent

`
AuthConfig.getMsalInstance().addEventCallback((event: EventMessage) => {
  if (event.eventType === EventType.LOGIN_SUCCESS && event.payload) {
      const payload = event.payload as AuthenticationResult;
      const account = payload.account;
      AuthConfig.getMsalInstance().setActiveAccount(account);
  }
  if (event.eventType === EventType.LOGIN_FAILURE) {
    if (event.error && event.error.message.indexOf("AADB2C90118") > -1) {
      if (event.interactionType === InteractionType.Redirect) {
        let req:RedirectRequest = {authority: 'https://mytenent.b2clogin.com/mytenent.onmicrosoft.com/passwordreset_policy'}
        AuthConfig.getMsalInstance().loginRedirect(req);
      }
    }
  }
 }`


it returns compilation error saying that "Type '{ authority: string; }' is not assignable to type 'RedirectRequest'.
  Property 'scopes' is missing in type '{ authority: string; }' but required in type '{ scopes: string[]; redirectStartPage?: string | undefined; onRedirectNavigate?: ((url: string) => boolean | void) | undefined; }'". i dont know why scope is needed here.? will you provide any example to implement "forgot password policy " behaviour

**Comment by jasonnutter** [comment]
@Shyam268 We can look at fixing the types, as scopes shouldn't be needed for login, but can you try adding a blank array for scopes to fix the typescript warning?

```typescript
let req:RedirectRequest = {
  authority: 'https://mytenent.b2clogin.com/mytenent.onmicrosoft.com/passwordreset_policy',
  scopes: [] // can also set to [ "openid", "profile" ]
}
```

**Comment by Shyam268** [comment]
I tried with empty array and when i click forget password it always redirect to the same page
which is 
![image](https://user-images.githubusercontent.com/30112490/147546936-e5b64008-1014-4c7d-bce1-f34fc3f8bdfc.png)

please provide any example which works with react typescript

**Comment by jasonnutter** [comment]
> I tried with empty array and when i click forget password it always redirect to the same page which is ![image](https://user-images.githubusercontent.com/30112490/147546936-e5b64008-1014-4c7d-bce1-f34fc3f8bdfc.png)
> 
> please provide any example which works with react typescript

Okay, that seems like an issue with your password reset policy then? Is this a standard or custom policy?

**Comment by Shyam268** [comment]
It is a standard policy . the forgot password policy works for other projects

**Comment by sameerag** [comment]
@Shyam268 Does the linked issue solve your case?

**Comment by Shyam268** [comment]
No can we have any working example

**Comment by derisen** [comment]
@Shyam268 apologies for the late response, is this still an issue? You can see a working example in this [PR ](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/5015) (the Angular sample in particular)
