### ISSUE TITLE
Unable to fetch renewed token when opened in multiple tabs

### ISSUE THREAD

**Issue by sujithgundlapalli** [AzureAD/microsoft-authentication-library-for-js#4319]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

1.3.4

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

1.1.1

### Description

when we open only one tab.. token renewal happens perfectly (we are doing it before 5 min of expiry).
But. when we open app in multiple tabs (~6), our token expiry check runs in all tabs and tries to renew token. In this process only one or two tabs renew token correctly using acquiretokensilent with renewed expiry time of 60 min, where as remaining tabs are not able to get the renewed token, instead taking old token and subsequently logging out of app due to token expiry.

### MSAL Configuration

```javascript
MsalModule.forRoot(
      {
        auth: {
          clientId: `${environment.adalClientId}`,
          authority: `${environment.adalTenant}`,
          redirectUri: `${environment.adalRedirectURL}`,
          postLogoutRedirectUri: `${environment.adalRedirectURL}` //logout`
        },
        cache: {
          cacheLocation: 'localStorage',
          storeAuthStateInCookie: isIE // Set this to "true" if you are having issues on IE11 or Edge
        },
        system: {
          loadFrameTimeout: 30000,
          tokenRenewalOffsetSeconds: 480
        }
      }
```

### Relevant Code Snippets

```javascript
this.timer = timer(0, 1000 * 60).subscribe(() =>
fireInterval()
);

private get expireMinutes(): number {
const account = this.msalService.getAccount();
if (!account) return 0;

const exp = account.idTokenClaims['exp'];
//const exp = +account.idToken.exp;

if (!exp) return 0;

const expireDate = new Date(0);

expireDate.setUTCSeconds(+exp);
const now = new Date();
const minutesToExpire = Math.trunc((+expireDate - +now) / 1000 / 60);

if (minutesToExpire % 10 == 0)
console.log(this.cycleCount, expireDate, minutesToExpire);
return minutesToExpire;
}

private fireInterval() {
let expMinutes = this.expireMinutes;
if (expMinutes < 6)
this.renewToken()
else if (expMinutes < 0)
this.logout();
}

public renewToken(): Promise<AuthResponse> {
const loginRequest = {
scopes: [`${environment.adalClientId}`]
//loginHint: this.Account.user
};

return this.msalService.acquireTokenSilent(loginRequest)
.then((response : AuthResponse) => {
console.log('response after Silent renew', response)
if(!!response)
{
let minutesToExpire = this.expireMinutes;
if (minutesToExpire < 5)
{
console.log('Silent token renewal failed')
return this.msalService.acquireTokenPopup(loginRequest)
}
}
else
{
return this.msalService.acquireTokenPopup(loginRequest)
}
})
.catch(err => {
console.log('acquireTokenSilent failed', err)
return this.msalService.acquireTokenPopup(loginRequest)
});
}
```

Tab : 1 (token renewed)
![image](https://user-images.githubusercontent.com/41381361/145465130-d5a06429-e897-467d-a116-d1f90d2ac0e2.png)

Tab : 2 (token not renewed - and logged out )
![image](https://user-images.githubusercontent.com/41381361/145465468-0327cb88-0f29-43d1-ba6d-d0e4e74abb90.png)

### Reproduction Steps

Triggering expiry check of token every one minute.
if expiry is less than 5 min, renewing with acquireTokenSilent, if it still fails then using acquireTokenPopup to acquire token
Logging out when token is expired or total idle time of app is 8 hrs (counting in a local storage variable), 

### Expected Behavior

Renewed token from any of the tab should be read by all other tabs so that user will not be logged out in any tab and subsequently from the app.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@Sujith2020 Does this happen if you set `cache.cacheLocation` to `sessionStorage`?

**Comment by sujithgundlapalli** [comment]
with sessionStorage, I have tested and its working fine for 8hr (app requirement), but can we find the issue with local storage.

**Comment by jasonnutter** [comment]
This is likely fixed in MSAL Angular v2, which does a better job of handling concurrent token requests. Please try updating to MSAL.js v2 and MSAL Angular v2 and let us know if this is still an issue: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/v1-v2-upgrade-guide.md
