### ISSUE TITLE
Wrong installation instruction in readme for msal-angular

### ISSUE THREAD

**Issue by jplette** [AzureAD/microsoft-authentication-library-for-js#432]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 0.1.2

## Current behavior

In the readme you describe the npm installation:
npm install msal-angular --save

This is the wrong library! It is an old library not from microsoft

## Expected behavior

Update the installation instructions

## Minimal reproduction of the problem with instructions

</code></pre>

**Comment by nehaagrawal** [comment]
fixed
