### ISSUE TITLE
[Mac-SAFARI] Continuous Redirect is happening in Mac Safari with redirect flow in angular SPA

### ISSUE THREAD

**Issue by hitkumar25** [AzureAD/microsoft-authentication-library-for-js#4321]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.18.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.4

### Description

After the token is acquired. It redirects again and again in loop while using msal-angular in Angular v9 SPA.

### MSAL Configuration

```javascript
msalConfig: {
        auth: {
            clientId: '*******************',
            authority: 'https://login.microsoftonline.com/microsoft.com',
            redirectUri: `${location.origin}/iv`,
            postLogoutRedirectUri: `${location.origin}/iv/login`,
        },
        cache: {
            cacheLocation: 'localStorage',
            storeAuthStateInCookie: false,
        },
    },
```

### Relevant Code Snippets

```javascript
private handleUnAuthenticatedUser(observer: Observer<OAuthData>, resource: string): void {
        const redirectStartPage = window.location.href;
        this.msalBroadcastService.inProgress$
            .pipe(
                filter((status: InteractionStatus) => status === InteractionStatus.None),
            )
            .subscribe(() => {
                const activeAccount = this.msalService.instance.getActiveAccount();
                if (activeAccount) {
                    // If interaction got completed and in between Login is Successful then acquire token silently.
                    this.acquireTokenSilently(observer, resource, activeAccount);
                } else {
                    // If interaction got completed and still no account set then acquire token interactively.
                    this.msalService.acquireTokenRedirect({ scopes: [resource], redirectStartPage });
                }
            })
    }
```

### Reproduction Steps

1. Go to root URL.
2. It will redirect (not visible though) to login.microsoft.online.com and get the /#code= in the url.
3. #code is removed from the URl and it again redirects get the code and same again on loop

### Expected Behavior

It should redirect only once and then settle down.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Safari

### Source

Internal (Microsoft)

**Comment by jasonnutter** [comment]
@hitkumar25 Is your app invoking `handleRedirectObservable` or using the `MsalRedirectComponent`? This is required when using redirects for interaction. Docs: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/redirects.md
