### ISSUE TITLE
Module can't be resolved

### ISSUE THREAD

**Issue by jplette** [AzureAD/microsoft-authentication-library-for-js#433]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: @azure/msal-angular 0.1.2

## Current behavior

After updating to current version @azure/msal-angular 0.1.2 the the module can't be resolved anymore.
When importing the module with 

import { MsalModule } from '@azure/msal-angular';

the module isn't found.

"Cannot find module '@azure/msal-angular'".

Maybe the package has wrong typings or is not a correct es6 module

## Expected behavior

Provide a working NPM-Module. 

## Minimal reproduction of the problem with instructions

Create a new angular project. Install @azure/msal-angular version 1.1.2
Try to import the npm package in app.module.ts

</code></pre>

**Comment by nehaagrawal** [comment]
@jplette I am not able to reproduce this issue. Our samples works just fine with @azure/msal-angular version 0.1.2. Could you please check how your app.module is different from our samples? I have a feeling that your code could be failing because of the breaking change for protectedResourceMap which was introduced in version 0.1.2 to fix the AOT issue. Since you are at Microsoft, let's connect over email and I can help you.

**Comment by jplette** [comment]
Sorry about that. After all I uninstalled the old library and installed the new library again and now it works. Maybe my VSCode made some problems. Sorry making unnecessary trouble. Thank you

**Comment by kkwere** [comment]
I am experiencing this issue, but it only occurs in vsts build server when running the tests. However it does work locally. On the build server I get the following error which occurs anywhere msal has been referenced:

`2019-02-08T10:46:15.1920689Z ERROR in src/app/app.component.ts(11,47): error TS2307: Cannot find module '@azure/msal-angular'.`

Any ideas what could be causing this and why it would only be an issue on a build server?
