### ISSUE TITLE
idTokenClaims using Typescript

### ISSUE THREAD

**Issue by ivan7707** [AzureAD/microsoft-authentication-library-for-js#4332]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.18.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.1.0

### Description

I am currently using the useAccount hook to retrieve account information for the logged in user.  When trying to access the any attribute (family_name in this case) that is not on the AccountInfo type I receive the error:

Property 'family_name' does not exist on type 'object'.

export declare type AccountInfo = {
    homeAccountId: string;
    environment: string;
    tenantId: string;
    username: string;
    localAccountId: string;
    name?: string;
    idTokenClaims?: object;
};

I found this solution, but do not know how to implement it.  

https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/3870

Solution for my use case:

```
type IdTokenClaims  = {
  family_name: string
};

const family_name = (account?.idTokenClaims as IdTokenClaims).family_name;
```

When I add this code to the functional component, I receive the error: 

**TypeError: Cannot read properties of undefined (reading 'family_name')**

on the solution line of 

`const family_name = (account?.idTokenClaims as IdTokenClaims).family_name;`

### Relevant Code Snippets

The functional component I am using (based on MSAL react sample)

```javascript


type IdTokenClaims  = {
  family_name: string
};

const HelloContent = () => {
    const { instance, accounts, inProgress } = useMsal();
    const account = useAccount(accounts[0] || {});

    const family_name = (account?.idTokenClaims as IdTokenClaims).family_name;

    return (
      <>
      {JSON.stringify(family_name)}
      </>
    
    )
}
```
```


### Identity Provider

Azure B2C Basic Policy

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@ivan7707 Can you check that the claim 'family_name' exists on the token? It may not be one of the claims that you can expect on tokens issued from Azure AD B2C (more information [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/tokens-overview)), so you may need to set a custom claim. See [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/claimsschema) for more information on defining custom claims with custom policies.

**Comment by ivan7707** [comment]
@jo-arroyo Thank you for responding.  

I have setup custom claims that include the family_name attribute.  However, I was initially having the error: Property 'family_name' does not exist on type 'object" because the AccountInfo is a type where the idTokenClaims cannot be extended hence the suggestion from the other question issue: 

`const family_name = (account?.idTokenClaims as IdTokenClaims).family_name;`

I included an existence check before setting this variable which resolved this issue.  

TypeError: Cannot read properties of undefined (reading 'family_name')


This just feels like a very roundabout way to access a custom claim that is not on the Account info type.
