### ISSUE TITLE
Warn the user if they use `responseMode: "form_post"` and `body-parser` middleware it's not present

### ISSUE THREAD

**Issue by ecerulm** [AzureAD/microsoft-authentication-library-for-js#4334]
### Core Library

Passport Azure AD (passport-azure-ad)

### Wrapper Library

Not Applicable

### Description

If using 

        "responseMode": "form_post",

and the express application is not using 

```
const bodyParser = require('body-parser');
app.use(bodyParser.urlencoded({extended: false}));
```

The login flow will fail, usually ending in an infinite loop of redirects back to Azure AD, with no warning / message in the console log about what is happening. 

I think, this could be improved by adding a 

```
  if (config.responseMode === "form_post' && req.body === undefined) {
    throw Error("Missing body-parser");
  } 
```
somewhere in the flow. 

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@ecerulm Apologies for the delayed response, thanks for the suggestion. We're currently not working on new features for `passport-azure-ad`, but will consider this for our future Node middleware offerings. cc @jo-arroyo

**Comment by jasonnutter** [comment]
Closing. If you would like to see this logic in MSAL Node, you may open a PR.
