### ISSUE TITLE
Since @azure/msal-common@5.1.0 

### ISSUE THREAD

**Issue by domiSchenk** [AzureAD/microsoft-authentication-library-for-js#4337]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

^5.1.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

^2.0.3

### Description

In our Angular app we used the following dependencies:
```
        "@azure/msal-angular": "^2.0.3",
        "@azure/msal-browser": "^2.17.0",
```
We had to update another library and got new versions of @azure/msal-* libs. (common: 5.2.0)
now we noticed the login does not work anymore. Sice version 5.1.0 (tested up to this version) makes 2 requests to our ADFS:
- one with grant_type: authorization_code
- one with grant_type: refresh_token

the refresh_token call fails. (we don't know why yet)

do we have to change settings so it does not make the request?

if you need more info let me know

### MSAL Configuration

```javascript
{
    auth: {
        clientId: authSetting.client_id,
        authority: authSetting.authority,
        knownAuthorities: [authSetting.authority],
        protocolMode: authSetting.protocol,
        postLogoutRedirectUri: authSetting.post_logout_redirect_uri,
        redirectUri: authSetting.redirect_uri,
    },
    cache: {
        cacheLocation: BrowserCacheLocation.LocalStorage,
        storeAuthStateInCookie: false, // set to true for IE 11
    },
    system: {
        loggerOptions: {
            loggerCallback,
            logLevel: msalLogLevel,
            piiLoggingEnabled: false
        }
    }
}
```

### Relevant Code Snippets

```javascript
async loginRedirect() {
    this.authService.loginRedirect({ ...this.msalGuardConfig.authRequest } as RedirectRequest);
}
```

### Identity Provider

ADFS

### Source

External (Customer)

**Comment by pkanher617** [comment]
> the refresh_token call fails. (we don't know why yet)

@domiSchenk Can you provide some more details of the error you are getting? If you have any additional details like a Fiddler trace you can send it to my email (available in my profile page).

> do we have to change settings so it does not make the request?

MSAL will make the refresh token request if the acquireTokenSilent call does not find a token.

**Comment by domiSchenk** [comment]
Hi @pkanher617 

I'm currently on holiday, i will reply next week.

**Comment by domiSchenk** [comment]
we found the problem.
Out ADFS did not have enough rights to read the Private Key. 🤷‍♂️
