### ISSUE TITLE
Images form SharePoint List not visible in react application 

### ISSUE THREAD

**Issue by Augustya-sharma** [AzureAD/microsoft-authentication-library-for-js#4338]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.19.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.1.1

### Description

I am trying to get images from the SharePoint List and display the images in react application. The Images aren't visible when we login using graph api. But when we open the image url in the new tab and login to the sharepoint then images are getting rendered in the react application.

All the Image URL are returning 302 response with the URL to authenticate in the network tab 

As per my understanding of this issue.  The SharePoint needs to authenticated first and using Graph API you cannot access SharePoint you cannot get authenticated to SharePoint Images using Graph API 

### MSAL Configuration

```javascript
// <MsalInstanceSnippet>
const msalInstance = new PublicClientApplication({
  auth: {
    clientId: config.appId,
    redirectUri: config.redirectUri,
    navigateToLoginRequestUrl: true,
    postLogoutRedirectUri: config.postLogoutRedirectUri,
  },
  cache: {
    cacheLocation: "localStorage",
    storeAuthStateInCookie: true,
  },
});
```

### Relevant Code Snippets

```javascript
const accounts = msalInstance.getAllAccounts();
if (accounts && accounts.length > 0) {
  msalInstance.setActiveAccount(accounts[0]);
}

msalInstance.addEventCallback((event: EventMessage) => {
  if (event.eventType === EventType.LOGIN_SUCCESS && event.payload) {
    // Set the active account - this simplifies token acquisition
    const authResult = event.payload as AuthenticationResult;
    msalInstance.setActiveAccount(authResult.account);
  }
});
// </MsalInstanceSnippet>
```

### Reproduction Steps

Render image from SharePoint 

### Expected Behavior

The images should get rendered 

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer

### Source

External (Customer)

**Comment by pkanher617** [comment]
This sounds like it may be an issue that the Sharepoint team can help you with, you can try submitting an issue [here](https://github.com/SharePoint/sp-dev-docs/issues).

> The SharePoint needs to authenticated first and using Graph API you cannot access SharePoint you cannot get authenticated to SharePoint Images using Graph API

It does look like the Microsoft Graph API [supports a subset of Sharepoint REST operations](https://docs.microsoft.com/en-us/sharepoint/dev/apis/sharepoint-rest-graph), you may be able to try using the endpoints in the provided link to get the images.

> All the Image URL are returning 302 response with the URL to authenticate in the network tab

Could you provide the error message that you are receiving here? If there is sensitive data you can email it to me, my email is provided in my profile page.
