### ISSUE TITLE
React 18 Support and Issues

### ISSUE THREAD

**Issue by GeorgSteyn** [AzureAD/microsoft-authentication-library-for-js#4341]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL React (@azure/msal-react)

### Description

As React 18 RC is released I think it would be nice to have efforts to work on support for React 18. I have tried upgrading my project to React 18 and I get a weird navigation loop between my app and the MS Login. After a few navigations, it always stops on the MS Login.

I am still investigating on my own but thought I would open a ticket so other people can maybe give feedback and also start the conversations about upgrading.

### Source

External (Customer)

**Comment by pkanher617** [comment]
@GeorgSteyn Thank you for opening this. We are planning on supporting React 18 in the future, and will post updates when React 18 is out of beta as a full release. 

Could you confirm that the navigation loop doesn't occur in React 17 (latest)?

**Comment by GeorgSteyn** [comment]
Hi,

I am glad to hear there are plans for it.

My application is running in production with React V17.0.2 everything still running smooth.

**Comment by GeorgSteyn** [comment]
@pkanher617 As a test I created a blank application with Create React App and upgraded the app to React 18.

With the below minimum code I could replicate my redirect to the login issue.

```jsx
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import reportWebVitals from './reportWebVitals';
import { InteractionType, PublicClientApplication } from "@azure/msal-browser";
import { MsalAuthenticationTemplate, MsalProvider } from '@azure/msal-react';

const msalConfig = {
  auth: {
    clientId: 'clientId',
    authority: 'https://login.microsoftonline.com/vumacamonline.onmicrosoft.com'
  }
};

const pca = new PublicClientApplication(msalConfig);

const container = document.getElementById('root');
const root = ReactDOM.createRoot(container);
root.render(
  <React.StrictMode>
    <MsalProvider instance={pca}>
      <MsalAuthenticationTemplate interactionType={InteractionType.Redirect}>
        <App />
      </MsalAuthenticationTemplate>
    </MsalProvider>
  </React.StrictMode>
);

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();

```

**Comment by pkanher617** [comment]
Thanks @GeorgSteyn we will take a look at this as part of supporting React 18. Appreciate your feedback! :)

**Comment by tnorling** [comment]
@GeorgSteyn Can you try the new version (1.3.0), which was published yesterday? I believe this should resolve the looping behavior you are experiencing.

**Comment by GeorgSteyn** [comment]
@tnorling Will do thanks a lot. 😄

**Comment by GeorgSteyn** [comment]
@tnorling After testing my dummy app and my production app. Seems the issue has been resolved. Thank you very much.
