### ISSUE TITLE
Add WAM Support to MSAL for JS, for cross-language consistency

### ISSUE THREAD

**Issue by joshfree** [AzureAD/microsoft-authentication-library-for-js#4346]
### Core Library

MSAL.js v2 (@azure/msal-browser), MSAL Node (@azure/msal-node)

### Wrapper Library

MSAL Angular (@azure/msal-angular), MSAL React (@azure/msal-react), MSAL Node Extensions (@azure/msal-node-extensions)

### Description

Today WAM support is only in MSAL for .NET. In order to support WAM in Azure Identity Client Library and meet Azure SDK Design Guidelines (of maintaining feature parity across languages), the support for WAM must exist in all Tier-1 languages (C#, Java, JS, Python) for Azure Identity SDK to GA the support at its layer of the stack.

This GitHub issue tracks the ask for adding WAM support to MSAL in Java, JS, Python, and in Go. I'll file GitHub issues in each respective repo.

Related: AzureAD/microsoft-authentication-library-for-dotnet#643
Related: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/wam
Related: Azure/azure-sdk#3724

/cc @dingmeng-xue @scottaddie @schaabs @sadasant @KarishmaGhiya

### Source

Internal (Microsoft)

## Related MSAL Feature Request Issues

MSAL for Python: https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/451
MSAL for JS: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4346
MSAL for Java: https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/455
MSAL for Go: https://github.com/AzureAD/microsoft-authentication-library-for-go/issues/284

**Comment by jasonnutter** [comment]
@joshfree Thanks. For this type of ask, I would recommend connecting with @peterzenz and @EmLauber to make sure this is tracked in ADO, especially given some of this work is already in progress.

**Comment by joshfree** [comment]
Thanks.  ADO issues are incoming; just filing on github first.

**Comment by sameerag** [comment]
Just to add context, 
* This is in progress with some work in progress for msal-browser - which will be extended to msal-react and msal-angular for which ADO items already exist.
* msal-node WAM support will be similar to msal-java, msal-go and msal-python - which is also tracked in ADO

I can sync up offline to send those ADO items your way or @EmLauber  can help with the same.

**Comment by EmLauber** [comment]
I have synced up offline and provided the ADO items.

**Comment by EmLauber** [comment]
Closing as this is tracked separately.

**Comment by EmLauber** [comment]
Closing as this is tracked separately.
