### ISSUE TITLE
How to disable sending the `x-client-last-telemetry` parameter

### ISSUE THREAD

**Issue by shibayan** [AzureAD/microsoft-authentication-library-for-js#4361]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.19.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

When you configure Azure AD B2C Custom Domain and enable Front Door WAF, requests may be blocked depending on the value of the `x-client-last-telemetry` parameter.

When the session is cleared, MSAL.js may send parameters such as the following, which will be trapped by SQL injection rules because they contain `||`.

```
x-client-last-telemetry: 5|0|||0,0
```

To avoid this problem, I would like to set the MSAL.js not to send telemetry, is there any way to do this?

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by tnorling** [comment]
@shibayan There is not currently an option to disable this but we have filed an item in our backlog to investigate. We'll update this ticket when we have more to share. Thanks for raising this!

**Comment by shylasummers** [comment]
Fixed in PR #6262. Let us know if this solves your issue.
