### ISSUE TITLE
Redirect uri not working for msal-angularjs

### ISSUE THREAD

**Issue by ashinzekene** [AzureAD/microsoft-authentication-library-for-js#4362]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

0.0.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

0.1.1

### Description

Redirect uri is always the current location even after setting a `redirectUri` in config for [msal-angularjs](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/maintenance/msal-angularjs)

@azure/msal-angularjs version: 0.1.1

### Error Message

No error message

### MSAL Configuration

```javascript
{
  clientID: 'f3e5cf63-6c0d-42cb-b5aa-ee58b1ef7523',
  redirectUri: 'https://google.com'
}
```

### Relevant Code Snippets

```javascript
window.applicationConfig = {
      clientID: 'f3e5cf63-6c0d-42cb-b5aa-ee58b1ef7523',
      redirectUri: 'https://google.com'
};

app.config(['msalAuthenticationServiceProvider', function (msalProvider) {
	msalProvider.init({
		clientID: applicationConfig.clientID,
		tokenReceivedCallback: function (errorDesc, token, error, tokenType) {
		}
	});
}]);
```

### Reproduction Steps

1. Create sample angular1 application
2. Set the redirect uri in the config
3. Try to login/acquire token

### Expected Behavior

Redirect uri is always `window.location.href`

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

Internal (Microsoft)

**Comment by jermylucas** [comment]
@ashinzekene Your redirect uri is set to `htts://google.com` instead of `https://...` . If you make it https instead of htts, will it work? The uri should need either http or https depending upon the site

**Comment by ashinzekene** [comment]
Oh that was a mistake. It doesn't work with https uris

**Comment by tnorling** [comment]
@ashinzekene `msal-angularjs` is no longer receiving updates. Please use `msal-angular` instead.

**Comment by ashinzekene** [comment]
`msal-angular` is for angular2+ apps. I'm working with a legacy angular1 application @tnorling

**Comment by ashinzekene** [comment]
I was using the wrong version of msal
