### ISSUE TITLE
Depricated import for UUID

### ISSUE THREAD

**Issue by AlexSpelt** [AzureAD/microsoft-authentication-library-for-js#4364]
### Core Library

ADAL Node (adal-node)

### Core Library Version

0.2.3

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

Your package imports a deprecated version of UUID. Please update UUID to at least version 7. The current version clutters my npm install with deprecation warnings.

### Error Message

npm WARN deprecated uuid@3.4.0: Please upgrade to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

### MSAL Configuration

```javascript
{}
```

### Relevant Code Snippets

```javascript
"adal-node": {
      "version": "0.2.3",
      "resolved": "https://registry.npmjs.org/adal-node/-/adal-node-0.2.3.tgz",
      "integrity": "sha512-gMKr8RuYEYvsj7jyfCv/4BfKToQThz20SP71N3AtFn3ia3yAR8Qt2T3aVQhuJzunWs2b38ZsQV0qsZPdwZr7VQ==",
      "requires": {
        "@xmldom/xmldom": "^0.7.0",
        "async": "^2.6.3",
        "axios": "^0.21.1",
        "date-utils": "*",
        "jws": "3.x.x",
        "underscore": ">= 1.3.1",
        "uuid": "^3.1.0",
        "xpath.js": "~1.1.0"
      },
      "dependencies": {
        "uuid": {
          "version": "3.4.0",
          "resolved": "https://registry.npmjs.org/uuid/-/uuid-3.4.0.tgz",
          "integrity": "sha512-HjSDRw6gZE5JMggctHBcjVak08+KEVhSIiDzFnT9S9aegmp85S/bReBVTb4QTFaRNptJ9kuYaNhnbNEOkbKb/A=="
        }
      }
    },
```

### Reproduction Steps

1. npm ci

### Expected Behavior

A clean install without deprecation warnings.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Source

External (Customer)

**Comment by tnorling** [comment]
@AlexSpelt Please migrate to `msal-node` as `adal-node` is no longer receiving updates at this time. Migration docs can be found [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-node-migration)
