### ISSUE TITLE
msal breaks with authority url with upper case letters

### ISSUE THREAD

**Issue by kyubisation** [AzureAD/microsoft-authentication-library-for-js#4366]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.21.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.1.0

### Description

When using an authority with upper case letters (and an authority with case sensitive url) msal breaks, since it cannot load the well known infos. This is the case for RedHat SSO.

e.g.
```ts
new PublicClientApplication({
  auth: {
    authority: 'https://oauth-provider.example/auth/realms/EXAMPLE
    ...
  } 
})
```

This is essentially due to `Authority.canonicalAuthority` (https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/src/authority/Authority.ts#L92) using `UrlString`, which converts the url to lower case in `UrlString.canonicalizeUri` (https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/src/url/UrlString.ts#L42).

### Error Message

See description

### Msal Logs

See description

### MSAL Configuration

```javascript
See description
```

### Relevant Code Snippets

```javascript
See description
```

### Reproduction Steps

See description

### Expected Behavior

The authority url should not be converted to lower case.

### Identity Provider

Other

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer, None (Server), Other

### Source

External (Customer)

**Comment by tnorling** [comment]
@kyubisation You can provide the well-known metadata manually by following the instructions in [this doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/performance.md). Unfortunately support for 3rd party IDPs is limited, we try our best to make MSAL work with non-Microsoft OAuth compliant IDPs, however, we are unlikely to prioritize fixing broken behavior like this. PRs are welcome if you'd like to take a crack at it yourself!

**Comment by kyubisation** [comment]
Hello @tnorling 
Thanks for the feedback. I will bring it up during our next meetup with our Microsoft contacts.

**Comment by jasonnutter** [comment]
Reopening to confirm workaround, see if there are other options.
