### ISSUE TITLE
Inject MSAL config using code

### ISSUE THREAD

**Issue by alexander-kastil** [AzureAD/microsoft-authentication-library-for-js#4367]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.20.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.6

### Description

MSALInstanceFactory, MSALInterceptorConfigFactory require some data like clientid, authority (tenantid for single tenant apps) and also protectedResourceMap info like the api url (protectedResourceMap.set('https://localhost:5001/food', ['api://b509d389-361a-447b-afb2-97cc8131dad6/access_as_user',]) ... As I am not taking those values from environment but instead in use a ConfigService and load those values in order to be able to deploy one Angular Build to different environments (dev, test, prod, ...) I wonder if you have a pattern to set this values using code?

### MSAL Configuration

```javascript
export function MSALInstanceFactory(): IPublicClientApplication {
  let config = {
    auth: {
      clientId: 'd23642f7-9ccf-4165-92e7-919f625a5acc',
      authority:
        'https://login.microsoftonline.com/d92b247e-90e0-4469-a129-6a32866c0d0a',
      redirectUri: '/',
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE, // set to true for IE 11
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Info,
        piiLoggingEnabled: false,
      },
    },
  };
  return new PublicClientApplication(config);
}

export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
  const protectedResourceMap = new Map<string, Array<string>>();
  protectedResourceMap.set('https://graph.microsoft.com/v1.0/me', [
    'user.read',
  ]);
  protectedResourceMap.set('https://localhost:5001/food', [
    'api://b509d389-361a-447b-afb2-97cc8131dad6/access_as_user',
  ]);

  return {
    interactionType: InteractionType.Redirect,
    protectedResourceMap,
  };
}
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by tnorling** [comment]
@arambazamba Can you please review our [configuration docs](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/configuration.md) and let us know if your question is answered there? Thanks!

**Comment by alexander-kastil** [comment]
> @arambazamba Can you please review our [configuration docs](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/configuration.md) and let us know if your question is answered there? Thanks!

question ist answered in platformBrowserDynamic section 👍
