### ISSUE TITLE
Getting consent_required error for other outlook accounts except my account.

### ISSUE THREAD

**Issue by turpu-rakesh** [AzureAD/microsoft-authentication-library-for-js#437]
Hello,

Thanks for providing this library 👍 and I'm using this library in my angular 4 web application and web API is .net core 2.0 . Registered my web app and web API in  [Application Registration Portal](https://apps.dev.microsoft.com) site with my outlook account and added both web app and web API platform within the same app and gave permissions to web API, user.read permissions for graph API. I have installed @azure/msal-angular library file and configured everything as it is mentioned in sample app. When I log-in into my application with outlook account using which I registered my App in Application Registration Portal, I'm able to login and make API calls. But if others are trying to login into the application using their outlook then it is throwing below error. Since I work for Microsoft and I have v- account when myself and my team mates when logged-in into application with v- we all were able to login into the app without any issues.

ERROR The request was denied because one or more scopes requested are unauthorized or expired. The user must first sign in and grant the client application access to the requested  #scope.|consent_required

**Comment by nehaagrawal** [comment]
@turpu-rakesh  Please don't remove the template while creating a new issue. That gives us a lot of detail to resolve your issue faster. I am not sure what version of the library you are using.
1. Could you please tell us what scopes you requested that resulted in error?
2. When you said others are not able to login, do you mean MSA account?
3. Could you please tell me what authority you passed in the config?

**Comment by turpu-rakesh** [comment]
@nehaagrawal Sorry, I thought MSA account is microsoft.com account but it is outlook.com/hotmail.com. Yes, others are not able to login with MSA accounts only through their v- able to access. 

I did some analysis and found that if we enable below permissions to our app then we are able to access without any issue using any account. This permissions we have added using another app but using same App Registration Id, by this for that App Id below permissions were enabled and able to access our App.
**1. Access your info anytime
2. View your basic profile 
3. Read your profile**

To give above 3 delegated permissions, we have passed "offline_access","profile" and "user.read" permissions  to consentScopes but it showing only read permission and not prompting for access and view permission. Because of that we are not able to access. screenshot#1 is read permission prompt which is coming for our were we are using msal angular library. And screenshot#2 is from another app which we downloaded from git and just added same app id which we are using in our app and it is prompting with access and view permissions. Here is the link for [GitHub](https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore-v2) of app code which we downloaded and tested. 

**screehshot#1**
![image](https://user-images.githubusercontent.com/38064129/45813630-bb93d200-bcf0-11e8-8537-91ba146ac967.png)

**screehshot#2**
![image](https://user-images.githubusercontent.com/38064129/45813779-280ed100-bcf1-11e8-98fc-9ed8ebb528e3.png)

**Comment by nehaagrawal** [comment]
@turpu-rakesh  We discussed this issue over email and it was resolved. I am closing this issue for now. Please reopen if issue still exists.

**Comment by charles-resfrac** [comment]
I am now running into the same issue. What was the resolution?

**Comment by charles-resfrac** [comment]
Ok, I figured out what I was doing wrong. Writing it down here to benefit future searchers. 

I needed to include the 'offline_access' scope in the auth code grant request (to https://login.microsoftonline.com/common/oauth2/v2.0/authorize) as well as for the access token request (https://login.microsoftonline.com/common/oauth2/v2.0/token). I had a mismatch in the scopes in my two requests.

**Comment by charles-resfrac** [comment]
Also for future reference, here is a useful documentation link for Azure: 
https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-permissions-and-consent, especially the "Types of Consent" section, comparing "Static user consent" with "Dynamic user consent".
