### ISSUE TITLE
PKCE code challenge and verifier could not be generated error

### ISSUE THREAD

**Issue by AgarwalKush** [AzureAD/microsoft-authentication-library-for-js#4375]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.21.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.2.0

### Description

Using the redirect login flow on a React single page application, but getting the following error:

`BrowserAuthError: pkce_not_created: The PKCE code challenge and verifier could not be generated. Detail:TypeError: Cannot read properties of undefined (reading 'digest')`

When I run it locally on localhost it works fine and logs in successfully, but when running on a hosted server on nginx it gives this error.  I've looked for hours but couldn't find this issue anywhere.  I searched through the code and found the block where the error is being thrown, and suspect it might be an issue where it is accessing an undefined variable prematurely (although I could very well be wrong).

### Error Message

`BrowserAuthError: pkce_not_created: The PKCE code challenge and verifier could not be generated. Detail:TypeError: Cannot read properties of undefined (reading 'digest')`

### Msal Logs
`{"eventType":"msal:loginFailure","interactionType":"redirect","payload":null,"error":{"errorCode":"pkce_not_created","errorMessage":"The PKCE code challenge and verifier could not be generated. Detail:TypeError: Cannot read properties of undefined (reading 'digest')","subError":"","name":"BrowserAuthError","correlationId":"94305f4b-a471-4b9b-b361-314d542ea33f"},"timestamp":1641521186620}`

### MSAL Configuration

```javascript
auth: {
        clientId: "xxx",
        authority: "https://login.microsoftonline.com/e2793358-22c6-4d05-ba11-534ec733b8dd",
        redirectUri: "/home",
        postLogoutRedirectUri: "/login",
        navigateToLoginRequestUrl: false,
    },
    cache: {
        cacheLocation: "sessionStorage",
        storeAuthStateInCookie: false,
    },
    system: {
        loggerOptions: {
            loggerCallback: (level, message, containsPii) => {
                if (containsPii) {
                    return;
                }
                switch (level) {
                    case LogLevel.Error:
                        console.error(message);
                        return;
                    case LogLevel.Info:
                        console.info(message);
                        return;
                    case LogLevel.Verbose:
                        console.debug(message);
                        return;
                    case LogLevel.Warning:
                        console.warn(message);
                        return;
                }
            }
        }
    }
```

### Relevant Code Snippets

```javascript
const { instance } = useMsal();
const login = async () => {
    await instance.loginRedirect({ scopes: "api://xxx/access_as_user"})
    .catch((err) => {
      console.log('login err', err); // this is where the above error i'm talking about gets thrown
    })
  }
```

### Reproduction Steps

Try logging in using redirect and this issue happens right when clicking login - I don't even get to the redirected page.  Seems like it is unable to generate a parameter needed for the login url

### Expected Behavior

Redirect the page to the microsoftonline login page

### Identity Provider

Other

### Browsers Affected (Select all that apply)

Chrome, Firefox, Safari

### Source

External (Customer)

**Comment by tnorling** [comment]
@AgarwalKush This means the browser crypto APIs are not available. Is your site running on https?

**Comment by AgarwalKush** [comment]
Running on HTTPS worked.  Thanks!  This isn't an issue with MSAL, but with the way I set it up.   Closing this thread.
