### ISSUE TITLE
Add observability mechanism

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-js#4388]
### Core Library

MSAL Node (@azure/msal-node)

### Wrapper Library

Not Applicable

### Description

Please see https://identitydivision.visualstudio.com/DevEx/_git/AuthLibrariesApiReview/pullrequest/4733

The gist of it is: 

Systems in production need to be monitored. As a critical library, MSAL must facilitate both runtime monitoring, as well as inform the app developers about substandard (non-performant, less secure) configuration, while also keeping backwards compatibility. The solution proposed is:

- expose a few metrics as part of `AuthenticationResult` such as "time spent in cache", "time spent in http", "token source" etc.
- small logging improvements
- review telemetry

### Source

Internal (Microsoft)

**Comment by jasonnutter** [comment]
@EmLauber for performance telemetry for MSAL Node.

**Comment by bgavrilMS** [comment]
MSAL JS exposes token source (cache vs IDP), which is enough to monitor cache hit ratios.
