### ISSUE TITLE
Best pattern for reading App Roles for an API

### ISSUE THREAD

**Issue by Thnslj** [AzureAD/microsoft-authentication-library-for-js#4389]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.16.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.2

### Description

I have successfully configured connected two App's using the [azure-tutorial ](https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/blob/main/5-AccessControl/1-call-api-roles/README.md) - Users can login and access_tokens are retrieved right before the first request to my API.

In the tutorial, App Roles are mapped to users/groups for both the SPA and the API.
However, I would like to only register and map the App Roles for the API for easier maintenance of users and their access.

**Question**
In the SPA. How can I upfront determine what roles the user have for a specific API? This is needed to conditionally hide/show menus and buttons.

Should I immediately request an access_token for my API after the user makes a login?
What if I have multiple API's, should I loop all my connected API's or what would be the best practice? 🤔

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by tnorling** [comment]
@Thnslj You can use the roles claim in the idToken to determine what roles the user has. The tutorial shows one example of how to do this [here](https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/blob/main/5-AccessControl/1-call-api-roles/README.md#angular-roleguard-and-protected-routes-for-role-based-access-control). You can also read more about roles [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-add-app-roles-in-azure-ad-apps#use-app-roles-in-your-web-api)

**Comment by Thnslj** [comment]
@tnorling Thanks for the answer..
Yes I know I can check the `idToken`. But those roles will be those that are configured on the SPA. Not those that are configured on the API. 

If you look in the tutorial, they are adding them both the API and the SPA:

This is done twice:
![image](https://user-images.githubusercontent.com/20703505/149398271-469e0847-426a-49ec-89bd-7df564d41cad.png)

**Comment by tnorling** [comment]
@Thnslj Does your access token contain the correct roles when only configured on the API? Can you add an API to your backend that reads the token and returns the list of roles? Otherwise perhaps `groups` are more in line with what you're looking for. See the comparison [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-add-app-roles-in-azure-ad-apps#app-roles-vs-groups)

**Comment by Thnslj** [comment]
> @Thnslj Does your access token contain the correct roles when only configured on the API? 

Yes they contain the correct roles.

> Can you add an API to your backend that reads the token and returns the list of roles?

Yes I could do that. However, I have multiple API's, and it feels like a hack to implement that in every API I will be calling.

**Comment by tnorling** [comment]
Are they just different endpoints or do they each have their own distinct applicationId?

**Comment by Thnslj** [comment]
> Are they just different endpoints or do they each have their own distinct applicationId?

Different applicationId's

**Comment by tnorling** [comment]
@Thnslj Looks like you can use the [MS Graph API](https://docs.microsoft.com/en-us/graph/api/user-list-approleassignments?view=graph-rest-1.0&tabs=http) to retrieve user app roles. It's unfortunately not something I'm personally familiar with, if you have questions or issues using the Graph API you can ask the Graph SDK team [here](https://github.com/microsoftgraph/msgraph-sdk-javascript)

**Comment by amaleszewski** [comment]
> @Thnslj Looks like you can use the [MS Graph API](https://docs.microsoft.com/en-us/graph/api/user-list-approleassignments?view=graph-rest-1.0&tabs=http) to retrieve user app roles. It's unfortunately not something I'm personally familiar with, if you have questions or issues using the Graph API you can ask the Graph SDK team [here](https://github.com/microsoftgraph/msgraph-sdk-javascript)

Is there any possibility to return object from access token like there is currently for identity token? I mean add something like `idTokenClaims` but for access token, ie. `accessTokenClaims`? This will resolve my issues also. I have the same flow in AAD for API and SPA as author, and it's also causes me troubles.

**Comment by tnorling** [comment]
@amaleszewski Access tokens should only be opened by the resource for which it is intended, so unfortunately MSAL.js will not be able to return the access token claims. If this is something you need you should do this on your backend
