### ISSUE TITLE
MSAL cannot logout user directly/silently

### ISSUE THREAD

**Issue by bourne-xian** [AzureAD/microsoft-authentication-library-for-js#4393]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Description

Use the configuration options for logout by following [article](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md#logoutredirect), it still failed to logout user directly but redirect to end session endpoint and ask user pick an account to logout.

It's because of we want to implement a logic to logout user directly after a period of inactivity time, for security reason.

NOTE: As AAD Policy [Refresh Token Max Inactive Time](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes#refresh-and-session-token-lifetime-policy-properties) was retired since January 30, 2021. But the replacement feature -- [Conditional Access](https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens#access-token-lifetime) didn't support sliding expiration.  So we want the MSAL library to support logout specific user.

So the work around maybe [revoke user session](https://docs.microsoft.com/en-us/graph/api/user-revokesigninsessions?view=graph-rest-1.0&tabs=http) via graph API? But seems it will impact all application for user (e.g. signed in mobile app session will be revoked?).

### Source

External (Customer)

**Comment by tnorling** [comment]
@bourne-xian The silent logout feature is being tracked in #4335. Closing this as duplicate
