### ISSUE TITLE
ssoSilent Incognito code fix

### ISSUE THREAD

**Issue by nopsal** [AzureAD/microsoft-authentication-library-for-js#4398]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.18.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

Hi all,

I am currently working on an app using ssoSilent. When the app is accessed in incognito mode in Chrome there is an error because no user is recognized. I know this can be fixed by changing Chrome settings to allow all cookies, but is there a code fix available to avoid requiring users to change settings? Thanks in advance for any response.

### Source

External (Customer)

**Comment by tnorling** [comment]
@nopsal Unfortunately, the ssoSilent API depends on 3rd party cookies. When these cookies are blocked you will have to use an interactive method for the first sign-in (sso may still work in "interactive" cases in the sense that the user may not be asked for credentials but you still need to either redirect or open a popup). After the first sign-in you can silently acquire tokens using the `acquireTokenSilent` API, even in browsers that block 3rd party cookies.
