### ISSUE TITLE
Support multiple policies

### ISSUE THREAD

**Issue by yakimko** [AzureAD/microsoft-authentication-library-for-js#440]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: X.Y.Z

## Current behavior
Right now I use 3 different policies: auth, reset password and edit profile.
After reset password and edit profile actions I need to log out a user and then log in the user using auth policy

## Expected behavior
Support multiple policies 

## Minimal reproduction of the problem with instructions

</code></pre>

**Comment by StewSchrieff** [comment]
Has any progress been made on this front? Or does anyone know of a workaround that can be accomplished by modifying MSAL code? I've got an application that needs to support three policies, much like @yakimko

**Comment by sameerag** [comment]
We are working on understanding how to support this in MSAL JS and if any background work is needed to enable this. Will update this ticket once we have more clarity on the dates.

**Comment by tnorling** [comment]
This is now supported in version 1.4.0, you can switch your policy by providing the `authority` parameter on the request object.
