### ISSUE TITLE
handleRedirectPromise() in MSAL2.0 clears all hash values regardless of the fragment name

### ISSUE THREAD

**Issue by Miwa199739** [AzureAD/microsoft-authentication-library-for-js#4400]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.17.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

N/A

### Description

handleRedirectPromise() in MSAL2.0 clears all hash values regardless of the fragment name

Access a SPA (built with Angular) with any url containing a hash, e.g. https://adf.azure.com/en-us/authoring?factory=xxx#myCustomziedHash=xxx, the hash fragment (#myCustomziedHash=xxx) got cleared after we are redirected back from the login page.

### Error Message

N/A

### Msal Logs

N/A

### MSAL Configuration

```javascript
{
            auth: {
                clientId: 'xxxxxx',
                authority: 'https://login.microsoftonline.com/organizations',
                redirectUri: window.location.origin,
                postLogoutRedirectUri: window.location.origin + baseHref,
                navigateToLoginRequestUrl: true
            },
            cache: {
                storeAuthStateInCookie: false,
                cacheLocation: 'sessionStorage'
            }
        };

How do we invoke loginRedirect function:

public loginRedirect(): void {
        const request: RedirectRequest = {
            redirectStartPage: window.location.href,
            scopes: ['openid']
        };
        this._msalInstance.loginRedirect(request);
    }
```

### Relevant Code Snippets

```javascript
In microsoft-authentication-library-for-js\lib\msal-browser\src\interaction_client\RedirectClient.ts, async handleRedirectPromise(hash?: string): Promise<AuthenticationResult | null> 

            try {
                state = this.validateAndExtractStateFromHash(responseHash, InteractionType.Redirect);
                BrowserUtils.clearHash(window);
                this.logger.verbose("State extracted from hash");
            } catch (e) {
                this.logger.info(`handleRedirectPromise was unable to extract state due to: ${e}`);
                this.browserStorage.cleanRequestByInteractionType(InteractionType.Redirect);
                return null;
            }
```

### Reproduction Steps

1. 
![image](https://user-images.githubusercontent.com/14820833/149471955-eae36019-a4f9-4588-a942-c76cf3d46eb7.png)

2. in our app, call this._msalInstance.handleRedirectPromise() to get the login result.
![image](https://user-images.githubusercontent.com/14820833/149470602-8f975931-fb10-4e24-9a94-13c99f9f9fb2.png)

3. 
![image](https://user-images.githubusercontent.com/14820833/149470785-39e7b199-b059-4fbe-8a7b-9d3b2a56aa09.png)

### Expected Behavior

Access a SPA (built with Angular) with URL _https://adf.azure.com/en-us/authoring?factory=xxx#myCustomziedHash=xxx_, the hash fragment (_#myCustomziedHash=xxx)_ **should be well-reserved** after we are redirected back from the login page.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Regression

No

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
@Miwa199739 I am not able to reproduce this on my end, however, I do see there is potential room for improvement here. The hash should be re-added to the url a few lines further down. Is that not happening? Can you provide a minimal reproduction?

**Comment by jasonnutter** [comment]
`validateAndExtractStateFromHash` is supposed to throw if the hash doesn't contain a number of known properties, so I mind it surprising that a value like `myCustomizedHash=xxx` wouldn't throw.

**Comment by Miwa199739** [comment]
Thanks for replying!
Yes, I can see that the hash got added soon, but these two location hashChange events (one clears and one added back) cause the Angular router to behave incorrectly. The phenomenon in our app is that all the query parameters got cleared.

![image](https://user-images.githubusercontent.com/14820833/149754641-a9a8cd6a-046e-44c8-b0b3-3b5b3c072978.png)

I created a reproduced app and have sent the link to you via Teams, please check, thanks for your helping!

**Comment by Miwa199739** [comment]
Thanks for your effort! @tnorling
