### ISSUE TITLE
msal-react logout request is getting cancelled. It redirects to home page

### ISSUE THREAD

**Issue by muthurnd3** [AzureAD/microsoft-authentication-library-for-js#4401]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.19.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.1.1

### Description

When I click on logout button it redirects to application homepage. Microsoft logout url is getting cancelled.
If I manually clear the cookies and try, then it works. Also it works if I manually redirects to Microsoft logout url using window.location.href .

### MSAL Configuration

```javascript
export const msalConfig = {
  auth: {
    clientId: CLIENTID,
    authority:
      'https://login.microsoftonline.com/*****************************',
    redirectUri: window.location.origin,
    postLogoutRedirectUri: window.location.origin,
  },
  cache: {
    cacheLocation: 'localStorage',
    storeAuthStateInCookie: true,
  },
  system: {
    loggerOptions: {
      loggerCallback: (level, message, containsPii) => {
        if (containsPii) {
          return;
        }
        switch (level) {
          case LogLevel.Error:
            break;
          case LogLevel.Info:
            break;
          case LogLevel.Verbose:
            break;
          case LogLevel.Warning:
          default:
            break;
        }
      },
    },
  },
};
```

### Relevant Code Snippets

```javascript
async function login(instance, handleMSGraph, graphMeInfo) {

  const accounts = instance.getAllAccounts();
  if (accounts.length === 0) {
    sessionStorage.removeItem('accessToken');
    sessionStorage.removeItem('idToken');
    await instance.handleRedirectPromise();
    await instance.loginRedirect();
  } else {
    msalInstance.setActiveAccount(accounts[0]);
    const activeAccount = accounts[0];
    msalInstance.acquireTokenSilent({
      ...loginRequest,
      account: activeAccount,
    }).then((response)=>{
      sessionStorage.setItem('accessToken', response.accessToken);
      sessionStorage.setItem('idToken', response.idToken);
      if(!graphMeInfo.id){
        handleMSGraph();
      }
    }).catch(error => {
      if (error instanceof InteractionRequiredAuthError) {
          // fallback to interaction when silent call fails
          return msalInstance.acquireTokenRedirect(request)
      }
    });
  }

  msalInstance.addEventCallback((message) => {
    console.log(message);
    // if (message.eventType === EventType.LOGIN_SUCCESS) {
    // }
  });
}


const handleLogout = async event => {
      await instance.logoutRedirect(logoutRequest);
};
```

### Reproduction Steps

Trigger logout function.

### Expected Behavior

This should ideally redirect to microsoft logout page and user's session should get cleared.

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari

### Source

External (Customer)

**Comment by tnorling** [comment]
@muthurnd3 When you say the logout request is cancelled, do you mean the network request (in your browser's network tab) is showing "cancelled" or it's getting skipped entirely? Can you please share the code that calls your `handleLogout` function and verbose logs from MSAL? Thanks!

**Comment by muthurnd3** [comment]
@tnorling  Yes you are right. The network call for logout request is cancelled.
<img width="1674" alt="Screenshot 2022-01-14 at 23 21 28" src="https://user-images.githubusercontent.com/78701655/149592931-fc534339-58a0-4531-ad4a-a14bde64bb2c.png">

Here is code for logout :
   
event.preventDefault();
localStorage.clear();
sessionStorage.clear();
msalInstance['browserStorage'].clear();
await instance.logoutRedirect();

**Comment by tnorling** [comment]
@muthurnd3 You have 2 login calls after the logout. The 1st login call is cancelling the logout and the 2nd login is cancelling the first login. Check that your react components aren't re-rendering and unintentionally calling login. You should make sure you always check that `inProgress === InteractionStatus.None` before calling interactive methods.

Also, you don't need to manually clear local/session storage as the logout APIs do this for you.
