### ISSUE TITLE
Unexpected/delayed context data after logout

### ISSUE THREAD

**Issue by ToshB** [AzureAD/microsoft-authentication-library-for-js#4402]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.20.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.1.2

### Description

After logging out using logoutPopup i consistently got an error saying no_tokens_found. After digging a bit, this was due to an acquireTokenSilent-call I had in a useEffect, taking both `accounts` and `inProgress` as dependencies. Immediately after logging out I had `inProgress=InteractionStatus.None` and `accounts.length > 0`, so my acquireTokenSilent ran, and immediately after the accounts array was emptied.

While the instance variable is stable, both inProgress and accounts change during logout. And as these are stored in different state variables in MsalProvider, they do not change at the same time (ref https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/master/lib/msal-react/src/MsalProvider.tsx#L57 and https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/master/lib/msal-react/src/MsalProvider.tsx#L81).

I am able to work around this by not using `context.accounts` in my useEffect hooks (while it works fine in most useCallbacks), and instead use `instance.getAllAccounts()`. However, this is confusing behavior, as it works fine in some cases (typically things triggered by user interaction, like useCallback) but not in useEffecs triggered by value change.

I would suggest changing these into useReducer instead of 2x useState, so you can set both at the same time, so state changes are atomic. Perhaps just moving the whole event callback handling into useReducer. 

Another note, I can't see the need for inProgressRef. It seems to be to get the current value of inProgress without requiring another hook dependency, but you should be able to do this with `setInProgress(currentProgress -> { /* get new value */; return status;})`.

### Error Message

Uncaught (in promise) InteractionRequiredAuthError: no_tokens_found: No refresh token found in the cache. Please sign-in.
    at InteractionRequiredAuthError.AuthError [as constructor] (AuthError.js:27:1)
    at new InteractionRequiredAuthError (InteractionRequiredAuthError.js:40:1)
    at Function.InteractionRequiredAuthError.createNoTokensFoundError (InteractionRequiredAuthError.js:63:1)
    at RefreshTokenClient.<anonymous> (RefreshTokenClient.js:99:1)
    at step (_tslib.js:75:1)
    at Object.next (_tslib.js:56:1)
    at _tslib.js:49:1
    at new Promise (<anonymous>)
    at __awaiter (_tslib.js:45:1)
    at RefreshTokenClient.acquireTokenWithCachedRefreshToken (RefreshTokenClient.js:93:1)

### Msal Logs

authConfig.ts:28 [Fri, 14 Jan 2022 10:45:21 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:logoutStart
2authConfig.ts:28 [Fri, 14 Jan 2022 10:45:21 GMT] : @azure/msal-react@1.2.0 : Info - MsalProvider - msal:logoutStart results in setting inProgress from none to logout
authConfig.ts:28 [Fri, 14 Jan 2022 10:45:21 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:logoutSuccess
authConfig.ts:28 [Fri, 14 Jan 2022 10:45:21 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:popupOpened
authConfig.ts:28 [Fri, 14 Jan 2022 10:45:25 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:logoutEnd
2authConfig.ts:28 [Fri, 14 Jan 2022 10:45:25 GMT] : @azure/msal-react@1.2.0 : Info - MsalProvider - msal:logoutEnd results in setting inProgress from logout to none
2authConfig.ts:28 [Fri, 14 Jan 2022 10:45:25 GMT] : @azure/msal-react@1.2.0 : Info - MsalProvider - updating account state
authConfig.ts:28 [Fri, 14 Jan 2022 10:45:25 GMT] : @azure/msal-react@1.2.0 : Info - MsalProvider - no account changes
authConfig.ts:28 [Fri, 14 Jan 2022 10:45:25 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:acquireTokenStart
authConfig.ts:28 [Fri, 14 Jan 2022 10:45:25 GMT] : [5f8c2d7a-f1b2-4354-b6ea-a05c93874085] : @azure/msal-common@6.0.0 : Info - SilentFlowClient:acquireCachedToken - No access token found in cache for the given properties.
authConfig.ts:28 [Fri, 14 Jan 2022 10:45:25 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:acquireTokenFromNetworkStart
authConfig.ts:28 [Fri, 14 Jan 2022 10:45:25 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:acquireTokenFailure
authConfig.ts:28 [Fri, 14 Jan 2022 10:45:25 GMT] : @azure/msal-react@1.2.0 : Info - MsalProvider - updating account state
2authConfig.ts:28 [Fri, 14 Jan 2022 10:45:25 GMT] : @azure/msal-react@1.2.0 : Info - MsalProvider - no account changes
-- Followed by the error message above --

### MSAL Configuration

```javascript
{
  auth: {
    clientId: CLIENT_ID,
    authority: AUTHORITY,
    redirectUri: '/',
    postLogoutRedirectUri: '/',
    navigateToLoginRequestUrl: true,
  },
  cache: {
    cacheLocation: 'localStorage',
    storeAuthStateInCookie: false,
  }
}
```

### Relevant Code Snippets

```javascript
export function useToken() {
  const { accounts, instance, inProgress } = useMsal();
  const [token, setToken] = React.useState<string>();

  React.useEffect(() => {
    async function load() {
      if (inProgress === InteractionStatus.None && accounts.length > 0) {
        const response = await instance.acquireTokenSilent({
          scopes: ['myScope'],
          account: accounts[0],
        });
        setToken(response.accessToken);
      } else {
        setToken(undefined);
      }
    }

    load();
  }, [accounts, inProgress, instance]);

  return [token];
}
```

### Reproduction Steps

1. Log in, and see the token being acquired
2. Log out using instance.logoutPopup()

### Expected Behavior

I would expect inProgress and accounts to change value at the same time, so the useEffect-hook would not receive an intermediate and invalid state.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge

### Source

External (Customer)

**Comment by tnorling** [comment]
@ToshB Thanks for the detailed explanation! I agree this can be improved and I'll mark this as a bug to take a closer look. If you already have a solution in mind, we welcome pull requests!

**Comment by ToshB** [comment]
As I realized from your response to #4416, there's not really a need to have a dependency on both `inProgress` and `accounts` when i use the active account pattern. That makes this less of an problem. I would still consider it a bug though, as those variables should be synchronized in order to avoid seeing impossible/illegal states. 

I started looking into making a pull request on this, and have a few questions: 
- I noticed that the accounts array is updated only on certain events, in addition to the check that the accounts array has actually changed. Are there any event types where you would not want the accounts-array to update, or is this just to limit context updates? [link](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/src/MsalProvider.tsx#L43)
- Does the accounts ever change without the InteractionStatus/inProgress changing as well? Or could the change in interaction status be the trigger for updating context, setting accounts to `instance.getAllAccounts()` (if it has changed). 

It feels like the logic could be simplified quite a lot, but with all the state transitions it's hard knowing there aren't any special cases coded into the switch statements.

**Comment by tnorling** [comment]
> I noticed that the accounts array is updated only on certain events, in addition to the check that the accounts array has actually changed. Are there any event types where you would not want the accounts-array to update, or is this just to limit context updates? link

It was mainly to avoid doing the potentially expensive array comparison on every event. Admittedly, this may not be a huge concern today but we may add more events to `msal-browser` in the future that could cause this to run more often than needed.

> Does the accounts ever change without the InteractionStatus/inProgress changing as well? Or could the change in interaction status be the trigger for updating context, setting accounts to instance.getAllAccounts() (if it has changed).

It can. Specifically the `ACCOUNT_ADDED` and `ACCOUNT_REMOVED` events are emitted when a different browser tab or window signs in or out. The trigger to update both `inProgress` and `accounts` should be events.
