### ISSUE TITLE
Switching Users

### ISSUE THREAD

**Issue by kdubious** [AzureAD/microsoft-authentication-library-for-js#4403]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

^2.20.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

^2.0.6

### Description

Yesterday, User1 logged into the app in my browser while debugging. Today, my app loads, I see User 1's email in the app. Then the app redirects to the login page, I assume because the cached creds are expired now.

On the Azure login screen (https://login.microsoftonline.com/), I click to "Sign in with another account."

I try to log in as User 2, it all goes well, until I am redirected to my app, which still shows User 1. I am then redirected to the Azure login page again, with User 1's username already filled out.

### Error Message

None

### Msal Logs

I don't see anything useful

### MSAL Configuration

```javascript
{
        auth: {
          clientId: environment.clientId,
          authority: "https://login.microsoftonline.com/" + environment.tenant,
          redirectUri: environment.redirectUri,
          postLogoutRedirectUri: environment.redirectUri,
        },
        cache: {
          cacheLocation: BrowserCacheLocation.LocalStorage,
          storeAuthStateInCookie: isIE,
        },
        system: {
          loggerOptions: {
            loggerCallback: (
              level: LogLevel,
              message: string,
              containsPii: boolean
            ): void => {
              if (containsPii) {
                return;
              }
              switch (level) {
                case LogLevel.Error:
                  console.error(message);
                  return;
                case LogLevel.Info:
                  console.info(message);
                  return;
                case LogLevel.Verbose:
                  console.debug(message);
                  return;
                case LogLevel.Warning:
                  console.warn(message);
                  return;
              }
            },
            piiLoggingEnabled: false,
          },
        },
      }
```

### Relevant Code Snippets

```javascript
Not sure
```

### Reproduction Steps

1. Log in as User 1
2. wait for token to expire
3. open browser with expired token
4. try to log in as a diff user
5. end up in a circle

### Expected Behavior

I expect to be able to log in as a diff user... and NOT have to clear my cache

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

External (Customer)

**Comment by tnorling** [comment]
@kdubious Msal.js supports multiple accounts. In your example, `getAllAccounts` should contain both User1 and User2. Your application is responsible for choosing the account you want to use. I'm guessing your application is using something like `getAllAccounts()[0].username` to get the user's email, which would be why you're getting User1's email. 

If instead the desire is to display the _most recent_ signed in account one way to do this would be to call `setActiveAccount` after each successful login and replace the `getAllAccounts()[0]` call with `getActiveAccount()`. Check out the [account docs](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/accounts.md) if you want more information about these APIs.

**Comment by kdubious** [comment]
@tnorling Cannot tell you how much I love when someone can guess my code based on what to me is strange behavior... but to you is clearly a known feature. Thanks! I wondered the use case for that being an array.

I'll go check out the docs now.

**Comment by kdubious** [comment]
@tnorling ok, still a bit stuck. I'm using the Angular wrappers, so the route Guard is logging me in. Not sure where I can hook this:

```
function login() {
    return myMsalObj.loginPopup().then((response) => {
        // After a successful login set the active account to be the user that just logged in
        myMsalObj.setActiveAccount(response.account);
    });
}
```

Also, I'm using redirects, and I see this in the code:

```
     * IMPORTANT: It is NOT recommended to have code that is dependent on the resolution of the Promise. This function will navigate away from the current
     * browser window. It currently returns a Promise in order to reflect the asynchronous nature of the code running in this function.
     *
```

So how (else) can I know which of the accounts from getAllAccounts() is the most recent? Maybe compare the `idTokenClaims.exp` and take the largest?

**Comment by tnorling** [comment]
You could use the [event API](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/events.md) to listen for the `LOGIN_SUCCESS` event. I'd recommend registering this callback in the same place you instantiate `PublicClientApplication` to make sure it's added before the redirect response is processed.

Something like this:

```javascript
msalInstance.addEventCallback((message: EventMessage) => {
    if (message.eventType === EventType.LOGIN_SUCCESS) {
        msalInstance.setActiveAccount(message.payload.account);
     }
});
```

**Comment by kdubious** [comment]
I think in an Angular app, this is a good translation of your suggestion. It's in my `app.component.ts` `ngOnInit`:

```
this.broadcastService.inProgress$
        .pipe(
          filter(
            (status: InteractionStatus) => status === InteractionStatus.None
          ),
          takeUntil(this._destroying$)
        )
        .subscribe(() => {
          const all = this.authService.instance.getAllAccounts();
          let latest = all[0];
          all.forEach((element) => {
            if (element.idTokenClaims["exp"] > latest.idTokenClaims["exp"]) {
              latest = element;
            }
          });
          this.authService.instance.setActiveAccount(latest);
          this.setLoginDisplay();
        })
```

I surely need to deal with the case where there's not been a prior cached sign-in. (but it's Friday evening here.)

Thanks so much, will test this out and see if it's right.
