### ISSUE TITLE
Angular MsalInterceptor: add access token to custom header

### ISSUE THREAD

**Issue by eliott-loreal** [AzureAD/microsoft-authentication-library-for-js#4413]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.19.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.5

### Description

Is it possible to configure the interceptor to add the access token in a custom header in addition to the Authorization header?
There is a proxy in front of my backend that overwrites the Authorization header. I need to keep the token in another header.
Alternatively, is it possible to create a second custom interceptor in parallel to the MsalInterceptor for this need?

Thanks in advance.

### Source

External (Customer)

**Comment by sameerag** [comment]
@eliott-loreal We recommend adding the `accessToken` to the custom interceptor and call it after `MsalInterceptor` if you need to customize this experience. We do not support adding `accessToken` to other headers yet.
