### ISSUE TITLE
Is there a way to setup the access token expiration time/date? 

### ISSUE THREAD

**Issue by antoveritas** [AzureAD/microsoft-authentication-library-for-js#4414]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.21.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.1.0

### Description

Hey guys, I have the following scenario: 
By default the token that gets returned after successful sign-in keeps getting refreshed, resulting in the user NOT needing to sign-in again for days, sometimes even a week (the threshold is very high).
While its great for usability, I would like to configure an expiry date/time (lets say 3 days) that once it hits the mark, even the refresh token should not work and the user should be requested to sign-in again.

I went through  the documentation, the code samples and even the code library but I haven't found a way to configure the token expiry time/date manually. 

I was wondering maybe someone can point me in the right direction, or comment on my situation with any advice. 
Potentially its a known limitation and the feature is already in works? 

### Source

External (Customer)

**Comment by sameerag** [comment]
We do not support this unfortunately, partly because the tokens are stored in the browser cache for SPA apps and hence only shorter validity times are enabled by the service. More documentation on token lifetime is available [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/token-lifetimes.md). 

MSAL JS does not control the token validation time, this is usually set by the underlying service(STS or B2C etc)

**Comment by antoveritas** [comment]
**Refresh tokens:**
_Refresh tokens given to Single-Page Applications are limited-time refresh tokens (usually 24 hours from the time of retrieval). This is a non-adjustable, non-sliding window, lifetime. Whenever a refresh token is used to renew an access token, a new refresh token is fetched with the renewed access token. This new refresh token will have a lifetime equal to the remaining lifetime of the original refresh token. **Once a refresh token has expired, a new authorization code flow must be initiated to retrieve an authorization code and trade it for a new set of tokens.**_

**2 Questions:**
1. Based on the description above, the refresh token lifespan should be 24 hours OR less, but from my experience: going away for the weekend, coming back to the browser/app my session continues and I'm not required to re-login, in fact that stretched for days/weeks like my previous post. Is there an explanation for that behavior? 

2. Is there a way to fully logout programmatically, currently when we call msalService.logout/logoutRedirect it clears the session storage and navigates you to a select which account you would like to sign out off ADD, without selecting the account to sign out off ADD, the logout process is not complete. User will refresh the page and will automatically be logged in. Is there a way to fully logout the user programmatically without any UI interaction (essentially, I'm looking to logout the user from our app and the ADD session programmatically)? 
I believe this issue was discussed exactly a year ago in this thread: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2922#:~:text=Yes%2C%20because%20if%20you%20don,you%20are%20immediately%20logged%20in.

Even thought I pass the user account info as part of the logout (EndSessionRequest), I'm still met with the UI asking me question account I would like to log out of... 

In contrast, I tried the logout from Azure Portal and there was no follow-up UI asking me which account I would like to log-out off.

**Comment by antoveritas** [comment]
*bump* since I didn't receive a response yet  :)

**Comment by sameerag** [comment]
@antoveritas, Apologies for the delay. Please find the answers below:


> **Refresh tokens:** _Refresh tokens given to Single-Page Applications are limited-time refresh tokens (usually 24 hours from the time of retrieval). This is a non-adjustable, non-sliding window, lifetime. Whenever a refresh token is used to renew an access token, a new refresh token is fetched with the renewed access token. This new refresh token will have a lifetime equal to the remaining lifetime of the original refresh token. **Once a refresh token has expired, a new authorization code flow must be initiated to retrieve an authorization code and trade it for a new set of tokens.**_
> 
> **2 Questions:**
> 
> 1. Based on the description above, the refresh token lifespan should be 24 hours OR less, but from my experience: going away for the weekend, coming back to the browser/app my session continues and I'm not required to re-login, in fact that stretched for days/weeks like my previous post. Is there an explanation for that behavior?

Your login session is linked to the AAD session's lifetime and not the RT. MSAL exchanges the stale RT with the new RT in the background, with the help of session identifiers like `sid` or `login_hint` with the eSTS. If the service finds an active session, it will return a valid token, if it doesn't, it fails with interactive login. The server session life time is controlled by the service and not the SDK. 

The only confirmed way of logging out is to explicitly logout from the AAD session calling the `logout` API.

> 2. Is there a way to fully logout programmatically, currently when we call msalService.logout/logoutRedirect it clears the session storage and navigates you to a select which account you would like to sign out off ADD, without selecting the account to sign out off ADD, the logout process is not complete. User will refresh the page and will automatically be logged in. Is there a way to fully logout the user programmatically without any UI interaction (essentially, I'm looking to logout the user from our app and the ADD session programmatically)?
>    I believe this issue was discussed exactly a year ago in this thread: [MSAL logout() function requires to select account for whom user wants to logout #2922](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2922).
> 
> Even thought I pass the user account info as part of the logout (EndSessionRequest), I'm still met with the UI asking me question account I would like to log out of...
> 
> In contrast, I tried the logout from Azure Portal and there was no follow-up UI asking me which account I would like to log-out off.

This issue was in their queue (the server team) to not show the UI when there is a single user that can be mapped to the session (logout_hint, sid, etc etc). I need to check the latest there, have sent them the q. Will update once I hear from them.

cc @jasonnutter
