### ISSUE TITLE
Include activeAccount in the MSAL Context

### ISSUE THREAD

**Issue by ToshB** [AzureAD/microsoft-authentication-library-for-js#4416]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL React (@azure/msal-react)

### Description

I think it would be useful to include `activeAccount` in the MSAL Context (from MsalProvider). 

When performing token requests and other account operations I'm switching to using `instance.getActiveAccount()` (after setting this on login), instead of `accounts[0]` (after reading the suggestions [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4403)). This however, won't refresh my hooks. And I'd rather not include `accounts` in the hook dependencies just to refresh.

If I could instead make `activeAccount` a dependency for my hooks my code would be a lot clearer. 

### Source

External (Customer)

**Comment by tnorling** [comment]
@ToshB Thank you for opening this. PR #4280 will update the `useAccount` hook to return the current "active account" if no account identifiers are provided. Would this give you what you need?

**Comment by ToshB** [comment]
Ah, yes. That seems to work. Or perhaps both? 
As acquireTokenSilent-flow requires both instance, status/inProgress and accounts/active account, it's convenient when all are available through useMsal.

As I mentioned in #4402, accounts should preferable be updated withinProgress whenever any of them changes. So perhaps setting activeAccout as well would't be too out of place there.

**Comment by tnorling** [comment]
@ToshB 

> As acquireTokenSilent-flow requires both instance, status/inProgress and accounts/active account, it's convenient when all are available through useMsal.

If you're using the active account pattern you actually don't need to provide anything to `acquireTokenSilent`. If no account is provided on the request it will automatically check for an active account and attach it to your request.

I'd rather keep the specific account logic contained to `useAccount` for now but it's something we can consider in the future.

**Comment by ToshB** [comment]
> If you're using the active account pattern you actually don't need to provide anything to `acquireTokenSilent`. If no account is provided on the request it will automatically check for an active account and attach it to your request.

Oh, I didn't realize. That lets me clean up things quite a bit. I guess we can close this issue. Thanks for clarifying!
