### ISSUE TITLE
Generates invalid id_token (without signature) when it tries to redeem refresh_token

### ISSUE THREAD

**Issue by DelandPo** [AzureAD/microsoft-authentication-library-for-js#4417]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

I am using MSAL with Vue. The first login works as expected; however, If I leave the browser open for an hour and let the token expire and come back, it tries to generate a new token using refresh_token, and the HTTP POST call is successful. However, the received id_token(JWT) is missing the signature.  

### MSAL Configuration

```javascript
"VUE_APP_MSAL_CLIENT_ID": "435d45af-f20b-4463-9772-2ee946e4448d",
  "VUE_APP_AUTHORITY_URL": "https://login.microsoftonline.com/42447d67-83b5-4c50-8105-12858cff3899"
```

### Relevant Code Snippets

```javascript
const myMSALObj = new Msal.UserAgentApplication(msalConfig);

function signIn() {
  myMSALObj.loginPopup(loginRequest)
    .then(loginResponse => {
      console.log('id_token acquired at: ' + new Date().toString());
      console.log(loginResponse);

      if (myMSALObj.getAccount()) {
        showWelcomeMessage(myMSALObj.getAccount());
      }
    }).catch(error => {
      console.log(error);
    });
}

function signOut() {
  myMSALObj.logout();
}

function callMSGraph(theUrl, accessToken, callback) {
    var xmlHttp = new XMLHttpRequest();
    xmlHttp.onreadystatechange = function () {
        if (this.readyState == 4 && this.status == 200) {
           callback(JSON.parse(this.responseText));
        }
    }
    xmlHttp.open("GET", theUrl, true); // true for asynchronous
    xmlHttp.setRequestHeader('Authorization', 'Bearer ' + accessToken);
    xmlHttp.send();
}

function getTokenPopup(request) {
  return myMSALObj.acquireTokenSilent(request)
    .catch(error => {
      console.log(error);
      console.log("silent token acquisition fails. acquiring token using popup");

      // fallback to interaction when silent call fails
        return myMSALObj.acquireTokenPopup(request)
          .then(tokenResponse => {
            return tokenResponse;
          }).catch(error => {
            console.log(error);
          });
    });
}

function seeProfile() {
  if (myMSALObj.getAccount()) {
    getTokenPopup(loginRequest)
      .then(response => {
        callMSGraph(graphConfig.graphMeEndpoint, response.accessToken, updateUI);
        profileButton.classList.add('d-none');
        mailButton.classList.remove('d-none');
      }).catch(error => {
        console.log(error);
      });
  }
}

function readMail() {
  if (myMSALObj.getAccount()) {
    getTokenPopup(tokenRequest)
      .then(response => {
        callMSGraph(graphConfig.graphMailEndpoint, response.accessToken, updateUI);
      }).catch(error => {
        console.log(error);
      });
  }
}
```

### Reproduction Steps

1. Spin up the resources  https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-javascript-spa
2. Add your own client_id
3. Login and leave it for an hour. Make sure your token expires in an hour
4. Come back after an hour and try to log in. You will see /token response is incomplete

### Expected Behavior

Expect to receive valid id_token when redeeming refresh_token

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari

### Source

External (Customer)

**Comment by sameerag** [comment]
@DelandPo I am trying to reproduce this on my end and will reach out soon.

**Comment by ghost** [comment]
This issue requires attention from the MSAL.js team and has not seen activity in **5 days**. @sameerag please follow up.

**Comment by jasonnutter** [comment]
@DelandPo Can you please share a Fiddler trace demonstrating this behavior? Email is on my profile, thanks!
