### ISSUE TITLE
Cannot read properties of undefined (reading 'idTokenClaims') in the guard

### ISSUE THREAD

**Issue by virtazp** [AzureAD/microsoft-authentication-library-for-js#4419]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.1.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.1.0

### Description

Hello,

angular: 11.0.4

In my custom Guard file, I have this error: Cannot read properties of undefined (reading 'idTokenClaims')

This error appears on the first load and blocks the connection when I try to log "!account.idTokenClaims?.roles".

'this.authService.instance.getAllAccounts()[0]' = null.

I use this method: https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/tree/main/5-AccessControl/1-call-api-roles/SPA

I'm using Parameterized Roles in Azure AD.

At the first connection, I do not retrieve the user profile.

I tried to remove the guard on the homepage route, but the problem moves when clicking on a tab where the guard is applied.

I followed the tutorial mentioned above, except for the routes.

If I comment out the piece of code in my guard that triggers the error, the connection is established correctly but I cannot retrieve the roles.
If I log 'this.authService.instance.getAllAccounts()[0]' and browse through my application, the profile appears when switching tabs.
What if, once I've browsed and the profile has loaded, and uncommented the code that's throwing the error, it works.

### Error Message

Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'idTokenClaims')

### Msal Logs

[Wed, 19 Jan 2022 13:41:09 GMT] : @azure/msal-browser@2.20.0 : Verbose - Event callback registered with id: 3fa3a230-3215-46e3-b45b-c99a2cbad563
auth-config.ts:31 [Wed, 19 Jan 2022 13:41:09 GMT] : @azure/msal-angular@2.1.0 : Verbose - Guard - canActivate
auth-config.ts:31 [Wed, 19 Jan 2022 13:41:09 GMT] : @azure/msal-angular@2.1.0 : Verbose - MSAL Guard activated
auth-config.ts:31 [Wed, 19 Jan 2022 13:41:09 GMT] : @azure/msal-browser@2.20.0 : Verbose - handleRedirectPromise called
auth-config.ts:31 [Wed, 19 Jan 2022 13:41:10 GMT] : @azure/msal-browser@2.20.0 : Verbose - getAllAccounts called
auth-config.ts:31 [Wed, 19 Jan 2022 13:41:10 GMT] : @azure/msal-browser@2.20.0 : Info - Emitting event: msal:handleRedirectStart
auth-config.ts:31 [Wed, 19 Jan 2022 13:41:10 GMT] : @azure/msal-browser@2.20.0 : Verbose - Emitting event to callback 3fa3a230-3215-46e3-b45b-c99a2cbad563: msal:handleRedirectStart
auth-config.ts:31 [Wed, 19 Jan 2022 13:41:10 GMT] : @azure/msal-angular@2.1.0 : Verbose - BroadcastService - msal:handleRedirectStart results in setting inProgress from startup to handleRedirect
auth-config.ts:31 [Wed, 19 Jan 2022 13:41:10 GMT] : @azure/msal-browser@2.20.0 : Verbose - handleRedirectPromise has been called for the first time, storing the promise
auth-config.ts:31 [Wed, 19 Jan 2022 13:41:10 GMT] : [2e314e3d-9b06-49f0-95b3-b92aa7668654] : msal.js.browser@2.20.0 : Verbose - initializeServerTelemetryManager called
auth-config.ts:31 [Wed, 19 Jan 2022 13:41:10 GMT] : [2e314e3d-9b06-49f0-95b3-b92aa7668654] : msal.js.browser@2.20.0 : Info - handleRedirectPromise called but there is no interaction in progress, returning null.
auth-config.ts:31 [Wed, 19 Jan 2022 13:41:10 GMT] : @azure/msal-browser@2.20.0 : Verbose - getAllAccounts called
auth-config.ts:31 [Wed, 19 Jan 2022 13:41:10 GMT] : @azure/msal-browser@2.20.0 : Info - Emitting event: msal:handleRedirectEnd
auth-config.ts:31 [Wed, 19 Jan 2022 13:41:10 GMT] : @azure/msal-browser@2.20.0 : Verbose - Emitting event to callback 3fa3a230-3215-46e3-b45b-c99a2cbad563: msal:handleRedirectEnd
auth-config.ts:31 [Wed, 19 Jan 2022 13:41:10 GMT] : @azure/msal-angular@2.1.0 : Verbose - BroadcastService - msal:handleRedirectEnd results in setting inProgress from handleRedirect to none

### MSAL Configuration

```javascript
export const msalConfig: Configuration = {
     auth: {
         clientId: config.clientId, // This is the ONLY mandatory field that you need to supply.
         authority: 'https://login.microsoftonline.com/' + config.tenant, // Defaults to "https://login.microsoftonline.com/common"
         redirectUri: config.redirect, // Points to window.location.origin. You must register this URI on Azure portal/App Registration.
     },
     cache: {
         cacheLocation: BrowserCacheLocation.LocalStorage, // Configures cache location. "sessionStorage" is more secure, but "localStorage" gives you SSO between tabs.
         storeAuthStateInCookie: isIE, // Set this to "true" if you are having issues on IE11 or Edge
     },
     system: {
         loggerOptions: {
             loggerCallback(logLevel: LogLevel, message: string) {
                 console.log(message);
             },
             logLevel: LogLevel.Verbose,
             piiLoggingEnabled: false
         }
     }
 }
```

### Relevant Code Snippets

```javascript
app.module.ts

import { msalConfig, loginRequest, protectedResources } from './config/auth-config';
import { BrowserCacheLocation, InteractionType, IPublicClientApplication, LogLevel, PublicClientApplication } from '@azure/msal-browser';
import { MsalBroadcastService, MsalGuard, MsalGuardConfiguration, MsalInterceptor, MsalInterceptorConfiguration, MsalModule, MsalRedirectComponent, MsalService, MSAL_GUARD_CONFIG, MSAL_INSTANCE, MSAL_INTERCEPTOR_CONFIG } from '@azure/msal-angular';

export function MSALInstanceFactory(): IPublicClientApplication {
  return new PublicClientApplication(msalConfig);
}

export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
  const protectedResourceMap = new Map<string, Array<string>>();
  protectedResourceMap.set('https://graph.microsoft.com/v1.0/me', ['User.Read']);

  return {
    interactionType: InteractionType.Redirect,
    protectedResourceMap
  };
}

export function MSALGuardConfigFactory(): MsalGuardConfiguration {
  return {
    interactionType: InteractionType.Redirect,
    // authRequest: {
    //   scopes: ['user.read']
    // },
    authRequest: loginRequest,
    loginFailedRoute: '/login-failed'
  };
}

@NgModule({
  declarations: [
    AppComponent,
    MenuComponent,

    CandidatsListComponent,
    CandidatDetailsComponent,
    CandidatsListBlocComponent,
    AddCandidatModalComponent,
    EditCandidatModalComponent,
    OffresListComponent,
    OffresDetailsComponent,
    OffresListBlocComponent,
    OffresDetailsListBlocComponent,
    DocumentsComponent,
    DashboardComponent,
    OffreCandidatDetailsComponent,
    FiltreComponent,
    EditOffreModalComponent,
    AddOffreModalComponent,
    AddCandidatureModalComponent,
    EditCandidatureModalComponent,
    HeaderComponent,
    CorrecteurComponent,
    MailModalComponent,
    AddNoteComponent,
    LoadComponent,
    NouveautesComponent,
    FailedComponent,
  ],
  imports: [
    BrowserAnimationsModule,
    BrowserModule,
    AppRoutingModule,
    HttpClientModule,
    FormsModule,
    ReactiveFormsModule,
    InfiniteScrollModule,
    ToastrModule.forRoot({
      timeOut: 5000,
      // disableTimeOut: true,
      positionClass: 'toast-bottom-full-width',
      preventDuplicates: true,
      resetTimeoutOnDuplicate: true,
    }),
    MsalModule,
],
  providers: [
    {
      provide: HTTP_INTERCEPTORS,
      useClass: MsalInterceptor,
      multi: true
    },
    {
      provide: MSAL_INSTANCE,
      useFactory: MSALInstanceFactory
    },
    {
      provide: MSAL_GUARD_CONFIG,
      useFactory: MSALGuardConfigFactory
    },
    {
      provide: MSAL_INTERCEPTOR_CONFIG,
      useFactory: MSALInterceptorConfigFactory
    },
    MsalService,
    MsalGuard,
    MsalBroadcastService,
    // AuthguardService,
    OffreService,
    CandidatService,
    CandidatureService,
    CandidatureGlobalService,
    DocumentService,
    ApiHelperService,
    NgbActiveModal
  ],
  bootstrap: [AppComponent, MsalRedirectComponent]

Authguard.service.ts

canActivate(route: ActivatedRouteSnapshot): boolean {
    const expectedRole = route.data.expectedRole;
    const expectedRole2 = route.data.expectedRole2;

    let account: Account = this.authService.instance.getAllAccounts()[0];

    console.log(account); // <= null first

    if (!account.idTokenClaims?.roles) { // <= Cannot read ... (reading 'idTokenClaims')
      window.alert('Token does not have roles claim. Please ensure that your account is assigned to an app role and then sign-out and sign-in again.');
      return false;
    } else if (!account.idTokenClaims?.roles?.includes(expectedRole)) {
      window.alert('You do not have access as expected role is missing. Please ensure that your account is assigned to an app role and then sign-out and sign-in again.');
      return false;
    }
}

app-routing.module.ts

const routes: Routes = [
  { path: '', component: DashboardComponent, pathMatch: 'full', data: { expectedRole: roles.TaskAdmin } },
  { path: 'auth', component: MsalRedirectComponent },
  { path: 'login-failed', component: FailedComponent },
  { path: 'dashboard', component: DashboardComponent, canActivate: [MsalGuard, AuthguardService], data: { expectedRole: roles.TaskAdmin } },
  { path: 'offres', component: OffresListComponent, canActivate: [MsalGuard, AuthguardService], data: { expectedRole: roles.TaskAdmin } },
  { path: 'offres/:id', component: OffresDetailsComponent, canActivate: [MsalGuard, AuthguardService], data: { expectedRole: roles.TaskAdmin } },
  { path: 'profils', component: CandidatsListComponent, canActivate: [MsalGuard, AuthguardService], data: { expectedRole: roles.TaskAdmin } },
  { path: 'evaluateur-technique', component: CorrecteurComponent, canActivate: [MsalGuard, AuthguardService], data: { expectedRole: roles.TaskAdmin, expectedRole2: roles.TaskUser } },
  { path: 'documentation', component: DocumentsComponent, canActivate: [MsalGuard, AuthguardService], data: { expectedRole: roles.TaskAdmin, expectedRole2: roles.TaskUser } },
  { path: 'nouveautes', component: NouveautesComponent, canActivate: [MsalGuard, AuthguardService], data: { expectedRole: roles.TaskAdmin, expectedRole2: roles.TaskUser } },
];
```

### Reproduction Steps

1. Follow the tutorial mentioned above
2. Modify the app-routing.module.ts file with my configuration
3. Copy my canactivate method

### Expected Behavior

I need to fetch the profile on first app load, to avoid this error and manage roles.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Regression

@azure/msal-angular V1

### Source

External (Customer)

**Comment by sameerag** [comment]
@virtazp We require calling `handleRedirectObservable()` from the guard as demonstrated [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/src/msal.guard.ts) : line 132 - we do not inspect accounts until this API is called, this is because the previous `loginRedirect()`s response isn't handled until we call this API.

**Comment by virtazp** [comment]
Hello and thank you for your answer.

How should I go about in this case to retrieve the profile in this case, and then go through my guard?

Thank you

**Comment by sameerag** [comment]
@jasonnutter Can you help here?

**Comment by virtazp** [comment]
Hello,

I may have found a workaround.

The example provided works with a login page. I don't have a login page.

I can add a page to login, with the login button or subscribe to the handleRedirectObservable() method in my guard.


`canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): boolean | UrlTree {
  
    const expectedRole1 = route.data.expectedRole;
    const expectedRole2 = route.data.expectedRole2;

    let accounts = this.authService.instance.getAllAccounts();

    if (accounts.length > 0) {

      let role = accounts[0].idTokenClaims['roles'][0];

      if (role == 'role1' || role == 'role2') {

         // work
         
      } else {
        return false;
      }
    } else {
      this.authService.handleRedirectObservable().subscribe(() => {
        if (this.msalGuardConfig.authRequest) {
          this.authService.loginRedirect({ ...this.msalGuardConfig.authRequest } as RedirectRequest);
        } else {
          this.authService.loginRedirect();
        }
      });
    }
}`
    
I don't know if it's clean but it works.

Have a good day

**Comment by jasonnutter** [comment]
`handleRedirectPromise` should be called every time and should be called before `getAllAccounts`, otherwise, you could get into an infinite loop:

```typescript
const expectedRole1 = route.data.expectedRole;
const expectedRole2 = route.data.expectedRole2;

this.authService.handleRedirectObservable().subscribe((result) => {
    let accounts = this.authService.instance.getAllAccounts();

    if (accounts.length > 0) {

        let role = accounts[0].idTokenClaims['roles'][0]; // may be better to call result.account

        if (role == 'role1' || role == 'role2') {

            // work
            return true;
        } else {
            return false;
        }
    } else {
        if (this.msalGuardConfig.authRequest) {
            this.authService.loginRedirect({ ...this.msalGuardConfig.authRequest } as RedirectRequest);
        } else {
            this.authService.loginRedirect();
        }
    }
});

```

**Comment by virtazp** [comment]
It works ! 

Thanks for your help.

Have a good day.
