### ISSUE TITLE
Clearing access tokens after getting a new ID token

### ISSUE THREAD

**Issue by blockingHD** [AzureAD/microsoft-authentication-library-for-js#4421]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.21.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.1.0

### Description

We are using AzureB2C as our identity provider which gives a user an account number claim when they login. A user can login to multiple accounts in the app and can change the account throughout the user journey via a drop down. When the user changes account we use login redirect with query parameters to issue a new ID token with the new account number however this doesn't refresh the access tokens cached. This is not ideal. 

Current work around is forcing a refresh on every call. Is there a way of clearing the cache on these events? 

### MSAL Configuration

```javascript
{
    auth: environment.azureB2C,
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE // set to true for IE 11. Remove this line to use Angular Universal
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Info,
        piiLoggingEnabled: true
      }
    }
  }
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by sameerag** [comment]
@blockingHD Thanks for reaching out. In your case, can you please provide the "scopes" for the access tokens that you are trying to renew? Please note that access tokens are resource scoped, hence you may have to make separate requests for different resources.
