### ISSUE TITLE
How to use the proposed CustomNavigationClient(history) with the new react-router-dom v6 API

### ISSUE THREAD

**Issue by kai-dorschner-twinsity** [AzureAD/microsoft-authentication-library-for-js#4422]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.21.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.2.0

### Description

react-router-dom version 6 was released a while ago and it has some breaking API changes that have some contact surface with the msal-browser adapter for reducing hard page reloads with `CustomNavigationClient(history)`

**example code from you guys:** https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-react-samples/react-router-sample/src/App.js#L21-L23

**Breaking change of react-router-dom described here:** https://reactrouter.com/docs/en/v6/upgrading/v5#use-usenavigate-instead-of-usehistory

**My question is:** how are we supposed to adapt the replaced `useHistory() -> useLocation()` change.

### MSAL Configuration

```javascript
// irrelevant here
```

### Relevant Code Snippets

```javascript
// Copied and adapted from your example
function App({ pca }) {
  // The next 3 lines are optional. This is how you configure MSAL to take advantage of the router's navigate functions when MSAL redirects between pages in your app
  // const history = useHistory(); // Not available in react-router-dom v6
  const location = useLocation(); // the only thing we have now
  const navigationClient = new CustomNavigationClient(location); // <-- THIS WILL BREAK
  pca.setNavigationClient(navigationClient);

  return (
    <MsalProvider instance={pca}>
      <PageLayout>
        <Grid container justifyContent="center">
          <Pages />
        </Grid>
      </PageLayout>
    </MsalProvider>
  );
}
```

### Source

External (Customer)

**Comment by tnorling** [comment]
@kai-dorschner-twinsity The `CustomNavigationClient` in the sample is an example rather than part of our API surface, you should adapt it to your use case or to the routing library you use.

In the case of react-router-dom v6 something like this might work:

```javascript
export class CustomNavigationClient extends NavigationClient{
    constructor(navigate) {
        super();
        this.navigate = navigate;
    }
    async navigateInternal(url, options) {
        const relativePath = url.replace(window.location.origin, '');
        if (options.noHistory) {
            this.navigate(relativePath, { replace: true});
        } else {
            this.navigate(relativePath);
        }

        return false;
    }
}
```

**Comment by kai-dorschner-twinsity** [comment]
Hey Thomas,
thank you for your quick answer :) That helps us.

### For everybode else coming here from google
In order to safe anybody else half a day of figuring out what msal is trying to tell it wants and how to implement it in the target application (not the easiest library I used in my time) its probably better to rename "react-router-sample" to a more non-generic sample. Also the hint with the CustomNavigationClient itself is fairly hidden in the docs, despite being a huge performance gain.

Our working implementation for react-router-dom v6:
```typescript

/**
 * react-router-dom v6 implementation of msal NavigationClient
 * @see https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/3d1cbe7599bbc00da12159a1c0c5e4aa720fb7a6/samples/msal-react-samples/react-router-sample/src/utils/NavigationClient.js#L6
 */
export class CustomNavigationClient extends NavigationClient {
  constructor(private navigate: NavigateFunction) {
    super();
  }

  /**
   * Navigates to other pages within the same web application
   * You can use the useHistory hook provided by react-router-dom to take advantage of client-side routing
   * @param url
   * @param options
   */
  async navigateInternal(url: string, options: NavigationOptions) {
    const relativePath = url.replace(window.location.origin, '');
    if (options.noHistory) {
      this.navigate(relativePath, { replace: true });
    } else {
      this.navigate(relativePath);
    }

    return false;
  }
}
```

Final verdict: the mentioned example only works for `"react-router-dom": "<=5"`

Closing this issue, since our problem is solved.
Again thank you Thomas.
