### ISSUE TITLE
MSAL-React: Error when logging out user

### ISSUE THREAD

**Issue by AndreaEsposit** [AzureAD/microsoft-authentication-library-for-js#4423]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.20.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.1.2

### Description

The full application is wrapped with the MsalAuthenticationTemplate-component, as the application is not available for not-authenticated users. 

When trying to sign out (using the ClientApplication.logoutRedirect() function)  we are experiencing some unexpected behaviors, even though the logout process does indeed work. 
Right before getting redirected to the logout page, we run into the following error: 
`BrowserAuthError: no_account_error: No account object provided to acquireTokenSilent and no active account has been set. Please call setActiveAccount or provide an account on the request.`

We assumed that providing an AccountInfo object inside the EndSessionRequest (in the logoutRedirect-function) would fix the problem, but the issue continued to appear.
We then added an acquireTokenSilent to the sign-out process after finding a solution to a similar issue ([link](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/3569#issuecomment-833757141)) ... but the same error still presented itself. 
In the end, we also tried setting an active account, right before logging out, but the error still accrued. 

Are we missing something obvious here?

### MSAL Configuration

```javascript
{
    auth: {
        clientId: "***",
        authority: "https://login.microsoftonline.com/***",
        redirectUri: "/", // index page
    },
    cache: {
        cacheLocation: 'sessionStorage',
        storeAuthStateInCookie: false,
    },
};
```

### Relevant Code Snippets

```javascript
index.tsx:

const renderApp = () => {
    return ReactDOM.render(
        <MsalProvider instance={publicClientApplication}>
            <App />
        </MsalProvider>,
        document.getElementById('root'),
    );
};

All application is wrapped in this component: 
const AuthenticationHandler: FunctionComponent = ({ children }) => {
    const { accounts } = useMsal();
    const authRequest: RedirectRequest = { ...loginRequest, account: accounts[0] };
     return (
        <MsalAuthenticationTemplate
            interactionType={InteractionType.Redirect}
            errorComponent={ErrorComponent}
            loadingComponent={LoadingComponent}
            authenticationRequest={authRequest}
        >
            {children}
        </MsalAuthenticationTemplate>
    );
};

// signOut function

export const signOut = async (msalInstance: PublicClientApplication, account: AccountInfo) => {
    const token = await acquireTokenSilent(msalInstance, account);
    const activeAccount = msalInstance.getActiveAccount();
    if (!activeAccount) msalInstance.setActiveAccount(account);
    const logoutRequest: EndSessionRequest = { idTokenHint: token.idToken, account };
    msalInstance.logoutRedirect(logoutRequest).catch((e) => {
        console.error(e);
    });
};


const acquireTokenSilent = async (msalInstance: PublicClientApplication, account: AccountInfo) => {
    const request: SilentRequest = {
        ...loginRequest,
        account,
    };

    const authResult = await msalInstance.acquireTokenSilent(request);
    return authResult;
};
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by tnorling** [comment]
@AndreaEsposit This is happening because `acquireTokenSilent` is being called somewhere in your app **after** the logout has cleared the cached accounts. Most likely this is caused by one of your components re-rendering when the `logout` happens. Make sure all your calls to `acquireTokenSilent` check that 1. at least one user is signed in and 2. the `inProgress` variable is 'None'.

You do not need to call `acquireTokenSilent` or `setActiveAccount` before the logout.

**Comment by AndreaEsposit** [comment]
That makes sense, thank you. I will add those checks and close the issue if this solves our problem (I'm confident this will fix the problem, Might take some hours for me to test this though).

**Comment by AndreaEsposit** [comment]
It was exactly as @tnorling mentioned, some other components were trying to call `acquireTokenSilent `with clients. length = 0. 
By adding a simple check, we avoid the error, I am however curious to know if there Is a way to check the `inProgress `variable via the `PublicClientApplication`/`IPublicClientApplication `objects, or any other way that is not via the msal hook.
