### ISSUE TITLE
Intermittent 400 response when calling acquireTokenSilent

### ISSUE THREAD

**Issue by joshmouch** [AzureAD/microsoft-authentication-library-for-js#4424]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.16.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

Intermittently, when we call `acquireTokenSilent`, an HTTP 400 response will be returned from `POST https://login.microsoftonline.com/common/oauth2/v2.0/token`.  The error message in the returned value only says `monitor_window_timeout: Token acquisition in iframe failed due to timeout`.  

As a side note, the exception is raised *exactly* 6 seconds after the request is made.  Perhaps this is a coincidence, but it's very consistent.  I don't think this is relevant because an HTTP 400 response is being returned, which means there is no timeout... just a bad request.

I read the FAQ that talks about the "monitor_window_timeout" error, but none of the answers speak to why the error might be raised by a 400 response or why a 400 response might be returned.

Do you have any insight into what's triggering this 400, how I may be able to log additional details (e.g. what the request/response look like, or maybe a correlation id of some kind).  I read in the documentation that you can add a logging handler, but I don't know if that would provide more detail (at the error filter level) than what the error message currently has in the exception.  If you think it would be useful, can you change the logging level to verbose on an already instantiated `PublicClientApplication` object to log on the next `acquireTokenSilent` retry, and then change it back after the 2nd attempt so as to not overwhelm the logs??

The error message that is currently returned is pretty useless and there's no insight into where to look next.  In some other situations, I've seen the exception message can include a Correlation ID and other useful information, but this one just has `monitor_window_timeout: Token acquisition in iframe failed due to timeout`, and nothing else.

### Error Message

monitor_window_timeout: Token acquisition in iframe failed due to timeout

No additional detail at all.

### Msal Logs

N/A

### MSAL Configuration

```javascript
N/A
```

### Relevant Code Snippets

```javascript
N/A
```

### Reproduction Steps

This is intermittent and have not been able to reproduce in a control environment.

### Expected Behavior

Return a new token.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer, Other

### Regression

NA

### Source

External (Customer)

**Comment by sameerag** [comment]
@joshmouch My theory is that the request is being rejected before being processed by the service(in this case AAD) and hence the service which is invoked in an iframe in your case is not returned to MSAL JS. MSAL JS customarily waits for 6 seconds after spinning up a silent iframe for the server response before timing out.

Ideally the server page should display why the 400 is happening but since this is a silent request, the STS error is lost. We have seen this kind of pattern before but I thought we send a link to the URL a user can go to to retrieve the server error wrapped in the MSAL JS error messaging to the application. Please confirm that you do not see any additional data in the error description in your case, and I will check if we can add that.

**Comment by joshmouch** [comment]
Yes, I can confirm the error returned doesn't have any information about the 400 response.  Thank you for looking to add it.
In the mean time, are there workarounds for getting this? 
Out of curiosity,  where is that 6 seconds defined in this particular case? The documentation mentions the default silent iframe timeout is 10 seconds for other scenarios.

**Comment by joshmouch** [comment]
@sameerag Were you able to find anything additional on this?

**Comment by sameerag** [comment]
@joshmouch Need couple things from you, If you are able to consistently reproduce this, can you please send us:
* MSAL JS logs (logging docs [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/configuration.md))
* Fiddler trace 

You can send an email to me, mine is listed in my profile, for the fiddler.
