### ISSUE TITLE
Clarification of intent to support Angular releases

### ISSUE THREAD

**Issue by slubowsky** [AzureAD/microsoft-authentication-library-for-js#4425]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.21.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.1.0

### Description

Angular 13 was released 11/3/21. It is now 1/19/22
The readme for msal-angular (https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-angular#version-support) does not include version support for Angular 13.
The readme also states 

> At a minimum, @azure/msal-angular will follow the support schedule of the main Angular project

By default, Angular 13 uses RxJS 7, msal-angular requires RxJS 6. While it appears Angular 13 can be made to work using RxJS 6, this is not desirable.

There have been many issues raised touching on these various topics with a high amount of user engagement - but AFAIK no response has been made indicating if/when the library will be updated. (see for example https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4154#issuecomment-974183734 and https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4154#issuecomment-975930280)

I see that the msal roadmap (https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/roadmap.md) was updated yesterday 1/18/22 but no mention of an update for msal-angular is included in the plans for the upcoming quarter.

Can we get clarification on whether this project intends to release updates in a reasonable timeframe or if it is to be expected that long periods of time may elapse when this project is not compatible with the current Angular ecosystem?

Thank you!

 

### Source

External (Customer)

**Comment by sameerag** [comment]
@slubowsky Thanks for raising this. We are reviewing our plan on angular support and reach out with the roadmap that will clarify this support. Marking this as feature support on the [angular board](https://github.com/AzureAD/microsoft-authentication-library-for-js/projects/3).

**Comment by sameerag** [comment]
@EmLauber can we close this if this is tracked internally?

**Comment by EmLauber** [comment]
@sameerag  I'm happy to close this as we are tracking it internally as well as externally in other issues:  https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4154

**Comment by sameerag** [comment]
Thanks. Closing.
