### ISSUE TITLE
MSAL documentation: Passing null in postlogoutredirecturi

### ISSUE THREAD

**Issue by manavsharmaprog** [AzureAD/microsoft-authentication-library-for-js#4430]
### Core Library

MSAL.js v2 (@azure/msal-browser), MSAL.js v1 (@azure/msal or msal)

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Documentation Location

https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-sign-in?tabs=angular2

### Description

Found a solution to pass **null** in postlogoutredirecturi when a redirect is not needed.

[https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/2789](url)

May I please request you to bring the documentation up to speed with this small trick of passing null in postlogoutredirecturi.

My use case was that I was logging out and got redirected back to login screen with postlogoutredirecturi set to "".
Once I closed the browser and tried to log in again, it caused interaction_in_progress error on Chrome Dev console. Clearing the cookie manually didn't look like a good idea either. I know there're some better ways to handle redirects but a lot of people may end up bumping into a similar use case as mine.

**Comment by manavsharmaprog** [comment]
Here're the msal versions i'm using. Picked from package.json

```
"@azure/msal-angular": "^2.0.6",
"@azure/msal-browser": "^2.20.0",
```

**Comment by ellymakuba** [comment]
Please follow this link https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/configuration.md

**Comment by manavsharmaprog** [comment]
That helps, thank you!
So the MSAL Angular documentation is not a complete guide but builds on top of MSAL Browser documentation. Didn't realise that!
