### ISSUE TITLE
使用@azure/msal-react，acount信息获取不到

### ISSUE THREAD

**Issue by brucethomaswayne6** [AzureAD/microsoft-authentication-library-for-js#4431]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.21.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.2.0

### Description

https://stackblitz.com/edit/react-whfvxs?file=src/pages/home/home.js

麻烦看看我这个写的demo有什么问题吗？App.js中的event没有触发，home.js下account账户信息获取不到。

### Source

External (Customer)

**Comment by ellymakuba** [comment]
Could you please translate this into English?
