### ISSUE TITLE
[Msal for Angular v2.1.x] How to do Dynamic configuration

### ISSUE THREAD

**Issue by JIBIN-P** [AzureAD/microsoft-authentication-library-for-js#4432]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.21.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.1.0

### Description

Hi I referred to https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/481 & https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1403, but it seems a lot has changed in v2.1 so can anybody help me out on how to do dynamic configurations for v2.1.x

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by ellymakuba** [comment]
Hello, please try out this link https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/configuration.md

**Comment by JIBIN-P** [comment]
@ellymakuba thankieww so much for linking me to the appropriate documentation for dynamic configuration, the app_initilizer method helped get the job done.
