### ISSUE TITLE
 TeamMember.ReadWrite.All not in token

### ISSUE THREAD

**Issue by mkohns** [AzureAD/microsoft-authentication-library-for-js#4437]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.21.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

not-applicable

### Description

Hi, these are the permissions configured at my AppReg

![image](https://user-images.githubusercontent.com/4640562/150695986-894fde10-c488-44bd-aeed-68cc41e77d66.png)

When logging in a user, I get an response from https://login.microsoftonline.com/{my-tentant-id}/oauth2/v2.0/token with following scopes

![image](https://user-images.githubusercontent.com/4640562/150695805-bd918701-9d87-42d6-8250-8173d4a41091.png)

Questions: 
1) All scopes are present BESIDES TeamMember.ReadWrite.All. Why is this the case? 
2) How can I get the a token with scope TeamMember.ReadWrite.All?

### MSAL Configuration

```javascript
msalConfig: {
        auth: {
          clientId: process.env.VUE_APP_CLIENTID,
          authority: process.env.VUE_APP_AUTHORITY,
        },
        cache: {
          cacheLocation: "sessionStorage",
        },
        system: {
          allowRedirectInIframe: true,
        },
      },
      accessToken: "",
    };
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by ellymakuba** [comment]
Probing further, will get back to you as soon as possible.

**Comment by ellymakuba** [comment]
Two steps to having scopes on the client side
1. Register the permissions to your app in azure portal (which you have done)
2. Request the permission(s) in your scopes payload from your library (I suspect you have not done)

Please provide your request payload I need to check for discrepancies.
