### ISSUE TITLE
Is there any way to Azure AD and Azure AD B2C working together in the same application?

### ISSUE THREAD

**Issue by danielweil** [AzureAD/microsoft-authentication-library-for-js#4438]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.19.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.1.1

### Description

Is there any way to Azure AD and Azure AD B2C working together in the same application?

For instance, I need Azure AD to handle login in all application, except in one page. But, if the user has already authenticated in one of the providers, he should be able to access the other pages (Application Authorization would handle it). So if the user is not autenticated and access the single page it required b2c, it should redirect him to B2C login, all others Azure AD.

I tried doing it with 2 MsalProviders, each with a single config and also tried passing the instances through props, and calling redirect through it. Have a hard time making it work.

### Source

Internal (Microsoft)

**Comment by ellymakuba** [comment]
Please provide more context: What steps are you executing to get where you are stuck? and share your configuration file and the request you are sending.

**Comment by danielweil** [comment]
First, I tried using only one provider using a ternary operation in the instance prop:

![image](https://user-images.githubusercontent.com/44274213/150840860-ec420eff-2937-4a4c-a388-198d81a1c293.png)

And in the MsalAuth component I called the useMsalAuthentication hook:

![image](https://user-images.githubusercontent.com/44274213/150840248-a4dbf42d-35d9-444c-80df-e159105cc559.png)

The Azure AD login in the home page worked out, and when I entered the page where B2C is supposed to login in, it kept the session like I wanted to. When I open another incognito tab to start the login flow from the B2C page, it redirects correctly, but keeps getting stuck on the state parameter in the url.

![image](https://user-images.githubusercontent.com/44274213/150840542-ff047cd3-cd7e-4377-91b0-225830c5c94e.png)

Then I tried using two providers, but I realized all the hooks wouldn't be able to correctly find the right context.

![image](https://user-images.githubusercontent.com/44274213/150840771-08b46279-30cc-4a09-b84c-9ef4790b1877.png)

Lastly, I tried passing my PublicClientApplications instances through props, and It worked until it kept going into an infinite loop. I was not able to find a way to get the interaction status to see if it was in progress without using hooks. So I wasn't able to move forward.

I tried using a provider for Azure AD and manually calling redirect for B2C, but got stuck in the same loop problem.

Here are my config files:

B2C:

![image](https://user-images.githubusercontent.com/44274213/150841354-3e0d116f-5190-480e-b3ca-3f0796075772.png)

AD:
![image](https://user-images.githubusercontent.com/44274213/150841398-10b905c0-f877-4bed-a36e-e854c5af4211.png)

Which way to you guys rec·ommend going with, and it is indeed possible to make it work?

**Comment by jasonnutter** [comment]
@danielweil Have you tried configuring your B2C application to federate to AAD, instead of integrating with AAD directly? 

Docs: https://docs.microsoft.com/azure/active-directory-b2c/identity-provider-azure-ad-single-tenant?pivots=b2c-custom-policy
