### ISSUE TITLE
MSAL Interceptor not adding bearer token to the API call after authenticated from AD

### ISSUE THREAD

**Issue by sujithgundlapalli** [AzureAD/microsoft-authentication-library-for-js#4442]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.21.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.1.0

### Description

We are upgrading from msal v1 to msal v2 and using redirect method of login. In AD app registered under SPA and did not select Implicit grant and hybrid flows checkboxs as we are using MSAL V2. 
AD authentication is happening and I can see token request success and its redirecting to app. But after authentication , token is being added to api call automatically by Interceptor though all the necessary configuration is in place according to official documentation.

Note : when I run the sample app using our client and tenant details, its working perfectly for the graph api call - token is passing.

### Error Message

![image](https://user-images.githubusercontent.com/41381361/150917150-dd00d215-7f9b-485c-8297-ee9e8fc78f9b.png)

![image](https://user-images.githubusercontent.com/41381361/150917197-ae13bc56-0e60-4bf4-8bdf-a73a08f63e9e.png)

### Msal Logs

Navigated to https://localhost:4200/my-work/work-list
3DevTools failed to load source map: Could not load content for https://localhost:4200/sockjs.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
VM11:452571 Msal Logging: [Tue, 25 Jan 2022 05:09:23 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:loginStart
VM11:452583 [Tue, 25 Jan 2022 05:09:23 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:loginStart
VM11:73415 Angular is running in development mode. Call enableProdMode() to enable production mode.
VM11:452571 Msal Logging: [Tue, 25 Jan 2022 05:09:23 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:handleRedirectStart
VM11:452583 [Tue, 25 Jan 2022 05:09:23 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:handleRedirectStart
VM11:452571 Msal Logging: [Tue, 25 Jan 2022 05:09:23 GMT] : [6a37a070-f9d7-4f1b-9f5f-5de7ab2badb6] : msal.js.browser@2.21.0 : Info - handleRedirectPromise called but there is no interaction in progress, returning null.
VM11:452583 [Tue, 25 Jan 2022 05:09:23 GMT] : [6a37a070-f9d7-4f1b-9f5f-5de7ab2badb6] : msal.js.browser@2.21.0 : Info - handleRedirectPromise called but there is no interaction in progress, returning null.
VM11:73415 Angular is running in development mode. Call enableProdMode() to enable production mode.
VM11:452571 Msal Logging: [Tue, 25 Jan 2022 05:09:23 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:handleRedirectEnd
VM11:452583 [Tue, 25 Jan 2022 05:09:23 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:handleRedirectEnd
VM11:604772 msal:in progress
VM11:452571 Msal Logging: [Tue, 25 Jan 2022 05:09:23 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:loginStart
VM11:452583 [Tue, 25 Jan 2022 05:09:23 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:loginStart
Navigated to https://login.microsoftonline.com/.../oauth2/v2.0/authorize?client_id=....&scope=user.read%20openid%20profile%20offline_access&redirect_uri=https%3A%2F%2Flocalhost%3A4200%2F&client-request-id=......
main.js:73 BSSO Telemetry: {"result":"Error","error":"NoExtension","type":"ChromeSsoTelemetry","data":{},"traces":["BrowserSSO Initialized","Creating ChromeBrowserCore provider","Sending message for method CreateProviderAsync","Received message for method CreateProviderAsync","Error: ChromeBrowserCore error NoExtension: Extension is not installed."]}
DevTools failed to load source map: Could not load content for https://login.microsoftonline.com/.../oauth2/v2.0/7941c8df4f140717a949.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
favicon.ico:1 GET https://login.microsoftonline.com/favicon.ico 404 (Not Found)
Navigated to https://login.microsoftonline.com/.../oauth2/v2.0/authorize?client_id=...&scope=user.read%20openid%20profile%20offline_access&redirect_uri=https%3A%2F%2Flocalhost%3A4200%2F&client-request-id=....
VM16:13 [Violation] 'setTimeout' handler took 98ms
[Violation] Forced reflow while executing JavaScript took 73ms
Navigated to https://gfs2.glb.kworld.kpmg.com/adfs/ls/?client-request-id=....
chrome-error://chromewebdata/:1 Failed to load resource: the server responded with a status of 401 ()
Navigated to chrome-error://chromewebdata/
Navigated to https://gfs2.glb.kworld.kpmg.com/adfs/ls/wia?client-request-id=....
favicon.ico:1 GET https://gfs2.glb.kworld.kpmg.com/favicon.ico 404 (Not Found)
Navigated to https://login.microsoftonline.com/login.srf
Navigated to https://localhost:4200/
3DevTools failed to load source map: Could not load content for https://localhost:4200/sockjs.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
main.js:452571 Msal Logging: [Tue, 25 Jan 2022 05:09:55 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:loginStart
main.js:452583 [Tue, 25 Jan 2022 05:09:55 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:loginStart
main.js:73415 Angular is running in development mode. Call enableProdMode() to enable production mode.
main.js:452571 Msal Logging: [Tue, 25 Jan 2022 05:09:55 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:handleRedirectStart
main.js:452583 [Tue, 25 Jan 2022 05:09:55 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:handleRedirectStart
main.js:73415 Angular is running in development mode. Call enableProdMode() to enable production mode.
main.js:452571 Msal Logging: [Tue, 25 Jan 2022 05:09:55 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:loginFailure
main.js:452583 [Tue, 25 Jan 2022 05:09:55 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:loginFailure
main.js:47887 ERROR Error: Uncaught (in promise): BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.  For more visit: aka.ms/msaljs/browser-errors.
BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.  For more visit: aka.ms/msaljs/browser-errors.
    at BrowserAuthError.AuthError [as constructor] (main.js:162927:20)
    at new BrowserAuthError (main.js:152364:24)
    at Function.BrowserAuthError.createInteractionInProgressError (main.js:152452:12)
    at RedirectClient.<anonymous> (main.js:155148:94)
    at step (main.js:147797:17)
    at Object.next (main.js:147728:14)
    at main.js:147700:67
    at new ZoneAwarePromise (polyfills.js:14512:23)
    at __awaiter (main.js:147679:10)
    at RedirectClient.StandardInteractionClient.preflightInteractiveRequest (main.js:155139:72)
    at resolvePromise (polyfills.js:14412:21)
    at polyfills.js:14307:11
    at polyfills.js:14324:27
    at ZoneDelegate.invoke (polyfills.js:13339:160)
    at Object.onInvoke (main.js:74154:25)
    at ZoneDelegate.invoke (polyfills.js:13339:48)
    at Zone.run (polyfills.js:13065:37)
    at polyfills.js:14485:28
    at ZoneDelegate.invokeTask (polyfills.js:13372:173)
    at Object.onInvokeTask (main.js:74142:25)
defaultErrorLogger @ main.js:47887
handleError @ main.js:47940
next @ main.js:74929
__tryOrUnsub @ main.js:407452
next @ main.js:407379
_next @ main.js:407315
next @ main.js:407285
next @ main.js:407023
emit @ main.js:70902
(anonymous) @ main.js:74180
ZoneDelegate.invoke @ polyfills.js:13339
Zone.run @ polyfills.js:13065
runOutsideAngular @ main.js:74045
onHandleError @ main.js:74180
ZoneDelegate.handleError @ polyfills.js:13343
Zone.runGuarded @ polyfills.js:13085
_loop_2 @ polyfills.js:14245
api.microtaskDrainDone @ polyfills.js:14258
drainMicroTaskQueue @ polyfills.js:13595
Promise.then (async)
scheduleMicroTask @ polyfills.js:13567
ZoneDelegate.scheduleTask @ polyfills.js:13362
Zone.scheduleTask @ polyfills.js:13170
Zone.scheduleMicroTask @ polyfills.js:13195
scheduleResolveOrReject @ polyfills.js:14473
ZoneAwarePromise.then @ polyfills.js:14674
bootstrapModule @ main.js:74974
965878 @ main.js:519400
__webpack_require__ @ runtime.js:23
__webpack_exec__ @ main.js:607223
(anonymous) @ main.js:607224
webpackJsonpCallback @ runtime.js:321
(anonymous) @ main.js:1
Navigated to https://localhost:4200/my-work/work-list
3DevTools failed to load source map: Could not load content for https://localhost:4200/sockjs.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
main.js:452571 Msal Logging: [Tue, 25 Jan 2022 05:09:57 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:loginStart
main.js:452583 [Tue, 25 Jan 2022 05:09:57 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:loginStart
main.js:73415 Angular is running in development mode. Call enableProdMode() to enable production mode.
main.js:452571 Msal Logging: [Tue, 25 Jan 2022 05:09:57 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:handleRedirectStart
main.js:452583 [Tue, 25 Jan 2022 05:09:57 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:handleRedirectStart
main.js:73415 Angular is running in development mode. Call enableProdMode() to enable production mode.
main.js:452571 Msal Logging: [Tue, 25 Jan 2022 05:09:57 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:loginFailure
main.js:452583 [Tue, 25 Jan 2022 05:09:57 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:loginFailure
main.js:47887 ERROR Error: Uncaught (in promise): BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.  For more visit: aka.ms/msaljs/browser-errors.
BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.  For more visit: aka.ms/msaljs/browser-errors.
    at BrowserAuthError.AuthError [as constructor] (main.js:162927:20)
    at new BrowserAuthError (main.js:152364:24)
    at Function.BrowserAuthError.createInteractionInProgressError (main.js:152452:12)
    at RedirectClient.<anonymous> (main.js:155148:94)
    at step (main.js:147797:17)
    at Object.next (main.js:147728:14)
    at main.js:147700:67
    at new ZoneAwarePromise (polyfills.js:14512:23)
    at __awaiter (main.js:147679:10)
    at RedirectClient.StandardInteractionClient.preflightInteractiveRequest (main.js:155139:72)
    at resolvePromise (polyfills.js:14412:21)
    at polyfills.js:14307:11
    at polyfills.js:14324:27
    at ZoneDelegate.invoke (polyfills.js:13339:160)
    at Object.onInvoke (main.js:74154:25)
    at ZoneDelegate.invoke (polyfills.js:13339:48)
    at Zone.run (polyfills.js:13065:37)
    at polyfills.js:14485:28
    at ZoneDelegate.invokeTask (polyfills.js:13372:173)
    at Object.onInvokeTask (main.js:74142:25)
defaultErrorLogger @ main.js:47887
handleError @ main.js:47940
next @ main.js:74929
__tryOrUnsub @ main.js:407452
next @ main.js:407379
_next @ main.js:407315
next @ main.js:407285
next @ main.js:407023
emit @ main.js:70902
(anonymous) @ main.js:74180
ZoneDelegate.invoke @ polyfills.js:13339
Zone.run @ polyfills.js:13065
runOutsideAngular @ main.js:74045
onHandleError @ main.js:74180
ZoneDelegate.handleError @ polyfills.js:13343
Zone.runGuarded @ polyfills.js:13085
_loop_2 @ polyfills.js:14245
api.microtaskDrainDone @ polyfills.js:14258
drainMicroTaskQueue @ polyfills.js:13595
Promise.then (async)
scheduleMicroTask @ polyfills.js:13567
ZoneDelegate.scheduleTask @ polyfills.js:13362
Zone.scheduleTask @ polyfills.js:13170
Zone.scheduleMicroTask @ polyfills.js:13195
scheduleResolveOrReject @ polyfills.js:14473
ZoneAwarePromise.then @ polyfills.js:14674
bootstrapModule @ main.js:74974
965878 @ main.js:519400
__webpack_require__ @ runtime.js:23
__webpack_exec__ @ main.js:607223
(anonymous) @ main.js:607224
webpackJsonpCallback @ runtime.js:321
(anonymous) @ main.js:1
main.js:452571 Msal Logging: [Tue, 25 Jan 2022 05:09:57 GMT] : [d9b12d39-7b34-4860-9541-1a31885e3f7a] : @azure/msal-common@6.0.0 : Info - in acquireToken call
main.js:452583 [Tue, 25 Jan 2022 05:09:57 GMT] : [d9b12d39-7b34-4860-9541-1a31885e3f7a] : @azure/msal-common@6.0.0 : Info - in acquireToken call
main.js:452571 Msal Logging: [Tue, 25 Jan 2022 05:09:58 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:loginSuccess
main.js:452583 [Tue, 25 Jan 2022 05:09:58 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:loginSuccess
main.js:452571 Msal Logging: [Tue, 25 Jan 2022 05:09:58 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:handleRedirectEnd
main.js:452583 [Tue, 25 Jan 2022 05:09:58 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:handleRedirectEnd
main.js:604772 msal:in progress
polyfills.js:16769 GET https://localhost:4200/client/api/user/.... 401 (Unauthorized)
scheduleTask @ polyfills.js:16769
ZoneDelegate.scheduleTask @ polyfills.js:13360
onScheduleTask @ polyfills.js:13253
ZoneDelegate.scheduleTask @ polyfills.js:13355
Zone.scheduleTask @ polyfills.js:13170
Zone.scheduleMacroTask @ polyfills.js:13199
scheduleMacroTaskWithCurrentZone @ polyfills.js:13759
(anonymous) @ polyfills.js:16814
proto.<computed> @ polyfills.js:14121
(anonymous) @ main.js:39366
_trySubscribe @ main.js:406633
subscribe @ main.js:406615
subscribeToResult @ main.js:419955
_innerSub @ main.js:413766
_tryNext @ main.js:413759
_next @ main.js:413740
next @ main.js:407285
.
.
.
.

bootstrapModule @ main.js:74974
965878 @ main.js:519400
__webpack_require__ @ runtime.js:23
__webpack_exec__ @ main.js:607223
(anonymous) @ main.js:607224
webpackJsonpCallback @ runtime.js:321
(anonymous) @ main.js:1
Show 213 more frames
main.js:47887 ERROR Error: Uncaught (in promise): HttpErrorResponse: {"headers":{"normalizedNames":{},"lazyUpdate":null},"status":401,"statusText":"Unauthorized","url":"https://localhost:4200/client/api/user/...","ok":false,"name":"HttpErrorResponse","message":"Http failure response for https://localhost:4200/client/api/user/...: 401 Unauthorized","error":null}
    at resolvePromise (polyfills.js:14412:21)
    at resolvePromise (polyfills.js:14359:11)
    at polyfills.js:14486:11
    at ZoneDelegate.invokeTask (polyfills.js:13372:173)
    at Object.onInvokeTask (main.js:74142:25)
    at ZoneDelegate.invokeTask (polyfills.js:13372:56)
    at Zone.runTask (polyfills.js:13122:39)
    at drainMicroTaskQueue (polyfills.js:13588:25)
    at ZoneTask.invokeTask [as invoke] (polyfills.js:13470:13)
    at invokeTask (polyfills.js:14912:12)
defaultErrorLogger @ main.js:47887
handleError @ main.js:47940
next @ main.js:74929
__tryOrUnsub @ main.js:407452
next @ main.js:407379
_next @ main.js:407315
next @ main.js:407285
next @ main.js:407023
.
.
.
### MSAL Configuration

```javascript
export function MSALInstanceFactory(): IPublicClientApplication {
  return new PublicClientApplication({
    auth: {
      clientId: `${environment.adalClientId}`,
      authority: `${environment.adalTenant}`,
      redirectUri: "https://localhost:4200/",
      postLogoutRedirectUri: "https://localhost:4200/"
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE 
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Info,
        piiLoggingEnabled: false
      }
    }
  });
}

export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
  const protectedResourceMap = new Map<string, Array<string>>();
  protectedResourceMap.set('/gms-compliance-trans', null); 
  protectedResourceMap.set('/gms-compliance-perf', null);
  protectedResourceMap.set(`${environment.FIRMWIDE_API_BASE_URL}`, null);
  return {
    interactionType: InteractionType.Redirect,
    protectedResourceMap
  };
}

export function MSALGuardConfigFactory(): MsalGuardConfiguration {
  return {
    interactionType: InteractionType.Redirect,
    authRequest: {
      scopes: ['user.read', 'openid', 'profile']
    },
    loginFailedRoute: '/unauthorized'
  };
}

  providers: [
    {
      provide: HTTP_INTERCEPTORS,
      useClass: MsalInterceptor,
      multi: true
    },
    {
      provide: MSAL_INSTANCE,
      useFactory: MSALInstanceFactory
    },
    {
      provide: MSAL_GUARD_CONFIG,
      useFactory: MSALGuardConfigFactory
    },
    {
      provide: MSAL_INTERCEPTOR_CONFIG,
      useFactory: MSALInterceptorConfigFactory
    },
    MsalService,
    MsalGuard,
    MsalBroadcastService
 ]
```

### Relevant Code Snippets

```javascript
public login(){

    if (this.msalGuardConfig.authRequest) {
      return this.msalService.loginRedirect({
        ...this.msalGuardConfig.authRequest
      } as RedirectRequest);
    } else {
      return this.msalService.loginRedirect();
    }
}

this.msalBroadcastService.msalSubject$
.pipe(
  filter(
	(msg: EventMessage) => msg.eventType === EventType.LOGIN_SUCCESS
  )
)
.subscribe((result: EventMessage) => {        
  const payload = result.payload as AuthenticationResult;
  this.msalService.instance.setActiveAccount(payload.account);
  const account = this.msalService.instance.getActiveAccount();
  // calling user api
  this.authService.getUser().then(isActive => { 
	console.log('user loaded : ', isActive);
	if (!isActive) {
	  return (this.showContent = true);
	}
  });
});
```

### Reproduction Steps

Use above configuration and just used basic redirect code same as the samples from official doc

### Expected Behavior

Token should be sent for api calls once authenticated from AD

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Internet Explorer

### Regression

MSAL V1

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@Sujith2020 In MSAL Angular v2, MSAL Angular will no longer automatically attach a token to API requests to routes on your app.

Add this to your configuration:

```js
protectedResourceMap.set('/client/api/user/*', [ "scope-for-this-api"]);
```

More: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/msal-interceptor.md
