### ISSUE TITLE
Add support for the OIDC `max_age` parameter

### ISSUE THREAD

**Issue by kevindixon** [AzureAD/microsoft-authentication-library-for-js#4445]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

Not Applicable

### Description

The ability to force re-authentication by setting the OIDC `max_age` option ([ref](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest)) was added to the MSAL Python library some time ago ([1.15](https://github.com/AzureAD/microsoft-authentication-library-for-python/releases/tag/1.15.0)).

We have a need to FORCE re-authentication on a JS based SPA where a user is carrying out a privileged action (this is highly regulated environment) - could this feature be added to `PublicClientApplication` in parity with MSAL Python?

(BTW see [this article](https://auth0.com/docs/authenticate/login/max-age-reauthentication) to understand why `login=prompt` isn't a good solution).

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@kevindixon We'll add this to our backlog, thanks! cc @EmLauber

**Comment by kevindixon** [comment]
Any indication when this might land? Its a showstopper for us....

**Comment by EmLauber** [comment]
Thanks for the feedback. It won't land in the current quarter as our priorities are already full (see https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/roadmap.md), but we will evaluate it for next quarter (CY22Q2).

**Comment by kevindixon** [comment]
Thanks for letting me know @EmLauber  - "evaluate it" sounds mighty unsure re: CY22Q2. Do you have an indication when plans for next quarter will be clearer? (Reason being, we'll need to assess ourselves whether to implement our own solution or look elsewhere).

**Comment by EmLauber** [comment]
We start our quarterly planning period in March and it typically takes a month to gather, validate, and prioritize all the asks. I'll know more by end of March.

**Comment by EmLauber** [comment]
Hi @kevindixon we added this to our CY22Q2 planning period (April-June). We'll have updates on what release specifically once the team starts developing on it.

**Comment by svrooij** [comment]
@kevindixon if it really is a showstopper, maybe spend some time in implementing it yourself.

That’s always working for us, if we don’t want to wait on others implementing it. I cannot look in your time or capabilities, but the team is accepting PR’s often.

**Comment by kevindixon** [comment]
@EmLauber CY22Q2 is drawing to a close - any update?

**Comment by EmLauber** [comment]
Thanks for following up. Due to changing priorities, we were unable to work on this in CY22Q2. It is still in our backlog. If that does not work for your timeline, we are open to PRs!

**Comment by bgavrilMS** [comment]
Just out of curiosity, can't the same requirement be achieved with Conditional Access policies - https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes#refresh-and-session-token-lifetime-policy-properties ? This would imply no code change in MSAL.

**Comment by svrooij** [comment]
@bgavrilMS if I may pitch in, what he is trying to accomplish is something like this:

You have this banking app (eg.) where the user is logged in. Now the user wants to transfer money, while accessing the balance it doesn't really matter for how long the session is alive. But for transferring money (privileged action) the app wants the user to re-authenticate or at least trigger a new MFA call.

So the app (JavaScript in this case) wants to trigger the user to prove his identity with MFA. I'm not sure how that would work with conditional access policies.

**Comment by bgavrilMS** [comment]
I don't know who to achieve this exactly, but does `max_age` solve it? You cannot force MFA this way?

Either the Identity Provider or the RP must challenge the user, e.g. the RP can return a 401 Unauthorized and include a WWW-Authenticate header which contains some claims. The app then requests a new token (interactively) and includes these claims in the request to the Identity Provider (AAD). This triggers MFA. 

@jmprieur can probably clarify this

**Comment by svrooij** [comment]
This is the first reference I could find that mentions max_age. It's in the openid connect spec and Microsoft implemented it in Azure AD.

https://hajekj.net/2017/03/06/forcing-reauthentication-with-azure-ad/

You can use it to force re-authentication from the client side, but reading your explanation I guess you can implement continuous access evaluation to force re-authentication from the API side. I don't have a good sample to do that, by the way.
