### ISSUE TITLE
MSAL together with NextJS keeps redirecting in infinite loop + no_cached_authority_error when using dynamic routes

### ISSUE THREAD

**Issue by danielweil** [AzureAD/microsoft-authentication-library-for-js#4446]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.19.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.1.1

### Description

I am using NextJS and when I try to start a new session directly in a dynamic route, MSAL keeps redirecting me in a infinite loop. If I preserve browser log and ask for verbose logs, it also prints out no_cached_authority_error.

This only happens in dynamic routes. I did a test and replaced the dynamic route with a static one, but the URL in test was the same. It worked correctly.

I did an experiment altering the page to a static route. It worked. After it, I tried using query parameters to then redirect inside my application to the correct route, after the login was made successfully. It turned out to give the same problem. I tried next using URL Hashes, and I was able to redirect internally. Will keep it this way until we figure out why dynamic/route params doesn't work.

### Error Message

Redirect loop + no_cached_authority_error

### Msal Logs

Navigated to https://login.microsoftonline.com/common/SAS/ProcessAuth
Navigated to http://localhost:3000/
_app.tsx:27 startup
auth.ts:35 [Tue, 25 Jan 2022 18:46:17 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:handleRedirectStart
auth.ts:35 [Tue, 25 Jan 2022 18:46:17 GMT] : @azure/msal-react@1.1.1 : Info - MsalProvider - msal:handleRedirectStart results in setting inProgress from startup to handleRedirect
2_app.tsx:27 handleRedirect
Navigated to http://localhost:3000/submissions/new/2
_app.tsx:27 startup
auth.ts:35 [Tue, 25 Jan 2022 18:46:17 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:handleRedirectStart
auth.ts:35 [Tue, 25 Jan 2022 18:46:17 GMT] : @azure/msal-react@1.1.1 : Info - MsalProvider - msal:handleRedirectStart results in setting inProgress from startup to handleRedirect
2_app.tsx:27 handleRedirect
_app.tsx:27 handleRedirect
auth.ts:35 [Tue, 25 Jan 2022 18:46:17 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:handleRedirectStart
auth.ts:35 [Tue, 25 Jan 2022 18:46:17 GMT] : @azure/msal-react@1.1.1 : Info - MsalProvider - msal:handleRedirectStart results in setting inProgress from handleRedirect to handleRedirect
auth.ts:35 [Tue, 25 Jan 2022 18:46:17 GMT] : [e36deb48-827d-4819-8e1d-6aecf639ec1f] : msal.js.browser@2.21.0 : Info - handleRedirectPromise did not detect a response hash as a result of a redirect. Cleaning temporary cache.
_app.tsx:27 handleRedirect
auth.ts:35 [Tue, 25 Jan 2022 18:46:17 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:handleRedirectEnd
auth.ts:35 [Tue, 25 Jan 2022 18:46:17 GMT] : @azure/msal-react@1.1.1 : Info - MsalProvider - no account changes
auth.ts:35 [Tue, 25 Jan 2022 18:46:17 GMT] : @azure/msal-react@1.1.1 : Info - MsalProvider - msal:handleRedirectEnd results in setting inProgress from handleRedirect to none
_app.tsx:27 none
auth.ts:35 [Tue, 25 Jan 2022 18:46:17 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:loginStart
auth.ts:35 [Tue, 25 Jan 2022 18:46:17 GMT] : @azure/msal-react@1.1.1 : Info - MsalProvider - msal:loginStart results in setting inProgress from none to login
_app.tsx:27 login
_app.tsx:27 login
auth.ts:35 [Tue, 25 Jan 2022 18:46:17 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:loginFailure
auth.ts:35 [Tue, 25 Jan 2022 18:46:17 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:handleRedirectEnd
Navigated to http://localhost:3000/
​ startup
​ [Tue, 25 Jan 2022 18:46:19 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:handleRedirectStart
​ [Tue, 25 Jan 2022 18:46:19 GMT] : @azure/msal-react@1.1.1 : Info - MsalProvider - msal:handleRedirectStart results in setting inProgress from startup to handleRedirect
2​ handleRedirect
Navigated to http://localhost:3000/submissions/new/2
_app.tsx:27 startup
auth.ts:35 [Tue, 25 Jan 2022 18:46:20 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:handleRedirectStart
auth.ts:35 [Tue, 25 Jan 2022 18:46:20 GMT] : @azure/msal-react@1.1.1 : Info - MsalProvider - msal:handleRedirectStart results in setting inProgress from startup to handleRedirect
_app.tsx:27 handleRedirect
auth.ts:35 [Tue, 25 Jan 2022 18:46:20 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:loginFailure
auth.ts:35 [Tue, 25 Jan 2022 18:46:20 GMT] : @azure/msal-react@1.1.1 : Info - MsalProvider - no account changes
auth.ts:35 [Tue, 25 Jan 2022 18:46:20 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:handleRedirectEnd
auth.ts:35 [Tue, 25 Jan 2022 18:46:20 GMT] : @azure/msal-react@1.1.1 : Info - MsalProvider - no account changes
auth.ts:35 [Tue, 25 Jan 2022 18:46:20 GMT] : @azure/msal-react@1.1.1 : Info - MsalProvider - msal:handleRedirectEnd results in setting inProgress from handleRedirect to none
_app.tsx:27 none
_app.js?ts=1643136379661:13672 Uncaught (in promise) BrowserAuthError: no_cached_authority_error: No cached authority found.
    at BrowserAuthError.AuthError [as constructor] (_app.js?ts=1643136379661:13672:24)
    at new BrowserAuthError (_app.js?ts=1643136379661:4235:28)
    at Function.push../node_modules/@azure/msal-browser/dist/error/BrowserAuthError.js.BrowserAuthError.createNoCachedAuthorityError (_app.js?ts=1643136379661:4404:16)
    at RedirectClient.<anonymous> (_app.js?ts=1643136379661:5651:108)
    at step (_app.js?ts=1643136379661:333:23)
    at Object.next (_app.js?ts=1643136379661:314:53)
    at _app.js?ts=1643136379661:307:71
    at new Promise (<anonymous>)
    at __awaiter (_app.js?ts=1643136379661:303:12)
    at RedirectClient.push../node_modules/@azure/msal-browser/dist/interaction_client/RedirectClient.js.RedirectClient.handleHash (_app.js?ts=1643136379661:5642:76)
    at RedirectClient.<anonymous> (_app.js?ts=1643136379661:5557:51)
    at step (_app.js?ts=1643136379661:333:23)
    at Object.next (_app.js?ts=1643136379661:314:53)
    at _app.js?ts=1643136379661:307:71
    at new Promise (<anonymous>)
    at __awaiter (_app.js?ts=1643136379661:303:12)
    at RedirectClient.push../node_modules/@azure/msal-browser/dist/interaction_client/RedirectClient.js.RedirectClient.handleRedirectPromise (_app.js?ts=1643136379661:5520:76)
    at PublicClientApplication.<anonymous> (_app.js?ts=1643136379661:496:51)
    at step (_app.js?ts=1643136379661:333:23)
    at Object.next (_app.js?ts=1643136379661:314:53)
    at _app.js?ts=1643136379661:307:71
    at new Promise (<anonymous>)
    at __awaiter (_app.js?ts=1643136379661:303:12)
    at PublicClientApplication.push../node_modules/@azure/msal-browser/dist/app/ClientApplication.js.ClientApplication.handleRedirectPromise (_app.js?ts=1643136379661:482:76)
    at _app.js?ts=1643136379661:17587:14
    at invokePassiveEffectCreate (main.js?ts=1643136379661:41259:20)
    at HTMLUnknownElement.callCallback (main.js?ts=1643136379661:21722:14)
    at Object.invokeGuardedCallbackDev (main.js?ts=1643136379661:21771:16)
    at invokeGuardedCallback (main.js?ts=1643136379661:21833:31)
    at flushPassiveEffectsImpl (main.js?ts=1643136379661:41346:9)
    at unstable_runWithPriority (main.js?ts=1643136379661:48292:12)
    at runWithPriority$1 (main.js?ts=1643136379661:29053:10)
    at flushPassiveEffects (main.js?ts=1643136379661:41219:14)
    at main.js?ts=1643136379661:41096:11
    at workLoop (main.js?ts=1643136379661:48241:34)
    at flushWork (main.js?ts=1643136379661:48214:14)
    at MessagePort.performWorkUntilDeadline (main.js?ts=1643136379661:47981:27)
AuthError @ _app.js?ts=1643136379661:13672
BrowserAuthError @ _app.js?ts=1643136379661:4235
push../node_modules/@azure/msal-browser/dist/error/BrowserAuthError.js.BrowserAuthError.createNoCachedAuthorityError @ _app.js?ts=1643136379661:4404
(anonymous) @ _app.js?ts=1643136379661:5651
step @ _app.js?ts=1643136379661:333
(anonymous) @ _app.js?ts=1643136379661:314
(anonymous) @ _app.js?ts=1643136379661:307
__awaiter @ _app.js?ts=1643136379661:303
push../node_modules/@azure/msal-browser/dist/interaction_client/RedirectClient.js.RedirectClient.handleHash @ _app.js?ts=1643136379661:5642
(anonymous) @ _app.js?ts=1643136379661:5557
step @ _app.js?ts=1643136379661:333
(anonymous) @ _app.js?ts=1643136379661:314
(anonymous) @ _app.js?ts=1643136379661:307
__awaiter @ _app.js?ts=1643136379661:303
push../node_modules/@azure/msal-browser/dist/interaction_client/RedirectClient.js.RedirectClient.handleRedirectPromise @ _app.js?ts=1643136379661:5520
(anonymous) @ _app.js?ts=1643136379661:496
step @ _app.js?ts=1643136379661:333
(anonymous) @ _app.js?ts=1643136379661:314
(anonymous) @ _app.js?ts=1643136379661:307
__awaiter @ _app.js?ts=1643136379661:303
push../node_modules/@azure/msal-browser/dist/app/ClientApplication.js.ClientApplication.handleRedirectPromise @ _app.js?ts=1643136379661:482
(anonymous) @ _app.js?ts=1643136379661:17587
invokePassiveEffectCreate @ main.js?ts=1643136379661:41259
callCallback @ main.js?ts=1643136379661:21722
invokeGuardedCallbackDev @ main.js?ts=1643136379661:21771
invokeGuardedCallback @ main.js?ts=1643136379661:21833
flushPassiveEffectsImpl @ main.js?ts=1643136379661:41346
unstable_runWithPriority @ main.js?ts=1643136379661:48292
runWithPriority$1 @ main.js?ts=1643136379661:29053
flushPassiveEffects @ main.js?ts=1643136379661:41219
(anonymous) @ main.js?ts=1643136379661:41096
workLoop @ main.js?ts=1643136379661:48241
flushWork @ main.js?ts=1643136379661:48214
performWorkUntilDeadline @ main.js?ts=1643136379661:47981
Promise.then (async)
(anonymous) @ _app.js?ts=1643136379661:33376
invokePassiveEffectCreate @ main.js?ts=1643136379661:41259
callCallback @ main.js?ts=1643136379661:21722
invokeGuardedCallbackDev @ main.js?ts=1643136379661:21771
invokeGuardedCallback @ main.js?ts=1643136379661:21833
flushPassiveEffectsImpl @ main.js?ts=1643136379661:41346
unstable_runWithPriority @ main.js?ts=1643136379661:48292
runWithPriority$1 @ main.js?ts=1643136379661:29053
flushPassiveEffects @ main.js?ts=1643136379661:41219
(anonymous) @ main.js?ts=1643136379661:41096
workLoop @ main.js?ts=1643136379661:48241
flushWork @ main.js?ts=1643136379661:48214
performWorkUntilDeadline @ main.js?ts=1643136379661:47981
Show 4 more frames
_app.tsx:27 none
auth.ts:35 [Tue, 25 Jan 2022 18:46:20 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:handleRedirectStart
auth.ts:35 [Tue, 25 Jan 2022 18:46:20 GMT] : @azure/msal-react@1.1.1 : Info - MsalProvider - msal:handleRedirectStart results in setting inProgress from none to handleRedirect
auth.ts:35 [Tue, 25 Jan 2022 18:46:20 GMT] : [2b03a397-9343-4296-9056-bb6f62994353] : msal.js.browser@2.21.0 : Info - handleRedirectPromise called but there is no interaction in progress, returning null.
2_app.tsx:27 handleRedirect
auth.ts:35 [Tue, 25 Jan 2022 18:46:20 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:handleRedirectEnd
auth.ts:35 [Tue, 25 Jan 2022 18:46:20 GMT] : @azure/msal-react@1.1.1 : Info - MsalProvider - no account changes
auth.ts:35 [Tue, 25 Jan 2022 18:46:20 GMT] : @azure/msal-react@1.1.1 : Info - MsalProvider - msal:handleRedirectEnd results in setting inProgress from handleRedirect to none
_app.tsx:27 none
auth.ts:35 [Tue, 25 Jan 2022 18:46:20 GMT] : @azure/msal-browser@2.21.0 : Info - Emitting event: msal:loginStart
auth.ts:35 [Tue, 25 Jan 2022 18:46:20 GMT] : @azure/msal-react@1.1.1 : Info - MsalProvider - msal:loginStart results in setting inProgress from none to login
_app.tsx:27 login
_app.tsx:27 login
Navigated to http://localhost:3000/

### MSAL Configuration

```javascript
import {
  AZURE_B2C_CLIENT_ID,
  AZURE_B2C_POLICY,
  AZURE_B2C_REDIRECT_URI,
  AZURE_B2C_TENANT,
} from '.';

const b2cPolicies = {
  names: {
    signIn: AZURE_B2C_POLICY,
  },
  authorities: {
    signIn: {
      authority: `https://${AZURE_B2C_TENANT}.b2clogin.com/${AZURE_B2C_TENANT}.onmicrosoft.com/${AZURE_B2C_POLICY}`,
    },
  },
  authorityDomain: `${AZURE_B2C_TENANT}.b2clogin.com`,
};

export const loginRequest = {
  scopes: ['profile', 'email', 'offline_access', 'openid', AZURE_B2C_CLIENT_ID],
};

export const msalConfig = {
  auth: {
    clientId: AZURE_B2C_CLIENT_ID,
    authority: b2cPolicies.authorities.signIn.authority,
    knownAuthorities: [b2cPolicies.authorityDomain],
    redirectUri: AZURE_B2C_REDIRECT_URI,
  },
  cache: {
    cacheLocation: 'sessionStorage',
    storeAuthStateInCookie: false,
  },
};
```

### Relevant Code Snippets

```javascript
![image](https://user-images.githubusercontent.com/44274213/151039678-054380bb-7b8f-4bfb-baba-3a4648a2d47e.png)

![image](https://user-images.githubusercontent.com/44274213/151039744-51ffb211-d8b5-4852-bfa7-6b20980dfbd2.png)
```

### Reproduction Steps

1. Setup MSAL lib.
2. Create Dynamic Route Page
3. Try to start a new session directly in the previous created page.

### Expected Behavior

1. Should redirect to microsoft login screen and ask for user credentials.
2. Afer user's input, should redirect to registered Redirect URI.
3. After session is created and user is authenticates, should redirect back to dynamic page.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer

### Source

Internal (Microsoft)

**Comment by jasonnutter** [comment]
@danielweil Are you able to reproduce this with our [Next.js sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/nextjs-sample)?

**Comment by danielweil** [comment]
Hello @jasonnutter, 

I just tried out, and it did work with the sample. I tried copying the Navigation Client to my application, and now it works fine!.
Thank you for the support.
