### ISSUE TITLE
MSAL Angular w/ B2C SPA client code flow w/ pkce

### ISSUE THREAD

**Issue by johnyoungnvs** [AzureAD/microsoft-authentication-library-for-js#4452]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.21.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.1.0

### Description

When the refresh token expires, with an angular spa configured for code flow pkce w/ b2c, the application goes into an infinite loop and becomes unresponsive after 24 hours when the refresh token expires

### Error Message

Got 1000's and 1000's of these logs in console, to the point that the browser becomes unusable

Error: Uncaught (in promise): BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.  For more visit: aka.ms/msaljs/browser-errors.
t@https://www.example.org/main.bbbbe4bab3b701f34f01.js:1:3869928
t@https://www.example.org/main.bbbbe4bab3b701f34f01.js:1:3887338
@https://www.example.org/main.bbbbe4bab3b701f34f01.js:1:3889032
@https://www.example.org/main.bbbbe4bab3b701f34f01.js:1:8135249
@https://www.example.org/main.bbbbe4bab3b701f34f01.js:1:8152234
@https://www.example.org/main.bbbbe4bab3b701f34f01.js:1:3869378
@https://www.example.org/main.bbbbe4bab3b701f34f01.js:1:3868420
A@https://www.example.org/polyfills.1652abd69e0565092c78.js:1:104040
CC@https://www.example.org/main.bbbbe4bab3b701f34f01.js:1:3868179
@https://www.example.org/main.bbbbe4bab3b701f34f01.js:1:8175348
@https://www.example.org/main.bbbbe4bab3b701f34f01.js:1:3869378
@https://www.example.org/main.bbbbe4bab3b701f34f01.js:1:3868420
A@https://www.example.org/polyfills.1652abd69e0565092c78.js:1:104040
CC@https://www.example.org/main.bbbbe4bab3b701f34f01.js:1:3868179
acquireTokenRedirect@https://www.example.org/main.bbbbe4bab3b701f34f01.js:1:3971415
acquireTokenInteractively@https://www.example.org/main.bbbbe4bab3b701f34f01.js:1:3979547
error@https://www.example.org/main.bbbbe4bab3b701f34f01.js:1:3899629
onInvoke@https://www.example.org/main.bbbbe4bab3b701f34f01.js:1:3568317
run@https://www.example.org/polyfills.1652abd69e0565092c78.js:1:92043
@https://www.example.org/polyfills.1652abd69e0565092c78.js:1:102978
onInvokeTask@https://www.example.org/main.bbbbe4bab3b701f34f01.js:1:3568210
runTask@https://www.example.org/polyfills.1652abd69e0565092c78.js:1:92662
v@https://www.example.org/polyfills.1652abd69e0565092c78.js:1:99244
promiseReactionJob@[native code]
	ua (main.bbbbe4bab3b701f34f01.js:1:3491864)
	handleError (main.bbbbe4bab3b701f34f01.js:1:3492035)
	next (main.bbbbe4bab3b701f34f01.js:1:3574419)
	(anonymous function) (main.bbbbe4bab3b701f34f01.js:1:3558595)
	__tryOrUnsub (main.bbbbe4bab3b701f34f01.js:1:3454720)
	next (main.bbbbe4bab3b701f34f01.js:1:3453973)
	_next (main.bbbbe4bab3b701f34f01.js:1:3453160)
	next (main.bbbbe4bab3b701f34f01.js:1:3452935)
	next (main.bbbbe4bab3b701f34f01.js:1:3457595)
	emit (main.bbbbe4bab3b701f34f01.js:1:3558466)
	run (polyfills.1652abd69e0565092c78.js:1:92044)
	onHandleError (main.bbbbe4bab3b701f34f01.js:1:3568589)
	runGuarded (polyfills.1652abd69e0565092c78.js:1:92224)
	(anonymous function) (polyfills.1652abd69e0565092c78.js:1:100874)
	v (polyfills.1652abd69e0565092c78.js:1:99312)
	promiseReactionJob

### Msal Logs

Error: Uncaught (in promise): BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.  For more visit: aka.ms/msaljs/browser-errors.
t@https://www.example.org/main.bbbbe4bab3b701f34f01.js:1:3869928
t@https://www.example.org/main.bbbbe4bab3b701f34f01.js:1:3887338
@https://www.example.org/main.bbbbe4bab3b701f34f01.js:1:3889032
@https://www.example.org/main.bbbbe4bab3b701f34f01.js:1:8135249
@https://www.example.org/main.bbbbe4bab3b701f34f01.js:1:8152234
@https://www.example.org/main.bbbbe4bab3b701f34f01.js:1:3869378
@https://www.example.org/main.bbbbe4bab3b701f34f01.js:1:3868420
A@https://www.example.org/polyfills.1652abd69e0565092c78.js:1:104040
CC@https://www.example.org/main.bbbbe4bab3b701f34f01.js:1:3868179
@https://www.example.org/main.bbbbe4bab3b701f34f01.js:1:8175348
@https://www.example.org/main.bbbbe4bab3b701f34f01.js:1:3869378
@https://www.example.org/main.bbbbe4bab3b701f34f01.js:1:3868420
A@https://www.example.org/polyfills.1652abd69e0565092c78.js:1:104040
CC@https://www.example.org/main.bbbbe4bab3b701f34f01.js:1:3868179
acquireTokenRedirect@https://www.example.org/main.bbbbe4bab3b701f34f01.js:1:3971415
acquireTokenInteractively@https://www.example.org/main.bbbbe4bab3b701f34f01.js:1:3979547
error@https://www.example.org/main.bbbbe4bab3b701f34f01.js:1:3899629
onInvoke@https://www.example.org/main.bbbbe4bab3b701f34f01.js:1:3568317
run@https://www.example.org/polyfills.1652abd69e0565092c78.js:1:92043
@https://www.example.org/polyfills.1652abd69e0565092c78.js:1:102978
onInvokeTask@https://www.example.org/main.bbbbe4bab3b701f34f01.js:1:3568210
runTask@https://www.example.org/polyfills.1652abd69e0565092c78.js:1:92662
v@https://www.example.org/polyfills.1652abd69e0565092c78.js:1:99244
promiseReactionJob@[native code]
	ua (main.bbbbe4bab3b701f34f01.js:1:3491864)
	handleError (main.bbbbe4bab3b701f34f01.js:1:3492035)
	next (main.bbbbe4bab3b701f34f01.js:1:3574419)
	(anonymous function) (main.bbbbe4bab3b701f34f01.js:1:3558595)
	__tryOrUnsub (main.bbbbe4bab3b701f34f01.js:1:3454720)
	next (main.bbbbe4bab3b701f34f01.js:1:3453973)
	_next (main.bbbbe4bab3b701f34f01.js:1:3453160)
	next (main.bbbbe4bab3b701f34f01.js:1:3452935)
	next (main.bbbbe4bab3b701f34f01.js:1:3457595)
	emit (main.bbbbe4bab3b701f34f01.js:1:3558466)
	run (polyfills.1652abd69e0565092c78.js:1:92044)
	onHandleError (main.bbbbe4bab3b701f34f01.js:1:3568589)
	runGuarded (polyfills.1652abd69e0565092c78.js:1:92224)
	(anonymous function) (polyfills.1652abd69e0565092c78.js:1:100874)
	v (polyfills.1652abd69e0565092c78.js:1:99312)
	promiseReactionJob

### MSAL Configuration

```javascript
{
      auth: {
        clientId: this.config.b2cConfiguration.b2cPolicies.clientId,
        authority:
          this.config.b2cConfiguration.b2cPolicies.authorities.signUpSignIn
            .authority,
        redirectUri: this.config.b2cConfiguration.b2cPolicies.redirectUri,
        postLogoutRedirectUri:
          this.config.b2cConfiguration.b2cPolicies.postLogoutRedirectUri,
        knownAuthorities: [
          this.config.b2cConfiguration.b2cPolicies.authorityDomain,
        ],
      },
      cache: {
        cacheLocation: BrowserCacheLocation.LocalStorage,
        storeAuthStateInCookie: this.isIE, // set to true for IE 11
      },
    }
```

### Relevant Code Snippets

```javascript
N/A, normal use of MSAL
```

### Reproduction Steps

1. Log into angular application
2. Leave on for 24 hours (allowing silent refresh to occur).
3. After 24 hours when the refresh token expires, B2C will throw a 400 error and MSAL goes into an infinite loop with the following error in the logs (after 15 minutes, I literally got 1000's of pages of the same error in console)

### Expected Behavior

After refresh token expires, it should redirect to B2C, get a fresh set of token/refresh token and start the cycle new

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Safari

### Source

External (Customer)

**Comment by ChrisMeeusen** [comment]
I'm getting this same behavoir on the initial bootstrapping and authenication in the app.  If i refresh the page after a token is cached and stored in session storage my app loads and runs fine.  I'm wondering if this is a race condition between getting a token and storing it in cache vs the interceptors trying to retreive the token from cache and send them in the request.

**Comment by jasonnutter** [comment]
> I'm wondering if this is a race condition between getting a token and storing it in cache vs the interceptors trying to retreive the token from cache and send them in the request.

Yes, this is a potential cause. Applications using the interceptor should wait until MSAL indicates that interaction (such as a previous redirect) [is no longer in progress](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-angular-v2-samples/angular12-sample-app/src/app/app.component.ts#L41-L49) before invoking an http request that would trigger the interceptor.

**Comment by johnyoungnvs** [comment]
Thanks guys for the feedback, we aren't making any calls, but have narrowed down the issue

It seems when silent refresh fails, it keeps trying and trying again, perhaps we need to add a circuit breaker if something goes wrong with silent refresh?

We found these two errors in console:

1. [Error] Refused to display 'https://www.example.com/#state=SAMPLE' in a frame because it set 'X-Frame-Options' to 'Deny'.

--> We fixed this by removing the X-Frame-Options header

2. [Error] Fetch API cannot load https://login.example.com/bsfmcaiamprod.onmicrosoft.com/b2c_1a_signuporsignin/v2.0/.well-known/openid-configuration due to access control checks.

--> We are still trying to figure out why it's throwing this error.  We can open another tab and the issue goes away, or do a fresh login and no issues getting access to the discovery endpoint.  However the original tab that has the expired refresh token gets this error and also throws the system into an infinite loop scenario

Is anyone aware of the second error?

Thanks!

**Comment by jasonnutter** [comment]
@johnyoungnvs Can you please provide verbose logs from MSAL? It looks like you are providing your B2C authority domain in the `knownAuthorities` array, which I believe should mitigate the need for the http call to the `openid-configuration` endpoint.

**Comment by johnyoungnvs** [comment]
Sorry for the delay, got some time from dev team to enable it and pull out the details

Please see below, i've tokenized the website and tenant name, if you need, I can send privately, no front door on this one, straight connection to b2c, i highlighted the first error of access control error from b2c

[MSAL Verbose.docx](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/8118773/MSAL.Verbose.docx)

**Comment by vtrusevich-incomm** [comment]
Are there any updates on the issue?

**Comment by johnyoungnvs** [comment]
No updates yet, still getting an infinite loop when msal tries to do refresh token cycle w/ b2c

we're adding some logic to clear the local/session storage after 12 hours so we don't hit the 24 hour refresh token expiry time now to avoid the issue from happening, but it is just a bandaid fix so users aren't stuck

we think the problem starts from this

https://{{B2C_TENANT}}.b2clogin.com/{{B2C_TENANT}}.onmicrosoft.com/b2c_1a_signuporsignin/v2.0/.well-known/openid-configuration due to access control checks.

we tried this on both a setup with frontdoor and without front door, and it gives the same issue, cause after this, it goes into its infinite loop

**Comment by tnorling** [comment]
@johnyoungnvs Your redirect loop is happening because you have a race condition between the interceptor and MSAL processing the response from the previous redirect. Did you try the suggestion posted by Jason above?

> Yes, this is a potential cause. Applications using the interceptor should wait until MSAL indicates that interaction (such as a previous redirect) [is no longer in progress](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-angular-v2-samples/angular12-sample-app/src/app/app.component.ts#L41-L49) before invoking an http request that would trigger the interceptor.
