### ISSUE TITLE
Use redirect to login but can't get token

### ISSUE THREAD

**Issue by zhshqzyc** [AzureAD/microsoft-authentication-library-for-js#4454]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0

### Description

The message is **handleredirectpromise called but there is no interaction in progress returning null**

In azure, I have set redirect url as http://localhost
In my angular 11 application I want to silently login in my home page. So in my home page. I have
```javascript
msalInstance
            .handleRedirectPromise()
            .then((tokenResponse: Msal.AuthenticationResult) => {
                let accountObj = null;
                if (tokenResponse !== null) {
                    accountObj = tokenResponse.account;
                    const id_token = tokenResponse.idToken;
                    const access_token = tokenResponse.accessToken;
                    console.log('id_token', id_token);
                    console.log('access_token', access_token);
                }
            })
            .catch(error => {
                  console.error(error);
            });

    msalInstance.loginRedirect(this.loginRequest)
```
But the response returns null so I can't get the token

Also please see my routing module
```js
const routes: Routes = {
    {path: '', component: HomeComponent},
    {path: 'app/home', component: HomeComponent},
    ****
} 
```

### MSAL Configuration

```javascript
export function MSALInstanceFactory(): IPublicClientApplication {
  return new PublicClientApplication({
    auth: {
          clientId: 'blah-blah-blah-8u1a-fd58772cb82e',
          authority: 'https://login.microsoftonline.com/blah-blah-blah-blah/', 
          redirectUri: window.location.origin
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE, // set to true for IE 11. Remove this line to use Angular Universal
    },
    system: {
      allowRedirectInIframe: true,
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Info,
        piiLoggingEnabled: false
      }
    }
  });
}

export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
  const protectedResourceMap = new Map<string, Array<string>>();
  protectedResourceMap.set('https://graph.microsoft-ppe.com/v1.0/me', ['user.read']);

  return {
    interactionType: InteractionType.Redirect,
    protectedResourceMap
  };
}

export function MSALGuardConfigFactory(): MsalGuardConfiguration {
  return { 
    interactionType: InteractionType.Redirect,
    authRequest: {
      scopes: ['user.read']
    }
  };
```

### Relevant Code Snippets

```javascript
@NgModule({
  declarations: [
    AppComponent,
    HomeComponent,
    ProfileComponent,
    DetailComponent,
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    AppRoutingModule,
    MatButtonModule,
    MatToolbarModule,
    MatListModule,
    MatMenuModule,
    HttpClientModule,
    MsalModule
  ],
  providers: [
    {
      provide: HTTP_INTERCEPTORS,
      useClass: MsalInterceptor,
      multi: true
    },
    {
      provide: MSAL_INSTANCE,
      useFactory: MSALInstanceFactory
    },
    {
      provide: MSAL_GUARD_CONFIG,
      useFactory: MSALGuardConfigFactory
    },
    {
      provide: MSAL_INTERCEPTOR_CONFIG,
      useFactory: MSALInterceptorConfigFactory
    },
    MsalService,
    MsalGuard,
    MsalBroadcastService
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@zhshqzyc To be clear, `handleRedirectPromise` processes a redirect interactive login, but does not perform silent authentication itself. If `handleRedirectPromise` returns `null`, that means the page was loaded normally (i.e. not a result of coming back from an AAD redirect), in which case your app can gets tokens via `acquireTokenSilent` (which is invoked automatically in the interceptor).

**Comment by zhshqzyc** [comment]
The difficult thing is that I want to get the tokens in advance(at the very beginning). I have a power bi module embed in angular. So I want to get roles from the tokens but it doesn't call the interceptor at all as no http request. I just want to open PowerBi report.

I tried to copy and paste the code from interceptor but it is not working. It needs account parameter. Any idea or sample code?

**Comment by jasonnutter** [comment]
@zhshqzyc To set an account for `acquireTokenSilent`, you can use the [account APIs](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/accounts.md) to find the account to use for the request:

```typescript
ngOnInit(): void {
    this.msalBroadcastService.inProgress$
      .pipe(
        filter((status: InteractionStatus) => status === InteractionStatus.None),
        takeUntil(this._destroying$)
      )
      .subscribe(() => {
        this.setLoginDisplay();
        this.checkAndSetActiveAccount();

       if (this.authService.instance.getAllAccounts().length > 0) {
          const { accessToken } = this.authService.instance.acquireTokenSilent({ 
              scopes: [ "your-scopes" ],
              account: this.authService.instance.getAllAccounts()[0]
         })
      }
   })
}
```

**Comment by zhshqzyc** [comment]
Please see my ode:
```
ngOnInit(): void {
     this.msalService.instance.handleRedirectPromise().then(
        res => {
          if(res) {
              // get token code, ignore here as it never reaches here
          } else {
                this.msalBroadcastService.inProgress$
      .pipe(
        filter((status: InteractionStatus) => status === InteractionStatus.None),
        takeUntil(this._destroying$)
      )
      .subscribe(() => {
        this.setLoginDisplay();
        this.checkAndSetActiveAccount();

       if (this.authService.instance.getAllAccounts().length > 0) {
          const { accessToken } = this.authService.instance.acquireTokenSilent({ 
              scopes: [ "your-scopes" ],
              account: this.authService.instance.getAllAccounts()[0]
         })
      }
   })
         }
       }
   );
}

```
However in the method `checkAndSetActiveAccount()`, the `activeAccount` is still null. What is wrong?

**Comment by jasonnutter** [comment]
@zhshqzyc That means that there is no cached active account, so you'll need to set one using `setActiveAccount`.

**Comment by zhshqzyc** [comment]
I guess that I found the solution at https://stackoverflow.com/questions/63347299/unable-to-acquire-token-silently-or-via-redirect-using-msal-browser
init = async () => {

    try {
      let tokenResponse = await this.app.handleRedirectPromise();

      let accountObj;
      if (tokenResponse) {
        accountObj = tokenResponse.account;
      } else {
        accountObj = this.app.getAllAccounts()[0];
      }

      if (accountObj && tokenResponse) {
        console.log("[AuthService.init] Got valid accountObj and tokenResponse")
      } else if (accountObj) {
        console.log("[AuthService.init] User has logged in, but no tokens.");
        try {
          tokenResponse = await this.app.acquireTokenSilent({
            account: this.app.getAllAccounts()[0],
            scopes: ["user.read"]
          })
        } catch(err) {
          await this.app.acquireTokenRedirect({scopes: ["user.read"]});
        }
      } else {
        console.log("[AuthService.init] No accountObject or tokenResponse present. User must now login.");
        await this.app.loginRedirect({scopes: ["user.read"]})
      }
    } catch (error) {
      console.error("[AuthService.init] Failed to handleRedirectPromise()", error)
    }

  }`
  
  I am ready for close the issue but I have one more question. I have the scope `authRequest: {
      scopes: ['user.read']
    }
    But why in the msal interceptor, I found ` const scopes = this.getscopeforendpoint(req.url, req.method) returned null. It should return  ['user.read']?

**Comment by jasonnutter** [comment]
> I am ready for close the issue but I have one more question. I have the scope authRequest: { scopes: ['user.read'] } But why in the msal interceptor, I found const scopes = this.getscopeforendpoint(req.url, req.method) returned null. It should return ['user.read']?

Make sure that the URL your application is calling is configured in the MSAL Interceptor configuration correctly:

```typescript
export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
  const protectedResourceMap = new Map<string, Array<string>>();
  protectedResourceMap.set('https://graph.microsoft-ppe.com/v1.0/me', ['user.read']);

  return {
    interactionType: InteractionType.Redirect,
    protectedResourceMap
  };
}
```

Double check your settings (e.g. the above example is for `graph.microsoft-ppe.com`, as opposed to `graph.microsoft.com`).

**Comment by zhshqzyc** [comment]
I am pretty that I use the same setting with yours. But it is null, I have to manually set the scopes in api-interceptor.service.ts. However it does not affect the result.

I can get all information such as account, token even I set `scopes = []` or` scopes = ['user.read']` or `scopes = ['xxxxxx']`

**Comment by zhshqzyc** [comment]
More findings:
In the method `matchResourcesEndpoints`, I got `absoluteResources` and `relativeResources` empty.  It happens here:
`StringUtils.matchPattern(normalizedKey, endpoint)`. It seems not matched. The normalizedKey is `https://graph.microsoft-ppe.com/v1.0/me` but the endpoint is `https://dev.my-company.com/api/team`. So in the method `getScopesForEndpoint` it always returns null.

**Comment by ghost** [comment]
This issue requires attention from the MSAL.js team and has not seen activity in **5 days**. @jasonnutter please follow up.

**Comment by jasonnutter** [comment]
@zhshqzyc This means you need to add an entry to the `protectedResourceMap` for your API. For example:

```typescript
protectedResourceMap.set('https://dev.my-company.com/api/team', ['custom-scope-for-your-api']);

```

**Comment by zhshqzyc** [comment]
I guess that the definition of scope should exclude from graph `protectedResourceMap.set('https://graph.microsoft-ppe.com/v1.0/me', ['user.read']);`. It is user self defined scope. The term is really confused. That's all.
