### ISSUE TITLE
@azure/msal-angular  the token can't get key vault's secretes/keys/certificates

### ISSUE THREAD

**Issue by baoj-dfo** [AzureAD/microsoft-authentication-library-for-js#4455]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.21.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.21.0

### Description

I was told from Microsoft support "To authenticate on the key vault you will have to use the Azure Identity package and any class within it as per your requirement If you do not wish to use a client secret in your code in that case you may use the defaultazurecredentials() or Interactivebrowsercredentials() class to authenticate"

so this is a missing piece from MSAL library, which can't http get key vault's secretes/keys/certificates with api 
GET {vaultBaseUrl}/secrets?api-version=7.2
GET {vaultBaseUrl}/keys?api-version=7.2
GET {vaultBaseUrl}/certificates?api-version=7.2
https://docs.microsoft.com/en-us/rest/api/keyvault/keys/get-keys/get-keys
https://docs.microsoft.com/en-us/rest/api/keyvault/secrets/get-secrets/get-secrets
https://docs.microsoft.com/en-us/rest/api/keyvault/certificates/get-certificates/get-certificates

according to https://docs.microsoft.com/en-us/javascript/api/overview/azure/identity-readme?view=azure-node-latest
"Most of the credential types offered by @azure/identity use the Microsoft Authentication Library for JavaScript (MSAL.js). "
It seems the above keyvault scenario can't rely on MSAL library to get correct token.

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@baoj-dfo While MSAL.js can get access tokens for the `https://vault.azure.net/user_impersonation` scope (which is needed to access Key Vault), the Key Vault API itself does not support cross-origin requests from the browser. Please see [this sample](https://github.com/Azure/azure-sdk-for-js/tree/main/samples/cors/ts) for how to build a middle-tier which can be used to proxy requests to Key Vault from the browser.

**Comment by byunru** [comment]
@jasonnutter  thanks for pointing out the APIM way, it is quite a lots of extra works :( , wish the Key Vault API can support cross-origin requests from the browser, at least provide API (cors) getting a list of name of secrets/keys/certificates shouldn't have security concern.

**Comment by jasonnutter** [comment]
If you'd like to let the KeyVault know about this request, I would recommend commenting here: https://feedback.azure.com/d365community/idea/89085b38-f624-ec11-b6e6-000d3a4f0da0

Closing.
