### ISSUE TITLE
useMsal sample code doesn't appear correct - might need to use a state variable for the token

### ISSUE THREAD

**Issue by mcqueene** [AzureAD/microsoft-authentication-library-for-js#4461]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL React (@azure/msal-react)

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/hooks.md#usemsal-hook

### Description

I'm not sure the sample for the useMsal hook is correct. It seems to suggest that you can check for a value in the variable `accessToken` but that is returned from the hook (which I'm not sure is correct) and I think the token is acquired asynchronously by `acquireTokenSilent`. So the code sample given where it attempts to see if `accessToken` is null or has a value, will always end up with null. I've tried to find a way to make this sample work but I can't figure it out (so maybe it's me). I think what might work is instead of the `useEffect` trying to return a value for the token, it should set a state variable. So if `accessToken` were a state variable I think it would work.

**Comment by tnorling** [comment]
@mcqueene Thanks for raising this. You are indeed correct, I'll make sure this doc gets updated. If you still need help please take a look at our [react samples](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples) which all demonstrate acquiring a token and calling the Graph API.
