### ISSUE TITLE
owserAuthError: block_nested_popups: Request was blocked inside a popup because MSAL detected it was running in a popup.

### ISSUE THREAD

**Issue by ankit-bagaria-kr** [AzureAD/microsoft-authentication-library-for-js#4462]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.21.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

0.0

### Description

**I am authenticating using msal library, using PublicClientApplication**

> const myMsal = new PublicClientApplication(config);
> const loginResponse = await myMsal.loginPopup(loginRequest)
        
It is authenticating correctly, I am getting token correctly. But in msal login popup, I get an error alert.

### Error Message

BowserAuthError: block_nested_popups: Request was blocked inside a popup because MSAL detected it was running in a popup.

### MSAL Configuration

```javascript
const config = {
     auth: {
         clientId: 'bab9fad8-5de6-4076-9d59-4e6c0e88c00c',
         authority:
           'https://login.microsoftonline.com/8331e14a-9134-4288-bf5a-5e2c8412f074',
         redirectUri: `http://localhost:3000/oauth2/token`
       },
       cache: {
         cacheLocation: 'localStorage', // This configures where your cache will be stored
         storeAuthStateInCookie: true, // Set this to "true" if you are having issues on IE11 or Edge
       }
 }
 
> const loginRequest = {
>   scopes: ['openid'],
> }
```

### Relevant Code Snippets

```javascript
const myMsal = new PublicClientApplication(config);
const loginResponse = await myMsal.loginPopup(loginRequest)
```

### Reproduction Steps

Download msal Library
and try running the authentication mechanism using the above code snippets and configuration

### Expected Behavior

it should login without giving any error alert

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by ankit-bagaria-kr** [comment]
<img width="592" alt="Screenshot 2022-01-31 at 1 14 06 PM" src="https://user-images.githubusercontent.com/94103442/151758601-5c92b5d7-ed3a-47ec-8bcb-45210fbcd09c.png">


Screenshot of the error

**Comment by jasonnutter** [comment]
@ankit-bagaria-kr This is likely happening because the page your app is using for the redirect uri (`localhost:3000/oauth2/token`) has code that is checking for the user's authentication state and invoking a popup method while MSAL is trying to process the initial popup operation. To mitigate this, make sure this code does not run while this page is in a popup.
