### ISSUE TITLE
Getting Token issued by V1 instead of V2

### ISSUE THREAD

**Issue by ihrigb** [AzureAD/microsoft-authentication-library-for-js#4463]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.21.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.2.0

### Description

When using MSAL to get a token, I receive a token with the V1 issue claim (sts.***). My backend service expects V2 issue though and reports this as unknown issuer and therefore answers with 401.
Any way I can influence this to make it work?

### MSAL Configuration

```javascript
{
    auth: {
        clientId: '6b45900f-fee7-41c4-851e-00785a2c8b32',
        authority: 'https://login.microsoftonline.com/0b8f51e5-134a-4768-b108-caa12f30ffc1/'
    }
}
```

### Relevant Code Snippets

```javascript
var expiry = localStorage.getItem(auth_access_token_expiry_name);
        if (expiry && expiry > new Date()) {
            // we have a valid token
            console.log("Valid token.");
            return Promise.resolve();
        }

        console.log("No token in storage");

        // check if it is a callback
        const location = window.location.href;
        console.log("Location", location);
        const url = new URL(location);
        const hash = url.hash;
        if (hash && hash.startsWith("#/code=")) {
            console.log("Got #/code hash.");
            const test = await msalInstance.handleRedirectPromise(hash);
            console.log("HIER", test);
        }

        // check if we have accounts
        const accounts = msalInstance.getAllAccounts();
        if (!accounts || accounts.length === 0) {
            // no logged in accounts
            return Promise.reject();
        }
```

### Reproduction Steps

See code above.

### Expected Behavior

Token with V2 issuer.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@ihrigb 

> There are two versions of access tokens available in the Microsoft identity platform: v1.0 and v2.0. These versions govern what claims are in the token, ensuring that a web API can control what their tokens look like. Web APIs have one of these selected as a default during registration - v1.0 for Azure AD-only apps, and v2.0 for apps that support consumer accounts. This is controllable by applications using the `accessTokenAcceptedVersion` setting in the [app manifest](https://docs.microsoft.com/azure/active-directory/develop/reference-app-manifest#manifest-reference), where null and 1 result in v1.0 tokens, and 2 results in v2.0 tokens.

https://docs.microsoft.com/azure/active-directory/develop/access-tokens#v10-and-v20

**Comment by ihrigb** [comment]
@jasonnutter, thanks for the response! I already read about `accessTokenAcceptedVersion` in the manifest and did set it to 2. Nothing changed and I still get a v1 Token (issuer is sts.windows.net/***).

**Comment by jasonnutter** [comment]
@ihrigb What is the audience (`aud` claim) of this token in question?

**Comment by ihrigb** [comment]
@jasonnutter aud is `00000003-0000-0000-c000-000000000000`

**Comment by jasonnutter** [comment]
@ihrigb That means the token is for the Microsoft Graph, not your API. To get a token for your API, invoke `acquireTokenSilent` and only pass the scopes for your API.

**Comment by ihrigb** [comment]
@jasonnutter Ok, I did this. When I do so, I get `The user or administrator has not consented to use the application with ID '6b45900f-fee7-41c4-851e-00785a2c8b32' named 'Alarmmanager'.` Although I granted tenant wide admin consent.

**Comment by jasonnutter** [comment]
@ihrigb Is this scope an application scope, or a delegated scope?

**Comment by ihrigb** [comment]
@jasonnutter as they are defined under "App-Roles" they should be application scope, right?

**Comment by jasonnutter** [comment]
@ihrigb MSAL.js is only able to acquire tokens for delegated scopes, and cannot get tokens for application scopes. Are you able to change this scope to a delegated scope?

More information: https://docs.microsoft.com/azure/active-directory/develop/v2-permissions-and-consent#permission-types

**Comment by ihrigb** [comment]
@jasonnutter Not sure, if I understand, how to setup the whole thing. I have a small API (resource server) that provides some functionality via REST. That service will for now be exclusively used by a UI which is provided within another runtime. API requests are proxied through the UI service to get around CORS problems.
Do I need to seperate App Registrations for them? For now, I thought I could get along with a single one.

**Comment by jasonnutter** [comment]
@ihrigb It is up to you if you want them to be separate registrations, but the scope itself should be registered under "Expose an API" for the app registration for the resource.

**Comment by Yasveer** [comment]
Hello Developers. I am searching for solutions to authenticate with Microsoft Graph and get all my emails in Eclipse IDE. I have used the authentication method of  'Client Credentials Provider'. I am having issues with the SCOPES that need to be defined. Thanks in advance. Please find the error and my code below:

package JAVA_MicrosoftGraphAPI;

import java.net.URL;
import java.util.Arrays;
import java.util.List;
import com.azure.identity.ClientSecretCredential;
import com.azure.identity.ClientSecretCredentialBuilder;
import com.microsoft.graph.authentication.TokenCredentialAuthProvider;
import com.microsoft.graph.logger.DefaultLogger;
import com.microsoft.graph.logger.LoggerLevel;
import com.microsoft.graph.models.User;
import com.microsoft.graph.requests.GraphServiceClient;
import okhttp3.Request;

public class YT_Video{

	//Replace CLIENT_ID with your own client id from an app that is configured according to the requirements below
	//for requirements visit: https://github.com/Azure/azure-sdk-for-java/wiki/Set-up-Your-Environment-for-Authentication#enable-applications-for-device-code-flow
	private final static String CLIENT_ID = "61a75ccc-70f2-48f8-b0ff-2e8fa0f968c0";
	private final static String TENANT_ID = "48942891-ee19-4912-ba1d-136b4b0d5697";
	private final static String SECRET_ID = "49931b6f-302d-4c35-bcee-29a1d1e2e853";

	//Set the scopes for your ms-graph request
	private final static List<String> SCOPES = Arrays.asList("User.Read", "Mail.Read", "openid", "offline_access", "profile");

	public static void main(String[] args) throws Exception {
		// Create the auth provider.		
		final ClientSecretCredential clientSecretCredential = new ClientSecretCredentialBuilder()
		        .clientId(CLIENT_ID)
		        .clientSecret(SECRET_ID)
				.tenantId(TENANT_ID)
				.build();
		
		
		
		final TokenCredentialAuthProvider tokenCredAuthProvider = new TokenCredentialAuthProvider(SCOPES, clientSecretCredential);
		System.out.println("First Step Reached. ");


		// Create default logger to only log errors
		DefaultLogger logger = new DefaultLogger();
		logger.setLoggingLevel(LoggerLevel.ERROR);


		// Build a Graph client
		GraphServiceClient<Request> graphClient = GraphServiceClient.builder()
				.authenticationProvider(tokenCredAuthProvider)
				.logger(logger)
				.buildClient();
		System.out.println("Second Step Reached. ");

		// Redirecting to web browser and signing in for authentication and connection.
		URL myUrl = new URL("https://graph.microsoft.com/v1.0/me/");
		final String accessToken = tokenCredAuthProvider.getAuthorizationTokenAsync(myUrl).get();
		System.out.println("Access token --> " + accessToken);

		// Just another optional step to get name of signed-in user.
		final User me = ((GraphServiceClient<Request>) graphClient).me().buildRequest().get();
		System.out.println("Hello " + me.displayName +  "( Synced !)");
		System.out.println("Hello " + me.mail +  "( Mail !)");
		System.out.println("Got " + me.messages.getCount() + " messages !");

	}

}

at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at JAVA_MicrosoftGraphAPI.YT_Video.main(YT_Video.java:67)
Caused by: com.microsoft.aad.msal4j.MsalServiceException: AADSTS1002012: The provided value for scope User.Read openid profile offline_access Mail.Read is not valid. Client credential flows must have a scope value with /.default suffixed to the resource identifier (application ID URI).

**Comment by samuel-sujith** [comment]
@ihrigb were you able to get around this. I am getting the exact thing. I set the tokentype to v2, added User.Read scope but still get v1 token instead of v2

**Comment by iremnuy** [comment]
I  am also still getting v1 tokens from msal even if i set the related parameter to 2 in manifest file, i get issuer is invalid error
