### ISSUE TITLE
Any hope for Electron?

### ISSUE THREAD

**Issue by jbpoulsen** [AzureAD/microsoft-authentication-library-for-js#447]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Current behavior

Calling the sample code from [https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/README.md](url) to display a simple login-dialog just displays a blank page (called _blank) in Electron. 
I have noticed another issue asking the same question, but the response seemed incomplete.

Are there other recommended ways to authenticate both personal and work accounts in Electron?

**Comment by navyasric** [comment]
@jbpoulsen The MSAL.js library is designed to work with SPA and browser based JS web apps. It does not support the native capabilities and integration required to work with a cross-plat framework like Electron. 
We do not currently have a definite roadmap for Electron and are still evaluating plans. Closing this issue for now.
