### ISSUE TITLE
[msal-node] Support updating the client assertion after creating the confidential client

### ISSUE THREAD

**Issue by sadasant** [AzureAD/microsoft-authentication-library-for-js#4481]
### Core Library

MSAL Node (@azure/msal-node)

### Wrapper Library

Not Applicable

### Description

In MSAL for .NET, the confidential client class has a method `confidnetialClient.WithClientAssertion()` which allows passing an asynchronous callback to update the client assertion.

The Azure SDK for JS&TS team would like to have this feature also in msal-node!

How does that sound? Feedback appreciated.

### Source

Internal (Microsoft)

**Comment by jasonnutter** [comment]
@sadasant Would the ability to set the assertion on a per request basis suffice (similar to other properties that can be set pre-request in MSAL)?

cc @EmLauber

**Comment by sadasant** [comment]
@jasonnutter I think so, but let me ask my team in case I’m missing something!

**Comment by sadasant** [comment]
@jasonnutter yep! having the ability to set the assertion on a per request basis would be enough! 🙂

**Comment by jasonnutter** [comment]
@sadasant Great, thanks! I can't comment on when we will be able to prioritize this, but you are also welcome to open a PR (to start, look for places in `msal-common` where the library reads from `this.config.clientCredentials` to populate the assertion on the request, and update it to also read an assertion provided on the request, and work up from there).

**Comment by EmLauber** [comment]
Work item is created & added to backlog. As Jason said, can't comment yet on priority. CC @sameerag

**Comment by svrooij** [comment]
A use case for this callback functionality is that you’re then able to generate an assertion in the key vault without being able to export the certificate. I’ve build a small extension for the dotnet SDK that dynamically creates an assertion on demand, by sending the unsigned assertion to the keyvault and signing it in the cloud.

more details [here](https://svrooij.io/2022/01/20/secure-multi-tenant-app/) and [here](https://svrooij.io/2022/03/03/keyvault-proxy/)

**Comment by sameerag** [comment]
A new `msal-node` release now has this functionality.

>> notes from the release

🎉@azure/msal-node@v1.10.0 has been released which incorporates this pull request.🎉

Handy links:

[Release Notes](https://github.com/AzureAD/microsoft-authentication-library-for-js/releases/tag/msal-node-v1.10.0)
[Official NPM Release](https://www.npmjs.com/package/@azure/msal-node/v/1.10.0)
