### ISSUE TITLE
Syncing session state across browsers when using sessionStorage

### ISSUE THREAD

**Issue by talhatfl** [AzureAD/microsoft-authentication-library-for-js#4490]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

None

### Description

Hi,

If a user has duplicated a tab in Chrome whilst the cache location is set to sessionStorage, we have noticed that logging a user out of one tab does not log them out of the duplicated tab. 

We followed [this](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/events.md#syncing-logged-in-state-across-tabs-and-windows) guide and are able to make it work when the cache location is set to localStorage.

Is it just not possible for sessionStorage?

Thanks

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@talhatfl It is not possible, unfortunately, as `storage` events for `sessionStorage` are only fired for the multiple frames of the same website within the same tab, but not across different tabs.

**Comment by talhatfl** [comment]
thanks for the update @jasonnutter
