### ISSUE TITLE
Data Fetching pattern question

### ISSUE THREAD

**Issue by pwang2** [AzureAD/microsoft-authentication-library-for-js#4494]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.21.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

NONE

### Description

Great work to provide an example battery-included with all good practices with modern framework features! 

Can you help explain why we need to watch on the `isProgress` in useMsal and call the API again in Line 38? Line34 already guarded `inProgress` has to be 'none',  at what condition the resolved could be `false` after setting to `true` at Line 37 and need to call again?

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/a146c2b656b98764375cd6a68de3d41ac2416442/samples/msal-browser-samples/vue3-sample-app/src/views/Profile.vue#L25-L50

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by tnorling** [comment]
@pwang2 Line 38 is not calling `getGraphData` again, it's calling the stop callback which tells the watcher to stop listening for changes to `inProgress`. You can read more about stopping watchers in the Vue docs [here](https://v3.vuejs.org/guide/reactivity-computed-watchers.html#stopping-the-watcher)

**Comment by pwang2** [comment]
You are right! Forget my temp stupidness . I should know that.  Thank you
very much.
