### ISSUE TITLE
Please clean-up and elaborate some of the documentation.

### ISSUE THREAD

**Issue by kizerkizer** [AzureAD/microsoft-authentication-library-for-js#450]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version
Latest

## Current behavior

Forward: I know this is a preview, so this is constructive feedback towards GA.

What is the point of the authCallback? Why are there two tokens (an identification token, and an access token), instead of just one? Authentication is decoupled from MS Graph, right? Why do we need to pass in "graph scopes" How come we pass in needed permissions twice - when fetching an id token and when fetching an access token. Some of these I have answered myself, but their resolution wasn't quick. Also, the documentation links 404 right now. I had to DL the docs. 

Maybe improve some example code, like:
```
        if (token) {
        }
        else {
            log(error + ":" + errorDesc);
        }
```

## Minimal reproduction of the problem with instructions

</code></pre>

**Comment by navyasric** [comment]
Thank you for the feedback. We are working on improving the documentation.

**Comment by navyasric** [comment]
Added more information related to these questions in Readme: https://github.com/AzureAD/microsoft-authentication-library-for-js/commit/394ead848a89d2062c6318c007c66867b0e22702
Closing this issue.
