### ISSUE TITLE
Which msal event can notify me when i logged in another application in the another tab(ex: office.com)  ? How can Microsoft teams and github are getting notified when i logged in another tab using azure AD login

### ISSUE THREAD

**Issue by lokesh-kr** [AzureAD/microsoft-authentication-library-for-js#4503]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.22.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.3.0

### Description

Scenario is I've two applications in 2 tabs and both are logged out.  if i logged in one tab i want to be notified in another tab. 
same domain apps in the 2tabs are getting  notified using enablestorageevents. I can able to use ssoSilent to login in my application when i logged in another app.
But how can my application know when i logged in another app(office.com) without ssoSilent ? How can Microsoft teams and github are getting notified when i logged in another tab using azure AD login 

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by bmahall** [comment]
Hi @lokesh-kr ! This is out-of-scope for the msal library. For the second app on a different domain to be notified, the user needs to go to aad. 
For the same session, to achieve this , please refer to [https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/events.md#syncing-logged-in-state-across-tabs-and-windows.  
](url)

**Comment by lokesh-kr** [comment]
Hi @bmahall , Thanks for the reply. we are using Azure active directory. please let me know what do you mean by **user needs to go to aad** ?

**Comment by lokesh-kr** [comment]
@tnorling  can you answer to my question ?

**Comment by bmahall** [comment]
@lokesh-kr Apologies for the delay . By going to aad, I meant using ssoSilent or one of the msal login Api's.
@tnorling might be able to add more context to this.
 Thanks for your patience!

**Comment by lokesh-kr** [comment]
@bmahall ssoSilent and msal login APis needs be triggered by user, but i'm asking is there a event which notifies  the tab(in which he logged out in the another application) as soon as the user logged in another application in another tab or window ?
@tnorling

**Comment by bmahall** [comment]
@lokesh-kr :- For the same app, this can be done using enableAccountStorageEvents API  (as you have mentioned in the description as well) . 
[https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/events.md#syncing-logged-in-state-across-tabs-and-windows](url)

However for apps on different domain, there is no similar way to notify another tab when the user has logged in the first tab. {For example, the tokens from Github cache cannot be accessed by Teams}. 
@tnorling

**Comment by lokesh-kr** [comment]
@bmahall thanks for the quick reply, when i logged in my application using aad,  Teams, office.com and github.com are getting notified, can you let me know how those tabs are getting notified ? is there a way we can configure like single sign-out Front-end channel URL (which sign out my app when i logged out in the another tab) for single sign-on ? @tnorling

**Comment by lokesh-kr** [comment]
@bmahall thanks for the quick reply, when i logged in my application using aad, Teams, office.com and github.com are getting notified, can you let me know how those tabs are getting notified ? is there a way we can configure like single sign-out Front-end channel URL (which signs out my app when i logged out another application in the another tab ) for single sign-on ? @tnorling

**Comment by bmahall** [comment]
@lokesh-kr When you refer to these apps getting notified, can you please share the concrete steps to reproduce this behavior in order to investigate this.  

Msal cannot automatically figure out when the user is signed in on another app. Your application can invoke loginRedirect or loginPopup which should complete very quickly if the user has an active AAD session. Alternatively, you can also pass the loginHint in the query parameter, which can be parsed by the second application and passed to msal. 

As for your second question, there is not one I am aware of , for Cross-domain apps. There is no straightforward way to share cookies for apps on different domain , and would require looking into the various options on case-by-case basis.  cc: @tnorling

**Comment by lokesh-kr** [comment]
@bmahall my bad, when i'm on my github signin page sometime i see **you've signed in another tab, please refresh**  message. but is not happening in teams.
