### ISSUE TITLE
This function acquiresTokenSilent which it uses to renew the token for me automatically?

### ISSUE THREAD

**Issue by gustavoabel** [AzureAD/microsoft-authentication-library-for-js#4506]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2

### Wrapper Library

Not Applicable

### Wrapper Library Version

2

### Description

I need to know if this is the right code so that after my token expires, call a refresh token to not stop my app.

### MSAL Configuration

```javascript
//MSAL configuration
const msalConfig = {
    auth: {
        clientId: '7e391644-15a5-47d4-9cd6-5d86711f4c66',
        authority: 'https://login.microsoftonline.com/92d143fd-f58c-420c-8469-393fab93e1ea',
        redirectUri: 'http://localhost:8080'
    }
};
const msalRequest = { scopes: ['user.read'] };
function ensureScope (scope) {
    if (!msalRequest.scopes.some((s) => s.toLowerCase() === scope.toLowerCase())) {
        msalRequest.scopes.push(scope);
    }
}
// Inicializa a Biblioteca MSAL.
const msalClient = new msal.PublicClientApplication(msalConfig);

// Conecta o usuário.
async function signIn() {
    const authResult = await msalClient.loginPopup(msalRequest);
    sessionStorage.setItem('msalAccount', authResult.account.username);
}
// Manipula a obtendo um token de acesso que Microsoft Graph pode usar.
async function getToken() {
    let account = sessionStorage.getItem('msalAccount');
    if (!account) {
        throw new Error(
            'As informações do usuário foram apagadas da sessão. Saia e faça login novamente.');
    }
    try {
        // Primeiro, tente obter o token silenciosamente
        const silentRequest = {
            scopes: msalRequest.scopes,
            account: msalClient.getAccountByUsername(account)
        };

        const silentResult = await msalClient.acquireTokenSilent(silentRequest);
        return silentResult.accessToken;
    } catch (silentError) {

        // Se as solicitações silenciosas falharem com InteractionRequiredAuthError,
        // tenta obter o token interativamente

        if (silentError instanceof msal.InteractionRequiredAuthError) {
            const interactiveResult = await msalClient.acquireTokenPopup(msalRequest);
            return interactiveResult.accessToken;
        } else {
            throw silentError;
        }
    }
}
```

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by gustavoabel** [comment]
When my application's token expires, I can't search the database, so I've been trying to renew this token for 1 week.

**Comment by bmahall** [comment]
Hi @gustavoabell ! Can you provide more information in the description regarding the part you are blocked on. 
Also, please refer to [https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1246] ,hope it helps!

**Comment by gustavoabel** [comment]
@bmahall done.

**Comment by bmahall** [comment]
@gustavoabell Thanks for that! As per [https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1246#issuecomment-578963619](url) 
you need to use acquireTokenSilent with the client-id of your application as the scope. 
Let me know if it helps!

**Comment by bmahall** [comment]
@gustavoabell  Can you try setting the silent request config similar to this and retry: (note the forceRefresh set to false option) :

var currentAccount = msalInstance.getAccountByUsername(username);
var silentRequest = {
    scopes: ["Mail.Read"],
    account: currentAccount,
    forceRefresh: false
};

**Comment by gustavoabel** [comment]
@bmahall in case this configuration you sent me, as soon as my access token expires will another one be called?

**Comment by gustavoabel** [comment]
@bmahall my goal is to bring a refresh token to my app, so when my access token expires it calls another one.. because when my app has an expired token I can't access the database.

**Comment by bmahall** [comment]
@gustavoabell Yes, calling acquireTokenSilent before every API request will enable MSAL to return an access token either from the cache, if still valid, or exchange the refresh token for a new access token.

 You only need to pass the account and the needed scopes to the acquireTokenSilent. Setting forceRefresh to true will enable skipping the cache lookup. 
For more details, please refer to:-
[https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/token-lifetimes.md#token-renewal](url)

 Note: Please ensure 3P cookies are not blocked on your system for ATS to automatically "renew" the tokens, i,e obtain new Refresh Token post expiry (default: 24h).

**Comment by gustavoabel** [comment]
@bmahall I have a question, in my case i published my app on microsoft azure and added an identity provider.. do i really need the MSAL login and logout to make the token scheme?

**Comment by gustavoabel** [comment]
@bmahall  I would also like to know if msal is an identity provider too.. because if it is I don't need the microsoft azure platform identity provider to authenticate to microsoft.

**Comment by bmahall** [comment]
@gustavoabell Was the previous question resolved? Please update. 

In regards to the new questions, Msal can be used to authenticate with MSA/AAD/other Social IDPs like Google, Facebook (Using B2C). It enables developers to acquire tokens from the Microsoft identity platform. If you prefer using an IDP other than the Azure IDP, you can do so. 

The MSAL Login and Logout Api calls are required for authentication. 
Does that help?

**Comment by gustavoabell** [comment]
@bmahall Can I have a more direct contact with you? my application does not need to logout.. just that when I access the application it redirects me to the login screen (this I have already managed to do) but I need to get the access token and do a validation so that when this token expires, get another token not to stop my application. Can you help me with this?

**Comment by gustavoabel** [comment]
@bmahall I can upload the application to my github repository

**Comment by jo-arroyo** [comment]
@gustavoabell Please provide the steps you are currently taking, and where you are seeing issues, so that we can better help you.

**Comment by gustavoabel** [comment]
All Right.

**Comment by pkanher617** [comment]
@gustavoabell Are you still having issues with this? A more detailed list of steps for the authentication flow can help us better understand what the desired behavior is here.
