### ISSUE TITLE
Unit Test for Project

### ISSUE THREAD

**Issue by gmiked** [AzureAD/microsoft-authentication-library-for-js#4508]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.19.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.5

### Description

I am trying to unit test using jest, but I am getting the below errors.  How to resolve?  Also, if I want to bypass MSALGuards for testing, how can you do this?  A previous question links to a github that doesn't exist anymore.

NullInjectorError: StaticInjectorError(DynamicTestModule)[MenuItemsComponent -> InjectionToken MSAL_GUARD_CONFIG]:
      StaticInjectorError(Platform: core)[MenuItemsComponent -> InjectionToken MSAL_GUARD_CONFIG]:
        NullInjectorError: No provider for InjectionToken MSAL_GUARD_CONFIG!

### Relevant Code Snippets

```javascript
import { TestBed } from '@angular/core/testing';
import { AppComponent } from './app.component';
import {CUSTOM_ELEMENTS_SCHEMA} from "@angular/core";

describe('AppComponent', () => {
  beforeEach(async () => {
    await TestBed.configureTestingModule({
      schemas: [CUSTOM_ELEMENTS_SCHEMA],
      declarations: [
        AppComponent
      ]
    }).compileComponents();
  });

  it('should create the app', () => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.componentInstance;
    expect(app).toBeTruthy();
  });

  it(`should have as title 'ClientApp'`, () => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.componentInstance;
    expect(app.title).toEqual('ClientApp');
  });

  it('should render title', () => {
    const fixture = TestBed.createComponent(AppComponent);
    fixture.detectChanges();
    const compiled = fixture.nativeElement as HTMLElement;
    expect(compiled.querySelector('.content span')?.textContent).toContain('ClientApp app is running!');
  });
});

```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by gmiked** [comment]
I want to add, I have an angular 12 project.

**Comment by bmahall** [comment]
Hi @gmiked , can you please share the relevant app code as well? Thanks

**Comment by gmiked** [comment]
@bmahall I updated the relevant app code section to include the entire app.component.spec.ts.

**Comment by bmahall** [comment]
@gmiked Thanks for uploading the test file. Can you please make sure that the msal and msal guard modules have been declared in the test file you shared and try re-running it?
You can refer to [https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/0a8e67b1159ba4d745b11a57bb598c73e2adbf92/lib/msal-angular/src/msal.broadcast.service.spec.ts#L23](url) and other test files in the msal-angular code.

**Comment by gmiked** [comment]
@bmahall Sure I can try that.  I would prefer to mock the services similar to the angular 8 app where possible.  Is it acceptable to mock the services similar to this example for MSAL v2 ?
[Angular 8 app example](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-angular-samples/angular8-sample-app/src/app/app.component.spec.ts)

**Comment by bmahall** [comment]
@gmiked  Yes , it should be totally fine! Please comment in case you face any issues during the mock.
