### ISSUE TITLE
message: "You do not have sufficient permissions to edit this workbook."

### ISSUE THREAD

**Issue by richard-313** [AzureAD/microsoft-authentication-library-for-js#4509]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

msal-browser v2.7.0 2020-12-03

### Wrapper Library

Not Applicable

### Wrapper Library Version

none

### Description

Hi, I hope someone can help me.
I setup msal for vanilla JS successful. I can access others Excel files and read it.
BUT I cannot write to others excel file.

I get this error:
<img width="569" alt="image" src="https://user-images.githubusercontent.com/10269756/153325766-5ab562a9-469f-45f3-8367-2fb0f1cf43e7.png">

What did I do for writing?
In https://portal.azure.com/ in my application I setup the permission like screenshot
<img width="1035" alt="Screenshot 2022-02-09 at 20 25 12" src="https://user-images.githubusercontent.com/10269756/153325304-138a477a-a078-4316-9c18-da6f7761e51c.png">
p

I use this code:
`const r = await OneDrive.callMSGraph(`https://graph.microsoft.com/v1.0/me/drive/items/F7084234324234D45763E%2126755/workbook/worksheets/Sheet1/range(address='A1:B2')`, 'PATCH',
            {
                "values": [
                    [
                        "KE",
                        "100"
                    ],
                    [
                        "1/1/2016",
                        null
                    ]
                ],
                "formulas": [
                    [
                        null,
                        null
                    ],
                    [
                        null,
                        "=B1*2"
                    ]
                ],
                "numberFormat": [
                    [
                        null,
                        null
                    ],
                    [
                        "m-ddd",
                        null
                    ]
                ]
            }
        );`

When I try https://graph.microsoft.com/v1.0/me/drive/items/F7084234324234D45763E%2126755/workbook/worksheets/Sheet1/range(address='A1:B2') in MS Graph Editor, it works perfectly.
So what can I do or what did I do wrong?

### MSAL Configuration

```javascript
this.msalInstance = new msal.PublicClientApplication({
            auth: {
                authority: "https://login.microsoftonline.com/common/",
                clientId: "2398476283469287346",
                redirectUri: chrome.identity.getRedirectURL("oauth2")
            },
            cache: {
                cacheLocation: "localStorage"
            }
        })
```

### Source

External (Customer)

**Comment by bmahall** [comment]
Hi @s72817 ! Can you please try putting your access token in jwt.ms and see if it has the required (app level permission) in the Roles claim? Please confirm if you have the admin role. 

Also, are you providing any scope? You would need to determine that for the endpoint you're calling, which scope(s) you need to request and add all of them for oauth2.

**Comment by richard-313** [comment]
Thanks @bmahall for the quick reply!!
I found it :)))))))
I use this example for chrome browser: https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/67e4af7ed6640ea1e140ed2eb3aec4bf6f5b674c/samples/msal-browser-samples/ChromiumExtensionSample
And in the following method I found the issue:
`
async acquireToken() {
        if (!this.msalInstance) return false;
        const account = this.msalInstance.getAllAccounts()[0];
        // console.log(account)
        const request = {
            scopes: ["files.read"],
            account: account
        }
        return this.msalInstance.acquireTokenSilent(request).catch(() => this.relogin(request));
    },
`
Here I changed to "files.readWrite.all".

Thanks a lot for your help. It was the right hint!

**Comment by bmahall** [comment]
Closing this, feel free to reach out in case of any other issues.
