### ISSUE TITLE
AccountInfo.name returns Display Name instead of Full Name

### ISSUE THREAD

**Issue by svdHero** [AzureAD/microsoft-authentication-library-for-js#4516]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.11.2

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.0-alpha.6

### Description

In the library's [source-code](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/src/account/AccountInfo.ts) the comments for type `AccountInfo` read:
```typescript
/**
 * Account object with the following signature:
 * - homeAccountId          - Home account identifier for this account object
 * - environment            - Entity which issued the token represented by the domain of the issuer (e.g. login.microsoftonline.com)
 * - tenantId               - Full tenant or organizational id that this account belongs to
 * - username               - preferred_username claim of the id_token that represents this account
 * - localAccountId         - Local, tenant-specific account identifer for this account object, usually used in legacy cases
 * - name                   - Full name for the account, including given name and family name
 * - idTokenClaims          - Object contains claims from ID token
 * - localAccountId         - The user's account ID
 */
export declare type AccountInfo = {
    homeAccountId: string;
    environment: string;
    tenantId: string;
    username: string;
    localAccountId: string;
    name?: string;
    idTokenClaims?: object;
};
```
Note how it describes the field `name` as `Full name for the account, including given name and family name`.

However, when I read `AccountInfo.name` it contains the display name instead of the given name and family name, although said claims are present in the Identity Token.

In particular, when I authenticate against Azure B2C where the display name is not part of the userflow's attributes and claims, the field `AccountInfo.name` is undefined, although there are claims `given_name` and `family_name` in the identity token.

So, is the source code comment wrong here? Is this a bug?

My feature request would be to replace `name` by three new fields:

- `AccountInfo.displayName`
- `AccountInfo.givenName`
- `AccountInfo.familyName`

This way all information from the identity token would be available easily to the Front-End Code. For backward compatibility, `AccountInfo.name` could be kept, containing the same value as `AccountInfo.displayName`.

### Relevant Code Snippets

```javascript
const accountInfo = msalInstance.getActiveAccount()
const fullName = accountInfo?.name // is NOT Full Name, but Display Name or undefined
```

### Identity Provider

Azure B2C Basic Policy

### Source

External (Customer)

**Comment by peterzenz** [comment]
The comment is more accurate when using at the non-B2C variant of Azure Active Directory, apologies for the confusion here.  B2C might only have a display name which gets inserted into name.  More information on [Azure B2C names](https://docs.microsoft.com/en-us/azure/active-directory-b2c/user-profile-attributes#required-attributes) and on that same page you can read about Extension Attributes which would contain Given Name and Surname if they are enabled for the tenant.

**Comment by svdHero** [comment]
@peterzenz thank you for your explanation, but I still don't understand. Like I wrote above, given name and family name are part of the B2C registration form. They are visible in the AD of the B2C tenant and they are included in the id token claims. I can read them manually from the token.

Shouldn't they be provided via `AccountInfo.name` then?

And wouldn't it be more consistent across systems to distinguish between `display name` and `full name` in `AccountInfo` instead of having some generic `name` field?

**Comment by pkanher617** [comment]
> My feature request would be to replace name by three new fields:
> 
> AccountInfo.displayName
> AccountInfo.givenName
> AccountInfo.familyName

> This way all information from the identity token would be available easily to the Front-End Code

All of these claims can be found under the `idTokenClaims` object as well, so adding these to the AccountInfo object doesn't seem necessary. The `.name` field is more of a convenience feature, but any code dependent on a specific claim can get it from the `idTokenClaims` property.

**Comment by svdHero** [comment]
@pkanher617 thank you for your advice. That's what I am actually doing, reading from the claims directly.

I was just wondering if improving said convenience feature might be helpful for some users. Especially for people using Typescript who don't want to write yet another interface just to access `idTokenClaims` in a type-safe way.
