### ISSUE TITLE
[msal-react] How should I automate Azure AD login in my automated integration test?

### ISSUE THREAD

**Issue by whatjakecodes** [AzureAD/microsoft-authentication-library-for-js#4519]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.21.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.2.0

### Description

I am working on an automated test (e.g. using Cypress or Selenium) that needs to initially get pass the Azure AD login screen.

In this test, I am able to make a POST request to `https://login.microsoftonline.com/my-tenantId/oauth2/v2.0/token` with the grant type `client_credentials` and a client_id and client_secret. I get a token back. 

However, I don't understand how I should save this token into the sessionStorage so that when my Cypress test visits `localhost:8080`, I avoid the redirect to login again. I would prefer my test to not use an email/password to login (and instead use the client credentials).

When I look at how msal-react updates the sessionStorage in my real-world browser runtime, I see quite a few MSAL tokens being saved into session storage. I don't understand if I need to get all of these using POST requests.

Am I going about automating this the wrong way? Would love some guidance or direction on which documentation I should read for my use case. Thanks!

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by hectormmg** [comment]
Hi, @whatjakecodes ! Thanks for the question.

So, there's quite a big difference between the way MSAL React (which wraps MSAL Browser) acquires and stores tokens on the browser and the way you would handle tokens acquired through the Client Credentials grant. Since MSAL React works on the browser side, it can't keep a client secret secure, meaning it can't use the Client Credentials flow.  Since your automated tests (Cypress, Selenium) run inside Node, you can manually execute POST requests with a client secret that you must keep protected yourself.

**A question I have in this case is whether you are testing code that uses MSAL React or if you need AAD access tokens for some other reason?** We need a little bit more context on what you're trying to achieve in order to provide accurate advice here.

Unfortunately, we don't have much documentation around our own end-to-end tests since only internal devs really interact with them, but looking though the following directories may help see how we handle this ourselves:

- [samples/msal-browser-samples/VanillaJSTestApp2.0/app/customisable-e2e-test](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-browser-samples/VanillaJSTestApp2.0/app/customizable-e2e-test)
- [samples/msal-node-samples/auth-code/test](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/auth-code/test)


I hope these files help, please let us know if you have any further questions.

**Comment by whatjakecodes** [comment]
thanks for following up, @hectormmg! I am looking into those links, as well as this library that seems to do what I am trying to do: https://www.npmjs.com/package/cypress-msal-login

> **A question I have in this case is whether you are testing code that uses MSAL React or if you need AAD access tokens for some other reason**? 

We are indeed testing an app that relies on MSAL React! Our app uses `UnauthenticatedTemplate` and `AuthenticatedTemplate` components -- if the Unauthenticated component loads, our app immediately redirects to the logon.microsoft.com/tenantID URL. This redirect is what we are trying to prevent by having our e2e test first establish a valid session, and then after that, our e2e test navigates to our app hosted on localhost (and that app should detect we already have a session, and thus not redirect).

My team came to the conclusion today that `client_credentials` isn't the correct grant type for our use case. It's not similar enough to a user logging in. So we're exploring using a test user account credential with the `password` grant_type instead, now.

**We're trying to get something like the below code working. The main problem we're having, is after getting the response back, how should we save the token into sessionStorage correctly? Saving to `id_token` as below is wrong - msal-react seems to save several token key names, and I am not sure how to generate that list of token keys properly**

```
Cypress.Commands.add("aadAuthenticate", window => {
    const clientId = "my-client-id";
    const tenantId = "my-tenant-id";
    const clientSecret = "my-secret";

    cy.request({
        method: "POST",
        url: `https://login.microsoftonline.com/${tenantId}/oauth2/v2.0/token`,
        header: {
            "cache-control": "no-cache",
            "Content-Type": "application/x-www-form-urlencoded"
        },
        form: true,
        body: {
            client_id: clientId,
            client_secret: clientSecret,
            username: "testaccount@test.com",
            password: "test-pw",
            grant_type: "password",
            scope: "api://my-app.com/app.Read openid profile"
        }
    }).then(response => {
        const token = response.body.access_token;
        window.sessionStorage.setItem("id_token", token);
    });
});
```

**Comment by hectormmg** [comment]
@whatjakecodes I wouldn't recommend obtaining a token yourself and then adding it to the cache so that MSAL React picks it up. You would need to replicate MSAL's caching logic and that is just too complicated (especially since our cache schema is subject to unannounced changes that will break your tests).

Furthermore, I don't think it's a good idea to avoid the interactive login since it's clearly a part of the flow you are testing end-to-end. I suggest setting up a test account and then automating the credential input (as securely as possible of course, don't hardcode the credentials into your code, use environment variables that are secured).

Also, if you set up your tests in such a way that you do the login once and then navigate within your app to test different things instead of destroying the browser session (i.e. closing the tab or window and re-initialzing), MSAL will be able to access the acquired tokens from the cache without a problem.

**Comment by whatjakecodes** [comment]
That all makes sense.. Unfortunately, logging into the Microsoft SSO from Cypress by filling in the fields and clicking the buttons isn't well supported and they recommend against it here: https://docs.cypress.io/guides/references/best-practices#Visiting-external-sites. I do think I can get it to work, however.

By the way, I am having luck with the [cypress-msal-login](https://www.npmjs.com/package/cypress-msal-login) package. This package provides a Cypress plugin command that gets the oauth session without clicking UI buttons, but making an API request. [The author directly uses the `ResponseHandler` from `msal-common` to get MSAL's caching logic, it seems](https://github.com/joelmeiller/cypress-msal-login/blob/main/src/client/OauthClient.ts#L132). I'm not sure if you would recommend pulling that utility out - it's also subject to change sporadically, I'm assuming.

**Comment by whatjakecodes** [comment]
Looking into setting our test to fill in the Microsoft SSO page form and click the sign in button... 

We'd like our test to first navigate to `https://login.microsoftonline.com/my-tenant-id/oauth2/v2.0/authorize` and login, and then second navigate to `localhost:8080`. This would be different from going directly to `localhost:8080` and letting msal-react redirect our test harness browser to the microsoft SSO login -- the redirect breaks out of the Cypress test harness browser and cannot return back properly.

My question is, how do you recommend we properly build the below URL for the first navigation to sign-in? Particularly the `nonce` and `code_challenge` and `state`. These seem to be required - without them, the microsoft SSO webpage won't load within the Cypress test harness browser. Is there a possibility that the microsoft SSO webpage blocks automated scripts from logging in?

URL we need to build, taken from the redirect that msal-react triggers when calling `msal.instance.loginRedirect`:

```
https://login.microsoftonline.com/my-tenant-id/oauth2/v2.0/authorize?client_id=abcd&
scope=scopes&
redirect_uri=http%3A%2F%2Flocalhost:8080&
client-request-id=1234...&
response_mode=fragment&
response_type=code&
x-client-SKU=msal.js.browser&
x-client-VER=2.21.0&
x-client-OS=&
x-client-CPU=&
client_info=1&
code_challenge=xyz123...&
code_challenge_method=S256&
nonce=57f...&
state=eyJpZC...
```

**Comment by hectormmg** [comment]
@whatjakecodes I don't recommend trying to handle the login yourself, you would essentially be re-implementing what MSAL already does. It's not as simple as navigating to a page and filling in the credentials, the Authorization Code flow has a lot of nuances that MSAL abstracts away for you (the nonce, code_challenge, state, etc. are just the tip of the iceberg here).

I don't see why the regular MSAL authentication flow should break out of the Cypress test harness browser, there is nothing on the Microsoft login prompt that blocks automation (we automate login for our own tests).

> he redirect breaks out of the Cypress test harness browser and cannot return back properly

What kind of error are you seeing here?

**Comment by whatjakecodes** [comment]
The error I was seeing was that the Cypress test harness, which loads `localhost:8080` where the app is running into an iframe, would redirect the entire page (including the Cypress harness, which is outside the iframe on `localhost:15436` or some such port) to the microsoft online login page, rather than contain the redirect within the iframe.

Perhaps there are some settings to make that redirect work more smoothly within the iframe?

My idea for another option is to first, within the Cypress iframe, directly visit the microsoft login page and click through signin. Then navigate to localhost:8080 and the iframe would retain the session information. Unfortunately this didn't work very well, for the reasons you described above.


My issue is, for now, resolved because I am using the `cypress-msal-login` package, which wraps a lot of MSAL common and browser function calls to programmatically sign in. I'm not sure how long that plugin will be maintained, though, so I'm still a bit apprehensive and may have to contribute to it some day if it ever breaks. For now, at least, it seems to be a great plugin.

**Comment by hectormmg** [comment]
@whatjakecodes I've been looking further into your approach, and I think you should check out the [testing doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/testing.md) we have on using `loadExternalTokens` API. What you originally wanted to do is achievable through this advanced API.

**Comment by mikkelmk** [comment]
I did something like this, which is... suboptimal. It has, however, worked seamlessly. 

```javascript
export const loginAndVisit = (url) => {
  const clientId = Cypress.env('CLIENT_ID');
  const tenantId = Cypress.env('TENANT_ID');
  const api = `api://${Cypress.env('API_CLIENT_ID')}/foo`;
  const scope = `${api} profile openid offline_access`;

  const options = {
    method: 'POST',
    url: `https://login.microsoftonline.com/${tenantId}/oauth2/v2.0/token`,
    form: true,
    body: {
      grant_type: 'password',
      scope: scope,
      client_id: clientId,
      username: Cypress.env('USERNAME'),
      password: Cypress.env('PASSWORD'),
      client_secret: Cypress.env('CLIENT_SECRET'),
    },
  };

  return cy.request(options).then((response) => {
    const responseBody = response.body;

    const accessToken = responseBody.access_token;
    const idToken = responseBody.id_token;
    const refreshToken = responseBody.refresh_token;

    const accessTokenPayload = JSON.parse(Buffer.from(accessToken.split('.')[1], 'base64'));
    const idTokenPayload = JSON.parse(Buffer.from(idToken.split('.')[1], 'base64'));

    const environment = 'login.windows.net';
    const homeAccountId = `${accessTokenPayload.oid}.${tenantId}`;

    const accountKey = `${homeAccountId}-${environment}-${tenantId}`;
    const accountValue = {
      authorityType: 'MSSTS',
      clientInfo: Buffer.from(
        JSON.stringify({
          uid: accessTokenPayload.oid,
          utid: tenantId,
        })
      ).toString('base64'),
      environment,
      homeAccountId,
      idTokenClaims: idTokenPayload,
      localAccountId: accessTokenPayload.oid,
      name: accessTokenPayload.name,
      realm: tenantId,
      username: accessTokenPayload.preferred_username,
    };

    const idTokenKey = `${homeAccountId}-${environment}-idtoken-${clientId}-${tenantId}-`;
    const idTokenValue = {
      credentialType: 'IdToken',
      clientId,
      environment,
      homeAccountId,
      realm: tenantId,
      secret: idToken,
    };

    const accessTokenKey = `${homeAccountId}-${environment}-accesstoken-${clientId}-${tenantId}-${api}`;
    const accessTokenValue = {
      credentialType: 'AccessToken',
      cachedAt: Math.round(new Date().getTime() / 1000.0).toString(),
      clientId,
      environment,
      expiresOn: accessTokenPayload.exp,
      extendedExpiresOn: accessTokenPayload.exp + responseBody.ext_expires_in,
      homeAccountId,
      realm: tenantId,
      secret: accessToken,
      target: api,
      tokenType: 'Bearer',
    };

    const refreshTokenKey = `${homeAccountId}-${environment}-refreshtoken-${clientId}--`;
    const refreshTokenValue = {
      credentialType: 'RefreshToken',
      clientId,
      environment,
      homeAccountId,
      secret: refreshToken,
    };

    localStorage.clear();
    localStorage.setItem(accountKey, JSON.stringify(accountValue));
    localStorage.setItem(accessTokenKey, JSON.stringify(accessTokenValue));
    localStorage.setItem(idTokenKey, JSON.stringify(idTokenValue));
    localStorage.setItem(refreshTokenKey, JSON.stringify(refreshTokenValue));

    return cy.visit(url);
  });
};
```

`loadExternalTokens` might be a better way to achieve something similar.

**Comment by hectormmg** [comment]
@whatjakecodes yes, `loadExternalTokens` should help abstract away most of this logic, please let us know if your issue is resolved so we can close this ticket.

**Comment by djcarryout** [comment]
Yes you can mark it resolved. I appreciate your support very much, @hectormmg !

**Comment by whatjakecodes** [comment]
Yes, please mark it resolved. Appreciate your support, @hectormmg !

**Comment by 2strokes** [comment]
@hectormmg Thank you for all the suggestions. I am in a similar scenario and would like to know if loadExternalTokens can be used with client credentials grant to obtain token.

**Comment by hectormmg** [comment]
> @hectormmg Thank you for all the suggestions. I am in a similar scenario and would like to know if loadExternalTokens can be used with client credentials grant to obtain token.

@2strokes we recommend the username password grant for this testing scenario (never use ROPC or username/password grant in production on a confidential client application)

**Comment by prsauer** [comment]
@hectormmg Getting an error using the `loadExternalTokens` strategy -- since I'm not granted a refresh token and it seems like the access token I'm injecting isn't being used:

```
AuthError.js?a1f2:27 Uncaught (in promise) InteractionRequiredAuthError: no_tokens_found: No refresh token found in the cache. Please sign-in.
```

**Comment by prsauer** [comment]
@hectormmg please see https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4710

**Comment by weenix1** [comment]
I have a security feature called Two-Factor Authentication (2FA) enabled when logging in. It requires the user to enter a number displayed on the screen into an authenticator app. I want to automate this process. How can I do that?

**Comment by tcb1978** [comment]
I have an identical issue to [https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4519#issuecomment-1040863809]. What can I update in local or session storage that will update MsalProvider within Cypress to display authenticated routes?
