### ISSUE TITLE
Cannot login on msal-react, error on console.log()

### ISSUE THREAD

**Issue by getwebem** [AzureAD/microsoft-authentication-library-for-js#4522]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

^2.14.2

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

MSAL.js for React B2C Sample

### Description

I am getting an error in the console.log() FetchClient.ts:24   as the place for the error. Line 24 is the await in the function below
  /**
     * Fetch Client for REST endpoints - Get request
     * @param url 
     * @param headers 
     * @param body 
     */
    async sendGetRequestAsync<T>(url: string, options?: NetworkRequestOptions): Promise<NetworkResponse<T>> {
        let response;
        try {
            response = await fetch(url, {
                method: HTTP_REQUEST_TYPE.GET,
                headers: this.getFetchHeaders(options)
            });
        } catch (e) {
            if (window.navigator.onLine) {
                throw BrowserAuthError.createGetRequestFailedError(e, url);
            } else {
                throw BrowserAuthError.createNoNetworkConnectivityError();
            }
        }

### Error Message

The resulting error from the console.log();

`GET https://promise%20ltd.b2clogin.com/promise%20ltd.onmicrosoft.com/b2c_1_signin_signout/v2.0/.well-known/openid-configuration net::ERR_NAME_NOT_RESOLVED`

### Msal Logs

not sure

### MSAL Configuration

```javascript
// Config object to be passed to Msal on creation
export const msalConfig = {
    auth: {
        clientId: "3a68f70e-c7c9-4115-9b55-7bf1da0d366f",
        authority: "https://Promise Ltd.b2clogin.com/Promise Ltd.onmicrosoft.com/B2C_1_signin_signout",
        knownAuthorities: ["Promise Ltd.b2clogin.com"],
        redirectUri: "http://localhost:4200",
        postLogoutRedirectUri: "http://localhost:4200"
    }
};

// Scopes you add here will be prompted for consent during login
export const loginRequest = {
    scopes: ["https://Promise Ltd.onmicrosoft.com/helloapi/demo.read"]
};
```

### Relevant Code Snippets

```javascript
/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License.
 */

import { INetworkModule, NetworkRequestOptions, NetworkResponse } from "@azure/msal-common";
import { BrowserAuthError } from "../error/BrowserAuthError";
import { HTTP_REQUEST_TYPE } from "../utils/BrowserConstants";

/**
 * This class implements the Fetch API for GET and POST requests. See more here: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API
 */
export class FetchClient implements INetworkModule {

    /**
     * Fetch Client for REST endpoints - Get request
     * @param url 
     * @param headers 
     * @param body 
     */
    async sendGetRequestAsync<T>(url: string, options?: NetworkRequestOptions): Promise<NetworkResponse<T>> {
        let response;
        try {
            response = await fetch(url, {
                method: HTTP_REQUEST_TYPE.GET,
                headers: this.getFetchHeaders(options)
            });
        } catch (e) {
            if (window.navigator.onLine) {
                throw BrowserAuthError.createGetRequestFailedError(e, url);
            } else {
                throw BrowserAuthError.createNoNetworkConnectivityError();
            }
        }

        try {
            return {
                headers: this.getHeaderDict(response.headers),
                body: await response.json() as T,
                status: response.status
            };
        } catch (e) {
            throw BrowserAuthError.createFailedToParseNetworkResponseError(url);
        }
    }

    /**
     * Fetch Client for REST endpoints - Post request
     * @param url 
     * @param headers 
     * @param body 
     */
    async sendPostRequestAsync<T>(url: string, options?: NetworkRequestOptions): Promise<NetworkResponse<T>> {
        const reqBody = (options && options.body) || "";

        let response;
        try {
            response = await fetch(url, {
                method: HTTP_REQUEST_TYPE.POST,
                headers: this.getFetchHeaders(options),
                body: reqBody
            });
        } catch (e) {
            if (window.navigator.onLine) {
                throw BrowserAuthError.createPostRequestFailedError(e, url);
            } else {
                throw BrowserAuthError.createNoNetworkConnectivityError();
            }
        }

        try {
            return {
                headers: this.getHeaderDict(response.headers),
                body: await response.json() as T,
                status: response.status
            };
        } catch (e) {
            throw BrowserAuthError.createFailedToParseNetworkResponseError(url);
        }
    }

    /**
     * Get Fetch API Headers object from string map
     * @param inputHeaders 
     */
    private getFetchHeaders(options?: NetworkRequestOptions): Headers {
        const headers = new Headers();
        if (!(options && options.headers)) {
            return headers;
        }
        const optionsHeaders = options.headers;
        Object.keys(optionsHeaders).forEach((key) => {
            headers.append(key, optionsHeaders[key]);
        });
        return headers;
    }

FetchClient.ts 
-----------------------

    private getHeaderDict(headers: Headers): Record<string, string> {
        const headerDict: Record<string, string> = {};
        headers.forEach((value: string, key: string) => {
            headerDict[key] = value;
        });
        return headerDict;
    }
}
```

### Reproduction Steps

https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/b2c-sample

### Expected Behavior

this error is not supposed to show

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Internet Explorer

### Regression

none

### Source

Internal (Microsoft)

**Comment by hectormmg** [comment]
Hi @getwebem ! Please review your MSAL and request configuration, the `authority` and `knownAuthorities `values seem off to me, same as the initial part of the scope, these should be normal URLs. There should be no spaces, I believe these values are incorrect.


```javascript
// Config object to be passed to Msal on creation
export const msalConfig = {
    auth: {
        clientId: "3a68f70e-c7c9-4115-9b55-7bf1da0d366f",
        authority: "https://Promise Ltd.b2clogin.com/Promise Ltd.onmicrosoft.com/B2C_1_signin_signout", // There shouldn't be any spaces in this string
        knownAuthorities: ["Promise Ltd.b2clogin.com"], // There shouldn't be any spaces in this string
        redirectUri: "http://localhost:4200",
        postLogoutRedirectUri: "http://localhost:4200"
    }
};

// Scopes you add here will be prompted for consent during login
export const loginRequest = {
    scopes: ["https://Promise Ltd.onmicrosoft.com/helloapi/demo.read"] // There shouldn't be any spaces in this string
};
```

In short, your base authority seems to be incorrect as far as I can tell.

**Comment by getwebem** [comment]
hi Hectormmg, I understand what you mean but even my new msal i still face the same error: 

// Config object to be passed to Msal on creation
export const msalConfig = {
    auth: {
        clientId: "7ab42012-eec1-4e5f-b82d-218d1ec6ce7e",
        authority: "https://promise-web001.b2clogin.com/promise-web001.onmicrosoft.com/B2C_1_signup_signin_b2c001",
        knownAuthorities: ["promise-web001.b2clogin.com"],
        redirectUri: "http://localhost:4200",
        postLogoutRedirectUri: "http://localhost:4200"
    }
};

// Scopes you add here will be prompted for consent during login
export const loginRequest = {
    scopes: ["https://promise-web001.onmicrosoft.com/helloapi/demo.read"]
};

**Comment by getwebem** [comment]
This MSAL and the one with spaces in them I can both sign in an get the jwt.ms token so i suspect the error might be in my b2c configuration, am happy to send you the details

**Comment by getwebem** [comment]
B2C_1_signup_signin_b2c001
B2C_1_reset_passwordb2c001
B2C_1_profile_editingb2c001
------
Display name: promise-web001

**Comment by hectormmg** [comment]
@getwebem please turn on the verbose logs in your MSAL config and share those so we can better figure out what's going on.

```javascript
// Config object to be passed to Msal on creation
export const msalConfig = {
    auth: {
      ...
    },
    system: {
        loggerOptions: {
            loggerCallback: (level, message, containsPii) => {
                if (containsPii) {	
                    return;	
                }
                switch (level) {	
                    case msal.LogLevel.Error:	
                        console.error(message);	
                        return;	
                    case msal.LogLevel.Info:	
                        console.info(message);	
                        return;	
                    case msal.LogLevel.Verbose:	
                        console.debug(message);	
                        return;	
                    case msal.LogLevel.Warning:	
                        console.warn(message);	
                        return;	
                }
            },
           logLevel: msal.LogLevel.Verbose
        }
    }
};
```

**Comment by getwebem** [comment]
`GET https://promise-web001.b2clogin.com/promise-web001.onmicrosoft.com/b2c_1_signup_signin_b2c001/v2.0/.well-known/openid-configuration 404 (Not Found)`

**Comment by getwebem** [comment]
@hectormmg the only  msalConfig file in my code is listed below:

// Config object to be passed to Msal on creation
export const msalConfig = {
    auth: {
        clientId: "7ab42012-eec1-4e5f-b82d-218d1ec6ce7e",
        authority: "https://promise-web001.b2clogin.com/promise-web001.onmicrosoft.com/B2C_1_signup_signin_b2c001",
        knownAuthorities: ["promise-web001.b2clogin.com"],
        redirectUri: "http://localhost:4200",
        postLogoutRedirectUri: "http://localhost:4200"
    }
};

// Scopes you add here will be prompted for consent during login
export const loginRequest = {
    scopes: ["https://promise-web001.onmicrosoft.com/helloapi/demo.read"]
};

I also double checked the original sample code it doesn't have that code you're refering to:
[MSAL.js for React B2C Sample - Authorization Code Flow in Single-Page Applications](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/b2c-sample)

**Comment by hectormmg** [comment]
@getwebem yes, I'm suggesting you add the `system` configuration object to your config to turn the MSAL logger on. This way you'll be able to see the logs on the browser console and get more diagnostic info.

**Comment by getwebem** [comment]
This is the updated code

![Screenshot (278)](https://user-images.githubusercontent.com/15692073/154155542-993d5e7d-5d76-4f1e-9f22-17317fb2760b.png)

**Comment by getwebem** [comment]
These are the errors in the console.log()

Uncaught ReferenceError: msal is not defined
    at Module.<anonymous> (authConfig.js:34:1)
    at Module../src/authConfig.js (authConfig.js:42:1)
    at __webpack_require__ (bootstrap:851:1)
    at fn (bootstrap:150:1)
    at Module.<anonymous> (ProtectedData.jsx:57:1)
    at Module../src/ui-components/SignInButton.jsx (SignInButton.jsx:10:1)
    at __webpack_require__ (bootstrap:851:1)
    at fn (bootstrap:150:1)
    at Module.<anonymous> (SignInButton.jsx:10:1)
    at Module../src/ui-components/SignInSignOutButton.jsx (SignInSignOutButton.jsx:21:1)
    at __webpack_require__ (bootstrap:851:1)
    at fn (bootstrap:150:1)
    at Module.<anonymous> (Loading.jsx:4:1)
    at Module../src/ui-components/NavBar.jsx (NavBar.jsx:29:1)
    at __webpack_require__ (bootstrap:851:1)
    at fn (bootstrap:150:1)
    at Module.<anonymous> (NavBar.jsx:29:1)
    at Module../src/ui-components/PageLayout.jsx (PageLayout.jsx:5:1)
    at __webpack_require__ (bootstrap:851:1)
    at fn (bootstrap:150:1)
    at Module.<anonymous> (main.chunk.js:17:83)
    at Module../src/App.js (App.js:46:1)
    at __webpack_require__ (bootstrap:851:1)
    at fn (bootstrap:150:1)
    at Module.<anonymous> (authConfig.js:42:1)
    at Module../src/index.js (index.js:13:1)
    at __webpack_require__ (bootstrap:851:1)
    at fn (bootstrap:150:1)
    at Object.1 (WelcomeName.jsx:25:1)
    at __webpack_require__ (bootstrap:851:1)
    at checkDeferredModules (bootstrap:45:1)
    at Array.webpackJsonpCallback [as push] (bootstrap:32:1)
    at main.chunk.js:1:73
(anonymous) @ authConfig.js:34
./src/authConfig.js @ authConfig.js:42
__webpack_require__ @ bootstrap:851
fn @ bootstrap:150
(anonymous) @ ProtectedData.jsx:57
./src/ui-components/SignInButton.jsx @ SignInButton.jsx:10
__webpack_require__ @ bootstrap:851
fn @ bootstrap:150
(anonymous) @ SignInButton.jsx:10
./src/ui-components/SignInSignOutButton.jsx @ SignInSignOutButton.jsx:21
__webpack_require__ @ bootstrap:851
fn @ bootstrap:150
(anonymous) @ Loading.jsx:4
./src/ui-components/NavBar.jsx @ NavBar.jsx:29
__webpack_require__ @ bootstrap:851
fn @ bootstrap:150
(anonymous) @ NavBar.jsx:29
./src/ui-components/PageLayout.jsx @ PageLayout.jsx:5
__webpack_require__ @ bootstrap:851
fn @ bootstrap:150
(anonymous) @ main.chunk.js:17
./src/App.js @ App.js:46
__webpack_require__ @ bootstrap:851
fn @ bootstrap:150
(anonymous) @ authConfig.js:42
./src/index.js @ index.js:13
__webpack_require__ @ bootstrap:851
fn @ bootstrap:150
1 @ WelcomeName.jsx:25
__webpack_require__ @ bootstrap:851
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
Show 3 more frames
VM70:2 Uncaught ReferenceError: process is not defined
    at Object.4043 (<anonymous>:2:13168)
    at r (<anonymous>:2:306599)
    at Object.8048 (<anonymous>:2:9496)
    at r (<anonymous>:2:306599)
    at Object.8641 (<anonymous>:2:1379)
    at r (<anonymous>:2:306599)
    at <anonymous>:2:315627
    at <anonymous>:2:324225
    at <anonymous>:2:324229
    at HTMLIFrameElement.e.onload (index.js:1:1)
4043 @ VM70:2
r @ VM70:2
8048 @ VM70:2
r @ VM70:2
8641 @ VM70:2
r @ VM70:2
(anonymous) @ VM70:2
(anonymous) @ VM70:2
(anonymous) @ VM70:2
e.onload @ index.js:1
be @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
load (async)
be @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
Promise.then (async)
(anonymous) @ index.js:1
(anonymous) @ index.js:1
t @ index.js:1
error (async)
o @ index.js:1
(anonymous) @ index.js:1
ge @ index.js:1
./node_modules/react-dev-utils/webpackHotDevClient.js @ webpackHotDevClient.js:45
__webpack_require__ @ bootstrap:851
fn @ bootstrap:150
1 @ WelcomeName.jsx:25
__webpack_require__ @ bootstrap:851
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
index.js:1 src\authConfig.js
  Line 20:26:  'msal' is not defined  no-undef
  Line 23:26:  'msal' is not defined  no-undef
  Line 26:26:  'msal' is not defined  no-undef
  Line 29:26:  'msal' is not defined  no-undef
  Line 34:22:  'msal' is not defined  no-undef

Search for the keywords to learn more about each error.

**Comment by getwebem** [comment]
Errors from console.log()

![Screenshot (277)](https://user-images.githubusercontent.com/15692073/154155201-81d8eb1b-f77f-4b1d-bdb2-4d1a8c2b73fa.png)

**Comment by hectormmg** [comment]
@getwebem add:

```javascript
import { LogLevel } from "@azure/msal-browser";
```

And then instead of `logLevel: msal.LogLevel.Verbose` do `logLevel: LogLevel.Verbose`

**Comment by getwebem** [comment]
@hectormmg I have attached the updated code as well as the Error results 
![Screenshot (282)](https://user-images.githubusercontent.com/15692073/154238220-3c53c3fa-8957-44e0-899f-1f952a09dcf8.png)


![Screenshot (283)](https://user-images.githubusercontent.com/15692073/154238245-b1c5bfae-eb5b-4901-afd5-a63d187e2143.png)

**Comment by hectormmg** [comment]
@getwebem sorry, please remove the `msal.` from lines 22-31.

**Comment by getwebem** [comment]
@hectormmg  updated code now


![Screenshot (289)](https://user-images.githubusercontent.com/15692073/154327898-f311cc68-26cf-4d27-a4da-1a628bf53634.png)

**Comment by getwebem** [comment]
@hectormmg The error from console.log()

![Screenshot (288)](https://user-images.githubusercontent.com/15692073/154326836-7e911cd5-8642-4a84-a836-dfb920888bba.png)

**Comment by hectormmg** [comment]
@getwebem could you [file a support](https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options) ticket with the B2C service team? This is most likely related to your B2C configuration and not MSAL itself, thanks!
