### ISSUE TITLE
login.live.com CORS error

### ISSUE THREAD

**Issue by patrick-rodgers** [AzureAD/microsoft-authentication-library-for-js#4524]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

^2.19.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

I need to retrieve a token with scope "OneDrive.ReadWrite" for use with a file picker targeting OneDrive consumer (@live.com account). I setup the configuration as below and pass the scopes. As best I can tell from various available documents this should work. But I am currently stuck on a CORS error hitting "https://login.live.com/.well-known/openid-configuration" from localhost. I can hit that url directly so the url is correct.

My app has the correct redirects configured, is setup as a SPA, and works for all other cases (SharePoint, Graph).

For reference I reviewed [this issue](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1824), [associated PR](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/2389), and the [docs it updated](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/initialization.md#optional-configure-authority).

Appreciate any guidance to the proper way to achieve getting a token from login.live.com.

### MSAL Configuration

```javascript
{
    auth: {
        authority: "https://login.live.com/",
        clientId,
        knownAuthorities: ["login.live.com"],
        protocolMode: "OIDC",
        redirectUri: "http://localhost:3000",
    },
}
```

### Relevant Code Snippets

```javascript
import { Configuration, PublicClientApplication } from "@azure/msal-browser";

 const app = new PublicClientApplication(config);

let accessToken: string;
                const authParams = { scopes: scopes || [`${combine(command.resource, ".default")}`] };

                try {

                    // see if we have already the idtoken saved
                    const resp = await app.acquireTokenSilent(authParams);
                    accessToken = resp.accessToken;

                } catch (e) {

                    // per examples we fall back to popup
                    const resp = await app.loginPopup(authParams);

                    if (resp.account) {
                        app.setActiveAccount(resp.account);
                    }

                    if (resp.idToken) {

                        const resp2 = await app.acquireTokenSilent(authParams);
                        accessToken = resp2.accessToken;

                    } else {

                        this.error(e);
                    }
                }

                if (accessToken) {
                    this.log(`Returning token for auth type: '${command.type}'`, 0);
                    result = {
                        result: "token",
                        token: accessToken,
                    }
                }
```

### Identity Provider

Other

### Source

Internal (Microsoft)

**Comment by hectormmg** [comment]
@patrick-rodgers thanks for raising the issue, I've gone through your description and the issues/PRs/docs you link to and haven't seen an obvious answer here. I'll look into it and get back to you soon.

**Comment by patrick-rodgers** [comment]
Thanks!

**Comment by jo-arroyo** [comment]
@patrick-rodgers Are you able to access login.microsoftonline.com/consumers with those configurations?

**Comment by patrick-rodgers** [comment]
Hi @jo-arroyo - Thanks! Gave it a try this morning and am a step further, but got this now. Do you have a link on how to get my app enabled for consumer? 

_unauthorized_client: The client does not exist or is not enabled for consumers. If you are the application developer, configure a new application through the App Registrations in the Azure Portal at https://go.microsoft.com/fwlink/?linkid=2083908._

Edit: Is this setting only available when you first create the application? I see it on the create new app screen, but there is nothing similar for existing apps - is there a way to update existing apps to support commercial accounts?

**Comment by hectormmg** [comment]
@patrick-rodgers you can try updating the supported account type property in your app registration manifest.

Assuming you want AAD + MSA consumer accounts:

```
"signInAudience": "AzureADandPersonalMicrosoftAccount",
```

Or if you just want to support /consumer (MSA):

```
"signInAudience": "PersonalMicrosoftAccount",
```
Is that what you're looking for?

**Comment by patrick-rodgers** [comment]
Hmm, I got the below error, guessing this choice isn't in the UI due to some conditions in the back end - switching probably isn't supported. All good. I am going to create a new registration to test. Thanks for your help!

```
Failed to update PickerTestingApp application. Error detail: Property accessTokenAcceptedVersion is invalid. [BjnAFCjLYGl0+Sr0bFlWBc]
```

**Comment by matthiaskopeinigg** [comment]
> Hmm, I got the below error, guessing this choice isn't in the UI due to some conditions in the back end - switching probably isn't supported. All good. I am going to create a new registration to test. Thanks for your help!
> 
> ```
> Failed to update PickerTestingApp application. Error detail: Property accessTokenAcceptedVersion is invalid. [BjnAFCjLYGl0+Sr0bFlWBc]
> ```

How did you resolve it?
