### ISSUE TITLE
Obtain app roles client-side for multiple resources

### ISSUE THREAD

**Issue by ukaaa** [AzureAD/microsoft-authentication-library-for-js#4526]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.22.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

**Use case**
I have a frontend SPA which uses multiple backend APIs. Each API has an app registration and some app roles defined. I would like to conditionally render UI elements based on the roles a user has for these individual resources.
E.g. When a user does not have a "Something.Create" role, I would disable/hide a button labeled "Create new something".

I understand access tokens have these roles, and an access token is meant to be validated by a backend. But I would like to read them _before_ making an API call to that backend.

**Options**
1. Get an access token for the specific resource, and then use [jsonwebtoken](https://www.npmjs.com/package/jsonwebtoken) to decode it and get the values of `roles`. I tried this and it works.
2. Use the Microsoft Graph API to [list appRoleAssignments](https://docs.microsoft.com/en-us/graph/api/user-list-approleassignments). I tried it but it doesn't seem to find appRoleAssigments for all of my resources. Additionally, it returns items with just an `appRoleId`. I would prefer to use a human-readable name such as "Something.Create".
3. … ?

**Question**
What would be the recommended approach?

### Source

External (Customer)

**Comment by ukaaa** [comment]
Any suggestions? Is the approach of using `jsonwebtoken` acceptable? I find it strange that there is no clean way of obtaining a user's roles using the MSAL library. I can't be the first one wanting to adapt a UI based on the roles a user has.

**Comment by timtucker-dte** [comment]
was looking to see if there were tags for this as well and disappointed not to see them -- looks like I'll be heading down the jsonwebtoken approach as well.

**Comment by jo-arroyo** [comment]
@ukaaa We generally don't recommend opening up access tokens to get the roles. User roles should also be found on an id token (see docs [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens)), and MSAL populates `idTokenClaims` on the `AccountInfo` object with these roles. Please see [this doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/docs/Accounts.md) for information on the `AccountInfo` object, and [this doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/accounts.md) for setting and getting the active account.

For resource-specific roles on an access token, our recommendation would be to use the Microsoft Graph APIs instead of opening the access token.

**Comment by ukaaa** [comment]
> @ukaaa We generally don't recommend opening up access tokens to get the roles. User roles should also be found on an id token (see docs [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens)), and MSAL populates `idTokenClaims` on the `AccountInfo` object with these roles. Please see [this doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/docs/Accounts.md) for information on the `AccountInfo` object, and [this doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/accounts.md) for setting and getting the active account.
> 
> 
> 
> For resource-specific roles on an access token, our recommendation would be to use the Microsoft Graph APIs instead of opening the access token. 

Hi @jo-arroyo 

Thanks for the input. I've tried using the Graph API but as stated above I was only able to get the assigned app roles for _some_ of the app registrations but not all of them. Some of the app registrations simply didn't show up. On the other hand, when I retrieve and parse access tokens with `jsonwebtoken` the roles are there.

**Comment by ukaaa** [comment]
Hi @jo-arroyo 
I just discovered I can in fact [list appRoleAssignments](https://docs.microsoft.com/en-us/graph/api/user-list-approleassignments) for _all_ app registrations. I was incorrectly filtering the results. I had the pass the resource ID of the resource in enterprize applications, instead of the ID of the app registration.

Now my next question would be, how can I retrieve the human-readable name for the app role, when I have `appRoleId`. Can this only be done by calling `/applications/{id}` when you have permissions to this application? Thank you.

**Comment by pkanher617** [comment]
You should be able to retrieve `displayName` the same way the `appRoleId` is found [here](https://docs.microsoft.com/en-us/answers/questions/110903/how-to-get-app-role-id.html).

**Comment by nicholashendrickx-tomtom** [comment]
> You should be able to retrieve `displayName` the same way the `appRoleId` is found [here](https://docs.microsoft.com/en-us/answers/questions/110903/how-to-get-app-role-id.html).

I've tried calling `https://graph.microsoft.com/v1.0/applications?$select=displayName, appId, appRoles&$filter=startswith(displayName, 'App-Name')` but I get a status 403 stating "Insufficient privileges to complete the operation."

I pass the access token I use for other Graph API calls. The one for my client. But no luck.

**Comment by ukaaa** [comment]
> You should be able to retrieve `displayName` the same way the `appRoleId` is found [here](https://docs.microsoft.com/en-us/answers/questions/110903/how-to-get-app-role-id.html).

I've tried calling `https://graph.microsoft.com/v1.0/applications?$select=displayName, appId, appRoles&$filter=startswith(displayName, 'App-Name')` but I get a status 403 stating "Insufficient privileges to complete the operation."

I pass the access token I use for other Graph API calls. The one for my client. But no luck.

**Comment by pkanher617** [comment]
> but I get a status 403 stating "Insufficient privileges to complete the operation."

This means the scope you are using for the access token does not have the correct scope for the graph operation. You can try using the `/.default` scope. Since these are application level permissions, you will have to grant admin consent for these scopes in the portal. Please review the linked docs again as there are samples linked that should have the scopes used for this endpoint.
