### ISSUE TITLE
If Azure is down, will it use the cache automatically? My SPA is clearing local and session storage

### ISSUE THREAD

**Issue by relief12** [AzureAD/microsoft-authentication-library-for-js#4527]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.19.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.5

### Description

I have a SPA. Every time the user signs off or closes the app we are clearing the local and session storage. I read that if for any reason Azure is down and unavailable, and we can't reach their API for login, then Azure will check the cache to see if the user has previously logged in, if so, it will use that token to let the user use the app. Will our current process of clearing out local and session storage interfere with that particular scenario where Azure is down? We just want to cover all possible success and failure scenarios. Thanks

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by hectormmg** [comment]
@relief12 yes, clearing local/session storage will remove MSAL tokens from the cache, meaning that when MSAL attempts to retrieve a token silently, it will not be able to and the user will have to re-authenticate in order to acquire more tokens.

**Comment by relief12** [comment]
@hectormmg thanks for the reply. So if for some reason Azure is offline, then the users won’t be able to use my app because they can’t log in? I had the understanding that in that scenario Azure/MSAL would automatically check if the user has cached credentials/token and use that for the log in process. So then if we are clearing out the cache, the Azure backup plan won’t work, is that correct?

**Comment by hectormmg** [comment]
Right, if the authorization service were to come offline, the user may be able to keep using their cached tokens for as long as they are valid (assuming the validation service that the resource server uses isn't also down).

However, if the user signs out from your app, the correct behavior would be to clear the cache and require them to log in again the next time. If the authorization service happens to be down the next time they try to log in, there is nothing that can be done to authenticate them.

Now, if they don't actively logout (i.e. you want to keep their session alive even if they close the app), then you simply don't reset the cache and the next time they open the app, MSAL will be able to access the tokens in the browser cache. The only time when they wouldn't be able to access the token-protected resources would be when the tokens expire, and the authorization service happens to be offline.

**Comment by relief12** [comment]
@hectormmg Thank you!
