### ISSUE TITLE
State Missmatch Error

### ISSUE THREAD

**Issue by GhaithZamrik** [AzureAD/microsoft-authentication-library-for-js#453]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version 69
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [x] Safari version 11.1.2

## Library version

<pre><code>
Library version: 0.2.3

## Current behavior

After the token has expired the user is unable to log in again to the application and Azure returns an error of State Missmatch

## Expected behavior
Users are able to login successfully after the token has expired

</code></pre>

## Minimal reproduction of the problem with instructions

I am using MSAL 0.2.3 to login the users on the client side and I am using the `localStorage` instead of the `sessionStorage`; the issue that I am facing is the following:
After the user has logged in successfully to their account and then after 60 min, when the token has expired, I delete the 'msal.idtoken' from the localStorage. 
Then the user tried to login after the token has expired, they go through the login flow and then MSAL returns an error of a State Missmatch.

Even if I don't remove the token myself after it expires, and just call the logout function on token expire, I still get the same error

here's my Auth class: 

<pre><code>
class Auth {
  constructor(config) {
    this.config = config
    this.isDev = process.env.NODE_ENV === 'development' ? true : false
    this.logger = new Msal.Logger(
      (logLevel, message) => {
        if (this.isDev && this.config.DEV_LOGS) {
          console.log(logLevel, 'logLevel')
          console.log(message, 'message')
        }
      },
      {
        level: Msal.LogLevel.Verbose,
      }
    )
    this.clientApplication = new UserAgentApplication(
      this.config.AZURE_ID,
      this.config.LOGIN_AUTHORITY,
      (errorDesc, token, error, tokenType, state) => {
        if (this.isDev && config.DEV_LOGS) {
          console.log(token, 'token')
          console.log(error, 'error')
          console.log(errorDesc, 'errorDesc')
          console.log(tokenType, 'tokenType')
          console.log(state, 'state')
        }
        if (error) {
          const err = { type: error, message: errorDesc }
          console.log(err)
        }
        if (errorDesc && errorDesc.indexOf('AADB2C90118') > -1) {
          this.clientApplication = new UserAgentApplication(
            this.config.AZURE_ID,
            this.config.PASSWORD_RESET_AUTHORITY,
            this.authCallback,
            {
              redirectUri: this.config.REDIRECT_URL,
              cacheLocation: 'localStorage',
              navigateToLoginRequestUrl: false,
              validateAuthority: false,
              storeAuthStateInCookie: true,
            }
          )
          this.login()
        } else if (
          errorDesc &&
          errorDesc.indexOf('AADB2C90091') > -1 &&
          this.getUser() &&
          this.getUser().tfp === this.config.PASSWORD_RESET_POLICY
        ) {
          this.logout()
        }
      },
      {
        redirectUri: this.config.REDIRECT_URL,
        cacheLocation: 'localStorage',
        logger: this.logger,
        validateAuthority: false,
        navigateToLoginRequestUrl: false,
        storeAuthStateInCookie: true,
      }
    )
  }

  login() {
    window.localStorage.setItem(
      'origin',
      window.location.pathname + window.location.search
    )
    this.clientApplication.loginRedirect([this.config.B2C_SCOPES], 'mkt=de')
  }

  logout() {
    window.localStorage.removeItem('msal.idtoken')
    this.clientApplication.logout()
  }

  get profileUrl() {
    if (this.getUser()) {
      return `https://${this.config.TENANT_URL}.b2clogin.com/${this.config.TENANT_URL}.onmicrosoft.com/oauth2/v2.0/authorize?client_id=${
        this.config.AZURE_ID
      }&response_type=token&redirect_uri=${
        this.config.REDIRECT_URL
      }&response_mode=fragment&scope=${
        this.config.B2C_SCOPES
      }%20openid%20profile&nonce=${this.getUser().nonce}&p=${
        this.config.PROFILE_POLICY
      }&mkt=de`
    } else {
      return ''
    }
  }

  getToken() {
    const token = window.localStorage.getItem('msal.idtoken')
    return token
  }

  getUser() {
    return this.getTokenDecoded()
  }

  getTokenDecoded() {
    return this.getToken() ? jwtDecode(this.getToken()) : undefined
  }

  authCallback(errorDesc, token, error, tokenType) {
    if (this.isDev) {
      console.log(token, 'token')
      console.log(error, 'error')
      console.log(errorDesc, 'errorDesc')
      console.log(tokenType, 'tokenType')
    }
    if (error) {
      const err = { type: error, message: errorDesc }
      console.log(err)
    }
  }

  loginAfterPasswordRest() {
    this.clientApplication.authority = this.config.LOGIN_AUTHORITY
    this.clientApplication.loginRedirect(
      [this.config.B2C_SCOPES],
      `login_hint=${encodeURIComponent(this.getUser().emails[0])}&'mkt=de'`
    )
  }
</code></pre>

**Comment by navyasric** [comment]
@GhaithZamrik Are you still having this issue? If not can you post your resolution or how you fixed it?

**Comment by sameerag** [comment]
Closing this issue as there is no response from the user. 
Please reopen if the issue persists with clear repro steps.
