### ISSUE TITLE
Change type of `idTokenClaims` for direct access

### ISSUE THREAD

**Issue by svrooij** [AzureAD/microsoft-authentication-library-for-js#4538]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Description

If the `idTokenClaims` are set on an account, it's recognized as an `object`. This means you cannot access it's members (`roles doesn't exist on object`). With the following work-around I'm able to access the properties in the identity token.

```js
// Doesn't work
const roles = account.idTokenClaims.roles;
// or
const roles2 = account.idTokenClaims['roles'];
// this does work
const claims = account.idTokenClaims as { [key: string]: any };
const roles3 = claims.roles;
// and this does also work:
const roles4 = claims['roles'];
```

The type `{ [key: string]: any }` is valid for each json document, and since the idTokenClaims are always represented as json, this would be a better description, and allow access to all the claims without manually changing the type. It would also support future claims that are not known yet.

An alternative would be to create something like this, but that requires more maintenance:

```js
declare type IdentityToken {
  aud?: string;
  exp?: number;
  iss?: string;
  name?: string;
  roles?: string[];
}

// Or supporting both methods
declare type IdentityTokenExtension  = IdentityToken & {  [key: string]: any; }
```

### Source

External (Customer)

**Comment by ClumsyPenguin** [comment]
Yes, i kinda also want to get rid of the dynamic objects, since i need to get access to role exp date of the token and it roles. 
I don't like writing something like this.

```ts
accounts[0].idTokenClaims["exp"]
```

**Comment by svrooij** [comment]
@tnorling or @jasonnutter what do you guys think of my idea? And would you go for the complete type or for the open `{  [key: string]: any; }` way?

**Comment by jasonnutter** [comment]
@svrooij We'll take it into consideration and follow up, thanks!

**Comment by svrooij** [comment]
Want me to create a pr for this?

**Comment by jasonnutter** [comment]
@svrooij You're welcome to open a PR, yes.

**Comment by sameerag** [comment]
@svrooij Can you please check if all tests pass and we can consider merging it?

**Comment by svrooij** [comment]
@sameerag all tests are checked in the PR and are still green
