### ISSUE TITLE
Does msal-react, msal-common, msal-browser support client credentials Flow "acquireTokenByClientCredential" for automation testing ?

### ISSUE THREAD

**Issue by 2strokes** [AzureAD/microsoft-authentication-library-for-js#4539]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.22.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.1.2

### Description

Does msal-react, msal-browser, support Client Credentials Flow "acquireTokenByClientCredential"  for automation testing ?

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@2strokes msal-browser and msal-react only supports the Auth Code Flow, and not the Client Credential Flow. If you are wanting to load tokens for testing purposes, you could use our `loadExternalTokens` API, detailed in this doc [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/testing.md).

**Comment by 2strokes** [comment]
@jo-arroyo Thank you for your quick response. In order to use loadExternalTokens, do I need to have a valid test user account set up in azure ?
Also, acquireTokenSilent() causes interaction Auth error because no refresh token is present.

**Comment by kandeeb1** [comment]
@jo-arroyo  Could you please help me with mentioned questions?

**Comment by 2strokes** [comment]
@jo-arroyo @hectormmg Could you please help me with the above mentioned questions. Appreciate your help !!

**Comment by pkanher617** [comment]
>  In order to use loadExternalTokens, do I need to have a valid test user account set up in azure ?

You will need to use the same account as the external tokens you are loading. 

> Also, acquireTokenSilent() causes interaction Auth error because no refresh token is present.

This is most likely because the scopes or account provided does not match the account used to load the tokens. Make sure that the IDs being passed in match the IDs in the cache/token you are loading using `loadExternalTokens`.

**Comment by 2strokes** [comment]
@pkanher617 Appreciate your help !! I am trying to use username password grant flow and loading the same external tokens (using loadExternalTokens) for automation. But stuck with an error "The request body must contain the following parameter: 'client_assertion' or 'client_secret'.  And this happens when MSAL tries to acquire a token.

**Comment by samuelkubai** [comment]
Hi @2strokes,

Could you share more information on the setup you have for acquiring tokens through the username and password flow?
To help us, help you debug that error, as it is often a configuration issue.
