### ISSUE TITLE
Cookie msal.state.login redirection issue

### ISSUE THREAD

**Issue by adamtay** [AzureAD/microsoft-authentication-library-for-js#454]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:

</code></pre>

## Browser:
- [x] Chrome version 69.0.3497.100
- [x] Firefox version 62.0.3
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

Library version: 0.2.3

## Current behavior

We have a public `/sign-up` route and an authenticated `/` route.
Once a user has signed up and authenticated via the `/sign-up` route, `msal.state.login` is stored as a cookie containing the value `https://website.com/sign-up`. Following authentication, we redirect the user to the authenticated `/` route.

On the authenticated `/` route, we allow users to change their password via the built-in `password reset policy`. However, upon the user changing their password, they are redirected to the `msal.state.login` cookie value `https://website.com/sign-up` where it should instead redirect back to `https://website.com/`

## Expected behavior

User should be redirected to the previous page prior to triggering B2C login flow rather than the `msal.state.login` value.

## Minimal reproduction of the problem with instructions

Msal.UserAgentApplication configured with `storeAuthStateInCookie` as true.

**Comment by adamtay** [comment]
Additionally, if a user is authenticated and has triggered the 'password reset policy', msal will subsequently sign the user out. How can we keep the user signed in should they decide to click on CANCEL and not change their password?

The crux of our issue is that we need to allow our end users to change their password. At this time, we are unable to leverage custom policies or graph api and would prefer to keep scope to in-built policies/functionality.

**Comment by navyasric** [comment]
@adamtay Please try the latest msal.js v0.2.4 to see if it resolves the issue with being signed out. 
For the redirect to the starting page (in this case /sign-up), MSAL.js has a configuration option `navigateToLoginRequestUrl` which is set to true by default. Setting it to false gives the ability to turn off default navigation to start page after login. Please try and let us know if this is resolved?

**Comment by navyasric** [comment]
The issue with signing out between policies is related to #440

**Comment by silver-stack** [comment]
Hello, I believe that I have a related issue that I just cannot seem to get to work (unless I am misunderstanding the option 'navigateToLoginRequestUrl').

We have an app that users can sign up and sign into and everything works fine, except for one feature.  One of our back end processes sends email notifications to the users that contain a deep link to a specific record and page within the app (fairly common functionality).

If the user is not already signed in, they click the deep link, get presented with the login and then get navigated to the redirect_uri (which is the home page) that is specified within our B2C portal.  Ideally, I would like them to get navigated through to the original deep link after successful login.

I have set the navigateToLoginRequestUrl to false, however this appears to make no difference.

Example from my app.module

`    MsalModule.forRoot({
      clientID: environment.azureConfig.clientId,
      authority: environment.azureConfig.authority,
      redirectUri: environment.azureConfig.redirectUri,
      cacheLocation : 'localStorage',
      popUp: false,
      logger: loggerCallback,
      level: LogLevel.Verbose,
      consentScopes: environment.azureConfig.scope,
      protectedResourceMap: protectedResourceMap,
      navigateToLoginRequestUrl: environment.azureConfig.navigateToLoginRequestUrl
  }),`
Any ideas on why this might not be working?

**Comment by sameerag** [comment]
Tracking this with #440. @adamtay Please reopen if the "navigateToLoginRequestUrl" suggested above did not help your case.

We also upgraded our library to 1.0.x with a better API surfacing, please try the newer version if that is an option. Most of our dev work is focused on the later releases.
