### ISSUE TITLE
@azure/msal-browser and @azure/msal-common are huge dependencies

### ISSUE THREAD

**Issue by NateRadebaugh** [AzureAD/microsoft-authentication-library-for-js#4543]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.22.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.1.1

### Description

I'm using this library in my angular app but the documented steps result in a `230+ KB` increase of bundle size.

<img width="541" alt="image" src="https://user-images.githubusercontent.com/130445/155634779-7dccb216-a9c0-4253-8668-c5e3c253795c.png">

### MSAL Configuration

```javascript
auth: {
    clientId: environment.B2C_ClientId,
    authority: b2cPolicies.authorities.SignUpIn.authority,
    redirectUri: environment.B2C_RedirectURL,
    knownAuthorities: [environment.B2C_AuthorityDomain],
    postLogoutRedirectUri: environment.B2C_PostLogoutRedirectURL
},
cache: {
    cacheLocation: BrowserCacheLocation.LocalStorage,
    storeAuthStateInCookie: isIE
},
```

### Relevant Code Snippets

```javascript
import { MsalGuard } from '@azure/msal-angular';

import {
  MsalBroadcastService,
  MsalGuard,
  MsalGuardConfiguration,
  MsalModule,
  MsalRedirectComponent,
  MsalService,
  MSAL_GUARD_CONFIG,
  MSAL_INSTANCE,
} from '@azure/msal-angular';
import {
  InteractionType,
  IPublicClientApplication,
  PublicClientApplication,
} from '@azure/msal-browser';

import { LogLevel, Configuration, BrowserCacheLocation } from '@azure/msal-browser';

import { MsalBroadcastService, MsalGuardConfiguration, MsalService, MSAL_GUARD_CONFIG } from '@azure/msal-angular';
import { AccountInfo, InteractionStatus } from '@azure/msal-browser';

export const loginRequest = {
  scopes: [] as string[]
}

export function MSALInstanceFactory(): IPublicClientApplication {
  return new PublicClientApplication(msalConfig);
}

export function MSALGuardConfigFactory(): MsalGuardConfiguration {
  return {
    interactionType: InteractionType.Redirect,
    authRequest: loginRequest,
  };
}

@NgModule({
  declarations: [AppComponent],
  imports: [
    CommonModule,
    AppRoutingModule,
    RouterModule,
    BrowserModule,
    HttpClientModule,
    BrowserAnimationsModule,
    //...
  ],
  providers: [
    MsalModule,
    MsalService,
    MsalGuard,
    MsalBroadcastService,
    //...
    {
      provide: MSAL_INSTANCE,
      useFactory: MSALInstanceFactory,
    },
    {
      provide: MSAL_GUARD_CONFIG,
      useFactory: MSALGuardConfigFactory,
    },
    // {
    //   provide: MSAL_INTERCEPTOR_CONFIG,
    //   useFactory: MSALInterceptorConfigFactory
    // },

  ],
  bootstrap: [AppComponent, MsalRedirectComponent],
})
```

### Reproduction Steps

Follow documented instructions on integrating with Azure B2C with Angular app

### Expected Behavior

Unused features should not show up in my bundles. A simple redirect application should not be over half the size of the entire angular framework.

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

None (Server)

### Source

External (Customer)

**Comment by pkanher617** [comment]
@NateRadebaugh We appreciate the feedback! For the most part the modules that are included in the MSAL package are required files. There is a bit more involved than just redirecting, but you are correct that you shouldn't be required to package every feature as part of this if you only need basic token acquisition through a redirect. We are exploring ways to make this package easier to perform tree-shaking on or remove features that aren't required, but this is something that will most likely come in a major version release.

**Comment by yann-combarnous** [comment]
Package size has increased by 45% since this issue was raised.

<img width="784" alt="Screenshot 2023-02-21 at 12 30 40" src="https://user-images.githubusercontent.com/39089766/220333795-afd02b28-1939-445d-93e7-fe925a357b93.png">

**Comment by billyjov** [comment]
@pkanher617 Any progress on this issue?
