### ISSUE TITLE
Single Logout Using iFrame X-Frame-Options Deny

### ISSUE THREAD

**Issue by BobJeronowitz** [AzureAD/microsoft-authentication-library-for-js#4545]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.17.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.1.1

### Description

There are 2 applications sharing SSO,  Logout using Single Logout (SLO)
- Asp.Net / AngularJs application
- Angular v12 SPA

User logs into 1 application and is logged in to both and SLO logs each user out of both applicaions as long as it is in a browser that doesn't enforce cross-site scripting security in an iFrame.  When using Chrome Incognito, Firefox or Safari SLO is prevented in the SPA because x-frame-options = deny.  Is there a way to set this up that the iframe can accept the call via a pre-established iframe with the source set to the B2C URL?  Using logoutPopup because it is also prevented in the browser.  The .Net application works fine because the front-channel logout URL is an endpoint that terminates the session.

![image](https://user-images.githubusercontent.com/30864875/155806767-753c0a5f-c133-45af-ac3c-20cedd711e6c.png)

### MSAL Configuration

```javascript
auth: {
    clientId: config.B2C_ClientId,
    authority: config.authorities.SignUpIn.authority,
    redirectUri: config.B2C_RedirectURL,
    knownAuthorities: [ config.B2C_AuthorityDomain ]
},
cache: {
    cacheLocation: BrowserCacheLocation.LocalStorage,
    storeAuthStateInCookie: false
},
```

### Relevant Code Snippets

```javascript
// Logout is using Single Logout / Popup not possible as it is prevented by browser
 this.msalInstance.logoutRedirect({
        // If in iframe, skip redirect to Azure B2C
        onRedirectNavigate: () => {
          return !BrowserUtils.isInIframe();
        },
      })
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by pkanher617** [comment]
> Using logoutPopup because it is also prevented in the browser.

Bit confused here, did this mean to say "NOT using..."?

This is probably something that the B2C team will need to help with, as front-channel logout is handled by the B2C service. The page that is throwing the "X-Frame-Options Deny" error is the B2C logout page rendered inside of the iframe.

Please file a support ticket with the B2C team by following the instructions here: https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options

They can help you out further, they may ask for a public repro link or additional data. You can also link this Github issue in the support request.

**Comment by bobjeronowitz-gs1us** [comment]
Thanks, Prithvi.  Yes, NOT using logoutPopup.  I will create an issue with the B2C team to see if they can help with getting the script to operate in the iframe.
