### ISSUE TITLE
[QUESTION] What is the Authorize param mscrid for?

### ISSUE THREAD

**Issue by luismanez** [AzureAD/microsoft-authentication-library-for-js#4548]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

1.4.12

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

I´ve been involved in this interesting issue related to SharePoint framework, msal.js and MS Edge Canary:
https://github.com/SharePoint/sp-dev-docs/issues/7711

Luckily, seems finally solved, and, although I´m not sure about the cause and final resolution, what I can see using Fiddler, is that before the fix, there were a call to the AAD Authorize endpoint passing the parameter __mscrid__ (which seems just a generated GUID), and now, the call is not sending that parameter.

Sample of a failed call:

```
			https://login.microsoftonline.com/tenant/oauth2/v2.0/authorize
				?response_type=id_token+token
				&scope=https://graph.microsoft.com/.default+openid+profile
				&client_id=
				&redirect_uri=https://tenant.sharepoint.com/_forms/spfxsinglesignon.aspx				 
                                &state=eyJpZCI6Ij...
				&nonce=b66e4684-938c-4de4-bc97-92a88fad4ce2
				&client_info=1
				&x-client-SKU=MSAL.JS
				&x-client-Ver=1.4.12
				&sid=6ef565b8-0012-4125-a3a0-e67f107dddfb
				&client-request-id=99631934-bfc0-4cf5-9a21-25140b845466
				&prompt=none
				&response_mode=fragment
				&sso_nonce=AwAB...
				&mscrid=99631934-bfc0-4cf5-9a21-25140b845466	
```

I can´t add more information (as I say, I don´t know the cause and final fix), but I guess someone from the SDK team, should know what´s that _mscrid_ param for, as is not officially documented.

Many thanks!

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by pkanher617** [comment]
@luismanez Thanks for opening this and bringing this to our attention. It doesn't appear that the `mscrid` parameter is something that would have affected this - this param is most likely being added by Windows or Edge, and the original issue appears to be fixed in Edge, looking at the linked issue. We will keep this in mind for any future cases that come up!

**Comment by luismanez** [comment]
Thanks for the comment @pkanher617. Yeah, issue has been fixed by the Edge team, I was just so curious to know what´s that param for. Would be good to see if someone in the AAD team know the answer :). Anyway, closing this issue, as is not _msal.js_ using that parameter for anything.
Thanks again!
