### ISSUE TITLE
Infinite loop while making api calls

### ISSUE THREAD

**Issue by cajutemdesign** [AzureAD/microsoft-authentication-library-for-js#4549]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.0.4

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.4

### Description

After authentication, I am getting an infinite loop on any subsequent api calls I make while using msal as a custom interceptor. I am not sure what I am doing wrong

### MSAL Configuration

```javascript
{
auth: {
      clientId: '319a98fe-6e49-481e-8049-4cb036a6362f',
      authority: 'https://thriiivb2c.b2clogin.com/thriiivb2c.onmicrosoft.com/B2C_1_User_SignIn',
      knownAuthorities: ['thriiivb2c.b2clogin.com'],
      redirectUri: environment.redirectUri
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE // set to true for IE 11. Remove this line to use Angular Universal
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Info,
        piiLoggingEnabled: false
      }
    }
}
```

### Identity Provider

Azure B2C Basic Policy

### Source

Internal (Microsoft)

**Comment by pkanher617** [comment]
Need more info - redirect loop?
