### ISSUE TITLE
Intermittent MSAL Browser Auth Error: hash empty

### ISSUE THREAD

**Issue by yrosenberg-hj** [AzureAD/microsoft-authentication-library-for-js#4550]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.16.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.2

### Description

Intermittently getting a error when sending a request to authenticate user.

### Error Message

![image](https://user-images.githubusercontent.com/100439885/156042960-255822e0-f5e1-4be8-9850-fa4429384ba8.png)

### MSAL Configuration

```javascript
auth: {
    
      clientId: clientId,
      authority: "https://login.microsoftonline.com/organizations",
      postLogoutRedirectUri:postLogoutRedirectUri2,
      redirectUri: redirectUri,
      
    },
```

### Relevant Code Snippets

```javascript
providers: [
    {
      provide: MSAL_INSTANCE,
      useFactory: MSALInstanceFactory
    }, 
      MsalService,
      MsalGuard,
      {
        provide:HTTP_INTERCEPTORS,
        useClass: MsalInterceptor,
        multi: true
      }, {
        provide: MSAL_INTERCEPTOR_CONFIG,
        useFactory: MSALInterceptorConfigFactory
      }
    
  ],
  bootstrap: [AppComponent]
})


loginPop(){
   this.msalService.loginPopup().subscribe( (response:AuthenticationResult) => {
     this.msalService.instance.setActiveAccount(response.account);
 

     if (!this.validateTenant(response.tenantId)){
      this.logout();
      throw alert("Invalid registration")
    };
    
      
  
   
    
  if (this.isLoggedIn()){
     const user = this.formatUser(response.account);
       this.validateUser(user);
      
     //  console.log("logged In")

    } 
   
   }, ((error: any) => {
     alert("Error: Microsoft could not confirm your account please try to log in again.")
     console.log(error)
   }))

 
 }
```

### Reproduction Steps

Authenticate with the code snippets.

### Expected Behavior

Authenticates user when user is a microsoft organization account holder.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge, Safari, Internet Explorer

### Source

External (Customer)

**Comment by pkanher617** [comment]
@yrosenberg-hj Could you try updating your packages to the latest versions? That would be `2.22.0` for `@azure/msal-browser` and `2.1.1` for `@azure/msal-angular`.

There have been [multiple updates](https://github.com/AzureAD/microsoft-authentication-library-for-js/releases?expanded=true&page=1&q=browser) addressing redirect handling in the versions since the one you provided, and may fix the issues you are having.

**Comment by yrosenberg-hj** [comment]
Thank you for the response. Unfortunately, the issue persists even after updating to the the latest versions.

**Comment by HichamBenjelloun** [comment]
@yrosenberg-hj I had the same issue recently and solved it by setting the `redirectUri` to a blank page as suggested in the documentation : https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/login-user.md#redirecturi-considerations

Similar issue: #4456

**Comment by yrosenberg-hj** [comment]
> @yrosenberg-hj I had the same issue recently and solved it by setting the `redirectUri` to a blank page as suggested in the documentation : https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/login-user.md#redirecturi-considerations
> 
> Similar issue: #4456

Thank You! It looks like the issue is resolved!
