### ISSUE TITLE
Logout redirecting 3 or more times

### ISSUE THREAD

**Issue by DerekJDev** [AzureAD/microsoft-authentication-library-for-js#4551]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.21.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.1.0

### Description

When I call the msalService.logoutRedirect({ postLogoutRedirectUrl: ..appurl }) the msal library goes between the Azure B2C logout route and my app 3 or more times before finally routing to the login screen. I know this redirect needs to happen at least once based on B2C's current functionality. I verified that when I call the logout function that localStorage is getting cleared out with all the Azure B2C token information. Also I'm using the MSAL redirect component, and I have it in my index.html file.

### MSAL Configuration

```javascript
{
    auth: {
      clientId: environment.clientIdMS, // This is your client ID
      authority: environment.authorityMS, // This is your tenant ID
      knownAuthorities: [B2C Tenant],
      redirectUri: environment.redirectUriMS // This is your redirect URI
    },
    cache: {
      cacheLocation: 'localStorage',
      storeAuthStateInCookie: isIE, // Set to true for Internet Explorer 11
    },
    system: {
       loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Info,
        piiLoggingEnabled: false
      }
    }
  }
```

### Relevant Code Snippets

```javascript
// Guard config
{
    interactionType: InteractionType.Redirect,
    authRequest: {
      scopes: ['openid', 'profile',
        API Scope],
      extraQueryParameters: {
        test: 'test'
      }
    }
  }

// Listener to check if user is logged in
this.msalBroadcast.inProgress$
      .pipe(
        filter((status: InteractionStatus) => status === InteractionStatus.None),
        takeUntil(this._destroying$)
      )
      .subscribe((result) => {
        // const payload = result.payload as AuthenticationResult;
        this.loggedIn = this.msalService.instance.getAllAccounts().length > 0;
        if (this.loggedIn)
          this.checkAccount();
      });

// Logout function
this.msalService.logoutRedirect({
    postLogoutRedirectUri: environment.redirectUriMS,
    account: this.msalService.instance.getActiveAccount() // I've tried it with and without this line
});
```

### Reproduction Steps

1. Call the logoutRedirect call

### Expected Behavior

To be redirected once and then back to the login page

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer

### Source

External (Customer)

**Comment by pkanher617** [comment]
@DerekJDev This commonly happens when the postLogoutRedirectUri page is the same as the redirectUri. Could you ensure that the page you redirect to after logout is not invoking the logout API again?

**Comment by DerekJDev** [comment]
@pkanher617 I had is set to the same thing... I switched the postLogoutRedirectUri to a route that is not protected by the MsalGuard and that you can access with being authenticated, but now it's just stuck in a loop of redirecting back and forth. Besides msalService.logoutRedirect(...) and the MsalGuard, what would be invoking the logout API?

For reference, my **redirectUri** is **http://localhost:4200/** and my **postLogoutRedirectUri** is **http://localhost:4200/unauthorized**

**Comment by DerekJDev** [comment]
Any update on this?

**Comment by pkanher617** [comment]
Apologies for not reviewing this earlier. Is the `postLogoutRedirectUri` calling logout somewhere? Is that why this is redirecting multiple times? If you can send a Fiddler trace to my email in my profile, I can review the trace to see if there are any unexpected issues.

**Comment by DerekJDev** [comment]
@pkanher617 I will send that trace over. Also, here's my code to show how the `postLogoutRedirectUri` is routed to:

app-routing.module.ts
```
import { PagesModule } from './framework/pages/pages.module';
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { DefaultLayoutComponent } from '@framework/pages/default-layout';
import { UnauthorizedComponent } from './framework/pages/unauthorized/unauthorized.component';

const routes: Routes = [
  {
    path: '',
    component: DefaultLayoutComponent,
    loadChildren: () => import('./features/features.module').then(mod => mod.FeaturesModule),
  },
  { path: 'unauthorized', component: UnauthorizedComponent, data: { title: 'Unauthorized' } },
  // 404 Not found
  { path: '**', redirectTo: '404' }
];

@NgModule({
  imports: [
    PagesModule,
    RouterModule.forRoot(routes, {
      initialNavigation: 'enabled'
    }),
  ],
  exports: [RouterModule]
})
export class AppRoutingModule { }
```

unauthorized.component.ts
```
import { TvButton } from '@shared/components/elements/button/button.model';
import { Component } from '@angular/core';
import { MsalService } from '@azure/msal-angular';

@Component({
  selector: 'app-dashboard',
  templateUrl: 'unauthorized.component.html',
  providers: []
})
export class UnauthorizedComponent {
  title = 'unauthorized.unauthorized';
  desc = 'unauthorized.unauthorizedDesc';
  loginBtn = new TvButton('button', null, 'tall', 'basic', 'unauthorized.login', null,
  null, true, null, 'primary', false);

  constructor(public msalService: MsalService) { }

  public login() {
    this.msalService.loginRedirect();
  }
}
```

**Comment by pkanher617** [comment]
Hi @DerekJDev could you resend the logs? I don't appear to have them in my email. The code alone doesn't have enough information to help us debug this.

**Comment by DerekJDev** [comment]
Hi @pkanher617, I sent it to the email on your GitHub profile, I just replied to the original message, let me know if you got it. Thanks.

**Comment by DerekJDev** [comment]
@pkanher617 did you get my email?

**Comment by pkanher617** [comment]
Thanks @DerekJDev I got it, reviewing today and will get as soon as I can!

**Comment by DerekJDev** [comment]
Keep open.

**Comment by DerekJDev** [comment]
Hey @pkanher617 sorry for all the checking in, but were you able to find anything in the fiddler trace? Thanks in advance.

**Comment by DerekJDev** [comment]
Comment to keep open and active.

**Comment by DerekJDev** [comment]
Any update on this?

**Comment by DerekJDev** [comment]
@pkanher617  Do I need to provide anything else to debug this?

**Comment by DerekJDev** [comment]
@pkanher617 after updating the package and modifying some settings I was able to get it to work better. It works as it should most of the time, but sometimes it still redirects more than once.

I changed my logout redirect url and redirectUri to: http://localhost:4200. In my app registration, I left the "Front-channel logout URL" empty and I have http://localhost:4200/ as one of the redirect urls.

I'll try to get a fiddler trace when it redirects more than once, but any help would be appreciated.

**Comment by tnorling** [comment]
@DerekJDev I apologize that this fell through the cracks, Prithvi is no longer on the team. Please email me your logs and I will be happy to follow up on this.

**Comment by DerekJDev** [comment]
@tnorling thanks for the response, after making the changes I mentioned above and upgrading to the latest package I haven't been running into the issue. I will close this issue. If run into it in the future, I can reopen this issue and provide logs.
