### ISSUE TITLE
OIDC compatibility

### ISSUE THREAD

**Issue by mharj** [AzureAD/microsoft-authentication-library-for-js#4562]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.22.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.3.0

### Description

Testing msal with other OIDC IDP's and at least Google seem to complains on login about offline_access scope (which I haven't set).
Is there way to prevent offline_access scope or is it just required for library? 

### Error Message

Error 400: invalid_scope
Some requested scopes were invalid. {valid=[openid, https://www.googleapis.com/auth/userinfo.profile, https://www.googleapis.com/auth/userinfo.email], invalid=[offline_access]}

### MSAL Configuration

```javascript
{
		auth: {
			clientId: 'xxxxxxxxxxxx.apps.googleusercontent.com',
			authority: 'https://accounts.google.com/',
			protocolMode: ProtocolMode.OIDC,
			knownAuthorities: ['https://accounts.google.com/'],
		},
		cache: {
			cacheLocation: 'localStorage',
			storeAuthStateInCookie: true,
		},
	}
```

### Relevant Code Snippets

```javascript
export const loginScope = {
	scopes: ['openid', 'profile', 'email'],
};
await msalInstance.loginPopup(loginScope)
```

### Reproduction Steps

trigger login

### Expected Behavior

I mean this is wonderful piece of SW with work with multiple API and different scopes at same time , and I it would be nice to get it working on all OIDC IDP's.

### Identity Provider

Other

### Browsers Affected (Select all that apply)

Edge

### Source

External (Customer)

**Comment by EmLauber** [comment]
We appreciate the feedback. We could investigate this issue, but in general the library is scoped to be optimized for Microsoft as an IDP. There is not yet a commitment that the libraries should support other IDPs so we can't guarantee combability with others. We are open to this feedback though and will monitor for more feedback on MSAL.js supporting non-Microsoft IDPs.

**Comment by mharj** [comment]
@EmLauber yep, I know not all IDP's working same way. We mostly working with AAD environments but sometimes we need to support also other IDP's. Also it would be great it there would be some abstraction we can help to fill parts to do handling for others :)

**Comment by EmLauber** [comment]
@mharj  can can you be more specific by "some abstraction... to fill parts"? We are open to PRs from the community, and it would be great if we knew more specifics of what kind of changes we can make that would help you contribute.

**Comment by mharj** [comment]
@EmLauber I was thinking something like generic Config to be more specific i.e. AzureADConfig class which implements something like getRequestHeaders(), getRequestBody() methods (based from abstract class) which then can be consumed when building payloads, this way we can have also GitHubConfig, BattleNetConfig, etc either build as npm packages by community or even PR those to be on same package.
