### ISSUE TITLE
logoutRedirect() gives --> "Error - Attempted to clear all MSAL cache items and failed. Local cache unchanged."

### ISSUE THREAD

**Issue by mettoware** [AzureAD/microsoft-authentication-library-for-js#4564]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.22.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.1.1

### Description

Everything seems to be working fine, but when you do msalService.logoutRedirect() you will get an error (in Chrome browser console + preserve logs):
**"Error - Attempted to clear all MSAL cache items and failed. Local cache unchanged.".** 

After some research I managed to find out the there it at least a "not a function" exception in CryptoOps.ts when doing databaseStorage.deleteDatabase():

![typeerror](https://user-images.githubusercontent.com/3253430/156345636-418ce3d0-47fb-41ef-bd14-7a405fb63ecf.png)

### Error Message

1. Error - Attempted to clear all MSAL cache items and failed. Local cache unchanged.
2. databaseStorage.deleteDatabase is not a function

### MSAL Configuration

```javascript
auth: {
      clientId: <myappid>,
      authority: `https://login.microsoftonline.com/${<mytenantid>}`,
      redirectUri: '<myredirecturl>',
      postLogoutRedirectUri: '<mylogouturl>',
      navigateToLoginRequestUrl: false
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: false,
    },
    system: {
      loggerOptions: {
          logLevel: LogLevel.Error,
          loggerCallback: (level, message) => {
              console.log(level, message);
          },
          piiLoggingEnabled: false
      }
    }
```

### Relevant Code Snippets

```javascript
msalService.logoutRedirect();
```

### Reproduction Steps

1. Open Chrome developer tools
2. Open console
3. Toggle "preserve logs"
4. msalService.LoginRedirect();
5. msalService.logoutRedirect();
6. See the console output for error.

### Expected Behavior

1. databaseStorage.deleteDatabase() should not cause "is not a function"
2. logoutRedirect() should not cause an error message

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by pkanher617** [comment]
@mettoware We were able to reproduce this and hope to have a PR up to fix this shortly - thanks for bringing this to our attention!

**Comment by PraveenVerma17** [comment]
@pkanher617  is this fixed ?

**Comment by mettoware** [comment]
@pkanher617 Could you estimate when you'll have a fix for this released? The issue labels could also be updated as a confirmed bug.

**Comment by PraveenVerma17** [comment]
@hectormmg when can we expect fix for this, this is causing so much unwanted error logged in my system.  
Kindly fix as early as possible.

**Comment by hectormmg** [comment]
@PraveenVerma17 I'm currently working on a fix for this issue which should come out in the april release barring any complications. This issue should be updated automatically when the PR in question is submitted and merged. Thanks for your patience!
