### ISSUE TITLE
Firefox 31.0 SyntaxError: class is a reserved identifier

### ISSUE THREAD

**Issue by dornellas13** [AzureAD/microsoft-authentication-library-for-js#457]
Hello good night, 
I am using msal for authentication with azure AD in my angular application 6, however I am having problems using the firefox browser version 31.0. I know that this browser is very old and some words are reserved for the same, when trying to access the application in firefox 31.0, I am getting this error **SyntaxError: class is a reserved identifier**, I looked at vendor.js and realized that MSAL classes are not being converted to ECMASCRIPT. Has anyone had this problem? If so, can you help me solve it?

![capturar](https://user-images.githubusercontent.com/12344282/46896115-e84f8b00-ce51-11e8-910b-b71bdd43da8f.PNG)

**Comment by Weschk** [comment]
Looks like the same issue reported in #414 causing IE11 to crash with syntax error.

**Comment by sameerag** [comment]
#414 is now fixed with a potential PR. Also the latest msal release: 1.0.x has AuthResponse.ts as the response class. 

Please check out our [release notes](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL.js-1.0.0-api-release) for more details.
