### ISSUE TITLE
How to specify Interceptor configuration for Static Web App's integrated APIs?

### ISSUE THREAD

**Issue by TLKG** [AzureAD/microsoft-authentication-library-for-js#4584]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.1.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

None

### Description

Followed this [MS Doc for adding API into Static Web App (SWA)](https://docs.microsoft.com/en-us/azure/static-web-apps/add-api?tabs=angular), I'd like to 

- MS account login prompt as a popup.
- add Msal Interceptor to send in token silently without any interaction calling integrated API. 

Is there any detailed document available explaining options and values? For example `popup` vs. `redirect`, how to piggy back adding `hello`: `world` from sessionStorage in addition to token into the header, etc.

### MSAL Configuration

```javascript
@NgModule({
  declarations: [...],
  imports: [..., 
  MsalModule.forRoot
    ( 
        new PublicClientApplication
        (
            {
                // MSal Configuration
                auth: 
                {
                    clientId: '...',   authority: 'https://login.microsoftonline.com/common',  redirectUri: 'http://localhost:4280/'   
                },
                cache: 
                {
                    cacheLocation: 'localStorage', // tried 'sessionStorage' too 
                    storeAuthStateInCookie: false, // using Chrome
                }
            }
        )
        , 
        {
            // MSAL Guard Configuration
            interactionType: InteractionType.Redirect,
            authRequest: {scopes: ['user.read']}
        }, 
        {
            // MSAL Interceptor Configurations
            interactionType: InteractionType.Popup, // .redirect never hits API
            protectedResourceMap: 
            new Map
            ([ 
                ['https://graph.microsoft.com/v1.0/me', ['user.read'] ],
                ['/api/AF1', ['api://custom api consent']]    // get invalid reading
                ['/api/AF1', null]    // hit API but token not in context.req.headers
            ])
        }
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by mpminayo** [comment]
We currently don't have any documentation on using MSAL Angular with Static Web Apps. 
All our docs for using MSAL Angular can be found here: https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-angular/docs/v2-docs

**Comment by mpminayo** [comment]
MSAL interceptor is a convenience function that adds the access token to the authorization header of the request. To add additional things to the header, you may want to write your own interceptor.  

From your configuration, the last entry to your protectedResourceMap has the api and then null. The reason that the token is not in the headers is because null is used to unprotect the resource, so the token would not be attached. More information can be found in the interceptor docs https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/msal-interceptor.md .

**Comment by TLKG** [comment]
@mpminayo Appreciate the info. I'll study the doc and please keep this thread open. Thank you.

**Comment by TLKG** [comment]
Solution:
`['/api/*', ['offline_access']]`
