### ISSUE TITLE
MSAL support for Service Principals

### ISSUE THREAD

**Issue by ss90128311** [AzureAD/microsoft-authentication-library-for-js#4585]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.21.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.2.0

### Description

Is it possible to use a service principal to login to an application using MSAL?

I am trying to write an automated test in cypress to login via a service principal. I need to get a token for the service principal and cache it so that MSAL recognizes a signed in user exists and doesn't redirect me to login, however I still get redirected to login.

Steps:
1. Get token for service principal using client_credentials grant type
2. Insert the token and service principal information into the cache using the loadExternalTokens API
3. Run cypress test, however I get redirected to azure login page. It's as if the cached values are invalid.

### Relevant Code Snippets

```javascript
// Get token
curl -X POST -H 'Content-Type: application/x-www-form-urlencoded' \
https://login.microsoftonline.com/<tenant-id>/oauth2/v2.0/token \
-d 'client_id=<client-id>' \
-d 'grant_type=client_credentials' \
-d 'scope=2ff814a6-3304-4ab8-85cb-cd0e6f879c1d%2F.default' \
-d 'client_secret=<client-secret>

// Save token in cache
export const msalInstance = new PublicClientApplication(config.msalConfig);
const msalTokenCache = msalInstance.getTokenCache();
const silentRequest: SilentRequest = {
  scopes: ["User.Read", "email"],
  authority: "https://login.microsoftonline.com/my-tenant-d"
};
const serverResponse: ExternalTokenResponse = {
  token_type: "Bearer",
  scopes: "User.Read email",
  expires_in: 3599,
  id_token: "my id token",
}
const loadTokenOptions: LoadTokenOptions = {
  clientInfo: "my service principal client ID"
};
msalTokenCache.loadExternalTokens(silentRequest, serverResponse, loadTokenOptions);
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by mpminayo** [comment]
MSAL node does not take service principals as input. What is the end goal here?

**Comment by ss90128311** [comment]
Hi, we're looking to login to our application via a service principal in order to run automated tests, we are trying to use a service principal as we are not allowed to use a test user account. I assume this is a no-go then?

**Comment by ss90128311** [comment]
Although, even when we did try with a test user account it still didn't work. We used the ROPC flow in order to generate a token for the user, extracted and saved the values in the cache before the test and we still got re-directed to login when running the tests. We were using the example code listed here in order to generate the cache values in the correct format: https://github.com/juunas11/AzureAdUiTestAutomation/blob/main/UiTestAutomation.Cypress/cypress/support/auth.js

**Comment by andrewalderson** [comment]
@ss90128311  I have tried doing this with a Service Principal and have never been able to figure it out. You would have to use the msal-node and a plugin to get the tokens. I could never get it to work. I have a sample of how to do this with a test user in github [(here)](https://github.com/andrewalderson/angular-msal).  It is based off of the sample you linked to. That sample is a little outdated now. The MSAL library now has a utility method that side loads the tokens called ```loadExternalTokens```.

My sample uses Angular and NX. There is a custom command in the libs/shared/cypress-commands that handles logging in with ROPC to get tokens and cache them.  It loads he msal config from a json file so it can be modified in the cypress tests. See the app.spec files to see how this is done. You also have to make sure that the tokens are in the correct browser storage - sessionStorage by default.

I am currently using this same code in a number of projects and it works great.

Hope this helps.

**Comment by ss90128311** [comment]
> @ss90128311 I have tried doing this with a Service Principal and have never been able to figure it out. You would have to use the msal-node and a plugin to get the tokens. I could never get it to work. I have a sample of how to do this with a test user in github [(here)](https://github.com/andrewalderson/angular-msal). It is based off of the sample you linked to. That sample is a little outdated now. The MSAL library now has a utility method that side loads the tokens called `loadExternalTokens`.
> 
> My sample uses Angular and NX. There is a custom command in the libs/shared/cypress-commands that handles logging in with ROPC to get tokens and cache them. It loads he msal config from a json file so it can be modified in the cypress tests. See the app.spec files to see how this is done. You also have to make sure that the tokens are in the correct browser storage - sessionStorage by default.
> 
> I am currently using this same code in a number of projects and it works great.
> 
> Hope this helps.

I have ran your example and made a few changes to it, I needed to change the scope and add a client_secret value. I have managed to generate a token, I then provide a redirect back to my application. However I just see a grey screen. I tried copying the tokens generated from the test manually into session storage within the app itself and I still get redirected to login.

**Comment by sameerag** [comment]
@ss90128311 Is this what you are looking for - [managed identities](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview)? Please let us know your use case clearly for us to suggest which solution works for you.
