### ISSUE TITLE
Token data is not being updated after edit account flow

### ISSUE THREAD

**Issue by ranzolinrafa** [AzureAD/microsoft-authentication-library-for-js#4587]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.22.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.3.1

### Description

We're trying to implement an edit account feature in our application but we're encountering a problem with the edit account flow. When user has ended the flow and the SSO returns the user to the application the account is not being updated, the user needs to sign-out and sign-in again to get the updated data.

### Error Message

No error message is received

### Msal Logs

![msal-logs](https://user-images.githubusercontent.com/46724955/157308062-26fc8743-87b9-41ca-abd5-eda223aa2b81.png)

### MSAL Configuration

```javascript
{
		clientId: '2fdd06f3-7b34-49a3-a78b-0cf1dd87878e',
		authority: b2cPolicies.authorities.signUpSignIn.authority,
		knownAuthorities: [b2cPolicies.authorityDomain],
		redirectUri: 'http://localhost:3000',
	},
	cache: {
		cacheLocation: 'localStorage',
	},
	system: {
		loggerOptions: {
			loggerCallback: (level, message, containsPii) => {
				if (containsPii) {
					return;
				}
				// eslint-disable-next-line default-case
				switch (level) {
					case LogLevel.Error:
						// eslint-disable-next-line no-console
						console.error(message);
						return;
					case LogLevel.Info:
						// eslint-disable-next-line no-console
						console.info(message);
						return;
					case LogLevel.Verbose:
						// eslint-disable-next-line no-console
						console.debug(message);
						return;
					case LogLevel.Warning:
						// eslint-disable-next-line no-console
						console.warn(message);
				}
			},
		},
	},
}
```

### Relevant Code Snippets

```javascript
// Here's how I'm getting the token into a useEffect in our AuthContext


useEffect(() => {
		if (accounts.length === 0) {
			return false;
		}

		console.log(accounts);
		const account = accounts[0];
		const authority = b2cPolicies.authorities.signUpSignIn.authority;

		if (accounts.length > 0) {
			instance
				.acquireTokenSilent({
					authority,
					scopes: loginRequest.scopes,
					account,
					forceRefresh: true,
				})
				.then(response => {
					if (response) {
						setUser({
							...account.idTokenClaims,
							token: response.accessToken,
						});
						setOnHeadersAndLocalStorage(response.accessToken);
					}
				})
				.catch(err => {
					if (err instanceof InteractionRequiredAuthError) {
						const request = {
							authority,
							scopes: loginRequest.scopes,
							prompt: 'login',
						};
						return instance.acquireTokenRedirect(request);
					}
					throw Error(err);
				});
		}
	}, [accounts, instance]);
```

### Reproduction Steps

1. Click on Edit Account button
2. Edit account data and save
3. SSO returns the user to the application and the old data is shown

### Expected Behavior

1. Click on Edit Account button
2. Edit account data and save
3. SSO returns the user to the application and the new data is shown

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge

### Source

External (Customer)

**Comment by ranzolinrafa** [comment]
I've uploaded a sample project so anyone can reproduce the problem. 
https://github.com/ranzolinrafa/sample-sso-azure-react

**Comment by mpminayo** [comment]
Are you experiencing something similar to this https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4411? If so, we are looking into it.

**Comment by ranzolinrafa** [comment]
> Are you experiencing something similar to this #4411? If so, we are looking into it.

 @mpminayo  It's seems to be the same problem with msal-browser library, do you have and idea when this will be prioritized?

**Comment by ranzolinrafa** [comment]
I'm closing this issue since there is another already in progress.

https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4411
