### ISSUE TITLE
The library keeps to add default scopes when I'm requesting for a one

### ISSUE THREAD

**Issue by adamblok** [AzureAD/microsoft-authentication-library-for-js#4591]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.22.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

For a logged in user to my application, I'd like to ask him later for some additional permission (User.ReadBasic.All) to be able to perform some operations. My code looks like:

```js
const loginRedirectParams = {
   scopes: ['User.ReadBasic.All']
};
this.authContext.loginRedirect(loginRedirectParams);
```

It works as expected and redirect user to a login page when he needs to accepts new permissions list. The problem is, except the permission I requested, there are three more scopes:

```&scope=User.ReadBasic.All%20openid%20profile%20offline_access```

Why is that? How can I force the MSAL library to stop adding some extra scopes?

### MSAL Configuration

```javascript
{
   auth:
   authority: "https://login.microsoftonline.com/xxx"
   clientId: "xxx"
   navigateToLoginRequestUrl: true
   postLogoutRedirectUri: "xxx"
   redirectUri: "xxx"
   cache: {
      cacheLocation: "localStorage"
      storeAuthStateInCookie: false
   }
}
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by samuelkubai** [comment]
Hi @adamblok,

Thank you for reaching out, we require the additional scopes to ensure the library works as expected as documented [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md#im-seeing-scopes-openid-profile-email-offline_access-and-userread-in-my-tokens-even-though-i-havent-requested-them-what-are-they)

However, why do you want the extra scopes removed, if I may ask?

**Comment by adamblok** [comment]
@samuelkubai Thanks for the answer. I'd like to ask for a single scope for an extra call in API (it receives basics scopes after first user login), which needs ``User.ReadBasic.All`` in order to get all users from a tenant. It doesn't need additional scopes and I'd like to not ask user for them in a login prompt. I can do that by generating URL by myself in a frontend code (and it works), but for obvious reason it'd be better to use the MSAL library for this action.

**Comment by samuelkubai** [comment]
Hi @adamblok, at this point the library does require to inject the default scopes to ensure the library works as expected. We will however take your case under consideration, keep your eye out for our next releases on the evolution of this behaviour.

**Comment by adamblok** [comment]
@samuelkubai Thanks
