### ISSUE TITLE
Which Library should we use to integrate Azure Ad B2C login in my Electron React App? 

### ISSUE THREAD

**Issue by vishnu-marthala** [AzureAD/microsoft-authentication-library-for-js#4592]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.22.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.3.0

### Description

I am trying to integrate  Azure Ad B2C login in my [Electron React App](https://electron-react-boilerplate.js.org/). I have used the [MSAL-React Wrapper library](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/FAQ.md) for the Login authentical and it works fine in dev mode because of webserver but in production it doesn't work because no webserver in production. I even tried running this example https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/ElectronTestApp but it doesnt work for Azure AD B2c tenant.  Also, which redirect uri should i use for my Electron app on windows http://localhost:3333/ or msal3cb5f0ac-afd2-4579-9369-b26bc7212f69://auth. I tried both and both showed an empty screen after azure login screen is success. 

Now the question is: what library should i use to integrate azure AD B2c login in my Electron(backend)+React(frontend) App ? So that the user login with azure portal and my app get a valid token.

### MSAL Configuration

```javascript
export const msalConfig: Configuration = {
  auth: {
    clientId: '3cb5f0ac-afd2-4579-9369-b26bc7212f69',
    authority:
      'https://kebazureapps.b2clogin.com/kebazureapps.onmicrosoft.com/B2C_1_SignIn',
    knownAuthorities: ['kebazureapps.b2clogin.com'],
    redirectUri: 'msal3cb5f0ac-afd2-4579-9369-b26bc7212f69://auth',
    postLogoutRedirectUri: 'msal3cb5f0ac-afd2-4579-9369-b26bc7212f69://auth',
  },
};
```

### Identity Provider

Azure B2C Basic Policy

### Source

External (Customer)

**Comment by samuelkubai** [comment]
Hi @vishnu-marthala 

Thank you for reaching out to us, to answer which library to use where, you should use msal-node for the Electron app and msal-react for the React(frontend).

To help us debug you problem, please provide us with an accurate step by step reproduction of your setup.

**Comment by vishnu-marthala** [comment]
thank you @samuelkubai  for the reply. My situation is that my frontend is in React and backend is in Electron.js . So how can i use both as you suggested?

**Comment by jo-arroyo** [comment]
@vishnu-marthala Unfortunately, we have not fully investigated the model you described and do not currently have a sample. We will be investigating and update this issue when we know more. 

cc: @salman90
