### ISSUE TITLE
Is MSAL for Javascript using FIPS validated cryptography?

### ISSUE THREAD

**Issue by mdivkovic-speech** [AzureAD/microsoft-authentication-library-for-js#4594]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

Any

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

[FIPS](https://en.wikipedia.org/wiki/FIPS_140-2) Is a security standard that federal agencies in the US have to adhere to, and that means that the software they use also has to be built on top of FIPS validated cryptography.

Following this, could you answer these questions:

Is the MSAL Javascript client library using [FIPS approved cryptographic algorithms](https://csrc.nist.gov/csrc/media/publications/fips/140/2/final/documents/fips1402annexa.pdf)?
Does MSAL use any proprietary cryptographic modules or libraries, or does it use the underlying runtime default cryptography?

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by peterzenz** [comment]
We are to our current understanding using algorithms that are FIPS approved, and we are not using any proprietary crypto algorithms.  You're welcome to review the source and confirm which crypto libraries and algorithms are being used as our source is all open.  We have not, and likely will not submit the MSAL library for official or formal FIPS certification.
