### ISSUE TITLE
I'm acquiring token in axios interceptors, how could I know whether there is an interaction happening?

### ISSUE THREAD

**Issue by hp7hao** [AzureAD/microsoft-authentication-library-for-js#4595]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.22.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.3.0

### Description

Hi, I'm now integrating msal to our web app, we use axios to send API calls.
After reading the doc, I think the most straightforward way is to put acquireTokenSilent calls in axios interceptors.
But we keep getting interaction_in_progress error when refresh token expires, how can I know there is already an interaction happending in background?
And what is good practice to acquire refreshtoken after expriation outside react component tree?

Thanks a lot.

### MSAL Configuration

```javascript
const msalConfig = {
    auth: {
      clientId: '',
      authority: 'https://login.microsoftonline.com/common',
      redirectUri: '/',
    },
    cache: {
      cacheLocation: 'localStorage',
    },
  };
```

### Relevant Code Snippets

```javascript
const acquireToken = async () => {
    let token = '';
    const authRequest = {
      scopes: ['api://'],
      account,
    };
    try {
      const resp = await instance.acquireTokenSilent(authRequest);
      token = resp.accessToken;
    } catch (err) {
      if (err instanceof InteractionRequiredAuthError) {
        await instance.acquireTokenRedirect(authRequest);
      }
    }
    return token;
  };
```

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by samuelkubai** [comment]
Hi @youkabeng, 

The `interaction_in_progress` error is not originating from the `acquireTokenSilent` call rather the `acquireTokenRedirect` and with react we [advice](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/FAQ.md#what-can-i-do-outside-of-azuremsal-react-context) that all functions that trigger an interaction be done under the react component tree rather than in the axios interceptor.

**Comment by hp7hao** [comment]
Hi @samuelkubai 
I checked the advice, I think it explains the strange issues reported by random users.
I'm moving redirect call to react context.
Thanks a lot.

**Comment by hp7hao** [comment]
Hi @samuelkubai,

Though I added redirect calls in interceptors, but all the API calls are triggered in react useEffect() hook, I think it's already under the react component tree. I'm not a react expert, please correct me if I get it wrong. Thank you.

**Comment by tnorling** [comment]
@youkabeng Yes this should be fine. Are you still experiencing issues with this?

**Comment by OlegSharyk** [comment]
> The `interaction_in_progress` error is not originating from the `acquireTokenSilent` call rather the `acquireTokenRedirect` and with react we [advice](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/FAQ.md#what-can-i-do-outside-of-azuremsal-react-context) that all functions that trigger an interaction be done under the react component tree rather than in the axios interceptor.

@samuelkubai, according to your advice I need to get access Token every time when I need to call to API in react component. 
But using axios interceptor helps to get access Token once and than call API in Redux-Saga, not in each react component.
According to your advice I need to rewrite logic for application and refuse Redux-Saga.
