### ISSUE TITLE
Redirect flow within iframe with allowRedirectInIframe flag

### ISSUE THREAD

**Issue by sibijohn72** [AzureAD/microsoft-authentication-library-for-js#4596]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.22.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.1.1

### Description

Hi,

My application B is hosted inside an iframe of another application A. The user journey is that the user logs into the parent application A and then clicks on the navigation menu which loads my application B in an iframe. This application B is an Angular SPA and the backend is hosted on a different domain. I am trying use Bearer tokens in this application B after acquiring a session with the redirect flow. I am using the "allowRedirectInIframe" flag as well. however this does not work. B starts the redirect flow comes back and starts it all over again and fails with the following error
![image](https://user-images.githubusercontent.com/7763098/157837498-c29b68af-8f89-46e2-81f6-6a100d972436.png)

I can see some issues/docs where it explicitly says that redirect flow is not possible in iframes. for eg
https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/3759
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/iframe-usage.md
 
 But the existence of the "allowRedirectInIframe" flag leads me to believe that this is outdated. Please correct me if i am wrong. Otherwise can you tell me what i am doing wrong? I have attached my msal config and app.module.ts file below.

### MSAL Configuration

```javascript
auth: {
    clientId: 'xxxxxxxxxxxx',
    authority: b2cPolicies.authorities.signUpSignIn.authority,
    knownAuthorities: [b2cPolicies.authorityDomain],
    redirectUri: https://my.redirect.uri,
    postLogoutRedirectUri: '/logged-out'
  },
  cache: {
    cacheLocation: BrowserCacheLocation.LocalStorage,
    storeAuthStateInCookie: false
  },
  system: {
    loggerOptions: {
      logLevel: LogLevel.Error,
      piiLoggingEnabled: false,
    },
    allowRedirectInIframe: true,
  },
```

### Relevant Code Snippets

```javascript
// app.module.ts code
  providers: [
    ConfigService,
    {provide: HTTP_INTERCEPTORS, useClass: RequestHeaderInterceptor, multi: true},
    {provide: HTTP_INTERCEPTORS, useClass: ConfigServiceInterceptor, multi: true, deps: [ConfigService]},
    {provide: HTTP_INTERCEPTORS, useClass: RequestErrorInterceptor, multi: true, deps: [ToastrService]},
    {provide: ErrorHandler, useClass: AppErrorHandler},
    {
      provide: HTTP_INTERCEPTORS,
      useClass: MsalInterceptor,
      multi: true,
    },
    {
      provide: MSAL_INSTANCE,
      useFactory: MSALInstanceFactory,
    },
    {
      provide: MSAL_GUARD_CONFIG,
      useFactory: MSALGuardConfigFactory,
    },
    {
      provide: MSAL_INTERCEPTOR_CONFIG,
      useFactory: MSALInterceptorConfigFactory,
    },
    MsalService,
    MsalGuard,
    MsalBroadcastService,
    // {
    //   provide: APP_INITIALIZER,
    //   multi: true,
    //   deps: [MsalService],
    //   useFactory: (authService: MsalService) => {
    //     return () => {
    //       return authService.ssoSilent({
    //         scopes: []
    //       }).toPromise();
    //     };
    //   }
    // },
  ],
  bootstrap: [AppComponent]
})
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@sibijohn72 Are you using the B2C embedded sign in feature? The `allowRedirectInIframe` flag was added specifically to enable that feature (otherwise, the server will return `X-Frame-Options` header set to `Deny`, which will prevent the login page from being rendered in the iframe).

From the documentation you linked:

> **Azure AD B2C** offers an [embedded sign-in experience](https://docs.microsoft.com/azure/active-directory-b2c/embedded-login), which allows rendering a custom login UI in an iframe. Since MSAL prevents redirect in iframes by default, you'll need to set the [allowRedirectInIframe](./configuration.md#system-config-options) configuration option to **true** in order to make use of this feature. Note that enabling this option for apps on **Azure AD** is not recommended, due to the above restriction.

**Comment by sibijohn72** [comment]
@jasonnutter We dont use the embedded sign-in experience. Thank you for clarifying. 👍 
It would be really great if you can tell me if the following thought process of mine is right. :)
 My app and the iframe is on the same origin. Unfortunately the parent frame does not use local storage for MSAL's caching. Given this scenario i am assuming that i could to go with the "Apps with cross origin" approach outlined [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/iframe-usage.md#apps-with-cross-origin). Is my understanding correct?

**Comment by jasonnutter** [comment]
@sibijohn72 Yes, you can try that approach.

**Comment by sibijohn72** [comment]
Try it already. Works. Thank you. :)

**Comment by kevinvugts** [comment]
> @sibijohn72 Are you using the B2C embedded sign in feature? The `allowRedirectInIframe` flag was added specifically to enable that feature (otherwise, the server will return `X-Frame-Options` header set to `Deny`, which will prevent the login page from being rendered in the iframe).
> 
> From the documentation you linked:
> 
> > **Azure AD B2C** offers an [embedded sign-in experience](https://docs.microsoft.com/azure/active-directory-b2c/embedded-login), which allows rendering a custom login UI in an iframe. Since MSAL prevents redirect in iframes by default, you'll need to set the [allowRedirectInIframe](./configuration.md#system-config-options) configuration option to **true** in order to make use of this feature. Note that enabling this option for apps on **Azure AD** is not recommended, due to the above restriction.

Can you elaborate more on this topic? According to Microsoft the front-channel logout functionality is supported for both Azure AD as Azure AD B2C. However, indeed I get an error when trying to logout from Azure AD in an iframe that has the allowRedirectInIframe: true  flag set.

**Comment by gurhangulmez** [comment]
@sibijohn72 Thanks for openning this discussion. I am trying to achieve the same thing, and it took a lot of time. Did you use postMessage to authenticate the page in iframe?

**Comment by sibijohn72** [comment]
@gurhangulmez  No, i didnt have to do that. I can share my config and the
app module file. But i am on vacation and can only do this after Jan 4th.
Sorry :/

Regards,
*Sibi John*
