### ISSUE TITLE
Requesting "passport-azure-ad" migrate off of the deprecated "request" package for getting openid connect metadata.

### ISSUE THREAD

**Issue by ryansh100** [AzureAD/microsoft-authentication-library-for-js#4598]
### Core Library

Passport Azure AD (passport-azure-ad)

### Wrapper Library

Not Applicable

### Description

The "request" package is still used in the passport-azure-ad library. This hurts the ability of an application to maintain a high level of security and reduce CVE's.

https://www.npmjs.com/package/request
https://github.com/request/request/issues/3142

I believe that these could easily be migrated to the node native **https** module since Azure AD should not be available from a non-secure location. This package shouldn't really need to be an isomorphic library as a passport middleware.

### Source

External (Customer)

**Comment by sameerag** [comment]
@ryansh100 We are working on a new token validation library which is moving to a more up-to-date https module. Currently we are not adding new features on `passport-azure-ad` since we plan to move away soon. cc @jo-arroyo to add more context.

**Comment by erik-neumann** [comment]
Hi @sameerag ,

any idea of a timeline or maybe reference to that replacement? There currently seem to be some security issues within currently used packages. E.g. related issues #4633 and #4705. Does this mean they won't be addressed within `passport-azure-ad`?

**Comment by jasonnutter** [comment]
@erik-neumann We will be addressing these dependencies soon. No exact ETA yet.

**Comment by sameerag** [comment]
This will be addressed in `passport-azure-ad` as this is a security vulnerability @erik-neumann. We have picked this up and will update the issue with the PR once we have it ready.

**Comment by adrianzielonka** [comment]
Seems like this issue should now be resolved with the release of version 4.3.3
@erik-neumann

**Comment by jasonnutter** [comment]
Correct, 4.3.3 was released yesterday without `request`.
