### ISSUE TITLE
B2C Error codes enum

### ISSUE THREAD

**Issue by LuisDev99** [AzureAD/microsoft-authentication-library-for-js#4600]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.22.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.1.1

### Description

Duplicate issue of #1441 but since that issue got closed, I'm opening a new issue to this since it really never got solved.

It would be really helpful if we had enums for all the [error codes from B2C](https://docs.microsoft.com/en-us/azure/active-directory-b2c/error-codes) to avoid maintaining those error codes ourselves. It would be a great addition to the library.

For example, something like this: 

```ts
export enum B2CErrors {
    resetPassword = 'AADB2C90037',
    /* all other error codes.... */
}
```

**Comment by samuelkubai** [comment]
Hi @LuisDev99 

Thank you for raising this issue, the errors in question are server generated errors, the server is the source of truth for this, it's not practical for us to mirror this.

The best solution here is to improve the docs and we have an active conversation on that.
