### ISSUE TITLE
HttpClient call requires login

### ISSUE THREAD

**Issue by nmylle** [AzureAD/microsoft-authentication-library-for-js#4604]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.13.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.0-beta.3

### Description

Hi,

I have an angular website that uses the MSAL to let colleagues login and ask company data. 
The calls to the endpoint must be authenticated (as it is company data). (endpoint example: api.company.be/aaa) 
This all works.
 
Now I need to create an page for external people who need to see other data.
I created an unauthorized endpoint on our company API and a page on the website. (endpoint example:: api.company.be/bbb)
I made sure the specific URL doesnt require a login so unauthorized people can visit the page.
This also works.

But now I am stuck when trying to get the data from my unauthorized endpoint. Everytime I try to use an httpClient call, I'm getting redirect to a login page (which I don't want).

Is there a way to fix this problem?

FYI: I am not a angular expert

### MSAL Configuration

```javascript
export function MSALInstanceFactory(): IPublicClientApplication {
  return new PublicClientApplication({
    auth: {
      clientId: '3454d924-4412-4505-9af6-XXXXXX',
      authority: 'https://login.microsoftonline.com/510df548-a539-40b9-8716-eb24afaccf1f',
      redirectUri: environment.MSAL_redirectUri,
      postLogoutRedirectUri: environment.MSAL_postLogoutRedirectUri,
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE,
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Warning,
        piiLoggingEnabled: false
      }
    }
  });
}

export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
  const protectedResourceMap = new Map<string, Array<string>>();
  protectedResourceMap.set(environment.API_URL, ['api://f1c2d297-0e55-4c4f-9a97-XXXXX/api-access']);

  return {
    interactionType: InteractionType.Redirect,
    protectedResourceMap
  };
}

export function MSALGuardConfigFactory(): MsalGuardConfiguration {
  return {
    interactionType: InteractionType.Redirect
  };
}
```

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by samuelkubai** [comment]
Hi @mylle, thanks for reaching out to us.

It looks like you are still using the beta version of msal-angular, whereas msal-angular is now on version 2.1.2. It would be great if you could upgrade.

On the matter at hand, is endpoint set in the protectedResourceMap (environment.API_URL) the same as the authorized and unauthorized endpoint you are trying to use? (I.e. is environment.API_URI api.company.be)

If it was the same, then whenever you makes an HTTP call, the msal-interceptor will intercept that call and try to access a token and prompt for login if there is no token, thinking that that endpoint has been protected.

In this situation, you could either make the protectedResourceMap entry more specific (only have api.company.be/aaa) or unprotect the /bbb endpoint by adding protectedResourceMap.set('api.company.be/bbb', null); which would unprotect the route you do not want to prompt for login.

For more information  on the msal-interceptor you can visit the documentation [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/msal-interceptor.md#protected-resource-map)

Looking forward to hearing from you, on whether this solution resolved your issue

**Comment by nmylle** [comment]
Hi @samuelkubai , 

I want to let you know everything worked like you explained!
I changed my code to this:

```
export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
  const protectedResourceMap = new Map<string, Array<string>>();
  // No verification on this URL:
  protectedResourceMap.set(environment.API_URL + '/external/*', null); 
  // Verification:
  protectedResourceMap.set(environment.API_URL, ['api://f1c2d297-0e55-4c4f-9a97-f327b500e832/api-access']);

  return {
    interactionType: InteractionType.Redirect,
    protectedResourceMap
  };
}
```

Thank you very much for the explanation!

Kind regards,
Niels
