### ISSUE TITLE
node js and browser only compliance

### ISSUE THREAD

**Issue by jeffj6123** [AzureAD/microsoft-authentication-library-for-js#4607]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.70

### Wrapper Library

Not Applicable

### Wrapper Library Version

n/a

### Description

When wrapping an existing web app into an electron app, I ran across the following error. I just wanted to confirm if this means this tenant isnt allowed to use an electron browserWindow configuration and if there is another way in which authenticating would be possible?

I followed almost directly from https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-nodejs-desktop#create-the-projec
![aad-issue](https://user-images.githubusercontent.com/15344718/158876990-32caffeb-3f01-45bd-aadc-0e71a163dc93.PNG)
t

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by hectormmg** [comment]
Hi @jeffj6123 , thanks for raising the issue. I'll try to reproduce this issue and get back to you as soon as I get a successful repro. It is likely that for corp accounts Electron would not be a supported browser environment out of the box, so we'll have to look into the specifics to give you a concrete answer. For now, following that tutorial or our Electron sample (in the msal-node-samples directory) is your best bet.

**Comment by jeffj6123** [comment]
hey @hectormmg I had made this progress by using the electron sample and that is when I hit this issue.

**Comment by hectormmg** [comment]
@jeffj6123 could you elaborate on how this error happens with the sample? Is this error happening on login in the popup?
