### ISSUE TITLE
How to export token cache for use in backend console application?

### ISSUE THREAD

**Issue by keystroke** [AzureAD/microsoft-authentication-library-for-js#4609]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

We are trying to enable a workflow like described in the MSAL.NET docs for "sharing" the tokens acquired from this frontend application in a backend context:
https://github.com/Azure-Samples/ms-identity-dotnet-advanced-token-cache/blob/master/1-Integrated-Cache/1-1-WebApp-BgWorker/README.md#share-the-msal-token-cache-between-a-web-app-and-a-background-console-worker-app

The WAC team is updating from msal 1 to msal2 and will now gain access to a refresh token from the PKCE flow. The hope is that we can "save" that user authentication session, and later (several hours later) make use of the refresh token to acquire fresh access tokens to Azure and Graph. This is for a private cloud deployment flow, where a customer would sign-in initially and then kick-off a multi-hour deployment, and the much later in this flow is when the access tokens to call Azure are required.

MASL design is to obscure access to the refresh tokens, and instead exposes cache serialization methods in the .NET versions of the SDK. The idea is that you would serialize the token cache bytes, and then import them elsewhere later, and the acquire token silent flows would be able to "find" the refresh token internally and acquire the necessary access tokens.

Is this flow possible to use with the MSAL JS 2.0 library? If so, how can we export the token cache? The alternative would be to write some code to extract the refresh token manually out of the local storage / cache, and then use direct REST calls on the backend to acquire access tokens we need directly (rather than trying to use any MSAL assets).

Would you be able to advise a flow for how to use MSAL with this frontend app and a backend PowerShell / EXE using MSAL.NET?

Thanks!

### Source

Internal (Microsoft)

**Comment by jo-arroyo** [comment]
@keystroke While we do have samples demonstrating the hybrid flow where a user is authenticated server-side and then an auth code is redeemed client-side, MSAL does not support the scenario you describe. The refresh token issued by MSAL Browser is specific to single-page applications, and therefore cannot be exchanged for tokens for any other application type.

**Comment by keystroke** [comment]
@jo-arroyo can you provide more details? Which API call can be used with the refresh token acquired from MSAL? Why couldn’t we use this in backend with an embedded browser session (if truly necessary) or some kind of CURL request?

**Comment by jo-arroyo** [comment]
@keystroke Different application models issue different refresh tokens. The refresh tokens issued from the browser is different from refresh tokens from the server, and you cannot exchange a refresh token from a SPA app for access tokens for the backend.

cc. @nickludwig for further information on refresh tokens. 

Could you further clarify what you are trying to achieve? What is your use case?
If you are looking to do something similar to the .NET example, msal-node does have the pieces you'd need (distributed cache, supporting the same flows) but we do not have a sample for this particular usage.

**Comment by keystroke** [comment]
@jo-arroyo the flow is for a private cloud deployment system; a customer initiates a multi-hour private cloud deployment from a Windows Admin Center (WAC) UI, which is using MSAL.js. The auth token(s) acquired there are not used until hours later in the deployment. The auth context needs to be captured up-front and saved to be used later to acquire fresh access tokens. This WAC SPA application ends-up collecting parameters and then invoking a PowerShell script on the backend. This would include passing-in the auth context (e.g. refresh token or full token cache byes if that were supported).

I understand that the refresh token you'll receive from ESTS is "different" than one that might be issued for a different type of application. However, it should still be a MRRT (multi-resource refresh token) capable of acquiring a fresh access token later-on in the deployment. Is there any kind of IP-address pinning or other limitations on the ESTS side of this that lead you to suspect the refresh token would not work? Because it needs to work in the context of some JS sending a request from a public client SPA to ESTS to exchange for an access token, so there isn't really much that could be done on ESTS to "prevent" use from using a refresh token from the backend context other than seeing it's initiated from a different IP address.

So far, the WAC engineer has found the refresh token in local storage and can extract it manually from there. + @sushmadharm who was trying this out.

**Comment by jasonnutter** [comment]
@keystroke Today, eSTS does not allow refresh tokens issued to spa redirect URIs to be redeemed server-side, and in the future, refresh tokens issued by eSTS will be cryptographically bound to the browser, to explicitly prevent what you are trying to do. This is one of the reasons we do not expose the refresh tokens in our API surface.

Have you considered using the on behalf of flow here? https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow

**Comment by keystroke** [comment]
We discussed offline; issue here is WAC is a public client without a straightforward way of making it a confidential client to use those flows. An approach using device login flow could perhaps be utilized and may even get some direct support in future versions of MSAL.js (requiring ESTS adjusting the CORS on the token endpoint for that flow).

**Comment by ghost** [comment]
This issue requires attention from the MSAL.js team and has not seen activity in **5 days**. @samuelkubai please follow up.

**Comment by sameerag** [comment]
Closing this since the use case is clarified.
