### ISSUE TITLE
Error on module import 

### ISSUE THREAD

**Issue by jobala** [AzureAD/microsoft-authentication-library-for-js#461]
## I'm submitting a...
<pre><code>
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [X] Bug report  
- [ ] Performance issue
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 0.1.Z

## Current behavior
Getting the error below
(index):50 Error: Fetch error: 404 Not Found
  Instantiating http://localhost:3000/@azure/msal-angular
  Loading http://localhost:3000/app/app.module.js
  Loading main-jit.js
    at fetch.js:37
    at ZoneDelegate.invoke (zone.js:388)
    at Zone.run (zone.js:138)
    at zone.js:872
    at ZoneDelegate.invokeTask (zone.js:421)
    at Zone.runTask (zone.js:188)
    at drainMicroTaskQueue (zone.js:595)

## Expected behavior
Shouldn't see an error

## Minimal reproduction of the problem with instructions
* npm install the angular msal library
* Add the module to app.module.ts

</code></pre>

**Comment by nehaagrawal** [comment]
@jobala I am closing this issue since it's not reproducible and due to lack of activity. Please reopen if issue exists.

**Comment by thewahome** [comment]
@nehaagrawal I am getting the same exact errors.
