### ISSUE TITLE
MsalGuard is allowing to route even after logout in same browser window.

### ISSUE THREAD

**Issue by yuvarani-nagarajan** [AzureAD/microsoft-authentication-library-for-js#4610]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.22.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.5

### Description

**Issue**:   MsalGuard is not preventing to use the route url, when the session is logged out from different application with same Microsoft authentication
 
**Steps to reproduce**:
1. Open Incognito mode 

2. Login to any  Portal with Microsoft authentication (e.g. Workday)

3. Now In another tab I am opening my application and click on Login link which is using Msal authentication.

Observation: User is able to login successfully. 

4. Now logout from Workday

5. I am opening  my Application again and click on Login

Observation : User is asked to enter username & password

6. Now directly open the route url https://localhost:4200/home, which is guarded by MsalGuard. 

**Actual** : It is observed that user is directly redirected to the home page even though user have not yet logged in, and this url https://login.microsoftonline.com/{tenant-id}/v2.0/.well-known/openid-configuration is called and all user related details are getting stored in localstorage.

**Expected:**  Even though user gives direct route url, application should route to sign in page as it is logged out from different application.

I have attached my routing file and MSAL configuration for reference, kindly let me know what I am missing.

### MSAL Configuration

```javascript
export function MSALInstanceFactory():IPublicClientApplication{
  return new PublicClientApplication({
    auth: {clientId: environment.clientId,
      authority: environment.authority,
      redirectUri: environment.redirectUrl,
      navigateToLoginRequestUrl:false,
      postLogoutRedirectUri: environment.loginUrl,
    },
      cache: {
        cacheLocation:BrowserCacheLocation.LocalStorage,
        storeAuthStateInCookie: true, // Set to true for Internet Explorer 11
    
      }
      ,
      system: {
        loggerOptions: {
          loggerCallback(logLevel: LogLevel, message: string) {
            //console.log(message);
          },
          logLevel: LogLevel.Verbose,
          piiLoggingEnabled: false
        }
      }
    });
}
export const protectedResources = {
  profileApi: {
    endpoint: environment.BASE_URL,
    scopes: [environment.Audiance],
 
    
    
  },
}


export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
  const protectedResourceMap = new Map<string, Array<string>>();
 protectedResourceMap.set(protectedResources.profileApi.endpoint, protectedResources.profileApi.scopes);

  return {
    interactionType: InteractionType.Redirect,
    protectedResourceMap,
  };
}

export function MSALGuardConfigFactory():MsalGuardConfiguration{
  return {
    interactionType: InteractionType.Redirect,
    authRequest:{
      scopes:[environment.Audiance],
    },
  };
}
```

### Relevant Code Snippets

```javascript
app-routing file:
import { NgModule } from '@angular/core';
import { RouterModule, Routes, ActivatedRouteSnapshot, RouterStateSnapshot } from '@angular/router';
import { MsalGuard } from '@azure/msal-angular'; // Import MsalInterceptor


const routes: Routes = [{
  path: '',
  canActivate: [],
  children: [ { 
    path: '',  
    loadChildren: () => import('./features/login/login.module').then(x => x.LoginModule),
    canActivate: [] 
  },
  { 
    path: 'home',  
    loadChildren: () => import('./features/dashboard/dashbord.module').then(x => x.DashboardModule),
    canActivate: [MsalGuard] 
  },
  { 
    path: 'search',  
    loadChildren: () => import('./features/search-study/search-study.module').then(x => x.SearchStudyModule),
    canActivate: [MsalGuard] 
  },
]
}
  
];
@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@yuvarani-nagarajan You can enable front-channel logout to prevent this from happening. Please see our docs on logout [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md#front-channel-logout) and our sample demonstrating this with MSAL Angular [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular11-sample-app).
