### ISSUE TITLE
Can you provide some sample/document on how to use msal-Angular for Google login?

### ISSUE THREAD

**Issue by TLKG** [AzureAD/microsoft-authentication-library-for-js#4615]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2

### Description

Love this library, works out great! 
Looking for a way to log in using Google gmail acct, and Apple's icloud as well. Can you please provide a document/sample on how?
Thank you!

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@TLKG Are you looking to use MSAL with B2C for your app? Please find more information on B2C [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/overview), how to work with MSAL.js and B2C [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/working-with-b2c.md), and our msal-angular B2C sample [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular11-b2c-sample).

**Comment by TLKG** [comment]
@jo-arroyo For this [Custom authentication in Azure Static Web Apps](https://docs.microsoft.com/en-us/azure/static-web-apps/authentication-custom?tabs=aad#configure-a-custom-identity-provider), to find out `AZURE_CLIENT_ID` and `AZURE_CLIENT_SECRET`, I go portal, find Azure Active Directory goes into Default Directory, Manage -> App registration, select the SWA, in the Overview, there is `Application (client) ID`, not seeing `secret`. Manage -> Certificates & secrets has none

**Comment by TLKG** [comment]
@jo-arroyo All my users need is to be authenticated using their own personal MS acct, Gmail acct, iCloud acct, etc. They don't need features such as sign-up, or manage their own MS/Google/iCloud profiles within my app. My app has own database backend not AAD directory/store to manage user access/authorization. The sophisticated feature of AAD B2C seems an overkill, and I admit not smart enough to understand.

Is there an easy way to achieve what I'm looking for?

**Comment by jo-arroyo** [comment]
@TLKG B2C would still be the way to authenticate your users, and our [msal-angular B2C sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular11-b2c-sample) demonstrates how to set it up for an Angular app. If you have more questions about portal configurations or how to set up B2C in a simple way for your application, please file a support request with B2C customer service [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options).

cc. @nickgmicrosoft for visibility.

**Comment by TLKG** [comment]
@jo-arroyo You are simply AWESOME!
