### ISSUE TITLE
Logout doesn't redirect back to my iOS app

### ISSUE THREAD

**Issue by RajendraNayak** [AzureAD/microsoft-authentication-library-for-js#4619]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.2.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

none

### Description

I am using MSAL auth library in my iOS app & login is perfectly working.
I want logout using browser so I made below

**signoutParameters.signoutFromBrowser = true**

But On calling logout(), I expect the browser to be redirected to my app once the logout process is completed. However, I just get a screen "You signed out of your account ..." and it stays there.

![Simulator Screen Shot - iPhone 13 - 2022-03-22 at 14 38 26](https://user-images.githubusercontent.com/3063882/159449738-175468c6-12c6-4c41-bf0a-06e6cfec39f9.png)

I use [CocoaPods](http://cocoapods.org/) to install MSAL

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@RajendraNayak Are you using MSAL for JavaScript or [MSAL for Objective C](https://github.com/AzureAD/microsoft-authentication-library-for-objc)?

**Comment by RajendraNayak** [comment]
@jo-arroyo I am using MSAL for Objective C 
https://github.com/AzureAD/microsoft-authentication-library-for-objc

**Comment by jo-arroyo** [comment]
@RajendraNayak Please open an issue on the MSAL for Objective C repository, as issues here are handled by the MSAL for JavaScript team. Closing.
