### ISSUE TITLE
You can't sign in with this GitHub account

### ISSUE THREAD

**Issue by TLKG** [AzureAD/microsoft-authentication-library-for-js#4622]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.1.1

### Description

A valid GitHub account got "You can't sign in with this GitHub account ... is a work or school account. You can't use this GitHub account to sign in"

![image](https://user-images.githubusercontent.com/22269729/159538214-ae9c7870-2500-49f6-8b94-ce8f258c2359.png)

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@TLKG You may need to look into the "Supported Account Types" setting in your Azure Portal app registration.

**Comment by TLKG** [comment]
@jo-arroyo This is all "Supported Account Types" has:
![image](https://user-images.githubusercontent.com/22269729/160158332-049d7895-d8d3-4886-bf3b-dddb14c777a1.png)

**Comment by jo-arroyo** [comment]
@TLKG You may need to link your Github account to a Microsoft account to use it in an AAD application (see [here](https://support.microsoft.com/en-us/account-billing/link-your-github-account-and-microsoft-account-c9b04f45-8978-448e-bb90-0503d22d7ea1#:~:text=Link%20your%20GitHub%20account%20and%20Microsoft%20account%201,GitHub%20and%20Microsoft%20accounts.%20...%203%20See%20also) for more details) or you may wish to make this a B2C application (see the other issue where we talked about B2C [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4615)).
