### ISSUE TITLE
Bypass "account list" page when authenticating

### ISSUE THREAD

**Issue by gregchak** [AzureAD/microsoft-authentication-library-for-js#4623]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

1.4.15

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.1.1

### Description

If a user in our SPA has not yet authenticated and they attempt to navigate to a route guarded by `MsalGuard`, they will be redirected to start the authentication process.  If that user had previously authenticated against AAD they are presented with a list of previously authenticated accounts, regardless of whether those accounts have access to our application or not.  For a user that is new to the application it would be easy to think they can click on one of their previously authenticated accounts and sign into the application that way.  Further giving this impression, if you click on one of those accounts it will ask you to authenticate.  The problem is at the end it will say that this account doesn't have access to our application which is completely accurate.  This is not a great user experience because now they either give up or try to go back and figure out where they messed up.  What they should have done is clicked on "Use another account" from the list of accounts and then be redirected to the sign in page with the option to create a new account.  This action is not obvious.   

I would like to know if there is a way to configure MSAL to bypass the account list page and go directly to the sign in page that asks for username and has the option to create a new account.  

Account List page for reference:
![image](https://user-images.githubusercontent.com/5882933/159558094-06c6c7ce-7b81-455b-8d4f-73c0bca34804.png)

Sign in page for reference:
![image](https://user-images.githubusercontent.com/5882933/159558218-82b112e2-2d0b-42ef-b9e1-acb7106bda37.png)

### MSAL Configuration

```javascript
auth: {
          clientId: `${clientId}`,
          authority: `https://login.microsoftonline.com/${tenant}`,
          redirectUri: '/loginredirect',
          postLogoutRedirectUri: '/',
          navigateToLoginRequestUrl: false
        },

        cache: {
          cacheLocation: BrowserCacheLocation.LocalStorage,
          storeAuthStateInCookie: isIE // set to true for IE 11
        },
        system: {
          windowHashTimeout: 90000,
          iframeHashTimeout: 90000,
          loadFrameTimeout: 90000,
          loggerOptions: {
            loggerCallback,
            logLevel: LogLevel.Error,
            piiLoggingEnabled: false
          }
        }
      }
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@gregchak You can bypass the select account page and force the login page by passing `prompt: "login"` in the login request. Please see our [FAQ](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md#in-what-scenarios-will-getallaccounts-return-multiple-accounts) for more information about all accounts, and [our docs](https://azuread.github.io/microsoft-authentication-library-for-js/ref/modules/_azure_msal_browser.html#popuprequest) for supported prompt values in the request and expected outcomes.

**Comment by gregchak** [comment]
I have my guard configured as follows.  Is this the correct way to implement this?  In this configuration I am redirected to the select account page and not the login page.
```
    {
      provide: MSAL_GUARD_CONFIG,
      useValue: {
        interactionType: InteractionType.Redirect,
        authRequest: {
          scopes: ['user.read'],
          prompt: 'login'
        }
      } as MsalGuardConfiguration
    },
```

**Comment by gregchak** [comment]
I think I found the issue.  My `MsalGuard` is doing the redirect as expected with the `prompt` value set to 'login'.  In the other area of my application I am manually calling `MsalService.loginRedirect()`.  I specified `RedirectRequest` options in the call and now it works as expected.  Thank you for your help!
