### ISSUE TITLE
BrowserAuthError: empty_window_error: window.open returned null or undefined window object in ios 

### ISSUE THREAD

**Issue by piyumi25** [AzureAD/microsoft-authentication-library-for-js#4626]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.22.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.3.1

### Description

I am using msal-browser and msal-react libraries to process authentication for outlook addin. When trying to use "loginPopup"
 in ios I am getting following error. In android it works fine.

### Error Message

popup_window_error: Error opening popup window. This can happen if you are using IE or if popups are blocked in the browser. Details: BrowserAuthError: empty_window_error: window.open returned null or undefined window object.

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/33615108/159626463-01218e32-a35a-4fdd-afd6-23f29a8448e1.png)

### MSAL Configuration

```javascript
auth: {
        clientId: "client-id", 
        authority: "https://login.microsoftonline.com/common", 
        redirectUri: "https://prt-test.azurewebsites.net/addin/taskpane.html",
        postLogoutRedirectUri: "https://prt-test.azurewebsites.net/addin/taskpane.html",
    },
    cache: {
        cacheLocation: "sessionStorage", // Configures cache location. "sessionStorage" is more secure, but "localStorage" gives you SSO between tabs.
        storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
    },
    system: {
        loggerOptions: {
            loggerCallback: (level, message, containsPii) => {
                if (containsPii) {
                    return;
                }
                switch (level) {
                    case LogLevel.Error:
                        console.error(message);
                        return;
                    case LogLevel.Info:
                        console.info(message);
                        return;
                    case LogLevel.Verbose:
                        console.debug(message);
                        return;
                    case LogLevel.Warning:
                        console.warn(message);
                        return;
                }
            }
        }
    }
```

### Relevant Code Snippets

```javascript
instance.loginPopup(loginRequest)
            .catch((error) => {console.log(error);
                setIsError(true);
                setErrorMessage(error?.message);
            })
```

### Reproduction Steps

1. use msal-browser and msal-react to login MS
2. when calling instance.loginPopup, this issue is occurred in ios

### Expected Behavior

Should open a popup to log in to Microsoft

### Identity Provider

common

### Browsers Affected (Select all that apply)

Safari

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@piyumi25 Does following the instructions in [this comment](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4095#issuecomment-930259019) address your issue?
