### ISSUE TITLE
How to get more information about the B2C-signed in user ?

### ISSUE THREAD

**Issue by valuesoft-dk** [AzureAD/microsoft-authentication-library-for-js#463]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version 69
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 0.2.3

How to get more information about the B2C-signed in user ?

For instance what groups the user is member of ?
Or any of the other things you can do with
https://graph.microsoft.com and https://graph.windows.net ?

Is it possible to use the B2C token, in one way or another, to retrieve another type of token,
i.e. an access token for one of these two endpoints ?
</code></pre>

**Comment by pkanher617** [comment]
@valuesoft-dk you should be able to use the B2C token as any other id token obtained from AzureAD to read user information from graph. There may be some claims differences. The full documentation can be viewed here:
https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-reference-tokens

**Comment by himadrinath** [comment]
@valuesoft-dk did you able to obtain graph token using b2c token. i tried but not success

**Comment by nehaagrawal** [comment]
@parakhj can you please help here.

**Comment by valuesoft-dk** [comment]
@parakhj thanks, I have already long time ago read that article and I can use the ADAL client side library for that and so on. But I'm using the MSAL client side library to authenticate and then I have a B2C token. How can I use that token to get an access token for Graph API ? (without authenticating twice).

**Comment by parakhj** [comment]
As mentioned earlier, the B2C token is useless for the Graph API. B2C tokens don't allow you to talk to the graph API. You need to spin up another application (a service application) which uses ADAL (or MSAL) to acquire an AAD token. You can use that to talk to the Graph API. 

You don't need to authenticate twice in that case because the service app should be using the confidential client flow (essentially using a client ID and client secret) to get the AAD token

**Comment by visualjeff** [comment]
```
//If the user has authenticated...
userAgentApplication.acquireTokenSilent(graphAPIScopes).then(function (token) {
    //After token is acquired, call the Graph API, using the acquired token
}
```

**Comment by navyasric** [comment]
@valuesoft-dk Please let us know if the pattern explained in the above comment resolved your issue.

**Comment by valuesoft-dk** [comment]
Yes, I can see the idea, so I will put that into practice. Thanks
