### ISSUE TITLE
GetTokenCache not recongnized as a function

### ISSUE THREAD

**Issue by ElSpitfire** [AzureAD/microsoft-authentication-library-for-js#4630]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.3.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

none

### Description

Hi,

I am trying to follow this tutorial : https://docs.microsoft.com/fr-fr/graph/tutorials/node

unfortunatly i am running into an error that is telling me that GetTokenCache is not a function

I ran into this error because i added an other parameter in the GetAuthenticatedClient function in the Auth.js script.

I dont understand what is going on here...

Is something in the tutorial wrong or is it me that made a mistake ?

fairly new to this... Any help would be appreciated 

### Error Message

{"stack":"TypeError: msalClient.GetTokenCache is not a function\n    at CustomAuthenticationProvider.authProvider [as provider] (C:\\Users\\acharlet\\Desktop\\NEOIDCG\\neoidcg\\graph.js:30:12)\n    at C:\\Users\\acharlet\\Desktop\\NEOIDCG\\neoidcg\\node_modules\\@microsoft\\microsoft-graph-client\\lib\\src\\CustomAuthenticationProvider.js:42:31\n    at new Promise (<anonymous>)\n    at CustomAuthenticationProvider.<anonymous> (C:\\Users\\acharlet\\Desktop\\NEOIDCG\\neoidcg\\node_modules\\@microsoft\\microsoft-graph-client\\lib\\src\\CustomAuthenticationProvider.js:41:39)\n    at step (C:\\Users\\acharlet\\Desktop\\NEOIDCG\\neoidcg\\node_modules\\tslib\\tslib.js:143:27)\n    at Object.next (C:\\Users\\acharlet\\Desktop\\NEOIDCG\\neoidcg\\node_modules\\tslib\\tslib.js:124:57)\n    at C:\\Users\\acharlet\\Desktop\\NEOIDCG\\neoidcg\\node_modules\\tslib\\tslib.js:117:75\n    at new Promise (<anonymous>)\n    at Object.__awaiter (C:\\Users\\acharlet\\Desktop\\NEOIDCG\\neoidcg\\node_modules\\tslib\\tslib.js:113:16)\n    at CustomAuthenticationProvider.getAccessToken (C:\\Users\\acharlet\\Desktop\\NEOIDCG\\neoidcg\\node_modules\\@microsoft\\microsoft-graph-client\\lib\\src\\CustomAuthenticationProvider.js:38:24)","message":"msalClient.GetTokenCache is not a function","statusCode":-1,"code":"TypeError","requestId":null,"date":"2022-03-25T09:18:47.263Z","body":"TypeError: msalClient.GetTokenCache is not a function"}

### MSAL Configuration

```javascript
// MSAL config
const msalConfig = {
  auth: {
    clientId: process.env.OAUTH_APP_ID,
    authority: process.env.OAUTH_AUTHORITY,
    clientSecret: process.env.OAUTH_APP_SECRET
  },
  system: {
    loggerOptions: {
      loggerCallback(loglevel, message, containsPii) {
        console.log(message);
      },
      piiLoggingEnabled: false,
      logLevel: msal.LogLevel.Verbose,
    }
  }
};
```

### Relevant Code Snippets

```javascript
var graph = require('@microsoft/microsoft-graph-client');
require('isomorphic-fetch');

module.exports = {
  getUserDetails: async function(msalClient, userId) {
    const client = getAuthenticatedClient(msalClient, userId);

    const user = await client
      .api('/me')
      .select('displayName,mail,mailboxSettings,userPrincipalName')
      .get();
    return user;
  },
};

function getAuthenticatedClient(msalClient, userId) {
  if (!msalClient || !userId) {
    throw new Error(
      `Invalid MSAL state. Client: ${msalClient ? 'present' : 'missing'}, User ID: ${userId ? 'present' : 'missing'}`);
  }

  // Initialize Graph client
  const client = graph.Client.init({
    // Implement an auth provider that gets a token
    // from the app's MSAL instance
    authProvider: async (done) => {
      try {
        // Get the user's account
        const account = await msalClient
          .GetTokenCache()
          .getAccountByHomeId(userId);

        if (account) {
          // Attempt to get the token silently
          // This method uses the token cache and
          // refreshes expired tokens as needed
          const response = await msalClient.acquireTokenSilent({
            scopes: process.env.OAUTH_SCOPES.split(','),
            redirectUri: process.env.OAUTH_REDIRECT_URI,
            account: account
          });

          // First param to callback is the error,
          // Set to null in success case
          done(null, response.accessToken);
        }
      } catch (err) {
        console.log(JSON.stringify(err, Object.getOwnPropertyNames(err)));
        done(err, null);
      }
    }
  });

  return client;
}
```

### Reproduction Steps

Just follow the tutorial, i got this ussies on 2 diffrent computer

### Expected Behavior

The Msal client should get some user infomation 

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@ElSpitfire Can you try `getTokenCache` instead of `GetTokenCache`? Also, can you show where you are instantiating the `msalClient`?

**Comment by ElSpitfire** [comment]
Hi,

Thank you for your response.
I tried what you said and the result is the same.

This script is called in an other script called auth.js
on the line 45 i duplicated the Response.accessToken to get through the "if" condition in the previous script with the getTokenCache error then this error showed up

Here is the code you asked for :

const graph = require('../graph');
const router = require('express-promise-router')();

/* GET auth callback. */
router.get('/signin',
  async function (req, res) {
    const urlParameters = {
      scopes: process.env.OAUTH_SCOPES.split(','),
      redirectUri: process.env.OAUTH_REDIRECT_URI
    };

    try {
      const authUrl = await req.app.locals
        .msalClient.getAuthCodeUrl(urlParameters);
      res.redirect(authUrl);
    }
    catch (error) {
      console.log(`Error: ${error}`);
      req.flash('error_msg', {
        message: 'Error getting auth URL',
        debug: JSON.stringify(error, Object.getOwnPropertyNames(error))
      });
      res.redirect('/');
    }
  }
);

router.get('/callback',
  async function(req, res) {
    const tokenRequest = {
      code: req.query.code,
      scopes: process.env.OAUTH_SCOPES.split(','),
      redirectUri: process.env.OAUTH_REDIRECT_URI
    };

    try {
      const response = await req.app.locals
        .msalClient.acquireTokenByCode(tokenRequest);

      // Save the user's homeAccountId in their session
      req.session.userId = response.account.homeAccountId;
      //console.log(response.account.homeAccountId);
      //console.log(response.accessToken);

      const user = await graph.getUserDetails(response.accessToken, response.accessToken);

      // Add the user to user storage
      req.app.locals.users[req.session.userId] = {
        displayName: user.displayName,
        email: user.mail || user.userPrincipalName,
        timeZone: user.mailboxSettings.timeZone
      };
    } catch(error) {
      req.flash('error_msg', {
        message: 'Error completing authentication',
        debug: JSON.stringify(error, Object.getOwnPropertyNames(error))
      });
    }

    res.redirect('/');
  }
);

router.get('/signout',
  async function(req, res) {
    // Sign out
    if (req.session.userId) {
      // Look up the user's account in the cache
      const accounts = await req.app.locals.msalClient
        .getTokenCache()
        .getAllAccounts();

      const userAccount = accounts.find(a => a.homeAccountId === req.session.userId);

      // Remove the account
      if (userAccount) {
        req.app.locals.msalClient
          .getTokenCache()
          .removeAccount(userAccount);
      }
    }

    // Destroy the user's session
    req.session.destroy(function (err) {
      res.redirect('/');
    });
  }
);

module.exports = router;


Thank you in advance

**Comment by sameerag** [comment]
@ElSpitfire I do not see `msalClient` being initialized in the above code. It is only fetched from the `req.app.locals` instead. `getTokenCache()` is an API exposed under the instance of `msalClient` and hence can you check if `msalClient` is accessible at the place where you are invoking `getTokenCache`?

If possible, can you upload the relevant code sample (may be dummy functional one) and share the link to us?

**Comment by ElSpitfire** [comment]
Thank you for your response.

 With your help and quit some time I solved the issue.

For thoses who are interested by this tutorial here is what you need to change :  

In the auth.js script search for this line :
const user = await graph.getUserDetails(response.accesToken);
and replace it by this one : 
const user = await graph.getUserDetails(req.app.locals.msalClient, req.session.userId);

First the fuction needs two argument
The argument in the first line is just the Token 
the first argument need to be an msalClient type
the function was trying to do response.accesToken.getTokencache() wich doesn't exist

thanks again
