### ISSUE TITLE
Providers.globalProvider.getAccessToken always makes an http call even if the token is present in the local storage.

### ISSUE THREAD

**Issue by ARsquare** [AzureAD/microsoft-authentication-library-for-js#4643]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.0.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

2.0.0

### Description

We are working on an app which uses MSAL for authentication. 
For getting the access token we are using the following function exposed by the library.
The issue is :-
Providers.globalProvider.getAccessToken always makes an http call even if the token is present in the local storage.

### Error Message

NA

### Msal Logs

NA

### MSAL Configuration

```javascript
clientId: AADDetails.BUDDH_CLIENT_AAD_ID,
scopes: [AADDetails.BUDDH_SERVICE_API_PERMISSION_NAME, 
    AADDetails.GRAPH_USER_READ_PERMISSION_NAME],
loginType: LoginType.Popup,
redirectUri: AADDetails.WEB_AUTH_REDIRECT_URI
```

### Relevant Code Snippets

```javascript
export function getAccessTokenForBuddhService (scopes?: Array<string>): Promise<string> {
    return Providers.globalProvider.getAccessToken({scopes});
}
```

### Reproduction Steps

https://user-images.githubusercontent.com/34487802/161037094-544250c6-2f8f-4cd0-962c-d09f86b05095.mp4

### Expected Behavior

Network call should not be made always

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge

### Regression

azure/msal-browser 2.0.0

### Source

Internal (Microsoft)

**Comment by sameerag** [comment]
@ARsquare Can you share your token `request` details? And turn on MSAL logs? For the first request, we go to the network (which is indicated by the loginType.popup in your code) and later expect your application to call `acquireTokenSilent` which pulls the tokens from cache and silently goes to the network in case of token expiry.

All our samples demonstrate this and can be accessed [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-browser-samples).
