### ISSUE TITLE
 Keep user signed in after the browser has been closed and 24 hours has expired in SPA

### ISSUE THREAD

**Issue by fan-boy** [AzureAD/microsoft-authentication-library-for-js#4662]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.15.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.1

### Description

We are using an Azure B2C Custom Policy to Sign Up/Sign In users using local account (Phone Number).

Currently Azure AD B2C issues a [refresh token](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/token-lifetimes.md) that is valid for 24 hours (non-configurable, non-renewable) for single page apps that use the PKCE code flow.

When that 24 hours is expired from the initial sign in the user needs to reauthenticate with the AD B2C. If the browser has been closed during that time the AD B2C session is lost and now user must interactively reauthenticate. 

Is there any way to work around this? Perhaps a way to make the AD B2C session persistent so that it survives browser closes and full interactive reauthentication is avoided. I have tried KMSI but that also dosent keep the user logged in for some reason. Have followed all the steps given in this [link](https://docs.microsoft.com/en-us/azure/active-directory-b2c/session-behavior?pivots=b2c-custom-policy#enable-keep-me-signed-in-kmsi).

### MSAL Configuration

```javascript
{
  auth: {
    clientId: AzureActiveDirectoryAppClientId,
    authority: b2cPolicies.authorities.signUpSignIn.authority, 
    knownAuthorities: [b2cPolicies.authorityDomain,b2cPolicies.authorities.forgotPassword.authority], 
    redirectUri: RedirectURI,  
    postLogoutRedirectUri: "/", 
    navigateToLoginRequestUrl: true,
    
  },
  cache: {
    cacheLocation: "localStorage",
    storeAuthStateInCookie: true,
  }
}
```

### Relevant Code Snippets

```javascript
<BasePolicy>
    <TenantId>*.onmicrosoft.com</TenantId>
    <PolicyId>B2C_1A_Phone_Email_Base</PolicyId>
  </BasePolicy>
  <RelyingParty>
    <DefaultUserJourney ReferenceId="PhoneSignInOnly" />
     <UserJourneyBehaviors>
      <SingleSignOn Scope="Tenant" KeepAliveInDays="90" />
      <SessionExpiryType>Rolling</SessionExpiryType>
      <SessionExpiryInSeconds>86400</SessionExpiryInSeconds>
    </UserJourneyBehaviors>
    <TechnicalProfile Id="PolicyProfile">
      <DisplayName>PolicyProfile</DisplayName>
      <Protocol Name="OpenIdConnect" />
      <OutputClaims>
        <OutputClaim ClaimTypeReferenceId="displayName" />
        <OutputClaim ClaimTypeReferenceId="givenName" />
        <OutputClaim ClaimTypeReferenceId="surname" />
        <OutputClaim ClaimTypeReferenceId="signInNames.phoneNumber" />
        <OutputClaim ClaimTypeReferenceId="signInNames.emailAddress" PartnerClaimType="email" />
        <OutputClaim ClaimTypeReferenceId="strongAuthenticationEmailAddress" />
        <OutputClaim ClaimTypeReferenceId="objectId" PartnerClaimType="sub" />
        <OutputClaim ClaimTypeReferenceId="objectId" PartnerClaimType="oid" />
        <OutputClaim ClaimTypeReferenceId="trustFrameworkPolicy" Required="true" DefaultValue="{policy}" />
        <OutputClaim ClaimTypeReferenceId="tenantId" AlwaysUseDefaultValue="true" DefaultValue="{Policy:TenantObjectId}" />
        <OutputClaim ClaimTypeReferenceId="kmsi" AlwaysUseDefaultValue="true" DefaultValue="{Context:KMSI}" />
      </OutputClaims>
      <SubjectNamingInfo ClaimType="sub" />
    </TechnicalProfile>
  </RelyingParty>
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by ellymakuba** [comment]
Pursuing this issue, I will revert to you

**Comment by fan-boy** [comment]
Okay.

**Comment by fan-boy** [comment]
Hi @ellymakuba . Any updates on this.

**Comment by ellymakuba** [comment]
Hello @fan-boy, This was identified as an issue with the B2C service. Please file a support ticket with the B2C team by following the instructions here: https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options. They can help you out further, they may ask for a public repro link or additional data. You can also link this Github issue in the support request.

**Comment by fan-boy** [comment]
Okay. Thanks @ellymakuba . Closing this issue.

**Comment by jasonklinke** [comment]
Having the same issue -- @ellymakuba is this a known bug?

React SPA using MSAL-react library with Azure AD B2C and KMSI (using Local Accounts).
cacheLocation is LocalStorage and the user stays logged in across tabs just fine, and also gets new Refresh Tokens fine within the first 24 hrs. 
But after 24 hrs user is forced to re-authenticate (acquireTokenSilent fails and is handled and we call acquireTokenRedirect) -- they are required to enter their credentials even though KMSI is configured for 90 days and the user selected KMSI when logging in.

Is this an issue with AD B2C or with MSAL?
