### ISSUE TITLE
msal-common's debug dependency part of production build

### ISSUE THREAD

**Issue by vlabensky** [AzureAD/microsoft-authentication-library-for-js#4663]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.22.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

-

### Description

Not sure whether it can be considered a bug, but I'll post it regardless.

We're using msal-browser in our SPA web app successfully and we've just noticed that the 'debug' library in our NPM package list has switched from 'dev=true' to 'dev=false'.

Quick investigation shows that 'msal-common' depends on 'debug' too. Searching the source code in this repo yields only two files where the 'debug' lib is used: `samples/msal-browser-samples/HybridSample/bin/www` and `lib/msal-common/src/logger/Logger.ts` (where it is commented out). So I assume the 'debug' lib has been used only during development and/or for tutorials.

We'd prefer not to include the 'debug' lib in our production build, so if the lib indeed is not used in production by msal, then I'd suggest marking it as "dev=true" in NPM.

Here's an excerpt from our npm dependencies tree `npm list --all`:
```json
"@azure/msal-browser": {
  "version": "2.22.0",
  "from": "@azure/msal-browser@2.22.0",
  "resolved": "https://registry.npmjs.org/@azure/msal-browser/-/msal-browser-2.22.0.tgz",
  "dependencies": {
	"@azure/msal-common": {
	  "version": "6.1.0",
	  "from": "@azure/msal-common@6.1.0",
	  "resolved": "https://registry.npmjs.org/@azure/msal-common/-/msal-common-6.1.0.tgz",
	  "dependencies": {
		"debug": {
		  "version": "4.1.1",
		  "from": "debug@4.1.1",
		  "resolved": "https://registry.npmjs.org/debug/-/debug-4.1.1.tgz"
		}
	  }
	}
  }
}
```

### MSAL Configuration

```javascript
not applicable
```

### Relevant Code Snippets

```javascript
not applicable
```

### Reproduction Steps

1. Instal 'debug' via NPM: `npm install debug --only=dev`
Observe `package-lock.json`:
```json
{
  "requires": true,
  "lockfileVersion": 1,
  "dependencies": {
    "debug": {
      "version": "4.3.4",
      "resolved": "https://registry.npmjs.org/debug/-/debug-4.3.4.tgz",
      "integrity": "sha512-PRWFHuSU3eDtQJPvnNY7Jcket1j0t5OuOsFzPPzsekD52Zl8qUfFIPEiswXqIvHWGVHOgX+7G/vCNNhehwxfkQ==",
      "dev": true,
      "requires": {
        "ms": "2.1.2"
      }
    },
    "ms": {
      "version": "2.1.2",
      "resolved": "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz",
      "integrity": "sha512-sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==",
      "dev": true
    }
  }
}
```
2. Install '@azure/msal-browser' via NPM: `npm i @azure/msal-browser`.
Observe `package-lock.json`:
```json
{
  "requires": true,
  "lockfileVersion": 1,
  "dependencies": {
    "@azure/msal-browser": {
      "version": "2.22.1",
      "resolved": "https://registry.npmjs.org/@azure/msal-browser/-/msal-browser-2.22.1.tgz",
      "integrity": "sha512-VYvdSHnOen1CDok01OhfQ2qNxsrY10WAKe6c2reIuwqqDDOkWwq1IDkieGHpDRjj4kGdPZ/dle4d7SlvNi9EJQ==",
      "requires": {
        "@azure/msal-common": "^6.1.0"
      }
    },
    "@azure/msal-common": {
      "version": "6.1.0",
      "resolved": "https://registry.npmjs.org/@azure/msal-common/-/msal-common-6.1.0.tgz",
      "integrity": "sha512-IGjAHttOgKDPQr0Qxx1NjABR635ZNuN7LHjxI0Y7SEA2thcaRGTccy+oaXTFabM/rZLt4F2VrPKUX4BnR9hW9g==",
      "requires": {
        "debug": "^4.1.1"
      }
    },
    "debug": {
      "version": "4.3.4",
      "resolved": "https://registry.npmjs.org/debug/-/debug-4.3.4.tgz",
      "integrity": "sha512-PRWFHuSU3eDtQJPvnNY7Jcket1j0t5OuOsFzPPzsekD52Zl8qUfFIPEiswXqIvHWGVHOgX+7G/vCNNhehwxfkQ==",
      "requires": {
        "ms": "2.1.2"
      }
    },
    "ms": {
      "version": "2.1.2",
      "resolved": "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz",
      "integrity": "sha512-sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w=="
    }
  }
}
```

Notice how `"dev": true` property disappears on 'debug' lib after installing 'msal-browser'.

### Expected Behavior

Expected: 'debug' lib remains as dev dependency.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Other

### Source

External (Customer)

**Comment by ellymakuba** [comment]
Looking into this, will get back to you

**Comment by ellymakuba** [comment]
I have made a PR to fix the issue, waiting for changes to be merged
