### ISSUE TITLE
Fix for multiple reload of application

### ISSUE THREAD

**Issue by roopeshchinnakampalli** [AzureAD/microsoft-authentication-library-for-js#4664]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.15.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.4

### Description

Let's say, our redirectURI is configured to - **http://localhost:4200** and we're kicking the Authentication (by MSALGuard) in the route - **http://localhost:4200/myprofile** and we set the option - **"navigateToLoginRequestUrl": true**

Now, we see the application loads twice - 

1. After redirecting 
2. It's navigating to the desired route.

As per this article, this is expected - [https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/performance.md#how-to-configure-azuremsal-angular-to-use-your-routers-navigate-function-for-client-side-navigation](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/performance.md#how-to-configure-azuremsal-angular-to-use-your-routers-navigate-function-for-client-side-navigation)

Is there any fix available for this? I mean use the Angular Router instead of window.location to avoid the second reload of the application

### MSAL Configuration

```javascript
auth: {
      authority: 'https://login.microsoftonline.com/xxx-xxx-xxx/',
      clientId: 'xxx-xxx-xxx-xxxx-xxx',
      redirectUri: 'http://localhost:4200',
      postLogoutRedirectUri: 'xxxx-xxx-xxx',
      navigateToLoginRequestUrl: true
    },
    cache: {
      cacheLocation: 'sessionStorage'
    },
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by ellymakuba** [comment]
Unfortunately this issue has not been addressed yet, as we have been unable to prioritize it.

**Comment by roopeshchinnakampalli** [comment]
Any idea when we gonna get this? This is causing an extra load on lower bandiwdth n/w's.

**Comment by jasonnutter** [comment]
@roopeshreddy Unfortunately, no. We found that using the Angular router resulted in the hash (containing the auth code) not being properly cleared, which is a security concern. And we have deprioritized finding a workaround.

**Comment by roopeshchinnakampalli** [comment]
@jasonnutter Thanks for the update! Unfortunately, we see the SPA loads (all assets downloads again) because of this. This is becoming a thing in low bandwidth areas and also in small form factors.

**Comment by jasonnutter** [comment]
@roopeshreddy If the provided navigation behavior does not suite your needs, you can implement your own. 

- Overview: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/navigation.md
- Example: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/src/msal.navigation.client.ts

For MSAL Angular, you can provide this by calling `this.msalService.instance.setNavigationClient(navigationClient)`.

**Comment by roopeshchinnakampalli** [comment]
Thanks @jasonnutter  This helps!
