### ISSUE TITLE
Incorrect Naming in Documentation

### ISSUE THREAD

**Issue by finalgriever** [AzureAD/microsoft-authentication-library-for-js#467]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Library version

<pre><code>
Library version: 0.2.3
</pre></code>

## Current behavior

Documentation in the msal-angular library suggests that the public APIs are named in a `snake_case` styling, such as `login_popup()`

## Expected behavior

The documentation should indicate the correct name of the APIs, which are camelCase, such as `loginPopup()`

## Minimal reproduction of the problem with instructions

Observe the documentation [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/README.md)

Observe the actual method names, as can be found [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/src/msal.service.ts#L291)

</code></pre>

**Comment by navyasric** [comment]
@finalgriever Thank you for pointing out the discrepancy. We have updated the Readme with the method names.
