### ISSUE TITLE
Additional parameters for Popup-Window

### ISSUE THREAD

**Issue by GoestaBergfeld** [AzureAD/microsoft-authentication-library-for-js#4681]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

Not Applicable

### Description

It would be great if we could pass some more parameters to the popup-Request. Currently we can only set the width and height per popupWindowAttributes but in addition we would like to control wheather the location-bar should be visible and if it's allowed to resize the popup window.

### Source

External (Customer)

**Comment by ellymakuba** [comment]
@GoestaBergfeld we will discuss this internally and get back to you

**Comment by sameerag** [comment]
@GoestaBergfeld We anticipate more problems with providing the ability to resize a popup to the user (we do not want more overhead of error handling). However, feel free to open a PR for adding the `location Bar` and we can consider this added to the MSAL popups.

We do not plan to make this enhancement ourselves right now.
