### ISSUE TITLE
How to configure scopes for own Web APIs?

### ISSUE THREAD

**Issue by siddarthapal** [AzureAD/microsoft-authentication-library-for-js#4685]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/msal-interceptor.md

### Description

Hello Documentation team

We are using MSAL authentication library for our Angular 13 Project. I am trying to understand how we can use MSAL Interceptor for passing tokens as per the documentation. We are not able to understand "how to configure scopes for custom APIs?"

As per my little understanding, we need to configure scope on Azure Portal where we generated the client id. 
Could you please arrange to clarify?

**Comment by siddarthapal** [comment]
This is request for missing stuff from the documentation, not for the Angular 13 compatible MSAL library. I see something being closed at the bottom so I am confused.

**Comment by siddarthapal** [comment]
This is the URL, I guess:-
https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-configure-app-expose-web-apis

It would be good, if we can add to documentation.

**Comment by ellymakuba** [comment]
That is the correct link, thank you. We will add that to our FAQ.

**Comment by siddarthapal** [comment]
> That is the correct link, thank you. We will add that to our FAQ.

As a consumer of this package, having  a link/reference at the location I mentioned would be far more helpful. I faced the issue and we can see the same. Everyone is not aware of all the things around Azure Authentication.

**Comment by jasonnutter** [comment]
@siddarthapal Fair feedback, we'll make sure that gets added.

**Comment by siddarthapal** [comment]
> @siddarthapal Fair feedback, we'll make sure that gets added.

THANK YOU VERY MUCH FOR YOUR CONSIDERATION. HOPE THIS WOULD HELPS OTHERS.
