### ISSUE TITLE
useIsAuthenticated returns true during logout process

### ISSUE THREAD

**Issue by prsauer** [AzureAD/microsoft-authentication-library-for-js#4689]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.23.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.3.2

### Description

Using `useIsAuthenticated` seems to produce unwanted behavior when `logout` is called. The user accounts array from `getAllAccounts()` is emptied before `isAuthenticated` becomes false. This leads to a situation where you can't rely on `isAuthenticated` as proof that there is a user account.

This seems unintuitive -- is this intended behavior?

### MSAL Configuration

```javascript
{}
```

### Relevant Code Snippets

```javascript
{}
```

### Reproduction Steps

{}

### Expected Behavior

{}

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@prsauer Can you please share relevant code snippets for how you are invoking logout and handling `useIsAuthenticated`?

**Comment by prsauer** [comment]
> @prsauer Can you please share relevant code snippets for how you are invoking logout and handling `useIsAuthenticated`?

From SignOutButton:
```
<button
  onClick={() => {
    instance.logoutRedirect();
  }}
>
```

Index page
UserInfo displays name+email of active account
```
          <AuthenticatedTemplate>
            <div>Logged in as</div>
            <UserInfo />
            <SignOutButton />
          </AuthenticatedTemplate>
          <UnauthenticatedTemplate>
            <Link href="/test">Go to test index</Link>
            <SignInButton />
          </UnauthenticatedTemplate>
```

**Comment by jasonnutter** [comment]
@prsauer Thanks. We recommend adding a check for `inProgress` to be `InteractionStatus.None`, which should catch intermediate states such as during the middle of logout.

**Comment by prsauer** [comment]
> @prsauer Thanks. We recommend adding a check for `inProgress` to be `InteractionStatus.None`, which should catch intermediate states such as during the middle of logout.

Where would I check that? Isn't that something the template would cover?

**Comment by jasonnutter** [comment]
@prsauer Apologies for the confusion, misread your code. When using `AuthenticatedTemplate`, it is expected that when a logout is initiated, it will continue to show the authenticated content until the interaction is complete. When using `useIsAuthenticated` directly, we recommend also looking at `inProgress` from [useMsal](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/hooks.md#usemsal-hook) and checking for `InteractionStatus.None`.

**Comment by prsauer** [comment]
> @prsauer Apologies for the confusion, misread your code. When using `AuthenticatedTemplate`, it is expected that when a logout is initiated, it will continue to show the authenticated content until the interaction is complete. When using `useIsAuthenticated` directly, we recommend also looking at `inProgress` from [useMsal](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/hooks.md#usemsal-hook) and checking for `InteractionStatus.None`.

Got it. So this would be the intended pattern:

```
function UserInfo() {
  const { instance, inProgress } = useMsal();
  

  if (inProgress !== InteractionStatus.None) {
    return <div>loading</div>;
  }

  const account = instance.getAllAccounts()[0];
  
  return (
    <>
      <div>{account.name}</div>
      <div>{account.username}</div>
```

**Comment by jasonnutter** [comment]
@prsauer Yes, correct.
