### ISSUE TITLE
Refresh auth token

### ISSUE THREAD

**Issue by madhumlr** [AzureAD/microsoft-authentication-library-for-js#469]
Does this library has refresh token functionality?

**Comment by pkanher617** [comment]
@madhumlr This library is for JS applications, which are typically single-page applications. As such, we use the implicit flow model of the OAuth protocol. The implicit grant flow does not issue refresh tokens, mainly for security reasons. 

More info can be found here: https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-oauth2-implicit-grant-flow

For the use cases where you require a refresh token, you can instead use a hidden iframe to make new token requests against the authN endpoint. As long as the browser's session is active, there will be no user interaction required.

**Comment by himadrinath** [comment]
@pkanher617  then how can we keep user logged in PWA application

**Comment by pkanher617** [comment]
@himadrinath are you using loginPopup or loginRedirect?

**Comment by pkanher617** [comment]
I recommend using loginPopup for PWA applications.

**Comment by himadrinath** [comment]
@pkanher617 loginPopup

**Comment by nehaagrawal** [comment]
@himadrinath  @pkanher617  already answered your question. Please don't reopen this issue. This is more of a how to question. Please use stack-overflow for such questions in future.
