### ISSUE TITLE
Blocked form submission because the form's frame is sandboxed and the 'allow-forms' permission is not set. 

### ISSUE THREAD

**Issue by sturano** [AzureAD/microsoft-authentication-library-for-js#4692]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

1.2.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

Hello,
after a Azure b2c login flow with external identity provider configurated on OpenID Connect, we get on console:
Blocked form submission to 'https://xxxxxxxx.b2clogin.com/xxxxxxxxx.onmicrosoft.com/oauth2/authresp' because the form's frame is sandboxed and the 'allow-forms' permission is not set. 
If the login on the same flow is made with user/password, it works properly.

Can you help us to solve it?

Thanks
Best regards

### Error Message

Blocked form submission to 'https://xxxxxxxx.b2clogin.com/xxxxxxxxx.onmicrosoft.com/oauth2/authresp' because the form's frame is sandboxed and the 'allow-forms' permission is not set. 

### Msal Logs

.

### MSAL Configuration

```javascript
{}
```

### Relevant Code Snippets

```javascript
<iframe id="msalRenewFrameopenid profile https://xxxxxxxxxxxxx.onmicrosoft.com/racweb/user_impersonation" sandbox="allow-scripts allow-same-origin" src="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" style="visibility: hidden; position: absolute; height: 0px; width: 0px; border: 0px;"></iframe>
```

### Reproduction Steps

1. authenticate with B2C LoginFlow with identity provider OpenID
2. access to angular app

### Expected Behavior

Login success

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge

### Source

External (Customer)

**Comment by ellymakuba** [comment]
Please update to MSALJS version 1.4.16 as this has been fixed in the latest version.

**Comment by jasonnutter** [comment]
Closing, as this was a known issue that has since been fixed in the latest version of MSAL.
