### ISSUE TITLE
acquireTokenSilent with MSAL.js giving error

### ISSUE THREAD

**Issue by ppagadala** [AzureAD/microsoft-authentication-library-for-js#4693]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.22.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

When trying to renew the token with acquireTokenSilent getting 400 status for "/token" call.

### Error Message

`{"error":"invalid_grant","error_description":"AADSTS700084: The refresh token was issued to a single page app (SPA), and therefore has a fixed, limited lifetime of 1.00:00:00, which cannot be extended. It is now expired and a new sign in request must be sent by the SPA to the sign in page. The token was issued on 2022-04-01T07:29:11.1319999+00:00.\r\nTrace ID: e0ce4356-03da-4b91-99f9-3c8efbad8b01\r\nCorrelation ID: dd0bd01d-ea85-4247-8233-cee2c9e56664\r\nTimestamp: 2022-04-08 11:53:29Z","error_codes":[700084],"timestamp":"2022-04-08 11:53:29Z","trace_id":"e0ce4356-03da-4b91-99f9-3c8efbad8b01","correlation_id":"dd0bd01d-ea85-4247-8233-cee2c9e56664","error_uri":"https://login.microsoftonline.com/error?code=700084","suberror":"bad_token"}`

### MSAL Configuration

```javascript
{
      auth: {
        redirectUri: 'http://localhost:4200/',
        clientId: '2936cadc-397f-453b-86e2-a1f94ee7a21f',
        navigateToLoginRequestUrl: false,
      },
      cache: {
        cacheLocation: BrowserCacheLocation.LocalStorage,
        storeAuthStateInCookie: true,
      },
    }
```

### Relevant Code Snippets

```javascript
constructor(config: GraphAPIClientConfig) {
    this.config = config;
    this.client = new PublicClientApplication({
      auth: {
        redirectUri: this.config.consentURI,
        clientId: this.config.clientId,
        navigateToLoginRequestUrl: false,
      },
      cache: {
        cacheLocation: BrowserCacheLocation.LocalStorage,
        storeAuthStateInCookie: true,
      },
    });
  }
initGraphAPI() {
    this.graphClient = Client.initWithMiddleware({
      authProvider: {
        getAccessToken: (data) => this.graphAPIClient.getToken(),
      },
      fetchOptions: {
        signal: this.controller.signal
      }
    });
  }

async getToken(): Promise<string | null> {
    if (localStorage.getItem('GRAPH_API_ACCESS_TOKEN') && localStorage.getItem('GRAPH_API_ACCESS_TOKEN_EXPIRE') && new Date(localStorage.getItem('GRAPH_API_ACCESS_TOKEN_EXPIRE') || Date.now()) > new Date()) {
      return localStorage.getItem('GRAPH_API_ACCESS_TOKEN');
    }

    let data;

    try {
      data = await this.client.acquireTokenSilent(this.silentRequest);
    } catch {
      data = await this.acquireTokenWithInteraction();
    }

    console.info(data);

    if (!data) {
      throw new Error('Unable to get token');
    }

    const { accessToken, account, expiresOn } = data;

    localStorage.setItem('GRAPH_API_ACCESS_TOKEN', accessToken);
    localStorage.setItem('GRAPH_API_ACCESS_TOKEN_EXPIRE', expiresOn instanceof Date ? expiresOn.toString() : expiresOn as string);
    localStorage.setItem('GRAPH_API_ACCOUNT', JSON.stringify(account));
    this.accessToken = accessToken;
    this.userAccountInfo = account as AccountInfo;
    this.accessTokenExpiry = expiresOn instanceof Date ? expiresOn : new Date(expiresOn as string);
    return this.accessToken;
  }
```

### Reproduction Steps

1. Initialise Graph client API with config
2. Have getToken method which returns triggers on every graph api request
3. Make token expired by changing the expireoOn time. 
4. Request for graph api service
5. Then the 'acquireTokenSilent' executes but return 400

### Expected Behavior

acquireTokenSilent should return new accessToken and refresh token.

Error:-

<img width="908" alt="Screenshot 2022-04-08 at 5 53 10 PM" src="https://user-images.githubusercontent.com/11500788/162434842-d259d953-c03d-4371-b067-bd7179695098.png">

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

Internal (Microsoft)

**Comment by ellymakuba** [comment]
Expected behavior and it will be handled by the library. Which you can see by the authorize call that happened after the failed call to the token endpoint.

**Comment by ppagadala** [comment]
@ellymakuba 
That is happening because we had **acquireTokenPopup** if the **acquireTokenSilent** fails. The acquireTokenSilent should return refreshToken once the accessToken expires?

**Comment by jasonnutter** [comment]
@ppagadala acquireTokenSilent will attempt to silently renew the access token (and refresh token, if that has expired, which happened here), and then return an error if that does not succeed. Can you please share a network trace and verbose logs from MSAL with me demonstrating the behavior shown in the screenshot above (email is in my profile)?

**Comment by hsalla923** [comment]
Hi Team, I see this issue still persists and has no solution yet I believe as per the comments. Can anyone please let me know if there has been any update or solution provided. Thank you!
