### ISSUE TITLE
MSAL Interceptor Configuration-Gap between Angular 13 sample and documentation

### ISSUE THREAD

**Issue by siddarthapal** [AzureAD/microsoft-authentication-library-for-js#4695]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/msal-interceptor.md

### Description

Following is the code from Angular 13 sample:-

export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
  const protectedResourceMap = new Map<string, Array<string>>();
  // protectedResourceMap.set('https://graph.microsoft.com/v1.0/me', ['user.read']); // Prod environment. Uncomment to use.
  protectedResourceMap.set('https://graph.microsoft-ppe.com/v1.0/me', ['user.read']);

  return {
    interactionType: InteractionType.Redirect,
    protectedResourceMap
  };
}
 and the documentation is 

@NgModule({
    declarations: [
        AppComponent,
    ],
    imports: [
        MsalModule.forRoot( new PublicClientApplication({
            // MSAL Configuration
        }), {
            // MSAL Guard Configuration
        }, {
            // MSAL Interceptor Configurations
            interactionType: InteractionType.Redirect,
            protectedResourceMap: new Map([ 
                ['Enter_the_Graph_Endpoint_Here/v1.0/me', ['user.read']]
            ])
        })
    ],
    providers: [
        {
            provide: HTTP_INTERCEPTORS, // Provides as HTTP Interceptor
            useClass: MsalInterceptor,
            multi: true
        },
        MsalGuard
    ],
    bootstrap: [AppComponent, MsalRedirectComponent]
})
export class AppModule { }

Two different ways  so bit confused with the same. I need to add my own end points so I need to add the following line?

 protectedResourceMap.set('https://localhost:8080/api', ['user.read']);

or I need to follow the old way?

**Comment by ellymakuba** [comment]
Both methods are valid, it just depends on whether you are using a factory method to set the interceptor configuration.

**Comment by siddarthapal** [comment]
Closing the issue....
