### ISSUE TITLE
Multiple configurations in a single SPA

### ISSUE THREAD

**Issue by KrzysztofJaneczko** [AzureAD/microsoft-authentication-library-for-js#4699]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.1.2

### Description

Hi! 

In the Angular app I currently develop, I've got a structure like this:
- admin
- module a
- module b

I've received a requirement that the admin section of the app should be protected by two factor authentication, but the rest of the app should only require login & password.

I assume I need two app registrations to achieve this.

My questions:
1. Is it possible to use multiple app registrations in a single app without conflicts between them?
2. I found nothing that would support that, but is it possible to achieve the above with a single app registration?

Cheers,
Krzysztof

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by jasonnutter** [comment]
> Is it possible to use multiple app registrations in a single app without conflicts between them?

I don't believe this is currently possible with MSAL Angular. 


> I found nothing that would support that, but is it possible to achieve the above with a single app registration?

I think this would be possible using a combination of the MSAL Guard and Conditional Access policies. You could setup the MSAL Guard on the admin part of the app to prompt the user to login, only allow users with the admin role to access it, and then require admin users to complete MFA via conditional access policy.

Enabling MFA via CA policies: https://docs.microsoft.com/azure/active-directory/authentication/tutorial-enable-azure-mfa

Azure RBAC: https://docs.microsoft.com/azure/role-based-access-control/overview

Example guard configuration:

```typescript
export function MSALGuardConfigFactory(): MsalGuardConfiguration {
  return { 
    interactionType: InteractionType.Redirect,
    authRequest: (authService, state) => {
        if (state.url.indexOf("/admin") > -1) {
            return {
                prompt: "login"
            }
        }

        return {
            //...
        }
    }
  };
}
```
