### ISSUE TITLE
acquireTokenSilent not working inside Teams app?

### ISSUE THREAD

**Issue by didair** [AzureAD/microsoft-authentication-library-for-js#470]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Other... Please describe:
Question
</code></pre>

## Browser:
- [ ] Chrome version XX
- [x] Firefox Developer Edition
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 0.2.3
</code></pre>

## Issue

When running the same app outside of Teams my app is able to runt the `acquireTokenSilent` get a token for the scopes and run API calls to the MS Graph API but once the app is in Teams, it doesnt seem to run the function acquireTokenSilent but acquireTokenPopup works.. Hopefully I'm missing something easy.

**Comment by didair** [comment]
Related to #222

**Comment by vedeevi** [comment]
@didair , Is this issue got resolved? as we are also having same issue in getting a token silently in Microsoft Teams Tabs....

**Comment by vedeevi** [comment]
@didair , Is this issue got resolved? as we are also having same issue in getting a token silently in Microsoft Teams Tabs....

**Comment by didair** [comment]
@vedeevi sadly not.. What i got from issue 222 was that "msal isnt designed for Teams" I'm currently in some support tickets with Microsoft and I'll get back when i have a clear method of authenticating and receiving access tokens

**Comment by nehaagrawal** [comment]
Closing this issue since this is already answered in https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/222
