### ISSUE TITLE
Not working "Syncing logged in state across tabs and windows". Do I need to set up anything?

### ISSUE THREAD

**Issue by Takas0522** [AzureAD/microsoft-authentication-library-for-js#4700]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.19.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

Even though I set it up as per [this document](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/events.md#syncing-logged-in-state-across-tabs-and-windows).
The logout process, etc. that I performed on another tab or window was not synchronized.

Is there any other configuration required other than what is described in the documentation?

## Reproduction Steps

1. Login with main tab or window.
2. Login with other tab or window.
    * At this time, login events are not synchronized on the main tab.
    * The tab where the login was performed was outputting the login event.
3. Logout with other tab or window.
    * At this time, logout events are not synchronized on the main tab.
    * The tab where the logout was performed was outputting the logout event.

## Msal Logs

Log when `enableAccountStorageEvents()` run.

`[Mon, 11 Apr 2022 10:59:45 GMT] : @azure/msal-browser@2.19.0 : Verbose - Adding account storage listener.`

### MSAL Configuration

```javascript
const loggerCallback = (level, message, containsPii) => {
  console.log({level, message, containsPii})
}

{
  auth: {
    clientId: 'xxxx',
    authority: 'https://login.microsoftonline.com/xxxx/'
  },
  system: {
    loggerOptions: {
      logLevel: 3, // Verbose
      loggerCallback
    }
  }
}
```

### Relevant Code Snippets

```html
<html>
  <head>
    <script type="text/javascript" src="https://alcdn.msauth.net/browser/2.19.0/js/msal-browser.min.js"></script>
  </head>
  <body>
    <button id="login">LOGIN</button>
    <button id="logout">LOGOUT</button>
    <script>
      const loggerCallback = (level, message, containsPii) => {
        console.log({level, message, containsPii})
      }
      const msalConfig = {
        auth: {
          clientId: 'xxx',
          authority: 'https://login.microsoftonline.com/xxxx/'
        },
        system: {
          loggerOptions: {
            logLevel: 3, // Verbose
            loggerCallback
          }
        }
      };
      const client = new msal.PublicClientApplication(msalConfig);
      client.enableAccountStorageEvents();
      client.addEventCallback(message => {
        console.log(message)
      });
      const login = document.getElementById('login')
      login.onclick = async () => {
        const res = await client.loginPopup();
        console.log(res);
      }

      const logout = document.getElementById('logout')
      logout.onclick = async () => {
        client.logout();
        // await client.logoutRedirect();
      }

    </script>
  </body>
</html>
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by Takas0522** [comment]
`<script type="text/javascript" src="https://alcdn.msauth.net/browser/2.23.0/js/msal-browser.min.js"></script>`
Version `2.23.0` had the same result

**Comment by jasonnutter** [comment]
@Takas0522 If your `msalConfig` object, you will need to set `cache.cacheLocation` to `localStorage` in order to share MSAL cache across tabs and windows.

**Comment by Takas0522** [comment]
Changing `cache.cacheLocation` to localStorage did not change the situation, but if I was SSO Login, the results were as expected.

I understand that the process is based on [this documents](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-sso#sso-between-browser-tabs) function.
Thanks for the very good advice--that solves it!
