### ISSUE TITLE
Performance issues after msal-react update caused by a lot of hook changes

### ISSUE THREAD

**Issue by matzehecht** [AzureAD/microsoft-authentication-library-for-js#4701]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.22.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.3.1

### Description

Since upgrading from @azure/msal-browser v2.22.0 to v2.22.1 and from @azure/msal-react v1.3.0 to v1.3.1 my React App is terribly slow on each navigation. With some investigation (using [why-did-you-render](https://github.com/welldone-software/why-did-you-render)) I saw that a top-level component does a lot of re-renderings because the `useIsAuthenticated`-hook changes several times (I counted 45 times). The actual value of the hook does not change (only the ref of the object stored in the MsalContext changes). The same is true for other subcomponents that are using `useMsal`. Before updating those packages each of those hooks only changed one time per navigation (I should mention that I am using `react-router(-dom)` for routing).

Here the diff output reported by `why-did-you-render` (as mentioned such a ref change without value change happens several times): 
![image](https://user-images.githubusercontent.com/38589070/162764304-3f720e7c-eb01-40bb-a682-c1e988a0d4aa.png)

### MSAL Configuration

```javascript
{
  auth: {
    authority: `https://login.microsoftonline.com/${TENANT_ID}`,
    clientId: CLIENT_ID,
    navigateToLoginRequestUrl: false,
    postLogoutRedirectUri: '/auth/logout',
    redirectUri: '/',
  },
  cache: {
    cacheLocation: 'localStorage',
  },
};
```

### Relevant Code Snippets

```javascript
export function Pages() {
  const isAuthenticated = useIsAuthenticated();

  return (
    <Routes>
      <Route element={<LogoutPage />} path="auth/logout" />
      <Route element={<LoginPage />} path="auth" />
      <Route element={<LandingPage />} path="welcome" />
      <Route element={isAuthenticated ? <AuthorizedPagesWithSubRoutes /> : <LandingPage />} path="/*" />
    </Routes>
  );
}
```

### Reproduction Steps

1. Navigate on a page that uses a `@azure/msal-react`-hook

### Expected Behavior

The hooks of `@azure/msal-react` should not change so many times.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Regression

@azure/msal-browser 2.22.0 @azure/msal-react 1.3.0

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@matzehecht Do you think this is similar to behavior described here? https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/4477#issuecomment-1080891316

cc @tnorling

**Comment by matzehecht** [comment]
@jasonnutter Yes, I think this is the same behavior. In my project, I call the acquireToken function on each request to our backend. Such a request happens after almost every navigation (that's why I thought the issue has something to do with react-router/navigation... my colleague implemented this part...).

Until these changes, our implementation worked perfectly fine, as every call to the acquireToken functions caused one (or even no) hook change (I can test it tomorrow). Now every call causes at least several hook changes, even if the value of the state does not change (as described here https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/4477#issuecomment-1080253697).

**Comment by jasonnutter** [comment]
@matzehecht Thanks, we'll investigate and follow up if we need more information.

**Comment by jasonnutter** [comment]
I believe we have found the root cause of this issue, will have PR soon with a fix (which will land in our May release).

**Comment by matzehecht** [comment]
Thanks for the quick response. I am happy to test this as soon as the fix is released.
