### ISSUE TITLE
Msal returns graph api token, not authentication token

### ISSUE THREAD

**Issue by HakuTheWolfSpirit** [AzureAD/microsoft-authentication-library-for-js#4702]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

^2.23.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

I am having trouble with following the vue3-sample. When acquiring the token I get the token for the graph api only, which is not accepted by the backend. 

I have analyzed the token and the scope "User.Read" is always in the scp field.
![image](https://user-images.githubusercontent.com/35311793/162894818-f45da75b-21a4-4115-b7c1-60f12bb905cb.png)

Here is my header:
{
  "typ": "JWT",
  "nonce": "rBU3wzELLofWF0x0eAfRHJDGCpdQQR3G-t-f7iPjsfI",
  "alg": "RS256",
  "x5t": "jS1Xo1OWDj_52vbwGNgvQO2VzMc",
  "kid": "jS1Xo1OWDj_52vbwGNgvQO2VzMc"
}

It does not matter if I am using personal accounts or accounts from the organization. I get an 401 when verifying the token.

IDX10511: Signature validation failed. Keys tried: 'Microsoft.IdentityModel.Tokens.X509SecurityKey, KeyId: 'jS1Xo1OWDj_52vbwGNgvQO2VzMc', InternalId: 'jS1Xo1OWDj_52vbwGNgvQO2VzMc'. , KeyId: jS1Xo1OWDj_52vbwGNgvQO2VzMc
'

This is my appsettings for my web api
  "AzureAd": {
    "Instance": "https://login.microsoftonline.com/bc5ef6e5-1c58-48dc-8561-c1c47aa5e0ea/",
    "Domain": "patrickspiegel.onmicrosoft.com",
    "TenantId": "bc5ef6e5-1c58-48dc-8561-c1c47aa5e0ea",
    "ClientId": "4226c94f-86d6-4fde-ab7a-4a1e391a602c",
    "Audience": "00000003-0000-0000-c000-000000000000",
    "Authority": "https://login.microsoftonline.com/bc5ef6e5-1c58-48dc-8561-c1c47aa5e0ea/",
    "Issuer": "https://sts.windows.net/bc5ef6e5-1c58-48dc-8561-c1c47aa5e0ea/"
  },

### MSAL Configuration

```javascript
{
  auth: {
    authority: "https://login.microsoftonline.com/bc5ef6e5-1c58-48dc-8561-c1c47aa5e0ea",
    clientId: "4226c94f-86d6-4fde-ab7a-4a1e391a602c",
    redirectUri: "https://localhost:5002", // Must be registered as a SPA redirectURI on your app registration
    postLogoutRedirectUri: "https://localhost:5002", // Must be registered as a SPA redirectURI on your app registration
  }
  cache: {
    cacheLocation: "localStorage",
  },
  system: {
    loggerOptions: {
      loggerCallback: (level: LogLevel, message: string, containsPii: boolean) => {
        if (containsPii) {
          return;
        }
        switch (level) {
          case LogLevel.Error:
            console.error(message);
            return;
          case LogLevel.Info:
            console.info(message);
            return;
          case LogLevel.Verbose:
            console.debug(message);
            return;
          case LogLevel.Warning:
            console.warn(message);
            return;
          default:
            return;
        }
      },
      logLevel: LogLevel.Verbose,
    },
  },
}
```

### Relevant Code Snippets

```javascript
export async function aqquireToken(): Promise<string> {
  const instance = msalInstance;
  const redirectResponse = await instance.handleRedirectPromise();
  console.log(redirectResponse);
  if (redirectResponse !== null) {
    const accessToken = redirectResponse.accessToken;
    return accessToken;
  } else {
    // MSAL.js v2 exposes several account APIs, logic to determine which account to use is the responsibility of the developer
    const account = instance.getAllAccounts()[0];
    const accessTokenRequest: RedirectRequest = {
      scopes: [],
      account: account,
    };
    const accessTokenResponse = await instance.acquireTokenSilent(accessTokenRequest);
    const accessToken = accessTokenResponse.accessToken;
    return accessToken;
  }
}
```
```C#

services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
{
    Configuration.Bind("AzureAd", options);
}
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@Popeye4242 It looks like you are trying to validate a Microsoft Graph access token for your own resource, which is not allowed. Instead, you should register your resource in the Azure Portal, create custom scopes for that resource, and then request an access token for those scopes. 

More details here: https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-configure-app-expose-web-apis

Then update the settings in the web api to reflect the correct audience value.

You should then invoke `acquireTokenSilent` with the custom scope, e.g.

```typescript
const { accessToken } = instance.acquireTokenSilent({ scopes: [ "your-custom-scope" ] });
```

**Comment by HakuTheWolfSpirit** [comment]
Thank you for your suggestion @jasonnutter. After defining the scope I could successfully sign in.
