### ISSUE TITLE
MSAL Guard - URLS not working

### ISSUE THREAD

**Issue by siddarthapal** [AzureAD/microsoft-authentication-library-for-js#4704]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/msal-guard.md

### Description

Under section "Optional authRequest" there are links on "PopupRequest" and "RedirectRequest". they are not working. Could you please fix the same and help?

![image](https://user-images.githubusercontent.com/100094024/163044419-e193f3d8-f253-44f7-8a95-2797db4779db.png)

**Comment by jasonnutter** [comment]
@siddarthapal Thanks, I'll make sure those are fixed. You can find them both here: https://azuread.github.io/microsoft-authentication-library-for-js/ref/modules/_azure_msal_browser.html#popuprequest

**Comment by siddarthapal** [comment]
> @siddarthapal Thanks, I'll make sure those are fixed. You can find them both here: https://azuread.github.io/microsoft-authentication-library-for-js/ref/modules/_azure_msal_browser.html#popuprequest

Thank you very much for the timely reply.

**Comment by siddarthapal** [comment]
Closing the issue...
