### ISSUE TITLE
Hybrid SPA flow doesn't work in AD B2C

### ISSUE THREAD

**Issue by idbartosz** [AzureAD/microsoft-authentication-library-for-js#4707]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.8.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

0.0.0

### Description

In AD B2C setup while calling `acquireTokenByCode` with `enableSpaAuthorizationCode: true` option the response returns `code: undefined`. In contrast, for a tenant without AD B2C the code is normally returned.

I suspect that this might be related to the Microsoft Graph permissions. AD B2C supports only `offline_access` and `openid` while this SPA authorization code requires `user.read`. Please correct me if I'm wrong.

### MSAL Configuration

```javascript
{
  auth: {
    clientId: process.env.MSAL_CLIENT_ID,
    clientSecret: process.env.MSAL_CLIENT_SECRET,
    authority: https://sometenant.b2clogin.com/sometenant.onmicrosoft.com/B2C_1_signupsignin1,
    knownAuthorities: ["sometenant.b2clogin.com"],
  },
}
```

### Relevant Code Snippets

```javascript
msalInstance
    .acquireTokenByCode({...tokenRequest, enableSpaAuthorizationCode: true })
    .then((response) => {
      // code value is undefined
      const { code } = response;
      
      ...
    })
```

### Reproduction Steps

1. Provide proper MSAL configuration for AD B2C
2. call `getAuthCodeUrl` and redirect response
3. obtain code from the redirect response and call `acquireTokenByCode` with `enableSpaAuthorizationCode: true` option
4. response from `acquireTokenByCode` returns

```
{
  authority: 'https://sometenant.b2clogin.com/sometenant.onmicrosoft.com/b2c_1_signupsignin1/',
  uniqueId: 'b240b59e...',
  tenantId: '',
  scopes: [],
  account: { ... },
  idToken: 'eyJ0eXAiO...,
  idTokenClaims: { ... },
  accessToken: '',
  fromCache: false,
  expiresOn: null,
  correlationId: '3ca595c5-d824...',
  extExpiresOn: undefined,
  familyId: '',
  tokenType: '',
  state: '',
  cloudGraphHostName: '',
  msGraphHost: '',
  code: undefined
}
```

### Expected Behavior

The response from `acquireTokenByCode` should contain code.

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome

### Source

Internal/External (Microsoft)

**Comment by jasonnutter** [comment]
@idbartosz Support for the hybrid spa flow has not yet shipped for B2C. Will close this for now, and follow up when that support has been added (ETA TBD, unfortunately). cc @EmLauber

**Comment by jasonnutter** [comment]
I'll add a note to our docs that B2C has not added support yet.

**Comment by idbartosz** [comment]
Thanks @jasonnutter for a quick response, and looking forward to any updates on this 👍

**Comment by emilpalsson** [comment]
Any update on this? I haven't found any note in the docs that B2C has not added support yet, but it seems I still get no `code` from `acquireTokenByCode` with `enableSpaAuthorizationCode: true` on a B2C tenant. @jasonnutter @EmLauber
