### ISSUE TITLE
How to access ID Token for passing to web api project

### ISSUE THREAD

**Issue by siddarthapal** [AzureAD/microsoft-authentication-library-for-js#4716]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/msal-interceptor.md

### Description

One quick question. We are using MSAL for Angular 13. Instead of access token, we need to pass ID Token. I don't see any method in "MsalService" for the same. We have different methods.

Could you please arrange to answer the following:-
1: Does MSAL npm package somehow allows to get access to "ID Token"?
2: If Yes, any pointers you can provide?( I have raised this already to stack over flow. Also I don't see anything in FAQ also)

I asked question here as part of the dev team, you would be able to reply "Yes" or "No" quickly. :)

**Comment by jasonnutter** [comment]
@siddarthapal Unfortunately not, no. The interceptor we provide is only for attaching access tokens, as we believe this is the best practice for protecting web apis. You can write our own interceptor if our interceptor does not satisfy your requirements.

Can you detail why you are using ID tokens instead of access tokens? Are you looking for specific ID token claims (e.g. roles)?

**Comment by siddarthapal** [comment]
> @siddarthapal Unfortunately not, no. The interceptor we provide is only for attaching access tokens, as we believe this is the best practice for protecting web apis. You can write our own interceptor if our interceptor does not satisfy your requirements.
> 
> Can you detail why you are using ID tokens instead of access tokens? Are you looking for specific ID token claims (e.g. roles)?

We have a web api (in .NET Core) which connected to another web api (in .NET Core), which is build by another organization. For some reason, they are not using MSAL. They are using some other library and they are using ID Tokens. I have also read on MS Site that for authentication, its better to use Access Tokens not ID Tokens.

I discovered something in Angular 13 sample code. If I click "Login" button, I cant get access token . Please refer the following:-
```
ngOnInit(): void {
    this.msalBroadcastService.msalSubject$
      .pipe(
        filter((msg: EventMessage) => msg.eventType === EventType.LOGIN_SUCCESS),
      )
      .subscribe((result: EventMessage) => {
        console.log(result);
        const payload = result.payload as AuthenticationResult;
        **console.log('$$IDToken',payload.idToken);**
        console.log('$$AccessToken',payload.accessToken);
        this.authService.instance.setActiveAccount(payload.account);
      });
}
```
As per your comment, we cant access ID Tokens using MSAL. But if you check "AuthenticationResult" class, it has a property called  "idToken".

Could you please share your view on the above discovery/finding?

We need ID Tokens and we can write our own interceptor that's not an issue. Issue is how to get "ID Token" using MSAL library.

**Comment by jasonnutter** [comment]
@siddarthapal Correct, and it should also be called after calling `acquireTokenSilent`, which you can use in a custom interceptor.

**Comment by siddarthapal** [comment]
Closing this for now
