### ISSUE TITLE
Azure AD B2C: User can't login after login-page was open for  some time

### ISSUE THREAD

**Issue by mvpindev** [AzureAD/microsoft-authentication-library-for-js#4718]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.22.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.3.1

### Description

If a user leaves the login-page open for a few hours (or over night) they can't log in due to a 400 Bad Request Error.

If you click on "Sign In", a loading indicator is shown for a short amount of time, but nothing else happens afterwards.

This behaviour can be fixed by refreshing the whole login-page, but not every user will do that, without an indication on what went wrong.

![image](https://user-images.githubusercontent.com/49334712/163547314-44e1a45a-642e-40a5-adf5-3a856bf41aab.png)

Network Tab:
![image](https://user-images.githubusercontent.com/49334712/163547735-bfb87caf-8dbb-4282-b729-163913d4437e.png)
![image](https://user-images.githubusercontent.com/49334712/163547911-39a93507-5cf7-4d8c-96bb-701744c3f48a.png)

### Error Message

400 Bad Request

### MSAL Configuration

```javascript
"msalConfig": {
    "auth": {
      "clientId": "clientId",
      "authority": "https://tenant.b2clogin.com/tfp/tenant.onmicrosoft.com/B2C_1_login",
      "knownAuthorities": ["https://tenant.b2clogin.com"],
      "scopes": [
        "https://tenant.onmicrosoft.com/tenant.api/user_impersonate"
      ],
      "redirectUri": "http://localhost:3000"
    },
    "cache": {
      "cacheLocation": "localStorage",
      "storeAuthStateInCookie": false
    }
  },
```

### Relevant Code Snippets

```javascript
Error happens on the B2C Login Page, which is not part of the source code of the application
```

### Reproduction Steps

1. Leave B2C Login Page open for a few hours
2. Enter credentials
3. Click on "Sign In"
4. 400 - Bad Request

### Expected Behavior

There should be an indication what went wrong (like session expired, if thats the case)
An error message should be shown to the user, that is trying to log in

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by jasonnutter** [comment]
This was identified as an issue with the B2C service. Please file a support ticket with the B2C team by following the instructions here: https://docs.microsoft.com/azure/active-directory-b2c/support-options

They can help you out further, they may ask for a public repro link or additional data. You can also link this Github issue in the support request.
