### ISSUE TITLE
Refresh token fails to refresh after sometime

### ISSUE THREAD

**Issue by kaushalbcactus** [AzureAD/microsoft-authentication-library-for-js#4726]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.7.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

App functinality:-

1. We have node solution which fetches emails of 1 user(xyz@abc.com) using oauth code grant(https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow)  and then process and send email from same email id.
2. Token is obtained using delegated permission since application permission is not allowed by our organisation.
3. node solution needs to auto execute after every 15 min.

Current implementation:-
1. We manually login using user credentials to obtain authorization code and  then programmatically fetch refesh token and save in file then again use saved token and update refresh token in file to keep solution running after every 15 min without human intervention.

Problem:-
Solution works for some irregular interval of time like 6 or 8 hrs and then it fails to fetch.

Need assistance reason it is failing and can this method improved or there is some mistake that I am doing?
 

### Relevant Code Snippets

```javascript
async function readWriteBlobStorage(emailId, scopes) {
    //Get storage value.
    const blobServiceClient = await common.getBlobClient(constants.AZURE_CREDENTIALS.STORAGE_ACCOUNT_NAME, constants.AZURE_CREDENTIALS.STORAGE_ACCOUNT_KEY);
    const containerClient = blobServiceClient.getContainerClient(constants.AZURE_CREDENTIALS.STORAGE_CONTAINER_NAME);
    const blobClient = containerClient.getBlobClient(constants.AZURE_CREDENTIALS.BLOB_NAME);
    const downloadBlockBlobResponse = await blobClient.download();
    const storageBlob = JSON.parse(
        await streamToBuffer(downloadBlockBlobResponse.readableStreamBody)
    );
    log.info("Downloaded blob content:", storageBlob);
    //Get access token using refresh token.
    const code = storageBlob.refresh_token;
    const requestURI = "https://login.microsoftonline.com/" + constants.AZURE_CREDENTIALS.TENANTID + "/oauth2/v2.0/token";
    const headers = {
        "origin": "null"
    }
    const scope = scopes;
    const tokenrequest = {
        "client_id": constants.AZURE_CREDENTIALS.CLIENTID,
        "scope": scope,
        "grant_type": "refresh_token",
        "refresh_token": code,
        "code_verifier": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "Origin": headers
    }
    const token = await common.getAzureAccessToken(requestURI, headers, tokenrequest);
    //log.info(`Azure token value: ${token}`);
    const blobcontent = {
        "Account": emailId,
        "refresh_token": token.refresh_token
    }
    const appendBlobClient = containerClient.getBlockBlobClient(constants.AZURE_CREDENTIALS.BLOB_NAME);
    const uploadBlobResponse = await appendBlobClient.upload(JSON.stringify(blobcontent), JSON.stringify(blobcontent).length);
    log.info(`Upload block blob ${constants.AZURE_CREDENTIALS.BLOB_NAME} ${JSON.stringify(blobcontent)} successfully`, uploadBlobResponse.requestId);
    return token;
}
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by bmahall** [comment]
It is advised not to manually refresh the token as detailed above, instead the AcquireTokenSilent API ([Token Renewal] https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/token-lifetimes.md) should be used for refreshing a token when it's getting close to expiration. 

Besides, can you include the logic for getAzureAccessToken() for better understanding.
