### ISSUE TITLE
Manage tokenRefresh while using ConfidentialClientApplication 

### ISSUE THREAD

**Issue by Alekhyasingi** [AzureAD/microsoft-authentication-library-for-js#4731]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.8.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

Functionality: Migration to Oauth from basic authentication with offline_access. My application runs in background to retrieve and update data from O365. 

Implementation:
I am using msal.ConfidentialClientApplication to fetch the accessToken.

Problem: The accesstoken that I received expires after an hour as expected. But is there a way that I can refresh it . I see no refresh token is sent in AuthenticationResult. So do I need to refetch the accessToken every hour. 

Sample AuthResult format received:
{
  "authority": "https://login.microsoftonline.com/<tenantId>",
  "uniqueId": "",
  "tenantId": "",
  "scopes": [
    "https://outlook.office365.com/.default",
    "openid",
    "profile",
    "offline_access"
  ],
  "account": null,
  "idToken": "",
  "idTokenClaims": {},
  "accessToken": <Token>,
  "fromCache": false,
  "expiresOn": "",
  "correlationId": "",
  "extExpiresOn": "",
  "familyId": "",
  "tokenType": "Bearer",
  "state": "",
  "cloudGraphHostName": "",
  "msGraphHost": ""
}

Note : I am new to Azure. I might have missed some configurations too.

### MSAL Configuration

```javascript
auth: {
        clientId: '',
        authority: "https://login.microsoftonline.com/<tenantID>",
        clientSecret: ''
    }
```

### Relevant Code Snippets

```javascript
const config = {
    auth: {
        clientId: "",
        authority: "",
        clientSecret: ""
   } 
};
const cca = new msal.ConfidentialClientApplication(config);
const clientCredentialRequest = {
    scopes: ["https://outlook.office365.com/.default"],
};

const authResult  = await cca.acquireTokenByClientCredential(this.clientCredentialRequest);
```

### Source

External (Customer)

**Comment by hectormmg** [comment]
@Alekhyasingi thanks for your question. The `ConfidentialClientApplication.acquireTokenByClientCredential` method has internal token caching logic that will:

1. Return a valid (not expired) access token from the cache when it is available and
2. Silently refresh an expired access token when a valid (not expired) refresh token is available

Given that the Client credentials flow does not require user input or interaction (it uses a client application-owned secret), all token acquisitions will be "silent". The API will only go to the network when:

a) There is no access/refresh token pair matching the request
b) The access token expires

So you don't have to handle the refresh token yourself, the `acquireTokenByClientCredential` API will do it for you.

Please let us know if this resolves your question!

**Comment by Alekhyasingi** [comment]
Thankyou for your answer. So how do I acquire new accessToken once it expires, do I need to call `ConfidentialClientApplication.acquireTokenByClientCredential` method again to renew accessToken? 

Note: My tasks are running in the background and I am using another library to store this accessToken for further operations.

**Comment by Alekhyasingi** [comment]
using `ConfidentialClientApplication.acquireTokenByClientCredential`  is the solution for any kind of token retrieval , which includes even after expiry(refreshToken). Hence closing it.
