### ISSUE TITLE
Standard case with MsalInterceptor and MsalGuard causes error in component with multiple http calls before redirecting to login page

### ISSUE THREAD

**Issue by kjerstifagerholt** [AzureAD/microsoft-authentication-library-for-js#4732]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.20.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.1.0

### Description

I have configured an angular v13 app with Msallnterceptor and MsalGuard, following the examples in documentation. There's two pages in the app. The first makes one http call to get data from API and the second one makes two calls to the API. The app is configured with Redirect interaction type. 

One problem occurs when user have an old token. 
This only happens in the page where there's two http calls. 
When loading page with one call, everything works out and user gets automatically redirected to login page with not problems. 
However, in the second component with two separate http calls, I get an error message from the library "BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API”.

The browser will redirect to the login page but the error message will happen first. Because of a global error handler this will be shown to the user before the login page shows. 
It’s not causing any severe interruption for the user as the redirection always happens, but an error like that should not happen anyway. 

The app has implemented the MsalInterceptor, MsalGuard and MsalRedirectComponent as recommended in the documentation, so I wonder why this ends with an error because a case where you have multiple http calls on one page is not an edge case.  Should it have been a warning rather than an error or can I prevent this in some way?

Thanks. 

### MSAL Configuration

```javascript
auth: {
      clientId: "clientId",
      authority: https://login.microsoftonline.com/..`,
      redirectUri: "https://localhost:4200",
      postLogoutRedirectUri: `https://localhost:4200/logout`,
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE, // set to true for IE 11
    },
    system: {
      loggerOptions: {
        loggerCallback,
        piiLoggingEnabled: true,
        logLevel: LogLevel.Verbose
      }
    }
  });
```

### Relevant Code Snippets

app.module.ts:
```javascript
const isIE = window.navigator.userAgent.indexOf("MSIE ") > -1 || window.navigator.userAgent.indexOf("Trident/") > -1; // Remove this line to use Angular Universal

export function MSALInstanceFactory(appConfig: AppConfig): IPublicClientApplication {
..
}

export function MSALInterceptorConfigFactory(appConfig: AppConfig): MsalInterceptorConfiguration {
  const protectedResourceMap = new Map<string, Array<string>>();
  protectedResourceMap.set(backendUrl, backendScope);

  return {
    interactionType: InteractionType.Redirect,
    protectedResourceMap,
  };
}

export function MSALGuardConfigFactory(): MsalGuardConfiguration {
  return {
    interactionType: InteractionType.Redirect,
    authRequest: {
      scopes: ['user.read']
    },

  };
}

@NgModule({
  declarations: [
    AppComponent,
    PageWithOneCallComponent,
    PageWithTwoCallsComponent
  ],
  imports: [
    ...
    AppRoutingModule,
    HttpClientModule,
    MsalModule
  ],
  providers: [
    AppConfig,
    AppInitializer,
    { provide: APP_INITIALIZER, useFactory: initializeApp, deps: [AppInitializer], multi: true } ,
    {
      provide: HTTP_INTERCEPTORS,
      useClass: MsalInterceptor,
      multi: true
    },
    {
      provide: MSAL_INSTANCE,
      useFactory: MSALInstanceFactory,
      deps: [AppConfig]
    },
    {
      provide: MSAL_GUARD_CONFIG,
      useFactory: MSALGuardConfigFactory
    },
    {
      provide: MSAL_INTERCEPTOR_CONFIG,
      useFactory: MSALInterceptorConfigFactory,
      deps: [AppConfig]
    },
    { provide: HTTP_INTERCEPTORS, useClass: HttpErrorsInterceptor, multi: true },
    MsalService,
    MsalGuard,
    MsalBroadcastService
  ],
  bootstrap: [AppComponent, MsalRedirectComponent]
})
export class AppModule { }
```
From app-routing.modules.ts:
```javascript
const routes: Routes = [
  {
    path: '',
    redirectTo: 'one',
    pathMatch: 'full'
  },
  {

    path: 'one',
    component: PageWithOneCallComponent,
    canActivate: [MsalGuard]
  },
  {
    path: 'two',
    component: PageWithTwoCallsComponent,
    canActivate: [MsalGuard]
  }
}
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by bmahall** [comment]
@kjerstifagerholt It is advised to perform the token acquisition in the two http call scenario-sequentially, i.e. 
acquire the first token, once it's done, then acquire the second token. 

This error happens due to the async nature of handleRedirectPromise() and is in accordance with the design. 
Please let me know in case of any further questions.
