### ISSUE TITLE
Invalid_grant error when library calls auth endpoint with grant type of refresh_token

### ISSUE THREAD

**Issue by finbarw** [AzureAD/microsoft-authentication-library-for-js#4733]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.23.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

We have a client app deployed to an Azure Static Web app.

We are finding that, once an access token has expired, the library is hitting a 400 acquiring a new token. This is happening occasionally, when a user returns to the application after longer than an hour.

My understanding ([corroborated by Jo-arroyo's response to this post](https://githublab.com/repository/issues/AzureAD/microsoft-authentication-library-for-js/4613)) is that, with our configuration, the library should handle expired tokens / refreshing silently without the need for us to actively intervene and call acquireTokenSilent. Is that an incorrect reading or are we missing something from our configuration?

The response to the oauth2/v2.0/token request is as follows:

`{
    "error": "invalid_grant",
    "error_description": "AADSTS700084: The refresh token was issued to a single page app (SPA), and therefore has a fixed, limited lifetime of 1.00:00:00, which cannot be extended. It is now expired and a new sign in request must be sent by the SPA to the sign in page. The token was issued on 2022-04-21T10:34:13.1733745+00:00.\r\nTrace ID: 2f81e1be-a63b-40a7-bbb8-22fef8540800\r\nCorrelation ID: 45334818-e0dd-4b40-80e6-f77b383c951f\r\nTimestamp: 2022-04-22 11:41:14Z",
    "error_codes": [
        700084
    ],
    "timestamp": "2022-04-22 11:41:14Z",
    "trace_id": "2f81e1be-a63b-40a7-bbb8-22fef8540800",
    "correlation_id": "45334818-e0dd-4b40-80e6-f77b383c951f",
    "error_uri": "https://login.microsoftonline.com/error?code=700084",
    "suberror": "bad_token"
}`

We can see that the request grant type is refresh_token.

It may be worth noting that we're using the MSAL Guard to auth users accessing our route and we have no 'click to login' cta as part of our user / auth flow.

### MSAL Configuration

```javascript
{
            auth: {
                clientId: environment.azureAadClientId,
                authority: environment.azureAadAuthority,
                redirectUri: environment.clientBaseUrl
            },
            cache: {
                cacheLocation: 'localStorage',
                storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
            }
        }), {
            interactionType: InteractionType.Redirect, // MSAL Guard Configuration
            authRequest: {
                scopes: []
            }
        }, {
            interactionType: InteractionType.Redirect, // MSAL Interceptor Configuration
            protectedResourceMap: new Map([
                [`${environment.apiUrl}/${environment.apiPrefix}`, [environment.apiScope]]
            ])
        }
```

### Relevant Code Snippets

```javascript
const routes: Routes = [
    {path: "", component: StatusComponent, canActivate: [MsalGuard]},
    {path: "translation", component: TranslationComponent, canActivate: [MsalGuard]}
];
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by bmahall** [comment]
@chuckyOHare We expect that the server will return 400 error when refresh token expires. Through the Guard, MSAL can refresh access tokens silently as long as a refresh token is valid. 

When the refresh token expires, AcquireTokenSilent will throw InteractionRequiredError that signals to the application that they need to fallback to an Interactive token acquisition method. You can refer to [TokenLifetime](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/token-lifetimes.md#token-renewal) . 

Let me know in case of further questions.

**Comment by finbarw** [comment]
That's helfpul, thanks @bmahall. If we're not explicitly calling acquireTokenSilent, is there a recommended way to catch the resulting InteractionRequiredAuthError from the hidden iframe call?

**Comment by tnorling** [comment]
@chuckyOHare How is `acquireTokenSilent` being called, if not explicitly? Do you mean to say that you are using the Interceptor? If so, the Interceptor should handle the fallback with the interaction type you've specified in your Interceptor config.

**Comment by finbarw** [comment]
Thanks for clarifying @tnorling. Yes, we're using the interceptor with InteractionType.Redirect (see configuration above).

**Comment by tnorling** [comment]
@chuckyOHare It's a little unclear to me what you need from us. Can you please clarify?

**Comment by finbarw** [comment]
In that case, it seems possible that the fallback is not being handled correctly for us in some instances.

@bmahall suggests here that an interactive fallback is required when AcquireTokenSilent fails.
> When the refresh token expires, AcquireTokenSilent will throw InteractionRequiredError that signals to the application that they need to fallback to an Interactive token acquisition method. You can refer to [TokenLifetime](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/token-lifetimes.md#token-renewal) .

@tnorling you seem to be telling me that the `InteractionType.Redirect` option in the MSAL Interceptor configuration should handle this error with a redirect, is that right?

We're finding that, intermittently, rather than be redirected to sign in, the client app sometimes gets into an error state for a signed in user when the refresh token has expired (outlined above).

**Comment by tnorling** [comment]
@chuckyOHare 

> you seem to be telling me that the InteractionType.Redirect option in the MSAL Interceptor configuration should handle this error with a redirect, is that right?

This is correct.

> We're finding that, intermittently, rather than be redirected to sign in, the client app sometimes gets into an error state for a signed in user when the refresh token has expired (outlined above).

Can you please clarify what happens when your app gets into this error state? The error you shared above is coming from the network request (this is expected and you may see this printed to the browser console), however, the library catches this error internally and attempts to handle it silently. It will never be thrown back to the application but if the silent backup also fails a different error will be thrown back to your application (usually InteractionRequired, which is then handled by the Interceptor).

So with that said, my question is: are you just seeing the above error printed to the console/network logs or are you actually failing to acquire a token? If it's the former, that is expected and not an indication anything is wrong. If it's the latter please provide more details about what error is being thrown instead.

**Comment by finbarw** [comment]
Thanks for clarifying @tnorling. The issue is hard hard to replicate but I'm investigating further. I'll get back to you asap.

**Comment by finbarw** [comment]
I'm still looking into this, apologies for the delay. It only appears on our production environment and only every now and again so it's tricky to pin down. I will update asap.

**Comment by finbarw** [comment]
To elaborate what I mean by 'error state': 
During initialisation our application fetches job data from our api. This outgoing request requires an access token. The MSAL interceptor handles token acquisition for us. When reaching this error state, we see the invalid_grant error in the console and network trace, however **we never see the actual outgoing /jobs request (which triggers the token call) in the network tab**. The result is that our app loads no data. We have reason to believe that MSAL interceptor somehow resolves the promise without ever making the outgoing call, as we're seeing an unhandled error being thrown from further down the stack.
Note we never see an InteractionRequired error.
This is the promise which we believe is resolving early in these cases:
![image](https://user-images.githubusercontent.com/29379528/169847345-d7bd5ab4-6e7f-4090-b1ee-90d95fc2cc1e.png)
![image](https://user-images.githubusercontent.com/29379528/169853004-9cfc94c7-3224-4653-8cc6-59dbda8acc21.png)
I'm aware that rxjs toPromise is deprecated but can't quite figure out how that might lead to our issue. Any suggestions you can offer would be gratefully received.

**Comment by tnorling** [comment]
@chuckyOHare Could you please configure MSAL to output verbose level logs and share the logs here? That should give us a better clue as to what's happening.

**Comment by finbarw** [comment]
![image](https://user-images.githubusercontent.com/29379528/170011245-6dad3dc5-31cb-483c-8723-e3006084e26f.png)

.log file:
[logfile.log](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/8761847/logfile.log)

**Comment by eirikb** [comment]
We're seeing the same error message when doing 
```js
await msal.acquireTokenSilent({ scopes: ["User.Read"] });
```
The call works fine, and we get a token, but the error will be printed to console.
Not a big deal by itself, but we have global error handlers that pick it up and log + show error to user. Perhaps not the best pattern, but this is how it has been for a long time.

I'm struggling to reproduce the behavior, waiting (at least an hour) does not always trigger it, setting the system clock into the future does not trigger it, changing random expire-dates in storage does not trigger it.

**Comment by tnorling** [comment]
> The call works fine, and we get a token, but the error will be printed to console. Not a big deal by itself, but we have global error handlers that pick it up and log + show error to user. Perhaps not the best pattern, but this is how it has been for a long time.

You're going to have to work around this. As explained above, the error printing to the console is expected, and not something we can suppress. As long as you are successfully getting a token or a more descriptive error returned from the API itself everything is working as expected.

**Comment by eirikb** [comment]
> 

Got it. Thanks for the quick response. Our pattern is a bad one to begin with, just wasn't sure this was really expected. Now I know, and I will find a way to deal with it :slightly_smiling_face:

**Comment by finbarw** [comment]
Hi, our question has still not been answered. We're getting some push from the client to resolve the issue, I appreciate this may turn out to be an issue with our code, but we'd really appreciate your continued assistance!

**Comment by ghost** [comment]
This issue requires attention from the MSAL.js team and has not seen activity in **5 days**. @hectormmg please follow up.

**Comment by tnorling** [comment]
@chuckyOHare Apologies for letting this fall through the cracks. It appears the redirect interaction is invoked as expected and then your code immediately prints "no jobs found". I'm wondering if this may be due to [this line](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/48525cc579e3102a25ea0c1f9e7be6663368acb5/lib/msal-angular/src/msal.interceptor.ts#L105) not being awaited before returning. Ideally, since this is a redirect call, this promise should never resolve and instead the page would be redirected  before anything else happens. I wonder if you've tried the popup interaction type and if that works as expected? If so, this may be a bug on us in redirect cases and we can take a look at how we can fix this.

**Comment by finbarw** [comment]
Thanks @tnorling for your response, and apologies in return for my delay, I must confess I'd stopped checking this thread.
We'll look into your suggestion and get back to you.
