### ISSUE TITLE
Unable to read /me from MS Graph API even if authentication is successful

### ISSUE THREAD

**Issue by tscislo** [AzureAD/microsoft-authentication-library-for-js#4734]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

^2.22.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

^2.1.2

### Description

I'm trying to use your sample angular13-rxjs6-sample.
The only  code part I changed is to use your Prod environment clientId.
When I try to authenticate either using my company account or private this is successful. 
However when I try to read my profile from Graph API i alwyas get: 401
```
{"error":{"code":"InvalidAuthenticationToken","message":"Signing key is invalid.","innerError":{"date":"2022-04-24T11:21:25","request-id":"aa252c65-853c-4341-ad6b-858b41990d2f","client-request-id":"aa252c65-853c-4341-ad6b-858b41990d2f"}}}
```

What am I doing wrong? 
When I tried to use my own Azure AD with my own registered application I get the same error.

### MSAL Configuration

```javascript
clientId: '6226576d-37e9-49eb-b201-ec1eeb0029b6', // Prod enviroment. Uncomment to use.
// clientId: '3fba556e-5d4a-48e3-8e1a-fd57c12cb82e', // PPE testing environment
authority: 'https://login.microsoftonline.com/common', // Prod environment. Uncomment to use.
// authority: 'https://login.windows-ppe.net/common', // PPE testing environment.
redirectUri: '/',
postLogoutRedirectUri: '/'
```

### Source

External (Customer)

**Comment by hectormmg** [comment]
Hi, @tscislo. Could you please provide the code you're using to actually request the token (the request and the acquireToken call)? Also, if you could show the way you're making the graph request (i.e. appending the token to the headers) that could be helpful.

This seems like an access or configuration issue that may be unrelated to the actual token acquisition by MSAL, which seems to be working fine since you're getting an access token.

**Comment by tscislo** [comment]
Hi @hectormmg !
I'm using your sample application: https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/typescript-sample

For which the only thing I changed is authConfig to

```
export const msalConfig: Configuration = {
    auth: {
        clientId: '6226576d-37e9-49eb-b201-ec1eeb0029b6', // Prod enviroment. Uncomment to use.
        authority: 'https://login.microsoftonline.com/common', // Prod environment. Uncomment to use.
        redirectUri: "/",
        postLogoutRedirectUri: "/"
    }
};
```

Since I cannot use this authority: https://login.windows-ppe.net/common I changed it to https://login.microsoftonline.com/common and I'm using 6226576d-37e9-49eb-b201-ec1eeb0029b6 that I found in one of the Angular samples in your samples folder.

**Comment by tnorling** [comment]
@tscislo When switching off PPE you also need to update the `graphMeEndpoint` config in the same file to `https://graph.microsoft.com/v1.0/me`. Can you try that and let me know if that works?
