### ISSUE TITLE
Access Token Returned with non-ascii characters 

### ISSUE THREAD

**Issue by mustafaAly** [AzureAD/microsoft-authentication-library-for-js#4738]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.8.0

### Wrapper Library

MSAL Node Extensions (@azure/msal-node-extensions)

### Wrapper Library Version

1.8.0

### Description

I tried to authenticate with my electron desktop app with azureAD using Azure/msal/node V 1.8.0 and it successfully returned the access token and id token but when I use this access token for authentication with graph API  it seems to be the token contains the non-ASCII character '...'   and the authentication goes fail 
the returned access token like 
EwBwA8l6BAAUkj1NuJYtTVha+Mogk+HEiPbQo04AATXZ9EjId9OhuFen52jzR/bc3Nn5S8xnSJGDmmVQ04VJPgRQNYMZva5NCPzHv6NTKMntR1YBDlv4XJ8ekIHjKQwyGm4r8BH/oyMksgllMqbbYUJCmQB4NaDJq0POOI8dFVlTY3C3iNj5wW2vYMPiOgimXTg1MFMBOzdEFcUrkpg8wlrtIOjrySTvCFSd+VRzo3HhXR/vps8K4D+SaFblJUGIK0En09OwHPQMnP1ZDyOVElZtPoVCBbNUliywoPHqIRjVNJ7ZtXuGEUyqF2k1yPoi2sVT9HKb8YmTvXP0PBZiWJc5mybxKQJaAFFBqCTB6bRFpTnMCzUinNOLDpaxvIIDZgAACHwVk71OM1paQALdvct5FG+gU+6QYODZYZarUmuqNr7rgwW5YGS684GmWgjXiUoVeebESMPbhh6Cgq+XeKJuDQst/H9MzIHt3+Eyx6xGcu986i7…uTv8V6ELrdfSEVw2NlVuH8cOfuS18Bbtda/zTxsoXnGjkSmdUe0IHi/yjJywz+ShDXwmomZu2lUwI87p1xxDV8HL2xdQWU0kL9JOUVSszlOrTChc3hciBqk68z+ajd6vVhFdEXc0GCMlNOfF5XWYufq3/qJPagGvLxVKQ5Z/9LNPjEs4JI0NdSfTrS+1yCpUeJmd8J9gPySIKy7vWWtexX/ISlFgBszmDL0Zy7oSIRKxJ8sMY6qjiEiLlCZB/qItnWHZ6jCFnX0Mmu+keIN5XiF70NzJbTdb0cV9GPjhGDkk+xBiGA77ng3+5vYws3g4wkNZX6efZ7Re1H3bfFCelzW8IhHeAc1/lIsNMBRMyQUY4WOfRcG1jfNI9CT7SchBOhu68fmCHgZ65g2lTDMJgzEeZ7o50hi9vd6zYSPgZ94470XkjKaNBE87Z/HJInFcKFvcUFJxX13uzWykeTU==

### MSAL Configuration

```javascript
const MSAL_CONFIG = {
	auth: {
		clientId: "xxxxxx",
		authority: `https://login.microsoftonline.com/common/`,
	},
	system: {
		loggerOptions: {
			loggerCallback(loglevel, message, containsPii) {
				console.log(message);
			},
			piiLoggingEnabled: false,
			logLevel: LogLevel.Verbose,
		}
	}
};
```

### Relevant Code Snippets

```javascript
const MSAL_CONFIG = {
	auth: {
		clientId: "xxxxxx",
		authority: `https://login.microsoftonline.com/common/`,
	},
	system: {
		loggerOptions: {
			loggerCallback(loglevel, message, containsPii) {
				console.log(message);
			},
			piiLoggingEnabled: false,
			logLevel: LogLevel.Verbose,
		}
	}
};
	constructor() {
		/**
		 * Initialize a public client application. For more information, visit:
		 * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/initialize-public-client-application.md
		 */
		this.clientApplication = new PublicClientApplication(MSAL_CONFIG);
		this.account = null;

		// Initialize CryptoProvider instance
		this.cryptoProvider = new CryptoProvider();

		this.setRequestObjects();
	}
	setRequestObjects() {
		const requestScopes = [
			'openid',
			'profile',
			'User.Read'
		];
		const redirectUri = "msal://redirect";

		this.authCodeUrlParams = {
			scopes: requestScopes,
			redirectUri: redirectUri
		};

		this.authCodeRequest = {
			scopes: requestScopes,
			redirectUri: redirectUri,
			code: null
		}

		this.pkceCodes = {
			challengeMethod: "S256", // Use SHA256 Algorithm S256 RS256 
			verifier: "", // Generate a code verifier for the Auth Code Request first
			challenge: "" // Generate a code challenge from the previously generated code verifier
		};
	}
	async getTokenInteractive(authWindow, tokenRequest) {

		/**
		 * Proof Key for Code Exchange (PKCE) Setup
		 *
		 * MSAL enables PKCE in the Authorization Code Grant Flow by including the codeChallenge and codeChallengeMethod parameters
		 * in the request passed into getAuthCodeUrl() API, as well as the codeVerifier parameter in the
		 * second leg (acquireTokenByCode() API).
		 *
		 * MSAL Node provides PKCE Generation tools through the CryptoProvider class, which exposes
		 * the generatePkceCodes() asynchronous API. As illustrated in the example below, the verifier
		 * and challenge values should be generated previous to the authorization flow initiation.
		 *
		 * For details on PKCE code generation logic, consult the
		 * PKCE specification https://tools.ietf.org/html/rfc7636#section-4
		 */

		const { verifier, challenge } = await this.cryptoProvider.generatePkceCodes();

		this.pkceCodes.verifier = verifier;
		this.pkceCodes.challenge = challenge;

		const authCodeUrlParams = {
			...this.authCodeUrlParams,
			scopes: tokenRequest.scopes,
			codeChallenge: this.pkceCodes.challenge, // PKCE Code Challenge
			codeChallengeMethod: this.pkceCodes.challengeMethod // PKCE Code Challenge Method
		};

		const authCodeUrl = await this.clientApplication.getAuthCodeUrl(authCodeUrlParams);

		protocol.registerFileProtocol("msal", (req, callback) => {
			const requestUrl = url.parse(req.url, true);
			callback(path.normalize(`${__dirname}/${requestUrl.path}`));
		});

		const authCode = await this.listenForAuthCode(authCodeUrl, authWindow);

		const authResponse = await this.clientApplication.acquireTokenByCode({
			...this.authCodeRequest,
			scopes: tokenRequest.scopes,
			code: authCode,
			codeVerifier: this.pkceCodes.verifier // PKCE Code Verifier
		});

		return authResponse;
	}


	async login(authWindow) {
		const authResult = await this.getTokenInteractive(authWindow, this.authCodeUrlParams);
		return this.handleResponse(authResult);
	}
```

### Reproduction Steps

const MSAL_CONFIG = {
	auth: {
		clientId: "xxxxxx",
		authority: `https://login.microsoftonline.com/common/`,
	},
	system: {
		loggerOptions: {
			loggerCallback(loglevel, message, containsPii) {
				console.log(message);
			},
			piiLoggingEnabled: false,
			logLevel: LogLevel.Verbose,
		}
	}
};
	constructor() {
		/**
		 * Initialize a public client application. For more information, visit:
		 * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/initialize-public-client-application.md
		 */
		this.clientApplication = new PublicClientApplication(MSAL_CONFIG);
		this.account = null;

		// Initialize CryptoProvider instance
		this.cryptoProvider = new CryptoProvider();

		this.setRequestObjects();
	}
	setRequestObjects() {
		const requestScopes = [
			'openid',
			'profile',
			'User.Read'
		];
		const redirectUri = "msal://redirect";

		this.authCodeUrlParams = {
			scopes: requestScopes,
			redirectUri: redirectUri
		};

		this.authCodeRequest = {
			scopes: requestScopes,
			redirectUri: redirectUri,
			code: null
		}

		this.pkceCodes = {
			challengeMethod: "S256", // Use SHA256 Algorithm S256 RS256 
			verifier: "", // Generate a code verifier for the Auth Code Request first
			challenge: "" // Generate a code challenge from the previously generated code verifier
		};
	}
	async getTokenInteractive(authWindow, tokenRequest) {

		/**
		 * Proof Key for Code Exchange (PKCE) Setup
		 *
		 * MSAL enables PKCE in the Authorization Code Grant Flow by including the codeChallenge and codeChallengeMethod parameters
		 * in the request passed into getAuthCodeUrl() API, as well as the codeVerifier parameter in the
		 * second leg (acquireTokenByCode() API).
		 *
		 * MSAL Node provides PKCE Generation tools through the CryptoProvider class, which exposes
		 * the generatePkceCodes() asynchronous API. As illustrated in the example below, the verifier
		 * and challenge values should be generated previous to the authorization flow initiation.
		 *
		 * For details on PKCE code generation logic, consult the
		 * PKCE specification https://tools.ietf.org/html/rfc7636#section-4
		 */

		const { verifier, challenge } = await this.cryptoProvider.generatePkceCodes();

		this.pkceCodes.verifier = verifier;
		this.pkceCodes.challenge = challenge;

		const authCodeUrlParams = {
			...this.authCodeUrlParams,
			scopes: tokenRequest.scopes,
			codeChallenge: this.pkceCodes.challenge, // PKCE Code Challenge
			codeChallengeMethod: this.pkceCodes.challengeMethod // PKCE Code Challenge Method
		};

		const authCodeUrl = await this.clientApplication.getAuthCodeUrl(authCodeUrlParams);

		protocol.registerFileProtocol("msal", (req, callback) => {
			const requestUrl = url.parse(req.url, true);
			callback(path.normalize(`${__dirname}/${requestUrl.path}`));
		});

		const authCode = await this.listenForAuthCode(authCodeUrl, authWindow);

		const authResponse = await this.clientApplication.acquireTokenByCode({
			...this.authCodeRequest,
			scopes: tokenRequest.scopes,
			code: authCode,
			codeVerifier: this.pkceCodes.verifier // PKCE Code Verifier
		});

		return authResponse;
	}

	async login(authWindow) {
		const authResult = await this.getTokenInteractive(authWindow, this.authCodeUrlParams);
		return this.handleResponse(authResult);
	}

### Expected Behavior

Valid And Completed Access Token 

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, None (Server), Other

### Source

External (Customer)

**Comment by hectormmg** [comment]
Hi @mustafaAly , thanks for opening the issue.

Please don't post access token secrets since GitHub is a public forum and those are sensitive credentials.

Having said that, the access token value you posted does seem to be wrong since access tokens are BASE64 encoded JWTs (they should start with "eyJ...").

We've recently made changes to our Electron sample that might help solve your issue, could you please try to update your code to match [the updated sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/ElectronTestApp)?

Also, if you could send a network trace captured with a tool such as Fiddler of the whole authentication flow to the email in my GitHub profile, that could help me diagnose the root cause of the issue.

**Comment by mustafaAly** [comment]
Hi @hectormmg , thanks for replying I made these changes to my electron app and the problem still exists 
my access code returned started with "EwBwA8l6BAAUkj1NuJYtTVha+Mogk+HEiPbQo04AARC8x0U82pbqS9kpGS/qrDtM8SyXTt8dBEfsc0JLXx2KM/"
also, it contains the "..." I will send to you the authentication flow to your mail 
Thank you

**Comment by hectormmg** [comment]
@mustafaAly I couldn't open the Fiddler everywhere file, could you export the .saz file and send that instead please?

**Comment by hectormmg** [comment]
@mustafaAly could you update your code snippets in the description to match the way it looks now? Also, could you provide more details on what platform you are using? I couldn't find the /token request or response in your Fiddler trace so you may need to do another capture that has the calls to /authorize and /token as well as their responses.

**Comment by mustafaAly** [comment]
@hectormmg  yeah sure , I wonder if I can send you the project in your mail to check what's wrong , Thanks in Advance

**Comment by hectormmg** [comment]
@mustafaAly sure, you can send me a zip so I can look at the code as well. Thanks!

**Comment by mustafaAly** [comment]
@hectormmg  Hi Hector, thank you so much for your time and your support I really appreciate that I resolve my issue and the access token was returned successfully thank you again for your help
