### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by sunkimMS** [AzureAD/microsoft-authentication-library-for-js#4739]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

n/a

### Wrapper Library

Not Applicable

### Wrapper Library Version

none

### Description

Following this document to do PR to contribute.
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/contributing.md

and "Npm install" fails with following error.
![image](https://user-images.githubusercontent.com/102757762/165391531-eca01d26-bae2-40a4-b05b-19b5e20c678b.png)

and npm build fails as well.
![image](https://user-images.githubusercontent.com/102757762/165391647-9e6a559f-f571-4985-8531-03786973ad13.png)

Jason Nutter mentioned, validation library needs to be removed.
![image](https://user-images.githubusercontent.com/102757762/165391782-6539357c-a837-4b91-b163-85cbac5a726d.png)

### Error Message

this is with NPM install, so N/A

### Msal Logs

this is with NPM install, so N/A

### MSAL Configuration

```javascript
this is with NPM install, so N/A
```

### Relevant Code Snippets

```javascript
this is with NPM install, so N/A
```

### Reproduction Steps

Fork the "microsoft-authentication-library-for-js.git" and do "npm install"

### Expected Behavior

Npm install and npm build success, and able to run npm test.

### Identity Provider

Other

### Browsers Affected (Select all that apply)

Other

### Source

Internal (Microsoft)

**Comment by hectormmg** [comment]
@sunkimMS thanks for opening the issue, will try to repro and then remove the validation library from lerna in a PR to fix it.
