### ISSUE TITLE
Device ID not detected in Azure Single Sign On using MSAL 2.23.0 (Browser)

### ISSUE THREAD

**Issue by yongks** [AzureAD/microsoft-authentication-library-for-js#4740]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.23.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

My app is a browser extension with MSAL 2.23.0 (browser). It had been working fine until one day IT department imposed a conditional access rule that restrict domain joined device. That is when I realize AAD had rejected the signin because it can't determine if the device is domain-joined due to missing Device ID.

I had tested my extension in Edge, Firefox, Chrome browser, same result.

### Error Message

Error Code: 53001
Request Id: 8571d6f5-0981-428d-b419-beb6ad9c9300
Correlation Id: 4045aa28-6dea-4cf8-ad32-5c09f7853ea0
Timestamp: 2022-04-27T04:07:42.506Z
App name: xxx
App id: xxxxxxx
IP address: xxxxxxxx
Device identifier: Not available
Device platform: Windows 10
Device state: Unregistered

### Msal Logs

Unchecked runtime.lastError: The user did not approve access.

### MSAL Configuration

```javascript
// Get The Chromium URL dynamically
 const redirect_uri = typeof chrome !== "undefined" && chrome.identity ?
    chrome.identity.getRedirectURL() : 
    `${window.location.origin}/index.html`;

const tenant_id    = 'xxxx';
const client_id    = 'yyyy'

// Init MSAL Instance
const msalInstance = new msal.PublicClientApplication({
    auth: {
        authority:  `https://login.microsoftonline.com/${tenant_id}`,
        clientId:    client_id,
        redirectUri: redirect_uri,
        postLogoutRedirectUri: redirect_uri,
        navigateToLoginRequestUrl: false
    },
    cache: {
        cacheLocation: "localStorage"
    }
});
```

### Relevant Code Snippets

```javascript
async function ssoLogin() {
    const sso_login_url = await getLoginUrl();
    const tokenResponse = await launchWebAuthFlow(sso_login_url);  // trigger popup window login
}

async function getLogoutUrl(request) {
 return new Promise((resolve, reject) => {
     msalInstance.logout({
         ...request,
         onRedirectNavigate: (url) => {
             resolve(url);
             return false;
         }
     }).catch(reject);
 });
}


In manifest.json, msal library must be loaded, snipet as below:

  "background":{
      "scripts":["libs/msal-browser-2.23.0/msal-browser.min.js"]
 }
```

### Reproduction Steps

The codes above is background script of an extension.

1. Azure AD App registration must be configured to allow SPA with the chrome extension URL as redirect. Configure your own tenant and client ID.
2. load the extension in browser (Edge, Chrome, Firefox will work)
3. open the background page of the extension (in developer mode)
4. hit "ssoLogin()"
5. Follow through the sigin process (username/password/mfa)
6. Check the AAD signon logs, witness that Device ID is blank

### Expected Behavior

Device ID should not be empty

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge

### Source

External (Customer)

**Comment by yongks** [comment]
any update on this ?

**Comment by jasonnutter** [comment]
For Chrome, please install the Windows Account extension, which should handles including your device id in outgoing requests (MSAL.js is not and cannot be responsible for including device id): https://chrome.google.com/webstore/detail/windows-accounts/ppnbnpeolgkicgegkbkbjmhlideopiji

**Comment by yongks** [comment]
I had tried the extension, it doesn't work as well. Don't understand how this would help.

When using chrome identity API, "launchWebAuthFlow" will launch a window for SSO login, it is this window that I suspect the device ID didn't get pass through.

**Comment by tnorling** [comment]
The chrome extension or Edge browser is **required** in order to inject the deviceId into the request. It sounds like the extension isn't getting loaded into the window opened by the `launchWebAuthFlow` API. You may need to open a new tab to the /authorize endpoint and then find a way to feed the response back to your extension. We unfortunately don't have an example of how to do this. We have another issue open for Chrome extension compatibility: #3923 which we are using to track better guidance for integrating MSAL.js with extensions

**Comment by tnorling** [comment]
The chrome extension or Edge browser is **required** in order to inject the deviceId into the request. It sounds like the extension isn't getting loaded into the window opened by the `launchWebAuthFlow` API. You may need to open a new tab to the /authorize endpoint and then find a way to feed the response back to your extension. We unfortunately don't have an example of how to do this. We have another issue open for Chrome extension compatibility: #3923 which we are using to track better guidance for integrating MSAL.js with extensions

**Comment by rkrsgithub** [comment]
Hi Team. I am also having the same issue, while login using android MSAL lib. DO we have a workaround of Android app login ?

**Comment by slu019** [comment]
@tnorling I am also running into the same issue with Edge browser using the ChromiumExtensionSample. The /authorize endpoint will succeed in a standard browser tab where I am signed in to an Edge profile, but not in the popup window opened by the extension. Any ideas on how to resolve this?

**Comment by lucf15** [comment]
> Hi Team. I am also having the same issue, while login using android MSAL lib. DO we have a workaround of Android app login ?

Did you find any solutions for this? @rkrsgithub
