### ISSUE TITLE
Typescript Error in typings file

### ISSUE THREAD

**Issue by CraigComeOnThisNameCantBeTaken** [AzureAD/microsoft-authentication-library-for-js#475]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre>0.2.3<code>
Library version: X.Y.Z

## Current behavior

When attempting to transpile my angular app I get the following error:

ERROR in node_modules/msal/lib-commonjs/UserAgentApplication.d.ts(35,9): error TS2717: Subsequent property declarations must have the same type.  Property 'callBackMappedToRenewStates' must be of type 'any', but here has type '{}'.

## Expected behavior

No error

## Minimal reproduction of the problem with instructions

setup a basic angular app or anything using typescript 3.1.1
npm install msal
attempt to build

</code></pre>

**Comment by michaellichtner** [comment]
I experienced this in angular 6 and typescript 2.7.2 but did not have the issue in angular 7 typescript 3.1.6 - if you're able to upgrade to work-around while it gets fixed.

**Comment by sameerag** [comment]
Linking to #786
