### ISSUE TITLE
How can I get token from Azure Enterprise application proxy pre-authentication in Browser ?

### ISSUE THREAD

**Issue by RoussillonClement** [AzureAD/microsoft-authentication-library-for-js#4757]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.23.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

Hello,

In my company, we have multiple Enterprise applications (not App registrations) in Azure AD with a proxy pre-authentication with 2FA.
In order to keep our security, we don't want to remove the proxy pre-auth check so we need to get the azure token given by pre-auth in browser and then send it to our internal APIs for many cases.
My question is how can I get the token or the account informations given by the pre-auth in our app (Vue.js app)? 
I've tried Msal.js but the library always returns an empty array when I use getAllAccounts function even if I am already connected in Azure AD.
I see there is informations in Cookies but I don't see any information about that in documentations, maybe I can do something with these cookies. 
Maybe this is an Azure config, with the Enterprise application, we can't set the application type to 'Single Page Application', so the MSAL library throw an error for each request I send even if the connection to Azure works. 

Is there a solution about that ? 

### MSAL Configuration

```javascript
auth: {
    clientId: '***',
    authority: 'https://login.microsoftonline.com/****',
    redirectUri: ****,
  },
  cache: {
    storeAuthStateInCookie: true,
  },
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by peterzenz** [comment]
@RoussillonClement we have no support for the Azure AD Application Proxy today.  We will track this as a customer ask but we don't have this in our current roadmap today.  @EmLauber for FYI.
