### ISSUE TITLE
Recommendation for server side authentication for node.js

### ISSUE THREAD

**Issue by chitturs** [AzureAD/microsoft-authentication-library-for-js#4759]
### Core Library

Passport Azure AD (passport-azure-ad)

### Core Library Version

4.3.1

### Wrapper Library

MSAL Node Extensions (@azure/msal-node-extensions)

### Wrapper Library Version

None

### Description

What would be the recommendation for server side auth for node.js? I see passport authentication support, but that looks like in maintenance. It sounded like [microsoft-authentication-library-for-js/lib/msal-node at dev · AzureAD/microsoft-authentication-library-for-js (github.com)](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-node) but I couldn't easily see server-side auth support.

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by hectormmg** [comment]
@chitturs can you please describe your requirements more elaborately? MSAL Node has support for server-side authentication using the following OAuth2.0 flows:

Confidential Client:
- [Authorization Code Grant](https://oauth.net/2/grant-types/authorization-code/) with a client credential
- [Refresh Token Grant](https://oauth.net/2/grant-types/refresh-token/)
- [Silent Flow](https://docs.microsoft.com/azure/active-directory/develop/msal-acquire-cache-tokens#acquiring-tokens-silently-from-the-cache)
- [Client Credential Grant](https://oauth.net/2/grant-types/client-credentials/)
- [On-behalf-of flow](https://docs.microsoft.com/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow)
- [Username and Password flow](https://docs.microsoft.com/azure/active-directory/develop/msal-authentication-flows#usernamepassword)

**Comment by chitturs** [comment]
Thanks. Can you point to me a BearerStrategy server side sample like https://github.com/AzureADQuickStarts/AppModelv2-WebAPI-nodejs? That is what I am currently using.

My client is a daemon app (confidential client) as well as a public client (using auth code flow).

**Comment by hectormmg** [comment]
@chitturs to be clear, are you looking to protect a server-side API running on Node, or are you trying to acquire access tokens from a daemon app running on Node?

If it is the former, we don't currently have a published token validation library yet, although we are working on one.

If it is the latter, the client credentials or auth code samples in our [samples/msal-node-samples](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples) directory may help.

**Comment by chitturs** [comment]
Yep, former. Is there a way I can be notified when the server-side library is available?

Thanks

**Comment by tnorling** [comment]
@chitturs You can track our [releases page](https://github.com/AzureAD/microsoft-authentication-library-for-js/releases). Keep an eye out for `@azure/node-token-validation`. We will also update and close this issue when it has been published.

**Comment by drGarbinsky** [comment]
Is [this code sample ](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-node-samples/on-behalf-of/web-api/index.js)the current recommended approach for validating a token? I am coming from a Azure AD background where bearer strategies were common. The fact that node-token-validation has yet to be complete makes me think I am unnecessarily working towards an edge case. Should I be using a different pattern to secure my node API?

Scenario specifics:
-SPA / React frontend
-Apollo / Node API

**Comment by drGarbinsky** [comment]
[https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-node-samples/on-behalf-of/web-api/index.js](url)

**Comment by EmLauber** [comment]
Moving to @jennyf19 @jmprieur for tracking node token validation story.

**Comment by bgavrilMS** [comment]
Let's use this similar issue to track this request: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/6113
