### ISSUE TITLE
[Msal for Angular] Feature - Optional HTTP Interceptor on authentication State

### ISSUE THREAD

**Issue by Dedme** [AzureAD/microsoft-authentication-library-for-js#476]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version XX
- [x] Firefox version XX
- [x] IE version XX
- [x] Edge version XX
- [x] Safari version XX

## Library version

<pre><code>
Library version: X.Y.Z

</code></pre>

## Current behavior
Setting the httpInterceptor allows you to configure which urls to send the tokens on,
however when the user is not signed in those urls error requiring the service to be authenticated.
I am using the single endpoint to return subsets of data for unauthorised users.
i would like to send the token when i have one, but if i don't i wish to send the request without a token.

## Expected behavior
add an additional config option on behaviour when not authenticated.
either as a parameter to the Protected endpoint (most flexible), or on the whole.
I have had to implement a middle interceptor that checks if the user is signed in before calling the MsalInterceptor.

```typescript
protectedResourceMap: [['http://localhost:50133/api', ['api://xxx-0992-4fb0-8426-xxx/access_as_user'], false],
                             ['https://graph.microsoft.com/v1.0/me', ['user.read']]],
```

where the procestedResporceMap is something like [ [ EndpointUri, [Scopes], AuthenticationRequiredFlag] ]

**Comment by nehaagrawal** [comment]
@Dedme  You can use this config unprotectedResources . This will not attach token to all the urls configured here.

unprotectedResources : Array of URI's. Msal will not attach a token to outgoing requests that have these uri. Defaults to 'null'.

**Comment by Dedme** [comment]
@nehaagrawal,
thanks for your reply, however this causes the API to never send the request? at least in my initial testing, if you can confirm otherwise ill investigate further.

> I am using the single endpoint to return subsets of data for unauthorized users.
> i would like to send the token when i have one, but if i don't i wish to send the request without a token.

i would like to send a token if i am signed in, and not send one when i am not.
The API contains logic on what to return is authorized or not. its not a complete yes or no access to data, its a large range depending on permissions to what data is valid.

this has been my solution to the problem, but i don't like having the extra layer of interception. - makes maintenance trickier for others.

```typescript
export class MyInterceptorService implements HttpInterceptor {
  constructor(private store: Store, private msal: MsalInterceptor) {}
  intercept(req: HttpRequest<any>, next: HttpHandler) {
    if (this.store.selectSnapshot(AppState.user)) {
      return this.msal.intercept(req, next);
    } else {
      return next.handle(req);
    }
  }
}
```

**Comment by nehaagrawal** [comment]
@Dedme  Thank you for explaining the issue. I need to discuss this issue with my team internally to confirm if this can be added as a feature. We will get back to you on this soon.

**Comment by navyasric** [comment]
@Dedme We have had some context loss on this issue. 
Can you explain the scenario where you would need the AuthenticationRequired flag on the protectedResourceMap for the interceptor? 
The MSAL library expects to have an authenticated user context before being able to get tokens for API access. The idea is to not provide protected data access to unauthenticated users. Hence, we expect the endpoints listed in protectedResourceMap to be authenticated. 
IAre you requesting that the MSAL interceptor not make a request to the API if there is no signed in user?
Please confirm my understanding.

**Comment by Dedme** [comment]
@navyasric 
My use case is that i have an API endpoint which is not authenticated by default, as there is public data that is available which is nearly identical to the authenticated data.

My API does an authentication check as part of its business logic, which then either filters, or not, the data returned from the Data Layer.

I make the same web call when i am authenticated to when i am not, because for 99% of my workflow from Client request to Client response and parsing, there is no change to the process.

so my intention is that for a particular protectedResourceMap that it can only attempt to add the Token if logged in. essentially a flag to make the authentication user context optional, and bypass the Interceptor when its not present.

i do understand that this might be a niche requirement, and that there is always the option to create 2 endpoints 1 for Authenticated and one for not, but then i will need to have more granular protected resources, and become cumbersome including/excluding the sub paths "/controller/method", for each method that i want to be accessible to both. 

My workaround is perfectly manageable if this is an outlier. but i figured i couldn't be the only one that wants to have an optional user context on method calls.

**Comment by navyasric** [comment]
@Dedme Thank you for the detailed explanation of the scenario. Your point about bypassing interceptor when there is no authenticated user context is valid. However, considering that protectedResourceMap intends to take only endpoints that require authentication, another flag for it seems conflicting. We will consider this scenario and discuss in our team. Thanks.

**Comment by Dedme** [comment]
@navyasric, to me the next place i would think for it is another array like the unprotectedResources list, but with an Optional or Dynamic type name. or even a flag on the excluded list. 

optionalResources, dynamicResources, conditialResources, or something

**Comment by sameerag** [comment]
Linking #786 but keeping this open as this is a specific ask.

**Comment by DarylThayil** [comment]
closing because it is tracked in #786

**Comment by brijesh1ec** [comment]
Store is in built class or custom class which uses localstorage or sessionstorage

**Comment by ormico** [comment]
what was the resolution on this b/c I have almost identical issue and cannot find how I'm suppose to resolve it?

**Comment by Dedme** [comment]
> Store is in built class or custom class which uses localstorage or sessionstorage
@brijesh1ec  this is the NGXS store. (sorry late reply)

> what was he resolution on this b/c I have almost identical issue and cannot find how I'm suppose to resolve it?
I ended up just creating a secondary endpoint - and using the framework as indented at the time. - it did end up cleaning up my api a fair amount anyway
