### ISSUE TITLE
Getting consent for a live.com account fails with invalid_request: The provided request must include a 'client_id' input parameter.

### ISSUE THREAD

**Issue by brugh** [AzureAD/microsoft-authentication-library-for-js#4767]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.23.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.2.0

### Description

I load msal in an Office.js add-in. The first time I run the add-in the user needs to give consent. When I use a AzureAD account, the consent screen shows up inside the add-in just fine. But when I use a live.com address, the consent screen doesn't show up and instead a new browser window opens to https://login.live.com/oauth20_authorize.srf?res=error&ec=&uaid=xxx without a consent prompt. 
When I instead of loginredirect open a dialog windows like `Office.context.ui.displayDialogAsync(window.location.origin + '/#/login', ...` I DO get a consent prompt inside that dialog. When I then give consent for the live.com address, and change the code back to loginRedirect, everything works fine. When I remove the consent on https://account.live.com/consent/Manage, the error is back and I can't log in. 
Weird thing is that for AzureAD accounts I get the consent prompt just fine without the Dialog window. Only live.com addresses seem to have this problem. 
In the add-in Manifest I tried adding all AppDomains I could find in my Wireshark capture but when the Addin needs consent, it opens an external browser window with said error. 

snippit from manifest: 
`
  <AppDomains>
    <AppDomain>https://localhost:4200</AppDomain>
    <AppDomain>https://graph.microsoft.com</AppDomain>
    <AppDomain>https://login.microsoftonline.com</AppDomain>
    <AppDomain>https://login.live.com</AppDomain>
    <AppDomain>https://account.live.com</AppDomain>
    <AppDomain>https://aadcdn.msauth.net</AppDomain>
    <AppDomain>https://aadcdn.msftauth.net</AppDomain>
    <AppDomain>https://www.microsoft.com</AppDomain>
    <AppDomain>https://privacy.microsoft.com</AppDomain>
  </AppDomains>
`

### Error Message

invalid_request: The provided request must include a 'client_id' input parameter.

### Msal Logs

Because this happens after MSAL redirects, there are now msal logs specific to the error. the logs are similar for AzureAD accounts, with or without consent and for live accounts, also with or without consent. The only thing showing in the console.log is 

VM37:470 [Sat, 30 Apr 2022 13:18:46 GMT] : [d8e582dd-7925-4a4b-818a-8684b05f12cd] : @azure/msal-browser@2.23.0 : Verbose - loginRedirect called
VM37:470 [Sat, 30 Apr 2022 13:18:46 GMT] : [d8e582dd-7925-4a4b-818a-8684b05f12cd] : @azure/msal-browser@2.23.0 : Verbose - acquireTokenRedirect called
VM37:470 [Sat, 30 Apr 2022 13:18:46 GMT] : @azure/msal-browser@2.23.0 : Verbose - preflightBrowserEnvironmentCheck started
VM37:470 [Sat, 30 Apr 2022 13:18:46 GMT] : @azure/msal-browser@2.23.0 : Verbose - preflightInteractiveRequest called, validating app environment
VM37:470 [Sat, 30 Apr 2022 13:18:46 GMT] : @azure/msal-browser@2.23.0 : Trace - BrowserCacheManager.getTemporaryCache: No cache item found in local storage
VM37:470 [Sat, 30 Apr 2022 13:18:46 GMT] : @azure/msal-browser@2.23.0 : Verbose - getAllAccounts called
VM37:470 [Sat, 30 Apr 2022 13:18:46 GMT] : @azure/msal-browser@2.23.0 : Info - Emitting event: msal:loginStart
VM37:470 [Sat, 30 Apr 2022 13:18:46 GMT] : @azure/msal-browser@2.23.0 : Verbose - Emitting event to callback 9adf98ca-1ca5-4aac-a328-e32535a3351c: msal:loginStart
VM37:470 [Sat, 30 Apr 2022 13:18:46 GMT] : @azure/msal-angular@2.2.0 : Verbose - BroadcastService - msal:loginStart results in setting inProgress from none to login
VM37:470 [Sat, 30 Apr 2022 13:18:46 GMT] : [d8e582dd-7925-4a4b-818a-8684b05f12cd] : msal.js.browser@2.23.0 : Verbose - initializeAuthorizationRequest called
VM37:470 [Sat, 30 Apr 2022 13:18:46 GMT] : [d8e582dd-7925-4a4b-818a-8684b05f12cd] : msal.js.browser@2.23.0 : Verbose - getRedirectUri called
VM37:470 [Sat, 30 Apr 2022 13:18:46 GMT] : [d8e582dd-7925-4a4b-818a-8684b05f12cd] : msal.js.browser@2.23.0 : Verbose - Initializing BaseAuthRequest
VM37:470 [Sat, 30 Apr 2022 13:18:46 GMT] : [d8e582dd-7925-4a4b-818a-8684b05f12cd] : msal.js.browser@2.23.0 : Verbose - Authentication Scheme wasn't explicitly set in request, defaulting to "Bearer" request
VM37:470 [Sat, 30 Apr 2022 13:18:46 GMT] : @azure/msal-browser@2.23.0 : Trace - BrowserCacheManager.getTemporaryCache: No cache item found in local storage
VM37:470 [Sat, 30 Apr 2022 13:18:46 GMT] : @azure/msal-browser@2.23.0 : Trace - BrowserCacheManager.getTemporaryCache: No cache item found in local storage
VM37:470 [Sat, 30 Apr 2022 13:18:46 GMT] : @azure/msal-browser@2.23.0 : Trace - BrowserCacheManager.updateCacheEntries called
VM37:470 [Sat, 30 Apr 2022 13:18:46 GMT] : [d8e582dd-7925-4a4b-818a-8684b05f12cd] : msal.js.browser@2.23.0 : Verbose - initializeServerTelemetryManager called
VM37:470 [Sat, 30 Apr 2022 13:18:46 GMT] : [d8e582dd-7925-4a4b-818a-8684b05f12cd] : msal.js.browser@2.23.0 : Verbose - initializeAuthorizationRequest called
VM37:470 [Sat, 30 Apr 2022 13:18:46 GMT] : [d8e582dd-7925-4a4b-818a-8684b05f12cd] : msal.js.browser@2.23.0 : Verbose - getClientConfiguration called
VM37:470 [Sat, 30 Apr 2022 13:18:46 GMT] : [d8e582dd-7925-4a4b-818a-8684b05f12cd] : msal.js.browser@2.23.0 : Verbose - getDiscoveredAuthority called
VM37:470 [Sat, 30 Apr 2022 13:18:46 GMT] : [d8e582dd-7925-4a4b-818a-8684b05f12cd] : @azure/msal-browser@2.23.0 : Trace - PerformanceClient: Performance measurement started for standardInteractionClientGetDiscoveredAuthority
VM37:470 [Sat, 30 Apr 2022 13:18:46 GMT] : [d8e582dd-7925-4a4b-818a-8684b05f12cd] : @azure/msal-browser@2.23.0 : Trace - PerformanceClient: Performance measurement for standardInteractionClientGetDiscoveredAuthority started
VM37:470 [Sat, 30 Apr 2022 13:18:46 GMT] : [d8e582dd-7925-4a4b-818a-8684b05f12cd] : msal.js.browser@2.23.0 : Verbose - Creating discovered authority with configured authority
VM37:470 [Sat, 30 Apr 2022 13:18:46 GMT] : @azure/msal-browser@2.23.0 : Trace - BrowserCacheManager.getAuthorityMetadata: cache hit
VM37:470 [Sat, 30 Apr 2022 13:18:46 GMT] : @azure/msal-browser@2.23.0 : Trace - BrowserCacheManager.setAuthorityMetadata called
VM37:470 [Sat, 30 Apr 2022 13:18:46 GMT] : [d8e582dd-7925-4a4b-818a-8684b05f12cd] : @azure/msal-browser@2.23.0 : Trace - PerformanceClient: Performance measurement ended for standardInteractionClientGetDiscoveredAuthority: 3.100000023841858 ms
VM37:470 [Sat, 30 Apr 2022 13:18:46 GMT] : [d8e582dd-7925-4a4b-818a-8684b05f12cd] : @azure/msal-browser@2.23.0 : Trace - PerformanceClient: Performance measurement for standardInteractionClientGetDiscoveredAuthority added/updated
VM37:470 [Sat, 30 Apr 2022 13:18:46 GMT] : [d8e582dd-7925-4a4b-818a-8684b05f12cd] : msal.js.browser@2.23.0 : Verbose - Auth code client created
VM37:470 [Sat, 30 Apr 2022 13:18:46 GMT] : [d8e582dd-7925-4a4b-818a-8684b05f12cd] : msal.js.browser@2.23.0 : Verbose - Redirect start page: https://localhost:4200/?_host_Info=Word$Win32$16.01$en-US$$$$0#/
VM37:470 [Sat, 30 Apr 2022 13:18:46 GMT] : [d8e582dd-7925-4a4b-818a-8684b05f12cd] : msal.js.browser@2.23.0 : Verbose - RedirectHandler.initiateAuthRequest called
VM37:470 [Sat, 30 Apr 2022 13:18:46 GMT] : [d8e582dd-7925-4a4b-818a-8684b05f12cd] : msal.js.browser@2.23.0 : Verbose - RedirectHandler.initiateAuthRequest: redirectStartPage set, caching start page
VM37:470 [Sat, 30 Apr 2022 13:18:46 GMT] : @azure/msal-browser@2.23.0 : Trace - BrowserCacheManager.cacheCodeRequest called
VM37:470 [Sat, 30 Apr 2022 13:18:46 GMT] : [d8e582dd-7925-4a4b-818a-8684b05f12cd] : msal.js.browser@2.23.0 : Info - RedirectHandler.initiateAuthRequest: Navigate to: https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=04634b9b-7e1a-45d2-be82-f8de64c13fa2&scope=User.Read%20openid%20profile%20offline_access&redirect_uri=https%3A%2F%2Flocalhost%3A4200&client-request-id=d8e582dd-7925-4a4b-818a-8684b05f12cd&response_mode=fragment&response_type=code&x-client-SKU=msal.js.browser&x-client-VER=2.23.0&client_info=1&code_challenge=nJdNzZQoS_tjpH14SEKkKdtmpWbLUk1YvRL3GxPrP8A&code_challenge_method=S256&nonce=fe7416b0-26a1-4f4c-88b8-4315d082ea34&state=eyJpZCI6ImY5YjA3ZDJiLTkxMGMtNGUzZC05Nzk2LWYwMmU1ZTFiMDY2YiIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicmVkaXJlY3QifX0%3D
VM37:470 [Sat, 30 Apr 2022 13:18:46 GMT] : [d8e582dd-7925-4a4b-818a-8684b05f12cd] : msal.js.browser@2.23.0 : Verbose - RedirectHandler.initiateAuthRequest: Navigating window to navigate url
Navigated to https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=04634b9b-7e1a-45d2-be82-f8de64c13fa2&scope=User.Read+openid+profile+offline_access&redirect_uri=https%3a%2f%2flocalhost%3a4200&client-request-id=d8e582dd-7925-4a4b-818a-8684b05f12cd&response_mode=fragment&response_type=code&x-client-SKU=msal.js.browser&x-client-VER=2.23.0&client_info=1&code_challenge=nJdNzZQoS_tjpH14SEKkKdtmpWbLUk1YvRL3GxPrP8A&code_challenge_method=S256&nonce=fe7416b0-26a1-4f4c-88b8-4315d082ea34&state=eyJpZCI6ImY5YjA3ZDJiLTkxMGMtNGUzZC05Nzk2LWYwMmU1ZTFiMDY2YiIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicmVkaXJlY3QifX0%3d&sso_nonce=AwABAAEAAAACAOz_BAD0_1nlnyCOy0FXkcSwtOJ0ptS5DYyVdx7DiGqmXs7-wv_lko6mkJqUiKdKOWop9VivpDVC9bB0g_ruvSNsj7eWKIogAA&mscrid=d8e582dd-7925-4a4b-818a-8684b05f12cd
Navigated to https://login.live.com/oauth20_authorize.srf?client_id=04634b9b-7e1a-45d2-be82-f8de64c13fa2&scope=User.Read+openid+profile+offline_access&redirect_uri=https%3a%2f%2flocalhost%3a4200&response_type=code&state=eyJpZCI6ImY5YjA3ZDJiLTkxMGMtNGUzZC05Nzk2LWYwMmU1ZTFiMDY2YiIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicmVkaXJlY3QifX0%3d&response_mode=fragment&nonce=fe7416b0-26a1-4f4c-88b8-4315d082ea34&code_challenge=6AtxuGcgXSsAXnawP5UogYtngQ0wK9W_H4E7eA7JWDQ&code_challenge_method=S256&x-client-SKU=msal.js.browser&x-client-Ver=2.23.0&uaid=d8e582dd79254a4b818a8684b05f12cd&msproxy=1&issuer=mso&tenant=common&ui_locales=en-US&client_info=1&epct=AQABAAAAAAD--DLA3VO7QrddgJg7WevrUV4bl35LR6al9KG2Rz3_haC1sKvnZOM0yXmRKR4NAGdoC6-usYq5nqbi913oNCmwrk7rx-I7g2qw5-kZEo6OmkBEenQZ8WbZ2x3olIvbi4Hn4vdQlIXBtq96CZzZzSAtiKTqR7Cu5vzpgAC5WyK0uxsd9zFi2flMNxNeylzqv1kz1YrmcQWaNFCB3ngKMofDxc4C-xXrt-ttiXFNpda1uiAA&jshs=0&username=xxxx%40hotmail.com&login_hint=xxxx%40hotmail.com

### MSAL Configuration

```javascript
export const msalConfig: Configuration = {
     auth: {
         clientId: '04634b9b-7e1a-45d2-be82-f8de64c13fa2', // This is the ONLY mandatory field that you need to supply.
         authority: 'https://login.microsoftonline.com/common', // Defaults to "https://login.microsoftonline.com/common"
         redirectUri: window.location.origin, // Points to window.location.origin. You must register this URI on Azure portal/App Registration.
     },
     cache: {
         cacheLocation: BrowserCacheLocation.LocalStorage, // Configures cache location. "sessionStorage" is more secure, but "localStorage" gives you SSO between tabs.
         storeAuthStateInCookie: isIE, // Set this to "true" if you are having issues on IE11 or Edge
     },
     system: {
         loggerOptions: {
             loggerCallback(logLevel: LogLevel, message: string) {
                 console.log(message);
             },
             logLevel: LogLevel.Trace,
             piiLoggingEnabled: true
         }
     }
 }
```

### Relevant Code Snippets

```javascript
if (this.isIframe || this.msalGuardConfig.interactionType === InteractionType.Popup) {
      if (this.msalGuardConfig.authRequest) {
        this.authService.loginPopup({ ...this.msalGuardConfig.authRequest } as PopupRequest)
          .subscribe((response: AuthenticationResult) => {
            this.authService.instance.setActiveAccount(response.account);
          });
      } else {
        this.authService.loginPopup()
          .subscribe((response: AuthenticationResult) => {
            this.authService.instance.setActiveAccount(response.account);
          });
      }
    } else {
      // Office.context.ui.displayDialogAsync(window.location.origin + '/#/login',
      //   { height: 50, width: 24 }, (result: any) => {
      //     const dialog = result.value;
      //     dialog.addEventHandler(Office.EventType.DialogMessageReceived, (arg: { message: string, type: string }) => {
      //       const messageFromDialog = JSON.parse(arg.message);
      //       if (messageFromDialog.status === 'success') {
      //         console.log(messageFromDialog.result);
      //       } else {
      //         console.log("Message error\n" + JSON.stringify(messageFromDialog));
      //       }
      //       dialog.close();
      //     });
      //   }
      // );
      if (this.msalGuardConfig.authRequest) {
        this.authService.loginRedirect({ ...this.msalGuardConfig.authRequest } as RedirectRequest);
      } else {
        this.authService.loginRedirect();
      }
```

### Reproduction Steps

See problem description 

### Expected Behavior

Consent popup for live.com accounts should open in office.js add-in just like it does for azureAD accounts

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Edge

### Source

External (Customer)

**Comment by brugh** [comment]
Also, if I really do need displayDialogAsync (although I don't understand why AzureAD accounts don't need it and live.com accounts do), how do I configure MsalGuard to open a dialog too instead of redirecting or even worse, trying to open a popup in the add-in...

**Comment by tnorling** [comment]
@brugh This looks like the same issue you raised previously in #3179. To build an office add-on you need to use the dialog API when invoking interaction, every time. There's 2 ways you can do this: 

1. Write your own custom guard that opens the dialog box to a page that calls login and returns to a page that handles the response and sends the response back up to the guard. This approach is roughly demonstrated in the [office add-on sample](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/auth/Office-Add-in-Microsoft-Graph-React)
2. Use the [`onRedirectNavigate` parameter](https://azuread.github.io/microsoft-authentication-library-for-js/ref/modules/_azure_msal_browser.html#redirectrequest) on your redirect request to open the dialog box, have the redirectUri page send the url hash back up to the guard and have the guard call `handleRedirectPromise` with that hash.

**Comment by brugh** [comment]
True, I struggled with this before. Good that you remember the other case. 
I noticed the new msal versions and gave it another go. I tried some reworks of my other workaround of having two separate applications which created a situation that our dev env differs from our prod significantly which makes for hard testing. 
the new version does solve a few of our issues, except this one. Since we can now get the entire authenication including consent questions inside the Add-in without any dialogs for AzureAD accounts I was hoping we can figure out what makes live accounts require the dialog still. As said, once consent is give, live accounts work fine inside the add-in too. 

that said, I reworked our auth.service so it pops the dialog when any regular login requests are given so that works fine. I no longer need 2 apps to handle login. But I run into trouble when a protected resource get called before a user is logged in and the msal interceptor takes over and gives an Interaction Required error. We can only set interactionType: InteractionType.Redirect (or Popup) which redirects inside the add-in. How can we hook into that and prevent the default redirect? When I subscribe to this.msalBroadcastService.msalSubject$ and check for InteractionType.Redirect I can open a dialog but the redirect inside the add-in also still happens. if I can prevent that redirect, I think I can get a working flow.

**Comment by tnorling** [comment]
> Since we can now get the entire authenication including consent questions inside the Add-in without any dialogs for AzureAD accounts

Whether it works or not, this is not the recommended approach for developing office add-ins. Dialogs are the recommended approach.

> But I run into trouble when a protected resource get called before a user is logged in and the msal interceptor takes over and gives an Interaction Required error.

You should wait until the `inProgress` observable indicates there is not interaction in progress before making an http request that might invoke the interceptor. See [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-angular-v2-samples/angular12-sample-app/src/app/app.component.ts#L41-L49) for an example.

**Comment by brugh** [comment]
Very well, I concede ;) I still don't understand exactly why we need the dialogs but the flow in this version works fine now. 

I created a boilerplate repo because I can't seem to find a sample project that works for Office desktop as well as Office Online and that has the correct **MSAL** flow for **Office**.js in **Angular**, connects to the **Graph**-API and uses **Fluent-UI** Web-components and **Redux** state. Perhaps somebody looking at the same issues finds this useful: https://github.com/brugh/Angular-office-msal 

because this works now in pre and post consent and in desktop apps and online, I guess you can close this ticket now :) thanks for you patience 👍

**Comment by tnorling** [comment]
Great thank you! I've created an item in our backlog to write an official sample for Angular + Office Add-in, we will certainly take a look at what you've got there when we're ready to pick that up. Closing for now but let us know if you have any other questions
