### ISSUE TITLE
passport-azure-ad vs msal-node server side cache/storage

### ISSUE THREAD

**Issue by daniel-crouch** [AzureAD/microsoft-authentication-library-for-js#4768]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.8.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

From my understanding `passport-azure-ad` can be configured using cookie-session persisting authentication state in cookies and nothing is stored server side (relying on passport to validate the session etc). With `msal-node`, there is a default built in in-memory cache and extensions that allow you to persist authentication state to a data layer.

With `passport-azure-ad` now in maintenance, I was wondering/hoping if `msal-node` was planning on having a similar setup whereby a server side persistence layer is not needed?

For context, my use case is simply to protect a server endpoint from serving up static assets.

This may well be a silly question, or answered elsewhere but I can't seem to find an answer.

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by tnorling** [comment]
@daniel-crouch We are working on a new token validation library that will replace passport-azure-ad. I don't have an ETA to share at the moment but it is in active development and we can update this issue when the first version has been released

**Comment by daniel-crouch** [comment]
Many thanks @tnorling for your reply. When you say to replace passport-azure-ad, does that mean it will be another plug-in for passportjs as a strategy?

I am trying to understand the differences and the need for both this and msal-node is why I ask.

**Comment by tnorling** [comment]
It will be more generic, not specific to passport.

msal-node = token acquisition library
node-token-validation = token validation library (Coming soon)

Depending on what you're building you may need to use one or the other or both

**Comment by daniel-crouch** [comment]
I see. Sounds good. However I feel my original question is unanswered still. Passport-azure-ad from what I can tell does not persist state on the server, yet msal-node does. I understand you have a new library to replace passport-azure-ad, but in replacing it, it's not like for like. Therefore is there a solution which does not need to persist any state on the server and we can just rely on cookies and jwt validation server side?

**Comment by tnorling** [comment]
@daniel-crouch We do not offer a cookie storage solution out of the box, however, you may be able to write your own implementation and provide it to msal-node via `ICachePlugin`. Docs on that can be found [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/caching.md)
