### ISSUE TITLE
AcquireTokenSilent failed to renew accessToken for MSA account due to scope error

### ISSUE THREAD

**Issue by TestInSeptember** [AzureAD/microsoft-authentication-library-for-js#477]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version XX
- [x] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version
0.2.3
<pre><code>
Library version: X.Y.Z

## Current behavior

For MSA account, the AcquireTokenSilent does not work as expected to renew accessToken via hidden frame.It always failed if it cannot get accessToken directly from cache.
Here is the error:
errorDesc = "The request was denied because one or more scopes requested are unauthorized or expired. The user must first sign in and grant the client application access to the requested scope.", token = undefined, error = "consent_required", tokenType = "access_token".

It also happens right after LoginPopup successfully get idToken. I double checked the scope is same when calling LoginPopup and AcquireTokenSilent, and the user already consent in LoginPopup flow.

One thing need to mention, this issue only happens to MSA account, AAD works fine.

## Expected behavior

MSA account should work as AAD, to be able to AcquireTokenSilent after LoginPopup and when token in cache expired.

## Minimal reproduction of the problem with instructions

</code></pre>

**Comment by nehaagrawal** [comment]
@TestInSeptember  Can you please tell us what scopes you are consenting for?

**Comment by nehaagrawal** [comment]
@TestInSeptember  Since we are following up internally and this is not msal.js library issue, I am closing this  issue.
