### ISSUE TITLE
passport-azure-ad 4.3.2 on npm

### ISSUE THREAD

**Issue by vikram-k** [AzureAD/microsoft-authentication-library-for-js#4780]
### Core Library

Passport Azure AD (passport-azure-ad)

### Core Library Version

4.3.2

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

I noticed that passport-azure-ad 4.3.2 was updated a couple weeks ago containing a vulnerability fix for the async package.
Will 4.3.2 be published to npmjs? Let me know what the timeline is for that. Thank you!

### Source

External (Customer)

**Comment by jasonnutter** [comment]
`passport-azure-ad@4.3.2` is now available on npm.
