### ISSUE TITLE
Silent Sign-in Fails in Safari with Error Code AADSTS50058

### ISSUE THREAD

**Issue by qqzm** [AzureAD/microsoft-authentication-library-for-js#4782]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.24.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

Not Applicable

### Description

I am using msal-browser to authenticate against an Azure AD domain. My app is configured as an SPA with relevant redirect Uris configured and Implicit grant and hybrid flows turned-off.
The outer page (https://server1.example.com/) loads msal-browser and calls acquireTokenRedirect to log the user in. Once that is done, it loads an iframe pointing to an inner page at https://server2.example.com/?loginHint=USERNAME
This inner page then calls ssoSilent to authenticate the user, passing in the loginHint that was supplied as a http parameter. If this fails, it falls back to authentication via acquireTokenPopup.
On Chrome, Firefox and Edge the ssoSilent call is successful and the user is logged-in without interaction. However on Safari (tested on Safari version 15.4 on macOS 12.3.1 and iOS 15.4.1) the ssoSilent call fails with the error shown below (AADSTS50058).
Googling around I found a number of people experiencing this error in Safari, but all seemed to be related to the previous azure-activedirectory-library-for-js library. e.g.: https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/323 
In that thread, @jasonnutter commented 2 years ago "We are working on a new version of MSAL which uses the Auth Code Flow w/ PKCE, which will mitigate the need for third-party cookies in most scenarios." I am using the new version of MSAL, is there anything specific I need to do to configure it to use Auth Code Flow w/ PKCE? All the documentation seems to imply that it should be used by default without any extra config being necessary.

### Error Message

InteractionRequiredAuthError: login_required: AADSTS50058: A silent sign-in request was sent but no user is signed in. The cookies used to represent the user's session were not sent in the request to Azure AD. This can happen if the user is using Internet Explorer or Edge, and the web app sending the silent sign-in request is in different IE security zone than the Azure AD endpoint (login.microsoftonline.com). msal-browser.js

Stack Trace:
AuthError — AuthError.js:27 
InteractionRequiredAuthError — InteractionRequiredAuthError.js:40
(anonymous function) — ResponseHandler.js:55
(anonymous function) — AuthorizationCodeClient.js:97
(anonymous function) — InteractionHandler.ts:57
step — tslib.es6.js:100
(anonymous function) — tslib.es6.js:74
Promise
__awaiter$1 — tslib.es6.js:70
(anonymous function) — SilentIframeClient.ts:131
step — tslib.es6.js:100
fulfilled — tslib.es6.js:71
promiseReactionJob

### Msal Logs

[Wed, 04 May 2022 11:00:54 GMT] : @azure/msal-browser@2.24.0 : Info - Emitting event: msal:ssoSilentStart
[Wed, 04 May 2022 11:00:54 GMT] : @azure/msal-browser@2.24.0 : Info - Emitting event: msal:ssoSilentFailure

### MSAL Configuration

```javascript
AzureAuth.msal = new msal.PublicClientApplication({
  auth: {
    clientId: AzureAuth.clientId,
    authority: "https://login.microsoftonline.com/" + AzureAuth.tenantId,
    navigateToLoginRequestUrl: false
  },`
  cache: {
    cacheLocation: "localStorage", // I have also tried sessionStorage
    storeAuthStateInCookie: true // I have tried setting this to false
  },
  system: {
    asyncPopups: false,
    loggerOptions: {
      loggerCallback(logLevel, message) {
        console.log(message);
      }
    }
  }
});
```

### Relevant Code Snippets

```javascript
getToken: function() {
  return new Promise((resolve) => {
      let request = { 
        scopes: AzureAuth.scopes
      };

      if (AzureAuth.username.indexOf('@') == -1) {
        AzureAuth.username = AzureAuth.username + '@' + AzureAuth.domain;
      }
      request.loginHint = AzureAuth.username;

      return AzureAuth.msal.ssoSilent(request)
        .then( (response) => {
          resolve(response);
        })
        .catch(error => {
          if (error instanceof msal.InteractionRequiredAuthError) {
            // Fallback to interaction when silent call fails
            console.warn("silent token acquisition failed, acquiring token interactively");
            console.warn(error);
            AzureAuth.interactive(request).then((response) => {
              resolve(response);
            });
          }
          else if (error instanceof msal.BrowserAuthError) {
            // Just warn about this error.
            console.warn(error);
            AzureAuth.interactive(request).then((response) => {
              resolve(response);
            });
          }
          else {
            // Raise all other errors.
            console.error(error);   
          }
      });
  });
},
```

### Reproduction Steps

1. Create a page that loads msal-browser and performs acquireTokenRedirect.
2. After the user has logged in, programmatically create an iframe on that page that loads a url in the same domain as the first page.
3. Pass the username to the second page as a parameter.
4. On the second page, load msal-broswer and call ssoSilent passing loginHint=USERNAME.
5. Load the page in Chrome, Firefox and Edge and verify it logs the user in correctly.
6. Load the page in Safari and see that the user is not logged-in and there is an AADSTS50058 error message in the console.

### Expected Behavior

I would expect the silent sign-in to succeed on all major browsers.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Safari

### Source

External (Customer)

**Comment by tnorling** [comment]
@qqzm Unfortunately, ssoSilent will always fail if 3P cookies are blocked, as is the default setting in Safari. Currently the only way to authenticate in this case is to invoke interaction, after you have signed in you can then invoke `acquireTokenSilent` to get tokens silently for around 24 hours. At this point `acquireTokenSilent` will throw an `Interaction_required` error which your app should catch and invoke interaction again to renew.

**Comment by qqzm** [comment]
Hi @tnorling, thanks for your reply.
Ok, in that case I have a slightly different problem - acquireTokenSilent gives the error and prompts me for interaction every single time. Even once I have already authenticated interactively on the second page, I don't get the 24 hours of working silently in Safari.

**Comment by qqzm** [comment]
Oh, I think I may have fixed it and it now logs in silently the first time. What I've done is changed the following on the request:
Instead of:
`request.loginHint = username;`
I'm now doing:
`request.account = msal.getAccountByUsername(username);`
I still need to do more testing but it seems to be fixed.

**Comment by tnorling** [comment]
Cool, keep us posted!

**Comment by qqzm** [comment]
I'm now getting the following error:

InteractionRequiredAuthError: invalid_grant: AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access 'api://[app-id]'. 

Timestamp: 2022-05-05 15:34:04Z
AuthError — AuthError.js:27
InteractionRequiredAuthError — InteractionRequiredAuthError.js:40
(anonymous function) — ResponseHandler.js:71
(anonymous function) — AuthorizationCodeClient.js:77
step — _tslib.js:75
fulfilled — _tslib.js:46
promiseReactionJob

I have tried disabling MFA on the app id in question, in makes no difference.
Again, this only occurs on Safari - it works correctly in Chrome, Firefox and Edge

**Comment by qqzm** [comment]
(Needless to say I have not made any configuration changes and I have not moved to a new location)

**Comment by tnorling** [comment]
@qqzm It's likely happening because the cookies are being blocked. Do you get the same error in Chrome Incognito? Silent calls are never guaranteed to succeed, in general your app should catch `InteractionRequiredAuthError` and invoke an interactive API

**Comment by qqzm** [comment]
My app does catch InteractionRequiredAuthError and invoke an interactive api and **that** is when this error occurs - in the call to either acquireTokenRedirect or acquireTokenPopup (I've tried both).
The error does not occur in Chrome incognito mode, just Safari.

**Comment by qqzm** [comment]
I think I have now resolved or worked around all my issues.
I've solved my original issue - the second page will now log the user in silently the first time, even in Safari or Chrome incognito. I'll post my solution code next week once I've tidied it up.

The latest issue with the AADSTS50076 error I've managed to find a workaround, which is to require MFA for all MacOS and iOS users at all times regardless of any other exceptions that might apply.

**Comment by tnorling** [comment]
> My app does catch InteractionRequiredAuthError and invoke an interactive api and that is when this error occurs - in the call to either acquireTokenRedirect or acquireTokenPopup (I've tried both).

Interactive APIs don't throw InteractionRequired. This has to be coming from an uncaught silent call somewhere

**Comment by qqzm** [comment]
Thanks, that's really helpful. The MFA error seems to have gone away so it must have been some test code or something that I've since removed.
Here's how I solved the issue with Safari IDP blocking the authentication, in case anyone comes here with the same situation as me (one page with another inside an iframe, wanting to sign-in once on the the outer page then have it silently authenticate in the iframed page).

1) Load msal library in the parent. Attempt to sign-in using acquireTokenSilent, if this fails use acquireTokenRedirect.
2) Once authentication is complete, setup a message handler to respond to window messages. Then set the url of the iframe to load the iframed app.
3) The iframed app then loads msal and sends a message to the parent via window.parent.postMessage to request the authentication data from the parent.
4) The message handler setup in step 2 responds with the account details of the current user and the contents of localStorage.
5) The ifrmaed app now proceeds with acquireTokenSilent.

Here's the relevant section of code:
```
window.addEventListener("message", (event) => {
    // Ignore messages from origins other than localhost or our domain.
    let domainRE = new RegExp('(http:\/\/localhost.*|https:\/\/[A-Za-z0-9\-\.]+' + AzureAuth.domain.replaceAll('.', '\\.') + ')');
    if (!event.origin.match(domainRE)) {
        return;
    }
    // If a subframe is asking us for authentication data, send it.
    if (event.data.message == 'getAuthenticationData') {
	if (!event.source) return;

	let account = AzureAuth.msal.getAccountByUsername(AzureAuth.username);
	let id = account.homeAccountId;
	let items = { ...localStorage };
	// Remove any items that aren't to do with this account.
	let keys = Object.keys(items);
	for (let i=0; i<keys.length; i++) {
		if (keys[i].substring(0, id.length) != id) {
			delete items[keys[i]];
		}
	}
	// Return the data by sending a message to the frame that requested it.
	event.source.postMessage({
		message: 'sendData',
		account: account,
		storage: items
	}, '*');
    }
    // Else if we are receiving data we asked for.
    else if (event.data.message == 'sendData') {
        if (!AzureAuth.paused) return;
        let keys = Object.keys(event.data.storage);
        for (let i=0; i<keys.length; i++) {
            localStorage.setItem(keys[i], event.data.storage[keys[i]]);
        }

        let request = { 
            scopes: AzureAuth.scopes,
            account: event.data.account
        };

        AzureAuth.msal.acquireTokenSilent(request)
            .then( (response) => {
		AzureAuth.username = response.account.username;
                AzureAuth.paused = false;
                resolve(AzureAuth.username);
            })
            .catch(error => {
                // Just warn for errors here. Don't want to force the user to login until they actually try to do something.
                console.warn(error);
            });
    }
}, false);

// If the client is running in iframe mode, request authentication data from our parent window.
if (AzureAuth.mode == 'iframe' && AzureAuth.isEmpty(AzureAuth.username)) {
    AzureAuth.paused = true;
    window.parent.postMessage({message: 'getAuthenticationData'}, '*');
    
    setTimeout(() => {
        // If we don't receive the data back within 2 seconds, give up waiting and allow interactive requests to proceed.
        if (AzureAuth.paused) {
            AzureAuth.paused = false;
            resolve(AzureAuth.username);
        }
    }, 2000);
}
else {
    resolve(AzureAuth.username);
}
```
