### ISSUE TITLE
Special characters in ConfidentialClientApplication.acquireTokenByUsernamePassword() breaking the Request.

### ISSUE THREAD

**Issue by priyanka-ciandt** [AzureAD/microsoft-authentication-library-for-js#4791]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.9.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

NA

### Description

I am using "ConfidentialClientApplication" to get token but it has same issue if there is special character in password it breaks the Request which going call acquire token.

I bet that it is with all the calls in msal-node because the generate is written that way. I specifically reverse engineered the @azure/msal-node code and found that all parameter merged in single string and joined by "&" and there multiple comma to in some of the values looks array of string being passed as value1, value2 .

fundamental problem either this issue should restricted at root level don't allow to use those special character to be used in password or any other values or have request validation after you build actual request. Last but not least it needs proper error handling "50126" error code for this error seemed to very mis leading. 

Version : 1.9.0 msal-node

### Error Message

50126 - [2021-12-14 21:37:35Z]: AADSTS50126: Error validating credentials due to invalid username or password.\r\nTrace ID: 885a428b-91b5-4c94-aacc-082bbfdf2000\r\nCorrelation ID: 0567c418-a6cc-4c0e-9994-747317a5a929\r\nTimestamp: 2021-12-14 21:37:35Z - Correlation ID: 0567c418-a6cc-4c0e-9994-747317a5a929 - Trace ID: 885a428b-91b5-4c94-aacc-082bbfdf2000

### here is string of request body that is build with concatenating by all params. 

'client_id=**client_id_value**&username=**username_value**&password=**pass&word**&scope=**user.read%20openid%20profile%20offline_access**&grant_type=**Grant**&client_info=1&x-client-SKU=msal.js.node& **there are multiple internal version and telemetry parameters**&client-request-id=**request_id**&client_secret=**ClientSecret**'

### MSAL Configuration

```javascript
const cachePlugin = {
  beforeCacheAccess,
  afterCacheAccess,
};

const msalConfig = {
  auth: {
    clientId: azureAd.auth.clientId,
    authority: azureAd.auth.authority,
  },
  cache: {
    cachePlugin,
  },
};
```

### Relevant Code Snippets

```javascript
const usernamePasswordRequest = {
      scopes: ['user.read'],
      username,
      password,
    };
 const response = await cca
      .acquireTokenByUsernamePassword(usernamePasswordRequest);
```

### Reproduction Steps

1.  first of all setup password with & special character in it.
2.  user that account for acquire token  password with ConfidentialClinetApplication
3.  and that is it.
4. you will that error. And same thing can happen if account name has of those invalid string request parameter.

### Expected Behavior

it should work seamlessly even if your password special character in it. Below line should be perfectly obeyed by system.
"Password can be more than 8 character long it must be a combination one of special character , Capital letter and number"

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Other

### Source

External (Customer)

**Comment by tnorling** [comment]
@priyanka-ciandt This is being tracked by #4326, updates will be posted in that issue. In the meantime you can try URI encoding the password (which is likely what msal-node should be doing under the hood to mitigate this). Closing this issue for now as duplicate
