### ISSUE TITLE
PublicClientApplication constructor parameters

### ISSUE THREAD

**Issue by Deewens** [AzureAD/microsoft-authentication-library-for-js#4795]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Documentation Location

https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-angular-auth-code#configure-the-application

### Description

I am following the documentation linked above to setup SSO with Azure on my Angular App. The documentation tells us to add the MsalModule.forRoot({...}) import, as you can see on this screenshot:

![image](https://user-images.githubusercontent.com/26287270/167115491-7eec66f6-6caa-46c6-97c0-c53c764c069f.png)

However, there are two other parameters to give to the PublicClientApplication constructor, which should be "null" according to the documentation. However, as you can see on the screenshot below, the TS compiler is not happy and is telling me that "null" value is not possible. I don't know if the issue come from the code or if the documentation is wrong, but I am not sure what to put instead.

![image](https://user-images.githubusercontent.com/26287270/167115649-fafe7c50-97c1-4b13-9ec9-5b94ec2e0a35.png)

Thank you.

**Comment by tnorling** [comment]
@Deewens Apologies for the confusion. That tutorial takes you step by step in setting up an Angular app from the ground up. As such, some of the individual code snippets may be incomplete until you get further into the tutorial. If you scroll down you'll find a section that has you replace those `null` placeholders with the `MsalGuard` and `MsalInterceptor` configs. I'll see what we can do to make these docs more intuitive.

Were you just wanting to understand how to get up and running or is your desire to configure an app without the Guard or Interceptor?

**Comment by Deewens** [comment]
Hi!

Thanks for your reply! When I scrolled down I found the other parts about MsalGuard and MsalInterceptor. It is not really intuitive, however. I think it would be best to add the required parameter (if it is really mandatory) and explain with a comment why it is there and that will be described in a later part.

I just wanted to understand how to get up and running, but I am also curious to know how I can configure without the Guard/Interceptor?

Btw, the error arises only for the `MsalGuard` param and not for the `MsalInterceptor `param.

Thanks for your quick response!

**Comment by tnorling** [comment]
@Deewens Thanks, I agree the tutorial could be more clear in this regard. I've noted your feedback and will see what we can do to improve this for future users.

As for not using the Guard or Interceptor, the configs are required but you don't have to protect any routes or APIs.

You could set the configs to the minimum required, something like this and then if you don't want to guard any routes you don't have to and this config will just be ignored.

```javascript
{
  interactionType: InteractionType.Redirect
}
```

**Comment by Deewens** [comment]
@tnorling Alright, thanks for your answer!
