### ISSUE TITLE
After login it will redirect to default page even if set `navigateToLoginRequestUrl: false`

### ISSUE THREAD

**Issue by WellyHong** [AzureAD/microsoft-authentication-library-for-js#4796]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.24.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

N/A

### Description

We implement Azure AD login via @azure/msal-browser and encounter unexpected behavior after upgrading from  2.14.0 to 2.23.0.
We use `history.push` to go to a specific url (e.g. `https://mywebsite.com/#/app`) after `handleRedirectPromise()`.
But it will redirect to default page (e.g. `https://mywebsite.com/#/`) first then go to specific path. 
It causes that users see a blink page after login and feel weird.
It could be related to [the reason](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/3609#issuecomment-1077586879).

### MSAL Configuration

```javascript
export const MsalConfig = {
  auth: {
    clientId: AAD_CLIENT_ID,
    authority: `https://login.microsoftonline.com/${AZURE_TENANT_ID}`,
    redirectUri,
    navigateToLoginRequestUrl: false,
  },
  cache: {
    cacheLocation: 'localStorage', // This configures where your cache will be stored
    storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
  },
};
```

### Relevant Code Snippets

```javascript
msal.handleRedirectPromise().then((response) => {
    if (response !== null) {
      handleAzureLogin(response);
      history.push(PATH.APP_LIST);
    } else {
      const currentAccounts = msal.getAllAccounts();
      if (currentAccounts === null) {
        return;
      }
      if (currentAccounts.length > 1) {
        // Add choose account code here
        console.warn('Multiple accounts detected.');
      } else if (currentAccounts.length === 1) {
        const { username } = currentAccounts[0];
        history.push(PATH.APP_LIST);
      }
    }
  }).catch((err) => {
    console.error(err);
  });
```

### Reproduction Steps

1. set `navigateToLoginRequestUrl: false`
2. login & handleRedirectPromise()
3. it redirect to default page, e.g. https://mywebsite.com/#/

### Expected Behavior

It wont redirect to default page (e.g. `https://mywebsite.com/#/`) if set `navigateToLoginRequestUrl: false`.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Safari

### Source

External (Customer)

**Comment by tnorling** [comment]
@WellyHong Looks like you're using hash routing, can you please confirm? The identity provider returns responses back to the application via the hash in the url, which MSAL extracts and then clears (which is why it redirects to `/#/`). This is expected behavior, however, if you would like to end up on a different route than `/#/` you can flip `navigateToLoginRequestUrl` to `true` and MSAL will handle getting you back to the page that made the request or the page specified in the request via the `redirectStartPage` property.

**Comment by WellyHong** [comment]
@tnorling 
exactly, we use hash routing.
we face same situation after setting `navigateToLoginRequestUrl: true` & specific request via `redirectStartPage`. ☹️  
suggestions are greatly appreciated.

**Comment by tnorling** [comment]
@WellyHong I'm not sure I fully understand the issue, can you please clarify? Like I said, removing the hash is expected behavior and is done to prevent the auth code from being accessible in browser history.

**Comment by WellyHong** [comment]
@tnorling 
sorry for the late reply, like you said, removing the hash is expected behavior.
I found the issue was caused by `contentWindow.location.hash = Constants.EMPTY_STRING;`;
It will cause browser reload, so we see a blink (default page, e.g. https://mywebsite.com/#/) after login.
Can you give me any suggestion on this matter.

**Comment by tnorling** [comment]
@WellyHong I see now. You want to go directly to your intended hash without the intermediate stage of clearing the hash, is that right? I don't have a solution for you right now but I'll add an item to our backlog to investigate.

**Comment by tnorling** [comment]
@WellyHong After looking at this further I'm not sure we can address this from our side without breaking other scenarios we need to support. If this is still an issue for you my suggestion would be to have the home route (`/#/`) and the auth code route (`/#code=`) render the same content so that the removal of the auth code doesn't cause your site to re-render.
