### ISSUE TITLE
Cannot use query or form_post for response_mode

### ISSUE THREAD

**Issue by KevinMcDonnell-BC** [AzureAD/microsoft-authentication-library-for-js#480]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version 70.0.3538.77 (Official Build) (64-bit)
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 0.2.3

## Current behavior
MSAL enforces response_mode=fragment

## Expected behavior
Default to response_mode=fragment but add response_mode to the config and allow query and form_post. This would be particularly useful for Angular Routing with Azure B2C scenarios

</code></pre>

**Comment by navyasric** [comment]
@kevmcdonk Here is a link to the OAuth implicit flow spec which allows only response_type= token:
https://tools.ietf.org/html/rfc6749#section-4.2.1

**Comment by leniel** [comment]
This is also the problem here: https://stackoverflow.com/a/54129602/114029 when trying to use `app.UseOpenIdConnectAuthentication`.
