### ISSUE TITLE
Documentation on loadExternalToken

### ISSUE THREAD

**Issue by svrooij** [AzureAD/microsoft-authentication-library-for-js#4809]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

Not Applicable

### Documentation Location

docs.microsoft.com

### Description

Recently I’ve been experimenting with an existing Angular SPA, with `@azure/msal-angular` in combination with a teams tabs. We figured out a hack-y-way to use information from the access token that we got from Teams SSO (the Teams app is pre-authorized, and can be instructed to request an access tokens for our custom api) and creating both an account and registering the access token for our api.

Then I started looking in the code and found [this code](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/90365303db30da0fb4817b3e075db137a1ee3e33/lib/msal-browser/src/cache/TokenCache.ts#L49-L85) `loadExternalToken(…)`, this seems useful instead of us doing the same, while making direct calls to private methods on the browsercache.

But I cannot find a sample or any documentation on this advanced, well hidden, method. Maybe @tnorling can enlighten us?

Our higher goal is to still keep using msal-angular, but also using the access token we get from Teams SSO. Because that will make the process for the user a bit more smooth (skipping the login pop-up, that closes automatically anyway).

**Comment by derisen** [comment]
@svrooij the document on `loadExternalToken` can be found [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/testing.md). However this approach shouldn't be used outside of testing scenarios -it sounds like this is what you're aiming at. Can you elaborate a bit more on your scenario? You should be able to make use of the teams sso access token to call a resource via the OBO pattern shown [here](https://github.com/derisen/teams-dev-samples/tree/master/samples/tab-sso/src/nodejs).

**Comment by svrooij** [comment]
@derisen Sure I can elaborate on our scenario. We have an API protected with Azure AD token. We already have an angular app using this api (it's hosted as Azure Static Web App, combining both the SPA and the API on a single domain). The angular app uses MSAL to get tokens for the api.

Now we want a portion of the angular app to be available in Teams. In teams you have two options to get a token, you can open a special pop-up and use MSAL there. In this case the user is shown a pop-up, and the pop-up will likely disappear without user interaction, because teams supplies us with the tenant and the login hint.

The second option is to call some teams sdk javascript method, which tells the teams client to just generate an access token for the api (specified in the app manifest). In this case the access token is requested by the teams client id, but the audience is our custom api. And there is no user interaction required.

For us not the change anything to the code calling our custom api with the access token, the token needs to be registered to MSAL. So that it's picked up by the MsalInspector.

Once we have the token on the custom api, we are able to call graph with the obo flow, but the issue is in getting the token in Msal so it's send to the custom api by the MsalInspector.

We now take the information from the access token that we get from teams and create an account for that, and register the token as both the identity token and the access token (hence the "hacky" in my description).

**Comment by derisen** [comment]
@svrooij I see. IMHO modifying the existing code (perhaps via a custom interceptor) to accommodate the SSO token from Teams SDK  would be less of a hurdle in future than opening the app to unpredictable behavior by using the loadExternalToken API.

**Comment by svrooij** [comment]
Building a custom Interceptor seems like more hassle then injecting the token…. That is because then we would need to copy the entire code of the current interceptor and add a new way when the client is in teams. That is because the current interceptor has all its method defined as private, so you cannot extend it and re-use the existing code.

You pointed me to the documentation of the loadExternalToken method, so that will make my solution a bit more stable. Eventually the Teams app should be supporting MSAL (in my opinion), but until then we will be injecting the token. And getting this desire some attention.

**Comment by tnorling** [comment]
@svrooij We **strongly** discourage using the `loadExternalToken` API for anything other than testing. If you choose to use it in production, please know that you do so at your own risk and we make no guarantees that we will support issues that arise from it. Furthermore, by injecting the tokens you are creating a 2nd source of truth in terms of cached tokens (one in the Teams context and another in MSAL context), this may create more unintended issues down the line.

The recommended approach, as Dogan mentioned, is to write a custom interceptor. The provided interceptor was designed to address the most common use cases but we are aware that it may not address all scenarios, writing a custom one is the way to go if you find the one provided doesn't meet your needs.

**Comment by svrooij** [comment]
@tnorling understood!

A solution might be to provide enough information to the loginscreen through the query string that it logs in automatically. Is that something that would be possible?

I think that if the application is consented for that user opening the login screen with the domain set and the loginHint it might not ask the user for more info and just continue (and auto close).

**Comment by tnorling** [comment]
Yes theoretically, if a user is already signed in and you provide a hint (`login_hint` [optional claim](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims) is the best one to use) to MSAL it __can__ sign you in without interaction, however, there may still be cases where interaction may be required such as when the user's session has expired or MFA is required.

**Comment by svrooij** [comment]
Thanks for the explanation. This issue can be closed
