### ISSUE TITLE
IDToken roles between two react applications

### ISSUE THREAD

**Issue by zzbxd** [AzureAD/microsoft-authentication-library-for-js#4810]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.19.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.1.1

### Description

I have two react applications using same tenant, I register two applications in Azure AD for them. I use the IDToken role to control GUI.

When I log in to first app, I get the first app's IDToken role; -- expected
Then I goto second app, no need login,  -- expected
but second app's IDtoken role still show the first app's ID token role. --??? 

Is there anyway to get the second app's IDToken role?

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by tnorling** [comment]
@zzbxd Can you please share code snippets showing how you are retrieving the roles? Are both apps hosted on the same domain?

**Comment by zzbxd** [comment]
Both apps running on local http://localhost:3000; Of course they can not run same time, so I start one, stop it, then start another one.

Here are the code for getting idtoken roles:
`
  const { instance, inProgress } = useMsal();`
`
  const activeAccount = instance.getActiveAccount();`
`
  const roles = activeAccount.idTokenClaims.roles;
`

**Comment by tnorling** [comment]
I see. Because both apps are running on the same domain they will share storage and accounts are not tied to any app ID. If you need to get the most up to date roles I would suggest pulling them from the idToken, rather than from the account. You can call `acquireTokenSilent` with the account object and then read the roles from the response.

```javascript
const activeAccount = instance.getActiveAccount();
const response = await instance.acquireTokenSilent({account: activeAccount});
const roles = response.idTokenClaims.roles;
```

**Comment by zzbxd** [comment]
So, what's the exact meaning of 'same domain' here? 
- If say I hosted those two apps separately on app1.example.com and app2.example.com, will app1 get its IDToken Role and app2 also get its IDToken Role?
- Or does it mean I had to host them separately on app1.domain1.com and app2.domain2.com to get their own IDToken roles?

Also, I tried to apply your code into both app1 and app2, and repeat the test:
For app1, I successfully get the roles;
Then run app2, get error messages _InteractionRequiredAuthError: no_tokens_found: No refresh token found in the cache. Please sign-in._ on line `const response = await instance.acquireTokenSilent({account: activeAccount});`

**Comment by tnorling** [comment]
`app1.example.com` and `app2.example.com` are considered different domains for the purposes of caching (this is enforced by browsers, not by MSAL).

When you get an InteractionRequired error you should fallback to acquireTokenPopup or acquireTokenRedirect
