### ISSUE TITLE
Auto Redirect if from login page if user is Logged in

### ISSUE THREAD

**Issue by Mohdaqib1** [AzureAD/microsoft-authentication-library-for-js#4812]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

2.21.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

None

### Description

1.Whenever I see my output after saving by writing something wrong in my code and then I fix it and then see output so our login page is shown sometimes.
2.Whenever I change the tab then our login page is shown sometimes.
I login or refresh to remove it so then it goes away
It would be great if someone can help here?

### Source

External (Customer)

**Comment by tnorling** [comment]
@Mohdaqib1 I unfortunately don't understand your question, can you please provide more details? Code snippets showing how you are using the library and a brief explanation of what is happening vs what you expect to happen and steps to reproduce would help clarify. Thanks!

**Comment by Mohdaqib1** [comment]
> Even after being logged in if someone writes a login inside the url, it redirects to the login page.

**Comment by tnorling** [comment]
@Mohdaqib1 I'm sorry but I still don't understand. Can you please provide the following:

1. Code snippets showing how you are using the library
2. Steps to reproduce the issue and/or a short video showing the behavior
