### ISSUE TITLE
"initialize has already been called once" warning in console upon app start.

### ISSUE THREAD

**Issue by kjkent** [AzureAD/microsoft-authentication-library-for-js#4813]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.24.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.0

### Description

Upon starting a React development server with `npm start`, a warning message appears that `initialize` has already been called, despite (unless I've messed up somewhere) me laying out the project as described in the tutorials/docs, including the docs for [usage with React Router](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/performance.md).

### Error Message

```
[Mon, 16 May 2022 09:57:29 GMT] : @azure/msal-browser@2.24.0 : Warning - initialize has already been called. This function only needs to be run once.
loggerCallback @ authConfig.js:98
```

### Msal Logs

```
[Mon, 16 May 2022 09:57:29 GMT] : @azure/msal-browser@2.24.0 : Info - Emitting event: msal:initializeStart
authConfig.js:92 [Mon, 16 May 2022 09:57:29 GMT] : @azure/msal-browser@2.24.0 : Info - Emitting event: msal:initializeEnd
authConfig.js:98 [Mon, 16 May 2022 09:57:29 GMT] : @azure/msal-browser@2.24.0 : Warning - initialize has already been called. This function only needs to be run once.
loggerCallback @ authConfig.js:98
authConfig.js:92 [Mon, 16 May 2022 09:57:29 GMT] : @azure/msal-browser@2.24.0 : Info - Emitting event: msal:handleRedirectStart
authConfig.js:92 [Mon, 16 May 2022 09:57:29 GMT] : [b58d0025-cbdd-4fa7-b753-819bfea15fb5] : msal.js.browser@2.24.0 : Info - handleRedirectPromise called but there is no interaction in progress, returning null.
authConfig.js:92 [Mon, 16 May 2022 09:57:29 GMT] : @azure/msal-browser@2.24.0 : Info - Emitting event: msal:handleRedirectEnd
authConfig.js:92 [Mon, 16 May 2022 09:57:29 GMT] : @azure/msal-react@1.4.0 : Info - MsalProvider - msal:handleRedirectStart results in setting inProgress from startup to handleRedirect
authConfig.js:92 [Mon, 16 May 2022 09:57:29 GMT] : @azure/msal-react@1.4.0 : Info - MsalProvider - msal:handleRedirectEnd results in setting inProgress from handleRedirect to none
authConfig.js:92 [Mon, 16 May 2022 09:57:29 GMT] : @azure/msal-react@1.4.0 : Info - MsalProvider - msal:handleRedirectStart results in setting inProgress from startup to handleRedirect
authConfig.js:92 [Mon, 16 May 2022 09:57:29 GMT] : @azure/msal-react@1.4.0 : Info - MsalProvider - msal:handleRedirectEnd results in setting inProgress from handleRedirect to none
```

### MSAL Configuration

```javascript
{
    auth: {
        clientId: process.env.REACT_APP_MSAL_CLIENT_ID,
        authority: b2cPolicies.authorities.signIn.authority,
        knownAuthorities: [b2cPolicies.authorityDomain],
        redirectUri: "/ece",
        postLogoutRedirectUri: "/",
        navigateToLoginRequestUrl: false
    },
    cache: {
        cacheLocation: "sessionStorage"
    }
```

### Relevant Code Snippets

```javascript
// index.js

const root = ReactDOM.createRoot(document.getElementById("root"));
const msalInstance = new PublicClientApplication(msalConfig);

root.render(
    <React.StrictMode>
        <Provider store={store}>
            <BrowserRouter>
                <CssBaseline />
                <App msalInstance={msalInstance}/>
            </BrowserRouter>
        </Provider>
    </React.StrictMode>
);
```

```javascript
// App.js

const App = ({msalInstance}) => {
	const navigate = useNavigate();
	const dispatch = useDispatch();
	const navigationClient = new CustomNavigationClient(navigate);
	msalInstance.setNavigationClient(navigationClient);

	return (
		<MsalProvider instance={msalInstance}>
			<Routes>
				<Route path="/" element={<HomeLayout />}>
					<Route path="/" element={<HomeContent />} />
				</Route>
				<Route path="/404" element={<NotFound />} />
				<Route path="*" element={<Navigate to="/404" replace />} />
			</Routes>
		</MsalProvider>
	);
};
```

```javascript
// msalNavClient.js

export default class CustomNavigationClient extends NavigationClient {
    constructor(navigate) {
        super();
        this.navigate = navigate;
    }

    async navigateInternal(url, options) {
        const relativePath = url.replace(window.location.origin, "");
        if (options.noHistory) {
            this.navigate(relativePath, { replace: true });
        } else {
            this.navigate(relativePath);
        }
        return false;
    }
}
```

### Reproduction Steps

1. Run app in development server
2. Error occurs

### Expected Behavior

1. `initialize` is only called once and the error and log message do not occur.

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by tnorling** [comment]
@kjkent This happens because React StrictMode mounts your react components twice and `initialize` is called when `MsalProvider` is mounted. This log message can be safely ignored.

**Comment by kjkent** [comment]
@tnorling Thanks so much for the clarification. Would you accept a PR to include this info on [this docs page](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/errors.md)?

**Comment by tnorling** [comment]
@kjkent In general yes, we welcome PRs, however, I want to be clear that this is **not** an error and would not be appropriate for that doc. It is merely a log message, which you can turn off by not configuring the logger (which you should only configure during development or debugging anyway).

**Comment by kjkent** [comment]
@tnorling I can appreciate that this is not an error message and perhaps that is the wrong doc page. However, it **is** a warning message. As warnings highlight potentially adverse behaviour, I think I would disagree with the assertion that it's on par with the other, purely informational log messages. If in this case the warning can be disregarded, I would guess the community might benefit from that info outside of this issue thread.

If you disagree, I respect that and ask you close the issue.

**Comment by tnorling** [comment]
I understand the message is potentially confusing, we may need to rethink if warning is appropriate or if the wording needs to be rephrased.  There is no adverse behavior in calling `initialize` more than once as MSAL will immediately return on subsequent invocations, the log message was intended to point out that subsequent calls will not do anything and are unnecessary.

**Comment by kjkent** [comment]
That's fair enough. Thanks again for your input, @tnorling , it's much appreciated.

**Comment by tnorling** [comment]
Opened a PR to address. Let me know if the changes help resolve your concerns around this. Thanks!

**Comment by kjkent** [comment]
Apologies for the slow response; I just looked through the PR and I definitely agree with the changes. Thanks for being so open to feedback about this :).
