### ISSUE TITLE
Transition from passport-azure-ad to msal-node

### ISSUE THREAD

**Issue by harishnarain** [AzureAD/microsoft-authentication-library-for-js#4816]
### Core Library

Passport Azure AD (passport-azure-ad)

### Core Library Version

4.3.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

We're currently looking to get clarification on whether we should be transitioning from passport-azure-ad to msal-node? There seems to be some conflicting information on passport-azure-ad only being in maintenance mode but other resources stating that for validating token should still be done with passport-azure-ad.

We're currently using BearerStrategy, IBearerStrategyOptionWithRequest, ITokenPayload and VerifyCallback in passport-azure-ad with Express.js. Is there a recommended transition to msal-node with Passport.js from passport-azure-ad?

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
@harishnarain passport-azure-ad is in maintenance and is not receiving any updates besides critical security fixes. `msal-node` can be used to acquire tokens, however, we do not yet have a token validation replacement for passport-azure-ad. A replacement token validation library is currently in active development.
