### ISSUE TITLE
How to configure Microsoft Login Dialogue while using MSAL Library  for Angular 13

### ISSUE THREAD

**Issue by siddarthapal** [AzureAD/microsoft-authentication-library-for-js#4817]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

2.23.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.2.0

### Description

[Forum.docx](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/8711656/Forum.docx)

Hi MSAL Lib Team

Please refer the word document to view the query.

best regards

### MSAL Configuration

```javascript
export function MSALInstanceFactory(): IPublicClientApplication {
  return new PublicClientApplication({
    auth: {
      clientId: environment.clientId,
      authority: environment.authority,
      redirectUri: '/',
      postLogoutRedirectUri: '/'
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE, // set to true for IE 11. Remove this line to use Angular Universal
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Info,
        piiLoggingEnabled: false
      }
    }
  });
}
```

### Relevant Code Snippets

```javascript
NA
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by tnorling** [comment]
@siddarthapal Can you please describe your question in detail and provide relevant code snippets showing what you've tried? Thanks!

**Comment by siddarthapal** [comment]
@tnorling I have added a a word document describing the scenario. Could you please have a look?
In simple words, I want to replicate the login and logout process which happens when we connect to "Azure Portal", on our portal. And it's something related to re-direct flow....

**Comment by tnorling** [comment]
@siddarthapal I would prefer not to download files in order to answer questions. Please copy over the relevant details into the issue body above and I would be happy to help resolve whatever issues you are having. Thanks!

**Comment by siddarthapal** [comment]
I have found solution to this issue eventually and sorry for the late update.
