### ISSUE TITLE
React-Apollo: azure msal-browser does not return token

### ISSUE THREAD

**Issue by alakdam07** [AzureAD/microsoft-authentication-library-for-js#4818]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.24.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.0

### Description

I am moving my package from [react-adal](https://www.npmjs.com/package/react-adal) to [@azure/msal-react](https://www.npmjs.com/package/@azure/msal-react). In [react-adal](https://www.npmjs.com/package/react-adal) I can authorise and able to go my app. I am using same `client_id` and `Tenant_id` but seems like `getAllAccounts()` returns me empty array, it means no user found as a result I am not getting any token. I used exactly same what the doc says. I am not sure what I am making mistake. 

### MSAL Configuration

```javascript
import { Configuration, PopupRequest, PublicClientApplication } from '@azure/msal-browser'

export const msalConfig: Configuration = {
  auth: {
    clientId: process.env.NEXT_PUBLIC_MSAL_CLIENT_ID || '',
    redirectUri: process.env.NEXT_PUBLIC_MSAL_REDIRECT_URL,
    authority: `https://login.microsoftonline.com/${process.env.NEXT_PUBLIC_MSAL_TENANT}`,
    navigateToLoginRequestUrl: true,
  },
  cache: {
    cacheLocation: 'localStorage', // This configures where your cache will be stored
    storeAuthStateInCookie: false,
  },
}

export const loginRequest: PopupRequest = {
  scopes: ['User.Read'],
}

export const msalInstance = new PublicClientApplication(msalConfig)

const currentAccounts = msalInstance.getAllAccounts()

console.log({ currentAccounts }) // returns empty array
```

### Relevant Code Snippets

```javascript
This is how I warp my app with MsalProvider


import { ApolloProvider } from '@apollo/client'
import { MsalProvider } from '@azure/msal-react'
import { defaultClient } from 'apollo'
import { msalInstance } from 'msal-auth-config' // import msalInstance from config
import type { AppProps } from 'next/app'
import React from 'react'


const App = ({ Component, pageProps }: AppProps): JSX.Element => {

  return (
    <MsalProvider instance={msalInstance}>
      <ApolloProvider client={defaultClient}>
        <App />
      </ApolloProvider>
    </MsalProvider>
  )
}

export default App

```

Apollo Auth link

```
const authLink = setContext((_operation, { headers }) => {
 
  const accounts = msalInstance.getAllAccounts() // return [ ]
  //console.log({ accounts, headers })

  if (accounts.length > 0) {
    msalInstance.setActiveAccount(accounts[0])
  }

  return msalInstance
    .acquireTokenSilent(loginRequest)
    .then((response) => {
      console.log(response) // return undefined
      return { headers: { ...headers, Authorization: `Bearer ${response.idToken}` } }
    })
    .catch((error) => {
      if (error instanceof InteractionRequiredAuthError) {
        return msalInstance.acquireTokenRedirect(loginRequest)
      }

      return
    })
})
```
```


### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by alakdam07** [comment]
@tnorling any clue?

**Comment by tnorling** [comment]
@alakdam07 Your call to `getAllAccounts` is likely happening before the login has completed. If you have logic dependent on users being signed in or out, you should write that logic inside a React component underneath the `MsalProvider` by either using the provided React methods, such as the `accounts` context value returned by the `useMsal` hook, or by checking the `inProgress` value before attempting to retrieve accounts.

**Comment by alakdam07** [comment]
Could you please show me code sample?

**Comment by alakdam07** [comment]
@tnorling  I console logged the `Progress` and `Accounts ` in my App component. The  `Progress` is always `none`status. That is what I get 👇🏾👇🏾👇🏾
<img width="998" alt="Screenshot 2022-05-19 at 10 04 02" src="https://user-images.githubusercontent.com/47625626/169230880-9f2fa68c-813b-485f-88e7-f7645c6319d5.png">

**Comment by tnorling** [comment]
@alakdam07 Can you show the code snippets of where you put this? It needs to be somewhere underneath the `MsalProvider` (default value for accounts is [] and inProgress is "none" if you try to access from outside context)

**Comment by alakdam07** [comment]
<img width="643" alt="Screenshot 2022-05-24 at 8 51 41" src="https://user-images.githubusercontent.com/47625626/169958518-c7e0e7df-de67-4b11-8eeb-f9ef90713416.png">

**Comment by alakdam07** [comment]
Also I am getting CORS error:`'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by tnorling** [comment]
@alakdam07 This logic needs to be somewhere **underneath** the `MsalProvider` component. Right now your console.log statement lives above it.

Regarding the CORS error please see [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/errors.md#access-to-fetch-at-url-has-been-blocked-by-cors-policy)
