### ISSUE TITLE
loginRedirect() does not automatically redirect on iOS with Intune

### ISSUE THREAD

**Issue by hiroki-nishida-avanade** [AzureAD/microsoft-authentication-library-for-js#4822]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.24.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.0

### Description

We have an SSO app using the msal-react.
The app works on a PC, but it doesn't work as expected when accessed from an Edge browser on iOS with Microsoft Intune.
The app is not automatically redirected by loginRedirect() and must be reloaded manually by the user.

### MSAL Configuration

```javascript
{
  auth: {
    clientId: `CLIENT_ID`,
    authority: 'https://login.microsoftonline.com/`TENANT_ID`',
    redirectUri: `APP_URL`,
  },
  cache: {
    cacheLocation: 'sessionStorage',
    storeAuthStateInCookie: false,
  },
}
```

### Relevant Code Snippets

```javascript
import { InteractionStatus } from '@azure/msal-browser';
import { useMsal } from '@azure/msal-react';

const loginRequest = {
  scopes: [
    'User.Read',
  ],
};

const { instance, inProgress } = useMsal();

React.useEffect(() => {
  if (inProgress !== InteractionStatus.None) return;
  (async () => {
    try {
      const accounts = instance.getAllAccounts();
      if (accounts.length > 0) {
        // get a token for Graph API
      } else {
        await instance.loginRedirect({
          ...loginRequest,
        });
      }
    } catch (error) {
      console.log(error);
    }
  })();
}, [
  instance,
  inProgress,
]);
```

### Reproduction Steps

1. successful login to the account (iOS with Intune)
2. call loginRedirect()

### Expected Behavior

As with PC access, users should be able to run the app without manual reloading.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Edge

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@HLNishida We're aware of this issue, but have been unable to prioritize a fix. See this comment for a workaround: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4458#issuecomment-1026614100

**Comment by hiroki-nishida-avanade** [comment]
I successfully fixed the problem with the comment.
Thanks!
