### ISSUE TITLE
How to handle multiple concurrent requests that require interaction

### ISSUE THREAD

**Issue by RaulBurian** [AzureAD/microsoft-authentication-library-for-js#4824]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.22.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.3.0

### Description

In our application we have some points where we make multiple API requests at the same time.

In order to do that we try to obtain a token with `msal` for every request first using the silent way and falling back to interactive token acquisition with popup if the silent one throws an error.

However, since there are multiple requests done concurrently we can run into the issue of an interactive acquisition being in progress when another one is to get started.

We tried to serialize the execution of the interactive requests on our side but that added a lot of complexity and made the process harder to understand. We were wondering if there is any guidance of a way / better way to handle when you have to deal with multiple interactions at the same time?

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by tnorling** [comment]
@RaulBurian You should not need to invoke more than one interaction. What I mean by that is that, when interaction is required by one or more invocations of `acquireTokenSilent` you will only need to invoke interaction on one of them and then retry the silent call for the others when the interaction is complete. You should not need to serialize interactive calls. 

The implementation would be different depending on whether you use redirects or popups for interaction but the general idea is that you should invoke interaction when `interactionRequired` is thrown **and** `inProgress === InteractionStatus.None`. If `inProgress` is anything other than `None` you should wait until it is and then retry your token acquisition logic (including the silent token acquisition). This would result in only the first failure invoking interaction and subsequent failures should be able to acquire their tokens silently after interaction is complete.

**Comment by RaulBurian** [comment]
Thank you for the help!
