### ISSUE TITLE
@azure/msal-browser and @azure/msal-angular failing on latest package version

### ISSUE THREAD

**Issue by dhirajv07** [AzureAD/microsoft-authentication-library-for-js#4825]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.24.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.3.0

### Description

msal-angular 2.2.0 is restoring in UAt and working fine,  but msal-angular 2.3.0 is being restored in QA and breaking

### Error Message

Generating browser application bundles (phase: setup)...An unhandled exception occurred: Script file node_modules/@azure/msal-angular/__ivy_ngcc__/bundles/azure-msal-angular.umd.js does not exist.
See "C:\Users\MOHKHA~1\AppData\Local\Temp\ng-uFfHcP\angular-errors.log" for further details.

### Msal Logs

NA

### MSAL Configuration

```javascript
currently this is in the package.json

"@azure/msal-angular": "^2.0.0",
"@azure/msal-browser": "^2.14.2",
```

### Relevant Code Snippets

```javascript
currently this is in the package.json

"@azure/msal-angular": "^2.0.0",
"@azure/msal-browser": "^2.14.2",
```

### Reproduction Steps

currently this is in the package.json

"@azure/msal-angular": "^2.0.0",
"@azure/msal-browser": "^2.14.2",

### Expected Behavior

Build Successful

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by taylorhutchison** [comment]
Have you tried deleting node_modules folder, npm installing again, and checking in your package-lock.json file?
