### ISSUE TITLE
If the browser has logged in to two Azure accounts, the logout popup does not close automatically when user select one to logout.

### ISSUE THREAD

**Issue by super-chen** [AzureAD/microsoft-authentication-library-for-js#4826]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.22.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.3.1

### Description

**Precondition**
Log in with an Azure account, and it exists two Azure accounts on the browser

**Steps**
1. Login with one of the Azure account
2. Show logout popup when I call instance.logoutPopup()
3. Select one of the accounts to logout
4. The popup window can't be closed auto. Need user to close manually

**Expected Results:**
Log out popup window will close auto and then back to the login page

![image](https://user-images.githubusercontent.com/1482026/169438890-0acaacf2-cdeb-4a82-8bfa-e60f0ed69022.png)
![image](https://user-images.githubusercontent.com/1482026/169440181-f0f5e2a8-adef-4b31-8c7d-d460095d4916.png)

### MSAL Configuration

```javascript
auth: {
    clientId: `16878cc5-e503-46fb-894c-d08da3a0a1f0`,
    authority: `https://login.microsoftonline.com/537426a3-f8c5-4fa5-89e0-6898ffe70c96`,
    redirectUri: `http://localhost:3000/black.html`
  },
  cache: {
    cacheLocation: 'sessionStorage', 
    storeAuthStateInCookie: false
  }
```

### Relevant Code Snippets

```javascript
instance
      .loginPopup({
        scopes: ['User.Read'],
        redirectUri: `http://localhost:3000/black.html`
      })

instance
      .logoutPopup({
        account: instance.getAccountByHomeId(accounts[0].homeAccountId),
        mainWindowRedirectUri: '/',
        postLogoutRedirectUri:'http://localhost:3000/black.html'
      })
```

### Reproduction Steps

**Precondition**
Log in with an Azure account, and it exists two Azure accounts on the browser

**Steps**
1. Login with one of the Azure account
2. Show logout popup when I click logout
3. Select one of the accounts to logout
4. Can't auto close the popup window. Stay on the following screen page

![image](https://user-images.githubusercontent.com/1482026/169441586-8d2091e1-a426-4b96-a867-d35303caf90f.png)

### Expected Behavior

Log out popup window will close auto. Don't need a user manual to do that.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
@super-chen I was not able to reproduce this. Does this also reproduce with only a single account signed in? Does it matter if you are signing out of an AAD account or MSA account or does this reproduce with both? Have you followed the `postLogoutRedirectUri` instructions in [this doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md)?
