### ISSUE TITLE
@azure/msal-browser and @azure/msal-react fails on latest version

### ISSUE THREAD

**Issue by josefhardelin** [AzureAD/microsoft-authentication-library-for-js#4827]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.24.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.3.2

### Description

I get the following error. Works on previous version

### Error Message

react.development.js:2467 
        
       Uncaught TypeError: instance.initialize is not a function
    at eval (msal-react.esm.js:268:14)
    at xy (react-dom.development.min.js:1:214302)
    at HTMLUnknownElement.g (react-dom.development.min.js:1:48705)
    at Object.kr (react-dom.development.min.js:1:49030)
    at Pr (react-dom.development.min.js:1:49992)
    at Ey (react-dom.development.min.js:1:214842)
    at unstable_runWithPriority (react.development.js:2942:14)
    at dd (react-dom.development.min.js:1:101890)
    at wy (react-dom.development.min.js:1:214043)
    at react-dom.development.min.js:1:213363

### MSAL Configuration

```javascript
export const msalConfig = {
  auth: {
    clientId: "*****",
    authority:
      "https://login.microsoftonline.com/*****",
    redirectUri: __CLIENTROOT__,
  },
  cache: {
    cacheLocation: "sessionStorage", // This configures where your cache will be stored
    storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
  },
  system: {
    loggerOptions: {
      loggerCallback: (level, message, containsPii) => {
        if (containsPii) {
          return;
        }
        switch (level) {
          case LogLevel.Error:
            console.error(message);
            return;
          case LogLevel.Info:
            console.info(message);
            return;
          case LogLevel.Verbose:
            console.debug(message);
            return;
          case LogLevel.Warning:
            console.warn(message);
            return;
        }
      },
    },
  },
};
```

### Relevant Code Snippets

```javascript
export const msalInstance = new PublicClientApplication(msalConfig);

const appdiv = document.getElementById("rc-app");
ReactDOM.render(
  <Router>
    <React.StrictMode>
      <ClientSideNavigation pca={msalInstance}>
        <MsalProvider instance={msalInstance}>
          <UhThemeProvider>
            <App />
          </UhThemeProvider>
        </MsalProvider>
      </ClientSideNavigation>
    </React.StrictMode>
  </Router>,
  appdiv
);
```

### Reproduction Steps

1. Follow this [sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/react-18-sample)

### Expected Behavior

This should work

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Regression

@azure/msal-browser@2.23.0 @azure/msal-react@1.3.2

### Source

External (Customer)

**Comment by tnorling** [comment]
@josefkvist Please try deleting your node_modules/package-lock and reinstalling.
