### ISSUE TITLE
CacheManager.isAuthorityMetadata blocks main thread

### ISSUE THREAD

**Issue by mhmoritz** [AzureAD/microsoft-authentication-library-for-js#4828]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.9.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

0

### Description

We observe isolated but regular performance bottlenecks for about 2-3 weeks now, caused by a blocked main thread in a node.js application. According to the CPU profile recorded during the outages, node gets stuck on validating `CacheManager.isAuthorityMetadata`:

![performance-cpu-github](https://user-images.githubusercontent.com/27928129/169547023-f7fa55bb-6d19-445f-b4ea-9beef3ea9255.png)

### MSAL Configuration

```javascript
{
  auth: {
    clientId: CLIENT_ID,
    authority: 'https://login.microsoftonline.com/common',
    knownAuthorities: [],
    redirectUri: REDIRECT_URI,
    postLogoutRedirectUri: `${REDIRECT_URI}/logout`,
    navigateToLoginRequestUrl: true,
  },
  cache: {
    cacheLocation: 'sessionStorage',
    storeAuthStateInCookie: false,
  },
}
```

### Relevant Code Snippets

```javascript
private async getAccessToken(token: string) {
    const result = await this.confidentialClient.acquireTokenOnBehalfOf({
      oboAssertion: token,
      scopes: ['https://graph.microsoft.com/.default'],
    })

    return result?.accessToken
  }
```

### Reproduction Steps

1. God only knows
2. This issue happens 1-2 times per day while having a couple of hundreds of users active daily

### Expected Behavior
```javascript
protected isAuthorityMetadata(key: string): boolean {
    return key.indexOf(AUTHORITY_METADATA_CONSTANTS.CACHE_KEY) !== -1;
}
```

I'm bamboozled about how a string lookup like this could block the main thread? Any help is highly appreciated

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Other

### Source

External (Customer)

**Comment by sameerag** [comment]
I am unable to reproduce it on my end. Is this still persistent @mhmoritz?
