### ISSUE TITLE
React 18 sample fails with `interaction_in_progress: Interaction is currently in progress` error

### ISSUE THREAD

**Issue by mirkode** [AzureAD/microsoft-authentication-library-for-js#4830]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL React (@azure/msal-react)

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/react-18-sample

### Description

Hey folks,

tried all kind of possible configurations (including completely checking the whole codebase out again).
Tried with no changes at all, changed the `clientId`, the `authority`, the `clientId` and `authority` and all other combinations, but I always end up with the infamous:

`Uncaught (in promise) BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.  For more visit: aka.ms/msaljs/browser-errors.`

error.
Tried to follow everything as close as possible and thoroughly read the documentation in all its 15 different places.
Now I am stuck. Can anyone else check out the project, run it and maybe nudge me in the right direction, please!?

**Comment by tnorling** [comment]
@mirkode Can you please describe what steps you are taking that result in this error being thrown? I was just able to run this sample and did not get this error.

**Comment by mirkode** [comment]
Hi @tnorling,
sorry for my late reply and my apologies. I don't know what happened but in order to gather the reproduction steps I completely cloned the project again and after setting it up and installing everything it worked out of the box.

Now I am not sure what caused it. Could it maybe be a node/npm configuration?

In any case I will observe closely and as soon as I can reproduce reopen.

Sorry about that!
