### ISSUE TITLE
How to front-channel logout via b2c with angular hash routing

### ISSUE THREAD

**Issue by e110c0** [AzureAD/microsoft-authentication-library-for-js#4833]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.24.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.3.0

### Description

I'm trying to set up an angular app with single sign-out and hash routing.
Building and running the `angular11-sample-app` (only change: clientId and authority to own b2c tenant)

While the app itself is working and loading the `#/logout` route manually in the browser does exactly what it should, I do not understand how this is supposed to work since b2c (nor OIDC in general according to the spec) does not allow fragments for the front channel logout url (error: `Error detail: Fragments are not supported in redirect URIs.`)

do you have any suggestion how to implement front-channel logout with the restrictions implied by b2c/oidc?

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by sameerag** [comment]
@e110c0 Can you please use a route that does not have a fragment but instead a query param for front channel logout? This would also need some more code on your end to redirect to the specific route you want after logout as mentioned below:
``` javascript
 <yourapp.com>?logout=true -> <yourapp.com>#logout
```

**Comment by e110c0** [comment]
@sameerag query parameters as well are not allowed in a b2c front channel logout url. 

The only options we have found so far are:
1. don't use hash routing (which our environment doesn't allow)
2. create a second SPA for the sole purpose of handling the logout.

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md#front-channel-logout points to the angular 11 example using hash routing, misleading to the idea that front channel sign-out and hash routing are compatible

**Comment by sameerag** [comment]
@e110c0 Feedback noted. The guidance above is for AAD apps, however B2C has specific implementation that could be hindering this. Can you please raise this issue in the B2C forums and check if they have any workarounds other than what you mentioned above? You can raise an issue [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md#what-should-i-do-if-i-believe-my-issue-is-with-the-b2c-service-itself-rather-than-with-the-library).
