### ISSUE TITLE
Select another account is not working after browser back button was clicked

### ISSUE THREAD

**Issue by sT0pe** [AzureAD/microsoft-authentication-library-for-js#4836]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.24.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.0

### Description

Select another account is not working after browser back button was clicked

### MSAL Configuration

```javascript
auth: {
        clientId: "xxx",
        authority: "https://login.microsoftonline.com/xxx",
        redirectUri: "/",
        postLogoutRedirectUri: "/"
    },
    cache: {
        cacheLocation: "localStorage",
        storeAuthStateInCookie: isIE || isEdge || isFirefox
    },
```

### Relevant Code Snippets

```javascript
Issue can be reproduced using example: samples/msal-react-samples/react-router-sample
```

### Reproduction Steps

1. Sign in using redirect to any account
![image](https://user-images.githubusercontent.com/24894105/170489217-5fa8f4b8-666a-46f7-afe0-aee66838f6a9.png)
![image](https://user-images.githubusercontent.com/24894105/170489336-334c8c51-7c6b-46ed-b9c8-04bf3a61a3c1.png)

2. Then go back using browser button
![image](https://user-images.githubusercontent.com/24894105/170489413-b53ee192-5584-4c59-981f-e941820a6abb.png)

3. Select any other account.

4. It still shows account that was selected first time. 

5. msalInstance.getAllAccounts() returns only first account.

### Expected Behavior

User will be signed in using second account

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by tnorling** [comment]
@sT0pe Going back into the middle of an already completed sign-in like this is not supported. If you want to switch users you need to call one of the sign in APIs and start the flow from the beginning.

**Comment by sT0pe** [comment]
@tnorling understood, thank you
