### ISSUE TITLE
InteractionRequiredAuthError: interaction_required: AADB2C90077: User does not have an existing session and request prompt parameter has a value of 'None'.

### ISSUE THREAD

**Issue by gitmurali** [AzureAD/microsoft-authentication-library-for-js#4838]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.18.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.1.0

### Description

I'm trying to make single sign on work between two apps which has two different client id's but it throws the following error.
I have seen there's another similar issue raised here https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/349 I have tried all the given options but none seems to work. How do I resolve this ?

### Error Message

react_devtools_backend.js:4026 InteractionRequiredAuthError: interaction_required: AADB2C90077: User does not have an existing session and request prompt parameter has a value of 'None'.
Correlation ID: x-x-x-x
Timestamp: 2022-05-27 07:52:05Z

    at t [as constructor] (_app-8002ae5169750d21ba5e.js:1:259144)
    at new t (_app-8002ae5169750d21ba5e.js:1:271712)
    at e.validateServerAuthorizationCodeResponse (_app-8002ae5169750d21ba5e.js:1:93185)
    at t.handleFragmentResponse (_app-8002ae5169750d21ba5e.js:1:99878)
    at t.<anonymous> (_app-8002ae5169750d21ba5e.js:1:139458)
    at _app-8002ae5169750d21ba5e.js:1:2010
    at Object.next (_app-8002ae5169750d21ba5e.js:1:2115)
    at _app-8002ae5169750d21ba5e.js:1:1051
    at new Promise (<anonymous>)
    at a (_app-8002ae5169750d21ba5e.js:1:796)

### MSAL Configuration

```javascript
Can't share the configuration here
```

### Relevant Code Snippets

```javascript
useEffect(() => {
    const fetchDetaiils = async () => {
      if (inProgress === InteractionStatus.None && instance) {
        try {
          const [account] = instance.getAllAccounts()
          if (account) {
            const resp = await instance.acquireTokenSilent({
              ...loginRequest,
              account,
            })
            const token: Token = resp?.idTokenClaims
            setUsername(token.email)
          }
        } catch (err) {
          console.error(err)
        }
      }
    }
    fetchDetaiils()
  }, [inProgress, instance])
```

### Reproduction Steps

1. login to app1 and then try refreshing app2 then it throws the error. 

### Expected Behavior

run two apps with two different client id's 
1. if you are logged in first app then second app should pick up the logged in session and do SSO instead of interaction.
2. when I logout from app 1 then app 2 should also be logged out. 

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge

### Source

External (Customer)

**Comment by sameerag** [comment]
The IDP used for both the applications should match for an `ssoSilent` call to match the session. If the IDPs are different (which each profile in B2C is considered as one), it is possible that the cookies are not picked up. 

Can you please raise an issue with the B2C service team to check if they have any workarounds as indicated [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md#what-should-i-do-if-i-believe-my-issue-is-with-the-b2c-service-itself-rather-than-with-the-library)?

**Comment by gitmurali** [comment]
@sameerag we are using the same IDP's and it did work for us in the past but I can see errors now. Is it possible that someone from B2C disabled the SSO ?

**Comment by gitmurali** [comment]
in terms of work around I have used `acquireTokenRedirect` which worked for me but I want to implement it using `ssoSilent`

**Comment by sameerag** [comment]
> @sameerag we are using the same IDP's and it did work for us in the past but I can see errors now. Is it possible that someone from B2C disabled the SSO ?

Did you get a chance to follow up in the B2C channel linked above?

**Comment by gitmurali** [comment]
looks like our internal Azure B2C guys have disabled `ssoSilent` for security reasons. I'm going with `acquireTokenRedirect`.  Closing this issue as Its no longer a problem for us.

**Comment by sameerag** [comment]
Closing the issue as per the customer comments.
