### ISSUE TITLE
.loginPopup fails in full-screen browser

### ISSUE THREAD

**Issue by StephenTHendrix** [AzureAD/microsoft-authentication-library-for-js#4839]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

1.4.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.24.0

### Description

When logging in from a full-screen browser, a new tab is opened allowing me to sign in, but I get redirected back to the login page. From here if I click the login button again, I see the route change to the Redirect URL and then back to the login page, though the login page remains displayed through this process. As soon as I come out of a full screen, however, I'm redirected properly and the flow works as expected.

Logging out works just fine in a full-screen browser; a new tab opens, I log out, and the original tab redirects to the login page.

To be clear, if the browser isn't maximized, there are no issues. Thanks!

### Error Message

```
BrowserAuthError: hash_empty_error: Hash value cannot be processed because it is empty. Please verify that your redirectUri is not clearing the hash.

at BrowserAuthError.AuthError [as constructor] (AuthError.ts:45:1)
    at new BrowserAuthError (BrowserAuthError.ts:195:1)
    at Function.BrowserAuthError.createEmptyHashError (BrowserAuthError.ts:241:1)
    at PopupHandler.ts:62:1
overrideMethod @ react_devtools_backend.js:4026
```

### MSAL Configuration

```javascript
{
  auth: {
    clientId,
    authority,
    redirectUri,
  },
  cache: {
    cacheLocation,,
  },
  system: {
    loggerOptions,
  },
}
```

### Relevant Code Snippets

```javascript
import { useMsal } from '@azure/msal-react'

  const { instance } = useMsal()
  const scopes = {
  scopes: ['User.Read'],
}
  const login = await instance.loginPopup(scopes)
```

### Reproduction Steps

1. Open application in full-screen browser
2. Click login button
3. After being redirected to new tab, logging in, and being redirected back to login page, click login button again.
4. Login page continues to be displayed while URL can be seen changing to Redirect URL and back to login page while error appears in console.

### Expected Behavior

After clicking login button the first time and logging in, user authenticated and redirected to home page.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox

### Source

External (Customer)

**Comment by sameerag** [comment]
@StephenTHendrix There is new guidance published on the `redirects` with #4793, can you please check that and let us know if there is any pattern that you can change in your application which can help here?

**Comment by StephenTHendrix** [comment]
@sameerag thanks for the quick response! I'm not sure where I should be looking - do you mean this? https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-sign-in?tabs=javascript2

Either way I don't yet see much I can do on my end, but that PR looks like it addresses my issue about perfectly! Any idea when it might get released? Thanks again!

**Comment by sameerag** [comment]
@StephenTHendrix Should be a part of June's `msal-browser` release.

**Comment by sameerag** [comment]
Closing. Please raise a new issue if the issue still persists post june release.
