### ISSUE TITLE
Azure login in ionic cordova mobile app

### ISSUE THREAD

**Issue by PriyankaDatDure** [AzureAD/microsoft-authentication-library-for-js#4842]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.23.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.2.0

### Description

I am using @azure/msal-angular plugin to login with azure in ionic mobile app. I'am able to login but theres some issue with the redirect url. I get Application error net::ERR_CONNECTION_REFUSED (http://localhost/#code={code}
![1653392327335](https://user-images.githubusercontent.com/66406241/170945794-784dcb19-af78-4486-a86a-9b03ce756796.JPEG)
)

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by ellymakuba** [comment]
@PriyankaDatDure please provide the fiddler trace, MSAL configuration and relevant code snippet.

**Comment by ellymakuba** [comment]
@PriyankaDatDure see the link shared on how to resolve the error of localhost not being accessible from a mobile device while using ionic [Redirect URI for Angular/Ionic App on Device · Issue #2723 · AzureAD/microsoft-authentication-library-for-js (github.com)](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2723#issuecomment-742766291)

**Comment by PriyankaDatDure** [comment]
this the config:  

MsalModule.forRoot( new PublicClientApplication({
      auth: {
        clientId: 'CLIENTID',
        authority: 'https://login.microsoftonline.com/tenantId',
      },
      cache: {
        cacheLocation: 'localStorage',
        storeAuthStateInCookie: isIE,
      }
    }), null, null)


and i use     this.authService.loginRedirect() method to login

**Comment by ghost** [comment]
This issue requires attention from the MSAL.js team and has not seen activity in **5 days**. @ellymakuba please follow up.

**Comment by ellymakuba** [comment]
@PriyankaDatDure did you try the above, if yes what was the outcome?
