### ISSUE TITLE
Requesting authorization CODE only to pass for backend to redeem for longer tokens lifetime

### ISSUE THREAD

**Issue by OfirSam** [AzureAD/microsoft-authentication-library-for-js#4843]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1

### Description

Hi everyone, 
Currently i use a [Code grant flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow) to get a code & then i pass it to the backend to redeem and extend the tokens lifetime. 

The issue starts when trying to render the app inside a iframe which rises some problems with the current implementation.

Now i was playing a bit with MSAL and tried to get a code as in my previous implementation but find a way...

Is it cable of such thing? only had success receiving tokens with the library..

Thanks!

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by ellymakuba** [comment]
@OfirSam please provide more context on the use case - MSAL configuration, relevant code snippet and fiddler traces. For SPA applications we don't provide long-lived refresh tokens beyond 24 hours. For more information on token lifetimes see this link https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/token-lifetimes.md.
