### ISSUE TITLE
Chrome-extension : Pop up window does not close after redirect  

### ISSUE THREAD

**Issue by h4n0sh1** [AzureAD/microsoft-authentication-library-for-js#4848]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

v2.24.0 

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

Hello, 

Problem : **In some cases**, the pop up window does not close after sucessfull authentication and redirection, thus not returning the promise. 

I am leveraging MSAL js 2.24 as is (no wrapper) for my chrome-extension with loginPopup(). I have set redirect uri to https://google.com as a placeholder in both the MSAL configuration and my SPA configuration in Azure.

On both stations (test, dev), the flow works properly, and the pop up immediately closes after successful authentication and redirection, returning the js promise, and the rest of my code can run. 

However in the demo machine (not mine), running the same LTS version of Chrome Version 102.0.5005.63 (Official Build) (64-bit), and OS (W11), the popup just hangs in there, displaying the redirect page, never closing. 
Of course this kind of stuff only happens in demo. 

This is very problematic and I don't quite know how to debug this issue as i am lacking logs or error sources, furthermore all the event types that i tried using, to debug this issue such as HANDLE_REDIRECT_START or LOGIN_SUCCESS do not seem to trigger before pop up window is closed, which is completely pointless because closing it manually will get me a "user cancelled the flow" browser error. 

I have tried setting the logger inside my msal configuration, following the doc in here : [https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging-js](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging-js )
However i get an unexpected ":" at this line `loggerCallback: (level: LogLevel, message: string, containsPii: boolean): void => { `  ....

I have exhausted all topics related to this kind of issue, with unfortunate success.

### Error Message

Would like to get some

### Msal Logs

Would like to generate them 

### MSAL Configuration

```javascript
const config = {
	    auth: {
	        clientId: 'xxx..',  
	        redirectUri: 'https://google.com',
	        postLogoutRedirectUri: "https://google.com",
	    },   
};
```

### Relevant Code Snippets

```javascript
async function msalAuth(){

	const config = {
	    auth: {
	        clientId: 'xxx...',
	        redirectUri: 'https://google.com',
	        postLogoutRedirectUri: "https://google.com",
	    },   
	};
	
	const loginRequest = {
	    scopes: ["user.read"]
	}
	
	let accountId = "";
	
	const myMsal = new msal.PublicClientApplication(config);

	const callbackId = myMsal.addEventCallback((message) => {
         // This will be run every time an event is emitted after registering this callback
      	if (message.eventType === msal.EventType.LOGIN_SUCCESS) {
            const result = message.payload;  
            test = true;
            console.log("Success auth !!")

      	}
  	});


	let resp = await myMsal.loginPopup(loginRequest)


	// Do some stuff

    console.log("MSAL DISCO ATTEMPT")
    myMsal.logoutRedirect({account: myMsal.getAccountByUsername(resp.account.username)});
	
}
```

### Reproduction Steps

1. Run the aforementionned code snippet in a content_script using chrome-extension, with manifest V3.
2. Hope that your station can reproduce the error ? (cause mine can't ...)

### Expected Behavior

The popup should always immediately close after redirection.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by ellymakuba** [comment]
@h4n0sh1 for chrome extensions the redirect uri must be a chromiumapp.org uri as shown in this sample as shown in this link https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-browser-samples/ChromiumExtensionSample. Please note that unfortunately msal-browser does not support manifest v3 for chromium extensions. Please see issue #3923 for more details.

**Comment by h4n0sh1** [comment]
> @h4n0sh1 for chrome extensions the redirect uri must be a chromiumapp.org uri as shown in this sample as shown in this link https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-browser-samples/ChromiumExtensionSample. Please note that unfortunately msal-browser does not support manifest v3 for chromium extensions. Please see issue #3923 for more details.

Hi thanks for the update, but this does not seem to work in manifest v3 i've replaced my current extension with the code in that sample but then i get an : "Uncaught (in promise) Type Error: Cannot read properties of undefined (reading 'launchWebAuthFlow') " suggesting that it can not resolve the chrome.identity object. 

I tried placing the code at several places such as in background or directly in my content.js, while eliminating all the window and button listeners, but it still did not work unfortunately. 

I would like to add an important piece of information as well , completely non related to the subject of chrome-extensions : 
I have tried to run the following sample JS vanilla MSAL project in my chrome browser : 
[https://github.com/Azure-Samples/ms-identity-javascript-v2/tree/master/app](https://github.com/Azure-Samples/ms-identity-javascript-v2/tree/master/app)

I've supplemented https://google.com as my redirect url both in app and in azure, and i get the exact same behaviour as with the plugin before. Is this intented ? If so, how can i forge a redirect page to get the popup to close. 
I think that by solving this issue, i will also solve my plugin problem, the behaviour is very similar.

**Comment by jasonnutter** [comment]
> Hi thanks for the update, but this does not seem to work in manifest v3 i've replaced my current extension with the code in that sample but then i get an : "Uncaught (in promise) Type Error: Cannot read properties of undefined (reading 'launchWebAuthFlow') " suggesting that it can not resolve the chrome.identity object.

You must enable the `chrome.identity` APIs in your manifest: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-browser-samples/ChromiumExtensionSample/manifest.json#L11

> I've supplemented https://google.com/ as my redirect url both in app and in azure, and i get the exact same behaviour as with the plugin before. Is this intented ? If so, how can i forge a redirect page to get the popup to close.
I think that by solving this issue, i will also solve my plugin problem, the behaviour is very similar.


Your redirect URI must be the on the same domain as your application, so using `google.com` as your redirect will not work. If you do not specify a redirect URI, MSAL will use the current page. And again as noted in the Chromium sample app, for Chrome extensions you must use the `chromiumapp.org` URL as a redirect URI.

**Comment by h4n0sh1** [comment]
> > Hi thanks for the update, but this does not seem to work in manifest v3 i've replaced my current extension with the code in that sample but then i get an : "Uncaught (in promise) Type Error: Cannot read properties of undefined (reading 'launchWebAuthFlow') " suggesting that it can not resolve the chrome.identity object.
> 
> You must enable the `chrome.identity` APIs in your manifest: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-browser-samples/ChromiumExtensionSample/manifest.json#L11
> 
> > I've supplemented https://google.com/ as my redirect url both in app and in azure, and i get the exact same behaviour as with the plugin before. Is this intented ? If so, how can i forge a redirect page to get the popup to close.
> > I think that by solving this issue, i will also solve my plugin problem, the behaviour is very similar.
> 
> Your redirect URI must be the on the same domain as your application, so using `google.com` as your redirect will not work. If you do not specify a redirect URI, MSAL will use the current page. And again as noted in the Chromium sample app, for Chrome extensions you must use the `chromiumapp.org` URL as a redirect URI.

Hello, yes i already have identity declared in my manifest.

As for the redirect URI i have also added the chromiumapp.org corresponding to my extension ID following the format https://epfnbngoodhmbeepjlcohfacgnbhbhah.chromiumapp.org/ but now what happens is that instead of getting a popup stuck in "google.com" i get a popup stuck at "this site can't be reached" error page (DNS_PROBE_FINISHED_NXDOMAIN) 

Just as a side question, does the extension need to be registered in the chrome store for the redirect to work ?

Also wanted to add as a reminder that the current code snippet, surprisingly works in 2 of my stations with redirect set to google.com, i'm thinking some antivirus side effect with popup behaviour might be at stake, however when reading through the msal.js code earlier, this led me to think that if i could inject the msal cleanpopup funciton somewhere in my code, i might hack it in the way i want to. not sure if it's a good idea.

**Comment by h4n0sh1** [comment]
Hello again, 

Just a little update on the meaningful things i've tried so far, getting closer, but still always hitting a roadblock in each way, sadly.

1/ Tried downgrading to manifest v2 with the code provided in [https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-browser-samples/ChromiumExtensionSample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-browser-samples/ChromiumExtensionSample)
This actually works but only partly for my purpose, the popup does close, however i can not use this method because i need to listen to the user input in the actual login popup. Unfortunately the sample uses chrome.identity which leverages a special chrome UI that does not behave like a classic browser window. 
I can not listen to it's event, it is not inspectable, there seems to be no programatic interaction possible with that the chrome.identity UI. 

2/ I solved the "site can't be reached" issue using the previous code (manifest v3), by adding chrome-extension://myextid.org/popup.html in both Azure (Mobile & Desktop apps) and my msal auth configuration. Also adding the popup.html to the web accessible ressources. Following your guidelines from this post [https://stackoverflow.com/questions/62396398/azure-ad-app-redirect-uri-for-chrome-extension](https://stackoverflow.com/questions/62396398/azure-ad-app-redirect-uri-for-chrome-extension)
However this leads to a tragic "ERR_BLOCKED_BY_CLIENT" chrome page within the popup, thus still not closing.


I am about to create my own modal popup to fake the msal login and send user request from there, but i still would like to make this work properly, it shouldn't be this complciated...

**Comment by jasonnutter** [comment]
> however i can not use this method because i need to listen to the user input in the actual login popup. 

Why do you want to do this? You should not need to know what is happening in the login UX.

> However this leads to a tragic "ERR_BLOCKED_BY_CLIENT" chrome page within the popup, thus still not closing.

I don't know why this would be happening, do you have an ad blocker running bychance?

> I am about to create my own modal popup to fake the msal login and send user request from there, but i still would like to make this work properly, it shouldn't be this complciated...

We would not recommend doing this, and instead relying on the popups created by the browser.
