### ISSUE TITLE
Broken Documentation Link

### ISSUE THREAD

**Issue by jasonfavrod** [AzureAD/microsoft-authentication-library-for-js#485]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x ] Chrome version 69
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 0.2.3

## Current behavior
The `Library Reference` link on the README.md page is broken.
Directs user to a page with the following text:
```
Error: Cannot load file https://raw.githubusercontent.com/AzureAD/microsoft-authentication-library-for-js/dev/docs/classes/_useragentapplication_.useragentapplication.html
```

## Expected behavior
Expected to be taken to a Web page containing the Library Reference documentation.

## Minimal reproduction of the problem with instructions
From either the [NPM](https://www.npmjs.com/package/msal) or [Github](https://github.com/AzureAD/microsoft-authentication-library-for-js#readme) project pages, click on `Library Reference` link at the top of the README.md document.

</code></pre>

**Comment by nehaagrawal** [comment]
PR in progress https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/487

**Comment by nehaagrawal** [comment]
Fixed.
