### ISSUE TITLE
need some documentation how to use and what are fuctions why its maded like services ,guards and many more  

### ISSUE THREAD

**Issue by shahnisargweb** [AzureAD/microsoft-authentication-library-for-js#4856]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Documentation Location

need some improvement

### Description

i have little bit confusing i want to migrate Microsoft authentication in our existing Angular  project (version 13 with rxjs 7) then i need some kind of code guidance what is purpose of  functions and how i configure it in my project easy way  what is purpose of that function

**Comment by ellymakuba** [comment]
@shahnisargweb please start with this link https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-angular#readme. Let us know if you have further questions.
