### ISSUE TITLE
ServerRequestParameters.ts setting of scopes throws undefined error

### ISSUE THREAD

**Issue by ravinleague** [AzureAD/microsoft-authentication-library-for-js#4857]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

1.4.16

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

We are trying to implement ADAL to MSAL migration in our SharePoint Online environment for our SPFx Apps.
To start with, we have updated one of our SPFx web parts to use MSAL and it worked without any issues after moving to MSAL>

With confidence from the first success, we then started updating one of our Application Customizers to use MSAL. This is where we are encoutering errors in the ServerRequestParameters.ts file

 

### Error Message

 this.scopes = scopes ? [ ...scopes] : Constants.oidcScopes; <-- This is throwing error

**Uncaught (in promise) TypeError: Object(...) is not a function**

### MSAL Configuration

```javascript
const config: Configuration = {
            auth: {
                clientId: clientId,
                authority: "https://login.microsoftonline.com/<>",
                navigateToLoginRequestUrl: true,
            },
            cache:{
                cacheLocation:"sessionStorage"
            }
        };
```

### Relevant Code Snippets

```javascript
const account = userAgentObject.getAllAccounts()[0]; 
let accessTokenRequest = {
            scopes: ['user.read'],
            account: account
        };

        try {
            var accessTokenResponse = await userAgentObject.acquireTokenSilent(accessTokenRequest);
            return accessTokenResponse.accessToken;
        }
        catch (error) {
throw(error)
}
```

### Reproduction Steps

Try retrieving the MSAL access token in an application customiser in a sharepoint online page

### Expected Behavior

An access token is returned without any errors

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

Internal (Microsoft)

**Comment by ellymakuba** [comment]
@ravinleague please provide verbose logs from msal.

**Comment by ravinleague** [comment]
![image](https://user-images.githubusercontent.com/18733308/171748276-a7c7cfba-2fb3-407f-9925-d9cdc5d30701.png)

**Comment by jasonnutter** [comment]
@ravinleague Can you please also provide logs from MSAL.js? Are you able to reproduce this with one of our samples?

Futhermore, SPFX Webparts should use the token APIs provided by SPFX, instead of using MSAL.js directly. You can find more information here: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/connect-to-api-secured-with-aad#use-the-aadtokenprovider-to-retrieve-access-token
