### ISSUE TITLE
MSAL SSO not working in I.E 11

### ISSUE THREAD

**Issue by meseras** [AzureAD/microsoft-authentication-library-for-js#486]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [X] IE version 11
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 0.2.3

## Current behavior
I am writing an MSAL app page pulling data from various graph api's as a web page within SharePoint.  
As it's hosted within Sharepoint all of my users have authenticated as the point the page is loaded.  
I have simplified version on this app whereby I am simply calling acquireTokenSilent to get the token for the signed in user.    
For Chrome, Firefox and Edge I get the single sign experience I expect but I.E 11 returns the following exception  

"AADSTS50058: A silent sign-in request was sent but none of the currently signed in user(s) match the requested login hint."  

Is there any reason I.E behaves differently that all the other browsers.

## Expected behavior

I.E to find logged in user and return token.

## Minimal reproduction of the problem with instructions

Copy page to page library within SharePoint. Enter Logged in users email address and press single sign on button.  
NB: I sign in with the same user in a different browser (e..g chrome) initially to accept the permission requested, to keep the test as simple as possible.

</code></pre>

```
<!DOCTYPE html>
<html>
<head>
    <title>Quickstart for MSAL JS</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.min.js" class="pre"></script>
    <script src="https://secure.aadcdn.microsoftonline-p.com/lib/0.2.3/js/msal.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
</head>

<body>
<h4 id="Enter Email to Test if User is Logged In"></h4>
<input id="userEmail" type="text" />
<button id="SignIn" onclick="signIn()">Sign In</button>
<button id="SilentSignIn" onclick="silentsignIn()">Silent Sign In</button>
<button id="SilentSignIn" onclick="silent2signIn()">Silent Sign In - Graph Only</button>
<br/><br/>
<pre id="json"></pre>

<script>

    // Browser check variables
    var ua = window.navigator.userAgent;
    var msie = ua.indexOf('MSIE ');
    var msie11 = ua.indexOf('Trident/');
    var msedge = ua.indexOf('Edge/');
    var isIE = msie > 0 || msie11 > 0;
    var isEdge = msedge > 0;

    var applicationConfig = {
        clientID: '****************************', //This is your client ID
        authority: "https://login.microsoftonline.com/common",
        graphScopes: ["openid"],
        graphEndpoint: "https://graph.microsoft.com/v1.0/me",
    };

    var myMSALObj = new Msal.UserAgentApplication(applicationConfig.clientID, null, acquireTokenRedirectCallBack,
        {storeAuthStateInCookie: true, cacheLocation: "localStorage", navigateToLoginRequestUrl: false, loadFrameTimeout: 10000});
    

    function silentsignIn() {

      var emailAddress = document.getElementById('userEmail');
      applicationConfig.extraQueryParameters =  "&login_hint=" + emailAddress.value + "&domain_hint=organizations";
      console.log("GRAPH SILENT SIGN IN ***************");
      myMSALObj.acquireTokenSilent(applicationConfig.graphScopes,applicationConfig.authority,null,applicationConfig.extraQueryParameters ).then(function (accessToken) {
        console.log("GRAPH SILENT SIGN IN TOKEN ***************", accessToken);
            
        }, function (error) {
          console.log("GRAPH SILENT SIGN IN ERROR ***************", error);
        });
    }
    function signIn() {
      console.log("GRAPH SIGN IN ***************");
        myMSALObj.loginPopup(applicationConfig.graphScopes).then(function (idToken) {
          console.log("GRAPH SIGN IN *************** LOGIN POPUP");
            //Login Success
            showWelcomeMessage();
            acquireTokenPopupAndCallMSGraph();
        }, function (error) {
            console.log(error);
        });
    }

    function silent2signIn() {
      
      console.log("GRAPH SILENT2 SIGN IN ***************");
      myMSALObj.acquireTokenSilent(applicationConfig.graphScopes).then(function (accessToken) {
        console.log("GRAPH SILENT2 SIGN IN TOKEN ***************", accessToken);
        callMSGraph(applicationConfig.graphEndpoint, accessToken, graphAPICallback);            
        }, function (error) {
          console.log("GRAPH SILENT2 SIGN IN ERROR ***************", error);
        });
    }

</script>
</body>
</html>
```

**Comment by ewaldhofman** [comment]
You might need to use Bluebird: https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL-Installation

**Comment by meseras** [comment]
In the sample code i posted above i am already using bluebird

**Comment by meseras** [comment]
NB: To get this working for IE I had to get my enterprise to add "https://login.microsoftonline.com" as a trusted site for all employees using a group policy.

**Comment by navyasric** [comment]
@meseras  Thanks for the update here. 
As documented in the [known issues wiki](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Known-issues-on-IE-and-Edge-Browser#update-fix-available-in-msaljs-023) the storeAuthStateInCookie flag resolves this issue only for login redirect flows in IE. 
Since you are using loginPopup flow, adding to trusted sites is the only workaround available.
Closing this issue.
