### ISSUE TITLE
Refresh Token from different B2C Policy being used when logged into another Policy

### ISSUE THREAD

**Issue by philip-young** [AzureAD/microsoft-authentication-library-for-js#4860]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.15.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.1.0

### Description

This might end up being a B2C question but I thought I would start here as this library is using the refresh token provided from it. Or maybe it is a bug, or a setting I need to set on the MSAL side. 

I have multiple B2C policies, but the same User, and sometimes they sign into one policy using MSAL and then switch environments, which uses the same Application, but a different B2C policy. For the purpose of example, lets call them Test and Staging. What I have observed happening is occasionally the application gets stuck in a loop trying to get a token from the /token endpoint. What I have discovered is that MSAL is trying to use a refresh token to get a new token, however, this gets rejected with a Bad Request 400 from B2C and the error below appears. I am able to see that the ``refresh_token`` grant is being used with this endpoint when the Bad Request is returned. This leads me to believe that MSAL acquired a refresh token from the first environment (Test), and then later uses the same refresh token to try to renew the token while it is in environment (Staging), targeting the different policy, and this error occurs.

Is there anything I can do about this?

Error message from B2C:

``
"error": "invalid_grant", "error_description": "AADB2C90088 | The provided grant has not been issued for this endpoint. Actual Value : B2C_1A_MyPolicyTest and Expected Value : B2C_1A_MyPolicyStaging"
``

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by ellymakuba** [comment]
@philip-young are you able to reproduce this issue with the latest version of MSAL (2.24.0)?

**Comment by philip-young** [comment]
@ellymakuba Sure, I will give that a try. I'll have to let the token expire to get the refresh token to work - will get back to you soon.

**Comment by philip-young** [comment]
hi @ellymakuba I am still getting the error after testing. I updated to the latest: msal-react 1.4.0 and msal-browser 2.24.0.

**Comment by jasonnutter** [comment]
@tnorling Do you have any insight here, would this be expected?

**Comment by tnorling** [comment]
@philip-young Each B2C policy you use will be tied to a separate `account` object and the tokens will be looked up in the cache based on the `account` you pass into the request. Make sure when you call `acquireTokenXXX` you are passing the `account` associated with the policy you intend to use. To check which policy the account belongs to you can check the `acr` or `tfp` claims in `idTokenClaims`

**Comment by philip-young** [comment]
Hi @tnorling , thanks for the response. That sounds like exactly what I need to do! It took me a bit to get the tfp claim set up in my B2C Tenant (originally I was wondering why it was missing in the ```idTokenClaims``` until I looked into it). Do you guys mind leaving this open while I try this out?

**Comment by philip-young** [comment]
Hi @tnorling sorry for the delay on my response. I was able to test this by passing in the Account as you suggested once I found the correct one for the Policy. It worked great, thanks for the help!
