### ISSUE TITLE
More information on serviceName and accountName on mac/Linux

### ISSUE THREAD

**Issue by scottdurow** [AzureAD/microsoft-authentication-library-for-js#4861]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.9.0

### Wrapper Library

MSAL Node Extensions (@azure/msal-node-extensions)

### Wrapper Library Version

1.0.0-alpha.17

### Description

The `persistenceConfiguration` accepts serviceName and accountName:

```
const persistenceConfiguration = {
    cachePath,
    dataProtectionScope: DataProtectionScope.CurrentUser,
    serviceName: "<SERVICE-NAME>",
    accountName: "<ACCOUNT-NAME>",
    usePlaintextFileOnLinux: false,
}
```

The docs simply say 'This specifies the service/account name to be used on Mac and/or Linux'.

Could this be elaborated please with an example - what code needs to be used to ensure that they are correct for mac/Linux? 

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@scottdurow Something that uniquely identifies your app should be fine. This is what the MSAL.NET Extensions library uses as an example: https://github.com/AzureAD/microsoft-authentication-extensions-for-dotnet/blob/master/sample/ManualTestApp/Config.cs#L27-L28

Apologies for the confusion, we'll update our examples to make this more clear.

**Comment by scottdurow** [comment]
Hi @jasonnutter - many thanks for the info. I had suspected that it's purely for the path in the keychain/libsecret - thank you for confirming that there is no special implications. 

Presumably when using the persistence across multiple node applications, by providing the same values, the authentication cache store can be shared?

**Comment by jasonnutter** [comment]
> Presumably when using the persistence across multiple node applications, by providing the same values, the authentication cache store can be shared?

Yes, that should work.

**Comment by scottdurow** [comment]
Perfect - thank you.
