### ISSUE TITLE
Are there any plans to expose the refresh_token for confidential client authorization_code grant flows?

### ISSUE THREAD

**Issue by r-delgadillo** [AzureAD/microsoft-authentication-library-for-js#4871]
### Core Library

MSAL Node (@azure/msal-node)

### Wrapper Library

Not Applicable

### Description

We are currently migrating from the AAD V1 endpoint to the Identity V2 endpoint using MSAL Node. We just noticed that the confidential client `acquireTokenByCode` method does not return the refresh_token in the result. This becomes an issue for us since we have multiple instances of our service running on different machines which will have a different cache. Hence when we attempt to acquire a token silently it's not guaranteed that we will use the cached refresh token and potentially prompt the user to re-authenticate.

I read on the [FAQ](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/faq.md#how-do-i-get-the-refresh-token)  that in fact it is not exposed.

Is there anything we can do to avoid multiple authentication requests for our end users? Can we have the refresh_token exposed? We would love to use the MSAL-Node library instead of the Identity V2 Rest APIs directly. 

### Source

Internal (Microsoft)

**Comment by derisen** [comment]
@r-delgadillo refresh tokens are not returned in auth code response but you should be able to retrieve them directly from the cache (either in memory or persisted to disk). Is this not the case? 

After that, you can make use of the [`acquireTokenByRefreshToken`](https://azuread.github.io/microsoft-authentication-library-for-js/ref/classes/_azure_msal_node.confidentialclientapplication.html#acquiretokenbyrefreshtoken) API ([sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/refresh-token)). The logic might look like: 

```JavaScript
    try {
        // attempt acquireTokenSilent
    } catch (error) {
        if (error instanceof msal.InteractionRequiredAuthError) {
           try {
                // grab refresh token from cache
                // attempt acquireTokenByRefreshToken
           } catch (error) {
                // acquireTokenByCode
           }
        }
    }
 ``` 
 
 Also, have you considered using a [distributed cache](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/caching.md#token-caching-in-msal-node) shared between the instances?

**Comment by r-delgadillo** [comment]
@derisen I'm having trouble finding the refresh token in the cache. Do you happen to have an example of how this is done or which method to use if it's exposed through the cache?

Yes, we currently use Redis as our distributed cache in other flows. We'll take a look at adding it to this as well, thank you.

**Comment by r-delgadillo** [comment]
Accidentally closed issue

**Comment by derisen** [comment]
So if you are using a [cache plugin](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-node-samples/cachePlugin.js) to persist the cache, you could access the refresh token entry there. The cache template looks like [this](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/cache.json). But if you were to read it from in-memory cache, you could access it via [getTokenCache](https://azuread.github.io/microsoft-authentication-library-for-js/ref/classes/_azure_msal_node.confidentialclientapplication.html#gettokencache):

```TypeScript
const cache = confidentialClientApplication.getTokenCache();
const kvStore = cache.getKVStore();
```

Then query [kvStore](https://azuread.github.io/microsoft-authentication-library-for-js/ref/modules/_azure_msal_node.html#cachekvstore) for that user's refresh tokens using the scheme `<homeAccountId-authority-refreshtoken-clientId>` as key.

@sameerag to consider offering a convenience method.

**Comment by r-delgadillo** [comment]
@derisen We are finishing up some existing code paths for ADAL -> MSAL adoption and noticed the cache is not being set when using NodeJs ConfidentialClient.acquireTokenByRefreshToken method. Underneath it goes through the [RefreshTokenClient.acquireToken](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/5ef1da0fa05bad08d09bc6f41dec14f373acdb3f/lib/msal-common/src/response/ResponseHandler.ts#L152) method which skips setting the new cache entry if the user account is not found in the cache. Is there a way to get the new refreshToken when calling `acquireTokenByRefreshToken`?

For reference, from the link above, line 160 is the statement we are hitting that prevents the cache entry from being set.
![image](https://user-images.githubusercontent.com/35089121/182070694-791e310e-e606-416d-80a7-6e98b053eeff.png)

Our client is currently storing the refreshToken in CosmosDb. So before calling `acquireTokenByRefreshToken` we are making a GET call to the CosmosDB document to supply the refreshToken to the MSAL client.

**Comment by jasonnutter** [comment]
@sameerag Is this supported?

**Comment by derisen** [comment]
This is supported as of msal-node@1.12.0 (msal-common@7.2.0). @r-delgadillo you'll need to set the `forceCache` property to **true** in the initial token request, e.g.:

```javascript
 const tokenResponse = await cca.acquireTokenByRefreshToken({
    refreshToken: "raw-refresh-token-string",
    scopes: ['https://graph.microsoft.com/.default'],
    forceCache: true,
});
```
Please see the [refresh-token](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/refresh-token) sample for an illustration.
