### ISSUE TITLE
Combine repositories or provide similar examples

### ISSUE THREAD

**Issue by Depechie** [AzureAD/microsoft-authentication-library-for-js#4873]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

^2.1.2

### Description

I submitted an issue on : [https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/issues/180](https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/issues/180)

It's regarding using a role guard in Angular, that uses the MSAL lib to get Azure AD roles.
But that sample repo is using a very old Angular version and is not maintained as much as this repository it seems.

So question now, can both be combined somehow?
So that we get more up to date samples...

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@Depechie Thanks for the feedback. We'll make sure your question is answered. cc @derisen 

We maintain samples both [inside of this repository](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples) and in the Azure Samples organization, such as the one you are using. While I don't think we will combine those samples into this repository, we'll make sure to keep those samples up to date.

**Comment by derisen** [comment]
@Depechie apologies, we had it in the backlog but didn't get a chance so far. We'll double down on updating them.
