### ISSUE TITLE
How can I get a access_token for activesync protocol。

### ISSUE THREAD

**Issue by Leaking** [AzureAD/microsoft-authentication-library-for-js#4874]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.0.0

### Wrapper Library

MSAL Node Extensions (@azure/msal-node-extensions)

### Wrapper Library Version

1.0.0

### Description

According to [Authenticate an IMAP, POP or SMTP connection using OAuth](https://docs.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth)。we can get access_token for imap/pop3/smtp。but i can't find any document discuss how to get access_token for activesync 

for example, i use scopes like this

```
 const requestScopes = ["offline_access", 'https://outlook.office.com/SMTP.Send'];
```
i can get an access_token to send mail with smtp protocal。what scopes should i use if i  want to get an access_token for activesync
 

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@Leaking I'm not finding any information about this, unfortunately. Have you considered using the Microsoft Graph API to send email: https://docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=http
