### ISSUE TITLE
Angular v14

### ISSUE THREAD

**Issue by gaweCodes** [AzureAD/microsoft-authentication-library-for-js#4876]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

^2.23.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

^2.3.0

### Description

Are there any plans for Angular v14? It the package already ready for Angular v14? 

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@gaweCodes Yes, Angular 14 is supported and there are multiple samples available: https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples

**Comment by gaweCodes** [comment]
Thanks a lot. Issue can be closed
