### ISSUE TITLE
After authentication while redirecting back to application return error 404 not found.

### ISSUE THREAD

**Issue by UMANGAWASTHY** [AzureAD/microsoft-authentication-library-for-js#4877]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.0.2

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.2

### Description

Hello Team
I am using azure/msal in angular 12.2.0 application. It’s working fine on http://localhost:4200/. I had deploy my application apache server, its’ redirecting on Microsoft authentication site and open authentication popup. After successful authentication it’s redirect on return url, now I am getting 404 not found : The requested URL was not found on this server.

Application Authentication Steps – 
1.	Hit url https://abc-xyz.com// on browser.
2.	Redirect to https://abc-xyz.com/login page. –Excepted
3.	Checking local storage for token and user information if user authenticated redirect to /home page, if not redirect to Microsoft authentication site and open authentication popup. - Excepted
4.	After authentication redirect back to https://abc-xyz.com/login page. Now I am getting Error 404 not found. -Unexcepted

![image](https://user-images.githubusercontent.com/29591202/172619530-b98be468-7327-45f0-8754-039b180261b8.png)

Redirect Uri on Azure AD: https://abc-xyz.com/
Redirect Uri on Application Config: https://abc-xyz.com/

Server SSL Information:  Your connection is to this site is not secure.

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@UMANGAWASTHY It looks like your server is not configured correctly to route `/login` to your Angular application when a user visits the page directly (it works initially likely because you are using client-side routing in Angular). Please verify your server configuration to ensure any pages on your application are routed to your application when visited directly.

Closing, as this is outside of the scope of MSAL.js.

**Comment by UMANGAWASTHY** [comment]
Hey @jasonnutter, it seems my hosting server in fully SSL configured. 
My question is azure ad authentication will work here.

![image](https://user-images.githubusercontent.com/29591202/172889691-0abaed78-4516-4fe0-93b9-af91abe17786.png)

**Comment by jasonnutter** [comment]
@UMANGAWASTHY Again, the issue if your web server not routing `/login` to your app correctly, not anything to do with MSAL.js.
