### ISSUE TITLE
ADAL.js - what should be the IFrame target origin for embedding PowerBI dashboard

### ISSUE THREAD

**Issue by cmgchess** [AzureAD/microsoft-authentication-library-for-js#4887]
### Core Library

ADAL.js (adal.js)

### Core Library Version

1.0.17

### Wrapper Library

ADAL Angular (adal-angular)

### Wrapper Library Version

1.0.17

### Description

I'm using the [PowerBI REST API](https://docs.microsoft.com/en-us/rest/api/power-bi/dashboards/get-dashboards-in-group) along with [ADAL.js](https://github.com/AzureAD/azure-activedirectory-library-for-js) and getting Dashboards. I want to embed a Dashboard in an IFrame. I'm using Angular.JS
So what did was something like this. Notice I have used **"*"** as the IFrame Target Origin. `dashboardEmbedUrl` is obtained from the API call

```html
<iframe id="PBDashboard" ng-show="dashboardVisible" src="{{dashboardEmbededUrl}}" frameborder="0" style="height: 100vh; width: 100%"></iframe>
```
and in my controller

```javascript
var iframe = document.getElementById("PBDashboard")
const loadIframeDashboardEventListner = function() {
    const token = localStorage.getItem('adal.access.token.keyhttps://analysis.windows.net/powerbi/api');
    iframe.contentWindow.postMessage(JSON.stringify({
        action: "loadDashboard",
        accessToken: token
    }), "*") //target is *. what should be the specific URL needed here
}
```
and
```javascript
iframe.addEventListener("load",loadIframeDashboardEventListner);
```
This worked perfectly fine but using **"*"** triggers a security warning in SonarCloud. It says to specify a target. I'm not sure what the target should be. The API call also gives a `webUrl` along with the `embedUrl`. I used the `webUrl` instead of the `"*"` and it rendered the IFrame data but also gave the following error in console
![image](https://user-images.githubusercontent.com/61736812/173253317-63928961-7f65-46f5-bd17-774bae74167e.png)

### MSAL Configuration

```javascript
adalAuthenticationServiceProvider.init(
        {
        clientId: 'clientID',
        endpoints: {
            'https://api.powerbi.com': 'https://analysis.windows.net/powerbi/api'
        },
        anonymousEndpoints: ['http://localhost:3000'],
        cacheLocation: 'localStorage'
        },
        $httpProvider
    );
```

### Relevant Code Snippets

```javascript
var iframe = document.getElementById("PBDashboard")
const loadIframeDashboardEventListner = function() {
    const token = localStorage.getItem('adal.access.token.keyhttps://analysis.windows.net/powerbi/api');
    iframe.contentWindow.postMessage(JSON.stringify({
        action: "loadDashboard",
        accessToken: token
    }), "*") //target is *. what should be the specific URL needed here
}
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by hectormmg** [comment]
@cmgchess I'm not sure we can help here since this isn't an issue with the ADAL library. I'm unfamiliar with the environment that you're working with, but perhaps this question is better directed at the Power BI SDK?

**Comment by cmgchess** [comment]
hi @hectormmg 
Thanks for the reply!
I guess https://community.powerbi.com/ is the correct place to ask this question 🤔
