### ISSUE TITLE
Unable to login with a Cordova / InAppBrowser redirect on iOS

### ISSUE THREAD

**Issue by zarko-tg** [AzureAD/microsoft-authentication-library-for-js#4910]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.26.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

We have a Cordova app (using a slightly older but proven Ionic/Angular stack and codebase) and we seem to have succeeded in integrating msal-browser but it's working only on Android and in the desktop browser (development and testing). The Redirect API/calls work just fine on Android, and in the desktop browser the popup API is also performing as expected.

The redirect sign-and-dance flow was solved using the Cordova InAppBrowser plugin, where the solution is similar to the one presented here: https://stackoverflow.com/a/70337594

The problem on iOS (latest / 15.x) is that we get stuck right after entering (correct) user password - seeing an AADSTS900561 (The endpoint only accepts POST requests. Received a GET request.)

I understand there might an issue (or no support?) for InAppBrowser / WKWebView / iOS and the redirect flow, but is the above error and indication for that or is it something else?

Is there any working solution at all for msal-browser and Cordova that also covers iOS?

![iOS screenshots](https://user-images.githubusercontent.com/6142411/173787442-f9196ec5-b316-4c8d-8b18-b998060ae7ee.png)

### MSAL Configuration

```javascript
{
      auth: {
        protocolMode: 'OIDC',
        clientId: 'OUR CLIENT ID',
        authority: 'https://login.microsoftonline.com/OUR TENANT ID',
        redirectUri: 'http://localhost:8100'
      },
      cache: {
        cacheLocation: 'localStorage'
      }
}
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by zarko-tg** [comment]
Attaching MSAL log just in case:
[Safari log.txt](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/8907846/Safari.log.txt)

**Comment by hectormmg** [comment]
@zarko-tg thanks for raising the issue. Could you send a network trace from a tool such as Fiddler to the e-mail address listed on my profile? I can see the last log is from the auth code navigation, so it's unclear what request the error message is referring to. 

Also, if you could post a snippet of how you're using the MSAL acquieToken APIs, that would be helpful as well.

**Comment by zarko-tg** [comment]
Thanks @hectormmg, here is the gist our current implementation / use of msal-browser:

<img width="785" alt="Screenshot 2022-06-15 at 23 02 05" src="https://user-images.githubusercontent.com/6142411/173929417-6b474476-1c26-4f5a-8abf-85f75f35d50e.png">

I'm sending you a Fiddler log in short.

**Comment by zarko-tg** [comment]
Here's a demo project demonstrating the problem, see README.md inside:
[msal-gh-4910.zip](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/8914147/msal-gh-4910.zip)

**Comment by hectormmg** [comment]
@zarko-tg I've looked at the Fiddler trace you sent and I can see the error showing up but it isn't clear which request the server is complaining about. The authorization/ endpoint request MSAL makes is working properly and the server never redirects back to MSAL so it doesn't have a chance to perform the /token request, so it seems this may be an issue unrelated to MSAL directly.

**Comment by zarko-tg** [comment]
Ok, so we're stuck with this for the time being. It isn't clear what causes the issue. And unfortunately I haven't been able to find any alternative solution yet.

**Comment by zarko-tg** [comment]
After some cumbersome attempts I can conclude that one should not even bother to use InAppBrowser / WKWebView. The only likely solution is to launch the external browser and do redirection(s) back to the app using deep links (via Firebase for example). It doesn't seem like the best UX compared to showing/using an embedded browser (InAppBrowser / WKWebView) within the Cordova app but at least login is possible.

Thanks for having a look @hectormmg!

**Comment by Airdevelopments** [comment]
I got it working on iOS. I am also using the msal-browser module + the InAppBrowser.

The only difference I noted on quick glance: I am using the AAD protocol. But I doubt that is the cause of your issue.

Also note: It's not working in dev environment, only in a final build. This is because of browser security.

**Comment by aleon0103** [comment]
I got it working on iOS using Capacitor with the Cordova InAppBrowser plugin on IOS 16  I use this approach 
https://stackoverflow.com/a/73729743/20002757

instead of use  _msalInstance.loginPopup(); try to use LoginRedirect 

> After some cumbersome attempts I can conclude that one should not even bother to use InAppBrowser / WKWebView. The only likely solution is to launch the external browser and do redirection(s) back to the app using deep links (via Firebase for example). It doesn't seem like the best UX compared to showing/using an embedded browser (InAppBrowser / WKWebView) within the Cordova app but at least login is possible.
> 
> Thanks for having a look @hectormmg!
