### ISSUE TITLE
monitor_window_timeout on Teams app

### ISSUE THREAD

**Issue by MudulOzan** [AzureAD/microsoft-authentication-library-for-js#4914]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.21.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.2.0

### Description

Hi, we are trying to put our web app to teams tab,  it is built by teams fx. The app works perfectly on web but in teams we couldn't know which redirect url that we are going to put for teams, thus it is giving monitor window timeout error. I am confident that this issue caused by this since happened to stuck with this many times and solved giving the correct url. 

We tried to give iframe src url and teams app url but none of those worked. I've been looking for 5 days but there aren't any to send teams notification without proper login given the scopes (cannot give scopes in msal graph sdk). 

We do an ssoSilent operation on app load just before everything, data fetching etc. so it can't be throttling problem.

Thanks in advance

### MSAL Configuration

```javascript
{
    auth: {
        clientId: clientId,
        authority: "https://login.microsoftonline.com/" + tenantId
    },
    cache: {
        cacheLocation: "sessionStorage",
        storeAuthStateInCookie: true, 
    }
}
```

### Source

Internal (Microsoft)

**Comment by hectormmg** [comment]
@MudulOzan please take a look at our [Teams Tab SSO sample](https://github.com/pnp/teams-dev-samples/tree/main/samples/tab-sso/src/nodejs) to see how to use MSAL with the Teams SDK. The regular interactive flows will not work, you need to use an auth dialogue from the teams SDK and do the interactions in the resulting popup. Please let us know if this helps answer your question so we can close your issue.

**Comment by MudulOzan** [comment]
> @MudulOzan please take a look at our [Teams Tab SSO sample](https://github.com/pnp/teams-dev-samples/tree/main/samples/tab-sso/src/nodejs) to see how to use MSAL with the Teams SDK. The regular interactive flows will not work, you need to use an auth dialogue from the teams SDK and do the interactions in the resulting popup. Please let us know if this helps answer your question so we can close your issue.

If I am not mistaken, it receives an access token from a custom API. We want to do it with MSAL itself in the component

**Comment by hectormmg** [comment]
@MudulOzan unfortunately MSAL cannot be used on its own in a Teams Tab since all interactive flows have to go through the Teams SDK.

**Comment by MudulOzan** [comment]
Thanks, we found graph api and using it now.
