### ISSUE TITLE
Need Help acquiring Tokens using MSAL. js for Datverse APIs

### ISSUE THREAD

**Issue by dheerajbalmuri** [AzureAD/microsoft-authentication-library-for-js#4916]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.26.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.2

### Description

Is there documentation on how to obtain tokens for Dataverse APIs using Msal .Js . I was able to obain it using post by following the [documentation](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/webapi/use-postman-web-api) but was wondering how we can do it using MSal. I am using React as frontend framework.

### MSAL Configuration

```javascript
auth: {
      clientId: "Client ID",
      authority: "https://login.microsoftonline.com/Tenant Id", // This is a URL (e.g. https://login.microsoftonline.com/{your tenant ID})
      redirectUri: "http://localhost:3000/",
    },
    cache: {
      cacheLocation: "sessionStorage", // This configures where your cache will be stored
      storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
    }
  };
  
  // Add scopes here for ID token to be used at Microsoft identity platform endpoints.
  export const loginRequest = {
   scopes: ["User.Read", "https://admin.services.crm.dynamics.com/user_impersonation"]
  };
```

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by hectormmg** [comment]
@dheerajbalmuri please check out our [MSAL React](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-react) library docs for information on how to use it to acquire tokens on your React app. Please let us know if this helps resolve your question so we can close the issue.
