### ISSUE TITLE
AADSTS50058 - Unable authenticate on MS Teams Desktop App

### ISSUE THREAD

**Issue by tiennguyen1293** [AzureAD/microsoft-authentication-library-for-js#4918]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.26.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

0

### Description

Using template [tab-aad-msal2](https://github.com/pnp/teams-dev-samples/tree/main/samples/tab-aad-msal2)

And upgrade 
```
"@azure/msal-browser": "^2.26.0",
"@microsoft/teams-js": "^2.0.0",
```

`this.msalClient.loginRedirect(this.request)` working on Teams Web, but not working on Teams Desktop App

### Error Message

```
InteractionRequiredAuthError: AADSTS50058: A silent sign-in request was sent but no user is signed in. The cookies used to represent the user's session were not sent in the request to Azure AD. This can happen if the user is using Internet Explorer or Edge, and the web app sending the silent sign-in request is in a different IE security zone than the Azure AD endpoint (login.microsoftonline.com). Trace ID: f6450045-e435-4fa7-8dcb-b1e7da7f2300 Correlation ID: b88afb3e-7b95-48fc-a68e-5875238dd1d3 Timestamp: 2021-01-28 08:56:59Z
```

### Msal Logs

<img width="736" alt="image" src="https://user-images.githubusercontent.com/26110369/174554875-53cb7cca-dca9-4452-935e-70c9f69fe326.png">

### MSAL Configuration

```javascript
const msalConfig = {
            auth: {
                clientId,
                authority,
                redirectUri
            },
            cache: {
                cacheLocation: "localStorage",
                storeAuthStateInCookie: false
            }
};
```

### Relevant Code Snippets

```javascript
this.msalClient.loginRedirect(this.request);
```

### Reproduction Steps

1. Login in Microsoft Teams Desktop App
2. Select Tab
3. Click Login
4. Open devTool in Iframe Auth
5. Observe

### Expected Behavior

`loginRedirect` successfully.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by bmahall** [comment]
@tiennguyen1293 Does this issue persist only for Chrome or any other browsers as well? Are you using incognito mode?
 Can you please try enabling storeAuthStateInCookie and issuing the redirect call , and let us know. Thanks!

**Comment by tiennguyen1293** [comment]
Hi @bmahall , i didn't using incognito mode and i tried change brower default on MacOS, but it's still not working

NOTE: issue happening Teams Desktop App when i using `microsoftTeams.authentication.authenticate` from `"@microsoft/teams-js": "^2.0.0"` and open login popup, Teams Web (https://teams.microsoft.com) its working.

```
cache: {
        cacheLocation: BrowserCacheLocation.LocalStorage,
        storeAuthStateInCookie: true,
},
```

<img width="668" alt="image" src="https://user-images.githubusercontent.com/26110369/174716565-0590263b-a17a-4e9d-838e-684372374c6a.png">

<img width="1654" alt="image" src="https://user-images.githubusercontent.com/26110369/174719033-b3a3a995-1bcd-46dd-bc61-1793056cb80f.png">

**Comment by derisen** [comment]
@tiennguyen1293 can you share the code block that throws this error? If there was indeed a silent sign-in request, it would be expected to fail on Teams Desktop as the desktop client won't have access to AAD session cookies that the system browser has, so this error needs to be caught and handled with an interactive login request (loginRedirect).

**Comment by tiennguyen1293** [comment]
Thank for your response @derisen, 

I was using `microsoftTeams.authentication.authenticate` to open popup on Teams Desktop provided by `@microsoft/teams-js` and after that I redirect to page using silent sign-in.

I implemented like [react-router-sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/react-router-sample) example from this repo and have updated `prompt: "none"` param in `loginRedirect` func.

```
instance.loginRedirect({
      ...loginRequest,
      prompt: "none"
    });
```

**Comment by tiennguyen1293** [comment]
And if Silent Auth is expected to fail on Teams Desktop, Do we have any way to get session sign-in of the user to no need to re-login?

**Comment by derisen** [comment]
@tiennguyen1293 I haven't tried the sample myself but I don't think there's much you can do to avoid popups with this setup, as [noted by the author](https://github.com/pnp/teams-dev-samples/tree/main/samples/tab-aad-msal2#summary) (by the way is the user prompted for full sign-in, or just seeing a brief popup?). Did you had a chance to try out the [Teams Tab SSO](https://github.com/pnp/teams-dev-samples/tree/main/samples/tab-sso/src/nodejs) sample instead?

**Comment by tiennguyen1293** [comment]
User just see a brief popup, and after that I saw the errors.

By the way, i found the root cause was because i used `prompt: "none"` and it didn't work on Teams Desktop. If I remove it, Teams desktop will redirect to login page instead of showing an error.

**Comment by derisen** [comment]
That's right, I should have mentioned, `prompt: none` is the issue here.

**Comment by tiennguyen1293** [comment]
Do we have a plan to fix it?

**Comment by ghost** [comment]
This issue requires attention from the MSAL.js team and has not seen activity in **5 days**. @bmahall please follow up.

**Comment by derisen** [comment]
@tiennguyen1293 Apologies for late response. Seeing some brief prompts is an inherent limitation with this setup, so what I meant is that setting `prompt: none` will prevent msal to acquire tokens via the popup opened by Teams, hence it shouldn't be set in the first place. Achieving SSO will require some server component in the setup, so you should check out the [Tab SSO sample](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-sso/nodejs) or the [App Auth sample](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-auth/nodejs) as suggested. @bmahall any other thoughts?

**Comment by tiennguyen1293** [comment]
@derisen I'm implementing sample code from you guys, i will respond as soon as I done.

**Comment by tiennguyen1293** [comment]
Hi @derisen i still get a login page, even when I'm signed in to Microsoft Teams Desktop App.
i based on [App Auth sample](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-auth)

<img width="891" alt="image" src="https://user-images.githubusercontent.com/26110369/178648962-c61ab173-bcbe-420a-b7ec-0d127570a5a1.png">
<img width="483" alt="image" src="https://user-images.githubusercontent.com/26110369/178649070-935ed773-3908-4a00-bdc6-c119cafbcbf3.png">

**Comment by derisen** [comment]
@tiennguyen1293 apologies, we haven't developed that particular sample. Let me take some time to go through it, but it might be faster to direct this query to the maintainers of the [Microsoft-Teams-Samples](https://github.com/OfficeDev/Microsoft-Teams-Samples) repo. On the other hand, we did contribute the [Tab SSO sample](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-sso/nodejs), which has single sign-on for sure -you might want to refer to that.

**Comment by tiennguyen1293** [comment]
hi @derisen

and Why the issue was closed? :(

I used 2 samples, it just works on Teams Web, but doesn't work on Teams Desktop.

Still facing the issue.
`InteractionRequiredAuthError: AADSTS50058: A silent sign-in request was sent but no user is signed in. The cookies used to represent the user's session were not sent in the request to Azure AD. This can happen if the user is using Internet Explorer or Edge, and the web app sending the silent sign-in request is in a different IE security zone than the Azure AD endpoint (login.microsoftonline.com). Trace ID: f6450045-e435-4fa7-8dcb-b1e7da7f2300 Correlation ID: b88afb3e-7b95-48fc-a68e-5875238dd1d3 Timestamp: 2021-01-28 08:56:59Z`

I'll try to detail the code flow below:

We have a Leap Work web which is displayed as a Personal Custom App within Teams. This web talks to one of the Azure Service APIs and for authentication with that API, we have been trying to use
```
"@azure/msal-browser": "^2.26.0",
"@microsoft/teams-js": "^2.0.0",
```
The flow:
1. User logs on to Microsoft Teams on Desktop Teams, Web Teams, Android/IOS Teams.
2. User accesses to Leap Work Personal Custom App. the App use `microsoftTeams.authentication.authenticate` to open login popup, and then request `this.msalClient.handleRedirectPromise` to check if there have any response or account already, 
- if YES use `this.msalClient.setActiveAccount(response.account)` => authenticated flow successfully
- if NO use `loginRedirect` to login
```
this.msalClient.loginRedirect({
   ...loginOptions,
   prompt: 'none',
})
```

And actually, it's always NO on Teams Desktop,

`prompt: 'none'` to implement for Silent Authenticate on Microsoft. Ref: [link](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-silent-aad#how-silent-authentication-works)

3. Observer the error message thrown above, my expectation is authenticated flow successfully instead of redirect to Microsoft Login Page.

**Comment by derisen** [comment]
@tiennguyen1293 sorry for the confusion, issues without response gets stale and close automatically.

As we discussed before, you'll need to remove the `prompt: 'none'` as interaction is needed at this stage and there is no way avoiding it. The article on the link you've shared also mentions this:

> The Active Directory Authentication Library creates a hidden iframe for OAuth 2.0 implicit grant flow. But the library specifies prompt=none, so Azure AD does not display the sign-in page. User interaction may be needed if the user needs to sign in or grant access to the application. If user interaction is necessary, Azure AD returns an error that the library reports to your app. If necessary, your app can now display a sign-in option.

**Comment by tiennguyen1293** [comment]
Hi @derisen, Thank you for responding so quickly.

So this is limitation in the library? Or can you suggest an alternative solution that can allow silent authentication on Teams desktop client?

**Comment by derisen** [comment]
@tiennguyen1293 the best approach for SSO is demonstrated in the [Teams Tab OSS sample](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/tab-sso/nodejs). Are you saying that, when you try the sample as it is (without setting the prompt), you are prompted to sign-in when accessing the tab application? (that is, after signing into the Teams desktop client itself, you shouldn't be prompted for sign-in again when accessing the tab app).

I'm afraid there's no other alternative. Setting the `prompt: 'none'` might work on the web client since probably the user already has an active session with Azure AD (say, you signed in with Azure AD somewhere else before, and the session cookie is not expired), but on the desktop client, the first sign-in is needed to establish an active session (that is, if you don't use the SSO approach explained [here](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-overview)). 

@jasonnutter is there anything else to recommend here?

**Comment by jasonnutter** [comment]
@derisen For now, that is correct. If you are unable to perform the OBO flow on your own server to silently acquire tokens (demonstrated in the sample), you can try what you describe, otherwise, you will need to show a prompt (via the Teams SDK, as also shown in the sample).

**Comment by tiennguyen1293** [comment]
Hi @derisen @jasonnutter 

I'm understanding you are not sure about silently acquiring tokens will work on Teams Desktop App?
For some reason, we still have to display a prompt to re-login again in the Teams Tab app.

I'm meaning Teams App => login => Tab App => get Token => re-login?

**Comment by tiennguyen1293** [comment]
So ... Do we help update the DOC on [this](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-silent-aad#how-silent-authentication-works)?

Just to clearly and for others to have the same question as me.

**Comment by jasonnutter** [comment]
> Hi @derisen @jasonnutter
> 
> I'm understanding you are not sure about silently acquiring tokens will work on Teams Desktop App? For some reason, we still have to display a prompt to re-login again in the Teams Tab app.
> 
> I'm meaning Teams App => login => Tab App => get Token => re-login?

If you are not able to perform the OBO flow using the Teams SSO token (as shown in the sample) you can try invoking ssoSilent on page load to attempt to silently sign in. If that fails, you will need to invoke an interactive prompt.

> So ... Do we help update the DOC on [this](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-silent-aad#how-silent-authentication-works)?

> Just to clearly and for others to have the same question as me.

Yes, those docs should probably be updated. cc @EmLauber

**Comment by tiennguyen1293** [comment]
Many thanks team !!!

**Comment by derisen** [comment]
Created an issue for the team to update their docs. Closing this cc @EmLauber
