### ISSUE TITLE
MSAL Angular Forgotten password error event not caught with PathLocationStrategy

### ISSUE THREAD

**Issue by euphoria3k** [AzureAD/microsoft-authentication-library-for-js#4920]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.26.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.3.2

### Description

Hi, I have a problem and i'm unsure whether it is a bug or me doing something dumb.

I have reproduced the problem using the Angular 11 B2C sample application, with PathLocationStrategy routing enabled.
If I navigate to a **protected** route, I get redirected to the login screen, but if i click the forgotten password link, the LOGIN_FAILURE event is not raised back in my application (currently inside app.component.ts). 
However, if I click the login button from an **unprotected** page and click the forgotten password link, the event is raised as expected.

Also if I switch to using HashLocationStrategy then both scenarios work perfectly.

Below is the code i added to handle the AADB2C90118 code received for the forgotten password flow in app.component.ts.

```
this.msalBroadcastService.msalSubject$
      .pipe(
        filter(
          (msg: EventMessage) =>
            msg.eventType === EventType.LOGIN_FAILURE ||
            msg.eventType === EventType.ACQUIRE_TOKEN_FAILURE
        ), takeUntil(this._destroying$)
      ).subscribe((result: EventMessage) => {
        if (result.error) { 
          // Check for forgot password error
          if (result.error.message.includes('AADB2C90118')) {
            let resetPasswordFlowRequest = {
              scopes: ['openid'],
              authority: b2cPolicies.authorities.forgotPassword.authority,
            };
            this.login(resetPasswordFlowRequest);
          }
        }
      });
```

Many thanks for your help

### MSAL Configuration

```javascript
auth: {
      clientId: CLIENT_ID, // PPE testing environment
      authority: b2cPolicies.authorities.signUpSignIn.authority, // PPE testing environment.
      redirectUri: 'https://localhost:5001/auth',
      postLogoutRedirectUri: 'https://localhost:5001/',
      knownAuthorities: [b2cPolicies.authorityDomain],
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE, // set to true for IE 11
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Info,
        piiLoggingEnabled: false,
      },
    },
```

### Identity Provider

Azure B2C Basic Policy

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@euphoria3k Thank you for your patience. I was able to reproduce this behavior, and am investigating a fix or a workaround. 

To clarify, are you getting the `LOGIN_FAILURE` event when the user clicks the forgot password link and cancels, or as soon as they click the forgot password link? If a user clicks the forgot password link and sets a new password, they should be able to log in, which should not result in a `LOGIN_FAILURE` event.

**Comment by euphoria3k** [comment]
@jo-arroyo thank you for your reply! The problem is that when the user clicks the forgotten password link, it returns to our site with the code AADB2C90118, but the LOGIN_FAILURE event doesn't get raised resulting in the user then not being redirected to the forgotten password flow at all.

**Comment by jo-arroyo** [comment]
@euphoria3k I've worked on a fix for msal-angular which should address your issue of not being able to get the LOGIN_FAILURE event. Feel free to take a look at #4998, which should be available in the next release.

**Comment by euphoria3k** [comment]
@jo-arroyo that is great! Thank you for the quick response 👍 I will keep an eye out for the release.

**Comment by euphoria3k** [comment]
@jo-arroyo unfortunately i have tried the new release with the Angular 11 B2C sample and the same problem still occurs. If you add the code to handle the LOGIN_FAILURE event to check for 'AADB2C90118', click "Web API" link to navigate to the protected path, it will redirect correctly to the login screen. However when you click the forgotten password link it returns to the sample app but does not trigger the LOGIN_FAILURE event in order to handle redirecting the user to the reset password flow. Thank you for all your help

**Comment by jo-arroyo** [comment]
@euphoria3k Did you configure the sample [like so](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/events.md#optional-msalbroadcastservice-configurations)?

**Comment by euphoria3k** [comment]
@jo-arroyo yes i have added the following to ngOnInit in app.component.ts

```
this.msalBroadcastService.msalSubject$
      .pipe(
        filter(
          (msg: EventMessage) =>
            msg.eventType === EventType.LOGIN_FAILURE ||
            msg.eventType === EventType.ACQUIRE_TOKEN_FAILURE
        ), takeUntil(this._destroying$)
      ).subscribe((result: EventMessage) => {
        if (result.error) { 
          // Check for forgot password error
          if (result.error.message.includes('AADB2C90118')) {
            let resetPasswordFlowRequest = {
              scopes: ['openid'],
              authority: b2cPolicies.authorities.forgotPassword.authority,
            };
            this.login(resetPasswordFlowRequest);
          }
        }
      });
```

Thanks

**Comment by jo-arroyo** [comment]
@euphoria3k Please add configuration values for the `MsalBroadcastService`, in addition to what you've done above. It is detailed in the docs I linked above (it will be in the app.module.ts, not in the app.configuration.ts), but I have also pasted the relevant parts below:

```js
// Make sure you are importing the MSAL_BROADCAST_CONFIG from msal-angular
import { ... MSAL_BROADCAST_CONFIG } from "@azure/msal-angular"; 

...
// In providers, add configuration values for the MsalBroadcastService. 
// You may need to change the number of replay values until the error appears for the flow
    providers: [
        {
          provide: MSAL_BROADCAST_CONFIG,
          useValue: {
            replayPastEvents: 2 // Set how many events you want to replay when subscribing
          }
        },
```

**Comment by euphoria3k** [comment]
@jo-arroyo thank you for your reply. I had not implemented the changes to the app.module.ts, however after doing so, i still can not get to work. I have pasted the code below:

```
providers: [
    {
      provide: HTTP_INTERCEPTORS,
      useClass: MsalInterceptor,
      multi: true,
    },
    {
      provide: MSAL_INSTANCE,
      useFactory: MSALInstanceFactory,
    },
    {
      provide: MSAL_GUARD_CONFIG,
      useFactory: MSALGuardConfigFactory,
    },
    {
      provide: MSAL_INTERCEPTOR_CONFIG,
      useFactory: MSALInterceptorConfigFactory,
    },
    {
      provide: MSAL_BROADCAST_CONFIG,
      useValue: {
        replayPastEvents: 2, // Set how many events you want to replay when subscribing
      },
    },
    MsalService,
    MsalGuard,
    MsalBroadcastService,
  ],
```

Thank you for your support

**Comment by jo-arroyo** [comment]
@euphoria3k Please try using different numbers for the `replayPastEvents` and see if it works.

**Comment by euphoria3k** [comment]
@jo-arroyo i have tried increasing the value with several different values and it doesn't seem to make any difference.

**Comment by jo-arroyo** [comment]
@euphoria3k Can you check that you are filtering for the right error when subscribing to the failure events?

**Comment by euphoria3k** [comment]
@jo-arroyo i am filtering like so

```
this.msalBroadcastService.msalSubject$
      .pipe(
        filter(
          (msg: EventMessage) =>
            msg.eventType === EventType.LOGIN_FAILURE ||
            msg.eventType === EventType.ACQUIRE_TOKEN_FAILURE
        ), takeUntil(this._destroying$)
      ).subscribe((result: EventMessage) => {
        if (result.error) { 
          // Check for forgot password error
          if (result.error.message.includes('AADB2C90118')) {
            let resetPasswordFlowRequest = {
              scopes: ['openid'],
              authority: b2cPolicies.authorities.forgotPassword.authority,
            };
            this.login(resetPasswordFlowRequest);
          }
        }
      });
```

**Comment by jo-arroyo** [comment]
@euphoria3k Could you try console logging or otherwise printing the result.error to make sure that 'AADB2C90118' is the error being thrown? I am not able to reproduce that exact error because our samples do not use the legacy password reset policy. Have you considered using the self-service password reset policy detailed [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-password-reset-policy?pivots=b2c-user-flow#self-service-password-reset-recommended)?
