### ISSUE TITLE
Please add b2clogin.com support to the list of trusted authorities

### ISSUE THREAD

**Issue by ryancole** [AzureAD/microsoft-authentication-library-for-js#493]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

There is an object of trusted authorities in [this code here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/fdbf3329d246466354dece033a62c26752ed9d05/lib/msal-core/src/AadAuthority.ts#L45-L52). It does not include or support the newer b2clogin.com domain, though. Currently, it is required to disabled authority verification in order to use b2clogin.com.

It does not look as simple as just adding a new entry to that object because the b2clogin approach includes a custom URL segment.

**Comment by navyasric** [comment]
Same as #435
