### ISSUE TITLE
How to navigate desired URL after Azure AD Login

### ISSUE THREAD

**Issue by raiajithkumarr** [AzureAD/microsoft-authentication-library-for-js#4938]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

1.4.4

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

None

### Description

Hi Team,

We are using Azure AD Authentication to validate users after successful verification it is navigating to configured redirect url

For example : 

**redirecturi** : https://www.testurl.com (Configured in App registration under Auzre portal)
Here it will navigate azure ad login page after successful login it will navigate to above redirecturi.

**Problem :**  Now If user is trying to access specific document or specific url as mentioned below  (If user is not authenticated)

https://www.testurl.com/data/100

User should navigate to Azure AD login page >> after successful login >> it should navigate to user requested URL for example above URL (https://www.testurl.com/data/100), But it always going to configured **redirecturi** i.e. **https://www.testurl.com**.

How to handle this type of scenario to navigate to desired URL?

### MSAL Configuration

```javascript
const MsalObj = new UserAgentApplication({
    auth: {
        clientId: config.msalConfig?.clientId,
        authority: config.msalConfig?.authority,
        postLogoutRedirectUri: config.msalConfig?.postLogoutRedirectUri,
        redirectUri: config.msalConfig?.redirectUri
    },
    cache: {
        cacheLocation: 'sessionStorage',
        storeAuthStateInCookie: false
    }
});
```

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by raiajithkumarr** [comment]
Hi Team,
Please provide some information on this question

**Comment by jo-arroyo** [comment]
@raiajithkumarr Can you please confirm whether your application is using MSAL 1.x or msal-react (which wraps MSAL 2.x)?

If MSAL 1.x, can you try setting `navigateToLoginRequestUrl` to `true` in your `auth` configurations?

```js
const MsalObj = new UserAgentApplication({
    auth: {
        clientId: config.msalConfig?.clientId,
        authority: config.msalConfig?.authority,
        postLogoutRedirectUri: config.msalConfig?.postLogoutRedirectUri,
        redirectUri: config.msalConfig?.redirectUri,
        navigateToLoginRequestUrl: true
    },
    cache: {
        cacheLocation: 'sessionStorage',
        storeAuthStateInCookie: false
    }
});
```

**Comment by raiajithkumarr** [comment]
We are using MSAL 1.X version only i.e.  "msal": "^1.4.4"

Even after using **navigateToLoginRequestUrl: true** property still it is redirecting to home page only and it is asking AAD login two times after that it is navigating to home page instead of requested URL

**Locally it is working fine (even using state also same behavior) only on deployed version we are facing this issue.**

We deployed on edge like this "https://testurl.azureedge.net/"

When user is trying to access resource directly from browser like this "https://testurl.azureedge.net/data/1" >> it is navigating to AAD login >> after providing Login details >> Again navigating to AAD login screen >> After providing login details >> Going to Dashboard Instead of **"https://testurl.azureedge.net/data/1"**

We are using React to connect AAD through MSAL1.x

Please suggest me here.

**Comment by jo-arroyo** [comment]
@raiajithkumarr Are you able to provide verbose logs for this behavior?

**Comment by raiajithkumarr** [comment]
Hi @jo-arroyo 
You want verbose logs from deployed version means application insight ? or locally ?

Currently locally it is working fine

**Comment by raiajithkumarr** [comment]
After doing analysis of this behavior observed that, if we try to navigate child URL other than Origin(http://testurl.com)  for example  **http://testurl.com/data/1 or http://testurl.com/report/1** or anything like this it will navigate to AAD login page ( https://login.microsoftonline.com/<tenantId>/oauth2/v2.0/authorize?response_type=id_token&scope) **twice**

How to handle this behavior.

Instead of using this "**navigateToLoginRequestUrl** " we are trying to handle at landing/home page of application to navigate to user requested URL While doing this we observed above behavior and please find attachment for verbose logs (PII is disabled logs )

[300620222033_MSAL.log](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/9021131/300620222033_MSAL.log)

if you need **navigateToLoginRequestUrl** enabling logs please let me know.
I think above behavior is same for enabling **navigateToLoginRequestUrl** also.

**Comment by ghost** [comment]
This issue requires attention from the MSAL.js team and has not seen activity in **5 days**. @jo-arroyo please follow up.

**Comment by raiajithkumarr** [comment]
Hi @jo-arroyo ,
Any updates on this issue.
It is going two times for AAD login (I think first time it is not getting token through msal.js library).

Please suggest here

**Comment by sudeep-yadagiri** [comment]
Hi Ranjith, Have you deployed this application in Azure portal?

**Comment by jo-arroyo** [comment]
@raiajithkumarr Can you confirm that you are using the correct redirectUri in your deployed application?
Also, is the navigation to AAD only happening on the deployed version or on your local app as well?

**Comment by raiajithkumarr** [comment]
Due to some other hooks it is calling authorization very fast before we get the response from MSAL Library.
Now we applied some delay with this it is working fine.

So I am closing this request.
