### ISSUE TITLE
useIsAuthenticated is false on first load

### ISSUE THREAD

**Issue by theoturner** [AzureAD/microsoft-authentication-library-for-js#4941]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.23.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.3.2

### Description

[This has been raised before and a fix merged](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2846), but the problem was not actually fixed.

`useIsAuthenticated` is always false on first load until the first `useMsal().loginRedirect()`, meaning a button must be pressed to log in.

The most obvious fix is to just add a hook which calls the above. This however leads to a very large number of redirects which does work sometimes, but often boots the user out to Microsoft account selection with the error message `We couldn’t sign you in. Please try again.`

I believe preferable behaviour, as per the linked issue, is for `useIsAuthenticated` to have the correct value on first load.

### MSAL Configuration

```javascript
auth: {
    clientId: MY_CLIENT_ID,
    authority: 'https://login.microsoftonline.com/MY_TENANT',
    redirectUri: 'http://localhost:3000/',
  },
  cache: {
    cacheLocation: 'sessionStorage',
    storeAuthStateInCookie: false,
  },
};
```

### Relevant Code Snippets

```javascript
import { useIsAuthenticated, useMsal } from '@azure/msal-react';

const handleLogin = (instance) => {
  const loginRequest = {
    scopes: ['api://my-app/access_as_user', 'User.Read'];,
  };
  instance.loginRedirect(loginRequest).catch((e) => {
    console.error(e);
  });
};

const App = () => {
  const { instance } = useMsal();
  const isAuthenticated = useIsAuthenticated();
  return (
    <>
      { isAuthenticated ? <span>Signed In</span> : <button onClick={() => handleLogin(instance)}>Sign in</button> }
    </>
  );
};

export default App;
```

### Reproduction Steps

Run code above as react app. Sign in button displays even if signed in to specified scope.

### Expected Behavior

Sign in button should not display as useIsAuthenticated should equal true.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Safari, Other

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@theoturner Can you clarify what you mean by "first load"? Do you mean the first load of the tab, or the first render of each page load? If you mean the former, you can persist state across tabs/browser instances by using local storage instead of session storage.

**Comment by theoturner** [comment]
By first load I mean first of the tab. Thank you for the pointer to use localStorage in the MSAL Config. That works!

Alternatively, if you can't use localstorage, this useEffect hook also works:
```js
useEffect(() => {
  instance.handleRedirectPromise().then((tokenResponse) => {
    if (!tokenResponse) {
      const accounts = instance.getAllAccounts();
      if (accounts.length === 0) {
        instance.loginRedirect();
      }
    }
  }
});
```

**Comment by marcbernalencora** [comment]
I am presenting the same behavior. I am doing a `instance.loginRedirect(loginRequest)` and the login works, also I see the tokens and login data on localStorage and also sessionStorage (tried both). When the render happens again (or consecutive ones, refreshing page, etc) `const isAuthenticated = useIsAuthenticated();` is always false. 

Any advice? Thanks !
