### ISSUE TITLE
How to keep a mobile SPA user logged in for more than a day

### ISSUE THREAD

**Issue by zarko-tg** [AzureAD/microsoft-authentication-library-for-js#4944]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.26.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

We have an existing B2B-type of mobile app built using Apache Cordova, basically a SPA running locally on the device. Some of our clients/users wants to log into our own service using their Azure accounts. The app doesn't need access to any special/other user resources in Azure AD / Graph.

After some trial and error we did managed to get login and logout working on both iOS and Android, using the redirect API (The discussion was here https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4910).

The issue now is how to make sure users stay logged in without any interaction on their side, whether they open the app every day or not. The only cases where they would need to log in again is if the user is deleted, their password has been changed, or an admin has for ex. revoked their session(s).

The challenge is that I am not able to decode/understand related Azure online documentation and the 24h period doesn't make it easy to test what happens when due. Does one need to wait 24h before every attempt of cooking up a possible solution and testing?

Atm. the app is calling acquireTokenSilent for a logged in user that starts/comes back to the app. This works as expected on both OS's - it does refresh tokens. But if one hasn't opened the app for more than 24h this call fails at which point we are forced to take the user to the login page. Due to the problem with testability I don't yet have details on the error, but I suppose it's because of the expiration.

How are we supposed to approach or solve this?

### MSAL Configuration

```javascript
{
      auth: {
        protocolMode: 'OIDC',
        clientId: 'OUR CLIENT ID',
        authority: 'https://login.microsoftonline.com/OUR TENANT ID',
        redirectUri: 'http://localhost:8100',
        postLogoutRedirectUri: 'http://localhost:8100'
      },
      cache: {
        cacheLocation: 'localStorage'
      }
}
```

### Relevant Code Snippets

```javascript
let result;
try {
  result = await this._app.acquireTokenSilent({
    account: this._app.getAccountByHomeId(homeAccountId),
    forceRefresh: true,
    scopes: this._msal.OIDC_DEFAULT_SCOPES
  });
} catch(e) {
  if (e instanceof this._msal.BrowserAuthError) {
    if (e.errorCode === this._msal.BrowserAuthErrorMessage.noNetworkConnectivity.code) {
      return;
    }
  }

  console.log('AuthAzure.verify failed', e);
}
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@zarko-tg This is expected behavior. Refresh tokens used in single page apps and with the authorization code flow are limited to 24 hours. Once outside the 24 hour window, it is supposed to fail and require interactive login. Please see [this document](https://docs.microsoft.com/en-us/azure/active-directory/develop/refresh-tokens#token-timeouts) about refresh tokens lifetimes and [this document](https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-third-party-cookies-spas#overview-of-the-solution) about refresh tokens and the auth code flow.

**Comment by zarko-tg** [comment]
@jo-arroyo Thanks @jo-arroyo, I am more or less aware of that limitation since I've been through documentation a number of times. But that likely means a bad user experience. How many (good) mobile apps are there which force the user to log in manually again after a day of inactivity?

The reason for filing this issue is to look for any possible configuration, workaround or a solution. Is there any at all?

I think this challenge isn't specific to Cordova type SPA mobile apps, but also React, Angular and similar.

**Comment by jo-arroyo** [comment]
@zarko-tg Unfortunately, MSAL.js has to abide by the refresh token lifetimes set by the service, and we're unable to provide a workaround at this time. While we recognize that this is not the best user experience, the 24 hour limit was chosen for [security reasons](https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-third-party-cookies-spas#security-implications-of-refresh-tokens-in-the-browser) for single-page apps. If you choose to write a mobile app that is not a single-page app, extended refresh token lifetimes may be available to you.

**Comment by zarko-tg** [comment]
@jo-arroyo Ok, that confirms our concerns.

Changing a tech stack and large code base immediately is not realistic. We are going to try a solution that basically does not depend on any MSAL/Azure sessions (refreshing tokens and related complexity). It'll be a bit of an improvisation but at least we will not force users to log in frequently and repetitively.

Our own system / backend has its own user session management so we'll rely on it instead, while continuing to use only MSAL login and logout. A few user properties in Azure / Graph API will inform our system when to drop the user session in the app - the very existence of the user, "accountEnabled", "lastPasswordChangeDateTime" and/or "passwordProfile". This can be done by a dedicated authorized daemon / server application set up to read all users / properties.

**Comment by nevertheless1975** [comment]
@jo-arroyo @zarko-tg what about bullet point 5 in documentation below (Token Renewal)? 

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/token-lifetimes.md

This sounds like there's still something being tried on MSAL side to fetch another access token, even if the refresh token is expired. 

> If the refresh token is expired, MSAL will attempt to retrieve an access tokens silently using a hidden iframe. This will use the sid or username in the account's claims object to retrieve a hint about the user's session. If this hidden iframe call fails, MSAL will pass on an error from the server as an InteractionRequiredAuthError, asking to retrieve an authorization code to retrieve a new set of tokens. You can do this by performing a login or acquireToken API call with the PublicClientApplication object. If the session is still active, the server will send a code without any user prompts. Otherwise, the user will be required to enter their credentials.

It seems to work for us. What would be the reason if this does not work?
