### ISSUE TITLE
Mechanism used to fetch Tokens from MSa Service

### ISSUE THREAD

**Issue by ashitaagrwl** [AzureAD/microsoft-authentication-library-for-js#4946]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

None

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

None

### Description

HI Team, I am currently working on a chrome extension and we have a limitation that from Manifest Version3, chrome extensions don't allow the usage of XMLHttpRequest. I would like to confirm if the access tokens using in the MSAL library are extracted using fetch API or XMLHttpRequest.

### Source

Internal (Microsoft)

**Comment by jo-arroyo** [comment]
@ashitaagrwl Where the Fetch API is detected (i.e. `window.fetch && window.Headers`), MSAL will use Fetch instead of XMLHttpRequest.
