### ISSUE TITLE
token size with groups

### ISSUE THREAD

**Issue by SimonManfredo** [AzureAD/microsoft-authentication-library-for-js#4947]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.23.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.0

### Description

authentication works fine and I get Access token and ID Token. but in some cases the ID token is too long. greater than 11 thousand characters and causes me that when sending it to my backend, I get a 413 error for being too large. I saw what happens because it returns all the groups to which the user belongs, if he belongs to many, the token is too long and I can't use it.

Is there a way to select the groups I need or to generate a smaller token?

thanks

### Source

External (Customer)

**Comment by derisen** [comment]
@SimonManfredo you can configure group claims to contain only the groups that are assigned to the application (though you won't be receiving nested groups that way). More on this [here](https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-fed-group-claims). Also, you normally shouldn't pass the id token to another application -group claims can also be added to access tokens if that's what you are after.

**Comment by derisen** [comment]
Closing this assuming to be resolved, but let us know if you have a follow-up.
