### ISSUE TITLE
Security concerns over caching security tokens in browser storage.

### ISSUE THREAD

**Issue by Ra-Sedgwick** [AzureAD/microsoft-authentication-library-for-js#495]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x ] Other... Please describe:
</code></pre>

## Browser:
- [ x] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: Any

## Current behavior

Id and Access tokens are being cached in either local or session storage which would leave them open to CSS attacks right? Is this Safe?

Is it possible to configure the library not to cache these tokens?

## Minimal reproduction of the problem with instructions

</code></pre>

**Comment by Mabiro** [comment]
@Ra-Sedgwick : Isn't it a concern, as id_tokens are used to validate access to your API?
