### ISSUE TITLE
MSAL doesn't recognize the signed MS Account when there are multiple accounts Signed 

### ISSUE THREAD

**Issue by baggiolorenzo** [AzureAD/microsoft-authentication-library-for-js#4954]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.24.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.3.0

### Description

We have two sites published in two different servers on the same domain (currently azurewebsites.net) that use MSAL to authenticate the user.
The Internal site is called by the Main site via 'iframe'.

When only one user authenticates to the Main site, the Internal site inherits the Active Account and works fine.

Instead when there are multiple Active Account the Main site lets you correctly choose which user to use, but the Internal site doesn't recognize the choice and try to propose it again.

### MSAL Configuration

```javascript
const config = {
    auth: {
      clientId: environment.clientId,
      authority: 'https://login.microsoftonline.com/' + environment.config.tenant,
      redirectUri: environment.redirectUri,
      postLogoutRedirectUri: environment.redirectUri,
      navigateToLoginRequestUrl: true,
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE,
    },
    system: {
      allowRedirectInIframe: true,
    }
};

const guard = {
    interactionType: InteractionType.Redirect,
    authRequest: {
      scopes: [
        'user.read'
      ],
    }
};
```

### Relevant Code Snippets

```javascript
constructor(private authService: MsalService){}

...
// Multiple Accounts Scenario

this.authService.instance.getActiveAccount() // Is null in the Internal Site even if in the Main Site there was the choice
this.authService.instance.getAllAccounts() // Is empty in the Internal Site
...
```

### Reproduction Steps

1. Signed in with two AAD accounts
2. Sign with one of them
3. In another Browser Tab a site use the MSAL login, doesn't recognize the previous choice

### Expected Behavior

The Internal Site should recognize that a choice has been made and it should automatically perform the login

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by baggiolorenzo** [comment]
We published two application on the same domain, connected to the same Azure Application.  to check if after reproducing the situations of the multiple AAD Accounts signed the problem remains.

**Comment by baggiolorenzo** [comment]
We published two application linked to the same Azure Application, on the same domain, to test the problem of the multi AAD signed accounts. After logging in an application, the second one didn't recognize the current Active Account and reproposed the login form.

**Comment by sameerag** [comment]
When you say same domain, is it as per [same domain rules](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy), and can you please confirm if the cache is shared?  I suspect the cache isn't and hence you are unable to fetch the accounts info. Please let us know once you check this.
