### ISSUE TITLE
MSAL Angular not Ivy compatible

### ISSUE THREAD

**Issue by Pablodotjs** [AzureAD/microsoft-authentication-library-for-js#4956]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.26.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.3.2

### Description

I can't build applications that uses MsalModule if I'm using yarn plug and play

### Error Message

Error: src/app/app.module.ts:109:5 - error NG6002: 'MsalModule' does not appear to be an NgModule class.

109     MsalModule,
        ~~~~~~~~~~

  .yarn/__virtual__/@azure-msal-angular-virtual-851349a031/0/cache/@azure-msal-angular-npm-2.3.2-ce65851f15-85eafd6d54.zip/node_modules/@azure/msal-angular/msal.module.d.ts:5:22
    5 export declare class MsalModule {
                           ~~~~~~~~~~
    This likely means that the library (@azure/msal-angular) which declares MsalModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

### MSAL Configuration

```javascript
Default one in the angular 14 example
```

### Relevant Code Snippets

```javascript
Change the demo to use yarn plug and play
```

### Reproduction Steps

Change the angular 14 demo to use yarn plug and play and use yarn pnpify to use angular commands because that's the workaround to use plug and play with Angular

### Expected Behavior

Successfull build of applications

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@Pablodotjs We are aware that the current version of msal-angular may not be compatible with Ivy. This work is being tracked [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4298) and will be prioritized in future quarters.

@EmLauber for roadmap.

**Comment by jo-arroyo** [comment]
Closing because feature is being tracked in #4298 .

**Comment by johnvinosh** [comment]
![image](https://user-images.githubusercontent.com/26540475/197952087-2ab45fe2-ab1d-40de-864c-030e779667ad.png)

I am using Angular 14 and I am getting this error. Is there any workaround for this ?

**Comment by dansau84** [comment]
please give me a solution i got same error    :  

'MsalModule' does not appear to be an NgModule class.(-996002)
msal.module.d.ts(5, 30): This likely means that the library (@azure/msal-angular) which declares MsalModule is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
(method) MsalModule.forRoot(config: Configuration, angularConfig?: MsalAngularConfiguration | undefined): ModuleWithProviders<MsalModule>


app.mpdule.ts
  import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { environment } from "src/environments/environment";
import { MsalModule, MsalInterceptor } from "@azure/msal-angular";
import {
  HttpClientModule,
  HttpClient,
  HTTP_INTERCEPTORS,
} from "@angular/common/http";
import { MsalUserService } from "./msaluser.service";

export const protectedResourceMap: any = [
  [environment.baseUrl, environment.scopeUri],
];

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    MsalModule.forRoot({
      clientID: environment.uiClienId,
      authority: "https://login.microsoftonline.com/" + environment.tenantId,
      protectedResourceMap: protectedResourceMap,
      redirectUri: environment.redirectUrl,
    }),
    BrowserModule,
    AppRoutingModule,
    HttpClientModule,
  ],
  providers: [
    HttpClient,
    MsalUserService,
    {
      provide: HTTP_INTERCEPTORS,
      useClass: MsalInterceptor,
      multi: true,
    },
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }

**Comment by EmLauber** [comment]
@johnvinosh @dansau84 this issue is closed as a duplicate. You can track the most up to date information in #4298 for Ivy as we do not update/monitor closed issues.
