### ISSUE TITLE
loginRedirect doesn't work with React-Route V6 with a index Route

### ISSUE THREAD

**Issue by timtong1982** [AzureAD/microsoft-authentication-library-for-js#4965]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.26.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.2

### Description

When there is a index Route in the React-Route config, the loginRedirect will not acquire account

 "react-router-dom": "6.3.0",

### Msal Logs

{eventType: 'msal:initializeStart', interactionType: null, payload: null, error: null, timestamp: 1656696891048}
App.tsx?7629:18 {eventType: 'msal:initializeEnd', interactionType: null, payload: null, error: null, timestamp: 1656696891049}
App.Base.tsx?c56b:11 []
App.tsx?7629:18 {eventType: 'msal:handleRedirectStart', interactionType: 'redirect', payload: null, error: null, timestamp: 1656696891052}
App.Base.tsx?c56b:11 []
App.tsx?7629:18 {eventType: 'msal:handleRedirectEnd', interactionType: 'redirect', payload: null, error: null, timestamp: 1656696891054}
App.Base.tsx?c56b:11 []

### MSAL Configuration

```javascript
{
        clientId: '<my_app_id>',
        authority:
            'https://login.microsoftonline.com/<tenant_id>/',
        redirectUri: '/',
    }
```

### Relevant Code Snippets

```javascript
export const AppBase: React.FunctionComponent<IAppBaseProps> = (
    props: IAppBaseProps
): React.ReactElement<IAppBaseProps> => {
    const { msalInstance } = props;
    return (
        <MsalProvider instance={msalInstance}>

            <TestRoutes />
        </MsalProvider>
    );
};

const TestComp = () => {
    const { instance, accounts } = useMsal();
    console.log(accounts);
    return (
        <>
            <button
                onClick={() => {
                    instance.loginRedirect();
                }}
            >
                sign in
            </button>
            <button
                onClick={() => {
                    instance.logout();
                }}
            >
                sign out
            </button>
        </>
    );
};

const TestRoutes = () => {
    return (
        <Routes>
            <Route element={<Outlet />}>
                <Route path={'/testpath'} element={<TestComp />} />
            </Route>
            <Route index element={<Navigate to='testpath' />} /> // this is the trouble maker, comment this line make the login work
        </Routes>
    );
};
```

### Reproduction Steps

see the code above

### Expected Behavior

login success and acquired account info

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

External (Customer)

**Comment by timtong1982** [comment]
A possible reason is when the redirect back from AAD is happening, before MSAL process the response code, React Route the index route hijacked the URL and redirected it to the index route points

**Comment by tnorling** [comment]
@timtong1982  

> A possible reason is when the redirect back from AAD is happening, before MSAL process the response code, React Route the index route hijacked the URL and redirected it to the index route points

This is exactly right. When using a router with the redirect flow you must ensure that either:

1. Your route change is triggered **after** `handleRedirectPromise` has resolved
or
2. Your router preserves the url fragment (hash) during the route change

In your case your router is navigating to a static route, which results in the response hash from the login being lost.
