### ISSUE TITLE
More Information needed for "authority" option in MSAL js library for Azure AD B2C. It seems like a very important option.

### ISSUE THREAD

**Issue by xtianus79** [AzureAD/microsoft-authentication-library-for-js#4966]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular), MSAL React (@azure/msal-react), MSAL Node Extensions (@azure/msal-node-extensions), Not Applicable

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/redirects.md

### Description

I'll start with this as an example. 

```
https://login.bbbbbbbb.com/bbb5bbbbbbb01/b2c_1a_signup_scccccn/oauth2/v2.0/authorize?client_id=bbbbbbbbbbbbb&scope=openid%20profile%20offline_access&redirect_uri=http%3A%2F%2Flocalhost%3A6420&client-request-id=fbbbbbbbbbbbc7d5f&response_mode=fragment&response_type=code&x-client-SKU=msal.js.browser&x-client-VER=2.13.1&x-client-OS=&x-client-CPU=&client_info=1&code_challenge=etq0YbbbbbbVxbbbNjuZ-WL3bbbYtw&code_challenge_method=S256&nonce=390bbbb46bc-a46f-bb0167127b4c&state=eyJpZCbbbbbbbFjNiIsIm1ldGEiOnsiaWcccccccccccccccX0%3D
```

This is what I see from above ```<my custom domain>/<my app reg directory id (not tenant id)>/<policy-name>/oauth2/v2.0/authorize? + <clientId> + [[<openid> + <offline_access>]] + <redirect_uri> + <client-request-id> + <response_mode> + <response_type> + <code> + <x-client-sku> + <x-client-VER> + <x-client-OS> + <x-client-CPU> + <client_info> + <code_challenge> + <code_challenge_method> + <nonce> + <state>```

I know about 40% of what's going on up there. It pretty much falls off at client-request-id. Is there an api flow diagram explaining exactly what's going on? 

I'll pick out `nonce` for example. I didn't set that anywhere but yet it's there. Any additional information about that I should know?

***More over, and this is kind of the entire point, what makes this URI `"https://bbbbbbbbb.com/bbbbbb342-bbbd01/B2C_1A_SIGNUP_SIGbbbb"` do/transform the above URI with the following settings:

```
auth: {
      clientId: "............", // This is the ONLY mandatory field; everything else is optional.
      **[[authority]]**: b2cPolicies.authorities.signUpSignIn.authority, // Choose sign-up/sign-in user-flow as your default.
      knownAuthorities: [b2cPolicies.authorityDomain], // You must identify your tenant's domain as a known authority.
      redirectUri: "http://localhost:6420", // You must register this URI on Azure Portal/App Registration. Defaults to "window.location.href".
    },
```

The only thing I can tell that is kicking off the above authority is the `<Endpoints>` section in Azure AD B2C and specifically it is the `Azure AD B2C OAuth 2.0 authorization endpoint (v2)` section. Can I use others? When do I choose token endpoint (v2) versus OpenID Connect metadata document? 

***Which brings me to the sample Angular v2 docs and react for that matter. 

```
export function MSALInstanceFactory(): IPublicClientApplication {
  return new PublicClientApplication({
    auth: {
      clientId: 'bbbbbbbbbbb6',
      redirectUri: 'http://localhost:4200',
      postLogoutRedirectUri: 'http://localhost:4200'
    },
``` 

here the authority is not here. Should I add that like I did in the other sample app? Does this MSAL configuration need for me to find the AD B2C authorization endpoint v2 (for PKCE) (???is the token endpoint only for implicit MSAL v1???) flows and therefore that endpoint is the one I should choose? 

Also, would this documentation, I found somewhere, not be entirely correct? 

URI of the tenant to authenticate and authorize with. Usually takes the form of: (because... above)

```
https://{uri}/{tenantid}.
```

It becomes a "how did we get here" exercise that is painful based finding and linking and reading and finding and linking and reading... the current documentation situation. 

As well, I found this in the docs for MSAL JS v2. I am so happy after a week I even found those docs.
 
```
Type declaration
Optional authority?: string
You can configure a specific authority, defaults to " " or "[https://login.microsoftonline.com/common"](https://login.microsoftonline.com/common%22)
```

You see, that doesn't tell me anything at all. If I experiment with it over hours and hours eventually I can figure it out. But on something like the URI/authority why isn't it just fully and completely explained? It literally controls your login. It's not a small thing. 

Also, when you're putting these in wrappers it's even more abstracted away so if you don't explain it in the docs then it's always a pain to figure it out. 

With that said, if you all improved your documenation and created a more comprehensive spec that includes some important parts of the api i.e., like `Authority` you would see so much more wide spread adoption. Even the youtube videos are, in a sense, lacking.

**Comment by derisen** [comment]
@xtianus79 that's fair criticism mostly, but you see it's a double-edged sword. One goal of the library is to abstract away the details of OAuth 2.0 & OpenID Connect protocols (which is complex enough) AND how Azure AD/B2C implements that protocol (which introduces other idiosyncrasies) within reason. A proper discussion of `authority` would require getting into these details, which at that point, you might as well read the OAuth/OpenID [specs](https://oauth.net/specs/), or rather, the [protocol reference docs](https://docs.microsoft.com/en-us/azure/active-directory-b2c/authorization-code-flow) on docs.microsoft.com. I'm certain 90% of what goes into your example url above will become familiar afterwards.

But the point where your criticism particularly has merit is that there's a certain lack of connection between MSALs concept of authority and how docs.microsoft.com & Azure portal presents authority related information. That's mostly a verbiage issue, but what authority string should be supplied to MSAL configuration will not be immediately obvious to someone coming from docs or portal/app registration. So perhaps an `authority` guidance doc might help alleviate these concerns.

**Comment by derisen** [comment]
@xtianus79 apologies, this one fell through the cracks apparently. I've put this in the backlog and tracking internally, though I don't have an ETA unfortunately.

**Comment by derisen** [comment]
@xtianus79 please refer to the [authority doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/docs/authority.md) here. Closing this.
