### ISSUE TITLE
APPLE ID LOGIN: Need to login twice when used acquireTokenRedirect due to X-Frame-Options DENY ERROR

### ISSUE THREAD

**Issue by tsampath** [AzureAD/microsoft-authentication-library-for-js#4967]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

1.4.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

1.1.1

### Description

When we used acquireTokenRedirect as per suggestion given at https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1266, user needs to login twice as apple site is loaded in background at hidden Iframe. Is there way to handle this as we cannot ask user to login twice. 

### MSAL Configuration

```javascript
auth: {
        clientId: 'clientId',
        authority: b2cPolicies.authorities.signUpSignIn.authority :         
        navigateToLoginRequestUrl: true,
        knownAuthorities: [b2cPolicies.authorities.signUpSignIn.authority, b2cPolicies.authorities.signUp.authority],
        validateAuthority: false
    },
    cache: {
        cacheLocation: 'localStorage',
        storeAuthStateInCookie: isIE, 
    },
```

### Relevant Code Snippets

```javascript
N/A
```

### Reproduction Steps

1. Select AppleId login from B2C page

### Expected Behavior

Ask user to login only ones

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

External (Customer)

**Comment by tnorling** [comment]
@tsampath I would first suggest upgrading to `msal-browser` v2 and `msal-angular` v2 as this will provide you with a refresh token that can be used to silently acquire new access tokens for up to 24 hours. 

The x-frame options deny error happens when the IDP is expecting some sort of user interaction (such as sign in) which it cannot display in the hidden iframe (which is the only silent renewal method supported by the v1 libraries). I'm not familiar with Apple login but other IDPs allow you to provide them with a login_hint which may result in a non-interactive renewal. This is also worth exploring for both v1 and v2 implementations (for renewals after the refresh token is expired)

**Comment by tsampath** [comment]
@tnorling  Thanks for the reply. As I understand, as soon as initial authentication is successful, MSAL loads apple IDP within Iframe to do the silent login. Since Apple IDP does not allow to be loaded within Iframe, MSAL throws Interaction required error. As per suggested approach, when it triggers acquireTokenRedirect on Interaction required error, it does redirection to login again, which is not expected by user. Even if we upgrade to V2, if it also fallows same approach for silent renewal, we may experience the same issue with V2 also. Could you please confirm this?

Could someone reopen this ticket, since issue is not resolved?

**Comment by tnorling** [comment]
Msal.js v2 uses a refresh token instead of the hidden iframe for most token renewals. The hidden iframe is still used when the refresh token expires, however, this means you'll face this once every 24 hours instead of once per hour you are seeing in v1.

**Comment by tsampath** [comment]
Actually this happens as soon as user login into application using AppleID and not after one hour time. As soon as user logged in via Apple ID,  It loads Apple IDP within Iframe to do silent renewal/for obtaining access token. Since Apple IDP is not allowing to be loaded within IFrame, it throws Interaction required error. As a result of that user needs to login again. That is what we are trying to eliminate.      

We have IOS mobile application, which uses same B2C environment. IOS app review team is not approving App until we support AppleID login, while we provide other social login, as it is against their guide line.

Therefore could you please let us know that this issue will be there or not on V2, so that we can take a decision for upgrade.

**Comment by tnorling** [comment]
To reiterate what I said in my previous comment, silent token renewal in MSAL.js v2 _does not_ rely on iframes except when the refresh token expires. This happens once every 24 hours. Furthermore we recommend that everyone upgrade as v1 is no longer receiving any investment from our end outside of addressing security related issues.

**Comment by tsampath** [comment]
Thanks again for quick reply. Its much appreciated.  We will upgrade the package and see. I am just asking for curiosity. Dont we get [X-Frame-Options DENY ERROR, even if we get access token via refresh token after 24 hours time,  as we need to keep ADP loaded within Iframe as soon as user logged in?

**Comment by tnorling** [comment]
In v1 AcquireTokenSilent does the following:
1. Check the cache for unexpired tokens (will not throw x-frame options deny)
2. If 1 fails, open a hidden iframe to renew tokens (throws x-frame options deny)

In v2 AcquireTokenSilent does the following:
1. Check the cache for unexpired tokens (will not throw x-frame options deny)
2. If 1 fails use the refresh token to acquire new tokens (will not throw x-frame options deny)
3. If 2 fails open a hidden iframe to renew tokens (throws x-frame options deny)

You will never completely eliminate the need for interaction but as you can see above there is an extra step in v2 which extends your ability to acquire tokens silently so you should see this error less often.
