### ISSUE TITLE
Fallback to acquireTokenRedirect/popup when silent fails in msal-angular/angularjs interceptor

### ISSUE THREAD

**Issue by nehaagrawal** [AzureAD/microsoft-authentication-library-for-js#497]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ *] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ *] Chrome version XX
- [* ] Firefox version XX
- [* ] IE version XX
- [* ] Edge version XX
- [* ] Safari version XX

## Library version
msal-angular /msal-angularjs

<pre><code>
Library version: any version

## Current behavior
This issue was originally created as part of PR. I am just creating a github issue for tracking purpose.
https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/464/files
This was discussed internally with the team and it was approved as a valid feature request. 

Currently there is no way to fallback to acquireTokenRedirect/popup if acquireTokenSilent call fails in the interceptor. 

## Expected behavior
There should be a flag to configure if user wants to fallback to interactive flow of acquireTokenSilent fails in the interceptor. Flag could be called fallbackToInteractive. Apart from this flag we also need to use the config.popup flag to determine if we need to call acquireTokenRedirect/popup

## Minimal reproduction of the problem with instructions

</code></pre>

**Comment by sameerag** [comment]
Linking this with #786, We have this as a pattern in the core sample today, ensure it is integrated into the angular wrapper as the angular devs do not have a UI/Code control to call the fallback when aquireTokenSilent fails.

**Comment by DarylThayil** [comment]
linked to #945

**Comment by jasonnutter** [comment]
We did not get to this in MSAL Angular v1, but is a follow up improvement we want to make. Reopening and tracking.

**Comment by jasonnutter** [comment]
This is now possible is MSAL Angular v2: https://github.com/AzureAD/microsoft-authentication-library-for-js/releases/tag/msal-angular-v2.0.0-alpha.0

Closing.
