### ISSUE TITLE
question about login page using login_hint

### ISSUE THREAD

**Issue by annndddy** [AzureAD/microsoft-authentication-library-for-js#4970]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.24.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

Hi, im trying the msal by passing login hint abc@abcde.com
https://login.microsoftonline.com/xxxxxxxx/&login_hint=abc@abcde.com
but the login password page will show the azure account that associate with my login hint like 12345@abc.onmicrosoft.com

but if i enter abc@abcde.com at the login page, it can correctly show the account name i want at the password page

i would like to know how to set the password page show the account name as the login hint (abc@abcde.com) i set?

Thanks
![msal](https://user-images.githubusercontent.com/66762687/177236650-c0837ccf-1d4b-4757-9fc5-692e38803da3.PNG)

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by ghost** [comment]
This issue requires attention from the MSAL.js team and has not seen activity in **5 days**. @mpminayo please follow up.

**Comment by sameerag** [comment]
`login_hint` is the `upn` or `preferred_username` claim in the `idToken`, you can find the reference [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens).

Can you please clarify what you mean by:
>> but if i enter [abc@abcde.com](mailto:abc@abcde.com) at the login page, it can correctly show the account name i want at the password page

Where are you entering this? As the `username` in the `login` page?

**Comment by annndddy** [comment]
that mean i input like this
![msal1](https://user-images.githubusercontent.com/66762687/179648830-c4e3edea-d492-4bc5-8f9b-a376427c6d29.PNG)
after i click next it show like this
![msal2](https://user-images.githubusercontent.com/66762687/179648886-de311b22-7908-42a2-85e8-2cfcefb630f1.PNG)

you can see at the second picture the email abc@abcde.com show at the input password phase

but i use login_hint abc@abcde.com
in the input password phase show like this
![msal](https://user-images.githubusercontent.com/66762687/179649148-eabdb544-c784-46e8-9bb7-34ab27cc1d18.PNG)
what i want it to be is like this
![msal3](https://user-images.githubusercontent.com/66762687/179649171-99893347-c4da-470d-87f9-4c4fcaca39be.png)
because our company do not want the user able to see the onmicrosoft.com account name, which will make them confuse

i would like to know if there is a setting to config what user name show at the input password phase? in this case i want to set it as our domain email address/ user nickname not the onmicrosoft.com address, or is it something set in the azure ad user profile? thanks

**Comment by tnorling** [comment]
@annndddy Is this a guest user scenario? In other words, does abc@abcde.com belong to the tenant which you are trying to sign in or a different one?

**Comment by annndddy** [comment]
@tnorling this use case is from our company user
the user like this
{ 
username 12345@abc.onmicrosoft.com
email: abc@abcde.com
}
and we already set allow to login by email, and pass the email (abc@abcde.com) by the login_hint
in this case we input the password and the login is successful
but the problem is we don't want the username show to the user, because the username (@abc.onmicrosoft.com) is not used by the users, as you can see the domain and the first path is quite different 12345 vs abc, abc.onmicrosoft.com vs abcde.com
so we would like to know is there a setting to change to display label (12345@abc.onmicrosoft.com) at the login password page?
in this case we want to show the email which we pass to the login_hint not the username.
thanks

**Comment by tnorling** [comment]
@annndddy I believe it will always show username but this is not something that MSAL controls so I can't say for sure. If you'd like you can open a support ticket [here](https://azure.microsoft.com/en-us/support/create-ticket/) and they may be able to answer more definitively.
