### ISSUE TITLE
nextjs-sample fails on "name.split(" ")" for test users

### ISSUE THREAD

**Issue by jeroenheijmans** [AzureAD/microsoft-authentication-library-for-js#4994]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

^2.14.2

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

^1.0.0

### Description

Running the `nextjs-sample` from the repository results in an error after signing in with redirect flow.

### Error Message

Full error details, browser window:

```none
Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'split')

Source
.next\static\chunks\pages\_app.js (159:37) @ <unknown>

  157 | useEffect(() => {
  158 |     if (accounts.length > 0) {
> 159 |         setName(accounts[0].name.split(" ")[0]);
      |                                 ^
  160 |     } else {
  161 |         setName(null);
  162 |     }
```

Devtools console shows several errors from my session:

```none
createTheme.js:94 Material-UI: the createMuiTheme function was renamed to createTheme
ui.jsx:159 Uncaught TypeError: Cannot read properties of undefined (reading 'split')
react-dom.development.js:20085 The above error occurred in the <WelcomeName> component:
react-dom.development.js:67 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
```

### Msal Logs

The sample was run as is, providing no extra logs.

### MSAL Configuration

Default configuration from the repository itself, `git log -1` shows I'm on commit `a986a32d2bc9d9944130fefe08c9cf13b2817107`.

### Relevant Code Snippets

```javascript
`git clone` + `npm install` + `npm run dev`
```

### Reproduction Steps

Steps to reproduce:

1. Clone the repository
2. `cd microsoft-authentication-library-for-js\samples\msal-react-samples\nextjs-sample`
3. `npm install`
4. `npm run dev`
5. On Windows 10 open Chrome Incognito blocking third party cookies, open `localhost:3000`
6. Click "Login with Redirect"
7. Create new account using a tempmail setup (it asked for email, password, and a date of birth) and complete the captcha
8. Leave all consent values to default and continue
9. Get redirected back to the application

Outcome: NextJS error in the browser and the devtools 

### Expected Behavior

Expected: some rendered page from the sample.

### Identity Provider

Other

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by tnorling** [comment]
@jeroenheijmans Thanks for raising this, this is happening because the `idToken` issued by the service does not contain a `name` claim in your case. Either double check if additional configurations are needed by the service to return this claim or add a check that verifies `account[0].name` is defined before attempting to run `.split` on it. I'll update the sample to include this additional check.

**Comment by jeroenheijmans** [comment]
> I'll update the sample to include this additional check.

Cheers, thanks! That'd be great for future users of the sample! I had figured as much for the root cause, but it'll be great for others if the sample's robust against this out of the box.

Thanks for your replies, good luck with your endeavors!
