### ISSUE TITLE
TypeError: "listener" argument must be a function in passport-azure-ad 4.3.3

### ISSUE THREAD

**Issue by robins1212** [AzureAD/microsoft-authentication-library-for-js#4997]
### Core Library

Passport Azure AD (passport-azure-ad)

### Core Library Version

4.3.3

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

Azure Cloud Shell uses passport-azure-ad for token validation in our containers and after updating to version 4.3.3 token validation fails and the container crashes

### Error Message

[ERROR]  TypeError: "listener" argument must be a function
    at ClientRequest.once (events.js:340:11)
    at new ClientRequest (_http_client.js:174:10)
    at Object.request (http.js:39:10)
    at Object.request (https.js:245:15)
    at Metadata.fetch (/usr/cloudshell/node_modules/passport-azure-ad/lib/metadata.js:179:9)
    at memoryCache.wrap (/usr/cloudshell/node_modules/passport-azure-ad/lib/bearerstrategy.js:583:14)
    at /usr/cloudshell/node_modules/cache-manager/lib/caching.js:195:17
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)

### MSAL Configuration

```javascript
n/a msal configuration
```

### Relevant Code Snippets

```javascript
var validationOptions = {
  identityMetadata: "https://login.microsoftonline.com/common/.well-known/openid-configuration",
  clientID: "{CLOUDSHELLAPPID}",
  validateIssuer: false,
  audience: ["https://management.core.windows.net/", "https://management.core.windows.net"],
  passReqToCallback: false,
  loggingLevel: "info"
};

var bearerStrategy = new BearerStrategy(validationOptions,
  function (token, done) {
    process.nextTick(() => {
      return done(null, { oid: token.oid }, token);
    });
  }
);
```

### Reproduction Steps

n/a

### Expected Behavior

In previous versions, including 4.3.2 the token authentication has succeeded without error.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Regression

passport-azure-ad 4.3.2

### Source

Internal (Microsoft)

**Comment by sameerag** [comment]
cc @jo-arroyo 

@robins1212 We are not actively maintaining `passport-azure-ad`, and currently only doing security patches if needed. However we are working on a new library for `token validation` [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/node-token-validation), currently a work-in-progress.

Can you please track this for release and migrate to this library instead?

**Comment by Engelce** [comment]
Is there any solution? Thank you🙏 @jo-arroyo @sameerag
