### ISSUE TITLE
MSAL not returning control back to application after login failure

### ISSUE THREAD

**Issue by waykolep** [AzureAD/microsoft-authentication-library-for-js#5007]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.27.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.2

### Description

We are migrating from adal-> msal and using MSAL react npm package for the same.

A sample code usage -

```
<Router basename={process.env.TENANT_BASENAME}>
<MsalProvider instance={AuthenticationUtil.getMSALInstance()}>
 <MsalAuthenticationTemplate
   interactionType={InteractionType.Redirect}
   authenticationRequest={loginRequest}
    errorComponent={Error}
 >
  <Switch>  
   <Route path="/" component={component1}/>
   ...
   </Switch>
 </MsalAuthenticationTemplate>
</MsalProvider>
</Router>
```

For a happy use case where user has access, it works fine but for alternate use case where user does NOT have access, it gets stuck on the login screen that says, 'Trouble Signing you in'.

![image](https://user-images.githubusercontent.com/109254534/178860512-adbb8214-b1f6-4a30-b6eb-ae2b8c80590f.png)

Now this is valid scenario mentioned [here](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/error-code-aadsts50105-user-not-assigned-role) but then we would like to show the custom page or message when this 'access denied' scenario occurs. And the problem seems like the control is still at 'login.microsoft.com' page and not our calling application. I enabled verbose logging and it confirms msal:loginStart event is fired but not msal:loginFailure
![image](https://user-images.githubusercontent.com/109254534/178860524-78e6408e-39bd-4e8a-b269-e95e08074b58.png)

Is there a way to get back to our application/site after this scenario happens?

We want to show a custom page with instructions on how to get access and not this generic page.

I am passing `errorComponent in <MsalAuthenticationTemplate>`  but that doesn't seem to work for this.

### MSAL Configuration

```javascript
{
    auth: {
        clientId,
        authority: endpoint,
        postLogoutRedirectUri: process.env.POSTLOGOUTREDIRECTURI,
    },
    cache: {
        cacheLocation: process.env.CACHELOCATION,
    },
    system: {
        loggerOptions: {
            loggerCallback: (
                level: LogLevel,
                message: string,
                containsPii: boolean
            ): void => {
                if (containsPii) {
                    return;
                }
                switch (level) {
                    case LogLevel.Error:
                        console.error(message);
                        return;
                    case LogLevel.Info:
                        console.info(message);
                        return;
                    case LogLevel.Verbose:
                        console.debug(message);
                        return;
                    case LogLevel.Warning:
                        console.warn(message);
                        return;
                }
            },
            piiLoggingEnabled: false,
        },
        windowHashTimeout: 60000,
        iframeHashTimeout: 6000,
        loadFrameTimeout: 0,
        asyncPopups: false,
    },
};
```

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by sameerag** [comment]
@waykolep The service team does not relay this error back to MSAL and hence the application cannot be redirected or the error handled. I can check with them if this is a scenario they support.

**Comment by sameerag** [comment]
Service confirmed they cannot return the control to the app, these failures are displayed to the user to close the browser session and retry as needed.

MSAL JS has no control here.
