### ISSUE TITLE
B2C Redirect URLs change from login.microsof to b2clogin.com

### ISSUE THREAD

**Issue by MrsCD** [AzureAD/microsoft-authentication-library-for-js#5008]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.17.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.3

### Description

Hi, 
we are trying to change the URLs from login.microsoft to b2clogin.com in the Azure Portal and in our code itself. However it is absolutely not working at all. The problem is, the deadline Azure provided is 31. August and until now we were not able to fix this issue. 

So if anyone has an idea, how to make this work, please comment asap.
 

### Relevant Code Snippets

```javascript
This is how it looks like right now, without the change.
What was done is just changing the url to b2clogin.com

export const environment = {
  production: true,
  domain: 'https://test.test/portal/v1com',
  signalRUrl: '....',
  authorityDomain: 'login.microsoftonline.com/',
  api: {
    url: 'https://test.test/portal/v1',
    key: '.......'
  },
  authentication: {
    clientId: '...',
    redirectUri: 'https://test-test.testresult.com',
    authority:

  //this url how its supposed to be    'https://testenduserb2cdev.b2clogin.com/tfp/testenduserb2cdev.onmicrosoft.com/b2c_1_test_portal_signin/'
  },
  passwordReset: {
    authority:
 // this url how its not correct     'https://login.microsoftonline.com/tfptestalenduserb2cdev.onmicrosoft.com/b2c_1_testportalpasswordreset/'
  },
  changePassword: {
    authority:
 // this url how its not correct 'https://login.microsoftonline.com/tfp/testenduserb2cdev.onmicrosoft.com/b2c_1_testportalchangepassword'
  },
  appInsights: {
    instrumentationKey: ''
  },
  consentScopes: ['openid', 'profile']
};
```

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by derisen** [comment]
@MrsCD could you please provide more detail on what is not working? Can you share the error or faulty behavior, some code snippets for how you are initializing and using msal, as well as any reproduction steps? If you could fill out the issue form that would help to diagnose -thanks.

**Comment by MrsCD** [comment]
@derisen unfortunately I cant send you a code snippet. This is all I have. We tried again yesterday to change the URL. However it isnt working. We only see a blank screen when calling the web app. We spent so much time already, but we cant find a solution and the deadline is so near.
Is there a possibility to change the deadline for us? Even only 1 more month, so instead of Aug 31, 2022 to Oct 01, 2022?

**Comment by tnorling** [comment]
@MrsCD Unfortunately there's not enough information here to help you. I'm not aware of the deadline you're referring to and have no power to change it. My only suggestion is that you can file a [support ticket with B2C](https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options) and they may be better able to assist in this regard. If you have issues specific to MSAL.js I would be more than happy to help you, but I'll need a bit more detail.
