### ISSUE TITLE
After successful login and redirection, the execution of the routing guard is interrupted.

### ISSUE THREAD

**Issue by ChongZhiCZ** [AzureAD/microsoft-authentication-library-for-js#5011]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.26.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

HI,

I have a sign in page. When you visit the website without authentication, you will be redirected to this page.

When I click sign in to enter the login process and successfully authenticate and jump back to my website, there seems to be a problem with the routing guard, which makes me return to the sign in page.

I need to enter the home page after successful authentication. I don't know how to implement it.

But in fact, the login is successful. When I visit the website again, I can get the login user information. It seems that it is not waiting for the execution of `handleredirectpromise` at the routing guard.

The source code is here
[vue3-sample-app.zip](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/9122801/vue3-sample-app.zip)
.

### Source

External (Customer)

**Comment by tnorling** [comment]
@zico209 Can you please provide your configuration and your routing guard implementation so I can better assist you? Have you seen our Vue3 sample, which implements a routing Guard [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-browser-samples/vue3-sample-app/src/router/Guard.ts)?

**Comment by ChongZhiCZ** [comment]
> @zico209 Can you please provide your configuration and your routing guard implementation so I can better assist you? Have you seen our Vue3 sample, which implements a routing Guard [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-browser-samples/vue3-sample-app/src/router/Guard.ts)?

https://github.com/AzureAD/microsoft-authentication-library-for-js/files/9122801/vue3-sample-app.zip

This is my demo project modified on vue3 simple. All details are here.

**Comment by tnorling** [comment]
@zico209 Thanks! A couple things I noticed:

1. By default the library will redirect the user back to the page which started the login flow (in your case /signin) after hitting the specified `redirectUri`. Sounds like you don't want this behavior so to disable you can either set the `navigateToLoginRequestUrl` flag to false in your `auth` config (authConfig.ts -> msalConfig -> auth). Alternatively, you can set the `redirectStartPage` parameter on the login request (also located in authConfig.ts) to tell MSAL to redirect to any page you want after login is complete.
2. You are using the home route as your redirectUri and also configuring that route to use the Guard. This is not advisable. We recommend setting your redirectUri to a page which does not require the user to be authenticated, and then if needed, have that page redirect the user to where they need to be using the methods mentioned in point 1.

**Comment by ChongZhiCZ** [comment]
@tnorling Thank you! This is really helpful.
