### ISSUE TITLE
Can not back to application after successfully login via popup

### ISSUE THREAD

**Issue by 153011490** [AzureAD/microsoft-authentication-library-for-js#5013]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.3

### Description

Hi MS supp,

   Our application is using MSAL React to login, we are using `loginPopup ` interaction type. When we set `http://localhost:3000` as the redirect uri in our local machine, the login pop up can close itself and back to our application after successfully login. But we deployed our application to Production Envirnoment and set our website(`https://www.xxxx.com`) as the redirect uri, the popup will not close itself and navigate to our website. Our application is using React.js to develop and using webpack to build a whole JS file and then deploy to Weblogic. [Here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/174) is the simillar issue for your reference. 

Best Regards,
Eason

### MSAL Configuration

```javascript
auth: {
            clientId: config.appId,
            authority: config.authorityUri,
            redirectUri: 'https://www.xxxx.com'
        }

scopes: [
        'user.read',
        'mailboxsettings.read',
        'calendars.readwrite'
    ]
```

### Relevant Code Snippets

```javascript
const {instance} = useMsal()
instance.loginPopup({
            scopes: config.scopes,
            prompt: 'select_account'
        })
```

### Reproduction Steps

1. login via popup
2. popup doesn't close itself after successfully login

### Expected Behavior

popup close itself after successfully login

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge

### Source

External (Customer)

**Comment by tnorling** [comment]
@153011490 Can you please confirm the top frame application domain matches the popup window domain exactly? Are there any errors thrown or printed to the console?

**Comment by 153011490** [comment]
> @153011490 Can you please confirm the top frame application domain matches the popup window domain exactly? Are there any errors thrown or printed to the console?

Yes, the top frame application domain matches the popup window, the console doesn't show any errors. May we know if it is necessary to use NodeJS Server to deploy instead of using Weblogic Server to deploy? We are using webpack to build our application and then deploy output javascript files to Weblogic.

**Comment by tnorling** [comment]
@153011490 What you use to deploy shouldn't matter. Can you please provide a video or a link to your site showing the behavior? You may email it to me if you prefer.

**Comment by 153011490** [comment]
@tnorling Please refer the picture
![login popup window](https://user-images.githubusercontent.com/26665684/179873530-27727495-cc8d-4ba9-8261-e18582a936f5.png)
.

**Comment by tnorling** [comment]
@153011490 Please check that your router is not auto-redirecting the popup or removing the hash. We generally recommend using a blank page that does not contain any logic as your redirectUri page when using popups as your interaction type, both for improved performance and to avoid issues like this.

**Comment by 153011490** [comment]
@tnorling But in my local machine, using `http://localhost:3000` as both host and redirectUri is normal , the popup window will close itself after login

**Comment by tnorling** [comment]
@153011490 I can't tell you why localhost is behaving differently from your hosted app without a reproduction. I can, however, tell you what may cause this behavior more generally, which is what I explained above. Does the popup window still contain a hash in the url when it is left open?

**Comment by 153011490** [comment]
@tnorling Yes, your understanding is right, I have solved it, thanks~

**Comment by KristianMijares** [comment]
Hi, i'm having this exact same issue, i can login ok on localhost but when i deploy to a azure appservice i got into a login loop, the token url on popup dissapears on a second and got console error login browserautherror: user_cancelled: user cancelled the flow, try all recommendations and anything works msal-browser 2.37.1, msal-react: 1.5.8
