### ISSUE TITLE
Allow developers to use custom cache

### ISSUE THREAD

**Issue by Alino** [AzureAD/microsoft-authentication-library-for-js#5023]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

Not Applicable

### Description

As a developer I would like to be able to somehow hook into the caching mechanism of MSAL for browser so that I can write my own functions for retrieving data from cache and storing data to cache.

This would for example allow me to to use chrome.storage API in the chromium extension context.

This could probably be part of the cache config:
```javascript
    cache: {
        cacheLocation "custom",
        getItem(key): {
         // custom code to get item
        },
        setItem(key, value) {
         // custom code to set item
        },
        clear() {
         // custom code to clear storage
        }
    }
```
These functions could return a Promise. So MSAL should check for that.

### Source

External (Customer)

**Comment by tnorling** [comment]
@Alino Thanks for expressing your interest in this feature, it is one we have heard before and we do have an item in our backlog to add this. Closing this as duplicate, however, you can track any updates regarding prioritization in #1588. cc. @EmLauber
