### ISSUE TITLE
Redis Support

### ISSUE THREAD

**Issue by Jesse-Lucas1996** [AzureAD/microsoft-authentication-library-for-js#5027]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.4.1

### Wrapper Library

MSAL Node Extensions (@azure/msal-node-extensions)

### Wrapper Library Version

2.0

### Description

Hello!

I was hoping you could tell me when we could expect redis support for caching? I see it on the road map was just seeing if we had a date!

Thank you

### Source

External (Customer)

**Comment by tnorling** [comment]
@Jesse-Lucas1996 Have you seen our [redis sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/RedisTestApp)?
