### ISSUE TITLE
forcing re-authenticate with existing user session

### ISSUE THREAD

**Issue by himadrinath** [AzureAD/microsoft-authentication-library-for-js#503]
in my next js application after user signup and redirect to my app their are steps they have to complete for requirement after they complete those steps from my backend using azure ad graph api i am updating the user claims so i need to expire the session and force to re-authenticate with existing user session without any user input so i can extract those claims from new token. how can i re-authenticate user in this way?

**Comment by navyasric** [comment]
@himadrinath Is this still an issue for you? You can trigger a re-authentication prompt for the user by calling the loginRedirect() or loginPopup() methods. Closing this issue due to the issue being old. Please reopen if you still see a problem.
