### ISSUE TITLE
Teams Tab using msal-browser ssoSilent on Android Device

### ISSUE THREAD

**Issue by devszr** [AzureAD/microsoft-authentication-library-for-js#5030]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.27.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

We are using msal-browser in our Teams SSO tab to invoke backend APIs with SSO. The flow is as follows:

* User signs into Microsoft Teams
* User loads a Tab with our custom App
* The Tab uses msal-browser to get an access token for our Backend API which is secured by Azure AD.
* We make calls to the backend using this Token.

This Tab works fine in the following scenarios:

* Teams native app on Windows.
* Teams within the Web Browser on Windows.
* Teams native Android App within the Android Emulator "Pixel 2 API 28" (Android Pie) provided with the standard Android SDK.

However, the tab fails to get an access token when we use the Teams native Android App on a physical device running Android 9 (Pie). The error we see is below:

`InteractionRequiredAuthError: login_required: AADSTS50058: A silent sign-in request was sent but no user is signed in. The cookies used to represent the user's session were not sent in the request to Azure AD. This can happen if the user is using Internet Explorer or Edge, and the web app sending the silent sign-in request is in different IE security zone than the Azure AD endpoint (login.microsoftonline.com).`

Any idea what may be going on? Since the Tab works fine everywhere, including an Android Emulator, shouldn't we expect it work on the physical device as well?

Thanks.

### MSAL Configuration

```javascript
{
  auth:
    {
      clientId: "clientId",
      authority:"https://login.microsoftonline.com/<tenant_id>",
    },
  cache:
    {
       cacheLocation: "localStorage",
       storeAuthStateInCookie: "true"
    }
}
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by tnorling** [comment]
@devszr Can you share some code snippets of your usage? Can you also try to collect some logs from MSAL as well as the network? Thanks!

**Comment by devszr** [comment]
@tnorling Thank you for the quick response.

Unfortunately, the latest version of Teams on Android has a problem with displaying the Dev Tools Window from both a physical and emulator device. See this MicrosoftDocs/msteams-docs#6467. Due to this, I am unable to get logs from the Dev Tools console. 

I'll try to detail the code flow below:

We have a Blazor web app which is displayed as a Tab within Teams. This web app talks to one of the Azure Service APIs and for authentication with that API, we have been trying to use MSAL-Browser. The flow:

1) User logs on to Microsoft Teams on Desktop Teams, Web Teams or Android/IOS Teams.
2) User accesses the Tab. This Tab uses JSInterOp to invoke the following functions in order to get an Access Token for the Azure Service API and then makes calls to it using that Access Token from the backend:

*  `microsoftTeams.authentication.getAuthToken()` -> From the Teams JavaScript SDK

*  Validates the Token received from Step 1 to make sure it's from a valid issuer and has the correct intended audience.

* Performs  `MSAL.ssoSilent(tokenRequest)`

* Performs `MSAL.acquireTokenSilent()` -> With the request for an Access Token to the Azure Service API. 

The token received from Step 4 is then used to access the backed service API.

Interestingly, because of the DevTools problem with the latest version of Teams, I tried using Teams version 1416_1.0.0.2022263501 and that works fine. I even left the Emulator open the whole night and our Tab was successfully refreshing the token before expiry and working with no problems at all. Also, the version of Chrome WebView used for this test with the older Teams version is **103.0.5060.129** which is the latest version of Chrome.

I can get you MSAL logs from the older Teams version if that'll help you understand our flow better.

So, not sure if:

* The latest version of Teams is buggy, because SSO for the Tab works just fine on the Desktop Teams app and on Browser Teams?
* or, the way we are trying to get the Access Token is not correct and it's just working on the older version of Teams because that isn't enforcing something that prevents us from getting an Access Token.

**Comment by tnorling** [comment]
@devszr It sounds like this is a bug in the Teams app if it's working on an older version. I unfortunately can't provide more insight than that without logs. I would suggest raising this with Teams to find out what changed or if your usage in their environment can be improved.

**Comment by devszr** [comment]
Thanks @tnorling for a quick response once again. 

We did a few more tests and managed to get our Tab app using msal-browser working on the Teams desktop, web and Android clients.

What we found is, `MSAL.ssoSilent(tokenRequest)` fails on the first attempt for some reason on the teams Android client even though we have performed a ` microsoftTeams.authentication.getAuthToken()` before calling it within our Tab. Note that, this doesn't happen all the time on the older version of Teams on Android. Because of this, `MSAL.acquireTokenSilent()` fails with errors. Furthermore, Teams Android client cannot do a `MSAL.loginPopup()` because of browser/device restrictions and Teams Web client cannot do a `MSAL.loginRedirect()` due to its use of an iframe. Therefore, what we finally ended up doing is something like the below snippet (Note that the code sample below is not complete, but just describing our flow):

```
try{
   MSAL.ssoSilent(..);
}catch(error){
  try{
      await MSAL.loginRedirect();
   }catch(error){
      try{
          await MSAL.loginPopup(..);
       }catch(error){
       }// end of loginpopup catch
   }// end of loginredirect catch
}// end ssosilent catch
```

That way, we are able to handle all the clients and get our AccessToken for the remote Azure service. Not sure if there is a better way to use MSAL-Browser for SSO directly within Teams, especially if using Blazor, but this method seems to work in all our tests so far. Please do let me know if you think there is a better way or if we are doing something incorrectly.

**Comment by tnorling** [comment]
@devszr This does make sense, silent calls are not guaranteed to succeed and you should always implement fallback logic to an interactive API as you've done here. What you've shown here works, you could further optimize by selectively calling redirect or popup based on the environment rather than potentially calling both but that's ultimately up to you, it shouldn't affect MSAL's behavior.

**Comment by devszr** [comment]
Sounds good. I am not sure we are able to know if we are inside the Teams web, desktop or mobile clients from within JavaScript, so until we have a way to figure out the environment we are working in, I guess we'll have to continue with this try/catch approach.

Thank you for all the assistance. I will close this issue.
