### ISSUE TITLE
msal.loginPopup fails to login when user has permissions w/o error message

### ISSUE THREAD

**Issue by ghost** [AzureAD/microsoft-authentication-library-for-js#5031]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

^2.23.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

^1.3.2

### Description

Two issues:
1. msal.loginPopup fails to login when user has permissions w/o error message

What we saw:
1. open the website in Chrome or Edge
2. Click Login button
4. sign in with popup dialog (msal.loginPopup())
5. page gets refreshed
6. useIsAuthenticated is still false
7. Repeated attempts results in the same issue

This issue has become more serious recently. 

### Error Message

We do not see an exception or error returned.  That's the pain point.

### Msal Logs

No logs available. 

### MSAL Configuration

```javascript
{
	auth: 
	{
		"Instance": "https://login.microsoftonline.com/",
    		"TenantId": null,
   		 "ClientId": null,
    		"ClientSecret": null,
    		"CallbackPath": "/signin-oidc"
	}
	cache: {
		cacheLocation: "localStorage"
	}
}
```

### Relevant Code Snippets

```javascript
Block 1:
<Button color='secondary' size='sm' onClick={() => msal.loginPopup()}>
    Login
</Button>

Block 2:
const [isLoading, setLoading] = useState(false)
const isAuthenticated = useIsAuthenticated()
const setData = data => {
  localStorage.setItem('Authorization', `Bearer ${data?.accessToken}`)
}

useEffect(() => {
        if (isAuthenticated && !localStorage.Authorization && !isLoading && inProgress === InteractionStatus.None) {
            setLoading(true)
            msal
                .acquireTokenSilent({
                    scopes: ['api://' + localStorage.ClientId + '/User.Read'],
                    account: account
                })
                .then(res => setData(res))
                .catch(error => {
                    showError(error)
                })
                .finally(() => setLoading(false))
        }
    }, [isLoading, isAuthenticated, account, msal, inProgress])
```

### Reproduction Steps

1. Try to login with msal.loginPopup().
2. Check whether token is saved in browser.
3. Run useIsAuthenticated see if it returns true when there is token issued.

### Expected Behavior

Successful login when the user has permissions or return some error message so we can know what happened.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
@momoliu-msft What do you mean when you say "page gets refreshed"? Are you referring to the main tab or the popup window? Refreshing the page during a sign in will abort the flow, you should debug to see why this is happening.

**Comment by ghost** [comment]
Hey, I mean the page gets redirected as expected after the msal.loginPopup(). We do not interrupt the login process.

**Comment by ghost** [comment]
then if we check useIsAuthenticated, it is still false.

**Comment by tnorling** [comment]
@momoliu-msft I'm not sure I understand. MSAL does not redirect the main page when using popups, is this something your app is doing specifically?

**Comment by ghost** [comment]
Let's forget the redirect. What I see is that, after msal.loginPopup(), useIsAuthenticated is still false and we do not have any exception/error returned. 
Rarely see it when using Edge, but a lot when using Chrome.

**Comment by tnorling** [comment]
@momoliu-msft The redirect here is important because if an error occurs it will be lost when the page changes. The only reasons `isAuthenticated` would be false is if there is no user signed in or there isn't an `MsalProvider` component rendered above. Since you say it works in Edge it means it's likely the former and is likely due to an error. If an error occurs during login you will need to capture it either in a `.catch` hanging off the `loginPopup` call or by registering an event listener, and both need to happen in the same page context that made the call.

**Comment by ghost** [comment]
Thanks for the explanation. We see this intermittently on both Edge and Chrome. (Just less frequent with Edge) 

Let's say that the endpoint is https://abcd.azurewebsites.net, user account is xyz@microsoft.com.  

When the user visits the page, they see the login button, click it, then a window pops up, user chooses the account they want to use, which is xyz@microsoft.com, the popped-up windows gets loading, then 
if lucky, the popped-up window gets closed, and user can see the content on abcd.azurewebsites.net that they can only see when authenticated and authorized. 
If not lucky, the popped-up window still shows up, and the interesting thing is that it loads duplicate content of https://abcde.azurewebsites.net (the content people see when not signed in yet), please see the attachment.

**Comment by tnorling** [comment]
@momoliu-msft Ah ok. This happens because there's a race condition between your application's router and MSAL.js attempting to retrieve the response from the popup (which is returned in the hash of the url). You need to ensure that your router is not redirecting the page or removing the hash inside the popup (most commonly people configure some sort of static route which results in the hash disappearing). Our general recommendation for popups is to set your redirectUri to a blank page which does not contain any logic. This helps prevent issues like this and gives you some small performance gains.

**Comment by ghost** [comment]
By setting redirectUri to a blank page, shall I expect that every time signing in, it will get redirected to that blank page? Or am I missing something here? Can I have an example?

**Comment by tnorling** [comment]
@momoliu-msft Only the popup window gets redirected to your redirectUri and ideally that popup should get closed before the user has even noticed

**Comment by ghost** [comment]
Something like this?

msalInstance.loginPopup({
    redirectUri: "http://localhost:3000/blank.html"
});

**Comment by ghost** [comment]
Looks like we still have this issue after adding blank page redirect. Any other thoughts?

**Comment by tnorling** [comment]
@momoliu-msft Please confirm your blank page is not subject to your router. Does the url of the popup window contain a hash?

**Comment by ghost** [comment]
That's a good point. I made it work in local environment where the blank page not subject to the router. 

I am wondering what address of the blank page we could use when the website in in the cloud.

**Comment by tnorling** [comment]
@momoliu-msft You should be able to serve up static assets. Alternatively, you can ensure that your router preserves the hash while routing. The issue isn't so much the presence of the router and more so that it is indeterminately redirecting to a static route which ends up removing the hash.
