### ISSUE TITLE
Inquiry for token retrieval failure using first party application with MSALV1

### ISSUE THREAD

**Issue by KeviCheng** [AzureAD/microsoft-authentication-library-for-js#5037]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

2.18.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

n/a

### Description

I am making a call to get token using my first party application for some new feature work, but an encountering a time out. Could someone please help me lookt into the logs to see whats going on?

request url:
Request URL: https://login.microsoftonline.com/3c79fde3-e9cf-4819-b103-e11991afbd37/oauth2/v2.0/authorize?response_type=id_token%20token&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default%20openid%20profile&client_id=e29b5c86-b9ab-4a86-9a20-d10842007599&redirect_uri=https%3A%2F%2Ftesta190720221053-admin.sharepoint.com%2F_forms%2Fspfxsinglesignon.aspx&state=eyJpZCI6IjM1ZjRlYzYwLTM5YmYtNGJjMC1iZjNkLTYzZmIyZWNjNWQ4NCIsInRzIjoxNjU4NDI4MDI4LCJtZXRob2QiOiJzaWxlbnRJbnRlcmFjdGlvbiJ9&nonce=d6e4c30e-0a74-4a15-8b2c-901339c2111f&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=1.4.12&sid=08393b96-e3a2-4df5-b8e1-a96acb5eb10d&client-request-id=a89090bf-caaf-4fc3-8052-c1595e116ce9&prompt=none&response_mode=fragment

response headers:
x-ms-request-id: 083ec020-2080-434c-a2dc-6b4e37493c01
Thu, 21 Jul 2022 18:27:08 GMT

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
Resolved offline. App registration was not configured for implicit grant
