### ISSUE TITLE
Seamless SSO with Azure AD

### ISSUE THREAD

**Issue by khanhnguyen3759** [AzureAD/microsoft-authentication-library-for-js#5041]
### Core Library

MSAL Node (@azure/msal-node)

### Wrapper Library

MSAL Node Extensions (@azure/msal-node-extensions)

### Description

Hello guys,

I working on a feature request for Seamless SSO https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-sso-how-it-works

Could electron apply this topic? https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-sso-how-it-works#how-does-sign-in-on-a-native-client-with-seamless-sso-work

1. The user tries to access a native application (for example, the Outlook client) from a domain-joined corporate device inside your corporate network.
2. If the user is not already signed in, the native application retrieves the username of the user from the device's Windows session.
===
How does **step 2** work?

### Source

Internal (Microsoft)

**Comment by ellymakuba** [comment]
Please clarify what you want to achieve. Seamless SSO feature in windows is enabled by admins and is out of the control of the MSAL SDK.

**Comment by khanhnguyen3759** [comment]
@ellymakuba  so how electron can do this feature without msal sdk?

**Comment by khanhnguyen3759** [comment]
Any limitation here with electron to do this feature if any sir? Could you explain?

**Comment by ellymakuba** [comment]
Msal-node doesn't support token retrieval from WAM today, but we will in the future. So, you cannot do seamless SSO with electron alone.

**Comment by khanhnguyen3759** [comment]
How electron app like Microsoft Teams can work without MSAL ?
Could you explain @ellymakuba ? Does it related to backend ?

**Comment by EmLauber** [comment]
The Microsoft Teams electron app uses a different internal library. The MSAL.js team is not involved in the Seamless SSO feature, and looks like you already asked the question for the team I would redirect you to: https://github.com/electron/electron/issues/35066. Closing this for the MSAL.js team.

**Comment by lexxizz** [comment]
@EmLauber could you please help us to find some examples of integrations of Seamless SSO for the native applications? It could not be related to electron. Could be written on any language. We just need to find sequence of actions which we need to do. Thanks in advance

**Comment by EmLauber** [comment]
The Quickstart for the feature is an example you can walk through: https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-sso-quick-start. If that doesn't help, I recommend the FAQ or Troubleshooting references linked at the bottom of that page.

**Comment by khanhnguyen3759** [comment]
@EmLauber of course we already config everything in that page. We try to open electron in a joined domain computer but still require password everytime

**Comment by lexxizz** [comment]
@EmLauber Could you please share any libraries which could be used for integration [Password hash synchronization (PHS)](https://docs.microsoft.com/en-us/azure/active-directory/hybrid/whatis-phs) or [Pass-through authentication (PTA)](https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-pta)
