### ISSUE TITLE
 AADSTS50148: The code_verifier does not match the code_challenge supplied in the authorization request for PKCE

### ISSUE THREAD

**Issue by cssuh** [AzureAD/microsoft-authentication-library-for-js#5044]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.9.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

After fetching the auth code, I try calling `acquireTokenByCode` and it gives me this error:

`'50148 - [2022-07-27 18:16:02Z]: AADSTS50148: The code_verifier does not match the code_challenge supplied in the authorization request for PKCE.\r\nTrace ID: bd3a506f-4758-4794-851f-e8f7714cc900\r\nCorrelation ID: 8411037a-8e3f-4492-bc7f-d5cbce99389d\r\nTimestamp: 2022-07-27 18:16:02Z - Correlation ID: 8411037a-8e3f-4492-bc7f-d5cbce99389d - Trace ID: bd3a506f-4758-4794-851f-e8f7714cc900'`

Can someone help me with this issue? I'm generating the code_verifier and code_challenge using the CryptoProvider in MSAL-node with the `generatePkceCodes`, so I'm not sure why this is happening.

### MSAL Configuration

```javascript
const MSAL_CONFIG = {
	auth: {
		clientId: ,
		redirect_uri: https://vscode-redirect.azurewebsites.net/
	}
};
```

### Relevant Code Snippets

```javascript
serverPort = await this.server.startup();
await this.createCryptoValues();
const state = `${serverPort},${this.pkceCodes.nonce}`;

authUrlRequest = {
	scopes: this.scopes,
	redirectUri: this.redirectUri,
	codeChallenge: this.pkceCodes.challenge,
	codeChallengeMethod: this.pkceCodes.challengeMethod,
	prompt: 'select_account',
	state: state
};
let authCodeUrl = await this.clientApplication.getAuthCodeUrl(authUrlRequest);

private async createCryptoValues(): Promise<void> {
	this.pkceCodes.nonce = this.cryptoProvider.createNewGuid();
	const { verifier, challenge } = await this.cryptoProvider.generatePkceCodes();
    	this.pkceCodes.verifier = verifier;
    	this.pkceCodes.challenge = challenge;
}

authCodeRequest = {
	scopes: this.scopes,
	redirectUri: this.redirectUri,
	code: '' (this gets filled in after we request the auth code)
};

let result = await this.clientApplication.acquireTokenByCode(authCodeRequest);
```

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by derisen** [comment]
@cssuh can you also share the code snippet where you call the `acquireTokenByCode` API? Also, is this a public client or confidential client app?

**Comment by cssuh** [comment]
public client - I am working on the MSAL implementation for ADS
I updated the code snippets, please let me know if there is any other info you need.

**Comment by derisen** [comment]
@cssuh ah, it seems you're not passing the code verifier to the `acquireTokenByCode`. Your request object should look something like:

```javascript
authCodeRequest = {
	scopes: this.scopes,
	redirectUri: this.redirectUri,
        codeVerifier: this.pkceCodes.verifier
	code: '' (this gets filled in after we request the auth code)
};

let result = await this.clientApplication.acquireTokenByCode(authCodeRequest);
```

**Comment by cssuh** [comment]
@derisen that worked, thank you so much!
