### ISSUE TITLE
How to pass additional Headers to msal-node HttpClient

### ISSUE THREAD

**Issue by keki007** [AzureAD/microsoft-authentication-library-for-js#5050]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

latest

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

I need to add some custom Headers to the HTTP requests made by the msal-node.

The reason for this is that I'm trying to implement the Authorization code with PKCE flow in Node and it only works if I add the Origin header (normally the browser would add this but it's not the case in Node)

Can you provide some guidance on how to do this? 

Is it possible to extend the default HttpClient and override the methods to add in the additional headers and then set this as the networkClient in msalConfig.system.networkClient

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by sameerag** [comment]
@kevinkilroy  Yes it is possible to override the default `HttpClient` implementation in `msal-node`. While configuring the app, a user can initialize it with an instance of [`INetworkModule`](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/src/network/INetworkModule.ts) to do this.

**Comment by keki007** [comment]
Yes I know I can do that, I was more thinking of extending the current implementation rather than replace it. Something like:

```
MyHttpClient extends HttpClient {
//Override existing functions
async sendGetRequestAsync(url, options) {
// Add additional headers to options and call existing function
super.sendGetRequestAsync(url, options);
}
}
```

But I couldn't find a way of importing the existing HttpClient. Is it possible?

Thanks,

Kevin.

**Comment by jasonnutter** [comment]
> The reason for this is that I'm trying to implement the Authorization code with PKCE flow in Node and it only works if I add the Origin header (normally the browser would add this but it's not the case in Node)

Can you please clarify why you want to do this? The Auth Code Flow w/ PKCE for SPAs (i.e. CORS) requires the origin header (i.e. the flow used by MSAL.js), but you can still use the Auth Code Flow w/ PKCE without CORS. See this sample for more: https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/auth-code-pkce

**Comment by keki007** [comment]
I tried that sample but on the 2nd leg (handling the callback from Microsoft IDP and requesting a token) I was get the following exception:


```
Msal Node Auth Code Sample app listening on port 3000!
[Tue, 02 Aug 2022 01:26:38 GMT] : @azure/msal-node@1.12.0 : Info - getAuthCodeUrl called
[Tue, 02 Aug 2022 01:26:38 GMT] : @azure/msal-node@1.12.0 : Verbose - initializeRequestScopes called
[Tue, 02 Aug 2022 01:26:38 GMT] : [aa857391-dd7b-48ba-bcc0-35cbf9f7b77a] : @azure/msal-node@1.12.0 : Verbose - buildOauthClientConfiguration called
[Tue, 02 Aug 2022 01:26:38 GMT] : [aa857391-dd7b-48ba-bcc0-35cbf9f7b77a] : @azure/msal-node@1.12.0 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/<TENANT_ID_REDACTED>
[Tue, 02 Aug 2022 01:26:38 GMT] : [aa857391-dd7b-48ba-bcc0-35cbf9f7b77a] : @azure/msal-node@1.12.0 : Verbose - createAuthority called
[Tue, 02 Aug 2022 01:26:38 GMT] : [aa857391-dd7b-48ba-bcc0-35cbf9f7b77a] : @azure/msal-node@1.12.0 : Verbose - Auth code client created
[Tue, 02 Aug 2022 01:26:49 GMT] : @azure/msal-node@1.12.0 : Info - acquireTokenByCode called
[Tue, 02 Aug 2022 01:26:49 GMT] : @azure/msal-node@1.12.0 : Verbose - initializeRequestScopes called
[Tue, 02 Aug 2022 01:26:52 GMT] : [418edea0-ce66-4a6a-8a4b-c9405eea72ea] : @azure/msal-node@1.12.0 : Verbose - buildOauthClientConfiguration called
[Tue, 02 Aug 2022 01:26:52 GMT] : [418edea0-ce66-4a6a-8a4b-c9405eea72ea] : @azure/msal-node@1.12.0 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/<TENANT_ID_REDACTED>
[Tue, 02 Aug 2022 01:26:52 GMT] : [418edea0-ce66-4a6a-8a4b-c9405eea72ea] : @azure/msal-node@1.12.0 : Verbose - createAuthority called
[Tue, 02 Aug 2022 01:26:54 GMT] : [418edea0-ce66-4a6a-8a4b-c9405eea72ea] : @azure/msal-node@1.12.0 : Verbose - Auth code client created
[Tue, 02 Aug 2022 01:26:55 GMT] : [418edea0-ce66-4a6a-8a4b-c9405eea72ea] : @azure/msal-common@7.2.0 : Info - in acquireToken call
ClientAuthError: network_error: Network request failed. Please check network trace to determine root cause. | Fetch client threw: Error: HTTP status code 400 | Attempted to reach: https://login.microsoftonline.com/<TENANT_ID_REDACTED>/oauth2/v2.0/token
    at ClientAuthError.AuthError [as constructor] (/home/kevin/projects/microsoft-authentication-library-for-js/lib/msal-common/dist/index.cjs.js:496:24)
    at new ClientAuthError (/home/kevin/projects/microsoft-authentication-library-for-js/lib/msal-common/dist/index.cjs.js:790:28)
    at Function.ClientAuthError.createNetworkError (/home/kevin/projects/microsoft-authentication-library-for-js/lib/msal-common/dist/index.cjs.js:833:16)
    at NetworkManager.<anonymous> (/home/kevin/projects/microsoft-authentication-library-for-js/lib/msal-common/dist/index.cjs.js:3406:51)
    at step (/home/kevin/projects/microsoft-authentication-library-for-js/lib/msal-common/dist/index.cjs.js:79:23)
    at Object.throw (/home/kevin/projects/microsoft-authentication-library-for-js/lib/msal-common/dist/index.cjs.js:60:53)
    at rejected (/home/kevin/projects/microsoft-authentication-library-for-js/lib/msal-common/dist/index.cjs.js:51:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errorCode: 'network_error',
  errorMessage: 'Network request failed. Please check network trace to determine root cause. | Fetch client threw: Error: HTTP status code 400 | Attempted to reach: https://login.microsoftonline.com/<TENANT_ID_REDACTED>/oauth2/v2.0/token',
  subError: ''
```

I then stepped through the code and saw that another exception was occurring which was being swallowed/lost:

`"{\"error\":\"invalid_request\",\"error_description\":\"AADSTS9002327: Tokens issued for the 'Single-Page Application' client-type may only be redeemed via cross-origin requests.\\r\\nTrace ID: 7c5df8ca-373a-4979-b8af-632349e39500\\r\\nCorrelation ID: d7debd4c-71e8-4ee3-b530-7dc8ee020f4f\\r\\nTimestamp: 2022-08-02 01:26:58Z\",\"error_codes\":[9002327],\"timestamp\":\"2022-08-02 01:26:58Z\",\"trace_id\":\"7c5df8ca-373a-4979-b8af-632349e39500\",\"correlation_id\":\"d7debd4c-71e8-4ee3-b530-7dc8ee020f4f\"}"`

Googling for this error resulted in this:

https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2482

Where they mention adding the Origin header. I added the Origin header using the debugger and then the call succeeded and the Token was returned.

**Comment by jasonnutter** [comment]
@kevinkilroy This likely means the redirect URI you are using for the flow is registered as a "spa" redirect URI, which should only be used for redirect URIs needed for MSAL.js (not MSAL Node). Can you try changing the redirect URI to be of type "Web"?

**Comment by keki007** [comment]
That's what I thought. If I do that I now need to setup a client secret which was something I was trying to avoid (since they need to be rotated)

**Comment by jasonnutter** [comment]
@kevinkilroy The sample linked above demonstrates how to use MSAL Node to do the Auth Code Flow as a public client (i.e. without a client secret).

**Comment by keki007** [comment]
@jasonnutter I was getting an exception saying client_secret or client_assertion must be present in the body. I finally got it to work when switching the redirect URL from Web to Public (mobile/desktop) in the App registration in Azure portal. Thanks for your assistance.
