### ISSUE TITLE
idToken can't be retrieved from cache

### ISSUE THREAD

**Issue by easingthemes** [AzureAD/microsoft-authentication-library-for-js#5053]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.21.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

`acquireTokenSilent` method can be used only for accessToken.
It should also be available for idToken.

My app is using only idToken, accessToken is always empty.

Currently there is no way to get idToken from cache, with the same nice flow as it exist for accessToken.

`msal.acquireTokenSilent({ forceRefresh: false, etc })` will always trigger network call.

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/master/lib/msal-common/src/client/SilentFlowClient.ts#L68

Is there any configuration where we can set which token is main, eg { authToken: 'idToken'; //  default 'accessToken' }.

Thanks.

### MSAL Configuration

```javascript
auth: {
    clientId: config.clientId,
    authority: config.authority,
    knownAuthorities: config.knownAuthorities,
    redirectUri: config.loginRedirectUrl,
    postLogoutRedirectUri: config.logoutRedirectUrl
  },
  cache: {
    cacheLocation: CONSTANTS.localStorage,
    storeAuthStateInCookie: false
  }
```

### Relevant Code Snippets

```javascript
It's clear from the source code that network call is always required, since `!cacheRecord.accessToken` is true:


       if (request.forceRefresh) {
            // Must refresh due to present force_refresh flag.
            this.serverTelemetryManager?.setCacheOutcome(CacheOutcome.FORCE_REFRESH);
            throw ClientAuthError.createRefreshRequiredError();
        } else if (!cacheRecord.accessToken) {
            // Must refresh due to non-existent access_token.
            this.serverTelemetryManager?.setCacheOutcome(CacheOutcome.NO_CACHED_ACCESS_TOKEN);
            throw ClientAuthError.createRefreshRequiredError();
        }
```
```


### Reproduction Steps

1. check Relevant Code Snippets

### Expected Behavior

acquireTokenSilent should work for idToken if accessToken is empty.
There should be some configuration to mark main authToken.

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer

### Regression

_No response_

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@easingthemes The ID token should always be returned from `acquireTokenSilent`. However, the ID token is currently not returned in the `AccountInfo` objects returned from the `getAccount*` APIs, which will be addressed in #5036

**Comment by easingthemes** [comment]
Thanks @jasonnutter, I've checked now deeper and indeed idToken should be retrieved from cache, just naming is confusing.
Method `readAccessTokenFromCache` is not referring to `accessToken` only, but other tokens also, depending on the type.
```
            switch (credType) {
                case CredentialType.ID_TOKEN:
                    matchingCredentials.idTokens[cacheKey] = entity as IdTokenEntity;
                    break;
                case CredentialType.ACCESS_TOKEN:
                case CredentialType.ACCESS_TOKEN_WITH_AUTH_SCHEME:
                    matchingCredentials.accessTokens[cacheKey] = entity as AccessTokenEntity;
                    break;
                case CredentialType.REFRESH_TOKEN:
                    matchingCredentials.refreshTokens[cacheKey] = entity as RefreshTokenEntity;
                    break;
            }
```
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/master/lib/msal-common/src/cache/CacheManager.ts#L421

Thanks for the explanation and the fix.

**Comment by jasonnutter** [comment]
@easingthemes Correct. In v2, acquireToken/login/ssoSilent APIs will always return both an ID token and an access token.
