### ISSUE TITLE
"Split is not a function" error

### ISSUE THREAD

**Issue by CRidge** [AzureAD/microsoft-authentication-library-for-js#507]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version 71
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
@azure/msal-angular 0.1.2

</code></pre>

## Current behavior
We have had several different behaviors where our Angular app, using @azure/msal-angular, crashes inside msal.service.ts with the following error message:

<pre>
Uncaught (in promise): TypeError: error.split is not a function
</pre>

Our application is rather complex: It needs to work offline, and has a service worker to enable it to function as a PWA. Most of our issues have come when network conditions were poor.

The core issue seems to be situations where errors arise which don't give errors with the expected "something|something" format. An example of code which causes the issue in question in msal.service.ts:

<pre><code>
    public acquireTokenSilent(scopes: Array<string>, authority?: string, user?: User, extraQueryParameters?: string): Promise<any> {
        return new Promise((resolve, reject) => {
            super.acquireTokenSilent(scopes, authority, user, extraQueryParameters).then((token: any) => {
                this._renewActive = false;
                var authenticationResult = new AuthenticationResult(token);
                this.broadcastService.broadcast('msal:acquireTokenSuccess', authenticationResult);
                resolve(token);
            }, (error: any) => {
                var errorParts = error.split('|');
                var msalError = new MSALError(errorParts[0], errorParts[1]);
                this._renewActive = false;
                this.broadcastService.broadcast('msal:acquireTokenFailure', msalError);
                this._logger.error('Error when acquiring token for scopes: ' + scopes + " " + error);
                reject(error);
            })
        });
    }
</code></pre>

Here the "error.split" doesn't account for errors not having the expected format. In one case the XhrClient fails a call (during DiscoverEndpoints, if the client has gone offline), and the following error handling simply sets the status (which is a number, not a string) as the error:

<pre><code>
      xhr.onerror = (ev) => {
        reject(xhr.status);
      };
</code></pre>

Number doesn't have a split function, and the first error handling itself throws an error, causing our code to fail unrecoverably. The required/expected "reject(error)" is never called.

## Expected behavior

What ever may fail internally, reject(error) should be called with some sort of sensible data, enabling us to recover.

## Minimal reproduction of the problem with instructions

I haven't been able to create a simple repo of this issue, but I hope it's fairly clear that the error handling in the code above isn't robust enough.

We've fixed some issues in the past (which where bugs in our code) which showed the exact same error, but for different reasons. These were hard to figure out, as the real error got lost.

**Comment by suhailsalim** [comment]
Is a fix coming anytime soon ?

**Comment by sameerag** [comment]
@CRidge @suhailsalim Apologies for the delay in responding to this issue. We recently revamped our msal js core library to have a better error interface, please check our documentation for [Error Handling](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL.js-1.0.0-api-release#error-handling-in-msaljs). I believe this will solve your issue to handle error cases better. 

However there is a catch regarding our Angular wrapper, we are still fleshing out the plan to upgrade it to be in sync with the core msal 1.0.x. This is being tracked with #786 and will be updated as we progress in our [roadmap](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#roadmap).

Closing this to be tracked with #786.
