### ISSUE TITLE
Profile edit flow without sing-out

### ISSUE THREAD

**Issue by mmuszalski** [AzureAD/microsoft-authentication-library-for-js#5081]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

In the example [you pointed](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/3742#issuecomment-859186227) to edit profile flow is just sign-in flow actually there is even this sentence: 

> Like password reset, edit profile user-flow requires users to sign-out and sign-in again

My question would be, is it possible to edit profile without signing out. It seems to me, when I do such request with loginPopup method and successfully change profile data, in return I get two accounts with two homeAccountIds (..**.b2c_1a_profileedit**... and ...**b2c_1a_signup_signin**...). Only the first one has updated data and unless I sign-out, using the b2c_1a_signup_signin will always use old data. Should I set b2c_1a_profileedit as the acctiveAccount and use only that until logout or shall I somehow merge data from it to the b2c_1a_signup_signin account.

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@mmuszalski Looks like we will have an updated sample that demonstrates how to do this. See #5015 for more information.

**Comment by peterzenz** [comment]
@derisen assigning to you to resolve once your PR is complete.
