### ISSUE TITLE
acquireTokenSilent using RefreshTokenClient fails to include redirectUri in the payload

### ISSUE THREAD

**Issue by manio143** [AzureAD/microsoft-authentication-library-for-js#5083]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.28.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

When acquiring a token using a refresh token in cross origin scenarios, such as requesting a token from another authority (i.e. another tenant) than the user has logged into, but in which they exist as a guest, AAD requires a redirectUri to be present in the payload (which is configured as SPA in app's registration) or using a client assertion. At the moment `RefreshTokenClient` is not adding redirectUri to the payload even if it's explicitly set on the token request when calling `acquireTokenSilent`.

This would require changes to the msal-common's `CommonRefreshTokenRequest` to accommodate the redirectUri in the request type and in the `RefreshTokenClient` [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/src/client/RefreshTokenClient.ts#L188) where you'd append it to the builder using `addRedirectUri(...)` if it's set on the request.

### MSAL Configuration

```javascript
{
  auth:
  {
    clientId: "client-id",
    authority: "https://login.microsoftonline.com/consumers/"
  }
}
```

### Relevant Code Snippets

```javascript
const myMsal = new msal.PublicClientApplication(msalConfig);
await myMsal.loginPopup()
const request = {
  scopes: ["api://.../.default"],
  authority: "https://login.microsoftonline.com/{tenantId}/",
  redirectUri: "https://my-app.net/"
};
await myMsal.acquireTokenSilent(request);
```

### Reproduction Steps

1. Log in to authority A (e.g. MSA)
2. Get a token in authority A and a refresh token
3. Get a token in authority B (e.g. AAD tenant where user is a guest) using A's refresh token and specify `redirectUri` in the request.
4. Request to AAD is missing `redirect_uri` in the payload

### Expected Behavior

`redirect_uri` should be included in the payload

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer, Other

### Source

Internal (Microsoft)

**Comment by jasonnutter** [comment]
@manio143 Thanks, I'll investigate if this is intended behavior by the server.

**Comment by manio143** [comment]
The issue is being discussed internally.

**Comment by manio143** [comment]
The issue has been fixed in the token issuing service, no changes to MSAL.js are required.
