### ISSUE TITLE
MsalAuthenticationTemplate causes redirect loop when refresh token expires

### ISSUE THREAD

**Issue by h3rmanj** [AzureAD/microsoft-authentication-library-for-js#5089]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.28.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.4

### Description

`MsalAuthenticationTemplate` seems to cause a redirect loop when a tab is left open long enough for the refresh token to expire.

### Error Message

By looking at the network calls, i see this pattern;
![image](https://user-images.githubusercontent.com/11387548/183598023-c13c44e8-4480-40c7-a9cf-6559f1f74bbc.png)

- 2 token POST requests, which fails with this error

```
"AADSTS700084: The refresh token was issued to a single page app (SPA), and therefore has a fixed, limited lifetime of 1.00:00:00, which cannot be extended. It is now expired and a new sign in request must be sent by the SPA to the sign in page. The token was issued on 2022-08-08T07:07:56.0747046Z.\r\nTrace ID: b207e2d4-c9c3-4049-a4d5-3694ef474e00\r\nCorrelation ID: adfb57f2-e2ee-43fe-94a1-8945ea5b782e\r\nTimestamp: 2022-08-09 07:46:00Z"
```

- A silent sign-in request is made (subdocument requests), which redirects back with this error

```
[#error=login_required&error_description=AADSTS50058%3a+A+silent+sign-in+request+was+sent+but+no+user+is+signed+in.%0d%0aTrace+ID%3a+0df1e86c-cba3-4506-8025-554c38d94400%0d%0aCorrelation+ID%3a+f1732dbf-804e-4f0a-808f-90fc490e8b85%0d%0aTimestamp%3a+2022-08-09+07%3a45%3a59Z&error_uri=https%3a%2f%2flogin.microsoftonline.com%2ferror%3fcode%3d50058&state=...#error=login_required&error_description=AADSTS50058%3a+A+silent+sign-in+request+was+sent+but+no+user+is+signed+in.%0d%0aTrace+ID%3a+0df1e86c-cba3-4506-8025-554c38d94400%0d%0aCorrelation+ID%3a+f1732dbf-804e-4f0a-808f-90fc490e8b85%0d%0aTimestamp%3a+2022-08-09+07%3a45%3a59Z&error_uri=https%3a%2f%2flogin.microsoftonline.com%2ferror%3fcode%3d50058&state=...
```

- A full redirect is taking place, which actually seems to be successful, as I don't get any errors, but then it starts again. I wonder if there might be some timing issues, and `MsalAuthenticationTemplate` is trying to fetch new tokens with the expired refresh token before the `PublicClientApplication` has finished its auth code flow

### MSAL Configuration

```javascript
const msal: Configuration = {
  auth: {
    clientId: 'CLIENT_ID',
    authority:
      'https://login.microsoftonline.com/TENANT_ID',
    redirectUri: window.location.origin,
    cloudDiscoveryMetadata:
      process.env.REACT_APP_CLOUD_DISCOVERY_METADATA ??
      'cloud_discovery_metadata',
    authorityMetadata:
      process.env.REACT_APP_AUTHORITY_METADATA ??
      'authority_metadata'
  }
}
```

### Relevant Code Snippets

```javascript
root.render(
  <React.StrictMode>
    <MsalProvider instance={instance}>
      <MsalAuthenticationTemplate
        interactionType={InteractionType.Redirect}
        authenticationRequest={{
          scopes: [
            'api://api_client_id/user_impersonation'
          ],
          extraScopesToConsent: ['User.Read']
        }}
      >
        {/* REST OF APP */}
      </MsalAuthenticationTemplate>
    </MsalProvider>
  </React.StrictMode>
)
```

### Reproduction Steps

This is kind of hard, as it only happens after the refresh token has expired, so I have to wait a day. This process might be able to be sped up if you can configure the refreshtoken and accesstoken to expire faster.

### Expected Behavior

Not looping.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Firefox

### Source

External (Customer)

**Comment by h3rmanj** [comment]
According to [these docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/refresh-tokens) the refresh token lifetime is non-configurable. Seems to reproduce this without waiting 24 hours would be to revoke the token without the msal instance knowing.

**Comment by h3rmanj** [comment]
I can't seem to reproduce it

I've tried making a simple app, with `forceRefresh: true` so it tries to fetch an access token on every reload without it being expired.
https://codesandbox.io/s/shy-pond-689hjt?file=/src/App.js

1. Login to the site ( https://689hjt.csb.app/ )
2. Run `Revoke-AzureADSignedInUserAllRefreshToken` PS command
3. Reload site so it tries to fetch new access token and realizes the refresh token is invalid

It seems to run correctly then, so I wonder if it has any different behavior if the token is expired, rather than forced fetched.

Revoking refresh token manually also don't cause the redirect loop in my original application, it only seems to happen if the tokens are expired.

**Comment by h3rmanj** [comment]
I've made a change in my code that enables debug logging so I'll be able to post logs if it happens again.

**Comment by h3rmanj** [comment]
I have acquired debug logs, but I'm reluctant to post them here as they contain auth codes etc.
@bmahall

**Comment by bmahall** [comment]
@h3rmanj Thanks for opening this issue,can you kindly please share the logs on my email found in Github profile?

**Comment by bmahall** [comment]
@h3rmanj Thanks for the email. While I am investigating your logs, an older issue might be of relevance to your case so linking it here for further investigation: [#4058](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4058), particularly the part where it is suggested to ensure that the pca instance is not re-rendered multiple times.

**Comment by h3rmanj** [comment]
I don't think that's the case. I'm instantiating the PublicClientApplication in it's own `auth.ts` file, which I then import the instance from and pass to `<MsalProvider>`. The app and auth works perfectly normal usually, but ever so often in a long-living tab it'll do this. Worth mentioning that I'm on React 18 in concurrent mode, although this is on a live site, so `StrictMode` shouldn't be doing anything.

**Comment by bmahall** [comment]
@h3rmanj  Linking the email communication here for reference:-
Thanks so much for sharing the logs over email . 
Based on the verbose logs, I am interested in the below:-


1.Can you try setting  navigateToLoginRequestUrl:false in the config?

2.  Are you registering callback in your code to handle the redirect response?
A snippet of how you are handling redirect response and where you are registering the callback would be helpful. 
e.g:-

function authCallback(error, response) {
    //handle redirect response
}

userAgentApplication.handleRedirectCallback(authCallback);


3. Are you calling handleRedirectPromise and allowing the promise to resolve before calling acquireTokenSilent again? This is really critical, as this could result in no token . 

4.
What is your redirect URI type?
Please verify your app registration. 


5. Lastly, If the issue is still there, you could use a tool like Fiddler to find the inner error message in the response. This should show the correct underlying server error response in the  form : AADSTS*** 

I suspect there are some missing parameters in your request, which is why it is resulting in 400:Bad Request as shown in the logs. You can check from the network response in Fiddler 
OR use  postman to send a post request to the url .

**Comment by h3rmanj** [comment]
Hi again, thanks for the answer. I will try to reproduce again, but it'll take a day or so to get an expired token. Do you by any chance know of any tool to export and import session storage, so I can try to develop with a broken one for easier debug and fixing?

I use `@azure/msal-react` with redirect. I also have an authorizedFetch method calling acquireToken directly on the public client instance.

After reading your suggestion, I suspect number 3 might be relevant. A lot of my components use the authorizedFetch method on load, and they might try to fetch to early. I thought I was safe since everything is wrapped in `MsalAuthenticationTemplate`, which shouldn't render its content unless the user is authenticated, but it seems it might render the content with an expired token, in which case my authorizedFetch method could potentially run before handleRedirectPromise is resolved.

The problem is since I use MsalAuthenticationTemplate, I don't really call handleRedirectPromise myself. Is there any way to see if there's an active unresolved promise on an instance directly?

**Comment by h3rmanj** [comment]
To give more context, a very simplified version of my app;

```jsx
const instance = new PublicClientApplication(config);

const authorizedFetch = async (url, init) => {
  // acquire token with scopes based on url
  const token = await instance.acquireToken();
  
  // Inject token in init
  
  return await fetch(url, init);
};

const App = () => {
  // lib for managing data fetching, fetch on mount, reconnect, focus etc.
  const { data } = useSWR("url", authorizedFetch);
  
  return ...
};

React.render(
  <MsalProvider instance={instance}>
    <MsalAuthenticationTemplate
      interactionType={InteractionType.Redirect}
      authenticationRequest={{
        scopes: [
          'some_api_scope'
        ],
        extraScopesToConsent: ['User.Read']
      }}
    >
      <App />
    </MsalAuthenticationTemplate>
  </MsalProvider>
);

```

I suspect that `MsalAuthenticationTemplate` might be rendering it's children, even though the token in cache has expired, which would make the `App` component try to fetch data and trying to acquire a token from the instance.

After reading the source code for `handleRedirectPromise`, it seems to return a singleton promise of sorts, so I think that adding `await instance.handleRedirectPromise()` to the start of `authorizedFetch` would be safe, and prevent it from doing anything while handling redirect? I will test if it fixes it later today when I've managed to reproduce the error.

**Comment by h3rmanj** [comment]
I'm struggling to reproduce it now. I've had a tab/session open for a couple of days. Has there been a minor or patch which could have fixed this?

The versions from my logs are @azure/msal-browser@2.28.0 & @azure/msal-react@1.4.4.
The versions now are @azure/msal-browser@2.28.1 & @azure/msal-react@1.4.5.

But I can't see any meaningful changes in those versions. I'll give it some more time.

**Comment by bmahall** [comment]
@h3rmanj Is this after you are adding `await instance.handleRedirectPromise()' ?

**Comment by h3rmanj** [comment]
No, I have not yet changed any code, I want to reproduce the error first so I can confirm a fix. I have a tab open om my work computer that I will check tomorrow, and I'll close this issue if it hasn't happened then.

**Comment by h3rmanj** [comment]
I can't reproduce it anymore. I'll close it for now, sorry for taking so much of your time.

**Comment by brahmaiahthota** [comment]
@h3rmanj  Did you resolve this issue ?

**Comment by h3rmanj** [comment]
I didn't explicitly solve it, but I haven't experienced this since closing the issue.

Ensure you're on the newest version of the packages, and create a new issue if you experience something similar, as I'm sure it would be caused by something different than this issue.
