### ISSUE TITLE
SPA with MSAL V2 not redirected to login page

### ISSUE THREAD

**Issue by foramkumar-parekh** [AzureAD/microsoft-authentication-library-for-js#5090]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.24.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.3.0

### Description

Current Setup:
Angular - 13
MSAL Angular - 2.3.0
MSAL Browser - 2.24.0
Node - 16.16.0
npm - 8.11.0

I have an angular app, with the above setup. The application is deployed in Azure App Service. The application should redirect to the login page but instead goes into an infinite loop in console logs that says login started and login failed. No specific error message. I am sharing the trace logs for more details.

### Error Message

Error - Guard - error while logging in, unable to activate main.7f41e47775b9d522.js:1:1159
10:49:09.793 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-angular@2.3.0 : Error - Guard - error: pkce_not_created: The PKCE code challenge and verifier could not be generated. Detail:TypeError: window.crypto.subtle is undefined main.7f41e47775b9d522.js:1:1159

### Msal Logs

10:49:09.739 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-browser@2.24.0 : Trace - BrowserCacheManager.updateCacheEntries called main.7f41e47775b9d522.js:1:1159
10:49:09.739 [Wed, 10 Aug 2022 05:19:09 GMT] : [9471a0b5-3e66-4c43-bfb9-1e96dc693a86] : msal.js.browser@2.24.0 : Verbose - initializeServerTelemetryManager called main.7f41e47775b9d522.js:1:1159
10:49:09.739 [Wed, 10 Aug 2022 05:19:09 GMT] : [9471a0b5-3e66-4c43-bfb9-1e96dc693a86] : msal.js.browser@2.24.0 : Verbose - initializeAuthorizationRequest called main.7f41e47775b9d522.js:1:1159
10:49:09.739 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-browser@2.24.0 : Trace - BrowserCacheManager.getServerTelemetry: cache hit main.7f41e47775b9d522.js:1:1159
10:49:09.739 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-browser@2.24.0 : Trace - BrowserCacheManager.setServerTelemetry called main.7f41e47775b9d522.js:1:1159
10:49:09.739 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-browser@2.24.0 : Trace - BrowserCacheManager.cleanRequestByState called main.7f41e47775b9d522.js:1:1159
10:49:09.739 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-browser@2.24.0 : Info - BrowserCacheManager.cleanRequestByState: Removing temporary cache items for state: eyJpZCI6ImRhY2M2ODVmLWFjMjMtNDlmNi1iOTgxLTJkNDEzNWIwMmJhOSIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicmVkaXJlY3QifX0= main.7f41e47775b9d522.js:1:1159
10:49:09.739 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-browser@2.24.0 : Trace - BrowserCacheManager.resetRequestCache called main.7f41e47775b9d522.js:1:1159
10:49:09.740 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-browser@2.24.0 : Trace - BrowserCacheManager.getTemporaryCache: Temporary cache item returned main.7f41e47775b9d522.js:1:1159
10:49:09.740 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-browser@2.24.0 : Info - Emitting event: msal:loginFailure main.7f41e47775b9d522.js:1:1159
10:49:09.740 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-browser@2.24.0 : Verbose - Emitting event to callback 6d7f5dc9-e804-46dd-b710-54757b342f9e: msal:loginFailure main.7f41e47775b9d522.js:1:1159
10:49:09.740 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-angular@2.3.0 : Verbose - BroadcastService - msal:loginFailure results in setting inProgress from login to none main.7f41e47775b9d522.js:1:1159
10:49:09.740 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-angular@2.3.0 : Error - Guard - error while logging in, unable to activate main.7f41e47775b9d522.js:1:1159
10:49:09.740 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-angular@2.3.0 : Error - Guard - error: pkce_not_created: The PKCE code challenge and verifier could not be generated. Detail:TypeError: window.crypto.subtle is undefined main.7f41e47775b9d522.js:1:1159
10:49:09.740 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-angular@2.3.0 : Verbose - Guard - loginFailedRoute set, redirecting main.7f41e47775b9d522.js:1:1159
10:49:09.759 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-angular@2.3.0 : Verbose - Guard - canActivate main.7f41e47775b9d522.js:1:1159
10:49:09.759 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-angular@2.3.0 : Verbose - MSAL Guard activated main.7f41e47775b9d522.js:1:1159
10:49:09.759 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-browser@2.24.0 : Verbose - handleRedirectPromise called main.7f41e47775b9d522.js:1:1159
10:49:09.759 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-browser@2.24.0 : Verbose - getAllAccounts called main.7f41e47775b9d522.js:1:1159
10:49:09.759 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-browser@2.24.0 : Verbose - handleRedirectPromise has been called previously, returning the result from the first call main.7f41e47775b9d522.js:1:1159
10:49:09.760 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-browser@2.24.0 : Verbose - getAllAccounts called main.7f41e47775b9d522.js:1:1159
10:49:09.760 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-angular@2.3.0 : Verbose - Guard - no accounts retrieved, log in required to activate main.7f41e47775b9d522.js:1:1159
10:49:09.760 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-angular@2.3.0 : Verbose - Guard - logging in by redirect main.7f41e47775b9d522.js:1:1159
10:49:09.760 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-angular@2.3.0 : Verbose - Guard - getting destination url main.7f41e47775b9d522.js:1:1159
10:49:09.760 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-angular@2.3.0 : Verbose - Guard - destination by hash routing main.7f41e47775b9d522.js:1:1159
10:49:09.760 [Wed, 10 Aug 2022 05:19:09 GMT] : [927efa71-70f4-4ba3-b761-51eb1a5b5ff3] : @azure/msal-browser@2.24.0 : Verbose - loginRedirect called main.7f41e47775b9d522.js:1:1159
10:49:09.760 [Wed, 10 Aug 2022 05:19:09 GMT] : [927efa71-70f4-4ba3-b761-51eb1a5b5ff3] : @azure/msal-browser@2.24.0 : Verbose - acquireTokenRedirect called main.7f41e47775b9d522.js:1:1159
10:49:09.760 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-browser@2.24.0 : Verbose - preflightBrowserEnvironmentCheck started main.7f41e47775b9d522.js:1:1159
10:49:09.760 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-browser@2.24.0 : Verbose - preflightInteractiveRequest called, validating app environment main.7f41e47775b9d522.js:1:1159
10:49:09.760 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-browser@2.24.0 : Trace - BrowserCacheManager.getTemporaryCache: No cache item found in local storage main.7f41e47775b9d522.js:1:1159
10:49:09.760 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-browser@2.24.0 : Verbose - getAllAccounts called main.7f41e47775b9d522.js:1:1159
10:49:09.760 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-browser@2.24.0 : Info - Emitting event: msal:loginStart main.7f41e47775b9d522.js:1:1159
10:49:09.760 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-browser@2.24.0 : Verbose - Emitting event to callback 6d7f5dc9-e804-46dd-b710-54757b342f9e: msal:loginStart main.7f41e47775b9d522.js:1:1159
10:49:09.760 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-angular@2.3.0 : Verbose - BroadcastService - msal:loginStart results in setting inProgress from none to login main.7f41e47775b9d522.js:1:1159
10:49:09.760 [Wed, 10 Aug 2022 05:19:09 GMT] : [927efa71-70f4-4ba3-b761-51eb1a5b5ff3] : msal.js.browser@2.24.0 : Verbose - initializeAuthorizationRequest called main.7f41e47775b9d522.js:1:1159
10:49:09.760 [Wed, 10 Aug 2022 05:19:09 GMT] : [927efa71-70f4-4ba3-b761-51eb1a5b5ff3] : msal.js.browser@2.24.0 : Verbose - getRedirectUri called main.7f41e47775b9d522.js:1:1159
10:49:09.761 [Wed, 10 Aug 2022 05:19:09 GMT] : [927efa71-70f4-4ba3-b761-51eb1a5b5ff3] : msal.js.browser@2.24.0 : Verbose - Initializing BaseAuthRequest main.7f41e47775b9d522.js:1:1159
10:49:09.761 [Wed, 10 Aug 2022 05:19:09 GMT] : [927efa71-70f4-4ba3-b761-51eb1a5b5ff3] : msal.js.browser@2.24.0 : Verbose - Authentication Scheme wasn't explicitly set in request, defaulting to "Bearer" request main.7f41e47775b9d522.js:1:1159
10:49:09.761 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-browser@2.24.0 : Trace - BrowserCacheManager.getTemporaryCache: No cache item found in local storage 2 main.7f41e47775b9d522.js:1:1159
10:49:09.761 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-browser@2.24.0 : Trace - BrowserCacheManager.updateCacheEntries called main.7f41e47775b9d522.js:1:1159
10:49:09.761 [Wed, 10 Aug 2022 05:19:09 GMT] : [927efa71-70f4-4ba3-b761-51eb1a5b5ff3] : msal.js.browser@2.24.0 : Verbose - initializeServerTelemetryManager called main.7f41e47775b9d522.js:1:1159
10:49:09.761 [Wed, 10 Aug 2022 05:19:09 GMT] : [927efa71-70f4-4ba3-b761-51eb1a5b5ff3] : msal.js.browser@2.24.0 : Verbose - initializeAuthorizationRequest called main.7f41e47775b9d522.js:1:1159
10:49:09.762 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-browser@2.24.0 : Trace - BrowserCacheManager.getServerTelemetry: cache hit main.7f41e47775b9d522.js:1:1159
10:49:09.762 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-browser@2.24.0 : Trace - BrowserCacheManager.setServerTelemetry called main.7f41e47775b9d522.js:1:1159
10:49:09.762 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-browser@2.24.0 : Trace - BrowserCacheManager.cleanRequestByState called main.7f41e47775b9d522.js:1:1159
10:49:09.762 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-browser@2.24.0 : Info - BrowserCacheManager.cleanRequestByState: Removing temporary cache items for state: eyJpZCI6ImRhYzExYTljLWNjZmYtNDBhYi05OTM2LTlhMzAxMzk1ZTA2NCIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicmVkaXJlY3QifX0= main.7f41e47775b9d522.js:1:1159
10:49:09.762 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-browser@2.24.0 : Trace - BrowserCacheManager.resetRequestCache called main.7f41e47775b9d522.js:1:1159
10:49:09.762 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-browser@2.24.0 : Trace - BrowserCacheManager.getTemporaryCache: Temporary cache item returned main.7f41e47775b9d522.js:1:1159
10:49:09.762 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-browser@2.24.0 : Info - Emitting event: msal:loginFailure main.7f41e47775b9d522.js:1:1159
10:49:09.762 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-browser@2.24.0 : Verbose - Emitting event to callback 6d7f5dc9-e804-46dd-b710-54757b342f9e: msal:loginFailure main.7f41e47775b9d522.js:1:1159
10:49:09.762 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-angular@2.3.0 : Verbose - BroadcastService - msal:loginFailure results in setting inProgress from login to none main.7f41e47775b9d522.js:1:1159
10:49:09.763 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-angular@2.3.0 : Error - Guard - error while logging in, unable to activate main.7f41e47775b9d522.js:1:1159
10:49:09.763 [Wed, 10 Aug 2022 05:19:09 GMT] : @azure/msal-angular@2.3.0 : Error - Guard - error: pkce_not_created: The PKCE code challenge and verifier could not be generated. Detail:TypeError: window.crypto.subtle is undefined main.7f41e47775b9d522.js:1:1159

### MSAL Configuration

```javascript
{
auth: {
    clientId: '7b6fcd14-3bab-4f75-b850-f601d156ac23',
    authority: 'https://login.microsoftonline.com/testscorpiogroup.net/', // for single tenancy
    consentScopes: ['user.read', 'api://bbbbbb-xxxxx-yyyyy-zzzz-aaaaa/my_scope'],
    redirectUri: 'https://myapp.azurewebsites.net', // dummy URL for this post
    postLogoutRedirectUri: 'https://myapp.azurewebsites.net', // dummy URL for this post,
    navigateToLoginRequestUrl: false,
  },
cache: {
  cacheLocation: BrowserCacheLocation.SessionStorage,
  storeAuthStateInCookie: false, // set to true for IE 11. We are not supporting IE.
},
system: {
  loggerOptions: {
    loggerCallback,
    logLevel: LogLevel.Trace,
    piiLoggingEnabled: true
  }
}
}
```

### Relevant Code Snippets

```javascript
there is no specific code part to check with
```

### Reproduction Steps

 I do not have any. The application should redirect to the login page, but it doesn't. Maybe logs can help.

### Expected Behavior

The application should redirect to the login page

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari

### Source

External (Customer)

**Comment by bmahall** [comment]
@foramkumar-parekh Thanks for opening this issue. From the error logs provided, the window.crypto.subtle is available only over secure context, as explained here [Crypto-subtle](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/subtle)
, which means it can only be used for https and localhost (not http). 
Are you using any http /unsecured context in your application which might be resulting in this error?

Also, can you share firefox and other browser versions you are using?

**Comment by foramkumar-parekh** [comment]
The SPA is deployed in the App Service and the _URL used is provided by azure_, which is HTTPS (eg. _https://myapp.azurewebsites.net_).

**Browser versions:**
- Chrome: 104.0.5112.81
- Firefox: 103.0.2
- Edge: 104.0.1293.54

**Comment by bmahall** [comment]
@foramkumar-parekh 

Please verify:
1. The site is loaded over https and not http
2. The redirect uri and authority is configured correctly,  is " https://login.microsoftonline.com/testscorpiogroup.net/" valid?
3. Is the redirect uri set properly in the Azure portal?

**Comment by foramkumar-parekh** [comment]
> @foramkumar-parekh
> 
> Please verify:
> 
> 1. The site is loaded over https and not http
> 2. The redirect uri and authority is configured correctly,  is " https://login.microsoftonline.com/testscorpiogroup.net/" valid?
> 3. Is the redirect uri set properly in the Azure portal?

@bmahall can you please be more specific about point 1? Points 2 & 3 are correctly configured.

**Comment by bmahall** [comment]
[](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5090#issuecomment-1236522163)

Regarding point 1:-
The server needs to be SSL/TLS enabled.

Can you please ensure that the logoutRedirectUri and postLogoutRedirectUri are both set correctly, and there is no inconsistency between the url's mentioned in the Azure and your application. 

Are you facing similar error on Firefox, since there are some known issues with Chrome around this. Alternatively, you can try checking whether the app is running in secured context by running  `window.isSecureContext()` in your browser- JS console. 

Please refer to this related question [Chrome:enable crypto](https://stackoverflow.com/questions/46670556/how-to-enable-crypto-subtle-for-unsecure-origins-in-chrome/46671627#46671627). 

Let me know if the object is still undefined. Thanks!

**Comment by foramkumar-parekh** [comment]
@bmahall 
I figured out that the app service was enabled for HTTP and HTTPS. After changing it to HTTPS only, it is working as expected.
