### ISSUE TITLE
MsalAuthenticationTemplate doesn't work correctly 9 out of 10 times in deployment

### ISSUE THREAD

**Issue by taoisu** [AzureAD/microsoft-authentication-library-for-js#5093]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.26.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.2

### Description

I'm using `MsalAuthenticationTemplate` to show authenticated content. When I develop locally this component works nicely without any problem. However, when I deployed it with a k8s pod the component is not working properly. Concretely, when I go to the url, say https://mypage.com, the popup window will show up, but the content of the popup window is empty, just as what's shown in https://mypage.com.

![image](https://user-images.githubusercontent.com/30015018/184036854-537e81ba-7e47-4116-ad08-21da1cfc4b40.png)

9 out of 10 times I'll hit this issue, and I had to refresh the browser page several times to get it working, sometimes I had to quit the browser and reopen.

I'm wondering if you have any idea what might be causing this issue?

### MSAL Configuration

```javascript
import { LogLevel } from "@azure/msal-browser";

const frontend_url = process.env.REACT_APP_FRONTEND_URL || "http://localhost:3000";

export const msalConfig = {
  auth: {
    clientId: "${client_id}",
    authority: "https://login.microsoftonline.com/${tenant_id}", // This is a URL (e.g. https://login.microsoftonline.com/{your tenant ID})
    redirectUri: frontend_url,
  },
  cache: {
    cacheLocation: "sessionStorage", // This configures where your cache will be stored
    storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
  },
  system: {
    loggerOptions: {
      loggerCallback: (level, message, containsPii) => {
        if (containsPii) {
          return;
        }
        switch (level) {
          case LogLevel.Error:
            console.error(message);
            return;
          case LogLevel.Info:
            console.info(message);
            return;
          case LogLevel.Verbose:
            console.debug(message);
            return;
          case LogLevel.Warning:
            console.warn(message);
            return;
        }
      }
    }
  }
};

// Add scopes here for ID token to be used at Microsoft identity platform endpoints.
export const loginRequest = {
  scopes: ["User.Read"]
};

// Add the endpoints here for Microsoft Graph API services you'd like to use.
export const graphConfig = {
  graphMeEndpoint: "https://graph.microsoft.com/v1.0/me"
};
```

### Relevant Code Snippets

```javascript
import React, { StrictMode } from 'react';
import ReactDOM from 'react-dom';
import { App } from './App';
import { mergeStyles } from '@fluentui/react';
import reportWebVitals from './reportWebVitals';

import { PublicClientApplication, InteractionType } from "@azure/msal-browser";
import { MsalProvider, MsalAuthenticationTemplate } from "@azure/msal-react";
import { msalConfig } from "./authConfig";


const msalInstance = new PublicClientApplication(msalConfig);

// Inject some global styles
mergeStyles({
  ':global(body,html,#root)': {
    margin: 0,
    padding: 0,
    height: '100vh',
  },
});

ReactDOM.render(
  <StrictMode>
    <MsalProvider instance={msalInstance}>
      <MsalAuthenticationTemplate interactionType={InteractionType.Popup} >
        <App />
      </MsalAuthenticationTemplate>
    </MsalProvider>
  </StrictMode>,
  document.getElementById('root'));

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();
```

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by taoisu** [comment]
@bmahall Do you have any ideas?

**Comment by bmahall** [comment]
@taoisu  Thanks for your patience! 
`<MsalAuthenticationTemplate interactionType={InteractionType.Popup} >
        <App />
      </MsalAuthenticationTemplate>`

This code piece will render the app only in case of authenticated users. IS there a chance the authentication is still in progress/ unsuccessful which renders the popup empty?

**Comment by bmahall** [comment]
@taoisu Can you also please share verbose logs and fiddler trace to further debug?

**Comment by bmahall** [comment]
@taoisu Please refer to my previous comments, and also can you confirm if redirectURI in the Azure portal is the same as the two options specified above? It must exactly match "http://localhost:3000" in case of localhost.

**Comment by taoisu** [comment]
@bmahall this issue sounds like the same as https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5091

The issue only happens after I deployed the service to the cloud, it never happens locally in localhost. I did check the url of the popup window and the hash seems to be eaten. I've tried your suggestion to redirect to an empty page, after I did that the issue seems to be gone.

**Comment by taoisu** [comment]
I checked the debug console and I didn't see any errors.

**Comment by taoisu** [comment]
I'm sorry I'm not familiar with the fiddler nor do I know how to enable verbose logs, since now the issue is gone, feel free to close this issue. If you still want me to share the log, please let me know and share with me how to make that happen. Thanks very much!

**Comment by samadeep** [comment]
Yes meeting with a lot of silent failures.

Could someone help here ?
