### ISSUE TITLE
PopupRequest - prompt - login not working as expected.

### ISSUE THREAD

**Issue by ViswanathCelitotech** [AzureAD/microsoft-authentication-library-for-js#5095]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.27.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Description

Hi Team,
As part of the application requirement, to perform certain operation, need to force the user to reauthenticate by entering the username and password.

To achieve the requirement, in **PopRequest** , the **prompt** as been set as '**login**'(which makes the user to enter the credentials every time).
When the tenant is not integrated, things are working fine as expected(crendetials popup is appearing everytime).
But when tenant is integrated with a thirdparty IDP(identity provider), crendetials popup is appearing only for the first time and automatically getting logged in from subsequent requests.

For referece, I have provided MSAL configuration and code snippet which has been used.

If needed, we can have an online connect and check the issue.

Regards,
Viswanath Vankadari

### MSAL Configuration

```javascript
{
            auth: {
                clientId: "<clientid>",
                authority: "https://login.microsoftonline.com/<tenantid>",
                redirectUri: "http://localhost:8181/",// the url mentioned here should be registered in Azure AD app registeration as SPA redirect uri
            },
            cache: {
                cacheLocation: "memoryStorage",
                storeAuthStateInCookie: false
                
            },
        }
```

### Relevant Code Snippets

```javascript
let Configuration: Configuration = {
            auth: {
                clientId: "<clientid>",
                authority: "https://login.microsoftonline.com/<tenantid>",
                redirectUri: "http://localhost:8181/",// the url mentioned here should be registered in Azure AD app registeration as SPA redirect uri
            },
            cache: {
                cacheLocation: "memoryStorage",
                storeAuthStateInCookie: false
                
            },
        }

        const PublicClientApplicationInstance = new PublicClientApplication(Configuration);
        const POPUP_REQUEST: PopupRequest /*| SilentRequest*/ = {
            scopes: ['https://graph.microsoft.com/User.Read'],// Add more permissions in this array as needed.
            prompt: 'login',//'consent',//'create''login',//'select_account',
            }


        let msalInstance: PublicClientApplication = PublicClientApplicationInstance as PublicClientApplication;
        msalInstance["browserStorage"].clear();
        window.localStorage.clear();


        PublicClientApplicationInstance.disableAccountStorageEvents;

        PublicClientApplicationInstance.loginPopup(POPUP_REQUEST).then(PopUpResponse => {
            console.log('PopUp response :', PopUpResponse);

        }).catch(error => {
            console.log('error', error);
        });
```

### Reproduction Steps

1. Can have a small react application with just a button.
2. In the button click event, the code snippets can be kept .
3. Once the button is clicked from than once, the behaviour can be observed.

### Expected Behavior

When a tenant is integrated with a third party IDP and  for the  **PopRequestpt** being set as '**login**', credentials popup should be shown everytime.

### Identity Provider

Other

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer

### Source

External (Customer)

**Comment by bmahall** [comment]
@ViswanathCelitotech  We don't officially support third party IDP [https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-fed-compatibility](url). 
To debug on the MSAL side of things, can you please try using the sessionStorage once for your scenario and see if the credentials popup is shown every time.

**Comment by ViswanathCelitotech** [comment]
Hi Team,
We have tried using the storage location with local/session/windows. But still the behaviour is the same, which is not an expected one.

Is there any alternate option/approach to achieve the desired result??

Regards,
Viswanath Vankadari

**Comment by bmahall** [comment]
@ViswanathCelitotech This can be due to the third-party IDP specific behavior . 
Can you share network trace to see which parameters are getting sent in the popup request, and you can send a fiddler trace to the email on my profile. 
Also, are you using B2c ?

**Comment by bmahall** [comment]
@ViswanathCelitotech If you need help sending verbose logs, or fiddler trace please let me know. Thanks

**Comment by bmahall** [comment]
@ViswanathCelitotech  To enable verbose logs:-You can change the logLevel in config as below:-

`auth: {
      clientId: clientid
      authority: authority,
    
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Verbose, // Change to Verbose here
        piiLoggingEnabled: false
      }
    }`
Please use [Fiddler](https://www.telerik.com/download/fiddler) to share network trace for us to be better able to solve this issue, Thanks!
