### ISSUE TITLE
Force login locale doesn't seem to work with extraQueryParameters

### ISSUE THREAD

**Issue by michaelhum** [AzureAD/microsoft-authentication-library-for-js#5096]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.28.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.4

### Description

Based on #4289, we should be able to override the browser's preferred language setting with a `locale` parameter in the `extraQueryParameters` property of the login request.

However, this does not seem to work. The original poster of the related issue did not provide any followup so I'm creating this one instead :) 

### MSAL Configuration

```javascript
const msalConfig = {
  auth: {
    clientId: config.msal.CLIENT_ID,
    authority: config.msal.AUTHORITY,
    redirectUri: config.msal.REDIRECT_URI,
    postLogoutRedirectUri: config.msal.POST_LOGOUT_REDIRECT_URI,
  },
  cache: {
    cacheLocation: 'localStorage',
    storeAuthStateInCookie: false,
  },
```

### Relevant Code Snippets

```javascript
const accessTokenRequest = {
    scopes: [...],
    extraQueryParameters: {
      locale: 'en',
    },
  };
  instance
    .acquireTokenPopup(accessTokenRequest)
    .then(() => {})
    .catch((error) => {
      // eslint-disable-next-line no-console
      console.log(error);
    });
```
```


### Reproduction Steps

1. Change browser preferred language to something other than English (I changed it to fr-CA in Edge).
2. Go to app and trigger login popup with above configuration

### Expected Behavior

The login popup text is in English due to the `locale` param in the `extraQueryParameters`.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Edge

### Regression

_No response_

### Source

External (Customer)

**Comment by bmahall** [comment]
@michaelhum  Thanks for creating a new issue.  I am able to reproduce this behavior. 
Just FYI, if you are using Azure b2c, there are detailed steps for language customization here [https://docs.microsoft.com/en-us/azure/active-directory-b2c/enable-authentication-react-spa-app-options?tabs=popup](url). 

The locale parameter doesnt override the default browser setting and  I am checking if we can support this feature going forward. I am curious if you have considered writing your own click handler to force set the popup dialog language?

**Comment by michaelhum** [comment]
Hi @bmahall we are unfortunately not using B2C yet, but that's good to know for the future thanks!

I am not sure I follow regarding trying to write a dedicated handler - is this something supported by msal? Or do you mean trying to edit the text of the popup manually? I don't see a setting to swap the locale of the popup once it's opened (unless I am missing something here) - sorry for the confusion :)

**Comment by bmahall** [comment]
@michaelhum Can you please try using mkt parameter?
Example: mkt=fr-fr

**Comment by michaelhum** [comment]
@bmahall the mkt parameter seems to work! I am able to swap between English/French with en/fr as input for both the login and logout popup. Thanks!

**Comment by abhinavgurung** [comment]
Hello @bmahall, I am using mkt parameter and it is working fine for login. for log out pop up, When it says "Please wait while we sign out", I still get it in English even though, the mkt parameter passed was fr. 
Could you share some thoughts. 
Thanks
