### ISSUE TITLE
Firefox get an error "window.indexedDB.databases is not a function" when user logout

### ISSUE THREAD

**Issue by dilidili** [AzureAD/microsoft-authentication-library-for-js#5107]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.23.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.3.2

### Public or Confidential Client?

Public

### Description

When call the ```IPublicClientApplication.logoutRedirect()```, the deletion of MSAL databse https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/be68c190f5561e1a8e7c3144cfee35a5dbc5f109/lib/msal-browser/src/cache/DatabaseStorage.ts#L239 will fail due to ```window.indexedDB.databases is not a function``` in Firefox.

### MSAL Configuration

```javascript
export const msalConfig: Configuration = {
  auth: {
    clientId: IWPAppId,
    redirectUri: `${window.location.origin}/spa-signin-oidc`,
    postLogoutRedirectUri: "/",
  },
  cache: {
    cacheLocation: "localStorage",
  },
  system: {
    // Give more timeout for waiting for a response hash in an iframe or popup other than default value 6s
    iframeHashTimeout: 10000,
    loggerOptions: {
      loggerCallback: (
        level: LogLevel,
        message: string,
        containsPii: boolean
      ): void => {
        if (containsPii) {
          return;
        }

        switch (level) {
          case LogLevel.Error:
            sendConsoleErrorEvent(`@azure/msal-browser ${message}`);
            return;
          case LogLevel.Info:
          case LogLevel.Verbose:
          case LogLevel.Warning:
            sendNormalEvent(
              `@azure/msal-browser ${message}`,
              "web",
              // Use 3 for EventSendType.SyncFetch in const enum isolated module
              shouldSendSync(message) ? 3 : undefined
            );
            return;
        }
      },
      piiLoggingEnabled: false,
    },
  },
};
```

### Relevant Code Snippets

```javascript
instance.logoutRedirect();
```

### Reproduction Steps

1. Signed in user.
2. Call IPublicClientApplication.logoutRedirect() to signout.

### Expected Behavior

The signout will not throw exception and delete all MSAL databses successfully.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Firefox

### Source

Internal (Microsoft)

**Comment by hectormmg** [comment]
Thanks for bringing this to our attention. I'll look into it.

**Comment by mchr3k** [comment]
I think this ticket should still be open as https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/5112 has not been merged yet.
