### ISSUE TITLE
contributing.md 404

### ISSUE THREAD

**Issue by zgqit** [AzureAD/microsoft-authentication-library-for-js#5108]
### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Public or Confidential Client?

Public

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-angular/README.md

### Description

Contribute
We enthusiastically welcome contributions and feedback. Please read the [contributing guide](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/contributing.md) before you begin.
when i clicked the contributing guide link,i got the 404 page.

**Comment by hectormmg** [comment]
Thanks for bringing this to our attention, I've fixed the link!
