### ISSUE TITLE
How to get MsalInterceptor's error

### ISSUE THREAD

**Issue by ladudu** [AzureAD/microsoft-authentication-library-for-js#5109]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.26.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.3.2

### Public or Confidential Client?

Public

### Description

I want handle the MsalInterceptor error but I just got error log.
I have requested an api which is not authorized by the admin．
He seems to keep looping, requesting a token, making an error, logging in again.
![image](https://user-images.githubusercontent.com/26648370/185044431-9fc38b87-1dd5-4584-983b-bd04e72caa75.png)
![image](https://user-images.githubusercontent.com/26648370/185043797-48e8a255-b638-499e-970c-6d6798e9957f.png)
I want to deal with this error how to do？
Do I need to write my own Interceptor?
I listened to all events and it doesn't seem to be an error event.
![image](https://user-images.githubusercontent.com/26648370/185044672-5c4a9c2c-97ca-4814-9cd7-8cc7b895bea4.png).

### Relevant Code Snippets

```javascript
this.broadcastService.msalSubject$.subscribe((result: EventMessage) => {
      console.error(result);
    });
```

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@ladudu The MsalInterceptor is designed to handle errors thrown by `acquireTokenSilent` by invoking interaction and acquiring the token interactively, either by popup or by redirect. After the logs pasted above, are you then able to acquire the token by redirect? Are there other errors thrown later? Please provide the rest of the logs if possible.

**Comment by ladudu** [comment]
> @ladudu The MsalInterceptor is designed to handle errors thrown by `acquireTokenSilent` by invoking interaction and acquiring the token interactively, either by popup or by redirect. After the logs pasted above, are you then able to acquire the token by redirect? Are there other errors thrown later? Please provide the rest of the logs if possible.

Thank you for your reply.I seem to understand what you mean.
it able to acquire the token by redirect，but It cant get access token always.Because this api currently has not authorized by the admin.So MsalInterceptor will keep trying to get the token, but he can never get it.

I want show error message in this state，But he keeps looping.How to stop it？

Below are all the logs about azure，
[msal.txt](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/9366910/msal.txt)

We are using custom policy，Should this kind of state be handled in there?

**Comment by jo-arroyo** [comment]
@ladudu If you are wanting to show the error message after acquireTokenSilent fails in the MsalInterceptor, we recommend you use a custom interceptor, as the current MsalInterceptor will handle it interactively without throwing the error.

**Comment by ladudu** [comment]
> @ladudu If you are wanting to show the error message after acquireTokenSilent fails in the MsalInterceptor, we recommend you use a custom interceptor, as the current MsalInterceptor will handle it interactively without throwing the error.

Thank you for your help.I would write myself interceptor.
have a great day!

**Comment by jo-arroyo** [comment]
Thank you. Closing this issue as customer question answered.
