### ISSUE TITLE
User is not redirected to redirect uri on mobile

### ISSUE THREAD

**Issue by 1hw7** [AzureAD/microsoft-authentication-library-for-js#5111]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.24.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.0

### Public or Confidential Client?

Public

### Description

On mobile (safari and edge) when a user logs out, it hangs on the "you have logged out page" and the redirect uri does not seem to be triggered (user is never redirected to redirect uri)

### MSAL Configuration

```javascript
auth: {
        clientId: config.auth.clientId,
        authority: 'https://login.microsoftonline.com/consumers',
        redirectUri: `${config.auth.redirectUrl || config.sasUrl}/home`,
        navigateToLoginRequestUrl: false,
        postLogoutRedirectUri: `${config.auth.redirectUrl || config.sasUrl}`,
    },
    cache: {
        cacheLocation: BrowserCacheLocation.SessionStorage,
    }
```

### Relevant Code Snippets

```javascript
used button click to trigger signout, used instance.logoutredirect on button click
```

### Reproduction Steps

1. Open safari on mobile
2. Click sign out button
3. User is signed out, but never redirected back to redirect uri

### Expected Behavior

User should be redirected to redirect uri

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Edge, Safari

### Source

Internal (Microsoft)

**Comment by hectormmg** [comment]
@1hw7 is the `postLogoutRedirectUri` registered as a redirect URL and Logout URL in your app registration?

Here's the three requirements for successful redirection after logout:

1. Pass a postLogoutRedirectUri to logout
2. Register this url as a redirectUri on the app registration

Check out the [MSAL Logout](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md) docs for more details.

**Comment by 1hw7** [comment]
Thanks for your help Hector! Yes, it is and this works for us in desktop. The issue only arises on a mobile device
edit: actually, it's possible we didn't configure this correctly! sorry, double checking now. Thank you!

**Comment by 1hw7** [comment]
We confirmed that our implementation follows the docs you linked Hector (thank you!) so we are awaiting further context on what the error is and how we can solve this problem

**Comment by 1hw7** [comment]
To update: user is not actually signed out and the user is sso'd back into the app. It seems the server session is not ended?

**Comment by sameerag** [comment]
Can we please get the msal and network logs @1hw7?

**Comment by sameerag** [comment]
Keeping this active. The team reached out to me offline and provided the needed information.

**Comment by tadeas22** [comment]
Same problem for me, please reopen

**Comment by gatsby-david** [comment]
For me, the bug is happening only in Chrome on mobile. FF is ok.

**Comment by 1hw7** [comment]
Hi @sameerag could we please reopen this issue(edit: i didn't realize my comment would reopen sorry!)? i do not think the issue has been resolved on our end

**Comment by sameerag** [comment]
The issue is auto closed. This will be kept open.

**Comment by gatsby-david** [comment]
We have investigated this bug with @tadeas22 into depth and possibly find the root source of the problem, sadly not the solution. It looks like the bug isn't connected with msal library itself but with the implementation of IndexedDB (https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB). If you run the example code from this page https://developer.mozilla.org/en-US/docs/Web/API/IDBRequest on the buggy device (in our case Huawei P20 Lite, Samsung Galaxy S8, S9) you will find out that the `IDBRequest.readyState` is stucked in `pending` state for some reason and that's why the redirection is never finished. The redirection part of the code don´t even start because the script stucks on indexedDB manipulation which must finish before the redirect is called.

**Comment by 1hw7** [comment]
Hi! I'm wondering if there are any updates on this issue or if there is any other information i can provide?

**Comment by sameerag** [comment]
@bmahal Can we prioritize to root cause this?

**Comment by bmahall** [comment]
@1hw7 I am in touch with @sameerag and will get back on this on priority. Thanks

**Comment by bmahall** [comment]
@1hw7 Please share logs on the email mentioned on my profile if possible , looking forward to chat on Monday when you are next available.

**Comment by 1hw7** [comment]
Commenting to leave open, as the issue continues to persist

**Comment by sameerag** [comment]
@1hw7 Are we still stuck on this?

**Comment by 1hw7** [comment]
@sameerag sorry i missed your comment! Thomas was able to help us look into it (thank you Thomas!). He gave us some insight on what might be going wrong on our end, we really appreciate the help!

**Comment by asimyaramis** [comment]
can u describe what is causing the error and how u solved? @1hw7
