### ISSUE TITLE
Multi Tenant guest users - wrong authority

### ISSUE THREAD

**Issue by jcharnley** [AzureAD/microsoft-authentication-library-for-js#5113]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.28.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

0

### Public or Confidential Client?

Public

### Description

Having a issue when I configure MSAL to accept guest users from multi tenants. Guest users cannot access the resource because their tenant id is pointing to the base application on the resource tenant (where the app was created) not where it has been consumed.

In a single tenant configuration this works as the authority is specified. However when the b2b multi setup is on /common or / organizations then guest users seem to point back to where the applicatin is hosted. and I cannot get the tenant id from any of the msal endpoints nor Graph API.

Originally, we setup the MSAL config like so:

export const msalConfig = {
  auth: {
    clientId: "{clientId}",
    authority:
      "https://login.microsoftonline.com/{tenantID}",
 
This is a single tenant setup as the tenantID is specify, guests invited into that tenant can access shared resources
 
export const msalConfig = {
  auth: {
    clientId: "{clientId}",
    authority:
      "https://login.microsoftonline.com/{common||organizations}",
 
This is a multi tenancy setup, any organisation with a AAD account can signin and share resources (this all works fine and tested)
 
however, with this multi-tenant setup if an organisational member invites a guest user, they are a part of that organisation not where the application originates from (our production tenant). The token seems to be coming from the production tenant they cannot access the shared resource. 1. because they aren't a user of that tenant, 2. the resource is not on that tenant.
 
MSAL documents that we can change the authority on request, however I cannot seem to find the guest users invitee tenant id. it always links back to our production tenant.
 
I have found a really good blog entry that talks about the same issue, however its out of date. Could anyone help in anyway possible ?
 
[https://www.syskit.com/blog/supporting-tenant-selection-for-b2b-users-in-a-multitenant-azure-active-directory-application/](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.syskit.com%2Fblog%2Fsupporting-tenant-selection-for-b2b-users-in-a-multitenant-azure-active-directory-application%2F&data=05%7C01%7Cv-shinyau%40microsoft.com%7C4f2fdb63f4bf49f2a4c208da810c7e34%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637964187953174784%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=dJYkEdf51K%2BPP%2Fk1Gu5IoSXXC1JnPS9hC7Djvw0z3%2BQ%3D&reserved=0)
 
[https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/3223](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzureAD%2Fmicrosoft-authentication-library-for-js%2Fissues%2F3223&data=05%7C01%7Cv-shinyau%40microsoft.com%7C4f2fdb63f4bf49f2a4c208da810c7e34%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637964187953174784%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=SvXCZ8VXgRJ3EKZTz%2FYI90CDOuuq%2Fz7hWpeLTNJvLRU%3D&reserved=0)

Thanks in advance

### Error Message

<img width="904" alt="Screenshot 2022-08-18 at 16 03 17" src="https://user-images.githubusercontent.com/25176118/185428801-22e6627b-c1bf-4b0a-99ef-4cab7351ceed.png">
<img width="763" alt="Screenshot 2022-08-18 at 16 02 55" src="https://user-images.githubusercontent.com/25176118/185428889-910596a8-742d-4485-9ef7-80a57d7d0a27.png">

### MSAL Configuration

```javascript
export const msalConfig = {
  auth: {
    clientId: "{clientId}",
    authority:
      "https://login.microsoftonline.com/{common||organizations}",
 },
  cache: {
    cacheLocation: "sessionStorage",
    storeAuthStateInCookie: false
  }
}
```

### Relevant Code Snippets

```javascript
// sign in function
export const signIn = async () => {
  myMSALObj.loginRedirect(loginRequest);
 
};

// success response login
const handleResponse = (resp) => {
  const welcome = document.getElementById("signInMessageMicrosoftSignin");
  if (resp !== null) {
    username = resp.account.name;
    welcome.textContent = username;
    console.log("username",username)
    return resp;
  }
};

// Redirect: once login is successful and redirects with tokens, call Graph API
myMSALObj
  .handleRedirectPromise()
  .then(handleResponse)
  .then((resp) => {
    if (!resp) return;
    downloadModelFromUrl(resp.accessToken);
    updateStaticLoadingContent(
      document,
      "staticLoadingScreen",
      sharedLoaderContent(document)
    );
  })
  .catch((err) => {
    console.error(err);
  });
```

### Reproduction Steps

1. create app regisation as a multi tenant application on base tenant 
2. another organization/tenant to consume
3. other organization can invite guest users
4. guest invite sent/redeem
5. give permissions
6. use web app url with sharing link as a query parameter
7. use msal to login to auth into the tenant
8. call the endpoint/ read the file

### Expected Behavior

Guest users are able to authorise via the tenant they have been invited into to access the resource

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

btw this is the response I get from the guest user, as you can see it has a tenant id but its not the tenant id that the guest has been invited to

<img width="947" alt="Screenshot 2022-08-18 at 16 10 25" src="https://user-images.githubusercontent.com/25176118/185430358-f5af8a5f-5964-462a-88ee-b5c0903c28d3.png">

**Comment by hectormmg** [comment]
@jcharnley thanks for the question and sorry for the delay. I'll need some time to look into it and get back to you with more information.

**Comment by jcharnley** [comment]
I really appreciate this, let me know if you need further information.

**Comment by hectormmg** [comment]
@jcharnley if I understood correctly, you will either need to supply the tenanted authority (if you know the tenant before hand) or queyr the ARM API and prompt the user to select the tenant they want to sign into. https://docs.microsoft.com/en-us/rest/api/resources/

**Comment by jcharnley** [comment]
thanks @hectormmg i've been speaking with Sergio on this too. I will proceed with the ARM solution and see how that goes first. I will keep you updated. Thanks again

**Comment by jcharnley** [comment]
I implemented The ARM Api however this does not allow for type guests users, it only works for AAD members. I have found a working solution, I now send over the tenantID as a query parameter in the sharing url, and I update the authority on login request. This can be closed now but could be a idea to look into guest accounts in a multi tenant setup as people will run into this problem
