### ISSUE TITLE
msal-browser - handleRedirectPromise() returns null for loginRedirect request from SPFx React app

### ISSUE THREAD

**Issue by vineeshvenu97** [AzureAD/microsoft-authentication-library-for-js#5115]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.28.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

2

### Public or Confidential Client?

Public

### Description

I am trying to implement redirect based authentication from an SPFx React application. I am using @azure/msal-browser version 2.28.1, in this I have implemented handleRedirectPromise() method which returns null value as token when the method gets registered for the first time.
Later when I call loginRedirect , I see the app redirecting from the original specified redirectUri with auth code in the url.
This interaction stops at this point and control does not get back to the resolve/reject(then/catch) part of handleredirectPromise method.
How do I get the handleRedirectPromise to return a valid token response?

### MSAL Configuration

```javascript
let authConfig = {
            auth: {
                authority: Configurations.AUTHENTICATION.authority,
                cacheLocation: "localStorage",
                clientId: Configurations.AUTHENTICATION.clientId,
                redirectUri: window.location.href,
                navigateToLoginRequestUrl: false
            },
           cache: {
                cacheLocation: "localStorage"
            }
}
```

### Relevant Code Snippets

```javascript
public authenticateUser = () => {
        debugger;
        let accountObj = this.authContext.getAllAccounts();
        if(accountObj.length == 0 )
        {
            this.authContext.loginRedirect();
        }
    }


public registerHandleCallback = async () => {
        debugger;
        await this.authContext
            .handleRedirectPromise()
            .then((tokenResponse) => {
                console.log(tokenResponse)
                console.log("success")
                

                if(tokenResponse == null){
                    let accountObj = this.authContext.getAllAccounts();
                }
                
            }).then(res=>{
                console.log(res)
            })
            
            .catch(error => {
                console.log(error)
            })
    }
```

### Reproduction Steps

await svc.registerHandleCallback();
await svc.authenticateUser();

I am calling the two mentioned methods from webpart base file.

### Expected Behavior

After redirecting to the specified URL, the control is expected to be back to the promise handlers of handleRedirectPromise method.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

External (Customer)

**Comment by hectormmg** [comment]
@vineeshvenu97 thanks for opening the issue. In order to debug this, it'd be helpful if you could please send a Fiddler or network trace to the e-mail in my profile and if possible, the MSAL logs which you can post here on your issue description.
