### ISSUE TITLE
Firefox stuck in login loop

### ISSUE THREAD

**Issue by eluchsinger** [AzureAD/microsoft-authentication-library-for-js#5118]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.28.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.4.1

### Public or Confidential Client?

Public

### Description

On Firefox we are noticing a redirection loop when trying to login. This stops from happening after clearing the cookies & cache.

### Error Message

The only errors I get is an HTTP `400` from AAD B2C and the error below from MSAL:

```json
{
    "error":"invalid_grant",
    "error_description":"AADB2C90128: The account associated with this grant no longer exists. Please reauthenticate and try again.\r\nCorrelation ID: <redacted>\r\nTimestamp: 2022-08-19 08:11:57Z\r\n"}
```

@azure/msal-angular@2.4.1 : Error - Interceptor - acquireTokenSilent rejected with error. Invoking interaction to resolve.

### Msal Logs

Sorry. Can't do, because I can not reproduce the behavior after clearing the cookies once.

### MSAL Configuration

```javascript
{
    auth: {
      clientId: environment.AzureClientId,
      authority: b2cPolicies.authorities.signUpSignIn.authority,
      redirectUri: "/",
      postLogoutRedirectUri: "/",
      knownAuthorities: [`${environment.AzureB2CName}.b2clogin.com`],
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE,
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Warning,
        piiLoggingEnabled: false,
      },
    },
  }
```

### Relevant Code Snippets

```javascript
None
```

### Reproduction Steps

1. Navigate to a guarded route via `MsalGuard` using Firefox
2. Get stuck in a loop

### Expected Behavior

Go to the login screen or serve the guarded route if already logged in.

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Firefox

### Source

External (Customer)

**Comment by eluchsinger** [comment]
I have to say these loops have been a common thing for MSAL since it's release. Maybe you could look into implementing better tools to detect them (and gather the metrics needed to understand them) and if possible automatically try to fix them, like trying to clear the storages.

**Comment by hectormmg** [comment]
@eluchsinger thanks for the suggestion and for opening the issue.  Was this loop something that was only seen once and fixed by clearing storage and cookies? Or has it been noticed by multiple users?

**Comment by eluchsinger** [comment]
@hectormmg it was experienced by multiple users. All on Firefox and probably had not used the login in a while (could both be coincidence of course).

**Comment by hectormmg** [comment]
@eluchsinger could you show us what you're passing in your app-routing.module.ts so we can see how your app implements reidrects?

**Comment by eluchsinger** [comment]
@hectormmg of course.

This is what we are doing in the app-routing:

```typescript
import { NgModule } from "@angular/core";
import { Routes, RouterModule } from "@angular/router";
import { IndexComponent } from "./index/index.component";
import { MsalGuard } from "@azure/msal-angular";
import { BrowserUtils } from "@azure/msal-browser";

const routes: Routes = [
  {
    path: "",
    component: IndexComponent,
  },
  {
    path: "b2b",
    loadChildren: () => import("./b2b/b2b.module").then((m) => m.B2bModule),
    canActivate: [MsalGuard],
  },
];

@NgModule({
  imports: [
    RouterModule.forRoot(routes, {
      initialNavigation:
        !BrowserUtils.isInIframe() && !BrowserUtils.isInPopup()
          ? "enabledNonBlocking"
          : "disabled", // Set to enabledBlocking to use Angular Universal
    }),
  ],
  exports: [RouterModule],
})
export class AppRoutingModule {}

```

**Comment by jo-arroyo** [comment]
@eluchsinger Picking up this issue. Have you continued to see this behavior since the last comment? If so, are you able to get verbose logs and a network trace? We have thus far been unable to reproduce this behavior on our end.

**Comment by eluchsinger** [comment]
@jo-arroyo I haven't heard of any further problems. I think we can close this issue. Thanks!
