### ISSUE TITLE
Not storing token in storage correctly

### ISSUE THREAD

**Issue by rahulraajtanwar** [AzureAD/microsoft-authentication-library-for-js#5120]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.22.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.1.2

### Public or Confidential Client?

Confidential

### Description

Stored token information is different in 2 separate packages with the same library version. 

### MSAL Configuration

```javascript
{
     auth: {
      clientId: 'f6154650-169f-4b7a-998f-5b9cec24177e',
      authority: 'https://thrivepasslogin.b2clogin.com/tfp/thrivepasslogin.onmicrosoft.com/B2C_1_susi',
    },
    cache: {
      cacheLocation: BrowserCacheLocation.SessionStorage,
      storeAuthStateInCookie: false
    }
}
```

### Relevant Code Snippets

```javascript
Same as in your sample.
https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular13-rxjs7-sample-app
```

### Reproduction Steps

Same as in your sample.
https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular13-rxjs7-sample-app

### Expected Behavior

Should be storing the token like this
![image](https://user-images.githubusercontent.com/24808435/185653772-f75e0ba8-041a-4457-b9f7-807d99dcca86.png)

But storing them like this
![image](https://user-images.githubusercontent.com/24808435/185653903-4cac1a62-af60-490f-bf2c-783f5f0285d7.png)

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Edge

### Source

Internal (Microsoft)

**Comment by derisen** [comment]
@rahulraajtanwar I think you are looking at the temporary auth artifacts that msal is caching. If you have configured your msal with `cacheLocation: "localStorage"`, durable cache entries will be stored in local storage (your 1st screenshot). msal also caches some temporary entries, and they will be in the session storage (or memory storage if you specify it in configuration). Checkout the [caching doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/caching.md#cached-artifacts) for more.

**Comment by derisen** [comment]
Closing let us resolved. Let us know if you have further questions.
