### ISSUE TITLE
@azure/msal-node missing README.md

### ISSUE THREAD

**Issue by diberry** [AzureAD/microsoft-authentication-library-for-js#5121]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

no version

### Wrapper Library

Not Applicable

### Wrapper Library Version

no wrapper

### Public or Confidential Client?

Public

### Description

The readme is missing from npm: 

![image](https://user-images.githubusercontent.com/41597107/185425197-c60a3a60-cb4c-44d1-adcc-09cfae469576.png)

**Expected behavior**
This should have a README with sample code - standard stuff the other @azure packages has. 

If I go to the [GitHub repository](https://github.com/AzureAD/microsoft-authentication-library-for-js#readme), it still doesn't have any sample code. 

This probably isn't a P0 but it sure feels like it. How do I use this package? 

Moved from [azure-sdk-for-js](https://github.com/Azure/azure-sdk-for-js/issues/22937)

### Identity Provider

Other

### Source

Internal (Microsoft)

**Comment by jasonnutter** [comment]
I think this is a transient npmjs.com issue, as I've seen it with various packages. Doesn't currently reproduce for me:

![image](https://user-images.githubusercontent.com/443409/185665176-0bf7289b-0be0-4bff-8903-0316c064a9fb.png)

**Comment by jasonnutter** [comment]
@hectormmg Can you look at potentially improving discoverability of basic usage examples and full sample links?
