### ISSUE TITLE
Delegated Admin - Switching tenants / Authenticating against a different authority returns a cached token from the incorrect issuer

### ISSUE THREAD

**Issue by t-jmakulec** [AzureAD/microsoft-authentication-library-for-js#5127]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.28.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

When a user that has access to multiple tenants, after authenticating with one, a silent authentication request to other authorities succeeds, however the token that it responds with is the cached token, from the wrong issuer.

### MSAL Configuration

```javascript
Multi-tenant app. Authority is set each time before a request to https://login.microsoftonline.com/Tenant_ID
```

### Relevant Code Snippets

```javascript
const silentRequest: msal.SilentRequest = {
                        scopes: [resourceId + "/.default"],
                    };
                    this.AuthContext.acquireTokenSilent(silentRequest).then((response: msal.AuthenticationResult) => {
                        resolve(response?.accessToken);
                    }, (error: msal.AuthError) => {
                        reject(error);
                    });
```

### Reproduction Steps

1. Have a delegated admin/guest admin user to more than one tenants
2. Authenticate for one of the authorities
3. Try to authenticate against a different authority silently
4. Check the response and compare the issuer in returned JWT with the authority

### Expected Behavior

The issuer matches the authority.

Side note: Force refresh works, however it doesn't allow setting the returned account as active account, marks the active account null.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Edge

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
@t-jmakulec This is happening because `authority` only specifies where to go when a new token is needed and is not used for cache lookups. In order to get the cached token you expect you need to provide the account object that corresponds to the tenant you wish to get a token for.

> however it doesn't allow setting the returned account as active account, marks the active account null.

Can you please expand this? This sounds unexpected.

**Comment by t-jmakulec** [comment]
So, as I understand it - it will always return the cached token even if we point to the new authority? Since this user is able to authenticate against it as well? 


Regarding setting the account: After receiving the response from silent request against the new authority, I'm calling
`Auth.SetActiveAccount(response.account)` -where Auth is PublicClientApplication.
When printing the response, there is an account returned with the correct tenantId (matching the new authority). However, the operation doesn't run as expected, the account is set to null and any further attempts to authenticate in requests of course fail.

**Comment by tnorling** [comment]
>So, as I understand it - it will always return the cached token even if we point to the new authority? Since this user is able to authenticate against it as well?

Yes, an `account` object is tied to a specific tenant. When you are providing the `account` for tenant A with `authority` for tenant B it creates a conflict. To get back the tokens you expect you need to make sure your authority matches your account.

>However, the operation doesn't run as expected, the account is set to null and any further attempts to authenticate in requests of course fail.

Can you see the active account in local or session storage when this happens? Can you collect trace level logs and share them here?
