### ISSUE TITLE
AcquireTokenSilient on MsalGuard not working due lack of claim name

### ISSUE THREAD

**Issue by cleberdantas** [AzureAD/microsoft-authentication-library-for-js#513]
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/fa8ce39c60c9a5ac277a1d8661fc6cd609d91cbb/lib/msal-angular/src/msal-guard.service.ts#L27

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/fa8ce39c60c9a5ac277a1d8661fc6cd609d91cbb/lib/msal-angular/src/msal-guard.service.ts#L52

Since the claim **name** is not required to exist in the id token (https://openid.net/specs/openid-connect-core-1_0.html#IDToken), maybe it would be better to change to something that it is required to exist, like **iss**.

In case of this claim **name** been not returned, the MsalGuard process to acquire a token silently just fails and the redirect to the identity provider takes place.

`this.authService._oauthData.userName`
The userName above comes from the **name** property in the **User** class. Maybe it could be changed to something like this:
`this.authService._oauthData.idToken.iss` in the lines above.

**Comment by navyasric** [comment]
@cleberdantas  Can you explain if there is a use case where you don't get the name claim in the id_token? The intent is to check if an authenticated user exists, so iss claim may not be the ideal option. Instead we could use the sub claim.

**Comment by cleberdantas** [comment]
@navyasric yes, agree, sub indeed is a better option.

About the use case... well ... 
![image](https://user-images.githubusercontent.com/699321/50143541-0db6a600-0294-11e9-8ef4-5eca1bd7f565.png)
I was using Given Name (given_name) not Display Name (name), so Display Name was unmarked.
I think other users may stumble in the same situation as mine, so changing **name** for **sub** would be very appreciated.

Thanks.

**Comment by sameerag** [comment]
@cleberdantas Thanks for raising this issue. I am discussing with the team if we can fix this before the Angular Wrapper sync with msal 1.0.x as this seems simple enough. Will keep you posted on the same.

Apologies for the delay, we are getting through most angular issues one by one post the core release.

**Comment by sameerag** [comment]
@DarylThayil  On further thought maybe we should modify this to check _idToken != null_ than to verify a specific claim, so we can be independent of the token contents.

```
if (!this.authService._oauthData.isAuthenticated && !this.authService._oauthData.userName)
```
would be 
```
if (!this.authService._oauthData.isAuthenticated && !this.authService._oauthData.idToken)
```

**Comment by sameerag** [comment]
#836 is fixing this.

**Comment by sameerag** [comment]
This will be pushed in the next angular patch release, currently merged to dev.
