### ISSUE TITLE
Slow Logins and Redirects using MSAL with Azure AD and B2C

### ISSUE THREAD

**Issue by udayansarma** [AzureAD/microsoft-authentication-library-for-js#5130]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

none

### Public or Confidential Client?

Public

### Description

Hello team, using MSAL js library for React for an enterprise application doing authentication and authorization. The initial attempt to authenticate using that library takes about 7 - 10 seconds to complete the redirects and the flows. Is there a guideline or benchmark defining the amount of time the library should take to complete the flow? I know that the login flow can vary based on policies and the identity provider. In this case we are using Azure AD and B2C. 

Thanks much 

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@udayansarma We don't currently have a benchmark for completing the flows. Are you able to send a Fiddler trace of this behavior?
