### ISSUE TITLE
Login reloop issue when using msal-angular wrapper

### ISSUE THREAD

**Issue by supriyaGannvi** [AzureAD/microsoft-authentication-library-for-js#5132]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.5

### Public or Confidential Client?

Public

### Description

@jasonnutter Using Angular Wrapper, after sometime when accessing the application, loginRedirect goes into loop then I have to delete cookies to make it work. What's the trick to make it work. it works fine for the first time. Appreciate your help.

### MSAL Configuration

```javascript
auth: {
      clientId: clientid
      authority: authority,
    
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE // set to true for IE 11. Remove this line to use Angular Universal
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Info,
        piiLoggingEnabled: false
      }
    }
```

### Relevant Code Snippets

```javascript
msalService.loginRedirect(singIn)
```

### Reproduction Steps

1. Logged in with properly user and did not logged out
2. Logged in after 24 hrs and logging with different user 
3. The Application looping back to multiple time until the user explicitly delete the cookies 

### Expected Behavior

once user logs in after token expiry then it should navigate to authentication screen and once he logs in the user should be login with new token 

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Edge

### Regression

@azure/msal-browser: "2.19.0"

### Source

Internal (Microsoft)

**Comment by jo-arroyo** [comment]
@supriyaGannvi Are you able to provide verbose logs of this behavior?

**Comment by supriyaGannvi** [comment]
<img width="1418" alt="133048223-36214e5e-5c39-46f7-82f3-a73ad2406dfa" src="https://user-images.githubusercontent.com/111850297/186862853-4b62f991-c764-4268-88b7-933e98c40ecb.png">

**Comment by supriyaGannvi** [comment]
@jo-arroyo this is what we get console

**Comment by jo-arroyo** [comment]
@supriyaGannvi Please send **verbose** logs. You can turn on verbose logging by changing the `logLevel` in the configurations as follows:

```js
auth: {
      clientId: clientid
      authority: authority,
    
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Verbose, // Change to Verbose here
        piiLoggingEnabled: false
      }
    }
```

**Comment by ionut-gheorghe** [comment]
I can confirm this. After the refresh token is expired (I have this issue that logs out the user even if the user has conditional access policies, 24 hours refresh token for SPA) and I try to log in the another user: redirects to the first user asking for password. You either have to delete the cookie or sign out the first user.

**Comment by supriyaGannvi** [comment]
@ionut-gheorghe  Did u got any solution for this issue

**Comment by ionut-gheorghe** [comment]
None for my 2 issues: mandatory interactive login after 24 hours and the loop when sign in a new user.

**Comment by supriyaGannvi** [comment]
@jo-arroyo could u help us how can we reslove this issue

**Comment by jo-arroyo** [comment]
@ionut-gheorghe Needing to login interactively after 24 hours is expected behavior. Refresh tokens used in single page apps and with the authorization code flow are limited to 24 hours. Once outside the 24 hour window, it is supposed to fail and require interactive login. While we recognize that this is not the best user experience, the 24 hour limit was chosen for [security reasons](https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-third-party-cookies-spas#security-implications-of-refresh-tokens-in-the-browser) for single-page apps. Please see [this document](https://docs.microsoft.com/en-us/azure/active-directory/develop/refresh-tokens#token-timeouts) about refresh tokens lifetimes and [this document](https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-third-party-cookies-spas#overview-of-the-solution) about refresh tokens and the auth code flow.

@supriyaGannvi Please provide verbose logs, per above.

**Comment by supriyaGannvi** [comment]
![Screenshot (62)](https://user-images.githubusercontent.com/111850297/190657801-fbb0c2a8-5923-4037-8c4e-556e88552226.png)

**Comment by supriyaGannvi** [comment]
![Screenshot (61)](https://user-images.githubusercontent.com/111850297/190657896-9e76386c-e06a-4319-88c2-f01f709c4553.png)

**Comment by supriyaGannvi** [comment]
@jo-arroyo i have send u the screen shot verbose logs

**Comment by jo-arroyo** [comment]
@supriyaGannvi Please upgrade to the latest versions of msal-angular and msal-browser, and let me know if you are still experiencing this behavior.

Edit: If you are still experiencing this behavior, please copy and paste the verbose logs in a comment and provide a fiddler trace, thanks.

**Comment by supriyaGannvi** [comment]
![Screenshot (62)](https://user-images.githubusercontent.com/111850297/188640553-93cfdc11-7727-4b43-9873-f718d86a0b4d.png)

**Comment by supriyaGannvi** [comment]
@jo-arroyo  
Still the issue persist and recent upgardation @azure/msal-angular :2.4.1 @azure/msal-browser : 2.28.1

**Comment by supriyaGannvi** [comment]
And this issue happens only if we are logging with different user

**Comment by supriyaGannvi** [comment]
@bmahall  could u please help how can we resolve this issue

**Comment by bmahall** [comment]
@supriyaGannvi Thanks for upgrading to recent version of msal-browser . Do you experience the looping issue with acquireTokenPopup() API as well? 
It would be more helpful if you can kindly provide the logs in a text format using notepad, in place of screenshots as suggested above too.

**Comment by bmahall** [comment]
@ionut-gheorghe Please feel free to open a separate issue in case of any further questions. Thanks!

**Comment by supriyaGannvi** [comment]
@bmahall its only happening while we are using loginRedirect

**Comment by supriyaGannvi** [comment]
@bmahall could u please help us out

**Comment by bmahall** [comment]
@supriyaGannvi Can you please share code snippet(masking any critical auth data) where you are calling loginRedirect() and handling the response?
It is possible that the application logic is improperly using the handleRedirect() Api. Please refer to this document which explains the point:- [Angular -looping when redirect](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/FAQ.md#why-is-my-app-looping-when-logging-in-with-redirect). 


You can use getActiveAccount() and setActiveAccount() APis to manage multiple accounts:-
The msal-browser instance exposes getActiveAccount() and setActiveAccount() for active accounts.

We recommend subscribing to the inProgress$ observable and filtering for InteractionStatus.None before retrieving account information with getActiveAccount(). This ensures that all interactions have completed before getting account information.

We recommend setting the active account:

After any action that may change the account, especially if your app uses multiple accounts. See [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-angular-v2-samples/angular11-sample-app/src/app/home/home.component.ts#L23) for an example of setting the account after a successful login)

Link: [Managing multiple accounts](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/FAQ.md#how-do-i-get-and-set-active-accounts). 

Please let me know if you have any questions. You can also share the source code over the email mentioned on my Github profile.

**Comment by supriyaGannvi** [comment]
@bmahall  still the issue persist

**Comment by supriyaGannvi** [comment]
@bmahall We have added the $Inprogress and handle the active account as suggest by you still we could see the login redirect issue

**Comment by supriyaGannvi** [comment]
@bmahall  could u please helps us out

**Comment by bmahall** [comment]
@supriyaGannvi Can you please share the fiddler trace and verbose logs on the email on my Git profile? Thanks

**Comment by bmahall** [comment]
@supriyaGannvi Meanwhile , please refer to a couple of points : -
1. Are you able to reproduce the behavior with local Storage , rather than session storage? 
2. Please confirm the version(s) of msal-angular with which you are facing this issue
3. Redirects must be handled either with the MsalRedirectComponent or with calling handleRedirectObservable(). See our docs on redirects [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-angular/docs/v2-docs/redirects.md) for more information. Additionally, any interaction or account validation should be done after subscribing to the inProgress$ observable and filtering for InteractionStatus.None. 
   For more details on the above, please refer to the [sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/30b5ff95e2ff2cc827d98118004d92968bb67b3f/samples/msal-angular-v2-samples/angular11-sample-app/src/app/app.component.ts#L27)

Kindly share your source code wherein you are calling loginRedirect on my email. 
Thanks for your patience!

**Comment by supriyaGannvi** [comment]
this is snipped code 


 this.msalBrodcastService.msalSubject$
      .pipe(
        filter(
          (msg: EventMessage) =>
            msg.eventType === EventType.LOGIN_SUCCESS ||
            msg.eventType === EventType.LOGOUT_START
        )
      )
      .subscribe(({ eventType }: EventMessage) => {
        if (eventType === EventType.LOGIN_SUCCESS) {
          this._isAuthenticated.next(true);
        } else {
          this._isAuthenticated.next(false);
        }
      });

    this.msalBrodcastService.inProgress$
      .pipe(filter((status: InteractionStatus) => status === InteractionStatus.None))
      .subscribe(() => {
        this.setLoginDisplay();
      });
  }

  /**
   * function to represent the login Disaply
   */
  setLoginDisplay = () =>
    (this.loginDisplay =
      this.authService.instance.getAllAccounts().length >
      DefaultNumberInitializableConstants.ZERO);

  /**
   * Login using MSAL
   * @param popup Should the login happen using popup or redirect
   * @returns Observable with either void or AuthenticationResult
   */
  onLogin(popup: boolean = false): Observable<void | AuthenticationResult> {
    if (popup) {
      return this.authService.loginPopup();
    } else {
      return this.authService.loginRedirect();
    }
  }

**Comment by bmahall** [comment]
@supriyaGannvi Please use the following code in place of ` this.msalBrodcastService.inProgress$
  .pipe(filter((status: InteractionStatus) => status === InteractionStatus.None))
  .subscribe(() => {
    this.setLoginDisplay();
  });`

`
    this.msalBroadcastService.inProgress$
      .pipe(
        filter((status: InteractionStatus) => status === InteractionStatus.None),
        takeUntil(this._destroying$)
      )
      .subscribe(() => {
        this.setLoginDisplay();
        this.checkAndSetActiveAccount();
      })
  }

  setLoginDisplay() {
    this.loginDisplay = this.authService.instance.getAllAccounts().length > 0;
  }

  checkAndSetActiveAccount(){
    /**
     * If no active account set but there are accounts signed in, sets first account to active account
     * To use active account set here, subscribe to inProgress$ first in your component
     * Note: Basic usage demonstrated. Your app may require more complicated account selection logic
     */
    let activeAccount = this.authService.instance.getActiveAccount();

    if (!activeAccount && this.authService.instance.getAllAccounts().length > 0) {
      let accounts = this.authService.instance.getAllAccounts();
      this.authService.instance.setActiveAccount(accounts[0]);
    }
  }
`

**Comment by supriyaGannvi** [comment]
@bmahall  we cannot add the $destory for the service

**Comment by tnorling** [comment]
> @bmahall we cannot add the $destory for the service

Why not? Can you also please confirm that you are handling the redirect response as described by @bmahall above? Are you able to reproduce your issue with one of our samples [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples)?
