### ISSUE TITLE
Ability to not use cache for serverless applications?

### ISSUE THREAD

**Issue by SandonAhoy** [AzureAD/microsoft-authentication-library-for-js#5140]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

2.14.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Confidential

### Description

I am running a [serverless](https://www.serverless.com/) application.

I am using msal-node to acquire a token, which is then passed to the microsoft graph client ( @microsoft/microsoft-graph-client ) like this tutorial here: https://docs.microsoft.com/en-us/graph/tutorials/node?tutorial-step=3

However in that example the local token cache is used to find the account and acquireTokenSilent is used which is supposed to transparently handle token refresh.

Ideally I'd like to be able to store the refresh token in the database but that doesn't seem to be possible. In a serverless application where it may be restarted at any time, what is the correct way to store, retrieve, and pass tokens to the graph client?

Thanks

### MSAL Configuration

```javascript
{
    auth: {
        clientId: myMsConfig.clientID,
        authority: myMsConfig.authority,
        clientSecret: myMsConfig.clientSecret
    },
    system: {
        loggerOptions: {
            loggerCallback(logLevel: number, message: string) {
                logger(logLevel, message);
            },
            piiLoggingEnabled: false,
            logLevel: LogLevel.Verbose,
        }
    },
}
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by bgavrilMS** [comment]
@derisen - are there any existing docs around this? Do we support distributed caching for web site scenario or only for client_credential scenario?

**Comment by derisen** [comment]
@bgavrilMS we've only demoed distributed caching for web app scenarios so far. @SandonAhoy you should be able to store the cache in a database using a custom cache plugin -see the [caching doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/caching.md) for more. The example [RedisTestApp](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/RedisTestApp) shows how to use Redis as a distributed token cache store in a web app, but you should be able to use another db instead. Let us know if you run into any issues.

**Comment by SandonAhoy** [comment]
This seems to work thanks.

For future reference you want something like this:

```        
cache: {
    cachePlugin: {
        beforeCacheAccess: async (cacheContext) => {
            const tokens = await getTokensFromDb()
            const dbCache = tokens ? tokens : ''
            cacheContext.tokenCache.deserialize(dbCache);
        },
        afterCacheAccess: async (cacheContext) => {
            if (cacheContext.cacheHasChanged) {
                const cache = cacheContext.tokenCache.serialize() as unknown as MicrosoftCacheObject
                await putTokensInDb(cache)
            }
        }
    }
}
```
