### ISSUE TITLE
GitHub Enterprise Rest API authenticate with MSAL

### ISSUE THREAD

**Issue by byunru** [AzureAD/microsoft-authentication-library-for-js#5149]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Public or Confidential Client?

Public

### Description

Request an example for call GitHub Enterprise Rest API and authenticate with MSAL

### Source

External (Customer)

**Comment by tnorling** [comment]
@byunru You can find our Msal-Angular samples [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples) which will show you how to obtain an access token for MS Graph. You may need to consult the documentation or samples provided by Github for specific usage of that API and make the necessary changes.
