### ISSUE TITLE
Ionic - Cordova application

### ISSUE THREAD

**Issue by phyr0s** [AzureAD/microsoft-authentication-library-for-js#5150]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Public or Confidential Client?

Public

### Description

Allow to use msal-angular using ionic-cordova based application

-> 
https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5052

https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4290

### Source

External (Customer)

**Comment by tnorling** [comment]
@phyr0s We do not currently support Cordova, Capacitor or any hybrid framework. We do have this on our backlog for future consideration but unfortunately do not have an ETA at this time. You can track updates to that feature request in #4290. Closing this as duplicate for now.
