### ISSUE TITLE
Token retrieval error after changing password

### ISSUE THREAD

**Issue by himesha-wijekoon** [AzureAD/microsoft-authentication-library-for-js#5153]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.22.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.1.1

### Public or Confidential Client?

Public

### Description

We implemented the password change policy as given in the example below.

https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack/tree/main/scenarios/password-change

However, in some cases, we get the following error when the user is redirected to the application after changing the password.

{
  "error": "invalid_grant",
  "error_description": "AADB2C90088: The provided grant has not been issued for this endpoint. Actual Value : B2C_1A_Dev_SignupSignin and Expected Value : B2C_1A_Dev_PasswordChange\r\nCorrelation ID: b3a2fdd5-df58-4aa1-8eca-d91503ebb75a\r\nTimestamp: 2022-08-31 12:23:48Z\r\n"
}

This error does not happen to all users. But for some users, it happens always.

### Error Message

{
  "error": "invalid_grant",
  "error_description": "AADB2C90088: The provided grant has not been issued for this endpoint. Actual Value : B2C_1A_Dev_SignupSignin and Expected Value : B2C_1A_Dev_PasswordChange\r\nCorrelation ID: b3a2fdd5-df58-4aa1-8eca-d91503ebb75a\r\nTimestamp: 2022-08-31 12:23:48Z\r\n"
}

### MSAL Configuration

```javascript
export function MSALInstanceFactory(): IPublicClientApplication {
  return new PublicClientApplication({
    auth: {
      authority: environment.b2cPolicies.authorities.signUpSignIn.authority,
      clientId: environment.clientId,
      knownAuthorities: [environment.b2cPolicies.authorityDomain],
      navigateToLoginRequestUrl: true,
      postLogoutRedirectUri: '/',
      redirectUri: '/',
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE,
    },
    system: {
      loggerOptions: {
        logLevel: environment.msalLoggerLevel,
        loggerCallback,
        piiLoggingEnabled: true,
      },
    },
  });
}
```

### Relevant Code Snippets

```javascript
changePassword(): void {
    const changePasswordFlowRequest: RedirectRequest = {
      authority: environment.b2cPolicies.authorities.changePassword.authority,
      extraQueryParameters: {
        p: environment.b2cPolicies.names.changePassword,
        ui_locales: (
          this.translateService.currentLang ?? SupportedLocale.EN
        ).toLowerCase(),
      },
      scopes: ['openid'],
    };

    this.login(changePasswordFlowRequest);
  }
```

### Reproduction Steps

1. Log in to the application
2. Change password using the password change policy
3. When returning to the application after successfully changing the password, the token cannot be retrieved as an error occurs.

### Expected Behavior

The user should be able to get the token after changing the password.

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge

### Source

External (Customer)

**Comment by tnorling** [comment]
@himesha-wijekoon Could you please email me (email on my profile) a network trace showing this behavior? Thanks!

**Comment by himesha-wijekoon** [comment]
I emailed @tnorling the trace as he requested and now waiting for his feedback.

**Comment by tnorling** [comment]
@himesha-wijekoon I've reviewed the trace - this is happening because somewhere in your application you are calling `acquireTokenSilent` with authority = your signUpSignIn policy & account = the account associated with your passwordReset policy. This results in an attempt to redeem the refresh token associated with your password reset policy for a token from your signInSignUp policy which is not allowed.

**Comment by himesha-wijekoon** [comment]
@tnorling Thanks for investigating this. However this call is made by the MSAL library, not by our code as per my understanding. It only happens for random users. Do you have any clues to find why it can only happen for specific users only?

**Comment by tnorling** [comment]
@himesha-wijekoon You should check to see where you are configuring your token requests and ensure that if you are providing an account on the request that it matches the authority. If you are not providing an account on the request the only other possibility is that you are using the `setActiveAccount` APIs. If this is the case you need to ensure that the active account matches the authority you're trying to use.
