### ISSUE TITLE
After loginRedirect success, no active account exists

### ISSUE THREAD

**Issue by danielvoigt** [AzureAD/microsoft-authentication-library-for-js#5155]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.28.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.4.1

### Public or Confidential Client?

Public

### Description

After successfully logging with AD B2C using the `loginRedirect` method and getting redirected back to the SPA, MSAL is unable to retrieve the active account of the user. So ultimately the login fails.

Following the documentation for using `loginRedirect` with `msal-angular`: https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-angular-auth-code

Steps to reproduce:
1. use the loginRedirect method to initiate the login flow (`MsalService.loginRedirect()`)
2. subscribe to the `LOGIN_SUCCESS` event on the component that is the redirectUri. For example
```
  ngOnInit(): void {
    this.msalBroadcastService.msalSubject$
      .pipe(
        filter((msg: EventMessage) => msg.eventType === EventType.LOGIN_SUCCESS),
      )
      .subscribe((result: EventMessage) => {
        // the error is here - no active account
        const isLoggedIn =  this.msalService.instance.getActiveAccount() === null // this should be true, but it isn't working
        console.log(result);
      });
  }
```
3. There should be an active account available after the subscription for the `LOGIN_SUCCESS` events receives an event message on login success - but there isn't. The `getActiveAccount` method returns `null`.

Notes:
- I have used the same configuration to successfully login with the `MsalService.loginPopup` method, so the configuration of the SPA shouldn't be an issue. However, there are currently blocking bugs with the loginPopup flow, as it doesn't work with MacOS in full-screen mode and there are also reports of the flow not working on iOS, so that's currently not usable. Issues: #5123 #4921
- I have experienced a similar issue with `msal-browser` where after a successful AD B2C login there is no active account, and thus the login fails. That's essentially the same behavior that is happening here, just different code. That is documented in this unresolved issue: #4935
- This is the third attempt at getting MSAL for B2C to work. We first attempted to get `msal-browser` to work, then loginPopup with `msal-angular`, and now `msal-angular` with loginRedirect. We've experienced unresolved issues for all these MSAL B2C flows.

### Error Message

No error messages, but the user is not successfully logged in with an active account after a successful `loginRedirect` and 

### MSAL Configuration

```javascript
{
    auth: {
      clientId: 'uuid-goes-here',
      authority:
        'https://company-name.b2clogin.com/company-name.onmicrosoft.com/B2C_1_SignInOnly',
      redirectUri: 'http://localhost:4200',
      knownAuthorities: ['company-name.b2clogin.com'],
      postLogoutRedirectUri: 'http://localhost:4200',
      navigateToLoginRequestUrl: true,
    },
  }
```

### Relevant Code Snippets

```javascript
see description
```

### Reproduction Steps

see description

### Expected Behavior

on the `LOGIN_SUCCESS` event, you should be able to retrieve an active account and be successfully logged in.
the `MsalService.getActiveAccount` method should not be `null`

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by tnorling** [comment]
@danielvoigt Where are you setting the active account?

**Comment by Core121** [comment]
You have to do something like this, since for some reason setting the active account isn't something MSAL handles.

```
this.msalBroadcastService.inProgress$
      .pipe(
        filter((status: InteractionStatus) => status === InteractionStatus.None),
        takeUntil(this._destroying$)
      )
      .subscribe(() => {
        this.checkAndSetActiveAccount();
      })

checkAndSetActiveAccount() {
    let activeAccount = this.msalService.instance.getActiveAccount();

    if (!activeAccount && this.msalService.instance.getAllAccounts().length > 0) {
      let accounts = this.msalService.instance.getAllAccounts();
      this.msalService.instance.setActiveAccount(accounts[0]);
    }
  }

```

If you have any more trouble check out [this example](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular14-rxjs7-sample-app)

**Comment by bmahall** [comment]
@danielvoigt Are you still facing any issues in setting active account?

**Comment by hgc10120** [comment]
Yes. I can confirm that this is still an issue that requires a workaround.

**Comment by deckerdent** [comment]
Just ran into it so yes, it's still an issue. Would really like to know why it is designed like this, doesn't seem to be unintentionally
