### ISSUE TITLE
No refresh token in acquireTokenOnBehalfOf response

### ISSUE THREAD

**Issue by itstaby** [AzureAD/microsoft-authentication-library-for-js#5165]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.12.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Confidential

### Description

I'm working on a Teams app and integrating Graph API into some of the server side operations.

I first use the Teams SDK to request a token with the required scopes on the app client with an explicit consent dialog.

I then serve that token to the server side and use the MSAL Node OBO exchange `acquireTokenOnBehalfOf` to get the relevant Graph API token and then encrypt and store in the DB.
I noticed that these token have an expiry of 1 hour, and I don't get a refresh token to renew them.

This is a problem because acquiring Graph API related scopes using the Teams SDK requires an explicit consent dialog, and I can't display that to my users every 24 hours.

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by tnorling** [comment]
We intentionally do not return the refresh token on any of our APIs. See [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/faq.md#how-do-i-get-the-refresh-token). When you need a new access token you should call `acquireTokenSilent` and MSAL.js will use its stored refresh token, if available, to get it for you.

**Comment by bgavrilMS** [comment]
CC @Robbie-Microsoft as FYI

**Comment by itstaby** [comment]
The documentation [here](soft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/acquire-token.md#acquiring-an-access-token) states that silent acquisition works by using the user session and an invisible iframe, but I'm doing OBO on the backend as per [these](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-graph-api?tabs=nodejs#configure-code-to-fetch-access-token-using-msal) set of instructions for teams apps.  I cannot use pop-ups or redirects within the teams client, and I'm restricted to using the Teams SDK authentication mechanism on the client side and using the generated AAD token to exchange for a Graph API token on the server side with `acquireTokenOnBehalfOf`.

If I cannot store and refresh these tokens as needed, would the recommended approach here be to exchange for a new token every time I need to talk to Graph API?

Internal MSAL client cache or token refresh doesn't work for me because I will have many server instances and I cannot rely on which server instance ends up receiving the request.

**Comment by bgavrilMS** [comment]
OBO flow is for web APIs, so it expected that there is no UI / invisible iframe or anything like that. See token caching https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/caching.md - it shows how to persist the "whole" cache. If you don't persist it, MSAL will store it in memory.

MSAL js does not have documentation around distributed token caching yet, which I think is what you'd want here. 

Recommendation for a service at scale would be to not rely on token caching right now for OBO. Just cache the access token if you need to make multiple calls to Graph API. If the token is close to expiry or does not exist, invoke `acquireTokenOnBehalfOf` [again].

**Comment by itstaby** [comment]
Sounds good. Thanks for the guidance!
