### ISSUE TITLE
How do you re-validate the token for session management?

### ISSUE THREAD

**Issue by DewangS** [AzureAD/microsoft-authentication-library-for-js#5187]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.13.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

NA

### Public or Confidential Client?

Public

### Description

I have a single page React app. I use this @azure/msal-browser package's loginPopup() API to let my app user login using their Azure AD credentials. Once successfully signed in, their login data e.g. access token etc gets stored in the local storage.

My question is how do I check the validity of the access token for the. session? i.e. if the token has passed its expiration time? Do I can see the MSAL response does have "exp": 1662430649, (Unix timestamp) value of expiration. Do I save this in the local storage and check\update on each user interaction or save session data in the backend database and do the validations? Does the MS Graph API or the @azure/msal-browser package provides any API to validate the expiry of the token?

### MSAL Configuration

```javascript
Not relevant to my question
```

### Relevant Code Snippets

```javascript
Not applicable
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by derisen** [comment]
@DewangS client apps shouldn't build logic around claims in an access token. Token validation is to be done by the resource server (your backend, MS Graph etc.). The correct pattern is to always call msal's `acquireToken*` before you make a call to a resource server, and msal will do it's best to return a fresh access token to you.

**Comment by bmahall** [comment]
@DewangS As suggested above, you don't need to manually check token validity and should use acquireTokenSilent  API . 
For more information, refer to [Token Lifetimes](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/token-lifetimes.md)

**Comment by DewangS** [comment]
Thanks @derisen  and @bmahall  though the question was, is there an API in this package (and in MS Graph) to validate the existing token which was acquired from the initial login and also some kind of flag if it has expired. Saves me from creating database based persistence and session time management.

**Comment by bmahall** [comment]
@DewangS I see, are you trying to validate an Access Token for MS-Graph or for your own custom API?

**Comment by DewangS** [comment]
@bmahall My app uses MS Graph API when user tries to initially login. It authenticates them against the Azure AD. This is all working though I need to manage sessions i.e. user should be re-directed to the login page if their idToken expired. I can see the response from MS Graph API suing this NPM package, returns expiry date\time in Unix date\time format though I want to use any other API from MS Graph using this NPM package if it can re-validate the already acquired token.

**Comment by derisen** [comment]
@DewangS just to clarify a few things:

- The ID token is only meant for your client application. It should not be used for accessing a web API (Microsoft Graph will not accept an ID token in any case).
- If you need to manage user session in your app based on ID token expiry, you should look at the [exp claim](https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens#payload-claims) in the token, and compare this with the current time. Specifics of this depends on your app. For instance, if you were to build a React app, you could have a component that wraps the rest of your component tree and run this check on component load each time, prompting a sign-in if the token is expired.
- The access token you've sent to MS Graph API will be validated by the Graph API itself. You as a developer are only responsible for calling one of MSAL's `acquireToken `APIs beforehand, and then pass the obtained access token to your Graph API call. For instance:

```javascript
const myMSALObj = new msal.PublicClientApplication({
     // your app configuration
});

myMSALObj.acquireTokenPopup({
     scopes: ["User.Read"]
}).then(response => {
    const headers = new Headers();
    const bearer = `Bearer ${response.accessToken}`;

    headers.append("Authorization", bearer);

    const options = {
        method: "GET",
        headers: headers
    };

    fetch("https://graph.microsoft.com/v1.0/me", options)
        .then(response => response.json())
        .then(response => {
              // do something with the response
        })
}).catch(error => {
      console.error(error);
});
```

**Comment by DewangS** [comment]
Thanks @derisen . Correct, I am just using MS Graph for the initial auth against our AD. Not using pr planning to use any other MS Graph APIs. At the moment, I am successfully logging in user and storing their session details in the local storage.. just their userid and the idtoken. I can also convert and store the token expiry date\time in the local storage and validate against each request though I guess I need to update the storage with a new expiry date\time each time the user successfully uses any protected routes\feature of my web app.

**Comment by bmahall** [comment]
@DewangS Thanks for elaborating further. As @derisen  mentioned above, the idToken is not tied to the web resource that you are trying to access. 
In order to renew id tokens, you need to use acquireTokenSilent with the client-id of your application as the scope. This api will automatically fetch a valid IdToken for you in case of expiration. 

If the session is not valid at that point, Msal will throw an error. You can then catch the error & use acquireTokenRedirect() or acquireTokenPopup() for renewing the token. 
Since the Access token lifetime is 1h, you can also make sure you call the ATS api every hour, to maintain the session. 

Please let us know in case you have any further questions.

**Comment by DewangS** [comment]
Thanks @bmahall for the detailed explanation. For now I've just implemented local session management i.e. if the session is idle for a set amount of time, user gets logged out.
