### ISSUE TITLE
Use credentials obtained by msal-node for e2e tests on msal-angular

### ISSUE THREAD

**Issue by rafagsiqueira** [AzureAD/microsoft-authentication-library-for-js#5192]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular), MSAL Node Extensions (@azure/msal-node-extensions)

### Public or Confidential Client?

Public, Confidential

### Description

Most test runners allow running a global script to populate browser session storage before running tests. 
This could allow a scenario where a confidential client could be used to get credentials to populate the session storage to run e2e tests.
I couldn't find a way to populate the session storage with all the information necessary for msal-guard and msal-interceptor to work with the cached credentials. Is this possible?

### Source

External (Customer)

**Comment by bmahall** [comment]
@rafagsiqueira Please refer to this [sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/2771) that illustrates how to use msal-node ROPC flow in test environment to obtain cached credentials that can be used for e2e testing . Please note ROPC is meant to be used for testing only and not in prod environment.

**Comment by rafagsiqueira** [comment]
@bmahall I tried a similar approach with @azure/msal-node ConfidentialClientApplication, but msal guard doesn't recognize the user as authenticated. Upon inspecting the local storage, I noticed that homeAccountId = "". Is that the reason? Does that mean acquiring the access token with ConfidentialClientApplication is not supported?

**Comment by sameerag** [comment]
@rafagsiqueira What happens if you acquire tokens with msal-node as a `Public Client` app and try the same use case? Does that work?
