### ISSUE TITLE
Cross-origin token redemption is permitted only for the 'Single-Page Application' client-type

### ISSUE THREAD

**Issue by diamantisufi** [AzureAD/microsoft-authentication-library-for-js#5196]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.28.2

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.6

### Public or Confidential Client?

Confidential

### Description

Hi guys, I'm getting this error while trying to login with 'popup' interaction.

Cross-origin token redemption is permitted only for the 'Single-Page Application' client-type. Request origin: 'http://localhost:3000'.

Is there a way I can pass an extra property request origin to the request?

### MSAL Configuration

```javascript
export const b2cPolicies = {
    names: {
        signUpSignIn: "B2C_1_SISOPolicy",
        editProfile: "B2C_1_ProfileEditPolicy"
    },
    authorities: {
        signUpSignIn: {
            authority: "https://login.microsoftonline.com/tfp/msidlabb2c.onmicrosoft.com/B2C_1_SISOPolicy"
        },
        editProfile: {
            authority: "https://login.microsoftonline.com/tfp/msidlabb2c.onmicrosoft.com/B2C_1_ProfileEditPolicy"
        }
    },
    authorityDomain: "login.microsoftonline.com"
}

// Config object to be passed to Msal on creation
export const msalConfig = {
    auth: {
        clientId: process.env.REACT_APP_AZURE_CLIENT_ID,
        authority: b2cPolicies.authorities.signUpSignIn.authority,
        knownAuthorities: [b2cPolicies.authorityDomain],
        redirectUri: process.env.REACT_APP_AZURE_REDIRECT_URI,
        postLogoutRedirectUri: process.env.REACT_APP_AZURE_POSTLOGOUT_REDIRECT_URI
    },
    cache: {
        cacheLocation: "localStorage",
        storeAuthStateInCookie: isIE || isEdge || isFirefox
    },
    system: {
        loggerOptions: {
            loggerCallback: (level, message, containsPii) => {
                if (containsPii) {	
                    return;	
                }
                switch (level) {	
                    case LogLevel.Error:	
                        console.error(message);	
                        return;	
                    case LogLevel.Info:	
                        console.info(message);	
                        return;	
                    case LogLevel.Verbose:	
                        console.debug(message);	
                        return;	
                    case LogLevel.Warning:	
                        console.warn(message);	
                        return;	
                    default:
                        return;
                }
            }
        }
    }
};
```

### Relevant Code Snippets

```javascript
<MsalProvider instance={msalInstance}>
                <MsalAuthenticationTemplate 
                    interactionType={InteractionType.Popup} 
                    authenticationRequest={authRequest} 
                    errorComponent={ErrorComponent} 
                    loadingComponent={LoadingComponent}
                >
                    <div>Profile Content</div>
                </MsalAuthenticationTemplate>
            </MsalProvider>
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by sameerag** [comment]
@diamantisufi Is your application type `web`? Can you change the app-type to `SPA` in the [portal](https://ms.portal.azure.com/#home) and let us know if the login works?

**Comment by sameerag** [comment]
Also I see the app type is set as `Confidential`. React is supported only for browser apps which are `PublicClient`.

**Comment by diamant-isufi-sveasolar** [comment]
@sameerag could you guide me on how to change the app-type and PublicClient.

**Comment by sameerag** [comment]
@derisen Do we have docs demonstrating this?

@diamantisufi In your app registration, there is a left blade for `Authentication`:

> Authentication Blade

<img width="275" alt="AuthenticationBlade" src="https://user-images.githubusercontent.com/21958742/190212780-0b345a07-3cc7-426c-b2de-e9ce01e327ce.png">

Once you go to the screen it has an option to `Add a platform` and you should be able to add the `SPA` type.
Hope this helps.

**Comment by sameerag** [comment]
Did this solve your issue @diamantisufi?

**Comment by sameerag** [comment]
Closing this, please open a new issue if you still have questions.

**Comment by diamantisufi** [comment]
@sameerag it solved my issue, thanks!

**Comment by adudiapis** [comment]
@sameerag Worked for me too. Thanks! 
But I am curious to know if a hosting platform makes any difference, because previous web app config worked Heroku but failed on EKS. Changing to SPA worked on EKS. Very strange.
