### ISSUE TITLE
Content overflow on login screen - Electron

### ISSUE THREAD

**Issue by rbWies** [AzureAD/microsoft-authentication-library-for-js#5205]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

2.14.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

2.0.0-beta.0

### Public or Confidential Client?

Public

### Description

When creating a new browserwindow object in electron the login page content has an overflow, showing a scrollbar. The scrollbar only moves a tiny amount up and down. Would be better to remove it.

### Error Message

No error message, just unintended behavior.

### Msal Logs

No logs.

### MSAL Configuration

```javascript
const MSAL_CONFIG = {
  auth: {
    clientId: 'REDACTED',
    authority: `https://login.microsoftonline.com/REDACTED`,
    // clientSecret: 'REDACTED',
    redirectUri: 'msal://redirect',
  },
  system: {
    loggerOptions: {
      loggerCallback(loglevel, message, containsPii) {
        console.log(message);
      },
      piiLoggingEnabled: false,
      logLevel: LogLevel.Verbose,
    },
  },
};
```

### Relevant Code Snippets

```javascript
ipcMain.handle('login', async () => {

  // create a new electron window
  const authWindow = new BrowserWindow({
    width: 800,
    height: 600,
    show: true,
    frame: false,
    webPreferences: {
      nodeIntegration: false,
    },
  });
  // get token
  const tokenRequest = {
    scopes: [
      'User.Read',
      'Tasks.Read',
      'Group.ReadWrite.All',
      'Directory.ReadWrite.All',
    ],
  };
  const token = await authProvider.getToken(authWindow, tokenRequest);

  // close the auth window
  authWindow.destroy();

  return 'succeeded';
});
```

### Reproduction Steps

This behavior is present in the example app ms-identity-javascript-nodejs-desktop-main

### Expected Behavior

New browserwindow object opens login page without scrollbars (overflow hidden)

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Other

### Source

External (Customer)

**Comment by derisen** [comment]
@rbWies thanks for catching this! I've created a new [issue in the sample repo itself](https://github.com/Azure-Samples/ms-identity-javascript-nodejs-desktop/issues/10) instead. Will try to reproduce this and respond accordingly. Closing this one.
