### ISSUE TITLE
Is is possible to set token validation "clockSkew" in @azure/msal-browser lib?

### ISSUE THREAD

**Issue by zhongsp** [AzureAD/microsoft-authentication-library-for-js#5206]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.28.2

### Wrapper Library

Not Applicable

### Wrapper Library Version

N/A

### Public or Confidential Client?

Public

### Description

How to set the `clockSkew` setting for token expiration validation in `@azure/msal-browser` lib?
If it's not supported, what's the reason? Thanks.

### MSAL Configuration

```javascript
N/A
```

### Relevant Code Snippets

```javascript
N/A
```

### Source

External (Customer)

**Comment by sameerag** [comment]
@zhongsp Yes, it is. You can set `system.tokenRenewalOffsetSeconds` in your  msal `Configuration` to achieve this. 

```js
msalConfig = {
    auth: {
        clientId: "enter_client_id_here",
        ....
    },
    cache: {
        cacheLocation: "sessionStorage",
        ....
    },
    system: {
        tokenRenewalOffsetSeconds: xx;
    }
}
```

Hope this helps.

**Comment by zhongsp** [comment]
@sameerag Thanks, it helps a lot!
