### ISSUE TITLE
Resolve 2 HIGH severity VULNERABILITIES

### ISSUE THREAD

**Issue by drcrook1** [AzureAD/microsoft-authentication-library-for-js#5207]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL React (@azure/msal-react)

### Public or Confidential Client?

Public

### Description

Just feels wrong to be installing a security focused sample and on a fresh install of it I get a big red warning that says I now have 2 high severity vulnerabilities.

<img width="787" alt="image" src="https://user-images.githubusercontent.com/6099287/189979645-a0fd0415-6838-48f2-a8f4-5b3b8f1c6e7b.png">

### Source

Internal (Microsoft)

**Comment by drcrook1** [comment]
If I install the dependencies for the router example, I increase my HIGH SEVERITY VULNERABILITY count to 6
<img width="691" alt="image" src="https://user-images.githubusercontent.com/6099287/189983530-cc521a29-e0fc-4260-8f99-00d6a714733e.png">

**Comment by sameerag** [comment]
@drcrook1 We will address this asap. We have a periodic check point to resolve these in general, I will track this ticket to make these changes.

**Comment by drcrook1** [comment]
Might be related to this: https://overreacted.io/npm-audit-broken-by-design/ if it is, it is an unfortunate situation that hopefully can be resolved at the ecosystem level.

**Comment by drcrook1** [comment]
the 6 vulnerabilities are a cumulative counting based on the dependency chain which starts at react-scripts which is a build time tool.  Its worth further investigation but the "high" severity is probably a bit ambitious of a mention from the tooling.  So _really_ this appears to be only a single vulnerability which is deep in the dependency tree of the build tooling used for this project.  The specific vulnerability is poor performance in regex expressions and this library is not used in the final output of the app.  

What it does do though is condition us to start ignoring these vulnerability flags.

**Comment by derisen** [comment]
@drcrook1 as you found out, these vulnerabilities are coming from the `react-scripts` package, and are essentially false positives.  Here is [the notice from the devs](https://github.com/facebook/create-react-app/issues/11174#issue-935928547). I've made a note to move it into `devDependencies` section. If you are running into issues in CI/CD, you should use `npm audit --production` instead of `npm audit` in your worklfow.

**Comment by drcrook1** [comment]
On the learning path for node here, npm audit --production produces the same result still, I'm sure its some kind of config issue I'll resolve later.  

For now, I'm content enough knowing its a false positive.  It might be worth documenting this though in the docs because I think a lot of folks will probably have the same initial reaction I did but may not necessarily research it further to this conclusion.
