### ISSUE TITLE
how to implement promptless logout with msal

### ISSUE THREAD

**Issue by aNyMoRe0505** [AzureAD/microsoft-authentication-library-for-js#5210]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.28.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.5

### Public or Confidential Client?

Public

### Description

Hello, I am using Azure AD B2C custom policy to implement sign-in, sign-up flow

I want to implement [promptless logout](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md#promptless-logout) in my app and the document indicate that I need to enable [login_hint optional claim](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims#v10-and-v20-optional-claims-set) for ID Tokens

It seems that the document is for Azure AD not Azure AD B2C. According to the doumcnet, for B2C, I need to configure by modifying the application manifest and I can find more info [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/configure-user-input?pivots=b2c-custom-policy)

But I still don't know how to enable login_hint to my ID Token.

Is it possible with azure ad b2c custom policy ? if it is possible, how to do that ? Is there any limitation ?

many thanks !

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by sameerag** [comment]
@aNyMoRe0505 We do not have support for this in B2C yet. There is an open feature request on the service team regarding the same, and I tagged this issue with the same ticket

The idea is to enable a user send `logout_hint` to the `logout_endpoint` which enables logout without the screen selection of the user account (as it is today).

**Comment by sameerag** [comment]
Hey @aNyMoRe0505 , on a second check, I believe this is possible with B2C by passing an `id_token_hint` to the `logout endpoint`. Please check the issue #3569 for details.

**Comment by aNyMoRe0505** [comment]
@sameerag Thank for your reply

I tried to pass `idToken` which from `acquireTokenSilent` response in logoutPopup function

```
          await instance.logoutPopup({
            idTokenHint: 'idToken from acquireTokenSilent',
          });
```

But it still popup a modal to logout, I think I misunderstand something... 🤔 

BTW, the issue https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/3569 you mentioned, it seems that `idToken` will expose in account object now, but I log my account object and I find it only contain `idTokenClaims `

---

sorry, I just misunderstand, I check the document again

**Note: Depending on the API you choose (redirect/popup), the app will still redirect or open a popup to terminate the server session. The difference is that the user will not see or have to interact with the server's account picker prompt.**

I thought if I passed `idTokenHint` then user won't see any popup..

so this is used when user login multiple account right ?

**Comment by sameerag** [comment]
> so this is used when user login multiple account right ?

Yes. And not necessarily that, eSTS also renders an account selection page even if there is a single account unless you pass t
the `id_token_hint` which is the `idToken` for B2C use cases.

> I thought if I passed idTokenHint then user won't see any popup.

Nope. As you highlighted above, the `id_token_hint` addresses the server interaction only.

**Comment by aNyMoRe0505** [comment]
@sameerag  thank you, I have no further questions, let me close this issue
