### ISSUE TITLE
BrowserAuthError: monitor_window_timeout instead of InteractionRequiredAuthError when the refresh token expires

### ISSUE THREAD

**Issue by mariiasonina** [AzureAD/microsoft-authentication-library-for-js#5222]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.28.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.5

### Public or Confidential Client?

Public

### Description

I faced a problem with receiving the real InteractionRequiredAuthError (which I can see in the network tab: "error":"invalid_grant") after the refresh token expires. Instead of this, I'm getting BrowserAuthError: monitor_window_timeout:
<img width="352" alt="2022-09-16_12h49_40" src="https://user-images.githubusercontent.com/55025379/190613830-7803ea64-cebb-42f9-a8d4-32af9a8adabd.png">
For that reason I can't use condition "err instanceof InteractionRequiredAuthError" to call an interactive method when acquireTokenSilent fails. Since I do not use this condition, the user makes an interactive login to the application with any error and after that in the network tab I see 2 requests to get tokens, one of which fails again with the same error and I get a second interactive login request, after which everything works correctly: 
<img width="497" alt="image" src="https://user-images.githubusercontent.com/55025379/190616455-d3a6c495-2675-421c-918c-efe9e91f2c15.png">
The solutions I found [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/errors.md#monitor_window_timeout) didn't help.
For calling api with access token I use axios interceptors.

Can you please help me to solve this problem?
Thanks.

### MSAL Configuration

```javascript
export const msalConfig = {
	auth: {
		clientId: process.env.REACT_APP_CLIENT_ID,
		authority: `${'https://login.microsoftonline.com'}/${process.env.REACT_APP_TENANT}`,
		redirectUri: 'http://localhost:3000/blank.html',
		postLogoutRedirectUri: '/',
		navigationToLoginRequestUrl: true,
	},
	cache: {
		cacheLocation: 'sessionStorage',
		storeAuthStateInCookie: false,
	},
	system: {
		loggerOptions: {
			loggerCallback: (level: LogLevel, message: string, containsPii: boolean): void => {
				if (containsPii) {
					return;
				}
				switch (level) {
					case LogLevel.Error:
						console.error(message);
						return;
					case LogLevel.Info:
						console.info(message);
						return;
					case LogLevel.Verbose:
						console.debug(message);
						return;
					case LogLevel.Warning:
						console.warn(message);
						return;
				}
			},
		},
		piiLoggingEnabled: false,
	},
    windowHashTimeout: 15000,
    iframeHashTimeout: 15000,
};

export const loginRequest = {
	scopes: [`api://${process.env.REACT_APP_CLIENT_ID}/user_impersonation`, 'offline_access'],
};
```

### Relevant Code Snippets

```javascript
export const msalInstance = new PublicClientApplication(msalConfig);

export const acquireToken = async (): string => {
	const activeAccount = msalInstance.getAllAccounts()[0];
	const requestConfig = { ...loginRequest, account: activeAccount };

	const response = await msalInstance
		.acquireTokenSilent(requestConfig)
		.then((tokenSilentResponse) => tokenSilentResponse.accessToken)
		.catch(async (err) => {
			console.log(err.message);
			console.log(err instanceof InteractionRequiredAuthError);
			await msalInstance
				.acquireTokenRedirect({ ...requestConfig, prompt: 'select_account' })
				.then((tokenRedirectResponse) => tokenRedirectResponse.accessToken);
		});

	return response;
};

// axios interseprors
axiosInstance.interceptors.request.use(
	async (config) => {
		const token = await acquireToken();

		return { ...config, headers: { Authorization: `Bearer ${token}` } };
		},
	(error) => Promise.reject(error)
);

// Application where I use msal
const Application = () => {
	const { accounts, inProgress } = useMsal();

	useMsalAuthentication('redirect');

	const isAuthenticated = useIsAuthenticated();

	useEffect(() => {
		if (!isAuthenticated || !accounts[0] || inProgress !== InteractionStatus.None) {
			return;
		}
                
                // performLogIn puts account data to redux store and gets the initial data for the page
		store.dispatch(performLogIn(accounts[0].name, accounts[0].username, true));
	}, [isAuthenticated, inProgress]);
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by sameerag** [comment]
@mariiasonina msal js handles the `invalid_grant` error internally by retrying the request with the `/authorize` endpoint as per the spec [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow).  If the request fails even after the retry, we throw and that is when `monitor_window_timeout` is thrown (where the iframe could not authorize on time and times out).

In cases like this we advise to fall back to Interactive flow. However  `monitor_window_timeout` as an error in itself can happen for a myriad of reasons. Hope this clarifies.

**Comment by mariiasonina** [comment]
@sameerag thank you for the explanation.
What do you mean by the Interactive flow? I'm assuming that the call to acquireTokenRedirect after the failure of acquireTokenSilent is an interactive flow. Am I wrong?
I noticed that after the refresh token expires and the user is logged in, the first token post request has grant_type: authorization_code and that request succeeds, but the second one has grant_type: refresh_token and and fails with error: "invalid_grant" (picture above). Why is this happening when I've already successfully logged in interactively?

**Comment by sameerag** [comment]
> I'm assuming that the call to `acquireTokenRedirect` after the failure of `acquireTokenSilent` is an interactive flow. 

Yes. 

>I noticed that after the refresh token expires and the user is logged in, the first token post request has grant_type: authorization_code and that request succeeds, but the second one has grant_type: refresh_token and and fails with error: "invalid_grant" (picture above). Why is this happening when I've already successfully logged in interactively?

* When `acquireTokenSilent` is called, we first try to fetch the tokens from the cache. 
* If the `access_token` is expired, we try to refresh the tokens in the background with the `grant_type=refresh_token`. 
* If the `refresh_token` is also expired, and the request fails with `invalid_grant`, we initiate the call to the `/authorize` endpoint in an iframe to attempt to fetch tokens silently for the user.

At this point, if the silent call is unable to fetch a token, we then ask the user to fall back to interactive flow.

Hope this helps.

**Comment by mariiasonina** [comment]
@sameerag, seems the handleRedirectPromise registration solved my problem.

**Comment by sameerag** [comment]
Great! Resolving the issue.

**Comment by fong1999** [comment]
@mariiasonina  @sameerag Hi! We are having the same error below.

```
MsalAuthService >>> getTokenRedirect : Silent token acquisition fails. acuirting token using redirect.
BrowserAuthError: monitor_window_timeout: Token acquistion in iframe failed due to timeout. For more visit: aka.ms/msaljs/browser-errors. 
```

Could you please share how you solved it using handleRedirectPromise registration? 

Thanks much!

**Comment by mariiasonina** [comment]
> @mariiasonina @sameerag Hi! We are having the same error below.
> 
> ```
> MsalAuthService >>> getTokenRedirect : Silent token acquisition fails. acuirting token using redirect.
> BrowserAuthError: monitor_window_timeout: Token acquistion in iframe failed due to timeout. For more visit: aka.ms/msaljs/browser-errors. 
> ```
> 
> Could you please share how you solved it using handleRedirectPromise registration?
> 
> Thanks much!

@fong1999, Hi!

Sure, my implementation below:

```
export const msalInstance = new PublicClientApplication(msalConfig);

export const handleResponse = (response: AuthenticationResult) => {
    if (response) {
        store.dispatch(performLogIn(response.account.name, response.account.username, true));
    } else {
        const currentAccount = msalInstance.getAllAccounts()[0];

        if (currentAccount) {
            store.dispatch(performLogIn(currentAccount.name, currentAccount.username, true));
        }
    }
};

msalInstance.handleRedirectPromise().then(handleResponse);
```
Hope it will help.
