### ISSUE TITLE
Getting new authentication result after updating dissenting to a permissions still returns the dissented permission in the scopes array

### ISSUE THREAD

**Issue by Onokaev** [AzureAD/microsoft-authentication-library-for-js#5226]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.27.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

none

### Public or Confidential Client?

Public

### Description

I am implementing a feature where our users should be able to dissent to permissions already granted. I am using the /v1.0/oAuth2PermissionGrant endpoint for this. The permissions are updated correctly and if I query the endpoint for the updated grant, I get the updated permissions.

After dissenting, I need to get a new access token with the updated permissions. So I am logging the user out and then back in. The returned scopes array sometimes still has the permission that has been dissented to and the token can still be used to access the resource whose permission has been revoked.

### Relevant Code Snippets

```javascript
let retries = 2;
  await authenticationWrapper.logOut();
  let authResponse = await authenticationWrapper.consentToScopes(updatedScopes);

  while (retries > 0 && authResponse && authResponse.scopes.length !== updatedScopes.length) {
    await authenticationWrapper.logOut();
    authResponse = await authenticationWrapper.consentToScopes(updatedScopes);
    retries--;
  }

  return authResponse;
```

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by jasonnutter** [comment]
> The returned scopes array sometimes still has the permission that has been dissented to and the token can still be used to access the resource whose permission has been revoked.

@Onokaev Have you noticed any patterns here? For example, a certain amount of time passing?

Worth noting from [the documentation](https://learn.microsoft.com/en-us/graph/api/oauth2permissiongrant-delete?view=graph-rest-1.0&tabs=http):

> When a delegated permission grant is deleted, the access it granted is revoked. Existing access tokens will continue to be valid for their lifetime, but new access tokens will not be granted for the delegated permissions identified in the deleted oAuth2PermissionGrant.
