### ISSUE TITLE
Is it possible to have multiple application logins?

### ISSUE THREAD

**Issue by grgicpetar** [AzureAD/microsoft-authentication-library-for-js#5230]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.28.3

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.7

### Public or Confidential Client?

Public

### Description

Application usage scenario:

Landing page -> _Azure AD B2C login_ -> some functionalities -> _Azure AD B2B login_ -> all functionalities

After authenticating with Azure AD B2C, the user gets access to application. After the initial login only some functionalities 
are available. To be granted access to all the functionalities, user must authenticate with Azure AD B2B this time.

Is this scenario possible with single instance of PCA?

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@grgicpetar 

> After authenticating with Azure AD B2C, the user gets access to application. After the initial login only some functionalities
are available. To be granted access to all the functionalities, user must authenticate with Azure AD B2B this time.

To be clear, do you want users to authenticate directly against AAD (i.e. MSAL -> AAD, [as opposed to via B2C](https://learn.microsoft.com/en-us/azure/active-directory-b2c/identity-provider-azure-ad-single-tenant?pivots=b2c-user-flow), i.e. MSAL -> B2C -> AAD)?

You can technically change authorities on a per request basis, so assuming the answer to the above question is yes, then you may be able to achieve what you describe, although it may be easier if you maintain two PCA instances. Unfortunately, we do not have sample that demonstrates this scenario, as far as I know.

**Comment by grgicpetar** [comment]
@jasonnutter 

I am aware that I can change authorities on a per request basis, but what I need to do is change ClientId  on a second authorization request.

I believe this should explain my use case more clearly:

Landing page -> _Azure AD B2C login (Client ID 1)_ -> some functionalities -> _Azure AD B2B login (Client ID 2)_ -> all functionalities.

As far as I know, I didn't see any example where ClientId can be changed using a single instance of MSAL.

**Comment by jasonnutter** [comment]
@grgicpetar In that case, you will need multiple instances of `PublicClientApplication`.

**Comment by tangyinhao123** [comment]
@grgicpetar HI grgicpetar.I want to know how you solved it in the end because I also encountered the same scenario.

**Comment by grgicpetar** [comment]
Hi @tangyinhao123, multiple instances did indeed work. It just feels weird to use since you can use only one instance through useMsal().

**Comment by tangyinhao123** [comment]
> Hi @tangyinhao123, multiple instances did indeed work. It just feels weird to use since you can use only one instance through useMsal().

Thanks @grgicpetar  Is there an example for me to refer to, because I put it in index.tsx and re-instantiate it every time it is called?MY code:`  // Initialize client side tracing
  initializeAppInsights();

  // Initialize Icons
  initializeIcons();
const RootComponent = () => {
  const [instances,setInstance] = useState<PublicClientApplication|null>(null);


  // Inject some global styles
  mergeStyles({
    ":global(body,html,#root)": {
      margin: 0,
      padding: 0,
      height: "100vh",
    },
  });
  React.useEffect(() => {
    const session = sessionStorage.getItem("clientId")
    if (session) {
      if (session == msalConfig.auth.clientId)
      {
        setInstance(new PublicClientApplication(msalConfig))
      }
      else {
        setInstance(new PublicClientApplication(pmeConfig))
      }
    }
  }, []);
  document.title = "OfferStore Portal";
const handAccountType = (atype:string)=>()=>{
  if(atype == "pme")
  {
    setInstance(new PublicClientApplication(pmeConfig))
    sessionStorage.setItem("clientId",pmeConfig.auth.clientId)
  }
  else if (atype == "ms")
  {
     setInstance(new PublicClientApplication(msalConfig))
     sessionStorage.setItem("clientId",msalConfig.auth.clientId)
  }
  else
  {
    return
  }
}
  return (
instances!=null?(
      <CookiesProvider>
        <MsalProvider instance={instances!}>
          <App />
        </MsalProvider>
      </CookiesProvider>):(
           <Stack style={{ marginTop: '50px' }}  tokens={stackTokens}>
           <PrimaryButton  onClick={handAccountType("ms")}  text="Microsoft Account" />
           <PrimaryButton  onClick={handAccountType("pme")} text="PME Account" />
         </Stack>)
  );
};
ReactDOM.render(<RootComponent />, document.getElementById("root"));`

**Comment by grgicpetar** [comment]
@tangyinhao123 

Define two PCA first in some config file:

```
export const msalConfig1 Configuration = {
  ...
};

export const msalConfig2: Configuration = {
 ...
};

export const pca1 = new PublicClientApplication(msalConfig1);
export const pca2 = new PublicClientApplication(msalConfig2);
```

Provide the first one through Provider, this one you can use through useMsal() hook.

The second one you can use by explicity importing pca2 in files.
