### ISSUE TITLE
Using multiple B2C sign in policies

### ISSUE THREAD

**Issue by blockingHD** [AzureAD/microsoft-authentication-library-for-js#5231]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.28.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.4.1

### Public or Confidential Client?

Public

### Description

We are looking at implementing a impersonation flow to our Angular application. Currently we are using a custom sign-in sign-up policy using local accounts.

The requirements are to be able to login via Azure AD (single tenant) then impersonate a local account. We've setup login via AzureAD and that works. We have also setup the impersonation flow (in a separate policy) which has the user login via AzureAD then does the impersonation flow. If I set the authority to https://{Url}/{TenantID}/B2C_1A_IMPERSONATION then I can impersonate users.

Knowing both flows work on their own we want to be able to have the site allow users from either sign in type. 

So far we have tried setting the knownAuthorities to have both B2C_1A_IMPERSONATION and B2C_1A_SIGNUP_SIGNIN. This causes no login actions to be tried as it doesn't know where to get the well-known config from (this is an assumption).

Any help on getting this working or a simple this isn't possible would be great.

### MSAL Configuration

```javascript
{
   "auth":{
      "clientId":"{clientId}",
      "authority":"https://{url}/B2C_1A_IMPERSONATION",
      "knownAuthorities":[
         "{domain}"
      ],
      "redirectUri":"http://localhost:4200",
      "postLogoutRedirectUri":"{logoutUri}"
   },
   "cache":{
      "cacheLocation":"BrowserCacheLocation.LocalStorage",
      "storeAuthStateInCookie":isIE
   }
}
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@blockingHD You can set the `authority` for a given request on a per-request basis, which would enable you to login with a different B2C policy than the one set in the configuration (`auth.authority` above). Have you tried this? If so, can you provide code snippets show what you tried and what happens when do?

**Comment by blockingHD** [comment]
@jasonnutter Not sure how I can do this in my case as I want the authority to be accepted when the auth request is triggered externally to the application. IE a user goes into https://www.office.com/apps and clicks the enterprise application then they go straight to the b2c policy. 

Going through the app is not ideal as we would have to create a page that routes them with the authority. Plus they may already be authed against that other authority from another application (SSO) so I'd like it to be seemless. 

This might not be possible but I'd like to explore this before conceding to triggering it via the app.

**Comment by jasonnutter** [comment]
@blockingHD I'm not sure if this is possible, and I think the B2C support team will be able to provide a better answer: https://docs.microsoft.com/azure/active-directory-b2c/support-options

**Comment by hectormmg** [comment]
@blockingHD please let us know if you do file a support ticket with the B2C team so we can close this issue.

**Comment by blockingHD** [comment]
Asked this question via Microsoft Support. @hectormmg
