### ISSUE TITLE
Azure AD in nodejs unable to resolve endpoint in the keyvault when in vnet

### ISSUE THREAD

**Issue by prattyaDatta** [AzureAD/microsoft-authentication-library-for-js#5232]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

none

### Wrapper Library

Not Applicable

### Wrapper Library Version

none

### Public or Confidential Client?

Public

### Description

I am using @azure/identity for an app registered in azure AD which has all the access to the keyvault. The node js app where this package is used, uses @azure/keyvault-secrets to get the secret. It works perfectly fine however when the nodejs app running on windows and the keyvault is put behind the vnet and private endpoints I get an error which says unable to resolve endpoints ( clicking on the link and investigating further brought me to msal error ). 

### Error Message

DefaultAzureCredential {
  UnavailableMessage: 'DefaultAzureCredential => failed to retrieve a token from the included credentials. To troubleshoot, visit https://aka.ms/azsdk/js/identity/defaultazurecredential/troubleshoot.',
  _sources: [
    EnvironmentCredential { _credential: [ClientSecretCredential] },
    DefaultManagedIdentityCredential {
      isEndpointUnavailable: null,
      clientId: '',
      resourceId: undefined,
      identityClient: [IdentityClient],
      isAvailableIdentityClient: [IdentityClient]
    },
    VisualStudioCodeCredential {
      cloudName: 'AzureCloud',
      identityClient: [IdentityClient],
      tenantId: 'common'
    },
    AzureCliCredential { tenantId: undefined },
    AzurePowerShellCredential { tenantId: undefined }
  ]
}
The azure client resulting from the above error 
KeyClient {
  vaultUrl: 'https://kv-gdp-ammi-dev-ne-010.vault.azure.net',
  credential: DefaultAzureCredential {
    UnavailableMessage: 'DefaultAzureCredential => failed to retrieve a token from the included credentials. To troubleshoot, visit https://aka.ms/azsdk/js/identity/defaultazurecredential/troubleshoot.',
    _sources: [
      [EnvironmentCredential],
      [DefaultManagedIdentityCredential],
      [VisualStudioCodeCredential],
      [AzureCliCredential],
      [AzurePowerShellCredential]
    ]
  },
  client: KeyVaultClient {
    _requestContentType: 'application/json; charset=utf-8',
    _endpoint: '{vaultBaseUrl}',
    _allowInsecureConnection: undefined,
    _httpClient: NodeHttpClient { cachedHttpsAgents: [WeakMap] },
    pipeline: HttpPipeline { _policies: [Array], _orderedPolicies: undefined },
    apiVersion: '7.3'
  }
}

### MSAL Configuration

```javascript
none
```

### Relevant Code Snippets

```javascript
use strict';

const { DefaultAzureCredential, ClientSecretCredential }    = require("@azure/identity");
const { SecretClient  }                                     = require("@azure/keyvault-secrets");
const { CertificateClient }                                 = require("@azure/keyvault-certificates");
const { KeyClient, CryptographyClient }                     = require("@azure/keyvault-keys");
const   appInsightsClient                                   = require('./appinsights');
const resolve                                               = require('../lib/cname');
module.exports.createClient = (kvConfig, kvType) => {
    if (!kvConfig.clientId) {
        throw new Error('KeyVault client ID required at this time for the middleware to initialize.');
    }
    if (!kvConfig.clientSecret) {
        throw new Error('KeyVault client credential/secret required at this time for the middleware to initialize.');
    }
    if (!kvConfig.tenantId) {
        throw new Error('KeyVault client tenant ID required at this time for the middleware to initialize.');
    }
    const vaultUri = process.env.vaultUri;
    const url = `https://${vaultUri}.vault.azure.net`;
    let credentials = null;
    let keyVaultClient = null;
    console.log('resolving for google.com :\n')
    resolve('www.google.com')
    console.log('resolving for keyvault\n')
    resolve(url)

    try{
        console.log(kvConfig);
        credentials = new DefaultAzureCredential(kvConfig.tenantId, kvConfig.clientId, kvConfig.clientSecret);
        console.log('credentials: \n')
        console.log(`resolved credentials object ${Object.getOwnPropertyNames(credentials)} with follwing details!\n`)
        console.log(credentials)
        if(kvType == "secret"){
            console.log("resolving the keyvault client in the following!\n")
            keyVaultClient = new SecretClient(url, credentials);
            if(keyVaultClient){
                console.log("KeyVault client resolved with the following values: \n")
                console.log(`Object has follwing field names! => ${Object.getOwnPropertyNames(keyVaultClient)}`)
                console.log(keyVaultClient);
            }
        }else if(kvType == "certificate"){
            keyVaultClient = new CertificateClient(url, credentials);
            if(keyVaultClient){
                console.log("KeyVault client resolved with the following values: \n")
                console.log(`Object has follwing field names! => ${Object.getOwnPropertyNames(keyVaultClient)}`)
                console.log(keyVaultClient);
            }
        }else if(kvType == "key"){
            keyVaultClient = new KeyClient(url, credentials);
            if(keyVaultClient){
                console.log("KeyVault client resolved with the following values: \n")
                console.log(`Object has follwing field names! => ${Object.getOwnPropertyNames(keyVaultClient)}`)
                console.log(keyVaultClient);
            }
        }
        else{
            appInsightsClient.trackException({exception: new Error('KeyVault undefined')})
            throw new Error('Key Vault unidentified');
        }
    }catch(err){
        console.log(err)
        appInsightsClient.trackException({exception:  new Error(`${err}`)})
    }
    return keyVaultClient;
};
```

### Reproduction Steps

None                       

### Expected Behavior

The default credentials should resolve

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Source

External (Customer)

**Comment by jasonnutter** [comment]
May be related to #4879

**Comment by bmahall** [comment]
@prattyaDatta Can you try the latest version (node 1.14.1) and let me know if you are still seeing this error?
