### ISSUE TITLE
Redirect URL is converted to lowercase

### ISSUE THREAD

**Issue by roopeshchinnakampalli** [AzureAD/microsoft-authentication-library-for-js#5238]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.24.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.4.3

### Public or Confidential Client?

Public

### Description

#3621 -  I'm looking for the fix for this issue which was reported last year. I can still reproduce this issue now with the latest code.

You can follow the same steps described in this thread - [https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/3621](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/3621)

@jasonnutter Any help on this?

### Error Message

N/A

### Msal Logs

N/A

### MSAL Configuration

```javascript
{
auth: {
      authority: 'https://login.microsoftonline.com/xxx.org/',
      clientId: 'xxxxxxxxxxxxxxx',
      redirectUri: 'http://localhost:4200',
      postLogoutRedirectUri: 'https://xxxx.org',
      navigateToLoginRequestUrl: true
    },
    cache: {
      cacheLocation: 'sessionStorage'
    }
}
```

### Relevant Code Snippets

```javascript
N/A
```

### Reproduction Steps

Try to authenticate the app with the URL with uppercase and you will see the bevaiour.

### Expected Behavior

It should retain the case after redirection

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari

### Regression

N/A

### Source

External (Customer)

**Comment by jasonnutter** [comment]
@roopeshreddy Please provide code snippets that demonstrate your usage, including your configuration of MSAL Angular.

**Comment by roopeshchinnakampalli** [comment]
Hey @jasonnutter We've written a custom MSAL navigation client wrapper. 

Basically, I've extended the Navigation Client as described here - [https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/performance.md](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/performance.md)

The below snippets is causing the url path to lowercase! These methods are from **@azure/msal-browser**

```
    const urlComponents = new UrlString(url).getUrlComponents();
    const newUrl = urlComponents.QueryString
      ? `${urlComponents.AbsolutePath}?${urlComponents.QueryString}`
      : this.location.normalize(urlComponents.AbsolutePath);
```
To be precise, **UrlString(url).getUrlComponents()** is the culprit. If we pass the URL with the upper case, then it's returning the lowercase.

Thanks!

**Comment by jasonnutter** [comment]
@roopeshreddy Our `UrlString` class normalizes URLs by design. If the built-in navigation client does not fit your needs, you should consider implementing a custom navigation client (i.e. copy the built-in navigation client into your project and change it to fit your needs).

**Comment by roopeshchinnakampalli** [comment]
@jasonnutter  Thank you! Sure, we can do that. Since this method is available OOB, we thought to use it. Atleast if we can get the URL in the same case, that would be great.

**Comment by hectormmg** [comment]
@roopeshreddy since you're going with a custom implementation of the navigation client, is it alright if we close this issue?

**Comment by roopeshchinnakampalli** [comment]
@hectormmg Since I'm using the function from MSAL library - 

`import { UrlString } from '@azure/msal-browser';`

is there any possibility to fix it?

**Comment by jo-arroyo** [comment]
@roopeshreddy As stated above, our `UrlString` class normalizes URLs by design. Along with the custom navigation client, you may need to write your own URL methods to suit your needs.

**Comment by roopeshchinnakampalli** [comment]
Sure thanks!
