### ISSUE TITLE
Interactive state still set in session storage on logoutRedirect

### ISSUE THREAD

**Issue by eglavin** [AzureAD/microsoft-authentication-library-for-js#5241]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.28.3

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

After upgrade from version 2.21.0 to 2.28.3. I'm unable to login again after logoutRedirect is called and browser is redirected to the login page. I see in the browsers session storage the key `msal.interaction.status` is set, On removal I can then login again.

I have a gif showing this issue but has private information shown, Please let me know if it would be of use to share with you.

### Error Message

```json
{
    "errorCode": "interaction_in_progress",
    "errorMessage": "Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.  For more visit: aka.ms/msaljs/browser-errors.",
    "subError": "",
    "name": "BrowserAuthError"
}
```

### MSAL Configuration

```javascript
{
  auth: {
    clientId: `${AUTH_CLIENT_ID}`,
    authority: `${AUTH_AUTHORITY_URI}/${AUTH_TENANT_ID}`,
    redirectUri: `${window.location.origin}/Redirect`,
    postLogoutRedirectUri: `${window.location.origin}`,
  },
  cache: {
    cacheLocation: BrowserCacheLocation.SessionStorage,
    storeAuthStateInCookie: false,
  },
}
```

### Relevant Code Snippets

```javascript
public logout(): Promise<void> {
  return this._client.logoutRedirect({ account: this.activeAccount });
}
```

### Reproduction Steps

1. Login to app using loginPopup
2. Logout using logoutRedirect
3. Attempt to login again using loginPopup (Receive error above)

### Expected Behavior

Able to login again after returning to the login page.

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge

### Regression

@azure/msal-browser 2.28.3

### Source

External (Customer)

**Comment by eglavin** [comment]
I tried upgrading a few months ago and ran into the same issue, I thought it had been fixed though

Possibly related: #4719 #4697

**Comment by hectormmg** [comment]
@eglavin thanks for raising this issue. I'll start investigating and update you when I can reproduce this behavior.

**Comment by hectormmg** [comment]
@eglavin could you send the GIF you mentioned to the e-mail in my profile? I haven't been able to reproduce this behavior. Does it always happen?

**Comment by eglavin** [comment]
@hectormmg Did you receive the email I sent you? 

> Does it always happen?

For any version past 2.21.0 it does yes, returning to 2.21.0 fixes it for now.

**Comment by eglavin** [comment]
Ok, I'm realising now that I'm missing a call to `handleRedirectPromise` in my init function which I see now in these docs https://learn.microsoft.com/en-gb/azure/active-directory/develop/msal-js-initializing-client-applications#initialize-msaljs-2x-apps

My original implementation was based of this repo: https://github.com/Azure-Samples/ms-identity-javascript-react-spa-dotnetcore-webapi-obo/blob/master/ProfileSPA/src/utils/authProvider.js#L36

Which only calls the `handleRedirectPromise` if its used in Internet Explorer. I wonder was there a change to the logic since 2.21.0+ ? Any way I think I have that in hand now, just need to refactor the init function to ensure `handleRedirectPromise` is called before app is ready!

Thanks for you help Hector!
