### ISSUE TITLE
How do I get rawIdToken and jwt token

### ISSUE THREAD

**Issue by diamant-isufi-sveasolar** [AzureAD/microsoft-authentication-library-for-js#5259]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.27.2

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.6

### Public or Confidential Client?

Public

### Description

To send request to my server I need to get the rawIdToken and the jwt token from the request.

### MSAL Configuration

```javascript
export const msalConfig: Configuration = {
    auth: {
        clientId: process.env.REACT_APP_AZURE_CLIENT_ID,
        redirectUri: process.env.REACT_APP_AZURE_REDIRECT_URI,
        postLogoutRedirectUri:
            process.env.REACT_APP_AZURE_POSTLOGOUT_REDIRECT_URI,
    },
    cache: {
        cacheLocation: 'localStorage',
        storeAuthStateInCookie: false,
    },
}
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by hectormmg** [comment]
@diamant-isufi-sveasolar please take a look at our [Acquire Token docs](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/acquire-token.md) and let us know if this answers your question.
