### ISSUE TITLE
this.msalBroadcastService.inProgress$ subscribe event called twice

### ISSUE THREAD

**Issue by SGeorge007** [AzureAD/microsoft-authentication-library-for-js#5273]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.0

### Public or Confidential Client?

Public

### Description

Inside subscribe of  this.msalBroadcastService.inProgress$, I am calling my API code.
but this subscribe event is always called two times when user logs in. Please suggest how should I avoid twice/duplicate calls?

 this.msalBroadcastService.inProgress$
      .pipe(
        filter((status: InteractionStatus) => status === InteractionStatus.None),
        takeUntil(this.onDestroy$)
      )
      .subscribe(() => {
        this.checkAndSetActiveAccount();
      });  

### MSAL Configuration

```javascript
NA
```

### Relevant Code Snippets

```javascript
ngOnInit() {
    this._logger.logMessage('Inside init');
    this.isIframe = window !== window.parent && !window.opener;
    
    this.notifyService.getPerksOfficeID.subscribe(value => {
      this.perksOfficeID = value || EaStore.getValue('perksOfficeID');
      this._logger.logMessage('OfficeID from Perks: ' + this.perksOfficeID);
    });
   
    this.msalBroadcastService.msalSubject$
    .pipe(
      filter((msg: EventMessage) => msg.eventType === EventType.LOGIN_SUCCESS || msg.eventType === EventType.ACQUIRE_TOKEN_SUCCESS),
      takeUntil(this._onDestroy$)
    )
    .subscribe((result) => {
      this._logger.logMessage('On Login success ' + result);
      const payload = result.payload as AuthenticationResult;
      this.msalService.instance.setActiveAccount(payload.account);      
    });

    this.msalBroadcastService.inProgress$
      .pipe(
        filter((status: InteractionStatus) => status === InteractionStatus.None),
        takeUntil(this.onDestroy$)
      )
      .subscribe(() => {
        this.checkAndSetActiveAccount();
      });   
  }
```

### Reproduction Steps

1. Login to you app
2. enter user id and pwd
3. At this point subscribe event of  this.msalBroadcastService.inProgress$ is called twice

### Expected Behavior

 subscribe event of  this.msalBroadcastService.inProgress$ should be called only once

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@SGeorge007 Can you provide your configuration (how you are setting up your app in app.module.ts) and also provide verbose logs showing where the two calls are happening?
