### ISSUE TITLE
ES6 export options for npm package @azure/msal-browser

### ISSUE THREAD

**Issue by FelipeSimoes** [AzureAD/microsoft-authentication-library-for-js#5274]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

Not Applicable

### Public or Confidential Client?

Confidential

### Description

Currently, we have all bundled at @azure/msal-browser.
Meaning no tree-shaking is allowed now.
Projects can reduce the final bundle size by at least 40%, not ~300k.
We wish to have an option exported at NPM package with ES6 modules 

For example other than the current rollup bundle, having the library at the NPM as we have in `msal-core` package 
```tsc --project tsconfig.build.json && tsc --project tsconfig.build.json -m es6 --outDir lib-es6```

Thanks 
Best regards

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@FelipeSimoes This ask is already in our consideration and has been added to our backlog. Changing this to feature ask for tracking.

**Comment by stefaniehansen** [comment]
Hi there, I'll also chime in to ask for this as msal-browser is a large portion of our (OneNote Meeting Notes) bundle and it'd be really nice to be able to tree-shake unused code out.
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/31112980/205179632-ff1c0165-cc96-4832-8975-73fa3a5c8030.png">

**Comment by tnorling** [comment]
A beta of the v3 version of msal-browser is released which should be exporting ES2020 modules. Can you try that out and let us know if that resolves this issue? Thanks!

**Comment by Milos5611** [comment]
Is this real? This package goes bigger and bigger by the day. This become a bottleneck for my project atm.
Can someone give me a hint on how to reduce it?

This is my settings:

```
import { LogLevel, PublicClientApplication } from "@azure/msal-browser";
import { Configuration } from "@azure/msal-browser/dist/config/Configuration";

// Config object to be passed to Msal on creation
const OIDC_REDIRECT_URL =
  process.env.NODE_ENV === "production"
    ? window?._env_?.OIDC_REDIRECT_URL
    : process.env.OIDC_REDIRECT_URL;

export const msalConfig: Configuration = {
  auth: {
    clientId: `${process.env.OIDC_CLIENT_ID}`,
    authority: `${process.env.OIDC_AUTH_URL}/${process.env.OIDC_TENANT_ID}`,
    redirectUri: OIDC_REDIRECT_URL,
  },
  cache: {
    cacheLocation: "sessionStorage",
    storeAuthStateInCookie: false,
  },
  system: {
    loggerOptions: {
      logLevel:
        process.env.NODE_ENV === "production" ? LogLevel.Error : LogLevel.Info,
      piiLoggingEnabled: false,
      loggerCallback: (level, message) => console.log(`MSAL ${message}`),
    },
  },
};

export const msalInstance = new PublicClientApplication(msalConfig);
```

<img width="734" alt="Screenshot at Jul 10 21-23-37" src="https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/2955028/85c3b4cb-2867-48d2-8454-88ab88e293b4">

**Comment by tnorling** [comment]
@Milos5611 This is certainly much, much bigger than we would expect to see. The first thing to check is to make sure your bundler is minifying the output, beyond that we would need a reproduction to further debug. Please open a separate issue so we can have a focused discussion on your particular problem.

**Comment by tnorling** [comment]
Closing as msal-browser 3.0.0 is now released and includes these changes
