### ISSUE TITLE
es6 import documentation

### ISSUE THREAD

**Issue by jkga** [AzureAD/microsoft-authentication-library-for-js#528]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

Library version: 0.2.4

## Current behavior

Documentation doesn't state how to import msal in es6. Though this might not be   
 too important, it is good to be included on the documentation.

## Expected behavior

Documentation must somehow include how to properly import msal in es6   
> import * as Msal from 'msal'

Related Issue:
#96

**Comment by visualjeff** [comment]
This works for me...

`import * as Msal from 'msal';`

**Comment by pkanher617** [comment]
@jkga I have added this documentation here. Please let me know if I should add anything more.

https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL-basics

**Comment by jkga** [comment]
Thank you @pkanher617
