### ISSUE TITLE
MSAL Angular: Guard/intercept all (service worker) web requests to the hosting web site

### ISSUE THREAD

**Issue by Done3319** [AzureAD/microsoft-authentication-library-for-js#5281]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.28.3

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.4.4

### Public or Confidential Client?

Confidential

### Description

We have an Angular application which is located on an Azure "App Service" web server
The web server requires authentication for all requests (EasyAuth - Return HTTP 302 Found - Redirect to identity provider)
The app is also registered in Azure AD with all routes protected with "canActivate: [MsalGuard]". It has the Angular service worker enabled.

Everything works well when using the app the first time:
1. User calls hosting URL
2. Browser is redirected to Azure IDP logon page and redirected back authenticated
3. Browser downloads and starts app
4. Service worker checks for updates (calling https://hosting_site/ngsw.json)

However, once the application is in the browser cache and the authentication token is expired, step 4 fails with a CORS error:

`Access to fetch at 'https://login.windows.net/.../oauth2/v2.0/authorize?response_type=code+id_token&redirect_uri=https%3A%2F%2Fhosting_site%2F.auth%2Flogin%2Faad%2Fcallback&client_id=xxx&scope=openid+profile+email&response_mode=form_post&nonce=xxx&state=redir%3D%252Fngsw.json%253Fngsw-cache-bust%253D0.3592058817013697' (redirected from 'https://hosting_site/ngsw.json?ngsw-cache-bust=0.3592058817013697') from origin 'https://hosting_site.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Question: Is there a way how all requests to a specific web server, also the ones which are formally not an application route, can be intercepted/pre-authenticated by MSAL?

I was already thinking of defining a dummy scope and configuring an interceptor like

`protectedResourceMap: new Map([ 
        ['hosting_site/*', ['dummy']]
`

but I'm not sure if this will work and I hope there are better solutions for this?

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by tnorling** [comment]
@Done3319 I'm not familiar with this pattern. What is making the failing request (It doesn't look like MSAL.js)? Do you need to be authenticated to access the hosting site? If not, configuring the interceptor may not solve the problem.

**Comment by Done3319** [comment]
@tnorling Thanks for looking into this!
Right, any request to the hosting site must be authenticated (the hosting site is an Azure App Service with EasyAuth enabled).
The ngsw.json is located on the hosting site. The Angular service worker fetches this file regularly in order to check if there is a newer version of the app available.
I'm wondering how such requests can be covered by the MSAL interceptor. Basically, something that provides authentication for any request sent to the hosting site is required.

**Comment by tnorling** [comment]
Got it, so then yes you should use the Interceptor to attach an access token to all requests to the hosting site. I'm not sure I understand why you're suggesting using a dummy scope, you should use a real scope that you will then validate on the resource.

**Comment by Done3319** [comment]
I was thinking of a dummy scope because the hosting web server will only check for successful authentication. As far as I know, EasyAuth cannot check authorization tokens.

In order to test with the Interceptor approach, I have setup a mapping like
`protectedResourceMap: new Map([ ['https://hosting_site/*', ['dummy']]`

Unfortunately, this does not work. According to the MSAL verbose logs the Interceptor never gets triggered by the service worker request to https://hosting_site/ngsw.json

The request is initiated by ngsw-worker.js:
`const res = await this.safeFetch(this.adapter.newRequest("ngsw.json?ngsw-cache-bust=" + Math.random()));`

Any idea why this request is not intercepted?

**Comment by tnorling** [comment]
So the service worker is making the request to hosting_site? I'm assuming the service worker is not running MSAL, is that a correct assumption? If so, that's why it's not working. You may need to manually call `acquireTokenSilent` before invoking your `safeFetch` function

**Comment by Done3319** [comment]
The service worker is something provided by Angular out of the box. I don't know how this works in detail. As far as I understand it is regularly checking for updates by polling the https://hosting_site/ngsw.json file.
Not sure how much this process can be changed from outside. I will check the `acquireTokenSilent` and see if it can help.

**Comment by Done3319** [comment]
Update: The `acquireTokenSilent` works as expected. However, the acquired token useless because it cannot be passed to the service worker. The worker uses `fetch` instead of HttpClient, so the worker's requests never get intercepted.

I'll follow up on this with the Angular community. This needs to be fixed in the Angular service worker.

**Comment by vvolodin** [comment]
Any updates on this issue? @Done3319 ? When I try my angular app in offline mode service worker causes infinite loop of redirects to login.microsoftonline.com
