### ISSUE TITLE
ConfidentialClientApplication -> acquireTokenByUsernamePassword : Error  AADSTS90036

### ISSUE THREAD

**Issue by quentingosset** [AzureAD/microsoft-authentication-library-for-js#5282]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.14.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

noe

### Public or Confidential Client?

Confidential

### Description

I did exactly what the following example shows: https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/username-password-cca

but when calling acquireTokenByUsernamePassword, I got an error AADSTS90036 

```
ServerError: server_error: 90036 - [2022-10-08 17:49:40Z]: AADSTS90036: An unexpected, non-retryable error stemming from the directory service has occurred.    
Trace ID: e6f18f74-0abf-4d8e-aab5-919f74787800
Correlation ID: c9f8bc7e-9eea-4967-bb6d-77e92642baaa
Timestamp: 2022-10-08 17:49:40Z - Correlation ID: c9f8bc7e-9eea-4967-bb6d-77e92642baaa - Trace ID: e6f18f74-0abf-4d8e-aab5-919f74787800
```

### MSAL Configuration

```javascript
{
    auth: {
        clientId: "201c978e-5402-4b1f-a8fd-572598d7e691",
        authority: "https://login.microsoftonline.com/09812eab-c0af-4aa8-a9f4-3ee3d1cda1dc",
        clientSecret: "*************"
    }
};
```

### Relevant Code Snippets

```javascript
var msal = require("@azure/msal-node");

const msalConfig = {
    auth: {
        clientId: "201c978e-5402-4b1f-a8fd-572598d7e691",
        authority: "https://login.microsoftonline.com/09812eab-c0af-4aa8-a9f4-3ee3d1cda1dc",
        clientSecret: "***********"
    }
};

const cca = new msal.ConfidentialClientApplication(msalConfig);

const usernamePasswordRequest = {
    scopes: ["user.read"],
    username: "*********@hotmail.com", // Add your username here
    password: "*********", // Add your password here
};

cca.acquireTokenByUsernamePassword(usernamePasswordRequest).then((response) => {
    console.log("acquired token by password grant in confidential clients");
}).catch((error) => {
    console.log(error);
});
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by quentingosset** [comment]
After a few attempts, I think I have a lead.
My main Azure account is quentingosset7500@hotmail.com it is the one that has the error message AADSTS90036.
This one is therefore in the list of users in the default directory.
To test, I created a new user in the default directory and there, what is my surprise. I have no error!

~~The difference is that I have my main account quentingosset7500@hotmail.com which has double authentication unlike the new one where there is nothing. Do you have any idea if this could be the cause?~~

the problem come with each "Microsoft account" like all "@hotmail.com" directly connected or invited on AD.

![image](https://user-images.githubusercontent.com/6824137/194727147-f4cce69e-4b75-4d28-880c-c8d159f3363a.png)

**Comment by tnorling** [comment]
@quentingosset Please see the prerequisites on the doc you linked and the important notes in the [ROPC docs](https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth-ropc). ROPC is not supported for personal accounts (@hotmail.com accounts for example) even if those accounts are invited to an Azure AD tenant. You must use an account that belongs to your organizational tenant.

**Comment by quentingosset** [comment]
@tnorling I see ! 
So it is impossible for a personal Hotmail account of the type "quentin@hotmail.com" to give identification information or validate once and only once the access to the application which will be in background? 
I am currently facing a huge amount of mail on my mailbox and I would like to be able to create a background app that will sort my mails automatically.


However, I have to admit that it's only with Microsoft that I have a problem to find my way in the API documentation. I have the impression that the Microsoft APIs are a JUNGLE.

**Comment by tnorling** [comment]
You should use the auth code flow for this, or perhaps the device code flow if your server can't take user input. Besides the incompatibility with MSA accounts, the ROPC flow is generally discouraged and should be limited to only testing scenarios. The refresh token you'll receive from these other flows will have a lifetime of 90 days so that's how often you would need to reauthenticate.
