### ISSUE TITLE
Angular application integrating with ADFS 2019 - Error when calling secured API service

### ISSUE THREAD

**Issue by ghost** [AzureAD/microsoft-authentication-library-for-js#5285]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.29.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.4.1

### Public or Confidential Client?

Public

### Description

I have an Angular 14.x project using the msal angular library. This project is configured to integrate with ADFS 2019. The issue I'm running into is configuring the MsalInterceptor that will retrieve a token for a secured API.

Not sure what I'm doing wrong.  I thought the latest MSAL.js worked with ADFS, so I'm puzzled why this isn't working.

From the service perspective,  it is just a .NET 6 Web API configured to validate the Audience:

Here is the service configuration:
 **"Federation": {
    "MetadataAddress": "https://dvfs.rcis.com/adfs/.well-known/openid-configuration",
    "Audience": "urn:App:Azure:Generic",
    "TokenValidationParameters": {
      "ValidIssuer": "http://dvfs.rcis.com/adfs/services/trust"
    }
  }**

Here is the DI code:
**builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options => builder.Configuration.Bind("Federation", options));
builder.Services.AddAuthorization();**

### Error Message

The browser logs this in the console: **Http failure response for https://localhost:7299/weatherforecast: 401 Unauthorized**

From the server:
Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler: Information: **Failed to validate the token.**

Microsoft.IdentityModel.Tokens.SecurityTokenInvalidAudienceException: **IDX10214: Audience validation failed. Audiences: 'microsoft:identityserver:f2c5c411-8f32-49ca-b8ff-536c0f7cb362'. Did not match: validationParameters.ValidAudience: 'urn:App:Azure:Generic' or validationParameters.ValidAudiences: 'null'.**
   at Microsoft.IdentityModel.Tokens.Validators.ValidateAudience(IEnumerable`1 audiences, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwtToken, TokenValidationParameters validationParameters, BaseConfiguration configuration)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateJWS(String token, TokenValidationParameters validationParameters, BaseConfiguration currentConfiguration, SecurityToken& signatureValidatedToken, ExceptionDispatchInfo& exceptionThrown)
--- End of stack trace from previous location ---
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, JwtSecurityToken outerToken, TokenValidationParameters validationParameters, SecurityToken& signatureValidatedToken)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler: Information: Bearer was not authenticated. Failure message: IDX10214: Audience validation failed. Audiences: 'microsoft:identityserver:f2c5c411-8f32-49ca-b8ff-536c0f7cb362'. Did not match: validationParameters.ValidAudience: 'urn:App:Azure:Generic' or validationParameters.ValidAudiences: 'null'.
Microsoft.AspNetCore.Authorization.DefaultAuthorizationService: Information: Authorization failed. These requirements were not met:
DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler: Information: AuthenticationScheme: Bearer was challenged.
Microsoft.AspNetCore.Server.Kestrel.Connections: Debug: Connection id "0HMLAUKV3PM00" completed keep alive response.
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished HTTP/1.1 GET https://localhost:7299/weatherforecast - - - 401 0 - 1296.0602ms

### Msal Logs

[Mon, 10 Oct 2022 21:21:10 GMT] : @azure/msal-browser@2.29.0 : Info - Emitting event: msal:acquireTokenFromNetworkStart
src/app/app.module.ts:48
[Mon, 10 Oct 2022 21:21:10 GMT] : @azure/msal-browser@2.29.0 : Verbose - Emitting event to callback 9c137bce-187c-4208-87bc-278fb3baaea2: msal:acquireTokenFromNetworkStart
src/app/app.module.ts:51
[Mon, 10 Oct 2022 21:21:10 GMT] : [8c97f288-af64-47e6-ad9e-b13b186dd800] : msal.js.browser@2.29.0 : Verbose - Initializing BaseAuthRequest
src/app/app.module.ts:51
[Mon, 10 Oct 2022 21:21:10 GMT] : [8c97f288-af64-47e6-ad9e-b13b186dd800] : msal.js.browser@2.29.0 : Verbose - Authentication Scheme set to "Bearer" as configured in Auth request
src/app/app.module.ts:51
[Mon, 10 Oct 2022 21:21:10 GMT] : [8c97f288-af64-47e6-ad9e-b13b186dd800] : msal.js.browser@2.29.0 : Verbose - initializeServerTelemetryManager called
src/app/app.module.ts:51
[Mon, 10 Oct 2022 21:21:10 GMT] : [8c97f288-af64-47e6-ad9e-b13b186dd800] : msal.js.browser@2.29.0 : Verbose - getClientConfiguration called
src/app/app.module.ts:51
[Mon, 10 Oct 2022 21:21:10 GMT] : [8c97f288-af64-47e6-ad9e-b13b186dd800] : msal.js.browser@2.29.0 : Verbose - getDiscoveredAuthority called
src/app/app.module.ts:51
[Mon, 10 Oct 2022 21:21:10 GMT] : [8c97f288-af64-47e6-ad9e-b13b186dd800] : msal.js.browser@2.29.0 : Verbose - Creating discovered authority with configured authority
src/app/app.module.ts:51
[Mon, 10 Oct 2022 21:21:10 GMT] : [8c97f288-af64-47e6-ad9e-b13b186dd800] : msal.js.browser@2.29.0 : Verbose - Refresh token client created
src/app/app.module.ts:51
[Mon, 10 Oct 2022 21:21:10 GMT] : [8c97f288-af64-47e6-ad9e-b13b186dd800] : @azure/msal-common@7.5.0 : Verbose - RefreshTokenClientAcquireTokenWithCachedRefreshToken called
src/app/app.module.ts:51
[Mon, 10 Oct 2022 21:21:10 GMT] : [8c97f288-af64-47e6-ad9e-b13b186dd800] : @azure/msal-common@7.5.0 : Verbose - RefreshTokenClientAcquireToken called
src/app/app.module.ts:51
[Mon, 10 Oct 2022 21:21:10 GMT] : [8c97f288-af64-47e6-ad9e-b13b186dd800] : @azure/msal-common@7.5.0 : Verbose - Authority type is ADFS, creating ADFS account
src/app/app.module.ts:51
[Mon, 10 Oct 2022 21:21:10 GMT] : @azure/msal-browser@2.29.0 : Info - Emitting event: msal:acquireTokenSuccess
src/app/app.module.ts:48
[Mon, 10 Oct 2022 21:21:10 GMT] : @azure/msal-browser@2.29.0 : Verbose - Emitting event to callback 9c137bce-187c-4208-87bc-278fb3baaea2: msal:acquireTokenSuccess
src/app/app.module.ts:51
[Mon, 10 Oct 2022 21:21:10 GMT] : [8c97f288-af64-47e6-ad9e-b13b186dd800] : @azure/msal-browser@2.29.0 : Verbose - PerformanceClient: Measurement found for acquireTokenSilent
src/app/app.module.ts:51
[Mon, 10 Oct 2022 21:21:10 GMT] : [8c97f288-af64-47e6-ad9e-b13b186dd800] : @azure/msal-browser@2.29.0 : Verbose - PerformanceClient: Submeasurement for acquireTokenSilent already exists for standardInteractionClientGetDiscoveredAuthority, ignoring
src/app/app.module.ts:51
[Mon, 10 Oct 2022 21:21:10 GMT] : [8c97f288-af64-47e6-ad9e-b13b186dd800] : @azure/msal-browser@2.29.0 : Verbose - PerformanceClient: Emitting performance events
src/app/app.module.ts:51
[Mon, 10 Oct 2022 21:21:10 GMT] : @azure/msal-angular@2.4.1 : Verbose - Interceptor - setting authorization headers
src/app/app.module.ts:51
HttpErrorResponse {headers: HttpHeaders, status: 401, statusText: 'OK', url: 'https://localhost:7299/weatherforecast', ok: false, …}

### MSAL Configuration

```javascript
export function MSALInstanceFactory(): IPublicClientApplication {
  return new PublicClientApplication({
    auth: {
      clientId: 'f2c5c411-8f32-49ca-b8ff-536c0f7cb362',
      authority: 'https://dvfs.rcis.com/adfs',
      protocolMode: ProtocolMode.OIDC,
      knownAuthorities: ["dvfs.rcis.com"],
      redirectUri: '/',
      postLogoutRedirectUri: '/sign-out',
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Verbose,
        piiLoggingEnabled: false
      }
    }
  });
}

export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
  const protectedResourceMap = new Map<string, Array<string>>();
  protectedResourceMap.set('https://localhost:7299/*', ['urn:App:Azure:Generic']);

  return {
    interactionType: InteractionType.Redirect,
    protectedResourceMap
  };
}
```

### Relevant Code Snippets

```javascript
This is a basic service:

@Injectable({
  providedIn: 'root'
})
export class WeatherService {

  private uri: string = "https://localhost:7299/weatherforecast"

  constructor(private client: HttpClient) { }

  getWeather(): Observable<Weather[]> {
    return this.client.get<Weather[]>(this.uri);
  }

}
```

### Reproduction Steps

1.  Execute service

### Expected Behavior

I'm expecting a the MsalInterceptor retrieve the proper token and add the authorization header before calling the protected service.

According to fiddler, this is sent to the token endpoint:

client_id=f2c5c411-8f32-49ca-b8ff-536c0f7cb362&scope=urn%3AApp%3AAzure%3AGeneric%20openid%20profile%20offline_access&grant_type=refresh_token

### Identity Provider

ADFS

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

External (Customer)

**Comment by ghost** [comment]
The issue might be related to the refresh_token grant request... I thought ADFS needs something like this:

client_id=f2c5c411-8f32-49ca-b8ff-536c0f7cb362&**resource**=urn%3AApp%3AAzure%3AGeneric%20openid%20profile%20offline_access&grant_type=refresh_token

**Comment by tnorling** [comment]
@remkm01 Just to clarify, you are receiving an access token from your ADFS server using MSAL.js but when you try to use it on your resource validation fails? Has this worked for you when acquiring the token through other means? Have you tried decoding the token to determine what is missing or different? If MSAL.js is getting you a token but the contents are incorrect it's likely due to some misconfiguration on the server, we're unfortunately not very familiar with ADFS configuration so you may be better served opening a support ticket with Microsoft with these types of questions.

**Comment by ghost** [comment]
@tnorling To clarify, I'm getting an access token from ADFS but when accessing the API, the audience validation fails at the service because the aud field is not set correctly. Yes, if you manually call the token endpoint as described above (use "resource" instead of "scope"), the access token returned has the correct aud value. If I open a ticket with Microsoft, they will say this is working as designed. If this library is compatible with ADFS, shouldn't it just work?

**Comment by tnorling** [comment]
I see. Is the rest of the token correct? We do support ADFS 2019+ as long as it is OIDC compliant and supports scopes and PKCE. See more [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/docs/ADFS.md). We do not support the `resource` parameter.

**Comment by ghost** [comment]
Sorry to be blunt, but how can you say you support ADFS 2019+?  Am I doing something wrong?

The token is not what I expect either... The service only requires a few "claims". Looks like the token sent to the service is basically a copy of the IdToken/AccessToken received during authentication.

**Comment by tnorling** [comment]
@remkm01 This is what you are passing as scope: `urn:App:Azure:Generic` but this doesn't look like a scope to me. A scope is typically in the form of `https://resource-url.com/scope-name`. And the resulting access token will have the audience set to the corresponding resource. If you need specific claims included in the token you can request them through the `claims` parameter on the auth request.

**Comment by ghost** [comment]
@tnorling Yes, `urn:App:Azure:Generic` is the scope I'm sending. This is just a URI assigned to the API for ADFS to locate and generate the access token:
![image](https://user-images.githubusercontent.com/5065217/195193698-bd5c84bd-8c45-41ed-aef2-f622d43001a4.png)

By specifying the "resource" identifier, the access token generated is concise and only sends what the service requires:
![image](https://user-images.githubusercontent.com/5065217/195194299-53475419-553a-4a0d-a98c-65f7d576ee07.png)

The access token sent to the service looks like this (using the scope parameter) by MSAL:
![image](https://user-images.githubusercontent.com/5065217/195196581-47c34886-165c-4fdb-a943-7d9fc76ee41e.png)

If you notice, the aud does not match the aud claim in the 2nd image

**Comment by tnorling** [comment]
Right so that's not actually a scope. The "scp" field in your access token shows "profile openid" which are default scopes appended by MSAL.js and in the absence of any other valid scopes will result in an access token intended for your application rather than an external resource (which is what's happening here). Wherever you configure your resource you need to create a scope and request that instead. To reiterate, we are not experts on ADFS so this type of configuration is something you'll need to open a support ticket to get help with if you need it.

**Comment by ghost** [comment]
I think I figured it out... I had to configure the Interceptor with the resourceId/scope (even though the scope isn't used here).  I setup 2 services within the application and was calling each one simultaneously and the calls were working as expected.  I will keep testing to make sure.

For those who are having issues, make sure to configure the Interceptor as follows:

export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
  const protectedResourceMap = new Map<string, Array<string>>();
  protectedResourceMap.set('https://localhost:7299/*', **['urn:Service:Weather1/profile']**);
  protectedResourceMap.set('https://localhost:7298/*', **['urn:Service:Weather2/profile']**);

  return {
    interactionType: InteractionType.Redirect,
    protectedResourceMap
  };
}

"urn:Service:Weather1" is the resource id and the "profile" is the scope (**can be anything**).
