### ISSUE TITLE
MSAL Configuration: 'Telemetry' Description Update

### ISSUE THREAD

**Issue by olafwrieden** [AzureAD/microsoft-authentication-library-for-js#5294]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL React (@azure/msal-react)

### Public or Confidential Client?

Public

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/configuration.md#telemetry-config-options

### Description

I would like to find out more about the MSAL Configuration for `telemetry` and found [this doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/configuration.md#telemetry-config-options) which mentions the possible configuration options. Every section seems to contain useful information in the description except for `Telemetry`.

- Could someone update the description to make it a bit clearer what this configuration actually does?
- Where does the `telemetry` (i.e. application name and version) get used? Is this written to logs and used to help filter out auth logs by application, say with Log Analytics or is there another purpose for this configuration?

**Comment by tnorling** [comment]
@olafwrieden These values get sent to our internal logs on every network request. They are used by our first party (Microsoft) applications and are generally not something external developers need to provide. Is there something you are looking for in terms of telemetry features?

**Comment by olafwrieden** [comment]
> @olafwrieden These values get sent to our internal logs on every network request. They are used by our first party (Microsoft) applications and are generally not something external developers need to provide. Is there something you are looking for in terms of telemetry features?

Thanks, that's all I was looking for. I was thinking maybe this value is visible to me in Application Insights somewhere or can be used to filter logs if I have multiple apps using the same Application ID. No further info required but it might be good to update the docs to inform users what this value does and where it becomes visible to them if they define it.

**Comment by sameerag** [comment]
Sure. We have plans to update the docs soon.  I have marked an internal ticket to track this.
Thanks for reaching out.
