### ISSUE TITLE
Setting custom https.Agent for msal-node

### ISSUE THREAD

**Issue by aleknik** [AzureAD/microsoft-authentication-library-for-js#5295]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.14.2

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Confidential

### Description

Is it possible to set a custom https.Agent for msal-node confidential client? I see there is a way to set networkClient as INetworkModule. Can the default INetworkModule be extended to use custom https.Agent?

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
No we do not expose a way to configure the default implementation. If you need to use a different https agent you will need to provide your own custom implementation of `INetworkModule`.

**Comment by aleknik** [comment]
We are ok with using the default implementation of INetworkModule, so having our own implementation and maintaining it just so we can specify an http agent is not a good idea for us. It would be good if we could configure MSAL directly to use a custom https agent. Can we contribute to the project by adding support for http agent in the MSAL config, or another option would be to export the default implementation of  INetworkModule and inject the http agent through the contractor and provide it as a custom implementation of INetworkModule?

**Comment by tnorling** [comment]
We do welcome external contributions, please feel free to open a PR with a suggested implementation. I think I would personally lean towards option 2 of the ones you've described.

**Comment by Robbie-Microsoft** [comment]
@aleknik Just curious, what is your scenario for wanting a custom https agent?

**Comment by aleknik** [comment]
@Robbie-Microsoft We have some custom agent configuration we use across the service like setting keep alive, max sockets, dns cache, socket connection timeout, limiting socket concurrency and churn.
