### ISSUE TITLE
Public API for access token

### ISSUE THREAD

**Issue by rajarameshvarma** [AzureAD/microsoft-authentication-library-for-js#530]
## I'm submitting a...
[X ] Feature request
[X ] Documentation issue or request

## Library version: 0.2.4

Is there a public API to obtain access token from cache? as of now, we are adding access token to session storage after obtaining this via acquireTokenSilent. However this token is already added to the session storage by MSAL.

is there a way to read the access token from cache with out storing it again?

Thanks

**Comment by navyasric** [comment]
@rajarameshvarma As you mentioned, MSAL.js caches the access token in the browser storage. Can you explain what is the reason or scenario in which you need to read the access token? As a client getting access tokens, you should only be using it to access an API or resource and the access token should be opaque to you.

**Comment by rajarameshvarma** [comment]
We are getting access token during user login process. We would want to use this token if the user comes back to the app (before the id_token or access_token expires, assuming we are not using session storage). Though MSAL.js caches the access token, I have no way to get it. For this reason, I am adding it to the storage.

**Comment by mpalumbo7** [comment]
The method `acquireTokenSilent()` retrieves the token from cache for you, if one already exists and has not expired. See the wiki for [acquireTokenSilent](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Public-APIs#acquire-token-apis)

However, the function returns a promise and not the token directly. You'll need to use it like this:

```javascript
msal.acquireTokenSilent(config.auth.scopes).then(
      (accessToken) => {
        // You have access to the token here        
        console.log(accessToken);
        // Call some function with it
        myFunction(accessToken);
      },
      () => {
        // Open a redirect page in case the token is bad
        this.auth.acquireTokenRedirect(config.auth.scopes);
      }
    );
```

**Comment by navyasric** [comment]
The above comments should address your issue. Closing this issue.
