### ISSUE TITLE
adal-node depends on @xmldom/xmldom that has a security vulnerability

### ISSUE THREAD

**Issue by carpusherw** [AzureAD/microsoft-authentication-library-for-js#5302]
### Core Library

ADAL Node (adal-node)

### Core Library Version

0.2.3

### Wrapper Library

Not Applicable

### Wrapper Library Version

N/A

### Public or Confidential Client?

Public

### Description

The `adal-node` package has a dependency on `@xmldom/xmldom` which in turn has a security vulnerability. Please see https://github.com/advisories/GHSA-9pgh-qqpf-7wqj

### MSAL Configuration

```javascript
N/A
```

### Relevant Code Snippets

```javascript
https://github.com/advisories/GHSA-9pgh-qqpf-7wqj
```

### Reproduction Steps

https://github.com/advisories/GHSA-9pgh-qqpf-7wqj

### Expected Behavior

Package should be installable without any npm audit errors

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Source

External (Customer)

**Comment by carpusherw** [comment]
Oh I just saw this #5300

**Comment by tnorling** [comment]
The linked pull request will address this. Please be aware that adal-node is deprecated and will no longer be receiving any updates as of [December 31st, 2022](https://github.com/azure-deprecation/dashboard/issues/60) You should [migrate to msal-node](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-node-migration) ASAP.

**Comment by carpusherw** [comment]
> The linked pull request will address this. Please be aware that adal-node is deprecated and will no longer be receiving any updates as of [December 31st, 2022](https://github.com/azure-deprecation/dashboard/issues/60) You should [migrate to msal-node](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-node-migration) ASAP.

Cross post to https://github.com/Azure/ms-rest-nodeauth/issues/146

**Comment by carpusherw** [comment]
@tnorling, would you release a new version, supposedly 0.2.4?

**Comment by tnorling** [comment]
Yes, we have a release currently scheduled for next Monday. Will make sure this gets out. cc. @sameerag

**Comment by bejuzb0** [comment]
Any updates on adal-node 0.2.4 ? @tnorling I wasn't able to find any new version.

**Comment by tnorling** [comment]
Apologies the release slipped. @sameerag can provide updates. Reopening this until the new version is released

**Comment by sameerag** [comment]
Since this is a one off release on an old branch, we hit some snag in the process. I am on it to resolve this and will update here as soon as I can. Thanks for reopening @tnorling!

**Comment by bejuzb0** [comment]
Thank you ! Looking forward to an update

**Comment by carpusherw** [comment]
I believe the label is added unintentionally and we are still waiting for the update.

**Comment by sameerag** [comment]
Released [0.2.4](https://www.npmjs.com/package/adal-node/v/0.2.4) with this change.
