### ISSUE TITLE
uglifyjs unexpected token name (MsalGuard)

### ISSUE THREAD

**Issue by NaceurBouhamed** [AzureAD/microsoft-authentication-library-for-js#531]
Hi everyone,
I'm having an issue while trying to build using --prod with msal-angular@0.1.1 and **Angular 4** .
I tried along both :
- 0.1.0 : fails using --aot flag
- 0.1.2 : fails while serving ( metadata version mismatch which is the reason I downgraded to 0.1.1 in first place )

The error output while building is as following :
`uglifyjs unexpected token name (MsalGuard)`
I tried upgrading the uglifyjs version that comes nested with angular to the harmony version. Still no luck till now.

Did anyone encounter this error by any chance ? If not, is there any fix or alternative solution to counter this error ?

Thanks !

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Library version

<pre><code>
Library version: 0.1.1

## Current behavior
Not building 
`uglifyjs unexpected token name (MsalGuard)`

## Expected behavior
Building like it should

## Minimal reproduction of the problem with instructions
1. Create a project using Angular 4
2. Install @azure/msal-angular@0.1.1 version using your favorite node package manager
3. Build using --prod flag

</code></pre>

**Comment by sameerag** [comment]
@NaceurBouhamed Is this issue still seen?

**Comment by NaceurBouhamed** [comment]
> @NaceurBouhamed Is this issue still seen?

not sure, but probably yes. What I did though to avoid the error on 0.1.1, is transpiling the whole package files using babel and then running the build again.  Seems Angular 4 uglify fails because it doesn't handle es6 files well at that time.

**Comment by sameerag** [comment]
Okay. There is recently a fix that helped with Angular ES6 compilation, please take a look @ #785. I am closing this issue since it seems to be more of a transpilation issue which I believe is resolved with the above PR. 

If you think it is not resolved by the #785, please feel free to reopen.

Thanks for the prompt response.
