### ISSUE TITLE
acquireTokenSilent not returning an error

### ISSUE THREAD

**Issue by 72gm** [AzureAD/microsoft-authentication-library-for-js#5310]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.28.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.5

### Public or Confidential Client?

Public

### Description

If I call the following 

`export const acquireAccessToken = async (
  theInstance: IPublicClientApplication,
  theAccount: AccountInfo,
  theScopes: string[]
) => {
  const accessTokenRequest = {
    scopes: theScopes,
    account: theAccount,
  };

  const result = await theInstance.acquireTokenSilent(accessTokenRequest);

  return result;
};
`

with the incorrect scopes I get an empty token back and no error - should this not throw an error? 

If I'm trying to get a token and it fails then that's an error in my book... Otherwise I have to check for an empty token and fire an error

Thanks

### Error Message

No error message but empty token

### MSAL Configuration

```javascript
config isn't an issue
```

### Relevant Code Snippets

```javascript
as above
```

### Reproduction Steps

set the scopes to a value that is wrong

### Expected Behavior

I'd expect an error

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by sameerag** [comment]
MSAL JS is only a token acquisition library and not a token validation library. When we require a token with a set of scopes, the authentication service issues a token for the specific scopes the user consented to and is allowed to be issued a token for. You can refer the documentation [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/resources-and-scopes.md) and [here](https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent). 

However, if a wrong scope is requested, unless none of the scopes can be issued, STS does not fail the request, it issues the token with the set of scopes it can issue the tokens for. This behavior depends on the service and not on MSAL, as MSAL JS does not open/validate the token before returning it to the user. The `token validation` libraries or the resource determines if the given token cannot be applied.

Can you share what the scopes are coming back as? I am also involving the CXP team if they have specific usage guidance in this case.

cc @derisen

**Comment by derisen** [comment]
@72gm if the scope string you are passing to `acquireToken*` is malformed or invalid somehow, B2C will respond with an error, and MSAL will resurface that error to you. Other than that, the scope might be valid but the service might not carry out the request. In B2C for instance, if you haven't declared the required permissions in the app registration, it will not issue the user an access token, since users cannot consent for themselves. Also in the case of B2C, there won't be an initial access token when the user signs-in for the first time, unless the app passes a resource scope to the login request (this is in contrast to AAD). Because of these differences, it's a good idea to consider `accessToken=null` in B2C scenarios.

Please share the exact scope you are passing to MSAL and also confirm if you have granted admin consent for that permission.

**Comment by 72gm** [comment]
@sameerag & @derisen many thanks for the quick responses.

In my scenario the DevOps had failed to set up the scopes correctly named. My application was handling tokens and errors but not empty string tokens, so it blew my application up

I can't remember the exact detail of the original scenario but if I call B2C with 'scope2' instead of 'scope1' the access token being returned from B2C is an empty string (rather than a null)

![image](https://user-images.githubusercontent.com/12847881/196682363-eae9d714-3e7b-4e73-a6b7-dd357f77f59d.png)

Personally, I think an empty string in this scenario isn't correct!? But I check for empty and deal with it that way if this is the expected behaviour

**Comment by derisen** [comment]
@72gm I agree the inconsistency here is confusing, but MSAL merely constructs the response object with what is coming from the service. Perhaps MSAL can set the `accessToken` property to null when it's an empty string, but this would make it opiniated about the service response. @sameerag @tnorling thoughts?

**Comment by tnorling** [comment]
Changing the response type would be a breaking change which we cannot do now but may consider for future versions of the library. That said, empty access token is unexpected and indicates a configuration error - once you've addressed the issue in your code you shouldn't have this problem anymore. Checking for empty string (or even better - truthiness) would help you identify this problem in the future.

**Comment by sameerag** [comment]
Closing this as we cannot make the changes suggested above.
