### ISSUE TITLE
400 bad request error while Sign In

### ISSUE THREAD

**Issue by anjalikalsariya** [AzureAD/microsoft-authentication-library-for-js#5311]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.22.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.3.0

### Public or Confidential Client?

Public

### Description

Can't be able to do azure b2c login with two tabs.

Reproduce the error:
Step: 1 Open the login page in two tabs.
Step 2: Now go to the first tab and do login and left the tab as it is.
Step 3: Now go to second tab and try to do login
Step 4: See the network tab of second you will get error of 400 bad request

### Error Message

![image](https://user-images.githubusercontent.com/13288691/196460773-bdc5cde4-343e-4751-b064-5967149f137c.png)

### MSAL Configuration

```javascript
const msalConfig: Configuration = {

    auth: {
        clientId: xyz....,
        authority: b2cPolicies.authorities.signUpSignIn.authority,
        knownAuthorities: [b2cPolicies.authorityDomain],
        redirectUri: process.env.REACT_APP_AUTH_REDIRECT_URI,
        postLogoutRedirectUri: process.env.REACT_APP_AUTH_REDIRECT_URI,
        navigateToLoginRequestUrl: true
    },
    cache: {
        cacheLocation: BrowserCacheLocation.SessionStorage,
        storeAuthStateInCookie: isIE
    }
}
```

### Relevant Code Snippets

```javascript
----
```

### Reproduction Steps

Step: 1 Open the login page in two tabs.
Step 2: Now go to the first tab and do login and left the tab as it is.
Step 3: Now go to second tab and try to do login
Step 4: See the network tab of second you will get error of 400 bad request

### Expected Behavior

It should not return 400 error instead it should do login as usual.

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer, None (Server), Other

### Source

Internal (Microsoft)

**Comment by sameerag** [comment]
@anjalikalsariya Can you share us msal logs? You can enable them as instructed [here](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-logging-js).

**Comment by anjalikalsariya** [comment]
@sameerag I have added below msal config

export const msalConfig: Configuration = {

    auth: {
        clientId: clientId,
        authority: b2cPolicies.authorities.signUpSignIn.authority,
        knownAuthorities: [b2cPolicies.authorityDomain],
        redirectUri: process.env.REACT_APP_AUTH_REDIRECT_URI,
        postLogoutRedirectUri: process.env.REACT_APP_AUTH_REDIRECT_URI,
        navigateToLoginRequestUrl: true
    },
    cache: {
        cacheLocation: BrowserCacheLocation.SessionStorage,
        storeAuthStateInCookie: isIE
    },
    system: {
        loggerOptions: {
            loggerCallback: (level: LogLevel, message: string, containsPii: boolean): void => {
                if (containsPii) {
                    return;
                }
                switch (level) {
                    case LogLevel.Error:
                        console.error(message);
                        return;
                    case LogLevel.Info:
                        console.info(message);
                        return;
                    case LogLevel.Verbose:
                        console.debug(message);
                        return;
                    case LogLevel.Warning:
                        console.warn(message);
                        return;
                }
            },
            piiLoggingEnabled: true
        },
        windowHashTimeout: 60000,
        iframeHashTimeout: 6000,
        loadFrameTimeout: 0,
        asyncPopups: false
    }
}

**And not getting any log in inspect.**
![image](https://user-images.githubusercontent.com/13288691/196608149-77d74a52-4b57-4eca-bd30-07a2ac060dd7.png)

**Comment by sameerag** [comment]
Please set `logLevel: LogLevel.Trace` in your `config` options and collect MSAL JS logs in the Console. An example can be found [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-browser-samples/VanillaJSTestApp2.0/app/default/authConfig.js).

@bmahal assigning this to you for follow up.

**Comment by bmahall** [comment]
@anjalikalsariya Can you please share verbose logs on email mentioned on my profile, if they are not showing up for some reason, please update.
