### ISSUE TITLE
Device Code Flow in msal-browser

### ISSUE THREAD

**Issue by ToshB** [AzureAD/microsoft-authentication-library-for-js#5312]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

Not Applicable

### Public or Confidential Client?

Public

### Description

I'd like to request support for Device Code flow in msal-browser (in addition to msal-node).

I have several applications where the auth code flow doesn't give the best user experience, due to several reasons.
- The page is displayed on a dashboard display with no keyboard connected
- The page is displayed inside applications like Adobe Premiere, with isolated cookie storage, so there is no single sign-on
- The browser part of an electron app where I have to use msal-node due to the page not having a non-http url, so msal-browser won't work. (This one works ok with msal-node, but it feels unnecessarily complicated. And there is isolated cookie storage, so I'm rewriting this to device code flow to take advantage of browser cookies).

I understand that it could be confusing for users if both msal-node and msal-browser were to both support device code flow, but I think this flow is applicable in both scenarios, where a browser application also can be input-constrained, doesn't have an URL, or is isolated from browser cookies - which breaks single sign-on.

### Source

External (Customer)

**Comment by sameerag** [comment]
@ToshB Thanks for raising this. `msal-browser` is a specific type of public client (SPA) which has certain restrictions on the RT issued etc. Expanding it to device-code may not be feasible as is. 

However, we do think browsers with limited i/p or interface is a good use case. We are exploring some solutions internally in MSFT to address similar scenarios and the 3P cookies being blocked on most browsers. We will be announcing as they come and will update our roadmap.

**Comment by sameerag** [comment]
Closing this as no immediate solution is viable here.

**Comment by simongymer** [comment]
We have the same requirement where we run a Javascript application on a device that has no keyboard, so we need device code flow within Javascript. Our back-end is NOT node-js so we have no way to use msal-node.
