### ISSUE TITLE
Azure AD B2C user flow name can break token cache

### ISSUE THREAD

**Issue by goester-team23** [AzureAD/microsoft-authentication-library-for-js#5313]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.30.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.4.5

### Public or Confidential Client?

Public

### Description

The implementation of [`getCredentialType`](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/src/cache/entities/CredentialEntity.ts#L110) is ambiguous and can result in false positives.

The reason for this is that the `key` that is passed to the function contains the string an Azure user inputs for its user flow. When the user names his user flow for example `B2C_1_AccessToken`, this string will be part of the `key` (in lowercase), i.e. the key will look something like `...-b2c_1_accesstoken-...`. Thus the `getCredentialType` function will always return `CredentialType.ACCESS_TOKEN` as type of the key, as it just checks if the string `'accesstoken'` is present in `key`.

This actually happened to me as my admin used such a name for the user flow. I was implementing a token refresh in my application using `MsalService.acquireTokenSilent`.

Some more details: According to my knowledge, msal stores the idtoken, access token and refresh token in its cache (in my case in the browsers local storage). As the cache is a <key,value>-store, it needs a `key` to identify the objects that represent those tokens. The key composed of:
`[SOME-UUID]-[NAME_OF_AZURE_USER_FLOW].[AZURE_DIRECTORY_TENANT_ID]-[AZURE_AD_B2C_HOSTNAME]-[TYPE_OF_TOKEN]-[AZURE_APPLICATION_CLIENT_ID]----`
Where TYPE_OF_TOKEN is one of `idtoken`, `accesstoken` or `refreshtoken`. The current implementation of `getCredentialType` assumes that all other parts of the key do not contain one of those strings, which is actually not correct, as the Azure user flow name is set by the user and may contain those strings.

### MSAL Configuration

```javascript
{
        auth: {
            clientId: environment.AZURE_APPLICATION_CLIENT_ID,
            authority,
            knownAuthorities: [authority],
            redirectUri,
            postLogoutRedirectUri,
            navigateToLoginRequestUrl: true,
        },
        cache: {
            cacheLocation: 'localStorage',
            storeAuthStateInCookie: false, // Set to true for Internet Explorer 11
        },
        system: {
            loggerOptions: {
                logLevel: LogLevel.Verbose,
                piiLoggingEnabled: false,
            },
        },
    });
}
```

### Relevant Code Snippets

```javascript
-
```

### Reproduction Steps

1. Setup an Azure user flow with the name `B2C_1_AccessToken`
2. Implement a token refresh using `MsalService.acquireTokenSilent`

### Expected Behavior

It will refresh the token.

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by sameerag** [comment]
@goester-team23 good find. Since credential look up is a substring-based search, I see why this can happen. Let me mark this as a bug on our end.

**Comment by sameerag** [comment]
Internally tracked, will be assigned when there is someone working on it.
