### ISSUE TITLE
acquireTokenSilent after 8 hour 

### ISSUE THREAD

**Issue by alexseyrakov** [AzureAD/microsoft-authentication-library-for-js#5315]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.29.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

We use the MSAL library to access corporate resources.
After 8 hours, acquireTokenSilent stops receiving a new token and asks for re-authorization in ADFS.

### Relevant Code Snippets

```javascript
//MSAL Config
const msalConfig = {
  auth: {
      clientId: APPID,
      authority: 'https://corporate.network/adfs/', 
      knownAuthorities: ['https://corporate.network/adfs/'], 
      redirectUri: REDIRECTURL, 
      
  },
  cache: {
      cacheLocation: "localStorage",
      storeAuthStateInCookie: false, 
  },
};

//acquireTokenSilent
async function refreshWebToken(){

  return await msalInstance.acquireTokenSilent(silentRequest).catch(async (error) => {
    if (error instanceof msal.InteractionRequiredAuthError) {
        return await msalInstance.acquireTokenPopup(loginRequest).catch(error => {
            console.log(error);
        });
    }
});
}
```

### Identity Provider

ADFS

### Source

External (Customer)

**Comment by sameerag** [comment]
@alexseyrakov Thanks for reaching out. We try to acquire/refresh tokens silently as long as the session is valid. Can you share the exact error message you see?

**Comment by alexseyrakov** [comment]
> @sameerag 
in console
"MSIS9615: The refresh token received in 'refresh_token' parameter has expired."

**Comment by sameerag** [comment]
@alexseyrakov This could be the policy set by your admin. `msal-js` does not control the expiration times, the token issuance does which depends on many factors. 

@derisen can you help here or redirect this to support who can help?

**Comment by alexseyrakov** [comment]
@sameerag @derisen 
Thanks
Tell me please, what settings on the ADFS server are responsible for this settings?

**Comment by derisen** [comment]
@alexseyrakov Let me reach out to some internal partners about this. In the meantime, could you capture a network trace with [Fiddler](https://www.telerik.com/fiddler/fiddler-classic) when this happens, and then send it to me (you can find my email on my [profile](https://github.com/derisen))?

**Comment by derisen** [comment]
@alexseyrakov apologies for the late response. 8 hours seems to be the default configuration with ADFS -you can find more on this [here](https://learn.microsoft.com/windows-server/identity/ad-fs/operations/ad-fs-single-sign-on-settings). In general refresh tokens can be invoked at any time for a variety of reasons, and your application shouldn't assume an interval and should be ready to handle the error (by re-authenticating the user). Longer lived refresh tokens are not always desirable for enhanced security.

Closing this -feel free to open another issue if you have other questions.
