### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by dbelyaev** [AzureAD/microsoft-authentication-library-for-js#5316]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Public or Confidential Client?

Public

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples

### Description

* Broken link

[Multi-tenant tutorial using MSAL Angular v2](https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/tree/main/6-Multitenancy/1-call-api-mt) target of this link in the documentation does not exist.

**Comment by derisen** [comment]
@dbelyaev Thanks for catching that! A fix is underway.

**Comment by sameerag** [comment]
Fix is in progress.
