### ISSUE TITLE
Cannot build the vue3-sample-app 

### ISSUE THREAD

**Issue by bui2jp** [AzureAD/microsoft-authentication-library-for-js#5317]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.26.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

2.18.0

### Public or Confidential Client?

Public

### Description

reg, samples/msal-browser-samples/vue3-sample-app

i cannot build the vue3-sample-app with following error.

can anyone help me for this issue?

`
$ npm run build

> msal-vue-sample@0.0.0 build /Users/takuya/microsoft-authentication-library-for-js/samples/msal-browser-samples/vue3-sample-app
> vue-tsc --noEmit && vite build

src/views/Profile.vue:2:14 - error TS2304: Cannot find name 'state'.

2   <div v-if="state.resolved">
               ~~~~~

src/views/Home.vue:3:18 - error TS2304: Cannot find name 'isAuthenticated'.

3     <span v-if="!isAuthenticated">Please sign-in to see your profile information.</span>
                   ~~~~~~~~~~~~~~~

src/views/Profile.vue:3:14 - error TS2304: Cannot find name 'state'.

3  <p>Name: {{ state.data.displayName }}</p>

:

node_modules/element-plus/es/utils/objects.d.ts:1:30 - error TS2307: Cannot find module 'type-fest' or its corresponding type declarations.

1 import type { Entries } from 'type-fest';
                               ~~~~~~~~~~~


Found 17 errors in 9 files.

Errors  Files
     6  src/views/Profile.vue:2
     2  src/views/Home.vue:3
     1  src/components/WelcomeName.vue:3
     2  src/components/SignOutButton.vue:6
     2  src/components/SignInButton.vue:6
     1  src/components/NavBar.vue:13
     1  node_modules/element-plus/es/components/table-v2/src/components/sort-icon.d.ts:5
     1  node_modules/element-plus/es/components/table-v2/src/types.d.ts:92
     1  node_modules/element-plus/es/utils/objects.d.ts:1
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! msal-vue-sample@0.0.0 build: `vue-tsc --noEmit && vite build`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the msal-vue-sample@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/takuya/.npm/_logs/2022-10-20T10_45_54_786Z-debug.log
`


### MSAL Configuration

_No response_

### Relevant Code Snippets

_No response_

### Identity Provider

_No response_

### Source

External (Customer)

**Comment by bui2jp** [comment]
I found that it works without "vue-tsc --noEmit".

**Comment by derisen** [comment]
@bui2jp I can reproduce this. There are two issues here: 

(1) view files (Profile.vue, ProfileNoGuard.vue) don't have a type for the displayed data from Graph, so you could just define one to resolve.
(2) Typescript complaining about some dependencies in the `node_modules` folder. These are outside of your control so not much to do. I tried excluding them but this doesn't seem to work. So another alternative is to add [skipLibCheck ](https://www.typescriptlang.org/tsconfig#skipLibCheck) to `tsconfig.json` (this will skip type checking of all .d.ts files, including the project's own, though that is less of a concern in a project like this).

Will update the sample to resolve these. Thanks for catching this!

**Comment by derisen** [comment]
@bui2jp fyi just updated the sample -thanks again for catching this.
