### ISSUE TITLE
How to capture network traffic for a nodejs app?

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-js#5319]
### Core Library

MSAL Node (@azure/msal-node)

### Wrapper Library

Not Applicable

### Public or Confidential Client?

Confidential

### Documentation Location

msal wiki or samples or docs.ms

### Description

1. Run the sample https://github.com/Azure-Samples/ms-identity-javascript-nodejs-console
2. Get into some problem with it
3. Contact the team, who'll ask for logs and network traces

Actual: it's not easy to get network traces (e.g. Fiddler doesn't seem to work) and there is no doc that explains how to do it.

**Comment by derisen** [comment]
Fiddler has some [guidance ](https://docs.telerik.com/fiddler-everywhere/knowledge-base/how-to-capture-nodejs-traffic) for setting up a proxied http client, which could be used as a custom network client with msal-node. There's this [FAQ item](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/faq.md#why-doesnt-my-app-function-correctly-when-its-running-behind-a-proxy) that hints at this, but a more direct guidance would be great indeed (it also seems a little outdated cc @EmLauber @Robbie-Microsoft)

**Comment by Robbie-Microsoft** [comment]
@bgavrilMS As I seem to remember, when you open Fiddler, it acts as a proxy and all network traffic travels through it. I think that Node doesn't like traveling through proxies and that you need to make a new rule in the Firewall to allow outbound traffic on port 8888 (default Fiddler port). See step #3 my description [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/4744#issue-1217867803) - I was able to simulate running a node app behind a corporate proxy (via Fiddler), and see the network trace.

**Comment by Robbie-Microsoft** [comment]
@derisen Looks like that guidance is out of date. MSAL-Node no longer uses axios, I re-wrote the default network manager to use node's native http/https modules. I think the first 3 sentences should be deleted.

**Comment by sameerag** [comment]
@Robbie-Microsoft @derisen can we please make the FAQ doc changes as needed?

**Comment by Robbie-Microsoft** [comment]
@sameerag yes. @bgavrilMS @derisen. I actually just put the finishing touches on a small typescript msal-node project that's able to have it's network traffic traced in Fiddler! Will share the sample tomorrow.
