### ISSUE TITLE
msal-angular - Support redirectUrl to be a function

### ISSUE THREAD

**Issue by hansmaad** [AzureAD/microsoft-authentication-library-for-js#532]
## I'm submitting a...
<pre><code>
[x] Feature request
</code></pre>

msal-core allows `redirectUrl` to be a function:
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/ac32c459c7398be02fe3f50afbd7d38e19d8ef0e/lib/msal-core/src/UserAgentApplication.ts#L231

But msal-angular not:
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/ac32c459c7398be02fe3f50afbd7d38e19d8ef0e/lib/msal-angular/src/msal-config.ts#L10

It's already working when doing

       MsalModule.forRoot({
            clientID: '...',
            redirectUri: <any>makeRedirectUrl,
        }),

so it seems to be a typing issue only.

Same for `postLogoutRedirectUri` of course...

**Comment by sameerag** [comment]
@hansmaad This will be a part of our angular wrapper upgrade to msal core release 1.0.0 coming soon in summer. The [roadmap](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#roadmap) will be added with more details once we start this activity.

**Comment by sameerag** [comment]
Linking this with #786
