### ISSUE TITLE
Firefox v103.0.1+ does not show popup screen during authentication

### ISSUE THREAD

**Issue by musale** [AzureAD/microsoft-authentication-library-for-js#5324]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

^2.22.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

N/A

### Public or Confidential Client?

Public

### Description

The [Microsoft Graph Toolkit](https://learn.microsoft.com/toolkit) uses the `msal-browser` package in their Teams Provider for authentication. There are [issues](https://github.com/microsoftgraph/microsoft-graph-toolkit/issues/1866) where the pop up doesn't show in the latest versions of Firefox. This is because Firefox has implemented a [Total Cookie Protection](https://blog.mozilla.org/en/mozilla/firefox-rolls-out-total-cookie-protection-by-default-to-all-users-worldwide/) policy which prevents cross-site sharing of cookies, in this case the `clientId` in the browser.

### MSAL Configuration

```javascript
N/A
```

### Relevant Code Snippets

```javascript
N/A
```

### Reproduction Steps

This issue https://github.com/microsoftgraph/microsoft-graph-toolkit/issues/1866 contains all the reproduced steps.

### Expected Behavior

The authentication popup should appear in the latest Firefox browser.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Firefox

### Source

Internal (Microsoft)

**Comment by sameerag** [comment]
CC @EmLauber. Can we confirm if firefox supports AAD logins in `total cookie protection` mode?

**Comment by EmLauber** [comment]
We are still investigating this.

**Comment by sameerag** [comment]
@EmLauber assigning to you just for traction, please pull me in as needed.
