### ISSUE TITLE
Cancelling editProfile or changePassword flows lead to access_denied

### ISSUE THREAD

**Issue by daniel-seitz** [AzureAD/microsoft-authentication-library-for-js#5325]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.30.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

n.a.

### Public or Confidential Client?

Public

### Description

We are calling loginRedirect with 

    { authority: `${cloudInstance}/${tenant}/${changePasswordPolicyId}` } 

and are directed to the correct page.

However when **cancelling** there, the resulting Error is

    errorCode: "access_denied"
    errorMessage: "AADB2C90091: The user has cancelled entering self-asserted information...
    name: "ServerError"

This Code should not be **"access_denied"** but rather something like "cancelled" nor should the name be **ServerError** . We i.e. use this code in order to determine if the user cancelled the normal login flow or if there really was something wrong, like a wrong password or so. Hence I'd like to be able to distinguish these two.

### Error Message

see above

### MSAL Configuration

```javascript
normal
```

### Relevant Code Snippets

```javascript
see above, just test with your setup and cancel the flow.
```

### Reproduction Steps

see above

### Expected Behavior

see description

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge

### Source

External (Customer)

**Comment by sameerag** [comment]
cc @nickgmicrosoft Is there a specific reason for this error from B2C?
@daniel-seitz We are relaying the server error and it is possible the error messaging is accurate in the sub_code. I have tagged our B2C contact to help with this.

**Comment by daniel-seitz** [comment]
According to https://learn.microsoft.com/en-us/azure/active-directory-b2c/error-codes this is a defined and expected _error_ so technically the message is forwarded correctly but the _errorCode_ is not. The term "access_denied" is not correct.

I'd like to stress the definition of the word _error_ though and suggest a different usage here. A cancel operation is not an error but for me a result of a user interaction. - I guess this would be a breaking change, wouldn't it?

**Comment by sameerag** [comment]
This should be handled by the service team. 
Please file a support ticket with the B2C team by following the instructions here: [B2C support options](https://docs.microsoft.com/azure/active-directory-b2c/support-options).

**Comment by daniel-seitz** [comment]
@sameerag we dont have direct access to this. It would be a great customer experience if MS is able to clarify this internally.

**Comment by sameerag** [comment]
@EmLauber can we track this with B2C? @nickgmicrosoft Can you check this please and redirect @daniel-seitz to appropriate teams?

**Comment by daniel-seitz** [comment]
no pressure, rather needs feedback from @EmLauber or @nickgmicrosoft.

**Comment by peterzenz** [comment]
@EmLauber moving to you to own.  Thanks!

**Comment by EmLauber** [comment]
@daniel-seitz I'm working on tracking this internally with the B2C team. To confirm, you said this process of filing a support ticket with B2C directly didn't work for you? https://learn.microsoft.com/en-us/azure/active-directory-b2c/support-options

**Comment by daniel-seitz** [comment]
@EmLauber I could, of course, with another account but actually it would be a nicer user experience if you can handle that internally. great to 'see' you actually at the AppDevTrack last week :)

**Comment by peterzenz** [comment]
@daniel-seitz we'll need you to submit your request on the link that Emily has above.  Thanks!

**Comment by daniel-seitz** [comment]
I wont.
Its a problem I encounter here and if you think that another team, delivering information to your library has to change something I would really appreciate if you handle this internally. I have a workaround and can live with it, up to you now.

**Comment by sameerag** [comment]
My two cents on this @daniel-seitz : We have already done that due diligence and this is already forwarded to the B2C team internally. However, please note that considering the volume of issues we get in github, it is much easier to reach out B2C support channel for the relevant issues to gain traction from the B2C team.
