### ISSUE TITLE
PopupWindowAttributes is not exported

### ISSUE THREAD

**Issue by izikl** [AzureAD/microsoft-authentication-library-for-js#5332]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

Not Applicable

### Public or Confidential Client?

Public

### Description

loginPopup expects PopupRequest: 
```typescript
loginPopup(request?: PopupRequest): Observable<AuthenticationResult>;
```

PopupRequest type is:
```typescript
export type PopupRequest = Partial<Omit<CommonAuthorizationUrlRequest, "responseMode"|"scopes"|"codeChallenge"|"codeChallengeMethod"|"requestedClaimsHash"|"nativeBroker">> & {
    scopes: Array<string>;
    popupWindowAttributes?: PopupWindowAttributes;
};
``` 

Which allows popupWindowAttributes as parameter. However, this parameter is not exported in `\lib\msal-browser\src\index.ts`. Can this type be exported?

### Source

Internal (Microsoft)

**Comment by bmahall** [comment]
@izikl Can you provide more information on your specific use case ?
Normally, you can configure the popup window size as below:- (note: exact config such as scope values will depend on your use case)
`
    const popupRequest = {
        scopes:["Mail.Read"],
        popupWindowAttributes: {
            popupSize: {
                height: 100,
                width: 100
            },
            popupPosition: {
                top: 100,
                left: 100
            }
        }
    }

`

**Comment by izikl** [comment]
@bmahall 
We are trying to do it more typescript friendly:
![image](https://user-images.githubusercontent.com/8294298/198418508-2affc7ec-85d5-42e8-9c1a-51361651cf62.png)
 
We were also used this type `PopupRequest['popupWindowAttributes']` as a workaround:
![image](https://user-images.githubusercontent.com/8294298/198418666-b341c319-2f2c-49b2-95d1-9663d3c4cf7d.png)

**Comment by hectormmg** [comment]
@izikl thanks for raising the issue, I'll put the PR in to export this type.
