### ISSUE TITLE
How do I dynamically set the cachePlugin?

### ISSUE THREAD

**Issue by jim-moody** [AzureAD/microsoft-authentication-library-for-js#5335]
### Core Library

MSAL Node (@azure/msal-node)

### Wrapper Library

Not Applicable

### Public or Confidential Client?

Confidential

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/caching.md#performance-and-security

### Description

In this documentation, it talks about creating a custom `cachePlugin` that can partition a user's cache by the accountId. 

However, I don't see any way to instantiate the cachePlugin with the context from a particular request. i.e. when I call `const cca = new msal.ConfidentialClientApplication(config)` I do not have access to the user's accountId. It is only when a request comes in that I can access the user's accountId, and at that point the cachePlugin is already set.

How can I dynamically set the cachePlugin later in the process?

**Comment by bmahall** [comment]
@jim-moody Please refer to the latest documentation and the sample listed on caching:- [Caching.md](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/b96d4a1a9588d6587e2fbb65e6ba888f0ff469c3/lib/msal-node/docs/caching.md)

This is part of PR [#5003 ](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/5003)

**Comment by bgavrilMS** [comment]
CC @derisen 

We do have a sample integration with Express, see https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/RedisTestApp

The gist of it is to save the account id in a session. 

If the session has `account_id`, then use it to load an Account object and to call `AcquireTokenSilent`, which will silently give you a token. If this fails or if the session does not have the data, then you redirect the user to the login page, where they will get an auth code and have MSAL exchange that code for a token using `authorization_code` flow. It's all a bit complicated, so using the same should help. 

Please let me know if this answers your question.
