### ISSUE TITLE
acquiretokenredirect best practices guidance

### ISSUE THREAD

**Issue by 1hw7** [AzureAD/microsoft-authentication-library-for-js#5337]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.21.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.0

### Public or Confidential Client?

Public

### Description

Hi! I am just looking for guidance on best practice with acquireTokenRedirect.

We are using msal-react, but we have reusable functions we use to acquire tokens with msal-browser (not in any react component where we pass in the instance and context).

We have several parallel requests which run, and we are not sure what the best practice is for acquiring tokens by redirect.

It seems this is called several times on each failed acquireTokenSilent request when tokens have expired, causing a redirect loop of about 4 loops until the page loads. I'm wondering what guidance would be to fix our issue and improve how we are using msal.

Thanks so much!

### MSAL Configuration

```javascript
export const msalConfig = {
    auth: {
        clientId: config.auth.clientId,
        authority: 'https://login.microsoftonline.com/consumers',
        navigateToLoginRequestUrl: false,
        postLogoutRedirectUri: `${config.auth.redirectUrl || config.sasUrl}`,
        redirectUri: getRedirectUri()
    },
    cache: {
        cacheLocation: BrowserCacheLocation.LocalStorage,
    },
};
```

### Relevant Code Snippets

```javascript
get token function: const getToken = async (msalContext: IMsalContext, scopes: string[], telemetryService: ITelemetryService): Promise<AuthenticationResult> => {
    const msalInstance = msalContext.instance;
    const accounts = msalInstance.getAllAccounts();
    if (accounts.length > 0) {
        const silentRequest = {
            scopes,
            account: msalInstance.getActiveAccount() || accounts[0]
        };
        const redirectRequest = {
            scopes,
        };
        try {
            return await msalInstance.acquireTokenSilent(silentRequest);
        }catch (error) {
            if (error instanceof (InteractionRequiredAuthError)){
                try {
                    // fallback to interaction when silent call fails
                    if (msalContext.inProgress === InteractionStatus.None){
                        await msalInstance.acquireTokenRedirect(redirectRequest);
                    }
                }catch (e) {
                    telemetryService.trackError(e, TelemetryEventName.GetMsalTokenRedirect);
                    return null;
                }
            }
            telemetryService.trackError(error, TelemetryEventName.GetMsalTokenSilent);
            return null;
        }
    }
};




where we fetch token in axios interceptor (abstracted some away from here  as it's not really needed)

  constructor(msalContext: IMsalContext, telemetryService: ITelemetryService) {
        this.axiosInstance = axios.create();
        this.telemetryService = telemetryService;
        this.axiosInstance.interceptors.request.use(
            (config: ExtendedAxiosRequestConfig) => {
                config.requestId = createGuid();
                config.startTimeMs = performance.now();
                return new Promise((resolve, reject) => {
                    getToken(msalContext, telemetryService).then(tokenResult => {
                        if (!tokenResult) {
                            throw new AxiosError("No token");
                        }
                        const { accessToken } = tokenResult;
                        config.headers['Authorization'] = `Bearer ${accessToken}`;
                        config.headers['Content-Type'] = 'application/json';
                        config.headers['ms-cv'] = telemetryService?.getCorrelationVector(true);
                        if (config.telemetryEventName) {
                            config.headers['x-ms-operation-name'] = config.telemetryEventName;
                        }
                        resolve(config);
                    }, reject);
                });
            }
        );
```

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by 1hw7** [comment]
I was able to talk with @sameerag (thank you so much!) about our app and how we can improve our usage of msal. It would be great if there could be further docs made to explain best practices for concurrent requests. 

For anyone else who happens upon this: If you are sending off concurrent requests to fetch tokens which will fail due to expired refresh tokens, make sure you fall back to interactive sign in within the app page where you can detect if interaction is in progress,  and not within the code which is concurrently run to fetch tokens (as you may end up with more acquiretokenredirect requests sent off than you want)

**Comment by bmahall** [comment]
@1hw7 Thanks for updated comment, looking forward to connect on Monday as discussed.

**Comment by sameerag** [comment]
We will work on docs here, cc @derisen can we track this?

**Comment by sameerag** [comment]
@derisen I marked a work item for the actual support of concurrency (which we do not have a design today and needs work). However, in the short term we should document this to clarify that we do not support this and what is the best practice for cases developers may run into them.

**Comment by derisen** [comment]
@sameerag sounds good, tracking this internally

**Comment by joostmeijles** [comment]
I am experiencing this issue with a React application. Do you have an example of how to handle concurrent requests and `loginRedirect`?

For example, we currently have the following setup which results in multiple logins after the token expires:
```
export const instance = new PublicClientApplication({
  ...config.msalConfig,
  auth: {
    ...config.msalConfig.auth,
    redirectUri: window.location.origin, // Always redirect to the index page
  },
});

<MsalProvider instance={msalInstance}>
   <AuthenticatedTemplate>
         // Inside here multiple components that fetch concurrently
   </AuthenticatedTemplate>
   <UnauthenticatedTemplate>
          <SignIn />
    </UnauthenticatedTemplate>
</MsalProvider>

function SignIn() {
  const { instance } = useMsal();

  instance.loginRedirect(authRequest);

  return <></>;
}

function FetchingComponent() { 
   const { instance } = useMsal();
   
   ...

   try {
        const accessTokenResponse = await instance.acquireTokenSilent({
          scopes: [config.msalConfig.auth.requiredScope],
          account: instance.getAllAccounts()[0],
        });

        accessToken = accessTokenResponse.accessToken;
      } catch (error) {
        if (error instanceof InteractionRequiredAuthError) {
          // Token is expired
          await instance.loginRedirect(authRequest);
        } else {
          throw error;
        }
      }
    }
    ...
}
```

What is wrong with this setup?

**Comment by derisen** [comment]
@joostmeijles have a look at the usage examples [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/errors.md#interaction_in_progress). Also, not sure why you are handling `InteractionRequiredAuthError` with `loginRedirect` instead of `acquireTokenRedirect`.

**Comment by joostmeijles** [comment]
@derisen thanks for the example, that explains it. I changed my app to only send API requests when `inProgress == InteractionStatus.None`.

Regarding `loginRedirect`, I want to obtain the access token and as far as I know `acquireTokenRedirect` does not return this. In addition, the [documentation](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/acquire-token.md#acquiring-an-access-token) states that:
> It is best practice to attempt an acquireTokenSilent call before using the interactive APIs if you have already logged in.

**Comment by asos-alexhaigh** [comment]
> @derisen thanks for the example, that explains it. I changed my app to only send API requests when `inProgress == InteractionStatus.None`.
> 
> Regarding `loginRedirect`, I want to obtain the access token and as far as I know `acquireTokenRedirect` does not return this. In addition, the [documentation](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/acquire-token.md#acquiring-an-access-token) states that:
> 
> > It is best practice to attempt an acquireTokenSilent call before using the interactive APIs if you have already logged in.

You're right it doesn't return an authToken, instead you need to await `handleRedirectPromise` then when the user is redirected back to your back your page you can read the token.

````
const redirectResponse = await publicClientApplication.handleRedirectPromise();
if (redirectResponse !== null) {
let accessToken = redirectResponse.accessToken;
}
````

A full example is available here
https://learn.microsoft.com/en-us/entra/identity-platform/scenario-spa-acquire-token?tabs=javascript2#acquire-a-token-with-a-redirect
