### ISSUE TITLE
How to achieve silent SSO with msal-react app using B2C federated Active Directory and protected API

### ISSUE THREAD

**Issue by jasonk-ma** [AzureAD/microsoft-authentication-library-for-js#5339]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.30.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.9

### Public or Confidential Client?

Public

### Description

I have a B2C tenant created with custom policy for signup/signin. We are using a Federated Azure AD for our login and trying to achieve long-lived SSO between our internal Azure AD apps and this new MSAL-React app.

When I use B2C local accounts, SSO works (including KMSI to keep users signed in for more than 24 hours), however when using a Federated identity provider for our Azure AD (not B2C), we cannot achieve the same result.

I know that KMSI is not available for anything but Local Accounts in B2C, and also that a React SPA using MSAL will have 24 hr refresh tokens (with no ability to change this).

Here is  my scenario:
1. User is signed in to our organizational Azure AD (using other apps) and has elected to stay signed in (for 60 days).
2. User now launches MSAL-React app and navigates to a protected page that requires login
3. User should be automatically signed in via silent SSO since they have an active session with our Federated IDP.
4. Furthermore, once user's issued refresh token has expired (24 hrs later), they should be able to refresh the MSAL-React app protected page (which calls an API) and still remain signed in (or be silently signed in without any user interaction at all) since they have a valid session with the Federated IDP.  And then the API call should succeed because a subsequent call to acquireTokenSilent will succeed if the user's session is valid.

Is this possible with MSAL v2 and MSAL-React?

None of the samples really demonstrate how to do silent SSO while calling a protected API.

I'm using this sample as a base:
https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/b2c-sample

How would you modify the protected route for /Profile in this sample to not only silently perform SSO, but then retrieve the new access token and call the protected API, all without requiring any user interaction if the user has a valid session with the Federated IDP?

I have tried changing the MSAL Authentication Template to InteractionType.Silent and in my authRequest I'm passing in the  user's loginHint.

Or is it better to just avoid use of the MsalAuthenticationTemplate wrapping the React components, and do this some other way?

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by derisen** [comment]
@jasonk-ma apologies for the late response. Can you confirm that your issue occurs only with Azure AD federated sign-ins/user accounts, and you are able to achieve your scenario with local B2C accounts? If that's the case, your usage of MSAL React shouldn't be a factor (otherwise please have a look at the [ssoSilent considerations](https://learn.microsoft.comazure/active-directory/develop/msal-js-sso#considerations-when-using-ssosilent)) -

@mistermik are there any differences between local and federated accounts for SSO that might be relevant here? Any other recommendations you have?

**Comment by mistermik** [comment]
that is correct. KMSI doesn’t work for social accounts because AAD B2C always relies on the social accounts session. It would be a security flaw if AAD B2C kept you signed in but your account was deleted at the federated IdP.
Adding @JasSuri

**Comment by JasSuri** [comment]
I would call ssoSilent() in this case.
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/login-user.md#silent-login-with-ssosilent

The normal acquireTokenSilent() should call ssoSilent() before redirecting the user though. You should call acquireTokenSilent() before every API call.

**Comment by jasonk-ma** [comment]
> I would call ssoSilent() in this case. https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/login-user.md#silent-login-with-ssosilent
> 
> The normal acquireTokenSilent() should call ssoSilent() before redirecting the user though. You should call acquireTokenSilent() before every API call.

Don't your two statements conflict with each other? You say you would call ssoSilent in this case, but that acquireTokenSilent should call ssoSilent before redirecting (which I'm taking to mean just call acquireTokenSilent alone).

**Comment by JasSuri** [comment]
You should call acquireTokenSilent() before all API calls.
However, if that fails, eg when the AAD B2C SSO Cookie expires (24hrs), then only way to get SSO would be to subsequently call ssoSilent() with the `domain_hint` parameter. This would then allow B2C to redirect to AAD automatically in the iframe, and get SSO without a redirect.

The logic should be:

```.net
callMyAPI(){
acquireTokenSilent()
  if (error & AADUser)
    {
       ssoSilent() + domain_hint
         if (error)
           {
               acquireTokenRedirect()
           }
    }
  else {
       acquireTokenRedirect()
    }
```

**Comment by jasonk-ma** [comment]
Thanks! So, calling ssoSilent in this situation will log the user in silently as well as provide them a new access token all in the single call?

Will try that and report back in 24 hours (frustrating to not have any easy way to iterate on this more quickly...surely there must be a way to invalidate the RT sooner than 24 hrs in an SPA?).

The article you linked above for SSOSilent usage makes no mention of domain_hint parameter at all, in fact it says the following:

"It is recommended to leverage the [login_hint optional ID token claim](https://docs.microsoft.com/azure/active-directory/develop/active-directory-optional-claims#v10-and-v20-optional-claims-set) (provided to ssoSilent as loginHint), as it is the most reliable account hint of silent (and interactive) requests."

So, I'm using both login_hint and domain_hint in my ssoSilent request...

**Comment by jasonk-ma** [comment]
It didn't work -- after 24 hrs, I refreshed the Profile page my SPA app was on (and it ended up re-directing me to my custom B2C login page (where I would have to click on the Login button for the AAD/Social account) to continue. When I do click on the B2C login button to authenticate with my AAD it does so without any prompt, but then redirects me back to my application at the root instead of at /profile. 

Is it possible this is because my B2C tenant has both Local Accounts and AAD as IDPs? 

A few additional questions:
1. Is it possible to avoid that B2C login page altogether and just re-authenticate me with my AAD without any further user interaction? That's what I thought the SSO Silent method would do...
2. If that is not possible, then at the very least when I click on the login button it should redirect me back to my app at the same location as it was previously (http://localhost:3000/profile) and continue with the API call since it should have a valid token now. I have tried setting redirectUri and navigateToLoginRequestUrl -- they don't seem to have any impact.


The acquireTokenSilent() call in the pseudo-code above failed -- and I have really only modified the sample project in a small way (just to add the ssoSilent() call in the Profile.jsx page as indicated in the pseudo-code above)

This is the sample app I'm using:
https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/b2c-sample


InteractionRequiredAuthError: interaction_required: AADB2C90077: User does not have an existing session and request prompt parameter has a value of 'None'.

So it then went on to call ssoSilent() - passing in login_hint and domain_hint:

@azure/msal-browser@2.30.0 : Verbose - ssoSilent called
 @azure/msal-browser@2.30.0 : Info - Emitting event: msal:ssoSilentStart
 @azure/msal-react@1.4.9 : Info - MsalProvider - msal:ssoSilentStart results in setting inProgress from acquireToken to ssoSilent

[Thu, 10 Nov 2022 23:14:14 GMT] : @azure/msal-browser@2.30.0 : Verbose - getAllAccounts called
​ [Thu, 10 Nov 2022 23:14:14 GMT] : @azure/msal-browser@2.30.0 : Verbose - getAllAccounts called
​ [Thu, 10 Nov 2022 23:14:14 GMT] : [0c43c0b9-8689-438d-a4dd-3d7f695c5d0c] : msal.js.browser@2.30.0 : Verbose - acquireTokenByIframe called
​ [Thu, 10 Nov 2022 23:14:14 GMT] : [0c43c0b9-8689-438d-a4dd-3d7f695c5d0c] : msal.js.browser@2.30.0 : Verbose - initializeAuthorizationRequest called
​ [Thu, 10 Nov 2022 23:14:14 GMT] : [0c43c0b9-8689-438d-a4dd-3d7f695c5d0c] : msal.js.browser@2.30.0 : Verbose - getRedirectUri called
​ [Thu, 10 Nov 2022 23:14:14 GMT] : [0c43c0b9-8689-438d-a4dd-3d7f695c5d0c] : msal.js.browser@2.30.0 : Verbose - Initializing BaseAuthRequest
​ [Thu, 10 Nov 2022 23:14:14 GMT] : [0c43c0b9-8689-438d-a4dd-3d7f695c5d0c] : msal.js.browser@2.30.0 : Verbose - Authentication Scheme wasn't explicitly set in request, defaulting to "Bearer" request
​ [Thu, 10 Nov 2022 23:14:14 GMT] : [15f3e988-3964-47a7-8efc-a4fc56df4eb4] : msal.js.browser@2.30.0 : Verbose - initializeServerTelemetryManager called
​ [Thu, 10 Nov 2022 23:14:14 GMT] : [15f3e988-3964-47a7-8efc-a4fc56df4eb4] : msal.js.browser@2.30.0 : Verbose - initializeAuthorizationRequest called
​ [Thu, 10 Nov 2022 23:14:14 GMT] : [0c43c0b9-8689-438d-a4dd-3d7f695c5d0c] : msal.js.browser@2.30.0 : Verbose - Setting validated request account
​ [Thu, 10 Nov 2022 23:14:14 GMT] : [0c43c0b9-8689-438d-a4dd-3d7f695c5d0c] : msal.js.browser@2.30.0 : Verbose - initializeServerTelemetryManager called
​ [Thu, 10 Nov 2022 23:14:14 GMT] : [0c43c0b9-8689-438d-a4dd-3d7f695c5d0c] : msal.js.browser@2.30.0 : Verbose - getClientConfiguration called
​ [Thu, 10 Nov 2022 23:14:14 GMT] : [0c43c0b9-8689-438d-a4dd-3d7f695c5d0c] : msal.js.browser@2.30.0 : Verbose - getDiscoveredAuthority called
​ [Thu, 10 Nov 2022 23:14:14 GMT] : [0c43c0b9-8689-438d-a4dd-3d7f695c5d0c] : msal.js.browser@2.30.0 : Verbose - Creating discovered authority with configured authority
​ [Thu, 10 Nov 2022 23:14:14 GMT] : [0c43c0b9-8689-438d-a4dd-3d7f695c5d0c] : msal.js.browser@2.30.0 : Verbose - Auth code client created
​ [Thu, 10 Nov 2022 23:14:14 GMT] : [0c43c0b9-8689-438d-a4dd-3d7f695c5d0c] : msal.js.browser@2.30.0 : Verbose - initializeAuthorizationRequest called
​ [Thu, 10 Nov 2022 23:14:14 GMT] : [15f3e988-3964-47a7-8efc-a4fc56df4eb4] : msal.js.browser@2.30.0 : Verbose - getClientConfiguration called
​ [Thu, 10 Nov 2022 23:14:14 GMT] : [15f3e988-3964-47a7-8efc-a4fc56df4eb4] : msal.js.browser@2.30.0 : Verbose - getDiscoveredAuthority called
​ [Thu, 10 Nov 2022 23:14:14 GMT] : [15f3e988-3964-47a7-8efc-a4fc56df4eb4] : msal.js.browser@2.30.0 : Verbose - Creating discovered authority with configured authority
​ [Thu, 10 Nov 2022 23:14:14 GMT] : [15f3e988-3964-47a7-8efc-a4fc56df4eb4] : msal.js.browser@2.30.0 : Verbose - Auth code client created
​ [Thu, 10 Nov 2022 23:14:14 GMT] : [15f3e988-3964-47a7-8efc-a4fc56df4eb4] : @azure/msal-common@7.6.0 : Verbose - createAuthCodeUrlQueryString: Adding login_hint from account
​ [Thu, 10 Nov 2022 23:14:14 GMT] : [15f3e988-3964-47a7-8efc-a4fc56df4eb4] : msal.js.browser@2.30.0 : Verbose - RedirectHandler.initiateAuthRequest called
​ [Thu, 10 Nov 2022 23:14:14 GMT] : [15f3e988-3964-47a7-8efc-a4fc56df4eb4] : msal.js.browser@2.30.0 : Verbose - RedirectHandler.initiateAuthRequest: redirectStartPage set, caching start page
​ [Thu, 10 Nov 2022 23:14:14 GMT] : [15f3e988-3964-47a7-8efc-a4fc56df4eb4] : msal.js.browser@2.30.0 : Verbose - RedirectHandler.initiateAuthRequest: Navigating window to navigate url
​ [Thu, 10 Nov 2022 23:14:14 GMT] : [0c43c0b9-8689-438d-a4dd-3d7f695c5d0c] : @azure/msal-common@7.6.0 : Verbose - createAuthCodeUrlQueryString: Adding login_hint from request
​ [Thu, 10 Nov 2022 23:14:15 GMT] : [0c43c0b9-8689-438d-a4dd-3d7f695c5d0c] : msal.js.browser@2.30.0 : Verbose - validateAndExtractStateFromHash called
​ [Thu, 10 Nov 2022 23:14:15 GMT] : [0c43c0b9-8689-438d-a4dd-3d7f695c5d0c] : msal.js.browser@2.30.0 : Verbose - Returning state from hash
​ [Thu, 10 Nov 2022 23:14:15 GMT] : [0c43c0b9-8689-438d-a4dd-3d7f695c5d0c] : msal.js.browser@2.30.0 : Verbose - InteractionHandler.handleCodeResponse called
​ [Thu, 10 Nov 2022 23:14:15 GMT] : @azure/msal-browser@2.30.0 : Info - Emitting event: msal:ssoSilentFailure

 @azure/msal-react@1.4.9 : Info - MsalProvider - msal:ssoSilentFailure results in setting inProgress from ssoSilent to none

**Comment by derisen** [comment]
@jasonk-ma Can you confirm that your issue occurs only with Azure AD federated sign-ins/user accounts, and you are able to achieve your SSO scenario with local B2C accounts?

> It didn't work -- after 24 hrs, I refreshed the Profile page my SPA app was on (and it ended up re-directing me to my custom B2C login page (where I would have to click on the Login button for the AAD/Social account) to continue. When I do click on the B2C login button to authenticate with my AAD it does so without any prompt, but then redirects me back to my application at the root instead of at /profile.
> A few additional questions:
> 
> 1. Is it possible to avoid that B2C login page altogether and just re-authenticate me with my AAD without any further user interaction? That's what I thought the SSO Silent method would do...

Are you using `MsalAuthenticationTemplate `with `interactionType `set to `Silent`? This will attempt `ssoSilent` under the hood, and will fail if your browser blocks 3rd party cookies. You should handle that failure with an interactive request. A useful trick is that you can [pass the prompt parameter set to none](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-js-prompt-behavior#interactive-requests-with-promptnone) when handling ssoSilent failure with an interactive request (this can also fail, so you should handle that with an interactive request without [prompt=none](url) parameter)

Also, can you share a code snippet of how your code looks like (in particular the request object)? I assume the `domain_hint` is not getting attached to the request, which is why you hit the B2C login page itself and have to click AAD/Social account buttons. You can pass `domain_hint` as an `extraQueryParameter`, e.g.:

```javascript
const loginRequest = {
   scopes: [],
   loginHint: "your_login_hint",
   extraQueryParameters: {'domain_hint': "your_domain_hint"}
}
```

> 2. If that is not possible, then at the very least when I click on the login button it should redirect me back to my app at the same location as it was previously (http://localhost:3000/profile) and continue with the API call since it should have a valid token now. I have tried setting redirectUri and navigateToLoginRequestUrl -- they don't seem to have any impact.
> 

You shouldn't need the set the `redirectUri` in the request, but are you setting the `navigateToLoginRequestUrl ` to true in the msal [configuraiton object](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/configuration.md)? (as opposed to setting it in the request object, which is not a valid parameter). If that's not the issue, it might be that your router is interfering with msal's redirect after the auth code in the hash is processed -do you have any extra code in the sample that might be doing this?

If you can, it would also help if you capture a network trace with [Fiddler](https://www.telerik.com/fiddler/fiddler-classic)when this happens. You can send it to me over email  (you can find my email on my GitHub profile).

**Comment by jasonk-ma** [comment]
> Can you confirm that your issue occurs only with Azure AD federated sign-ins/user accounts, and you are able to achieve your SSO scenario with local B2C accounts?

I can't confirm that yet as I'm focusing on the AAD scenario as my primary concern. I will attempt with Local B2C account now (but have to wait another 24 hrs for results).

Regarding msalAuthenticationTemplate, yes, I'm using InteractionType = Silent:
Profile.jsx:
        <MsalAuthenticationTemplate
            interactionType={InteractionType.Silent}
            authenticationRequest={authRequest}
            errorComponent={ErrorComponent}
            loadingComponent={Loading}
        >
            <ProfileContent />
        </MsalAuthenticationTemplate>

useEffect from the Profile page is as follows (with PII removed):

`    useEffect(() => {
        if (!apiData && inProgress === InteractionStatus.None) {
            callApi()
                .then((response) => setApiData(response))
                .catch((e) => {
                    const silentRequest = {
                        scopes: [...protectedResources.apiHello.scopes],
                        extraQueryParameters: {
                            appId: "FF",
                            domain_hint: "<my AAD tenant GUID here>",
                        },
                        loginHint: "<user@domain.com>",
                    };
                    instance
                        .ssoSilent(silentRequest)
                        .then((response) => callApi(response.accessToken))
                        .then((apiResponse) => setApiData(apiResponse))
                        .catch((e) => {
                            if (e instanceof InteractionRequiredAuthError) {
                                instance.acquireTokenRedirect({
                                    ...loginRequest,
                                    account: instance.getActiveAccount(),
                                });
                            }
                        });
                });
        }
    }, [inProgress, apiData, instance]);`

navigateToLoginRequestUrl is set to true in my authConfig.js.

The result from my last test is that it still failed when I refreshed the /profile page after 24hrs, and it redirected me to the B2C login page where I had to select my Social/AAD provider by clicking the button for it. So it did not seem to do any SSO. I did not need to enter my credentials again, but I did have to click on the button on the B2C login page. And then after that, it logged me back in and redirected me to my SPA and actually went to the /profile page where it retrieved the results from the API call successfully. So, the redirect back to my application post-login is working but again the SSO did not seem to (even with domain hint and loginHint specified.

I'm sending you some files over email from Chrome console and Fiddler.

Thanks for your assistance!

**Comment by jasonk-ma** [comment]
I can confirm that this issue is not present when using B2C Local Accounts -- after 24 hrs, I am able to reload the /profile endpoint and the SPA just goes and does the SSO and makes the API call all without any user interaction or any visible redirect.

So, the issue is only happening when using a AAD B2C account.

**Comment by derisen** [comment]
> I can confirm that this issue is not present when using B2C Local Accounts -- after 24 hrs, I am able to reload the /profile endpoint and the SPA just goes and does the SSO and makes the API call all without any user interaction or any visible redirect.
> 
> So, the issue is only happening when using a AAD B2C account.

@jasonk-ma apologies for the late response. I've checked the Fiddler trace you sent but I wasn't able to see the calls the Azure -I think you need to [enable capturing HTTPS traffic in Fiddler](https://docs.telerik.com/fiddler/configure-fiddler/tasks/decrypthttps) (if you could recapture with HTTPS enabled that is worth looking again). Regardless, the fact that this works as expected with B2C local account suggests that MSAL usage is not the culprit here, but we need to confirm if `domain_hint` is getting attached to the request.

~~You might also want to open a [support ticket with B2C service](https://learn.microsoft.com/en-us/azure/active-directory-b2c/support-options), unless @mistermik or @JasSuri has any other recommendations.~~

**Comment by derisen** [comment]
@jasonk-ma sorry, I just saw from MSAL logs that domain hint is not present -your usage looks correct to me so let me try to figure out why this isn't getting attached.

**Comment by derisen** [comment]
@jasonk-ma I've double checked your code -not sure why domain_hint does not appear in the msal logs, though we need to see the Fiddler trace to see if it is actually being sent or not. However, it seems if domain_hint is not correct (i.e. doesn't match any of the IdPs), the user will not pass the B2C login page and have to select the button for the IdP. So you might need to check if this (domain_hint: "`<my AAD tenant GUID here>`") is the correct format -I don't seem to recall seeing a GUID used as a domain_hint before, so this could be an issue. You should be able to test this with a regular login request (no need to wait for RT expiry) 

```javascript
useEffect(() => {
  if (!apiData && inProgress === InteractionStatus.None) {
    callApi().then((response) => setApiData(response))
      .catch((e) => {
        const silentRequest = {
          scopes: [...protectedResources.apiHello.scopes],
          extraQueryParameters: { appId: "FF", domain_hint: "<my AAD tenant GUID here>", },
          loginHint: "<user@domain.com>",
        };

        instance.ssoSilent(silentRequest).then((response) => callApi(response.accessToken))
          .then((apiResponse) => setApiData(apiResponse))
          .catch((e) => {
            if (e instanceof InteractionRequiredAuthError) {
              instance.acquireTokenRedirect({
                ...loginRequest, account: instance.getActiveAccount(),
              });
            }
          });
      });
  }
}, [inProgress, apiData, instance]);
```

**Comment by jasonk-ma** [comment]
Ok I’ll give it a try with domain_hint set to my actual domain name, but I believe I’ve already tried that, and also the documentation seems to indicate I’m using the correct format:

From here:
https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-js-sso
·         domain_hint: Use the ID token's tid claim value. Required in requests made by multi-tenant applications that use the /common authority. Optional for other applications.

***@***.***

**Comment by derisen** [comment]
> Ok I’ll give it a try with domain_hint set to my actual domain name, but I believe I’ve already tried that, and also the documentation seems to indicate I’m using the correct format: From here: https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-js-sso · domain_hint: Use the ID token's tid claim value. Required in requests made by multi-tenant applications that use the /common authority. Optional for other applications. 

Interesting. I'll try to confirm this -will update the docs if need be.

**Comment by JasSuri** [comment]
No, for B2C, domain_hint is not the AAD GUID.

See this doc to set the right domain_hint value:
https://learn.microsoft.com/en-us/azure/active-directory-b2c/direct-signin?pivots=b2c-custom-policy#redirect-sign-in-to-a-social-provider

**Comment by jasonk-ma** [comment]
> No, for B2C, domain_hint is not the AAD GUID.
> 
> See this doc to set the right domain_hint value: https://learn.microsoft.com/en-us/azure/active-directory-b2c/direct-signin?pivots=b2c-custom-policy#redirect-sign-in-to-a-social-provider

ClaimsProvider / Domain is described as:
      <xs:element minOccurs="0" maxOccurs="1" name="Domain" type="xs:string">
        <xs:annotation>
          <xs:documentation>
            The **human understandable** domain name for the technical profile.
          </xs:documentation>
        </xs:annotation>

In my custom policy I have a simple user-friendly name listed as the Domain for the ClaimsProvider. 
But I tried setting the domain_hint to this same user-friendly name and it didn't work.

Is it supposed to actually be the TLD rather than a user-friendly string?

The documentated annotation in the XSD describes it as "human understandable" versus this page:
https://learn.microsoft.com/en-us/azure/active-directory-b2c/claimsproviders
Which describes the Domain element as:  "A string that contains the domain name for the claim provider."

Which is it?

**Comment by JasSuri** [comment]
I have always used a FQDN - can you try `something.com`?

**Comment by jasonk-ma** [comment]
> I have always used a FQDN - can you try `something.com`?

I tried it with FQDN and it still does not work as expected. The domain hint is not getting attached.

**Comment by derisen** [comment]
@jasonk-ma I'm not able to reproduce this with the [b2c-sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/b2c-sample). Are you sure the the domain hint is actually in the request object? Could you share the code/component that triggers login (profile.jsx)? If you a have a public repo for reproduction, feel free to share it.

**Comment by jasonk-ma** [comment]
> @jasonk-ma I'm not able to reproduce this with the [b2c-sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/b2c-sample). Are you sure the the domain hint is actually in the request object? Could you share the code/component that triggers login (profile.jsx)? If you a have a public repo for reproduction, feel free to share it.

Profile.jsx:


`import { useEffect, useState } from "react";

// Msal imports
import { MsalAuthenticationTemplate, useMsal } from "@azure/msal-react";
import {
    InteractionStatus,
    InteractionType,
    InteractionRequiredAuthError,
} from "@azure/msal-browser";
import { loginRequest, protectedResources } from "../authConfig";

// Sample app imports
import { ProfileData } from "../ui-components/ProfileData";
import { Loading } from "../ui-components/Loading";
import { ErrorComponent } from "../ui-components/ErrorComponent";
import { callApi } from "../utils/ApiCall";

// Material-ui imports
import Paper from "@mui/material/Paper";

const ProfileContent = () => {
    const { instance, inProgress } = useMsal();
    const [apiData, setApiData] = useState(null);

    useEffect(() => {
        if (!apiData && inProgress === InteractionStatus.None) {
            callApi()
                .then((response) => setApiData(response))
                .catch((e) => {
                    const silentRequest = {
                        scopes: [...protectedResources.apiHello.scopes],
                        extraQueryParameters: {
                            appId: "FF",
                            domain_hint: "domainname.com",
                        },
                        loginHint: "my-user@domainname.com",
                    };
                    instance
                        .ssoSilent(silentRequest)
                        .then((response) => callApi(response.accessToken))
                        .then((apiResponse) => setApiData(apiResponse))
                        .catch((e) => {
                            if (e instanceof InteractionRequiredAuthError) {
                                instance.acquireTokenRedirect({
                                    ...loginRequest,
                                    account: instance.getActiveAccount(),
                                });
                            }
                        });
                });
        }
    }, [inProgress, apiData, instance]);

    return <Paper>{apiData ? <ProfileData apiData={apiData} /> : null}</Paper>;
};

export function Profile() {
    const authRequest = {
        ...loginRequest,
    };

    return (
        <MsalAuthenticationTemplate
            interactionType={InteractionType.Silent}
            authenticationRequest={authRequest}
            errorComponent={ErrorComponent}
            loadingComponent={Loading}
        >
            <ProfileContent />
        </MsalAuthenticationTemplate>
    );
}
`

**Comment by derisen** [comment]
@jasonk-ma aah, I don't see you passing the params to `authRequest` object in case if `MsalAuthenticationTemplate` triggers login:

```
export function Profile() {
const authRequest = {
  ...loginRequest,
  extraQueryParameters: {
      appId: "FF",
      domain_hint: "domainname.com",
  },
  loginHint: "my-user@domainname.com",
};

return (
    <MsalAuthenticationTemplate
        interactionType={InteractionType.Silent}
        authenticationRequest={authRequest}
        errorComponent={ErrorComponent}
        loadingComponent={Loading}
    >
        <ProfileContent />
    </MsalAuthenticationTemplate>
);
}
```

In any case, I would suggest you to just test if the domain_hint value you are using is correct. Modify the `loginRequest ` object  in `authConfig.js`, then just perform a sign-in in an incognito browser session and see if the IdP selection screen is bypassed

**Comment by jasonk-ma** [comment]
Thanks - this is working now. The missing piece was to have the domain_hint in the authRequest that is passed in via MsalAuthenticationTemplate (it was already in the ssoSilent request, but not in both places). Also, you need to make sure that your domain_hint is in the format of FQDN and that this matches the ClaimsProvider - Domain specified in the custom B2C policy.

**Comment by derisen** [comment]
@jasonk-ma sounds great! Closing this as resolved -thanks @JasSuri @mistermik
