### ISSUE TITLE
getActiveAccount() failed with: ClientAuthError: multiple_matching_tokens: The cache contains multiple tokens satisfying the requirements

### ISSUE THREAD

**Issue by izikl** [AzureAD/microsoft-authentication-library-for-js#5340]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.30.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

After upgrading from 2.19.0 to 2.30.0 and back to 2.19.0, I have started getting this error when calling getActiveAccount():
![image](https://user-images.githubusercontent.com/8294298/198419369-3273a5d1-b428-4679-875f-b30a48d80023.png)

Looking at my application I have noticed that indeed there are duplicate idtokens: 
![image](https://user-images.githubusercontent.com/8294298/198419413-ba983fa9-868d-4333-827b-f408f31a65f4.png)

clearing all the idtokens and refresh the page solved the problem. 

### Error Message

Uncaught (in promise) ClientAuthError: multiple_matching_tokens: The cache contains multiple tokens satisfying the requirements. Call AcquireToken again providing more requirements such as authority or account..
    at t [as constructor] (AuthError.ts:45:9)
    at new t (ClientAuthError.ts:201:9)
    at t.createMultipleMatchingTokensInCacheError (ClientAuthError.ts:323:16)
    at e.readIdTokenFromCache (CacheManager.ts:690:19)
    at CacheManager.ts:177:38
    at Array.map (<anonymous>)
    at e.getAllAccounts (CacheManager.ts:174:47)
    at t.getAccountInfoByFilter (BrowserCacheManager.ts:430:34)
    at t.getActiveAccount (BrowserCacheManager.ts:407:21)
    at e.getActiveAccount (ClientApplication.ts:526:36)

### MSAL Configuration

```javascript
auth: {
        clientId: "f9818e52-50bd-463e-8932-a1650bd3fad2",
        redirectUri: redirectUri,
    },
    cache: {
        cacheLocation: 'localStorage',
        // Fix for auth loop issues https://aka.ms/known-issues-on-Microsoft-Browsers-due-to-security-zones
        storeAuthStateInCookie: true,
    },
    system: {
        loggerOptions: {
            loggerCallback: (level: LogLevel, message: string): void => {
                trackTrace(message, levelToSeverity(level), { flow: 'msalv2' });
            },
            logLevel: LogLevel.Info,
            piiLoggingEnabled: false,
        },
        // Allow more time before a token renewal response from Azure AD should be considered timed out
        loadFrameTimeout: 30000,
    },
```

### Relevant Code Snippets

```javascript
this.application.getActiveAccount()
```

### Reproduction Steps

1. Call getActiveAccount with 2.19.0
2. Call getActiveAccount with 2.30.0
3. Call getActiveAccount with 2.19.0 again

### Expected Behavior

Either do not throw or throw but recommend how to catch and handle this error. 

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Regression

msal-browser 2.19.0

### Source

Internal (Microsoft)

**Comment by bmahall** [comment]
@izikl This is occurring due to multiple IdTokens in the cache matching the IdTokenFilter criteria. 
What parameters are currently being passed to the acquireTokenSilent  ?

**Comment by izikl** [comment]
@bmahall 
To answer your question: 
![image](https://user-images.githubusercontent.com/8294298/199135004-3bf8cfe8-7481-4491-b589-75522ad97c6d.png)

These are all the idtokens I can see in the local storage:
![image](https://user-images.githubusercontent.com/8294298/199134483-c9415f9d-023a-4089-9fe3-6be84a00b4ec.png)

Note that there are 2 idtokens from 2 different msal-browser versions (2.19.0 that ends with 1 hyphan and 2.30.0 that ends with 3 hyphans). 
Moving from 2.19.0 to 2.30.0 doesn't cause any problem since 2.30.0 handle correclty 2 different idtoken templates. It merges them. 
However, the code to handle a mismatch idtoken templates doesn't exist in version 2.19.0 which is why the SDK throws.

**Comment by hectormmg** [comment]
@izikl thanks for raising the issue, we're aware of the forward compatibility issue and will update our documentation to help avoid it.
