### ISSUE TITLE
Unsure when LOGIN_FAILURE is fired

### ISSUE THREAD

**Issue by Core121** [AzureAD/microsoft-authentication-library-for-js#5341]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.21.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.1.0

### Public or Confidential Client?

Public

### Description

I'm not sure when the LOGIN_FAILURE event type is being fired. I tried running logs or navigating to another page on LOGIN_FAILURE but nothing is running. I'm not sure what I'm doing wrong or how I should be handling this. I'd like to send a log to our API with information about the login failure and what email failed to login. Am I able to do this using this event?

This is the only output I get in the console window when using an incorrect password.
![image](https://user-images.githubusercontent.com/42871786/198595101-54191e5d-ca19-4fd6-a6ef-bbd40bb3b2ef.png)

### Relevant Code Snippets

```javascript
this.msalBroadcastService.msalSubject$
      .pipe(
        // Optional filtering of events
        filter((msg: EventMessage) => msg.eventType === EventType.LOGIN_FAILURE),
        takeUntil(this._destroying$)
      )
      .subscribe((result) => {
        window.location.pathname = "/login";
        console.log("could not login");
      });
```

### Identity Provider

Azure B2C Basic Policy

### Source

External (Customer)

**Comment by hectormmg** [comment]
@Core121 the login UI is not actually controlled by MSAL so things like incorrect passwords won't trigger an MSAL error. The LOGIN_FAILURE event is fired when there is an error before or after the interaction.

**Comment by Core121** [comment]
Okay got it, that makes sense to me
