### ISSUE TITLE
tokenReceivedCallback not be called after loginRedirect()

### ISSUE THREAD

**Issue by Gtyrande** [AzureAD/microsoft-authentication-library-for-js#535]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Center Browser version 3.7.2.33 (Chromium 70.0.3538.110)
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 0.2.4

## Current behavior
tokenReceivedCallback not be called after loginRedirect() in my Vue app
loginPopup() works fine but has some problems on my mobilephone explorer, so I want to use loginRedirect() instead of loginPopup()

## Expected behavior
tokenReceivedCallback can be called after loginRedirect()

## Minimal reproduction of the problem with instructions
this.app = new Msal.UserAgentApplication(
      this.applicationConfig.clientID,
      this.applicationConfig.authority,
      this.tokenReceivedCallback,
      {
        redirectUri
      }
);

login() {
    Store.commit('SET_USEREMAIL', 'test')
    this.app.loginRedirect(this.applicationConfig.graphScopes, "&prompt=select_account");
}

tokenReceivedCallback(errorDesc, token, error, tokenType) {
    Store.commit('SET_USEREMAIL', 'another test')
}

Most of the time store.state.userEmail is 'test' instead of 'another test'

</code></pre>

**Comment by Gtyrande** [comment]
@sameerag Can you help me with this problem?

**Comment by sameerag** [comment]
Hi @Gtyrande. Sure. We are debugging a similar issue #498. Will update once we have some progress.

**Comment by aashiman** [comment]
@navyasric  is this a dup of  issue #498

**Comment by pkanher617** [comment]
@Gtyrande Thanks for submitting this issue. Our compatibility with Vue is something we are taking a look at, but this may be a library issue. 

We have recently gone through a redesign of the library's API surface and the calling pattern for the redirect pattern. Please download our [latest preview package](https://www.npmjs.com/package/msal) or pull the [dev branch](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev) and try updating your code and see if the issue still persists. Please re-open this issue if it persists. We are now throwing error stack traces so we can understand better why your code is failing. 

If you would like guidance on how to use the new version of the library, please review our wiki page [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL.js-1.0.0-preview-api-release).
