### ISSUE TITLE
Dyamically loading MSAL related libraries  based on flag

### ISSUE THREAD

**Issue by ajhaver** [AzureAD/microsoft-authentication-library-for-js#5357]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.3.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

Do we have a flag ?

In which we can dynamically load msal related libraries or by-pass all MSAL related interceptors/config ?

### Relevant Code Snippets

```javascript
providers: [
    // Enable adb2c access token with guard, for every request access token
    {
      provide: HTTP_INTERCEPTORS,
      useClass: MsalInterceptor,
      multi: true
    },
    MsalGuard,
    AzureAdService
  ],
```

### Source

External (Customer)

**Comment by hectormmg** [comment]
@ajhaver could you please elaborate on what you're looking for? We don't have any configuraiton flags to dynamically load our libraries. In order to bypass things like the MsalInterceptor, you need to manually provide a custom Interceptor.

**Comment by abhijith-k07** [comment]
Hi i also have  a similar scenario, I am using Teams SSO in my application. at the time of app initialization i am calling team SDK  initializer function to detect if the my web app is inside teams or in browser, based on this i am deciding which authentication flow to occur. if my app is inside teams app i need to disable msal or its functionalities but in browser i need to use msal
