### ISSUE TITLE
Webpack error in build pipeline

### ISSUE THREAD

**Issue by cssuh** [AzureAD/microsoft-authentication-library-for-js#5358]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.14.0

### Wrapper Library

MSAL Node Extensions (@azure/msal-node-extensions)

### Wrapper Library Version

1.0.0-alpha.25

### Public or Confidential Client?

Public

### Description

<img width="1154" alt="Screenshot 2022-11-02 at 3 49 27 PM" src="https://user-images.githubusercontent.com/18150417/199617478-7a6978f8-3395-44cf-aa02-f832ec2536a4.png">
I get this build error when trying to use the msal-node-extensions library, I saw this issue: #3200 but adding the rule as suggested by https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/3200#issuecomment-801511395 but that did not resolve the issue.

### Error Message

[22:44:33] 'extensions-ci' errored after 3.77 min
[extensions-ci] [22:44:33] Error in plugin "webpack-stream"
[extensions-ci] Message:
[extensions-ci]     Module parse failed: Unexpected character '' (1:0)
[extensions-ci] You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

### Msal Logs

Link to failing CI build: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=177562&view=logs&j=bd1e231b-cef9-51a2-e461-b67194c0a817&t=9cc46b07-0f4a-51e5-598b-b142e2b8a72a

### MSAL Configuration

```javascript
N/A
```

### Relevant Code Snippets

```javascript
webpack.json:

/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the Source EULA. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

//@ts-check

'use strict';

const withDefaults = require('../shared.webpack.config');
const fs = require('fs');
const path = require('path');

const externals = {
	'node-fetch': 'commonjs node-fetch',
	'bufferutil': 'commonjs bufferutil',
	'utf-8-validate': 'commonjs utf-8-validate',
	'keytar': 'commonjs keytar',
	'universalify': 'commonjs universalify',
	'@azure/arm-subscriptions': 'commonjs @azure/arm-subscriptions',
	'@azure/arm-resourcegraph': 'commonjs @azure/arm-resourcegraph',
	'@azure/storage-blob': 'commonjs @azure/storage-blob'
};

// conditionally add ws if we are going to be running in a node environment
const yarnrcPath = path.join(__dirname, '.yarnrc');
if (fs.existsSync(yarnrcPath)) {
	const yarnrc = fs.readFileSync(yarnrcPath).toString();
	const properties = yarnrc.split(/\r?\n/).map(r => r.split(' '));
	if (properties.find(r => r[0] === 'runtime')[1] === '"node"') {
		externals['ws'] = 'commonjs ws';
	}
}

module.exports = withDefaults({
	context: __dirname,
	entry: {
		extension: './src/extension.ts'
	},
	externals: externals

});
```

### Reproduction Steps

1. Add msal-node-extensions to project
2. Run CI build - "node --max_old_space_size=4095 ./node_modules/gulp/bin/gulp.js extensions-ci"
3. See failure above

### Expected Behavior

This should compile successfully

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

Internal (Microsoft)

**Comment by hectormmg** [comment]
@cssuh do you have a way of checking which file can't be processed (in the issue you referenced it was a .node file, but the same message doesn't appear in your logs plus it's a different module failing)?

**Comment by cssuh** [comment]
Whoops, looks like this was caused by something else - I added our packages to the webpack.config.js and it works now.
