### ISSUE TITLE
no_tokens_found: No tokens were found for the given scopes, and no authorization code was passed to acquireToken. You must retrieve an authorization code before making a call to acquireToken().

### ISSUE THREAD

**Issue by cbishop-fv** [AzureAD/microsoft-authentication-library-for-js#5362]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.16.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

none

### Public or Confidential Client?

Public

### Description

We have an outlook add-in that we augment with MS API calls. We are converting from REST to GraphREST API since rest is getting turned off the end of the month. We have a variety of types of users and exchange servers. The Auth flow calls are failing for almost 1/2 of our users.

``` no_tokens_found: No tokens were found for the given scopes, and no authorization code was passed to acquireToken. You must retrieve an authorization code before making a call to acquireToken().```

We have set up an Azure AD app registration for this flow. The redirect URL is set up as SPA.  We tried enabling both Access tokens (used for implicit flows) and ID tokens (used for implicit and hybrid flows). We are unsure is Allow public client flows is needed.

### MSAL Configuration

```javascript
const msalConfig: Configuration = {
  auth: {
    clientId: process.env.REACT_APP_AZURE_CLIENT_ID || '',
    redirectUri: `${getConfig().hostUrl}/auth`,
    authority: 'https://login.microsoftonline.com/common',
  },
  cache: {
    cacheLocation: 'localStorage', // needed to avoid "login required" error
    storeAuthStateInCookie: true, // recommended to avoid certain IE/Edge issues
  },
};

// MSAL App Instance
const msalPublicClientAppInstance = new PublicClientApplication(msalConfig);
```

### Relevant Code Snippets

```javascript
const scopes = ['User.Read', 'Mail.ReadWrite', 'Mail.Send', 'Mail.Read'];

const fetchMSALAccount = async (): Promise<AccountInfo | undefined> => {
  const MSALAccount = msalPublicClientAppInstance.getActiveAccount();
  if (MSALAccount) {
    return MSALAccount;
  }

  try {
    const userName = Office?.context?.mailbox?.userProfile?.emailAddress;
    if (!userName) {
      return undefined;
    }

    const accounts = await msalPublicClientAppInstance.getAllAccounts();
    if (!accounts.length) {
      return undefined;
    }

    const accountMatch = accounts.find((a) => a.username === userName);
    if (accountMatch) {
      msalPublicClientAppInstance.setActiveAccount(accountMatch);
      return accountMatch;
    }
    return undefined;
  } catch (error) {
    return undefined;
  }
};

const fetchMSALResult = async (): Promise<AuthenticationResult | undefined> => {
  const account = await fetchMSALAccount();

  if (account) {
    return msalPublicClientAppInstance.acquireTokenSilent({
      account,
      scopes,
    });
  }

  return undefined;
};

const refreshMSALToken = async (): Promise<boolean> => {
  try {
    const result = await fetchMSALResult();
    if (result?.accessToken) {
      return true;
    }

    return false;
  } catch (error) {
    return false;
  }
};

const handleMSALRedirect = async (): Promise<void> => {
  try {
    const response = await msalPublicClientAppInstance.handleRedirectPromise();
    const accounts = await msalPublicClientAppInstance.getAllAccounts();

    if (!accounts.length) {
      msalPublicClientAppInstance.loginRedirect({
        loginHint: Office?.context?.mailbox?.userProfile?.emailAddress,
        scopes,
      });
    } else if (Office?.context?.host && response) {
      // Close the dialog
      Office.context.ui.messageParent(
        JSON.stringify({ status: 'success', result: response.accessToken }),
      );
    }
  } catch (error) {
    Office.context.ui.messageParent(
      JSON.stringify({ status: 'error', result: error.message }),
    );
  }
};
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by hectormmg** [comment]
@cbishop-fv a couple of things:

1. Have you verified that there's a token for those scopes in the cache? I'm assuming there isn't one, which means acquireTokenSilent is expected to fail.
2. The correct usage pattern is to call acquireTokenSilent and if that fails, catch and call an interactive acquireToken/login API (i.e. acquireTokenRedirect or acquireTokenPopup, whichever one is feasible in your environment).

**Comment by cbishop-fv** [comment]
> @cbishop-fv a couple of things:
> 
> 1. Have you verified that there's a token for those scopes in the cache? I'm assuming there isn't one, which means acquireTokenSilent is expected to fail.
> 2. The correct usage pattern is to call acquireTokenSilent and if that fails, catch and call an interactive acquireToken/login API (i.e. acquireTokenRedirect or acquireTokenPopup, whichever one is feasible in your environment).

I have not been able to repro this error myself to look at the data, unfortunately.

I will try #2 thank you

**Comment by cbishop-fv** [comment]
@hectormmg  Are you familiar with this error? 
`CompactToken parsing failed with error code: 80049217` 
This is another one we are seeing a high error rate for but are unable to replicate.

**Comment by derisen** [comment]
@cbishop-fv this error could occur if the token you are passing to MS Graph is somehow malformed. You might be passing the wrong token, the token might have the wrong format, version, the header in the request might be malformed etc etc. When this occurs, you could try parsing the token at https://jwt.ms and see if it looks out of ordinary (`aud `and `scp` claims in particular) or check if the [request header looks correct](https://www.rfc-editor.org/rfc/rfc6750#section-2.1).

**Comment by cbishop-fv** [comment]
> @cbishop-fv this error could occur if the token you are passing to MS Graph is somehow malformed. You might be passing the wrong token, the token might have the wrong format, version, the header in the request might be malformed etc etc. When this occurs, you could try parsing the token at https://jwt.ms and see if it looks out of ordinary (`aud `and `scp` claims in particular) or check if the [request header looks correct](https://www.rfc-editor.org/rfc/rfc6750#section-2.1).

We are not doing anything with the token directly just calling ` msalPublicClientAppInstance.getActiveAccount()` and `msalPublicClientAppInstance.acquireTokenSilent()`

**Comment by derisen** [comment]
@cbishop-fv sorry, I was responding to your question about `CompactToken parsing failed with error code: 80049217` -you are receiving this from MS Graph, right?

**Comment by cbishop-fv** [comment]
> @cbishop-fv sorry, I was responding to your question about `CompactToken parsing failed with error code: 80049217` -you are receiving this from MS Graph, right?

Yes that is correct we call `msalPublicClientAppInstance.getActiveAccount();`  or `msalPublicClientAppInstance.getAllAccounts()` if there isn't an active account and pass that result to the graph client 

```  const activeAccount = await fetchMSALAccount();
  if (activeAccount) {
    const graph = msGraphClient(activeAccount);```

**Comment by derisen** [comment]
May I ask what `msGraphClient` does with the account object? Is it using it to acquire a token and calll Graph afterwards? Can you share a bit of the implementation?

**Comment by cbishop-fv** [comment]
> May I ask what `msGraphClient` does with the account object? Is it using it to acquire a token and calll Graph afterwards? Can you share a bit of the implementation?

My apologies I thought I had included that in the original sample code. We do not acquire a token, the token is already on the account object I believe. We just pass the account directly to the Graph client. Thanks for your help!

```

export const msGraphClient = (account: AccountInfo) => {
  const options: AuthCodeMSALBrowserAuthenticationProviderOptions = {
    account,
    scopes,
    interactionType: InteractionType.Silent,
  };
  return Client.initWithMiddleware({
    authProvider: new AuthCodeMSALBrowserAuthenticationProvider(
      msalPublicClientAppInstance,
      options,
    ),
  });
};

**Comment by derisen** [comment]
> We do not acquire a token, the token is already on the account object I believe. We just pass the account directly to the Graph client. 

Oh no the token won't be in the account object. Anyways I see that you are using [MS Graph SDK](https://github.com/microsoftgraph/msgraph-sdk-javascript). But you are specifying the interaction type as silent. I'm not entirely sure about `AuthCodeMSALBrowserAuthenticationProvider` implementation but it [looks like ](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/91eb11f7a7155844f7404c8087c347870da436b0/src/authentication/msal-browser/AuthCodeMSALBrowserAuthenticationProvider.ts#L67) unless you specify `Popup `or `Redirect `as interaction type, it will not handle `InteractionRequiredAuthError`, so the error would be expected in this case. By default, `AuthCodeMSALBrowserAuthenticationProvider` already attempts to do a silent call, so the interaction type is there for handling `InteractionRequiredAuthError` (which should always be handled when using `acquireTokenSilent`).

So just changing the interaction type should resolve this. Can you give this a try? Also you mentioned:

`We have set up an Azure AD app registration for this flow. The redirect URL is set up as SPA. We tried enabling both Access tokens (used for implicit flows) and ID tokens (used for implicit and hybrid flows). We are unsure is Allow public client flows is needed.`

Please don't check any of these boxes/switches (they are not needed with msal-browser).

**Comment by cbishop-fv** [comment]
I think maybe it was due to expired tokens. Since implementing the fix for expired tokens Hector offered the CompactToken parsing failed with error code: 80049217 error has also gone away. 

The last two errors we are currently see are :

`The specified object was not found in the store., The process failed to get the correct properties.` From Graph

`Token InteractionRequiredAuthError: interaction_required: Session information is not sufficient for single-sign-on.` From Azure / MSAL

Thank you both for your help as we transition over and roll this out!

**Comment by derisen** [comment]
> I think maybe it was due to expired tokens. Since implementing the fix for expired tokens Hector offered the CompactToken parsing failed with error code: 80049217 error has also gone away.
> 
> The last two errors we are currently see are :
> 
> `The specified object was not found in the store., The process failed to get the correct properties.` From Graph

This is not an MSAL error -best to check with the [Graph SDK](https://github.com/microsoftgraph/msgraph-sdk-javascript) (although it's probably related to no_tokens_found error)

> `Token InteractionRequiredAuthError: interaction_required: Session information is not sufficient for single-sign-on.` From Azure / MSAL

This error should be handled with an interactive method (`acquireTokenPopup`/`acquireTokenRedirect`), so what @hectormmg said applies here as well. I would assume if you use the `msGraphClient` with `interactionType`: `Popup` or `Redirect` this error should be handled by it (in more detail the error tells you that the user does not have an active session with Azure AD, so they need to sign-in i.e. interaction required).

> Thank you both for your help as we transition over and roll this out!

No worries!

**Comment by hectormmg** [comment]
@cbishop-fv please let us know if @derisen 's suggestions helped so we can close the issue.

**Comment by cbishop-fv** [comment]
Hello both! I have done a bit of a rework on our auth flow. Hopefully if will clear a lot fo these issues. I will reach out to graph on some of the other issues that we are seeing down the line. Feel free to close out! Have a good day and thanks!
