### ISSUE TITLE
Service worker issue

### ISSUE THREAD

**Issue by hmsuchier** [AzureAD/microsoft-authentication-library-for-js#5365]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.29.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.4.4

### Public or Confidential Client?

Public

### Description

Hi, 
 Is it possible to bypass the service worker when calling `login.microsoftonline*` urls in a PWA context with this library? I have CORS issues when such queries are handled with service worker, whereas everything is fine without it. With Angular service worker implementation, there is a specific way of doing such bypass by passing  a "ngsw-bypass" parameter in query header or as get parameter, this is usually done with an interceptor. I tried this solution, but for some reason the interceptor gets ignored by this library client. Any help appreciated.
Thanks

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@hmsuchier Thank you for your patience.
When you say you have tried the solution of adding `ngsw-bypass` in the query header as get parameter, but the interceptor gets ignored, are you using an additional interceptor as well as the MsalInterceptor? 

Have you tried adding `ngsw-bypass` as an `extraQueryParameter` or `tokenQueryParameter`? These fields can be added as part of the authRequest for MsalInterceptor configurations, see docs [here](https://azuread.github.io/microsoft-authentication-library-for-js/ref/modules/_azure_msal_angular.html#msalinterceptorauthrequest).
