### ISSUE TITLE
Documentation for Silent Flow (readme.md)

### ISSUE THREAD

**Issue by Andrei15193** [AzureAD/microsoft-authentication-library-for-js#5366]
### Core Library

MSAL Node (@azure/msal-node)

### Wrapper Library

Not Applicable

### Public or Confidential Client?

Confidential

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/silent-flow

### Description

The landing page for the Silent Flow is absent in the repository, there is one for the Refresh Token. This would be useful to have here as well.

In addition, after I've been a bit frustrated around not being able to easily access the refresh token and basically being left with using the silent flow, I've started thinking how to best leverage this.

The issue is around the in-memory cache and that the entire refresh process is done for me, however this becomes a problem if I horizontally scale my application as the cache is not distributed and I have to manually manage this. Initially I thought about a centralized cache that would get updated on each request (in case of a token refresh).

Afterwards I thought about initializing the related objects for each request and to serialize/deserialize the cache per account and maintain that somewhere (Azure Table Storage, Blob Storage, Redis Cache, whichever works as they associated a key (the account unique ID) and a string value which is the serialized cache just for that account). With this approach MSAL Node can do its job and not have to deal conflicting cache changes and so on as it would be spread per account. On logout I would clear the MSAL cache specific to that account.

There probably are other approaches to this, I would like to have this documented and have the horizontal scaling taken into consideration as it can become a problem. Another alternative is to provide a way to plug into the cache for a particular account thus allowing for account-specific actions before and after accessing the cache. Currently, this can only be done at the cache level. This would allow for a configuration at the application level, but the approach I thought about can create closures around the account ID and retrieve that through the current plugin mechanism since each request instantiates the related objects.

**Comment by bgavrilMS** [comment]
Hi @Andrei15193, can you give us more details about your scenario? Are you using a web site (AcquireTokenByAuthorizationCode) or a web api (AcquireTokenOnBehalfOf) ?

For web app via Express MSAL Node does support distributed caching and we have a sample for that. https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/ExpressTestApp

For web api (AcqurieTokenOnBelhalfOf) note that there is a bug which prevents using the refresh token - https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5330 . We can workaround this if you need to, let me know.

@derisen can help answer more questions on this.

**Comment by Andrei15193** [comment]
Hi @bgavrilMS @derisen,

I'm using a web site, it's basically a classic multi-page web application and I'm using the confidential application to authorize by code (`acquireTokenByCode`) and afterwards I ended up using `acquireTokenSilent` to recheck the user.

After thinking more about it I think this is the way it is meant to be used actually, please correct me if I am wrong. `acquireTokenSilent` handles the authentication checks and refreshes making it the one stop for all private routes/endpoints. It checks the validity of the token as well as refreshing it if it expired. If a token cannot be (re)acquired, then you know the user no longer has access to that page/endpoint.

The other methods, such as `acquireTokenByCode`, are used exclusively for beginning an authenticated user session (up until that point they are a guest since we don't really know who they are) and similarly we have the logout flow that ends the authenticated user session.

In my case, each time a route is hit I use `acquireTokenSilent` to check if the user is authenticated. The issue comes if I want to horizontally scale my application because in that case an in-memory cache will not do unless I turn ARR affinity on. If I use a distributed cache that holds all the information in a single blob then I end up with concurrency issues as theoretically multiple requests can access the same resource (cache) and potentially update it, I'd need to lock the resource to ensure it remains consistent.

What I ended up doing is something similar to what you have linked. I stored userId and sessionId (generated upon successful authentication) pairs into Azure Table Storage (I'm already using this service, Redis cache would do the trick but at this point I'd need to create an instance) and basically serialize the cache just for that authenticated user session. Before I call `acquireTokenSilent` I retrieve the cache information and deserialize and afterwards I serialize and save it back to Azure Table Storage. This ensures I can horizontally scale the application and that the risk of conflicting cache changes is almost non-existent. If there is a conflict, it's for that particular authenticated user session only and all other users are not affected. It should work for all normal scenarios even under high stress (I'm not really expecting this, the initial design challenge came from being able to horizontally scale the application without having to turn on ARR affinity).

The userId and sessionId are passed to the browser through HTTP only, signed, secure, and same site `lax` cookies (should provide plenty of security, the `tokenId` and token claims never get to the browser). I get that information back whenever I call `acquireTokenSilent`.

I haven't pushed the code yet to showcase exactly how I approached this; I'm still working on some finishing touches. But what I described above is the approach I've picked in the end. Please let me know if you have any inputs about it, it's greatly appreciated 🙂

**Comment by derisen** [comment]
Hi @Andrei15193 -a couple of remarks:

> Hi @bgavrilMS @derisen,
> 
> I'm using a web site, it's basically a classic multi-page web application and I'm using the confidential application to authorize by code (`acquireTokenByCode`) and afterwards I ended up using `acquireTokenSilent` to recheck the user.
> 
> After thinking more about it I think this is the way it is meant to be used actually, please correct me if I am wrong. `acquireTokenSilent` handles the authentication checks and refreshes making it the one stop for all private routes/endpoints. It checks the validity of the token as well as refreshing it if it expired. If a token cannot be (re)acquired, then you know the user no longer has access to that page/endpoint.
> 

Using `acquireTokenSilent` to check authentication status in your app's routes doesn't strike me as correct usage of this API. `acquireToken*` APIs are primarily for acquiring an access token for some other resource, such as a web API that your web app calls (although `acquireToken*` also happen to return you an ID token). It would work, but I don't think it's efficient. Protocol-wise, the ID token is the proof that your user has authenticated to your app (i.e. your app has information about who this user is). I would instead rely on a session cookie for authentication status checks in routes (which, in a horizontal scaling scenario, should be saved either client side or in a shared store like Redis etc.), and set an expiry for the cookie based on the ID token expiry. When the session expires, the user should be taken to Azure AD to re-establish a user session (which would return you a new ID token).  

> The other methods, such as `acquireTokenByCode`, are used exclusively for beginning an authenticated user session (up until that point they are a guest since we don't really know who they are) and similarly we have the logout flow that ends the authenticated user session.

`acquireTokenByCode` acquires you an access token (and an ID token) by exchanging an authorization code. By the time you would use `acquireTokenByCode`, you would already have an established session with Azure AD (this is what the first leg of this flow, `getAuthCodeUrl` > navigate to that auth code url does). Also, when you are using `acquireTokenBySilent`, you should always handle any `interactionRequiredAuthError` exceptions with `acquireTokenByCode` (just in case).

> In my case, each time a route is hit I use `acquireTokenSilent` to check if the user is authenticated. The issue comes if I want to horizontally scale my application because in that case an in-memory cache will not do unless I turn ARR affinity on. If I use a distributed cache that holds all the information in a single blob then I end up with concurrency issues as theoretically multiple requests can access the same resource (cache) and potentially update it, I'd need to lock the resource to ensure it remains consistent.
> 
> What I ended up doing is something similar to what you have linked. I stored userId and sessionId (generated upon successful authentication) pairs into Azure Table Storage (I'm already using this service, Redis cache would do the trick but at this point I'd need to create an instance) and basically serialize the cache just for that authenticated user session. Before I call `acquireTokenSilent` I retrieve the cache information and deserialize and afterwards I serialize and save it back to Azure Table Storage. This ensures I can horizontally scale the application and that the risk of conflicting cache changes is almost non-existent. If there is a conflict, it's for that particular authenticated user session only and all other users are not affected. It should work for all normal scenarios even under high stress (I'm not really expecting this, the initial design challenge came from being able to horizontally scale the application without having to turn on ARR affinity).

That's pretty much what we did in the distributed caching sample with Redis: [RedisTestApp](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/RedisTestApp). Feel free to let us know your experience and findings -we would really appreciate input on scaling scenarios!

**Comment by Andrei15193** [comment]
> Hi @Andrei15193 -a couple of remarks:
> 
> > Hi @bgavrilMS @derisen,
> > I'm using a web site, it's basically a classic multi-page web application and I'm using the confidential application to authorize by code (`acquireTokenByCode`) and afterwards I ended up using `acquireTokenSilent` to recheck the user.
> > After thinking more about it I think this is the way it is meant to be used actually, please correct me if I am wrong. `acquireTokenSilent` handles the authentication checks and refreshes making it the one stop for all private routes/endpoints. It checks the validity of the token as well as refreshing it if it expired. If a token cannot be (re)acquired, then you know the user no longer has access to that page/endpoint.
> 
> Using `acquireTokenSilent` to check authentication status in your app's routes doesn't strike me as correct usage of this API. `acquireToken*` APIs are primarily for acquiring an access token for some other resource, such as a web API that your web app calls (although `acquireToken*` also happen to return you an ID token). It would work, but I don't think it's efficient. Protocol-wise, the ID token is the proof that your user has authenticated to your app (i.e. your app has information about who this user is). I would instead rely on a session cookie for authentication status checks in routes (which, in a horizontal scaling scenario, should be saved either client side or in a shared store like Redis etc.), and set an expiry for the cookie based on the ID token expiry. When the session expires, the user should be taken to Azure AD to re-establish a user session (which would return you a new ID token).

This makes sense. I have not thought about this.

The issue I was trying to resolve with `acquireTokenSilent` is to ensure the user session is active with Azure AD and get a new token (cached or refreshed) to check this. Basically, as long as the user is active on the web site clicking on things and making requests just by navigating then I don't want to redirect them to a login page even if they have been doing this for 3 hours. If they remain inactive for 1 hour, or 30 minutes even, then their session has expired and need to reauthenticate.

But since using a session cookie to check the authentication status of the user is required in any approach then at the application level having that session ID is proof of authentication by extension, it only gets generated when I get a favourable response from `acquireTokenByCode` and it gets cleared on sign out (both from the cache service and cookie + the call to Azure AD).

While the user is active on the web site, I can keep resetting the session cookie expiration so it will always be 30 minutes since the last interaction which will in turn be able to keep the session active for 3 hours if the user keeps clicking on stuff. I'm already keeping track of user session in Azure Table Storage, I can basically dump any information about the user that I get from Azure AD when I call `acquireTokenByCode` and not have to worry about getting more information from the token itself. If it was issued, then the user can use the app for as long as the session cookie is kept active and there is a corresponding entity in Azure Table Storage for that session in particular (admins may be able to log people out just by removing that entity).

In this case I don't need to use `acquireTokenSilent` at all, and the entire cache serialization/deserialization doesn't need to happen. Simplifies things quite a bit actually now that I think more about it. I was fixated on the refresh token.

> > The other methods, such as `acquireTokenByCode`, are used exclusively for beginning an authenticated user session (up until that point they are a guest since we don't really know who they are) and similarly we have the logout flow that ends the authenticated user session.
> 
> `acquireTokenByCode` acquires you an access token (and an ID token) by exchanging an authorization code. By the time you would use `acquireTokenByCode`, you would already have an established session with Azure AD (this is what the first leg of this flow, `getAuthCodeUrl` > navigate to that auth code url does). Also, when you are using `acquireTokenBySilent`, you should always handle any `interactionRequiredAuthError` exceptions with `acquireTokenByCode` (just in case).

I have not thought about `interactionRequiredAuthError` and didn't cover it. With the initial approach it would be the same as not finding a serialized cache for that session, still had to cover the case though.

> > In my case, each time a route is hit I use `acquireTokenSilent` to check if the user is authenticated. The issue comes if I want to horizontally scale my application because in that case an in-memory cache will not do unless I turn ARR affinity on. If I use a distributed cache that holds all the information in a single blob then I end up with concurrency issues as theoretically multiple requests can access the same resource (cache) and potentially update it, I'd need to lock the resource to ensure it remains consistent.
> > What I ended up doing is something similar to what you have linked. I stored userId and sessionId (generated upon successful authentication) pairs into Azure Table Storage (I'm already using this service, Redis cache would do the trick but at this point I'd need to create an instance) and basically serialize the cache just for that authenticated user session. Before I call `acquireTokenSilent` I retrieve the cache information and deserialize and afterwards I serialize and save it back to Azure Table Storage. This ensures I can horizontally scale the application and that the risk of conflicting cache changes is almost non-existent. If there is a conflict, it's for that particular authenticated user session only and all other users are not affected. It should work for all normal scenarios even under high stress (I'm not really expecting this, the initial design challenge came from being able to horizontally scale the application without having to turn on ARR affinity).
> 
> That's pretty much what we did in the distributed caching sample with Redis: [RedisTestApp](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/RedisTestApp). Feel free to let us know your experience and findings -we would really appreciate input on scaling scenarios!

Some of it I did get right, hehe 🙂

**Comment by derisen** [comment]
> This makes sense. I have not thought about this.
> 
> The issue I was trying to resolve with `acquireTokenSilent` is to ensure the user session is active with Azure AD and get a new token (cached or refreshed) to check this. Basically, as long as the user is active on the web site clicking on things and making requests just by navigating then I don't want to redirect them to a login page even if they have been doing this for 3 hours. If they remain inactive for 1 hour, or 30 minutes even, then their session has expired and need to reauthenticate.
> 
> But since using a session cookie to check the authentication status of the user is required in any approach then at the application level having that session ID is proof of authentication by extension, it only gets generated when I get a favourable response from `acquireTokenByCode` and it gets cleared on sign out (both from the cache service and cookie + the call to Azure AD).
> 
> While the user is active on the web site, I can keep resetting the session cookie expiration so it will always be 30 minutes since the last interaction which will in turn be able to keep the session active for 3 hours if the user keeps clicking on stuff. I'm already keeping track of user session in Azure Table Storage, I can basically dump any information about the user that I get from Azure AD when I call `acquireTokenByCode` and not have to worry about getting more information from the token itself. If it was issued, then the user can use the app for as long as the session cookie is kept active and there is a corresponding entity in Azure Table Storage for that session in particular (admins may be able to log people out just by removing that entity).
> 

More or less, but in general I would recommend not to go beyond the ID token expiry time, since there could be changes to user's status,  account info or tenant's policies and your app might be out of sync with that. I would also not expire the session too soon -since its bad user experience and unnecessary load on Azure AD. Probably best to be selective about it -certain pages may contain sensitive info and may require re-authentication, while others can be more lax about it. There are also other Azure AD mechanisms like [step-up authentication](https://learn.microsoft.com/en-us/azure/active-directory/develop/developer-guide-conditional-access-authentication-context) and the [OIDC max_age request parameter](https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.3.1.2.1) that gives you more fine-grained control over this.

**Comment by Andrei15193** [comment]
> More or less, but in general I would recommend not to go beyond the ID token expiry time, since there could be changes to user's status, account info or tenant's policies and your app might be out of sync with that. I would also not expire the session too soon -since its bad user experience and unnecessary load on Azure AD. Probably best to be selective about it -certain pages may contain sensitive info and may require re-authentication, while others can be more lax about it. There are also other Azure AD mechanisms like [step-up authentication](https://learn.microsoft.com/en-us/azure/active-directory/develop/developer-guide-conditional-access-authentication-context) and the [OIDC max_age request parameter](https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.3.1.2.1) that gives you more fine-grained control over this.

Makes sense, in this case I could still use `acquireTokenByCode` and force a token refresh when the session is close to expire so the user would be prompted to re-authenticate only if it is necessary.

**Comment by derisen** [comment]
@Andrei15193 You can use the [`forceRefresh` parameter](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/token-lifetimes.md#token-renewal) in the request object to skip a cached token and go to the service to renew them. In general try to follow the pattern:

````javascript
try {
      // attempt silent
      const response = await msal.acquireTokenSilent(request)
} catch(error) {
      if (error instanceof InteractionRequiredAuthError) {
              // acquire token interactively
      }

     // handle other errors
}
````

Make sure to get yourself familar with [this doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/acquire-token.md) (this is for msal-browser, but mostly applies to msal-node as well). 

Closing this, but feel free to raise another issue if you have other questions!
