### ISSUE TITLE
Long latencies from MSAL leading to timeouts

### ISSUE THREAD

**Issue by r-delgadillo** [AzureAD/microsoft-authentication-library-for-js#5367]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.14.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Confidential

### Description

We are experiencing long latencies when calling several methods for our Confidential client. I would imagine some network latencies occuring for SOME of these methods but the one that concerns me is `getAuthCodeUrl`. This method is used to generate the redirect/sign-in URL to AAD.  I would not expect these calls to ever take > 15 seconds to execute (We configured `Promise.race` of 15 seconds). In the last 24 hours, we've received 62 hits on this method taking greater than 15 seconds.

Some other methods that are also showing timeouts on our side are:

- AcquireTokenByCode
- AcquireTokenByRefreshToken	

### MSAL Configuration

```javascript
return new msal.ConfidentialClientApplication({
            auth: {
                clientId,
                authority: this._authority,
                clientCertificate: {
                    thumbprint: pem.thumbprint,
                    privateKey: pem.privateKey,
                    x5c: pem.certificate,
                },
            },
        });
```

### Relevant Code Snippets

```javascript
private async sendRequest<T>(
        log: CommonEventLogger.Scope,
        operationPromise: Promise<T>
    ): Promise<T> {
        const timeoutMs = 15000; // 15 seconds
        try {
            return await CommonUtils.promiseTimeout<T>(
                <msalMethodPromise>,
                timeoutMs,
                ErrorCodes.MsalTimeoutError({ timeoutMs })
            );
        } catch (err) {
            throw this.mapError(err, log);
        }
    }
```

### Reproduction Steps

Unfortunately, we do not have repro steps for forcing a timeout to occur.

### Expected Behavior

I would expect `getAuthCodeUrl` not to take > 15 seconds to generate.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Source

Internal (Microsoft)

**Comment by r-delgadillo** [comment]
FYI, we've monitored and do not have any concerns about our event loop delay in NodeJS.

**Comment by derisen** [comment]
I believe `getAuthCodeUrl` does endpoint discovery, so there might be network latencies with that as well -cc @bgavrilMS @Robbie-Microsoft

**Comment by bgavrilMS** [comment]
There seem to be several issues coming from instance discoevery, but we cannot reproduce. @Robbie-Microsoft is adding more logging to MSAL.

@r-delgadillo - one workaround would be to use `knownAuthorities`. This implies that you know the authority - e.g. login.microsoftonline.com which you talk go (as opposed to reading the authority string from the 401 header of a resource, which could be compromised).

If authority is known, there is no need to do instance discovery and hopefully this issue is averted.

**Comment by r-delgadillo** [comment]
Thank you @bgavrilMS . I just added `knownAuthorities` and it's definitely helping with performance. I'll update the thread once it's deployed to production to see the impact on our timeouts.

Regarding the issues from instance discovery, is that being tracked somewhere else?

**Comment by bgavrilMS** [comment]
Yes - https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4879

**Comment by bgavrilMS** [comment]
Root cause not resolved, still trying to root cause the issue from #4879
