### ISSUE TITLE
Can I use MSAL.js 2.0 with OIDC and a client secret

### ISSUE THREAD

**Issue by afridley** [AzureAD/microsoft-authentication-library-for-js#5368]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.30

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.9

### Public or Confidential Client?

Public

### Description

Im hoping to use MSAL 2.0 react wrapper. Im currently getting the error that the client secret is undefined or incorrect.
We are using B2C with OpenId Connect. Ive added clientSecret to my MSAL config but im not sure it's being used. What configuration would need to be done in Azure to get this working? Is it something with the OpenId config or can clientSecret still be used?

### MSAL Configuration

```javascript
const msalConfig = {
  auth: {
   
    clientId: clientId,
    authority: authUrl,
    redirectUri: '/',
    clientSecret: clientSecret,
    postLogoutRedirectUri: '/sign-in',
    navigateToLoginRequestUrl: false,
    knownAuthorities: [`tenent.b2clogin.com`],
  },
}

export const loginRequest = {
  scopes: ['openid'],
}
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by lasarian27** [comment]
@afridley How did you solve this?

**Comment by thuyng-ing** [comment]
@afridley How did you solve this?
