### ISSUE TITLE
Acquire access token from API using AzureB2C

### ISSUE THREAD

**Issue by AniTang99** [AzureAD/microsoft-authentication-library-for-js#5376]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.20.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.6

### Public or Confidential Client?

Public

### Description

I am trying to implement a signup-signin process to allow external users into our application using AzureB2C. My angular application and API are currently protected using Azure AD authentication with the PKCE flow. I have added a service principal for the API registration from the Azure AD tenant in the Azure B2C tenant. I have added the necessary scopes in the AzureB2C client app registration. However, when I try to login using `loginRedirect()` I only get back an Id Token and Refresh Token and am unable to access the API. I am not super familiar with creating a multi-tenant application, so I am unsure if my approach is correct. Any help would be greatly appreciated!

### MSAL Configuration

```javascript
[
    {
        "AzureAd" : {
            "config" : {
                "auth" : {
                    "authority" : "https://login.microsoftonline.com/{tenantId}",
                    "redirectUri" : "http://localhost:4200"
                },
                "cache" : {
                    "cahceLocation" : "localStorage",
                    "storeAuthStateInCookie" : false
                }
            },
            "guard" : {
                "interactionType" : "popup",
                "authRequest" : {
                    "scopes" : ["https://{azureADTenantdomain}.onmicrosoft.com/{apiClientId}/access_as_user"]
                }
            },
            "interceptor" : {
                "protectedResourceMap" : [
                    ["https://localhost:5445/api/*", ["https://{azureADTenantdomain}.onmicrosoft.com/{apiClientId}/access_as_user"]],
                    ["https://graph.microsoft.com/v1.0/", ["User.Read", "User.ReadBasic.All"]]
                ]
            }
        } 
    }, 
    {
        "AzureB2C": {
            "config" : {
                "auth" : {
                    "authority" : "https://{b2cTenantDomain}.b2clogin.com/{b2cTenantDomain}.onmicrosoft.com/B2C_1_{susi_flow}",
                    "knownAuthorities" : ["{b2cTenantDomain}.b2clogin.com", "{azureADTenantdomain}.onmicrosoft.com"],
                    "redirectUri" : "http://localhost:4200"
                },
                "cache" : {
                    "cahceLocation" : "localStorage",
                    "storeAuthStateInCookie" : false
                }
            },
            "guard" : {
                "interactionType" : "popup",
                "authRequest" : {
                    "scopes" : ["https://{azureADTenantdomain}.onmicrosoft.com/{apiClientId}/access_as_user"]
                }
            },
            "interceptor" : {
                "protectedResourceMap" : [
                    ["https://localhost:5445/api/*", ["https://{azureADTenantdomain}.onmicrosoft.com/{apiClientId}/access_as_user"]]
                ]
            }
        }
    }
]
```

### Identity Provider

Azure B2C Basic Policy

### Source

External (Customer)

**Comment by derisen** [comment]
@AniTang99 what are you passing as [request object](https://azuread.github.io/microsoft-authentication-library-for-js/ref/modules/_azure_msal_browser.html#redirectrequest) to `loginRedirect()`? If you are not adding scopes parameter that contains your API scope(s), you won't be receiving an access token after `loginRedirect()` in B2C -so that's expected.

**Comment by AniTang99** [comment]
Thank you for replying, @derisen! Here is my login logic. The URL seems to include the scope I am trying to access.

```
this.authService.loginRedirect({ scopes:['https://{domain}.onmicrosoft.com/{apiClientId}/access_as_user']} as RedirectRequest)
```

I don't get an access token so then I tried getting one explicitly by calling acquireTokenPopup and the response succeeds but the accesstoken is empty:

```
const req = {scopes: ['https://{domain}.onmicrosoft.com/{apiClientId}/access_as_user']} as PopupRequest
 console.log(req);
 this.authService.acquireTokenPopup(req).subscribe(result => {
      console.log(result);
 })
```
Same response in both cases:
![image](https://user-images.githubusercontent.com/31628247/201192084-b904ce58-a1bc-414f-a10f-93e8cea6d5a8.png)

**Comment by derisen** [comment]
@AniTang99 thanks. Can you double check if this scope/permission is admin consented? (since users cannot consent to permissions in B2C). You'll see this on the API Permissions blade on Azure portal > Azure AD B2C > App Registration

**Comment by AniTang99** [comment]
Are you talking about this permission here? 
![image](https://user-images.githubusercontent.com/31628247/201194006-12882dcd-0e27-46dc-9c24-d919bef62c53.png)

**Comment by AniTang99** [comment]
@derisen I have gone ahead and granted admin consent to that permission in the Azure Portal. However, that did not return an access token when I tried the same login process.

**Comment by derisen** [comment]
@AniTang99 that's curious, I don't see anything wrong with your request or scope. I see you have configured msal interceptor protectedResourceMap -what happens when the interceptor is triggered i.e. when you try to call the "https://localhost:5445/api/*"? Is the AT obtained then?

**Comment by AniTang99** [comment]
@derisen After cleaning the slate and rewriting the login process step by step, I am now successfully able to get an access token! However, now my API is rejecting the access token due to an invalid signature. The API successfully accepts tokens when logging in as a user from the Azure AD tenant so do I need to somehow match the signature of the tokens, or should my API be configured somehow to handle both the Azure AD and B2C tokens? Thank you for your guidance!!

API is an ASP.NET Core web api

**Comment by AniTang99** [comment]
@derisen I was able to add another authentication scheme in addition to the Azure AD scheme and now the API correctly checks for either token! Thank you for your help.
