### ISSUE TITLE
Ask for regional authorities support

### ISSUE THREAD

**Issue by dilidili** [AzureAD/microsoft-authentication-library-for-js#5382]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL React (@azure/msal-react)

### Public or Confidential Client?

Public

### Description

The ability to try auto detect regional authorities has been supported on msal-node and releted codes also exists on msal-common package. https://github.com/AzureAD/microsoft-authentication-library-for-js/commit/0dbf9719734aeedf02e77bec47608605036467f3

We have a need to support regional authorities on a JS based SPA where a user can continue to access AAD with better resilience. Do you have any plan for this feature support on msal-browser. thanks.

### Source

Internal (Microsoft)

**Comment by jo-arroyo** [comment]
@dilidili We do not currently have this feature committed, but will add this to the backlog. 

@EmLauber for feature request.

**Comment by EmLauber** [comment]
Tracking in the backlog but can't commit to an ETA. To clarify, @dilidili you are looking for the exact functionality in MSAL-node replicated in msal-browser or was there something unique for msal-browser?

**Comment by sudamsfJy** [comment]
> Tracking in the backlog but can't commit to an ETA. To clarify, @dilidili you are looking for the exact functionality in MSAL-node replicated in msal-browser or was there something unique for msal-browser?

Actually we want the functionality of [this](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1956). Not sure what ETA for MSAL.js.
