### ISSUE TITLE
How to remove `Continue` button from MSAL email verification page while signup.

### ISSUE THREAD

**Issue by chahal26** [AzureAD/microsoft-authentication-library-for-js#5387]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.24.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.3.0

### Public or Confidential Client?

Confidential

### Description

I need to remove the `Continue` button from email verification page.

![image](https://user-images.githubusercontent.com/91047757/201292854-dc256861-c2ac-4e2d-b380-b34254186d12.png)

How can I do this?

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@chahal26 This email verification page is shown by the server and not controlled by MSAL.

**Comment by chahal26** [comment]
@jo-arroyo Thanks for your reply. So, isn't there any way to get rid of it?
