### ISSUE TITLE
Use this lib for vscode extension development to sign in users to Azure AD

### ISSUE THREAD

**Issue by mkohns** [AzureAD/microsoft-authentication-library-for-js#5389]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

newest

### Wrapper Library

MSAL Node Extensions (@azure/msal-node-extensions)

### Wrapper Library Version

newest

### Public or Confidential Client?

Confidential

### Description

Hi! I have a vscode extension. I am looking for a possibility to sign in users to Azure AD via authentication code flow with PKCE inside my vscode extension. My goal ist to start the auth flow on extension activation hook and (after all) get the OAuth2 access token to perform API calls. I am familiar with this flow on browsers. All approach I tried so far did not work as msal uses browser based session/localstorage which is not available in vscode. 

Does this lib could help my requirements to became reality?

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by tnorling** [comment]
Yes, you can use msal-node for this. Do you have any specific questions?
