### ISSUE TITLE
acquireTokenPopup not works on Android mobile devices if MFA is needed

### ISSUE THREAD

**Issue by dilidili** [AzureAD/microsoft-authentication-library-for-js#5391]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.31.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.10

### Public or Confidential Client?

Public

### Description

When call acquireTokenPopup on Android devices, browser will open a new tab with MFA request shows. After complete the MFA, the new tab will keep unclosed with blank page at application redirect URL.

After checking the codebase, found the root cause is that msal-browser use a function named **monitorPopupForHash** to monitor the code in hash with default 30ms interval. However, the browser on mobile devices only allow 1000ms minimum interval(on my testing devices) on out of fucus tabs, hence the monitorPopupForHash will miss the code hash change which removed by msal-browser itself.

Here is the console logs I added in the monitorPopupForHash callback funciton.
![image](https://user-images.githubusercontent.com/5905726/201567954-c992579d-09b8-496a-9354-b092859ea1fa.png)

### MSAL Configuration

```javascript
export const msalConfig: Configuration = {
  auth: {
    clientId: IWPAppId,
    redirectUri: `${window.location.origin}/spa-signin-oidc`,
    postLogoutRedirectUri: "/",
  },
  cache: {
    cacheLocation: "localStorage",
  },
  system: {
    // Give more timeout for waiting for a response hash in an iframe or popup other than default value 6s
    iframeHashTimeout: 10000,
    loggerOptions: {
      loggerCallback: (
        level: LogLevel,
        message: string,
        containsPii: boolean
      ): void => {
        if (containsPii) {
          return;
        }

        switch (level) {
          case LogLevel.Error:
            sendConsoleErrorEvent(`@azure/msal-browser ${message}`);
            return;
          case LogLevel.Info:
          case LogLevel.Verbose:
          case LogLevel.Warning:
            sendNormalEvent(
              `@azure/msal-browser ${message}`,
              "web",
              // Use 3 for EventSendType.SyncFetch in const enum isolated module
              shouldSendSync(message) ? 3 : undefined
            );
            return;
        }
      },
      piiLoggingEnabled: false,
    },
  },
};
```

### Relevant Code Snippets

```javascript
export const acquireToken = (request: AcquireTokenRequest) => {
  const account = app.getActiveAccount();
  if (!account) return null;

  return app
    .acquireTokenSilent({
      scopes: request.scopes,
      account: account,
    })
    .then(function (accessTokenResponse) {
      // Acquire token silent success
      return accessTokenResponse;
    })
    .catch(function (error) {
      if (request.interactionType === "none") {
        return error;
      }

      // Acquire token silent failure, and send an interactive request
      if (error instanceof InteractionRequiredAuthError) {
        return app
          .acquireTokenPopup({
            scopes: request.scopes,
            loginHint: userInfo.email,
          })
          .then(function (accessTokenResponse) {
            // Acquire token interactive success
            return accessTokenResponse;
          })
          .catch(function (error) {
            // Acquire token interactive failure
            console.error(error);
            return error;
          });
      }

      console.error(error);
      return error;
    });
};
```

### Reproduction Steps

1. Setup a account need MFA when acquire token.
2. Trigger MFA flow.
3. Consent MFA request.

### Expected Behavior

The popup window will close automatically and the MFA process is complete.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Safari

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
> monitorPopupForHash will miss the code hash change which removed by msal-browser itself.

I'm a bit confused by this statement. The `monitorPopupForHash` code is what reads and removes the hash. If the hash is being removed but not detected it means it's being removed by something else unexpectedly. You should determine what is removing the hash and make it stop.

Also, if the default interval is a problem you can provide your own value through the `system` config setting `pollIntervalMilliseconds`

**Comment by dilidili** [comment]
Hi @tnorling , due to I tested our web with #code=123 will not remove the code part automatically, I will dig more about this remove behaviour on popup window. thanks.

For the pollIntervalMilliseconds config, I just use the default value. I think the problem is the device browser limitation on unfocused web page.
