### ISSUE TITLE
Please post a non-minified version on the CDN

### ISSUE THREAD

**Issue by SaeedAkhter-MSFT** [AzureAD/microsoft-authentication-library-for-js#54]
https://secure.aadcdn.microsoftonline-p.com/lib/0.1.1/js/msal.min.js does exist BUT
https://secure.aadcdn.microsoftonline-p.com/lib/0.1.1/js/msal.js does not exist.

Please post a version that can be used for debugging on the CDN.

**Comment by rohitnarula7176** [comment]
@SaeedAkhter-MSFT Fixed in the latest release.
