### ISSUE TITLE
tokenReceivedCallBack called before constructor returns

### ISSUE THREAD

**Issue by midgethoen** [AzureAD/microsoft-authentication-library-for-js#540]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x ] Other... Please describe: api enhancement
</code></pre>

## Browser:
- [ x] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

Library version: 0.1.1

## Current behavior

when initiating UserAgentApplication with tokenReceivedCallBack, the callback is called before the constructor returns. 

## Expected behavior

my expectation was that would be able to use the returned api from within the callback. This was a bit of a hurdle for me to get started with the lib

## Minimal reproduction of the problem with instructions

```js
// see: https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp/blob/master/index.html#L48
var clientApplication = new Msal.UserAgentApplication(applicationConfig.clientID, applicationConfig.authority, function (errorDesc, token, error, tokenType) {
            // Called after loginRedirect or acquireTokenPopup
            console.log('user:', clientApplication.getUser());
        })
```

**Comment by midgethoen** [comment]
after submitting this issue  i asked myself; why it take me so long to figure this out 🤔

turns out the callback also swallows errors

**Comment by zamzowd** [comment]
If it didn't check the hash and fire the callback in the constructor, wouldn't it need an "init" function that devs have to call after the constructor?  That seems like a less desirable implementation.

Turns out, you can access the UserAgentApplication with `this` inside of the callback.  For your example, you can have:
```
console.log('user:', this.getUser());
```

**Comment by zamzowd** [comment]
Regarding swallowed errors, it puts them into the logger provided in the UserAgentApplication constructor.  It's not a pattern I'm too fond of, but I think the idea is to avoid writing to console for production applications.  For development, you can just provide a logger that writes to console.

**Comment by midgethoen** [comment]
Thanks for your insight, Dean.

> If it didn't check the hash and fire the callback in the constructor, wouldn't it need an "init" function that devs have to call after the constructor? That seems like a less desirable implementation.

I was thinking the callback could be called the next tick or something. although, I might be overlooking something.

Anyway. I'm sure there's good reasons for all design decisions. I just wanted to report my initial experience could have been better.  Maybe extending the examples a bit could go a long way. 

Ill close this now as I don't want to be nitpicking any more. 

Have a great day!
