### ISSUE TITLE
Node code runs inside WSL2 but doesn't outside.

### ISSUE THREAD

**Issue by luixal** [AzureAD/microsoft-authentication-library-for-js#5401]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.14.3

### Wrapper Library

Not Applicable

### Wrapper Library Version

n/a

### Public or Confidential Client?

Confidential

### Description

Hi,

I have a node.js script using @azure/msal-node that works perfectly inside the WSL2 environment, but not in windows itself. Auth crashes.

First, I got this error (which I don't get when running in WSL2):

```json
{
  "errorCode": "endpoints_resolution_error",
  "errorMessage": "Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter.",
  "subError": "",
  "correlationId": "589656e9-5e4e-4fbd-bf62-994747a140f8"
}
```

when I added the `knownAuthorities` field to the config, I get this other message:

```json
{
  "errorCode": "endpoints_resolution_error",
  "errorMessage": "Error: could not resolve endpoints. Please check network and try again. Detail: ClientAuthError: openid_config_error: Could not retrieve endpoints. Check your authority and verify the .well-known/openid-configuration endpoint returns the required endpoints. Attempted to retrieve endpoints from: https://login.microsoftonline.com/<my-tenant-id>/v2.0/.well-known/openid-configuration",
  "subError": "",
  "correlationId": "9a2c3558-5538-4a98-8221-e296f5449817"
}
```

If I point a browser to that url, it loads without a problem.

### MSAL Configuration

```javascript
{
    auth: {
      clientId: '<my-client-id>',
      authority: 'https://login.microsoftonline.com/<my-tenant-id>',
      clientSecret: '<my-client-secret>',
      knownAuthorities: ['https://login.microsoftonline.com/<my-tenant-id>'] // added after first error
    }
  }
```

### Relevant Code Snippets

```javascript
async function login() {
  const msalConfig = {
    auth: {
      clientId: '<my-client-id>',
      authority: 'https://login.microsoftonline.com/<my-tenant-id>',
      clientSecret: '<my-client-secret>',
      knownAuthorities: ['https://login.microsoftonline.com/<my-tenant-id>'] // added after first error
    }
  };

  const tokenRequest = {
    scopes: ["https://outlook.office365.com/.default"]
  };

  try {
    const cca = new msal.ConfidentialClientApplication(msalConfig);
    // const msalTokenCache = cca.getTokenCache();
    const authResponse = await cca.acquireTokenByClientCredential(tokenRequest);
    token = authResponse.accessToken;
  } catch (err) {
    console.log('AUTH ERROR');
    console.log(err);
  }
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by tnorling** [comment]
@luixal Can you try debugging the [network client](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/src/network/HttpClient.ts) to see if the request is going out and coming back? You can copy it, make any changes you need to help debug and provide it back to msal-node through the `networkClient` [config parameter](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/f318796c278e39153e8cd9bf3ce03259cb80c8a6/lib/msal-node/src/config/Configuration.ts#L68)

**Comment by luixal** [comment]
Hi,

This problem was due to not running node with the right certificates. Node doesn't take certs from the windows cert repo, but I had them configured in the WSL env, that's why it worked in the WSL but not in outside.

Thanks!
