### ISSUE TITLE
Enable "Keep Me Signed In" MSAL

### ISSUE THREAD

**Issue by alexseyrakov** [AzureAD/microsoft-authentication-library-for-js#5404]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.29.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

We use the MSAL library to access corporate resources.
The KMSI checkbox does not appear on login page.

AD FS server command: Set-AdfsProperties -EnableKmsi:$true
Are there any additional settings I need to add in order to show KMSI?

### MSAL Configuration

```javascript
//MSAL Config
const msalConfig = {
  auth: {
      clientId: APPID,
      authority: 'https://corporate.network/adfs/', 
      knownAuthorities: ['https://corporate.network/adfs/'], 
      redirectUri: REDIRECTURL, 
      
  },
  cache: {
      cacheLocation: "localStorage",
      storeAuthStateInCookie: true, 
  },
};

const msalInstance = new msal.PublicClientApplication(msalConfig);

function getWebAuth() {
  msalInstance
    .acquireTokenPopup(loginRequest)
    .then(handleResponse)
    .then(() => {
      
    })
    .catch((error) => {
      console.error(error);
     
    });
}
```

### Identity Provider

ADFS

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
@alexseyrakov MSAL.js does not control the login UX on the server, you will need to reach out to your ADFS admin for any issues with the login page.
