### ISSUE TITLE
Msal Interceptor redirects to common endpoint, not to the specific tenant endpoint

### ISSUE THREAD

**Issue by web265p3** [AzureAD/microsoft-authentication-library-for-js#5422]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.32.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.5.0

### Public or Confidential Client?

Public

### Description

In the apps I develop, only people with a work or school account that are inside our organization should be able to login. This will also include guests.

To protect certain endpoints, I am using the MsalInterceptor that will protect some of my urls.

This works _always_ when we open a fresh browser tab. If one of the protected resource urls is called, the user gets redirected to:

https://login.microsoftonline.com/{OUR TENANT ID}/oauth2/v2.0/authorize?client_id={THE CLIENT ID OF THE APP}&scope=user.read%....

The app gets those values from my configuration:

    auth: {
      clientId: {CLIENTID}, 
      authority: 'https://login.microsoftonline.com/{TENANTID}',
      redirectUri: '/',
      postLogoutRedirectUri: '/'
    },

So far, everything works fine.
But sometimes - if the user did not use the app for a while and returns, the app wants him to sign in again. This would be okay, but now the MSALInterceptor redirects not to our organization endpoint anymore, but to the common endpoint:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id={OUR CLIENTID}&scope=user.read%20

This happens mainly for guests.
Of course the user cannot login here, because we are now outside of the organization. The login fails... 
This only happens from time to time, so after some reloads of the application, the user can use the app without any issues.

I have no explanation for this strange behaviour... 
Any ideas?

### MSAL Configuration

```javascript
return new PublicClientApplication({
    auth: {
      clientId: appConfiguration.clientId, 
      authority: 'https://login.microsoftonline.com/{OUR TENANTID}',
      redirectUri: '/',
      postLogoutRedirectUri: '/'
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE, // set to true for IE 11. Remove this line to use Angular Universal
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Warning,
        piiLoggingEnabled: false
      }
    }
  });
```

### Relevant Code Snippets

```javascript
Nothing special - just the sample code
```

### Reproduction Steps

I just used the code from the samples section here: https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular14-rxjs7-sample-app

Then login with a guest user, wait some hours and reload the app... it's hard to reproduce and happens only from time to time, but usually a bad request first goes to the token endpoint (common) and then the user is redirected to a login page with a common endpoint - not the actual tenant that was configured in the authority. This causes the issue.

### Expected Behavior

Always redirect to our organizations login page, never use the common endpoint

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge

### Source

External (Customer)

**Comment by sameerag** [comment]
@web265p3 Can you share MSAL logs?

**Comment by web265p3** [comment]
I am already sure that this only happens to guests. I could enable the logging and set it to verbose.

Those are the results from the console at the very end where the navigation to the common endpoint happens - you can see the last line:

Navigate to https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=3c0d63b3-c2f9-4e4b-b0e8-b8fd0fa39e01&scope=user.read%20...

But why the common endpoint?

![image](https://user-images.githubusercontent.com/20642406/204005579-99465f8d-98e7-43ba-86bc-1782750d2618.png)

**Comment by web265p3** [comment]
I think I partially could resolve my problem - I changed my login option in the app registration to "Accounts in this organizational directory only (MY COMPANY only - Single tenant)"

Now the common page is not shown anymore... not a good solution though, because I will have the problem in a multi tenant app...

**Comment by derisen** [comment]
@web265p3 this is strange, MsalInterceptor is supposed to use the static properties set in the msal config. Did you look into [dynamically configuring the msalInterceptor](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/multi-tenant.md#msalinterceptor---dynamic-auth-request-multi-tenant-tokens)? You can detect guest users via the [optional id token claim (**acct**)](https://learn.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims#v10-and-v20-optional-claims-set) and perform some logic on the auth request.
