### ISSUE TITLE
How can I request a login prompt or select_account option for my ConfidentialClientApplication using redirect?

### ISSUE THREAD

**Issue by PhilHannent** [AzureAD/microsoft-authentication-library-for-js#5423]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.14.4

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Confidential

### Description

My service is most likely not going to use the users own account but a dedicated administration account. 

I see that the MSAL.js documentation talks about different prompt types which would allow me control over this behaviour:
https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-js-prompt-behavior

However, within the configuration documentation of the ConfidentialClientApplication I do not see any reference to where I can specify the prompt I would want to use for the redirect. Can you tell me if this is available and where the documentation is?

Thank you

### Source

External (Customer)

**Comment by sameerag** [comment]
@PhilHannent `prompt` param is supported the same way in `msal-node`, any `request` object can be initialized with a `prompt` - an eg of the request is [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/src/request/AuthorizationUrlRequest.ts). 

> However, within the configuration documentation of the ConfidentialClientApplication I do not see any reference to where I can specify the prompt I would want to use for the redirect. Can you tell me if this is available and where the documentation is?

The `prompt` support in `msal-browser` is also supported in `request` and not `configuration`. `Prompt` determines the auth UX experience: eg., if you set it to `select_account`, when the auth request is executed, you see the selection of current accounts displayed. 

Can you please elaborate  how you think `prompt` will help or is needed in your use case?

cc @derisen as this could be a usage question.

**Comment by derisen** [comment]
@PhilHannent you can use a prompt parameter with the [getAuthCodeUrl()](https://azuread.github.io/microsoft-authentication-library-for-js/ref/classes/_azure_msal_node.confidentialclientapplication.html#getauthcodeurl) API -here's an example: 

```javascript
const app = express();
const msalClient = new ConfidentialClientApplication(msalConfig);

app.get('/signin', async function (req, res, next) {
  try {
    const authCodeUrl = await msalClient.getAuthCodeUrl({
         scopes: ["User.Read"],
         redirectUri: "/redirect",
         prompt: "select_account"
    });
    
    res.redirect(authCodeUrl); // will take you to AAD /authorize endpoint with account selection UI
  } catch (err) {
    next(err))
  }
});
```

**Comment by PhilHannent** [comment]
Thank you for all the help, it worked.

As to answer this question:
> Can you please elaborate how you think prompt will help or is needed in your use case?

We have a platform that helps with room booking, the user links the account that needs to manage the rooms. That account will have the delegate permissions on the mailboxes. If the user uses their own account they'll fail and we have to warn them in the user interface that they need to add permissions and check the have the correct account. 

Adding the `select_account` prompt will certainly help.
