### ISSUE TITLE
BrowserAuthError Interaction in_progress on page idle

### ISSUE THREAD

**Issue by StevenMedeot** [AzureAD/microsoft-authentication-library-for-js#5424]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.23.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.4

### Public or Confidential Client?

Public

### Description

Idling on our react browser for around 20-30 minute's causes MSAL to throw a `BrowserAuthError` saying that there is currently an interaction in progress. I've checked the code flow on our react app and it doesn't call the login flow at any point before this attempt to login, so I don't believe we're attempting a login and not redirecting the user.  Once we refresh the page it allows us to log in correctly. 

![image](https://user-images.githubusercontent.com/55761357/203834124-1d5e9601-aacf-4ce0-9122-ed4e833cd09f.png)

Does the PublicClientApplication attempt a silent login after idling for a while? And is there a correct way to handle this error to reset the current login state?

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by sameerag** [comment]
@StevenMedeot Can you please share if you have collected any MSAL logs around the time where you see this? We do not trigger a login call afaik but logs can tell you if that is the case.

**Comment by StevenMedeot** [comment]
I did manage to get some logs and here are the logs from MSAL at the time.
[localhost-1669388796059.log](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/10093775/localhost-1669388796059.log)


Edit:
Small update: I was under the impression it was from idling (as told by my QA team), but after doing a bit of testing locally I was unable to retrigger this by idling but instead I could only get this by opening 2 tabs of my browser and then entering the login flow on one of the tabs. The other tab then can not go through to the login flow. Seems like it's setting the `inProgress` state for all tabs open at the time. Setting the `storeAuthStateInCookie` to false should fix it. 

I'll keep an eye out for the `idle problem`

**Comment by sameerag** [comment]
@StevenMedeot We store a temporary cache item `interaction.status: true` to track an interaction in progress.  However can you please confirm if this bit is stored in `localStorage` or `sessionStorage`? It is supposed to be in `sessionStorage` which is not shared across tabs. 

Also if you are trying to create separate sessions in each tab, can you also confirm your cache isn't set to `localStorage`?
