### ISSUE TITLE
The msal-browser Popup API does not work on the mobile web browser.

### ISSUE THREAD

**Issue by blackadi** [AzureAD/microsoft-authentication-library-for-js#5426]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.32.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

When using Vue sample app located [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-browser-samples/vue3-sample-app) to login via Popup API on mobile web browser it will not work as expected but when switching to redirect API it will work normally.

I've tested this using both Android and iPhone mobile browsers, and it's not working when using Popup API, but when using the Redirect API it will work as expected.

Is this a bug on the mobile device, or is this expected behavior?

### MSAL Configuration

```javascript
The same as in the Vue sample app.
(https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-browser-samples/vue3-sample-app).
```

### Relevant Code Snippets

```javascript
Running the Vue sample app as is
(https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-browser-samples/vue3-sample-app)
```

### Reproduction Steps

1. Cloned this [sample app](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-browser-samples/vue3-sample-app).
2. Modified msal config file to match my app registration.
3. Created `dist` folder by running `npm run build`
4. Deployed `dist` folder to azure static web and tested on iPhone web browser using [this link](https://redirecturiblank.z1.web.core.windows.net/).
7. Popup API not working for mobile web browser (Android and iPhone ).

### Expected Behavior

msal-browser Popup API to login and return token as Redirect API.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Safari, Firefox, Edge

### Regression

@azure/msal-browser 2.32.0

### Source

Internal (Microsoft)

**Comment by sameerag** [comment]
Can you please share the MSAL logs?

**Comment by blackadi** [comment]
@sameerag This is the console logs : 

[Debug] [Tue, 29 Nov 2022 13:59:42 GMT] : [2857ef2b-d8a5-4da0-a42c-fb8449397a34] : @azure/msal-browser@2.32.0 : Verbose - loginPopup called (index.1512a7b6.js, line 27) 
[Debug] [Tue, 29 Nov 2022 13:59:42 GMT] : [2857ef2b-d8a5-4da0-a42c-fb8449397a34] : @azure/msal-browser@2.32.0 : Verbose - acquireTokenPopup called (index.1512a7b6.js, line 27) 
[Debug] [Tue, 29 Nov 2022 13:59:42 GMT] : @azure/msal-browser@2.32.0 : Verbose - preflightBrowserEnvironmentCheck started (index.1512a7b6.js, line 27) 
[Debug] [Tue, 29 Nov 2022 13:59:42 GMT] : @azure/msal-browser@2.32.0 : Verbose - preflightInteractiveRequest called, validating app environment (index.1512a7b6.js, line 27) 
[Debug] [Tue, 29 Nov 2022 13:59:42 GMT] : @azure/msal-browser@2.32.0 : Verbose - getAllAccounts called (index.1512a7b6.js, line 27) 
[Info] [Tue, 29 Nov 2022 13:59:42 GMT] : @azure/msal-browser@2.32.0 : Info - Emitting event: msal:loginStart (index.1512a7b6.js, line 27) 
[Debug] [Tue, 29 Nov 2022 13:59:42 GMT] : @azure/msal-browser@2.32.0 : Verbose - Emitting event to callback 5f709b9f-1856-4835-92c5-ca47147e52c4: msal:loginStart (index.1512a7b6.js, line 27) 
[Debug] [Tue, 29 Nov 2022 13:59:42 GMT] : @azure/msal-browser@2.32.0 : Verbose - Emitting event to callback 40465fae-e6c9-48f0-b966-a92ea22ecf10: msal:loginStart (index.1512a7b6.js, line 27) 
[Debug] [Tue, 29 Nov 2022 13:59:42 GMT] : [2857ef2b-d8a5-4da0-a42c-fb8449397a34] : msal.js.browser@2.32.0 : Verbose - asyncPopup set to false, opening popup before acquiring token (index.1512a7b6.js, line 27) 
[Debug] [Tue, 29 Nov 2022 13:59:42 GMT] : [2857ef2b-d8a5-4da0-a42c-fb8449397a34] : msal.js.browser@2.32.0 : Verbose - Default popup window width used. Window width not configured or invalid. (index.1512a7b6.js, line 27) 
[Debug] [Tue, 29 Nov 2022 13:59:42 GMT] : [2857ef2b-d8a5-4da0-a42c-fb8449397a34] : msal.js.browser@2.32.0 : Verbose - Default popup window height used. Window height not configured or invalid. (index.1512a7b6.js, line 27) 
[Debug] [Tue, 29 Nov 2022 13:59:42 GMT] : [2857ef2b-d8a5-4da0-a42c-fb8449397a34] : msal.js.browser@2.32.0 : Verbose - Default popup window top position used. Window top not configured or invalid. (index.1512a7b6.js, line 27) 
[Debug] [Tue, 29 Nov 2022 13:59:42 GMT] : [2857ef2b-d8a5-4da0-a42c-fb8449397a34] : msal.js.browser@2.32.0 : Verbose - Default popup window left position used. Window left not configured or invalid. (index.1512a7b6.js, line 27) 
[Debug] [Tue, 29 Nov 2022 13:59:42 GMT] : [2857ef2b-d8a5-4da0-a42c-fb8449397a34] : msal.js.browser@2.32.0 : Verbose - acquireTokenPopupAsync called (index.1512a7b6.js, line 27) 
[Debug] [Tue, 29 Nov 2022 13:59:42 GMT] : [2857ef2b-d8a5-4da0-a42c-fb8449397a34] : msal.js.browser@2.32.0 : Verbose - initializeServerTelemetryManager called (index.1512a7b6.js, line 27) 
[Debug] [Tue, 29 Nov 2022 13:59:42 GMT] : [2857ef2b-d8a5-4da0-a42c-fb8449397a34] : msal.js.browser@2.32.0 : Verbose - initializeAuthorizationRequest called (index.1512a7b6.js, line 27) 
[Debug] [Tue, 29 Nov 2022 13:59:42 GMT] : [2857ef2b-d8a5-4da0-a42c-fb8449397a34] : msal.js.browser@2.32.0 : Verbose - getRedirectUri called (index.1512a7b6.js, line 27) 
[Debug] [Tue, 29 Nov 2022 13:59:42 GMT] : [2857ef2b-d8a5-4da0-a42c-fb8449397a34] : msal.js.browser@2.32.0 : Verbose - Initializing BaseAuthRequest (index.1512a7b6.js, line 27) 
[Debug] [Tue, 29 Nov 2022 13:59:42 GMT] : [2857ef2b-d8a5-4da0-a42c-fb8449397a34] : msal.js.browser@2.32.0 : Verbose - Authentication Scheme wasn't explicitly set in request, defaulting to "Bearer" request (index.1512a7b6.js, line 27) 
[Debug] [Tue, 29 Nov 2022 13:59:42 GMT] : [2857ef2b-d8a5-4da0-a42c-fb8449397a34] : msal.js.browser@2.32.0 : Verbose - initializeAuthorizationRequest called (index.1512a7b6.js, line 27) 
[Debug] [Tue, 29 Nov 2022 13:59:42 GMT] : [2857ef2b-d8a5-4da0-a42c-fb8449397a34] : msal.js.browser@2.32.0 : Verbose - getClientConfiguration called (index.1512a7b6.js, line 27) 
[Debug] [Tue, 29 Nov 2022 13:59:42 GMT] : [2857ef2b-d8a5-4da0-a42c-fb8449397a34] : msal.js.browser@2.32.0 : Verbose - getDiscoveredAuthority called (index.1512a7b6.js, line 27) 
[Debug] [Tue, 29 Nov 2022 13:59:42 GMT] : [2857ef2b-d8a5-4da0-a42c-fb8449397a34] : msal.js.browser@2.32.0 : Verbose - Creating discovered authority with configured authority (index.1512a7b6.js, line 27) 
[Debug] [Tue, 29 Nov 2022 13:59:42 GMT] : [2857ef2b-d8a5-4da0-a42c-fb8449397a34] : msal.js.browser@2.32.0 : Verbose - Attempting to get cloud discovery metadata in the config (index.1512a7b6.js, line 27) 
[Debug] [Tue, 29 Nov 2022 13:59:42 GMT] : [2857ef2b-d8a5-4da0-a42c-fb8449397a34] : msal.js.browser@2.32.0 : Verbose - Did not find cloud discovery metadata in the config... Attempting to get cloud discovery metadata from the cache. (index.1512a7b6.js, line 27) 
[Debug] [Tue, 29 Nov 2022 13:59:42 GMT] : [2857ef2b-d8a5-4da0-a42c-fb8449397a34] : msal.js.browser@2.32.0 : Verbose - Did not find cloud discovery metadata in the cache... Attempting to get cloud discovery metadata from the network. (index.1512a7b6.js, line 27) 
[Debug] [Tue, 29 Nov 2022 13:59:42 GMT] : [2857ef2b-d8a5-4da0-a42c-fb8449397a34] : msal.js.browser@2.32.0 : Verbose - Found cloud discovery metadata from the network. (index.1512a7b6.js, line 27) 
[Debug] [Tue, 29 Nov 2022 13:59:42 GMT] : [2857ef2b-d8a5-4da0-a42c-fb8449397a34] : msal.js.browser@2.32.0 : Verbose - Auth code client created (index.1512a7b6.js, line 27) 
[Info] [Tue, 29 Nov 2022 13:59:42 GMT] : @azure/msal-browser@2.32.0 : Info - Emitting event: msal:popupOpened (index.1512a7b6.js, line 27) 
[Debug] [Tue, 29 Nov 2022 13:59:42 GMT] : @azure/msal-browser@2.32.0 : Verbose - Emitting event to callback 5f709b9f-1856-4835-92c5-ca47147e52c4: msal:popupOpened (index.1512a7b6.js, line 27) 
[Debug] [Tue, 29 Nov 2022 13:59:42 GMT] : @azure/msal-browser@2.32.0 : Verbose - Emitting event to callback 40465fae-e6c9-48f0-b966-a92ea22ecf10: msal:popupOpened (index.1512a7b6.js, line 27) 
[Debug] [Tue, 29 Nov 2022 13:59:42 GMT] : [2857ef2b-d8a5-4da0-a42c-fb8449397a34] : msal.js.browser@2.32.0 : Verbose - PopupHandler.monitorPopupForHash - polling started (index.1512a7b6.js, line 27) 
[Debug] [Tue, 29 Nov 2022 13:59:50 GMT] : [2857ef2b-d8a5-4da0-a42c-fb8449397a34] : msal.js.browser@2.32.0 : Verbose - PopupHandler.monitorPopupForHash - popup window is on same origin as caller (index.1512a7b6.js, line 27) 
[Debug] [Tue, 29 Nov 2022 13:59:51 GMT] : [2857ef2b-d8a5-4da0-a42c-fb8449397a34] : msal.js.browser@2.32.0 : Verbose - PopupHandler.monitorPopupForHash - popup window is on same origin as caller (index.1512a7b6.js, line 27) 
[Debug] [Tue, 29 Nov 2022 13:59:52 GMT] : [2857ef2b-d8a5-4da0-a42c-fb8449397a34] : msal.js.browser@2.32.0 : Verbose - PopupHandler.monitorPopupForHash - popup window is on same origin as caller (index.1512a7b6.js, line 27) 
[Debug] [Tue, 29 Nov 2022 13:59:53 GMT] : [2857ef2b-d8a5-4da0-a42c-fb8449397a34] : msal.js.browser@2.32.0 : Verbose - PopupHandler.monitorPopupForHash - popup window is on same origin as caller (index.1512a7b6.js, line 27) 
[Debug] [Tue, 29 Nov 2022 13:59:54 GMT] : [2857ef2b-d8a5-4da0-a42c-fb8449397a34] : msal.js.browser@2.32.0 : Verbose - PopupHandler.monitorPopupForHash - popup window is on same origin as caller (index.1512a7b6.js, line 27)

**Comment by bmahall** [comment]
@blackadi From the logs, the popup is opened successfully (note the event msal:popupOpened) . Can you elaborate on whether you are actually not able to see the popup, or there is some other error message?
You can enable verbose logs to track further and share those. There might be some additional support steps missing for mobile platform, but please ensure the popup is not blocked on the specific environment you are testing it in. Thanks!
