### ISSUE TITLE
Customize code_challenge and code_challenge_method 

### ISSUE THREAD

**Issue by khalifaelbanan** [AzureAD/microsoft-authentication-library-for-js#5427]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.31.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

Greetings, 
Is there a way to pass my own code_challenge and code_challenge_method for PKCE flow with msal/browser ? if not, how can I achieve that ?

### MSAL Configuration

```javascript
publicClientApp = new PublicClientApplication({
      auth: {
        clientId: azureConfig.clientId,
        authority: azureConfig.authority,
        redirectUri: azureConfig.redirectUrl,
      },
      cache: {
        cacheLocation: 'sessionStorage',
        storeAuthStateInCookie: false,
      },
    });
```

### Relevant Code Snippets

```javascript
await publicClientApp.loginRedirect({
          scopes: ['openid'],
          prompt: 'select_account',
          code_challenge: 'code_challenge',
          code_challenge_method: 'S256',
        });
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by derisen** [comment]
@khalifaelbanan msal-browser abstracts away the PKCE process, so this is not possible with msal-browser. May I ask why you need this?

**Comment by khalifaelbanan** [comment]
Thanks for your answer !  
In general I need to generate the code on the Front-End side (using a specific code challenge) and pass it to the backend who'll be in charge to generate the jwt token based on this code (and using the appropriate code verifier).

**Comment by hectormmg** [comment]
@khalifaelbanan are you re-using the PKCE codes for a different purpose? The way MSAL Browser works you won't be able to acquire a token on the backend anyway.
