### ISSUE TITLE
How to configure msalv2 js library to renew token on ExpiresOn instead of extExpiresOn?

### ISSUE THREAD

**Issue by Employee87** [AzureAD/microsoft-authentication-library-for-js#5441]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.32.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Confidential

### Description

I'm trying to use msalv2 js library to do SSO authentication. It mostly works but I find an issue with token expiring and how to renew it.

I am calling the `aquireTokenRedirect` function to get the new token and auto renew it but I see that it keeps returning the same token. I try to auto renew it when my server side code detects that the token is expired. It uses a msal jwt library to check.

My guess as to what is happening is, my app is sending the id token to the server (I use that instead of access token), and the server decodes it and sees the exp value, which is the `ExpiresOn` value from the msal js response.

When this time has expired, it will return a 401 error which is fine. However then I try to renew it on the client side, but find it gives me back the same token value...

I check the msal response from earlier and notice there is a `extExpiresOn` value which is a little later in time. So now i'm thinking the msal library only renews on this time.

So the question is, how can I configure msalv2 js library to renew on the `ExpiresOn` instead of the `extExpiresOn`?

Thanks

### MSAL Configuration

```javascript
const msalConfig = {
    auth: {
        // 'Application (client) ID' of app registration in Azure portal - this value is a GUID
        clientId: "my key",
        // Full directory URL, in the form of https://login.microsoftonline.com/<tenant-id>
        authority: "my authority",
        // Full redirect URL, in form of http://localhost:3000
        redirectUri: window.location.origin,
    },
    cache: {
        cacheLocation: "sessionStorage", // This configures where your cache will be stored
        storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
    },
    system: {
        loggerOptions: {
            loggerCallback: (level, message, containsPii) => {
                if (containsPii) {
                    return;
                }
                switch (level) {
                    case msal.LogLevel.Error:
                        console.error(message);
                        return;
                    case msal.LogLevel.Info:
                        console.info(message);
                        return;
                    case msal.LogLevel.Verbose:
                        console.debug(message);
                        return;
                    case msal.LogLevel.Warning:
                        console.warn(message);
                        return;
                }
            }
        }
    }
};
```

### Relevant Code Snippets

```javascript
function getTokenRedirect(request) {
        /**
         * See here for more info on account retrieval: 
         * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/docs/Accounts.md
         */
        request.account = myMSALObj.getAccountByUsername(username);
    
        return myMSALObj.acquireTokenSilent(request)
            .catch(error => {
                console.warn("silent token acquisition fails. acquiring token using redirect");
                if (error instanceof msal.InteractionRequiredAuthError) {
                    // fallback to interaction when silent call fails
                    return myMSALObj.acquireTokenRedirect(request);
                } else {
                    console.warn(error);
                }
            });
    }
```
```


### Reproduction Steps

Open page when token expired

### Expected Behavior

It renews when expired on ExpiresOn value

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari

### Regression

_No response_

### Source

Internal (Microsoft)

**Comment by bmahall** [comment]
@Employee87 Thanks for sharing detailed information on the issue. 
Couple of things, for SSO:-
It is recommended to leverage the [login_hint optional ID token claim](https://docs.microsoft.com/azure/active-directory/develop/active-directory-optional-claims#v10-and-v20-optional-claims-set) (provided to ssoSilent as loginHint), as it is the most reliable account hint of silent (and interactive) requests.
Please refer to [sso-silent](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/login-user.md#silent-login-with-ssosilent).

For further information on usage of login_hint, sid, please refer to [user-hint](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-js-sso#with-user-hint).

Secondly, can you please retry with forceRefresh:true :-
e.g-
await msalInstanse.acquireTokenSilent({
        scopes: {scopes here},
        forceRefresh: true;
        account,
})

Lastly, are you using B2c?

**Comment by TheInvoker** [comment]
What is B2c? But I don't think so.

I already use loginHint, and I tried forceRefresh and it works, but seems overkill since it refreshes the token even while it was still active? Actually upon further inspection, I think what is happening is when I sent the idtoken to the server, it is checking if the expiry date of the idtoken is expired or not.

If I compare the expiry date of the idtoken with the access token expiresOn and extExpiresOn, I find that

```idtoken expiry < access token expiresOn  < access token extExpiresOn```

And the msal js library is only going to renew the token when its close to or expired from the `access token expiresOn` date. 

I was hoping to find a way to make msal js just renew when the idtoken is expired instead. Is there a way for that?

**Comment by Tzahile** [comment]
This thread was closed without any proper answer.
I agree that `forceRefresh` solves the problem, but as @TheInvoker mentioned, it's overkill; I don't want to perform `forceRefresh` on every `acquireTokenSilent` if it's not needed.

I'd expect `acquireTokenSilent` to refresh token by itself, automatically, when token expiry is soon - but it doesn't happen
