### ISSUE TITLE
Problem with ElectronSystemBrowserTestApp deep linking with acquireTokenInteractive()

### ISSUE THREAD

**Issue by MrCodeWeaver** [AzureAD/microsoft-authentication-library-for-js#5442]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.14.2

### Wrapper Library

Not Applicable

### Wrapper Library Version

none

### Public or Confidential Client?

Public

### Description

I have the [ElectronSystemBrowserTestApp ](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/ElectronSystemBrowserTestApp) sample app setup and running, and can sign and the deeplink calls back to the app. The problem is how to improve the experience with the browser popup to allow the redirect. Since acquireTokenInteractive chooses a random port on localhost each time, the user will always have the browser popup, even if they check the box to allow to open link, because the next time it will be a different port on localhost.
![image](https://user-images.githubusercontent.com/12052413/205152581-88a67e3c-a309-4f82-baa9-2d86ab325ef0.png)

### MSAL Configuration

```javascript
{
    "authOptions":
        {
            "clientId": "Enter_the_Application_Id_Here",
            "authority": "https://login.microsoftonline.com/organizations"
        },
    "resourceApi":
    {
        "endpoint": "Enter_the_Graph_Endpoint_Here",
        "scopes": ["User.Read", "Mail.Read"]
    },
    "customProtocol":
    {
        "name": "msal{Enter_the_Application_Id_Here}"
    },
    "cache": {
        "cacheLocation": "./data/cache.json"
    }
}
```

### Relevant Code Snippets

```javascript
ElectronSystemBrowserTestApp: https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/ElectronSystemBrowserTestApp
```

### Reproduction Steps

1. Download the [ElectronSystemBrowserTestApp ](https://github.dev/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-node-samples/ElectronSystemBrowserTestApp/src/AuthProvider.ts) and configure the application in customConfig.js and enable deeplinking
2. Run the app and sign in > browser will open and after sign in is complete will try to deeplink back to the app, but browser will popup to allow to open this applicaiton.
3. The problem is the browser will popup every time, even if the users checks always allow, because acquireTokenInteractive uses a different port every time.

### Expected Behavior

Expected behavior would be some way to specify a port number or a way to have acquireTokenInteractive use a consistent URL so that the user would not always get the popup consent in browser for the deep link back to the electron app****

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer

### Source

External (Customer)

**Comment by derisen** [comment]
> Expected behavior would be some way to specify a port number or a way to have acquireTokenInteractive use a consistent URL so that the user would not always get the popup consent in browser for the deep link back to the electron app****

@MrCodeWeaver that (specifying a port number) seems like a reasonable request to me -@tnorling what do you think?

**Comment by tnorling** [comment]
We intentionally did not use a static port because you can't guarantee that the port is available on a given user's system. I supposed we could provide a "preferred port" mechanism by which we use a statically defined port if it's available, otherwise fallback to the existing "random" behavior. Would that be an acceptable solution @MrCodeWeaver ?

**Comment by MrCodeWeaver** [comment]
Yes, I think using a 'preferred port' if its available would be a workable solution

**Comment by derisen** [comment]
@MrCodeWeaver a loopback client interface for `acquireTokenInteractive` API has been added to msal-node, which will be available in the next release ([see](5578)). This should mitigate the issue you are having. Please have a look at the [ElectronSystemBrowserTestApp](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-node-samples/ElectronSystemBrowserTestApp/src/CustomLoopbackClient.ts) sample for a usage example. Let us know if you have more issues!
