### ISSUE TITLE
How to use msal in VSCode for web extension?

### ISSUE THREAD

**Issue by realDuang** [AzureAD/microsoft-authentication-library-for-js#5444]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.14.4

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

I'm now trying to migrate a VSCode extension to a **_VSCode for web_** extension which needs to get AAD token. And the login feature in VSCode extension runs well.

Cause the **_VSCode for web_** extension is run on web browser, so I first choose  `msal-browser`, it doesn't work.

![4b0beb67-2ee7-4e08-9866-341f26338e52](https://user-images.githubusercontent.com/17807197/205251057-6e915bbe-4dd7-42c0-b4a9-5ea198121cd0.jpg)

Then I choose `msal-node` package, but when I call getAuthCodeUrl, it shows I have untrusted_authority. That's weird because in VSCode extension we use the same API and it worked! Or it has a network problem in commiuncate with VSCode for web extension?

```
  ERR [Extension Host] [Fri, 02 Dec 2022 08:24:40 GMT] : @azure/msal-node@1.14.4 : Info - getAuthCodeUrl called
vscode-appc:/Users/longcheng/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:609
[Extension Host] [Fri, 02 Dec 2022 08:24:40 GMT] : @azure/msal-node@1.14.4 : Info - getAuthCodeUrl called
vscode-appc:/Users/longcheng/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87
  ERR [Extension Host] [Fri, 02 Dec 2022 08:24:40 GMT] : @azure/msal-node@1.14.4 : Verbose - initializeRequestScopes called
vscode-appc:/Users/longcheng/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:609
[Extension Host] [Fri, 02 Dec 2022 08:24:40 GMT] : @azure/msal-node@1.14.4 : Verbose - initializeRequestScopes called
vscode-appc:/Users/longcheng/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87
  ERR [Extension Host] [Fri, 02 Dec 2022 08:24:40 GMT] : [a903a039-b998-487e-a9fa-e0dcf64df253] : @azure/msal-node@1.14.4 : Verbose - buildOauthClientConfiguration called
vscode-appc:/Users/longcheng/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:609
[Extension Host] [Fri, 02 Dec 2022 08:24:40 GMT] : [a903a039-b998-487e-a9fa-e0dcf64df253] : @azure/msal-node@1.14.4 : Verbose - buildOauthClientConfiguration called
vscode-appc:/Users/longcheng/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87
  ERR [Extension Host] [Fri, 02 Dec 2022 08:24:40 GMT] : [a903a039-b998-487e-a9fa-e0dcf64df253] : @azure/msal-node@1.14.4 : Verbose - building oauth client configuration with the authority: https://login.windows-ppe.net/common/
vscode-appc:/Users/longcheng/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:609
[Extension Host] [Fri, 02 Dec 2022 08:24:40 GMT] : [a903a039-b998-487e-a9fa-e0dcf64df253] : @azure/msal-node@1.14.4 : Verbose - building oauth client configuration with the authority: https://login.windows-ppe.net/common/
vscode-appc:/Users/longcheng/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87
  ERR [Extension Host] [Fri, 02 Dec 2022 08:24:40 GMT] : [a903a039-b998-487e-a9fa-e0dcf64df253] : @azure/msal-node@1.14.4 : Verbose - createAuthority called
vscode-appc:/Users/longcheng/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:609
[Extension Host] [Fri, 02 Dec 2022 08:24:40 GMT] : [a903a039-b998-487e-a9fa-e0dcf64df253] : @azure/msal-node@1.14.4 : Verbose - createAuthority called
vscode-appc:/Users/longcheng/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87
  ERR [Extension Host] [Fri, 02 Dec 2022 08:24:40 GMT] : @azure/msal-node@1.14.4 : Verbose - Attempting to get cloud discovery metadata in the config
vscode-appc:/Users/longcheng/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:609
[Extension Host] [Fri, 02 Dec 2022 08:24:40 GMT] : @azure/msal-node@1.14.4 : Verbose - Attempting to get cloud discovery metadata in the config
vscode-appc:/Users/longcheng/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87
  ERR [Extension Host] [Fri, 02 Dec 2022 08:24:40 GMT] : @azure/msal-node@1.14.4 : Verbose - Did not find cloud discovery metadata in the config... Attempting to get cloud discovery metadata from the cache.
vscode-appc:/Users/longcheng/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:609
[Extension Host] [Fri, 02 Dec 2022 08:24:40 GMT] : @azure/msal-node@1.14.4 : Verbose - Did not find cloud discovery metadata in the config... Attempting to get cloud discovery metadata from the cache.
vscode-appc:/Users/longcheng/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87
  ERR [Extension Host] [Fri, 02 Dec 2022 08:24:40 GMT] : @azure/msal-node@1.14.4 : Verbose - Did not find cloud discovery metadata in the cache... Attempting to get cloud discovery metadata from the network.
vscode-appc:/Users/longcheng/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:609
[Extension Host] [Fri, 02 Dec 2022 08:24:40 GMT] : @azure/msal-node@1.14.4 : Verbose - Did not find cloud discovery metadata in the cache... Attempting to get cloud discovery metadata from the network.
vscode-appc:/Users/longcheng/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87
  ERR [Extension Host] [Fri, 02 Dec 2022 08:24:40 GMT] : @azure/msal-node@1.14.4 : Verbose - Did not find cloud discovery metadata from the network... Attempting to get cloud discovery metadata from hardcoded values.
vscode-appc:/Users/longcheng/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:609
[Extension Host] [Fri, 02 Dec 2022 08:24:40 GMT] : @azure/msal-node@1.14.4 : Verbose - Did not find cloud discovery metadata from the network... Attempting to get cloud discovery metadata from hardcoded values.
vscode-appc:/Users/longcheng/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87
  ERR [Extension Host] [Fri, 02 Dec 2022 08:24:40 GMT] : @azure/msal-node@1.14.4 : Verbose - Did not find cloud discovery metadata from hardcoded values... Metadata could not be obtained from config, cache, network or hardcoded value. Throwing Untrusted Authority Error.
vscode-appc:/Users/longcheng/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:609
[Extension Host] [Fri, 02 Dec 2022 08:24:40 GMT] : @azure/msal-node@1.14.4 : Verbose - Did not find cloud discovery metadata from hardcoded values... Metadata could not be obtained from config, cache, network or hardcoded value. Throwing Untrusted Authority Error.
vscode-appc:/Users/longcheng/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87
[Extension Host] {"errorCode":"endpoints_resolution_error","errorMessage":"Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter.","subError":"","name":"ClientAuthError"}
```

FYI, the error log is on above.

Do you have any experience on how to use MSAL in VSCode for web extension? Which package should I use?

### MSAL Configuration

```javascript
const MSAL_CONFIG: Configuration = {
  auth: {
    clientId: '448e8446-7f2d-4c49-927e-e8a6cc9dcac2',
    authority: 'https://login.windows-ppe.net/common/'
  },
  system: {
    loggerOptions: {
      loggerCallback(loglevel: LogLevel, message: string, containsPii: boolean) {
        console.error(message);
      },
      piiLoggingEnabled: false,
      logLevel: LogLevel.Verbose
    }
  }
};
```

### Relevant Code Snippets

```javascript
const authCodeUrlParameters = {
      scopes: ['https://analysis.windows-int.net/powerbi/api/user_impersonation'],
      redirectUri: `http://localhost:3000`
    };

    this.publicClientApp
      .getAuthCodeUrl(authCodeUrlParameters)
      .then((response) => {
        console.log(response);
      })
      .catch((error) => console.log(JSON.stringify(error)));
```

### Identity Provider

None

### Source

Internal (Microsoft)

**Comment by bmahall** [comment]
@realDuang Your msal config seems correct, I will create a work item to document usage of VSCode for Web Extension for msal. 
Are you using single tenant or multi-tenant application?

**Comment by hectormmg** [comment]
@realDuang whenever the `non_browser_environment` error comes up, that means MSAL can't access the `window` browser API. I'm assuming this is somehow caused by the VSCode for web environment acting as a sandbox of some sort.

I think `msal-node` is probably the best bet since we can probably work around the untrusted authority issues.

Please try adding `knownAuthorities` to your config as such:

```typescript
const MSAL_CONFIG: Configuration = {
  auth: {
    clientId: '448e8446-7f2d-4c49-927e-e8a6cc9dcac2',
    authority: 'https://login.windows-ppe.net/common/',
    knownAuthorities: ['https://login.windows-ppe.net/common/]
  },
  system: {
    loggerOptions: {
      loggerCallback(loglevel: LogLevel, message: string, containsPii: boolean) {
        console.error(message);
      },
      piiLoggingEnabled: false,
      logLevel: LogLevel.Verbose
    }
  }
};
Relevant 
```

Let us know if this helps.

**Comment by realDuang** [comment]
> @realDuang Your msal config seems correct, I will create a work item to document usage of VSCode for Web Extension for msal. Are you using single tenant or multi-tenant application?

I think it is a single tenant application, because vscode for web seems like not support multi-tenant.

**Comment by realDuang** [comment]
> @realDuang whenever the `non_browser_environment` error comes up, that means MSAL can't access the `window` browser API. I'm assuming this is somehow caused by the VSCode for web environment acting as a sandbox of some sort.
> 
> I think `msal-node` is probably the best bet since we can probably work around the untrusted authority issues.
> 
> Please try adding `knownAuthorities` to your config as such:
> 
> ```ts
> const MSAL_CONFIG: Configuration = {
>   auth: {
>     clientId: '448e8446-7f2d-4c49-927e-e8a6cc9dcac2',
>     authority: 'https://login.windows-ppe.net/common/',
>     knownAuthorities: ['https://login.windows-ppe.net/common/]
>   },
>   system: {
>     loggerOptions: {
>       loggerCallback(loglevel: LogLevel, message: string, containsPii: boolean) {
>         console.error(message);
>       },
>       piiLoggingEnabled: false,
>       logLevel: LogLevel.Verbose
>     }
>   }
> };
> Relevant 
> ```
> 
> Let us know if this helps.

Oh thanks for you help! It is success to work around the authorities check. But it still failed to run.

```
{"errorCode":"endpoints_resolution_error","errorMessage":"Error: could not resolve endpoints. Please check network and try again. Detail: ClientAuthError: openid_config_error: Could not retrieve endpoints. Check your authority and verify the .well-known/openid-configuration endpoint returns the required endpoints. Attempted to retrieve endpoints from: https://login.windows-ppe.net/common/v2.0/.well-known/openid-configuration","subError":"","name":"ClientAuthError"}
```

I have tried to open `https://login.windows-ppe.net/common/v2.0/.well-known/openid-configuration` url and it worked from my side. And it's weird that the error log says it is a network problem but I can't find any network request during the code run.

**Comment by hectormmg** [comment]
@realDuang I think the problem here is that since VSCode for Web runs on the browser, the Node HTTPS client that msal-node uses is somehow blocked.

**Comment by realDuang** [comment]
> 

Yeah I agree with you. So that's why I open this issue, and hope to find out a best practice in VSCode for Web azure login.

**Comment by hectormmg** [comment]
@realDuang I see that VSCode for web extensions have a few limitations. One of them is that all network calls have to be made through Fetch API. MSAL Node's default network client is an HTTP client that uses Node's native HTTPS module (not fetch). However, MSAL Node is designed to accept a custom-made network client that you can pass in through the configuration object.

Here's the [default network client](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/src/network/HttpClient.ts) for reference.

You can rewrite that client to use fetch and see if it works for you.

**Comment by realDuang** [comment]
@hectormmg Great solution! It works when I change the network client as customized fetch client! Thanks for your advice!



>

**Comment by realDuang** [comment]
Another point I hope to get an answer is that the current vscode.dev plug-in calls the msal-node library, and the webpage does not support node server routing jumps.
So all auth codes and client_info can only be displayed in the redirected vscode .dev, so that the extension can get the value through the url. Is this a safe practice?

**Comment by hectormmg** [comment]
@realDuang the auth code is always visible in the browser URL bar, it's taken into account by the protocol design. There are mechanisms such as PKCE that help make this secure, since the code_verifier and code_challenge need to match for the auth code to be accepted and traded for a token. Even if an attacker extracts the auth code, if PKCE is used it should be relatively safe.

**Comment by realDuang** [comment]
@hectormmg Thanks for your reply! realy helped a lot!

After I fix the network client problem, there seems have a CORS problem in getToken api. The api seems blocked the vscode.dev domain `*.vscode-cdn.net`. 

![35f311f5-ab0d-4db4-b4ed-00a2c33514e1](https://user-images.githubusercontent.com/17807197/208012448-0f6abb90-c360-49d1-95d3-36e41061b7d1.jpg)

Shouldn't this be an open api? If not, how could we add this into cors policy? I think the vscode.dev cdn domain can be trusted in azure login.

**Comment by hectormmg** [comment]
@realDuang please look at our [docs](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/916f926d8fd2d7776000b50256b169e27759e00a/lib/msal-browser/docs/errors.md#access-to-fetch-at-url-has-been-blocked-by-cors-policy) for more info on CORS
