### ISSUE TITLE
Short on documentation för the use case of using msal.js 2.+ and AD FS as Identity provider

### ISSUE THREAD

**Issue by SelfishLucho** [AzureAD/microsoft-authentication-library-for-js#5445]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

Not Applicable

### Public or Confidential Client?

Public

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js

### Description

Im finding tickets/PR ([#4301](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4301), [#1668](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/1668), [#99](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/99)) which gives an indication that msal.js 2.+ works not only with Azure AD but also with AD FS. Either with sample code or atleast mention about it.

**Comment by derisen** [comment]
@SelfishLucho sorry for late response, I hope you found the [ADFS doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/docs/ADFS.md#adfs-support) and [example](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/docs/authority.md#adfs) already

**Comment by SelfishLucho** [comment]
@derisen You were quick on answering, and yes I found the links you posted. Thank you!
