### ISSUE TITLE
Force Azure login MSAL for angular to remember user's credentials

### ISSUE THREAD

**Issue by relief12** [AzureAD/microsoft-authentication-library-for-js#5447]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

None

### Public or Confidential Client?

Confidential

### Description

I'm using Azure MSAL for angular V2 with an embedded browser using WPF. Every time the user closes the WPF window, they have to re-enter their azure credentials. What can I do to force Azure to remember the user's credentials? This is a private client/tenant and when the WPF window closes behaves as if we close the browser.

### Identity Provider

None

### Source

External (Customer)

**Comment by hectormmg** [comment]
@relief12 unfortunately MSAL doesn't have any control over the login UI, that is handled by the authorization service. This means there is no way to configure the behavior from MSAL.
