### ISSUE TITLE
loginPopup promise is never resolved

### ISSUE THREAD

**Issue by MaximBalaganskiy** [AzureAD/microsoft-authentication-library-for-js#545]
## I'm submitting a...
<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version 71
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

Library version: >=0.1.5, including latest 0.2.4

## Current behavior
The promise returned by `loginPopup` is never resolved on login

## Expected behavior
The promise returned by `loginPopup` is resolved on login

## Minimal reproduction of the problem with instructions
Clone `active-directory-b2c-javascript-msal-singlepageapp`, update `msal` link to `0.2.4`, add options `{ validateAuthority: false, isAngular: true }` so that there is no redirect

**Comment by zamzowd** [comment]
Don't set the option `isAngular: true` unless you're using the `msal-angular` package.  That repository is not an Angular application, just plain javascript without a framework.

Setting `isAngular` to `true` makes the library expect that the hash from the page reload will be handled outside of the msal library.  The `msal-angular` package handles it in `msal.service.ts`.

**Comment by MaximBalaganskiy** [comment]
Not setting this option makes the popup redirect to the redirectUrl and
Promise is not resolved as well.
