### ISSUE TITLE
Change logger library for passport-azure-ad

### ISSUE THREAD

**Issue by lays147** [AzureAD/microsoft-authentication-library-for-js#5455]
### Core Library

Passport Azure AD (passport-azure-ad)

### Wrapper Library

Not Applicable

### Public or Confidential Client?

Public

### Description

passport-azure-ad uses bunyan as logger library, and that library was last published **2 years ago**. I suggest that the library is changed to use winston or other modern logger library. And the user of this library should be able to extend the logger configs. 
Right now the library doesn't allow to set proper values, and messes with log indexing on Datadog.

### Source

External (Customer)

**Comment by hectormmg** [comment]
@lays147 given that `passport-azure-ad` itself is deprecated, we only intend to make changes required for critical security-related issues, but thanks for raising the issue.
