### ISSUE TITLE
useIsAuthenticated hook returning true when token is expired

### ISSUE THREAD

**Issue by kvargha** [AzureAD/microsoft-authentication-library-for-js#5456]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.32.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.5.0

### Public or Confidential Client?

Public

### Description

I'm using the useIsAuthenticated() hook to render specific components when a user is signed in with a valid session. When the token expires, useIsAuthenticated() returns true.

### Error Message

InteractionRequiredAuthError: interaction_required: AADSTS70044: The session has expired or is invalid due to sign-in frequency checks by conditional access.
Trace ID: c6c8ef47-fefa-4c22-a062-0c711089dc00
Correlation ID: b72a73fe-3359-44ca-b770-8eaab110d757

### MSAL Configuration

```javascript
{
  auth: {
    clientId: '',
    authority: '',
    redirectUri: window.location.origin
  },
  cache: {
    cacheLocation: 'localStorage',
    storeAuthStateInCookie: false 
  }
}
```

### Relevant Code Snippets

```javascript
import { useIsAuthenticated } from '@azure/msal-react'
const IsAuthenticated = useIsAuthenticated()

export default function MyComponent () {
  return (
     IsAuthenticated === true
       ? Valid Session
       : Invalid Session
  )
}
```

### Reproduction Steps

1. Wait for the token to expire
2. Log the return value of useIsAuthenticated()

### Expected Behavior

useIsAuthenticated() should be returning false when a session is invalid.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by hectormmg** [comment]
@kvargha thanks for raising the issue.

The `useIsAuthenticated` hook is designed to return true when there is a user account in the cache, meaning the user is "Authenticated" in your application. It doesn't reflect the state of validity of any of the related tokens, which determine whether or not the user is "Authorized".

If you want to determine if the user is authorized, please use the `useMsalAuthentication` hook or `MsalAuthenticationTemplate` instead. Thanks!

**Comment by kvargha** [comment]
Hi @hectormmg, I tried using the two suggestions you made with an expired session and this was what I was faced with:

- useMsalAuthentication: The return value for error was null. Shouldn't this return an error if a token is expired?
- MsalAuthenticationTemplate: It rendered its children, and not the error component.

Is this the expected behavior?

**Comment by jo-arroyo** [comment]
@kvargha Are you able to show your usage of the `useMsalAuthentication` hook or `MsalAuthenticationTemplate`?

Additionally, please take a look at our docs for [useMsalAuthentication](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/hooks.md#usemsalauthentication-hook) and [MsalAuthenticationTemplate](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/getting-started.md#protecting-components) if you haven't already.

**Comment by kvargha** [comment]
Hi @jo-arroyo,

Here is how I'm using `useMsalAuthentication`:

```
import { useMsalAuthentication } from '@azure/msal-react'

// These two are components for a Sign In and Sign Out button
import AzureSignIn from './Azure/AzureSignIn'
import AzureSignOut from './Azure/AzureSignOut'

export default function App () {
    const { error } = useMsalAuthentication()
    
    return (
        { error ? <AzureSignIn/> : <AzureSignOut/> }
    )
}
```

When I invoke `acquireTokenSilent`, it throws the error I indicated in my issue due to my expired session.

The documentation states "If an error occurs during login or token acquisition this property will contain information about the error". However, the return value from `useMsalAuthentication()` is null.

Essentially, I want to show a Sign In button if there aren't any users signed in or their session is expired, otherwise, render the Sign Out button.

**Comment by jo-arroyo** [comment]
@kvargha Please add an input parameter for `useMsalAuthentication`, per the docs [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/hooks.md#input-parameters).

**Comment by kvargha** [comment]
Hi @jo-arroyo,

Here is my updated code:

```
import React, { useEffect } from 'react'
import { useMsalAuthentication, useMsal } from '@azure/msal-react'
import { InteractionType, InteractionRequiredAuthError } from '@azure/msal-browser'

// These two are components for a Sign In and Sign Out button
import AzureSignIn from './AzureSignIn'
import AzureSignOut from './AzureSignOut'

export default function LoginToggle () {
  const { accounts } = useMsal()
  const request = {
    loginHint: accounts[0]?.username,
    scopes: ['myclientid/.default'],
    account: accounts[0]
  }
  const { login, error } = useMsalAuthentication(InteractionType.Silent, request)

  useEffect(() => {
    if (error instanceof InteractionRequiredAuthError) {
      login(InteractionType.Popup, request)
    }
  }, [error])

  return (
        <React.Fragment>
            { error ? <AzureSignIn/> : <AzureSignOut/> }
        </React.Fragment>
  )
}

```

I'm still facing the same issue, the value for error is null. I've also tried passing in an account identifier to `useMsalAuthentication` but it still didn't work.

**Comment by jo-arroyo** [comment]
@kvargha Are you able to provide Verbose logs?

**Comment by kvargha** [comment]
Here you go @jo-arroyo:

> [Wed, 14 Dec 2022 22:49:31 GMT] : @azure/msal-browser@2.26.0 : Verbose - getAllAccounts called
AuthConfig.js:22 [Wed, 14 Dec 2022 22:49:31 GMT] : @azure/msal-browser@2.26.0 : Verbose - getAllAccounts called
AuthConfig.js:22 [Wed, 14 Dec 2022 22:49:31 GMT] : @azure/msal-browser@2.26.0 : Verbose - Event callback registered with id: 016cef66-e0d5-4ef8-8229-a1de29a99048
AuthConfig.js:22 [Wed, 14 Dec 2022 22:49:31 GMT] : @azure/msal-react@1.4.2 : Verbose - useMsalAuthentication - Registered event callback with id: 016cef66-e0d5-4ef8-8229-a1de29a99048
AuthConfig.js:22 [Wed, 14 Dec 2022 22:49:31 GMT] : @azure/msal-browser@2.26.0 : Verbose - Event callback registered with id: 24c732c5-1b17-45d8-b4c0-ec765e3c05c5
AuthConfig.js:22 [Wed, 14 Dec 2022 22:49:31 GMT] : @azure/msal-react@1.4.2 : Verbose - MsalProvider - Registered event callback with id: 24c732c5-1b17-45d8-b4c0-ec765e3c05c5
AuthConfig.js:22 [Wed, 14 Dec 2022 22:49:31 GMT] : @azure/msal-browser@2.26.0 : Verbose - Emitting event to callback 016cef66-e0d5-4ef8-8229-a1de29a99048: msal:initializeStart
AuthConfig.js:22 [Wed, 14 Dec 2022 22:49:31 GMT] : @azure/msal-browser@2.26.0 : Verbose - Emitting event to callback 24c732c5-1b17-45d8-b4c0-ec765e3c05c5: msal:initializeStart
AuthConfig.js:22 [Wed, 14 Dec 2022 22:49:31 GMT] : @azure/msal-browser@2.26.0 : Verbose - getAllAccounts called
AuthConfig.js:22 [Wed, 14 Dec 2022 22:49:31 GMT] : @azure/msal-browser@2.26.0 : Verbose - Emitting event to callback 016cef66-e0d5-4ef8-8229-a1de29a99048: msal:initializeEnd
AuthConfig.js:22 [Wed, 14 Dec 2022 22:49:31 GMT] : @azure/msal-browser@2.26.0 : Verbose - Emitting event to callback 24c732c5-1b17-45d8-b4c0-ec765e3c05c5: msal:initializeEnd
AuthConfig.js:22 [Wed, 14 Dec 2022 22:49:31 GMT] : @azure/msal-browser@2.26.0 : Verbose - getAllAccounts called
AuthConfig.js:22 [Wed, 14 Dec 2022 22:49:31 GMT] : @azure/msal-browser@2.26.0 : Verbose - handleRedirectPromise called
AuthConfig.js:22 [Wed, 14 Dec 2022 22:49:31 GMT] : @azure/msal-browser@2.26.0 : Verbose - getAllAccounts called
AuthConfig.js:22 [Wed, 14 Dec 2022 22:49:31 GMT] : @azure/msal-browser@2.26.0 : Verbose - Emitting event to callback 016cef66-e0d5-4ef8-8229-a1de29a99048: msal:handleRedirectStart
AuthConfig.js:22 [Wed, 14 Dec 2022 22:49:31 GMT] : @azure/msal-browser@2.26.0 : Verbose - Emitting event to callback 24c732c5-1b17-45d8-b4c0-ec765e3c05c5: msal:handleRedirectStart
AuthConfig.js:22 [Wed, 14 Dec 2022 22:49:31 GMT] : @azure/msal-browser@2.26.0 : Verbose - getAllAccounts called
AuthConfig.js:22 [Wed, 14 Dec 2022 22:49:31 GMT] : @azure/msal-browser@2.26.0 : Verbose - handleRedirectPromise has been called for the first time, storing the promise
AuthConfig.js:22 [Wed, 14 Dec 2022 22:49:31 GMT] : [ca1beada-803f-4271-9155-9cf1612c5b0d] : msal.js.browser@2.26.0 : Verbose - initializeServerTelemetryManager called
AuthConfig.js:22 [Wed, 14 Dec 2022 22:49:31 GMT] : @azure/msal-browser@2.26.0 : Verbose - Emitting event to callback 016cef66-e0d5-4ef8-8229-a1de29a99048: msal:handleRedirectEnd
AuthConfig.js:22 [Wed, 14 Dec 2022 22:49:31 GMT] : @azure/msal-browser@2.26.0 : Verbose - Emitting event to callback 24c732c5-1b17-45d8-b4c0-ec765e3c05c5: msal:handleRedirectEnd
AuthConfig.js:22 [Wed, 14 Dec 2022 22:49:31 GMT] : @azure/msal-browser@2.26.0 : Verbose - getAllAccounts called
AuthConfig.js:22 [Wed, 14 Dec 2022 22:49:31 GMT] : @azure/msal-browser@2.26.0 : Verbose - getAllAccounts called
AuthConfig.js:22 [Wed, 14 Dec 2022 22:49:31 GMT] : @azure/msal-browser@2.26.0 : Verbose - getAllAccounts called

**Comment by tnorling** [comment]
@kvargha Are these the complete logs? I'd expect to see more at the end, could you set the log level to Trace please? Additionally, I don't think conditionally rendering your sign in button based on the error property is the right approach. The hook will only attempt to acquire a token automatically once (on one of its first renders), any subsequent renders will not re-attempt. 

There are 3 states you should be aware of and handle:

1. `error === null` and `result !== null` - Means a user is signed in and has a valid access token for whichever resource you requested
2. `error !== null` and `result === null` - Means token acquisition was attempted and an error occurred (you should have logic in place to handle this error)
3. Both `error` and `result` are `null` - Means either token acquisition hasn't happened yet or is currently in progress (this is essentially neither signed in nor out)

Another thing to keep in mind is that we generally discourage what you're trying to do. To truly achieve conditional rendering based on the validity of the token you would need to call acquireTokenSilent on every render which gets very expensive. Our general recommended best practice is to call acquireTokenSilent, on demand, when you need an access token for a resource and if it throws to handle it, either by invoking interaction or, if you don't want to extend the session, sign the user out.

**Comment by kvargha** [comment]
Hi @tnorling,

Thank you for the explanation. 

Is there a way to sign out a user without using a popup or redirect? I don't want to show the user the AzureAD signout page when their session is expired or automatically redirect them to the sign-in page, I'd prefer to prompt them to sign in again by rendering the sign-in button. If not, I can achieve this by using a hook tied to a failed acquireTokenSilent invocation when making calls to a protected resource.

Here are the logs when the log level is set to Trace:

> [Tue, 20 Dec 2022 20:29:47 GMT] : @azure/msal-browser@2.32.1 : Verbose - BrowserCrypto: modern crypto interface available
AuthConfig.js:28 [Tue, 20 Dec 2022 20:29:47 GMT] : @azure/msal-browser@2.32.1 : Verbose - BrowserCrypto: modern crypto interface available
AuthConfig.js:28 [Tue, 20 Dec 2022 20:29:47 GMT] : @azure/msal-browser@2.32.1 : Verbose - getAllAccounts called
AuthConfig.js:28 [Tue, 20 Dec 2022 20:29:47 GMT] : @azure/msal-browser@2.32.1 : Verbose - getAllAccounts called
AuthConfig.js:28 [Tue, 20 Dec 2022 20:29:47 GMT] : @azure/msal-browser@2.32.1 : Verbose - Event callback registered with id: c2e7f98a-b87b-4c41-ad49-bc3ab2115a9c
AuthConfig.js:28 [Tue, 20 Dec 2022 20:29:47 GMT] : @azure/msal-react@1.5.1 : Verbose - useMsalAuthentication - Registered event callback with id: c2e7f98a-b87b-4c41-ad49-bc3ab2115a9c
AuthConfig.js:28 [Tue, 20 Dec 2022 20:29:47 GMT] : @azure/msal-browser@2.32.1 : Verbose - Event callback registered with id: 2ff6b585-00c3-4a38-adb5-19191824006f
AuthConfig.js:28 [Tue, 20 Dec 2022 20:29:47 GMT] : @azure/msal-react@1.5.1 : Verbose - MsalProvider - Registered event callback with id: 2ff6b585-00c3-4a38-adb5-19191824006f
AuthConfig.js:25 [Tue, 20 Dec 2022 20:29:47 GMT] : @azure/msal-browser@2.32.1 : Info - Emitting event: msal:initializeStart
AuthConfig.js:28 [Tue, 20 Dec 2022 20:29:47 GMT] : @azure/msal-browser@2.32.1 : Verbose - Emitting event to callback c2e7f98a-b87b-4c41-ad49-bc3ab2115a9c: msal:initializeStart
AuthConfig.js:28 [Tue, 20 Dec 2022 20:29:47 GMT] : @azure/msal-browser@2.32.1 : Verbose - Emitting event to callback 2ff6b585-00c3-4a38-adb5-19191824006f: msal:initializeStart
AuthConfig.js:28 [Tue, 20 Dec 2022 20:29:47 GMT] : @azure/msal-browser@2.32.1 : Verbose - getAllAccounts called
AuthConfig.js:25 [Tue, 20 Dec 2022 20:29:47 GMT] : @azure/msal-browser@2.32.1 : Info - Emitting event: msal:initializeEnd
AuthConfig.js:28 [Tue, 20 Dec 2022 20:29:47 GMT] : @azure/msal-browser@2.32.1 : Verbose - Emitting event to callback c2e7f98a-b87b-4c41-ad49-bc3ab2115a9c: msal:initializeEnd
AuthConfig.js:28 [Tue, 20 Dec 2022 20:29:47 GMT] : @azure/msal-browser@2.32.1 : Verbose - Emitting event to callback 2ff6b585-00c3-4a38-adb5-19191824006f: msal:initializeEnd
AuthConfig.js:28 [Tue, 20 Dec 2022 20:29:47 GMT] : @azure/msal-browser@2.32.1 : Verbose - getAllAccounts called
AuthConfig.js:25 [Tue, 20 Dec 2022 20:29:47 GMT] : @azure/msal-react@1.5.1 : Info - useAccount - Updating account
AuthConfig.js:28 [Tue, 20 Dec 2022 20:29:47 GMT] : @azure/msal-browser@2.32.1 : Verbose - handleRedirectPromise called
AuthConfig.js:28 [Tue, 20 Dec 2022 20:29:47 GMT] : @azure/msal-browser@2.32.1 : Verbose - getAllAccounts called
AuthConfig.js:25 [Tue, 20 Dec 2022 20:29:47 GMT] : @azure/msal-browser@2.32.1 : Info - Emitting event: msal:handleRedirectStart
AuthConfig.js:28 [Tue, 20 Dec 2022 20:29:47 GMT] : @azure/msal-browser@2.32.1 : Verbose - Emitting event to callback c2e7f98a-b87b-4c41-ad49-bc3ab2115a9c: msal:handleRedirectStart
AuthConfig.js:28 [Tue, 20 Dec 2022 20:29:47 GMT] : @azure/msal-browser@2.32.1 : Verbose - Emitting event to callback 2ff6b585-00c3-4a38-adb5-19191824006f: msal:handleRedirectStart
AuthConfig.js:25 [Tue, 20 Dec 2022 20:29:47 GMT] : @azure/msal-react@1.5.1 : Info - MsalProvider - msal:handleRedirectStart results in setting inProgress from startup to handleRedirect
AuthConfig.js:28 [Tue, 20 Dec 2022 20:29:47 GMT] : @azure/msal-browser@2.32.1 : Verbose - getAllAccounts called
AuthConfig.js:28 [Tue, 20 Dec 2022 20:29:47 GMT] : @azure/msal-browser@2.32.1 : Verbose - handleRedirectPromise has been called for the first time, storing the promise
AuthConfig.js:28 [Tue, 20 Dec 2022 20:29:47 GMT] : [0b578c53-ea0a-40be-ad3a-84ab3b758c24] : msal.js.browser@2.32.1 : Verbose - initializeServerTelemetryManager called
AuthConfig.js:25 [Tue, 20 Dec 2022 20:29:47 GMT] : [0b578c53-ea0a-40be-ad3a-84ab3b758c24] : msal.js.browser@2.32.1 : Info - handleRedirectPromise called but there is no interaction in progress, returning null.
AuthConfig.js:25 [Tue, 20 Dec 2022 20:29:47 GMT] : @azure/msal-browser@2.32.1 : Info - Emitting event: msal:handleRedirectEnd
AuthConfig.js:28 [Tue, 20 Dec 2022 20:29:47 GMT] : @azure/msal-browser@2.32.1 : Verbose - Emitting event to callback c2e7f98a-b87b-4c41-ad49-bc3ab2115a9c: msal:handleRedirectEnd
AuthConfig.js:28 [Tue, 20 Dec 2022 20:29:47 GMT] : @azure/msal-browser@2.32.1 : Verbose - Emitting event to callback 2ff6b585-00c3-4a38-adb5-19191824006f: msal:handleRedirectEnd
AuthConfig.js:25 [Tue, 20 Dec 2022 20:29:47 GMT] : @azure/msal-react@1.5.1 : Info - MsalProvider - msal:handleRedirectEnd results in setting inProgress from handleRedirect to none
AuthConfig.js:28 [Tue, 20 Dec 2022 20:29:47 GMT] : @azure/msal-browser@2.32.1 : Verbose - getAllAccounts called
AuthConfig.js:28 [Tue, 20 Dec 2022 20:29:47 GMT] : @azure/msal-browser@2.32.1 : Verbose - getAllAccounts called
AuthConfig.js:25 [Tue, 20 Dec 2022 20:29:47 GMT] : @azure/msal-react@1.5.1 : Info - useAccount - Updating account
AuthConfig.js:28 [Tue, 20 Dec 2022 20:29:47 GMT] : @azure/msal-browser@2.32.1 : Verbose - getAllAccounts called
AuthConfig.js:28 [Tue, 20 Dec 2022 20:29:47 GMT] : @azure/msal-browser@2.32.1 : Verbose - getAllAccounts called
AuthConfig.js:25 [Tue, 20 Dec 2022 20:29:47 GMT] : @azure/msal-react@1.5.1 : Info - useAccount - Updating account

**Comment by tnorling** [comment]
>Is there a way to sign out a user without using a popup or redirect?

Yes, you can pass a callback to the `onRedirectNavigate` parameter in the logout request. This callback will be executed after the MSAL cache is cleared but before the redirect to the signout page occurs. If the callback you provide returns `false` the redirect to the signout page will be skipped. You can use this to either redirect to your own internal "you have been signed out page" or to update React state to cause your button to render. Just note that skipping the server signout means the user's session may still remain active on the server meaning they can sign back in to your app without providing credentials. More details on skipping the server signout [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md#skipping-the-server-sign-out)

**Comment by kvargha** [comment]
Thank you @tnorling! This is exactly what I needed. I'll be closing the issue now.
