### ISSUE TITLE
SCP required

### ISSUE THREAD

**Issue by lokkwanfoo** [AzureAD/microsoft-authentication-library-for-js#546]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [X] Chrome version 71.0.3578.98
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

Library version: 0.2.3

## Current behavior
I am using [Office-js](https://github.com/OfficeDev/Office-Add-in-NodeJS-SSO) to SSO. This application isn't supported in the Word Client, only Word Online so I figured I would use MSAL for a login in the Word Client. I can successfully get an ID token from MSAL. From the front-end, I give the ID token to my API that checks the JWT. In the JWT of Office-js, there is a variable called 'scp', but this variable is not present in the JWT of MSAL. Because I use the Office-SSO application, the API checks the JWT if there's an 'scp' present. It's not present so it gives me a 401 error.

## Expected behavior
I'd like to ask if there's a way to add the scp variable in the application_config when requesting an ID token with MSAL.

**Comment by sameerag** [comment]
@lokkwanfoo We support 'scp' when the request contains scopes as per the OAuth Spec: https://tools.ietf.org/id/draft-ietf-oauth-token-exchange-09.html#rfc.section.4.2.

Usual guidance in our sample is that we have two access tokens: One for the user to access the SPA (which may not have scopes) and another to access the resource API (eg. Microsoft Graph). Usually the token associated with the API access does have 'scp'. I think in this case you may be using the wrong access token to access the resource API.

Can you please send me the tokens you are storing in your cache for your app? Or best would be some sample code that I can execute at my end to see what tokens are issued to your app from the MSAL JS.

**Comment by navyasric** [comment]
@lokkwanfoo  Please note that scp (scopes) are not returned in id_tokens should be used for authentication and since they are meant to represent a user's authentication, they contain claims about the user's info. 
It is a best practice to request access tokens when you need to make authorized call to an API and the API should validate the access token. To get the scp in the token, please request an access token for the API. Closing this issue.

**Comment by llakhani** [comment]
> @lokkwanfoo Please note that scp (scopes) are not returned in id_tokens should be used for authentication and since they are meant to represent a user's authentication, they contain claims about the user's info.
> It is a best practice to request access tokens when you need to make authorized call to an API and the API should validate the access token. To get the scp in the token, please request an access token for the API. Closing this issue.

I have already auto generated token using msal , I received in loginSuccess event also. But that doesn't have scp.. So how can I get that in token? I want to have scope for mail.send .
