### ISSUE TITLE
Allow specifying loopback interface to listen on in aquireTokenInteractive method of PublicClientApplication class

### ISSUE THREAD

**Issue by pratikfuse** [AzureAD/microsoft-authentication-library-for-js#5466]
### Core Library

MSAL Node (@azure/msal-node)

### Wrapper Library

Not Applicable

### Public or Confidential Client?

Public

### Description

I have an electron application for windows that is using aquireTokenInteractive to login the user and fetch access token.

The problem is, this method starts a node server on a random port and all interfaces which forces windows to show a firewall prompt to the user.

Windows won't show the prompt if it's only listening on localhost which is how the authentication process works currently. 

Solution: Allow to define the interface for the server to listen for incoming requests.

### Source

External (Customer)

**Comment by hectormmg** [comment]
@tnorling I think this issue and #5442 can be discussed in tandem. Any thoughts on configurability of the server address here? I'm assuming the random port was an intentional design choice?

**Comment by tnorling** [comment]
@hectormmg Yes - these are similar but different so let's leave both open for now. @pratikfuse I've created an internal work item to track these and we'll provide an update here when we have committed to it.

**Comment by pratikfuse** [comment]
Sure, thank you for your input @hectormmg and @tnorling

**Comment by derisen** [comment]
@pratikfuse a loopback client interface for `acquireTokenInteractive` API has been added to msal-node, which will be available in the next release ([see](5578)). This should help mitigating the issue you are having. Please have a look at the [ElectronSystemBrowserTestApp](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-node-samples/ElectronSystemBrowserTestApp/src/CustomLoopbackClient.ts) sample for a usage example. Closing, but let us know if you have more questions or issues.
