### ISSUE TITLE
After trying to log in, login pop-up not closing and inside that pop-up window application is rendering

### ISSUE THREAD

**Issue by diamant-isufi-sveasolar** [AzureAD/microsoft-authentication-library-for-js#5477]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.32.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.6

### Public or Confidential Client?

Public

### Description

The issue is intermittent.
In login pop-up window the user typed valid credentials to log in his Microsoft account.
In most cases the user will successfully be logged in and pop-up will close.

However, sometimes login pop-up doesn't close and inside that pop-up window the user can use the same application.
I noticed that app is also running in the parent app window but user is not logged in.

I have noticed that logging out from your MS account in the browser, makes the popup require the email again and it works. IF there isn't a fix for this, is there a way I can always ask for the credentials even though I am signed in in the browser?

When this happens, the URL contains a hash **#code=0.AXQABc3mS.**

### MSAL Configuration

```javascript
export const msalConfig: Configuration = {
  auth: {
    clientId: process.env.REACT_APP_AZURE_CLIENT_ID,
    redirectUri: process.env.REACT_APP_AZURE_REDIRECT_URI,
    postLogoutRedirectUri: process.env.REACT_APP_AZURE_POSTLOGOUT_REDIRECT_URI,
  },
  cache: {
    cacheLocation: "localStorage",
    storeAuthStateInCookie: isIE || isEdge || isFirefox,
  },
  system: {
    asyncPopups: true,
    allowRedirectInIframe: true, // Needed for Front-channel logout
    loggerOptions: {
      loggerCallback: (level, message, containsPii) => {
        if (containsPii) {
          return;
        }
        switch (level) {
          case LogLevel.Error:
            console.error(message);
            return;
          case LogLevel.Info:
            console.info(message);
            return;
          case LogLevel.Verbose:
            console.debug(message);
            return;
          case LogLevel.Warning:
            console.warn(message);
            return;
          default:
            return;
        }
      },
    },
  },
};
```

### Relevant Code Snippets

```javascript
<MsalAuthenticationTemplate
        interactionType={InteractionType.Popup}
        authenticationRequest={authRequest}
        errorComponent={ErrorComponent}
        loadingComponent={LoadingComponent}
 />
```

### Reproduction Steps

User clicks to log into application with his Microsoft account.
Pop-up window shows up and user enters valid credentials to sign in with his MS account.
The pop-up does not close and inside that pop-up window application is rendering.

### Expected Behavior

After giving valid credentials the login pop-up window is **always** closing and user is logged into application.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox

### Source

Internal (Microsoft)

**Comment by diamant-isufi-sveasolar** [comment]
https://user-images.githubusercontent.com/105778530/206939863-26310509-bd11-4e38-9b60-2747bedf97a9.mp4

**Comment by diamant-isufi-sveasolar** [comment]
I have noticed that this is added when the popup fails to close

<img width="147" alt="image" src="https://user-images.githubusercontent.com/105778530/206955130-3686b1f2-633b-4c27-8ac7-fdb07e6a15fa.png">

**Comment by jo-arroyo** [comment]
@diamant-isufi-sveasolar The video you attached does not appear to include the hash in the popup window. Can you explain/show where you are seeing it?

Additionally, have you tried increasing the frequency with which MSAL checks the hash by reducing the pollIntervalMilliseconds [system configuration option](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/configuration.md#system-config-options)? You can try 20 or 15 ms.

**Comment by diamant-isufi-sveasolar** [comment]
@jo-arroyo I have screen recorded it, and it displays for a very short period of time before opening the app inside the popup.  About the pollIntervalMilliseconds, you say increasing but the default value is 30. Should I try and decrease it?

**Comment by diamant-isufi-sveasolar** [comment]
Anyone has a suggestion?

**Comment by hectormmg** [comment]
@diamant-isufi-sveasolar the value of `pollIntervalMilliseconds` is the time between polls, so when you decrease the value you are effectively "increasing" the polling frequency. The suggestion would be to try lower values such as 20 or 15 ms so MSAL waits less between polls and the probability of the hash being cleared before MSAL checks it is lower.

**Comment by diamant-isufi-sveasolar** [comment]
@hectormmg I will add that and will comment here if solved. Thing is the issue is **intermittent**, so I would appreciate leaving this issue opened until I try to reproduce it again with the added pollIntervalMilliseconds. Thanks!

**Comment by tnorling** [comment]
> I have screen recorded it, and it displays for a very short period of time before opening the app inside the popup.

This is the issue. It should not disappear. The page you use as your redirectUri is removing the hash (probably your router). To fix this you need to ensure that your router (or anything else) is not manipulating the url in any way. The best way to accomplish this is to use a static blank page as your redirectUri and do not include it in your routing logic

**Comment by diamant-isufi-sveasolar** [comment]
@tnorling but most of the times this will work, and couple of times it fails.. Why would it work in some of the cases, and the same routing logic taking place?

**Comment by tnorling** [comment]
Because this is a race condition. When it fails it means whatever is removing the hash won the race. When it succeeds it means MSAL.js won the race. By ensuring that your router is not acting upon the redirectUri page you eliminate the race and ensure that MSAL.js always has access to the hash.

**Comment by diamant-isufi-sveasolar** [comment]
@tnorling It is worth saying that this never happens locally, only when deployed..Now I need the router logic after it's finished cause that is the thing that redirects the user to the Private routes.

**Comment by tnorling** [comment]
@diamant-isufi-sveasolar Do you need anything else from us at this point or have you figured it out?

**Comment by diamant-isufi-sveasolar** [comment]
@tnorling 

1. It is worth noting that this does not happen when I run the app locally. Only when it is deployed..So if it was for the router it should've happened locally too.

2. It doesn't happen when using windows machine, but it does in mac.

**Comment by diamant-isufi-sveasolar** [comment]
I was able to fix my issue by setting pollIntervalMilliseconds to 0.

**Comment by maxidr** [comment]
I have the same issue, I tried with pollIntervalMilliseconds, and continue to happen sometimes

**Comment by djpritchett** [comment]
where is the `pollIntervalMilliseconds` setting? This issue is killing me. :)

**Comment by djpritchett** [comment]
> where is the `pollIntervalMilliseconds` setting? This issue is killing me. :)

never mind, found it. Thanks

**Comment by djpritchett** [comment]
Re**:ClientAuthError: User cancelled the flow**. fix
Django users that have recently upgraded: 
One of my co-workers(thanks @ryanhiebert) found our issue was `SECURE_CROSS_ORIGIN_OPENER_POLICY` not set, https://docs.djangoproject.com/en/4.1/releases/4.0/#requests-and-responses
Hope it saves someone an unexpected trip down a rabbit hole.

**Comment by DanWeissman** [comment]
I have been having the same issue on a React application that is not even using a router. There are two views - the logged out screen and the logged in dashboard, separated by the `@azure/msal-react` `AuthenticatedTemplate` and `UnauthenticatedTemplate`.

Setting the polling interval to 0 has also seemed to fix it at present.

**Comment by jpalo** [comment]
Same here, login window sits there for a good 15-30 secs or so, setting `pollIntervalMilliseconds` to `0` fixes the issue.

**Comment by zameb** [comment]
> Same here, login window sits there for a good 15-30 secs or so, setting `pollIntervalMilliseconds` to `0` fixes the issue.
I have the same issue, repeating every time I change branches. How do you specify this parameter?

Clearing the cache, rebuilding, deleting node_modules and dist, does not solve the issue. But, after some tries it start working by itself and does not fail until another branch is selected.

**Comment by steReply** [comment]
> > where is the `pollIntervalMilliseconds` setting? This issue is killing me. :)
> 
> never mind, found it. Thanks

I don't know where the setting is too. Thank you for sharing your knowledge.

**Comment by jpalo** [comment]
> > > where is the `pollIntervalMilliseconds` setting? This issue is killing me. :)
> > 
> > 
> > never mind, found it. Thanks
> 
> I don't know where the setting is too. Thank you for sharing your knowledge.

Please see this: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/configuration.md 

It is in the configuration object under 'system' configuration value.
