### ISSUE TITLE
state does not match the value I put in

### ISSUE THREAD

**Issue by blindfish3** [AzureAD/microsoft-authentication-library-for-js#548]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Other... Please describe: unexpected behaviour
</code></pre>

## Browser:
n/a

## Library version
0.2.4

## Current behavior
The state parameter I pass in to `msal.UserAgentApplication()` has a value prepended to it in the response.  This is done [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/ac32c459c7398be02fe3f50afbd7d38e19d8ef0e/lib/msal-core/src/AuthenticationRequestParameters.ts#L58); presumably with the intent of ensuring a unique state value.

From my perspective that's not desirable: I have a generic endpoint handling OAuth2 responses which checks the returned value matches what I've got stored in my app state.  This check fails because of the prepended value.  Whilst I understand the intent; I think it should be the responsibility of the implementer to ensure the state parameter is unique and not easily spoofed: I already add a nonce value to my state.  I don't need msal to do this for me.

## Expected behavior
For the state parameter I pass into the constructor to be the exact same value I see in the `state` param in the response URL.

## Minimal reproduction of the problem with instructions
- Pass a state param `myState` to `msal.UserAgentApplication()`
- see that the state param in the response is `valueFromUtilsCreateNewGuid|myState`

**Comment by blindfish3** [comment]
I'm just going to add that the [documentation for state](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL-basics#configuration-options) could be improved to reflect the purpose of this field: i.e. that - if properly formed - it can "[prevent cross-site request forgery attacks](https://tools.ietf.org/html/rfc6819#section-3.6)" *and* can also be used to provide additional data in the response.  Presumably the security aspect of this isn't reinforced in the documentation (and the field left as optional) because behind the scenes msal adds a random value to state.

I think obfuscating the security aspect of state does less experienced users a disservice - they've missed an opportunity to understand its dual purpose - whilst imposing unnecessary hurdles on the rest of us.

**Comment by sameerag** [comment]
@blindfish3 The issue is two fold here:
- I agree with you regarding the documentation and we will fill the gap here. @navyasric to follow up on this.
- When the 'myState' is set by the user, we also need to removed the GUID we add internally and return only 'myState' to the app developer as per the original requirement. We will make those changes  but please expect some delay on this, as we are making this a part of bunch of other enhancements that are in the pipeline.

**Comment by navyasric** [comment]
@blindfish3 Thank you for the feedback. We have updated the documentation of state and as mentioned above will plan to improve the expected behavior.

**Comment by pkanher617** [comment]
@blindfish3 We have updated the library to return the correct state in the PR referenced above, and it has been merged to dev. We plan on pushing a new preview release by the end of day today, and will be releasing our 1.0.0 version soon. Please feel free to pull our dev branch or use the npm preview release version 1.0.0-preview.5 and reopen this issue if there are any issues with the state parameter not working as expected.
