### ISSUE TITLE
The application is reloaded after signing in, the files are downloaded again

### ISSUE THREAD

**Issue by AntonEvseev** [AzureAD/microsoft-authentication-library-for-js#5483]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

msal.js.browser@2.30.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.4.5

### Public or Confidential Client?

Public

### Description

The main.js, vendor.js, etc are loaded twice after successful login. I run example from [samples](https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/tree/main/3-Authorization-II/2-call-api-b2c) . 
The same behavior when clicking the cancel button on the profile editing page.
![image](https://user-images.githubusercontent.com/16895663/207626490-146ebf7c-d2cf-45c2-9b39-5d070ea541c3.png)
Why is this happening?

### Error Message

-

### Msal Logs

[Wed, 14 Dec 2022 14:42:24 GMT] : [dee81dc5-9ca9-40cb-bd28-a7e1f107b82b] : msal.js.browser@2.30.0 : Verbose - RedirectHandler.initiateAuthRequest: Navigating window to navigate url
Navigated to https://fabrikamb2c.b2clogin.com/fabrikamb2c.onmicrosoft.com/b2c_1_susi_v2/oauth2/v2.0/authorize?client_id=9067c884-9fa6-414f-9aa4-a565b1cb46be&scope=openid%20profile%20offline_access&redirect_uri=http%3A%2F%2Flocalhost%3A4200%2Fauth&client-request-id=dee81dc5-9ca9-40cb-bd28-a7e1f107b82b&response_mode=fragment&response_type=code&x-client-SKU=msal.js.browser&x-client-VER=2.30.0&client_info=1&code_challenge=6ts4WOGu5R-Pots5iiP7syd_fWQMIYU6LXsYsmq9H4A&code_challenge_method=S256&nonce=02e7e5cc-5779-4bff-9b14-802104234d4e&state=eyJpZCI6IjBkMmU0OTk1LTM4NWItNDA5ZS1hMWYyLWIyY2E2OTAzNTA0MCIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicmVkaXJlY3QifX0%3D
fabrikamb2c.b2clogin.com/fabrikamb2c.onmicrosoft.com/b2c_1_susi_v2/oauth2/v2.0/authorize?client_id=9067c884-9fa6-414f-9aa4-a565b1cb46be&scope=openid%20profile%20offline_access&redirect_uri=http%3A%2F%2Flocalhost%3A4200%2Fauth&client-request-id=dee81dc5-9ca9-40cb-bd28-a7e1f107b82b&response_mode=fragment&response_type=code&x-client-SKU=msal.js.browser&x-client-VER=2.30.0&client_info=1&code_challenge=6ts4WOGu5R-Pots5iiP7syd_fWQMIYU6LXsYsmq9H4A&code_challenge_method=S256&nonce=02e7e5cc-5779-4bff-9b14-802104234d4e&state=eyJpZCI6IjBkMmU0OTk1LTM4NWItNDA5ZS1hMWYyLWIyY2E2OTAzNTA0MCIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicmVkaXJlY3QifX0%3D:1 [DOM] Input elements should have autocomplete attributes (suggested: "username"): (More info: https://goo.gl/9p2vKq) input#email
Navigated to http://localhost:4200/auth
​ [webpack-dev-server] Server started: Hot Module Replacement disabled, Live Reloading enabled, Progress disabled, Overlay enabled.
​ [Wed, 14 Dec 2022 14:42:36 GMT] : @azure/msal-browser@2.30.0 : Verbose - BrowserCrypto: modern crypto interface available
​ [Wed, 14 Dec 2022 14:42:36 GMT] : @azure/msal-browser@2.30.0 : Verbose - BrowserCrypto: modern crypto interface available
​ [Wed, 14 Dec 2022 14:42:36 GMT] : @azure/msal-browser@2.30.0 : Verbose - Event callback registered with id: 354e4f7e-2a4c-4e45-938c-a08fb83dca90
​ [Wed, 14 Dec 2022 14:42:36 GMT] : @azure/msal-browser@2.30.0 : Verbose - getAllAccounts called
​ [Wed, 14 Dec 2022 14:42:36 GMT] : @azure/msal-browser@2.30.0 : Verbose - Adding account storage listener.
​ Angular is running in development mode. Call enableProdMode() to enable production mode.
​ [Wed, 14 Dec 2022 14:42:36 GMT] : @azure/msal-angular@2.4.5 : Verbose - MsalRedirectComponent activated
​ [Wed, 14 Dec 2022 14:42:36 GMT] : @azure/msal-browser@2.30.0 : Info - Emitting event: msal:initializeStart
​ [Wed, 14 Dec 2022 14:42:36 GMT] : @azure/msal-browser@2.30.0 : Verbose - Emitting event to callback 354e4f7e-2a4c-4e45-938c-a08fb83dca90: msal:initializeStart
​ [Wed, 14 Dec 2022 14:42:36 GMT] : @azure/msal-browser@2.30.0 : Info - Emitting event: msal:initializeEnd
​ [Wed, 14 Dec 2022 14:42:36 GMT] : @azure/msal-browser@2.30.0 : Verbose - Emitting event to callback 354e4f7e-2a4c-4e45-938c-a08fb83dca90: msal:initializeEnd
​ Angular is running in development mode. Call enableProdMode() to enable production mode.
​ [Wed, 14 Dec 2022 14:42:36 GMT] : @azure/msal-browser@2.30.0 : Verbose - handleRedirectPromise called
​ [Wed, 14 Dec 2022 14:42:36 GMT] : @azure/msal-browser@2.30.0 : Verbose - getAllAccounts called
​ [Wed, 14 Dec 2022 14:42:36 GMT] : @azure/msal-browser@2.30.0 : Info - Emitting event: msal:handleRedirectStart
​ [Wed, 14 Dec 2022 14:42:36 GMT] : @azure/msal-browser@2.30.0 : Verbose - Emitting event to callback 354e4f7e-2a4c-4e45-938c-a08fb83dca90: msal:handleRedirectStart
​ [Wed, 14 Dec 2022 14:42:36 GMT] : @azure/msal-angular@2.4.5 : Verbose - BroadcastService - msal:handleRedirectStart results in setting inProgress from startup to handleRedirect
​ [Wed, 14 Dec 2022 14:42:36 GMT] : @azure/msal-browser@2.30.0 : Verbose - handleRedirectPromise has been called for the first time, storing the promise
​ [Wed, 14 Dec 2022 14:42:36 GMT] : [dee81dc5-9ca9-40cb-bd28-a7e1f107b82b] : msal.js.browser@2.30.0 : Verbose - initializeServerTelemetryManager called
​ [Wed, 14 Dec 2022 14:42:36 GMT] : [dee81dc5-9ca9-40cb-bd28-a7e1f107b82b] : msal.js.browser@2.30.0 : Verbose - getRedirectResponseHash called
​ [Wed, 14 Dec 2022 14:42:36 GMT] : [dee81dc5-9ca9-40cb-bd28-a7e1f107b82b] : msal.js.browser@2.30.0 : Verbose - Hash contains known properties, returning response hash
​ [Wed, 14 Dec 2022 14:42:36 GMT] : [dee81dc5-9ca9-40cb-bd28-a7e1f107b82b] : msal.js.browser@2.30.0 : Verbose - validateAndExtractStateFromHash called
​ [Wed, 14 Dec 2022 14:42:36 GMT] : [dee81dc5-9ca9-40cb-bd28-a7e1f107b82b] : msal.js.browser@2.30.0 : Verbose - Returning state from hash
​ [Wed, 14 Dec 2022 14:42:36 GMT] : [dee81dc5-9ca9-40cb-bd28-a7e1f107b82b] : msal.js.browser@2.30.0 : Verbose - State extracted from hash
​ [Wed, 14 Dec 2022 14:42:36 GMT] : [dee81dc5-9ca9-40cb-bd28-a7e1f107b82b] : msal.js.browser@2.30.0 : Verbose - Navigating to loginRequestUrl: http://localhost:4200/
​ [Wed, 14 Dec 2022 14:42:36 GMT] : @azure/msal-angular@2.4.5 : Verbose - MsalRedirectComponent activated
​ [Wed, 14 Dec 2022 14:42:36 GMT] : @azure/msal-browser@2.30.0 : Info - initialize has already been called, exiting early.
​ [Wed, 14 Dec 2022 14:42:36 GMT] : @azure/msal-browser@2.30.0 : Verbose - handleRedirectPromise called
​ [Wed, 14 Dec 2022 14:42:36 GMT] : @azure/msal-browser@2.30.0 : Verbose - getAllAccounts called
​ [Wed, 14 Dec 2022 14:42:36 GMT] : @azure/msal-browser@2.30.0 : Verbose - handleRedirectPromise has been called previously, returning the result from the first call
Navigated to http://localhost:4200/
polyfills.js:1 [webpack-dev-server] Server started: Hot Module Replacement disabled, Live Reloading enabled, Progress disabled, Overlay enabled.
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:36 GMT] : @azure/msal-browser@2.30.0 : Verbose - BrowserCrypto: modern crypto interface available
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:36 GMT] : @azure/msal-browser@2.30.0 : Verbose - BrowserCrypto: modern crypto interface available
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:36 GMT] : @azure/msal-browser@2.30.0 : Verbose - Event callback registered with id: f5300dd7-6310-446f-839c-27e4a25535a8
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:36 GMT] : @azure/msal-browser@2.30.0 : Verbose - getAllAccounts called
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:36 GMT] : @azure/msal-browser@2.30.0 : Verbose - Adding account storage listener.
core.mjs:25477 Angular is running in development mode. Call enableProdMode() to enable production mode.
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:36 GMT] : @azure/msal-angular@2.4.5 : Verbose - MsalRedirectComponent activated
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:36 GMT] : @azure/msal-browser@2.30.0 : Info - Emitting event: msal:initializeStart
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:36 GMT] : @azure/msal-browser@2.30.0 : Verbose - Emitting event to callback f5300dd7-6310-446f-839c-27e4a25535a8: msal:initializeStart
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:36 GMT] : @azure/msal-browser@2.30.0 : Info - Emitting event: msal:initializeEnd
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:36 GMT] : @azure/msal-browser@2.30.0 : Verbose - Emitting event to callback f5300dd7-6310-446f-839c-27e4a25535a8: msal:initializeEnd
core.mjs:25477 Angular is running in development mode. Call enableProdMode() to enable production mode.
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:36 GMT] : @azure/msal-browser@2.30.0 : Verbose - handleRedirectPromise called
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:36 GMT] : @azure/msal-browser@2.30.0 : Verbose - getAllAccounts called
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:36 GMT] : @azure/msal-browser@2.30.0 : Info - Emitting event: msal:handleRedirectStart
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:36 GMT] : @azure/msal-browser@2.30.0 : Verbose - Emitting event to callback f5300dd7-6310-446f-839c-27e4a25535a8: msal:handleRedirectStart
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:36 GMT] : @azure/msal-angular@2.4.5 : Verbose - BroadcastService - msal:handleRedirectStart results in setting inProgress from startup to handleRedirect
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:36 GMT] : @azure/msal-browser@2.30.0 : Verbose - handleRedirectPromise has been called for the first time, storing the promise
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:36 GMT] : [dee81dc5-9ca9-40cb-bd28-a7e1f107b82b] : msal.js.browser@2.30.0 : Verbose - initializeServerTelemetryManager called
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:36 GMT] : [dee81dc5-9ca9-40cb-bd28-a7e1f107b82b] : msal.js.browser@2.30.0 : Verbose - getRedirectResponseHash called
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:36 GMT] : [dee81dc5-9ca9-40cb-bd28-a7e1f107b82b] : msal.js.browser@2.30.0 : Verbose - Hash does not contain known properties, returning cached hash
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:36 GMT] : [dee81dc5-9ca9-40cb-bd28-a7e1f107b82b] : msal.js.browser@2.30.0 : Verbose - validateAndExtractStateFromHash called
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:36 GMT] : [dee81dc5-9ca9-40cb-bd28-a7e1f107b82b] : msal.js.browser@2.30.0 : Verbose - Returning state from hash
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:36 GMT] : [dee81dc5-9ca9-40cb-bd28-a7e1f107b82b] : msal.js.browser@2.30.0 : Verbose - State extracted from hash
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:36 GMT] : [dee81dc5-9ca9-40cb-bd28-a7e1f107b82b] : msal.js.browser@2.30.0 : Verbose - Current page is loginRequestUrl, handling hash
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:36 GMT] : [dee81dc5-9ca9-40cb-bd28-a7e1f107b82b] : msal.js.browser@2.30.0 : Verbose - handleHash called, retrieved cached request
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:36 GMT] : [dee81dc5-9ca9-40cb-bd28-a7e1f107b82b] : msal.js.browser@2.30.0 : Verbose - getClientConfiguration called
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:36 GMT] : [dee81dc5-9ca9-40cb-bd28-a7e1f107b82b] : msal.js.browser@2.30.0 : Verbose - getDiscoveredAuthority called
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:36 GMT] : [dee81dc5-9ca9-40cb-bd28-a7e1f107b82b] : msal.js.browser@2.30.0 : Verbose - Creating discovered authority with configured authority
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:36 GMT] : [dee81dc5-9ca9-40cb-bd28-a7e1f107b82b] : msal.js.browser@2.30.0 : Verbose - Auth code client created
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:36 GMT] : [dee81dc5-9ca9-40cb-bd28-a7e1f107b82b] : msal.js.browser@2.30.0 : Verbose - RedirectHandler.handleCodeResponse called
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:36 GMT] : [dee81dc5-9ca9-40cb-bd28-a7e1f107b82b] : @azure/msal-common@7.6.0 : Info - in acquireToken call
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:37 GMT] : @azure/msal-browser@2.30.0 : Verbose - getAllAccounts called
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:37 GMT] : @azure/msal-browser@2.30.0 : Info - Emitting event: msal:loginSuccess
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:37 GMT] : @azure/msal-browser@2.30.0 : Verbose - Emitting event to callback f5300dd7-6310-446f-839c-27e4a25535a8: msal:loginSuccess
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:37 GMT] : @azure/msal-browser@2.30.0 : Verbose - setActiveAccount: Active account set
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:37 GMT] : @azure/msal-browser@2.30.0 : Verbose - setActiveAccount: Active account set
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:37 GMT] : @azure/msal-browser@2.30.0 : Verbose - handleRedirectResponse returned result, login success
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:37 GMT] : @azure/msal-browser@2.30.0 : Info - Emitting event: msal:handleRedirectEnd
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:37 GMT] : @azure/msal-browser@2.30.0 : Verbose - Emitting event to callback f5300dd7-6310-446f-839c-27e4a25535a8: msal:handleRedirectEnd
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:37 GMT] : @azure/msal-angular@2.4.5 : Verbose - BroadcastService - msal:handleRedirectEnd results in setting inProgress from handleRedirect to none
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:37 GMT] : @azure/msal-browser@2.30.0 : Verbose - getAllAccounts called
auth-config.ts:61 [Wed, 14 Dec 2022 14:42:37 GMT] : @azure/msal-browser@2.30.0 : Verbose - getAllAccounts called

### MSAL Configuration

```javascript
export const b2cPolicies = {
    names: {
        signUpSignIn: 'B2C_1_susi_v2',
        resetPassword: 'B2C_1_reset_v3',
        editProfile: 'B2C_1_edit_profile_v2',
    },
    authorities: {
        signUpSignIn: {
            authority: 'https://fabrikamb2c.b2clogin.com/fabrikamb2c.onmicrosoft.com/b2c_1_susi_v2',
        },
        resetPassword: {
            authority: 'https://fabrikamb2c.b2clogin.com/fabrikamb2c.onmicrosoft.com/B2C_1_reset_v3',
        },
        editProfile: {
            authority: 'https://fabrikamb2c.b2clogin.com/fabrikamb2c.onmicrosoft.com/b2c_1_edit_profile_v2',
        },
    },
    authorityDomain: 'fabrikamb2c.b2clogin.com',
};

export const msalConfig: Configuration = {
    auth: {
        clientId: '9067c884-9fa6-414f-9aa4-a565b1cb46be', // This is the ONLY mandatory field that you need to supply.
        authority: b2cPolicies.authorities.signUpSignIn.authority, // Defaults to "https://login.microsoftonline.com/common"
        knownAuthorities: [b2cPolicies.authorityDomain], // Mark your B2C tenant's domain as trusted.
        redirectUri: '/auth', // Points to window.location.origin by default. You must register this URI on Azure portal/App Registration.
        postLogoutRedirectUri: '/', // Points to window.location.origin by default.
    },
    cache: {
        cacheLocation: BrowserCacheLocation.LocalStorage, // Configures cache location. "sessionStorage" is more secure, but "localStorage" gives you SSO between tabs.
        storeAuthStateInCookie: isIE, // Set this to "true" if you are having issues on IE11 or Edge. Remove this line to use Angular Universal
    },
    system: {
        /**
         * Below you can configure MSAL.js logs. For more information, visit:
         * https://docs.microsoft.com/azure/active-directory/develop/msal-logging-js
         */
        loggerOptions: {
            loggerCallback(logLevel: LogLevel, message: string) {
                console.log(message);
            },
            logLevel: LogLevel.Verbose,
            piiLoggingEnabled: false
        }
    }
}
```

### Relevant Code Snippets

```javascript
-
```

### Reproduction Steps

1 Click login button.
2 Click google login button

### Expected Behavior

js files and application are loaded only once

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome

### Regression

msal.js.browser@2.30.0

### Source

External (Customer)

**Comment by derisen** [comment]
@AntonEvseev apologies for the late response. I can reproduce this. Let me debug and get back to you.

**Comment by derisen** [comment]
@AntonEvseev thanks for catching this. This is a misuse of `MsalRedirectComponent` in the sample. Once the MSAL processes the redirect response from AAD on `/auth` route (what we originally set as redirectUri), it redirects the app back to the login request url (in this case, home page). However, `MsalRedirectComponent` by default it does not make use of Angular's own router, causing the whole page content to reload. 

Simples way to mitigate this is by setting the `navigateToLoginRequestUrl` in the MSAL configration object to **false**, and then updating the Angular routes as:

```typescript
const routes: Routes = [
    // ...

    {
        // Needed for handling redirect after login
        path: 'auth',
        component: MsalRedirectComponent,
        redirectTo: '' // redirect to home page
    },
    {
        path: '',
        component: HomeComponent
    }
];
```

You can also look into using a custom navigation client with MSAL. See: [msal-angular/performance](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/performance.md)

I've created an [issue](https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/issues/260) in the sample repo and will make the necessary changes there. Let me know if this helps so I can close it here.

**Comment by AntonEvseev** [comment]
@derisen Thanks, it works.

**Comment by derisen** [comment]
Sounds great! Closing this one then.
