### ISSUE TITLE
Claims are not attached to the request body when using acquireTokenOnBehalfOf API

### ISSUE THREAD

**Issue by salman90** [AzureAD/microsoft-authentication-library-for-js#5486]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.14.5

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.5.1

### Public or Confidential Client?

Confidential

### Description

When setting the configuration object `clientCapabilities` to CP1 in a `ConfidentialClientApplication` instance using `acquireTokenOnBehalfOf` API, the application is not declared [capable of handling challenges](https://learn.microsoft.com/en-us/azure/active-directory/develop/claims-challenge?tabs=JavaScript#how-to-communicate-client-capabilities-to-azure-ad). The issue is in the [createTokenRequestBody](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/src/client/OnBehalfOfClient.ts#L234) function, as the `acquireTokenOnBehalfOf` doesn't attach the claims to the request body as other clients do, for example, in the [client credentials](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/src/client/ClientCredentialClient.ts#L221) flow. Is this intentional in msal-node when using OnBehalfOf flow?

MSAL.NET supports claims challenges when using OnBehalfOf flow, as demonstrated in the following [sample](https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/tree/main/6-AdvancedScenarios/1-call-api-obo).

### Error Message

No error message. We receive an access token without the [xms_cc claim](https://learn.microsoft.com/en-us/azure/active-directory/develop/claims-challenge?tabs=JavaScript#receiving-xms_cc-claim-in-an-access-token)

### Msal Logs

[Fri, 16 Dec 2022 00:22:48 GMT] : @azure/msal-node@1.14.5 : Info - acquireTokenOnBehalfOf called
[Fri, 16 Dec 2022 00:22:49 GMT] : [5526a90b-03a7-4268-a10e-41a15f41b21f] : @azure/msal-common@9.0.1 : Info - SilentFlowClient:acquireCachedToken - No access token found in cache for the given 

### MSAL Configuration

```javascript
const msalConfig = {
    auth: {
        clientId: config.credentials.clientID,
        authority: `https://${config.metadata.authority}/${config.credentials.tenantID}`,
        clientSecret: config.credentials.clientSecret,
        clientCapabilities: ["CP1"],
    },
    system: {
        loggerOptions: {
            loggerCallback(loglevel, message, containsPii) {
                console.log(message);
            },
            piiLoggingEnabled: false,
            logLevel: msal.LogLevel.Info,
        },
    },
};
```

### Relevant Code Snippets

```javascript
const msal = require('@azure/msal-node');
const config = require('./authConfig');

const msalConfig = {
    auth: {
        clientId: config.credentials.clientID,
        authority: `https://${config.metadata.authority}/${config.credentials.tenantID}`,
        clientSecret: config.credentials.clientSecret,
        clientCapabilities: ["CP1"],
    },
    system: {
        loggerOptions: {
            loggerCallback(loglevel, message, containsPii) {
                console.log(message);
            },
            piiLoggingEnabled: false,
            logLevel: msal.LogLevel.Info,
        },
    },
};

// Create msal application object
const cca = new msal.ConfidentialClientApplication(msalConfig);

const getOboToken = async (oboAssertion) => {
    const oboRequest = {
        oboAssertion: oboAssertion,
        scopes: config.resources.downstreamAPI.scopes,
    };

    try {
        const response = await cca.acquireTokenOnBehalfOf(oboRequest);
        return response.accessToken;
    } catch (error) {
        console.log(error);
        return error;
    }
};
```

### Reproduction Steps

1. Initialize a ConfidentialClientApplication instance with the clientCapabilities to cp1 in the configuration object.
2. Acquire a graph access token with acquireTokenOnBehalfOf API.
3. Check if the token includes the required claims

### Expected Behavior

Access token to include [xms_cc claim](https://learn.microsoft.com/en-us/azure/active-directory/develop/claims-challenge?tabs=JavaScript#receiving-xms_cc-claim-in-an-access-token)

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

Internal (Microsoft)

**Comment by bgavrilMS** [comment]
Ack, we will look at this asap.
