### ISSUE TITLE
ClientAuthError: network_error: Network request failed. Please check network trace to determine root cause. | Fetch client threw: TypeError: listener must be a function | Attempted to reach: https://login.microsoftonline.com/common/oauth2/v2.0/devicecode

### ISSUE THREAD

**Issue by veronica-pignotti** [AzureAD/microsoft-authentication-library-for-js#5489]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.14.5

### Wrapper Library

Not Applicable

### Wrapper Library Version

1.14.5

### Public or Confidential Client?

Public

### Description

I tried to request the access token with the device code directly from Azure, but I always get the following error:

ClientAuthError: network_error: Network request failed. Please check network trace to determine root cause. | Fetch client threw: TypeError: listener must be a function | Attempted to reach: https://login.microsoftonline.com/common/oauth2/v2.0/devicecode
    at ClientAuthError.AuthError [as constructor] (AuthError.js?49ab:31:1)
    at new ClientAuthError (ClientAuthError.js?3b73:216:1)
    at ClientAuthError.createNetworkError (ClientAuthError.js?3b73:259:1)
    at NetworkManager.eval (NetworkManager.js?8e49:43:1)
    at step (_tslib.js?b5ec:75:1)
    at Object.eval [as throw] (_tslib.js?b5ec:56:1)
    at rejected (_tslib.js?b5ec:47:1)
    
I followed your code into: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/8b18e2abbdbe79dff8d6bb2cdd8ef90541f5b262/samples/msal-node-samples/device-code/index.js, replacing clientId and authority.

Where am I wrong?

### MSAL Configuration

```javascript
{
    auth: {
        clientId: "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
        authority: "https://login.microsoftonline.com/common/",
        knownAuthorities: ["https://login.microsoftonline.com/common/"],
    },
}
```

### Relevant Code Snippets

```javascript
var clientConfig = {
    auth: {
        clientId: "04b07795-8ddb-461a-bbee-02f9e1bf7b46",
        authority: "https://login.microsoftonline.com/common/",
        knownAuthorities: ["https://login.microsoftonline.com/common/"],
    },
};

var pca = new msal.PublicClientApplication(clientConfig);

var deviceCodeRequest = {
    deviceCodeCallback: (response) => console.log(response.message),
    scopes: []//["user.read"],
};

var authResult = await pca.acquireTokenByDeviceCode(deviceCodeRequest)
    .then(res => {
        console.log(res);
        return res;
    })
    .catch(error => {

/*
this is always the error :
ClientAuthError: network_error: Network request failed. Please check network trace to determine root cause. | Fetch client threw: TypeError: listener must be a function | Attempted to reach: https://login.microsoftonline.com/common/oauth2/v2.0/devicecode
    at ClientAuthError.AuthError [as constructor] (AuthError.js?49ab:31:1)
    at new ClientAuthError (ClientAuthError.js?3b73:216:1)
    at ClientAuthError.createNetworkError (ClientAuthError.js?3b73:259:1)
    at NetworkManager.eval (NetworkManager.js?8e49:43:1)
    at step (_tslib.js?b5ec:75:1)
    at Object.eval [as throw] (_tslib.js?b5ec:56:1)
    at rejected (_tslib.js?b5ec:47:1)
*/
        console.log(error);
        return null;
    });
```

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
I am not able to reproduce this with our device code sample. What version of node are you using? Can you debug to see what the fetch client is receiving if not a function?

**Comment by veronica-pignotti** [comment]
I haven't a node app, but I have a vue app. I can't see what the client gets with debugging.
The error always appears when using other functions as well, such as 'acquireTokenByCode'. How can I configure this listener? I can't find any examples.

**Comment by tnorling** [comment]
I see. For Vue, or any other browser based apps, you should use the `msal-browser` package, not `msal-node`. We do have a sample for Vue 3 which you can find [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-browser-samples/vue3-sample-app)

**Comment by veronica-pignotti** [comment]
I tried to use msal-browser and would like to report an error. The acquireTokenByCode request always returns this error:
"ServerError: invalid_grant: 700009 : AADSTS700009: Reply address must be provided when presenting an authorization code requested with an explicit reply address."
Although the 'redirectUri' value is present in token request, I noticed with Fiddler that it is not inserted in the request body.

**Comment by tnorling** [comment]
`acquireTokenByCode` is specifically for the "hybrid flow" - this is an advanced feature which you do not need if your app is a pure SPA. You should use `acquireTokenSilent` and one of `acquireTokenPopup` or `acquireTokenRedirect`. Please have a look at the sample I linked above to get you started.
