### ISSUE TITLE
Need to clear "localstorage" automatically after token expired

### ISSUE THREAD

**Issue by jesusarockias** [AzureAD/microsoft-authentication-library-for-js#5495]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.32.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.5.1

### Public or Confidential Client?

Public

### Description

We have set token expiry time as 10 hours in Azure AD. Browser storage location is configured as "localstorage".

But the problem is that the localstorage is not cleared so once we login using credentials then we can login without entering credential even after the "Token Expiry" time. (in our case it is 10 hours)

Can any one point us to proper documentation or code snippet for this?

You can find the configuration from the below code snippet

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/41784897/208930464-f0818681-95fa-4f89-a62b-372e9483b145.png)

Please help me to resolve this

### MSAL Configuration

```javascript
auth: {

 

clientId: environment.clientId,

redirectUri: environment.redirectUri,

postLogoutRedirectUri: environment.postLogoutRedirectUri,

authority: environment.authority

},

cache: {

cacheLocation: BrowserCacheLocation.LocalStorage,

storeAuthStateInCookie: true

},

system: {

loggerOptions: {

loggerCallback: () => { }

}

}
```

### Relevant Code Snippets

```javascript
export function MsalInstanceFactory(): IPublicClientApplication {
  return new PublicClientApplication({
    auth: {
      clientId: 'my clientId',
      redirectUri: '<domain>/azurePOC2/auth',
      authority: 'https://login.microsoftonline.com/common/',
      postLogoutRedirectUri: '<domain>//azurePOC2/logout'
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: true
    },
    system: {
      loggerOptions: {
        loggerCallback: ()=>{}
      }
    }
  })
}

export function MsalGuardConfig(): MsalGuardConfiguration {
  return {
    interactionType: InteractionType.Redirect,
    loginFailedRoute: '<domain>/azurePOC2/error',
    authRequest: {
      scopes: ['openid']
    }
  }
}
```

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
Token lifetime is != session lifetime. The reason you are able to reauthenticate after the token expires is because the session cookie has a longer lifetime than the token and is being used to mint a new token after the initial one has expired. If you'd like to enforce how often a user is prompted for credentials you should configure [sign in frequency CA policy](https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/howto-conditional-access-session-lifetime#user-sign-in-frequency)

**Comment by jesusarockias** [comment]
@tnorling - Thank you for prompt response and  pointing to the proper resource. I will check this suggestion and contact back if anything needs. 

Merci Beaucoup!!! :)
