### ISSUE TITLE
MSAL.js React with custom url does not seem to be working

### ISSUE THREAD

**Issue by afridley** [AzureAD/microsoft-authentication-library-for-js#5496]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.30

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.9

### Public or Confidential Client?

Confidential

### Description

Using a custom url based on https://learn.microsoft.com/en-us/azure/active-directory-b2c/enable-authentication-spa-app-options in the msalConfig does not seem to be working
```js
const msalConfig = {
  auth: {
    clientId: id,
    authority: 'https://account.customdomain.org/${tenantId}/te/B2C_1A_consumer_signup_signin',
    redirectUri: '/',
    postLogoutRedirectUri: '/sign-in',
    navigateToLoginRequestUrl: false,
    knownAuthorities: ['account.customdomain.org'],
  },

  cache: {
    cacheLocation: 'sessionStorage',
    storeAuthStateInCookie: true,
  },
}
```

With this it seems to be duplicating the url when calling
https://login.microsoftonline.com/common/discovery/instance?api-version=1.1&authorization_endpoint=https://https://account.customdomain.org/34324321432143214321/te/b2c_1a_consumer_signup_signin.b2clogin.com/https://account.customdomain.org/34324321432143214321/te/b2c_1a_consumer_signup_signin.onmicrosoft.com/te/b2c_1a_consumer_signup_signin/oauth2/v2.0/authorize

Is what ends up being called which looks very broken
### MSAL Configuration

```javascript
const msalConfig = {
  auth: {
    clientId: id,
    authority: 'https://account.customdomain.org/${tenantId}/te/B2C_1A_consumer_signup_signin',
    redirectUri: '/',
    postLogoutRedirectUri: '/sign-in',
    navigateToLoginRequestUrl: false,
    knownAuthorities: ['account.customdomain.org'],
  },

  cache: {
    cacheLocation: 'sessionStorage',
    storeAuthStateInCookie: true,
  },
}
js
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by tnorling** [comment]
Can you please double check that your actual config looks exactly like the config you've shared here and you are not providing a different authority on your login/acquireToken request? 

Sort of looks like string placeholders gone wrong. Something like this perhaps? Try hardcoding your authority and see if it resolves itself

```js
const tenant = "1234";
const authority = `https://account.customdomain.com/${tenant}/`
const policy = `${authority}/sign_up_sign_in_policy`

const msalConfig = {
  auth: {
    authority: `https://${authority}/${policy}`
  }
}

```

**Comment by tnorling** [comment]
Also of note, if the domain in `knownAuthorities` matches the domain in `authority` the instance discovery call will be skipped
