### ISSUE TITLE
Use commonjs instead of amd in typescript compilerOptions

### ISSUE THREAD

**Issue by harshithkashyap** [AzureAD/microsoft-authentication-library-for-js#55]
I'm trying to import this module in Angular 4 but it looks like the client library is not exported. Use commonjs as used by [Microsoft JS Graph SDK](https://github.com/microsoftgraph/msgraph-sdk-javascript)

**Comment by rohitnarula7176** [comment]
@harshithkashyap You can now import msal using es-6 and commonjs syntax. It is added in the dev branch. Closing this issue. Please reopen if you still face issues.
