### ISSUE TITLE
Vulnerability in the dependency: jsonwebtoken

### ISSUE THREAD

**Issue by mfeminer** [AzureAD/microsoft-authentication-library-for-js#5501]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.14.5

### Wrapper Library

Not Applicable

### Wrapper Library Version

not applicable

### Public or Confidential Client?

Public

### Description

There is a security issue in dependency jsonwebtoken. Updating to jsonwebtoken's latest version 9.0.0 resolves the vulnerability.
Details: [GHSA-27h2-hvpr-p74q](https://github.com/advisories/GHSA-27h2-hvpr-p74q)

### Identity Provider

None

### Source

External (Customer)

**Comment by ptc-jhirzel** [comment]
Same as this one: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5500

**Comment by tnorling** [comment]
Thanks, we'll look to address this ASAP. Closing as duplicate, updates will be shared in #5500
