### ISSUE TITLE
Vanilla JavaScript SPA acquireTokenRedirect() not getting token for a code

### ISSUE THREAD

**Issue by kkukkadri** [AzureAD/microsoft-authentication-library-for-js#5504]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.32.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

none

### Public or Confidential Client?

Public

### Description

Hello,

I am using the sample here https://github.com/Azure-Samples/ms-identity-javascript-v2 to make the loginRedirect() or acquireTokenRedirect() methods working, and have configured the Azure AAD app exactly by the example. Login method with popup works perfect, but login with redirect is always stuck in the same place. 

Once I press the sign in button, the URL renders with the "code" parameter and the process stops there. Please see the rendered URL here under. How should the token be received in exchange for a code from this point on?

The same issue happens as well, when the redirect url is tunneled via ngrok. Also the behavior is browser independent.

I will need to use login **redirect** in my application, as many web browsers block popups and hence it won't suit to my use case. Any help, how to make that work is more than appreciated. 

**URL with code parameter:** 

https://localhost:3000/#code=0.AYIAxNRsOei8SkajXzGvkmE0uBxVWrG_xxxxx

Thanks! Kadri

### Error Message

This site can’t provide a secure connection 
localhost sent an invalid response.
ERR_SSL_PROTOCOL_ERROR

### Msal Logs

The following messages appear in console when I load the login page:
[Tue, 27 Dec 2022 08:42:56 GMT] : @azure/msal-browser@2.30.0 : Info - Emitting event: msal:handleRedirectStart
authConfig.js:30 [Tue, 27 Dec 2022 08:42:56 GMT] : [4bfb48ab-4407-4324-a3df-fa80226f3684] : msal.js.browser@2.30.0 : Info - handleRedirectPromise called but there is no interaction in progress, returning null.
authConfig.js:30 [Tue, 27 Dec 2022 08:42:56 GMT] : @azure/msal-browser@2.30.0 : Info - Emitting event: msal:handleRedirectEnd

This message appears once I press the sign in button:
crbug/1173575, non-JS module files deprecated.
(anonymous) @ VM11:6748

### MSAL Configuration

```javascript
const msalConfig = {
    auth: {
        // 'Application (client) ID' of app registration in Azure portal - this value is a GUID
        clientId: "XXX-my-actual-client-id",
        // Full directory URL, in the form of https://login.microsoftonline.com/<tenant-id>
        authority: "https://login.microsoftonline.com/common",
        // Full redirect URL, in form of http://localhost:3000
        redirectUri: "https://localhost:3000/",
    },
    cache: {
        cacheLocation: "localStorage", 
        storeAuthStateInCookie: false, 
    },
    system: {
        loggerOptions: {
            loggerCallback: (level, message, containsPii) => {
                if (containsPii) {
                    return;
                }
                switch (level) {
                    case msal.LogLevel.Error:
                        console.error(message);
                        return;
                    case msal.LogLevel.Info:
                        console.info(message);
                        return;
                    case msal.LogLevel.Verbose:
                        console.debug(message);
                        return;
                    case msal.LogLevel.Warning:
                        console.warn(message);
                        return;
                }
            }
        }
    }
};


const loginRequest = {
    scopes: ["User.Read"]
};
```

### Relevant Code Snippets

```javascript
redirect flow in the code is the same as here: https://github.com/Azure-Samples/ms-identity-javascript-v2/blob/master/app/authRedirect.js
```

### Reproduction Steps

1. download https://github.com/Azure-Samples/ms-identity-javascript-v2
2. adjust index html to use redirect method for login
3. run the sample 

### Expected Behavior

The redirect code flow in the sample is able to acquire the token store that in cache.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox

### Source

External (Customer)

**Comment by tnorling** [comment]
If the code isn't being removed from the url it usually means `handleRedirectPromise` was not invoked on the page used as your redirectUri. Are there any logs in the console after you return from the redirect?

@derisen @salman90 Is this something you can assist with?

**Comment by kkukkadri** [comment]
Many thanks for your reply!

Just to clarify, my sign-in url is http://localhost:3000/chat and redirectUri is http://localhost:3000, to what extent I should invoke handleRedirectPromise on both pages?

E.g. something like this on both:

myMSALObj.handleRedirectPromise().then(handleResponse).catch(err => {
    console.error(err);
});

function handleResponse(resp) {
    if (resp !== null) {
        accountId = resp.account.homeAccountId;
        myMSALObj.setActiveAccount(resp.account);
        showWelcomeMessage(resp.account);
    } else {
        // need to call getAccount here?
        const currentAccounts = myMSALObj.getAllAccounts();
        if (!currentAccounts || currentAccounts.length < 1) {
            return;
        } else if (currentAccounts.length > 1) {
            // Add choose account code here
        } else if (currentAccounts.length === 1) {
            const activeAccount = currentAccounts[0];
            myMSALObj.setActiveAccount(activeAccount);
            accountId = activeAccount.homeAccountId;
            showWelcomeMessage(activeAccount);
        }
    }
}
 
I am also testing the loginPopup method and in certain circumstanced end up in having a code variable in the URL of the popup window and not getting further. What could be the blocking issue in this case? It happens in Chrome specifically. In Firefox everything works fine.

More specifically, I am able to reproduce that with the following steps:
1) have logged in to Teams web client with my org account
2) Teams bot displays me a button with a link to a SPA which open in a separate browser tab and logs in silently or initiates a login with a popup method. 

It seems as if msalInstance.getAllAccounts()[0] does not return to me my signed in account (already signed in to Teams web app)

Many thanks for your help!

Kind regards

**Comment by tnorling** [comment]
> Just to clarify, my sign-in url is http://localhost:3000/chat and redirectUri is http://localhost:3000/, to what extent I should invoke handleRedirectPromise on both pages?

Yes you should call handleRedirectPromise on both pages. The default behavior is that handleRedirectPromise called on the redirectUri page will redirect you to the starting page (in your case /chat) and then handleRedirectPromise called on the starting page will exchange the code for tokens.

> I am also testing the loginPopup method and in certain circumstanced end up in having a code variable in the URL of the popup window and not getting further. What could be the blocking issue in this case? It happens in Chrome specifically. In Firefox everything works fine.

I'd need more information to speculate as to what's happening here. Can you share verbose or trace level logs and perhaps a video?

> It seems as if msalInstance.getAllAccounts()[0] does not return to me my signed in account (already signed in to Teams web app)

The `getAllAccounts` API returns the accounts which are stored in local/session storage, and is not necessarily an enumeration of accounts currently signed in to the service. Storage is sandboxed per domain, thus when you open your app for the first time accounts will always be empty regardless of whether or not you are signed into another app.

**Comment by kkukkadri** [comment]
Thanks!

Are there any good examples of calling handleRedirectPromise on both redirect page and the actual login page, e.g. also using await, not then/catch/finally?

The issue that I have on Chrome seems to be a different type of problem, so not adding it to this thread further on.

**Comment by tnorling** [comment]
```
const response = await pca.handleRedirectPromise();
handleResponse(response);
```
