### ISSUE TITLE
Angular - Handling optional authentication on a route 

### ISSUE THREAD

**Issue by akoreh** [AzureAD/microsoft-authentication-library-for-js#5505]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.28.3

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.4.3

### Public or Confidential Client?

Public

### Description

I have to implement a feature in which I have to show the details of a logged in user in a page, if the user is logged in and just not show them if he is not. Currently I have a setup with `MsalGuard` for my routes that strictly require authentication and I use the `getActiveAccount` method from the `MsalService` to retrieve the active account after the login flow.

The issue I got stuck on now is that the method does not return any account, neither does the `getAllAccounts` method, even when I am logged in, unless I add `MsalGuard` to the route in question. Is there any way to retrieve the current account of the logged in user, and not force a login if he's not?

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by tnorling** [comment]
The account APIs should work independently of the Guard. To confirm my understanding is correct, you have two routes - one protected by the Guard and the other without the Guard. You navigate to the guarded route, sign in then navigate to the "unprotected" route and `getAllAccounts` is returning an empty array?

Can you please share verbose logs demonstrating this behavior?
