### ISSUE TITLE
Expecting angular15-rxjs7-sample-app

### ISSUE THREAD

**Issue by byunru** [AzureAD/microsoft-authentication-library-for-js#5506]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Public or Confidential Client?

Public

### Description

Expecting [angular15-rxjs7-sample-app]

### Source

External (Customer)

**Comment by tnorling** [comment]
This will be added as soon as we are ready to officially support Angular 15. Please follow #5410 for updates on that.
