### ISSUE TITLE
`handleRedirectObservable` returns only the `HANDLE_REDIRECT_END` when using the redirect url from a new tab.

### ISSUE THREAD

**Issue by hansakaRightS** [AzureAD/microsoft-authentication-library-for-js#5507]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.22.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.1.2

### Public or Confidential Client?

Public

### Description

We have the MSAL login with the redirect option implemented in angular, which is working fine if everything is happening in the same tab. but if we copy the redirected url to a new tab and login using valid credentials, **handleRedirectObservable** method only returns the **HANDLE_REDIRECT_END** without any token info.

and when ever we invoke the login function again manually we get the login success as Normal.

I want user to get the login success as normal event if they uses the url in a new tab.

### MSAL Configuration

```javascript
auth: {
        clientId: clientId,
        authority: "B2C_1A_SIGNUP_SIGNIN",
        redirectUri: '/',
        navigateToLoginRequestUrl: false
    },
    cache: {
        cacheLocation: "LocalStoarage",
        storeAuthStateInCookie: false
    }
```

### Identity Provider

None

### Source

External (Customer)

**Comment by tnorling** [comment]
@HansakaSS I'm not sure I understand your scenario. Can you give me a step by step?

**Comment by hansakaRightS** [comment]
@tnorling thanks for the reply. 
yes. whenever we use the redirect option to login, and after we redirected to the login page and we copy the page url to a new tab and continue the login i can face this issue.
it redirect me back to my application but i don't have the success login. also i can see the `state` and `client_info` on the address after the redirect back to the application.

1. invoke redirect login
2. from the login page copy the URL to a new tab
3. login using the valid credentials
4. getting redirect back to the  application but I'm not getting the `msal:loginSuccess`. only gets the `msal:handleRedirectEnd` from `handleRedirectObservable`.

**Comment by tnorling** [comment]
This is not a supported scenario. Login must be initiated and completed from within the same session (tab). Can you tell me a little more about why you need to open the login page in a new tab?

**Comment by hansakaRightS** [comment]
thanks for the clarification. Its not that we are opening the login in a new tab. problem occurs if we use a password vault to log in. for example zoho.

**Comment by tnorling** [comment]
> Its not that we are opening the login in a new tab. 

I'm a bit confused by this statement because this seems to conflict what you stated in your previous comment: 

> 2. from the login page copy the URL to a new tab

Can you please clarify?

> problem occurs if we use a password vault to log in. for example zoho.

Can you please go into more detail about this? I don't understand how this relates.
