### ISSUE TITLE
How to authenticate React application on the server

### ISSUE THREAD

**Issue by uehlbran** [AzureAD/microsoft-authentication-library-for-js#5509]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

N/A

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

N/A

### Public or Confidential Client?

Public

### Description

I have a react application that was created using create-react-app. I also have an ASP.NET Core Web Application (API) that the React application should talk directly to for everything (including authentication). They're completely separate applications.

I don't understand how I can make a request from my React application to my ASP.NET Core backend (something like /api/auth/login) and then have my backend redirect my React application to the authentication server (in this case Azure AD). After that the user would login, and the Identity/Access tokens would be sent back to the ASP.NET Core application where the access token would be stored on the server and the identity token would be converted to a cookie and sent back to the React application. Essentially, an API Gateway/BFF pattern using Microsoft.Identity.Web is what I want.

The reason I want to do this is that storing tokens in the browser is a security risk. I'm not sure if what I'm asking for above is the correct way to go about this but, I'm pretty sure that msal-react is an insecure approach to authentication.

Can someone please point me in the right direction on how to achieve this? And please be thorough in your explanation. Assume I'm an idiot (I kind-of am).

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by derisen** [comment]
@uehlbran @bmahall  I'm afraid there's no sample that implements the BFF pattern at this moment (but it's in the backlog, so keep an eye out). The closest thing would be to use [hybrid spa auth flow](https://github.com/AzureAD/microsoft-identity-web/wiki/Hybrid-SPA), where you authenticate a user on both client and server side (see the [sample](https://github.com/Azure-Samples/active-directory-aspnetcore-webapp-openidconnect-v2/tree/master/2-WebApp-graph-user/2-5-HybridFlow)). You can then use the server side app to perform more sensitive authZ tasks, while the client side app serves mainly as UI. To be clear this doesn't eliminate all tokens from the client side browser storage, but only helps you avoids high privilage tokens on the client side (in general, we consider browser storage secure as long as your app takes precauations against XSS related vulnurabilities -see the [OWASP XSS prevention cheat sheet](https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html) for reference. Note that MSAL.js also has a [memory storage option](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/caching.md#cache-storage))
