### ISSUE TITLE
Compatibility with node v19

### ISSUE THREAD

**Issue by badeball** [AzureAD/microsoft-authentication-library-for-js#5516]
### Core Library

MSAL Node (@azure/msal-node)

### Wrapper Library

Not Applicable

### Public or Confidential Client?

Public

### Description

Node v19 was released 2022-10-17 and it would be nice if this was compatible. Currently it restricts node as seen here: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/msal-node-v1.14.5/lib/msal-node/package.json#L66

### Source

External (Customer)

**Comment by hectormmg** [comment]
@badeball thanks for raising the issue. MSAL Node only supports even-numbered versions of Node.js, as is explained in our [docs](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-node#node-version-support).

**Comment by bmahall** [comment]
Thanks @hectormmg ! @badeball Closing this as resolved, you can also use [discussions](https://github.com/AzureAD/microsoft-authentication-library-for-js/discussions/new) for any feedback on this context and general library usage.
