### ISSUE TITLE
Getting started is missing installation of nx

### ISSUE THREAD

**Issue by bjorn-einar-bjartnes-4ss** [AzureAD/microsoft-authentication-library-for-js#5519]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

Not Applicable

### Public or Confidential Client?

Public

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/contributing.md#build-library

### Description

As described in https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/5517, there seems to be a requirement to install nx.

It could be added to package.json, it worked for me to add nx as a dev-dependency, but I was a bit unsure about the massive diffs in package-lock. 

I guess it also could be added to the readme in https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/contributing.md#build-library to install it.

**Comment by bmahall** [comment]
@bjorn-einar-bjartnes-4ss I cannot reproduce this issue on my machine, while #5517 is under review, can you look into the output of nx report to check for any version mismatches , and deleting node_modules before npm install might help in case there is a mismatch.

**Comment by bjorn-einar-bjartnes-4ss** [comment]
It does happen on a clean clone on both windows and linux when 
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/88324093/210589099-56bb3b9b-09e9-42a8-b41d-fcf96dac6f49.png">
<img width="797" alt="image" src="https://user-images.githubusercontent.com/88324093/210589299-bada6015-1271-4f07-b28f-f0539ba09e9e.png">

On both windows and linux it works again when I run
```
npm install nx
npm run build
```
I guess it is lerna that needs to include nx as a dependency,  so I can close the issue, but it will affect users who do not install nx "by hand" until this is fixed in lerna.

**Comment by bjorn-einar-bjartnes-4ss** [comment]
I reported it on lerna https://github.com/lerna/lerna/issues/3481
I guess it belongs there, and I guess I can close this issue and it will be fixed sometime in lerna I suppose.

**Comment by bjorn-einar-bjartnes-4ss** [comment]
It is being fixed upstream https://github.com/lerna/lerna/pull/3486 @bmahall
