### ISSUE TITLE
Glob pattern URL matching for unprocted ressource

### ISSUE THREAD

**Issue by Davilink** [AzureAD/microsoft-authentication-library-for-js#552]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>
## Library version

<pre><code>
Library version: 0.2.4

## Current behavior
Glob url matching isn't supported

## Expected behavior
Support glob matching pattern

## Minimal reproduction of the problem with instructions
/assets/* so alll route under /assets is mark has unprotected.
</code></pre>

**Comment by sameerag** [comment]
@Davilink Can you please expand this requirement?

**Comment by Davilink** [comment]
If i want to unprotected a bunch or url that normally would match a GLOB Pattern, i would have to manually add all the url in the array of unprotected resource. So if we could have GLOB Pattern support (or other mecanism) to indicate which resource is unprotected or not that would be nice.

**Comment by jasonnutter** [comment]
We'll track this feature request in #786, thanks!

**Comment by jasonnutter** [comment]
We did not get to this in MSAL Angular v1, but is a follow up improvement we want to make. Reopening and tracking.
