### ISSUE TITLE
[Help] MSAL failing to retrieve new/refreshed token in local development after expiration

### ISSUE THREAD

**Issue by terrenceferguson** [AzureAD/microsoft-authentication-library-for-js#5524]
**Logs and network traces**

> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:54 GMT] : @azure/msal-browser@2.28.3 : Verbose - handleRedirectPromise called
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:54 GMT] : @azure/msal-browser@2.28.3 : Verbose - getAllAccounts called
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:54 GMT] : @azure/msal-browser@2.28.3 : Info - Emitting event: msal:handleRedirectStart
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:54 GMT] : @azure/msal-browser@2.28.3 : Verbose - handleRedirectPromise has been called for the first time, storing the promise
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:54 GMT] : [bc8bf137-eb3c-4e58-9856-8a8d050d25f9] : msal.js.browser@2.28.3 : Verbose - initializeServerTelemetryManager called
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:54 GMT] : [bc8bf137-eb3c-4e58-9856-8a8d050d25f9] : msal.js.browser@2.28.3 : Info - handleRedirectPromise called but there is no interaction in progress, returning null.
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:54 GMT] : @azure/msal-browser@2.28.3 : Info - Emitting event: msal:handleRedirectEnd
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:54 GMT] : @azure/msal-browser@2.28.3 : Verbose - getAllAccounts called
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : @azure/msal-browser@2.28.3 : Verbose - getAllAccounts called
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       Provisioning a token silently for scopes 'https://graph.microsoft.com/User.Read'
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : @azure/msal-browser@2.28.3 : Verbose - preflightBrowserEnvironmentCheck started
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : @azure/msal-browser@2.28.3 : Verbose - acquireTokenSilent called
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : @azure/msal-browser@2.28.3 : Verbose - acquireTokenSilent called for the first time, storing active request
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : @azure/msal-browser@2.28.3 : Info - Emitting event: msal:acquireTokenStart
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : @azure/msal-browser@2.28.3 : Verbose - acquireTokenSilent - attempting to acquire token from web flow
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - Initializing BaseAuthRequest
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - Authentication Scheme wasn't explicitly set in request, defaulting to "Bearer" request
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - initializeServerTelemetryManager called
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - getClientConfiguration called
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - getDiscoveredAuthority called
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - Creating discovered authority with configured authority
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - Silent auth client created
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : @azure/msal-common@7.4.1 : Info - SilentFlowClient:acquireCachedToken - Cached access token is expired or will expire within 300 seconds.
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : @azure/msal-browser@2.28.3 : Info - Emitting event: msal:acquireTokenFromNetworkStart
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - Initializing BaseAuthRequest
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - Authentication Scheme set to "Bearer" as configured in Auth request
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - initializeServerTelemetryManager called
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - getClientConfiguration called
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - getDiscoveredAuthority called
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - Creating discovered authority with configured authority
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - Refresh token client created
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : @azure/msal-browser@2.28.3 : Verbose - Refresh token expired or invalid, attempting acquire token by iframe
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - acquireTokenByIframe called
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - initializeAuthorizationRequest called
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - getRedirectUri called
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - Initializing BaseAuthRequest
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - Authentication Scheme set to "Bearer" as configured in Auth request
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - Setting validated request account
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - initializeServerTelemetryManager called
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - getClientConfiguration called
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - getDiscoveredAuthority called
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - Creating discovered authority with configured authority
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - Auth code client created
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - initializeAuthorizationRequest called
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : @azure/msal-common@7.4.1 : Verbose - createAuthCodeUrlQueryString: Adding login_hint from account
> The thread 0xe has exited with code 0 (0x0).
> The program '' has exited with code 4294967295 (0xffffffff).
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:20:01 GMT] : @azure/msal-browser@2.28.3 : Info - Emitting event: **msal:acquireTokenFailure**
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:20:01 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : @azure/msal-browser@2.28.3 : Verbose - PerformanceClient: Measurement found for acquireTokenSilent
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:20:01 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : @azure/msal-browser@2.28.3 : Verbose - PerformanceClient: Submeasurement for acquireTokenSilent already exists for standardInteractionClientGetDiscoveredAuthority, ignoring
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:20:01 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : @azure/msal-browser@2.28.3 : Verbose - PerformanceClient: Submeasurement for acquireTokenSilent already exists for standardInteractionClientGetDiscoveredAuthority, ignoring
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:20:01 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : @azure/msal-browser@2.28.3 : Verbose - PerformanceClient: Emitting performance events

**Which version of MSAL.NET are you using?**

7.0.1

**Platform**

.NET 7 Blazor WASM Standalone Azure AAD

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [ ] Integrated Windows Authentication
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web app 
    * [ ] Authorization code
    * [ ] On-Behalf-Of
* Daemon app 
    * [ ] Service to Service calls

Other?

Not sure (I'm assuming authorization code?).

**Is this a new or existing app?**

New

**Repro**
Authenticate initially, let access expire (normally happens when I start work the next day), start debugging app again locally.

**Expected behavior**
I would expect the app upon seeing an expired token to automatically redirect to login, acquire a new token, and log the user in.

**Actual behavior**
The call to graph API fails due to a Bad Token (expired).

**Additional context / logs / screenshots / links to code**

Program.cs (MSAL Config)
```csharp
builder.Services.AddMicrosoftGraphClient("https://graph.microsoft.com/User.Read");

builder.Services.AddMsalAuthentication(options =>
{
    builder.Configuration.Bind("AzureAd", options.ProviderOptions.Authentication);
    options.ProviderOptions.DefaultAccessTokenScopes.Add("https://graph.microsoft.com/openid");
    options.ProviderOptions.DefaultAccessTokenScopes.Add("https://graph.microsoft.com/profile");
    options.ProviderOptions.DefaultAccessTokenScopes.Add("https://graph.microsoft.com/User.Read");

    options.ProviderOptions.Cache.CacheLocation = "localStorage";
    options.ProviderOptions.LoginMode = "redirect";
});
```
LoginDisplay.razor
```razor
<AuthorizeView>
    <NotAuthorized>
        <MudButton Variant="Variant.Filled" Color="Color.Primary" OnClick="@(() => Navigation.NavigateToLogin("authentication/login"))">Login</MudButton>
    </NotAuthorized>
    <Authorized>
        <MudTooltip Duration="1000" Text="@($"Hello, {_user?.DisplayName}!")">
                    <MudAvatar Class="mt-2"
                        Rounded="true"
                               Size="Size.Medium"
                               Image="@(@$"data:image/jpeg;base64,{_imgSrc}")">
                    </MudAvatar>
                </MudTooltip>
        <MudButton Class="ml-4" Variant="Variant.Filled" Color="Color.Secondary" OnClick="BeginSignOut">Logout</MudButton>
    </Authorized>
</AuthorizeView>

@code {

    [CascadingParameter]
    Task<AuthenticationState> authenticationStateTask { get; set; } = default!;

    private User? _user;
    private string? _imgSrc;

    protected override async Task OnInitializedAsync()
    {
        if (authenticationStateTask is not null)
        {
            var auth = await authenticationStateTask;

            var qq = authenticationStateTask.Result;

            if (auth.User.Identity?.IsAuthenticated ?? false)
            {
                _user = await GraphClient.Me.Request().GetAsync();

                using (var photoResponse = await GraphClient.Me.Photo.Content.Request().GetResponseAsync())
                {
                    if (photoResponse != null)
                    {
                        _imgSrc = Convert.ToBase64String(await photoResponse.Content.ReadAsByteArrayAsync());
                    }
                }
            }
        }
    }

    private void BeginSignOut(MouseEventArgs args)
    {
        Navigation.NavigateToLogout("authentication/logout");
    }
}
```
RedirectToLogin.razor
```razor
@using Microsoft.AspNetCore.Components.WebAssembly.Authentication;
@using Microsoft.Extensions.Options

@inject NavigationManager Navigation
@inject IOptionsSnapshot<RemoteAuthenticationOptions<ApiAuthorizationProviderOptions>> Options

@code {
    protected override void OnInitialized()
    {
        Navigation.NavigateToLogin(Options.Get(
            Microsoft.Extensions.Options.Options.DefaultName)
            .AuthenticationPaths.LogInPath);
    }
}
```
Authentication.razor
```razor
@layout LoginLayout
@page "/authentication/{action}"
@using Microsoft.AspNetCore.Components.WebAssembly.Authentication

<RemoteAuthenticatorView Action="@Action">
    <LoggingIn>
        Custom login screen...
    </LoggingIn>

    <LogInFailed>
        
    </LogInFailed>
    
    <LogOutSucceeded>
        Custom logout screen...
    </LogOutSucceeded>
</RemoteAuthenticatorView>

@code{
    [Parameter] public string? Action { get; set; }
}
```
![image](https://user-images.githubusercontent.com/19277507/210412646-db1039e6-6808-44ca-b4fa-c06e1c0fb3c2.png)

![image](https://user-images.githubusercontent.com/19277507/210412815-2fef51dc-1c0e-429d-a8cc-81ded5f8870e.png)

If I manually delete the token from the local storage, it will retrieve it correctly. I haven't really noticed the issue when the app is published to our DEV server. I'm not sure if I have something configured incorrectly, or if there's an actual issue here.

**Comment by pmaytak** [comment]
Seems like it's Blazor using MSAL JavaScript underneath.

**Comment by terrenceferguson** [comment]
> Seems like it's Blazor using MSAL JavaScript underneath.

Does this mean I need to post it somewhere else? This is my first time posting an issue.

**Comment by pmaytak** [comment]
@bmahall Can JS team help with this or should this go to Blazor team?

**Comment by bmahall** [comment]
@terrenceferguson Can you create a new issue here? [MSAL_JS](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/new/choose)
