### ISSUE TITLE
npm audit fails: 

### ISSUE THREAD

**Issue by oliverbock** [AzureAD/microsoft-authentication-library-for-js#5526]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.14.2

### Wrapper Library

Not Applicable

### Wrapper Library Version

n/a

### Public or Confidential Client?

Public

### Description

npm audit fails due to a vulnerability in a package being used.  See below

### Error Message

                       === npm audit security report ===

                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance

  Moderate        jsonwebtoken unrestricted key type could lead to legacy keys  
                  usage 

  Package         jsonwebtoken

  Patched in      >=9.0.0

  Dependency of   @azure/msal-node

  Path            @azure/msal-node > jsonwebtoken

  More info       https://github.com/advisories/GHSA-8cf7-32gw-wr33

  High            jsonwebtoken has insecure input validation in jwt.verify
                  function

  Package         jsonwebtoken

  Patched in      >=9.0.0

  Dependency of   @azure/msal-node

  Path            @azure/msal-node > jsonwebtoken

  More info       https://github.com/advisories/GHSA-27h2-hvpr-p74q

  Moderate        jsonwebtoken's insecure implementation of key retrieval
                  function could lead to Forgeable Public/Private Tokens from
                  RSA to HMAC

  Package         jsonwebtoken

  Patched in      >=9.0.0

  Dependency of   @azure/msal-node

  Path            @azure/msal-node > jsonwebtoken

  More info       https://github.com/advisories/GHSA-hjrf-2m68-5959

  Moderate        jsonwebtoken vulnerable to signature validation bypass due
                  to insecure default algorithm in jwt.verify()

  Package         jsonwebtoken

  Patched in      >=9.0.0

  Dependency of   @azure/msal-node

  Path            @azure/msal-node > jsonwebtoken

  More info       https://github.com/advisories/GHSA-qwph-4952-7xr6

### MSAL Configuration

```javascript
n/a because problem occurs before configuration
```

### Relevant Code Snippets

```javascript
npm install msal-node
npm audit
```

### Reproduction Steps

1. npm install msal-node
2. npm audit

### Expected Behavior

0 vulnerabilities detected

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Source

External (Customer)

**Comment by tnorling** [comment]
This was addressed by #5503 and a new version of msal-node will be released next week.
