### ISSUE TITLE
Does the redirect URL have to be same domain?

### ISSUE THREAD

**Issue by camer314** [AzureAD/microsoft-authentication-library-for-js#5527]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.32.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

I am trying to incorporate MSAL 2 authentication into a PowerApps custom component. PowerApps does not have a stable reply url so I was wondering if any url you have control over will suffice?

So far I created a test node.js web application with the recommended blank.html page and I have added that url to the AAD reply url list. However I am getting error **monitor_window_timeout**

If I try and do a popup logon I see the iframe gets the redirect to my blank page but then it never gets further than that.

How does that redirect url work in practice? My assumption was that MSAL would consume the redirect message from AAD and extract the code from it, but it seems like it gets passed through to the browser to do a physical redirect. If that is the case how does MSAL get the code?

Is there any hope for me to get a stable URL, with silent SSO, that is not part of my current domain?

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by bmahall** [comment]
@camer314 thanks for opening this issue! What are you using as redirecturi?

**Comment by camer314** [comment]
@bmahall 

I am just using a blank page url from a web app I control but not the domain of where I am using it from.

For example, if I am in the PowerApps authoring environment, **window.location.ref** is:

https://authoring.uk-il102.gateway.prod.island.powerapps.com/v3.22122.15.245107243/embed/

And if I use that as my redirectUri then MSAL works fine. But that url has some variable content so is not guaranteed to remain static, which I have no control over. So I thought maybe I could use a url from a website I own, for example:

https://xxx.azurewebsites.net/blank.html

**Comment by bmahall** [comment]
Thanks @camer314 for providing further information, the redirect URL needs to be on same domain.
