### ISSUE TITLE
[Help] MSAL failing to retrieve new/refreshed token in local development after expiration

### ISSUE THREAD

**Issue by terrenceferguson** [AzureAD/microsoft-authentication-library-for-js#5528]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.28.3

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Confidential

### Description

After the token expires from AAD, the app fails to refresh/fetch a new token, which results in the call to graph API failing due to a Bad Token (expired).

For reference, I'm using the following platform:
> .NET 7 Blazor WASM Standalone Azure AAD

If I manually delete the token from the local storage, it will retrieve it correctly. I haven't really noticed the issue when the app is published to our DEV server. I'm not sure if I have something configured incorrectly, or if there's an actual issue here.

### Error Message

![image](https://user-images.githubusercontent.com/19277507/210412646-db1039e6-6808-44ca-b4fa-c06e1c0fb3c2.png)

![image](https://user-images.githubusercontent.com/19277507/210412815-2fef51dc-1c0e-429d-a8cc-81ded5f8870e.png)

### Msal Logs

> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:54 GMT] : @azure/msal-browser@2.28.3 : Verbose - handleRedirectPromise called
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:54 GMT] : @azure/msal-browser@2.28.3 : Verbose - getAllAccounts called
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:54 GMT] : @azure/msal-browser@2.28.3 : Info - Emitting event: msal:handleRedirectStart
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:54 GMT] : @azure/msal-browser@2.28.3 : Verbose - handleRedirectPromise has been called for the first time, storing the promise
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:54 GMT] : [bc8bf137-eb3c-4e58-9856-8a8d050d25f9] : msal.js.browser@2.28.3 : Verbose - initializeServerTelemetryManager called
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:54 GMT] : [bc8bf137-eb3c-4e58-9856-8a8d050d25f9] : msal.js.browser@2.28.3 : Info - handleRedirectPromise called but there is no interaction in progress, returning null.
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:54 GMT] : @azure/msal-browser@2.28.3 : Info - Emitting event: msal:handleRedirectEnd
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:54 GMT] : @azure/msal-browser@2.28.3 : Verbose - getAllAccounts called
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : @azure/msal-browser@2.28.3 : Verbose - getAllAccounts called
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       Provisioning a token silently for scopes 'https://graph.microsoft.com/User.Read'
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : @azure/msal-browser@2.28.3 : Verbose - preflightBrowserEnvironmentCheck started
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : @azure/msal-browser@2.28.3 : Verbose - acquireTokenSilent called
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : @azure/msal-browser@2.28.3 : Verbose - acquireTokenSilent called for the first time, storing active request
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : @azure/msal-browser@2.28.3 : Info - Emitting event: msal:acquireTokenStart
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : @azure/msal-browser@2.28.3 : Verbose - acquireTokenSilent - attempting to acquire token from web flow
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - Initializing BaseAuthRequest
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - Authentication Scheme wasn't explicitly set in request, defaulting to "Bearer" request
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - initializeServerTelemetryManager called
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - getClientConfiguration called
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - getDiscoveredAuthority called
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - Creating discovered authority with configured authority
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - Silent auth client created
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : @azure/msal-common@7.4.1 : Info - SilentFlowClient:acquireCachedToken - Cached access token is expired or will expire within 300 seconds.
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : @azure/msal-browser@2.28.3 : Info - Emitting event: msal:acquireTokenFromNetworkStart
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - Initializing BaseAuthRequest
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - Authentication Scheme set to "Bearer" as configured in Auth request
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - initializeServerTelemetryManager called
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - getClientConfiguration called
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - getDiscoveredAuthority called
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - Creating discovered authority with configured authority
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - Refresh token client created
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : @azure/msal-browser@2.28.3 : Verbose - Refresh token expired or invalid, attempting acquire token by iframe
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - acquireTokenByIframe called
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - initializeAuthorizationRequest called
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - getRedirectUri called
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - Initializing BaseAuthRequest
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - Authentication Scheme set to "Bearer" as configured in Auth request
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - Setting validated request account
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - initializeServerTelemetryManager called
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - getClientConfiguration called
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - getDiscoveredAuthority called
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - Creating discovered authority with configured authority
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - Auth code client created
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : msal.js.browser@2.28.3 : Verbose - initializeAuthorizationRequest called
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:19:55 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : @azure/msal-common@7.4.1 : Verbose - createAuthCodeUrlQueryString: Adding login_hint from account
> The thread 0xe has exited with code 0 (0x0).
> The program '' has exited with code 4294967295 (0xffffffff).
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:20:01 GMT] : @azure/msal-browser@2.28.3 : Info - Emitting event: **msal:acquireTokenFailure**
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:20:01 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : @azure/msal-browser@2.28.3 : Verbose - PerformanceClient: Measurement found for acquireTokenSilent
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:20:01 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : @azure/msal-browser@2.28.3 : Verbose - PerformanceClient: Submeasurement for acquireTokenSilent already exists for standardInteractionClientGetDiscoveredAuthority, ignoring
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:20:01 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : @azure/msal-browser@2.28.3 : Verbose - PerformanceClient: Submeasurement for acquireTokenSilent already exists for standardInteractionClientGetDiscoveredAuthority, ignoring
> dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
>       [Tue, 03 Jan 2023 17:20:01 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : @azure/msal-browser@2.28.3 : Verbose - PerformanceClient: Emitting performance events

### MSAL Configuration

```javascript
builder.Services.AddMicrosoftGraphClient("https://graph.microsoft.com/User.Read");

builder.Services.AddMsalAuthentication(options =>
{
    builder.Configuration.Bind("AzureAd", options.ProviderOptions.Authentication);
    options.ProviderOptions.DefaultAccessTokenScopes.Add("https://graph.microsoft.com/openid");
    options.ProviderOptions.DefaultAccessTokenScopes.Add("https://graph.microsoft.com/profile");
    options.ProviderOptions.DefaultAccessTokenScopes.Add("https://graph.microsoft.com/User.Read");

    options.ProviderOptions.Cache.CacheLocation = "localStorage";
    options.ProviderOptions.LoginMode = "redirect";
});
```

### Relevant Code Snippets

```razor
LoginDisplay.razor

<AuthorizeView>
    <NotAuthorized>
        <MudButton Variant="Variant.Filled" Color="Color.Primary" OnClick="@(() => Navigation.NavigateToLogin("authentication/login"))">Login</MudButton>
    </NotAuthorized>
    <Authorized>
        <MudTooltip Duration="1000" Text="@($"Hello, {_user?.DisplayName}!")">
                    <MudAvatar Class="mt-2"
                        Rounded="true"
                               Size="Size.Medium"
                               Image="@(@$"data:image/jpeg;base64,{_imgSrc}")">
                    </MudAvatar>
                </MudTooltip>
        <MudButton Class="ml-4" Variant="Variant.Filled" Color="Color.Secondary" OnClick="BeginSignOut">Logout</MudButton>
    </Authorized>
</AuthorizeView>

@code {

    [CascadingParameter]
    Task<AuthenticationState> authenticationStateTask { get; set; } = default!;

    private User? _user;
    private string? _imgSrc;

    protected override async Task OnInitializedAsync()
    {
        if (authenticationStateTask is not null)
        {
            var auth = await authenticationStateTask;

            var qq = authenticationStateTask.Result;

            if (auth.User.Identity?.IsAuthenticated ?? false)
            {
                _user = await GraphClient.Me.Request().GetAsync();

                using (var photoResponse = await GraphClient.Me.Photo.Content.Request().GetResponseAsync())
                {
                    if (photoResponse != null)
                    {
                        _imgSrc = Convert.ToBase64String(await photoResponse.Content.ReadAsByteArrayAsync());
                    }
                }
            }
        }
    }

    private void BeginSignOut(MouseEventArgs args)
    {
        Navigation.NavigateToLogout("authentication/logout");
    }
}
```
RedirectToLogin.razor
```razor
@using Microsoft.AspNetCore.Components.WebAssembly.Authentication;
@using Microsoft.Extensions.Options

@inject NavigationManager Navigation
@inject IOptionsSnapshot<RemoteAuthenticationOptions<ApiAuthorizationProviderOptions>> Options

@code {
    protected override void OnInitialized()
    {
        Navigation.NavigateToLogin(Options.Get(
            Microsoft.Extensions.Options.Options.DefaultName)
            .AuthenticationPaths.LogInPath);
    }
}
```
Authentication.razor
```razor
@layout LoginLayout
@page "/authentication/{action}"
@using Microsoft.AspNetCore.Components.WebAssembly.Authentication

<RemoteAuthenticatorView Action="@Action">
    <LoggingIn>
        Custom login screen...
    </LoggingIn>

    <LogInFailed>
        
    </LogInFailed>
    
    <LogOutSucceeded>
        Custom logout screen...
    </LogOutSucceeded>
</RemoteAuthenticatorView>

@code{
    [Parameter] public string? Action { get; set; }
}
```

### Reproduction Steps

1. Authenticate to Blazor WASM App in local development.
2. Let token expire (usually happens after an extended period of time, such as stopping work for the night and coming back in the morning).
3. Relaunch the app in local development

### Expected Behavior

I expected the AuthenticationStateTask.User.IsAuthenticated to return false on token expiration, but it doesn't. The property remains true even after expiration.

I would also expect the app upon seeing an expired token to automatically redirect to login, acquire a new token, and log the user in.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

External (Customer)

**Comment by bmahall** [comment]
@terrenceferguson Are you falling back to an interactive method when an error occurs on token expiry? Can you share fiddler trace on the email on my Github profile?

**Comment by terrenceferguson** [comment]
> @terrenceferguson Are you falling back to an interactive method when an error occurs on token expiry? Can you share fiddler trace on the email on my Github profile?

I'll try to get that fiddler trace for you ASAP.

As far as "falling back to an interactive method" is concerned, I'm not exactly sure what you mean? Are you asking if I've created a custom method to monitor token expiration? If so, the answer would be no, seeing as I would assume that wouldn't be necessary; for two reasons in particular:

I'm not using a framework external to MS to implement authentication.
And in my 20+ hours of research into this issue, I have never seen any official documentation (or otherwise) stating that a custom method is always required to handle token expiration when implementing AAD authentication from Blazor WASM Standalone.

**Comment by ghost** [comment]
This issue requires attention from the MSAL.js team and has not seen activity in **5 days**. @bmahall please follow up.

**Comment by terrenceferguson** [comment]
Any news on this? Still having the issue, and it actually extends to the server instance as well (not just localhost).

**Comment by sameerag** [comment]
@terrenceferguson Is there a fiddler trace? Can you send it to me (email available in my [profile](https://github.com/sameerag))?

**Comment by terrenceferguson** [comment]
@sameerag I've forwarded you the same trace I sent @bmahall

**Comment by sameerag** [comment]
Ack the log. Will reach out.

**Comment by terrenceferguson** [comment]
The issue still persists.

**Comment by sscots** [comment]
I'm having a similar issue with acquireTokenSilent() is returning an expired token. I've tried it with both the Default and AccessTokenAndRefreshToken cache lookup policy and both still return an expired token.

**Comment by tnorling** [comment]
@terrenceferguson Can you share your MSAL usage? I don't see any of our APIs being called in the code snippets you shared above. Generally speaking if a silent token call fails with an InteractionRequired error, as it appears from your logs is the case here, you need to invoke an interactive token API (acquireTokenRedirect or acquireTokenPopup) to resolve.

**Comment by terrenceferguson** [comment]
> @terrenceferguson Can you share your MSAL usage? I don't see any of our APIs being called in the code snippets you shared above. Generally speaking if a silent token call fails with an InteractionRequired error, as it appears from your logs is the case here, you need to invoke an interactive token API (acquireTokenRedirect or acquireTokenPopup) to resolve.

I don't have any manual MSAL usage. As I mentioned above, this is all done through the Microsoft Identity Platform configuration option in a Blazor WASM application created in Visual Studio. Everything at a baseline was automatically configured. The only changes I've made to the implementation are using localStorage and loginMode redirect. I have coworkers that are using the same implementation, but they do not have this issue (albeit they're on .NET 6).

I have spent several hours looking for documentation that would indicate that I'm required to manually resolve an expired token with this configuration, and have found nothing to support that. I would understand if it were a manual implementation through a different front end framework, but my expectation in this case was that an expired token would automatically be resolved since everything I'm using is .NET.

If you can share the documentation that shows that I need to manually invoke the interactive token API, that would be great.

**Comment by tnorling** [comment]
Can you please share a link to the documentation for what you're using. I'm not familiar with your scenario, the MSAL.js team does not own anything Blazor or .NET related.

**Comment by terrenceferguson** [comment]
> Can you please share a link to the documentation for what you're using. I'm not familiar with your scenario, the MSAL.js team does not own anything Blazor or .NET related.

This is (more or less) what I've followed:

[Secure an ASP.NET Core Blazor WebAssembly standalone app with Azure Active Directory](
https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-azure-active-directory?view=aspnetcore-7.0)

**Comment by tnorling** [comment]
It doesn't look like this uses MSAL.js so I'm not sure we're going to be the best team to help you with this. There's some instructions at the [bottom of the page](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-azure-active-directory?view=aspnetcore-7.0#common-errors) for getting support with this. Looks like they recommend opening issues [here](https://github.com/dotnet/aspnetcore/issues)

**Comment by chris1411** [comment]
We had the same issue when updating our Blazor project to dotnet 7. The Blazor MSAL auth is reporting that the user is still authenticated even after a token expires and does not attempt to refresh. We were able to get around it by reverting the Microsoft.Authentication.WebAssembly.Msal package to version 6.0.15.

**Comment by terrenceferguson** [comment]
> It doesn't look like this uses MSAL.js so I'm not sure we're going to be the best team to help you with this. There's some instructions at the [bottom of the page](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-azure-active-directory?view=aspnetcore-7.0#common-errors) for getting support with this. Looks like they recommend opening issues [here](https://github.com/dotnet/aspnetcore/issues)

Gotcha. I'll recreate the issue there.

> We had the same issue when updating our Blazor project to dotnet 7. The Blazor MSAL auth is reporting that the user is still authenticated even after a token expires and does not attempt to refresh. We were able to get around it by reverting the Microsoft.Authentication.WebAssembly.Msal package to version 6.0.15.

I'll try this @chris1411 thanks for the recommendation.

**Comment by sameerag** [comment]
Closing this as this isn't an MSAL JS issue.
