### ISSUE TITLE
AuthZ code not being cleared after redirect

### ISSUE THREAD

**Issue by ayushman2609** [AzureAD/microsoft-authentication-library-for-js#5532]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.30.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

There are two deployments: Deployment 1 and Deployment 2.
If I set Deployment 2 as the redirect for Deployment 1, then after redirection I see AuthZ code, client_info, session_state, etc information in the address bar of Deployment 2.
If I set redirect to themselves then there is no such information.

### MSAL Configuration

```javascript
export const msalConfig = {
  auth: {
    clientId: "clientid",
    authority: "https://login.microsoftonline.com/common",
    redirectUri: process.env.REACT_APP_REDIRECT_URL,
    postLogoutRedirectUri: process.env.REACT_APP_REDIRECT_URL,
  },
  cache: {
    cacheLocation: "localStorage", // This configures where your cache will be stored
    storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
  },
};
```

### Relevant Code Snippets

```javascript
const getAccounts = () => {
    const currentAccounts = msalInstance.getAllAccounts();

    if (currentAccounts.length === 0) {
      // no accounts signed-in, attempt to sign a user in
      msalInstance.loginRedirect(loginRequest);
    } else if (currentAccounts.length > 1) {
      // Add choose account code here
      setAccount(msalInstance.getAccountByUsername(currentAccounts[0].username));
      setUsername(currentAccounts[0].username);
      setIsAuthenticated(true);
    } else if (currentAccounts.length === 1) {
      setAccount(msalInstance.getAccountByUsername(currentAccounts[0].username));
      setUsername(currentAccounts[0].username);
      setIsAuthenticated(true);
    }
  }

  const handleResponse = (response) => {
    if (response !== null) {
      setAccount(response.account);
      setUsername(response.account.username);
      setIsAuthenticated(true);
    } else {
      getAccounts();
    }
  }


  const signIn = () => {
    return msalInstance.handleRedirectPromise().then(handleResponse).catch(err => console.log(err));
  }
```

### Reproduction Steps

There are two deployments: Deployment 1 and Deployment 2.
If I set Deployment 2 as the redirect for Deployment 1, then after redirection I see AuthZ code, client_info, session_state, etc information in the address bar of Deployment 2.
If I set redirect to themselves then there is no such information.

### Expected Behavior

Address bar to be cleared of all the extra information

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

Internal (Microsoft)

**Comment by bmahall** [comment]
@ayushman2609 Thanks for raising this issue, I am able to reproduce this on my instance and will get back to you. 
I have a few questions:- 
Where are you calling loginRedirect() in your code?
Are you able to successfully login when you set Deployment 2 as redirect Url? Please ensure you have msal instance running on your redirect url. 

Also, please ensure that the redirect URI used is configured in the portal registration. You can also set the redirect URI per request using the [login](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/login-user.md) and [request APIs](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/acquire-token.md).

**Comment by derisen** [comment]
@ayushman2609 @bmahall just to chime in -I think this would be expected. If you initiate `loginRedirect` from deployment1, and then end up on deployment2 after redirect, the relevant temporary cache entries are not set on deployment2, so msal on deployment2 doesn't know if it should process the hash. May I ask why you need this arrangement? (also keep in mind that your redirect uris must be on the same domain with the initiating app)

**Comment by ayushman2609** [comment]
@bmahall Please find the answers to the questions:
_Where are you calling loginRedirect() in your code?_
It is called on page load
_Are you able to successfully login when you set Deployment 2 as redirect Url? Please ensure you have msal instance running on your redirect url._
Yes, log in is working fine. It's just these extra parameters in the address bar which is a concern.

**Comment by ayushman2609** [comment]
@derisen So the Deployment 1 and Depoyment 2 have the same code. We are planning on putting them behind a traffic manager and this traffic manager endpoint will be used by users and this traffic manager endpoint will be set as the redirect URL in MSAL as well. My concern and the scenario I was testing for was if the user's initial request resolves to Deployment 1 when the user opens the URL and then after the redirection they end up on Deployment 2 for some reason

**Comment by ayushman2609** [comment]
@bmahall, Any update?

**Comment by derisen** [comment]
@ayushman2609 one thing you can do is to [use a state parameter](https://learn.microsoft.com/en-us/azure/active-directory/develop/reply-url#use-a-state-parameter) to store the url before redirect, and then after redirect retrieve and parse the state parameter to compare it with where you end up. If they are not the same but sign-in is successful, you can manually clear the hash. See also [this](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2139) for a similar use case.

Didn't had a chance to reproduce your issue yet (please share if you have a public repro), but just to confirm, in the snippet you share, are you invoking `signIn()` on page load since that calls `handleRedirectPromise`?
