### ISSUE TITLE
React sample implementation to use updated version of React router (v.6+)

### ISSUE THREAD

**Issue by georgiosApo** [AzureAD/microsoft-authentication-library-for-js#5535]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL React (@azure/msal-react)

### Public or Confidential Client?

Public

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/typescript-sample

### Description

Hello all!

It would be great to have an up to date implementation sample for MSAL with react router v6+.

V6 has been out for a minute and it would be great to see a best practice implementation with this version.

Is this in the roadmap perhaps? Would be a great addition to this already nice documentation.

I'm still in the process of migrating, don't feel I got the knowledge just yet to make a PR on this topic.

Links to other sources with information on the matter is also very welcome.
Thanks a bunch in advance!

// G

**Comment by derisen** [comment]
@georgiosApo good idea, will put this in the backlog and keep the issue open until -in the meantime, you can [check this one](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/tree/main/2-Authorization-I/1-call-graph) out which uses v6, but I'm afraid its not a typescript implementation (also doesn't make use of custom navigation client)

cc @bmahall taking this over
