### ISSUE TITLE
With multiple mailboxes added to Outlook, SSO does not work for non-default mailboxes 

### ISSUE THREAD

**Issue by Iso5786** [AzureAD/microsoft-authentication-library-for-js#5537]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.30.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

By implementing the provided example to add authentication towards Azure (https://github.com/OfficeDev/Office-Addin-Taskpane-SSO/blob/master/src/helpers/fallbackauthdialog.ts) I expect that if a user has several mailboxes added to her Outlook instance, that the correct user of the selected mailbox is authenticated.
In my case the default mailbox is from ru.nl, and second and third from outlook.com.

I also tried to add logic to set the active account to the currently selected one by passing the account via a URL param to the fallback auth dialog.

By looking at the provided examples within this project, I found the following:
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-browser-samples/TypescriptTestApp2.0/src/AuthModule.ts#L120

So it seems that my issue is known and will be implemented in the future?

(create similar issue within [Office-Addin-Taskpane-SSO](https://github.com/OfficeDev/Office-Addin-Taskpane-SSO) repo but don't get response (https://github.com/OfficeDev/office-js/issues/3314).

### Error Message

'{"error":{"code":"ErrorNonExistentMailbox","message":"No mailbox with such guid.","innerError":{"date":"2023-01-09T12:22:19","request-id":"40116152-054d-4515-a67c-cb56619b3b35","client-request-id":"40116152-054d-4515-a67c-cb56619b3b35"}}}'

### MSAL Configuration

```javascript
const msalConfig: Configuration = {
  auth: {
    clientId: 'clientId'
  },
  cache: {
    cacheLocation: 'localStorage', // Needed to avoid "User login is required" error.
    storeAuthStateInCookie: true // Recommended to avoid certain IE/Edge issues.
  }
}
```

### Relevant Code Snippets

```javascript
Office.onReady(async () => {
  if (Office.context.ui.messageParent) {
    publicClientApp
      .handleRedirectPromise()
      .then(handleResponse)
      .catch((error) => {
        console.log(error)
        Office.context.ui.messageParent(
          JSON.stringify({ status: 'failure', result: error })
        )
      })

    const urlParams = new URLSearchParams(window.location.search)
    const currentAccountMail = urlParams.get('currentAccountMail')
    localStorage.setItem('authCurrentMail', currentAccountMail)

    const allAccountsurrentAccount: AccountInfo[] =
      publicClientApp.getAllAccounts()
    const accountObj: AccountInfo = allAccountsurrentAccount.find((acc) =>
      findMyAcc(acc, currentAccountMail)
    )
    publicClientApp.setActiveAccount(accountObj)

    // The very first time the add-in runs on a developer's computer, msal.js hasn't yet
    // stored login data in localStorage. So a direct call of acquireTokenRedirect
    // causes the error "User login is required". Once the user is logged in successfully
    // the first time, msal data in localStorage will prevent this error from ever hap-
    // pening again; but the error must be blocked here, so that the user can login
    // successfully the first time. To do that, call loginRedirect first instead of
    // acquireTokenRedirect.
    if (localStorage.getItem('loggedIn') === 'yes') {
      publicClientApp.acquireTokenRedirect(loginRequest)
    } else {
      // This will login the user and then the (response.tokenType === "id_token")
      // path in authCallback below will run, which sets localStorage.loggedIn to "yes"
      // and then the dialog is redirected back to this script, so the
      // acquireTokenRedirect above runs.
      publicClientApp.loginRedirect(loginRequest)
    }
  }
})
```

### Reproduction Steps

1. Add serveral mailboxes to Outlook
2. Use the addon with the primary mailbox to receive an authentication token
3. Try to use the addon with other mailboxes and receive the error as the token received is for the account of the primary mailbox.

### Expected Behavior

I would expect that the "setActiveAccount" method would set the account to request a token for to the one passed via the parameter.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Source

External (Customer)

**Comment by hectormmg** [comment]
@Iso5786 thanks for raising the issue. The "Add choose account code..." comment is a note to the developer indicating that that is where the account picking logic should go, it's not a TODO for the library to add that behavior. The `setActiveAccount` API is the way MSAL can be told which account to fetch tokens for as you understood. It seems like your issue is more with the way the fallback auth dialog handles multiple accounts.

**Comment by sameerag** [comment]
@Iso5786 Suggestion is to track your accounts or fetch them using `getAllAccounts` and pass the corresponding account to MSAL JS through `setActiveAccount`. 

Closing this. Please raise a new issue if this does not solve it for you.
