### ISSUE TITLE
How does SSO work between domains

### ISSUE THREAD

**Issue by Klukies** [AzureAD/microsoft-authentication-library-for-js#5538]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.32.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

Hey 👋

I've been trying to get SSO working for our application, however this does not seem to work.
For context, I'm creating a web component which is responsible solely for loggin the user and requesting the user's information. This functionality is already provided and is working as intended.

Currently I'm trying to achieve SSO. As the web component can be deployed between multiple domains. I believe it should be possible for the user to log in on domain A, navigate to domain B and use the `ssoSilent` function in order for the user not to have to click the login button or be prompted to fill in their email/password again.

However I can't get this function to work, as I constantly get the following error: `User does not have an existing session and request prompt parameter has a value of 'None'.`. I'm simulating the SSO behaviour by just locally clearing my localStorage after a successful login.

I don't believe there's a way for my to get access to a login hint of the user as the user is on different domains.

### MSAL Configuration

```javascript
{
    authority: 'custom-sign-in-policy',
    clientId: 'clientId',
    knownAuthorities: 'custom-authorities',
    navigateToLoginRequestUrl: false,
    postLogoutRedirectUri: '/',
    redirectUri: '/',
  },
  cache: {
    cacheLocation: BrowserCacheLocation.LocalStorage,
  },
}
```

### Relevant Code Snippets

```javascript
async getAccessToken() {
  const { accessToken } = await this.#publicClientApplication.acquireTokenSilent({
    scopes: this.#scopes,
  });

  return accessToken;
}
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by hectormmg** [comment]
Hi @LukasCornille thanks for raising the issue.

If there's no hint, the SSO is achieved using a cookie set by eSTS. However, this can only be done if there is exactly one account signed in, given that eSTS has no way of telling which account you're trying to get tokens for.

**Comment by Klukies** [comment]
Thanks for you answer, however I'm only testing SSO with a single account. Is there something specific I have to change regarding my configuration? Maybe the signIn policy I have needs to be a specific one in order for the `ssoSilent` to work?

Because even if I'm only logged in with a single user, I still get the error I've described above, which doesn't seem like the proper error if I'm already logged in.

The only thing I'm doing is logging in, clearing my cache (session or local storage) and then reloading the page. I would assume calling the `ssoSilent` function should work at that point.

**Comment by Klukies** [comment]
I just wanted to update this real quick, it seems that the `ssoSilent` seems to work in Chrome, but not in Firefox or Safari.
This probably has to do with the fact that [third party cookies are blocked](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-js-sso#third-party-cookies).

However I still get this error: `User does not have an existing session and request prompt parameter has a value of 'None'.` instead of the one provided in [the docs](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-js-sso#third-party-cookies). So there's no way for my component to know that the issue is related to the third party cookies and not the fact that the user isn't logged in. The only way to get SSO working from this point is first using `ssoSilent` and then `loginRedirect` with `prompt: none`, however this doesn't seem like wanted behaviour as this will cause redirects for every user regardless if they are logged in or not.

**Comment by hectormmg** [comment]
@LukasCornille this seems like it could be a B2C service issue since the `ssoSilent` flow is optimized for eSTS. Please file a support ticket with the B2C team by following the instructions [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options). Thank you.

**Comment by Klukies** [comment]
Hey, it appears that it's just a browser issue. I still get other issues though when I've actually published my component.
This time it's related to the silent iframe performing a `http` request on a `https` domain, even if the the redirect uri is set to https 😅

**Comment by hectormmg** [comment]
@LukasCornille thanks for the update, closing since it's not an MSAL bug
