### ISSUE TITLE
Every time authenticating a user needs to "Approve sign in request" via MS Authenticator app

### ISSUE THREAD

**Issue by Iso5786** [AzureAD/microsoft-authentication-library-for-js#5539]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.30.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

Not sure if this is an issue within msal-browser.

If I do a sign in request via msal within my Outlook addin (taken from https://github.com/OfficeDev/Office-Addin-Taskpane-SSO/blob/master/src/helpers/fallbackauthdialog.ts) as I want to request the Graph API afterwards I need to approve the sign in request every time I want to get a token via msal.
For an end-user this is not desirable, as we developed an addon for email encryption / decryption and it is to burdensome for a user to use the auth app every time she wishes to use the addon.

So am wondering if this is a) an issue within msal or some other lib from MS b) an issue within my addon c) a config issue within my tenant.

### MSAL Configuration

```javascript
const msalConfig: Configuration = {
  auth: {
    clientId: clientId,
    authority: 'https://login.microsoftonline.com/common',
    redirectUri: `https://${window.location.host}/fallbackauthdialog.html`, // Update config script to enable `https://${window.location.host}/fallbackauthdialog.html`,
    navigateToLoginRequestUrl: false
  },
  cache: {
    cacheLocation: 'localStorage', // Needed to avoid "User login is required" error.
    storeAuthStateInCookie: true // Recommended to avoid certain IE/Edge issues.
  }
}
```

### Relevant Code Snippets

```javascript
const loginRequest: RedirectRequest = {
  scopes: [
    'Mail.ReadBasic',
    'Mail.Read',
    'Mail.ReadWrite',
    'Mail.Send',
    'openid',
    'profile',
    'offline_access'
  ],
  prompt: 'select_account'
}



const publicClientApp: PublicClientApplication = new PublicClientApplication(
  msalConfig
)

Office.onReady(async () => {
  if (Office.context.ui.messageParent) {
    publicClientApp
      .handleRedirectPromise()
      .then(handleResponse)
      .catch((error) => {
        console.log(error)
        Office.context.ui.messageParent(
          JSON.stringify({ status: 'failure', result: error })
        )
      })

    //const urlParams = new URLSearchParams(window.location.search)
    //const currentAccountMail = urlParams.get('currentAccountMail')
    //localStorage.setItem('authCurrentMail', currentAccountMail)

    //const allAccountsurrentAccount: AccountInfo[] =
    //  publicClientApp.getAllAccounts()
    //const accountObj: AccountInfo = allAccountsurrentAccount.find((acc) =>
    //  findMyAcc(acc, currentAccountMail)
    //)

    setAuthLog('After handling promise ...')

    //publicClientApp.setActiveAccount(accountObj)

    // The very first time the add-in runs on a developer's computer, msal.js hasn't yet
    // stored login data in localStorage. So a direct call of acquireTokenRedirect
    // causes the error "User login is required". Once the user is logged in successfully
    // the first time, msal data in localStorage will prevent this error from ever hap-
    // pening again; but the error must be blocked here, so that the user can login
    // successfully the first time. To do that, call loginRedirect first instead of
    // acquireTokenRedirect.
    if (localStorage.getItem('loggedIn') === 'yes') {
      publicClientApp.acquireTokenRedirect(loginRequest)
    } else {
      // This will login the user and then the (response.tokenType === "id_token")
      // path in authCallback below will run, which sets localStorage.loggedIn to "yes"
      // and then the dialog is redirected back to this script, so the
      // acquireTokenRedirect above runs.
      publicClientApp.loginRedirect(loginRequest)
    }
  }
})
```

### Reproduction Steps

1. Register an addon within a tenant where MFA is enabled.
2. Try to get a token via msal-browser.
3. Approve sign-in request via Auth app.

### Expected Behavior

At least desired behavior is that not every time the user needs to approve the sign-in request but maybe once a day.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Other

### Source

External (Customer)

**Comment by hectormmg** [comment]
@Iso5786 thanks for raising the issue. If you want to acquire a token without interaction, please look into using `acquireTokenSilent` instead of redirect.

Our documentation for MSAL Browser shows the correct usage pattern, first trying to acquire silently and then falling back to interactive token acquisition if there are no tokens in the cache.

**Comment by Iso5786** [comment]
@hectormmg It seems to work. Indeed, I just had to use `acquireTokenSilent`.
