### ISSUE TITLE
How to use renewToken?

### ISSUE THREAD

**Issue by josephd9** [AzureAD/microsoft-authentication-library-for-js#554]
We have run into an issue with token renewal. Our application checks every 15 minutes if the token is fresh and if not performs a silent acquire. This trouble is if the token expires and the window for renewal hasn't arrived then request with the expired token fails. I'm trying to implement the clientApplication.renewToken every 45 minutes instead and just force a refresh before expiration but I have no idea how to invoke it. What other parameters does it require?

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: v0.2.0

## Minimal reproduction of the problem with instructions

</code></pre>

**Comment by sameerag** [comment]
@josephd9 renewToken is a private function and you are not supposed to use it. ATS(acquireTokenSilent) within itself takes care of the expired token as long as you have a valid session. There is an internal variable _clockSkew(which we do plan to make public and settable) which has a 300sec expiry setting to call the server 5 min before the token expires. If you want a specific offset you can experiment with the same to account for any time difference.

If ATS is failing with expired token, it could be a bug. Can you please share some sample code and the failure logs for us to have a better understanding of what is really going on here?

**Comment by navyasric** [comment]
@josephd9 Please note MSAL.js provides the acquireTokenSilent method to renew tokens. Please use this method to renew tokens. The method makes a request to renew the token and can return a valid token if the user session is maintained with Azure AD (read [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes#single-sign-on-session-tokens) for more details on user's session).  If the user session has expired, the acquireTokenSilent will fail and you need to handle the failure by calling the interactive methods(acquireTokenPopup or acquireTokenRedirect).

**Comment by josephd9** [comment]
I didn't know that it would refresh the token on its own. I created an iframe that calls acquireTokenSilent every 15 min. Could that be causing this issue? After 1 hour I attempted to use the token even after the acquireTokenSilent had taken place and the token still got rejected as unauthorized until I manually hit refresh on the browser. Does this sound like a defect of the code or something wrong with our sessions?

The Code

`
var clientApplication;

var myAuth = {
    refreshInterval: null,
    authIframe : $('<iframe name="id" name="authIframe" src=""></iframe>', { css: { 'display': 'none' } }),

    initialize: function (Audience, azureTenant, azureAADInstance, redirectURI) {      
       
        window.config = {      
            clientID: Audience,
            tenant: azureTenant,
            AADInstance: azureAADInstance,
            redirectURI: redirectURI
        };
        function authCallback(errorDesc, token, error, tokenType) {           
            //This function is called after loginRedirect and acquireTokenRedirect. Not called with loginPopup
            // msal object is bound to the window object after the constructor is called.
            if (token) {
                console.log('Auth Load Successful');
            }
            else {
                console.log("AuthError", error, ":", errorDesc);
            }
        }

        if (!clientApplication) {
            clientApplication = new Msal.UserAgentApplication(window.config.clientID, window.config.AADInstance + window.config.tenant, authCallback, { redirectUri: window.config.redirectURI, cacheLocation: 'localStorage' });
        }
    },

    loginSuccess: function (successFun) {
            var scope = [window.config.clientID];

            try {
                if (clientApplication.getCachedToken({ scopes: scope }, clientApplication.getUser()) != null) {
                    clientApplication.acquireTokenSilent(scope)
                        .then(function (token) {
                            $.ajaxSetup({
                                headers: {
                                    'Authorization': 'Bearer ' + token
                                },
                            });
                            if (successFun != null)
                                successFun();
                        });
                } else {
                    clientApplication.loginRedirect(scope);
                }
            } catch (e) {
                clientApplication.loginRedirect(scope);
            }
    },

    checkLogin: function (successFun) {
        if (!clientApplication.getUser()) {
            var scope = [window.config.clientID];
            //clientApplication.loginPopup(scope).then(successLoginIn);
            clientApplication.loginRedirect(scope);
        } else {
            myAuth.removeIframe();

            if (myAuth.refreshInterval != null) {
                console.log('refreshInterval removed');
                myAuth.refreshInterval == null;
                clearInterval(myAuth.refreshInterval);
            }

            myAuth.refreshInterval = setInterval(myAuth.refreshToken, 1000 * 60 * 5);              
            myAuth.loginSuccess(successFun);
        }
    },

    isLoggedIn: function () {
        if (!clientApplication.getUser()) {
            return false;
        } else {
            return true;
        }
    },

    refreshToken: function () {
        try {
            var scope = [window.config.clientID];
            clientApplication.acquireTokenSilent(scope)
                .then(function (token) {
                    console.log('Token is fresh');
                });
        } catch (e) {
            console.log('Token is stail');

            if ($('.authIframe').length > 0)
                myAuth.removeIframe();   
            
            console.log('Add Iframe');       
            $('body').append(myAuth.authIframe);
        }       
    }, 

    removeIframe: function () {
        if ($('.authIframe').length > 0) {
            $('.authIframe').remove();
            console.log('Iframe removed');
        }
    },

    signout: function () {
        clientApplication.logout();
    },
};
`

**Comment by josephd9** [comment]
It just occurred to me that I'm never reassigning the new token to the ajax headers. lol this is probably the issue. i'll test and report back.

**Comment by josephd9** [comment]
Yup it was my fault! Many thanks!

**Comment by sameerag** [comment]
@josephd9 Also acquireTokenSilent() is handled in a hidden iframe. So may be you need not create an iframe of your own. Just test it out and see if it works for you.

**Comment by sameerag** [comment]
@josephd9 Of course unless you need the iframe for other bookkeeping.

**Comment by josephd9** [comment]
@sameerag In this instance I feel like I need to use the iframe because we need to use ajaxSetup on the auth header and I don't know how we'd be able to detect when the aquireTokenSilent completed a refresh.
