### ISSUE TITLE
msal-browser: Unable to login into AngularJS application

### ISSUE THREAD

**Issue by lkmbUser** [AzureAD/microsoft-authentication-library-for-js#5549]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

Not Applicable

### Wrapper Library Version

NA

### Public or Confidential Client?

Public

### Description

We are unable to login into java script application by migrating authentication from adal.js to msal.js

### Error Message

Error is logging in catch block of HnadleRedirectResponse method

ClientAuthError: state_not_found: State not found:  Cached State
    at t [as constructor] (msal.js:417:26)
    at new t (msal.js:573:23)
    at t.createStateNotFoundError (msal.js:597:20)
    at n.<anonymous> (msal.js:4038:136)
    at msal.js:116:31
    at Object.next (msal.js:127:18)
    at msal.js:49:41
    at new Promise (<anonymous>)
    at o (msal.js:29:16)
    at n.handleCodeResponse (msal.js:4030:20)

### Msal Logs

@azure/msal-browser@2.14.2 : Info - Emitting event: msal:handleRedirectStart
@azure/msal-browser@2.14.2 : Verbose - handleRedirectPromise called
@azure/msal-browser@2.14.2 : Verbose - getAllAccounts called
@azure/msal-browser@2.14.2 : Verbose - handleRedirectPromise has been called for the first time,storing the promise
@azure/msal-browser@2.14.2 : Verbose - getRedirectResponseHash called
@azure/msal-browser@2.14.2 : Verbose - Hash contains known properties, returning response hash
@azure/msal-browser@2.14.2 : Verbose - validateAndExtractStateFromHash called
@azure/msal-browser@2.14.2 : Verbose - Returning state from hash
@azure/msal-browser@2.14.2 : Verbose - State extracted from hash
@azure/msal-browser@2.14.2 : Verbose - NavigateToLoginRequestUrl set to false, handling hash
@azure/msal-browser@2.14.2 : Verbose - handleHash called
@azure/msal-browser@2.14.2 : Verbose - initializeServerTelemetryManager called
@azure/msal-browser@2.14.2 : Verbose - createAuthCodeClient called
@azure/msal-browser@2.14.2 : Verbose - getClientConfiguration called
@azure/msal-browser@2.14.2 : Verbose - getDiscoveredAuthority called
@azure/msal-browser@2.14.2 : Verbose - Creating discovered authority with request authority
@azure/msal-browser@2.14.2 : Info - Emitting event: msal:loginFailure
@azure/msal-browser@2.14.2 : Info - Emitting event: msal:handleRedirectEnd
 ClientAuthError: state_not_found: State not found:  Cached State
    at t [as constructor] (msal.js:417:26)
    at new t (msal.js:573:23)
    at t.createStateNotFoundError (msal.js:597:20)
    at n.<anonymous> (msal.js:4038:136)
    at msal.js:116:31
    at Object.next (msal.js:127:18)
    at msal.js:49:41
    at new Promise (<anonymous>)
    at o (msal.js:29:16)
    at n.handleCodeResponse (msal.js:4030:20)
(anonymous) @ 

### MSAL Configuration

```javascript
const msalInstance = new msal.PublicClientApplication({
        auth: {
            authority: "",
            clientId: "",
            postLogoutRedirectUri: "",
            navigateToLoginRequestUrl: false
        },
        cache: {
            cacheLocation: "localStorage",
            storeAuthStateInCookie: true
        },
       system: {
            loggerOptions: {
                loggerCallback(loglevel, message, containsPii) {
                    console.log(message);
                },
                piiLoggingEnabled: false,
                logLevel: msal.LogLevel.Verbose,
            }
        }
    });;
```

### Relevant Code Snippets

```javascript
const loginRequest = {
        scopes: ["openid", "profile", "User.Read"],
        extraQueryParameters: "" 
    };
 let interactionstatus = null;
    let msalInteractionStatus = "msal." + "clientId" + ".interaction.status=interaction_in_progress";
    if (document.cookie.contains(msalInteractionStatus)) {
        interactionstatus = "interaction_in_progress";
    }

msalInstance.handleRedirectPromise()
            .then((tokenResponse) => {
                if (tokenResponse) {
                    msalInstance.setActiveAccount(tokenResponse.account);
                }
            })
            .catch(err => {
                console.error(err);
            });
msalInstance.addEventCallback((event) => {
                if ((event.eventType === "msal:loginSuccess" || event.eventType === "msal:acquireTokenSuccess") && event.payload.account) {
                    const account = event.payload.account;
// Code to use token and land on application home page
             }

var token = null;
   if ((token === null || token === undefined) && interactionstatus === null) {
                msalInstance.loginRedirect(loginRequest);
            }
```

### Reproduction Steps

1. User clicks on Login button
2. User credentials are automatically taken from browser profile
3. Msal:Login start event will occur
4. #code is returned in URL from msal 
5. Error is logged in console
6. ClientAuthError: state_not_found: State not found:  Cached State
    at t [as constructor] (msal.js:417:26)
    at new t (msal.js:573:23)
    at t.createStateNotFoundError (msal.js:597:20)
    at n.<anonymous> (msal.js:4038:136)
    at msal.js:116:31
    at Object.next (msal.js:127:18)
    at msal.js:49:41
    at new Promise (<anonymous>)
    at o (msal.js:29:16)
    at n.handleCodeResponse (msal.js:4030:20)

### Expected Behavior

1. Login success event should occur
2. User should land on application home page by using token returned in Login success event payload

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer

### Source

Internal (Microsoft)

**Comment by hectormmg** [comment]
@lkmbUser thanks for raising the issue.  Why are you looking at the MSAL cookies for interaction in progress? You don't need to check the status yourself since MSAL handles that. Also, MSAL will use the clientID value, not the string "clientId" for the cookies so the logic you're using wouldn't access the right cookie.

Could you please provide verbose logs of this error so we can better diagnose it?

**Comment by lkmbUser** [comment]
@hectormmg : In our application before completion of first login event it was again raising login start event. To avoid this we are checking interaction status in cookies and it's referring to correct cookie.

let msalInteractionStatus = "msal." + "clientId" + ".interaction.status=interaction_in_progress";

here" clientid" is the application client id.

I have shared logs MsalLogs section of this issue.

Thank you.

**Comment by hectormmg** [comment]
@lkmbUser the `stateNotFound` error is an indicator that the cache has been modified since login was called. Can you see if the temporary cache items set before the redirect are still there when the app comes back? If they're missing or changed, that means something is interfering with the cache.

**Comment by sameerag** [comment]
@lkmbUser Can you please link this issue to a new one with more logs after you confirm that the usage is as suggested?  Closing this as Hector explained the flow above.
