### ISSUE TITLE
Support for response_type=code

### ISSUE THREAD

**Issue by roalonso** [AzureAD/microsoft-authentication-library-for-js#555]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Library version

<pre><code>
Library version: 0.2.4
</code></pre>

## Current behavior
I find no way to pass the parameter described in
https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-protocols-oauth-code.
If I try using `extraQueryParameters` described in the [wiki](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Public-APIs) then I get an error screen with:
```
AADSTS9000411: The request is not properly formatted. The parameter 'response_type' is duplicated.
```
because the value is hardcoded to `id_token` without checking if it was set by extra parameters.

## Expected behavior
Some way to set the `response_type` query parameter.

## Minimal reproduction of the problem with instructions
When doing the above, this is the screen I get:
<img width="481" alt="screen shot 2019-02-06 at 6 33 38 pm" src="https://user-images.githubusercontent.com/6528419/52387187-0d3dbe80-2a3e-11e9-8a4c-add45df8a6ad.png">

**Comment by sameerag** [comment]
@roalonso MSAL JS being implicit flow support only, does not support the developer to set response_type as per design. All login requests are by default of response_type=id_token and the acquireToken calls set them as per the context, cookie status, login_hint etc. 

Can you also let us know what is the use case you may need this? That may help us get a better insight to determine if our current model supports your case.

@navyasric  can you please confirm this?

**Comment by navyasric** [comment]
@roalonso Adding to above comment, please not that MSAL.js supports only the [Implicit flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-implicit-grant-flow) for client side browser based JS apps such as SPAs. Therefore, it defaults to the response_type=id_token for login and response_type=token for acquireToken calls.

**Comment by roalonso** [comment]
@sameerag I see. Are there any libraries supporting the OAuth 2.0 code grant flow? My use case is that of a backend which obtains the a code from a web page after a user authorizes my app. All processing is done by the backend. The only purpose of the web app (related to the Graph API) is requesting user authorization.

I'm currently generating the URL manually, but I started rewriting everything and thought it was a good opportunity to switch to a library instead.
