### ISSUE TITLE
Front-Channel logout - is it really possible using MSAL.js?

### ISSUE THREAD

**Issue by melmanm** [AzureAD/microsoft-authentication-library-for-js#5552]
### Core Library

MSAL.js v2 (@azure/msal-browser), MSAL.js v1 (@azure/msal or msal)

### Wrapper Library

MSAL React (@azure/msal-react)

### Public or Confidential Client?

Public

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md#front-channel-logout

### Description

In attached documentation there is a description of front-channel logout mechanism. 

I will refere to [react-router sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/react-router-sample) mentioned in this section to explain the issue. 

In [logout](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-react-samples/react-router-sample/src/pages/Logout.jsx) page there is a code that uses `logoutRedirect` function. `logoutRedirect` should clear user information from browser cache. In [authConfig](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-react-samples/react-router-sample/src/authConfig.js) cache location is configured as `cacheLocation: "localStorage"`.

Logout page is intended to be loaded in iframe by IdP, during front-channel logout. However, localStorage can be accessed only from applicaiton domain, not from IdP domain. In my opinion the only way to make it working is to place IdP and application in exact same domain (subdomains won't work for localStorage as well).

Is that correct?

**Comment by hectormmg** [comment]
@melmanm thanks for the question! MSAL clears the auth artifacts from `localStorage` independently from the session being ended on the front-channel iframe.

**Comment by melmanm** [comment]
@hectormmg thank you very much for response! I didnt see this behavior before due to some missconfiguration in my app. Now it works as intended and localStorage is cleared. 🚀 I am just wondering how it works underneath so it is possible to clear localStorage after iframe call from different domain?

**Comment by hectormmg** [comment]
@melmann localStorage is actualy cleared before the iframe is created and navigated to the front-channel logout URL i believe

**Comment by melmanm** [comment]
@hectormmg i investigated this issue a bit and it seems i have not been fully aware of how localStorage works. I thought it behavies simmilar to cookies but localStorage entries are thighten to domain and cannot be accesed if domain is iframed.

In reality, in iframe context, localStorage (at least in chrome) behavies like cookies, moreover it is controlled by „allow third party cookies” browser option. 

In result /logout endpoint can clear localStorage even its called from iframe.

Thank you for your support. I think we can close the issue.

**Comment by kevinvugts** [comment]
> @hectormmg i investigated this issue a bit and it seems i have not been fully aware of how localStorage works. I thought it behavies simmilar to cookies but localStorage entries are thighten to domain and cannot be accesed if domain is iframed.

Hi Hector,

Can you elaborate more on this topic? I am trying to create a system consisting of 2 react apps. Both use the MSAL/react and MSAL/browser libraries. 

Using front-channel feature in the app registrations I am trying to logout from all subsystems if the user logs out. I see that the GET request is being made via iframe and console.logs are appearing from the app that initiates the log out request. 

However, when navigating to the app 2 (that needs to be logged out as well) the session is still in place. I have an active issue, but haven't received any replies yet.

Maybe you could help me along the way since you questioned this mechanism as well.

Issue: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/6597
