### ISSUE TITLE
MSAL-Browser External URI not showing up as expected

### ISSUE THREAD

**Issue by plogmanAustinPFG** [AzureAD/microsoft-authentication-library-for-js#5553]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.19.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.1.2

### Public or Confidential Client?

Public

### Description

Hello, I am having an issue while trying to login via localhost. There is a registered app for a SPA with the URL of "http://localhost:{port}/#/page" and when I try to login it is setting the external_uri to "http://localhost:{port}/". I am expecting the redirect_uri to be "http://localhost:{port}/#/page" as that is the page I am on. When I manually set the external_uri in the config is also still doesn't work. Any insight into this problem would be nice. Thanks!

### MSAL Configuration

```javascript
const config: Configuration = {
	auth: {
		clientId: process.env.clientId ?? "",
		authority: process.env.tenantId ?? ""
                externalUri: "http://localhost:{port}/#/page"   <<< external_uri comes out as just "http://localhost:{port}/" so it says it doesn't match with the application on azure
		},
	cache: {
		cacheLocation: "sessionStorage",
		storeAuthStateInCookie: false,
	},
	system: {
		loggerOptions: {
			loggerCallback: (level, message, containsPii) => {
				if (containsPii) {
					return;
				}
				switch (level) {
					case LogLevel.Error:
						console.error(message);
						return;
					case LogLevel.Warning:
						console.warn(message);
						return;
				}
			},
		},
	},
};
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by hectormmg** [comment]
@plogmanAustinPFG MSAL doesn't have an attribute called `external_uri`. The config attribute should be called `redirectUri` and it should have the same value as the one registered on the Azure Portal.

**Comment by plogmanAustinPFG** [comment]
> @plogmanAustinPFG MSAL doesn't have an attribute called `external_uri`. The config attribute should be called `redirectUri` and it should have the same value as the one registered on the Azure Portal.

I was referring to the URL that shows up, it has the param of external_uri. I do have these two URL's matching but for some reason it doesn't like the /#/page at the end. The Azure portal has http://localhost:{port}/#/page and with and without setting the externalUri to match, it thinks it is http://localhost:{port}/ so it fails.

Here is the error:
```AADSTS500112: The reply address 'http://localhost:{port}/#/page' does not match the reply address 'http://localhost:{port}/'```

**Comment by hectormmg** [comment]
With the exception of the port, the URL has to match exactly. You cannot use a variable URI for this. What you can do is the following:

1. Have a set redirectUri like localhos:{port}/auth
2. Before initiating redirec token request, add the window.location.href to the request config as the `state` attribute
3. In the /auth page, once the redirect is handled, get the location from the state and navigate back to the page you were in


Does that help?
