### ISSUE TITLE
Clarify navigating back with respect to redirect authentication flow

### ISSUE THREAD

**Issue by aforemny** [AzureAD/microsoft-authentication-library-for-js#5562]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.28.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

Hi!,

we are using msal-browser's redirect authentication flow, and I have the following question regarding the back navigation of the browser, that I could not find an answer about.

Suppose I am performing the following steps:

- I am interactively authenticating via redirect, and everything works as expected. I get redirected back to the application (website) and I am logged in.
- Now, I am pressing the browser's back button, which takes me back to the sign in page. This sign in page either, depending on configuration, automatically redirects me back to the redirect url, or it re-requires interactive authentication, ie. entering username and password, and then redirects me back to the redirect url.
- In either case, msal-browser will refuse to handle the redirect url containing the hash, because there is no interaction in progress. It seems the interaction has been consumed by the first successful redirect.

Assuming this is clear, and I've stated things correctly, I would like to ask for clarification how a client application should handle this situation:

- The application is not set up to handle the redirect url, because it expects msal-browser to navigate away from this url to a url that the application is set up to handle. Currently, the application shows a "not found" page on the redirect url.
  - I could show an error message that states that this page is invalid because of authentication, but that seems unsatisfactory as well.
- Is it possible to configure msal-browser to retain information about the previous interaction, and redirect again as in the first successful authentication, either retaining the old login information, or replacing it with the new one?
  - If not, is it possible to obtain the redirect url from the hash, to then let the application perform the necessary redirect without having to maintain this piece of state itself?

Thanks!

### MSAL Configuration

```javascript
{
  authority: `https://${tenant}.b2clogin.com/${tenant}.onmicrosoft.com/${policy}`,
  clientId,
  knownAuthorities: [ "${knownAuthority}" ],
  scopes: [
    clientId,
    "offline_access"
  ]
}
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by hectormmg** [comment]
@aforemny thanks for the question.

1. Techincally speaking, navigating backwards after login is not supported by MSAL. What I mean by that is there's not much that MSAL can do to mitigate the behavior without some drastic changes.
2. A possible workaround would be for your app to leverage the token request `state` parameter. That means you would add the redirect location to the state on the initial request. After hitting "back" the state will still be in the URL hash, were your app can read it and redirect manually.

**Comment by aforemny** [comment]
> 2. A possible workaround would be for your app to leverage the token request `state` parameter. That means you would add the redirect location to the state on the initial request. After hitting "back" the state will still be in the URL hash, were your app can read it and redirect manually.

@hectormmg Thank you for your reply! That sounds like the solution I am looking for!

First I've realized that because of the way `state` works, I have to decode `state` manually from the URL, as you've stated: the `state` passed to `loginRedirect` is only available from a successful invocation of `handleRedirectPromise`, which is not available when navigating back. Neither `getAllAccounts` or `aquireTokenSilent` and `ssoSilent` are able to get at the original `state` passed to `loginRedirect`.

Digging through the code, I am realizing that the user state is appended to the URL hash's state field, separated by `|` from the library state.

- Is there some way to get at the user state from the URL's hash via the library? Or else, is the structure of the URL hash's state field documented somewhere, so that I can rely on that?
  - I've found `BrowserProtocolUtils`' `extractBrowserRequestState`, but that requires me to pass `browserCrypto: ICrypto`. It is not immediately clear to me how I could obtain such an instance.

Thanks!

**Comment by tnorling** [comment]
Just to confirm I understand the scenario correctly: your redirectUri further redirects the user to a different page in your app (such as the page they started on) but when going back and logging in again this 2nd redirect doesn't happen. Is that correct?

If I have that right, you should either: 

1. Redirect the user to a predefined page, such as your homepage
2. Keep track of the page you want to land on yourself and use that to redirect the user back to the correct page.

I would not suggest decoding state manually as you've correctly come to the conclusion that the raw format is an implementation detail of the library.
