### ISSUE TITLE
SSO between different apps not working when trying using loginhint

### ISSUE THREAD

**Issue by garvraj** [AzureAD/microsoft-authentication-library-for-js#5564]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.22.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.1.2

### Public or Confidential Client?

Public

### Description

I have an application where I already signed in , I am using the same configuration like below

    clientId: environment.clientId,
    authority: b2cPolicies.authorities.signUpSignIn.authority,
    knownAuthorities: [b2cPolicies.authorityDomain],
    redirectUri: environment.redirectUri,
    
    The requirement is to implement single signon when I logged in to application1 and when  I am trying to access application2, application 2 should get all the account details without asking to sign in again

### Error Message

BrowserAuthError: monitor_window_timeout: Token acquisition in iframe failed due to timeout. For more visit: aka.ms/msaljs/browser-errors.

### Msal Logs

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/41892368/212079550-1b1c977f-d321-44fd-8fac-eb4352919fdd.png">

### MSAL Configuration

```javascript
Configuration = {
  auth: {
    clientId: environment.clientId,
    authority: b2cPolicies.authorities.signUpSignIn.authority,
    knownAuthorities: [b2cPolicies.authorityDomain],
    redirectUri: '/',
    postLogoutRedirectUri: '/'
  },
  cache: {
    cacheLocation: BrowserCacheLocation.LocalStorage,
    storeAuthStateInCookie: isIE, // Set this to "true" if you are having issues on IE11 or Edge
  },
  system: {
    loggerOptions: {
      loggerCallback(logLevel: LogLevel, message: string) {
        console.log(message);
      },
      logLevel: LogLevel.Verbose,
      piiLoggingEnabled: false
    },
    iframeHashTimeout: 10000,
  }
}
```

### Relevant Code Snippets

```javascript
This code snippet I am using in application2 to check if user is already logged in in the browser or not   

console.log( this.authService.instance.getActiveAccount()). // This is returning null

    const SsoSilentRequest = {
      loginHint: 'garvraj303@gmail.com' // I have added my static mail id which i used to login in application1
        }

Note : I even tried by providing domainHint and scopes also in above param

      this.authService.instance.ssoSilent(SsoSilentRequest).then((res) => {
        console.log(res)
    }).catch(error => {
        console.error("Silent Error: " + error);
    });
```

### Reproduction Steps

Need to create two different application with similar configuration

### Expected Behavior

I should get the loggedin user detail in res

      this.authService.instance.ssoSilent(SsoSilentRequest).then((res) => {
        console.log(res)
    }).catch(error => {
        console.error("Silent Error: " + error);
    });

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge

### Source

External (Customer)

**Comment by garvraj** [comment]
@iambmelt @i-am-dan @akuang @andreaswasita @antkmsft @antonafMSFT @baywet @bgavrilMS @dstrockis

**Comment by peterzenz** [comment]
@garvraj adding another 9 people to this issue won't get you a faster resolution.  An engineer has been assigned to review this and they will get back to you.

**Comment by hectormmg** [comment]
@garvraj does this happen every time? If so, it looks like it could be a B2C service issue. Please file a support ticket with the B2C team by following the instructions [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options).

**Comment by garvraj** [comment]
> @garvraj does this happen every time? If so, it looks like it could be a B2C service issue. Please file a support ticket with the B2C team by following the instructions [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options).

I will check and try to create a support ticket with the B2C team

**Comment by sameerag** [comment]
@garvraj Please create a new issue after you follow up with the B2C service and still think it is an MSAL JS issue.
