### ISSUE TITLE
400 Bad Request after signout on multiple tabs

### ISSUE THREAD

**Issue by joostmeijles** [AzureAD/microsoft-authentication-library-for-js#5565]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.32.2

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.5.2

### Public or Confidential Client?

Public

### Description

I can only login on one browser tab after signing out on multiple browser tabs.

Steps to reproduce:
1. Sign in to application
2. Open second tab with application (implicit sign in)
3. Sign out on one tab using `logoutRedirect`.
4.  Other tab(s) sign out automatically using `loginRedirect`
5. Sign in on the tab where the logout took place succeeds
6. Sign in on the other tab(s) fails with `Failed to load resource: the server responded with a status of 400 (Bad Request)`

### MSAL Configuration

```javascript
auth: {
      clientId: import.meta.env.VITE_AUTH_CLIENT_ID,
      authority: import.meta.env.VITE_AUTH_AUTHORITY,
      knownAuthorities: [import.meta.env.VITE_AUTH_KNOWN_AUTHORITY],
      requiredScope: import.meta.env.VITE_AUTH_REQUIRED_SCOPE,
      redirectUri: window.location.origin
},
cache: {
      cacheLocation: 'localStorage', // This configures where your cache will be stored
      storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
},
system: {
      loggerOptions: {
        loggerCallback: (
          level: LogLevel,
          message: string,
          containsPii: boolean,
        ) => {
          if (containsPii) {
            return;
          }
          switch (level) {
            case LogLevel.Error:
              // eslint-disable-next-line no-console
              console.error(message);
              return;
            case LogLevel.Info:
              // eslint-disable-next-line no-console
              console.info(message);
              return;
            case LogLevel.Verbose:
              // eslint-disable-next-line no-console
              console.debug(message);
              return;
            case LogLevel.Warning:
              // eslint-disable-next-line no-console
              console.warn(message);
              return;
            case LogLevel.Trace:
              console.debug(message);
              return;
          }
        },
        logLevel: LogLevel.Verbose,
      },
    },
```

### Relevant Code Snippets

```javascript
function MsalApp({ children }: MsalApp) {
  const { instance, inProgress } = useMsal();

  useEffect(() => {
    const callbackId = instance.addEventCallback(
      async (message: EventMessage) => {
        if (message.eventType === EventType.LOGIN_SUCCESS) {
          const payload = message.payload as AuthenticationResult;

          instance.setActiveAccount(payload.account);
        }
      },
    );

    return () => {
      if (callbackId) {
        instance.removeEventCallback(callbackId);
      }
    };
  });

return (
    <>
      <AuthenticatedTemplate>
        {/* Only render children when no MSAL interaction is in progress.
            This prevents (async) API calls from trying to obtain a MSAL token,
            while the token is not yet available. 
            When a token is not yet available it will fail and (re-)trigger 
            a login redirect, and this causes unwanted redirect login looping. */}
        {msalInteractionInProgress && children}
      </AuthenticatedTemplate>
      <UnauthenticatedTemplate>
        <SignIn />
      </UnauthenticatedTemplate>
    </>
  );
}

export function SignIn() {
  const { instance, inProgress } = useMsal();

  useEffect(() => {
    if (inProgress == InteractionStatus.None) {
      // Redirect user to Azure AD login
      instance.loginRedirect(authRequest);
    }
  }, [inProgress]);

  return <></>;
}

function SignOut() {
   return <button onClick={() => instance.logoutRedirect()}>Sign out</button>
}
```

### Identity Provider

Azure B2C Basic Policy

### Source

Internal (Microsoft)

**Comment by hectormmg** [comment]
@joostmeijles can you send a network trace captured with fiddler to the e-mail on my profile please? I'd like to look at the request that's causing the error so I can see what's going on.

**Comment by joostmeijles** [comment]
@hectormmg sent you a mail with the logs.

Please note that when I reload the login page (by hitting enter in the browser url box), the login succeeds (after providing the credentials).

**Comment by joostmeijles** [comment]
I am able to reproduce the error with a React sample application: https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/react-18-sample

Steps to reproduce:
- Open http://localhost:3000 in 2 browser tabs
- Sign in on a single tab
- Sign out on a single tab
- Click sign in on tab 1 using redirect (do not yet sign in)
- Click sign in on tab 2 using redirect (do not yet sign in)
- Try to sign in on tab 1 -> you will not be logged in

**Comment by tnorling** [comment]
Hi @joostmeijles I was not able to reproduce this with the steps you shared. Is this still an issue?

**Comment by joostmeijles** [comment]
@tnorling just tried the same steps with the latest version and I can still reproduce the issue.

**Comment by tnorling** [comment]
I have taken a look at your network trace and it appears this 400 is happening in the network requests which the B2C service or policy is making, not MSAL. I would suggest you [open a support ticket](https://learn.microsoft.com/en-us/azure/active-directory-b2c/support-options) with the B2C service who will be better able to troubleshoot this
