### ISSUE TITLE
Exception is thrown in acquireTokenByClientCredential if tenantId is missing 

### ISSUE THREAD

**Issue by Robbie-Microsoft** [AzureAD/microsoft-authentication-library-for-js#5567]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

2.14.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

N/A

### Public or Confidential Client?

Confidential

### Description

An exception should be thrown in AcquireTokenByCredential if "common" or "organization" are used in lieu of the tenant_id in the authority in the auth configuration. As it stands, using "common" or "organization" will work, but the behavior is undefined. AAD will try to guess the correct tenant_id, which is undesired behavior.

### MSAL Configuration

```javascript
auth: {
    clientId: "<ENTER_CLIENT_ID>",
    authority: "https://login.microsoftonline.com/<ENTER_TENANT_ID>",
    clientSecret: "<ENTER_CLIENT_SECRET>",
},
```

### Relevant Code Snippets

```javascript
N/A
```

### Reproduction Steps

N/A

### Expected Behavior

An exception should be thrown when using AcquireTokenByCredential if "common" or "organization" are used in the authority instead of the tenant_id.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Source

Internal (Microsoft)

**Comment by bgavrilMS** [comment]
The fix requires a breaking change.
