### ISSUE TITLE
ProxyUrl should be passed to msal-node's HttpClient via the constructor

### ISSUE THREAD

**Issue by Robbie-Microsoft** [AzureAD/microsoft-authentication-library-for-js#5568]
### Core Library

MSAL Node (@azure/msal-node)

### Wrapper Library

Not Applicable

### Public or Confidential Client?

Confidential

### Description

ProxyUrl should be passed to msal-node's HttpClient the same way a custom HttpAgent can be, as defined in [this ticket](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/5472). 

### Source

Internal (Microsoft)

**Comment by derisen** [comment]
@Robbie-Microsoft just for future reference, does this lead to an error or a certain behavior? Can we update the issue template if so?

**Comment by Robbie-Microsoft** [comment]
This does not lead to any errors. It's just a code improvement to match the implementation of the custom HttpAgent linked in the description.
