### ISSUE TITLE
react-router-sample throws "Can't resolve 'react-dom/client'" error

### ISSUE THREAD

**Issue by joostmeijles** [AzureAD/microsoft-authentication-library-for-js#5570]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.32.2

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.5.2

### Public or Confidential Client?

Public

### Description

After installing the sample using:
```
> npm run install:published
> npm run install
```

The react-router-sample sample app throws the following error when starting it:
```
> npm run start
```

![image](https://user-images.githubusercontent.com/4342282/212329590-b66fbc69-bf4c-48d5-aa36-914c16502d7b.png)

### Error Message

Failed to compile.

Module not found: Error: Can't resolve 'react-dom/client' in 'C:\Repos\microsoft-authentication-library-for-js\samples\msal-react-samples\react-router-sample\src'
ERROR in ./src/index.js 8:0-40
Module not found: Error: Can't resolve 'react-dom/client' in 'C:\Repos\microsoft-authentication-library-for-js\samples\msal-react-samples\react-router-sample\src'

webpack compiled with 1 error

### MSAL Configuration

```javascript
NA
```

### Relevant Code Snippets

```javascript
NA
```

### Reproduction Steps

1. `npm run install:published`
2. `npm run start`

### Expected Behavior

Run without errors.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by derisen** [comment]
@joostmeijles looks like you haven't installed the rest of the dependencies. Can you run "npm install" and try again? (both npm install:published and npm install needed)

**Comment by joostmeijles** [comment]
I did run `npm install` (updated that in the description), unfortunately still the same error.

**Comment by derisen** [comment]
@joostmeijles my bad, I see now that install:published installs react v17 whereas it should have been 18, i.e.: 

> `"install:published": "npm install @azure/msal-browser@latest @azure/msal-react@latest react@^18 react-dom@^18"`

Will make a PR to fix that (you're also welcome to do so)
