### ISSUE TITLE
Window is not defined.

### ISSUE THREAD

**Issue by ajhstn** [AzureAD/microsoft-authentication-library-for-js#558]
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report  
- [ ] Performance issue
- [ ] Feature request
- [ ] Documentation issue or request
- [X] Other... Please describe:

I don't think my issue is either of the above, probably more so my lack of understanding.

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX
- [X] Terminal/Console, no  browser, UI

## Library version

Library version: 0.2.4

## Current behavior

When the browser storage is set, and i am not using a browser?

## Expected behavior

I want to use MSAL in console only Msal.UserAgentApplication object

## Minimal reproduction of the problem with instructions

Save this js to index.js.  Install the msal module.  run index.js

```
const Msal = require('msal')
var applicationConfig = {
  clientID: "<clientID>",
  authority: "https://login.microsoftonline.com/<guid>"
};

var myMSALObj = new Msal.UserAgentApplication(applicationConfig.clientID, applicationConfig.authority, acquireTokenRedirectCallBack, {storeAuthStateInCookie: true, cacheLocation: "localStorage"});

function acquireTokenRedirectCallBack(errorDesc, token, error, tokenType) {}
```

**Comment by annikahanna** [comment]
I have the same issue with my azure function. Is there a different library which is also supporting non-Single-Page Apps?

**Comment by mdwe** [comment]
I have the same issue in NativeScript application - Window context is not available. 

`System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException:

System.err: Error calling module function

System.err: ReferenceError: Window is not defined`

**Comment by DarylThayil** [comment]
Msal is oriented around user login flows and so it is expected to be run in a browser.
We do have an Adal [node lib](https://github.com/AzureAD/azure-activedirectory-library-for-nodejs)

I am new to the team, but from what I understand msal node is on the horizon.  @navyasric  do you have insight into the roadmap?

**Comment by navyasric** [comment]
As mentioned above by DarylThayil, MSAL.js is designed to be used in client side JavaScript running in a web browser such as in case of single page apps. 
For your console application, you may want to take a look at [MSAL .Net](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki#details-on-the-ways-to-acquire-tokens). If your application is built in Node.js, we don't have concrete timelines to share on the plans for MSAL Node.js as yet. 
You can also find a list of the libraries we offer [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-v2-libraries). Closing this issue.

**Comment by ajhstn** [comment]
For those interested i have a working nodejs console app against the Microsoft Graph, based off the https://github.com/microsoftgraph/nodejs-apponlytoken-rest-sample
