### ISSUE TITLE
loginPopup interaction_in_progress error

### ISSUE THREAD

**Issue by data-handler** [AzureAD/microsoft-authentication-library-for-js#5591]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.32.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

N/A

### Public or Confidential Client?

Public

### Description

I am receiving an interaction_in_progress error when attempting to log in the user via the loginPopup function.

I am using the graph wrapper (@microsoft/microsoft-graph-client) by providing my own authProvider class.

The login popup is shown but the error is thrown before the user has a chance to enter their details.

Am I doing something wrong or is this a bug?

### MSAL Configuration

```javascript
{
    auth: {
        clientId: [my registered app id],
        authority: 'https://login.microsoftonline.com/[our azure tenant id]',
        redirectUri: 'http://localhost:3000', // this is set on our app registration in azure
    },
    cache: {
        cacheLocation: 'localStorage',
        storeAuthStateInCookie: false
    }
};
```

### Relevant Code Snippets

```javascript
const tokenRequest = {
    scopes: ['Calendars.ReadWrite.Shared', 'Mail.ReadWrite', 'Mail.Send'],
    forceRefresh: false
};

const loginRequest = {
    scopes: ['User.Read']
};

export default class {
    constructor() {
        this.client = new msal.PublicClientApplication(msalConfig);
    }

    async getAccessToken() {
        let token;
        await this.ensureClientAccount();

        try {
            const response = await this.client.acquireTokenSilent(tokenRequest);
            token = response.accessToken;
        } catch (error) {
            if (error instanceof msal.InteractionRequiredAuthError) {
                console.warn('silent token acquisition fails. acquiring token using popup');
                token = await this.acquireTokenByPopup();
            } else {
                console.warn(error);
            }
        }

        return token;
    }

    async ensureClientAccount() {
        if (this.client.getActiveAccount()) {
            return;
        }

        await this.setClientAccount();
    }

    async setClientAccount() {
        const currentAccounts = this.client.getAllAccounts();

        if (currentAccounts.length > 0) {
            this.client.setActiveAccount(currentAccounts[0]);
        } else {
            const account = await this.signIn();
            this.client.setActiveAccount(account);
        }
    }

    async signIn() {
        try {
            const response = await this.client.loginPopup(loginRequest);
            return response.account;
        } catch (error) {
            console.error(error); // interaction_in_progress error
        }
    }

    async acquireTokenByPopup() {
        try {
            const tokenResponse = await this.client.acquireTokenPopup(tokenRequest);
            return tokenResponse.accessToken;
        } catch (error) {
            console.error(error);
        }
    }
}
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@data-handler Can you please provide the following:
1. Your usage of the above snippets
2. The steps you are taking when you run into the error
3. Verbose logs

Please also take a look at [this FAQ](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/errors.md#interaction_in_progress) regarding this particular error.

**Comment by data-handler** [comment]
@jo-arroyo Thank you for getting back to me. Please see below:

1.
static getInstance() {
        if (!this.instance) {
            this.instance = new GraphClient();
            this.instance.client = Client.initWithMiddleware({
                authProvider: new MsalAuthentication()
            });
        }
        return this.instance;
    }

2.
A browser refresh fixes the issue

3.
index.js:24 [Mon, 23 Jan 2023 10:38:44 GMT] : @azure/msal-browser@2.32.0 : Info - Emitting event: msal:loginStart
index.js:24 [Mon, 23 Jan 2023 10:38:44 GMT] : @azure/msal-browser@2.32.0 : Info - Emitting event: msal:popupOpened
HTTPMessageHandler.js:23          GET https://graph.microsoft.com/v1.0/users/[removed]/calendarview?$select=subject,body,location,start,end&startdatetime=2023-01-23T07:00:00&enddatetime=2023-01-25T18:00:00 401 (Unauthorized)
(anonymous) @ HTTPMessageHandler.js:23
(anonymous) @ tslib.es6.js:76
It @ tslib.es6.js:72
execute @ HTTPMessageHandler.js:22
(anonymous) @ TelemetryHandler.js:56
(anonymous) @ tslib.es6.js:76
It @ tslib.es6.js:72
execute @ TelemetryHandler.js:30
(anonymous) @ RetryHandler.js:126
(anonymous) @ tslib.es6.js:76
It @ tslib.es6.js:72
executeWithRetry @ RetryHandler.js:125
(anonymous) @ RetryHandler.js:151
(anonymous) @ tslib.es6.js:76
It @ tslib.es6.js:72
execute @ RetryHandler.js:147
(anonymous) @ AuthenticationHandler.js:65
a @ tslib.es6.js:73
Promise.then (async)
c @ tslib.es6.js:75
(anonymous) @ tslib.es6.js:76
It @ tslib.es6.js:72
execute @ AuthenticationHandler.js:39
(anonymous) @ HTTPClient.js:74
(anonymous) @ tslib.es6.js:76
It @ tslib.es6.js:72
sendRequest @ HTTPClient.js:67
(anonymous) @ GraphRequest.js:281
(anonymous) @ tslib.es6.js:76
It @ tslib.es6.js:72
send @ GraphRequest.js:275
(anonymous) @ GraphRequest.js:526
(anonymous) @ tslib.es6.js:76
It @ tslib.es6.js:72
get @ GraphRequest.js:521
getCalendarAppointments @ index.js:26
build @ index.js:14
(anonymous) @ index.js:36
getSurveyorAppointments @ index.js:35
populateSurveyorAppointments @ index.js:26
build @ index.js:18
await in build (async)
populate @ app.js:58
(anonymous) @ app.js:20
Promise.then (async)
onmount @ app.js:19
s @ redom.es.js:169
s @ redom.es.js:183
s @ redom.es.js:183
s @ redom.es.js:183
s @ redom.es.js:183
(anonymous) @ redom.es.js:238
a @ redom.es.js:148
(anonymous) @ index.js:24
(anonymous) @ app.js:86
GraphErrorHandler.js:57 Uncaught (in promise) Error: CompactToken parsing failed with error code: 80049217
    at Do.constructErrorFromResponse (GraphErrorHandler.js:57:24)
    at Do.<anonymous> (GraphErrorHandler.js:81:44)
    at Generator.next (<anonymous>)
    at tslib.es6.js:76:71
    at new Promise (<anonymous>)
    at It (tslib.es6.js:72:12)
    at Do.getError (GraphErrorHandler.js:78:16)
    at Ro.<anonymous> (GraphRequest.js:299:56)
    at Generator.throw (<anonymous>)
    at s (tslib.es6.js:74:64)
constructErrorFromResponse @ GraphErrorHandler.js:57
(anonymous) @ GraphErrorHandler.js:81
(anonymous) @ tslib.es6.js:76
It @ tslib.es6.js:72
getError @ GraphErrorHandler.js:78
(anonymous) @ GraphRequest.js:299
s @ tslib.es6.js:74
Promise.then (async)
populate @ app.js:59
(anonymous) @ app.js:20
Promise.then (async)
onmount @ app.js:19
s @ redom.es.js:169
s @ redom.es.js:183
s @ redom.es.js:183
s @ redom.es.js:183
s @ redom.es.js:183
(anonymous) @ redom.es.js:238
a @ redom.es.js:148
(anonymous) @ index.js:24
(anonymous) @ app.js:86
HTTPMessageHandler.js:23          GET https://graph.microsoft.com/v1.0/users/[removed]/calendarview?$select=subject,body,location,start,end&startdatetime=2023-01-23T07:00:00&enddatetime=2023-01-25T18:00:00 401 (Unauthorized)
(anonymous) @ HTTPMessageHandler.js:23
(anonymous) @ tslib.es6.js:76
It @ tslib.es6.js:72
execute @ HTTPMessageHandler.js:22
(anonymous) @ TelemetryHandler.js:56
(anonymous) @ tslib.es6.js:76
It @ tslib.es6.js:72
execute @ TelemetryHandler.js:30
(anonymous) @ RetryHandler.js:126
(anonymous) @ tslib.es6.js:76
It @ tslib.es6.js:72
executeWithRetry @ RetryHandler.js:125
(anonymous) @ RetryHandler.js:151
(anonymous) @ tslib.es6.js:76
It @ tslib.es6.js:72
execute @ RetryHandler.js:147
(anonymous) @ AuthenticationHandler.js:65
a @ tslib.es6.js:73
Promise.then (async)
c @ tslib.es6.js:75
(anonymous) @ tslib.es6.js:76
It @ tslib.es6.js:72
execute @ AuthenticationHandler.js:39
(anonymous) @ HTTPClient.js:74
(anonymous) @ tslib.es6.js:76
It @ tslib.es6.js:72
sendRequest @ HTTPClient.js:67
(anonymous) @ GraphRequest.js:281
(anonymous) @ tslib.es6.js:76
It @ tslib.es6.js:72
send @ GraphRequest.js:275
(anonymous) @ GraphRequest.js:526
(anonymous) @ tslib.es6.js:76
It @ tslib.es6.js:72
get @ GraphRequest.js:521
getCalendarAppointments @ index.js:26
build @ index.js:14
(anonymous) @ index.js:36
getSurveyorAppointments @ index.js:35
populateSurveyorAppointments @ index.js:26
build @ index.js:18
await in build (async)
populate @ app.js:58
(anonymous) @ app.js:20
Promise.then (async)
onmount @ app.js:19
s @ redom.es.js:169
s @ redom.es.js:183
s @ redom.es.js:183
s @ redom.es.js:183
s @ redom.es.js:183
(anonymous) @ redom.es.js:238
a @ redom.es.js:148
(anonymous) @ index.js:24
(anonymous) @ app.js:86
HTTPMessageHandler.js:23          GET https://graph.microsoft.com/v1.0/users/[removed]/calendarview?$select=subject,body,location,start,end&startdatetime=2023-01-23T07:00:00&enddatetime=2023-01-25T18:00:00 401 (Unauthorized)
(anonymous) @ HTTPMessageHandler.js:23
(anonymous) @ tslib.es6.js:76
It @ tslib.es6.js:72
execute @ HTTPMessageHandler.js:22
(anonymous) @ TelemetryHandler.js:56
(anonymous) @ tslib.es6.js:76
It @ tslib.es6.js:72
execute @ TelemetryHandler.js:30
(anonymous) @ RetryHandler.js:126
(anonymous) @ tslib.es6.js:76
It @ tslib.es6.js:72
executeWithRetry @ RetryHandler.js:125
(anonymous) @ RetryHandler.js:151
(anonymous) @ tslib.es6.js:76
It @ tslib.es6.js:72
execute @ RetryHandler.js:147
(anonymous) @ AuthenticationHandler.js:65
a @ tslib.es6.js:73
Promise.then (async)
c @ tslib.es6.js:75
(anonymous) @ tslib.es6.js:76
It @ tslib.es6.js:72
execute @ AuthenticationHandler.js:39
(anonymous) @ HTTPClient.js:74
(anonymous) @ tslib.es6.js:76
It @ tslib.es6.js:72
sendRequest @ HTTPClient.js:67
(anonymous) @ GraphRequest.js:281
(anonymous) @ tslib.es6.js:76
It @ tslib.es6.js:72
send @ GraphRequest.js:275
(anonymous) @ GraphRequest.js:526
(anonymous) @ tslib.es6.js:76
It @ tslib.es6.js:72
get @ GraphRequest.js:521
getCalendarAppointments @ index.js:26
build @ index.js:14
(anonymous) @ index.js:36
getSurveyorAppointments @ index.js:35
populateSurveyorAppointments @ index.js:26
build @ index.js:18
await in build (async)
populate @ app.js:58
(anonymous) @ app.js:20
Promise.then (async)
onmount @ app.js:19
s @ redom.es.js:169
s @ redom.es.js:183
s @ redom.es.js:183
s @ redom.es.js:183
s @ redom.es.js:183
(anonymous) @ redom.es.js:238
a @ redom.es.js:148
(anonymous) @ index.js:24
(anonymous) @ app.js:86
HTTPMessageHandler.js:23          GET https://graph.microsoft.com/v1.0/users/[removed]/calendarview?$select=subject,body,location,start,end&startdatetime=2023-01-23T07:00:00&enddatetime=2023-01-25T18:00:00 401 (Unauthorized)
(anonymous) @ HTTPMessageHandler.js:23
(anonymous) @ tslib.es6.js:76
It @ tslib.es6.js:72
execute @ HTTPMessageHandler.js:22
(anonymous) @ TelemetryHandler.js:56
(anonymous) @ tslib.es6.js:76
It @ tslib.es6.js:72
execute @ TelemetryHandler.js:30
(anonymous) @ RetryHandler.js:126
(anonymous) @ tslib.es6.js:76
It @ tslib.es6.js:72
executeWithRetry @ RetryHandler.js:125
(anonymous) @ RetryHandler.js:151
(anonymous) @ tslib.es6.js:76
It @ tslib.es6.js:72
execute @ RetryHandler.js:147
(anonymous) @ AuthenticationHandler.js:65
a @ tslib.es6.js:73
Promise.then (async)
c @ tslib.es6.js:75
(anonymous) @ tslib.es6.js:76
It @ tslib.es6.js:72
execute @ AuthenticationHandler.js:39
(anonymous) @ HTTPClient.js:74
(anonymous) @ tslib.es6.js:76
It @ tslib.es6.js:72
sendRequest @ HTTPClient.js:67
(anonymous) @ GraphRequest.js:281
(anonymous) @ tslib.es6.js:76
It @ tslib.es6.js:72
send @ GraphRequest.js:275
(anonymous) @ GraphRequest.js:526
(anonymous) @ tslib.es6.js:76
It @ tslib.es6.js:72
get @ GraphRequest.js:521
getCalendarAppointments @ index.js:26
build @ index.js:14
(anonymous) @ index.js:36
getSurveyorAppointments @ index.js:35
populateSurveyorAppointments @ index.js:26
build @ index.js:18
await in build (async)
populate @ app.js:58
(anonymous) @ app.js:20
Promise.then (async)
onmount @ app.js:19
s @ redom.es.js:169
s @ redom.es.js:183
s @ redom.es.js:183
s @ redom.es.js:183
s @ redom.es.js:183
(anonymous) @ redom.es.js:238
a @ redom.es.js:148
(anonymous) @ index.js:24
(anonymous) @ app.js:86
index.js:24 [Mon, 23 Jan 2023 10:38:44 GMT] : [f06686de-cb2a-43d9-9aff-8483b6b36c15] : @azure/msal-common@9.1.0 : Info - in acquireToken call in auth-code client
index.js:24 [Mon, 23 Jan 2023 10:38:44 GMT] : @azure/msal-browser@2.32.0 : Info - Emitting event: msal:loginSuccess
index.js:24 [Mon, 23 Jan 2023 10:38:44 GMT] : @azure/msal-browser@2.32.0 : Info - Emitting event: msal:acquireTokenStart
index.js:24 [Mon, 23 Jan 2023 10:38:44 GMT] : @azure/msal-browser@2.32.0 : Info - Emitting event: msal:acquireTokenSuccess

**Comment by data-handler** [comment]
Update:

I believe I have found the issue.

I have been using Promise.all to await an array of Graph API call promises.

Each promise retrieves a list of calendar events by user id.

The first call to the Graph API was invoking MSAL authentication and loginPopup (if user not already signed in), but, of course, subsequent Graph API calls were made before authentication had completed.

If I make each Graph API call in sequence, the issue is resolved.

Is there a way to retrieve each user's calendar events in one API call, or is calling in sequence my only option?

**Comment by jo-arroyo** [comment]
@data-handler The usage and calling of Graph APIs is out of scope for our library, so please open an issue in the Graph wrapper repo [here](https://github.com/microsoftgraph/msgraph-sdk-javascript). MSAL.js is only responsible for getting the tokens that are requested.

**Comment by sameerag** [comment]
Closing this issue as appropriate guidance is provided. @data-handler Feel free to raise a new issue if you think MSAL JS can help once you talk to the graph team. One caveat I can add is that we do not support concurrent interactive calls but can support concurrent silent calls.

If graph team can help you with bundling multiple scopes into  a single auth request, we already support it. Else it could be out of our scope.

**Comment by data-handler** [comment]
Thank you for your help. In case anyone else wants similar functionality, it is possible to pass multiple user ids to the Graph API.
