### ISSUE TITLE
Login request redirect uri header is set to url with specific path for SPAs that do not use hash-based routing

### ISSUE THREAD

**Issue by austindyoung** [AzureAD/microsoft-authentication-library-for-js#56]
UserAgentApplication.redirectUri is hard coded as

```window.location.href.split("?")[0].split("#")[0]```,

which assumes that routing is hash-based (e.g. https://spa.com/#/path/to/page).

If the routing is non-hash-based, this results in the login request's "redirect-uri" header being set to whatever the specific SPA path is. If this is not the app's registered redirect URI (e.g. https://spa.com/#/asset/6), the subsequent authentication request will fail.

**Comment by prichter** [comment]
Following worked for me.  Not sure if this helps for hash-based routing...
`var UserAgentApplication = new Msal.UserAgentApplication('APP ID', null, function....{}
userAgentApplication.redirectUri = 'redirect URI here...`

**Comment by jmprieur** [comment]
Yes, @austindyoung: you can always set the redirectUri after the construction of UserAgentApplication. Does it work for you?

**Comment by austindyoung** [comment]
Yes, @jmprieur. This is what I did initially. However, it was a surprise to me that the client has to mutate the UserAgentApplication object whenever the app uses non-hash routing. I opened a PR in which redirectUri is included as an optional constructor parameter.
