### ISSUE TITLE
Invalid Issuer (iss: sts.windows.net) when acquiring token

### ISSUE THREAD

**Issue by mpalumbo7** [AzureAD/microsoft-authentication-library-for-js#560]
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report  
- [ ] Performance issue
- [ ] Feature request
- [ ] Documentation issue or request
- [x] Other... Please describe: Help

## Browser:
- [X] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version
Library version: `0.2.4`

## Current behavior

The acquired `access_token` appears to have the wrong issuer, and my ASP.NET Core API rejects the token due to `The issuer is invalid`. 

The decoded access token looks like:

```json
{
  "aud": "api://{clientId}",
  "iss": "https://sts.windows.net/{tenantId}/",
  ...
  "ver": "1.0"
}
```

Shouldn't the token issuer be: `https://login.microsoftonline.com/{tenantId}/v2.0`? Is this an issue with my Azure AD, or a MSAL.js configuration issue?

When I change to my API options to `o.TokenValidationParameters.ValidateIssuer = false;` it works fine. The registered app is meant to be isolated to a single AAD tenant.

## Expected behavior

The access token's issuer should be: `https://login.microsoftonline.com/{tenantId}/v2.0`

## Minimal reproduction of the problem with instructions

When I use MSAL.js to acquire token via:

```javascript
msal = new msal.UserAgentApplication(
      '{clientId}',
      'https://login.microsoftonline.com/{tenantId}',
      () => {},
      {
        redirectUri: 'http://localhost:3001/',
        storeAuthStateInCookie: true,
        cacheLocation: 'sessionStorage'
      }
    );

msal.acquireTokenSilent(['api://{cliend-id}/my-scope']).then(
      (accessToken) => {
        console.log(accessToken);
        return accessToken;
      },
      () => {
        // Open a redirect page in case the token is bad
       ...
      }
    );
```

The returned access token is:

```json
{
  "aud": "api://{clientId}",
  "iss": "https://sts.windows.net/{tenantId}/",
  ...
  "ver": "1.0"
}
```

When I use the accessToken to hit my ASP.NET Core Web API, I get a response with `error="invalid_token", error_description="The issuer is invalid"`.

When I configure the API to skip checking the issuer, the API calls works fine.

**Comment by mpalumbo7** [comment]
FYI - My `Startup.cs` looks like this:

```csharp
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

namespace r2dlcto.api
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddAuthentication(sharedOptions => 
            {
                sharedOptions.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
                sharedOptions.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            })
            // .AddAzureADBearer(options => Configuration.Bind("AzureAd", options));
            .AddJwtBearer(o =>
            {
                o.Audience = Configuration["AzureAd:Audience"]; 
                o.Authority = Configuration["AzureAd:Authority"];
                // TODO: When this is false, it works!
                o.TokenValidationParameters.ValidateIssuer = true;
            });

            services.AddCors();

            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseHsts();
            }

            // Very important that this is before MVC (or anything that will require authentication)            
            app.UseAuthentication();
            app.UseHttpsRedirection();
            app.UseCors(builder => builder
                .WithOrigins("http://localhost:3001") // TODO: Need to make configurable
                .WithHeaders("Authorization"));
            app.UseMvc();
        }
    }
}
```

**Comment by verbedr** [comment]
I don't think this is something that the msal library controls. If you check the token you will notice that Azure AD uses the sts.windows.net as the issuer identifier.  So use 'https://sts.windows.net/{tenantid}/' it will expose the same discovery document. Not sure in what scenario you would decouple this. Perhaps in a multi tenant system?

**Comment by navyasric** [comment]
As mentioned above, the iss claim is set by Azure AD in the tokens and represents the STS issuing the token as described [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens#payload-claims).
The library only returns the token received from the Identity provider (Azure AD in this case).

**Comment by mpalumbo7** [comment]
I believe this is a configuration issue in the Azure AD App Registration. There is a field called `accessTokenAcceptedVersion` then when left `null` defaults to v1.0. It must be changed to `2` so that tokens are generated in the v2.0 format.

**Comment by tinodo** [comment]
I am experiencing the same 'issue'.
The metadata endpoint for OpenID Connect that Azure AD exposes, for example: **https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/discovery/v2.0/keys** lists the **issuer** in the response:

{{
  "keys": [
    {
      "kty": "RSA",
      "use": "sig",
      "kid": "**u4OfNFPHwEBosHjtrauObV84LnY**",
      "x5t": "u4OfNFPHwEBosHjtrauObV84LnY",
      "n": "oRRQG-...MIg30Hqgw",
      "e": "AQAB",
      "x5c": [
        "MIIDBTCCAe2...U/ceH6AW"
      ],
      "issuer": "**https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/v2.0**"
    },
    {
      "kty": "RSA",
      "use": "sig",
      "kid": "ie_qWCXhXxt1zIEsu4c7acQVGn4",
      "x5t": "ie_qWCXhXxt1zIEsu4c7acQVGn4",
      "n": "68tx...jwoCDb3Q",
      "e": "AQAB",
      "x5c": [
        "MIIDB...wSbiSryT2SUk"
      ],
      "issuer": "**https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/v2.0**"
    },
    {
      "kty": "RSA",
      "use": "sig",
      "kid": "M6pX7RHoraLsprfJeRCjSxuURhc",
      "x5t": "M6pX7RHoraLsprfJeRCjSxuURhc",
      "n": "xHScZMP...tfpWr3hFRdpxrwuoQEO4QQ",
      "e": "AQAB",
      "x5c": [
        "4iotvXDWDBWx9...PMwaVt5432GA=="
      ],
      "issuer": "**https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/v2.0**"
    }
  ]
}}

Yet, when you check the actual token, it contains a different issuer:
{
  "typ": "JWT",
  "alg": "RS256",
  "x5t": "u4OfNFPHwEBosHjtrauObV84LnY",
  "kid": "**u4OfNFPHwEBosHjtrauObV84LnY**"
}.{
  [snip]
  "iss": "https://sts.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/",
[snip]
  "idp": "https://sts.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/",
  "oid": "58e0e9e7-e629-4d3a-863d-4a05d98cac83",
  "sub": "58e0e9e7-e629-4d3a-863d-4a05d98cac83",
  "tid": "72f988bf-86f1-41af-91ab-2d7cd011db47",
  "uti": "mDeHTclWuUaSNJELHsUNAA",
  "ver": "1.0"
}.[Signature]

This **might** cause token validation problems.

_Sorry for the formatting..._

**Comment by oleksabor** [comment]
@mpalumbo7 Thank you for this hint.
I've updated Azure App manifest file with the ` "accessTokenAcceptedVersion": 2,` and it started to generate correct token. 

The most strange thing is getting v1.0 token if I'm asking for token from the `https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token` endpoint...

**Comment by thomaslevesque** [comment]
Why on earth would it return a v1 token when we're only using v2 endpoints? Looks like a bug to me...

**Comment by jasonnutter** [comment]
@thomaslevesque The v2 endpoint is capable of returning both v1 and v2 tokens: https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-app-manifest#key-value-type-accesstokenacceptedversion-nullable-int32

**Comment by thomaslevesque** [comment]
@jasonnutter I understand that, but I find it strange that *by default*, the issuer in the token doesn't match the one in the metadata. If you just rely on the metadata to configure token validation (which I usually do), it's broken by default; that's hardly ideal...

**Comment by mayank1214** [comment]
I have a similar problem. It generates v1 token on local machine (works fine) however It generates v2 token on server with same source code. Any suggestion on possible solution?

**Comment by jasonnutter** [comment]
@mayank1214 Can you open a new issue please? Thanks!

**Comment by saurabhjain-MA** [comment]
https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/560#issuecomment-466583013

This suggestion is not working for me.
I've changed it to `"accessTokenAcceptedVersion": 2,` , however when i ask for token using `acquireTokenSilent` method in msal lib, the token generated has the **"iss": "https://sts.windows.net**

**Comment by tinodo** [comment]
Changing the token _version_ will **not** change the issuer. The issuer is changed when you use a different endpoint; so use the Azure AD V2 endpoint instead of the V1 endpoint (e.g. the one like https://login.microsoftonline.com/tenant.onmicrosoft.com/oauth2/**v2.0**/token)

**Comment by saurabhjain-MA** [comment]
@tinodo , how can i change to Azure AD V2 endpoint. i'm using [msal angular](https://azuread.github.io/microsoft-authentication-library-for-js/ref/msal-angular/) .

**Comment by saurabhjain-MA** [comment]
i've checked and my azure app is configured to use v2 endpoint (as i see under azure app overview-> endpoints). looks like an issue with the library.

**Comment by jasonnutter** [comment]
@saurabhjain-MA MSAL uses the v2 endpoint already. What happens when you use the token in your application? And how are you validating the token in your server?

**Comment by flashtheman** [comment]
Odd, my application was working until about one week ago. Now, I get an invalid token too. I think something on Azure side.

**Comment by saurabhjain-MA** [comment]
the initial call to MS api returns a token signed through **login.microsoftonline.com** but when i call **acquireTokenSilent** method of lib, it returns toke signed through **sts.windows**.  lib is **"@azure/msal-angular": "^1.0.0-beta.4"**.

**Comment by jasonnutter** [comment]
@saurabhjain-MA Are you encountering problems when attempting to use these access tokens? And if so, what are you using to validate the access tokens?

**Comment by saurabhjain-MA** [comment]
@jasonnutter , i'm using a python library in backend to validate the token. I know the public key for the issuer **login.microsoftonline.com**, so i can validate it, but for **sts.windows.** it failed.

**Comment by saurabhjain-MA** [comment]
So ideally the library should make sure that both tokens(generated initially vs generated through  acquireTokenSilent method of msal angular lib) should  have same issuer. and if it's not happening(and may take time) can i've public key for issuer **sts.windows** that i can use to validate on backend.

**Comment by hpsin** [comment]
> Changing the token _version_ will **not** change the issuer. The issuer is changed when you use a different endpoint; so use the Azure AD V2 endpoint instead of the V1 endpoint (e.g. the one like https://login.microsoftonline.com/tenant.onmicrosoft.com/oauth2/v2.0/token)

@tinodo  this is **not** accurate.  When an API  (the resource AKA target AKA scope-owner of the access token) changes their token version, it does change the issuer of the access tokens issued for that API.  Every API sets this differently, so depending on the API you plan to call, you may get tokens with different issuers and token versions. If you have encountered behavior that runs opposite to this I'd love to investigate it as it means we have issues in our token service.  

ID tokens are issue based on the endpoint used, so all ID tokens issued to MSAL will be v2.0 and have the login.microsoftonline.com issuer. 

For reference: 

1. Every single token (access or ID) issued with a v1.0 fomat will have issuer sts.windows.net (assuming the worldwide cloud and not a national one) 
1. Every single token (access or ID) issued with a v2.0 format will have issuer login.microsoftonline.com
1. Every single ID token issued by the v1 endpoint (used by ADAL) is v1 format. 
1. Every single ID token issued by the v2 endpoint (used by MSAL) is v2 format. 
1. Every single access token is issued with the format from the API's registration, and can be issued from *either* endpoint. 

So @saurabhjain-MA - can you clarify that you are getting a token for the *same resource* in both calls? And that both are access tokens? And they have different issuers? 

As a closing reminder - only the app in the audience of a token should ever, ever, ever look inside the access token. Access tokens are completely and utterly controlled by the API, and never, in any way, by the client requesting them.  They can be encrypted, change versions, or have claims added or removed without warning to you. If your app takes a dependency on the format or on validating tokens for *other* applications, you have a potential security issue and a guaranteed reliability issue.

**Comment by saurabhjain-MA** [comment]
@hpsin ,
here are the details of the [setup](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/560#issuecomment-618797695). 

- can you clarify that you are getting a token for the same resource in both calls? 
yes and i just use `MsalInterceptor` for getting token. Pls let me know if you need further code level info.

- And that both are access tokens? 
Yes

- And they have different issuers?
Yes.

I need to validate the token i receive on backend where the jwt library reject it as the issuer is different as we supply public key for issuer **login.microsoftonline.com** for validation and it was signed with different issuer.
If i can have public key for issuer **https://sts.windows.net**, that may also work for me.

**Comment by hpsin** [comment]
@saurabhjain-MA - can you confirm the "scopes" and "aud" of each token?

**Comment by saurabhjain-MA** [comment]
@hpsin , scopes are same ['user.read', 'openid', 'profile'], but **aud** in token are different and i don't know why. **aud** is the azure app client ID i believe and  I've configured it once but msal -interceptor not using it i guess.

**Comment by hpsin** [comment]
Ok, that's expected then - different token versions for different audiences.  You might be looking at the ID token instead of the access token.

**Comment by jstevensgithub** [comment]
I just encountered this using the lasted MSAL code.  2 AAD app registrations, one client and one server (API).  
Worked fine with ADAL.   

With MSAL library:
API manifest set to:
"accessTokenAcceptedVersion": null.
The resulting token has the claim:
"iss": "https://sts.windows.net/{tenantId}"
The server return 401 from the client.

API manifest set to:
"accessTokenAcceptedVersion": 2
The token has the claim:
"iss": "https://login.microsoftonline.com/{tenantId}/v2.0",
The server works but I had to set validation parameters for the authority as:
                options.Authority = $"{_azureOptions.Instance}{_azureOptions.TenantId}/v2.0";

Any way to fix this in the client app so I don't have to change the manifest for the API?

Is there a way to force this in the token

**Comment by hpsin** [comment]
This is always and only controlled by the API. It is very much by design that a client cannot disrupt the version of tokens sent to an API. You are doing the correct thing in your API by validating like that.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mderaeve** [comment]
I changed the Authority string to this, than it works! 

`.AddJwtBearer(options =>
{
    options.Authority = $"https://login.microsoftonline.com/{Configuration["AzureAd:TenantId"]}/v2.0";
    options.Audience = Configuration["AzureAd:ClientId"];`
