### ISSUE TITLE
Mark client-side React components with "use client" to support React 18

### ISSUE THREAD

**Issue by saraelsa** [AzureAD/microsoft-authentication-library-for-js#5601]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL React (@azure/msal-react)

### Public or Confidential Client?

Public

### Description

React 18 introduced server components which don't support state. Components that rely on state (e.g. MsalProvider) should be marked with `"use client"` directive at the top of the file so that they can directly be used within server components; otherwise, if they are used within a parent server component, React will attempt to render them on the server and fail.

A workaround for external libraries is to import and re-export the component within a file that's marked with the directive.

See React RFC 227: https://github.com/reactjs/rfcs/blob/main/text/0227-server-module-conventions.md

### Source

External (Customer)

**Comment by sameerag** [comment]
@saraelsa Thanks for bring this to our attention. We haven't really gotten around supporting this feature in React 18 yet. I have marked this in our backlog.

However, It may be a while for us to support this as we are prioritizing some other features at this time. Community PRs are welcome though.

**Comment by EmLauber** [comment]
Re-opening as this is a feature request and not meant to auto-close. We will add it to our backlog and will update the issue if we can prioritize.

**Comment by tobi1220** [comment]
Is there an easy workaround for this?
