### ISSUE TITLE
Ionic React iOS

### ISSUE THREAD

**Issue by Yannickvandenbos** [AzureAD/microsoft-authentication-library-for-js#5605]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

Newest

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

Newest

### Public or Confidential Client?

Public

### Description

I have made an Ionic react capacitor application for iOS only. 

Opening the browser, logging in and redirect are working perfect. But here comes the problem:

once back in the app, there is no signed in account, token or whatsoever. 

Is there any workaround to make it work on the specified platform?

### Identity Provider

None

### Source

Internal (Microsoft)

**Comment by sameerag** [comment]
@Yannickvandenbos Unfortunately we do not yet support for ionic with MSAL Js. We have it in the backlog but do not have a clear ETA at this point. Let me revert if we can help with general direction regarding ionic storage but please note it will not be supported in code.

**Comment by Yannickvandenbos** [comment]
> @Yannickvandenbos Unfortunately we do not yet support for ionic with MSAL Js. We have it in the backlog but do not have a clear ETA at this point. Let me revert if we can help with general direction regarding ionic storage but please note it will not be supported in code.

What would be a solution regarding to ionic storage…?

**Comment by sameerag** [comment]
@Yannickvandenbos 

I gathered some info and we believe currently only `browser` works out of box for `ionic`. Support for mobile platforms - iOS and Android - is not available. Even a workaround for storage is not possible as this can be supported only if we add `custom storage` in MSAL JS, i.e., user can set the storage API to `ionic/storage` when MSAL boots up. However we do not yet have support for `custom storage` in MSAL JS.

@EmLauber can we track this as a part of `Custom Storage` support (whenever we plan to take it, I assume no ETA for now)?

**Comment by sameerag** [comment]
Linking the custom storage feature request on MSAL JS:  #1588

**Comment by EmLauber** [comment]
Changing to Feature request and linking the general Ionic support request in #4290

**Comment by tnorling** [comment]
Closing - we'll track the request for Ionic support in #4290
