### ISSUE TITLE
acquireTokenSilent fails when identity server is on localhost

### ISSUE THREAD

**Issue by kyledevans** [AzureAD/microsoft-authentication-library-for-js#5608]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.32.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.5.1

### Public or Confidential Client?

Public

### Description

Our authority is Duende Identity Server running on https://localhost:5000 (for development).  When I updated our project dependencies to include the latest version of msal-common, acquireTokenSilent began throwing errors.  It looks like it is failing to retrieve the access token.  It doesn't appear to actually be making any network calls to our IDP (except to retrieve the openid configuration object).

Upon investigating the msal-common library, there is a regex that was recently added to /lib/msal-common/src/cache/entities/CredentialEntity.ts.  This regex fails to recognize localhost:5000 as the domain.  The method is called getCredentialType().

### Error Message

Uncaught (in promise) InteractionRequiredAuthError: no_tokens_found: No refresh token found in the cache. Please sign-in.
    at InteractionRequiredAuthError.AuthError [as constructor] (AuthError.ts:49:1)
    at new InteractionRequiredAuthError (InteractionRequiredAuthError.ts:44:1)
    at InteractionRequiredAuthError.createNoTokensFoundError (InteractionRequiredAuthError.ts:71:1)
    at RefreshTokenClient.<anonymous> (RefreshTokenClient.ts:146:1)
    at step (MathUtils.ts:23:1)
    at Object.next (MathUtils.ts:23:1)
    at MathUtils.ts:23:1
    at new Promise (<anonymous>)
    at __awaiter (MathUtils.ts:23:1)
    at RefreshTokenClient.acquireTokenWithCachedRefreshToken (RefreshTokenClient.ts:137:1)
AuthError @ AuthError.ts:49
InteractionRequiredAuthError @ InteractionRequiredAuthError.ts:44
InteractionRequiredAuthError.createNoTokensFoundError @ InteractionRequiredAuthError.ts:71
(anonymous) @ RefreshTokenClient.ts:146
step @ MathUtils.ts:23
(anonymous) @ MathUtils.ts:23
(anonymous) @ MathUtils.ts:23
__awaiter @ MathUtils.ts:23
RefreshTokenClient.acquireTokenWithCachedRefreshToken @ RefreshTokenClient.ts:137
(anonymous) @ RefreshTokenClient.ts:129
step @ MathUtils.ts:23
(anonymous) @ MathUtils.ts:23
(anonymous) @ MathUtils.ts:23
__awaiter @ MathUtils.ts:23
RefreshTokenClient.acquireTokenByRefreshToken @ RefreshTokenClient.ts:97
(anonymous) @ SilentRefreshClient.ts:27
step @ log.browser.ts:19
(anonymous) @ log.browser.ts:19
fulfilled @ log.browser.ts:19
await in fulfilled (async)
(anonymous) @ CurrentUserProvider.tsx:46
commitHookEffectListMount @ react-dom.development.js:23049
commitPassiveMountOnFiber @ react-dom.development.js:24816
commitPassiveMountEffects_complete @ react-dom.development.js:24781
commitPassiveMountEffects_begin @ react-dom.development.js:24768
commitPassiveMountEffects @ react-dom.development.js:24756
flushPassiveEffectsImpl @ react-dom.development.js:26990
flushPassiveEffects @ react-dom.development.js:26935
(anonymous) @ react-dom.development.js:26725
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533

### MSAL Configuration

```javascript
let reactAppUrl = new URL(window.location.href);
reactAppUrl = new URL(`${reactAppUrl.protocol}//${reactAppUrl.host}`);
const ssoUrl = new URL('https://localhost:5000');

const pcaConfig: Configuration = {
  auth: {
    clientId: 'CompumedReact',
    authority: `${ssoUrl.protocol}//${ssoUrl.host}`,
    knownAuthorities: [ssoUrl.host],
    redirectUri: `${reactAppUrl.protocol}//${reactAppUrl.host}/`,
    navigateToLoginRequestUrl: true,
    protocolMode: ProtocolMode.OIDC,
  },
  cache: {
    cacheLocation: 'localStorage',
  },
  system: {
    loggerOptions: {
      loggerCallback: msalLogMarshaller,
    },
  },
};
```

### Relevant Code Snippets

```javascript
export async function getAccessToken() {
  const account = pca.getActiveAccount();
  if (account == null) {
    throw new AnonymousUserError(
      'Cannot acquire JWT access token because the user is not logged in.',
    );
  } else {
    try {
      return (
        await pca.acquireTokenSilent({ scopes: ACCESS_TOKEN_SCOPES, account })
      ).accessToken;
    } catch (ex) {
      console.log('setAccessToken', ex);
      throw ex;
    }
  }
}
```

### Reproduction Steps

1. Login via loginRedirect()
2. Attempt to acquire token using acquireTokenSilent()

### Expected Behavior

Access token is returned.

### Identity Provider

Other

### Browsers Affected (Select all that apply)

Chrome

### Regression

@azure/msal-common 9.0.1

### Source

External (Customer)

**Comment by sameerag** [comment]
@konstantin-msft Is this related to the recent push? Can you please verify?

**Comment by Vandersteen** [comment]
We are also hitting this issue. 
Did you find a work-around or do you know which version's do work ?

**Comment by konstantin-msft** [comment]
> @konstantin-msft Is this related to the recent push? Can you please verify?

Yes, this one is related to the recent push. Working on a fix.

**Comment by kyledevans** [comment]
I was able to workaround by manually adding "@azure/msal-common" version 9.0.1 as a dependency in my package.json.

**Comment by gianlucca** [comment]
I've been experiencing this error too.

Core Library
MSAL.js v2 (@azure/msal-browser)

Core Library Version
2.33.0

Wrapper Library
MSAL React (@azure/msal-react)

Wrapper Library Version
1.5.3

> I was able to workaround by manually adding "@azure/msal-common" version 9.0.1 as a dependency in my package.json.

Tried doing that, but no luck.

**Comment by sameerag** [comment]
Can you please try upgrading to [`@azure/msal-browser-2.33.0`](https://www.npmjs.com/package/@azure/msal-browser/v/2.33.0)?

**Comment by gianlucca** [comment]
> Can you please try upgrading to [`@azure/msal-browser-2.33.0`](https://www.npmjs.com/package/@azure/msal-browser/v/2.33.0)?

I was already using v2.33.0

what worked for me was deleting the node_modules folder and the package lock file, and running npm install again

seems to be working fine since then

**Comment by sameerag** [comment]
Could be old `node-modules` pointing to older `msal-browser`. Closing.
