### ISSUE TITLE
Unable to login using personal account

### ISSUE THREAD

**Issue by yolossn** [AzureAD/microsoft-authentication-library-for-js#5610]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.32.2

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.5.2

### Public or Confidential Client?

Public

### Description

When the login flow is initiated I am not able to login using personal accounts to authenticate. I think this has to do with `v2`, If I remove `v2` from the login URL the personal accounts are displayed. I found a similar issue https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/3706 but the answer is not clear, the issue suggests enabling MSA passthrough is the solution but I couldn't find any documentation on how to enable MSA passthrough.

If this is about "Supported Account types" I also tried changing it to 
```
Accounts in any organizational directory (Any Azure AD directory - Multitenant) and personal Microsoft accounts (e.g. Skype, Xbox)
```

<img width="350" alt="image" src="https://user-images.githubusercontent.com/22731013/214528678-c60fc98a-f38f-4c0f-ae87-62987008ecb1.png">

### MSAL Configuration

```javascript
{
    auth:{
        clientId: clientId,
        authority: "https://login.microsoftonline.com/organizations",
        redirectUri: redirectUri,
    },
}
```

### Relevant Code Snippets

```javascript
function login(){
    const msalInstance = new PublicClientApplication(config)

    const loginRequest:RedirectRequest = {
        redirectUri: redirectUri,
        prompt: "select_account",
        scopes:["openid","profile","User.Read"],
    }

    return <button onClick={()=>msalInstance.loginRedirect(loginRequest)}>Login</button>
}
```

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by sameerag** [comment]
@yolossn What is the error you see? Can you please share it?

**Comment by yolossn** [comment]
When I try to login with personal account I get the following error message:
```
You can't sign in here with a personal account. Use your work or school account instead.
```

**Comment by sameerag** [comment]
@yolossn The authority `login.microsoftonline.com/organizations` is meant for AAD accounts. Did you try `consumers` instead?

**Comment by yolossn** [comment]
When I change `/organizations` to `/consumers` I can see only the personal accounts, basically I want the user to be able to login with either personal or organization accounts and access the resources in ARM from my application.

**Comment by sameerag** [comment]
Did you try `/common` and what happens in that case?

**Comment by yolossn** [comment]
Yes, when using `/common` I get the `You can't sign in here with a personal account. Use your work or school account instead.` error message.

**Comment by sameerag** [comment]
@yolossn Some AAD resources do not support MSA. ARM is one of them. Some 1P apps support it but only through something called MSA Passthrough. 

I think what you are trying to do here is not possible, access ARM resources with personal accounts. The last issue I could dig on this is [here](https://github.com/AzureAD/microsoft-identity-web/issues/651).

**Comment by yolossn** [comment]
Hey, Any idea on how I can setup the MSA passthrough. I am able to get the whole flow working (both personal and organization accounts) by doing the OIDC login flow, I want to get the same working using msal.js.

**Comment by sameerag** [comment]
Please find the guidance [here](https://review.learn.microsoft.com/en-us/identity/microsoft-identity-platform/adding-msa-audience-first-party?branch=main#step-10-considerations-for-msa-passthrough-users).

**Comment by Lawton** [comment]
I know this is not the original authors issue. But I stumbled on this when trying to resolve my own issue using `/common`. It turns out I needed to update my Azure App's Manifest directly https://learn.microsoft.com/en-us/azure/active-directory/develop/supported-accounts-validation

Also if you are updating to `AzureADandPersonalMicrosoftAccount` you must also update `accessTokenAcceptedVersion` to 2 https://learn.microsoft.com/en-us/azure/active-directory/develop/reference-app-manifest#accesstokenacceptedversion-attribute

**Comment by nik-net** [comment]
Did someone manage to resolve this issue? We are using MSAL to authenticate users so that we can access Azure DevOps resources on their behalf but we continue to get the same error.
