### ISSUE TITLE
Unrecoverable invalid_grant error state after multiple login attempts

### ISSUE THREAD

**Issue by JasonGore** [AzureAD/microsoft-authentication-library-for-js#5613]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.28.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Confidential

### Description

We have been using `msal-browser` for 18 months in our app successfully. However, I was troubleshooting a UI issue where multiple logins could be queued. While fixing the UI issue I had one `loginPopup` succeed immediately followed by another `loginPopup` showing a login window. This appear to get me into an unrecoverable `invalid_grant: UserPrincipal doesn't have the key ID configured.` state.

This state was not fixable by doing a full logout. In addition, it polluted other apps in the same browser, such as Office.com, Teams, and Kusto. The login flow did not give me the option to "Sign out and forget" the affected account either. The only fix that worked was to delete all cookies for `login.microsoftonline.com` in the browser.

### Error Message

invalid_grant: UserPrincipal doesn't have the key ID configured.

### MSAL Configuration

```javascript
auth: {
  clientId: MsalAuthService.authClientId,
  redirectUri: `${window.location.origin}/authLanding.html`,
  clientCapabilities: ['CP1'],
  authority: getTenantAuthority(),
  navigateToLoginRequestUrl: true
},
cache: {
  cacheLocation: 'localStorage',
  storeAuthStateInCookie: false
}
```

### Relevant Code Snippets

```javascript
// Simplified version of code that I assume got me into this state
await loginPopup();
await loginPopup();
```

### Reproduction Steps

1. Call `loginPopup` and log in successfully
2. Immediately call `loginPopup` again

### Expected Behavior

While I know that calling `loginPopup` isn't proper use of the API, it seems this error should be recoverable through the MSAL API without requiring manual user intervention.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Edge

### Source

Internal (Microsoft)

**Comment by sameerag** [comment]
We think this is a MFA issue at the backend. Will reach out if we have specific conditions you may have to check in your app registration to surpass this.

**Comment by sameerag** [comment]
Closing. Tracking offline as needed.
