### ISSUE TITLE
`getAccountByUsername` returns null on IOS

### ISSUE THREAD

**Issue by KennethBWSong** [AzureAD/microsoft-authentication-library-for-js#5617]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.32.2

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

We have a Teams Tab app using `msal-browser` for SSO. When user first trigger SSO in this app, SSO works properly. If the user logout and login Teams, and we found user will be asked to login in popup login page again on Teams IOS to get user profile, while the same app on Windows can get user profile directly. When debugging, we found that the root cause should be `getAccountByUsername` returns null on IOS, while returns an account object on Windows.
You can find sample app [here](https://github.com/OfficeDev/TeamsFx-Samples/tree/dev/hello-world-tab).
Related bug [here](https://github.com/OfficeDev/TeamsFx/issues/7574).

### MSAL Configuration

```javascript
{
  auth: {
    clientId: clientId,
    authority: `https://login.microsoftonline.com/${tenantId}`,
    navigateToLoginRequestUrl: false
  },
  cache: {
    cacheLocation: "localStorage",
  },
}
```

### Relevant Code Snippets

```javascript
try {
  const account = msalInstance.getAccountByUsername(loginHint!);
  const scopesRequestForAcquireTokenSilent = {
    scopes: scopesArray,
    account: account,
    redirectUri: redirectUri,
  };
  tokenResponse = await this.msalInstance!.acquireTokenSilent(
    scopesRequestForAcquireTokenSilent
  );
} catch (error: any) {
  // error handling
}
```

### Reproduction Steps

1. Provision and deploy SSO Tab
2. Open the app on Teams IOS, click on `Authorization` and login in pop-up page, you can get user profile now
3. Logout and login Teams IOS, open the app again and you need to login again in pop-up page

### Expected Behavior

Should have same behavior as on Windows which can directly get user profile when login again.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Edge

### Source

Internal (Microsoft)

**Comment by sameerag** [comment]
@KennethBWSong Can you please provide the MSAL logs enabling the "verbose" mode? Instructions can be found [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/configuration.md).

**Comment by KennethBWSong** [comment]
@sameerag Do you have any idea how I can check the logs on IOS?

**Comment by sameerag** [comment]
Teams has a unique auth process on mobile. Is this flow browser in iOS -> Teams app in iOS SSO?

**Comment by KennethBWSong** [comment]
It is in an Teams Tab app on IOS. Actually, this flow works on Teams client as well as Teams Web client, and only have this issue on Teams IOS client.

**Comment by SLdragon** [comment]
@sameerag , any update?

**Comment by pjpraveenjayakumar** [comment]
@SLdragon , @sameerag FYI, this issue is happening with both iOS and Android mobile platforms.

Version [iOS 16.2 Android 11]

**Comment by sameerag** [comment]
@SLdragon @pjpraveenjayakumar The issue is still under investigation. We heard from a few other folks that mobile platforms have an issue with MSAL JS. We do not develop for mobile but expect the mobile browsers work as web browsers too. 

As the other issue mentions, this could be something to do with webOS not allowing us to access the memory. Will keep you folks posted.

**Comment by SLdragon** [comment]
Thanks, if you have any update, please let we know.

**Comment by benjblack** [comment]
Having the same issue (#5667). This seems like a major bug / limitation on multiple mobile browsers, both iOS and Android (unless we are missing something configuration related).

**Comment by KennethBWSong** [comment]
@sameerag Please let us know in this thread if you have any update, thx!

**Comment by SLdragon** [comment]
@sameerag Any update?

**Comment by ghost** [comment]
This issue requires attention from the MSAL.js team and has not seen activity in **5 days**. @sameerag please follow up.

**Comment by sameerag** [comment]
@SLdragon We officially do not support mobile browsers though MSAL JS is expected to work as long as they work as web browsers (in supporting popup vs redirect, browser storage etc). I would appreciate if anyone who can repro this issue can provide the network trace and verbose logs (instructions [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logging.md)) for me to check what may be happening.

Please also share the cache status in a `working case` vs `non-working case`.

**Comment by andresgd7** [comment]
any news?

**Comment by ThomasPe** [comment]
this is not solved!

**Comment by keeth** [comment]
This is affecting me too. It is hard to trace since it's happening inside the iOS Teams app, which doesn't provide DevTools / Remote Debugging support as far as I know.

I am able to login interactively, but nothing is stored to `sessionStorage`, so silent token acquisition always fails. Works fine on the Desktop Teams client and on web Teams.
