### ISSUE TITLE
getAccountByHomeId return null

### ISSUE THREAD

**Issue by QCGSH** [AzureAD/microsoft-authentication-library-for-js#5618]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.28.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

none

### Public or Confidential Client?

Public

### Description

After successful login, use accountId to get active account and return null.

### MSAL Configuration

```javascript
auth: {
    clientId: clientId,
    authority: "https://login.microsoftonline.com/common",
    redirectUri: `https://localhost:44355/fallbackauthdialog.html`,
    navigateToLoginRequestUrl: true,
  },
  cache: {
    cacheLocation: "localStorage", // Needed to avoid "User login is required" error.
    storeAuthStateInCookie: false, // Recommended to avoid certain IE/Edge issues.
  },
```

### Relevant Code Snippets

```javascript
let messageFromDialog = JSON.parse(arg.message);

  if (messageFromDialog.status === "success") {
    loginDialog.close();

    homeAccountId = messageFromDialog.accountId; 

    const homeAccount = publicClientApp.getAccountByHomeId(messageFromDialog.accountId);
```

### Identity Provider

None

### Source

Internal (Microsoft)

**Comment by lalimasharda** [comment]
Hey @QCGSH!

It seems that the `accountId` you are passing into the `getAccountByHomeId` method might be incorrect. Could you please shed some light on how you are acquiring the `accountId` or `messageFromDialog` in your code?

Could you also please share some browser logs? [How to set logging options.](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/configuration.md#:~:text=Default%20Value-,loggerOptions,-Config%20object%20for)
