### ISSUE TITLE
MsalGuard support for app roles

### ISSUE THREAD

**Issue by jesben** [AzureAD/microsoft-authentication-library-for-js#5619]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Public or Confidential Client?

Public

### Description

It will be nice if MsalGuard also could check required app roles for route. App roles could be specified in data. E.g. an roles array, only one role is required to gain access.

`data: {
      roles: ['Editor', 'Admin'],
 },
 canActivate: [MsalGuard],`

### Source

External (Customer)

**Comment by derisen** [comment]
@jesben at the moment, you could copy `MsalGuard` and extend for your scenario as in the [example here](https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/tree/main/5-AccessControl/1-call-api-roles/SPA/src/app). @lalimasharda this seems related to #3406
