### ISSUE TITLE
Cross-origin token redemption is permitted only for the 'Single-Page Application' -- even though it is definitely a single page app

### ISSUE THREAD

**Issue by jhendricks-hart** [AzureAD/microsoft-authentication-library-for-js#5622]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.5.2

### Public or Confidential Client?

Public

### Description

In is a basic `create-react-app` and we added `http://localhost:3000` to the SPA redirect URIs in the Azure Portal. But even with that when I run `loginRedirect` we still get the Cross Origin error.
This app also utilizes the Tenant ID, which I set up in the `authority` parameter as seen in the config below.

**Note**: it will successfully redirect to the login screen if the user is not logged in, but when it redirects back the authorization fails.

### Error Message

Cross-origin token redemption is permitted only for the 'Single-Page Application' client-type.

### MSAL Configuration

```javascript
{
    auth: {
      clientId: process.env.REACT_APP_CLIENT_ID || '',
      authority: `https://login.microsoft.com/${process.env.REACT_APP_TENANT_ID || ''}`,
      redirectUri: window.location.origin + '/',
    },
    cache: {
      cacheLocation: 'localStorage',
      storeAuthStateInCookie: true,
    },
  }
```

### Relevant Code Snippets

```javascript
const { login, result, error: msalError } = useMsalAuthentication(InteractionType.Silent, config.loginRequest);

  useEffect(() => {
    if (msalError instanceof InteractionRequiredAuthError) {
      login(InteractionType.Redirect, config.loginRequest)
        .then((response) => {
          console.log(response);
        })
        .catch((err) => {
          console.log(err);
        });
    }
  }, [msalError]);
```

### Reproduction Steps

Not sure how to reproduce outside of my app because it uses the Tenant ID.

### Expected Behavior

It should successfully authorize the user and return an event with a payload.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Firefox, Safari

### Source

External (Customer)

**Comment by jhendricks-hart** [comment]
This _might_ be a duplicate of https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5196, but I am not sure.

**Comment by derisen** [comment]
@jhendricks-hart do you by any chance have another platform added (e.g. web) on the **Authentication** blade on app registration portal?

**Comment by jhendricks-hart** [comment]
Yes we have both
________________________________

**Comment by derisen** [comment]
@jhendricks-hart ok that explains. Please refer to [redirect uri limitations](https://learn.microsoft.com/en-us/azure/active-directory/develop/reply-url#localhost-exceptions):

> Due to ephemeral port ranges often required by native applications, the port component (for example, :5001 or :443) is ignored for the purposes of matching a redirect URI. As a result, all of these URIs are considered equivalent:
> http://localhost/MyApp
> http://localhost:1234/MyApp
> http://localhost:5000/MyApp
> http://localhost:8080/MyApp
> From a development standpoint, this means a few things:
> Do not register multiple redirect URIs where only the port differs. The login server will pick one arbitrarily and use the behavior associated with that redirect URI (for example, whether it's a web-, native-, or spa-type redirect).
> 
> This is especially important when you want to use different authentication flows in the same application registration, for example both the authorization code grant and implicit flow. To associate the correct response behavior with each redirect URI, the login server must be able to distinguish between the redirect URIs and cannot do so when only the port differs.
> 
> To register multiple redirect URIs on localhost to test different flows during development, differentiate them using the path component of the URI. For example, http://localhost/MyWebApp doesn't match http://localhost/MyNativeApp.

does that apply?

**Comment by jhendricks-hart** [comment]
> does that apply?

I bet that is it, we will try it out today and if it works I'll close this issue

**Comment by jhendricks-hart** [comment]
Worked like a charm, thanks

**Comment by ERobishaw** [comment]
> @jhendricks-hart ok that explains. Please refer to [redirect uri limitations](https://learn.microsoft.com/en-us/azure/active-directory/develop/reply-url#localhost-exceptions):
> 
> > Due to ephemeral port ranges often required by native applications, the port component (for example, :5001 or :443) is ignored for the purposes of matching a redirect URI. As a result, all of these URIs are considered equivalent:
> > http://localhost/MyApp
> > http://localhost:1234/MyApp
> > http://localhost:5000/MyApp
> > http://localhost:8080/MyApp
> > From a development standpoint, this means a few things:
> > Do not register multiple redirect URIs where only the port differs. The login server will pick one arbitrarily and use the behavior associated with that redirect URI (for example, whether it's a web-, native-, or spa-type redirect).
> > This is especially important when you want to use different authentication flows in the same application registration, for example both the authorization code grant and implicit flow. To associate the correct response behavior with each redirect URI, the login server must be able to distinguish between the redirect URIs and cannot do so when only the port differs.
> > To register multiple redirect URIs on localhost to test different flows during development, differentiate them using the path component of the URI. For example, http://localhost/MyWebApp doesn't match http://localhost/MyNativeApp.
> 
> does that apply?

man.... I wish that were clearly documented somewhere....
I can't tell you how many DAYS I spent trying to figure out why I'm getting cross-origin error... and it was nowhere clear that it behaves this way...

THANK YOU @derisen 
I'd buy you a coffee or 100 if I could...

**PLEASE Microsoft... DOCUMENT THIS SOMEWHERE!!!!!**
