### ISSUE TITLE
forceRefresh configuration and example

### ISSUE THREAD

**Issue by fong1999** [AzureAD/microsoft-authentication-library-for-js#5623]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.11

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

Hi!

I am looking for a solution or example that I can set to use forceRefresh flag when id token expires. 

Here is what we have right now:

```

export const msalConfig: Msal.Configuration = {
  auth: {
    clientId: EnvironmentService.getAzureClientId(),
    redirectUri: `${window.location.origin}`,
    authority: `https://login.microsoftonline.com/${EnvironmentService.getAzureTenantId()}`
  },
  cache: {
    cacheLocation: "sessionStorage",
    storeAuthStateInCookie: true,
  }
}

const loginRequest = {
  scopes: ["openid", "profile", "User.Read"]
}

export function getIdTokenFromAzure(): Promise<string> {
  return getTokenRedirect(loginRequest).then(response => {
    if (!response || !response.idToken) {
      console.log("MsalAuthService >>> getIdTokenFromAzure : Failed to get id token, no redirect response");
      return "";
    } else {
      return response.idToken;
    }
  })
}

```

Is it correct to do something similar by adding forceRefresh flag here? Then define a new method - getIdTokenFromAzureWithForceRefresh() to do the forceRefresh? 

```

const loginRequestForceRefresh = {
  scopes: ["openid", "profile", "User.Read"],
  forceRefresh: true,
}

export function getIdTokenFromAzureWithForceRefresh(): Promise<string> {
  return getTokenRedirect(loginRequestForceRefresh).then(response => {
    if (!response || !response.idToken) {
      console.log("MsalAuthService >>> getIdTokenFromAzureWithForceRefresh : Failed to get id token, no redirect response");
      return "";
    } else {
      return response.idToken;
    }
  })
}

```
There is a piece of code below, but I don't know what is used for? Do I need to call it with loginRequestForceRefresh too? 

```
function signIn() {
  myMSALObj.loginRedirect(loginRequest);
  // myMSALObj.loginRedirect(loginRequestForceRefresh);
}

```
Thanks so much!

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by lalimasharda** [comment]
Hey @fong1999 !

Can you please share the implementation for `getTokenRedirect`?

**Comment by fong1999** [comment]
> Hey @fong1999 !
> 
> Can you please share the implementation for `getTokenRedirect`?

Hi @lalimasharda Sharda, Thanks for your reply. Yes, please see below:

```

function getTokenRedirect(request) {
  /**
   * See here for more info on account retrieval:
   * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/docs/Accounts.md
   */
  request.account = myMSALObj.getAccountByUsername(username);
  return myMSALObj.acquireTokenSilent(request).catch(error => {
    console.warn("MsalAuthService >>> getTokenRedirect : Silent token acquisition fails. acquiring token using redirect");
    if (error instanceof Msal.InteractionRequiredAuthError) {
      // fallback to interaction when silent call fails
      return myMSALObj.acquireTokenRedirect(request);
    } else {
      console.warn("MsalAuthService >>> getTokenRedirect : " + error);
    }
  });
}

```

Please let me know if you need more info.  Thanks!

**Comment by fong1999** [comment]
Hi! 

While I am waiting for your response, I thought about another question. 

With **forceRefresh** flag to be true, will sessionStorage be **updated** with the new values?

Thanks!

**Comment by lalimasharda** [comment]
Thanks for the info @fong1999! To address your questions:

1. Since the lifetimes of the access token and id tokens are not in sync, the forceRefresh flag is necessary to renew the tokens. But if the access token is expired, MSAL will silently renew both the access as well as id tokens if the session is still active. Only silent calls use forceRefresh.

    This flag has nothing to do with the sessionStorage. It is used when you want to skip the tokens already cached in the storage of your choice and make a call directly to the server for new tokens. Whatever response you get from the server is then cached into the storage. You can read more on token renewal [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md#how-do-i-renew-tokens-with-msaljs).

2. The implementation of `getTokenRedirect()` seems a little off. There can be a `then` block but it will not resolve to a response because it is using the redirect flow. If acquireTokenSilent fails, MSAL will execute acquireTokenRedirect, which will basically redirect the browser away from the current page to get tokens from the server and the context will be lost. Please make sure you are calling `handleRedirectPromise` independently to capture the tokens when the control returns back to MSAL. Please check the implementation example [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-browser-samples/VanillaJSTestApp2.0/app/onPageLoad/auth.js#:~:text=msalConfig%3B-,//%20Register%20Callbacks%20for%20Redirect%20flow,%7D,-async%20function%20signIn). 

    In the case of `myMSALObj.loginRedirect(loginRequest); `, it will directly execute the redirect interaction flow to acquire tokens as compared to `getTokenRedirect()` where the code is first trying to acquire tokens silently. But in both these cases, it is necessary for you to have `handleRedirectPromise` called. You can better understand the redirect flow [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md#i-dont-understand-the-redirect-flow-how-does-the-handleredirectpromise-function-work).


Hope this helps. Please let me know if you have more questions.

**Comment by fong1999** [comment]
Hi @lalimasharda Thank you for your explanation! Very helpful! I do have some follow up questions.

In the paragraph you suggested in your first bullet point - about [token renew](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md#how-do-i-renew-tokens-with-msaljs)


_MSAL.js provides the acquireTokenSilent method which handles token renewal by making silent token requests without prompting the user. The method first looks for a valid cached token in the browser storage. If it does not find one, the library makes the silent request to Azure AD and if there is **an active user session (determined by a cookie set in browser on the Azure AD domain)**, a fresh token is returned. The library does not automatically invoke the acquireTokenSilent method. It is recommended that you call acquireTokenSilent in your app before making an API call to get the valid token._

**Question:** 

Where or how to find out the user session lifetime?  In the above message, it says "**an active user session (determined by a cookie set in browser on the Azure AD domain**" Is it in the browser cookies list? According to our company standard, 20 minutes is the max life time of a user session. Does it mean that this is configured by Azure AD admin? We, as client, cannot change it except to find a way to auto-refresh the browser every 20 minutes without a user knowing (use an Iframe or something like that) to make the user session keep active till the user closes the browser or clears cache, right? 

Thanks!

**Comment by fong1999** [comment]
Hi @lalimasharda Please see my next question below.

You said "**This flag has nothing to do with the sessionStorage. It is used when you want to skip the tokens already cached in the storage of your choice and make a call directly to the server for new tokens. Whatever response you get from the server is then cached into the storage**"

**Question**

Yes. My thinking is at 5 minutes **before** the cached id token stored in browser sessionStorage/localStorage **expires**, I want our app to **skip** that existing id token to call the server to get a new id token. So using forceRefersh flag will make a call directly to the server(Azure) to get a new token, and then it will **save** it to the storage (sessionStorage/localStorage by our choice) **again**, correct? In other words, the old token will be **replaced** by the new token got from the call made by using forceRefresh flag, right? 

If this is true, I plan to manually test if my code works or not by comparing the cached id token (**without** using forceRefresh flag) with the new id token got by using the forceRefresh flag **5 minutes before the token expires.** 

We use `handleRedirectPromise` in the code, I have pasted it in below code section. 

About using **forceRefrech** flag, Does below code look right to you for the purpose above? Is that the right way to set the **forceRefresh** flag to **true**?

```

const loginRequestForceRefresh = {
  scopes: ["openid", "profile", "User.Read"],
  forceRefresh: true,
}

export function getIdTokenFromAzureWithForceRefresh(): Promise<string> {
  return getTokenRedirect(loginRequestForceRefresh).then(response => {
    if (!response || !response.idToken) {
      console.log("MsalAuthService >>> getIdTokenFromAzureWithForceRefresh : Failed to get id token, no redirect response");
      return "";
    } else {
      return response.idToken;
    }
  })
}

if (!BrowserUtils.isIframe()) {
  myMSALObj = new Msal.PublicClientApplication(msalConfig);
  // Redirect: once login is successful and redirects with tokens, call Graph API
  myMSALObj.handleRedirectPromise().then(handleResponse).catch(err => {
    console.error(err);
  });
}

```

Any suggestions?

Thanks!

**Comment by lalimasharda** [comment]
The default user session lifetime is 24 hours but yes, it can also be set by the admin. 

And yes, using the forceRefresh flag will refresh the tokens. So theoretically, what you are trying to achieve should work. About the implementation, as I mentioned in my previous comment, the implementation of the then() block after getTokenRedirect() would be useless. The response will be captured in handleResponse() instead and from there you can decide what needs to be done with the response.

Can you maybe try something like this:

```
export function getIdTokenFromAzureWithForceRefresh(): Promise<string> {
  return getTokenRedirect(loginRequestForceRefresh);
}

if (!BrowserUtils.isIframe()) {
  myMSALObj = new Msal.PublicClientApplication(msalConfig);
  // Redirect: once login is successful and redirects with tokens, call Graph API
  myMSALObj.handleRedirectPromise().then(handleResponse).catch(err => {
    console.error(err);
  });
}

function handleResponse(response) {
   if (!response || !response.idToken) {
    ...
  } // this is a rough implementation.
}

function getTokenRedirect(request) {
  /**
   * See here for more info on account retrieval:
   * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/docs/Accounts.md
   */
  request.account = myMSALObj.getAccountByUsername(username);
  return myMSALObj.acquireTokenSilent(request)
   .then(handleResponse(response)
   .catch(error => {
    console.warn("MsalAuthService >>> getTokenRedirect : Silent token acquisition fails. acquiring token using redirect");
    if (error instanceof Msal.InteractionRequiredAuthError) {
      // fallback to interaction when silent call fails
      return myMSALObj.acquireTokenRedirect(request);
    } else {
      console.warn("MsalAuthService >>> getTokenRedirect : " + error);
    }
  });
}

```

Let me know if this makes sense and if it works.

**Comment by fong1999** [comment]
@lalimasharda  Thank you for the idea! I will try that soon.

Below is what our updated version **before** I received your message about using `.then(handleResponse(response)`.  Please let me know what you think. Thanks!

```
import * as Msal from "@azure/msal-browser";
import BrowserUtils from "../utils/BrowserUtils";
import EnvironmentService from "./EnvironmentService";

export const msalConfig: Msal.Configuration = {
  auth: {
    clientId: EnvironmentService.getAzureClientId(),
    redirectUri: `${window.location.origin}`,
    authority: `https://login.microsoftonline.com/${EnvironmentService.getAzureTenantId()}`
  },
  cache: {
    cacheLocation: "sessionStorage",
    storeAuthStateInCookie: true,
  }
}

const loginRequest = {
  scopes: ["openid", "profile", "User.Read"]
}

const tokenRequestForceRefresh = {
  scopes: ["User.Read"],
  forceRefresh: true,
}

export let myMSALObj: Msal.PublicClientApplication;
export let username = "";

if (!BrowserUtils.isIframe()) {
  myMSALObj = new Msal.PublicClientApplication(msalConfig);
  // Redirect: once login is successful and redirects with tokens, call Graph API
  myMSALObj.handleRedirectPromise().then(handleResponse).catch(err => {
    console.error(err);
  });
}

export function hasActiveMsalSession(): boolean {
  return !!username;
}

function handleResponse(resp) {
  if (resp !== null) {
    username = resp.account.username;
  } else {
    /**
     * See here for more info on account retrieval:
     * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/docs/Accounts.md
     */
    const currentAccounts = myMSALObj.getAllAccounts();
    if (currentAccounts === null) {
      return;
    } else if (currentAccounts.length > 1) {
      // Add choose account code here
      console.warn("MsalAuthService >>> handleResponse >>> Multiple accounts detected.");
    } else if (currentAccounts.length === 0) {
      signIn();
    } else if (currentAccounts.length === 1) {
      username = currentAccounts[0].username;
    }
  }
}

function signIn() {
  myMSALObj.loginRedirect(loginRequest);
}

function getTokenRedirect(request) {
  /**
   * See here for more info on account retrieval:
   * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/docs/Accounts.md
   */
  request.account = myMSALObj.getAccountByUsername(username);
  return myMSALObj.acquireTokenSilent(request).catch(error => {
    console.warn("MsalAuthService >>> getTokenRedirect : Silent token acquisition fails. acquiring token using redirect");
    if (error instanceof Msal.InteractionRequiredAuthError) {
      // fallback to interaction when silent call fails
      return myMSALObj.acquireTokenRedirect(request);
    } else {
      console.warn("MsalAuthService >>> getTokenRedirect : " + error);
    }
  });
}

export function getAccessToken(): Promise<string> {
  return getTokenRedirect(loginRequest).then(response => {
    if (!response || !response.accessToken) {
      console.log("MsalAuthService >>> getAccessToken : Failed to get access token, no redirect response");
      return "";
    } else {
      return response.accessToken;
    }
  })
}

/** Get an id token from the cached storage */
export function getIdTokenFromAzure(): Promise<string> {
  return getTokenRedirect(loginRequest).then(response => {
    if (!response || !response.idToken) {
      console.log("MsalAuthService >>> getIdTokenFromAzure : Failed to get id token, no redirect response");
      return "";
    } else {
      return response.idToken;
    }
  })
}

/** Get an id token with forceRefresh flag is true, skipping the cached id token from storage */
export function getIdTokenFromAzureWithForceRefresh(): Promise<string> {
  return getTokenRedirect(tokenRequestForceRefresh).then(response => {
    if (!response || !response.idToken) {
      console.log("MsalAuthService >>> getIdTokenFromAzureWithForceRefresh : Failed to get id token, no redirect response");
      return "";
    } else {
      return response.idToken;
    }
  })
}
```

**Comment by fong1999** [comment]
@lalimasharda  I still have some questions.

**Question**:

- Where or how to find out the user session lifetime?

- In the document that you referred, it says "an active user session (determined by a cookie set in browser on the Azure AD domain" Is it in the browser cookies list? 

- Your message from your first response: `This flag has nothing to do with the sessionStorage. It is used when you want to skip the tokens already cached in the storage of your choice and make a call directly to the server for new tokens. Whatever response you get from the server is then cached into the storage. You can read more on token renewal [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md#how-do-i-renew-tokens-with-msaljs).` When it skips the tokens already cached in the storage of our choice(sessionStorage) and make a call directly to the server for new tokens. Does it `removeItem` from the storage of our choice, and `setItem` after it calls directly to the server to get the new tokens? 

Thank you very much!

**Comment by lalimasharda** [comment]
1. You can find out the session lifetime from the admin who set up the application in Azure portal.
2. I don't think so. I believe browser cookies are set for a different purpose.
3. Yes, it will the new tokens will completely replace the old ones.

**Comment by fong1999** [comment]
@lalimasharda Thank you very much! Very helpful!

**Comment by sameerag** [comment]
@fong1999 Hope all your questions are addressed above.

@derisen can we please check if we have good docs around force_refresh and the token lifetimes? I think we do but we can give a once over if any of the guidance above isn't captured or is hard to find.

**Comment by fong1999** [comment]
@sameerag  Thank you! 

That would be great if you can share that type of document on forceRefresh flag and related Azure AD topics once you have it. Thanks much!

**Comment by derisen** [comment]
@sameerag @fong1999 sorry for missing this. I think much of the discussion here is covered in [token-lifetimes doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/token-lifetimes.md#token-renewal)

**Comment by sameerag** [comment]
Thanks @derisen. @fong1999 Please add if you have any feedback, closing this now.
