### ISSUE TITLE
Angular 13/14 - not supported?

### ISSUE THREAD

**Issue by tiga05** [AzureAD/microsoft-authentication-library-for-js#5635]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Public or Confidential Client?

Public

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-angular#version-support

### Description

Are you sure you are supporting Angular Version 13/14?

Because I have found out you are not supporting Version 15 ( as stated here: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5410#issuecomment-1405758706).
So I tried to use Angular Version 14 which did not work in my project.
And it also did not work with your example( https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular14-rxjs7-sample-app) and version 13 ( https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular13-rxjs7-sample-app )
I get the same error as with version 15:
![image](https://user-images.githubusercontent.com/1228542/216059351-6f1c59d6-1355-4271-a4ab-b4d5e0d8dcaf.png)

 An looks like I am not the only one? ( https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4298#issuecomment-1407239912)

I am not really aware of the deep technical details of the issue. But as far as I know the exclusive ivy support was forced in Version 13. And since you are not supporting ivy, it should definitely not work in this versions?

Why are they then listed as supported versions? Could you please clarify your documentation about that?

**Comment by lalimasharda** [comment]
Hey @tiga05,

Can you please mention what version of msal-angular and msal-browser are you using? Also, could you please share verbose logs that you are seeing?

Thanks.
