### ISSUE TITLE
no way to obtain encoded id token from fresh UserAgentApplication

### ISSUE THREAD

**Issue by aappddeevv** [AzureAD/microsoft-authentication-library-for-js#564]
There appears to be no API to obtain the encoded id token.

Let's say I refresh the page. My UserAgentApplication is recreated.

I can get the User object fine via app.getUser. But there is no way to get the encoded id token. I see that localStorage has it under the key msal.idtoken, but there is no API for that. This felt like a gap.

Is this intentional to force us to choose our own storage mechanism?

**Comment by navyasric** [comment]
@aappddeevv Can you explain what is the use case where you want to obtain the encoded id token?
In Msal.js we do expose the idtoken through the User object as shown in the [reference](https://htmlpreview.github.io/?https://raw.githubusercontent.com/AzureAD/microsoft-authentication-library-for-js/dev/lib/msal-core/docs/classes/_user_.user.html). In other words, you can do userAgentApp.getUser().idtoken to get the idtoken claims. Does that work for your usecase?

**Comment by aappddeevv** [comment]
Completely missed that so that works for me.
