### ISSUE TITLE
handleRedirectPromise did not detect a response hash as a result of a redirect, why?

### ISSUE THREAD

**Issue by AKrousti** [AzureAD/microsoft-authentication-library-for-js#5640]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.5.2

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.32.2

### Public or Confidential Client?

Public

### Description

I have been using your Angular12 Sample App to intergrate MSAL with our existing application, however everytime I try to login i get redirected back to my application, however i am not logged in and get the following error: 

"Info - handleRedirectPromise did not detect a response hash as a result of a redirect. Cleaning temporary cache."

Do you have any ideas why this would be happening?

I havent added MsalGuard to any routes either, just trying to get a user logged in

### MSAL Configuration

```javascript
auth: {
      clientId: 'clientId', // PPE testing environment
      authority: 'https://login.microsoftonline.com/' + 'tenantId',
      redirectUri: 'https://localhost:4200',
      postLogoutRedirectUri: '/'
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      // storeAuthStateInCookie: isIE, // set to true for IE 11. Remove this line to use Angular Universal
    },
```

### Relevant Code Snippets

```javascript
const routes: Routes = [
  { path: 'trading', loadChildren: () => import('./components/pages/trading/trading.module').then(m => m.TradingModule),  canActivate: [AuthGuard], data: { breadcrumb: 'Trading'} },
  { path: 'datamaint-upload', loadChildren: () => import('./components/pages/bulk-upload/bulk-upload.module').then(m => m.BulkUploadModule), data: { breadcrumb: 'Bulk Upload'} },
  { path: 'notification-dashboard', loadChildren: () => import('./components/pages/notification-dashboard/notification-dashboard.module').then(m => m.NotificationDashboardModule), canActivate: [AuthGuard], data: { breadcrumb: 'Notification Dashboard'} },
  { path: 'dashboard', loadChildren: () => import('./dashboard/dashboard.module').then(m => m.DashboardModule), data: { breadcrumb: 'Analytics'} },
  { path: 'analytics', loadChildren: () => import('./analytics/analytics.module').then(m => m.AnalyticsModule), canActivate: [AuthGuard], data: { breadcrumb: 'Analytics'} },
  { path: 'datamaint', loadChildren: () => import('./datamaint/datamaint.module').then(m => m.DataMaintModule), canActivate: [AuthGuard], data: { breadcrumb: 'Data Maintenance'} },
  { path: 'unauthorized', component: UnauthorizedComponent },
  // { path: '', redirectTo: 'trading', pathMatch: 'full', data: { breadcrumb: ''} },
  { path: 'code' },
  
];
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by AKrousti** [comment]
Verbose logs are as follows too

[Thu, 02 Feb 2023 17:17:08 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : @azure/msal-browser@2.32.2 : Verbose - loginRedirect called
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:08 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : @azure/msal-browser@2.32.2 : Verbose - acquireTokenRedirect called
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:08 GMT] : @azure/msal-browser@2.32.2 : Verbose - preflightBrowserEnvironmentCheck started
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:08 GMT] : @azure/msal-browser@2.32.2 : Verbose - preflightInteractiveRequest called, validating app environment
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:08 GMT] : @azure/msal-browser@2.32.2 : Verbose - getAllAccounts called
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:08 GMT] : @azure/msal-browser@2.32.2 : Info - Emitting event: msal:loginStart
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:08 GMT] : @azure/msal-browser@2.32.2 : Verbose - Emitting event to callback 4ca3df65-8fae-469f-8ff9-dcf79b6298ce: msal:loginStart
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:08 GMT] : @azure/msal-angular@2.5.2 : Verbose - BroadcastService - msal:loginStart results in setting inProgress from none to login
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:08 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Verbose - initializeAuthorizationRequest called
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:08 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Verbose - getRedirectUri called
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:08 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Verbose - Initializing BaseAuthRequest
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:08 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Verbose - Authentication Scheme wasn't explicitly set in request, defaulting to "Bearer" request
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:08 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Verbose - initializeServerTelemetryManager called
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:08 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Verbose - initializeAuthorizationRequest called
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:08 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Verbose - getClientConfiguration called
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:08 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Verbose - getDiscoveredAuthority called
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:08 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Verbose - Creating discovered authority with configured authority
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:08 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Verbose - Attempting to get cloud discovery metadata in the config
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:08 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Verbose - Did not find cloud discovery metadata in the config... Attempting to get cloud discovery metadata from the cache.
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:08 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Verbose - Did not find cloud discovery metadata in the cache... Attempting to get cloud discovery metadata from the network.
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:08 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Verbose - Attempting to find a match between the developer's authority and the CloudInstanceDiscoveryMetadata returned from the network request.
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:08 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Verbose - cloud discovery metadata was successfully returned from getCloudDiscoveryMetadataFromNetwork()
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:08 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Verbose - Auth code client created
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:08 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Verbose - RedirectHandler.initiateAuthRequest called
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:08 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Verbose - RedirectHandler.initiateAuthRequest: redirectStartPage set, caching start page
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:08 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Verbose - RedirectHandler.initiateAuthRequest: Navigating window to navigate url
Navigated to https://login.microsoftonline.com/60e158be-aef8-4b44-89ec-03627b9fe7c2/oauth2/v2.0/authorize?client_id=5df3a0fc-83c6-4db0-a993-0ca355e69cc6&scope=user.read%20openid%20profile%20offline_access&redirect_uri=https%3A%2F%2Flocalhost%3A4200%2F&client-request-id=3d80d9af-45b5-46c3-850a-3e746051caef&response_mode=fragment&response_type=code&x-client-SKU=msal.js.browser&x-client-VER=2.32.2&client_info=1&code_challenge=BDeh1cdX5jk5tzYvmTDCZOku4FUe0VqDApCAZcw-CLQ&code_challenge_method=S256&nonce=ed919b61-3a8e-4552-b920-530efce44c62&state=eyJpZCI6IjAxNmE3YjQ2LWQ1ZDEtNGQ0Yi1hM2E0LThmNDQxZWQ4Y2MwMSIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicmVkaXJlY3QifX0%3D
Navigated to https://localhost:4200/
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:14 GMT] : @azure/msal-browser@2.32.2 : Verbose - BrowserCrypto: modern crypto interface available
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:14 GMT] : @azure/msal-browser@2.32.2 : Verbose - BrowserCrypto: modern crypto interface available
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:14 GMT] : @azure/msal-browser@2.32.2 : Verbose - Event callback registered with id: 36870985-0515-4225-ae0a-6427996d445f
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:14 GMT] : @azure/msal-browser@2.32.2 : Verbose - getAllAccounts called
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:14 GMT] : @azure/msal-browser@2.32.2 : Verbose - Adding account storage listener.
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:14 GMT] : @azure/msal-angular@2.5.2 : Verbose - MsalRedirectComponent activated
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:14 GMT] : @azure/msal-browser@2.32.2 : Info - Emitting event: msal:initializeStart
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:14 GMT] : @azure/msal-browser@2.32.2 : Verbose - Emitting event to callback 36870985-0515-4225-ae0a-6427996d445f: msal:initializeStart
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:14 GMT] : @azure/msal-browser@2.32.2 : Info - Emitting event: msal:initializeEnd
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:14 GMT] : @azure/msal-browser@2.32.2 : Verbose - Emitting event to callback 36870985-0515-4225-ae0a-6427996d445f: msal:initializeEnd
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:14 GMT] : @azure/msal-browser@2.32.2 : Verbose - handleRedirectPromise called
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:14 GMT] : @azure/msal-browser@2.32.2 : Verbose - getAllAccounts called
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:14 GMT] : @azure/msal-browser@2.32.2 : Info - Emitting event: msal:handleRedirectStart
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:14 GMT] : @azure/msal-browser@2.32.2 : Verbose - Emitting event to callback 36870985-0515-4225-ae0a-6427996d445f: msal:handleRedirectStart
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:14 GMT] : @azure/msal-angular@2.5.2 : Verbose - BroadcastService - msal:handleRedirectStart results in setting inProgress from startup to handleRedirect
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:14 GMT] : @azure/msal-browser@2.32.2 : Verbose - handleRedirectPromise has been called for the first time, storing the promise
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:14 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Verbose - initializeServerTelemetryManager called
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:14 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Verbose - getRedirectResponseHash called
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:14 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Verbose - Hash contains known properties, returning response hash
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:14 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Verbose - validateAndExtractStateFromHash called
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:14 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Verbose - Returning state from hash
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:14 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Verbose - State extracted from hash
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:14 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Verbose - Current page is loginRequestUrl, handling hash
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:14 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Verbose - handleHash called, retrieved cached request
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:14 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Verbose - getClientConfiguration called
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:14 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Verbose - getDiscoveredAuthority called
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:14 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Verbose - Creating discovered authority with configured authority
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:14 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Verbose - Attempting to get cloud discovery metadata in the config
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:14 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Verbose - Did not find cloud discovery metadata in the config... Attempting to get cloud discovery metadata from the cache.
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:14 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Verbose - Did not find cloud discovery metadata in the cache... Attempting to get cloud discovery metadata from the network.
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:15 GMT] : @azure/msal-angular@2.5.2 : Verbose - MSAL Interceptor activated
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:15 GMT] : @azure/msal-angular@2.5.2 : Verbose - Interceptor - getting scopes for endpoint
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:15 GMT] : @azure/msal-angular@2.5.2 : Verbose - Interceptor - no scopes for endpoint
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:15 GMT] : @azure/msal-angular@2.5.2 : Verbose - MSAL Interceptor activated
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:15 GMT] : @azure/msal-angular@2.5.2 : Verbose - Interceptor - getting scopes for endpoint
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:15 GMT] : @azure/msal-angular@2.5.2 : Verbose - Interceptor - no scopes for endpoint
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:16 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Verbose - Attempting to find a match between the developer's authority and the CloudInstanceDiscoveryMetadata returned from the network request.
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:16 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Verbose - cloud discovery metadata was successfully returned from getCloudDiscoveryMetadataFromNetwork()
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:16 GMT] : @azure/msal-browser@2.32.2 : Verbose - BrowserCrypto: modern crypto interface available
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:16 GMT] : @azure/msal-browser@2.32.2 : Verbose - BrowserCrypto: modern crypto interface available
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:16 GMT] : @azure/msal-browser@2.32.2 : Verbose - Event callback registered with id: 922a367e-04c5-4815-99df-df36621013b6
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:16 GMT] : @azure/msal-browser@2.32.2 : Verbose - getAllAccounts called
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:16 GMT] : @azure/msal-browser@2.32.2 : Verbose - Adding account storage listener.
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:16 GMT] : @azure/msal-angular@2.5.2 : Verbose - MsalRedirectComponent activated
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:16 GMT] : @azure/msal-browser@2.32.2 : Info - Emitting event: msal:initializeStart
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:16 GMT] : @azure/msal-browser@2.32.2 : Verbose - Emitting event to callback 922a367e-04c5-4815-99df-df36621013b6: msal:initializeStart
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:16 GMT] : @azure/msal-browser@2.32.2 : Info - Emitting event: msal:initializeEnd
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:16 GMT] : @azure/msal-browser@2.32.2 : Verbose - Emitting event to callback 922a367e-04c5-4815-99df-df36621013b6: msal:initializeEnd
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:16 GMT] : @azure/msal-browser@2.32.2 : Verbose - handleRedirectPromise called
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:16 GMT] : @azure/msal-browser@2.32.2 : Verbose - getAllAccounts called
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:16 GMT] : @azure/msal-browser@2.32.2 : Info - Emitting event: msal:handleRedirectStart
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:16 GMT] : @azure/msal-browser@2.32.2 : Verbose - Emitting event to callback 922a367e-04c5-4815-99df-df36621013b6: msal:handleRedirectStart
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:16 GMT] : @azure/msal-angular@2.5.2 : Verbose - BroadcastService - msal:handleRedirectStart results in setting inProgress from startup to handleRedirect
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:16 GMT] : @azure/msal-browser@2.32.2 : Verbose - handleRedirectPromise has been called for the first time, storing the promise
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:16 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Verbose - initializeServerTelemetryManager called
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:16 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Verbose - getRedirectResponseHash called
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:16 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Verbose - Hash does not contain known properties, returning cached hash
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:16 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Info - handleRedirectPromise did not detect a response hash as a result of a redirect. Cleaning temporary cache.
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:16 GMT] : @azure/msal-browser@2.32.2 : Info - Emitting event: msal:handleRedirectEnd
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:16 GMT] : @azure/msal-browser@2.32.2 : Verbose - Emitting event to callback 922a367e-04c5-4815-99df-df36621013b6: msal:handleRedirectEnd
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:16 GMT] : @azure/msal-angular@2.5.2 : Verbose - BroadcastService - msal:handleRedirectEnd results in setting inProgress from handleRedirect to none
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:16 GMT] : @azure/msal-angular@2.5.2 : Verbose - MSAL Interceptor activated
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:16 GMT] : @azure/msal-angular@2.5.2 : Verbose - Interceptor - getting scopes for endpoint
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:16 GMT] : @azure/msal-angular@2.5.2 : Verbose - Interceptor - no scopes for endpoint
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:16 GMT] : @azure/msal-angular@2.5.2 : Verbose - MSAL Interceptor activated
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:16 GMT] : @azure/msal-angular@2.5.2 : Verbose - Interceptor - getting scopes for endpoint
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:16 GMT] : @azure/msal-angular@2.5.2 : Verbose - Interceptor - no scopes for endpoint
VM8 polyfills.js:1 [WDS] Live Reloading enabled.
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:17 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Verbose - Auth code client created
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:17 GMT] : [3d80d9af-45b5-46c3-850a-3e746051caef] : msal.js.browser@2.32.2 : Verbose - RedirectHandler.handleCodeResponse called
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:17 GMT] : @azure/msal-browser@2.32.2 : Info - Emitting event: msal:loginFailure
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:17 GMT] : @azure/msal-browser@2.32.2 : Verbose - Emitting event to callback 36870985-0515-4225-ae0a-6427996d445f: msal:loginFailure
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:17 GMT] : @azure/msal-browser@2.32.2 : Info - Emitting event: msal:handleRedirectEnd
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:17 GMT] : @azure/msal-browser@2.32.2 : Verbose - Emitting event to callback 36870985-0515-4225-ae0a-6427996d445f: msal:handleRedirectEnd
VM10 main.js:1 [Thu, 02 Feb 2023 17:17:17 GMT] : @azure/msal-angular@2.5.2 : Verbose - BroadcastService - msal:handleRedirectEnd results in setting inProgress from handleRedirect to none
VM10 main.js:1 02-Feb-2023 05:17:19	Error	AppModule	AppErrorHandler	handleError()	state_not_found: State not found:  Cached State Params: stack: ClientAuthError: state_not_found: State not found:  Cached State
    at u [as constructor] (https://localhost:4200/main.js:1:2203081)
    at new u (https://localhost:4200/main.js:1:2213664)
    at u.createStateNotFoundError (https://localhost:4200/main.js:1:2215219)
    at u.<anonymous> (https://localhost:4200/main.js:1:2485924)
    at https://localhost:4200/main.js:1:2202204
    at Object.next (https://localhost:4200/main.js:1:2202316)
    at https://localhost:4200/main.js:1:2201214
    at new k (https://localhost:4200/polyfills.js:1:167875)
    at un (https://localhost:4200/main.js:1:2200926)
    at u.handleCodeResponseFromHash (https://localhost:4200/main.js:1:2485547)
VM8 polyfills.js:1 [WDS] Live Reloading enabled.

**Comment by lalimasharda** [comment]
Hey @AKrousti !

Is it possible that your application is somehow interfering with the hash?

**Comment by AKrousti** [comment]
Hi @lalimasharda 

In our app-routing.module.ts file we are using the following

@NgModule({
  imports: [RouterModule.forRoot(routes, { preloadingStrategy: PreloadAllModules, useHash: true })] ,
  exports: [RouterModule]
})

Could "useHash: true" be affecting the way its behaving?

Also after login, unless I have a path "code" defined i get the following error:
Cannot match any routes. URL Segment: 'code'

Why do I need a code path defined?

Thanks

**Comment by lalimasharda** [comment]
Hi @AKrousti 

It seems like useHash=true might remove the hash from the URL before MSAL could get to it. 

Please take a look at this [Angular 11 sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-angular-v2-samples/angular11-sample-app/src/app/app-routing.module.ts). 

We also have some guidance on using [hash or path location strategy](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/FAQ.md#authentication).

Please let me know if this helps!

**Comment by AKrousti** [comment]
Hi @lalimasharda 

I have gone through those examples and our applcation is following the Angular 11 Sample.

What I noticed was it looks like app.component.ts is being called twice whenever a page is loaded. Do you know if this would have an effect on the MSAL.

As a temporary test, I commented out a line in index.html, which now means app.component.ts ngOnit is being called once. However when doing this, I am now getting a different error: **Cross-origin token redemption is permitted only for the 'Single-Page Application' client-type. Request origin: 'https://localhost:4200'.** when calling the microsoft OAuth Token API

Any ideas how to solve this error? Our application is definetly single page app.

The line I have commented out in index.html is needed, but I cannot work out if I am dealing with 2 different errors (1 caused by index.html, the other this new issue above) or if both errors are because of the same thing

Thank you for the help so far

**Comment by sameerag** [comment]
> Cross-origin token redemption is permitted only for the 'Single-Page Application' client-type. Request origin: 'https://localhost:4200/'. when calling the microsoft OAuth Token API

@AKrousti Is your app registered as a SPA in the Azure Portal? The instructions can be found [here](https://learn.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-app-registration#redirect-uri-msaljs-20-with-auth-code-flow).

**Comment by gitsofkhaleel** [comment]
any solution for this issue? in local it works. in server it doesn't work
