### ISSUE TITLE
Prevent account mix-up at login after acquireTokenRedirect

### ISSUE THREAD

**Issue by Tan-Aki** [AzureAD/microsoft-authentication-library-for-js#5642]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.29.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.8

### Public or Confidential Client?

Public

### Description

**=> We have a react app that uses msal.**
Our whole app rendering is dependant on the success of a custom _getUserInfo(localAccountId)_ request made toward our backend.
For every request made to our backend, we have an axios interceptor that uses the _acquireTokenSilent_ method to check if the access token is expired or not.
If the access token is expired, but the refresh token is still valid, it will automatically renew the access token (regular behavior of the _acquireTokenSilent_ method).
If both the access token and the refresh token are expired, in the _catch()_ block of the _acquireTokenSilent_, we use the _acquireTokenRedirect_ method to redirect our user to a B2C login page.
The refresh token expires after 24 hours.

**=> We have a bug when the following scenario occurs:**
The user logs in with credentials "A1" and waits 24 hours without doing anything on the app (both the access token and the refresh are thus expired).
When the user starts interacting with the app again after this period, thanks to the _acquireTokenRedirect_ method, he is redirected to the B2C login page.
He decides to enter some other credentials "B2" at the B2C login page.
Bug: When he does log in successfully with the "B2" credentials, he finds himself connected to the app with the "A1" credentials when he should be connected with the "B2" credentials.

**=> We think we have identified where the probleme lies.** 
It is because we always use the _accounts[0].localAccountId_  (accounts object retrieved from the _useMsal()_ hook) to make our _getUserInfo()_ call to our backend. 
(so it looks like this : _getUserInfo(accounts[0].localAccountId)_)
The problem is, when we successfully authenticate with the "B2" credentials, the local storage gets populated with a whole new set of tokens without wiping the previous user's tokens, the accounts array thus has two entries, yet we still use the _accounts[0]_ entry.

**=> What would the best practice to make sure we make the _getUserInfo()_ call with the _localAccountId_ of the last logged in user?**
1/We were thinking of maybe clearing the cache right before the _acquireTokenRedirect_ happens. But we cannot find a clearCache method or something along these lines in the library. Are there any? If not, could/should we use the vanilla  _localStorage.clear()_ method to try and delete only the msal related entries? 
2/ We could maybe compare the auth_time of the accounts object and take the most recent one?
3/ Note: We used the _handleRedirectPromise_ method at the root of our app the set an active account with _setActiveAccount()_ but it seems there might be a bug with our approach, hence us wondering if there are other options.

Hope that makes sense.

Thank you!

(For SEO, some additional "tags" :
Wrongly wrong problem authenticated authentication connected with previously previous old logged in signed in user account info credentials token cache local storage  B2C)  

### MSAL Configuration

```javascript
export const msalConfig = {
    auth: {
        clientId: configurations.ClientId,
        authority: configurations.AuthoritySignIn,
        knownAuthorities: configurations.KnownAuthorities,
        redirectUri: configurations.RedirectUri,
    },
    cache: {
        cacheLocation: 'localStorage',
        storeAuthStateInCookie: false,
    },
};
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by lalimasharda** [comment]
Can you try using getAllAccounts() and retrieving the account that you are looking for from the resulting list?

Example:
`const currentAccounts = myMSALObj.getAllAccounts();`

**Comment by Tan-Aki** [comment]
Thank you for the answer!
How do you suggest we retrieve the account we are looking for?
Would comparing the auth_time be a good idea as mentionned in point 2/?

Do you also have the answer on whether or not there is some sort of msal clearcache method?

Thank you!

**Comment by lalimasharda** [comment]
I would suggest you to remember the account you want to set as the active account. Or you can maybe retrieve the account using username (may not be unique enough) or accountId.

**Comment by Tan-Aki** [comment]
Hi,

Thank you for your answers.

We managed to make it work thanks to the _handleRedirectPromise()_ and _setActiveAccount()_ methods.
Not sure it's the right approach, but, for future seekers, it looks something like this:

In the body of App.tsx functional component:

```
    **some code**

    const { instance, inProgress } = useMsal();
    const isAuthenticated = useIsAuthenticated();
    // Initialized with useAccount() that will return an active account if there is one (useful for page refreshes)
    const [activeAccount, setActiveAccount] = useState<AccountInfo | null>(useAccount());

    useEffect(() => {
        // Setting (once) the active account for every future redirection from B2C
        // (acts a bit like an axios interceptor it seems)
        instance
            .handleRedirectPromise()
            .then((tokenResponse) => {
                if (tokenResponse) {
                    instance.setActiveAccount(tokenResponse.account);
                    setActiveAccount(tokenResponse.account);
                }
            })
            .catch((error) => {
                // Handle redirect error if desired
            });
    }, [instance]);


    // At login and at page refreshes this will make the getUserInfo() call to our backend 
    useEffect(() => {
        if (isAuthenticated && activeAccount && inProgress === InteractionStatus.None) {
           getUserInfo(activeAccount.localAccountId);
        }
        // A "shadow" state for activeAccount is needed because we cannot rely on instance nor on instance.getActiveAccount as dependencies?
        // (because of shallow reference equality checks I suppose?)
    }, [isAuthenticated, inProgress, activeAccount]);

    **some code**

```

Afterwards, everytime we need to access the active account  we can do it this way:

`const activeAccount = instance.getActiveAccount();`

(or we could also access it with the _useAccount()_ hook that will return an active account if any:
`const activeAccount = useAccount();`) 

As an exemple, we can then use the thus  retrieved activeAccount in our axios interceptor, before we call the _acquireTokenSilent()_:

```
    **some code**
    
    const activeAccount = instance.getActiveAccount()

    instance
        // This will use the access token in the browser cache if already present or not expired
        // and will also try to use the refresh token to renew the access token in case it was expired
        .acquireTokenSilent({
            scopes: loginRequestConfig.scopes,
            account: activeAccount,
        })
        .then((accessTokenResponse) => accessTokenResponse.accessToken)
        .catch((error) => {
            // If silent token acquisition fails, redirect user to login screen.
            if (error instanceof InteractionRequiredAuthError) {
                msalInstance.acquireTokenRedirect({
                    scopes: loginRequestConfig.scopes,
                    account: activeAccount,
                });
            }
        })
        
    **some code**
    
```
