### ISSUE TITLE
endpoints_resolution_error: Error: could not resolve endpoints

### ISSUE THREAD

**Issue by rizaldirpamungkas** [AzureAD/microsoft-authentication-library-for-js#5646]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

Latest

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Confidential

### Description

I was trying to acquire token from our Microsoft tenant. I have no knowledge about the Azure AD or whatsoever, because I only tasked to develop front end for our Microsoft Dynamics App in React. I only got some of the credential like tenant id, client id, client secret and resource.

I used MSAL Node library and function ConfidentialClientApplication() to acquire the token

But when I check it in the Ms. Edge's console log it throw an error

> {"errorCode":"endpoints_resolution_error","errorMessage":"Error: could not resolve endpoints. Please check network and try again. Detail: ClientAuthError: openid_config_error: Could not retrieve endpoints. Check your authority and verify the .well-known/openid-configuration endpoint returns the required endpoints. Attempted to retrieve endpoints from: verify url","subError":"","name":"ClientAuthError","correlationId":""}

When I click the veryfy url (Cannot show you the url because it might contain sensitive information) It shows all the metadata of the open id so I thought maybe it's normal. But why is the error endpoints_resolution_error throwed when everything is normal?

BTW here is the metadata I got from OpenID

> {"token_endpoint":"https://login.microsoftonline.com/*tenant-id*/oauth2/token","token_endpoint_auth_methods_supported":["client_secret_post","private_key_jwt","client_secret_basic"],"jwks_uri":"https://login.microsoftonline.com/common/discovery/keys","response_modes_supported":["query","fragment","form_post"],"subject_types_supported":["pairwise"],"id_token_signing_alg_values_supported":["RS256"],"response_types_supported":["code","id_token","code id_token","token id_token","token"],"scopes_supported":["openid"],"issuer":"https://sts.windows.net/*tenant-id*/","microsoft_multi_refresh_token":true,"authorization_endpoint":"https://login.microsoftonline.com/*tenant-id*/oauth2/authorize","device_authorization_endpoint":"https://login.microsoftonline.com/*tenant-id*/oauth2/devicecode","http_logout_supported":true,"frontchannel_logout_supported":true,"end_session_endpoint":"https://login.microsoftonline.com/*tenant-id*/oauth2/logout","claims_supported":["sub","iss","cloud_instance_name","cloud_instance_host_name","cloud_graph_host_name","msgraph_host","aud","exp","iat","auth_time","acr","amr","nonce","email","given_name","family_name","nickname"],"check_session_iframe":"https://login.microsoftonline.com/*tenant-id*/oauth2/checksession","userinfo_endpoint":"https://login.microsoftonline.com/*tenant-id*/openid/userinfo","kerberos_endpoint":"https://login.microsoftonline.com/*tenant-id*/kerberos","tenant_region_scope":"AS","cloud_instance_name":"microsoftonline.com","cloud_graph_host_name":"graph.windows.net","msgraph_host":"graph.microsoft.com","rbac_url":"https://pas.windows.net"}

### MSAL Configuration

```javascript
const config = {
      auth: {
        clientId: **SECRET**,
        authority: "https://login.microsoftonline.com/**SECRET**/,
        clientSecret: **SECRET**,
        knownAuthorities: ["login.microsoftonline.com"],
        protocolMode: "OIDC"
      }
    }
```

### Relevant Code Snippets

```javascript
const clientCredentialRequest = {
  scopes: [**SECRET**"/.default"], // replace with your resource
};

cca.acquireTokenByClientCredential(clientCredentialRequest).then((response) => {
  console.log("Response: ", response);
}).catch((error) => {
  console.log(JSON.stringify(error));
});
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by lalimasharda** [comment]
Hey @rizaldirpamungkas,

Can you please explain why you are using "login.microsoftonline.com" in known authorities? Can you try removing it at retrying?

@derisen can you please help out here with the usage?

**Comment by rizaldirpamungkas** [comment]
It gives me error, if I don't put the known authorities. Here is the error

> Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter.","subError":"","name":"ClientAuthError"

**Comment by derisen** [comment]
@rizaldirpamungkas seems like you are way off. You mention this is React app, so most likely you wan to build a single-page application using [msal-react](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-react) to sign-in users and call some Microsoft APIs? Have a look at the tutorials [here](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial). It's also a good idea to get familiar with app types and scenarios mentioned [here](https://learn.microsoft.com/en-us/azure/active-directory/develop/authentication-flows-app-scenarios).

Let us know if this helps.

**Comment by rizaldirpamungkas** [comment]
Hi @derisen, yeah I tried using msal-react as well before but so far I can't find the function to retrieve token using shared secret in which that's the only way I can access the token for the API

**Comment by sameerag** [comment]
@rizaldirpamungkas Can you explain your use case? Why are you using client credentials grant with a React App? Any high level description of your use case may help us enable you better.

**Comment by rizaldirpamungkas** [comment]
I currently build a UI app using React for the custom module in our Dynamics 365 ERP, to be able to access the API that Dynamics serve I need to get access token from login.microsoft.com . The only thing I get to have that access token was just client id, tenant id, client secret and resource. So in this app we're not really using SSO type of auth with pop up login window. And since the only viable library match my use case was MSAL Node, so that's why I use that. I hope my explanation clear, thanks

**Comment by derisen** [comment]
> Hi @derisen, yeah I tried using msal-react as well before but so far I can't find the function to retrieve token using shared secret in which that's the only way I can access the token for the API

@rizaldirpamungkas not entirely sure what you're referring with "shared secret", but in general you cannot have secrets in a browser app. For acquiring an access token and calling an API on the browser side, please have a look at:

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/acquire-token.md
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/resources-and-scopes.md

**Comment by rizaldirpamungkas** [comment]
Ok, thanks think I have to change my approach now, if it's possible
