### ISSUE TITLE
Login Popup using JS on .net MVC the popup not closed but the popup link already contain hash

### ISSUE THREAD

**Issue by dewade22** [AzureAD/microsoft-authentication-library-for-js#5659]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.32.2

### Wrapper Library

Not Applicable

### Wrapper Library Version

-

### Public or Confidential Client?

Public

### Description

I have implement the login popup, but after the user login the popup not closed and the link on popup always my redirecturi#state=eyJpCl6lm........

the redirect uri already use a blank html page, and in the controller that not have authorized attribute

I'm using .net MVC 5 for the app

Note: I have check my config with single spa sample but that's not issue.
No error on console app and popup app, last network call in popup is the redirect uri

in my app console
[Tue, 07 Feb 2023 09:27:41 GMT] : @azure/msal-browser@2.32.2 : Info - Emitting event: msal:loginStart
[Tue, 07 Feb 2023 09:27:41 GMT] : @azure/msal-browser@2.32.2 : Info - Emitting event: msal:popupOpened

### MSAL Configuration

```javascript
{
 auth: {
        clientId: "c2d5d3ff-xxxx-xxxx-xxxx-xxxxxxx",
        authority: "https://<tenant-name>.b2clogin.com/tfp/<tenant-name>.onmicrosoft.com/<policy-id>",
        knownAuthorities: ["<tenant-name>.b2clogin.com"],
        redirectUri: window.location.origin,
    },
    cache: {
        cacheLocation: "sessionStorage",
        storeAuthStateInCookie: false,
    },
}
```

### Relevant Code Snippets

```javascript
-
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by sameerag** [comment]
@dewade22 Can you please share more detailed logs collected from MSAL JS as instructed [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logging.md)?

Also please send me the network logs, my email is listed in my [profile](https://github.com/sameerag).

**Comment by dewade22** [comment]
Thanks for your reply,
as I mention above, in my app the msal logs only stuck with the last status popup opened
I will send it by email
Thankyou

From the hash in msal popup I only get the parameter Client_info, code and state.

**Comment by tnorling** [comment]
@dewade22 I just took a look at your trace and it's all encrypted so I unfortunately can't see the traffic. I did notice in the screenshot you shared that an error was thrown that the popup window was closed. Is it possible that your B2C policy is opening a new popup window to the federated IDP and closing the original one?

**Comment by dewade22** [comment]
Oh sory about the log, that all was record by fidler app.
For the popup, no thats's not closing, I close it manually because that stuck.
For now, because it cannot close and cannot get the token, I have manually read the user from directory by the client_info on the popup. I just using the login popup for register the user, that was solve my problem for now

**Comment by tnorling** [comment]
Is the main window and the popup window on the same domain?

**Comment by dewade22** [comment]
Same domain (localhost and now in production) and the redirect uri already register in AD

**Comment by tnorling** [comment]
Can you make sure Fiddler is configured to decrypt https, collect another trace and email it to me? Thanks!

**Comment by dewade22** [comment]
I have email it to you, Thankyou
Note: the issue only occurs in .net MVC with framework 4.7.2, I test it on .net core but it's run correctly

**Comment by tnorling** [comment]
@dewade22 I got a video but not a network trace. Could you please send a network trace? Thanks!
