### ISSUE TITLE
getAllAccounts returns an empty array in mobile browsers

### ISSUE THREAD

**Issue by benjblack** [AzureAD/microsoft-authentication-library-for-js#5667]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.32.2

### Wrapper Library

Not Applicable

### Wrapper Library Version

n/a

### Public or Confidential Client?

Public

### Description

getAllAccounts() returns an empty array in mobile browsers. Tested in multiple mobile browsers and devices. iPhone and Android.

It works on PC browser though - also tested in multiple browsers and devices. Works in Edge/Chrome on PC, Safari/Chrome on Mac.

### MSAL Configuration

```javascript
const timeoutms = 30000;
let msalConfig = {
	auth: {
		clientId: <client id of Azure Fn App Svc App Registration>
		authority: authority,
		redirectUri:  "https://ktslaw.sharepoint.com/sites/AuthenticateStaging/SitePages/RedirectHandler.aspx",
		cache: {
			cacheLocation: BrowserCacheLocation.SessionStorage, 
			storeAuthStateInCookie:false,
		},    
		system: {
			windowHashTimeout: timeoutms,
			iframeHashTimeout: timeoutms,
			loadFrameTimeout: timeoutms,
		},
	}
};
```

### Relevant Code Snippets

```javascript
const publicClientApplication = new PublicClientApplication(msalConfig);      
const accounts = publicClientApplication.getAllAccounts();
console.log('msal accounts: ' + JSON.stringify(accounts));
```

### Reproduction Steps

This is a SharePoint SPFx application calling an Azure Function API. Everything is wired up correctly and is working - we have followed the configuration steps to switch from ADAL to MSAL. The user logs in to SharePoint first, so acquireTokenSilent (below) works, but only on PC - not sure why it's not working in mobile browsers.

`      const ssoRequest:any = {
        scopes: azureSvcInfo.MsalScopes,
        account: accounts[0],
        redirectUri: azureSvcInfo.AuthRedirectUrl
      };
      return publicClientApplication.acquireTokenSilent(ssoRequest)
`

### Expected Behavior

Output in mobile browser console is: 
`msal accounts: []`

Output in PC browser console is: 
`msal accounts: [{"homeAccountId":"<guid>","environment":"login.windows.net","tenantId":"<tenant guid>","username":"<email address>","localAccountId":"<guid>","name":"<user name>","idTokenClaims":{"aud":"<client id of Azure Fn App Svc App Registration>","iss":"https://login.microsoftonline.com/f4a1ab02-c5fc-4301-b2ae-301b19ba59d2/v2.`

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Other

### Regression

asdf

### Source

External (Customer)

**Comment by sameerag** [comment]
@benjblack Can you confirm the accounts are being written to the `sessionStorage` in the mobile browser?

**Comment by benjblack** [comment]
@sameerag  Under Local Storage I see keys:

sessionTracking_10037FFE8B43A342 | {"authenticatedState":1,"upn":"myuser@companydomain.com","idp":"aad","lastActiveTime":1675952625165}
sessionTracking_SignedInAccountList | [{"sessionTrackingKey":"sessionTracking_10037FFE8B43A342","lastActiveTime":1675952625165}]

Under Session Storage, the only item matching the AAD application client id is:

server-telemetry-<CLIENTID> |
{"failedRequests":[863,"14154f68-d7a5-404b-aa8c-337c88c161ee",863,"6bcd27c5-7380-45ec-a2f3-8434e8ffa19d"],"errors":["monitor_window_timeout","monitor_window_timeout"],"cacheHits":0}

Other Session Storage items (redacted) are attached.
[msal - Sheet1.csv](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/10698400/msal.-.Sheet1.csv)

On PC, there is a Session Storage key named msal.idtoken with the token.

**Comment by benjblack** [comment]
Login to our SharePoint tenant uses MFA / I use the Microsoft Authenticator app. Not sure if this is relevant though - the authentication process is same via PC or mobile browser.

**Comment by sameerag** [comment]
I do not think it is MFA. It could be something with the storage in Mobile browsers. 
Note: Linking some similar issues here: #5617

**Comment by benjblack** [comment]
I looked at issue #5617 you referenced above which confirms the issue but provides no resolution. Microsoft is deprecating ADAL so we switched to MSAL - but mobile browsers aren't supported as before?!?

**Comment by tnorling** [comment]
@benjblack Just looking through the .csv you shared it looks like interaction is in progress, meaning if you're using redirects,  `handleRedirectPromise` has not been called or has not completed. The accounts array will not be populated until that's done.

**Comment by devanshuGit** [comment]
I followed similar article for implementing MSAL 2.0 in SPFX using @azure/msal-browser pacakge
https://mmsharepoint.wordpress.com/2020/08/15/using-msal-js-2-0-in-sharepoint-framework-spfx/, MSAL is integrated and it works fine to call Graph or Custom API protected with Azure AD.

We are facing problem with multiple accounts and handling it. SharePoint allows switch user using ‘sign in as different user’, so in same session (browser window/tab) allows to sign in with different account (interactive) and also msal config has cache set to sessionStorage. When we do that, MSAL still takes previous user (current account). Event with getAllAccounts() it only return 1 account of previous user so it silently generates token for that user and data for that user is being fetched. We were expecting to get multiple account from MSAL and then from current logged-in user use correct account to work with to get tokens. But this is kind of security concern as well as one user can see data of another user.
Also getAccountByUsername() returns null even by passing user login from page context.

Any help in this regards?

**Comment by xinzhaozhang1985** [comment]
> I followed similar article for implementing MSAL 2.0 in SPFX using @azure/msal-browser pacakge https://mmsharepoint.wordpress.com/2020/08/15/using-msal-js-2-0-in-sharepoint-framework-spfx/, MSAL is integrated and it works fine to call Graph or Custom API protected with Azure AD.
> 
> We are facing problem with multiple accounts and handling it. SharePoint allows switch user using ‘sign in as different user’, so in same session (browser window/tab) allows to sign in with different account (interactive) and also msal config has cache set to sessionStorage. When we do that, MSAL still takes previous user (current account). Event with getAllAccounts() it only return 1 account of previous user so it silently generates token for that user and data for that user is being fetched. We were expecting to get multiple account from MSAL and then from current logged-in user use correct account to work with to get tokens. But this is kind of security concern as well as one user can see data of another user. Also getAccountByUsername() returns null even by passing user login from page context.
> 
> Any help in this regards?

Have you solved your issues?
We are facing similar problem when use SPFX with @azure/msal-browser. However when multiple users log into the sharepoint, we get empty accounts when calling getAllAccounts(). With single user logs in everything works fine. I could not work out why the accounts are empty. We are still using 
    "@azure/msal-browser": "^2.38.3",
    "@azure/msal-react": "^1.5.12", since upgrade to the latest version requires a lot more work and we are not sure if the latest package can solve the problem or not.
