### ISSUE TITLE
Custom UAA Server with PKCE: offline_access is added despite provided scopes

### ISSUE THREAD

**Issue by sandrooco** [AzureAD/microsoft-authentication-library-for-js#5674]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.33.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.5.3

### Public or Confidential Client?

Public

### Description

I do use a custom UAA, not AAD. This server doesn't support the "offline_access" scope which is always added for clients with authorization code grant (see `RequestParameterBuilder.addScopes`).

When I try to make a login request the error `offline_access is invalid. Please use a valid scope name in the request` is thrown.

How can I prevent the default scopes to be added? My custom scopes are provided, I don't need additional default ones.

### Error Message

`offline_access is invalid. Please use a valid scope name in the request`

### MSAL Configuration

```javascript
{
  auth: {
    protocolMode: ProtocolMode.OIDC,
    authorityMetadata: JSON.stringify({
      authorization_endpoint: baseUrl + '/oauth/authorize',
      token_endpoint: baseUrl + '/oauth/token',
      jwks_uri: baseUrl + '/token_keys',
    }),
    redirectUri: 'http://localhost:3000',
    clientId: config.auth.clientId,
  },
}
```

### Relevant Code Snippets

```javascript
const login = () => {
    msalInstance.loginRedirect({
      scopes: [
        'phone',
        'openid',
        'roles',
        'profile',
        'user_attributes',
        'email',
      ],
    });
  };
```

### Reproduction Steps

I fear I can't give you a full repro because the UAA is internal.

### Expected Behavior

I'd expect to only have the scopes  phone, openid, roles, profile, user_attributes and email in the login request, without offline_access.

### Identity Provider

Other

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari

### Source

External (Customer)

**Comment by sameerag** [comment]
@sandrooco We add `offline_access` as a default scope as it is expected be present for the issuance of refresh token as per the [OIDC Spec](https://openid.net/specs/openid-connect-core-1_0.html#OfflineAccess). 

Let me revert if we can make it optional for use cases like yours, we decided to keep it after some analysis in the past.

**Comment by sandrooco** [comment]
Thanks for the quick feedback! Then I will consult with the UAA server's provider.

**Comment by sameerag** [comment]
Thanks. At this point I am inclined not to change on our end for a special case. Closing.

**Comment by wedevops1** [comment]
Just want to link [this issue](https://github.com/MicrosoftDocs/azure-docs/issues/107811) which is mine as well as [this issue](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/3649). 

If one wants to control the session time of in a B2C tenant (according to the multiple sources as seen in the first linked issue) the `offline_access` scope **has** to be omitted. 

Just closing the issue won't solve the problem folks.
