### ISSUE TITLE
AcquireToken for api

### ISSUE THREAD

**Issue by PrasannaKolla** [AzureAD/microsoft-authentication-library-for-js#568]
I have an angular 7 client app and .net core webapi.  I am able to get id token when I login.

The problem is when I try to get access token for my .net core webapi(which is a different app service), I am getting the below error

The application named api://<ClientID of my .net core api> was not found in the tenant named <Tenant ID>.  This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant.  You might have sent your authentication request to the wrong tenant.

Both My UI app service and .net core web api are registered in the same Tenant.

Not sure what I am missing.

Attached the sample code which I was trying.

**app.module.ts**
imports: [
    MsalModule.forRoot({
      clientID: environment.azureClientId,
      authority: "https://login.microsoftonline.com/<tenant>/",
      redirectUri: "http://localhost:4200/",
      validateAuthority : true,
      cacheLocation : "localStorage",
      popUp: false,
      postLogoutRedirectUri: "http://localhost:4200/",
      consentScopes: ["https://graph.microsoft.com/.default"],      
      navigateToLoginRequestUrl : true,
      })

AuthService : 

public getToken() {        
        return this.Msal.acquireTokenSilent(['api://<Web API ClientID>/access_as_user'])
            .then(accessToken => {
                return accessToken;
            }, error => {
}
})

and calling getToken() method which is in authservice from app.component.ts.

I am not sure what scope should I give for WebAPI Client ID.

I would really appreciate if I can can get any code sample to call web api other than graph.

**Comment by zamzowd** [comment]
Your scopes passed to `acquireTokenSilent` should be defined on your API's registration in the tenant.  The full scope names might not necessarily match the actual url of your application, depending on how it's registered.

For example, after registering an application to my Azure AD tenant, the scopes I can create for the application get named using the following pattern:
```
https://{tenant}/{clientId}/{scope}
```
For applications in my Azure AD B2C tenant, the scopes I can create for the application get named using the following pattern:
```
https://{tenant}.onmicrosoft.com/{app}/{scope}
```

In both of these, I have a little bit of control over what the "APP ID URI" is.  You should be able to see how scopes are named for applications in your tenant.

**Comment by PrasannaKolla** [comment]
I figured out scopes, I have passed .default for APIs, then it started working. Thank you
