### ISSUE TITLE
Any way to conditionally attach a token to an API call only if signed in? 

### ISSUE THREAD

**Issue by mattcheah** [AzureAD/microsoft-authentication-library-for-js#5691]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.31.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.4.6

### Public or Confidential Client?

Public

### Description

I have an api call that can be called as an authenticated call or unauthenticated (and returns more data with an authenticated call) 
Is there any way to conditionally attach a token if the user is authenticated but to send it anyway without the token if not? 

### MSAL Configuration

```javascript
MsalModule.forRoot(
      new PublicClientApplication(msalConfig),
      {
        // The routing guard configuration.
        interactionType: InteractionType.Popup,
        authRequest: {
          scopes: scopes,
        },
      },
      {
        // MSAL interceptor configuration.
        // The protected resource mapping maps your web API with the corresponding app scopes. If your code needs to call another web API, add the URI mapping here.
        interactionType: InteractionType.Popup,
        protectedResourceMap: new Map([
          [env.apiUrl + 'Admin/*', scopes],
          [env.apiUrl + 'Shared/*', scopes],
        ]),
      }
    ),
```

### Identity Provider

Azure B2C Basic Policy

### Source

External (Customer)

**Comment by derisen** [comment]
@mattcheah @hectormmg the [interceptor configuration](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/msal-interceptor.md#configuration) has an optional `authRequest` property that allows you to access request properties and the msal service, which you might be able to use with your scenario to dynamically set the behavior. See these for more:

- https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/multi-tenant.md#dynamic-auth-request
- https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/src/msal.interceptor.config.ts

**Comment by mattcheah** [comment]
Thank you @derisen. 
The documentation you linked recommended a way to change the authority of the authRequest with a multi-tenant setup. Do you know of any way to prevent the user from being prompted to sign in and just allowing the request to go through? 

In other words, potentially bypassing the MSAL interceptor if there is no active account? 

Thank you for your help!

**Comment by derisen** [comment]
@mattcheah @jo-arroyo sorry for the late response. Yes, I should have mentioned, the doc I linked mentions a different problem, but the API usage is the same (dynamic auth request). Anyways I've just given this a shot, here's one way this could work:

```typescript
export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
  const protectedResourceMap = new Map<string, Array<string> | null>();
  protectedResourceMap.set('https://graph.microsoft.com/v1.0/me/', ['user.read']);

  return {
    interactionType: InteractionType.Redirect,
    protectedResourceMap,
    authRequest: (msalService, httpReq, originalAuthRequest) => {
      const accounts = msalService.instance.getAllAccounts();

      if (!accounts || accounts.length < 1) {
        protectedResourceMap.set('https://graph.microsoft.com/v1.0/me/', null); // reconfigure protectedResourceMap
        throw new Error('No accounts detected'); // catch this error in the component making the http request and handle
      }

      return originalAuthRequest;
    }
  };
}
```

Other than that, your options are:

1) don't use the interceptor i.e. use the acquireToken* APIs directly before making an http request (if there is an account), or make an unauthenticated request (if there is no account)
2) Create your custom interceptor based on the msal interceptor
3) make a feature request for msal interceptor

Let me know if this helps!

**Comment by mattcheah** [comment]
Thanks @derisen, 
Setting the protectedResourceMap scopes value to `null` didn't work for me, nor did removing the value from the map completely - but I'll see what I can do without the interceptor, or just change my API. Thanks for your help!
