### ISSUE TITLE
Issues with Two same instance of login screen in same browser window 

### ISSUE THREAD

**Issue by ankushdaga11** [AzureAD/microsoft-authentication-library-for-js#5693]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.33.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.5.3

### Public or Confidential Client?

Public

### Description

We have implemented custom policies with azure adb2c and calling that through a client using MSAL Angular (Latest Version).

Curently using Localstorage to save MSAL Cache and tokens.

The issue we and most of our Customer are facing is they need to do MFA Twice.
We first thought it's an intermittent issue and occur for users logging into system after X no. of days and due to refresh token expiry the system invalidates the login and makes MFA request twice.

But recently we relesed a specific pattern when this issue occurs.

Whenever we start our application due to MSAL Guards it automatically redirect to a long b2c url defined in the cofiguration.

https://***.b2clogin.com/***.onmicrosoft.com/b2c_1a_mfa_phone_or_email/oauth2/v2.0/authorize?client_id=01c7**&scope=openid%20profile%20offline_access&redirect_uri=http%3A%2F%2Flocalhost%3A4200%2F&client-request-id=f5c7d413-257f-48ac-999c-6e1a213840b3&response_mode=fragment&response_type=code&x-client-SKU=msal.js.browser&x-client-VER=2.33.0&client_info=1&code_challenge=JUGPQlehE-bQxph7q4YnAzEJzs&code_challenge_method=S256&nonce=6b2a8c0f-22d0-483f-9065-6662910&state=eyJpZCI6IjhiZGQwMGI0LTBmMDEtNGQ0Zi05NTg2LTdlMTZlYjBkYTNiNCIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBl

If I open a new tab and hit the base url (localhost in this example) it again redirects to the b2c url but with new values in parameters like state , nounce and code challenge as well as request id.

Now if I switch to the old tab and hit login in the first place it erases the password , If I hit it again it asks me for MFA and redirects back to MFA screen again. After verifying MFA again it lets me inside the system.

Same thing works on newly open login page.
I want to get rid of thsi MFA loop (occuring Twice in my case but users have reported it more as well)

Any help to resolve this is Appreciated.

Thanks in Advance!

### Error Message

No Error Mesaage in console

### MSAL Configuration

```javascript
auth: {
      clientId: clientID,
      authority:authorityURL,
      navigateToLoginRequestUrl:true,
      redirectUri: http://localhost:4200/,
      postLogoutRedirectUri:http://localhost:4200/,
      knownAuthorities: **.b2clogin.com
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE // set to true for IE 11
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Info,
        piiLoggingEnabled: false
      }
    }
```

### Relevant Code Snippets

```javascript
NA
```

### Reproduction Steps

1. Open Two Tabs of Angular App
2. Try to login with the 1st Tab you used to open the application
3. Password field goes blank in first attempt
4. Try to input password again and hit enter
5. You will be presented with MFA twice 

### Expected Behavior

User should be able to login in first attempt irrescpective of which tab he choosed

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

Internal (Microsoft)

**Comment by ankushdaga11** [comment]
Reproduced the same issue on angular sample :

https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples

**Comment by tnorling** [comment]
This looks like a question for the B2C service team please follow the support instructions documented [here](https://learn.microsoft.com/en-us/azure/active-directory-b2c/support-options) and they should be able to provide further assistance.
