### ISSUE TITLE
How do I prevent MSAL doing a double redirect on login?

### ISSUE THREAD

**Issue by davestewart** [AzureAD/microsoft-authentication-library-for-js#5694]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.30.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

I'm running an SPA written in Vue, and am having issues with the login redirect.

When the login form is redirected back to my app, I use a route handler to handle the redirect, calling `msal.handleRedirectPromise()` and doing any additional work to store accounts, etc.

However, MSAL seems to do an additional _internal_ redirect to `#`:

```
/auth/redirect/login#state=...   <-- main redirect URI
/auth/redirect/login#            <-- some kind of internal redirect
```

You can see in the stack the `RedirectClient` doing this: 

![image](https://user-images.githubusercontent.com/132681/219426745-60b540aa-59f4-4966-b496-4cad4d2cea88.png)

Additionally, it seems to trigger a full page reload, which my app handles because it is now authenticated.

But I don't understand why any of this is happening; I've caught the browser redirect, MSAL has parsed the hash, I have the access token.

How do I stop this additional flow and handle things myself?

### MSAL Configuration

```js
{
  auth: {
    clientId: '...',
    authority: '...',
    knownAuthorities: [
      '...',
    ],

    // redirects
    redirectUri: '/auth/redirect/login',
    postLogoutRedirectUri: '/auth/redirect/logout',
    navigateToLoginRequestUrl: true,
  },
  cache: {
    cacheLocation: 'localStorage'
  },
 
```

### Identity Provider

Azure B2C Basic Policy

### Source

External (Customer)

**Comment by derisen** [comment]
@davestewart @hectormmg Can you also share the MSAL logs please?

What if you set the `navigateToLoginRequestUrl` to **false** in msal config and handle the navigation back to to login request page yourself in your route handler -does this help? See also the [vue.js sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-browser-samples/vue3-sample-app) that takes advantage of the app's router for msal redirects.

**Comment by hectormmg** [comment]
@davestewart rather than an actual redirect I believe this is the result of MSAL clearing the hash after parsing the auth code and other authentication parameters from the URL hash. This is done to avoid having important parameters visibly in the URL for longer than is required.

My guess is the reason the reload happens is your router interprets the URL change as a navigation event.

**Comment by davestewart** [comment]
Hi @derisen - I realised that after I posted and experimented with removing it.

Unfortunately (cc @hectormmg) the clearing of the hash triggers another route navigation, and if you're using route guards to run code on every route as I am, it seems to cause unexpected results as the previous route navigation (with full hash) has not yet completed, because MSAL triggers another navigation in the first route guard handler.

Ideally there could just be a `parseHash()` function like [Auth0](https://auth0.com/docs/libraries/auth0js#extract-the-authresult-and-get-user-info) have, and I would be trusted to navigate from there.

The problems I have with `handleRedirectPromise()` are:

- it's badly named; we're supposed to run it [on non-redirect routes](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-js-initializing-client-applications#handleredirectpromise)
- before using other MSAL functions (even in the [Vue example](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-browser-samples/vue3-sample-app/src/router/Guard.ts#L22))
- it does too much; in this case clearing the hash and triggering additional navigation

On a side note, I also tried to use `extraQueryParameters` to pass through the current page, hoping that it would be passed back in the redirect, but it wasn't.

Is this a valid approach, or have I misunderstood what it is supposed to do?

PS. I'll take a look at the Vue example again. FWIW it's not great Vue code; did not expect to find so much spaghetti in a Microsoft sample.

**Comment by derisen** [comment]
@davestewart @jo-arroyo Apologies for the late response

> Hi @derisen - I realised that after I posted and experimented with removing it.
> 
> Unfortunately (cc @hectormmg) the clearing of the hash triggers another route navigation, and if you're using route guards to run code on every route as I am, it seems to cause unexpected results as the previous route navigation (with full hash) has not yet completed, because MSAL triggers another navigation in the first route guard handler.
> 
> Ideally there could just be a `parseHash()` function like [Auth0](https://auth0.com/docs/libraries/auth0js#extract-the-authresult-and-get-user-info) have, and I would be trusted to navigate from there.
>
> The problems I have with `handleRedirectPromise()` are:
> 
> * it's badly named; we're supposed to run it [on non-redirect routes](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-js-initializing-client-applications#handleredirectpromise)
> * before using other MSAL functions (even in the [Vue example](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-browser-samples/vue3-sample-app/src/router/Guard.ts#L22))
> * it does too much; in this case clearing the hash and triggering additional navigation

Please feel free to make a [feature request](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/new/choose) here.

> On a side note, I also tried to use `extraQueryParameters` to pass through the current page, hoping that it would be passed back in the redirect, but it wasn't.
> 
> Is this a valid approach, or have I misunderstood what it is supposed to do?

You should look into making use of the OAuth `state` parameter, instead of `extraQueryParameters`. See [here](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-js-pass-custom-state-authentication-request) for more (the article is slightly outdated unfortunately, but the main idea applies i.e. you attach this string to the request and receive it back in the response).

> PS. I'll take a look at the Vue example again. FWIW it's not great Vue code; did not expect to find so much spaghetti in a Microsoft sample.

Sorry to hear that. We welcome contributions from the community -please feel free to open a PR.

**Comment by davestewart** [comment]
Hey @derisen - thanks for the response. Will weigh up the options and go from there!

**Comment by davestewart** [comment]
Hello,

I wanted to get back to this ticket as I'd left it hanging.

In the end I rewrote our authentication to use popup interaction, which solved the double-navigation issue. It also seems generally to be a cleaner way to authenticate, rather than bouncing through various URIs and routes in the app.

I wrote up my journey of using the library for the first time – which I think is a fair appraisal – along with an accompanying repo which demos authentication using popup interaction only:

- [A guide to MSAL authentication in Vue](https://davestewart.co.uk/blog/msal-vue)
- [davestewart/msal-vue-demo: A minimal but production-friendly Vue 3 / MSAL demo](https://github.com/davestewart/msal-vue-demo)

Regards my previous comments, I understand that Microsoft are trying to solve, document and support a lot of frameworks and use cases in this repository, but it's ironic that [the really simple code snippet in this video](https://youtu.be/zufQ0QRUHUk) is a world away from the final implementation that consumers have to engineer.

Anyway, regards making redirect interaction work successfully, I may find the time to fork my own demo and see if I can swap the popup logic for redirect logic in the [Auth service](https://github.com/davestewart/msal-vue-demo/blob/main/src/services/auth.ts) and also look at the [route handling](https://github.com/davestewart/msal-vue-demo/blob/main/src/router/index.ts) again, now it is in a simple app.

And perhaps I'll be able to come back with a better perspective on handling the hash clearing + additional route navigation.

If you look at the code and spot anything I've missed, it would be great to get your input!

Anyway, that's it for now.

Thanks for your help,
Dave

**Comment by tnorling** [comment]
Great, glad you got it figured out. I'm going to go ahead and close this but feel free to let us know if there's anything else you need. Thanks!

**Comment by Mobiletainment** [comment]
I am also very thankful for this thread since we had the same issue after upgrading to React Router 6. We're not relying on `@azure/msal-react` and ran into the issue during the `loginRedirect` flow as well. I would not have discovered `navigateToLoginRequestUrl` without @derisen's comment, thank you.

I disabled MSAL's navigation and I'm doing the navigation manually in a React component now by using `navigate`. I did not use the `CustomNavigationClient` though, because our call to `handleRedirectPromise()` had a timing issue with the React component setting the navigation client. The `CustomNavigationClient` was set too late in our case. In my current solution, this React component does the navigation itself, but I had to expose the `ORIGIN_URI` from MSAL to do so, which is not safe since it's an internal of `msal-browser`. So it's definitely not the best solution. Nevertheless, this component can now redirect to the requested target page if one was requested, or just activate the default page after the login.

Here are the bits and pieces for getting it to work in our custom setup:
```typescript
export class AuthClient extends PublicClientApplication {
  constructor(configuration: AuthConfiguration) {
    super({
      auth: {
        /**
         * MSAL normally redirects us to the requested page upon login. This happens in the `handleRedirectPromise` during rehydration.
         * This will cause a full pge reload though. The SPA conform approach is to disable this and rather have the React Router do the navigation internally
         * See https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5694
         */
        navigateToLoginRequestUrl: false,
  // rest left out for brevity

  public redirectUri: string;

  /**
   * This exposes the URI of the page the user wanted to navigate to.
   * Note: it uses internals from MSAL. Updates to the library can break this functionality, so use it with caution!
   */
  public getTargetOriginUriAfterLogin() {
    return this.browserStorage.getTemporaryCache(TemporaryCacheKeys.ORIGIN_URI, true);
  }
}
```

```tsx
const routes = createRoutesFromElements(
  <>
    {/* render the virtual signedin route required for completing the authentication */}
    <Route
      path={authClient.redirectUri}
      element={<RedirectUriNavigationHelper authClient={authClient} defaultPathAfterLogin={defaultPageAfterLogin} basename={basename} />}
    />
    {/* all other routes should be specified after the navigation helper */}
    {/* other routes */}
  </>,
  parentPath
);
```

```tsx
import { createBrowserRouter, createRoutesFromElements, Navigate, Route, useLocation, useNavigate } from 'react-router-dom';
// rest left out for brevity

interface Props {
  /**
   * This is the default path that we want to redirect the user to upon successful login
   * Note: if the user wanted to open a specific page before the login kicked in, this specific page will be used instead
   */
  defaultPathAfterLogin: string;

  /**
   * the application's instance of the Authentication Client
   */
  authClient: AuthClient;
}

/**
 * This component for the virtual route at `redirectUri` ensures that when the login has finished, we navigate to a proper start URL.
 * Note: since the finishing of the authentication depends on the hash in the URL, we need to preserve it to give the rehydration time to process it
 */
const RedirectUriNavigationHelper: React.FunctionComponent<Props> = React.memo(function RedirectUriNavigationHelper({ defaultPathAfterLogin, authClient }) {
  const location = useLocation();
  const navigate = useNavigate();

  useEffect(() => {
    // MSAL's `navigateToLoginRequestUrl` would cause a full page reload when redirecting us to the requested page upon login.
    // To prevent this, we navigate internally within our SPA by having the React Router take care of the navigation instead
    const targetUri = authClient.getTargetOriginUriAfterLogin();
    if (isDefined(targetUri)) {
      const navigateTo = targetUri.replace(window.location.origin, '');
      if (navigateTo === '/') {
        navigate(defaultPathAfterLogin, { replace: true }); // use the default page by default
      } else {
        navigate(navigateTo, { replace: true }); // navigate to the path that the user wanted to navigate to
      }
    }
  }, [authClient, defaultPathAfterLogin, navigate]);

  if (!location.hash) {
    // this page is used only during the login process. If the hash is not there anymore, it means that MSAL has processed the state in the URL already and it's safe to redirect internally, which will happen in the next tick
    return <PageLoadingScreen container="window" />;
  }

  // This is only a virtual route which is part of the login contract. There's nothing to show here, we're just redirecting to the default page after the login.
  // We have to keep the hash in the URL in place though, so that MSAL can pick it up during `` and complete the authentication if it hasn't already.
  // If a specific target URL was requested during login, MSAL will redirect us to that page (by doing another replace) once the authentication is completed
  return <Navigate to={{ pathname: defaultPathAfterLogin, hash: location.hash, search: location.search }} replace={true} />;
});
```

Maybe it's helpful to someone.

**Comment by eminmuratoglu** [comment]
A probable cause, which was the fact in my case, when you have a logic like this:

_If user goes to `/` (home) route and not authenticated, redirect them back to auth page like `/login`_
That causes a loop because Microsoft is going to their own route like `/whatever_microsoft_auth_route` for redirect authentication and your app will redirect user to back to `/login` because user is trying to go to a different route without yet being authenticated, and this loop will keep happening.

Hope this sparks something.

**Comment by cassioutfpr** [comment]
> A probable cause, which was the fact in my case, when you have a logic like this:
> 
> _If user goes to `/` (home) route and not authenticated, redirect them back to auth page like `/login`_ That causes a loop because Microsoft is going to their own route like `/whatever_microsoft_auth_route` for redirect authentication and your app will redirect user to back to `/login` because user is trying to go to a different route without yet being authenticated, and this loop will keep happening.
> 
> Hope this sparks something.

Thank you so much! That was exactly the issue in my Vue 2 app. My router was set to redirect unauthenticated users to  `/login` , but Azure was configured to redirect them to  `/` (home), which caused the loop. I updated the Azure configuration to use redirectUri: window.location.origin + '/login' and added this route in Azure. Now everything works perfectly!
