### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by ksp2018** [AzureAD/microsoft-authentication-library-for-js#570]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe: 
</code></pre>

## Library version 0.2.4

<pre><code>
Library version: 0.2.4

## Current behavior
Getting the error "window is not defined" when running in a nodejs backend api when creating new instance of Msal.UserAgentApplication. Is this not designed to be used for backend as well as frontend code? In our implementation we would be pulling the username/password from a config or secret and using the same credentials to call another API owned by a different team. Is this supported by MSAL? If not, are there plans to add such support in the future?

## Expected behavior
A new Msal.UserAgentApplication object should be  created

## Minimal reproduction of the problem with instructions

 var userAgentApplication = new Msal.UserAgentApplication(applicationConfig.clientID, null, tokenReceivedCallback, { cacheLocation: 'localStorage'});

function tokenReceivedCallback(errorDesc, token, error, tokenType) {
    if (token) {
    }
    else {
        log(error + ":" + errorDesc);
    }
}

</code></pre>

**Comment by DarylThayil** [comment]
@ksp2018 Unfortunately msal js does not support node.

Adal ( for our v1 apis ) does have a node lib adal-node 
https://github.com/AzureAD/azure-activedirectory-library-for-nodejs

We will be looking at adding support for msal.js on node but have not figure out how we want to do that just yet. 

Please keep an eye on our wiki (which will be getting an overhaul soon).  We will make sure to communicate roadmap for this support.

**Comment by ksp2018** [comment]
Thank you for the update
