### ISSUE TITLE
Update package `azure/msal-node@1.15.0` field `engines` to include Node.js > v18

### ISSUE THREAD

**Issue by jaydenseric** [AzureAD/microsoft-authentication-library-for-js#5700]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.15.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Confidential

### Description

The package `azure/msal-node@1.15.0` field `engines` doesn't include Node.js versions greater than v18 (i.e. v19, which we are using):

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/2e4df196d41db10216889d0b360b9abc6c0cee7b/lib/msal-node/package.json#L65-L67

This causes an annoying `npm install` warning (it's not a direct dependency, it's pulled in via `@azure/storage-blob@12.12.0`):

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/msal-node@1.15.0',
npm WARN EBADENGINE   required: { node: '10 || 12 || 14 || 16 || 18' },
npm WARN EBADENGINE   current: { node: 'v19.6.1', npm: '9.4.0' }
npm WARN EBADENGINE }
```

It's the only Azure related package that doesn't support Node.js v19 in `engines`. Other packages even in this repo have `engines` like this:

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/2e4df196d41db10216889d0b360b9abc6c0cee7b/lib/msal-core/package.json#L26-L28

### Error Message

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/msal-node@1.15.0',
npm WARN EBADENGINE   required: { node: '10 || 12 || 14 || 16 || 18' },
npm WARN EBADENGINE   current: { node: 'v19.6.1', npm: '9.4.0' }
npm WARN EBADENGINE }
```

### MSAL Configuration

```javascript
N/A
```

### Relevant Code Snippets

```javascript
N/A
```

### Reproduction Steps

1. Install Node.js v19
2. In a package directory, run `npm install @azure/msal-node@1.15.0`.

### Expected Behavior

No `npm install` unsupported engine warnings output.

### Identity Provider

Other

### Browsers Affected (Select all that apply)

None (Server)

### Source

External (Customer)

**Comment by jaydenseric** [comment]
As a side note; the GitHub issue bug report template for this repo is not a good fit for issues like this. The package in question (`@azure/msal-node@1.15.0`) is used somewhere nested in a dependency graph (of `@azure/storage-blob@12.12.0`) and I have no idea how to answer irrelevant questions like "Identity Provider" but they are required and don't have a "Not applicable" option.

**Comment by emrysal** [comment]
👍 Glad this is in progress @jo-arroyo

**Comment by tnorling** [comment]
Please see our [version support stance](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-node#node-version-support). We will support Node 20 when it becomes available in April.

**Comment by emrysal** [comment]
I understand your stance; if it were not that you are a library - so any app that runs you as a library will never be able to run using Node 19. Having to tell all of our users to --ignore-engines that wishes to run on n19 is very undesirable.

**Comment by jaydenseric** [comment]
It's not a good policy to not support the current version of Node.js for an entire year, thereby forcing Azure customers to not be able to use the current version of Node.js in their apps or published libraries, ***on purpose***, every other year, indefinitely.

Microsoft doesn't appear to understand how the npm ecosystem is intended to work; lets take a look…

```
npm ls azurite
```

```
└─┬ azurite@3.22.0
  └─┬ tedious@15.1.3
    └─┬ @azure/identity@2.1.0
      └── @azure/msal-node@1.15.0
```

`@azure/msal-node` explicitly by policy doesn't support Node.js v19, but `@azure/identity` which depends on it incorrectly says it does support Node.js v19 with its `package.json` field `engines.node` set to `>=12.0.0`:

https://unpkg.com/@azure/identity@2.1.0/package.json

A package can't support newer Node.js versions that it's dependencies do.

This mistake ripples all the way up this particular chain of Microsoft dependencies.

`tedious` incorrectly declares Node.js support of `>=14`:

https://unpkg.com/tedious@15.1.3/package.json

And in turn `azurite` incorrectly declares Node.js support of `>=10.0.0`:

https://unpkg.com/browse/azurite@3.22.0/package.json

Already I have had to explain to less technical team members installing our project locally that the installations didn't fail because of all the engines errors appearing in their console. `azure/msal-node` is the only package in our dependency graph causing errors like that, unique even amongst all the other Microsoft packages.

**Comment by tnorling** [comment]
> It's not a good policy to not support the current version of Node.js for an entire year, thereby forcing Azure customers to not be able to use the current version of Node.js in their apps or published libraries, on purpose, every other year, indefinitely.

Just to clarify, odd numbered Node releases have a 6 month lifespan, not an entire year. They are essentially beta releases of the next even numbered release.

In addition, Node themselves [do not recommend using odd numbered releases in production](https://nodejs.dev/en/about/releases/). We have chosen to heed that advice as the support, testing and maintenance cost associated with supporting a short lived version is frankly not worth it. We also cannot declare support for future, unreleased versions of node as we do not know what changes they may or may not make, thus why we do not use a minimum version as many other packages choose to do. I understand the desire to be on the latest and greatest, and you can by using `ignore-engines`, we just can't commit to providing support if there are issues with these versions.

**Comment by emrysal** [comment]
Looking at it from the other perspective, you actually very much want to open up odd numbered releases as a library - from a package point of view you can always say to your consumers: "Hey, you're running a beta version, that's at your risk". 

These 6 months releases are intended for libraries such as these to have people run them (indeed, in production at your own risk) and finding issues and bugs in this package before `n<LTS>` is released - it provides a package maintainer a 6 months heads up that something is coming that is going to break in the next release. That's the intention of the Node team providing these short lived beta versions.

Odd releases are the canary you are opting out of, likely to increase teething issues / or at least increasing the development effort during implementation of the Current LTS.
