### ISSUE TITLE
Access Token is not parsable with MSAL.js with a simple fetch API

### ISSUE THREAD

**Issue by HamedFathi** [AzureAD/microsoft-authentication-library-for-js#5704]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.33.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

Hello, 

We need to get tokens from the `Microsoft Azure endpoint` directly and pass them to `MSAL.js` to cache them.

Let me share our source code first:

```ts
import {
    AuthenticationScheme,
    Configuration,
    ExternalTokenResponse,
    LoadTokenOptions,
    PublicClientApplication,
    SilentRequest,
} from "@azure/msal-browser";
import { ServerAuthorizationTokenResponse } from "@azure/msal-common";

export async function getAzureToken(): Promise<string | undefined> {

    var headers = new Headers();
    headers.append("Accept", "application/json");
    headers.append("Content-Type", "application/x-www-form-urlencoded");
    headers.append("cache-control", "no-cache");

    var urlencoded = new URLSearchParams();
    urlencoded.append("grant_type", "password");
    urlencoded.append("client_id", "CLIENT_ID");
    urlencoded.append("username", "USERNAME");
    urlencoded.append("password", "PASSWORD");
    urlencoded.append("client_secret", "CLIENT_SECRET");
    urlencoded.append("scope", "email profile openid offline_access MORE_SCOPES_HERE");

    var requestOptions = {
        method: 'POST',
        headers: headers,
        body: urlencoded,
    };

    let response = await fetch(`https://login.microsoftonline.com/TENANT_ID/oauth2/v2.0/token`, requestOptions);
    const jsonResponse = await response.json();

    const tokenResponse: ServerAuthorizationTokenResponse =
        jsonResponse as ServerAuthorizationTokenResponse;
    const accessToken: string | undefined = tokenResponse.access_token;
    const idToken: string | undefined = tokenResponse.id_token;
    const scopes: string = tokenResponse.scope || "";
    const refreshToken: string | undefined = tokenResponse.refresh_token;
    const expiresIn: number | undefined = Number(tokenResponse.expires_in);
    if (accessToken && idToken && refreshToken) {
        const silentRequest: SilentRequest = {
            scopes: scopes.split(" "),
            authority: `https://login.microsoftonline.com/TENANT_ID/oauth2/v2.0/token`,
            account: {
                homeAccountId: "HOME_ACCOUNT_ID",
                environment: "login.windows.net",
                tenantId: "TENANT_ID",
                username: "USERNAME",
                localAccountId: "LOCAL_ACCOUNT_ID",
            },
        };

        const serverResponse: ExternalTokenResponse = {
            token_type: AuthenticationScheme.BEARER,
            scope: scopes,
            expires_in: expiresIn,
            id_token: idToken,
            access_token: accessToken,
            refresh_token: refreshToken,
        };

        const loadTokenOptions: LoadTokenOptions = {
            extendedExpiresOn: Number(tokenResponse.ext_expires_in),
        };

        const msalConfig: Configuration = {
            auth: {
                clientId: "CLIENT_ID",
                authority: "https://login.microsoftonline.com/" + "TENANT_ID",
            },
            cache: {
                cacheLocation: "sessionStorage",
                storeAuthStateInCookie: false,
                secureCookies: false,
            },
        };
    
        const msalObj = new PublicClientApplication(msalConfig);
        const tokenCache = msalObj.getTokenCache();
        tokenCache.loadExternalTokens( /* <-- Error here but not the root cause */
            silentRequest,
            serverResponse,
            loadTokenOptions
        );
    }
    return refreshToken;
}
```

By running the above code and calling the function we got this error:

```
// tokenCache.loadExternalTokens()

ClientAuthError: token_parsing_error: Token cannot be parsed. Please review stack trace to determine root cause.
Failed with error: AuthError: unexpected_error: Unexpected error in the authentication.: Crypto interface - base64Decode() has not been implemented.
```

As you can read in the error, this is not the root cause so after investigation, we found the error raised because the `response.json()` of the fetch API returns an invalid `access_token`.

```ts

let response = await fetch(`https://login.microsoftonline.com/TENANT_ID/oauth2/v2.0/token`, requestOptions);
var jsonResponse = await response.json(); // <- HERE
```

So let's change the code to a simple one just about fetching:

```ts
(async () => {
  var headers = new Headers();
  headers.append("Accept", "application/json");
  headers.append("Content-Type", "application/x-www-form-urlencoded");
  headers.append("cache-control", "no-cache");
  
  var urlencoded = new URLSearchParams();
  urlencoded.append("grant_type", "password");
  urlencoded.append("client_id", "VALUE");
  urlencoded.append("username", "VALUE");
  urlencoded.append("password", "VALUE");
  urlencoded.append("client_secret", "VALUE");
  urlencoded.append("scope", "email profile openid offline_access ...");
  
  var requestOptions = { method: "POST", headers: headers, body: urlencoded };
  
  let response = await fetch(
    `https://login.microsoftonline.com/TENANT_ID/oauth2/v2.0/token`,
    requestOptions
  );
  let jsonResponse = await response.json(); // <-- ISSUE IS HERE
})();
```

We checked the result of `await response.json()`  and for `access_token` it is invalid. (id_token is valid JWT)

![json](https://user-images.githubusercontent.com/8418700/220318075-3c5175c3-9650-4387-8c60-24143f661cd7.png)

![jwt](https://user-images.githubusercontent.com/8418700/220318583-dcc58270-4c20-481c-b4c6-d0577a228f18.png)

FYI

```
    "@azure/msal-browser": "^2.33.0",
    "@azure/msal-common": "^10.0.0",
    "@azure/identity": "^3.1.3",
    "jsonwebtoken": "^9.0.0"
```

### MSAL Configuration

```javascript
const msalConfig: Configuration = {
            auth: {
                clientId: "CLIENT_ID",
                authority: "https://login.microsoftonline.com/" + "TENANT_ID",
            },
            cache: {
                cacheLocation: "sessionStorage",
                storeAuthStateInCookie: false,
                secureCookies: false,
            },
        };
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@HamedFathi Why have you decided to get tokens directly instead of using MSAL to retrieve and cache your tokens?

**Comment by HamedFathi** [comment]
@jo-arroyo 
Two years ago we used the same way to login **silently** to our site with Cypress (I do not want to login with UI / more reliable & less flaky)
In Cypress, we use `cy.request`, a built-in HTTP client and it works but I have decided to have the core separated from Cypress. So, I tried to write the above code to return just **Promise**.

In our mono-repo with this core (if it works which is not now) I am able to use it for Playwright and ... too.

The most important part for me is login **silently** (no UI) and separating things from the other tools (Cypress, Playwright, and ...) this is why I need to work with the API and then save the result.

Honestly, I cannot understand it, I have the token but invalid! no error if I did something wrong!

**Comment by ghost** [comment]
Hello @jo-arroyo ,
Hello @HamedFathi !

Thank you @jo-arroyo and @HamedFathi for your answers!

Maybe I can explain a bit more about what @HamedFathi's and my main goal is: Our main goal is to login certain users to a web application (application under test, AUT) and save the various tokens into the MSAL cache. Launching the AUT subsequentially, the AUT does not ask for the user credentials but retrieves the tokens from the MSAL cache. We try to follow the recommendations of the [Testing](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/testing.md) guidelines.

Currently, we do this procedure via Cypress.io. A command, called `cy.request()`, fires up the HTTP request to the API and gets the tokens back. There is maybe a possibility to do this step with MSAL, but this is not our main concern right now. 

Our problem is, that MSAL throws an error, when we try to write the tokens to the MSAL cache, utilizing `loadExternalTokens()` (@HamedFathi mentioned in the original post):
```
// tokenCache.loadExternalTokens()

ClientAuthError: token_parsing_error: Token cannot be parsed. Please review stack trace to determine root cause.
Failed with error: AuthError: unexpected_error: Unexpected error in the authentication.: Crypto interface - base64Decode() has not been implemented.
```
The error is thrown by the [DEFAULT_CRYPTO_IMPLEMENTATION](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/b03430c5841e5caad33d0b928b160af9f1535708/lib/msal-common/src/crypto/ICrypto.ts#L78) interface.

From what I understand, the constructor of the `PublicClientApplication` class should create a `CryptoOps` [object](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/b03430c5841e5caad33d0b928b160af9f1535708/lib/msal-browser/src/app/ClientApplication.ts#L141), if the environment is a browser environment (window == defined). Otherwise, the a DEFAULT_CRYPTO_IMPLEMENTATION object is created (which throws the error). However, it seems, we are not running in a browser environment. Our scripts are started via `node.exe` and utilize playwright tests: `C:\nodejs\node.exe .\..\..\node_modules\playwright-core\lib\cli\cli test ...`

So after researching the last few days: is it possible, to log in as a user (with ROPC) using only API calls (directly or via MSAL API)?

**Comment by tnorling** [comment]
msal-browser APIs must be called from a brower environment. If you're not able to invoke these APIs from your application context you'll need to hydrate the cache manually from the test context. We have a sample demonstrating how to use msal-node to do this in a playwright test [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-browser-samples/TestingSample/test/browser-test.spec.ts)
