### ISSUE TITLE
acquireTokenSilent rejected with error. Invoking interaction to resolve. BrowserAuthError: interaction_in_progress

### ISSUE THREAD

**Issue by mikebper** [AzureAD/microsoft-authentication-library-for-js#5705]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.4.6

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

Logging in seems to be working fine. The tokens are enriched with a claim by using a custom policy and calling a REST API. In the example the claim is named departments. Everything works fine until a new idToken is retrieved using the refresh token (after being logged in for about an hour). The refresh seems to ultimately succeed, and new tokens are procured and everything works, but in the console the below errors are being reported. This suggests to me that something is not quite right about the implementation. I can see that the tokens are refreshing at the same time as the "getData" method in the example is being called, but I'm not sure how to synchronize those actions. Can you provide guidance, please?

Errors:
@azure/msal-angular@2.4.6 : Error - Interceptor - acquireTokenSilent rejected with error. Invoking interaction to resolve.

BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.  For more visit: aka.ms/msaljs/browser-errors.

### MSAL Configuration

```javascript
import { LogLevel, Configuration, BrowserCacheLocation } from '@azure/msal-browser';
import { environment } from 'src/environments/environment';

const isIE = window.navigator.userAgent.indexOf('MSIE ') > -1 || window.navigator.userAgent.indexOf('Trident/') > -1;

export const b2cPolicies = {
    names: {
        signUpSignIn: 'B2C_1A_SIGNUP_SIGNIN',
        resetPassword: 'B2C_1A_PASSWORDRESET',
        editProfile: 'B2C_1A_PROFILEEDIT'
    },
    authorities: {
        signUpSignIn: {
            authority: '<redacted>/B2C_1A_SIGNUP_SIGNIN',
        },
        resetPassword: {
            authority: '<redacted>/<myb2onmicrosofcomtdomain>/B2C_1A_PASSWORDRESET',
        },
        editProfile: {
            authority: '<redacted>/<myb2onmicrosofcomtdomain>/B2C_1A_PROFILEEDIT'
        }
    },
    authorityDomain: '<redacted>'
};

export const msalConfig: Configuration = {
    auth: {
        clientId: '<redacted>',
        authority: b2cPolicies.authorities.signUpSignIn.authority,
        knownAuthorities: [b2cPolicies.authorityDomain],
        redirectUri: '/',
        postLogoutRedirectUri: '/'
    },
    cache: {
        cacheLocation: BrowserCacheLocation.LocalStorage,
        storeAuthStateInCookie: isIE,
    },
    system: {
        loggerOptions: {
            loggerCallback: (level, message, containsPii) => {
                console.log(message);
            },
            logLevel: LogLevel.Error,
            piiLoggingEnabled: false
        }
    }
}

export const protectedResources = {
    loginRequest: {
        scopes: ['openid', 'https://<redacted>/Read']
    },
    list: {
        endpoint: `${environment.apiBaseUrl}/List`,
        scopes: ['openid', 'https://<redacted>/Read']
    }
}
```

### Relevant Code Snippets

```javascript
app.module.ts snippet:

imports: [
    ...,
    MsalModule.forRoot(new PublicClientApplication(msalConfig),
      {
        interactionType: InteractionType.Redirect,
        authRequest: {
          scopes: protectedResources.loginRequest.scopes
        }
      },
      {
        interactionType: InteractionType.Redirect,
        protectedResourceMap: new Map([
          [protectedResources.list.endpoint, protectedResources.list.scopes]
        ])
      }),
    providers: [    
    {
      provide: HTTP_INTERCEPTORS,
      useClass: HttpAppInterceptor,
      multi: true
    },
    {
      provide: HTTP_INTERCEPTORS,
      useClass: MsalInterceptor,
      multi: true
    },
    MsalGuard
  ],
  bootstrap: [
    AppComponent,
    MsalRedirectComponent
  ]
  ]

Angular service snippet which uses claims from idToken:

  public async getClaims(): Promise<void> {
    let userClaims = this.msalService.instance.getAllAccounts()[0].idTokenClaims!;
    let departments = userClaims['departments'];

    ...do something based on departments
  }
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@mikebper The `acquireTokenSilent rejected with error. Invoking interaction to resolve` from the MSAL Interceptor is expected behavior. AcquireTokenSilent is designed fail when the access token is expired, prompting new tokens to be retrieved interactively with the refresh token. 

To address the `interaction in progress` error, please check that no other interactions are in progress before using `getAllAccounts`, using subscribing to the `inProgress` observable. You can see this in our [samples](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/2e4df196d41db10216889d0b360b9abc6c0cee7b/samples/msal-angular-v2-samples/angular12-sample-app/src/app/home/home.component.ts#L27) and in our [error doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/errors.md#interaction_in_progress).

If you are continuing to see errors, please enable and provide verbose logs.

**Comment by mikebper** [comment]
How can I access the claims associated with the ID token on demand, for example when a UI button is clicked? Like if I want a "Show Claims" button that displays the claims associated with the ID token whenever it's clicked?  At login you can subscribe and check this.msalService.instance.getAllAccounts().length > 0 to determine if the user is authenticated, and then get the claims and use them, and that seems to work. But once the token refreshes, the "Show Claims" button seems to break, because I think the token refresh isn't done in time. If you call getAllAccounts()[0].idToken directly then it works, but behind the scenes the "interaction in progress" error occurs.

**Comment by jo-arroyo** [comment]
@mikebper Please also subscribe to the `inProgress` observable, as in the samples and error doc above, before you call `getAllAccounts[0].idToken` to get the claims.

**Comment by mikebper** [comment]
If I have multiple components that need data from the account, is it advisable to subscribe in all of them? Or should it only be subscribed to once and then the data shared to other components that need it from there?

    this.msalBroadcaseServiceSubscription = this.msalBroadcastService.inProgress$
    .pipe(
      filter((status: InteractionStatus) => status === InteractionStatus.None)
    )
    .subscribe(() => {
      if (this.msalService.instance.getAllAccounts().length > 0) {
        this.isAuthenticated = true;
        this.userClaims = this.msalService.instance.getAllAccounts()[0].idTokenClaims!;
      }
    });

**Comment by jo-arroyo** [comment]
@mikebper Subscribing to the `inProgress` variable is necessary every time before getting accounts or invoking any interaction. How you choose to use the data is up to you, but the data is cached by MSAL for easy access and updated any time there is interaction.
