### ISSUE TITLE
logoutRedirect ignores extraQueryParameters

### ISSUE THREAD

**Issue by Rutakamekiar** [AzureAD/microsoft-authentication-library-for-js#5707]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.32.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.5.1

### Public or Confidential Client?

Public

### Description

I want to implement tenant invite flow, during invite I want to redirect user to signin or signup flow, for this I use query parameter option=signup, however when I call logoutRedirect it ignores extraQueryParameters field

### MSAL Configuration

```javascript
{
  auth: {
    clientId: 'afe97106-8c7f-4b47-855d-1f78b3458715',
    authority: b2cPolicies.authorities.signUpSignIn.authority,
    knownAuthorities: [b2cPolicies.authorityDomain],
    redirectUri: '/',
    postLogoutRedirectUri: '/',
  },
  cache: {
    cacheLocation: 'localStorage',
  }
}
```

### Relevant Code Snippets

```javascript
instance.logoutRedirect({
      extraQueryParameters: { option: 'signup' },
    })
```

### Reproduction Steps

1. login to the app
2. press the button that should redirect you to login with right query parameters

### Expected Behavior

logoutRedirect should redirect to login with the selected extraQueryParameters

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@Rutakamekiar Are you able to reproduce this behavior in one of our [sample apps](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples)?

**Comment by Rutakamekiar** [comment]
@jo-arroyo I tried to reproduce this in msal-react-samples/nextjs-sample/ and found that after logoutRedirect, I am not redirected to the login at all. On the network, I only see this request oauth2/v2.0/logout?post_logout_redirect_uri=http%3A%2F%2Flocalhost%3A3201%2F&client-request-id=11d39c03-b64d-462b-b9d8-7de59e7100aa and then a redirect to postLogoutRedirectUri. I understand that it looks like a logical flow, but not for me :)

Is it possible to make a logout so that it immediately redirects to a login with specific extraQueryParameters?

**Comment by jo-arroyo** [comment]
@Rutakamekiar If I'm understanding your ask correctly, you are wanting to log out a user and then be directed to a page where the user will be prompted to sign up or sign in?

If so, you could try setting your `postLogoutRedirectUri` in configurations to a dedicated page that calls `loginRedirect` with the `extraQueryParameters` desired, as we do not currently have a way in MSAL to trigger redirect to login.

**Comment by Rutakamekiar** [comment]
@jo-arroyo Thanks for the answer, I came to the point that on a separate layout I track whether someone is authorized, if so, then I perform a logoutPopup, if not, then I redirect to the login with extra query parameters. For the future, it would be interesting to see some boolean parameter in logout request that will indicate a redirect to login immediately after logout.
