### ISSUE TITLE
BrowserAuthError: user_cancelled: User cancelled the flow.

### ISSUE THREAD

**Issue by arslan-ideawake** [AzureAD/microsoft-authentication-library-for-js#5709]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.18.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

Currently, I'm working on an angular v8 project which is using @azure/msal-browser, previously it was working fine locally, in testing and production environments as well, but now when loginPopup of msal function call, it still opens an authentication window in a new tab, but automatically trigger user cancel event, even if user does not close auth tab, but on localhost still working fine.
<img width="1671" alt="Screenshot 2023-02-22 at 5 40 08 PM" src="https://user-images.githubusercontent.com/85274866/220624626-d2d84819-57ad-4361-856a-f60972bfe086.png">

### MSAL Configuration

```javascript
{
    auth: {
      clientId: environment.azure.clientId,
      authority: 'https://login.microsoftonline.com/common',
      redirectUri: environment.azure.redirectURI
    },
    cache: {
      cacheLocation: 'sessionStorage',
      storeAuthStateInCookie: false
    }
}
```

### Relevant Code Snippets

```javascript
MSAL_CONFIG: Configuration = {
    auth: {
      clientId: environment.azure.clientId,
      authority: 'https://login.microsoftonline.com/common',
      redirectUri: environment.azure.redirectURI
    },
    cache: {
      cacheLocation: 'sessionStorage',
      storeAuthStateInCookie: false
    }
  };

  private myMSALObj: PublicClientApplication = new PublicClientApplication(
    this.MSAL_CONFIG
  );
  private loginRequest?: PopupRequest;
  
  azureLogin() {
    this.loginRequest = {
      scopes: [
        'user.read',
        'profile',
        'email',
        'openid',
      ],
    };
    return this.myMSALObj.loginPopup(this.loginRequest);
  }
```

### Identity Provider

None

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@arslan-ideawake Can you provide verbose logs of this behavior? See [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logging.md) for how to enable verbose logs.

**Comment by arslan-ideawake** [comment]
@jo-arroyo Thanks for your response, this is how verbose logs look like when I turned them on.
(point to note here is that I did not cancel the flow).

<img width="1680" alt="Screenshot 2023-02-23 at 12 31 21 PM" src="https://user-images.githubusercontent.com/85274866/220844287-18c10826-19a2-4789-af9a-c20cb5787e06.png">

**Comment by jo-arroyo** [comment]
@arslan-ideawake Can you try upgrading to the latest version of msal-browser and see if you still see the error? We have made changes to popups since v2.18.0.

**Comment by w304105033** [comment]
I recently came across the same issue in my application. In my case it is related to the response header of my application. When removed header "Cross-Origin-Opener-Policy" from response header, It works again. I hope that these help to you!

**Comment by arslan-ideawake** [comment]
@jo-arroyo yes, I did check twice on the latest version of azure/msal-browser but same behavior, basically @w304105033 is right (Thanks @w304105033 for your response), totally forgot that have set some security headers in the system, I have checked after removing "Cross-Origin-Opener-Policy" header then it again starts working, but can you please suggest any solution for this because in case if do not want to remove security header "Cross-Origin-Opener-Policy" too, any chance to use it with header.

**Comment by w304105033** [comment]
@arslan-ideawake I didn't found any good solutions. Using "loginRedirect" instead of "loginPopup" may bypass the problem but it also hurts user experience.

@jo-arroyo Do you have any suggestions ?

**Comment by arslan-ideawake** [comment]
@w304105033 by setting " Cross-Origin-Opener-Policy: 'same-origin-allow-popups' " will do the job.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Opener-Policy

**Comment by tnorling** [comment]
Sounds like you've solved this, did you need anything else from us?

**Comment by w304105033** [comment]
@arslan-ideawake I have tried setting it to "same-origin-allow-popups" before. At the beginning it is "same-origin" and it always 
reports error when open login popup dialog. Then I set it to "same-origin-allow-popups". it stop reporting error while open login dialog but still reports the same error after authorization completed. Would you mind sending me all your response header configurations? And then I can compare it with mine.

**Comment by arslan-ideawake** [comment]
@w304105033 yes you said right, forgot to update here, for now, I just removed the header "Cross-Origin-Opener-Policy" from the response header and achieved my goal, but will keep an eye on it, and if I found any appropriate solution, will share with you.

**Comment by tnorling** [comment]
Closing as no action from MSAL.js is needed. Let us know if there's anything else we can help you with. Thanks!
