### ISSUE TITLE
CORS issue with MsalService.aquireTokenSilent()

### ISSUE THREAD

**Issue by hmsuchier** [AzureAD/microsoft-authentication-library-for-js#5712]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.33.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.5.3

### Public or Confidential Client?

Public

### Description

Hello, 
 I'm trying to acquire access token in the context of a PWA application, thus using service worker and fetch method. I call the `loginRedirect()` method from `MsalService`, and it goes fine (except for a noMatchError because somewhere the app is asked to go to a /#code route that does not exists, that is another problem), then I call `aquireTokenSilent()` from same service. Here is the error I get then:
 
`Access to fetch at 'https://login.microsoftonline.com/XXXXXXXXXXXXXXX/oauth2/v2.0/token' from origin 'https://risq-deve.bouyer-leroux.fr' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`
I know this might be an error linked to the use of service worker but this worker is used as well for the first method call, and I set a "ngsw-bypass" extra parameter option for both. I don't see what is the difference here, so I'm asking for someone help, thanks to anyone that could give me a hint!

### MSAL Configuration

```javascript
{
    auth: {
      clientId: XXXX,
      authority: `https://login.microsoftonline.com/XXXX`,
      redirectUri: environment.msredirectUri
    },
    cache: {
      cacheLocation: 'localStorage',
      storeAuthStateInCookie: isIE,
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Info,
        piiLoggingEnabled: false
      }
    }
  }
```

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
You need to register your redirectUri on your app registration as type "SPA"

**Comment by hmsuchier** [comment]
Thanks for your answer. As I have no access to the configuration page to check if this is correctly setup, could you please describe where to find this? The person I'm interacting with on this subject tells me that there is no such setting. An y help appreciated, thanks!

**Comment by tnorling** [comment]
[Docs](https://learn.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-app-registration#redirect-uri-msaljs-20-with-auth-code-flow)

**Comment by hmsuchier** [comment]
Good point, thanks.

**Comment by hmsuchier** [comment]
Hi, now I've got the setup working as long as there are no service worker involved. What is the way to bypass service worker for mal related queries?

**Comment by hmsuchier** [comment]
Here is what I've tried to do today with MSALInterceptorFactory:
```
export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
  const protectedResourceMap = new Map<string, Array<string>>();
  protectedResourceMap.set('https://graph.microsoft.com/v1.0/me', ['user.read']);
  return {
    interactionType: InteractionType.Redirect,
    protectedResourceMap,
    authRequest: (msalService: MsalService, req, originalAuthRequest: MsalInterceptorAuthRequest) => {
   
      originalAuthRequest.extraQueryParameters = {"ngsw-bypass": ""};
      originalAuthRequest.tokenQueryParameters = {"ngsw-bypass": ""};
      return originalAuthRequest
    }
  };
}
```
I still get a CORS error when requesting `https://login.microsoftonline.com/here-my-tenant-id/oauth2/v2.0/token`. I can see that fetch method is invoked when service worker is running, thus generating the error because query origin is missing. I'd really like some help here, please.

**Comment by lalimasharda** [comment]
Hey @hmsuchier ! Are you sure you have registered the app correctly as a Single Page Application on Azure Portal? 

Also, it seems that a PWA application (hoping that you are talking about a Progressive Web App) uses service workers to deliver content, but we do not support service workers in MSAL Angular yet.

**Comment by hmsuchier** [comment]
Hey @lalimasharda, thanks for your answer. Yes, everything is setup properly on config page. Just to be clear, everything worked just fine with the popup login mechanism, and the app setup as pwa (yes, progressive web app). In this context, I add "ngsw-bypass" parameter to tell Angular not to use service workers for specific queries. What could be the reason why this is not working anymore with the redirect mechanism? 
You say you do not support service worker, at least, could it be possible to make sure that the "ngsw-bypass" trick is taken into account in all (possible) scenarios?
Thanks!

**Comment by lalimasharda** [comment]
Hey @hmsuchier , if pop-up is working with the "ngsw-bypass" parameter, then that would mean that it is getting appended to the query properly. Can you please check the network trace for the query for redirect and see if that parameter is getting appended correctly as well?
