### ISSUE TITLE
CORS issue when using protocolMode OIDC on Google identity provider

### ISSUE THREAD

**Issue by yann-combarnous** [AzureAD/microsoft-authentication-library-for-js#5713]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.33.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

n/a

### Public or Confidential Client?

Public

### Description

When trying to login, I am getting a CORS error due to Google IDP CORS setup and MSAL headers added to request.

### Error Message

```Access to fetch at 'https://accounts.google.com/.well-known/openid-configuration' from origin 'http://localhost:3000' has been blocked by CORS policy: Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.```

### MSAL Configuration

```javascript
Configuration:

- clientId:  'xxx.apps.googleusercontent.com',
- authority: 'https://accounts.google.com',
- protocolMode: 'OIDC',
```

### Relevant Code Snippets

```javascript
msal.loginRedirect({
      loginHint: email,
      scopes,
    });
```

### Reproduction Steps

Try to connect to Google IDP

### Expected Behavior

MSAL can connect to Google openid-configuration endpoint

### Identity Provider

Other

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari

### Source

External (Customer)

**Comment by tnorling** [comment]
What value is being set for `content-type`? I don't see that we're setting this header for openid-configuration endpoint calls. You can also [provide this metadata statically](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/docs/performance.md#bypass-authority-metadata-resolution) through the `authorityMetadata` config option to work around this.

**Comment by vikash933494** [comment]
Can MSAL library me user to authenticate using non Microsoft login providers like any organization specific?
Any samples for that.I get error like :scopes like openid etc cannot be requested for in Oauth 2.0

**Comment by tnorling** [comment]
Generally speaking no, MSAL is a Microsoft Authentication Library and thus is built for and supports Microsoft identity providers. That said, unofficially, if your identity provider is OIDC compliant our library may work. We make no promises that we will be compatible and we may not prioritize fixes for external IDPs but if there are small things that are blocking you from using our library please let us know or open a PR and we will certainly consider them.

**Comment by vikash933494** [comment]
Then how is it that MSAL can be integrated to Facebook, Google login as they are not Microsoft identity providers?

**Comment by vikash933494** [comment]
Before closing, could you please respond then how is MSAL integrated to Facebook,Google login as they are not Microsoft identity providers

**Comment by yann-combarnous** [comment]
> Before closing, could you please respond then how is MSAL integrated to Facebook,Google login as they are not Microsoft identity providers

Use protocolMode: ´oidc, see https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/configuration.md
