### ISSUE TITLE
Get Access Token using Client credentials.

### ISSUE THREAD

**Issue by KotanaSai21** [AzureAD/microsoft-authentication-library-for-js#5714]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

1.4.4

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.4

### Public or Confidential Client?

Public

### Description

We have a React Application implemented where user login and gets authenticated and then using `acquireTokenSilent` , I am able to get the accessToken from Response.

But My requirement is that, instead of authenticating from login or By userNamePassword, I want to authenticate using `clientcredentials` and get the accessToken. We have something like `acquireTokenByClientCredential` in msal-node which uses ConfidentialClientApplication. And I know MSAL React doesn't support Confidential client application.

Is there any workaround to get authenticate using `clientCredentials` and get the accesstoken in a React Application ?

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by tnorling** [comment]
No. msal-browser, and by extension, msal-react only support Public Clients. If you want to use client credentials you will need to use a backend which is capable of keeping those secret.

**Comment by KotanaSai21** [comment]
Service principal is the Azure AD recommended authorization method. Can you tell me is it possible in MSAL React to get authenticate using either an application secret or a certificate ? Any workarounds in a react web app?

**Comment by KotanaSai21** [comment]
Got a work around. Created a Http Trigger function in azure, and get the token from there in my React app. Thank You.
