### ISSUE TITLE
Issue with login popup on Mac OS

### ISSUE THREAD

**Issue by bcarolan** [AzureAD/microsoft-authentication-library-for-js#5715]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.32.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

-

### Public or Confidential Client?

Public

### Description

When I load https://login.microsoftonline.com/common with my client id, outlook accounts sometimes do not appear as options to sign in. 
If I am in a browser session with just one outlook email, the email will flash on the screen before disappearing. This only happens on my MacIOS machine. The issue is not present on a Windows machine. 

If I am in a browser session with more than one Microsoft account, both appear on the login screen. 

### Error Message

No console errors or Network errors.

### Msal Logs

N/A

### MSAL Configuration

```javascript
auth: {
    clientId: CLIENT_ID,
    authority: 'https://login.microsoftonline.com/common',
    redirectUri: 'BLANK-HTML'
  },
 cache: {
    cacheLocation: 'sessionStorage', 
    storeAuthStateInCookie: false, 
  },
```

### Relevant Code Snippets

```javascript
Login popup: 
const microsoftApp = new (window as any).msal.PublicClientApplication(
    msalConfig
  );

microsoftApp
      .loginPopup({
        prompt: 'select_account',
        scopes: ['openid', 'profile', 'email'],
      })
```

### Reproduction Steps

1. Log into one outlook account. 
2. Open a configured link of 'https://login.microsoftonline.com/common' with any valid client id on a Mac machine.
3. You will see the logged in account flash at the bottom of the screen, then disappear. 

### Expected Behavior

The logged in Microsoft account should remain on the screen, and not disappear. 

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Safari

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@bcarolan The outlook accounts selection screen is not controlled by MSAL, please open a ticket Azure support to address this issue.
