### ISSUE TITLE
Upgrade @azure/msal-angular to Ivy Renderer

### ISSUE THREAD

**Issue by alexander-kastil** [AzureAD/microsoft-authentication-library-for-js#5731]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Public or Confidential Client?

Public

### Description

In the current implementation @azure/msal-angular does not use Ivy Renderer but in contrast uses the previous renderer. Support for the legacy View Engine will be removed in Angular 16. This would result in @azure/msal-angular being the showstopper concerning Angular 16 migration. 

Please find details in this post:

https://twitter.com/tomastrajan/status/1630494785151565824?cxt=HHwWgICw0cmX16AtAAAA

Current build message: 

Generating browser application bundles (phase: setup)... Processing legacy "View Engine" libraries:
- @azure/msal-angular [es2015/esm2015] (https://github.com/AzureAD/microsoft-authentication-library-for-js.git)
Encourage the library authors to publish an Ivy distribution.

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
This is currently being worked on and is tracked by issues #5410, #4298 and #3277. Closing as duplicate.
