### ISSUE TITLE
postLogoutRedirectUri on multiple tabs

### ISSUE THREAD

**Issue by akkinenivijay** [AzureAD/microsoft-authentication-library-for-js#574]
## I'm submitting a...
<pre><code>
[X] Bug report 
</code></pre>

<pre>
I have two vue based spa apps served from appA.xyz.com and appB.xyz.com with two app registrations in Azure AD using implicit flow in the same tenant.  When we issue logout on one of the tabs with appA , the behavior is as expected it redirects to the postLogoutRedirectUri. But on appB when we do logout it just stays at page https://login.microsoftonline.com/{tenantid}/oauth2/v2.0/logoutsession without redirecting to postLogoutRedirectUri

Console logs from appA
Navigated to https://login.microsoftonline.com/{tenantid}/oauth2/v2.0/logout?post_logout_redirect_uri=https%3A%2F%2FappA.xyz.com%2Flogout%2F
Navigated to https://login.microsoftonline.com/{tenantid}/oauth2/v2.0/logoutsession
Navigated to https://appA.xyz.com/logout/ 

Console logs from appB
Navigated to https://login.microsoftonline.com/{tenantid}//oauth2/v2.0/logout?post_logout_redirect_uri=https%3A%2F%2FappB.xyz.com%2Flogout%2F
Navigated to https://login.microsoftonline.com/64b0287b-af0d-4307-ae82-febfb154a6e6/oauth2/v2.0/logoutsession

## Expected behavior
postLogoutRedirectUri should work on the other tab too. 
</pre>

## Browser:
- [X] Chrome version XX
- [X] Firefox version XX
## Library version

<pre><code>
Library version: 0.2.4
</code></pre>

**Comment by navyasric** [comment]
@akkinenivijay Can you make sure that the app registration for your apps have the logoutURI set to the same value as the postLogoutRedirectURI you are configuring in the code? You need this to be set for the logout redirect to work.

**Comment by navyasric** [comment]
Closing this issue due to lack of further information or response.
