### ISSUE TITLE
B2C with multiple policies: AADB2C90088: The provided grant has not been issued for this endpoint

### ISSUE THREAD

**Issue by MichdeJong** [AzureAD/microsoft-authentication-library-for-js#5742]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.4.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.28.1

### Public or Confidential Client?

Public

### Description

We have a client application that uses MSAL to connect to Azure B2C.
In Azure B2C we have a (custom) SignIn/SignUp policy but also some other (custom) policies, for example Edit Profile.

Recently we have changed the validity of our access tokens to 15 minutes and are now getting some errors when MSAL tries to (silently) get a new access token (we suspect this issue was already there before but just never noticed).

The error we are seeing is on the call to the /token endpoint of the \<signin policy\>. This occurs if the user has first logged in, then does an Edit Profile (runs the Edit Profile policy), then the access token expires and the user does something that requires an access token.
Error:
_AADB2C90088: The provided grant has not been issued for this endpoint. Actual Value : \<signin policy\> and Expected Value : \<edit profile policy\>_
Looking at the refresh token that is sent as payload on the call to /token we see that it is the refresh token for the Edit Profile policy.
**Our main question:** Why does MSAL try to call the /token endpoint for the \<signin policy\> while passing the refresh token belonging to the \<edit profile policy\>? But perhaps our whole approach with handling the multiple policies is incorrect and someone can point us to a better approach?

### Background Info

We use
`instance.setActiveAccount(account)`
to set the active account after each msal interaction.
We see that, after the initial SignIn and the subsequent EditProfile, that
`instance.getAllAccounts()`
returns two accounts, on for the SignIn policy and one for the EditProfile policy.
As mentioned, this results in an error when a new access token is needed.

As an alternative we also tried to use
`instance.setActiveAccount(account)`
only after the initial SignIn. That way the active account is always the one for the SignIn policy.
This way, whenever a new access token is needed, msal uses the refresh token for the SignIn policy on the call to /token and the call succeeds. However, this approach has a big drawback for us: the other policies we have, like the EditProfile, change the claims in the token. If we keep using the access token from the initial SignIn policy the backend services receive the 'old' claims, not the new ones. We might be able to overcome this drawback by creating a custom refresh journey but there are some complexities for our particual situation related to this so we are hoping to be able to avoid that.

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by tnorling** [comment]
Sounds like theres 2 issues you're facing here so let's try and separate those:

1. The wrong RT is being passed to the /token endpoint

As you've figured out, account objects belong to a specific policy. You need to make sure the account you are passing to acquireToken is the one associated with the policy you wish to get a token for.

2. You are receiving stale claims after the profile has been edited. 

Sounds like the access token is being served from the cache. If you need a new token you can force a refresh with either the `forceRefresh` parameter or the [cacheLookupPolicy](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/token-lifetimes.md#cache-lookup-policy)

**Comment by MichdeJong** [comment]
Thanks for the feedback. Let me focus on issue 1 (wrong RT is passed).
You mentioned
> You need to make sure the account you are passing to acquireToken is the one associated with the policy you wish to get a token for.

It was our assumption that MSAL would be able to figure out based on the account object which policy to use. Obviously an incorrect assumption 🙂 
How do we indicate to MSAL which policy to use.

We start the EditProfile policy by doing:

```ts
const editProfileFlowRequest = {
     scopes: environment.authenticationServer.scopes,
     authority: environment.authenticationServer.authorities.editProfile.authority,
     redirectUri: `${environment.appUrl}/auth`
};
this.msalService.loginRedirect(editProfileFlowRequest);
```
After the user is redirected back to our app we do:
```ts
const payload = result.payload as AuthenticationResult;
this.msalService.instance.setActiveAccount(payload.account);      
```
As the account now belongs to a different policy than the one we use initially for Login, we want to tell MSAL to use this EditProfile policy whenever it needs to get a new AccessToken based on the RefreshToken.
How do we do that?

**Comment by tnorling** [comment]
When you need to get a token for a particular policy you need to pass both `authority` with the correct policy and `account` associated with that given authority. If these don't match you'll see unexpected behaviors.

**Comment by tnorling** [comment]
I'm also a little confused why you want to silently get a token from the edit Profile policy. That doesn't make a whole lot of sense to me...edit profile is by definition an interactive flow

**Comment by mamoorkhan** [comment]
> I'm also a little confused why you want to silently get a token from the edit Profile policy. That doesn't make a whole lot of sense to me...edit profile is by definition an interactive flow

what about when we have a requirement to let a user change their expired password and sign them in straight away without having to re-enter their new password a third time?

**Comment by mamoorkhan** [comment]
> I'm also a little confused why you want to silently get a token from the edit Profile policy. That doesn't make a whole lot of sense to me...edit profile is by definition an interactive flow

So lets say we have a requirement where the user gets a notification that their password is expired and they need to reset it, they click on the link to the application, the application takes them to the reset password policy, they signin, update their password and we want them to stay signed in without having to re-enter their password that they just entered twice a third time. What should we do?

**Comment by tnorling** [comment]
Re-entering your password after a change is a pretty common scenario, which users should be accustomed to, I think that's pretty reasonable. That's a different discussion though than what's being discussed in this issue and not really related to MSAL.js. I'd suggest that you raise an issue with [B2C support](https://learn.microsoft.com/en-us/azure/active-directory-b2c/find-help-open-support-ticket) for these types of questions.
