### ISSUE TITLE
BrowserAuthError: interaction_in_progress

### ISSUE THREAD

**Issue by gitmurali** [AzureAD/microsoft-authentication-library-for-js#5744]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.32.0

### Public or Confidential Client?

Public

### Description

So, Before raising this bug I tried handleRedirectPromise() but no luck so I have posted this bug here. 

I'm using ssoSilent for session management for my single page apps but when I logout from one app and other app also logged out but when I re-login it throws interaction_in_progress error but in logs it says the inProgress is set to None. 
The weird thing is it is set to None but still it throws interaction_in_progress error which has become a nightmare to me. Please suggest some fixes. Thanks. 

![Screenshot 2023-03-01 at 19 37 32](https://user-images.githubusercontent.com/25775153/222247069-cbd01e01-4e75-4b33-9647-8407ca8add8f.png)

### Error Message

Uncaught (in promise) BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.  For more visit: aka.ms/msaljs/browser-errors.

### Msal Logs

[Wed, 01 Mar 2023 19:36:20 GMT] : @azure/msal-browser@2.32.0 : Info - Emitting event: msal:initializeStart
index.esm.js?dfc2:16954 [Wed, 01 Mar 2023 19:36:20 GMT] : @azure/msal-browser@2.32.0 : Info - Emitting event: msal:initializeEnd
index.esm.js?dfc2:16954 [Wed, 01 Mar 2023 19:36:20 GMT] : @azure/msal-browser@2.32.0 : Info - Emitting event: msal:handleRedirectStart
index.esm.js?dfc2:16954 [Wed, 01 Mar 2023 19:36:20 GMT] : @azure/msal-react@1.5.0 : Info - MsalProvider - msal:handleRedirectStart results in setting inProgress from startup to handleRedirect
index.esm.js?dfc2:16954 [Wed, 01 Mar 2023 19:36:20 GMT] : [b41c2d47-7e60-42ff-b3f6-c2b81b01bc67] : msal.js.browser@2.32.0 : Info - handleRedirectPromise called but there is no interaction in progress, returning null.
index.esm.js?dfc2:16954 [Wed, 01 Mar 2023 19:36:20 GMT] : @azure/msal-browser@2.32.0 : Info - Emitting event: msal:handleRedirectEnd
index.esm.js?dfc2:16954 [Wed, 01 Mar 2023 19:36:20 GMT] : @azure/msal-react@1.5.0 : Info - MsalProvider - msal:handleRedirectEnd results in setting inProgress from handleRedirect to none

index.esm.js?dfc2:710 Uncaught (in promise) BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.  For more visit: aka.ms/msaljs/browser-errors.
    at BrowserAuthError.AuthError [as constructor] (index.esm.js?dfc2:710:1)
    at new BrowserAuthError (index.esm.js?dfc2:8415:1)
    at BrowserAuthError.createInteractionInProgressError (index.esm.js?dfc2:8482:1)
    at BrowserCacheManager.setInteractionInProgress (index.esm.js?dfc2:10001:1)
    at ClientApplication.preflightInteractiveRequest (index.esm.js?dfc2:16336:1)
    at ClientApplication.preflightBrowserEnvironmentCheck (index.esm.js?dfc2:16321:1)
    at Identity.eval (index.esm.js?dfc2:15774:1)
    at step (index.esm.js?dfc2:183:1)
    at Object.eval [as next] (index.esm.js?dfc2:164:46)
    at eval (index.esm.js?dfc2:157:1)
    at new Promise (<anonymous>)
    at __awaiter$1 (index.esm.js?dfc2:153:1)
    at ClientApplication.acquireTokenRedirect (index.esm.js?dfc2:15768:1)
    at Identity.eval (index.esm.js?dfc2:16593:1)
    at step (index.esm.js?dfc2:183:1)
    at Object.eval [as next] (index.esm.js?dfc2:164:46)
    at eval (index.esm.js?dfc2:157:1)
    at new Promise (<anonymous>)
    at __awaiter$1 (index.esm.js?dfc2:153:1)
    at PublicClientApplication.loginRedirect (index.esm.js?dfc2:16588:1)
    at eval (index.esm.js?dfc2:19011:1)

### MSAL Configuration

```javascript
can't share the config here
```

### Relevant Code Snippets

```javascript
instance.handleRedirectPromise().then((tokenResponse) => {
        console.log('step1', tokenResponse)
        if (!tokenResponse) {
          const accounts = instance.getAllAccounts()
          console.log(accounts)
          if (accounts.length === 0) {
            if (inProgress === InteractionStatus.None) {
              instance.loginRedirect()
            }
          } else {
            setLoggedIn(true)
          }
        } else {
          instance
            .ssoSilent(authenticationRequest as SsoSilentRequest)
            .then((tokenCache) => {
              console.log('inside token cache', tokenCache)
              if (tokenCache?.account && !isLoggedIn && isMounted.current) {
                setLoggedIn(true)
              }
            })
        }
```

### Reproduction Steps

1. login one app and sso another app
2. logout from second app
3. and re-login
4. interaction_in_progress error.

### Expected Behavior

It should redirect to login page without throwing the error.

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari

### Regression

@azure/msal-browser 2.32.0

### Source

External (Customer)

**Comment by tnorling** [comment]
Could you [turn on `Trace` level logging](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logging.md) and share the output here?

**Comment by murali-bt** [comment]
@tnorling  please see the trace level logging. 

![Screenshot 2023-03-01 at 20 41 07](https://user-images.githubusercontent.com/92741519/222260316-a131ca12-3fba-498b-8dc4-88829178aae0.png)

**Comment by gitmurali** [comment]
@tnorling please see the trace level logging.

![Screenshot 2023-03-01 at 20 41 07](https://user-images.githubusercontent.com/25775153/222261269-2c00e4a0-6ca7-445a-8529-39e637a941d0.png)

**Comment by gitmurali** [comment]
@tnorling  can I manually set `setInteractionInProgress` to `false` ?

**Comment by tnorling** [comment]
These are not Trace logs, looks like still Info level. And no do not manually set interaction in progress

**Comment by gitmurali** [comment]
is this what you are looking for ?

![Screenshot 2023-03-01 at 23 09 12](https://user-images.githubusercontent.com/25775153/222287523-2fc6dc39-d590-4e20-a698-df3f2d46e370.png)

**Comment by tnorling** [comment]
Yes thanks. Is there any interaction happening at all when this throws? What happens if you clear local/session storage?

**Comment by gitmurali** [comment]
yeah I could see the msal.interaction.status in storage and cleared it and it now works fine. Thanks for help @tnorling
