### ISSUE TITLE
Claims challenges

### ISSUE THREAD

**Issue by Onokaev** [AzureAD/microsoft-authentication-library-for-js#5747]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.32.2

### Wrapper Library

Not Applicable

### Wrapper Library Version

@azure/msal-browser": "2.32.2"

### Public or Confidential Client?

Public

### Description

When an endpoint invokes a claims challenge, does MSAL invalidate the current token? I noticed that when doing an MFA to satisfy the claims challenge and I deny the request, my current token becomes invalid and I have to re-authenticate.
Is this the expected behavior?

### MSAL Configuration

```javascript
{
auth: {
    clientId,
    clientCapabilities: ['CP1']
  },
  cache: {
    cacheLocation: 'localStorage',
    storeAuthStateInCookie: true
  }
}
```

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
No, MSAL does not and cannot invalidate tokens. Can you please describe what exactly is the behavior you're seeing when you say the "current token becomes invalid"? If you had a claims challenge the current token was already invalid, no? What am I missing?

**Comment by Onokaev** [comment]
The issue was my code. 
When I canceled the login popup for the claims challenge, I was still making an acquireTokenSilent call with a claims parameter even though the claims challenge was not fulfilled. So I was getting a 401 and my app was trying to re-authenticate.
