### ISSUE TITLE
Cache usage and documentation is confusing

### ISSUE THREAD

**Issue by Lawton** [AzureAD/microsoft-authentication-library-for-js#5748]
### Core Library

MSAL Node (@azure/msal-node)

### Wrapper Library

Not Applicable

### Public or Confidential Client?

Confidential

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/caching.md

### Description

Over the past few days I've been trying to integrate MSAL into our application. Our system allows for users to add microsoft accounts to read some basic information off graph api. We use SQL database to persist tokens. We also integrate with other providers. After struggling for some time with MSAL I gave up on using the library and simply hit oauth endpoints directly. I was disappointed that the library wasn't more straightforward to use.

A lot of my confusion stemmed from the cache usage. In working with authentication platforms before I handle token refresh on my own. However MSAL looks to handle this for you.

The documentation on MSAL gives the option to persist using ICachePlugin, but doesn't explain the CacheContext object. The linked documentation about cache serialization sends me to .NET examples. I had to look outside microsoft documentation on stackoverflow to determine I need to call ` cacheContext.tokenCache.deserialize` and ` cacheContext.tokenCache.serialize` to write and read to MSAL memory cache respectively. However I still am unsure what is contained in tokenCache itself.

The documentation further suggestions `serialize one cache blob per user` and recommends using DistributedCachePlugin. But does not fully explain why (the reason is perhaps implied, but not explicit). Again I found my answer outside this repo that it was due to each user being added to in memory cache context which quickly gets bloated. Something that does not feel particularly relevant for a serverless application.

Even after a lot of reading and research I'm not sure I understand the cache correctly and I don't want to commit the time to determining if my assumptions are correct. That's why I gave up on the library.

Because MSAL forces the user to use it's cache strategy and abstracts away token refreshing I feel like the cache is one of the most important aspects of the library, but the documentation is very short. I would really appreciate more detail in the cache documentation, not just on what needs to be done, but why and how.

Alternatively I would desire a library that comes without the cache altogether and allows us to create our own cache and refresh strategy.

**Comment by derisen** [comment]
@Lawton @tnorling apologies for the confusion, we are aware that the current state of our caching guidance leaves much to be desired. In the next couple of days we will be starting to update our docs and samples to help alleviate these issues. We would appreciate your input along the process. I'll leave the issue open until then. cc @bgavrilMS @sameerag

**Comment by Lawton** [comment]
@derisen thanks for the prompt response. Yes I can tell that there has been a lot of changes to the cache so I understand why the documentation may not be polished. I just wanted to provide candid feedback while it was still fresh in my mind. I'll do my best to provide input if you have any questions for me.

**Comment by derisen** [comment]
@Lawton we are have a few PRs open for caching guidance and more samples. Would really appreciate if you have any suggestions or concerns:

https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/5784
https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/5772
https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/5766
https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/5760

**Comment by Lawton** [comment]
Thanks for the follow up. I added my thoughts on #5784 I didn't have a chance to dig through the example code. If you have something specific on the example code your looking for feedback let me know. I think the updates are an improvement, though I outlined some areas that I stumbled on with the documentation that I feel still aren't completely clear.

**Comment by sameerag** [comment]
Great. I see @derisen is addressing a few of them in the linked PR. If nothing else, can we close this issue?

**Comment by Lawton** [comment]
Yes I can close the ticket. Thanks.

**Comment by bpossolo** [comment]
I created a new issue with my comments since this one is unlikely to be re-opened
https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5854
