### ISSUE TITLE
acquireTokenInteractive API redirects to the success template when the token request is rejected

### ISSUE THREAD

**Issue by salman90** [AzureAD/microsoft-authentication-library-for-js#5749]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.15.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

0

### Public or Confidential Client?

Public

### Description

When using `acquireTokenInteractive` API with the [Electron System browser sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/ElectronSystemBrowserTestApp), the API redirects the user to the success template even when the token request fails. The issue is that the user is redirected to the success or failure templates after receiving the [authorization code](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/src/client/PublicClientApplication.ts#L112), not the token, as shown in the [LoopbackClient class](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/src/network/LoopbackClient.ts#L26). While the token request will fail in the application's terminal, the user will still be redirected to the success template in the browser.

### Error Message

(node:31352) UnhandledPromiseRejectionWarning: ServerError: invalid_client: 7000218 - [2023-03-02 16:37:02Z]: AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
Trace ID: 108d9647-1061-4bfa-9985-b2dcdffc4901
Correlation ID: e7dfbda4-05aa-4663-a600-413c89c5df9f
Timestamp: 2023-03-02 16:37:02Z - Correlation ID: e7dfbda4-05aa-4663-a600-413c89c5df9f - Trace ID: 108d9647-1061-4bfa-9985-b2dcdffc4901
    at ServerError.AuthError [as constructor] (C:\github\ciam\ms-identity-ciam-javascript-tutorial\1-Authentication\3-sign-in-electron\App\node_modules\@azure\msal-common\dist\index.cjs.js:517:24)
    at new ServerError (C:\github\ciam\ms-identity-ciam-javascript-tutorial\1-Authentication\3-sign-in-electron\App\node_modules\@azure\msal-common\dist\index.cjs.js:3369:28)
    at ResponseHandler.validateTokenResponse (C:\github\ciam\ms-identity-ciam-javascript-tutorial\1-Authentication\3-sign-in-electron\App\node_modules\@azure\msal-common\dist\index.cjs.js:5262:19)
    at AuthorizationCodeClient.<anonymous> (C:\github\ciam\ms-identity-ciam-javascript-tutorial\1-Authentication\3-sign-in-electron\App\node_modules\@azure\msal-common\dist\index.cjs.js:5566:41)
    at step (C:\github\ciam\ms-identity-ciam-javascript-tutorial\1-Authentication\3-sign-in-electron\App\node_modules\@azure\msal-common\dist\index.cjs.js:79:23)
    at Object.next (C:\github\ciam\ms-identity-ciam-javascript-tutorial\1-Authentication\3-sign-in-electron\App\node_modules\@azure\msal-common\dist\index.cjs.js:60:53)
    at fulfilled (C:\github\ciam\ms-identity-ciam-javascript-tutorial\1-Authentication\3-sign-in-electron\App\node_modules\@azure\msal-common\dist\index.cjs.js:50:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:31352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

### Msal Logs

[Thu, 02 Mar 2023 16:36:48 GMT] : @azure/msal-node@1.15.0 : Info - getTokenCache called
[Thu, 02 Mar 2023 16:36:50 GMT] : @azure/msal-node@1.15.0 : Info - getAuthCodeUrl called
[Thu, 02 Mar 2023 16:36:50 GMT] : @azure/msal-node@1.15.0 : Verbose - initializeRequestScopes called
[Thu, 02 Mar 2023 16:36:50 GMT] : [df5c3b55-4693-4ec4-8569-ede074253b07] : @azure/msal-node@1.15.0 : Verbose - buildOauthClientConfiguration called
[Thu, 02 Mar 2023 16:36:50 GMT] : [df5c3b55-4693-4ec4-8569-ede074253b07] : @azure/msal-node@1.15.0 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/556b80b7-c9fc-41fd-92da-c3635f7918e5
[Thu, 02 Mar 2023 16:36:50 GMT] : [df5c3b55-4693-4ec4-8569-ede074253b07] : @azure/msal-node@1.15.0 : Verbose - createAuthority called
[Thu, 02 Mar 2023 16:36:50 GMT] : @azure/msal-node@1.15.0 : Verbose - Attempting to get cloud discovery metadata in the config     
[Thu, 02 Mar 2023 16:36:50 GMT] : @azure/msal-node@1.15.0 : Verbose - Did not find cloud discovery metadata in the config... Attempting to get cloud discovery metadata from the cache.
[Thu, 02 Mar 2023 16:36:50 GMT] : @azure/msal-node@1.15.0 : Verbose - Did not find cloud discovery metadata in the cache... Attempting to get cloud discovery metadata from the network.
[Thu, 02 Mar 2023 16:36:50 GMT] : @azure/msal-node@1.15.0 : Verbose - Attempting to find a match between the developer's authority and the CloudInstanceDiscoveryMetadata returned from the network request.
[Thu, 02 Mar 2023 16:36:50 GMT] : @azure/msal-node@1.15.0 : Verbose - cloud discovery metadata was successfully returned from getCloudDiscoveryMetadataFromNetwork()
[Thu, 02 Mar 2023 16:36:50 GMT] : [df5c3b55-4693-4ec4-8569-ede074253b07] : @azure/msal-node@1.15.0 : Verbose - Auth code client created
[Thu, 02 Mar 2023 16:37:01 GMT] : @azure/msal-node@1.15.0 : Info - acquireTokenByCode called
[Thu, 02 Mar 2023 16:37:01 GMT] : @azure/msal-node@1.15.0 : Verbose - initializeRequestScopes called
[Thu, 02 Mar 2023 16:37:01 GMT] : [3e1c952c-9fb5-4164-a5e0-5b3639f496e7] : @azure/msal-node@1.15.0 : Verbose - buildOauthClientConfiguration called
[Thu, 02 Mar 2023 16:37:01 GMT] : [3e1c952c-9fb5-4164-a5e0-5b3639f496e7] : @azure/msal-node@1.15.0 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/556b80b7-c9fc-41fd-92da-c3635f7918e5
[Thu, 02 Mar 2023 16:37:01 GMT] : [3e1c952c-9fb5-4164-a5e0-5b3639f496e7] : @azure/msal-node@1.15.0 : Verbose - createAuthority called
[Thu, 02 Mar 2023 16:37:01 GMT] : @azure/msal-node@1.15.0 : Verbose - Attempting to get cloud discovery metadata in the config     
[Thu, 02 Mar 2023 16:37:01 GMT] : @azure/msal-node@1.15.0 : Verbose - Did not find cloud discovery metadata in the config... Attempting to get cloud discovery metadata from the cache.
[Thu, 02 Mar 2023 16:37:01 GMT] : @azure/msal-node@1.15.0 : Verbose - Found metadata in the cache.
[Thu, 02 Mar 2023 16:37:01 GMT] : [3e1c952c-9fb5-4164-a5e0-5b3639f496e7] : @azure/msal-node@1.15.0 : Verbose - Auth code client created
[Thu, 02 Mar 2023 16:37:01 GMT] : [3e1c952c-9fb5-4164-a5e0-5b3639f496e7] : @azure/msal-common@10.0.0 : Info - in acquireToken call in auth-code client

### MSAL Configuration

```javascript
{
    "authOptions":
        {
            "clientId": "ApplicationId",
            "authority": "https://login.microsoftonline.com/TenantID"
        },
    "resourceApi":
    {
        "endpoint": "https://graph.microsoft.com/v1.0",
        "scopes": ["User.Read", "Mail.Read"]
    },
    "customProtocol":
    {
        "name": "msalApplicationId"
    },
    "cache": {
        "cacheLocation": "./data/cache.json"
    }
}
```

### Relevant Code Snippets

```javascript
async getTokenInteractive(
        tokenRequest: SilentFlowRequest
    ): Promise<AuthenticationResult> {
        try {
            /**
             * A loopback server of your own implementation, which can have custom logic
             * such as attempting to listen on a given port if it is available.
             */
            const customLoopbackClient = await CustomLoopbackClient.initialize(3874);

            // opens a browser instance via Electron shell API
            const openBrowser = async (url: any) => {
                if (process.env.automation != null) {
                    // publishTest is used only in the testing environment to listen to the AuthCodeURL
                    this.publishTest(IpcMessages.GET_AUTH_CODE_URL, url);
                } else {
                    await shell.openExternal(url);
                }
            };
            const interactiveRequest: InteractiveRequest = {
                ...tokenRequest,
                openBrowser,
                successTemplate: fs
                    .readFileSync("./public/successTemplate.html", "utf8")
                    .toString(),
                errorTemplate: fs
                    .readFileSync("./public/errorTemplate.html", "utf8")
                    .toString(),
                loopbackClient: customLoopbackClient // overrides default loopback client
            };

            const authResponse =
                await this.clientApplication.acquireTokenInteractive(
                    interactiveRequest
                );          
            return authResponse;
        } catch (error) {
            throw error;
        }
    }
```

### Reproduction Steps

1. Run the [Electron system browser sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/ElectronSystemBrowserTestApp).
2. [ Configure an application registration in Azure AD ](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/ElectronSystemBrowserTestApp#configure-the-application)for electron and change the desktop Authentication type to web to reproduce the error.
3. Login to the application.
4. The application will redirect to the success template while the token will be rejected.

### Expected Behavior

The expected behavior is for the application to redirect to the error template in the browser.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
This is expected behavior. The success/error templates are used for the auth code acquisition because it needs to redirect to something but it's not really part of the application. You should not build logic off these templates. The API itself will return or throw based on the result of the entire flow.
