### ISSUE TITLE
Angular 4 support

### ISSUE THREAD

**Issue by jasonshsoftware** [AzureAD/microsoft-authentication-library-for-js#575]
## I'm submitting a...
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report  
- [ ] Performance issue
- [ ] Feature request
- [x] Documentation issue or request
- [ ] Other... Please describe:

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version
MSAL-Angular Library version: 0.1.2
Angular version 4.4.3

## Current behavior
`ng build` does not build the application with with angular 4.3+. The readme for MSAL-angular states that angular 4.3+ is supported.

When trying to build, I receive the following build error:
`Metadata version mismatch for module .../node_modules/@azure/msal-angular/dist/index.d.ts, found version 4, expected 3`

## Expected behavior
Is there a build of MSAL-angular that does support angular 4.4.3?

**Comment by SainathReddy-GNV** [comment]
I also facing the same issue is there any workaround for this

**Comment by jasonshsoftware** [comment]
I have found no workaround. We are advising teams to upgrade to the latest angular framework.

**Comment by sameerag** [comment]
Probably not. Our angular wrapper work which is coming up in the [roadmap](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#roadmap) will include support to the later angular versions. 

@DarylThayil Any more ideas?

**Comment by DarylThayil** [comment]
cc @jasonnutter  if you have a chance can you look at this error and see if we are missing anything here for a quick fix?

**Comment by jasonnutter** [comment]
This seems strange to me given the wrapper is built with angular 4.3, but no quick fixes come to mind unfortunately.

**Comment by jmckennon** [comment]
@jasonshsoftware Closing this at it's been some time. If you're still seeing this issue please comment and we'll reopen the issue.
