### ISSUE TITLE
A non-MSALJS error was thrown while attempting to get the cloud instance discovery metadata

### ISSUE THREAD

**Issue by xiaolang124** [AzureAD/microsoft-authentication-library-for-js#5779]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.14.6

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

We are developing a VS Code extension to help users to develop Teams applications. We are using msal/node to login M365 account. Some of my users have reported this issue. When signing in to the microsoft 365 account to enable side-loading, instead of opening a login page in browser its immediately logging the below in the output tab.

```
 [Error] - [Wed, 08 Mar 2023 16:34:51 GMT] : @azure/msal-node@1.14.6 : Error - A non-MSALJS error was thrown while attempting to get the cloud instance discovery metadata. Error: Error Error Description: Error: certificate has expired
```

Do you know why this happen and how can we solve this?

### Error Message

 [Error] - [Wed, 08 Mar 2023 16:34:51 GMT] : @azure/msal-node@1.14.6 : Error - A non-MSALJS error was thrown while attempting to get the cloud instance discovery metadata. Error: Error Error Description: Error: certificate has expired

### MSAL Configuration

```javascript
const config = {
  auth: {
    clientId: "7ea7c24c-b1f6-4a20-9d11-9ae12e9e7ac0",
    authority: "https://login.microsoftonline.com/common",
  },
  system: {
    loggerOptions: {
      // @ts-ignore
      loggerCallback(loglevel, message, containsPii) {
        if (loglevel <= LogLevel.Error) {
          VsCodeLogInstance.error(message);
        }
      },
      piiLoggingEnabled: false,
      logLevel: LogLevel.Error,
    },
  },
  cache: {
    cachePlugin,
  },
};

https://github.com/OfficeDev/TeamsFx/blob/c3493c756cb902d59789c6e50ca874843957f3fa/packages/vscode-extension/src/commonlib/m365Login.ts#L49
```

### Relevant Code Snippets

```javascript
if (!this.account) {
      const accessToken = await this.login(scopes, loginHint);
      return ok(accessToken);
    } else {
      try {
        const res = await this.pca.acquireTokenSilent({
          account: this.account,
          scopes: scopes,
          forceRefresh: false,
        });
        if (res) {
          return ok(res.accessToken);
        } else {
          return err(LoginCodeFlowError(new Error("No token response.")));
        }
      } catch (error) {
        VsCodeLogInstance.error(
          "[Login] " +
            stringUtil.format(
              localize("teamstoolkit.codeFlowLogin.silentAcquireToken"),
              path.join(os.homedir(), ".fx", "account"),
              error.message
            )
        );
        if (!(await checkIsOnline())) {
          return error(CheckOnlineError());
        }
        await this.logout();
        if (refresh) {
          const accessToken = await this.login(scopes, loginHint);
          return ok(accessToken);
        }
        return err(LoginCodeFlowError(error));
      }
    }

https://github.com/OfficeDev/TeamsFx/blob/c3493c756cb902d59789c6e50ca874843957f3fa/packages/vscode-extension/src/commonlib/codeFlowLogin.ts#L370
```

### Reproduction Steps

I'm not sure how to reproduce this.

### Expected Behavior

Open a login page in browser.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

External (Customer)

**Comment by xiaolang124** [comment]
Related issue: https://github.com/OfficeDev/TeamsFx/issues/7995

**Comment by lalimasharda** [comment]
Hey @xiaolang124 , which MSAL or ADAL are you using in your application?

**Comment by xiaolang124** [comment]
> Hey @xiaolang124 , which MSAL or ADAL are you using in your application?

We are using 1.14.6 @azure/msal-node.

**Comment by sameerag** [comment]
@xiaolang124 The linked issues show this could be a certs issue. Did you try the alternatives suggested?

**Comment by xiaolang124** [comment]
> @xiaolang124 The linked issues show this could be a certs issue. Did you try the alternatives suggested?

Yes, the user unchecks 'Proxy: System Certificates' in VsCode will solve the issue. Maybe something about extension network is wrong in VsCode.

**Comment by sameerag** [comment]
@xiaolang124 So is this a localized error based on your network settings?
