### ISSUE TITLE
Storing refreshToken for running task on behalf of the user on a schedule.

### ISSUE THREAD

**Issue by ramaguruprakash** [AzureAD/microsoft-authentication-library-for-js#5781]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.8.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Confidential

### Description

I am building an excel addin that talks to our webapi with the accessToken. The webapi does some actions on the excel sheet based on user instructions. The user should be able to set a schedule for the instructions and the webapi needs to perform those actions on a schedule. 

My initial idea is to store the refresh token in a db and use it to fetch the accesstoken for onBehalfOf flow on schedule specified by the user. But I am unable to get the refresh token. What is the general pattern used in case we want to run actions on behalf of the user on a schedule from the webapi.

### Relevant Code Snippets

```javascript
function getConfidentialClientApplication() {
    // Create msal application object
    return new msal.ConfidentialClientApplication(config);
  };

 const cca = authHelper.getConfidentialClientApplication();
  try {
     const res =  await cca.acquireTokenOnBehalfOf(oboRequest);
     // the res doesnot have refresh token for offline access. How can I get accessToken in a background task. Can I store the refresh token ?
  } catch(err) {
      console.log('acquire obo', err);
      throw err;
  }
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by lalimasharda** [comment]
Hey @ramaguruprakash there is a doc on this: [Docs](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/faq.md#how-do-i-get-the-refresh-token)

Does this help?

**Comment by ramaguruprakash** [comment]
Hey, I am not using MSAL in the backend and relying directly on the https calls for fetching the refresh token. The idea is to run few tasks on behalf of the user even when the user is not loggedin

**Comment by sameerag** [comment]
@ramaguruprakash If you are fetching the `refresh_token` yourself, can you then call `msal-node` with `acquireTokenByRefreshToken`, reference [here](https://azuread.github.io/microsoft-authentication-library-for-js/ref/classes/_azure_msal_node.clientapplication.html#acquiretokenbyrefreshtoken) to hydrate the `msal-node` cache and then proceed with the OBO flow?

**Comment by mpalmerlee** [comment]
In case it helps anyone else, I ran into the same issue when using `acquireTokenSilent` for a multi-user app since the [CacheContext](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-node-samples/cachePlugin.js) passed into the `beforeCacheAccess` and `afterCacheAccess` is the entire cache not just the element for the current key. What helped me was this section on [Performance](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/performance.md#performance-considerations-for-confidential-client-applications). Specifically this hint:
> we recommend to scope MSAL ConfidenticalClientApplication (CCA) instances to each user, request or session.

Using this pattern we can create an instance of the `ConfidenticalClientApplication` for each user and then serialize the proper tokens in the `beforeCacheAccess` and `afterCacheAccess` methods as necessary.

**Comment by ramaguruprakash** [comment]
@sameerag , Thanks for the update. we are doing something like that. Where we are using the following API call to get the obo token.

```
POST /common/oauth2/v2.0/token HTTP/1.1
Host: login.microsoftonline.com
Content-Type: application/x-www-form-urlencoded

grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer&client_id=<app client id>&client_secret=<client secret>&assertion=<access token>&scope=https://graph.microsoft.com/offline_access&requested_token_use=on_behalf_of
```

And then using the following API call to get the access token given the refresh token.
```POST /common/oauth2/v2.0/token HTTP/1.1
Host: login.microsoftonline.com
Content-Type: application/x-www-form-urlencoded

client_id=<app client id>&scope=https://graph.microsoft.com/offline_access&grant_type=refresh_token&client_secret=<client secret>&refresh_token=<refresh token>
```

we can use MSAL library as well but will we get any advantage given that we will not have MSAL node object active all the time ?

**Comment by ramaguruprakash** [comment]
Also, I am finding other issues as well. I am building an office excel add-in and want to the following flow.

On Install and launch -
1. Try to acquire SSO token.
```
await OfficeRuntime.auth.getAccessToken({
                allowSignInPrompt: true,
                allowConsentPrompt: true,
                forMSGraphAccess: true,
            });
```
2. Expectation is that it should fail because user did not give consent for all the ms graph permissions listed in the registered azure application. This does not happen, I am able to acquire the tokens even if there are no consents on all the MS graph permissions. . (I am testing it by revoking the permissions and relaunching it)
3. I am forced to use MSAL acquireTokensSilent which requires the user to re authenticate everytime he launches the application. 


Is there a cleaner way of doing all this. I know the add-in part is not part of this repository but any light on this problem would be helpful.

**Comment by sameerag** [comment]
> 2. Expectation is that it should fail because user did not give consent for all the ms graph permissions listed in the registered azure application. This does not happen, I am able to acquire the tokens even if there are no consents on all the MS graph permissions. . (I am testing it by revoking the permissions and relaunching it)

Is it possible the tokens are pulled from cache? 

> 3. I am forced to use MSAL acquireTokensSilent which requires the user to re authenticate every time he launches the application.

Are you looking for SSO here? You need to call some MSAL JS API for auth right?
