### ISSUE TITLE
Intermittent 400 result code while fetching token https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/token

### ISSUE THREAD

**Issue by nitigupta11** [AzureAD/microsoft-authentication-library-for-js#5799]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.16.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

1.1.0

### Public or Confidential Client?

Public

### Description

Facing strange issue of getting 400 result code for POST https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/v2.0/token intermittently which we are not able to repro but we have few instances in our App Insights having 400 as result code
<img width="932" alt="image" src="https://user-images.githubusercontent.com/13751503/225688006-d03b1b4b-235b-4708-b4f7-35302b3ecb32.png">

### Error Message

it just gives 400  result code

### MSAL Configuration

```javascript
authentication: {
		msalConfig: {
		  auth: {
			clientId: "b12ca5c0-ea9d-4d0f-9eec-8e5463be5c82",
			authority:
			  "https://login.microsoftonline.com/microsoft.onmicrosoft.com",
			redirectUri: window.location.origin,
			knownAuthorities: ["login.microsoftonline.com"],
		  },
		  cache: {
			cacheLocation: "sessionStorage",
			storeAuthStateInCookie: false,
		  },
		},
		scopes: [
			"api://060093e8-aa23-4eba-9208-5e14e5a75854/TemplateService.Crud",
		],
	  }
```

### Relevant Code Snippets

```javascript
export const getAuthenticationToken = async (
  scope: string[]
): Promise<string> => {


  const account = publicClientApplication().getAllAccounts()[0];
  // to avoid warning in unit tests
  if (!account) {
    return "";
  }
  const silentTokenRequest = { scopes: scope, account };
  const authenticationResponse =
    await publicClientApplication().acquireTokenSilent(silentTokenRequest);
  return authenticationResponse.accessToken;
};
```

### Reproduction Steps

We are not able to repro it. we don't know what is causing this issue intermittently.

### Expected Behavior

Since we are using acquireTokensilent we should not get 400.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer

### Regression

NA

### Source

Internal (Microsoft)

**Comment by sameerag** [comment]
@nitigupta11 This does not look like an MSAL issue. Can you please share your fiddler trace and msal verbose logs (instructions [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logging.md))? You can send the trace to my email (in my profile).

Also curious why you added `login.microsoftonline.com` in `knownAuthorities`.

Note: `acquireTokenSilent` can make a network call in the background using iframes if it needs to fetch new tokens from the service when the session is still active. However I am surprised at the `400` as the request format stays the same.

**Comment by ADNewsom09** [comment]
we are having the same issue.

**Comment by sivapokuri** [comment]
I'm facing same issue. Any solution for this?
