### ISSUE TITLE
Login popup does not appear

### ISSUE THREAD

**Issue by sberthu** [AzureAD/microsoft-authentication-library-for-js#5801]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

2.5.4

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.5.4

### Public or Confidential Client?

Public

### Description

The Microsoft login box does not appear after update @azure/msal-angular to version 2.5.4.

here is my package.json dependencies causing the issue:
    "@angular/animations": "^14.0.4",
    "@angular/cdk": "^14.0.4",
    "@angular/common": "^14.0.4",
    "@angular/compiler": "^14.0.4",
    "@angular/core": "^14.0.4",
    "@angular/forms": "^14.0.4",
    "@angular/material": "^14.0.4",
    "@angular/platform-browser": "^14.0.4",
    "@angular/platform-browser-dynamic": "^14.0.4",
    "@angular/router": "^14.0.4",
    "@azure/msal-angular": "^2.5.0",
    "@azure/msal-browser": "^2.34.0",
    "rxjs": "~7.4.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"

and, for the moment,  I correct it to :
here is my package.json dependencies:
    "@angular/animations": "^14.0.4",
    "@angular/cdk": "^14.0.4",
    "@angular/common": "^14.0.4",
    "@angular/compiler": "^14.0.4",
    "@angular/core": "^14.0.4",
    "@angular/forms": "^14.0.4",
    "@angular/material": "^14.0.4",
    "@angular/platform-browser": "^14.0.4",
    "@angular/platform-browser-dynamic": "^14.0.4",
    "@angular/router": "^14.0.4",
    "@azure/msal-angular": "2.5.3",
    "@azure/msal-browser": "^2.34.0",
    "rxjs": "~7.4.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"

### Error Message

[Fri, 17 Mar 2023 08:54:23 GMT] : @azure/msal-angular@2.5.4 : Error - Interceptor - acquireTokenSilent rejected with error. Invoking interaction to resolve.
(but I had the this message in version 2.5.3 too)

### Msal Logs

[Fri, 17 Mar 2023 08:54:23 GMT] : @azure/msal-angular@2.5.4 : Error - Interceptor - acquireTokenSilent rejected with error. Invoking interaction to resolve.
(but I had the this message in version 2.5.3 too)

### MSAL Configuration

```javascript
{
        auth: {
            clientId: environment.msalConfiguration.clientId,
            authority: environment.msalConfiguration.authority,
            redirectUri: environment.msalConfiguration.redirectUri
        },
        cache: {
            cacheLocation: BrowserCacheLocation.LocalStorage,
            storeAuthStateInCookie: isIE, // set to true for IE 11
        },
        system: {
            loggerOptions: {
                loggerCallback,
                logLevel: environment.production? LogLevel.Error : LogLevel.Error,
                piiLoggingEnabled: false
            }
        }
    }
```

### Relevant Code Snippets

```javascript
app.module.ts configuration:
  providers: [
    {
      provide: HTTP_INTERCEPTORS,
      useClass: MsalInterceptor,
      multi: true
    }
}

msal-configuration.ts:

import { MsalGuardConfiguration, MsalInterceptorConfiguration } from "@azure/msal-angular";
import { BrowserCacheLocation, InteractionType, IPublicClientApplication, PublicClientApplication, LogLevel } from "@azure/msal-browser";
import { environment } from "src/environments/environment";

export function loggerCallback(logLevel: LogLevel, message: string) {
    console.log(message);
}

export function MSALInstanceFactory(): IPublicClientApplication {
    const isIE = window.navigator.userAgent.indexOf("MSIE ") > -1 || window.navigator.userAgent.indexOf("Trident/") > -1;
    return new PublicClientApplication({
        auth: {
            clientId: environment.msalConfiguration.clientId,
            authority: environment.msalConfiguration.authority,
            redirectUri: environment.msalConfiguration.redirectUri
        },
        cache: {
            cacheLocation: BrowserCacheLocation.LocalStorage,
            storeAuthStateInCookie: isIE, // set to true for IE 11
        },
        system: {
            loggerOptions: {
                loggerCallback,
                logLevel: environment.production? LogLevel.Error : LogLevel.Error,
                piiLoggingEnabled: false
            }
        }
    });
}

export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
    const protectedResourceMap = new Map<string, Array<string>>();
    protectedResourceMap.set(environment.adminBackendUrl +'/*', environment.msalConfiguration.consentScopes);
  
    return {
      interactionType: InteractionType.Popup,
      protectedResourceMap
    };
  }

export function MSALGuardConfigFactory(): MsalGuardConfiguration {
    return {
        interactionType: InteractionType.Popup,
        authRequest: {
            scopes: environment.msalConfiguration.consentScopes
        }
    };
}
```

### Reproduction Steps

Important Note: In my CICD (azure devops), the node_modules folder is always removed before publishing.

1. After push a new version, the CICD compile the angular project:ok - no problem.

2. But when we go the the page, the Login Box does not appear any more.

3. I search in the package-lock.json file and see that the @azure/msal-angular is now to version 2.5.4.

4. So, I downgrade @azure/msal-angular to the version 2.5.3 and the login box appears again.

5. So, I upgrade again to @azure/msal-angular:2.5.4 and the login box does not appear.

Note: On my local system (development), I did not see the problem because I do never remove the node_modules folder.
But after deleting the node_modules folder, the issue is on my local system too.

### Expected Behavior

I expect than the Microsoft Login popup appears.
but it doesn't.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Regression

 @azure/msal-angular:2.5.3

### Source

External (Customer)

**Comment by sameerag** [comment]
@sberthu Can you share the msal-angular logs here by enabling `verbose` mode? Instructions are [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/logging.md)

**Comment by mdarefull** [comment]
This is happening to me as well. It started happening right when I upgraded from 2.5.3 to 2.5.4. 

I leverage MsalInterceptor to easily log the user into my app. 
Here's how it works: As soon as the app has initialized and stabilized, I perform a request to a protected API to retrieve the user information, if there's no token, the interceptor tries silently, if the user is not logged in, this fails and automatically opens the login popup. As of the new version 2.5.4, the error '@azure/msal-angular@2.5.4 : Error - Interceptor - acquireTokenSilent rejected with error. Invoking interaction to resolve.' is still being thrown, but no login popup is shown.

Rollbacked to the previous 2.5.3 version, and it's working as before.

**Comment by sameerag** [comment]
@hectormmg Can you please check this?

**Comment by jo-arroyo** [comment]
@sberthu @mdarefull Are you still seeing this behavior with 2.5.5? Are you able to reproduce this behavior in our [sample apps](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples)?

Please also provide verbose logs (instructions above) to help us diagnose whether this is an issue with MSAL Angular or changes made in the core libraries.
