### ISSUE TITLE
Azure b2c application is getting signed out after 2 hours even while using continuously

### ISSUE THREAD

**Issue by garvraj** [AzureAD/microsoft-authentication-library-for-js#5802]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

 "@azure/msal-browser": "^2.16.0",

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

    "@azure/msal-angular": "^2.0.2",

### Public or Confidential Client?

Public

### Description

Azure b2c application is getting signed out after 2 hours, trying to add the code for renew the token using acquireTokenSilent but that is not working, it still log out after 2 hours

I have added a code , to acquireTokenSilent before 15 minutes of token expiry . The code is getting executed before 15 minutes and I am setting the new accessToken in localstorage which I get from acquireTokenSilent(), but as soon as 2 hours completes, It still log out

### MSAL Configuration

```javascript
Configuration = {
  auth: {
    clientId: environment.clientId,
    authority: b2cPolicies.authorities.signUpSignIn.authority,
    knownAuthorities: [b2cPolicies.authorityDomain],
    redirectUri: '/',
    postLogoutRedirectUri: '/'
  },
  cache: {
    cacheLocation: BrowserCacheLocation.LocalStorage,
    storeAuthStateInCookie: isIE, // Set this to "true" if you are having issues on IE11 or Edge
  },
  system: {
    loggerOptions: {
      loggerCallback(logLevel: LogLevel, message: string) {
        console.log(message);
      },
      logLevel: LogLevel.Verbose,
      piiLoggingEnabled: false
    },
    tokenRenewalOffsetSeconds: 300
    iframeHashTimeout: 10000,
  }
}
```

### Relevant Code Snippets

```javascript
Below is the code I am using to get the new token 
    getRefreshToken(){
        const accountInfo:any = (this.authService.instance.getAllAccounts()?.length) ?this.authService.instance.getAllAccounts()[0]: ''
        this.authService.acquireTokenSilent({
          scopes: [environment.scope],
          account: accountInfo
        }).subscribe((tokenResponse: any) => {
          localStorage.setItem('currentUserToken', tokenResponse.idToken);
        },
          (error) => {
            if (error instanceof InteractionRequiredAuthError) {
            this.authService.acquireTokenRedirect({
              authority: environment.authority,
              scopes: [
                environment.scope
              ]
            })
          }
            if (error.errorMessage.includes("AADB2C90077")) {
              this.authService.acquireTokenRedirect({
                authority: environment.authority,
                scopes: [
                  environment.scope
                ]
              })
            }
          });
      }
```

### Reproduction Steps

Wait for the application to loggedout

### Expected Behavior

The token should be refreshed and use should not be logged out automatically

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox

### Source

Internal (Microsoft)

**Comment by sameerag** [comment]
@garvraj Can you please share verbose msal logs? Instructions [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logging.md)

**Comment by garvraj** [comment]
> @garvraj Can you please share verbose msal logs? Instructions [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logging.md)

verbose msal logs - at the time when it gets logged out?

**Comment by garvraj** [comment]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/41892368/226118075-097395db-657e-4628-91db-e854305a45a0.png">

**Comment by garvraj** [comment]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/41892368/226152702-1fb2b4ec-ad9c-4a62-b8f5-32a6c57b6362.png">
this is after it gets logged out

**Comment by sameerag** [comment]
@garvraj  Looks like your AAD session is logged out too, as `ssoSilent` is failing. Can you please share the fiddler trace? My email is in my profile. 

My two cents: Your policies may be enabling session logout in 2 hrs. MSAL does not determine session lifetimes. We only try our best to get the token silently for you and then throw an error for the app to initiate interaction.

In this case, can you share if the error you are seeing is "interaction_required"?

**Comment by sameerag** [comment]
@garvraj Can you also share the `correlation-id` for these requests and the `timestamp` for the same? This will help us gather the token lifetime in your use case.

**Comment by garvraj** [comment]
Your policies may be enabling session logout in 2 hrs - yes I have set it to 2 hrs, but the expectation is it should log out after 2 hours when the application is not in use, but when I am continuously using it , it should not log out

Can you please share the fiddler trace? - Do you mean the jsfiddle sample with my msal configuration?

Can you also share the correlation-id for these requests and the timestamp for the same? This will help us gather the token lifetime in your use case. - You want the correlation-id and timestamp when it gets loggedout?

@sameerag

**Comment by garvraj** [comment]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/41892368/226544844-fabd0b55-00d1-4977-9477-9b437d47bf73.png">

**Comment by sameerag** [comment]
@garvraj You logs above do not show the user being logged out. Can you please describe what is the user experience? Are you asked for interaction again?

**Comment by garvraj** [comment]
> @garvraj You logs above do not show the user being logged out. Can you please describe what is the user experience? Are you asked for interaction again?

It happens only after 2 hours because we have 2 hours session time in azure portal, the requirement is the user should not get logged out when they are continuously using it

**Comment by jo-arroyo** [comment]
@garvraj Can you please email me the following information:
1. Verbose logs showing all logs and errors when the user is logged out (the screenshots do not show us the full story). In particular, we are looking for an `interaction_required` error.
2. A network trace of the same behavior
3. The correlationId and timestamp of when the token is first issued.

My email is in my profile. Thank you.
