### ISSUE TITLE
Use the token from Msal in Parallel  - when to call acquireTokenSilent correctly

### ISSUE THREAD

**Issue by fong1999** [AzureAD/microsoft-authentication-library-for-js#5803]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.11.2

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.x

### Public or Confidential Client?

Public

### Description

How does the SPA initialize Msal at the first place? What is the workflow of Msal? 

If we are using `msal-react` and `msal-browser`. So as long as we do the steps are described in below document, the Msal is running at the time the app is up? 

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/initialization.md

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/initialization.md#initializing-the-publicclientapplication-object

Thanks!

### Relevant Code Snippets

```javascript
import * as Msal from "@azure/msal-browser";
import BrowserUtils from "../utils/BrowserUtils";
import EnvironmentService from "./EnvironmentService";

export const msalConfig: Msal.Configuration = {
  auth: {
    clientId: EnvironmentService.getAzureClientId(),
    redirectUri: `${window.location.origin}`,
    authority: `https://login.microsoftonline.com/${EnvironmentService.getAzureTenantId()}`
  },
  cache: {
    cacheLocation: "sessionStorage",
    storeAuthStateInCookie: true,
  }
}

const loginRequest = {
  scopes: ["openid", "profile", "User.Read"]
}

/**
 * Sets flag forceRefresh to true, the program will skip the cached id token in sessionStorage,
 * it will call the server directly to get a new id token and replace the catched one with this new
 * value to sessionStorage.
 * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md#how-do-i-renew-tokens-with-msaljs
 */
const tokenRequestForceRefresh = {
  scopes: ["User.Read"],
  forceRefresh: true,
}

export let myMSALObj: Msal.PublicClientApplication;
export let username = "";


myMSALObj = new Msal.PublicClientApplication(msalConfig);
// Redirect: once login is successful and redirects with tokens, call Graph API
myMSALObj.handleRedirectPromise().then(handleResponse).catch(err => {
  console.error(err);
});


export function hasActiveMsalSession(): boolean {
  return !!username;
}

function handleResponse(resp) {
  if (resp !== null) {
    username = resp.account.username;
  } else {
    /**
     * See here for more info on account retrieval:
     * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/docs/Accounts.md
     */
    const currentAccounts = myMSALObj.getAllAccounts();
    if (currentAccounts === null) {
      return;
    } else if (currentAccounts.length > 1) {
      // Add choose account code here
      console.warn("MsalAuthService >>> handleResponse >>> Multiple accounts detected.");
    } else if (currentAccounts.length === 0) {
      signIn();
    } else if (currentAccounts.length === 1) {
      username = currentAccounts[0].username;
    }
  }
}

function signIn() {
  myMSALObj.loginRedirect(loginRequest);
}

function getTokenRedirect(request) {
  /**
   * See here for more info on account retrieval:
   * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/docs/Accounts.md
   */
  request.account = myMSALObj.getAccountByUsername(username);
  return myMSALObj.acquireTokenSilent(request).catch(error => {
    console.warn("MsalAuthService >>> getTokenRedirect : Silent token acquisition fails. acquiring token using redirect");
    if (error instanceof Msal.InteractionRequiredAuthError) {
      // fallback to interaction when silent call fails
      return myMSALObj.acquireTokenRedirect(request);
    } else {
      console.warn("MsalAuthService >>> getTokenRedirect : " + error);
    }
  });
}

export function getAccessToken(): Promise<string> {
  return getTokenRedirect(loginRequest).then(response => {
    if (!response || !response.accessToken) {
      console.log("MsalAuthService >>> getAccessToken : Failed to get access token, no redirect response");
      return "";
    } else {
      return response.accessToken;
    }
  })
}


export function getIdTokenFromAzure(): Promise<string> {
  console.log("fong loginRequest --> ", loginRequest);
  return getTokenRedirect(loginRequest).then(response => {
    if (!response || !response.idToken) {
      console.log("MsalAuthService >>> getIdTokenFromAzure : Failed to get access token, no redirect response");
      return "";
    } else {
      return response.idToken;
    }
  })
}

export function getIdTokenFromAzureWithForceRefresh(): Promise<string> {
  return getTokenRedirect(tokenRequestForceRefresh).then(response => {
    if (!response || !response.idToken) {
      console.log("MsalAuthService >>> getIdTokenFromAzureWithForceRefresh : Failed to foreceFresh to get id token, no redirect response");
      return "";
    } else {
      return response.idToken;
    }
  })
}
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by fong1999** [comment]
Hi! I am refactoring our existing SPA application. I noticed that the place that we use Masl is at the class as an instance variable.

```
class MegaMenuView extends React.Component<
  RouteComponentProps<{}>,
  IMegaMenuState
> {

private tok: any = getIdTokenFromAzure();

......

export function getIdTokenFromAzure(): Promise<string> {
  return getTokenRedirect(loginRequest).then(response => {
    if (!response || !response.idToken) {
      console.log("MsalAuthService >>> getIdTokenFromAzure : Failed to get access token, no redirect response");
      return "";
    } else {
      return response.idToken;
    }
  })
}

function getTokenRedirect(request) {
  /**
   * See here for more info on account retrieval:
   * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/docs/Accounts.md
   */
  request.account = myMSALObj.getAccountByUsername(username);
  return myMSALObj.acquireTokenSilent(request).catch(error => {
    console.warn("MsalAuthService >>> getTokenRedirect : Silent token acquisition fails. acquiring token using redirect");
    if (error instanceof Msal.InteractionRequiredAuthError) {
      // fallback to interaction when silent call fails
      return myMSALObj.acquireTokenRedirect(request);
    } else {
      console.warn("MsalAuthService >>> getTokenRedirect : " + error);
    }
  });
}
```
However, this approach has a problem. We call it before an active account is set.  We are getting a warning as below.

```
MsalAuthService.ts:85 MsalAuthService >>> getTokenRedirect : BrowserAuthError: no_account_error: No account object provided to acquireTokenSilent and no active account has been set. Please call setActiveAccount or provide an account on the request.
```

To avoid this issue, at the same time, we can get the token. What is the right way doing it? 

Is there a way to get the token(s) from sessionStorage/localStorage by using sessionStorage.getItem() instead of calling `return myMSALObj.acquireTokenSilent(request)`? What is the best/good practice of doing it? 

We need to use the same token for another process in parallel with calling Graph API. We need to pass the same token to an Apigee authentication API get access token as an exchange to call that API via apigee...

Any suggestions? Thanks!

**Comment by sameerag** [comment]
@fong1999 Samples above are guidance on how a preferred pattern of usage should be for MSAL JS. The idea is that you first try to acquire tokens silently if you can (there are many conditions that cause this, your app may have a session with STS allowing for silent calls, there may be tokens in the cache from a previous call etc) and if it fails, then initiate an interactive call.

If there is no account, it is not a fatal error, it is just an indication to trigger interaction.

MSAL JS/React also support parallel silent calls i.e., once an interactive call is successful and all relevant consents are granted, you can then fetch the tokens silently in any fashion you want to.

> Is there a way to get the token(s) from sessionStorage/localStorage by using sessionStorage.getItem() instead of calling return myMSALObj.acquireTokenSilent(request)? What is the best/good practice of doing it?

If you already fetched tokens and they are not yet expired, that is when you can fetch them from the cache. Else you will have to initiate an interactive token call.

> We need to use the same token for another process in parallel with calling Graph API. We need to pass the same token to an Apigee authentication API get access token as an exchange to call that API via apigee...

I would advise to first establish a session with STS (which is a successful interactive call) and then you can make your parallel `acquireTokenSilent` calls to fetch the relevant tokens as needed.

Adding @derisen if he can add more guidance here.

Hope this helps.

**Comment by derisen** [comment]
@fong1999 please refer to [acquire-token.md](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/acquire-token.md) for best practices with token acquisition. Let us know if you still have questions or concerns.

**Comment by fong1999** [comment]
@derisen Hi Thanks for your response. I watched your youtube video. I posted my question regarding that on that here - https://github.com/derisen/msal-react-demo/issues/6

Could you please take a look at there? Thank you so much!

**Comment by derisen** [comment]
@fong1999 responded there. Feel free to close this if that answers your query.

**Comment by fong1999** [comment]
@derisen  Thank you for the info! Let me take a look. Thanks!

**Comment by fong1999** [comment]
@derisen  Let me check there. Thanks you so much!!
