### ISSUE TITLE
StringUtils: Cannot read properties of undefined (reading 'trim')

### ISSUE THREAD

**Issue by KieranSunshine** [AzureAD/microsoft-authentication-library-for-js#5812]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

11.0.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

2.34.0

### Public or Confidential Client?

Public

### Description

MSAL has been working fine previously, all of a sudden the browser is reporting Cannot read properties of undefined (reading 'trim').

I upgraded from 2.33.0 to 2.34.0 to see whether that would fix the issue but it did not. Clearing local storage hasn't helped either.

The stack trace points towards the StringUtils, trimArrayEntries method.

### Error Message

StringUtils.ts:93 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'trim')
    at StringUtils.ts:93:39
    at Array.map (<anonymous>)
    at StringUtils2.trimArrayEntries (StringUtils.ts:93:20)
    at new ScopeSet2 (ScopeSet.ts:22:52)
    at RequestParameterBuilder2.addScopes (RequestParameterBuilder.ts:70:26)
    at AuthorizationCodeClient2.<anonymous> (AuthorizationCodeClient.ts:357:26)
    at step (_tslib.js:75:23)
    at Object.next (_tslib.js:56:53)
    at _tslib.js:49:71
    at new Promise (<anonymous>)

### MSAL Configuration

```javascript
{
	auth: {
		clientId: import.meta.env.VITE_AUTH_CLIENT_ID,
		authority: `https://login.microsoftonline.com/${
			import.meta.env.VITE_AUTH_TENANT_ID
		}`,
		redirectUri: `${import.meta.env.VITE_AUTH_REDIRECT_URL}`,
		postLogoutRedirectUri: `${
			import.meta.env.VITE_AUTH_POST_LOGOUT_REDIRECT_URL
		}`,
	},
	cache: {
		cacheLocation: "localStorage",
	},
	system: {
		loggerOptions: {
			loggerCallback: (
				level: LogLevel,
				message: string,
				containsPii: boolean
			) => {
				if (containsPii) {
					return;
				}
				switch (level) {
					case LogLevel.Error:
						console.error(message);
						return;
					case LogLevel.Info:
						console.info(message);
						return;
					case LogLevel.Verbose:
						console.debug(message);
						return;
					case LogLevel.Warning:
						console.warn(message);
						return;
					default:
						return;
				}
			},
			logLevel: LogLevel.Verbose,
		},
	},
};
```

### Relevant Code Snippets

```javascript
Not applicable
```

### Reproduction Steps

1.Attempt to log in

### Expected Behavior

The library should redirect the user to MS login page.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge

### Source

External (Customer)

**Comment by KieranSunshine** [comment]
Closing as issue was down to misconfiguration on my end.

**Comment by scottlinddk** [comment]
@KieranSunshine I know it's a longshot but do you remember what your misconfiguration was? Facing the same issue and can't find a working solution.
