### ISSUE TITLE
How do I test the refresh_token token expiry flow?

### ISSUE THREAD

**Issue by pwoji** [AzureAD/microsoft-authentication-library-for-js#5813]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.30.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.4.5

### Public or Confidential Client?

Public

### Description

I'm trying to test application behavior when my refresh_token expires. The refresh token has an expiry of 1 day and is impractical to wait that long in order to test my flow. I can't set the expiry to less than 1 day due to b2c restrictions. Is there a way to force the expiration of this token so it triggers the flow to acquire a new refresh token?

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by konstantin-msft** [comment]
Hi @pwojee.
Please refer to the [token lifetime cache lookup policy](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/token-lifetimes.md#cache-lookup-policy). Setting `cacheLookupPolicy` to `CacheLookupPolicy.Skip` should do the trick. These [code snippets](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/token-lifetimes.md#code-snippets) might be helpful.

**Comment by davidwitten** [comment]
@pwojee Dumb question (and issue I'm running into). How are you getting a refresh token in the first place? 

Seems like there's no place in the frontend that returns it.
