### ISSUE TITLE
Why I get different ADB2C refresh token lifetime for apps in the same tennant?

### ISSUE THREAD

**Issue by miranc** [AzureAD/microsoft-authentication-library-for-js#5821]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.33.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.5.3

### Public or Confidential Client?

Public

### Description

I have two react SPA apps. Both use the same msal-react and msal-browser package versions for authentication. 
Both use the same sign-in flow and therefore have the same token configuration. 
One is deployed as an app service in Azure and the second one is deployed as an app on virtual machine IIS in Azure. App in app service gets refresh token that lasts 14 days (as configured in sign-in flow) and app deployed in Azure virtual machine gets refresh token valid only 24h. Authentication flow is the same. Each app has its own app registration, scopes and api resources are different but configured correctly. Besides custom scopes they both have Graph Api offline_access and openid scopes. 
What could be the reason that app published to IIS in virtual machine in Azure gets only 24h refresh token? Redirect URIs in app registration and authentication settings are different for both apps and set to return to the app itself. Both authentications work just that refresh token lifetimes are different, and that causes often login redirects for an app deployed to virtual machine IIS.
I have tried many suggested things like addin domain and login hints to silentLoginRequest and loginRedirectRequest but I always get kicked to login page after 24h.

### MSAL Configuration

```javascript
{
        auth: {
            clientId: clientID,
            redirectUri: redirectUri,
            knownAuthorities: XXXXXXXXXXXX,
            navigateToLoginRequestUrl: true
        },
        cache: {
            cacheLocation: BrowserCacheLocation.LocalStorage, 
            storeAuthStateInCookie: false, 
        },
    };
```

### Identity Provider

Azure B2C Basic Policy

### Source

External (Customer)

**Comment by hectormmg** [comment]
@miranc thanks for the question. This isn't directly related to either of the msal libraries, so it may be better to directly ask the B2C service team by opening a ticket [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options). Refresh tokens can be issued with different lifetimes depending on how securely they can be stored by the client. Single-page app refresh tokens are limited to 24 hours while other less vulnerable clients may have refresh token lifetimes up to 90 days.

**Comment by miranc** [comment]
@hectormmg Thanks for an answer I'll try contacting B2C service team as well. What confuses me is that both of these apps are SPA, and one is consistently getting refresh token that lasts 14 days and other only for 24h.
Question regarding msal libraries: 
I am never able to silently get new refresh-token, user is always sent to loginRedirect after 24h expiry. From what I read, refresh token should be renewed if there is active session in ADB2C identity provider, but what keeps this session active I don't know because I was never able to get new refresh-token without user interaction.

**Comment by hectormmg** [comment]
@miranc the refresh token can sometimes be renewed silently in cases like when the user is logged into the browser with the same account. However, in most cases the auth service will require interaction after the 24 hour RT has expired in SPAs.

As for the SPAs getting different token lifetimes, my assumption is that the azure app service has better security capabilities than the VM your second app is running in.

Please let me know if we can close this issue as answered!

**Comment by miranc** [comment]
Thanks @hectormmg , you can close this thread, I'll seek for an answer in different place ;)
