### ISSUE TITLE
Chromium 80 freezes / blocks for a few minutes after upgrading msal-browser and msal-common 

### ISSUE THREAD

**Issue by sladomic** [AzureAD/microsoft-authentication-library-for-js#5822]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.34.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

During login the app freezes / blocks for a few minutes without any errors / logs in Chromium 80. Chromium 95 and newer browsers all work fine (Chrome, Brave, Edge, Firefox, Safari).

### Error Message

None

Profiling shows however, that the app stops executing at https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/570ca651427b7f347b18aa20ae0e16c63862ea53/lib/msal-common/src/cache/entities/CredentialEntity.ts#L143.

### MSAL Configuration

```javascript
const azureActiveDirectoryClient = new PublicClientApplication({
  auth: {
    clientId: process.env.AZURE_ACTIVE_DIRECTORY_CLIENT_ID,
    authority: process.env.AZURE_ACTIVE_DIRECTORY_AUTHORITY,
    redirectUri: process.env.AZURE_ACTIVE_DIRECTORY_REDIRECT_URI,
  },
})
```

### Relevant Code Snippets

```javascript
https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/tree/main/1-Authentication/1-sign-in/SPA has the same issue in Chromium 80
```

### Reproduction Steps

1. Download Chromium 80 [Mac](https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Mac%2F722274%2Fchrome-mac.zip?generation=1575589468690598&alt=media) / [Windows](https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Win_x64%2F722274%2Fchrome-win.zip?generation=1575590120225705&alt=media)
2. Run example https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/tree/main/1-Authentication/1-sign-in/SPA
3. Try to login
4. Browser freezes / blocks

### Expected Behavior

No freezing / blocking of UI

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Regression

@azure/msal-browser: 2.32.3, @azure/msal-common: 9.1.1

### Source

External (Customer)

**Comment by sladomic** [comment]
Downgrading as in https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5548 helped to resolve the issue for now.

**Comment by tnorling** [comment]
We will have a new release going out on Monday which removes that regex lookup so please give it another try next week. Please also note that we only [officially support the latest 2 versions of Chrome](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md#what-browsers-are-supported-by-msaljs) and any issues specific to older versions are unlikely to be prioritized.

**Comment by sladomic** [comment]
Thanks @tnorling the issue seems to be resolved!
