### ISSUE TITLE
Embedded iframes get blocked by strict COEP policy

### ISSUE THREAD

**Issue by palexaki** [AzureAD/microsoft-authentication-library-for-js#5829]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.28.3

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.4.3

### Public or Confidential Client?

Public

### Description

When the refresh token expires msal-browser creates an iframe to retrieve an updated refresh token. This won't work when the parent document has its Cross-Origin-Embedder-Policy set to `require-corp`, because `login.microsoftonline.com` does not set its Cross-Origin-Resource-Policy header to `cross-origin` which means that the iframe is blocked by the browser. Is there a workaround for this? Or might it be possible for microsoft to set the CORP header, in that case we can use a stricter COEP header.

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by hectormmg** [comment]
@palexaki unfortunately MSAL has no control over the HTTP headers set by `login.microsoftonline.com` since those are controlled by the authorization service.

**Comment by palexaki** [comment]
Thanks for the answer, any suggestion on how to flag this issue further up the chain?

**Comment by jo-arroyo** [comment]
@palexaki Please open a ticket with [Azure Support](https://azure.microsoft.com/en-us/support/) for further help with this.

**Comment by simonjpartridge** [comment]
@palexaki did you figure out a resolution to this issue. I am having a similar problem

**Comment by Martin4R** [comment]
Having the same problem. Does anyone know a solution or workaround for this? I cannot find any documentation for this for Microsoft Entra.

**Comment by Martin4R** [comment]
Current status:
I contacted Azure Support as mentioned above. After a few weeks of routing my issue through the support to the correct team, the answer is:
> ... unfortunately this is an item that has been in the backlog since 2021. We will ask for it to be prioritized but there is no ETA so far.

On the other hand, it seems that the current implementations of site isolation open the gates for new attacks. So, not sure if it is really worth it to use site-isolation as it is right now.
