### ISSUE TITLE
Getting "interaction_in_progress" error even though inProgress returns 'none'

### ISSUE THREAD

**Issue by adriansalgadoa** [AzureAD/microsoft-authentication-library-for-js#5842]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.32.2

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.5.2

### Public or Confidential Client?

Public

### Description

I'm getting the error "interaction_in_progress" when testing locally, even though inProgress returns "none". Tested on Firefox and Microsoft Edge, both in normal and private modes and same thing happens.

### Error Message

![image](https://user-images.githubusercontent.com/3248837/229523804-554efdee-381c-49f5-8dca-b31091522126.png)

### Msal Logs

BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.  For more visit: aka.ms/msaljs/browser-errors.

### MSAL Configuration

```javascript
import {Configuration, RedirectRequest} from '@azure/msal-browser';

export const msalConfig: Configuration = {
  auth: {
    clientId: "c5d71fae-91cd-4ccc-adef-f274d5b77229"
    authority: "https://login.microsoftonline.com/bridgeit.dk",
    redirectUri: "localhost:4200"
  },
  cache: {
    cacheLocation: 'localStorage',
    storeAuthStateInCookie: true
  }
};

export const loginRequest: RedirectRequest = {
  scopes: ['https://bridgeit.dk/bmp/user_impersonation']
};
```

### Relevant Code Snippets

```javascript
Not sure what to share here, I'm doing

instance.loginRedirect(msalConfig)
```

### Reproduction Steps

Click on login button (which calls instance.loginRedirect(msalConfig))

### Expected Behavior

I expect it to redirect me to the microsoft auth login screen instead of returning an error

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari

### Source

External (Customer)

**Comment by adriansalgadoa** [comment]
I just found that, sometimes, there's a cookie `msal.interaction.status=undefined` that breaks everything. Fixed the issue by expiring it, but it does seem like a weird bug.

**Comment by tnorling** [comment]
You should turn off `storeAuthStateInCookie`. It's only needed for IE11

**Comment by lobaak** [comment]
I'm also seeing interaction_in_progress when inProgress is returning none. This seems to be an issue
