### ISSUE TITLE
After authenticating to Azure B2C using Mobile App is there a way to automatically sign into web app?

### ISSUE THREAD

**Issue by RangerDunadan** [AzureAD/microsoft-authentication-library-for-js#5844]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.18.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.4

### Public or Confidential Client?

Public

### Description

I have a web app and a mobile app.  Both of these apps authenticate independently to Azure B2C and I can communicate with the backend APIs securely and without a problem. 

I want to add functionality to the mobile app that allows a user to click a row and go to the web app.  When the user launched the mobile app they were required to login (which works perfectly).  However, when the user clicks the row and the web app is launched inside the Mobile apps native browser the user is required to log into the web app.  

The mobile app and web app use the tenant id and client id configuration inside the Azure B2C.  They also use the same username and passwords --- just a different mechanism for using the app.  After I have logged into the mobile app I have access to the access token, id token, and refresh token.  Can I use these pieces of information to authenticate to the web app to prevent the web app from asking the user to login again?  

Or is there another way so that once I'm logged into the mobile app that I can automatically log the user into the web app?

### MSAL Configuration

```javascript
{
    "msal": {
      "auth": {
        "clientId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx",
        "authority": "https://xxxxxx-xxxxx.xxxxxxxxx.com/xxxxxxxxxxxxxxB2C.onmicrosoft.com/B2C_1A_signup_signin_saml_staging",
        "knownAuthorities": ["xxxxxx-xxxxx.xxxxxxxxx.com"],
        "redirectUri": "http://localhost:4200/",
        "postLogoutRedirectUri": "https://xxxxxxx.xxxxxxxx.com/simplesaml/module.php/core/authenticate.php?as=sso-auth&logout&redirectUrl=http://localhost:4200",
        "navigateToLoginRequestUrl": false
      },
      "cache": {
        "cacheLocation": "localStorage"
      }
    },
    "guard": {
      "interactionType": "redirect",
      "authRequest": {
        "scopes": ["openid profile email offline_access"]
      }
    },
    "interceptor": {
      "interactionType": "redirect",
      "protectedResourceMap": [
        ["http://localhost/xxxxxxxxxxxx/*", ["https://xxxxxxxxxxxxxxB2C.onmicrosoft.com/xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/xxxxxxx.all"]],
        ["https://graph.microsoft.com/v1.0/me", ["user.read"]]
      ]
    },
    "publicInterceptor": {
      "interactionType": "redirect",
      "protectedResourceMap": [
        ["http://localhost/xxxxxxxxxxxx/API/Public**", null],
        ["http://localhost/xxxxxxxxxxxx/API/Portal**", ["https://DiocesanCaminoB2C.onmicrosoft.com/xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/camino.all"]],
        ["https://graph.microsoft.com/v1.0/me", ["user.read"]]
      ]
    }
  }
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by hectormmg** [comment]
@RangerDunadan please look at our [ssoSilent documentation](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/login-user.md#silent-login-with-ssosilent), it may help with what you're trying to achieve. Let us know if it helps!
