### ISSUE TITLE
Switch accounts with loginPopup without select_account prompt

### ISSUE THREAD

**Issue by xinyi-joffre** [AzureAD/microsoft-authentication-library-for-js#5858]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.34.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

We are trying to implement account switching behavior, so that when we click on a different account in a list of accounts, the active account is changed.

It seems like if we pass loginHint and domainHint to loginPopup, it always disregards it if there's already an account signed in and it will return the existing account as the AuthenticationResult.

As an example:
- Currently logged in user: aad@microsoft.com
- User clicks another remembered account to swap to: msa@gmail.com
  - We trigger `loginPopup({loginHint: 'msa@gmail.com', domainHint: '9188040d-6c67-4c5b-b112-36a304b66dad'})`
- AuthenticationResult still comes back as aad@microsoft.com

The only workaround seems to be to pass `prompt: select_account` in the PopupRequest options, but this forces the user to click on the account they want for a second time. Is there a way to tell loginPopup to swap accounts without forcing the user to click again?

### MSAL Configuration

```javascript
{
    "auth": {
        "clientId": "<clientId>",
        "authority": "https://login.microsoftonline.com/common/",
        "redirectUri": "http://localhost:8080",
        "navigateToLoginRequestUrl": true,
        "postLogoutRedirectUri": "http://localhost:8080"
    },
    "cache": {
        "cacheLocation": "localStorage"
    }
}
```

### Relevant Code Snippets

```javascript
public signInTo = async (args: any) => {
        const popupRequest = {
            loginHint: args.nextAccount.memberName,
            domainHint: args.nextAccount.tenantId,
            // prompt: "select_account", // This works but forces user to click the account they want again
            scopes: ["openid", "profile", "User.Read"]
        };

        const msalAuthResponse = await this.msalInstance.loginPopup(popupRequest);
        if (msalAuthResponse.account) { // This is coming back with original account
            this.setCurrentAccount(msalAuthResponse.account);
        }
    };
```

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by jo-arroyo** [comment]
@xinyi-joffre To clarify, is the second account the user trying to switch to already logged in? Or are they logged into one account and trying to log into another?

**Comment by xinyi-joffre** [comment]
Hi @jo-arroyo , thanks for the response! For screenshot above, the second account is already logged in, but the remembered accounts feature for standard Microsoft MeControl will also show remembered accounts that are not logged in. So, it could be either case (logged in or just remembered)

**Comment by jo-arroyo** [comment]
@xinyi-joffre Please take a look at our [FAQ regarding logged in accounts](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md#how-can-i-switch-between-multiple-logged-in-users) as well as the [accounts documentation](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/accounts.md#active-account-apis) and see if these account APIs work in your scenario.

**Comment by xinyi-joffre** [comment]
Thank you, we tried just using this logic:
```
public signInTo = async (args: any) => {
        const switchedAccount = this.msalInstance.getAccountByUsername(args.nextAccount.memberName);
        if (switchedAccount) {
          this.msalInstance.setActiveAccount(account);
        }
        else {
            // Fallback to select_account, if we cannot find the indicated account
            this.signIn({ prompt: 'select_account' });
        }
    };
```
But the behavior is a bit odd, since it behaves differently than logins, and we cannot use events across tabs to sync accounts, since there are only events for "ACCOUNT_ADDED" and "ACCOUNT_REMOVED" but not for "ACCOUNT_SWITCHED." We also wonder if the logic above is too loose, since it doesn't do any validation (only does client side swapping of a storage cache value for current account).

**Comment by lalimasharda** [comment]
Hey @xinyi-joffre,
Can you try something like this:

`const switchedAccount = this.msalInstance.getAccountByUsername(args.nextAccount.memberName);`

`const msalAuthResponse = await this.msalInstance.loginPopup({`
`       ...popupRequest,`
`       account: switchedAccount` 
`});`

And then make sure you are doing setActiveAccount(msalAuthResponse.account) ?

Does it still not work as expected?

**Comment by xinyi-joffre** [comment]
@lalimasharda , yes, we tried that way as well, but the msalAuthResponse coming back is always the original account, so when we say setActiveAccount, it's the wrong account (not the one we want to switch to).

**Comment by sameerag** [comment]
@xinyi-joffre This seems to be more of a server behavior pattern - the B2C service is not picking up the session you intended to. Can you please raise an issue with the Service team, instructions are [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md#what-should-i-do-if-i-believe-my-issue-is-with-the-b2c-service-itself-rather-than-with-the-library).
