### ISSUE TITLE
Provide a way to configure AAD_INSTANCE_DISCOVERY_ENDPT

### ISSUE THREAD

**Issue by fhljys** [AzureAD/microsoft-authentication-library-for-js#5861]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

Not Applicable

### Public or Confidential Client?

Public

### Description

Right now, the default endpoint is https://login.microsoftonline.com/common/discovery/instance?api-version=1.1&authorization_endpoint=
It works perfectly for public cloud customers. 
But it might cause issues for non-public cloud customers as they want to block all the .com website. 

Can we provide a way to customize this value when creating the MSAL instance? 

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
@fhljys You will need to provide the metadata by following the instructions [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/docs/performance.md#bypass-cloud-instance-discovery-resolution) in environments where the discovery url is not available.

**Comment by fhljys** [comment]
Hi @tnorling , I understand that we can provide the metadata. But I feel provide a way to config the endpoint is more flexiable. What's your opinion?

**Comment by tnorling** [comment]
We intentionally do not expose a way to provide an arbitrary endpoint for security reasons. Providing the metadata statically is the recommended practice if you need to support environments where the discovery endpoint is not available.
