### ISSUE TITLE
"You'll need a new app to open this about link" message when using acquireTokenPopup() in Teams desktop app

### ISSUE THREAD

**Issue by FE-POLY** [AzureAD/microsoft-authentication-library-for-js#5879]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.35.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.5.5

### Public or Confidential Client?

Public

### Description

Hello everyone,

I'm currently using the `acquireTokenPopup()` method from `@azure/msal-react` to authenticate users in my Teams custom app. If used inside a browser, everything works fine. But if I try to test it inside the Teams desktop application, I get a Microsoft "You'll need a new app to open this about link" popup.

### MSAL Configuration

```javascript
{
  auth: {
    clientId: <myAppId>,
  },
}
```

### Relevant Code Snippets

```javascript
export const ssoAuthInsideTeams = async (
  instance: IPublicClientApplication,
  history: any,
  enqueueSnackbar: EnqueueSnackbar
): Promise<void> => {
  await instance
    .acquireTokenPopup({
      scopes: [],
      redirectUri: `${window.location.origin}/api/login/openid/cb`,
    })
    .then((response) => {
      post("/api/auth/login/openid/cb", {
        id_token: response.idToken,
      })
        .then((response) => {
          const typedResponse: any = response.response;
          const urlToRedirect: string = "/" + typedResponse.hash;
          history.push(urlToRedirect);
        })
        .catch((reason) => {
          // eslint-disable-next-line no-console
          console.error("Failed to authenticate : ", reason);
        });
    })
    .catch((reason) => {
      // eslint-disable-next-line no-console
      console.error("Failed to authenticate : ", reason);
    });
};
```

### Reproduction Steps

1. Use the code snippet above to authenticate users
2. try it inside Teams desktop application

### Expected Behavior

Authentication process is the same as in Teams browser version : user has a Azure SSO popup appearing and, after he authenticate, he's redirected to the home page of the custom app.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Other

### Source

External (Customer)

**Comment by tnorling** [comment]
Can you try setting the `asyncPopups` flag to true? More info [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/configuration.md#system-config-options)

**Comment by FE-POLY** [comment]
Hello @tnorling and thank you for your answer. Setting `asyncPopups` to true as indeed removed the "You'll need a new app to open this about link" popup but the intended popup window does not open. Instead, user is redirected from Teams desktop app to a browser window where a "cannot get < myUrl >" message is displayed.

**Comment by tnorling** [comment]
I see, you may need to use the Teams SDK to open a popup and use the redirect flow inside that popup. We have a sample demonstrating Teams integration [here](https://github.com/pnp/teams-dev-samples/tree/main/samples/tab-sso/src/nodejs), please give that a look
