### ISSUE TITLE
Cannot navigate "Back" in Login Redirect

### ISSUE THREAD

**Issue by zamzowd** [AzureAD/microsoft-authentication-library-for-js#588]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
When `loginRedirect` is called, the browser navigation is handled with `window.location.replace(urlNavigate)`.  This means an entry is not added to the browser "Back" history.  If a user clicks a "Sign In" button to trigger the `loginRedirect`, but then has a change of heart when faced with the login page, there is no way for the user to navigate back to the application.

## Desired behavior
Use `window.location.assign(urlNavigate)` instead of `window.location.replace(urlNavigate)`.  This results in an entry added to the browser "Back" history.  When the user gets taken to the login page, the user can use the "Back" button to return to the application.

## References
https://developer.mozilla.org/en-US/docs/Web/API/Location/replace

https://developer.mozilla.org/en-US/docs/Web/API/Location/assign

**Comment by emilpalsson** [comment]
I agree. `location.replace` leads to annoying user experience.
We've done a silly workaround for this:
```
window.history.pushState({ login: true }, '')
userAgentApplication.loginRedirect(...)
```
This way, msal replaces our faked history item instead of the current one, which allows for proper back navigation.

**Comment by sameerag** [comment]
Closing this as the latest msal release `msal 1.2.0-beta.2` has this fix.
