### ISSUE TITLE
Infinite routing loop when returning from AzureAD policy page (EditProfile, ForgotUsername, etc...)

### ISSUE THREAD

**Issue by doug-williamson** [AzureAD/microsoft-authentication-library-for-js#5887]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

^2.28.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.4.1

### Public or Confidential Client?

Public

### Description

[Angular14B2CApp_03202023.zip](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/11226171/Angular14B2CApp_03202023.zip)

My Angular/MSAL configuration is causing an infinite redirect loop. When authenticated, and in my HomeComponent, I can click "Edit Profile" and am routed to '/edit-profile', which then navigates me to the EditProfile IDaaS policy. After completing the policy, I'm routed back to my app's base route ('/') and then am auto-navigated back to the '/edit-profile' route, causing a loop. It looks like something relating to @azure/msal-browser.

The expected behavior is to stay at the base route '/' after coming back from IDaaS.

I'm noticing this behavior on completing any policy pages (anonymously or authenticated).

### MSAL Configuration

```javascript
{
    auth: {
      clientId: environment.msalConfig.auth.clientId,
      authority: environment.b2cPolicies.authorities.signIn.authority,
      redirectUri: '/',
      postLogoutRedirectUri: '/',
      knownAuthorities: [environment.b2cPolicies.authorityDomain]
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE, // set to true for IE 11
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Verbose,
        piiLoggingEnabled: false
      }
    },
  }
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by tnorling** [comment]
Please set the [`navigateToLoginRequestUrl` configuration option](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/configuration.md#auth-config-options) to `false`

**Comment by doug-williamson** [comment]
Thank you!
