### ISSUE TITLE
writing to persistence triggers Kaspersky trojan detection

### ISSUE THREAD

**Issue by juxnpxblo** [AzureAD/microsoft-authentication-library-for-js#5888]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

1.14.6

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

1.0.0-alpha.32

### Public or Confidential Client?

Public

### Description

after a succesful login using the library, right after the cache file is written, Kaspersky detects the application (electron based) as a **PDM:Trojan.Win32.Generic** by **Behavior analysis** and it's removed from the system

I can confirm that the cache file is successfully created and can be read from (if I then reinstall the application, it can read from the cache file in the temp folder and runs fine) but something that occurs in the process of writing to the persistence file makes Kaspersky to detect it as a trojan (it's just them, the bug couldn't be reproduced testing against 3 other AVs)

already tried to save cache file to temp folder **app.getPath('userData')** and execution path **path.dirname(process.execPath)**, same thing occurs in both

I am using Windows 11

### MSAL Configuration

```javascript
const persistenceConfiguration = {
  cachePath,
  dataProtectionScope: DataProtectionScope.CurrentUser,
  serviceName: APP_NAME,
  accountName: APP_NAME,
  usePlaintextFileOnLinux: false,
};

const config: MsalElectronConfig = {
  clientId: CLIENT_ID,
  mainWindow: mainWindow,
  scopes: SCOPES,
  cachePlugin: new PersistenceCachePlugin(persistence),
};
```

### Relevant Code Snippets

```javascript
.
```

### Reproduction Steps

1. try to write to persistence with Kaspersky running on Windows 11

### Expected Behavior

Kaspersky doesn't detect it as a trojan

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Other

### Source

External (Customer)

**Comment by tnorling** [comment]
This is an issue you should take up with Kaspersky. We don't have any visibility into what they're looking for or why they might flag this. My sincerest apologies!
