### ISSUE TITLE
Get updated claims from idToken after refresh

### ISSUE THREAD

**Issue by mikebper** [AzureAD/microsoft-authentication-library-for-js#5894]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.31.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.4.6

### Public or Confidential Client?

Public

### Description

I am getting new tokens using the refresh token, and I see the new tokens in the response, but msalService.instance.getActiveAccount()?.idTokenClaims continues to show the claims from the old token, and the tokens in sessionStorage are still the old ones, not the new ones returned in the response from the refresh. Calls made to the API, however, do use the new access token. How do I use/consume the updated claims from the refreshed idToken in the client-side app?

### MSAL Configuration

```javascript
app.module.ts:
MsalModule.forRoot(new PublicClientApplication(msalConfig),
    {
      interactionType: InteractionType.Redirect,
      authRequest: {
        scopes: protectedResource.authRequest.scopes,
        redirectUri: '/'
      }
    },
    {
      interactionType: InteractionType.Redirect,
      protectedResourceMap: new Map([
        [protectedResource.myApiEndpoint.endpoint, protectedResource.myApiEndpoint.scopes],
      ])
    })
],
providers: [    
  {
    provide: HTTP_INTERCEPTORS,
    useClass: MsalInterceptor,
    multi: true
  },
  MsalGuard
],
bootstrap: [
  AppComponent,
  MsalRedirectComponent
]

auth-config.ts:
import { LogLevel, Configuration, BrowserCacheLocation } from '@azure/msal-browser';
import { environment } from 'src/environments/environment';

export const b2cPolicies = {
    authorities: {
        signIn: {
            authority: 'https://myapib2cdev.b2clogin.com/myapib2cdev.onmicrosoft.com/B2C_1A_SIGNIN',
        },
        resetPassword: {
            authority: 'https://myapib2cdev.b2clogin.com/myapib2cdev.onmicrosoft.com/B2C_1A_PASSWORDRESET',
        },
        editProfile: {
            authority: 'https://myapib2cdev.b2clogin.com/myapib2cdev.onmicrosoft.com/B2C_1A_PROFILEEDIT'
        }
    },
    authorityDomain: 'myapib2cdev.b2clogin.com'
};

export const msalConfig: Configuration = {
    auth: {
        clientId: 'my-client-ID',
        authority: b2cPolicies.authorities.signIn.authority,
        knownAuthorities: [b2cPolicies.authorityDomain],
        redirectUri: '/',
        postLogoutRedirectUri: '/'
    },
    cache: {
        cacheLocation: BrowserCacheLocation.SessionStorage
    },
    system: {
        loggerOptions: {
            logLevel: LogLevel.Error,
            loggerCallback: (level, message, containsPii) => {
                if (containsPii) {
                    return;
                }
                switch (level) {
                    case LogLevel.Error:
                        console.error(message);
                        return;
                    case LogLevel.Info:
                        console.info(message);
                        return;
                    case LogLevel.Verbose:
                        console.debug(message);
                        return;
                    case LogLevel.Warning:
                        console.warn(message);
                        return;
                }
            },
            piiLoggingEnabled: false
        }
    }
}

export const protectedResource = {
    authRequest: {
        scopes: ['https://myapib2cdev.onmicrosoft.com/myapi/Read']
    },
    myApiEndpoint: {
        endpoint: `${environment.myApiBaseUrl}/myApiEndpoint`,
        scopes: ['https://myapib2cdev.onmicrosoft.com/myapi/Read']
    },
}
```

### Relevant Code Snippets

```javascript
// After acquiring a new token using the refresh token, the idTokenClaims on this.activeAccount or
// this.msalService.instance.getActiveAccount()?.idTokenClaims are still those from the old token despite
// the new token with different claims having been returned in the response to the refresh token request.

app.component.ts:

  constructor(private msalService: MsalService, private msalBroadcastService: MsalBroadcastService, ) {}

  activeAccount: AccountInfo | null = null;
  isAuthenticated: boolean = false;

  ngOnInit(): void {
    this.msalBroadcaseServiceSubscription = this.msalBroadcastService.inProgress$
    .pipe(
      filter((status: InteractionStatus) => status === InteractionStatus.None)
    )
    .subscribe(() => {
      if (!this.activeAccount) {
        let accounts = this.msalService.instance.getAllAccounts();
        if (accounts.length > 0) {
          this.activeAccount = accounts[0];
          this.msalService.instance.setActiveAccount(this.activeAccount);
          this.initialize();
        } else {
          this.activeAccount = null;
          this.isAuthenticated = false;
        }
      }
    });
  }

  logIn(): void {
    let popupRequest = {
      scopes: protectedResource.authRequest.scopes,
      redirectUri: '/assets/html/blank.html'
    } as PopupRequest;
    
    firstValueFrom(this.msalService.loginPopup(popupRequest)).then((response: AuthenticationResult) => {
      this.activeAccount = response.account;
      this.msalService.instance.setActiveAccount(this.authService.activeAccount);
    });
  }
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by tnorling** [comment]
Can you please share trace level logs? Can you also please share your usage where you're refreshing the token and where you're attempting to read the claims?

**Comment by mikebper** [comment]
Sure, here are the trace logs.
[trace-logs.txt](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/11237106/trace-logs.txt)

**Comment by mikebper** [comment]
Below is an example of the usage, however I changed given name in the directory and don't seem to be getting the updated value yet in my refreshed ID token. I'm guessing the provider has the old value cached, and I'll get the new value shortly. I add claims to the tokens via a REST API call, and I'm able to see those values update in the token response but not reflect in the MSAL account idClaims collection immediately.

  async ngOnInit(): Promise<void> {
    this.msalBroadcaseServiceSubscription = this.msalBroadcastService.inProgress$
    .pipe(
      filter((status: InteractionStatus) => status === InteractionStatus.None)
    )
    .subscribe(() => {
        let accounts = this.msalService.instance.getAllAccounts();
        if (accounts.length > 0) {
          this.account = accounts[0];
          this.msalService.instance.setActiveAccount(this.account);
        } else {
          this.account = undefined;
        }
    });
  }

  showClaims() {
    alert(this.account?.idTokenClaims!['given_name']);
  }

**Comment by mikebper** [comment]
Actually I do get the updated given_name immediately in my refreshed ID token. I had accidentally changed the given name on a different account. So the above example demonstrates what I'm seeing. Are the claims on the AccountInfo object supposed to be updated from the refresh token response?

**Comment by mikebper** [comment]
The code in that subscription callback for InteractionStatus.None is never even called (breakpoint doesn't get hit) when the refresh happens. I tried subscribing to InteractionStatus.SsoSilent and AcquireToken as well, and those don't seem to be called when the refresh happens either.

**Comment by tnorling** [comment]
Nope, because silent calls aren't interactive ;) Can you try this instead?

```
showClaims() {
alert(this.msalService.getActiveAccount()?.idTokenClaims!['given_name']);
}
```

**Comment by mikebper** [comment]
Yeah, that works. I was trying to avoid using getActiveAccount(), because I saw it mentioned to only do that if you subscribe and filter on interactionstatus none, and I don't want to resubscribe everywhere that I want to access a claim, when I should already know what they are from when the user logged in, or when the token was refreshed.

**Comment by mikebper** [comment]
Am I supposed to do this? Or is it safe to use getActiveAccount() any time?

  showClaims() {
    this.msalBroadcaseServiceSubscription = this.msalBroadcastService.inProgress$
    .pipe(
      filter((status: InteractionStatus) => status === InteractionStatus.None)
    )
    .subscribe(() => {
      alert(this.msalService.instance.getActiveAccount()?.idTokenClaims!['given_name']);
    });
  }

**Comment by tnorling** [comment]
It's safe. Though I would make sure this gets re-run each time a token call completes in case the values have changed.

Generally speaking, you should subscribe and verify the interaction status anytime you want to call a login or acquireToken API. Account APIs are generally safe to call whenever. The one caveat is that if a login or token call _is_ in progress when you call an account API you may get data that is about to be stale.

**Comment by mikebper** [comment]
OK, that's good information, and the problem is resolved. Thanks so much for your help, have a great weekend!

**Comment by mikebper** [comment]
Is there a way I can hook onto the refresh token event so that I can update UI elements based on changes in claims?

**Comment by tnorling** [comment]
You can subscribe to the `LOGIN_SUCCESS` and `ACQUIRE_TOKEN_SUCCESS` events. Docs for the event API [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/events.md#consuming-events-in-your-app)

**Comment by mikebper** [comment]
Got it, thanks!

**Comment by mikebper** [comment]
I'm still struggling with these claims. I get updates from token refreshes in my app.component.ts for given_name and that works great. I have another component, though, which also needs to use the new claims from the refresh token, and it's not getting them, even though I do see them in the refresh token response when I decode it on jwt.ms. And I do also see them on the object in app.module.ts. Is it not proper to inject MsalService in multiple components?

app.module.ts - I see all of the new post-refresh token claims here
```javascript
  ngOnInit(): void {
    this.msalBroadcastService.msalSubject$
      .pipe(
        filter((msg: EventMessage) => msg.eventType === EventType.ACQUIRE_TOKEN_SUCCESS)
      )
      .subscribe((result: EventMessage) => {
        const payload = result.payload as { account: AccountInfo };

        if (payload.account) {
          this.updateUiForAccount(payload.account)
        }
      });

    this.msalBroadcaseServiceSubscription = this.msalBroadcastService.inProgress$
      .pipe(
        filter((status: InteractionStatus) => status === InteractionStatus.None)
      )
      .subscribe(() => {
        let activeAccount = this.msalService.instance.getActiveAccount();
        if (!activeAccount) {
          let accounts = this.msalService.instance.getAllAccounts();
          if (accounts.length > 0) {
            activeAccount = accounts[0];
            this.msalService.instance.setActiveAccount(activeAccount);
            this.setLoginDisplay(activeAccount);
          }
        } else {
          this.setLoginDisplay(activeAccount);
        }
      });
  }

  setLoginDisplay(activeAccount: AccountInfo): void {
    this.isAuthenticated = true;
    this.updateUiForAccount(activeAccount);
  }

  updateUiForAccount(activeAccount: AccountInfo) {
    this.displayName = `${activeAccount.idTokenClaims!['given_name']} ${activeAccount.idTokenClaims!['family_name']}`;
  }

  logIn(): void {
    let popupRequest = {
      scopes: protectedResource.authRequest.scopes,
      redirectUri: '/assets/html/blank.html'
    } as PopupRequest;

    firstValueFrom(this.msalService.loginPopup(popupRequest)).then((response: AuthenticationResult) => {
      this.msalService.instance.setActiveAccount(response.account);
    });
  }

  logOut(): void {
    this.msalService.logoutRedirect({
      postLogoutRedirectUri: msalConfig.auth.postLogoutRedirectUri
    });
  }
``` 

other-component.ts - renders as a view in router-outlet on app.component - I don't see the new post-refresh token claims here
```javascript
  constructor(private msalService: MsalService, private http: HttpClient) { }

  public async getData(): Promise<Data | undefined> {
    let claims = this.msalService.instance.getActiveAccount()?.idTokenClaims;
```

**Comment by mikebper** [comment]
You mentioned "silent calls aren't interactive", I believe in reference to why InteractionStatus.None isn't broadcast, but there is an "InteractionType.Silent" that does get broadcast, which by that logic I'd think InteractionStatus.None would also occur once the silent interaction completes. It's so confusing how to structure this right such that the page loads properly without performing logic twice, and updates properly in response to token refreshes. And that's separate from the problem of my other component not seeing the updated claims when it calls getActiveAccount().

```javascript
this.msalBroadcastService.msalSubject$
.pipe(
  filter((msg: EventMessage) => msg.interactionType === InteractionType.Silent)
)
```

**Comment by mikebper** [comment]
I worked around the issue by only using MsalService in app.component and maintaining the AccountInfo instance on my own singleton service, which I share with the other component and access the account through it. It seems like a bug to me, though, that MsalService when injected into different components in the same Module returns stale data from getActiveAccount() in the child component.

I do have another issue where the following occurs:

1. My tokens are refreshed by aquireTokenSilent using the refresh token, which happens at the first request for a protected resource that is less than 5 minutes from the id/access token expirations.
2. I get new ID, access, and refresh tokens which all look good. The ID and access tokens have full lifetimes, and the refresh token lifetime is the remainder of the day (1440 minutes) from login.
3. After the first time the tokens are refreshed, EVERY subsequent request for a protected resource results in a call to the token endpoint to refresh the tokens again, even though it is not less than 5 minutes from the previously acquired tokens' expirations.

I tried using both BrowserCacheLocation.SessionStorage and BrowserCacheLocation.LocalStorage and the same thing happens with both. I've been testing with my token lifetimes set to 5 minutes and 20 seconds, so that they refresh every 20 seconds. I changed that to 10 minutes so that the first refresh doesn't occur for 5 minutes, and the same problem occurs. I've done this in multiple browsers with cleared cache.

I think the issue may be related to me not seeing the tokens update in storage when I check in the browsers' dev tools, despite the updated ID token reflecting in the active account's idTokenClaims, and the updated access token being the one added by MSAL to protected resource requests.

Should I open a separate issue for this?

**Comment by tnorling** [comment]
> It seems like a bug to me, though, that MsalService when injected into different components in the same Module returns stale data from getActiveAccount() in the child component.

getActiveAccount just does a cache lookup from local/session storage. If it's returning stale data it means it was called before the data was updated. I would try to debug the order in which things are invoked/completed to determine what's happening here.

> Should I open a separate issue for this?

Yes please do.

**Comment by mikebper** [comment]
> > It seems like a bug to me, though, that MsalService when injected into different components in the same Module returns stale data from getActiveAccount() in the child component.
> 
> getActiveAccount just does a cache lookup from local/session storage. If it's returning stale data it means it was called before the data was updated. I would try to debug the order in which things are invoked/completed to determine what's happening here.
> 
> > Should I open a separate issue for this?
> 
> Yes please do.

I opened a separate issue regarding the tokens refreshing every time after the first time it refreshes for social login AAD users.

Regarding getActiveAccount returning stale data, I don't believe it's related to the order things are happening. That could be the case for the first time that code is run if the token/AccountInfo are being updated after getActiveAccount was called, but I'd expect it to at least be updated on subsequent executions. However, it's always stale no matter how many times I call it, long after the tokens have been refreshed. But only in that one component. The MsalService in my app.component does get the correct data. I worked around it by storing the current AccountInfo instance, which I get from my app.component's MsalService, in a variable on my own singleton service, and accessing it from there in my other component.

**Comment by mattcheah** [comment]
@mikebper Any updates with the stale data issues? Running into similar issues myself and I wanted to see if you found any fixes.

**Comment by mikebper** [comment]
No updates from me. I worked around it by storing the AccountInfo instance in a variable on my own service, and then I inject that service into the other component(s) that I need to use it from. And I update the AccountInfo via a subscription to MsalBroadcastService whenever the token refreshes. That worked for me. Sample code below, but I don't know if this is an advisable way to do it. I think that the recommended way is to inject MsalService in the other component(s) and call GetActiveAccount, but that wasn't working for me.

I actually ended up refactoring out the need for the claims in the other component altogether. They were being used to compose some query string parameters for an API request, which the API then also verified were allowed. But I changed my design to instead not use the query string at all (it was redundant) and just use the data from the token API-side, which is a better design anyway.

app.component.ts:
```typescript
  ngOnInit(): void {
    this.msalBroadcastService.msalSubject$
    .pipe(
      filter((msg: EventMessage) => {
        if (msg.eventType === EventType.ACQUIRE_TOKEN_SUCCESS) {
          const payload = msg.payload as AuthenticationResult;
          return !payload.fromCache;
        } else {
          return false;
        }
      }),
      takeUntil(this.destroying)
    )
    .subscribe((result: EventMessage) => {
      const payload = result.payload as { account: AccountInfo };
      this.updateAccount(payload.account)
    });

  this.msalBroadcastService.inProgress$
    .pipe(
      filter((status: InteractionStatus) => status === InteractionStatus.None),
      takeUntil(this.destroying)
    )
    .subscribe(() => {
      let activeAccount = this.msalService.instance.getActiveAccount();
      if (!activeAccount) {
        let accounts = this.msalService.instance.getAllAccounts();
        if (accounts.length > 0) {
          activeAccount = accounts[0];
          this.msalService.instance.setActiveAccount(activeAccount);
          this.setLoginDisplay(activeAccount);
        }
      } else {
        this.setLoginDisplay(activeAccount);
      }
    });
  }

  setLoginDisplay(activeAccount: AccountInfo): void {
    this.updateAccount(activeAccount);
    // Optionally update the UI based on the user now being logged in here
  }

  updateAccount(activeAccount: AccountInfo) {
    this.authService.account = activeAccount;
    // Optionally set any component-level properties based on claims here
  }
```

auth.service.ts
```typescript
@Injectable({ providedIn: 'root' })
export class AuthService {
  account: AccountInfo | null = null;

  // Optionally put other security related methods here
}
```

**Comment by mikebper** [comment]
Now that I think about it again, it's possible the issue was happening for me because I had the token set to refresh after 2 minutes (for testing), and the refreshed token wasn't being cached due to a missing tid (tenant ID) on the token (if you turn MSAL logging on you can see messages indicating as such in the console). I since resolved that, though, so I bet GetActiveAccount would work in other components for me now.

**Comment by mattcheah** [comment]
Thanks for the insight - I haven't been able to get refreshed claims immediately after changing them no matter where it is in my app - I've just had to retry `ssoSilent()` until it responds with the updated claims ~ 10-20 seconds after a change was made by GraphAPI. Not the best user experience, so I've been looking for a workaround.
