### ISSUE TITLE
Login Redirect won't work on Safari when used inside a task pane in MS Word Add-in (deployed on a server)

### ISSUE THREAD

**Issue by edgarsenrarocha** [AzureAD/microsoft-authentication-library-for-js#5898]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.35.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.5.5

### Public or Confidential Client?

Public

### Description

The **loginRedirect** function doesn't redirect to AzureADB2C when used inside a dialog in Word Add-in on Mac.

**The sample followed:** https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular-b2c-sample-app

**The project that can be used to reproduce:** https://github.com/edgarsenrarocha/msal-word-add-in-safari-test

### Error Message

No message error is presented

### Msal Logs

[Log] [Mon, 17 Apr 2023 04:28:30 GMT] : @azure/msal-browser@2.35.0 : Verbose - getAllAccounts called (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:30 GMT] : @azure/msal-browser@2.35.0 : Trace - BrowserCacheManager.getAccountKeys called (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:30 GMT] : @azure/msal-browser@2.35.0 : Verbose - BrowserCacheManager.getAccountKeys - No account keys found (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:30 GMT] : @azure/msal-browser@2.35.0 : Info - Emitting event: msal:handleRedirectStart (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:30 GMT] : @azure/msal-browser@2.35.0 : Verbose - Emitting event to callback ca25b1f0-cd35-43ad-8314-702f8143d9aa: msal:handleRedirectStart (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:30 GMT] : @azure/msal-angular@2.5.5 : Verbose - BroadcastService - msal:handleRedirectStart results in setting inProgress from startup to handleRedirect (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:30 GMT] : @azure/msal-browser@2.35.0 : Verbose - handleRedirectPromise has been called for the first time, storing the promise (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:30 GMT] : @azure/msal-browser@2.35.0 : Trace - BrowserCacheManager.getCachedNativeRequest called (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:30 GMT] : @azure/msal-browser@2.35.0 : Trace - BrowserCacheManager.getTemporaryCache: No cache item found in local storage (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:30 GMT] : @azure/msal-browser@2.35.0 : Trace - BrowserCacheManager.getCachedNativeRequest: No cached native request found (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:30 GMT] : @azure/msal-browser@2.35.0 : Trace - handleRedirectPromise - acquiring token from web flow (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:30 GMT] : @azure/msal-browser@2.35.0 : Trace - BrowserCacheManager.getTemporaryCache: No cache item found in local storage (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:30 GMT] : [64b51f62-d7ac-4572-8c2c-601578d4fa55] : msal.js.browser@2.35.0 : Verbose - initializeServerTelemetryManager called (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:30 GMT] : @azure/msal-browser@2.35.0 : Trace - BrowserCacheManager.getTemporaryCache: No cache item found in local storage (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:30 GMT] : [64b51f62-d7ac-4572-8c2c-601578d4fa55] : msal.js.browser@2.35.0 : Info - handleRedirectPromise called but there is no interaction in progress, returning null. (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:30 GMT] : @azure/msal-browser@2.35.0 : Info - Emitting event: msal:handleRedirectEnd (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:30 GMT] : @azure/msal-browser@2.35.0 : Verbose - Emitting event to callback ca25b1f0-cd35-43ad-8314-702f8143d9aa: msal:handleRedirectEnd (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:30 GMT] : @azure/msal-angular@2.5.5 : Verbose - BroadcastService - msal:handleRedirectEnd results in setting inProgress from handleRedirect to none (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:30 GMT] : @azure/msal-browser@2.35.0 : Verbose - getAllAccounts called (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:30 GMT] : @azure/msal-browser@2.35.0 : Trace - BrowserCacheManager.getAccountKeys called (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:30 GMT] : @azure/msal-browser@2.35.0 : Verbose - BrowserCacheManager.getAccountKeys - No account keys found (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:30 GMT] : @azure/msal-browser@2.35.0 : Verbose - Adding account storage listener. (main.c937671b51c99301.js, line 1) 

 

[Log] none (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:30 GMT] : @azure/msal-browser@2.35.0 : Verbose - getAllAccounts called (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:30 GMT] : @azure/msal-browser@2.35.0 : Trace - BrowserCacheManager.getAccountKeys called (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:30 GMT] : @azure/msal-browser@2.35.0 : Verbose - BrowserCacheManager.getAccountKeys - No account keys found (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:30 GMT] : @azure/msal-browser@2.35.0 : Trace - BrowserCacheManager.getActiveAccount: No active account filters cache schema found, looking for legacy schema (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:30 GMT] : @azure/msal-browser@2.35.0 : Trace - BrowserCacheManager.getActiveAccount: No active account found (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:30 GMT] : @azure/msal-browser@2.35.0 : Verbose - getAllAccounts called (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:30 GMT] : @azure/msal-browser@2.35.0 : Trace - BrowserCacheManager.getAccountKeys called (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:30 GMT] : @azure/msal-browser@2.35.0 : Verbose - BrowserCacheManager.getAccountKeys - No account keys found (main.c937671b51c99301.js, line 1) 

 

[Log] none (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:30 GMT] : @azure/msal-browser@2.35.0 : Verbose - getAllAccounts called (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:30 GMT] : @azure/msal-browser@2.35.0 : Trace - BrowserCacheManager.getAccountKeys called (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:30 GMT] : @azure/msal-browser@2.35.0 : Verbose - BrowserCacheManager.getAccountKeys - No account keys found (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:30 GMT] : @azure/msal-browser@2.35.0 : Trace - BrowserCacheManager.getActiveAccount: No active account filters cache schema found, looking for legacy schema (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:30 GMT] : @azure/msal-browser@2.35.0 : Trace - BrowserCacheManager.getActiveAccount: No active account found (main.c937671b51c99301.js, line 1) 

 

[Log] undefined (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : [c8095d54-22a6-4c34-b3d9-4bd86346244a] : @azure/msal-browser@2.35.0 : Verbose - loginRedirect called (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : [c8095d54-22a6-4c34-b3d9-4bd86346244a] : @azure/msal-browser@2.35.0 : Verbose - acquireTokenRedirect called (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : @azure/msal-browser@2.35.0 : Verbose - preflightBrowserEnvironmentCheck started (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : @azure/msal-browser@2.35.0 : Verbose - preflightInteractiveRequest called, validating app environment (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : @azure/msal-browser@2.35.0 : Trace - BrowserCacheManager.getTemporaryCache: No cache item found in local storage (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : @azure/msal-browser@2.35.0 : Verbose - getAllAccounts called (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : @azure/msal-browser@2.35.0 : Trace - BrowserCacheManager.getAccountKeys called (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : @azure/msal-browser@2.35.0 : Verbose - BrowserCacheManager.getAccountKeys - No account keys found (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : @azure/msal-browser@2.35.0 : Info - Emitting event: msal:loginStart (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : @azure/msal-browser@2.35.0 : Verbose - Emitting event to callback ca25b1f0-cd35-43ad-8314-702f8143d9aa: msal:loginStart (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : @azure/msal-angular@2.5.5 : Verbose - BroadcastService - msal:loginStart results in setting inProgress from none to login (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : @azure/msal-browser@2.35.0 : Trace - PerformanceClient.addQueueMeasurement: queue time provided for standardInteractionClientInitializeAuthorizationRequest is 0 (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : @azure/msal-browser@2.35.0 : Trace - PerformanceClient.addQueueMeasurement: adding correlationId c8095d54-22a6-4c34-b3d9-4bd86346244a to queue measurements (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : [c8095d54-22a6-4c34-b3d9-4bd86346244a] : msal.js.browser@2.35.0 : Verbose - initializeAuthorizationRequest called (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : [c8095d54-22a6-4c34-b3d9-4bd86346244a] : msal.js.browser@2.35.0 : Verbose - getRedirectUri called (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : @azure/msal-browser@2.35.0 : Trace - PerformanceClient.addQueueMeasurement: queue time provided for initializeBaseRequest is 0 (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : [c8095d54-22a6-4c34-b3d9-4bd86346244a] : msal.js.browser@2.35.0 : Verbose - Initializing BaseAuthRequest (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : [c8095d54-22a6-4c34-b3d9-4bd86346244a] : msal.js.browser@2.35.0 : Verbose - Authentication Scheme wasn't explicitly set in request, defaulting to "Bearer" request (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : @azure/msal-browser@2.35.0 : Trace - BrowserCacheManager.getActiveAccount: No active account filters cache schema found, looking for legacy schema (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : @azure/msal-browser@2.35.0 : Trace - BrowserCacheManager.getActiveAccount: No active account found (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : @azure/msal-browser@2.35.0 : Trace - BrowserCacheManager.getTemporaryCache: No cache item found in local storage (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : @azure/msal-browser@2.35.0 : Trace - BrowserCacheManager.getTemporaryCache: No cache item found in local storage (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : @azure/msal-browser@2.35.0 : Trace - BrowserCacheManager.updateCacheEntries called (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : [c8095d54-22a6-4c34-b3d9-4bd86346244a] : msal.js.browser@2.35.0 : Verbose - initializeServerTelemetryManager called (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : @azure/msal-browser@2.35.0 : Trace - PerformanceClient.addQueueMeasurement: queue time provided for standardInteractionClientInitializeAuthorizationCodeRequest is 0 (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : [c8095d54-22a6-4c34-b3d9-4bd86346244a] : msal.js.browser@2.35.0 : Verbose - initializeAuthorizationRequest called (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : @azure/msal-browser@2.35.0 : Trace - PerformanceClient.addQueueMeasurement: queue time provided for standardInteractionClientCreateAuthCodeClient is 0 (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : [c8095d54-22a6-4c34-b3d9-4bd86346244a] : msal.js.browser@2.35.0 : Verbose - getClientConfiguration called (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : @azure/msal-browser@2.35.0 : Trace - PerformanceClient.addQueueMeasurement: queue time provided for standardInteractionClientGetDiscoveredAuthority is 0 (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : [c8095d54-22a6-4c34-b3d9-4bd86346244a] : msal.js.browser@2.35.0 : Verbose - getDiscoveredAuthority called (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : [c8095d54-22a6-4c34-b3d9-4bd86346244a] : @azure/msal-browser@2.35.0 : Trace - PerformanceClient: Performance measurement started for standardInteractionClientGetDiscoveredAuthority (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : [c8095d54-22a6-4c34-b3d9-4bd86346244a] : @azure/msal-browser@2.35.0 : Trace - PerformanceClient: Performance measurement for standardInteractionClientGetDiscoveredAuthority started (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : [c8095d54-22a6-4c34-b3d9-4bd86346244a] : msal.js.browser@2.35.0 : Verbose - Creating discovered authority with configured authority (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : @azure/msal-browser@2.35.0 : Trace - PerformanceClient.addQueueMeasurement: queue time provided for authorityFactoryCreateDiscoveredInstance is 0 (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : @azure/msal-browser@2.35.0 : Trace - PerformanceClient.addQueueMeasurement: queue time provided for authorityResolveEndpointsAsync is 0 (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : @azure/msal-browser@2.35.0 : Trace - PerformanceClient.addQueueMeasurement: queue time provided for authorityUpdateCloudDiscoveryMetadata is 0 (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : [c8095d54-22a6-4c34-b3d9-4bd86346244a] : msal.js.browser@2.35.0 : Verbose - Attempting to get cloud discovery metadata in the config (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : [c8095d54-22a6-4c34-b3d9-4bd86346244a] : msal.js.browser@2.35.0 : Verbose - The host is included in knownAuthorities. Creating new cloud discovery metadata from the host. (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : [c8095d54-22a6-4c34-b3d9-4bd86346244a] : msal.js.browser@2.35.0 : Verbose - Found cloud discovery metadata in the config. (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : @azure/msal-browser@2.35.0 : Trace - PerformanceClient.addQueueMeasurement: queue time provided for authorityGetEndpointMetadataFromNetwork is 0 (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : @azure/msal-browser@2.35.0 : Trace - BrowserCacheManager.setAuthorityMetadata called (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : [c8095d54-22a6-4c34-b3d9-4bd86346244a] : @azure/msal-browser@2.35.0 : Trace - PerformanceClient: Performance measurements discarded (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : [c8095d54-22a6-4c34-b3d9-4bd86346244a] : @azure/msal-browser@2.35.0 : Trace - PerformanceClient: QueueMeasurements discarded (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : [c8095d54-22a6-4c34-b3d9-4bd86346244a] : @azure/msal-browser@2.35.0 : Trace - PerformanceClient: Pre-queue times discarded (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : [c8095d54-22a6-4c34-b3d9-4bd86346244a] : @azure/msal-browser@2.35.0 : Trace - PerformanceClient: Performance measurement ended for standardInteractionClientGetDiscoveredAuthority: 92 ms (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : [c8095d54-22a6-4c34-b3d9-4bd86346244a] : @azure/msal-browser@2.35.0 : Verbose - PerformanceClient: Emitting performance events (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : [c8095d54-22a6-4c34-b3d9-4bd86346244a] : msal.js.browser@2.35.0 : Verbose - Auth code client created (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : [c8095d54-22a6-4c34-b3d9-4bd86346244a] : msal.js.browser@2.35.0 : Trace - isNativeAvailable called (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : [c8095d54-22a6-4c34-b3d9-4bd86346244a] : msal.js.browser@2.35.0 : Trace - isNativeAvailable: allowNativeBroker is not enabled, returning false (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : @azure/msal-browser@2.35.0 : Trace - PerformanceClient.getPreQueueTime: no pre-queue times found for correlationId: c8095d54-22a6-4c34-b3d9-4bd86346244a, unable to add queue measurement (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : @azure/msal-browser@2.35.0 : Trace - PerformanceClient.addQueueMeasurement: queue time provided for authClientCreateQueryString is 0 (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : @azure/msal-browser@2.35.0 : Trace - PerformanceClient.addQueueMeasurement: adding correlationId c8095d54-22a6-4c34-b3d9-4bd86346244a to queue measurements (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : [c8095d54-22a6-4c34-b3d9-4bd86346244a] : msal.js.browser@2.35.0 : Verbose - RedirectHandler.initiateAuthRequest called (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : [c8095d54-22a6-4c34-b3d9-4bd86346244a] : msal.js.browser@2.35.0 : Verbose - RedirectHandler.initiateAuthRequest: redirectStartPage set, caching start page (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : @azure/msal-browser@2.35.0 : Trace - BrowserCacheManager.cacheCodeRequest called (main.c937671b51c99301.js, line 1) 

 

[Log] [Mon, 17 Apr 2023 04:28:32 GMT] : [c8095d54-22a6-4c34-b3d9-4bd86346244a] : msal.js.browser@2.35.0 : Verbose - RedirectHandler.initiateAuthRequest: Navigating window to navigate url (main.c937671b51c99301.js, line 1) 

### MSAL Configuration

```javascript
auth: {
      clientId: environment.aadB2CClientId,
      authority: `https://${environment.aadB2CDomain}/${environment.aadB2CTenant}/${environment.aadB2CSIPolicy}`,
      redirectUri: getLocationOriginWithPath('login'),
      postLogoutRedirectUri: getLocationOriginWithPath('logout'),
      knownAuthorities: [environment.aadB2CDomain],
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE, // set to true for IE 11
    },
    system: {
      allowNativeBroker: false, // Disables WAM Broker
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Trace,
        piiLoggingEnabled: false
      }
    }
```

### Relevant Code Snippets

```javascript
No code snippet, but the whole project: https://github.com/edgarsenrarocha/msal-word-add-in-safari-test
```

### Reproduction Steps

1. Clone https://github.com/edgarsenrarocha/msal-word-add-in-safari-test
2. Change the AzureADB2C configurations
3. Run npm build-prod
4. Deploy it somewhere
5. Change the manifest file to the URL of the add-in(created in previous steps
6. Install the add-in manifest on Mac (latest OS version)
7. 8. Open Microsoft Word and open the task pane add-in
9. Click "Sign In"
10. Click "Login"

### Expected Behavior

Clicking "Login" in the dialog should redirect to the AzureB2C sign-in page just like it does on Windows.

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Safari

### Source

External (Customer)

**Comment by lalimasharda** [comment]
Hi @edgarsenrarocha, can you confirm that the host page URL on which the dialog is triggered is the same as the URL being passed to the displayDialogAsync method?

**Comment by edgarsenrarocha** [comment]
Hi @lalimasharda,

The URLs are the same(**https://rs-addin-test.azurewebsites.net/**) but the main taskpane page is **/home** and the dialog one is **/login**  .

Just to be clear, the MSAL **loginRedirect** function works normally when running **locally** on MacOS (Safari), but when deployed on the server it **doesn't** redirect. Also, if I run the add-in on **Windows** it works too.

Please run on your machine using the manifest: https://github.com/edgarsenrarocha/msal-word-add-in-safari-test/blob/master/manifests/test-manifest.xml

**Comment by lalimasharda** [comment]
Hey @edgarsenrarocha, just to be clear, you are able to get tokens in the add-in using loginRedirect on Windows while running it locally as well as on server? Can you double-check the redirect URI registered for this app.. maybe you are missing https instead of http since it is hosted on a server?

**Comment by edgarsenrarocha** [comment]
Hey @lalimasharda,

Correct.
I can also get tokens in the add-in when running locally on Mac but not on the server (the same one that works on Windows).

I've checked already, the URI is correct with the proper protocol. Both server and local are running over HTTPS with valid certificates.

Could you please run the following manifest on your Mac and Windows machines? You'll notice that it will only work on Windows.

**Comment by edgarsenrarocha** [comment]
Hi, is there anything I can do to help finding the solution for the issue? Thanks

**Comment by sameerag** [comment]
@hectormmg Can you please check this?

**Comment by edgarsenrarocha** [comment]
Hi @hectormmg, 
This a live Word add-in that our Mac customers can't access it. So, it's crucial to get it fixed. Could you please let me know if need anything from me so we can get it fixed sooner?
Thank you,
Edgar

**Comment by tnorling** [comment]
@edgarsenrarocha Could you please collect a fiddler trace and send it to MsalJsHelp@microsoft.com? Thanks!

**Comment by edgarsenrarocha** [comment]
Hi @tnorling,
Just sent, any other info please let me know.
Thanks,
Edgar Rocha

**Comment by tnorling** [comment]
It didn't come through, could you try resending to me directly (thomas.norling@microsoft.com). Thanks!

**Comment by tnorling** [comment]
Thanks, I just wanted to confirm that the redirect wasn't being cancelled, it does not appear to be the case, I don't see the request at all. Based on the logs you shared in the original issue [this line](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/bce0cb792ffe9f45429a2ee918a9c92ce16a5ee2/lib/msal-browser/src/navigation/NavigationClient.ts#L37) is the next, and final line, which should be executed before being redirected to the sign-in page. I wonder if `window.location.assign` isn't supported or has been modified in this environment. Is there any way you could debug this or at least confirm whether you're able to use this API directly (without MSAL)?

**Comment by edgarsenrarocha** [comment]
Thanks @tnorling.

I've added a button to call the [example](https://developer.mozilla.org/en-US/docs/Web/API/Location/assign#examples) which only worked on Windows, but not on Mac, seems like this is the issue.

I was not able to get any logs, it also doesn't throw any errors.

Any ideas on how to solve that?

**Comment by tnorling** [comment]
hmm ok. Either the environment doesn't support this API or something in the app (another dependency perhaps) is modifying the global window object (seems less likely considering this works on Windows...). You should do some research/debugging to dig into this. However, if you're not able to figure it out and can determine if a different API _does_ work (such as window.location.replace) you could [pass in your own implementation of `INavigationClient`](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/navigation.md) to override the default navigation behavior with something more compatible. It's a workaround but I don't know what else to tell you at this point :confused:

**Comment by edgarsenrarocha** [comment]
Thanks @tnorling, yeah, the issue is precisely on window.location API. 
All window.location redirect capabilities (href, replace or assign) doesn't work inside the office dialog on Mac, even without MSAL.
Strangely, when I use the developer tool and disable Javascript and re-enable the problem is gone. Seems like Mac is preventing those APIs to be used. I exhausted all tests, not sure what to do anymore.

**Comment by tnorling** [comment]
That's really unfortunate. However, as this isn't an MSAL issue I'm going to go ahead and close this. Let us know if you have any follow ups.
