### ISSUE TITLE
loginHint is ignored by 

### ISSUE THREAD

**Issue by bumbel42so** [AzureAD/microsoft-authentication-library-for-js#5899]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.35.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.5.5

### Public or Confidential Client?

Public

### Description

Hi, 

in an application where a main user is signed i need to sign in a second user (its part of a approval check). The second user is choosed in a drop down and i handed it over to MsalService.instance.loginPopup as loginHint to prefill in popup window. 
This worked very well for last 2 years, but today suddenly loginHint is ignored and the main user is prefilled in popup window. 
![image](https://user-images.githubusercontent.com/60612641/232533680-0b88612a-6819-4639-a59c-29b3c3e3c562.png)

![image](https://user-images.githubusercontent.com/60612641/232533654-40d4a75b-0030-416e-8304-d5ef751d77fe.png)

Maybe it´s n API change, because i don´t change the lib version? Can you help me please?

### MSAL Configuration

```javascript
const mSALInstanceFactory = (): IPublicClientApplication => new PublicClientApplication({
  auth: {
    clientId: '********,
    authority: 'https://login.microsoftonline.com/***********/',
    redirectUri: '/',
    postLogoutRedirectUri: '/logout'
  }
});
```

### Relevant Code Snippets

```javascript
this.msalSvc.instance.loginPopup({ loginHint: 'donald@duck.de', prompt: 'login' } as PopupRequest).then(
```

### Reproduction Steps

1. login a user
2. log in a second user with provided loginHint

### Expected Behavior

User from loginHint should be prefilled

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

External (Customer)

**Comment by lalimasharda** [comment]
Hi @bumbel42so! Can you check the URL in the popup and see if prompt=login is present? 

This issue also seems similar to #5858

**Comment by bumbel42so** [comment]
@lalimasharda 
Yes &prompt=login is in the Popup URL present 

Sorry for late response, i was on holidays.

**Comment by bumbel42so** [comment]
By studying the URL parameters i noticed the login_hint parameter is something like
&login_hint=O.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx%3D%3D3
i decoded this with base64 and got the objectid + tenantid + username of the first logged in user

![image](https://user-images.githubusercontent.com/60612641/235621494-f04f1b69-4c5a-42fd-b5b6-742808b17ca2.png)

**Comment by bumbel42so** [comment]
Now i found a solution: 
In another part of the application i set the active account via

**Comment by bumbel42so** [comment]
Now i found a solution that worked for me. Even if i can´t explain why it has appeared suddenly. 

In another part of the application i set the active account via

> this.msalSvc.instance.setActiveAccount(this.msalSvc.instance.getAllAccounts()[0]);

If i remove this it works. 
Or as alternative solution i can set the active account to null before login a second user or i put an empty object as account to request parameters 
> this.msalSvc.loginPopup({ loginHint: 'donald@duck.de', prompt: 'login', account: {} } as PopupRequest)

If this is intended, documentation would be helpful.
