### ISSUE TITLE
Silently log out user the app, not from the Microsoft account

### ISSUE THREAD

**Issue by proambb** [AzureAD/microsoft-authentication-library-for-js#5906]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.35.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.5.5

### Public or Confidential Client?

Public

### Description

 Is there a way to silently log out a user from the app? 

We sign in user using msal, receive idToken, validate it, and then use our cookies to manage user's session. But since the library stores cache when we do log out in our app, msal still have idToken of the user. 

How can we clear this idToken? We don't want to use `logout` method and log out the user from his Microsoft account. We just want to clear information in our app, as though the user just opened the page for the first time. 

One way to achieve this is to use `SessionStorage` for caching and clear it on user log out, but it looks like a hack

 
 

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by lalimasharda** [comment]
Hi @davoam , we have some documentation on silently logging the user out ([Promptless logout](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md#promptless-logout)). Please have a look and let me know if you need more help!

Also typically, when user logs out using one of the logout methods - logoutRedirect or logoutPopup, all of the cache is cleared out along with the id tokens as long as you are going through the whole logout process including the server side also. If for some reason you are still seeing id tokens in the cache, then we will need to look into it further. Which interaction method are you using for logout at the moment?

**Comment by proambb** [comment]
> Hi @davoam , we have some documentation on silently logging the user out ([Promptless logout](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md#promptless-logout)). Please have a look and let me know if you need more help!
> 
> Also typically, when user logs out using one of the logout methods - logoutRedirect or logoutPopup, all of the cache is cleared out along with the id tokens as long as you are going through the whole logout process including the server side also. If for some reason you are still seeing id tokens in the cache, then we will need to look into it further. Which interaction method are you using for logout at the moment?

@lalimasharda thanks for the quick response! 

This is not what we want. We don't want to log out a user from his Microsoft account (`logoutRedirect` or `logoutPopup`), we just want to clear the cache of the library. 

Assume that you have set cache location to 'sessionStorage' logged in, closed the tab, and opened another tab of your app, now you have nothing in your cache. We want to achieve the same result, but without closing the tab. 

Now, I just clear the `sessionStorage` on log out in our app. 

P.S. We use idToken from msal library, verify it, and then use our cookies for managing user session. When a user logs out from our app, there is still idToken in the cache of the library. We'd like to clear the cache of the library as well.

**Comment by lalimasharda** [comment]
Got it.. I think this is more suited for your needs: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md#skipping-the-server-sign-out

Let me know if this still does not work for you.

**Comment by sameerag** [comment]
Closing this as the guidance is provided. Please let us know if you need more help, preferably, create a new issue. Thanks.

**Comment by proambb** [comment]
@lalimasharda @sameerag thanks!
