### ISSUE TITLE
inProgress status stucks in Login state after restoring app from bfcache

### ISSUE THREAD

**Issue by yksht** [AzureAD/microsoft-authentication-library-for-js#5908]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.36.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.5.5

### Public or Confidential Client?

Public

### Description

MSAL `inProgress` status stucks in `Login` state after restoring the app from bfcache in browser.

I made a test project for this problem:
https://stackblitz.com/edit/angular-k8caw7?file=src/app/app.module.ts

Notes:
1. msal configured with `Redirect` interaction type
2. msal configured with 'Verbose' log level
3. login button handler follows this guide: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/errors.md#interaction_in_progress

### MSAL Configuration

```javascript
https://stackblitz.com/edit/angular-k8caw7?file=src/app/app.module.ts
```

### Relevant Code Snippets

```javascript
-
```

### Reproduction Steps

1. Visit https://angular-k8caw7.stackblitz.io using Chrome or any other browser with activated bfcache
2. Press Login button (you will be redirected to IDP login page)
4. Press back button in the browser (you will be redirected back to the app obviously)
5. Press Login button again - **and here is the problem, nothing happens after the click because `inProgress` status is not  `None`**

### Expected Behavior

MSAL `inProgress` status is `None` after restoring the app from bfcache in browser so 4th reproduction step should cause redirection to IDP page.

### Identity Provider

Other

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari

### Source

External (Customer)

**Comment by yksht** [comment]
Currently I use following solution to reset inProgress status:

```
@HostListener('window:pageshow', ['$event'])
onPageShow(event: PageTransitionEvent): void {
  if (event.persisted) {
    this.document.location.reload();
  }
}
```

**Comment by ChristianHoffmannS2** [comment]
We are having the same issue with msal-react. 

We are using: 

@azure/msal-react@1.5.4
@azure/msal-browser@2.34.0

We actually only need to hit the browser back button after logging in and we are already in the inProgress dead end. InProgress has always the value of "Login". 

We set the LogLevel to verbose and got these logs:

```
logger [Thu, 20 Apr 2023 12:27:27 GMT] : [xxxxx-xxxxx-xxxx-xxxxxx] : msal.js.browser@2.34.0 : Verbose - validateAndExtractStateFromHash called
client.tsx:43 logger [Thu, 20 Apr 2023 12:27:27 GMT] : [xxxxx-xxxxx-xxxx-xxxxxx] : msal.js.browser@2.34.0 : Verbose - Returning state from hash
client.tsx:43 logger [Thu, 20 Apr 2023 12:27:27 GMT] : [xxxxx-xxxxx-xxxx-xxxxxx : msal.js.browser@2.34.0 : Verbose - InteractionHandler.handleCodeResponse called
client.tsx:43 logger [Thu, 20 Apr 2023 12:27:27 GMT] : @azure/msal-browser@2.34.0 : Info - Emitting event: msal:ssoSilentFailure
client.tsx:43 logger [Thu, 20 Apr 2023 12:27:27 GMT] : @azure/msal-browser@2.34.0 : Verbose - Emitting event to callback zzzzzz-zzzzzz-zzzzz-zzzzz: msal:ssoSilentFailure
client.tsx:43 logger [Thu, 20 Apr 2023 12:27:27 GMT] : @azure/msal-browser@2.34.0 : Verbose - getAllAccounts called
client.tsx:43 logger [Thu, 20 Apr 2023 12:27:27 GMT] : [xxxxx-xxxxx-xxxx-xxxxxx] : @azure/msal-browser@2.34.0 : Verbose - PerformanceClient: Emitting performance events
client.tsx:43 logger [Thu, 20 Apr 2023 12:27:31 GMT] : [yyyyy-yyyyy-yyyyy-yyyyyy] : msal.js.browser@2.34.0 : Verbose - Page was restored from back/forward cache. Clearing temporary cache.
client.tsx:43 logger [Thu, 20 Apr 2023 12:27:33 GMT] : @azure/msal-react@1.5.4 : Info - useAccount - Updating account
3client.tsx:43 logger [Thu, 20 Apr 2023 12:27:34 GMT] : @azure/msal-react@1.5.4 : Info - useAccount - Updating account
```

This bug is supposed to be fixed, but thats not what we are experiencing: 
https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4171

**Comment by yksht** [comment]
@ChristianHoffmannS2 
Thanks for the link. I looked for similar issue before creating the one but nothing found.

By the way I also tried to call handleRedirectPromise on pageshow event and it doesn't reset inProgress status to 'None'. So for now I use solution with page reloading

**Comment by lalimasharda** [comment]
Hi @yksht @ChristianHoffmannS2 , this seems to be a bug on our side. We are working on a fix for it. Will let you know once we make the fix. Thanks!

**Comment by tnorling** [comment]
A fix for this was merged and will be included in the June release.
