### ISSUE TITLE
Good way to test a silent token refresh failure in MSAL for Blazor?

### ISSUE THREAD

**Issue by andrewrondeau-optirtc** [AzureAD/microsoft-authentication-library-for-js#5913]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2

### Wrapper Library

Not Applicable

### Wrapper Library Version

Microsoft.Authentication.WebAssembly.Msal 7.0.4

### Public or Confidential Client?

Public

### Description

(Originally submitted at https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4098)

I'm currently using MSAL (https://www.nuget.org/packages/Microsoft.Authentication.WebAssembly.Msal 7.0.4) in a blazor project.

Due to how our project is implemented, silent token refresh is failing. (As described at https://learn.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-acquire-token?tabs=javascript2, "More often, failures are due to the refresh token's 24-hour lifetime expiring and [the browser blocking third party cookies](https://learn.microsoft.com/en-us/azure/active-directory/develop/reference-third-party-cookies-spas), which prevents the use of hidden iframes to continue authenticating the user.")

In this case, I get an AccessTokenNotAvailableException when I make an HTTP request. Handling this exception is documented at https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-8.0#attach-tokens-to-outgoing-requests.

**How do I simulate a silent token refresh failure so I can test a silent token refresh _interactively_?**

So far I've put in a debugging hook to throw an AccessTokenNotAvailableException from a subclass of AuthorizationMessageHandler. Is there a better way to do this? We need to keep this as part of our regression suite; and our product is not ready to invest in significant test automation.

For example, is there a value we can tweak in local storage or session storage that would trigger MSAL to perform a silent token refresh?

### Relevant Code Snippets

```javascript
I am looking to test code based on https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-8.0#attach-tokens-to-outgoing-requests

protected override async Task OnInitializedAsync()
{
    try
    {
        var examples = 
            await Http.GetFromJsonAsync<ExampleType[]>("ExampleAPIMethod");

        ...
    }
    catch (AccessTokenNotAvailableException exception)
    {
        exception.Redirect();
    }
}
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by sameerag** [comment]
Yes, @andrewrondeau-optirtc. Can you update the `expiresIn` in your stored token cache from the `localStorage` to simulate token expiry and try?

**Comment by andrewrondeau-optirtc** [comment]
I can't find "expiresIn"

This is what MSAL in Blazor stores for me:

![image](https://user-images.githubusercontent.com/78368152/234309666-daae70ed-a15a-4058-8031-6b61b34a345c.png)

There is nothing in Session storage:

![image](https://user-images.githubusercontent.com/78368152/234309867-7a55ce74-6e68-46ff-8f07-56537523d19d.png)

There are some cookies that appear to have sensitive information, but no "expiresIn".

There are no trust tokens.

Am I looking in the wrong place? (F12, Application tab, Local Storage).

I've currently configured storage like this, although we can change it if needed:

`
            options.ProviderOptions.LoginMode = "redirect";

            // Keeps us logged in between debugging sessions
            options.ProviderOptions.Cache.CacheLocation = "localStorage";
            options.ProviderOptions.Cache.StoreAuthStateInCookie = false;

`

**Comment by konstantin-msft** [comment]
Hi @andrewrondeau-optirtc.

Please refer to the [token lifetime cache lookup policy](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/token-lifetimes.md#cache-lookup-policy). Setting `cacheLookupPolicy` to `CacheLookupPolicy.Skip` makes the request fail as long as the 3rd party cookies are blocked by the browser (which is your use case as far as I get it). These [code snippets](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/token-lifetimes.md#code-snippets) might be helpful.

**Comment by andrewrondeau-optirtc** [comment]
How would I adapt that to fit in the sample code that's in the ticket description?

**Specifically,** how do I make "await Http.GetFromJsonAsync<ExampleType[]>("ExampleAPIMethod");" simulate a silent token refresh failure such that it throws an AccessTokenNotAvailableException?

Remember, I'm seeking support for Blazor (WASM,). I initially filed this support ticket here: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4098

(As shown in the code example that's part of the ticket description, I am not calling acquireTokenSilent or a C# equivalent.)

**Comment by sameerag** [comment]
Apologies for the mix up @andrewrondeau-optirtc. We can only manage `expiresIn` from the `accessToken`, I do not think clients can manage RT expiry, it is a blob we cannot decipher. @konstantin-msft  is following up with the service team if they can help, but we do not think client (MSAL JS) can simulate this.

**Comment by bgavrilMS** [comment]
@andrewrondeau-optirtc - I can think of 3 ways for you to test:

1. As a tenant admin, you can invalidate all refresh tokens for a user https://learn.microsoft.com/en-us/azure/active-directory/enterprise-users/users-revoke-access
2. As a tenant admin, you can change the security configuration and ask for MFA from your users. 
3. You can also set token lifetime, I think the min for an RT is a few hours.  https://learn.microsoft.com/en-us/azure/active-directory/develop/configurable-token-lifetimes

In all these cases, your app is unaware that the cached RT is invalid and will try to use it. What will happen internally is: 


1. You call `AcquireTokenSilent`
2. MSAL checks for a cached access token. If AT is expired, it will look for RT.
3. MSAL will perform the `refresh_token` OAuth grant. 
4. AAD will refuse and will respond with a [specific error](https://learn.microsoft.com/en-us/azure/active-directory/develop/reference-error-codes) (`interaction_required` or `invalid_grant` if memory servers) 
5. MSAL will throw an UIRequiredException
6. Your app is supposed to catch this exception, see if there are any claims and call `AcquireTokenInteractive` + claims
7. User logs in interactively and will be guided to resolve the problem. This may simply mean performing MFA, or just logging in as normal etc.

Hope this helps.

**Comment by bgavrilMS** [comment]
If you really want to write a unit test around this, you can inject your own HTTP stack and when MSAL performs the refresh_token flow, you can respond with a 400 + "interaction_required" failure just like AAD would. 

But I would think a better E2E test is to option 1 from above.

**Comment by andrewrondeau-optirtc** [comment]
Ok, so it looks like I can revoke my refresh token with "Revoke-AzureADUserAllRefreshToken -ObjectId (email address)"; but not my session token.

I ran that once and triggered a re-login. I'll retry it another time today and verify that it's working.

**Comment by andrewrondeau-optirtc** [comment]
Ok, that did it. Thanks!
