### ISSUE TITLE
Cannot sign in - We're currently unable to complete your request.

### ISSUE THREAD

**Issue by jonhue** [AzureAD/microsoft-authentication-library-for-js#592]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version 72
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version
Library version: 0.2.4

## Current behavior
After entering the email address in the login popup, I'm redirected to a page that says: We're currently unable to complete your request.

## Expected behavior
Proceed with the sign in process.

---

I'm pretty certain that this is a configuration issue with my app registration in the Azure portal as I tried using [this page](https://shawntabrizi.com/msal/) with my client id, and it failed too. However, by now I tried every possible combination of settings. What configuration would I need for example to use my application with the above mentioned tool?

My understanding is that
* I do not need any web redirect URIs
* I need the suggested public redirect URI `msal<client_id>://auth`
* I don not need to provide access token/id token with the authorization endpoint

Are these assumptions correct?

**Comment by visualjeff** [comment]
From the client side you should provide:
1. clientId  <== from your registered app
2. resource  <== https://login.microsoftonline.com/YOUR_TENANT_NAME.onmicrosoft.com
3. redirectUri  <== Something like http://localhost:8080

The redirectUri from the client side should match what you have set in your registered Azure app.

The authorization endpoint will return an id_token from which you can get an access_token.
