### ISSUE TITLE
How to request token for a specific audience?

### ISSUE THREAD

**Issue by rwilliams3088** [AzureAD/microsoft-authentication-library-for-js#5920]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.33.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.5.3

### Public or Confidential Client?

Public

### Description

I am attempting to implement the on-behalf-of (OBO) flow where I pass the token acquired on the front-end (using msal-react) and pass it to a middle-tier application (a confidential client) for it to use. In order to get this to work, I need the token audience to be set to the middle-tier application's client id. I'm not seeing any documentation on how to set the requested audience for the token. Please advise on how to use msal-react to request a token for a specific audience. Thanks!

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by sameerag** [comment]
@rwilliams3088 While requesting the token , setting for a scope of the format: `api://<App Id URI>/Read value` should give you what you are looking for. MSAL JS docs on how to set the scope format is [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/api-scopes).

I found a relative blog post that can help [here](https://learn.microsoft.com/en-us/answers/questions/899390/how-to-use-the-access-token-provided-by-microsoft?page=1#answer-903578) that can help you.
