### ISSUE TITLE
Token is not Expired After Logging out From React Application

### ISSUE THREAD

**Issue by ArunKumar-webdev** [AzureAD/microsoft-authentication-library-for-js#5937]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

1.4.2

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

We are Logging in from Microsoft account as well as Gmail for our application but even after logging out i can enter into application without submitting credentials until till the token expires automatically (after 24hr from token created). i used all methods in documentation by popup logout and redirect logout but still i couldn't find the solution to fix this issue.

note: checked cookies and all storage nothing as been stored.

### MSAL Configuration

```javascript
const msalConfig = {
  auth: {
    clientId: Policies.clientId,
    authority: Policies.authorities.signUpSignIn.authority,
    knownAuthorities: Policies.authorityDomain.split(","),
    redirectUri: "/",
    navigateToLoginRequestUrl: false,
  },
  cache: {
    cacheLocation: "localStorage", // This configures where your cache will be stored
    storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
  },
  system: {
    windowHashTimeout: 10000, // Applies just to popup calls - In milliseconds
    iframeHashTimeout: 10000, // Applies just to silent calls - In milliseconds
    loadFrameTimeout: 10000, // Applies to both silent and popup calls - In milliseconds
    loggerOptions: {
    },
  },
};
```

### Relevant Code Snippets

```javascript
handleLogout(instance: IPublicClientApplication) {
  instance.logoutRedirect({ postLogoutRedirectUri: "/logout" }).catch((e) => {
    console.error(e);
  });
}
```

### Identity Provider

Azure B2C Custom Policy

### Source

Internal (Microsoft)

**Comment by ArunKumar-webdev** [comment]
By the way i am using okta for other domain signing/logging except microsoft account

**Comment by sameerag** [comment]
@ArunKumar-webdev Looks like B2C service isn't logging you out (session is still alive). Can you please share MSAL logs (instructions [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logging.md)) and a fiddler trace to my email (check my [profile](https://github.com/sameerag))?

If it is service, I can redirect to the B2C folks but let us establish that through the logs.

**Comment by ArunKumar-webdev** [comment]
@sameerag Can you please help me on how to take MSAL logs, fiddler trace and also attached instructions link is not proper

are you asking below log details
![image](https://user-images.githubusercontent.com/69241947/235847947-394bdfc7-b15d-4360-b600-e5a6cf4a6b65.png)

**Comment by sameerag** [comment]
> @sameerag Can you please help me on how to take MSAL logs, fiddler trace and also attached instructions link is not proper

Apologies. Updated the proper link in the above message now. Fiddler trace is straight forward, please download [fiddler](https://www.telerik.com/fiddler) and collect the chrome process logs which should capture the network traffic.

> are you asking below log details ![image](https://user-images.githubusercontent.com/69241947/235847947-394bdfc7-b15d-4360-b600-e5a6cf4a6b65.png)

Yes. Please turn on verbose (as stated in the above link) and share the logs.

**Comment by ArunKumar-webdev** [comment]
@sameerag @konstantin-msft Sent the required details via mail

**Comment by konstantin-msft** [comment]
Hi @ArunKumar-webdev. 
Thank you for sharing the fiddler trace. I can see that the logout request to `dev-*.okta.com/oauth2/default/v1/logout` returned HTTP 400. Please correct me if i am wrong but it looks like Okta OIDC policy requires providing `id_token` issued during sign on as part of SLO request. Please add `idTokenHint` to logout handler. Also, please refer to [end session request](https://azuread.github.io/microsoft-authentication-library-for-js/ref/modules/_azure_msal_browser.html#endsessionrequest) doc for more details.

```javascript
handleLogout(instance: IPublicClientApplication) {
  instance.logoutRedirect({ postLogoutRedirectUri: "/logout", idTokenHint: "<your_account.idToken>" }).catch((e) => {
    console.error(e);
  });
}
```

**Comment by ArunKumar-webdev** [comment]
Hi @konstantin-msft ,

Thanks for the response, but I tried with idTokenHint still I get HTTP 400. is there any other solution or way to track the cause of issue.

code I used for logout:

 function handleLogout(instance: IPublicClientApplication) {
    instance.logoutRedirect({
      postLogoutRedirectUri: "/logout" ,
      idTokenHint: instance.getActiveAccount()?.idToken
      // also used like by retriving from accounts
      // idTokenHint: account.iat
      }).catch((e) => {
      console.error(e);
    });
  }
  
  also i shared the fiddler trace after adding idTokenHint via mail

**Comment by konstantin-msft** [comment]
By looking at the latest fiddler trace I can see that the logout request still does not carry an `id_token` query parameter.
Please check that:
1. b2c provider provides `id_token` during sign-on
2. active account is set with [instance.setActiveAccount()](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-react-samples/b2c-sample/src/index.js#L17) before calling `instance.getActiveAccount()?.idToken` or get `idToken` with `msalInstance.getAllAccounts()[0].idToken`

**Comment by ArunKumar-webdev** [comment]
Hi @konstantin-msft ,

Getting the idToken from this https://******_signin_openid/oauth2/v2.0/token and using this idTokenHint: idToken,

![image](https://user-images.githubusercontent.com/69241947/236605864-6f349e79-14e2-474f-a20c-b6350b8cd38c.png)

Code Snippet:
____________________________________________________________________
function handleLogout(instance: IPublicClientApplication) {
    instance.setActiveAccount(instance.getAllAccounts()[0]);
    instance.logoutRedirect({
      postLogoutRedirectUri: "/logout" , idTokenHint: idToken,
    }).catch((e) => {
      console.error(e);
    });
  }
_________________________________________________________________________
  
 I am not getting idToken in MSAL instance.
 
![image](https://user-images.githubusercontent.com/69241947/236606130-6ef29592-83ee-44f4-8e09-1d0657d99cac.png)

by any chance is there any separate API to logout from account?

**Comment by konstantin-msft** [comment]
@ArunKumar-webdev There is no other logout API that can help to circumvent this. Can you please share the trace logs? Please refer to [this doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logging.md) for assistance.
It looks like the `idToken` is not picked up for you [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/msal-lts/lib/msal-common/src/cache/CacheManager.ts#L228). Are you fetching the `idToken` before setting an active account? Can you please share the corresponding code snippet as well?

**Comment by ArunKumar-webdev** [comment]
Hi @konstantin-msft 

I am not setting active account any were if i need current account I will take current account like the below code snippet
__________________________________________
const account = useAccount(accounts?.[0] || {});
_________________________________________________________

Initial Login happens like below code snippet

if any user is still not logged silent token works. if not loginRedirect happens 
____________________________________________________
export const handleLogin = (
  instance: IPublicClientApplication,
  request: any
) => {
  //Authenticating by silent sso
  instance.ssoSilent(request as SsoSilentRequest).catch((error) => {
    console.error(error);
    //if silent authentication is failed, trying to authenticate by full page redirect.
    instance.loginRedirect(request as RedirectRequest).catch((err) => {
      console.error(err);
    });
  });
____________________________________________________

As mentioned previously i am getting the idToken from this https://******_signin_openid/oauth2/v2.0/token and storing it in redux using like this when user trying to logout

____________________________________
function handleLogout(instance: IPublicClientApplication) {
instance.setActiveAccount(instance.getAllAccounts()[0]);
instance.logoutRedirect({
postLogoutRedirectUri: "/logout" , idTokenHint: idToken,
}).catch((e) => {
console.error(e);
});
}
____________________________________________

log trace:
![image](https://user-images.githubusercontent.com/69241947/236872694-d4e24ded-004f-40bb-aaa7-86fc14a13112.png)

**Comment by konstantin-msft** [comment]
@ArunKumar-webdev Can you please check that the `idToken`, cached by redux, has the proper format and passed as a raw string to `instance.logoutRedirect()`? I am trying to figure out why `idTokenHint` is not picked up by logout query builder. Thanks.

**Comment by ArunKumar-webdev** [comment]
@hectormmg @konstantin-msft 

I am resetting the store to initial state in logout page and clearing the storage too.

_______________________________________________________________________
useEffect(() => {
    if(persistor){
      persistor.pause();
      persistor.flush().then(() => {
        return persistor.purge();
      });
    }

    dispatch(resetAccount());
    sessionStorage.clear();
    localStorage.clear();
    console.log('clear data');
  }, []);
  ______________________________________________________________________________

**Comment by konstantin-msft** [comment]
@ArunKumar-webdev Got it. Can you please debug this piece of code
```javascript
function handleLogout(instance: IPublicClientApplication) {
  instance.setActiveAccount(instance.getAllAccounts()[0]);
  instance.logoutRedirect({
    postLogoutRedirectUri: "/logout" , idTokenHint: idToken,
  }).catch((e) => {
    console.error(e);
  });
}
```
to make sure that `idTokenHint` is picked up (not null) before you flush the store? Is there a chance you flush the store before fetching the token?

**Comment by ArunKumar-webdev** [comment]
Hi @konstantin-msft ,

value is not null when setting active account
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/69241947/da68e743-d28b-4804-a5e2-18365b46ce00)

and also the idToken value is passed 
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/69241947/fba8505a-3be9-4661-b187-e8d44317be3c)

do we need to register logout url or any related to this in okta or azure active directory 

is there any chance to have meeting with you to get better solution on this issue?

**Comment by ArunKumar-webdev** [comment]
any updates

**Comment by tnorling** [comment]
Hi @ArunKumar-webdev, I'd like to confirm my understanding. You are using B2C with federation to Microsoft consumer accounts, but upon logout your session remains active. Is that correct? 

You also mentioned Okta so I want to make sure we're on the same page. This is NOT an issue pertaining to B2C with federation to Okta, correct?

**Comment by tnorling** [comment]
Regarding the idTokenHint, I see you've confirmed that the idTokenHint is now being passed into the logoutRedirect API. If you could collect a network trace that shows sign-in, sign-out and then finally the subsequent sign-in that would be helpful to debug this further. You can send it to the email on my profile. Thanks!

**Comment by ArunKumar-webdev** [comment]
Hi @tnorling 

 I'd like to confirm my understanding. You are using B2C with federation to Microsoft consumer accounts, but upon logout your session remains active. Is that correct?
 Ans: Yes
 
We are using B2C custom policy in which we are using multiple IDP based on customer’s. were OKTA is one, and by using MSAL, we authenticate in our React application.

I sent network trace via mail to you kindly check it.

**Comment by tnorling** [comment]
Thanks. I now see that the id_token_hint is being sent to the B2C logout endpoint but it is not being forwarded to the Okta logout. You'll need to update your B2C policy to ensure that the correct query parameters are passed through from B2C to your federated IDP(s). We are unfortunately not B2C experts so if you need assistance with policy related questions you should [open a support ticket with B2C](https://learn.microsoft.com/en-us/azure/active-directory-b2c/find-help-open-support-ticket).
