### ISSUE TITLE
Angular7 Azure AD redirect loops in S3 bucket.But, Pop up works fine. I need loginredirect

### ISSUE THREAD

**Issue by ss94866** [AzureAD/microsoft-authentication-library-for-js#5939]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

1.4.4

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

1.1.2

### Public or Confidential Client?

Public

### Description

I used your angular 7 sample code. I changed the code from loginpopup to loginredirect and hosted in the S3 bucket. It works fine in the local for both popup and redirect. It works fine for loginpopup in the S3. But, it loops for ad redirect. My entering https://domain.com/index.html, it loads and moves to https://domain.com/ and redirect to ad login page. After successful authentication, it redirects to S3 link with id_token, https://domain.com/index.html#id_token=eynsns... Then, it loops their. I can't able to login. Please help me to resolve this issue. Do I need to add any configuration in the app.module.ts for redirect rather than popup.

### Error Message

Angular 7 Azure ad redirects loops in the S3 bucket, but popup works fine in the s3

### MSAL Configuration

```javascript
I used your sample angular 7 code for configuration. I changed login() in app.component.ts and changed app.modules.ts as popup:false

I commented login popup
login() {
  //  const isIE = window.navigator.userAgent.indexOf('MSIE ') > -1 || window.navigator.userAgent.indexOf('Trident/') > -1;

   // if (isIE) {
      this.authService.loginRedirect();
   // } else {
     // this.authService.loginPopup();
    }
  }
```

### Relevant Code Snippets

```javascript
login() {
  //  const isIE = window.navigator.userAgent.indexOf('MSIE ') > -1 || window.navigator.userAgent.indexOf('Trident/') > -1;

   // if (isIE) {
      this.authService.loginRedirect();
   // } else {
     // this.authService.loginPopup();
    }
  }
```

### Reproduction Steps

1. Make angular 7 sample application to redirect sample
2. Build it and host it in the S3 bucket
3. Try to login via ad redirects. It loops in the Idtoken.

### Expected Behavior

Need proper login with azure ad redirects in angular 7 in S3 buckets. Without loop, it has to make me log in.
https://domain.com/index.html#id_token=eynsns... Then, it loops their. I can't able to login. Please help me to resolve this issue. Do I need to add any configuration in the app.module.ts for redirect rather than popup.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge

### Source

External (Customer)

**Comment by ss94866** [comment]
Hi, please give some updates.

**Comment by sameerag** [comment]
@ss94866 Are you handling the response with `handleRedirectPromise?` Can you share the msaljs logs?
Instructions for redirect usage are [here](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-js-initializing-client-applications) and instructions to collect logs [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logging.md)

**Comment by ss94866** [comment]
No, I didn't use handleRedirectPromise. I used the sample angular 7 example https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-samples/angular7-sample-app . I changed login method in app.module.ts from `  login() {
    const isIE = window.navigator.userAgent.indexOf('MSIE ') > -1 || window.navigator.userAgent.indexOf('Trident/') > -1;

    if (isIE) {
      this.authService.loginRedirect();
    } else {
      this.authService.loginPopup();
    }
  }`   to   `login() {
  //  const isIE = window.navigator.userAgent.indexOf('MSIE ') > -1 || window.navigator.userAgent.indexOf('Trident/') > -1;

   // if (isIE) {
      this.authService.loginRedirect();
   // } else {
     // this.authService.loginPopup();
    }
  }` and changed app.module.ts from  ` MsalModule.forRoot({
      auth: {
        clientId: '< clientid >',
        authority: "https://login.microsoftonline.com/common/",
        validateAuthority: true,
        redirectUri: "http://localhost:4200/",
        postLogoutRedirectUri: "http://localhost:4200/",
        navigateToLoginRequestUrl: true,
      },
      cache: {
        cacheLocation: "localStorage",
        storeAuthStateInCookie: isIE, // set to true for IE 11
      },
    },
      {
        **_popUp: !isIE_,**
        consentScopes: [
          "user.read",
          "openid",
          "profile",
          "api://a88bb933-319c-41b5-9f04-eff36d985612/access_as_user"
        ],
        unprotectedResources: ["https://www.microsoft.com/en-us/"],
        protectedResourceMap,
        extraQueryParameters: {}
      }
    )` to ` MsalModule.forRoot({
      auth: {
        clientId: '< clientid >',
        authority: "https://login.microsoftonline.com/common/",
        validateAuthority: true,
        redirectUri: "http://localhost:4200/",
        postLogoutRedirectUri: "http://localhost:4200/",
        navigateToLoginRequestUrl: true,
      },
      cache: {
        cacheLocation: "localStorage",
        storeAuthStateInCookie: isIE, // set to true for IE 11
      },
    },
      {
        **_popUp:  false,_**
        consentScopes: [
          "user.read",
          "openid",
          "profile",
          "api://a88bb933-319c-41b5-9f04-eff36d985612/access_as_user"
        ],
        unprotectedResources: ["https://www.microsoft.com/en-us/"],
        protectedResourceMap,
        extraQueryParameters: {}
      }
    )`

**Comment by ss94866** [comment]
on summary, I changed login in app.component.ts from loginPopup to loginRedirect and set popup to false. I hosted in the s3 and access with the hosted url. For popup it works fine. But in redirect login, I am able to see loop in the url as https://domain.com/index.html#id_token=ebyas...
also I am able to see login button in the page instead of logout.

**Comment by konstantin-msft** [comment]
Hi @ss94866. I wasn't able to reproduce the issue. Can you please share the msaljs logs? You can find instructions to collect logs [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logging.md).

**Comment by ss94866** [comment]
@konstantin-msft  Sorry for the delay. As it loops faster I cant able to see the console logs clearly. But, I tried to see it somehow. I cant able to see any logs in the console. I only able to see. this.router.url. and it loops at the following url https://domain.com/index.html#id_token=eybakn... We have built the angular 7 application locally, took the files in the dist folder and hosted in the s3 and created the private link and used aws load balancer to map the domain to /index.html. the application is hosted in the private environment.
![msalloop_issue](https://user-images.githubusercontent.com/68229944/236835226-95833714-851b-406c-a522-6eda6d0d99b6.png)
I have also attached the screenshot above. please refer it. It loops here. Kindly do the needful. 
![msal-portal-log](https://user-images.githubusercontent.com/68229944/236841234-f2c0d5a6-ff56-477b-9277-1ceb91cc4d6c.png)

**Comment by konstantin-msft** [comment]
@ss94866 You can enable "Preserve log" option in "Console" tab to persist logs on page redirect or navigation. Unfortunately, I won't be able to help without MSAL.js verbose logs.

![image](https://user-images.githubusercontent.com/119362382/236857120-fe52225d-e587-43a4-9c7d-57ca1e864f54.png)

**Comment by ss94866** [comment]
Thanks a lot!

@konstantin-msft 
I only have these libs in the sample application - [https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-angular-samples/angular7-sample-app/package.json](url) . I haven't installed @azure/msal-browser. It throws some error in my main application. I cant able to find the proper blog/doc to add log in the MsalModule which is in the @azure/msal-angular@1.1.2 

`    MsalModule.forRoot({
      auth: {
        clientId: 'clientid',
        authority: "https://login.microsoftonline.com/tenantid",
        validateAuthority: true,
        redirectUri: "http://localhost:4200/",
        postLogoutRedirectUri: "http://localhost:4200/",
        navigateToLoginRequestUrl: true,
      },
      cache: {
        cacheLocation: "localStorage",
        storeAuthStateInCookie: isIE, // set to true for IE 11
      },
    },
      {
        popUp: false,
        consentScopes: [
          "user.read",
          "openid",
          "profile",
          "api://something"
        ],
        unprotectedResources: ["https://www.microsoft.com/en-us/"],
        protectedResourceMap,
        extraQueryParameters: {}
      }
    )`

I use @azure/msal-angular@1.1.2 and msal@1.4.4 . Kindly share the reference for adding logs in the angular 7 application as I have only msal and @azure/msal-angular and I don't have @azure/msal-browser.

**Comment by konstantin-msft** [comment]
@ss94866 Logging is already enabled [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-angular-samples/angular7-sample-app/src/app/app.component.ts#L36) for `angular7-sample-app`. You should be able to capture the logs without making any changes.

**Comment by ss94866** [comment]
@hectormmg @konstantin-msft 
I have attached the log file you requested, Kindly check it.
[msallogs.txt](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/11426508/msallogs.txt)

Please note that I have AWS cloudwatch RUM in this sample application. So, You may see some logs related to AWS. 

You can see at the bottom of the txt file. The logs repeats due to the loops.

**Comment by konstantin-msft** [comment]
@ss94866 I can't see any MSAL.js logs in the attached file. Please make sure you have logging enabled. Please refer to [this sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-angular-samples/angular7-sample-app/src/app/app.component.ts#L36) for assistance.

**Comment by ss94866** [comment]
@konstantin-msft @hectormmg 
![MicrosoftTeams-image (29)](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/68229944/e1d09b13-2bb9-4131-8393-266dcdc50396)
I am able to see these logs when I use popup login, But for redirect login I can't able to see these logs.

**Comment by ss94866** [comment]
@konstantin-msft @hectormmg 
Please share the proper working sample for azure ad using redirect for angular 7 application. The sample we have in the Github repo uses popup for login. Please share the redirect working sample.

Thank you so much for the support !

**Comment by konstantin-msft** [comment]
@ss94866 `angular7-sample-app` already provides an option to login with [redirect API](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-angular-samples/angular7-sample-app/src/app/app.component.ts#L51) that can be enabled by tweaking the `isIE` flag.

**Comment by ss94866** [comment]
@konstantin-msft  Yes, I made those changes for login redirect which I posted on the top of the post. The code snippet that I used is on the top of this post. By using this code, I can't able to see the msal logs. But, I am able to see the msal logs by using pop up login. I also shared the screenshot of msal logs with popup login in the last post.

**Comment by hectormmg** [comment]
@ss94866 unfortunately msal-angular v1.x and msal.js v1.x are no longer receiving active support except for critical security upgrades. Please upgrade to our latest Angular library.
