### ISSUE TITLE
Angular 15.2.8 MSAL not compatible

### ISSUE THREAD

**Issue by ghost** [AzureAD/microsoft-authentication-library-for-js#5945]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.14.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.5.6

### Public or Confidential Client?

Confidential

### Description

Good Day

Could you urgently advise, I am busy developing an application and need to implement MSAL authentication on angular 15.2.8. 

I am getting the below error. 

This likely means that the library (@azure/msal-angular) which declares MsalModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

### Error Message

This likely means that the library (@azure/msal-angular) which declares MsalModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

### Msal Logs

/src/app/app.module.ts:29:0-49 - Error: Module not found: Error: Can't resolve '@azure/msal-angular' in 'C:\Dev Repos\PS Development (Git)\Selfservice\web\src\app'

Error: src/app/app.module.ts:33:89 - error NG6002: 'MsalModule' does not appear to be an NgModule class.

33   imports: [BrowserModule, AppRoutingModule, BrowserAnimationsModule, HttpClientModule, MsalModule],
                                                                                           ~~~~~~~~~~

  .yarn/__virtual__/@azure-msal-angular-virtual-70e602083a/0/cache/@azure-msal-angular-npm-2.5.6-d65118eb43-351fab48e1.zip/node_modules/@azure/msal-angular/msal.module.d.ts:5:22
    5 export declare class MsalModule {
                           ~~~~~~~~~~
    This likely means that the library (@azure/msal-angular) which declares MsalModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

### MSAL Configuration

```javascript
auth: {
    clientId: &quot;clientId&quot;,
    authority: &quot;https://login.microsoftonline.com/common/&quot;
  },
  cache: {
    cacheLocation: localStorage;
    storeAuthStateInCookie: false
  }
}
```

### Relevant Code Snippets

```javascript
This likely means that the library (@azure/msal-angular) which declares MsalModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
```

### Reproduction Steps

1. Create Angular Application with version 15.2.8
2. Use yarn as package manager

### Expected Behavior

To use the Microsoft Login as a popup to allow users to login to the application

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer

### Regression

@azure/msal-angular

### Source

Internal (Microsoft)

**Comment by sameerag** [comment]
@LexiPow Our current Angular library does not support `Ivy`, a related issue can be tracked here: #4298. We are currently working on adding this support.

@EmLauber @jo-arroyo Can you please help add more information?

**Comment by EmLauber** [comment]
Correct, MSAL.Angular v2 does not support Ivy. You can track #4298 for updates on when MSAL.Angular v3 is released which will have Ivy support. In the meantime, you can use MSAL.Angular v2 with Angular 14 with the View engineer. Closing this as a duplicate.
