### ISSUE TITLE
B2B SPA Angular signup page 

### ISSUE THREAD

**Issue by RedEyedDog** [AzureAD/microsoft-authentication-library-for-js#595]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[* ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

Hi, I'm looking to make a SPA Angular app with **B2B** login, similar to **https://github.com/Azure/active-directory-dotnet-graphapi-b2bportal-web**. Can you please tell me if this is possible and if so point me in the right direction.

Thank you

**Comment by pkanher617** [comment]
@RedEyedDog You can use the documentation available for application registration in the Azure portal: 

App Registration: https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-register-an-app

For a Single-Page Application (SPA), the registration is categorized as a web application. Once you have completed that registration, you will be able to use the client id and other information given to perform authentication with Azure AD. There is also more information about the B2B features available here: https://docs.microsoft.com/en-us/azure/active-directory/b2b/what-is-b2b

Please let us know if the linked steps are helpful, and if you had any issues.

**Comment by sameerag** [comment]
@RedEyedDog Hopefully the above comments from @pkanher617 are helpful. Closing this issue, please reachout in case you need more info.
