### ISSUE TITLE
Errors with Spanish names in the user object

### ISSUE THREAD

**Issue by jeverduzco** [AzureAD/microsoft-authentication-library-for-js#596]
## Errors with Spanish names in the user object

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome XX
- [ ] Firefox version XX
- [ ] IE version XX
- [x] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 0.2.4
</code></pre>

## The problem

The problem is this:

When I use the getUser() method to get the user information if the name has a Spanish character it looks bad.

Example:

Name in AD B2C; Jesús
Name obtained with getUser(); JesÃºs

## This is how it should work 

Characters should be displayed correctly with utf-8.

Example:

Name in AD B2C; Jesús
Name obtained with getUser(); Jesús

## Reproduction of the problem

To reproduce this bug is only necessary to have a name with Spanish characters and use the method getUser()

**Comment by jeverduzco** [comment]
I've been checking and found that there was already a previous thread with the same problem on #264 but why haven't you updated?

**Comment by sameerag** [comment]
@jeverduzco This is being tracked. The existing PR seems to have some build issues in travis, let me check the changes in detail and give you an ETA on when this would be integrated in the dev branch.

**Comment by jeverduzco** [comment]
Please @sameerag Because it's a really bad experience for my users :(

**Comment by jeverduzco** [comment]
Any ideas for when this list update? @navyasric 
This is very important to me because many of my users complain about it :(

**Comment by sameerag** [comment]
@jeverduzco Our next patch release will have this fix, tentatively in a week. Will update here once the release is made.

**Comment by sameerag** [comment]
#712 is now merged to dev @jeverduzco if you want to try the fix. We will soon have a patch release which would consist of this fix among others.

**Comment by jeverduzco** [comment]
I upgraded to version 1.0.1 and it worked perfectly. Thank you.

**Comment by sameerag** [comment]
@jeverduzco Awesome!
