### ISSUE TITLE
Verbose logs don't contain enough info when ClientAuthError: endpoints_resolution_error occurs

### ISSUE THREAD

**Issue by mstepanov-microsoft** [AzureAD/microsoft-authentication-library-for-js#5960]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.16.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Confidential

### Description

When the error occurs: "ClientAuthError: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientAuthError: openid_config_error: Could not retrieve endpoints. Check your authority and verify the .well-known/openid-configuration endpoint returns the required endpoints. Attempted to retrieve endpoints from: https://login.microsoftonline.com/[TENANT_ID]/v2.0/.well-known/openid-configuration\n    at ClientAuthError.AuthError [as constructor] (/app/node_modules/.pnpm/@azure+msal-common@11.0.0/node_modules/@azure/msal-common/src/error/AuthError.ts:49:9)\n    at new ClientAuthError (/app/node_modules/.pnpm/@azure+msal-common@11.0.0/node_modules/@azure/msal-common/src/error/ClientAuthError.ts:223:15)\n    at Function.ClientAuthError.createEndpointDiscoveryIncompleteError (/app/node_modules/.pnpm/@azure+msal-common@11.0.0/node_modules/@azure/msal-common/src/error/ClientAuthError.ts:269:16)\n    at Function.<anonymous> (/app/node_modules/.pnpm/@azure+msal-common@11.0.0/node_modules/@azure/msal-common/src/authority/AuthorityFactory.ts:56:35)\n    at step (/app/node_modules/.pnpm/@azure+msal-common@11.0.0/node_modules/@azure/msal-common/dist/index.cjs.js:79:23)\n    at Object.throw (/app/node_modules/.pnpm/@azure+msal-common@11.0.0/node_modules/@azure/msal-common/dist/index.cjs.js:60:53)\n    at rejected (/app/node_modules/.pnpm/@azure+msal-common@11.0.0/node_modules/@azure/msal-common/dist/index.cjs.js:51:65)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"

verbose logs don't contain enough information to understand source of the issue.

### Error Message

"ClientAuthError: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientAuthError: openid_config_error: Could not retrieve endpoints. Check your authority and verify the .well-known/openid-configuration endpoint returns the required endpoints. Attempted to retrieve endpoints from: https://login.microsoftonline.com/[TENANT_ID]/v2.0/.well-known/openid-configuration\n    at ClientAuthError.AuthError [as constructor] (/app/node_modules/.pnpm/@azure+msal-common@11.0.0/node_modules/@azure/msal-common/src/error/AuthError.ts:49:9)\n    at new ClientAuthError (/app/node_modules/.pnpm/@azure+msal-common@11.0.0/node_modules/@azure/msal-common/src/error/ClientAuthError.ts:223:15)\n    at Function.ClientAuthError.createEndpointDiscoveryIncompleteError (/app/node_modules/.pnpm/@azure+msal-common@11.0.0/node_modules/@azure/msal-common/src/error/ClientAuthError.ts:269:16)\n    at Function.<anonymous> (/app/node_modules/.pnpm/@azure+msal-common@11.0.0/node_modules/@azure/msal-common/src/authority/AuthorityFactory.ts:56:35)\n    at step (/app/node_modules/.pnpm/@azure+msal-common@11.0.0/node_modules/@azure/msal-common/dist/index.cjs.js:79:23)\n    at Object.throw (/app/node_modules/.pnpm/@azure+msal-common@11.0.0/node_modules/@azure/msal-common/dist/index.cjs.js:60:53)\n    at rejected (/app/node_modules/.pnpm/@azure+msal-common@11.0.0/node_modules/@azure/msal-common/dist/index.cjs.js:51:65)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"

### Msal Logs

[Wed, 19 Apr 2023 09:31:06 GMT] : @azure/msal-node@1.16.0 : Info - acquireTokenByClientCredential called
[Wed, 19 Apr 2023 09:31:06 GMT] : @azure/msal-node@1.16.0 : Verbose - initializeRequestScopes called
[Wed, 19 Apr 2023 09:31:06 GMT] : [c37acff0-b85d-4cab-800e-fe7a6ac8c257] : @azure/msal-node@1.16.0 : Verbose - buildOauthClientConfiguration called
[Wed, 19 Apr 2023 09:31:06 GMT] : [c37acff0-b85d-4cab-800e-fe7a6ac8c257] : @azure/msal-node@1.16.0 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/[TENANT_ID]/
[Wed, 19 Apr 2023 09:31:06 GMT] : [c37acff0-b85d-4cab-800e-fe7a6ac8c257] : @azure/msal-node@1.16.0 : Verbose - createAuthority called
[Wed, 19 Apr 2023 09:31:06 GMT] : @azure/msal-node@1.16.0 : Verbose - Attempting to get cloud discovery metadata in the config
[Wed, 19 Apr 2023 09:31:06 GMT] : @azure/msal-node@1.16.0 : Verbose - The host is included in knownAuthorities. Creating new cloud discovery metadata from the host.
[Wed, 19 Apr 2023 09:31:06 GMT] : @azure/msal-node@1.16.0 : Verbose - Found cloud discovery metadata in the config.

### MSAL Configuration

```javascript
{
    auth: {
        clientId,
        authority: authorityUrl,
        knownAuthorities: [authorityUrl],
        clientCertificate: {
            thumbprint,
            privateKey,
            x5c,
        },
    },
    system: {
        loggerOptions: {
            logLevel: LogLevel.Verbose,
            loggerCallback: (level, message, containsPii) => {
                if (containsPii) {
                    return;
                }
                switch (level) {
                    case LogLevel.Error:
                        logger.error(message);
                        return;
                    case LogLevel.Verbose:
                        logger.debug(message);
                        return;
                    case LogLevel.Warning:
                        logger.warn(message);
                        return;
                    default:
                        logger.info(message);
                        return;
                }
            },
            piiLoggingEnabled: false
        },
    },
}
```

### Relevant Code Snippets

```javascript
const clientConfig = {
    auth: {
        clientId,
        authority: authorityUrl,
        knownAuthorities: [authorityUrl],
        clientCertificate: {
            thumbprint,
            privateKey,
            x5c,
        },
    },
    system: {
        loggerOptions: {
            logLevel: LogLevel.Verbose,
            loggerCallback: (level, message, containsPii) => {
                if (containsPii) {
                    return;
                }
                switch (level) {
                    case LogLevel.Error:
                        logger.error(message);
                        return;
                    case LogLevel.Verbose:
                        logger.debug(message);
                        return;
                    case LogLevel.Warning:
                        logger.warn(message);
                        return;
                    default:
                        logger.info(message);
                        return;
                }
            },
            piiLoggingEnabled: false
        },
    },
};

const pca = new ConfidentialClientApplication(clientConfig);
const authResult = await pca.acquireTokenByClientCredential({
    scopes,
    azureRegion,
});
```

### Reproduction Steps

It should be enough to specify a wrong `authority` URL in the `clientConfig`, for example: `https://login.microsoftonline.com/WRONG_TENANT/`

### Expected Behavior

There should be verbose logs that contain enough information to figure out why the HTTP call failed

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Source

Internal (Microsoft)

**Comment by konstantin-msft** [comment]
Hi @mstepanov-microsoft. That's a good call, thank you. I have opened a PR to add verbose logging in accordance with your request.
