### ISSUE TITLE
documentation: token caching

### ISSUE THREAD

**Issue by aappddeevv** [AzureAD/microsoft-authentication-library-for-js#597]
I'm not convinced this is the right answer but the problem I want to solve is to improve the id_token and access_token refresh user experience. The current approach *appears* to be that when you call the id or access token API, if the token has not expired, return the cached token but potentially you need to popup/redirect to a login screen if a new id/access token is needed.

I'd like to place a high zindex model overlay on my app's content saying that you need to login again, that way, I can preserve app state and ensure no content is lost. But I need to do this prior to the expiration to have a smooth experience. I don't want to have a potential popup in the middle of a backend API call. I'm assuming that I need to use the acquireToken* API to obtain an access_token through for every API call I make to ensure that my API call has the latest token. I'm concerned that I could have some strange interactions if I try to set a timer on the access_token's expiration and try to issue a refresh prior to expiration in order to improve the user experience.

The alternative is to setup these callbacks myself fusing the expiration date (easy to do on the id_token) and also decode/setup a callback on the access_token.

**Comment by aappddeevv** [comment]
Hmm..naturally as soon as I wrote this I noticed some documentation on the SSO page.

**Comment by AndrewCraswell** [comment]
Another option would be to have a class which handles HTTP requests to your API that requires authentication. The class would be responsible for watching any HTTP requests which return a 401 error. It could then (a) store the failed HTTP request in a queue, (b) determine how to acquire the token and refresh it, then (c) replay any failed requests in the queue. This should give you a seamless user experience so long as you can refresh the token seamlessly. 

Not sure what framework you're using, but I know I've done similar code in AngularJS using Interceptors. I'm sure similar patterns exist for Angular, React, Vue, etc.

**Comment by sameerag** [comment]
@aappddeevv MSAL JS tokens expire every hour. acquireTokenSilent() call helps you with a silent refresh in the background without a popup. Combining this with the above suggestion from @AndrewCraswell may be something you are looking for.

We are also documenting our expiry_time for more clarity on questions like this.
Please reopen if your issue is still unaddressed.
