### ISSUE TITLE
Support for Demonstrating Proof-of-Possession (DPoP)

### ISSUE THREAD

**Issue by krischandra** [AzureAD/microsoft-authentication-library-for-js#5979]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

None

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

Hello Team,

Is DPoP implementation supported with Azure MSAL browser meaning Client will send public key to azure during code exchange with access token and The authorization server binds the public key to the access token and sends the response.
When we decode the Bearer Token, public key will be part under cnf

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by konstantin-msft** [comment]
Hi @krischandra.
Yes, we do support PoP flow. Please find a sample [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-browser-samples/VanillaJSTestApp2.0/app/pop) and the corresponding [test](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-browser-samples/VanillaJSTestApp2.0/app/pop/test/browser.spec.ts#L84) that validates public key is part of cnf.

**Comment by krischandra** [comment]
Thanks for the links shared. I am looking for **DPoP** implementation. And implementation will be
1) Generate Public Key and Private Key
2) Send Public Key to Azure during code exchange with Access token
3) Azure will add that public key to Access token under cnf
4) My Application will encode the payload using Private Key
5) My Application server will get public key from Access Token, and validate.

Please find the similar implementation for [Okta](https://developer.okta.com/docs/guides/dpop/-/main/#oauth-2-0-dpop-jwt-flow)

Thanks

**Comment by konstantin-msft** [comment]
What are we missing? Our PoP implementation returns a signed token and handles all of the steps you are asking for.

**Comment by muthurajanr63** [comment]
how long the pop token is valid? or client should set the expiration claims? also for POST request, will it need to add payload?

**Comment by krischandra** [comment]
Also, How does this solves Man in the Middle attack? Let's say someone stole my Access Token, and he can use his own msal library and use the stolen token and create pop token.

**Also the key difference is Public key is not part of Access (Bearer) token.** If Public key is part of access token, then we have one more validation if public key in access token matches with public key in POP token. That way it is more secure and we can ensure that someone else is not generating pop token with stolen Access token and pretending that he is legitimate user.

**Comment by konstantin-msft** [comment]
Thanks for sharing more details. It makes more sense now.
MSAL.js does not support DPoP at the moment. Unfortunately, at this point, we do not have immediate plans to support it.
cc @EmLauber for feature request.

**Comment by krischandra** [comment]
@konstantin-msft  Thanks for the confirmation. I put more analysis and see if we can achieve similar implementation.

While exchanging the code with token, i'll request for PoP token which has kid under cnf object which i'll be storing locally. When i want to generate PoP token using Signed Http Request. While implementing Signed Http Request, instead of creating new public key thumbprint, i'll use the thumbprint which i got from access token and generate PoP token.

At my application server, I'll re-generate SHA-256 hash of an cnf. jwk. If it matches with kid from header then It's a valid request.

Create PoP Token
```
const signedHttpRequest = new msal.SignedHttpRequest(popTokenRequest);
const publicKeyThumbprint = access_token_response.cnf.kid;
objClaim = {};
objClaim.exp = 1683422414
const popToken = await signedHttpRequest.signRequest(some_payload, publicKeyThumbprint, objClaim );

```
Validation at server:
```

const previousHash = access_token_response.cnf.kid;

const pubKeyThumprintObj = {
            e: pop_token. cnf. jwk.e,
            kty: pop_token. cnf. jwk.kty
            n: pop_token. cnf. jwk.n
}

const buffer = await crypto.subtle.digest('SHA-256', JSON.stringify(pubKeyThumprintObj));
const hashArray = new Uint8Array(buffer);
const serverGeneratedHashFromPoPCnf = urlEncodeArr(hashArray);

if (previousHash === serverGeneratedHashFromPoPCnf === base64Decode(pop_token_header. kid)) {
console.log('matched')
} else {
console.log('not_matched')
}

```
Thoughts on above?

Thanks.

**Comment by hectormmg** [comment]
> Also, How does this solves Man in the Middle attack? Let's say someone stole my Access Token, and he can use his own msal library and use the stolen token and create pop token.
> 
> **Also the key difference is Public key is not part of Access (Bearer) token.** If Public key is part of access token, then we have one more validation if public key in access token matches with public key in POP token. That way it is more secure and we can ensure that someone else is not generating pop token with stolen Access token and pretending that he is legitimate user.

@krischandra  MITM is mitigated in our PoP implementation because the req_cnf (public key thumbprint) sent to the authorization server is in fact returned as a claim in the access token. The validation service can check that the SHR signature (which is made with the matching private key MSAL stores) is valid using the public key. A copy of MSAL does not give an attacker the private key that was used to mint an access token.

What do you mean that the public key is not part of Access (Bearer) token?

**Comment by krischandra** [comment]
@hectormmg  That's correct If Request type is POP. This is what my understanding was.

1) Launch application.
2) Request Access token of type PoP.
    2.1) MSAL generates new Public Key and Private and stored in indexed DB (KID = 123)
    2.2) Return Access token which has Kid under cnf (public key thumbprint) (KID = 123)
3) Generate new pop token before making API call
    3.1) MSAL generates new Public Key and Private and stored in indexed DB (KID = 456)
     3.2) Generated PoP token with public key cnf

Now how can i validate if PoP token generated second time (Before making API call) belongs to my access token?

One solution i can see is, Instead of creating new Public and Private key for each request, i need to sign PoP token with secret that was generated during access token. As public key is part of access token i can validate and make sure public key in PoP token matches with Kid in access token

**Comment by hectormmg** [comment]
@krischandra as long as the request is the same and the access token hasn't been refreshed (hasn't expired and needed to be replaced in other words) the keypair being used to generate new SHRs (pop tokens) should be the same.

If the request is for a different access token (different scopes) or a token renewal, MSAL will generate a new keypair that the new token is bound to. The cnf in that access token will match the new public key, so the validation service can use that to verify the signature on the SHR.

Generating a new SHR/PoP token from a cached bound access token shouldn't result in new keys being generated unless that token has expired.

**Comment by krischandra** [comment]
Correct. As long as we use the same Public Key and Private key to generate the pop token we can achieve this. I just want to make sure what's the standard pattern here as there document says to create new Public key or Private key for each request

**Comment by hectormmg** [comment]
@krischandra the implementation may vary a bit but the important part is that the protocol is the same. The token is bound to the asymmetric keypair that MSAL uses at the moment of requesting the access token from the authorization service. Anytime that token is requested from MSAL, MSAL will use the same keys to sign the SHR/PoP token, which the resource server can use to verify the signature on the token and accept it.

**Comment by macupryk** [comment]
Does msal version 2.3.8 support dpop?

**Comment by alisha31084** [comment]
> [krishna (@krischandra)](https://github.com/krischandra) the implementation may vary a bit but the important part is that the protocol is the same. The token is bound to the asymmetric keypair that MSAL uses at the moment of requesting the access token from the authorization service. Anytime that token is requested from MSAL, MSAL will use the same keys to sign the SHR/PoP token, which the resource server can use to verify the signature on the token and accept it.

Hi, I'm facing issues on receiving a DPoP token via azure, from the client side, DPoP is implemented usign latest msal versions and the DPoP header is being sent with the token request. I've also completed the API-side prerequisites (accessTokenAcceptedVersion=2, and custom API scope assigned), but Entra ID continues to issue a Bearer token and throwing this error : "ClientAuthError: dpop_token_type_mismatch: See https://aka.ms/msal.js.errors#dpop_token_type_mismatch for details". Could you advise if any additional Azure configuration is needed?
