### ISSUE TITLE
MSAL Angular route guard with expired token causes application whitescreen

### ISSUE THREAD

**Issue by stweedie** [AzureAD/microsoft-authentication-library-for-js#598]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Library version
0.2.4

## Current behavior
When a user lets their session expire and loads a site with the MsalGuard configured, no route will load.

## Expected behavior
User is prompted for login (via popup or redirect), the same behavior as when there is no token present.

## Minimal reproduction of the problem with instructions
* Configure MSAL
* Use MsalGuard as canActivate guard for any feature route 
* Log in and activate the application at that route
* Leave browser open until token expires
* Refresh the page

[Issue occurs here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/5fb588912bc69d719f3a9decde4b3cdfa38dbc26/lib/msal-angular/src/msal-guard.service.ts#L61), where the library assumes the user is logged in because of the existence of a token, but attempts to silently retrieve a token will error out and be swallowed.

There is a workaround by setting up a subscription to the broadcastService and then manually calling login like this:

```ts
const sub = broadcastService.subscribe('msal:acquireTokenFailure', x => {
  sub.unsubscribe();
  msalService.loginRedirect();
});
```

I'm not sure that the event 'acquireTokenFailure' is unique to this workflow. This issue makes abstracting MSAL hard and isn't apparent until the proper circumstances are met. 
</code></pre>

**Comment by sameerag** [comment]
@stweedie  
- we usually advise the users to fall back to interactive calls as expanded [here](https://github.com/AzureAD/microsoft-authentication-library-for-js#3-get-an-access-token-to-call-an-api) when there is a failure seen in silent calls. The library does not handle this as there are some SPAs who would not like interaction triggered by msal.  However, I suspect if this is an option with router guards, I still see the GitHub [issue](https://github.com/angular/angular/issues/16211) raised on Angular open.

- Also, have you considered this pattern of checking the expiration of the token as an option for a canActivate guard before calling MSAL: [route](https://ryanchenkie.com/angular-authentication-using-route-guards); if I misunderstood the flow and the issue persists at msal level despite doing this, please update it here.

- If you are using interceptors, there is an existing issue #497 we plan to fix with the next major angular release (angular wrapper being compatible with latest msal 1.0.x).

Either way, I do get your frustration. The past few months we redesigned our API surface for msal core (1.0.x) and plan to release a new angular wrapper in sync with the core. We would like to incorporate use cases like this in the design. As a part of this effort, we are also tracking all basic angular issues with #786.

I am leaving this issue open until I can determine if there is some mitigation possible until the angular release is made.

**Comment by sameerag** [comment]
Closing this as we are tracking it with #786.
