### ISSUE TITLE
How to handle Single Sign Out across domains?

### ISSUE THREAD

**Issue by mattcheah** [AzureAD/microsoft-authentication-library-for-js#5981]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.31.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.4.6

### Public or Confidential Client?

Public

### Description

Not sure how to get Single Sign Out working across domains. I have Single Sign On working fine - user signs in on domain1.com and then when calling ssoSilent() on domain2.com, the user is automatically signed in. 

**Desired Behavior:** I'd like it if a user on domain1.com clicks `msalService.logoutRedirect()`, then if the user attempts to access a guarded route or call a protected resource on, they are unable to do so. 

I've followed the [front channel logout instructions here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md#front-channel-logout), and I have a front-channel logout URL set for both domains (domain1.com/logout and domain2.com/logout). These routes load the following copied from [the Angular 11 sample project ](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-angular-v2-samples/angular11-sample-app/src/app/logout/logout.component.ts) but I have also tried passing in the config object from the first link (posted in the relevant code snippets below) 

Cache location is also set to localStorage. 

Is it possible to do this cross-domain? I figured that since cross-domain SSO works, I might be able to make sign-off happen but I'm not sure where to go from here. Thanks all! 

### MSAL Configuration

```javascript
{
  auth: {
    clientId: 'my-client-id-asdf-asdfgasdf',
    authority: b2cPolicies.authorities.signUpSignIn.authority,
    knownAuthorities: ['myauthority.b2clogin.com],
    redirectUri: '/',
  },
  cache: {
    cacheLocation: BrowserCacheLocation.LocalStorage,
    storeAuthStateInCookie: isIE,
  },
  system: {
    loggerOptions: {
      loggerCallback: (logLevel, message, containsPii) => {
        console.log(message);
      },
      logLevel: LogLevel.Error,
      piiLoggingEnabled: false,
    },
  },
};
```

### Relevant Code Snippets

```javascript
const msal = new PublicClientApplication({
    auth: {
        clientId: "my-client-id"
    },
    system: {
        allowRedirectInIframe: true
    }
})

// Automatically on page load
msal.logoutRedirect({
    onRedirectNavigate: () => {
        // Return false to stop navigation after local logout
        return false;
    }
});
```

### Identity Provider

Azure B2C Basic Policy

### Source

External (Customer)

**Comment by konstantin-msft** [comment]
Hi @mattcheah.
Yes, cross-domain sign out is possible. However, you are [skipping the server sign-out](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md#skipping-the-server-sign-out) in your code snippet by performing local logout only (clearing cache). You can remove `onRedirectNavigate` callback to perform the server sing-out inside the iframe since you have `allowRedirectInIframe` set to true.

**Comment by mattcheah** [comment]
Thanks @konstantin-msft, 
I removed the `onRedirectNavigate` callback, was there anything else required? It looks like functionality remains the same on my end. 

Edited - Upon further review it looks like that Front Channel Logout URL that I set in the B2C Authentication page is NOT being hit. On page load I make a request to a logger which works just fine when I visit the URL myself, but when I manually logout from my app, that page isn't being hit. Any idea if i've missed a step somewhere? Thanks!

**Comment by konstantin-msft** [comment]
@mattcheah Can you please share the trace logs? Please refer to [this doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logging.md) for assistance.

**Comment by mattcheah** [comment]
Sure, this is what is logged after calling `logoutRedirect()`

```shell
main.ts:12 [Mon, 08 May 2023 15:33:23 GMT] : @azure/msal-browser@2.32.1 : Verbose - preflightBrowserEnvironmentCheck started
main.ts:12 [Mon, 08 May 2023 15:33:23 GMT] : @azure/msal-browser@2.32.1 : Verbose - preflightInteractiveRequest called, validating app environment
main.ts:12 [Mon, 08 May 2023 15:33:23 GMT] : @azure/msal-browser@2.32.1 : Trace - BrowserCacheManager.getTemporaryCache: No cache item found in local storage
main.ts:12 [Mon, 08 May 2023 15:33:23 GMT] : [25ba7fb2-6a6f-457f-accf-143bf01d9951] : msal.js.browser@2.32.1 : Verbose - logoutRedirect called
main.ts:12 [Mon, 08 May 2023 15:33:23 GMT] : [25ba7fb2-6a6f-457f-accf-143bf01d9951] : msal.js.browser@2.32.1 : Verbose - initializeLogoutRequest called
main.ts:12 [Mon, 08 May 2023 15:33:23 GMT] : [25ba7fb2-6a6f-457f-accf-143bf01d9951] : msal.js.browser@2.32.1 : Verbose - logoutHint was not set and account was not passed into logout request, logoutHint will not be set
main.ts:12 [Mon, 08 May 2023 15:33:23 GMT] : [25ba7fb2-6a6f-457f-accf-143bf01d9951] : msal.js.browser@2.32.1 : Verbose - Setting postLogoutRedirectUri to uri set on logout request
main.ts:12 [Mon, 08 May 2023 15:33:23 GMT] : [25ba7fb2-6a6f-457f-accf-143bf01d9951] : msal.js.browser@2.32.1 : Verbose - initializeServerTelemetryManager called
main.ts:12 [Mon, 08 May 2023 15:33:23 GMT] : @azure/msal-browser@2.32.1 : Info - Emitting event: msal:logoutStart
main.ts:12 [Mon, 08 May 2023 15:33:23 GMT] : @azure/msal-browser@2.32.1 : Verbose - Emitting event to callback a0ac5a43-5783-4a48-95df-21d5631c65f1: msal:logoutStart
main.ts:12 [Mon, 08 May 2023 15:33:23 GMT] : @azure/msal-angular@2.5.1 : Verbose - BroadcastService - msal:logoutStart results in setting inProgress from none to logout
main.ts:12 [Mon, 08 May 2023 15:33:23 GMT] : [25ba7fb2-6a6f-457f-accf-143bf01d9951] : msal.js.browser@2.32.1 : Verbose - No account provided in logout request, clearing all cache items.
main.ts:12 [Mon, 08 May 2023 15:33:23 GMT] : @azure/msal-browser@2.32.1 : Trace - BrowserCacheManager.getAccessTokenCredential: cache hit
main.ts:12 [Mon, 08 May 2023 15:33:23 GMT] : @azure/msal-browser@2.32.1 : Trace - BrowserCacheManager.getRefreshTokenCredential: cache hit
main.ts:12 [Mon, 08 May 2023 15:33:23 GMT] : @azure/msal-browser@2.32.1 : Trace - BrowserCacheManager.getIdTokenCredential: cache hit
main.ts:12 [Mon, 08 May 2023 15:33:23 GMT] : @azure/msal-browser@2.32.1 : Verbose - Deleting in-memory keystore asymmetricKeys
main.ts:12 [Mon, 08 May 2023 15:33:23 GMT] : @azure/msal-browser@2.32.1 : Verbose - In-memory keystore asymmetricKeys deleted
main.ts:12 [Mon, 08 May 2023 15:33:23 GMT] : @azure/msal-browser@2.32.1 : Verbose - Deleting in-memory keystore symmetricKeys
main.ts:12 [Mon, 08 May 2023 15:33:23 GMT] : @azure/msal-browser@2.32.1 : Verbose - In-memory keystore symmetricKeys deleted
main.ts:12 [Mon, 08 May 2023 15:33:23 GMT] : @azure/msal-browser@2.32.1 : Verbose - Deleting persistent keystore
main.ts:12 [Mon, 08 May 2023 15:33:23 GMT] : @azure/msal-browser@2.32.1 : Verbose - Persistent keystore deleted
main.ts:12 [Mon, 08 May 2023 15:33:23 GMT] : [25ba7fb2-6a6f-457f-accf-143bf01d9951] : msal.js.browser@2.32.1 : Verbose - getClientConfiguration called
main.ts:12 [Mon, 08 May 2023 15:33:23 GMT] : [25ba7fb2-6a6f-457f-accf-143bf01d9951] : msal.js.browser@2.32.1 : Verbose - getDiscoveredAuthority called
main.ts:12 [Mon, 08 May 2023 15:33:23 GMT] : [25ba7fb2-6a6f-457f-accf-143bf01d9951] : @azure/msal-browser@2.32.1 : Trace - PerformanceClient: Performance measurement started for standardInteractionClientGetDiscoveredAuthority
main.ts:12 [Mon, 08 May 2023 15:33:23 GMT] : [25ba7fb2-6a6f-457f-accf-143bf01d9951] : @azure/msal-browser@2.32.1 : Trace - PerformanceClient: Performance measurement for standardInteractionClientGetDiscoveredAuthority started
main.ts:12 [Mon, 08 May 2023 15:33:23 GMT] : @azure/msal-browser@2.32.1 : Trace - PerformanceClient: Adding static fields
main.ts:12 [Mon, 08 May 2023 15:33:23 GMT] : [25ba7fb2-6a6f-457f-accf-143bf01d9951] : msal.js.browser@2.32.1 : Verbose - Creating discovered authority with configured authority
main.ts:12 [Mon, 08 May 2023 15:33:23 GMT] : [25ba7fb2-6a6f-457f-accf-143bf01d9951] : msal.js.browser@2.32.1 : Verbose - Attempting to get cloud discovery metadata in the config
main.ts:12 [Mon, 08 May 2023 15:33:23 GMT] : [25ba7fb2-6a6f-457f-accf-143bf01d9951] : msal.js.browser@2.32.1 : Verbose - The host is included in knownAuthorities. Creating new cloud discovery metadata from the host.
main.ts:12 [Mon, 08 May 2023 15:33:23 GMT] : [25ba7fb2-6a6f-457f-accf-143bf01d9951] : msal.js.browser@2.32.1 : Verbose - Found cloud discovery metadata in the config.
main.ts:12 [Mon, 08 May 2023 15:33:24 GMT] : @azure/msal-browser@2.32.1 : Trace - BrowserCacheManager.setAuthorityMetadata called
main.ts:12 [Mon, 08 May 2023 15:33:24 GMT] : [25ba7fb2-6a6f-457f-accf-143bf01d9951] : @azure/msal-browser@2.32.1 : Trace - PerformanceClient: Performance measurement ended for standardInteractionClientGetDiscoveredAuthority: 373 ms
main.ts:12 [Mon, 08 May 2023 15:33:24 GMT] : [25ba7fb2-6a6f-457f-accf-143bf01d9951] : @azure/msal-browser@2.32.1 : Trace - PerformanceClient: Performance measurement for standardInteractionClientGetDiscoveredAuthority added/updated
main.ts:12 [Mon, 08 May 2023 15:33:24 GMT] : [25ba7fb2-6a6f-457f-accf-143bf01d9951] : msal.js.browser@2.32.1 : Verbose - Auth code client created
main.ts:12 [Mon, 08 May 2023 15:33:24 GMT] : @azure/msal-browser@2.32.1 : Info - Emitting event: msal:logoutSuccess
main.ts:12 [Mon, 08 May 2023 15:33:24 GMT] : @azure/msal-browser@2.32.1 : Verbose - Emitting event to callback a0ac5a43-5783-4a48-95df-21d5631c65f1: msal:logoutSuccess
main.ts:12 [Mon, 08 May 2023 15:33:24 GMT] : @azure/msal-browser@2.32.1 : Trace - BrowserCacheManager.getTemporaryCache: No cache item found in local storage
main.ts:12 [Mon, 08 May 2023 15:33:24 GMT] : @azure/msal-browser@2.32.1 : Trace - BrowserCacheManager.getTemporaryCache: No cache item found in local storage
```

**Comment by konstantin-msft** [comment]
@mattcheah I can't see anything suspicious in the MSAL.js logs. Can you please send me the whole [Fiddler trace](https://learn.microsoft.com/en-us/azure/azure-web-pubsub/howto-troubleshoot-network-trace) in an email specified in my Github profile description.

**Comment by mattcheah** [comment]
Thanks Konstantin - I sent it over. Much appreciated!

**Comment by tnorling** [comment]
@mattcheah I've reviewed your trace but there don't appear to be any logout calls in it. Can you record another trace and make sure to include the logout in it? Once you have it you can send it to our team at MsalJSHelp@microsoft.com. Thanks!

**Comment by mattcheah** [comment]
Thanks @tnorling, I've sent an email to that address with a new trace. 
The new trace seemed very similar to the old one and both contained calls to the Azure AD B2C OAuth 2.0 logout endpoint (v2) (with ?post_logout_redirect_uri=[...]&client-request-id=[...] query params), let me know if that's not what you're looking to see. Thanks!

**Comment by tnorling** [comment]
@mattcheah Thanks, I do see the calls to the logout endpoint now but do not see the iframed calls to your front channel logout urls. That makes this a service issue, could you please follow the directions at [this link](https://learn.microsoft.com/en-us/azure/active-directory-b2c/find-help-open-support-ticket) to open an issue with the B2C service team? They will need to review your app configuration and trace here to determine why that's not happening.

**Comment by kevinvugts** [comment]
> Hi @mattcheah. Yes, cross-domain sign out is possible. However, you are [skipping the server sign-out](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md#skipping-the-server-sign-out) in your code snippet by performing local logout only (clearing cache). You can remove `onRedirectNavigate` callback to perform the server sing-out inside the iframe since you have `allowRedirectInIframe` set to true.

Will this work for regular Azure AD as well? I followed the docs as described here: 
But it doesn't log out the session from the apps. 

Since localstorage/sessionStorage etc are tight to the same origin security principle of modern browsers you cannot clear browser storage from a different origin. 

So app 1 hosted on https://app-1.localhost:3001 cannot clear the browserstorage of https://app-2.localhost:3001 via an iframe. This is blocked by the browser. Am I correct?

At least, for me it doesn't work...
