### ISSUE TITLE
Alpha does not work with provideHttpClient

### ISSUE THREAD

**Issue by grosch-intl** [AzureAD/microsoft-authentication-library-for-js#5988]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

3.0.0-alpha.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.0-alpha.0

### Public or Confidential Client?

Public

### Description

If I try and use `provideHttpClient()` instead of importing `HttpClientModule` then things don't work.  There's not a token acquired and passed to the server.

### MSAL Configuration

```javascript
const publicClientApplication = new PublicClientApplication({
    auth: {
        clientId: environment.azure.clientId,
        authority: 'https://login.microsoftonline.com/...',
        redirectUri: window.location.origin
    },
    cache: {
        cacheLocation: BrowserCacheLocation.LocalStorage,
        storeAuthStateInCookie: false
    }
})
```

### Relevant Code Snippets

```javascript
bootstrapApplication(AppComponent, {
        providers: [
            importProvidersFrom(
                HttpClientModule,    // <=- Have to still do this
                ...
            ),
            // provideHttpClient(),      // <=- This doesn't work with the current msal interceptor.
```

### Reproduction Steps

See code snippet

### Expected Behavior

Shouldn't have to use the old HttpClientModule after angular 14.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by fayeBabacar78** [comment]
@grosch-intl Do you have a workaround solution? If you haved configured MsalInterceptor, can you share your configuration?

**Comment by grosch** [comment]
I'm just using the HttpClientModule until Microsoft provides an update.

**Comment by grosch-intl** [comment]
Any updates on this?

**Comment by jo-arroyo** [comment]
@grosch-intl Apologies for the delay, we will investigate this and update this thread when we have a fix.

**Comment by Marcel0024** [comment]
I manage to get it dynamic configurations to work with HttpClient, But then no other HttpClient calls work. 

@grosch-intl can you share your relevant main.ts

**Comment by grosch-intl** [comment]
@Marcel0024 I included that in the details of this ticket.

**Comment by fayeBabacar78** [comment]
@Marcel0024 have a look here #6080

For more details, check this repos out at https://github.com/mdddev/msal-b2c/blob/main/angular15-msal3-standalone

**Comment by grosch-intl** [comment]
@jo-arroyo Just updated to 3.0.0-beta.0 and still having the same issue.

**Comment by ckorherr** [comment]
I suggest applying `provideHttpClient(withInterceptorsFromDi())`. Implementing this approach worked successfully in my case.

**Comment by dzhavat** [comment]
Adding `provideHttpClient(withInterceptorsFromDi())` worked for us as well. We're on `3.0.0-beta.0`.

**Comment by grosch-intl** [comment]
@ckorherr Thanks, that works well.

@jo-arroyo Should we close this ticket and open a new one asking for an interceptor that doesn't require the DI to be used?

**Comment by jo-arroyo** [comment]
@grosch No need, we will track this issue as a feature request for an interceptor that doesn't require DI. Thanks
