### ISSUE TITLE
After user logout, any provided credential logs in the previous user

### ISSUE THREAD

**Issue by adamrkerr** [AzureAD/microsoft-authentication-library-for-js#5995]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.36.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.5.5

### Public or Confidential Client?

Public

### Description

I'm setting up MSAL for a web API and SPA for my client, following all the instructions in this repository: [Angular single-page application using MSAL Angular to sign-in users with Azure Active Directory and call a .NET Core web API](https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/tree/main/3-Authorization-II/1-call-api). Everything is configured as described, but we have noticed that after logging out, when returned to the Azure login screen, any credentials will allow the user to return to the app under the original identity. The issue was discovered in a local app under development, but upon investigation we found the same behavior in several deployed applications. This client uses Azure AD and Office 365 for their entire organization. Please see reproduction steps for details.

### MSAL Configuration

```javascript
{
    auth: {
      clientId: '{client id}',
      authority:
        'https://login.microsoftonline.com/{tenant}',
      redirectUri: 'http://localhost:4200/auth/login/aad/callback',
    },
    cache: {
      cacheLocation: 'localStorage',
      storeAuthStateInCookie: ISIE, // Set to true for Internet Explorer 11
    },
  }
```

### Relevant Code Snippets

```javascript
//From app.component.ts  
logout() {
    const currentAccount = this._msalService.instance.getActiveAccount() || this._msalService.instance.getAllAccounts()[0];
    this._msalService.logoutRedirect(
      {
        account: currentAccount,
        postLogoutRedirectUri: "http://localhost:4200"
      }
    );
  }
```

### Reproduction Steps

1. User arrives at the SPA root url
2. User is redirected to client's branded Microsoft SSO page
3. User logs in with client domain email ("user@contoso.com") and password
4. User is redirected to SPA
5. User selects "Log Out" from SPA menu
6. User is redirected to client's branded Microsoft SSO page and given a choice of account to log out
7. User selects account "user@contoso.com" for log out
8. Microsoft log out screen is displayed
9. User arrives at the SPA root, immediately redirected to client's branded Microsoft SSO page to select a new login
11. User's login ("user@contoso.com") is visible as a choice, but user selects "Use another account"
12. User enters bogus "fake12345@contoso.com" as login, clicks "Next" (The email must end in the client's domain to proceed. Behavior has also been observed when attempting to switch legitimate users in the same browser.)
13. User is redirected to the SPA without prompt for password, and shows still logged in as "user@contoso.com"

### Expected Behavior

User should be prompted for new password when logging in as a different user. User should not be allowed to continue as the previously logged in user.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

External (Customer)

**Comment by hectormmg** [comment]
@adamrkerr can you confirm that the MSAL cache is being cleared properly after logout? This sounds more like the user isn't properly logged out rather than an error in the login.

**Comment by adamrkerr** [comment]
> @adamrkerr can you confirm that the MSAL cache is being cleared properly after logout? This sounds more like the user isn't properly logged out rather than an error in the login.

Can you tell me how I could go about confirming that? I've had the browser Dev Tools open while observing the issue, but I can only see the page's local storage when I'm on the page. Since logout redirects me to Microsoft's SSO, everything is empty because I'm now on a different site. When I'm eventually returned to the page, I can't tell if what is in storage is new, or left over from the previous visit.

**Comment by hectormmg** [comment]
@adamrkerr one possible way is to look at the cached access token to see what its expiration time is. If the token after the logout flow has the same expiration and other varying attributes are the same, it's most likely not being cleared correctly.

**Comment by adamrkerr** [comment]
@hectormmg I repeated the steps I described above while observing my brower's local storage in Dev Tools. Here is what I saw:
First time:
Key: `{my oid}.{app reg id}-login.windows.net-accesstoken-...`
Expiration: 1683837461

Second time:
Key: `{my oid}.{app reg id}-login.windows.net-accesstoken-...`
Expiration: 1683838657

I noticed similar behavior with the `idtoken` key.

One thing I noticed while inspecting the JWT:
```
  "signin_state": [
    "inknownntwk"
  ]
```
The laptop where I observe this issue is on the client's domain, and I am signed in to Windows using account with the same domain. Since the client is using Azure AD, is it possible the auth flow is somehow pulling my windows credentials from my machine, regardless of what I enter?

**Comment by hectormmg** [comment]
> @hectormmg I repeated the steps I described above while observing my brower's local storage in Dev Tools. Here is what I saw: First time: Key: `{my oid}.{app reg id}-login.windows.net-accesstoken-...` Expiration: 1683837461
> 
> Second time: Key: `{my oid}.{app reg id}-login.windows.net-accesstoken-...` Expiration: 1683838657
> 
> I noticed similar behavior with the `idtoken` key.
> 
> One thing I noticed while inspecting the JWT:
> 
> ```
>   "signin_state": [
>     "inknownntwk"
>   ]
> ```
> 
> The laptop where I observe this issue is on the client's domain, and I am signed in to Windows using account with the same domain. Since the client is using Azure AD, is it possible the auth flow is somehow pulling my windows credentials from my machine, regardless of what I enter?

This was my second suspicion. This sounds like the browser is automatically performing SSO through your Windows account, bypassing the browser auth flow.

**Comment by adamrkerr** [comment]
For what it's worth, we've now observed the exact same behavior while logging in to the Azure Management Portal. Whatever is happening, I now doubt it's anything to do with our application code or configuration since we're observing it on Microsoft's own site.

**Comment by tnorling** [comment]
This sounds like a bug on the login server which is pulling your account from Windows. If you're using Chrome try this scenario in incognito (and make sure browser extensions are disabled). If you're no longer able to repro that's likely the case.

In any event, this is not something MSAL controls and we're going to be of limited help here. I would highly suggest opening a support ticket with your Azure subscription to get the best assistance with this.
