### ISSUE TITLE
Jest tests fail after upgrade to 3.0.0-alpha.0

### ISSUE THREAD

**Issue by Wooshaah** [AzureAD/microsoft-authentication-library-for-js#5996]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

3.0.0-alpha.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.0-alpha.0

### Public or Confidential Client?

Public

### Description

After upgrading from `"@azure/msal-angular": "^2.5.7",` and `"@azure/msal-browser": "^2.37.0",` to versions `3.0.0-alpha.0` the jest unit tests in our nx monorepo start failing

### Error Message

Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/username/Documents/Work/client/msal-jest-issue/node_modules/@azure/msal-browser/dist/index.d.ts:9
    import * as internals from "./internals";
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1796:14)

### MSAL Configuration

```javascript
not relevant
```

### Relevant Code Snippets

```javascript
app.component.ts

import { Component } from '@angular/core';
import { MsalService } from '@azure/msal-angular';

@Component({
  selector: 'msal-jest-issue-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  constructor(msalSerivce: MsalService) {}
}
```

app.component.spec.ts
```
import { TestBed } from '@angular/core/testing';
import { MsalService } from '@azure/msal-angular';
import { AppComponent } from './app.component';

describe('AppComponent', () => {
  beforeEach(async () => {
    await TestBed.configureTestingModule({
      declarations: [AppComponent],
      providers: [{ provide: MsalService, useValue: '' }],
    }).compileComponents();
  });
});
```
```


### Reproduction Steps

1. create new nx workspace
<img width="678" alt="image" src="https://user-images.githubusercontent.com/26672237/237026962-b1499a72-028a-4189-8c62-e9993b6799b0.png">
2. install `"@azure/msal-browser": "^3.0.0-alpha.0"` and `"@azure/msal-angular": "^3.0.0-alpha.0"`
3. inject MsalService into the app.component.ts (can also be another service from `@azure/msal-angular`)
`constructor(msalSerivce: MsalService) {}`
5. provide a mock for the MsalService in the app.component.spec.ts
`providers: [{ provide: MsalService, useValue: '' }],`
7. run tests

### Expected Behavior

Jest tests run successfully

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Other

### Regression

@azure/msal-browser 2.37.0, @azure/msal-angular 2.5.7

### Source

External (Customer)

**Comment by hectormmg** [comment]
@Wooshaah thanks for raising the issue, it seems there's an issue with which files are included in the published bundle. We're working on a fix that should be available on the next alpha release (alpha.3).

**Comment by hectormmg** [comment]
@Wooshaah [@azure/msal-browser@3.0.0-alpha.2](https://www.npmjs.com/package/@azure/msal-browser/v/3.0.0-alpha.2) has just been released with the fix for this issue, please test it out and let us know if it's resolved! Thanks.

**Comment by rafagsiqueira** [comment]
@hectormmg still getting the same error on 3.0.0-alpha-2 and 3.0.0-beta.1
