### ISSUE TITLE
JWT Bearer Authentication Parameters for Graph 2.0 endpoint token

### ISSUE THREAD

**Issue by hiraldesai** [AzureAD/microsoft-authentication-library-for-js#60]
Question: Is it possible to use the token obtained by `Msal.UserAgentApplication.acquireTokenSilent()` method to post as a bearer authorization header to authenticate against a dotnet core Web API? If so, what should I use as `JwtBearerOptions` in `app.UseJwtBearerAuthentication()` method?

I tried the standard options used by one of my other apps that uses Azure Active Directory. But getting the following error:
`IDX10503: Signature validation failed. Keys tried: 'Microsoft.IdentityModel.Tokens.X509SecurityKey , KeyId:`

**Comment by MariusSc** [comment]
This worked for me in case of AD B2C:

```
app.UseJwtBearerAuthentication(new JwtBearerOptions()
{
   MetadataAddress = string.Format("https://login.microsoftonline.com/{0}/v2.0/.well-known/openid-configuration?p={1}",
   Configuration["AAD:TenantId"], Configuration["AAD:Policy"]),
   AuthenticationScheme = Configuration["AAD:Policy"],
   Audience = Configuration["AAD:AppId"],
   AutomaticAuthenticate = true,
   AutomaticChallenge = true,
});
```
TenantId is the GUID of your AD tenant.
AppId is the GUID of your App.
Policy is the name of the sign-in or sign-up policy that you have configured in B2C.

**Comment by hiraldesai** [comment]
I don't have a B2C implementation, I have registered my app on https://apps.dev.microsoft.com/ as per instructions from [here](https://github.com/AzureADQuickStarts/AppModelv2-WebAPI-DotNet). There is no notion of `AAD:Policy` AFAIK. 

The only difference in my case is that my web API is dotnet core app so there is no `UseOAuthBearerAuthentication` and my front-end is my own implementation of angular2 service that uses [MSAL JS](https://github.com/AzureAD/microsoft-authentication-library-for-js).

**Comment by hiraldesai** [comment]
I ended up scrapping the idea of directly validating the graph token. Instead, I ended up validating the id token as usual and sent graph token as a custom header to my requests to the api.
