### ISSUE TITLE
Locale doesn't work completely using mkt parameter with extraQueryParameters while log out.

### ISSUE THREAD

**Issue by abhinavgurung** [AzureAD/microsoft-authentication-library-for-js#6001]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.28.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.4

### Public or Confidential Client?

Public

### Description

Using `mkt` parameter with `extraQueryParameters` does not work with log out completely.

while logging out, the first page of dialog box is in French but The page where it says
`hang on a moment while we sign you out` is still in english. Even though the `mkt` value is fr-CA.
Tested with `mkt=fr` and `mkt-fr-CA`

### MSAL Configuration

```javascript
const msalConfig = {
  auth: {
    clientId: config.msal.CLIENT_ID,
    authority: config.msal.AUTHORITY,
    redirectUri: config.msal.REDIRECT_URI,
    postLogoutRedirectUri: config.msal.POST_LOGOUT_REDIRECT_URI,
  },
  cache: {
    cacheLocation: 'localStorage',
    storeAuthStateInCookie: false,
  },
```

### Relevant Code Snippets

```javascript
instance.logoutPopup({
    extraQueryParameters: {
      mkt: `${msLang}`,
    },
  });
```

### Reproduction Steps

1. Change browser preferred language to something other than English (I changed it to fr-CA in Edge).
2. Go to app and trigger login popup with above configuration and log out.

### Expected Behavior

The log out popup text is in french due to the `mkt` parameter in the `extraQueryParameters`

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

External (Customer)

**Comment by hectormmg** [comment]
@abhinavgurung can you confirm the `mkt` attribute is being passed in the extra query params correctly? If it's being passed correctly you should consider bringing this up with the AAD service since MSAL doesn't have control over the login UI, it only creates and executes requests and then processes the token response.

**Comment by abhinavgurung** [comment]
@hectormmg I confirm that `mkt` parameter is being passed correctly. I even tried using booth `mkt=fr` and `mkt=fr-CA`. Since it is working partially as mentioned above, it also confirms it is receiving the `mkt` parameter but not changing locale for all pop up pages during log out.

**Comment by abhinavgurung** [comment]
@hectormmg Is there a particular Github Repo where I can raise this issue?

**Comment by jo-arroyo** [comment]
@abhinavgurung Apologies for the delay. Please open a ticket with [Azure Support](https://azure.microsoft.com/en-us/support/).
