### ISSUE TITLE
Multiple redirections to the azure sso page in a loop after authentication

### ISSUE THREAD

**Issue by rkreddy99** [AzureAD/microsoft-authentication-library-for-js#6005]
### Core Library

Passport Azure AD (passport-azure-ad)

### Core Library Version

4.3.5

### Wrapper Library

Passport

### Wrapper Library Version

0.6.0

### Public or Confidential Client?

Confidential

### Description

I am using passport-azure-ad lib to authenticate users on server side in Nodejs + Express server

When I enter the login url in the browser the redirection to the sso page is successfully done. After I select an user for authentication it is redirecting again to the sso page instead of going to the redirectUrl provided in the OIDCStrategy config.

I dont believe that the callbackurl provided in oidcStrategy is getting executed, as i am not able to see the logs from the function or error or anything.

If i remove the authentication middleware from the callbackurl endpoint, it redirecting to the "/" but with it in place, it is not redirecting the user to failureRedirect url as well, so i dont know whether the middleware check is getting completed or not

I have configured the api url as redirect url under web section in azure ad
and react app endpoints under spa section in azure ad

### Relevant Code Snippets

```javascript
export const oidcStrategy = new OIDCStrategy(
  {
    identityMetadata:
      "https://login.microsoftonline.com/<tenantId>/v2.0/.well-known/openid-configuration",
    clientID: "<clientid>", // Replace with your own client ID
    clientSecret: "<clienrtsecret>",
    responseType: "code id_token",
    responseMode: "form_post",
    redirectUrl: "http://localhost:9093/api/auth/callback/azure-ad", // Replace with your own redirect URL
    allowHttpForRedirectUrl: true,
    validateIssuer: false,
    passReqToCallback: true,
    scope: ["openid", "profile", "email"],
  },
  function (
    req,
    profile,
    done
  ) {
    if (!profile.oid) {
      return done(new Error("No oid found"), null);
    }
    return done(null, profile);
  }
);

// Serialize user
export const serializeUser = (user: any, done: any) => {
  done(null, user.oid);
};

// Deserialize user
export const deserializeUser = (id: any, done: any) => {
  done(null, user);
};






passport.use(oidcStrategy)
passport.use(serializeUser)
passport.use(deserializeUser)

router.get("/api/auth/login", passport.authenticate("azuread-openidconnect"));

// Callback URL for Azure AD to redirect to
router.post(
  "api/auth/callback/azure-ad",
  passport.authenticate("azuread-openidconnect", {
    authInfo: true,
    failureMessage: "Cannot login",
    failureRedirect: "<REACT_APP_URL>/error",
    successRedirect: "<REACT_APP_URL>/success",
  }),
  (req, res) => {
    res.redirect("/");
  }
);
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by rkreddy99** [comment]
@hectormmg , Do you have any idea on why this issue is caused, really need someone's help on this. thanks.

**Comment by hectormmg** [comment]
@rkreddy99 unfortunately passport-azure-ad is no longer supported, we only provide support for security updates.

**Comment by rkreddy99** [comment]
@hectormmg then what is the lib that i can use for server side authentication using azure ad in nodejs + react typescript app
