### ISSUE TITLE
Is there an option for admin consent?

### ISSUE THREAD

**Issue by JingyuShao** [AzureAD/microsoft-authentication-library-for-js#601]
Is there an optional to use admin consent with MSAL? Our scenario need to grant permission to a webapp to have admin access and make changes to tenants. Admin consent is needed. But not seeing an option with the extraQueryParameters. If not today, is it possible to add the support in near future? and what's the timeline looks like.

**Comment by visualjeff** [comment]
I think you'll find help on the wiki:  [https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Prompt-behavior](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Prompt-behavior)

**Comment by sameerag** [comment]
I believe this should be done during app registration if I am not wrong. @navyasric Can you confirm how and where admin consent can be set in our flow? Particularly is it in MSAL's scope?

**Comment by aashiman** [comment]
An admin will now be able to see the consent experience inline, would this work for your needs:
https://docs.microsoft.com/en-us/azure/active-directory/develop/application-consent-experience

**Comment by sameerag** [comment]
@JingyuShao Please reopen if the above data is not sufficient for your needs.

**Comment by antonGritsenko** [comment]
I think this still will not work in multi-tenant env. The workflow to grant using application registered in tenantA for user in tenantB is following:
1. Create app registration in tenantA, allow multi-tenancy, set required permission (for example, User.ReadWrite.All)
2. Create Web UI + msal.js, use client id from the step 1
3. Log in using account from tenant B. You will be prompted **only for basic consent** (view basic profile + sign in). It will be the same even if user is the tenant's B admin.
4. Send admin consents using URL https://login.microsoftonline.com/_tenant_b_id/adminConsent?client_id=_app_from_tenantA_clientid (here you will see the UI from @aashiman comment https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/601#issuecomment-481412868)

And looks like the step 4 is not possible using msal at all, at least I was not able to find how to do that.

**Comment by cvburgess** [comment]
Running into this issue as well, any advice?
