### ISSUE TITLE
Expiring access_token on Logout

### ISSUE THREAD

**Issue by ghost** [AzureAD/microsoft-authentication-library-for-js#6013]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.23.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.5.4

### Public or Confidential Client?

Public

### Description

I am wondering if there is a way to have MSAL expire the `access_token` after logging out.  I am not seeing any reference to that in the docs.  Currently, after a user logs out, I can continue to make API requests with that token until it naturally expires.  Is that the intended behavior?  

I am just doing a standard logoutRedirect, I have tried passing the account but that doesn't change anything.

### MSAL Configuration

```javascript
auth: {
    clientId: CLIENT_ID,
    authority: AUTHORITY,
    postLogoutRedirectUri: LOGOUT_REDIRECT,
  },
```

### Relevant Code Snippets

```javascript
const { instance } = useMsal();
  const azureLogout = async () => {
    try {
      await instance.logoutRedirect();
    } catch (err) {
      // handle error
    }
  };
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by hectormmg** [comment]
@sgreco-dev upon logout the token cache should be deleted, but the tokens aren't directly expired. Can you confirm the cache is being cleared after logout and no further authentication is performed?

**Comment by ghost** [comment]
@hectormmg Yes there is no other authentication being performed.  What is the best way for me to check if the cache is deleted?  I know everything is properly being cleared from the browser.  Our issue is that if for some reason someone got one of the tokens, they could continue to make API requests after the user had logged out.  This showed up in penetration testing.

**Comment by tnorling** [comment]
Access Tokens are stateless, they will be valid until expiration and cannot be revoked. This is why the lifetime is typically short (1 hr), if that still concerns you, you can [make the lifetime shorter](https://learn.microsoft.com/en-us/azure/active-directory/develop/configurable-token-lifetimes#access-tokens), but keep in mind this has a performance tradeoff.
