### ISSUE TITLE
Requesting clarity on forced Request scopes

### ISSUE THREAD

**Issue by MattWatt** [AzureAD/microsoft-authentication-library-for-js#6015]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.37.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

I'm looking for clarity around why the MSAL.js v2.x library is forcing request scopes, like "profile", on `loginPopup()` or `loginRedirect()`?

I'm trying to use the library on a public SPA application to request an id_token from an Azure B2C instance.  I don't manage or control that instance, but they've configured it so permissions are only allowed for "openid" and "offline_access" scopes, but not "profile".  No matter what specific request scopes I send to `loginPopup()`, the request is always made with the scopes: "openid", "profile", "offline_access".

BTW, it took me a lot of digging to discover that the "invalid_grant" error with code AADB2C90085 was a result of scope permissions.  That was not clear in the error description.

I'm seeing conflicting info from B2C examples for MSAL.js v2.x that just show the use of the "openid", as well as some of the FAQ information that seems less than clear around whether or why these scopes are forced.

I can however pinpoint the exact code block in the `msal-common` library that indeed shows that it is appended to every Auth Request.:
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/eeb136bcb815f32f931fda39d6f9e99d6be29a17/lib/msal-common/src/request/RequestParameterBuilder.ts#L86C12-L89

I'm now in a pickle since the library is forcing scopes I can't control and integrating with a partner that does not want to allow permissions to the "profile" scope.

I appreciate any help or clarity you can provide.

### MSAL Configuration

```javascript
{
	"auth": {
		"clientId": "7b695e04-fe0f-41d8-b16c-03207d6c3f31",
		"authority": "https://{omitted_tenant_name}.b2clogin.com/{omitted_tenant_name}.onmicrosoft.com/b2c_1a_signup_signin_drg",
		"knownAuthorities": [
			"{omitted_tenant_name}.b2clogin.com"
		],
		"cloudDiscoveryMetadata": "",
		"authorityMetadata": "",
		"redirectUri": "http://localhost:11400/oidc",
		"postLogoutRedirectUri": "http://localhost:11400/signout/oidc",
		"navigateToLoginRequestUrl": false,
		"clientCapabilities": [],
		"protocolMode": "AAD",
		"azureCloudOptions": {
			"azureCloudInstance": 0,
			"tenant": ""
		},
		"skipAuthorityMetadataCache": false
	},
	"cache": {
		"cacheLocation": "sessionStorage",
		"temporaryCacheLocation": "sessionStorage",
		"storeAuthStateInCookie": false,
		"secureCookies": false,
		"cacheMigrationEnabled": false
	},
	"system": {
		"tokenRenewalOffsetSeconds": 300,
		"preventCorsPreflight": false,
		"loggerOptions": {
			"logLevel": 3
		},
		"networkClient": {},
		"navigationClient": {},
		"loadFrameTimeout": 0,
		"windowHashTimeout": 60000,
		"iframeHashTimeout": 6000,
		"navigateFrameWait": 0,
		"redirectNavigationTimeout": 30000,
		"asyncPopups": false,
		"allowRedirectInIframe": false,
		"allowNativeBroker": false,
		"nativeBrokerHandshakeTimeout": 2000,
		"pollIntervalMilliseconds": 30,
		"cryptoOptions": {
			"useMsrCrypto": false
		}
	},
	"telemetry": {
		"application": {
			"appName": {omitted},
			"appVersion": {omitted}
		}
	}
}
```

### Relevant Code Snippets

```javascript
const request: msal.PopupRequest = {
            scopes: ["openid"],
            prompt: "login"
        };

        try {
            await this.msalInstance.loginPopup(request)
                .then(this.handleRequestResponse)
                .catch(error => {
                    this.logger.error("Login Response Error", error);
                });

            if(this.account) {
                // omitted
            }
        } catch(error) {
            this.logger.error("Login Popup Error", error);
        }
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by tnorling** [comment]
The short answer is that `openid`, `profile` and `offline_access` are required scopes because they provide artifacts the library relies on in most flows. I've confirmed with our B2C team that `profile` is allow listed service side. How did you determine that this error was due to the profile scope? Can you share a correlationId and timestamp for a failed request? I can pass it along to our service team to take a look.

**Comment by MattWatt** [comment]
Thank you for the reply.  A search for "invalid_grant" and that error code lead me to that conclusion, but mainly weighted by what I was being told by the administrators of the Azure B2C instance I was trying to connect with.

I freely admit now that I may have been mislead in that information.  I was told that our application wasn't configured correctly as a Public App, and that may in-fact be the source of the integration issue, and I've had some progress in getting tokens.

Here is a CorrelationId and Timestamp I have available, and is by no means the last instance, but AN instance of this error:
Correlation ID: 2363579d-fce3-4d3f-af61-f8caa0d67792
Timestamp: 2023-05-11 22:55:17Z

My question for whether and why those scopes were always forced is still one I wanted clarity on, since I was being told I should not request the "profile" scope.  I understand they're common scopes, and certainly make sense as "defaults".  I would hope there would be some flexibility in whether they are sent, particularly if the IdP does not want to given application permissions to them, like the "profile" scope.

Can you tell me if I could encounter errors in the flow if permissions were not given to one of those scopes?  I've made progress just today on my end and am receiving ID and Access tokens, but that's likely due to changes made on their side, and I can't be certain at this time.

Thanks for your response.

**Comment by tnorling** [comment]
> My question for whether and why those scopes were always forced is still one I wanted clarity on

Yes, they are always forced. They ensure that the service returns the necessary information MSAL.js needs in order to properly cache and lookup the tokens. The caveat here is that the B2C service in particular does not actually do anything with the profile scope, it is simply ignored. We made the decision (for better or worse) to include it on all flows to maintain a more consistent and streamlined developer experience across all providers, since the primary provider we support (AAD) _does_ require it.

> Can you tell me if I could encounter errors in the flow if permissions were not given to one of those scopes?

From talking with our B2C devs it sounds like it shouldn't matter if the profile scope is allow listed on your instance or not, it will always be ignored by the service. If an invalid scope is requested an invalid scope error would be thrown instead: AADB2C90117.

**Comment by MattWatt** [comment]
Thank you so much for that information, particularly this: 
> The caveat here is that the B2C service in particular does not actually do anything with the profile scope, it is simply ignored.

That would explain why they were pushing the question of why I needed to send that scope, but it sounds like this should be passively ignored, and not cause any errors, and any invalid scope issues would be related to AADB2C90117.

That answers all of my questions.

It might be useful for the behavior of the default scopes to be stated plainly on this documentation page:
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/resources-and-scopes.md

**Comment by tnorling** [comment]
> It might be useful for the behavior of the default scopes to be stated plainly on this documentation page: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/resources-and-scopes.md

I agree, I'll mark this as a documentation request and close once I have a chance to update it. Thanks!
