### ISSUE TITLE
MsalInterceptor not firing inside Lazy Loaded module

### ISSUE THREAD

**Issue by doug-williamson** [AzureAD/microsoft-authentication-library-for-js#6017]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.31.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.4.6

### Public or Confidential Client?

Confidential

### Description

I have a lazy loaded module that I navigate to after completing the SignUp (Azure) policy. This route is guarded (MsalGuard), but I'm not seeing the Authorization Bearer token injected automatically. I have to create a sessionStorage variable to temporarily store the AccessToken I'm given.

Is there something special I have to consider to get the MsalInterceptor to inject the token?

### MSAL Configuration

```javascript
export function MSALInstanceFactory(): IPublicClientApplication {
	return new PublicClientApplication({
		auth: {
			clientId: environment.msalConfig.auth.clientId,
			authority: environment.b2cPolicies.authorities.signIn.authority,
			redirectUri: environment.msalConfig.auth.logoutRedirectUri,
			postLogoutRedirectUri: environment.msalConfig.auth.logoutRedirectUri,
			knownAuthorities: [environment.b2cPolicies.authorityDomain],
			navigateToLoginRequestUrl: false
		},
		cache: {
			cacheLocation: BrowserCacheLocation.SessionStorage,
			storeAuthStateInCookie: isIE, // set to true for IE 11.
		},
		system: {
			loggerOptions: {
				loggerCallback,
				logLevel: LogLevel.Verbose,
				piiLoggingEnabled: false,
			},
		},
	});
}
```

### Relevant Code Snippets

```javascript
startTransactionPrep(token: string): Observable<any> {
		let tokenHeader = new HttpHeaders().set('Authorization', `Bearer ${this.storageService.getItem('AccessToken')}`);
		let transactionPrepUrl = `${this.baseUrl}/api/tprun/transactions/transaction-prep`;
		let tokenBody = { Token: token };

		return this.http.post(transactionPrepUrl, tokenBody, { headers: tokenHeader}).pipe(
			map((result: any) => { 
				return result; 
			}),
			catchError((error: HttpErrorResponse) => {				
				return throwError('Error: Error processing Transaction Prep ');
			})
		);
	}
```

### Identity Provider

Azure B2C Basic Policy

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
@doug-williamson I was not able to reproduce this. [I modified our Angular 14 sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/angular14-lazy-load/samples/msal-angular-v2-samples/angular14-rxjs7-sample-app) to lazy load the profile component and it appears to be working properly. Please take a look at that branch and see if that works for you. If you could put together a minimal repro and share a link we can take another look. Thanks!
