### ISSUE TITLE
MSAL how to store ID Token and Access Token in Secure Cookie

### ISSUE THREAD

**Issue by rsrinivasanhome** [AzureAD/microsoft-authentication-library-for-js#602]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version XX
- [x] Firefox version XX
- [ ] IE version XX
- [x] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: X.Y.Z

## Minimal reproduction of the problem with instructions

</code></pre>

**Comment by rsrinivasanhome** [comment]
We have been observing MSAL is storing the Access Token and ID Token in the local storage.  Is there any way to make it get stored in a secure cookie.

Will the below flag help
storeAuthStateInCookie(Optional): This flag was introduced in MSAL.js v0.2.2 as a fix for the authentication loop issues on IE and Edge. Please enable the flag storeAuthStateInCookie to true to take advantage of this fix. When this is enabled, MSAL.js will store the auth request state required for validation of the auth flows in the browser cookies. By default this flag is set to false.

**Comment by devragland** [comment]
any updates on this?

**Comment by sameerag** [comment]
Yes as in, storeAuthStateInCookie(Optional) is an additional option to the users (introduced for IE to resolve access across trusted zones) and can be used to store tokens in the cookies. Please try this if it helps your case.

**Comment by rsrinivasanhome** [comment]
We however see the session state (local storage) to still contain the access token and refresh token.  My expectation is they will be only stored in cookies and be secured .

**Comment by AndrewCraswell** [comment]
I don't think it's currently possible to use just a cookie. Looking at the code in the `UserAgentApplication` shows this is how it handles the `cacheLocation` parameter:

```
this._cacheLocation = cacheLocation;
    if (!this._cacheLocations[cacheLocation]) {
      throw new Error("Cache Location is not valid. Provided value:" + this._cacheLocation + ".Possible values are: " + this._cacheLocations.localStorage + ", " + this._cacheLocations.sessionStorage);
    }
    this._cacheStorage = new Storage(this._cacheLocation); //cache keys msal
```

It forces the `cacheLocation` to either be "sessionStorage" or "localStorage".

**Comment by sameerag** [comment]
@rsrinivasanhome  and @AndrewCraswell , Cookie is designed to be in addition to localstorage/sessionstorage, not as an alternative. It is introduced to solve an issue with IE [TrustedZones](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Known-issues-on-IE-and-Edge-Browser). Exclusive cookie storage only is not something that we supported in the past.

@navyasric is this something we have scope to support in future?

**Comment by Highspeed7** [comment]
It should allow HttpOnly cookies to be used and avoid localStorage and sessionStorage to avoid all the caveats regarding XSS. It's much easier to prevent CSRF with cookies then it is for HTML storage.

**Comment by sameerag** [comment]
@Highspeed7 We are in middle of a major update for the library and would love to consider this once we release the current in the works changes. @navyasric to add this in our road map and update this thread as and when we plan to support this.

**Comment by DarylThayil** [comment]
We are exploring other alternatives to in memory storage, will take this into account but closing for now.
