### ISSUE TITLE
Prevent console errors for the MSAL Angular AAD Errors

### ISSUE THREAD

**Issue by SamShekhovtsov** [AzureAD/microsoft-authentication-library-for-js#6038]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.33.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.5.3

### Public or Confidential Client?

Public

### Description

Hi. Is there is there any way to prevent errors returned from the Azure AAD login policy to appear in the brwser console?
For instance, I have the following error thrown in the console:
main.ts:11 ERROR ServerError: access_denied: AADB2C90091: The user has cancelled entering self-asserted information.

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by tnorling** [comment]
MSAL doesn't log anything unless you've explicitly configured logging when instantiating `PublicClientApplication`. Please check that you haven't configured logging, that your app isn't logging and that you are catching errors thrown by our APIs.
