### ISSUE TITLE
Does the msal-react library automatically refreshes the token?

### ISSUE THREAD

**Issue by Ashutosh2547** [AzureAD/microsoft-authentication-library-for-js#6039]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.33.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.5.3

### Public or Confidential Client?

Public

### Description

**Does the msal-react library automatically refreshes the token?**
I am using Azure app registration, but can see only access token as a part of response returned by "acquireTokenSilent". Access token lifetime (as per jwt.io) looks like 1.5 hours.
How does the token refresh work here?
Do we get a new token after 1.5 hours of does the user logout? I am using web api at backend which are getting authorized with the JWT generated on frontend. Will my API start giving 401 after 1.5 hours?

### MSAL Configuration

```javascript
Not a configuraiton issue
```

### Relevant Code Snippets

```javascript
Using this to get the access token
 instance.acquireTokenSilent({
                scopes: ["User.Read"],
                account: account
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by tnorling** [comment]
Please see [this document](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/token-lifetimes.md#token-renewal). The acquireTokenSilent API will not return an expired token. It will make a best effort attempt to get you a fresh token silently (either from the cache or by exchanging a refresh token for new access tokens) and if it is unable to will throw an error describing why. Typically this would be an `InteractionRequired` error which your application should catch and invoke `acquireTokenRedirect` or `acquireTokenPopup` to refresh your tokens.

**Comment by Ashutosh2547** [comment]
Thank you for pointing me to the right direction.
