### ISSUE TITLE
Latest @azure/msal-angular alpha has redirect loop for existing sessions

### ISSUE THREAD

**Issue by NateRadebaugh** [AzureAD/microsoft-authentication-library-for-js#6044]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

3.0.0-alpha.2

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.0-alpha.2

### Public or Confidential Client?

Public

### Description

Attempting to use the site with Angular 16 and `@azure/msal-angular` has issues.
* When accessing from an "incognito" window, everything works just fine
* However, when accessing from an existing or expired session, a redirect loop occurs:
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/130445/afaaa661-8094-491b-b34a-fb25776182c0)

Eventually I get stuck at:
https://login.microsoftonline.com/common/webbridgereprocess
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/130445/4da512ff-e060-4d7d-aece-bc5f7b7824ca)

### MSAL Configuration

```javascript
{
  auth: {
    clientId: `${environment.auth.adfs.clientId}`,
    authority: `https://login.microsoftonline.com/${environment.auth.adfs.tenantId}/`,
    redirectUri: `https://${document.location.host}/`,
  },
  cache: {
    cacheLocation: BrowserCacheLocation.LocalStorage,
    storeAuthStateInCookie: isIE, // set to true for IE 11
  },
}
```

### Relevant Code Snippets

```javascript
const scopes = ['user.read'];
public async login() {
  await this.msalService.instance.handleRedirectPromise();
  await this.msalService
    .loginRedirect({
      scopes: scopes,
      authority: `https://login.microsoftonline.com/${environment.auth.adfs.tenantId}/`,
      redirectUri: `https://${document.location.host}/`,
    })
    .toPromise();
}
```

### Reproduction Steps

1. Navigate to home page on Angular 16 and latest msal alpha.
2. Log in and see site

### Expected Behavior

Login should work the same for angular 16 + latest msal alpha as it does for angular 15 and latest msal stable.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge

### Regression

@azure/msal-* 2.5.7

### Source

External

**Comment by tnorling** [comment]
This is a known bug with a new security feature we're enabling by default in v3. The server team is working on a fix and this will resolve itself once that rolls out. In the meantime, you can turn off this feature to unblock your testing and revert to the v2 behavior by [disabling the `allowNativeBroker` flag](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-v3-upgrade-guide.md#the-allownativebroker-flag). We'll update this issue when the fix has rolled out so you can turn it back on.

**Comment by NateRadebaugh** [comment]
Thanks this worked.

**Comment by tnorling** [comment]
We've reverted the change in default value of the `allowNativeBroker` flag in v3.0.0 so this should no longer be an issue by default. After the server bugs mentioned are resolved we will re-enable this flow in a v4 release. Closing for now.
