### ISSUE TITLE
Can't use VanillaJSTestApp2.0 Examples, missing files

### ISSUE THREAD

**Issue by kaangoksal** [AzureAD/microsoft-authentication-library-for-js#6047]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

latest

### Wrapper Library

Not Applicable

### Wrapper Library Version

barebones files

### Public or Confidential Client?

Public

### Description

I'm trying to use this sample 

`samples/msal-browser-samples/VanillaJSTestApp2.0/app/default`

there are missing files in nearly every index.html file in VanillaJSTestApp2.0 folder.

```
../../lib/msal-browser.js
../../lib/index.js
```

Following instructions are not valid

```
- You can run any VanillaJSTestApp2.0 sample by changing the `authConfig.js` file in the respective folder to match your app registration and running the `npm` command `npm start -- -s <sample-name> -p <port>` in the VanillaJSTestApp2.0 folder.
- You can run the TypescriptTestApp2.0 sample by changing the `AuthModule.ts` file to match your app registration and running the `npm` command `npm start` in the TypescriptTestApp2.0 folder.
```

### Error Message
```
The resource from “http://localhost:30662/lib/index.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
[localhost:30662](http://localhost:30662/)
15:32:58.399 Loading failed for the <script> with source “http://localhost:30662/lib/index.js”. [localhost:30662:8:60](http://localhost:30662/)
15:32:58.439
Uncaught ReferenceError: msal is not defined
    <anonymous> http://localhost:30662/authConfig.js:13
[authConfig.js:13:13](http://localhost:30662/authConfig.js)
15:32:58.439
Uncaught ReferenceError: msal is not defined
    <anonymous> http://localhost:30662/auth.js:16
[auth.js:16:19](http://localhost:30662/auth.js)
15:33:07.603
Uncaught (in promise) ReferenceError: can't access lexical declaration 'myMSALObj' before initialization
    signIn http://localhost:30662/auth.js:49
    onclick http://localhost:30662/:1
```    
    
    
   I can also see that the server (npm start) replied with a 404 to /lib/index.js

### MSAL Configuration

```javascript
couldn't even get to that point yet
```

### Relevant Code Snippets

```javascript
all from this repo, no change
```

### Reproduction Steps
```
1) pull repo 
2) cd samples/msal-browser-samples/VanillaJSTestApp2.0/
3) npm i
4) npm start 
5) Navigate the port shown on the console, localhost:30662
```

### Expected Behavior

I expect files to be present and example working out of the box.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Edge

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
These are local development samples for developing MSAL.js itself, you have to build the library first locally for the files to be available. That said these should all be `msal-browser.js` rather than `index.js`. I'll make a note to fix those paths.

If you would like a more straightforward tutorial I would suggest you start [here](https://learn.microsoft.com/en-us/azure/active-directory/develop/single-page-app-quickstart?pivots=devlang-javascript) or a more in-depth tutorial [here](https://github.com/Azure-Samples/ms-identity-javascript-tutorial/tree/main)
