### ISSUE TITLE
Cannot use JSDOM in combination with MSAL

### ISSUE THREAD

**Issue by jappe999** [AzureAD/microsoft-authentication-library-for-js#605]
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report  
- [ ] Performance issue
- [ ] Feature request
- [ ] Documentation issue or request
- [x] Other... Please describe:
Conflict with another package.

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX
- [x] Terminal/Console, no browser, UI

## Library version

Library version: 0.2.4

## Current behavior

If I use JSDOM, the testing library throws this error:
```
ERROR in node_modules/@types/jsdom/ts3.1/index.d.ts(118,18): error TS2430: Interface 'DOMWindow' incorrectly extends interface 'Window'.
  Types of property 'CustomEvent' are incompatible.
    Type '{ new <T>(typeArg: string, eventInitDict?: CustomEventInit<T>): CustomEvent<T>; prototype: CustomEvent<any>; }' is missing the following properties from type 'CustomEvent<any>': detail, initCustomEvent, bubbles, cancelBubble, and 20 more.
```

JSDOM works as it should, but MSAL declares a global interface Window that JSDOM automatically uses. The declaration can be found in [UserAgentApplication.ts](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/src/UserAgentApplication.ts)

## Expected behavior

JSDOM should implement the default interface. Not that of MSAL.

## Minimal reproduction of the problem with instructions

1. Create an Angular project.
2. Install `@azure/msal-angular` and `jsdom`.
3. Write a test using JSDOM.
4. Run the test.
5. See it fail.

**Comment by sameerag** [comment]
May not be angular specific issue. @jasonnutter any ideas?

**Comment by jasonnutter** [comment]
Right, I imagine this isn't Angular specific. That is seemingly strange behavior from JSDOM, though. I'll create a ticket in our backlog to investigate.

**Comment by jasonnutter** [comment]
MSAL Browser v2 should not have this problem, closing.
