### ISSUE TITLE
Provide Support for form_post response_mode 

### ISSUE THREAD

**Issue by douglas-woods** [AzureAD/microsoft-authentication-library-for-js#6050]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL React (@azure/msal-react)

### Public or Confidential Client?

Public

### Description

Recently Azure AD has increased the size of various tokens. See https://techcommunity.microsoft.com/t5/microsoft-entra-azure-ad/azure-ad-b2c-authorization-code-and-refresh-token-size-increase/m-p/3770890

As a result the size of URLS returned to the client app after auth can become very long. In our case that then triggered firewall rules that rejected the calls. :-(

Microsoft now recommed using a response_mode of form_post to remove the issue.

Our React SPA aap is using
    "@azure/msal-browser": "^2.37.0",
    "@azure/msal-react": "^1.5.7",

### Source

External (Customer)

**Comment by tnorling** [comment]
form_post is not possible for SPA apps unfortunately, as they run completely client-side.
