### ISSUE TITLE
Embedded Registration 

### ISSUE THREAD

**Issue by hansakaRightS** [AzureAD/microsoft-authentication-library-for-js#6059]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.32.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.1.2

### Public or Confidential Client?

Public

### Description

We have implemented the embedded registration in out application as a feature. we have configured the headers and were able to load the registration inside the iframe.

after a success full registration azure b2c redirects to the redirect uri inside the iframe and then we reload the parent frame to continue the flow. after this the application redirects one more time before we get authenticated. 

Is there a way to get the authentication details in a single redirection?

### MSAL Configuration

```javascript
auth: {
        clientId: clientId,
        authority: "B2C_1A_SIGNUP_SIGNIN",
        redirectUri: '/',
        navigateToLoginRequestUrl: false
    },
    cache: {
        cacheLocation: "LocalStoarage",
        storeAuthStateInCookie: false
    }
```

### Relevant Code Snippets

```javascript
<iframe 
    id="embeddedRegisterIframe" 
    frameborder="0" 
    scrolling="no" 
    [src]=" uri" 
    style=" width: 100%; height: 100%;"></iframe>
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by lalimasharda** [comment]
Just to be clear, are you talking about embedding the Azure AD B2C sign-in user interface in your application?

**Comment by hansakaRightS** [comment]
https://learn.microsoft.com/en-us/azure/active-directory-b2c/embedded-login?pivots=b2c-custom-policy
 we  have implemented this but, after `window.top.location.reload();` we are getting too many redirection before we are actually logged into the app. we want to reduce this redirections.

**Comment by lalimasharda** [comment]
Can you please share network logs and MSAL verbose logs from the console? We have documentation on [Logging](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/25b5b256d03ccc93c2cbb6b042af519601957e2b/lib/msal-browser/docs/logging.md?plain=1#L1).
