### ISSUE TITLE
Getting Unhandled rejection UnsupportedAuthorityValidation when using latest version of MSAL.js for B2C authentication. 

### ISSUE THREAD

**Issue by byteoriginkiran** [AzureAD/microsoft-authentication-library-for-js#606]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ x] Edge version XX
- [ ] Safari version XX

## Library version
0.2.4 - 0.1.2
<pre><code>
Library version: X.Y.Z

Yes behavior is still in recent version

## Current behavior

Getting error "Unhandled rejection UnsupportedAuthorityValidation" in debug console and auth  is failing. I got authentication working as expected using 0.1.1 library as described in the B2C sample. https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp/blob/master/index.html but versions after that are throwing above error. Even the B2C sample is referencing outdated version which is 2 years old.

Other thread with similar issue but cannot find solution:
https://social.msdn.microsoft.com/Forums/SECURITY/en-US/612dbdd7-1d83-46b2-ba4f-08cdf87c5126/unsupportedauthorityvalidation-error-when-configuring-the-sample-code-to-use-my-own-azure-ad-b2c?forum=WindowsAzureAD

## Minimal reproduction of the problem with instructions

1)Use the version 0.1.1 of msal.js  library and try to do B2C auth as described in the B2C auth sample auth by updating with your clientid and authority using your tenant id. auth works as expected.
2) Updated the sample to use the latest version of msal.js. auth fails with error "Unhandled rejection UnsupportedAuthorityValidation" in browser dev console.

</code></pre>

**Comment by byteoriginkiran** [comment]
I haven't recieved any response so. can someone for microsoft support confirm if there is a existing defect in library or if this is a config issue. microsoft's own b2c  working samples showing using outdated libraries that is old than 2 years is frustrating.

**Comment by stijnvanbossuyt** [comment]
You can pass `{ validateAuthority: false, },` when initialising **Msal.UserAgentApplication**

**Comment by sameerag** [comment]
@byteoriginkiran Since B2C authority validation is not possible (as there will be virtually 100s of domains to support in theory), we are currently supporting any B2C endpoint by setting "validateAuthority: false" in the configuration for MSAL JS. 

We are working on formulating a better interface for Authority validation and would announce as and when we are ready. Until then please use the above setting.

MSAL JS has upgraded to 1.0.x, please try it out as it is a more comprehensive API surface as opposed to older versions.
