### ISSUE TITLE
400 Bad Request - Wrong URL Azure AD B2C redirect to URL login.microsoftonline.com

### ISSUE THREAD

**Issue by asmurph** [AzureAD/microsoft-authentication-library-for-js#6063]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Core Library Version

2.36.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.5.7

### Public or Confidential Client?

Public

### Description

After upgrading to both Msal-Browser and Msal-React I'm getting an error with redirecting to a custom Azure B2C policy
According to this URL - login.microsoftonline.com was retired on August 31 2022?
https://azure.microsoft.com/en-us/updates/update-apps-using-azure-ad-b2c-to-new-redirect-b2clogincom/

### Error Message

FetchClient.ts:   GET https://login.microsoftonline.com/common/discovery/instance?api-version=1.1&authorization_endpoint=https://asmurph.b2clogin.com/asmurph.onmicrosoft.com/b2c_1a_signup_signin/oauth2/v2.0/authorize 400 (Bad Request)

### Msal Logs

FetchClient.ts:24     GET https://login.microsoftonline.com/common/discovery/instance?api-version=1.1&authorization_endpoint=https://asmurph.b2clogin.com/asmurph.onmicrosoft.com/b2c_1a_signup_signin/oauth2/v2.0/authorize 400 (Bad Request)
(anonymous) @ FetchClient.ts:24
step @ vendors~main.chunk.js:210
(anonymous) @ vendors~main.chunk.js:141
(anonymous) @ vendors~main.chunk.js:113
__awaiter @ vendors~main.chunk.js:92
FetchClient.sendGetRequestAsync @ FetchClient.ts:21
(anonymous) @ Authority.ts:582
step @ MathUtils.ts:24
(anonymous) @ MathUtils.ts:24
(anonymous) @ MathUtils.ts:24
__awaiter @ MathUtils.ts:24
Authority.getCloudDiscoveryMetadataFromNetwork @ Authority.ts:568
(anonymous) @ Authority.ts:500
step @ MathUtils.ts:24
(anonymous) @ MathUtils.ts:24
(anonymous) @ MathUtils.ts:24
__awaiter @ MathUtils.ts:24
Authority.updateCloudDiscoveryMetadata @ Authority.ts:471
(anonymous) @ Authority.ts:294
step @ MathUtils.ts:24
(anonymous) @ MathUtils.ts:24
(anonymous) @ MathUtils.ts:24
__awaiter @ MathUtils.ts:24
Authority.resolveEndpointsAsync @ Authority.ts:283
(anonymous) @ AuthorityFactory.ts:55
step @ MathUtils.ts:24
(anonymous) @ MathUtils.ts:24
(anonymous) @ MathUtils.ts:24
__awaiter @ MathUtils.ts:24
AuthorityFactory.createDiscoveredInstance @ AuthorityFactory.ts:29
(anonymous) @ StandardInteractionClient.ts:227
step @ vendors~main.chunk.js:210
(anonymous) @ vendors~main.chunk.js:141
(anonymous) @ vendors~main.chunk.js:113
__awaiter @ vendors~main.chunk.js:92
StandardInteractionClient.getDiscoveredAuthority @ StandardInteractionClient.ts:208
(anonymous) @ StandardInteractionClient.ts:147
step @ vendors~main.chunk.js:210
(anonymous) @ vendors~main.chunk.js:141
(anonymous) @ vendors~main.chunk.js:113
__awaiter @ vendors~main.chunk.js:92
StandardInteractionClient.getClientConfiguration @ StandardInteractionClient.ts:143
(anonymous) @ StandardInteractionClient.ts:133
step @ vendors~main.chunk.js:210
(anonymous) @ vendors~main.chunk.js:141
(anonymous) @ vendors~main.chunk.js:113
__awaiter @ vendors~main.chunk.js:92
StandardInteractionClient.createAuthCodeClient @ StandardInteractionClient.ts:129
(anonymous) @ RedirectClient.ts:56
step @ vendors~main.chunk.js:210
(anonymous) @ vendors~main.chunk.js:141
fulfilled @ vendors~main.chunk.js:95
Promise.then (async)
step @ vendors~main.chunk.js:110
fulfilled @ vendors~main.chunk.js:95
Promise.then (async)
step @ vendors~main.chunk.js:110
(anonymous) @ vendors~main.chunk.js:113
__awaiter @ vendors~main.chunk.js:92
RedirectClient.acquireToken @ RedirectClient.ts:35
(anonymous) @ ClientApplication.ts:313
step @ vendors~main.chunk.js:210
(anonymous) @ vendors~main.chunk.js:141
(anonymous) @ vendors~main.chunk.js:113
__awaiter @ vendors~main.chunk.js:92
ClientApplication.acquireTokenRedirect @ ClientApplication.ts:280
(anonymous) @ PublicClientApplication.ts:71
step @ vendors~main.chunk.js:210
(anonymous) @ vendors~main.chunk.js:141
(anonymous) @ vendors~main.chunk.js:113
__awaiter @ vendors~main.chunk.js:92
PublicClientApplication.loginRedirect @ PublicClientApplication.ts:68
(anonymous) @ useAuthLogin.ts:44
onClick @ index.tsx:120
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4070
executeDispatch @ react-dom.development.js:8243
processDispatchQueueItemsInOrder @ react-dom.development.js:8275
processDispatchQueue @ react-dom.development.js:8288
dispatchEventsForPlugins @ react-dom.development.js:8299
(anonymous) @ react-dom.development.js:8508
batchedEventUpdates$1 @ react-dom.development.js:22396
batchedEventUpdates @ react-dom.development.js:3745
dispatchEventForPluginEventSystem @ react-dom.development.js:8507
attemptToDispatchEvent @ react-dom.development.js:6005
dispatchEvent @ react-dom.development.js:5924
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
discreteUpdates$1 @ react-dom.development.js:22413
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
index.js:1 Auth Error: ClientAuthError: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter.
    at ClientAuthError.AuthError [as constructor] (AuthError.ts:49:1)
    at new ClientAuthError (ClientAuthError.ts:222:1)
    at ClientAuthError.createEndpointDiscoveryIncompleteError (ClientAuthError.ts:269:1)
    at Function.<anonymous> (AuthorityFactory.ts:58:1)
    at step (MathUtils.ts:24:1)
    at Object.throw (MathUtils.ts:24:1)
    at rejected (MathUtils.ts:24:1)

### MSAL Configuration

```javascript
export const b2cPolicies = {
  names: {
    signUpSignIn: 'B2C_1A_DISPLAYCONTROL_SENDGRID_SIGNIN',
    forgotPassword: 'B2C_1A_DISPLAYCONTROL_SENDGRID_PASSWORDRESET',
    editProfile: 'B2C_1_edit_profile_v2',
  },
  authorities: {
    signUpSignIn: {
      authority:
        'https://asmurph.b2clogin.com/asmurph.onmicrosoft.com/B2C_1A_DISPLAYCONTROL_SENDGRID_SIGNIN',
    },
    forgotPassword: {
      authority:
        'https://asmurph.b2clogin.com/asmurph.onmicrosoft.com/B2C_1A_DISPLAYCONTROL_SENDGRID_PASSWORDRESET',
    },
    editProfile: {
      authority: 'https://asmurph1.b2clogin.com/asmurph.onmicrosoft.com/b2c_1_edit_profile_v2',
    },
  },
  authorityDomain: 'asmurph.b2clogin.com',
};
/**
 * Configuration object to be passed to MSAL instance on creation.
 * For a full list of MSAL.js configuration parameters, visit:
 * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/configuration.md
 */
export const msalConfig = {
  auth: {
    clientId: '5dd2b59a-2198-43ef-9f49-36ca97c71ad2', // This is the ONLY mandatory field that you need to supply.
    authority: b2cPolicies.authorities.signUpSignIn.authority, // Choose SUSI as your default authority.
    knownAuthorities: [b2cPolicies.authorityDomain], // Mark your B2C tenant's domain as trusted.
    redirectUri: '/', // You must register this URI on Azure Portal/App Registration. Defaults to window.location.origin
    postLogoutRedirectUri: '/', // Indicates the page to navigate after logout.
    navigateToLoginRequestUrl: false, // If "true", will navigate back to the original request location before processing the auth code response.
  },
  cache: {
    cacheLocation: 'sessionStorage', // Configures cache location. "sessionStorage" is more secure, but "localStorage" gives you SSO between tabs.
    storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
  },
};
/**
 * Add here the endpoints and scopes when obtaining an access token for protected web APIs. For more information, see:
 * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/resources-and-scopes.md
 */
export const protectedResources = {
  apiTodoList: {
    endpoint: 'http://localhost:3000',
    scopes: {
      read: ['https://asmurph.onmicrosoft.com/TodoList/ToDoList.Read'],
      write: ['https://asmurph.onmicrosoft.com/TodoList/ToDoList.ReadWrite'],
    },
  },
};
```

### Relevant Code Snippets

```javascript
import { useMsal } from '@azure/msal-react';
import { useCallback, useEffect } from 'react';
import { loginRequest, b2cPolicies } from './authConfig';
// Core.
// import { Configuration } from 'core';
import { EventType } from '@azure/msal-browser';

export const useAuthLogin = (): VoidFunction => {
  const { instance } = useMsal();
  useEffect(() => {
    const callbackId = instance.addEventCallback((event) => {
      if (event.eventType === EventType.LOGIN_FAILURE) {
        // Check for forgot password error
        // Learn more about AAD error codes at https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-aadsts-error-codes
        if (event.error && event.error.errorMessage.includes('AADB2C90118')) {
          const resetPasswordRequest = {
            authority: b2cPolicies.authorities.forgotPassword.authority,
            scopes: [],
          };
          instance.loginRedirect(resetPasswordRequest);
        }
      }
      if (event.eventType === 'msal:handleRedirectEnd') {
        // Check for forgot password error
        // Learn more about AAD error codes at https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-aadsts-error-codes
        if (event.error && event.error.errorMessage.includes('could not resolve endpoints.')) {
          const loginReqeust = {
            authority: b2cPolicies.authorities.signUpSignIn.authority,
            scopes: [],
          };
          instance.loginRedirect(loginReqeust);
        }
      }
    });

    return () => {
      if (callbackId) {
        instance.removeEventCallback(callbackId);
      }
    };
    // eslint-disable-next-line
}, [instance]);
  const login = useCallback(() => {
    instance.loginRedirect(loginRequest).catch((error) => {
      console.error('Auth Error:', error);
    });
  }, [instance]);

  return login;
};
```

### Reproduction Steps

This is a react application - all I did was to upgrade 
  "dependencies": 
    "@azure/msal-browser": "^2.14.1",
    "@azure/msal-react": "^1.0.0-beta.2",

To  "dependencies": 
    "@azure/msal-browser": "2.36.0",
    "@azure/msal-react": "^1.5.7",
    
    Updated the AuthLogin.ts file from:

```js
    import { useMsal } from '@azure/msal-react';
import { useCallback } from 'react';

// Core.
import { Configuration } from 'core';

export const useAuthLogin = (): VoidFunction => {
  const { instance } = useMsal();

  const login = useCallback(() => {
    instance.loginRedirect({ scopes: ['openid', Configuration.azureMsalScope] }).catch((error) => {
      console.error('Auth Error:', error);
    });
  }, [instance]);

  return login;
};
```

To: 
```js
import { useMsal } from '@azure/msal-react';
import { useCallback, useEffect } from 'react';
import { loginRequest, b2cPolicies } from './authConfig';
// Core.
// import { Configuration } from 'core';
import { EventType } from '@azure/msal-browser';

export const useAuthLogin = (): VoidFunction => {
  const { instance } = useMsal();
  useEffect(() => {
    const callbackId = instance.addEventCallback((event) => {
      if (event.eventType === EventType.LOGIN_FAILURE) {
        // Check for forgot password error
        // Learn more about AAD error codes at https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-aadsts-error-codes
        if (event.error && event.error.errorMessage.includes('AADB2C90118')) {
          const resetPasswordRequest = {
            authority: b2cPolicies.authorities.forgotPassword.authority,
            scopes: [],
          };
          instance.loginRedirect(resetPasswordRequest);
        }
      }
      if (event.eventType === 'msal:handleRedirectEnd') {
        // Check for forgot password error
        // Learn more about AAD error codes at https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-aadsts-error-codes
        if (event.error && event.error.errorMessage.includes('could not resolve endpoints.')) {
          const loginReqeust = {
            authority: b2cPolicies.authorities.signUpSignIn.authority,
            scopes: [],
          };
          instance.loginRedirect(loginReqeust);
        }
      }
    });

    return () => {
      if (callbackId) {
        instance.removeEventCallback(callbackId);
      }
    };
    // eslint-disable-next-line
}, [instance]);
  const login = useCallback(() => {
    instance.loginRedirect(loginRequest).catch((error) => {
      console.error('Auth Error:', error);
    });
  }, [instance]);

  return login;
};
```
    

### Expected Behavior

I would expect to redirected to the azure b2c signup_signin custom policy URL.

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome, Edge

### Regression

"@azure/msal-browser": "^2.14.1",

### Source

Internal (Microsoft)

**Comment by jo-arroyo** [comment]
@asmurph Are you able to provide verbose logs of this behavior? Instructions for logs can be found [here](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-logging-js).
