### ISSUE TITLE
acquireTokenByClientCredential fails with multiple scopes

### ISSUE THREAD

**Issue by jefbarn** [AzureAD/microsoft-authentication-library-for-js#6069]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.17.2

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Confidential

### Description

acquireTokenByClientCredential indicates that multiple 'scopes' can be supplied, but using more than one scope gives an error.

```typescript
const token = await this.#cca.acquireTokenByClientCredential({
      scopes: [
        'https://graph.microsoft.com/.default',
        'https://xxx.sharepoint.com/.default'
      ]
    })
```

  ServerError: invalid_scope: 70011 - [2023-05-31 17:07:41Z]: AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope https://graph.microsoft.com/.default https://xxx.sharepoint.com/.default is not valid.

### Error Message

  ServerError: invalid_scope: 70011 - [2023-05-31 17:07:41Z]: AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope https://graph.microsoft.com/.default https://xxx.sharepoint.com/.default is not valid.

### MSAL Configuration

```javascript
{
      auth: {
        clientId: this.#options.clientId,
        clientCertificate: {
          thumbprint: this.#options.clientCertFingerprint,
          privateKey: this.#options.clientCertKey
        },
        authority: `https://login.microsoftonline.com/${this.#options.tenantId}`
      }
    }
```

### Relevant Code Snippets

```javascript
const token = await this.#cca.acquireTokenByClientCredential({
      scopes: [
        'https://graph.microsoft.com/.default',
        'https://xxx.sharepoint.com/.default'
      ]
    })
```

### Reproduction Steps

see description

### Expected Behavior

multiple scopes supported

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Source

External (Customer)

**Comment by RayGHeld** [comment]
Azure will not issue a token for more than one resource at a time.  You have 2 resources listed, one for Microsoft Graph and one for SharePoint.  You will need to make 2 separate token requests to get a token for each resource.

**Comment by jefbarn** [comment]
@RayGHeld Thanks. The documentation and typescript typings should be changed to reflect this.

```typescript
/**
 * CommonClientCredentialRequest
 * - scopes                  - Array of scopes the application is requesting access to. // FIXME
 * - authority               - URL of the authority, the security token service (STS) from which MSAL will acquire tokens.
 * - correlationId           - Unique GUID set per request to trace a request end-to-end for telemetry purposes.
 * - skipCache               - Skip token cache lookup and force request to authority to get a a new token. Defaults to false.
 * - clientAssertion         - A Base64Url-encoded signed JWT assertion string used in the Client Credential flow
 * - tokenQueryParameters    - String to string map of custom query parameters added to the /token call
 * @public
 */
export declare type ClientCredentialRequest = Partial<Omit<CommonClientCredentialRequest, "scopes" | "resourceRequestMethod" | "resourceRequestUri" | "requestedClaimsHash" | "clientAssertion">> & {
    scopes: Array<string>;  // FIXME
    clientAssertion?: string;
};
```

**Comment by bgavrilMS** [comment]
Agreed @jefbarn, we will update the docs.

**Comment by derisen** [comment]
@jefbarn we do outline how scopes and resources relate to acquireToken* APIs in the [docs here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/resources-and-scopes.md) -please have a look. But agreed, typings could be updated to clarify this as convenience.

**Comment by jefbarn** [comment]
@derisen Thanks for that link.
Yeah looks like the api was designed with the delegated token flow in mind and not really for the client credential workflow. 
Probably just buggy because no one tested setting multiple scopes on the acquireTokenByClientCredential function.

**Comment by bgavrilMS** [comment]
I may be wrong, but IdP other than AAD might support multiple scopes? If so, we should keep the API as is, and just update docs.

**Comment by jefbarn** [comment]
@bgavrilMS If so that would probably require a different function. Certainly what acquireTokenByClientCredential is doing (using toString on the array) is incorrect.
Edit: acquireTokenByClientCredential is doing a little more than concatenating the strings, but it still probably needs a check for this and a better error message.

**Comment by derisen** [comment]
@jefbarn @bgavrilMS this is the case for delegated permissions as well though. Scopes for more than one resource will be ignored i.e. the AT will only be issued for the first resource (but might have more than one scope for that resource). It's just that, as a matter of contingency, client credentials flow make use of the [./default scope](https://learn.microsoft.com/en-us/azure/active-directory/develop/scopes-oidc#the-default-scope), so there's never more than one scope for any given resource. My take is that the API does not need a change, but API documentation for typings can be improved to steer folks in the right direction (or better, the ESTS error description might hint at this).
