### ISSUE TITLE
acquireTokenByRefreshToken() AADSTS9002313: Invalid request. Request is malformed or invalid

### ISSUE THREAD

**Issue by davidwitten** [AzureAD/microsoft-authentication-library-for-js#6076]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.17.2

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Confidential

### Description

```
    const config = {
        auth: {
            clientId: client_id,
            authority: "https://login.microsoftonline.com/" + tenant_id,
            clientSecret: client_secret
        },
        system: {
            loggerOptions: {
                loggerCallback(loglevel, message, containsPii) {
                    console.log(message);
                },
                piiLoggingEnabled: false,
                logLevel: msal.LogLevel.Verbose,
            }
        }
    };
    
    const cca = new msal.ConfidentialClientApplication(config);
    
    const refreshTokenRequest = {
        refreshToken: refresh_token,
        scopes: ["https://graph.microsoft.com/.default"]
    };
    
    cca.acquireTokenByRefreshToken(refreshTokenRequest).then((response) => {
        console.log(JSON.stringify(response));
    }).catch((error) => {
        console.log(error);
    });
```
I used a refresh token that was created maybe 30 seconds before I ran this code snippet. 

### Error Message

ServerError: invalid_grant: 9002313 - [2023-05-31 18:39:20Z]: AADSTS9002313: Invalid request. Request is malformed or invalid.
Trace ID: 2645c6cf-126b-42ce-ba16-ceff4ddb0102
Correlation ID: 2844be1f-59c0-462d-87a3-5e01f9d360d4

### Msal Logs

[Wed, 31 May 2023 18:44:38 GMT] : @azure/msal-node@1.17.2 : Verbose - Attempting to find a match between the developer's authority and the CloudInstanceDiscoveryMetadata returned from the network request.
[Wed, 31 May 2023 18:44:38 GMT] : @azure/msal-node@1.17.2 : Verbose - cloud discovery metadata was successfully returned from getCloudDiscoveryMetadataFromNetwork()
[Wed, 31 May 2023 18:44:38 GMT] : @azure/msal-node@1.17.2 : Info - acquireTokenByRefreshToken called
[Wed, 31 May 2023 18:44:38 GMT] : @azure/msal-node@1.17.2 : Verbose - initializeRequestScopes called
[Wed, 31 May 2023 18:44:38 GMT] : [31a37094-82e9-4036-965e-bc470d474b01] : @azure/msal-node@1.17.2 : Verbose - buildOauthClientConfiguration called
[Wed, 31 May 2023 18:44:38 GMT] : [31a37094-82e9-4036-965e-bc470d474b01] : @azure/msal-node@1.17.2 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/common/
[Wed, 31 May 2023 18:44:38 GMT] : [31a37094-82e9-4036-965e-bc470d474b01] : @azure/msal-node@1.17.2 : Verbose - createAuthority called
[Wed, 31 May 2023 18:44:38 GMT] : @azure/msal-node@1.17.2 : Verbose - Attempting to get cloud discovery metadata in the config
[Wed, 31 May 2023 18:44:38 GMT] : @azure/msal-node@1.17.2 : Verbose - Did not find cloud discovery metadata in the config... Attempting to get cloud discovery metadata from the cache.
[Wed, 31 May 2023 18:44:38 GMT] : @azure/msal-node@1.17.2 : Verbose - Did not find cloud discovery metadata in the cache... Attempting to get cloud discovery metadata from the network.
[Wed, 31 May 2023 18:44:38 GMT] : [9f6b5bb0-8b66-4333-8e8c-aa2e18e58dd8] : @azure/msal-node@1.17.2 : Verbose - Refresh token client created
[Wed, 31 May 2023 18:44:38 GMT] : [9f6b5bb0-8b66-4333-8e8c-aa2e18e58dd8] : @azure/msal-common@13.0.0 : Verbose - RefreshTokenClientAcquireToken called
[Wed, 31 May 2023 18:44:39 GMT] : @azure/msal-node@1.17.2 : Verbose - Attempting to find a match between the developer's authority and the CloudInstanceDiscoveryMetadata returned from the network request.
[Wed, 31 May 2023 18:44:39 GMT] : @azure/msal-node@1.17.2 : Verbose - cloud discovery metadata was successfully returned from getCloudDiscoveryMetadataFromNetwork()

### MSAL Configuration

```javascript
na
```

### Relevant Code Snippets

```javascript
above
```

### Reproduction Steps

I authenticated from the browser and received a refresh + access token. However, when I try to use the same refresh token to get a new access token, I get the error above.

### Expected Behavior

The request successfully returns an access token.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Source

External (Customer)

**Comment by davidwitten** [comment]
I tried both:
`authority: "https://login.microsoftonline.com/" + tenant_id,`
and 
`authority: "https://login.microsoftonline.com/common"`

Both failed.

**Comment by jo-arroyo** [comment]
@davidwitten In your code sample above, where are you getting the refresh token from?

**Comment by davidwitten** [comment]
@jo-arroyo The user authenticates in the frontend using [Firebase](https://firebase.google.com/docs/auth/web/microsoft-oauth)
```
        signInWithPopup(getAuth(firebase), outlookAuthProvider)
            .then((res) => {

                console.log(res._tokenResponse.refreshToken); // This is the refresh token
            })
            .catch((err) => { console.log("Sign up failed.", err); });
```

I've pointed out where I receive the refresh token. I also confirm that the access token `res._tokenResponse.oauthAccessToken` works perfectly.

**Comment by bgavrilMS** [comment]
@davidwitten - do I understand correctly that the front-end is a SPA application and that it retrieves an access token and refresh token from AAD? Does your front-end call any downstream api? 

Next, you send the refresh token to the backend and you then try to get a new access token based on it and you get this error? Do you need the backend to also access some downstream api?

I haven't seen this error before but it simply means that the refresh token is invalid. I would hypothesize that this is because the front-end is a SPA (so no secret is used) and the backend is a confidential client and a secret is used. @jmprieur - can you confirm this? 

Note that this isn't how we guide folks to architect their apps and MSAL doesn't expose the concept of refresh tokens except for a very specific use case related to a legacy library. I would recommend you do the following: 

- your back-end is a web api and you protect it with AAD (see https://learn.microsoft.com/en-us/azure/active-directory/develop/sample-v2-code#web-api)
- your front-end gets an access token for the back-end. The scope of the request is what you configure in "Expose an API" section in Azure Portal
- your back-end validates the access token and figures out who the user is. 
- if your back-end needs to call a downstream api, use MSAL's `AcquireTokenOnBehalfOf`

**Comment by davidwitten** [comment]
Thank you! @bgavrilMS 

I want the backend to be able to send emails on behalf of the user even after original access token has become invalid. 

This is why I want to get an access and refresh token. Is this not necessary?

When I look at network requests, I see the `/token` request which has the refresh token and it works perfectly. However, it seems like you hide it in `loginRedirect`

**Comment by bgavrilMS** [comment]
I can't see any issue with your approach, except that it's possible that the refresh token obtained by the SPA is not usable by in a confidential client. Is it possible that the refresh token is somehow changed / trimmed ?

Normally I would advise one of 2 ways: 

- SPA app calls web api (as described above), using OBO flow. Unfortunately OBO flow in MSAL JS does not make use of refresh token. So you won't be able to send email after the fact. Tracking issue: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5330

- You can also use service to service auth. This is where the backend authenticates as itself (a service principal, not a user). You can then send email to any user in the directory. You still need to validate the call from the SPA to the backend.

<img width="644" alt="image" src="https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/12273384/6907c42c-9134-4c61-9919-253596962c3f">

<img width="564" alt="image" src="https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/12273384/790d7a8d-cbb3-4568-8fb3-dbb22e06d18b">

**Comment by davidwitten** [comment]
@bgavrilMS Thank you! Is there really no better way of doing this than the two ways you mentioned? The first is not a solution, unfortunately. My users need to grant extended access. The second also requires our application to get permissions that are too strict.

When I examine network requests and manually copy the refresh token from the network request, I'm able to use it indefinitely. It works perfectly, and this is the behavior I need:

<img width="209" alt="image" src="https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/3642085/70a0db1d-2dd2-4eab-957c-444df210bef0">

Can I really not do the same thing in my code? I try to do the `/token` request but I need a code_verifier, hence my Github issue [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/6088)

**Comment by bgavrilMS** [comment]
Can you try to perform the auth flow manually and see if it works? Maybe with PostMan - https://www.postman.com/lmedenred/workspace/lm-s-public-workspace/request/11230239-f637943a-965e-4131-a3ce-19b24ddf1dd9
