### ISSUE TITLE
Window is not defined

### ISSUE THREAD

**Issue by Julien-sans** [AzureAD/microsoft-authentication-library-for-js#608]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[] Other... Please describe:
</code></pre>

## Library version 

<pre><code>
Library version: 0.2.3

## Current behavior

Getting error "window is not defined" in heroku's console in staging environment. if i comment this.userArgentApplication line, the app works. I suppose the problem comes from this. 

## Expected behavior

get outlook contact with react. The code below just works normally on localhost environment (not in staging).

## Minimal reproduction of the problem with instructions

</code></pre>

app.js (initialize user Agent Application)

```javascript
import { UserAgentApplication } from 'msal';

class App extends LoadingComponent {

  constructor(props) {

    super(props);

    this.userAgentApplication = new UserAgentApplication(env.REACT_APP_OUTLOOK_CLIENT_ID, null, null)
```

outlookApi.js (child of app.js)

```javascript
import { UserAgentApplication } from 'msal';

class outlookApi extends Component {

  constructor(props) {

    super(props);

    this.state = {
      people: [],
    };

    this.userAgentApplication = new  UserAgentApplication(env.REACT_APP_OUTLOOK_CLIENT_ID, null, null)
  }

  async login() {
      await this.userAgentApplication.loginPopup([
        "user.read",
        "contacts.read",
      ]);
      await this.getUserProfile();
  }

  async getUserProfile() {
      var accessToken = await this.userAgentApplication.acquireTokenSilent([
        "user.read",
        "contacts.read",
      ]);
      var people = await getPeople(accessToken);
      this.setState({people: people.value});
      this.props.contacts(this.state.people);
      this.props.openModal();
  }

  render() {

    return (
    <div id="outlook" onClick={this.login.bind(this)}>
      <img src={outlookIcon} alt='outlook_logo' />
      <span>Outlook</span>
    </div>
    )
  }
}

export default outlookApi;

var graph = require('@microsoft/microsoft-graph-client');

function getAuthenticatedClient(accessToken) {
  // Initialize Graph client
  const client = graph.Client.init({
    // Use the provided access token to authenticate
    // requests
    authProvider: (done) => {
      done(null, accessToken);
    }
  });
  return client;
}

export async function getPeople(accessToken) {
  const client = getAuthenticatedClient(accessToken);

  const people = await client
    .api('/me/contacts?$top=500')
    .get();

  return people;
}
```

**Comment by DarylThayil** [comment]
Is this being rendered server side?

**Comment by sameerag** [comment]
@Julien-sans Can you please give us clear instructions on the repro? The usage seems alright from your sample code but there may be an issue with the way your environment is configured that may be leading to this.

**Comment by DarylThayil** [comment]
@Julien-sans  my hunch is that if this is being server rendered, the same code that should only be run client side is being run server side and causing this issue

**Comment by DarylThayil** [comment]
@Julien-sans  closing this issue since we have not seen activity.  If you come across this issue again, please reopen / create a new issue
