### ISSUE TITLE
`.loginRedirect()` does not work with MSAL V3-based standalone Angular 15 app

### ISSUE THREAD

**Issue by mdddev** [AzureAD/microsoft-authentication-library-for-js#6080]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.0.0-alpha-2

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.0-alpha-2

### Public or Confidential Client?

Public

### Description

I have cloned the official MSAL V3 Angular 15 Version in this repo and have changed it to work without NgModules, i.e. in `standalone` mode. The source code can be seen [here](https://github.com/mdddev/msal-b2c/tree/main/angular15-msal3-standalone).

Everything works fine if I login using a Popup. Logging in with the Redirect flow does not work however. 

Can you please help in identifying what must be changed in order to make it work?

### Error Message

None. 

### Msal Logs

main.ts:17 [Wed, 31 May 2023 23:00:49 GMT] : [bbc99fe3-7703-4716-9df9-84961e772967] : @azure/msal-browser@3.0.0-alpha.2 : Verbose - loginRedirect called
main.ts:17 [Wed, 31 May 2023 23:00:49 GMT] : [bbc99fe3-7703-4716-9df9-84961e772967] : @azure/msal-browser@3.0.0-alpha.2 : Verbose - acquireTokenRedirect called
main.ts:17 [Wed, 31 May 2023 23:00:49 GMT] : @azure/msal-browser@3.0.0-alpha.2 : Verbose - preflightBrowserEnvironmentCheck started
main.ts:17 [Wed, 31 May 2023 23:00:49 GMT] : @azure/msal-browser@3.0.0-alpha.2 : Verbose - preflightInteractiveRequest called, validating app environment
main.ts:17 [Wed, 31 May 2023 23:00:49 GMT] : @azure/msal-browser@3.0.0-alpha.2 : Verbose - getAllAccounts called
main.ts:17 [Wed, 31 May 2023 23:00:49 GMT] : @azure/msal-browser@3.0.0-alpha.2 : Verbose - BrowserCacheManager.getAccountKeys - No account keys found
main.ts:17 [Wed, 31 May 2023 23:00:49 GMT] : @azure/msal-browser@3.0.0-alpha.2 : Info - Emitting event: msal:loginStart
main.ts:17 [Wed, 31 May 2023 23:00:49 GMT] : @azure/msal-browser@3.0.0-alpha.2 : Verbose - Emitting event to callback 6c5ae9d0-b3cb-4f6d-874f-a18145030fd7: msal:loginStart
main.ts:17 [Wed, 31 May 2023 23:00:49 GMT] : @azure/msal-angular@3.0.0-alpha.2 : Verbose - BroadcastService - msal:loginStart results in setting inProgress from startup to login
main.ts:17 [Wed, 31 May 2023 23:00:49 GMT] : [bbc99fe3-7703-4716-9df9-84961e772967] : msal.js.browser@3.0.0-alpha.2 : Verbose - initializeAuthorizationRequest called
main.ts:17 [Wed, 31 May 2023 23:00:49 GMT] : [bbc99fe3-7703-4716-9df9-84961e772967] : msal.js.browser@3.0.0-alpha.2 : Verbose - getRedirectUri called
main.ts:17 [Wed, 31 May 2023 23:00:49 GMT] : [bbc99fe3-7703-4716-9df9-84961e772967] : msal.js.browser@3.0.0-alpha.2 : Verbose - Initializing BaseAuthRequest
main.ts:17 [Wed, 31 May 2023 23:00:49 GMT] : [bbc99fe3-7703-4716-9df9-84961e772967] : msal.js.browser@3.0.0-alpha.2 : Verbose - Authentication Scheme wasn't explicitly set in request, defaulting to "Bearer" request
main.ts:17 [Wed, 31 May 2023 23:00:49 GMT] : [bbc99fe3-7703-4716-9df9-84961e772967] : msal.js.browser@3.0.0-alpha.2 : Verbose - initializeServerTelemetryManager called
main.ts:17 [Wed, 31 May 2023 23:00:49 GMT] : [bbc99fe3-7703-4716-9df9-84961e772967] : msal.js.browser@3.0.0-alpha.2 : Verbose - initializeAuthorizationRequest called
main.ts:17 [Wed, 31 May 2023 23:00:49 GMT] : [bbc99fe3-7703-4716-9df9-84961e772967] : msal.js.browser@3.0.0-alpha.2 : Verbose - getClientConfiguration called
main.ts:17 [Wed, 31 May 2023 23:00:49 GMT] : [bbc99fe3-7703-4716-9df9-84961e772967] : msal.js.browser@3.0.0-alpha.2 : Verbose - getDiscoveredAuthority called
main.ts:17 [Wed, 31 May 2023 23:00:49 GMT] : [bbc99fe3-7703-4716-9df9-84961e772967] : msal.js.browser@3.0.0-alpha.2 : Verbose - Creating discovered authority with configured authority
main.ts:17 [Wed, 31 May 2023 23:00:49 GMT] : [bbc99fe3-7703-4716-9df9-84961e772967] : msal.js.browser@3.0.0-alpha.2 : Verbose - Attempting to get cloud discovery metadata in the config
main.ts:17 [Wed, 31 May 2023 23:00:49 GMT] : [bbc99fe3-7703-4716-9df9-84961e772967] : msal.js.browser@3.0.0-alpha.2 : Verbose - The host is included in knownAuthorities. Creating new cloud discovery metadata from the host.
main.ts:17 [Wed, 31 May 2023 23:00:49 GMT] : [bbc99fe3-7703-4716-9df9-84961e772967] : msal.js.browser@3.0.0-alpha.2 : Verbose - Found cloud discovery metadata in the config.
main.ts:17 [Wed, 31 May 2023 23:00:49 GMT] : [bbc99fe3-7703-4716-9df9-84961e772967] : msal.js.browser@3.0.0-alpha.2 : Verbose - Authority.getEndpointMetadataFromNetwork: attempting to retrieve OAuth endpoints from https://fabrikamb2c.b2clogin.com/fabrikamb2c.onmicrosoft.com/b2c_1_susi/v2.0/.well-known/openid-configuration
main.ts:17 [Wed, 31 May 2023 23:00:49 GMT] : [bbc99fe3-7703-4716-9df9-84961e772967] : @azure/msal-browser@3.0.0-alpha.2 : Verbose - PerformanceClient: Emitting performance events
main.ts:17 [Wed, 31 May 2023 23:00:49 GMT] : [bbc99fe3-7703-4716-9df9-84961e772967] : msal.js.browser@3.0.0-alpha.2 : Verbose - Auth code client created
main.ts:17 [Wed, 31 May 2023 23:00:49 GMT] : [bbc99fe3-7703-4716-9df9-84961e772967] : msal.js.browser@3.0.0-alpha.2 : Verbose - RedirectHandler.initiateAuthRequest called
main.ts:17 [Wed, 31 May 2023 23:00:49 GMT] : [bbc99fe3-7703-4716-9df9-84961e772967] : msal.js.browser@3.0.0-alpha.2 : Verbose - RedirectHandler.initiateAuthRequest: redirectStartPage set, caching start page
main.ts:17 [Wed, 31 May 2023 23:00:49 GMT] : [bbc99fe3-7703-4716-9df9-84961e772967] : msal.js.browser@3.0.0-alpha.2 : Verbose - RedirectHandler.initiateAuthRequest: Navigating window to navigate url
Navigated to http://localhost:4200/
polyfills.js:1 [webpack-dev-server] Server started: Hot Module Replacement disabled, Live Reloading enabled, Progress disabled, Overlay enabled.
main.ts:17 [Wed, 31 May 2023 23:00:51 GMT] : @azure/msal-browser@3.0.0-alpha.2 : Verbose - BrowserCrypto: modern crypto interface available
main.ts:17 [Wed, 31 May 2023 23:00:51 GMT] : @azure/msal-browser@3.0.0-alpha.2 : Verbose - BrowserCrypto: modern crypto interface available
main.ts:17 [Wed, 31 May 2023 23:00:51 GMT] : @azure/msal-browser@3.0.0-alpha.2 : Verbose - Event callback registered with id: b9b8bbbb-56fb-4977-bf4f-a92fade6dea9
main.ts:17 [Wed, 31 May 2023 23:00:51 GMT] : @azure/msal-browser@3.0.0-alpha.2 : Verbose - getAllAccounts called
main.ts:17 [Wed, 31 May 2023 23:00:51 GMT] : @azure/msal-browser@3.0.0-alpha.2 : Verbose - BrowserCacheManager.getAccountKeys - No account keys found
main.ts:17 [Wed, 31 May 2023 23:00:51 GMT] : @azure/msal-browser@3.0.0-alpha.2 : Verbose - Adding account storage listener.
core.mjs:23480 Angular is running in development mode. Call enableProdMode() to enable production mode.

### MSAL Configuration

```javascript
const SIGN_IN_USER_FLOW_NAME = 'b2c_1_susi'
const B2C_TENANT_PREFIX = 'fabrikamb2c'
const B2C_TENANT_DOMAIN = 'fabrikamb2c'

const CLIENT_IDS = {
  WEB_APP: '9067c884-9fa6-414f-9aa4-a565b1cb46be'
}

export const environment = {
  production: false,
  msalConfig: {
      auth: {
          clientId: CLIENT_IDS.WEB_APP,
      }
  },
  apiConfig: {
      scopes: [
        'openid',
        'offline_access'
      ],
      uri: 'https://fabrikamb2chello.azurewebsites.net/hello'
  },
  b2cPolicies: {
      names: {
          signUpSignIn: SIGN_IN_USER_FLOW_NAME,
      },
      authorities: {
          signUpSignIn: {
              authority: `https://${B2C_TENANT_PREFIX}.b2clogin.com/${B2C_TENANT_PREFIX}.onmicrosoft.com/${SIGN_IN_USER_FLOW_NAME}`
          }
      },
      authorityDomain: `${B2C_TENANT_PREFIX}.b2clogin.com`
  }
};
```

### Relevant Code Snippets

```javascript
https://github.com/mdddev/msal-b2c/tree/main/angular15-msal3-standalone
```

### Reproduction Steps

Repo link provided for easy repro, it's ready to go.

### Expected Behavior

LoginRedirect and LoginPopup behaving the same way.

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Edge

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
Thanks for opening this issue for v3. While work to support standalone apps has not been prioritized for v3, we will take this into consideration and investigation, and post updates here if updates are made.

Tagging @EmLauber for visibility.

**Comment by jo-arroyo** [comment]
@mdddev Thank you for the repros, those were very helpful. Can you please try subscribing to the `handleRedirectObservable()` to your `app.component.ts` and let me know what happens for you?
```js
  ngOnInit(): void {
    this.authService.handleRedirectObservable().subscribe(); // Add this line
```

**Comment by senthil-cg** [comment]
@jo-arroyo  It is working after subscribing to handleRedirectObservable()
