### ISSUE TITLE
the auth stuck after browser session restore

### ISSUE THREAD

**Issue by SamShekhovtsov** [AzureAD/microsoft-authentication-library-for-js#6081]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.33.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.5.3

### Public or Confidential Client?

Confidential

### Description

there is an isssue, which is 100% reproducible, but I'm not quite sure that it's related to the MSAL Angular library.
when I authenticate using the Msal for Angular library, after that I logout, close the browser, open the same browser with session automatically restored and try to login (as another user) the Azure AD B2C login page works fine, however after that - the app stuck at the http://localhost:4200/auth#state=..... url. It doesn't do anything, the app is broken, the user can't do anything. I have noticed few other cases when the application get stuck at the following address: http://localhost:4200/auth#state=..... it just stays at that address and not load anything. Please advise.

### Error Message

there is no any error message. The app just stuck at the http://localhost:4200/auth#state=..... address

### Msal Logs

there are no any logs. The console is empty

### MSAL Configuration

```javascript
export function MSALInstanceFactory(): IPublicClientApplication {
  return new PublicClientApplication(msalConfig);
}

export function MSALGuardConfigFactory(): MsalGuardConfiguration {
  return {
    interactionType: InteractionType.Redirect,
    authRequest: loginRequest
  };
}
```

### Relevant Code Snippets

```javascript
const routes: Routes = [
  ...,
  {
    // Needed for handling redirect after login
    path: 'auth',
    component: MsalRedirectComponent
  },
  ...
]
```

### Reproduction Steps

1. Login with a valid user account to the application using the AAD B2C Custom Policy
2. Logout from the app
3. Close the browser
4. Open the same browser with the previous session restored
5. Login to the application with a different user account

### Expected Behavior

the MsalRedirectComponent should handle correctly the address: http://localhost:4200/auth#state=.....
the user should see the destination page after the successfull login

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@SamShekhovtsov A few questions:
1. What version of Angular are you using?
2. How are you handling redirects in your app? Is the `MsalRedirectComponent` bootstrapped? 

Additionally, are you able to turn on verbose logging to see if there is any more information? You can find instructions [here](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-logging-js).

**Comment by SamShekhovtsov** [comment]
@jo-arroyo 

The angular version is 15.1.3
Yes, sure the `MsalRedirectComponent `is bootstraped, I have following code in the `app-routing.module.ts`:
```
const routes: Routes = [
...
  {
    // Needed for handling redirect after login
    path: 'auth',
    component: MsalRedirectComponent
  },
...
]

```
When I turn Verbose logging, it shows some activity but I don't understand why it hangs:

16:24:07.958 [webpack-dev-server] Server started: Hot Module Replacement disabled, Live Reloading enabled, Progress disabled, Overlay enabled. index.js:551:21
16:24:08.003 Could not find Angular Material core theme. Most Material components may not work as expected. For more info refer to the theming guide: https://material.angular.io/guide/theming core.mjs:147:16
16:24:08.004 [Fri, 02 Jun 2023 13:24:08 GMT] : @azure/msal-browser@2.33.0 : Verbose - BrowserCrypto: modern crypto interface available 2 auth-config.ts:78:32
16:24:08.006 [Fri, 02 Jun 2023 13:24:08 GMT] : @azure/msal-browser@2.33.0 : Verbose - Event callback registered with id: 2a169cea-166c-4cbc-b254-aebecc3b18f1 auth-config.ts:78:32
16:24:08.013 [Fri, 02 Jun 2023 13:24:08 GMT] : @azure/msal-browser@2.33.0 : Verbose - getAllAccounts called 2 auth-config.ts:78:32
16:24:08.014 [Fri, 02 Jun 2023 13:24:08 GMT] : @azure/msal-browser@2.33.0 : Verbose - Adding account storage listener. auth-config.ts:78:32
16:24:08.018 Angular is running in development mode. Call enableProdMode() to enable production mode. core.mjs:23583:16
16:24:08.018 [Fri, 02 Jun 2023 13:24:08 GMT] : @azure/msal-angular@2.5.3 : Verbose - MsalRedirectComponent activated auth-config.ts:78:32
16:24:08.018 [Fri, 02 Jun 2023 13:24:08 GMT] : @azure/msal-browser@2.33.0 : Info - Emitting event: msal:initializeStart auth-config.ts:75:32
16:24:08.018 [Fri, 02 Jun 2023 13:24:08 GMT] : @azure/msal-browser@2.33.0 : Verbose - Emitting event to callback 2a169cea-166c-4cbc-b254-aebecc3b18f1: msal:initializeStart auth-config.ts:78:32
16:24:08.018 [Fri, 02 Jun 2023 13:24:08 GMT] : @azure/msal-browser@2.33.0 : Info - Emitting event: msal:initializeEnd auth-config.ts:75:32
16:24:08.018 [Fri, 02 Jun 2023 13:24:08 GMT] : @azure/msal-browser@2.33.0 : Verbose - Emitting event to callback 2a169cea-166c-4cbc-b254-aebecc3b18f1: msal:initializeEnd auth-config.ts:78:32
16:24:08.019 Angular is running in development mode. Call enableProdMode() to enable production mode. core.mjs:23583:16
16:24:08.021 [Fri, 02 Jun 2023 13:24:08 GMT] : @azure/msal-browser@2.33.0 : Verbose - handleRedirectPromise called auth-config.ts:78:32
16:24:08.021 [Fri, 02 Jun 2023 13:24:08 GMT] : @azure/msal-browser@2.33.0 : Verbose - getAllAccounts called auth-config.ts:78:32
16:24:08.021 [Fri, 02 Jun 2023 13:24:08 GMT] : @azure/msal-browser@2.33.0 : Info - Emitting event: msal:handleRedirectStart auth-config.ts:75:32
16:24:08.021 [Fri, 02 Jun 2023 13:24:08 GMT] : @azure/msal-browser@2.33.0 : Verbose - Emitting event to callback 2a169cea-166c-4cbc-b254-aebecc3b18f1: msal:handleRedirectStart auth-config.ts:78:32
16:24:08.022 [Fri, 02 Jun 2023 13:24:08 GMT] : @azure/msal-angular@2.5.3 : Verbose - BroadcastService - msal:handleRedirectStart results in setting inProgress from startup to handleRedirect auth-config.ts:78:32
16:24:08.022 [Fri, 02 Jun 2023 13:24:08 GMT] : @azure/msal-browser@2.33.0 : Verbose - handleRedirectPromise has been called for the first time, storing the promise auth-config.ts:78:32
16:24:08.022 [Fri, 02 Jun 2023 13:24:08 GMT] : [60fdb4b9-fac4-45b4-9dd2-d7c2610cb4ec] : msal.js.browser@2.33.0 : Verbose - initializeServerTelemetryManager called auth-config.ts:78:32
16:24:08.022 [Fri, 02 Jun 2023 13:24:08 GMT] : [60fdb4b9-fac4-45b4-9dd2-d7c2610cb4ec] : msal.js.browser@2.33.0 : Info - handleRedirectPromise called but there is no interaction in progress, returning null. auth-config.ts:75:32
16:24:08.022 [Fri, 02 Jun 2023 13:24:08 GMT] : @azure/msal-browser@2.33.0 : Info - Emitting event: msal:handleRedirectEnd auth-config.ts:75:32
16:24:08.022 [Fri, 02 Jun 2023 13:24:08 GMT] : @azure/msal-browser@2.33.0 : Verbose - Emitting event to callback 2a169cea-166c-4cbc-b254-aebecc3b18f1: msal:handleRedirectEnd auth-config.ts:78:32
16:24:08.022 [Fri, 02 Jun 2023 13:24:08 GMT] : @azure/msal-angular@2.5.3 : Verbose - BroadcastService - msal:handleRedirectEnd results in setting inProgress from handleRedirect to none auth-config.ts:78:32
16:24:08.022 [Fri, 02 Jun 2023 13:24:08 GMT] : @azure/msal-browser@2.33.0 : Verbose - getAllAccounts called 2 auth-config.ts:78:32

There is no useful information in the log above, it doesn't say why the application stuck at the auth address

**Comment by jo-arroyo** [comment]
@SamShekhovtsov Is the `MsalRedirectComponent` bootstrapped in your app.module.ts and selector added to the index.html? Please see instructions [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/redirects.md#1-msalredirectcomponent-a-dedicated-handleredirectobservable-component).

**Comment by SamShekhovtsov** [comment]
@jo-arroyo let me try that. I didn't bootstrap the `MsalRedirectComponent` . However, I don't think that this can help, because the Url address where the application stuck is `http://localhost:4200/auth#state=....` the auth route is configured correctly in the application routing file.

**Comment by SamShekhovtsov** [comment]
@jo-arroyo  the MsalRedirectComponent is fully bootstrapped according to the instructions in that article, I have just double checked that. However, it still doesn't work as expected. The page stopped loading at the `http://localhost:4200/auth#state=....` and not moves forward.

**Comment by sameerag** [comment]
@SamShekhovtsov Can you please share the server trace as I suspect MSAL is not being rendered after you get stuck, the server probably is not redirecting you. You can share your logs [here](https://github.com/konstantin-msft).

**Comment by SamShekhovtsov** [comment]
@sameerag what should I do to get the server trace? How should I get that?

**Comment by tnorling** [comment]
@SamShekhovtsov When you reopen the browser are you opening your app then navigating the B2C login or are you directly opening the B2C login page?

**Comment by SamShekhovtsov** [comment]
@tnorling directly opening the B2C login page, because it's automatically done by browser engine when restoring the previous browser session. The browser is closed with the B2C login page and later opened with previous session automatic restore - which is the B2C login page.

**Comment by tnorling** [comment]
This is not a supported scenario unfortunately. MSAL needs to both, initiate the request and handle the response in a single session. The request artifacts necessary to complete the flow are lost when the tab is closed.
