### ISSUE TITLE
User account selection required even as logoutHint is provided

### ISSUE THREAD

**Issue by rkreddy99** [AzureAD/microsoft-authentication-library-for-js#6082]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

"^2.30.0"

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

"^1.4.9"

### Public or Confidential Client?

Public

### Description

Even though I used UserPrincipalName as logoutHint parameter, i still have to select the account to logout in react application

```typescript
instance.logoutRedirect({
        logoutHint: userprinicalname,
    });
```

PS: I am not deriving it from the id token claims because I am not storing in anywhere, as I have my custom session in the db. I am using azure ad just for using an existing users list.

  

### MSAL Configuration

```javascript
{
    auth: {
        clientId: process.env.REACT_APP_AZURE_AD_CLIENT_ID as string,
        authority: `https://login.microsoftonline.com/${process.env.REACT_APP_AZURE_AD_TENANT_ID}`,
        redirectUri: `${process.env.REACT_APP_URL}/login`,
        postLogoutRedirectUri: `${process.env.REACT_APP_URL}/login`,
        navigateToLoginRequestUrl: false,
    },
    cache: {
        storeAuthStateInCookie: true,
    },
    system: {
        loggerOptions: {
            loggerCallback: (level, message, containsPii) => {
                if (containsPii) {
                    return;
                }
                switch (level) {
                    case LogLevel.Error:
                        console.error(message);
                        return;
                    case LogLevel.Info:
                        console.info(message);
                        return;
                    case LogLevel.Verbose:
                        console.debug(message);
                        return;
                    case LogLevel.Warning:
                        console.warn(message);
                        return;
                }
            },
        },
    },
};
```

### Relevant Code Snippets

```javascript
const handleLogout = async (instance: IPublicClientApplication) => {
    await instance.logoutRedirect({
        logoutHint: userprincipalname,
    });
};
```

### Reproduction Steps

- Authenticate the user using azure ad and get the access token, and store just the userprincipalname in localStorage per say
- Click on the logout button which calls the above logout function and provide upn as logoutHint

### Expected Behavior

Session should be logged out without the need for the user to select account from the prompt

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@rkreddy99 Have you followed all the instructions from out [logout doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md), specifically, for [promptless logout](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md#promptless-logout)?

**Comment by rkreddy99** [comment]
@jo-arroyo Yes, i have followed the instructions as per the doc. Except for providing the logoutHint in the logout function I dont think it mentions anything else to be done.

Also i had another doubt about front channel logout, is it only called when the user clicks on logout or even when the browser session for azure ad login expires. I want this to make the authentication in sync with the browser session for azure ad.

**Comment by sameerag** [comment]
@rkreddy99 Frontchannel logout is usually triggered only when we call the `/logout` end point which is when the user clicks logout. I can check with the service team is there is any other way to trigger this. 

Can you please share your fiddler trace when you pass the `login_hint` and you still see the prompt? You can send the logs to my [profile](https://github.com/sameerag)

**Comment by sameerag** [comment]
cc @konstantin-msft Shared the logs offline.

**Comment by konstantin-msft** [comment]
Hi @rkreddy99.
There is no call to the `logoutRedirect` API captured in the trace file. Can you please make sure to capture the whole session and email the fiddler trace to [my profile](https://github.com/konstantin-msft)?
