### ISSUE TITLE
loginRedirect with codeChallenge?

### ISSUE THREAD

**Issue by davidwitten** [AzureAD/microsoft-authentication-library-for-js#6088]
### Core Library

MSAL.js (@azure/msal-browser)

### Wrapper Library

MSAL React (@azure/msal-react)

### Public or Confidential Client?

Public

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/42dd47713c8c8e362fa3cd54cbf7367140d9fb06/lib/msal-browser/src/request/RedirectRequest.ts#L40-L41C1

### Description

Based on the documentation linked above, it seems like this should work:

```
msalInstance.loginRedirect({ 
        codeChallenge: 'sB9MtOglgWOYU2i_NR7L-RQYgngIj05p2BkvcSe6bW0', 
        codeChallengeMethod: "S256", 
        scopes, 
        prompt 
      });
```
However, the actual loginRedirect ignores this. The reason I need this is because I get the `code` and then have to make this request:

```
    const response = await axios.post(
        'https://login.microsoftonline.com/common/oauth2/v2.0/token',
        qs.stringify({
            client_id,
            client_secret,
            code: req.query.code,
            redirect_uri,
            grant_type: 'authorization_code',
            code_verifier,
          }),
```

**Comment by jo-arroyo** [comment]
@davidwitten No, the `RedirectRequest` type omits `codeChallenge`, and loginRedirect is not designed to log in with `codeChallenge`.
