### ISSUE TITLE
Remove accounts from the cache

### ISSUE THREAD

**Issue by georgiosApo** [AzureAD/microsoft-authentication-library-for-js#6089]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.32.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.5.2

### Public or Confidential Client?

Public

### Description

I would like a way to clear accounts from the cache. It seems like the clearCache method on the PublicClientApplication object doesn't exist anymore.

My hope was to iterate over the accounts and do some conditional check to determine if the account should be set to active or be removed depending on env. setActiveAccount works fine but I can't seem to find the clearCache method.

Seems to have existed in the past following this thread:
https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1545

Maybe it has been renamed or moved somewhere else?

Any pointers are much appreciated, thanks in advance!

Regards,
G

### Identity Provider

None

### Source

Internal (Microsoft)

**Comment by jo-arroyo** [comment]
@georgiosApo We do not currently have a method for removing specific accounts from the cache. Are there additional reasons why setting the active account does not meet your app's need?

**Comment by georgiosApo** [comment]
Hello @jo-arroyo!

That's no problem, just wondered if there was a way to achieve that programmatically.

Thanks for your reply!

**Comment by jo-arroyo** [comment]
@georgiosApo Alternatively, you could sign out locally, which will clear the cache locally but keep the session on the server. You can find instructions [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md#skipping-the-server-sign-out).
