### ISSUE TITLE
Angular V16 => initialNavigation

### ISSUE THREAD

**Issue by Alan-Lun** [AzureAD/microsoft-authentication-library-for-js#6090]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.0.0-alpha.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.0-alpha.0

### Public or Confidential Client?

Public

### Description

I want to refactor it into a separate architecture.
Remove ngModule, but initialNavigation cannot be replaced

initialNavigation How to rewrite

### Relevant Code Snippets

```javascript
@NgModule({
    imports: [
        RouterModule.forRoot(routes, {
          scrollPositionRestoration: 'enabled',
          anchorScrolling: 'enabled',
          onSameUrlNavigation: 'reload',
          // Question
          initialNavigation: !BrowserUtils.isInIframe() && !BrowserUtils.isInPopup() ? 'enabledNonBlocking' : 'disabled' 
        })
    ],
    exports: [RouterModule]
})
export class AppRoutingModule {
}


app.config.ts


import { ApplicationConfig } from '@angular/core';
import {provideRouter, withInMemoryScrolling, withRouterConfig} from '@angular/router';
import { provideHttpClient } from '@angular/common/http';

import { routes } from './app.routes';
import {BrowserUtils} from "@azure/msal-browser";

export const appConfig: ApplicationConfig = {
  providers: [
    provideRouter(routes, withRouterConfig({
      onSameUrlNavigation: 'reload',

    }),withInMemoryScrolling({
      scrollPositionRestoration:'enabled',
      anchorScrolling:'enabled',
    })),
    provideHttpClient()
  ]

};
```

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by Alan-Lun** [comment]
any update?

**Comment by jo-arroyo** [comment]
@Alan-Lun Can you please provide a bit more detail about what you're looking to achieve here?

**Comment by Alan-Lun** [comment]
I used to write Angular 15 AppRoutingModule with reference to the example, now I am upgrading to Angular 16 Standalone, and then in the Angular 16 Standalone example, I am no longer using NgModule, I am now doing the migration and hope to transfer the AppRoutingModule to app.config.ts, but I found that there is no initialNavigation on ApplicationConfig, I would like you to tell me how to set initialNavigation: !BrowserUtils.isInIframe() && !BrowserUtils.isInPopup() ? 'enabledNonBlocking' : 'disabled' paragraph to achieve the same effect

**Comment by jo-arroyo** [comment]
@Alan-Lun MSAL Angular v3 does not fully support standalone components yet, but it is under investigation. Closing as duplicate feature request. Please see #6080 for updates and releases.
