### ISSUE TITLE
TypeError: this._history.replaceState is not a function - in office.js

### ISSUE THREAD

**Issue by JimbobTheSailor** [AzureAD/microsoft-authentication-library-for-js#6091]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.0.0-alpha.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.0-alpha.0

### Public or Confidential Client?

Public

### Description

Error occurs when navigating within a callback that fires after authentication is complete. Error began occuring in otherwise stable code after updadting to Angular 16 (from 15) and to 3.0.0.alpha (from 2.37.0)

I note that his error has occurred in the past https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2488

 

I does appear that I can work around the issue by using "skipLocationChange"
    this.router.navigate([`${myUrl}`], {skipLocationChange: true}));

### Error Message

"Unhandled Navigation Error: TypeError: this._history.replaceState is not a function"

>  | (anonymous) | @ | auth.service.msal.ts:678
>  | callbackLoginHelper | @ | auth.service.msal.ts:678
>  | Promise.then (async) |   |  
>  | (anonymous) | @ | excel-win32-16.01.js:25
>  | OSF.DDA.issueAsyncResult | @ | excel-win32-16.01.js:25
>  | onComplete | @ | excel-win32-16.01.js:25
>  | (anonymous) | @ | excel-win32-16.01.js:25
>  | agaveResponseCallback | @ | VM117:1
>  | window.agaveHostCallback | @ | VM117:1
>  | (anonymous) | @ | VM157:1

### MSAL Configuration

```javascript
const browserAuthOptions:BrowserAuthOptions = 
{
	clientId: 'xxx', 
	authority: 'https://login.microsoftonline.com/common', 
	redirectUri: 'https://localhost:3000', 
	postLogoutRedirectUri: '/', 
	navigateToLoginRequestUrl: true, 
}
 const cacheOptions: CacheOptions=
{
	cacheLocation: BrowserCacheLocation.LocalStorage, 
	storeAuthStateInCookie: isIE, 
}

//const x: RedirectRequest;
const browserSystemOptions:BrowserSystemOptions=
{
	loggerOptions: {
		loggerCallback(logLevel: LogLevel, message: string) {
			console.log(">>MSAL Main Log",message);
		},
		logLevel: LogLevel.Error,
		piiLoggingEnabled: false
	}
}
```

### Relevant Code Snippets

```javascript
this.ngZone.run(() => this.router.navigate([`${myURL}`]));
```

### Reproduction Steps

1. 

### Expected Behavior

The error should not occur, and navigation continue

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Other

### Regression

2.37.0

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@JimbobTheSailor Thanks for bringing this to our attention. I will look into this issue and update with findings soon.

**Comment by JimbobTheSailor** [comment]
I am not certain what author feedback is required from me?

**Comment by tnorling** [comment]
@JimbobTheSailor Can you please clarify if this is being thrown by msal-angular or by the code snippet you shared: ```this.ngZone.run(() => this.router.navigate([`${myURL}`]));```

I don't believe the replaceState function is available in an Office add-in so you won't be able to use APIs which invoke it. That's not something MSAL controls so there's not much we can do about that unfortunately.

**Comment by dzivoing** [comment]
I wouldnt mark it as stale because i have the same problem half a year later
