### ISSUE TITLE
LocalStorage not working with loginRedirect

### ISSUE THREAD

**Issue by snirbenyosef** [AzureAD/microsoft-authentication-library-for-js#6092]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.37.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

m currently working on integrating Azure authorization into my Vue.js Single Page Application (SPA) using the msal.js package. My goal is to find an elegant way to save the accessToken to localStorage. Since it's an SPA, I acquire the token when the application loads for the first time. After the redirect, I have to refresh the page for the token acquisition function to run, and its bad, so i created a redreict page where i do fetchAccessToken(), see snipping below, and then it redreict me to the desire page.

Many websites use a middle page that shows a countdown (e.g., "You will be redirected in 5, 4, 3, 2, 1...") to provide a better user experience. I want to implement something similar to enhance the UX feeling for the user. I'm trying to use the loginRedirect function with localStorage configured.

However, I'm facing a few issues:

First, for some reason, the cache items are saved in sessionStorage instead of localStorage as I have configured. I'm not sure why this is happening. Do you have any ideas?

Second, on the redirect page, when I call msalInstance.getAllAccounts(), it returns an empty list. I'm not sure what I'm doing wrong in the flow.

### Msal Logs

@azure/msal-browser@2.37.0 : Info - Emitting event: msal:loginStart

### MSAL Configuration

```javascript
const MSAL_CONFIG = {
  auth: {
    clientId: "clientid",
    authority: "authorities.signIn",
    knownAuthorities: [...knownAuthorities],
    redirectUri: "http:://localhost:3000/redirect-page",
  },
  cache: {
    cacheLocation: "localStorage",
    storeAuthStateInCookie: false,
  },
};
```

### Relevant Code Snippets

```javascript
initMsalInstance() {
  this.msalInstance = new msal.PublicClientApplication(MSAL_CONFIG);
},

openLoginRedirect() {
  this.initMsalInstance();
  this.msalInstance.loginRedirect();
},

async fetchAccessToken() {
  // Get all accounts from the cache
  const accounts = this.msalInstance.getAllAccounts();
  // Perform some work if accounts are found, such as getting the token and saving it...
}
```

### Reproduction Steps

1. Create a vue app with vite and pinia
2. configure msal Instance and a redreiect page.
3. try login, redriect to Rederdict-page, try catching the token, msalInstance.getAllAccounts() is allways 0.

### Expected Behavior

using LoginRedirect should move me to the redried page, then there i can use acquireTokenSilent in order to save it and continue to the next page.

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari

### Source

Internal (Microsoft)

**Comment by sameerag** [comment]
@snirbenyosef Sorry delayed responding to this. We store some temporary cache in `sessionStorage` but if you have mentioned `localStorage` in configuration, the tokens should be ideally stored in `localStorage`. 

Can you confirm you have a successful token response? I do not see the handling response code for `redirect`, usage is [here] (https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-browser-samples/VanillaJSTestApp2.0/app/default/auth.js), calling `handleRedirectPromise()`.
