### ISSUE TITLE
Can I get a id_token without the refresh token? 

### ISSUE THREAD

**Issue by hschell-cortado** [AzureAD/microsoft-authentication-library-for-js#6093]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.0

### Public or Confidential Client?

Public

### Description

I want to get an id token and no refresh token but I cant get no refresh token. Why is that? Can I get a id/access token without a refresh token? Having a refresh token poses a security issue for my needs. see also https://learn.microsoft.com/en-us/azure/active-directory/develop/reference-third-party-cookies-spas#security-implications-of-refresh-tokens-in-the-browser

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by sameerag** [comment]
@hschell-cortado We currently do not support fetching `idToken` and `accessToken` without `refreshToken`. Please note that the security concern you mentioned in the above link is why we limit the RT to 24 hrs without extending it for `SPA` type applications.

**Comment by hschell-cortado** [comment]
Ok thanks for the reply, I see your point but 24h doesnt really fix the problem when you can get another refresh token with the first and so on. maybe consider having the option to skip refresh token. Thanks for your time.

**Comment by sameerag** [comment]
Sure. We have noted this feedback and consider if supporting this is feasible at some point. Thanks for the patience.
