### ISSUE TITLE
Azure B2C Msal-Angular v2.5.7 works fine in all browsers except the latest version of safari

### ISSUE THREAD

**Issue by fokerone** [AzureAD/microsoft-authentication-library-for-js#6097]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.37.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.5.7

### Public or Confidential Client?

Public

### Description

I Take the example proyect for b2C with Angular 14 and Msal v2. from the official repo:
https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v2-samples/angular-b2c-sample-app
 I was able to log in with chrome and firefox, but with the latest version of safari v16.3.1 it enters an infinite loop
The login gets the token and gets the user account then returns to the login screen once there, go back to the app and repeat.

Disabling ITP in Safari everything works without problems.
This behavior occurs on mac os and iphone.

This problem was not solved with Msal 2.0?

what am I doing wrong?

### MSAL Configuration

```javascript
auth: {
      clientId: environment.clientId,
      authority: b2cPolicies.authorities.signUpSignIn.authority,
      redirectUri: environment.frontBaseURL,
      postLogoutRedirectUri: environment.frontBaseURL,
      navigateToLoginRequestUrl: true,
      knownAuthorities: [b2cPolicies.authorityDomain]
    },
    cache: {
      cacheLocation: 'localStorage',
      storeAuthStateInCookie: false
    },
    system: {
      allowNativeBroker: false, // Disables WAM Broker
    }
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by sameerag** [comment]
If 3P cookies are blocked, MSAL JS cannot work unfortunately. Looks like that is the case here when ITP is enabled. Just to be sure, can you please share your code snippet on how you are handling the redirect response? The usage is documented [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/redirects.md).

**Comment by submarines-and** [comment]
Wasn't one of the advantages of MSAL2 that cookies were no longer needed? Is ITP still not supported with msal2?

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/3114694/9cf6bde2-6e8e-439b-a1bc-d53cdcedd483)

https://learn.microsoft.com/en-us/azure/active-directory/develop/reference-third-party-cookies-spas

**Comment by fokerone** [comment]
Sorry for the delay in responding, I confirm that Safari works with Msal2.0, the problem was using localhost to do the tests, once testing in the final domain it works without problems and the itp does not affect the login mechanism

Tks!

**Comment by sameerag** [comment]
Great. Thanks for getting back.
