### ISSUE TITLE
How to work with azure storage file share content

### ISSUE THREAD

**Issue by baoj-dfo** [AzureAD/microsoft-authentication-library-for-js#6098]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.5.6

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

    "@azure/msal-angular": "^2.5.6"

### Public or Confidential Client?

Confidential

### Description

What is the right way to retrieve file content of azure storage account for browser Angular app?
1) http get File service API: https://learn.microsoft.com/en-us/rest/api/storageservices/get-file
2) using typescript SDK:  https://learn.microsoft.com/en-us/samples/azure/azure-sdk-for-js/storage-file-share-typescript

### Relevant Code Snippets

```javascript
would be nice if code snip can be provided for Azure AD authentication, not SAS
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by sameerag** [comment]
@baoj-dfo Are you looking for help with `AzureSDK`? Our samples [https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples] do cover AzureAD access if that is what you are looking for.

**Comment by baoj-dfo** [comment]
@sameerag  I am familiar with the sample code, and I've already consume the Azure management api from angular app for long time. 
My scenario is to call  File service rest api: https://myaccount.file.core.windows.net/myshare/mydirectorypath/myfile
I guess it is different from call management api: "https://management.azure.com", there could be more setting in MSAL that I might missing.

I can't find sample code online. MSAL with  https://learn.microsoft.com/en-us/rest/api/storageservices/get-file
and for this https://learn.microsoft.com/en-us/samples/azure/azure-sdk-for-js/storage-file-share-typescript/, seems with SAS or key, haven't mentioned about AAD authentication.

Thanks

**Comment by sameerag** [comment]
Can you talk to AzureSDK folks who may have an API for you? They built on top of MSAL JS but their interfacing could be different.

**Comment by baoj-dfo** [comment]
@sameerag 
The only AzureSDK JavaScript sample code for browser app I can found is:
https://github.com/Azure-Samples/AzureStorageSnippets/blob/master/blobs/quickstarts/JavaScript/V12/azure-blobs-js-browser/index.js
which unfortunately  use sasUrl, didn't even reference "@azure/identity"
line 41:       const blobSasUrl = "<placeholder>";

**Comment by sameerag** [comment]
@KarishmaGhiya Can you help here?

**Comment by baoj-dfo** [comment]
For browser case, MS recommend using the InteractiveBrowserCredential instead of the DefaultAzureCredential.
https://github.com/Azure/azure-sdk-for-js/issues/12334
can't find an example to use InteractiveBrowserCredential for browser app case.

All I can find are console app with JavaScript:
https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/storage/storage-blob/samples/v12/javascript/azureAdAuth.js

**Comment by tnorling** [comment]
There's [some instructions](https://www.npmjs.com/package/@azure/storage-blob#with-defaultazurecredential-from-azureidentity-package) in the readme for that package to authenticate with AAD. Please try that out and if you have further questions I recommend opening an issue on the Azure SDK repo as we do not own that package. If you have questions specific to MSAL please open a new issue. Thanks!
