### ISSUE TITLE
Error after Angular upgrade 

### ISSUE THREAD

**Issue by MohammadBoushi** [AzureAD/microsoft-authentication-library-for-js#6099]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.33.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.5.3

### Public or Confidential Client?

Public

### Description

Hi there, 
after angular upgrade from angular 15 to 16 i am getting this error : "ncaught Error: NG0204: Can't resolve all parameters for MsalInterceptor: (?, ?, ?, ?, ?)."

before the upgrade worked everything very well.
 
is there any suggestion?

### MSAL Configuration

```javascript
export function MSALInstanceFactory(clientId: string, authority: string, hostUrl: string): IPublicClientApplication {
  return new PublicClientApplication({
    auth: {
      clientId: clientId,
      authority: authority,
      redirectUri: hostUrl,
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE,  
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Info,
        piiLoggingEnabled: false,
      },
    },
  });
}
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by sameerag** [comment]
@MohammadBoushi Using `msal-angular v2` with Angular 16 will break. Can you please upgrade to our [v3 alpha release](https://github.com/AzureAD/microsoft-authentication-library-for-js/releases/tag/msal-angular-v3.0.0-alpha.2) and try?

**Comment by sp90** [comment]
It broke my build, what are the breaking changes that have been done from v2-v3

**Comment by sp90** [comment]
After digging a bit; 

First of note that `"msal-angular": "3.0.0-alpha.2"` has a dependency on `"msal-browser": "3.0.0-alpha.2"` - have not tested if you can mix alpha versions or its still to fragile that they need to be in sync

Secondly docs for breaking changes:
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-v3-upgrade-guide.md

**Comment by sp90** [comment]
Currently, it seems impossible to get to work with a standalone bootstrapped application, it's hard to really understand the ins and outs of how to configure it

My dream configuration is:

```ts
bootstrapApplication(AppComponent, {
  providers: [
    ...Other app config
    
    provideMsalAngular({
      All config needed...
    })
  ]
});
```
And then this should allow 

```js
const routes: Routes = [
  {
    path: 'guarded',
    canActivate: [MsalGuard],
    loadComponent: () => import('msal-angular-redirect'),
    loadChildren: () => [
      guarded routes...
    ]
  }
]
```

I'm hoping for a better guide soon, since msal is currently the only blocker for v16 upgrade

**Comment by jo-arroyo** [comment]
@sp90 Apologies, MSAL Angular v3 does not fully support standalone bootstrapped applications yet, but it is under investigation. We are aware that this is blocking for some applications. I will close this issue as a duplicate, updates and releases will be tracked at #6080.

**Comment by sp90** [comment]
@jo-arroyo I find that odd since v2.5.x did :S
