### ISSUE TITLE
Slow msalSubject$ subscription. Is there a way to get logged user info faster after redirect?

### ISSUE THREAD

**Issue by georgyevv** [AzureAD/microsoft-authentication-library-for-js#6100]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.0.0-alpha.2

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.0-alpha.2

### Public or Confidential Client?

Public

### Description

I'm using login redirect. After redirecting and successfully login I'm redirected back to my app login page but it takes so much time to get the subscription result from this.msalBroadcastService.msalSubject$ in order to set the active account that the app manages to render the login screen for a second and then redirect to home page. This flickering for 1-2 seconds is not okay for the business.

I'm handling the subscription in the app component for the highest chance to catch it as early as possible but it is still very slow.
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/13435068/51e67f5a-f68b-49d8-8895-8c7d382abdb1)

Is this msalSubject$ making a request in order to get the data and that's why it's so slow? Am I missing something or is there a configuration that can help to catch the successful login after redirection faster so I can at least show the loading indicator that the information is still processing?

Thank you in advance!

### MSAL Configuration

```javascript
{
    auth: {
      clientId: authConfig.msalConfig.auth.clientId,
      authority: authConfig.msalConfig.auth.authority,
      redirectUri: window.location.origin,
      postLogoutRedirectUri: window.location.origin
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: true
    },
    system: {
      allowNativeBroker: false,
    }
  }
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by sameerag** [comment]
@georgyevv Are you getting the response faster than the event flag?  Redirect usually is handled with a call back once the page is reloaded. Can you separate the page reload time vs the broadcast message?

1-2 sec is unusually long, If you can collect the logs with time stamps, that would probably help us narrow down the issue. Logging instructions for angular are [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-docs/logging.md).
