### ISSUE TITLE
Link to react-aad-msal wrapper library in readme?

### ISSUE THREAD

**Issue by AndrewCraswell** [AzureAD/microsoft-authentication-library-for-js#611]
Many of the consumers of MSAL.js (especially at Microsoft) are building React apps, a reflection on the fact that Microsoft has bet very heavily in React, especially in orgs like Office, Windows, etc. I know it's a huge undertaking to support a new framework to the level that Angular is being covered. Maybe a compromise would be to link to the `react-aad-msal` community driven project that was built by a group from CSE. I'm thinking it could make sense to add a mention in the `readme.md` under the Wrapper Libraries section, denoting it as a community project.

In lieu of a better option and no timeline for an official React wrapper, I think giving visibility to the community members solving the problem could help drive more contributions.

https://github.com/syncweek-react-aad/react-aad

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

**Comment by AndrewCraswell** [comment]
If this is something that others think would be a good idea, I'd be happy to submit the PR.

**Comment by navyasric** [comment]
@AndrewCraswell Thank you for the feedback and suggestion. We would need to evaluate community built open source libraries for criteria like maintenance, security, code quality, etc. before we recommend or list it on the Msal.js Readme or docs.
As mentioned in #510, React support is in our backlog. Per the roadmap, we are currently working on the core library followed by Angular improvements. Please watch the wiki for a refresh of the roadmap around May.

**Comment by AndrewCraswell** [comment]
Thanks for the response, @navyasric. I totally understand, and the project is there linked above ready to be evaluated. I've seen #510 but didn't see any timeline mentioned. In fact, it seems from the issue while a React wrapper is in the backlog, it's not being prioritized. The roadmap currently has no mention of React, which is fair since it's articulated numerous times that Angular and AngularJS is the priority.

Since a React wrapper is not a priority on the map, and there's no timeline for such a feature, it would be a big help to reference other options from the community trying to solve the problem. I think a fair compromise is to evaluate the solution referenced above and either link it or provide your feedback. Is that something you think is likely to happen?
