### ISSUE TITLE
Angular v16 two consequent redirects

### ISSUE THREAD

**Issue by gultyayev** [AzureAD/microsoft-authentication-library-for-js#6116]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.0.0-alpha.2

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.0-alpha.2

### Public or Confidential Client?

Public

### Description

I'm using Angular v16 full standalone. In `AppComponent.ngOnInit` I've placed
`this.#msalService.handleRedirectObservable().subscribe()`.

When I first load the page a request to `sections` is made which triggers redirect to AD. After I authenticate I am redirected back to localhost. After that I'm redirected once again back to AD. Again, I have to authenticate and am redirected back to localhost.

After that I observe two requests for `token` and a request to `sections` with the token attached.

### MSAL Configuration

```javascript
{
  auth: {
    clientId: '',
    authority: '',
    redirectUri: 'http://localhost:4200'
  }
}

Not sharing id & authority for security reasons.
```

### Relevant Code Snippets

`app.config.ts` is following

```typescript
export const appConfig: ApplicationConfig = {
  providers: [
    provideHttpClient(withInterceptorsFromDi()),
    {
      provide: HTTP_INTERCEPTORS,
      useClass: MsalInterceptor,
      multi: true,
    },
    importProvidersFrom(
      MsalModule.forRoot(
        new PublicClientApplication({ ... }),
        { interactionType: InteractionType.Redirect },
        {
          interactionType: InteractionType.Redirect,
          protectedResourceMap: new Map([ ['sections', ['']] ])
        }
      )
    )
  ]
}
```

`app.component.ts`

```typescript
export class AppComponent {
  #http = inject(HttpClient)
  #msal = inject(MsalService)

  ngOnInit() {
    this.#msalService.handleRedirectObservable().subscribe()
    this.#http.get('sections').subscribe()
  }
}
```

### Reproduction Steps

1. Scaffold Angular v16 app in standalone
2. Add the MSAL libs that support Angular v16
3. Provide the required providers like in my samples
4. Handle the redirect in `ngOnInit` for `AppComponent` and make a request to the protected route

### Expected Behavior

I would expect that I am redirected only once and there only one request to the `token` instead of two (sequential).

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by sameerag** [comment]
@gultyayev Is this on the sample we provided? Can you share logs? You can email them to [me](https://github.com/sameerag).

**Comment by sp90** [comment]
Could this be related to #6080 and #6099 - do you @gultyayev use a standalone bootstrapped app?

**Comment by gultyayev** [comment]
> Could this be related to #6080 and #6099 - do you @gultyayev use a standalone bootstrapped app?

Yes. I use a standalone bootstrapped app. However, I don't experience any errors. Only double redirection.

> Is this on the sample we provided?

No this is on our internal project.

**Comment by gultyayev** [comment]
Right now it stopped making 2 redirects all of a sudden. However, in the Network tab I still see 2 requests for the token. The interesting thing is that the second request starts only when the first is finished. Response size is the same for both of the requests. Second request contains way more fields in FormData.

This happens only after the login. If I refresh the page the token obtained only once.

**Comment by sameerag** [comment]
Is it possible there is a re-authentication in any of the routes?

**Comment by gultyayev** [comment]
> Is it possible there is a re-authentication in any of the routes?

Currently, there are no routes. The app is just being created and there is just one AppComponent. It has one single request to `sections` to test the SSO integration.

**Comment by konstantin-msft** [comment]
Hi @gultyayev. 
There are not enough details about your standalone app to reproduce the issue. May I ask you to reproduce it [with our sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v3-samples/angular16-sample-app) and share the result? Providing us with the [verbose logs](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logging.md) would be of great help as well.
Thank you.

**Comment by konstantin-msft** [comment]
cc @jo-arroyo
