### ISSUE TITLE
Crash while attempting transformation on CIAM_AUTHORIY

### ISSUE THREAD

**Issue by dylank** [AzureAD/microsoft-authentication-library-for-js#6128]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.32.2

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.5.2

### Public or Confidential Client?

Public

### Description

Looks like we expected a string and got an undefined 

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/749842/665e9e5d-c781-44aa-a4cf-a03ebea0f473)

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/src/authority/Authority.ts#L1094

### Msal Logs

```
client_info: 1
x-client-SKU: msal.js.browser
x-client-VER: 2.37.0
x-ms-lib-capability: retry-after, h429
x-client-current-telemetry: 5|61,0,,,|@azure/msal-react,1.5.7
x-client-last-telemetry: 5|3|61,004984ad-7711-466c-bf65-8e871d15b2e1,61,8a0fab58-db44-4f4e-ad2f-d4df18b5d426,61,8fd04a66-60ac-454d-aa56-6eda4434d89e,61,9c816e47-c96d-4bfb-98f6-951a578dc9b3,61,4e00f47f-4e05-4ef3-aa1c-033470a6626f|post_request_failed,post_request_failed,post_request_failed,post_request_failed,post_request_failed|11,1
client-request-id: 41c7bca7-a23b-4b9b-963b-362723179faf
```

### MSAL Configuration

```javascript
{
  auth: {
    clientId: "clientId",
    authority: "https://login.microsoftonline.com/common/"
  },
  cache: {
    cacheLocation: "sessionStorage"
    storeAuthStateInCookie: false
  }
}
```

### Relevant Code Snippets

```javascript
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/src/authority/Authority.ts#L1094
```

### Reproduction Steps

1. Load app using msal-react
2. Refresh the page

### Expected Behavior

No crash?

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by konstantin-msft** [comment]
Hi @dylank. Can you please share the full code snippet? I am not able to reproduce the error using your MSAL config with [react-18](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/msal-lts/samples/msal-react-samples/react-18-sample) sample.
Also, you are missing comma after `cacheLocation` attribute.
