### ISSUE TITLE
tslib version

### ISSUE THREAD

**Issue by MaximBalaganskiy** [AzureAD/microsoft-authentication-library-for-js#613]
## I'm submitting a...
<pre><code>
[x] Question
</code></pre>

## Library version
<pre><code>
Library version: 0.2.4
</code></pre>

Is there any specific reason to use the tslib@1.7.1 version? This leads to the duplication if a project wants to use the latest of tslib.

**Comment by DarylThayil** [comment]
unsure why this was done, good catch will make a pr for this
