### ISSUE TITLE
State parameter in login request - Angular MSAL

### ISSUE THREAD

**Issue by vramasam** [AzureAD/microsoft-authentication-library-for-js#614]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [X ] Chrome version XX
- [X] Firefox version XX
- [X] IE version XX
- [X] Edge version XX
- [ ] Safari version XX

## Library version : Current Version 0.1.2 

<pre><code>
Library version: X.Y.Z : Current Version 0.1.2 

## Current behavior

Not able to get the state passed by the client.

## Expected behavior

Need to pass the state to MSAL library and expecting the same state in the response callback for client.

## Additional information

STEP 1 : If the User is accessing a deep link URL which needs Microsoft Authentication.
STEP 2: Client needs to set the URL information as a state parameter in AD request happening through Angular MSAL. (To preserve the URL information until login succeed).
STEP 3: After successful login, client expecting the state information in the AD response callback.
STEP 4: Client retrieves the  AD response  information and extract the state parameter.

Above is the use case. Currently state information is not maintained  in Angular MSAL latest version. Please fix this issue.

We have seen this issue has been fixed in Core JS https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/262. Let us know how to handle this issue using Angular MSAL.

</code></pre>

**Comment by vramasam** [comment]
Hi @sameerag 

If there is any update on this ticket. Can you please provide to us?

**Comment by sameerag** [comment]
Yes, should be committed this week. Will update here once I have a PR out.

**Comment by sameerag** [comment]
@vramasam There is an issue with 'state' where we are not stripping the GUID we add in MSAL JS when the user sets the 'state' in the request. But this change will make it only to msal-core and not to msal-angular at this point. Are you looking at a fix for angular? As mentioned in the homepage by @navyasric we are currently in middle of an API change for msal-core and hence no angular support is expected immediately.

My apologies for the previous comment as I assumed this is for core when I was mentioning that comment as this looked similar to an issue I am fixing in the core library.

**Comment by sameerag** [comment]
This issue is being fixed in the core library with #548. Angular adaption when it happens will automatically pick this up (as angular is a wrapper) on our core library. Please check our [roadmap](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/548) for updates on the same periodically.

**Comment by sameerag** [comment]
@vramasam The original state issue is now fixed with msal core 1.0.0; angular wrapper update is planned for this summer and the [roadmap](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#roadmap) will be updated with more details as and when we start on this activity.

**Comment by sameerag** [comment]
Linking this to #786. This is fixed in the lastest msal 1.0.x, but angular wrappers cannot use this until the upgrade happens.

**Comment by artmasa** [comment]
> Linking this to #786. This is fixed in the lastest msal 1.0.x, but angular wrappers cannot use this until the upgrade happens.

Did the wrapper was changed to use this fix?
