### ISSUE TITLE
Logout Redirection Issue from Microsoft Services using MSAL Library

### ISSUE THREAD

**Issue by Awolwe** [AzureAD/microsoft-authentication-library-for-js#6150]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.34.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Confidential

### Description

When using the MSAL library for JavaScript in conjunction with Microsoft services like Planner or Outlook, there is an issue with the logout functionality. After logging out from the MSAL library, the user is not redirected back to my website as expected. This issue occurs when the user is signed in through MSAL and then logs out from a Microsoft service.

Actual Behavior:
After logging out from only the MSAL library, the user is not redirected back to my website. The redirection to the appropriate website is not occurring as expected.

Additional Information:

This issue affects the user experience on my website, as users are not being properly redirected after logging out from the MSAL library.

### MSAL Configuration

```javascript
const msalConfig = {
  auth: {
    clientId: process.env.VUE_APP_AZURE_CLIENT_ID,
    authority: 'https://login.microsoftonline.com/' + process.env.VUE_APP_AZURE_TENANT_ID, 
    redirectUri: process.env.VUE_APP_BASE_URL + '/login',
  },
  cache: {
    cacheLocation: "sessionStorage",
    storeAuthStateInCookie: false,
  },
};
```

### Relevant Code Snippets

```javascript
<template>
  <div class="planner-signin-header">
    <div class="language-switcher-container">
      <a @click="toggle"  title="Custom"><span><img width="24" src="/layout/images/7578243-c3952b10.png" alt=""></span>
      </a>
      <Menu ref="menu" id="overlay_menu" :model="items" :popup="true" />
    </div>
  </div>

  <body class="pages-body flex flex-column align-items-center justify-content-center" >
    <div class="main-container">
      <div id="body" class="main-app-container">
        <div id="projectLiteSignIn" class="p01-home">
          <div class="planner-signin-section">
            <div class="planner-signin-main-content">
              <img class="planner-signin-logo" src="/layout/images/logomua.png" alt="">
              <div class="planner-signin-brand">
                SMART
              </div>
              <div class="planner-signin-description">
                {{ $t('main.description') }}
              </div>
              <img class="planner-signin-icons" src="/layout/images/sign_in_icons.png" alt="Значки">
              <div class="planner-signin-button-wrapper">
                <button @click="handleLogin" id="plannerSignInButton" type="button" class="ms-Button ms-Button--primary planner-signin-button">
                  <div id="plannerSignInButtonSpinner" v-if="loading || store.state.user.isMicrosoftAuthenticated">
                    <img class="planner-signin-spinner" src="/layout/images/spinner-white.svg" width="30" height="30" alt="Загрузка">
                  </div>
                  <div id="plannerSignInButtonText" class="ms-Button-label" v-else>
                    {{ $t('main.signIn') }}
                  </div>
                </button>
              </div>

            </div>
            <div class="planner-signin-footer">
              <div style="font-size: 12px" class="planner-signin-microsoft-logo-wrapper">
                {{ $t('main.footer') }}
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </body>
</template>

<script>

import { login} from "@/authService";
import store from "@/store";
import i18n, {supportedLocales} from "@/locales/i18n";

export default {
  computed: {
    store() {
      return store
    },
    items(){
      return [
        ...this.formatLanguageObject(supportedLocales),
      ]
    }
  },
  async mounted() {
    console.log()
    this.loadingMain = !(await this.checkIsMicrosoftAuthenticated());
    store.watch(
      (state) => state.user.authenticate_loading,
      (value) => {
        if (!value) {
          this.loadingMain = false;
        }
      }
    );
  },
  data(){
    return{
      loading: false,
      loadingMain: true,
    }
  },
  methods: {

    toggle(event) {
      this.$refs.menu.toggle(event);
    },
    changeLocale(val) {
      i18n.setLocale(val);
      this.$router.push({...this.$route, params: {...this.$route.params, locale: val}});
    },
    formatLanguageObject(obj) {
      let result = [];
      for (let key in obj) {
        let lang = obj[key];
        result.push({
          label: lang.name,
          command: () => {
            this.changeLocale(key)
          }
        });
      }
      return result;
    },
    async checkIsMicrosoftAuthenticated() {
      return new Promise((resolve) => {
        store.watch(
          (state) => state.user.isMicrosoftAuthenticated,
          (value) => {
            resolve(value);
          }
        );
      });
    },
    async handleLogin() {
      try {
        if (!store.state.user.isMicrosoftAuthenticated){
          this.loading = true;
          await login();
          this.loading = false;
        }
        // Handle login success
      } catch (error) {
        // Handle login failure
      }
    },
  },
};
</script>
```

### Reproduction Steps

1. Sign in to the Microsoft service (e.g., Planner or Outlook) using MSAL.
2. Perform necessary actions within the Microsoft service.
3. Log out from the Microsoft service.
4. Use the MSAL library for JavaScript to log out the user.
5. Observe that the user is not redirected back to my website.

### Expected Behavior

Upon logging out from the MSAL library, the user should be redirected back to my website.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox

### Source

External (Customer)

**Comment by hectormmg** [comment]
Hi @Awolwe , thanks for raising the issue. I don't see any logout logic in your code, could you share your MSAL logout API usage. Please make sure you're setting a `postLogoutRedirectUri` in your auth config like shown in [our docs](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md)

**Comment by Awolwe** [comment]
I apologize for the previous omission. I'd like to add that I've implemented a custom logout logic with redirection to a logout page. Here's the code snippet for the implementation:


```
export async function logout() {
  try {
    await store.dispatch("logout").then(() =>{
      removeCookie("auth_token");
      // Redirect the user to the logout URL
      window.location.href = `https://login.microsoftonline.com/common/oauth2/logout?post_logout_redirect_uri=${encodeURIComponent(process.env.VUE_APP_BASE_URL + "/login")}`;
    });
  } catch (error) {
    console.error("Logout failed:", error);
  }
}
```


This implementation performs as expected for standard logout scenarios, but I've observed some inconsistent behavior when logout is initiated in a manner similar to the issue described.

Here are the corresponding screenshots for the observed behavior:

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/48988355/54571fd7-e8f6-42f4-aeb6-ef5d6ef47144)

This is the default redirection behavior.

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/48988355/925a13d0-2e88-4bc0-8e60-0de50aef250f)

The motivation for using my own logout logic stems from the fact that the core logout displays the Microsoft logo, while using the [common logout](https://login.microsoftonline.com/common/oauth2/logout) endpoint ensures a logo-free logout.

**Comment by jo-arroyo** [comment]
@Awolwe To clarify, you are not using MSAL's logout APIs for logout, and the issue is happening with your custom logout redirect? Have you registered your logout uri in your app registration?

Please take a look at our [docs on logout](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md) for more information.
