### ISSUE TITLE
@azure/msal-react exports not defined correctly

### ISSUE THREAD

**Issue by nvonbenken** [AzureAD/microsoft-authentication-library-for-js#6151]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.0.0-beta.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.0.0-beta.0

### Public or Confidential Client?

Public

### Description

Using Vite it seems that exports are not specified correctly. I'm getting this error:
`Failed to resolve entry for package "@azure/msal-react". The package may have incorrect main/module/exports specified in its package.json.`

### Error Message

Failed to resolve entry for package "@azure/msal-react". The package may have incorrect main/module/exports specified in its package.json.

### MSAL Configuration

```javascript
import type { Configuration } from '@azure/msal-browser';

const clientId = import.meta.env.CLIENT_ID ?? '';
const tenant = import.meta.env.TENANT ?? '';
const policy = import.meta.env.POLICY ?? '';
const postLogoutRedirectUri = import.meta.env.POST_LOGOUT_REDIRECT_URI
  ? `${import.meta.env.POST_LOGOUT_REDIRECT_URI}/Account/Logout`
  : '/';

export const msalConfig: Configuration = {
  auth: {
    clientId: clientId,
    authority: `https://${tenant}.b2clogin.com/${tenant}.onmicrosoft.com/${policy}`,
    knownAuthorities: [`${tenant}.b2clogin.com`],
    redirectUri: `${window.location.origin}`,
    postLogoutRedirectUri: postLogoutRedirectUri,
  },
  cache: {
    cacheLocation: 'sessionStorage', // This configures where your cache will be stored
    storeAuthStateInCookie: false,
  },
};

export const loginRequest = {
  scopes: [],
};

export const graphConfig = {
  graphMeEndpoint: 'https://graph.microsoft.com/v1.0/me',
};
```

### Relevant Code Snippets

```javascript
import type { PublicClientApplication } from '@azure/msal-browser';
import {
  InteractionRequiredAuthError,
  InteractionType,
} from '@azure/msal-browser';
import {
  AuthenticatedTemplate,
  MsalProvider,
  useMsal,
  useMsalAuthentication,
} from '@azure/msal-react';
```

### Reproduction Steps

1. Update to beta packages
2. Attempt to build

### Expected Behavior

Exports defined correctly to allow a build to work as expected.

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge

### Regression

@azure/msal-browser 1.5.8

### Source

External (Customer)

**Comment by hectormmg** [comment]
Hi @nvonbenken, thanks for raising the issue, looking into it.

**Comment by nvonbenken** [comment]
Great, thank you!

**Comment by jahead** [comment]
@hectormmg this is a simple bug. And it's effecting msal-node too
for `msal-node` the module reference for the index is wrong.
see screenshot
<img width="309" alt="image" src="https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/5070464/72c0ae88-3582-4d1d-a700-ca9a96ec21ea">

And this is a screenshot of the dist for the esm file
<img width="281" alt="image" src="https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/5070464/2c7f25e9-bf26-4509-bad1-f95da22f5481">

And on `msal-react` the esm file doesn't even exist. 
here is the package.json
<img width="350" alt="image" src="https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/5070464/38b04f5b-8906-46d0-a36e-ea5d5455f8a7">

and this is the dist folder.
<img width="502" alt="image" src="https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/5070464/15890987-c1c3-4658-8585-e8fb9814d005">


I know its a beta but both node and react would be broken for vite. Can we get a fix and a beta release to quickly fix the broken packages?

**Comment by tnorling** [comment]
The linked PR will address this, thanks for reporting!

**Comment by jahead** [comment]
@tnorling 

My pr only addresses the issue for @msal-node 


In the case of msal-react we need to either configure the rollup.config.ts to produce an index.esm.js file or remove the `module` property in the package.json, which should make vite or other bundlers fall back to main. 

I don't have a react playground ATM to quickly test this so I haven't created a pr. I can do this out of work hours if ms doesn't get to it before me
