### ISSUE TITLE
Post-login redirect happens within popup intermittently

### ISSUE THREAD

**Issue by amrutha95** [AzureAD/microsoft-authentication-library-for-js#6161]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.37.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

One out of approximately 4 times that I try to log in, the redirect post login happens within the popup window which doesn't close.  

### MSAL Configuration

```javascript
const msalConfig: Configuration = {
      auth: {
        clientId: env.CLIENT_ID,
        authority: 'https://login.microsoftonline.com/consumers/',       
      },
      cache: {
        cacheLocation: 'sessionStorage',
        storeAuthStateInCookie: false,
      },
    };
```

### Relevant Code Snippets

```javascript
Just a simple log in flow.
```

### Reproduction Steps

1. Go to https://polite-glacier-097fe8710-4148.centralus.2.azurestaticapps.net/giveaway?site=https://friendship-calendar-c0efc.web.app
2. Click on "Sign in with a Microsoft account" and complete the sign in process. Try multiple times until you get the error.

Screenshot here: 
<img width="988" alt="image" src="https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/22471775/c2d3dec6-70b6-434f-996c-61b1cdaef671">

### Expected Behavior

Once login is complete the popup should close on its own.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Edge

### Source

Internal (Microsoft)

**Comment by jo-arroyo** [comment]
@amrutha95 Unfortunately, there are known issues with the hash not being polled correctly intermittently. Please ensure you [set the redirectUri](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md#redirecturi-for-popup-and-silent-flows) correctly, and follow the instructions [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/errors.md#monitor_window_timeout) to try to mitigate this behavior.
