### ISSUE TITLE
Popup shows empty window after authentication and does not close with @azure/msal-browser

### ISSUE THREAD

**Issue by jaswindersodhi1997** [AzureAD/microsoft-authentication-library-for-js#6166]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.33.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

'None'

### Public or Confidential Client?

Confidential

### Description

Hi,

I am trying to integrate the Azure Authentication into my vue.js application setup using vue-router with hash mode. But after integrating it works successfully but when I use in production app it doesn't work and it just shows this empty window with success response coming from azure?
<img width="586" alt="image" src="https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/55807035/3e1ddbe5-a392-4bff-b94e-fb085314d710">

### MSAL Configuration

```javascript
const msalConfig = {
  auth: {
    clientId: <<CLIENT_ID>>,
    authority: 'https://login.microsoftonline.com/<<TENANT_ID>>',
    redirectUri: 'https://<<DOMAIN_NAME>>/#/base/tables'
  },
  cache: {
    cacheLocation: 'sessionStorage',
    storeAuthStateInCookie: false
  },
  system: {
    loggerOptions: {
      loggerCallback: (level, message, containsPii) => {
        if (containsPii) {
          return
        }
        switch (level) {
          case msal.LogLevel.Error:
            console.error(message)
            return
          case msal.LogLevel.Info:
            console.info(message)
            return
          case msal.LogLevel.Verbose:
            console.debug(message)
            return
          case msal.LogLevel.Warning:
            console.warn(message)
        }
      },
      logLevel: msal.LogLevel.Verbose
    }
  }
}

export const msalInstance = new msal.PublicClientApplication(msalConfig)
```

### Relevant Code Snippets

```javascript
I am using it in one of my vue files(Login.vue) rendered at '/pages/Login' to invoke the authentication as follows:-

The page has a login button and on click of that button I invoke the signIn function for which the function definition as follows:-

async signIn () {
       try {
         console.log(loginRequest)
         let response = await msalInstance.loginPopup(loginRequest)
         console.log('Response is--> ', response)

         const accountId = response.account.homeAccountId
         const account = msalInstance.getAccountByHomeId(accountId)
         console.log('User account information is --> ', account)
         if (response !== null) {
           localStorage.username = response.account.username
         }
       } catch (error) {
         console.error(error)
       }
    }

So please could someone help to me to resolve this issue?
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@jaswindersodhi1997 Have you taken a look at our [Vue sample app](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-browser-samples/vue3-sample-app) to see how MSAL can be used with Vue?

Can you also provide verbose logs of this behavior? 

Please also upgrade to the latest version of MSAL Browser, thank you.
