### ISSUE TITLE
MSAL node cannot be used in node 20

### ISSUE THREAD

**Issue by SalvatorePreviti** [AzureAD/microsoft-authentication-library-for-js#6167]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.17.3

### Wrapper Library

Not Applicable

### Wrapper Library Version

N/A

### Public or Confidential Client?

Public

### Description

The package cannot be installed when using node 20, npm i fails because in package.json the list of supported engines does not include node 20.

 "engines": {  "node": "10 || 12 || 14 || 16 || 18" }

Please, add node 20 as well to the list of supported engines.

### Error Message

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@azure/msal-node@1.17.3',
npm WARN EBADENGINE   required: { node: '10 || 12 || 14 || 16 || 18' },
npm WARN EBADENGINE   current: { node: 'v20.3.1', npm: '9.6.7' }
npm WARN EBADENGINE }

### Msal Logs

N/A

### MSAL Configuration

```javascript
N/A
```

### Relevant Code Snippets

```javascript
N/A
```

### Reproduction Steps

N/A

### Expected Behavior

N/A

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@SalvatorePreviti Support for Node 20 will be added to msal-node v2, which is currently in pre-release. Please give `@azure/msal-node@2.0.0-beta.0` and let us know if you have any issues.

**Comment by jo-arroyo** [comment]
Closing as question answered. Please open a new issue with the MSAL Node version used if there are further questions.

**Comment by asdf23** [comment]
me too

**Comment by maheshgondugade** [comment]
Facing same issue with Node 20
