### ISSUE TITLE
AADSTS50158: External security challenge not satisfied.

### ISSUE THREAD

**Issue by peshos** [AzureAD/microsoft-authentication-library-for-js#617]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [x] Edge version 44.17763.1.0
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 0.2.4

## Current behavior

Authenticating to a site that uses Ping Identity [https://www.pingidentity.com/en.html](https://www.pingidentity.com) as a two-factor authentication results in the above error in Edge. Works fine in latest Chrome.

I can see the access token in the local storage. 

## Expected behavior

Log in successfully. 

## Minimal reproduction of the problem with instructions

- Register SPA web application in Azure AD.
- Configure Ping Identity for this Azure AD.
- Authenticate using loginRedirect method.

</code></pre>

**Comment by sameerag** [comment]
@peshos  We are planning to looking at this and update after msal 1.0.0 release.

**Comment by aashiman** [comment]
@peshos  can you please share a requestId/correlationId for a broken request?  We will look into our service logs to see what might be causing this.

Better if you are able to track a success vs fail flow via fiddler, that would help as well

**Comment by peshos** [comment]
@aashiman I am sorry about the delay. Here is one from today:

AADSTS50158: External security challenge not satisfied.Trace ID: 260083b7-3f60-45a2-8a81-1e4f30220400Correlation ID: 410cb97b-8551-4e8f-bbaf-31078037705aTimestamp: 2019-05-08 07:54:51Z

I can provide a fiddler flow but I am afraid I cannot do this publicly. Is there another way?

**Comment by sameerag** [comment]
@peshos Sure. Can you please send me an email @ sameera.gajjarapu@microsoft.com and we can take the conversation private?

**Comment by PraveenVerma17** [comment]
InteractionRequiredAuthError: AADSTS50158: External security challenge not satisfied.
Trace ID: f92ad13c-2b85-4f9e-a3cb-d1210e880400
Correlation ID: d47ccc24-9598-4dd6-9a92-0616240d6b16
Timestamp: 2019-07-25 16:42:11Z
    at InteractionRequiredAuthError.AuthError [as constructor] (https://localhost:44318/static/js/0.chunk.js:101884:24)
    at InteractionRequiredAuthError.ServerError [as constructor] (https://localhost:44318/static/js/0.chunk.js:102411:24)
    at new InteractionRequiredAuthError (https://localhost:44318/static/js/0.chunk.js:102344:24)
    at UserAgentApplication.saveTokenFromHash (https://localhost:44318/static/js/0.chunk.js:100261:17)
    at UserAgentApplication.processCallBack (https://localhost:44318/static/js/0.chunk.js:99745:23)
    at UserAgentApplication.handleAuthenticationResponse (https://localhost:44318/static/js/0.chunk.js:99852:10)
    at new UserAgentApplication (https://localhost:44318/static/js/0.chunk.js:98842:14)
    at MsalProvider.initProvider (https://localhost:44318/static/js/0.chunk.js:14572:36)
    at new MsalProvider (https://localhost:44318/static/js/0.chunk.js:14537:10)
    at https://localhost:44318/static/js/main.chunk.js:55:24
    at run (https://localhost:44318/static/js/0.chunk.js:111344:22)
    at https://localhost:44318/static/js/0.chunk.js:111364:30
MsalProvider.js:189 authError: ClientAuthError: AcquireToken_In_Progress: Error during login call - login is already in progress. accountState

**Comment by spissay** [comment]
Do we have any update on this. We are seeing similar error after enabling MFA. This is happening on chrome and firefox as well.

**Comment by laundreej** [comment]
We are also seeing this same issue.  Any ETA on a fix or workaround?
Thanks

**Comment by PraveenVerma17** [comment]
for me conditional access was causing the issue. You might need to look into that.

**Comment by sameerag** [comment]
@PraveenVerma17 So what is happening here? If you enable MFA, are you seeing this error even after satisfying the needed conditional access condition only in Edge and not in Chrome?
Can you please send me the repro steps?

This error: `InteractionRequiredAuthError: AADSTS50158: External security challenge not satisfied.` is sent by the server and we (`msal js`) relay it to the user. I can check with the service to understand why we are seeing this, if I have a consistent setup to repro this.

@peshos My mistake, we missed tracking this issue. Is it still a problem for you?

**Comment by peshos** [comment]
@sameerag Yes, the issue is still present. Most of the users are on Chrome though and is not a blocker for us.

**Comment by sameerag** [comment]
@peshos Thanks for the response. 

@PraveenVerma17 As I have mentioned before we believe this is a specific MFA/CA issue that is happening with your app configuration. Closing this issue as there is no `msal js` solution to address this.
