### ISSUE TITLE
Can MSAL.js v2.0 work with Angular 8?

### ISSUE THREAD

**Issue by lzhang-advent** [AzureAD/microsoft-authentication-library-for-js#6175]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.14.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0

### Public or Confidential Client?

Public

### Description

Our app is based on Angular 8, can I use msal v2.0 based on Angular 8? I prefer to use masl v2.0 since it brings support for the authorization code flow with PKCE
The sample code for Angular 8 is based on msal v1.0. 

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by jo-arroyo** [comment]
@lzhang-advent MSAL Angular v2 officially supports Angular 9-14, and has not been tested with Angular 8. You may try it if you wish, but it is not guaranteed to work, and we will not be able to make library fixes to accommodate Angular 8. We strongly encourage you to upgrade to modern versions of Angular, as we are currently working on releasing MSAL Angular v3, which will only support Angular 15 onwards.

**Comment by lzhang-advent** [comment]
Got it. Thank you.
