### ISSUE TITLE
Managing token lifetime with msal, angular and office add-in.

### ISSUE THREAD

**Issue by JxEngel** [AzureAD/microsoft-authentication-library-for-js#6176]
### Core Library

MSAL.js (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Public or Confidential Client?

Public

### Documentation Location

docs.microsoft.com

### Description

I have seen documentation to authenticate and receive a single access token using the office dialog api. But I do not see how I can manage the token's lifetime without waiting for a 401 and then opening another dialog to get another access token. Also, I do not know how I can integrate a protected resource map to call multiple 3rd party API's. Are there any examples or documentation to guide me in this work?

**Comment by jo-arroyo** [comment]
@JxEngel While we do not have specific documentation for office add-ins, please take a look at our documentation and samples for [MSAL Angular](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/README.md), using the [MSAL Interceptor and the protectedResourceMap](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/msal-interceptor.md), and [token lifetimes](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/token-lifetimes.md). You may also find the FAQs for [MSAL Browser](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md) and [MSAL Angular](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/FAQ.md) helpful.
