### ISSUE TITLE
Add a pop-up public client that integrates msal-browser with the office-addin dialog api

### ISSUE THREAD

**Issue by JxEngel** [AzureAD/microsoft-authentication-library-for-js#6177]
### Core Library

MSAL.js (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Public or Confidential Client?

Public

### Description

Attempting to write an authentication scenario for an enterprise application that uses multiple 3rd party Azure AD protected resources and the graph which runs within an office (word) add-in. Many hurdles to overcome with this, from the documentation I see the current status in examples show getting a single access token with no management. It would be great to add an office dialog driven popup to the popupClient.ts file, or alongside, with a new interaction type for office add-ins. I am of course not sure what other hurdles would exist, but for developers using angular msal-angular is amazing, but adding in the office add-in it doesn't appear to be useable. 

### Source

Internal (Microsoft)

**Comment by jo-arroyo** [comment]
@JxEngel Could you clarify what you mean by "an office dialog driven popup" and the use case?

**Comment by JxEngel** [comment]
Hi, thank you for your response! When using an office add-in the msal packages do not work to authenticate from the task pane itself. When you try to do so by either redirect or popup from my experience it opens a browser window outside of the office application and crashes. To open a popup, in this case to navigate to the authorize endpoint and handle the auth redirects, you have to use the office context and open a popup. here's the call: 
    await Office.context.ui.displayDialogAsync()
The react add-in sample (and most likely the .net but I haven't reviewed) show opening the popup through the call shown above, creating a public client to authenticate and then using the built-in messaging service to send back an access token to make an api call. The add-in I am developing is a large enterprise application that makes many api calls to many different api's. We also have a SPA that does this and MSAL does work for our scenario. Where I am having trouble connecting the dots is if I am setting up my authentication in that popup from the office context it is a completely different browser session and the resources used by the msal to provide a robust auth setup with the protected resource map and management of the token lifetimes does not appear to be available. My goal would be for a user to login once, and then be able to reach all resources protected by azure ad. 
I am not sure if I am missing something, or if in office add-ins this truly is not available. I did however notice in the msal-common code (I believe, or maybe it was browser) there is a class that uses the built-in Window popup for that type of auth interaction. It made me wonder, could they write another popup client that used the call to Office.context and listened for a message reply to get the auth code (or other items from the authorize endpoint) and then continue the auth process inside the taskpane so all the other functionality works? 
I have also put in a request for more documentation to research and make sure its not just me who is missing something obvious to getting the correct setup for an office add-in. And I also don't know what other challenges this type of request would bring. But hey, let's aim for the fences! Thanks.

**Comment by tnorling** [comment]
Could you use the `onRedirectNavigate` callback on the `loginRedirect` request to open your dialog?

```js
msalInstance.loginRedirect({
  onRedirectNavigate: (url) => {
    Office.context.ui.displayDialogAsync(url);
    return false; // Stops the current context from redirecting
  }
});
```

Then on your redirectUri page you would need to capture the hash in the url, and message it back to the calling page. The calling page would then need to invoke `handleRedirectPromise(hash)` to get the tokens.

It's not a scenario we have a sample for but it should work in theory. Can you try it?

**Comment by JxEngel** [comment]
Thanks, I will try this and update!

**Comment by JxEngel** [comment]
Hello, I was able to successfully log in through the redirect as you described above! Thank you so much. The task pane local storage has all data stored and I am able to call the graph and my two azure secured 3rd party apis with 1 user interaction as desired.  But... I have an issue. When a page is refreshed after the successful login an error is thrown on "acquiretokensilent" call originating from the HttpInterceptor, it seems the msal instance is not initializing. The actual error occurs as this.initialize is false in below snippet from StandardController.ts: 
`    preflightBrowserEnvironmentCheck(interactionType, isAppEmbedded = false) {
       ...
        /*
         * Block token acquisition before initialize has been called if native brokering is enabled in top-frame.
         * Skip check if application is embedded.
         */
        if (!isAppEmbedded) {
            BrowserUtils.blockNativeBrokerCalledBeforeInitialized(this.config.system.allowNativeBroker, this.initialized);
        }`
I have tried await msalService.instance.initiualize() in multiple places. I tried using it in the angular components but it seems to not complete before the interceptor code runs. I have put it in the authentication module "factory" method that creates the public client for injection. That throws all kinds of errors... Any ideas on what I may be doing wrong? Worth noting, I can put the login method in the main component I have the <router-outlet> tag and it will log-in every refresh (flashing the office dialog popup on the screen). But that's not really ideal. 

Once I get through this hurdle I also have questions on the proper method to logout. I can clear the cache myself and navigate an office dialog to the logout url. Or is there a way to do this as you have shown me with the login? Thanks for all your time.

**Comment by tnorling** [comment]
@JxEngel Are you bootstrapping the `HandleRedirectComponent` or using the `handleRedirectObservable`? More information on this [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/redirects.md)

Regarding logout, you can use the `logoutRedirect` API the same way you use login (pass the `onRedirectNavigate` callback). The logout API will handle clearing the cache and then invoke the callback to take you to the server logout page

**Comment by JxEngel** [comment]
Ok, now I am thoroughly confused. If I setup everything with the HandleRedirectComponent, and I use LoginRedirect() without the office dialog it redirects in the taskpane and everything seems to work. If I use the office dialog it works just fine as well, but... either the guard or the interceptor is catching the call and redirecting inside the task pane for a second login. I am very surprised as I thought you could not use the redirect behavior in an office add-in. All the documentation and code examples show you can't and to use the office dialog api. So I don't know if I should be happy and "ship it!" with the redirect, or is that only working with my version of Word??? Any insight on this? I really appreciate the time you have taken to answer all my questions!

**Comment by tnorling** [comment]
hmm when it redirects without the office dialog are you entering your credentials/interacting with the page at all? The reason redirects aren't supported is that the AAD login page doesn't allow itself to be embedded on other pages to prevent click-jacking attacks. I suspect this may work if AAD doesn't need to render any prompts but would fail the moment it determines it needs user interaction to proceed.

**Comment by JxEngel** [comment]
I am able to do the complete interaction. Input email, password, select text a 2-factor code and input that code.

**Comment by JxEngel** [comment]
![2-factor](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/19728391/0665be74-aa9c-467e-a976-ca8736b71848)
![email](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/19728391/cb44e256-ea76-4c13-8857-e1de34ba64eb)
![password](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/19728391/2e55f32e-6236-4db8-9679-8d8877746a04)

**Comment by JxEngel** [comment]
![localstorage](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/19728391/d784cc50-9514-45a5-9cdb-bf109ce5ad65)

**Comment by JxEngel** [comment]
I would have no problem with using the office dialog approach and ignoring this, but... If I log out and then refresh a page or navigate to a page with a guard it runs the code to login inside the library. I don't know how to stop it and display in the office dialog like the manual call. So, users can have 2 different login experiences in the same app.

**Comment by JxEngel** [comment]
Currently my code is in a branch that I can't share. If we are getting to the point it would help to look at the scenario, I can get it moved for your access.

**Comment by tnorling** [comment]
You can [configure the request](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/msal-guard.md#configuring-the-msalguard-in-the-appmodulets-and-app-routingmodulets) the Guard and/or [interceptor](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/msal-interceptor.md) will use and pass in the same request object you're using to open the dialog. 

It is a bit curious though that this works for you without the dialog...that's news to me. I will need to consult with our server teams to understand if this is a new feature or a bug...
