### ISSUE TITLE
Authorizing service API client with BearerStrategy

### ISSUE THREAD

**Issue by egm9078** [AzureAD/microsoft-authentication-library-for-js#6178]
### Core Library

Passport Azure AD (passport-azure-ad)

### Core Library Version

"^4.3.3"

### Wrapper Library

Not Applicable

### Wrapper Library Version

none

### Public or Confidential Client?

Public

### Description

Using this BearerStrategy `require('passport-azure-ad').BearerStrategy` config:
```
const options = {
	identityMetadata: `https://${config.metadata.authority}/${config.credentials.tenantID}/${config.metadata.version}/${config.metadata.discovery}`,
	issuer: `https://${config.metadata.authority}/${config.credentials.tenantID}/${config.metadata.version}`,
	clientID: config.credentials.clientID,
	audience: config.credentials.audience,
	validateIssuer: config.settings.validateIssuer,
	passReqToCallback: config.settings.passReqToCallback,
	loggingLevel: config.settings.loggingLevel,
	scope: config.settings.scope
};
```

The API authorizes user tokens. 

After adding an App Role (Allowed member types - Applications) intended for authorized API clients, it's unclear how the config should be updated to authorize these requests.

This is the intended design (currently authorizing users and handling accordingly)
```
const bearerStrategy = new BearerStrategy(options, async function(token, done) {
    
	//- if token has user scope, handle accordingly
	//- if token has app role, handle accordingly
	
});
```

The service client token is generated through the client credentials flow and has the correct API role in the token
```
/*
Generating Token
POST
https://login.microsoftonline.com/[tenant_id]/oauth2/v2.0/token
client_id
grant_type (client credentials)
client_secret
scope api://[client_id]/.default
*/

```

After trying several Bearer Strategy configuration changes, the service client is still unauthorized.

Can you point towards an example that relates to this use case? 

i.e. BearerStrategy is configured to authorize both clients via `@azure/msal-browser` with `acquireTokenSilent` (authenticated user) and also a service account that is authorized to use an App Role

### MSAL Configuration

```javascript
{
    "credentials": {
        "tenantID": "7d76d361-8277-4708-a477-64e8366cd1bc",
        "clientID": process.env.API_CLIENTID,
        "audience": process.env.API_CLIENTID
    },
    "metadata": {
        "authority": "login.microsoftonline.com",
        "discovery": ".well-known/openid-configuration",
        "version": "v2.0"
    },
    "settings": {
        "validateIssuer": true,
        "passReqToCallback": false,
        "loggingLevel": "info",
        "scope": process.env.API_SCOPE
    }
}
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@egm9078 Unfortunately, passport-azure-ad has been deprecated and is currently only receiving support for critical security fixes. Alternate solutions for token validation are currently under development, tagging @jmprieur and @jennyf19 for status.

@EmLauber for visibility.

**Comment by dylel** [comment]
Can you post back here when there’s an update @jo-arroyo , I’m currently trying to decode a token in a nextjs api route but haven’t found any documents pointing to how to do so correctly without passportjs

**Comment by egm9078** [comment]
Could you provide feedback for this example? 

```
const jwt = require('jsonwebtoken');
const jwksClient = require("jwks-rsa");

app.use('/protected-endpoints*', async (req, res) => {
	
	const authHeader = req.headers.authorization;
	if (!authHeader) return res.sendStatus(403);
	const token = authHeader.split(' ')[1];
	
	try {

		const getSigningKey = async (header) => {
			return new Promise((resolve, reject) => {
				const client = jwksClient({
					jwksUri: `https://login.microsoftonline.com/${process.env.API_TENANTID}/discovery/v2.0/keys`,
				});
				
				client.getSigningKey(header.kid, (err, key) => {
					if (err) {
						reject(err);
					} else {
						const signingKey = key.publicKey || key.rsaPublicKey;
						resolve(signingKey);
					}
				});
			});
		};
		
		const decodedToken = jwt.decode(token, { complete: true });
		const header = decodedToken.header;
		const signingKey = await getSigningKey(header);
		const decoded = jwt.verify(token, signingKey);
		console.log(decoded);
	
	} catch (err) {
		logger.error({error: err});
		res.sendStatus(403);
	}
	
});
```

**Comment by tnorling** [comment]
As mentioned, passport-azure-ad is deprecated and we do not recommend using it for new applications nor do we provide support for it anymore beyond security updates. Closing but please track #6113 for alternate token validation solutions
