### ISSUE TITLE
teams sdk getAuthToken to msal instance

### ISSUE THREAD

**Issue by Venipa** [AzureAD/microsoft-authentication-library-for-js#6188]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.35.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.5.5

### Public or Confidential Client?

Public, Confidential

### Description

I'm currently trying to authorize the public client to accept my token that was exchanged with a confidential client.
Current methods are not documented on how to pass the token i received from the confidential client to the msal-angular instance.

### Relevant Code Snippets

```javascript
teams sdk: `@microsoft/teams-js`



try {
      const teamsInstance = ...; // instance of sdk library, already initialized
      const teamsAuth = teamsInstance.authentication,
        teamsApp = teamsInstance.app;
      if (teamsAuth) {
        const userAuth = await teamsAuth
          .getAuthToken()
          .then((x) =>
            fetch(environment.serverUrl + '/teams_sso_client_auth_exchange', {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                Origin: window.location.origin,
              },
              body: JSON.stringify({
                token: x,
              }),
            })
              .then((d) => d.json())
              .then((d) => d && d.ssoToken)
          )
          .catch((err) => {
            log.error('sso', err);
            return null;
          });
        if (userAuth) { // trying to use the exchanged token somehow
          const ssoResult: AuthenticationResult | null = await msal
            .ssoSilent({
              account: (userAuth.account || msal.instance.getActiveAccount()) as any,
              scopes: userAuth.scopes || [Scope.Me],
            })
            .toPromise()
            .catch((err) => {
              log.error(err);
              teamsApp.notifyFailure({
                reason: FailedReason.Other,
                message: 'Something went wrong while authorizing token.',
              });
              return null;
            });
          if (ssoResult) return ssoResult;
        }
      }
    } catch (ex) {
      log.debug(ex);
    }
```
```


### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by tnorling** [comment]
> how to pass the token i received from the confidential client to the msal-angular instance.

This is not a supported use case. Tokens should only be used by the application which requested them and validated by the API that it was requested for.

Can you please tell me a little more about what you're trying to do and what's not working?

**Comment by Venipa** [comment]
> > how to pass the token i received from the confidential client to the msal-angular instance.
> 
> This is not a supported use case. Tokens should only be used by the application which requested them and validated by the API that it was requested for.
> 
> Can you please tell me a little more about what you're trying to do and what's not working?

we are trying to implement teams sso but are unable to pass the access token to the msal library even though msal library has a ssoSilent method it is not the same as teams sso.

**Comment by tnorling** [comment]
You do not need to pass an access token to msal, each msal instance needs to acquire its own tokens. To achieve sso you should call ssoSilent and pass in a loginHint which is either the user's email or the login_hint claim from the user's idToken (preferred). More information [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/login-user.md#silent-login-with-ssosilent)
