### ISSUE TITLE
Cookie length should be less than or equal to 4096 characters

### ISSUE THREAD

**Issue by ormico** [AzureAD/microsoft-authentication-library-for-js#620]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [X] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: msal v0.2.1
with msal-angular.js

## Current behavior
Adding azure ad login to a legacy angularjs app that already support password logins.
When logging in I'm seeing an error in the console that the cookie is not being set b/c it is too large.

## Expected behavior
Login succeeds and cookie is set.

<code>
Set-Cookie header is ignored in response from url: https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=id_token&scope=openid%20profile&client_id=<clientID>&redirect_uri=https%3A%2F%2Flocalhost%3A44302%2Fm%2Fdefault.aspx&state=<state>&nonce=<nonce>&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=0.2.1&client-request-id=<client request id>&prompt=none&login_hint=<hint>&domain_req=<domain_req>&login_req=<login request>&domain_hint=organizations. Cookie length should be less than or equal to 4096 characters.
(anonymous) @ msal-angular.min.js:18
setTimeout (async)
e.loadFrame @ msal-angular.min.js:18
e.loadIframeTimeout @ msal-angular.min.js:18
e.renewIdToken @ msal-angular.min.js:18
(anonymous) @ msal-angular.min.js:18
</code>

## Minimal reproduction of the problem with instructions

</code></pre>

**Comment by navyasric** [comment]
This issue seems related to #534. Please track that issue. Closing this
