### ISSUE TITLE
Add standalone support (without modules) for angular

### ISSUE THREAD

**Issue by swami-sanapathi** [AzureAD/microsoft-authentication-library-for-js#6212]
### Core Library

MSAL.js v2 (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Public or Confidential Client?

Public

### Description

Since angular is moving towards functional way and without modules. 

### Source

External (Customer)

**Comment by tnorling** [comment]
Closing as duplicate of #6080 - please track that issue for updates
