### ISSUE TITLE
How to make msal-browser PoP sample work?

### ISSUE THREAD

**Issue by srdan-bozovic-msft** [AzureAD/microsoft-authentication-library-for-js#6223]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.38.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

I manage to acquire pop token but using pop token fails with CORS error.

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/5732116/595448ee-8314-4153-8d6d-d26f80adb62d)

Even if I get past it with CORS plugin, I get 401 Unauthorised.

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/5732116/584f386d-79af-49bb-804e-b208d2490a90)

Could you help resolving this?

### MSAL Configuration

```javascript
// Config object to be passed to Msal on creation
const msalConfig = {
    auth: {
        clientId: "b5c2e510-4a17-4feb-b219-e55aa5b74144",
        authority: "https://login.microsoftonline.com/common"
    },
    cache: {
        cacheLocation: "sessionStorage", // This configures where your cache will be stored
        storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
    },
    system: {
        allowNativeBroker: false, // Disables WAM Broker
        loggerOptions: {
            loggerCallback: (level, message, containsPii) => {
                if (containsPii) {
                    return;
                }
                switch (level) {
                    case msal.LogLevel.Error:
                        console.error(message);
                        return;
                    case msal.LogLevel.Info:
                        console.info(message);
                        return;
                    case msal.LogLevel.Verbose:
                        console.debug(message);
                        return;
                    case msal.LogLevel.Warning:
                        console.warn(message);
                        return;
                    case msal.LogLevel.Trace:
                        console.trace(message);
                        return;
                }
            }
        }
    }
};

// Add here the endpoints for MS Graph API services you would like to use.
const graphConfig = {
    graphMeEndpoint: "https://graph.microsoft.com/v1.0/me",
};

const popConfig = {
    endpoint: "https://signedhttprequest.azurewebsites.net/api/validateSHR"
};

// Add here scopes for id token to be used at MS Identity Platform endpoints.
const loginRequest = {
    scopes: ["User.Read"]
};

const silentRequest = {
    scopes: ["openid", "profile", "User.Read"],
};

const popTokenRequest = {
    scopes: ["openid", "profile", "User.Read"],
    authenticationScheme: msal.AuthenticationScheme.POP,
    resourceRequestMethod: "POST",
    resourceRequestUri: popConfig.endpoint
}

const bearerTokenRequest = {
    scopes: ["openid", "profile", "User.Read"]
}
```

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by lalimasharda** [comment]
Hey @srdan-bozovic-msft ! Can I get some more info on the way you are using the PoP access token?  According to our [docs](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/access-token-proof-of-possession.md#bound-access-token), this is what we expect from the client:

// Using the POP scheme (default), acquireTokenRedirect returns an AuthenticationResult object containing the Signed HTTP Request (PoP Token)
const { accessToken } = await myMSALObj.acquireTokenRedirect(popTokenRequest);

// The SHR is appended to the Authorization header
const headers = new Headers();
const authHeader = `PoP ${accessToken}`; // The PoP label is used in this header
headers.append("Authorization", authHeader);

**Comment by lalimasharda** [comment]
Hey @srdan-bozovic-msft , after consulting with a teammate it seems that the sample doesn't work for token validation. The endpoint we use in the sample is now blocked by CORS. The sample is more importantly an example of token acquisition, but we currently don't offer a validation solution. I will bring this up with my team but I do not know if this will be prioritized at the moment.
