### ISSUE TITLE
Support of new Node LTS Version 20

### ISSUE THREAD

**Issue by thomas-be** [AzureAD/microsoft-authentication-library-for-js#6225]
### Core Library

MSAL Node (@azure/msal-node)

### Wrapper Library

Not Applicable

### Public or Confidential Client?

Public

### Description

Hi,
is there something missing to support the new node version 20?
We would like to use the library together with it.

Thank in advance!

### Source

External (Customer)

<img width="725" alt="screenshot" src="https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/7757106/03c8905a-806c-485a-a770-0f7726b66d59">

**Comment by tnorling** [comment]
Node 20 is supported in msal-node version 3.0.0-beta.1
