### ISSUE TITLE
The account info will be overwritten by another SPA deployed under the same domain

### ISSUE THREAD

**Issue by khuangzzz** [AzureAD/microsoft-authentication-library-for-js#6228]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.33.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

Hello MSAL team, 

I have two applications deployed under the same domain:
- app1: https://some-domain.com/main has the `client-id-1`
- app2: https://some-domain.com/app2 has the `client-id-2`

When I sign in to the `app1`, the MSAL library stores account info in the browser's local storage. After that, I go to the `app2`. During the `app2` bootstrap, I manually filter out the `app1`'s account info by the following code:
```typescript
    // calls MSAL public application instance to get all accounts
    const accounts = this.application.getAllAccounts(); 
    // get rid of accounts that have the app1's client id
    const cachedAccounts = accounts.filter(
      (account) => (account.idTokenClaims as IdTokenClaims)?.aud === this.clientId
    );
    // If no app2's account info being found, it opens a popup to sign in
    if (cachedAccounts.length < 1) {
      const loginPopupRequest: PopupRequest = {
        scopes,
      };

      await this.application.loginPopup(loginPopupRequest);
    }
```
The problem is after I sign in with the same user in `app2`, the account info in the local storage will be overwritten by the `app2`'s account info. It seems the MSAL library cannot properly process the same user's account info for different apps under the same domain.
 

### MSAL Configuration

```javascript
{
      auth: {
        authority: 'https://login.microsoftonline.com/organizations',
        clientId: 'client-id',
        navigateToLoginRequestUrl: true,
        postLogoutRedirectUri: 'post-logout-url',
        redirectUri: 'redirect-url',
      },
      cache: {
        cacheLocation: 'localStorage',
        storeAuthStateInCookie: false,
      },
      system: {
        loggerOptions,
        pollIntervalMilliseconds: 20,
      },
    }
```

### Relevant Code Snippets

```javascript
N/A
```

### Reproduction Steps

1. Create two apps and deploy them under the same domain
2. Sign in to the first app
3. Go to the second app
4. Sign in to the second app with the same user
5. The first app user's account info in the local storage has been overwritten by the second app

### Expected Behavior

Account info for different apps should be separated.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari

### Source

Internal (Microsoft)

**Comment by lalimasharda** [comment]
Hey @khuangzzz ! Thanks for opening this issue. We are aware of this bug and are tracking it internally.

**Comment by peterzenz** [comment]
Our next scheduled release is August 7th, first Monday of each month.  We'll try to get a fix in for that release.  Thanks!

**Comment by khuangzzz** [comment]
Hey @peterzenz, do we have any updates on this bug?
