### ISSUE TITLE
AADSTS50058 after Azure AD invite

### ISSUE THREAD

**Issue by mlankamp** [AzureAD/microsoft-authentication-library-for-js#623]
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report  
- [ ] Performance issue
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Browser:
- [x] Chrome version 73.0
- [x] Firefox version XX
- [ ] IE version XX
- [x] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 0.2.4

</code></pre>

## Current behavior

We use our CRM system to invite users to an customer site (through the graph api). The user receives the Azure AD invite and logs in on the Invite Url, and is send back to our custom site. Depending on how the invite was send, the user is able to login.

Example: The user has a username user@domain.com and an email alias firstname.lastname@domain.com. If we send the Azure AD invite to user@domain.com a user is created in our tenant with user@domain.com and the user can login succesfully. If we send an invite to the alias, a user firstname.lastname@domain.com is created in our tenant and after the user goes through the invite process the alternate email address field is updated with user@domain.com.

The initial login is succesfull, but when we call acquireTokenSilent msal.js fails with AADSTS50058: A silent sign-in request was sent but none of the currently signed in user(s) match the requested login hint.

In the token request to Azure AD we can see the login_hint is set to firstname.lastname@domain.com, but the user is signed in with user@domain.com

## Minimal reproduction of the problem with instructions
- 2 Azure AD's are required
- In the AD where the client application is registered, use the graph api to invite a user from the other Azure AD
- send an invite using the upn
- send an invite using an email alias

**Comment by mlankamp** [comment]
Just found the solution :-) When you add the following to your Azure AD application manifest:

<pre><code>
"optionalClaims": {
      "idToken": [ 
            { 
                  "name": "sid", 
                  "essential": true
            }
      ]
}
</code></pre>

the login_hint isn't used but the SID is used. This seems to solve the problem.

**Comment by verbedr** [comment]
Hi we got the same problem. But although the optional claim 'sid' is send with the idToken it keeps on using the unique_name instead of the sid for the login_hint. What version of the msal library did you use. Are you using v2.0 endpoints or v1.0?

**Comment by verbedr** [comment]
So I found the discrepancy between the two situations. I'm using the msal-angular library which is still using the msal@0.2.1 version. While this has been fixed since msal@0.2.3 library (currently at @0.2.4).
