### ISSUE TITLE
Msal redirect causing a reload and then erroring out 

### ISSUE THREAD

**Issue by amrutha95** [AzureAD/microsoft-authentication-library-for-js#6232]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.37.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

I'm calling handleRedirectPromise() only once on my page but it seems like it's reloading the page and then I'm getting the error: 
`ClientAuthError: state_not_found: State not found:  Cached State`

I've read #2796 already and I know that this error means handleRedirectPromise is being called twice. But I've debugged it to a point where I'm confident that the reload happens right after handleRedirectPromise is called after a successful login.

### Error Message

AuthError.ts:49  Uncaught (in promise) ClientAuthError: state_not_found: State not found:  Cached State
    at ClientAuthError2.AuthError2 [as constructor] (AuthError.ts:49:9)
    at new ClientAuthError2 (ClientAuthError.ts:223:15)
    at ClientAuthError2.createStateNotFoundError (ClientAuthError.ts:320:16)
    at RedirectHandler2.<anonymous> (RedirectHandler.ts:100:35)
    at step (_tslib.js:87:23)
    at Object.next (_tslib.js:68:53)
    at _tslib.js:61:71
    at new Promise (<anonymous>)
    at __awaiter (_tslib.js:57:12)
    at RedirectHandler2.handleCodeResponseFromHash (RedirectHandler.ts:85:126)

### MSAL Configuration

```javascript
onst msalConfig: Configuration = {
      auth: {
        clientId: "GUID',
        authority: 'https://login.microsoftonline.com/common/',
        navigateToLoginRequestUrl : false
      },
      cache: {
        cacheLocation: 'sessionStorage',
        storeAuthStateInCookie: true,       
      },
    };
    this._publicClientApplication = new PublicClientApplication(msalConfig);
```

### Relevant Code Snippets

```javascript
Simple login redirect flow from your docs
```

### Reproduction Steps

Simple login flow with provided configuration.

### Expected Behavior

Redirect login should happen without a reload or error and load the logged in info.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

Internal (Microsoft)

**Comment by lalimasharda** [comment]
Hey @amrutha95 ! Is it possible for you to debug and check if your application is clearing out the state somehow from the cache? Can you please share verbose logs for this issue on my email?
