### ISSUE TITLE
authentication_mismatch with latest msal config

### ISSUE THREAD

**Issue by PlayAnyData** [AzureAD/microsoft-authentication-library-for-js#6238]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.38.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.5.9

### Public or Confidential Client?

Public

### Description

After successful login, the following error is shown. Was working in the latest previous version.

### Error Message

```
ERROR
authority_mismatch: Authority mismatch error. Authority provided in login request or PublicClientApplication config does not match the environment of the provided account. Please use a matching account or make an interactive request to login to this authority.

```

### Msal Logs

AuthError@http://localhost:3000/static/js/bundle.js:29850:20
ClientAuthError@http://localhost:3000/static/js/bundle.js:30117:24
ClientConfigurationError@http://localhost:3000/static/js/bundle.js:30546:24
./node_modules/@azure/msal-common/dist/error/ClientConfigurationError.js/ClientConfigurationError.createAuthorityMismatchError@http://localhost:3000/static/js/bundle.js:30693:12
./node_modules/@azure/msal-browser/dist/interaction_client/BaseInteractionClient.js/BaseInteractionClient.prototype.validateRequestAuthority/BaseInteractionClient</<@http://localhost:3000/static/js/bundle.js:19684:94
step@http://localhost:3000/static/js/bundle.js:13179:17
./node_modules/@azure/msal-browser/dist/_virtual/_tslib.js/__generator/verb/<@http://localhost:3000/static/js/bundle.js:13128:14
fulfilled@http://localhost:3000/static/js/bundle.js:13087:24

### MSAL Configuration

```javascript
export const msalConfig = {
  auth: {
    clientId: process.env.REACT_APP_CLIENT_ID,
    authority: "https://login.microsoftonline.com/" + process.env.REACT_APP_TENANT_ID,
    redirectUri: process.env.REACT_APP_REDIRECT_URL,
  },
  cache: {
    cacheLocation: "sessionStorage", 
    storeAuthStateInCookie: false, 
  }
};


export const loginRequest = {
  scopes: [process.env.REACT_APP_CLIENT_ID + "/.default"]
};
```

### Relevant Code Snippets

```javascript
The index.js loading the MSAL:

export const msalInstance = new PublicClientApplication(msalConfig);

const container = document.getElementById('root');
const root = createRoot(container);
root.render(
  <MsalProvider instance={msalInstance}>
    <MsalAuthenticationTemplate interactionType={InteractionType.Redirect} authenticationRequest={loginRequest}>
      <BrowserRouter>
        <App />
      </BrowserRouter>
    </MsalAuthenticationTemplate>
  </MsalProvider>
);
```
```


### Reproduction Steps

1. Visit localhost:3000
2. Login with username + password + 2FA
3. Get the error.

### Expected Behavior

With the previous version, the user was logged in and everything was working fine.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Firefox, Internet Explorer

### Regression

12.0.0

### Source

External (Customer)

Started as a discussion here: https://github.com/AzureAD/microsoft-authentication-library-for-js/discussions/6131

**Comment by lalimasharda** [comment]
Hey @PlayAnyData , are you making a silent request during this process? If you are, can you please check if you are passing the correct account in your silent request? The environment in the account should match with the authority in your request/MSAL config.

**Comment by PlayAnyData** [comment]
Hey @lalimasharda,
yep that is the case. In index, we are having a:
```
export const activeAccount = () => {
  if (!msalInstance.getActiveAccount() && msalInstance.getAllAccounts().length > 0) {
    msalInstance.setActiveAccount(msalInstance.getAllAccounts()[0]);
  }
  return msalInstance.getActiveAccount();
}
```

We additionally have a token fetcher, where we passed this function, which now does not work anymore. So we have replaced it from:
```
export const acquireBackendToken = async () => {

    const request = {
        scopes: [process.env.REACT_APP_SCOPE_BACKEND],
        account: activeAccount,
    };

    const authResult = await msalInstance.acquireTokenSilent(request);
    return authResult.accessToken
};
```
to (calling function directly):
```
export const acquireBackendToken = async () => {

    const request = {
        scopes: [process.env.REACT_APP_SCOPE_BACKEND],
        account: activeAccount(),
    };

    const authResult = await msalInstance.acquireTokenSilent(request);
    return authResult.accessToken
};
```

This does seem to resolve the issue on initial call. I have to check whether are any other issues though.

**Comment by lalimasharda** [comment]
Hey @PlayAnyData, what do you mean by issue being resolved on the initial call? Does it show up again in subsequent token requests? I would suggest you to debug and check the environment value set in the account object you are passing in and compare it with the authority set in the request. It should be the same or an alias.

**Comment by PlayAnyData** [comment]
Thank you @lalimasharda . It looks like it is working now. For a short period of time, it was not working when coming back to the application, i.e. logging in -> leaving page -> coming back. However, I have only seen this once and guess there was another issue. So I will close this issue now.
