### ISSUE TITLE
The MSAL library redirects authenticated user to the login page when changing password

### ISSUE THREAD

**Issue by SamShekhovtsov** [AzureAD/microsoft-authentication-library-for-js#6240]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.33.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.5.3

### Public or Confidential Client?

Confidential

### Description

There is a need to logout user whenever the browser is closed. In order to achieve that I have used the following configuration:

```ts
cache: {
        cacheLocation: BrowserCacheLocation.SessionStorage,
        storeAuthStateInCookie: false
    },
```

in combination with the following option:

```ts
loginRequest = {
    scopes: [],
    prompt: PromptState.SELECT_ACCOUNT
}
```

Now when user changes his password, or trying to impersonate, it redirects the user to the login page, even though the user is logged in. It is a redundant redirect to the login page. It shouldn't happen, there is no need to login the authenticated user.

I'm redirecting the user to the change password custom policy in the following way:

```ts
let changePasswordRequest: RedirectRequest | PopupRequest = {
            authority: b2cPolicies.authorities.customChangePassword.authority,
            scopes: [],
};
this.authService.loginRedirect(changePasswordRequest);

let impersonateUserRequest: RedirectRequest | PopupRequest = {
            authority: b2cPolicies.authorities.impersonateUser.authority,
            scopes: [],
};
this.authService.loginRedirect(impersonateUserRequest);
```

I have used the `this.authService.loginRedirect` function because I don't see any other way to redirect the user to the change password or another custom policy.

### Error Message

there is no error message, there is a redundant login redirect. The user shouldn't be redirected to the login page multiple times if they are already authenticated.

### MSAL Configuration

```javascript
export const msalConfig: Configuration = {
    auth: {
        clientId: '--- app id ---', // This is the ONLY mandatory field that you need to supply.
        authority: b2cPolicies.authorities.customSignUpSignIn.authority, // Defaults to "https://login.microsoftonline.com/common"
        knownAuthorities: [b2cPolicies.authorityDomain], // Mark your B2C tenant's domain as trusted.
        redirectUri: '/auth', // Points to window.location.origin by default. You must register this URI on Azure portal/App Registration.
        postLogoutRedirectUri: '/logout', // Points to window.location.origin by default.,
        navigateToLoginRequestUrl: true
    },
    cache: {
        cacheLocation: BrowserCacheLocation.SessionStorage,
        storeAuthStateInCookie: false
    },
    system: {
        /**
         * Below you can configure MSAL.js logs. For more information, visit:
         * https://docs.microsoft.com/azure/active-directory/develop/msal-logging-js
         */
        loggerOptions: {
            loggerCallback(logLevel: LogLevel, message: string) {
                console.log(message);
            },
            //logLevel: LogLevel.Verbose,
            logLevel: LogLevel.Error,
            piiLoggingEnabled: false
        }
    }
}
```

### Relevant Code Snippets

```javascript
let changePasswordRequest: RedirectRequest | PopupRequest = {
            authority: b2cPolicies.authorities.customChangePassword.authority,
            scopes: [],
};
this.authService.loginRedirect(changePasswordRequest);

let impersonateUserRequest: RedirectRequest | PopupRequest = {
            authority: b2cPolicies.authorities.impersonateUser.authority,
            scopes: [],
};
this.authService.loginRedirect(impersonateUserRequest);
```

### Reproduction Steps

1. login to the application using the custom policies, Azure AD B2C and MSAL library.
2. navigate the user to another custom policy using the `this.authService.loginRedirect` function.

### Expected Behavior

the user should be directly taken to the change password custom policy (or any other custom policy), since he is already logged in

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge

### Source

External (Customer)

**Comment by SamShekhovtsov** [comment]
@konstantin-msft  @sameerag any help on this? could you guys please take a look?

**Comment by sameerag** [comment]
@SamShekhovtsov Can you please provide us more information on how your app is handling the redirects? The sample code does not show it, it helps to know if the `handle redirect component` is present in `app.module.ts`  or elsewhere.

**Comment by SamShekhovtsov** [comment]
> @SamShekhovtsov Can you please provide us more information on how your app is handling the redirects? The sample code does not show it, it helps to know if the `handle redirect component` is present in `app.module.ts` or elsewhere.

here is what I have in the `app.module.ts`

```ts
@NgModule({
  declarations: [
    AppComponent,
    HomeComponent,
  ],
  imports: [
  ],
  bootstrap: [
    AppComponent,
    MsalRedirectComponent
  ],
  providers: [
    { 
      provide: MAT_DATE_LOCALE, 
      useValue: 'en-GB' 
    },
    {
      provide: HTTP_INTERCEPTORS,
      useClass: MsalInterceptor,
      multi: true
    },
    {
      provide: HTTP_INTERCEPTORS,
      useClass: RequestInterceptor,
      multi: true,
    },
    {
      provide: MSAL_INSTANCE,
      useFactory: MSALInstanceFactory
    },
    {
      provide: MSAL_GUARD_CONFIG,
      useFactory: MSALGuardConfigFactory
    },
    {
      provide: INACTIVITY_CONFIG,
      useFactory: InactivityLogoutConfigFactory
    },
    {
      provide: MSAL_INTERCEPTOR_CONFIG,
      useFactory: MSALInterceptorConfigFactory
    },
    DatePipe,
    MsalService,
    MsalGuard,
    MsalBroadcastService
  ]
})
export class AppModule { }
```

as you can see, the `handle redirect component` is present in the `app.module.ts` @konstantin-msft @sameerag @hectormmg

**Comment by SamShekhovtsov** [comment]
@konstantin-msft @sameerag @hectormmg any clue what is going on and why the login dialog appears while it shouldn't?

**Comment by tnorling** [comment]
MSAL does not control the user experience presented after redirecting to the authority provided. Please open a ticket with [the B2C service](https://learn.microsoft.com/en-us/azure/active-directory-b2c/find-help-open-support-ticket) if you're getting an experience you don't expect. If you believe MSAL is redirecting you to the wrong policy altogether please provide a minimal repro so we can help debug.
