### ISSUE TITLE
Handle api/SelfAsserted/confirmed? during authentication flow

### ISSUE THREAD

**Issue by steve2bi** [AzureAD/microsoft-authentication-library-for-js#6243]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.5.9

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

My custom policy will handle TOU checkbox, and the authenticate flow will return api/SelfAsserted/confirmed page at the end of authentication, could not find any service/events handle it

### Relevant Code Snippets

```javascript
tried with msalInstance.addEventCallback and msalBroadcastService.inProgress
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by konstantin-msft** [comment]
Hi @steve2bi. What event type did you use with `msalInstance.addEventCallback`? Did you try `ACQUIRE_TOKEN_SUCCESS`? Please refer [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/events.md#how-to-use-the-event-api) for more info on event types.

**Comment by steve2bi** [comment]
my problem is caused by iframe. Fixed it. Thanks!
