### ISSUE TITLE
"interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API" Error appears when we are trying to login/logout from multiple tabs at the same time.

### ISSUE THREAD

**Issue by saibunneesashaik** [AzureAD/microsoft-authentication-library-for-js#6245]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.32.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.5.0

### Public or Confidential Client?

Public

### Description

login and logout functionality works good when we are using it in single tab.
 I am facing this error when we are trying to login or logout from multiple tabs at the same time.
 Try to open the app in 2 tabs and try login/logout from first tab. while the login/logout is in progress, switch to the second tab and we will get this error. It is inevitable because login or logout will be asking the user with prompts of "select an account", and what if the user wants logout/login from 2 tabs instantaneously.

seems like login or logout in progress in one tab may causes errors in other tab.

### Error Message

×
interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.  For more visit: aka.ms/msaljs/browser-errors.
▶ 18 stack frames were collapsed.
_callee$
/src/services/authService.ts:24
  21 |   const { instance } = useMsal();
  22 |   const redirectStartPage = window.sessionStorage.getItem('local-url') || '/';
  23 | 
> 24 |   return async () => instance.loginRedirect({ ...loginRequest, redirectStartPage });
  25 | };

### MSAL Configuration

```javascript
auth: {
    clientId,
    authority,
    redirectUri,
    postLogoutRedirectUri: window.location.origin + '/login'
  },
  cache: {
    cacheLocation:'localStorage',
    storeAuthStateInCookie: true
  },
```

### Relevant Code Snippets

```javascript
//login  
const { instance } = useMsal();
  const redirectStartPage = window.sessionStorage.getItem('local-url') || '/';

  return async () => instance.loginRedirect({ ...loginRequest, redirectStartPage });
```

### Reproduction Steps

1.open the app in two tabs
2.try to login in first tab,
3.while the login is in progress in first tab,try to login in the second tab.
4.repeat the same with logout as well

### Expected Behavior

The user should be able to logout/login in multiple tabs simultaneously without any error

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Edge

### Source

External (Customer)

**Comment by surielmx** [comment]
Same issue, solved deleting sessionStorage, but check [this](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/caching.md#warning-warning)

**Comment by konstantin-msft** [comment]
Hi @saibunneesashaik. Concurrent interactive requests are not permitted by design. Please refer [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/msal-lts/lib/msal-browser/docs/acquire-token.md#attempt-silent-request-first-then-interactive) for more details.
