### ISSUE TITLE
React redirect flow abruptly quits during the internal login step

### ISSUE THREAD

**Issue by geoff-harper** [AzureAD/microsoft-authentication-library-for-js#6247]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.37.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.5.7

### Public or Confidential Client?

Public

### Description

Hello. I'm trying to get my auth flow working with a custom policy and I'm getting stuck during the redirect interaction. I land on the app, get sent over to auth, and sent back, but when I return msal looks around a bit and just fizzles out. Specifically, [this seems to be the last meaningful log produced.](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/0d8457479870564784530839c5a17d0b38df1a00/lib/msal-react/src/hooks/useMsalAuthentication.ts#L259). What I'm left with is never reaching authentication and the hash state still in the url. We've tried another policy and that is working with no code changes outside of config swap. This could entirely mean the custom policy is borked but if we could get set on the right path to figuring it out client or idp side that would be great. Thanks

### Msal Logs

localhost:3001

[vite] connected. client:286:21
[Tue, 18 Jul 2023 18:28:41 GMT] : @azure/msal-react@1.5.7 : Info - useAccount - Updating account azure.ts:32:21
[Tue, 18 Jul 2023 18:28:41 GMT] : [762105ab-ad24-4926-b5d7-b6ecaa090ec8] : @azure/msal-browser@2.37.0 : Info - PerformanceClient: No correlation id provided for initializeClientApplication, generating azure.ts:32:21
[Tue, 18 Jul 2023 18:28:41 GMT] : @azure/msal-browser@2.37.0 : Info - Emitting event: msal:initializeStart azure.ts:32:21
[Tue, 18 Jul 2023 18:28:41 GMT] : @azure/msal-browser@2.37.0 : Info - Emitting event: msal:initializeEnd azure.ts:32:21
[Tue, 18 Jul 2023 18:28:41 GMT] : @azure/msal-react@1.5.7 : Info - useAccount - Updating account azure.ts:32:21
[Tue, 18 Jul 2023 18:28:41 GMT] : @azure/msal-browser@2.37.0 : Info - initialize has already been called, exiting early. azure.ts:32:21
[Tue, 18 Jul 2023 18:28:41 GMT] : @azure/msal-browser@2.37.0 : Info - Emitting event: msal:handleRedirectStart azure.ts:32:21
[Tue, 18 Jul 2023 18:28:41 GMT] : [1f031b33-fb48-451d-84e3-55ee14418a03] : msal.js.browser@2.37.0 : Info - handleRedirectPromise did not detect a response hash as a result of a redirect. Cleaning temporary cache. azure.ts:32:21
[Tue, 18 Jul 2023 18:28:41 GMT] : @azure/msal-browser@2.37.0 : Info - Emitting event: msal:handleRedirectEnd azure.ts:32:21
[Tue, 18 Jul 2023 18:28:42 GMT] : @azure/msal-react@1.5.7 : Info - MsalProvider - msal:handleRedirectStart results in setting inProgress from startup to handleRedirect azure.ts:32:21
[Tue, 18 Jul 2023 18:28:42 GMT] : @azure/msal-react@1.5.7 : Info - MsalProvider - msal:handleRedirectEnd results in setting inProgress from handleRedirect to none azure.ts:32:21
[Tue, 18 Jul 2023 18:28:42 GMT] : @azure/msal-react@1.5.7 : Info - MsalProvider - msal:handleRedirectStart results in setting inProgress from startup to handleRedirect localhost:3001:342:29
[Tue, 18 Jul 2023 18:28:42 GMT] : @azure/msal-react@1.5.7 : Info - MsalProvider - msal:handleRedirectEnd results in setting inProgress from handleRedirect to none localhost:3001:342:29
[Tue, 18 Jul 2023 18:28:42 GMT] : @azure/msal-react@1.5.7 : Info - useMsalAuthentication - No user is authenticated, attempting to login azure.ts:32:21
[Tue, 18 Jul 2023 18:28:42 GMT] : @azure/msal-browser@2.37.0 : Info - Emitting event: msal:loginStart azure.ts:32:21
[Tue, 18 Jul 2023 18:28:42 GMT] : @azure/msal-react@1.5.7 : Info - MsalProvider - msal:loginStart results in setting inProgress from none to login azure.ts:32:21
[Tue, 18 Jul 2023 18:28:42 GMT] : @azure/msal-react@1.5.7 : Info - MsalProvider - msal:loginStart results in setting inProgress from none to login localhost:3001:342:29
[Tue, 18 Jul 2023 18:28:42 GMT] : @azure/msal-react@1.5.7 : Info - useAccount - Updating account azure.ts:32:21
[Tue, 18 Jul 2023 18:28:42 GMT] : @azure/msal-react@1.5.7 : Info - useAccount - Updating account localhost:3001:342:29
[Tue, 18 Jul 2023 18:28:42 GMT] : @azure/msal-react@1.5.7 : Info - useAccount - Updating account azure.ts:32:21
[Tue, 18 Jul 2023 18:28:42 GMT] : @azure/msal-react@1.5.7 : Info - useAccount - Updating account localhost:3001:342:29

XHRGET
PII -> /v2.0/.well-known/openid-configuration

Navigated to 
PII -> the b2c login page

[vite] connecting... client:206:9
[vite] connected. client:286:21
[Tue, 18 Jul 2023 18:28:48 GMT] : @azure/msal-react@1.5.7 : Info - useAccount - Updating account azure.ts:32:21
[Tue, 18 Jul 2023 18:28:48 GMT] : [0b4c671b-6409-4b2a-8da2-6c12fff51efc] : @azure/msal-browser@2.37.0 : Info - PerformanceClient: No correlation id provided for initializeClientApplication, generating azure.ts:32:21
[Tue, 18 Jul 2023 18:28:48 GMT] : @azure/msal-browser@2.37.0 : Info - Emitting event: msal:initializeStart azure.ts:32:21
[Tue, 18 Jul 2023 18:28:48 GMT] : @azure/msal-browser@2.37.0 : Info - Emitting event: msal:initializeEnd azure.ts:32:21
[Tue, 18 Jul 2023 18:28:48 GMT] : @azure/msal-react@1.5.7 : Info - useAccount - Updating account azure.ts:32:21
[Tue, 18 Jul 2023 18:28:48 GMT] : @azure/msal-browser@2.37.0 : Info - initialize has already been called, exiting early. azure.ts:32:21
[Tue, 18 Jul 2023 18:28:48 GMT] : @azure/msal-browser@2.37.0 : Info - Emitting event: msal:handleRedirectStart azure.ts:32:21
[Tue, 18 Jul 2023 18:28:48 GMT] : [aabea941-95d0-470a-aa73-88d4ad981872] : msal.js.browser@2.37.0 : Info - handleRedirectPromise called but there is no interaction in progress, returning null. azure.ts:32:21
[Tue, 18 Jul 2023 18:28:48 GMT] : @azure/msal-browser@2.37.0 : Info - Emitting event: msal:handleRedirectEnd azure.ts:32:21
[Tue, 18 Jul 2023 18:28:48 GMT] : @azure/msal-react@1.5.7 : Info - MsalProvider - msal:handleRedirectStart results in setting inProgress from startup to handleRedirect azure.ts:32:21
[Tue, 18 Jul 2023 18:28:48 GMT] : @azure/msal-react@1.5.7 : Info - MsalProvider - msal:handleRedirectEnd results in setting inProgress from handleRedirect to none azure.ts:32:21
[Tue, 18 Jul 2023 18:28:48 GMT] : @azure/msal-react@1.5.7 : Info - MsalProvider - msal:handleRedirectStart results in setting inProgress from startup to handleRedirect localhost:3001:342:29
[Tue, 18 Jul 2023 18:28:48 GMT] : @azure/msal-react@1.5.7 : Info - MsalProvider - msal:handleRedirectEnd results in setting inProgress from handleRedirect to none localhost:3001:342:29
[Tue, 18 Jul 2023 18:28:48 GMT] : @azure/msal-react@1.5.7 : Info - useMsalAuthentication - No user is authenticated, attempting to login azure.ts:32:21
[Tue, 18 Jul 2023 18:28:48 GMT] : @azure/msal-react@1.5.7 : Info - useAccount - Updating account azure.ts:32:21
[Tue, 18 Jul 2023 18:28:48 GMT] : @azure/msal-react@1.5.7 : Info - useAccount - Updating account localhost:3001:342:29

Navigated to 
PII -> localhost with a state hash that seems valid

[vite] connecting... client.ts:18:8
[vite] connected. client.ts:133:14
[Tue, 18 Jul 2023 18:32:16 GMT] : @azure/msal-react@1.5.7 : Info - useAccount - Updating account azure.ts:32:21
[Tue, 18 Jul 2023 18:32:16 GMT] : [1da9727c-3b1f-4305-94f4-7a0f66e5b12b] : @azure/msal-browser@2.37.0 : Info - PerformanceClient: No correlation id provided for initializeClientApplication, generating azure.ts:32:21
[Tue, 18 Jul 2023 18:32:16 GMT] : @azure/msal-browser@2.37.0 : Info - Emitting event: msal:initializeStart azure.ts:32:21
[Tue, 18 Jul 2023 18:32:16 GMT] : @azure/msal-browser@2.37.0 : Info - Emitting event: msal:initializeEnd azure.ts:32:21
[Tue, 18 Jul 2023 18:32:16 GMT] : @azure/msal-react@1.5.7 : Info - useAccount - Updating account azure.ts:32:21
[Tue, 18 Jul 2023 18:32:16 GMT] : @azure/msal-browser@2.37.0 : Info - initialize has already been called, exiting early. azure.ts:32:21
[Tue, 18 Jul 2023 18:32:16 GMT] : @azure/msal-browser@2.37.0 : Info - Emitting event: msal:handleRedirectStart azure.ts:32:21
[Tue, 18 Jul 2023 18:32:16 GMT] : [98834aea-fb6f-4f53-a7a5-99154e242cee] : msal.js.browser@2.37.0 : Info - handleRedirectPromise called but there is no interaction in progress, returning null. azure.ts:32:21
[Tue, 18 Jul 2023 18:32:16 GMT] : @azure/msal-browser@2.37.0 : Info - Emitting event: msal:handleRedirectEnd azure.ts:32:21
[Tue, 18 Jul 2023 18:32:16 GMT] : @azure/msal-react@1.5.7 : Info - MsalProvider - msal:handleRedirectStart results in setting inProgress from startup to handleRedirect azure.ts:32:21
[Tue, 18 Jul 2023 18:32:16 GMT] : @azure/msal-react@1.5.7 : Info - MsalProvider - msal:handleRedirectEnd results in setting inProgress from handleRedirect to none azure.ts:32:21
[Tue, 18 Jul 2023 18:32:16 GMT] : @azure/msal-react@1.5.7 : Info - MsalProvider - msal:handleRedirectStart results in setting inProgress from startup to handleRedirect localhost:3001:342:29
[Tue, 18 Jul 2023 18:32:16 GMT] : @azure/msal-react@1.5.7 : Info - MsalProvider - msal:handleRedirectEnd results in setting inProgress from handleRedirect to none localhost:3001:342:29
[Tue, 18 Jul 2023 18:32:17 GMT] : @azure/msal-react@1.5.7 : Info - useMsalAuthentication - No user is authenticated, attempting to login azure.ts:32:21
[Tue, 18 Jul 2023 18:32:17 GMT] : @azure/msal-react@1.5.7 : Info - useAccount - Updating account azure.ts:32:21
[Tue, 18 Jul 2023 18:32:17 GMT] : @azure/msal-react@1.5.7 : Info - useAccount - Updating account localhost:3001:342:29

### MSAL Configuration

```javascript
const config: Configuration = {
  auth: {
    clientId: import.meta.env.VITE_VIEWER_AZURE_CLIENT_ID,
    authority: `https://${import.meta.env.VITE_VIEWER_AZURE_TENANT}.b2clogin.com/${import.meta.env.VITE_VIEWER_AZURE_TENANT}.onmicrosoft.com/${import.meta.env.VITE_VIEWER_AZURE_POLICY}`,
    knownAuthorities: [
      `${import.meta.env.VITE_VIEWER_AZURE_TENANT}.b2clogin.com`,
    ],
    redirectUri: window.location.origin,
    postLogoutRedirectUri:
      window.location.origin + import.meta.env.VITE_AZURE_LOGOUT_URI,
  },
  system: {
    loggerOptions: {
      loggerCallback: (level: LogLevel, message: string): void => {
        switch (level) {
          case LogLevel.Error:
            console.error(message);
            return;
          case LogLevel.Info:
            console.info(message);
            return;
          case LogLevel.Verbose:
            console.debug(message);
            return;
          case LogLevel.Warning:
            console.warn(message);
            return;
        }
      },
      piiLoggingEnabled: false,
    },
  },
};
```

### Relevant Code Snippets

```javascript
type GateProps = {
  children: React.ReactNode;
};
function AuthGate(props: GateProps): JSX.Element {
  const {instance, inProgress} = useMsal();
  const active = instance.getActiveAccount();
  const first = instance.getAllAccounts()[0];
  const isAuthenticated = useIsAuthenticated({username: first?.username});

  useEffect(() => {
    if (!active && first) {
      instance.setActiveAccount(first);
    }
  }, [active, first, instance]);

  const auth = useMsalAuthentication(InteractionType.Redirect, mainRequest);
  const {error, login} = auth;

  const shouldRetryAfterError =
    !!error &&
    // https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/hooks.md#ssosilent-example
    (error instanceof InteractionRequiredAuthError ||
      // https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/errors.md#x-frame-options-deny
      error.errorCode === 'monitor_window_timeout');

  // useEffect(() => {
  //   if (shouldRetryAfterError && inProgress === InteractionStatus.None) {
  //     login(InteractionType.Redirect);
  //   }
  // }, [shouldRetryAfterError, error, inProgress, login]);

  if (error && !shouldRetryAfterError) {
    return <MainErrorScreen error={error} />;
  }

  // eslint-disable-next-line react/jsx-no-useless-fragment
  return isAuthenticated ? <>{props.children}</> : <LoadingScreen />;
}
```

### Reproduction Steps

The codebase is proprietary and it's a custom policy so I'm not quite sure how to do this.

### Expected Behavior

From a cold start, I expect the tab to get kicked over to b2clogin.com and then returned with a valid token. Once redirect works I'm going to change the argument in the auth hook back to silent and only redirect as required.

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari

### Source

External (Customer)

**Comment by konstantin-msft** [comment]
Hi @geoff-harper. Can you please provide [MSAL verbose logs](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logging.md) and send a .har file to my GH email?

**Comment by geoff-harper** [comment]
Please keep this open. I sent the info over by email per request

**Comment by tnorling** [comment]
@geoff-harper I've taken a look at your logs and it appears MSAL isn't able to find the temporary cache artifacts in sessionStorage. When you return to your app after the redirect, what do you see in sessionStorage? If the msal temporary cache entries are missing you'll need to determine what is removing them.

**Comment by geoff-harper** [comment]
@tnorling should I send it in a followup email or reply here? In session storage I have 8 msal entries and one of them has `{type: 'UPN', credential: $MY_EMAIL}`. Which one in particular am I looking for?

**Comment by lalimasharda** [comment]
Hey @geoff-harper , can you email me the entries along with the email history?

**Comment by geoff-harper** [comment]
@lalimasharda emailed!
