### ISSUE TITLE
App URI ID in aud property of access token

### ISSUE THREAD

**Issue by ryandegruyter** [AzureAD/microsoft-authentication-library-for-js#625]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Library version

0.1.2

## Current behavior
I set the App URI ID as the clientId. The aud parameter in the jwt access token contains the App UUID as a value

## Expected behavior
Set App URI ID as the clientId -> aud property equals the App URI ID
Set App UUID as the clientId -> aud property equals the App UUID

## Minimal reproduction of the problem with instructions
<code></pre>

clientID: 'https://example.onmicrosoft.com/ExampleAPI',
authority: 'https://login.microsoftonline.com/example.onmicrosoft.com',
redirectUri: 'https://bla-acc-test.eu'

</code></pre>

**Comment by aashiman** [comment]
Are you checking the access token or id token or both ? is your client app and API app the same app ID?

**Comment by ryandegruyter** [comment]
Checking the access token.

Client app and API app don't have the same clientId.

**Comment by aashiman** [comment]
Can you please confirm that the access token version for this API / app ID URL is 1? We only support these attributes for atver=1 access tokens

**Comment by ryandegruyter** [comment]
Ah I see, we have token version 2.0

**Comment by sameerag** [comment]
@ryandegruyter does this clarify your question? Can we close this ticket? Please let us know.

**Comment by ryandegruyter** [comment]
Yes, will there be any support for v2 tokens in the near future?

**Comment by sameerag** [comment]
@ryandegruyter I am following up with the service team internally if this is planned for v2. Can update once I hear from them.

**Comment by sameerag** [comment]
@ryandegruyter I checked with the service, unfortunately at this point they do not intend to support this behavior on v2 tokens. The v1 behavior introduced certain complexity in validation code and hence the decision.

**Comment by jmprieur** [comment]
@ryandegruyter : if you are using msal.js, you are on the client side?
You should not look at the content of the access token (which is only for the Web API).
Or do I miss something?
