### ISSUE TITLE
"interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API" Error appears when user re-signs in after cancelling auth window login.

### ISSUE THREAD

**Issue by jjmacapagal** [AzureAD/microsoft-authentication-library-for-js#6251]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.37.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

When using the sample, [Chromium Extension Sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-browser-samples/ChromiumExtensionSample), the user is to sign-in after opening the extension button. if the user accidentally closed the auth popup window and tried to re-login again, console throws "interaction_in_progress" error.

### Error Message

"interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API"

### MSAL Configuration

```javascript
{
  auth: {
    authority: `https://login.microsoftonline.com/${tenant}`,
    clientId: `${clientId}`,
    redirectUri,
    postLogoutRedirectUri: redirectUri,
  },
  cache: {
    cacheLocation: "sessionStorage",
    storeAuthStateInCookie: true,
  },
}
```

### Relevant Code Snippets

```javascript
async function getLoginUrl(request) {
  return new Promise((resolve, reject) => {
    msalInstance
      .loginRedirect({
        ...request,
        onRedirectNavigate: (url) => {
          resolve(url);
          return false;
        },
      })
      .catch(reject);
  });
}
```

### Reproduction Steps

1. install [MSAL chrome extension](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-browser-samples/ChromiumExtensionSample)
2. open extension
3. extension popup window appears
4. click sign in
5. auth window appears
6. close auth window
7. re-open extension
8. re-sign in
9. console throws error.

### Expected Behavior

user should not encounter "interaction_in_progress" if they accidentally closed the auth window.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

External (Customer)

**Comment by surielmx** [comment]
Same issue, solved deleting sessionStorage, but check [this](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/caching.md#warning-warning)

**Comment by sameerag** [comment]
Guidance above holds. I am checking if we can improve the UX here, will reach out when we have it. Until then, please clear the storage as suggested above to be unblocked.
