### ISSUE TITLE
msal-browser error hash_does_not_contain_known_properties just in mobile browser (Chrome, safari, etc)

### ISSUE THREAD

**Issue by apriansyah19** [AzureAD/microsoft-authentication-library-for-js#6253]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.38.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

I get this error when login popup msal-browser :

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/59590356/a43ca911-50e6-433b-b9bd-0159567b0f15)

this is my app registration 
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/59590356/d32a6338-a267-4854-a65e-48037cbd271c)

this is my url when login https://vue-msal-browser.netlify.app/#/sign-in

### Error Message

Error - PopupHandler.monitorPopupForHash - found hash in url but it does not contain known properties. Check that your router is not changing the hash prematurely.

### MSAL Configuration

```javascript
import { LogLevel, PublicClientApplication } from "@azure/msal-browser";

const msalConfig = new PublicClientApplication({
    auth: {
        clientId: "{{CENSORED}}",
        authority: "https://login.microsoftonline.com/common",
        redirectUri: 'https://vue-msal-browser.netlify.app/'
    },
    cache: {
        cacheLocation: "localStorage", // This configures where your cache will be stored
        storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
    },
    system: {
        allowNativeBroker: false, // Disables WAM Broker
        loggerOptions: {
            loggerCallback: (level, message, containsPii) => {
                if (containsPii) {
                    return;
                }
                switch (level) {
                    case LogLevel.Error:
                        console.error(message);
                        return;
                    case LogLevel.Info:
                        console.info(message);
                        return;
                    case LogLevel.Verbose:
                        console.debug(message);
                        return;
                    case LogLevel.Warning:
                        console.warn(message);
                        return;
                }
            }
        }
    }
})

const loginRequest = {
    scopes: ["User.Read"]
};


export {msalConfig, loginRequest}
```

### Relevant Code Snippets

```javascript
import { loginRequest, msalConfig } from "@/services/SSOMsal";
import { onBeforeMount } from "vue";
import { useRouter } from "vue-router";
const router = useRouter();
const Login = async () => {
  try {
    await msalConfig.loginPopup(loginRequest);
    router.push({ name: "dashboard" });
  } catch (error) {
    console.log(error);
  }
};
```

### Reproduction Steps

1. login with popup msal-browser "this is my url when login https://vue-msal-browser.netlify.app/#/sign-in"
2. enter e-mail and password
3. Authentication success but i got error [hash_does_not_contain_known_properties]

### Expected Behavior

i have not error in mobile browser

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer

### Source

Internal (Microsoft)

**Comment by konstantin-msft** [comment]
Hi @apriansyah19. Do you come across this error on mobile browsers only? Also, can you please double check that `redirectUri` page is not being manipulated by Vue router? Please refer [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/errors.md#hash_does_not_contain_known_properties) for more details.

**Comment by apriansyah19** [comment]
is it problem if i use hash ? @konstantin-msft

**Comment by sameerag** [comment]
@apriansyah19 What happens if you do not use hash? Can you verify?

**Comment by apriansyah19** [comment]
my login url is "https://vue-msal-browser.netlify.app/#/sign-in"
and the redirect uri in the msal config "https://vue-msal-browser.netlify.app/"
and I registered in the redirect url app registration portal azure "https://vue-msal-browser.netlify.app/" is that a problem 
because my login url uses hash(#) ? @sameerag

**Comment by sameerag** [comment]
@apriansyah19 It is possible when you reload the page, the `hash` in login is being understood as the `hash` we expect when we try strip the `auth code`. However, if you `redirectUri` is not having a hash and you do not reload your page, it should be fine. As I see you are using only popup, I do not think you reload your page.

I suspect what @konstantin-msft mentioned above, if the `vue` router is stripping the hash. You can find that by verfying when the page is loaded if there is a hash before and after the routing logic. Please let us know or send us the logs before and after the router code execution.

**Comment by Iworb** [comment]
I have a similar issue but with an Angular app. My router uses hash. Chrome-like browsers open a popup window to sign in without any problem, but Safari and mobile ones use the redirect mode to sign in. I thought I was able to change this behavior by changing the "responseMode", but in [this ticket](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2228) mentioned that I'm not able to do that. It says that the "query" mode is not safe, but how about the "matrix" one?

We need a way to sign in to the applications that rely on the hash for their own routing.
