### ISSUE TITLE
getAllAccounts() it only return 1 account of previous user using MSAL in SPFX component with SharePoint switch user using ‘sign in as different user’ in same browser session (window/tab)

### ISSUE THREAD

**Issue by devanshuGit** [AzureAD/microsoft-authentication-library-for-js#6258]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.34.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

i followed an article for implementing MSAL 2.0 in SPFX
https://mmsharepoint.wordpress.com/2020/08/15/using-msal-js-2-0-in-sharepoint-framework-spfx/.
MSAL is integrated and it works fine to call Graph or Custom API protected with Azure AD.

We are facing problem with multiple accounts and handling it. SharePoint allows switch user using ‘sign in as different user’, so in same session (browser window/tab) allows to sign in with different account. When we do that, MSAL still takes previous user (current account). Even with getAllAccounts() it only return 1 account of previous user so it silently generates token for that user and data for that user is being fetched. We were expecting to get multiple account from MSAL and then from current logged-in user use correct account to work with to get tokens. But this is kind of security concern as well as one user can see data of another user.
Also getAccountByUsername() returns null even by passing user login from page context.

### Error Message

There is no error message, instead MSAL is still taking previous user session and generating token as explained above

### Msal Logs

[Mon, 24 Jul 2023 05:51:26 GMT] : @azure/msal-browser@2.34.0 : Info - Emitting event: msal:handleRedirectStart
beeah-notification-application-customizer_4b8089b3f313a2890c09.js:2 [Mon, 24 Jul 2023 05:51:26 GMT] : [993be30d-ee8f-41c3-85f6-a73abc35ba37] : msal.js.browser@2.34.0 : Info - handleRedirectPromise called but there is no interaction in progress, returning null.
beeah-notification-application-customizer_4b8089b3f313a2890c09.js:2 [Mon, 24 Jul 2023 05:51:26 GMT] : @azure/msal-browser@2.34.0 : Info - Emitting event: msal:handleRedirectEnd
beeah-notification-application-customizer_4b8089b3f313a2890c09.js:2 [Mon, 24 Jul 2023 05:51:26 GMT] : @azure/msal-browser@2.34.0 : Info - Emitting event: msal:acquireTokenStart
beeah-notification-application-customizer_4b8089b3f313a2890c09.js:2 [Mon, 24 Jul 2023 05:51:26 GMT] : @azure/msal-browser@2.34.0 : Info - Emitting event: msal:acquireTokenSuccess
directline-bot-extension-application-customizer_a5a3286513157f2bb5b9.js:2 [Mon, 24 Jul 2023 05:51:27 GMT] : @azure/msal-browser@2.34.0 : Info - Emitting event: msal:handleRedirectStart
directline-bot-extension-application-customizer_a5a3286513157f2bb5b9.js:2 [Mon, 24 Jul 2023 05:51:27 GMT] : [2dcaabaf-70bc-4f09-987c-8f66fcd12e6e] : msal.js.browser@2.34.0 : Info - handleRedirectPromise called but there is no interaction in progress, returning null.
directline-bot-extension-application-customizer_a5a3286513157f2bb5b9.js:2 [Mon, 24 Jul 2023 05:51:27 GMT] : @azure/msal-browser@2.34.0 : Info - Emitting event: msal:handleRedirectEnd
directline-bot-extension-application-customizer_a5a3286513157f2bb5b9.js:2 [Mon, 24 Jul 2023 05:51:27 GMT] : @azure/msal-browser@2.34.0 : Info - Emitting event: msal:acquireTokenStart
directline-bot-extension-application-customizer_a5a3286513157f2bb5b9.js:2 [Mon, 24 Jul 2023 05:51:27 GMT] : @azure/msal-browser@2.34.0 : Info - Emitting event: msal:acquireTokenSuccess

### MSAL Configuration

```javascript
const MSAL_CONFIG: Configuration = {
    auth: environment.MSALauth,
    cache: {
        cacheLocation: "sessionStorage", // This configures where your cache will be stored
        storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
    }
}

Environment file value: masked
MSALauth: {
    authority: "https://login.microsoftonline.com/503xxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    clientId: "314xxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    redirectUri: "https://xxxxxx.sharepoint.com/_layouts/15/workbench.aspx"
  },
```

### Relevant Code Snippets

```javascript
SPFx main component tsx file code:
this.authModule = new AuthModule(this.context.pageContext.user.loginName); //contructor
this.adtoken = await this.authModule.loadAuthModule(); // renderPlaceHolder

AuthModule code
/**
     * Checks whether we are in the middle of a redirect and handles state accordingly. Only required for redirect flows.
     * 
     * https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/initialization.md#redirect-apis
     */
    async loadAuthModule(): Promise<string> {
        try {
            const resp = await this.myMSALObj.handleRedirectPromise();
            return await this.handleResponse(resp);
        } catch (message) {
            console.error(message);
            return null;
        }
    }

    /**
     * Handles the response from a popup or redirect. If response is null, will check if we have any accounts and attempt to sign in.
     * @param response 
     */
    async handleResponse(response: AuthenticationResult | null) : Promise<string>{
        var currentAccounts = [];
        if (response !== null) {
            currentAccounts.push(response.account);
        } else {
            currentAccounts = this.myMSALObj.getAllAccounts();
        }

        if (currentAccounts !== null && currentAccounts.length > 0) {
            const accessToken = await this.handleLoggedInUser(currentAccounts, this.userName);
            return accessToken;
          }
          else {
            const token = await this.loginForAccessTokenByMSAL();
            return token;
    }
}

private async loginForAccessTokenByMSAL(): Promise<string> {
        /*var ssoSilentRequest: SsoSilentRequest = {
          ...this.ootfSSOScopes,
          loginHint: userName
        }*/
        return this.myMSALObj.ssoSilent(this.silentSSOOOTFAccessRequest).then((response) => {
          return response.accessToken;  
        }).catch((silentError) => {  
            console.log(silentError);
            if (silentError instanceof InteractionRequiredAuthError) {
              if(silentError.errorCode == 'login_required')
              {
                return 'login_required';
              }
              else{
              return this.myMSALObj.loginPopup(this.ootfSSOScopes)
              .then((response) => {
                return response.accessToken;
              }) 
              .catch(popupError => {
                if (popupError.message.indexOf('popup_window_error') > -1) { // Popups are blocked
                  return this.redirectLogin(this.ootfSSOScopes);
                }            
              });
            }
            }
            else if (silentError instanceof BrowserAuthError){
             
               if (silentError.errorCode === "monitor_window_timeout") {
                return 'login_required';
              }
              if (silentError.errorCode === "popup_window_error") {
                return 'login_required';
              }

            }
             else {
                return null;
            }
        });  
      }

    private async handleLoggedInUser(currentAccounts: AccountInfo[], userName: string): Promise<string> {
        let accountObj = null;
        if (currentAccounts === null) {
          // No user signed in
          return;
        } else if (currentAccounts.length > 1) {
            // More than one user is authenticated, get current one 
            accountObj = this.myMSALObj.getAccountByUsername(userName);
        } else {
            accountObj = currentAccounts[0];
            //accountObj=this.myMSALObj.getActiveAccount();
        }
        if (accountObj !== null) {
          try {
                const accessToken = await this.acquireAccessToken(this.silentOOTFAccessRequest, accountObj);
                return accessToken;
            } catch (error) {
                console.log(error);
                return null;
            }
        }    
      }
    
      private async acquireAccessToken(ssoRequest: SilentRequest, account: AccountInfo): Promise<string> {
        const accessTokenRequest: SilentRequest = {
          scopes: ssoRequest.scopes,
          account: account
        };
        return this.myMSALObj.acquireTokenSilent(accessTokenRequest).then((val) => {            
          return val.accessToken;
        }).catch((errorinternal) => {  
          console.log(errorinternal);  
          return null;
        }); 
      }
    
      private redirectLogin(ssoRequest: RedirectRequest): Promise<string> {
        try {      
          this.myMSALObj.loginRedirect(ssoRequest)
            .then(() => {
              return Promise.resolve('');
            });
          
        } catch (err) {
            console.log(err);
            return null;
        }
      }
```

### Reproduction Steps

using above MSAL config and placing code in any SPFx component it can be reproduce easily.
or else can clone below git repo for reproducing it
https://github.com/mmsharepoint/msal-20-spfx-demo/tree/master

### Expected Behavior

Expecting to get multiple account from MSAL when switching user sign-ins in SharePoint and then from current logged-in user use correct account to work with to get tokens. Nowhere we are setting active account in the code and explicitly passing accounts object to obtain token

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox

### Source

External (Customer)

**Comment by sameerag** [comment]
@devanshuGit Can you confirm if your app cache (sessionStorage as per your config) has multiple accounts? `getAllAccounts` should ideally fetch all the accounts in the cache and I would like to know if they are created in the first place.

**Comment by devanshuGit** [comment]
@sameerag are you referring to following cache key, if yes then it holds only 1 account token that too of previous user.
both keys with 'authority' only differs in scopes and expiration time but for old user. The below cache screen shot is post switching user in same browser window. However other session keys are updated to take new signed-in user (screenshot 2), even session key 'sessionTracking_ActiveAccountIdentifier' has modified value pointing to new user

Let me know if we are looking for some other session key.

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/9657686/ab0b1cb2-5036-4ed4-bb79-398e59f45ae7)

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/9657686/bb65dacb-46ae-401c-9978-01fcc6f1c267)

**Comment by sameerag** [comment]
@devanshuGit I think the silent call made with a new user in your case is matching the cache instead of going to the network. However I do not see a check for a specific account in your code.

Is the `username` same for both the accounts?
> const accessToken = await this.handleLoggedInUser(currentAccounts, this.userName);

Your options are to set an account `active` using our `setActiveAccount()` API or somehow filter the user you want to match. I do not see that in the code above.

**Comment by devanshuGit** [comment]
@sameerag userName is not same for both user and it's not specific any 2 users. Issue is in general for any user, the scenario if 2 different tries to login using 'signed-in as different user' option on SharePoint site with Account panel on top right (believe this is standard across all O365 products).

`this.username` is passed from pageContext as `this.context.pageContext.user.loginName` (coming from library _@microsoft — /sp-extension-base#BaseExtension.context_) and i can see for different users it is passed correctly. 

slient calls is working as token from previous user still persist in cache and hence it is using that token. However when new user signs-in cache key should be updated or new keys should be created to handle multiple accounts scenario.

is there a way to connect to show it in action (over teams or other communication channel), i think that would help for better understanding?

**Comment by devanshuGit** [comment]
@hectormmg let me know if you need more details as well as is there a communication channel to connect over and show it in action, i feel that would help better understanding and quick resolution

**Comment by hectormmg** [comment]
@devanshuGit MSAL is caching both accounts but unless you pass in a specific account object in the token request, MSAL will use the "active" account by default. You can either pick the account you want for each token request and MSAL will use the account you pass in, or you can set that account as the "active account" and MSAL will use it for every request.

**Comment by devanshuGit** [comment]
@hectormmg if MSAL is caching both accounts there should be 2 session keys or some identification of 2 accounts in session storage as that is configured for MSAL in the application to use session storage. kindly check this reply [https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/6258#issuecomment-1649269539](url).
Also that is what we were expecting with getAllAccounts() to fetch multiple signed-in user accounts but it only return 1 account of previous user. If you check code snippet (updated in original issue description) method 'handleLoggedInUser' we are passing account object for each request to get token. In fact getAccountByUsername() returns null even by passing user login from page context.

**Comment by tnorling** [comment]
@devanshuGit Are you using MSAL to sign both users in? If I'm understanding correctly, you're signing the 2nd user in out of band. The MSAL cache is only aware of accounts which it was responsible for signing in

**Comment by devanshuGit** [comment]
@tnorling as it is SPFx component (hosted on SharePoint site, doesn't have it's own mechanism for login) leveraging MSAL.js, it uses SharePoint context to get signed-in user email or UPN (`this.context.pageContext.user.loginName`).

Some lines of code to explain the flow. Below lines are executed on page load to load SPFx component from `render` method
```
SPFx main component tsx file code:
this.authModule = new AuthModule(this.context.pageContext.user.loginName); //contructor
this.adtoken = await this.authModule.loadAuthModule(); // renderPlaceHolder
```
Explaining flow of code once Authmodule is loaded in steps (Refer actual issue description for relevant code snippet):

1. This line always returns null as it is not redirected from login
`this.myMSALObj.handleRedirectPromise();` and 
2. flow continues to `this.handleResponse(resp);` with null `resp` variable
3. Within handleResponse, gets into `else` `currentAccounts = this.myMSALObj.getAllAccounts();` and continues to below
4. `const accessToken = await this.handleLoggedInUser(currentAccounts, this.userName);`
5. Within in handleLoggedInUser, goes to `else` part `accountObj = currentAccounts[0];`
6. And finally to retrieve access token with silent call `const accessToken = await this.acquireAccessToken(this.silentOOTFAccessRequest, accountObj);`

Were expecting this line to return multiple account objects `this.myMSALObj.getAllAccounts()` but it returns only previous user.

One observation here though, first time when we browse to SharePoint site page (hosted SPFx component), user login interaction happens and it details are captured in session storage by MSAL (again note `this.myMSALObj.handleRedirectPromise();` still returns null).

Now when use below option 'sign in with different user', though login interaction happens by going to Microsoft login page
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/9657686/e49532e5-915f-4391-b743-2f0ff40b5be2)

Post login it redirects to SharePoint home, instead of the actual site i.e. [https://contoso.sharepoint.com/_layouts/15/sharepoint.aspx](https://contoso.sharepoint.com/_layouts/15/sharepoint.aspx)
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/9657686/cbcd9e47-879d-4fba-800d-c593659beddd)

Not sure whether this is the cause of behavior for MSAL not to capture another user login and still persist data of previous user. However when navigating to actual site, flow is same as explained above in steps.

**Comment by tnorling** [comment]
That sign-in pane is not using MSAL.js. When you click "Sign-in with a different account" MSAL is not made aware that a sign-in is occurring and does not handle the response in order to cache the account. If you were to make another request **after** this with MSAL.js you would be signed in without re-entering your credentials and the cache would then be populated with both accounts.

**Comment by devanshuGit** [comment]
@tnorling could you please elaborate more on making another request with MSAL.js? any sample would be more helpful. and Also which cache properties should be verified/checked to look for accounts cached by MSAL in session storage?  is this the one in the reply posted 


> @sameerag are you referring to following cache key, if yes then it holds only 1 account token that too of previous user. both keys with 'authority' only differs in scopes and expiration time but for old user. The below cache screen shot is post switching user in same browser window. However other session keys are updated to take new signed-in user (screenshot 2), even session key 'sessionTracking_ActiveAccountIdentifier' has modified value pointing to new user
> 
> Let me know if we are looking for some other session key.
> 
> ![image](https://user-images.githubusercontent.com/9657686/255819026-ab0b1cb2-5036-4ed4-bb79-398e59f45ae7.png)
> 
> ![image](https://user-images.githubusercontent.com/9657686/255821655-bb65dacb-46ae-401c-9978-01fcc6f1c267.png)

**Comment by tnorling** [comment]
The same way you made the first one. The account is the one whose value starts with {"authorityType: "MSSTS"...

Also for SPFx components we typically suggest you use the APIs provided by SharePoint rather than using MSAL.js directly, this may give you a better experience. See the docs for that [here](https://learn.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient#connect-to-azure-ad-applications-using-the-aadhttpclient) they should have some samples linked as well. The MSAL.js team does not own these package, however, so any questions you have about the SharePoint packages should be directed at [SharePoint](https://learn.microsoft.com/en-us/sharepoint/dev/support-feedback)

**Comment by devanshuGit** [comment]
@tnorling 
1. We were using APIs provided by SharePoint i.e. AadHttpClient or AADTokenProvider but there was no finer control for example if cookies are disabled or any other problems arising in token generation hence then as pointed out in this article
[https://mmsharepoint.wordpress.com/2020/08/15/using-msal-js-2-0-in-sharepoint-framework-spfx/](url) implemented MSAL.js to generate token for consuming API/resource secured by Azure AD app. This provided to handle scenarios as explained for cookies disabled or other and provide user meaningful message.
2. Thank you for your suggestion to make another call using MSAL.js, however this time using `ssoSilent` request on MSAL instance in this code snippet `loginForAccessTokenByMSAL()` which is purely based on user login name (in this case same as UPN and it is passed from `this.context.pageContext.user.loginName` (SharePoint context)), can see 2 account values in session Storage
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/9657686/86d57651-e349-4f00-8632-dc8cca61c515)
However still validating all works fine and keep posted

Thank you for help till now.

**Comment by lalimasharda** [comment]
Hey @devanshuGit , are you still facing issues on this?

**Comment by devanshuGit** [comment]
Thank you all @hectormmg @sameerag @jo-arroyo @tnorling @lalimasharda for continued support.

@tnorling comments helped to resolve and get all signed-in user accounts being cached by MSAL in session storage and all the API's like getAllAccounts() and getAccountByUsername() started working. Trick was to make another call using MSAL.js, however this time using ssoSilent request on MSAL instance in this code snippet loginForAccessTokenByMSAL() with code logic to determine whether signed-in user changed based on `this.context.pageContext.user.loginName` and cached account.

Marking helpful comments which helped for others reference:
https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/6258#issuecomment-1681060719
https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/6258#issuecomment-1682852659
https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/6258#issuecomment-1689298747
