### ISSUE TITLE
window.parent is not defined if page in iframe

### ISSUE THREAD

**Issue by imnista** [AzureAD/microsoft-authentication-library-for-js#626]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version 73.0.3683.86 (Official Build) (64-bit)
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 0.2.1
</code></pre>
We are using the msal-angular@0.1.2, and that using the MSAL for js ver 0.2.1, and no update since 7 months ago... [MSAL-Angular](https://www.npmjs.com/package/@azure/msal-angular)

## Current behavior

If we visit the Azure AD B2C login page in an iframe (For example in ***Cypress***, for E2E testing).
After we finish login and redirect to the web site, the MSAL will throw the following exception:

Uncaught TypeError: Cannot read property 'stateMatch' of null

The root cause is in this [function](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/43558e0f5e7309c8400ce387539559a6bb44d0e6/lib/msal-angular/src/msal.service.ts#L93), there a logic neet to load the msal object from the window.parent, but when we using the Cypress or if we visit the page via a iframe, the window.parent is not equal to window

## Expected behavior
Add a condition to check the window.parent

## Minimal reproduction of the problem with instructions

Visit the page by Cypress or iframe, and you will got the error.

**Comment by sameerag** [comment]
@imnista Are you launching the MSAL within an iFrame?

**Comment by imnista** [comment]
> @imnista Are you launching the MSAL within an iFrame?

Yeah, and our project have been remove the MSAL lib, and replace it by oidc-cliend-js (https://github.com/IdentityModel/oidc-client-js)

**Comment by DarylThayil** [comment]
Linked to #504  closing as duplicate

**Comment by DarylThayil** [comment]
@imnista  note this is something currently in progress to support
