### ISSUE TITLE
Redirect loop in the browser

### ISSUE THREAD

**Issue by Staisha-N** [AzureAD/microsoft-authentication-library-for-js#6261]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.34.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.5.4

### Public or Confidential Client?

Public

### Description

After the user successfully goes through the sign in flow provided by Azure AD B2C, they are supposed to be brought to their account page "http://localhost:4200/home". The issue is that the page constantly reloads itself, switching between the localhost:4200/home URL and another URL that looks like this: "http://localhost:4200/#state=eyJp ... ". 

My suspicion is that the error lies with the apiScope used (see Relevant Code Snippets). Before we switched from Azure AD to Azure AD B2C, the apiScope looked like this: 

const apiScope = `api://${process.env['NX_HOST']}/${process.env['NX_AUTH_CLIENT_ID']}/access_as_user`;

This was an exposed scope in our Azure AD. I exposed a scope called access_as_user in the new Azure AD B2C tenant as well, but when I use that for apiScope, I get this error:

"ERROR ServerError: invalid_request: AADB2C90117: The scope 'api://localhost:3000/[B2C tenant client id]/access_as_user' provided in the request is not supported."

So, we have been using this instead (which I believe is causing the redirect loop issue):
const apiScope = `https://example.onmicrosoft.com/${process.env['NX_AUTH_CLIENT_ID']}/access_as_user`;

Any help as to how to fix this redirect loop would be greatly appreciated.

### MSAL Configuration

```javascript
MsalModule.forRoot(
      new PublicClientApplication({
        auth: {
          clientId: process.env['NX_AUTH_CLIENT_ID']!,
          authority: 'https://example.b2clogin.com/example.onmicrosoft.com/B2C_1_SignInSignUpFlow', 
          redirectUri: 'http://localhost:4200/home', 
          knownAuthorities: ["example.b2clogin.com"],
        },
        cache: {
          cacheLocation: 'localStorage',
          storeAuthStateInCookie: false, 
        },
      }),
      {
        interactionType: InteractionType.Redirect,
        authRequest: {
          scopes: [ 
            'openid',
          ], 
        }
      },
      {
        interactionType: InteractionType.Redirect,     
        protectedResourceMap,
      }
    ),
```

### Relevant Code Snippets

```javascript
const apiBaseUrl = `https://${process.env['NX_API_HOST']}`;
const apiScope = `https://example.onmicrosoft.com/${process.env['NX_AUTH_CLIENT_ID']}/access_as_user`;
const apiPaths = [
  'billing/license',
  'billing/activate',
  'billing/resolve',
  'usagerecord',
];
const protectedResourceMap = new Map<string, Array<string>>();
protectedResourceMap.set("https://graph.microsoft.com/v1.0/me", [
  'openid'
]);
apiPaths.forEach((a) =>
  protectedResourceMap.set(`${apiBaseUrl}/${a}`, [apiScope])
);
```

### Identity Provider

Azure B2C Basic Policy

### Source

External (Customer)

**Comment by sameerag** [comment]
@Staisha-N Why do you think the new scope is causing the loop? Do we have any MSAL JS logs or a server trace you can share? Logging instructions can be found [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/logging.md)
