### ISSUE TITLE
how should I pass additional parameters to the ADFS login service via AAD authority

### ISSUE THREAD

**Issue by GHL2770** [AzureAD/microsoft-authentication-library-for-js#6265]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.18.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

Verify the AAD+ADFS login using the official MSAL.JS sample code (https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/react-router-sample ), specifying extraQueryParameters: {"OTP": "123456"}, which is passed to AAD authority, but AAD is not passed to ADFS authority; But when we point authority directly to ADFS authority, the ADFS login service can receive additional parameters specified by extraQueryParameters.
Please confirm whether AAD authentication supports passing additional parameters to ADFS.
If possible, how should I pass additional parameters to the ADFS login service via AAD authority? 

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by sameerag** [comment]
@GHL2770 Are these params to be added to the `/authorize` end point or the `/token` endpoint?

**Comment by GHL2770** [comment]
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/103106974/05e6d8e7-c03c-4c18-a46e-cdcacd44cf14)
https://login.partner.microsoftonline.cn/***********/oauth2/v2.0/authorize
this end point.

**Comment by GHL2770** [comment]
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/103106974/f7d6616d-23be-4a9d-983c-0cf3b2cb3730)
I added an extra parameter to the request for AAD authentication, extraQueryParameters: {"OTP": "123456"}, You can see in the AAD https://login.partner.microsoftonline.cn/ * * * * / oauth2 authentication/v2.0  "OTP=1234568**" are included in the GET request, but the location to have the adfs have no this parameter.

**Comment by sameerag** [comment]
@GHL2770 The AAD->ADFS interface is controlled by the service and not MSAL JS. I can reroute this question to the STS folks and get back.
