### ISSUE TITLE
Can not login in Safari hash_does_not_contain_known_properties

### ISSUE THREAD

**Issue by Yijx** [AzureAD/microsoft-authentication-library-for-js#6266]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.38.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

None

### Public or Confidential Client?

Confidential

### Description

When I click login button,In Chrome everyThing is ok
```
instance.loginPopup()
```
But when i use safari,Iframe can popup but immediately disappear and show error hash_does_not_contain_known_properties

### Error Message

[Error] Unhandled Promise Rejection: BrowserAuthError: hash_does_not_contain_known_properties: Hash does not contain known properites. Please verify that your redirectUri is not changing the hash. For more visit: aka.ms/msaljs/browser-er...
 （匿名函数）
 rejectPromise
 promiseReactionJob

### MSAL Configuration

```javascript
auth: {
        authority: 'https://login.microsoftonline.com/xxxx'
        redirectUri: window.location.origin,
    },
    cache: {
        cacheLocation: BrowserCacheLocation.LocalStorage, // This configures where your cache will be stored
        storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
    },
```

### Relevant Code Snippets

```javascript
no more complex code, login code:

 <Button type={'primary'} onClick={() => {
                    cookie.remove('logoutFlag')
                    instance.loginPopup()
                }}>
                    login
                </Button>
```
```


### Reproduction Steps

1.loginPopup
2.use safari 

### Expected Behavior



Normal login

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Safari

### Regression

_No response_

### Source

External (Customer)

**Comment by sameerag** [comment]
@Yijx This issue looks similar to #3926. Can you please check if the suggestions in the linked issue work for you?

**Comment by izhangzhihao** [comment]
It's still not fixed.

**Comment by sameerag** [comment]
@izhangzhihao Do you see this on other browsers? Also, for safari, can you please share logs: the instructions are [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logging.md).

cc @hectormmg
