### ISSUE TITLE
Changing MSAL BrowseAuthOptions in Angular at Runtime

### ISSUE THREAD

**Issue by rubymoodi** [AzureAD/microsoft-authentication-library-for-js#6267]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.5.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.5.0

### Public or Confidential Client?

Public

### Description

I have a web client with multitenancy. The user can choose a tenant and then log in with it. See please the screenshot under this link: [Login form](https://i.stack.imgur.com/xOsKX.png)

Depending on the chosen tenant I want to configure MSAL [BrowseAuthOptions](https://azuread.github.io/microsoft-authentication-library-for-js/ref/modules/_azure_msal_browser.html#browserauthoptions) without reloading the whole page. Is this possible?

I can't see an appropirate way to do it under this link: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/configuration.md

I tried to create a service for that. However, this doesn't work.

`@Injectable({`
`  providedIn: 'root'`
`})`
`export class AzureService {`
`  constructor(private loginService: LoginService, private msalService: MsalService, @Inject(MSAL_INSTANCE) private authConfig) { }`
`  initialize() {`
`    const auth = this.getConfig();`
`    const msalConfig = {`
`      auth,`
`      cache: {`
`        cacheLocation: BrowserCacheLocation.LocalStorage,`
`        storeAuthStateInCookie: false`
`      },`
`      system: {`
`        loggerOptions: {`
`          loggerCallback: (level: LogLevel, message: string, containsPii: boolean): void => console.log(message),`
`          logLevel: LogLevel.Info,`
`          piiLoggingEnabled: false`
`        }`
`      }`
`    };`
`    const msalInstance = new msal.PublicClientApplication(msalConfig);`
`    return from(msalInstance.initialize());`
`  }`
`  getConfig(): BrowserAuthOptions {`
`    let authConfig = this.loginService.azureAuthOptions;`

`    return {`
`      clientId: authConfig?.clientId,`
`      authority: authConfig?.authority,`
`      redirectUri: `${location.origin}/`

`    };`

`  }`

`}`

### Identity Provider

None

### Source

External (Customer)

**Comment by sameerag** [comment]
@rubimadi Can you try changing the `tenant` in the `request` instead? We support `authority` as a parameter in the request and the `tenant` can be changed there per [request](https://azuread.github.io/microsoft-authentication-library-for-js/ref/modules/_azure_msal_angular.html#msalguardauthrequest).

**Comment by rubymoodi** [comment]
@sameerag Do you mean to pass it to loginRedirect?

I tried it this way, however it doesn't work:

`this.msal.loginRedirect(`
`        {`
`          authority: this.loginService.azureAuthOptions,`
`          account: {tenantId: this.loginService.azureAuthOptions.clientId}`
`        } as RedirectRequest`
`      )`

I'm not sure how to pass the tenant.

On the other side I still have to declare a provider for MSAL_INSTANCE, where I'm obligated to set the auth options. So, what should I set there for the authority an the tenant?

`{`
 `    provide: MSAL_INSTANCE,`
 `     useFactory: MSALInstanceFactory,`
 `   }`

`export function MSALInstanceFactory(): IPublicClientApplication {`
`  return new PublicClientApplication({`
`    auth: {clientId: '', authority: ''},`
`    cache: {`
`      cacheLocation: BrowserCacheLocation.LocalStorage,`
`      storeAuthStateInCookie: false`
`    },`
`    system: {`
`      loggerOptions: {`
`        loggerCallback: (logLevel: LogLevel, message: string): void => {`
`          console.log(message);`
`        },`
`        logLevel: LogLevel.Info,`
`        piiLoggingEnabled: false`
`      }`
`    }`
`  });`
`}``

**Comment by sameerag** [comment]
@rubimadi 
A sample authority in MSAL JS looks like this:
```
authority: "login.microsoftonline.com/TENANT"
```

This format is supported for both `configuration` and `request`. Can you try this in `loginRedirect` and let us know what happens?

**Comment by rubymoodi** [comment]
I have to clarify something. A tenant in our terms means a separat customer with its separat AAD, that is synchronised with its on-premise AD. So, I have to set the authority URL (authority) and the clientId for each of our customer (tenants), if it gets selected from the dropdown list in the [login form](https://i.stack.imgur.com/xOsKX.png).

This is how I configure MSAL. Please note, how I'm setting the auth property to null. Because at the initialization I don't know yet, which customer the user is gonna choose.

```typescript
export function MSALInstanceFactory(): IPublicClientApplication {
  return new PublicClientApplication({
    auth: null,
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: false
    },
    system: {
      loggerOptions: {
        loggerCallback: (logLevel: LogLevel, message: string): void => {
          switch (logLevel) {
            case LogLevel.Error:
                console.error(message);
                return;
            case LogLevel.Info:
                console.info(message);
                return;
            case LogLevel.Verbose:
                console.debug(message);
                return;
            case LogLevel.Warning:
                console.warn(message);
                return;
        }
        },
        logLevel: LogLevel.Verbose,
        piiLoggingEnabled: false
      }
    }
  });
}

@NgModule({
  imports: [MsalModule],
  providers: [
    {
      provide: APP_INITIALIZER,
      useFactory: (authService: MsalService) => {
        return (): void => {
          authService.getLogger().verbose('MsalRedirectService activated');
          authService
            .initialize()
            .pipe(concatMap(() => authService.handleRedirectObservable()))
            .subscribe();
        };
      },
      deps: [MsalService],
      multi: true
    },
    {
      provide: MSAL_INSTANCE,
      useFactory: MSALInstanceFactory,
    },
    {
      provide: HTTP_INTERCEPTORS,
      useClass: MsalInterceptor,
      multi: true
    },
    {
      provide: MSAL_GUARD_CONFIG,
      useFactory: (): MsalGuardConfiguration => {
        return {
          interactionType: InteractionType.Redirect,
          authRequest: {
            scopes: ['user.read']
          }
        };
      }
    },
    {
      provide: MSAL_INTERCEPTOR_CONFIG,
      useFactory: (): MsalInterceptorConfiguration => {
        const protectedResourceMap = new Map<string, Array<string>>();
        protectedResourceMap.set('https://graph.microsoft.com/v1.0/me', ['user.read']);

        return {
          interactionType: InteractionType.Redirect,
          protectedResourceMap
        };
      }
    },
    MsalService,
    MsalGuard,
    MsalBroadcastService
  ]
})
export class AzureModule { }
```

When the user chooses a customer, I set the auth property like this:
```typescript
constructor(private msal: MsalService) {
}

onClientChanged(e) {
    let client = e.value;

    return this.loginService.getAzureAuthOptions(client)
    .map(options => {
      this.msal.instance = new PublicClientApplication({
        auth: {
          clientId: options.clientId,
          authority: options.authority,
          redirectUri: `${location.origin}/`
        }
      });
    });
}	
```

When the user press the login button, I call:
```typescript
this.msal.loginRedirect({ ...this.msalGuardConfig.authRequest } as RedirectRequest)
```

Of course, this approach doesn't work. That's why I'm seeking for help. It would be helpful, if you could show me, how to rewrite this code to make it works.

**Comment by sameerag** [comment]
@hectormmg As discussed please check if this is due to multi-tenancy and if it is fixed with your PR.

**Comment by hectormmg** [comment]
@rubimadi unfortunately acquiring tokens for multiple tenants with the same account isn't supported yet. Currently, MSAL will keep requesting tokens from the tenant that the first request uses, since it gets "linked" to the account locally and used in future requests. However, we're working on this feature and will update this issue when it is released.  Thanks!

**Comment by tnorling** [comment]
Closing in favor of #3687 which tracks the multi-tenant feature request
