### ISSUE TITLE
Device Code Flow Support

### ISSUE THREAD

**Issue by mm-gmbd** [AzureAD/microsoft-authentication-library-for-js#627]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX
- [x] Headless (i.e. pure Node.js, no browser)

## Library version

<pre><code>
Library version: 0.2.4

## Current behavior
I'd like to implement the [Device Code Flow](https://oauth.net/2/grant-types/device-code/) using MSAL for JS. 

There appears to be [support for this](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Device-Code-Flow) in MSAL for .NET by utilizing `PublicClientApplication`. 

However, the JS library only provides `UserClientApplication`, and no support that I've been able to find for the Device Code Flow.

## Expected behavior
Implemented, it would look like the same as the support in MSAL for .NET, or like it did in [v1.0 ADAL](https://docs.microsoft.com/en-us/javascript/api/adal-node/authenticationcontext?view=azure-node-latest#acquiretokenwithdevicecode-string--string--usercodeinfo--acquiretokencallback-).

## Minimal reproduction of the problem with instructions

</code></pre>

**Comment by navyasric** [comment]
@mm-gmbd Thank you for the feedback. The MSAL.js library is designed for client side JS web apps running in a browser such as single page apps and therefore supports only the implicit flow.
The device code flow is for authentication in public clients apps which do not have a browser interface. This is not a feature we plan to add to the MSAL JS library. 

We do have the [ADAL Node.js](https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/blob/dev/sample/device-code-sample.js) library which offers this flow. We have plans of an MSAL Node.js library for later this year.

**Comment by mm-gmbd** [comment]
Thanks for the feedback @navyasric. I'll be waiting eagerly for the Node.js library :smile:

**Comment by ElectricLlama** [comment]
"client side JS web apps running in a browser such as single page apps". These do not need a web server to run. Right now I have a SPA which calls Azure API's and the only reason it needs a web server is so that the app registration callback URI works. I'd happily run it without a web server but then I'd need to get device code working (and it sounds like it doesn't work with MSAL.js)

**Comment by sameerag** [comment]
Yes. please track [msal-node](https://github.com/AzureAD/microsoft-authentication-library-for-js/projects/4) which will have device-code support.
