### ISSUE TITLE
Azure AD logoutredirect doesn't revoke access token

### ISSUE THREAD

**Issue by sammyRi542** [AzureAD/microsoft-authentication-library-for-js#6277]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.28.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.4

### Public or Confidential Client?

Public

### Description

After I logout of my React SPA using msalInstance.logoutRedirect() method, the access token for the terminated session is not revoked. I am still able to access my backend APIs using the same.

### MSAL Configuration

```javascript
const msalConfig = {
  auth: {
    clientId: AZURE_ACTIVE_DIRECTORY_CLIENT_ID,
    authority: `https://login.microsoftonline.com/${AZURE_ACTIVE_DIRECTORY_TENANT_ID}`,
    redirectUri: AZURE_ACTIVE_DIRECTORY_REDIRECT_URI,
  },
};
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by hectormmg** [comment]
@sammyRi542 MSAL logout APIs don't invalidate access tokens, they just delete them from the cache and send an end session request to the service. 

The access tokens in question are Bearer tokens, which means they can be used up until the point of expiration by any party that holds them, as documented [here](https://learn.microsoft.com/en-us/azure/active-directory/develop/configurable-token-lifetimes#access-tokens).

While there's no way to directly invalidate access tokens, please look into [Continuous Access Evaliation (CAE)](https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/concept-continuous-access-evaluation) if you're interested in giving your resource the ability to reject tokens upon revocation in certain scenarios.

**Comment by sammyRi542** [comment]
@hectormmg Can backend check if a user session is active or not using the access token after logging out from client side?

**Comment by hectormmg** [comment]
@sammyRi542 by backend do you mean the resource server? I believe access tokens will be accepted as long as they are valid, what CAE does is determine whether the session should be terminated under certain conditions. Whether a session with a server is alive or not determines whether the browser keeps certain cookies that make acquiring tokens easier, not whether tokens issued when the session was valid are themselves valid or not.
