### ISSUE TITLE
msal react app signs in AD FS using Authorization Code Flow w/ PKCE

### ISSUE THREAD

**Issue by hfknight** [AzureAD/microsoft-authentication-library-for-js#6281]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.32.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.5.1

### Public or Confidential Client?

Public

### Description

I'm trying to authorize a react SPA app from AD FS server (2019) directly but gets an error

{
    "error": "invalid_client",
    "error_description": "MSIS9622: Client authentication failed. Please verify the credential provided for client authentication is valid."
}

and the error from the ADFS server log is

Exception details: 
Microsoft.IdentityServer.Web.Protocols.OAuth.Exceptions.OAuthClientCredentialAuthenticationException: MSIS9267: No Client credentials found in the request. Client 'xxxxxxxxxxx' is configured as a confidential client.

is it because the client is set to a confidential client? 

### MSAL Configuration

```javascript
auth: {
    clientId: <client-id>,
    authority: `<adfs-server.domain.name>/adfs/`,
    knownAuthorities: [<adfs-server.domain.name>],
    redirectUri: '/callback.html',
    postLogoutRedirectUri: '/signin',
    navigateToLoginRequestUrl: false
  },
  cache: {
    cacheLocation: 'sessionStorage'
    storeAuthStateInCookie: false
  }
```

### Identity Provider

ADFS

### Source

External (Customer)

**Comment by hectormmg** [comment]
@hfknight which client or configuration do you mean when you say "the client is set to confidential client"? Single-page applications, like the ones made with React, are considered Public Client applications given their inability to protect client secrets.

**Comment by hfknight** [comment]
> @hfknight which client or configuration do you mean when you say "the client is set to confidential client"? Single-page applications, like the ones made with React, are considered Public Client applications given their inability to protect client secrets.

Thanks for the reply, I meant the error from ADFS server, "MSIS9267: No Client credentials found in the request. Client 'xxxxxxxxxxx' is configured as a confidential client." does that mean the client configuration is incorrect? the client need be configured as a Public client?

**Comment by hectormmg** [comment]
@hfknight that's right, if you're requesting tokens from a SPA the client needs to be public

**Comment by hfknight** [comment]
> @hfknight that's right, if you're requesting tokens from a SPA the client needs to be public

Thanks, we changed the client to be public and the issue is solved.
