### ISSUE TITLE
The documentation for the type BrowserSystemOptions is not available

### ISSUE THREAD

**Issue by dirthsj** [AzureAD/microsoft-authentication-library-for-js#6283]
### Core Library

MSAL.js (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Public or Confidential Client?

Public

### Documentation Location

https://azuread.github.io/microsoft-authentication-library-for-js/ref/modules/_azure_msal_browser.html#browsersystemoptions

### Description

Other types on this page have useful descriptions of their contents. `BrowserSystemOptions` does not.

**Comment by hectormmg** [comment]
@dirthsj for some reason it seems typedoc isn't picking up the attribute descriptions, I'll look into it. Thanks for pointing this out!

**Comment by dirthsj** [comment]
This comment is to prevent the bot from closing the issue automatically.

**Comment by tnorling** [comment]
@dirthsj Can you take another look? https://azuread.github.io/microsoft-authentication-library-for-js/ref/types/_azure_msal_browser.BrowserSystemOptions.html

**Comment by dirthsj** [comment]
Looks good to me! Thanks for quick turn around.
