### ISSUE TITLE
How to clear access and refresh token without logout

### ISSUE THREAD

**Issue by marcelloraffaele** [AzureAD/microsoft-authentication-library-for-js#6288]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.38.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

Is there a way to clear access and refresh token without logout?

I tried to [skipping the server logout](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md#skipping-the-server-sign-out) but after it when i call again acquireTokenSilent it goes in error maybe because need again login, but if i make login i need to refresh the page ( cannot use popup).

### MSAL Configuration

```javascript
const msalConfig = {
           auth: {
             clientId: "xxxxxx-yyyyyyyyy-xxxxxxx-yyyyyyyy",
             authority: "https://example.myadfs.it/adfs",
             knownAuthorities: ["example.myadfs.it"],
           },
           cache: {
             cacheLocation: "sessionStorage",
           },
           system: {
             loggerOptions: {
               loggerCallback: (level, message, containsPii) => {
                 if (containsPii) {
                   return;
                 }
                 switch (level) {
                   case msal.LogLevel.Error:
                     console.error(message);
                     return;
                   case msal.LogLevel.Info:
                     console.info(message);
                     return;
                   case msal.LogLevel.Verbose:
                     console.debug(message);
                     return;
                   case msal.LogLevel.Warning:
                     console.warn(message);
                     return;
                 }
               },
             },
           },
         };
```

### Relevant Code Snippets

```javascript
function signOutLight() {           
           msalClient.logoutRedirect({
              onRedirectNavigate: (url) => {
                  // Return false if you would like to stop navigation after local logout
                  return false;
              }
          });
         }
```

### Identity Provider

ADFS

### Source

External (Customer)

**Comment by hectormmg** [comment]
@marcelloraffaele there's no way to do this in MSAL without using a logout API. And yes, acquireTokenSilent will throw an error if there are no tokens in the cache, that is expected behavior. Could you give a little more context on your scenario? You could manually clear your browser storage (not recommended) but then you'd still have an issue calling acquireTokenSilent afterwards.
