### ISSUE TITLE
Msal for angular has enormous bundle size

### ISSUE THREAD

**Issue by markostojkov** [AzureAD/microsoft-authentication-library-for-js#6290]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

13.2.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.5.9

### Public or Confidential Client?

Public

### Description

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/50018746/1a7b479e-69a7-4a6a-beaf-06516c9562db)

The size of the msal bundle is 30% of my whole app (350KB+) 

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@markostojkov We have been working on reducing the bundle size for the next version of MSAL. Can you please try upgrading to the beta versions of MSAL Browser and MSAL Angular and see if that helps?

**Comment by markostojkov** [comment]
@jo-arroyo You are very generous with your time, thanks for the quick response.

I installed 
    "@azure/msal-angular": "^3.0.0-beta.1",
    "@azure/msal-browser": "^3.0.0-beta.1",
Cleaned up my node_modules and reinstalled all
Build with source maps and I still get 320KB
Is there anything else that I am supposed to do?

Here is a tree of the @azure folder in node modules https://pastebin.com/QH2Lh9aK
Here is my sourcemap 
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/50018746/7a7f6728-3814-4192-b500-3133d046b4bc)

**Comment by jo-arroyo** [comment]
@markostojkov Thank you for providing the breakdown. We have made changes to the library in this version that impacted our ability to reduce the size, and unfortunately, this is the extent of the reduction we are able to make. We are aware that this is a frustration to our customers, but we do not have further work prioritized in this regard at this time.

**Comment by markostojkov** [comment]
@jo-arroyo I am no expert in angular, I am curious whether I am allowed as person not belonging to your organization to make a pull request and try reducing the size?

**Comment by jo-arroyo** [comment]
@markostojkov We welcome your contributions, and would be more than happy to look at a PR. Please see [this guide](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/contributing.md) on how to get set up.

Closing this issue as there is no further guidance. We look forward to seeing your PR.
