### ISSUE TITLE
How should I automate Azure AD login in my automated integration test? 

### ISSUE THREAD

**Issue by tcb1978** [AzureAD/microsoft-authentication-library-for-js#6293]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.38.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

none

### Public or Confidential Client?

Confidential

### Description

I am testing an app that relies on MSAL React! Our app uses UnauthenticatedTemplate and AuthenticatedTemplate components -- if the Unauthenticated component loads, our app immediately redirects to the logon.microsoft.com/tenantID URL. This redirect is what we are trying to prevent by having our e2e test first establish a valid session, and then after that, our e2e test navigates to our app hosted on localhost (and that app should detect we already have a session, and thus not redirect).

My team came to the conclusion today that client_credentials isn't the correct grant type for our use case. It's not similar enough to a user logging in. So we're exploring using a test user account credential with the password grant_type instead, now.

We're trying to get something like the below code working. The main problem we're having, is after getting the response back, how should we save the token into sessionStorage correctly? Saving to id_token as below is wrong - msal-react seems to save several token key names, and I am not sure how to generate that list of token keys properly

Cypress.Commands.add("aadAuthenticate", window => {
    const clientId = "my-client-id";
    const tenantId = "my-tenant-id";
    const clientSecret = "my-secret";

    cy.request({
        method: "POST",
        url: `https://login.microsoftonline.com/${tenantId}/oauth2/v2.0/token`,
        header: {
            "cache-control": "no-cache",
            "Content-Type": "application/x-www-form-urlencoded"
        },
        form: true,
        body: {
            client_id: clientId,
            client_secret: clientSecret,
            username: "testaccount@test.com",
            password: "test-pw",
            grant_type: "password",
            scope: "api://my-app.com/app.Read openid profile"
        }
    }).then(response => {
        const token = response.body.access_token;
        window.sessionStorage.setItem("id_token", token);
    });
});

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by jo-arroyo** [comment]
@tcb1978 I see that you have copied a comment from #4519 as your issue. Have you read the rest of the guidance provided on that issue, as well as looked into our [testing doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/testing.md) that details the `loadExternalTokens` API and [testing sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-browser-samples/TestingSample)?
