### ISSUE TITLE
Token renewal causes infinite loop

### ISSUE THREAD

**Issue by austindyoung** [AzureAD/microsoft-authentication-library-for-js#63]
Token renewal in an Angular app causes an infinite loop in which:

1. acquireTokenSilent([clientId]) causes iframe reassigment
2. Iframe src assignment causes app to get reconstructed
3. Hash "callback" is for access token (not id token)
2. acquireTokenSilent([clientId]) causes iframe reassigment

**Comment by DibranMulder** [comment]
I have experienced this issue aswell, why aren't they fixing this?! This is a major deal breaker.

**Comment by rohitnarula7176** [comment]
@DibranMulder Can you please provide a code snippet that can help us to reproduce the issue.

**Comment by rohitnarula7176** [comment]
Closing this issue. Fixed in dev.

**Comment by DibranMulder** [comment]
Great job, I tried to provide a sample but I didn't manage to reproduce the bug in my sample. I'll test with dev if its solved and let you know!
