### ISSUE TITLE
msal-common error while using msal-node (AccessTokenEntity)

### ISSUE THREAD

**Issue by ludovicoloreti** [AzureAD/microsoft-authentication-library-for-js#6307]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

2.0.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Confidential

### Description

Trying to use it in the simpliest way possible, just doing the import 
```
import msal from "@azure/msal-node";
const { ConfidentialClientApplication } = msal;
```
And the error occurs, but the problem is, the error occurs in a sub-dependency. 

### Error Message

import { StringUtils, AccountEntity, CacheManager, IdTokenEntity, AccessTokenEntity, RefreshTokenEntity, AppMetadataEntity } from '@azure/msal-common';
                                                                  ^^^^^^^^^^^^^^^^^
SyntaxError: Named export 'AccessTokenEntity' not found. The requested module '@azure/msal-common' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@azure/msal-common';
const { StringUtils, AccountEntity, CacheManager, IdTokenEntity, AccessTokenEntity, RefreshTokenEntity, AppMetadataEntity } = pkg;

### MSAL Configuration

```javascript
{
  auth: {
    clientId: "_",
    authority: `https://login.microsoftonline.com/___`,
    clientSecret: "_",
  },
}
```

### Relevant Code Snippets

```javascript
import msal from "@azure/msal-node";
const { ConfidentialClientApplication } = msal;

const config = {
  auth: {
    clientId: "_",
    authority: `https://login.microsoftonline.com/___`,
    clientSecret: "_",
  },
  },
};

const cca = new ConfidentialClientApplication(config);
```

### Reproduction Steps

1. `pnpm i @azure/msal-node`
2. Add the code snippet I gave you
3. Run it

### Expected Behavior

it should not give me any errors because it works with curl.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Source

External (Customer)

**Comment by ludovicoloreti** [comment]
I can confirm that with `"@azure/msal-node": "^1.18.1"` the error disappeared.
So basically only with version 2.0.0

**Comment by atsjo** [comment]
Can confirm same problem and error message upgrading to latest msal-node in my firebase-functions...
