### ISSUE TITLE
PublicClientApplication.addEventCallback has incorrect callback type

### ISSUE THREAD

**Issue by bagoette** [AzureAD/microsoft-authentication-library-for-js#6309]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.0.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.0.0

### Public or Confidential Client?

Public

### Description

The type for for the `callback` parameter in `PublicClientApplication.addEventCallback` used to be typed as `EventCallbackFunction` now it is typed as `Function`

### MSAL Configuration

```javascript
Not a configuration issue
```

### Relevant Code Snippets

```javascript
msalInstance.addEventCallback((event: EventMessage) => {
  if (event.eventType === EventType.LOGIN_SUCCESS && event.payload) {
    console.log('login success');

    const account = (event.payload as AuthenticationResult).account;
    msalInstance.setActiveAccount(account);
  }
});
```

### Reproduction Steps

1. Update to v3.0.0
2. Try to `addEventCallback` on the `PublicClientApplication`
3. Typescript no longer has parameter information for the `EventMessage`

### Expected Behavior

Typescript should have the correct type for the callback parameters

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Regression

@azure/msal-browser 2.38.0

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@bagoette Can you update to the latest 1.x version of MSAL React and 2.x version of MSAL Browser and let us know if you still see this issue?

**Comment by bagoette** [comment]
Do you mean to downgrade both packages? I already went back down to `msal-browser@2.38.0` and `msal-react@1.5.9` (which is what I was on previously) the issue is **not** there.

**Comment by jo-arroyo** [comment]
@bagoette Apologies, I misread the versions. We have recently had an error in our release process, please wait until the latest patch version for MSAL Browser v3 to be released before upgrading again.
