### ISSUE TITLE
How about creating an example that actually works?

### ISSUE THREAD

**Issue by tabinnorway** [AzureAD/microsoft-authentication-library-for-js#631]
git clone
npm install
ng serve

App comes up fine. Press login. AAD login screen pops up. Log in. Move around the app. Each "tab" presents the login screen again.

[x] All browsers
[x] Angular version 7.x installed, but using local, which is 1.7.x

**Comment by anubi** [comment]
It works for me fine. If you are being presented with a login on each tab, this indicates an authentication failure. Check your browser's console for error output. It's possible your local environment is setup incorrectly, your browser is incompatible, failing HTTP requests via network issues, or something weird.

**Comment by sameerag** [comment]
@tabinnorway I am closing this issue. Please send us complete repro and stacktrace in case you haven't been able to get this to work. Please also note that there is angular wrapper support missing for the latest msal release and  please watch our [roadmap](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#roadmap) for updates on this.
