### ISSUE TITLE
Why doesn't the authentication return the refreshToken?

### ISSUE THREAD

**Issue by TheNatas** [AzureAD/microsoft-authentication-library-for-js#6314]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.38.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.5.9

### Public or Confidential Client?

Public

### Description

I'm trying to create an integration between my application and Outlook. I decided to follow the On-Behalf-Of flow, for structure and security reasons. I'm still trying to use this library for authentication to get the token information and save it to a database, but I've checked the AuthenticationResult type and it seems to not include the refreshToken. Why is that?

### MSAL Configuration

```javascript
{
  auth: {
    clientId: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
  }
}
```

### Relevant Code Snippets

```javascript
instance.loginPopup({
      scopes: ['Calendars.Read', 'Calendars.ReadWrite'],
      redirectUri: window.location.origin + '/integracoes'
    }).then((values) => {
      console.log(values); // doesn't include refreshToken
      dispatch(updateUserIntegration({ userId: InfoUsuario.get('cdUsuario'), integrationId, value: true }));
    })
```

### Identity Provider

None

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@TheNatas We intentionally do not expose the refresh token for security reasons. Please see this FAQ [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/faq.md#how-do-i-get-the-refresh-token). Can you confirm if you are using MSAL React or MSAL Node? The OBO flow is only for MSAL Node.

**Comment by TheNatas** [comment]
@jo-arroyo I'm using MSAL React just for the initial authentication, so then I want to send the token information (access, refresh, expiresOn) to my Java backend where I'll handle the token refreshing and API calls. 

I'm in a hurry right now, so I'm currently making the authentication without using the library, but it would be easier if I had access to the refreshToken through the library. 

I saw this question <a href="https://learn.microsoft.com/en-us/answers/questions/702519/endpoint-url-for-offline-access">here</a> which says something about an <code>offline_access</code> permission for having the refreshToken, but it doesn't seem to work. Is it an old feature?

**Comment by jo-arroyo** [comment]
@TheNatas The `offline_access` scope is a default scope sent in the request so that MSAL receives and is able to use the refresh token returned. Again, that MSAL does not expose the refresh token is by design. 
If you would like a refresh token for your backend, you could consider using MSAL Node or MSAL for Java.

**Comment by TheNatas** [comment]
I see. I'm gonna try the MSAL for Java then. I was able to get it by sending the authentication requests manually, but I'll sure try to improve it in the future by using the back end API.

Thanks for the explanation.
