### ISSUE TITLE
using msal-browser runtime error

### ISSUE THREAD

**Issue by NickLWMP** [AzureAD/microsoft-authentication-library-for-js#6317]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2

### Public or Confidential Client?

Public

### Description

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/141171859/993985c8-5a8c-4c35-a822-ac7d002e355f)

### MSAL Configuration

```javascript
{}
```

### Relevant Code Snippets

```javascript
import {PublicClientApplication} from "@azure/msal-browser";

export default function App({ Component, pageProps }: AppProps) {
  const msalInstance = new PublicClientApplication(msalConfig);

// importing PublicClientApplication from msal-browser is all it takes to reproduce
```

### Reproduction Steps

1

### Expected Behavior

1

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by hectormmg** [comment]
@NickLWMP could you please share the exact versions of both msal-browser and msal-angular? Thanks.

**Comment by Pespiri** [comment]
I'm having the same issue on React v18 (18.2.0)

```json
    "@azure/msal-browser": "^3.0.0",
    "@azure/msal-react": "^2.0.0",
```

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/32248439/d2124a74-d0a1-4eff-8862-38c25edf41a3)

**Comment by NickLWMP** [comment]
@hectormmg 
    
    "@azure/msal-browser": "^3.0.0",
    "@azure/msal-react": "^2.0.0",`
    "react": "18.2.0",

It's a react project,  not angular.

**Comment by Mimetis** [comment]
Same error here.

The problem is coming from `msal-common` package.
`package.json` is missing the property `"type"="module"`

``` json

  "sideEffects": false,
  "module": "./dist/index.js",
  "types": "./dist/index.d.ts",
  **"type": "module",**
  "exports": {
    ".": {
      "types": "./dist/index.d.ts",
      "module": "./dist/index.js",
      "import": "./dist/index.js",
      "require": "./dist/index.cjs.js",
      "default": "./dist/index.js"
    },
    "./package.json": "./package.json"
  },
```

A temporary fix is to go in `/node_modules/@azure/msal-common/package.json` and add manually the property `"type": "module"`

**Comment by NickLWMP** [comment]
> Same error here.
> 
> The problem is coming from `msal-common` package. `package.json` is missing the property `"type"="module"`
> 
> ```json
>   "sideEffects": false,
>   "module": "./dist/index.js",
>   "types": "./dist/index.d.ts",
>   **"type": "module",**
>   "exports": {
>     ".": {
>       "types": "./dist/index.d.ts",
>       "module": "./dist/index.js",
>       "import": "./dist/index.js",
>       "require": "./dist/index.cjs.js",
>       "default": "./dist/index.js"
>     },
>     "./package.json": "./package.json"
>   },
> ```
> 
> A temporary fix is to go in `/node_modules/@azure/msal-common/package.json` and add manually the property `"type": "module"`

This workaround worked for me. Thank you!
