### ISSUE TITLE
Unicode issue with username

### ISSUE THREAD

**Issue by mahoekst** [AzureAD/microsoft-authentication-library-for-js#632]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 0.2.3

## Current behavior

When logging in with a user with a display name like Björn Ironside the MSAL object doesn't populate the username correctly

## Expected behavior

Have the username properly contain the unicode display name

## Minimal reproduction of the problem with instructions

Create a user with display name which contains unicode. login with the SPA quickstart sample.

</code></pre>

**Comment by navyasric** [comment]
This issue is same as existing report of the issue https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/596. Please track above issue and the PR: https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/549 that could fix this. Closing.
