### ISSUE TITLE
MSAL Angular v0, issue about prompt=select_account

### ISSUE THREAD

**Issue by SamYeungHL** [AzureAD/microsoft-authentication-library-for-js#6327]
### Core Library

MSAL.js (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Public or Confidential Client?

Public

### Description

I am applying MSAL Angular v0 for my project of Angular 5. I tried to pass the value of login_hint to the parameter of extraQueryParameters in order to skip the account prompt for users. However, the "prompt=select_account" make the login page ignore the login_hint value. I can't find the way to get rid of "prompt=select_account".

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@SamYeungHL Unfortunately, MSAL Angular v0 is out of support, and we are unable to help you debug this issue. We highly recommend you upgrade to a modern version of Angular to use MSAL Angular v2, and the upcoming MSAL Angular v3.
Please see our MSAL Angular version support [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-angular#version-support).

**Comment by SamYeungHL** [comment]
@jo-arroyo thanks for your reply, but the upgrade of angular is not an option because the cost is unaffordable to us. I just wonder it might not be a bug and there might be a right way to do it with the version of v0?

**Comment by tnorling** [comment]
You can try passing in the `promptValue` parameter with your desired prompt value. As mentioned v0 is not supported and uses a less secure auth flow, we highly recommend upgrading as soon as you are able.

**Comment by SamYeungHL** [comment]
@tnorling trust me. I've already tried hundred times to change the prompt value such as "prompt=none" or "prompt=", but whatever I add to the extraQueryParameters with the key of prompt must cause the login page showing error about Duplicate Query Parameters

**Comment by tnorling** [comment]
Don't add it to the extraQueryParameters. There is a separate `promptValue` request param.

```javascript
const request = {
  promptValue: "none",
  extraQueryParameters: {
    yourextraParams
  };
```

If that doesn't work, I can't stress this enough: v0 was a pre-release library which is potentially buggy and/or insecure and is not supported. If you are insistent on using it you will likely need to dig into the source, debug it yourself and roll your own fix.

**Comment by SamYeungHL** [comment]
@tnorling thanks for being here to help. Your approach seems like compatible with newer version only.
Here is the definition of those login methods found in the v0 library.
```
loginRedirect(consentScopes?: string[], extraQueryParameters?: string): void;
loginPopup(consentScopes?: string[], extraQueryParameters?: string): Promise<any>;
```


As we can see that they take two parameters, string array and string, and I have to call the method like this.
`this.msalService.loginRedirect(['user.read'], 'login_hint=abc@abc.com&mkt=zh-HK');`
you are right, editing the library source code might be the only choice.
