### ISSUE TITLE
login not working on iPhone 12 mini (iOS 16.5.1) window.crypto.subtle.digest is undefined

### ISSUE THREAD

**Issue by h3nn1-ship-it** [AzureAD/microsoft-authentication-library-for-js#6328]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.38.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.0.0

### Public or Confidential Client?

Public

### Description

I implemented a login flow via `msal-browser` and `msal-react` which works fine on Desktop and Android.
On an iPhone, I receive an error when clicking on the login button.
I use:

- "react": "^18.2.0",
- "next": "^13.4.12",
- "typescript": "^5.1.6"

### Error Message

BrowserAuthError: pkce_not_created: The PKCE code challenge and verifier could not be generated. Detail:TypeError: undefined is not an object (evaluating 'window.crypto.subtle.digest')

### MSAL Configuration

```javascript
auth: {
        clientId: process.env.NEXT_PUBLIC_CLIENT_ID as string,
        authority: `https://login.microsoftonline.com/${process.env.NEXT_PUBLIC_AZURE_AD_TENANT_ID}`,
        redirectUri: process.env.NEXT_PUBLIC_REDIRECT_URI,
        postLogoutRedirectUri: process.env.NEXT_PUBLIC_REDIRECT_URI,
    },
```

### Relevant Code Snippets

```javascript
async function handleLogin(msalInstance: IPublicClientApplication) {
        try {
            return await msalInstance.acquireTokenRedirect({
                scopes: ['User.Read', 'email', 'mail.send'],
                account: account || undefined,
                redirectStartPage: process.env.NEXT_PUBLIC_REDIRECT_URI,
            });
        } catch (e) {
            setLoginError(e as Error);
        }
    }
```

### Reproduction Steps

Setup up
Run on iPhone
Try to login

### Expected Behavior

Login should work without any errors

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Safari

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@henrikhertler Can you confirm the versions of MSAL React and MSAL Browser that are being used? The latest MSAL React 2.0.1 should be used with MSAL Browser 3.0.1, whereas MSAL React 1.5.10 is used with MSAL Browser 2.38.1?

**Comment by h3nn1-ship-it** [comment]
Hey @jo-arroyo 
thanks for your reply.

I have tested the versions you suggested:
```
"@azure/msal-browser": "^2.38.1",
"@azure/msal-react": "^1.5.10",
```
and 
```
"@azure/msal-browser": "^3.0.1",
"@azure/msal-react": "^2.0.1",
```

but I receive the same error.

**Comment by tnorling** [comment]
Are you hosting your app over https? I believe the crypto APIs are only available in secure contexts.

**Comment by h3nn1-ship-it** [comment]
> Are you hosting your app over https? I believe the crypto APIs are only available in secure contexts.

@tnorling yes, the app is hosted and reachable via https.

**Comment by tnorling** [comment]
I'm not sure what else it could be, I'm not terribly familiar with iOS - MDN indicates these APIs should be available in [version 7 onwards](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest). You may need to do some research around why these APIs aren't available in your environment. Worst case you can include polyfills, such as [MSR crypto](https://github.com/microsoft/MSR-JavaScript-Crypto)

**Comment by h3nn1-ship-it** [comment]
@tnorling thanks for your input. I will have a deeper look and let you know what I find.
