### ISSUE TITLE
How do you unit test this library?

### ISSUE THREAD

**Issue by fristys** [AzureAD/microsoft-authentication-library-for-js#633]
## I'm submitting a...

<pre><code>
[x] Documentation issue or request
</code></pre>

We're interested in using MSAL, however, all of our development is test driven. Is it possible, and/or are there any examples of unit testing the library (in conjunction with Angular in particular)?

**Comment by navyasric** [comment]
Please take a look at [these steps to run the unit tests](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Build-and-run-tests) for the library and let us know if that helps you.

**Comment by fristys** [comment]
I meant, how do you unit test your own services and such implementing the library in an Angular application, not how to build and test the actual library.

**Comment by sameerag** [comment]
@fristys  We have existing UT cases and end-to-end cases for angular, may be the end-to-end cases would help you in this context. Having said that we started a comprehensive test suite addition to our core library code as we move forward with our [API changes in msal core](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#roadmap). 

Can you give us an example of what exactly are you looking for? We might consider that when we start working on our angular release in future.

**Comment by fristys** [comment]
For example, imagine I have a service that has a method that silently acquires a token, performs `GET https://graph.microsoft.com/beta/me`, and returns the request response. How do I test that?

**Comment by sameerag** [comment]
@fristys  What you mentioned is an end-to-end case.
Since the response if returned to you, you can validate the tokens and other parameters of the response at your end.

We are also actively filling in our Unit tests and end-to-end tests in our code and we will be soon enhancing the end-2-end testing to match most use cases. The use cases you are referring to will be covered in those.
