### ISSUE TITLE
The scope provided in the request is not supported

### ISSUE THREAD

**Issue by eluchsinger** [AzureAD/microsoft-authentication-library-for-js#6340]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.0.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.1

### Public or Confidential Client?

Public

### Description

After updating to Angular 15 and MSAL 3.0.1, we are getting an error when trying to authenticate.

Since nothing in this regard is documented in the Upgrade Guide, I would not expect any change to be required in this regard or any deprecations.

### Error Message

```
invalid_request: AADB2C90012: The scope '<our-scopes> openid profile offline_access' provided in request is not supported.
```

### MSAL Configuration

```javascript
new PublicClientApplication({
    auth: {
      clientId: environment.AzureClientId,
      authority: b2cPolicies.authorities.signUpSignIn.authority,
      redirectUri: "/",
      postLogoutRedirectUri: "/",
      knownAuthorities: [`${environment.AzureB2CName}.b2clogin.com`],
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE, // set to true for IE 11
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Warning,
        piiLoggingEnabled: false,
      },
    },
  });
```

### Relevant Code Snippets

```javascript
-
```

### Reproduction Steps

1. Start the login flow
2. The page blanks out and this error appears in the console

### Expected Behavior

Nothing should error out, because there are no deprecations in the [Upgrade Guide](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-v3-upgrade-guide.md)

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer, Other

### Regression

@azure/msal-browser 2.x

### Source

External (Customer)

**Comment by Harbinder-web** [comment]
Same issue in msal react following for solution

**Comment by pkgwarek** [comment]
I am experiencing the same issue in angular app

**Comment by TamerHussien** [comment]
same issue with Angular b2c login and Angular standalone samples as well

core.mjs:10920 ERROR ServerError: invalid_request: AADB2C90012: The scope 'https://fabrikamb2c.onmicrosoft.com/helloapi/demo.read openid profile offline_access' provided in request is not supported.
Correlation ID: 83ea568a-33a3-4d65-82b9-4593d7f34d7c

**Comment by mgermino** [comment]
It appears the login request URL is missing v2.0. At least for me, before the upgrade it was oauth2/v2.0/authorize. After the upgrade it is now attempting to redirect me to oauth2/authorize.

**Comment by mgermino** [comment]
Specifying 3.0.0-beta.1 in the package.json doesn't result in this issue and is working fine for me so far.

**Comment by TamerHussien** [comment]
> Specifying 3.0.0-beta.1 in the package.json doesn't result in this issue and is working fine for me so far.

Thanks that works for me

**Comment by gcrockenberg** [comment]
Experienced the same issue. Downgrading back to beta worked. Will keep an eye on this thread.

**Comment by hectormmg** [comment]
@eluchsinger thanks for raising the issue! As @mgermino noticed, v3.0.1 has an issue where B2C authorities aren't appended the "/v2/" path when generating the .well-known/openid-configuraiton endpoint URL (effectively going to the v1 config endpoint), causing the /authorization endpoint URLs to comeback missing the /v2/ path as well. Here's a PR with the fix #6342.

Existing workarounds for the meantime are to downgrade to 3.0.0-beta.1 or to manually configure the `authorityMetadata` option as shown in our [Performance docs](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/docs/performance.md#bypass-authority-metadata-resolution).

**Comment by marvijo-code** [comment]
Hi. Here is one way to modify the `authorityMetadata` JSON string, while we wait for MS and the PR to be merged and released. Modify the `authConfig` object (name of the root object you use) by adding the `authorityMetadata` string `msalConfig.auth.authorityMetadata`:

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/82562019/e147d7ec-0dcb-493b-a237-11e54c72418b)

const tenantName = '<tenant_name>';
const clientId = '<client_id>'

'{"token_endpoint": "https://login.microsoftonline.com/common/oauth2/v2.0/token", "token_endpoint_auth_methods_supported": ["client_secret_post", "private_key_jwt", "client_secret_basic"], "jwks_uri": "https://login.microsoftonline.com/common/discovery/v2.0/keys", "response_modes_supported": ["query", "fragment", "form_post"], "subject_types_supported": ["pairwise"], "id_token_signing_alg_values_supported": ["RS256"], "response_types_supported": ["code", "id_token", "code id_token", "id_token token"], "scopes_supported": ["' + clientId + '", "openid", "profile", "email", "offline_access"], "issuer": "https://login.microsoftonline.com/' + tenantName + '/v2.0", "request_uri_parameter_supported": false, "userinfo_endpoint": "https://graph.microsoft.com/oidc/userinfo", "authorization_endpoint": "https://login.microsoftonline.com/common/oauth2/v2.0/authorize", "device_authorization_endpoint": "https://login.microsoftonline.com/common/oauth2/v2.0/devicecode", "http_logout_supported": true, "frontchannel_logout_supported": true, "end_session_endpoint": "https://login.microsoftonline.com/common/oauth2/v2.0/logout", "claims_supported": ["sub", "iss", "cloud_instance_name", "cloud_instance_host_name", "cloud_graph_host_name", "msgraph_host", "aud", "exp", "iat", "auth_time", "acr", "nonce", "preferred_username", "name", "tid", "ver", "at_hash", "c_hash", "email"], "kerberos_endpoint": "https://login.microsoftonline.com/common/kerberos", "tenant_region_scope": null, "cloud_instance_name": "microsoftonline.com", "cloud_graph_host_name": "graph.windows.net", "msgraph_host": "graph.microsoft.com", "rbac_url": "https://pas.windows.net"}'

**Comment by jonatanpetersson** [comment]
Nobody's happened to stumble upon a third workaround option?
I'm on B2C but neither does it for me unfortunately. Switching to beta or adding `authorityMetadata` still doesn't append `/v2`. Otherwise  I'll just wait for the patch!

**Comment by mgermino** [comment]
> Nobody's happened to stumble upon a third workaround option? I'm on B2C but neither does it for me unfortunately. Switching to beta or adding `authorityMetadata` still doesn't append `/v2`. Otherwise I'll just wait for the patch!

Check your package-lock file. I had an issue where downgrading to the beta didn't actually work.

If in your package.json you have...

`"@azure/msal-angular": '^3.0.0-beta.1'`

Try removing the caret

`"@azure/msal-angular": '3.0.0-beta.1'`

You can then maybe delete your package-lock.json and npm install again. Hope this helps.

**Comment by jonatanpetersson** [comment]
> Try removing the caret

@mgermino That did the trick, thanks a lot! 🥳

**Comment by eluchsinger** [comment]
For me it worked with the `authorityMetadata` workaround and it should also be more performant. Prefer this to downgrade to a Beta version. Still, I don't understand how this change was introduced after the beta.
