### ISSUE TITLE
Getting multiple redirects to app with #code in url

### ISSUE THREAD

**Issue by martinvillysson** [AzureAD/microsoft-authentication-library-for-js#6343]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.0.0-beta.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.0-beta.1

### Public or Confidential Client?

Public

### Description

After upgrade to both msal-browser 2.38.1 and 3.0.0 beta1 I've started getting issues with multiple redirects after visiting our app then closing the browser and then after a couple of hours opening it again.
It starts by me browsing to the app and then multiple consecutive redirects starts with the "#code" in the url and then stops with the #code stuck in the url.

After all redirects the app works fine. I can browse around and reload it without problems. If I then close the browser and wait a couple of hours the error re-appears.

From the network log I can see both HTTP 400 errors from token endpoint https://login.microsoftonline.com/[redacted]/oauth2/v2.0/token

I can also see HTTP 401 to 
https://autologon.microsoftazuread-sso.com/[redacted]/winauth/ssoprobe

I have full network logs if needed but cant share them publicly.

### Error Message

HTTP 400 Bad request - https://login.microsoftonline.com/[redacted]/oauth2/v2.0/token
HTTP 401 - https://autologon.microsoftazuread-sso.com/[redacted]/winauth/ssoprobe

### Msal Logs
This is from sign in logs in Azure AD:
`Sign-in error code:
700084
Failure reason:
The refresh token was issued to a single page app (SPA), and therefore has a fixed, limited lifetime of {time}, which cannot be extended. It is now expired and a new sign in request must be sent by the SPA to the sign in page. The token was issued on {issueDate}.
Additional Details:
Single page apps receive fixed, shorter-lived refresh tokens, and are expected to encounter this error on a regular basis. Apps must handle this error by redirecting the user to the sign in page for a refreshed sign in session.`

Was able to reproduce on localhost and got this message:
BSSO Telemetry: {"result":"Error","error":"NoExtension","type":"ChromeSsoTelemetry","data":{},"traces":["BrowserSSO Initialized","Creating ChromeBrowserCore provider","Sending message for method CreateProviderAsync","Received message for method CreateProviderAsync","Error: ChromeBrowserCore error NoExtension: Extension is not installed."]}

### MSAL Configuration

```javascript
{
    tenant: '[redacted]',
    auth: {
      clientId: '[redacted]',
      redirectUri: 'https://[redacted]',
      clientCapabilities: ['CP1'],
        authority: 'https://login.microsoftonline.com/[redacted]',
        navigateToLoginRequestUrl: true,

        // load auth metadata from memory to save 2 requests
        authorityMetadata: JSON.stringify(AUTHORITY_METADATA),
        cloudDiscoveryMetadata: JSON.stringify(CLOUD_DISCOVERY_METADATA),
      },
      cache: {
        cacheLocation: BrowserCacheLocation.LocalStorage,
      },
      domainHint: '[redacted].onmicrosoft.com',
      protectedResourceScopeMap: [...]
}
```

### Relevant Code Snippets

```javascript
-
```

### Reproduction Steps

1. Browse to app - login as normally
2. Close browser - wait a couple of hours
3. Browse to app again - No sign in required
4. Redirects starts

### Expected Behavior

Should not have redirect multiple times and not leave "#code" in the url

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome - Block third party cookies is ON

### Regression

@azure/msal-browser 2.38.0

### Source

External (Customer)

**Comment by tnorling** [comment]
@martinvillysson Can you please email me the network trace as well as Trace level MSAL logs?

**Comment by zeroregard** [comment]
I'm experiencing the same/similar thing, on version `3.0.1` of both `msal-browser` and `msal-angular`

I'm seeing that my application is redirected to with `localhost:4200/#code=` and afterwards it fails to perform the SSO request and once again redirects the user to login, stuck in an eternal loop. To me it seems that the login itself works fine, but my hunch is that _the MSAL module/service does not pick up the code_ ⚠️ 

Here's a snippet of a function I use for login;
```javascript
login(): Observable<void | AuthenticationResult> {
    console.log('🪟 MSAL - Login started');
    const initialize$ = this.initialized ? of(undefined) : from(this.msalService.instance.initialize());
    return initialize$.pipe(
      tap(() => (this.initialized = true)),
      switchMap(() => {
        const silentRequest = {
          scopes: ['openid', 'profile', 'offline_access'],
        };

        return from(this.msalService.instance.ssoSilent(silentRequest)).pipe(
          catchError(() => {
            console.log('🪟 MSAL - Silent SSO failed, redirecting user to login');
            return this.msalService.loginRedirect();
          }),
          tap(tokenResponse => {
            console.log('🪟 MSAL - Access token acquired', tokenResponse);
          })
        );
      })
    );
  }
```

I made sure to bootstrap the redirect component;
```javascript
  bootstrap: [AppComponent, MsalRedirectComponent],
```

And include it in index.html
```html
  <body>
    <app-root></app-root>
    <app-redirect></app-redirect>
    <noscript>Please enable JavaScript to continue using this application.</noscript>
  </body>
  ```
  
I assume my module setup is correct;
```javascript
MsalModule.forRoot(
      new PublicClientApplication({
        auth: {
          clientId: '[redacted]',
          authority: 'https://login.microsoftonline.com/[redacted]',
          redirectUri: window.origin,
        },
        cache: {
          cacheLocation: 'localStorage',
          storeAuthStateInCookie: isIE,
        },
      }),
      { interactionType: InteractionType.Redirect },
      {
        interactionType: InteractionType.Redirect,
        protectedResourceMap: new Map([['https://graph.microsoft.com', ['user.read']]]),
      }
    ),
```

**Comment by submarines-and** [comment]
Issue is being worked on through email. Go away bot!

**Comment by martinvillysson** [comment]
We are trying to resolve this over mail currently.

**Comment by martinvillysson** [comment]
I may have a possible workaround/solution for this issue by handling the redirects in our initialization logic.
https://github.com/martinvillysson/msal-issue-6343/blob/be3cadc519d67bd71082696d5cd2232bbc436dfa/src/app/app.module.ts#L11

**Comment by lalimasharda** [comment]
Hey @martinvillysson were you able to find a solution or do you have further questions?

**Comment by martinvillysson** [comment]
Hey we’re running our solution in staging at the moment. Planning for production next week. If we don’t experience any issues by then I’ll close the issue.
