### ISSUE TITLE
What is best practice of using acquireTokenSilent ?

### ISSUE THREAD

**Issue by lzhang-advent** [AzureAD/microsoft-authentication-library-for-js#6345]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

2.0

### Public or Confidential Client?

Public

### Description

What is best practice of using acquireTokenSilent ?
1: Call acquireTokenSilent in your app before making **every** API call to get the valid token.
2: Call the acquireTokenSilently method before api call. Then store the token inside the localStorage. Then when calling the API,  get the token from the localStorage and send the token with the request.

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
Option 1: Call acquireTokenSilent before every API call. MSAL.js handles caching the token for you so you do not need to be responsible for the complexity around caching and evaluating token expiration.

**Comment by lzhang-advent** [comment]
Thank you tnorling. 
I implemented using option1 and meet another issue:
After I logout, then login again, get error: BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.  For more visit: aka.ms/msaljs/browser-errors.

This can be fix if I delete msal.interaction.status manually.
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/116617854/eb189b0c-4761-482b-a975-3d860c1d71cd)

I'm using loginpopup, not loginReirect.
Accoding to https://stackoverflow.com/questions/66405214/browserautherror-interaction-in-progress-interaction-is-currently-in-progress
I add this code after user logout.
msalInstance["browserStorage"].clear();

The issue not fixed. I'm using @azure/msal-browser 2.0 since I'm using Angular 8 and don't want to upgrade @azure/msal-browser.

Is there any workaround to fix this issue? Thank you, have a nice day.

**Comment by tnorling** [comment]
You should not clear or manipulate msal cache entries yourself. If it's not getting properly cleaned up by the library either there's something wrong with your usage or there's a bug in the library. Please start by upgrading to the latest version of msal-browser (it does not affect what versions of Angular are supported) and let me know if you're still experiencing this behavior.

**Comment by lzhang-advent** [comment]
Thank you.  Thomas.

**Comment by lzhang-advent** [comment]
Hi Thomas,
Last question, I'm using TypeScript 3.4.3 which is a lower version. But MSAL.js is based on a new version of TypeScript. I upgrade MSAL.js to 2.38.0. In my testing it works well. Do you know if there is any potential issue?

**Comment by lzhang-advent** [comment]
Hi @tnorling  Any comments? Thanks,
