### ISSUE TITLE
How to use the MSAL REACT SDK to login in multiple ways? 

### ISSUE THREAD

**Issue by yunbozhang-msft** [AzureAD/microsoft-authentication-library-for-js#6358]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.38.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.5.10

### Public or Confidential Client?

Confidential

### Description

Hi team, we are following this sample code to implement B2C login: https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/tree/main/1-Authentication/2-sign-in-b2c/SPA

We want to implement multiple login methods in b2clogin page, such as SUSI_PASSWORD and SUSI_PASSCODE. We can click to switch the login method on the b2clogin page.
![image](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/assets/44389598/fe6c1984-439b-462c-8ffd-bc457b82fcce)

![image](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/assets/44389598/d9253e2c-d913-445b-96f4-b936a6efdfd1)

But for these two login methods, we have defined two authority URLs: https://xxxx.b2clogin.cn/xxxx/B2C_1A_AccountLink_SUSI_PASSWORD and https://xxxx.b2clogin.cn/xxxx/B2C_1A_AccountLink_SUSI_PASSCODE.

But when jumping to xxxx.b2clogin.cn through sample code, we can only carry one authority URL, which will cause the verification to fail after we switch the login method on the xxxx.b2clogin.cn page.
For example: I defined the following loginrequest in your sample code:
```
export const loginRequest = {
     scopes: ['https://xxxx.partner.xxxx.cn/xxxx/user_impersonation'],
     authority: 'https://xxxx.b2clogin.cn/xxxx/B2C_1A_AccountLink_SUSI_PASSWORD',
};
```
But after jumping to the xxxx.b2clogin.cn page, I want to switch to the SUSI_PASSCODE login method, but doing so will cause us to still log in with the authority of SUSI_PASSWORD, which will cause the failure to get the token.

How should I achieve our requirements? Is it because we don't currently support this kind of authentication? Should I modify the definition of my policy? Is there any other way to achieve this without modifying the definition of policy?

Any log messages given by the failure
```
{
"error": "invalid_grant",
"error_description": "AADB2C90088: The provided grant has not been issued for this endpoint. Actual Value : B2C_1A_AccountLink_SUSI_PASSWORD and Expected Value : B2C_1A_ACCOUNTLINK_SUSI_PASSCODE\r\nCorrelation ID: 1d9c901a-85bf-4060-ac8a-46cc435a5a94\r\nTimestamp: 2023-08-09 04:01:56Z\r\n"
}
```

### Identity Provider

Azure B2C Custom Policy

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
We unfortunately do not support switching policies mid flow. If you'd like to switch policies clicking SUSI_PASSCODE should redirect back to your app with an error. Your app can catch this error and make a new request to the desired policy.

We're not B2C experts so I'm not sure how possible this would be, but another alternative would be to have a single converged policy e.g. SUSI which has the capability to handle both Password and Passcode.

**Comment by yunbozhang-msft** [comment]
Hi @tnorling thanks for your support. Do we have plan to support switching policies mid-flow? If we have, could you please share the timeline, thanks!

**Comment by tnorling** [comment]
Unfortunately, we have no plans to support this.
