### ISSUE TITLE
After completing an EditProfile policy, I end up with two accounts (one for SignIn, one for EditProfile)

### ISSUE THREAD

**Issue by doug-williamson** [AzureAD/microsoft-authentication-library-for-js#6363]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.31.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.4.6

### Public or Confidential Client?

Public

### Description

When I first authenticate myself and am logged into my app, I have one account with the acr/tfp value of SignIn in my SessionStorage (authorityType: MSSTS). If I navigate to an EditProfile policy page, complete it and return to my app, I have two accounts (one with the acr/tfp value of SignIn and one with the acr/tfp value of EditProfile (same authorityType).

The account w/ EditProfile acr/tfp has up-to-date claims information, whereas the account w/ SignIn acr/tfp retains the version of claims from when the user originally authenticated.

Is there something I could be doing wrong that's causing the multiple accounts to appear in my SessionStorage?

### MSAL Configuration

```javascript
return new PublicClientApplication({
		auth: {
			clientId: isIgniteReHost() ? environment.msalConfig.auth.igniteReClientId : environment.msalConfig.auth.standaloneClientId,
			authority: environment.b2cPolicies.authorities.signIn.authority,
			redirectUri: environment.msalConfig.auth.logoutRedirectUri,
			postLogoutRedirectUri: environment.msalConfig.auth.logoutRedirectUri,
			knownAuthorities: [environment.b2cPolicies.authorityDomain],
			navigateToLoginRequestUrl: false,
		},
		cache: {
			cacheLocation: BrowserCacheLocation.SessionStorage,
			storeAuthStateInCookie: isIE, // set to true for IE 11.
		},
		system: {
			loggerOptions: {
				loggerCallback,
				logLevel: LogLevel.Verbose,
				piiLoggingEnabled: false,
			},
		},
	});
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by doug-williamson** [comment]
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/12549217/fa60e1f0-8888-4f93-a0da-b3f9a6b627e2)

**Comment by doug-williamson** [comment]
If I trigger a different policy page, like PhoneEdit, I get yet another account. What I'm trying to do is get the claims information from the most-recent policy page (to send to my API), but I'll have to cycle through the msalService account instances. Would the most-recent (3 of 3, for example) one be the latest-and-greatest?

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/12549217/380a7d04-cba6-4c42-a5b8-17eb8423a56e)

**Comment by doug-williamson** [comment]
They do not appear to be in a sequential order. The latest one (of 3) is in the middle of the array.

**Comment by doug-williamson** [comment]
I suppose I could grab the account w/ the highest auth_time value, but I'd prefer a cleaner option if possible. Thoughts?

**Comment by tnorling** [comment]
This is unfortunately, as designed for B2C use cases. Each policy is essentially a separate authority and as such gets treated as a separate account. I understand it's a pain but you will have to build custom logic for what you're trying to do.

Another thing to keep in mind is when you need to go back to a policy you've already hit you'll need to pass the account object which corresponds to the policy you're trying to get tokens for (in addition to passing the policy on the authority parameter)

> They do not appear to be in a sequential order. The latest one (of 3) is in the middle of the array.

This is correct. Accounts are not sorted nor are they guaranteed to be in the same order each time.

**Comment by doug-williamson** [comment]
Thank you for following up! I appreciate it.

**Comment by tnorling** [comment]
If you need anything else let us know!
