### ISSUE TITLE
Provide In-Memory Storage of Access Token

### ISSUE THREAD

**Issue by heymega** [AzureAD/microsoft-authentication-library-for-js#637]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Currently you can store the access token in either **localStorage** or **sessionStorage**.

## Expected behavior
Add a third option which allows you to store the access token in-memory.

In-memory storage is more secure than local storage.

For information
- https://auth0.com/docs/security/store-tokens
- https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/HTML5_Security_Cheat_Sheet.md#local-storage

</code></pre>

**Comment by DarylThayil** [comment]
Can you describe what you mean by in memory?

**Comment by heymega** [comment]
Storing the value in a variable/object inside a service registered as a singleton.

**Comment by sameerag** [comment]
Linking this with #602 ; closing this issue.
