### ISSUE TITLE
acquireTokenSilent fails in 3.0.1 and 3.0.2 but not  2.37.0

### ISSUE THREAD

**Issue by bibble235** [AzureAD/microsoft-authentication-library-for-js#6375]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.0.2

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.0.2

### Public or Confidential Client?

Public

### Description

Calling acquireTokenSilent no longer returns a token

### Error Message

uninitialized_public_client_application

### MSAL Configuration

```javascript
auth: {
        clientId: `${Config.reactAppAuth0ClientId}`,
        authority: `https://login.microsoftonline.com/${Config.reactAppAuth0TenantId}`,
        postLogoutRedirectUri: ROUTES.SIGNED_OUT,
        redirectUri: `${Config.reactAppAuth0Domain}/`,
    },
    cache: {
        cacheLocation: 'sessionStorage', // This configures where your cache will be stored
        storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
    },
```

### Relevant Code Snippets

```javascript
export const GetAccessTokenService2 = async (): Promise<string> => {
    const msalInstance = new PublicClientApplication(msalConfig)

    const activeAccount = msalInstance.getActiveAccount()
    const accounts = msalInstance.getAllAccounts()

    if (!activeAccount && accounts.length === 0) {
        throw new Error('No active account or accounts found')
    }

    const resp = await msalInstance.acquireTokenSilent({
        ...apiLoginRequest,
        account: activeAccount ?? accounts[0],
    })

    return resp.accessToken
}
```

### Reproduction Steps

1.             const token = await GetAccessTokenService2()

### Expected Behavior

1/ Have a valid Logged in React App
2/ Call await GetAccessTokenService2()

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Regression

@azure/msal-browser": "^2.37.0"

### Source

External (Customer)

**Comment by tnorling** [comment]
Please see the [v2-v3 migration guide](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/v2-migration.md)

**Comment by bibble235** [comment]
Just those watching this did resolve my issue ie.

`    const msalInstance = new PublicClientApplication(msalConfig)
await msalInstance.initialize()
`
