### ISSUE TITLE
Generate B2C signup form url for unified signup signin flow

### ISSUE THREAD

**Issue by isthatcentered** [AzureAD/microsoft-authentication-library-for-js#6376]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

2.0.2

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Confidential

### Description

When using a unified signup/sign-in flow, I was not able to find any example or issue showing how to generate the url for the signup flow and not the sign-in.

I tried setting the `request.prompt` value of `getAuthCodeUrl` as this looked like something that would do the trick but this returns an AADB2C90043 (`The prompt included in the request contains invalid values. Expected 'none', 'login', 'consent' or 'select_account'.`)

Am I approaching this the wrong way? This is something we've been able to accomplish using the `msal-browser` library so I assume this is possible here too.

### MSAL Configuration

```javascript
{
  auth: {
    clientId: 'xxxx',
    clientSecret: 'xxxx',
    authority: 'https://.../B2C_1_Blah_SignUp_SignIn',
    knownAuthorities: [ 'https://xxx.b2clogin.com' ]
  }
}
```

### Relevant Code Snippets

```javascript
cca.getAuthCodeUrl({
   state: params.state,
   redirectUri: params.redirectUri,
   scopes: config.scopes,
   prompt: "create"
})
```

### Identity Provider

Azure B2C Basic Policy

### Source

External (Customer)

**Comment by isthatcentered** [comment]
We have managed to make it work by using a custom B2C template for the page that reads a query param to display either the signup or the sign-in form and it works very well. 

I would be curious however to know if there is a better way.

**Comment by tnorling** [comment]
I don't think prompt: create is supported by the B2C service out of the box - your workaround is likely the best way to achieve this

**Comment by isthatcentered** [comment]
Thank you for taking the time to answer. I'm closing the issue then :)
