### ISSUE TITLE
Types are broken for moduleResolution: Node16 and NodeNext 

### ISSUE THREAD

**Issue by datner** [AzureAD/microsoft-authentication-library-for-js#6377]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

2.0.2

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public, Confidential

### Description

reminiscent of #6151 

I'm using latest typescript, my server is fully esm.
```json
{
  "type": "module"
}
```
```json
{
  "compilerOptions": {
    "module": "NodeNext",
    "moduleResolution": "NodeNext"
  }
}
```
and all the types from msal are broken. This is because typescript doesn't map `.mjs` to `.d.ts` naturally. So you get this, if you're looking inside:
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/22598347/7ac1b567-9336-4c1d-9ddd-0488a29f8bd6)

Looking at `index.d.ts`, for `esm` the imports don't point to any _typed_ file,
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/22598347/e41476e4-c5eb-4cfe-a815-a46eea7e4670)

If directed explicitly to the `d.ts`, this is resolved

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/22598347/fe747806-7a5f-45ec-890a-e565fc068eec)

### **!NOTE! This is not enough, for this to work _all_  imports in `d.ts` files have to explicitly point to `d.ts` files**

I'm not sure how to solve this, but from my personal experience I found that meme extensions are very painful to work with

### MSAL Configuration

```javascript
{}
```

### Relevant Code Snippets

```javascript
import { CryptoProvider } from "@azure/msal-node"
// or anything, really
```

### Reproduction Steps

1. create modern esm node project
2. install `@azure/msal-node`
3. ??????
4. profit

### Expected Behavior

Typed correctly

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Regression

@azure/msal-node@~2

### Source

External (Customer)

**Comment by tnorling** [comment]
This is due to your `moduleResolution: NodeNext` which requires relative paths to include file extensions. We do not yet compile for the newer module resolution. Marking this as a feature, for now you may need to go back to `moduleResolution: node` to get this to work - we also accept PRs if you'd like to take a crack at this yourself.

**Comment by datner** [comment]
@tnorling I'll give it a go if you promise that the PR won't sit ignored for 2 months 😅
This is real blocker for us

**Comment by datner** [comment]
@tnorling here you go mate, hope this is resolved swiftly 💪🏻
