### ISSUE TITLE
Auth0 with MSAL

### ISSUE THREAD

**Issue by gmiked** [AzureAD/microsoft-authentication-library-for-js#6388]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.28.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.4.1

### Public or Confidential Client?

Public

### Description

I am trying to use Auth0 idp and currently receiving an error 'unsupported_response_mode: Unsupported response mode: fragment'.  I have seen previous questions where there was a plan to allow changing the response mode from the default fragment to query.  Is that still on the pipeline?

### Identity Provider

Other

### Source

External (Customer)

**Comment by lalimasharda** [comment]
Hey @gmiked , can you share how you are configuring your Public Client App? Can you please double check your configuration based on[ this sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-browser-samples/VanillaJSTestApp2.0/app/facebook-sample#important-changes-when-using-non-microsoft-identity-providers)? Thanks!

**Comment by gmiked** [comment]
Hello @lalimasharda.  Thanks for providing the sample code.  I am also recieving an error stating that OIDCOptions' does not exist in type 'BrowserAuthOptions'.  Was the this added in a later version than what I currently have?

**Comment by lalimasharda** [comment]
Hey @gmiked apologies. I missed out on checking what version you were on. We support non-Microsoft IdPs only in v3. Please upgrade your msal-browser and msal-angular versions to the latest 3.0.2.

**Comment by gmiked** [comment]
@lalimasharda No problems.  With the latest 3.0.2, I am assuming this is MSAL.js v3.  Is there any documentation such as breaking changes or FAQ available on the changes between v2 and v3?  Also, does this support Angular 14?

**Comment by lalimasharda** [comment]
Hey @gmiked please follow this [doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/v2-migration.md) for guidelines on migrating from v2 to v3. Please also take a look at this [README](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-angular) for Angular support questions.

**Comment by gmiked** [comment]
@lalimasharda Thank you!!!
