### ISSUE TITLE
Endpoint discovery and Authority validation needs Logging

### ISSUE THREAD

**Issue by shivbijlani** [AzureAD/microsoft-authentication-library-for-js#64]

**Comment by rohitnarula7176** [comment]
@spottedmahn We would be open to a community PR.

**Comment by sameerag** [comment]
@spottedmahn We have enhanced our error handling with our API changes and this would help catch any authority validation or endpoint errors.

Please download our [latest preview package](https://www.npmjs.com/package/msal) or pull the [dev branch](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev) and try updating your code and see if the issue still persists. 

If you would like guidance on how to use the new version of the library, please review our wiki page [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL.js-1.0.0-preview-api-release).

**Comment by spottedmahn** [comment]
Hi @sameerag - that's great.  Can you provide a link to the PR/commit?

**Comment by sameerag** [comment]
So we had multiple PRs as this was a big API surface change activity. npm@msal-preview should pull the latest code for you as mentioned above - or 'dev' branch is up to date. We do plan a release soon and get out of the preview mode. This release is majorly focused in API surface changes to improve the usability of the library. 

Having said that some of the inner workings updates (includes logging) will follow once we stabilize the API changes for the community.

Regarding logging/error handling some things of note:

- Validating Authority has error handling code now. This part of the code is going through some feature changes to accommodate a more generic solution, hence the release after the current release (in plan) will have more traction.
- we added some error checking for endPointResolution but this is not complete. Some code could be simplified and there is an internal tracker for this.
- Logging is separate from API Changes as we want to evolve logging into a more consistent pattern across the code. This is a separate effort which we plan in a future release.

**Comment by spottedmahn** [comment]
>So we had multiple PRs as this was a big API surface change activity

Fair enough, thanks for the reply 👍
