### ISSUE TITLE
How to remove admin consent check box?

### ISSUE THREAD

**Issue by chesteryang** [AzureAD/microsoft-authentication-library-for-js#640]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
N/A

## Library version

Library version: 0.2.4

## Current behavior
When calling loginPopup, there are scopes such as Group.ReadWrite.All, which requires Admin consent for none admin users. Currently when an administrator logins, it will popup consent dialog as follows:
![RemoveAdminConsent](https://user-images.githubusercontent.com/7731284/56051036-b3da6000-5d0a-11e9-8418-0681f50158cf.jpg)

We only want to let administrator login but don't want administrator consent for the whole organization.

## Expected behavior
When calling loginPopup, provide an option to remove admin consent check box if it is an administrator logins

**Comment by Zawad** [comment]
Thank you for sharing this idea @chesteryang! I would like to fully understand the value you are looking for here, so can you provide more details on the value of having this functionality?

Here is a little background on the checkbox functionality as it is now - The checkbox only appears for global admin users. The global admin role is a very privileged role that only a select few employees should be eligible for. This checkbox will never be seen by a non-admin user. In the case a global admin user sees this checkbox, they already have the authority to decide whether or not they would like to grant consent for themselves or on behalf of the entire organization. The checkbox presented in this experience is just providing a convenient affordance for global admins.

**Comment by chesteryang** [comment]
Thanks for the response. We have such scenario as getting consent once to setup an application on an azure account. We cannot assume there is always a knowledgeable global admin user. And also we don't want to provide a chance through the application to let admin user check consent box for others. If they do it in azure portal, they can do it but it is slightly different and it has nothing to do with the application.
