### ISSUE TITLE
Managed Identity Support in MSAL JS

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-js#6401]
### Core Library

MSAL Node (@azure/msal-node)

### Wrapper Library

Not Applicable

### Public or Confidential Client?

Confidential

### Description

See example support in MSAL .NET - https://learn.microsoft.com/en-us/entra/msal/dotnet/advanced/managed-identity

More in-depth technical spec : https://identitydivision.visualstudio.com/DevEx/_git/AuthLibrariesApiReview?path=/ManagedIdentity/ManagedIdentity.md&version=GBdev&anchor=key-case-sensitivity 

Full task breakdown as per MSAL Java: https://github.com/orgs/AzureAD/projects/25

Azure Identity implementation: https://github.com/Azure/azure-sdk-for-js/tree/main/sdk/identity/identity/src/credentials/managedIdentityCredential

### Source

Internal (Microsoft)

**Comment by jeffwilcox** [comment]
If you need another Microsoft tester here, lmk. Keen to move away from some ancient code...

**Comment by Robbie-Microsoft** [comment]
> If you need another Microsoft tester here, lmk. Keen to move away from some ancient code...

@jeffwilcox Managed Identity is now available in msal-node 2.7.0
