### ISSUE TITLE
User not signed-out if RelyingParty SSO scope=Application

### ISSUE THREAD

**Issue by aorlenko** [AzureAD/microsoft-authentication-library-for-js#6402]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.28.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.4.0

### Public or Confidential Client?

Public

### Description

I'm using the `angular-b2c-sample-app` sample app. I've setup the B2C instance with custom policies support, and setup one application registration for my test app.
In general I haven't made any major changes to the js sample app, just setup the parameters appropriately (auth-config.ts file). 
I have the custom policy for signin. If I don't specify the SingleSignOn section in RelyingParty, or use the `Scope=Tenant`, everything works fine. So I can sign in and signout from the application. 
But if I set the `SingleSignOn Scope="Application"` in the RelyingParty, the sign out is not working properly anymore. After clicking Logout button, I see the application as if it is logged out. But when I click Login button, it signs me in via sso, without prompting credentials.
Also, if I manually clear the browser state, or just delete the `x-ms-cpim-sso:******_0` cookie before sign-out, then I'm successfully logged out after clicking Logout button.
So it looks like if the SSO Scope is Application, the logout is not working properly and it seems like it's not clearing the session state properly. And if the RP SSO Scope is `Tenant`, the logout is working correctly.
Thanks in advance for any help.

### MSAL Configuration

```javascript
export const msalConfig: Configuration = {
    auth: {
        clientId: '-- client id --', 
        authority: '--b2c instance--/B2C_1A_signup_signin_prototype', 
        knownAuthorities: ['-- authority --'], 
        redirectUri: '/auth', 
        postLogoutRedirectUri: '/', 
    },
    cache: {
        cacheLocation: BrowserCacheLocation.LocalStorage,
        storeAuthStateInCookie: isIE,
    },
    system: {
        ...
    }
}
```

### Relevant Code Snippets

```javascript
<RelyingParty>
    <DefaultUserJourney ReferenceId="CustomSignUpOrSignIn" />
    <UserJourneyBehaviors>
      <SingleSignOn Scope="Application" KeepAliveInDays="30" />
      <SessionExpiryType>Rolling</SessionExpiryType>
      <SessionExpiryInSeconds>86400</SessionExpiryInSeconds>
...
</RelyingParty>
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by lalimasharda** [comment]
Hey @aorlenko ! Can you share how you are building the logout request or share the link to the sample you are using? Have you tried passing in the client id as per [this spec](https://learn.microsoft.com/en-us/azure/active-directory-b2c/openid-connect#send-a-sign-out-request)?

**Comment by aorlenko** [comment]
@lalimasharda Not passing the client_id parameter along with the logout request was the reason.
Thanks a lot!

**Comment by TanyaMykhnevych** [comment]
@aorlenko could you please share Angular code for logout? I have the same issue and I can not find where to put client_id parameter along with the logout request. If I just add it by hands and put request into browser - it does not help.

**Comment by TanyaMykhnevych** [comment]
We found how to pass parameter. Like this:
`this._msalService.logout({ extraQueryParameters: { client_id: environment.msalClientId }, })`
