### ISSUE TITLE
Msal-Angular multi-tenant - switching between tenants yields unexpected results

### ISSUE THREAD

**Issue by HarrisonMulder** [AzureAD/microsoft-authentication-library-for-js#6409]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

^3.0.2

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

^3.0.2

### Public or Confidential Client?

Public

### Description

I have an application that allows the user to choose one of four tenants to login to in an 'unguarded' login page (loginComponent).  Once the user chooses a tenant, I use loginRedirect() to sign the user in.  The redirect routes back to the login component, which detects that they're now logged in and re-routes them into a 'guarded' dashboard page, protected by MsalGuard (guardedComponent).  Inside the 'guarded' dashboard page, I have a dropdown available to allow the user to switch between tenants.  

This behaviour works at first, but when switching back to a tenant that was already previously logged in, the MsalService's active account's tenantId property doesn't seem to update properly to the new tenantId.  

The issue occurs when the user FIRST logs into Tenant A, then in the dashboard switches to Tenant B (this works), but when switching back to Tenant A again, their 'tenantId' property is STILL set to Tenant B.  

I have a 'tenantService' which keeps track of the available tenants, by name and ID.  I have an 'authService' which holds the msalService instance, listens on msal events, and updates its state accordingly using angular signals.

### MSAL Configuration

```javascript
{
    auth: {
        clientId: appRegistrationClientId,
        authority: `https://login.microsoftonline.com/${tenantId}/`,
        redirectUri: "/login"
    },
    cache: {
        cacheLocation: BrowserCacheLocation.LocalStorage,
        storeAuthStateInCookie: true
    },
    system: {
        allowNativeBroker: false, // Disables WAM Broker
        loggerOptions: {
            loggerCallback: loggerCallback,
            logLevel: LogLevel.Warning,
            piiLoggingEnabled: false
        }
    }
}
```

### Relevant Code Snippets

```javascript
public async login(tenantId: string) {
    this.msalService.instance = createMsalInstance(tenantId);
    await this.msalService.initialize();
    this.msalService.loginRedirect();
}

constructor() {
    this.msalInstance.enableAccountStorageEvents();
    this.updateAuthStatus();

    this.msalBroadcastService.msalSubject$
    .pipe(
      filter((msg: EventMessage) => msg.eventType === EventType.LOGIN_SUCCESS),
    )
    .subscribe((result: EventMessage) => {
      const payload = result.payload as AuthenticationResult;
      this.msalInstance.setActiveAccount(payload.account);
      this.updateAuthStatus();
    });

    this.msalBroadcastService.msalSubject$
    .pipe(
      filter((msg: EventMessage) => msg.eventType === EventType.ACCOUNT_ADDED || msg.eventType === EventType.ACCOUNT_REMOVED),
    )
    .subscribe((result: EventMessage) => {
      if (result.eventType === EventType.ACCOUNT_ADDED) {
        const payload = result.payload as AccountInfo;
        this.msalInstance.setActiveAccount(payload);
      }

      this.updateAuthStatus();
    });

    this.msalBroadcastService.inProgress$
    .pipe(
      filter((status: InteractionStatus) => status === InteractionStatus.None)
    )
    .subscribe(() => {
      this.updateAuthStatus();
    });
}

private updateAuthStatus() {
    let activeAccount = this.msalInstance.getActiveAccount();

    if (!activeAccount && this.msalInstance.getAllAccounts().length > 0) {
      activeAccount = this.msalInstance.getAllAccounts()[0];
      this.msalInstance.setActiveAccount(activeAccount);
    }

    const loggedIn = activeAccount ? this.tenantService.AllTenants.some(t => t.id === activeAccount?.tenantId) : false;
    const userName = loggedIn ? activeAccount?.name ?? '' : '';
    const tenantId = loggedIn ? activeAccount?.tenantId ?? '' : '';
    const tenantName = loggedIn ? this.tenantService.getById(tenantId)?.friendlyName ?? '' : '';

    this.setState({
      isLoggedIn: loggedIn,
      userName: userName,
      tenantId: tenantId,
      tenantName: tenantName
    } as AuthServiceState);
}
```

### Reproduction Steps

1. Log into Tenant A
2. Observe the active account's "tenantId" is set to Tenant A
3. Log into Tenant B
4. Observe the active account's "tenantId" is set to Tenant B
5. Log back into Tenant A
6. Observe the active account's "tenantId" is still set to Tenant B

### Expected Behavior

1. Log into Tenant A
2. Observe the active account's "tenantId" is set to Tenant A
3. Log into Tenant B
4. Observe the active account's "tenantId" is set to Tenant B
5. Log back into Tenant A
6. EXPECTED the active account's "tenantId" to be set to Tenant A again

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

Internal (Microsoft)

**Comment by sameerag** [comment]
@HarrisonMulder There is an active PR to fix this on our end, supporting multi-tenanted behavior (some gaps like above). Please track it here: #6396. We expect this to be available in the next MSAL release.

**Comment by HarrisonMulder** [comment]
@sameerag thank you, will keep an eye on that!
