### ISSUE TITLE
Error: NG04002: Cannot match any routes. URL Segment: 'state%3D' 

### ISSUE THREAD

**Issue by ankushdaga11** [AzureAD/microsoft-authentication-library-for-js#6415]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

^3.0.2

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

^3.0.2

### Public or Confidential Client?

Public

### Description

We recently upgraded from Angular 14 to Angular 16, and as a result, we have begun experiencing login loop issues. As soon as I enter MFA details  it again present's me with MFA screen to enter the code again. It's happening in loop.

If I remove the useHash setting from routes things work fine for me , I am able to login and access the application but soon as the user hits the refresh it results in WebContentNotFound - 404. I don't want to remove the useHash setting as that is breaking other parts in application which used to work fine before the upgrade.

Also as shown in the code snippet below we are already having hash routes included in our routing file

{
    // Needed for hash routing
    path: 'state',
    canActivate: [MsalGuard],
    redirectTo: '',
    pathMatch: 'full'
  },
  {
    // Needed for hash routing
    path: 'code',
    canActivate: [MsalGuard],
    redirectTo: '',
    pathMatch: 'full'
  },

### Error Message

Error: Uncaught (in promise): Error: NG04002: Cannot match any routes. URL Segment: 'state%3DeyJpZCI6IjQwY2FhOTNlLTc1OTItNDA2ZS05NzAwLWRiYjIyZTExZWViY**********'

### Msal Logs

Navigated to https://XXXX.b2clogin.com/XXXX.onmicrosoft.com/XXXX/api/SelfAsserted/confirmed?csrf_token=Rm14eHR3ei9ZajU0Q3RYUjR3N1ROMmNkMncxQWs0L2kwL2ZpeE5yVDJnTkdOdkc3NWVZbk1hOVZqbm5YU3JlbE1QT3BBc2labVpZeThIeHZCWms0T3c9PTsyMDIzLTA4LTMxVDA2OjQ0OjAzLjA0MzgwMTFaO09ZWDZYeGl5VFpkejRVZ1p4MHZ5ZXc9PTt7IlRhcmdldEVudGl0eSI6IkxvY2FsQWNjb3VudFNpZ25pbkVtYWlsRXhjaGFuZ2UiLCJPcmNoZXN0cmF0aW9uU3RlcCI6NH0=&tx=StateProperties=eyJUSUQiOiIyZGU4ZTFlYi0zNjZmLTQwZDYtOTQ2Ni1hY2E2ZjFlMGJiMDIifQ&p=XXXX&diags=%7B%22pageViewId%22%3A%22cbf83d36-8f20-4e74-896d-38187644368d%22%2C%22pageId%22%3A%22SelfAsserted
Navigated to http://localhost:4200/
app-config-loader.service.ts:4 [webpack-dev-server] Server started: Hot Module Replacement disabled, Live Reloading enabled, Progress disabled, Overlay enabled.
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : @azure/msal-browser@3.0.2 : Verbose - BrowserCrypto: modern crypto interface available
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : @azure/msal-browser@3.0.2 : Verbose - Event callback registered with id: 14b43d05-be7f-420f-b929-ded8d628c157
jsonp chunk loading:86 Angular is running in development mode.
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : @azure/msal-angular@3.0.2 : Verbose - MsalRedirectComponent activated
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : @azure/msal-browser@3.0.2 : Info - Emitting event: msal:initializeStart
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : @azure/msal-browser@3.0.2 : Verbose - Emitting event to callback 14b43d05-be7f-420f-b929-ded8d628c157: msal:initializeStart
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : @azure/msal-browser@3.0.2 : Info - Emitting event: msal:initializeEnd
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : @azure/msal-browser@3.0.2 : Verbose - Emitting event to callback 14b43d05-be7f-420f-b929-ded8d628c157: msal:initializeEnd
jsonp chunk loading:86 Angular is running in development mode.
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : @azure/msal-browser@3.0.2 : Verbose - handleRedirectPromise called
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : @azure/msal-browser@3.0.2 : Verbose - getAllAccounts called
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : @azure/msal-browser@3.0.2 : Verbose - BrowserCacheManager.getAccountKeys - No account keys found
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : @azure/msal-browser@3.0.2 : Info - Emitting event: msal:handleRedirectStart
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : @azure/msal-browser@3.0.2 : Verbose - Emitting event to callback 14b43d05-be7f-420f-b929-ded8d628c157: msal:handleRedirectStart
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : @azure/msal-angular@3.0.2 : Verbose - BroadcastService - msal:handleRedirectStart results in setting inProgress from startup to handleRedirect
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : @azure/msal-browser@3.0.2 : Verbose - handleRedirectPromise has been called for the first time, storing the promise
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : [a6753fbc-8a77-413b-af4d-99354aace3e8] : msal.js.browser@3.0.2 : Verbose - initializeServerTelemetryManager called
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : [a6753fbc-8a77-413b-af4d-99354aace3e8] : msal.js.browser@3.0.2 : Verbose - getRedirectResponseHash called
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : [a6753fbc-8a77-413b-af4d-99354aace3e8] : msal.js.browser@3.0.2 : Verbose - Hash does not contain known properties, returning cached hash
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : [a6753fbc-8a77-413b-af4d-99354aace3e8] : msal.js.browser@3.0.2 : Info - handleRedirectPromise did not detect a response hash as a result of a redirect. Cleaning temporary cache.
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : @azure/msal-browser@3.0.2 : Info - Emitting event: msal:handleRedirectEnd
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : @azure/msal-browser@3.0.2 : Verbose - Emitting event to callback 14b43d05-be7f-420f-b929-ded8d628c157: msal:handleRedirectEnd
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : @azure/msal-angular@3.0.2 : Verbose - BroadcastService - msal:handleRedirectEnd results in setting inProgress from handleRedirect to none
jsonp chunk loading:86 none
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : @azure/msal-browser@3.0.2 : Verbose - getAllAccounts called
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : @azure/msal-browser@3.0.2 : Verbose - BrowserCacheManager.getAccountKeys - No account keys found
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : @azure/msal-browser@3.0.2 : Verbose - getAllAccounts called
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : @azure/msal-browser@3.0.2 : Verbose - BrowserCacheManager.getAccountKeys - No account keys found
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : @azure/msal-browser@3.0.2 : Verbose - getAllAccounts called
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : @azure/msal-browser@3.0.2 : Verbose - BrowserCacheManager.getAccountKeys - No account keys found
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : [747947ca-e6cb-436f-8d8a-3a469b0f2ec5] : @azure/msal-browser@3.0.2 : Verbose - loginRedirect called
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : [747947ca-e6cb-436f-8d8a-3a469b0f2ec5] : @azure/msal-browser@3.0.2 : Verbose - acquireTokenRedirect called
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : @azure/msal-browser@3.0.2 : Verbose - preflightBrowserEnvironmentCheck started
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : @azure/msal-browser@3.0.2 : Verbose - preflightInteractiveRequest called, validating app environment
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : @azure/msal-browser@3.0.2 : Verbose - getAllAccounts called
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : @azure/msal-browser@3.0.2 : Verbose - BrowserCacheManager.getAccountKeys - No account keys found
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : @azure/msal-browser@3.0.2 : Info - Emitting event: msal:loginStart
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : @azure/msal-browser@3.0.2 : Verbose - Emitting event to callback 14b43d05-be7f-420f-b929-ded8d628c157: msal:loginStart
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : @azure/msal-angular@3.0.2 : Verbose - BroadcastService - msal:loginStart results in setting inProgress from none to login
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : [747947ca-e6cb-436f-8d8a-3a469b0f2ec5] : msal.js.browser@3.0.2 : Verbose - initializeAuthorizationRequest called
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : [747947ca-e6cb-436f-8d8a-3a469b0f2ec5] : msal.js.browser@3.0.2 : Verbose - getRedirectUri called
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : [747947ca-e6cb-436f-8d8a-3a469b0f2ec5] : msal.js.browser@3.0.2 : Verbose - Initializing BaseAuthRequest
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : [747947ca-e6cb-436f-8d8a-3a469b0f2ec5] : msal.js.browser@3.0.2 : Verbose - Authentication Scheme wasn't explicitly set in request, defaulting to "Bearer" request
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : [747947ca-e6cb-436f-8d8a-3a469b0f2ec5] : msal.js.browser@3.0.2 : Verbose - initializeServerTelemetryManager called
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : [747947ca-e6cb-436f-8d8a-3a469b0f2ec5] : msal.js.browser@3.0.2 : Verbose - initializeAuthorizationRequest called
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : [747947ca-e6cb-436f-8d8a-3a469b0f2ec5] : msal.js.browser@3.0.2 : Verbose - getClientConfiguration called
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : [747947ca-e6cb-436f-8d8a-3a469b0f2ec5] : msal.js.browser@3.0.2 : Verbose - getDiscoveredAuthority called
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : [747947ca-e6cb-436f-8d8a-3a469b0f2ec5] : msal.js.browser@3.0.2 : Verbose - Creating discovered authority with configured authority
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : [747947ca-e6cb-436f-8d8a-3a469b0f2ec5] : msal.js.browser@3.0.2 : Verbose - Attempting to get cloud discovery metadata  from authority configuration
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : [747947ca-e6cb-436f-8d8a-3a469b0f2ec5] : msal.js.browser@3.0.2 : Verbose - The host is included in knownAuthorities. Creating new cloud discovery metadata from the host.
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : [747947ca-e6cb-436f-8d8a-3a469b0f2ec5] : msal.js.browser@3.0.2 : Verbose - Found cloud discovery metadata in authority configuration
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : [747947ca-e6cb-436f-8d8a-3a469b0f2ec5] : msal.js.browser@3.0.2 : Verbose - Attempting to get endpoint metadata from authority configuration
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : [747947ca-e6cb-436f-8d8a-3a469b0f2ec5] : msal.js.browser@3.0.2 : Verbose - Found endpoint metadata in authority configuration
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : [747947ca-e6cb-436f-8d8a-3a469b0f2ec5] : msal.js.browser@3.0.2 : Verbose - Auth code client created
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : [747947ca-e6cb-436f-8d8a-3a469b0f2ec5] : msal.js.browser@3.0.2 : Verbose - RedirectHandler.initiateAuthRequest called
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : [747947ca-e6cb-436f-8d8a-3a469b0f2ec5] : msal.js.browser@3.0.2 : Verbose - RedirectHandler.initiateAuthRequest: redirectStartPage set, caching start page
jsonp chunk loading:86 [Thu, 31 Aug 2023 06:45:35 GMT] : [747947ca-e6cb-436f-8d8a-3a469b0f2ec5] : msal.js.browser@3.0.2 : Verbose - RedirectHandler.initiateAuthRequest: Navigating window to navigate url
Util.js:102 [webpack-dev-server] Disconnected!
Util.js:102 [webpack-dev-server] Trying to reconnect...
Navigated to https://XXXX.b2clogin.com/XXXX.onmicrosoft.com/XXXX/oauth2/v2.0/authorize?client_id=01c7e36e-e3d8-4609-baf3-d06fca482641&scope=openid%20profile%20offline_access&redirect_uri=http%3A%2F%2Flocalhost%3A4200%2F&client-request-id=747947ca-e6cb-436f-8d8a-3a469b0f2ec5&response_mode=fragment&response_type=code&x-client-SKU=msal.js.browser&x-client-VER=3.0.2&client_info=1&code_challenge=G28TxGrY2ovCRM6fC2W6czPQ4yJcNcGGM1fbJI4fBnY&code_challenge_method=S256&nonce=c4cb9016-70fd-44b5-8916-3e28d66abf18&state=eyJpZCI6IjQwY2FhOTNlLTc1OTItNDA2ZS05NzAwLWRiYjIyZTExZWViYyIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicmVkaXJlY3QifX0%3D
Navigated to https://XXXX.b2clogin.com/XXXX.onmicrosoft.com/XXXX/api/SelfAsserted/confirmed?csrf_token=S1ZZSCtYUXI3UDhsd0VndEtiWVN4N09vdkY2MTEwZEpzNjFXT2tEdit6M1dBWms1OUZMaHdqblFIb3pSV1VWT3B5TkRhMG81R2YwNVl1TFNoSEN1VXc9PTsyMDIzLTA4LTMxVDA2OjQ1OjM2LjE0NjU0MTJaO2prTTVSOFUxZTBTWG1lVXBTWjl2ZHc9PTt7IlRhcmdldEVudGl0eSI6IkxvY2FsQWNjb3VudFNpZ25pbkVtYWlsRXhjaGFuZ2UiLCJPcmNoZXN0cmF0aW9uU3RlcCI6NH0=&tx=StateProperties=eyJUSUQiOiJlODVmNDdjNS05ZGYwLTRmMTMtOGI3OS0zYjc5ZTFkNWZhNTQifQ&p=B2C_1A_MFA_phone_or_email&diags=%7B%22pageViewId%22%3A%2214b945e6-8977-4d3e-a043-0da22f7d9acb%22%2C%22pageId%22%3A%22SelfAsserted%22%2C%22trace%22%3A%5B%7B%22ac%22%3A%22T005%22%2C%22acST%22%3A1693464336%2C%22acD%22%3A1%7D%2C%7B%22ac%22%3A%22T021%20-%20URL%3Ahttps%3A%2F%XXXX.azureedge.net%2Fsignintemplate%
Navigated to http://localhost:4200/
polyfills.js:1 [webpack-dev-server] Server started: Hot Module Replacement disabled, Live Reloading enabled, Progress disabled, Overlay enabled.
error
Error: Uncaught (in promise): Error: NG04002: Cannot match any routes. URL Segment: 'state%3DeyJpZCI6IjQwY2FhOTNlLTc1OTItNDA2ZS05NzAwLWRiYjIyZTExZWViYyIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicmVkaXJlY3QifX0%3D&client_info%3DeyJ1aWQiOiJhY2RkNWRmZS1lODg1LTQyMTItYWZhMy02NmNiM2NhMmNkNjItYjJjXzFhX21mYV9waG9uZV9vcl9lbWFpbCIsInV0aWQiOiJlZmJhOTVhZS01YWQ3LTQ2NmQtYmVkNy05YmY2ODYxYzYxYzgifQ&code%3DeyJraWQiOiI3VnI0NTlYZFE2NmxLcUFNM1hicFpHTDBYdVBjdlF1VHlaVE0zR2VnblRJIiwidmVyIjoiMS4wIiwiemlwIjoiRGVmbGF0ZSIsInNlciI6IjEuMCJ9.P8ZbBhskN4NuWpL5bEnRnEocsS_D5bXQy5242AgFg5KknW6pKvR9rIkQmdclXaMgv22YLDcFFSPIsPT396Wo0c88Q-6yB_IhQolF2qqYViSNNyTNsV8iuEAp3H1JglDyldSibolkFgsCmQYa3VBwQJG93tf3LELOCUOKvQ3t5Pfsg2cRTEPrr1zhHBMIsmtgC7W08-NskRGR7fIBXj0TJ6KrxpopxkdDzaqzJdxHw2crGiPEC6RjjpLwei5ONMR6Qkq0CRFUG9ed_blhqKVoEKeF_cYs1CGcOxXtm8NvOPZ5txgmTLhkbG8g-VLxiZM7S5mJxgh5bUy_pkJzwwUdcg.M8pbBSHPlz9UISRQ.AGPmGaRpgps1CbSQFaZmX0jXfwrH9C3D-vABMHVlZP3n2Hl2s2nBmhjN0w8H9l1MheJq_yAny3pmUnGLniDSa8XyntwQ7sqzqZe890ZvF7iORFOOdCB1g00-WWUhaDgqgMZaf46EhWZ7wpgsXyIj1rG67QyKUlB5jwjYXbjKBsR0PiiT5jgu7Ftc9VGuBjVkD1mUTuJE5czyeZi4T2fPec-N-QtXHEieLwi5hQBFAQUX8ud18ewEMbFExXaEcO6DRquYKHt73kXudDfMm_6N5VpZVDgfXRB0Ru575c4QnumoLUO1bn_Mh_r-P2uR4wM8u97XU91qIbFqRdmCdJ3i5BWujZWWyq20ChWNi7dhFIzmO9u6CAQv0Jmk39T47o_s-Yft2tbwhoD7lXNyy0ZPxfOBC92CGZycRurwnBfi-cBycbSImMTdAt058YEtYjRg-N1T_8U_cZBxbHJdI0bdI2xvJ9JrjgtxnOKfYG9nB8brPBKbBXK8Cc00wH0iHamibXd1OVyYlxs6F5_e9qRQvEvkNRQyzGLjxTdVIZak9vkF9m1t9-8Jqapc6HauokHkfcyOpWOMMldUX7929lotc9LCWcPdOHItHXyYLOWfb_2Blk7xBPMkcIpuzl48MF4NP75IGeXzE9XnTapzTI3E7k9zOR95M1YSaF2j3B2O1_DhLG0DiRSg7D2S7dosqK9nPLBlyKQeuQGISlEiEeYkBxohI6lbRC-1X9teaR-IQvQU7j6SQNkYQJZrDfT5Yol6nZGzJGJFrFgvQdt-tGUWurP23fHu6BTThtWenQAn.XGa4H31WVqU0F_LRW1kgrw'
Error: NG04002: Cannot match any routes. URL Segment: 'state%3DeyJpZCI6IjQwY2FhOTNlLTc1OTItNDA2ZS05NzAwLWRiYjIyZTExZWViYyIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicmVkaXJlY3QifX0%3D&client_info%3DeyJ1aWQiOiJhY2RkNWRmZS1lODg1LTQyMTItYWZhMy02NmNiM2NhMmNkNjItYjJjXzFhX21mYV9waG9uZV9vcl9lbWFpbCIsInV0aWQiOiJlZmJhOTVhZS01YWQ3LTQ2NmQtYmVkNy05YmY2ODYxYzYxYzgifQ&code%3DeyJraWQiOiI3VnI0NTlYZFE2NmxLcUFNM1hicFpHTDBYdVBjdlF1VHlaVE0zR2VnblRJIiwidmVyIjoiMS4wIiwiemlwIjoiRGVmbGF0ZSIsInNlciI6IjEuMCJ9.P8ZbBhskN4NuWpL5bEnRnEocsS_D5bXQy5242AgFg5KknW6pKvR9rIkQmdclXaMgv22YLDcFFSPIsPT396Wo0c88Q-6yB_IhQolF2qqYViSNNyTNsV8iuEAp3H1JglDyldSibolkFgsCmQYa3VBwQJG93tf3LELOCUOKvQ3t5Pfsg2cRTEPrr1zhHBMIsmtgC7W08-NskRGR7fIBXj0TJ6KrxpopxkdDzaqzJdxHw2crGiPEC6RjjpLwei5ONMR6Qkq0CRFUG9ed_blhqKVoEKeF_cYs1CGcOxXtm8NvOPZ5txgmTLhkbG8g-VLxiZM7S5mJxgh5bUy_pkJzww9u6CAQv0Jmk39T47o_s-Yft2tbwhoD7lXNyy0ZPxfOBC92CGZycRurwnBfi-cBycbSImMTdAt058YEtYjRg-N1T_8U_cZBxbHJdI0bdI2xvJ9JrjgtxnOKfYG9nB8brPBKbBXK8Cc00wH0iHamibXd1OVyYlxs6F5_e9qRQvEvkNRQyzGLjxTdVIZak9vkF9m1t9-8Jqapc6HauokHkfcyOpWOMMldUX7929lotc9LCWcPdOHItHXyYLOWfb_2Blk7xBPMkcIpuzl48MF4NP75IGeXzE9XnTapzTI3E7k9zOR95M1YSaF2j3B2O1_DhLG0DiRSg7D2S7dosqK9nPLBlyKQeuQGISlEiEeYkBxohI6lbRC-1X9teaR-IQvQU7j6SQNkYQJZrDfT5Yol6nZGzJGJFrFgvQdt-tGUWurP23fHu6BTThtWenQAn.XGa4H31WVqU0F_LRW1kgrw'
    at Recognizer.noMatchError (router.mjs:3655:16)
    at router.mjs:3670:28
    at catchError.js:10:39
    at OperatorSubscriber._error (OperatorSubscriber.js:23:21)
    at OperatorSubscriber.error (Subscriber.js:40:18)
    at OperatorSubscriber._error (Subscriber.js:64:30)
    at OperatorSubscriber.error (Subscriber.js:40:18)
    at OperatorSubscriber._error (Subscriber.js:64:30)
    at OperatorSubscriber.error (Subscriber.js:40:18)
    at OperatorSubscriber._error (Subscriber.js:64:30)
    at resolvePromise (zone.js:1193:31)
    at resolvePromise (zone.js:1147:17)
    at zone.js:1260:17
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at core.mjs:27127:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:27127:36)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Object.onInvokeTask (core.mjs:27437:33)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
    at Zone.runTask (zone.js:173:47)

### MSAL Configuration

```javascript
export function MSALInstanceFactory(): IPublicClientApplication {
  const msalConfig: Configuration = {
    auth: {
      clientId: ConfigService.configSettings?.clientID,
      authority:
        ConfigService.configSettings?.b2cPolicies.authorities.signIn.authority,
      navigateToLoginRequestUrl:
        ConfigService.configSettings?.navigateToLoginRequestUrl,
      redirectUri: ConfigService.configSettings?.redirectUri,
      postLogoutRedirectUri:
        ConfigService.configSettings?.postLogoutRedirectUri,
      knownAuthorities: ConfigService.configSettings?.knownAuthorities,
      authorityMetadata: '{"token_endpoint":"https://tenant.b2clogin.com/tenant.onmicrosoft.com/policy_name/oauth2/v2.0/token","token_endpoint_auth_methods_supported":["client_secret_post","private_key_jwt","client_secret_basic"],"jwks_uri":"https://login.microsoftonline.com/common/discovery/v2.0/keys","response_modes_supported":["query","fragment","form_post"],"subject_types_supported":["pairwise"],"id_token_signing_alg_values_supported":["RS256"],"response_types_supported":["code","id_token","code id_token","id_token token"],"scopes_supported":["openid","profile","email","offline_access"],"issuer":"https://login.microsoftonline.com/tenatId/v2.0","request_uri_parameter_supported":false,"userinfo_endpoint":"https://graph.microsoft.com/oidc/userinfo","authorization_endpoint":"https://tenant.b2clogin.com/tenant.onmicrosoft.com/B2C_1A_MFA_PHONE_OR_EMAIL/oauth2/v2.0/authorize","http_logout_supported":true,"frontchannel_logout_supported":true,"end_session_endpoint":"https://tenant.b2clogin.com/tenant.onmicrosoft.com/policy_name/oauth2/v2.0/logout","claims_supported":["sub","iss","cloud_instance_name","cloud_instance_host_name","cloud_graph_host_name","msgraph_host","aud","exp","iat","auth_time","acr","nonce","preferred_username","name","tid","ver","at_hash","c_hash","email"],"tenant_region_scope":null,"cloud_instance_name":"microsoftonline.com","cloud_graph_host_name":"graph.windows.net","msgraph_host":"graph.microsoft.com","rbac_url":"https://pas.windows.net"}'
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
      storeAuthStateInCookie: isIE // set to true for IE 11
    },
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Verbose,
        piiLoggingEnabled: false
      }
    }
  };
  return new PublicClientApplication(msalConfig);
}
```

### Relevant Code Snippets

```javascript
const routes: Routes = [
  {
    // Needed for hash routing

    path: 'error',
    component: AppComponent
  },
  {
    // Dedicated route for redirects
    path: 'auth',
    component: MsalRedirectComponent
  },
  {
    // Needed for hash routing

    path: '',
    component: Component1
  },
  {
    // Needed for hash routing
    path: 'state',
    canActivate: [MsalGuard],
    redirectTo: '',
    pathMatch: 'full'
  },
  {
    // Needed for hash routing
    path: 'code',
    canActivate: [MsalGuard],
    redirectTo: '',
    pathMatch: 'full'
  },
  {
    path: '',
    canActivate: [MsalGuard],
    redirectTo: '',
    pathMatch: 'full'
  },
  {
    path: 'register-user',
    component: RegisterUserComponent,
    pathMatch: 'full'
  },
  {
    path: 'abc',
    loadChildren: () =>
      import('./modules/abc/abc.module').then(
        (m) => m.abc
      )
  }
];

@NgModule({
  imports: [
    RouterModule.forRoot(routes, {
      paramsInheritanceStrategy: 'always',
      useHash: true,
      // Don't perform initial navigation in iframes or popups
      initialNavigation:
        !BrowserUtils.isInIframe() && !BrowserUtils.isInPopup()
          ? 'enabledBlocking'
          : 'disabled' // Remove this line to use Angular Universal
    })
  ],
  exports: [RouterModule]
})
```

### Reproduction Steps

1. User Logs in and provide username and password
2. Presented with MFA screen
3. After validating MFA again redirects to MFA screen

### Expected Behavior

User should be redirected to application home page after validating the details.

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
It seems that the Angular router is expecting exact matches. Try using a [custom matcher](https://angular.io/api/router/Route#properties) instead of an explicit path or including a wildcard route as a catch-all.

This seemed to work for me: 

```js
{
    component: RedirectComponent,
    matcher: (url) => {
      return url.length === 1 && (url[0].path.startsWith('code') || url[0].path.startsWith('state'))
        ? { consumed: url }
        : null;
    },
  },
```

This is more an Angular question than an MSAL question so I would encourage you to open an issue with Angular if you need further assistance.

**Comment by gultyayev** [comment]
> It seems that the Angular router is expecting exact matches. Try using a [custom matcher](https://angular.io/api/router/Route#properties) instead of an explicit path or including a wildcard route as a catch-all.
> 
> This seemed to work for me:
> 
> ```js
> {
>     component: RedirectComponent,
>     matcher: (url) => {
>       return url.length === 1 && (url[0].path.startsWith('code') || url[0].path.startsWith('state'))
>         ? { consumed: url }
>         : null;
>     },
>   },
> ```
> 
> This is more an Angular question than an MSAL question so I would encourage you to open an issue with Angular if you need further assistance.

It would be wonderful to have this as a recipe in the docs, or in some troubleshooting section. Frankly, not the first thing that comes to mind.
