### ISSUE TITLE
React 18 Support

### ISSUE THREAD

**Issue by askAguilr** [AzureAD/microsoft-authentication-library-for-js#6422]
### Core Library

MSAL.js (@azure/msal-browser)

### Wrapper Library

MSAL React (@azure/msal-react)

### Public or Confidential Client?

Public

### Description

Currently React 18 is not supported
<img width="463" alt="image" src="https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/105661698/73f7cb74-6409-46e2-bcba-6213fe864158">

Node version: 18
NPM version: 10

### Source

External (Customer)

**Comment by tnorling** [comment]
Msal-React [supports React versions 16.8+, including 18](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/39ff93c407886f9d3883f814d4439f36dba69b11/lib/msal-react/package.json#L51). Your @radixiot/react-cache-buster dependency does not support 18, which is what this error is for - please follow up with that package.
