### ISSUE TITLE
@azure/msal-angular 3.0.3 is an almost empty package

### ISSUE THREAD

**Issue by apmdsotl** [AzureAD/microsoft-authentication-library-for-js#6440]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.1.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.3

### Public or Confidential Client?

Public

### Description

Occurred previously in #6310

The msal-angular folder under node_modules only contains `LICENSE`, `package.json`, and `README.md`.
This causes any usage of the library to produce `Cannot find module '@azure/msal-angular' or its corresponding type declarations` and breaking the build.

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/96101792/9acedceb-e084-47e7-861c-e86e86424c08)

Renovate Bot shows the contents of the package being removed:
https://app.renovatebot.com/package-diff?name=@azure%2fmsal-angular&from=3.0.2&to=3.0.3

### MSAL Configuration

```javascript
{}
```

### Relevant Code Snippets

```javascript
`npm install @azure/msal-angular`
```

### Reproduction Steps

1. Upgrade `@azure/msal-angular` to 3.0.3

### Expected Behavior

`@azure/msal-angular` to have code

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer

### Regression

@azure/msal-angular 3.0.2

### Source

External (Customer)

**Comment by konstantin-msft** [comment]
Thank you @apmdsotl. Apologies for the inconvenience. Working on the fix now.

**Comment by Alex18gr** [comment]
Yes please fix that issue, it blocks our development we cannot deploy with this error. I had the same issue with every v3 subversion, stable, alpha or beta I tested.

**Comment by konstantin-msft** [comment]
`msal-angular@3.0.4` is released, while `msal-angular@3.0.3` is marked for unpublishing. Once again apologies for the inconvenience. Closing this.
