### ISSUE TITLE
@azure/msal-angular v3 is empty

### ISSUE THREAD

**Issue by OspinaJuan2000** [AzureAD/microsoft-authentication-library-for-js#6441]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.0.2

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.2

### Public or Confidential Client?

Public

### Description

Hello everyone, when I install the library @azure/msal-angular, in the node_modules it appears empty, so when I try to import any type of it, it does not work.

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/56393513/e233ba1b-d4d7-4bba-8b20-57a53b485675)

### MSAL Configuration

```javascript
...
```

### Relevant Code Snippets

```javascript
...
```

### Reproduction Steps

1. npm install @azure/msal-angular
2. try import MsalService or MsalModule, it does not work.

### Expected Behavior

That the import works.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Other

### Source

External (Customer)

**Comment by konstantin-msft** [comment]
Hi @OspinaJuan2000. Apologies for the inconvenience. `msal-angular@3.0.4` is released, while `msal-angular@3.0.3` is marked for unpublishing. Closing this.
