### ISSUE TITLE
Token is never returned from cache when there is no accessToken

### ISSUE THREAD

**Issue by Evertvdw** [AzureAD/microsoft-authentication-library-for-js#6451]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

2.1.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Confidential

### Description

I am trying to setup a confidential client app that uses a Redis cache. When doing the following call:
`const tokenResponse = await confidentialClientApp.acquireTokenSilent(silentRequest);`

It will always obtain a token from the network, as `tokenResponse.fromCache` is always false. Also when I time this step it always takes around 500ms to complete, which leaves me to believe that the cache is not used.

When I check the logs below I see that it can find an `idToken` in the cache but not an `accessToken`.:
```
[Fri, 08 Sep 2023 12:28:19 GMT] : [] : @azure/msal-node@2.1.0 : Info - getTokenCache called
[Fri, 08 Sep 2023 12:28:19 GMT] : [] : @azure/msal-common@14.0.3 : Info - CacheManager:getIdToken - Returning id token
[Fri, 08 Sep 2023 12:28:19 GMT] : [] : @azure/msal-common@14.0.3 : Info - CacheManager:getIdToken - Returning id token
[Fri, 08 Sep 2023 12:28:19 GMT] : [] : @azure/msal-node@2.1.0 : Info - getTokenCache called
[Fri, 08 Sep 2023 12:28:19 GMT] : [] : @azure/msal-common@14.0.3 : Info - CacheManager:getIdToken - Returning id token
[Fri, 08 Sep 2023 12:28:19 GMT] : [] : @azure/msal-node@2.1.0 : Verbose - initializeRequestScopes called
[Fri, 08 Sep 2023 12:28:19 GMT] : [07d04c86-7067-4e88-a423-0ee8bc6ed8df] : @azure/msal-node@2.1.0 : Verbose - buildOauthClientConfiguration called
[Fri, 08 Sep 2023 12:28:19 GMT] : [07d04c86-7067-4e88-a423-0ee8bc6ed8df] : @azure/msal-node@2.1.0 : Verbose - building oauth client configuration with the authority: ########################################
[Fri, 08 Sep 2023 12:28:19 GMT] : [07d04c86-7067-4e88-a423-0ee8bc6ed8df] : @azure/msal-node@2.1.0 : Verbose - createAuthority called
[Fri, 08 Sep 2023 12:28:19 GMT] : [] : @azure/msal-node@2.1.0 : Verbose - Attempting to get cloud discovery metadata  from authority configuration
[Fri, 08 Sep 2023 12:28:19 GMT] : [] : @azure/msal-node@2.1.0 : Verbose - The host is included in knownAuthorities. Creating new cloud discovery metadata from the host.
[Fri, 08 Sep 2023 12:28:19 GMT] : [] : @azure/msal-node@2.1.0 : Verbose - Found cloud discovery metadata in authority configuration
[Fri, 08 Sep 2023 12:28:19 GMT] : [] : @azure/msal-node@2.1.0 : Verbose - Attempting to get endpoint metadata from authority configuration
[Fri, 08 Sep 2023 12:28:19 GMT] : [] : @azure/msal-node@2.1.0 : Verbose - Did not find endpoint metadata in the config... Attempting to get endpoint metadata from the hardcoded values.
[Fri, 08 Sep 2023 12:28:19 GMT] : [] : @azure/msal-node@2.1.0 : Verbose - Did not find endpoint metadata in hardcoded values... Attempting to get endpoint metadata from the network metadata cache.
[Fri, 08 Sep 2023 12:28:19 GMT] : [] : @azure/msal-node@2.1.0 : Verbose - Found endpoint metadata in the cache.
[Fri, 08 Sep 2023 12:28:19 GMT] : [07d04c86-7067-4e88-a423-0ee8bc6ed8df] : @azure/msal-node@2.1.0 : Verbose - Silent flow client created
[Fri, 08 Sep 2023 12:28:19 GMT] : [] : @azure/msal-common@14.0.3 : Info - CacheManager:getIdToken - Returning id token
[Fri, 08 Sep 2023 12:28:19 GMT] : [] : @azure/msal-common@14.0.3 : Info - CacheManager:getAccessToken - No token found
[Fri, 08 Sep 2023 12:28:19 GMT] : [] : @azure/msal-common@14.0.3 : Info - CacheManager:getRefreshToken - returning refresh token
[Fri, 08 Sep 2023 12:28:19 GMT] : [07d04c86-7067-4e88-a423-0ee8bc6ed8df] : @azure/msal-common@14.0.3 : Info - SilentFlowClient:acquireCachedToken - No access token found in cache for the given properties.
[Fri, 08 Sep 2023 12:28:19 GMT] : [07d04c86-7067-4e88-a423-0ee8bc6ed8df] : @azure/msal-common@14.0.3 : Verbose - RefreshTokenClientAcquireTokenWithCachedRefreshToken called
[Fri, 08 Sep 2023 12:28:19 GMT] : [] : @azure/msal-common@14.0.3 : Info - CacheManager:getRefreshToken - returning refresh token
[Fri, 08 Sep 2023 12:28:19 GMT] : [07d04c86-7067-4e88-a423-0ee8bc6ed8df] : @azure/msal-common@14.0.3 : Verbose - RefreshTokenClientAcquireToken called
[Fri, 08 Sep 2023 12:28:20 GMT] : [07d04c86-7067-4e88-a423-0ee8bc6ed8df] : @azure/msal-common@14.0.3 : Verbose - Persistence enabled, calling beforeCacheAccess
[Fri, 08 Sep 2023 12:28:20 GMT] : [07d04c86-7067-4e88-a423-0ee8bc6ed8df] : @azure/msal-common@14.0.3 : Verbose - Persistence enabled, calling afterCacheAccess
```
 
I do not need the `accessToken` for my use case, I am only interested in the `idToken`. When doing `await confidentialClientApp.acquireTokenByCode` the tokenResponse there on login will also not include the `accessToken`. The scope I'm passing to the login/tokenrequests is `['openid']`. 

Is there a way to get the cache to work when there are no accessTokens involved? It seems that it will always try to refresh tokens when there is no accessToken, and in my case there never is. Or is there an easy way to make B2C return an accessToken so that the cache may work properly?

### Identity Provider

Azure B2C Custom Policy

### Source

Internal (Microsoft)

**Comment by konstantin-msft** [comment]
@bgavrilMS FYI. Please take a look when you get a chance.

**Comment by Evertvdw** [comment]
I did some digging in the source code myself, and found this on lines 119-126 in `src/client/ClientCredentialClient.ts`:
```ts
        // must refresh due to non-existent access_token
        if (!cachedAccessToken) {
            this.lastCacheOutcome = CacheOutcome.NO_CACHED_ACCESS_TOKEN;
            this.serverTelemetryManager?.setCacheOutcome(
                CacheOutcome.NO_CACHED_ACCESS_TOKEN
            );
            return null;
        }
```

Which seems to confirm my guess

**Comment by Evertvdw** [comment]
Any follow up? It has been a while

**Comment by bgavrilMS** [comment]
Yeah, MSAL is really focused on accessing protected APIs, not managing id tokens i.e. just signing in the user.

For example ASP.NET Core's middleware does this without MSAL help. But the Express samples we have use MSAL. 

Do you know if there there Express middleware that logs in users from an OIDC compliant directory (AAD is OAuth / OIDC complaint)?

**Comment by Evertvdw** [comment]
I'm not sure what you are asking me. I need to use a user flow in B2C and get an IdToken returned to me. And I would like to use the `msal-node` library to handle this process and also cache properly.

Could you explain to me how I can make it so that an accessToken is returned, so that caching will work as intented?

**Comment by bgavrilMS** [comment]
Hi @Evertvdw - the simplest is to define a fake scope in the Azure Portal. And instead of asking a token for "openid", ask a token for that scope. This will ensure you get cache hits. 

Alternatively, you can save the id token in the session and use it until it expires, at which point you ask MSAL for a new one. So you'd handle the lifetime yourself.

**Comment by Evertvdw** [comment]
@bgavrilMS Was some figuring out how to use a scopes in general but I managed to get it working. It will now return an accessToken so caching will also work as intended! Thanks!

**Comment by bgavrilMS** [comment]
Thank you for getting back to us and confirming.
