### ISSUE TITLE
 Can't clean cache or remove MSAL account (msal-angular)

### ISSUE THREAD

**Issue by israelbousquet** [AzureAD/microsoft-authentication-library-for-js#6453]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.5.10

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.25.0

### Public or Confidential Client?

Public

### Description

When the mailbox is either inactive, soft-deleted error occurs, it does not log in and returns an error, but it continues with the user token and account in cache.

When I try to log in again it does the same error account, instead of opening the prompt.

I wanted to know if there is any way to clear this cache to remove the account from MSAL 

### MSAL Configuration

```javascript
export function MSALInstanceFactory(): IPublicClientApplication {
  return new PublicClientApplication({
    auth: {
      clientId: OAuthSettings.appId,
      redirectUri: OAuthSettings.redirectUri,
      postLogoutRedirectUri: OAuthSettings.redirectUri,
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
    },
    system: {
      loggerOptions: {
        loggerCallback: (level: LogLevel, message: string, containsPii: boolean): void => {
          if (containsPii) {
            return;
          }
          switch (level) {
            case LogLevel.Error:
              return;
            case LogLevel.Info:
              return;
            case LogLevel.Verbose:
              return;
            case LogLevel.Warning:
              return;
          }
        },
        piiLoggingEnabled: false,
      },
      windowHashTimeout: 60000,
      iframeHashTimeout: 6000,
      loadFrameTimeout: 0,
    },
  });
}



@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    AppRoutingModule,
    MatSnackBarModule,
    MatDialogModule,
    FormsModule,
    ReactiveFormsModule,
    MatTooltipModule,
    MatAutocompleteModule,
    MatDatepickerModule,
    MatNativeDateModule,
    NgxColorsModule,
    NgxMaskModule.forRoot(),
    FlatpickrModule.forRoot(),
    NgxMaterialTimepickerModule.setLocale('pt-BR'),
    BrowserAnimationsModule,
    HttpClientModule,
    MsalModule,
  ],
  providers: [
    { provide: MAT_DATE_LOCALE, useValue: 'pt-BR' },
    {
      provide: MSAL_INSTANCE,
      useFactory: MSALInstanceFactory,
    },
    { provide: MatPaginatorIntl, useClass: MatPaginatorIntlCro },
    MsalService,
    NegociosDetailsComponent,
  ],
  bootstrap: [AppComponent],
})
export class AppModule {}
```

### Relevant Code Snippets

```javascript
constructor(private msalService: MsalService, private _snackBar: MatSnackBar) 

async signIn(): Promise<void> {
    try {
      const result = await this.msalService.instance.loginPopup(OAuthSettings);

      if (result) {
        this.authenticated = true;
        this.user = await this.getUser();
      }
    } catch (error: any) {
      const errorMsg = this.getErrorMessage(error.message);
      
      if (errorMsg.length) {
        this._snackBar.open(errorMsg, '', {
          duration: 4500,
        });
      }
    }
  }
```

### Reproduction Steps

1. Login with an account, the configuration of which returns an error
2. Try logging in again

### Expected Behavior

When trying to log in, and having an error, I hope that MSAL clears the cached accounts, so that the state returns to the original

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer

### Source

External (Customer)

**Comment by konstantin-msft** [comment]
Hi @israelbousquet.
MSAL does not clean up soft-deleted accounts by itself. Please use the [logout API](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md#L15) to wipe account data from the cache and then call the `acquireToken` API.

As an alternative approach you can force the server account selection screen by passing `select_account` prompt to the `acquireToken` or `login` APIs. Once you authorize the second account you can use the [setActiveAccount](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/accounts.md#active-account-apis) API to make `acquireToken` and `ssoSilent` APIs use it by default. Keep in mind that the first account will remain in the cache in this scenario.
