### ISSUE TITLE
Regression in metadata discovery after upgrading msal-common v13.1.0 to v14.0.2

### ISSUE THREAD

**Issue by koenigst** [AzureAD/microsoft-authentication-library-for-js#6456]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.0.2

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.2

### Public or Confidential Client?

Public

### Description

After upgrading the @azure/msal-common library the metadata discovery goes into an infinite loop.

### Error Message

GET https://login.microsoftonline.com/<redacted tenant id>/v2.0/v2.0/.well-known/openid-configuration net::ERR_FAILED 404 (Not Found)

### MSAL Configuration

```javascript
{
    auth: {
        authority: 'https://login.microsoftonline.com/<redacted tenant id>/v2.0',
        protocolMode: ProtocolMode.OIDC,
    },
}
```

### Relevant Code Snippets

```javascript
function MsalInstanceFactory(configuration): IPublicClientApplication {
    return new PublicClientApplication(configuration);
}
```

### Reproduction Steps

1. Initialize the PublicClientApplication with the provided authority
2. Request a login
3. Metadata discovery fails because the discovery endpoint has duplicate `v2.0` in URL.

### Expected Behavior

The discovery URL is correct (as was the behaviour with msal-common v13.1.0).

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox

### Regression

@azure/msal-common v13.1.0

### Source

External (Customer)

**Comment by konstantin-msft** [comment]
@koenigst Hello.
Thanks for bringing this up to our attention. [This PR](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/6342/files) causes a regression. Can you please remove `/v2.0` from `authority` URL as an interim solution while we are working on the fix?

**Comment by koenigst** [comment]
@konstantin-msft Thank you for the quick response! We will apply the suggested workaround until the fix becomes available.
