### ISSUE TITLE
Azure B2C - Behavior with Multiple Tabs after logout

### ISSUE THREAD

**Issue by Ronald123ol** [AzureAD/microsoft-authentication-library-for-js#6458]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.0.4

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.0-alpha.0

### Public or Confidential Client?

Public

### Description

My problem is that when I log out of my page in Angular and it redirects me to the login (b2c custom login), if the user has multiple tabs open and is logged out and tries to log in, b2c presents a bad request through the console bcs we know that b2c doesn't allow you interact with login in multiple tabs, but i was wondering how to manage that error?  users may get confused if they have that problem. I need to pass any property on the login request? 

### MSAL Configuration

```javascript
export const msalConfig: Configuration = {
  auth: {
    clientId: environment.azure_config.clientId,
    authority: environment.b2c_policies.authorities.signUpSignIn.authority,
    knownAuthorities: [environment.b2c_policies.authorityDomain],
    redirectUri: environment.azure_config.redirecturi,
    navigateToLoginRequestUrl: true,
  },
  cache: {
    cacheLocation: BrowserCacheLocation.LocalStorage,
    storeAuthStateInCookie: isIE,
  },
  system: {
    allowNativeBroker: false,
     loggerOptions: {
      loggerCallback(logLevel: LogLevel, message: string) {
        console.log(message);
      },
      logLevel: LogLevel.Verbose,
      piiLoggingEnabled: false
  },

};
```

### Relevant Code Snippets

```javascript
export const loginRequest = {

  scopes: ['openid'],
  state: "success",
  prompt: "login"
};

export function MSALGuardConfigFactory(): MsalGuardConfiguration {
  return {
    interactionType: InteractionType.Redirect,
    authRequest: loginRequest
  };
}


 logout() {
      const logoutRequest = {
        postLogoutRedirectUri: `${LocalEnvironmentPostLogoutUri}`,
      };

      this.authService.logoutRedirect(logoutRequest);


      this.logoutPageCommunicationService.sendLogoutSignal();
    }

  }
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by tnorling** [comment]
This is a question I would suggest you bring to [B2C support](https://learn.microsoft.com/en-us/azure/active-directory-b2c/find-help-open-support-ticket) as MSAL does not control this specific behavior/restriction or have any knowledge of it
