### ISSUE TITLE
Cannot convert msal loginPopup to loginRedirect react msal

### ISSUE THREAD

**Issue by MominMahmud** [AzureAD/microsoft-authentication-library-for-js#6460]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.30.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.9

### Public or Confidential Client?

Public

### Successful Scenario

 I am using Azure Adb2c SSO to sign in to my react application. I have implemented everything successfully I am using msalInstance.loginpopup() to display the Microsoft ADB2C popup for the login. Everything is working fine.

### Change
 
**Now I want to change the popup to redirect** but when I change it, It does redirect me to Microsoft ADB2C login page as expected but after successful sign in, redirects me back to the main login page of my application (where the user was initially when they pressed the login button).

### Issue

When I change it to redirect it does not go in to my **.then block in tryAgentLogin function** hence redirects me back to my original react login page

### MSAL Configuration

```javascript
const msalConfig = {
      auth: {
        clientId: ADB2C_CLIENT_ID,
        clientSecret: ADB2C_CLIENT_SECRET,
        authority: b2cPolicies.authorities.signUpSignIn.authority,
        knownAuthorities: [b2cPolicies.authorityDomain],
        validateAuthority: true,
        navigateToLoginRequestUrl: true,
      },
      cache: {
        cacheLocation: "sessionStorage",
        temporaryCacheLocation: "sessionStorage",
        storeAuthStateInCookie: false,
        secureCookies: false,
        claimsBasedCachingEnabled: true,
      },
      system: {
        pollIntervalMilliseconds: 1,
        windowHashTimeout: 60000,
        iframeHashTimeout: 6000,
        loadFrameTimeout: 0,
        asyncPopups: false,
        loggerOptions: {
          loggerCallback: (level, message, containsPii) => {
            if (containsPii) {
              return;
            }
            switch (level) {
              case LogLevel.Error:
                console.error(message);
                return;
              case LogLevel.Info:
                console.info(message);
                return;
              case LogLevel.Verbose:
                console.debug(message);
                return;
              case LogLevel.Warning:
                console.warn(message);
                return;
              default:
                return;
            }
          },
        },
      },
    };
```

### Relevant Code Snippets

```javascript
//This function is called when the login button of my react application login page is clicked 
const tryAgentLogin = () => {
    setPageLoading(true);
    message.info("Please enter your credentials in the login popup.");
    msalInstance 
      .loginPopup({                                        ** *//I change to loginRedirect here***
        redirectUri: ADB2C_AGENT_REDIRECT_URI,
        popupWindowAttributes: {
          popupSize: {
            height: window.innerHeight,
            width: window.innerWidth,
          },
          popupPosition: {
            left: 0,
            top: 0,
          },
        },
      })
      .then((res) => {
        console.log("TOKEN RETURNED BY ADB2C", res);
        LoginAgent(
          res.idToken,
          setAuth,
          navigate,
          routes,
          setPageLoading,
          msalInstance
        );
      });
  };


//Logout Function

export const LoginAgent = (
  accessToken,
  setAuth,
  navigate,
  routes,
  setPageLoading,
  msalInstance
) => {
  axios
    .get(`${BASE_URL}${GET_AGENT_CLAIM_DATA}`, {
      headers: {
        Authorization: `Bearer ${accessToken}`,
      },
    })
    .then((res) => {
      if (res?.data?.success) {
        setPageLoading(false);
        message.success("Login successful");
        setAuth(res?.data);
        initAxiosGlobalConfigs(res?.data);

        navigate(`${routes.AGENT_DASHBOARD}?page=1&pageSize=10`);
      } else {
        showUnauthorizedMessage(msalInstance, message, setPageLoading);
      }
    });
};
```

### Identity Provider

None

### Source

External (Customer)

**Comment by MominMahmud** [comment]
### Successful scenario of Popup **Verbose** Logs


[Tue, 12 Sep 2023 07:05:11 GMT] : [f184fb3f-5935-40fc-9970-4d6ebf85acdf] : @azure/msal-browser@2.38.0 : Info - PerformanceClient: No correlation id provided for initializeClientApplication, generating
authConfig.js:64 [Tue, 12 Sep 2023 07:05:11 GMT] : @azure/msal-browser@2.38.0 : Info - Emitting event: msal:initializeStart
authConfig.js:64 [Tue, 12 Sep 2023 07:05:11 GMT] : @azure/msal-browser@2.38.0 : Info - Emitting event: msal:initializeEnd
authConfig.js:64 [Tue, 12 Sep 2023 07:05:11 GMT] : @azure/msal-browser@2.38.0 : Info - initialize has already been called, exiting early.
authConfig.js:64 [Tue, 12 Sep 2023 07:05:11 GMT] : @azure/msal-browser@2.38.0 : Info - Emitting event: msal:handleRedirectStart
authConfig.js:64 [Tue, 12 Sep 2023 07:05:11 GMT] : [8f2c9ef5-3212-424d-b267-bc6ae9e5458b] : msal.js.browser@2.38.0 : Info - handleRedirectPromise called but there is no interaction in progress, returning null.
authConfig.js:64 [Tue, 12 Sep 2023 07:05:11 GMT] : @azure/msal-browser@2.38.0 : Info - Emitting event: msal:handleRedirectEnd
authConfig.js:64 [Tue, 12 Sep 2023 07:05:11 GMT] : @azure/msal-react@1.5.9 : Info - MsalProvider - msal:handleRedirectStart results in setting inProgress from startup to handleRedirect
authConfig.js:64 [Tue, 12 Sep 2023 07:05:11 GMT] : @azure/msal-react@1.5.9 : Info - MsalProvider - msal:handleRedirectEnd results in setting inProgress from handleRedirect to none
authConfig.js:64 [Tue, 12 Sep 2023 07:05:11 GMT] : @azure/msal-react@1.5.9 : Info - MsalProvider - msal:handleRedirectStart results in setting inProgress from startup to handleRedirect
authConfig.js:64 [Tue, 12 Sep 2023 07:05:11 GMT] : @azure/msal-react@1.5.9 : Info - MsalProvider - msal:handleRedirectEnd results in setting inProgress from handleRedirect to none
DevTools failed to load source map: Could not load content for chrome-extension://gkkdmjjodidppndkbkhhknakbeflbomf/polyfills/browser-polyfill.min.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://fheoggkfdfchfphceeifdbepaooicaho/sourceMap/chrome/scripts/iframe_form_check.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
warning.js:6 Warning: [antd: message] Static function can not consume context like dynamic theme. Please use 'App' component instead.
warning @ warning.js:6
call @ warning.js:20
warningOnce @ warning.js:25
warning @ warning.js:8
warnContext @ index.js:34
typeOpen @ index.js:189
staticMethods.<computed> @ index.js:236
tryAgentLogin @ index.js:73
handleClick @ button.js:124
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
(anonymous) @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
dispatchDiscreteEvent @ react-dom.development.js:6430

### 
### When the login button is clicked on my react application


authConfig.js:64 [Tue, 12 Sep 2023 07:59:44 GMT] : @azure/msal-browser@2.38.0 : Info - Emitting event: msal:loginStart
index.js:50 ADB2C {eventType: 'msal:loginStart', interactionType: 'popup', payload: {…}, error: null, timestamp: 1694505584603}
index.js:50 ADB2C {eventType: 'msal:loginStart', interactionType: 'popup', payload: {…}, error: null, timestamp: 1694505584603}
index.js:50 ADB2C {eventType: 'msal:loginStart', interactionType: 'popup', payload: {…}, error: null, timestamp: 1694505584603}
index.js:50 ADB2C {eventType: 'msal:loginStart', interactionType: 'popup', payload: {…}, error: null, timestamp: 1694505584603}
authConfig.js:64 [Tue, 12 Sep 2023 07:59:44 GMT] : @azure/msal-react@1.5.9 : Info - MsalProvider - msal:loginStart results in setting inProgress from none to login
authConfig.js:64 [Tue, 12 Sep 2023 07:59:44 GMT] : @azure/msal-react@1.5.9 : Info - MsalProvider - msal:loginStart results in setting inProgress from none to login
authConfig.js:64 [Tue, 12 Sep 2023 07:59:46 GMT] : @azure/msal-browser@2.38.0 : Info - Emitting event: msal:popupOpened
index.js:50 ADB2C {eventType: 'msal:popupOpened', interactionType: 'popup', payload: {…}, error: null, timestamp: 1694505586772}
index.js:50 ADB2C {eventType: 'msal:popupOpened', interactionType: 'popup', payload: {…}, error: null, timestamp: 1694505586772}
index.js:50 ADB2C {eventType: 'msal:popupOpened', interactionType: 'popup', payload: {…}, error: null, timestamp: 1694505586772}
index.js:50 ADB2C {eventType: 'msal:popupOpened', interactionType: 'popup', payload: {…}, error: null, timestamp: 1694505586772}
index.js:50 ADB2C {eventType: 'msal:popupOpened', interactionType: 'popup', payload: {…}, error: null, timestamp: 1694505586772}
index.js:50 ADB2C {eventType: 'msal:popupOpened', interactionType: 'popup', payload: {…}, error: null, timestamp: 1694505586772}
authConfig.js:64 [Tue, 12 Sep 2023 07:59:49 GMT] : [32e11815-c5e1-45ef-903e-c9a12e98e704] : @azure/msal-common@13.2.0 : Info - in acquireToken call in auth-code client
authConfig.js:64 [Tue, 12 Sep 2023 07:59:50 GMT] : @azure/msal-browser@2.38.0 : Info - BrowserCacheManager: addTokenKey - idToken added to map
authConfig.js:64 [Tue, 12 Sep 2023 07:59:50 GMT] : @azure/msal-browser@2.38.0 : Info - BrowserCacheManager: addTokenKey - refreshToken added to map
authConfig.js:64 [Tue, 12 Sep 2023 07:59:50 GMT] : @azure/msal-common@13.2.0 : Info - CacheManager:getIdToken - Returning id token
authConfig.js:64 [Tue, 12 Sep 2023 07:59:50 GMT] : @azure/msal-browser@2.38.0 : Info - Emitting event: msal:loginSuccess
index.js:50 ADB2C {eventType: 'msal:loginSuccess', interactionType: 'popup', payload: {…}, error: null, timestamp: 1694505590526}
index.js:50 ADB2C {eventType: 'msal:loginSuccess', interactionType: 'popup', payload: {…}, error: null, timestamp: 1694505590526}
index.js:50 ADB2C {eventType: 'msal:loginSuccess', interactionType: 'popup', payload: {…}, error: null, timestamp: 1694505590526}
index.js:50 ADB2C {eventType: 'msal:loginSuccess', interactionType: 'popup', payload: {…}, error: null, timestamp: 1694505590526}
index.js:50 ADB2C {eventType: 'msal:loginSuccess', interactionType: 'popup', payload: {…}, error: null, timestamp: 1694505590526}
index.js:50 ADB2C {eventType: 'msal:loginSuccess', interactionType: 'popup', payload: {…}, error: null, timestamp: 1694505590526}







### **### AFTER SUCCESSFULL LGOIN IN POPUP**











index.js:89 TOKEN RETURNED BY ADB2C {authority: <tenant>/b2c_1a_signup_signin_agent/', (OTHER INFORMATION) scopes: Array(0), account: {…}, …}
authConfig.js:64 [Tue, 12 Sep 2023 07:59:50 GMT] : @azure/msal-react@1.5.9 : Info - MsalProvider - msal:loginSuccess results in setting inProgress from login to none
authConfig.js:64 [Tue, 12 Sep 2023 07:59:50 GMT] : @azure/msal-common@13.2.0 : Info - CacheManager:getIdToken - Returning id token
authConfig.js:64 [Tue, 12 Sep 2023 07:59:50 GMT] : @azure/msal-react@1.5.9 : Info - MsalProvider - msal:loginSuccess results in setting inProgress from login to none
authConfig.js:64 [Tue, 12 Sep 2023 07:59:50 GMT] : @azure/msal-common@13.2.0 : Info - CacheManager:getIdToken - Returning id token
authConfig.js:64 [Tue, 12 Sep 2023 07:59:50 GMT] : [18f7d309-1f4d-4e65-9e2f-bd77b380866e] : @azure/msal-browser@2.38.0 : Info - PerformanceClient: No correlation id provided for initializeClientApplication, generating
authConfig.js:64 [Tue, 12 Sep 2023 07:59:50 GMT] : @azure/msal-browser@2.38.0 : Info - Emitting event: msal:initializeStart
authConfig.js:64 [Tue, 12 Sep 2023 07:59:50 GMT] : @azure/msal-browser@2.38.0 : Info - Emitting event: msal:initializeEnd
2authConfig.js:64 [Tue, 12 Sep 2023 07:59:50 GMT] : @azure/msal-common@13.2.0 : Info - CacheManager:getIdToken - No token found
2authConfig.js:64 [Tue, 12 Sep 2023 07:59:50 GMT] : @azure/msal-common@13.2.0 : Info - CacheManager:getIdToken - No token found
authConfig.js:64 [Tue, 12 Sep 2023 07:59:50 GMT] : @azure/msal-common@13.2.0 : Info - CacheManager:getIdToken - No token found
authConfig.js:64 [Tue, 12 Sep 2023 07:59:50 GMT] : @azure/msal-browser@2.38.0 : Info - Emitting event: msal:handleRedirectStart
authConfig.js:64 [Tue, 12 Sep 2023 07:59:50 GMT] : [7acca845-c571-40d4-a7aa-27b1d906539b] : msal.js.browser@2.38.0 : Info - handleRedirectPromise called but there is no interaction in progress, returning null.
authConfig.js:64 [Tue, 12 Sep 2023 07:59:50 GMT] : @azure/msal-browser@2.38.0 : Info - Emitting event: msal:handleRedirectEnd
authConfig.js:64 [Tue, 12 Sep 2023 07:59:50 GMT] : @azure/msal-react@1.5.9 : Info - MsalProvider - msal:handleRedirectStart results in setting inProgress from none to handleRedirect
authConfig.js:64 [Tue, 12 Sep 2023 07:59:50 GMT] : @azure/msal-common@13.2.0 : Info - CacheManager:getIdToken - No token found
authConfig.js:64 [Tue, 12 Sep 2023 07:59:50 GMT] : @azure/msal-react@1.5.9 : Info - MsalProvider - msal:handleRedirectEnd results in setting inProgress from handleRedirect to none
2authConfig.js:64 [Tue, 12 Sep 2023 07:59:50 GMT] : @azure/msal-common@13.2.0 : Info - CacheManager:getIdToken - No token found
authConfig.js:64 [Tue, 12 Sep 2023 07:59:50 GMT] : @azure/msal-react@1.5.9 : Info - MsalProvider - msal:handleRedirectStart results in setting inProgress from none to handleRedirect
authConfig.js:64 [Tue, 12 Sep 2023 07:59:50 GMT] : @azure/msal-common@13.2.0 : Info - CacheManager:getIdToken - No token found
authConfig.js:64 [Tue, 12 Sep 2023 07:59:50 GMT] : @azure/msal-react@1.5.9 : Info - MsalProvider - msal:handleRedirectEnd results in setting inProgress from handleRedirect to none
2authConfig.js:64 [Tue, 12 Sep 2023 07:59:50 GMT] : @azure/msal-common@13.2.0 : Info - CacheManager:getIdToken - No token found

**Comment by hectormmg** [comment]
@MominMahmud when the browser redirects away from your app the execution thread is broken so any code after the acquireTokenRedirect call will not be executed. If you want to customize which page to redirect to, you can either make it your redirect URI location or use the [redirectStartPage](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/6eaf83f4abff2e6f89bd952c27fea7d6d0d9099a/lib/msal-browser/src/request/RedirectRequest.ts#L48) request config option.

**Comment by MominMahmud** [comment]
Thank you @hectormmg for explaining the issue, As you can see I am already using the `redirectUri` config option when calling the` .loginRedirect `function that is [](http://localhost:3000/agent-dashboard/) The page it takes to when successful login. Shown below: 
```
msalInstance
      .loginRedirect({
        redirectUri: ADB2C_AGENT_REDIRECT_URI,
        popupWindowAttributes: {
          popupSize: {
            height: window.innerHeight,
            width: window.innerWidth,
          },
          popupPosition: {
            left: 0,
            top: 0,
          },
        },
      })
```

Now I am using the `redirectstartPage `with the same `url `as `redirectUri `   _but It has the same behavior._ 

```
msalInstance
      .loginRedirect({
        redirectUri: ADB2C_AGENT_REDIRECT_URI,
        redirectStartPage: ADB2C_AGENT_REDIRECT_URI,
```


I also tried using the `redirectstartPage `option in the `authConfig` shown below:-> **but still same behavior of routing back to the `loginPage `of my react app rather than routing to the application agent dashboard that I set as in `redirectUri `and `redirectStartPage`** 

```
const msalConfig = {
      auth: {
        clientId: ADB2C_CLIENT_ID,
        clientSecret: ADB2C_CLIENT_SECRET,
        authority: b2cPolicies.authorities.signUpSignIn.authority,
        knownAuthorities: [b2cPolicies.authorityDomain],
        validateAuthority: true,
        navigateToLoginRequestUrl: true,
        redirectStartPage: ADB2C_AGENT_REDIRECT_URI,
      },
      cache: {
        cacheLocation: "sessionStorage",
        temporaryCacheLocation: "sessionStorage",
        storeAuthStateInCookie: false,
        secureCookies: false,
        claimsBasedCachingEnabled: true,
      },
```


Still issue persists........

**Comment by tnorling** [comment]
Please set the `navigateToLoginRequestUrl` config parameter to `false` if the path where you start the flow is different from the path where you want to end the flow.
