### ISSUE TITLE
MSAL Authentication: Auto-Logout and Account Switching Across Apps

### ISSUE THREAD

**Issue by SanBri** [AzureAD/microsoft-authentication-library-for-js#6464]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.37.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.5.7

### Public or Confidential Client?

Public

### Description

I'm using msal.js with React for authentication in my apps. Here's the issue:
I have a primary app named "app-redirect" that redirects to a second app, let's call it "app-web".
Both apps use "MSAL" for authentication.
I can log into "app-web" directly without going through "app-redirect" first. Their authentication works independently.
When I sign into "app-redirect", it automatically redirects me to "app-web", which doesn't prompt me for a new login since it recognizes the credentials from "app-redirect".

Considering this setup, here's the problem:
Say I first log into "app-web" with an account, let's name it "Paul's Account". Then, in the same browser window without logging out of "app-web", I log into "app-redirect" with a different account, say "Manon's Account". The automatic redirect from "app-redirect" will take me back to "app-web" as expected. But the catch is, I'm still logged in with "Paul's Account" and not "Manon's Account" as intended.

How can I make sure that when I log in with a different account on "app-redirect", "app-web" recognizes it and switches to that account automatically?

### MSAL Configuration

```javascript
auth: {
    clientId: ${client_ID},
    knownAuthorities: ["${app_name}.b2clogin.com"],
    authority: "https://${app_name}.b2clogin.com/${app_name}.onmicrosoft.com/B2C_1_susi/",
    redirectUri: `/`,
  },
  cache: {
    cacheLocation: 'localStorage'
  }
```

### Relevant Code Snippets

```javascript
instance.logout({
                authority: "https://${app_name}.b2clogin.com/${app_name}.onmicrosoft.com/B2C_1_susi/",
                postLogoutRedirectUri: `my_redirection_url_after_logout`,
            });
```

### Identity Provider

None

### Source

External (Customer)

**Comment by hectormmg** [comment]
@SanBri you can use the `setActiveAccount()` API to pass Manon's account from the AuthResponse wherever you process the redirect. This will set "Manon's Account" as active account, so when you call `getActiveAccount()` it will give you Manon's. However, this will not log "Paul's account" out. You must explictily call "logout(paul's account)" to achieve that.
