### ISSUE TITLE
B2C login timeout after App Service deployment slot swap

### ISSUE THREAD

**Issue by leskodan** [AzureAD/microsoft-authentication-library-for-js#6466]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.30.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.5.0

### Public or Confidential Client?

Public

### Description

We are using msal-browser along with msal-react to implement auth in our next.js application with Azure AD B2C. Our next.js application is hosted on Azure App Service (runtime node 18). We deploy code changes via a github action to a staging slot and then swap the staging slot with our production slot to release the changes.

We have a single App Registrant in our B2C tenant that is shared by both deployment slots. The B2C configs are provided to our application via configuration values and fetched as server-side props. 

Intermittently, about an hour after performing a swap (for changes unrelated to auth), the connection between our app and B2C will seemingly break as the login request will timeout and result in a B2C error. We do not observe any errors in our application code and the issue recovers on its own after 15-30mins.

### Error Message

![image (11)](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/51446532/4de690b6-d048-4bac-a95c-faa44eb19dcb)

The error in the console states that the requested service has either moved, had a name change, or been deleted even though no changes to the B2C configuration values or app registrant have been made.

### Msal Logs

No logs available.

### MSAL Configuration

```javascript
const msalConfig: Configuration = {
        auth: {
            clientId: serverRuntimeConfig.AUTH_CLIENT_ID,
            authority: serverRuntimeConfig.AUTH_AUTHORITY,
            knownAuthorities: [serverRuntimeConfig.AUTH_KNOWN_AUTHORITY],
            redirectUri: '/',
            postLogoutRedirectUri: '/',
            navigateToLoginRequestUrl: true,
        },
    };
```

### Relevant Code Snippets

```javascript
Doesn't seem to be isolated to a specific section of code.
```

### Reproduction Steps

This occurs intermittently, but the repro steps include:
1. Deploy code change to staging slot (changes unrelated to auth configuration)
2. Swap staging slot with production slot (no auth configuration changes, i.e. auth configuration identical in both slots)
3. Attempt to reauthenticate with app-- encounter B2C timeout error
4. Repeat step 3 until you are able to successfully authenticate with B2C

### Expected Behavior

There should be zero downtime for the B2C connection when performing an App Service deployment slot swap.

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by hectormmg** [comment]
@leskodan this sounds like a B2C service issue, MSAL has no influence on the service side. Please open a support ticket with the B2C team instead. Check this [link](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md#what-should-i-do-if-i-believe-my-issue-is-with-the-b2c-service-itself-rather-than-with-the-library) out for more information on raising a B2C service ticket.
