### ISSUE TITLE
Integration testing with @azure/msal-node

### ISSUE THREAD

**Issue by williamdclt** [AzureAD/microsoft-authentication-library-for-js#6470]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.18.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Confidential

### Description

I am trying to figure out how to test my Node application. It's using MSAL for SSO, which a custom Postgres-based distributed token cache.

I'd like to write integration tests for our login flow. In particular:

- I don't want to actually call Azure on `acquireTokenByCode` or `acquireTokenSilent`: I want to mock the auth response
- I _do_ want the token caching to be part of the test. It's non-trivial and somewhat byzantine to wire up, probably would be a main source of bugs if untested.

`@azure/msal-browser` has a [testing doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/testing.md) which points to a `loadExternalTokens` API. It seems perfect for what I want to do, but this API doesn't exist in `@azure/msal-node`.

Is there a reason there's no such API? Is there a different recommended way of doing integration testing?

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by hectormmg** [comment]
@williamdclt the reason it doesn't exist on MSAL Node is that tokens can easily be sideloaded by leveraging the [cachePlugin](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/6eaf83f4abff2e6f89bd952c27fea7d6d0d9099a/lib/msal-node/src/config/Configuration.ts#L59) option. You should be able to acquire tokens out-of-band and decide how you want to feed them to the cache (like through a JSON file like in our samples)

**Comment by williamdclt** [comment]
> tokens can easily be sideloaded by leveraging the [cachePlugin](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/6eaf83f4abff2e6f89bd952c27fea7d6d0d9099a/lib/msal-node/src/config/Configuration.ts#L59) option

I don't think that solves what I am trying to do. I am calling `acquireTokenByCode`, and need to avoid it sending an actual HTTP request to Azure, it's unrelated to the cache. In fact, pre-loading the cache is something I do _not_ want to do: the saving and retrieving is part of what is being tested.

Ideally what I'd like to be able to do is to mock the HTTP requests made by `acquireTokenByCode`: "for this given authorization code, use this hardcoded response", this hardcoded response then being cached normally.

**Comment by bgavrilMS** [comment]
I don't think there is a way to automate this sort of end to end testing. I wrote a doc for MSAL.NET, but it is relevant to all MSALs. Have a look: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Testing-an-app-using-MSAL

**Comment by williamdclt** [comment]
> I don't think there is a way to automate this sort of end to end testing

(a nitpick but I want to make sure I make my case clearly: it's not really end-to-end testing as I do want to mock out azure.com)

There's no fundamental blocker to allow this sort of testing. It is not straightforward for the same reason as other users have complained in other issues (https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5854, https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5748, https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/6079): this token cache concept has an awkward API, the abstraction is leaky, and it's lacks decoupling. 

To give concrete feedback, what I would expect from a library like this would be that the caching layer and the API layer are separate, so that one can be mocked while keeping the other. I'd expect to instantiate a `ConfidentialClientApplication` using token caching somewhat like this:

```ts
	// acquireTokenSilent always refreshes.
    const client = new msal.ConfidentialClientApplication({
      auth: { ... },
      system: { ... },
    });

	// CachedClientApplication also implements IConfidentialClientApplication
	// acquireTokenSilent uses the cache, fallbacks to client.acquireTokenSilent
	const cachedClient = new msal.CachedClientApplication({
		client: client,
		cache: new msal.DistributedCache(...),
	});
```

For testing, I could then just create my own mock of `ConfidentialClientApplication`:

```ts
    const mockClient = new MockClientApplication();
	const cachedClient = new msal.CachedClientApplication({
		client: mockClient,
		cache: new msal.DistributedCache(...),
	});

	// ... in my test
	mockClient.acquireTokenByCode.mockResolvedValue(...)
	const response = await request(myServer).post('/oauth/authorize') // does not call azure, but my mock instead
	// ... assertions etc
```

We could go a bit deeper and extract a "simple OAuth2" layer, which doesn't have any Azure-specific behaviour so that I can keep the microsoft-specific layer in my testing and just stub the OAuth2 layer. But I'd already be happy without that.

This would have a number of advantages:

- I can mock the HTTP client without mocking the caching behaviour, which is important for testing
- I don't need to recreate a `ConfidentialClientApplication` at each request (which is necessary ATM because [the cachePlugin needs to be created per-user which is very awkward](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/4392a636c2d340394949b46c866a5b9895fc195e/samples/msal-node-samples/auth-code-distributed-cache/src/AuthProvider.ts#L69-L79))
- Devs wouldn't _have_ to use the caching layer, it'd be an optional abstraction (could be moved to msal-node-extensions) while keeping azure-specific behaviour
	- Given the frustration around token caching, making it optional would be a good thing.

**Comment by bgavrilMS** [comment]
Thanks for your feedback @williamdclt, I agree with this assessment and it is on the backlog / vision to get there. This is mostly done for MSAL .NET btw, but we need to put more effort into the other MSALs. 

A few points: 

- Why is creating a new instance of ConfidentialClientApplication on a per session, per user or even per request basis a problem?  Do web site middleware make it easier to deal with singletons?
- AAD is standards compliant, it's been certified OIDC / OAuth. Any OIDC library will work with it. MSAL helps with multi-tenancy (but most ppl will use a single tenant) and token caching logic, access token management etc. 
- Token caching is optional. It's an opt in feature. Particularly for the web site scenario, there are cookies set in AAD by the browser which ensure that users don't get re-prompted for passwords. So even if you don't an access token, you can just go through the authorization flow (auth_code) to get one and it will be fast.

**Comment by williamdclt** [comment]
> Why is creating a new instance of ConfidentialClientApplication on a per session, per user or even per request basis a problem?

It's not a _problem_ per se, it's unexpected and confusing: the common pattern is to have a singleton and passing the cache key as argument when calling methods, rather than having it part of the constructor. Having to create an MSAL instance per request means that:

- I have to spend time to discover that this is what I need to do, as this is an unusual pattern
- I have to worry about whether instantiating MSAL instances is costly

> Token caching is optional. It's an opt in feature.

It comes down to saying "refresh tokens are optional": sure I could ask the user to relogin every time the access token expires, but this is a massive trade-off for usability which really makes it a no-go. I don't want to give up on refreshing tokens, I'm just disatisfied by the idiosyncrasies that MSAL forces me to go through!

**Comment by williamdclt** [comment]
This issue is not resolved, it's still not possible to do integration testing with msal-node. Can we re-open this issue?

**Comment by bgavrilMS** [comment]
You can prime the token cache by using `AcquireTokenForUsernamePassword`. This is how many apps do their integration testing today. It is semantically equivalent to `loadExternalTokens`. 

There is no way to automate the browser though. You can't inject a cookie via an automated process unless you do Selenium type testing and ensure that the user under test is excluded from MFA.
