### ISSUE TITLE
Unicode string(japanese-strting) use atob is getting error . (Regression)

### ISSUE THREAD

**Issue by magnet163** [AzureAD/microsoft-authentication-library-for-js#6476]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.1.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.4

### Public or Confidential Client?

Public

### Description

The following error has recurred.
Since @azure/msal-browser 3.1.0, I am getting occasional errors when Japanese characters are included.
https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/985

### Error Message

[1694663603412.log](https://github.com/AzureAD/microsoft-authentication-library-for-js/files/12604560/1694663603412.log)

### MSAL Configuration

```javascript
auth: {
   clientId: "XXXXXX",
   authority: "https://login.microsoftonline.com/common/",
   redirectUri: "/auth/signin",
   postLogoutRedirectUri: "/auth/signin"
 },
 cache: {
   cacheLocation: BrowserCacheLocation.LocalStorage,
   storeAuthStateInCookie: false
 },
 system: {
   allowNativeBroker: false
 }
```

### Relevant Code Snippets

```javascript
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { MsalService } from '@azure/msal-angular';

@Component({
  selector: 'app-signin',
  standalone: true,
  imports: [
    CommonModule,
  ],
  templateUrl: './signin.component.html',
  styleUrls: ['./signin.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SigninComponent {
  readonly #msalService = inject(MsalService);

  constructor() {
    this.#msalService.handleRedirectObservable().subscribe();
  }

  signIn() {
    this.#msalService.loginPopup()
      .subscribe(res => {
      });
  }
}
```

### Reproduction Steps

1. Signin Japanese DisplayName account.
2. Execute signIn method.

However, it does not always result in an error, and in rare cases it may succeed.

### Expected Behavior

Non Error decode.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge

### Regression

@azure/msal-browser 3.0.2

### Source

External (Customer)

**Comment by tnorling** [comment]
This has been fixed in version 3.2.0
