### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by clementSabattie** [AzureAD/microsoft-authentication-library-for-js#6477]
### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Public or Confidential Client?

Public

### Documentation Location

dead link

### Description

there is a dead link [here]( https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/a596d3ddd3ad48a58814ba575cd37b14302ed540/lib/msal-angular/docs/events.md?plain=1#L3)

clicking on the link lead to a 404 - page not found

**Comment by hectormmg** [comment]
Thanks for reporting this, it has been addressed in #6479
