### ISSUE TITLE
Disable MSA

### ISSUE THREAD

**Issue by pieterdv** [AzureAD/microsoft-authentication-library-for-js#65]
Is there a possibility to disable Microsoft Account to login, so to only use AAD account as login option?

**Comment by jmprieur** [comment]
No @pieterdv, msal is about the converged endpoint, which offers authentication for both AAD and MSA. If you want only AAD, you probably want to use [ADAL.js](https://github.com/AzureAD/azure-activedirectory-library-for-js).

**Comment by pieterdv** [comment]
I was in the believe that MSAL is the future library and ADAL.js is going to be phased out? So MSAL and ADAL will be maintained a long each other?

**Comment by jmprieur** [comment]
Yes, for the moment, until the converged endpoint ([AAD V2](https://aka.ms/aadv2)) supports all the scenarios that the V1 endpoint supports

**Comment by pieterdv** [comment]
Ok, my question was more a feature request, not something I need right away. The possibility to only login to AAD will come to MSAL in the future? If so my question is answered. Thanks!
