### ISSUE TITLE
Issue with MSAL Upgrade from v2 to v3 in angular project v15

### ISSUE THREAD

**Issue by Laharikota07** [AzureAD/microsoft-authentication-library-for-js#6500]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

^3.1.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

^3.0.4

### Public or Confidential Client?

Public

### Description

Upgraded version and then i got error for as "BrowserAuthError: uninitialized_public_client_application: You must call and await the initialize function before attempting to call any other MSAL API.  For more visit: aka.ms/msaljs/browser-errors"...then i reffered doc and fixed initialization issue
After fixing it i get error as appconfig.service.ts:17  ERROR TypeError: this.instance.initializeWrapperLibrary is not a function
    at new MsalService (azure-msal-angular.mjs:35:23)
    at Object.MsalService_Factory [as factory] (azure-msal-angular.mjs:88:17)
    at R3Injector.hydrate (core.mjs:8015:35)
    at R3Injector.get (core.mjs:7903:33)
    at ChainedInjector.get (core.mjs:12084:36)
    at lookupTokenUsingModuleInjector (core.mjs:3201:39)
    at getOrCreateInjectable (core.mjs:3246:12)
    at Module.ɵɵdirectiveInject (core.mjs:10041:12)
    at NodeInjectorFactory.LayoutComponent_Factory [as factory] (layout.component.ts:19:29)
    at getNodeInjectable (core.mjs:3431:44)

if i try to fix i am getting Circular DI and errors are not ending as fixing one issue giving other issue.

### Identity Provider

None

### Source

External (Customer)

**Comment by stefanvettiger** [comment]
I have a similar error. I'm getting also circular DI error for MsalBroadcastService. But this only happens when i test my application NOT on http://localhost:4200. The problem occurs with the following library versions:

- "@azure/msal-angular": "^3.0.4",
- "@azure/msal-browser": "^3.1.0"

When i force to use the following versions, everything works well (Note: delete package-lock.json and recreate to force using the correct versions!!!):

- "@azure/msal-angular": "3.0.4",
- "@azure/msal-browser": "3.0.2"

```
ERROR Error: NG0200: Circular dependency in DI detected for MsalBroadcastService. Find more at https://angular.io/errors/NG0200
    at throwCyclicDependencyError (core.mjs:228:11)
    at R3Injector.hydrate (core.mjs:9426:13)
    at R3Injector.get (core.mjs:9301:33)
    at ChainedInjector.get (core.mjs:14001:36)
    at lookupTokenUsingModuleInjector (core.mjs:4504:39)
    at getOrCreateInjectable (core.mjs:4552:12)
    at Module.ɵɵdirectiveInject (core.mjs:11784:19)
    at NodeInjectorFactory.NavbarComponent_Factory [as factory] (navbar.component.ts:23:29)
    at getNodeInjectable (core.mjs:4758:44)
    at instantiateAllDirectives (core.mjs:12612:27)
```

**Comment by jo-arroyo** [comment]
@Laharikota07 @stefanvettiger Have you correctly bootstrapped `MsalRedirectComponent` or called `handleRedirectObservable`? The `initialize` function should be taken care of in there. Please follow our [redirect doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/redirects.md) for more information on how to correct configure redirects. This includes apps that only use popups and apps with standalone components.

@stefanvettiger I am unable to reproduce your issue with the latest versions with [our sample apps](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v3-samples). Please follow the examples provided in the samples, including how to provide the `MsalBroadcastService`.

**Comment by Laharikota07** [comment]
Yes i did and followed as per https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/redirects.md  this doc.

**Comment by polys** [comment]
I'm having the same/similar issue with a React app:
- @azure/msal-react 2.0.2 with @azure/msal-browser@3.0.2 works without any issues
- newer versions that bundle @azure/msal-browser 3.1.0 or 3.2.0 result in `uninitialized_public_client_application`

The issue **can't** be reproduced on `localhost` unfortunately.

When deployed properly, clearing session storage and cookies makes it work the first time. 
Refreshing the page afterwards (without clearing storage) fails with `uninitialized_public_client_application` most of the time, but it does work occasionally.

**Comment by StefanoLucchi** [comment]
> @Laharikota07 @stefanvettiger Have you correctly bootstrapped `MsalRedirectComponent` or called `handleRedirectObservable`? The `initialize` function should be taken care of in there. Please follow our [redirect doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/redirects.md) for more information on how to correct configure redirects. This includes apps that only use popups and apps with standalone components.

I have the same issue of @Laharikota07 also with:
@azure/msal-angular: 3.0.5
@azure/msal-browser: 3.2.0

I have bootstrapped `MsalRedirectComponent` according to the provided documentation. The first time that I run the application, the redirect component is displayed and the authentication goes well. If I refresh the page, having the token cached, correctly the redirect component is not displayed, but later, using the `acquireTokenSilent` function, I get the error above.

Launching the `initialize` function before the `acquireTokenSilent` function fixes the issue. Is it the expected behavior?

**Comment by jo-arroyo** [comment]
@polys Please open a separate issue for MSAL React.

@StefanoLucchi Can you turn on verbose logs and check if `handleRedirectObservable` or `handleRedirectPromise` is being called after you refresh the page? The `MsalRedirectComponent` should call `handleRedirectObservable`, which also calls `initialize`. If the way that your app is bootstrapping `MsalRedirectComponent` means that it is not used upon page refresh, then it is expected behavior that `initialize` will not be called, and you can call it directly.

**Comment by polys** [comment]
All I was trying to say is that this may be an issue with @azure/msal-browser >= 3.1.0, not an Angular or React thing.

**Comment by georgiosApo** [comment]
What solved it for me in my React application was simply updating how I was initialising the msalInstance.

```
// Old implementation
export const msalInstance = new PublicClientApplication(msalConfig)

// New implementation
export const msalInstance = await PublicClientApplication.createPublicClientApplication(msalConfig)
```

Migrated from:
```
"@azure/msal-browser": "2.32.1",
"@azure/msal-react": "^1.5.2",
```

To:
```
"@azure/msal-browser": "^3.2.0",
"@azure/msal-react": "^2.0.4",
```

Hope this helps anyone out there.

**Comment by DMOAbove** [comment]
> What solved it for me in my React application was simply updating how I was initialising the msalInstance.
> 
> ```
> // Old implementation
> export const msalInstance = new PublicClientApplication(msalConfig)
> 
> // New implementation
> export const msalInstance = await PublicClientApplication.createPublicClientApplication(msalConfig)
> ```
> 
> Migrated from:
> 
> ```
> "@azure/msal-browser": "2.32.1",
> "@azure/msal-react": "^1.5.2",
> ```
> 
> To:
> 
> ```
> "@azure/msal-browser": "^3.2.0",
> "@azure/msal-react": "^2.0.4",
> ```
> 
> Hope this helps anyone out there.

Thank you, that solved my problem on a vue project. changed the msal instance initializing implementation and it works perfectly :)

For more information here we can find the migration guide:
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/v2-migration.md

**Comment by AliAsafPolat** [comment]
Hey guys, I fixed my error by putting my components into "\<AuthenticatedTemplate> \<AuthenticatedTemplate/>". So before the page loads, I make sure that it is initialized.

**Comment by wdison** [comment]
> I have a similar error. I'm getting also circular DI error for MsalBroadcastService. But this only happens when i test my application NOT on http://localhost:4200. The problem occurs with the following library versions:
> 
> * "@azure/msal-angular": "^3.0.4",
> * "@azure/msal-browser": "^3.1.0"
> 
> When i force to use the following versions, everything works well (Note: delete package-lock.json and recreate to force using the correct versions!!!):
> 
> * "@azure/msal-angular": "3.0.4",
> * "@azure/msal-browser": "3.0.2"
> 
> ```
> ERROR Error: NG0200: Circular dependency in DI detected for MsalBroadcastService. Find more at https://angular.io/errors/NG0200
>     at throwCyclicDependencyError (core.mjs:228:11)
>     at R3Injector.hydrate (core.mjs:9426:13)
>     at R3Injector.get (core.mjs:9301:33)
>     at ChainedInjector.get (core.mjs:14001:36)
>     at lookupTokenUsingModuleInjector (core.mjs:4504:39)
>     at getOrCreateInjectable (core.mjs:4552:12)
>     at Module.ɵɵdirectiveInject (core.mjs:11784:19)
>     at NodeInjectorFactory.NavbarComponent_Factory [as factory] (navbar.component.ts:23:29)
>     at getNodeInjectable (core.mjs:4758:44)
>     at instantiateAllDirectives (core.mjs:12612:27)
> ```
@stefanvettiger 

I had this same error... running on localhost:4200 it worked normally, but when running by URL or IP, on the local machine or any other server, this error appeared...

The solution for me was to run over HTTPS.
To test locally with nodejs and ng use:

```sh
ng serve --host 0.0.0.0 --ssl
```

After that, just enter the IP in the browser.

https://url_or_ip:4200/

**Comment by wdison** [comment]
I'll leave it to the next users who get here with this problem. A solution I found to load any asynchronous/promise configuration, which is dependent on a provider/service... using module with APP_INITIALIZER.

[Dynamic Configurations Using Factory Providers And APP_INITIALIZER](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/configuration.md#dynamic-configurations-using-factory-providers-and-app_initializer)

```
src/app/config.service.ts
```
```
import { Injectable } from '@angular/core';
import { HttpClient, HttpBackend } from '@angular/common/http';
import { map } from 'rxjs/operators';

export const PUBLIC_CLIENT_APPLICATION_NAME: string = 'IPublicClientApplication';

export function loggerCallback(logLevel: LogLevel, message: string) {
  console.log(message);
}

async function createIPublicClientApplicationAsync(config: ConfigService): Promise<IPublicClientApplication> {
  const msalConfigLocal = {
    auth: config.getSettings('msal').auth,
    cache: config.getSettings('msal').cache,
    system: {
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Info,
        piiLoggingEnabled: false
      }
    }
  };

  const msalInstanceLocal = await PublicClientApplication.createPublicClientApplication(msalConfigLocal);
  return msalInstanceLocal;
}


@Injectable({
  providedIn: 'root'
})
export class ConfigService {
  private settings: any;
  private http: HttpClient;

  constructor(private readonly httpHandler: HttpBackend) {
    this.http = new HttpClient(httpHandler);
  }

  init(endpoint: string): Promise<boolean> {
    return new Promise<boolean>(async (resolve, reject) => {
      try {
        this.settings = await this.http.get(endpoint).pipe(map(result => result)).toPromise();
      
        //Here you can call anything asynchronous, as synchronous... like:
        this.settings[PUBLIC_CLIENT_APPLICATION_NAME] = await createIPublicClientApplicationAsync();
        
        resolve(true);
      } catch (error) {
        reject(error);
      }
    });
  }

  getSettings(key?: string | Array<string>): any {
    if (!key || (Array.isArray(key) && !key[0])) {
      return this.settings;
    }

    if (!Array.isArray(key)) {
      key = key.split('.');
    }

    let result = key.reduce((account: any, current: string) => account && account[current], this.settings);

    return result;
  }
}
```
```
src/app/msal-config-dynamic.module.ts
```
```
import { InjectionToken, NgModule, APP_INITIALIZER } from '@angular/core';
import { IPublicClientApplication, PublicClientApplication, 
    LogLevel } from '@azure/msal-browser';
import { MsalGuard, MsalInterceptor, MsalBroadcastService,
     MsalInterceptorConfiguration, MsalModule, MsalService,
      MSAL_GUARD_CONFIG, MSAL_INSTANCE, MSAL_INTERCEPTOR_CONFIG, 
      MsalGuardConfiguration } from '@azure/msal-angular';
import { HTTP_INTERCEPTORS } from '@angular/common/http';
import { ConfigService, PUBLIC_CLIENT_APPLICATION_NAME } from './config.service';

const AUTH_CONFIG_URL_TOKEN = new InjectionToken<string>('AUTH_CONFIG_URL');

export function initializerFactory(env: ConfigService, configUrl: string): any {
    const promise = env.init(configUrl).then((value) => {
        console.log('finished getting configurations dynamically.');
    });
    return () => promise;
}

export function MSALInstanceFactory(config: ConfigService): IPublicClientApplication {
  return config.getSettings(PUBLIC_CLIENT_APPLICATION_NAME);
}

export function MSALInterceptorConfigFactory(config: ConfigService): MsalInterceptorConfiguration {
    const protectedResourceMap = new Map<string, Array<string>>(config.getSettings('interceptor').protectedResourceMap)
  
    return {
      interactionType: config.getSettings('interceptor').interactionType,
      protectedResourceMap
    };
  }
  
export function MSALGuardConfigFactory(config: ConfigService): MsalGuardConfiguration {
    return { 
      interactionType: config.getSettings('guard').interactionType,
      authRequest: config.getSettings('guard').authRequest,
      loginFailedRoute: config.getSettings('guard').loginFailedRoute
    };
}

@NgModule({
    providers: [],
    imports: [MsalModule]
})
export class MsalConfigDynamicModule {

    static forRoot(configFile: string) {
        return {
            ngModule: MsalConfigDynamicModule,
            providers: [
                ConfigService,
                { provide: AUTH_CONFIG_URL_TOKEN, useValue: configFile },
                { provide: APP_INITIALIZER, useFactory: initializerFactory,
                     deps: [ConfigService, AUTH_CONFIG_URL_TOKEN], multi: true },
                {
                    provide: MSAL_INSTANCE,
                    useFactory: MSALInstanceFactory,
                    deps: [ConfigService]
                },
                {
                    provide: MSAL_GUARD_CONFIG,
                    useFactory: MSALGuardConfigFactory,
                    deps: [ConfigService]
                },
                {
                    provide: MSAL_INTERCEPTOR_CONFIG,
                    useFactory: MSALInterceptorConfigFactory,
                    deps: [ConfigService]
                },
                MsalService,
                MsalGuard,
                MsalBroadcastService,
                {
                    provide: HTTP_INTERCEPTORS,
                    useClass: MsalInterceptor,
                    multi: true
                }
            ]
        };
    }
}
```
```
src/app/app.module.ts
```
```
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { NgModule } from '@angular/core';

import { MatButtonModule } from '@angular/material/button';
import { MatToolbarModule } from '@angular/material/toolbar';
import { MatListModule } from '@angular/material/list';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { HomeComponent } from './home/home.component';
import { ProfileComponent } from './profile/profile.component';

import { HttpClientModule } from '@angular/common/http';
import { MsalRedirectComponent } from '@azure/msal-angular';
import { DetailComponent } from './detail/detail.component';
import { MsalConfigDynamicModule } from './msal-config-dynamic.module';

@NgModule({
  declarations: [
    AppComponent,
    HomeComponent,
    ProfileComponent,
    DetailComponent
  ],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    AppRoutingModule,
    MatButtonModule,
    MatToolbarModule,
    MatListModule,
    HttpClientModule,
    MsalConfigDynamicModule.forRoot('assets/configuration.json')
  ],
  providers: [],
  bootstrap: [AppComponent, MsalRedirectComponent]
})
export class AppModule { }
```
```
src/assets/configuration.json
```
```
{
  "msal": {
    "auth": {
      "clientId": "clientid",
      "authority": "https://login.microsoftonline.com/common/",
      "redirectUri": "http://localhost:4200/",
      "postLogoutRedirectUri": "http://localhost:4200/",
      "navigateToLoginRequestUrl": true
    },
    "cache": {
      "cacheLocation": "localStorage",
      "storeAuthStateInCookie": true
    }
  },
  "guard": {
    "interactionType": "redirect",
    "authRequest": {
      "scopes": ["user.read"]
    },
    "loginFailedRoute": "/login-failed" 
  },
  "interceptor": {
    "interactionType": "redirect",
    "protectedResourceMap": [
      ["https://graph.microsoft.com/v1.0/me", ["user.read"]]
    ]
  }
}
```


I hope I've helped!
