### ISSUE TITLE
I've a question regarding best bracticies while acquiring the microsoft graph token

### ISSUE THREAD

**Issue by Paula2001** [AzureAD/microsoft-authentication-library-for-js#6505]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.14

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.0.0

### Public or Confidential Client?

Public

### Description

we all know that we can acquire a new token with microsoft graph scopes like that 
`
 const response = await msalInstance.acquireTokenSilent({
        ...loginRequest,
        account: account
    });`

my question is should acquire a new token on each request because this is what every documentation about this topic suggest or can generate only one and refresh it when needed ?

### Identity Provider

None

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@Paula2001 Please see our documentation for [acquiring tokens](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/acquire-token.md) and [token lifetimes](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/token-lifetimes.md) to answer your question.
