### ISSUE TITLE
"Cannot read property 'indexOf' of undefined" error received

### ISSUE THREAD

**Issue by trevonmckay** [AzureAD/microsoft-authentication-library-for-js#6506]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.37.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

While running the msal-browser package in a React Native application I receive an error that reads "Cannot read property 'indexOf' of undefined."

### Error Message

Cannot read property 'indexOf' of undefined.

![IMG_89B994B2485E-1](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/18320804/3fe08f86-1f52-4f08-b571-1e0aa6fb2f92)

### MSAL Configuration

```javascript
{
		auth: {
			clientId,
		},
	};
```

### Relevant Code Snippets

```javascript
export const AuthenticationProvider: React.FC<AuthenticationProviderProps> = (props: Readonly<AuthenticationProviderProps>) => {
	const msalInstanceRef = useRef<PublicClientApplication>(null);
	const [isReady, setIsReady] = useState<boolean>(false);
	const [account, setAccount] = useState<AccountInfo>(undefined);

	const {
		clientId
	} = props;

	const msalConfig = {
		auth: {
			clientId,
		},
	};

	if (msalInstanceRef.current === null) {
		console.log("Instantiate PublicClientApplication");
		msalInstanceRef.current = new PublicClientApplication(msalConfig);
	}

	const msalInstance = msalInstanceRef.current;
	if (msalInstance && msalConfig.auth.clientId && !isReady) {
		console.log("Initialize PublicClientApplication");
		msalInstance
			.initialize()
			.then(() => {
				console.log("PublicClientApplication is ready");
				setIsReady(true);
			});
	}

	if (msalInstance && isReady) {
		const activeAccount = msalInstance.getActiveAccount();
		setAccount(activeAccount);
	}

	console.log("account", account);

	return (
		<AuthenticationContext.Provider value={{
			authenticated: account !== undefined,
			account,
		}}>
			{props.children}
		</AuthenticationContext.Provider>
	)
}
```

### Reproduction Steps

1. Install @azure/msal-browser package to React Native project
2. Instantiate and initialize an instance of the PubilcClientApplication

### Expected Behavior

I expect that an undefined user agent would return false for the function BrowserUtils.detectIEOrEdge

```js
static detectIEOrEdge(): boolean {
     const ua = window.navigator.userAgent;
     if (ua) {
        const msie = ua.indexOf("MSIE ");
        const msie11 = ua.indexOf("Trident/");
        const msedge = ua.indexOf("Edge/");
        const isIE = msie > 0 || msie11 > 0;
        const isEdge = msedge > 0;
        return isIE || isEdge;
     } else {
        return false;
     }
}
```

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Other

### Source

External (Customer)

**Comment by jo-arroyo** [comment]
@trevonmckay Please upgrade to the latest version of MSAL Browser if possible and see if this error still occurs.
