### ISSUE TITLE
logoutPopup parameter type incorrect. 

### ISSUE THREAD

**Issue by MattMinke** [AzureAD/microsoft-authentication-library-for-js#6508]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.1.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

Parameter type for function [PublicCLientApplication.logoutPopup](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/4392a636c2d340394949b46c866a5b9895fc195e/lib/msal-browser/src/app/PublicClientApplication.ts#L296C33-L296C50) is incorrect. Its currently defined as `EndSessionRequest ` but should be defined as EndSessionPopupRequest. The incorrect parameter type prevents mainWindowRedirectUri and popupWindowAttributes from being specified. 

Note: [StandardController.logoutPopup](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/4392a636c2d340394949b46c866a5b9895fc195e/lib/msal-browser/src/controllers/StandardController.ts#L1172) is defined with EndSessionPopupRequest:

Error in VSCode
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/5995359/87225eed-17a0-421b-b0dd-bd7b116d4152)

### Error Message

Argument of type '{ mainWindowRedirectUri: string; }' is not assignable to parameter of type 'EndSessionRequest'.
  Object literal may only specify known properties, and 'mainWindowRedirectUri' does not exist in type 'EndSessionRequest'.ts(2345)

### MSAL Configuration

```javascript
{
  // required
  auth: {
    // must match info in dashboard
    clientId: import.meta.env.VITE_AUTH_CLIENT_ID,
    authority: import.meta.env.VITE_AUTH_AUTHORITY,
    knownAuthorities: [
      import.meta.env.VITE_AUTH_AUTHORITY,
    ],

    // login redirect; must match path in dashboard
    redirectUri: `${location.origin}/auth/redirect/login`,
  },

  // optional
  system: {
    loggerOptions: {
      logLevel: LogLevel.Verbose,
      loggerCallback,
    }
  }
}
```

### Relevant Code Snippets

```javascript
async logout () {
    // ref: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md#logoutpopup
    return msal.logoutPopup({

      // required to make the application return to the home page
      mainWindowRedirectUri: '/'
    
    })
  },
```

### Reproduction Steps

1. Clone repo https://github.com/davestewart/msal-vue-demo
2. upgrade msal-browser
3. auth.ts will produce an error

### Expected Behavior

For properties `mainWindowRedirectUri `and `popupWindowAttributes `to assignable when calling `logoutPopup`

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer

### Regression

@azure/msal-browser@2.38.2

### Source

External (Customer)

**Comment by tnorling** [comment]
Thanks, marking this as a bug. Please feel free to open a pull request with the change if you need this fixed sooner rather than later.

**Comment by scottmillionnexient** [comment]
If you're stuck on this in the meantime this removes typescript / build issues:

```
import { type EndSessionPopupRequest } from "@azure/msal-browser"

 const logoutRequest: EndSessionPopupRequest = {
    mainWindowRedirectUri: "/",
  }
  instance.logoutPopup(logoutRequest)
```
