### ISSUE TITLE
Browser Session Handling using MSAL.

### ISSUE THREAD

**Issue by veera-raghavagupta** [AzureAD/microsoft-authentication-library-for-js#6509]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.14.2

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.0.0

### Public or Confidential Client?

Public

### Description

We have requirement to store MSAL acquired token in cache and it should clear automatically on closing all browser windows and also should share token between windows and tabs.  We are using Angular 14 at front end.

Has any body implemented similar requirement. Can you please shed some light on the approach you have taken.

### MSAL Configuration

```javascript
{
  cache: {
    cacheLocation: "localStorage"
  }
}
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by tnorling** [comment]
To share cache between tabs/windows use localStorage. To clear cache when closing a window you can subscribe to the beforeUnload browser event and clear localStorage prior to exiting. To ensure you don't clear cache while other tabs are still open will likely require more complex custom logic that extends beyond the scope of MSAL.js and the support we're able to offer. I would suggest asking your question over on StackOverflow.
