### ISSUE TITLE
Enabling regional STS using the azureRegion variable is not working.

### ISSUE THREAD

**Issue by niallb96** [AzureAD/microsoft-authentication-library-for-js#6510]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

2.1.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Confidential

### Description

Enabling regional STS using the `azureRegion` variable is not working.   I've set the `azureRegion ` to `eastus `and deployed this changed for testing  but the logs still show a login url of: `https://login.microsoftonline.com` rather than `eastus.login.microsoftonline.com` indicating it's not working.  All the other logs look the same as when this variable isn't configured and there are no error logs.  I've also tried configuring regional STS using the environment variable with no success.

### Msal Logs

Info - acquireTokenByClientCredential called
Verbose - initializeRequestScopes called
Verbose - buildOauthClientConfiguration called
Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/***
Verbose - createAuthority called
Verbose - Attempting to get cloud discovery metadata in the config
Verbose - Did not find cloud discovery metadata in the config... Attempting to get cloud discovery metadata from the cache.
Verbose - The metadata entity is expired.
Verbose - Did not find cloud discovery metadata in the cache... Attempting to get cloud discovery metadata from the network.
Verbose - Attempting to find a match between the developer's authority and the CloudInstanceDiscoveryMetadata returned from the network request.
Verbose - cloud discovery metadata was successfully returned from getCloudDiscoveryMetadataFromNetwork()
Verbose - Client credential client created

### MSAL Configuration

```javascript
auth: {
        clientId,
        clientCertificate: {
          thumbprint: certificate.thumbprint.toLowerCase().replace(/:/g, ''),
          privateKey: certificate.privateKeyWithNewLines,
          x5c: certificate.certificateWithNewLines,
        },
      }
```

### Relevant Code Snippets

```javascript
public async getFirstPartyToken (stsHostname: string, tenantId: string, resourceAppId: string, skipCache: boolean): Promise<string> {
    const request: ClientCredentialRequest = {
      scopes: [`${resourceAppId}/.default`],
      authority: `${stsHostname}/${tenantId}`,
      skipCache,
      azureRegion: 'eastus2',
    };
    const response = await this.application.acquireTokenByClientCredential(request);
    return response!.accessToken;
  }
```

### Reproduction Steps

1. Set up request with the same configuration.
2.  Look at MSAL log to validate if regional sts is configured.

### Expected Behavior

Log should contain authority: `eastus.login.microsoftonline.com`  as regional sts has been configured.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Source

Internal (Microsoft)

**Comment by bgavrilMS** [comment]
@trwalke - can you have a look at as you're ramping up on NodeJS stuff pls

**Comment by trwalke** [comment]
Sure

**Comment by bgavrilMS** [comment]
@trwalke - isn't this done?

**Comment by bgavrilMS** [comment]
I'm going to mark it as done. There was no issue with the happy path logic, but we added more logging to be able to tell what's happening on invalid scenario.

**Comment by trwalke** [comment]
> @trwalke - isn't this done?

Yes, it is complete.
