### ISSUE TITLE
The interface to AuthToken.extractTokenClaims broke without a comment in the release notes

### ISSUE THREAD

**Issue by ngbrown** [AzureAD/microsoft-authentication-library-for-js#6513]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

2.1.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

N/A

### Public or Confidential Client?

Confidential

### Description

Between `@azure/msal-node` version `2.0.2` and `@azure/msal-node` version `2.1.0` the interface to `AuthToken.extractTokenClaims` changed from accepting `ICrypto` to accepting a function.

It was a static method on a class:

```ts
export declare class AuthToken {
    rawToken: string;
    claims: TokenClaims;
    constructor(rawToken: string, crypto: ICrypto);
    /**
     * Extract token by decoding the rawToken
     *
     * @param encodedToken
     */
    static extractTokenClaims(encodedToken: string, crypto: ICrypto): TokenClaims;
    /**
     * Determine if the token's max_age has transpired
     */
    static checkMaxAge(authTime: number, maxAge: number): void;
}
```

It is now individually exported:

```ts
export declare function extractTokenClaims(encodedToken: string, base64Decode: (input: string) => string): TokenClaims;
```

This changed in #6423 as only a patch when it was in-fact a breaking change.

### Error Message

N/A

### Msal Logs

N/A

### MSAL Configuration

```javascript
N/A
```

### Relevant Code Snippets

```javascript
AuthToken.extractTokenClaims(accessToken, new CryptoProvider());
```

### Reproduction Steps

N/A

### Expected Behavior

I expect better documentation of breaking changes, or don't make the breaking change.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Regression

@azure/msal-node 2.0.2

### Source

Internal (Microsoft)

**Comment by sameerag** [comment]
cc @tnorling

**Comment by tnorling** [comment]
AuthToken is not part of the public surface, hence not a breaking change. If you need the token claims they are returned as part of the `AuthenticationResult` object (idTokenClaims) each of our token acquisition APIs returns.
