### ISSUE TITLE
handleRedirectPromise did not detect a response hash as a result of a redirect, why?

### ISSUE THREAD

**Issue by Yogish9** [AzureAD/microsoft-authentication-library-for-js#6515]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.30.0

### Public or Confidential Client?

Public

### Description

I am getting below error when redirecting from azure :

Info - handleRedirectPromise did not detect a response hash as a result of a redirect. Cleaning temporary cache.

if user cancels the authentication flow also same error is coming.

additionally getting Exception: Authentication error: ClientAuthError: state_not_found: State not found:  Cached State
    at ClientAuthError.AuthError [as constructor] (AuthError.js:31:24)
    at new ClientAuthError (ClientAuthError.js:216:28)
    at ClientAuthError.createStateNotFoundError (ClientAuthError.js:292:16)
    at RedirectHandler.<anonymous> (RedirectHandler.ts:100:35)

### Error Message

Info - handleRedirectPromise did not detect a response hash as a result of a redirect. Cleaning temporary cache.

additionally getting Exception: Authentication error: ClientAuthError: state_not_found: State not found:  Cached State
    at ClientAuthError.AuthError [as constructor] (AuthError.js:31:24)
    at new ClientAuthError (ClientAuthError.js:216:28)
    at ClientAuthError.createStateNotFoundError (ClientAuthError.js:292:16)
    at RedirectHandler.<anonymous> (RedirectHandler.ts:100:35)

### MSAL Configuration

```javascript
auth: 
{
clientId: 'a1569f9e-d94b-4569-841f-21a7c580e608',
authority: 'https://SoleraNAB2BNPrd.b2clogin.com/SoleraNAB2BNPrd.onmicrosoft.com/b2c_1a_passwordless',
knownAuthorities: ['SoleraNAB2BNPrd.b2clogin.com'],
redirectUri: "http://localhost:1841/app",
postLogoutRedirectUri: "http://localhost:1841/app"
},
cache: {
            cacheLocation: "sessionStorage", // Configures cache location. "sessionStorage" is more secure, but "localStorage" gives you SSO between tabs.
            storeAuthStateInCookie: false, // If you wish to store cache items in cookies as well as browser cache, set this to "true".
        },
```

### Relevant Code Snippets

```javascript
getConfigFile: function () {
        var msalconfig;
        Ext.Ajax.request({
            url: 'msalconfig.json', // Config file for B2C policies
            async: false, // Make the request synchronous
            success: function (response) {
                msalconfig = Ext.decode(response.responseText);
            },
            async: false // Ensure that the request is synchronous
        });
        return msalconfig;
    },
    beforeshow: function (loginForm, eOpts) {
        var msaldata = this.getConfigFile();
        var myMSALObj = new msal.PublicClientApplication(msaldata);

        myMSALObj.handleRedirectPromise()
            .then(function (response) {
                
                console.log("Authentication response:", response);
                if (response !== null) {
                    
                    console.log(response);
                    // Authentication was successful
                   // var accessToken = response.accessToken; // Access token
                    var idToken = response.idToken; // ID token
                    var account = response.account; // User account information
                    OPApp.util.EnservioCookie.setCookie('IdToken', idToken);
                    // Use the tokens and account information as needed
                    console.log("Authentication successful:",idToken, account);

                    // Handle successful authentication here
                    // For example, you can update your UI or perform additional actions

                } else {
                    
                    // Authentication failed or was canceled by the user
                    // Handle authentication failure or cancellation here
                }
            })
            .catch(function (error) {
                // Handle any errors that occur during the authentication process
                console.log("Authentication error:", error);

                // You can also update your UI or perform other error handling tasks
            });
```

### Reproduction Steps

I don't have any link which demonstrates this behavior

### Expected Behavior

I should not get above error message. it should validate the result.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
This happens when MSAL is not able to find the server response in the hash of the URL. This can happen for a number of reasons, including: 

1. Your application has removed or changed the hash fragment before MSAL had a chance to read it
2. The service returned the response in the query string instead of the hash - it looks like you're using B2C, make sure your policy is respecting the responseMode parameter

Easy way to check which case this is, is to look at the URL when this error is thrown

**Comment by Yogish9** [comment]
Please close this ticket and mark it as private, By mistake I have shared Client Secrete

**Comment by Yogish9** [comment]
Please mark this issue as private
