### ISSUE TITLE
Login popup doesn't close on Vue3 application after acquireTokenPopup

### ISSUE THREAD

**Issue by AliasMM** [AzureAD/microsoft-authentication-library-for-js#6516]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.1.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

none

### Public or Confidential Client?

Public

### Description

Hi, I'm facing a bug when I try to login calling the acquireTokenPopup method on a Vue 3 application. 
9 times out of 10 the popup shows the Webapp itself and doesn't close. 
I've seen that the issue is alredy known (https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5091) and that you've tried to fix it by adding the pollIntervalMilliseconds property but in my case that won't reslove the issue.

### MSAL Configuration

```javascript
msalConfig: {
    auth: {
        clientId: ClientId,
        authority: AuthorityId
    },
    cache: {
        cacheLocation: 'localStorage',
    },
    //system: {
    //    pollIntervalMilliseconds: 20 //doesn't work
    //}
},
```

### Relevant Code Snippets

```javascript
This is my js function where i call the method:

SignInAndGetAccessToken: async function () {

    if (this.$store.state.accessToken == '') {

        let request = {
            account: this.account,
            scopes: ['myscope goes here'],
        };

        const msalInstance = new PublicClientApplication(this.$store.state.msalConfig); //Vuex store

        try {
            await msalInstance.initialize();
            await msalInstance.handleRedirectPromise();
            let tokenResponse = await msalInstance.acquireTokenSilent(request);
	    this.$store.commit('setAccessToken', tokenResponse.accessToken);
			
	    if (this.account == null)
		this.account = tokenResponse.account;

        } catch (error) {
            try {
                let tokenResponse = await msalInstance.acquireTokenPopup(request);
                this.$store.commit('setAccessToken', tokenResponse.accessToken);

		if (this.account == null)
		    this.account = tokenResponse.account;
					
            } catch (error) {
                console.error(error);
            }
        }
    }
}
```

### Reproduction Steps

1. Create a Vue 3 application
2. Install the newest version of @azure/msal-browser and vuex throught npm.
3. Adjust MSAL configuration 
4. Run the sample and try to log in several times.

### Expected Behavior

Login popup should close, but it doesn't.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

External (Customer)

**Comment by tnorling** [comment]
The domain of the redirectUri and the domain of the calling page must be the same, the popup won't close until it returns to same domain as the caller. Please verify that this is the case.
