### ISSUE TITLE
Issuers comparison missing after call to updateEndpointMetadata

### ISSUE THREAD

**Issue by denvernyaw** [AzureAD/microsoft-authentication-library-for-js#6518]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.14.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.0.3

### Public or Confidential Client?

Public

### Description

Hi,

I faced the issue with issuers comparison while using OpenID Connect Discovery specification. It says that issuer, used to make a request to /.well-known/openid-configuration, and the issuer field from JSON response must be equal: 
https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationValidation

In MSAL library there is a function which is called updateEndpointMetadata (https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/src/authority/Authority.ts#L444) which do the next steps:

1. get endpoint metadata from config
2. if not found in config – get metadata from hardcoded values
3. if not found in hardcoded values – get metadata from cache. At this step there is an issuers comparison validation.
4. if not found in cache – make an HTTP GET request to .well-known/openid-configuration and get metadata from response. At this step I would expect that the issuers comparison validation step is going to be performed, but it is not.

Sou could you please kindly explain why there is no check in place? It might be a case that I'm missing something. I faced an issue with different issuers and was surprised when MSAL didn't highlight it.

### MSAL Configuration

```javascript
nothing special, just regural config from examples
```

### Relevant Code Snippets

```javascript
updateEndpointMetadata function: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-common/src/authority/Authority.ts#L444
```

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by denvernyaw** [comment]
Hi @sameerag , could you please kindly share updates if any? We are really looking for support here

**Comment by tnorling** [comment]
Validation was not implemented because we never use the issuer field for anything. Can you help me understand why you think you need this validation to occur?

**Comment by denvernyaw** [comment]
Hi @tnorling , sorry for long delay.

According to https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationValidation official Open ID Connect specification – comparison of issuers is mandatory step of ID token validation. Although you are not using issuer – if we are implementing OIDC protocol we must do that. 

@tnorling could you please kindly fix this in the nearest versions?

Looking like this thread need to be converted to bug/security defect. Can anyone kindly help me with that? :)

**Comment by denvernyaw** [comment]
Hi, sorry, any reason why bot closed this issue? This is not yet resolved..

@tnorling @sameerag

**Comment by peterzenz** [comment]
Microsoft guidance on ID token validation:  https://learn.microsoft.com/en-us/entra/identity-platform/id-tokens#validate-tokens
Notable is that:

> Public applications (code running entirely on a device or network you don't control such as a user's browser or their home network) don't benefit from validating the ID token. In this instance, a malicious user can intercept and edit the keys used for validation of the token.

Also stated earlier in that article:

> ID tokens shouldn't be used for authorization purposes. Access tokens are used for authorization. The claims provided by ID tokens can be used for UX inside your application, as keys in a database, and providing access to the client application.

MSAL.js doesn't provide any token validation.  Applications that accept any token should perform the required signature validation, then perform the required claims validation.  More details on token validation can be found here:  https://learn.microsoft.com/en-us/entra/identity-platform/access-tokens#validate-tokens
