### ISSUE TITLE
Token response sometimes does not contain "access_token", depending on client app

### ISSUE THREAD

**Issue by Kiechlus** [AzureAD/microsoft-authentication-library-for-js#6522]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.38.2

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.5.11

### Public or Confidential Client?

Public

### Description

* Two B2C client applications, one created manually, the other with terraform
* With the manual-created, it always works
* With the terraform-created, it works only sometimes. Other times it doesn't work for the whole team. We couldn't find any way to influence this, using Incognito, devalidating refresh tokens for user, creating new user, ...
   -  When it does not work, the token response does not contain `access_token` and `scope` is empty:
   
   ![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/9875731/c68246d4-d0ed-4736-b4c6-4c18785a50f0)
   - Logs then show a null pointer due to the missing accesstoken: `Invalid token specified: Cannot read properties of undefined (reading 'replace')`
   
    ![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/9875731/e4c11d45-a041-4d61-9baa-2aa23dface3e)

   - The token requests look exactly similar (except for IDs)
  

 *  Both B2C applications are completely identicial, except:
    - Manual created app has `"allowPublicClient": null` in Manifest
    - For terraform created, this is not possible. If this option is chosen, the following error appears in console: `AADB2C90058: The provided application is not configured to allow public clients.`
    - `optionalClaims` cannot be set to `null` by terraform

### Msal Logs

The first 28 lines are the same. Then they start to differ:

**Success:**
````
@azure/msal-common@13.3.0 : Info - CacheManager:getAccessToken - Returning access token	
@azure/msal-common@13.3.0 : Info - CacheManager:getRefreshToken - returning refresh token	
@azure/msal-browser@2.38.2 : Info - Emitting event: msal:acquireTokenSuccess	
@azure/msal-common@13.3.0 : Info - CacheManager:getIdToken - Returning id token	
@azure/msal-common@13.3.0 : Info - CacheManager:getIdToken - Returning id token
````

**Failure:**
````
@azure/msal-common@13.3.0 : Info - CacheManager:getAccessToken - No token found
@azure/msal-common@13.3.0 : Info - CacheManager:getRefreshToken - returning refresh token
[92fcd68f-e504-4698-b6e2-bf2baa9629bd] : @azure/msal-common@13.3.0 : Info - SilentFlowClient:acquireCachedToken - No access token found in cache for the given properties.
@azure/msal-browser@2.38.2 : Info - Emitting event: msal:acquireTokenFromNetworkStart
@azure/msal-common@13.3.0 : Info - CacheManager:getRefreshToken - returning refresh token
@azure/msal-common@13.3.0 : Info - CacheManager:getIdToken - Returning id token
@azure/msal-common@13.3.0 : Info - CacheManager:getIdToken - Returning id token
@azure/msal-browser@2.38.2 : Info - Emitting event: msal:acquireTokenSuccess
query.ts:446 X {message: "Invalid token specified: Cannot read properties of undefined (reading 'replace')", stack: 'InvalidTokenError\n
````

### MSAL Configuration

```javascript
export const b2cPolicies = {
  names: {
    signUpSignIn: "B2C_1A_SIGNUP_SIGNIN",
  },
  authorities: {
    signUpSignIn: {
      authority: "https://osepb2c.b2clogin.com/osepb2c.onmicrosoft.com/B2C_1A_SIGNUP_SIGNIN",
    },
  },
  authorityDomain: "https://osepb2c.b2clogin.com",
};

export const msalConfig: Configuration = {
  auth: {
    clientId: config.clientId, // Always works with: "94a9c104-66c3-4b47-8ca3-9be1152c6744",  sometimes works with "43bbab04-c5a0-4744-ab2b-bfe537cdb6c8"
    authority: b2cPolicies.authorities.signUpSignIn.authority,
    knownAuthorities: [b2cPolicies.authorityDomain],
    postLogoutRedirectUri: '/',
    redirectUri: '/',
  },
  cache: {
    cacheLocation: 'localStorage',
    storeAuthStateInCookie: true,
  },
  system: {
    loggerOptions: {
      logLevel: config.msalLogLevel ?? LogLevel.Verbose,
      loggerCallback: (level, message, containsPii) => {
        if (containsPii) return;
        switch (level) {
           ...
        }
      },
      piiLoggingEnabled: false,
    },
  },
};
```

### Relevant Code Snippets

```javascript
function useSilentRequest(): SilentRequest {
  const { accounts } = useMsal();
  const account = accounts[0];

  return useMemo(
    () => ({
      account,
      scopes: loginRequest.scopes,
      authority: b2cPolicies.authorities.signUpSignIn.authority,
    }),
    [account],
  );
}

declare function useAccessToken(siltentRequest: SilentRequest): () => Promise<{
    accessToken: string;
    payload: {
        [key: string]: any;
    };
}>;

function useSiassBackend() {
  const silentRequest = useSilentRequest();
  const aquireAccessToken = useAccessToken(silentRequest);

  const basePath = `${config.mibHost}/api/v1`;

  const createApiConfig = useCallback(
    () =>
      aquireAccessToken()
        .then(({ accessToken }) => `Bearer ${accessToken}`)
        .then(
          (apiKey) =>
            new Configuration({
              basePath,
              apiKey,
            }),
        ),
    [aquireAccessToken, basePath],
  );

  return useMemo(() => ({ createApiConfig }), [createApiConfig]);
}
```

### Reproduction Steps

* Use app from terraform
* Sometimes, no access token is returned
* undefined error in console, frontend stops to work

### Expected Behavior

* Should always return access token and work

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome
Firefox

### Source

External (Customer)

**Comment by Kiechlus** [comment]
@bgavrilMS @sameerag Can you help us understand why the token response in some cases does not contain an access token? It is a blocker for us. Also, it seems it is not possible to open Azure B2C support requests for technical issues. 

Can this be somehow related to https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/6451? 

Is it required to set App Uris on the Api-describing-appliation (see screenshot below)? This is limited by terraform due to https://github.com/hashicorp/terraform-provider-azuread/issues/428

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/9875731/0a56af48-a0d3-486f-83c0-746a52436da2)

**Comment by bgavrilMS** [comment]
Depends on what you are trying to do @Kiechlus . To sign-in a user means to obtain an ID token for that user. You only need a token if you want to call a protected API and with B2C this is always "your web api". Microsoft has protected APIs such as Microsoft Graph, Sharepoint etc, but these are protected by AAD. 

Scopes that MSAL always asks for: `openid` (id token), `profile` (adds claims about the user in the id token), `offline_access` (refresh token).

**Comment by Kiechlus** [comment]
Thanks for the answer @bgavrilMS. Exactly, we need the access token to call our API with some of the scopes defined by this API.

Is there a way we can force MSAL always to include the access token? Any idea why the behavior seems to be different depending on the client app? Might it be related to public vs. private client?

**Comment by tnorling** [comment]
To get an access token back you need to request a scope associated with the API you intend to access. If you need an access token for your own app please see the docs [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/working-with-b2c.md#acquiring-an-access-token-for-your-own-api) if you're requesting a specific scope and still not getting an access token back there's likely something missing in your policy and you should [open a ticket with B2C.](https://learn.microsoft.com/en-us/azure/active-directory-b2c/find-help-open-support-ticket) MSAL itself does not control what artifacts are returned by the service.

**Comment by Kiechlus** [comment]
Yes, the problem was that the B2C app which defines the scopes needs to set "Application Id Uri", otherwise MSAL can't find the scope requested and therefore omits the access token. 

This involves manual work in a terraform setup due to 
https://github.com/hashicorp/terraform-provider-azuread/issues/428

We needed so long to detect this because changes to the B2C apps take effect only after some time, there seems to be some caches on Azure side. 

Thanks for your replies, I also wanted to close but you were faster )
