### ISSUE TITLE
Azure B2c - getAllAccounts() account.username is empty after the very first signup

### ISSUE THREAD

**Issue by middiu** [AzureAD/microsoft-authentication-library-for-js#6526]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.38.2

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.5.11

### Public or Confidential Client?

Public

### Description

Hello there, 

My application uses Azure B2C with a custom policy and msal-react wrapper.
The very first time the user signup and get redirected to App, the property account.username is always an empty string (account are retrieved using pca.getAllAccounts()).

As soon as the user logs out from the App, and log back in, username is correctly populated.

I understand username is assigned using emails claim in the token, in fact my custom policy has the claim emails specified in all the TechnicalProfiles.

The workaround I'm using is to call pca.logoutRedirect() when username property is empty so that everything works fine after the user log back in, but this doesn't sound correct.

Anyone can confirm this should not be the case?

Cheers 

### Error Message

N/A

### Msal Logs

N/A

### MSAL Configuration

```javascript
xport const authConfiguration: Configuration = {
	auth: {
		clientId: process.env.REACT_APP_AD_CLIENT_ID as string,
		authority: process.env.REACT_APP_AD_AUTHORITY as string,
		redirectUri: window.location.protocol + '//' + (window.location.host || window.location.host),
		knownAuthorities: [process.env.REACT_APP_AD_BASE_AUTHORITY as string],
		authorityMetadata: process.env.REACT_APP_AD_AUTHORITYMETADATA!
	},
	cache: {
		cacheLocation: 'localStorage',
		storeAuthStateInCookie: false
	}
};
```

### Relevant Code Snippets

```javascript
export const getAccessToken = async (): Promise<IAccessToken> => {
	const accounts = pca.getAllAccounts();

	if (accounts.length > 0) {
		const request = {
			scopes: azAPITokenRequestScope,
			account: accounts[0],
		};

		const accessToken = await pca
			.acquireTokenSilent(request)
			.then((response: AuthenticationResult) => {
				return response.accessToken;
			})
			.catch(error => {
				authlog(error);
				if (error instanceof InteractionRequiredAuthError) {
					// fallback to interaction when silent call fails
					authlog('Error in getting token: %o', error);
					pca.acquireTokenRedirect(request);
				} else {
					pca.logoutRedirect();
				}
			});

		if (accounts[0].username === '') {
			authlog('Username of first Accounts is empty, will logout');
			pca.logoutRedirect();
		}

		return {
			accessToken: accessToken,
			account: accounts[0]
		};
	} else {
		authlog('Users array empty, will try to refresh');
		
	}

	return {};
};
```

### Reproduction Steps

1. User sign up
2. User is redirected to my app but username property is empty
3. Once the user has logged out and logged back in username is populated correctly 

### Expected Behavior

username should be there after the sign up

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari

### Source

External (Customer)

**Comment by tnorling** [comment]
This should not be the case. I would first confirm that the token returned on that first login also does not contain the emails claim and if so I would recommend raising with [B2C Support](https://learn.microsoft.com/en-us/azure/active-directory-b2c/find-help-open-support-ticket) to understand why this might be happening. MSAL doesn't have control over the claims returned so we unfortunately can't be of much assistance resolving this.
