### ISSUE TITLE
Bug - @azure/msal-node acquireTokenByClientCredential throws missing tenant for MI scenarios

### ISSUE THREAD

**Issue by KarishmaGhiya** [AzureAD/microsoft-authentication-library-for-js#6531]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

2.0.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

N/A

### Public or Confidential Client?

Confidential

### Description

acquireTokenByClientCredential API throws  `Message missing_tenant_id_error: A tenant id - not common, organizations, or consumers - must be specified when using the client_credentials flow.`
even when we are using it for Managed Identity scenarios.

### Error Message

missing_tenant_id_error: A tenant id - not common, organizations, or consumers - must be specified when using the client_credentials flow.

### MSAL Configuration

```javascript
const appTokenParameters: AppTokenProviderParameters = {
            correlationId: this.identityClient.getCorrelationId(),
            tenantId: options?.tenantId || "organizations",
            scopes: Array.isArray(scopes) ? scopes : [scopes],
            claims: options?.claims,
          };

          // Added a check to see if SetAppTokenProvider was already defined.
          this.initializeSetAppTokenProvider();
          const authenticationResult = await this.confidentialApp.acquireTokenByClientCredential({
            ...appTokenParameters,
          });
```

### Relevant Code Snippets

```javascript
const appTokenParameters: AppTokenProviderParameters = {
            correlationId: this.identityClient.getCorrelationId(),
            tenantId: options?.tenantId || "organizations",
            scopes: Array.isArray(scopes) ? scopes : [scopes],
            claims: options?.claims,
          };

          // Added a check to see if SetAppTokenProvider was already defined.
          this.initializeSetAppTokenProvider();
          const authenticationResult = await this.confidentialApp.acquireTokenByClientCredential({
            ...appTokenParameters,
          });
```

### Reproduction Steps

1. Set up a code sample with just consuming the `acquireTokenByClientCredential` for the `SetAppTokenProvider` like snippet above and run in MI environment.
Link to code - https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/identity/identity/src/credentials/managedIdentityCredential/index.ts#L248

### Expected Behavior

Should not throw the error for missing tenant 

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Regression

@azure/msal-node 1.18.3

### Source

Internal (Microsoft)

**Comment by bgavrilMS** [comment]
Discussed offline and found a solution. Since only Azure SDK is using this extensiblity point, we will not revert to the old behavior.

**Comment by GabGueAlva** [comment]
A mi me sigue saliendo el mismo error

**Comment by jamie-pate** [comment]
uh, ok, what was the solution? any hints?

```TypeScript
    auth: {
        clientId: 'YOUR_CLIENT_ID',
        authority: 'https://login.microsoftonline.com/YOUR_TENANT_ID', // Replace with your tenant GUID
        clientSecret: 'YOUR_CLIENT_SECRET'
    }
```
