### ISSUE TITLE
Proper way to execute custom policy

### ISSUE THREAD

**Issue by dominic-simplan** [AzureAD/microsoft-authentication-library-for-js#6534]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

2.1.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

Hello,

I have created a custom policy in our Azure B2C to delete an account (https://github.com/azure-ad-b2c/samples/tree/master/policies/delete-my-account#delete-my-account).

Now I am wondering how to execute this custom policy using msal-node (Using Electron).

I saw a few examples which are calling `PublicClientApplication.acquireTokenInteractive()` (msal-node) or `PublicClientApplication.loginPopup()` (msal-browser) with the custom policy in the authority URL.

This works, I am using the `openBrowser` callback in the `acquireTokenInteractive` method to show a `BrowserWindow` in which I can complete the custom policy. 

However, the `PublicClientApplication.acquireTokenInteractive()` Promise does never resolve when using the custom policy, even when the user closes the `BrowserWindow` popup. I could probably just add a close listener on the popup to continue in our app, but I am not sure about the consequences of the non-resolved Promise.
```
const authResult = await this.clientApplication.acquireTokenInteractive({
  scopes: [...],
  authority: 'https://abc.b2clogin.com/abc.onmicrosoft.com/B2C_1A_DEMO_DELETE_MY_ACCOUNT',
  account: account ?? undefined,
  openBrowser: async (url) => {
       authWindow.show();
       authWindow.on("closed", () => {
          log.info("CLOSED");
       });
       await authWindow.loadURL(url);
 },
});
// Code never reaches here!
```

On the other hand, the `loginPopup()` Promise of msal-browser is resolved when the popup is closed by the user.

So now I am wondering if this is the correct way to execute a custom policy.
If yes, what is the intention of the `acquireTokenInteractive`-Promise?
If no, what is the alternative? I could create a BrowserWindow manually and load the custom policy URL there. In this case, is there any functionality to create the URL with all necessary query parameters?

### Identity Provider

Azure B2C Custom Policy

### Source

External (Customer)

**Comment by lalimasharda** [comment]
Hey @dominic-simplan can you check if your custom policy is set with the correct responseMode parameter. For msal-node, we set the responseMode to "query" and for msal-browser it is set to "fragment".

**Comment by dominic-simplan** [comment]
Our application is not setting the responseMode so I asusme that the default value is used.
Maybe the problem is that the delete account policy doesn't do a redirect as it just leaves the page open which informs the user that the account has been deleted.

So I guess `acquireTokenInteractive` should only be used for custom policies which do a redirect with a token result?

I have found a solution which works for us. We are now opening a BrowserWindow by ourselves and using the clientApplication.getAuthCodeUrl() method to generate the correct URL for the custom policy.

Not sure if this is the best way to do it but it seems to work.
