### ISSUE TITLE
loginRedirect, loginPopup will stuck in callback page

### ISSUE THREAD

**Issue by aNyMoRe0505** [AzureAD/microsoft-authentication-library-for-js#6539]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.1.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.0.3

### Public or Confidential Client?

Public

### Description

When using loginPopup or loginRedirect, it will redirect to the `redirectUri` and eventually return to the original request location
I'm not sure why I'm stuck on the redirectUri page and unable to log in successfully.
The logs for both methods are shown below (I also log the path and hash)

loginRedirect:
![截圖 2023-10-05 15 11 27](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/9814815/c6c19a27-5ebd-46fd-bcfc-c9f9edf3caf8)

loginPopup
![截圖 2023-10-05 15 14 18](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/9814815/90e72f18-ba38-4266-9c2c-774bbd6e0a40)

### Error Message

please see the above picture

### Msal Logs

please see the above picture

### MSAL Configuration

```javascript
auth: {
    clientId: CLIENT_ID, // This is the ONLY mandatory field that you need to supply.
    authority: b2cPolicies.authorities.signUpSignInPwdLess.authority, // Use a sign-up/sign-in user-flow as a default authority
    knownAuthorities: [b2cPolicies.authorityDomain], // Mark your B2C tenant's domain as trusted.
    redirectUri: `https://${getEnvVar('HOST_NAME')}${Urls.account.AzureLoginCallback}`, // Points to window.location.origin. You must register this URI on Azure Portal/App Registration.
    navigateToLoginRequestUrl: true, // If "true", will navigate back to the original request location before processing the auth code response.
  },
  cache: {
    cacheLocation: 'localStorage', // Configures cache location. "sessionStorage" is more secure, but "localStorage" gives you SSO between tabs.
  },
```

### Relevant Code Snippets

```javascript
N/A If the information provided is not sufficient, please let me know
```

### Reproduction Steps

N/A If the information provided is not sufficient, please let me know

### Expected Behavior

After calling login method, MSAL should return to the original request location and set token

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome, Safari

### Source

External (Customer)

**Comment by tnorling** [comment]
### Redirect Case

Temporary cache entries are stored in sessionStorage before redirecting and retrieved after the redirect. In this case handleRedirectPromise is not finding those entries in sessionStorage after the redirect. This can happen if your redirectUri is on a different domain than your starting location or if you have logic clearing sessionStorage somewhere. You may have to do some debugging on your end to see what might be happening.


### Popup Case

The logs appear to have been collected from inside the popup? Can you confirm? If so, please collect the logs from the frame making the request instead.

**Comment by theviveik1** [comment]
**I'm encountering a similar problem where, after logging out and attempting to log back into the application, the redirection doesn't take me to the intended page. Instead, it gets stuck with the callback URL information.**

http://localhost:4200/#code=0.AREAdGla839g1EeC1_8x19xTpZmlzPh4xtlIkT-4jeRedpURAGo.AgABAAIAAAAtyolDObpQQ5VtlI4uGjEPAgDs_wUA9P-rJYuYvfrSEXxdx6uliiC2rUjYvjcpj9ii6HS4F1mrCqou1dwkMeQ4oHwdLl_Cql2lK2CIYDEx4DHTNX-Ty8LkcOFCTcrpAi1Dw9FuT9ORnR1WEgRTeOgQehps37iqseyEpl2xrSCeuuYHI96h3ybrXnb4Aa9OH61HBkreo5jy9MpX8wlNApaMb2L43V0byvy345-WgcOkFHKodNoAM4TfsN4-_SNXn4hmnM-t83Ot69B5EWZOB_tzpPCLQLyicDL3AxYpOAFReRVimazJu1atlJJa42wUcbpRaPG9SU0eXMexeWzRjT_mAXv0DMEN52YCybMOZn8PNpOREgQ13ZRoKxKQ_yqcPmhXwXhNVv0pfb8Af91FBGjvRftppXuCbUtMtCw7s_6dYz_N_3nzPv3Rmiwte0QKijw6OH85E6Yi1P_3j6afrXnH7Z_roUb-sT2-snUEQmpq7fR0PzdR-yc7fULc13fwUkFSP75FZTCjTLDAryO79u-1b_Y3H7bSctlT0OnIKwEECkN_fhRLmlTrITwnaewbDHGIL_ridhEEhbqBZP1dFd0hhKMItwRKOLfSpL60qqBK_nLWMNldFI-lj87uFeeWaQt9yU3I9GSI9F5PcX1BRi25mpnDvIVb7FASBt3pP0vjLz4rPy_ffqfhjw1pD143A40EjXh1qh7K3Jl0mmbJApQsAwcIS98E-50EGB55Ww-Svh13Lx80bmzWBRj0InnmrDyjQ9LBeEgDKUSlmiesnSRiO1IFTGPe7Du7oH9JltnaYC1c38DI93GDQtl4iN6GxIiqE8ue1vCIlbtkhrNNvhPe_K3hbUv1aT1ohlApN9bgwmyoIDgJsrSyMlkyevIshNqUsV8TUMshM13x6JNIwQMdh2AwRSqiHA36gW2uW_CIbrAStRyrtdYyvPB3IjFbD7gbIW4838Y7gylX8J85sWpTKObh4x6cvbKI1PirrwIKD6bJZi3JTLZkq13cOSWHcjvqXO5j5C64AXt846bvyM8w7jTXq77L7dUA3KTXJ5S--LFsU4w&client_info=eyJ1aWQiOiIxNmYwNWViYS04MjllLTRlMDEtOWFlOC00ODEzODMyNGZmYTkiLCJ1dGlkIjoiZjM1YTY5NzQtNjA3Zi00N2Q0LTgyZDctZmYzMWQ3ZGM1M2E1In0&state=eyJpZCI6ImEyNjk2ZjQ1LWJiM2ItNDYzYy04YWU3LWJlNzczMDFhMWExOCIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicmVkaXJlY3QifX0%3d&session_state=490cee73-46ff-4669-b7d6-8e96366ee86d

**Comment by aNyMoRe0505** [comment]
@tnorling 
Hi, thank you for your response.
After several tests, there are some findings, but I'm not sure if they are helpful.
- This situation does not occur every time. it's occasional but quite frequent
- The issue can only be reproduced when using Xcode iOS simulator or physical mobile devices (both Android and iOS). There are no problems when using desktop devices (Mac, Windows desktop)

### Popup Case
I found there are two scenarios for the popup case
One is when the window is successfully closed, but upon returning to the original window, the log shows a login failure.
<img width="1150" alt="截圖 2023-10-11 11 46 59" src="https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/9814815/c8397c67-eb6e-41f9-8a83-555696586c9c">

The other scenario is when the popup cannot be closed and remains stuck on the callback page
At this point, the log from the page making the request would look like this
<img width="880" alt="截圖 2023-10-11 12 03 35" src="https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/9814815/0dc9176b-4a4d-4d70-a1c0-6093348a8650">
The popup page will be the same as provided above (stuck on the callback page)
![272821787-90e72f18-ba38-4266-9c2c-774bbd6e0a40](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/9814815/82bbd9c7-945f-4226-9863-3d8b6c5a6385)



### Redirect Case

I can confirm that my redirectUri is within the same domain.
We do not have any code related to manipulating sessionStorage

**Comment by theviveik1** [comment]
Uncaught (in promise): BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API. For more visit: aka.ms/msaljs/browser-errors. BrowserAuthError: interaction_in_progress: Interaction is currently in progress

**### When above error message is coming?**

**Comment by tnorling** [comment]
@aNyMoRe0505 Something is clearing sessionStorage in both cases. You will need to set some breakpoints and debug what's happening. When MSAL starts the login flow it will drop a number of entries in sessionStorage you should confirm that is indeed happening and then try to see if you can trace where they get removed.

@theviveik1 Your issue is not related to this one. Please read [this doc](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/errors.md#interaction_in_progress) regarding interaction_in_progress errors and if you have further questions please post your question on StackOverflow. Thanks!

**Comment by aNyMoRe0505** [comment]
@tnorling  thank you for your response
I attempted to return null on the callback page to confirm if there are other scripts affecting sessionStorage.
```js
    if (pathname === Urls.account.AzureLoginCallback) {
      return null;
    }
```
After testing, everything seems to be functioning correctly. However, this approach causes the redirect case to fail. So, I update the code
```javascript
if (pathname === Urls.account.AzureLoginCallback) {
      return <MsalProvider instance={msalInstance}>hello</MsalProvider>;
    }
```

But this resulted in a scenario where the popup couldn't be closed, similar to the log and screenshot above. Is this behavior normal?

**Comment by tnorling** [comment]
Glad to hear you got popup working by returning null. This is actually in-line with our recommended best practice for popups. As for it breaking again when returning the MsalProvider, no that's not normal. Why do you need to support both popups and redirects?

**Comment by aNyMoRe0505** [comment]
@tnorling 
Thank you for your response
I think the key point should be why returning `MsalProvider` is causing this issue.
We will support users to use either redirect or popup based on different contexts
In theory, this package should support both methods, right?

**Comment by tnorling** [comment]
I agree this is unexpected and will need a closer look. I'm not able to repro this behavior with my own apps so it would be helpful if you could you put together a minimal repro and share the link with me.

We do support both methods, however, we don't usually recommend that apps use both concurrently. Recommended best practice is to pick one based on the user experience you would like to have and stick to that.

**Comment by aNyMoRe0505** [comment]
@tnorling Thank you for your response.
I will find some time to try creating a reproducible example. Additionally, can I attempt to change the redirect page to an HTML page and then navigate to the next app's page once successful? 

like this: https://github.com/Azure-Samples/ms-identity-javascript-v2

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/cdn-usage.md

**Comment by tnorling** [comment]
Sure you can use a simple HTML page as long as it's hosted on the same domain as the rest of your app. You should not implement any sort of navigation, however, that will definitely cause you more problems. For popups don't do anything at all on the redirectUri page, for redirects just render MsalProvider or invoke handleRedirectPromise.

**Comment by aNyMoRe0505** [comment]
@tnorling 
Thank you for your response.
If my callback page is named callback.html, how can I determine whether the current request is a popup or a redirect? Does handleRedirectPromise handle this automatically?
Thank you

```javacript
const myMSALObj = new window.msal.PublicClientApplication(msalConfig);

myMSALObj
  .initialize()
  .then(() => myMSALObj.handleRedirectPromise())
  .then(response => {
    console.log('response', response);
  })
  .catch(error => {
    console.log(error);
  });
```

After testing, I found that logging in with a popup flow on a mobile device and redirecting to an HTML page using handleRedirectPromise leads to getting stuck on the callback page, and the hash disappears. Does this mean I need to create two separate redirect HTML files (one for redirect, one for popup)?

**Comment by Aichnerc** [comment]
> Glad to hear you got popup working by returning null. This is actually in-line with our recommended best practice for popups. As for it breaking again when returning the MsalProvider, no that's not normal. Why do you need to support both popups and redirects?

As for me, calling `instance.loginPopup` **sometimes** doesn't open a new popup but a new tab. This has happened in different browsers for me. I can't seem to reproduce when a popup is opened and when a new tab. If that happens, the entire login flow breaks. The "popup" new tab redirects me to my application at the login screen, where I can't log in because obviously, I'm currently in the login popup. If I close that tab, the login on the initial tab fails because `User cancelled the flow.`.

**Comment by aNyMoRe0505** [comment]
why this issue close ..?

**Comment by devpolo** [comment]
Hi @aNyMoRe0505 
Did you manage to return on the desktop app after calling `loginRedirect`?

**Comment by aNyMoRe0505** [comment]
@devpolo 
Sorry for the late reply
No, I don't manage the return logic. The azure SDK will handle it automatically
Or you can handle it manually, I remember there is an option you can config
