### ISSUE TITLE
Accessing the logged-in user's token cache from background apps, APIs and services

### ISSUE THREAD

**Issue by sotyo0514** [AzureAD/microsoft-authentication-library-for-js#6551]
### Core Library

MSAL Node (@azure/msal-node)

### Wrapper Library

MSAL Node Extensions (@azure/msal-node-extensions)

### Public or Confidential Client?

Public

### Description

I want to create the same system as below in node-js with SQL server or Redis.
https://github.com/Azure-Samples/ms-identity-dotnet-advanced-token-cache/blob/master/README.md

I find following sample in node-js, However, this uses confidential client application. I want to use public client because of not admin consent.
https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/client-credentials-distributed-cache

Finally, I want to use Graph API on serverless application(background app) with Node-JS using sample.
Do you have the sample of Background app and Webapp using public client?
If not, Could you point me to an existing implementation that would serve as a good reference? 

### Source

External (Customer)

**Comment by tnorling** [comment]
This request doesn't make a whole lot of sense to me. 

PublicClientApplication = Application is running on the client
ConfidentialClientApplication = Application is running on some remote device

Distributed cache is relevant to remotely hosted applications, it's not needed or feasible for public clients.

To summarize: if your application is hosted remotely use ConfidentialClientApplication where you can implement distributed cache, in which case the sample you linked would be the one I suggest. If, on the other hand, your application is running directly on the client use PublicClientApplication and you can use msal-node-extensions to persist the cache to disk, samples: [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/extensions/samples)
