### ISSUE TITLE
React. How to prevent user seing double sign-in dialog when enabling automatic user sign-in?

### ISSUE THREAD

**Issue by henrik-me** [AzureAD/microsoft-authentication-library-for-js#6553]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.0.4

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2

### Public or Confidential Client?

Public

### Description

Exploring how to enable users to automatically sign-in when they enter my SPA application (and not seeing the sign-in twice). 

Instead of having the user click a button for signing in (this works), I want to have the user automatically signed-in. When attempting this I get the user sign-in dialog twice. I tried searching for similar issues but was not able to find any.  

Currently attempting to:
```
 const { instance } = useMsal();
  const isAuthenticated = useIsAuthenticated();

  useEffect(() => {
    if (!isAuthenticated) {
      instance.loginRedirect({ redirectUri: `${window.location.origin}/signup`, ...loginRequest});
    }
  });

``` 

Note: I am using local storage

Looked at this older thread on SO:
https://stackoverflow.com/questions/67097663/react-app-using-msal-react-how-to-automatically-authenticate-user

The thread on SO didn't help and it seems like existing samples doesn't do this either. 

A link to a sample with this behavior would be great. I have not been able to find one that does this.

### Relevant Code Snippets

```javascript
see description for snippet.
```

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
You need to check that inProgress == "None" prior to invoking any interactive API. I'm making an educated guess that you're hitting a race condition between invoking interaction and handling the response from the last interaction. 

Try this:
```
 const { instance, inProgress } = useMsal();
  const isAuthenticated = useIsAuthenticated();

  useEffect(() => {
    if (!isAuthenticated && inProgress == InteractionStatus.None) {
      instance.loginRedirect({ redirectUri: `${window.location.origin}/signup`, ...loginRequest});
    }
  }, [isAuthenticated, inProgress]);
```

The other possibility, if it's happening exactly twice every time, is React Strict Mode which causes effects to run twice. The solution above should also address this since inProgress will block the 2nd call from executing.
