### ISSUE TITLE
Cannot save auth information in local storage

### ISSUE THREAD

**Issue by fonts1215** [AzureAD/microsoft-authentication-library-for-js#6555]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.38.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

I've go a teams app written in react, that use a SSO, but after a chrome update, the app doesn't set anything inside the local storage. Token is release successfully and is valid, but the information are not stored. I tried with a old chrome version, same machine, same baseline, and everthings works perfect. 

### MSAL Configuration

```javascript
{
            auth: {
                clientId: config.clientId,
                authority: Config.authority,
                redirectUri: config.redirectUri
            },
            cache: {
                cacheLocation: "localStorage",
                storeAuthStateInCookie: true,
            }
        }
```

### Relevant Code Snippets

```javascript
----
```

### Reproduction Steps

Teams app, with SSO inside new chrome version

### Expected Behavior

Chrome version --- 117

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by tnorling** [comment]
We unfortunately can't help with browser related issues/debugging. I would suggest posting your question on StackOverflow.
