### ISSUE TITLE
Please add v3.x CDN releases

### ISSUE THREAD

**Issue by lostmsu** [AzureAD/microsoft-authentication-library-for-js#6556]
### Core Library

MSAL.js (@azure/msal-browser)

### Wrapper Library

Not Applicable

### Public or Confidential Client?

Public

### Description

Extracting libraries from npm is pain.

### Source

External (Customer)

**Comment by tnorling** [comment]
We made a conscious decision to stop publishing our packages to our own CDN. We still publish the umd builds to npm which you can host on your own CDN or use a public CDN like [Unpkg](https://unpkg.com/)
