### ISSUE TITLE
Can't import the named export 'CryptoOps' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by puya91** [AzureAD/microsoft-authentication-library-for-js#6558]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.2.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

not applicable

### Public or Confidential Client?

Confidential

### Description

I am trying to update MSAL library (@azure/msal-browser) in my react app to v3.x (specifically from 2.14.2 to 3.2.0) but gives me this error after npm start:

./node_modules/@azure/msal-browser/dist/crypto/SignedHttpRequest.mjs Can't import the named export 'CryptoOps' from non EcmaScript module (only default export is available)

How can I fix this problem?

The reason why I want to update my MSAL library: Since the latest update of Google Chrome my Teams web app project shows a login popup for any API calls. It shows a popup every time for a second, verifies by itself, and goes away. I can see that my Local Storage is empty and clientIds are not already saved.

After updating to @azure/msal-browser@3.2.0 I expected to resolve my problem with the popup shown in my Teams web app. However, I have a problem executing the app. It gives me the compile error I mentioned above.

### MSAL Configuration

```javascript
auth: {
                clientId: config.clientId,
                authority: Config.authority,
                redirectUri: config.redirectUri
            },
     cache: {
                cacheLocation: "localStorage",
                storeAuthStateInCookie: false,
            }
```

### Identity Provider

None

### Source

External (Customer)

**Comment by tnorling** [comment]
Make sure your bundler recognizes .mjs file extensions as modules

**Comment by puya91** [comment]
In the end, we resolved it simply by disabling "Experimental third-party storage partitioning" Google Chrome flag feature.

**Comment by puya91** [comment]
In the end, we resolved it simply by disabling "Experimental third-party storage partitioning" Google Chrome flag feature.
