### ISSUE TITLE
MSAL & SignalR B2C 401 issues

### ISSUE THREAD

**Issue by zachsteffens** [AzureAD/microsoft-authentication-library-for-js#6559]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.2.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.5

### Public or Confidential Client?

Public

### Description

I'm trying to implement SignalR in my app. 
The app is using azureADB2C for authentication and besides the SignalR, everything works flawlessly.
Also of note is that the api runs in a Docker Container when running locally and will run in as a Containerized App Service when deployed to Azure.

### Relevant Code Snippets

I've figured out how to attach the token to the HubConnectionBuilder
```javascript


public startConnection = (accessToken: string) => {
    this.hubConnection = new signalR.HubConnectionBuilder()
      .configureLogging(signalR.LogLevel.Debug)
      .withUrl('https://localhost:64642/optimizationHub', {
        accessTokenFactory: () => accessToken
      })
      .build();
    this.hubConnection
      .start()
      .then(() => console.log('Connection started'))
      .catch((err) => console.log('Error while starting connection: ' + err));
  };
```
That got me past the first hurdle but now I'm getting a 401 error on the eventsorce type call in my network monitor.

So the 401 sent me down a rabbit hole trying to figure out how to properly validate and authorize the token passed in with the signalR connection.  I tried a few different variations of the [Authorize] tag on my hub class to no avail.

Below i've included what seem to be the relevant pieces from the API's **program.cs** file.  I'm hoping I'm just missing something simple or using the wrong authentication classes and that's why SignalR is complaining?
```
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
       .AddMicrosoftIdentityWebApi(builder.Configuration.GetSection("AzureADB2C"));

...

builder.Services.AddSignalR();

...

app.MapControllerRoute(
                name: "default",
                pattern: "{controller=Home}/{action=Index}/{id?}");

app.MapHub<OptimizationHub>("/optimizationHub");
```

And my controller methods are authorized with the following tag
`[RequiredScope(RequiredScopesConfigurationKey = "AzureAd:Scopes")]`
```


### Identity Provider

Azure B2C Basic Policy

### Source

External (Customer)

**Comment by zachsteffens** [comment]
New developments: 

It appears that Long Polling works, but this is not desirable.

The API container has Linux selected as it's DockerOS and is using `mcr.microsoft.com/dotnet/aspnet:7.0` as it's base image. I'm trying to determine if my issues are related to this [issue](https://github.com/dotnet/aspnetcore/issues/10370)

**Comment by tnorling** [comment]
This doesn't look related to MSAL.js. We don't have any recommendations around integrating with SignalR, I'd recommend working with SignalR first and then let us know if there's something specific we can help you with in regards to MSAL.js
