### ISSUE TITLE
How do I prevent 'state_not_found' error.

### ISSUE THREAD

**Issue by grosch-intl** [AzureAD/microsoft-authentication-library-for-js#6561]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.10

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.4

### Public or Confidential Client?

Public

### Description

I keep getting this error:

main.ts:51 ClientAuthError: state_not_found: State not found:  Cached State
    at ClientAuthError.createStateNotFoundError (ClientAuthError.mjs:301:16)
    at RedirectHandler.mjs:84:35
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:22:1)
    at asyncToGenerator.js:27:1
    at new ZoneAwarePromise (zone.js:1411:21)
    at asyncToGenerator.js:19:1
    at RedirectHandler.handleCodeResponseFromHash (RedirectHandler.mjs:124:30)
    at RedirectClient.mjs:231:41

I have to go to Applications -> Storage and then clear site data to "fix" it.

### MSAL Configuration

```javascript
{
    auth: {
        clientId: environment.azure.clientId,
        authority: 'https://login.microsoftonline.com/46c98d88-e344-4ed4-8496-4ed7712e255d',
        redirectUri: window.location.origin
    }, cache: {
        cacheLocation: BrowserCacheLocation.LocalStorage,
        storeAuthStateInCookie: false,
        claimsBasedCachingEnabled: true
    }, system: {
        allowNativeBroker: false, // Disables WAM Broker
        loggerOptions: {
            piiLoggingEnabled: false,
            logLevel: LogLevel.Error, loggerCallback: (level, message, containsPersonallyIdentifiableInformation) => {
                if (containsPersonallyIdentifiableInformation)
                    return

                switch (level) {
                    case LogLevel.Error:
                        console.error(message)
                        return
                    case LogLevel.Info:
                        console.info(message)
                        return
                    case LogLevel.Verbose:
                        console.debug(message)
                        return
                    case LogLevel.Warning:
                        console.warn(message)
                        return
                    default:
                        console.log(message)
                        return
                }
            }
        }
    }
```

### Relevant Code Snippets

```javascript
export const provideAzure = () => makeEnvironmentProviders([
    {
        provide: APP_INITIALIZER,
        useFactory: (msalService: MsalService) => async () => {
            await publicClientApplication.initialize()

            const redirect = await msalService.instance.handleRedirectPromise()
            if (redirect?.account)
                msalService.instance.setActiveAccount(redirect.account)
            else {
                let accounts = msalService.instance.getAllAccounts()

                if (accounts.length === 0) {
                    await firstValueFrom(msalService.loginRedirect())
                    accounts = msalService.instance.getAllAccounts()
                }

                msalService.instance.setActiveAccount(accounts[0])
            }

            Providers.globalProvider = new Msal2Provider({publicClientApplication})
        },
        multi: true,
        deps: [MsalService]
    },
    {provide: HTTP_INTERCEPTORS, useClass: MsalInterceptor, multi: true},
    MsalService,
    MsalGuard
])
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by tnorling** [comment]
Temporary request artifacts are stored in sessionStorage before redirecting and then read after returning. This error is thrown when handleRedirectPromise begins to process the response from a redirect but is unable to find those temporary entries again in sessionStorage. This usually means you have a race condition somewhere. I'd see if you can trace where sessionStorage is being updated.

**Comment by grosch-intl** [comment]
@tnorling Can you provide guidance on how to do that please?  The code I showed is the only area where I handle the Azure stuff. At the suggestion of a colleague, I tried adding this to my `useFactory` method, but that resulted in an infinite reload loop:

```typescript
msalBroadcastService.msalSubject$
    .pipe(
        filter(x => x.eventType === EventType.ACQUIRE_TOKEN_FAILURE),
        takeUntilDestroyed(destroyRef)
    )
    .subscribe(() => msalService.loginRedirect())
```

**Comment by tnorling** [comment]
Set a breakpoint somewhere at the very beginning of your page load, check sessionStorage to see if temporary cache entries are present. If they are, start stepping through until they get removed. If they're not there, set the breakpoint where you invoke login and start stepping through till they're added and continue to step through until the redirect to make sure they don't get removed before the redirect.

**Comment by grosch-intl** [comment]
@tnorling So I think I got this figured out.  The app won't work at all unless they're authenticated, and so the provider is triggering the authentication.  When they load a route, which is protected by the `MsalGuard`, it'll fail, go get a token...and then redirect them to the home page, instead of the route they tried to go to. 

At that point, the source and destination don't match, and the strange error appears.  I removed all the `MsalGuard` protections and I haven't had the issue since.  I also stuck that broadcast subscription back in to handle issues where the page sat so long that the refresh token is also no good.

If you think that makes sense for what the issue really was, we can go ahead and close this issue.

**Comment by tnorling** [comment]
hmm source and destination not matching shouldn't cause a state_not_found unless these are on different domains, which isn't supported anyway.

To help explain the routing behavior - The service will redirect you back to your redirectUri (in this case I'm assuming that's your home page). handleRedirectPromise should run on the page set as your redirectUri and if a response hash is present in the url & it's able to find those temporary cache entries it will redirect you back to the source route. On the source route, handleRedirectPromise should be run again and this time will handle the response hash and your user should be signed in at this point.

I don't think source != dest is the cause of your state_not_found error. Rather I think it's the opposite.

I'll also note that the page you use as your redirectUri should not be protected by the Guard. That may be part of the issue if removing the Guard solved this for you.

**Comment by kudorgyozo** [comment]
Thanks for the suggestion to remove MsalGuard. That caused the problem. I've spent an entire day on this.
