### ISSUE TITLE
I to change in query url params "response_mode" = "fragment" but wants "response_mode" = "query" & "response_type" = "code"  but wants "response_type" = "id_token" 

### ISSUE THREAD

**Issue by brijeshkothari6492** [AzureAD/microsoft-authentication-library-for-js#6564]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.26.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.2

### Public or Confidential Client?

Public

### Description

1. Package.json 
package.json
  "dependencies": {
    "@azure/msal-browser": "^2.26.0",
    "@azure/msal-react": "^1.4.2",
    }
2. In index.js 

const msalInstance = new PublicClientApplication(msalConfig);

  ReactDOM.hydrate(
    <Provider store={store}>
      <MsalProvider instance={msalInstance}>
        <BrowserRouter>
          {/* <AzureAdLogin instance={msalInstance}> */}
            <App />
          {/* </AzureAdLogin> */}
        </BrowserRouter>
      </MsalProvider>
    </Provider>, document.getElementById('root')
  );

3. Home.js - Page where on componentDidMount we need to redirect user to login of 3rd party client azure ad b2c login page

import { useMsal } from "@azure/msal-react";
import React, { useState, useEffect } from "react";

Here system prepare url like below 
xxxxxx?clientId=xxxx
&scope=openid profile offline_access
&redirect_uri=https://subdomain.domain.com/
&client-request-id=xxxxxx
&response_mode=fragment
&response_type=code
&x-client-SKU=msal.js.browser
&x-client-VER=2.38.2
&client_info=1
&code_challenge=2zCil27BuMIaG9yi__C4Sg5UaiTngJq30_2ECIjpjd4
&code_challenge_method=S256
&nonce=3bfed1c6-0b97-4d01-b7a1-f4919a91040b
&state=eyJpZCI6IjBmNjkxNzk0LTZiMjctNGNkMi04NzQwLWY3YzAyM2RlNjM1MSIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicmVkaXJlY3QifX0

but client demands 

xxxxxx?clientId=xxxx
&scope=openid profile offline_access
&redirect_uri=https://subdomain.domain.com
&client-request-id=xxxxxx
**&response_mode=query
&response_type=id_token**
&x-client-SKU=msal.js.browser
&x-client-VER=2.38.2
&client_info=1
&code_challenge=2zCil27BuMIaG9yi__C4Sg5UaiTngJq30_2ECIjpjd4
&code_challenge_method=S256
&nonce=3bfed1c6-0b97-4d01-b7a1-f4919a91040b
&state=eyJpZCI6IjBmNjkxNzk0LTZiMjctNGNkMi04NzQwLWY3YzAyM2RlNjM1MSIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoicmVkaXJlY3QifX0

I have checked with library and tried

const signInRequestObject = {
        "responseMode" : "query",
          "responseType":"id_token",
        // "scopes" : []
    };
    if (window.DEBUG) console.log("#19 signInRequestObject ", JSON.stringify(signInRequestObject));
    await instance.loginRedirect(signInRequestObject);
    
    but this not making change in response_mode & response_type as it was earlier.
    
    

### Error Message

Please help me to prepare url query params changes with library as below 

**&response_mode=query
&response_type=id_token**

### Msal Logs

No logs available

### MSAL Configuration

```javascript
{
  auth: {
    clientId: "clientId", // This is the ONLY mandatory field that you need to supply.
    authority:
      "https://{{tenantId}}.b2clogin.com/{{tenantId}}.onmicrosoft.com/B2C_1A_SIGNUP_SIGNIN", // Choose SUSI as your default authority. here Custom Policy name is B2C_1A_SIGNUP_SIGNIN which works fine on Identity Experience Framework
    knownAuthorities: ["{{tenantId}}.b2clogin.com"], // Mark your B2C tenant's domain as trusted.
    redirectUri: "https://subdomain.domain.com", // You must register this URI on Azure Portal/App Registration. Defaults to window.location.origin
    postLogoutRedirectUri: "/", // Indicates the page to navigate after logout.
    navigateToLoginRequestUrl: false, // If 'true', will navigate back to the original request location before processing the auth code response.
  },
  cache: {
    cacheLocation: "sessionStorage", // Configures cache location. 'sessionStorage' is more secure, but 'localStorage' gives you SSO between tabs.
    storeAuthStateInCookie: false, // Set this to 'true' if you are having issues on IE11 or Edge
  },
}
```

### Relevant Code Snippets

```javascript
const signInRequestObject = {
        "responseMode" : "query",
          "responseType":"id_token",
        // "scopes" : []
    };
    if (window.DEBUG) console.log("#19 signInRequestObject ", JSON.stringify(signInRequestObject));
    await instance.loginRedirect(signInRequestObject);
    
    but this not making change in response_mode & response_type as it was earlier.
```

### Reproduction Steps

Sorry can't disclose video / code snippet for security reason

### Expected Behavior

URL includes 

"response_mode" = "fragment" comes up but he suggested to change it to "response_mode" = "query"

"response_type" = "code"  comes up but he suggested to change it to "response_type" = "id_token" 

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer

### Source

External (Customer)

**Comment by tnorling** [comment]
MSAL.js does not support any response types other than code nor do we recommend using response_mode=query, you should configure your custom policy to respect response_mode=fragment and response_type=code instead.
