### ISSUE TITLE
MsalGuard prevents loading of page on first access

### ISSUE THREAD

**Issue by grosch-intl** [AzureAD/microsoft-authentication-library-for-js#6569]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.1.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.4

### Public or Confidential Client?

Public

### Description

When adding `canMatch: [MsalGuard]` to my route, I'm not able to get to a specific page on first load.  There's no token, and so the redirect stuff happens to get a token. However, because the route couldn't match, after getting a token, it then takes me to the home page of the app, instead of redirecting back to the page that tried to load.

### MSAL Configuration

```javascript
{
auth: {
        clientId: environment.azure.clientId,
        authority: 'https://login.microsoftonline.com/46c98d88-e344-4ed4-8496-4ed7712e255d',
        redirectUri: window.location.origin
    }, cache: {
        cacheLocation: BrowserCacheLocation.LocalStorage,
        storeAuthStateInCookie: false,
        claimsBasedCachingEnabled: true
```

### Relevant Code Snippets

```javascript
export const routes: Routes = [
    {path: '', pathMatch: 'full', component: HomeComponent},
    {
        ...barcodeRoute(),
        canMatch: [MsalGuard],
        canDeactivate: [pendingChangesGuard],
        loadComponent: () => import('./app/display/display-root/display-root.component')
            .then(x => x.DisplayRootComponent)
    }
```

### Reproduction Steps

Clear site storage so I have no cookie, then type in a URL that would match the `barcodeRoute` regex from above.

### Expected Behavior

Get a token and then load the exact same page that I typed into the URL, or link I clicked on.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by tnorling** [comment]
Apologies that this hasn't been addressed. Is this still causing issues? If so try turning on verbose PII logging and look for a log message that starts with "Redirect start page:" - this will tell you where MSAL _thinks_ it should return you to after the redirect. If that's the correct value but it's not working we'll need the full logs to understand why it failed. If it's _incorrect_ that may be a bug but you can try passing redirectStartPage explicitly on the msalGuard authRequest to workaround.
