### ISSUE TITLE
Include client_id in logout request

### ISSUE THREAD

**Issue by enqueue** [AzureAD/microsoft-authentication-library-for-js#6574]
### Core Library

MSAL.js (@azure/msal-browser)

### Wrapper Library

Not Applicable

### Public or Confidential Client?

Public

### Description

For usage with Azure B2C it is useful to include the `client_id` query parameter in the call to OAuth2 logout endpoint.

Popular setups, e.g. ones based on previous versions of the B2C custom policy starter pack, have a [SSO scope Application](https://learn.microsoft.com/en-us/azure/active-directory-b2c/session-behavior?pivots=b2c-custom-policy#configure-azure-ad-b2c-session-behavior), e.g. like this:

```xml
<UserJourneyBehaviors>
     <SingleSignOn Scope="Application" />
     <SessionExpiryType>Absolute</SessionExpiryType>
    <SessionExpiryInSeconds>86400</SessionExpiryInSeconds>
</UserJourneyBehaviors>
```

This means, that a session is maintained per Application, and when receiving a sign-out request, the B2C server needs to identify the Application to clear the session for. The Application is identified by `client_id` query parameter unless a `id_token_hint` is provided, see [Send a sign-out request documentation](https://learn.microsoft.com/en-us/azure/active-directory-b2c/openid-connect#send-a-sign-out-request):

>  client_id | No* | The application ID that the Azure portal assigned to your application. *This is required when using Application isolation SSO configuration and Require ID Token in logout request is set to No.

If the B2C server cannot resolve the correct Application, the session will not be terminated.

Of course, we could also try and include the `id_token_hint`, but this requires additional work and configuration. The `client_id` is already part of the most common MSAL configurations.

We can also include `extraQueryParameters`, but the `client_id` is already known to the MSAL configuration.

### Source

External (Customer)

**Comment by tnorling** [comment]
Given this is a B2C specific parameter I don't want to add this automatically on all requests and since MSAL already provides 2 ways you can add this yourself (id_token_hint or extraQueryParameters) I'm going to close this as wont-fix.
