### ISSUE TITLE
After the authentication is  successful  the URL fragment #Code = adgahg........... doesn't get automatically removed. 

### ISSUE THREAD

**Issue by kumardeepak123** [AzureAD/microsoft-authentication-library-for-js#6575]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

18.15.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

NA

### Public or Confidential Client?

Public

### Description

After the authentication is  successful  the URL fragment **#Code = adgahg...........** doesn't get automatically removed. So My application default route (home route) is not getting hit. I am facing this issue on _Microsoft edge_ only.

> Tech stack used

- Backbone.js
- .NET core
- EF Core
- Azure

### MSAL Configuration

```javascript
var msalConfig = {
    auth: {
        clientId: Azure.ClientId,  Consultation Application Id 
        instance: Azure.TenantHostUrl,
        redirectUri: window.location.origin + '/',
        tenant: Azure.TenantId, 
        authority: 'https://login.microsoftonline.com/' + Azure.TenantId
    },
    cache: {
        cacheLocation: 'sessionStorage',
        storeAuthStateInCookie: true,
    },
    system: {
        loggerOptions: {
            loggerCallback: (level, message, containsPii) => {
                if (containsPii) {
                    return;
                }
                switch (level) {
                    case Msal.LogLevel.Error:
                        console.error(message);
                        return;
                    case Msal.LogLevel.Info:
                        console.info(message);
                        return;
                    case Msal.LogLevel.Verbose:
                        console.debug(message);
                        return;
                    case Msal.LogLevel.Warning:
                        console.warn(message);
                        return;
                }
            },
        }
    }
};
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by trungthecelestial** [comment]
Have same issue with latest nextjs and @azure/msal-react.

**Comment by kumardeepak123** [comment]
This issue occurs only with Microsoft edge.

**Comment by tnorling** [comment]
Please share verbose level logs, there's not enough information here for us to help you.

Also please confirm the version of msal-browser you are using, the one listed in the issue doesn't exist.
