### ISSUE TITLE
SuccessTemplate not being displayed in browser

### ISSUE THREAD

**Issue by ghost** [AzureAD/microsoft-authentication-library-for-js#6595]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

2.2.0

### Wrapper Library

MSAL Node Extensions (@azure/msal-node-extensions)

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

After invoking `PublicClientApplication.acquireTokenInteractive()` the token get's properly processed, but once the following code gets executed, neither the expected `successTemplate` nor the `errorTemplate` provided to `acquireTokenInteractive()` get displayed and the browser tab ends up at the "This site can't be reached" page which gives a wrong impression to the user.
```
File: ..\node_modules\@azure\msal-node\src\client\PublicClientApplication.ts
226:             loopbackClient.closeServer();

```
### Potential issue
```
File: node_modules\@azure\msal-node\dist\network\LoopbackClient.cjs
34:                 else if (url === msalCommon.Constants.FORWARD_SLASH) {
```
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/64540984/313986ac-1ef2-421a-b3d5-c3f36976bd5c)

Seems as if this should rather be something along the lines of `else if (url[0] === ...`

Please see "Reproduction Steps" for more details.

### Error Message

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/64540984/4a15fbe7-41db-4f1a-9e25-96b4b1d6552c)

### MSAL Configuration

```javascript
auth: {
	  clientId: DevOpsAuthConfig.clientId,
	  authority: DevOpsAuthConfig.tenantId,
  },
  system: {
	  loggerOptions: {
		  loggerCallback(_logLevel: LogLevel, message: string, _containsPii: boolean) {
			  logMessage("DevOpsAuth", "I", message);
		  },
		  piiLoggingEnabled: false,
		  logLevel: LogLevel.Info,
	  }
  },
  cache: { <instance of ICachePlugin>}
```

### Relevant Code Snippets

```javascript
File: node_modules\@azure\msal-node\dist\network\LoopbackClient.cjs
34:                 else if (url === msalCommon.Constants.FORWARD_SLASH) {
```

### Reproduction Steps

**Within VSCode Extension execute:**

```
const pca = new PublicClientApplication({
  auth: {
	  clientId: DevOpsAuthConfig.clientId,
	  authority: DevOpsAuthConfig.tenantId,
  },
  system: {
	  loggerOptions: {
		  loggerCallback(_logLevel: LogLevel, message: string, _containsPii: boolean) {
			  logMessage("DevOpsAuth", "I", message);
		  },
		  piiLoggingEnabled: false,
		  logLevel: LogLevel.Info,
	  }
  },
  cache: { <instance of ICachePlugin>}
});

const authentication = await pca.acquireTokenInteractive({
	openBrowser: async url => vscode.commands.executeCommand('vscode.open', vscode.Uri.parse(url)),
	scopes,
	successTemplate: 'XYZ has been granted access to DevOps! You can close this window now.',
	errorTemplate: "XYZ hasn't been granted access to DevOps. You can close this window now.",
});
```

### Expected Behavior

Success- or error template to be displayed properly in browser tab.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

External (Customer)

**Comment by jetwiwo** [comment]
Additional information: I experience the same issue when running in my usual node version. The first time I tried this, I accidentally ran my application in node v16.20.0 (not supported by msal according to package.json) and the template was displayed. After returning to my usual node v18.18.2 the template is not displayed. I also tested in a few other versions and got the following results:

v16.20.0 - template is displayed
v18.18.2 - ERR_CONNECTION_REFUSED
v20.8.1 - ERR_CONNECTION_REFUSED
v21.0.0 - ERR_CONNECTION_REFUSED
