### ISSUE TITLE
Front-channel logout doesn't work as expected

### ISSUE THREAD

**Issue by kevinvugts** [AzureAD/microsoft-authentication-library-for-js#6597]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.3.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.0.5

### Public or Confidential Client?

Public

### Description

As stated per [docs](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md#front-channel-logout) we should be able to logout a user from all authenticated sessions of a specific app(s) with Azure AD. However, after following all required steps, only the app that initiated the logout request, logged out correctly.

When inspecting the chrome devtools I do see the GET request to the other apps that need to be logged out. As stated per docs this is being done by loading an invisible iframe. So that works as expected as far as I am concerned. The console.log in my Logout.jsx is also being called correctly. However, no sign out appeared.

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/17518874/3df35146-9866-4682-94e3-994b6d69dee2)

Here are the settings for my app registration in Azure AD

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/17518874/e87b9e0d-47d5-4645-bcbb-8e2ad3f66fe2)

### Error Message

No error shown. But authenticated session in other apps remains in place. Which shouldn't happen.
However, when I load an iframe myself from app-1 itself for example it does remove the session. When the iframe is loaded from app-2 the session isn't removed. 

App 1 is hosted on https://dbm.localhost:3001
App 2 is hosted on https://localhost:3000 

### MSAL Configuration

```javascript
export const msalConfig = {
  auth: {
    clientId: "hidden for security purposes", // This is the ONLY mandatory field that you need to supply.
    redirectUri: "/", // You must register this URI on Azure Portal/App Registration. Defaults to window.location.origin
    postLogoutRedirectUri: "/", // Indicates the page to navigate after logout.
    clientCapabilities: ["CP1"], // this lets the resource owner know that this client is capable of handling claims challenge.
  },
  cache: {
    cacheLocation: "localStorage", // sessionStorage has the same result
    storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
  },
  system: {
    allowRedirectInIframe: true,
    loggerOptions: {
      loggerCallback: (level, message, containsPii) => {
        if (containsPii) {
          return;
        }
        switch (level) {
          case LogLevel.Error:
            console.error(message);
            return;
          case LogLevel.Info:
            console.info(message);
            return;
          case LogLevel.Verbose:
            console.debug(message);
            return;
          case LogLevel.Warning:
            console.warn(message);
            return;
        }
      },
    },
  },
};
```

### Relevant Code Snippets

```javascript
Here is the code of the Logout.jsx page that is included in the react-router as a route.

 React, { useEffect } from "react";
import { useMsal } from "@azure/msal-react";
import { BrowserUtils } from "@azure/msal-browser";

export function Logout() {
  const { instance } = useMsal();

  useEffect(() => {
    instance.logoutRedirect({
      account: instance.getActiveAccount(),
      onRedirectNavigate: () => !BrowserUtils.isInIframe(),
    });
  }, [instance]);

  return <div>Logout</div>;
}
```

### Reproduction Steps

1. Login to app on https://app-1.localhost:3000
2. Login to app on https://app-2.localhost:3001
3. Logout from app on https://app-1.localhost:3000
4. A GET request should happen to logout https://app-2.localhost:3001

### Expected Behavior

It should call the https://app-2.localhost:3001/logout (called app-1 and app-2 for demo purposes) url and actually removing the session/localstorage authenticated session of the user. 

This does work if you call the url manually. (https://localhost:3001/logout)

The code is being called in the iframe by Azure AD front-channel feature. However the localstorage/session storage isn't cleared on the actual app that needs to be logged out as well. This implies to me that the browser is blocking this because of the same origin policy. I might be wrong but that's just a thought that came up to my mind.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

Internal (Microsoft)

**Comment by kevinvugts** [comment]
Could anyone elaborate more on this if possible? Is the front-channel logout feature also enabled for regular Azure AD?

**Comment by tnorling** [comment]
I wonder if the iframe is being closed before your page has fully rendered and triggered the effect. I'd recommend trying a simple HTML page with no React or anything other than instantiating PublicClientApplication and invoking logoutRedirect.

**Comment by jnsnj** [comment]
I am experiencing the same issue. app2's front-channel logout URL is called but its local storage is not cleared. It seems to depend on the browser's handling of cookies. My results after testing in different browsers:

* Chrome 119: Local storage is not cleared regardless of allowing third-party cookies or not.
* Firefox 118: Local storage is cleared only if browser privacy is changed from _Standard_ to _Custom_ and changing blocked cookies from _Cross-site tracking cookies, and isolate other cross-site cookies_ to _Cross-site tracking cookies_.
* Safari 17: Local storage is cleared if _Prevent cross-site tracking_ is disabled.

If I am correct front-channel logout doesn't seem to be useful anymore since browsers have and are becoming more strict.

**Comment by kevinvugts** [comment]
> I wonder if the iframe is being closed before your page has fully rendered and triggered the effect. I'd recommend trying a simple HTML page with no React or anything other than instantiating PublicClientApplication and invoking logoutRedirect.

Hmm, I tried that one already. But it also doesn't seem to work.

**Comment by kevinvugts** [comment]
> I am experiencing the same issue. app2's front-channel logout URL is called but its local storage is not cleared. It seems to depend on the browser's handling of cookies. My results after testing in different browsers:
> 
> * Chrome 119: Local storage is not cleared regardless of allowing third-party cookies or not.
> * Firefox 118: Local storage is cleared only if browser privacy is changed from _Standard_ to _Custom_ and changing blocked cookies from _Cross-site tracking cookies, and isolate other cross-site cookies_ to _Cross-site tracking cookies_.
> * Safari 17: Local storage is cleared if _Prevent cross-site tracking_ is disabled.
> 
> If I am correct front-channel logout doesn't seem to be useful anymore since browsers have and are becoming more strict.

This sounds interesting. Could this be the reason @tnorling ? 
I am wondering if there are any alternatives for single sign out for Azure AD. 

Since browsers are making this harder and harder to rely on sessoin/cookie/local storage log out.

**Comment by tnorling** [comment]
Ah, yes this could definitely be the root cause. We unfortunately don't have any alternatives when tracking protections are on. The server's session cookie should still be cleared so re-auth would fail but any existing tokens floating around would continue to be accessible until expiry. 

You may consider using sessionStorage so that cache is cleared upon closing the tab. There's tradeoffs with that however so it'll be up to you if those tradeoffs are worth it.

**Comment by kevinvugts** [comment]
> Ah, yes this could definitely be the root cause. We unfortunately don't have any alternatives when tracking protections are on. The server's session cookie should still be cleared so re-auth would fail but any existing tokens floating around would continue to be accessible until expiry.
> 
> You may consider using sessionStorage so that cache is cleared upon closing the tab. There's tradeoffs with that however so it'll be up to you if those tradeoffs are worth it.

Hi @tnorling 

I am afraid the server side session is also not cleared. So token refreshes work just fine, which shouldn't be the case.

We have used sessionStorage already. But still the user needs to be logged out upon a page refresh.

**Comment by tnorling** [comment]
Do you happen to be using the Edge browser or Chrome browser with the Windows Accounts extension installed? If so you're likely being signed back in using your enterprise creds on device rather than with the session cookie.

**Comment by iv-al** [comment]
I have the same problem (we are using localStorage as cacheLocation, Chrome: 119.0.6045.124).

If I open the front-channel manually via url - the storage is cleared
But when it opens via iframe - it doesn't

But I found that the problem is in "Storage Partitioning", when I disable it in chrome://flags/#third-party-storage-partitioning - everything works

**Comment by kevinvugts** [comment]
> I have the same problem (we are using localStorage as cacheLocation, Chrome: 119.0.6045.124).
> 
> If I open the front-channel manually via url - the storage is cleared But when it opens via iframe - it doesn't
> 
> But I found that the problem is in "Storage Partitioning", when I disable it in chrome://flags/#third-party-storage-partitioning - everything works

I disabled the flag. But it doesn't work still. Does it work with session storage from your end?

**Comment by iv-al** [comment]
Just checked, for 'sessionStorage' disabling #third-party-storage-partitioning doesn't seem to work at all

**Comment by kevinvugts** [comment]
> Just checked, for 'sessionStorage' disabling #third-party-storage-partitioning doesn't seem to work at all

That's correct. I also can confirm this doesn't work for session storage. 
@tnorling could you elaborate more on this? 

Is this front-channel logout feature event meant for sessionStorage end of the day?

**Comment by Venu-prahalad** [comment]
@kevinvugts I am facing same issue. Did you happen to find any solution?

**Comment by kevinvugts** [comment]
> @kevinvugts I am facing same issue. Did you happen to find any solution?

Nope, Microsoft support takes ages to get back to my query. .. Still no resolution. 
They even have said they don't support such a feature. 

So in terms of internal knowledge, it's. a bit dissapointed...

**Comment by tnorling** [comment]
> Is this front-channel logout feature event meant for sessionStorage end of the day?

No, front channel logout is not compatible with sessionStorage for technical reasons. 

The way front channel logout works is that it will open hidden iframes to all of your logged in application's registered logout URLs and those pages, if implemented correctly, would clear storage. Since sessionStorage is not shared across windows, tabs or frames this would clear storage inside the iframe (which was empty from the start) and leave any other open tabs unaffected. On the other hand, unlike localStorage, closing the tab would effectively clear the storage.

If you want to take advantage of front channel logout I suggest using localStorage or finding a way to communicate between the hidden iframe that's opened and other open tabs/windows, that would be outside the scope of MSAL.js however.

**Comment by kevinvugts** [comment]
> > Is this front-channel logout feature event meant for sessionStorage end of the day?
> 
> No, front channel logout is not compatible with sessionStorage for technical reasons.
> 
> The way front channel logout works is that it will open hidden iframes to all of your logged in application's registered logout URLs and those pages, if implemented correctly, would clear storage. Since sessionStorage is not shared across windows, tabs or frames this would clear storage inside the iframe (which was empty from the start) and leave any other open tabs unaffected. On the other hand, unlike localStorage, closing the tab would effectively clear the storage.
> 
> If you want to take advantage of front channel logout I suggest using localStorage or finding a way to communicate between the hidden iframe that's opened and other open tabs/windows, that would be outside the scope of MSAL.js however.

That makes sense! I tested it on Safari and it works straight away. When I tested it on Chrome or Brave, it doesn't. Does this indicate a browser issue? 

If so, what is the whole purpose of front channel anyway? Since most of the users are running on Chrome and similar browsers?

It feels a bit redundant to keep such a feature in that case...

Though it looks like this functionality works on Safari browsers! Just tested it.

**Comment by zhangqiuyang** [comment]
Hi @kevinvugts , could you please try to disable third-party storage partitioning in edge://flags and see if it can clear cache?
