### ISSUE TITLE
Token renewal iframe resolves token for the iframe

### ISSUE THREAD

**Issue by austindyoung** [AzureAD/microsoft-authentication-library-for-js#66]
Token renewal iframe resolves the token renewed within the iframe. In this case, any request associated with the current SPA route that is waiting on the token will get executed in the iframe. It would be preferable for the iframe only to resolve the token promise for the parent.

**Comment by amilsil** [comment]
This has been one major problem I was facing so far trying to get it to work with Angular 2.

Firstly, to work with SPA frameworks, we need an additional silentRedirectUri which will be loaded in the iframe. It should not redirect that iframe to the RedirectUri after (which will result in loading the SPA inside the iframe all over again). 
+1 on this

**Comment by gramidt** [comment]
Any update on this? This is killing our apps performance.

**Comment by rohitnarula7176** [comment]
@austindyoung I have merged your pull request into dev by making some changes to it. Thank you for your contribution. @gramidt @amilsil  Can you please use the dev branch and see if you still face any issues.

**Comment by rohitnarula7176** [comment]
Closing this issue. Fixed in dev.
