### ISSUE TITLE
Updating a state in eventCallback breaks my app

### ISSUE THREAD

**Issue by essequie1** [AzureAD/microsoft-authentication-library-for-js#6604]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.3.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.0.5

### Public or Confidential Client?

Public

### Description

I'm trying to check when the first request for a token is made, so I can update a "hasToken" state and tell my app that it can start using the token as a carrier for requests to my backend, I can add an event callback for the EventType "ACQUIRE_TOKEN_SUCCESS", and I can log the message and everything, but just when I try to update the event with a function (coming from a previous React Context) the app crashes for some reason. It does a first render that looks fine, then flickers and everything disappears from the screen.

Event Callback:
```tsx
 useEffect(() => {
    const callbackId = instance.addEventCallback(message => {
      if (message.eventType === EventType.ACQUIRE_TOKEN_SUCCESS) {
        console.log(message);
        updateHasToken(); // This line breaks the app
      }
    });
    return () => {
      if (callbackId) {
        instance.removeEventCallback(callbackId);
      }
    };
  }, []);
  ```
  
  The function that breaks the app:
  ```tsx
  const [hasToken, setHasToken] = useState(false);

  const updateHasToken = () => {
    setHasToken(true);
  };
  ```
  This code is in a context a level above where i'm trying to add the event callback

### MSAL Configuration

```javascript
{
    auth: {
      clientId: msalClientId ?? '',
      authority: msalAuthority,
      redirectUri: window.location.origin,
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage,
    },
  };
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by tnorling** [comment]
Why do you need custom state for this purpose? Can you simply use one of the hooks provided by msal-react?
