### ISSUE TITLE
 TypeError: Right-hand side of 'instanceof' is not an object after adding the .initialize()

### ISSUE THREAD

**Issue by sameerjonathankhatib** [AzureAD/microsoft-authentication-library-for-js#6607]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

1.4.18

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.5

### Public or Confidential Client?

Confidential

### Description

We have an Angular app where in we're trying to upgrade to version 9 to version 16 then we're using the 
"@azure/msal-angular": "^3.0.5",
"@azure/msal-browser": "^3.2.0",

before we went for upgrade all the codes were running as expected.
now on the documentation  for upgrading from version 2 to version 3 it says that we need to initialize first so what i did is that i add this line before my loginRedirect()

await this.msalInstance.initialize();

what happens is that i can now log in but it will return an error saying

ERROR Error: Uncaught (in promise): TypeError: Right-hand side of 'instanceof' is not an object
TypeError: Right-hand side of 'instanceof' is not an object

can you help me with this one?

### MSAL Configuration

```javascript
auth: {
						authority:
							window['environmentVariableConfig'].accentureADConfig
								.msalAuthorityURL +
							this.config.tenantId +
							'/',
						clientId: this.config.clientId,
						redirectUri: this.config.redirectUri,
						navigateToLoginRequestUrl: false,
						postLogoutRedirectUri: this.config.redirectUri
					},
					cache: {
					  cacheLocation: BrowserCacheLocation.LocalStorage,
					  storeAuthStateInCookie: isIE, // set to true for IE 11
					},
					system: {
					  loggerOptions: {
						loggerCallback,
						logLevel: LogLevel.Info,
						piiLoggingEnabled: false
					  }
					}
```

### Relevant Code Snippets

```javascript
public async login(): Promise<void> {
		if (localStorage.getItem('msal.accesstoken')) {
			if (this.isTokenInvalid()) {
				this.clearlocalStorage();
				this.clearsessionStorage();
			}
		}
		await this.msalInstance.initialize();
		await this.getMsal().loginRedirect();
	}
```

### Identity Provider

None

### Source

External (Customer)

**Comment by tnorling** [comment]
What is the right hand side? Do you have a stack trace?
