### ISSUE TITLE
Login flow stuck after proxy authentication

### ISSUE THREAD

**Issue by cheenamalhotra** [AzureAD/microsoft-authentication-library-for-js#6609]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

2.2.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

N/A

### Public or Confidential Client?

Public

### Description

`baseClientExecutePostToTokenEndpoint` doesn't complete executing in this release of msal-common after proxy authentication completes. Previous version 11.0.0 used to work successfully.

No issue in regular non-proxy environments.

### Error Message

No error, application stuck.

### Msal Logs

[Information]: [Wed, 25 Oct 2023 19:24:26 GMT] : [] : @azure/msal-node@2.2.0 : Info - getAuthCodeUrl called - []
[Verbose]: [Wed, 25 Oct 2023 19:24:26 GMT] : [] : @azure/msal-node@2.2.0 : Verbose - initializeRequestScopes called - []
[Verbose]: [Wed, 25 Oct 2023 19:24:26 GMT] : [1e40473e-0df5-4253-96ee-595c055c9612] : @azure/msal-node@2.2.0 : Verbose - buildOauthClientConfiguration called - []
[Verbose]: [Wed, 25 Oct 2023 19:24:26 GMT] : [1e40473e-0df5-4253-96ee-595c055c9612] : @azure/msal-node@2.2.0 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/organizations - []
[Verbose]: [Wed, 25 Oct 2023 19:24:26 GMT] : [1e40473e-0df5-4253-96ee-595c055c9612] : @azure/msal-node@2.2.0 : Verbose - createAuthority called - []
[Verbose]: [Wed, 25 Oct 2023 19:24:26 GMT] : [] : @azure/msal-node@2.2.0 : Trace - Executing function authorityResolveEndpointsAsync - []
[Verbose]: [Wed, 25 Oct 2023 19:24:26 GMT] : [] : @azure/msal-node@2.2.0 : Trace - Retrieving all cache keys - []
[Verbose]: [Wed, 25 Oct 2023 19:24:26 GMT] : [] : @azure/msal-node@2.2.0 : Trace - Getting cache key-value store - []
[Verbose]: [Wed, 25 Oct 2023 19:24:26 GMT] : [] : @azure/msal-node@2.2.0 : Trace - Executing function authorityUpdateCloudDiscoveryMetadata - []
[Verbose]: [Wed, 25 Oct 2023 19:24:26 GMT] : [] : @azure/msal-node@2.2.0 : Verbose - Attempting to get cloud discovery metadata  from authority configuration - []
[Verbose]: [Wed, 25 Oct 2023 19:24:26 GMT] : [] : @azure/msal-node@2.2.0 : Verbose - Did not find cloud discovery metadata in the config... Attempting to get cloud discovery metadata from the hardcoded values. - []
[Verbose]: [Wed, 25 Oct 2023 19:24:26 GMT] : [] : @azure/msal-node@2.2.0 : Verbose - Found cloud discovery metadata from hardcoded values. - []
[Verbose]: [Wed, 25 Oct 2023 19:24:26 GMT] : [] : @azure/msal-node@2.2.0 : Trace - Returning result from authorityUpdateCloudDiscoveryMetadata - []
[Verbose]: [Wed, 25 Oct 2023 19:24:26 GMT] : [] : @azure/msal-node@2.2.0 : Trace - Executing function authorityUpdateEndpointMetadata - []
[Verbose]: [Wed, 25 Oct 2023 19:24:26 GMT] : [] : @azure/msal-node@2.2.0 : Verbose - Attempting to get endpoint metadata from authority configuration - []
[Verbose]: [Wed, 25 Oct 2023 19:24:26 GMT] : [] : @azure/msal-node@2.2.0 : Verbose - Did not find endpoint metadata in the config... Attempting to get endpoint metadata from the hardcoded values. - []
[Verbose]: [Wed, 25 Oct 2023 19:24:26 GMT] : [] : @azure/msal-node@2.2.0 : Verbose - Found endpoint metadata from hardcoded values. - []
[Verbose]: [Wed, 25 Oct 2023 19:24:26 GMT] : [] : @azure/msal-node@2.2.0 : Trace - Returning result from authorityUpdateEndpointMetadata - []
[Verbose]: [Wed, 25 Oct 2023 19:24:26 GMT] : [] : @azure/msal-node@2.2.0 : Trace - Getting cache key-value store - []
[Verbose]: [Wed, 25 Oct 2023 19:24:26 GMT] : [] : @azure/msal-node@2.2.0 : Trace - Setting cache key value store - []
[Verbose]: [Wed, 25 Oct 2023 19:24:26 GMT] : [] : @azure/msal-node@2.2.0 : Trace - Returning result from authorityResolveEndpointsAsync - []
[Verbose]: [Wed, 25 Oct 2023 19:24:26 GMT] : [1e40473e-0df5-4253-96ee-595c055c9612] : @azure/msal-node@2.2.0 : Verbose - Auth code client created - []
[Verbose]: [Wed, 25 Oct 2023 19:24:26 GMT] : [1e40473e-0df5-4253-96ee-595c055c9612] : @azure/msal-common@14.1.0 : Trace - Executing function authClientCreateQueryString - []
[Verbose]: [Wed, 25 Oct 2023 19:24:26 GMT] : [1e40473e-0df5-4253-96ee-595c055c9612] : @azure/msal-common@14.1.0 : Verbose - createAuthCodeUrlQueryString: Prompt is select_account, ignoring account hints - []
[Verbose]: [Wed, 25 Oct 2023 19:24:26 GMT] : [1e40473e-0df5-4253-96ee-595c055c9612] : @azure/msal-common@14.1.0 : Trace - Returning result from authClientCreateQueryString - []
[Information]: [Wed, 25 Oct 2023 19:25:04 GMT] : [] : @azure/msal-node@2.2.0 : Info - acquireTokenByCode called - []
[Verbose]: [Wed, 25 Oct 2023 19:25:04 GMT] : [] : @azure/msal-node@2.2.0 : Verbose - initializeRequestScopes called - []
[Verbose]: [Wed, 25 Oct 2023 19:25:04 GMT] : [c4afd28b-cd24-4586-a625-c8b4ac9661de] : @azure/msal-node@2.2.0 : Verbose - buildOauthClientConfiguration called - []
[Verbose]: [Wed, 25 Oct 2023 19:25:04 GMT] : [c4afd28b-cd24-4586-a625-c8b4ac9661de] : @azure/msal-node@2.2.0 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/organizations - []
[Verbose]: [Wed, 25 Oct 2023 19:25:04 GMT] : [c4afd28b-cd24-4586-a625-c8b4ac9661de] : @azure/msal-node@2.2.0 : Verbose - createAuthority called - []
[Verbose]: [Wed, 25 Oct 2023 19:25:04 GMT] : [] : @azure/msal-node@2.2.0 : Trace - Executing function authorityResolveEndpointsAsync - []
[Verbose]: [Wed, 25 Oct 2023 19:25:04 GMT] : [] : @azure/msal-node@2.2.0 : Trace - Retrieving all cache keys - []
[Verbose]: [Wed, 25 Oct 2023 19:25:04 GMT] : [] : @azure/msal-node@2.2.0 : Trace - Getting cache key-value store - []
[Verbose]: [Wed, 25 Oct 2023 19:25:04 GMT] : [] : @azure/msal-node@2.2.0 : Trace - Getting cache key-value store - []
[Verbose]: [Wed, 25 Oct 2023 19:25:04 GMT] : [] : @azure/msal-node@2.2.0 : Trace - Executing function authorityUpdateCloudDiscoveryMetadata - []
[Verbose]: [Wed, 25 Oct 2023 19:25:04 GMT] : [] : @azure/msal-node@2.2.0 : Verbose - Attempting to get cloud discovery metadata  from authority configuration - []
[Verbose]: [Wed, 25 Oct 2023 19:25:04 GMT] : [] : @azure/msal-node@2.2.0 : Verbose - Did not find cloud discovery metadata in the config... Attempting to get cloud discovery metadata from the hardcoded values. - []
[Verbose]: [Wed, 25 Oct 2023 19:25:04 GMT] : [] : @azure/msal-node@2.2.0 : Verbose - Found cloud discovery metadata from hardcoded values. - []
[Verbose]: [Wed, 25 Oct 2023 19:25:04 GMT] : [] : @azure/msal-node@2.2.0 : Trace - Returning result from authorityUpdateCloudDiscoveryMetadata - []
[Verbose]: [Wed, 25 Oct 2023 19:25:04 GMT] : [] : @azure/msal-node@2.2.0 : Trace - Executing function authorityUpdateEndpointMetadata - []
[Verbose]: [Wed, 25 Oct 2023 19:25:04 GMT] : [] : @azure/msal-node@2.2.0 : Verbose - Attempting to get endpoint metadata from authority configuration - []
[Verbose]: [Wed, 25 Oct 2023 19:25:04 GMT] : [] : @azure/msal-node@2.2.0 : Verbose - Did not find endpoint metadata in the config... Attempting to get endpoint metadata from the hardcoded values. - []
[Verbose]: [Wed, 25 Oct 2023 19:25:04 GMT] : [] : @azure/msal-node@2.2.0 : Verbose - Found endpoint metadata from hardcoded values. - []
[Verbose]: [Wed, 25 Oct 2023 19:25:04 GMT] : [] : @azure/msal-node@2.2.0 : Trace - Returning result from authorityUpdateEndpointMetadata - []
[Verbose]: [Wed, 25 Oct 2023 19:25:04 GMT] : [] : @azure/msal-node@2.2.0 : Trace - Getting cache key-value store - []
[Verbose]: [Wed, 25 Oct 2023 19:25:04 GMT] : [] : @azure/msal-node@2.2.0 : Trace - Setting cache key value store - []
[Verbose]: [Wed, 25 Oct 2023 19:25:04 GMT] : [] : @azure/msal-node@2.2.0 : Trace - Returning result from authorityResolveEndpointsAsync - []
[Verbose]: [Wed, 25 Oct 2023 19:25:04 GMT] : [c4afd28b-cd24-4586-a625-c8b4ac9661de] : @azure/msal-node@2.2.0 : Verbose - Auth code client created - []
[Verbose]: [Wed, 25 Oct 2023 19:25:04 GMT] : [c4afd28b-cd24-4586-a625-c8b4ac9661de] : @azure/msal-common@14.1.0 : Trace - Executing function authClientExecuteTokenRequest - []
[Verbose]: [Wed, 25 Oct 2023 19:25:04 GMT] : [c4afd28b-cd24-4586-a625-c8b4ac9661de] : @azure/msal-common@14.1.0 : Trace - Executing function authClientCreateTokenRequestBody - []
[Verbose]: [Wed, 25 Oct 2023 19:25:04 GMT] : [] : @azure/msal-node@2.2.0 : Trace - Getting cache key-value store - []
[Verbose]: [Wed, 25 Oct 2023 19:25:04 GMT] : [c4afd28b-cd24-4586-a625-c8b4ac9661de] : @azure/msal-common@14.1.0 : Trace - Returning result from authClientCreateTokenRequestBody - []
[Verbose]: [Wed, 25 Oct 2023 19:25:04 GMT] : [c4afd28b-cd24-4586-a625-c8b4ac9661de] : @azure/msal-common@14.1.0 : Trace - Executing function baseClientExecutePostToTokenEndpoint - []
[Verbose]: [Wed, 25 Oct 2023 19:25:04 GMT] : [] : @azure/msal-node@2.2.0 : Trace - Getting cache key-value store - []

### MSAL Configuration

```javascript
{
    auth: {
	clientId: '#####',
	authority: 'https://login.windows.net/common'
    },
    system: {
	loggerOptions: {
	    loggerCallback: this.getLoggerCallback(),
	    logLevel: MsalLogLevel.Trace,
	    piiLoggingEnabled: true,
	},
    },
    cache: {
	cachePlugin: this._cachePluginProvider?.getCachePlugin()
    }
}
```

### Relevant Code Snippets

```javascript
let authUrlRequest: AuthorizationUrlRequest;
authUrlRequest = {
	scopes: this.scopes,
	redirectUri: `${this.redirectUri}:${serverPort}/redirect`,
	codeChallenge: this.pkceCodes.codeChallenge,
	codeChallengeMethod: this.pkceCodes.challengeMethod,
	prompt: Constants.SELECT_ACCOUNT,
	authority: `${this.loginEndpointUrl}${tenant.id}`,
	state: state
};

let authCodeRequest: AuthorizationCodeRequest;
authCodeRequest = {
	scopes: this.scopes,
	redirectUri: `${this.redirectUri}:${serverPort}/redirect`,
	codeVerifier: this.pkceCodes.codeVerifier,
	authority: `${this.loginEndpointUrl}${tenant.id}`,
	code: ''
};

let authCodeUrl = await this.clientApplication.getAuthCodeUrl(authUrlRequest);
await vscode.env.openExternal(vscode.Uri.parse(`http://localhost:${serverPort}/signin?nonce=${encodeURIComponent(this.pkceCodes.nonce)}`));
const authCode = await this.addServerListeners(server, this.pkceCodes.nonce, authCodeUrl, authCompletePromise);

authCodeRequest.code = authCode;
let result = await this.clientApplication.acquireTokenByCode(authCodeRequest);
```

### Reproduction Steps

Reproduced issue in ADS Insiders in proxy-enabled environment, I can provide build info if needed.
Feel free to ping me on Teams directly.

### Expected Behavior

Should be able to complete login.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Regression

@azure/msal-node 1.16.0 (last known)

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
Is this still an issue in 2.6.0?

**Comment by wintorez** [comment]
I have a somewhat issue while attempting to call accureTokenByCode behind a proxy. The proxy agent tries to make a POST to https://login.microsoftonline.com/xxxx-xxxx-xxxx-xxxxx/oauth2/v2.0/token and throws a network_error.

Only happens when behind a proxy.
