### ISSUE TITLE
In dynamices 365 filed service app, ssoSilent get error 'InteractionRequiredAuthError: login_required: AADSTS50058'

### ISSUE THREAD

**Issue by amysun123** [AzureAD/microsoft-authentication-library-for-js#6610]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.38.2

### Wrapper Library

Not Applicable

### Wrapper Library Version

NA

### Public or Confidential Client?

Public

### Description

In the dynamics 365 Field service apps, we try to call method 'msalInstance.ssoSilent' , 'msalInstance.acquireTokenSilent', 'msalInstance.loginPopup' to get AAD token,  the same code works in the pc browser(dynamics 365 field service mobile)

### Error Message

InteractionRequiredAuthError: login_required: AADSTS50058: A silent sign-in request was sent but no user is signed in. The cookies used to represent the user's session were not sent in the request to Azure AD. This can happen if the user is using Internet Explorer or Edge, and the web app sending the silent sign-in request is in different IE security zone than the Azure AD endpoint (login.microsoftonline.com).
Trace ID: 135cbee1-c136-4fe2-995c-f3d702c84c00
Correlation ID: 5b76a438-ba47-4edd-be02-89e0f89a9484
Timestamp: 2023-10-26 07:10:23Z

----
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/149053198/440c34e7-8b71-481a-9170-518c6019d9cf)

### MSAL Configuration

```javascript
const msalConfig = {
			auth: {
				clientId: clientId,
				authority: 'https://login.microsoftonline.com/' + tenantId,
				// redirectUri: environment + 'blank.html',
				redirectUri: environment + 'main.aspx',
			},
			cache: {
				cacheLocation: 'localStorage',
				storeAuthStateInCookie: true
			},
			system: {
				loggerOptions: {
					logLevel: msal.LogLevel.Verbose,
					loggerCallback: (level, message, containsPii) => {
						if (containsPii) {
							return;
						}
						switch (level) {
							case msal.LogLevel.Error:
								console.error(message);
								return;
							case msal.LogLevel.Info:
								console.info(message);
								return;
							case msal.LogLevel.Verbose:
								console.debug(message);
								return;
							case msal.LogLevel.Warning:
								console.warn(message);
								return;
						}
					},
					piiLoggingEnabled: true
				}
			}
		};
```

### Relevant Code Snippets

```javascript
msalInstance.ssoSilent(request).then((res) => {
				accountObj = res.account;
				request.account = accountObj;
				request.redirectUri = "http://localhost:3000/blank.html";
				
				return msalInstance.acquireTokenSilent(request)
					.then(function (response) {
						const token = response.accessToken;
						console.log(token);
						return token;
						// Xrm.Navigation.openAlertDialog(token);
					})
					.catch(function (error) {
						console.log('acquireTokenSilent error');
						console.log(error);
						
						return msalInstance.acquireTokenRedirect(request).catch(e => {
							console.log('acquireTokenRedirect error');
							console.log(e);
				
							return null
							// Xrm.Navigation.openAlertDialog(e);
						});
					});
			}).catch((err) => {
				console.log('auth error' + err);
				console.error("Silent Error: " + err);
				

				return msalInstance.loginPopup(request).catch(e => {
					console.log('loginPopup error');
					console.log(e);
		
					return null
					// Xrm.Navigation.openAlertDialog(e);
				});
				// Xrm.Navigation.openAlertDialog('auth error' + err);
			}).finally(() => {
				// Xrm.Utility.closeProgressIndicator("getting token");
			});
```

### Reproduction Steps

1. down load 'Dynamics 365 Field Service'
2. get the aad token

### Expected Behavior

get the aad token in the mobile (field service app)
https://www.bing.com/ck/a?!&&p=d40039a14e99fefaJmltdHM9MTY5ODI3ODQwMCZpZ3VpZD0wMTk3ODQ3My0yZDQzLTZlNmEtMzA5Ni05NzBjMmM2ZDZmYTEmaW5zaWQ9NTI2OA&ptn=3&hsh=3&fclid=01978473-2d43-6e6a-3096-970c2c6d6fa1&psq=field+service+app&u=a1aHR0cHM6Ly9wbGF5Lmdvb2dsZS5jb20vc3RvcmUvYXBwcy9kZXRhaWxzP2lkPWNvbS5taWNyb3NvZnQuY3JtLmNybXBob25lLmZpZWxkU2VydmljZXM&ntb=1

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/149053198/2b3c7e6c-bb3f-42cf-b079-b669060e5074)

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Safari, Other

### Regression

@azure/msal-browser v2.38.2 2023-08-24

### Source

External (Customer)

**Comment by amysun123** [comment]
Hi team, any update?

**Comment by tnorling** [comment]
ssoSilent will fail when 3P cookies are blocked (default in Safari). When you get InteractionRequired errors you should catch these and invoke interaction, either popup or redirect, to continue.
