### ISSUE TITLE
msalInstance.getAccountByHomeId is deprecated.ts

### ISSUE THREAD

**Issue by ashkumarverma** [AzureAD/microsoft-authentication-library-for-js#6611]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.3.0

### Wrapper Library

MSAL Node Extensions (@azure/msal-node-extensions)

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

Getting The signature '(homeAccountId: string): AccountInfo | null' of 'msalInstance.getAccountByHomeId' is deprecated.ts(6387), in "@azure/msal-browser": "^3.3.0". There is no issue with "@azure/msal-browser": "^3.1.0".

### Error Message

The signature '(homeAccountId: string): AccountInfo | null' of 'msalInstance.getAccountByHomeId' is deprecated.ts(6387)
PublicClientApplication.d.ts(131, 8): The declaration was marked as deprecated here.
(method) PublicClientApplication.getAccountByHomeId(homeAccountId: string): AccountInfo | null
Returns the signed in account matching homeAccountId. (the account object is created at the time of successful login) or null when no matching account is found

@param homeAccountId

@returns — The account object stored in MSAL

@deprecated — - Use getAccount instead

### MSAL Configuration

```javascript
CLIENTID=****
AUTHORITY=https://login.microsoftonline.com/****
```

### Relevant Code Snippets

```javascript
// Sign out user
  function signOut(accountId: string) {
    const account = accountId
      ? msalInstance.getAccountByHomeId(accountId)
      : null;
    if (account) {
      msalInstance.logoutRedirect({
        account,
      });
      localStorage.clear();
    } else {
      console.error("Account not found");
    }
```

### Reproduction Steps

While adding plugins in Nuxt 3

### Expected Behavior

It should get logout.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Edge

### Regression

@azure/msal-browser 3.3.0

### Source

Internal (Microsoft)

**Comment by hectormmg** [comment]
@ashkumarverma the `getAccountByHomeId()` API was marked for deprecation as of v3.3.0, but it is still available so it should work unless your project configuration doesn't allow using deprecated functions. MSAL doesn't actually throw an error for this.

You have two options to fix this:
1. (Recommended): Migrate to the new `getAccount()` API:
```javascript

// Sign out user
  function signOut(accountId: string) {
    const account = accountId
      // New getAccount API allows you to pass in a filter
      ? msalInstance.getAccount({ homeAccountId: accountId })
      : null;
    if (account) {
      msalInstance.logoutRedirect({
        account,
      });
      localStorage.clear();
    } else {
      console.error("Account not found");
    }
```

2. Configure your application to ignore the deprecation warning.
