### ISSUE TITLE
Cannot find module './index-9800158f.js' from '../../node_modules/@azure/msal-browser/lib/msal-browser.cjs'

### ISSUE THREAD

**Issue by zac1wz** [AzureAD/microsoft-authentication-library-for-js#6626]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.3.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.0.5

### Public or Confidential Client?

Public

### Description

I try to run Jest tests after upgrading dependency version and simply after modifying jest.config.ts I expected them to work.

Jest version: 29.7.0

### Error Message

  ● Test suite failed to run

    Cannot find module './index-9800158f.js' from '../../node_modules/@azure/msal-browser/lib/msal-browser.cjs'

    > 4 | import { useMsal } from '@azure/msal-react'
        | ^

### MSAL Configuration

```javascript
{
	auth: {
		knownAuthorities: [
			'https://login.microsoftonline.com/mytenantid',
		],
		authority:
			'https://login.microsoftonline.com/mytenantid',
		clientId: `clientid`,
		redirectUri: window.location.origin,
	},
}
```

### Relevant Code Snippets

```javascript
jest.config.ts


const esModules = [
	'nanoid',
	'headers-polyfill',
	'react-dnd',
	'dnd-core',
	'@react-dnd',
	'react-dnd-html5-backend',
	'msal-react-tester',
	'@azure/msal-browser',
	'@azure/msal-react',
].join('|')

export default {
	displayName: 'main',
	preset: '../../jest.preset.js',
	transform: {
		'^.+\\.(ts|tsx|js|jsx)$': [
			'ts-jest',
			{
				isolatedModules: true,
			},
		],
		'^.+\\.svg$': 'jest-transformer-svg',
	},
	moduleNameMapper: {
		'^.+\\.svg$': 'jest-transformer-svg',
	},
	moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx'],
	coverageReporters: ['lcov', 'json'],
	coverageDirectory: '../../coverage/apps/main',
	transformIgnorePatterns: [`node_modules/(?!${esModules}/)`],
	setupFilesAfterEnv: ['../../jest-polyfills.js'],
	coverageProvider: 'babel',
	collectCoverage: true,
	reporters: ['default'],
	globals: {},
}
```

### Reproduction Steps

NA

### Expected Behavior

Jest tests run

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Other

### Regression

"@azure/msal-browser": "^2.37.0"

### Source

External (Customer)

**Comment by martinfalisse** [comment]
Related https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/6596

**Comment by zac1wz** [comment]
Thank you @martinfalisse! I could not find an issue while querying by `Cannot find module './index-9800158f.js'`, so we could even close this one but keep reference, so others can find it.

**Comment by hectormmg** [comment]
@CezaryBD thanks for raising the issue, we already have a fix in the works. For now, downgrading to 3.2.0 is the official workaround until we release a patch. Thanks!
