### ISSUE TITLE
BrowserAuthError: monitor_window_timeout  in Outlook Addin on iOS

### ISSUE THREAD

**Issue by Aidam1** [AzureAD/microsoft-authentication-library-for-js#6628]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.3.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.0.5

### Public or Confidential Client?

Public

### Description

I am using MSAL in Outlook Office addin on iOS. But the same happens on Android.

I successfully login to the MSAL manually and am able to use it with it remembering the token correctly. However, next day (but definitely less than 24 hours), I try to auth again, but the msal returns `acquireTokenFailure`, so I have to login manually again.

I have looked through the documentation for this method but none of the solutions seem to apply to me. It seems weird to me that It works for a few hours, but the next day it throws this error. 

Logs when the silent token acquire is successful:
acquireTokenStart (silent request)
acquireCachedToken - expired
acquireTokenFromNetworkStart
acquireTokenSuccess

Logs when its not successful:
acquireTokenStart (silent request)
acquireCachedToken - expired
acquireTokenFromNetworkStart
acquireTokenFailure - Token acquisition in iframe failed due to timeout. For more visit: aka.ms/msaljs/browser-errors. name: BrowserAuthError

### Error Message

 "eventType": "msal:acquireTokenFailure",
 "interactionType: {
    "errorCode": "monitor_window_timeout"
    "errorMessage": "Token acquisition in iframe failed due to timeout. For more visit: aka.ms/msaljs/browser-errors."
    "subError": "",
    "name": "BrowserAuthError"

### Msal Logs

Its almost impossible to get these logs from Outlook Addin on iOS, so I have provided abbreviated version of them above.

### MSAL Configuration

```javascript
{
    auth: {
        clientId: process.env.REACT_APP_MSAL_CLIENT_ID!,
        authority: 'https://login.microsoftonline.com/common',
        redirectUri: window.location.href.split("?")[0],
    },
    cache: {
        cacheLocation: 'localStorage', // This configures where your cache will be stored
        storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
    }
}
```

### Relevant Code Snippets

```javascript
const loginRequestGraph = {
    scopes: [
        'https://graph.microsoft.com/User.Read',
    ],
    prompt: 'login'
};

const getLoginRequest = async (request: SilentRequest) => {
    const currentUserUserName = await MsalHelper.getCurrentUserUserName();

    return {
        ...loginRequestGraph,
        loginHint: currentUserUserName ?? Office.context.mailbox.userProfile.emailAddress,
    };
};

const getMsalAccessToken = async (msalInstance: IPublicClientApplication, silentRequest: SilentRequest) => {
const msalActiveAccount = msalInstance.getActiveAccount();
        if (msalActiveAccount) {
            const currentUserUserName = await MsalHelper.getCurrentUserUserName();
            if (currentUserUserName && currentUserUserName !== msalActiveAccount.username) {
                // Skip silent requests and login using dialog
                console.log(`Current user username ${currentUserUserName} doesn't match msal active account username ${msalActiveAccount.username}`);
            } else {
                console.log(`Trying silent request ${JSON.stringify(silentRequest)}...`);
                try {
                    const result = await msalInstance.acquireTokenSilent({ ...silentRequest, prompt: 'none', account: msalActiveAccount });
                    if (!!result && !!result.accessToken) {
                        return result.accessToken;
                    }

                    console.log(`No result when acquiring token silently with prompt 'none', scopes: ${JSON.stringify(silentRequest.scopes)}, res: ${JSON.stringify(result)}`);
                } catch (e) {
                    console.log("Couldn't acquire token silently with prompt 'none'", e);

                    try {
                        const result = await msalInstance.acquireTokenSilent({ ...silentRequest, account: msalActiveAccount });
                        if (!!result && !!result.accessToken) {
                            return result.accessToken;
                        }

                        console.log(`No result when acquiring token silently with prompt '${silentRequest.prompt}', scopes: ${JSON.stringify(silentRequest.scopes)}, res: ${JSON.stringify(result)}`, e);
                    } catch (e) {
                        console.log(`Couldn't acquire token silently with prompt '${silentRequest.prompt}'`, e);
                    }
                }
            }
        }

        return await MsalHelper.displayMsalSignInDialog(msalInstance);
}
```

### Reproduction Steps

1. Login to MSAL in Outlook Office Addin.
2. Wait for ~17 hours
3. Try to renew token silently

### Expected Behavior

The silent request works for at least 24 hours

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Safari

### Source

External (Customer)

**Comment by tnorling** [comment]
I would need network logs to confirm but it's likely that your RT is being rejected due to expiration, revocation or CA policies and the subsequent refresh attempt is failing due to 3P cookies being blocked.
