### ISSUE TITLE
How long is the authorization code for AzureAD single sign-on?

### ISSUE THREAD

**Issue by classmatewu** [AzureAD/microsoft-authentication-library-for-js#6629]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

2.2.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

none

### Public or Confidential Client?

Public

### Description

AzureAD is very powerful and convenient, a very cool protocol.
But, How long is the authorization code for AzureAD single sign-on? It doesn’t seem to be specified in the AAD document, and there doesn’t seem to be a clear limit in the RFC standard of OAuth2.0?
I have tried it several times and the result is more than 900 character strings, which seriously exceeds the length defined by my database field, so I want to confirm the maximum length so that I can adjust the database field length.
Please provide me some help if possible, thanks a lot.

### Identity Provider

None

### Source

External (Customer)

**Comment by hectormmg** [comment]
@classmatewu authorization codes are single-use and expire very quickly, so you most likely should not be persisting them to any database. Is there a reason why you store it?

**Comment by classmatewu** [comment]
@hectormmg Hi, thanks for your reply.
> authorization codes are single-use and expire very quickly.

I know this. I recorded it for similar tracking purposes. I asked this question out of curiosity.Is there an accurate answer to its length?
thanks a lot.

**Comment by tnorling** [comment]
Code is an opaque string and we make no assertions about any of its properties, including length. This is a security artifact, you absolutely **should not** store it in a database
