### ISSUE TITLE
AADSTS28004: The provided value for the input parameter 'scope' exceeded the number of scopes allowed

### ISSUE THREAD

**Issue by abishekreddy** [AzureAD/microsoft-authentication-library-for-js#663]
We get an `AADSTS28004: The provided value for the input parameter 'scope' exceeded the number of scopes allowed.` error when we add more than 5 values to the consentScopes list.

![image](https://user-images.githubusercontent.com/24618556/56789812-79031c80-6820-11e9-9984-b012930f9a24.png)

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version XX
- [x] Firefox version XX
- [x] IE version XX
- [x] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: @azure/msal-angular 0.1.2

</code></pre>

**Comment by aashiman** [comment]
Hi, in the interest of a best user experience with consent, we recommend that the scopes are asked for when needed using MSAL and the OIDC certified v2 protocol. 

Are you really  needing to consent across 5 APIs in the 1st user screen? have you collected end-user feedback? Our experience has been that you are likely to see user drop off on this screen

https://docs.microsoft.com/en-us/azure/active-directory/develop/application-consent-experience

**Comment by aashiman** [comment]
@abishekreddy I am closing this request as you should be able to do incremental/dynamic consent with MSAL/AAD v2 protocol. Please feel free to re-open if that does not work for you
