### ISSUE TITLE
Usage of http instead of https in authority uri

### ISSUE THREAD

**Issue by pschaub** [AzureAD/microsoft-authentication-library-for-js#6631]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.3.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.0.5

### Public or Confidential Client?

Public

### Description

I would like to use an `authority` URI that contains `http` instead of `https` for local development usage with Keycloak as Identity Provider.

### Error Message

ClientConfigurationError: authority_uri_insecure: Authority URIs must use https.  Please see here for valid authority configuration options: https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-initializing-client-applications#configuration-options

### MSAL Configuration

```javascript
{
  auth: {
    protocolMode: ProtocolMode.OIDC,
    authorityMetadata: JSON.stringify({
      authorization_endpoint: 'http://localhost:8180/realms/example-realm/protocol/openid-connect/auth',
      token_endpoint: 'http://localhost:8180/realms/example-realm/protocol/openid-connect/token',
      issuer: 'http://localhost:8180/realms/example-realm',
      userinfo_endpoint: 'http://localhost:8180/realms/example-realm/protocol/openid-connect/userinfo'
    }),
    authority: 'http://localhost:8180/realms/example-realm',
    clientId: 'my-webapp',
    clientSecret: 'your-client-secret-here',
    knownAuthorities: ['http://localhost:8180/realms/example-realm']
  }
}
```

### Relevant Code Snippets

```javascript
N/A
```

### Reproduction Steps

Use MSAL configuration with `authority` that contains `http` instead of `https`

### Expected Behavior

There should be a way to use `http` instead of `https` for local development usage

### Identity Provider

Other

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by hectormmg** [comment]
@pschaub we can't allow protocol downgrading since it could lead to unsafe usage. Have you considered using a tool like [ngrok](https://ngrok.com/) to create a tunnel to tunnel your identity server over HTTPS?

**Comment by pschaub** [comment]
@hectormmg This issue is blocking our local development setup, and so it's the only reason that resulted into moving away to [another library](https://github.com/authts/oidc-client-ts) to integrate OAuth2/OIDC. I just need a way to use any `localhost` identity server that is running on `http` instead of `https` because it's not easy to set up a tls certificate for `localhost` development usage.

It's `localhost` and for development usage only, so I don't see any risk in my case.

There should be a flag to disable the tls check.

**Specific example: local web app development with Quarkus**
In our specific case we use [Quarkus Dev Services](https://quarkus.io/guides/dev-services) to automatically start a keycloak server, that doesn't support any `https` configuration for local development. The Quarkus community expects that you don't use TLS for local development. We don't want to use any additional tools like `ngrok` because this would harm the development experience. Currently the keycloak instance is started automatically through 'Quarkus Dev Services' without any additional task.

**Please keep in mind that any other library does not result into this issue, this issue only occurs with the Microsoft library.**

**Comment by tnorling** [comment]
We don't offer support for non Microsoft authorities. If this is a use case you need to support I encourage you to find another library that can fulfill your needs. Closing this as wont-fix.

**Comment by pschaub** [comment]
We use `keycloak` for local development and `Microsoft Entra ID` for production. That because I tried to use keycloak locally. I'll switch to another library [react-oidc-context](https://github.com/authts/react-oidc-context) / [oidc-client-ts](https://github.com/authts/oidc-client-ts) to solve this.

**Comment by domdorn** [comment]
> We don't offer support for non Microsoft authorities. If this is a use case you need to support I encourage you to find another library that can fulfill your needs. Closing this as wont-fix.

As we're in the same boat (Entra for prod, keycloak for test/dev), I'm wondering what Microsoft is suggesting that developers do to fulfill this https requirement on their local machine.. tunneling potentially sensitive content over a 3rd party service like ngrok is a no-go. Is there a local Entra ID that can be started using docker and already comes with a SSL-Cert? I'm happy to migrate our dev setup to that instead of Keycloak.

**Comment by kamikaze** [comment]
then this library is not OIDC compliant. thanks, bye
