### ISSUE TITLE
Angular 16 app can't upgrade to MSAL 3+

### ISSUE THREAD

**Issue by usarskyy** [AzureAD/microsoft-authentication-library-for-js#6632]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3

### Public or Confidential Client?

Public

### Description

I am upgrading to Angular v16 and updated all `msal/*` dependencies as well:

```
"@azure/msal-angular": "^3.0.6",
"@azure/msal-browser": "^3.3.0",
```
Unfortunately I keep getting an error during `npm i` execution. I tried around five-six times and every time I am getting an error:

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/1206777/43a2d2ee-cd9f-4f92-8567-9aaf91009f85)

As you can see, `npm` can't resolve one of the dependencies. All other packages worked fine (I've just updated dozens of them).

At first I thought this is my local problem but npmjs.com also has problems displaying details about `msal-common` package.

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/1206777/25769ed4-025c-4685-b421-e5dff9f3909f)

Can anyone check if this package wasn't corrupted or deleted by mistake?

### MSAL Configuration

```javascript
{
  auth: {
    clientId: '...',
    authority: 'https://login.microsoftonline.com/blahblah.onmicrosoft.com/',
    redirectUri: '/',
  },
  cache: {
    claimsBasedCachingEnabled: true,
    cacheLocation: BrowserCacheLocation.LocalStorage,
    storeAuthStateInCookie: isIE,
  },
  system: {
    loggerOptions: {
      loggerCallback,
      logLevel: LogLevel.Verbose,
      piiLoggingEnabled: false,
    },
  },
}
```

### Relevant Code Snippets

```javascript
None
```

### Reproduction Steps

Try to install the following packages:

```
"@azure/msal-angular": "^3.0.6",
"@azure/msal-browser": "^3.3.0",
```

### Expected Behavior

Packages should be installed without an error

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
NPM is currently experiencing an incident related to package installs (we've seen this with some of our dependencies today as well). Please track status [here](https://status.npmjs.org/) for resolution.
