### ISSUE TITLE
`AADSTS700084` when user token is expired and another user logs in

### ISSUE THREAD

**Issue by DynaSpan** [AzureAD/microsoft-authentication-library-for-js#6643]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.4.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.7

### Public or Confidential Client?

Public

### Description

When a user hasn't used the website for a while, the token is expired and the users gets redirected to the `login.microsoftonline.com` login page with a `login_hint` provided by the `MsalGuard` or `MsalInterceptor`

I have only verified this with an account that is **not** equal to the `login_hint,` but when the user authenticates, the POST request to `https://login.microsoftonline.com/{tenantId}/oauth2/v2.0/token` returns a 400 Bad Request with the following error code: `AADSTS700084`. Then, the user gets redirected back to `login.microsoftonline.com`

In incognito, the user can login without any problems. So it seems MSAL uses a wrong token when requesting a new token, might have something to do with `login_hint` and user not being the same or some other cache errors.

Please note: I only have this issue on one Android tablet with Chrome, and I have to debug the tablet remotely via Teams which isn't available all the time, so some more logs will be added soon.

### Error Message

```json
{ "error": "invalid_grant", "error_description": "AADSTS700084: The refresh token was issued to a single page app (SPA), and therefore has a fixed, limited lifetime of 1.00:00:00, which cannot be extended. It is now expired and a new sign in request must be sent by the SPA to the sign in page. The token was issued on 2023-10-01T13:33:28.423123+00:00." }
```

### MSAL Configuration

```javascript
// app.component.ts
export const protectedResourceMap: Map<string, (string | ProtectedResourceScopes)[]> = new Map([
  [environment.apiUrl,                    [ 'api://' + environment.azureAdClientId + '/user_impersonation' ]],
  [environment.authApiUrl,                [ 'api://' + environment.azureAdClientId + '/user_impersonation' ]],
  [environment.projectApiUrl,             [ 'api://' + environment.azureAdClientId + '/user_impersonation']],
  [environment.docsApiUrl,                [ 'api://' + environment.azureAdClientId + '/user_impersonation' ]],
  ['https://graph.microsoft.com/v1.0/me', ['user.read']]
]);

@NgModule({
  declarations: [
    AppComponent
    // [...]
  ],
  imports: [
    // [...]
    MsalModule.forRoot(new PublicClientApplication({
      auth: {
          clientId: environment.azureAdClientId,
          authority: 'https://login.microsoftonline.com/' + environment.azureAdAuthority,
          redirectUri: environment.azureAdRedirectUri,
          navigateToLoginRequestUrl: false
      },
      cache: {
          cacheLocation: BrowserCacheLocation.LocalStorage
      },
      system: {
          loggerOptions: {
              loggerCallback: () => {},
              piiLoggingEnabled: false
          }
      },
    }),
    {
        interactionType: InteractionType.Redirect, // MSAL Guard Configuration
        authRequest: {
          scopes: ['user.read']
        },
        // loginFailedRoute: "/sso/redirect" 
    }, {
        interactionType: InteractionType.Redirect, // MSAL Interceptor Configuration
        protectedResourceMap
    }),
    ServiceWorkerModule.register('ngsw-worker.js', { enabled: environment.production })
  ],
  providers: [
      // [...]
      {
        provide: HTTP_INTERCEPTORS,
        useClass: MsalInterceptor,
        multi: true
      },
      MsalGuard
  ],
  bootstrap: [AppComponent]
})

// app-routing.component.ts
const routes: Routes = [
    { path: '', component: WrapperComponent, canActivate: [MsalGuard], children: [
      { path: '', redirectTo: '/dashboard', pathMatch: 'full' },
      { path: 'dashboard', component: DashboardComponent }
      // [...]
    ] },

    { path: 'sso/redirect', component: AzureLoginRedirectComponent },
    { path: 'sso/logout', component: AzureLogoutComponent },

    { path: '**', component: NotFoundComponent }
];

// login-redirect.component.ts
ngOnInit(): void {
    // [...]
    this.msalService.handleRedirectObservable()
        .subscribe(_ => {
            setTimeout(() => {
                const me$        = this.httpClient.get(settings.authApiUrl + 'user/me');
                const authCheck$ = this.httpClient.get(settings.apiUrl + 'auth/check');

                // Haven't been able to fully test this, but we dont get here
               // user gets redirected immediately back to login.microsoftonline.com
                forkJoin([me$, authCheck$])
                    .subscribe(_ => {
                        localStorage.removeItem('login-redirect-uri');
                        this.router.navigate([redirectUri]).catch(e => this.router.navigate["/"]);
                    }, (err: HttpErrorResponse)  => {
                        switch (err.status) {
                            case 401:
                                this.state = 'login-failed'; break;
                            case 403:
                                this.state = 'no-app-permissions'; break;
                            case 407:
                                this.state = 'credential-downstream-issue'; break;
                            default:
                                this.state = 'unknown-error'; break;
                        }

                        localStorage.removeItem('login-redirect-uri');
                    });
            }, 100);
        }, err => {
            console.error(err);
            this.state = 'login-failed';
        });
}
```

### Relevant Code Snippets

```javascript
I don't have a working reproduction case yet...
```

### Reproduction Steps

1. Let tokens expire
2. When redirect to login.microsoftonline.com, login with a different account than login_hint
3. When redirecting back to the application, the request to `https://login.microsoftonline.com/{tenantId}/oauth2/v2.0/token` will fail with a 400: Bad Request and the error provided above
4. The user gets redirected back to `login.microsoftonline.com` by MSAL

### Expected Behavior

POST request to `https://login.microsoftonline.com/{tenantId}/oauth2/v2.0/token` should make the request with the new token for the user, not re-use an expired token, and return a 200 status with a token.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by tnorling** [comment]
This is happening because you don't specify an account on your requests and MSAL defaults to the first account found in the cache if not provided. Try setting the active account to the account returned in the handleRedirectObservable response.

**Comment by brahmaiahthota** [comment]
@DynaSpan Did you resolve this issue ? could you please let me know I am also facing the same issue..

**Comment by DynaSpan** [comment]
I haven't yet. For now I just cleared the cache on the affected tablets when the problem arose.

I might work on a patch/fix in the future.

**Comment by brahmaiahthota** [comment]
Thanks for the update @DynaSpan
