### ISSUE TITLE
instance.loginPopup() - after finishing account login popup window opens login page inside

### ISSUE THREAD

**Issue by developerMahian** [AzureAD/microsoft-authentication-library-for-js#6649]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

1.4.18

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.5.9

### Public or Confidential Client?

Public

### Description

I've got a two-step login process where I'm using msal SSO for authentication and using the retrieved token with another API endpoint (react-qeury mutation) for authorization.
Sometimes, during logging in instead of redirecting to the dashboard, the popup stays open and shows the login page right inside.
Another thing to note is that none of the code after instance.loginPopup() gets executed in this scenario. Seems like in these scenarios msal is stopping my custom logic for calling the separate authorization endpoint?

### MSAL Configuration

```javascript
export const msalConfig = {
	auth: {
		clientId: process.env.REACT_APP_MSAL_CLIENT_ID,
		authority: process.env.REACT_APP_MSAL_AUTHORITY,
		redirectUri: process.env.REACT_APP_MSAL_REDIRECT_URL,
	},
	cache: {
		cacheLocation: "sessionStorage", // "sessionStorage" is more secure, but "localStorage" gives you SSO between tabs.
		storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
	},
};

export const loginRequestScopes = [process.env.REACT_APP_MSAL_SCOPE];
```

### Relevant Code Snippets

```javascript
const history = useHistory();
const { instance } = useMsal();
const loginPopupRef = useRef(null);

const { mutate, isLoading } = useMutation(loginWithSsoToken, {
	onSuccess: (res) => {
		console.log("mutate onSuccess: ", res);
		if (!res?.authoriseFlag) throw Error("Error logging in..");

		if (!res?.staffId) {
			showNotice.error({
				title: "No Valid StaffId",
				message: "No StaffId was found from your login. Please Try again.",
			});
			return; // exit..
		}

		localStorage.setItem("staffID", res?.staffId);
		localStorage.setItem("userRoleNumber", res?.roleNo);

		history.push("/dashboard");
		// window.location.reload();
	},
	onError: (err) => {
		showNotice.error({ title: "Some Issue came up Loging in.", message: err });
	},
});

const handleSsoPopup = async () => {
	try {
		const popupWindow = loginPopupRef.current;
		if (popupWindow && !popupWindow?.closed && popupWindow?.focus) {
			popupWindow?.focus?.();
		} else {
			const res = await instance.loginPopup({ scopes: loginRequestScopes, prompt: "select_account" });
			const token = res?.accessToken || res?.access_token || "";
			const { email = "" } = jwt_decode(token) || {};
			console.log("authenticated: ", res);

			popupWindow?.close?.();
			loginPopupRef.current = null;

			if (token && email) {
				mutate({ token, staffId: email });
				console.log("ran mutate..");
			} else {
				showNotice.error({
					title: "Microsoft Token Error",
					message: "Valid authorization token not found",
				});
			}
		}
	} catch (error) {
		loginPopupRef.current?.close?.(); // Close the popup in case of an error
		loginPopupRef.current = null;
		if (!error.message?.includes("user_cancelled")) {
			showNotice.error({ title: "Microsoft Login Error", message: error });
		}
	}
};

useEffect(() => {
	instance.addEventCallback((message) => {
		if (message.eventType === EventType.POPUP_OPENED) {
			loginPopupRef.current = message.payload.popupWindow;
		}
	});
}, [instance]);
```

### Reproduction Steps

1. Open login popup by clicking login button on the "/techlogin" page.
2. Complete microsoft account link process.
3. After ms account login inside the popup window is done you'll see the techlogin page opening up inside the popup window.

### Expected Behavior

Login should close the popup window and redirect to "/dashboard" route as expected.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
Please update to the latest versions of both msal-browser and msal-react and let us know if you're still experiencing this issue

**Comment by henrylake** [comment]
I am also facing this issue, is there any chance this will be fixed in version 2 of msal-browser or will I need to migrate to 3?

**Comment by developerMahian** [comment]
> Please update to the latest versions of both msal-browser and msal-react and let us know if you're still experiencing this issue

Same popup issue even with latest versions of both packages

**Comment by developerMahian** [comment]
> I am also facing this issue, is there any chance this will be fixed in version 2 of msal-browser or will I need to migrate to 3?

I've replaced popup method with redirect page sign-in. Also the second step auth endpoint call has been placed in a separate hook and used at the root App component. Auth hook uses the access-token from loginRedirect() call response.

This way I've resolved my scenario.

**Comment by henrylake** [comment]
> I've replaced popup method with redirect page sign-in. Also the second step auth endpoint call has been placed in a separate hook and used at the root App component. Auth hook uses the access-token from loginRedirect() call response.
> 
> This way I've resolved my scenario.

Thank you! Using `loginRedirect` seems to have fixed it for me too.
