### ISSUE TITLE
msal-angular getAllAccounts returns an empty array on first load after MsalBroadcastService.inProgress$ InteractionStatus.None

### ISSUE THREAD

**Issue by willyt150** [AzureAD/microsoft-authentication-library-for-js#6653]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.4.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.7

### Public or Confidential Client?

Public

### Description

Just upgraded from v2 to v3 of the msal-angular package (and msal-browser) and we are using the Popup interaction type in an Angular 15 project.

In the app.component.cs I'm mimicking the Angular 15 example for listening to the MsalBroadcastService.inProgress$ with InteractionStatus.None. I have also made sure to bootstrap the MsalRedirectComponent in the app module AND I use `PublicClientApplication.createPublicClientApplication`.

On first load of the site (new tab), when the MsalBroadcaseService.inProgress$ fires with `"none"` InteractionStatus, the MsalService.instance.getAllAccounts() is empty, and therefore never have an account to set as the active account.

If I then refresh the page (same tab), getAllAccounts() has an account and everything works.

[Found this older issue from 2020](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2615#issuecomment-729830186) saying that the handling of the redirect wasn't finished when calling getAllAccounts, so I just wrapped all the code in the inProgress$ handler in a `settimeout` that waits 2 seconds (1 second sometimes worked and sometimes didn't), and THEN getAllAccounts() has entries.

This seems like a bug to me that the `InteractionStatus.None` is firing before there are any accounts, but I'd love to know if I'm doing something wrong instead.

### Error Message

No error message occurs

### Msal Logs

**New Tab logs**
- Angular is running in development mode. Call enableProdMode() to enable production mode. main.ts:23
- msal: [Fri, 03 Nov 2023 20:40:29 GMT] : [a4e2b7cc-208f-4651-b3b2-af15b80021e7] : @ : Info - initialize has already been called, exiting early. core.mjs:23480
- Angular is running in development mode. Call enableProdMode() to enable production mode. main.ts:23
- msal: [Fri, 03 Nov 2023 20:40:29 GMT] : [2ca373b6-9f36-440a-8673-e70d1131dab1] : msal.js.browser@3.4.0 : Info - handleRedirectPromise did not detect a response hash as a result of a redirect. Cleaning temporary cache.
app.component.ts:331

**Refresh of current tab logs**
- Angular is running in development mode. Call enableProdMode() to enable production mode. main.ts:23
- msal: [Fri, 03 Nov 2023 20:43:11 GMT] : [9cbbcdb1-634b-45d2-91fb-1c1a8d440545] : @ : Info - initialize has already been called, exiting early. core.mjs:23480
- Angular is running in development mode. Call enableProdMode() to enable production mode. main.ts:23
- msal: [Fri, 03 Nov 2023 20:43:11 GMT] : [4d570a8e-4630-4804-974d-ca8bab4b2dc6] : msal.js.browser@3.4.0 : Info - handleRedirectPromise did not detect a response hash as a result of a redirect. Cleaning temporary cache. app.component.ts:329
- Active Account set configuration.service.ts:88
- Client Configuration: Initializing main.ts:23
- msal: [Fri, 03 Nov 2023 20:43:12 GMT] : [9cbbcdb1-634b-45d2-91fb-1c1a8d440545] : @azure/msal-angular@3.0.7 : Info - Interceptor - 1 scopes found for endpoint zone.js:2345
- [Violation] 'setTimeout' handler took 77ms loading.interceptor.ts:17
- Client Configuration finished loading main.ts:23
- msal: [Fri, 03 Nov 2023 20:43:13 GMT] : [9cbbcdb1-634b-45d2-91fb-1c1a8d440545] : @azure/msal-angular@3.0.7 : Info - Interceptor - 1 scopes found for endpoint main.ts:23
- msal: [Fri, 03 Nov 2023 20:43:13 GMT] : [9cbbcdb1-634b-45d2-91fb-1c1a8d440545] : @azure/msal-angular@3.0.7 : Info - Interceptor - 1 scopes found for endpoint main.ts:23
- msal: [Fri, 03 Nov 2023 20:43:13 GMT] : [9cbbcdb1-634b-45d2-91fb-1c1a8d440545] : @azure/msal-angular@3.0.7 : Info - Interceptor - 1 scopes found for endpoint main.ts:23
- msal: [Fri, 03 Nov 2023 20:43:13 GMT] : [9cbbcdb1-634b-45d2-91fb-1c1a8d440545] : @azure/msal-angular@3.0.7 : Info - Interceptor - 1 scopes found for endpoint main.ts:23
- msal: [Fri, 03 Nov 2023 20:43:16 GMT] : [9cbbcdb1-634b-45d2-91fb-1c1a8d440545] : @azure/msal-angular@3.0.7 : Info - Interceptor - 1 scopes found for endpoint

### MSAL Configuration

```javascript
{
  "auth": {
    "clientId": "<ClientIDGuid>",
    "authority": "https://login.microsoftonline.com/<TenantIdGuid>",
    "validateAuthority": true,
    "redirectUri": "http://localhost:4200",
    "navigateToLoginRequestUrl": true
  },
  "cache": {
    "cacheLocation": "sessionStorage",
    "storeAuthStateInCookie": false
  },
  "system": {
    "loadFrameTimeout": 90000
  }
}
```

### Relevant Code Snippets

`main.ts`
``` ts
// we retrieve the msal configuration from a file hosted next to the site's js/css/html/etc files
// so that we can deploy the same bits to multiple environments and just change the contents of that config file
// so we load that file first before bootstrapping the AppModule
const configurationService = injector.get(ConfigurationService as Type<ConfigurationService>);
void configurationService.initializeConfiguration(environment, true).then(() => {
  const currentConfig = configurationService.getConfiguration();

  void PublicClientApplication.createPublicClientApplication(currentConfig.msal)
    .then(msalInstance => {
      msalInstance.setLogger(new Logger({
        correlationId: v4(),
        piiLoggingEnabled: false,
        loggerCallback
      }));

      const interceptorConfig: MsalInterceptorConfiguration = {
        interactionType: InteractionType.Popup,
        protectedResourceMap: new Map(currentConfig.protectedResourceMap)
      };

      const guardConfig: MsalGuardConfiguration = {
        interactionType: InteractionType.Popup
      };

      platformBrowserDynamic([
        { provide: ConfigurationService, useValue: configurationService },
        { provide: MSAL_INSTANCE, useValue: msalInstance },
        { provide: MSAL_INTERCEPTOR_CONFIG, useValue: interceptorConfig },
        { provide: MSAL_GUARD_CONFIG, useValue: guardConfig }
      ])
        .bootstrapModule(AppModule)
        .catch(err => console.error(err));
    });
});
```

`app.module.ts`
``` ts
// just showing that I am indeed bootstrapping the MsalRedirectComponent following the guide
bootstrap: [AppComponent, MsalRedirectComponent]
```

`app.component.ts`
``` ts
// omitted everything that happens after authentication
private readonly subscription = new Subscription();
private readonly _destroying$ = new Subject<void>();

public isAuthenticated = false;

constructor(
  private msalBroadcastService: MsalBroadcastService,
  private authService: MsalService) {

}

ngOnInit(): void {
  this.subscription.add(this.msalBroadcastService.inProgress$
    .pipe(
      filter((status: InteractionStatus) => status === InteractionStatus.None),
      takeUntil(this._destroying$)
    )
    .subscribe((status: InteractionStatus) => {
      const msalUser = this.checkAndSetActiveAccount();

      this.checkAuthorizationStatus();

      if (msalUser) {
        void this.initializeAsync();
      }
    }));

  this.checkAuthorizationStatus();
  if (!this.isAuthenticated) {
    void this.authService.loginPopup();
  } else {
    void this.initializeAsync();
  }
}


ngOnDestroy(): void {
  this._destroying$.next(null);
  this._destroying$.complete();
  this.subscription.unsubscribe();
}

private async initializeAsync(): Promise<void> {
  // api calls and everything to do once authenticated  
}

private checkAndSetActiveAccount(): AccountInfo {
  /**
   * If no active account set but there are accounts signed in, sets first account to active account
   * To use active account set here, subscribe to inProgress$ first in your component
   */
  let activeAccount = this.authService.instance.getActiveAccount();

  if (!activeAccount && this.authService.instance.getAllAccounts().length > 0) {
    const accounts = this.authService.instance.getAllAccounts();
    activeAccount = accounts[0];
    this.authService.instance.setActiveAccount(activeAccount);
  }

  if (activeAccount) {
    console.debug('Active Account set');
  } else {
    console.debug('No account available to set as active account');
  }

  return activeAccount;
}

private checkAuthorizationStatus(): void {
  this.isAuthenticated = !!this.authService.instance.getActiveAccount();
}
```

### Reproduction Steps

1. Running angular 15 site locally
2. Open new Chrome browser tab
3. Navigate to the site
4. Popup opens and closes and InteractionStatus.None fires
5. **this.authService.instance.getAllAccounts() is empty**
6. Refresh the site, in the same tab
7. Popup opens and closes and InteractionStatus.None fires AND this.authService.instance.getAllAccounts() has a value

### Expected Behavior

First load of site, this.authService.instance.getAllAccounts() should have an account after successful signin from the popup

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge

### Regression

@azure/msal-angular 2.5.7 @azure/msal-browser 2.37.0

### Source

External (Customer)

**Comment by tnorling** [comment]
`InteractionStatus` isn't the right signal to use for this. `InteractionStatus.None` should be used to inform when it's safe to call `loginPopup` (which it doesn't appear you're doing). Then to set the active account you can either chain a `.then` directly off `loginPopup` or subscribe to the `LOGIN_SUCCESS` event

**Comment by willyt150** [comment]
Thank you so much @tnorling!

You are 100% correct, I was NOT using it to know when it's safe to call `loginPopup`

Following your suggestion, changing the code in `ngOnInit` to the following has resolved my issue. Thanks again!

``` ts
ngOnInit(): void {
  this.subscription.add(this.msalBroadcastService.inProgress$
    .pipe(
      filter((status: InteractionStatus) => status === InteractionStatus.None),
      takeUntil(this._destroying$)
    )
    .subscribe((status: InteractionStatus) => {
        this.checkAuthorizationStatus();
        if (!this.isAuthenticated) {
          this.subscription.add(this.authService.loginPopup().subscribe(() => {
            const msalUser = this.checkAndSetActiveAccount();

            this.checkAuthorizationStatus();

            if (msalUser) {
              this.appInsightsService.logEvent('LoginSuccess', { User: msalUser.username });
              void this.initializeAsync();
            }
          }));
        } else {
          void this.initializeAsync();
        }
    }));
}
```
