### ISSUE TITLE
PublicClientApplication not getting imported from @azure/msal-browser

### ISSUE THREAD

**Issue by MJaithra** [AzureAD/microsoft-authentication-library-for-js#6655]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.4.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.0.6

### Public or Confidential Client?

Public

### Description

I am importing PublicClientApplication from @azure/msal-browser. I find nothing in my node_modules folder corresponding to PublicClientApplication.

I do a F12 (using VScode) on the PublicClientApplication in the import statement or the constructor use din creating an msalInstance, it says "No definition found for PublicClientApplication".

I am using MsalProvider from @azure/msal-react. While passing instance created from the above used PublicClientApplication, I get an error saying 
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/137266209/caf015af-df80-42e8-9947-02fa0d933a28)

### Identity Provider

None

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
Need more information. Please check that msal-browser is installed in your environment. If it is and you're still seeing this error please share a minimal repro so we can investigate.
