### ISSUE TITLE
msal-node `acquireTokenInteractive` API displays "connection refused" error on the browser after authentication

### ISSUE THREAD

**Issue by KarishmaGhiya** [AzureAD/microsoft-authentication-library-for-js#6657]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

2.3.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

N/A

### Public or Confidential Client?

Public

### Description

In the browser credential scenarios where `acquireTokenInteractive` API successfully returns a token after user's login through the redirect URI, instead of a message being displayed on the browser indicating whether the authentication is successful or not, there is an `ERR_CONNECTION_REFUSED` in the browser once the auth is completed. This is not an ideal user experience for any of our customers who build on our SDKs. This also means that the "success Message" and "error Message" templates that the users provide, don't get displayed on the browser. So there are two issues associated with this bug. 

Before taking a dependency on @azure/msal-node, we had our own in-house implementation of the server and redirect URIs where we displayed a message "Authentication Complete. You can close the browser and return to the application." So the above behavior from msal-node's acquireTokenInteractive API is a regression.

The Office Growth/ Cloudpack Team is blocked on this issue for their release to using Node 20 version. They won't be able to upgrade to using our package with this issue.

### Error Message

`ERR_CONNECTION_REFUSED`  on the browser

### MSAL Configuration

```javascript
auth: {
      clientId: process.env.CLIENT_ID,
      authority: process.env.AUTHORITY,
  },
```

### Relevant Code Snippets

```ts
import open from "open";
import { PublicClientApplication } from "@azure/msal-node";
import * as dotenv from "dotenv";

async function main() {
  dotenv.config();

  const interactiveBrowserMockable = {
    open,
  };
  async function openBrowser(url) { 
    await interactiveBrowserMockable.open(url, { wait: true, newInstance: true });
  } 
  const app = new PublicClientApplication({
    auth: {
      clientId: process.env.CLIENT_ID,
      authority: process.env.AUTHORITY,
  },
  });
  const result = await app.acquireTokenInteractive({
    scopes: ["user.read"],
    openBrowser: openBrowser,
    successTemplate: "Authentication successful, close the browser window"
});
  console.log(result);
}

main().catch(e => console.error(e));
```

### Reproduction Steps

1. Install v 2.3.0 of @azure/msal node 
2. Create a sample package with the above snippet 
3. Run the code 
4. The authentication token will be returned in the console but the browser displays "ERR: CONNECTION REFUSED"

### Expected Behavior

The browser should indicate that the authentication was successful and display that message.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Source

Internal (Microsoft)

**Comment by joshfree** [comment]
> The Office Growth/ Cloudpack Team is blocked on this issue for their release to using Node 20 version. They won't be able to upgrade to using our package with this issue.

Additional the release of the azure-identity-broker package is also blocked by this issue.

**Comment by jynolen** [comment]
We got the same issue might be related to #6481

**Comment by johnvox** [comment]
We got the same issue.
Issue occurs with version 2.x.x and upper version 1.8.x  is not affected
