### ISSUE TITLE
CredentialManagement API support

### ISSUE THREAD

**Issue by RichardMaher** [AzureAD/microsoft-authentication-library-for-js#667]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ X ] Feature request
[ X ] Documentation issue or request
[ X ] Other... Please describe: W3C Standard support
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ X ] Edge version XX
- [ ] Safari version XX

Can you please explain, or point me to someone who can explain, MS/Edge intentions on providing support for [the CredentialManagement API?](https://www.w3.org/TR/credential-management-1/) Your going flat-out with WebAuthn/FIDO and say development of Password and Federated Credentials is underway but I can't see it :-(

It would certainly reduce MSAL code and vastly improve browser application  look and feel!

**Comment by sameerag** [comment]
@navyasric  any insights?

**Comment by pkanher617** [comment]
@RichardMaher We are still discussing this. We will update you as soon as we have some more info. Thanks

**Comment by DarylThayil** [comment]
Moving to Triage, @sameerag  to add context

**Comment by jasonnutter** [comment]
Closing, as we have no plans to support this currently.
