### ISSUE TITLE
 useIsAuthenticated() is giving always false with protected route

### ISSUE THREAD

**Issue by ranshine** [AzureAD/microsoft-authentication-library-for-js#6670]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.0.7

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

After msal login everywhere  useIsAuthenticated() is giving true, but for protected route it is giving false

### MSAL Configuration

```javascript
export const msalConfig: Configuration = {
    auth: {
        clientId: "clientID",
        authority: "authority",
        redirectUri: "/",
        postLogoutRedirectUri: "/",
        navigateToLoginRequestUrl: false
    },
    cache: {
        cacheLocation: "localStorage",
        storeAuthStateInCookie: false,
    }
};
```

### Relevant Code Snippets

```javascript
<Routes>
              <Route path="/" element={<Home />} />
              <Route element={<ProtectedRoute />}>
                <Route path={Product} element={<Product />} />
                <Route path={Delivery} element={<Delivery />} />
              </Route>
              <Route path="*" element={<NotFound />} />
            </Routes>

import { useIsAuthenticated } from '@azure/msal-react'
import React from 'react'
import { Outlet, Navigate } from 'react-router-dom'


export const ProtectedRoute = () => {
  const isAuthenticated = useIsAuthenticated()
  console.log(isAuthenticated)  // false
  return localStorage.getItem('msal.account.keys') != null ? <Outlet /> : <Navigate to="/" />
}
```

### Reproduction Steps

```
import { useIsAuthenticated } from '@azure/msal-react'
import React from 'react'
import { Outlet, Navigate } from 'react-router-dom'


export const ProtectedRoute = () => {
  const isAuthenticated = useIsAuthenticated()
  console.log(isAuthenticated)  // false
  return localStorage.getItem('msal.account.keys') != null ? <Outlet /> : <Navigate to="/" />
}
```

### Expected Behavior

useIsAuthenticated should give true after login everywhere

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
useIsAuthenticated will always be false on first render. Once initialization steps have completed it should reflect the correct value. With this in mind, it is not advisable to auto-navigate to another route upon a false value as you will always hit this condition on the first render. If your desire is to build a protected route I suggest using either the `AuthenticatedTemplate` or `MsalAuthenticationTemplate` exported by msal-react.

Additionally, please do not look for specific MSAL storage keys. Storage is not part of MSAL.js's API surface and keys/values are subject to change at any time.

**Comment by ranshine** [comment]
@tnorling I got your point but in our application we have multiple ways to do login(phone number login, google login) not only msal, that's why i am using useAuthenticated to identify user is logged in or not.

**Comment by vponnurudb** [comment]
useIsAuthenticated() is not reactive. I am using the state variable as a dependency in useEffect. But after authentication completes, the useEffect is not triggered.

const isConnected = useIsAuthenticated()
const [xyz, setXyz] = useState()

useEffect(()=> {

// do something to xyz

}, [isConnected]

I need to update my app's local xyz state based on isConnected's change in state. But the useEffect is not triggered after successful authentication. Is this the expected behavior?
