### ISSUE TITLE
Token request cannot be made without authorization code or refresh token when I add "teamsAppInstallation.ReadWriteSelfForChat.All" scope

### ISSUE THREAD

**Issue by malinosqui** [AzureAD/microsoft-authentication-library-for-js#6673]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

2.5.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Confidential

### Description

Hello everyone,

I'm currently facing an issue with the MSAL Node.js authentication library (msal2.js). When attempting to integrate the 'teamsAppInstallation.ReadWriteSelfForChat.All' scope into the Auth-Code flow for a Node.js application, I'm encountering the following error:

ClientAuthError: request_cannot_be_made: Token request cannot be made without authorization code or refresh token.

I'm utilizing the [auth-code sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-node-samples/auth-code) provided in the MSAL Node.js library, with the only modification being the addition of the aforementioned scope to my configuration. Below, I've shared the relevant segment of my customConfig.json and the primary code snippet where the error surfaces.

My auth configuration on Azure Entra Admin Center:
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/5993570/597a4dbd-2c91-4bdd-b93a-f3150f1b4eb0)

I would greatly appreciate any insights or guidance on resolving this error. Is there an additional configuration step or permission that I'm potentially missing for this specific scope?

Thank you for your assistance!

### MSAL Configuration

```javascript
{
  "authOptions": {
    "clientId": "fed2db9f-c2a4-44d9-ba19-8dbb4eece8cb",
    "authority": "https://login.microsoftonline.com/organizations/"
  },
  "request": {
    "authCodeUrlParameters": {
      "scopes": ["user.read", "user.read.all", "teamsAppInstallation.ReadWriteSelfForChat.All"],
      "redirectUri": "http://localhost:3000/redirect"
    },
    "tokenRequest": {
      "redirectUri": "http://localhost:3000/redirect",
      "scopes": ["user.read", "user.read.all", "teamsAppInstallation.ReadWriteSelfForChat.All"]
    }
  },
  "resourceApi": {
    "endpoint": "https://graph.microsoft.com/v1.0/me"
  }
}
```

### Relevant Code Snippets

```javascript
// Relevant express setup and MSAL initialization code
// ...

app.get("/redirect", (req, res) => {
  const tokenRequest = {
    ...requestConfig.tokenRequest,
    code: req.query.code,
    state: req.query.state,
  };
  // Additional code for handling the token request
  // ...
});
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by tnorling** [comment]
Can you please verify that `req.query.code` is defined? If not, please inspect the actual value of req.query, it's likely that some error is being returned instead which is not being handled and may give you more insight into what's happening.
