### ISSUE TITLE
Do not show unauthenticated template before redirect

### ISSUE THREAD

**Issue by nvonbenken** [AzureAD/microsoft-authentication-library-for-js#6674]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.3.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.0.5

### Public or Confidential Client?

Public

### Description

When hitting our application as an unauthenticated user the `UnauthenticatedTemplate` content is being displayed to the user before the redirect.

We are using `useMsalAuthentication` as follows:
```
  const { result, error, login } = useMsalAuthentication(
    InteractionType.Redirect,
    {
      scopes: [],
      extraQueryParameters: { ...extraParams },
    }
  );
```

### MSAL Configuration

```javascript
{
  auth: {
    clientId: clientId,
    authority: `https://${tenant}.b2clogin.com/${tenant}.onmicrosoft.com/${policy}`,
    knownAuthorities: [`${tenant}.b2clogin.com`],
    redirectUri: redirectUri,
    postLogoutRedirectUri: postLogoutRedirectUri,
  },
  cache: {
    cacheLocation: 'localStorage', // This configures where your cache will be stored
    storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
  },
}
```

### Relevant Code Snippets

```javascript
function AuthWrapper({
  instance,
  children,
}: PropsWithChildren<IAuthWrapperProps>) {
  const { result, error, login } = useMsalAuthentication(
    InteractionType.Redirect,
    {
      scopes: [],
    }
  );

  return (
    <>
      <AuthenticatedTemplate>{children}</AuthenticatedTemplate>
      <UnauthenticatedTemplate>
        <Error />
      </UnauthenticatedTemplate>
    </>
  );
}
```
```


### Reproduction Steps

1. Be unauthenticated
2. Hit application
3. Observe `UnauthenticatedTemplate` content before redirect.

### Expected Behavior

The `UnauthenticatedTemplate` content doesn't show when a user is in a "pending" state where MSAL is trying to determine the users status.

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge

### Regression

_No response_

### Source

External (Customer)

**Comment by tnorling** [comment]
This is expected behavior. The `UnauthenticatedTemplate` and `AuthenticatedTemplate` are very basic - if user signed in render this, else render that.

For this use case you may consider using the `MsalAuthenticationTemplate` instead which provides you the ability to specify a "Loading component" to be rendered while authentication is in progress. Otherwise I'd suggest you write your own implementation of the `UnauthenticatedTemplate` that takes inProgress state into account.

**Comment by nvonbenken** [comment]
> This is expected behavior. The `UnauthenticatedTemplate` and `AuthenticatedTemplate` are very basic - if user signed in render this, else render that.
> 
> For this use case you may consider using the `MsalAuthenticationTemplate` instead which provides you the ability to specify a "Loading component" to be rendered while authentication is in progress. Otherwise I'd suggest you write your own implementation of the `UnauthenticatedTemplate` that takes inProgress state into account.

Regarding the `inProgress` state where is that available from? It doesn't seem to be returned by `useMsalAuthentication`

**Comment by tnorling** [comment]
[useMsal hook](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/hooks.md#usemsal-hook)
