### ISSUE TITLE
User redirects to the forgot password instead of login page when session expired 

### ISSUE THREAD

**Issue by hansakaRightS** [AzureAD/microsoft-authentication-library-for-js#6677]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.0.4

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.4

### Public or Confidential Client?

Public

### Description

Hello, 

Whenever user resets the password using forget password from the login, after successful password reset user is logged into the system. then if the user session is expired and `acquireTokenSilent` is failed to get renew the token we call the login again. Problem is being the user is redirects back to the forgot password UI instead on the login page.

here is the login method we execute.
```
      const redirect = this.msalService.loginRedirect({
        scopes: [`https://${environment.activeDirectory.domain}/${environment.activeDirectory.tenantId}/access_as_user`],
        extraQueryParameters: extraParameters,
        redirectUri: redirectUri
      });
      
      ```

### MSAL Configuration

```javascript
auth: {
        clientId: clientId,
        authority: "B2C_1A_SIGNUP_SIGNIN",
        redirectUri: '/',
        navigateToLoginRequestUrl: false
    },
    cache: {
        cacheLocation: "LocalStoarage",
        storeAuthStateInCookie: false
    }
```

### Relevant Code Snippets

```javascript
this.activeDirectoryService.acquireTokenSilent$()
          .pipe(
            switchMap(res => {
              if (!res?.accessToken) {
                throw Error("Invalid Access token: " + res?.accessToken);
              }
              this.setStorageToken(res.accessToken);
              this.msalService.instance.setActiveAccount(res.account);
              return of(new GetToken());
            }),
            catchError(err => {
              if (err instanceof InteractionRequiredAuthError) {
                return of(
                  new LogWarning('Acquire Token Error. Interaction Required Auth Error. Error message: ' + err.errorMessage),
                  new MsalAcquireTokenRedirect({ context: 'Acquiring Token Silently', subcontext: 'Catch Error InteractionRequiredAuthError' })
                )
              }
              else {
                return of(
                  new LogError('Acquire Token Error. Unexpected Error. Error message: ' + err),
                  new LoginAction({ context: 'Acquiring Token Silently', subcontext: 'Catch Error Unexpected Error' })
                );
              }
            })
          )
      }
      return of(
        new LoginAction({ context: 'Acquiring Token Silently', subcontext: 'No Active Account Available' })
      );
    })
  ), { dispatch: true });
```
```


### Reproduction Steps

1. Go to the login page
2. initiate forget password 
3. after successful password reset user logs into the system automatically
4. wait until the token expire and system should call the login action

### Expected Behavior

we should be able to go to the login after the logic action called instead of forgot password 

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari, Internet Explorer

### Regression

_No response_

### Source

External (Customer)

**Comment by tnorling** [comment]
It's not clear to me from your description if you have 1 policy or 2.

If you have a single policy which supports both login and password reset and B2C is rendering an unexpected UX:

- Please [open a ticket with the B2C service](https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options) as MSAL doesn't control UX

If you have separate policies for login and password reset:

- Ensure you're providing the correct policy in the authority field of the login request

**Comment by hansakaRightS** [comment]
we are using  sign-up and sign-in journey to add the forgot password step. the implementation is similar to this,
https://learn.microsoft.com/en-us/azure/active-directory-b2c/add-password-reset-policy?pivots=b2c-custom-policy

**Comment by tnorling** [comment]
Thanks for confirming. This is controlled by the B2C service - [please open a ticket with B2C](https://docs.microsoft.com/en-us/azure/active-directory-b2c/support-options) for more assistance
