### ISSUE TITLE
Guarding a route using MSAL.js

### ISSUE THREAD

**Issue by Rorotu** [AzureAD/microsoft-authentication-library-for-js#668]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

For guarding a route, is calling acquireTokenSilent an appropriate way to ensure that the user is still authenticated when using MSAL.js (msal-core) ? 

Also, when the application is offline, what would be an appropriate way to let the user use the app for a specific period of time before forcing him to come back online to get a token ? Do I need to use KMSI ?

</code></pre>

**Comment by sameerag** [comment]
@Rorotu  Is this B2C? and Is this Angular?

**Comment by Rorotu** [comment]
Yes, it is b2c, but not angular.

**Comment by sameerag** [comment]
Guarding routes are usually in the context of msal-angular in our code and hence I was confused if it is an angular app.

Our tokens expire every hour. If you want a silent authentication you can call acquireTokenSilent periodically to keep session, If you choose user interaction for expired tokens for your app model, you can call loginPopup (for idToken) and then acquireToken() calls for the accessTokens.

**Comment by Rorotu** [comment]
I guess the periodic check could work well with a web worker. 

However, this solution will probably not work when the web app is offline, given that the token expire every hour.

**Comment by sameerag** [comment]
We do not want tokens to be valid for longer durations in SPAs and hence there is a default one hour expiry. 
From the service, accessTokens can be configured for a max 1 day expiry referenced 
 at [Configurable Token Lifetimes](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes) 

If you are setting it for less than 5 mins though, please read through this issue #512 and change the offset.

**Comment by Rorotu** [comment]
Why should I extend the access/id token lifetime ? If the the access/id token lifetime is 60 minutes and the web app session lifetime is 1440 minutes, why do I need to periodically call acquireTokenSilent before the access token expire. Instead, shouldn't acquireTokenSilent be called before the expiration of the web session? In which case, this bring us to the same limit of 1 day.

**Comment by navyasric** [comment]
@Rorotu The acquireTokenSilent method renews the access and id tokens cached by the library. If it is called before the expiration of the user session with Azure AD, the session is kept active and it will extend the session. However, the library or your app does not track if the user session on Azure AD domain is active or not. Please take a look at this [FAQ topic](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/FAQs#q3-how-to-renew-tokens-with-msaljs) on the token renewal pattern.

**Comment by Rorotu** [comment]
Yes, I wanted to confirm this behavior, because I think I might have a problem with the session duration. I will verify and see how it goes. Thanks !

**Comment by sameerag** [comment]
@Rorotu Please let us know if we can close this issue once you test this.

**Comment by Rorotu** [comment]
I did some tests and it works. The problem was on my side. I kept my original solution. I call acquireTokenSilent (with the fallback on acquireTokenRedirect) when the user navigate through the app.
