### ISSUE TITLE
Hybrid Storage of Tokens

### ISSUE THREAD

**Issue by johnkm516** [AzureAD/microsoft-authentication-library-for-js#6682]
### Core Library

MSAL.js (@azure/msal-browser)

### Wrapper Library

Not Applicable

### Public or Confidential Client?

Public

### Description

My architecture consists of an frontend SPA, middle-tier API Gateway (custom built), and backend APIs. 
Currently my plan is to authenticate between SPA and API Gateway using OIDC with PKCE, then use OBO between the API Gateway and backend APIs. 

The problem is the options MSAL currently provides for token storage is not usable either security-wise or user-friendly-wise. 
If I choose _localStorage_ or _sessionStorage_, I'm still storing all the token data in storage that is vulnerable to XSS attacks. 
If I choose _memoryStorage_, it completely ruins the user experience as when they refresh the page they are logged out. 

I propose a hybrid solution. 
Store all other data that is not the refresh_token in _localStorage_ or _sessionStorage_ or _memoryStorage_ (whatever the developer chooses), but give us a way to override where the refresh_token is stored. Access_tokens are short lived and therefore can be stored in _localStorage_. Refresh tokens should be stored in an HttpOnly Secure cookie. With the current options MSAL provides there is no in between like the hybrid solution above. Either you sacrifice security or you sacrifice user experience. I don't understand why refresh_tokens are stored the same way as access_tokens when they are significantly longer lived and completely nullifies any point in having a short access_token lifespan. 

### Source

External (Customer)

**Comment by tnorling** [comment]
SPA refresh tokens have a much shorter, 24 hour, lifetime and are not renewable for this reason. Furthermore we have [a new feature](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/device-bound-tokens.md) in the works that will result in refresh tokens being stored in and bound to the platform broker and they will never be exposed to the browser in this flow.

Closing as we won't be picking this up at this time.
