### ISSUE TITLE
SSO between two React applications InteractionRequiredAuthError: login_required

### ISSUE THREAD

**Issue by jamalkhattab** [AzureAD/microsoft-authentication-library-for-js#6686]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.4.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.0.6

### Public or Confidential Client?

Public

### Description

I am attempting to perform local testing of SSO capabilities with two React applications on different subdomains but I am getting InteractionRequiredAuthError: login_required.

The first application is responsible for handling the login process and enabling users to redirect to the second application without requiring them to re-enter credentials. To achieve this, I created two React applications, both using MSAL, running locally on ports 3001 and 3002. I configured Nginx to proxy pass requests, using a self-signed certificate, to servers at https://app1.local and https://app2.local, which in turn point to http://127.0.0.1:3001 and http://127.0.0.1:3002, respectively. 

Both applications are using the same clientId under the same tenant. 

To test the login process, I'm using an internal user I created under my organization. Their email domain is @{tenantname}.onmicrosoft.com. After successfully logging in on app1, I am passing the authenticated email as a query parameter while redirecting to app2. App2 retrieves the email from the query param and tries to perform an ssoSilent request while using the email as the loginHint, however, I am getting InteractionRequiredAuthError: login_required: AADSTS50058: A silent sign-in request was sent but none of the currently signed in user(s) match the requested login hint.

I tried catching the error and performing a loginPopup request with prompt "none", but I am getting the same error. I am also redirecting to a blank page (redirect.html) for both login attempts (ssoSilent and loginPopup). The redirect URIs in Entra are the following:
https://app2.local/redirect.html
https://app2.local/

Any insight as to what could be causing the error would be highly appreciated. The below code snippets and configurations are of App2.

### MSAL Configuration

```javascript
import { LogLevel } from "@azure/msal-browser";

export const msalConfig = {
    auth: {
        clientId: "{SameClientId as App1}", 
        authority: "https://login.microsoftonline.com/{tenantId}, 
        redirectUri: "/redirect.html", 
        postLogoutRedirectUri: "/", 
        navigateToLoginRequestUrl: false
    },
    cache: {
        cacheLocation: "localStorage", 
        storeAuthStateInCookie: false, 
    },
    system: {
        loggerOptions: {
            loggerCallback: (level, message, containsPii) => {
                if (containsPii) {
                    return;
                }
                switch (level) {
                    case LogLevel.Error:
                        console.error(message);
                        return;
                    case LogLevel.Info:
                        console.info(message);
                        return;
                    case LogLevel.Verbose:
                        console.debug(message);
                        return;
                    case LogLevel.Warning:
                        console.warn(message);
                        return;
                }
            }
        }
    }
};


export const protectedResources = {
    apiTodoList: {
        scopes: {
            read: [ "api://{SameClientId as App1}/Todolist.Read" ],
            write: [ "api://{SameClientId as App1}/Todolist.ReadWrite" ]
        }
    }
}


export const loginRequest = {
    scopes: [...protectedResources.apiTodoList.scopes.read, ...protectedResources.apiTodoList.scopes.write]
};
```

### Relevant Code Snippets

```javascript
//App.jsx
import { useEffect } from 'react';
import { useMsal, AuthenticatedTemplate, MsalProvider, UnauthenticatedTemplate } from "@azure/msal-react";
import { InteractionRequiredAuthError } from "@azure/msal-browser";

const TestSSOComponent = () => {
    const {instance, inProgress } = useMsal();
    useEffect(() => {
        console.log('Component has mounted');
        
        const silentRequest = {
            loginHint: "test3@{tenantName}.onmicrosoft.com",
            scopes: ["api://{SameClientId as App1}/TodoList.Read", "api://{SameClientId as App1}/TodoList.ReadWrite"],
            redirectUri: '/redirect.html',
            prompt: 'none'
        };

        const loginResponse = instance.ssoSilent(silentRequest).then(tokenResponse => {
            console.log(tokenResponse);
        }).catch(error => {
            if (error instanceof InteractionRequiredAuthError) {
                console.log("InteractionRequiredAuthError caught");
                console.log(error);
                const loginResponse = instance.loginPopup(silentRequest).then(tokenResponse => {
                    console.log("login popup response:");
                    console.log(tokenResponse);
                });
            } else {
                console.log("other error");
                console.log(error);
            }
        });

        return () => {
          console.log('Component will unmount');
        };
      }, []);
}

const App = ({ instance }) => {
    return (
        <MsalProvider instance={instance}>
          <AuthenticatedTemplate>
            User is authenticated!
          </AuthenticatedTemplate>
          <UnauthenticatedTemplate>
            <TestSSOComponent />
          </UnauthenticatedTemplate>
        </MsalProvider>
    );
};

export default App;
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by tnorling** [comment]
username is an unreliable hint. Try using the [login_hint optional idToken claim](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/login-user.md#with-user-hint) instead.

**Comment by jamalkhattab** [comment]
I tried passing the login_hint optional idToken claim in the ssoSilent request as the loginHint but I am getting the same InteractionRequiredAuthError: login_required.

```javascript
const silentRequest = {
    loginHint: "O.CiR...gNg==",
    scopes: ["api://.../TodoList.Read", "api://.../TodoList.ReadWrite"],
    redirectUri: '/redirect',
    prompt: 'none'
};

const loginResponse = instance.ssoSilent(silentRequest).then(tokenResponse => {
    console.log(tokenResponse);
})

**Comment by jamalkhattab** [comment]
After changing the authority in both applications to https://login.microsoftonline.com/consumers/ I am able to login on app1 using a personal outlook email, and the ssoSilent request on app2 worked like a charm while passing the corresponding login_hint. 

@tnorling Any idea why authentication using a user created in my organization using the Microsoft Entra Admin center is giving "InteractionRequiredAuthError: login_required" using the authority https://login.microsoftonline.com/{tenantId} while personal accounts using the consumers authority work? Supported account types are set to: Accounts in any organizational directory (Any Microsoft Entra ID tenant - Multitenant) and personal Microsoft accounts

**Comment by tnorling** [comment]
There's nothing that comes to mind, we'd have to review the network logs and server traces to understand why that's happening. We (MSAL.js) aren't the best people to analyze that so if you'd like to dig into that further I'd suggest [opening a support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) and they should be able to assist you.
