### ISSUE TITLE
Angular 16 and 17 : BrowserAuthError: uninitialized_public_client_application

### ISSUE THREAD

**Issue by memory660** [AzureAD/microsoft-authentication-library-for-js#6691]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.5.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.5.0

### Public or Confidential Client?

Public

### Description

no error with :
`
    "@azure/msal-angular": "3.0.0-alpha.2",
    "@azure/msal-browser": "3.0.0-alpha.2",
`

error with 
`
    "@azure/msal-angular": "^3.0.8",
    "@azure/msal-browser": "^3.5.0",
`

### Error Message

ERROR BrowserAuthError: uninitialized_public_client_application: You must call and await the initialize function before attempting to call any other MSAL API.  For more visit: aka.ms/msaljs/browser-errors

### MSAL Configuration

```javascript
export function MSALInstanceFactory(): IPublicClientApplication {
  return new PublicClientApplication({
    auth: {
      clientId: environment.msalConfig.auth.clientId,
      authority: environment.msalConfig.auth.authority,
      redirectUri: '/',
      postLogoutRedirectUri: '/'
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage
    },
    system: {
      allowNativeBroker: false, // Disables WAM Broker
      loggerOptions: {
        loggerCallback,
        logLevel: LogLevel.Info,
        piiLoggingEnabled: false
      }
    }
  });
}
```

### Relevant Code Snippets

```javascript
AppModule
`ts
  providers: [
    {
      provide: HTTP_INTERCEPTORS,
      useClass: MsalInterceptor,
      multi: true
    },
    {
      provide: MSAL_INSTANCE,
      useFactory: MSALInstanceFactory
    },
`
```

### Reproduction Steps

from launch

### Expected Behavior

no more errors

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Regression

@azure/msal-browser: ^3.5.0

### Source

External (Customer)

**Comment by lalimasharda** [comment]
Hey @memory660 we do not support Angular 17 yet. For your issue with Angular 16, please take a look at #6693 ! Let me know if you need more help.

**Comment by memory660** [comment]
@lalimasharda ,   I can't find the solution in the link you gave me.

**Comment by mlz11** [comment]
> Hey @memory660 we do not support Angular 17 yet. For your issue with Angular 16, please take a look at #6693 ! Let me know if you need more help.

Hello @lalimasharda, do you have any idea on when you would support Angular 17 ? 
Thank you 🙏🏻

**Comment by mlz11** [comment]
> > Hey @memory660 we do not support Angular 17 yet. For your issue with Angular 16, please take a look at #6693 ! Let me know if you need more help.
> 
> Hello @lalimasharda, do you have any idea on when you would support Angular 17 ? Thank you 🙏🏻

🆙 🙏🏻

**Comment by javargasm** [comment]
support Angular 17 Pliss

**Comment by muhamedkarajic** [comment]
Angular 17, support, please, arigato. :)

**Comment by mlz11** [comment]
> > > Hey @memory660 we do not support Angular 17 yet. For your issue with Angular 16, please take a look at #6693 ! Let me know if you need more help.
> > 
> > 
> > Hello @lalimasharda, do you have any idea on when you would support Angular 17 ? Thank you 🙏🏻
> 
> 🆙 🙏🏻

Hey @lalimasharda @tnorling @konstantin-msft @jo-arroyo @hectormmg, sorry for mentioning you all... 
Can we please get an answer on that matter ? 🙏🏻

**Comment by tnorling** [comment]
Angular 17 support is being tracked in #6719, any updates we have to share will be posted there.

As for the original issue concerning the uninitialized error - you need to do one of the following:

1. Bootstrap the `MsalRedirectComponent`
2. Call `handleRedirectObservable`

Additionally you must wait for `inProgress` to become `None`. More information [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/redirects.md) and [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-v3-upgrade-guide.md)
