### ISSUE TITLE
UserAgentApplication is missing the loginInProgress

### ISSUE THREAD

**Issue by mlankamp** [AzureAD/microsoft-authentication-library-for-js#670]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 1.0.0-preview.4

</code></pre>

## Current behavior

In version <= 0.2.4 the UserAgentApplication has a function called loginInProgress

## Expected behavior

Bring back the loginInProgress function

**Comment by pkanher617** [comment]
@mlankamp I have changed the getLoginInProgress function to be publicly available. Please feel free to pull and test the branch and let me know if you have any further issues.

**Comment by mlankamp** [comment]
Thank you!

I'm going to give a try!
