### ISSUE TITLE
Login stuck after authentication, infinite load.

### ISSUE THREAD

**Issue by jewseppi** [AzureAD/microsoft-authentication-library-for-js#6708]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.5.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.0.7

### Public or Confidential Client?

Confidential

### Description

After upgrading the libs to the most recent version, the app would hang after login, white screen and an infinite loader in the browser.

Downgrading to the following versions resolved the issue.

  "dependencies": {
    "@azure/msal-browser": "^2.38.3",
    "@azure/msal-react": "^1.5.3",

### Error Message

No error message received.

### MSAL Configuration

```javascript
const msalConfig: Configuration = {
  auth: {
    clientId: process.env.REACT_APP_CLIENT_ID || '',
    authority: process.env.REACT_APP_AUTHORITY,
    redirectUri: process.env.REACT_APP_REDIRECT_URL,
    knownAuthorities: [process.env.REACT_APP_KNOWN_AUTHORITY || '']
  },
  cache: {
    cacheLocation: 'sessionStorage',
    storeAuthStateInCookie: false,
  },
  system: {
    tokenRenewalOffsetSeconds: 100,
  },
};
```

### Relevant Code Snippets

```javascript
"dependencies": {
    "@azure/msal-browser": "^3.5.0",
    "@azure/msal-react": "^2.0.7",
```

### Reproduction Steps

update versions to latest and run application, does not work.

### Expected Behavior

for it to work.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome

### Regression

2.38.3

### Source

External (Customer)

**Comment by Emp3r** [comment]
I have the same issue. 

```
"@azure/msal-browser": "3.5.0",
"@azure/msal-react": "2.0.7",
```
All tests fail at the login stuck after authentication... (Cypress version 13.5)

MSAL config:
```
{
    auth: {
      clientId: process.env.REACT_APP_CLIENT_ID,
      authority: process.env.REACT_APP_AUTHORITY,
      navigateToLoginRequestUrl: true,
    },
}
```

**Comment by reza-sadr** [comment]
I have a somewhat issue while attempting to call `accureTokenByCode` behind a proxy. The proxy agent tries to make a POST to `https://login.microsoftonline.com/xxxx-xxxx-xxxx-xxxxx/oauth2/v2.0/token` and throws a `network_error`.

Only happens when behind a proxy.

**Comment by tnorling** [comment]
We're going to need more information here to provide a suggestion. Please provide trace level logs, how you're using MSAL and any errors thrown.
