### ISSUE TITLE
Jest tests on msal-angular & msal-browser v3

### ISSUE THREAD

**Issue by Venators** [AzureAD/microsoft-authentication-library-for-js#6711]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.5.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.8

### Public or Confidential Client?

Public

### Description

I upgraded to Angular 15, and with that, I also upgraded @azure/msal-angular & @azure/msal-browser from 2.5.7 & 2.37.0 to 3.0.8 & 3.5.0 respectively. When I encountered the errors, I also tried v3.0.7 & v3.4.0 but same issue, and v3.0.6 & 3.3.0 but encountered the "Importing MsalModule which does not have a ɵmod property" issue I'd previously been stuck with under v2.5.7 & 2.37.0. Post-update, the app & authentication work, which is always a good start, but AppComponent tests now fail.

If I follow the msal-angular-v3-samples/angular-b2c-sample-app example (the closest option to my current implementation), the test fails with the error "TypeError: window.crypto.randomUUID is not a function". I think this is because it's using the actual services and failing when it can't access the browser-based function - this wasn't an issue previously, and isn't accounted for in the noted sample?

If I try mocking the MsalService & MsalBroadcastService, I get the following error instead:
    ` 
              TypeError: this.msalBroadcastService.inProgress$.pipe is not a function

      24 |      ngOnInit() {
      25 |              this.msalBroadcastService.inProgress$
    > 26 |                      .pipe(filter((status: InteractionStatus) => status === InteractionStatus.None), takeUntil(this._destroying$))
         |                       ^
      27 |                      .subscribe(async () => {
      28 |                              if (!this.authenticated) {
      29 |                                      await this.logIn();

      at AppComponent.pipe [as ngOnInit] (src/app/app.component.ts:26:5)`

And I can't move past this error - I've tried to mock the dependency several ways, but every attempt has failed to resolve the error.

Does anyone have examples of how they've successfully mocked their AppComponent tests using the v3 libraries? Or failing that, a right direction to point me in?

Cheers!

### MSAL Configuration

```javascript
{ 
auth: {
      clientId: {{ClientId}},
      authority: 'https://' + {{TenantId}} + '.b2clogin.com/' + {{TenantId}} + '.onmicrosoft.com/' + {{Policy}},
      knownAuthorities: [{{TenantId}} + '.b2clogin.com'],
      redirectUri: {{RedirectUri}},
      postLogoutRedirectUri: {{RedirectUri}},
      navigateToLoginRequestUrl: true
    },
    cache: {
      cacheLocation: 'sessionStorage',
      storeAuthStateInCookie: false,
    }
}
```

### Relevant Code Snippets

```javascript
// jest.doMock('MsalBroadcastService', () => ({
	// 	inProgress$: of({ status: InteractionStatus.None })
	// }))

	const mockMsalBroadcastService = {
		inProgress$: () => {
			return of({ status: InteractionStatus.None });
		}
	};

	// const mockMsalBroadcastService = MockService(MsalBroadcastService, {
	// 	inProgress$: of({ status: InteractionStatus.None })
	//   });

	beforeEach(waitForAsync(() => {
		TestBed.configureTestingModule({
			imports: [
				RouterTestingModule,
				AppModule
			],
			declarations: [
				AppComponent
			],
			providers: [
				MockProvider(MsalService),
				{ provide: MsalBroadcastService, useValue: mockMsalBroadcastService }
				// MockProvider(MsalBroadcastService, { inProgress$: of({ status: InteractionStatus.None }) })				
			]
		}).compileComponents();
	}));
```

### Identity Provider

Azure B2C Basic Policy

### Source

External (Customer)

**Comment by tnorling** [comment]
Jest uses jsdom to mock the Window object and jsdom does not provide Crypto APIs out of the box. You'll need to add the implementations to the global object. See our config [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/4ef12a58add1bf9d62bc30b700a80b860c340adc/shared-configs/jest-config/jest.config.cjs#L16) and the crypto setup script [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/shared-configs/jest-config/setupCrypto.cjs)

**Comment by Venators** [comment]
@tnorling thank you for your input! I'm not entirely sure if applying the crypto setup script was the sole resolving factor, but I was able to the test to pass.
