### ISSUE TITLE
Cross site redirect URL with loginPopup

### ISSUE THREAD

**Issue by robjongbloed** [AzureAD/microsoft-authentication-library-for-js#6718]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.30.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

I have a problem with using acquireTokenPopup function, from our web client. The page does some Microsoft Graph calls and starts the OneDrive picker, but it never gets to that point as acquiring the access token fails.

It _appears_ that the redirect URL must be in the same domain as the page that it is called from. However, I cannot find in the documentation where it states this requirement. Samples are useless as they all use localhost. I have everything set up correctly in the Azure app registration as it works perfectly when the redirect URL is using the _same_ host.

To be clear,  when the page being loaded from https://sub.example.com/ms-office-files.html, and the redirect URL is https://sub.example.com/ms-office-auth-redirect.html, it works. But, changing nothing else, when the redirect URL is https://main.example.com/ms-office-auth-redirect.html the popup does not close. It just displays the contents of the file, which is effectively empty:
```
<!DOCTYPE html>
<html>
    <body>
        <!-- This file is intentionally empty. -->
    </body>
</html>
```
as recommended by the FAQ.

Rest assured both https://sub.example.com/ms-office-auth-redirect.html and https://main.example.com/ms-office-auth-redirect.html are in the app registration, or I would get a much clearer error.

The two web servers `sub` and `main` are both identically configured AWS buckets with CloudFront. Doing a curl I cannot see any difference in headers or content. The _only_ difference I can see is the hostname.

### MSAL Configuration

```javascript
{
            auth: {
                authority: 'https://login.microsoftonline.com/common',
                clientId: settings.azure_client_id,
                redirectUri: `https://main.example.com/ms-office-auth-redirect.html`
            },
            system: {
                allowRedirectInIframe: true
            }
        }
```

### Relevant Code Snippets

```javascript
try {
        const response = await (accounts.length === 0
            ? msalApp.ssoSilent(authParams)
            : msalApp.acquireTokenSilent(authParams));
        return response.accessToken;
    } catch (error) {
        // fall back to popup
        console.info('ssoSilent/acquireTokenSilent failed', error);
    }

    try {
        const response = await msalApp.acquireTokenPopup(authParams);
        msalApp.setActiveAccount(response.account);
        return response.accessToken;
    } catch (error) {
        // fall back to popup
        console.info('acquireTokenPopup failed', error);
    }
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by tnorling** [comment]
Yes the redirectUri must be same domain as the caller. This is a technical limitation (as well as security/privacy related) as browsers do not allow reading the url of cross origin frames.

**Comment by robjongbloed** [comment]
Do you think you could add that to the FAQ?
