### ISSUE TITLE
Error while login with Microsoft Active directory using Reactjs

### ISSUE THREAD

**Issue by hgillh** [AzureAD/microsoft-authentication-library-for-js#6727]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.4.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.0.6

### Public or Confidential Client?

Public

### Description

I am attempting to log in with Microsoft using ReactJS with Client ID and Tenant ID. It is functioning correctly for one of my applications, but it is displaying an error for the other application.

Here is the code I am currently utilizing:

```
import {
  PublicClientApplication,
} from "@azure/msal-browser";

const msalConfig = {
  auth: {
    clientId: "bd0f7574-xxxx-xxxx-xxxx-xxxxxxx",
    authority:
      "https://login.microsoftonline.com/c6f6dd74-xxxxx-xxxx-xxxxx-xxxxxx",
    redirectUri: window.location.origin,
  },
};
const loginRequest = {
  scopes: ["openid", "profile", "User.Read"],
};

```
const msalInstance = new PublicClientApplication(msalConfig);
It's returning following error:
```
ServerError: invalid_request: 9002326 - [2023-11-03 07:35:52Z]: AADSTS9002326: Cross-origin token redemption is permitted only for the 'Single-Page Application' client-type. Request origin: 'https://www.yello-ai.com'. Trace ID: 0e3d94c4-e3f1-4cba-9eec-f46b80dd5100 Correlation ID: 13311371-6122-4e67-9ff4-54a2b5458fd8 Timestamp: 2023-11-03 07:35:52Z - Correlation ID: 13311371-6122-4e67-9ff4-54a2b5458fd8 - Trace ID: 0e3d94c4-e3f1-4cba-9eec-f46b80dd5100
```
Could you please let me know which settings need to be adjusted to resolve this issue?

### MSAL Configuration

```javascript
import {
  PublicClientApplication,
} from "@azure/msal-browser";

const msalConfig = {
  auth: {
    clientId: "bd0f7574-xxxx-xxxx-xxxx-xxxxxxx",
    authority:
      "https://login.microsoftonline.com/c6f6dd74-xxxxx-xxxx-xxxxx-xxxxxx",
    redirectUri: window.location.origin,
  },
};
const loginRequest = {
  scopes: ["openid", "profile", "User.Read"],
};
```

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
Please register your redirectUri as type "Single Page Application" in the Azure Portal. More info [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/errors.md#access-to-fetch-at-url-has-been-blocked-by-cors-policy)

**Comment by hgillh** [comment]
Hi @tnorling - I have already register my redirectUri as type "Single Page Application" in the Azure Portal. But the issue is still there.

**Comment by Chris-Max-P** [comment]
@hgillh have you solved this issue? I am facing the same problem. I configured the URL (https://localhost:1234) for SPA, but I still get the same error message.

Might it be a problem that in my case there is also the "naked" https://localhost configured for Web?

**Comment by nd50k** [comment]
> Might it be a problem that in my case there is also the "naked" https://localhost configured for Web?

Just for the sake of somebody looking into this later, yes, this might be a cause of the problem. According to [this](https://learn.microsoft.com/en-us/entra/identity-platform/reply-url#localhost-exceptions) Azure does not differentiate between ports for localhost hence both "naked" URL and the one with the port are the same. 

> Do not register multiple redirect URIs where only the port differs. The login server picks one arbitrarily and uses the behavior associated with that redirect URI (for example, whether it's a `web-`, `native-`, or `spa`-type redirect).
