### ISSUE TITLE
Will there be an official Vue 3 wrapper library like for react and angular ?

### ISSUE THREAD

**Issue by JensVanhulstSolita** [AzureAD/microsoft-authentication-library-for-js#6729]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.5

### Wrapper Library

Not Applicable

### Wrapper Library Version

none

### Public or Confidential Client?

Public

### Description

Will there be a an official VUE 3 wrapper library like for React and Angular. 

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by tnorling** [comment]
We unfortunately do not have the bandwidth to write, maintain, and support another wrapper right now. We do have a Vue3 sample [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-browser-samples/vue3-sample-app) which you can reference to integrate msal-browser into a Vue app directly.
