### ISSUE TITLE
Prompt less logout is not working for multiple accounts

### ISSUE THREAD

**Issue by rajeshbayya** [AzureAD/microsoft-authentication-library-for-js#6731]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.0.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.1

### Public or Confidential Client?

Public

### Description

When multiple accounts are logged in. while logging out from application, account selection page is appearing. 
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/27064824/5953392d-a063-414d-9fbd-33dbdab51e60)
we followed  below options for prompt less logout. Still Prompt is appearing for multiple account scenario. but for single account it is working as expected.
Option 1: Let MSAL automatically parse the login_hint out of the account's ID token claims
The first and simplest option is to provide the account object you want to end the session for to the logout API. MSAL will check to see if the login_hint claim is available in the account's ID token and automatically add it to the end session request as logout_hint to skip the account picker prompt.

**const currentAccount = msalInstance.getAccountByHomeId(homeAccountId);
// The account's ID Token must contain the login_hint optional claim to avoid the account picker
await msalInstance.logoutRedirect({ account: currentAccount});**
Option 2: Manually set the logoutHint option in the logout request
Alternatively, if you prefer to manually set the logoutHint, you can extract the login_hint claim in your app and set it as the logoutHint in the logout request:

**const currentAccount = msalInstance.getAccountByHomeId(homeAccountId);

// Extract login hint to use as logout hint
const logoutHint = currentAccount.idTokenClaims.login_hint;
await msalInstance.logoutPopup({ logoutHint: logoutHint });**
Note: Depending on the API you choose (redirect/popup), the app will still redirect or open a popup to terminate the server session. The difference is that the user will not see or have to interact with the server's account picker prompt.

### MSAL Configuration

```javascript
const currentAccount = msalInstance.getAccountByHomeId(homeAccountId);
// The account's ID Token must contain the login_hint optional claim to avoid the account picker
await msalInstance.logoutRedirect({ account: currentAccount});
Option 2: Manually set the logoutHint option in the logout request
Alternatively, if you prefer to manually set the logoutHint, you can extract the login_hint claim in your app and set it as the logoutHint in the logout request:

**const currentAccount = msalInstance.getAccountByHomeId(homeAccountId);

// Extract login hint to use as logout hint
const logoutHint = currentAccount.idTokenClaims.login_hint;
await msalInstance.logoutPopup({ logoutHint: logoutHint });**
Note: Depending on the API you choose (redirect/popup), the app will still redirect or open a popup to terminate the server session. The difference is that the user will not see or have to interact with the server's account picker prompt.
```

### Relevant Code Snippets

```javascript
const currentAccount = msalInstance.getAccountByHomeId(homeAccountId);
// The account's ID Token must contain the login_hint optional claim to avoid the account picker
await msalInstance.logoutRedirect({ account: currentAccount});
Option 2: Manually set the logoutHint option in the logout request
Alternatively, if you prefer to manually set the logoutHint, you can extract the login_hint claim in your app and set it as the logoutHint in the logout request:

**const currentAccount = msalInstance.getAccountByHomeId(homeAccountId);

// Extract login hint to use as logout hint
const logoutHint = currentAccount.idTokenClaims.login_hint;
await msalInstance.logoutPopup({ logoutHint: logoutHint });**
Note: Depending on the API you choose (redirect/popup), the app will still redirect or open a popup to terminate the server session. The difference is that the user will not see or have to interact with the server's account picker prompt.
```

### Reproduction Steps

1. Sign into two Microsoft accounts for two different applications.
2. Sign out from the one of the application.

### Expected Behavior

 Prompt should not appear for multiple account scenario.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

Internal (Microsoft)

**Comment by rajeshbayya** [comment]
@tnorling @hectormmg Please suggest on this.

**Comment by tnorling** [comment]
Please [create a ticket with the service](https://azure.microsoft.com/en-us/support/create-ticket/) - MSAL.js does not own UX behavior

**Comment by rajeshbayya** [comment]
@tnorling  this is not UX issue. It is redirection issue and should allow prompt less signout when account is provided.

**Comment by tnorling** [comment]
The redirect must always happen in order to end the session server side. It is non-negotiable. What the server does or does not render is not something that MSAL.js controls, for questions around that you should open a ticket with the service.
