### ISSUE TITLE
With msal-browser version 2.35.0 and up, we can no longer login in UI tests

### ISSUE THREAD

**Issue by IvetaKovarikova** [AzureAD/microsoft-authentication-library-for-js#6739]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

every version after 2.34.0 

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.0.7

### Public or Confidential Client?

Public, Confidential

### Description

Our application is written using msal-browser and msal-react libraries (Public Client). And we're testing the UI using Cypress with msal-node library (Confidential Client). With the newer versions of msal-browser, we have trouble logging in.

With `msal-browser 2.34.0`, everything worked fine (we got the token, put it in (session) storage and login was successful). Our solution broke when we tried to update to the latest msal-browser, but the problem is already happening when getting from 2.34.0 to 2.35.0 In the [release notes](https://github.com/AzureAD/microsoft-authentication-library-for-js/releases?q=2.35) there are some optimizations that seems to "break" the way it worked for us.

Now with the 2.35.0, I get the token and I put it the storage, but the login does not happen. What seems to happen is, that the values in storage are not read at all - I am getting the same error if I try to put the token in the storage  and if I don't do anything at all with the token and the storage is empty. Also the value of server-telemetry in session storage says cacheHits: 0.

I found out that the optimization puts some extra stuff into storage - for example the keys of storage items used for authentication (to make the lookups faster). I tried to put that extra item into the storage manually, but it did not solve the issue. I guess there are more stuff happening around the optimization that I would have to address somehow...

### Error Message

After trying to login (calling `instance.loginRedirect(loginRequest)` in the app that's being tested), I am getting this error:

`ClientAuthError: endpoints_resolution_error: Endpoints cannot be resolved`

### Msal Logs

[Fri, 01 Dec 2023 12:33:07 GMT] : [] : @azure/msal-browser@3.5.0 : Trace - BrowserCacheManager.getTemporaryCache: No cache item found in local storage
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [] : @azure/msal-browser@3.5.0 : Trace - BrowserCacheManager.getAccountKeys called
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [] : @azure/msal-browser@3.5.0 : Info - Emitting event: msal:loginStart
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [] : @azure/msal-react@2.0.7 : Info - MsalProvider - msal:loginStart results in setting inProgress from none to login
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [] : @azure/msal-browser@3.5.0 : Trace - BrowserCacheManager.getAccountKeys called
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [883e643e-808e-4f5b-b91e-2021f88fa5b9] : msal.js.browser@3.5.0 : Trace - Executing function standardInteractionClientInitializeAuthorizationRequest
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [883e643e-808e-4f5b-b91e-2021f88fa5b9] : msal.js.browser@3.5.0 : Trace - Executing function initializeBaseRequest
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [] : @azure/msal-browser@3.5.0 : Trace - BrowserCacheManager.getActiveAccount: No active account filters cache schema found, looking for legacy schema
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [] : @azure/msal-browser@3.5.0 : Trace - BrowserCacheManager.getActiveAccount: No active account found
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [883e643e-808e-4f5b-b91e-2021f88fa5b9] : msal.js.browser@3.5.0 : Trace - Returning result from initializeBaseRequest
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [] : @azure/msal-browser@3.5.0 : Trace - BrowserCacheManager.getActiveAccount: No active account filters cache schema found, looking for legacy schema
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [] : @azure/msal-browser@3.5.0 : Trace - BrowserCacheManager.getActiveAccount: No active account found
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [] : @azure/msal-browser@3.5.0 : Trace - BrowserCacheManager.getTemporaryCache: No cache item found in local storage
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [] : @azure/msal-browser@3.5.0 : Trace - BrowserCacheManager.getTemporaryCache: No cache item found in local storage
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [883e643e-808e-4f5b-b91e-2021f88fa5b9] : msal.js.browser@3.5.0 : Trace - Returning result from standardInteractionClientInitializeAuthorizationRequest
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [] : @azure/msal-browser@3.5.0 : Trace - BrowserCacheManager.updateCacheEntries called
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [883e643e-808e-4f5b-b91e-2021f88fa5b9] : msal.js.browser@3.5.0 : Trace - Executing function standardInteractionClientInitializeAuthorizationCodeRequest
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [883e643e-808e-4f5b-b91e-2021f88fa5b9] : msal.js.browser@3.5.0 : Trace - Executing function generatePkceCodes
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [883e643e-808e-4f5b-b91e-2021f88fa5b9] : msal.js.browser@3.5.0 : Trace - Executing function generateCodeVerifier
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [883e643e-808e-4f5b-b91e-2021f88fa5b9] : msal.js.browser@3.5.0 : Trace - Executing function getRandomValues
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [883e643e-808e-4f5b-b91e-2021f88fa5b9] : msal.js.browser@3.5.0 : Trace - Returning result from getRandomValues
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [883e643e-808e-4f5b-b91e-2021f88fa5b9] : msal.js.browser@3.5.0 : Trace - Returning result from generateCodeVerifier
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [883e643e-808e-4f5b-b91e-2021f88fa5b9] : msal.js.browser@3.5.0 : Trace - Executing function generateCodeChallengeFromVerifier
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [883e643e-808e-4f5b-b91e-2021f88fa5b9] : msal.js.browser@3.5.0 : Trace - Executing function sha256Digest
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [883e643e-808e-4f5b-b91e-2021f88fa5b9] : msal.js.browser@3.5.0 : Trace - Returning result from sha256Digest
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [883e643e-808e-4f5b-b91e-2021f88fa5b9] : msal.js.browser@3.5.0 : Trace - Returning result from generateCodeChallengeFromVerifier
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [883e643e-808e-4f5b-b91e-2021f88fa5b9] : msal.js.browser@3.5.0 : Trace - Returning result from generatePkceCodes
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [883e643e-808e-4f5b-b91e-2021f88fa5b9] : msal.js.browser@3.5.0 : Trace - Returning result from standardInteractionClientInitializeAuthorizationCodeRequest
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [883e643e-808e-4f5b-b91e-2021f88fa5b9] : msal.js.browser@3.5.0 : Trace - Executing function standardInteractionClientCreateAuthCodeClient
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [883e643e-808e-4f5b-b91e-2021f88fa5b9] : msal.js.browser@3.5.0 : Trace - Executing function standardInteractionClientGetClientConfiguration
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [883e643e-808e-4f5b-b91e-2021f88fa5b9] : msal.js.browser@3.5.0 : Trace - Executing function standardInteractionClientGetDiscoveredAuthority
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [883e643e-808e-4f5b-b91e-2021f88fa5b9] : msal.js.browser@3.5.0 : Trace - Executing function authorityFactoryCreateDiscoveredInstance
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [883e643e-808e-4f5b-b91e-2021f88fa5b9] : msal.js.browser@3.5.0 : Trace - Executing function authorityResolveEndpointsAsync
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [883e643e-808e-4f5b-b91e-2021f88fa5b9] : msal.js.browser@3.5.0 : Trace - Executing function authorityUpdateCloudDiscoveryMetadata
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [883e643e-808e-4f5b-b91e-2021f88fa5b9] : msal.js.browser@3.5.0 : Trace - Returning result from authorityUpdateCloudDiscoveryMetadata
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [883e643e-808e-4f5b-b91e-2021f88fa5b9] : msal.js.browser@3.5.0 : Trace - Executing function authorityUpdateEndpointMetadata
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [883e643e-808e-4f5b-b91e-2021f88fa5b9] : msal.js.browser@3.5.0 : Trace - Executing function authorityGetEndpointMetadataFromNetwork
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [883e643e-808e-4f5b-b91e-2021f88fa5b9] : msal.js.browser@3.5.0 : Trace - Returning result from authorityGetEndpointMetadataFromNetwork
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [883e643e-808e-4f5b-b91e-2021f88fa5b9] : msal.js.browser@3.5.0 : Trace - Error occurred in authorityUpdateEndpointMetadata
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [883e643e-808e-4f5b-b91e-2021f88fa5b9] : msal.js.browser@3.5.0 : Trace - {"errorCode":"openid_config_error","errorMessage":"Could not retrieve endpoints. Check your authority and verify the .well-known/openid-configuration endpoint returns the required endpoints.: https://login.microsoftonline.com/*there-is-our-tenantId*/v2.0/.well-known/openid-configuration", "subError":"","name":"ClientAuthError"}
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [883e643e-808e-4f5b-b91e-2021f88fa5b9] : msal.js.browser@3.5.0 : Trace - Error occurred in authorityResolveEndpointsAsync
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [883e643e-808e-4f5b-b91e-2021f88fa5b9] : msal.js.browser@3.5.0 : Trace - {"errorCode":"openid_config_error","errorMessage":"Could not retrieve endpoints. Check your authority and verify the .well-known/openid-configuration endpoint returns the required endpoints.: https://login.microsoftonline.com/*there-is-our-tenantId*/v2.0/.well-known/openid-configuration", "subError":"","name":"ClientAuthError"}
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [883e643e-808e-4f5b-b91e-2021f88fa5b9] : msal.js.browser@3.5.0 : Trace - Error occurred in authorityFactoryCreateDiscoveredInstance
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [883e643e-808e-4f5b-b91e-2021f88fa5b9] : msal.js.browser@3.5.0 : Trace - {"errorCode":"endpoints_resolution_error","errorMessage":"Endpoints cannot be resolved","subError":"","name":"ClientAuthError"}
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [883e643e-808e-4f5b-b91e-2021f88fa5b9] : msal.js.browser@3.5.0 : Trace - Error occurred in standardInteractionClientGetDiscoveredAuthority
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [883e643e-808e-4f5b-b91e-2021f88fa5b9] : msal.js.browser@3.5.0 : Trace - {"errorCode":"endpoints_resolution_error","errorMessage":"Endpoints cannot be resolved","subError":"","name":"ClientAuthError"}
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [883e643e-808e-4f5b-b91e-2021f88fa5b9] : msal.js.browser@3.5.0 : Trace - Error occurred in standardInteractionClientGetClientConfiguration
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [883e643e-808e-4f5b-b91e-2021f88fa5b9] : msal.js.browser@3.5.0 : Trace - {"errorCode":"endpoints_resolution_error","errorMessage":"Endpoints cannot be resolved","subError":"","name":"ClientAuthError"}
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [883e643e-808e-4f5b-b91e-2021f88fa5b9] : msal.js.browser@3.5.0 : Trace - Error occurred in standardInteractionClientCreateAuthCodeClient
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [883e643e-808e-4f5b-b91e-2021f88fa5b9] : msal.js.browser@3.5.0 : Trace - {"errorCode":"endpoints_resolution_error","errorMessage":"Endpoints cannot be resolved","subError":"","name":"ClientAuthError"}
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [] : @azure/msal-browser@3.5.0 : Trace - BrowserCacheManager.getServerTelemetry: called, no cache hit
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [] : @azure/msal-browser@3.5.0 : Trace - BrowserCacheManager.setServerTelemetry called
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [] : @azure/msal-browser@3.5.0 : Trace - BrowserCacheManager.cleanRequestByState called
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [] : @azure/msal-browser@3.5.0 : Trace - BrowserCacheManager.resetRequestCache called
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [] : @azure/msal-browser@3.5.0 : Trace - BrowserCacheManager.getTemporaryCache: Temporary cache item returned
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [] : @azure/msal-browser@3.5.0 : Info - Emitting event: msal:loginFailure
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [] : @azure/msal-react@2.0.7 : Info - MsalProvider - msal:loginFailure results in setting inProgress from login to none
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [] : @azure/msal-browser@3.5.0 : Trace - BrowserCacheManager.getAccountKeys called
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [] : @azure/msal-browser@3.5.0 : Trace - BrowserCacheManager.getActiveAccount: No active account filters cache schema found, looking for legacy schema
main.fbdf648e14971b48.js:2 [Fri, 01 Dec 2023 12:33:07 GMT] : [] : @azure/msal-browser@3.5.0 : Trace - BrowserCacheManager.getActiveAccount: No active account found
main.fbdf648e14971b48.js:2 Uncaught (in promise) ClientAuthError: endpoints_resolution_error: Endpoints cannot be resolved
    at a (main.fbdf648e14971b48.js:2:240084)
    at AuthorityFactory.createDiscoveredInstance (main.fbdf648e14971b48.js:2:60693)
    at async RedirectClient.getDiscoveredAuthority (main.fbdf648e14971b48.js:2:89917)
    at async RedirectClient.getClientConfiguration (main.fbdf648e14971b48.js:2:88418)
    at async RedirectClient.createAuthCodeClient (main.fbdf648e14971b48.js:2:88035)
    at async RedirectClient.acquireToken (main.fbdf648e14971b48.js:2:130594)

### MSAL Configuration

```javascript
//MSAL configuration in the React app we're testing:

 auth: {
     clientId: clientId,
     authority: `https://login.microsoftonline.com/${authorityId}`,
     navigateToLoginRequestUrl: true,
}
```

### Relevant Code Snippets

```javascript
//The test is inspired by this sample (https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-browser-samples/TestingSample/test/browser-test.spec.ts)
// only we use the ConfidentialClientApplication class from "@azure/msal-node" (v2.5.1):


  const config: Configuration = {
        auth: {
            clientId: Cypress.env().azure.clientId,
            authority: Cypress.env().azure.login + Cypress.env().azure.tenantId,
            clientSecret: Cypress.env().azure.clientSecret
        }
    }
 
    const instance = new ConfidentialClientApplication(config)
    const usernamePasswordRequest = {
        scopes: [`${Cypress.env().azure.clientId}/.default`],
        username: Cypress.env().azure.username,
        password: Cypress.env().azure.password,
    }
    instance.acquireTokenByUsernamePassword(usernamePasswordRequest).then(() => {
        const token = instance.getTokenCache().getKVStore()
        setSessionStorage(tokenCache)
    }
```

### Expected Behavior

I would like to be able to log in to our app through a test somehow. Actually I am not sure If the approach we're using is correct. It seems like using the token and storing it in storage **was** fine before. Is it still a way to go?

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Regression

@azure/msal-browser 2.34.0

### Source

External (Customer)

**Comment by hectormmg** [comment]
@IvetaKovarikova msal-browser does not have a `ConfidentialClientApplication` class, that would be MSAL Node. Can you please verify your usage information and update your issue?

**Comment by IvetaKovarikova** [comment]
Sorry for confusion, I updated the issue.

The app uses msal-browser and the test msal-node (v2.5.1).

**Comment by hectormmg** [comment]
@IvetaKovarikova can you show the msal-browser code as well?

**Comment by IvetaKovarikova** [comment]
Sure, this is the minimal code on the UI side with msal-browser:
With 2.34.0 I am getting through to the Authenticated template (after clicking the button to log me in), with 2.35.0 and up not anymore.
```
const msalConfig = {
    auth: {
        clientId: clientId,
        authority: `https://login.microsoftonline.com/${tenantId}`,
        navigateToLoginRequestUrl: true,
    },
};

const loginRequest = msalConfig && {
    scopes: [`${msalConfig.auth.clientId}/.default`],
};

export function Wrapper(): React.ReactElement {
    const instance = new PublicClientApplication(msalConfig);

    instance.addEventCallback((event) => {
        if (event.eventType === EventType.LOGIN_SUCCESS && event.payload) {
            const payload = event.payload as AuthenticationResult;
            const account = payload.account;
            instance.setActiveAccount(account);
        }
    });

    const handleRedirect = () => {
        instance.loginRedirect(loginRequest);
    };

    return (
        <MsalProvider instance={instance}>
            <AuthenticatedTemplate>
                <div>Authenticated</div>
            </AuthenticatedTemplate>
            <UnauthenticatedTemplate>
                <div>Unauthenticated</div>
                <button onClick={handleRedirect}>Login</button>
            </UnauthenticatedTemplate>
        </MsalProvider>
    );
}
```

**Comment by tnorling** [comment]
Can you try using the [loadExternalTokens API](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/testing.md) instead of hydrating sessionStorage manually?

**Comment by IvetaKovarikova** [comment]
Sorry, I don't uderstand how to use the _loadExternalTokens API_ in our scenario. Can you explain further what do you mean?

I am testing in Cypress, using msal-node, creating ConflidentitalClientAplication instance, so the _loadExternalTokens API_  is not available for me.
From the docs:
> The loadExternalTokens() API can be accessed by calling getTokenCache() on MSAL Browser's PublicClientApplication instance.

**Comment by tnorling** [comment]
1. Use msal-node to acquire tokens using PublicClientApplication (recommend the UsernamePassword flow for this)
2. Open your SPA app with your test framework
3. Inject a script into the window that initializes msal-browser PublicClientApplication then invokes the loadExternalTokens API with results from step 1
4. Run your tests

**Comment by IvetaKovarikova** [comment]
I was trying to go by the steps you provided, but there is a problem in the first step. If I try to use PublicClientApplication to get the token, I am getting this error:

`ServerError: invalid_client: 7000218 - [2023-12-18 08:07:39Z]: AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.`

Although, I cannot pass the `client_secret`  with  PublicClientApplication instance.

I found that this error is related to the azure application authentication settings -  that we have to enable the option "Allow public client flow". Did I understand that correctly?

**Comment by tnorling** [comment]
Yes, you will need to allow public client flows
