### ISSUE TITLE
isAuthenticated based on cached account instead of valid access token

### ISSUE THREAD

**Issue by sebasptsch** [AzureAD/microsoft-authentication-library-for-js#6741]
### Core Library

MSAL.js (@azure/msal-browser)

### Wrapper Library

MSAL React (@azure/msal-react)

### Public or Confidential Client?

Public

### Description

isAuthenticated is based on a cached user account, not the presence of a valid access token? Is this expected behavior. If a user is unable to obtain a new access token but the profile is still cached then authenticated content is still visible to the user using `AuthenticatedTemplate` even if they don't have a valid access token to fetch the data for those _theoretically_ obscured views. The same goes for useIsAuthenticated etc.

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
Yes this is expected behavior. Using something like useMsalAuthentication or MsalAuthenticationTemplate might get you closer to the behavior you're looking for
