### ISSUE TITLE
AADB2C90077 error when using SsoSilent in Firefox, not in Chrome

### ISSUE THREAD

**Issue by LennartMart** [AzureAD/microsoft-authentication-library-for-js#6742]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

latest

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.9

### Public or Confidential Client?

Public

### Description

When doing an SsoSilent call in Firefox, we're getting `InteractionRequiredAuthError: interaction_required: AADB2C90077: User does not have an existing session and request prompt parameter has a value of 'None'`.
When running the same code in Chrome, everything works as expected.

### MSAL Configuration

```javascript
export function msalConfigFactory(configurationService: ConfigurationService): IPublicClientApplication {
    return new PublicClientApplication({
        auth: {
            clientId: configurationService.configuration.azureAuthenticationClientId,
            authority: configurationService.configuration.azureAuthenticationAuthority,
            redirectUri: window.location.origin,
            knownAuthorities: [configurationService.configuration.azureAuthenticationAuthority],
            postLogoutRedirectUri: window.location.origin,
        },
        cache: {
            cacheLocation: BrowserCacheLocation.LocalStorage,
        },
        system: {
            loggerOptions: {
                loggerCallback(logLevel: LogLevel, message: string) {
                    console.log(message);
                },
                logLevel: LogLevel.Warning,
                piiLoggingEnabled: false
            }
        }
    });
}
```

### Relevant Code Snippets

```javascript
In app.component.ts (in constructor):

        this.msalService.initialize().subscribe(() => {
            this.msalBroadcastService.msalSubject$
                .pipe(
                    first((value) =>
                        value.eventType === EventType.LOGIN_SUCCESS ||
                        value.eventType === EventType.ACQUIRE_TOKEN_SUCCESS ||
                        value.eventType === EventType.SSO_SILENT_SUCCESS)
                )
                .subscribe((result: EventMessage) => {
                    this.globalEventsService.setIsAuthenticated(true);
                    this.authorize();
                });

            this.msalService.ssoSilent({
                scopes: [this.configurationService.configuration.azureAuthenticationScope, "openid"]
            }).subscribe({
                next: (result: AuthenticationResult) => {
                    console.log("sso succeeded!");
                },
                error: (error) => {
                    console.log(error);
                    // uncomment if we automatically want to navigate to login page if not authenticated yet
                    // this.login();
                }
            });

        });
```

### Reproduction Steps

1. Instantiate PublicClientApplication with Factory method
2. Initialize msalService and subscribe
3. Perform SsoSilent in this subscribe event
4. Firefox: error. In Chrome: Success

### Expected Behavior

I expect to have the same behavior in every browser.

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Firefox

### Regression

@azure/msal-angular 2.5.2

### Source

External (Customer)

**Comment by tnorling** [comment]
The 2 main reasons this might fail with the error mentioned:

1. 3P cookies are blocked (this is becoming the default in browsers, Safari and Firefox are ahead of Chrome here)
2. You don't actually have a session yet

Unfortunately there's nothing we (MSAL.js) can do to address either of these scenarios. You should catch interaction required errors and invoke an interactive API, popup or redirect, to continue.
