### ISSUE TITLE
Unclear Documentation/Expectations Regarding useMsalAuthentication

### ISSUE THREAD

**Issue by wwkimball** [AzureAD/microsoft-authentication-library-for-js#6743]
### Core Library

MSAL.js (@azure/msal-browser)

### Wrapper Library

MSAL React (@azure/msal-react)

### Public or Confidential Client?

Public

### Documentation Location

https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/blob/main/3-Authorization-II/1-call-api/SPA/src/hooks/useFetchWithMsal.jsx

### Description

I'll start by suggesting the delineation between AzureAD/microsoft-authentication-library-for-js and Azure-Samples/ms-identity-javascript-react-tutorial is fuzzy; they appear to be inexorably intertwined.  Since the later uses hooks from the former and this is a matter of uncertainty with a hook, the issue at hand leans more into AzureAD/microsoft-authentication-library-for-js rather than Azure-Samples/ms-identity-javascript-react-tutorial, so here I write.

Azure-Samples/ms-identity-javascript-react-tutorial provides a helper hook named [`useFetchWithMsal.jsx`](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/blob/main/3-Authorization-II/1-call-api/SPA/src/hooks/useFetchWithMsal.jsx).  The presumption is that its use of `useMsalAuthentication` will automatically invoke a login event should the user's session be missing/invalid/expired/etc.  However, that isn't the case.  Rather, the hook merely dumps an error about 'invalid_client' when the session expires after one hour.

In fairness, I understand from the documentation that user sessions are expected to expire after one hour and can be refreshed up to 24 hours.  The confusion is in the expectation formed by the documentation surrounding `useMsalAuthentication` in light of this.

The in-code documentation for `useMsalAuthentication` states plainly that "If a user is not currently signed in this hook invokes a login. Failed logins can be retried using the login callback returned. *If a user is currently signed in this hook attempts to acquire a token.* Subsequent token requests can use the acquireToken callback returned. Optionally provide a request object to be used in the login/acquireToken call. Optionally provide a specific user that should be logged in." (emphasis mine).

To a novice, this looks like `useMsalAuthentication`, and therefore its `useFetchWithMsal` wrapper, is adequate to keep a user session alive for API queries after login with no further additional code from the application developer.  This is unfortunately not the case because after just one hour, all uses of `useFetchWithMsal` fail.

Is `useMsalAuthentication` meant to keep a user session alive following a valid login?  If not, this isn't clear.

To be clear, my Next-React-Node (SPA + separate API) application is working very well based on the Azure-Samples' TodoList example.  However, my users are getting kicked out after just one hour with non-obvious messaging.  I experimented with adding `acquireTokenSilent` to `useFetchWithMsal` before `useMsalAuthentication` but that solves nothing and actually makes React throw a warning on every call about modifying the DOM during a render.

I can't suss out from the documentation here at AzureAD/microsoft-authentication-library-for-js or there at Azure-Samples/ms-identity-javascript-react-tutorial how I'm supposed to keep the user logged in longer than one hour.  I don't mind forcing the user to log in fresh each workday, but every hour is disruptive.  I've read a great deal of the documentation but something is missing that would point me toward how to keep the user login session alive for longer than one hour if, in fact, `useMsalAuthentication` is not meant to fill this likely obvious need.

Please offer some guidance specifically for how to keep user login sessions alive beyond one hour if `useMsalAuthentication` is not responsible for this chore.  I cannot offer a PR given that I do not know the solution to this issue.

**Comment by tnorling** [comment]
> Rather, the hook merely dumps an error about 'invalid_client' when the session expires after one hour.

This is unexpected and is what's causing this to not work as you expect. Something is misconfigured either in the sample/your app or on the app registration or both. The useMsalAuthentication hook _should be_ capable of getting you a token for at least 24 hours.

We'll need more information to better understand why you're seeing this behavior - Can you please share: 
1. The full error message
2. Whether you're using AAD or B2C
3. correlationId + timestamp
4. The versions of both msal-browser and msal-react you're using

**Comment by wwkimball** [comment]
I'm grateful that you're interested in my plight!  I do hope this issue turns out to be merely a misconfiguration on my part, though I'll be surprised given that I built this application from the bones of the sample application.

I have written considerable code based on posts at StackExchange from other people trying to solve the same issue (keep user sessions alive beyond one hour) and as such, have buried that original error under myriad handlers which attempt to nicely kick the user out of the application rather than dumping the invalid_client message all over the screen (every component which fetches data was showing it; the result was a mess).  Let me revert my code back a couple of weeks to try to grab that original error.  It'll take me quite some time since I need to find that code point and then reproduce the error, which will take at least another hour after log-in.

While this isn't the error you'd like to see, the following is the error I get today (having buried invalid_client).  I will reproduce the original error and add it to this thread once I have it.  I hope this (still not working) version of the error may be in some way informative while I reproduce the original error.

<details>
  <summary>POST https://login.microsoftonline.com/9033bafc-94e3-4dec-87b5-4418b697e42c/oauth2/v2.0/token 400 (Bad Request)</summary>

```text
Mon, 04 Dec 2023 22:20:53 GMT] : [] : [@azure/msal-common@14.4.0](mailto:@azure/msal-common@14.4.0) : Info - CacheManager:getIdToken - Returning id token 

authConfig.js:40 [Mon, 04 Dec 2023 22:20:53 GMT] : [] : [@azure/msal-common@14.4.0](mailto:@azure/msal-common@14.4.0) : Info - CacheManager:getIdToken - Returning id token 

authConfig.js:40 [Mon, 04 Dec 2023 22:20:53 GMT] : [] : [@azure/msal-common@14.4.0](mailto:@azure/msal-common@14.4.0) : Info - CacheManager:getIdToken - Returning id token 

authConfig.js:40 [Mon, 04 Dec 2023 22:20:53 GMT] : [] : [@azure/msal-common@14.4.0](mailto:@azure/msal-common@14.4.0) : Info - CacheManager:getIdToken - Returning id token 

authConfig.js:40 [Mon, 04 Dec 2023 22:20:53 GMT] : [] : [@azure/msal-common@14.4.0](mailto:@azure/msal-common@14.4.0) : Info - CacheManager:getIdToken - Returning id token 

WelcomeUser.js:35 WelcomeUser::PeriodicallyRefreshToken:  MSAL token refresh timer is already set in the API user context. 

authConfig.js:40 [Mon, 04 Dec 2023 22:20:53 GMT] : [] : [@azure/msal-common@14.4.0](mailto:@azure/msal-common@14.4.0) : Info - CacheManager:getIdToken - Returning id token 

authConfig.js:40 [Mon, 04 Dec 2023 22:20:53 GMT] : [] : [@azure/msal-react@2.0.7](mailto:@azure/msal-react@2.0.7) : Info - useMsalAuthentication - User is authenticated, attempting to acquire token 

authConfig.js:40 [Mon, 04 Dec 2023 22:20:53 GMT] : [] : @azure/msal-browser@3.5.0 : Info - Emitting event: msal:acquireTokenStart 


PartOrders:  No response from the API (useFetchWithMsal failed to properly await). 

console.error @ client.js:1 

window.console.error @ setup-hydration-warning.js:18 

overrideMethod @ console.js:213 

eval @ [status].js:47 

Promise.then (async) 

eval @ [status].js:45 

commitHookEffectListMount @ react-dom.development.js:23150 

commitPassiveMountOnFiber @ react-dom.development.js:24926 

commitPassiveMountEffects_complete @ react-dom.development.js:24891 

commitPassiveMountEffects_begin @ react-dom.development.js:24878 

commitPassiveMountEffects @ react-dom.development.js:24866 

flushPassiveEffectsImpl @ react-dom.development.js:27039 

flushPassiveEffects @ react-dom.development.js:26984 

performSyncWorkOnRoot @ react-dom.development.js:26076 

flushSyncCallbacks @ react-dom.development.js:12042 

commitRootImpl @ react-dom.development.js:26959 

commitRoot @ react-dom.development.js:26682 

finishConcurrentRender @ react-dom.development.js:25981 

performConcurrentWorkOnRoot @ react-dom.development.js:25809 

workLoop @ scheduler.development.js:266 

flushWork @ scheduler.development.js:239 

performWorkUntilDeadline @ scheduler.development.js:533 

Show 1 more frame 

Show less 

authConfig.js:40 [Mon, 04 Dec 2023 22:20:53 GMT] : [] : [@azure/msal-common@14.4.0](mailto:@azure/msal-common@14.4.0) : Info - CacheManager:getIdToken - Returning id token 

authConfig.js:40 [Mon, 04 Dec 2023 22:20:53 GMT] : [] : [@azure/msal-common@14.4.0](mailto:@azure/msal-common@14.4.0) : Info - CacheManager:getAccessToken - Returning access token 

authConfig.js:40 [Mon, 04 Dec 2023 22:20:53 GMT] : [] : [@azure/msal-common@14.4.0](mailto:@azure/msal-common@14.4.0) : Info - CacheManager:getRefreshToken - returning refresh token 

authConfig.js:40 [Mon, 04 Dec 2023 22:20:53 GMT] : [bb76430e-490a-4028-9ada-f04dc693c73b] : [@azure/msal-common@14.4.0](mailto:@azure/msal-common@14.4.0) : Info - Token refresh is required due to cache outcome: 3 

authConfig.js:40 [Mon, 04 Dec 2023 22:20:53 GMT] : [] : [@azure/msal-browser@3.5.0](mailto:@azure/msal-browser@3.5.0) : Info - Emitting event: msal:acquireTokenFromNetworkStart 

authConfig.js:40 [Mon, 04 Dec 2023 22:20:53 GMT] : [] : [@azure/msal-common@14.4.0](mailto:@azure/msal-common@14.4.0) : Info - CacheManager:getRefreshToken - returning refresh token 

2authConfig.js:40 [Mon, 04 Dec 2023 22:20:53 GMT] : [] : [@azure/msal-common@14.4.0](mailto:@azure/msal-common@14.4.0) : Info - CacheManager:getIdToken - Returning id token 

FetchClient.mjs:59  

POST https://login.microsoftonline.com/9033bafc-94e3-4dec-87b5-4418b697e42c/oauth2/v2.0/token 400 (Bad Request) 

sendPostRequestAsync @ FetchClient.mjs:59 

sendPostRequest @ NetworkManager.mjs:28 

executePostToTokenEndpoint @ BaseClient.mjs:79 

eval @ FunctionWrappers.mjs:64 

executeTokenRequest @ RefreshTokenClient.mjs:133 

await in executeTokenRequest (async) 

eval @ FunctionWrappers.mjs:64 

acquireToken @ RefreshTokenClient.mjs:39 

eval @ FunctionWrappers.mjs:64 

acquireTokenWithCachedRefreshToken @ RefreshTokenClient.mjs:108 

eval @ FunctionWrappers.mjs:64 

acquireTokenByRefreshToken @ RefreshTokenClient.mjs:85 

eval @ FunctionWrappers.mjs:64 

acquireToken @ SilentRefreshClient.mjs:28 

await in acquireToken (async) 

eval @ FunctionWrappers.mjs:64 

acquireTokenByRefreshToken @ StandardController.mjs:633 

eval @ FunctionWrappers.mjs:64 

eval @ StandardController.mjs:1268 

Promise.catch (async) 

acquireTokenSilentAsync @ StandardController.mjs:1260 

await in acquireTokenSilentAsync (async) 

eval @ FunctionWrappers.mjs:64 

acquireTokenSilent @ StandardController.mjs:1183 

acquireTokenSilent @ PublicClientApplication.mjs:87 

getToken @ useMsalAuthentication.js:103 

eval @ useMsalAuthentication.js:118 

eval @ useMsalAuthentication.js:180 

commitHookEffectListMount @ react-dom.development.js:23150 

commitPassiveMountOnFiber @ react-dom.development.js:24926 

commitPassiveMountEffects_complete @ react-dom.development.js:24891 

commitPassiveMountEffects_begin @ react-dom.development.js:24878 

commitPassiveMountEffects @ react-dom.development.js:24866 

flushPassiveEffectsImpl @ react-dom.development.js:27039 

flushPassiveEffects @ react-dom.development.js:26984 

performSyncWorkOnRoot @ react-dom.development.js:26076 

flushSyncCallbacks @ react-dom.development.js:12042 

commitRootImpl @ react-dom.development.js:26959 

commitRoot @ react-dom.development.js:26682 

finishConcurrentRender @ react-dom.development.js:25981 

performConcurrentWorkOnRoot @ react-dom.development.js:25809 

workLoop @ scheduler.development.js:266 

flushWork @ scheduler.development.js:239 

performWorkUntilDeadline @ scheduler.development.js:533 

authConfig.js:40 [Mon, 04 Dec 2023 22:20:53 GMT] : [] : [@azure/msal-browser@3.5.0](mailto:@azure/msal-browser@3.5.0) : Info - Emitting event: msal:acquireTokenFailure 

authConfig.js:40 [Mon, 04 Dec 2023 22:20:53 GMT] : [] : [@azure/msal-common@14.4.0](mailto:@azure/msal-common@14.4.0) : Info - CacheManager:getIdToken - Returning id token 

2authConfig.js:40 [Mon, 04 Dec 2023 22:20:53 GMT] : [] : @azure/msal-common@14.4.0 : Info - CacheManager:getIdToken - Returning id token
```
</details>

Interesting Takeaways:

1. I have my own log comments in the code trying to rationalize what is happening.  I often see in the log that useFetchWithMsal seems to exit before CacheManager ever returns a token.  It feels like a missing `await` but my best efforts to add it everywhere reasonable (in useFetchWithMsal) fail to change this behavior (race condition?).  This always causes `execute` to return twice; once without any data and the second time with data (as long as the user session is less than an hour old).  Hence my guess in the log of, "useFetchWithMsal failed to properly await" (presumably for the token).
2. I've disabled React's StrictMode due to #5468, so the "always returns twice from useFetchWithMsal" behavior issue is presumably not due to that incompatibility.  That said, I can't help but wonder whether the race condition (not waiting for the id token on the first pass) still is...
3. You'll see in the log that the code is reporting that my refresh timer has already been set.  To wit, I have attempted to create a timer which calls `acquireTokenSilent` within 5 minutes of session expiry.  While the combination of that plus other code which attempts to detect the invalid_client error does bury the invalid_client error, it also fails to prolong the life of the login session.  The result is that whatever page the user attempts to navigate to after the one hour mark gets stuck with all of the API-dependent components "Loading...".

I don't mean to drag this thread down into the details my non-working attempt at a solution.  I'm simply sharing that I have made considerable effort to solve this on my own before reporting on the confusion.

As for the other information you specifically asked for, I have the following:

1. Full error message:  I will have this to you within the week; I'm out of time today and my next 3 workdays will be hectic.
4. I believe this is AAD.  I based the SPA upon the ["Node/Express API with Next/React SPA" example](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/tree/main/3-Authorization-II/1-call-api/SPA).
5. I'll have to try to find correlationId + timestamp when I regenerate the original invalid_client error.  I'm not entirely sure how to obtain those but I will try.
6. Versions:
    1. @azure/msal-browser@3.5.0
    2. @azure/msal-react@2.0.7

TMI:  This is a very small SPA, so if there's anything informative in it, here's my very short `npm list` output:

```text
├── @azure/msal-browser@3.5.0
├── @azure/msal-react@2.0.7
├── @headlessui/react@1.7.17
├── @heroicons/react@2.0.18
├── autoprefixer@10.4.16
├── classnames@2.3.2
├── eslint-config-next@14.0.2
├── eslint@8.53.0
├── next-themes@0.2.1
├── next@14.0.2
├── postcss@8.4.31
├── react-dom@18.2.0
├── react@18.2.0
└── tailwindcss@3.3.5
```

**Comment by tnorling** [comment]
If it's easier you can email me a network trace which should include everything I need. If you choose to do that, however, I would highly recommend sanitizing it first though to remove any active tokens or auth artifacts. You can use a tool such as [this one](https://har-sanitizer.pages.dev/) to do that.

**Comment by wwkimball** [comment]
I stayed late to try to grab a copy of the original invalid_client error.  I only hope this isn't a tainted result[^1] because the user session was open before I `git checkout [SHA]d` the code.  While I did revert the code and did generate the invalid_client error, it was via an already-open-and-aging user session.

Should it be useful anyway, here is the full text of the error:

<details>
  <summary>ServerError: invalid_client: 500116 - [2023-12-04 23:38:57Z]: AADSTS500116: The reply uri specified in the request is not a valid URL. Allowed schemes: '*'. Trace ID: 08723285-c857-4cba-8e03-8c6c0bb01000 Correlation ID: 89bd9116-f889-4a47-a58b-8964fa3b5dff Timestamp: 2023-12-04 23:38:57Z - Correlation ID: 89bd9116-f889-4a47-a58b-8964fa3b5dff - Trace ID: 08723285-c857-4cba-8e03-8c6c0bb01000</summary>

```text
client.js:1  WelcomeUser:  IdentifyPassportUser() error:  ServerError: invalid_client: 500116 - [2023-12-04 23:38:57Z]: AADSTS500116: The reply uri specified in the request is not a valid URL. Allowed schemes: '*'. Trace ID: 08723285-c857-4cba-8e03-8c6c0bb01000 Correlation ID: 89bd9116-f889-4a47-a58b-8964fa3b5dff Timestamp: 2023-12-04 23:38:57Z - Correlation ID: 89bd9116-f889-4a47-a58b-8964fa3b5dff - Trace ID: 08723285-c857-4cba-8e03-8c6c0bb01000
    at ResponseHandler.validateTokenResponse (ResponseHandler.mjs:87:1)
    at RefreshTokenClient.acquireToken (RefreshTokenClient.mjs:43:1) 
    at IdentifyPassportUser (webpack-internal:///./src/components/navigation/WelcomeUser.js:22:11)
    at p
    at MsalAuthenticationTemplate (webpack-internal:///./node_modules/@azure/msal-react/dist/components/MsalAuthenticationTemplate.js:28:39)
    at WelcomeUser (webpack-internal:///./src/components/navigation/WelcomeUser.js:93:84)
    at AuthenticatedTemplate (webpack-internal:///./node_modules/@azure/msal-react/dist/components/AuthenticatedTemplate.js:26:34)
    at div
    at footer
    at MainFooter
    at div
    at div
    at div
    at f (webpack-internal:///./node_modules/next-themes/dist/index.module.js:8:597)
    at $ (webpack-internal:///./node_modules/next-themes/dist/index.module.js:8:348)
    at MsalProvider (webpack-internal:///./node_modules/@azure/msal-react/dist/MsalProvider.js:84:25)
    at App (webpack-internal:///./src/pages/_app.js:28:11)
    at PathnameContextProviderAdapter (webpack-internal:///./node_modules/next/dist/shared/lib/router/adapters.js:79:11)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:2:5391)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:2:7787)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:79:1)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:183:11)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:397:11)
console.error @ client.js:1
window.console.error @ setup-hydration-warning.js:18
overrideMethod @ console.js:213
IdentifyPassportUser @ WelcomeUser.js:48
renderWithHooks @ react-dom.development.js:16305
updateFunctionComponent @ react-dom.development.js:19588
beginWork @ react-dom.development.js:21601
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 1 more frame
Show less
```
</details>

From this, I see the answers to your questions as:

1. correlationId:  89bd9116-f889-4a47-a58b-8964fa3b5dff
2. timestamp:  2023-12-04 23:38:57Z

[^1]:  I have no reason to believe it would be tainted.  I haven't changed the authentication code (based on the sample, in the /authConfig.js file) since the first time it worked.  Git history on the file confirms there have been no changes to it since I started troubleshooting this invalid_client issue.

**Comment by wwkimball** [comment]
> If it's easier you can email me a network trace which should include everything I need. If you choose to do that, however, I would highly recommend sanitizing it first though to remove any active tokens or auth artifacts. You can use a tool such as [this one](https://har-sanitizer.pages.dev/) to do that.

I'm happy to send you any information you'd like to see.  I believe I have so far captured everything you've asked for in this thread.  If you'd like more than is appropriate in a public site and/or you prefer e-mail to GitHub comments, please let me know; I'm happy to switch communication mediums at your preference.

**Comment by tnorling** [comment]
Ah, this is due to a bug (#6733) introduced in version 3.2.0 related to relative redirectUri's. Until this is fixed you have 2 options to resolve:

1. Set your redirectUri value to an absolute URL (e.g. `window.origin` instead of `"/"`)
2. Downgrade to version 3.1.0

**Comment by wwkimball** [comment]
I'm sorry I was away from code for a couple of days for other work.  I attempted option 1 by commenting out line 17 of [authConfig.js from the AzureAD sample](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/blob/main/3-Authorization-II/1-call-api/SPA/src/authConfig.js#L17) and save.  My assumption was that doing so would cause the `redirectUri` to default to `window.location.origin` as per the documentation on that line.

At first, I thought we were onto something.  I saw my browser automatically refresh (Next.js running `npm run dev` in a Docker container with the application files mapped to my local filesystem for live edits) and rather than getting kicked out, I saw the page simply pick up with a shockingly still-valid login session.  This was in itself extraordinary because my user session was already over 48 hours old.

However, at the one hour mark, the session collapsed anyway with another `invalid_client` error:

<details>
  <summary>client.js:1  PartOrders:  error:  ServerError: invalid_client: 500116 - [2023-12-07 15:58:02Z]: AADSTS500116: The reply uri specified in the request is not a valid URL. Allowed schemes: '*'. Trace ID: 91c1a0c6-94a0-4517-9dee-fb3f14901c00 Correlation ID: dd5e963b-a34e-4623-bc11-3f1359d787c8 Timestamp: 2023-12-07 15:58:02Z - Correlation ID: dd5e963b-a34e-4623-bc11-3f1359d787c8 - Trace ID: 91c1a0c6-94a0-4517-9dee-fb3f14901c00</summary>

```text
    at ResponseHandler.validateTokenResponse (ResponseHandler.mjs:87:1)
    at RefreshTokenClient.acquireToken (RefreshTokenClient.mjs:43:1)
console.error @ client.js:1
```
</details>

Because there is an unknown (to me) with the user session already having been very old (48+ hours), I'm running another test with a fresh user session.  I'll report back after the one hour mark.

**Comment by wwkimball** [comment]
My mistake; I failed to notice that `useFetchWithMsal` is also hard-coding the `redirectUri` [on line 23](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/blob/main/3-Authorization-II/1-call-api/SPA/src/hooks/useFetchWithMsal.jsx#L23).

I discovered this after the present one-hour test failed, producing another invalid_client error.  In giving benefit of the doubt regarding your option 1, I searched all code for any remaining hard-coded `redirectUri` settings and discovered the above setting.  I should have done this before assuming `authConfig.js` was the only place it was likely to be set.

Of note and changing nothing else -- including leaving my browser displaying the invalid_client error -- I merely commented out the offending line in `useFetchWithMsal` directly affecting `useMsalAuthentication` and suddenly, my application sprang back to life.

For a clean test, I will log out and back in anyway to run a fresh one hour test again.

**Comment by wwkimball** [comment]
I'm very happy to report that the first option indeed appears to have solved this issue; `useMsalAuthentication` (incidentally wrapped in `useFetchWithMsal`) *is behaving as expected*.

For anyone facing this issue while running [The MSAL-based AzureAD SPA Sample](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/tree/main/3-Authorization-II/1-call-api/SPA) or an application derived from it, the solution -- until #6733 is fixed -- is to comment out settings of `redirectUri` in the sample code.  At the time of this writing, these occur at:

1. [authConfig.js, line 17](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/blob/main/3-Authorization-II/1-call-api/SPA/src/authConfig.js#L17)
2. [useFetchWithMsal.jsx, line 23](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/blob/main/3-Authorization-II/1-call-api/SPA/src/hooks/useFetchWithMsal.jsx#L23)

Doing so allows the library and affected hooks to automatically set redirectUri to `window.location.origin`.  This works as long as you've registered that address in M365 Admin > Applications > App registrations > (Your SPA) > Authentication > Platform configurations > Single-page application > Redirect URIs.

As for this ticket, I'm not sure how to proceed.  You'd stated this is due to a bug that has been around from version 3.1.0 to now version 3.5.0.  The bug appears to break `useMsalAuthentication` away from the expected behavior when used in a Microsoft-prescribed way with recommended code (`useFetchWithMsal`) using recommended configuration (from the AzureAD sample code).  

That said, **thank you so much**, @tnorling!

**Comment by tnorling** [comment]
Great thanks for the update! Closing this and we'll use #6733 to track - note the fix is currently in PR
