### ISSUE TITLE
How to refresh automatically the token? using the version 3 of the library in angular

### ISSUE THREAD

**Issue by OspinaJuan2000** [AzureAD/microsoft-authentication-library-for-js#6745]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.0.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

None

### Public or Confidential Client?

Confidential

### Description

Hello, i need to know how to automatically refresh the token of the user. Cause i'm getting the following error:

{"error":"invalid_grant","error_description":"AADSTS700084: The refresh token was issued to a single page app (SPA), and therefore has a fixed, limited lifetime of 1.00:00:00, which cannot be extended. It is now expired and a new sign in request must be sent by the SPA to the sign in page. The token was issued on 2023-10-23T22:46:25.5670528Z. Trace ID: 7c3a6a4b-055f-4204-8e93-d9abb16b0100 Correlation ID: 51b5b8a8-fb77-432f-b498-1e5f9653e58e Timestamp: 2023-12-04 19:46:39Z","error_codes":[700084],"timestamp":"2023-12-04 19:46:39Z","trace_id":"7c3a6a4b-055f-4204-8e93-d9abb16b0100","correlation_id":"51b5b8a8-fb77-432f-b498-1e5f9653e58e","error_uri":"[https://login.microsoftonline.com/error?code=700084","suberror":"bad_token"}](https://login.microsoftonline.com/error?code=700084%22,%22suberror%22:%22bad_token%22%7D)

### MSAL Configuration

```javascript
auth: {
      clientId: environment.microsoft.azureConfig.clientId,
      authority: environment.microsoft.azureConfig.authority,
      redirectUri: '/',
      postLogoutRedirectUri: '/'
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage
    },
    system: {
      allowNativeBroker: false, // Disables WAM Broker
    }
```

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by hectormmg** [comment]
@OspinaJuan2000 how is acquireTokenSilent being called? Are you using the Interceptor?

**Comment by OspinaJuan2000** [comment]
> @OspinaJuan2000 how is acquireTokenSilent being called? Are you using the Interceptor?

I'm not using the acquireTokenSilent method, this is mi app.module.ts config complete:

```
import { registerLocaleData } from '@angular/common';
import { HTTP_INTERCEPTORS, HttpClientModule } from '@angular/common/http';
import myLocaleEs from '@angular/common/locales/es';
import { NgModule } from '@angular/core';

import { BrowserModule } from '@angular/platform-browser';
import { MSAL_GUARD_CONFIG, MSAL_INSTANCE, MSAL_INTERCEPTOR_CONFIG, MsalBroadcastService, MsalGuard, MsalGuardConfiguration, MsalInterceptor, MsalInterceptorConfiguration, MsalModule, MsalRedirectComponent, MsalService } from '@azure/msal-angular';
import { BrowserCacheLocation, IPublicClientApplication, InteractionType, PublicClientApplication } from '@azure/msal-browser';
import { environment } from 'src/environments/environment';

import { BcIconModule } from '@bancolombia/design-system-web/bc-icon';
import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { AuthenticationGateway } from './domain/models/authentication/gateway/authentication.gateway';
import { AuthenticationUseCase } from './domain/usecases/authentication/authentication.usecase';
import { MsalAdapter } from './infrastructure/adapters/msal-adapter/msal.adapter';
import { ProfileUseCase } from './domain/usecases/profile/profile.usecase';
import { ProfileGateway } from './domain/models/profile/gateway/profile.gateway';
import { ProfileHttpClient } from './infrastructure/adapters/httpclient-adapter/profile/profile-http-client.adapter';

registerLocaleData(myLocaleEs);

export function MSALInstanceFactory(): IPublicClientApplication {
  return new PublicClientApplication({
    auth: {
      clientId: environment.microsoft.azureConfig.clientId,
      authority: environment.microsoft.azureConfig.authority,
      redirectUri: '/',
      postLogoutRedirectUri: '/'
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage
    },
    system: {
      allowNativeBroker: false, // Disables WAM Broker
    }
  });
}

export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
  const protectedResourceMap = new Map<string, Array<string>>();
  protectedResourceMap.set(environment.microsoft.apisConfig.profileUrl, environment.microsoft.apisConfig.scopes);

  return {
    interactionType: InteractionType.Redirect,
    protectedResourceMap
  };
}

export function MSALGuardConfigFactory(): MsalGuardConfiguration {
  return {
    interactionType: InteractionType.Redirect,
    authRequest: {
      scopes: [...environment.microsoft.apisConfig.scopes]
    }
  };
}

@NgModule({
  declarations: [
    AppComponent,
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    HttpClientModule,
    BcIconModule.forRoot({ path: 'https://library-sdb.apps.bancolombia.com/bds/2.1.10' }),
    MsalModule
  ],
  providers: [
    {
      provide: HTTP_INTERCEPTORS,
      useClass: MsalInterceptor,
      multi: true
    },
    {
      provide: MSAL_INSTANCE,
      useFactory: MSALInstanceFactory
    },
    {
      provide: MSAL_GUARD_CONFIG,
      useFactory: MSALGuardConfigFactory
    },
    {
      provide: MSAL_INTERCEPTOR_CONFIG,
      useFactory: MSALInterceptorConfigFactory
    },
    MsalService,
    MsalGuard,
    MsalBroadcastService,
    AuthenticationUseCase,
    ProfileUseCase,
    {
      provide: AuthenticationGateway, useClass: MsalAdapter
    },
    {
      provide: ProfileGateway, useClass: ProfileHttpClient
    }
  ],
  bootstrap: [AppComponent, MsalRedirectComponent]
})
export class AppModule { }
```

**Comment by OspinaJuan2000** [comment]
I need to know how to implement the refresh token automatically or if i need to call a method for that, cause i'm getting the error:

`{"error":"invalid_grant","error_description":"AADSTS700084: The refresh token was issued to a single page app (SPA), and therefore has a fixed, limited lifetime of 1.00:00:00, which cannot be extended. It is now expired and a new sign in request must be sent by the SPA to the sign in page. The token was issued on 2023-10-23T22:46:25.5670528Z. Trace ID: 7c3a6a4b-055f-4204-8e93-d9abb16b0100 Correlation ID: 51b5b8a8-fb77-432f-b498-1e5f9653e58e Timestamp: 2023-12-04 19:46:39Z","error_codes":[700084],"timestamp":"2023-12-04 19:46:39Z","trace_id":"7c3a6a4b-055f-4204-8e93-d9abb16b0100","correlation_id":"51b5b8a8-fb77-432f-b498-1e5f9653e58e","error_uri":"[https://login.microsoftonline.com/error?code=700084","suberror":"bad_token"}](https://login.microsoftonline.com/error?code=700084%22,%22suberror%22:%22bad_token%22%7D)`

**Comment by hectormmg** [comment]
@OspinaJuan2000 even if you see the error, the Interceptor should still be handling the silent refresh. Are you sure the tokens aren't being refreshed silently after this error?

**Comment by OspinaJuan2000** [comment]
@hectormmg yes i'm sure because the Page goes blank and in the "network" tab appears the error.

**Comment by tnorling** [comment]
This is an internal error that is caught and handled by MSAL. Can you please determine what error is actually being thrown by MSAL?

**Comment by Ospina2k** [comment]
Hello, the error happened again in local environment (it usually happens in DEV)

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/153514548/6dba7bc4-e2b1-4c18-b69e-2e2ee51241d4)

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/153514548/b85ef28c-792b-451a-9d90-9163a0b9c509)

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/153514548/7f4c8cf4-7bda-4986-9290-b1e0efaf0d20)

**Comment by Ospina2k** [comment]
I reload the page and page goes blank.

Again, app.module.ts

```import { registerLocaleData } from '@angular/common';
import { HTTP_INTERCEPTORS, HttpClientModule } from '@angular/common/http';
import myLocaleEs from '@angular/common/locales/es';
import { NgModule } from '@angular/core';

import { BrowserModule } from '@angular/platform-browser';
import { MSAL_GUARD_CONFIG, MSAL_INSTANCE, MSAL_INTERCEPTOR_CONFIG, MsalBroadcastService, MsalGuard, MsalGuardConfiguration, MsalInterceptor, MsalInterceptorConfiguration, MsalModule, MsalRedirectComponent, MsalService } from '@azure/msal-angular';
import { BrowserCacheLocation, IPublicClientApplication, InteractionType, PublicClientApplication } from '@azure/msal-browser';
import { environment } from 'src/environments/environment';

import { BcIconModule } from '@bancolombia/design-system-web/bc-icon';
import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { AuthenticationGateway } from './domain/models/authentication/gateway/authentication.gateway';
import { AuthenticationUseCase } from './domain/usecases/authentication/authentication.usecase';
import { MsalAdapter } from './infrastructure/adapters/msal-adapter/msal.adapter';
import { ProfileUseCase } from './domain/usecases/profile/profile.usecase';
import { ProfileGateway } from './domain/models/profile/gateway/profile.gateway';
import { ProfileHttpClient } from './infrastructure/adapters/httpclient-adapter/profile/profile-http-client.adapter';

registerLocaleData(myLocaleEs);

export function MSALInstanceFactory(): IPublicClientApplication {
  return new PublicClientApplication({
    auth: {
      clientId: environment.microsoft.azureConfig.clientId,
      authority: environment.microsoft.azureConfig.authority,
      redirectUri: '/',
      postLogoutRedirectUri: '/'
    },
    cache: {
      cacheLocation: BrowserCacheLocation.LocalStorage
    },
    system: {
      allowNativeBroker: false, // Disables WAM Broker
    }
  });
}

export function MSALInterceptorConfigFactory(): MsalInterceptorConfiguration {
  const protectedResourceMap = new Map<string, Array<string>>();
  protectedResourceMap.set(environment.microsoft.apisConfig.profileUrl, environment.microsoft.apisConfig.scopes);

  return {
    interactionType: InteractionType.Redirect,
    protectedResourceMap
  };
}

export function MSALGuardConfigFactory(): MsalGuardConfiguration {
  return {
    interactionType: InteractionType.Redirect,
    authRequest: {
      scopes: [...environment.microsoft.apisConfig.scopes]
    }
  };
}

@NgModule({
  declarations: [
    AppComponent,
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    HttpClientModule,
    BcIconModule.forRoot({ path: 'https://library-sdb.apps.bancolombia.com/bds/2.1.10' }),
    MsalModule
  ],
  providers: [
    {
      provide: HTTP_INTERCEPTORS,
      useClass: MsalInterceptor,
      multi: true
    },
    {
      provide: MSAL_INSTANCE,
      useFactory: MSALInstanceFactory
    },
    {
      provide: MSAL_GUARD_CONFIG,
      useFactory: MSALGuardConfigFactory
    },
    {
      provide: MSAL_INTERCEPTOR_CONFIG,
      useFactory: MSALInterceptorConfigFactory
    },
    MsalService,
    MsalGuard,
    MsalBroadcastService,
    AuthenticationUseCase,
    ProfileUseCase,
    {
      provide: AuthenticationGateway, useClass: MsalAdapter
    },
    {
      provide: ProfileGateway, useClass: ProfileHttpClient
    }
  ],
  bootstrap: [AppComponent, MsalRedirectComponent]
})
export class AppModule { }
```

**Comment by Ospina2k** [comment]
The error disappear when I delete the data on Local Storage

**Comment by Ospina2k** [comment]
To keep in mind, I never logged out, I was always logged in since yesterday, today I logged in again and the error occurred. It seems that the library does not clear the local storage after the credentials expire, or something like that.

**Comment by tnorling** [comment]
Again, this is an expected error that is caught and handled internally by MSAL. You will see it in the developer tools but that error is not thrown by the MSAL APIs and is not an indication of a problem. You need to figure out what error is actually thrown by MSAL to determine why this is breaking.

**Comment by amanvermaa** [comment]
You need to include this in app.component.ts file.

` ngOnInit(): void {
    this.isIframe = window !== window.parent && !window.opener; // Remove this line to use Angular Universal`

Also in the app.component.html

`    <router-outlet *ngIf="!isIframe"></router-outlet>
`

**Comment by Ospina2k** [comment]
> You need to include this in app.component.ts file.
> 
> ` ngOnInit(): void { this.isIframe = window !== window.parent && !window.opener; // Remove this line to use Angular Universal`
> 
> Also in the app.component.html
> 
> ` <router-outlet *ngIf="!isIframe"></router-outlet>`

Hello, what will that code do?

**Comment by Ospina2k** [comment]
> You need to include this in app.component.ts file.
> 
> ` ngOnInit(): void { this.isIframe = window !== window.parent && !window.opener; // Remove this line to use Angular Universal`
> 
> Also in the app.component.html
> 
> ` <router-outlet *ngIf="!isIframe"></router-outlet>`

Hi, it does not change anything, same 400 http error...
