### ISSUE TITLE
400 bad request - Request Header or cookies is too large

### ISSUE THREAD

**Issue by mohdmujahithali** [AzureAD/microsoft-authentication-library-for-js#6752]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.38.3

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.5.12

### Public or Confidential Client?

Confidential

### Description

While trying to login in my react app through MSAL authentication, "request header or cookie too large" 400 error thrown.

### Error Message

In browser 1,
400 Bad Request - Request Header or Cookie Too Long. nginx. 

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/106740250/996a7f14-f240-4ed2-a157-7418392227ed)

In browser 2,
Bad Request - Request Too Long. HTTP Error 400. The size of the request headers is too long.

<img width="305" alt="image" src="https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/106740250/a1058c90-4be8-4934-bd8f-382e933917fb">

### MSAL Configuration

```javascript
const msalConfig: Configuration = {
  auth: {
    clientId: env.B2C_CLIENT_ID,
    authority: b2cPolicies.authorities.signUpSignIn.authority,
    knownAuthorities: [b2cPolicies.authorityDomain, `${env.B2C_TENANT_NAME}.b2clogin.com`],
    redirectUri: env.REDIRECT_URI,
    postLogoutRedirectUri: env.POST_LOGOUT_REDIRECT_URI,
    navigateToLoginRequestUrl: false,
  },
  cache: {
    cacheLocation: 'sessionStorage',
  },
};
```

### Relevant Code Snippets

```javascript
import { useMsal } from '@azure/msal-react';
import { IPublicClientApplication, RedirectRequest } from '@azure/msal-browser';

const env = {
  "API_DOMAIN": "https://api-zh.int.dev.com/asmatx",
  "B2C_AAD_AUTH_CLIENT_ID": "fdf4d7b-4hg3-1jk5-bccf-7f00752e75956",
  "B2C_CLIENT_ID": "455474fe-d1aa-3b32-a22b-b55832074412",
  "B2C_TENANT_NAME": "vertexb2c",
  "B2C_SIGNUP_SIGNIN_POLICY_NAME": "B2C_SIGNUP_SIGNIN_OKTA",
  "MULTITENANT_API_URL": "https://api-zh.int.dev.com/rbac",
  "INSTANCE_NAME": "ca",
  "POST_LOGOUT_REDIRECT_URI": "https://zh.int.dev.com/",
};

const b2cPolicies = {
  names: {
    signUpSignIn: env.B2C_SIGNUP_SIGNIN_POLICY_NAME,
  },
  authorities: {
    signUpSignIn: {
      authority: `https://${env.B2C_TENANT_NAME}.b2clogin.com/${env.B2C_TENANT_NAME}.onmicrosoft.com/${env.B2C_SIGNUP_SIGNIN_POLICY_NAME}`,
    },
  },
  authorityDomain: `${env.B2C_TENANT_NAME}.onmicrosoft.com`,
};


const msalConfig: Configuration = {
  auth: {
    clientId: env.B2C_CLIENT_ID,
    authority: b2cPolicies.authorities.signUpSignIn.authority,
    knownAuthorities: [b2cPolicies.authorityDomain, `${env.B2C_TENANT_NAME}.b2clogin.com`],
    redirectUri: env.REDIRECT_URI,
    postLogoutRedirectUri: env.POST_LOGOUT_REDIRECT_URI,
    navigateToLoginRequestUrl: false,
  },
  cache: {
    cacheLocation: 'sessionStorage',
  },
};

const getDomainHint = (email: string) => {
    return new RegExp('@(.*)').exec(email)![1];
    };

const loginRequest: RedirectRequest = {
    scopes: ['openid', 'profile'],
    };

const handleLogin = async (
    instance: IPublicClientApplication,
    userInput: string,
    ): Promise<void> => {
    const domainHint = getDomainHint(userInput);
    
    const request: RedirectRequest = {
        ...loginRequest,
        ...{
        extraQueryParameters: {
            domain_hint: domainHint,
        },
        loginHint: userInput,
        },
    };
    
    await instance.loginRedirect(request);
    };

const handleOnClick = async (event: any) => {
    event.preventDefault();
    try {
        await handleLogin(instance, emailInput);
    } catch (error: any) {
        history.push(CommonRoutes.InternalServerError);
    } finally {
        props.setLoading(false);
    }
};

<Button
	type="submit"
	onClick={handleOnClick}
	disabled={props.loading}
>
	{props.loading ? 'Loading...' : 'Sign In'}
</Button>
```

### Reproduction Steps

1) launch the react app
2) enter the valid email credentials
3) click sign-in button

its redirecting to authentication page to get password. at that time, 400 error thrown

**In browser 1**,
400 Bad Request - Request Header or Cookie Too Long. nginx. 

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/106740250/252b057d-42e7-4126-be3f-bf553a50055c)

**In browser 2**,
Bad Request - Request Too Long. HTTP Error 400. The size of the request headers is too long.

<img width="305" alt="image" src="https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/106740250/8683dc92-339a-4907-86b4-2442162dbf4f">

**Note**:
1) This issue occurs only when the specific browser having large number of cookies & others site data stored.
2) Login works fine if using “incognito window” or clear the cookies.
3) While this 400 error occurs in any browser, then at the same time https://${env.B2C_TENANT_NAME}.b2clogin.com/ also thrown 400 error

### Expected Behavior

Even any browser having any larger number of cookies stored, MSAL authentication should get works fine without any 400 error for all major browser.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge

### Source

External (Customer)

**Comment by tnorling** [comment]
> This issue occurs only when the specific browser having large number of cookies & others site data stored.

This is the problem. Cookies are sent on every request and browsers impose limits on the size of network requests. This has nothing to do with MSAL. You should reduce the number of cookies and the size of their values you store on your site to address this.

**Comment by BrandanDoesCode** [comment]
> > This issue occurs only when the specific browser having large number of cookies & others site data stored.
> 
> This is the problem. Cookies are sent on every request and browsers impose limits on the size of network requests. This has nothing to do with MSAL. You should reduce the number of cookies and the size of their values you store on your site to address this.

This issue is definitely related to MSAL.

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/107240494/39c7dd09-47ce-4a56-b534-0e4eb4bfc102)

I am able to sucessfully login but am faced with the same request error if I logout and log back in multiple times.

This issue is currently blocking the release of our product as it is not reasonable to expect our clients have to clear their cookies when faced with this issue.

Are you able to suggest any fixes?

I am currently facing the same issue, current package versions.
        "@azure/msal-browser": "^3.7.1",
        "@azure/msal-react": "^2.0.10",


And using the following configuration:


`"import { type Configuration, type PopupRequest } from '@azure/msal-browser'


**MSALCONFIG**
// Config object to be passed to Msal on creation
export const msalConfig: Configuration = {
    auth: {
        clientId: String(process.env.REACT_APP_AZURE_AD_B2C_CLIENT_ID),
        authority: String(process.env.REACT_APP_AZURE_AD_B2C_AUTHORITY),
        knownAuthorities: [String(process.env.REACT_APP_AZURE_AD_B2C_KNOWN_AUTHORITY)],
        redirectUri:
        String(process.env.REACT_APP_REDIRECT_URI) + "/",
        postLogoutRedirectUri: '/',
  },
    cache: {
        cacheLocation: 'sessionStorage', // Configures cache location. "sessionStorage" is more secure, but "localStorage" gives you SSO between tabs.
        storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge,
        cacheMigrationEnabled: false,
        secureCookies: true
  },
    system: {
        allowNativeBroker: false // Disables WAM Broker,
    }
}

// Add here scopes for id token to be used at MS Identity Platform endpoints.
export const loginRequest: PopupRequest = {
    scopes: [
    'openid', 'offline_access',
    String(process.env.REACT_APP_AZURE_AD_B2C_CLIENT_ID),
  ]

}

// Add here the endpoints for MS Graph API services you would like to use.
export const graphConfig = {
    graphMeEndpoint: String(process.env.REACT_APP_AZURE_GRAPH_ENDPOINT),
}
"`

**INSTANTIATION OF msalINstance according to @azure/msal-browser v3**
import React from 'react'
import ReactDOM from 'react-dom/client'
import { BrowserRouter as Router } from 'react-router-dom'
import { ThemeProvider } from '@mui/material/styles'
import { theme } from './styles/theme'
import App from './App'

// MSAL imports
import { PublicClientApplication, EventType, type EventMessage, type AuthenticationResult } from '@azure/msal-browser'
import { msalConfig } from './authConfig'

export const msalInstance = new PublicClientApplication(msalConfig)

msalInstance.initialize().then(() => {
    // Account selection logic is app dependent. Adjust as needed for different use cases.
    const accounts = msalInstance.getAllAccounts();
    if (accounts.length > 0) {
        msalInstance.setActiveAccount(accounts[0]);
    }

    console.log("COOKIE TEST");
    console.log(document.cookie);
    let cookies = document.cookie.split(';');
    for (let i = 0; i < cookies.length; i++) {
        let cookie = cookies[i];
        console.log(cookie);

    }

    msalInstance.addEventCallback((event: EventMessage) => {
        if (event.eventType === EventType.LOGIN_SUCCESS && event.payload) {
            const payload = event.payload as AuthenticationResult;
            const account = payload.account;
            msalInstance.setActiveAccount(account);
        }
    });

    const root = ReactDOM.createRoot(
        document.getElementById("root") as HTMLElement
    );
    document.getElementById('body')?.setAttribute('style', 'margin: 0px;')

    root.render(
        <Router>
            <ThemeProvider theme={theme}>
                <App pca={msalInstance} />
            </ThemeProvider>
        </Router>
    );
});

**Comment by Viltersten** [comment]
Has this issue been resolved (or at least addressed somehow)? We have 3 users who get this kind of weird errors and several who don't. Can the cookie size created by the MSAL package be restricted somehow?

**Comment by mordyort** [comment]
Im getting this issue as well on newer tenants using the graph API, so nothing to do with browsers, and this issue only presents itself on specific endpoints, for example https://graph.microsoft.com/v1.0/reports/authenticationMethods/userRegistrationDetails one i get the error however, when using the same token and header and calling https://graph.microsoft.com/beta/riskDetections it works I've seen this with multiple API's some throw the error and others don't i do have a app that has a lot of permission on it so the JWT is a bit large but what else am i supposed to do

**Comment by pshegde** [comment]
The cookies keep accumulating even after setting storeAuthStateInCookie: false, please let us know if there is any fix?
