### ISSUE TITLE
msal-react: MsalProvider throws exception if app launched via insecure URL

### ISSUE THREAD

**Issue by MGraefe** [AzureAD/microsoft-authentication-library-for-js#6758]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.6.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.0.8

### Public or Confidential Client?

Public

### Description

If I launch my app via an insecure URL, e.g. `http://192.168.0.2:3000`, the `MsalProvider` throws an unhandled exception, which causes react to not render all child JSX nodes (which usually is the whole application). The application works totally fine and authenticates correctly if I launch it via a 'trusted' URL, for example `https://example.com` or `http://localhost:3000`.

I'm not expecting authentication to work when the app is launched via an insecure URL, but I am expecting MsalProvider to not crash my whole application.

Browser: Edge 120.

This is likely caused by Msal trying to use the `window.crypto.randomUUID` function, which is only available in a secure Browser context. The problem is immediately reproducible by opening the react-router-sample via an unsafe URL (e.g. from a different machine using `http://`)

### Error Message

```
Uncaught TypeError: window.crypto.randomUUID is not a function
    at createNewGuid (BrowserCrypto.ts:87:1)
    at EventHandler.addEventCallback (EventHandler.ts:44:1)
    at StandardController.addEventCallback (StandardController.ts:1684:1)
    at PublicClientApplication.addEventCallback (PublicClientApplication.ts:149:1)
    at MsalProvider.tsx:143:1
    at commitHookEffectListMount (react-dom.development.js:23150:1)
    at commitPassiveMountOnFiber (react-dom.development.js:24926:1)
    at commitPassiveMountEffects_complete (react-dom.development.js:24891:1)
    at commitPassiveMountEffects_begin (react-dom.development.js:24878:1)
    at commitPassiveMountEffects (react-dom.development.js:24866:1)
react-dom.development.js:18687  The above error occurred in the <MsalProvider> component:

    at MsalProvider (http://172.28.74.175:3000/static/js/bundle.js:447590:3)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:18687
Show 1 more frame
Show less
```

### MSAL Configuration

```javascript
{
  "auth": {
    "clientId": "xxxxx",
    "authority": "https://login.microsoftonline.com/xxxxx",
    "redirectUri": "http://172.28.74.175:3000"
  },
  "cache": {
    "cacheLocation": "sessionStorage",
    "storeAuthStateInCookie": false
  }
}
```

### Relevant Code Snippets

```javascript
Just use react-router-sample
```

### Reproduction Steps

1. Build `msal-react-samples/react-router-sample`
2. `npm start`
3. Visit the app via the `On Your Network` URL given here: 
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/8102494/2d6d5523-282f-4717-a8d6-7de6a5a05cd3)

### Expected Behavior

Authentication fails, but app still renders

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Edge

### Source

External (Customer)

**Comment by tnorling** [comment]
Our libraries do not support http contexts. If you have a requirement to run your application in http without auth I would suggest conditionally rendering the MSAL components when in a supported context.

**Comment by MGraefe** [comment]
That's what I'm currently doing @tnorling. But don't you really think, that using the library in a http context shouldn't result in a somewhat cryptic exception thrown by crypto.randomUUID not existing? Even worse if the exception prevents rendering of everything wrapped inside `MsalProvider`.

I understand that you don't support this use-case, but I would at least expect a proper error message when the context is initialized inside an unsafe context. Ideally MsalProvider would also just behave as a no-op in that case.
