### ISSUE TITLE
Are there any breaking API changes between msal-node 1.x and 2.x ?

### ISSUE THREAD

**Issue by elovin** [AzureAD/microsoft-authentication-library-for-js#6759]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

1.18.4

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

There is no migration guide for msal-node for upgrading from 1.x to 2.x 
although the npm page says this:
> There have been no functional changes in the MSAL Node v2 release.

Does that mean that there are no breaking API changes between 1.x and 2.x and that it is safe to just upgrade the dependency ?

### Identity Provider

None

### Source

External (Customer)

**Comment by tnorling** [comment]
There are no breaking API changes between v1 and v2 of msal-node. The only breaking change is that support for Node versions < 16 has been dropped.
