### ISSUE TITLE
PublicClientApplication won't instantiate - 'crypto interface unavailable' - Android / NativeScript

### ISSUE THREAD

**Issue by rjattrill** [AzureAD/microsoft-authentication-library-for-js#6768]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.6.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

NA

### Public or Confidential Client?

Public

### Description

Attempt to instantiate `PublicClientApplication` on Android with NativeScript.   The instantiation blocks and never throws an error.   Trace logging shows a problem with BrowserCrypto:

      [Wed, 13 Dec 2023 07:16:47 GMT] : [] : @azure/msal-browser@3.6.0 : Error - BrowserCrypto: crypto interface is unavailable

### MSAL Configuration

```javascript
const msalConfig = {
            auth: {
                clientId: '3d105853-8db7-4c6f-9212-221891b7b8b9',
                authority: 'https://login.microsoftonline.com/00e34f38-d2a9-485a-be9a-05177574232d'
            },
            system: {
                loggerOptions: {
                    logLevel: LogLevel.Trace,
            ...
```

### Relevant Code Snippets

```javascript
console.log("Initiating MSAL")
        const msalConfig = {
            auth: {
                clientId: '3d105853-8db7-4c6f-9212-221891b7b8b9',
                authority: 'https://login.microsoftonline.com/00e34f38-d2a9-485a-be9a-05177574232d'
            },
            system: {
                loggerOptions: {
                    logLevel: LogLevel.Trace,

                    ...

        }
        const msalInstance = new PublicClientApplication(msalConfig)
        console.log("Never gets here...")


----
Output from Trace:
Initiating MSAL
  [Wed, 13 Dec 2023 07:16:47 GMT] : [] : @azure/msal-browser@3.6.0 : Error - BrowserCrypto: crypto interface is unavailable
```

### Identity Provider

Azure B2C Basic Policy

### Source

External (Customer)

**Comment by tnorling** [comment]
The Crypto APIs are required to use this library. Additionally, we don't officially support non-browser environments. You may need to include polyfills for the crypto APIs if they're not available.

**Comment by rjattrill** [comment]
Thanks for your response Thomas.  Looks like using MSAL.js in this environment isn't the go.
