### ISSUE TITLE
Is there a way to disable the msal authentication while working in local environment?

### ISSUE THREAD

**Issue by JalilEvoke** [AzureAD/microsoft-authentication-library-for-js#6774]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.0.0-alpha.2

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

We were working on implementing SSO by using MSAL in one of our angular applications and we have few queries to you as mentioned below

1. There are couple of files which were modified to implement SSO mainly like app module, app component and some additional files. Whenever we do local development work, we just want to skip the authentication. Is there a simple way to achieve this? 
2. As of now we are commenting the files wherever the MSAL is used which is little time consuming for a new developer so want to check with you if there is a simple way like a configuration change on/off which upon disabling it should disable the authentication process and directly launch the application
Your response to this is highly appreciated.

Thanks,
Jalil

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by tnorling** [comment]
Msal does not proactively do anything so there are no controls for this. You, as the application developer, are in control of how and when authentication is performed so conditionally rendering/invoking authentication related things based on whether you're in development or in production would be business logic you can build for your specific use case.
