### ISSUE TITLE
Getting: ClientAuthError: endpoints_resolution_error: Endpoints cannot be resolved with @azure/msal-node@2.6.0

### ISSUE THREAD

**Issue by atif-parvez** [AzureAD/microsoft-authentication-library-for-js#6776]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

2.6.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Confidential

### Description

Core Library
MSAL Node (@azure/msal-node)

Core Library Version
2.6.0

OS
Oracle Linux Server 8.8
Kernel version: 4.18.0-477.27.0.1.el8_8.x86_64

Container-Runtime : containerd://1.6.24

Description
We have developed a node application for authenticating Azure OIDC that is running on-premises on **Kubernetes version 1.27.7**
 On application login page when we click on singin button instead of getting MS login page we are getting 'Endpoints cannot be resolved error'

### Error Message

@azure/msal-node@2.6.0 : Info - getAuthCodeUrl called
msalInstance stacktrace:: ClientAuthError: endpoints_resolution_error: Endpoints cannot be resolved
    at createClientAuthError (/app/node_modules/@azure/msal-common/dist/index.cjs:721:12)
    at AuthorityFactory.createDiscoveredInstance (/app/node_modules/@azure/msal-common/dist/index.cjs:6497:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConfidentialClientApplication.buildOauthClientConfiguration (/app/node_modules/@azure/msal-node/dist/client/ClientApplication.cjs:230:37)
    at async ConfidentialClientApplication.getAuthCodeUrl (/app/node_modules/@azure/msal-node/dist/client/ClientApplication.cjs:51:34)
    at async redirectToAuthCodeUrl (/app/routes/index.js:47:37)
msalInstance error message:: endpoints_resolution_error: Endpoints cannot be resolved

### Msal Logs

@azure/msal-node@2.6.0 : Info - getAuthCodeUrl called
msalInstance stacktrace:: ClientAuthError: endpoints_resolution_error: Endpoints cannot be resolved
    at createClientAuthError (/app/node_modules/@azure/msal-common/dist/index.cjs:721:12)
    at AuthorityFactory.createDiscoveredInstance (/app/node_modules/@azure/msal-common/dist/index.cjs:6497:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConfidentialClientApplication.buildOauthClientConfiguration (/app/node_modules/@azure/msal-node/dist/client/ClientApplication.cjs:230:37)
    at async ConfidentialClientApplication.getAuthCodeUrl (/app/node_modules/@azure/msal-node/dist/client/ClientApplication.cjs:51:34)
    at async redirectToAuthCodeUrl (/app/routes/index.js:47:37)
msalInstance error message:: endpoints_resolution_error: Endpoints cannot be resolved

### MSAL Configuration

```javascript
const msalConfig = {
    auth: {
        clientId: process.env.CLIENT_ID,
        authority: process.env.CLOUD_INSTANCE + process.env.TENANT_ID,
        clientSecret: process.env.CLIENT_SECRET
    },
    system: {
        loggerOptions: {
            loggerCallback(loglevel, message, containsPii) {
                console.log(message);
            },
            piiLoggingEnabled: false,
            logLevel: "Info",
        }
    }
}
```

### Relevant Code Snippets

```javascript
try {
        const authCodeUrlResponse = await msalInstance.getAuthCodeUrl(req.session.authCodeUrlRequest);      
        res.redirect(authCodeUrlResponse);
    } catch (error) {
        next(error);
}
```

### Reproduction Steps

I'm not totally sure how to describe this

### Expected Behavior

There should be no error and the process should continue to work. Redirect to MS login page when clicking on signin button

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Source

External (Customer)

**Comment by tnorling** [comment]
Try setting your logLevel to verbose and setting piiLoggingEnabled to true. That should output the url it's trying and failing to reach

**Comment by atif-parvez** [comment]
After setting logLevel to verbose and setting piiLoggingEnabled to true we are getting below logs:


@azure/msal-node@2.6.0 : Info - getAuthCodeUrl called
msalInstance stacktrace:: ClientAuthError: endpoints_resolution_error: Endpoints cannot be resolved

    at createClientAuthError (/app/node_modules/@azure/msal-common/dist/index.cjs:721:12)

    at AuthorityFactory.createDiscoveredInstance (/app/node_modules/@azure/msal-common/dist/index.cjs:6497:19)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async ConfidentialClientApplication.buildOauthClientConfiguration (/app/node_modules/@azure/msal-node/dist/client/ClientApplication.cjs:230:37)

    at async ConfidentialClientApplication.getAuthCodeUrl (/app/node_modules/@azure/msal-node/dist/client/ClientApplication.cjs:51:34)

    at async redirectToAuthCodeUrl (/app/routes/index.js:47:37)

msalInstance error message:: endpoints_resolution_error: Endpoints cannot be resolved

GET / - - ms - -


at /app/routes/index.js:47:37 we have below line of code:
const authCodeUrlResponse = await msalInstance.getAuthCodeUrl(req.session.authCodeUrlRequest);

**Comment by hectormmg** [comment]
@atif-parvez please double check that the result of concatenating process.env.CLOUD_INSTANCE + process.env.TENANT_ID, results in a valid authority and that adding /v2.0/.well-known/openid-configuration to that authority actually takes you to the openid-config successfully.

**Comment by atif-parvez** [comment]
We have implmented below methods and we are getting 400 error 

const [cloudDiscoveryMetadata, authorityMetadata] = await Promise.all([
            getCloudDiscoveryMetadata(msalConfig.auth.authority),
            getAuthorityMetadata(msalConfig.auth.authority)
        ]);
		
async function getCloudDiscoveryMetadata(authority) {
    const endpoint = 'https://login.microsoftonline.com/common/discovery/instance';

    try {
        console.log("getCloudDiscoveryMetadata endpoint authority: ", authority);
        const response = await axios.get(endpoint, {
            params: {
                'api-version': '1.1',
                'authorization_endpoint': `${authority}/oauth2/v2.0/authorize`
            }
        });
        return await response.data;
    } catch (error) {
        throw error;
    }
}		

async function getCloudDiscoveryMetadata(authority) {
    const endpoint = 'https://login.microsoftonline.com/common/discovery/instance';

    try {
        const response = await axios.get(endpoint, {
            params: {
                'api-version': '1.1',
                'authorization_endpoint': `${authority}/oauth2/v2.0/authorize`
            }
        });
        return await response.data;
    } catch (error) {
        throw error;
    }
}

Below are the error details:

 adapter: [ 'xhr', 'http' ],

  transformRequest: [ [Function: transformRequest] ],

  transformResponse: [ [Function: transformResponse] ],

  timeout: 0,

  xsrfCookieName: 'XSRF-TOKEN',

  xsrfHeaderName: 'X-XSRF-TOKEN',

  maxContentLength: -1,

  maxBodyLength: -1,

  env: {

    FormData: [Function: FormData] {

      LINE_BREAK: '\r\n',

      DEFAULT_CONTENT_TYPE: 'application/octet-stream'

    },

    Blob: [class Blob]

  },

  validateStatus: [Function: validateStatus],

  headers: Object [AxiosHeaders] {

    Accept: 'application/json, text/plain, */*',

    'Content-Type': undefined,

    'User-Agent': 'axios/1.6.2',

    'Accept-Encoding': 'gzip, compress, deflate, br'

  },

  params: {

    'api-version': '1.1',

    authorization_endpoint: 'https://login.microsoftonline.com/removed-tenant-id-here/oauth2/v2.0/authorize'

  },

  method: 'get',

  url: 'https://login.microsoftonline.com/common/discovery/instance',

msalInstance stacktrace:: AxiosError: Request failed with status code 400

    at settle (/app/node_modules/axios/dist/node/axios.cjs:1967:12)

    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/dist/node/axios.cjs:3062:11)

    at IncomingMessage.emit (node:events:523:35)

    at endReadableNT (node:internal/streams/readable:1367:12)

    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

msalInstance error message:: Request failed with status code 400

  data: undefined

}

**Comment by hectormmg** [comment]
@atif-parvez MSAL already does cloud metadata discovery, you don't need to re-implement those methods. Let's focus on the error MSAL is giving you (endpoint resolution error). Can you please confirm that your authority value is correct? If the authority is malformed then endpoints cannot be resolved.

**Comment by atif-parvez** [comment]
@hectormmg We have confirmed authority value is correct. Same code when we use in local machine and on AWS it works fine but when we try it on on-premises behind proxy it's not working.

**Comment by tnorling** [comment]
If it's working locally and on AWS but not behind a proxy that indicates an issue with your proxy. That's not something we're going to be able to help you troubleshoot unfortunately. That said, you might try upgrading to 2.6.2 which fixed a bug related to resolving hardcoded metadata and should result in not attempting to get the metadata from the network all.

**Comment by manjeet13** [comment]
@atif-parvez Hey just checking if you were able to solve this issue somehow? We are facing the same problems in our ADFS setup in an on-premise installation. Although our setup was working well for a year, it stopped working all of a sudden one day. I have tried switching between a few version but to no avail yet.

**Comment by atif-parvez** [comment]
Hi @manjeet13 - yes, I was able to solve the issue using below package

https://www.npmjs.com/package/node-global-proxy

Use the config object example code provided in the above URL. I did that and it worked fine for me. Proxy was not working that was the issue for my case.

**Comment by manjeet13** [comment]
@atif-parvez thanks for the response, appreciate it!
Just one more from me, so you mean in your case, actual authority URL was different from the proxy url?
