### ISSUE TITLE
msalInstance.loginPopup() - promise is getting rejected if the page is redirecting to other domain inside the popup.

### ISSUE THREAD

**Issue by dawood-rf-97** [AzureAD/microsoft-authentication-library-for-js#6777]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Core Library Version

1.4.17

### Wrapper Library

Not Applicable

### Wrapper Library Version

NA

### Public or Confidential Client?

Public

### Description

Currently, the issue is related to loginPopup.
We've added the MS login flow in our SPA using `msal@1.4.17` . We're using `loginPopup()` method to get authentication code. And we're using `UserAgentApplication` class from `msal`. (Implicit flow)

In login pop-up window, the user entered valid credentials to log in his/her Microsoft account. The page is redirected to `sso.godaddy.com`, since it's a organisational account. 

As soon as it redirected, the `msalInstance.loginPopup()` promise got rejected. We've seen a error message like `ClientAuthError: User cancelled the flow.` Usually this kind of message will come if user closes the popup window.  But the popup window is still there and user entered the credentials. After logging in instead of redirecting to our app, the popup window stays open and shows the login page right inside. 

This is happening only in case of organisational accounts. If it's a individual account then it's working fine as expected.

Please could you help me with this issue?

Attaching few Screenshots for reference.
<img width="1433" alt="Screenshot 2023-12-18 at 4 40 05 PM" src="https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/140373514/51c20d3f-6b63-4960-86b9-1ceedf3b1b9f">
<img width="484" alt="Screenshot 2023-12-18 at 4 42 41 PM" src="https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/140373514/e5c7c051-5723-4256-a4f9-4c8254054f88">

### Error Message

ClientAuthError: User cancelled the flow.
    at ClientAuthError.AuthError [as constructor] (AuthError.ts:25:1)
    at new ClientAuthError (ClientAuthError.ts:98:1)
    at ClientAuthError.createUserCancelledError (ClientAuthError.ts:153:1)
    at WindowUtils.ts:114:1

### MSAL Configuration

```javascript
{
  auth: {
    clientId: "clientId",
    authority: "https://login.microsoftonline.com/common",
    validateAuthority: true,
    postLogoutRedirectUri: "REDIRECT_URI",
    navigateToLoginRequestUrl: false,
    redirectUri: "REDIRECT_URI",
  },
  cache: {
    cacheLocation: "localStorage",
    storeAuthStateInCookie: isIE(), // isIE() method is a special handling for edge browser
  },
  system: {
    navigateFrameWait: 0,
  },
}
```

### Relevant Code Snippets

```javascript
import { UserAgentApplication } from "msal";

const msalApp = new UserAgentApplication(msalConfig);

const loginRequest = { scopes: ["user.read"], prompt: "select_account" };

    msalApp.loginPopup(loginRequest).then(
      (idToken) => {
        //Login Success
        msalApp.acquireTokenSilent(loginRequest).then(
          (accessToken) => {
            //AcquireToken Success
            handleTokenSuccess(); // Our own logic to handle the login flow
          },
          (error) => {
            //AcquireToken Failure, send an interactive request.
            msalApp.acquireTokenPopup(loginRequest).then(
              (accessToken) => {
                //AcquireToken Success
                handleTokenSuccess(); // Our own logic to handle the login flow
              },
              (error) => {
                 console.log(error)
              }
            );
          }
        );
      },
      (error) => {
        console.log(error);
      }
    );
```

### Reproduction Steps

1. Execute `msalInstance.loginPopup`. Popup window will be opened. 
2. Enter organisational account credentials. So that it'll take you to the Organisation sign-in page. For eg: `sso.godaddy.com`.
3. We'll get the error in console once we redirect to other domain in popup window.
4. After logging in, the popup stays open.

### Expected Behavior

The popup should not get error after redirecting to other domain for sign-in and after logging the popup should close and should redirect to our app.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Safari

### Source

Internal (Microsoft)

**Comment by hectormmg** [comment]
@dawood-rf-97 MSAL v1 is deprecated and no longer receiving maintenance. Please upgrade to MSAL v3.
