### ISSUE TITLE
authentication callback function never gets invoked.

### ISSUE THREAD

**Issue by Aliksalot** [AzureAD/microsoft-authentication-library-for-js#6783]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

2.6.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Confidential

### Description

Hello,

I am using your API with netlify to create a MS teams application. Currently I am struggling with getting authentication token.  Looking at the logs everything seems fine with the /authenticate route, but the /authenticate-callback route never gets called. I get error AADSTS50149: Invalid Code_Challenge_method parameter. 
In your sample code it says i should put the verifier and the challenge (from the cryptoprovider) in session storage in the request, but in netlify i don't have access to such things. 
<img width="217" alt="image" src="https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/117526291/83b3d190-618b-40a8-a2c4-10132271f95b">

I would be happy to hear from you anytime soon!

Best wishes, Alexander Kolev,
Sofia, Bulgaira
12-20-2023

### MSAL Configuration

```javascript
auth: {
      clientId: process.env.REACT_APP_CLIENT_ID || '',
      authority: `https://login.microsoftonline.com/${process.env.REACT_APP_TENANT_ID}`,
      clientSecret: process.env.REACT_APP_CLIENT_SECRET
    },
    system: {
      loggerOptions: {
        loggerCallback(logLevel, message, containsPii) {
          console.log(message)
        },
        piiLoggingEnabled: false,
        logLevel: msal.LogLevel.Verbose,
      }
    }
```

### Relevant Code Snippets

```javascript
const cca = new msal.PublicClientApplication(config)
  const cryptoProvider = new msal.CryptoProvider()

  const { verifier, challenge } = await cryptoProvider.generatePkceCodes()

  const authCodeUrlParams: msal.AuthorizationUrlRequest = {
    scopes: ['openid', 'profile', 'user.read'],
    redirectUri: `${baseUrl}.netlify/functions/teams-authenticate-callback`,
    codeChallenge: challenge,
    codeChallengeMethod: 'S256',
  }

  const authUrl = await cca.getAuthCodeUrl(authCodeUrlParams)
  console.log(`DIRECTING TO CALLBACK WITH AUTHURL: ${authUrl}?Cache-Control=no-cache`)
  return {
    statusCode: 302,
    headers: {
      Location: `${authUrl}?Cache-Control=no-cache`
    },
    body: '',
  };
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by bgavrilMS** [comment]
1. For starter, can you create an authorization URL without PKCE? 
2. There is a state parameter that you can add to the authorization URL. Then the state paramter is sent back in the authorization uri.

**Comment by Aliksalot** [comment]
I managed to fix my problem. Thank you. I don't remember what the issue was, since it was a long ago.
