### ISSUE TITLE
window.crypto.randomUUID is not defined in older browsers

### ISSUE THREAD

**Issue by Stralos** [AzureAD/microsoft-authentication-library-for-js#6784]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.5.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

0

### Public or Confidential Client?

Public

### Description

msal-browser uses `window.crypto.randomUUID()` inside [BrowserCrypto](
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/src/crypto/BrowserCrypto.ts#L86)

Support for IOS safari for `window.crypto.randomUUID()` is only from [15.4](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID)

15.4 has been released at `2022-03-14`. That means this library supports only browser versions from the past 1 and a half year. 

Questions:
- Are there plans to support older browsers ?
- Are there plans to add a polyfill or update the documentation so developers would know that they need a polyfill ?

### Identity Provider

None

### Source

External (Customer)

**Comment by xxcodedream** [comment]
I also encountered this problem, a large number of users using the ios15 version. Some older versions of mobile phones still cannot use this method after upgrading to 15.8. like iphone6, iphonese and so on.

**Comment by Stralos** [comment]
My solution was adding a custom polyfill of guidv4 if window.crypto is not defined.

That seemed to to a trick.

But I would like a response from the maintainers on this one

**Comment by xxcodedream** [comment]
> My solution was adding a custom polyfill of guidv4 if window.crypto is not defined.
> 
> That seemed to to a trick.
> 
> But I would like a response from the maintainers on this one

I tried this way, the effect was not significant at the time, may be a problem with the coverage, but I found that version 3.* didn't use this function in an earlier stage, so I fixed the version to use it. as follows
   "@azure/msal-browser": "3.0.2",
   "@azure/msal-react": "2.0.2",

**Comment by tnorling** [comment]
We've switched to a custom UUID generation function, this will be resolved in 3.8.0. Please note, however, that our [official browser support stance](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md#what-browsers-are-supported-by-msaljs) states that we guarantee support only for the 2 latest versions of all the major browsers.
