### ISSUE TITLE
msal react is picking up really old refresh token and failing to do a silent refresh in iframes

### ISSUE THREAD

**Issue by anujjain85** [AzureAD/microsoft-authentication-library-for-js#6785]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.24.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.0

### Public or Confidential Client?

Public

### Description

Our web based app users use multiple Microsoft work/personal accounts to sign in to our app and other various Microsoft web based products/services using Edge browser. When using our web app (SPA), they are experiencing a weird issue. 

1. User sign in successfully, they are able to get access tokens successfully for upto a day or so(which is the lifetime of our refresh token) 
2. User comes back after few days and goes to our app home page. The home page logs in the user(most likely from local storage cache), then makes the call to acquire token.
3. Aquire token call makes a call to /token endpoint and fails with invalid_grant error code saying refresh token has expired.
4. Then msal tries to silent refresh the refresh token using iframes and is not able to do it. In network logs we see iframe activity as following:
- Call made to login.microsoftonline.com with all query parameters. The result code is 200.
- There is no call to our redirect uri with "code" query string param. On some of our machines/browsers, we can see a call to our redirect uri and that leads to a successful token acquisition in the next /token call. But not in this case.
- After 15 seconds(loadFrameTimeout) the acquireTokenSilent throws monitor_window_timeout error code.

Why is the login.microsoftonline.com not redirecting to our redirectUri in the iFrame on these specific machines? 3rd party cookies are enabled.

### Error Message

invalid_grant, monitor_window_timeout

### MSAL Configuration

```javascript
{
    auth: {
      clientId: 'client id of our app',
      authority: 'https://login.microsoftonline.com/organizations',
      redirectUri: `${window.location.origin}`,
    },
    cache: {
      cacheLocation: 'localStorage'
    },
    system: {
      loadFrameTimeout: 15000
    }
  }
```

### Relevant Code Snippets

```javascript
NA
```

### Reproduction Steps

Not sure of how to repro this consistently

### Expected Behavior

The user should be able to retrieve access tokens silently for as long as refresh tokens are valid/refreshed silently.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Edge

### Source

Internal (Microsoft)

**Comment by tharunhpe** [comment]
I faced a similar issue and had to add this value under system in config:
  system: {
    tokenRenewalOffsetSeconds: 0, // Configure to refresh your token before a certain offset
  },

**Comment by binerdy** [comment]
We have exactly the same problem. Description matches perfectly.

@azure/msal-browser
3.1.0

@azure/msal-angular
3.0.4

**Comment by tnorling** [comment]
> Call made to login.microsoftonline.com with all query parameters. The result code is 200

A result code of 200 & no redirect back to the redirectUri means that some error occurred service side before the redirectUri has been validated (including invalid redirectUri) thus can't be returned back to the application. If you have access to the full url that was called you can copy it and open it in a new tab to see what the error is. If you aren't able to find the url we would need a network trace, which you can send to msaljshelp@microsoft.com
