### ISSUE TITLE
getAuthCodeUrl without redirect but instead show loginPopup?

### ISSUE THREAD

**Issue by stefancvetkovic** [AzureAD/microsoft-authentication-library-for-js#6787]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

^1.14.6

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

^1.4.0

### Public or Confidential Client?

Confidential

### Description

Hello,
I'm using 4-sign-in-hybrid model, where Im trying to obtain an athCode.
Everything works ok, and I even managed to add this code to my redirect_uri, but I have a question regarding redirection for login.
Can you please show me how to use popup instead of redirection? and is it possible to have non-refreshing actions on successful login? to stay on the same page, but just to obtain authCode?

Thanks

### MSAL Configuration

```javascript
const msalInstance = new msal.ConfidentialClientApplication({
  auth: {
    clientId: process.env.CLIENT_ID,
    authority: `https://login.microsoftonline.com/${process.env.TENANT_ID}`,
    clientSecret: process.env.CLIENT_SECRET,
    navigateToLoginRequestUrl: true,
    postLogoutRedirectUri: "http://localhost:3000"
  },
  system: {
    loggerOptions: {
      loggerCallback: (loglevel, message, containsPii) => {
        console.log(message);
      },
      piiLoggingEnabled: false,
      logLevel: msal.LogLevel.Verbose,
    }
  }
});
```

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
`getAuthCodeUrl` only returns a url, it is up to you to implement how that url is opened, that is not within the scope of msal-node
