### ISSUE TITLE
MSAL LoginPopup is not closing 

### ISSUE THREAD

**Issue by Rajesh-UI-developer** [AzureAD/microsoft-authentication-library-for-js#6796]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.4.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.0.6

### Public or Confidential Client?

Public

### Description

I implemented outlook add-in , for this i added MSAL authentication method to login. It works as we expected in chrome, Edge , FireFox browsers but for ISO device like MacOs it's not working as we expected , also it throws error.i added the error message for your preference. I appreciate it if you could help me.Thank you.
![Error](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/95071972/10253079-200d-4252-a198-3f7832b55886)

This is React.js application , i tried  pollIntervalMilliSeconds to 0 this also not working and i tried redirectUri to blank_page this also not working.

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
The original popup window opened by MSAL was closed and a new one opened by the browser. We've heard reports of this happening in Safari but have not been able to determine why the browser is doing this. Unfortunately there's no way for MSAL to handle this as it no longer has a reference to the window. I would recommend using the redirect flow, at least in Safari, to work around this behavior.
