### ISSUE TITLE
Skip "email is verified" screen and continue with registration form.

### ISSUE THREAD

**Issue by faiyazAbdul** [AzureAD/microsoft-authentication-library-for-js#6804]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.14

### Wrapper Library

Not Applicable

### Wrapper Library Version

2.14

### Public or Confidential Client?

Public

### Description

The email verification has multiple steps: user enters his email, Azure sends the code, user enters the code and clicks on 'Verify code' button then there is a last step where the email has been verified and user still needs to click on the Next button to continue the user journey.

Is this possible to skip the last step? If the email is verified, then user should go straight to next screen of the user journey...

### Identity Provider

None

### Source

External (Customer)

**Comment by tnorling** [comment]
MSAL does not control UX and we are not the experts able to answer this kind of question. You haven't specified but I'm assuming you're using Azure B2C, in which case you can open a support ticket [here](https://learn.microsoft.com/en-us/azure/active-directory-b2c/find-help-open-support-ticket) and a B2C support engineer can help clarify this for you.
