### ISSUE TITLE
Customize outgoing request header

### ISSUE THREAD

**Issue by cabrinoob** [AzureAD/microsoft-authentication-library-for-js#6809]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.6.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.9

### Public or Confidential Client?

Confidential

### Description

I'd like to know if it's possible to change the destination header of outgoing requests to protected resources ?
By defaut the interceptor injects the access token in "Authorization: Bearer <token>" header.
I'd like to use this token with the MongoDB Atlas Data API but this API is looking for the token in "jwtTokenString: <token>" header.

So, is it possible to customize this?

Thank you.

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by tnorling** [comment]
No this is not possible with the default Interceptor. We try to build for the most common use cases, for something like this we'd suggest you implement your own interceptor. That said I won't rule out adding something like this in the future, I've marked a similar ask as a feature request. You can track #6795 for this.
