### ISSUE TITLE
Connection with Quarkus Backend

### ISSUE THREAD

**Issue by ManciDRaffy** [AzureAD/microsoft-authentication-library-for-js#6810]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.5.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.8

### Public or Confidential Client?

Public

### Description

I have integrated MSAL into my Angular frontend application.
My Quarkus 3.6.4 backend is configured with OIDC, but I am consistently receiving an "Unauthorized" response from it.
The user is logged in, and all relevant information is stored in local storage. Everything else appears to be functioning correctly.

I think it is a problem with MSAL

### MSAL Configuration

```javascript
const msalPublicClientApplication: PublicClientApplication = new PublicClientApplication({
  auth: {
    clientId: environment.auth.clientId,
    authority: environment.auth.authority,
    redirectUri: environment.auth.redirectUri,
    navigateToLoginRequestUrl: false,

  },
  cache: {
    cacheLocation: environment.auth.cacheLocation,
  },
  system: {
    allowNativeBroker: false,
    loggerOptions: {
      // loggerCallback,
      // logLevel: LogLevel.Info,
      // piiLoggingEnabled: false
    }
  }
});
```

### Relevant Code Snippets

```javascript
auth: {
    clientId: '{CLIENT-ID}',
    authority: 'https://login.microsoft.com/{ID}',
    redirectUri: window.location.origin,
    postLogoutRedirectUri: 'https://localhost:4200',
    cacheLocation: BrowserCacheLocation.LocalStorage,
    authRequest: {
      scopes: ['user.read']
    },
    protectedResourceMap: new Map([
      ['https://graph.microsoft.com/v1.0/me', ['user.read']],
      ['http://localhost:8080/api/v1', ['user.read']],
    ]),
  },

Quarkus Config:
quarkus.oidc.auth-server-url=https://login.microsoft.com/{id}
quarkus.oidc.provider=MICROSOFT
quarkus.oidc.client-id={client-id}
quarkus.oidc.application-type=SERVICE
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by tnorling** [comment]
I'm not familiar with Quarkus and unfortunately without more information about what specifically is wrong we won't be able to provide support. Let us know if there's more detail you can provide.
