### ISSUE TITLE
Need advice how to use entraid from a pwa/service worker

### ISSUE THREAD

**Issue by davesmits** [AzureAD/microsoft-authentication-library-for-js#6813]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

NA

### Wrapper Library

Not Applicable

### Wrapper Library Version

NA

### Public or Confidential Client?

Public

### Description

I am trying to build a windows 11 widget with a PWA app. The widget is controlled by a service worker that will be updating the widget periodically.

What I did so far: Create a PWA where the user via the GUI can sign in using code flow with PKCE. The access token and refresh token are stored in storage (indexeddb). 

This more or less worked but the refresh token is only valid for 24 hours.. and in my scenario, the user shouldn't come back to the UI. I tried to change the app type from a PWA to web but seems the origin the pwa adds for free is causing another problem: 'Cross-origin token redemption is permitted only for the 'Single-Page Application' client-type'

Can someone advice me what flow have to use to enable this scenario with EntraID?

 

### MSAL Configuration

```javascript
NA
```

### Relevant Code Snippets

```javascript
NA
```

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by davesmits** [comment]
Its gonna be kind of crappy solution but the only viable solutions seems to start using device code flow?

**Comment by hectormmg** [comment]
@davesmits for your specific use-case MSAL Node may be a better fit. A Windows 11 Widget would most likely be considered a public web client rather than a SPA. We have an Electon sample that you may be able to reference even if your scenario isn't officially supported.

**Comment by davesmits** [comment]
@hectormmg thank you. I will look in to it but I doubt that is a viable route as need to end up in the windows store (and there for need to use the pwabuilder).

But currently not using any MSAL library and directly the endpoints of EntraId. In my investigation I concluded that EntraID is going be a problem? DO you know a flow that might support this and isnt that ugly (the only one I think that can handle my scenario is Device Code flow).

**Comment by tnorling** [comment]
You can do auth code flow in msal-node as well if that's what you need. The refresh token returned in that flow is much longer lived than the one you get in SPA flows using msal-browser.

**Comment by davesmits** [comment]
I fixed it by adding a backend indeed and now have the non-spa application but all did require a actual backend as from a PWA you dont control the origin header
