### ISSUE TITLE
LoginPopup randomly throws "BrowserAuthError: user_cancelled: User cancelled the flow"

### ISSUE THREAD

**Issue by andreaslydemann** [AzureAD/microsoft-authentication-library-for-js#6821]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.7.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

I have setup the msal-browser using the loginPopup function. When the loginPopup function is called, it correctly shows a popup. after filling it out (of if you recently signed in) it automatically closes, but about half the time it doesn't redirect me from here. Instead it throws the error "BrowserAuthError: user_cancelled: User cancelled the flow" in the log and you need to press log in again. This error message is false as the user didn't cancel the flow at any point.

Whenever this error occurs, I can see in the network activity that `openid-configuration` is called and returns OK but no token retrieval happens after that, which would normally happen

### Error Message

```
Uncaught (in promise) BrowserAuthError: user_cancelled: User cancelled the flow.
    at _t (index-858c98ac.js:1665:32582)
    at index-858c98ac.js:1665:113288
```

### MSAL Configuration

```javascript
{
  auth: {
    clientId: this.settings.azureConfig?.clientId ?? '',
    authority: `https://login.microsoftonline.com/${this.settings.azureConfig?.tenant}`,
    redirectUri: getFullRedirectUri(this.settings.redirect),
  },
  cache: { cacheLocation: 'sessionStorage' }
}
```

### Relevant Code Snippets

```javascript
export class AzureADAuthenticator extends AbstractAuthenticator {
  private authClient: PublicClientApplication;
  private isInitialized = false;

  constructor(settings: Settings) {
    super({
      ...settings,
      authType: AuthType.CODE_PKCE,
    });

    this.authClient = new PublicClientApplication({
      auth: {
        clientId: this.settings.azureConfig?.clientId ?? '',
        authority: `https://login.microsoftonline.com/${this.settings.azureConfig?.tenant}`,
        redirectUri: getFullRedirectUri(this.settings.redirect),
      },
      cache: { cacheLocation: 'sessionStorage' },
    });
  }

  async initialize() {
    if (this.isInitialized) return;

    try {
      await this.authClient.initialize();
      this.isInitialized = true;
    } catch (error) {
      this.logger?.info('Initialization error: ' + error);
    }
  }

  login() {
    return this.authenticate(() => this.loginPopup());
  }

  override logout() {
    super.logout();

    this.authClient.clearCache();
  }

  private async authenticate(authfunc: () => Promise<AuthenticationResult>) {
    await this.initialize();

    const authResult = await authfunc();

    console.log('authResult: ', authResult);

    if (authResult?.idToken) {
      console.log('idToken: ', authResult.idToken);
      this.authenticateWithJWT(authResult.idToken);
    } else {
      this.logger?.warn(
        'Id token is undefined, could not trigger authentication with JWT.',
      );
    }
  }

  private loginPopup() {
    try {
      return this.authClient.loginPopup({
        scopes: ['openid', 'profile', 'email'],
      });
    } catch (error) {
      this.logger?.info('Login Popup error: ' + error);
      throw error;
    }
  }
  
  ...
}
```

### Reproduction Steps

Copy and execute the provided code by calling the login() function on a button press.

### Expected Behavior

I expect that I'm able to sign in consistently or an appropriate error is given that tells me what went wrong or what's missing.

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

External (Customer)

**Comment by tnorling** [comment]
I suspect your instance of `AzureAdAuthenticator` is being garbage collected before loginPopup is finished, especially given you're executing this on button press and this is uncaught. I can't reproduce this with our own samples so that might be something for you to investigate. If you have a link to a minimal repro I can download I'd be happy to take a closer look.
