### ISSUE TITLE
msal-browser failed in Office Addin Dialog API

### ISSUE THREAD

**Issue by Edward-Zhou** [AzureAD/microsoft-authentication-library-for-js#6823]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

^3.7.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

^2.0.9

### Public or Confidential Client?

Public

### Description

I am trying to use `@azure/msal-browser` and `@azure/msal-react` to enable Excel addin support microsoft sso and access Graph api.

Due to that Excel addin does not support access external url from Excel taskpane, i need to access `@azure/msal-browser` in dialog api which can be referece [Enable single sign-on (SSO) in an Office Add-in](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins).

If I use `PublicClientApplication` in normail excel addin project like react [React single-page application using MSAL React to authenticate users against Azure AD for Customers](https://learn.microsoft.com/en-us/samples/azure-samples/ms-identity-ciam-javascript-tutorial/ms-identity-ciam-javascript-tutorial-1-sign-in-react/), I am able to access the authorize consent page.

But, I open the page from dialog api like below:

```
 Office.context.ui.displayDialogAsync('https://localhost:3000/dialog.html', {height: 30, width: 20, displayInIframe: true});
```
And in the dialog page, it will call 
```
const msalInstance = new PublicClientApplication(msalConfig);
```
I will throw error below:
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/16079555/0c59d3c1-1391-4d47-904a-47e60ff04fe2)

### Identity Provider

Azure AD / MSA

### Source

External (Customer)

**Comment by Edward-Zhou** [comment]
This specific to `@azure/msal-browser` version `^3.7.0`, if I switch to `^2.28.1`, the error will gone.

**Comment by tnorling** [comment]
Is there anymore information you can provide? We don't have anything called "register" in our codebase
