### ISSUE TITLE
Test and update the confidential client application QuickStarts

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-js#6824]
### Core Library

MSAL Node (@azure/msal-node)

### Wrapper Library

Not Applicable

### Public or Confidential Client?

Confidential

### Documentation Location

quickstarts

### Description

We need to test and fix our quick starts. Quick Starts are based on samples.

For nodejs confidential there is only 1: "nodeJS web".

Follow the tracking document [here](https://microsoft.sharepoint.com/:x:/t/appregportal/EZZQEVnkGhJLlLvMHoTol3cBY3k13IReYVet5VtYUJyJlQ?e=kNCAj9&nav=MTVfe0FDQkFBOThELTA3MjgtNDIwNS1COEI5LUY0N0E4Qjg4RTI5MH0&isSPOFile=1&clickparams=eyAiWC1BcHBOYW1lIiA6ICJNaWNyb3NvZnQgT3V0bG9vayIsICJYLUFwcFZlcnNpb24iIDogIjE2LjAuMTY3MTguMjAwMDIiLCAiT1MiIDogIldpbmRvd3MiIH0%3D&CID=E2C32AAD-FB47-407F-BAA7-AA1C3FEDD5FE&web=1&wdLOR=cE3C72A42-5D64-4F4D-88F9-D37A572A9365)

Please note that testing needs to be done in PPE and you'll need an account for it. Reach out to Trishala Pugazhendhi for details.

**Comment by johnwc** [comment]
There currently is samples for react and angular, can we get a working sample for [vuejs 3](https://vuejs.org/guide/introduction.html) and their [router](https://router.vuejs.org/) with this update?

**Comment by Robbie-Microsoft** [comment]
> There currently is samples for react and angular, can we get a working sample for [vuejs 3](https://vuejs.org/guide/introduction.html) and their [router](https://router.vuejs.org/) with this update?

CC @peterzenz @tnorling

**Comment by johnwc** [comment]
@Robbie-Microsoft @peterzenz @tnorling what about the vuejs samples?
