### ISSUE TITLE
Set/obtain code_challenge value

### ISSUE THREAD

**Issue by snisar** [AzureAD/microsoft-authentication-library-for-js#6827]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.7.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.10

### Public or Confidential Client?

Public

### Description

I'm using MSAL 3.0.10 in an Angular application and can successfully obtain an authorisation code.

However, when trying to obtain a access token using the code + secret on my server, I get the following error

AADSTS501481: The Code_Verifier does not match the code_challenge supplied in the authorization request

Looking at the documentation, I need to pass code_verifier parameter in the request, which was used to generate the code_challenge in the authorisation code required in the front-end.

I can see the code_challenge value in the request the MSAL creates, but I can't seem to be able to access that value or set it myself, so I can then use it the back-end.

Thanks for any help/advise!

### Identity Provider

Azure AD / MSA

### Source

Internal (Microsoft)

**Comment by hectormmg** [comment]
@snisar thanks for submitting the question. Obtaining an auth code on the client-side and trading it on the server side is not supported by MSAL Browser. Could you tell us more about why you need to split the flow between the client and server?

Thanks.

**Comment by snisar** [comment]
Thanks for responding.

We're moving over from MSAL 2 and this was how our login functionality was implemented previously.

We need to verify the user exists in our own application security system, so can't rely on a ID token or email address being provided from the front end, the exchange of the Auth code plus client secret for an access/ID token provides us an extra layer of security we need. Hope this makes sense!

**Comment by hectormmg** [comment]
@snisar I'm surprised to hear this works with MSAL Browser v2, it's shouldn't be since the PKCE verifier and challenge are also required there. What are you using in the backend to trade the auth code? Can you not do the entire authentication flow from the server side?
