### ISSUE TITLE
@azure/msal-node is not available in Node 20.5.1

### ISSUE THREAD

**Issue by URockMan** [AzureAD/microsoft-authentication-library-for-js#6828]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

2.6.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

3.4.1

### Public or Confidential Client?

Public

### Description

import { ClientSecretCredential } from "@azure/identity"; 

While importing the identity library it is throwing below error: 
Cannot find module '@azure/msal-node' from 'project/node_modules/@azure/identity/dist/index.js'

### Error Message

import { ClientSecretCredential } from "@azure/identity"; 

While importing the identity library it is throwing below error: 
Cannot find module '@azure/msal-node' from 'project/node_modules/@azure/identity/dist/index.js'

### MSAL Configuration

```javascript
auth: {
                authority: "https://login.microsoftonline.com/managed_identity",
                clientId: clientId
            }
```

### Relevant Code Snippets

```javascript
import { ClientSecretCredential } from "@azure/identity";
```

### Reproduction Steps

import { ClientSecretCredential } from "@azure/identity"; 

### Expected Behavior

Import should be successfull

### Identity Provider

Azure AD / MSA

### Browsers Affected (Select all that apply)

None (Server), Other

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
We can't really help with package install issues nor can we assist with issues related to @azure/identity - you'll need to open an issue with them or with npm. The latest version of msal-node does support Node 20.
