### ISSUE TITLE
BrowserAuthError: uninitialized_public_client_application

### ISSUE THREAD

**Issue by Harbinder-web** [AzureAD/microsoft-authentication-library-for-js#6839]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.7.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.0.10

### Public or Confidential Client?

Public

### Description

Im checking for **InProgress** equals "none" before making a call, however its still showing the init issue.

### Error Message

BrowserAuthError: uninitialized_public_client_application: You must call and await the initialize function before attempting to call any other MSAL API.  For more visit: aka.ms/msaljs/browser-errors

### MSAL Logs

<img width="412" alt="image" src="https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/61920204/e7b82070-1b01-4ce2-b4fc-ee4db74d31c6">

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
export const msalConfig = {
  auth: {
    clientId: "added",
    authority: added,
    knownAuthorities: [b2cPolicies.authorityDomain],
    redirectUri: "/",
  },
  cache: {
    cacheLocation: "localStorage",
  },
};
```

### Relevant Code Snippets

```javascript
export const msalInstance = new PublicClientApplication(msalConfig);
msalInstance.initialize().then((res) => console.log("msalInstance", res));
```

### Reproduction Steps

1. Above provided all details 

### Expected Behavior

as expected or explained by moderator check for InProgress is not working for give issue

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by tnorling** [comment]
Please share trace level logs and we'd be happy to review.
