### ISSUE TITLE
Access token is not removed from the server after logging out

### ISSUE THREAD

**Issue by SofiiaRomah** [AzureAD/microsoft-authentication-library-for-js#6840]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.18.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.0.0-alpha.1

### Public or Confidential Client?

Public

### Description

I'm using **logoutRedirect** to log out from the app. But seems like the user session is active after logging out because I still can use the old access token to authenticate requests that I'm sending via Postman

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
{
    auth: {
        authority: "https://login.microsoftonline.com/{tenantId}",
        clientId: "clientId",
        redirectUri: "http://localhost:3000",
    },
    cache: {
        cacheLocation: BrowserCacheLocation.SessionStorage,
        storeAuthStateInCookie: false,
    },
};
```

### Relevant Code Snippets

```javascript
export const logoutCurrentUser = async (): Promise<void> => {
    const accounts = authProvider.getAllAccounts();
    const account = accounts[0] || null;
    await authProvider.logoutRedirect({
        account: account,
        postLogoutRedirectUri: "http://localhost:3000",
    });
};
```

### Reproduction Steps

1. Copy the access token 1 that is generated.
2. Log out of the application.
3. Try to send a request with token 1 in Postman

### Expected Behavior

401 error will appear

### Identity Provider

Entra ID (formerly Azure AD) / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
Access tokens are stateless so this is expected. After signing out you will not be able to _acquire new tokens_ without re-authenticating, however, existing tokens will be valid until expiration. MSAL.js will clear tokens from the cache upon signout but if you're storing them somewhere else it is your responsibility to remove them.
