### ISSUE TITLE
MSAL Azure AD B2C implicate flow clientAuthError: Invalid state 

### ISSUE THREAD

**Issue by amhemanth** [AzureAD/microsoft-authentication-library-for-js#6843]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.32.2

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

1.1.2

### Public or Confidential Client?

Confidential

### Description

While integrating MSAL-Angular lib for Azure AD login and angular-oauth2-oidc lib for Azure AD B2C login in our Angular application, we've encountered an issue involving state conflicts and ClientAuthError within the MSAL library.

### Error Message

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/40871106/8eaa3906-4a3e-42d9-b439-3e45dbd8d7b1)

### MSAL Logs

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/40871106/eef254fd-463d-4442-a92e-0c0d2d5643d9)

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
auth: {
                authority: azureAdOptions.instance + azureAdOptions.tenantId,
                clientId: azureAdOptions.clientId,
                validateAuthority: true,
                redirectUri: window.location.origin + '/signin-oidc',
            },
            cache: {
                cacheLocation: 'localStorage',
                storeAuthStateInCookie: isIE, // Set to true for Internet Explorer 11
            },
```

### Relevant Code Snippets

```javascript
this.oauthService.configure(authConfig);
        this.oauthService.tokenValidationHandler = new JwksValidationHandler();
        this.oauthService.setupAutomaticSilentRefresh();
        this.oauthService.events.subscribe((event: OAuthEvent) => {
            console.debug('oauth/oidc event: ', event.type);
            if (event.type === 'token_received') {
                console.debug('logged in');
            }
        });

        const url = authConfig.issuer + '.well-known/openid-configuration?p=B2C_1_Staging_SignUpIn';
        console.log('Url: ', url);
        this.oauthService.loadDiscoveryDocument(url).then(() => {
            return this.oauthService.tryLoginImplicitFlow();
        });
```

### Reproduction Steps

1. Configure Angular Application Azure AD login with msal-angular and msal-browser.
2. "@azure/msal-angular": "^1.1.2","@azure/msal-browser": "^2.32.2", 
3. Configure Angular Application Azure AD B2C login with angular-oauth2-oidc.
4. "angular-oauth2-oidc": "^9.0.0","angular-oauth2-oidc-jwks": "^9.0.0",

### Expected Behavior

User should be able to login in oauth2 implicit flow. 

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by tnorling** [comment]
I'm a bit confused by the libraries you're trying to use here.

- msal-angular v1 uses the Implicit flow and is deprecated
- msal-browser v2 uses the Auth Code flow and is incompatible with msal-angular v1
- I'm not familiar with the other 2 libraries you're trying to use here

My first suggestion is to ensure consistency between your dependencies. Use msal-angular v3 with msal-browser v3 or if you need to support older versions of angular use msal-angular v2 with msal-browser v2
