### ISSUE TITLE
Unable to build due to publicClientApplication mismatches (is it due to Angular 17)?

### ISSUE THREAD

**Issue by grosch-intl** [AzureAD/microsoft-authentication-library-for-js#6847]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.7.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.10

### Public or Confidential Client?

Public

### Description

Trying to add MSAL to my existing application and it won't build due to type mismatches.

This is in an Angular 17 application. I'm not sure if that's the whole issue.  I see things about angular 17 in these issues, but I'm not trying to do anything angular specific there so hoping that's not the issue.

I put this in my package.json overrides:

    "@azure/msal-browser": ">=3.7.0",
    "@azure/msal-angular": ">=3.0.10",

### Error Message

<pre>
 Error: src/app/provide-azure.ts:28:5 - error TS2345: Argument of type 'PublicClientApplication' is not assignable to parameter of type 'IPublicClientApplication'.
  The types returned by 'getLogger()' are incompatible between these types.
    Type 'import(".../node_modules/@azure/msal-common/dist/logger/Logger").Logger' is not assignable to type 'import(".../node_modules/@azure/msal-angular/node_modules/@azure/msal-common/dist/logger/Logger").Logger'.
      Types have separate declarations of a private property 'correlationId'.
  
28     publicClientApplication,
       ~~~~~~~~~~~~~~~~~~~~~~~


Error: src/app/provide-azure.ts:68:59 - error TS2322: Type 'import(".../node_modules/@azure/msal-browser/dist/app/PublicClientApplication").PublicClientApplication' is not assignable to type 'import(".../node_modules/@azure/msal-angular/node_modules/@azure/msal-browser/dist/app/PublicClientApplication").PublicClientApplication'.
  Property 'controller' is protected but type 'PublicClientApplication' is not a class derived from 'PublicClientApplication'.

68             Providers.globalProvider = new Msal2Provider({publicClientApplication})
                                                             ~~~~~~~~~~~~~~~~~~~~~~~
</pre>

### MSAL Logs

It won't compile so I can't provide logs.

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
const publicClientApplication = new PublicClientApplication({
    auth: {
        clientId: environment.azure.clientId,
        authority: 'https://login.microsoftonline.com/....',
        redirectUri: window.location.origin
    },
    cache: {
        cacheLocation: BrowserCacheLocation.LocalStorage,
        storeAuthStateInCookie: false,
        claimsBasedCachingEnabled: true
    }, system: {
        allowNativeBroker: false
    }
})
```

### Relevant Code Snippets

```javascript
export const msalProvider = MsalModule.forRoot(
    publicClientApplication,
    {
        interactionType: InteractionType.Redirect
    },
    {
        interactionType: InteractionType.Redirect,
        protectedResourceMap: new Map([
            [`${environment.baseUrl}/*`, [`${environment.azure.clientId}/.default`]]
        ])
    }
)

Providers.globalProvider = new Msal2Provider({publicClientApplication})
```

### Reproduction Steps

I'm just trying to build the app.

### Expected Behavior

It builds :)

### Identity Provider

Entra ID (formerly Azure AD) / MSA

### Browsers Affected (Select all that apply)

Other

### Source

External (Customer)

**Comment by grosch-intl** [comment]
Sorry, looks like this was due to another library that conflicted with versions.

**Comment by cfeo-bhs** [comment]
> Sorry, looks like this was due to another library that conflicted with versions.

Could you share which lib was causing the conflict? I'm having the same and suspect this is happening
