### ISSUE TITLE
Which Angular/msal versions support silent authentication without 3rd party cookies?

### ISSUE THREAD

**Issue by BrianMikinski** [AzureAD/microsoft-authentication-library-for-js#6848]
### Core Library

MSAL.js (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Public or Confidential Client?

Public

### Documentation Location

https://learn.microsoft.com/en-us/entra/identity-platform/quickstart-single-page-app-angular-sign-in

### Description

Hi, I'm trying to understand how Chromes deprecation of 3rd Party Cookies will affect different versions of the MSAL library, specifically as it relates to acquiring silent auth tokens.

From the Angular MSAL library, these are two of the options for silently acquiring new tokens - 

```typescript
MsalService.acquireTokenSilent(silentRequest: SilentRequest): Observable<AuthenticationResult>;
// and
MsalService.ssoSilent(request: SsoSilentRequest): Observable<AuthenticationResult>;
```

If an app is using MSAL V2, does an app need to upgrade to MSAL V3 to ensure that silent tokens are able to be acquired without the use of cookies?

**Comment by hectormmg** [comment]
@BrianMikinski falling back to interactive authentication is the correct usage pattern for all scenarios, especially where third-party cookies are blocked for both MSAL v2 and MSAL v3.

For both versions, the `acquireTokenSilent` API will still successfully return valid cached tokens and will refresh these tokens until the refresh token expires. However, when the refresh token expires and third-party cookies are blocked, `acquireTokenSilent` will not be able to silently acquire a new refresh token will throw an interaction_required error, prompting the application to fall back to an interactive API.

I would still recommend you upgrade to MSAL v3 for the all-around improvements and maintained support, but it doesn't provide a mitigation for SSO without access to 3p cookies.

https://learn.microsoft.com/en-us/entra/identity-platform/reference-third-party-cookies-spas
