### ISSUE TITLE
MSAL clearHash() after redirect causing exception in Next.js 14

### ISSUE THREAD

**Issue by timtucker-dte** [AzureAD/microsoft-authentication-library-for-js#6851]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.7.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.0.10

### Public or Confidential Client?

Public

### Description

Finding issues with the combination of MSAL-React + Next.js 14 when using redirect for logins.

(Edit: after simplifying things, it seems to be consistent regardless of whether I run live or via a client build)

From what it looks like:
- Initial page load is OK
- MSAL sees that the user needs to sign in
- MSAL redirects to a Microsoft page for sign in
- The Microsoft page redirects back, with data sent in the URL
- MSAL grabs the data out of the URL
- Next.js overrides window.history.replaceState
- MSAL has a clearHash() function that attempts to clear the "#" from the URL
- clearHash() makes a call to window.history.replaceState
- Next.js calls applyUrlFromHistoryPushReplace() from the overridden window.history.replaceState
- applyUrlFromHistoryPushReplace attempts to access window.history.state.__PRIVATE_NEXTJS_INTERNALS_TREE
- window.history.state is null at that point, so an exception gets thrown

Note that I'm passing a custom NavigationClient to the MSAL instance that uses the Next.js router for navigateInternal, but that doesn't appear to be getting called in this flow.

I haven't yet figured out why it works live, but not in the exported build -- I suspect it's a timing issue and in the live build either:
- MSAL makes the call to window.history.replaceState faster than Next.js can override it
- Next.js is able to set the value of window.history.state before MSAL attemps to call replaceState

Not sure if this is an MSAL bug or a Next.js bug.

It seems like this could potentially be addressed with either (or both):
- A null check on the Next.js side
- Using the Navigation client for updating the URL on the MSAL side (to enable everything that modifies the URL to go through the Next.js router)

### Error Message

The exception:
Cannot read properties of null (reading '__PRIVATE_NEXTJS_INTERNALS_TREE')

The relevant call stack:
at main-app-02669ec414a26910.js:1028:48
    at __webpack_modules__.45060.exports.startTransition (main-app-02669ec414a26910.js:16861:9)
    at applyUrlFromHistoryPushReplace (main-app-02669ec414a26910.js:1024:40)
    at History.replaceState (main-app-02669ec414a26910.js:1058:17)
    at clearHash (page-2720a79a295b2bcc.js:6199:31)
    at RedirectClient.getRedirectResponse (page-2720a79a295b2bcc.js:10086:13)
    at RedirectClient.handleRedirectPromise (page-2720a79a295b2bcc.js:9994:57)
    at StandardController.handleRedirectPromise (page-2720a79a295b2bcc.js:10905:55)
    at PublicClientApplication.handleRedirectPromise (page-2720a79a295b2bcc.js:2752:32)

(everything above clearHash is Next.js code / everything from clearHash and below is MSAL code)

### MSAL Logs

7.1 : Verbose - BrowserCrypto: modern crypto interface available
layout-a01009f142ecdc18.js:13093 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Trace - initialize called
layout-a01009f142ecdc18.js:13084 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Info - Emitting event: msal:initializeStart
layout-a01009f142ecdc18.js:13087 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Verbose - Claims-based caching is disabled. Clearing the previous cache with claims
layout-a01009f142ecdc18.js:13093 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Trace - Executing function clearTokensAndKeysWithClaims
layout-a01009f142ecdc18.js:13093 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Trace - BrowserCacheManager.getTokenKeys called
layout-a01009f142ecdc18.js:13087 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Verbose - BrowserCacheManager.getTokenKeys - No token keys found
layout-a01009f142ecdc18.js:13093 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Trace - Returning result from clearTokensAndKeysWithClaims
layout-a01009f142ecdc18.js:13084 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Info - Emitting event: msal:initializeEnd
layout-a01009f142ecdc18.js:13087 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Verbose - getAllAccounts called
layout-a01009f142ecdc18.js:13093 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Trace - BrowserCacheManager.getAccountKeys called
layout-a01009f142ecdc18.js:13087 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Verbose - BrowserCacheManager.getAccountKeys - No account keys found
layout-a01009f142ecdc18.js:13093 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Trace - BrowserCacheManager.getActiveAccount: No active account filters cache schema found, looking for legacy schema
layout-a01009f142ecdc18.js:13093 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Trace - BrowserCacheManager.getActiveAccount: No active account found
layout-a01009f142ecdc18.js:13093 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Trace - BrowserCacheManager.getActiveAccount: No active account filters cache schema found, looking for legacy schema
layout-a01009f142ecdc18.js:13093 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Trace - BrowserCacheManager.getActiveAccount: No active account found
layout-a01009f142ecdc18.js:13084 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-react@2.0.10 : Info - useAccount - Updating account
layout-a01009f142ecdc18.js:13087 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Verbose - Event callback registered with id: 35f071e6-3139-42cb-9cde-09b16242c1f2
layout-a01009f142ecdc18.js:13087 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-react@2.0.10 : Verbose - useMsalAuthentication - Registered event callback with id: 35f071e6-3139-42cb-9cde-09b16242c1f2
layout-a01009f142ecdc18.js:13087 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Verbose - Event callback registered with id: fa7e838b-96db-45ee-b283-c22ea2b640ff
layout-a01009f142ecdc18.js:13087 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-react@2.0.10 : Verbose - MsalProvider - Registered event callback with id: fa7e838b-96db-45ee-b283-c22ea2b640ff
layout-a01009f142ecdc18.js:13093 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Trace - initialize called
layout-a01009f142ecdc18.js:13084 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Info - initialize has already been called, exiting early.
layout-a01009f142ecdc18.js:13087 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Verbose - handleRedirectPromise called
layout-a01009f142ecdc18.js:13087 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Verbose - getAllAccounts called
layout-a01009f142ecdc18.js:13093 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Trace - BrowserCacheManager.getAccountKeys called
layout-a01009f142ecdc18.js:13087 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Verbose - BrowserCacheManager.getAccountKeys - No account keys found
layout-a01009f142ecdc18.js:13084 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Info - Emitting event: msal:handleRedirectStart
layout-a01009f142ecdc18.js:13087 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Verbose - Emitting event to callback 35f071e6-3139-42cb-9cde-09b16242c1f2: msal:handleRedirectStart
layout-a01009f142ecdc18.js:13087 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Verbose - Emitting event to callback fa7e838b-96db-45ee-b283-c22ea2b640ff: msal:handleRedirectStart
layout-a01009f142ecdc18.js:13087 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Verbose - handleRedirectPromise has been called for the first time, storing the promise
layout-a01009f142ecdc18.js:13093 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Trace - BrowserCacheManager.getCachedNativeRequest called
layout-a01009f142ecdc18.js:13093 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Trace - BrowserCacheManager.getTemporaryCache: No cache item found in local storage
layout-a01009f142ecdc18.js:13093 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Trace - BrowserCacheManager.getCachedNativeRequest: No cached native request found
layout-a01009f142ecdc18.js:13093 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Trace - handleRedirectPromise - acquiring token from web flow
layout-a01009f142ecdc18.js:13093 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Trace - BrowserCacheManager.getTemporaryCache: Temporary cache item returned
layout-a01009f142ecdc18.js:13087 [Fri, 26 Jan 2024 15:53:40 GMT] : [61f150f8-487d-4bb8-b9e0-473aad0baad6] : msal.js.browser@3.7.1 : Verbose - initializeServerTelemetryManager called
layout-a01009f142ecdc18.js:13093 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Trace - BrowserCacheManager.getTemporaryCache: Temporary cache item returned
layout-a01009f142ecdc18.js:13087 [Fri, 26 Jan 2024 15:53:40 GMT] : [61f150f8-487d-4bb8-b9e0-473aad0baad6] : msal.js.browser@3.7.1 : Verbose - getRedirectResponseHash called
layout-a01009f142ecdc18.js:13093 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Trace - BrowserCacheManager.cleanRequestByInteractionType called
layout-a01009f142ecdc18.js:13093 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Trace - BrowserCacheManager.resetRequestCache called
layout-a01009f142ecdc18.js:13093 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Trace - BrowserCacheManager.getTemporaryCache: Temporary cache item returned
layout-a01009f142ecdc18.js:13093 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Trace - BrowserCacheManager.getTemporaryCache: No cache item found in local storage
layout-a01009f142ecdc18.js:13084 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Info - Emitting event: msal:loginFailure
layout-a01009f142ecdc18.js:13087 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Verbose - Emitting event to callback 35f071e6-3139-42cb-9cde-09b16242c1f2: msal:loginFailure
layout-a01009f142ecdc18.js:13087 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Verbose - Emitting event to callback fa7e838b-96db-45ee-b283-c22ea2b640ff: msal:loginFailure
layout-a01009f142ecdc18.js:13084 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Info - Emitting event: msal:handleRedirectEnd
layout-a01009f142ecdc18.js:13087 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Verbose - Emitting event to callback 35f071e6-3139-42cb-9cde-09b16242c1f2: msal:handleRedirectEnd
layout-a01009f142ecdc18.js:13087 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Verbose - Emitting event to callback fa7e838b-96db-45ee-b283-c22ea2b640ff: msal:handleRedirectEnd
layout-a01009f142ecdc18.js:13084 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-react@2.0.10 : Info - MsalProvider - msal:handleRedirectStart results in setting inProgress from startup to handleRedirect
layout-a01009f142ecdc18.js:13087 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Verbose - getAllAccounts called
layout-a01009f142ecdc18.js:13093 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Trace - BrowserCacheManager.getAccountKeys called
layout-a01009f142ecdc18.js:13087 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Verbose - BrowserCacheManager.getAccountKeys - No account keys found
layout-a01009f142ecdc18.js:13087 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Verbose - getAllAccounts called
layout-a01009f142ecdc18.js:13093 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Trace - BrowserCacheManager.getAccountKeys called
layout-a01009f142ecdc18.js:13087 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Verbose - BrowserCacheManager.getAccountKeys - No account keys found
layout-a01009f142ecdc18.js:13084 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-react@2.0.10 : Info - MsalProvider - msal:handleRedirectEnd results in setting inProgress from handleRedirect to none
layout-a01009f142ecdc18.js:13087 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Verbose - getAllAccounts called
layout-a01009f142ecdc18.js:13093 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Trace - BrowserCacheManager.getAccountKeys called
layout-a01009f142ecdc18.js:13087 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Verbose - BrowserCacheManager.getAccountKeys - No account keys found
layout-a01009f142ecdc18.js:13087 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Verbose - getAllAccounts called
layout-a01009f142ecdc18.js:13093 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Trace - BrowserCacheManager.getAccountKeys called
layout-a01009f142ecdc18.js:13087 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Verbose - BrowserCacheManager.getAccountKeys - No account keys found
main-app-02669ec414a26910.js:256 Login error:  ObjectacquireToken: async (callbackInteractionType, callbackRequest)=> {…}error: TypeError: Cannot read properties of null (reading '__PRIVATE_NEXTJS_INTERNALS_TREE')
    at https://example.com/_next/static/chunks/main-app-02669ec414a26910.js:1028:48
    at __webpack_modules__.45060.exports.startTransition (https://example.com/_next/static/chunks/main-app-02669ec414a26910.js:16861:9)
    at applyUrlFromHistoryPushReplace (https://example.com/_next/static/chunks/main-app-02669ec414a26910.js:1024:40)
    at History.replaceState (https://example.com/_next/static/chunks/main-app-02669ec414a26910.js:1058:17)
    at clearHash (https://example.com/_next/static/chunks/app/(authenticated)/layout-a01009f142ecdc18.js:16427:31)
    at RedirectClient.getRedirectResponse (https://example.com/_next/static/chunks/app/(authenticated)/layout-a01009f142ecdc18.js:20314:13)
    at RedirectClient.handleRedirectPromise (https://example.com/_next/static/chunks/app/(authenticated)/layout-a01009f142ecdc18.js:20222:57)
    at StandardController.handleRedirectPromise (https://example.com/_next/static/chunks/app/(authenticated)/layout-a01009f142ecdc18.js:21133:55)
    at PublicClientApplication.handleRedirectPromise (https://example.com/_next/static/chunks/app/(authenticated)/layout-a01009f142ecdc18.js:12891:32)
    at https://example.com/_next/static/chunks/app/(authenticated)/layout-a01009f142ecdc18.js:12026:22login: async (callbackInteractionType, callbackRequest)=> {…}result: null[[Prototype]]: Object
__webpack_modules__.70945.window.console.error @ main-app-02669ec414a26910.js:256
layout-a01009f142ecdc18.js:13093 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Trace - BrowserCacheManager.getActiveAccount: No active account filters cache schema found, looking for legacy schema
layout-a01009f142ecdc18.js:13093 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-browser@3.7.1 : Trace - BrowserCacheManager.getActiveAccount: No active account found
layout-a01009f142ecdc18.js:13084 [Fri, 26 Jan 2024 15:53:40 GMT] : [] : @azure/msal-react@2.0.10 : Info - useAccount - Updating account

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
{
    auth: {
        clientId: clientId,
        authority: 'https://login.microsoftonline.com/' + tenantId,
        redirectUri: redirectUri,
    },
    cache: {
        cacheLocation: 'sessionStorage',
        storeAuthStateInCookie: false,
    },
};
```

### Relevant Code Snippets

```javascript
export const loginRequest = {
    scopes: ['openid']
};

export class CustomNavigationClient extends NavigationClient {
    private router: AppRouterInstance;

    constructor(router: AppRouterInstance) {
        super();
        this.router = router;
    }

    /**
     * Navigates to other pages within the same web application
     * You can use the useRouter hook provided by next.js to take advantage of client-side routing
     * @param url
     * @param options
     */
    async navigateInternal(url, options) {
        const relativePath = url.replace(window.location.origin, '');

        if (options.noHistory) {
            this.router.replace(relativePath);
        } else {
            this.router.push(relativePath);
        }

        return false;
    }
}

const msalInstance: PublicClientApplication = new PublicClientApplication(msalConfig);
const msalInstancePromise = msalInstance.initialize();

export const AuthenticatedWrapper: React.FunctionComponent<PropsWithChildren> = (props: PropsWithChildren) => {
    const [instance, setInstance] = useState<PublicClientApplication>();
    const router = useRouter();

    useEffect(() => {
        msalInstancePromise
            .then(() => {
                const navigationClient = new CustomNavigationClient(router);
                // (Note: this doesn't seem to have any effect on the issue)
                msalInstance.setNavigationClient(navigationClient);
                setInstance(msalInstance);
            })
            .catch((error) => {
                console.error(error);
                throw new Error('Unable to initialize authentication client');
            });
    });

    if (!instance) {
        return null;
    }

    return (
        <MsalProvider instance={instance}>
            <MsalAuthenticationTemplate
                interactionType={InteractionType.Redirect}
                authenticationRequest={loginRequest}
            >
                <p>Hello!</p>
            </MsalAuthenticationTemplate>
        </MsalProvider>
    );
};
```

### Reproduction Steps

1. Set up an application using Next.js 14 & a MSALTemplate with a login type of redirect
2. Attempt to sign in
3. Error occurs after a successful redirect

### Expected Behavior

Login via a redirect works.

### Identity Provider

Entra ID (formerly Azure AD) / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

External (Customer)

**Comment by sunny0183** [comment]
MSAL redirect login works up to Nextjs v[14.0.4]

any versions after that (including 14.0.5-canaryXX) fails to acquire a token.

**Comment by timtucker-dte** [comment]
Updated -- it looks like after I simplified things I can reproduce it via both the client bundle and when running live.

Also tried waiting until the Next.js router was initialized before starting creation of the MSAL instance, but that didn't seem to have any effect:

`
export const MsalWrapper: React.FunctionComponent<PropsWithChildren> = (props: PropsWithChildren) => {
    const [instance, setInstance] = useState<PublicClientApplication>();
    const router = useRouter();

    useEffect(() => {
        if (!router) {
            return;
        }

        const msalInstance: PublicClientApplication = new PublicClientApplication(msalConfig);
        const navigationClient = new CustomNavigationClient(router);
        msalInstance.setNavigationClient(navigationClient);

        const msalInstancePromise = msalInstance.initialize();
        msalInstancePromise
            .then(() => {
                setInstance(msalInstance);
            })
            .catch((error) => {
                console.error(error);
                throw new Error('Unable to initialize authentication client');
            });
    }, [router]);

    if (!instance) {
        return null;
    }

    return <MsalProvider instance={instance}>{props.children}</MsalProvider>;
};
`

**Comment by timtucker-dte** [comment]
Confirmed locally:

This is definitely an issue with the new windowHistorySupport feature added in Next.js 14.0.5

Everything works fine if app-router.tsx has applyUrlFromHistoryPushReplace modified from:
**window.history.state.__PRIVATE_NEXTJS_INTERNALS_TREE**
to
**window.history.state?.__PRIVATE_NEXTJS_INTERNALS_TREE**

Pull request submitted to Next.js
https://github.com/vercel/next.js/pull/61395

**Comment by hectormmg** [comment]
@timtucker-dte thanks for opening the issue and submitting the PR to the Next.js repo. We'll keep an eye on it to close this when it's merged.

**Comment by olivierr91** [comment]
I have this issued as well. I cannot clear the location hash without NextJs crashing. Please fix.

**Comment by timtucker-dte** [comment]
Definitely still an issue, just waiting on the Next.js team to merge in the fix on their side

**Comment by KasperiP** [comment]
This is no longer issue in latest Next.js canary version 🥳 `14.1.1-canary.62`

**Comment by timtucker-dte** [comment]
As FYI, Next 14.1.1 is out, but includes critical bug fixes only, not everything on Canary.

Looks like we'll be waiting until 14.1.2 for it to get incorporated into a production release.
