### ISSUE TITLE
Calling acquireTokenSilent with refreshTokenExpirationOffsetSeconds results in error on iOS 17

### ISSUE THREAD

**Issue by Emprint** [AzureAD/microsoft-authentication-library-for-js#6858]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.7.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.11

### Public or Confidential Client?

Public

### Description

We are developing a PWA on Angular 16 and have been using MSAL since 2 years now.
As this application is meant to be used offline frequently, it is preferable for us that the session does not expires while the user is offline. Refresh tokens have normally a duration of 24 hours but this is only true when they are first created. If the user logged in first 10 hours ago, his refresh token will only be valid an additional 14 hours even if he is online now and even when using `forceRefresh` set to true.

We were glad to find that you have added support for `refreshTokenExpirationOffsetSeconds` in MSAL Angular 3.0.11 (documented in https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/8ba7a00c197ac1b83e5420ee560a4e2ba9bef919/lib/msal-browser/docs/token-lifetimes.md) as this allowed us to force updating the refresh token when the user is online to extend it to 24 hours from now and while this works well on desktop (tested on Chrome and Safari), it looks like there is an issue on iOS (at least version 17.2.1 and 17.3).

When calling `acquireTokenSilent` with `refreshTokenExpirationOffsetSeconds` as in the code snippet below (also tested when passing optional `account` parameter with the same invalid result) we get `InteractionRequiredAuthError: login_required: AADSTS50058` (complete error message below).

Note: if we just use `acquireTokenSilent` with `forceRefresh` and without `refreshTokenExpirationOffsetSeconds`, the result is successful, so it really is `refreshTokenExpirationOffsetSeconds` that is causing this issue.

### Error Message

InteractionRequiredAuthError: login_required: AADSTS50058: A silent sign-in request was sent but no user is signed in. The cookies used to represent the user's session were not sent in the request to Azure AD. This can happen if the user is using Internet Explorer or Edge, and the web app sending the silent sign-in request is in different IE security zone than the Azure AD endpoint (login.microsoftonline.com). Trace ID: 680fe8d7-f7cf-484f-8457-052377730000 Correlation ID: 846fa906-3adf-4ca0-917c-97dfc18f7f9b Timestamp: 2024-01-29 17:43:12Z

### MSAL Logs

```
[Log] [Mon, 29 Jan 2024 18:23:16 GMT] : [] : @azure/msal-browser@3.7.1 : Info - Emitting event: msal:loginStart (main.8bedf5fff99962b7.js, line 1)
[Info] Successfully preconnected to https://aadcdn.msauth.net/ (x2)
[Log] [Mon, 29 Jan 2024 18:23:23 GMT] : [] : @azure/msal-browser@3.7.1 : Info - Emitting event: msal:initializeStart (main.8bedf5fff99962b7.js, line 1)
[Log] [Mon, 29 Jan 2024 18:23:23 GMT] : [] : @azure/msal-browser@3.7.1 : Info - Emitting event: msal:initializeEnd (main.8bedf5fff99962b7.js, line 1)
[Log] [Mon, 29 Jan 2024 18:23:23 GMT] : [] : @azure/msal-browser@3.7.1 : Info - Emitting event: msal:handleRedirectStart (main.8bedf5fff99962b7.js, line 1)
[Log] [Mon, 29 Jan 2024 18:23:24 GMT] : [] : @azure/msal-browser@3.7.1 : Info - BrowserCacheManager: addTokenKey - idToken added to map (main.8bedf5fff99962b7.js, line 1)
[Log] [Mon, 29 Jan 2024 18:23:24 GMT] : [] : @azure/msal-browser@3.7.1 : Info - BrowserCacheManager: addTokenKey - accessToken added to map (main.8bedf5fff99962b7.js, line 1)
[Log] [Mon, 29 Jan 2024 18:23:24 GMT] : [] : @azure/msal-browser@3.7.1 : Info - BrowserCacheManager: addTokenKey - refreshToken added to map (main.8bedf5fff99962b7.js, line 1)
[Log] [Mon, 29 Jan 2024 18:23:24 GMT] : [] : @azure/msal-common@14.6.1 : Info - CacheManager:getIdToken - Returning ID token (main.8bedf5fff99962b7.js, line 1)
[Log] [Mon, 29 Jan 2024 18:23:24 GMT] : [] : @azure/msal-browser@3.7.1 : Info - Emitting event: msal:loginSuccess (main.8bedf5fff99962b7.js, line 1)
[Log] {eventType: "msal:loginSuccess", interactionType: "redirect", payload: Object, error: null, timestamp: 1706552604078} (main.8bedf5fff99962b7.js, line 1)
[Log] [Mon, 29 Jan 2024 18:23:24 GMT] : [] : @azure/msal-browser@3.7.1 : Info - Emitting event: msal:handleRedirectEnd (main.8bedf5fff99962b7.js, line 1)
[Log] [Mon, 29 Jan 2024 18:23:24 GMT] : [] : @azure/msal-common@14.6.1 : Info - CacheManager:getIdToken - Returning ID token (main.8bedf5fff99962b7.js, line 1)
[Log] [Mon, 29 Jan 2024 18:23:24 GMT] : [] : @azure/msal-common@14.6.1 : Info - CacheManager:getIdToken - Returning ID token (main.8bedf5fff99962b7.js, line 1)
[Log] [Mon, 29 Jan 2024 18:23:24 GMT] : [] : @azure/msal-common@14.6.1 : Info - CacheManager:getIdToken - Returning ID token (main.8bedf5fff99962b7.js, line 1)
[Log] [Mon, 29 Jan 2024 18:23:27 GMT] : [] : @azure/msal-common@14.6.1 : Info - CacheManager:getIdToken - Returning ID token (main.8bedf5fff99962b7.js, line 1)
[Log] [Mon, 29 Jan 2024 18:23:27 GMT] : [] : @azure/msal-common@14.6.1 : Info - CacheManager:getIdToken - Returning ID token (main.8bedf5fff99962b7.js, line 1)
[Log] [Mon, 29 Jan 2024 18:23:27 GMT] : [] : @azure/msal-browser@3.7.1 : Info - Emitting event: msal:acquireTokenStart (main.8bedf5fff99962b7.js, line 1)
[Log] [Mon, 29 Jan 2024 18:23:27 GMT] : [b5891f5d-232b-4241-830d-7ed29f581931] : @azure/msal-common@14.6.1 : Info - Token refresh is required due to cache outcome: 1 (main.8bedf5fff99962b7.js, line 1)
[Log] [Mon, 29 Jan 2024 18:23:27 GMT] : [] : @azure/msal-browser@3.7.1 : Info - Emitting event: msal:acquireTokenFromNetworkStart (main.8bedf5fff99962b7.js, line 1)
[Log] [Mon, 29 Jan 2024 18:23:27 GMT] : [] : @azure/msal-common@14.6.1 : Info - CacheManager:getRefreshToken - returning refresh token (main.8bedf5fff99962b7.js, line 1)
[Info] Successfully preconnected to https://login.microsoftonline.com/
[Log] [Mon, 29 Jan 2024 18:23:29 GMT] : [] : @azure/msal-common@14.6.1 : Info - CacheManager:getIdToken - Returning ID token (main.8bedf5fff99962b7.js, line 1)
[Log] [Mon, 29 Jan 2024 18:23:29 GMT] : [] : @azure/msal-browser@3.7.1 : Info - Emitting event: msal:initializeStart (main.8bedf5fff99962b7.js, line 1)
[Log] [Mon, 29 Jan 2024 18:23:29 GMT] : [] : @azure/msal-browser@3.7.1 : Info - Emitting event: msal:initializeEnd (main.8bedf5fff99962b7.js, line 1)
[Log] [Mon, 29 Jan 2024 18:23:29 GMT] : [] : @azure/msal-common@14.6.1 : Info - CacheManager:getIdToken - Returning ID token (main.8bedf5fff99962b7.js, line 1)
[Log] [Mon, 29 Jan 2024 18:23:29 GMT] : [] : @azure/msal-browser@3.7.1 : Info - Emitting event: msal:handleRedirectStart (main.8bedf5fff99962b7.js, line 1)
[Log] [Mon, 29 Jan 2024 18:23:29 GMT] : [caf64689-d68e-41d4-b395-ba162a57769c] : msal.js.browser@3.7.1 : Info - handleRedirectPromise called but there is no interaction in progress, returning null. (main.8bedf5fff99962b7.js, line 1)
[Log] [Mon, 29 Jan 2024 18:23:29 GMT] : [] : @azure/msal-browser@3.7.1 : Info - Emitting event: msal:handleRedirectEnd (main.8bedf5fff99962b7.js, line 1)
[Log] [Mon, 29 Jan 2024 18:23:29 GMT] : [] : @azure/msal-common@14.6.1 : Info - CacheManager:getIdToken - Returning ID token (main.8bedf5fff99962b7.js, line 1)
[Log] [Mon, 29 Jan 2024 18:23:29 GMT] : [] : @azure/msal-common@14.6.1 : Info - CacheManager:getIdToken - Returning ID token (main.8bedf5fff99962b7.js, line 1)
[Log] [Mon, 29 Jan 2024 18:23:29 GMT] : [] : @azure/msal-browser@3.7.1 : Info - Emitting event: msal:acquireTokenFailure (main.8bedf5fff99962b7.js, line 1)
[Error] ERROR – InteractionRequiredAuthError: login_required: AADSTS50058: A silent sign-in request was sent but no user is signed in. The cookies used to represent the user's session were not sent in the request to Azure AD. This can happen if the user is using Internet Explorer or Edge, and the web app sending the silent sign-in request is in different IE security zone than the Azure AD endpoint (login.microsoftonline.com). Trace ID: 5d37ff1a-49a3-4209-9b50-dcecb6910000 Correlation ID: b5891f5d-232b-4241-830d-7ed29f581931 Timestamp: 2024-01-29 18:23:28Z
InteractionRequiredAuthError: login_required: AADSTS50058: A silent sign-in request was sent but no user is signed in. The cookies used to represent the user's session were not sent in the request to Azure AD. This can happen if the user is using Internet Explorer or Edge, and the web app sending the silent sign-in request is in different IE security zone than the Azure AD endpoint (login.microsoftonline.com). Trace ID: 5d37ff1a-49a3-4209-9b50-dcecb6910000 Correlation ID: b5891f5d-232b-4241-830d-7ed29f581931 Timestamp: 2024-01-29 18:23:28Z
	handleError (main.8bedf5fff99962b7.js:1:52381)
	next (main.8bedf5fff99962b7.js:1:107577)
	next (main.8bedf5fff99962b7.js:1:3465)
	_next (main.8bedf5fff99962b7.js:1:3145)
	next (main.8bedf5fff99962b7.js:1:2837)
	(anonymous function) (main.8bedf5fff99962b7.js:1:5983)
	P (main.8bedf5fff99962b7.js:1:2589)
	next (main.8bedf5fff99962b7.js:1:5818)
	emit (main.8bedf5fff99962b7.js:1:52651)
	run (polyfills.f0db93497f9aeb64.js:1:1977)
	onHandleError (main.8bedf5fff99962b7.js:1:55276)
	runTask (polyfills.f0db93497f9aeb64.js:1:2653)
	invokeTask (polyfills.f0db93497f9aeb64.js:1:8266)
```

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
export const environment = {
    production: false,
    msalConfig: {
        auth: {
            clientId: 'Client_ID',
            authority: 'https://login.microsoftonline.com/Tenant_ID'
        }
    },
    apiConfig: {
        scopes: ['user.read'],
        uri: 'https://graph.microsoft.com/v1.0/me'
    }
};
```

### Relevant Code Snippets

```javascript
// app.component.html
<a mat-button (click)="refreshToken()" *ngIf="loginDisplay">Refresh Token</a>

// app.component.ts
refreshToken() {
  this.authService
  .acquireTokenSilent({
    scopes: [...environment.apiConfig.scopes],
    forceRefresh: true,
    refreshTokenExpirationOffsetSeconds: 24 * 60 * 60 // Ensures that token is always extended by 24 hours when online
  }).subscribe(result => {
    console.log('Refresh Token Result', result);
  })
}
```

### Reproduction Steps

1. Use code of 'MSAL Angular 16 Sample App' from https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v3-samples/angular16-sample-app
2. Add Refresh token button and function as in code snippets above
4. Build/Deploy the application and access it on an iOS device
5. Connect the device to your computer and observe network and console logs
6. Click on Login and then click on "Refresh Token"
7. The error above is visible in the console and in the network logs you can see a redirect to your app home page with the same error in the url parameter `#error`

### Expected Behavior

Expected successful response with extended refresh token as in desktop browsers

### Identity Provider

Entra ID (formerly Azure AD) / MSA

### Browsers Affected (Select all that apply)

Safari

### Source

External (Customer)

**Comment by tnorling** [comment]
This is due to 3P cookies being blocked. 3P cookies are **required** in order to obtain a new refresh token (with or without the new param). The reason forceRefresh is working is because it's simply exchanging the cached RT for a new access token, which will not extend your RT.

Unfortunately there's no workaround to 3P cookie restrictions other than to invoke an interactive API (popup/redirect) when you get an interactionRequired error.

**Comment by Emprint** [comment]
Thank you @tnorling for the reply.

We will investigate more on iOS to see which device settings could be blocking third parties cookies but I must say this is really annoying, I have tested on several devices (company devices or not) and they all show this behavior, hence rendering silent extension of the Refresh Token basically unusable where we need it most (on iOS that is).

**Comment by Emprint** [comment]
The setting that is causing this is in Settings > Safari > under "Privacy & Security" section, "Prevent Cross-Site Tracking" should be off. The issue is that this setting is important for user privacy and most of them have this enabled, it's probably even on by default either from Apple or from our company policy (that we can change of course).

Ideally we could leave it enabled, for example for marketing cookies, and have exceptions per domains, for sites like Authentication providers, but obviously this feature would have to come from Apple/Webkit team.

**Comment by zecka** [comment]
> This is due to 3P cookies being blocked. 3P cookies are **required** in order to obtain a new refresh token (with or without the new param). The reason forceRefresh is working is because it's simply exchanging the cached RT for a new access token, which will not extend your RT.
> 
> Unfortunately there's no workaround to 3P cookie restrictions other than to invoke an interactive API (popup/redirect) when you get an interactionRequired error.

So to resume:
With Entra ID on Safari with default settings, **there is no way to keep a connection active for more than 24 hours** if the user does not open the app within the last 24 hours.

@tnorling do you agree ?

https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Known-issue-on-Safari

My main concern is to find a way for users not to have to re-enter their credentials after 24 hours of inactivity. I don't understand how third-party cookies are related to this, given that in the case of a login redirect, the user ultimately ends up on the Azure domain. Why is the session terminated after 24 hours of inactivity, even when the user lands on the Azure domain?
