### ISSUE TITLE
How to use Msal with keycloak

### ISSUE THREAD

**Issue by Manjukb** [AzureAD/microsoft-authentication-library-for-js#6869]
### Core Library

MSAL.js (@azure/msal-browser)

### Wrapper Library

MSAL React (@azure/msal-react)

### Public or Confidential Client?

Public

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js

### Description

Hi 
im trying to integrate keyckock with msal library facing multiple issues 

- The acquireTokenSilent method is not working. Instead, we have to use acquireTokenPopup to obtain the token.
- The logout functionality is not working as expected.
- After the token expires, how can we refresh it using the refresh token?

when trying to logout getting end_session_endpoint_not_supported error (attached screenshot) 
![Uploading chrome_hRxyWOGKWvscreen.png…]()

here is the configuration im using to initialize msal 
```
export const keyclockConfig = {
  auth: {
    protocolMode: msal.ProtocolMode.OIDC,
    autoRefreshToken: true,
    authorityMetadata: JSON.stringify({
      authorization_endpoint:
        `${process.env.REACT_APP_KEYCLOAK_URL}/realms/nec/protocol/openid-connect/auth`,
      token_endpoint:
        `${process.env.REACT_APP_KEYCLOAK_URL}/realms/nec/protocol/openid-connect/token`,
      issuer: `${process.env.REACT_APP_KEYCLOAK_URL}/realms/nec`,
      userinfo_endpoint:
        `${process.env.REACT_APP_KEYCLOAK_URL}/realms/nec/protocol/openid-connect/userinfo`,
    }),
    authority: `${process.env.REACT_APP_KEYCLOAK_URL}/realms/nec/protocol/openid-connect/logout`,
    clientId: "ibwweb",
    knownAuthorities: [`${process.env.REACT_APP_KEYCLOAK_URL}/realms/nec`],
    navigateToLoginRequestUrl: true
  },
  cache: {
    cacheLocation: "localStorage", // Configures cache location. "sessionStorage" is more secure, but "localStorage" gives you SSO between tabs.
    storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
  },
  system: {
    allowNativeBroker: false,
    loggerOptions: {
      piiLoggingEnabled: true,
      logLevel: LogLevel.Verbose, // Adjust log level based on your needs
    },
  },
}
```

**Comment by tnorling** [comment]
> The acquireTokenSilent method is not working. Instead, we have to use acquireTokenPopup to obtain the token.

Please provide more detail about what specifically is not working

> The logout functionality is not working as expected.

You need to provide the end_session_endpoint in your authorityMetadata config

> After the token expires, how can we refresh it using the refresh token?

acquireTokenSilent will make use of the cache & exchange refresh tokens for new access tokens when needed

**Comment by Manjukb** [comment]
i get an error if i use acquireTokenSilent 
I have uploaded a screenshot [here ](https://app.gemoo.com/share/image-annotation/613432884832837632?codeId=PajZYd8zgRgJm&origin=imageurlgenerator&card=613432882169454592) with error 

so if acquireTokenSilent works it automatically refreshes the token ?

**Comment by tnorling** [comment]
You can't use acquireTokenSilent until you're signed in. When you get InteractionRequired you need to fallback to either acquireTokenPopup or acquireTokenRedirect

**Comment by Manjukb** [comment]
is it mandatory that third party cookies should be enabled ??
i see if i enable it acquireTokenSilent works fine if its blocked it fails and keep looping 

below is example code 

> try {
          const silentRequest = {
            scopes: ['openid email profile'],
            account: activeAccount[0],
            forceRefresh: true,
            CacheLookupPolicy: CacheLookupPolicy.Default
          };
          const response = await instance.acquireTokenSilent(silentRequest).catch(async (error) => {
            if (error instanceof InteractionRequiredAuthError) {
              // fallback to interaction when silent call fails
              await instance.acquireTokenRedirect(silentRequest);
            }
          });
        } catch (error) {
          console.log('error', error);
          // Handle specific errors or provide more information for debugging
        } 
      }

**Comment by tnorling** [comment]
It's not mandatory but users that block 3P cookies will see more interactive prompts than users who don't.

I also would not recommend setting `forceRefresh` to true or setting the `CacheLookupPolicy` unless you have a specific requirements to get a brand new token and/or skip certain stages of the flow, most apps do not need to use these parameters.
