### ISSUE TITLE
B2C login loop infinitely, The getRedirectResponseHash method cannot get state value even the B2C response include the value #state=eyJpZ...

### ISSUE THREAD

**Issue by LuBu0505** [AzureAD/microsoft-authentication-library-for-js#6870]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.38.3

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.5.12

### Public or Confidential Client?

Public

### Description

login use met infinite loop. B2C already return the State value, But the MSAL cannot handler it. 

**The error condition：**
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/69841770/a501712d-8399-4719-89e4-59a5bf1a5f96)

**The Customer modify code part:**
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/69841770/0c3ea11d-9e86-4b38-9b8c-34bf9ef9004c)

**The MSAL SDK version:** 
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/69841770/71ad9a40-0fbc-4d4a-8f32-511801bfabaa)

### Error Message

No Error show , just infinite loop.

### MSAL Logs

The error message is 

`MSAL.JS.BROWSER@2.38.2: Info - handleRedirectPromise did not detect a response hash as a result of a redirect. Cleaning temporary cache. `

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/69841770/4312858d-50f6-4827-85ec-c4724930ae9d)

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
Reference the Docs: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/msal-browser-v2.32.3-patch-release/lib/msal-angular/docs/v2-docs/redirects.md 


Part2 : Subscribing to handleRedirectObservable manually
```

### Relevant Code Snippets

```javascript
NA
```

### Reproduction Steps

NA

### Expected Behavior

Login Successfully.  and The State have value. Like the below screenshot:
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/69841770/09cd7573-2145-4717-9818-a9b141241421)

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

External (Customer)

**Comment by tnorling** [comment]
Something, probably your router, has removed everything after `state`, you can see this in your URL bar. Unfortunately if the information isn't there MSAL can't handle the response. You'll need to track down where the hash is being changed and stop it from doing so
