### ISSUE TITLE
Allow the ability to exclude default scopes for Angular

### ISSUE THREAD

**Issue by gmiked** [AzureAD/microsoft-authentication-library-for-js#6881]
### Core Library

MSAL.js (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Public or Confidential Client?

Public

### Description

I understand python's version of MSAL allows to exclude certain default scopes like offline_access as seen here https://learn.microsoft.com/en-us/python/api/msal/msal.application.clientapplication?view=msal-py-latest.  Can the same be added to Angular's version of MSAL?

### Source

External (Customer)

**Comment by lalimasharda** [comment]
Hey @gmiked we do not currently have any plans to support excluding any of the default scopes. The offline_access scope is required for getting refresh tokens which are used in basic SPA flows. Tagging a similar discussion from before: #3649

**Comment by kvisscher** [comment]
Posting this work-a-round for anybody hitting this through a search engine: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/3649#issuecomment-2129771007
