### ISSUE TITLE
redirectCallback method is not called if navigateToLoginRequestUrl is false

### ISSUE THREAD

**Issue by kosjanne** [AzureAD/microsoft-authentication-library-for-js#689]
## I'm submitting a...

<pre><code>
[x ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x ] Chrome version 73
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 1.0.0

## Current behavior

If I set navigateToLoginRequestUrl to false, redirectCallback is not called.

## Expected behavior

I would expect that my redirectCallback method gets called even if navigateToLoginRequestUrl is false, as it was working still in 0.2.4 version.

## Minimal reproduction of the problem with instructions

Create user agent as follows:
const msalConfig: Msal.Configuration = {
      auth: {
        ...
        navigateToLoginRequestUrl: false
      }};
userAgentApplication = new Msal.UserAgentApplication(msalConfig);
userAgentApplication.handleRedirectCallback(authCallback);

authCallback method will never get called after we return from userAgentApplication.loginRedirect(…);
</code></pre>

**Comment by pkanher617** [comment]
@kosjanne Thank you for the submission. I was able to reproduce this, looking at the fix now.

**Comment by pkanher617** [comment]
@kosjanne I have introduced a PR to fix this. Feel free to pull the branch and test.
