### ISSUE TITLE
How to decode token expiresOn to local time 

### ISSUE THREAD

**Issue by sgidd** [AzureAD/microsoft-authentication-library-for-js#6897]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.8.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

^1.0.0-alpha.1

### Public or Confidential Client?

Public

### Description

I want to capture the expiration time of token and whenever refresh happens would like to update the user login timestamp to refresh time.

expire date is in format expiresOn: "1707971937", so would like to know how to decode it to the local time.

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
// Config object to be passed to Msal on creation
export const msalConfig = {
  auth: {
    clientId: 'https://rds-cbpas-np.solutions.iqvia.com',
    authority:
      'https://login.microsoftonline.com/5989ece0-f90e-40bf-9c79-1a7beccdb861',
    redirectUri: `${window.location.origin}/auth/return`,
    navigateToLoginRequestUrl: false,
  },
  cache: {
    cacheLocation: 'localStorage', // This configures where your cache will be stored
    storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
  },
  system: {
    loggerOptions: {
      loggerCallback: (level, message, containsPii) => {
        if (containsPii) {
          return;
        }
        switch (level) {
          case LogLevel.Error:
            console.error(message);
            return;
          case LogLevel.Info:
            console.info(message);
            return;
          case LogLevel.Verbose:
            console.debug(message);
            return;
          case LogLevel.Warning:
            console.warn(message);
            return;
        }
      },
      logLevel: LogLevel.Verbose,
    },
    iframeHashTimeout: 30000,
  },
};
```

### Relevant Code Snippets

```javascript
NA
```

### Reproduction Steps

q. NA

### Expected Behavior

should get the expiresOn as normal date string.

### Identity Provider

Entra ID (formerly Azure AD) / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by tnorling** [comment]
expiresOn is a UTC timestamp, converting to different formats and timezones is outside the scope of MSAL.js. I recommend searching StackOverflow as there are several ways to do this that have been shared and discussed there.
