### ISSUE TITLE
Session Logout information in details

### ISSUE THREAD

**Issue by sgidd** [AzureAD/microsoft-authentication-library-for-js#6898]
### Core Library

MSAL.js (@azure/msal-browser)

### Wrapper Library

MSAL React (@azure/msal-react)

### Public or Confidential Client?

Public

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/getting-started.md

### Description

Once the user is logged into the application how long session keeps active when tab is idle ? i am seeing even next day when i reload the tab i am still signed into the application. so can you please help me understand how session works once login and when does it gets expires.

**Comment by tnorling** [comment]
Access tokens are valid for 1 hour and Refresh tokens are valid for 24 hours. More information about token lifetimes [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/token-lifetimes.md)
