### ISSUE TITLE
Id token is not returned from a cache storage (PublicClientApplication.getActiveAccount)

### ISSUE THREAD

**Issue by Stralos** [AzureAD/microsoft-authentication-library-for-js#6900]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.9.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

With a sweaping changes that happend in version 3.5.0 a major breaking change / bug was introduced.

ID token is no longer being returned when accesing user information from the cache (using getActiveAccount())

The ID token is clearly stored inside my my session storage:
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/9497563/fcd63e42-a59d-4a1a-a051-80338c76004b)

But when accessing the current active account, it is not provided to me.

This bug was introduced in [this pull request](https://github.com/AzureAD/microsoft-authentication-library-for-js/commit/392020bee299d01d14db2907da0cab681a3fbdc3)

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/9497563/16922f29-05a0-4f5b-94aa-78a7d07f0758)

The important line is 306 in Cache manager:

```
{
...
  accountInfo.idToken = idToken.secret;
...
}
```
this line would set the idToken from the cache to the accountInfo object, but it was removed !

[link to PR Lines](https://github.com/AzureAD/microsoft-authentication-library-for-js/commit/392020bee299d01d14db2907da0cab681a3fbdc3#diff-9386241630b242163033adcf355efb44fbb1f78fc9516e3553f226e4a5c0738bL306)

one would expect that maybe this logic got moved to `updateAccountTenantProfileData`:
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/9497563/0a2e6fc0-668a-4ace-86fa-87245ffe01ca)

But as you can see that is not the case.

This change makes logout imposible as it requires a idTokenHint, witch I am not able to get when accessing the user info from.

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
Not important for this bug
```

### Relevant Code Snippets

```javascript
const result = new PublicClientApplication({ auth });
    result.addEventCallback((message) => {
      if (message.eventType !== EventType.LOGIN_SUCCESS) {
        return;
      }
      const payload = message.payload as AuthenticationResult;
      result.setActiveAccount(payload.account);
      const account = result.getActiveAccount() // no IdToken here
     });
    });
```

### Reproduction Steps

Log in to your application using msal-browser
set activeUser()
call getActiveUser()
see no idToken in the return object

### Expected Behavior

I expect to get idToken that is stored inside my session cache when calling getActiveUser().

### Identity Provider

Other

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari

### Source

External (Customer)

**Comment by hectormmg** [comment]
@Stralos thanks for opening the issue. I'll put a fix in to include a matching ID token in the account object returned. Please note that you may still see account objects returned without the ID token secret if there is no matching ID token for the specific tenant profile requested.

If you need a workaround in the meantime, you can pass the account into acquireTokenSilent with default scopes and get the ID token (which is actually the most correct way to get the ID token because acquireTokenSIlent will get an ID token from the network if there's no matching ID token in the cache).

**Comment by Stralos** [comment]
I am using an older version that works atm (3.5.0 is right before the change).

I'll consider using the acquireTokenSilent, but I need to think a bit

**Comment by Stralos** [comment]
if acquireTokenSilent is the correct approach, the documentation should be updated [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md#logging-out)
