### ISSUE TITLE
Can't access profile flow directly after password reset flow

### ISSUE THREAD

**Issue by volodya-marchenko-nl** [AzureAD/microsoft-authentication-library-for-js#6902]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.7.1

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.0.10

### Public or Confidential Client?

Public

### Description

I have setup B2C authentication in my React app. Everything seems to be working. After a user successfully resets their password the user is automatically logged into the app. However,  i can't access profile flow directly without re-login, Is this the expected behavior or is there something in my code that needs to be changed? I would expect that the user should be able access the profile flow since it's logged into the app.  

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
auth: {
    clientId: "33a06ec5-1d70-4a77-926e-dabb3444d6c5",
    authority: https://testb2ctmrw.b2clogin.com/testb2ctmrw.onmicrosoft.com/B2C_1_SignUpAndSignIn,
  },
    cache: {
        cacheLocation: "localStorage"
    },
```

### Relevant Code Snippets

```javascript
import { authScopes, b2cPolicies } from "@/authConfig";
import {
  AccountInfo,
  InteractionStatus,
  PopupRequest,
} from "@azure/msal-browser";
import {
  AuthenticatedTemplate,
  UnauthenticatedTemplate,
  useIsAuthenticated,
  useMsal,
} from "@azure/msal-react";

export default function Home() {
  const { instance, inProgress } = useMsal();
  const account = instance.getActiveAccount() as AccountInfo;

  const isAuthenticated = useIsAuthenticated();

  const handleLogin = () => {
    instance
      .loginPopup(authScopes)
      .then((response) => {
        console.log("Login successful!", response);
        instance.setActiveAccount(response.account);
      })
      .catch(function (error) {
        console.log(error);
      });
  };

  const handleLogout = () => {
    instance
      .logoutPopup(authScopes)
      .then(() => {})
      .catch(function (error) {
        console.log(error);
      });
  };

  const handleProfileEdit = () => {
    if (isAuthenticated && inProgress === InteractionStatus.None) {
      instance
        .acquireTokenPopup(b2cPolicies.authorities.editProfile as PopupRequest)
        .then((response) => {
          console.log("Update profile successful!", response);
          instance.setActiveAccount(response.account);
        })
        .catch(function (error) {
          console.log(error);
        });
    }
  };

  return (
    <center>
      <AuthenticatedTemplate>
        <h2>Welcome {account?.name} - You are logged in!</h2>
        <textarea
          rows={20}
          cols={150}
          value={JSON.stringify(account, null, 2)}
        />
        <hr />
        <button onClick={handleProfileEdit}>Update Profile</button>&nbsp;
        <button onClick={() => handleLogout()}>Logout</button>
      </AuthenticatedTemplate>
      <UnauthenticatedTemplate>
        <h2>Sign in with your email address</h2>

        <button onClick={() => handleLogin()}>Login</button>
      </UnauthenticatedTemplate>
    </center>
  );
}
```

### Reproduction Steps

1. User run Reset Password flow (integrated into Login / Signup flow)
2. User logged into app
3. User can't  access profile flow without re-login

### Expected Behavior

1. User run Reset Password flow
2. User logged into app
3. User can access profile flow without re-login

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome, Safari

### Source

External (Customer)

**Comment by tnorling** [comment]
This is a question best answered by the B2C service and may be policy dependent. I would recommend [opening a ticket with B2C support](https://learn.microsoft.com/en-us/azure/active-directory-b2c/find-help-open-support-ticket) for assistance.
