### ISSUE TITLE
Login and Token acquire flow using acquire token redirect

### ISSUE THREAD

**Issue by mansivai** [AzureAD/microsoft-authentication-library-for-js#6907]
### Core Library

MSAL.js (@azure/msal-browser)

### Wrapper Library

MSAL React (@azure/msal-react)

### Public or Confidential Client?

Public

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/acquire-token.md#acquiring-an-access-token

### Description

I am using MSAL react to login a user and acquire access token using the acquireTokenRedirect since acquireTokenSilent is not working for this as user consent is required.
I am not able to get the token as well as the redirect doesn't stop till it shows a screen which displays, not able to login.  

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/51209422/74436e7b-ead7-4f0d-bedb-90f19e1f5439)

User Login
```
const isAuthenticated = useIsAuthenticated();
  const { login, error } = useMsalAuthentication(InteractionType.Silent, loginRequest);

//Token Acquisition

useEffect(() => {
    async function TokenRequest() {
      if (isAuthenticated && inProgress === InteractionStatus.None) {
        try {
          const response = await instance.acquireTokenRedirect(tokenRequest);
          console.log("Redirecting for interactive token acquisition..."); 
          sessionStorage.setItem('accessToken', response.accessToken);
        } catch (error) {
          console.error('Error occurred:', error);
        }
      }
    TokenRequest();
  }, [isAuthenticated, inProgress]);
```

**Comment by tnorling** [comment]
> if (isAuthenticated && inProgress === InteractionStatus.None) {
        try {
          const response = await instance.acquireTokenRedirect(tokenRequest);

This is going to cause a loop and you're likely getting an error because you're looping. Every time you hit your application you will redirect to the sign in screen and back.

> acquireTokenSilent is not working for this as user consent is required.

Consent is only required once per user per scope. If the user is already signed in you should attempt acquireTokenSilent and if that throws with interactionRequired, fallback to redirect. If the user is not yet signed in you can directly try redirect.

**Comment by mansivai** [comment]
what changes do I need to make in order to prevent the loop?
can you suggest documentation I can refer for login and token acquisition using redirect

**Comment by tnorling** [comment]
You can use the `useMsalAuthentication` hook or wrap your protected component in `MsalAuthenticationTemplate` - docs [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-react/docs/getting-started.md#protecting-components) and comprehensive msal-react samples [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples)
