### ISSUE TITLE
Closing logout account picker window does not reject the promise / notify the user

### ISSUE THREAD

**Issue by deleted-avaya** [AzureAD/microsoft-authentication-library-for-js#6908]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.10.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

As an application developer, I want to differentiate between successful and canceled logout attempts.
I want to catch the error when logout window is closed by user to prevent executing actions (business logic) that should be executed only after successful logout.

Steps to reproduce:
1. Login with `PublicClientApplication.loginPopup(...)`
2. Open logout popup via `PublicClientApplication.logoutPopup({account})` with your active account as account
3. Close the "account picker" popup window.

Expected result:
`PublicClientApplication.logoutPopup` promise rejects with `user_cancelled` reason like `loginPopup` does.

Actual result:
`PublicClientApplication.logoutPopup` promise resolves.

Debugging 
I believe the issues comes from the fact that the `logoutPopupAsync` function [PopupClient.ts#L483](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/src/interaction_client/PopupClient.ts#L483) ignores the promise being rejected from the `monitorPopupForHash` function in [PopupClient.ts#L577](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/src/interaction_client/PopupClient.ts#L577).

### Error Message

There is no error message I receive. The MSAL logs are shared below.

### MSAL Logs

[Tue, 20 Feb 2024 10:50:54 GMT] : [018dc623-ab85-70bc-a256-7d9e1f04606f] : msal.js.browser@3.10.0 : Error - PopupHandler.monitorPopupForHash - window closed

[Tue, 20 Feb 2024 10:50:54 GMT] : [018dc623-ab85-70bc-a256-7d9e1f04606f] : msal.js.browser@3.10.0 : Verbose - No main window navigation requested

[Tue, 20 Feb 2024 10:50:54 GMT] : [] : @azure/msal-browser@3.10.0 : Info - Emitting event: msal:logoutEnd

[Tue, 20 Feb 2024 10:50:54 GMT] : [] : @azure/msal-browser@3.10.0 : Verbose - Emitting event to callback 018dc623-7300-7339-98ca-5cff017f04dc: msal:logoutEnd

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
{
      auth: {
        authority: <auhority_domain>,
        redirectUri: <redirect_uri>,
        clientId: <client_id>,,
      },
      cache: {
        cacheLocation: 'localStorage',
        storeAuthStateInCookie: false,
      },
      system: {
        pollIntervalMilliseconds: 15,
      },
}
```

### Relevant Code Snippets

```javascript
// Login:
const res = await msalInstance.loginPopup(requestScope);
msalInstance.setActiveAccount(res.account);


// Logout:
const account = msalInstance.getActiveAccount();
const res = await msalInstance.logoutPopup({ account });
```

### Reproduction Steps

1. Login with PublicClientApplication.loginPopup(...)
2. Open logout popup via PublicClientApplication.logoutPopup({account}) with your active account as account
3. Close the "account picker" popup window.

### Expected Behavior

User notified about window being closed / logout cancelled.

### Identity Provider

Entra ID (formerly Azure AD) / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari

### Source

External (Customer)

**Comment by tnorling** [comment]
Server logout is best effort by design. Clearing the client cache is sufficient for determining that the request was successful as the application no longer has tokens or other artifacts for the user. Can you help us understand why this is not sufficient for your use case? 

In a pinch you can always use logoutRedirect with an `onRedirectNavigate` callback to implement any custom logout handling, such as opening a popup to the logout url and throwing if it's closed.

**Comment by maharleeeka** [comment]
> Server logout is best effort by design. Clearing the client cache is sufficient for determining that the request was successful as the application no longer has tokens or other artifacts for the user. Can you help us understand why this is not sufficient for your use case?
> 
> In a pinch you can always use logoutRedirect with an `onRedirectNavigate` callback to implement any custom logout handling, such as opening a popup to the logout url and throwing if it's closed.

Hi, piggybacking on this post since I am in a similar situation. Here's my current logout function. 


  ```
const signOutUser = async () => {
    try {
      await instance.logoutPopup();
      dispatch(updateIsAuthenticated(false));
      dispatch(setUser(null));
      navigate(appRoutes.LOGIN);
    } catch (error) {
      alert("user cancelled")
    }
  };
```

My expectation is that when the popup is closed and logout is essentially cancelled, these parts  in the code should not be triggered but for some reason, it pushes through. 

```
dispatch(updateIsAuthenticated(false));
dispatch(setUser(null));
navigate(appRoutes.LOGIN);
```

I'd greatly appreciate any help, as I might have been doing it wrong. Thank you very much!

**Comment by deleted-avaya** [comment]
> Server logout is best effort by design. Clearing the client cache is sufficient for determining that the request was successful as the application no longer has tokens or other artifacts for the user. Can you help us understand why this is not sufficient for your use case?
> 
> In a pinch you can always use logoutRedirect with an `onRedirectNavigate` callback to implement any custom logout handling, such as opening a popup to the logout url and throwing if it's closed.

The use case is the following:
Application with msal is a micro-frontend app embedded on the page,
1. User logs in the main app (MS Auth may or may not be involved)
2. User logs in the "widget" app with MSFT user identity A
3. User tries to sign-out from the widget
4. User cancels the logout popup. Application reacts as user is signed out.
5. User wants to login to the widget with MSFT user identity B. User is signed in with account A, without ask of credentials.

We are aware of msal prompt `login` option. We consider it's not a good fit for us. The problem is with "canceled" part that counts as successful logout.

**Comment by tnorling** [comment]
We actually never guarantee that MSAL's state will be perfectly in sync with the server state, in fact it's pretty common for them not to be. All of MSAL's APIs are specifically scoped to the current application's context, as far as it's concerned as long as a user account was cached a login is successful and as long as it was removed a logout is successful - the current server state is irrelevant. You could just as easily get into the same situation you described if the user completes the signout and then signs back into that account in another tab/site before doing step 5 above.

While I agree it seems counterintuitive to emit success when the popup was closed, I'm not convinced that changing this behavior really solves your underlying problem. That problem being that when exactly one account is signed in it will be auto-selected by the service. That is true regardless of whether you're accessing the site for the first time or attempting to switch accounts. That is what the prompt=select_account parameter is for. This parameter tells the service "please show me the account picker" - can you help me understand why you feel setting the prompt is not a good option?

**Comment by deleted-avaya** [comment]
Hi @tnorling 
Thank you for such a detailed explanation!

> can you help me understand why you feel setting the prompt is not a good option?
It's breaks one of the use cases defined by the business.

We ended up with suggesting users to logout from both applications and closing the browser session.
I'm good with closing this ticket.
Thank you again!
