### ISSUE TITLE
After refreshing the Page, msal account and all other details become null. using @azure/msal-react 2.0.8 and @azure/msal-react 3.9.0

### ISSUE THREAD

**Issue by anujKumarZe** [AzureAD/microsoft-authentication-library-for-js#6911]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.9.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.0.8

### Public or Confidential Client?

Confidential

### Description

I have MS login option and setting up MsalProvider dynamically. When user choose to login via Outlook it works fine. but after refreshing page all the details relates to Msal i.e activeAccount, isAuthenticated, accounts becomes null. which in turn causes issue while trying to call acquireTokenSilent.

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/148355895/30607e04-2ec4-4b44-a3a0-e801c1c6800c)

### MSAL Logs

Since everything is null , i cannot see any logs.

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
{
```

### Relevant Code Snippets

```javascript
const getToken = async () => {
    await instance.initialize();
    const account = accounts[0];
    const tokenRequest = {
      account: account,
      scopes: ["User.read"],
    };

    try {
      const token = await instance.acquireTokenSilent(tokenRequest);
      console.log("Token refreshed:", token.accessToken);
      localStorage.setItem("idToken", JSON.stringify(token.idToken));
    } catch (error) {
      console.error("Failed to refresh token:", error);
    }
  };

  const authRedirect = async () => {
    try {
      await instance.initialize();
      const activeAccount = instance.getActiveAccount();

      if (activeAccount != null || !isAuthenticated) {
        const loginResult = await instance.loginPopup();
        await instance.handleRedirectPromise();
        localStorage.setItem("idToken", JSON.stringify(loginResult.idToken));
        console.log("auth result", loginResult);
      }
      await instance.handleRedirectPromise();
    } catch (error) {
      console.log("error while login in with msal", error);
      // navigate("auth/login");
    }
  };

  useEffect(() => {
    const activeAccount = instance.getActiveAccount();
    console.log({ inProgress, activeAccount, isAuthenticated });
    if (inProgress === InteractionStatus.None && activeAccount != null) {
      getToken();
    } else {
      authRedirect();
    }

    isAuthenticated && redirectOnSuccess();
  }, [inProgress, instance, isAuthenticated]);
```

### Reproduction Steps

login via outllook.

refresh the page. 

all msal related Variables will become null.

### Expected Behavior

UserData should Persist even after page refresh.

### Identity Provider

Entra ID (formerly Azure AD) / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Safari

### Source

External (Customer)

**Comment by hectormmg** [comment]
@anujKumarZe can you please add your MSAL config? If you've configured the cache to use "MemoryStorage" this would be expected behavior, please make sure you're using one of the refresh-persistent options like "SessionStorage" or "LocalStorage" Also, you should be able to add verbose logs regardless of whether MSAL has tokens or accounts or not.

**Comment by anujKumarZe** [comment]
Hi @hectormmg I am setting up this Msal Config dynamically.

`import { LogLevel } from "@azure/msal-browser";
import { SSOConfig } from "../interfaces/org-config.interface";

export const getOutlookConfig = (config: SSOConfig, org_slug: string) => ({
  auth: {
    clientId: config.outlookClientId,
    authority: `https://login.microsoftonline.com/${config.outlookTenantId}`,
    redirectUri: `${window.location.protocol}//${window.location.host}/org/${org_slug}/auth/outlook`,
  },
  cache: {
    cacheLocation: "sessionStorage", // This configures where your cache will be stored
    storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
  },
  system: {
    loggerOptions: {
      loggerCallback: (level: any, message: string, containsPii: any) => {
        if (containsPii) {
          return;
        }
        switch (level) {
          case LogLevel.Error:
            console.error(message);
            return;
          case LogLevel.Info:
            console.info(message);
            return;
          case LogLevel.Verbose:
            console.debug(message);
            return;
          case LogLevel.Warning:
            console.warn(message);
            return;
          default:
            return;
        }
      },
    },
    allowNativeBroker: true,
    tokenRenewalOffsetSeconds: 300,
  },
});

export const loginRequest = {
  scopes: ["User.Read"],
};

export const graphConfig = {
  graphMeEndpoint: "https://graph.microsoft.com/v1.0/me",
};
`

**Comment by tnorling** [comment]
Please check sessionStorage before and after the refresh - are the MSAL storage entries present?
