### ISSUE TITLE
Enable logoutRedirect to use location.replace instead of location.href

### ISSUE THREAD

**Issue by CeciliaSilvera** [AzureAD/microsoft-authentication-library-for-js#6913]
### Core Library

MSAL.js (@azure/msal-browser)

### Wrapper Library

Not Applicable

### Public or Confidential Client?

Public

### Description

By default `msal-browser` uses `location.href` for the `logoutRedirect` as the documentation states. This is problematic since that means the user can click the browser back-button post logout to return to the previous page. Using `location.replace` would remove the previous page by replacing it with the provided `postLogoutRedirectUrl`

To achieve the same behavior with the current version of `msal-browser` one can disable the redirect by returning `false` for `onRedirectNavigate` and handle the redirect manually as the next step.

It would be nice if this was handled by the package instead either configurable or to default use `location.replace` instead of `location.href`

### Source

External (Customer)

**Comment by tnorling** [comment]
You can override the method used for navigation by providing a `NavigationClient` - more information [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/navigation.md)
