### ISSUE TITLE
Address "Cancellation Token" Inconsistencies in MSAL-Node's HttpClient

### ISSUE THREAD

**Issue by Robbie-Microsoft** [AzureAD/microsoft-authentication-library-for-js#6916]
### Core Library

MSAL Node (@azure/msal-node)

### Wrapper Library

Not Applicable

### Public or Confidential Client?

Confidential

### Description

The INetworkModule in msal-node defines get and post requests as:

```
sendGetRequestAsync<T>(
        url: string,
        options?: NetworkRequestOptions,
        cancellationToken?: number
    ): Promise<NetworkResponse<T>>;
```

```
sendPostRequestAsync<T>(
        url: string,
        options?: NetworkRequestOptions
    ): Promise<NetworkResponse<T>>;
```

Notice, the only the get method allows for an optional cancellation token.

In msal-node's HttpClient, which extends INetworkModule, the get and post methods are redefined as:

```
async sendGetRequestAsync<T>(
        url: string,
        options?: NetworkRequestOptions
    ): Promise<NetworkResponse<T>> {
```

```
async sendPostRequestAsync<T>(
        url: string,
        options?: NetworkRequestOptions,
        cancellationToken?: number
    ): Promise<NetworkResponse<T>> {
```

Notice that now only the post method accepts an optional cancellation token.

### Source

Internal (Microsoft)

**Comment by bgavrilMS** [comment]
Let's not accept this cancelltion token for now. Ignore.
