### ISSUE TITLE
calling loginPopup for a "switch account" experience

### ISSUE THREAD

**Issue by SaeedAkhter-MSFT** [AzureAD/microsoft-authentication-library-for-js#692]
Most of the time, I'm signed in as one user, and I want skip the account selection screen and just sign in quickly.  However, if an app wants to build both a "Sign In" button and a "Switch Account" button, we want to accommodate an app to force prompt=select_account.

On the request object, there is a prompt: parameter that can be set by the developer.  However, it's ignored unless one of (loginHint, sid, account) is also set.  Is there a reason for this requirement?

Example, this does not work:

```
            <button id="SwitchAccount" onclick="switchAccount()">Switch Account</button>
<script>
...
    var requestObj = {
        scopes: ["user.read"],
        prompt: "select_account"
    };

    function switchAccount() {
        myMSALObj.loginPopup(requestObj).then(function (loginResponse) {
            //Successful login
            showWelcomeMessage();
        }).catch(function (error) {
            //Please check the console for errors
            console.log(error);
        });
    }
```

However, there is a workaround of just passing in a non-null value for loginHint and it starts working.

```
    var requestObj = {
        scopes: ["user.read"],
        prompt: "select_account",
        loginHint: ""
    };
```

Can this check be relaxed to include prompt?

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/34892e8d44d493df9754bc5692caebbccb451be3/lib/msal-core/src/Utils.ts#L707

**Comment by sameerag** [comment]
@SaeedAkhter-MSFT good catch. I can check this and see how we can remedy this. 

prompt=select_account is supposed to give the tile selection independent of login_hint. When there is no login_hint passed from the user, we append some information (if we have it already) to the request to the server. We are still supposed to pass an interactive prompt to the service since the user chose to, looks like that case is error prone here.

**Comment by sameerag** [comment]
@SaeedAkhter-MSFT It is probably the way the sample is written in this case. We login in the background if the account instance is detected without giving an option to the user to login again (or click a sign-in button). I tested the prompt=select_account in other cases and it does seem to work, I also verified the NW calls we make and we do include "&prompt=select_account" as a part of our query string parameters sent to the server in the request.

Please let me know if my understanding is not correct.

**Comment by sameerag** [comment]
@SaeedAkhter-MSFT I tested this behavior and it seems to work fine. I edited our sample to have an extra button to switch accounts with prompt: "select_account" and verified that the request sent out to the service is also populated with querystring parameter: "&prompt=select_account".

Please let me know if I missed any corner case. I can also send you the sample over email if you woud like to test the same.

**Comment by sameerag** [comment]
I will check in this sample soon to have a running demo for prompt behavior for users.

**Comment by sameerag** [comment]
@SaeedAkhter-MSFT I sent an email with a sample that works for this use-case. If it still persists and you believe it is an issue, please alert us. CC @negoe.
