### ISSUE TITLE
Hebrew characters are not displaying right

### ISSUE THREAD

**Issue by Tovli** [AzureAD/microsoft-authentication-library-for-js#693]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: X.Y.Z

1.0.0

## Current behavior

After we authenticate the user/account. The name property is showing gibberish symbols when the language is Hebrew (or spanish as described in [this stackoverflow question](https://stackoverflow.com/questions/48170828/msal-issue-with-spanish-characters-getting-name-from-social-provider)

## Expected behavior

The current characters should be displayed

## Minimal reproduction of the problem with instructions

Register a user with Hebrew name or Spanish characters in the name

</code></pre>

**Comment by sameerag** [comment]
@Tovli This is tagged with #549  and we plan to release a fix in the next release.

**Comment by Tovli** [comment]
Superb

**Comment by sameerag** [comment]
@Tovli Can you help testing this with the PR at #712?
