### ISSUE TITLE
[BUG] Problems with Login Pop Up

### ISSUE THREAD

**Issue by FernandoRb16** [AzureAD/microsoft-authentication-library-for-js#6934]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.31.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.4.6

### Public or Confidential Client?

Public

### Description

There is a problem when using the pop-up login because when we maximize the login screen, the MFA flow is lost in the initial pain from where the trigger was sent to lift that pop-up

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [X] Pending

### MSAL Configuration

```javascript
auth: {
      authority: environment.adB2C.authority,
      clientId: environment.adB2C.clientID,
      redirectUri: environment.adB2C.redirectUri,
      postLogoutRedirectUri: environment.adB2C.logoutRedirectUri,
      navigateToLoginRequestUrl: true,
      knownAuthorities: environment.adB2C.knownAuthorities,
    },
    cache: {
      cacheLocation: 'localStorage',
      storeAuthStateInCookie: false,
    },
```

### Relevant Code Snippets

```javascript
raiseMFAPopup(): Observable<any> {
    return this.authService
      .authorizationPopUpRequest({
        scopes: environment.adB2C.scopes,
        authority: environment.adB2C.authorityApprovalFlow,
        redirectStartPage: window.location.href,
      } as PopupRequest)
      .pipe(
        catchError((error) => {
          return throwError(error);
        }),
        tap((_) =>
          // Got success information
)
```

### Reproduction Steps

1.- trigger MFA
2.- Maximaize login pop-up screen
3.- Fill login data
4.- Got Error

### Expected Behavior

Allow the screen to be maximized to return to the corresponding page in the main window

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
What error are you getting?

**Comment by FavioChavezNtt** [comment]
The issue is still not resolved
