### ISSUE TITLE
Automatically persisting refresh tokens before they expire.

### ISSUE THREAD

**Issue by sirisian** [AzureAD/microsoft-authentication-library-for-js#6935]
### Core Library

MSAL Node (@azure/msal-node)

### Wrapper Library

Not Applicable

### Public or Confidential Client?

Confidential

### Description

I got a complaint from multiple customers that they have to reauthorize graph API access (they manage hundreds of logins) when they don't use some of them (in my case calendar access) for 14 days (the default expiration of refresh tokens). (I modified my code to update the refresh token every 14 days to get a new refresh token. This all felt hacky as I needed to inspect internal state to check when the refresh token changed so I've since removed msal-node from my project and am just using the rest API).

msal-node handles everything with refresh tokens internally so it seems like a better fit for the library to handle this token maintenance.

The changes required would be:

* Option to ```automaticallyRefreshRefreshTokens: true``` defined in the config passed to ConfidentialClientApplication. (Because of the cache issue I create a ConfidentialClientApplication for each authentication, but if that's fixed it might be useful to be able to control this for each individual authentication).
* When acquireTokenSilent is called and a new refresh token is acquired it would record the expiration for the current time plus 2 weeks internally. (This expiration time is not queryable I don't think, so using the default is fine). This would be stored in the blob (next to the [secret](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/src/cache/serializer/Serializer.ts#L135C17-L135C23) property).
* A timer is created (and updated when the cache changes with a new refresh token) which will just call acquireTokenSilent before it expires (subtracting a random duration of a few minutes to correct if one set this to true on multiple servers).
* When the node.js application is restarted (and each ConfidentialClientApplication initialized) the timers should be recreated with the saved expiration. So this will need to load all the cached authentications on startup and create the timers.

I was using the distributed cache to persist refresh tokens with my PostgreSQL database if it matters. (That API is kind of broken as mentioned in #5854 as it assumes session state which further convoluted things). (I was storing this refresh time outside the blob and on restart I would deserialize all the blobs into the token cache).

### Source

External (Customer)

**Comment by bgavrilMS** [comment]
We would prefer that you manage token lifetime via https://learn.microsoft.com/en-us/entra/identity-platform/configurable-token-lifetimes

Default RT lifetime should be 3 months, not 14 days btw, but again, it's up to the tenant admin to set this.
