### ISSUE TITLE
getActiveAccount() is return null, but getAllAccounts() returns an array of account active in another tab

### ISSUE THREAD

**Issue by AmitHBhagat** [AzureAD/microsoft-authentication-library-for-js#6938]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.28.2

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.5

### Public or Confidential Client?

Public

### Description

`import { useMsal } from "@azure/msal-react";
const { instance, accounts, inProgress } = useMsal();
const ssoActiveAccount = instance.getActiveAccount();
console.log("ssoActiveAccount => ", ssoActiveAccount);
const ssoAllAccounts = instance.getAllAccounts();
console.log("ssoAllAccounts => ", ssoAllAccounts);`

Output in the Browser tab (Chrome, Edge):
ssoActiveAccount => null
ssoAllAccounts => [{...account active in the neighboring tab...}]

However, output in the Incognito tab (Chrome, Edge):
ssoActiveAccount => {...account active in the neighboring incognito tab...}

Can anybody please help?

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
auth: {
    authority:
      "https://login.microsoftonline.com/{tenant_id}/",
    clientId: "{client_id}",
    redirectUri: "http://localhost:3000/loading",
  },
  cache: {
    cacheLocation: "localStorage",
  }
```

### Relevant Code Snippets

```javascript
import { MsalProvider } from "@azure/msal-react";
import { PublicClientApplication, EventType } from "@azure/msal-browser";
import { MsalAuthenticationTemplate } from "@azure/msal-react";
import { InteractionType } from "@azure/msal-browser";

// MSAL configuration
const configuration = {
  auth: {
    authority:
      "https://login.microsoftonline.com/{tenant_id}/",
    clientId: "{client_id}",
    redirectUri: "http://localhost:3000/loading",
  },
  cache: {
    cacheLocation: "localStorage",
  },
};

const pubClientApp = new PublicClientApplication(configuration);

<MsalProvider instance={pubClientApp}>
      <MsalAuthenticationTemplate
        interactionType={InteractionType.Redirect}
        errorComponent={ErrorPage}
        loadingComponent={LoadingPage}
      >
        <App />
      </MsalAuthenticationTemplate>
    </MsalProvider>
```

### Reproduction Steps

create a react app with the help of "cra".
"react": "^18.2.0"

and use the above code snippet as an example.

### Expected Behavior

getActiveAccount() is supposed to return the account active in the neighboring tab.

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

Internal (Microsoft)

**Comment by 21Ovi** [comment]
when user goes to another tab the in useMsal context accounts get cleared, so for every component you do a transaction with microsoft or requires accounts, create a custom hook and call this hook at all places and run this following code inside that hook.

`  const request = {
    scopes: ["User.Read", "User.ReadBasic.All", "email"],
  };

  useMsalAuthentication(InteractionType.Redirect, request);

  const handleAccountAcquisition = async () => {
    if (accounts.length === 0) {
      const res = await instance.ssoSilent(tokenRequest);
      console.log(res, "acquireAccount");
    }
  };

  useEffect(() => {
    handleAccountAcquisition();
  }, []);`

this will get refresh your useMsal context.

**Comment by tnorling** [comment]
You can use the `enableAccountStorageEvents` API to sync state across tabs. More information [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/events.md#syncing-logged-in-state-across-tabs-and-windows)
