### ISSUE TITLE
How to test the app.component.ts code in Angular 16?

### ISSUE THREAD

**Issue by Ospina2k** [AzureAD/microsoft-authentication-library-for-js#6939]
### Core Library

MSAL.js (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Public or Confidential Client?

Public

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-angular-v3-samples/angular16-sample-app/src/app/app.component.ts

### Description

Hello, the app.component.ts has a lot of code, but in the .spec.ts it does not have the test cases for that.

**Comment by Ospina2k** [comment]
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/153514548/26487b34-11f8-4875-bafb-5349409a254d)

This is my jest report

**Comment by Ospina2k** [comment]
up

**Comment by sameerag** [comment]
@jo-arroyo Can we address this?

**Comment by Ospina2k** [comment]
🥲

**Comment by Ospina2k** [comment]
up?

**Comment by tnorling** [comment]
You can't test these APIs in a headless environment without mocking them which is why those test files haven't been written. You can find our general E2E testing guidance [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/testing.md)
