### ISSUE TITLE
ReferenceError: "event is not defined"

### ISSUE THREAD

**Issue by jofo-eb** [AzureAD/microsoft-authentication-library-for-js#694]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [x] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 0.1.2

## Current behavior

acquireTokenSilent causes console error print.
Error happens in MsalService.processHash in msal.service.js:151

## Expected behavior

No error dumps

## Minimal reproduction of the problem with instructions

Call acquireTokenSilent in Firefox

</code></pre>

**Comment by pkanher617** [comment]
@jofo-eb Is this an issue relating to msal-angular?

Can you post a stack trace or error string?

**Comment by jofo-eb** [comment]
This happens when calling acquireTokenSilent. I'd say it is related to msal-angular.

There are two errors in the console.
First error:
ERROR ReferenceError: "event is not defined"
Second error:
Unhandled Promise rejection: event is not defined ; Zone: <root> ; Task: Promise.then ; Value: ReferenceError: "event is not defined"

Can you see the undefined event variable in the code that I pointed out?

**Comment by jofo-eb** [comment]
Note: If I extend the if-condition like this, the error vanishes:
`if (typeof event !== 'undefined' && event && event.preventDefault)`
...and makes space for another exception:
`ERROR DOMException: "'#access_token=[...long token and other params...]' is not a valid selector"`

**Comment by sameerag** [comment]
@jofo-eb Can you please paste some sample code on how you are using the current angular wrapper? This is a basic use case that should ideally work, we can help with the debug if we have more data available.

**Comment by jofo-eb** [comment]
Sorry currently don't have example code since we postponed implementation of that feature for a while.
Please try to reproduce it yourself, as I said it is simply to call acquireTokenSilent in Firefox.

**Comment by sameerag** [comment]
We did not see this issue with calling acquireTokenSilent in Firefox with our basic MSAL JS version nor have we heard this issue from any of our current customers using angular. Our angular example works with the use-case you mentioned. I suspect some local settings in your case.

Please feel free to open a new issue once you have more data on this.
