### ISSUE TITLE
BrowserAuthError: interaction_in_progress in deployment but not in local environment

### ISSUE THREAD

**Issue by AliceLoUMusic** [AzureAD/microsoft-authentication-library-for-js#6946]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.10.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.0.12

### Public or Confidential Client?

Public

### Description

Browser keeps throwing `Uncaught (in promise) BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.` error in deployed environment but it works in local development.

And `msal.interation.status` in `sessionStorage` always returns `undefined` in the deployed environment.

### Error Message

BrowserAuthError.ts:351 Uncaught (in promise) BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.   For more visit: aka.ms/msaljs/browser-errors
    at l (BrowserAuthError.ts:351:12)
    at q.setInteractionInProgress (BrowserCacheManager.ts:1727:23)
    at tt.preflightInteractiveRequest (StandardController.ts:1494:38)
    at tt.preflightBrowserEnvironmentCheck (StandardController.ts:1473:18)
    at tt.acquireTokenRedirect (StandardController.ts:528:14)
    at tt.loginRedirect (StandardController.ts:1883:21)
    at u.loginRedirect (PublicClientApplication.ts:285:32)
    at login (useAuth.js:16:20)
    at Object.De (react-dom.production.min.js:54:317)
    at He (react-dom.production.min.js:54:471)

### MSAL Logs

authConfig.js:36 : [] : @azure/msal-browser@3.10.0 : Info - Emitting event: msal:initializeStart
authConfig.js:36 : [] : @azure/msal-browser@3.10.0 : Info - Emitting event: msal:initializeEnd
authConfig.js:36 : [] : @azure/msal-browser@3.10.0 : Info - Emitting event: msal:handleRedirectStart
authConfig.js:36 : [] : [018e25d9-c79f-7d38-8e81-be9d812f58e6] : msal.js.browser@3.10.0 : Info - handleRedirectPromise called but there is no interaction in progress, returning null.
authConfig.js:36 : [] : @azure/msal-browser@3.10.0 : Info - Emitting event: msal:handleRedirectEnd
authConfig.js:36 : [] : @azure/msal-browser@3.10.0 : Info - initialize has already been called, exiting early.
authConfig.js:36 : [] : @azure/msal-react@2.0.12 : Info - MsalProvider - handleRedirectPromise resolved, setting inProgress to 'none'

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
const msalConfig = {
  auth: {
    clientId: process.env.REACT_APP_AZURE_AD_CLIENT_ID,
    authority: `https://login.microsoftonline.com/${process.env.REACT_APP_AZURE_AD_TENANT_ID}`,
    redirectUri: process.env.REACT_APP_REDIRECT_URI,
    postLogoutRedirectUri: process.env.REACT_APP_REDIRECT_URI,
    navigateToLoginRequestUrl: true
  },
  cache: {
    cacheLocation: 'sessionStorage',
    storeAuthStateInCookie: false
  },
  system: {
    loggerOptions: {
      loggerCallback: (level, message, containsPii) => {
        if (containsPii) {
          return;
        }
        switch (level) {
          case LogLevel.Error:
            console.error(message);
            return;
          case LogLevel.Info:
            console.info(message);
            return;
          case LogLevel.Verbose:
            console.debug(message);
            return;
          case LogLevel.Warning:
            console.warn(message);
            return;
          default:
            return;
        }
      }
    }
  }
};

export const loginRequest = {
  scopes: ['User.Read']
};

export const graphConfig = {
  graphMeEndpoint: 'https://graph.microsoft.com'
};

export const msalInstance = new PublicClientApplication(msalConfig);
await msalInstance.initialize();
```

### Relevant Code Snippets

```javascript
useAuth Hook:

import { useIsAuthenticated, useMsal } from '@azure/msal-react';
import {
  BrowserUtils,
  InteractionRequiredAuthError
} from '@azure/msal-browser';
import { msalInstance } from './authConfig';

export const useAuth = () => {
  const { instance } = useMsal();
  const isAuthenticated = useIsAuthenticated();

  const login = async () => {
    const accounts = msalInstance.getAllAccounts();

    if (accounts.length === 0) {
      msalInstance.loginRedirect({
        scopes: [process.env.REACT_APP_AZURE_AD_SCOPE]
      });
    }
  };

  const getAccessToken = async () => {
    let account = instance.getActiveAccount();
    if (!account && instance.getAllAccounts().length > 0) {
      account = instance.getAllAccounts()[0];
      instance.setActiveAccount(account);
    }

    if (!account) {
      console.error('No active account. Verify a user has signed in.');
      // Optionally trigger a login flow here if appropriate for your app's UX
      return;
    }

    const tokenRequest = {
      scopes: [process.env.REACT_APP_AZURE_AD_SCOPE],
      account
    };

    try {
      const response = await instance.acquireTokenSilent(tokenRequest);
      return response.accessToken;
    } catch (error) {
      console.error('Token acquisition error:', error);
      // Fallback to interactive method if silent acquisition fails
      if (error instanceof InteractionRequiredAuthError) {
        try {
          const interactiveResponse = await instance.acquireTokenPopup(
            tokenRequest
          );
          return interactiveResponse.accessToken;
        } catch (interactiveError) {
          console.error(
            'Interactive token acquisition error:',
            interactiveError
          );
          // Handle interactive error, potentially logging out or notifying the user
        }
      }
    }
  };

  const logout = () => {
    instance.logoutRedirect({
      onRedirectNavigate: () => !BrowserUtils.isInIframe()
    });
  };

  return {
    isAuthenticated,
    login,
    getAccessToken,
    logout
  };
};


Index.js

msalInstance
  .handleRedirectPromise()
  .then((tokenResponse) => {
    // Optional: Handle the token response if needed
    if (tokenResponse && tokenResponse.account) {
      msalInstance.setActiveAccount(tokenResponse.account);
    }
  })
  .catch((error) => {
    console.error('Error during redirect callback processing:', error);
    // Handle or log error as needed
  });

// This will update account state if a user signs in from another tab or window
msalInstance.enableAccountStorageEvents();

msalInstance.addEventCallback((event) => {
  if (event.eventType === EventType.LOGIN_SUCCESS && event.payload.account) {
    const account = event.payload.account;
    msalInstance.setActiveAccount(account);
  }
});

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <MsalProvider instance={msalInstance}>
      <ThemeProvider theme={theme}>
        <Router>
          <App />
        </Router>
      </ThemeProvider>
    </MsalProvider>
  </React.StrictMode>
);
```

### Reproduction Steps

Followed the steps listed in the docs and got it working in local development. But every time a user clicks Login to trigger login function it throws the `BrowserAuthError: interaction_in_progress` error. Tried changing to LoginPopup but the problem persists.

### Expected Behavior

Expected the login function to work as intended and see these:

@azure/msal-react@2.0.12 : Info - MsalProvider - handleRedirectPromise resolved, setting inProgress to 'none'
@azure/msal-common@14.7.1 : Info - CacheManager:getIdToken - Returning ID token

### Identity Provider

Entra ID (formerly Azure AD) / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari

### Source

External (Customer)

**Comment by tnorling** [comment]
Please share trace level logs and code snippets showing where you're calling the `login` and `acquireToken` functions returned by `useAuth` so we can better understand what is happening

**Comment by jmlivingston** [comment]
I found that removing ScrictMode removes this error. Obviously that's not an ideal, so I may end up putting it further down the hierarchy.

**Comment by siuusunn** [comment]
Just a quick update in case someone runs into similar issue - i made a rookie mistake: the environment variables were not injecting during build time in my deployed app, it was injected during run time, that was what caused the auth error. After I changed that and have the env var ready at build time, it solved the issue.

**Comment by dlindahl** [comment]
I ran into the same problem and tried all of the above solutions to no avail. Through additional debugging, I discovered that there was incomplete state from a previously failed login flow stored in cookies. Clearing the cookies resolved this issue for me.

Good luck! 🎉
