### ISSUE TITLE
Support for b2clogin.com 

### ISSUE THREAD

**Issue by anubi** [AzureAD/microsoft-authentication-library-for-js#695]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version (Chromium 69.0.3497.100)
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: Dev branch, latest commit faa898ffb0c295c7bd568e6b000c3d8db010352f

## Current behavior
When I configure the angular library in app.module.ts such that:

MsalModule.forRoot({
...
authority: "https://test.b2clogin.com/test.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1_test"
...})

...my login experience breaks for the demo angular example app in this repository.

I use a b2clogin.com custom login page policy, it won't recognize it as a valid endpoint despite my attempts to get a URL I think it could understand. I have of course, tried other b2clogin.com addresses and tenants and just different permutations of that url, but I believe that my login hosted at a link like

https://test.b2clogin.com/test.onmicrosoft.com/oauth2/v2.0/authorize?p=B2C_1_test&client_id=*******&nonce=defaultNonce&redirect_uri=http%3A%2F%2Flocalhost%3A4200%2Ftest&scope=openid&response_type=id_token&prompt=login

Isn't currently supported by this library without forking this project.

## Expected behavior
When I click on 'login' in the angular demo app, I expect to have a popup or my window directed to my custom login hosted in my azure blob storage account, similar to this tutorial https://docs.microsoft.com/en-us/azure/active-directory-b2c/tutorial-customize-ui implies. I currently don't think this is supported.

## Minimal reproduction of the problem with instructions
1. Create a custom user flow of type 'sign up and sign in' in 'Azure AD B2C - User Flows (policies)', follow the tutorial (tutorial-customize-ui) above and create a simple login page.
2. In the current example angular project, change MsalModule.forRoot's authority configuration from "https://login.microsoft.com/common/" to another authority that knows to serve your custom login page.
3. Login should direct you to that page, it currently cannot, based on my limited understanding

</code></pre>

**Comment by sameerag** [comment]
@anubi we are working with the B2C service team to clarify requirements for this support. We are aware that there is a customer base that is looking forward on this and we can get back once we have this as an active feature.

**Comment by sameerag** [comment]
Linking to #435 and closing this. b2clogin.com support will be tracked with the linked issue.
