### ISSUE TITLE
Session token in URL 

### ISSUE THREAD

**Issue by geek1596** [AzureAD/microsoft-authentication-library-for-js#6952]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

1.4.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.4.0

### Public or Confidential Client?

Public

### Description

Sensitive information within URLs may be logged in various locations, including the user's browser, the 
web server, and any forward or reverse proxy servers between the two endpoints. URLs may also be 
displayed on-screen, bookmarked or emailed by users. They may be disclosed to third parties via the 
Referrer header when any off-site links are followed. Placing session tokens into the URL increases the 
risk that they will be captured by an attacker.

### Error Message

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/163313852/6b212ad1-1329-459d-aa7e-1ddf852f728c)

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
import { UserAgentApplication } from "msal";

            // Msal Configurations
            const config = {
                auth: {
                    authority: "https://login.microsoftonline.com/" + TENANT_ID,
                    clientId: CLIENT_ID,
                    redirectUri: "http://localhost:3000",
                    navigateToLoginRequestUrl: false
                },
                cache: {
                    cacheLocation: "sessionStorage",
                    storeAuthStateInCookie: false
                }
            };
            const MSALObj = new UserAgentApplication(config);
            MSALObj.loginRedirect({
                scopes: ["openid", "profile", "User.Read"]
            });
```

### Relevant Code Snippets

```javascript
import { UserAgentApplication } from "msal";

            // Msal Configurations
            const config = {
                auth: {
                    authority: "https://login.microsoftonline.com/" + TENANT_ID,
                    clientId: CLIENT_ID,
                    redirectUri: "http://localhost:3000",
                    navigateToLoginRequestUrl: false
                },
                cache: {
                    cacheLocation: "sessionStorage",
                    storeAuthStateInCookie: false
                }
            };
            const MSALObj = new UserAgentApplication(config);
            MSALObj.loginRedirect({
                scopes: ["openid", "profile", "User.Read"]
            });
```

### Reproduction Steps

When we login to the app, it redirects us to the home page and the session token is passed in the URL

### Expected Behavior

The session token should not be passed in the URL, and it creates a security issue. Is there a fix or other way around where we have fixed this issue ?

### Identity Provider

Entra ID (formerly Azure AD) / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
msal v1 uses the implicit flow which returns tokens in the url. msal v1 has been deprecated in favor of msal-browser v2/3 which implements the auth code flow with PKCE and does not return tokens in the url. v1 is not receiving any further updates or support, please use msal-browser v3 instead

**Comment by geek1596** [comment]
I updated it to the latest version 3.10.0 and tried to run the application, but there has been a repeated error. So I have downgraded the version to 3.9.0 and tried, and still it throws me the same error 

Error : ./node_modules/@azure/msal-browser/dist/operatingcontext/UnknownOperatingContext.mjs
Can't import the named export 'BaseOperatingContext' from non EcmaScript module (only default export is available)

I guess it's an error regarding the package, can you please let me know which is the stable version that I can use in this scenario.

Thank you for the help in advance
