### ISSUE TITLE
Code route redirection does not have a slash prefix.

### ISSUE THREAD

**Issue by nandu-s** [AzureAD/microsoft-authentication-library-for-js#6964]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.9.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.12

### Public or Confidential Client?

Public

### Description

The issue is - after authentication, the AAD service redirects to our specified URL with the code parameter - http://localhost:4200/#code=0.AUoAq8w03cpv_ky1*** as you can see there is no forward slash prefix before the code parameter. So the application is treating it as a rouge url. Is there any way to add the slash before the code parameter or are we missing any thing here.We have added code route to angular as per your recommendation. Please advice. 

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
auth: {
      clientId: 'xxx',
      authority: `https://login.microsoftonline.com/xxx/`,
      redirectUri:'http://localhost:4200/',
      postLogoutRedirectUri: "http://localhost:4200/",
    },
```

### Relevant Code Snippets

```javascript
const routes: Routes = [
  {
    path: 'profile',
    component: ProfileComponent,
    canActivate: [MsalGuard]
  },
  {
    // Needed for hash routing
    path: 'code',
    component: HomeComponent
  },
  {
    path: '',
    component: HomeComponent
  }
];
```

### Reproduction Steps

1. Trigger login using MSAL.
2. Provide creds and authenticate.
3. App redirects to given redirect url with "code" suffix.
4. Application treat it as a unknown page. 

### Expected Behavior

There should be a / before the code suffix in the redirection url which is absent now. Because of this angular is not redirecting to the code route suggested by MSAL.

### Identity Provider

Entra ID (formerly Azure AD) / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari

### Source

External (Customer)

**Comment by sameerag** [comment]
@nandu-s Did this ever work?

**Comment by nandu-s** [comment]
> @nandu-s Did this ever work?

Please provide clarification.

**Comment by tnorling** [comment]
There is no way to prefix the hash with a / - we have many customers successfully using hash routing and samples that implement hash routing and haven't experienced any issues related to this, can you please give us more detail about what specifically is happening or not happening? Better yet if you can link us to a repo that demonstrates a minimal reproduction of the issue that would help immensely.
