### ISSUE TITLE
acquireTokenSilent unpredictable ID token retrieval

### ISSUE THREAD

**Issue by aochider** [AzureAD/microsoft-authentication-library-for-js#6971]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.32.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

1.5.0

### Public or Confidential Client?

Public

### Description

I am using `acquireTokenSilent()` in order to get the ID token from my React frontend. It seems that the retrieval behavior is unpredictable, which results in different tokens being retrieved depending on factors that I would not expect to be relevant. In my use case, I end up decoding the ID token in order to inspect the `claims` and `iat`, which can be problematic if the user has taken action (eg, via an MFA prompt with `acrs` claim) but I receive an old, cached ID token.

If I use the MSAL context instance inside of my own React context component and make a request to `acquireTokenSilent` (with or without `forceRefresh: true`), the response is always the ID token from the session storage. Using the Network tab, I can see a request to `/token` that has the most recent ID token, but the response in my code always receives the cached one. It is like it is _always_ using the session storage before the `/token` request is completed. Wrapping the request in a 1000ms timeout seems to make it work using the response from `/token`, but I'm sure that will vary and would prefer not to do that.

If I use the MSAL context instance inside of my own React UI component, I always receive the latest ID token in the response from `acquireTokenSilent` in my code.

### Error Message

None. I have to debug myself in the console, session storage, and the Network tab to see that the most recent ID token is not used.

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
const msalInstance = new PublicClientApplication({
  auth: {
    clientId,
    authority: `https://login.microsoftonline.com/${tenantId}`,
    redirectUri,
    clientCapabilities: ['CP1'],
  },
  cache: {
    cacheLocation: 'sessionStorage',
    storeAuthStateInCookie: false,
  },
});
```

### Relevant Code Snippets

```javascript
export function MyUIComponent(props) {
  const { startAuth } = useMyContext();
  const { instance, accounts } = useMsal();

  useEffect(() => {
    if (accounts.length > 0) {
      const request = {
        scopes: ['openid'],
        account: accounts[0],
      };
      instance
        .acquireTokenSilent(request)
        .then(response => {
          console.log('printed second', response.idToken); // Always seems to be a fresh value
        });
    }
  }, [instance, accounts]);
};

======

export const Context = createContext();

export const Provider = ({ children }) => {
  const { instance, accounts } = useMsal();

  useEffect(() => {
    if (accounts.length > 0) {
      const request = {
        scopes: ['openid'],
        account: accounts[0],
        forceRefresh: true,
      };
      instance
        .acquireTokenSilent(request)
        .then(response => {
          console.log('printed first', response.idToken); // Always seems to be a value from session storage, even if a request to /token was made
        });
    }
  }, [instance, accounts]);
};

export function useMyContext() {
  return useContext(Context);
}

======

<MsalProvider instance={msalInstance}>
  <Provider>
    <MyUIComponent />
  </Provider>
</MsalProvider>
```

### Reproduction Steps

1. Login to Microsoft
2. `acquireTokenSilent` in a context
3. `acquireTokenSilent` in a leaf UI component
4. Notice how the `acquireTokenSilent` in the context always returns the session storage version

### Expected Behavior

I expect that the `response.idToken` is always the same value regardless of where the MSAL instance is used. Also, if `forceRefresh: true` is provided, then `response.idToken` should always be the value from the `/token` request and never from the cache.

### Identity Provider

Entra ID (formerly Azure AD) / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by tnorling** [comment]
I'm not sure I fully understand what is happening here. Maybe it helps if I explain how acquireTokenSilent works. acquireTokenSilent is used to acquire *access tokens*, id tokens are also returned but are more of a secondary concern. 

If the access token is cached & valid the request is a success and both access and id tokens will be returned from the cache
If the access token is not cached or expired MSAL.js will attempt to exchange the refresh token and assuming that succeeds both the access and id tokens returned from the network request will be returned from that network request.

At no point is a cached token returned after making a POST to /token.

There's another piece to this that I think may be relevant given the example provided & the statement that wrapping in a timeout fixes the issue. If 2 or more of the *same* request are executed in parallel they will both return the same response rather than each independently checking the cache and making their own network requests. It sounds likely that `MyUIComponent` is doing the work here, returning the fresh response & the `Provider` component is making the same request very shortly after and is thus returning the same response object without doing the work.

**Comment by aochider** [comment]
@tnorling thanks for the response!

to clarify my example above: i do not use two `useMsal` contexts at the same time. that was to demonstrate what the code looks like in the components. my actual testing had `useMsal` in either the `Provider` or `MyUIComponent` but not both at the same time.

anyway, it sounds like youre saying there is not a chance that a stored id token is returned. but is there a chance that `acquireTokenSilent` returns a value outside of the one case you described?

for example, im thinking there may be more than one spot in the code where it calls `resolve(somePayload)`. i understand that ideally it would *only* be calling `resolve(response)` in one spot after the `/token` request succeeds, but that just doesnt seem to be the behavior i observed in my example above. it also makes sense as a programmer that there may be certain circumstances where it would make decisions based on the token issue date or try to be efficient and use stored values, and an issue may be in that code.

that being said, ive already worked around the issue for now and as with anything, the issue couldve certainly been on my side.

**Comment by tnorling** [comment]
> for example, im thinking there may be more than one spot in the code where it calls resolve(somePayload). i understand that ideally it would only be calling resolve(response) in one spot after the /token request succeeds

Promises can only be resolved once. Even if resolve is called multiple times only the first one would do anything, subsequent calls would be ignored by the js engine.

To reiterate my previous point responses can be returned from 1 of 3 places:

1. Cache
2. Network response
3. Shared promise from parallel request

Turning on trace level logging and looking through the messages will tell you exactly where the response is coming from as will the `fromCache` value in the response.

In any case I wouldn't normally recommend relying on the issuedAt time, forcing a refresh if the token isn't new enough is not a pattern we recommend. In fact, we rarely recommend you force a refresh at all. The expiration time of the token should be more than sufficient to determine validity and MSAL will handle token lifetime management for you under the hood by default.

**Comment by aochider** [comment]
> Promises can only be resolved once. Even if resolve is called multiple times only the first one would do anything, subsequent calls would be ignored by the js engine.

yes, i understand that. in fact, that idea is what i was getting at with my example. apologies for not being more clear! for example, a hypothetical example of what could go wrong is that `resolve` was called inside of an `if` block with the cached value (so my code now receives the cached value) but then a `/token` request is made anyway (due to some other conditions in the code, some timing issue when initializing msal, etc.) and that `resolve` then does nothing after the `/token` request succeeds. thus, my code is left with the cached token value but i still see a `/token` request in my browser network tab with values that i didnt receive in my code.

if i encounter this again, i will try to see if i can turn on more logging to debug. thanks for the info!
