### ISSUE TITLE
MSAL authentication issue for user accounts connected to windows

### ISSUE THREAD

**Issue by sagarpuranik** [AzureAD/microsoft-authentication-library-for-js#6983]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.11.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

0

### Public or Confidential Client?

Public

### Description

While using the SSO login on a system using Azure AD login, if you select "Use another account" and enter incorrect credentials still getting login success with the token generated for the user logged in to the system. 

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
{
      auth: {
        clientId: import.meta.env.VITE_API_CLIENT_ID,
        redirectUri: import.meta.env.VITE_REDIRECT_URL,
        postLogoutRedirectUri: import.meta.env.VITE_REDIRECT_URL,
        authority: import.meta.env.VITE_API_AUTHORITY
      },
      cache: {
        cacheLocation: 'localStorage',
        storeAuthStateInCookie: false 
      }
    }
```

### Relevant Code Snippets

```javascript
async login(scopes = ['user.read', 'openid', 'profile', 'email']) {
    if (!msalApp) {
      return
    }

    //const LOGIN_SCOPES = ['user.read', 'openid', 'profile', 'email']
    await msalApp.loginPopup({
      scopes,
      prompt: 'select_account'
    })
  },
```

### Reproduction Steps

1. Click on Login. 
2. Login Pop up shows ( The pop up shows one user "Connected to Windows" )
3. Click on Use another account
4. Enter an incorrect email id and password
5. It shows an error message 
But after that the popup closes and login succeeds. Token is also generated for the user Connected to Windows. 

*Note : This happens only incase of failed login. 

### Expected Behavior

Login failed as the user is invalid.

### Identity Provider

Entra ID (formerly Azure AD) / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

External (Customer)

**Comment by sameerag** [comment]
@sagarpuranik Do you know if you have enabled native flow in your MSAL JS integration? Also would like to get a trace here, can you please [email](https://github.com/sameerag) me? Please also enable MSAL JS [logging](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logging.md).
