### ISSUE TITLE
Obfuscate B2C items in URL

### ISSUE THREAD

**Issue by eplatow** [AzureAD/microsoft-authentication-library-for-js#6988]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Wrapper Library

Not Applicable

### Public or Confidential Client?

Public

### Description

As an owner of a system integrating Microsoft B2C into our authentication processes, I want to divulge as little information as possible regarding the underlying technology stacks to any potential bad actors.  As such, I would prefer to be able to use custom field name for the B2C tenant as well as not having "b2c" prefixed to the custom policy names in the URLs.  This also allows me an opportunity to switch tenants in the event of a catastrophic loss of the tenant where I need to rebuild it from scratch.

I am not sure if I tagged this correctly or not.

### Source

External (Customer)

**Comment by tnorling** [comment]
Please [open a support ticket with B2C](https://learn.microsoft.com/en-us/azure/active-directory-b2c/find-help-open-support-ticket) and someone can help you get this set up
