### ISSUE TITLE
Allow the authentication scheme to be specified for MsalInterceptor

### ISSUE THREAD

**Issue by richard-perry** [AzureAD/microsoft-authentication-library-for-js#7000]
### Core Library

MSAL.js (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Public or Confidential Client?

Public

### Description

I would like to be able to specify the authentication scheme that the MsalInterceptor passes in the authentication header. To support API's that can handle multiple authentication schemas as documented here https://github.com/AzureAD/microsoft-identity-web/wiki/multiple-authentication-schemes

### Source

External (Customer)

**Comment by tnorling** [comment]
Thanks for the feature request! This is similar to #6795 which we are tracking on our backlog though it hasn't been prioritized yet. I'll add a +1 to that feature request and close this in favor of that issue. When we have updates they will be shared there.
