### ISSUE TITLE
MSAL React redirect to "/#code=..." after login popup

### ISSUE THREAD

**Issue by NZMia** [AzureAD/microsoft-authentication-library-for-js#7004]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.10.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.0.12

### Public or Confidential Client?

Public

### Description

I am developing a web application using React and Azure functions, and I intend to retrieve user data from Azure B2C. For authentication purposes, I am utilising the following dependencies in my frontend:  

```
  "@azure/msal-browser": "^3.10.0",
    "@azure/msal-react": "^2.0.12",
    "@testing-library/jest-dom": "^5.17.0",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.5.2",
    "@types/node": "^16.18.90",
    "@types/react": "^18.2.67",
    "@types/react-dom": "^18.2.22",
    "antd": "^5.15.3",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.22.3",
    "react-scripts": "5.0.1",
    "sass": "^1.72.0",
    "typescript": "^4.9.5",
    "web-vitals": "^2.1.4"
  ```
  ```
   node:  v20.2.0
  ```
The problem I am encountering is as follows: while the application runs smoothly **locally**, upon deployment, I encounter an issue where after the login process, the popup redirects to a URL resembling "https://mySite/myRedirect#code=0.AX...", resulting in a 404 error.

I have attempted to troubleshoot this issue by conducting searches related to it. However, I have not come across any references to a [MsalGuard](https://stackoverflow.com/questions/76565901/msal-angular-redirect-to-code-after-login-popup-or-redirect-with-msalgua) specifically designed for React.

I am seeking assistance in resolving this issue and would appreciate guidance or suggestions on how to address the redirection problem encountered post-login in my React web application integrated with Azure B2C authentication.

### Error Message

No real error message, just the intermediate redirect to the route "https://mySite/myRedirect#code=0.AX..." after a successful login. (Local one is fine.)

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
export const msalConfig: Configuration = {
  auth: {
    clientId: clientId
    authority: 'https://login.microsoftonline.com/xxxxx',
    redirectUri: '/authz', 
    postLogoutRedirectUri: '/',
    navigateToLoginRequestUrl: false, 
  },
  cache: {
    cacheLocation: 'sessionStorage',
    storeAuthStateInCookie: false,
  },
  system: {
    // allowNativeBroker: false,
    loggerOptions: {
      loggerCallback(logLevel, message, containsPii) {
        if (containsPii) {
          return;
        }
        switch (logLevel) {
          case LogLevel.Error:
            console.error(message);
            return;
          case LogLevel.Info:
            console.info(message);
            return;
          case LogLevel.Verbose:
            console.debug(message);
            return;
          case LogLevel.Warning:
            console.warn(message);
            return;
          default:
            return;
        }
      },
    },
  },
};
```

### Relevant Code Snippets

```javascript
The issue arises solely on the live site. local is fine.

```
### What I found  
<img width="1504" alt="Screenshot 2024-04-05 at 12 08 07 PM" src="https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/10533181/ba923601-221a-435f-833e-89bccd01e0c5">

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/10533181/31e31b92-9b71-4265-9093-852f3afd03d9)

### Reproduction Steps

1. Click on the login button. (https://wonderful-sand-0c2958100.5.azurestaticapps.net/)
2. Observe the encountered error.

### Expected Behavior

Redirect to the URL without "#code=0.AX."

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
The redirection to #code= is part of the auth protocol and cannot be avoided. I'm not sure why it's returning 404, that's something you'll need to debug with whatever is hosting your app (azure static web apps?). I am noticing that your redirectUri page: `https://wonderful-sand-0c2958100.5.azurestaticapps.net/authz` is automatically invoking login on page load. You should not do this and this could be part of the problem. Your redirectUri should be responsible only for processing the response (#code=) using handleRedirectPromise when doing loginRedirect/acquireTokenRedirect or do nothing when using loginPopup/acquireTokenPopup/acquireTokenSilent/ssoSilent
