### ISSUE TITLE
Intune Get Devices API is not working as expected  in some cases and In some cases we do get devices and not able to find the difference and not able to understand from current error message

### ISSUE THREAD

**Issue by ravivarma4003** [AzureAD/microsoft-authentication-library-for-js#7011]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

NA

### Wrapper Library

Not Applicable

### Wrapper Library Version

NA

### Public or Confidential Client?

Confidential

### Description

i'm using the valid token only . i'm getting the below error in some times and was not able to understand it properly.
Sometimes we do get devices and sometimes we don't get any error and some times error . And not able to understand what does that error means here as it is inconsistent.
curl --location 'https://graph.microsoft.com/v1.0/deviceManagement/managedDevices' \
--header 'Authorization: Bearer token'

{
    "error": {
        "code": "UnknownError",
        "message": "{\"ErrorCode\":\"Forbidden\",\"Message\":\"{\\r\\n  \\\"_version\\\": 3,\\r\\n  \\\"Message\\\": \\\"An error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: e92e5699-51cf-49f7-b606-c839cb75eabe - Url: https://fef.msuc02.manage.microsoft.com/DeviceFE/StatelessDeviceFEService/deviceManagement/managedDevices?api-version=2023-07-04\\\",\\r\\n  \\\"CustomApiErrorPhrase\\\": \\\"\\\",\\r\\n  \\\"RetryAfter\\\": null,\\r\\n  \\\"ErrorSourceService\\\": \\\"\\\",\\r\\n  \\\"HttpHeaders\\\": \\\"{\\\\\\\"WWW-Authenticate\\\\\\\":\\\\\\\"Bearer realm=\\\\\\\\\\\\\\\"urn:intune:service,c3998d6e-2e37-4c56-87b5-7b444ee1cb26,3e9c57b9-808d-4aa0-9500-4b2d369279e7\\\\\\\\\\\\\\\"\\\\\\\"}\\\"\\r\\n}\",\"Target\":null,\"Details\":null,\"InnerError\":null,\"InstanceAnnotations\":[]}",
        "innerError": {
            "date": "2024-04-06T03:46:43",
            "request-id": "e92e5699-51cf-49f7-b606-c839cb75eabe",
            "client-request-id": "e92e5699-51cf-49f7-b606-c839cb75eabe"
        }
    }
}

### Error Message

{
    "error": {
        "code": "UnknownError",
        "message": "{\"ErrorCode\":\"Forbidden\",\"Message\":\"{\\r\\n  \\\"_version\\\": 3,\\r\\n  \\\"Message\\\": \\\"An error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: e92e5699-51cf-49f7-b606-c839cb75eabe - Url: https://fef.msuc02.manage.microsoft.com/DeviceFE/StatelessDeviceFEService/deviceManagement/managedDevices?api-version=2023-07-04\\\",\\r\\n  \\\"CustomApiErrorPhrase\\\": \\\"\\\",\\r\\n  \\\"RetryAfter\\\": null,\\r\\n  \\\"ErrorSourceService\\\": \\\"\\\",\\r\\n  \\\"HttpHeaders\\\": \\\"{\\\\\\\"WWW-Authenticate\\\\\\\":\\\\\\\"Bearer realm=\\\\\\\\\\\\\\\"urn:intune:service,c3998d6e-2e37-4c56-87b5-7b444ee1cb26,3e9c57b9-808d-4aa0-9500-4b2d369279e7\\\\\\\\\\\\\\\"\\\\\\\"}\\\"\\r\\n}\",\"Target\":null,\"Details\":null,\"InnerError\":null,\"InstanceAnnotations\":[]}",
        "innerError": {
            "date": "2024-04-06T03:46:43",
            "request-id": "e92e5699-51cf-49f7-b606-c839cb75eabe",
            "client-request-id": "e92e5699-51cf-49f7-b606-c839cb75eabe"
        }
    }
}

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
{
client_id : ..,
}
```

### Relevant Code Snippets

```javascript
Step 1:Use the below api to get the access token :

curl --location 'https://login.microsoftonline.com/common/oauth2/v2.0/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Cookie: buid=0.AWsAOEvuqe_X-kKLet9b0_uZ45nYg8yIGDRHo6mgdbaXncVrAAA.AQABGgEAAADnfolhJpSnRYB1SVj-Hgd8ycaU7FqPC052xX1W_b3KRwF_vik8KbR__k2f2rXSiLRQiM_6-ucWtIrc_Foanhd7DVtA32Y_K5_b_1O7t-VyOJ6K1GSEHMo6-MlLNr8E8twgAA; esctx=PAQABBwEAAADnfolhJpSnRYB1SVj-Hgd8xhbp4RVjw0d3PkUWYwK2Zq9ZZzlf-DXvGiWaetEKl2iE7IWzVAS68RbOVDnXZkubom2QbU3nWFT5aS3FUng9jqATznAysUUdBW45EP0ywcAlEQWnNtwV8ZkNai9WpCwtslUDF6hKYy8mA7bQyXj9Mc_6HN1oDgBiXP5nSazPvgEgAA; fpc=AuYcNbhx2NFBvetdo2qJglNslxSGAQAAAO3xod0OAAAA; stsservicecookie=estsfd; x-ms-gateway-slice=estsfd' \
--data-urlencode 'client_id=' \
--data-urlencode 'redirect_uri=' \
--data-urlencode 'client_secret=' \
--data-urlencode 'refresh_token=' \
--data-urlencode 'grant_type=refresh_token'

Once you have token call the below api :
step 2:
curl --location 'https://graph.microsoft.com/v1.0/deviceManagement/managedDevices' \
--header 'Authorization: Bearer ''
```

### Reproduction Steps

Step 1:Use the below api to get the access token :

curl --location 'https://login.microsoftonline.com/common/oauth2/v2.0/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Cookie: buid=0.AWsAOEvuqe_X-kKLet9b0_uZ45nYg8yIGDRHo6mgdbaXncVrAAA.AQABGgEAAADnfolhJpSnRYB1SVj-Hgd8ycaU7FqPC052xX1W_b3KRwF_vik8KbR__k2f2rXSiLRQiM_6-ucWtIrc_Foanhd7DVtA32Y_K5_b_1O7t-VyOJ6K1GSEHMo6-MlLNr8E8twgAA; esctx=PAQABBwEAAADnfolhJpSnRYB1SVj-Hgd8xhbp4RVjw0d3PkUWYwK2Zq9ZZzlf-DXvGiWaetEKl2iE7IWzVAS68RbOVDnXZkubom2QbU3nWFT5aS3FUng9jqATznAysUUdBW45EP0ywcAlEQWnNtwV8ZkNai9WpCwtslUDF6hKYy8mA7bQyXj9Mc_6HN1oDgBiXP5nSazPvgEgAA; fpc=AuYcNbhx2NFBvetdo2qJglNslxSGAQAAAO3xod0OAAAA; stsservicecookie=estsfd; x-ms-gateway-slice=estsfd' \
--data-urlencode 'client_id=' \
--data-urlencode 'redirect_uri=' \
--data-urlencode 'client_secret=' \
--data-urlencode 'refresh_token=' \
--data-urlencode 'grant_type=refresh_token'

Once you have token call the below api :
step 2:
curl --location 'https://graph.microsoft.com/v1.0/deviceManagement/managedDevices' \
--header 'Authorization: Bearer ''

### Expected Behavior

Expected behaviour is to get the devices but we are getting the error as mentioned above. Generally it's bit weird and in consistent. sometimes we do get devices and sometimes we get error . What exactly we are missing here.

### Identity Provider

Entra ID (formerly Azure AD) / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Regression

NA. it';s a api failure

### Source

External (Customer)

**Comment by FuAdmin** [comment]
I encounter same issue when I use Graph Api:

![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/108501535/bc1b01a4-63b6-4355-b8ec-e4722b9c490f)

I am sure I have the permission of the Api, So I think this is a BUG.

**Comment by FuAdmin** [comment]
@ravivarma4003

**Comment by ravivarma4003** [comment]
@FuAdmin We are also facing similar in consistency behaviour with this api.
One link i found : https://learn.microsoft.com/en-us/answers/questions/1409278/graph-api-endpoint-to-list-managed-devices-throwin

But still not consistent.

**Comment by FuAdmin** [comment]
@ravivarma4003 So this issue did is a bug, right? do we have any way to solve the issue now?

**Comment by ravivarma4003** [comment]
Not as of now. Try as above link and see if it's working for you.

**Comment by FuAdmin** [comment]
Thanks @ravivarma4003 

Above link use global administrator account, as a normal user can not have administrator account. based on doc (https://learn.microsoft.com/en-us/graph/api/intune-devices-manageddevice-list?view=graph-rest-1.0&tabs=http) of graph api, normal user just only apply for 'DeviceManagementManagedDevices.Read.All'. which can access the api. Currently I did have the permission, but still got error.
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/108501535/22d63789-11fa-4911-a59e-f9d41ff3772a)

**Comment by ravivarma4003** [comment]
looks like bug to me as well. We will wait for intune team to reply here.

**Comment by tnorling** [comment]
We don't own the Intune API, please [open a support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) so your question can be routed to the correct team. If you think there's an issue with MSAL please open a new issue specifically describing the issue with token acquisition.
