### ISSUE TITLE
[msal-node] Confidential Client - Client Assertion implementation should accept callback instead of string argument

### ISSUE THREAD

**Issue by KarishmaGhiya** [AzureAD/microsoft-authentication-library-for-js#7013]
### Core Library

MSAL Node (@azure/msal-node)

### Wrapper Library

Not Applicable

### Public or Confidential Client?

Confidential

### Description

The client assertion implementation for confidential client should take a user callback that returns a string instead of accepting a string assertion. This will extend the usability of the API to allow users for refreshing the assertion token etc. .NET and Java implementation of MSAL already support this.

### Source

Internal (Microsoft)

**Comment by KarishmaGhiya** [comment]
cc: @Robbie-Microsoft @bgavrilMS

**Comment by bgavrilMS** [comment]
Thanks, @KarishmaGhiya . 

@Robbie-Microsoft  - can you please propose an API here similar to what .NET has, something like `WithClientAssertion(await GetAssertion())`. The key point is that it needs to be async.

**Comment by Robbie-Microsoft** [comment]
@bgavrilMS sure. Before you left that comment, I made my own implementation. See my draft PR [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/7014). I didn't take async into account though.
