### ISSUE TITLE
Msal react signature verification fails

### ISSUE THREAD

**Issue by xeaser** [AzureAD/microsoft-authentication-library-for-js#702]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 0.2.4

## Current behavior
If already logged in to Microsoft AD account until the msal.id.token expires, then the token is not renewed and signature verification fails.
(Implemented using acquireTokenSilent and acquireTokenPopup with "read" scopes).

## Expected behavior
Every time the token is expired new token should be generated.

## Minimal reproduction of the problem with instructions
NA

</code></pre>

**Comment by pkanher617** [comment]
@xeaser I'm a little unclear on the issue. Does the idToken renewal fail? Or are you seeing another error relating to signature verification failure? 

A stack trace or error description would help us here.

We have also released our 1.0.0 version. If possible, please download our [latest preview package](https://www.npmjs.com/package/msal) or pull the [dev branch](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev) and try updating your code and see if the issue still persists. 

We are also now throwing error stack traces which may help us for any other issues you are facing.

If you would like guidance on how to use the new version of the library, please review our wiki page [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL.js-1.0.0-preview-api-release).

**Comment by xeaser** [comment]
> @xeaser I'm a little unclear on the issue. Does the idToken renewal fail? Or are you seeing another error relating to signature verification failure?
> 
> A stack trace or error description would help us here.
> 
> We have also released our 1.0.0 version. If possible, please download our [latest preview package](https://www.npmjs.com/package/msal) or pull the [dev branch](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev) and try updating your code and see if the issue still persists.
> 
> We are also now throwing error stack traces which may help us for any other issues you are facing.
> 
> If you would like guidance on how to use the new version of the library, please review our wiki page [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL.js-1.0.0-preview-api-release).

Sorry, If I was unclear the idToken renewal fails and we are creating our token after idToken generation. If the idToken is expired than signature verification fails.
I'll try with the newer version too.

**Comment by sameerag** [comment]
@xeaser Is there an update on this ticket? Did this resolve with a later version of MSAL JS?

**Comment by DarylThayil** [comment]
@xeaser  have not heard back, closing. If this is still an issue please open an new ticket.
Thanks
