### ISSUE TITLE
MsalGuard to support redirect on failure

### ISSUE THREAD

**Issue by snebjorn** [AzureAD/microsoft-authentication-library-for-js#703]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version 74.0.3729.131 
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

@azure/msal-angular
Library version: 0.1.2

## Expected behavior

It would be neat if the `MsalGuard` would support redirecting to an access denied page. The `CanActivate` interface supports returning a `UrlTree`. I believe this was added in Angular v7.1.

So if we can have `MsalConfig.failureRedirectUri = "access-denied-page"` that would be a lot simpler then having to subscribe to the failure event.

**Comment by DarylThayil** [comment]
@snebjorn  Thank you for sharing your thoughts.  We are currently finishing up work on our `msal-core` library, and will begin work on `msal-angular` this summer.  We will consider your suggestion, and investigate the impact on the library.

cc @negoe

**Comment by snebjorn** [comment]
Would you accept a PR on this? As this will probably introduce breaking changes.

**Comment by DarylThayil** [comment]
We are always open to pull requests, but I think as it stands right now, will not be releasing breaking changes until 1.0.0 (or the final preview). We will be working to communicate more about timeline, and keep the feature top of mind as we plan what developers need!

**Comment by sameerag** [comment]
Link to #786. Tracking as a feature ask.

**Comment by DarylThayil** [comment]
linked in #786  closing this

**Comment by jasonnutter** [comment]
We did not get to this in MSAL Angular v1, but is a follow up improvement we want to make. Reopening and tracking.

**Comment by snebjorn** [comment]
@jasonnutter I already have a working version of this based on the new MsalGuard. I can make a PR or at least share the solution. Interested?

**Comment by jasonnutter** [comment]
@snebjorn A PR would great, thanks!

**Comment by ahelmel** [comment]
Is there any progress on this feature?

**Comment by jasonnutter** [comment]
This is now possible in MSAL Angular v2: https://github.com/AzureAD/microsoft-authentication-library-for-js/releases/tag/msal-angular-v2.0.0-alpha.0

Closing.
