### ISSUE TITLE
msal v3 - navigateToLoginRequestUrl true does not wait for logic performed in redirectUri component before navigating to previous page

### ISSUE THREAD

**Issue by ac-ih** [AzureAD/microsoft-authentication-library-for-js#7034]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.13.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.16

### Public or Confidential Client?

Public

### Description

I am using the recommended redirect approach (as mentioned [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/redirects.md#msalredirectcomponent-a-dedicated-handleredirectobservable-component) / [Angular 15 sample](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-angular-v3-samples/angular15-sample-app/src/app/app.module.ts#L110))

My auth config looks like:
```
auth: {
  authority: `https://login.microsoftonline.com/${tenantId}`,
  clientId: `${clientId}`,
  redirectUri: '/auth/callback',
  postLogoutRedirectUri: '/logout/success',
  navigateToLoginRequestUrl: true
}
```

This works as expected. However, when I want to add some logic in the component connected to the redirectUri (aka callback component), then it initiates the call, does not wait for it, and redirects to the previous page. If I set `navigateToLoginRequestUrl` to false, then it waits on the redirectUri-connected component, but I lose the previous page info/functionality.

There's somewhat of a lack of control due to `MsalGuard` triggering logic redirect for the user, and the provided `RedirectComponent` is handling things.

Is there an option to override or passthrough the redirectUri path within the callback component so custom logic can be done?

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
{
  auth: {
    authority: `https://login.microsoftonline.com/${tenantId}`,
    clientId: `${clientId}`,
    redirectUri: '/auth/callback',
    postLogoutRedirectUri: '/logout/success',
    navigateToLoginRequestUrl: true
  }
}
```

### Relevant Code Snippets

```javascript
// routes
const routes: Route[] = [
  { path: 'auth/callback', component: AuthCallbackComponent },
  { path: 'logout/success', component: LogoutSuccessComponent },
  { path: 'home', component: HomeComponent, canActivate: [MsalGuard] },
  { path: 'resource', component: ResourceComponent, canActivate: [MsalGuard] },
  { path: '', redirectTo: 'home', pathMatch: 'full' }
];

// AuthCallback.component.ts

authenticateAndRedirect() {
  this.authService.someMethod().subscribe({
    next: (apiResponse: any) => {
      // do stuff
    
      // logic: if not base url, redirect user back to prev page; else redirect based 
      const calculatedRedirectUrl = `{}`
      this.router.navigate([calculatedRedirectUrl]);
    },
    error: () => {
      this.router.navigate(['/error']);
    }
  });
}
```

### Reproduction Steps

Try to add some api call logic in the component connected to the redirect path (aka callback component)

### Expected Behavior

Is there an option to override or passthrough the redirectUri path within the callback component so custom logic can be done?

### Identity Provider

Entra ID (formerly Azure AD) / MSA

### Browsers Affected (Select all that apply)

Other

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
This is the type of use case where you should consider not using our prebuilt components. In other words, don't use RedirectComponent and instead invoke handleRedirectPromise yourself. You can then do your custom logic and *then* invoke handleRedirectPromise to send you back to your original route.
