### ISSUE TITLE
Looking for reference for MSAL.JS

### ISSUE THREAD

**Issue by pamelafox** [AzureAD/microsoft-authentication-library-for-js#7037]
### Core Library

MSAL.js (@azure/msal-browser)

### Wrapper Library

MSAL React (@azure/msal-react)

### Public or Confidential Client?

Public

### Documentation Location

learn.microsoft.com

### Description

I cannot find a reference for this library - I have only found samples. I just want to see what parameters a function takes and what its return value looks like. (In this case, acquireTokenSilent). Is there a reference available?
(I will now look at the code, assuming there's no reference)

**Comment by tnorling** [comment]
You can find our TypeDocs [here](https://azuread.github.io/microsoft-authentication-library-for-js/ref/modules/_azure_msal_browser.html)
