### ISSUE TITLE
Login Redirect nor Login Pop Up are not working for Sign Up v2 or v1 with AAD B2C

### ISSUE THREAD

**Issue by aszalacinski** [AzureAD/microsoft-authentication-library-for-js#704]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version XX
- [X] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 1.0.0

## Current behavior

Attempting to use Login Redirect to send users to the Sign Up v2 page. MSAL dies quietly and doesn't provide a reason of why it will not show Sign up form. I know the flow works as I tested it within the Azure portal. So the issue lies with MSAL.

## Expected behavior

When I call loginRedirect the user should be redirected to the Signup Screen and on submission of signup details, redirected back to the calling application.

Additionally, if i attempt to use loginPopup, same experience occurs however the popup never closes and my confirmation page loads in the popup window.

## Minimal reproduction of the problem with instructions

Passing in appropriate Client ID
Passing in appropriate B2CLogin Authority
Setting ValidateAuthority to false.

On call to UserAgentApplication Login Redirect method, it bypasses any opportunity to enter user details and proceeds immediately to redirected address. No error messages.

These are new users attempting to add details.

Please advise

</code></pre>

**Comment by aszalacinski** [comment]
aha! It is not a code issue per se... more than likely a gap in my knowledge.

So the sample code was still working. The only difference was my redirect URL i specified the register app was buried in my site... https://<my-site>/confirmation

I got rid of the /confirmation and it's working now. I guess MSAL defaults a redirect url to the page that sent the file however why would I specify the Reply Url in the B2C applications setup then?

So if I wanted to redirect my B2C application to a URL that is not my top level domain, how to I pass in a redirectURL to MSAL?

**Comment by kest85** [comment]
I'm having this redirect loop in react application too. After calling loginRedirect() it does not set msal.idtoken in session storage (I see only msal.nonce.idtoken set there) after the redirect - I see this id token in browser address bar for several milliseconds and then redirect happens again and it does not set it in session storage. If I try calling acquireTokenSilent() after that - it always times out (even if timeout is set to 30 seconds) and I see no errors in console and session storage error items are also not set, so not sure how to debug this further. I think it may be a bug in MSAL. Can someone help resolving this?

**Comment by DarylThayil** [comment]
@aszalacinski  the library does default the redirect uri to the page it was sent, but can be overrode in configuration

```js
const msal = new UserAgentApplication({
    auth: { 
       clientId: '<you clientId>',
       redirectUri: '<your redirect uri>'
   }
});
```
https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL.js-1.0.0-api-release#configuration-options

**Comment by DarylThayil** [comment]
@kest85 loginRedirect is a funny beast. There are actually a few redirects happening to massage the state, we hope to simplify this soon.
Where we have seen login redirect loops, it usually because login redirect is being called regardless if a user is already logged in.

Our direction is to follow a pattern like this

```js
   if ( !msal.getAccount()) { // if we have no user
       msal.loginRedirect();
   } else {
         // a user is logged in and you can now do what you need to do like acquire a token for an api
   }
```
if this does not capture your use case, let me know and we can get into the detail a little bit more

**Comment by DarylThayil** [comment]
@kest85  your comment actuallyseems to be separate from the original.  I am going to close @aszalacinski issue because he was able to resolve. If my comment does not resolve your issue, please do make another ticket!

**Comment by aszalacinski** [comment]
@DarylThayil you rock! thanks for the pointer.
