### ISSUE TITLE
MSAL no event when user cancels aquireTokenPopup

### ISSUE THREAD

**Issue by engbibi** [AzureAD/microsoft-authentication-library-for-js#706]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version 74.0
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 0.1.2

## Current behavior

If the user closes the window after a call to aquireTokenPopup there is no error triggered and the subsequent calls result in the following error: "acquiretoken_progress_error|Acquire token is in progress". I belive there is an error in the msal-core where you only check for login in progress:

UserAgentApplication.ts (line 778):
` if (popupWindow && popupWindow.closed && instance.loginInProgress) {...}`

## Expected behavior

User canceled error should be triggered.

## Minimal reproduction of the problem with instructions

`this.msalService.acquireTokenPopup(environment.b2cScopes).then(
      (payload: any) => {
       ...
      }
    ).catch(error => {
      // No error when user closes the window.
     ...
    });`

</code></pre>

**Comment by sameerag** [comment]
@engbibi Can you please try this with the latest MSAL version 1.0.0? We added 'user cancelled error' and various other error handling with our new version.

**Comment by engbibi** [comment]
I am using the azure wrapper version 0.1.2 which is based on MSAL.js version 1.0.0. User canceled flow works on longinPopup, but not on aquireTokenPopup.

**Comment by sameerag** [comment]
Got it. Let us debug this before we get back. I see the error handling added to openPopup which is a common function, but I haven't yet checked the total flow. Will reach out once we have a conclusion on this. Thank you for bringing this to our notice.

**Comment by sameerag** [comment]
@engbibi can you please try out the PR #707 if you can locally build using the git PR branch? If you don't know how, please let me know, can help.

**Comment by DarylThayil** [comment]
@engbibi  if you don't want to build the branch locally, you can see the one line change in the pr and try adding that predicate to your node_module code for a quick and dirty way to make sure it fixes

**Comment by engbibi** [comment]
@sameerag I tried to build the PR but it seems that it has a dependency to an older version of msal:
`"dependencies": {
    "msal": "0.2.1",
    "tslib": "1.7.1"
  },`

If I use the build from msal-core I get type errors.

**Comment by sameerag** [comment]
@engbibi This PR is based off the dev branch which is msal 1.0.0; will a new npm release help your case? We will anyways release this PR to the next patch and can give you a release.

Can you share the type errors you are seeing? And also the details of how you are including msal in your application?

**Comment by engbibi** [comment]
@sameerag If I update msal to version 1.0.0 in msal-angular project (from version 0.2.1) I get a lot of problems like: "/node_modules/msal/lib-commonjs" has no exported member 'User'. This PR must have an msal-angular version with outdated dependencies, or is msal-angular in general a little behind?

**Comment by keystroke** [comment]
I am also getting this same error using 1.0.0; I can repro my inducing a call to acquireTokenPopup asking for scopes that require admin consent - this gives me the opportunity to close the pop-up, and no event or error is triggered. The same does NOT happen for loginPopup; that function will raise an error ("ClientAuthError: User Cancelled the flow.") if the user closes the login. I am using msal from https://secure.aadcdn.microsoftonline-p.com/lib/1.0.0/js/msal.min.js

**Comment by sameerag** [comment]
@engbibi yes, msal 1.0.0 is for the core library. Angular will follow suit, mostly this summer as mentioned in our [roadmap](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#roadmap)

@keystroke PR #707  will be released next week in a patch release for msal core and should solve your issue.

**Comment by sameerag** [comment]
Closing this issue as PR #707 is now released. Please reopen if you are seeing any variant of this issue again.
