### ISSUE TITLE
Does msal v1 support the removal of third-party cookies

### ISSUE THREAD

**Issue by YuriLopesM** [AzureAD/microsoft-authentication-library-for-js#7077]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Wrapper Library

Not Applicable

### Public or Confidential Client?

Public

### Documentation Location

https://learn.microsoft.com/en-us/entra/identity-platform/reference-third-party-cookies-spas

### Description

Currently, I have a internal lib (using React) on my company that uses **msal v1**. We use the `acquireTokenSilent` method and, If not granted, we redirect with `loginRedirect` method. In the past days, users related that when they try to login, a infinite loop between our app and the login page happen.

When I searched about this, I understand that the cause is the block of third-party cookies that Chrome is doing through the year, and not every person may have this problem (but probably in the future everyone does). I try the solution offered in [this document](https://learn.microsoft.com/en-us/entra/identity-platform/scenario-spa-acquire-token?tabs=javascript2) (using `acquireTokenPopup` or `acquireTokenRedirect` if the silent method fails), but not worked at all. Probably the problem is the **SameSite** being set as `None`, but when I went to the [document talking about this](https://learn.microsoft.com/en-us/entra/identity-platform/howto-handle-samesite-cookie-changes-chrome-browser?tabs=java), it doesn't have the solution for JS-based apps.

The question is, can I fix this with some workaround using **msal v1**, am I not understanding the problem correctly, or the only way out is bumping the version (using msal-browser and msal-react for my case)?

**Comment by sameerag** [comment]
msal v1 has been discontinued for a while, firstly owing to industry recommendation to not deploy implicit flow in browser auth flows. I highly recommend upgrading to msal js latest (3.x) nevertheless for security reasons.

The 3P cookies blocking applies to msal 3.x too, however, this will result in interaction required every 24 hrs instead. Authentication flows themselves will not break.

**Comment by YuriLopesM** [comment]
@sameerag 

> however, this will result in interaction required every 24 hrs instead. Authentication flows themselves will not break.

Is there a way to create the same 24h interaction in the msal v1? Or is the break of the authentication flow inevitable?

Just to try a fix for the moment, the plan is to upgrade to msal v3.x.
