### ISSUE TITLE
B2C Microsoft identity provider with msal-browser 2.x login error code challenge require

### ISSUE THREAD

**Issue by anasmohana** [AzureAD/microsoft-authentication-library-for-js#7079]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.30.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

2.0.0

### Public or Confidential Client?

Public

### Description

In my B2C AD configuration, Signicat has been set up as an identity provider alongside Google and Azure AD. While both Google and Azure AD integrations are functioning correctly, I encounter difficulty enabling Signicat due to an error message stating "code challenge required." Upon conducting a network inspection within the browser, I observe that the initial request to the user flow endpoint includes all requisite query parameters, including the code_challenge. However, upon interaction with the Signicat login popup, the subsequent request fails to reflect the inclusion of the code_challenge parameter, thus resulting in the aforementioned error and impeding successful authentication via Signicat.

### Error Message

code challenge required

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
auth: {
      clientId: "xxxxxxxxx", 
      authority: b2cPolicies.authorities.signUpSignIn.authority, 
      knownAuthorities: [b2cPolicies.authorityDomain], 
      redirectUri: "https://xxxxxxxx.azurewebsites.net", 
    },
```

### Relevant Code Snippets

```javascript
JavaScript single-page application secured with MSAL.js using the Authorization Code Flow (PKCE) on Azure AD B2C
```

### Reproduction Steps

1. config B2C app with spa 
2. add Signicat as identity provider
3. run the app and click sign in 

### Expected Behavior

use can login and get user info

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome

### Source

Internal (Microsoft)

**Comment by sameerag** [comment]
In B2C, the IDP should respect all the parameters forwarded by the client and it is not always uniform across the board. Can you please check with B2C team and debug this as this is unlikely to be an MSAL JS issue? Can you please reach out to them [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/FAQ.md#what-should-i-do-if-i-believe-my-issue-is-with-the-b2c-service-itself-rather-than-with-the-library)?
