### ISSUE TITLE
Problem calling acquireTokenSilent with sid

### ISSUE THREAD

**Issue by steenole** [AzureAD/microsoft-authentication-library-for-js#708]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ x] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 1.0.0

## Current behavior
I have an application that authenticates on the server side. Therefore I have a SID 
from the idToken, that I can pass to acquireTokenSilent() and avoid logging in again 
on the client side. At least, that is what I would expect. But I get an error saying 
"User login required".
The problem occurs in UserAgentApplication. I wonder if this code is correct?
The !! operator means that the error will be raised, even if sid (or loginHint) is provided:
 //if there is no account logged in and no login_hint/sid is passed in the request
      if (!account && !!(request.sid  || request.loginHint) && Utils.isEmpty(adalIdToken) ) {
        this.logger.info("User login is required");
        return reject(ClientAuthError.createUserLoginRequiredError());
      } 

## Expected behavior
Calling acquireTokenSilent with a sid, should get me an accessToken without logging in.

## Minimal reproduction of the problem with instructions
msalObj.acquireTokenSilent({
    scopes: ['user.read'],
    sid: 'some-valid-sid-here'
});
returns 'User login is required'

</code></pre>

**Comment by sameerag** [comment]
@steenole Yes, this seems to be a typo. Instead of just fixing this, I also want to consolidate all the checks we do for hints as separate util function if possible. Please expect a PR tomorrow for this.

**Comment by DarylThayil** [comment]
@sameerag  can you add update on the pr for this ?

**Comment by sameerag** [comment]
PR #700 has the needed changes as we already have a relevant issue being fixed in the same. I plan to include the PR in the upcoming patch release.

Regarding consolidation of hints, I later decided to pushing those as a separate PR makes it easier for traction and also to expedite the needed fixes to the patch release.

@steenole can test #700 for this issue.

**Comment by steenole** [comment]
Yes #700 seems to solve the issue I have reported.

**Comment by sameerag** [comment]
Great. msal js 1.0.1 is released now with #700; closing this issue.
