### ISSUE TITLE
LoginPopup and LoginRedirect not Working

### ISSUE THREAD

**Issue by mahira-code** [AzureAD/microsoft-authentication-library-for-js#7096]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

1.5.2

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

I am using Azure msal for B2C Login 
I am using loginPopup it is working fine 
But when my App is redirecting from another App loginPopup i am getting my website url (www.example.com/sign-in) in popup
If i change loginPopup to loginRedirect() its redirecting to signin and Dashboard Continuously 

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
export const msalConfig = {
   auth: {
       clientId: "clientId",
       authority: "tenantId",
       redirectUri: process.env.REACT_APP_REDIRECT_URI,
cache: {
        cacheLocation: "localStorage", // This configures where your cache will be stored
        storeAuthStateInCookie: true, // Set this to "true" if you are having issues on IE11 or Edge
    },
   },
```

### Relevant Code Snippets

```javascript
const handleLogin = () => {

        if (instance.getActiveAccount()) {
            // If already logged in, verify login and update form state
            console.log("its entering in to instance.getActiveAccount()",localStorage.length);
            const updatedValues = formState.values
            handleFormChange(updatedValues);
            verifLogin()
        }else{
            instance
            .loginPopup(loginRequest)
            .catch((error) => {
                console.error("Login error:", error);
            })
            .then(verifLogin);
            console.log(instance.setActiveAccount(account));
        }
       
    };
```

### Reproduction Steps

Redirect from one app to another App

### Expected Behavior

if I am redirecting from one app/website to another website without asking login Credentials.

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome

### Regression

@azure/msal-react: "^1.5.2",

### Source

Internal (Microsoft)

**Comment by tnorling** [comment]
Using another app's redirectUri is unsupported. The domain of the redirectUri must match the domain of the app which initiated the request.

**Comment by mahira-code** [comment]
@tnorling The problem is exactly www.example.com here i have one button if i am clicking the button www.example1.com it will open my website in this scenario LoginPopup is not working and in this version if i am implementing LoginRedirect instead of loginPopup its keep on loading no error no warning So basically its not redirecting while i am clicking the button its opening my website in this scenario my popup also not working
