### ISSUE TITLE
MSAL 3.0 not returning accounts in Angular 17 after upgrading from 2.16.0

### ISSUE THREAD

**Issue by virendra05** [AzureAD/microsoft-authentication-library-for-js#7105]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

None

### Public or Confidential Client?

Public, Confidential

### Description

I recently upgraded @azure/msal-angular and @azure/msal-browser from version 2.16.0 to 3.0.0 in my Angular 17 project. Since the upgrade, I am unable to retrieve user accounts using this.authService.instance.getAllAccounts(), which now returns an empty array

```
import { MsalService, MsalBroadcastService, MSAL_GUARD_CONFIG, MsalGuardConfiguration } from '@azure/msal-angular';

constructor(
  @Inject(MSAL_GUARD_CONFIG) private msalGuardConfig: MsalGuardConfiguration,
  private authService: MsalService, private msalBroadcastService: MsalBroadcastService) {}



 async ngOnInit() {
    this.msalBroadcastService.inProgress$
    .pipe(
      filter((status: InteractionStatus) => status === InteractionStatus.None),
      takeUntil(this._destroying$)
    )
    .subscribe(() => {
      this.setLoginDisplay();
    }, (error) => {
      this.isLoading = false;
    });
  }
  
  async setLoginDisplay() {
  if (!this.localAuthService.isLogin) {
    this.loginDisplay = this.authService.instance.getAllAccounts().length > 0;
    if (this.loginDisplay) {
      const data = this.authService.instance.getAllAccounts()[0];
      // Further processing...
    }
  }
}
```

No errors appear in the console, and the configurations and initializations appear to be unchanged besides the library upgrade. I suspect this might be a lifecycle or configuration issue with MSAL 3.0 in Angular 17. Has anyone encountered a similar problem or knows of any breaking changes in MSAL 3.0 that could affect account retrieval?

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
export const msalConfig: Configuration = {
    auth: signinsignupBrowserAuthOptions,
    cache: cacheOptions,
    system: browserSystemOptions

}


export const signinsignupBrowserAuthOptions = {
    clientId: ClientId,
    authority: authority,
    knownAuthorities: authorityDomain,
    redirectUri: '/',
    postLogoutRedirectUri: '/'
  }

  export const cacheOptions = {
    cacheLocation: BrowserCacheLocation.LocalStorage,
    storeAuthStateInCookie: isIE,
  }
  export const browserSystemOptions = {
    loggerOptions: {
      loggerCallback,
      logLevel: LogLevel.Info,
      piiLoggingEnabled: false
    }
  }
```

### Relevant Code Snippets

```javascript
shared in description
```

### Reproduction Steps

Upgrade from Angular 13 to Angular 17 and add above shared in App-component.ts

### Expected Behavior

Should get this.authService.instance.getAllAccounts() data

### Identity Provider

Entra ID (formerly Azure AD) / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari

### Source

Internal (Microsoft)

**Comment by hectormmg** [comment]
@virendra05 there are some issues with account in early minor versions of v3. Please try the latest minor/patch version and see if your problem persists.
