### ISSUE TITLE
Angular 17 Standalone MSAL Angular v3 Sample Doesnt work and Documentation is wrong

### ISSUE THREAD

**Issue by Pr1ke** [AzureAD/microsoft-authentication-library-for-js#7106]
### Core Library

MSAL.js (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Public or Confidential Client?

Public

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-angular-v3-samples/angular17-standalone-sample/README.md

### Description

The Sample references a package "e2e-test-utils" which doesnt exist and fails to install, the readme states "Open ./src/main.ts in an editor.
Replace client id with the Application (client) ID from the portal registration, or use the currently configured lab registration."

the Main.ts File does not offer a space to insert the client id.

I tried changing the client id found inside the environment.ts files (all of them) but the website still uses a different client id which doesnt belong to me.

**Comment by konstantin-msft** [comment]
Hi @Pr1ke. Thanks for bringing it up. I will update README.md shortly. 
1. Please use `./src/app/app.config.ts` to set the client id and other params.
2. Please remove `e2e-test-utils` from `package.json` for local development.
