### ISSUE TITLE
MsalContext accounts contains incorrect for authenticated user

### ISSUE THREAD

**Issue by ivi-hamiti** [AzureAD/microsoft-authentication-library-for-js#7110]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.14.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.0.16

### Public or Confidential Client?

Public

### Description

During app bootstrap msal is loaded and the msal context is initialized with 

```
...
accounts = instance.getAllAccounts()
...
```

After you acquire a token, the account is updated in the msal instance, but the context is still returning the old object. This is due the fact that the context is not updated as the utility function `accountArraysAreEqual` skips this new value as it matches the old account based on `homeAccountId`, `localAccountId` and `username`. My expectation is that this new account is reflected also in the msal context.

Is there a reasoning why this behaves like this, or is this a bug?

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
{
  auth: {
    clientId: "*************",
    authority: "*************",
    knownAuthorities: ["*************"],
    redirectUri: window.location.origin,
    navigateToLoginRequestUrl: true,
  },
  cache: {
    cacheLocation: "localStorage",
  },
}
```

### Relevant Code Snippets

```javascript
// none
```

### Reproduction Steps

1. login to app
2. refresh page
3. accuire token
4. ```const { accounts, instance } = useMsal(); // accounts is different from instance.getAllAccounts()```

### Expected Behavior

`accounts` in MsalContext properly reflect the result of `msalInstance.getAllAccounts()`

### Identity Provider

Azure B2C Custom Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari

### Source

External (Customer)

**Comment by tnorling** [comment]
This is expected behavior. The accounts returned by context should only be used if you depend on persistent values such as name, username, etc or for passing into acquireToken APIs. If you need specific claims from the idToken you should invoke the APIs provided by PublicClientApplication to get the most up to date values. 

The reason for this is that updating context every time a claim changes would result in far more re-renders than is often necessary.
