### ISSUE TITLE
Error: Uncaught (in promise): InteractionRequiredAuthError: interaction_required: AADB2C90077: User does not have an existing session and request prompt parameter has a value of 'None'.

### ISSUE THREAD

**Issue by gabi04** [AzureAD/microsoft-authentication-library-for-js#7115]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.13.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.16

### Public or Confidential Client?

Public

### Description

My app is working aparetally alrigth

But my data dog is full of errors like the one that I'm attaching

### Error Message

InteractionRequiredAuthError: interaction_required: AADB2C90077: User does not have an existing session and request prompt parameter has a value of 'None'.
Correlation ID: environment.azure.clientId
Timestamp: 2024-05-14 14:41:10Z

### MSAL Logs

Error: Uncaught (in promise): InteractionRequiredAuthError: interaction_required: AADB2C90077: User does not have an existing session and request prompt parameter has a value of 'None'.
Correlation ID: environment.azure.clientId
Timestamp: 2024-05-14 14:41:10Z
InteractionRequiredAuthError: interaction_required: AADB2C90077: User does not have an existing session and request prompt parameter has a value of 'None'.
Correlation ID: environment.azure.clientId
Timestamp: 2024-05-14 14:41:10Z
    at nn.validateServerAuthorizationCodeResponse (https://clientportal-test.iadb.org/main.js:1:2033937)
    at Fn.handleFragmentResponse (https://clientportal-test.iadb.org/main.js:1:2041269)
    at https://clientportal-test.iadb.org/main.js:1:2087258
    at Generator.next (<anonymous>)
    at i (https://clientportal-test.iadb.org/main.js:1:2271949)
    at v (https://clientportal-test.iadb.org/main.js:1:2272151)
    at https://clientportal-test.iadb.org/main.js:1:2272210
    at new t (https://clientportal-test.iadb.org/polyfills.js:1:18396)
    at https://clientportal-test.iadb.org/main.js:1:2272092
    at g.handleCodeResponse (https://clientportal-test.iadb.org/main.js:1:2087503)
  at z @ https://clientportal-test.iadb.org/polyfills.js:1:16008
  at <anonymous> @ https://clientportal-test.iadb.org/polyfills.js:1:15098
  at <anonymous> @ https://clientportal-test.iadb.org/polyfills.js:1:15204
  at <anonymous> @ https://clientportal-test.iadb.org/main.js:1:2143662
  at v.invoke @ https://clientportal-test.iadb.org/polyfills.js:1:6593
  at Object.onInvoke @ https://clientportal-test.iadb.org/main.js:1:1247047
  at v.invoke @ https://clientportal-test.iadb.org/polyfills.js:1:6533
  at L.run @ https://clientportal-test.iadb.org/polyfills.js:1:1974
  at <anonymous> @ https://clientportal-test.iadb.org/polyfills.js:1:16803
  at v.invokeTask @ https://clientportal-test.iadb.org/polyfills.js:1:7211
Handled by
Error: 
  at Mc.handleError @ https://clientportal-test.iadb.org/main.js:1:1244459
  at Object.next @ https://clientportal-test.iadb.org/main.js:1:1307015
  at x.next @ https://clientportal-test.iadb.org/main.js:1:1017990
  at P._next @ https://clientportal-test.iadb.org/main.js:1:1017666
  at P.next @ https://clientportal-test.iadb.org/main.js:1:1017356
  at <anonymous> @ https://clientportal-test.iadb.org/main.js:1:1015312
  at f @ https://clientportal-test.iadb.org/main.js:1:1039302
  at Py.next @ https://clientportal-test.iadb.org/main.js:1:1015151

Error: Uncaught (in promise): BrowserAuthError: hash_empty_error: Hash value cannot be processed because it is empty. Please verify that your redirectUri is not clearing the hash. For more visit: aka.ms/msaljs/browser-errors
BrowserAuthError: hash_empty_error: Hash value cannot be processed because it is empty. Please verify that your redirectUri is not clearing the hash. For more visit: aka.ms/msaljs/browser-errors
    at V (https://clientportal-test.iadb.org/main.js:1:2160264)
    at X (https://clientportal-test.iadb.org/main.js:1:2089010)
    at https://clientportal-test.iadb.org/main.js:1:1981451
    at https://clientportal-test.iadb.org/main.js:1:2111522
    at Generator.next (<anonymous>)
    at i (https://clientportal-test.iadb.org/main.js:1:2271949)
    at v (https://clientportal-test.iadb.org/main.js:1:2272151)
    at v.invoke (https://clientportal-test.iadb.org/polyfills.js:1:6593)
    at Object.onInvoke (https://clientportal-test.iadb.org/main.js:1:1247047)
    at v.invoke (https://clientportal-test.iadb.org/polyfills.js:1:6533)
  at z @ https://clientportal-test.iadb.org/polyfills.js:1:16008
  at <anonymous> @ https://clientportal-test.iadb.org/polyfills.js:1:15098
  at <anonymous> @ https://clientportal-test.iadb.org/polyfills.js:1:15204
  at <anonymous> @ https://clientportal-test.iadb.org/main.js:1:2143662
  at v.invoke @ https://clientportal-test.iadb.org/polyfills.js:1:6593
  at Object.onInvoke @ https://clientportal-test.iadb.org/main.js:1:1247047
  at v.invoke @ https://clientportal-test.iadb.org/polyfills.js:1:6533
  at L.run @ https://clientportal-test.iadb.org/polyfills.js:1:1974
  at <anonymous> @ https://clientportal-test.iadb.org/polyfills.js:1:16803
  at v.invokeTask @ https://clientportal-test.iadb.org/polyfills.js:1:7211
Handled by
Error: 
  at Mc.handleError @ https://clientportal-test.iadb.org/main.js:1:1244459
  at Object.next @ https://clientportal-test.iadb.org/main.js:1:1307015
  at x.next @ https://clientportal-test.iadb.org/main.js:1:1017990
  at P._next @ https://clientportal-test.iadb.org/main.js:1:1017666
  at P.next @ https://clientportal-test.iadb.org/main.js:1:1017356
  at <anonymous> @ https://clientportal-test.iadb.org/main.js:1:1015312
  at f @ https://clientportal-test.iadb.org/main.js:1:1039302
  at Py.next @ https://clientportal-test.iadb.org/main.js:1:1015151

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
export const MsalConfig: Configuration = {
  auth: {
    authority: environment.azure.loginUrl,
    clientId: environment.azure.clientId,
    redirectUri: '/',
    postLogoutRedirectUri: '/',
    knownAuthorities: [`${environment.azure.loginUrl}/oauth2/v2.0/authorize`],
  },
  cache: {
    cacheLocation: 'localStorage',
    storeAuthStateInCookie: isIE,
  },
  system: {
    iframeHashTimeout: 20000,
  },
};
```

### Relevant Code Snippets

```javascript
Besides the configura

import { NgModule } from '@angular/core';
import {
  MsalGuard,
  MsalInterceptor,
  MsalModule,
  MsalRedirectComponent,
  MsalService,
  MsalInterceptorConfiguration,
  MsalGuardConfiguration
} from '@azure/msal-angular';
import { HTTP_INTERCEPTORS } from '@angular/common/http';
import {InterceptorMSAL, MsalConfig, ProtectedResources} from "./auth.constants";
import {PublicClientApplication} from "@azure/msal-browser";

/**
 * Module auth, declaration to msal module and add msal interceptor in providers
 */
@NgModule({
  declarations: [],
  imports: [
    MsalModule.forRoot(
      new PublicClientApplication(MsalConfig),
      ProtectedResources as MsalGuardConfiguration,
      InterceptorMSAL as MsalInterceptorConfiguration
    )
  ],
  providers: [
    MsalService,
    { provide: HTTP_INTERCEPTORS, useClass: MsalInterceptor, multi: true },
    MsalGuard,
  ],
  bootstrap: [MsalRedirectComponent],
})
export class AuthModule {}
```

### Reproduction Steps

await token expire and monitor console

### Expected Behavior

no recievin those errors in data dog

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari

### Source

External (Customer)

**Comment by hectormmg** [comment]
@gabi04 this will happen when MSAL attempts to refresh a token silently after a session has expired. The interaction required error is returned to the application so it can fall back to interactive authentication, but the error remains in the logs anyway. As long as interactive auth works as a fallback, this is by design so I wouldn't worry about it.
