### ISSUE TITLE
Support for Angular 18

### ISSUE THREAD

**Issue by talgershman** [AzureAD/microsoft-authentication-library-for-js#7127]
### Core Library

MSAL.js (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Public or Confidential Client?

Public

### Description

Offical support for Angular 18.

I was wondering an ETA on the matter ?

In version 17, you release without support for SSR, so most of the projects can upgrade. I think you should do the same and also give feedback if you are going to support SSR in the future ( which I do this is importat for most modren JS frameworks )

### Source

External (Customer)

**Comment by tnorling** [comment]
Angular 18 is officially supported as of last Friday - sample is available [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-angular-v3-samples/angular18-standalone-sample)
