### ISSUE TITLE
Getting  AADB2C90079 after B2C login portal returns to app 

### ISSUE THREAD

**Issue by hekatx** [AzureAD/microsoft-authentication-library-for-js#7135]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.15.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.0.17

### Public or Confidential Client?

Public

### Description

I have a React SPA app where I can't authenticate. Everytime I try, after the redirect ends, I get the following error: 
"AADB2C90079: Clients must send a client_secret when redeeming a confidential grant."

I don't know where to start debugging this issue. I looked through some similar issues and I asked the DevOps people and apparently the redirectUri is set as SPA, but I don't know why I keep getting this issue

### Error Message

{
    "error": "invalid_request",
    "error_description": "AADB2C90079: Clients must send a client_secret when redeeming a confidential grant.\r\nCorrelation ID: 91004093-8b10-4c12-90a4-898b7c1a696a\r\nTimestamp: 2024-05-29 23:05:42Z\r\n"
}

### MSAL Logs

[Wed, 29 May 2024 23:05:41 GMT] : [] : @azure/msal-browser@3.15.0 : Info - Emitting event: msal:initializeStart
Tenant.tsx?t=1717022800564:54 [Wed, 29 May 2024 23:05:41 GMT] : [] : @azure/msal-browser@3.15.0 : Info - Emitting event: msal:initializeEnd
Tenant.tsx?t=1717022800564:54 [Wed, 29 May 2024 23:05:41 GMT] : [] : @azure/msal-browser@3.15.0 : Info - initialize has already been called, exiting early.
Tenant.tsx?t=1717022800564:54 [Wed, 29 May 2024 23:05:41 GMT] : [] : @azure/msal-browser@3.15.0 : Info - Emitting event: msal:handleRedirectStart
Tenant.tsx?t=1717022800564:54 [Wed, 29 May 2024 23:05:41 GMT] : [] : @azure/msal-react@2.0.17 : Info - MsalProvider - msal:handleRedirectStart results in setting inProgress from startup to handleRedirect
rudderstack.js:8 rudder started succesfully
Tenant.tsx?t=1717022800564:54 [Wed, 29 May 2024 23:05:42 GMT] : [] : @azure/msal-browser@3.15.0 : Info - Emitting event: msal:loginFailure
Tenant.tsx?t=1717022800564:54 [Wed, 29 May 2024 23:05:42 GMT] : [] : @azure/msal-browser@3.15.0 : Info - Emitting event: msal:handleRedirectEnd
Tenant.tsx?t=1717022800564:54 [Wed, 29 May 2024 23:05:42 GMT] : [] : @azure/msal-react@2.0.17 : Info - MsalProvider - msal:handleRedirectEnd results in setting inProgress from handleRedirect to none

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [X] Pending

### MSAL Configuration

```javascript

```

### Relevant Code Snippets

```javascript
const pca = new PublicClientApplication(config);
pca.initialize().then(() => {
  // Default to using the first account if no account is active on page load
  if (!pca.getActiveAccount() && pca.getAllAccounts().length > 0) {
    // Account selection logic is app dependent. Adjust as needed for different use cases.
    pca.setActiveAccount(pca.getAllAccounts()[0]);
  }

  // Optional - This will update account state if a user signs in from another tab or window
  pca.enableAccountStorageEvents();

  pca.addEventCallback((event) => {
    // @ts-expect-error ts is being mean
    if (event.eventType === EventType.LOGIN_SUCCESS && event.payload.account) {
      // @ts-expect-error ts is being mean
      const account = event.payload.account;
      pca.setActiveAccount(account);
    }
  });
});

export default function TenantProvider({ children }) {
  // irrelevant code
  return (
      <MsalProvider instance={pca}>{children}</MsalProvider>
  );
}
```

### Reproduction Steps

1. Call `pca.loginRedirect({ scope: ['openid'] })`

### Expected Behavior

That it logs in without issue

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by hekatx** [comment]
It was a misconfiguration on B2C. Closing.

**Comment by muraliispace** [comment]
@hekatx  please help withe configuration on B2c what needs to be changed the same issue I am facing currently

**Comment by hekatx** [comment]
> @hekatx please help withe configuration on B2c what needs to be changed the same issue I am facing currently

`redirectUri` wasn't really configured as an `SPA`. Verify that you've followed [the docs](https://learn.microsoft.com/en-us/azure/active-directory-b2c/tutorial-register-spa#register-the-spa-application)
