### ISSUE TITLE
Improve exception messages for loadExternalTokens

### ISSUE THREAD

**Issue by victor-pogor** [AzureAD/microsoft-authentication-library-for-js#7138]
### Core Library

MSAL.js (@azure/msal-browser)

### Wrapper Library

Not Applicable

### Public or Confidential Client?

Public

### Description

Hello, dear community,

I discovered that some error messages in this library are too generic and do not provide enough details on the type of error that occurred.

For example, the [loadExternalTokens()](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/4d3c84b3f5b633b269e46e03382fa8d834886ab0/lib/msal-browser/src/cache/TokenCache.ts#L79-L229) method has at least 3 checks that could throw the same `BrowserAuthErrorCodes.unableToLoadToken` code ([1](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/4d3c84b3f5b633b269e46e03382fa8d834886ab0/lib/msal-browser/src/cache/TokenCache.ts#L88), [2](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/4d3c84b3f5b633b269e46e03382fa8d834886ab0/lib/msal-browser/src/cache/TokenCache.ts#L213), [3](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/4d3c84b3f5b633b269e46e03382fa8d834886ab0/lib/msal-browser/src/cache/TokenCache.ts#L218)).

This method calls other methods like [loadIdToken()](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/4d3c84b3f5b633b269e46e03382fa8d834886ab0/lib/msal-browser/src/cache/TokenCache.ts#L299-L322) that also throw the [same code](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/4d3c84b3f5b633b269e46e03382fa8d834886ab0/lib/msal-browser/src/cache/TokenCache.ts#L319).

Since the code (and the mapped message) is the same in all exceptional cases, it is really hard to troubleshoot what went wrong, we can see only one exception: `Error loading token to cache.`

Looking into git blame, I noticed the messages were more explicit and descriptive before [this change](https://github.com/AzureAD/microsoft-authentication-library-for-js/commit/39ff93c407886f9d3883f814d4439f36dba69b11#diff-5f7831e13b2c981db1cd1b03fed5d4c547c6e15d722bedf343e48d5c98d22f8f).

I suggest two solutions here:
1. Add separate `BrowserAuthErrorCodes` (and messages) for each type of exception<br>For example `BrowserAuthErrorCodes.noClientInfoInResponseOrOptions`
2. Keep the same `BrowserAuthErrorCodes.unableToLoadToken` but use logger to provide more info on what went wrong<br>For example `this.logger.error("TokenCache - Please provide clientInfo in the response or options.")`

I would like to hear your feedback 😄 

Thanks,
Victor.

### Source

External (Customer)

**Comment by victor-pogor** [comment]
Hi @tnorling, is this issue closed?

Cause I see the PR has other changes related to `loadExternalTokens`, not the exception message improvements.

**Comment by tnorling** [comment]
@victor-pogor The linked PR does address your feedback amongst other changes. It removed most of the error scenarios outright, leaving only 2 error cases - one was changed to a more descriptive "non_browser_environment" error and the other now includes a log message describing why it threw. This change will be included in the next release.
