### ISSUE TITLE
How to force a `InteractionRequiredAuthError`? For integration testing

### ISSUE THREAD

**Issue by hterik** [AzureAD/microsoft-authentication-library-for-js#7140]
### Core Library

MSAL.js (@azure/msal-browser)

### Wrapper Library

MSAL React (@azure/msal-react)

### Public or Confidential Client?

Public

### Description

Hi
I'm in a situation where our application behaves very strange when msal throws a `InteractionRequiredAuthError` and application attempts to solve it with `acquireTokenRedirect`. 
The problem is that Interaction required only happens once every few days and the whole flow becomes very difficult to troubleshoot and reproduce.

Is there any way one can force such an error? Just unit testing the scenarios is not enough, because how `acquireTokenPopup`/ `acquireTokenRedirect` behave together with the browser and interaction with Azure is also very tightly coupled.

### Source

External (Customer)

**Comment by tnorling** [comment]
If you're testing manually you can delete the refresh token from local/session storage and set [CacheLookupPolicy](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/token-lifetimes.md#cache-lookup-policy) to "RefreshToken".

If you're attempting to write tests I recommend mocking the call.
