### ISSUE TITLE
MSAL for Salesforce LWC

### ISSUE THREAD

**Issue by jayatrir** [AzureAD/microsoft-authentication-library-for-js#7145]
### Core Library

MSAL.js v1 (@azure/msal or msal)

MSAL.js v2 (@azure/msal or msal)

### Wrapper Library

Not Applicable

### Public or Confidential Client?

Public

### Description

MSAL is not working for lightening web components when Lightening web security(LWS) is enabled. Could you create MSAL in compliance with Salesforce LWS?

### Source

External (Customer)

**Comment by ejahja** [comment]
Hi there! Thank you so much for raising this issue. We appreciate your feedback. We don't have plans right now to add support. You can file a compatibility request to LWS directly. Below is a link to their FAQ.
 
https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhelp.salesforce.com%2Fs%2FarticleView%3Fid%3D000392327%26type%3D1&data=05%7C02%7Cejahjaloo%40microsoft.com%7C65bc3ef1f96d4ab3fc4e08dc8976710a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638536389033174023%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=jXw2sg%2FAVgZriXrtsrTd3prYiueVPlPSfrQi86mpxhM%3D&reserved=0
