### ISSUE TITLE
Logout should use the EndSessionEndpoint when available

### ISSUE THREAD

**Issue by verbedr** [AzureAD/microsoft-authentication-library-for-js#715]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Other... **Improvement**
</code></pre>

## Browser:
- [x] All
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 1.0.0

## Current behavior

The logout will always call the authority endpoint followed with oauth2/v2.0/logout perhaps this is the default. But in some cases the OP is hanging on something. The redirect is going to sts.windows.net

## Expected behavior

Instead it would be more intuitive that we use the OP end_session_endpoint which points to login.windows.net in the case of an Azure AD B2B setup.

## Minimal reproduction of the problem with instructions

Configure an app with msal and an Azure AD B2B
Add an logout options in your page.
The logout will hang on 'select an account' page from azure ad without going forward to the close all windows message.

</code></pre>

**Comment by verbedr** [comment]
#716 
I created the PR in order to better explain the intend.

**Comment by sameerag** [comment]
Thanks @verbedr for taking the time for a PR. Let us check with our service team and others if this is aligned with their logout requirements, and I will respond if we can take this PR.

**Comment by DarylThayil** [comment]
#716  closes this ticket
