### ISSUE TITLE
v3 migration docs: CDN Usage for @azure/msal-browser

### ISSUE THREAD

**Issue by dvinci-klfr** [AzureAD/microsoft-authentication-library-for-js#7153]
### Core Library

MSAL.js (@azure/msal-browser)

### Wrapper Library

Not Applicable

### Public or Confidential Client?

Public

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/cdn-usage.md

### Description

In https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/cdn-usage.md there is a hint for using msal-browser in a packed and minified form: 

- Extract lib/msal-browser.js or lib/msal-browser.min.js from the downloaded package and serve it as a static asset with your app or host it on your own CDN

Within the downloaded package form https://github.com/AzureAD/microsoft-authentication-library-for-js/releases/tag/msal-browser-v3.16.0 -> https://github.com/AzureAD/microsoft-authentication-library-for-js/archive/refs/tags/msal-browser-v3.16.0.zip there are no such files.

I would either expext the file to be present in the ZIP, or a more detailed documention how to get them.

**Comment by tnorling** [comment]
> NOTE: Starting from MSAL.js v3 msal-browser is no longer hosted on the CDN. If you consume msal-browser from the CDN you will need to download msal-browser from **npm**

https://www.npmjs.com/package/@azure/msal-browser?activeTab=code
