### ISSUE TITLE
Missing release "@azure/msal-browser 2.39.0"

### ISSUE THREAD

**Issue by areriklq** [AzureAD/microsoft-authentication-library-for-js#7156]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.39.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

NPM reports a version 2.39.0 available of `msal-browser` but there is no such release in this repo.

https://www.npmjs.com/package/@azure/msal-browser/v/2.39.0

**Is 2.39.0 a legit release?**

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
N/A
```

### Relevant Code Snippets

```javascript
N/A
```

### Reproduction Steps

N/A

### Expected Behavior

A tag, release and release notes for the release if it is legit.

### Identity Provider

Entra ID (formerly Azure AD) / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by tnorling** [comment]
v2 is located on the `msal-lts` branch. You can find the release notes here: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/msal-lts/lib/msal-browser/CHANGELOG.md

**Comment by areriklq** [comment]
> v2 is located on the `msal-lts` branch. You can find the release notes here: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/msal-lts/lib/msal-browser/CHANGELOG.md

Thanks for pointing out the changelog!

The tag seems missing however, v2.38.4 exists but not v2.39.0. Maybe that is on purpose?
![image](https://github.com/AzureAD/microsoft-authentication-library-for-js/assets/156663890/9780937e-003e-4fdd-9ab3-6721f3901219)
