### ISSUE TITLE
MSAL v2 to v3 migration | confusion about the initialization

### ISSUE THREAD

**Issue by zombaki** [AzureAD/microsoft-authentication-library-for-js#7177]
### Core Library

MSAL Node (@azure/msal-node)

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Public or Confidential Client?

Public

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-angular-v3-samples/angular16-sample-app/src/app/app.module.ts#L25

### Description

In the documentation for migrating to version 2, we are instructed to create an instance of MSAL with two options:
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/v2-migration.md#application-instantiation

However, in the MSAL Angular version 3 sample, this step is not performed:
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-angular-v3-samples/angular16-sample-app/src/app/app.module.ts#L25

This discrepancy has led to confusion regarding whether the sample code is an accurate reference.

**Comment by jo-arroyo** [comment]
@zombaki The Angular 16 sample application creates a new instance of `PublicClientApplication` in the app.module.ts, as you linked above. For MSAL Angular v3, `initialize` is called in `handleRedirectObservable` in [`MsalService`](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/src/msal.service.ts#L58). As the sample application bootstraps the [MsalRedirectComponent](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/2b6041320cc8bcf007dd2e6bab41745c81057aec/lib/msal-angular/src/msal.redirect.component.ts#L24) which subscribes to `handleRedirectObservable`, `initialize` is called when the application is run. 

See the [MSAL Angular upgrade guide](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/v2-v3-upgrade-guide.md#initialization) for more details. 

Closing with comment.
