### ISSUE TITLE
Duplicate ManagedIdentitySourceName 

### ISSUE THREAD

**Issue by maorleger** [AzureAD/microsoft-authentication-library-for-js#7181]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

2.9.2

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Confidential

### Description

ManagedIdentitySourceNames defines both `Imds` and `DefaultToImds` but only one of these is actually used in [getManagedIdentitySource](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/2b6041320cc8bcf007dd2e6bab41745c81057aec/lib/msal-node/src/client/ManagedIdentityClient.ts#L92-L113)

We should remove one of the two, probably `Imds`, from the public API 

Alternatively, you could update the `getManagedIdentitySource`s type to:

```
public getManagedIdentitySource(): Exclude<ManagedIdentitySourceNames, "Imds">
```

So developers writing code against this know which value to check against when they want to do something special for IMDS flows (like probing the IMDS endpoint) instead of always remembering to check both values (or looking into the implementation to see that only one is actually used)

[playground example](https://www.typescriptlang.org/play/?#code/KYDwDg9gTgLgBAYwgOwM7wLIENlYObAAmAkocMjAJYwCeAyhAK5QLAByWAtsKnALxwA3gCg4YuAEEAClID6dAKIAlAGrEAwgoBccAEQSwYOsCgA3Sq10AaUeIkAtAKpKFsiUvU79AL2bAJLNa2YuoAMgDyjgAi8gASCqGhXuoANkyEdAAWwCkpQeJwUQoAYhKOoQAqshXhssQYUXReUcAAZliMKTAVEMSchKj54vWNXn0DQ2KKqhqupQBCShpexmYWwMVYAEZQFkEAvnBYvEhoMADcwgD0AFQ3ojdwFdlw2LgEJGQU1PRMLOxcHhwWhgYAPOAAATAjC2KQsDyuwlAkFgwJooNeOHwRFI5CotAYzFYHG4vD4wTgAAoQcAIK1Me8cV98b8iQDSQBKADaAGtgDQ6WjQYK3tjPnifoT-iSeABdS6iVqMZAIKgoOAEGCij6474Ev6sSkcnQKEAIFKMMgAHm1TIl+rZMtQVj040GAD4hBSoMAYMxkHoWu1Ot1ev1Bpc4PthKJTug4JRUG7+BrfbbxXrWf8jfw+AJdEGOl0em7dEA)

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
{}
```

### Relevant Code Snippets

```javascript
N/A
```

### Reproduction Steps

N/A

### Expected Behavior

N/A

### Identity Provider

Entra ID (formerly Azure AD) / MSA

### Browsers Affected (Select all that apply)

None (Server)

### Source

Internal (Microsoft)

**Comment by Robbie-Microsoft** [comment]
Not fixing, per offline discussion
