### ISSUE TITLE
AcquireTokenForManagedIdentity should throw if a user-assigned managed identity clientID or resourceID is supplied when not supported

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-js#7198]
The following ManagedIdentitySources do not currently support user-assigned managed identities:

AzureArc, CloudShell, ServiceFabric

If a user-assigned clientId or resourceId is specified for these sources, we should throw with a message similar to:

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/5c7c527b173b5f2a719926fb89ccd68bc55d1b3e/src/client/Microsoft.Identity.Client/MsalErrorMessage.cs#L424

This behavior should be consistent cross-language.

 ### Original issue: 
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4837

**Comment by rayluo** [comment]
Discussed [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4837#issuecomment-2229960868). Feel free to reopen this issue if a discrepancy will be observed.
