### ISSUE TITLE
PublicClientApplication sometimes failing on instantiation

### ISSUE THREAD

**Issue by cherewaty** [AzureAD/microsoft-authentication-library-for-js#7217]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.19.1

### Wrapper Library

Not Applicable

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

I'm using `@azure/msal-browser` in a Remix app, in [SPA mode](https://remix.run/docs/en/main/guides/spa-mode). I elected not to use `@azure/msal-react` at all, since the primary place I need to interact with MSAL is in route `clientLoader()` functions, where I don't have access to React context.

I'm running into an issue where the `PublicClientApplication` instance is sometimes failing to instantiate. 

Around 90% of the time in Chrome and Firefox, the `PublicClientApplication` instantiates, `initialize()`s, and works as expected. I get verbose logs about the MSAL instance's state.

Around 10% of the time, I encounter an error at `new PublicClientApplication()` and only the `HydrateFallback` in the code snippet below renders, not `App`.

I haven't run into this failure at all with Safari.

I also can only occasionally reproduce this with a production build of the app, but never with a `@remix-run/dev` Vite dev server.

### Error Message

In Firefox:
<img width="637" alt="firefox" src="https://github.com/user-attachments/assets/015ce65a-9ac8-4d40-b60d-c07e85f982aa">

In Chrome:
<img width="790" alt="chrome" src="https://github.com/user-attachments/assets/3e0a7641-8ded-464b-a395-b0982b9e5077">

### MSAL Logs

These logs are what a successful page load looks like. When I encounter the error at `isCredentialKey`, I don't get any MSAL log output.
```
[Wed, 24 Jul 2024 18:33:50 GMT] : [] : @azure/msal-browser@3.19.1 : Info - Emitting event: msal:initializeStart root-BD-gax1r.js:23:431
[Wed, 24 Jul 2024 18:33:50 GMT] : [] : @azure/msal-browser@3.19.1 : Info - Emitting event: msal:initializeEnd root-BD-gax1r.js:23:431
[Wed, 24 Jul 2024 18:33:50 GMT] : [] : @azure/msal-common@14.13.1 : Info - CacheManager:getIdToken - Returning ID token root-BD-gax1r.js:23:431
[Wed, 24 Jul 2024 18:33:50 GMT] : [] : @azure/msal-browser@3.19.1 : Info - Emitting event: msal:handleRedirectStart root-BD-gax1r.js:23:431
[Wed, 24 Jul 2024 18:33:50 GMT] : [0190e605-60ae-798e-8973-880c96edb226] : msal.js.browser@3.19.1 : Info - handleRedirectPromise called but there is no interaction in progress, returning null. root-BD-gax1r.js:23:431
[Wed, 24 Jul 2024 18:33:50 GMT] : [] : @azure/msal-browser@3.19.1 : Info - Emitting event: msal:handleRedirectEnd root-BD-gax1r.js:23:431
[Wed, 24 Jul 2024 18:33:51 GMT] : [] : @azure/msal-browser@3.19.1 : Info - initialize has already been called, exiting early. root-BD-gax1r.js:23:431
[Wed, 24 Jul 2024 18:33:51 GMT] : [] : @azure/msal-common@14.13.1 : Info - CacheManager:getIdToken - Returning ID token root-BD-gax1r.js:23:431
[Wed, 24 Jul 2024 18:33:51 GMT] : [] : @azure/msal-browser@3.19.1 : Info - Emitting event: msal:acquireTokenStart root-BD-gax1r.js:23:431
[Wed, 24 Jul 2024 18:33:51 GMT] : [] : @azure/msal-common@14.13.1 : Info - CacheManager:getAccessToken - Returning access token root-BD-gax1r.js:23:431
[Wed, 24 Jul 2024 18:33:51 GMT] : [] : @azure/msal-common@14.13.1 : Info - CacheManager:getIdToken - Returning ID token root-BD-gax1r.js:23:431
[Wed, 24 Jul 2024 18:33:51 GMT] : [] : @azure/msal-browser@3.19.1 : Info - Emitting event: msal:acquireTokenSuccess root-BD-gax1r.js:23:431
[Wed, 24 Jul 2024 18:33:51 GMT] : [] : @azure/msal-common@14.13.1 : Info - CacheManager:getIdToken - Returning ID token root-BD-gax1r.js:23:431
[Wed, 24 Jul 2024 18:33:51 GMT] : [] : @azure/msal-common@14.13.1 : Info - CacheManager:getIdToken - Returning ID token
```

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
{
  auth: {
    clientId: "XXXXX",
    authority: "https://login.microsoftonline.us/XXXXXX",
    redirectUri: "/",
    postLogoutRedirectUri: "/",
    navigateToLoginRequestUrl: false,
  },
  cache: {
    cacheLocation: "localStorage",
    storeAuthStateInCookie: false,
  }
}
```

### Relevant Code Snippets

```javascript
// app/root.tsx from Remix app, with @mui/joy and @tanstack/react-query pieces removed for clarity

import type {
  AuthenticationResult,
  RedirectRequest,
} from "@azure/msal-browser";
import { EventType, PublicClientApplication } from "@azure/msal-browser";
import {
  Await,
  Links,
  Meta,
  Outlet,
  Scripts,
  ScrollRestoration,
  defer,
  useLoaderData,
} from "@remix-run/react";
import { Suspense } from "react";
import { LogLevel } from "@azure/msal-browser";
import { PageLoading } from "~/components/PageLoading";

export const msalInstance = new PublicClientApplication({
  auth: {
    clientId: **MSAL_CLIENT_ID**,
    authority: **MSAL_AUTHORITY**,
    redirectUri: "/",
    postLogoutRedirectUri: "/",
    navigateToLoginRequestUrl: false,
  },
  cache: {
    cacheLocation: "localStorage",
    storeAuthStateInCookie: false,
  },
  system: {
    loggerOptions: {
      loggerCallback: (level, message, containsPii) => {
        if (containsPii) {
          return;
        }
        switch (level) {
          case LogLevel.Error:
            console.error(message);
            return;
          case LogLevel.Info:
            console.info(message);
            return;
          case LogLevel.Verbose:
            console.debug(message);
            return;
          case LogLevel.Warning:
            console.warn(message);
            return;
          default:
            return;
        }
      },
    },
  },
});

// Listen for sign-in event and set active account
msalInstance.addEventCallback(async (event) => {
  const payload = event.payload as RedirectRequest;
  if (event.eventType === EventType.LOGIN_SUCCESS && payload?.account) {
    const account = payload?.account;
    msalInstance.setActiveAccount(account);
    window.location.href = payload.state || "/";
  }
});

export async function clientLoader() {
  let authenticationResult: Promise<AuthenticationResult | null>;
  await msalInstance.initialize();
  authenticationResult = msalInstance.handleRedirectPromise();
  return defer({ authenticationResult });
}

export function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="manifest" href="/manifest.json" />
        <Meta />
        <Links />
        <link rel="stylesheet" href="/fallback.css" />
      </head>
      <body>
        {children}
        <ScrollRestoration />
        <Scripts />
      </body>
    </html>
  );
}

export function HydrateFallback() {
  return (
    <div className="hydrate-fallback-container">
      <span className="hydrate-fallback-loader" />
    </div>
  );
}

export default function App() {
  const { authenticationResult } = useLoaderData<typeof clientLoader>();

  return (
    <Suspense fallback={<PageLoading />}>
      <Await
        resolve={authenticationResult}
        errorElement={<div>Authentication failed.</div>}
      >
        <Outlet />
      </Await>
    </Suspense>
  );
}
```

### Reproduction Steps

Create `new PublicClientApplication()` with included configuration. Fails in Firefox and Chrome somewhere around 10% of the time.

### Expected Behavior

`PublicClientApplication` should successfully instantiate 100% of the time.

### Identity Provider

Entra ID (formerly Azure AD) / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox

### Source

External (Customer)

**Comment by konstantin-msft** [comment]
Hi @cherewaty.

I can only guess here given that I don't have the full app code snippet and I am not familiar with `@remix`. My guess is that the reference to client id, which is passed to MSAL.js, gets nullified outside of MSAL.js. MSAL.js itself does not modify the client id. Another concern is that it's not reproducible with `@remix-run/dev` so it's probably an issue with the framework itself.

Can you please debug this on your end? I would suggest catching the error in debugger and inspecting the stack trace to make sure that the client id is set.

**Comment by cherewaty** [comment]
>gets nullified outside of MSAL.js

That was the key.

I'm using https://import-meta-env.org to inject environment variables (like the MSAL client ID) at run time instead of at build time. Most of the time my external script that gets the ENV injected loaded quickly enough, but when it didn't, the `PublicClientApplication` instantiated with a null.

I swapped around the order of `<script>` tags in the DOM so my run time environment variables are always set first.

Problem solved!

Thanks for the hint @konstantin-msft
