### ISSUE TITLE
LoginPopup throws "wrong reply URL" when logging in from routes

### ISSUE THREAD

**Issue by teocomi** [AzureAD/microsoft-authentication-library-for-js#724]
## I'm submitting a...

- [X] Bug report  

## Browser:
- [X] Chrome version 74

## Library version
Library version: 1.0.1

## Current behavior
If I try to access my SPA from a route that is not listed in my app registration I get the "wrong reply URL" error. Eg: http://myapp.com works fine, but not http://myapp.com/about
Since the app uses dynamic routing it'd be impossible to add all routes and the Azure portal doesn't let me use wildcards for the app registration.

## Expected behavior
Should be able to log in from any route not just the base address.

## Minimal reproduction of the problem with instructions

This my UserAgentApplication config
```
  msalConfig: {
    auth: {
      clientId: "xxx",
      authority: "xxx"
    },
    cache: {
      cacheLocation: "localStorage",
      storeAuthStateInCookie: true
    }
  } 
```

I initialise UserAgentApplication once inside vuex.
The rest of my code was taken from: https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-javascript-spa
</code></pre>

**Comment by peshos** [comment]
You cannot have wildcards in the redirectUri for security reasons. More [here](https://tools.ietf.org/html/rfc6749#section-3.1.2).
You can do:
1. vuex stores the path in localStorage/cookie prior to authenticating.
2. Main route checks for a saved value after authenticating and if existing, delete the setting and transfer to the saved path.

**Comment by DarylThayil** [comment]
@teocomi Thanks for the issue, If you use the `redirectUri` field in configuration, you can specify the redirect path. 

The error is not complaining about the path you are logging in from, rather the path you are redirecting to.  If you don't set it, it defaults to your current page. 

That way you can login from an page, but are redirected to a page that is white listed to receive the auth parameters returned from the server. 

Closing for now, please reopen if this does not solve your problem

**Comment by teocomi** [comment]
That worked, how could have I missed that!!!
Thanks Daryl!
