### ISSUE TITLE
AuthError is not defined

### ISSUE THREAD

**Issue by NaveenJamdagani** [AzureAD/microsoft-authentication-library-for-js#7242]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.20.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.0.22

### Public or Confidential Client?

Confidential

### Description

I am getting this error saying "Uncaught (in promise) ReferenceError: AuthError is not defined".  It was working fine yesterday.
Work with npm start, but when serve build, not working.

### Error Message

![authErro](https://github.com/user-attachments/assets/64dc9260-f626-491a-bf24-a04d70b1f9b2)

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
{
  auth: {
    clientId: "process.env.REACT_APP_MICROSOFT_CLIENT_ID"
  },
}
```

### Relevant Code Snippets

```javascript
NA
```

### Reproduction Steps

1. npm install.
2. Build the react-app using npm run build
3. serve the apps using serve -s build
4. when accessing http://localhost:3000/ , its blank and showing the error on browser.

### Expected Behavior

It should open the tool, currently page got blank with some console error related to Autherro.

### Identity Provider

Entra ID (formerly Azure AD) / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox

### Source

Internal (Microsoft)

**Comment by kurroo10** [comment]
same here https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/7240

**Comment by kurroo10** [comment]
can someone rise this ? my production is crashing now @jo-arroyo @tnorling  ?

**Comment by NaveenJamdagani** [comment]
> can someone rise this ? my production is crashing now @jo-arroyo @tnorling ?

You can try using old package-lock.json file and push that file to production. It will solve the issue for now.

**Comment by ikrma47** [comment]
Hi I'm also facing the exact same error, It's happening all of the sudden and crashing my production to a blank page.

**Comment by kurroo10** [comment]
> > can someone rise this ? my production is crashing now @jo-arroyo @tnorling ?
> 
> You can try using old package-lock.json file and push that file to production. It will solve the issue for now.

thank you, yes its working fine now.

> Hi I'm also facing the exact same error, It's happening all of the sudden and crashing my production to a blank page.

try mine version, its working for me.

```
    "@azure/msal-browser": "3.10.0",
    "@azure/msal-react": "2.0.12",
```

note:
for anyone facing this, dont forget to remove the caret (^) to avoid updating package before its fixed properly.

**Comment by Gabriel-rd2** [comment]
I tried using this versions:
```
    "@azure/msal-browser": "3.10.0",
    "@azure/msal-react": "2.0.12",
```
 but the error is still happening.

The weird thing is, i have a production build currently running without erros using these versions:
```
    "@azure/msal-browser": "^2.32.0",
    "@azure/msal-react": "^1.5.7",
```
But when i install them and run my build locally, i get the error.

**Comment by tnorling** [comment]
Can someone please share a minimal reproduction?
