### ISSUE TITLE
Redirect user to a custom URL after access token expires

### ISSUE THREAD

**Issue by artemkolotilkin** [AzureAD/microsoft-authentication-library-for-js#7244]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.38.1

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

2.5.10

### Public or Confidential Client?

Confidential

### Description

I'm trying to redirect a user to a custom login page after their access token expires. But instead of a user being redirect to a provided URL, they are being sent to a standard Microsoft hosted login page. Any suggestions how to change that? Please see my code below. Thanks.

```
this.msalBroadcastService.msalSubject$.subscribe((msalSubject) => {
  if (msalSubject.eventType === 'msal:acquireTokenFailure') {
    this.router.navigate(['/', AppRoutes.LOGIN]);
  }
});
```

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
{
  auth: {
    clientId: environment.appCustomConfig.b2c.clientId, // This is the ONLY mandatory field that you need to supply.
    authority: b2cPolicies.authorities.signUpSignIn.authority, // Defaults to "https://login.microsoftonline.com/common"
    knownAuthorities: [b2cPolicies.authorityDomain], // Mark your B2C tenant's domain as trusted.
    redirectUri: '/auth', // Points to window.location.origin by default. You must register this URI on Azure portal/App Registration.
    postLogoutRedirectUri: '/', // Points to window.location.origin by default.
  },
  cache: {
    cacheLocation: BrowserCacheLocation.SessionStorage, // Configures cache location. "sessionStorage" is more secure, but "localStorage" gives you SSO between tabs.
    storeAuthStateInCookie: isIE, // Set this to "true" if you are having issues on IE11 or Edge. Remove this line to use Angular Universal
  },
  system: {
    /**
     * Below you can configure MSAL.js logs. For more information, visit:
     * https://docs.microsoft.com/azure/active-directory/develop/msal-logging-js
     */
    loggerOptions: {
      loggerCallback(logLevel: LogLevel, message: string) {
        console.log(logLevel, message);
      },
      logLevel: environment.production ? LogLevel.Error : LogLevel.Warning,
      piiLoggingEnabled: false,
    },
  },
}
```

### Relevant Code Snippets

```javascript
this.msalBroadcastService.msalSubject$.subscribe((msalSubject) => {
  if (msalSubject.eventType === 'msal:acquireTokenFailure') {
    this.router.navigate(['/', AppRoutes.LOGIN]);
  }
});
```

### Reproduction Steps

1. Aquire access token via Azure B2C auth flow.
2. Wait for the access token to expire.
3. Perform any action that requires the access token validation.

Notice that the user is redirected to the Microsoft hosted login page.

### Expected Behavior

Based on the custom redirect logic, expected behavior is for a user to be redirected to an internal URL within the application. 

### Identity Provider

Azure B2C Basic Policy

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

External (Customer)

**Comment by tnorling** [comment]
Do you have an interceptor or guard configured? That's likely what's causing the redirect to the login page. If you want to change that behavior you will need to write your own interceptor/guard rather than using the ones we provide.
