### ISSUE TITLE
MatchingResources Missing From msal.interceptor.config.ts

### ISSUE THREAD

**Issue by oliverdrummond** [AzureAD/microsoft-authentication-library-for-js#7255]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

msal-angular-v3.0.23

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

msal-angular-v3.0.23

### Public or Confidential Client?

Public

### Description

Until [v3.0.18](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/msal-angular-v3.0.18/lib/msal-angular/src/msal.interceptor.config.ts), `msal.interceptor.config.ts` had the export for `MatchingResources`

```ts
export type MatchingResources = {
  absoluteResources: Array<string>;
  relativeResources: Array<string>;
};
```

On version [3.0.19](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/msal-angular-v3.0.19/lib/msal-angular/src/msal.interceptor.config.ts) the export was removed and still not available on [v3.0.23](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/msal-angular-v3.0.23/lib/msal-angular/src/msal.interceptor.config.ts)

### Error Message

TS2305: Module '"@azure/msal-angular/msal.interceptor.config"' has no exported member 'MatchingResources'.

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
{
    auth: {
            clientId: authConfig.clientId,
            authority: `https: //login.microsoftonline.com/${authConfig.tenantId}`, // Defaults to 'https://login.microsoftonline.com/common'
            redirectUri: baseHref + '/auth/', // Points to window.location.origin. You must register this URI on Azure portal/App Registration.
            postLogoutRedirectUri: baseHref + '/',
    },
        cache: {
            cacheLocation: BrowserCacheLocation.LocalStorage,
            storeAuthStateInCookie: isIE,
    },
        system: {
            loggerOptions: {
                loggerCallback(logLevel: LogLevel, message: string) {
                    console.log(message)
            },
                logLevel: LogLevel.Info,
                piiLoggingEnabled: false
        }
    },
}
```

### Relevant Code Snippets

```javascript
export type MatchingResources = {
  absoluteResources: Array<string>;
  relativeResources: Array<string>;
};
```

### Reproduction Steps

1. Just check the diff between version 3.0.18 and 3.0.19

### Expected Behavior

Keep the exported type or provide an alternative

### Identity Provider

Entra ID (formerly Azure AD) / MSA

### Browsers Affected (Select all that apply)

Chrome, Firefox, Edge, Safari

### Regression

3.0.18

### Source

External (Customer)

**Comment by tnorling** [comment]
This type was never part of the [public surface](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/src/public-api.ts) so you should not be dependent on it. Some of the implementation details of the interceptor needed to change to fix some bugs which is why this was removed. 

Can you help me understand the impact of its removal to your specific requirements so I might suggest an alternative approach using API stable exports?
