### ISSUE TITLE
MsalGuard redirect to login instead of automatically authenticating?

### ISSUE THREAD

**Issue by umagon** [AzureAD/microsoft-authentication-library-for-js#7257]
### Core Library

MSAL.js (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Public or Confidential Client?

Public

### Description

I was checking this issue https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/3047 and the OP wanted to login automatically upon entering a protected path.

I want the opposite, I would like `MsalGuard` to redirect to my login page instead of trying to automatically authenticate (thus triggering a `msal:loginStart` event) upon arrival to a protected route. I only want the app to try to authenticate when the user clicks on my "SSO Login" button.

### My Setup
`PathLocationStrategy`, `MsalRedirectComponent` (bootstrapped in `app.module`) in its own `/auth` route, with its tag present in `index.html`. Login page with a button that calls `loginRedirect()`. Using `logoutRedirect({ account })` to logout with `postLogoutRedirectUri` to my login page, `MsalGuard` protecting all routes except `/auth`, `/login` and error pages, `RoleGuard` protecting certain screens.

### Source

External (Customer)

**Comment by tnorling** [comment]
This is more of a routing problem than an auth problem so this is not something we're going to build into the library, however, you can absolutely build your own Guard to handle this.
