### ISSUE TITLE
Example for Angular 18  Logging.md page is not found

### ISSUE THREAD

**Issue by DavisSylvester** [AzureAD/microsoft-authentication-library-for-js#7272]
### Core Library

MSAL.js (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Public or Confidential Client?

Public

### Documentation Location

logging.md

### Description

When accessing the logging.md page with the following url `https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-angular/docs/v2-docs/logging.md` the page is not found.

**Comment by jo-arroyo** [comment]
Closing as answered in #7273
