### ISSUE TITLE
v2-docs path not found

### ISSUE THREAD

**Issue by DavisSylvester** [AzureAD/microsoft-authentication-library-for-js#7273]
### Core Library

MSAL.js (@azure/msal-browser)

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Public or Confidential Client?

Public

### Documentation Location

https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-angular/docs/v2-docs

### Description

Seems that the URL path `https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-angular/docs/v2-docs` isn't found.   

None of the documentation hyperlinks are accessible.

**Comment by jo-arroyo** [comment]
@DavisSylvester As MSAL Angular v3 has been released, MSAL Angular v2 docs can be found her: https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/msal-lts/lib/msal-angular/docs/v2-docs/
