### ISSUE TITLE
_this.logger.warning is not a function

### ISSUE THREAD

**Issue by oehm-smith** [AzureAD/microsoft-authentication-library-for-js#728]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [X] Chrome version 74.0.3729.157
- [X] Firefox version 66.0.5
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 1.0.1 (latest at this date of 24.5.19)

## Current behavior
I added logging as per https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging to end up with:

                    ```
logger: {
    localCallback: loggerCallback,
    level: LogLevel.Verbose,
    piiLoggingEnabled: true,
    correlationId: '1234',
}
```

I saw this error in the browser console:

```
core.js:15724 ERROR Error: Uncaught (in promise): TypeError: _this.logger.warning is not a function
TypeError: _this.logger.warning is not a function
    at UserAgentApplication.js:471
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:391)
    at Object.onInvoke (core.js:17299)
```

I had to add ALL logger fields to remove this error and get the application working.

```
logger: {
                        localCallback: loggerCallback,
                        level: LogLevel.Verbose,
                        piiLoggingEnabled: true,
                        correlationId: '1234',
                        logMessage: loggerCallback,
                        executeCallback: loggerCallback,
                        errorPii: singleMessage,
                        error: singleMessage,
                        warning: singleMessage,
                        warningPii: singleMessage,
                        info: singleMessage,
                        infoPii: singleMessage,
                        verbose: singleMessage,
                        verbosePii: singleMessage
}
```

## Expected behavior
I would think that most of those fields are optional - they could default to an already given loggerCallback.  Or the doco could be updated to say they need to be populated also.

I also added a comment to that https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging page to say it isn't showing all the fields of Logger (before I discovered the error).

## Minimal reproduction of the problem with instructions
Follow https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging

</code></pre>

**Comment by DarylThayil** [comment]
Thanks for sharing @oehm-smith 
I think that this is valid feedback. 
We are working on shipping Telemetry soon and then reevaluating our logging from the library. 
For now I believe what you did, implementing all the functions is the workaround, but you are right, we should have some defaults that if not implemented, are put in.
I am going to put a work item in for the team.
This should be a part of a release in the next month or so, since its a small improvement.

**Comment by dipesh-wadhwa** [comment]
@DarylThayil this issue still exists in 1.0.1
I have added all parameters as suggest by @oehm-smith but it gives same error - _this.logger.warning is not a function

**Comment by oehm-smith** [comment]
Specifically I now have:

            const loggerCallback = (logLevel, message, containsPii) => {
                console.log(`Auth: [${logLevel} ${message}`);
            };
            const logger = new Logger(
                loggerCallback,
                {correlationId: '1234', level: LogLevel.Info, piiLoggingEnabled: true});

            const data = await this.getIds();

            this.msal = new UserAgentApplication(
                {
                    auth: {
                        clientId: data.clientId,
                        authority: 'https://login.microsoftonline.com/organizations',
                        redirectUri: Uri + '/login',
                    },
                    cache: {
                        cacheLocation: 'localStorage',
                        storeAuthStateInCookie: true
                    },
                    system: {
                        logger
                    }
                }
            );

**Comment by DarylThayil** [comment]
@sameerag  can you investigate this since you tested this ? Thanks!

**Comment by gauravgoyal5** [comment]
Is this working?
