### ISSUE TITLE
No event emitted when token is in session storage

### ISSUE THREAD

**Issue by xenalite** [AzureAD/microsoft-authentication-library-for-js#729]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version 71.0.3578.98
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version
<pre><code>
Library version: @azure/msal-angular 0.1.2
Library version: msal 0.2.1
</code></pre>

## Current behavior
When the page is refreshed, and tokens are stored in session storage, the broadcast service does not emit any events.

## Expected behavior
Broadcast service to emit login success.

## Minimal reproduction of the problem with instructions
- Go through the normal redirect flow.
- Angular SPA is authenticated.
- Login success event is emitted by broadcast service.
- Session storage is populated with msal keys.
- Refresh the page.
- MSAL service picks up the token from session storage instead of URL fragment.
- No event is emitted by broadcast service to say we are authenticated.

We use ngrx and broadcast service to listen on events from MSAL - only once login success / acquire token success events are emitted, do we show the remaining page content. Since this event is never emitted, we get a blank page.

**Comment by sameerag** [comment]
Link to #786. Keeping it open until we determine if a better design of guards in the new wrapper solves this or if there is interim mitigation for this behavior.

**Comment by DarylThayil** [comment]
@xenalite are you saying that you want the broadcast to happen on every page load and not just on the original token acquisition"?

**Comment by xenalite** [comment]
@DarylThayil Yes. If a token is already in storage on page load, an event should be emitted.

**Comment by DarylThayil** [comment]
hmmm I could be wrong but this seems outside of the design intent.

When a token is received we emit, if a token is cached it is something different altogether

**Comment by xenalite** [comment]
It doesn't really matter to me what type of event is emitted, as long as one is. Could even be a new one to say we are in authenticated state. Currently there is no way to differentiate between a state where you are authenticated using a stored token, or state when authentication flow has not even begun yet.

**Comment by DarylThayil** [comment]
we do have msal.getAccount() which will return null or a user object which is the general direction we give to checking if a user is logged in or not

**Comment by jasonnutter** [comment]
Tracking as a part of #786 .
