### ISSUE TITLE
Token renewal for multiple asynchronously triggered renewal requests is not supported

### ISSUE THREAD

**Issue by austindyoung** [AzureAD/microsoft-authentication-library-for-js#73]
Currently, if a UI action asynchronously triggers multiple authenticated requests, only one token will get resolved. This is because only one iframe request ever gets made and the callback values set on `window.callbacksMappedToRenewState` are set for their unique authentication request state GUIDs.

**Comment by rohitnarula7176** [comment]
@austindyoung Can you set up a small code repro to explain this issue. I can then compare your PR to see the problem.

**Comment by rohitnarula7176** [comment]
@austindyoung I think there was a minor change required in the library to fix this issue. I have made that change in my branch https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/rohitnarula7176/Issue_73. I reviewed your pull request but I don't think we need those many changes.Can you please check and confirm.

**Comment by rohitnarula7176** [comment]
@austindyoung The current code in the branch will send one request per unique combination of scope. For instance, if you send 3 acquireToken requests with the same scope value, only one request will be sent in an iframe but the promise will get resolved 3 times with the same token. The previous code only resolved the promise once and that was a bug.

**Comment by rohitnarula7176** [comment]
@austindyoung Closing this issue. Fixed in dev. Please reopen if you still face issues.
