### ISSUE TITLE
Can you add a function setConfiguration in IPublicClientApplication

### ISSUE THREAD

**Issue by zkjxx1548** [AzureAD/microsoft-authentication-library-for-js#7305]
### Core Library

MSAL.js v1 (@azure/msal or msal)

### Wrapper Library

MSAL React (@azure/msal-react)

### Public or Confidential Client?

Public

### Description

I want to use different auth config(`PublicClientApplication`) when clicking different buttons in my login page, but i only find `getConfiguration` function in `IPublicClientApplication`. What should i do?

"@azure/msal-react": "^1.0.0"

### Source

External (Customer)

**Comment by sameerag** [comment]
I do not clearly understand the question, @zkjxx1548. Can you please list what your expectation is? FWIW, msal maintains one configuration per instance and you cannot switch between configurations unless you maintain multiple `PublicClientApplication` instances.
