### ISSUE TITLE
Extract Token in other formats

### ISSUE THREAD

**Issue by Bakura01** [AzureAD/microsoft-authentication-library-for-js#7307]
### Core Library

MSAL Node (@azure/msal-node)

### Wrapper Library

Not Applicable

### Public or Confidential Client?

Confidential

### Description

# Feature:
Is it possible to get multiple token formats from the token cache to use the objects in other ways like saving, refreshing or fetching items from the Microsoft Graph API.
The current object from the cache is not compatible with other projects like python-o365 etc.

### Example object:
```python
{'token_type': 'Bearer', 
'scope': ['openid', 'profile', 'email', 'https://graph.microsoft.com/Mail.Read', 'https://graph.microsoft.com/Mail.Read.Shared', 'https://graph.microsoft.com/Mail.Send', 'https://graph.microsoft.com/User.Read'], 
'expires_in': 3676, 
'ext_expires_in': 3676, 
'access_token': '##', 
'refresh_token': '##',
'expires_at': ##} 
```

### Source

External (Customer)

**Comment by sameerag** [comment]
This is by design. It is a JSON blob which is universally parsable in various platforms. 

cc @bgavrilMS in case you want to add anything else.

**Comment by bgavrilMS** [comment]
We do not expect app developers to look in the cache. The format of the cache is irrelevant to the client, only where you store it is relevant. Not sure what scenario you are trying to achieve.
