### ISSUE TITLE
GitHub Release for @azure/msal-browser 3.23.0

### ISSUE THREAD

**Issue by aram-yesildeniz** [AzureAD/microsoft-authentication-library-for-js#7309]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.1.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.23.0

### Public or Confidential Client?

Public

### Description

Hi, the version 3.23.0 of the msal-browser package was released 9 days ago on the npm registry: https://www.npmjs.com/package/@azure/msal-browser/v/3.23.0.

Where is the corresponding release for this version on GitHub?

The last release of msal-browser on GitHub is version 3.21.0: https://github.com/AzureAD/microsoft-authentication-library-for-js/releases/tag/msal-browser-v3.21.0

Thanks

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
-
```

### Relevant Code Snippets

```javascript
-
```

### Reproduction Steps

-

### Expected Behavior

Version 3.23.0 of @azure/msal-browser is released on GitHub

### Identity Provider

Entra ID (formerly Azure AD) / MSA

### Browsers Affected (Select all that apply)

Chrome

### Source

External (Customer)

**Comment by sameerag** [comment]
cc @hectormmg. Apologies for the miss. We have been trying some automation around our releases and this was a mix up. Will fix it going forward.
