### ISSUE TITLE
[Feature Request] Region auto enable on env variable

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-js#7328]
## Region auto-enable

1. On creation of a ConfidentialClientApplication, MSAL shall detect env variable `MSAL_FORCE_REGION`, which will be set to a specific region (e.g. `westus1`)
2. If this env variable is set, MSAL shall opt-in to ESTS-R with the value of this variable.

## Disabling the behavior

If region is explicitly set in MSAL to the string "DisableMsalForceRegion`, then the above no longer applies

## Conflicts with `WithAzureRegion(xyz)`

Use of the api `WithRegion(xyz)` takes precedence over the env variable. 

## Acceptance tests

For all of the tests, assume env variable MSAL_FORCE_REGION=eastus

1. No other config is used. ACTUAL region used: eastus
2. App developer configures region "westus" in MSAL. ACTUAL region used: westus
3. App developer configures region "DisableMsalForceRegion" in MSAL. ACTUAL region used: none

 ### Original issue: 
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4930

**Comment by Robbie-Microsoft** [comment]
MSALJS does not use the `WithRegion(xyz)` api like .net does.

**Comment by bgavrilMS** [comment]
> MSALJS does not use the `WithRegion(xyz)` api like .net does.

Can you please adapt the feature request to MSAL JS API. It's should not be that different ? Happy to review,.

**Comment by Robbie-Microsoft** [comment]
@bgavrilMS According to your acceptance tests, I think I don't even need to check for the value of the passed in region. If it exists at all, then it overrides the environment variable. Is that correct? It doesn't matter if it's passed in with a value of "DisableMsalForceRegion" or "alskdjh". However if it is "DisableMsalForceRegion", then I'll need to set it to `undefined` instead of leaving it as that string.

I was able to pass the three acceptance tests listed above with the code
```
const region: AzureRegion | undefined =
            ENV_MSAL_FORCE_REGION && !validRequest.azureRegion
                ? ENV_MSAL_FORCE_REGION
                : validRequest.azureRegion === "DisableMsalForceRegion"
                ? undefined
                : validRequest.azureRegion;
```
but I don't think this is the functionality you're looking for.

**Comment by bgavrilMS** [comment]
> @bgavrilMS According to your acceptance tests, I think I don't even need to check for the value of the passed in region. If it exists at all, then it overrides the environment variable. Is that correct? It doesn't matter if it's passed in with a value of "DisableMsalForceRegion" or "alskdjh". However if it is "DisableMsalForceRegion", then I'll need to set it to `undefined` instead of leaving it as that string.
> 
> I was able to pass the three acceptance tests listed above with the code
> 
> ```
> const region: AzureRegion | undefined =
>             ENV_MSAL_FORCE_REGION && !validRequest.azureRegion
>                 ? ENV_MSAL_FORCE_REGION
>                 : validRequest.azureRegion === "DisableMsalForceRegion"
>                 ? undefined
>                 : validRequest.azureRegion;
> ```
> 
> but I don't think this is the functionality you're looking for.

Using the ternary operator : there makes the code hard to read. Consider refactoring with `if` clauses. 

If the region API is set to `DisableMsalForceRegion`, then the request goes to ESTS, not to ESTS-R.
