### ISSUE TITLE
Public clients can't send a client secret with Confidential Client

### ISSUE THREAD

**Issue by servefast-cto** [AzureAD/microsoft-authentication-library-for-js#7334]
### Core Library

MSAL Node (@azure/msal-node)

### Core Library Version

^2.13.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

n/a

### Public or Confidential Client?

Confidential

### Description

We are  trying to exchange code for a token on the server with the provided code

### Error Message

"Error(s): 90023 - Timestamp: 2024-09-24 14:40:44Z - Description: AADSTS90023: Public clients can't send a client secret. Trace ID: f2487f9e-7626-4069-bb47-49373ad39702 Correlation ID: 89690675-7722-45be-ac7e-ca281607bf92 Timestamp: 2024-09-24 14:40:44Z - Correlation ID: 89690675-7722-45be-ac7e-ca281607bf92 - Trace ID: f2487f9e-7626-4069-bb47-49373ad39702"

### MSAL Logs

"Error(s): 90023 - Timestamp: 2024-09-24 14:40:44Z - Description: AADSTS90023: Public clients can't send a client secret. Trace ID: f2487f9e-7626-4069-bb47-49373ad39702 Correlation ID: 89690675-7722-45be-ac7e-ca281607bf92 Timestamp: 2024-09-24 14:40:44Z - Correlation ID: 89690675-7722-45be-ac7e-ca281607bf92 - Trace ID: f2487f9e-7626-4069-bb47-49373ad39702"

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
{
        clientId: IdSecretKey.value(),
        authority: "https://login.microsoftonline.com/common",
        clientSecret: ClientSecretKey.value(),
      }
```

### Relevant Code Snippets

```javascript
const config: Configuration = {
      auth: {
        clientId: IdSecretKey.value(),
        authority: "https://login.microsoftonline.com/common",
        clientSecret: ClientSecretKey.value(),
      },
    };

    const msalClient = new ConfidentialClientApplication(config);

    const token = await msalClient.acquireTokenByCode({
      code: code,
      scopes: ["openid", "offline_access", "User.Read", "Mail.Read"],
      redirectUri: outlookRedirectUrlKey.value(),
      codeVerifier: codeVerifier,
      authority: "https://login.microsoftonline.com/common",
    });
```

### Reproduction Steps

Get access code from the front end try to call provided function this from MSAL node

### Expected Behavior

I expect an access token but obviously something is wrong

### Identity Provider

Entra ID (formerly Azure AD) / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge

### Source

External (Customer)

**Comment by sameerag** [comment]
@servefast-cto is your app configuration `public` when registered in the portal? That could cause this error.

**Comment by servefast-cto** [comment]
@sameerag Thanks for quick reply. Do you mean this 

![image](https://github.com/user-attachments/assets/b51c746d-fc68-4c0e-8a41-bc95d09a31ca)

And also yes we have this enabled but i dont think we need it at this point 

![image](https://github.com/user-attachments/assets/0274bd91-6138-40f4-8fda-3060f83d1b54)


I would imagine than that we need to setup a Web Platform as well ? Can those work together ?

**Comment by servefast-cto** [comment]
I was able to fix this by changing it to web application and it now works i get the tokens back. Problem is that i can only get valid ms graph tokens for Public accounts. EntraID tokens dont work with graph i have registered an app as

`Accounts in any organizational directory (Any Microsoft Entra ID tenant - Multitenant) and personal Microsoft accounts (e.g. Skype, Xbox)`

Also there is a warning

`
Starting November 9th, 2020 end users will no longer be able to grant consent to newly registered multitenant apps without verified publishers.  [Add MPN ID to verify publisher](https://portal.azure.com/#)
`

Does this mean that i will not get a valid token for Entra ID users until i am verified publisher ?

**Comment by servefast-cto** [comment]
we gave up on MSAL and created our own implementation. Closing
