### ISSUE TITLE
@azure/msal-angular installation requires doesnt support node20+

### ISSUE THREAD

**Issue by servefast-cto** [AzureAD/microsoft-authentication-library-for-js#7339]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.24.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

3.0.24

### Public or Confidential Client?

Confidential

### Description

Running:
`npm i @azure/msal-browser --save`
or
`npm i @azure/msal-angular --save`

### Error Message

`
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: '@azure/msal-node@1.18.4',
npm warn EBADENGINE   required: { node: '10 || 12 || 14 || 16 || 18' },
npm warn EBADENGINE   current: { node: 'v20.14.0', npm: '10.8.3' }
npm warn EBADENGINE }
`

### MSAL Logs

No logs available

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
Not applied
```

### Relevant Code Snippets

```javascript
"@azure/msal-angular": "^3.0.24"
"@azure/msal-browser": "^3.24.0"

running `npm i` same problem

$ node -v
v20.14.0

$ npm -v
10.8.3
```

### Reproduction Steps

Try to install msal with node20 installed

### Expected Behavior

I should be able to install MSAL with LTS node version. I dont think anybody is writting angular app 17 or 18 version without node at least 20+

### Identity Provider

Entra ID (formerly Azure AD) / MSA

### Browsers Affected (Select all that apply)

Other

### Source

External (Customer)

**Comment by servefast-cto** [comment]
Iam using Node 20.14.0 forgot to change but it is the same thing with 20.17.0 which is LTS

**Comment by servefast-cto** [comment]
we gave up on MSAL and created our own implementation. Closing

**Comment by gaitat** [comment]
Why is this closed when the issue still exists?
I am using node v22
I just cloned the repo and `npm install` fails with:

npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: '@azure/msal-node@1.18.4',
npm warn EBADENGINE   required: { node: '10 || 12 || 14 || 16 || 18' },
npm warn EBADENGINE   current: { node: 'v22.14.0', npm: '10.9.2' }
npm warn EBADENGINE }

**Comment by Iworb** [comment]
I'm also intrested, why this closed? You supporting Angular 21, which requires node ^20.19.0
