### ISSUE TITLE
hitting error of Cannot read property 'getRequestInfo' of null when login in an iframe

### ISSUE THREAD

**Issue by bryanchen-d** [AzureAD/microsoft-authentication-library-for-js#738]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version 74
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version
Library version: 0.2.4

## Current behavior

load an app which use msal.js for login in an iframe, after the login succeeds and redirect back to the app, it failed with error:
`Cannot read property 'getRequestInfo' of null`

the code that related is in UserAgentApplication.ts:
```
// Set the self to the window that created the popup/iframe
    if (isWindowOpenerMsal) {
      self = window.opener.msal;
      isPopup = true;
    } else if (window.parent && window.parent.msal) {
      self = window.parent.msal;
    }

    // if (window.parent !== window), by using self, window.parent becomes equal to window in getResponseState method specifically
    const stateInfo = self.getResponseState(hash);
```

in this case, the `self` does not fall into either case of the `if` clause and remain to be null, thus the failure at calling `getResponseState`. 

One possible fix might be to set `self=window.msal`? but not sure if there is any side effect though.

**Comment by DarylThayil** [comment]
@pkanher617  / @sameerag  is this fixed in 1.0.x?

**Comment by bryanchen-d** [comment]
I tried version 1.0.1, and the issue is still there.

**Comment by DarylThayil** [comment]
thanks for letting me know! @pkanher617  can you look into this and see what the issue might be?

**Comment by pkanher617** [comment]
Hi @bryanchen-d just to clarify, you are using msal inside an iframe correct?

I believe this is a known issue with our library currently. We are reviewing our calling pattern for this, and I will see if your suggestion has any other repercussions.

**Comment by bryanchen-d** [comment]
> Hi @bryanchen-d just to clarify, you are using msal inside an iframe correct?

Yes. I am also testing the scenarios with UI testing framework like cypress, in which it launch the SPA inside an iframe.

**Comment by pkanher617** [comment]
@sameerag This looks like support for MSAL inside an iframe.

**Comment by DarylThayil** [comment]
@bryanchen-d  unfortunately we do not support msal inside of an iframe, but this is an issue we would like to solve soon in a minor release .  Closing this ticket because it is already tracked

**Comment by DarylThayil** [comment]
Please look to our roadmap in next 2 weeks for a solid update
