### ISSUE TITLE
Signing into Azure DevOps using MSAL and a personal MS Account

### ISSUE THREAD

**Issue by nik-net** [AzureAD/microsoft-authentication-library-for-js#7411]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.1.0

### Wrapper Library

MSAL Angular (@azure/msal-angular)

### Wrapper Library Version

None

### Public or Confidential Client?

Public

### Description

We are building a single page application that can be used by anyone to interact with a set of capabilities provided in Microsoft Azure DevOps. We can't control or know upfront what MS Accounts will be used with our app.

We are using samples as provided here https://github.com/AzureAD/microsoft-authentication-library-for-js/

Our use case includes being able to authenticate a personal microsoft account so that we can

1. Identify all the Azure DevOps Organisations they have access to
2. Give the user the option to connect to an Organisation and a project

However we aren't able to get pass the Authentication steps. 

When we run this sample, the Authentication dialogue comes up but doesn't let us specify a personal MIcrosoft account. 

**_You can't sign in here with a personal account. Use your work or school account instead._**

See the error

<img width="506" alt="Screenshot 2024-11-08 at 14 11 18" src="https://github.com/user-attachments/assets/42f9a1c2-7b5f-4e76-b48f-5711f3fd6511">

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
{
    auth: {
        // 'Application (client) ID' of app registration in Azure portal - this value is a GUID
        clientId: "8f01aebc-2dd5-4058-b5ce-dedb0b73a17f",
        // Full directory URL, in the form of https://login.microsoftonline.com/<tenant-id>
        authority: "https://login.microsoftonline.com/common",
        // Full redirect URL, in form of http://localhost:3000
        redirectUri: "http://localhost:3000/",
        //protocolMode:"OIDC",
    },
    cache: {
        cacheLocation: "sessionStorage", // This configures where your cache will be stored
        storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
    },
    system: {	
        loggerOptions: {	
            loggerCallback: (level, message, containsPii) => {	
                if (containsPii) {		
                    return;		
                }		
                switch (level) {		
                    case msal.LogLevel.Error:		
                        console.error(message);		
                        return;		
                    case msal.LogLevel.Info:		
                        console.info(message);		
                        return;		
                    case msal.LogLevel.Verbose:		
                        console.debug(message);		
                        return;		
                    case msal.LogLevel.Warning:		
                        console.warn(message);		
                        return;		
                }	
            }	
        }	
    }
};
```

### Relevant Code Snippets

```javascript
const loginRequest = {
    //scopes: ["User.Read", "user_impersonation"]
    //scopes: ["https://app.vssps.visualstudio.com/.default"]
    scopes: ['openid', 'profile', '499b84ac-1321-427f-aa17-267ca6975798/user_impersonation'], // Azure DevOps scopes
    //,extraScopesToConsent: ["499b84ac-1321-427f-aa17-267ca6975798/.default"]
};
```

### Reproduction Steps

1. Simply use the sample provided here https://github.com/AzureAD/microsoft-authentication-library-for-js/b to try and sign into Azure DevOps using a personal MS Account
2. We have ensured that all settings in Entra App are correct as per the documentation

### Expected Behavior

User should be able to use their Personal MS Account to authenticate. This should not be restricted to only work or school MS Accounts

### Identity Provider

Entra ID (formerly Azure AD) / MSA

### Browsers Affected (Select all that apply)

Chrome

**Comment by nik-net** [comment]
Can someone please help?

**Comment by nik-net** [comment]
Hi everyone! CAn someone please help with this? Thanks

**Comment by LuccaRebelloToledo** [comment]
Hey @nik-net, how are you?

On Azure, go to App Registration, select your app and go to section Manage -> Authentication. Verify if your "Supported account types" is like: 

![image](https://github.com/user-attachments/assets/839e2e9c-678a-441a-bf29-de64ac0f31a9)

**Comment by nik-net** [comment]
Thank you. I can confirm that my setup is exactly like this. However I also found this recently from this page
https://learn.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/entra-oauth?view=azure-devops

![image](https://github.com/user-attachments/assets/2e7336f7-be0b-4e87-9a97-d22233c1763f)

Looks like its a known problem with Entra oAuth and MSA accounts. If so, it would be good to understand if this support is currently on the roadmap.

**Comment by LuccaRebelloToledo** [comment]
Interesting. Can you send a screenshot about your "Supported Account Types" and the method from which you generate the oauth URL?

**Comment by tnorling** [comment]
MSAL.js does support MSA accounts. The screenshot you posted refers to ADO REST APIs which this library does not use. The use of MSA accounts is controlled by the app registration, if you've indicated you support MSA on the app registration and you're still getting an error please [open a support ticket with Entra](https://azure.microsoft.com/en-us/support/create-ticket/) so that support can identify what the problem is in your specific case.
