### ISSUE TITLE
MSAL Js lib use in Kotlin multiplatform application.

### ISSUE THREAD

**Issue by Vikas-KMP** [AzureAD/microsoft-authentication-library-for-js#7428]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

2.32.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

2.32.0

### Public or Confidential Client?

Confidential

### Description

I want to use MSAL Js lib in Kotlin multiplatform application. but i am getting multiple errors.

Added MSAL Lib like:
val wasmJsMain by getting {
            dependencies {
                implementation(npm("@azure/msal-browser", "2.32.0")) // MSAL library
            }
        }

### Error Message

Calls to 'js(code)' should be a single expression inside a top-level function body or a property initializer in Kotlin/Wasm.

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
object MSALConfig {
    const val clientId = "xxxxx"  // Replace with your MSAL Client ID
    const val redirectUri = "https://localhost:3000/login"  // Replace with your Redirect URI
    const val scopes = "user.read"  // Define your required MSAL scopes
}
```

### Relevant Code Snippets

```javascript
private fun createMsalConfig(): MsalAuthConfig {
        return js("{}").unsafeCast<MsalAuthConfig>().apply {
            clientId = MSALConfig.clientId
            redirectUri = MSALConfig.redirectUri
        }
    }

    // Use the top-level function to create the PublicClientApplication
    private fun createMsalApp(): PublicClientApplication {
        val config = createMsalConfig()
        return PublicClientApplication(config)
    }
```

### Reproduction Steps

After adding JS lib i am not able to initialise msal lib in Kotlin Multiplatfrom project under wasmJsMain folder.

### Expected Behavior

Successful authication and authorization.

Should be able to receive the access token after login.

### Identity Provider

Entra ID (formerly Azure AD) / MSA

### Browsers Affected (Select all that apply)

Chrome, Edge, Safari

### Regression

@azure/msal-browser

**Comment by tnorling** [comment]
This is unfortunately not an environment we support, nor does this error originate in MSAL. I would suggest posting your question on StackOverflow instead.
