### ISSUE TITLE
Entry state history is not preserved by handleRedirectPromise

### ISSUE THREAD

**Issue by kanguro** [AzureAD/microsoft-authentication-library-for-js#7429]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.27.0

### Wrapper Library

Not Applicable

### Wrapper Library Version

0.0.0

### Public or Confidential Client?

Public

### Description

`PublicClientApplication.handleRedirectPromise( hash?: string | undefined)` clears current history entry state.

When `handleRedirectPromise( ...)` is called to complete authentication started by `acquireTokenRedirect(...)`, hash from URL in window history is removed by [RedirectClient.getRedirectResponse(...)](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/src/interaction_client/RedirectClient.ts#L407C1-L408C44) calling [BrowserUtils.clearHash(...)](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/src/utils/BrowserUtils.ts#L27). The hash is removed by calling [History.replaceState(...)](https://developer.mozilla.org/en-US/docs/Web/API/History/replaceState). 

Invocation of the History API method also clears state of the entry at top of the stack, by supplying `null` as first parameter. This may cause incorrect behavior on Firefox browser, that will duplicate most recent history entry instead of modifying it. Possibly related Mozilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=753264

I believe that `BrowserUtils.clearHash(...)` could preserve current history entry state by changing the invocation to:
```
contentWindow.history.replaceState(
    contentWindow.history.state,
    "",
    `${contentWindow.location.origin}${contentWindow.location.pathname}${contentWindow.location.search}`
);
```

### MSAL Logs

Logs captured for login with redirect and following it handle redirect. Login with redirect is executed in child window, not the main window, so main window does not do any redirects.

[console-export-2024-11-19_11-34-30.txt](https://github.com/user-attachments/files/17813740/console-export-2024-11-19_11-34-30.txt)

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
{
  auth: {
	clientId: '<valid client ID>'
	redirectUri: '<link to landing page>'
  },
  cache: {
	cacheLocation: BrowserCacheLocation.LocalStorage
  }
}
```

### Relevant Code Snippets

```javascript
Invokation of authentication in owned pop-up:

const filePickerWindow = window.open(
  'about:blank',
  'Microsoft OneDrive',
  'width=1080,height=680'
);

this.filePickerWindow.focus();

await this._authenticationService.acquireTokenInExternalPopup(
  this._filePickerWindow,
	request
);

----
Extended PublicClientApplication that does the work:

import {
  AuthenticationResult,
  BrowserAuthError,
  BrowserCacheLocation,
  Configuration,
  PublicClientApplication,
  RedirectRequest
} from '@azure/msal-browser';
import { firstValueFrom, fromEvent, Observable, Subject } from 'rxjs';
import { filter, map, switchMap, takeUntil } from "rxjs/operators";


export class MicrosoftOneDriveAuthenticationService extends PublicClientApplication {
  constructor(configuration: Configuration) {
    super({
      ...configuration,
      cache: {
        cacheLocation: BrowserCacheLocation.LocalStorage
      }
    });
  }

  async acquireTokenInExternalPopup(
    popupWindow: Window,
    request: RedirectRequest
  ): Promise<AuthenticationResult> {
    const currentWindowOrigin = window.origin;
    const requestId = `${ crypto.randomUUID().toString() }_${ new Date().getUTCDate() }`;

    request = {
      ...request,
      state: requestId
    };

    const popupWindowMessages$ = (fromEvent(window, 'message') as Observable<MessageEvent>).pipe(
      filter(event => event.origin === currentWindowOrigin),
      map(event => {
        const payload = event.data as string;
        const isExpectedType = payload && typeof payload === 'string' && payload.startsWith('#');

        if (!isExpectedType) {
          return null;
        }

        return payload;
      }),
      filter(payload => !!payload),
      filter(payload => payload.indexOf(requestId) >= 0)
    );

    const unsubscribe$ = new Subject<void>();

    let authenticationResult: AuthenticationResult;

    const authenticationCompleted$ = popupWindowMessages$.pipe(
      takeUntil(unsubscribe$),
      switchMap(async parameters => {
        const result = await this.handleRedirectPromise(parameters);
        this.setActiveAccount(result.account);
        authenticationResult = result;
      })
    );

    await this.acquireTokenRedirect({
      ...request,
      onRedirectNavigate: url => {
        popupWindow.location.replace(url);
        return false;
      }
    });

    await firstValueFrom(authenticationCompleted$);

    unsubscribe$.next();
    unsubscribe$.complete();

    return authenticationResult;
  }
}
```

### Reproduction Steps

I am using the library in a bit unusual way, as I open child window in which I conduct authentication using redirect flow. After authentication completes and child window is redirected to appointed page, message is posted from child window to parent with hash containing data required to complete the flow. The flow is completed from parent window. I have described the use case and provided code snippets in this bug: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/7362#issuecomment-2407092392

Issue can be reproduced by using code snippets attached to to this bug.

### Expected Behavior

History entry state is preserved after execution of `handleRedirectPromise`

### Identity Provider

Entra ID (formerly Azure AD) / MSA

### Browsers Affected (Select all that apply)

Firefox

**Comment by tnorling** [comment]
This is by design. We replace history so that the auth code does not persist. I understand that in your scenario the auth code is never present in the history of the frame that is updating history, but unfortunately since you are doing something non-standard we won't be able to address this for you. I would highly recommend using the APIs as they are intended, if possible.

**Comment by kanguro** [comment]
Hi @tnorling , thank you for such a quick feedback. I'm worried that my main concern got lost in the volume of information provided.

I understand the need to wipe out auth code. My concern is that as part of the process, state is also wiped out. 

I hope you could take a moment to re-check and confirm that's intentional or not.

Thanks in advance,
Artur

![image](https://github.com/user-attachments/assets/a27b7a48-11c1-4b24-b7f7-79bc603d38d9)
