### ISSUE TITLE
nextjs 15 and msal do not recognize environment variables

### ISSUE THREAD

**Issue by cadinhoruf** [AzureAD/microsoft-authentication-library-for-js#7431]
### Core Library

MSAL.js (@azure/msal-browser)

### Core Library Version

3.27.0

### Wrapper Library

MSAL React (@azure/msal-react)

### Wrapper Library Version

2.2.0

### Public or Confidential Client?

Confidential

### Description

If I configure my msalConfig with environment variables, the Microsoft client does not recognize it, I need to pass them all as hardcoded, passing the values ​​it works normally

### Error Message

![microsoft-error](https://github.com/user-attachments/assets/2b06142b-a230-451a-861a-8d6baaf9f0e2)

### Network Trace (Preferrably Fiddler)

- [ ] Sent
- [ ] Pending

### MSAL Configuration

```javascript
const msalConfig: Configuration = {
  auth: {
    clientId: process.env.AZURE_AD_CLIENT!,
    authority: `https://login.microsoftonline.com/${process.env.AZURE_AD_TENANT}/v2.0`,
    redirectUri: process.env.NEXT_PUBLIC_BASE_URL
  },
  cache: {
    cacheLocation: 'localStorage'
  }
}
```

### Relevant Code Snippets

```javascript
I only call the function onclick () => instance.loginRedirect() on the login button.
```

### Reproduction Steps

1. **Environment Setup**:
   - Ensure you are using the latest version of the MSAL library. (Example: `@azure/msal-browser@latest`)
   - Use Node.js version 14 or higher.
   - Create a new Next.js project or use an existing one.
   - Make sure you are using a version similar to or equal to 15.0.3 of Nextjs

2. **Install the Library**:
   - Run the following command to install the library:
     ```bash
     npm install @azure/msal-browser
     ```

3. **Code Configuration**:
   - Create a `config.ts` file with the following configuration:
     ```typescript
     import { Configuration, PublicClientApplication } from '@azure/msal-browser';

     const msalConfig: Configuration = {
       auth: {
         clientId: process.env.NEXT_PUBLIC_AZURE_AD_CLIENT || '',
         authority: `https://login.microsoftonline.com/${process.env.NEXT_PUBLIC_AZURE_AD_TENANT}/v2.0`,
         redirectUri: process.env.NEXT_PUBLIC_REDIRECT_URI || 'http://localhost:3000'
       },
       cache: {
         cacheLocation: 'localStorage'
       }
     };

     const msalInstance = new PublicClientApplication(msalConfig);
     export { msalInstance };
     ```

4. **Login Call**:
   - In your component, add the following code to call the login method:
     ```typescript
        <button onClick={() => instance.loginRedirect()}> Login</button>
     ```

5. **Run the Application**:
   - Start the development server:
     ```bash
     npm run dev
     ```

6. **Access the Application**:
   - Open your browser and go to `http://localhost:3000`.
   - Click the login button that calls the `loginRedirect` function.

7. **Result**:
   - Instead, you receive the error `AADSTS900023: Specified tenant identifier 'undefined' is neither a valid DNS name, nor a valid external domain.`.

### Expected Behavior

When I attempt to log in using the MSAL library with the provided configuration, I expect the following behavior:

1. **Successful Authentication**:
   - The login process should initiate without errors when the `loginRedirect()` function is called.
   - Upon successful authentication, I should receive a valid authentication response containing user information and access tokens.

2. **User Redirection**:
   - After successful login, the user should be redirected to the specified `redirectUri` (e.g., `http://localhost:3000`).

3. **Access to Protected Resources**:
   - Once authenticated, the user should be able to access protected resources or APIs that require authentication, using the access token received during the login process.

4. **No Errors**:
   - I expect that no errors will occur during the login process, particularly the error `AADSTS900023: Specified tenant identifier 'undefined' is neither a valid DNS name, nor a valid external domain.` should not be displayed.

### Identity Provider

Entra ID (formerly Azure AD) / MSA

### Browsers Affected (Select all that apply)

Firefox, Edge, Safari

##Comments

If I use NEXT_PUBLIC in the environment variables, it works normally, but I can't because it is an internal application

**Comment by tnorling** [comment]
This question is probably better asked at the Next.js folks. MSAL.js does not have any role in making available or evaluating environment variables, that is all handled by the framework and/or the runtime used.
