### ISSUE TITLE
Latest version missing on CDN

### ISSUE THREAD

**Issue by mlankamp** [AzureAD/microsoft-authentication-library-for-js#744]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 1.0.1

## Current behavior
https://secure.aadcdn.microsoftonline-p.com/lib/1.0.1/js/msal.js is missing on the CDN

## Minimal reproduction of the problem with instructions

</code></pre>

**Comment by sameerag** [comment]
Yes, we are following up on this and should close it soon.

**Comment by pkanher617** [comment]
@mlankamp Sorry for the delay, there are some access issues we are sorting out on our end. Please expect a CDN release today or tomorrow.

**Comment by pkanher617** [comment]
@mlankamp CDN for 1.0.1 should be published now. Hopefully there should be no more delays moving forward. Thanks for your patience.

https://secure.aadcdn.microsoftonline-p.com/lib/1.0.1/js/msal.min.js
