### ISSUE TITLE
No popups

### ISSUE THREAD

**Issue by newtack** [AzureAD/microsoft-authentication-library-for-js#75]
With a SPA application that leverages Azure AD B2C, I would like to allow the user to enter email password WITHIN the application without requiring a popup or a redirect. 

Can I do this with MSAL? If so, how and is there any example available?

Note: I'd also offer social logins for the user, and in that case would want a popup, but not when the user chooses email/password option.

**Comment by sethreidnz** [comment]
I agree with @newtack. I got really excited when I saw this as I'm currently trying to figure out the best way to auth with Azure B2C and a SPA framework. But this IMO severely limits the user experience and expeciall ony things like mobile you don't really want to pop a new windwow. 

Is there any plan to create say essentially the same thing as the `loginPopup` except we just have like `loginUser(username, password` and let the front end develop take care of getting the values.

 Seems the value in this library would be to me if it could take away the whole token management thing for me but still allow me to have it as an in-app experience.

**Comment by rohitnarula7176** [comment]
@newtack @sethreidnz The library is not meant to support this particular use case case.

**Comment by sethreidnz** [comment]
Why not? You mean 99% of use cases for a modern JavaScript app? Is there something that makes it impossible?

**Comment by jmprieur** [comment]
Collecting and storing a user's username and password is not considered the correct approach for non-interactive authentication, and therefore we are not implementing it for many platforms. With Azure AD, the service handles the conversation in the browser (popup or with an indirection).
The following GitHub issue (which is for ADAL.net, but this is the same principle) explains in details why we don't do it: https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/482
I recommend you to read the thread, which also proposes alternative solutions.

We are limiting it to very specific platforms (.NET desktop) for compatibility.
HTH
