### ISSUE TITLE
Support for Angular 7

### ISSUE THREAD

**Issue by arunprasathv** [AzureAD/microsoft-authentication-library-for-js#750]
@RamonPage @vladzaharia @DarylThayil 
@azure/msal-angular - Does this library support angular 7 application.?

I see in the desc, 
MSAL.js library which enables Angular(4.3 to 5) applications to authenticate enterprise users using Microsoft Azure Active Directory (AAD). 

npm install warnings

npm WARN @angular/core@7.2.15 requires a peer of zone.js@~0.8.26 but none is installed. You must install peer dependencies yourself.
npm WARN @azure/msal-angular@0.1.2 requires a peer of @angular/common@^4.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN @azure/msal-angular@0.1.2 requires a peer of @angular/core@^4.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN @azure/msal-angular@0.1.2 requires a peer of rxjs@^5.0.1 but none is installed. You must install peer dependencies yourself.

**Comment by DarylThayil** [comment]
Thanks for your request, we will be supporting angular 2+ as a part of our work to get msal-angular to 1.0.0. 

This work will likely being in July 

https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#roadmap

closing this ticket but please do stay in touch with any questions you may have
