### ISSUE TITLE
Prompt="select_account" is not working as expected.

### ISSUE THREAD

**Issue by anjiuidev** [AzureAD/microsoft-authentication-library-for-js#756]
## I'm submitting a...
[ ] Bug report  

## Library version
Library version: 1.0.0

## Current behavior
Prompt="select_account" is not redirecting to account selection page and using the existing session to login.

## Expected behavior
It should redirect to the account selection page.

## Minimal reproduction of the problem with instructions
Step 1: Clone or download this repository

From your shell or command line:
<pre>git clone https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp.git</pre>

Step 2: Run the application
<pre>cd active-directory-b2c-javascript-msal-singlepageapp
npm install 
node server.js</pre>

The console window shows the port number for the web application

Listening on port 6420...

You can visit http://localhost:4200

In the index.html file line number 70 edit the loginRequest object as below.
<pre>var loginRequest = {
        scopes: appConfig.b2cScopes,
        prompt: 'select_account'
      };</pre>

Run the Application, click on login and select an account. in my case, I have selected Google. If you are already logged in with Gmail it will automatically select that account, instead of redirecting to the account selection page.

**Comment by DarylThayil** [comment]
@pkanher617  can you look at this?

@anjiuidev  thanks for sharing such a well fleshed out example for us.

**Comment by DarylThayil** [comment]
cc @sameerag

**Comment by sameerag** [comment]
@anjiuidev I see prompt: "select_account" is working as expected for AAD/MSA but not for B2C. I will start working with the B2C service team to debug this as the screen that needs to be displayed for select_account is owned by them. Please expect some delay on this but we are actively tracking this.

**Comment by sameerag** [comment]
@anjiuidev I verified with the other MSAL teams and B2C service again. We (MSAL JS) are sending the queryString parameter "&prompt=select_account" in our request to the service. The second level of indirection where if a developer selects google or MSA or any other IDP, the select tile is not being rendered by the service team. 

I flagged it to their team and will tag it accordingly. Though this is not within MSAL JS's land to fix, I am keeping this bug open to track with B2C server team.

Thanks for raising this.

**Comment by anjiuidev** [comment]
@sameerag any update on this bug from B2C service team.

**Comment by sameerag** [comment]
@anjiuidev I have mentioned this to the B2C team and my initial impression is that the implementation of this is not a straightforward case for them. Especially since they cater to multiple endpoints within the same UI. 

I will have one of their engineers comment on this issue if they plan to support this.

**Comment by ktsakas** [comment]
We are looking into this internally, but this is not something we plan to support in the next couple of months.
Closing this for now, but will comment if there is an update. Feel free to leave a feature request on our [UserVoice page](https://feedback.azure.com/forums/169401-azure-active-directory/category/160596-b2c).
