### ISSUE TITLE
msal.getAccount() returns null on landing page

### ISSUE THREAD

**Issue by dipesh-wadhwa** [AzureAD/microsoft-authentication-library-for-js#758]
## getAccount() returns null on landing page

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version 75.0.3770.80
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 1.0.0

</code></pre>

## Current behavior

msal.getAccount() returns null on landing page.
Just to give you more information. I am not creating any SPA. There are 2 plain html pages with javascript - Login.html and Home.html. My requirement is to redirect user to Home page when he is successfully login.

## Expected behavior

msal.getAccount() should return logined user details.

## Minimal reproduction of the problem with instructions

**Login.html**

```
<!DOCTYPE html>
<html>
<head>
    <title>Login Page</title>    
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.0.min.js"></script>
    <script src="https://secure.aadcdn.microsoftonline-p.com/lib/1.0.0/js/msal.js"></script>
</head>
<body>
    <h2>You are on Login Page</h2>            
    <button id="SignIn" onclick="signIn()">Sign In</button><br/><br/>    
    
    <script type="text/javascript">
    var msalConfig = {
        auth: {
            clientId: "app-id-here",
            authority: "https://login.microsoftonline.com/tenant-id-here",
            redirectUri: "http://localhost/home.html",
            navigateToLoginRequestUrl: false
        },
        cache: {
            cacheLocation: "localStorage",
            storeAuthStateInCookie: true
        }
    };

    var myMSALObj = new Msal.UserAgentApplication(msalConfig);
    myMSALObj.handleRedirectCallback(authRedirectCallBack);

    function authRedirectCallBack(error, response) {
    //Do Nothing For Now
    }

    function signIn() {
        myMSALObj.loginRedirect({"loginHint":"user@myowndomain.com",scopes: ["user.read"]});
    }

    </script>
</body>
</html>
```

**Home.html**
```
<h1>You are on home page</h1>
<h2 id="userName"></h2>
<script src="https://secure.aadcdn.microsoftonline-p.com/lib/1.0.0/js/msal.js"></script>
<script>    

    var msalConfig = {
        auth: {
            clientId: "app-id-here",
            authority: "https://login.microsoftonline.com/tenant-id-here",
            redirectUri: "http://localhost/home.html",
            navigateToLoginRequestUrl: false
        },
        cache: {
            cacheLocation: "localStorage",
            storeAuthStateInCookie: true
        }
    };
    var myMSALObj = new Msal.UserAgentApplication(msalConfig);

    var divWelcome = document.getElementById('userName');
    divWelcome.innerHTML = 'Welcome ' + (myMSALObj.getAccount() != null ? myMSALObj.getAccount().userName : " {Failed to authenicate} ") + " to Microsoft Graph API";    

</script>
```
**App Registration and Configuration**
I have registered app as well with below configuration:
![image](https://user-images.githubusercontent.com/46276877/59354577-00f6a480-8d43-11e9-9820-38df5a0a5ecb.png)
Please note I have enabled id_token and access_token in the app as well.

**What I am trying to achieve?**
Below is the visual of what I am trying to achieve:
![image](https://user-images.githubusercontent.com/46276877/59354683-2d122580-8d43-11e9-83ba-27d69fa0464e.png)

**Comment by pkanher617** [comment]
@dipesh-wadhwa Thank you for submitting this. I am taking a look and will try to get back to you today.

**Comment by pkanher617** [comment]
@dipesh-wadhwa I believe what is happening is that the handleRedirectCallbacks is not being called where it needs to be. Since your redirect uri is the /home page, the app will need to handle the redirect on that page. Your login page will look like:

### Login.html
```html
<!DOCTYPE html>
<html>
<head>
    <title>Login Page</title>    
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.0.min.js"></script>
    <script src="https://secure.aadcdn.microsoftonline-p.com/lib/1.0.0/js/msal.js"></script>
</head>
<body>
    <h2>You are on Login Page</h2>            
    <button id="SignIn" onclick="signIn()">Sign In</button><br/><br/>    
    
    <script type="text/javascript">
    var msalConfig = {
        auth: {
            clientId: "app-id-here",
            authority: "https://login.microsoftonline.com/tenant-id-here",
            redirectUri: "http://localhost/home.html",
            navigateToLoginRequestUrl: false
        },
        cache: {
            cacheLocation: "localStorage",
            storeAuthStateInCookie: true
        }
    };

    var myMSALObj = new Msal.UserAgentApplication(msalConfig);
    myMSALObj.handleRedirectCallback(authRedirectCallBack);

    function authRedirectCallBack(error, response) {
    //Do Nothing Here since we don't come back to this page.
    }

    function signIn() {
        myMSALObj.loginRedirect({"loginHint":"user@myowndomain.com",scopes: ["user.read"]});
    }

    </script>
</body>
</html>
```
and your Home page will look like this:
### Home
```html
<h1>You are on home page</h1>
<h2 id="userName"></h2>
<script src="https://secure.aadcdn.microsoftonline-p.com/lib/1.0.0/js/msal.js"></script>
<script>    

    var msalConfig = {
        auth: {
            clientId: "app-id-here",
            authority: "https://login.microsoftonline.com/tenant-id-here",
            redirectUri: "http://localhost/home.html",
            navigateToLoginRequestUrl: false
        },
        cache: {
            cacheLocation: "localStorage",
            storeAuthStateInCookie: true
        }
    };
    var myMSALObj = new Msal.UserAgentApplication(msalConfig);
    myMSALObj.handleRedirectCallback(authRedirectCallBack);

    function authRedirectCallBack(error, response) {
        // You should be able to get the account object here in response.account
       var divWelcome = document.getElementById('userName');
       divWelcome.innerHTML = 'Welcome ' + (response.account != null ? 
                 myMSALObj.getAccount().userName : " {Failed to authenicate} ") + " to Microsoft Graph API"; 
    }
    // getAccount() should no longer return null outside of the callback now
    let account = myMSALObj.getAccount();

</script>
```
This should fix your issue. Please let me know if you still can't get the account object.

I think the confusion here is caused because of the way the library works today. Most use cases we have seen using has the redirect coming back to the same page (mostly SPAs), but the library needs to be more clear about use cases like this one. I will add a PR to update the usage to make it more clear when the handleRedirectCallback function needs to be called. Thank you for bringing this to our attention! :)

**Comment by dipesh-wadhwa** [comment]
@pkanher617 I have made changes as you suggested. Still same problem exist. Below are my observation:

1. handleRedirectCallback() does not triggers on landing page. In my case it is home.html
2. myMSALObj.getAccount() still returns null. (See screenshot below)

![image](https://user-images.githubusercontent.com/46276877/59499859-e7299e80-8eb5-11e9-8a98-93304592d8f4.png)

**Comment by GermanEZI** [comment]
I am having this same issue.   I've tried downloading version 1.1.3.  However, I cannot find the msal.js file in that download [MSAL 1.1.3](https://github.com/AzureAD/microsoft-authentication-library-for-js/releases/tag/v1.1.3)

Where can I get the 1.1.3 version of MSAL.js?

**Comment by sameerag** [comment]
1.1.3 is not released for CDN. @pkanher617 is working on the issues we are facing releasing in the CDN and he will update here once we have this in CDN.

@GermanEZI Can you please try npm release if that is possible? npm release has the compiled files in the "dist" folder.

**Comment by dipesh-wadhwa** [comment]
@GermanEZI issue still exist.. I have switched to SPA app as workaround.

**Comment by DarylThayil** [comment]
1.1.3 is  available from cdn now

**Comment by jasonnutter** [comment]
@dipesh-wadhwa To clarify, are you still seeing this issue on 1.1.3? It has been released to the cdn (updated urls are available [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/957#issuecomment-532923268)).

**Comment by dipesh-wadhwa** [comment]
@jasonnutter @GermanEZI @DarylThayil @sameerag @pkanher617
I have verified and this is fixed now. Brilliant...!!!
