### ISSUE TITLE
Standard pop-up blocker for Chrome and Firefox blocks consent screeen

### ISSUE THREAD

**Issue by andretms** [AzureAD/microsoft-authentication-library-for-js#76]
After user signs-in, a call to acquireTokenPopup(["https://graph.microsoft.com/user.read"]) fails due built-in pop-up blocker in Chrome or Firefox when consent is needed. The following error is happens:

popup_window_error:Error opening popup window. This can happen if you are using IE or if popups are blocked in the browser

In order to test this, create a new brand new application in ARP, login with a user using a private session, and then call acquireTokenPopup to acquire the token

**Comment by rohitnarula7176** [comment]
@andretms This is a standard problem where the browser blocks the popup window from opening if it is not a direct result of a click event. We have mentioned in the Read me that the developers need to allow popups in the browser if they want to consume msal and take advantage of the popup based login and acquireToken.

**Comment by navkakate** [comment]
Hello @rohitnarula7176!
Is there any changes to this statement? Does msal go well with popup blockers nowadays?
When I call getCachedTokenInternal() with popup blocker, it fails to retrieve token.

**Comment by ertejaspatel** [comment]
@rohitnarula7176 - Understand this is a browser issue but is there any known workaround that can help bypass this issue?

Thanks

**Comment by jasonnutter** [comment]
@navkakate @ertejaspatel Nothing has changed in this regard. Possible workarounds:

- Invoke `acquireTokenPopup` as a direct result of user interaction.
- User enables popups.
- Use `acquireTokenRedirect` instead of `acquireTokenPopup`
