### ISSUE TITLE
Please provide d.ts type definition file

### ISSUE THREAD

**Issue by wisercoder** [AzureAD/microsoft-authentication-library-for-js#763]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: X.Y.Z

## Current behavior

Currently msal is not very typescript friendly because a d.ts file is not available.
[PR 79](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/79) should at least have generated the d.ts file, but it is no longer doing so. 

## Expected behavior

The following command should install types:
`npm install --save-dev @types/msal
`
## Minimal reproduction of the problem with instructions

</code></pre>

**Comment by jasonnutter** [comment]
@wisercoder As you noted, `msal` should ship with its own type definition files (as opposed to from the `@types` org). If those do not appear to be working, I think that would be a bug. Can you provide more info on what you are or are not seeing (e.g. intellisense not working, etc)? Thanks!

**Comment by wisercoder** [comment]
@jasonnutter turns out this is working as you described. My bad.
