### ISSUE TITLE
Minified Script: Invalid regular expression

### ISSUE THREAD

**Issue by hunterwebapps** [AzureAD/microsoft-authentication-library-for-js#767]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [X] Chrome version 74
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version
<pre><code>
Library version: 1.0.1

## Current behavior
As soon as the script is loaded it throws the regex error and "Msal is not defined". Seems to work fine in a local environment, but fails on Azure app service.

## Expected behavior
Successfully load...

## Minimal reproduction of the problem with instructions
There was no problem when run locally, but it won't load when deployed to an Azure app service.
</code></pre>

![bug](https://user-images.githubusercontent.com/14143016/59698150-f2294b00-91a3-11e9-92a4-4fbec4f284df.PNG)

I think it's related to here:
```javascript
var re_btou = new RegExp([
  '[\xC0-\xDF][\x80-\xBF]',
  '[\xE0-\xEF][\x80-\xBF]{2}',
  '[\xF0-\xF7][\x80-\xBF]{3}'
].join('|'), 'g');
```

**Comment by DarylThayil** [comment]
This is really strange, it only happens in azure app services?

**Comment by Pheil** [comment]
I get the same bug.  Switching to the non-minified version seems to work.

**Comment by hunterwebapps** [comment]
@DarylThayil I can only confirm that it happened after deploying to an azure app service, but it did not happen in my local environment. The non-minified version works in both environments.

**Comment by sameerag** [comment]
Also @hunterwebapps Can you confirm this is the case with all releases? Can you please test it with msal 1.0.2 and confirm the same?

**Comment by Pheil** [comment]
Here's my results running locally with my Chrome extension.  

> 1.0.2 Min - NoK
> 1.0.2     - OK
> 1.0.1 Min - NoK
> 1.0.1     - OK
> 1.0.0 Min - OK
> 1.0.0     - OK

I'm not an expert, but shouldn't the minimization not change the code @hunterwebapps mentioned to this?  Looks almost like an encoding conversion issue.

`re_btou=new RegExp(["[Ã€-ÃŸ][Â€-Â¿]","[Ã -Ã¯][Â€-Â¿]{2}","[Ã°-Ã·][Â€-Â¿]{3}"]`

**Comment by sameerag** [comment]
Thanks for the feedback @Pheil. We will look into this and get back.

**Comment by Pheil** [comment]
FYI v1.1.2 Min is working.

**Comment by sameerag** [comment]
Thanks, that is interesting feedback.

**Comment by DarylThayil** [comment]
@Pheil  confirming that you are saying this is no longer an issue in 1.1.2?

**Comment by Pheil** [comment]
Correct.  If it wasn't intentionally fixed I can't see the "re_btou" regex anymore.

**Comment by DarylThayil** [comment]
great closing issue, thanks for feedback
