### ISSUE TITLE
Acquiretokensilent returning AADSTS50058 with MSAL.js 1.0.1 version(AAD and Live accounts)

### ISSUE THREAD

**Issue by athreyee** [AzureAD/microsoft-authentication-library-for-js#769]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [x] IE version 11
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

MSAL.js
Library version: 1.0.1
Yes , still an issue without workaround applied

## Current behavior
When user tries to acquire token using MSAL.js in IE 11 seeing the below error,
Error :login_required; Error description:AADSTS50058: A silent sign-in request was sent but no user is signed in. The cookies used to represent the user's session were not sent in the request to Azure AD. This can happen if the user is using Internet Explorer or Edge, and the web app sending the silent sign-in request is in different IE security zone than the Azure AD endpoint (login.microsoftonline.com)

With workaround of adding the needed urls under trusted sites,its working fine but we cannot request every user to do the same in PROD

## Expected behavior
Need to get token without any exception

## Minimal reproduction of the problem with instructions
1. Login to the application
2. Call acquireTokenSilent method in IE 11

return msalHelper.acquireTokenSilent(requestObj).then((tokenResponse) => {
    config.headers.Authorization = 'Bearer ' + tokenResponse.accessToken;
    return Promise.resolve(config);
  }).catch(function (error) {
</code></pre>

**Comment by DarylThayil** [comment]
@sameerag  can you please take a look at this when you get a chance ?

**Comment by sameerag** [comment]
@athreyee There is a fix that is propagated to all latest msal versions from 2.3 which stores certain data in cookies to fix this issue. More details are [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Known-issues-on-IE-and-Edge-Browser).

Enabling 'storeAuthStateInCookie = true' in MSAL configurartion should mitigate this (as the above article details it). Can you please check the same?

**Comment by athreyee** [comment]
@sameerag  We already tried this storeAuthStateInCookie as true and it didnt help . We are using MSAL .js and currently on 1.0.1. It works when we change the browser setting but we cannot ask every user to change that way so please re open the bug

**Comment by sameerag** [comment]
@athreyee Unfortunately since the restriction is from the IE browser implementation, we are limited on the support we can extend from MSAL JS. As a SPA support library, we are limited in our storage options: localStorage/sessionStorage and cannot store the tokens elsewhere as of today. 

One option we are considering is to give an option to the developer to cache the tokens; which could mitigate this issue. This developer cache storage is a future proposal and not shaped yet. 

Until then I am afraid changing the browser settings is the limitation IE 11 users may have to live with.
