### ISSUE TITLE
AngularJS 1 / 2 / 4 support

### ISSUE THREAD

**Issue by hkusulja** [AzureAD/microsoft-authentication-library-for-js#77]
Like old [Azure Active Directory Authentication Library (ADAL) for JavaScript](https://github.com/AzureAD/azure-activedirectory-library-for-js) had a [library AngularJS 1 (adal-angular.js)](https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/dev/lib/adal-angular.js), and we hope Angular 2 and Angular 4.

Are there any plans to develop Angular library inside MSAL for major stable version (1,2,4) ?

**Comment by jraadt** [comment]
With the newly released [HttpClient](https://angular.io/guide/http) in Angular it allows for interceptors. Building an interceptor like what was done for the ADAL library should be feasible now.

**Comment by hkusulja** [comment]
Maybe this can help - https://github.com/Azure-Samples/active-directory-b2c-javascript-angular2.4-spa

**Comment by Gimly** [comment]
I created a fully working example using MSAL in an Angular 4 / .Net Core application, based off the Angular 4 .Net starter template. https://github.com/Gimly/NetCoreAngularAzureB2CMsal

I also have a simpler example with just Angular 4 https://github.com/Gimly/simpleAngularAzureB2C

**Comment by hkusulja** [comment]
@Gimly great example. However it does not have Microsoft Graph API (which also should be used to pull extended properties from users) and delegation/access rights to another backend app. So properly frontend/angular (implicit flow) and backend can be devided...

**Comment by Gimly** [comment]
@hkusulja Yes, I know it has still a few things to improve. I could add easily the Graph API since I did it in the app I'm working on, but I'm using a sample Azure AD B2C tenant and therefore can't add the permission to get info from the Graph API.

Delegation/access rights to another backend app, you mean from the .Net Core backend?

**Comment by hkusulja** [comment]
So you are saying that it is not possible to get one OAuth2 token through implicit flow / angular2 from B2C AAD directory which also has a permission for:
 - Graph API, scope:xxx
 - mycustomServerBackend, scope: xxx

If so, any reference to do that?

This is normally working on "normal" AAD.

**Comment by hkusulja** [comment]
@Gimly  So you are saying that it is not possible to get one OAuth2 token through implicit flow / angular2 from B2C AAD directory which also has a permission for:

Graph API, scope:xxx
mycustomServerBackend, scope: xxx
If so, any reference to do that?

This is normally working on "normal" AAD.

**Comment by Gimly** [comment]
@hkusulja No, I'm not saying it's not possible, it's totally possible. It's just that I don't have to rights to the Azure B2C tenant I'm using in the sample and I'm not sure if they have added the rights for the app registration I'm using to use the Graph API. It's just a question of configuration.

**Comment by hkusulja** [comment]
I am sure, that if you have a Azure subscription for testing, you can create your own test Azure AD B2C , and inside it, create your applications with rights / Graph API...
I do not see way how to achieve access to Graph API and my custom backend...

**Comment by hkusulja** [comment]
So, any info about MSAL support for Angular 4+ ?

**Comment by hkusulja** [comment]
Bump, will Microsoft support the MSAL for Angular library?

**Comment by navyasric** [comment]
@hkusulja There are plans in MSAL roadmap this year for an Angular library.

**Comment by nehaagrawal** [comment]
@hkusulja @Gimly @jraadt  We have released @azure/msal-angular for angular 4.3+ and @azure/msal-angularjs for angular 1.7 on NPMJS. I am closing this issue.

**Comment by negberts** [comment]
@nehaagrawal where can we find @azure/msal-angular cause a google search only sends me to a github page of https://github.com/benbaran/msal-angular
