### ISSUE TITLE
FAQ in Wiki is deprecated

### ISSUE THREAD

**Issue by dluque92** [AzureAD/microsoft-authentication-library-for-js#777]
https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/FAQs#q10-how-to-pass-custom-state-parameter-value-in-msaljs-authentication-request-for-example-when-you-want-to-pass-the-page-the-user-is-on-or-custom-info-to-your-redirect-uri

With the new version 1.0.2: state, scope, onTokenCallBack... and more changed

**Comment by pkanher617** [comment]
@dluque92 Could you be more clear on what is missing from the FAQ?

**Comment by dluque92** [comment]
@pkanher617 Hi, yes, in the documentation how to initialize client applications:
https://docs.microsoft.com/bs-latn-ba/azure/active-directory/develop/msal-js-initializing-client-applications

`````
// Configuration object constructed
const config = {
    auth: {
        clientId: “abcd-ef12-gh34-ikkl-ashdjhlhsdg”
    }
}

// create UserAgentApplication instance
const myMSALObj = new UserAgentApplication(config);

function authCallback(error, response) {
    //handle redirect response
}

// (optional when using redirect methods) register redirect call back for Success or Error
myMSALObj.handleRedirectCallback(authCallback);

// Configuration Object
export type Configuration = {
    auth: AuthOptions,
    cache?: CacheOptions,
    system?: SystemOptions,
    framework?: FrameworkOptions
};

**Comment by sameerag** [comment]
@negoe to followup on thos
