### ISSUE TITLE
Missed state when create a new UserAgentApplication

### ISSUE THREAD

**Issue by dluque92** [AzureAD/microsoft-authentication-library-for-js#778]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 1.0.2

## Current behavior

In Configuration.ts we have the following lines to describe and define AuthOptions:

/**
 * @type AuthOptions: Use this to configure the auth options in the Configuration object
 *
 *  - clientId                    - Client ID of your app registered with our Application registration portal : https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/RegisteredAppsPreview in Microsoft Identity Platform
 *  - authority                   - You can configure a specific authority, defaults to " " or "https://login.microsoftonline.com/common"
 *  - validateAuthority           - Used to turn authority validation on/off. When set to true (default), MSAL will compare the application's authority against well-known URLs templates representing well-formed authorities. It is useful when the authority is obtained at run time to prevent MSAL from displaying authentication prompts from malicious pages.
 *  - redirectUri                 - The redirect URI of the application, this should be same as the value in the application registration portal.Defaults to `window.location.href`.
 *  - postLogoutRedirectUri       - Used to redirect the user to this location after logout. Defaults to `window.location.href`.
 *  - state                       - Use to send the state parameter with authentication request
 *  - navigateToLoginRequestUrl   - Used to turn off default navigation to start page after login. Default is true. This is used only for redirect flows.
 *
 */
export type AuthOptions = {
  clientId: string;
  authority?: string;
  validateAuthority?: boolean;
  redirectUri?: string | (() => string);
  postLogoutRedirectUri?: string | (() => string);
  navigateToLoginRequestUrl?: boolean;
};

## Expected behavior

As you can see in the comments below, is an state propertie, that is missing in the type AuthOptions

## Minimal reproduction of the problem with instructions

</code></pre>

If is not included since new versions, how can I manage it, and pass state? I need it to control state after callback in SignIn or EditProfile policies

**Comment by pkanher617** [comment]
Hi @dluque92, we allow the user to pass a state in the AuthenticationParameters object, which is the object sent in the login and acquireToken requests.

```javascript
/**
 * @link AuthenticationParameters}AuthenticationParameters
 */
export type AuthenticationParameters = {
    scopes?: Array<string>;
    extraScopesToConsent?: Array<string>;
    prompt?: string;
    extraQueryParameters?: QPDict;
    claimsRequest?: string;
    authority?: string;
    state?: string;
    correlationId?: string;
    account?: Account;
    sid?: string;
    loginHint?: string;
};

let loginRequest = {
   state = "1234"
};

loginPopup(loginRequest).then(loginResponse => {
   let responseState = loginResponse.accountState;
}).catch(error => {
   console.log(error);
});

```
This pattern should be the same for all of the login and acquiretoken APIs. Please let me know if you are still having issues.

**Comment by yakimko** [comment]
@pkanher617 I got tslint error when why to pass state property, because its not defined in type

**Comment by pkanher617** [comment]
Hm I haven't received this error before. Could you post a code snippet of your acquireToken or login call and the request object you are constructing?

**Comment by dluque92** [comment]
Hi @pkanher617 the new UserAgentApplication expects config with this format:
https://docs.microsoft.com/bs-latn-ba/azure/active-directory/develop/msal-js-initializing-client-applications

`````

export type Configuration = {
    auth: AuthOptions,
    cache?: CacheOptions,
    system?: SystemOptions,
    framework?: FrameworkOptions
};

**Comment by pkanher617** [comment]
@dluque92 As of MSAL.js v1.0.0, we no longer accept state as a configuration parameter. This is because the state needs to be set per request, not per instance of MSAL. 

The new configuration objects and parameters can be found [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-initializing-client-applications).

We have also changed how the requests for [login](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-sign-in) and [acquireToken](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-acquire-token) are made. A new object called AuthenticationParameters is now used to pass state.

**Comment by sameerag** [comment]
@dluque92 To expand specifically how a request looks:

export type AuthenticationParameters = {
    scopes?: Array<string>;
    extraScopesToConsent?: Array<string>;
    prompt?: string;
    extraQueryParameters?: Dict;
    claimsRequest?: string;
    authority?: string;
    state?: string;
    correlationId?: string;
    account?: Account;
    sid?: string;
    loginHint?: string;
};

We will be sticking to this more or less(except may be adding some more params if there is a user need). Please check the 1.0.0 [announcement](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL.js-1.0.0-api-release) for more details.

**Comment by dluque92** [comment]
@sameerag Then this file is wrong:
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/bff2b7007bfa7283fe8b9b77ca95994e5cef5c97/lib/msal-core/src/Configuration.ts

`````
/**
 * @type AuthOptions: Use this to configure the auth options in the Configuration object
 *
 *  - clientId                    - Client ID of your app registered with our Application registration portal : https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/RegisteredAppsPreview in Microsoft Identity Platform
 *  - authority                   - You can configure a specific authority, defaults to " " or "https://login.microsoftonline.com/common"
 *  - validateAuthority           - Used to turn authority validation on/off. When set to true (default), MSAL will compare the application's authority against well-known URLs templates representing well-formed authorities. It is useful when the authority is obtained at run time to prevent MSAL from displaying authentication prompts from malicious pages.
 *  - redirectUri                 - The redirect URI of the application, this should be same as the value in the application registration portal.Defaults to `window.location.href`.
 *  - postLogoutRedirectUri       - Used to redirect the user to this location after logout. Defaults to `window.location.href`.
 *  - state                       - Use to send the state parameter with authentication request
 *  - navigateToLoginRequestUrl   - Used to turn off default navigation to start page after login. Default is true. This is used only for redirect flows.
 *
 */
export type AuthOptions = {
  clientId: string;
  authority?: string;
  validateAuthority?: boolean;
  redirectUri?: string | (() => string);
  postLogoutRedirectUri?: string | (() => string);
  navigateToLoginRequestUrl?: boolean;
};

**Comment by pkanher617** [comment]
@dluque92 Thanks for pointing that out. I will fix the comments right now.

**Comment by dluque92** [comment]
@pkanher617 But also, the AuthenticationParameters has been changed, As you said [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-initializing-client-applications)

How can we pass state in this case?
Thanks!

**Comment by pkanher617** [comment]
@dluque92 This is still the configuration object.

Please see my above comment and the AuthenticationParameters.ts class.

**Comment by sameerag** [comment]
@dluque92 as @pkanher617 mentioned above, AuthenticationParameters.ts class has the detail on how to send the 'state' per request. Closing this issue as #780 is in dev.
