### ISSUE TITLE
is there an example of using MSAL.js for doing confidential client nodejs application?

### ISSUE THREAD

**Issue by johnnliu** [AzureAD/microsoft-authentication-library-for-js#779]
## I'm submitting a...

<pre><code>
[x] Documentation issue or request
</code></pre>

## Browser:
- [x] Chrome version XX
- [x] Firefox version XX
- [x] Edge version Chromium

## Library version

<pre><code>
Library version: MSAL.js any

</code></pre>

**Comment by pkanher617** [comment]
@johnnliu Thanks for the questions. Currently, the MSAL.js library only supports the implicit flow, which was built specifically for public clients. It is not recommended to use the implicit flow for confidential clients.

We do have a [roadmap](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#Roadmap) for an MSAL Node.js library which will support the auth code and device code flows for confidential clients.

**Comment by pkanher617** [comment]
Closing for now, please re-open if you are still seeing the issue.

**Comment by GerritPlehn** [comment]
Hello, I have been trying to figure this out for some days now, until I found this issue. As I gather from the roadmap you linked, this hasn't been and won't be worked on for a while. @johnnliu have you found a workaround for this, or does anybody else have any information on how one could implement this by themself?
