### ISSUE TITLE
loginStartPage URL doesn't have # when HashLocationStrategy is used

### ISSUE THREAD

**Issue by aathithan** [AzureAD/microsoft-authentication-library-for-js#782]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version 75
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 0.1.2

## Current behavior

When useHash is set to true in my angular App,
and I use MsalGuard for authenticating my application, 
after the login success and processing the token, it redirects back to my application with <hostname>/<routename> (for example 'http://localhost:4200/dashboard')

## Expected behavior

Once the login is success and after processing the token, it should redirect to http://localhost:4200/#/dashboard

## Minimal reproduction of the problem with instructions

1. Setup Azure authentication in the angular app
2. Use MsalGuard in canActivate and useHash:true in routing
3. Host the app in a server where no URL rewriting is written for path. (like static web site on an Azure blob storage)
4. Open the route which requires authentication
5. After the login success, you will see it goes to <hostname>/<route_name> which throws 404. it should have been <hostname>/#/<routename> 

</code></pre>

**Comment by sameerag** [comment]
@negoe  Can you help with the AAD requirement here? Do we support # in the reply URL?

**Comment by negoe** [comment]
@aathithan Hi Archana, Who is your target audiene? We do not support fragments in reply URL for AAD+MSA audience. It is supported for AAD only. 
cc @sameerag

**Comment by sameerag** [comment]
@aathithan Can you please confirm what is the target audience in your case?

**Comment by aathithan** [comment]
@sameerag and @negoe 

I am using Azure B2C and msal.js in my angular app to provide authentication.
Once the login is success, I get the reply URL with fragment (for e.g. #state=<token>)

But my concern here is, after processing the token, MSALGuard is redirecting to http://localhost:4200/dashboard instead of http://localhost:4200/#/dashboard.
PLEASE NOTE THE # in the URL.

**Comment by negoe** [comment]
@aathithan The # you are getting in the response is not part of the reply url, but a delimiter. MSAL and B2C  both do not support fragments in reply url. Are you able to register your B2C app on portal with this  'http://localhost:4200/#/dashboard'?
