### ISSUE TITLE
Support proxying requests for dynamic url redirects

### ISSUE THREAD

**Issue by mbrevda** [AzureAD/microsoft-authentication-library-for-js#783]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
non specific

## Library version

Library version: 1.0.2

## Current behavior

Logins expect credentials only via their own internal callbacks

## Expected behavior

Login should be able to receive an id_token and client_config from other sources and continue the flow

## Minimal reproduction of the problem with instructions

Currently, redirects are only possible to those whitelisted in the portal. While this is good for security, there are many legitimate scenarios where the url is not known in advance. For example, when using Netlify [deploy previews](https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/) where every branch/pr is deployed to a unique domain.

A possible solution would be a whitelisted proxy page can be used to forward the received credentials to the original requesting page. To facilitate this, msal might implement a method called, say, `loginFromCredentials` which can use previously received credentials. Alternatively, perhaps document how to return the received credentials from the proxy page.

To illustrate:

1. say siteA.com is whitelisted. preview-333333.netlify.com attempts to signin via popup login, specifying the redirect to siteA.com/redirect_proxy, and adding preview-333333.netlify.com to the request state.
1. the popup authenticates against azure and then redirect to siteA.com/redirect_proxy (in the same popup window launched by `msal.loginPopup`)
1. siteA.com/redirect_proxy reads the hash and parse the necessary credentials
1.
    1. if a `loginFromCredentials` method is supported, use window.postMessage to communicate back with `window.opener` and respond with the credentials, which can then be used to restart the login flow
    1. even better would be to allow the proxy to respond directly to the parent with the credentials and allow the `loginPopup` flow to continue successfully

<details>
<summary>Illistration of what the proxy page might look like</summary>

```html
<!DOCTYPE html>
<html>
    <head></head>
    <body>
        <script>
        // get  hash
        var hash = decodeURIComponent(window.location.hash)

        // convert to object of key: value
        var data = Object.fromEntries(hash.split('&').map(item => item.split('=')))

        // some method that can communicate back with the parent
        window.resolve({idToken: data.idToken, clientInfo: data.clientInfo})
        </script>
    </body>
</html>

```
</details>

Open to other ideas, too. Thanks!

**Comment by sameerag** [comment]
@mbrevda Thanks for raising this.  As you mentioned, the decision to limit the reply URLs is due to security concerns. The suggestions above are a good start, but the enhancement to support a URL list would involve  Azure Portal + AAD service support in addition to MSAL client libraries.

At this point, we cannot support this behavior but I am happy to pass this on as a suggested enhancement we are hearing from the community to the corresponding teams. Since this is beyond my team's purview we cannot promise anything solid but we will reach out once we know if there is a plan to support a white list in the near future.

@DarylThayil  @negoe to track the feasibility of this feature.

**Comment by mbrevda** [comment]
@sameerag thanks for reviewing this. Can you elaborate what changed would be needed to the portal to support option 4.ii above? To recap, I'm suggesting setting a url in the portal and using that as a proxy - no changes to the portal required.

**Comment by DarylThayil** [comment]
@mbrevda  I think I understand what you are asking for and while I think it makes sense in your use case, explicitly supporting it gives me some pause.  The surface area where an app can send sensitive information is restricted for security concerns.  Restricting it in the portal and allowing for it to proxy to another domain through the library seems to break the spirit of that restriction.

@negoe  is our PM and at the very least we will keep your feature request in mind as we determine what we work on!

**Comment by mbrevda** [comment]
> seems to break the spirit of that restriction

The spec [specifically allows](https://tools.ietf.org/html/rfc6749#section-3.1.2.2) for this type of behavior "allowing the client to dynamically vary only the query component of the redirection URI when requesting authorization".

Building this into the lib can actually help prevent secret leakage by ensuring that even while proxying these restrictions are being meet.

**Comment by DarylThayil** [comment]
Thanks for sharing, I think at this point we will take it as a feature request. If you implement this outside the lib, or even in a pr, and demonstrate how it works I would love to learn more about the use case / solution.
