### ISSUE TITLE
Change authority when calling loginPopup?

### ISSUE THREAD

**Issue by keystroke** [AzureAD/microsoft-authentication-library-for-js#784]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ x] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>

Library version: 1.0.2
</code></pre>

## Current behavior

Setting an "authority" property on the input to loginPop has no effect. Documentation in the wiki has broken links to AuthenticationParameters class when navigating from the loginPop section.

Using below code will not change the authority used in the popup page:

await msal.loginPopup({authority: 'https://login.microsoftonline.us/dynamicTenantId', prompt: 'select_account'})

## Expected behavior

code below should use the specified authority in the popup, or documentation should describe how to achieve this.

await msal.loginPopup({authority: 'https://login.microsoftonline.us/dynamicTenantId', prompt: 'select_account'})

## Minimal reproduction of the problem with instructions

await msal.loginPopup({authority: 'https://login.microsoftonline.us/dynamicTenantId', prompt: 'select_account'})

**Comment by sameerag** [comment]
@keystroke Thanks for raising this. Can you please provide the logs in this context where the "authority" in the request(AuthenticationParameters) is not honored? We set the 'authority' to default only if the user does not send a valid authority. If not, it is indeed a bug.

I will also try to reproduce this on my end.

**Comment by keystroke** [comment]
@sameerag Which logs do you need? Not sure how to retrieve them. Once I call loginPopup as described in code snippet above, the popup is directed to the original authority URL setup via the ctor of the Msal.UserAgentApplication class. I don't see the pop URL change to the new authority value.

I am not confident of the correct way to "set" the desired authority for the login request (outside of the ctor), nor am I certain that I have to... I am implementing a sort of "directory switcher" experience, so when the user selects a different directory, should I call loginPopup again with the new authority, or just proceed directly to use one of the acquire token methods and provide a new authority parameter option there?

This kind of scenario should perhaps have a dedicated example I think (maybe one exists and I missed it?), as this must be a common pattern, especially when interacting with Azure where you have to switch directories to access different subscriptions.

**Comment by sameerag** [comment]
@keystroke I guess in your scenario "when the user selects a different directory, proceeding directly to use one of the acquire token methods and provide a new authority parameter" should work. Can you try this and let me know?

We are also working on improving our samples, a merge to dev with updated samples is planned in a couple weeks. We will try including this use-case, If not in the first cut, we will do that as a follow-up. Tagged this with #samples now.

**Comment by keystroke** [comment]
@sameerag This is still not working in the latest release. Please advise if something is wrong with this code snippet:

````html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Demo</title>
</head>

<body>
    <script src="https://secure.aadcdn.microsoftonline-p.com/lib/1.1.1/js/msal.min.js"></script>
    <script>
        'use strict';
        const baseAuthority = 'https://login.microsoftonline.com';
        const defaultTenant = 'masselfhost.onmicrosoft.com';

        const msal = new Msal.UserAgentApplication({
            auth: {
                clientId: 'a963b646-fa01-4c06-b302-42c6ed1b2774',
                authority: 'https://login.microsoftonline.com/246b1785-9030-40d8-a0f0-d94b15dc002c'
            }
        });

        msal.handleRedirectCallback((error, response) => {
            if (error) console.error(error);
            if (response) console.log(response);
        });

        msal.loginRedirect({
            authority: 'https://login.microsoftonline.com/common',
            scopes: ['openid'],
            prompt: 'select_account'
        });
    </script>
</body>

</html>
````

If you open this as a web page, the redirection will be to https://login.microsoftonline.com/246b1785-9030-40d8-a0f0-d94b15dc002c/oauth2/v2.0/authorize? instead of using 'common' it is using '246b1785-9030-40d8-a0f0-d94b15dc002c' from the configuration.

I have my MSAL agent defaulting to some tenant, but when the user actually clicks my login button, I want to get the authority from an input box where the user types their target directory tenant ID or name. However, it seems that I cannot actually make this take effect!

Please advise how to make the above sample work so that the login redirect can be sent to any arbitrary directory tenant, independent of what the authority value is configured to in the MSAL user agent object.

Thanks!

**Comment by sameerag** [comment]
@keystroke Can you please try this?

msal.loginRedirect({
            authority: 'https://login.microsoftonline.com/<a different tenant-id than common or your default>',
            scopes: ['openid'],
            prompt: 'select_account'
        });

I am suspecting common is acting as a special case. I can also debug this but I would need some turnaround time as I am working on of some other issues in the pipeline. I will also check if someone from my team can pitch in if this is urgent.

**Comment by keystroke** [comment]
@sameerag That does not make any difference. Common is not acting as any special case. MSAL is just not using the authority URI specified in loginRedirect or loginPopup, it uses the one from the user agent config. I am trying to make a multitenant application here and the authority I use in my config is essentially irrelevant. I usually set it to "common" but this isn't the best approach as some users are not admins in their home directory like for MS employees and they cannot grant consent for this app in their home directories. And of course my application cannot be pre-configured with an authority value that would work for the users, so I ALWAYS need to delay authority selection until the user interacts with a login form where they can select a specific tenant or allow the form default of "common". You can use above SPA hosted from localhost to repro, try any combination of tenant hints. Keep in mind authority is valid from either the tenant ID, the tenant name, or any verified domain name associated to the directory.

**Comment by sameerag** [comment]
@keystroke Yes, I have just checked the code and I believe we are setting the use sent authority only for acquireToken() calls and not login() calls. I have something to check with requirements before I push a PR but mostly this sounds like a bug.

**Comment by sameerag** [comment]
@keystroke Investigated the requirements further. There is one problem enabling this for a generic case: MSAL JS today does not support multiple accounts concurrently. So there is one potential issue below.

**Usecase**
User1 logs in -> gets an idToken_user1
User1 makes an acquireToken() call -> gets an accessToken(user1-resource1)
User 2 logs in -> gets an idToken (user2) *This overwrites idToken_user1 as we have a fixed msal.idToken as key in the cache*
User 2 makes an  acquireToken() call -> gets an accessToken(user2-resource1)
Now if User1 makes an acquireToken() call -> User1 will get a User2 accessToken since the current idToken is for User1.

To prevent this, I believe the design limited the authority change only for acquiring tokens but not for login calls. This would be easier if msal starts supporting 'multiple accounts' and there are plans around the same.

Until then, I am a little apprehensive of providing this flexibility to the library generically.

**Comment by keystroke** [comment]
@sameerag can you clarify the issue more?

1. In an attempt to view the parameters to the acquire token calls, I find that the doc page links are broken. If you click on library reference and select any of the token methods, clicking on the hyperlink for AuthenticationParameters does not take you anywhere.

This link takes you to the acquire token silent doc page:
https://htmlpreview.github.io/?https://raw.githubusercontent.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/docs/classes/_useragentapplication_.useragentapplication.html#acquiretokensilent

They hyperlink for authentication parameters is:
https://htmlpreview.github.io/?https://raw.githubusercontent.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/docs/classes/_useragentapplication_.useragentapplication.html#authenticationparameters

Above link does not work to take me somewhere to view the actual properties that can be set for the login or acquire token methods. Please advise where I can see these properties.

2. Separate from all of this, why are you concerned about a dynamic authority value affecting the MSAL js behavior here? Don't you have the same problem if I call login methods multiple times with different accounts? I don't need to actually change the authority to get multiple accounts involved; does your scenario only occur if you login with two accounts in different authorities (directories)? Providing two different user accounts in the same authority is identical to providing the same user account in two different authorities (the user is a guest in one, and these are two separate accounts, despite them using the same username / password).

3. I see that MSAL vs. ADAL documentation explicitly redesigned their model to move away from IUser and use IAccount precisely for this scenario, because a user is a human that may have access to multiple accounts in multiple directories / authorities. Are you suggesting the JS implementation did not handle this correctly and its all because of the scope of this cache key for an id token?

4. Changing full authority values is probably not the way you want to design this. What is relevant is changing the tenantId of the authority value. Consider how you could possibly support changing the authority cross-cloud. What would it mean to login to Azure cloud, and then login another account in Azure China Cloud? Should we expect that MSAL could get tokens for these user accounts in different clouds entirely? Maybe... I suppose that would make your code as clean as possible to force yourself to design against that scenario... but I imagine it would make sense to restrict to a specific cloud at a time, because the client ID would have to change when you change clouds, so supporting this would mean giving MSAL client config a set of clientIds for each cloud (e.g. this is not a realistic scenario); all of this implies that what should be set in the configuration is a base authority URI which locks that config to a specific cloud, and then the login and acquire token methods instead accept a "directory or tenant hint" (ID, name, verified domain), rather than a full authority URI that could possible point at a different cloud entirely. The current model is a little awkward in that calling code must do this itself: keep a "base authority" URI in some config object, and swap the tenant hints. This means you can't re-use the config object given to MSAL, because it accepts a full authority URI.

5. Please let me know if you want to discuss further. I am a little concerned as I view this scenario to be fairly fundamental; I just want to have a website that can log a user into different directories. I don't even need it to be concurrent; I just want to have a button, just like in the Azure portal, that lets the user switch which directory they are signed-in to. I cannot do this today without instantiating a new MSAL user agent object. I will accept any implementation that accomplishes this, but perhaps consider some of the points above.

Thanks!

**Comment by sameerag** [comment]
@keystroke Thanks for taking time to sync up offline on this.

For 1, we have typedoc limitations we are observing in our documentation and, we will soon do better on that front.

For 2, You are right, adding this functionality doesn't prevent anyone from encountering this behaviour, I want to ensure that you are aware of this use-case before pulling in these changes.

For 3, MSAL JS 'multiple accounts' support is a work in progress. We have all the pieces ready, the cache makes some assumptions on the current user and, there is still some work pending to have this production-ready. Hence, as we stand today, 'multiple accounts' do not work as expected.

For 4, We are improvising on the developer format to input authority in the configuration. I agree that the behaviour is locked per cloud (though there are exceptions for some first-party apps). This is a different and bigger discussion as we synced. I do agree though the providing flexibility in login authority makes sense for now.

For 5, Nothing else needed I guess for now.

#915 is the PR that fixes this issue. I am working on adding meaningful Unit tests and will be merging this to dev soon.

**Comment by sameerag** [comment]
Tested #915 with Integration tests as UT is not feasible. Waiting for reviews to merge this to dev. Next release from MSAL JS should have this fix integrated.
