### ISSUE TITLE
Angular Wrapper in sync with core MSAL 1.0.x

### ISSUE THREAD

**Issue by sameerag** [AzureAD/microsoft-authentication-library-for-js#786]
This is a placeholder to track all the "Angular" specific issues which simply need the wrapper to be upgraded to the latest msal js core version.

- supports latest Angular versions with rxjs support
- is Msal JS 1.0.X compatible - with access to the new API Surfaced 

All tickets raised asking for this support will be tagged with this issue going forward. This is to simplify the traction from our end.

In case if anyone has specific Angular related requirement that you believe is not covered with the plan above, please feel free to drop a comment on this issue.

**Comment by sameerag** [comment]
From #385: Make protectedresourcemaps flexible post-initialization of MSAL.

**Comment by sameerag** [comment]
From #421: Angular 6/7/8 support with rxjs-compat

**Comment by sameerag** [comment]
From #475: Typescript typings support in Angular Wrapper

**Comment by sameerag** [comment]
From #786: redirectURI as a function -> This should happen when the wrapper is compatible with msal 1.0.x

**Comment by sameerag** [comment]
From #526: Separate the ATS redirect handling from the main application code. Write a small html/js service that processes the token extraction and passes the control to the parent (Angular app) to avoid reload every time a token is acquired.

**Comment by sameerag** [comment]
From #539: Routes without router guard would need full path match before they are pushed to unprotected resources. Add this as a test case for the new Angular Wrapper.

**Comment by sameerag** [comment]
From #507: Error handling for Angular Wrapper.

**Comment by sameerag** [comment]
From #497: Introduce a flag in the angular wrapper for the interceptor to fallback to interactive calls when acquireTokenSilent fails. This is needed for the wrapper as the angular developers has no control of the interceptor code to write the fall back code themselves.

**Comment by sameerag** [comment]
From #733: Angular wrapper for error handling

**Comment by sameerag** [comment]
From #629: prompt=select_account removal from msal js. This is already addressed in msal 0.2.4 but since angular is stuck on an older version, this is an issue for some users. Feedback is to not hardcode msal versions to be used with angular, #785 partially addresses this - revisit if more checks are needed.

**Comment by sameerag** [comment]
From #614: state parameter set by the user in request to be sent in the response. Addressed in latest msal js 1.0.x.

**Comment by sameerag** [comment]
From #481: Make msal configuration in Angular dynamic

**Comment by sameerag** [comment]
From #598: Route guard does not have the ability to handle acquireTokenSilent() failure. See how to better design this in the new angular wrapper.

**Comment by sameerag** [comment]
From #788: Same as #526. Redirect routed to a different HTML than the main angular app.

**Comment by sameerag** [comment]
From #585: Redirect sample and documentation for Angular

**Comment by sameerag** [comment]
From #729: Broadcast does not work when the token is picked up from cache in Angular (using sessionStorage).

**Comment by sameerag** [comment]
From #703: Msal Guard to support redirect to "Access denied page" as CanActivate guards support URLTree as a return type now in Angular. Feature-ask for the angular wrapper.

**Comment by jasonnutter** [comment]
From https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/552: Support glob patterns for protected resources

**Comment by jasonnutter** [comment]
From https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/729: No event when token is retrieved from cache
