### ISSUE TITLE
Too long time for each request

### ISSUE THREAD

**Issue by vcs38** [AzureAD/microsoft-authentication-library-for-js#788]
Hi,

I'm facing issue whith this very helpful library.

Each time I' doing a request to microsoft, the iframe is reloading and my app is very heavy to load therefore it happens that for each request the resulat displays after 15-20 seconds.

I'm giving you some code to help me.

this is how I configure the module
`MsalModule.forRoot({
      clientID: '00944399-ee66-47b8-84d6-bbc64656a3fc',
      loadFrameTimeout: 20000,
      cacheLocation : 'localStorage',
    }),`

this is my service

    import { Injectable } from '@angular/core';
    import { MsalService } from '@azure/msal-angular';
    import { Client } from '@microsoft/microsoft-graph-client';
    import { Calendar, Event as MicrosoftEvent } from '@microsoft/microsoft-graph-types';
    import * as moment from 'moment';
    import { from, Observable, ReplaySubject } from 'rxjs';
    import { map } from 'rxjs/operators';
    import { ConfService } from '../../../shared/service/configuration/conf.service';
    import { CalendarProvider } from '../../model/calendar-provider.model';
    import { AppointmentOrigin, ExternalAppointment } from '../../model/external- 
       appointment.model';
    import { calendarDefaultColor, ExternalCalendar } from '../../model/external-calendar.model';
    import { MicrosoftListResponse } from '../../model/microsoft-calendar.model';
    import { MicrosoftUser } from '../../model/microsoft-user.model';
    import { UserLoggedIn } from '../../model/user-logged-in.model';

    @Injectable()
    export class MicrosoftProviderService implements CalendarProvider {
      user: UserLoggedIn | undefined;
      private authenticated: boolean;
      private _userLoggedIn: ReplaySubject<UserLoggedIn> = new ReplaySubject(2);
      private graphClient: Client;

      constructor(
        private msalService: MsalService,
        private confService: ConfService) {
        this.initClient();

        this.authenticated = this.msalService.getUser() != null;

        this.getUser().then((user: UserLoggedIn) => { this.user = user; });
      }

      signIn(): void {
        this.msalService.loginPopup(this.confService.getMicrosoftScopes())
          .then((result: string) => {
            if (result) {
              this.authenticated = true;
              this.getUser()
                .then((user: UserLoggedIn) => {
                  this.user = user;
                  this._userLoggedIn.next(user);
                });
            } else {
              this._userLoggedIn.next();
            }
           })
      .catch(() => {
        throw new Error('microsoft script not loaded');
      });
      }

      signOut(): void {
        this.msalService.logout();
        this.user = undefined;
        this.authenticated = false;
        this._userLoggedIn.next();
      }

      getUserLoggedIn(): Observable<UserLoggedIn> {
        return this._userLoggedIn.asObservable();
      }

      getMyEvents(): Observable<ExternalAppointment[]> {
        const start: string = this.formateDateToStringForMicrosoft(moment().subtract(1, 'months'));
        const end: string = this.formateDateToStringForMicrosoft(moment().add(2, 'months'));
        return from(this.getAllEvents(0, start, end, ''));
      }

      getAllCalendars(): Observable<ExternalCalendar[]> {
        const observable: Observable<ExternalCalendar[]> = from(this.graphClient
          .api('/me/calendars')
          .get())
          .pipe(map((result: MicrosoftListResponse<Calendar>) => {
            const externalCalendars: ExternalCalendar[] =
              result.value && result.value.length ? result.value.map((cal: Calendar) =>
                ({
                   id: cal.id ? cal.id : '',
                  displayName: cal.name ? cal.name : '',
                  color: this.getCalendarColor(cal),
                }),
              ) : [];

           return externalCalendars;
          }));

         return observable;
      }

      getEventsForCalendar(calendarId: string): Observable<ExternalAppointment[]> {
        const start: string = this.formateDateToStringForMicrosoft(moment().subtract(1, 'months'));
        const end: string = this.formateDateToStringForMicrosoft(moment().add(2, 'months'));
        return from(this.getAllEvents(0, start, end, calendarId));
      }

      private async getAccessToken(): Promise<string> {
        const result: string = await 
    this.msalService.acquireTokenSilent(this.confService.getMicrosoftScopes())
          .catch(() => {
            throw new Error('could not get access token');
          });

        return result;
      }

      private initClient(): void {
        this.graphClient = Client.init({
          authProvider: async (done: (reason: string, token: string) => void): Promise<void> => {
            const token: string | void = await this.getAccessToken()
              .catch((reason: string) => {
                done(reason, '');
              });

            if (token) {
              done('', token);
            } else {
              done('Could not get an access token', '');
            }
         },
        });
      }
thanks for your help

**Comment by sameerag** [comment]
Same as #526; We do not have a fix yet but strongly considering to contain the refresh in an upcoming angular wrapper release. Please check our [roadmap](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#roadmap) for the latest announcements. 

We are also tracking all angular issues regarding the upgrade to msal core 1.0.x with #786.

My apologies that we do not have a readymade solution yet. Some of the responses linked in #526 had some approaches which may help you mitigate the problem meanwhile.

**Comment by sameerag** [comment]
Link to #526
