### ISSUE TITLE
Preview in github description

### ISSUE THREAD

**Issue by StefanSchoof** [AzureAD/microsoft-authentication-library-for-js#794]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: N/A
</pre></code>

## Current behavior

The github project has the description "Microsoft Authentication Library (MSAL) _Preview_ for JS", but there is a version 1 out.

## Expected behavior

If version 1 is released the preview in the description is droped.

## Minimal reproduction of the problem with instructions

1. go to https://github.com/AzureAD/microsoft-authentication-library-for-js
![grafik](https://user-images.githubusercontent.com/4662023/60252978-89408200-98cb-11e9-811a-edd8e9dec10e.png)
and see this is a preview
2. go to https://github.com/AzureAD/microsoft-authentication-library-for-js/releases and see the latest version is greater than 1
3. Be unsure if this is a preview or not

</code></pre>

**Comment by sameerag** [comment]
Thanks @StefanSchoof for raising this. @negoe Can we please correct this?

**Comment by DarylThayil** [comment]
I fixed this the other day without seeing this, thanks for letting u know @StefanSchoof
