### ISSUE TITLE
How to access SID received in other tab?

### ISSUE THREAD

**Issue by NickSevens** [AzureAD/microsoft-authentication-library-for-js#796]
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report  
- [ ] Performance issue
- [ ] Feature request
- [x] Documentation issue or request
- [ ] Other... Please describe:

## Library version

Library version: 1.0.2

## Question

I'm trying to implement MSAL in a client side library, which works pretty well so far.
Now for my next steps I'm trying to add SSO by following the documentation at https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-sso#automatically-select-account-on-azure-ad
In this documentation it is pointed out that I can add the **sid** claim to the auth requests, and reuse that sid in my second tab when logging in.

Now my main question is: what is the process to **access the sid retrieved in tab A, and then re-use it in tab B?**

**Comment by sameerag** [comment]
@NickStevens if you set the cache to 'localStorage' aren't you logged in by default? sid is usually passed in use cases where there is a plugin or an app that talks to the parent app and does have access to the msal responses. In the above documentation, It is stated that for access between tabs, localStorage as cache would be the better option.

**Comment by NickSevens** [comment]
@sameerag fair enough. :) I was under the impression that the SID way was an alternative to using localStorage. But as you said, localStorage does work for my use-case as well.
Thanks for the info.
