### ISSUE TITLE
Documentation typo, Example Part 3

### ISSUE THREAD

**Issue by mswehli** [AzureAD/microsoft-authentication-library-for-js#80]
Part 3 of the example on the index page of the repo (https://github.com/AzureAD/microsoft-authentication-library-for-js) appears to contain an typo of a misplaced parentheses,
// interaction required 
            if(error.indexOf("interaction_required" != -1)) {

should isntead be:
 if(error.indexOf("interaction_required") != -1){

**Comment by rohitnarula7176** [comment]
PR submitted

**Comment by rohitnarula7176** [comment]
Fixed
