### ISSUE TITLE
tokenReceivedCallback is not called when using MSAL AngularJS with Azure B2C

### ISSUE THREAD

**Issue by leniel** [AzureAD/microsoft-authentication-library-for-js#808]
## I'm submitting a

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[X] Other... Please describe:
</code></pre>

## Browser:
- [X] Chrome version 75.0.3770.100
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: msal.js 1.0.2
</code></pre>

## Current behavior

After successful login, tokenReceivedCallback is not called...

## Expected behavior
tokenReceivedCallback should be called.

## Minimal reproduction of the problem with instructions

```
msalProvider.init({
    clientID: "Client ID here",
    authority: "https://login.microsoftonline.com/tfp/myb2caad.onmicrosoft.com/B2C_1_SignUpSignIn",
    validateAuthority: false,
    //consentScopes: ["https://myb2caad.onmicrosoft.com/test/user_impersonation"],
    tokenReceivedCallback: function (errorDesc, token, error, tokenType) {
        debugger;
        if (token) {
            console.log('Token type: ' + tokenType + ' Token: ' + token)
        }
        else {
            console.log(errorDesc + error)
        }
    }
},
    $httpProvider // Optionally, pass http provider to inject request interceptor to attach tokens
);
```

Doing:

```msalService.loginPopup();```

and then:

```
$rootScope.$on("msal:loginSuccess", function () {
    console.log("loginSuccess");

    var token = msalService.userInfo.idToken;
});
```

I can see that userInfo.isAuthenticated is true and there's an id token present.

However, tokenReceivedCallback is never called. Can you spot the problem or give some hints where to look for it?

Note that this is a B2C AAD. Maybe I'm forgetting to set something elsewhere.

**Comment by DarylThayil** [comment]
@leniel can you try doing a .then off of login popup and see if that triggers, login popup is a promise but redirect requires the callback to be registered so on page reload we can call it.

**Comment by leniel** [comment]
The problem was happening because the app was messing with hashPrefix. I had to do:

```
app.config(['$locationProvider', function($locationProvider) {
    $locationProvider.html5Mode(false).hashPrefix('');
}]);
```

The hashPrefix was interfering with the callback.

It's mentioned here: https://www.npmjs.com/package/@azure/msal-angularjs
