### ISSUE TITLE
Support response_mode configuration for msal_angular

### ISSUE THREAD

**Issue by kwinyyyc** [AzureAD/microsoft-authentication-library-for-js#809]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
"@azure/msal-angular": "^0.1.2"
"@angular/core": "~8.1.0",
"@angular/router": "~8.1.0",
</code></pre>

## Current behavior
Is the response_mode configuration supported in msal_angular?

I am now facing a problem with the callback format as <code>#id_token=ABC&state=123&session_state=123</code>
Angular Router does not able to detect the route with "&" in it.
So I have tried #id_token=ABC does trigger the route correctly and render the correct component

That's why I want to see if the response_mode configure is supported? so that I can use the query param format with question mark instead of a hash style

Thanks!

**Comment by negoe** [comment]
@kwinyyyc The response_mode can not be supported. The reason behind the issue can be more of a way angular is identifying the routes than supporting a specific query parameter.
