### ISSUE TITLE
MSAL.js replacement of adal.js?

### ISSUE THREAD

**Issue by alexandro81** [AzureAD/microsoft-authentication-library-for-js#81]
Hi guys,
I was just wondering if MSAL.js is supposed to be the replacement for adal.js to consume from single-page applications Azure AD version > 1.

**Comment by jmprieur** [comment]
Hi @alexandro81: [MSAL.js](https://github.com/AzureAD/microsoft-authentication-library-for-js) works with the [AzureAD V2 endpoint](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-appmodel-v2-overview), whereas ADAL.js works with the [AzureAD V1 endpoint](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-developers-guide). The V1 endpoint supports work accounts, but not personal accounts. The V2.0 endpoint is the  unification of Microsoft personal accounts and work accounts into a single authentication system. Finally, with msal.js you can also get authentications for Azure AD B2C.
HTH.

**Comment by alexandro81** [comment]
Hi @jmprieur,
thanks for the quick response!
So that means that if we switched to AzureAD v2, we could use MSAL.js to authenticate work accounts, mirroring what we're currently doing by consuming AzureAD v1 through adal.js.
Is that correct?

**Comment by jmprieur** [comment]
Yes @alexandro81, I think so. But mind you that msal is for the moment in preview. Not all the scenarios are yet supported. For JavaScript, though, I think that this should be ok (this implements the implicit flow).

**Comment by juliepwchen** [comment]
Hi, can someone help with this question?  I want to call a Microsoft Graph API on behalf of an user. I am following the example on github at "active-directory-javascript-graphapi-v2-core".  Using app.js, my app was able to get to the login screen.  But after the credentials were entered, it returned an URL with an "id_token" and an error message on my debugger "SecurityError: Permission denied to access property "msal" on cross-origin object".  What did I do wrong?  Is it configuration or code?  It seems like the "id_token" was supposed to be handled by MSAL, but it seems to be CORS problem?  HELP???
