### ISSUE TITLE
Missing documentation for extraQueryParameters

### ISSUE THREAD

**Issue by snebjorn** [AzureAD/microsoft-authentication-library-for-js#818]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Library version

<pre><code>
Library version: "@azure/msal-angular": "0.1.2"
</code></pre>

## Current behavior
I can't seem to find any documentation on what the config `extraQueryParameters` is supposed to be used for.

https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-initializing-client-applications

## Expected behavior
There should be some documentation.

**Comment by jasonnutter** [comment]
@negoe Is this something we could add to the documentation? I agree the purpose of `extraQueryParameters` isn't clear.

**Comment by sameerag** [comment]
@negoe We had documentation for this prior to API changes, looks like it is missing with the new surface documentation. Can you please fill this gap? I can work with you if you need help with code samples.

@snebjorn Thanks for raising this.

**Comment by jmckennon** [comment]
@aiwangmicrosoft can you work with @sameerag and @negoe on this one too?

**Comment by sameerag** [comment]
This will be addressed as a part of #964. Closing.
