### ISSUE TITLE
Authentication on Safari not working due to ITP 2.0

### ISSUE THREAD

**Issue by siebigteroth** [AzureAD/microsoft-authentication-library-for-js#819]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [x] Safari version XX

## Library version

<pre><code>
Library version: 1.0.1

</code></pre>

## Current behavior

Acquiring an access token doesn't work on safari.

## Expected behavior

Acquiring an access token should work.

## Minimal reproduction of the problem with instructions

Acquire a token on safari silently.

## Reason
This is already a known issue, because ITP 2.0 restricts access to the cookies: https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Known-issue-on-Safari

## Solution
Solve it like auth0 did: https://auth0.com/docs/api-auth/token-renewal-in-safari
The Azure AD B2C has to offer the functionality to use custom domains. So we can configure a custom domain like login.contoso.com for all authentication steps for our contoso.com website.

**Comment by siebigteroth** [comment]
There is also a user voice for the azure ad b2c going on to allow the configuration of custom domains: https://feedback.azure.com/forums/169401-azure-active-directory/suggestions/15334317-customer-owned-domains
But there doesn't seem to be an update in the progress since 2 years.

**Comment by juho-hanhimaki** [comment]
I believe this issue does affect all AD scenarios, not just B2C? Custom login/authorization domain support for AD would indeed be a neat workaround.

**Comment by jasonnutter** [comment]
As you point out, this is currently a known issue, and unfortunately we currently don't have a good work around. While custom domains are not generally available yet, it is a goal to do so eventually (I can't provide an ETA, unfortunately).

Closing this as there isn't anything actionable at the moment. Appreciate the feedback!
