### ISSUE TITLE
'endpoint' is not defined in sample code

### ISSUE THREAD

**Issue by Pheil** [AzureAD/microsoft-authentication-library-for-js#821]
#607  I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ x] Chrome version 77.0.3849
- [ x] Firefox version 68.0

## Library version

<pre><code>
Library version: 1.0.2
</code></pre>

## Current behavior
I believe when updating this sample  (https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/master/lib/msal-core/samples/VanillaJSTestApp/index_externalAPI.html#L107) for the version 1.0 changes the error function wasn't updated

`callMSGraph(endpoint, tokenResponse.accessToken, graphAPICallback);`

## Expected behavior
I think this is the correct call.
`callMSGraph(graphConfig.graphMeEndpoint, tokenResponse.accessToken, graphAPICallback);`

## Minimal reproduction of the problem with instructions
'endpoint' is not defined.

**Comment by sameerag** [comment]
@Pheil @jasonnutter I remember prithvi fixing this in one of his PRs. I can make the changes needed with another PR, it is a typo that cropped up.

**Comment by jasonnutter** [comment]
Yeah that sounds good, thanks!

**Comment by sameerag** [comment]
Closing this with #857
