### ISSUE TITLE
Obtain Application roles from idToken

### ISSUE THREAD

**Issue by RecuencoJones** [AzureAD/microsoft-authentication-library-for-js#833]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version 75
- [ ] Firefox version XX
- [ ] IE version XX
- [x] Edge version 76
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 1.0.2

</code></pre>

## Current behavior

Once SSO is successful I know who the user is but not which roles he has assigned.

## Expected behavior

Once the SSO is successful I would expect to be able to get user roles from the idToken in order to restrict parts of the applications or actions to admin users only.

## Minimal reproduction of the problem with instructions

I created an example in codesandbox.io: https://codesandbox.io/s/vue-template-evqjg
The code is also checked in at https://github.com/RecuencoJones/Vue-Azure-SSO-example

<details>
<summary>Previous steps to setup Azure AD</summary>
<ol>
<li>Create an Azure AD directory.</li>
<li>Create an App Registration on Azure AD.</li>
<li>On Advanced settings, check both <code>Access tokens</code> and <code>ID tokens</code> for Implicit grant.</li>
<li>Edit following manifest fields:<br><br>
<pre>
  "accessTokenAcceptedVersion": 2,
  "appRoles": [
    {
      "allowedMemberTypes": [
        "User",
        "Application"
      ],
      "description": "Admin user for the application",
      "displayName": "Administrator",
      "id": "ccf2cb33-c1d2-4101-a1e8-b88e1d3806b2",
      "isEnabled": true,
      "lang": null,
      "origin": "Application",
      "value": "AdminUser"
    },
    {
      "allowedMemberTypes": [
        "User",
        "Application"
      ],
      "description": "Common user for the application",
      "displayName": "User",
      "id": "2ca47286-7be9-47b8-9c76-1369b3021506",
      "isEnabled": true,
      "lang": null,
      "origin": "Application",
      "value": "RegularUser"
    }
  ],
  "groupMembershipClaims": "All",
  "oauth2AllowIdTokenImplicitFlow": true,
  "oauth2AllowImplicitFlow": true,
  "signInAudience": "AzureADandPersonalMicrosoftAccount",
</pre>
</li>
<li>Create an Enterprise Application bound to previous App Registration</li>
<li>Add your user to the Enterprise Application and assign Admin role.</li>
</ol>
</details>

Test:
1. Fork the sandbox https://codesandbox.io/s/vue-template-evqjg
1. Update App registration Redirect URIs to add `https://<sandbox-id>.codesandbox.io` as `Web` type.
1. Copy Application Client ID from App registration and replace the value of `clientId` in `config/auth.js` with it.
1. Open the live preview in a new tab (codesandbox does not allow redirect within their embedded preview).
1. Attempt to SSO.
1. Check developer console for Account object and browse idToken entry. 
1. No claims related to roles can be found.

**Comment by RecuencoJones** [comment]
Could it be that this happens only for guest users and / or users which are not part of the AAD organization (i.e those not having a `.onmicrosoft.com` domain)?

**Comment by jasonnutter** [comment]
I believe this may be similar to #677. The short answer there is that the `wids` claim may not be present in tokens generated via the implicit flow due to length concerns ([source](https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens#payload-claims), scroll down to `wids`).

Does that sound right @sameerag?

**Comment by sameerag** [comment]
Yes. I am working with the server team to understand if there is a workaround to support implicit flow users in this context, will reach out once I close the loop with them. Can we close this as a dup for #677?

**Comment by RecuencoJones** [comment]
It might be a similar issue, but I observe this only with users which do not directly belong to Azure AD (i.e guest users or users from different domains)

If I attempt to log in with a user belonging to the AAD it returns the roles claim just fine.

I.e: https://gh1hp.codesandbox.io/
User: test@recuedav.onmicrosoft.com
Pass: Qopa3741

From the console you can check the output:
![image](https://user-images.githubusercontent.com/7302877/61444277-58dc8880-a94b-11e9-8e35-e0e41db19c5c.png)

**Comment by RecuencoJones** [comment]
Okay, so I got to solve the issue over the weekend, I was just missing adding the following to my configuration: 

```
authority: `https://login.microsoftonline.com/${ tenantId }`
```

After that I'm able to retrieve the roles for all users registered in the application.

**Comment by RecuencoJones** [comment]
On another hand (maybe should create another issue for this one?) once the `auth.loginRedirect()` returns with success I'm able to access `auth.getAccount().idToken` – decoded already. 

Would it be possible to also add the property `rawIdToken` to it without having to use `auth.acquireTokenSilent()` and/or `auth.acquireTokenRedirect()`?

**Comment by RecuencoJones** [comment]
Hi @sameerag, I previously noticed that `handleRedirectCallback()` response contains `rawIdToken`, but this callback is only called the first time user triggers SSO log in. 

Once they are logged in, this callback is not called anymore until logged out or token expired. Thus, we need to rely on calling `auth.acquireTokenSilent()`, so it does not really work.

I would somehow expect `auth.getAccount()` to contain the same data this callback returns.

As a workaround I could try loading `msal.idToken` from `sessionStorage` instead.

**Comment by sameerag** [comment]
@RecuencoJones There is a `response` for every `request` made to MSAL JS. The `response.idToken.rawIdToken` should have the info you are looking for. In your case for the subsequent calls after the `loginRedirect` call, you are probably calling `acquireTokenSilent` which returns the response in a promise format. 

If there is any confusion regarding this, please let me know.

**Comment by sameerag** [comment]
Closing this. Please open a new issue if there are further questions.
