### ISSUE TITLE
user getting logged out automatically while clicking on anywhere on the page

### ISSUE THREAD

**Issue by AbhaysinghBhosale** [AzureAD/microsoft-authentication-library-for-js#834]
**Version**: msal 0.2.4
**Implementation Code** :
`constructor() {
    let redirectUri = '......................example';
    this.applicationConfig = {
      clientID: ........................,
      graphScopes: ['user.read']
    };
    const logger = new Msal.Logger(this.loggerCallback, { level: Msal.LogLevel.Verbose })
    this.app = new Msal.UserAgentApplication(
      this.applicationConfig.clientID,
      '',
      () => {
        var self = this;
      },
      {
        logger,
        cacheLocation: 'localStorage',
        redirectUri,
        navigateToLoginRequestUrl: false
      }
    );

    this.user = null;
  }`

**Login method:** 
`login = () => {
    const user = this.app.getUser();
    return Promise.all(this.app.loginRedirect(this.applicationConfig.graphScopes)).then(
      idToken => {
        if (user) {
          return user;
        } else {
          return null;
        }
      },
      () => {
        return null;
      }
    );
  };`

**Browser** : Chrome
I have used this package in my react application for user login. Users get logged in successfully and it was working fine till last few days. 

From last few days we are experiencing the issue with the logout. We have kept the logout button which clears the msal.idtoken stored in localStorage. But this is happening without clicking on the logout button. Users got logged out automatically.

**Comment by jasonnutter** [comment]
@AbhaysinghBhosale When reporting, it would be appreciated if you could use the issue template, it helps us investigate your issue (e.g. which version of the library are you using, which browsers are impacted, etc).

Can you please provide reproduction steps?

**Comment by AbhaysinghBhosale** [comment]
@jasonnutter i have updated the issue with the details

**Comment by AbhaysinghBhosale** [comment]
@jasonnutter is there any update on this issue. I am getting this too many times now. While debugging found that localStorage is getting cleared. there is no single line of code in application which clear localStorage.

**Comment by jasonnutter** [comment]
@AbhaysinghBhosale It would helpful if you could share a full sample app that demonstrates your issue (e.g. a private Github repo that you can invite me to). Thanks!

**Comment by sameerag** [comment]
@AbhaysinghBhosale Can you please test this with `msal js`  version`1.1.3`?  Also please add repro steps for us to address this issue.

**Comment by AbhaysinghBhosale** [comment]
Found the reason for this  It was not an issue in msal We are logging out user(clear storage) on 1 hr of inactivity So if an tab is open and minimized(kept idle) for long time It was clearing all active tabs localStorage So use working in other tabs was getting logged out due to an idle tab
