### ISSUE TITLE
AngularJS (1.6) app with redirect for a custom B2C Sign Up policy

### ISSUE THREAD

**Issue by leniel** [AzureAD/microsoft-authentication-library-for-js#835]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[X] Other... Please describe:
</code></pre>

## Browser:
- [ X ] Chrome version 75.0.3770.142
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
msal v1.0.2 2019-06-21 +
msal-angular.js wrapper I got here: https://www.npmjs.com/package/@azure/msal-angularjs
</code></pre>

## Current behavior
After Sign Up policy runs it redirects to the AngularJS app with #id_token=tokenhere like this:

`https://localhost:49208/#id_token=eyJ0eX...`

That's OK. It shows that it's working... I checked the token @ jwt.io and it has all the custom claims I added, etc.

The problem is that the AngularJS is not using this #id_token returned by the B2C policy.

This is the code I use to setup the AngularJS app:

```
// MSAL - Microsoft Authentication Library (MSAL) for Angular JS
// https://github.com/AzureAD/microsoft-authentication-library-for-js
// https://www.npmjs.com/package/@azure/msal-angularjs
app.config(['$httpProvider', 'msalAuthenticationServiceProvider', function ($httpProvider, msalProvider) {
    const config = {
        clientID: "clientIdHere",
        authority: "https://tenant.b2clogin.com/tenantId/B2C_1A_signin_only",
        tokenReceivedCallback: function (errorDesc, token, error, tokenType) {
            if (token) {
                console.log('Token type: ' + tokenType + ' Token: ' + token)
            }
            else {
                console.log(errorDesc + error)
            }
        },
        optionalParams: {
            redirectUri: "https://localhost:49777/",
            unprotectedResources: ["/ng/views/directives/system/footer.html"],
            navigateToLoginRequestUrl: false,
            validateAuthority: false // https://docs.microsoft.com/en-us/azure/active-directory-b2c/b2clogin
        }
    }

    msalProvider.init(config,
        $httpProvider // Optionally, pass http provider to inject request interceptor to attach tokens
    );

}]);
```
I posted a question @ StackOverflow that describes what's going on in more detail: https://stackoverflow.com/q/57062803/114029

I now am able to get the token with location.hash however I think that the AngularJS app should\could parse this automagically for me when the #id_token is present in the URL.

Am I wrong assuming this behavior?

If I'm wrong, is there any way I can tell MSAL that hey... I have an id_token in the URL, can you please use it to set you up? :) I hope you can shed some light on this question.

I also asked this other question @ SO: https://stackoverflow.com/q/57085159/114029

## Expected behavior
Once the Sign Up policy redirects back to the app, it should parse the id_token automatically and sign in the user so that the guard\interceptor set to the $httpProvider above just works as expected and my OWIN handler setup in the ASP.NET MVC app gets called.

**Comment by DarylThayil** [comment]
We are no longer supporting AngularJs / Angular version 1.
We will be supporting 4+ by the end of the year #786
