### ISSUE TITLE
Azure ADB2C logout doesn't invalidates access token.

### ISSUE THREAD

**Issue by Statowfiq** [AzureAD/microsoft-authentication-library-for-js#838]
Azure ADB2C logout doesn't invalidates access token.

I am using MSAL 0.2.4 library. The logout function logs out me from my application and redirects me back to login. But the access token is still alive. I am able to use the old access token to access my webAPI.

The access token is not getting invalidated post logout.

**Comment by pkanher617** [comment]
@Statowfiq Thanks for bringing this to our attention, I will try to reproduce this today.

**Comment by sameerag** [comment]
@Statowfiq is this also seen in msal 1.0.x? Is it possible for you to test it?

**Comment by nscdde02** [comment]
Hello! Did you ever have the way to reproduce it? I am facing the same situation in an Enterprise application. I already tried to force the clearing, removing local storage, session storage, indexed DB and cookies but still retrieves the token after logout.

**Comment by Statowfiq** [comment]
Yes. I am able to reproduce the problem.

But i didn't get solution yet.

**Comment by sameerag** [comment]
@ktsakas friendly bump :)

**Comment by mcdonnell-john** [comment]
Any idea if/when this will be implemented?

Currently also facing this issue at the moment, and would love to see if resolved.

**Comment by tnorling** [comment]
This is expected behavior. Access tokens cannot be invalidated on logout. For this reason, access tokens have shorter lifetimes in the browser (1 hour)
