### ISSUE TITLE
acquired token silent timeout for token renewal on Azure B2C

### ISSUE THREAD

**Issue by kangcity** [AzureAD/microsoft-authentication-library-for-js#839]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x ] Chrome version 71.0.3578.98 (Official Build) (64-bit)
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: @azure/msal-angular": "^0.1.2"

</code></pre>

## Current behavior
B2C Token Lifetime : 10mins
B2C Session Lifetime : 24hours
Msal Angular ClockSkew : 300 (5mins)

We able to login to Azure B2C to retrieve the access token and authenticate it in the web API  successfully. But after 5 mins where the access token expired in local storage, we failed to retrieve the new token from Azure B2C by calling acquireTokenSilent function with error message returned "Token renewal operation failed due to timeout|Token Renewal Failed".

After investigate, we found the error is due to Iframe unable to resolve the B2C end point eg
https://xxxxx/b2c_1_sparksignupsignin/oauth2/v2.0/authorize?xxxx for the first time and it can be success with new access token if we call acquireTokenSilent function again.
Stepping thru further in the msal-angular.js code, we noticed that the loadFrame function to resolve the end point URL come with the setTimeout delay 500 ms as show below:-

UserAgentApplication.prototype.loadFrame = function (urlNavigate, frameName) {
        var _this = this;
        // This trick overcomes iframe navigation in IE
        // IE does not load the page consistently in iframe
        this._logger.info("LoadFrame: " + frameName);
        var frameCheck = frameName;
        setTimeout(function () {
            var frameHandle = _this.addAdalFrame(frameCheck);
            if (frameHandle.src === "" || frameHandle.src === "about:blank") {
                frameHandle.src = urlNavigate;
                _this._logger.infoPii("Frame Name : " + frameName + " Navigated to: " + urlNavigate);
            }
        }, 500);
    };

Why the timeout delay is set to 500ms? Will this cause the end point URL set on iframe failed on first hit and it can be success for next?

## Expected behavior

The acquireTokenSilent can return the access token on the first call

**Comment by kangcity** [comment]
I'm writing a simple program to further test on the issue as code below:-

import { Component } from '@angular/core';
import { MsalService, BroadcastService } from '@azure/msal-angular';
import { from } from 'rxjs';
import { environment } from 'src/environments/environment';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'msal';

  accesstoken: string;
 
  constructor(private msal:MsalService, private broadcastService:BroadcastService) { }

  login() {
    this.msal.loginRedirect();
  }

  acquiretoken(){
    debugger;
     var urlscopes = environment.gaAPIUrl;
     const scopes = this.msal.getScopesForEndpoint(urlscopes);
     from(this.msal.acquireTokenSilent(scopes).then(token => {
       this.accesstoken = token
     }));
  }
}

I can login and acquire the access token successfully.  After access token expired, I try hit the acquiretoken again it will failed with error caught as below:-

ERROR Error: Uncaught (in promise): Token renewal operation failed due to timeout|Token Renewal Failed
    at resolvePromise (zone.js:831)
    at resolvePromise (zone.js:788)
    at zone.js:892
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:26760)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at drainMicroTaskQueue (zone.js:601)
    at push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask (zone.js:502)
    at ZoneTask.invoke (zone.js:487)

![image](https://user-images.githubusercontent.com/53026407/61506936-5b57e480-aa16-11e9-9b94-0e411544ce26.png)

If I try it again this error gone with the new access token returned.

**Comment by kangcity** [comment]
@pkanher617 Any update on this issue? We are keep facing the same error on the first hit on the B2C open id after the access token expired by calling the acquireTokenSilent.

**Comment by rick-hayek** [comment]
i'm experiencing the same error

**Comment by sameerag** [comment]
Closing this as there is no update, @kangcity please raise a new issue if the above comments do not clarify the problem.
