### ISSUE TITLE
Where can I see which versions of Angular are supported?

### ISSUE THREAD

**Issue by jstallm** [AzureAD/microsoft-authentication-library-for-js#841]
Is there a single location to obtain this information? It appears at the surface that its up to angular 5.x, and that Angular 6+ and WIP. Can we get an official response on this please? Thank you in advance if this information is obtainable somewhere else, I just dont see it being very apparent to me, and its not obvious when looking at the 
https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-angular readme at all.

**Comment by sameerag** [comment]
@negoe Can we please add this in the Readme under angular?

**Comment by aiwangmicrosoft** [comment]
Here is my suggestion: https://github.com/AzureAD/microsoft-authentication-library-for-js/compare/dev...aiwangmicrosoft:patch-1#diff-3b1cbf21d93b8654b77b5bf8649ebaa5

**Comment by aiwangmicrosoft** [comment]
Should I create a pull request?

**Comment by jmckennon** [comment]
@aiwangmicrosoft this looks fine, coordinate with @jasonnutter for other angular information supported in the next few months so we can close here.

**Comment by aiwangmicrosoft** [comment]
@jasonnutter can you review my suggestion? I also updated the readme.md
