### ISSUE TITLE
Get a V1 token using MSAL.js

### ISSUE THREAD

**Issue by Meberem** [AzureAD/microsoft-authentication-library-for-js#844]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[X] Other... Please describe: General Help 
</code></pre>

## Library version
```
"@azure/msal-angular": "^0.1.2"
```

## Current behavior
I end up getting a V2 token for an app that requires a V1 token

## Expected behavior
I would be able to get a V1 token

## Minimal reproduction of the problem with instructions
I have setup an angular project like so:
```
@NgModule({
	declarations: [AppComponent],
	imports: [
		...,
		MsalModule.forRoot({
			clientID: "{applicationGuid}",
			authority: "https://login.microsoftonline.com/{tenantGuid}/",
		}),
	]
})
```

Where the application Id is that of Azure Blockchain Workbench product. I have added my applications URLs to the list of Reply URLs for the ADD Application and I am able to get a Bearer token as expected. When I go to use this token with the Blockchain API I get a 401 unauthorized. The only meaningful difference I can see between the tokens is the issuer url and the version

v1 token: https://sts.windows.net/2c72df40-3a20-41cd-a628-424afba070a5/
v2 token: https://login.microsoftonline.com/2c72df40-3a20-41cd-a628-424afba070a5/v2.0

I have a Swagger UI setup that will correctly generate an access token using the same authority and client id which leads me to believe it is the token version that is the issue. 

What can I do to fix this?

I have tried setting the `consentScope` to `["{applicationGuid}/.default"]` but then I end up with a v1 token for Microsoft Graph.

**Comment by kylemar** [comment]
_I have tried setting the consentScope to ["{applicationGuid}/.default"] but then I end up with a v1 token for Microsoft Graph._

In general, you should not inspect the access token that is intended for Microsoft Graph, or other APIs. When you set the scope to /.default did calls to Microsoft Graph succeed as well as the calls to the Blockchain API?

**Comment by Meberem** [comment]
I didn't really want to inspect the token, I needed to to figure out why I was getting 401 with what I thought was a valid setup. I don't really mind how to get the token I just thought as everything in the setup was MS/Azure that it would all fit together nicely.

I have created a [sample repo](https://github.com/Meberem/ng-ms-authenticator-v1-token) just needs a valid `/src/environments/environment.dev.ts` file with the following
```
export const environment = {
  production: false,
  appId: "{AppGuid}",
  tennantId: "{TennantGuid}"
};
```

With the scope like so: `consentScopes: ["/.default"]` I get the following error:
![image](https://user-images.githubusercontent.com/441023/62043931-febcac80-b201-11e9-8bb6-ef31c4e8f411.png)

**Comment by sameerag** [comment]
@negoe to follow up on this in the upcoming week.

**Comment by jberlyn** [comment]
Hey guys, any update on this issue?

**Comment by jberlyn** [comment]
Almost 3 months, still no response, can we please get an update on this?

**Comment by jasonnutter** [comment]
@jberlyn @Meberem Apologies for the delay. This should be possible by editing the manifest and setting `accessTokenAcceptedVersion`: https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-app-manifest#manifest-reference

**Comment by jasonnutter** [comment]
Closing, as the question is answered above.

**Comment by jberlyn** [comment]
@jasonnutter  I'm sorry but this doesn't solve the original issue.

The question I believe relates to whether it's possible to get an AAD v1 token using MSAL, not the access tokens.

If you take a look at the sample tokens in this documentation (https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens), you can see that the issuer URL is different. The original poster @Meberem also pointed this out.

I have done as instructed in your document and adjusted the accessTokenAcceptedVersion, but I'm still receiving a v1 ID token when using MSAL.

**Comment by jasonnutter** [comment]
@jberlyn By "token" do you mean ID tokens?

Also, see this answer: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/560#issuecomment-620133340
