### ISSUE TITLE
Leading blank space in scope makes token caching mechanism not work

### ISSUE THREAD

**Issue by mmuarc** [AzureAD/microsoft-authentication-library-for-js#845]
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ x] Performance issue
[ x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x ] Chrome version 75.0.3770.100
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

Library version: 1.0.2

## Current behavior
AB2c Server is contacted to renew a token

## Expected behavior
Token should be retrieved from the storage

## Minimal reproduction of the problem with instructions

I didn't know exactly how to tag this because I don't think it is exactly a bug, but here is what happens.

I have my scopes in a comma separated string like this:

REACT_APP_SCOPES='https://xxxx/read, https://xxxx/write'

Please notice the blank space after the comma.

When I login with msal I pass the requested scopes doing a string split getting the following:

'https://xxxx/read'
' https://xxxx/write'  (Again, notice the leading blank space)

When I try to login, I assume that somewhere in the flow the scopes are trimmed and I get back a valid access token with the following scopes.

'https://xxxx/read'
'https://xxxx/write'  (The leading blank space is gone!)

Next time I request a token, I again pass it with the blank leading space... and the code for finding a cached token does this:

`// filter by authority and scope
        for (var i = 0; i < tokenCacheItems.length; i++) {
          var cacheItem = tokenCacheItems[i];
          var cachedScopes = cacheItem.key.scopes.split(" ");
 if (Utils.containsScope(cachedScopes, scopes) && Utils.CanonicalizeUri(cacheItem.key.authority) === serverAuthenticationRequest.authority) {
            filteredItems.push(cacheItem);
          }`
So the cached scopes come like this:

[
  "https://xxxx/write",
  "https://xxxx/read"
]  (the space is gone)

but I'm passing the scopes with the leading space, so UserAgentApplication can't find the scopes because the blank space doesn't exist there.

The result is that my application was reaching the server every time for a new token due to this fault, causing it to be really slow on performance.

I understand this doesn't necessarily need to be a bug, but if when getting the access token for the first time the leading blank spaces are trimmed, they should always be trimmed. Another option would be to just refuse the login with uknown scope error due to the leading blank space.

What is currently happening is possibly worst possible scenario, ignoring the space in certain part of the code only for later misbehaving and causing performance issues.

Surely I just removed the blank space from the scope and everything works as expected but it took me a while to figure that this little blank space was causing so much a performance issue.

Thank you very much for your time and for the work you put in this library.

Miguel

**Comment by DarylThayil** [comment]
Thanks for submitting this @mmuarc , I agree this may not be a bug but it is an interesting potential confusing case for developers.  @pkanher617 / @sameerag  @jasonnutter  thoughts on whether we should trim scopes on the way in?

**Comment by sameerag** [comment]
Yes @DarylThayil, I think we should factor out all scopes behavior into a single place and have good documentation around it. Will come up with a plan regarding the same, once I conclude how auth libraries, in general, should handle these use-cases.

**Comment by DarylThayil** [comment]
@pkanher617  to add an update

**Comment by DarylThayil** [comment]
@pkanher617  if we can close this in September lets do it, otherwise lets move to future minor
