### ISSUE TITLE
Circular Dependency Utils.js -> ClientAuthError.js -> Utils.js

### ISSUE THREAD

**Issue by nmetulev** [AzureAD/microsoft-authentication-library-for-js#847]
## I'm submitting a...

<pre><code>
[x] Other... Please describe: Code quality 
</code></pre>

## Browser:
- [x] Chrome version XX
- [x] Firefox version XX
- [x] IE version XX
- [x] Edge version XX
- [x] Safari version XX

## Library version

<pre><code>
Library version: 1.0.2

</code></pre>

## Current behavior

Utils.ts is importing:

[import { ClientAuthError } from "./error/ClientAuthError";](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/src/Utils.ts#L10)

And ClientAuthError.ts is importing:

[import { Utils } from "../Utils";](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/src/error/ClientAuthError.ts#L5)

This is creating a circular dependency.

## Expected behavior

Circular dependencies should be avoided as they create high coupling and can cause [various issues](https://softwareengineering.stackexchange.com/questions/11856/whats-wrong-with-circular-references). Since ClientAuthError is only using the `isEmpty` one liner static method from Utils, the simplest solution would be to replace the usage of `isEmpty` in ClientAuthError with the one liner and remove the dependency. 

I'm open to creating a PR if you agree.

**Comment by jasonnutter** [comment]
The offending line is actually about to be removed in the PR addressing your base64 issues, so this will be resolved in the next release. Thanks!
