### ISSUE TITLE
Make CacheLocation an enum

### ISSUE THREAD

**Issue by jodonnell** [AzureAD/microsoft-authentication-library-for-js#848]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: X.Y.Z

</code></pre>

## Current behavior

when setting cacheLocation with typescript the user becomes victim to type widening so something like this is required
```
  const config = {
    auth: {
      authority: (process.env.REACT_APP_AUTHORITY as string),
      clientId: (process.env.REACT_APP_AAD_APP_CLIENT_ID as string),
    },
    cache: {
      cacheLocation: ('localStorage' as CacheLocation),
      storeAuthStateInCookie: true,
    },
  };
```

## Expected behavior

I think it would be a bit clearer if CacheLocation was an enum so that may be used directly without type widening

```
enum CacheStorage {
  LocalStorage = "localStorage",
  SessionStorage = "sessionStorage"
}
........
  const config = {
    auth: {
      authority: (process.env.REACT_APP_AUTHORITY as string),
      clientId: (process.env.REACT_APP_AAD_APP_CLIENT_ID as string),
    },
    cache: {
      cacheLocation: CacheStorage.LocalStorage,
      storeAuthStateInCookie: true,
    },
  };
```

See discussion here: https://github.com/syncweek-react-aad/react-aad/issues/95#issuecomment-513383239

**Comment by sameerag** [comment]
Sure. @jodonnell Are you open to submitting a PR for the same?

**Comment by jodonnell** [comment]
https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/851

i was only sort of able to test this in context so i'm not 100% confident it works like i want it to :'(

**Comment by sameerag** [comment]
Merged this to dev, @jodonnell Please let us know if you need anything else in this context.
