### ISSUE TITLE
Login not working after update

### ISSUE THREAD

**Issue by ncausey** [AzureAD/microsoft-authentication-library-for-js#867]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [x] Edge (Chromium) version 77.0.223.0
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 1.1.1

</code></pre>

## Current behavior

When updated from 1.0.2 to 1.1.1, with no other code changes, the login 'succeeds' and returns a response, but the account object properties are all undefined or null. On version 1.0.2 login works as expected, and I am able to use the login info (idToken, username, etc.).

## Expected behavior

Version 1.1.1 does not break existing login behavior and I can continue to access the account and user info.

## Minimal reproduction of the problem with instructions

All config setup to work with 1.0.X -> update to 1.1.1.

This is using Azure AD B2C and the login redirect.

```TypeScript
  applicationConfig: Configuration = {
    auth: {
      authority: AUTHORITY,
      clientId: CLIENT_ID,
      postLogoutRedirectUri: 'myLogoutRedirectUri',
      redirectUri: 'myRedirectUri',
      validateAuthority: false
    },
    cache: {
      cacheLocation: 'localStorage',
      storeAuthStateInCookie: true
    }
  };
  loginRequest: AuthenticationParameters = {
    authority: myAuthority,
    prompt: 'select_account',
    scopes: ['openid', 'offline_access']
  };
```

**Comment by pkanher617** [comment]
Hi @ncausey thank you for the details.

Can you verify exactly which parameters are not being populated in the account object? Is the entire object null or is it only specific properties?

**Comment by pkanher617** [comment]
@ncausey I tried to reproduce the issue with our b2c [sample](https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp) and wasn't able to see the issue you described. Do you have any repro steps or screenshots which may help?

**Comment by ncausey** [comment]
@pkanher617 the `homeAccountIdentifier` is populated, but all other parameters are null or undefined.

For me to repro this with my code, I update the version to 1.1.1 and log the response, it is not working.
This same code on version 1.0.2 for me logs the response and it all looks as expected.

```TypeScript
  this.userAgentApplication.handleRedirectCallback((error, response) => {
      if (response) {
        console.log(response);
      }
  ...
  });
  this.userAgentApplication.loginRedirect(this.loginRequest);
```

**Comment by DarylThayil** [comment]
@sameerag  is this related to claims?

**Comment by DarylThayil** [comment]
@ncausey  can you confirm this is still an issue in 1.1.3

**Comment by ncausey** [comment]
@DarylThayil it looks like it is still not working for me in 1.1.3. Same thing where it does return a response, rather than an error, but the properties of the response are undefined.

**Comment by ncausey** [comment]
If it helps, I'm using Facebook as an identify provider, and followed these examples to create custom policies in Azure AD B2C https://github.com/Azure-Samples/active-directory-b2c-custom-policy-starterpack/tree/master/SocialAccounts

**Comment by sameerag** [comment]
cc @ktsakas

**Comment by jmckennon** [comment]
@ncausey Can you pull down the latest beta `msal@1.2.0-beta.5` and see if this is still an issue?

**Comment by ncausey** [comment]
Yes, I will try to pull it down soon and test this. I'll update here when I have the results.

**Comment by ncausey** [comment]
@jmckennon it seems to be working with `msal@1.2.0-beta.5`. I'm not seeing the issues and am able do what I need as before.

**Comment by sameerag** [comment]
Great! Thanks @ncausey, closing this issue now.
