### ISSUE TITLE
MSAL Angular sample does not work in IE11

### ISSUE THREAD

**Issue by bachoang** [AzureAD/microsoft-authentication-library-for-js#869]
demo sample app https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-angular/samples/MSALAngularDemoApp does not work correctly.  It works fine in Chrome but not IE 11.  I am already using the sample from the dev branch (the default one from master branch is even worse showing blank screen).  
 
I see the following error in IE 11 console going through the login process
 

HTML1300: Navigation occurred.
localhost:4200
Angular is running in the development mode. Call enableProdMode() to enable the production mode.
client loggingThu, 25 Jul 2019 06:59:50 GMT:1234-0.2.1-Info Navigated Popup window to:https://login.microsoftonline.com/<blank out>/oauth2/v2.0/authorize?response_type=id_token&scope=user.read%20https%3A%2F%2Fxxx.onmicrosoft.com%2FtestOIDCWeb%2Fuser_impersonation%20openid%20profile&client_id=53365ba0-9e94-4db7-9cc1-c428bc3c55a8&redirect_uri=http%3A%2F%2Flocalhost%3A4200%2F&state=1fbda1bf-2490-448c-b699-2830029d278a&nonce=fddf7d4a-bce0-4198-8741-b31fb8417243&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=0.2.1&client-request-id=77156d00-b0d8-4f58-afdb-be73e85493e0&prompt=select_account&response_mode=fragment
ERROR TypeError: Object doesn't support this action
   "ERROR"
   {
      [functions]: ,
      __proto__: { },
      description: "Object doesn't support this action",
      message: "Object doesn't support this action",
      name: "TypeError",
      number: -2146827843,
      stack: "TypeError: Object doesn't support this action
   at UserAgentApplication.prototype.broadcast (eval code:388:9)
   at Anonymous function (eval code:360:21)
   at ZoneDelegate.prototype.invokeTask (eval code:422:13)
   at onInvokeTask (eval code:4972:17)
   at ZoneDelegate.prototype.invokeTask (eval code:422:13)
   at Zone.prototype.runTask (eval code:195:21)
   at ZoneTask.invokeTask (eval code:498:17)
   at invoke (eval code:487:21)
   at timer (eval code:2281:17)",
      Symbol(observable)_h.3q2j3sm1nti: undefined,
      Symbol(rxSubscriber)_g.3q2j3sm1nti: undefined
   }

 

client loggingThu, 25 Jul 2019 06:59:53 GMT:1234-0.2.1-Error Error during login:
user_cancelled|User closed the popup window and cancelled the flow
login failure {"_error":"user_cancelled","_errorDesc":"User closed the popup window and cancelled the flow","_scopes":""}
ERROR Error: Uncaught (in promise): user_cancelled|User closed the popup window and cancelled the flow
   "ERROR"
   {
      [functions]: ,
      __proto__: { },
      description: "Uncaught (in promise): user_cancelled|User closed the popup window and cancelled the flow",
      message: "Uncaught (in promise): user_cancelled|User closed the popup window and cancelled the flow",
      name: "Error",
      promise: { },
      rejection: "user_cancelled|User closed the popup window and cancelled the flow",
      stack: "Error: Uncaught (in promise): user_cancelled|User closed the popup window and cancelled the flow
   at resolvePromise (eval code:831:25)
   at Anonymous function (eval code:741:17)
   at Anonymous function (eval code:285:17)
   at ZoneDelegate.prototype.invoke (eval code:390:13)
   at onInvoke (eval code:4981:17)
   at ZoneDelegate.prototype.invoke (eval code:390:13)
   at Zone.prototype.run (eval code:150:17)
   at Anonymous function (eval code:889:17)
   at ZoneDelegate.prototype.invokeTask (eval code:422:13)
   at onInvokeTask (eval code:4972:17)",
      Symbol(observable)_h.3q2j3sm1nti: undefined,
      Symbol(rxSubscriber)_g.3q2j3sm1nti: undefined,
      task: { },
      zone: { }
   }

 
After providing credential the popup window does not go away:

**Comment by jasonnutter** [comment]
This is a known issue that we are currently investigating, and should hopefully have a fix soon. Closing as a duplicate, but will update when we have a fix. Thanks!
