### ISSUE TITLE
doesn't work with angular 8

### ISSUE THREAD

**Issue by alvipeo** [AzureAD/microsoft-authentication-library-for-js#870]
Tried to use MSAL for angular today, followed the readme but got bunch of compile errors from node_modules/@angular-msal-whatever.

No, I did not use rxjs-compat. If this is a lib for Angular please make it clean and work smoothly!
Now it's not usable.

Angular 8.

**Comment by DarylThayil** [comment]
@alvipeo  Thanks for reaching out, angular is on our roadmap and work should hopefully begin soon to get it to 1.0.0 angular 6+

**Comment by alvipeo** [comment]
yeah, you're 3 versions behind... so I wonder what "soon" means.

**Comment by DarylThayil** [comment]
https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#roadmap 
Definitely feel the pain on your end. this is our roadmap right now. 
We are trying to get the core library and issues into the best place to move angular over ASAP. 
 cc @negoe

**Comment by DarylThayil** [comment]
closing, tracked in #786
