### ISSUE TITLE
Need clarification on how to use MSAL.js in angular 6+/ latest angular projects

### ISSUE THREAD

**Issue by abannsunny** [AzureAD/microsoft-authentication-library-for-js#876]
## I'm submitting a...

[ ] Documentation issue or request/ incremental bug fixes to wrapper libraries

I understand that the main focus of this project is to add functionality to the core MSAL.js library and not the wrapper libraries. 

But I see that the road map shows that the angular wrapper library update has been pushed back to Oct-Dec 2019 from june-august-2019.

Please advise on how to use this library with latest version of angular and other libraries since a lot of features are broken at the moment in the angular wrapper and hacks like adding rxjs-compat has to be done to make the wrapper library work at all. Angular 9 will be released oct/nov 2019 which will for sure break more things.

So my questions are: 

Is there a way to use the js library without using the angular wrapper in an angular project? if yes please point to a resource or an example of the same. 
If no then please provide suggestions on how to use msal with the latest angular version since the wrapper project will drift from the latest versions of angular.

Is it possible to bring incremental bug fixes to the wrapper libraries so that it won't block people?
critical functionality like  acquireTokenSilent() is broken in the wrapper library
When I tried to implement the loginRedirect() instead of the Loginpopup[() the acquireTokenSilent() fails with login required error. 

It will be nice to get another answer than just its on the roadmap and it is planned because the roadmap keeps changing.

thank you

**Comment by DarylThayil** [comment]
#901 is tracking the work for this.  The goal is to have a good holdover sample / direction for angular users until Msal Angular 1.0.0 is ready
