### ISSUE TITLE
UserAgentApplication.getAccount() returns incorrect account in multi-tenant scenario

### ISSUE THREAD

**Issue by tylerjwatson** [AzureAD/microsoft-authentication-library-for-js#877]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [X] Chrome version 74.0.3729.169 (Official Build) (64-bit)
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 1.1.1

</code></pre>

## Current behavior
In a multi-tenant scenario when using local storage as a cache mechanism, UserAgentApplication.getAccount() returns the first user that was logged in as dictated by the `msal.idtoken` key.

I have two UserAgentApplications in two tabs under two separate authorities:

1) `https://login.microsoft.com/sampletenant1.onmicrosoft.com`, and
2) `https://login.microsoft.com/sampletenant2.onmicrosoft.com`.

Both cases are the same person logging in to different tenants under different accounts.

UserAgentApplication.getAccount() for `sampletenant2` will return the account logged in under the `sampletenant1`, leading to erroneous access tokens and `Unauthorized` responses.

## Expected behavior

`UserAgentApplication.getAccount()` return the account scoped to the correct authority so that users may enjoy single sign-on without needing to clear and reload caches.

This is a design issue.  Since `getAccount()` is an instance method of `UserAgentApplication` I expect that information returned by using its instance methods be scoped to that application.  I feel that using a storage key of `msal.idtoken|<authority>` would suffice in this scenario and not break any functionality.

## Minimal reproduction of the problem with instructions

* Set up MSAL with localStorage as a cache option
* Instantiate two UserAgentApplications in two separate tabs (or the same tab)
* Log in under the first tenant
* Log in under the second tenant
* Observe `UserAgentApplication.getAccount()` returning the identity of the first tenant in the second tenant's UserAgentApplication instance.

**Comment by sameerag** [comment]
This could be probably achieved by supporting "tenant profiles" in MSAL JS. Adding it as notes to follow up.

**Comment by pkanher617** [comment]
@tylerjwatson Could you please upgrade to 1.1.3 and see if it fixes the issue? We added the client-id to scope the cache keys, so you should no longer be receiving the wrong account for your tenant. We will re-open if you are still having issues.
