### ISSUE TITLE
Excessive amount of calls to https://xx.b2clogin.com/xx.onmicrosoft.com/xx/v2.0/.well-known/openid-configuration

### ISSUE THREAD

**Issue by prooli22** [AzureAD/microsoft-authentication-library-for-js#879]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version 75.0.3770.142
- [x] Firefox version 68.0.1
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 1.1.1

</code></pre>

## Current behavior

For each call to my Web API which requires an accessToken from MSAL, there's one call to the OpenID Profile/Policy Configuration. I don't recall that many calls to this route (https://ezpz.b2clogin.com/ezpz.onmicrosoft.com/B2C_1_USER_SUSI_V2/v2.0/.well-known/openid-configuration), before upgrading to MSAL 1.1.1

## Expected behavior

I would expect to be only one call to this config for an entire session in the app, not one for each call to the API.

## Minimal reproduction of the problem with instructions

My config looks like this : 
```
// The current application coordinates were pre-registered in a B2C tenant.
var appConfig = {
  b2cScopes: ["https://ezpz.onmicrosoft.com/api-dev/User.Read"],
  webApi: "https://neurhome-api.azurewebsites.net/api/protected"
};
```
```
// configuration to initialize msal
var msalConfig = {
    auth: {
        clientId: "c0c5214c-35a4-416a-a2ff-e95af3496c38", //This is your client ID
        authority: "https://ezpz.b2clogin.com/ezpz.onmicrosoft.com/B2C_1_USER_SUSI_V2", //This is your tenant info
        validateAuthority: false
    },
    cache: {
        cacheLocation: "sessionStorage",
        storeAuthStateInCookie: true
    }
};
```

I've tested my MSAL settings into your [JS MSAL APP](https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp) and I'm experiencing the same issue. 

Another thing is when I refresh the page and I'm already logged in, there's NO call to the config, which is weird, and I haven't been able to "control" the calls at all, from a MSAL config to another. 

Is there some new settings to update into ADB2C ? 
Is there a different behavior in you library wether there's already a token or not in the storage ? 

Thank you for helping out !

**Comment by prooli22** [comment]
After digging in the MSAL source code and debugging, I just found out that for every `acquireTokenSilent()` call, there's a `"Token is not in cache for scope:https://ezpz.onmicrosoft.com/api-dev/user.read openid profile"` which explain the call to /openid-configuration. But then, how come the token is not in cache after login in ? But it is after a refresh ?

**Comment by sameerag** [comment]
@prooli22 This is something we are actively debugging. @pkanher617 is there an existing GitHub issue that already tracks this issue?

**Comment by prooli22** [comment]
![image](https://user-images.githubusercontent.com/21690832/62154453-bcb06b00-b2d4-11e9-9cd8-a4a33461b759.png)

Looks like the `ScopeSet.containsScope(cachedScopes, scopes)` https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/81d01b6c8a0a67d1a31b5d4530d3cb10b7a6af48/lib/msal-core/src/UserAgentApplication.ts#L1331, is not doing the right thing ...

I think there should be the https://ezpz.onmicrosoft.com/api-dev/User.Read scope in the filteredItems right ?

**Comment by prooli22** [comment]
After the refresh the scopes array looks like this : `["https://ezpz.onmicrosoft.com/api-dev/User.Read"]` without the "openid" and "profile" and that seems to do the trick when looking if the cachedScopes contains the scopes....

**Comment by prooli22** [comment]
I just found a work around for this : 
```
clientApplication.loginPopup({ scopes: ['https://ezpz.onmicrosoft.com/api-dev/User.Read'], prompt: 'select_account' })

clientApplication.acquireTokenSilent({ scopes: ['https://ezpz.onmicrosoft.com/api-dev/User.Read'] })
```

Instead of : 
```
var appConfig = {
  b2cScopes: ["https://ezpz.onmicrosoft.com/api-dev/user.read"],
  webApi: "https://neurhome-api.azurewebsites.net/api/protected"
};

var loginRequest = {
  scopes: appConfig.b2cScopes,
  prompt: 'select_account'
};

clientApplication.loginPopup(loginRequest).then(function (loginResponse)

var tokenRequest = {
  scopes: appConfig.b2cScopes,
};

clientApplication.acquireTokenSilent(tokenRequest).then(function (tokenResponse
```

The thing is I think the MSAL code is mutating the array of scopes by adding "openid" and "profile" to it. But the changes are effective till the `appConfig` so for every other call you won't have the good array of scopes passed in as the request's scopes.

I hope this help some of you, and looking forward for a soon to be fix 👍

**Comment by sameerag** [comment]
#875 is fixing this. @pkanher617 will announce the details.

**Comment by jasonnutter** [comment]
Looks like this was fixed, please let us know if not. Thanks!
