### ISSUE TITLE
Rxjs v.6+ support

### ISSUE THREAD

**Issue by peshos** [AzureAD/microsoft-authentication-library-for-js#880]
## I'm submitting a bug

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Version update/support
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: latest

</code></pre>

## Current behavior

When using the library in a project with angular v8+, rxjs v6+, the following error is shown during compilation:

ERROR in node_modules/@azure/msal-angular/dist/broadcast.service.d.ts(1,10): error TS2305: Module '"[PROJECT]/node_modules/rxjs/Subscription"' has no exported member 'Subscription'.

## Expected behavior

Compile successfully.

## Minimal reproduction of the problem with instructions

Create a project with angular v8+ and rxjs v6+

**Comment by jasonnutter** [comment]
@peshos Does installing `rxjs-compat` fix that error?

**Comment by peshos** [comment]
@jasonnutter Yes,` rxjs-compat` resolves the error.

Thinking back, this should have been a feature request rather than a bug. Sorry about this :(

**Comment by jasonnutter** [comment]
@peshos No worries, that information is helpful for us, thanks!
