### ISSUE TITLE
All Adal, Msal, Passport libs in our Msal Mono Repo

### ISSUE THREAD

**Issue by DarylThayil** [AzureAD/microsoft-authentication-library-for-js#881]
Should we pull in all other repos into our mono repo for easy to manage bug filing, build / deploy consistency etc... 
Is it confusing to have adal in an msal lib? 
I think these libs will see benefits even if they are not in active development

**Comment by jasonnutter** [comment]
Long term this may not be a bad idea, but I think for now we should stick with just the MSAL libs. Once our monorepo setup is more mature I think pulling those in would be worth consideration.

**Comment by sameerag** [comment]
I am also concerned about communicating this to teams using ADAL. ADAL JS is in production for people from years and changing the github reference before we have a solid strategy on the monorepo setup, especially details on managing releases, may not be a great idea.

**Comment by DarylThayil** [comment]
Sold lets close it

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
