### ISSUE TITLE
acquireTokenSilent raise a page refresh

### ISSUE THREAD

**Issue by m4ss1m0g** [AzureAD/microsoft-authentication-library-for-js#884]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[X] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [X] Chrome version 75
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 1.1.1
</code></pre>

## Current behavior
When calling the `acquireTokenSilent` **AND** specify more than ONE scope on ``AuthenticationPramaters` the lib cannot find the cached token

I found a possible bug on **Utils.js** on method **containsScope** that return always false when requiring `scopes: [`api://${this._settings!.clientId}/access_as_user`, 'openid']`

`
Utils.containsScope = function (cachedScopes, scopes) {
        cachedScopes = this.convertToLowerCase(cachedScopes);
        return scopes.every(function (value) { return cachedScopes.indexOf(value.toString().toLowerCase()) >= 0; });
    };
`

## Expected behavior
Do not refresh the page

## Minimal reproduction of the problem with instructions
1. Specify more that one scope on request
2. Complete the authentication
3. Hit the refresh button
4. You see the log that the page is refreshed

## TEMP Workaround
Specify ONLY one scope
 `scopes: [`api://${this._settings!.clientId}/access_as_user`]`

## See also
#526

**Comment by DarylThayil** [comment]
@pkanher617  please comment on status of fix you are working on

**Comment by jasonnutter** [comment]
Closing a duplicate, see the PR linked above for progress on a fix.
