### ISSUE TITLE
ERROR DOMException: "'#access_token=... is not a valid selector"

### ISSUE THREAD

**Issue by kumader** [AzureAD/microsoft-authentication-library-for-js#885]
We did not see this issue with calling acquireTokenSilent in Firefox with our basic MSAL JS version nor have we heard this issue from any of our current customers using angular. Our angular example works with the use-case you mentioned. I suspect some local settings in your case.

Please feel free to open a new issue once you have more data on this.

_Originally posted by @sameerag in https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/694#issuecomment-509889890_

--------------------------------------------------------------------------------------------------

Hello,

We're still experiencing an issue with this under Firefox. Please let me know, specifically, what information you need to help us resolve this. I've copied the complete exception text below.

Thanks in advance,
Derek

ERROR DOMException: "'#access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6InU0T2ZORlBId0VCb3NIanRyYXVPYlY4NExuWSIsImtpZCI6InU0T2ZORlBId0VCb3NIanRyYXVPYlY4NExuWSJ9.eyJhdWQiOiI0NjMxYmM2ZS1lMzFhLTQ2NjUtOGI3NS05OWMzZmIwYTU4ZjkiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8xYTUyZWFkYS05ODNhLTQ3ZTgtYjAwYS00NTVjZjhiYjExZDMvIiwiaWF0IjoxNTY0NTE4NzQ3LCJuYmYiOjE1NjQ1MTg3NDcsImV4cCI6MTU2NDUyMjY0NywiYWNyIjoiMSIsImFpbyI6IkFVUUF1LzhNQUFBQXBOcFhBY0VHT2R2VkpHTHkwTDJlamNlYmphQmFhc2lieXArN3VBWDE3aW1TSEI5aEFySGhWM2J0N24xTUl1bDRuZFViZ0JRTURXdjBRZEF4QjE3WXpnPT0iLCJhbXIiOlsicHdkIl0sImFwcGlkIjoiMGMyMmQ5NmEtZmI1Mi00N2UwLWE2ZTAtNzU0MDA1ZTc1Njk2IiwiYXBwaWRhY3IiOiIwIiwiZW1haWwiOiJkZXJlay5rdW1hZ2FpQGVsZWt0cm9iaXQuY29tIiwiaWRwIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvZTc2NGMzNmItMDEyZS00MjE2LTkxMGQtOGZkMTYyODMxODJkLyIsImlwYWRkciI6IjUwLjIyOC4xMTEuMTU0IiwibmFtZSI6Ikt1bWFnYWksIERlcmVrIiwib2lkIjoiNmYzODRhMmMtYzc0Ni00N2VhLTgxOWMtOTEwZWJmZDVlYWIyIiwic2NwIjoidXNlcl9pbXBlcnNvbmF0aW9uIiwic3ViIjoiN0NUZXYzNGpqalZrUFZZRnUwaklwSTlDT0tHS1BqOV82alE1QWlzSEd0MCIsInRpZCI6IjFhNTJlYWRhLTk4M2EtNDdlOC1iMDBhLTQ1NWNmOGJiMTFkMyIsInVuaXF1ZV9uYW1lIjoiZGVyZWsua3VtYWdhaUBlbGVrdHJvYml0LmNvbSIsInV0aSI6ImxSaTJ6RjdrZ1U2V1g5dTBOandBQUEiLCJ2ZXIiOiIxLjAifQ.kUk96u_TB_ta8si983ULA1wVfdbzZ3Ul62tCRIJKTBo7o2Q7rWwXDZaN13XOiayuufQ1Q2xCAWJ05Ky-hR598zu-FvO440-5S2Tau8L7m8ll9rg5TebI2I4byMy8ir6lJr6n8mcfIRu9yAuoQu8kVLsgARObRrNPlxJXwmX1TP9vkg4rUNKHYWHmN5a9pVoR07_Il67PyXY2Nz0gAfKpBmxffSYo22irnMCdOaKZ1vd5_G0rmJs9FGhs_3r59zPI1gCFaqHBNT-5RvofIciu0iWfGtO2oOl6KlAWyhOkjvezmBFo68dEdG85VtTM5uCloe7eOrliHqW890EYaKq0hQ&token_type=Bearer&expires_in=3600&scope=4631bc6e-e31a-4665-8b75-99c3fb0a58f9/user_impersonation+4631bc6e-e31a-4665-8b75-99c3fb0a58f9/.default&client_info=eyJ1aWQiOiI4ZDY1NmUxNi01Yjc2LTQ1MWEtOWI0Ni1kOTdkMDI5NTY3ZGQiLCJ1dGlkIjoiZTc2NGMzNmItMDEyZS00MjE2LTkxMGQtOGZkMTYyODMxODJkIn0&state=61c416eb-467d-4916-8a0d-92b3a7fafcfc&session_state=ad9c861c-ff1f-4c8a-8ffd-70cdf6ce2a3a' is not a valid selector" vendor.js:77211:19
    defaultErrorLogger https://auth-testlab.azurewebsites.net/vendor.js:77211
    handleError https://auth-testlab.azurewebsites.net/vendor.js:77259
    next https://auth-testlab.azurewebsites.net/vendor.js:79258
    schedulerFn https://auth-testlab.azurewebsites.net/vendor.js:75002
    __tryOrUnsub https://auth-testlab.azurewebsites.net/vendor.js:210284
    next https://auth-testlab.azurewebsites.net/vendor.js:210222
    _next https://auth-testlab.azurewebsites.net/vendor.js:210165
    next https://auth-testlab.azurewebsites.net/vendor.js:210142
    next https://auth-testlab.azurewebsites.net/vendor.js:209907
    emit https://auth-testlab.azurewebsites.net/vendor.js:74986
    onHandleError https://auth-testlab.azurewebsites.net/vendor.js:78808
    invoke https://auth-testlab.azurewebsites.net/polyfills.js:5935
    run https://auth-testlab.azurewebsites.net/polyfills.js:5694
    runOutsideAngular https://auth-testlab.azurewebsites.net/vendor.js:78745
    onHandleError https://auth-testlab.azurewebsites.net/vendor.js:78808
    handleError https://auth-testlab.azurewebsites.net/polyfills.js:5939
    runTask https://auth-testlab.azurewebsites.net/polyfills.js:5742
    invokeTask https://auth-testlab.azurewebsites.net/polyfills.js:6042
    invoke https://auth-testlab.azurewebsites.net/polyfills.js:6031
    timer https://auth-testlab.azurewebsites.net/polyfills.js:7825

​
​

**Comment by jasonnutter** [comment]
This issue should be fixed in MSAL Angular v1, please let us know if not.
