### ISSUE TITLE
Support Instance Aware in Msal Js 

### ISSUE THREAD

**Issue by DarylThayil** [AzureAD/microsoft-authentication-library-for-js#887]
Instance aware is supported by msal js
* If bounced to another cloud instance, this authority is returned in the response so the subsequent requests can be made to this new authority by developers.
This will reduce latency and cogs.

**Comment by DarylThayil** [comment]
@sameerag  can you update status here?

**Comment by sameerag** [comment]
#969 closes this issue. #968 is a pre-requisite for the same.

**Comment by sameerag** [comment]
Closing this as the PRs #968 and #969 are now merged into dev.
