### ISSUE TITLE
Bug in call to insertAdjacentHTML('beforeEnd', ...)

### ISSUE THREAD

**Issue by Molibar** [AzureAD/microsoft-authentication-library-for-js#89]
Bug in call to insertAdjacentHTML('beforeEnd', ...) in UserAgentApplication.ts.

The specifications states that it should be "beforeend", not "beforeEnd":
https://www.w3.org/TR/2011/WD-html5-20110525/apis-in-html-documents.html

This broke the TypeScript pre-processing for me since InsertPosition in lib.es6.d.ts in the typescript node-package is defined as:
type InsertPosition = "beforebegin" | "afterbegin" | "beforeend" | "afterend";

Pull request coming.
Feel free to add a CONTRIBUTING.MD if I'm out of line.

**Comment by rohitnarula7176** [comment]
@Molibar Thank you for your contribution. I have merged your pull request. Closing this issue,
