### ISSUE TITLE
Full End To End Testing Framework Exists For Msal js

### ISSUE THREAD

**Issue by DarylThayil** [AzureAD/microsoft-authentication-library-for-js#896]
We have the framework and infrastructure to write and run end to end tests that provide value that increase velocity of development and deployment

**Comment by sameerag** [comment]
We are addressing this with the integration testing activity in this quarter.

**Comment by pkanher617** [comment]
Started work on updating this framework. 
- Made the decision to use puppeteer as the framework of choice. 
- @sameerag and I will be working on writing a comprehensive list of test cases to implement
- Hope to shortly push up a branch with new framework.

**Comment by pkanher617** [comment]
e2e tests and frameworks added to samples folders.
