### ISSUE TITLE
Support Login Silent If Feasible

### ISSUE THREAD

**Issue by DarylThayil** [AzureAD/microsoft-authentication-library-for-js#900]
Explore the feasibility of supporting login silent because of the potential uses cases it can help solve for customers 

@sameerag to fill in requirements

Feature / top level api that would allow users who are already logged into to ESTS to silently get their id token.  This is especially useful if the user is logged in but msal is not aware of it.

**Comment by sameerag** [comment]
We are supporting one version of this with #1166; 
The requirement that an application needs a hint to continue their session with AAD still remains intact w.r.t `msal js`; This conclusion is reached after a wide internal discussion, there are some special conditions where we do support an existing session acquired without `msal js` but to do so, the user would need to pass either a `login_hint` or `sid` to our library.

Closing this issue.

**Comment by zamzowd** [comment]
@sameerag Could you elaborate on what brought the team to the conclusion that a silent check for an existing session from the authority without any hint should not be supported?

The obvious use case is for Single Sign On:  If a user logs in from Application A, and then navigates to Application B, we'd like to be able to have Application B identify and use the existing authentication session without needing anything extra from the user.

**Comment by jasonnutter** [comment]
@zamzowd One reason is that if the user has multiple active AAD sessions (e.g. work account and personal account), the login hint is needed to disambiguate between those session.
