### ISSUE TITLE
Create an Angular 6+ sample using Msal Core

### ISSUE THREAD

**Issue by DarylThayil** [AzureAD/microsoft-authentication-library-for-js#901]
Because we have not been able to ship msal-angular in the time frame we wanted to, lets write a sample with Angular using Msal core showing developers how to use it in lieu of msal angular GA

**Comment by JackEdwards** [comment]
Is there any update on this? I'm unsure whether to try and use msal-core or msal-angular in my Angular 8 application.

**Comment by jasonnutter** [comment]
@JackEdwards Unfortunately, not yet. I have worked with customers who have `@azure/msal-angular` working with their Angular 8 application by installing `rxjs-compat` (and potentially other changes, depending on your setup).

**Comment by jmckennon** [comment]
Closing this issue, as it's been some time and I'm assuming the issue has been resolved. Feel free to open a new issue if you have further questions.

**Comment by jasonnutter** [comment]
@jmckennon I'm going to reopen, this isn't done yet, want to track as part of the Angular release.

**Comment by jasonnutter** [comment]
New samples are available:

- https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev-angular-1.0/samples/
- https://github.com/Azure-Samples/active-directory-javascript-singlepageapp-angular
