### ISSUE TITLE
Does not follow reject Promise calling acquireTokenSilent  if in Iframe

### ISSUE THREAD

**Issue by binaryjam** [AzureAD/microsoft-authentication-library-for-js#902]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [X ] Chrome version Version 76.0.3809.87 (Official Build) (64-bit)
- [ ] Firefox version XX
- [ ] IE version XX
- [X ] Edge version DevEdge 77.0.230.2 (Official build) dev (64-bit)
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 1.1.1

</code></pre>

## Current behavior

When making a call to msal.acquireTokenSilent,   if the page is embedded in an Iframe it does not work and neither does it return an error.

## Expected behavior

Now I know that you do not want to support IFRAMEs in this library from earlier tickets, but when this is called it needs to obey the promise pattern and either succeed or fail.

In this case it should return an error, preferably with a new error code to say we do not support iframes as part of the promise.

In the UserAgentApplication.ts the decorator resolveTokenOnlyIfOutOfIframe
checks if in Iframe and returns a new promise,  but does nothing with that promise subsequently,    if not in an iframe a differnt promise is called and resolves or rejects correctly.
That promise needs to be rejected with an iframe error warning please.

## Minimal reproduction of the problem with instructions

If you take the  QuickStart Code and make that work stand alone,   then embed that page inside an Iframe in another Website (pref not both localhost, I have not tried on localhost or same websites so this is how I set it up).     you can actually login it will popup the Dialog box, but it will not do anything.

**Comment by pkanher617** [comment]
@binaryjam We are currently working on updating the iframe logic to support msal.js within iframes. @sameerag Can you give more information here?

**Comment by DarylThayil** [comment]
I am into this suggestion, I wonder if this should be a breaking change or not 
I don't think it is ....

**Comment by sameerag** [comment]
I asked @binaryjam to open this. If there is a way we can send an error with our current behavior if a token is not resolved in an iframe, that can be at least informative. What I need to investigate is if this can be achieved today and the redundancy of the same once we lift the condition in MSAL.

**Comment by DarylThayil** [comment]
https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/909
@binaryjam  / @sameerag  please review

**Comment by sameerag** [comment]
Ah! I see @DarylThayil, This makes sense. I was more trying to find a condition at resolution. This sounds good.

**Comment by sameerag** [comment]
@binaryjam Can you also please test #909 in your environment to verify?

**Comment by binaryjam** [comment]
Sure, will be Monday though

**Comment by DarylThayil** [comment]
we believe this will be solved in #899, unfortunately my pr does not take into account the full scenario, and we believe removing the iframe in iframe restriction will. closing  this ticket
