### ISSUE TITLE
Msal Js Supports Sub Error Codes in CA error cases 

### ISSUE THREAD

**Issue by DarylThayil** [AzureAD/microsoft-authentication-library-for-js#903]
This addresses office blockers:

https://identitydivision.visualstudio.com/Internal%20Partner%20Requests/_workitems/edit/441332
https://identitydivision.visualstudio.com/Internal%20Partner%20Requests/_workitems/edit/441333

right now apps that make a web service call, but get blocked by CA policy, are not given additional context about the type of policy that was applied. Specifically, if it is an easy policy to remediate, or hard. An example of a hard policy would be a block based on location.
Office has asked for this capability to drive a better user experience, only prompting a user to step-up when policy evaluation is easy.

ESTS will return sub-error codes to provide this information. Work is also needed in ADAL and MSAL to expose error codes to apps.

sub error codes:
“message_only” -> this translates to Domain Joined requirement, or Block.

“additional_action” -> This translates to Device not compliant, application not an approved app, broker not installed, WPJ required.

“basic_action” -> This is MFA required or some external challenge, like TOU.

**Comment by jmckennon** [comment]
update: closing this ticket as sub-error codes are not currently supported for the implicit flow by ESTS. the sub-error codes feature will exist in our implementation of the auth-code flow on #1000
