### ISSUE TITLE
[DOC-FEATURE-REQUEST] Adding a JSFiddle to the ReadMe for quick testing

### ISSUE THREAD

**Issue by FrankHu-MSFT** [AzureAD/microsoft-authentication-library-for-js#908]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X ] Documentation issue or request
[X ] Other... Please describe: Feedback
</code></pre>

## Browser: 
- [x] N/A
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: X.Y.Z

</code></pre>

Summary:

It might be useful to add a JSFiddle, so that people have a boiler plate ready to go. That way they can easily run and test and then move the code they need into their existing code. See my JSFIddle here : 
https://jsfiddle.net/frhu123/pukctxd5/27/

if you have anymore questions feel free to ping me at FRHU.

**Comment by DarylThayil** [comment]
@FrankHu-MSFT  have you seen the samples we have in the libs?

/libs/msal-core/samples

The AAD scenario requires a server that accepts redirects to work, I think this would be hard to achieve in a fiddle.

This is also a little dangerous throwing your client id in a public fiddle

closing, but feel free to ping me if you think I am mistaken!

**Comment by FrankHu-MSFT** [comment]
I have seen the samples. if you don't think there's a good way to do it with JSFiddle I understand. I think something like that would be very convenient since it takes some time to setup an environment to get the samples up and running and jsfiddle is very very frictionless. (Our team uses it) Also the client id is fake. Thanks though, closing out issue.
