### ISSUE TITLE
Acquire Auth Token using Client Id AND Secret

### ISSUE THREAD

**Issue by tanmayghosh2507** [AzureAD/microsoft-authentication-library-for-js#911]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Library version

<pre><code>
Library version: 1.1.1

</code></pre>

## Current behavior

I'm currently using acquireTokenWithClientCredentials method from adal-node library for js to generate Bearer token using client Id and secret. Since it follows callback and we want to implement our code using async-await (Promises) pattern, we want to move to msal package. But I see the token generation feature exists only for native clients, which just require client ID.

## Expected behavior

Ability to generate auth bearer token using client Id and secret, similar to 'acquireTokenWithClientCredentials' in 'adal-node' library (https://www.npmjs.com/package/adal-node)

**Comment by jasonnutter** [comment]
A Node.js wrapper for MSAL.js is [on our roadmap](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#roadmap), but currently has no ETA.

Closing as nothing actionable for now.
