### ISSUE TITLE
Manually closing an access token request popup prevents subsequent silent requests from completing

### ISSUE THREAD

**Issue by anthony-nash** [AzureAD/microsoft-authentication-library-for-js#932]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [x] Firefox version 68.0.2
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 1.1.3

</code></pre>

## Current behavior

The usage instructions for obtaining an access token when using the popup flow say to first call `acquireTokenSilent` and if that fails with an error of type `InteractionRequiredAuthError` then start an interactive request with `acquireTokenPopup`.

A problem arises if the user chooses to close the popup - any subsequent attempts to obtain an access token using `acquireTokenSilent` will fail to ever complete and so `acquireTokenPopup` will never be called again. This is due to how the popup being closed is dealt with - it calls the passed in reject function without cleaning up the active renewal along with its associated callback and promises. Since `acquireTokenSilent` checks `window.activeRenewals` and sees that there is a renewal active for the requested scope, it then simply calls `registerCallback` to add another promise to `window.promiseMappedToRenewStates` which will never be run.

## Expected behavior

Upon the user closing the popup for `acquireTokenPopup`, the associated entries in `window.activeRenewals`, `window.callbackMappedToRenewStates` and `window.promiseMappedToRenewStates` should be cleaned up. This will allow later calls to `acquireTokenSilent` to complete and execute `acquireTokenPopup` to display the popup again.

## Minimal reproduction of the problem with instructions

1. Make a request for an access token which has expired by making a call to `acquireTokenSilent` with a fallback to `acquireTokenPopup` when `acquireTokenSilent` fails with an error of type `InteractionRequiredAuthError`.
2. Close the resulting popup manually.
3. Make another request for the access token and notice that the popup fails to display.
4. Inspect `window.activeRenewals`, `window.callbackMappedToRenewStates` and `window.promiseMappedToRenewStates` which will reveal entries for the requested scope.
5. Note that the number of entries in `window.promiseMappedToRenewStates` increments every time you make another request for the access token.

**Comment by DarylThayil** [comment]
@anthony-nash  thanks for sharing, will work to investigate solution to fix this problem and put it in the right milestone so you can track for release

**Comment by sameerag** [comment]
This may be potentially unblocked of #1042 is merged. Adding to track this here.

**Comment by jmckennon** [comment]
This is fixed now is `msal@1.2.0-beta.5`, closing.
