### ISSUE TITLE
Authorization Code flow with PKCE support

### ISSUE THREAD

**Issue by kstro21** [AzureAD/microsoft-authentication-library-for-js#944]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Library version

<pre><code>
Library version: 1.1.3

</code></pre>

## Current behavior
I can not find any reference if this is currently implemented/supported. I'm trying to use this library to authenticate with AAD B2C but I would like to use _Authorization Code flow with PKCE support_. I thought that passing the query parameters `response_type`, `code_challenge_method` and `code_challenge` would be enough but I can see it work.

## Expected behavior
Can someone, if possible, provide a minimal example of this library authenticating with AAD B2C using _Authorization Code flow with PKCE support_?

**Comment by DarylThayil** [comment]
Unfortunately msal js does not yet support the Auth Code Flow.  We do have plans to support it as some point soon and are in the middle of design  / exploration. The work is not yet scheduled

**Comment by DarylThayil** [comment]
We are taking this on in Q2  ( Oct - Dec ) of 2019.  Tracked in #1000 
Closing this ticket to be tracked in master ticket
