### ISSUE TITLE
FAQ Contradiction - Does MSAL support v1 or not?

### ISSUE THREAD

**Issue by BobGerman** [AzureAD/microsoft-authentication-library-for-js#949]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [x] Edge version 78.0.249.1 (Edgium)(Official build) dev (64-bit)
- [ ] Safari version XX

## Library version

<pre><code>
Library version: X.Y.Z

</code></pre>

## Current behavior

FAQ page contradicts itself

## Expected behavior

FAQ page is clear and easy to understand

## Minimal reproduction of the problem with instructions

This FAQ page: https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/FAQs

The page begins,
> MSAL.js integrates with the Azure AD v2.0 endpoint, whereas ADAL.js integrates with the Azure AD v1.0 endpoint.

Later it says, 
> When getting tokens for V1.0 APIs using MSAL.js, you can request all the static scopes registered on the API by appending .default to the App ID URI of the API as scope. 

Which is it? Does MSAL support v1.0 endpoints or not?
If not, what is the supported way to access v1.0 endpoints given ADAL has been deprecated and EasyAuth still uses it, so there are many apps that need it?

Thanks for clarifying - this is all very confusing! :)

**Comment by sameerag** [comment]
Closing this as this will be addressed with #844.
