### ISSUE TITLE
Where's the Best Place to Report Issues Related to the Portal?

### ISSUE THREAD

**Issue by spottedmahn** [AzureAD/microsoft-authentication-library-for-js#95]
I'm experiencing the following issue but I'm not sure where I should report it.  And advice?  Thanks!

1. I'm getting an error when trying to save my scopes complaining about my reply url
1. The url in the error is not clickable
1. I can't copy the url in error message

![image](https://user-images.githubusercontent.com/14079228/28140969-8e7a7306-6728-11e7-942a-8fb48011507c.png)

**Comment by spottedmahn** [comment]
@SaeedAkhter-MSFT @parakhj looks like there is a port issue. I tried creating a new app and it fails too.

![image](https://user-images.githubusercontent.com/14079228/28141426-803c5e4c-672a-11e7-9ef1-eb956fcd7084.png)

![image](https://user-images.githubusercontent.com/14079228/28141431-86cdf8a6-672a-11e7-8434-504e7037b97f.png)

**Comment by parakhj** [comment]
We are working to resolve the issue - sorry for the delay. Once the issue is resolved, will try to update the notification as well so the link is clickable.

**Comment by spottedmahn** [comment]
@parakhj thanks!

**Comment by danieldobalian** [comment]
To answer the question, StackOverflow posts are a great way to report this kind of thing with tag `azure-active-directory`.

**Comment by parakhj** [comment]
The issue was resolved a little while ago - you shouldn't see that notification anymore.

**Comment by spottedmahn** [comment]
thanks @danieldobalian  and @parakhj
