### ISSUE TITLE
Msal Is Not Defined

### ISSUE THREAD

**Issue by m-sterspace** [AzureAD/microsoft-authentication-library-for-js#950]
## I'm submitting a...

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report  
- [ ] Performance issue
- [ ] Feature request
- [x] Documentation issue or request
- [ ] Other... Please describe:

## Browser:
- [x] Chrome version XX
- [x] Firefox version XX
- [x] IE version XX
- [x] Edge version XX
- [x] Safari version XX

## Library version

<pre><code>
Library version: X.Y.Z

</code></pre>

## Current behavior

When reading "Usage" documentation here: https://github.com/AzureAD/microsoft-authentication-library-for-js

If you just follow it you'll get an "Msal is not defined" error.

## Expected behavior

The Usage section should just note that you need to import Msal first using this line:

    import * as Msal from 'msal';

**Comment by DarylThayil** [comment]
merged thanks for the feedback
