### ISSUE TITLE
Redirect loop/error for AAD names with double byte characters

### ISSUE THREAD

**Issue by Robjam** [AzureAD/microsoft-authentication-library-for-js#953]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version XX
- [x] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [x] Safari version XX

## Library version

`Library version: 1.1.3`

## Current behavior
Logged in user will throw on acquireTokenSilent, then on login will successfully login automatically, then throwing on aqcuireTokenSilent, etc.

Users that are added to an Azure AD directory as a guest with Japanese characters in their names throws an unexpected error after loginRedirect.

## Expected behavior
Users should be able to login with names containing 2 byte characters in them.

## Minimal reproduction of the problem with instructions
change guest username to 鈴木イチロー and try to login.

Can provide a minimal repro if needed, but a `userAgentApplication.acquireTokenSilent` wrapped in a try catch where the catch forces a `loginRedirect` should trigger this issue.

---

Further checking the response for `getAccount()` before calling `acquireTokenSilent` shows undefined for many of the parameters (data was scrubbed from a working request):
```js
{
  "accountIdentifier": "undefined",
  "homeAccountIdentifier": "{someRandom.accountIdentifier}",
  "userName": "undefined",
  "name": "undefined",
  "idToken": "undefined",
  "idTokenClaims": "undefined",
  "environment": "https://login.microsoftonline.com/{clientId}/v2.0"
}
```

**Comment by negoe** [comment]
@Robjam We have fixed the issue in this version MSAL.js 1.2.0-beta.3. Please try it and let us know if you see any further issues.
