### ISSUE TITLE
[Msal for Angular] Integration with microsoft-graph-client

### ISSUE THREAD

**Issue by snebjorn** [AzureAD/microsoft-authentication-library-for-js#954]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Library version
<pre><code>
Library "@azure/msal-angular": "^0.1.2"
</code></pre>

## Current behavior
Today I have to write this to integrate with the Graph Client

```ts
@Injectable({ providedIn: 'root' })
export class SharePointService {
  private readonly graphClient: Client;

  public constructor(private readonly msalService: MsalService) {
    this.graphClient = Client.init({
      authProvider: async (done) => {
        // Get the token from the auth service
        if (!environment.msalConfig.consentScopes) {
          // tslint:disable-next-line: no-null-keyword
          done('No consentScopes', null);

          return;
        }

        const token = await this.msalService
          .acquireTokenSilent(environment.msalConfig.consentScopes)
          .catch((reason) => {
            // tslint:disable-next-line: no-null-keyword
            done(reason, null);
          });

        if (token) {
          done(undefined, token);
        } else {
          // tslint:disable-next-line: no-null-keyword
          done('Could not get an access token', null);
        }
      },
    });
  }
}
```

## Expected behavior
According to https://www.npmjs.com/package/@microsoft/microsoft-graph-client#creating-an-instance-of-implicitmsalauthenticationprovider-in-browser-environment there's an easier way. Using the `ImplicitMSALAuthenticationProvider`.

So I wish to do this:

```ts
@Injectable({ providedIn: 'root' })
export class SharePointService {
  private readonly graphClient: Client;

  public constructor(private readonly msalService: MsalService) {
    this.graphClient = Client.initWithMiddleware(this.msalService.getMiddelware());
  }
}
```

Or something similar.

If there already exist an easier way. I apologize, I wasn't able to find it in the docs.

According to this example from https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-angular#2-secure-the-routes-in-your-application
```ts
{ path: 'myProfile' ,component: MsGraphComponent, canActivate : [MsalGuard] },
```
It hints at that this integration is super easy and in the `MsGraphComponent` the Client is already setup and user logged in. 

That is not my experience :(

**Comment by jasonnutter** [comment]
Closing, as nothing actionable at this time.
