### ISSUE TITLE
microsoft CDN does not work as stated in docs

### ISSUE THREAD

**Issue by ritmos** [AzureAD/microsoft-authentication-library-for-js#957]
In docs it states msal.js can be obtained through a CDN

https://secure.aadcdn.microsoftonline-p.com/lib/VERSION/js/msal.min.js

The thing is the following url does not work as expected

https://secure.aadcdn.microsoftonline-p.com/lib/1.1.3/js/msal.min.js

**Comment by ritmos** [comment]
The url is in this file
https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/README.md

**Comment by ispysoftware** [comment]
20 days and the CDN is still not working - Imagine if you were relying on the CDN to work for people to sign into your website! It's not really filling me with confidence.

**Comment by pkanher617** [comment]
@keystroke @ispysoftware Sorry for the delay. We had some issues with the CDN upload process. We have mostly rectified them, and the new files will be available here:
https://alcdn.msftauth.net/lib/1.1.3/js/msal.js
https://alcdn.msftauth.net/lib/1.1.3/js/msal.min.js
https://alcdn.msauth.net/lib/1.1.3/js/msal.js

**Comment by keystroke** [comment]
@pkanher617 Thanks! The 1.1.3 link isn't working for me yet but as you say should be available shortly. For the new links, what is the difference between using the "msauth" and "msftauth" endpoints? Is one intended for internal consumption only? Or just redundant endpoints?

**Comment by DarylThayil** [comment]
This should be completed, @keystroke  can you check again?
@pkanher617  to add context on the endpoint differences

**Comment by keystroke** [comment]
@DarylThayil Thanks! Verified I can access both endpoints for the CDN. Gave my app a spin and no explosions so looks like things are still working fine ;)

**Comment by jasonnutter** [comment]
I'll keep this open until we get the README updated.

**Comment by jasonnutter** [comment]
@negoe FYI

**Comment by sameerag** [comment]
Closing this as the README is now merged to dev.
