### ISSUE TITLE
AADSTS50199: token renewal doesn't work after a few hours on Edge canary

### ISSUE THREAD

**Issue by jepetty** [AzureAD/microsoft-authentication-library-for-js#958]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [x] Edge version 78.0.249.1
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 1.1.3

</code></pre>

## Current behavior

`acquireTokenSilent` fails after a number of hours of unuse (i.e. if I haven't used the application overnight).

## Expected behavior

Once I've logged in, I should continue to be able to use `acquireTokenSilent` to use a refresh token and get a new access token. I've verified this behavior is seen on Chrome version 78.0.3895.0

## Minimal reproduction of the problem with instructions
Including code snippets with error messages for completeness.

I set up my `UserAgentApplication` with a fairly standard configuration:
```typescript
const configuration: Msal.Configuration = {
    auth: {
        redirectUri: chrome.extension.getURL('login_return.html'),
        clientId: applicationConfig.clientId,
        authority: applicationConfig.authority,
        validateAuthority: true,
        navigateToLoginRequestUrl: true,
    },
    cache: {
        cacheLocation: 'localStorage',
    }
};

const userAgentApplication = new Msal.UserAgentApplication(configuration);
```
Then I first get a token with:
```typescript
const tokenRequest: Msal.AuthenticationParameters = {
        scopes: [ 'https://microsoft.onmicrosoft.com/RichCodeNav/read_public' ]
};
try {
        await userAgentApplication.loginPopup(tokenRequest);
        await userAgentApplication.acquireTokenSilent(tokenRequest);
    } catch (err) {
        try {
            await userAgentApplication.acquireTokenPopup(tokenRequest);
        } catch (err) {
            return;
        }
    }
```
which works, as I can see id tokens and access tokens in local storage. Renewal seems to be working (for a while) - I've set `tokenRenewalOffsetSeconds` to be 1000 to test, and haven't hit any problems. Then, after not using the application for a few hours, attempting to fetch a token using 
```typescript
await userAgentApplication.acquireTokenSilent(tokenRequest);
```
results in the following log messages and error:
<pre><code>
Wed, 28 Aug 2019 15:43:42 GMT:1.1.3-Info Add msal frame to document:msalRenewFramehttps://microsoft.onmicrosoft.com/richcodenav/read_public
Wed, 28 Aug 2019 15:43:42 GMT:1.1.3-Info LoadFrame: msalRenewFramehttps://microsoft.onmicrosoft.com/richcodenav/read_public
Wed, 28 Aug 2019 15:43:43 GMT:1.1.3-Info Add msal frame to document:msalRenewFramehttps://microsoft.onmicrosoft.com/richcodenav/read_public
Wed, 28 Aug 2019 15:43:47 GMT:1.1.3-Info Returned from redirect url
Wed, 28 Aug 2019 15:43:47 GMT:1.1.3-Info Processing the callback from redirect response
Wed, 28 Aug 2019 15:43:47 GMT:1.1.3-Info State status:true; Request type:RENEW_TOKEN
popup.ts:28 Unable to get logged in user:  InteractionRequiredAuthError: AADSTS50199: Conditions to show CMSI interrupt are met.
Trace ID: 797509dd-e2a8-4b59-a034-eeb3906c0800
Correlation ID: 06451745-8778-4191-b975-1feaaa062d68
Timestamp: 2019-08-28 15:43:45Z
    at InteractionRequiredAuthError.AuthError [as constructor] (chrome-extension://dckkmoeekhppkjieeeijihmepmfgeoll/js/vendor.js:180485:28)
    at InteractionRequiredAuthError.ServerError [as constructor] (chrome-extension://dckkmoeekhppkjieeeijihmepmfgeoll/js/vendor.js:180950:28)
    at new InteractionRequiredAuthError (chrome-extension://dckkmoeekhppkjieeeijihmepmfgeoll/js/vendor.js:180889:28)
    at UserAgentApplication.push../node_modules/msal/lib-es6/UserAgentApplication.js.UserAgentApplication.saveTokenFromHash (chrome-extension://dckkmoeekhppkjieeeijihmepmfgeoll/js/vendor.js:179753:25)
    at UserAgentApplication.push../node_modules/msal/lib-es6/UserAgentApplication.js.UserAgentApplication.processCallBack (chrome-extension://dckkmoeekhppkjieeeijihmepmfgeoll/js/vendor.js:179287:29)
    at UserAgentApplication.push../node_modules/msal/lib-es6/UserAgentApplication.js.UserAgentApplication.handleAuthenticationResponse (chrome-extension://dckkmoeekhppkjieeeijihmepmfgeoll/js/vendor.js:179389:14)
    at new UserAgentApplication (chrome-extension://dckkmoeekhppkjieeeijihmepmfgeoll/js/vendor.js:178530:22)
    at Object../src/auth.ts (chrome-extension://dckkmoeekhppkjieeeijihmepmfgeoll/js/vendor.js:234848:30)
    at __webpack_require__ (chrome-extension://dckkmoeekhppkjieeeijihmepmfgeoll/js/login_return.js:79:30)
    at Object../src/login_return.ts (chrome-extension://dckkmoeekhppkjieeeijihmepmfgeoll/js/login_return.js:174:14)
</code></pre>

That error code is nowhere in documentation (which is another place for thing that would be helpful). Any ideas? Thanks!

**Comment by DarylThayil** [comment]
I would expect so! interesting.  @sameerag  @pkanher617  have you seen this before? Any thoughts?
If not lets get a call set up @jepetty  to debug together!

**Comment by jepetty** [comment]
Thank you, I appreciate the help! Feel free to ping me (alias jepetty) as well to set up a meeting or if you need any more information. :)

**Comment by jepetty** [comment]
Ping... any updates on this? Shall we set up some time to chat?

**Comment by jasonnutter** [comment]
@jepetty Do you have a functional sample repro you can share? I've seen issues like this recently (e.g. #941), seems like this might be similar. Feel free to share on email/teams. Thanks!

**Comment by jepetty** [comment]
I agree, they do look pretty similar! I sent you an email, happy to help out as much as I can in diagnosing this :) Thanks!

**Comment by jasonnutter** [comment]
Working with @jepetty to improve MSAL usage, but for anyone else who gets the `AADSTS50199: Conditions to show CMSI interrupt are met` error, it is thrown when your app uses a non-https redirect uri (e.g. such as `chrome-extension://`). We'll make sure this gets added to the list of error codes.

**Comment by jasonnutter** [comment]
Another note: this error will not show for Chrome extensions running in Chrome, but will show for Chrome extensions running in non-Chrome browsers such as the new chromium-based Edge. We have opened a ticket internally to get the new Edge whitelisted (MSFTers can ping me on Teams if they want more details on that).

Closing, as no further actionable items at this time.

**Comment by jepetty** [comment]
Thanks for all your help @jasonnutter! You're the bomb!
