### ISSUE TITLE
Missing documentation for AuthenticationParameters

### ISSUE THREAD

**Issue by AndrewCraswell** [AzureAD/microsoft-authentication-library-for-js#964]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

Is there any official documentation for the `AuthenticationParameters` object? I'm writing some team wikis and can't find anything official anywhere... I'm able to find descriptions for some of the values spread widely throughout the docs, like this article about [passing state](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-pass-custom-state-authentication-request), or this [out-of-place doc](https://docs.microsoft.com/bs-latn-ba/azure/active-directory/develop/msal-js-sso#automatically-select-account-on-azure-ad) describing `login_hint` and `domain_hint`, and various docs about scopes. But is there any cohesive document the describes each parameter briefly and provides links to more detailed information when available?

**Comment by AndrewCraswell** [comment]
This is probably close enough to #818 for both to be resolved in tandem.

**Comment by sameerag** [comment]
@AndrewCraswell @negoe is working on documentation for AuthenticationParameters and hints. They are currently in internal review and we will update this ticket with the corresponding documentation links once published.

**Comment by burkeholland** [comment]
Just went through this myself. It looks like the paths are correct in the UserAgentApplication doc, but the HTML preview is still pointing to `classes/_authenticationparameters_html` instead of `modules/_authenticationparameters_.html`.

**Comment by jrmcdona** [comment]
Do we know when this will be on the public docs?   I am trying to convert the ME Control to MSAL based on an ADAL ME Control example and getting quite confused on some stuff!

**Comment by sameerag** [comment]
@jrmcdona We just checked in a docs PR and kicked off a project consolidating all our documentation to be at one place. This effort will reflect in public docs incrementally. Please give us a couple weeks before we close this particular issue.

cc @pkanher617 Please prioritize this issue in the docs effort, I would suggest linking to typedocs in addition to expanding on each parameter in Microsoft public docs.

**Comment by jasonnutter** [comment]
We have reference docs available here: https://azuread.github.io/microsoft-authentication-library-for-js/ref/msal-core/modules/_authenticationparameters_.html

**Comment by jasonnutter** [comment]
Closing, please use the link above to the reference docs (which we will work on improving).
