### ISSUE TITLE
How can I get AAD joined device ID without any form of login?

### ISSUE THREAD

**Issue by benzhi2011** [AzureAD/microsoft-authentication-library-for-js#966]
Is there any JS lib that can return the AAD joined device id or just id? I have a daemon server side .net core app that can lookup our tenant to see if the device is ours and the name is on a list.

The device is AAD joined, but in my case the user that log on the PC is not really masters, I just have to validate from my web app if the request is made from our AAD joined device. The login user could be local admin account without password.

Please help

**Comment by jasonnutter** [comment]
@benzhi2011 Apologies for the delay in responding. By definition, in order to be AAD joined, a device must be signed into an AAD account. See our docs more information: https://docs.microsoft.com/en-us/azure/active-directory/devices/concept-azure-ad-join

Closing as no further action.
