### ISSUE TITLE
Token is broken if Name in token contains no UTF-8 characters

### ISSUE THREAD

**Issue by dluque92** [AzureAD/microsoft-authentication-library-for-js#971]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [X] Chrome version 76.0.3809.132
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 1.1.3

</code></pre>

## Current behavior

I receive a null token and this AuthError
![ClientAuthError](https://user-images.githubusercontent.com/12599684/64350274-b65e8e80-cff8-11e9-9894-0edbdfc12315.jpg)

The problem is because of this user name:
![CharacterNoSupported](https://user-images.githubusercontent.com/12599684/64350328-c7a79b00-cff8-11e9-8f21-0b0c756d93a8.png)

That contains a non-supported character.

After change this character, everything works fine.

## Expected behavior

Allow this kind of characters or don't be able to send it 

## Minimal reproduction of the problem with instructions

Add or edit an user in Azure with this Name
![CharacterNoSupported](https://user-images.githubusercontent.com/12599684/64350502-09384600-cff9-11e9-9a65-38ff608f22fa.png)

**Comment by jasonnutter** [comment]
Looks like this is at least similar to #953.

**Comment by negoe** [comment]
@dluque92 We have fixed the issue in this version MSAL.js 1.2.0-beta.3. Please try it and let us know if you see any further issues.
