### ISSUE TITLE
Multiple instances of MSAL

### ISSUE THREAD

**Issue by shane7218** [AzureAD/microsoft-authentication-library-for-js#974]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [X] Chrome version ALL
- [X] Firefox version ALL
- [X] IE version ALL
- [X] Edge version ALL
- [X] Safari version ALL

## Library version

<pre><code>
Library version: All Versions

</code></pre>

## Current behavior

Currently MSAL creates a global instance in the window. As web applications move towards a more Micro Frontend architecture style where multiple parts of a page are essentially different independent applications, each with their own authentication requirements, this presents problems. With the current implementation of MSAL, it is not currently possible to have more then one MSAL  instance. For example when one component of the page which using this architecture is its own app in and of itself, its client ID needs to be different then that of another or that of the host page, and the current implementation does not allow for this.

## Expected behavior

MSAL should be able to create multiple instances on a single page so that Micro Frontend style architectures where multiple independent apps are running on the page are supported. Authentication can then be encapsulated within the applications, and not attached to the global context.

## Minimal reproduction of the problem with instructions

Not Applicable

**Comment by jasonnutter** [comment]
We are working on solving this, assigning to @sameerag who is leading that effort.

**Comment by villasante** [comment]
> We are working on solving this, assigning to @sameerag who is leading that effort.

Do you have a timeline for it?

**Comment by shane7218** [comment]
Absolutely, let me know whatever I can do to help!

**Comment by negoe** [comment]
Hi @shane7218, We have fixed this issue in MSAL JS 1.2.0-beta.3. Please try and let us know if you have any further issues. 

Thanks,
Neha

**Comment by oneillsp96** [comment]
@negoe I'm using the redirect flow, and I need 2 instances of UserAgentApplication, each with a different client Id. As soon as I add the second instance, everything breaks.

 Looking at the PR that claims to fix this, it only seems to be targeting the popup flow. Are there any workarounds?
