### ISSUE TITLE
MSLA support for ionic 4?

### ISSUE THREAD

**Issue by awadeyar** [AzureAD/microsoft-authentication-library-for-js#979]
Hi 
is there any other way using MSAL or ADAL JS for Ionic 4? Any help is appreciated. I am developing a mobile app with Ionic 4 which needs the authentication from Azure AD.

**Comment by jasonnutter** [comment]
@awadeyar Unfortunately, I don't believe our library is compatible with the Ionic framework. Have you tried look into our SDKs for [Objective C](https://github.com/AzureAD/microsoft-authentication-library-for-objc) or [Android](https://github.com/AzureAD/microsoft-authentication-library-for-android)?

**Comment by awadeyar** [comment]
@jasonnutter Thanks
