### ISSUE TITLE
Sporadic invalid_state_error errors

### ISSUE THREAD

**Issue by deregtd** [AzureAD/microsoft-authentication-library-for-js#981]
I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [X] Chrome version XX
- [?] Firefox version XX
- [?] IE version XX
- [X] Edge version XX
- [X] Safari version XX

## Library version

<pre><code>
Library version: 1.1.3

</code></pre>

## Current behavior

We have tried using localStorage and sessionStorage options as well as navigateToLoginRequestUrl: false (and removing the parameter) and storeAuthStateInCookie: true (and false), but, sporadically when users come to login for the first time in a little while, they get an invalid_state_error on first login attempt, then a second login works fine.  The two state values are definitely valid GUIDs, but it's pulling some old state from somewhere and then thinking that's the right one.

I assume there's some race condition at either startup or login here, so looking for suggestions about what expectations are around logging in, what to do at startup, etc.

## Expected behavior

Logins work normally.

## Minimal reproduction of the problem with instructions

Please contact me internally via Teams for what sometimes works as a repro.

**Comment by juteasl** [comment]
Is there a status update on this issue?  It's not had a follow up in 7 days, we are waiting on this fix too.

**Comment by AndrewCraswell** [comment]
This sounds very similar to a bug I'm trying to repro on a few of our applications too. Users (often on Edge) are reporting that on the first login attempt it seems successful, they're redirected to the application, then immediately directed back to login. This loop only occurs once before everything works fine. I felt like it was likely only happening when a token expired.

Are you able to repro the issue consistently? I was trying to test the IdToken expiration theory, but without being able to force a refresh of IdToken (like how you can offset the expiration time for Access Tokens) this is difficult to prove out consistently.

**Comment by deregtd** [comment]
We tried the latest version and unfortunately still got invalid_state_error calls.

One thing I noticed in one of the error paths though is a second telemetry point trying to login before it redirects away.  My current theory is that the login code is actually calling .loginRedirect TWICE in short succession, and so it's getting out of sync between what state it persists and what actually redirects away.  I just tried putting a wrapper around our loginRedirect call to make sure that it can only login once every 10 seconds, and we'll see if that makes the issue go away.  You may want to check your code for this sort of issue as well.

**Comment by sameerag** [comment]
@deregtd Does the latest version here refer to msal 1.1.3 or the dev beta?

**Comment by deregtd** [comment]
We're using 1.2.0-beta.0

**Comment by sameerag** [comment]
@deregtd Can your team please try `msal@1.2.0`? All cache issues are mostly resolved with this release and this issue should no longer be seen. Please let us know your test results and I will reopen the ticket as needed. We are fairly confident that this should not be an issue anymore.
