### ISSUE TITLE
polling interval set to 1ms

### ISSUE THREAD

**Issue by pbalzer** [AzureAD/microsoft-authentication-library-for-js#984]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ x] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ x] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 1.1.3

</code></pre>

## Current behavior
The polling loop waiting for the popup window is cycling with an interval of 1ms, causing Chrome to freeze in some situations because of overload.

## Expected behavior
300ms cycle time should be sufficient.

**Comment by jasonnutter** [comment]
We have planned fixes to the way we track popups and iframes, and we'll make sure this gets addressed as part of that. Thanks for the info!

**Comment by himadrinath** [comment]
@pbalzer when i try to login in my pwa application on mobile. popup window on chrome don't do any thing just stopped and some time it open the login page and after submitting the credential if i click signin its not work. if i only wait for few secs and then click to login its works but not even every time. 

this is causing the problem u mention 

![login_hungup](https://user-images.githubusercontent.com/12247490/65219470-3e06cb80-dad6-11e9-986e-b0bde0f23ab8.gif)

**Comment by negoe** [comment]
Hi @pbalzer,  We have fixed this issue in MSAL JS 1.2.0-beta.3. Please try and let us know if you have any further issues.

Thanks,
Neha
