### ISSUE TITLE
Unicode string(japanese-strting) use atob is getting error .

### ISSUE THREAD

**Issue by nakawankuma** [AzureAD/microsoft-authentication-library-for-js#985]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [x] Chrome version 76.0.3809.132
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 1.1.3

</code></pre>

## Current behavior

atob( "eyJ2ZXIiOiIxLjAiLCJzdWIiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFPLTV0Yy13SlhGREt3VWFqNkc4NFJzIiwibmFtZSI6IuWNmuS_iiDkuK0iLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJuYWthQHdhbmt1bWEuY29tIiwib2lkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLWVhOTctNmQyNjY5NWIxODhlIiwidGlkIjoiOTE4ODA0MGQtNmM2Ny00YzViLWIxMTItMzZhMzA0YjY2ZGFkIiwiaG9tZV9vaWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtZWE5Ny02ZDI2Njk1YjE4OGUiLCJ1aWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtZWE5Ny02ZDI2Njk1YjE4OGUiLCJ1dGlkIjoiOTE4ODA0MGQtNmM2Ny00YzViLWIxMTItMzZhMzA0YjY2ZGFkIn0");
I get exception to :
Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

## Expected behavior

Non Error decode.

>certutil -decode infile outfile
It is safe output.

## Minimal reproduction of the problem with instructions

Signin Japanese DisplayName account.
myMSALObj.loginPopup(requestObj)

**Comment by nakawankuma** [comment]
when other library that js-base64 I got correctry answer.
var Base64 = require('js-base64').Base64;


var a=Base64.decode('eyJ2ZXIiOiIxLjAiLCJzdWIiOiJBQUFBQUFBQUFBQUFBQUFBQUFBQUFPLTV0Yy13SlhGREt3VWFqNkc4NFJzIiwibmFtZSI6IuWNmuS_iiDkuK0iLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJuYWthQHdhbmt1bWEuY29tIiwib2lkIjoiMDAwMDAwMDAtMDAwMC0wMDAwLWVhOTctNmQyNjY5NWIxODhlIiwidGlkIjoiOTE4ODA0MGQtNmM2Ny00YzViLWIxMTItMzZhMzA0YjY2ZGFkIiwiaG9tZV9vaWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtZWE5Ny02ZDI2Njk1YjE4OGUiLCJ1aWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtZWE5Ny02ZDI2Njk1YjE4OGUiLCJ1dGlkIjoiOTE4ODA0MGQtNmM2Ny00YzViLWIxMTItMzZhMzA0YjY2ZGFkIn0');
console.log(a);

C:\Users\naka\Downloads\jjj>node a
{"ver":"1.0","sub":"AAAAAAAAAAAAAAAAAAAAAO-5tc-wJXFDKwUaj6G84Rs","name":"博俊 中","preferred_username":"naka@wankuma.com",   ---snip---}

**Comment by nakawankuma** [comment]
utils\CryptoUtils.ts\base64Decode

    static base64Decode(input: string): string {
        return decodeURIComponent(**atob**(input).split("").map(function(c) {
            return "%" + ("00" + c.charCodeAt(0).toString(16)).slice(-2);
        }).join(""));
    }

**Comment by jasonnutter** [comment]
@nakawankuma Thanks for the info and the sample reproduction case. We used to use `js-base64`, but decided to remove it due to compatibility issues, detailed in #746. We'll revisit this, and follow up here. Thanks!
