### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by dluc** [AzureAD/microsoft-authentication-library-for-js#989]
The library documentation is really really scarce and it's super hard understanding what to do with it.

1. How to retrieve an Identity Token?
2. How does the cache work?
3. How to avoid page reloads?

Also, complete examples are much more useful than incomplete snippets of code leaving too much to imagination. You should consider adding a samples folder, with subfolders containing working applications.

Also consider these major contexts:

1. ReactJs
2. AngularJs
3. React Native

Thanks

**Comment by sameerag** [comment]
@dluc We are working on MSAL JS documentation for some of these questions you asked, hopefully with the next release we will make some strides. Adding these questions to the planning doc to ensure we cover them in one form or the other. 

Regarding samples, there is a PR #987 which is consolidating all samples in the root folder of the repository. Once merged, we will focus on fine tuning the samples as we go.

For React, currently we have a sample that demonstrates MSAL JS integration. @DarylThayil Can you please comment on Angular JS and React Native?

**Comment by jasonnutter** [comment]
- **React**: As @sameerag noted, we have a React sample available [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-core/samples/react-sample-app). We may provide a wrapper in the future, but that work is not scheduled.
- **React Native**: We currently do not support React Native due to lack of support for things like `localStorage`. We do have [Android](https://github.com/AzureAD/microsoft-authentication-library-for-android) and [objective-c](https://github.com/AzureAD/microsoft-authentication-library-for-objc) libraries that we recommend for native mobile apps.
- **Angular**: We have two Angular wrappers, `msal-angular` (4/5) and `msal-angularjs` (older angular). We'll be working to update `msal-angular` to support the current version of `msal` core and newer versions of Angular soon.

**Comment by dluc** [comment]
Thanks, really appreciate the update and looking forward to see the new additions. (fixed typo in my original post 'library'=>'library documentation').

I've been looking at the React sample, here's some comments in case you could extend it:
1. Would be nice to have a Typescript example, ie to better understand the variable types involved. This would help with the library API, e.g. how to find identity tokens.
2. The example encapsulates in AuthProvide logic that doesn't belong to auth, e.g. readEmail. In real applications this sort of methods is in other classes, who simply need access tokens and id tokens for external API calls. I would suggest to refactor the code, e.g. having a Email class that can invoke MS Graph using the access token provided by AuthProvider. This would be the base for any other class that needs tokens to communicate with external services.

**Comment by jasonnutter** [comment]
@dluc Appreciate the feedback, I agree a Typescript example would be good to have.

To address your other questions:

1. An ID token will be returned after logging in. More info available here: https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-implicit-grant-flow#send-the-sign-in-request
2. Our cache isn't currently documented, as its an implementation detail of the library (you do get to configure options like `localStorage` verse `sessionStorage`). We've had requests to allow apps to [provide their own cache implementations](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/871), which we're considering, however, that work is not planned. We would certainly want to provide more complete documentation if end up opening that up.
3. We are working on changing how we fetch access to address some of the performance problems that come with loading your app in an iframe or popup. Once that is released we will provide guidance to developers on how to take advantage of that.

**Comment by jmckennon** [comment]
Closing this issue, as it's been some time and I'm assuming the issue has been resolved. Feel free to open a new issue if you have further questions.
