### ISSUE TITLE
Working Sample for Angular 7 (msal-angular)

### ISSUE THREAD

**Issue by rahulrastogi-git** [AzureAD/microsoft-authentication-library-for-js#990]
Team,
I am trying to implement msal-angular in my project, after so many attempts I still have question around best way to implement.

1. Best way to redirect to azure login page, without showing login button on Navbar
2. After login how to take user to first page of application, login success gives event but case where token is in cache, which event will be generated, or is there any better way of doing it.
3. At the minimum should we expect Index.html will be loaded 3 times, initial load, redirect load and iframe load.

Lack of examples and documentation is making very difficult adoption.

npm documentation says dont use non-public methods, but reading git issues, developers are using acquiretokensilent.

hope someone will advise on recommended practice.

Thanks

**Comment by jasonnutter** [comment]
1. If you need to redirect someone to the login screen, you can use `loginPopup` or `loginRediect`, depending on if you want a popup or full page redirect. I'm not sure exactly what you mean by "without showing login button", but you can call these methods whenever your application needs (I would probably recommend waiting for user input, but it is not required).
2. After login, MSAL will redirect your user back to the redirect url you provide (which defaults to the page the user is currently on). When login is successful, `msal:loginSuccess` will be broadcast, and when acquiring a token succeeds, the `msal:acquireTokenSuccess` event will be broadcast.
3. Correct, there may be 3 page loads, once for initial load, once after coming back from the redirect, and once inside an iframe when acquiring a new token. We are currently working on optimizing this in `msal` core, and we are planning on updating `msal-angular` to use `msal` 1.x (which will include these changes) later this year.

**Examples:** There is currently a simple example application [available here](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-angular/samples/MSALAngularDemoApp).  We'll be updating and improving our samples and documentation over the coming months.

**acquireTokenSilent:** `acquireTokenSilent` is a public method, however, we recommend using the `MsalGuard` and subscribing to the Angular events such as `msal:acquireTokenSuccess` and `msal:loginSuccess`. 

Let me know if you have any further questions!

**Comment by rahulrastogi-git** [comment]
Thanks for your response Jason.
Based on discussion in other forums i have downgraded my rxjs version to 6.2.2 and installed rxjs-compat 6.2.2 as well, after that it works fine.

Regarding point 1
scenario 1
After typing URL of my application, i want user to show login page, for that should I protect home page route by MsalGuard, or should I call "logindirect" on ngonInit(), what is recommended?

RedirectURI is also pointing to home page.


scenario 2
User close the browser and after few seconds comes back to same url, since token is in cache, how it will be used, assuming I am calling "logindirect" on ngonInit()

Also is there event generated, when token is picked from cache.

Thanks

**Comment by rahulrastogi-git** [comment]
Team, any opinion/suggestion on this.

**Comment by jasonnutter** [comment]
1. Use the guard, which will handle that logic for you.
2. The guard will generate an `msal:loginSuccess` event when it has retrieved a token.

**Comment by rahulrastogi-git** [comment]
on your point 2, I am not getting any event, in case token was picked from cache.

**Comment by rahulrastogi-git** [comment]
I am using @azure/msal-angular 0.1.4 version.

**Comment by rahulrastogi-git** [comment]
Any idea Jason?

**Comment by jasonnutter** [comment]
Ah, so it only broadcasts that event when a new token is acquired, and will not broadcast when retrieving a cached token. Ultimately, this is okay, as the `MsalInterceptor` will add the access token to your outgoing calls for you.

If you want to get the token directly even if its cached, you can use `acquireTokenSilent`, which will fetched the cached token.

**Comment by rahulrastogi-git** [comment]
MsalGuard is on **home**  page, onloginsuccess event i was directing my application to **main** page. since I am not getting onloginsuccess event in case cache, application remains at home, which is just a blank page, thats the issue.

Is there any method to check if there is valid token?
if there is then application can go Main page, if not then go to login page.

**Comment by jasonnutter** [comment]
`getAccount()` will return an object if a user is logged in, and `null` if not. So on your home page you could check if a user is logged in with `getAccount`, and then redirect to the main page if so.

**Comment by rahulrastogi-git** [comment]
I dont see getAccount in msalservice, it seems it is not part of msal-angular.

**Comment by jasonnutter** [comment]
Ah, sorry it's called `getUser()`.

**Comment by jasonnutter** [comment]
@rahulrastogi-git Did using `getUser()` work for you?

**Comment by rahulrastogi-git** [comment]
Hi Jason,
didnt get a chance yet to try, will let you know.

on other note, do you have timeline to upgrade @azure/msal-angular 0.1.4?

Thanks
Rahul

**Comment by jasonnutter** [comment]
@rahulrastogi-git If you are referring to upgrading `@azure/msal-angular` to version v1 of `msal`, we are planning to complete that work this upcoming quarter, so it should be released by the end of the year. We will make an announcement once we have beta releases that developers can try.

**Comment by mayankkalbhor** [comment]
Do we have an Angular 6 code sample with MSAL library available now? https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-angular/samples/MSALAngularDemoApp is not having any samples as of now.

**Comment by jasonnutter** [comment]
New samples for Angular are available:

- https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev-angular-1.0/samples/angular6-sample-app
- https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev-angular-1.0/samples/angular7-sample-app
- https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev-angular-1.0/samples/angular8-sample-app

https://github.com/Azure-Samples/active-directory-javascript-singlepageapp-angular
