### ISSUE TITLE
Provide config option to include id_token in B2C logout requests

### ISSUE THREAD

**Issue by adamstoffel** [AzureAD/microsoft-authentication-library-for-js#996]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Library version

<pre><code>
Library version: 1.0.4

</code></pre>

To provide additional security and avoid CSRF, it is possible to configure Azure AD B2C to require the `id_token_hint` parameter during logout. When this is turned on, logouts via MSAL.js will fail. MSAL should provide a configuration option to include this parameter when initiating log out.

See this docs article under "Secure your logout redirect". https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-reference-oidc#secure-your-logout-redirect

**Comment by sameerag** [comment]
@adamstoffel Thank you for bringing this to our attention. 
@ktsakas Does B2C service support this?  if they do, can we also understand what id_token_hint would be?

**Comment by tknerr** [comment]
Hi @sameerag ,

yes ADB2C in fact supports this, as documented here:
https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-reference-oidc#secure-your-logout-redirect

The `id_token_hint` must refer to the last valid id token that existed prior to logout (i.e. just pass the id token).

Note 1: the `id_token_hint` will only be considered if the login policy in ADB2C explicitly requires the `id_token_hint` to be set:

![image](https://user-images.githubusercontent.com/365744/66206722-37b94780-e6b1-11e9-99af-12a4c16e959b.png)

Note 2: once the policy is configured as above, the `id_token_hint` needs to be passed along with every logout request. If you don't pass it, you will hit an ADB2C error page telling you that it is required.

**Comment by s2ramana** [comment]
Will https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/1802 resolve this issue if we can pass the id_token_hint as part of the logout method?
