### ISSUE TITLE
accountState different in IE and in Chrome

### ISSUE THREAD

**Issue by Danieliverant** [AzureAD/microsoft-authentication-library-for-js#997]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [X ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library version

<pre><code>
Library version: 1.0.1

</code></pre>

## Current behavior

I've added language menu in the Azure login page.

when the user select a language I change the "ui_locales" and the "state" query params in the URL with the locale values.

when the login successful I check the "accountState" parameter from the response and redirect the user to the correct app.

flow as follows:

user switched to Arabic -> change query params to  "ui_locales=ar" and the "state=ar-ae" -> enter username and password and login -> redirect back to the redirect URI (English site) -> check the state and redirect the user to the Arabic site.

**Chrome working fine, in IE "accountState" is still in English (en-gb).**

## Expected behavior

"accountState" should be the same as the query param "state".

## Minimal reproduction of the problem with instructions

you can add the parameter manually without having "language menu"

flow as follows:

user switched to Arabic -> change query params to  "ui_locales=ar" and the "state=ar-ae" -> enter username and password and login -> redirect back to the redirect URI (English site) -> check the state and redirect the user to the Arabic site.

**Comment by Danieliverant** [comment]
can someone review this problem?

**Comment by Danieliverant** [comment]
any updates?

**Comment by jasonnutter** [comment]
@Danieliverant Sorry this fell through the cracks. 

I'm a bit confused about your issue. The `state` parameter is used by MSAL to mark an individual request, and should be unique per request. Are you saying you are using it to change locales? Can you share some images and urls that demonstrate the problem?

**Comment by Danieliverant** [comment]
> @Danieliverant Sorry this fell through the cracks.
> 
> I'm a bit confused about your issue. The `state` parameter is used by MSAL to mark an individual request, and should be unique per request. Are you saying you are using it to change locales? Can you share some images and urls that demonstrate the problem?

yes, I want to let the user login to the site with the same language he had on the login page.
(you can only have one redirect URI = English site, 
but if the user used the Arabic page in AzureB2C - he should also want to login to the Arabic site)

i.e. English site - ui_locales="en" & state="en-gb"
https://etoropartners.b2clogin.com/etoropartners.onmicrosoft.com/b2c_1_signin/oauth2/v2.0/authorize?response_type=id_token&scope=https%3A%2F%2Fetoropartners.onmicrosoft.com%2Fpartnersapi%2Fuser_impersonation%20openid%20profile&client_id=9c7105c0-57de-4677-95b4-f6be40d25f8a&redirect_uri=https%3A%2F%2Faffiliates.etoro.com%2Fen-gb%2Fdashboard&state=85b19c46-eb25-41de-87b3-63707f2463fe%7Cen-gb&nonce=f3527c0c-6f19-4382-aa1f-236f0c297e24&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=1.0.1&ui_locales=en&fromPortal=true&client-request-id=e5ddf113-c66b-4b63-9152-758dbf9ea2db&response_mode=fragment

after changing ui_locales and state parameter:
Arabic site - ui_locales="ar" & state="ar-ae"

https://etoropartners.b2clogin.com/etoropartners.onmicrosoft.com/b2c_1_signin/oauth2/v2.0/authorize?response_type=id_token&scope=https%3A%2F%2Fetoropartners.onmicrosoft.com%2Fpartnersapi%2Fuser_impersonation%20openid%20profile&client_id=9c7105c0-57de-4677-95b4-f6be40d25f8a&redirect_uri=https%3A%2F%2Faffiliates.etoro.com%2Fen-gb%2Fdashboard&state=85b19c46-eb25-41de-87b3-63707f2463fe|ar-ae&nonce=f3527c0c-6f19-4382-aa1f-236f0c297e24&client_info=1&x-client-SKU=MSAL.JS&x-client-Ver=1.0.1&ui_locales=ar&fromPortal=true&client-request-id=e5ddf113-c66b-4b63-9152-758dbf9ea2db&response_mode=fragment

and now I can know what language the user had on the login page (response.accountState="ar-ae"),
and redirect him to the corresponding site ("/ar-ae/" in this case)

in Chrome it works perfectly, but in IE the "accountState" stays "en-gb" instead of "ar-ae".

**Comment by jasonnutter** [comment]
@Danieliverant With version `msal@1.2.0`, you can now set the redirect uri on a per request basis. This would allow your application to determine which version of the site the user is currently on, and then set and pass that redirect uri directly into the request (each of these urls would need to be registered in the Azure Portal as redirect uris for your application). I think I would recommend try that instead of leveraging the `state` parameter.

You can also try setting `auth.navigateToLoginRequestUrl` to `true`, which would redirect the back to the page they were originally on when they initiated the MSAL request (this works for `loginRedirect` and `acquireTokenRedirect` only).

**Comment by Danieliverant** [comment]
> @Danieliverant With version `msal@1.2.0`, you can now set the redirect uri on a per request basis. This would allow your application to determine which version of the site the user is currently on, and then set and pass that redirect uri directly into the request (each of these urls would need to be registered in the Azure Portal as redirect uris for your application). I think I would recommend trying that instead of leveraging the `state` parameter.
> 
> For example:
> 
> ```js
> const locale = 'ar-ae';
> 
> msal.loginRedirect({
>    // ... other request options
>    redirectUri: `https://affiliates.etoro.com/${locale}/dashboard`
> });
> ```
> 
> You can also try setting `auth.navigateToLoginRequestUrl` to `true` in the configuration for `UserAgentApplication`, which would redirect the back to the page they were originally on when they initiated the MSAL request (this works for `loginRedirect` and `acquireTokenRedirect` only).

Thank you for the response! but it does not exactly answer my case. 

I'm trying to support this behavior:

The user is on the English version of the Login page, 
he doesn't understand English so he switched to Chinese, entered his credentials and presses "login".
now I should redirect him to the Chinese site. 
how can I know what language he had on the login page?

this is why I need the state parameter.

also maintaining the available languages in two places (Azure + the app) is not the best practice for me.
maybe in the future Azure can support some wild card in the redirect URI so I can save only one redirect URI in Azure and control the languages through my app.

**Comment by jasonnutter** [comment]
@Danieliverant Can you clarify if the user is changing language/local on your application page, or on the MS login screen? If the user is changing their language in your application, I'm not sure I understand why couldn't use the redirect URI to keep track of which language they are using.

And unfortunately, I would not expect the Azure portal to support wildcards, due to security concerns.

**Comment by jasonnutter** [comment]
@pkanher617 This looks to be an issue with the B2C login screen.

**Comment by jasonnutter** [comment]
@Danieliverant I believe the root cause of the issue is that the links to change locales don't properly encode the "|" parameter. You'll notice when you initially land on the login screen, the value of the state parameter is 

```
state=85b19c46-eb25-41de-87b3-63707f2463fe%7Cen-gb
```

However, after clicking the link to change languages, it changes to something like:

```
state=85b19c46-eb25-41de-87b3-63707f2463fe|ar-ae
```

I tested this, and it seems to work fine in both Chrome and IE the first time you click the links. The problem comes when you try to change the language a second time. Because the "|" is no longer encoded, the replacement doesn't happen properly, resulting in the state parameter not updating. This seems to happen regardless of browser or language.

Can you please update your logic to properly encode the "|" character (`%7C` is the correct value)? This can be done in JS with

```js
const stateDelimiter = encodeURIComponent("|");
```

**Comment by Danieliverant** [comment]
> @Danieliverant I believe the root cause of the issue is that the links to change locales don't properly encode the "|" parameter. You'll notice when you initially land on the login screen, the value of the state parameter is
> 
> ```
> state=85b19c46-eb25-41de-87b3-63707f2463fe%7Cen-gb
> ```
> 
> However, after clicking the link to change languages, it changes to something like:
> 
> ```
> state=85b19c46-eb25-41de-87b3-63707f2463fe|ar-ae
> ```
> 
> I tested this, and it seems to work fine in both Chrome and IE the first time you click the links (at least, the url updates. It's possible MSAL running in IE does not parse this correctly when the user is sent back to the page). The problem comes when you try to change the language a second time. Because the "|" is no longer encoded, the replacement doesn't happen properly, resulting in the state parameter not updating. This seems to happen regardless of browser or language.
> 
> Can you please update your logic to properly encode the "|" character (`%7C` is the correct value)? This can be done in JS with
> 
> ```js
> const stateDelimiter = encodeURIComponent("|");
> ```

wow... thats embarrassing. I changed the logic and all work now. thank you!

**Comment by jasonnutter** [comment]
You're welcome!
